### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by brenopolanski** [Scirra/Construct-3-bugs#1]
GitHub now supports **issue templates** via a markdown file called `issue_template.md` in the root or `.github/` folder of your repo!

About: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by AshleyScirra** [comment]
Great idea! Didn't know about that feature. On it.

(Well done for finding the repo before I posted it anywhere :P)

**Comment by AshleyScirra** [comment]
Done!
