### ISSUE TITLE
Projects with imported fonts fail to run in Chrome in r66.2

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1001]
## Problem description
Projects containing fonts don't run in Chrome as of r66.2, showing only a black screen and this message in the console: 

`index.html:1 Uncaught (in promise) DOMException: A network error occurred.`

These projects run in Firefox when loaded from local files.

This Chrome issue seems the same as the previously-reported one mOOnpunk pointed to below, so it's a dupe, but I'm adding repro steps and a project to this report anyway since that report didn't have them.

I think my other issue of being unable to load anything saved in the cloud in Firefox is its own bug, and I guess it should have its own report, but it's getting way too late here for me to write another one. I'll get to it tomorrow if it's needed, but it's pretty simple and described below.

## Attach a .c3p

[FontScrewy.zip](https://github.com/Scirra/Construct-3-bugs/files/1453267/FontScrewy.zip)

## Steps to reproduce

1. Create a project in Chrome version of C3.
2. Import a font (i.e. "Pixel_NES.otf", included in the attached project).
3. Preview the project.

## Observed result
The project fails to run in Chrome - the preview window is black, and the following error text appears in the console. The project previews properly in Firefox when loaded from a local file.

```
Registered service worker on https://preview.construct.net/local/
sw.js:46 [SW-Preview] Up to date
editor.construct.net/r66-2/behaviors/physics/c2runtime/box2d.asm.js:9 pre-main prep time: 0 ms
editor.construct.net/r66-2/preview/c2/preview_prelude.js:56 Using WebGL 2 renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0) [Google Inc.]
editor.construct.net/r66-2/preview/c2/preview_prelude.js:56 Max texture size: 16384
editor.construct.net/r66-2/preview/c2/preview_prelude.js:56 Point size range: 1 to 1024
editor.construct.net/r66-2/preview/c2/glwrap.js:404 WebGL extensions:  Array(9)0: "EXT_color_buffer_float"1: "EXT_disjoint_timer_query_webgl2"2: "EXT_texture_filter_anisotropic"3: "OES_texture_float_linear"4: "WEBGL_compressed_texture_s3tc"5: "WEBGL_compressed_texture_s3tc_srgb"6: "WEBGL_debug_renderer_info"7: "WEBGL_debug_shaders"8: "WEBGL_lose_context"length: 9__proto__: Array(0)
index.html:1 Uncaught (in promise) DOMException: A network error occurred.
```

Note: In Firefox I'm unable to open any projects from the cloud. When I try to open projects saved to the cloud in Firefox, nothing appears to happen, but I get this in the Firefox console:

```
TypeError: window is null  WebNavigationFrames.jsm:59:1
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it.  sandbox.html
```

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.89
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
C3 release: r66.2
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 75 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by mOOnpunk** [comment]
See this issue, it sounds like the same thing. https://github.com/Scirra/Construct-3-bugs/issues/994

**Comment by Scoremonger** [comment]
Awesome, thanks mOOnpunk, I don't know how I overlooked that but thanks for pointing it out. Yes, that's exactly what this is. Even though mine's a dupe I'll upload a project and repro steps.

**Comment by Scoremonger** [comment]
Oh, I see in the massive comments below your report this was resolved, haha. Closing this one. Thanks.
