### ISSUE TITLE
Can't open projects from OneDrive in Firefox

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1002]
## Problem description

When I try to open any project from the cloud (OneDrive in my case), it fails silently. Construct itself doesn't appear to do anything, but there is an error message in the console that appears before I try to load that might have something to do with this.

## Attach a .c3p

I get this with any project stored in OneDrive, so an example wouldn't help.

## Steps to reproduce

1. Open Construct in Firefox.
2. Click the "CLOUD" button to load a project from the cloud.
3. Select a project from OneDrive and open it.

## Observed result

Nothing happens - the file browser closes as usual, but the project doesn't load. In the web console, I see the following:

```
"Registered service worker on https://editor.construct.net/r66-3/"  main.js:167
TypeError: window is null  WebNavigationFrames.jsm:59:1
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it.
```

Note: I can load the same projects just fine in Firefox if they are local files. Chrome cloud loading seems fine too.

## Expected result

Project should load normally.

## Affected browsers

* Chrome: no
* Firefox: yes
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 56.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
C3 release: r66.3
Language setting: en-US
Local storage

Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    UI animations are disabled in Firefox due to bug 1354501
    CSS containment is not supported. Editor performance may be significantly degraded.
    The <dialog> element is not supported. A polyfill is in use.
    This browser does not support pluralisation rules. Plural forms may not be correct.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    Persistent storage is not available. Local storage could be deleted by the browser.
    Storage quota estimate is unavailable.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_texture_filter_anisotropic
    EXT_disjoint_timer_query
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context
    MOZ_WEBGL_lose_context
    MOZ_WEBGL_compressed_texture_s3tc

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Well "TypeError: window is null  WebNavigationFrames.jsm:59:1" seems completely unrelated to C3, so that's probably a browser plugin your using?

I'm not 100% sure about this yet but OneDrive is returning a redirect, which I think it isn't allowed to do in this situation according to the HTTP spec. Chrome doesn't seem to care about this, but Firefox does. I might be able to work around this, but the OneDrive specification is a bit of a labyrinth.

**Comment by shortercode** [comment]
Okay I've put a workaround in for this, should be fine in the next release.
