### ISSUE TITLE
When adding a local variable and setting static in the dialog, it will not be added static

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1003]
## Problem description

When you enter a variable and then in the first dialog set static to true, it will not be set.
This has led so some weird bugs in my game, but i discovered it now

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
There is no need for a Project as it should happen in any event sheet

## Steps to reproduce

1. add a local variable with "v" (tried it inside a group)
2. set static to true in the initial dialogue
3. notice the variable is not static

## Observed result

see Steps

## Expected result

see Steps

## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by tunepunk** [comment]
Can confirm. When you add a local variable and choose static, it doesn't become static. You have to edit the variable again, and again check the static box to get the variable to be static.

**Comment by AshleyScirra** [comment]
Thanks, fixed for r67.
