### ISSUE TITLE
Project window family item handling. (Usability issue)

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1004]
## Problem description

Families is something that I use quite a lot and noticed a bit of annoyance working with families.
This is not a bug but more of an enhancement or usability issue. Adding and removing stuff to families feels a bit clunky at times. Especially when you compare it to how you are able to drag and drop items into object subfolders which is very straightforward and feels natural.

**Current functionality:** 
The only way to add or remove objects from families is to right click the family and choose edit family. Always opening this dialogue doesn't feel very natural, and a bit clunky at times.

**Suggested additional functionality:**

* Drag and drop: Dragging an object directly to the family could add it to the family. Just the way you can drag and drop an object to a subfolder.

* Adding from Context menu: Right click an object that is not in a family > Add to family > (Display list of families)

* Removing something from a family: Right click object in the family > Remove from family >  (Display list of families where this object is a member)

This is more a usability issue that would make editing family members feel a bit more fluent and natural, as sometimes I find myself trying to do the above suggested methods although there is no such functionality at the moment.

## Attach a .c3p

N/A

## Steps to reproduce

1. Try to add an object to a family by dragging and drop.
2. Try to add or an object to a family by right clicking and select add to family.

## Observed result

The only way to add or remove objects from a family is by using the "edit family" dialogue.

## Expected result

More fluent ways to add and remove objects from families.

## Affected browsers

* Chrome: yes

**Comment by tunepunk** [comment]
I just noticed that you there is an option to remove from family If the family has more than 1 object.  So the option to remove was already there, but still looking for more ways to add items to a family.

**Comment by shortercode** [comment]
Okay these 2 options should now work in r68 ( when it's released ). 

The context menu only works for single items, but drag n drop works with as many as you have selected. If an object is the wrong plugin or already in a family the option wont appear in the context menu. If there's a parameters naming collision it will appear, but trying to add it will show a warning dialog and it won't be added to the family. I think this is all sensible, but let me know if anything seems obviously weird.

**Comment by tunepunk** [comment]
Thanks! I'll take a look at it when r68 is out.

**Comment by tunepunk** [comment]
Really great addition!! Works well. Only one option that I'm missing that I just thought of. Not a biggie but would be useful.

When you right click a sprite to add it to a family. The option '+ New Family' in the list as well. Would be a great addition, and it would open the regular add dialogue?

If there's no families in project, it would just show this option. '+ New Family' and the sprite you right clicked on would be automatically added to the new family.

That way we will have yet another handy way to instantly create families as well.

Thanks for a great update.

**Comment by shortercode** [comment]
Okay I'll reopen until I can look at trying that other idea out!

**Comment by AshleyScirra** [comment]
Added the 'Create new family' option for r72.
