### ISSUE TITLE
Properties Bar Cannot Be Snapped, Project Crashed Cannot Open

### ISSUE THREAD

**Issue by Madsoggytoast** [Scirra/Construct-3-bugs#1007]
## Problem description

As i was building in Construct 3, I wanted to change view of properties bar. After doing this, I was unable to snap it where I wanted. Things went south from there. I decided to just close and refresh. Then, upo trying to open my project, I got the following error.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Select view of bars, and remove the properties bar
2. Try to bring the properties bar back in
3. It will not allow me to drag to side.

## Observed result

It only lets me drag the size, not snap the properties bar

## Expected result

I expected to be able to just snap ot back where it originally was when I opened it.

## Affected browsers

* Chrome: idk
* Firefox: yes
* Edge: idk
* Safari: idk

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information

Type: unhandled exception
File: https://editor.construct.net/r66-3/main.js, line 2, col 0
Message: NS_ERROR_NOT_IMPLEMENTED:
Stack: L/this.ǃcb_@https://editor.construct.net/r66-3/main.js:2:84964 n@https://editor.construct.net/r66-3/main.js:2:89330 d@https://editor.construct.net/r66-3/main.js:2:89543 getEntries@https://editor.construct.net/r66-3/main.js:2:90150 ǃZO/ Construct 3 version: r66.3
URL: https://editor.construct.net/
Date: Mon Nov 13 2017 16:44:11 GMT-0500 (Eastern Standard Time)
Uptime: 20.9 s
Platform information

Browser: Firefox
Browser version: 56.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
C3 release: r66.3
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon(TM) R7 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, EXT_disjoint_timer_query, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, MOZ_WEBGL_lose_context, MOZ_WEBGL_compressed_texture_s3tc
[Tap Survivor Construct 3.zip](https://github.com/Scirra/Construct-3-bugs/files/1468738/Tap.Survivor.Construct.3.zip)

</details>

**Comment by shortercode** [comment]
I can't seem to replicate this, does this always happen for you when you repeat the replication steps?

**Comment by shortercode** [comment]
Been nearly a month since I requested information so I'm closing this as abandoned. Please file a new bug with the requested information.
