### ISSUE TITLE
.c3addon not working on Construct3 beta MacBook Pro

### ISSUE THREAD

**Issue by pompart** [Scirra/Construct-3-bugs#1008]
## .c3addon not working on Construct3 beta

After compressing (Making a Zip file) the file that includes [common.js, editime.js, PluginIcon.ico, runtime.js] I change the extension to .c3addon. I go to import into construct3 beta. Then it gives me this message. 

                "Failed to install the add-on. Check the browser console for details."

I tried to upload the .c3p and It won't upload either.

* Chrome:no
* Firefox:no
* Edge:I don't know
* Safari: yes

## System details
MAcBook pro lastest iOS

**Comment by shortercode** [comment]
This bug will likely be closed, please take a look at our [guidelines](https://github.com/Scirra/Construct-3-bugs/blob/master/README.md). 

Github doesn't allow the upload of files with extensions it doesn't know. You can get around this by uploading c3p and c3addon files inside a zip file, or by changing the extension to ".zip".

**Comment by AshleyScirra** [comment]
Check the browser console for a more detailed error message, as it suggests. We can't help without more information.
