### ISSUE TITLE
[r19] Unidentified crash on closing project

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#101]
## Problem description

Was just doing casual stuff like add random events, duplicate layouts, create a sprite. Then when closing project it crashes for no reason. Cannot reproduce.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: TypeError: Cannot read property 'ǃeR' of null
Stack: TypeError: Cannot read property 'ǃeR' of null at a.ǃM.ǃl (https://editor.construct.net/r19/plugins/sprite/plugin.js:1:5028) at te.ǃl (https://editor.construct.net/r19/main.js:61:204157) at te.ǃl (https://editor.construct.net/r19/main.js:61:210245) at ne.ǃl (https://editor.construct.net/r19/main.js:61:157842) at ye.ǃl (https://editor.construct.net/r19/main.js:61:76308) at De.then.$e (https://editor.construct.net/r19/main.js:153:27621)
Construct 3 version: r19
URL: https://editor.construct.net/index.html
Date: Wed Apr 19 2017 00:04:05 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 874 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
This is related to #57

This must be another case of a sprite that is created but is not initialized properly.

**Comment by shortercode** [comment]
Replication:
1. create new project
2. add sprite
3. duplicate layout
4. close project

@DiegoScirra best guess is that the layout duplication path isn't calling OnCreate like we added for cloning the Object

**Comment by DiegoScirra** [comment]
@shortercode Yeah, it must be that.

**Comment by DiegoScirra** [comment]
Fixed in r19.
