### ISSUE TITLE
Dragging a sprite to animation editor issue

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#1010]
## Problem description

Simply, the item dragged to animation editor doesn't appears on the frame, but appears on the layout.

## Attach a .c3p

[AXE JUGGLING.zip](https://github.com/Scirra/Construct-3-bugs/files/1472324/AXE.JUGGLING.zip)

## Steps to reproduce

1. Open construct
2. Create a sprite
3. Drag any image to the frame window.
4. the item doesn't appear

## Observed result

Item appears outside frame editor

## Expected result

Add item to the frame.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r68.
