### ISSUE TITLE
Crash after failing to run project and then saving it (once)

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1013]
## Problem description

I opened my project from One Drive, changed the name of a local variable in a function, added a "set position" action in another event sheet, tried to run several times (nothing happened - no preview window appeared, nothing), hit the save button to save to One Drive, and Construct crashed. Naturally, I can't reproduce this.

It might be unrelated, but the first time I tried to browse to the project in the cloud, before this crash, Construct gave me a message saying it was unable to refresh the window. I hit the refresh button and it worked the second time. That's happened before with no subsequent issues, but I thought I'd mention it.

## Attach a .c3p

If I discover a way to reproduce it, I'll upload a project.

## Steps to reproduce

1.
2.
3.

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: {"response":"\n\n\n

</details>

**Comment by shortercode** [comment]
Best guess was this is related to a networking problem ( intermittent connection or similar )... but I'm not really sure I can guess what happened here! I'd like to think the crash is more likely part of the preview code, but could be either or something completely unrelated. You got any hints yet?

**Comment by Scoremonger** [comment]
Sorry, no, I've got nothing. I expect you're right about the preview being the problem though, since I've never had it completely fail this way before or since.

**Comment by shortercode** [comment]
Okay well I think there's a problem with the preview loading occasionally, so it might be related to that. Until we get something solid I'm going to close this, but thanks for giving us some conditions, it might help us figure it out eventually!
