### ISSUE TITLE
Sprite Editor: Drag not working

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1014]
## Problem description

*Enter a concise description of your problem here*
In the Sprite Editor i cannot drag the screen with middle mouse / space when the mouse is over the Sprite Editor Window.

If i press Middle Mouse shortly so i could normally drag without holding Middle Mouse, i can drag when the Mouse is outside of the Sprite Editor Window.

(i use Dark Theme if that's important)

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Create Sprite
2. Try to drag
3. Press Middle Mouse shortly
4. Notice you can drag only outside the Sprite Editor Window

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r68
