### ISSUE TITLE
C3 does not have an id for the main canvas compared to c2

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1015]
## Problem description

Trying to execute some javascripts on the main canvas proved to be really hard since it does not have the id that C2 has. Can this please be added? I'm porting some projects and I really have a problem with this.

## Attach a .c3p

![image](https://user-images.githubusercontent.com/7268697/32964380-bb665b2e-cbdb-11e7-8059-1e0c7fd5fb01.png)

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r67
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 681 mb (9.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by newman321** [comment]
Are you going to use couple of canvases in same page ? if not you can choose canvas by its tag and if yes you can choose it by its properties like width and height

**Comment by shortercode** [comment]
I'm not sure if there was a reason for this or not, so will @AshleyScirra to respond to this. However,
```javascript
    const canvas = document.querySelector("canvas");
```
Should work fine for your purpose, as @newman321 says.

**Comment by AshleyScirra** [comment]
Yeah, it's the only canvas in the DOM, so there's not much point giving it an ID. Just use the `canvas` selector or `getElementsByTagName` instead. That would work in the C2 runtime too.

**Comment by JeFawk** [comment]
So much for porting games without problems.

**Comment by AshleyScirra** [comment]
You could always add back the id on startup to ensure it's backwards compatible with anything that expects the ID to be there.

**Comment by JeFawk** [comment]
Pretty manual, I'd use it but I just expected the elements to have the same IDs in C3 as in C2.
