### ISSUE TITLE
Error importing image

### ISSUE THREAD

**Issue by wiverson** [Scirra/Construct-3-bugs#102]
## Problem description

Drag and dropped a PNG into the Animations section of the image editor

## Attach a .c3p

Crashed before I could save anything.  See repro steps.

## Steps to reproduce

1. Create new empty project
2. Create Sprite
3. Drop an image into the Sprite -> Image Editor -> Animations.

## Observed result

I got the error message below.

## Expected result

To have a animation created based on the image I dragged in.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: ReferenceError: blob is not defined
Stack: ReferenceError: blob is not defined at ǃB.ǃpH.ǃB.ǃpH.ǃB.ǃvu.then.de (https://editor.construct.net/r19/main.js:61:181273)
Construct 3 version: r19
URL: https://editor.construct.net/
Date: Tue Apr 18 2017 15:56:37 GMT-0700 (PDT)
Uptime: 1069.3 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M290X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context</details>

**Comment by DiegoScirra** [comment]
Fixed in r20.

Thanks for reporting this one!
