### ISSUE TITLE
Preview broken when offline

### ISSUE THREAD

**Issue by tommakesgames** [Scirra/Construct-3-bugs#1020]
## Problem description
Projects that previewed fine before no longer working in preview when offline. 
Days left on authentication, no changes made since I went offline.

Result is black screen with no reading of input.

## Attach a .c3p

Done with several projects for testing - all get the same result. Disabled all events to check is wasn't faulty logic, but still get the same result.

i.e. nothing moving or responding, no behaviours, just a background colour to screen still results in black screen.

## Steps to reproduce

1. Go offline
2. Open any project
3. Run it.

## Observed result

Black screen.

## Expected result

See my game run.

## Affected browsers

* Chrome: yes

## System details

No crash report.

Macbook Pro 14,1 running MacOSX 10.12.6

**Comment by AshleyScirra** [comment]
Can't reproduce here, preview works fine when offline. You need to wait until the "ready to work offline" notification appears before everything will work offline. If your steps to reproduce do not include waiting for that notification to appear, all I can assume is that you closed C3 before it was ready to work offline.
