### ISSUE TITLE
Advert object makes my game crush

### ISSUE THREAD

**Issue by blindcrowgames** [Scirra/Construct-3-bugs#1021]
## Problem description

I’m trying to build my game with Advert. But when the APK is installed and I run the game, the screen goes black (is not a hardware error, because I can still use notifications bar or close de app). This is happening when I add Advert Object (construct admob plugin) to my project if I remove it, the video game runs excellent. 

## Attach a .c3p

https://www.dropbox.com/s/phvyhd3ei6wfmay/admobtest_bug.c3p?dl=0

## Steps to reproduce

1. Created AdMob account
2. Set payments method in Admob
3. Created App (android)
4. Created Interstitial
5. Interstitial ID
6. Copied App ID

On C3 (Only Android):

7. Created Advert Object
8. Paste my App ID
9. Tilt Test box
10. Event: On Load Complete -> Create Interstitial advert: ID: "my_Interstitial_ID" / Show: False
11. Event: On object touched -> Show Interstitial Advert

Export (Android)

12. Exported Android Studio Project
13. Exported Cordova Project

Building:

14. Opened Android Studio Project
15. Plugged my Samsung Galaxy Tab A6
16. Build on device -> App installed

AND

17. On Terminal (mac): went to cordova project location
18. $ cordova platform add android
19. $ cordova build
20. Copy APK builded to my Samsung Galaxy Tab A6.

## Observed result

After install the APK (both builds), on app start the screen of my tablet goes black forever (not hardware crush, only the app sustain that black, but I can still close it without any problem or display notifications).

If I remove advert object (construct Admob Plugin) from my project at C3, the game runs perfectly.

## Expected result

Game runs correctly and show interstitial test when I touched the object.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

It's not a browser problem.

## System details

There is no System crush report, the game just no run.

<details><summary>View details</summary>

</details>

**Comment by shortercode** [comment]
Well I've just tried this on my test device and it seemed to work fine when run via android studio. I see the C3 loading bar, then a red square appears. Pressing the red square doesn't do much, but by the looks of your project you set it not to show the interstitial anyway.

Could you attach the chrome debugger to your device and tell me if there's any errors in the console?

What version of Android are you running?

**Comment by blindcrowgames** [comment]
I will try the chrome debbuger. 

I’m using samsung galaxy tab A6 with android 7.0.

I put false on creation of interstitial but when you touch the object must show it. 

I’m going to to send you the .apk build.

**Comment by blindcrowgames** [comment]
<img width="1280" alt="screen shot 2017-11-20 at 6 57 10 pm" src="https://user-images.githubusercontent.com/33832212/33043763-41982344-ce25-11e7-81e1-cf717ef9adc9.png">

This is a screenshot of Chrome Console when I'm trying to open up the .APK in my tablet.

[advert_test.apk.zip](https://github.com/Scirra/Construct-3-bugs/files/1489278/advert_test.apk.zip)

And I'm attaching APK build, too.

Please let me know what do you think. Thank you once again.

**Comment by shortercode** [comment]
Are you using minification when building?

**Comment by blindcrowgames** [comment]
<img width="528" alt="screen shot 2017-11-21 at 9 44 33 am" src="https://user-images.githubusercontent.com/33832212/33073171-c918aa84-cea0-11e7-8b1a-e8ebdb82e24a.png">

Do you mean minification at Construct's export options? 

Here is the Cordova Project exported with NO minification

[admobtest_no_minification.zip](https://github.com/Scirra/Construct-3-bugs/files/1491345/admobtest_no_minification.zip)


And here is the APK builded by Cordova:

[admobtest_no_minification.apk.zip](https://github.com/Scirra/Construct-3-bugs/files/1491348/admobtest_no_minification.apk.zip)

I've tried the APK in my tablet now and IT WORKS! but test ads doesn't shown yet.

**Comment by AshleyScirra** [comment]
It's a minify bug with the advert plugin. The plugin has modified the standard SDK and broken its normal minify-proofing with these lines:

```js
var CNDS = cr.plugins_[NAME].prototype.cnds;
var ACTS = cr.plugins_[NAME].prototype.acts;
```

`NAME` has switched from dot syntax to bracket syntax, so is no longer minified correctly like other plugins.

**Comment by shortercode** [comment]
The reason why the ad isn't being shown is because you never actually create the interstitial advert, the condition your using "on load complete" is part of the game saves system ( not the layout startup ).

Working on the minification issue now, should be a patch for the next release.

**Comment by shortercode** [comment]
Okay fixes are done, can you please check again in r69 when it's released.

**Comment by blindcrowgames** [comment]
Indeed, I changed "on load complete" and now test ads are shown! Thank you so much for your help, I really appreciate that. I'm waiting for next release then.

**Comment by shortercode** [comment]
No problem :)
