### ISSUE TITLE
Events: Bug when selecting Action with Shift that has been Pasted there.

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1024]
## Problem description

See Steps to reproduce

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce
This bug is pretty bizarre, i dont know all the conditions for it, but it worked (the bug worked) for me like this. (Dont know if it happens also if you do it differently)

in the uploaded project it works in Event 3 and 4. (You have to copy&paste the last event before it works)

1. Open New Project
2. Add a Group (dont know if this is needed)
3. Add any Condition (= First Condition)
4. Add any Action to that Condition (should maybe add 2 or more)
5. add a blank Subcondition (= Subevent)
6. copy actions to the blank Subevent
7. Copy an Action to the end of the First Condition
8. Select the first Action of the First Condition
9. Hold Shift and select all Actions of the First Condition
10. See that the Actions of the Blank Subevent are also selected (= Bug)

I think maybe you need to have several Subevents and maybe always copy the actions of the first to the other actions
[asdasfasf.zip](https://github.com/Scirra/Construct-3-bugs/files/1492126/asdasfasf.zip)

## Observed result

*What do you see happen?*
Actions of the SubEvent are also selected

## Expected result

*What did you expect to happen instead?*
Actions of the SubEvent are not selected

## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, I could reproduce and it turned out there was some inconsistent handling of range selections in the event sheet view. Should be fixed in the next build.
