### ISSUE TITLE
Origin: When adding new Sprite then Resizing with Top-Left then setting Origin, the Origin won't be set

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1027]
## Problem description

*Enter a concise description of your problem here*
see steps to reproduce

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. add a new sprite (will open 250x250 sprite)
2. Resize Sprite to 64x64 (Align Top-Left)
3. Set Origin to Middle
4. Exit Sprite Editor - Notice the Origin is not in the Middle

## Observed result

*What do you see happen?*
Origin is not in the Middle

## Expected result

*What did you expect to happen instead?*
Origin is in the Middle

## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Can't reproduce this one with the steps provided, everything is working fine.

Tried the steps from a new empty project.

On step 3) I tried setting the origin with the pointer and using the quick assign keyboard shortcut. Everything seemed to work fine in both cases.

@Leralasss Maybe you are doing something extra that you haven't mentioned.

**Comment by Leralasss** [comment]
I meant set Origin with Quick Assign yes.

I tried it now and it also doesn't work.. If it happens again i'll try to find more circumstances
