### ISSUE TITLE
Tilemap panel error: "invalid grid cell coordinate"

### ISSUE THREAD

**Issue by toby56** [Scirra/Construct-3-bugs#103]
## Problem description

I tried the tile map panel and found out that anything including clicking, resizing or even hovering over it triggered "invalid grid cell coordinate" error.

## Attached .c3p as ZIP

[Pixel.zip](https://github.com/Scirra/Construct-3-bugs/files/931612/Pixel.zip)

## Observed result

Instant Crash

## Expected result

Tilemap panel working.

## Affected browsers

* Chrome

## Error report information
* Type: assertion failure
* Message: invalid grid cell coordinate
> Stack: Error at Function.ǃB.ǃiGe (https://editor.construct.net/r19/main.js:2:225259) at ie
(https://editor.construct.net/r19/main.js:2:195750) at window.assert (https://editor.construct.net/r19/main.js:2:196175) at u.ǃLs (https://editor.construct.net/r19/components/bars/tilemapBar/tilemapBar.js:1:2704) at u.window.ǃOn.ǃCR (https://editor.construct.net/r19/components/bars/tilemapBar/tilemapBar.js:1:13432) at HTMLDocument. (https://editor.construct.net/r19/main.js:2:278783)
* Construct 3 version: r19
* URL: https://editor.construct.net/index.html
* Date: Wed Apr 19 2017 12:41:11 GMT+1000 (AUS Eastern Standard Time)
* Uptime: 33.1 s

* Platform information
* Browser: Chrome
* Browser version: 57.0.2987.133
* Browser engine: Blink
* Browser architecture: 64-bit
* Context: webapp
* Operating system: Windows
* Operating system version: 10
* Operating system architecture: 64-bit
* Device type: desktop
* Device pixel ratio: 1
* Logical CPU cores: 4
* User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

> WebGL information
> Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
> Numeric version: 2
> Supports NPOT textures: yes
> Vendor: Google Inc.
> Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
> Major performance caveat: no
> Maximum texture size: 16384
> Point size range: 1 to 1024
> Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by toby56** [comment]
Was becuz the image was small than the tile size!

**Comment by AshleyScirra** [comment]
It still shouldn't crash. Reopening.

**Comment by DiegoScirra** [comment]
Fixed in r20.

I also a added a small warning message to the tilemap bar when the source image is not shown because of this kind of instance properties misconfiguration.
