### ISSUE TITLE
R69 can no longer save download project

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#1030]
## Problem description

Since updating every time i click to save, download file (download to computer) i get an error message.

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃL.ǃi (https://editor.construct.net/r69/main.js:2:180041) at Function.ǃL.ǃEQ (https://editor.construct.net/r69/main.js:2:190602) at window.ǃqTN.ǃjn (https://editor.construct.net/r69/main.js:167:39525) at 
Stack: TypeError: unexpected type at Function.ǃL.ǃi (https://editor.construct.net/r69/main.js:2:180041) at Function.ǃL.ǃEQ (https://editor.construct.net/r69/main.js:2:190602) at window.ǃqTN.ǃjn (https://editor.construct.net/r69/main.js:167:39525) at 
Construct 3 version: r69
URL: https://editor.construct.net/
Date: Thu Nov 23 2017 15:09:21 GMT+0000 (GMT)
Uptime: 446.1 s

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r69
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

I dont even have to edit, just load up file and click save as, download file, the file it just wont save.

## Observed result

get above error message

## Expected result

should save to downloads folder on computer

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r69
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 38 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Yup can confirm, I've fixed for next release.

**Comment by shortercode** [comment]
Okay r69.2 has gone out now, should have fixed this!

**Comment by AshleyScirra** [comment]
Should be working now, please let us know if anything is still wrong.
