### ISSUE TITLE
R69 cannot open an image from file in Animations Editor

### ISSUE THREAD

**Issue by esowe** [Scirra/Construct-3-bugs#1031]
## Problem description

*Enter a concise description of your problem here*
Construct 3 R69 crashes when an image file is opened in the animations editor.
## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
An empty project is enough to reproduce this, se below.

## Steps to reproduce

1. Create a new empty project
2. Insert a new sprite object to the layout
3. In the animations editor, select the "Load an image from a file" icon.
4. Select an image file (I have only tested with png files) and press Open in the dialog.

## Observed result

Construct 3 crashes immediately when Open is pressed.

## Expected result

The image should have been opened and shown in the Animations Editor.

## Affected browsers

* Chrome: yes
* Firefox: unknown
* Edge: unknown
* Safari: unknown

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Identifier 't' has already been declared @ SyntaxError: Identifier 't' has already been declared at e.ǃ$zK.ǃ$gp (https://editor.construct.net/r69/main.js:73:211793) at 
Stack: SyntaxError: Identifier 't' has already been declared at e.ǃ$zK.ǃ$gp (https://editor.construct.net/r69/main.js:73:211793) at 
Construct 3 version: r69
URL: https://editor.construct.net/index.html
Date: Thu Nov 23 2017 16:20:14 GMT+0100 (Västeuropa, normaltid)
Uptime: 30.3 s

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r69
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by esowe** [comment]
I have now tested this i Chrome 62.0.3202.84 on Android 6.0.1 and get exactly the same result.

**Comment by TheBl4ckSh33p** [comment]
When I try to import images from a strip I get a crash:

Error report information
Type: unhandled rejection
Reason: Error: Identifier 'e' has already been declared @ SyntaxError: Identifier 'e' has already been declared at e.ǃ$Cr.ǃ$Kh (https://editor.construct.net/r69/main.js:73:323938) at 
Stack: SyntaxError: Identifier 'e' has already been declared at e.ǃ$Cr.ǃ$Kh (https://editor.construct.net/r69/main.js:73:323938) at 
Construct 3 version: r69
URL: https://editor.construct.net/index.html
Date: Thu Nov 23 2017 16:42:49 GMT+0100 (Mitteleuropäische Zeit)
Uptime: 50.9 s

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r69
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by shortercode** [comment]
We're looking at this now, it seems to be build related.

**Comment by shortercode** [comment]
r69.2 has just been released, the issue should be fixed.

**Comment by esowe** [comment]
Thanks! I can confirm that it works for me too.
