### ISSUE TITLE
Light theme: cannot read on remote preview

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1032]
## Problem description

![image](https://user-images.githubusercontent.com/7268697/33182560-39d4bba4-d07d-11e7-91c6-17c80c124771.png)

I keep running into windows that i can't read anything from.

* Chrome: yes
## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r69
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 379 mb (5.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by JeFawk** [comment]
Since I'm talking about the remote preview, could something be done to minimize the window keeping the preview running while I could use the editor to implement fixes? (and then start the preview again)

**Comment by shortercode** [comment]
@JeFawk If you drag the dialog out of the main window it should go into its own popup window.

Slightly roundabout way of doing it, but that window can be minimised!

**Comment by JeFawk** [comment]
Ohh cool thanks!

**Comment by JeFawk** [comment]
A scroll bar would be useful, I couldnt find the request video button and randomly resized the frame.

**Comment by JeFawk** [comment]
![image](https://user-images.githubusercontent.com/7268697/33183025-e383917e-d07e-11e7-818b-3c90562cce23.png)
Was something like this at the beginning

**Comment by shortercode** [comment]
I think that's down to the them again, I have a scrollbar on mine (default theme) when I reduce it's height.

**Comment by Animmaniac** [comment]
This is related to some other problems. The theme is currently missing some styles that affect some types of dialogs. I think I fixed it for the next theme release, just need to test it thoroughly to make sure it doesn't break other obscure dialogs.

The scroll and request video link are working normally.
