### ISSUE TITLE
Layer locking stuck, only one layer unlock at a time available

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#1034]
## Problem description

*Can't unlock more than one layer*

## Attach a .c3p

*https://www.dropbox.com/s/0yg23rk6xopg734/can%27t%20unlock%202%20or%20more%20layers.c3p?dl=0*

## Steps to reproduce

1.Try to unlock more than one layer by clicking on the locks
2.Can't
3.Sadface :(

## Observed result

*Construct not allowing me to unlock more than one layer*

## Expected result

*Construct allowing me to unlock more than one layer*

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
It's because 'Show translucent inactive layers' is enabled on the layout. It appears to deliberately lock the other layers, which C2 did not do. This is Diego's code so assigning to him.

**Comment by DiegoScirra** [comment]
Fixed in r70
