### ISSUE TITLE
Add "Is timer running" condition

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#1036]
## Problem description

I noticed in the timer behaviour that there is currently no way to retrieve the name (tag) of a timer that is running.

You have a condition "on timer", but that only fires once when the timer ends, and you cant use compare two values because you only have "current time, duration and total time".

I need a way to get the name of timer thats running. It would be helpful it you could add this.

Thanks.

## Observed result

cant get name of timer running

## Expected result

would be helpful to be able to.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Also you can add multiple timers with one behavior, so it doesn't make much sense to only provide one timer expression.

Perhaps you want a "Is timer running" condition instead?

**Comment by mOOnpunk** [comment]
yes "is timer running (tag)"

**Comment by AshleyScirra** [comment]
Added for r75.
