### ISSUE TITLE
Undo Delete Instance Causing C3 to Crash (R69.2)

### ISSUE THREAD

**Issue by angelo-lopez** [Scirra/Construct-3-bugs#1038]
## Problem description
Saving after Undo Delete Instance Causes C3 to Crash on R69.2.
C3 would sometimes crash immediately after undoing a delete operation.

## Attach a .c3p
Was able to reproduce with any of my projects. Can also reproduce with "Kiwi Story".

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Delete an object instance.
2. Undo the delete instance.
3. Save project (C3 sometimes crashes immediately after undoing a delete instance).

## Observed result

C3 crashes.

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*
C3 should continue working after the undo operation.

## Affected browsers

* Chrome: Yes.
* Firefox: Not tested.
* Edge: Not tested.
* Safari: Not tested.

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: this.ǃvao is not a function @ TypeError: this.ǃvao is not a function at window.ǃsgR.ǃdl (https://editor.construct.net/r69-2/main.js:167:45549) at a.ǃst (https://editor.construct.net/r69-2/components/misc/mainMenu/mainMenu.js:1:10071)
Stack: TypeError: this.ǃvao is not a function at window.ǃsgR.ǃdl (https://editor.construct.net/r69-2/main.js:167:45549) at a.ǃst (https://editor.construct.net/r69-2/components/misc/mainMenu/mainMenu.js:1:10071)
Construct 3 version: r69.2
URL: https://editor.construct.net/index.html
Date: Fri Nov 24 2017 21:54:05 GMT+0000 (GMT Standard Time)
Uptime: 272.7 s

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r69.2
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by angelo-lopez** [comment]
Crash happens when selecting an instance to  "undo delete instance" from the Undo button on the toolbar.

**Comment by DiegoScirra** [comment]
Fixed in r70
