### ISSUE TITLE
Error creating an object at a mistyped position

### ISSUE THREAD

**Issue by Lobo93** [Scirra/Construct-3-bugs#104]
## Problem description

Construct 3 crashes when you try to create an object at a mistyped Mouse position

## Attach a .c3p

[Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/934165/Bug.zip)

## Steps to reproduce

1. Create an empty project
2. Add the Mouse object to the project
3. Add any event to the event sheet (in the example I chosethe 'Every tick' event)
4. Add the 'System: Create object' action to the previously created event
5. on the 'X' parameter of this action, type: 'Mouse.Xmouse.'

## Observed result

Construct 3 crashes

## Expected result

The editor would alert the user about an invalid parameter instead of crashing

## Affected browsers

Tested on Chrome 57.0.2987.133 (64-bit)

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r19/main.js, line 61, col 154729
Message: Uncaught Error: behaviors not supported
Stack: Error: behaviors not supported at ne.ǃBDQ (https://editor.construct.net/r19/main.js:61:154735) at ǃB.ǃBo.ǃau.ǃEP$.ǃEoz (https://editor.construct.net/r19/main.js:140:112595) at ǃB.ǃBo.ǃau.ǃEP$.ǃEge (https://editor.construct.net/r19/main.js:140:111078) at window.ǃEPu.ǃEgf (https://editor.construct.net/r19/main.js:140:93764) at window.ǃEPu.ǃEPU (https://editor.construct.net/r19/main.js:140:93369) at HTMLDivElement.ǃEP_.ǃaZ.oninput.oe (https://editor.construct.net/r19/main.js:140:91151)
Construct 3 version: r19
URL: https://editor.construct.net/index.html
Date: Wed Apr 19 2017 09:18:18 GMT-0300 (Hora oficial do Brasil)
Uptime: 308.3 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r20.
