### ISSUE TITLE
cant connect to host with multiplayer plugin when user is not in same network as host

### ISSUE THREAD

**Issue by newman321** [Scirra/Construct-3-bugs#1043]
## Problem description

im facing exactly this problem : 
https://www.scirra.com/forum/multiplayer-tutorial-help-thread_t99532?sid=a0f42d612329e3a0f6b2fdc77c08d4b6
## Attach a .c3p

construct 2 Multiplayer game example 

## Steps to reproduce

1.connect as host
2. open game with another device on a network other than the one host joined with
3.peer can not connect to host

## Observed result

peer can not connect to host

## Affected browsers

* Chrome: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's not a bug, it's just not all combinations of direct peer connections between two devices are possible, due to the architecture of the Internet.

**Comment by newman321** [comment]
Direct peers connection ? Its just one peer and one host each on different isp’s

**Comment by newman321** [comment]
I also cant open remote preview when user is on different isp than me.

**Comment by newman321** [comment]
@AshleyScirra i just added a TURN server and now it seems to work fine just wanted to share that there are free TURN servers like STUN servers and its not a necessity to pay for TURN server
