### ISSUE TITLE
Cordova export: update android-versionCode

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#1044]
A user has reported that they cannot update an existing APK without manually editing config.xml to insert android-versionCode: https://www.scirra.com/forum/cordova-versioncode_t198150

If possible we should automatically update this so manual modifications aren't necessary.

**Comment by shortercode** [comment]
I'm pretty sure versioncode is optional, cordova generates an android version code using the the version number. Only issue with this is that it only understand 3 value version numbers and we use 4 value. It actually ignores the 4th value completely. I did make an adjustment to prevent 4 value version numbers from being valid in the cordova exporter, but it was removed as it broke compatibility with other exporters.

**Comment by shortercode** [comment]
> To change the version code for your app's generated apk, set the android-versionCode attribute in the widget element of your application's config.xml file. If the android-versionCode is not set, the version code will be determined using the version attribute. For example, if the version is MAJOR.MINOR.PATCH:
> `versionCode = MAJOR * 10000 + MINOR * 100 + PATCH`

**Comment by AshleyScirra** [comment]
Ah. But could we not generate an android-versionCode ourselves taking in to account the fourth number?

**Comment by shortercode** [comment]
I guess, apparently 2100000000 is the maximum value for the versioncode. It would dramatically change the versioncode relative to any older builds, I'm not sure if that'll have any consequences.

Something like:
```
MAJOR.MINOR.PATCH.BUILD
versionCode = MAJOR * 1000000 + MINOR * 10000 + PATCH * 100 + BUILD
```

**Comment by AshleyScirra** [comment]
I think this might be worth a trial to see how it pans out. It would be nice to auto-increment the build number on export if we don't already as well (although it'd need to wrap around after .99, given that version code scheme, unless you shunt everything else up by 10x). Or if not, at least alert the user they need to increment the 3rd number, not the 4th, when exporting again. I'll leave this up to you to decide.

**Comment by AshleyScirra** [comment]
Got this in to r70.
