### ISSUE TITLE
Find references filter option.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1049]
## Problem description

When searching for a particular or specific word (ie. layer). Search also finds references containing layer, such as Player. This can create quite a long list and make it hard to find what you're actually looking for, as it also lists partial matches.

## Attach a .c3p

N/A - Any larger project to test for partial matches will do.

## Steps to reproduce

1. Use search function to find a references of specific word. (ie. layer)
2. Check list, and see partial matches as well.

## Observed result

Partial Matches show up in search result as well.

## Expected result

Option to search for the exact word, without partial matches.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

**Comment by AshleyScirra** [comment]
This is what the 'find all references' feature is for. Use that instead of searching for text. Searching for text will always return some irrelevant results, e.g. in strings.

**Comment by tunepunk** [comment]
Ahhh neat! 👍  I actually never noticed that feature. Thanks! I was always using the regular search and was going mad with all the results. you learn new things every day.
