### ISSUE TITLE
[Suggestion] About page like in Construct 2

### ISSUE THREAD

**Issue by Plasmmer** [Scirra/Construct-3-bugs#1051]
Resized Construct 3 logo and tab navigation.

**Comment by AshleyScirra** [comment]
Please post suggestions here: https://construct3.ideas.aha.io/
Note you'll need to be a lot more specific and include a thorough reasoning of why it's important.

**Comment by Plasmmer** [comment]
https://construct3.ideas.aha.io/ideas/C3-I-379
