### ISSUE TITLE
[Suggestion] Uses RGB 0, 128, 128 as default icon color

### ISSUE THREAD

**Issue by Plasmmer** [Scirra/Construct-3-bugs#1053]
Or any other that represents Construct 3 instead of black.

**Comment by AshleyScirra** [comment]
Please post suggestions here: https://construct3.ideas.aha.io/
Note you'll need to be a lot more specific and include a thorough reasoning of why it's important.

**Comment by Plasmmer** [comment]
https://construct3.ideas.aha.io/ideas/C3-I-377
