### ISSUE TITLE
ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1058]
## Problem description

One out of 10 preview attempts I get a black screen and these errors in the log. 

![image](https://user-images.githubusercontent.com/7268697/33410307-4b6bdb76-d588-11e7-8a32-f1ff42ea116a.png)

I have been getting them actually since I started working with C2 a few years ago and I figured there's something I could possibly do about this. 

I cannot reproduce it with a fixed % rate since its very random and it happens with any of my projects. I've found a bunch of answers starting from cookies to certificates:
https://stackoverflow.com/questions/24931566/getting-error-in-console-failed-to-load-resource-neterr-connection-reset

Any idea what it could be regarding C2/C3 ?

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r70.2
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 261 mb (3.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I don't think there's anything we can do about a report like this. If it happens with C2 as well, it suggests it's not specific to C3. I've never seen it myself and I've not seen any other reports from anyone else, so I would guess its an issue with your network configuration. Perhaps you have browser addons or content blockers or something that are spuriously causing a connection to fail? Try disabling all your browser addons. If nobody else can reproduce this though, there's nothing we can do.

**Comment by JeFawk** [comment]
*If nobody else can reproduce this though, there's nothing we can do.* yes I know, I just thought maybe you know of a bug in chromium or something. Thanks anyway though
