### ISSUE TITLE
Moving action referencing local variable crashes, instead of handling gracefully.

### ISSUE THREAD

**Issue by rovacado** [Scirra/Construct-3-bugs#106]
## Problem description

Moving an object/action referencing a local variable out of scope causes an instant, unrecoverable (saved project is also affected) crash.

## Attach a .c3p

[BugreportLocalVar.zip](https://github.com/Scirra/Construct-3-bugs/files/938479/BugreportLocalVar.zip)

## Steps to reproduce

1.create a local variable in an event
2.create an object/action that references that variable
3.move the object/action to another event outside of the local variables scope

## Observed result

Current working project crashes with error pasted below

## Expected result

Expected moving action to gracefully fail, with a dialog popup explaining why this action is invalid, instead of creating an unusable project file.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Unknown expression 'Variable1': This is not a system expression or variable name in this scope.
Construct 3 version: r19
URL: https://editor.construct.net/
Date: Wed Apr 19 2017 17:17:46 GMT-0400 (Eastern Daylight Time)
Uptime: 38.1 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in r20.
