### ISSUE TITLE
Breakpoint edit crash

### ISSUE THREAD

**Issue by bible9230** [Scirra/Construct-3-bugs#1061]
## Problem description

I was learning how to use breakpoints.  I first placed a breakpoint on non trigger event successfully.  Then I edited the event and changed it to a trigger event.  I was getting a popup window telling me that breakpoints are not allowed there.  When I tried to remove the breakpoint it crashes.

## Attach a .c3p

https://www.dropbox.com/s/kqe5tgfsyomb8j4/BreakpointCrash.c3p?dl=0

## Steps to reproduce

1. Add a breakpoint to an event.
2. Edit the event to a trigger event.
3. You will get a notice that it is not allowed there.
4. Try to edit the event back to a non-trigger and it will crash.

## Observed result

It crashes.

## Expected result

The breakpoint should automatically be removed when the event was changed to a trigger.

## Affected browsers

* Chrome: yes

## System details

Error report information
Type: unhandled rejection
Reason: Error: branch not breakable @ Error: branch not breakable at e.ǃJZ (https://editor.construct.net/r70-2/main.js:63:298592) at ǃb.ǃyN.then (https://editor.construct.net/r70-2/components/editors/eventSheetView/eventSheetView.js:1:79221) at 
Stack: Error: branch not breakable at e.ǃJZ (https://editor.construct.net/r70-2/main.js:63:298592) at ǃb.ǃyN.then (https://editor.construct.net/r70-2/components/editors/eventSheetView/eventSheetView.js:1:79221) at 
Construct 3 version: r70.2
URL: https://editor.construct.net/
Date: Wed Nov 29 2017 21:01:11 GMT-0800 (PST)
Uptime: 20613.9 s

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r70.2
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M380 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.

**Comment by bible9230** [comment]
Thanks.
I also don't know if it is supposed to react this way:  when the breakpoint is tripped it puts an arrow and red dotted lines around the area, but when I try to toggle it OFF the red dotted lines are still there.

https://www.dropbox.com/s/37m99krjbo6b44j/SmartSelectImage_2017-11-30-11-36-12.png?dl=0

https://www.dropbox.com/s/a4ou7ioz4nuzk68/SmartSelectImage_2017-11-30-11-35-16.png?dl=0
