### ISSUE TITLE
"Every X seconds" doesn't work properly

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#1063]
## Problem description

An "Every X seconds" doesn't work properly or i made something wrong, it skips randomly 1.., 2 seconds

## Attach a .c3p

[New project (2).zip](https://github.com/Scirra/Construct-3-bugs/files/1519739/New.project.2.zip)

## Steps to reproduce

1. Open the attached project and watch.
2.
3.

## Observed result

Skips randomly 1~2 seconds

## Expected result

Count without pauses
## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It looks like it's working correctly. If `round(random(0,6))` generates the same number twice in a row, there's no visible change.
