### ISSUE TITLE
Enhancement perhaps - remove collision boxes or assign them a different color other than red if collision is disabled for the specific object

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1064]
## Problem description

It becomes hard to see the proper collision boxes considering the background objects have collision disabled but the boxes still appear. I know I could give them a small collision box instead but I use the same types as collidables in the game as well.

![image](https://user-images.githubusercontent.com/7268697/33484007-37dde5c8-d6a9-11e7-8bd5-e8150b2969d3.png)

**Comment by AshleyScirra** [comment]
Collisions can be re-enabled in events so it may still be important to see the collision boxes when collisions are initially disabled. Also, can't you just hide the background layer?

**Comment by JeFawk** [comment]
Maybe just a different color then? I use very few layers since the implementation of the Lock feature and everything is mostly on 1-2 layers.

**Comment by AshleyScirra** [comment]
I think you should file this here as a feature suggestion: https://construct3.ideas.aha.io/
