### ISSUE TITLE
Debug "watch" tab does not remember watched items

### ISSUE THREAD

**Issue by bible9230** [Scirra/Construct-3-bugs#1066]
## Problem description

The "watch" feature is not working in debug mode. It does not remember the flagged properties when the window is closed and reopened. 

In C2, the watch feature allows you to flag and isolate properties that you want to view often in debug mode. These properties will be available in the watch tab in ALL future debug windows until you delete them.

## Attach a .c3p

It is not related to a project.

## Steps to reproduce

1.  Select any parameters in debug mode to watch.
2.  Close debug window and reopen.
3.  The selected parameters are deleted from the watch tab. 

## Observed result

The selected watch parameters are gone and they have to be re-selected every time.

## Expected result

I expect it to keep the selected parameters until manually deleted as in C2.

## Affected browsers

* Chrome: yes

## System details

 Model Name:	iMac
  Model Identifier:	iMac17,1
  Processor Name:	Intel Core i5
  Processor Speed:	3.2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	IM171.0105.B08

**Comment by AshleyScirra** [comment]
You describe the watch feature as "not working", but it sounds like it is working, but just not remembering what you watched. Is that the correct interpretation?

**Comment by bible9230** [comment]
Yes. That is a better way of describing it.

**Comment by AshleyScirra** [comment]
OK, just checking it's not that dramatic!

**Comment by bible9230** [comment]
In addition to watch not remembering watched items, there is a problem watching arrays.

https://www.dropbox.com/s/6t6ge3geqblsd9t/WatchArrayTest.c3p?dl=0

Watch will only hold one array at a time.  The second array selected will keep the first array's name and replace the data, but two arrays will not display at one time.

Also the array cannot be deleted from being watched.

**Comment by bible9230** [comment]
I was wondering when I might see this fixed.

"Watch" not remembering and the array problem stated above makes it very frustrating to debug.

**Comment by AshleyScirra** [comment]
Should be fixed in r80.

**Comment by bible9230** [comment]
Fantastic!  Thank you for all your hard work.  I greatly appreciate it.

Did you happen to notice that I slipped in an array watching issue 3 posts ago?

**Comment by AshleyScirra** [comment]
Please keep one issue to one report, it's very confusing otherwise. If you want that investigated please file a separate issue.
