### ISSUE TITLE
C3 does not work offline if it's not the latest version

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1068]
## Problem description

I remember filing a bug like this a few months ago but I couldn't find it nor can I remember the answer and if there was a fix or not. I also don't think i noticed it could be because the C3 i had as offline was not the latest version.

My laptop was r69 and when i tried without internet to start C3 from desktop i was treated with the following screen:

![unknown](https://user-images.githubusercontent.com/7268697/33522789-0de61cee-d7fe-11e7-8329-61c068bedf0e.png)

## Steps to reproduce

1. have an older version of C3 downloaded offline
2. close the application, disconnect internet
3. attempt to open C3 again

## Observed result

C3 won't start

## Expected result

I'd expect C3 to start even if it's not the latest version.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

This is from my laptop AFTER updating to the latest version

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.125
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r70.2
Language setting: en-US

Local storage
Storage quota (approx): 2.3 gb
Storage usage (approx): 496 mb (21%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm not sure what to do to reproduce this - I can switch between editor.construct.net/r69/ (not the latest release) and editor.construct.net while offline and both load OK.

I suspect the issue really comes about at the point a new release comes out - possibly if you go offline in between the "update ready" notification and actually reloading to update?

**Comment by JeFawk** [comment]
I know this might take a few iterations to test. On my laptop I was offline before the update message appeared. I literally started it up without any internet, clicked on the C3 icon and it showed me that screen, and this is not the first time it happened. I used my phone as a hotspot and restarted C3, got greeted with the update popup.

**Comment by AshleyScirra** [comment]
Without more information there's not much to be done about this. Please file a new issue if you can figure out what steps around a new release reproduce it.
