### ISSUE TITLE
[r20] Crash when adding a "is boolean set" event to a group

### ISSUE THREAD

**Issue by alvaromartmart** [Scirra/Construct-3-bugs#107]
## Problem description

Trying to add a "is boolean set" event to a group results in a crash.
If the event is created outside any group and dragged as a child to a group, the tooltip says "Cannot drag events here:  You can't drop events here because "Righ-hand side of 'instanceof' is not an object"

## Attach a .c3p

[bug_isBooleanSet.zip](https://github.com/Scirra/Construct-3-bugs/files/943537/bug_isBooleanSet.zip)

## Steps to reproduce

1. Add sub-event to the group
2. Select 'is boolean set' event type and select the only boolean variable.

## Observed result

The editor crashes

## Expected result

Adding the event outside a group doesn't result in a crash.

## Affected browsers

Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: TypeError: Right-hand side of 'instanceof' is not an object
Stack: TypeError: Right-hand side of 'instanceof' is not an object at Function.ǃS.ǃpf (https://editor.construct.net/r20/main.js:2:201429) at Function.ǃS.ǃl (https://editor.construct.net/r20/main.js:2:201553) at Function.ǃS.ǃnw (https://editor.construct.net/r20/main.js:2:201628) at te.ǃSNw (https://editor.construct.net/r20/main.js:61:274378) at window.ǃtwX.ǃSAw (https://editor.construct.net/r20/main.js:61:335532) at window.ǃtwX.Set (https://editor.construct.net/r20/main.js:61:335679) at ǃS.ǃtRN.then.N (https://editor.construct.net/r20/components/editors/eventSheetView/eventSheetView.js:1:29438)
Construct 3 version: r20
URL: https://editor.construct.net/
Date: Thu Apr 20 2017 16:17:51 GMT+0200 (Hora de verano romance)
Uptime: 129 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro K2000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Oops, looks like a fix in r20 caused another problem. I think this could affect a lot of usage so I'll leave this open marked fixed to avoid duplicate reports, and we'll probably get an r21 out tomorrow.

**Comment by rovacado** [comment]
I didn't want to create another bug report as the one I encountered I'm fairly certain is linked to this as I get the same error report as in the OPl issue.. This bug is also preventing setting variables (global or local) in a sub event, it seems. You can set it just fine in a main event, it just seems to go wonky when dealing with the sub events

**Comment by AshleyScirra** [comment]
@rovacado - does it report the same error? "TypeError: Right-hand side of 'instanceof' is not an object"

**Comment by AshleyScirra** [comment]
Just released r21, should be fixed now.
