### ISSUE TITLE
Event Sheet View column widths stay small after resizing window small

### ISSUE THREAD

**Issue by bible9230** [Scirra/Construct-3-bugs#1071]
## Problem description

When reducing the browser window size to something smaller than the code column width, and then sizing back up to a full screen, the column widths remain collapsed.  You have to manually adjust each column to the proper width.

## Attach a .c3p

not project specific

## Steps to reproduce

Full screen
https://www.dropbox.com/s/wgkqio7pwmxlsdd/Screen%201.jpg?dl=0

Reduced window size
https://www.dropbox.com/s/3kznl2yo5omylyn/Screen%202.jpg?dl=0

Full screen with collapsed columns
https://www.dropbox.com/s/5jxx2ws9jcspplv/Screen%203.jpg?dl=0

## Observed result

see above

## Expected result

It would be nice if the columns remembered their width.

## Affected browsers

* Chrome: yes

## System details

  Model Name:	iMac
  Model Identifier:	iMac17,1
  Processor Name:	Intel Core i5
  Processor Speed:	3.2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	IM171.0105.B08
  SMC Version (system):	2.33f10

**Comment by bible9230** [comment]
I've noticed that this only happens if C3 is the ACTIVE browser tab when the window is resized.

**Comment by tunepunk** [comment]
I've noticed something similar when switching computer. At work My Mac has one resolution, and at home my computer has pretty high dpi. Saving the project on one computer then opening on the other i have change column sizes. Maybe C3 is storing column width in pixels rather than percentages?

**Comment by tunepunk** [comment]
For example properties bar seems to be using percentages for the middle column. It always have a relative width. The event sheet columns seem to be a fixed pixel size, and only the action (right- most part of the event sheet) will scale depending on how much space you have. So on some computers the Left side (conditions) use a lot of space, but actions get a very tiny amount. Would be good if that was percentage based as well.

**Comment by AshleyScirra** [comment]
When you resize the browser window smaller, it clamps the widths to the minimum allowed sizes. Construct 2 works the same. Do you really resize your browser window that small very often?

**Comment by tunepunk** [comment]
I would think it's more accidental resizing of the window. But there is the right click "Event Sheet > Reset column sizes" to get it back to normal.

My problem is a bit different as I use often two different computers with different scaling. (At work when I have time over, and home) So when I save my project at work, and continue at home I always have to change the columns for that particular screen. That's why I think percentage based would be better, so the ratio between conditions and actions would be about equal, no matter what scaling / screen size you use.

**Comment by AshleyScirra** [comment]
@tunepunk - I think you are talking about a different issue and should file a separate report for that. This issue involves resizing the window smaller. The issue you are talking about sounds like an issue opening projects on systems with different device pixel ratios/zoom scales, which the column sizes ought to take in to account already, but perhaps there's something wrong with that.

**Comment by bible9230** [comment]
It's a better example to show an event and layout sharing the main area while resizing from a full screen.

event and layout at full screen
https://www.dropbox.com/s/0050nzpibheldi0/Layout%20Screen%201.jpg?dl=0

reduced window size
https://www.dropbox.com/s/tue7ivzn6aw229e/Layout%20Screen%202.jpg?dl=0

collapsed columns returning to full screen
https://www.dropbox.com/s/7c0k5ypciakb33c/Layout%20Screen%203.jpg?dl=0

**Comment by AshleyScirra** [comment]
Updated to preserve column sizes after resizing in r73.
