### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#1074]
## Problem description

Well, i didn't even start a new project just loaded construct and after ~2 seconds crashed.

## CRASH LOG

Error report information
Type: unhandled rejection
Reason: Error: expected function @ TypeError: expected function at Function.ǃz.ǃuH (https://editor.construct.net/r71/main.js:2:179070) at Function.ǃz.ǃt (https://editor.construct.net/r71/main.js:2:207550) at r.ǃybC (https://editor.construct.net/r71/main.js:73:39548) at Object.n.push.ǃz.ǃ_p [as ǃyVp] (https://editor.construct.net/r71/main.js:73:39938) at n (https://editor.construct.net/r71/main.js:2:272114) at t (https://editor.construct.net/r71/main.js:2:271900)
Stack: TypeError: expected function at Function.ǃz.ǃuH (https://editor.construct.net/r71/main.js:2:179070) at Function.ǃz.ǃt (https://editor.construct.net/r71/main.js:2:207550) at r.ǃybC (https://editor.construct.net/r71/main.js:73:39548) at Object.n.push.ǃz.ǃ_p [as ǃyVp] (https://editor.construct.net/r71/main.js:73:39938) at n (https://editor.construct.net/r71/main.js:2:272114) at t (https://editor.construct.net/r71/main.js:2:271900)
Construct 3 version: r71
URL: https://editor.construct.net/
Date: Tue Dec 05 2017 20:48:18 GMT+0100 (Środkowoeuropejski czas stand.)
Uptime: 105.7 s

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r71
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTS 450 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It looks like a plugin failed to load. It's not clear why that would happen, and there are no other details in the report, so I'm afraid there's not much we can do about this.
