### ISSUE TITLE
Consistent Repeatable Crash Trying to Authenticate Google Drive for back up when Offline

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1075]
## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
[New project (1).zip](https://github.com/Scirra/Construct-3-bugs/files/1533274/New.project.1.zip)

## Steps to reproduce

- Minimal project
- set backup location to google drive
- disconnect internet access
- wait for back up to initiate

## Observed result

receive " unable to authenticate google drive " message
close message box
C3 crashes

## Expected result

no back up and no crash

## Affected browsers

* Chrome: yes

## System details

Error report information
Type: unhandled rejection
Reason: Error: authentication cancelled @ Error: authentication cancelled at MessagePort.b (https://editor.construct.net/r71/cloud/sandbox.js:1:2366)
Stack: Error: authentication cancelled at MessagePort.b (https://editor.construct.net/r71/cloud/sandbox.js:1:2366)
Construct 3 version: r71
URL: https://editor.construct.net/
Date: Tue Dec 05 2017 22:46:52 GMT+0000 (GMT Standard Time)
Uptime: 151.3 s

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r71
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

PASTE HERE

</details>
[New project (1).zip](https://github.com/Scirra/Construct-3-bugs/files/1533270/New.project.1.zip)

**Comment by shortercode** [comment]
I've fixed this issue, but it's still likely to pop up the authentication window while your working. It doesn't differentiate between an invalid auth token and a network error at the moment.
