### ISSUE TITLE
C3 crashes Chromium stable tab on Linux

### ISSUE THREAD

**Issue by gedaerm** [Scirra/Construct-3-bugs#1076]
## Problem description

A few seconds after entering http://editor.construct.net, the current stable chromium (62.0.3202.94, 64bit) crashes on Linux (the tab shows the "Aw, snap" icon)

## Attach a .c3p

n/a, because it does not reach the point where one can create a project

## Steps to reproduce

1. Boot Linux, install Chromium 62.0.3202.94
2. Go to https://editor.construct.net
3. Wait ~2 seconds, then the crash will occur

## Observed result

Crash. A stack trace gets dumped to the console, and the following error message: 
"# Fatal process OOM in heap setup"

This suggests an out of memory error. Upon closer inspection the construct editor tab tries to alloc above 16gb of memory (which is a hard limit in chromium). Following this lead a bit further, by disabling the chromium sandbox (start with $ chromium --no-sandbox, which is something one cannot do in a productive environment, it's just for debugging purposes), the editor runs normally. This test box has 128gb of memory, so it was no problem, the tab wanted 26gb to just display the editor front website with the "create" etc buttons. To be precise: allocate it, not fill it. The actual memory consumption was much lower.

This is a problem, because that's not a beta or dev channel but rather the stable chromium release.

## Expected result

No crash. 

## Affected browsers

* Chromium: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

#
# Fatal process OOM in heap setup
#

Received signal 4 ILL_ILLOPN 55f38ec0698f
#0 0x55f38ca2bde7 <unknown>
  r8: 0000000000000000  r9: 000055f390fbecfe r10: 00007fd8e12c3be0 r11: 0000000000000000
 r12: 00007fd8b6a07c80 r13: 0000000000000000 r14: 000055f390fbecfe r15: 00007fd8b6a07e90
  di: 00007fd8b6a05310  si: 0000000000000028  bp: 0000000000000000  bx: 00001732afbcc000
  dx: 00007fd8e15036f0  ax: ad724bc43112d700  cx: 0000000000000000  sp: 00007fd8b6a07ae8
  ip: 000055f38ec0698f efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000006 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

</details>

**Comment by shortercode** [comment]
This definitely sounds like a chromium bug, when idle C3 is using 120MB on my windows box in Chrome 62 ( not exactly the same I know, but it's the closest I have for comparison ). Have you tried filing a bug with the chromium team?

Also, as a workaround, have you tried using Firefox instead for the time being?

**Comment by gedaerm** [comment]
I'm pretty sure it is a chromium issue, I still thought it was worth mentioning so that you have it on your radar (because of its severity on a stable browser release). 
Firefox is unaffected so that's what I currently use (Firefox 57.0.1 works)

I have not (yet) reported to the chromium team, I had.. shall we say: mixed results with this in the past (mostly failure to provide minimal JS examples that trigger the bugs)

**Comment by shortercode** [comment]
Yeah it's good to know, thanks :) I'll try repeating it when I'm back in
the office.

They can be reluctant to look at large projects, can take a very long time
to track things down... Sometimes when is obviously broken they look it,
but it varies on who takes up the bug.

**Comment by AshleyScirra** [comment]
"Aw snap" means Chromium crashed, and it's not our code. Normally this kind of crash is caused by buggy GPU drivers, but it could be something else. Either way your best bet is to file an issue on crbug.com and follow up there.

**Comment by AshleyScirra** [comment]
BTW Google noticed this and filed an issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=792711

FWIW Chrome 63 just came out so it might be worth retrying with that.

**Comment by gedaerm** [comment]
I've starred the issue, maybe it helps. 
Also checked against the fresh Chromium 63.0.3239.84, same thing happens.

**Comment by gedaerm** [comment]
FYI: As of Chromium 68.0.3440.106 this issue looks fixed.
