### ISSUE TITLE
Undo in spritefont editor

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#1078]
## Problem description

Undo doesn't work in spritefont animation editor. 

## Attach a .c3p

[New project (3).zip](https://github.com/Scirra/Construct-3-bugs/files/1537679/New.project.3.zip)

## Steps to reproduce

1.  Change the spritefont colour
2. Undo shouldn't work
3.

## Observed result

Cannot undo in spritefont editor

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r72. This was affecting all objects with no animations.
