### ISSUE TITLE
Sometimes a blank popup message with "OK" button appears

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#1079]
## Problem description

I had this twice in the last 2 days but could not find how to reproduce. Maybe something with autosaving (backup)? I use google cloud for saving and backups right now (every 10 min).

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Use C3 (as desktop version in Chrome)

## Observed result

A blank popup message appears (the one like "already saving") with an OK Button

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r71
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 40 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Assigning to Iain to review cloud-related OK dialogs.

**Comment by shortercode** [comment]
Sounds like some sort of blank error is being thrown in the autosave, google authentication tokens last about an hour so perhaps it's expiring during the session... Bug #1075 might be related, some part of the autosave not dealing with errors correctly.

**Comment by shortercode** [comment]
I haven't been able to find any obvious place for this error so I've added some placeholder error messages. If an error occurs without a message then it will at least tell you what it was trying to do at the time. Hopefully I'll find out what is actually breaking here at some point. But, I expect it's some poorly described network error. I've seen some in the past which just give you a generic error code ( like 500 ) and nothing else.

**Comment by shortercode** [comment]
@TheBl4ckSh33p any news on this? I'd like to close it if it's not causing you problems anymore

**Comment by shortercode** [comment]
Okay just going to close this, file a new bug if any problems related to this crop up.
