### ISSUE TITLE
crash when setting global from local storage

### ISSUE THREAD

**Issue by LiamDawe** [Scirra/Construct-3-bugs#108]
## Problem description

Inside a group, when it's active, grab something from local storage. Then try to set a global as the value of that item -> crash.

## Attach a .c3p

https://drive.google.com/open?id=0B9c_B4nsoa7fLVJrLVYyUEswU2c

## Steps to reproduce

1. Start of layout, make group active
2. Group active, grab local storage key
3. Set global to storage item, crash

## Observed result

Crash

## Expected result

Set the global, obviously.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: TypeError: Right-hand side of 'instanceof' is not an object
Stack: TypeError: Right-hand side of 'instanceof' is not an object at Function.ǃS.ǃpf (https://editor.construct.net/r20/main.js:2:201429) at Function.ǃS.ǃl (https://editor.construct.net/r20/main.js:2:201553) at Function.ǃS.ǃnw (https://editor.construct.net/r20/main.js:2:201628) at te.ǃSNw (https://editor.construct.net/r20/main.js:61:274378) at window.ǃtwX.ǃSAw (https://editor.construct.net/r20/main.js:61:335532) at window.ǃtwX.Set (https://editor.construct.net/r20/main.js:61:335679) at ǃS.ǃtRN.then.r (https://editor.construct.net/r20/components/editors/eventSheetView/eventSheetView.js:1:67894) at 
Construct 3 version: r20
URL: https://editor.construct.net/index.html
Date: Thu Apr 20 2017 15:19:24 GMT+0100 (BST)
Uptime: 1339.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.81
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 980 Ti/PCIe/SSE2
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 189.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I can't follow step 2: "Group active, grab local storage key". This is pretty ambiguous, I don't know what you're really doing, and there is no local storage plugin in the .c3p, so I'm stuck there. Still, the crash report looks like the same problem as #107 so closing as duplicate.

**Comment by AshleyScirra** [comment]
Check again after r21, since I'm pretty sure it is #107.

**Comment by AshleyScirra** [comment]
r21 is out now, can you verify it's fixed?
