### ISSUE TITLE
Crash dragging events into new Group

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1082]
## Problem description

Guys i know you're going to close this straight away as there is no minimal project 

but maybe the crash dump is some use to you.

happened in my primary project so no "minimal project" example to provide (though im happy to provide my project off line if it happens again)

**At the time of the crash
I had just made a new group and was dragging and dropping some 4 events from lower down into the new group.

when the drop finished the event sheet wiped itself  and looked like a new sheet with the "this is an empty sheet message.  then C3 crashed out with the opps something went wrong message**

## System details

Error report information
Type: assertion failure
Message: no sequence number assigned
Stack: Error at Function.ǃz.ǃymI (https://editor.construct.net/r71/main.js:2:205305) at t (https://editor.construct.net/r71/main.js:2:173802) at window.assert (https://editor.construct.net/r71/main.js:2:174205) at e.ǃzyz (https://editor.construct.net/r71/main.js:63:273685) at ǃRh (https://editor.construct.net/r71/main.js:63:273773) at Array.sort (native) at window.ǃIh.ǃRe (https://editor.construct.net/r71/components/editors/eventSheetView/eventSheetView.js:1:11579) at window.ǃIh.ǃhd (https://editor.construct.net/r71/components/editors/eventSheetView/eventSheetView.js:1:25107) at window.ǃIh.ǃPG (https://editor.construct.net/r71/components/editors/eventSheetView/eventSheetView.js:1:24471) at window.ǃIh.ǃus (https://editor.construct.net/r71/components/editors/eventSheetView/eventSheetView.js:1:20899)
Construct 3 version: r71
URL: https://editor.construct.net/
Date: Thu Dec 07 2017 23:42:36 GMT+0000 (GMT Standard Time)
Uptime: 4870.8 s

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r71
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
Sorry, the crash messages aren't always useful on their own, and in this case we need steps to reproduce to be able to investigate. Please re-file if you can find a way to reproduce it.
