### ISSUE TITLE
Xbox GamerPic not shown in Sprite

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#1083]
## Problem description

I have a emtpy sprite which I use to load the Xbox GamerPic with LoadFromURL but its always empty.
I added a browser>log action to log the URL and when I open it in Chrome it displays my Gamerpic. But it never appears in the game. (it worked a few weeks ago in my other game but stopped to show a pic there, too)

Example: http://images-eds.xboxlive.com/image?url=wHwbXKif8cus8csoZ03RW8ke8ralOdP9BGd4wzwl0MJ9z6QzuGwZjtvbE7sSsMVWWq4DZSvn7kbdfroV4boi78M1jdZHQn4hEJtIYqr4Xzd9MtFNk40TOx5Oiu5Vu6qX1HnnGPiS3GER2ha2vaPn_U3oEQuKJzn5gE0Nz7ISvhA-&format=png

## Attach a .c3p

[LoadGamerPicFails.zip](https://github.com/Scirra/Construct-3-bugs/files/1541763/LoadGamerPicFails.zip)

## Steps to reproduce

1. Use XboxLive.UserGameDisplayPictureUri to load image into sprite (tried anonymous and none)
2. no image shows up
(I used the URL I got for this example)

## Observed result

No image appears in sprite

## Expected result

Gamerpic should be shown

## Affected browsers

* Chrome: yes
* Edge: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r71
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 163 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Try changing 'cross-origin' to 'none', does that work?

**Comment by TheBl4ckSh33p** [comment]
Hi. Just tried it but it does not load the image. :(

**Comment by AshleyScirra** [comment]
OK, I think the problem is the avatar images are hosted on insecure HTTP (causing mixed-content errors), and without CORS either. Microsoft need to change the way these images are hosted, I'll get in touch with them to see what can be done about it.

**Comment by AshleyScirra** [comment]
BTW that error you posted involves a Service Worker, which is not used in UWP exports. So how are you testing that? Have you tried it in a UWP export?

**Comment by TheBl4ckSh33p** [comment]
In my published game and in VS preview I had a blank sprite (with anonymous) and I tested the "none" setting in construct preview last time.

I will try it in UWP export again and change all origins to "none" to see if it works then.

**Comment by AshleyScirra** [comment]
OK, so it at least works in UWP apps. For the other issues I posted for help here: https://social.msdn.microsoft.com/Forums/en-US/dfdb4c4a-d890-4164-a005-56b122500fed/gamer-pictures-do-not-support-https-or-cors?forum=xboxlivedev
- will follow up there.
