### ISSUE TITLE
Webfont in editor different than in preview?

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#1084]
## Problem description

When I preview my game the fond needs more space to fit into the text object and object placement is very difficult if you cant see in the editor where everything will be. Possible to fix this?

## Attach a .c3p

[TextDifferentInEditor.zip](https://github.com/Scirra/Construct-3-bugs/files/1544597/TextDifferentInEditor.zip)

## Steps to reproduce

1. Preview and see the difference

## Observed result

Middle text about Goals is longer in preview than in editor.
**And text is sometimes cut off if the text box is not big enough in preview but fits perfectly in the editor.**

Editor:
![editor](https://user-images.githubusercontent.com/2725603/33795005-6ede3210-dcd7-11e7-923e-fb405d00ad86.PNG)
Preview:
![preview](https://user-images.githubusercontent.com/2725603/33795006-78508000-dcd7-11e7-8f70-b056a3377bec.PNG)

## Expected result

Text should be same size in preview and editor

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.94
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
C3 release: r71
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 164 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Minimal project: [text-in-editor.zip](https://github.com/Scirra/Construct-3-bugs/files/1551907/text-in-editor.zip)
Note wrapping around word "trying"

**Comment by AshleyScirra** [comment]
Turns out the runtime wrapped if the space after the word didn't fit (i.e. it tries to fit "trying_" at the end of the line), but the editor more sensibly fit the word on the same line if it can fit not counting the space (i.e. it only tries to fit "trying" at the end of the line). In r73 I've updated the runtime to use the same approach as the editor, so it looks the same as in the editor now.
