### ISSUE TITLE
Navigating with ALT + Left/Right Arrow Keys in Action/Event Windows

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1085]
## Problem description

I can't navigate in add action and event windows with ALT + left/right arrow keys. It's important for me because in C2 I don't use the mouse most of the time and this makes doing things a lot faster.

## Observed result

Nothing happens.

## Expected result

ALT + LEFT ARROW: Back
ALT + RIGHT ARROW: Next

Like in C2.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

**Comment by AshleyScirra** [comment]
In response to issue #982, we changed the shortcut to Alt + Shift + Left/Right to avoid conflicting with a macOS shortcut. I realised the manual keyboard shortcuts entry was out of date though, so I updated it.
