### ISSUE TITLE
Chrome freezes on trigger event 

### ISSUE THREAD

**Issue by bible9230** [Scirra/Construct-3-bugs#1089]
## Problem description

I am testing my program in preview mode.  After the 5 cards are dealt and the deck is empty, I double click on the empty card pile and the preview freezes immediately.  In debug mode, the system time instantly stops.  The Chrome window faults out and has to restart.

## Attach a .c3p

https://www.dropbox.com/s/wrrb4tkq0q6guym/cards.c3p?dl=0

## Steps to reproduce

1.  Run in any preview mode
2.  Deal out five cards by clicking on the table
3.  When the deck is empty, double click on the empty space
4.  The program freezes instantly

## Observed result

Chrome freezes and faults out every time.

## Expected result

No freezing.

## Affected browsers

* Chrome: yes
and on my Note 5

## System details

  Model Name:	iMac
  Model Identifier:	iMac17,1
  Processor Name:	Intel Core i5
  Processor Speed:	3.2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	IM171.0110.B00
  SMC Version (system):	2.33f10

**Comment by AshleyScirra** [comment]
It looks like your events have an infinite loop. The while condition will never terminate if the sub-event condition does not run, because then IndexedPosition is never modified and so the while event never becomes false. Is there a reason you think this is a C3 bug rather than a mistake in your events?

**Comment by bible9230** [comment]
I just figured it out this morning that the array needs to be cleared.  It then functions properly.  

Is it possible for C3 to recover from an infinite loop and just give an error?  When it happened the first time, I lost all my changes up to that point.  When Chrome freezes every time on the infinite loop, it makes it very difficult to troubleshoot the program.  For an amateur like me it is very confusing.

**Comment by AshleyScirra** [comment]
Currently the way browsers and the runtime are architected makes it difficult to handle hanging due to infinite loops. We have plans on how to address this in the C3 runtime though.
