### ISSUE TITLE
"Invalid parent ID" error saving to browser in incognito mode

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#1090]
## Problem description

Saving to local browser in incognito mode shows a strange error.

## Steps to reproduce

1. Open C3 in Chrome Incognito
2. Open a project
3. Save to local browser

## Observed result

An error popup "Invalid parent ID" with a random code

## Expected result

Either the save should "succeed" (saving temporarily for the duration of the incognito session), or it should show a more descriptive error message, e.g. "unable to access storage".

I did also see this one time in normal (not incognito) browsing mode, maybe it's something to do with the first save.

**Comment by shortercode** [comment]
Yeah I can see this, looks like the root folder is only created during an "upgrade" from the older style folderless format.

**Comment by shortercode** [comment]
Fixed for r73
