### ISSUE TITLE
Lastpass login popup on chrome  goes under C3 login popup.

### ISSUE THREAD

**Issue by veevalkonen** [Scirra/Construct-3-bugs#1092]
Lastpass login popup on chrome  goes under C3 login popup.

![2017-12-12_011630](https://user-images.githubusercontent.com/9288088/33860217-5609e3be-dee0-11e7-81a6-e62c7727486e.png)

**Comment by jaydonteh** [comment]
What I did to circumvent was to right-click then Auto-fill.

**Comment by veevalkonen** [comment]
Didn't know about that option, thank you for the tip. 
Wish it could be fixed though.

**Comment by veevalkonen** [comment]
Not sure, but first time LP acts like this on +300 login pages.
I'll contact them as well.

**Comment by veevalkonen** [comment]
Yes, it's a LP problem, sorry for claiming it was C3 bug.

_Lastpass support:

Thank you for contacting LastPass Support.

I can replicate your reported issue.
We appreciate your time in reporting this incident. I have added the incident in our list for further review by our development team, however I cannot provide any ETA if or when it will be fixed. Although I am unable to say if/when this will be fixed (i.e. provide an ETA), rest assured that this has been logged and will be available for our team's review. I have added your information to the report so that we may notify you should we receive an update.

Our apologies for the inconvenience caused._

**Comment by AshleyScirra** [comment]
OK, thanks for contacting them.
