### ISSUE TITLE
Replace Project File does not work

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1096]
trying to import overwrite a json/array project file with the same name generates a replace file notice but does not replace the file when replace is clicked.

## Attach a .c3p
[testarrayimport.zip](https://github.com/Scirra/Construct-3-bugs/files/1551335/testarrayimport.zip)

## Steps to reproduce

(1) 
Using cp3 attached generate array A json text
copy text from the text box and paste into a text file (on desktop or wherever) with the file name "testarray.json"
verify that all the values are "A"
import the testarray.json into the project as a project file 
verify that the project files array values are all “A

(2)
Using same C3p attached generate array B json text
copy text from text box and paste (overwriting) into the exact same "testarray.json" text file as above (on the desktop or whatever) and save with the same name
verify that all the values are "B"
import into the same project as a project file

you will receive notice that "testarray.json"  file will be replaced
click replace to replace the file.
check the new testarray project file values

(Issue)
you will see that they are still all “A”
**the array has not been overwritten**

(Secondary Issue)
Depth field is not showing correct value on imported array, is showing 0 when should be 3 

## Expected result

To overwrite the file, show the correct values
and show the correct depth of the array

## Affected browsers

* Chrome: yes
only chrome tested

**Comment by NetOneGames** [comment]
No 

If the array editor is open during the import operation the file does not get updated.  (even if I close the editor after the import and reopen the editor.)

however if I close the array editor _before_ I import then the file does get overwritten correctly.

the editor being open is blocking the import

**Comment by shortercode** [comment]
Ah I should have been clearer, the file will be "updated" but the data editor will not read the change and it will save it's contents over the top whenever a change is made or the editor is closed. So its' impossible to actually see the change within C3.

I've made some changes so that if the file is changed the editor will reload the file, switching to the text editor if the file isn't a valid array or dictionary anymore.

**Comment by NetOneGames** [comment]
I get you.  

- The file _is_ actually overwritten but 

1. There is no notice to the user that the overwrite was successful
2. If the editor is open the editor does not get updated even if subsequently closed and reopened.
3. Then if the user makes any changes in the editor then the project file (with actually has the correct data) will get overwritten with totally the wrong and old data from the editor.

!!! sounds like a recipe for absolute disaster !!!

**So if you could also include a notice that overwrite has been successful**
**and obviously need the editor to show whatever is on the project file at all times.**

(i will be using the feature a lot going forwards so need it to work flawlessly)

cheers.

**Comment by shortercode** [comment]
Okay I've checked in a fix for this, so both parts should now work fine. Any open files will display a message along the lines of "Open file 'new array.json' was changed, its array editor will reload.

I've noticed the undo around this area is a little questionable  so going to try fix that as well before closing this issue.

**Comment by shortercode** [comment]
Undo fixed now as well. Turned out to be more complicated than I originally expected, so hopefully it doesn't have any bugs in it. These changes should appear in r73 when it appears.

**Comment by NetOneGames** [comment]
Nice one!  cant wait to check it out.
Happy Christmas.

**Comment by shortercode** [comment]
Happy Christmas to you too! 🎅
