### ISSUE TITLE
C3 not always can preview project 

### ISSUE THREAD

**Issue by XpMonster** [Scirra/Construct-3-bugs#1097]
## Problem description

I thought it was my project at first, but it's acting kinda weird. 

Error only appears on occasion for reasons unknown and can show up in any project.

Sometimes I don't get this error for a long time, sometimes I get it each time I try preview.

When I do get this error I usually just press F5 or close/start preview again and then preview usually starts running as always. 

It maybe can react on changes if any made in sheet editor or if I work for a long time, 
but more realistic I think it has something to do with my internet connection. 

What's to internet. So I run some tests on http://www.whatsmyip.org/ping/
Sometimes it's perfect, but sometimes I do lose packets. So if there's something C3 does differently in order to preview in Online/Offline mode, maybe when I preview in the moment of another lost packet there's this error? Just a theory...

Expect "Can't reproduce", but if you're able at least confirm that it has nothing to do with my project that would be highly appreciated. 

## Observed result

See pictures

https://i.imgur.com/HKDFoua.png

https://i.imgur.com/H3hCdUH.png

or sometimes i'm just getting a black screen. 

## Expected result

Preview my project

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
There's not a lot we can do without steps to reproduce. Some things to try though:

- try disabling all browser extensions
- when the error happens, check the browser console for the popup window (Ctrl+Shift+J), there should be more detailed information there

**Comment by NetOneGames** [comment]
just browsing these issues and I also have the same
I would say about 1 in 7 times the project will not preview will just get a blank screen.
refresh or re-preview will fix

**Comment by AshleyScirra** [comment]
This might be related to #1058. I previously closed that but if it's not isolated we should investigate.

Could anyone affected also try Firefox/Safari/Edge? If only Chrome is affected it's useful to know.

**Comment by NetOneGames** [comment]
yea sounds the same although ive never had an issue in C2.    its the sort of thing most people wont report as a  quick refresh sorts it. I didnt even think to report it but it has been bugging me.

Ive only used c3 with chrome so far.  haven't been brave enough to try other browsers but will try at least edge tonight  see if I get same issue

**Comment by XpMonster** [comment]
I'm currently have 0 packets loss and so I'm unable to reproduce no matter how much I try to preview. 
Usually internet gets worse when most people return to their homes so I hope update on the matter few hours later and can check on Firefox, Opera. See if this packet loss is related in any way. 

You'll never get same kind of error in C2, because it's not so internet dependent so it makes even more sense now. 

If you currently experience a lot of these @NetOneGames  please try http://www.whatsmyip.org/ping/

**Comment by NetOneGames** [comment]
Sorry Im at work so these links dont work for me (for some reason scirra/construct and github  work through thankfully)

**are we saying this is related to packet loss ???**

that is very interesting as I recently got a virgin hub 3 router upgrade (from hub 1) and notice my COD/Overwatch stats have taken a dive.  Im almost sure this is related to packet loss but havent checked properly yet.   It would have come the same time as C3 was nearing end of beta which is why I may not have seen in C2    hmmm

**Comment by AshleyScirra** [comment]
I seriously doubt this is anything to do with packet loss, because TCP automatically recovers from packet loss at the transport layer. Applications higher up the stack only see extra latency when packet loss happens, rather than failures, while TCP retransmits to obtain any lost packets.

**Comment by XpMonster** [comment]
Don't have anything yet. I'll let you know as I find more information.
I think it's clear now it has nothing to do with my project and so it's absolutely safe for me to continue.

**Comment by NetOneGames** [comment]
Sorry I haven't had time to work on my game, will do so over the weekend and get back asap.

**Comment by newman321** [comment]
Same problem here

**Comment by XpMonster** [comment]
Well it must have something to do with internet connection, because I'm having great connection all last days and so problem doesn't shows. 

Maybe got scared of my report. Bug with it's own AI lol
