### ISSUE TITLE
problems when creating a new project

### ISSUE THREAD

**Issue by kop9000** [Scirra/Construct-3-bugs#1098]
I discovered a problem when creating a new project.

The fact is that when I create a project with a certain resolution, for example 640 by 480, when creating a project, it will forever be 1280 by 720.

this happens when I create a new project

https://youtu.be/gRqEhLHm3vM

Why is this happening?

**Comment by AshleyScirra** [comment]
This is by design. The layout defaults to double the size of the viewport, so there's somewhere to scroll to. Otherwise beginners get confused as to why scrolling doesn't work. The actual viewport size is in project properties, not layout properties.

**Comment by kop9000** [comment]
sorry me. honestly did not know about it.

But I have a proposal to add the configuration of the first layout to the creation of a new project
