### ISSUE TITLE
Realease r72 - cloud not open

### ISSUE THREAD

**Issue by brunomcardoso** [Scirra/Construct-3-bugs#1099]
After opening the Construct 3, clicking on Cloud to open a project in Dropbox, opens the cloud window but does not connect to the dropbox... in previous realeases is fading correctly

**Comment by shortercode** [comment]
I tried a few variations of this in Chrome and it worked fine. Could you update the bug with the details specified in the guidelines please.

**Comment by shortercode** [comment]
closing as abandoned issue, comment here with the requested information for it to be reopened.
