### ISSUE TITLE
Crash when adding dictionary object (mobile)

### ISSUE THREAD

**Issue by psander5** [Scirra/Construct-3-bugs#11]
## Problem description

When adding a dictionary, array or xml object to any project, on mobile (Android phone) I get a crash.    This only happens in mobile UI mode.  If I switch to desktop UI mode I can add the objects as normal.  To verify this I tried the mobile UI mode on a pc and got the same crash.

## Attach a .c3p

This is just a blank, default new project saved after the crash:
[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/903328/New.project.zip)
And here is a version of that file with some events attempting to use the broken dictionary that was added at the point of the crash,  and a working dictionary added later:
[New project (events).zip](https://github.com/Scirra/Construct-3-bugs/files/903414/New.project.events.zip)

## Steps to reproduce

1. Have Construct 3 in mobile UI mode (any device)
2. insert dictionary, array or xml object

## Observed result

Crash.  If I manage to save the file from the crash dialog then upon re-opening I find that the object appears to have been added, but doesn't work.

## Expected result

Not to crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: TypeError: unexpected type
Stack: TypeError: unexpected type at Function.ǃp.ǃg (https://editor.construct.net/r16/main.js:2:201492) at window.ǃem.ǃWLo (https://editor.construct.net/r16/components/bars/zOrderBar/zOrderBar.js:1:12965) at Array.ǃWLY.k (https://editor.construct.net/r16/components/bars/zOrderBar/zOrderBar.js:1:1209) at ǃp.Event.ǃWXR.ǃWXM (https://editor.construct.net/r16/main.js:2:283389) at window.ǃLFe.dispatchEvent (https://editor.construct.net/r16/main.js:2:281781) at window.ǃLFe.ǃWoc (https://editor.construct.net/r16/main.js:153:36119) at ie.ǃplI (https://editor.construct.net/r16/main.js:61:160014) at Le.ǃpPV (https://editor.construct.net/r16/main.js:61:235739) at We.ǃplB.then (https://editor.construct.net/r16/main.js:63:421914)
Construct 3 version: r16
URL: https://editor.construct.net/
Date: Thu Apr 06 2017 18:02:57 GMT+0100 (BST)
Uptime: 19 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.132
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Android
Operating system version: 7.1.2
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 3.5
Logical CPU cores: 8
User agent: Mozilla/5.0 (Linux; Android 7.1.2; Nexus 6P Build/NPG47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.132 Mobile Safari/537.36

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: Qualcomm
Renderer: Adreno (TM) 430
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_atc, WEBKIT_WEBGL_compressed_texture_atc, WEBGL_compressed_texture_etc1, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for r17.
