### ISSUE TITLE
Expressions Dictionary (Usability)

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#110]
## Problem description

Not really a bug but more of a usability enhancement. It would be good if C3 remembers to keep this one open. In C2 i believe this one (or a similar one) is always open by default, but somewhat transparent. This is something I use quite often, for easy access to common expressions, and less typing. So it would be good if C3 remembered to keep it open whenever you are to input expressions, just like C2.

## Attach a .c3p

N/A

## Steps to reproduce

1. Add a new Action (For example set Position)
2. Dialogue has a very small link to the expression library. (Could be more clear)
3. Enter some expression...
4. Add another action (Expression dictionary open state is not remembered, so you have to open it again)

## Observed result

Open state of Expressions dictionary is not remembered, when adding a new expressions.

## Expected result

Expression dictionary to remember it's open/closed state when entering expressions.

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed in r22.
