### ISSUE TITLE
Wrong Collision Polygon Increment

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1100]
## Problem description

In Construct 2 you could use the arrow keys to adjust a collision polygon with a 1 pixel increment, which is perfect for pixel art assets! But in Construct 3 the increment seems to change based on your current zoom, which results in some really bad and "not snappy" point positioning.

I think the best solution would be adding a toggle button for the old 1 pixel increment or a type box for us to set the increment size, like in Adobe Illustrator.

[https://i.imgur.com/xc2jA1Q.png](url)

## Attach a .c3p

[Collision Polygon.zip](https://github.com/Scirra/Construct-3-bugs/files/1560474/Collision.Polygon.zip)

## Steps to reproduce

1. Open any image.
2. Select the Collision Polygon tool.
3. Try to adjust any Point using the arrow keys.

## Observed result

The Point will move with a increment based on your current zoom.

## Expected result

The Point to move 1 pixel per click.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by jaydonteh** [comment]
I speak on my own experiences, yes this is a much needed addition!

**Comment by DiegoScirra** [comment]
Fixed in r73.
