### ISSUE TITLE
Mobile mode: No option fir choosing colour in editor and no way to choose keyboard key

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#1101]
## Problem description

*In image editor their is not option for choosing colour
in keyboard plugin it says press any key to choose but in mobile we have no choice to select key*

## screenshot attached
![fon](https://user-images.githubusercontent.com/17684135/34012288-3603f96e-e139-11e7-87f9-ac03763bd940.png)
![fon](https://user-images.githubusercontent.com/17684135/34012289-364eec08-e139-11e7-88cc-09ce862f2993.png)
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. open image editor in mobile mode
2. insert keyboard plugin and try to set any key

## not finding choose option

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>
![screenshot_2017-12-15-01-31-21-536_com android chrome](https://user-images.githubusercontent.com/17684135/34012288-3603f96e-e139-11e7-87f9-ac03763bd940.png)
![screenshot_2017-12-15-01-32-38-158_com android chrome](https://user-images.githubusercontent.com/17684135/34012289-364eec08-e139-11e7-88cc-09ce862f2993.png)

**Comment by AshleyScirra** [comment]
Swipe in twice from the left to access the color picker. Currently the keyboard key dialog is by design.
