### ISSUE TITLE
Preview does not works when connected to router but not to internet 

### ISSUE THREAD

**Issue by newman321** [Scirra/Construct-3-bugs#1104]
Connect to a wifi router which is not connected to the internet. try to preview your project.
Preview shows error in console about not being able to update sw

**Comment by AshleyScirra** [comment]
Preview works offline-first so it should not matter what the state of your internet connection is. Can you at least share the message logged to the console? It's incredibly difficult to deal with bug reports based on such little information, which is we we have the bug report guidelines.

**Comment by newman321** [comment]
> Preview works offline-first so it should not matter what the state of your internet connection is.
i tried it in 3 mods totally offline and online worked fine, but connected to router wit no internet didn't worked. i will try to reproduce it again and share error here

**Comment by AshleyScirra** [comment]
Closing as no further information provided. Please re-open the issue including the requested information if you still want us to look in to this.
