### ISSUE TITLE
Invoking download of snapshot not working after apk compilation

### ISSUE THREAD

**Issue by drewford** [Scirra/Construct-3-bugs#1105]
## Problem description
After capturing a snapshot, invoking download of snapshot isn't working on Android after completing app.
*Enter a concise description of your problem here*
Downloading works while in preview but not after compile.
## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: yeno
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Downloading files is a browser feature. The browser provides the download UI (e.g. the download footer in Chrome and the Downloads page which shows progress etc). When built as an app there is no browser, so browser-related features like downloads don't work.

**Comment by Mathiasfx** [comment]
is there a way to do this in Apk in construct 3?

**Comment by AshleyScirra** [comment]
Use the Share plugin instead.
