### ISSUE TITLE
Creating huge 10k x 10k sprite and coloring it crashes C3 with Aw snap

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1107]
## Problem description

I was creating some huge sprites 10k x 10k for a test and it always crashed C3.

## Attach a .c3p

Could never save the project so you'll have to make one. Create a sprite with 10 000 x 10 000 then assign it a color like in the gif.

If it doesn't crash try to change the color or do any modification on the sprite.

I'm aware this is an unlikely scenario but a warning or something would be better than straight memory crash.

![bigspritecrash01](https://user-images.githubusercontent.com/7268697/34105533-5273fd8a-e3fd-11e7-9c41-f01b98d620f3.gif)

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.84
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
C3 release: r72
Language setting: en-US

Local storage
Storage quota (approx): 3.7 gb
Storage usage (approx): 1 gb (27%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
You're making a single sprite that uses 400mb of memory. The image editor and spritesheeting engines might need to copy it a couple of times to process it, so it's probably running out of memory or hitting some internal memory limit. Additionally at least 50% or so of devices won't even be able to create a texture that big, according to webglstats.com, so there's not much reason to do this.

We can't easily detect the out-of-memory event because JS doesn't get notified about it before it happens. We can only hard-code in limits, but last time we did this, it went out of date and started annoying everyone. (Lots of people were happy when we took off the "your project uses 1 GB of images" warning in C2.) So I don't think there's anything to be done about this.
