### ISSUE TITLE
Debug-APK don't work

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#1111]
## Problem description

The Debug-APK-Export from Construct 3 don't work on my Samsung Galaxy S7 (Android 7) and on Samsung Galaxy Note 2 (Android 5). I have create a blank new project without any events or anything.
When I launching the apk on my Phone, the Screen are black and frozen..

## Attach a .c3p

Create a blank project. Nothing works.

## Steps to reproduce

1. Create a new blank project
2. Export to Android (Debug-APK)
3. Install it on Android and launch..

## Observed result

Black Screen... (frozen)

## Affected browsers

Android APK only

## System details

Android 7 and Android 5

**Comment by AshleyScirra** [comment]
Can't reproduce, works fine here.

There's nothing we can do to help unless you provide more information. Are you sure it's not something specific to your project settings, export settings, or a certain plugin or behavior you're using? Also are you sure you've configured your device to allow debug APKs?

**Comment by AshleyScirra** [comment]
Closing as no further information provided.
