### ISSUE TITLE
Xbox Live no longer submitting scores

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#1115]
## Problem description

My previous game published a few weeks ago works fine and submits highscores, shows leaderboard and gets the current score with GetStatistic before submitting a new score to check if the new score is higher. But my new game I just published does not seem to submit any scores. I tried many things and debugging for 8+ hours but I can't find the issue. So maybe its a bug in C3 or the Xbox Plugin?

First I thought it may be a problem with SetTimescale=0 that the score is not submitted but I added a debug menu which just sets a highscore and even this one is not working. 
Or maybe its a problem with the Timeout error on SignIn? (created another report for it) 
Sign in takes 25-30 seconds and Visual Studio shows a Timeout error but it seems it still works to add local user and get profile data.

I added GetStatistics at start of menu/game to get the current stored value from Xbox Live and when the player has no lives it checks currentScore > Highscore to submit only higher values. But it returns always 0 cause no scores seem to be submitted. I tried this many times in Sandbox in Visual Studio and even in the current live version on Xbox. Even waiting a few hours did not update any leaderboard.

I removed most parts of the game to create an example project but still kept many things so you can see how I did it. If its too big let me know then I make a smaller version.
I marked the score submission with Bookmarks in eGame (Event Sheet) at the bottom part.

Layouts used:
Highscores: Get Leaderboard data but its always 0 entries, no data submitted.
Game: Submit score on death (at bottom marked with Bookmarks)
Debug: to set score values and to get number of leaderboard entries
Event Sheets:
eHighscores, eGame, eDEBUG.

**Debug menu can be opened with LB+RB+Y+DPad UP when the cursor is above santa in the main menu.**

## Attach a .c3p

[XboxLive Signin and Score Submission Issue.zip](https://github.com/Scirra/Construct-3-bugs/files/1575943/XboxLive.Signin.and.Score.Submission.Issue.zip)

## Steps to reproduce

1. use Xbox Live Submit Score action to submit a integer value
2. No error returned but no data seems to be submitted

## Observed result

No scores are submitted and leaderboard is emtpy

## Expected result

Scores should be stored in Xbox Live Leaderboard. Works fine in my other game published a few weeks ago with older Win10 SDK.

## Affected browsers

* Edge: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.84
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
C3 release: r73
Language setting: en-US

Local storage
Storage quota (approx): 27 gb
Storage usage (approx): 490 mb (1.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is not a minimal repro. I have a minimal project I use for testing Xbox Live, I updated it to the latest SDK version and it still submits and loads scores just fine. It also signs in relatively quickly (just a few seconds). So I believe our code is all working correctly.

Note Xbox Live submits statistics only every 5 minutes by default; if you want to submit a stat sooner than that, you must use the flush action some time after setting the statistic. There's no point doing this on start of layout since you won't have set any stats yet (and might not even be signed in), and the only other place your project appears to do this is in a gamepad input event, which is not a good place to do it (either it will happen unnecessarily often, or if you test it and don't press that button, the stat will not be submitted, making it an unreliable way to test).

If you have issues using the Xbox Live service it's probably best to contact Microsoft about it. I'm pretty sure our code is OK.
