### ISSUE TITLE
Google Play > Export Project Failed

### ISSUE THREAD

**Issue by luisforte** [Scirra/Construct-3-bugs#1116]
## Problem description

*If you add the Google Play plugin and try to Export to Cordova/Android the error accurs*

## Attach a .c3p
[bugoogle.zip](https://github.com/Scirra/Construct-3-bugs/files/1577200/bugoogle.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. try to export for Cordova/Android
2.
3.

## Observed result

*Failed to Export Project*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

**Comment by AshleyScirra** [comment]
Thanks, fixed for r74.
