### ISSUE TITLE
Behavior renaming isn't reflected in Actions

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#1118]
## Problem description

Rename a behavior - the new name is stored internally (it's in the c3p) but isn't updating in the actions - the old name remains.

## Attach a .c3p

[BehaviorRenaming.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1583393/BehaviorRenaming.c3p.zip)

## Steps to reproduce

1. Add a behavior. Close Dialog
2. Edit behaviors - rename behavior. Close dialog.
3. Note in Action panel that the name is still the original name (until you close and open the file again).

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
