### ISSUE TITLE
Black screen, cannot preview the project

### ISSUE THREAD

**Issue by Parth-Kadakia** [Scirra/Construct-3-bugs#1119]
## Problem description

When previewing the project I am just getting black screen.

## Steps to reproduce

1. Click on run and click on preview project.
2.
3.

## Observed result

Black screen and nothing else.

## Expected result

The project should be previewed.

## Affected browsers

* Chrome: **yes**/no
* Firefox: **yes**/no
* Edge: **yes**/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error message

root-sw.js:289 [Root-SW-Offline] Up to date
register-root-sw.js:17 Registered root service worker on https://editor.construct.net/
main.js:168 Stop!
main.js:168 This is a browser feature intended for developers. If someone told you to copy and paste something here to enable a feature or "hack" something, it is a scam and may allow them to steal your account information or your work.
www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-89204771-5&cid=1330078029.1513985326&jid=472236530&_v=j66&z=1068678196 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
main.js:168 Registered service worker on https://editor.construct.net/r73/
sw.js:288 [SW-Offline] Up to date
editor.construct.net/:1 <meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes"> - http://developers.google.com/chrome/mobile/docs/installtohomescreen

</details>

**Comment by Parth-Kadakia** [comment]
Retraced this to where I added a custom font which was causing this. So adding custom fonts is causing the app to not being previewed.

**Comment by AshleyScirra** [comment]
The error in the log is `ERR_BLOCKED_BY_CLIENT`. So it looks like you have a browser extension blocking the loading of web fonts. Unless you follow the bug report guidelines, such as by attaching an affected project, there is nothing else that can be done.

**Comment by Parth-Kadakia** [comment]
I did attach the project. I added my .c3 project file.

**Comment by AshleyScirra** [comment]
I don't see it anywhere in this report.
