### ISSUE TITLE
Spelling mistake in manual.

### ISSUE THREAD

**Issue by drg8** [Scirra/Construct-3-bugs#1120]
## Problem description
the word was supposed to be 'or' but instead it is typed 'of'.

*Enter a concise description of your problem here*

"When the host starts of stops video the client will be notified."
this is the last point in the Remote Preview section of the manual
the statement "starts of stops" should be "starts or stops".

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed.
