### ISSUE TITLE
Preload sound issue in Safari & Edge - stuck at 100%

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#1122]
## Problem description

C3 HTML exported site is stuck at 100%. There is no error logged, and nothing to indicate what the problem is. I was able to debug and found the preloading sounds code was stuck - the total never reached it's value. Was actually stuck at 0.99998... in progress (which I guess gets rounded to 100% when displayed).
Turning off preloaded sounds in C3 works around the problem.
Works in Chrome & Firefox.

## Attach a .c3p

[SafariSoundIssue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1589832/SafariSoundIssue.c3p.zip)

## Steps to reproduce

1. I had a project in C2. Imported into C3 - not sure if this is relevant.
2. Exported to HTML
3. Upload to host and test in Safari.

## Observed result

Progress reaches 100% and stays there. No errors in console.

## Expected result

Not that.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: yes
* Safari: yes

**Comment by AshleyScirra** [comment]
Safari fails to decode oneclick.m4a. It's probably corrupt, or too short (Safari has had issues with very short sounds in the past). If audio fails to load then preloading never succeeds. I'm not sure it makes sense to continue if loading failed, so I've just added in a console error that is logged if audio decoding fails. To work around this you probably need to re-encode the sound, possibly with silence padding to make it longer.
