### ISSUE TITLE
Loading Json string directly copy-paste from an exported from C3 Json doesn't work, exports it with single quotes and C3 needs it double

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#1124]
## Problem description

I exported a json file by downloading it. I opened the file in a text editor and copy-pasted the contents into Dictionary Load From Json. 

It says syntax error. I used Ashley's sample in the forums to load it and it work fine : "{""c2dictionary"":true,""data"":{""5"":1}}"

my exported string does not work, so I dug a bit deeper and it turns out it requires me to manually add double quotes on each item. When I add double quotes it works. 

This is my sample string: "{"c2dictionary":true,"data":{"sampleCoin1":"bucket:1,amount:1,value:4"}}"
this does not work.

This works : "{""c2dictionary"":true,""data"":{""sampleCoin1"":""bucket:1,amount:1,value:4""}}"

Seems to me the issue lies in the download dictionary as Json since it only adds a single quote while C3 and C2 require two. 

## Steps to reproduce

1. Download dictionary data to an external file
2. Open file with text editor, copy contents
3. Paste contents into Dictionary Load
4. Doesn't work. :p

## Observed result
Doesn't work, says "Syntax Error, are you missing something before...."

## Expected result

C3's Dictionary eating the Json data and digesting it normally into keys and values.

## Affected browsers

* Chrome: yes

## System details

Platform information
Browser: Chrome
Browser version: 63.0.3239.84
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_2
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.7999999523162842
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
C3 release: r73
Language setting: en-US

Local storage
Storage quota (approx): 6.9 gb
Storage usage (approx): 179 mb (2.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's simply that JSON data is not a valid expression. They use different syntaxes so you shouldn't expect JSON to work in an expression any more than any other expression to parse as valid JSON. You should load data from project files, anyway.

**Comment by damjancd** [comment]
I'm doing an exporter/importer on mobile. Have no idea how to do it with project files Ajax and local storage with external files.

Worst comes to worst I'll do replace() for the quote amounts :)
Thanks

**Comment by AshleyScirra** [comment]
Project files: https://www.construct.net/make-games/manuals/construct-3/project-primitives/files
AJAX: https://www.construct.net/make-games/manuals/construct-3/plugin-reference/ajax

**Comment by damjancd** [comment]
At project runtime. While the game is running.
I use both AJAX and project files for my project. But haven't figured out how to import an exported json at runtime. I'll browse the forums no worries. Would've been simpler if they had the same quote amounts though.

**Comment by AshleyScirra** [comment]
Use the File Chooser plugin to pick a file at runtime.

**Comment by damjancd** [comment]
You are a god. How did I not know this. Thank you. And it works on mobile!
