### ISSUE TITLE
Vibration does not work on Android

### ISSUE THREAD

**Issue by edrennikov** [Scirra/Construct-3-bugs#1125]
## Problem description
When I use Browser object to vibrate it does not work on Android if I build debug apk file. If I open project's preview on mobile in browser (e.g. Chrome) it works, but if I install compiled apk it does not work.

## Attach a .c3p
[Vibration test.zip](https://github.com/Scirra/Construct-3-bugs/files/1594897/Vibration.test.zip)

## Steps to reproduce

1. Create new project.
2. Add Browser object.
3. User Vibration command of Browser object.
4. Build debug apk.
5. Install this apk on Android.

## Observed result

No vibration.

## Expected result

Vibration works.

## Affected browsers

* Chrome: no
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

Meizu M5c (Flyme OS)

**Comment by AshleyScirra** [comment]
Did you enable "Require Vibrate permission" when exporting?

**Comment by edrennikov** [comment]
Sorry, I'm stupid blind, I didn't notice this permission. When I had enabled it vibration has started to work.
