### ISSUE TITLE
This is not a bug, but the C3 "Resize Image" description is misleading compared to C2

### ISSUE THREAD

**Issue by bible9230** [Scirra/Construct-3-bugs#1128]
## Problem description

In the C3 animation editor, the resize image feature is called "Resize Image" compared to C2 calling it "Resize Image Canvas".  It currently not referring to the Canvas size is misleading and gives the impression that the image itself will be resized/rescaled.

It would be consistent with C2 and clarify what it is actually doing if the descpription was changed to "Resize Image Canvas".

https://www.dropbox.com/s/agss772w9kzzk4i/20180102_105709.jpg?dl=0

**Comment by DiegoScirra** [comment]
Fixed in r75
