### ISSUE TITLE
Object negative values for size rotates fine but doesn't save

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#1129]
## Problem description

I have half circle pointed towards the upper left corner, I set values -250x-250 for size and it flips accordingly. Everyones happy. But then I save and reopen, it's back to the initial rotation +250x+250 :( probably shouldn't do that. 

I have another where only one value is negative and it works fine. 

## Attach a .c3p

[negarottest.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1600021/negarottest.c3p.zip)

## Steps to reproduce

1. Set nipple thing size values to -250x-250
2. Save
3.Close C3, Open C3, Open Project.
4. Nipple thing is back to 250x250

## Observed result

4. Nipple thing is back to 250x250

## Expected result

4. Nipple thing is not back to 250x250, it's -250x-250

## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 63.0.3239.84
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.13_2
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.600000023841858
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
C3 release: r73
Language setting: en-US

Local storage
Storage quota (approx): 6.9 gb
Storage usage (approx): 163 mb (2.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
The size is saved correctly but loaded incorrectly. It loads OK if the size is anything but the exact inverse of the animation frame size (e.g. -250 x -350 loads OK, but -250 x -250 flips it back). It looks like Diego's code in the Sprite plugin is flipping it back, so assigning to him.

**Comment by DiegoScirra** [comment]
Fixed in r76
