### ISSUE TITLE
[R21] Error when try to upload sounds&music

### ISSUE THREAD

**Issue by gpibernats** [Scirra/Construct-3-bugs#113]
## Problem description

I get an error when I try to upload a sound.

## Attach a .c3p

[errorWhenUploadMusic-21april.c3p](https://www.dropbox.com/s/k6ai2b8jrwf84lw/errorWhenUploadMusic-21april.c3p?dl=0)

## Steps to reproduce

1. Show project bar.
2. Right click on Sounds folder > Import Sounds
3. Import audio button
4. Choose a .ogg file > Open
5. ERROR

Video with steps: [video](https://www.dropbox.com/s/4vgdxne9hjvt086/errorWhenUploadMusic-21april.mov?dl=0)
 - Audio file uploaded: [collectable.ogg](https://www.dropbox.com/s/gakc7n6elku1kcu/collect.ogg?dl=0)

## Observed result

Error window.

## Expected result

Music uploaded.

## Affected browsers

* Chrome: yes
* Firefox: -
* Edge: -
* Safari: -

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: TypeError: unexpected type
Stack: TypeError: unexpected type at Function.ǃG.ǃp (https://editor.construct.net/r21/main.js:2:201263) at new ǃX$.ǃJK (https://editor.construct.net/r21/main.js:63:37818) at F.ǃoK.then.g (https://editor.construct.net/r21/components/bars/projectBar/projectBar.js:1:32116)
Construct 3 version: r21
URL: https://editor.construct.net/
Date: Fri Apr 21 2017 20:46:08 GMT+0200 (CEST)
Uptime: 708.6 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
I broke this last week when I was adding undo points to import files, etc. Import audio wasn't quite implemented correctly. I've fixed it so should be working in the next build.
