### ISSUE TITLE
AJAX request project file action does not update in event sheet view when changing the name of the file

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1130]
## Problem description

If you have AJAX requesting a project file (in this example a .json file to load into an array) and you do modify the name of the json file in the project bar, the new name does not update in the Request action in the event sheet.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
https://kyatric.com/c3/bugs/20180103-ModifyPFname.c3p

## Steps to reproduce

1. Open project.
2. Make sure to have "Event sheet 1" opened and look at it. Notice Event 1 as Action  "Request TestA.json"
3. In the "Files" folder of the project bar, select the project file, press f2 to rename it, change the name to whatever. Press enter to validate.

## Observed result
Event 1 action does not update, still indicating the previous name of the file, despite it having changed (and the tab of the file, if opened, having updated to the new name).

## Expected result
For the action to update/reflect the new name of the file.

## Affected browsers

* Chrome: yes 
* Firefox: yes 
* Edge: not tested
* Safari: note tested
r 74

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 63.0.3239.108
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
C3 release: r74
Language setting: en-US

Local storage
Storage quota (approx): 12 gb
Storage usage (approx): 702 mb (5.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for the next release.
