### ISSUE TITLE
Action "Go to Layout" does not update when changing the name of the selected layout

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1131]
## Problem description
Have a system action "Go to layout" and select a layout (for example Layout 2).
Modify the name of the layout in the project bar. The action still displays "Go to Layout 2" instead of the new layout name.

## Attach a .c3p
Can be created from scratch. Open a new project, add a new layout, no new even sheet is required.
In Event Sheet 1 create an event "On start of layout" (or whatever condition).
Add the action "System: Go to layout" select "Layout 2".

## Steps to reproduce

1. Select Layout 2 in the project bar.
2. Change the name of Layout 2 to whatever.
3. Validate (press enter)

## Observed result

In Event sheet 1 the action still displays as "Go to Layout 2"

## Expected result

In Event sheet 1 the action to display as "Go to whatever"

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: Not tested
* Safari: Not tested

R74

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, also fixed for the next release.
