### ISSUE TITLE
Cordova options dialog not fully translatable

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#1133]
Ref: https://www.scirra.com/forum/congratulations-on-completing-the-russian-translation_p1156081?#p1156081

Terms like "Min. version", "Android build", "URL whitelist", "Cordova project" etc. should be translatable.

**Comment by kop9000** [comment]
and here's another

https://www.scirra.com/forum/congratulations-on-completing-the-russian-translation_p1152278?#p1152278

**Comment by AshleyScirra** [comment]
Fixed for r76. The new terms are already on POEditor.
