### ISSUE TITLE
Safari 11 + Mac OS 10.11.6 + Construct 3 r74, elements fail to render in game

### ISSUE THREAD

**Issue by arloft** [Scirra/Construct-3-bugs#1134]
## Problem description

Discovered the latest release of Construct (3) and was excited to be able to use it on my Mac (dabbled with C2). However, I have noticed that Construct 3 doesn’t seem to work very well with Safari 11, despite claims on the Construct site stating otherwise. 

With some of the demo / example projects on the Start Page within the editor, parts of the game (sprites, etc) don’t render at all. I’m using Safari 11.0.2 on Mac OS X 10.11.6 (El Capitan). I’ve attached a link to a screen recording where you can see the Platformer example project render only black type on a white background, no other game elements are rendered at all. This isn’t the only example project that exhibits this strange behavior. 

I’ve turned off any content blockers for the construct.net domain within Safari to rule that out. I have Safari updated to its latest version as well.

Link to screen recording: https://www.dropbox.com/s/ni6wyqmut29pxcg/Safari%2011.0.2%20render%20issue%20Mac%20OSX%2010.11.6.mp4?dl=0

## Attach a .c3p

https://editor.construct.net > Start Page > Templates > "Platformer"

## Steps to reproduce

1. In Safari 11 on Mac OSX 11.10 (El Capitan), open URL editor.contruct.net
2. Click "Start Page" tab, click "Templates" on left hand side of Start Page screen
3. Open Project "Platformer", click "Run" button
4. No elements (sprites, graphics) render at all except black text object, all else is white (see screen recording linked above)
5. Tested in new Mac OS X user account, all content blockers disabled; same result

## Observed result

Game renders as white screen, only singular black text object "Arrow keys or WASD to move" is displayed.
Game "debug layout" panel shows all elements are present, yet none are rendered to the screen on preview.construct.net

## Expected result

Default "Platformer" game template launches, renders, and plays as designed by Scirra team

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: unknown (non-Mac browser)
* Safari: yes

## System details

- No crash report. Safari's Inspector displays the following under the "Console" tab:

[Error] Viewport argument key "minimal-ui" not recognized and ignored. (editor.construct.net, line 11)
[Log] Stop! (main.js, line 168)
[Log] This is a browser feature intended for developers. If someone told you to copy and paste something here to enable a feature or "hack" something, it is a scam and may allow them to steal your account information or your work. (main.js, line 168)
[Info] [WebGL] Shader program '<default>' compilation log: WARNING: Could not find vertex shader attribute 'webgl_359fbc7d00000008' to match BindAttributeLocation request. (main.js, line 63)
[Info] [WebGL] Shader program '<default-device-transform>' compilation log: WARNING: Could not find vertex shader attribute 'webgl_359fbc7d00000008' to match BindAttributeLocation request. (main.js, line 63)
[Info] [WebGL] Shader program '<point>' compilation log: WARNING: Could not find vertex shader attribute 'webgl_351d81300000005' to match BindAttributeLocation request.WARNING: Could not find vertex shader attribute 'webgl_defda7d800000004' to match BindAttributeLocation request. (main.js, line 63)
[Info] [WebGL] Shader program '<fill>' compilation log: WARNING: Could not find vertex shader attribute 'webgl_359fbc7d00000008' to match BindAttributeLocation request.WARNING: Output of vertex shader 'vTex' not read by fragment shader (main.js, line 63)
[Info] [WebGL] Shader program '<smoothline>' compilation log: WARNING: Could not find vertex shader attribute 'webgl_359fbc7d00000008' to match BindAttributeLocation request. (main.js, line 63)
[Info] [WebGL] Shader program '<tilemap>' compilation log: WARNING: Could not find vertex shader attribute 'webgl_359fbc7d00000008' to match BindAttributeLocation request. (main.js, line 63)
[Error] Unable to post message to https://preview.construct.net. Recipient has origin https://editor.construct.net. (x4)

[Error] Viewport argument key "minimal-ui" not recognized and ignored. (index.html, line 6)
[Log] Using WebGL renderer: Intel HD Graphics 3000 OpenGL Engine [Intel Inc.] (preview_prelude.js, line 56)
[Log] Shader '<fill>' log: WARNING: Output of vertex shader 'vTex' not read by fragment shader (preview_prelude.js, line 56)

[Log] Max texture size: 4096 (preview_prelude.js, line 56)
[Log] Point size range: 1 to 255 (preview_prelude.js, line 56)
[Log] WebGL extensions:  (glwrap.js, line 404)
[Error] Viewport argument key "minimal-ui" not recognized and ignored. (debug.html, line 6)
[Error] Viewport argument key "minimal-ui" not recognized and ignored. (index.html, line 6)
[Warning] Unexpected message type 'boot-ready' (bootpreview.js, line 8)
[Log] Using WebGL renderer: Intel HD Graphics 3000 OpenGL Engine [Intel Inc.] (preview_prelude.js, line 56)
[Log] Shader '<fill>' log: WARNING: Output of vertex shader 'vTex' not read by fragment shader (preview_prelude.js, line 56)

[Log] Max texture size: 4096 (preview_prelude.js, line 56)
[Log] Point size range: 1 to 255 (preview_prelude.js, line 56)
[Log] WebGL extensions:  (glwrap.js, line 404)
[Error] Viewport argument key "minimal-ui" not recognized and ignored. (index.html, line 6)
[Log] Using WebGL renderer: Intel HD Graphics 3000 OpenGL Engine [Intel Inc.] (preview_prelude.js, line 56)
[Log] Shader '<fill>' log: WARNING: Output of vertex shader 'vTex' not read by fragment shader (preview_prelude.js, line 56)

[Log] Max texture size: 4096 (preview_prelude.js, line 56)
[Log] Point size range: 1 to 255 (preview_prelude.js, line 56)
[Log] WebGL extensions:  (glwrap.js, line 404)
Array (18)
0 "EXT_blend_minmax"
1 "EXT_sRGB"
2 "EXT_frag_depth"
3 "OES_texture_float"
4 "OES_texture_float_linear"
5 "OES_texture_half_float"
6 "OES_texture_half_float_linear"
7 "OES_standard_derivatives"
8 "EXT_shader_texture_lod"
9 "EXT_texture_filter_anisotropic"
10 "OES_vertex_array_object"
11 "OES_element_index_uint"
12 "WEBGL_lose_context"
13 "WEBGL_compressed_texture_s3tc"
14 "WEBGL_depth_texture"
15 "WEBGL_draw_buffers"
16 "ANGLE_instanced_arrays"
17 "WEBGL_debug_renderer_info"

Array Prototype
> Selected Element
< <body style="background-color: rgb(0, 0, 0);">
<div id="fb-root"></div>
<canvas height="401" style="width: 535px; height: 401px; margin-left: 141px; margin-top: 0px;" width="535">
</body>

![safari 11 render issue white screen](https://user-images.githubusercontent.com/2423302/34536720-110e1300-f094-11e7-91ac-eb91d008c55d.png)
![1 view start page tab](https://user-images.githubusercontent.com/2423302/34536795-5347aaba-f094-11e7-816a-7e04ab21df2f.png)
![2 open project platformer template](https://user-images.githubusercontent.com/2423302/34537150-878af8b2-f095-11e7-9e20-5897396927b9.png)
![mac system browser affected versions](https://user-images.githubusercontent.com/2423302/34536976-eef4a1e8-f094-11e7-96d3-1633a1a428e5.png)

<details><summary>View details</summary>
</details>

**Comment by AshleyScirra** [comment]
I can't reproduce this on a Mid-2015 MacBook Pro with Safari 11. I strongly suspect this is a graphics driver bug. The last Safari-only display glitch we had was a graphics driver issue (https://bugs.webkit.org/show_bug.cgi?id=178348), the fact it works in Chrome and Firefox suggests our code is correct and the problem is in Safari, and the fact it works on our own MacBook suggests its a device/OS-specific issue only (which is the case with graphics driver bugs).

There's not much we can do about this - your best bet is to update to Sierra or High Sierra.
