### ISSUE TITLE
"This project exceeds the free edition limits" when I try to add an event (0 events)

### ISSUE THREAD

**Issue by yojona** [Scirra/Construct-3-bugs#1135]
## Problem description
I made a copy of a project to reuse the assets, I erased all event sheets and I create an empty one, when I try to add an event an alert prompt with text ""This project exceeds the free edition limits" 
## Attach a .c3p

[copy2.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1603943/copy2.c3p.zip)

## Steps to reproduce

1. Save project as another one
2. Erase events
3. Create another events.

## Observed result
Alert prompt with text "This project exceeds the free edition limits" 

## Expected result
Reset events count

## Affected browsers
* Chrome: yes

## System details

MacOS High Sierra
Google Chrome 63.0.3239.108
Construct 3 Editor r74

**Comment by AshleyScirra** [comment]
The provided project uses a third-party addon (Animated Counter). Please provide a project not using it, as per the bug report guidelines.

**Comment by yojona** [comment]
I updated the attachment.

**Comment by AshleyScirra** [comment]
The new attachment has no events, so I can't follow step 2 ("Erase events"). Did you upload the right file?

**Comment by yojona** [comment]
Sorry, I made this report wrong, I can not reproduce the problem, the previous steps are actually what I did to create the attached .c3p file, which has no events. BUT that's the thing, it has no events, and when I try to add one... "This project exceeds the limits of the free edition"

EDITED:

The problem was 3 instances of 1 SpriteText object with 1 effect. Please close this report. I'll be careful next time.
