### ISSUE TITLE
[R21] Mobile - Sprite Editor / Color Editor

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#114]
## Problem description

I modify RGB values via keyboard: at the end focus go to the animations section but it's difficult for me to return to the color palette.

Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Go to the color palette
2. Insert rgb values via keyboard
3. Confirm with the keyboard

## Observed result

See the video

https://youtu.be/64lNOA6_AyE
[![](https://img.youtube.com/vi/64lNOA6_AyE/0.jpg)](https://www.youtube.com/watch?v=64lNOA6_AyE)

## Expected result

Don't exit the color palette

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.132
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Android
Operating system version: 6.0.1
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 3
Logical CPU cores: 6
User agent: Mozilla/5.0 (Linux; Android 6.0.1; Redmi Note 3 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.132 Mobile Safari/537.36

Local storage
Storage quota (approx): 332 mb
Storage usage (approx): 1.6 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: Qualcomm
Renderer: Adreno (TM) 510
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_disjoint_timer_query
EXT_sRGB
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_atc
WEBKIT_WEBGL_compressed_texture_atc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The Android keyboard probably shouldn't lock up the UI like that, but Chrome should soon be changing the keyboard to not cause layout changes which is what causes the UI to crunch up vertically: https://bugs.chromium.org/p/chromium/issues/detail?id=404315
We might want to wait for that change since it should make keyboard use on Android much more sensible.

**Comment by AshleyScirra** [comment]
Closing as same problem as #138
