### ISSUE TITLE
Global constant variables - ALLCAPS

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1140]
## Problem description

Do global constant variables really have to be all caps? I like to write in camel case so that just ends up looking meh.

## Attach a .c3p

🌾 

## Steps to reproduce

1. make global constant variable
2. all small letters GETBIGANDUGLY

## Observed result

CAPSISLIKESCREAMING

## Expected result

Keep the name with small and big letters as I type it, there´s gotta be a better way to discern between constant and non-constant vars.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.84
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
C3 release: r75
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 99 mb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is by design - it's a common convention in several programming languages to use uppercase characters for constants, and C3 follows this convention as well. I do think it's useful to distinguish constants some way. Do you think there's a better way this could be done?

**Comment by Wackytoaster** [comment]
That convention is probably as old as programming languages, might aswell use a floppy disk to represent "saving" ;)
![b](https://user-images.githubusercontent.com/31101309/34684170-866aee2a-f4a4-11e7-9225-9c79e37294b3.PNG)

- The variable itself is already defined as 'Global constant number'
- You cannot use any Set-actions on constant vars, so no room for error here and I think this is the main reason for that convention to exist. Conventional programming languages have nothing to prevent you from trying to do that.

It defenitely is useful when comparing them or setting something to their value, but at that point you might aswell underline them or add a small ascii symbol to represent their constantness (is that a word?). Otherwise, if someone wants to use uppercase, he can choose to do so, and if someone doesn´t want to use uppercase, he should also be able to choose to do so. In javascript I can also use 'const' to define a constant, but I´m not forced to declare it in uppercase.

**Comment by AshleyScirra** [comment]
OK, removed the restriction for r78.
