### ISSUE TITLE
Problem Preloading Sounds

### ISSUE THREAD

**Issue by time-traveler01** [Scirra/Construct-3-bugs#1145]
## Problem description

*I'm having issue regarding implementing the audio plugin.I tried to export it on android debug mode  after adding audio whenever I checked the preload sounds the game just stop loading on the splash screen but after unchecking the preload the game loads but the background music and some audio seem to be not playing right.Example: When the preload sounds is unchecked "Player bump to enemy,audio should play here."PS: My Original construct file was converted from C2 to C3*

## Attach a .c3p

[Audio Preload.zip](https://github.com/Scirra/Construct-3-bugs/files/1608683/Audio.Preload.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.Open/Install the apk
2.Run the app
3.Wait to load 

## Observed result

*What do you see happen?
Preload is Checked:On android phone the game stop loading on the splash screen.
Preload is Unchecked:The game loads but the music and sounds not working properly or not playing at all.
On browser preview : Doing fine.
On Windows preview:Same result but sometimes not sure exactly.

*

## Expected result
The game load and music/audio play whenever preload is checked.
*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
If preloading is enabled and the audio file cannot be decoded then the game will fail to start, and given that the audio is not playing when preloading is disabled I think we can be fairly sure this is the problem. 

What version of Android are you running?

**Comment by shortercode** [comment]
Additionally can you check that your version of Android WebView is up to date.

**Comment by time-traveler01** [comment]
I'm using android 5.1 for testing.

**Comment by shortercode** [comment]
Originally Android 5.1 did not have opus support, but it was updated to have it a fair while ago. Did you check for a WebView update?

**Comment by shortercode** [comment]
@time-traveler01 do you have any more information for me?

**Comment by time-traveler01** [comment]
Sorry for the late reply I've been busy for some other stuff.If you mean the android webview app on the phone that is downloadable on the playstore I've been using the latest version but got the same result.As for the C3 r77 version , I will try to test it tomorrow If I got the same issue I will update you immediately

**Comment by shortercode** [comment]
No worries, thanks for getting back to me. That's unusual, could be that your device just doesn't have opus decoding for some reason. Their haven't been any changes to the audio runtime for r77 so it's probably not worth you retesting your example.

Instead could you try running this test project as an android app for me?

[opustest.zip](https://github.com/Scirra/Construct-3-bugs/files/1623354/opustest.zip)

It should display an alert saying either "can play opus" or "cannot play opus" based on what the browser claims to be able to do, and once the alert is dismissed it will show the useragent.

**Comment by time-traveler01** [comment]
I tested your project and the display message is "cannot play opus".

Useragent:Mozilla/5.0(Linux;Android 6.0.1)AppleWebkit/537.36(KHTML,like Gecko)Chrome/52.0.2743.98 Mobile Safari/537.36 Construct/7700

**Comment by shortercode** [comment]
Ah... I remembered we have an override in place for the useragent, so it's all fake :/

At least we confirmed that it can't play opus. If I sent you an APK for the same project, but without the useragent override would you be happy to run it?

**Comment by time-traveler01** [comment]
Yes just send me the project.I also tested my project on another device an Android 6.0.1 Tablet the sounds run fine but I just notice something I only got 45-48 FPS I don't know if there is a problem on my implementation or I just miss something but the app runs smoothly on my android phone 5.1 it's about 58-60 FPS the only problem in there is I cannot preload the sounds.

**Comment by shortercode** [comment]
There is a bug that affects a small number of Android devices that the apps C3 produces run slowly, it's been open a fair while but I haven't been able to replicate it and I'm unsure what could be causing it. I might take another look at it later today.

**Comment by time-traveler01** [comment]
Here's the new useragent
Mozilla/5.0(Linux;Android 5.1;Excite Prime Build/LMY47I)AppleWebKit/537.36(KHTML,like Gecko)Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36
