### ISSUE TITLE
Unintuitive behaviour when selecting specific instance of an object

### ISSUE THREAD

**Issue by dru1000** [Scirra/Construct-3-bugs#1147]
## Problem description
Select the object in the project tree then select an instance of that object on the layout. If you then change the instance variable it changes for all instances. 

Because the last action was to select a specific instance shouldn't it just effect the instance selected? It seems all instances remain selected until I click out of the object in the tree.

## Attach a .c3p

[variables test.zip](https://github.com/Scirra/Construct-3-bugs/files/1609543/variables.test.zip)

## Steps to reproduce

1. Select the object in the project tree
2. Select an instance of the object in the layout
3. Change the instance variable

## Observed result

All instances of the object are updated with the new var

## Expected result

Only the instance variable should change, not the object variable (all instances)

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
It's working as designed. I think you are expecting step 2 to unselect all instances other than the one you clicked. The layout view does not do this. It's the same as if you hold control and select both instances, then click on the other one again - it doesn't unselect anything, and it would probably be irritating if it did. The properties bar also clearly marks the instance variable field with "(multiple)" indicating there is a multiple selection with differing values, so you know ahead of time that changing it will overwrite varying values.
