### ISSUE TITLE
Just created first object in function is not accessible in subevent

### ISSUE THREAD

**Issue by edrennikov** [Scirra/Construct-3-bugs#1149]
## Problem description

If first object of its type is created in function, then it is not accessible in the same subevent after function call. But in the next event it's accessible.

## Attach a .c3p

[Test_objects.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1609910/Test_objects.c3p.zip)

## Steps to reproduce

1. Open attached project.
2. Run it.

## Observed result

Output on screen:

> debug 1: 0
> debug 2: 0
> debug 3: 1

## Expected result

Output on screen should be:

> debug 1: 1
> debug 2: 1
> debug 3: 1

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

MacOS, Chrome 63.0.3239.84

It is worth to note that if you disable first step when all instances of sprite are deleted, then it works ok:

> debug 1: 2
> debug 2: 2
> debug 3: 2

Note that count is 2 because there are two instances: one I've put on layout and another one was created during project run.

But in my project I don't need other instances, so I delete them at startup to not to mess with them. Construct 3 requires that at least one instance of sprite to be placed on layout before running the project, so I have to put it on layout, but after project is started I remove all instances and create them when they are needed but I can not access just created instances in the same subevent.

**Comment by AshleyScirra** [comment]
This is a known limitation in the event engine: https://www.scirra.com/forum/bug-with-object-creation-and-selection-in-the-same-event_t102154
