### ISSUE TITLE
[R21] Crash when renaming an animation subfolder

### ISSUE THREAD

**Issue by Magistross** [Scirra/Construct-3-bugs#115]
## Problem description

Inside the animation editor, renaming an animation subfolder will crash Construct.

## Attach a .c3p

Can be reproduced rapidly in a blank project with a sprite object.

## Steps to reproduce

1. Add a sprite object
2. Add an animation subfolder
3. Try renaming it

## Observed result

Crash.

## Expected result

Folder is renamed, no crash occuring.

## Affected browsers

* Chrome: yes

## System details
<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: TypeError: re.ǃSF is not a function
Stack: TypeError: re.ǃSF is not a function at ee.ǃ_Dh.ǃ_nE (https://editor.construct.net/r21/main.js:63:284017) at ae.ǃGgZ.ae.ǃJC.then.re (https://editor.construct.net/r21/main.js:63:279911)
Construct 3 version: r21
URL: https://editor.construct.net/
Date: Fri Apr 21 2017 16:43:53 GMT-0400 (Est (heure d’été))
Uptime: 239.7 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.110
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r22.
