### ISSUE TITLE
Webgl crash on google chrome

### ISSUE THREAD

**Issue by tyler3327** [Scirra/Construct-3-bugs#1150]
## Problem description

*Just starting a few hours ago I have been having construct 3 crash on me constantly.
I did find a temporary solution if i restart my computer it will work for about an hour than crash.
Google chrome displays "Oh Darn it looks like webgl has hit a snag!"
Its strange I restarted my laptop after it stopped working  it would work for a few minutes of the level
Then it would crash again.*

Also in the middle of testing my game and it says webgl hit a snag it doesn't just cause the game to crash it causes construct 3 browser to crash also.

## Steps to reproduce

1.Random after using construct 3 for too long
2.
3.

## Affected browsers

* I have only tried this in chrome browser. Chrome is updated to latest version and ran a system cleanup 
and cleared cookies etc anything I could do to check and see if it was just me.

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This means either Chrome or your graphics driver has crashed. I'm afraid there's nothing we can do about that. Try updating your graphics drivers or installing any available system updates.
