### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kop9000** [Scirra/Construct-3-bugs#1152]
log

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃbKz' of null @ TypeError: Cannot read property 'ǃbKz' of null at b.ǃKua (https://editor.construct.net/r75/main.js:63:244769) at b.ǃKXk (https://editor.construct.net/r75/main.js:63:76825) at b.ǃKXk (https://editor.construct.net/r75/main.js:63:156925) at b.ǃKXk (https://editor.construct.net/r75/main.js:63:244452) at b.ǃlu (https://editor.construct.net/r75/main.js:63:76743) at b.ǃlu (https://editor.construct.net/r75/main.js:63:244364) at window.ǃGN.ǃw$ (https://editor.construct.net/r75/components/bars/projectBar/projectBar.js:1:10083) at 
Stack: TypeError: Cannot read property 'ǃbKz' of null at b.ǃKua (https://editor.construct.net/r75/main.js:63:244769) at b.ǃKXk (https://editor.construct.net/r75/main.js:63:76825) at b.ǃKXk (https://editor.construct.net/r75/main.js:63:156925) at b.ǃKXk (https://editor.construct.net/r75/main.js:63:244452) at b.ǃlu (https://editor.construct.net/r75/main.js:63:76743) at b.ǃlu (https://editor.construct.net/r75/main.js:63:244364) at window.ǃGN.ǃw$ (https://editor.construct.net/r75/components/bars/projectBar/projectBar.js:1:10083) at 
Construct 3 version: r75
URL: https://editor.construct.net/index.html
Date: Mon Jan 08 2018 22:18:07 GMT+0300 (Романское время (зима))
Uptime: 37.7 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r75
Language setting: ru-RU

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
There's very little to go on here. Based on the fact the error message looks like a crash in r75 that should be fixed in r76, closing.
