### ISSUE TITLE
Problem with Y position in a unbounded scrolling

### ISSUE THREAD

**Issue by dimielannes** [Scirra/Construct-3-bugs#1153]
[ChickenJump109.zip](https://github.com/Scirra/Construct-3-bugs/files/1613419/ChickenJump109.zip)

## Problem description

in a simple game of infinite jump, putting the value y in relation ViewportBottom appears a problem putting value y wrong after entering and negative
--------------------------------
em um simples jogo de infinito pulo, colocando o valor y em relação ViewportBottom aparece um problema colocando valor y errado apos entrar em y negativo

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. jumping with player
2. after 9 jumps stopt work

## Observed result

sprite y set 888 

## Expected result

but the correct is -101

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes/no
* Safari: yes/no

**Comment by dimielannes** [comment]
![erro](https://user-images.githubusercontent.com/8438162/34697961-b22c55ae-f4bc-11e7-9aa5-ce82424ed86c.jpg)

**Comment by AshleyScirra** [comment]
This just looks like a mistake in your events. Please produce a minimal project as per the guidelines if you want us to investigate a bug, or post to the forum for general help with events. Additionally it's unclear why you expect a different Y position to what you get, the .c3p file does not include any browser logging as your screenshots show, and in the debugger you are inspecting block IID 6 and expressions will by default retrieve IID 0.

**Comment by dimielannes** [comment]
this problem occurs with any sprite by putting the Y less than -101, the program automatically switches to 888
