### ISSUE TITLE
CSS file is not imported with plugin SDK

### ISSUE THREAD

**Issue by armaldio** [Scirra/Construct-3-bugs#1155]
## Problem description

CSS file is not imported.

```js
this._info.AddFileDependency({
    filename: "file.css",
    type: "external-css"
});
```

## Attach a .c3p

[Project](https://drive.google.com/file/d/1x8MG0V-5uianFMDl4YZeM484Onk8H5R7/view?usp=sharing)
[Minimal plugin](https://drive.google.com/file/d/1Qp2BCFtnCMSKe02X-lg6Bbh6r1gYVgrl/view?usp=sharing)

## Steps to reproduce

1. Create a plugin
2. Add 
```js
this._info.AddFileDependency({
				filename: "notifier.css",
				type: "external-css"
}); 
```

to the constructor of the plugin
3. Add your css file at the root of the plugin directory
4. Import your plugin inside the editor

## Observed result

Css file is not loaded

## Expected result
CSS file should be loaded and added to the DOM as style element as mentioned in the [doc](https://www.construct.net/fr/make-games/manuals/addon-sdk/reference/specifying-dependencies): 

```
external-css

A stylesheet dependency that is included via the addition of an extra <link rel="stylesheet"> tag in the exported HTML file, in case the addon needs to specify CSS styles.
```

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
When you say "Css file is not loaded", what exactly are you doing? It looks like it correctly adds the CSS file on export, but not during preview. Does that match what you're seeing? Or are you looking somewhere else?

**Comment by armaldio** [comment]
I don't remember what was the behavior on export
Tho, during preview, I can't  find the css inside the différents tabs of
chrome (neither network nor elements) and its not added to the DOM

**Comment by AshleyScirra** [comment]
OK, the problem where external-css files are not loaded in preview mode should be fixed in r80. As far as I can tell though, exporting is already working.
