### ISSUE TITLE
Importing music doesn't work

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#1157]
## Problem description

Cannot import audio file, encoding shows complete, but import button is disabled.
Tried with a blank project either.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. import any audio to the music folder
2. 
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here, works fine in r76.2. Did you check r76.2 or r76? We already did an update today that ought to fix this. Please remember to include all the information we ask for since this would have answered the question.

**Comment by shortercode** [comment]
Think I've found it, seems that importing m4a files doesn't enable the button **sigh**

**Comment by Ind1eed** [comment]
MP3 files doesn't work as well.

**Comment by Ind1eed** [comment]
Importing MP3 files doesn't enable the button as well.

**Comment by Ind1eed** [comment]
By the way i checked in both, R76.2 and r76, doesn't work in both.

**Comment by AshleyScirra** [comment]
@Ind1eed can you confirm you are importing a .m4a file? I could not reproduce with a .wav file, and your steps to reproduce say it works with any audio.

**Comment by Ind1eed** [comment]
Excuse me, i checked only with MP3 file. WAV files works fine.

**Comment by shortercode** [comment]
It only occurs with audio types that are included without conversion ( m4a & mp3 ). The dialog doesn't count them when trying to decide if there's any files to add, I've fixed it for the next release.

I guess in the mean time your could work around it by including a wav file in the import, then deleting it afterwards.
