### ISSUE TITLE
No dropdown list in expression editor when enabling/disabling an effect

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#1158]
## Problem description

Normally when using the expression editor and you want to access the name of something, as you start typing a drop down list will appear, but this does not occur when dealing with Effects, in particular when enabling/disabling them with events.

## Attach a .c3p

[effectdisable.zip](https://github.com/Scirra/Construct-3-bugs/files/1618046/effectdisable.zip)

## Steps to reproduce

1. apply effects to a sprite or family
2. go to actions to disable the effect 

## Observed result

![image](https://user-images.githubusercontent.com/5744908/34762605-6d395aba-f63c-11e7-96fa-c0dadaa35eaf.png)

## Expected result

I want to see a list of the effects, so I know what to type in this field, this would be consistent with the way everything else works.

![image](https://user-images.githubusercontent.com/5744908/34762572-525c0e22-f63c-11e7-926d-63fd12babae6.png)

![image](https://user-images.githubusercontent.com/5744908/34762675-ae1ab704-f63c-11e7-81e0-31ef4973f674.png)

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
This is the same way it worked in C2, so this is a suggestion, not a bug. I think it was already suggested here: https://construct3.ideas.aha.io/ideas/C3-I-338 - but that post confusingly seems to mix up the terms "effects" and "behaviors". I think they mean the same thing though...

**Comment by alastajj** [comment]
"it's not a bug it's a feature" classic developer

**Comment by alastajj** [comment]
"it's a feature not a bug" classic developer.

Also just because the editor is behaving the same way as C2 is a poor argument, I'm using a product called C3.

**Comment by AshleyScirra** [comment]
It's a feature request. We generally don't use the bug tracker for features, we have the feature suggestion platform for that.
