### ISSUE TITLE
"Enabled" button missing for effects in layout editor

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#1159]
## Problem description

Unlike behaviors, effects are missing the enabled button while in the layout editor and can only be accessed by events, which is inconsistent and unexpected behavior from the software.

## Attach a .c3p

[effectdisable.zip](https://github.com/Scirra/Construct-3-bugs/files/1618062/effectdisable.zip)

## Steps to reproduce

1. Click on a sprite which has an effect

## Observed result

No enabled button.

![image](https://user-images.githubusercontent.com/5744908/34762974-cfa3aaec-f63d-11e7-87af-20d85dbdc830.png)

## Expected result

Like how the solid behavior has an enabled button, so should effects that you add

![image](https://user-images.githubusercontent.com/5744908/34763027-fe594cf2-f63d-11e7-9097-80f2513571b7.png)

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
It's not a bug, it's the same as it worked in C2. Since it's a feature suggestion it would be better filed here: https://construct3.ideas.aha.io/
