### ISSUE TITLE
Construct 3 crashed :-/

### ISSUE THREAD

**Issue by wirelesstkd** [Scirra/Construct-3-bugs#116]
I dunno what happened - following along on a YouTube tutorial (my first Construct project) and the whole thing crashed. No biggie, really. I wasn't too far in, and I don't mind re-creating it because I'll actually learna little better that way. But hopefully you figure out why and prevent it from happening again.

Here's the message it gave me:

Error report information
Type: unhandled rejection
Reason: TypeError: Right-hand side of 'instanceof' is not an object
Stack: TypeError: Right-hand side of 'instanceof' is not an object at Function.ǃS.ǃpf (https://editor.construct.net/r20/main.js:2:201429) at Function.ǃS.ǃl (https://editor.construct.net/r20/main.js:2:201553) at Function.ǃS.ǃnw (https://editor.construct.net/r20/main.js:2:201628) at te.ǃSNw (https://editor.construct.net/r20/main.js:61:274378) at window.ǃtwX.ǃSAw (https://editor.construct.net/r20/main.js:61:335532) at window.ǃtwX.Set (https://editor.construct.net/r20/main.js:61:335679) at ǃS.ǃtRN.then.r (https://editor.construct.net/r20/components/editors/eventSheetView/eventSheetView.js:1:67894)
Construct 3 version: r20
URL: https://editor.construct.net/
Date: Fri Apr 21 2017 20:08:32 GMT-0400 (Eastern Daylight Time)
Uptime: 82310.1 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
Closing as it's the same error as #107 which is already fixed in r21, and you're still using r20. Update C3 and it shouldn't happen again.
