### ISSUE TITLE
Can't open Construct 3 Project anymore

### ISSUE THREAD

**Issue by BrunrT** [Scirra/Construct-3-bugs#1161]
## Problem description
I can’t open my construct 3 project anymore as long as it was open I could freely work with it, after i closed it after a day i can‘t open it anymore. I already tried to open it with other Versions, didn't work.

## Attach a .c3p

Current Project:
https://www.dropbox.com/s/fycpyny5kymguem/Fehler%20bei%20%C3%B6ffnen.c3p?dl=0
 
latest Project save, I could open:
https://www.dropbox.com/s/k7aktrou7g82dn6/latest%20save%20I%20can%20open.c3p?dl=0

oldest save, I can’t open anymore:
https://www.dropbox.com/s/8qepukl4vx5ccj9/oldest%20save%20i%20cant%20open%20anymore.c3p?dl=0

## Steps to reproduce

1. open project
2.
3.

## Observed result

I get an Error and it doesn't open:
![screen](https://user-images.githubusercontent.com/9051865/34774939-39a7d22c-f609-11e7-91dd-e58a65b94761.png)

## Expected result

The project opens

## Affected browsers

* Chrome: yes
* Firefox: tested, didn't work
* Edge: no
* Safari: no

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: invalid frame index @ Error: invalid frame index at s.ǃsZZ (https://editor.construct.net/r76-2/main.js:63:197551) at s.ǃspf (https://editor.construct.net/r76-2/main.js:63:201572) at s.ǃMD (https://editor.construct.net/r76-2/main.js:63:201662) at s.ǃsZN (https://editor.construct.net/r76-2/main.js:63:201832) at s.ǃJY (https://editor.construct.net/r76-2/main.js:63:193940) at t.ǃzVE.then (https://editor.construct.net/r76-2/main.js:63:180418) at 
Stack: Error: invalid frame index at s.ǃsZZ (https://editor.construct.net/r76-2/main.js:63:197551) at s.ǃspf (https://editor.construct.net/r76-2/main.js:63:201572) at s.ǃMD (https://editor.construct.net/r76-2/main.js:63:201662) at s.ǃsZN (https://editor.construct.net/r76-2/main.js:63:201832) at s.ǃJY (https://editor.construct.net/r76-2/main.js:63:193940) at t.ǃzVE.then (https://editor.construct.net/r76-2/main.js:63:180418) at 
Construct 3 version: r76.2
URL: https://editor.construct.net/
Date: Wed Jan 10 2018 03:36:18 GMT+0100 (Mitteleuropäische Zeit)
Uptime: 774.4 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r76.2
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 760 (192-bit) Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Fixed the crash when loading Fehler bei offnen, @DiegoScirra is working on the issue with the project.

**Comment by DiegoScirra** [comment]
Fixed in r77. 

@BrunrT 

You will be able to open your project in the next release. We do regular releases, so it shouldn't take too long.

**Comment by BrunrT** [comment]
ok thx
