### ISSUE TITLE
"script minify" idea

### ISSUE THREAD

**Issue by kop9000** [Scirra/Construct-3-bugs#1165]
I was not helped with the problemma about "script minify", I asked what to do next, but they did not answer me. but I have an idea

Add a verification system for the availability of archeology of physics. if this behavior exists, then the setting "script minify" automatically becomes inactive.

You can even add a snippet when the mouse cursor hovers to this setting when it is not active. So I even helped translate a new line into Russian for hints

"In your project, there seems to be a behavior that will disrupt the launch of the project." Script minify "is not able to work normally with behavior such as physics."

**Comment by AshleyScirra** [comment]
This isn't a bug report, so closing. We would rather fix the bug than spend time on mitigations, which could take as long as fixing the bug to develop anyway.
