### ISSUE TITLE
MP4s don't work in Desktop/NW.js

### ISSUE THREAD

**Issue by phillnexus** [Scirra/Construct-3-bugs#1166]
My game starts with a video. I am using an MP4 since every modern browser now supports it. My project almost **entirely** depends on video - you get to choose your path between levels and videos play of the actions you take.

When I preview in Chrome, it works fine. When I export with NW.js, nothing happens when I launch the game. There's an event for when the video ends, and since the video never starts (or ends), it never progresses. I have tried setting them to both play and autoplay. I have tried adding an object that plays the video on click. I can't seem to play it no matter what I do.

[Attached: c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1621105/c3p.zip)

## Steps to reproduce

1. Open file
2. Export for Desktop/NW.js
3. Observe that the video doesn't play

## Observed result

The video doesn't play at all

## Expected result

The video should autoplay like it does in Chrome/FF.

**Comment by phillnexus** [comment]
Also, when detecting 'on video end' on my 3 minute clip, it generally lingers for 3-4 seconds after a video has ended, which delays the call to go to the next layout with a frozen frame...

**Comment by AshleyScirra** [comment]
MP4 is a patent-encumbered format. It's not actually supported by all platforms, such as NW.js. You have to use open codecs, because NW.js is an open-source project, and hasn't paid the patent license fees like other browsers have.

**Comment by phillnexus** [comment]
Can you show me where this is mentioned on either the NW.js or Video area of your documentation? This is the only reason I purchased Construct 3

**Comment by AshleyScirra** [comment]
See the section on video formats in the manual entry on the video plugin: https://www.construct.net/make-games/manuals/construct-3/plugin-reference/video

This is why the video plugin allows setting separate sources for separate formats. If one format worked everywhere, we'd just use that.
