### ISSUE TITLE
[SDK] Error when using "SetItalic" function

### ISSUE THREAD

**Issue by rexrainbow** [Scirra/Construct-3-bugs#1168]
## Problem description

Error message raised when using `SetItalic` function:
```
Error report information
Type: unhandled exception
File: https://editor.construct.net/r76-2/main.js, line 74, col 19448
Message: Uncaught ReferenceError: ǃynK is not defined
Stack: ReferenceError: ǃynK is not defined at window.SDK.Gfx.IWebGLText.SetItalic (...)
Construct 3 version: r76.2
URL: https://editor.construct.net/
```

Other functions like 
- SetFontSize
- SetLineHeight
- SetBold
- SetColor
- SetHorizontalAlignment
- SetVerticalAlignment
- SetWordWrapMode

worked well.

## Attach a .c3p

No c3p file attached.

## Steps to reproduce

1.
2.
3.

## Observed result

Error message raised

## Expected result

No error message

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
