### ISSUE TITLE
main.js:155 Error installing addon:  Error: missing addon.json

### ISSUE THREAD

**Issue by kishlayaS** [Scirra/Construct-3-bugs#1169]
## Problem description

Error while installing addon {Error missing addon.json). 

## Attach a .c3p

[ArcadixPlugin.zip](https://github.com/Scirra/Construct-3-bugs/files/1621313/ArcadixPlugin.zip)

## Steps to reproduce

1. Change file type from zip to .c3addon
2. Upload the .c3addon file in construct 3 using addon manager.
3. See the console for error.

## Observed result
We tried to follow each step written in sdk [manual ](https://www.construct.net/in/make-games/manuals/addon-sdk). we also tried to upload addon samples provide in the manual; still same error is coming.

## Expected result

The plugin should come in "Insert New Object" popup.
![image](https://user-images.githubusercontent.com/23715042/34809662-6dc8ace4-f6bc-11e7-9f93-7106af24d174.png)

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge:  Didn't checked.
* Safari: Didn't checked.

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

main.js:155 Error installing addon:  Error: missing addon.json
    at a.ǃspV (main.js:74)
    at <anonymous>
ǃvP.ǃs.ǃsyj.ǃspV.then.catch @ main.js:155
Promise rejected (async)
s.ǃvn.then @ main.js:155
Promise resolved (async)
ǃYS$ @ main.js:155
ǃYSv.onclick @ main.js:155

</details>

**Comment by AshleyScirra** [comment]
The error message is correct. addon.json is missing in the root, because everything was zipped in a sub-folder.
