### ISSUE TITLE
trying to save as without file name throw unhandled excpetion

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#117]
## Problem description

Go to menu =>Project =>  Save As => Click Save to local browser without putting a filename. and error is thrown.

## Attach a .c3p

No .c3p File needed, this is not a major issue but the exception should be handled gracefully instead of kicking you out, especially since your trying to save you work you might forget to put the filename 

## Steps to reproduce

1. Menu
2. Project
3.  Save As
4. Save to local browser
5. do not type in file name
6. save

## Observed result

exception is thrown but not handled

## Expected result

you get a valid error message, and it does not force you to restart the app, potentially losing the changes 

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: You must type a filename
Construct 3 version: r21
URL: https://editor.construct.net/index.html
Date: Fri Apr 21 2017 23:46:28 GMT-0400 (Eastern Daylight Time)
Uptime: 18.9 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Good catch this, was a combination of 2 bugs. Firstly a timing issue was causing the filename property to be cleared when opening a local browser save dialog. Secondly invalid character errors were not being dealt with when saving ( should have been bailing and displaying an error message ).

I've fixed both up, the patches should be in the next release.
