### ISSUE TITLE
Ordering of Effects is confusing in Dark Theme

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#1171]
## Problem description

The visual clarity of effects is confusing when using Dark Theme. 

You cannot see that's open, or what the parameters are, it needs indentation like the Light Theme.

## Attach a .c3p

[effect.zip](https://github.com/Scirra/Construct-3-bugs/files/1621388/effect.zip)

## Steps to reproduce

1. Use Dark Theme
2. Click on sprite with effect
3.

## Observed result

Is the effects tab open? Is Blend Mode the 2nd parameter of this Tint effect?

![image](https://user-images.githubusercontent.com/5744908/34810252-38238e9c-f6ee-11e7-8da0-89d75ec7bcb0.png)

## Expected result

With the light theme, "Tint" here looks like a child of the effects tab, it's not confusing. 

Should be the same style but with the dark colors.

![image](https://user-images.githubusercontent.com/5744908/34810278-6c7ab44a-f6ee-11e7-86af-e46b8648ffd3.png)

## Affected browsers

* Chrome: yes

**Comment by alastajj** [comment]
bump, still an issue when using effects

**Comment by Animmaniac** [comment]
Fixed for the next theme release.
