### ISSUE TITLE
Desktop app - can't reopen saved project

### ISSUE THREAD

**Issue by phillnexus** [Scirra/Construct-3-bugs#1172]
## Problem description

I spent 30 mins making some changes, saved it as a project, tried to open it again and the app crashes. No error code or message.

## Attach a .c3p

If I was to attach the one that no longer opens, I'd be attaching all of my game files (videos, sprites etc), can't do it sorry.

## Steps to reproduce

1. Open existing web based C3 file
2. Save as project
3. Try to open project after having made a heap of event changes

## Observed result

Crash

## Expected result

I expected my project to open in the state I had last left it

## Affected browsers

* Local x64 app

**Comment by AshleyScirra** [comment]
Sorry, nothing we can do from just this information. Please see the bug report guidelines, they're there so we can actually help you.
