### ISSUE TITLE
[ website ] Slight menu overflow on tutorials with long titles

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#1175]
## Problem description

Seems like the side menu on tutorials doesn't like long names! See image below.

## Steps to reproduce

1. Visit [le-guide-du-d-butant-construct-3](https://www.construct.net/gb/tutorials/le-guide-du-d-butant-construct-3-20)

## Observed result

![screenshot 2018-01-11 12 55 58](https://user-images.githubusercontent.com/9051865/34826667-608f3328-f6cf-11e7-93b2-c8e77946436f.png)

## Expected result

Content fits in side menu ( not that it's in English )
![screenshot 2018-01-11 13 04 07](https://user-images.githubusercontent.com/9051865/34826815-feb2cf88-f6cf-11e7-9ca9-0a3e83576bf6.png)

## Affected browsers

* Chrome: yes
* Firefox: unknown
* Edge: unknown
* Safari: unknown

## System details

<details><summary>View details</summary>

devicePixelRatio: 1

</details>

**Comment by phillscirra** [comment]
OK, fixed available when we deploy the next update.  Long menu items should now wrap around to the following line.
