### ISSUE TITLE
Cannot open project (.c3p) in R77 

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#1176]
When trying to load file in R77, i get the error message cannot open project, not a valid .c3p file. It works when i roll back to previous beta version. I also cleared the cache and restarted Chrome, to no avail.

![image](https://user-images.githubusercontent.com/30116964/34827451-7e68f5c2-f6da-11e7-903e-546661db6d2c.png)

## Attach a .c3p

The project is commercial so i can't provide a .c3p file publicly. I saved multiple versions of the project though over time and none of them opened. If you want, i'd be happy to provide it via E-Mail (it's only about 2 MB).

## Steps to reproduce

1. Launch Construct
2. Try to open project via cloud
3. Sometimes ask to install third party addons
4. Can't open project prompt

## Observed result

Project is not opened.

## Expected result

Project to open.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r76.2
Language setting: en-US

Local storage
Storage quota (approx): 131 gb
Storage usage (approx): 32 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Picoti** [comment]
Hello!
I have the same problem. I cannot open my local C3P project...

**Comment by AshleyScirra** [comment]
There's nothing we can do without a .c3p project demonstrating the problem.

**Comment by AshleyScirra** [comment]
Actually, looks like it affects the Glokar demo project in r77. It seems if the project uses global layers it can't open. Assigning to Diego.

**Comment by joelmayer87** [comment]
@AshleyScirra Oh that's right, i use quite a few global layers. Do you still want me to send the project?

**Comment by AshleyScirra** [comment]
Yep, should have a .2 release coming up shortly.

**Comment by DiegoScirra** [comment]
Yes, this one is fixed in r77.2
