### ISSUE TITLE
Desktop release: Layouts don't display with AJAX

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#1177]
## Problem description

Desktop release: Layouts don't display with AJAX object in project.

## Attach a .c3p

[desktop-layout-ajax.zip](https://github.com/Scirra/Construct-3-bugs/files/1623451/desktop-layout-ajax.zip)

## Steps to reproduce

1. Open the project file
2. Launch the preview
3. Layout don't display

## Observed result

Layout don't display until the AJAX object is deleted.

**Comment by AshleyScirra** [comment]
Should be fixed after r78 + followup desktop build update.
