### ISSUE TITLE
Desktop release: Preview window position and bar

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#1178]
## Problem description

In desktop version the preview window appears by default in the top-left corner of the screen and the title bar is outside the display.

When resizing the preview by right or bottom sides, the title bar is displayed again allowing to freely manipulate the window.

**Comment by LanciferStudios** [comment]
I'm having the same issue. 
The first time I preview the game, the popup window shows correctly in the center of the screen. But, every time after that, it gets stuck in the top-left corner of my screen. 

I was going to switch the preview to "dialogue", but it seems that option is no longer available.

**Comment by AshleyScirra** [comment]
Fixed this for r78, but we'll also need an update of the desktop build to fix it, so will do that shortly after r78.
