### ISSUE TITLE
Inconsistent brush size in image editor

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1179]
## Problem description

I have a sprite with a size of 100 x 100. When I use a brush with size 99 the brush is too small to completely fill out the sprite to the edges.
![brush](https://user-images.githubusercontent.com/31101309/34850437-17350228-f726-11e7-9f28-2fbda92639ba.PNG)

So I try to set the brush size to 100, it seems that it should fill the field perfectly now, but it´s too big.
![brush2](https://user-images.githubusercontent.com/31101309/34850456-377d9a22-f726-11e7-8ffb-772bdcd03208.PNG)

I don´t know if it only happens between 99 and 100.

## Attach a .c3p

🍦 

## Steps to reproduce

1. Sprite with size 100 x 100 px
2. Select brush size 99 - it´s too small
3. Select brush size 100 - it´s too big

## Observed result

The difference between brush size 99 and 100 seems to be too big. In addition I just realized that brush size 94-99 are literally the same size, brush size 93 is smaller again but with a big jump.

## Expected result

I expect brush size 100 to be roughly 100 pixel in width. But it seems that brush size 99 is 96 pixels in width where brush size 100 appears to be 102.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r77.2
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 152 mb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in r80.
