### ISSUE TITLE
 Desktop release: Project unsaved whithout changes

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#1183]
## Problem description

When opening a project with the desktop version, the project is considered as unsaved without changes being made.

**Comment by AshleyScirra** [comment]
I don't know what you mean. I can't see anything wrong.

**Comment by sebastien-c3** [comment]
Ok Ashley, sorry for my english. I retry to explain this minor issue. For example when I open a project (in my case on the cloud), the project opens but is considered as unsaved (the disk icon to save it is enabled) and when I close the project without changes the following message prompts: "The project 'xxx' has unsaved changes. What would you like to do?".

**Comment by sebastien-c3** [comment]
My original message has been updated.
It only happens by opening via "Menu > Project > Cloud open" or via "Open recent (cloud project)".

**Comment by AshleyScirra** [comment]
I still can't reproduce that. It does not happen when opening a project from Dropbox.

**Comment by sebastien-c3** [comment]
Very strange. It happens with all my Dropbox files.
