### ISSUE TITLE
[Desktop release] Does not recognize touch input.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1184]
## Problem description

Start the downloadable C3 version on a touch capable device. Touch seems to be completely disabled and not working as in chrome. Not even when previewing a project with touch input in mind.

## Attach a .c3p

Load template "Endless runner"

## Steps to reproduce

1. Open stanndalone C3
2. Try using touch in editor and in preview.

## Observed result

C3 is not recognizing touch input at all.

## Expected result

Should work same as in any other browser.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes

**Comment by shortercode** [comment]
Seems like it needs enabling in our build code, [touch-events-in-node-webkit-nw](https://stackoverflow.com/questions/33811587/touch-events-in-node-webkit-nw) just checking now

**Comment by AshleyScirra** [comment]
Do touch events work in exported NW.js projects? I thought Chromium had touch events enabled by default now.

**Comment by AshleyScirra** [comment]
Can't reproduce here, tried on a Win10 touchscreen laptop, and touch input works in the desktop build as well.

**Comment by tunepunk** [comment]
Tested on another device and it seemed to work there as well. Must have been fast ring insider preview build messing it up on that device? You can close for now. From now on I'm not doing any testing or reporting bugs on my device with insider previews.

**Comment by AshleyScirra** [comment]
Yeah, the insider previews can be flaky. Best double-check issues on public release builds.

**Comment by shortercode** [comment]
From what I read there's an edge case where chrome won't detect touch inputs in certain situations and so doesn't enable the touch event code, so I expect this is what's happening. A suggested workaround is to force enable touch events, but I'm unsure what side effects that has. There also seems to be a fair few unanswered stackoverflow questions about not getting any touch events on linux with both nwjs and electron.
