### ISSUE TITLE
iOS export to Xcode Admob not working

### ISSUE THREAD

**Issue by hansonbrody** [Scirra/Construct-3-bugs#1186]
Project won't build in Xcode citing "Umbrella Header 'Googlemobileads.h' not found" 
[https://drive.google.com/open?id=1kRcl9HiOjavsr-n9oSrymeuE7bJxjmk4](url)
## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open xcode project
2. Build
3.

## Observed Result

Above noted error

## Expected result

Proper build

## Affected browsers

N/A

## System details

Macbook

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Are you using the proj file or the workspace file?

**Comment by hansonbrody** [comment]
The proj file.

**Comment by hansonbrody** [comment]
Ok thanks, I’ll try that and update.

**Comment by hansonbrody** [comment]
That was it, thanks!

**Comment by shortercode** [comment]
@hansonbrody glad to hear :)
