### ISSUE TITLE
Perhaps the problem of the project when viewed in github

### ISSUE THREAD

**Issue by kop9000** [Scirra/Construct-3-bugs#1189]
when I for example open this file in github https://github.com/kop9000/GE-NE-RA-TOR/blob/master/eventSheets/car.json then the code is displayed in one line

**Comment by shortercode** [comment]
I'm not sure what your trying to get at here, and you haven't complied with with report guidelines. If you want to look at the file I recommend you paste the contents into a [beautifier](https://codebeautify.org/jsonviewer). However, you shouldn't need to edit the file in a text editor anyway and you would likely break your project.

**Comment by AshleyScirra** [comment]
I think the point is C3 saves all JSON files minified, which doesn't work well with source control. I think we'll save beautified by default.

**Comment by AshleyScirra** [comment]
Done this for r78.
