### ISSUE TITLE
Tilemap bar interface issues

### ISSUE THREAD

**Issue by oosyrag** [Scirra/Construct-3-bugs#119]
## Problem description

Cannot double click in margins to insert new object when a tilemap tool other than the pointer is selected.

## Observed result

Nothing happens

## Expected result

In Construct 2, double clicking on the layout (or in the margins) would bring up the insert new object dialogue regardless of any tilemap tool currently in use

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.81
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

Local storage
Storage quota (approx): 2.2 gb
Storage usage (approx): 132 mb (5.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
I am not too sure what is the correct thing to do here. C2 Seems to be a bit inconsistent in what it allows you to do and what it doesn't when editing a tilemap. C3, while more limiting, is predictable. If a tilemap editing tool is selected, you can't do any layout editing.

But in C2, for instance,  you can double click outside of the current tilemap instance, bring up the object type selection dialog and then place a new instance on top of the tilemap instance you were editing. If you had, let's say, the pencil tool selected in the Tilemap Bar, you now have a selected instance, which you can not edit further until you change to the pointer tool in the Tilemap Bar.

@AshleyScirra any thoughts about this?

**Comment by oosyrag** [comment]
Predictable is probably preferable. I didn't really mind much once I figured out why, but it was different than C2 so I posted in case it was unintentional.

Some context feedback might be useful in this case, such as:

When a tilemap tool is selected, highlight the tilemap object area to make it more prominent, maybe darken/grey out other areas.

Or maybe a context based mouse cursor that changes based on the situation (not sure if this is possible in a browser environment). Actually I personally would not like this approach - it is what GIMP uses. Their mouse cursor changes into a billion different contextual symbols that I have no idea what any mean anyway.

**Comment by AshleyScirra** [comment]
I think the existing way of preventing any other layout modifications while editing a tilemap is the right way to do it. Most likely C2 only lets you do other things by accident/oversight. However I think it would be handy to add a keyboard shortcut: pressing escape when editing a tilemap with a non-pointer tool should switch back to the pointer tool. This means while editing a tilemap you can easily revert to layout modifications at any time just by hitting Esc. @DiegoScirra, if you make that change I think you can close this issue.

**Comment by DiegoScirra** [comment]
Alright, that sounds sensible. Will do.

**Comment by DiegoScirra** [comment]
Turns out this was already implemented, sort of.

Pressing 1 activates the pointer tool. I Added the escape shortcut anyway because it makes sense to press escape to go back to the normal layout editing mode.
