### ISSUE TITLE
Desktop Beta r77.2  crashes when exporting a debug and/or release apk

### ISSUE THREAD

**Issue by LanciferStudios** [Scirra/Construct-3-bugs#1192]
## Problem description

C3 Desktop Beta crashes when exporting a debug and/or Unsigned release apk.

## Attach a .c3p

https://www.dropbox.com/s/gtd9w1hh6lb6elo/clicker.c3p?dl=0

## Steps to reproduce

1. Clicked Menu > Project > Export.
2. Selected Android (Cordova)
3. Selected Android Build as both a Debug APK and an Unsigned release APK. All other settings were left at default.

## Observed result

It crashes. Tried several times with the same result. 

## Expected result

Not to crash and spit out a working apk.

## Affected browsers

* Chrome: yes/**no**
* Firefox: yes/**no**
* Edge: yes/**no**
* Safari: yes/**no**

**Note** - This only happens in the standalone exe. Using the same build (r77.2) in the regular Chrome browser works normally.

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r77-2/main.js, line 2, col 287661
Message: Uncaught Error: unknown file content
Stack: Error: unknown file content at ǃ_.ǃkl.ǃdGk (https://editor.construct.net/r77-2/main.js:2:287667) at zip.ǃdqq (https://editor.construct.net/r77-2/main.js:2:287441) at https://editor.construct.net/r77-2/main.js:2:93218 at Worker.i (https://editor.construct.net/r77-2/main.js:2:93538)
Construct 3 version: r77.2
URL: https://editor.construct.net/
Date: Sun Jan 14 2018 16:25:45 GMT-0500 (Eastern Standard Time)
Uptime: 915.1 s

Platform information
Browser: NW.js
Browser version: 0.27.4
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1041666269302368
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@d8d23fd3b95d7b3c7744027f2ea1c954aec28955) NWjs/0.27.4 (like Chrome/63.0.3239.132)
C3 release: r77.2
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5450 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Okay I've sorted this out, I'm afraid it missed r78 but will be in r79
