### ISSUE TITLE
Check bundled addons more often.

### ISSUE THREAD

**Issue by Unentokku** [Scirra/Construct-3-bugs#1193]
## Problem description

Enabling bundle addons only checks if it can add the addons at the time you enable it and not whenever you start using a new addon.

## Attach a .c3p

just a c3addon that can't be bundled for some reason
https://mega.nz/#!Y98llZ5J!SuWxdDxPbREWgxJG2evtawefZZLAESqeUC1AuNhtXVo

## Steps to reproduce

1. Check bundle addons option in a project
2. Add a addon that can't be bundled
3. Recheck the bundle addons option

## Observed result

No warning about addon not being able to be bundled until you recheck the option

## Expected result

The warning should appear either when you add the object or save the project.

**Comment by mOOnpunk** [comment]
Perhaps a better solution, more control, would be if each 3 party addon being used is listed and gets its own checkbox?

**Comment by AshleyScirra** [comment]
In r80 added a prompt that reminds you if you add a new addon that cannot be bundled when "Bundle addons" is enabled.
