### ISSUE TITLE
Duplicating a layout with Global layers, cause confusion to which is overwritten

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#1194]
## Problem description

As of title, after duplicating a layout with Global layers, both the duplicated and the original Global layers 
are competing which to inherit. Unless I toggled one of the layer's Global setting, the other inherits.

## Steps to reproduce

1. Create Global layer.
2. Drop a Sprite object in that layer.
3. Duplicate the LAYOUT.

## Observed result

Duplicated layout's global layer isn't inheriting from the first layout's global layer. It also crashes.

## Expected result

No crash and the duplicated layer will say "overwritten".

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r77-2/main.js, line 63, col 261572
Message: Uncaught Error: can not set global property of overriden layer
Stack: Error: can not set global property of overriden layer at m.ǃdfT (https://editor.construct.net/r77-2/main.js:63:261578) at m.ǃ_ki (https://editor.construct.net/r77-2/main.js:63:270218) at m.ǃTm (https://editor.construct.net/r77-2/main.js:63:270396) at m.ǃmmw (https://editor.construct.net/r77-2/main.js:63:270417) at m.ǃmmu (https://editor.construct.net/r77-2/main.js:63:254920) at m.ǃdIL (https://editor.construct.net/r77-2/main.js:63:253424) at c.ǃId (https://editor.construct.net/r77-2/components/bars/projectBar/projectBar.js:1:27188)
Construct 3 version: r77.2
URL: https://editor.construct.net/index.html
Date: Mon Jan 15 2018 18:57:57 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 33 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r77.2
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r79.
