### ISSUE TITLE
error project github

### ISSUE THREAD

**Issue by kop9000** [Scirra/Construct-3-bugs#1196]
https://github.com/kop9000/GE-NE-RA-TOR/commit/85e50ee0076a36c9bbdc5709eef23b0d1b405219

the code in the project.uistate.json file is similar and remains one line

**Comment by AshleyScirra** [comment]
You're not supposed to commit .uistate.json files. They only contain things like the positions of dialogs for your system. If you commit them, they'll constantly create unnecessary diffs for irrelevant details.

**Comment by kop9000** [comment]
understandably. Thank you

**Comment by kop9000** [comment]
https://github.com/kop9000/GE-NE-RA-TOR/commit/b1583b2005cdf252cc5d5e97d415ebad0fe3efa4?diff=unified

still some files write code in one line. Perhaps they also should be like this

**Comment by AshleyScirra** [comment]
Those are still .uistate.json files.

**Comment by kop9000** [comment]
it would be nice to do them the same way, but if it's hard for you then I will not be offended
