### ISSUE TITLE
Crash on removing object from family(which has events). Can ruin project file.

### ISSUE THREAD

**Issue by NoSoul8** [Scirra/Construct-3-bugs#1197]
## Problem description

Crash on removing object from family(which has events). Can ruin project file.

## Attach a .c3p
[SHiEld_C3(broken).zip](https://github.com/Scirra/Construct-3-bugs/files/1633071/SHiEld_C3.broken.zip)
[SHiEld(120118).zip](https://github.com/Scirra/Construct-3-bugs/files/1633072/SHiEld.120118.zip)

## Steps to reproduce

_Scenario 1:_

1. Extract and run .c3p from SHiEld(120118).zip
2. Go to families > Enemy and edit it. Remove ThugBoss1 and ThugBoss2.
3. Run preview 

_Scenario 2:_

1. Extract and run .c3p from SHiEld(120118).zip
2. Go to families > Enemy and edit it. Remove ThugBoss1 and ThugBoss2.
3. Save project
4. Run preview 

## Observed result

_At scenario 1:_
The preview is running as expected, but the editor is crashed with the message specified in "details" section.

_At scenario 2:_
The preview is running as expected, but the editor is crashed with the message specified in "details" section, Also the project file becomes corrupted and displays "Failed to open project" on trying to open it.

## Expected result

I expect the editor neither to crash nor to ruin my project file.
>>**It would be a treat if you can recover my latest version project file attached as the SHiEld_C3(broken).zip**

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: cannot find instance variable export index
Stack: Error at Function.ǃl.ǃpSM (https://editor.construct.net/r78/main.js:2:206255) at t (https://editor.construct.net/r78/main.js:2:173886) at window.assert (https://editor.construct.net/r78/main.js:2:174289) at t.ǃlgc (https://editor.construct.net/r78/main.js:63:144123) at window.ǃhh.ǃVFq (https://editor.construct.net/r78/main.js:63:354102) at window.ǃhh.ǃlIJ (https://editor.construct.net/r78/main.js:63:348143) at o.map (https://editor.construct.net/r78/main.js:63:311679) at Array.map () at e.ǃlIJ (https://editor.construct.net/r78/main.js:63:311668) at t.map (https://editor.construct.net/r78/main.js:63:305211)
Construct 3 version: r78
URL: https://editor.construct.net/
Date: Tue Jan 16 2018 01:46:43 GMT+0400 (Грузинское время (зима))
Uptime: 43.2 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r78
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Attaching minimal repro: [family-vars-bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1635059/family-vars-bug.zip)
1. Remove Sprite from family
2. Notice event referencing variable is not removed
3. Crash on preview (and will save corrupt)

**Comment by AshleyScirra** [comment]
Thanks, good catch, this is a potentially serious bug. It should be fixed in r79. Let me see if I can recover the other project.

**Comment by AshleyScirra** [comment]
Had to delete a bunch of events but this project looks like it opens again: [SHiEld-recovered.zip](https://github.com/Scirra/Construct-3-bugs/files/1635141/SHiEld-recovered.zip)

Don't use the "Remove from family" feature until r79 otherwise you might run in to it again.

**Comment by NoSoul8** [comment]
@AshleyScirra , I'm glad that this bug report will save someone's time in the future :)
Thanks a lot for recovering my project file. I've downloaded it and it works fine.
Could you please remove the download link from your comment above, since it's no longer needed?

**Comment by AshleyScirra** [comment]
I've removed the link.
