### ISSUE TITLE
Can't close Preview window in Debug mode

### ISSUE THREAD

**Issue by dru1000** [Scirra/Construct-3-bugs#1198]
## Problem description

On the Desktop build only I can't close the preview window when I run in debug mode. Normal preview works fine. I've tried clicking the X in the top right and right clicking the window in the task bar.

## Attach a .c3p

Just run debug preview from blank project

## Steps to reproduce

1. run debug preview from blank project
2. try to close preview window using the X in top right

## Observed result

Nothing happens

## Expected result
Preview window should close

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, fixed for r79.
