### ISSUE TITLE
[R16] Pressing the "C" key can cause crashes.

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#12]
## Problem description
Related to this already reported bug in the forums : https://www.scirra.com/forum/crash-when-pressing-c-on-layout_t190225 which is to be fixed in R17, still reporting in case all presses aren't handled yet.
Looks like it is the same issue/details informations though, so likely possible to close this bug as fixed in R17.

I encountered the same type of crash when creating a layout and renaming it. 
I try to name the layout "PostRace" and when I pressed C, crash.

## Attach a .c3p
Can be reproduced in blank project

## Steps to reproduce

1. In a new project, create a new layout.
2. Rename the newly added layout, press the "C" key (not capital) (for example try to type the name "PostRace"

## Observed result
On pressing the C key, a crash happens.

## Expected result
No crash, be able to rename the layout and have it be applied without further issue.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r16/components/editors/layoutView/layoutView.js, line 1, col 48638
Message: Uncaught Error: no selection
Stack: Error: no selection at E.ǃdt (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:48644) at window.ǃUN.ǃej (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:25296) at window.ǃUN.ǃHU (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:16300) at Array.ǃqD.ǃp.ǃqx.ǃp.ǃqH.ǃqR.j (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:3698) at ǃp.Event.ǃWXR.ǃWXG (https://editor.construct.net/r16/main.js:2:283188) at ǃp.ǃd.ǃ$n.ǃW_j.dispatchEvent (https://editor.construct.net/r16/main.js:2:281769) at ǃp.ǃd.ǃ$n.ǃW_j.ǃHU (https://editor.construct.net/r16/main.js:2:324114) at re.ǃHU (https://editor.construct.net/r16/main.js:2:327269) at HTMLDocument.document.addEventListener.Le (https://editor.construct.net/r16/main.js:2:325577)
Construct 3 version: r16
URL: https://editor.construct.net/index.html
Date: Thu Apr 06 2017 19:39:59 GMT+0200 (Paris, Madrid (heure d’été))
Uptime: 177.6 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 560 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
This should be fixed in r17, but I'm going to leave this open for the time being since it's likely other people will run in to it.

**Comment by arturosanz** [comment]
@jaydonteh is right. "c" shortcut crashes if there are no objects selected or there are no objects in the layout. Changing the layout name is irrelevant. Just press "c" in a newly created layout page with no objects and it will crash.
