### ISSUE TITLE
C3 crashing when double-clicking an Image Point or trying to rename it

### ISSUE THREAD

**Issue by renegoldschmid** [Scirra/Construct-3-bugs#1202]
## Problem description

I can't edit/rename ImagePoints without C3 crashing during the process!

## Attach a .c3p

[TopDownShooter - Prototyp.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1634781/TopDownShooter.-.Prototyp.c3p.zip)

## Steps to reproduce

1. DoubleClick a Sprite
2. Go to Image Points
3. Create a new one
4. Right click it
5. Try to rename (or double click it)
6. Crash

## Observed result

C3 is telling me that it crashed and I need to reload.

## Expected result

A rename-dialogue or something like that.

## Affected browsers

* Chrome: yes
* Firefox: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r78/main.js, line 2, col 179707
Message: Uncaught TypeError: Right-hand side of 'instanceof' is not an object
Stack: TypeError: Right-hand side of 'instanceof' is not an object at Function.ǃl.ǃtc (https://editor.construct.net/r78/main.js:2:179707) at e.ǃVtC.ǃVtn (https://editor.construct.net/r78/main.js:74:140345) at Array.ǃLp.addEventListener (https://editor.construct.net/r78/main.js:74:136400) at ǃl.Event.ǃpAb.ǃpTl (https://editor.construct.net/r78/main.js:2:271667) at ǃl.ǃZ.ǃJ.ǃLl.dispatchEvent (https://editor.construct.net/r78/main.js:2:269956) at ǃl.ǃZ.ǃJ.ǃLl.ǃlnt (https://editor.construct.net/r78/main.js:52:5449) at ǃl.ǃZ.ǃJ.ǃLl.ǃND.ǃBp (https://editor.construct.net/r78/main.js:52:10145) at HTMLElement.ǃoG (https://editor.construct.net/r78/main.js:52:7254) at HTMLDocument. (https://editor.construct.net/r78/main.js:2:266727)
Construct 3 version: r78
URL: https://editor.construct.net/
Date: Tue Jan 16 2018 11:32:32 GMT+0100 (CET)
Uptime: 260.2 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r78
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 555 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by armandoalonso** [comment]
Also trying to delete an image point also causes a crash, might be related

**Comment by DiegoScirra** [comment]
Fixed in r79
