### ISSUE TITLE
Bullet behavior: when bullet is stopped the angle of motion gets set to closest between -180,-90,0,90,180 

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1203]
## Problem description

I've encountered a problem with the bullet behavior when the bullet stops (speed = 0). The angle of motion of the bullet is set to whatever angle is closest between -180, -90, 0, 90, 180.

This is an issue that can be bypassed by setting bullet speed instead of 0 to 0.00000000000001 but it's not too elegant and slowly i'm guessing the sprite will move especially if acceleration is used.

I've noticed this problem for a very long time (several months at least) and encountered it again, figured i'd make a bug report for it.

I've even tried setting the bullet angle of motion = sprite after i set speed = 0 but it didn't fix anything.

## Attach a .c3p

[Bullet Problem.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1635762/Bullet.Problem.c3p.zip)

![bulletgif](https://user-images.githubusercontent.com/7268697/34997027-001b2c54-fae4-11e7-8114-e15e61fde74c.gif)

## Steps to reproduce

1. open project
2. press spacebar

## Observed result

Notice the bullet angle is not the same as the sprite when it's not moving

## Expected result

I expect the bullet angle of motion to be correct set to the sprite's.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r78
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 2.1 gb (30.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I haven't checked especially but I expect the bullet behaviour is storing it's movement as a 2D velocity vector, so it's speed is also it's direction. Modifying it's angle and speed would just update it's velocity. Having a speed of 0 would set the velocity to { x: 0, y: 0 } so it looses it's directional part.

**Comment by JeFawk** [comment]
I see, thanks for the explanation.

**Comment by AshleyScirra** [comment]
Yeah, this is just a maths thing. If it's not moving, it has no angle of motion (i.e. what's the angle of a zero vector?). Usually this just means you need to set the speed before the angle of motion, so the angle of motion correctly applies if it was starting from stopped.

**Comment by JeFawk** [comment]
Might want to update the doc or something if it won't be fixed/changed so that people can understand what's happening.

**Comment by AshleyScirra** [comment]
It's already there: https://www.construct.net/make-games/manuals/construct-3/behavior-reference/bullet

> **Set angle of motion**
> Set the angle the bullet is currently moving at, in degrees. Note: when the speed is 0, the angle of motion is always 0 and cannot be changed, since there is no motion. Therefore setting the angle of motion then the speed does not work if the object iss stopped. Instead, set the speed first and then the angle of motion.

**Comment by JeFawk** [comment]
Sorry, didn't read that :/ but hey now you can update it by saying Note: when the speed is 0, the angle of motion is always closest to -180,-90,0,90,180 :D
