### ISSUE TITLE
Shader for "Softlight " Effect crashes HTML exports and C3 in Edge and Internet Explorer. 

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-3-bugs#1207]
## Problem description

Effect Shader for "Softlight " Crashing in Edge and Internet Explorer. 
Although Internet Explorer doesn't support C3 games generated should run with no problem. The error caused because of the shader also interrupts exported HTML5 games in Edge, so the error is injected in both C3 and the exported projects. Chrome and Mozilla work fine with this effect.

## Attach a .c3p

I can't attach a .c3p because C3 crashes before anything can be done

## Steps to reproduce

1. Open construct 3
2. Select any layer inside the layout
3. Add effect "SoftLight" 

## Observed result
Construct crashes because shader couldn't compile. Debug trace shows the following:

SCRIPT5022: SCRIPT5022: SyntaxError
6uQTKQJz.html (6,1350)

6 SCRIPT5007: Object expected
www-widgetapi.js (95,31)

 [Construct 2] com.cranberrygame.phonegap.plugin.ad.admob plugin is required to show Admob ads with Cordova; other platforms are not supported
c2runtime.js (2,1623)

 SCRIPT5022: error compiling fragment shader: Shader compilation errors
(0, 0): No precision specified for type 'float'
(0, 0): Internal compiler error
c2runtime.js (1,37748)

 SCRIPT5007: Object expected

## Expected result

Effect should have been added correctly. 
Exported projects should run in Edge and Internet Explorer

## Affected browsers

Edge: yes
IE: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r78/main.js, line 63, col 255127
Message: Error compiling fragment shader: Shader compilation errors (0, 0): No precision specified for type 'float' (0, 0): Internal compiler error 
Stack: Error: Error compiling fragment shader: Shader compilation errors (0, 0): No precision specified for type 'float' (0, 0): Internal compiler error at ǃlGw (https://editor.construct.net/r78/main.js:63:2905) at ǃl.ǃPN.ǃlG_ (https://editor.construct.net/r78/main.js:63:3821) at ǃl.ǃF (https://editor.construct.net/r78/main.js:2:208519) at prototype.ǃlsf (https://editor.construct.net/r78/main.js:63:35477) at t.prototype.ǃVoP (https://editor.construct.net/r78/main.js:63:482513) at t.prototype.ǃpLu (https://editor.construct.net/r78/main.js:63:482696) at ǃl.ǃpLk (https://editor.construct.net/r78/components/editors/layoutView/layoutView.js:1:42226) at d.prototype.ǃjZ (https://editor.construct.net/r78/main.js:63:271239) at d.prototype.ǃjZ (https://editor.construct.net/r78/main.js:63:255127) at prototype.ǃpis (https://editor.construct.net/r78/components/editors/layoutView/layoutView.js:1:7224)
Construct 3 version: r78
URL: https://editor.construct.net/
Date: Tue Jan 16 2018 18:35:28 GMT-0600 (Hora estándar central (México))
Uptime: 29.9 s 
Platform information
Browser: Edge
Browser version: 16.16299
Browser engine: Edge
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
C3 release: r78
Language setting: en-US 
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Microsoft
Renderer: Intel(R) HD Graphics 630
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 20
Extensions: WEBGL_compressed_texture_s3tc, OES_texture_float, OES_texture_float_linear, EXT_texture_filter_anisotropic, OES_standard_derivatives, ANGLE_instanced_arrays, OES_element_index_uint, WEBGL_debug_renderer_info, WEBGL_depth_texture, EXT_frag_depth, OES_texture_half_float, OES_texture_half_float_linear
</details>

**Comment by AshleyScirra** [comment]
Looks like another case of this Edge bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14342519/

It's easy to work around though, so should be fixed in r79.
