### ISSUE TITLE
Editor crashes when remote preview used

### ISSUE THREAD

**Issue by loz666** [Scirra/Construct-3-bugs#1209]
Editor crashes when remote preview used

Simple project (just a text box with some text in it), works fine on preview. Test on remote preview and editor crashes on PC.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.Run project through remote preview
2.Scan QR code
3.Watch editor screen crash

## Observed result

*What do you see happen?*

Text box would show

*What did you expect to happen instead?*

Crashed editor on PC

## Affected browsers

Edge: yes
Chrome: no
Firefox: unknown
Safari: unknown

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r79/exporters/preview/exporter.js, line 1, col 19031
Message: Unable to get property 'bufferedAmount' of undefined or null reference
Stack: TypeError: Unable to get property 'bufferedAmount' of undefined or null reference at prototype.ǃnf (https://editor.construct.net/r79/exporters/preview/exporter.js:1:15734) at prototype.ǃHc (https://editor.construct.net/r79/exporters/preview/exporter.js:1:19012) at Anonymous function (https://editor.construct.net/r79/exporters/preview/exporter.js:1:17579)
Construct 3 version: r79
URL: https://editor.construct.net/
Date: Thu Jan 18 2018 10:37:52 GMT+0000 (GMT Standard Time)
Uptime: 1933.1 s

Platform information
Browser: Edge
Browser version: 16.16299
Browser engine: Edge
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
C3 release: r79
Language setting: en-US

WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Microsoft
Renderer: Intel(R) HD Graphics 4600
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 16
Extensions: WEBGL_compressed_texture_s3tc, OES_texture_float, OES_texture_float_linear, EXT_texture_filter_anisotropic, OES_standard_derivatives, ANGLE_instanced_arrays, OES_element_index_uint, WEBGL_debug_renderer_info, WEBGL_depth_texture, EXT_frag_depth, OES_texture_half_float, OES_texture_half_float_linear

</details>

**Comment by loz666** [comment]
[test.zip](https://github.com/Scirra/Construct-3-bugs/files/1642602/test.zip)

**Comment by shortercode** [comment]
Can confirm this, but it seems to only happen on Edge. Probably would have been a good idea to fill that part of the report in!

Assigning to @AshleyScirra as this is in his area.

**Comment by loz666** [comment]
Not really as it would require testing across a range anyway.

**Comment by AshleyScirra** [comment]
Unfortunately Edge does not support DataChannels, which Remote Preview needs. I've fixed this for the next build by simply showing an error message when choosing Remote Preview, instead of letting you use it when it won't work.
