### ISSUE TITLE
Layout effects affects viewport boundaries

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#121]
## Problem description

In C2 these effects applied to the layout does not interfere with the visuals of the viewport boundaries. Now in C3 it gets affected and cause visual problems to the user.

## Observed result

Viewport boundaries where affected by the layout effects.

## Expected result

Separate the effects out of the viewport boundaries.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
There's no .c3p and it's not clear what you're seeing, can you at least provide screenshots?

**Comment by jaydonteh** [comment]
The bug does not require any .c3p files.

## Steps to reproduce
1. Create a new project.
2. Add "Pixellate" effect to layout. Any other effects are also part of the bug.

**Comment by jaydonteh** [comment]
Update: Margin corner indicators on the layout are also affected by effects applied to the layout.

**Comment by AshleyScirra** [comment]
Thanks, I see what you mean now. Should be fixed for r23.
