### ISSUE TITLE
Plugin doesn't work after exporting project with minification enabled

### ISSUE THREAD

**Issue by kacperwd** [Scirra/Construct-3-bugs#1210]
## Problem description

Plugin functions don't work after exporting mobile project with minification enabled. The plugin is a wrapper for a Cordova extension.

## Attach a .c3p

[bug_demo.c3p
](https://drive.google.com/file/d/11DjltLsFwOiWAhudQgJVPCJjv2W7Z9QN/view?usp=sharing)

## Steps to reproduce

1. Open the provided project.
2. Export as Xcode project or APK file, select the 'Minify script' option.
3. Build the exported project if applicable and run the application.
4. Press the 'show interstitial ad' button.

## Observed result

Plugin calls won't work. If you press the button, a dummy ad won't be displayed.

## Expected result

Plugin calls should work, like in applications with minification disabled. After pressing the button, a dummy ad should be displayed.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r79
Language setting: en-US

Local storage
Storage quota (approx): 6.8 gb
Storage usage (approx): 257 mb (3.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 6000
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This project uses a third-party addon (Enhance). Scirra aren't responsible for maintaining it, please report issues with it to the addon developer.

**Comment by kacperwd** [comment]
We are the developers of this addon (Enhance) and the issue is clearly related to how Construct 3 manages script minification.

**Comment by AshleyScirra** [comment]
Oh, sorry, I thought you were a user not the developer. Script minification in both C2 and C3 works the same: dot-syntax properties are mangled, but string properties or not. So `obj.myCustomApi()` will mangle `myCustomApi()` on export (outputting something like `obj.XaE()`), but `obj["myCustomApi"]()` will be left intact. So normally you just need to switch to the string syntax for external names.

I just realised we don't have anything covering this in our addon SDK documentation, I'll add something about that.

**Comment by kacperwd** [comment]
Thanks for your response.

**Comment by AshleyScirra** [comment]
I've added this page to the addon SDK documentation to explain it in more detail: https://www.construct.net/make-games/manuals/addon-sdk/guide/script-minification

Hopefully it's straightforward to update the code.
