### ISSUE TITLE
Debug Watch will only hold one array at a time.

### ISSUE THREAD

**Issue by bible9230** [Scirra/Construct-3-bugs#1213]
Watch will only hold one array at a time. The second array selected will keep the first array's name and replace the data, but two arrays will not display separately at one time.

Also the array cannot be deleted from being watched.

https://www.dropbox.com/s/6t6ge3geqblsd9t/WatchArrayTest.c3p?dl=0

## Steps to reproduce

1.  Watch "NumberArray" array data
2.  Watch "WordArray" array data
3.  Only one array data will display in Watch
4.  The array data shown will have "NumberArray" name but "WordArray" data
5.  Also, the array data cannot be deleted from watch

## Observed result

The two arrays are jumbled into a single array.

**Comment by AshleyScirra** [comment]
I assume when you say 'Watch "NumberArray"', you're watching the "Array data" section? You can only watch debugger sections, not entire objects.

**Comment by bible9230** [comment]
Yes

**Comment by AshleyScirra** [comment]
OK, well I looked in to this and really it comes down to an architectural shortcoming in the debugger :-\ unfortunately everything is keyed off the header text at the moment, which makes it difficult to add support for two separate groups with the same name. Fixing this would mean ripping up a lot of debugger code and rewriting it. So I'm afraid this might not be something that is resolved soon.

**Comment by AshleyScirra** [comment]
I'm currently working on the new C3 runtime debugger. I think this is now fixed with that, but the original link doesn't work any more. Can you re-upload the test file so I can verify it works with your project?
