### ISSUE TITLE
Moving inside image editor is not working - Desktop. 

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1217]
## Problem description

In the desktop version, you can't move in the image editor with mouse wheel or space + mouse. The moving symbol is appearing but it won't work.

## Steps to reproduce

1. Open the image editor, zoom in and try to move around.

## Observed result

Nothing.

## Expected result

Move.

## Affected browsers

Desktop.

**Comment by DiegoScirra** [comment]
Fixed in r81. This was affecting the browser build aswell.
