### ISSUE TITLE
Can't open a .c3p file directly with C3 - Desktop.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1218]
## Problem description

I changed .c3p default software to C3 Desktop. When I try to run the .c3p file it opens the C3 but won't open the game.

## Steps to reproduce

1. Change the .c3p file "Opens with:" to C3
2. Try to run it.

## Observed result

Starts C3 without opening the game.

## Expected result

Should open the game in C3 like in C2.

**Comment by AshleyScirra** [comment]
Added this for the next build.
