### ISSUE TITLE
Key Press or Global boolean not working in Debug Preview.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#122]
## Problem description

I have a small project here for testing purposes. Whenever I use the Debug Preview They key press is not registered, and the switching doesn't work. I don't know if this is either, keyboard, global boolean not switching correctly. This works perfectly fine in normal preview.

## Attach a .c3p

https://www.dropbox.com/s/yhikh6nqdsy10yk/array_overhead.c3p?dl=0

## Steps to reproduce

1. Open attached project.
2. Run a normal preview and press space to switch. Works perfectly.
3. Run a debug preview and switching with space key does not work.

## Observed result

Switching does with keypress does not work in Debug preview.

## Expected result

Should be working as in normal preview.

## Affected browsers

* Chrome: yes

**Comment by tunepunk** [comment]
It seems to be the key press not being registered in Debug preview.

**Comment by AshleyScirra** [comment]
It works if you click inside the game. It's just that the game isn't initially focused. I've fixed it in r23 so the game starts focused and keyboard input works without having to click in it first.
