### ISSUE TITLE
Saving takes time in Desktop Version.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1220]
## Problem description

In C3 when you save, a popup appears and shows saving progress. This also locks the editor and take some time to finish. I encountered this issue with a quite small project (2.2 MB <200 events) and it takes ~2 seconds to save. The same project or bigger ones won't take any time to save in C2. I assume it will take much longer time to save bigger projects in C3. I use CTRL + S very often and it's annoying to wait.

**Comment by bilgekaan** [comment]
I just tried it with Kiwi Story.

## Steps to reproduce

1. Download Kiwi Story,
2. Save it to the desktop.
3. Change the title position in the menu layout.
4. Save it. It should take ~2 seconds to save.

**Comment by phillnexus** [comment]
"I assume it will take much longer time to save bigger projects in C3"

FYI I have a ~350mb file and hundreds of events, it takes less than a second to save

**Comment by AshleyScirra** [comment]
I can't reproduce here. Following the steps to reproduce based on kiwi story, it saves so quickly after a change that the save progress bar barely even fades in.

According to @phillnexus this doesn't affect other users even with large projects, so this seems most likely to be a system-specific performance issue.
