### ISSUE TITLE
Project bugged

### ISSUE THREAD

**Issue by SaKrashDuFe** [Scirra/Construct-3-bugs#1221]
## Problem description

Every time I open a project and test it, nothing works. I can just move with arrows, but variables are not moving when I click, text is not displaying what it's supposed to display... I've cut everything in the project with just "if Click somewhere, Destroy Sprite" and even this is not working. I restarted the project from scratch, it's worked until I've reset my PC.

## Attach a .c3p

https://www.dropbox.com/s/woa9y9wt8uvwqfe/ID3.c3p?dl=0

## Steps to reproduce

1. Create project
2. Save, close C3
3. Open it

## Observed result

Nothing works

## Expected result

Something working?

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: yes
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
You don't have an event sheet assigned to your layout view. So the event sheet was never loaded. Once I set it to "Feuille dEvenements 1" the numbers rendered correctly and the mouse listener destroyed the sprite when clicked.

You can set the event sheet assigned to a layout view in the layout properties. Also you can import an event sheet into another using "include event sheet" within the event sheet.

If you select "add event sheet" when adding a layout then it will automatically be assigned to it.

I don't see any issues related to saving or loading projects here.
