### ISSUE TITLE
"Find Results" popup window behaves differently from "Expressions Dictionary" popup

### ISSUE THREAD

**Issue by bible9230** [Scirra/Construct-3-bugs#1222]
## Problem description

This is not a bug, but it is not consistent with other popup windows.

## Attach a .c3p

non-specific

## Steps to reproduce

1.  Go to any systems actions that give you access to the Expression Dictionary popup
2.  Resize and relocate the popup
3.  Notice that the popup closes when the system editor is closed.
4.  Reopen the Expression Dictionary again and it will remember the size and placement.
5.  Open "find" and search for something with a lot of occurrences.
6.  Resize and relocate the "Find Results" popup
7.  Notice that the popup does NOT close when the Find popup is closed.
8.  Reopen Find Results and you will see that the popup returns to its default size and position.

## Observed result

"Find Results" does not remember size and position and does not close when "Find" is closed.

## Expected result

I expect it to remember size and position and to close similarly to "Expression Dictionary".

## Affected browsers

* Chrome: yes

## System details

version r80

**Comment by AshleyScirra** [comment]
This is all working by design. I'm not sure why you think this is a problem?

FWIW the "Find results" window is not a popup dialog, it's actually a dockable bar, so you might see it working differently because of that.

**Comment by bible9230** [comment]
I didn't notice that it was a dockable bar.  Comparing it to the "Expression dictionary" was a bad comparison. 

The LAST POSITION and LAST SIZE is my main issue:
Upon using "Find" I would like to see "Find Results" snap to its last docked or undocked position and size.  

I like to have a maximum viewing area, if I were to permanently keep "find results" open and docked it uses too much of my screen.  Even scaled down in size.

Right now:
1. open "find results"
2. dock it
3. resize the bar
4. close it and reopen it
5. re-dock it
6. re-size it every time

Also, it would be great if the "Find" window search options were MERGED into the top of "Find Results" as a single line for a clean and simple appearance when it opened as one window.
