### ISSUE TITLE
Not translated text in the plugin window

### ISSUE THREAD

**Issue by kop9000** [Scirra/Construct-3-bugs#1224]
![bandicam 2018-01-23 01-00-28-318](https://user-images.githubusercontent.com/15349782/35246913-8147df8a-ffd9-11e7-97bf-55345226fc37.jpg)
![bandicam 2018-01-23 01-00-32-612](https://user-images.githubusercontent.com/15349782/35246914-816f365c-ffd9-11e7-80c2-0485ae6ef284.jpg)
![bandicam 2018-01-23 01-00-38-328](https://user-images.githubusercontent.com/15349782/35246915-81932a9e-ffd9-11e7-976b-369f6fa41724.jpg)

**Comment by AshleyScirra** [comment]
Fixed for r80. Note the "add dev addon" does not appear for most users, and if you're a developer, you need to know English anyway to understand the documentation... but they can be translated anyway. Strings will be on POEditor in a few minutes after this comment.
