### ISSUE TITLE
Edit collision polygon acts funny on Firefox

### ISSUE THREAD

**Issue by Belfryboi** [Scirra/Construct-3-bugs#1226]
## Problem description

When I drag any of the nodes the blue area moves to the top-left
![collisionpolygon](https://user-images.githubusercontent.com/34272209/35276267-2183a9ac-0043-11e8-982a-d3a11868d9c4.JPG)

## Attach a .c3p

Tried with KiwiStory

## Steps to reproduce

1. Double-click any sprite
2. Go to Edit collision polygon
3. Drag any of the nodes

## Observed result

Blue area moves to top-left

## Expected result

Stays relative to sprite

## Affected browsers

* Chrome: no
* Firefox: yes
* Edge: no

Only add-ons installed are adblock plus and some twitch ones (BetterTTV and FrankerFaceZ)

Only plugins I have are probably just the standard ones: 
-OpenH264 by Mozilla
-Widevine Content Decryptions Module by google
-Shockwave Flash (28.0 r0)

**Comment by DiegoScirra** [comment]
Fixed in r81.
