### ISSUE TITLE
Spritefont renders weird with negative spacing on the editor

### ISSUE THREAD

**Issue by MarcoWorms** [Scirra/Construct-3-bugs#1227]
## Problem description

When I use negative horizontal spacing for spritefonts, despite rendering well on preview and build i get this weird glitch on the editor where the transparent part of a char-tile overlaps the previous char. It only happens on editor so it's not a game breaker, but it annoying :P

<img width="761" alt="screen shot 2018-01-23 at 18 54 14" src="https://user-images.githubusercontent.com/7863230/35300198-ea973eb4-006e-11e8-8eb5-1e75c1def15c.png">

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines so we can actually fix the problem you report.
