### ISSUE TITLE
[ Website ] Login and Register buttons overflow menu bar at certain widths

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#1229]
## Problem description

On the construct.net homepage the "Login" and "Register" buttons will appear over the edge of the menu bar when between certain widths ( you will need to be logged out to view this ).

## Steps to reproduce

1. go to [construct.net](https://www.construct.net/gb)
2. resize your window to 1050px width
3. slowly increase the width to 1200px

## Observed result

Between 1100px and 1160px width the buttons move onto the next line of the layout, and appear outside of the menu.

<img width="1101" alt="screen shot 2018-01-24 at 11 55 22" src="https://user-images.githubusercontent.com/9051865/35331062-f7b05204-00fd-11e8-8f11-39bde5bbea8c.png">

## Expected result

<img width="1168" alt="screen shot 2018-01-24 at 11 59 17" src="https://user-images.githubusercontent.com/9051865/35331084-0b1a8328-00fe-11e8-81f9-7468b1959657.png">

## Affected browsers

* Chrome: yes
* Firefox: unknown
* Edge: unknown
* Safari: unknown

## System details

DevicePixelRatio: 2
MacBook Pro 2015
Chrome 63.0.3239.132 (Official Build) (64-bit)

**Comment by phillscirra** [comment]
Fixed as a byproduct of #1232 - Your Offers did not wrap correctly.
