### ISSUE TITLE
Construct 2 splash screen showing when exporting to web

### ISSUE THREAD

**Issue by simoneddeland** [Scirra/Construct-3-bugs#123]
## Problem description

When exporting a Construct 3 project to HTML/JS and uploading it to a web server a Construct 2 splash screen is shown even though the project is set to show a Construct 3 splash screen in the project properties.

## Attach a .c3p

[Platformer.zip](https://github.com/Scirra/Construct-3-bugs/files/960821/Platformer.zip)

## Steps to reproduce

1. Export the project to the web format.
2. Upload to a server.
3. Watch the splash screen.

## Observed result

A splash screen with the construct 2 logo.

## Expected result

A splash screen with the construct 3 logo.

## Affected browsers

* Chrome: yes
* Firefox: don't know
* Edge: don't know
* Safari: don't know

**Comment by AshleyScirra** [comment]
This is simply because we haven't got the C3 splash ready. Hopefully it'll be ready soon.

**Comment by AshleyScirra** [comment]
Updated to a C3 splash in r24.
