### ISSUE TITLE
Cant preview with r80 in firefox 

### ISSUE THREAD

**Issue by newman321** [Scirra/Construct-3-bugs#1230]
## Problem description
because of local storage error i turned to firefox(it shows different sandbox.js file) but
previewing shows this error : 
![screen shot 2018-01-24 at 3 44 33 pm](https://user-images.githubusercontent.com/426713/35331733-aaa3e7da-011d-11e8-9e94-b4d162daefce.png)
after clicking on ok this is what i see and its stuck.
![screen shot 2018-01-24 at 3 44 55 pm](https://user-images.githubusercontent.com/426713/35331924-64741d88-011e-11e8-98ea-1babfe237c8d.png)

## Attach a .c3p

cant reproduce with a minimal project 

## Steps to reproduce

1.open construct 3 
2.Hit Preview

## Observed result

*What do you see happen?*

![screen shot 2018-01-24 at 3 44 33 pm](https://user-images.githubusercontent.com/426713/35331845-10bb9464-011e-11e8-92b2-3c54f67dc5bc.png)
![screen shot 2018-01-24 at 3 44 27 pm](https://user-images.githubusercontent.com/426713/35331941-7ec12190-011e-11e8-959d-2cde71bfd795.png)

## Affected browsers

* Firefox: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 58.0
Browser engine: Gecko
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0
C3 release: r80
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 416 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    UI animations are disabled in Firefox due to bug 1354501
    CSS containment is not supported. Editor performance may be significantly degraded.
    The <dialog> element is not supported. A polyfill is in use.
    WebGL 2+ is not supported. Rendering quality and features may be affected.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 330M OpenGL Engine
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2047
Extensions:

    ANGLE_instanced_arrays
    EXT_blend_minmax
    EXT_color_buffer_half_float
    EXT_frag_depth
    EXT_sRGB
    EXT_shader_texture_lod
    EXT_texture_filter_anisotropic
    EXT_disjoint_timer_query
    OES_element_index_uint
    OES_standard_derivatives
    OES_texture_float
    OES_texture_float_linear
    OES_texture_half_float
    OES_texture_half_float_linear
    OES_vertex_array_object
    WEBGL_color_buffer_float
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_depth_texture
    WEBGL_draw_buffers
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce with Ghost Shooter. Please always follow the bug report guidelines otherwise we cannot help.

**Comment by newman321** [comment]
as i said i cant reproduce it with a minimal project, i can share original project in a private way

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. They explain how to create a minimal project from the original project.

**Comment by newman321** [comment]
tried to isolate the problem, when opening one of the images in construct 3 image editor in firefox i got an error about finding a faulty image and replacing it with default empty one afte opening that image and getting the error my problem solved but a more detailed error report may help users to find problem easier
