### ISSUE TITLE
[ Website ] Menu overflow on profile page

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#1232]
## Problem description

The sub-menu overflows onto the page between the width ranges 1100 and 1245

## Observed result

Take a look at the "Your offers" entry on the green / blue sub menu bar.

<img width="1191" alt="screen shot 2018-01-24 at 15 20 19" src="https://user-images.githubusercontent.com/9051865/35340175-566e9a28-011a-11e8-8799-d5f6115ccfb7.png">

## Expected result

<img width="1248" alt="screen shot 2018-01-24 at 15 20 32" src="https://user-images.githubusercontent.com/9051865/35340187-5b3d4720-011a-11e8-8c63-66f39d73676d.png">

## Affected browsers

* Chrome: yes
* Firefox: unknown
* Edge: unknown
* Safari: unknown

## System details

macbook pro 2015
devicepixelratio 2
Chrome 63.0.3239.132 (Official Build) (64-bit)

**Comment by phillscirra** [comment]
This problem occurs a little just before the options change automatically and get compiled underneath into a neater single menu icon (When the browser window is continually shrunk further).

This seemed like the easiest thing to do, tweaking the cyan menu to not wrap may have a knock on effect on other menu components that share the same styling settings.

Change won't be visible until we next update the software.
