### ISSUE TITLE
Pasted pixels in the animation editor and tilemap image editor vanish as soon as something else is clicked

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1234]
## Problem description

I'm using the Rectangle Select tool in the Animation Editor to copy and then paste pixels into a different frame. The copy/paste operation seems to work fine, but then no matter what I click on next, the pasted pixels vanish.

Update: nalcwap reported the same problem when trying to edit a tilemap image.

## Attach a .c3p

Can be done in a new project with a new sprite.

## Steps to reproduce

1. Create a sprite (or tilemap).
2. Draw some pixels.
3. Using the Rectangle Select tool, drag-select the pixels, hit ctrl-c to copy and ctrl-v to paste somewhere else in the frame (or in a new frame).
4. Click anywhere outside the selected pixels, or click on a different tool in the Animation Editor (or Tilemap Source Image Editor), like the draw tool.

## Observed result

The pasted pixels vanish.

## Expected result

I expect the pixels to be pasted when I choose a different tool or click outside the selected pixels.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r81
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 206 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by nalcwap** [comment]
one question is the tilemap work correct for you or same bug?i not mean the tiled background object that works but the tilemap  not appear the coçor or image when paint,sorry post there i not want post other  post if same bug but other object

**Comment by Scoremonger** [comment]
You are correct, the same issue happens in the Tilemap Source Image editor. I'll update the body of this bug so you shouldn't need to write a new one. Thanks!

**Comment by DiegoScirra** [comment]
Fixed in r82.

It looks like I broke this while trying to fix something else, sorry about that and thanks for reporting.
