### ISSUE TITLE
mobile version or android crash with error

### ISSUE THREAD

**Issue by nalcwap** [Scirra/Construct-3-bugs#1235]
## Problem description

the app crash with error in last version beta r81  when add a sprite object  the error is
  Error report information
Type: unhandled exception
File: https://editor.construct.net/r81/main.js, line 2, col 492149
Message: Uncaught TypeError: invalid icon
Stack: TypeError: invalid icon at i.ǃNQ (https://editor.construct.net/r81/main.js:2:492155) at window.ǃyf.ǃtL (https://editor.construct.net/r81/components/bars/zOrderBar/zOrderBar.js:1:16678) at Array.ǃts (https://editor.construct.net/r81/components/bars/zOrderBar/zOrderBar.js:1:1177) at ǃz.Event.ǃVuf.ǃVuv (https://editor.construct.net/r81/main.js:2:272038) at o.dispatchEvent (https://editor.construct.net/r81/main.js:2:270327) at o.ǃeVp (https://editor.construct.net/r81/main.js:63:222279) at o.ǃXF (https://editor.construct.net/r81/main.js:63:222159) at a.ǃe_.ǃVvh (https://editor.construct.net/r81/plugins/sprite/plugin.js:1:10376) at a.ǃe_.ǃon (https://editor.construct.net/r81/plugins/sprite/plugin.js:1:10567) at o.ǃon (https://editor.construct.net/r81/main.js:63:227954)
Construct 3 version: r81
URL: https://editor.construct.net/
Date: Thu Jan 25 2018 00:24:52 GMT+0000 (Hora padrão de GMT)
Uptime: 8.7 s

Platform information
Browser: Chrome
Browser version: 64.0.3282.119
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: mobile
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
C3 release: r81
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.try add a sprite object in android or pc mobile option the app crash with this example in chrome, i not test the error in android firefox because the bug in editor color behind the left part screen is there
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

   Error report information
Type: unhandled exception
File: https://editor.construct.net/r81/main.js, line 2, col 492149
Message: Uncaught TypeError: invalid icon
Stack: TypeError: invalid icon at i.ǃNQ (https://editor.construct.net/r81/main.js:2:492155) at window.ǃyf.ǃtL (https://editor.construct.net/r81/components/bars/zOrderBar/zOrderBar.js:1:16678) at Array.ǃts (https://editor.construct.net/r81/components/bars/zOrderBar/zOrderBar.js:1:1177) at ǃz.Event.ǃVuf.ǃVuv (https://editor.construct.net/r81/main.js:2:272038) at o.dispatchEvent (https://editor.construct.net/r81/main.js:2:270327) at o.ǃeVp (https://editor.construct.net/r81/main.js:63:222279) at o.ǃXF (https://editor.construct.net/r81/main.js:63:222159) at a.ǃe_.ǃVvh (https://editor.construct.net/r81/plugins/sprite/plugin.js:1:10376) at a.ǃe_.ǃon (https://editor.construct.net/r81/plugins/sprite/plugin.js:1:10567) at o.ǃon (https://editor.construct.net/r81/main.js:63:227954)
Construct 3 version: r81
URL: https://editor.construct.net/
Date: Thu Jan 25 2018 00:24:52 GMT+0000 (Hora padrão de GMT)
Uptime: 8.7 s

Platform information
Browser: Chrome
Browser version: 64.0.3282.119
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: mobile
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
C3 release: r81
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by DiegoScirra** [comment]
Fixed in r82.
