### ISSUE TITLE
Going to animation editor on new project causes crash

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#1237]
## Problem description

Going to animation editor causes crash

## Attach a .c3p
attached c3p 

https://drive.google.com/open?id=10ZwgLK2gKscPpG1qgFhIMDsT42ja9DFR

Attached gif of error
 
https://drive.google.com/open?id=1vBxwm54wHLfjXI-uKqAzTzan9n2QUt84

## Steps to reproduce

start new project,
create sprite
when it goes to animation editor it crashes

## Observed result

crash

## Expected result

animation editor

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r81/main.js, line 2, col 492149
Message: Uncaught TypeError: invalid icon
Stack: TypeError: invalid icon at i.ǃNQ (https://editor.construct.net/r81/main.js:2:492155) at window.ǃyf.ǃtL (https://editor.construct.net/r81/components/bars/zOrderBar/zOrderBar.js:1:16678) at Array.ǃts (https://editor.construct.net/r81/components/bars/zOrderBar/zOrderBar.js:1:1177) at ǃz.Event.ǃVuf.ǃVuv (https://editor.construct.net/r81/main.js:2:272038) at o.dispatchEvent (https://editor.construct.net/r81/main.js:2:270327) at o.ǃeVp (https://editor.construct.net/r81/main.js:63:222279) at o.ǃXF (https://editor.construct.net/r81/main.js:63:222159) at a.ǃe_.ǃVvh (https://editor.construct.net/r81/plugins/sprite/plugin.js:1:10376) at a.ǃe_.ǃon (https://editor.construct.net/r81/plugins/sprite/plugin.js:1:10567) at o.ǃon (https://editor.construct.net/r81/main.js:63:227954)
Construct 3 version: r81
URL: https://editor.construct.net/
Date: Wed Jan 24 2018 23:25:48 GMT-0500 (Eastern Standard Time)
Uptime: 63.9 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r81
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by armandoalonso** [comment]
clearing chrome cache fixed the issue, this can be closed

**Comment by DiegoScirra** [comment]
Fixed in r82
