### ISSUE TITLE
Tilemap object not show the paint image or color android chrome

### ISSUE THREAD

**Issue by nalcwap** [Scirra/Construct-3-bugs#1240]
Tilemap object not show the painf image or color here android cbrone,i not tested in pc

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.open the tilemoa object and paint something,
2.
3.

The imave or color i try paint show when pant but when i put tge tilemap object the image not show, in tge tiked background not appeae this error ,only appear in tikemap objects 

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes
* Firefox: not test
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by nalcwap** [comment]
the bug persistb in the last update i tryed in pc and  android chrome but the bug same,the images show in editor but when execute the object tilemap the image not appear can anyone verify this?thanks

**Comment by DiegoScirra** [comment]
@nalcwap

Was this fixed in r86?

**Comment by nalcwap** [comment]
@DiegoScirra no same problem, and the other bug i report for firefox in the editor have the other bug color, thanks

**Comment by nalcwap** [comment]
i fond something strange if i try ipen the tilemap sample  i can see the tilemsp and if i try edit wiith the editor the color show why shpw but if isd not this sample if i try create with the editor not show?thanks,i try pc and android same bug include in last beta

**Comment by nalcwap** [comment]
i found other thing the uid in the sample is 0 and in the created by me is 1 is this the problem?

**Comment by nalcwap** [comment]
sorry now works in last beta ,if anyone have this problem you can close this topic,thanks
