### ISSUE TITLE
crash in chrome android asus pad 2016 compile to html

### ISSUE THREAD

**Issue by nalcwap** [Scirra/Construct-3-bugs#1242]
## Problem description

when  i try compile in this tablet to html crash without any error but i not select any option minify or other when compile my question because not crash in other device is my tablet problem or a bug affecting asus 2016 tab tablet,can anyone with tablet asus verify this?in chrome,thanks

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.compile to html because free version not test other
2.
3.

## Observed result

*What do you see happen?*

compile without the crash

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes mobile
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Sorry, we can't help unless you follow the bug report guidelines.
