### ISSUE TITLE
Remote preview doesn't work on iPhones in ios safari using Chrome to remote preview

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#1245]
## Problem description

Remote preview doesn't work on iPhones and OSX, just says loading or it simply gets stuck

## Attach a .c3p
 
Any project

## Steps to reproduce

1. Remote preview
2. Open project via safari scan code via camera
3. C3 starts everything and then just loading forever

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no

## System details

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.13_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.600000023841858
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r81.2
Language setting: en-US

Local storage
Storage quota (approx): 6.9 gb
Storage usage (approx): 239 mb (3.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I tried Ghost Shooter and it loaded fine with Remote Preview. Are you sure it's not a connectivity issue on your end?

**Comment by damjancd** [comment]
Might be the project itself even though examples weren't running before. But now the same 92% loaded stuck problem is happening in OSX Safari while running preview and the editor from there. Will barebones my project as see where the problem arises from.

**Comment by damjancd** [comment]
OK Wen't through a lot of regressive deleting and pinpointed the problem to specifically audio and even more specifically webm format audio (mp4 works well). So safari doesn't tolerate it for some reason.

[Safari Audio Crash.zip](https://github.com/Scirra/Construct-3-bugs/files/1669631/Safari.Audio.Crash.zip)

I started using Safari to avoid all the crashes in OSX Chrome. IDK if the crashes are because of the Webm. I just want to start working. 

Gets stuck in 1% now unlike before when I had more files and it stuck at 92%

**Comment by damjancd** [comment]
OK Confirmed. I removed all webm's from the project, converted them in sketchy online audio conversion apps and reimported them back. Now preview works on iOS iPhone and on Safari.

**Comment by shortercode** [comment]
Ah yes... Apple broke WASM on iOS a couple of weeks ago and our opus audio
decoder uses it. It's pretty frustrating. We're hoping the next release
will fix it, but only time will tell and we could be waiting until March
for the patch to be issued from what I've heard.

**Comment by damjancd** [comment]
Damn it Apple get your shit together. Anyway the workaround works. M4A works fine when converted. Meanwhile maybe your converter could turn  all audio into M4As just so people don't come up to this problem suddenly. 

Thanks for the reply

**Comment by shortercode** [comment]
We can't encoder m4a files unfortunately. it's not a technical thing, the
format is patent encumbered so we would have to pay royalties. Also because
of this not all platforms support m4a.

There is a secondary decoder intended for older devices which should work
still, but due to the nature of the Safari bug it believes the main one
works.

**Comment by damjancd** [comment]
Ok so essentially we can just convert M4As on our own and it's going to work. Works for me at least :)
