### ISSUE TITLE
Storage full on export warning message but without implications

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1246]
## Problem description

Every now and then (10-25% of the time) whenever I export as HTML5 i get the following message:

![image](https://user-images.githubusercontent.com/7268697/35475156-0cf1efaa-03a2-11e8-9ed5-398213ea286e.png)

My storage is not full (why would it need that for an export anyway?)

![image](https://user-images.githubusercontent.com/7268697/35475162-1c4b007c-03a2-11e8-905f-5c02316ed7f9.png)

This does not hinder me at all, the export works and everything seems fine.

## Attach a .c3p

Happens even with empty projects. 

## Steps to reproduce

1. ??

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r81.2
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 2.1 gb (31.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Well I can tell you that whenever you export the result is stored in the editor ( Menu > View > Export Manager ). It will hold the last 10 exports I believe, I probably need to make this configurable. As to why this is causing a storage error when your obviously not low on space is strange... Do you get these messages at any other time?

**Comment by AshleyScirra** [comment]
That warning appears when there's *any* error writing to storage. It suggests that it *might* be because the quota is full, because that is by far the most common reason writing to storage may fail, but not the only one. It might be useful to look in the browser console when that error appears, there might be more information logged there.

**Comment by AshleyScirra** [comment]
FWIW I've noticed some unusual things about the storage error analytics since we updated to localforage 1.5.5, I filed this issue in case they have any thoughts: https://github.com/localForage/localForage/issues/788

That "unable to write to storage" error only appears when we get an error from localforage, so it might be hard for us to do anything about it.

**Comment by shortercode** [comment]
@JeFawk do you still experience these errors?

**Comment by JeFawk** [comment]
No @shortercode

**Comment by shortercode** [comment]
Thanks for getting back to me, I guess if it has stabilised then there's not much to worry about. If memory serves the code should work correctly ( but not be persistent ) even if it fails to save.

I'm going to change the warning message to a specific message for the export manager and close the issue I think.
