### ISSUE TITLE
Layout is not displayed in the editor in Safari (MacBook Pro mid-2009)

### ISSUE THREAD

**Issue by narFnarF** [Scirra/Construct-3-bugs#1247]
## Problem description

Opening any project in Safari, layout are not displayed in the editor. The layout editor section remains white. Note that the event sheet are correctly displayed. Running the game also works correctly
![capture d ecran 2018-01-27 a 14 49 58](https://user-images.githubusercontent.com/3538115/35475884-2afa76b2-0374-11e8-91df-3ad02cc8811e.png)

I'm having this issue on my MacBook Pro mid-2009 running MacOS "El Capitan" 10.11.6. 

## Attach a .c3p

You can use any project. You can the Glokar demo project.

## Steps to reproduce

1. Launch Construct 3
2. Open the Glokar demo project
3. Open any layout

## Observed result

The layout editor remains white and no game objects are displayed.

## Expected result

The layout editor is displayed, and we can see game objects.

## Affected browsers

* Chrome: Construct cannot launch on Chrome because WebGL is not available
* Firefox: ??? (Not tested)
* Edge: Edge is not available on mac
* Safari: Yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0.3
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6
C3 release: r81.2
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
Service Workers are not supported. Construct 3 cannot be used offline in this browser.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (2.1 NVIDIA-10.0.52 310.90.10.05b46)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce 9400M OpenGL Engine
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2047
Extensions:

EXT_blend_minmax
EXT_sRGB
EXT_frag_depth
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBGL_compressed_texture_s3tc
WEBGL_depth_texture
WEBGL_draw_buffers
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by narFnarF** [comment]
I should add that there's no OS updates available. Both Chrome and MacOS are running the latest available version.

To be honest, I would totally understand if the conclusion is that this MacBook Pro mid-2009 i'm using is simply too old to handle Construct. However, if that's the case, I would expect a warning saying that Construct 3 is not supported, similar to the warning I get when trying to launch Construct in Chrome on the same computer:

![capture d ecran 2018-01-27 a 15 11 40](https://user-images.githubusercontent.com/3538115/35475910-93e60984-0374-11e8-8ce4-573d6e06661a.png)

That kind of warning makes it very clear as to what to expect.

If you think that's it's simply a bug and it should work on this computer, I would be glad to help with debugging or providing crash logs or whatever you need.

**Comment by AshleyScirra** [comment]
This kind if issue is always due to poor quality graphics drivers, and is especially common on old devices like you say you have. Graphics driver bugs are pretty much infeasible to work around since we'd have to buy the specific device and configure it identically to your setup, and even then the issue can be essentially random.

We do display the "WebGL not supported" error if the browser says it doesn't support WebGL, but in this case the browser says it *does* support WebGL, but when we try to use it it's broken. This is tricky to detect, so I'm not sure we can even show a more useful error message.

Graphics driver bugs have been a major problem for us for years, it's definitely the weakest link in the modern technology stack.
