### ISSUE TITLE
Facebook plugin is using old fb sdk

### ISSUE THREAD

**Issue by pooyaGames** [Scirra/Construct-3-bugs#1249]
Facebook plugin loads 
https://connect.facebook.net/en_US/all.js but this is old sdk the newer one is here https://connect.facebook.net/en_US/sdk.js.

using old one causes not being able to use new features like Facebook analytics loading new sdk after the old one doesn't works either because right after first script loaded FB objects gets initialized , so this does not works : 

`<script src="https://connect.facebook.net/en_US/all.js"></script><script src="https://connect.facebook.net/en_US/sdk.js"></script>`

but this works

`<script src="https://connect.facebook.net/en_US/sdk.js"></script><script src="https://connect.facebook.net/en_US/all.js"></script>`

because of this in preview i can not use newer sdk with facebook plugin.

https://stackoverflow.com/questions/38462764/difference-between-facebook-all-js-and-sdk-js

**Comment by AshleyScirra** [comment]
Updated to v2.11 for r82.
