### ISSUE TITLE
Construct 3 restart automatically

### ISSUE THREAD

**Issue by iftikharlove555** [Scirra/Construct-3-bugs#125]
When I go to preview my project it's ok but when come back to construct 3 it's restart automatically  and I lose everything I made I'm using construct 3 in my mobile Google chrome and another problem is I can't open the game I made in construct 2 and it's very small not something bigger but can't modify or can't preview I'm using construct 3 in Samsung galaxy A3

**Comment by AshleyScirra** [comment]
Closing, please see the guidelines.

**Comment by shortercode** [comment]
[guidelines can be found here](https://github.com/Scirra/Construct-3-bugs)
