### ISSUE TITLE
Cannot open project due to "Invalid expressions"

### ISSUE THREAD

**Issue by DrEvilGenius** [Scirra/Construct-3-bugs#1250]
## Problem description
[GridPlatformer.zip](https://github.com/Scirra/Construct-3-bugs/files/1673289/GridPlatformer.zip)

Removed an Array that had some events linked to it, Array was removed but construct encountered a problem, so I clicked the restart button that was in the error popup. Now I cannot re-open that project, looks like it didnt fully blank out/remove events/conditions linked with the Array, like it usually does, but just replaced them with: <invalid expression>

## Attach a .c3p
Cannot recreate so posted the file im working on :/ Hope that helps

## Steps to reproduce
1.Remove an Array that is in use within some events/conditions
2. Hope it crashes/gets an error (I think its this stage where it doesn't properly remove the array and just replaces it with <invalid expressions>s)

## Observed result
Unable to open project, get an error popup (see below)

## Expected result
For my project to open and allow me to delete the <invalid expression> segments 

## Affected browsers
* Chrome: yes

##Popup when trying to open project
"In some circumstances, previous versions of Construct allow invalid expressions to be used. These expressions must be corrected the prior version before using the project in this version of Construct 3. A list of the invalid expressions is provided below.

Event sheet 1, event 8, action 1: Not an object: 'Array' is not an object name

Event sheet 1, event 9, action 1: Not an object: 'Array' is not an object name

Event sheet 1, event 10, action 1: Not an object: 'Array' is not an object name

Event sheet 1, event 11, action 1: Not an object: 'Array' is not an object name"

Image link if easier: https://gyazo.com/b03f9f80bc77d9b9ab4901bbd145cfa5

## System details
*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r81.2
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 178 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 720 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
There's not much we can do other than recover the file unless you provide steps to reproduce. The steps provided are vague and don't include a starting project so I can't follow them. Are you able to find a way to reproduce the issue?

**Comment by DrEvilGenius** [comment]
There was an error when I deleted the array, I tried to reproduce and couldn't. There's not much I can do if I don't get an error when I do (what I believe to be) the exact same steps that caused the issue in the first place.

I would appreciate anything you can do that will allow me to continue working on that project, because as of right now I have lost everything for an unknown reason that apparently you can't solve because I don't know enough about the error in the first place?

**Comment by AshleyScirra** [comment]
Here's the recovered project: [gridplatformer-recovered.zip](https://github.com/Scirra/Construct-3-bugs/files/1673803/gridplatformer-recovered.zip)

We need the requested information to be able to investigate the bug, so without that, closing the report as there's nothing else we can do. Please file a new issue with steps to reproduce if you can find a way to make it happen again.
