### ISSUE TITLE
C3 shades / colors not working correctly

### ISSUE THREAD

**Issue by uberdroidgames** [Scirra/Construct-3-bugs#1251]
## Problem description
Here's a white ball with smoothing on on construct 2:

https://drive.google.com/open?id=1nDYvq ... wEh3AWeYkT

See how smooth and fadey?

Here's the same thing in construct 3
(actually same project loaded into construct 3)

https://drive.google.com/open?id=1AW9Vb ... 4w_y9OihLF

It's more solid and dithered. Like I'm running in Windows 95 mode or something.

It's all rough around the edges:

https://drive.google.com/open?id=1u2ccD ... NJ8xuUhFbZ

*Enter a concise description of your problem here*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.   Make a sprite standard 255,255 size
2.   In the sprite editor pick pure white with 255 alpha and brush with full opacity and smoothing on size 250 or so
3.  make a brush stroke with a single click in the center so a faded out circle appears.

## Observed result

Instead of fading to transparent smoothly, the fade stops at what it says is an alpha level of 1, but it appears to be a much higher alpha level --creating a very visible and not smoothed edge between the brush stroke and the background. 

This edge is not there in C2 when we follow the same steps.  It just appears as a smooth transition you can't see exactly where the brush ends and the background begins.

*What do you see happen?*
see above
## Expected result
The effect in C2.  

This makes lighting using destination out on a dark non transparent layer above the playfield look bad.

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Those links are returning 404 not found.

**Comment by uberdroidgames** [comment]
c2 sprite editor
https://drive.google.com/open?id=1nDYvqWgLd4CLvJ3OabCyqAwEh3AWeYkT
c3 sprite editor
https://drive.google.com/open?id=1AW9VbR2pxq5iA9NjK29hzg4w_y9OihLF
edge on c3 sprite:
https://drive.google.com/open?id=1u2ccD0aE9Ns7cf1gfrGsWJNJ8xuUhFbZ

In c3 there is an abrupt edge between alpha=1 and alpha = 0 whereas in c2 it's a smooth transition; there's no edge.   alpha = 1 in c3 looks like alpha = around 32 in c2.

**Comment by uberdroidgames** [comment]
The difference between alpha 1 and alpha 0 for a pure white color should be nearly if not completely invisible.  In c3 and only the later versions this difference looks very pronounced.
