### ISSUE TITLE
Z Sort action vanishing from event sheet

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1253]
## Problem description

I have one action that keeps vanishing from the event sheet

I thought at first I was opening an old save file.
But then it happened again and again.

The event is a z sorting action.

I will change it and the change works in preview.
Then maybe after about the 5th preview , during preview , it disappears.
I can make 10 other changes after this that will remain but this single z sorting action  item will keep disappearing.

it also disappears if involved in any cut and paste action

it also causes a crash if dragged and dropped

This is the action 

![capture](https://user-images.githubusercontent.com/21962641/35538291-258d1f2c-0545-11e8-8ccf-4862ca8764d7.PNG)

there are no related console error messages when it happens

## Attach a .c3p

edit i have cut and paste the whole event+actions and objects into a new file and can repeatedly observe the issues described below in the new file which i think related to the vanishing

[Vanishing Action.zip](https://github.com/Scirra/Construct-3-bugs/files/1675607/Vanishing.Action.zip)

if you would like to see my project i can provide.  (its a bit of a mess tho!)
but I think the culprit is captured in the zip

## Steps to reproduce

I am trying to catch it happening on xbox vid cap  but the capture keeps stopping when i preview.  will try some other ways

**However, most likely related ,** 
1) in the attached file, cut the z-sorting action and try to paste the action back where it was you should hopefully see that it just disappears

2) Select the whole event+actions and copy and paste back into the editor you should see that both the original and the new pasted z sorting actions in each event vanish ! Magic !!!!

3) create a new every tick event under the sorting event Event then drag the z sorting action into the every tick event for a consistent and dependable crash (see crash message below in second comment) 

### (edit) Right I have totally narrowed it down I think

just make a family with 1 sprite and family instance variable myz

then make the event below

![image](https://user-images.githubusercontent.com/21962641/35588786-95c83628-05f9-11e8-90b7-88e8b2c5dda1.png)

then copy and paste etc you will see it disappears.
it does not happen if you z sort sprites
you can even delete the every tick event to have a blank event and the same happens

### so....the issue is caused by some conflict arising when making an event to system z sort a family

_
ps ive just seen that i meant to be using the is on screen instead of is visible but shouldn't matter.

## Observed result

z sorting action disappears after preview and cut and paste actions

## Expected result

not to

## Affected browsers

* Chrome: currently using

## System details

surface pro 4 i5 8gb win 10

**Comment by NetOneGames** [comment]
**Update**
I have found that if I cut the event and try to paste it back there it does not paste back.
Very strange indeed......

**Comment by NetOneGames** [comment]
**Another update**

Under the Event in the attached c3p , create an every tick event , then drag the z sorting action into the every tick event for a consistent and dependable crash with the following message 

Error report information
Type: assertion failure
Message: cannot select detached view
Stack: Error at Function.ǃa.ǃUXQ (https://editor.construct.net/r81-2/main.js:2:206204) at a (https://editor.construct.net/r81-2/main.js:2:173847) at window.assert (https://editor.construct.net/r81-2/main.js:2:174250) at window.ǃse.ǃiD (https://editor.construct.net/r81-2/components/editors/eventSheetView/eventSheetView.js:1:11698) at window.ǃse.ǃiK (https://editor.construct.net/r81-2/components/editors/eventSheetView/eventSheetView.js:1:11187) at window.ǃse.ǃCZ (https://editor.construct.net/r81-2/components/editors/eventSheetView/eventSheetView.js:1:26661) at window.ǃse.ǃBA (https://editor.construct.net/r81-2/components/editors/eventSheetView/eventSheetView.js:1:24527) at window.ǃse.ǃbh (https://editor.construct.net/r81-2/components/editors/eventSheetView/eventSheetView.js:1:20797) at HTMLDocument.ǃzP (https://editor.construct.net/r81-2/components/editors/eventSheetView/eventSheetView.js:1:1957) at HTMLDocument. (https://editor.construct.net/r81-2/main.js:2:267000)
Construct 3 version: r81.2
URL: https://editor.construct.net/
Date: Mon Jan 29 2018 23:41:09 GMT+0000 (GMT Standard Time)
Uptime: 16.6 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r81.2
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by NetOneGames** [comment]
Just FIY I totally deleted and rebuilt the event and actions but still observing the strange behaviors as above. (haven't been able to trigger a disappearance yet though with this even will get back if it does.)
also did some further experiments and it **seems to be directly related to the system z sorting action,** if I replace this action with anything else all appears well.

**Comment by NetOneGames** [comment]
edit narrowed it down to a conflict trying to system z sort a family.   (see above in main issue)

**Comment by NetOneGames** [comment]
So I will crack on with my project for now as I dont think it is corrupt rather there is a conflict in the event system.

Although my clouds are in front of my enemy ships at the moment making the impossible to spot !

**Comment by AshleyScirra** [comment]
Thanks, good catch with this one. It should be fixed in the next build. I don't think it will corrupt your project, it is simply incorrectly thinking that the referenced object or instance variable were deleted, so also deleting the action.

**Comment by NetOneGames** [comment]
awesome cheers
