### ISSUE TITLE
Translation: Poeditor pixels per second per second

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1254]
## Problem description

I was translating and ran into this. Is this correct?

![image](https://user-images.githubusercontent.com/7268697/35539671-3c922b16-055b-11e8-82f1-8f9f9bc53d72.png)

**Comment by NetOneGames** [comment]
yes 
acceleration or deceleration is feet/meter/miles/pixels  per second  per second.

**Comment by AshleyScirra** [comment]
As @NetOneGames points out, yes, it's a unit of acceleration.
