### ISSUE TITLE
Issue when loading project

### ISSUE THREAD

**Issue by Link64U** [Scirra/Construct-3-bugs#1255]
Each time I load a project, nothing works.

Everytime I save a project (doesn't matter if it's on Google Drive or on the computer, I tried everything), and load it later, none of the events seem to work, even if delete them and make them again. For example, none of the buttons on the menu will work once I load the project.

## Attach a .c3p

[Test GD.zip](https://github.com/Scirra/Construct-3-bugs/files/1679215/Test.GD.zip)

## Steps to reproduce

1. Make a new project with some kind of event, like a button that leads to another scene, for example.
2. Save it somewhere, then load it back up.
3. Go into preview mode and trigger the event you placed, like clicking on the button.

## Observed result

The button just doesn't work. Same thing with any kind of event, really.

## Expected result

Well, I expected the events to work!

## Affected browsers

* Chrome: yes.
* Firefox: unknown.
* Edge: unknown.
* Safari: yes.

**Comment by NetOneGames** [comment]
you didnt attach the event sheet to the scene

do this below and it will work

![image](https://user-images.githubusercontent.com/21962641/35594956-f80a3cd8-060c-11e8-8a08-f52fb68a1d3f.png)

**Comment by shortercode** [comment]
Thanks NetOneGames for replying to this, I think I've found a subtle bug here though which I think is causing it.

I had a look at the project file first, and the eventSheet for the layout is set to "Feuille d'Evènements 1" but there's no eventsheet by this name, so it sets it to `none`. You'll note the eventsheet is actually called "Feuille dEvènements 1" which is lacking the `'`. So tried editing it to use the full name, but the editor doesn't seem to let you use it and changes it to the other version. While I'm not sure whether we should be considered that character invalid the bigger question is how did you manage to set the eventsheet to an invalid value.

How are you creating the eventsheet?

**Comment by shortercode** [comment]
Okay so thanks to some fancy detective work from @DiegoScirra we have figured this out. The default event sheet name in french is `Feuille d'Evènements 1`, and it actually creates the event sheet with this name. However, when it is saved then opened it is renamed to `Feuille dEvènements 1` so it doesn't match the information in the layout.

**Comment by DiegoScirra** [comment]
This is fixed in r83
