### ISSUE TITLE
Google Drive save takes ages to load

### ISSUE THREAD

**Issue by trueicecold** [Scirra/Construct-3-bugs#1257]
## Problem description

Choosing to save to google drive takes ages to load. upon investigation, I see that you attempt to list all folders in my google drive account, which is A LOT! made about 400 requests to https://www.googleapis.com/drive/v3/files and still counting...

Also, I can't cancel calls for Google Drive to choose another cloud solution like Dropbox/OneDrive. I have to wait for it to finish first...

## Steps to reproduce

1. Try to cloud save on an account with LOTS of folders in it.

## Observed result

It's stuck in the cloud save loading dialog saying "Getting Files from Google Drive"

## Expected result

Should list only files under a dedicated Construct 3 folder, or list only root folders, and load nested folders only if needed.

## Affected browsers

All browsers.

**Comment by shortercode** [comment]
We request a list of all folders and any files with the "c3p" extension. So it's not quite all your files thankfully.

I'd like to have it list files under a Construct 3 folder, but it's too late to change it ( breaking behaviour for existing users ). Originally we had considered using Google Drives "application" mode, which gives each application access only to it's own folder. Unfortunately Google take a slightly strange decision to hide this folder away from the user entirely, so we didn't go for it.

The optimisation to load only the folder your currently in is on my to do list, but I considered it fairly low priority until now ( it's adds quite a bit of complexity and your the first to come forward with this issue ). Even so a fix probably won't make it into the next release. I can reduce the number of request by increasing the page size from 100 to 1000 which should speed it up a fair amount. Out of interest how long does it actually take to load, and is the UI usable?

**Comment by shortercode** [comment]
Okay so I've just committed a patch for r83 that reduces the required network requests.

It was originally requesting a page of 100 entries, which involved 2 requests as a  preflight request was automatically added by the browser.

With the revision it should request a page of 1000 entries, and I adjusted the request so that the preflight request isn't required any more.

So overall this should reduce your network requests by 20 times.  I'll still look into reducing the amount of content we request, but hopefully this will improve things for you until I can actually make the larger change. I'm not sure what the ETA is on r83 but it's probably going to be next week at the earliest.

**Comment by trueicecold** [comment]
Well, it took me about 10 minutes to load (LOTS of folders in there), but the UI was usable in a way I could just close the dialog and save it locally/to a file.

**Comment by shortercode** [comment]
I was just curious, I don't think it's ever been tested with quite that many entries.

**Comment by trueicecold** [comment]
so once it's up, I'll send you my impressions :)

Thanks!

**Comment by AshleyScirra** [comment]
r83 is out again, you can check again!

**Comment by AshleyScirra** [comment]
r83 is already out so not sure why this was tagged "check next release"? We're waiting for feedback from @trueicecold

**Comment by shortercode** [comment]
I marked it after r83, but I meant it for @trueicecold to confirm in r83. I haven't added anything else for r84 related to this.

**Comment by trueicecold** [comment]
Well, it does work considerably faster now although I did have to wait a while.
I can live with that :)

Thanks!

**Comment by shortercode** [comment]
That's good to hear! You should only have to load the filelist once per session, as it caches it in memory and only requests it again if you press the reload button in the dialog. Hopefully in future I will be able to get it to load just the folder your looking at but at the moment it causes issues with some edge cases like the autosave system.
