### ISSUE TITLE
C3 crashes if you right click on the layer name in the Z-index panel

### ISSUE THREAD

**Issue by DudetteonTheEdge** [Scirra/Construct-3-bugs#1259]
C3 crashes if you right click on the layer name in the Z-index panel
This happens with any file

## Steps to reproduce

1. z-index panel is selected
2. right click on a layer name

result: this crashes C3

*What do you see happen?*

## Expected result NA

*What did you expect to happen instead?* No crash

## Affected browsers 

* Chrome: yes
* Firefox: yes
* Edge: yes/no  did not try
* Safari: yes/no did not try

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information

Type: unhandled exception
File: https://editor.construct.net/r83/compon ... rderBar.js, line 1, col 12915
Message: ReferenceError: event is not defined
Stack: window.ǃCN.prototype.ǃgH@https://editor.construct.net/r83/components/bars/zOrderBar/zOrderBar.js:1:12915 window.ǃCN Construct 3 version: r83
URL: https://editor.construct.net/
Date: Fri Feb 02 2018 10:46:30 GMT-0600 (Central Standard Time)
Uptime: 6876.6 s
Platform information

Browser: Firefox
Browser version: 58.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
C3 release: r83
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro 410 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, EXT_disjoint_timer_query, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context 

</details>

**Comment by DiegoScirra** [comment]
Fixed in r86
