### ISSUE TITLE
Copying a comparison condition with a local variable can cause a crash

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#126]
## Problem description

Pasting a condition with reference to a local variable into a different event scope will cause crash and project corruption.

## Attach a .c3p

https://www.dropbox.com/s/qyla9jdkmmtg0ht/EventCrasher.c3p?dl=0

## Steps to reproduce

1. Copy the sub event on line 2
2. Paste onto line 4

## Alternative reproduction

1. Copy the condition on line 2
2. Paste onto line 4

*this produces a different error*

## Observed result

Editor crashes, saved project is corrupt.

## Expected result

Maybe a warning dialog?

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: untested

## System details

<details><summary>Reproduction A</summary>

Error report information
Type: unhandled exception
File: http://localhost:60000/lib/misc/jsutil.js, line 297, col 4
Message: Uncaught [object Object]
Stack: undefined
Construct 3 version: r21
URL: http://localhost:60000/?mode=dev&debug&project=test
Date: Thu Apr 27 2017 15:22:11 GMT+0100 (GMT Summer Time)
Uptime: 47.8 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_get_buffer_sub_data_async, WEBGL_lose_context

</details>

<details><summary>Reproduction B</summary>

Error report information
Type: unhandled rejection
Reason: Unknown expression 'Variable': This is not a system expression or variable name in this scope.
Construct 3 version: r21
URL: http://localhost:60000/?mode=dev&debug&project=test
Date: Thu Apr 27 2017 15:17:56 GMT+0100 (GMT Summer Time)
Uptime: 19.4 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_get_buffer_sub_data_async, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Good catch, fixed for r23.
