### ISSUE TITLE
Input box is offset from the element you want to rename

### ISSUE THREAD

**Issue by DudetteonTheEdge** [Scirra/Construct-3-bugs#1260]
## Steps to reproduce

1. Right click to rename a layer, a layout, or an object
2. The input box appears offset to the X left and any Y 
3. The box where it should be in the project panel shows only a dot

## Observed result

*What do you see happen?*

## Affected browsers

* Chrome: yes/
* Firefox: yes/
* Edge: did not try
* Safari: did not try

## System details
WINDOW 10 latest version
No crash report.

**Comment by AshleyScirra** [comment]
Can't reproduce, looks fine to me: ![rename-box](https://user-images.githubusercontent.com/768723/35811810-52b6c632-0a87-11e8-90d6-f9d48dcc1b3d.png)

Please follow the bug report guidelines in as much detail as possible to ensure we can fix the problem you report.

**Comment by DudetteonTheEdge** [comment]
How can you close a thread when you have given only one feedback and did not even wait for an answer???
I am this problem with several computers I use at different locations (home and work). So this is a problem t hat needs to be solved. when the object panel is on the right of the screen the box still appear on the left of the screen. I this image the panel is on the left next to the property panel and you can see the box at a random place on the left.
Note: I am using 2 monitors on each PC.
![construct 3](https://user-images.githubusercontent.com/6223991/35812269-14bf1aea-0a56-11e8-8251-0481d566c680.png)

**Comment by AshleyScirra** [comment]
If I cannot reproduce the issue, it is impossible to do anything about it. We routinely receive bugs which are impossible to do anything about and so we just close them. Please see the bug report guidelines. Posting screenshots doesn't help, we need a way to reproduce the issue.

**Comment by DudetteonTheEdge** [comment]
I'd be willing to screenshare on Google Hangouts if you can do it.

**Comment by AshleyScirra** [comment]
I believe you. I am sure I would see it happen. The problem is I need to see it on my own computer to be able to fix it.

**Comment by DudetteonTheEdge** [comment]
OK. No problem. Since I do not have an error log for it, I understand it is hard to trace.

I have only 2 errors in the console if that helps:
error 1:
Error loading texture: 
DOMException {  }
Error 2:
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://preview.construct.net’) does not match the recipient window’s origin (‘https://editor.construct.net’).

**Comment by DudetteonTheEdge** [comment]
Maybe you need to try with a machine with 2 monitors. This actually happened to Adobe Edge Animate when in preview and they corrected it. If you have only one monitor then maybe you will not see the error.

**Comment by AshleyScirra** [comment]
I have a dual-monitor system. It doesn't reproduce on either monitor.
