### ISSUE TITLE
Button object can't set cursor CSS

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1264]
## Problem description

I was following https://codepen.io/geoffgraham/pen/QNgoQW to change the cursor's image when over a form element via CSS. The "cursor" CSS element is not recognized by the button and never added to its CSS. 

The cursor image change works if I modify the CSS manually. In my case I added the code right under the gray CSS which I've added via code and it worked.

## Attach a .c3p

[Mouse Sprite Over Form Element.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1695593/Mouse.Sprite.Over.Form.Element.c3p.zip)

## Steps to reproduce

1. open project
2. preview
3. use dev tools to see how the color css worked but not the cursor

## Observed result

*What do you see happen?*

## Expected result

I expected the cursor css to work as well, actually I expect what I write in css to be added in the CSS sheet without any prior verification made by the game engine OR create a new action "Add code to CSS" to do this directly so we can write whatever we want to have in the CSS.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r83
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 2.1 gb (31.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It ignores it because the syntax is invalid. There is no need for a semicolon at the end, you only need that in CSS files to denote the end of a statement.

In general bugs in 'set CSS' are not going to be Construct bugs, because you are bypassing all our code and directly changing CSS, which is all handled by the browser.

**Comment by JeFawk** [comment]
God dammit!

Thanks a lot!

**Comment by AshleyScirra** [comment]
We don't validate anything at all with 'Set CSS', we just pass it right through to the browser. That is a bit of a gotcha though :P
