### ISSUE TITLE
Editor <form> colors hard to read

### ISSUE THREAD

**Issue by dupkey** [Scirra/Construct-3-bugs#1265]
## Problem description

When using a dark browser/os theme along with a browser that supports client-side decoration the form field colors in the editor are hard to read. The general rule in css is if you define a field text color you should define a background color too or else let the browser/os decide. Screenshot attached.

![construct 3 make games](https://user-images.githubusercontent.com/2023141/35820089-4b288134-0a6a-11e8-972f-63918c195721.png)

## Attach a .c3p

This relates to the editor.

## Steps to reproduce

1. Open the editor
2. Click on "New Project"

## Observed result

Partially styled form fields.

## Expected result

Better css coverage.

## Affected browsers

* Chrome: no
* Firefox: yes
* Edge: no access to windows
* Safari: no access to mac

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 58.0
Browser engine: Gecko
Browser architecture: (unknown)
Context: browser
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0
C3 release: r83
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 8.2 mb (0.4%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    UI animations are disabled in Firefox due to bug 1354501
    CSS containment is not supported. Editor performance may be significantly degraded.
    The <dialog> element is not supported. A polyfill is in use.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 255
Extensions:

    EXT_color_buffer_float
    EXT_texture_filter_anisotropic
    EXT_disjoint_timer_query
    OES_texture_float_linear
    WEBGL_compressed_texture_etc
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Isn't this a problem with the default stylesheet you've applied? Those colors aren't what Construct specifies, it's what your custom stylesheet specifies. If it changes the background color, shouldn't it change the text color too?

**Comment by dupkey** [comment]
The gtk+ stylesheet specifies a background and text color (see screenshot) however the text color is being overriden by the editor styles. So essentially there is a mismatch. From what I inspected of the editor stylesheet is that it only specifies a "color" element for input, option, and select fields. No background color specified.

![a pen by dominic businaro](https://user-images.githubusercontent.com/2023141/35821761-b4e200dc-0a6f-11e8-9fd5-5d218d83a28a.png)

body, html, input, option, select {
    color: #000;
}

**Comment by AshleyScirra** [comment]
Where do you get this stylesheet and how do you use it? Can you provide steps for me to see what you're seeing?

**Comment by dupkey** [comment]
I'm running Gnome 3.26 desktop on Arch Linux with the Adwaita-dark theme that comes pre-installed. Firefox 58 running the default theme which inherits the gtk styles.

In order to duplicate environment you would have to spin up a virtual machine with Antergos and install the Gnome desktop. Then set the application theme to Adwaita-dark using the Tweak tool.

To help maybe explain the issue better I've supplied a link to a browser plugin that I use at times. The "About this extension" section explains the problem (better than I can).

https://addons.mozilla.org/en-US/firefox/addon/text-contrast-for-dark-themes/?src=api

**Comment by AshleyScirra** [comment]
OK, well I haven't gone through all that yet, but I've removed the default color: black style from the next build which should allow a user agent stylesheet to override it. Let me know how it looks when the next release is out.

**Comment by AshleyScirra** [comment]
OK, r84 is out with this change, let me know how it works.

**Comment by dupkey** [comment]
Looks good. Thanks for your help!
