### ISSUE TITLE
No repro crash

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1267]
## Problem description

This is probably a useless report because I can't reproduce it. Maybe you can check the code and see a possible issue.

I was using remote preview and right after i refreshed the client's browser tabs connected I also updated the project. The app then crashed. I tried for 10 minutes to reproduce it and nothing.

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot convert undefined or null to object @ TypeError: Cannot convert undefined or null to object at Function.entries () at e (https://editor.construct.net/r83/exporters/preview/exporter.js:1:9571) at window.ǃMX.ǃMG (https://editor.construct.net/r83/exporters/preview/exporter.js:1:15405) at window.ǃMs.ǃEF (https://editor.construct.net/r83/exporters/preview/exporter.js:1:18109) at 
Stack: TypeError: Cannot convert undefined or null to object at Function.entries () at e (https://editor.construct.net/r83/exporters/preview/exporter.js:1:9571) at window.ǃMX.ǃMG (https://editor.construct.net/r83/exporters/preview/exporter.js:1:15405) at window.ǃMs.ǃEF (https://editor.construct.net/r83/exporters/preview/exporter.js:1:18109) at 
Construct 3 version: r83
URL: https://editor.construct.net/index.html
Date: Tue Feb 06 2018 04:47:36 GMT+0200 (GTB Standard Time)
Uptime: 8683.6 s

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r83
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I can tell from the crash report it failed trying to send a null message during remote preview. I've added in some extra error handlers for the next build to try to make sure this type of error is caught. That's about as much as we can do from a crash report like this.

**Comment by JeFawk** [comment]
That's great then!
