### ISSUE TITLE
'pre-load sounds' stops game from loading on mobile

### ISSUE THREAD

**Issue by cb85** [Scirra/Construct-3-bugs#1268]
Not sure if this is happening to anyone else but if 'Pre-load sounds' is set to on, it stops the game from loading on mobile. It has the same effect on debug apk and the signed and aligned apks. I even tried alpha testing on the google play store and it still doesn't load fully. The blue loading bar only goes to near complete then stops. 
If I turn 'pre-load sounds' to off, then all games work and load correctly no matter what settings I apply but no sounds play with it set to off. I put a basic test file here and once again it doesn't load on mobiles if its set to on but it does load with it set to off
[Test (3).zip](https://github.com/Scirra/Construct-3-bugs/files/1704468/Test.3.zip)

**Comment by AshleyScirra** [comment]
I built the provided project as a debug APK and it ran fine on my HTC 10 with Android 8. It's not surprising, because the provided project does not include any audio at all. Please always follow the full bug report guidelines to ensure we can investigate the issue you're reporting.

**Comment by cb85** [comment]
I included audio files. how come they are not showing? maybe the problem though is for android 6 and below. i'm using android 6

________________________________

**Comment by AshleyScirra** [comment]
The project you attached has no audio files. The sounds and music folders are empty.

**Comment by cb85** [comment]
I've made a new one with sounds. They are included for sure this time. Can you test using Android 6 first then 7/8? I'm only using Android 6
[Test.android.debug.zip](https://github.com/Scirra/Construct-3-bugs/files/1717480/Test.android.debug.zip)

**Comment by AshleyScirra** [comment]
Can you submit the original Construct project instead?

**Comment by cb85** [comment]
I had a friend test it on Android 7 and it worked, but it still won't work on Android 6 Here is the original project [https://1drv.ms/f/s!AmRrzcoCxa52i3qWqP7738kKq40m](url)

**Comment by AshleyScirra** [comment]
Nope, that's still a compiled APK.

This sounds exactly like #1145 by the way - it turned out the device had a really old web view that had never been updated. If you update the webview it should work. There's a test APK in that issue thread that you can use to test your webview version.

**Comment by cb85** [comment]
Ahhh I updated the webview and now it works! I had turned auto-updates off because my phone memory was limited. Well that's fixed the problem Thanks for the help
