### ISSUE TITLE
Sprite color can't change 

### ISSUE THREAD

**Issue by iftikharlove555** [Scirra/Construct-3-bugs#127]
Please I don't know how to attach images or video here but if you see there in the image or sprite editor I can't change the color of sprite or tilemap I just signed here in gethub for construct 3 issues I don't know anything in gethub thanks

**Comment by shortercode** [comment]
[Please read the guidelines before posting bugs](https://github.com/Scirra/Construct-3-bugs/blob/master/README.md)

It is very important to use the bug template, otherwise it is very hard for us to help you

**Comment by iftikharlove555** [comment]
![screenshot_2017-04-27-20-53-35](https://cloud.githubusercontent.com/assets/28054777/25495588/b23ca2d0-2b8e-11e7-8e6a-65e10e6c8dbd.png)
![screenshot_2017-04-27-17-38-35](https://cloud.githubusercontent.com/assets/28054777/25495603/bacd5174-2b8e-11e7-9a70-cb99665133af.png)
