### ISSUE TITLE
problem with free edition limits

### ISSUE THREAD

**Issue by ilanah** [Scirra/Construct-3-bugs#1270]
## Problem description

when getting the free edition limits message, even deleting many lines doesn't help and you stay stuck with the limit indication

## Attach a .c3p
https://drive.google.com/open?id=122pQLGnDapdWUrp20M5KD0CvgILqZKfW

## Steps to reproduce

1.Try to add any action, drag lines etc. everything is blocked.
2.
3.

## Observed result

I keep getting the free edition limits message

## Expected result

1. if i get the free edition limits message - it should show why (I see I have 20 events remaining. if it counts additional things, it should be mentioned.
2. when I remove a few items, the blocking should be removed

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?
## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE
Platform information
Browser: Chrome
Browser version: 64.0.3282.119
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
C3 release: r85
Language setting: en-US

Local storage
Storage quota (approx): 6.9 gb
Storage usage (approx): 124 mb (1.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The free edition limits also include a maximum of 2 layers, 2 effects and 1 web font. The project uses more than 2 effects so you must also delete those before the project can be edited in the free edition again.

**Comment by ilanah** [comment]
So maybe you can put this info in the message that shows the free edition was exceeded ?
There was no way for me to find this out :-(
