### ISSUE TITLE
[Construct 3 Desktop] Doesn't Allow Opening Devtools For Advanced Debugging

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1271]
## Problem description

I'm using the desktop (NW.js) version of Construct 3 and would like to open up devtools using the action found inside the NW.js plugin.

## Attach a .c3p

[OpenDevtoolsBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1708077/OpenDevtoolsBug.zip)

## Steps to reproduce

1. Open Project
2. Preview it
3. Notice the action doesn't work

## Observed result
The open devtools action doesn't work as it's supposed to.

## Expected result

Users should be able to open devtools in preview for the purpose of debugging.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary></summary>

Nothing.

</details>

**Comment by AshleyScirra** [comment]
The desktop build has been updated to Chrome 64 and now also includes dev tools.

**Comment by TheRealDannyyy** [comment]
Great news, thanks for the quick fix!
