### ISSUE TITLE
[C2 Compat] "1 Click" Direct Browser Previewing Feature

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1272]
## Problem description

In Construct 2 users could pick a preview browser to directly preview their projects in (_1 click_ preview).
Construct 3 so far doesn't offer a way to directly preview your projects inside a specific browser and defaults to previewing inside the browser you're currently in.

I would like to make it clear that previewing in other browser **is possible**, my problem is that I would like to have _1 click previewing_  like Construct 2 had, instead of: 
1. launching remote preview
2. copy the access URL 
3. open the browser 
4. paste the URL and start

## Attach a .c3p

Any project will do.

## Observed result

Construct 3 doesn't offer _1 click previewing_ like Construct 2 did.

## Expected result

![preview browser](https://user-images.githubusercontent.com/15656049/35988462-bc46a9ae-0cfe-11e8-80a7-745277715334.PNG)

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Nothing.

</details>

**Comment by NetOneGames** [comment]
got a feeling this is gonna be closed as a feature request.  Better off on the suggestions board https://construct3.ideas.aha.io/

**Comment by TheRealDannyyy** [comment]
I'd rather go with a missing feature that didn't get ported into Construct 3 yet.

Since we got a desktop build now there shouldn't be any problems with file-access anymore, which I assume was the main reason for this feature not getting ported yet.

**Comment by AshleyScirra** [comment]
Browsers don't let to launch other applications, even other browsers. In general being able to launch an external application from a web page is a major security vulnerability (e.g. launch `cmd.exe /C ...`). So this capability is simply not possible in a browser. It's one of the few things C2 had that we can't directly reproduce in C3. Cross-browser testing is possible with Remote Preview - or just loading C3 itself in another browser! - and that's about the best we can do from a browser for now.
