### ISSUE TITLE
R85 Firefox Open project dialog not scrolling

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1273]
## Problem description

Trying to open a project in firefox there are no scroll bars in the open project dialog. Scrololing the file list with touch does not seem to work either.

## Attach a .c3p

N/A
## Steps to reproduce

1. Open editor in firefox
2. Click open from cloud. Make sure you have a list extending so that there would be scrollbars.
3. Notice there is no scrollbars. And not scrolling on touch.

## Observed result

Can't scroll file list.

## Expected result

Should be able to scroll.

## Affected browsers

* Firefox: yes

**Comment by tunepunk** [comment]
I might add that even mouse wheel scrolling doesn't work either.

**Comment by shortercode** [comment]
We had this issue before #769 but it was solved, I'm not aware of any changes made to the cloud dialog itself that could cause this. @tunepunk do you know if this is a recent break?

**Comment by shortercode** [comment]
It's okay I took a look through the old releases and it looks like it was broken in r72. Going to see if there's any obvious breakages in that release.

**Comment by tunepunk** [comment]
For me it must have broke one the latest stable release. Didn't notice anything before that, but I could be wrong. Testing on my Mac now it seems to work fine on R71 in firefox. But after that release it does not seem to scroll.

**Comment by shortercode** [comment]
Seems to have been broken by the fix for #1055

**Comment by shortercode** [comment]
Fixed for r87
