### ISSUE TITLE
FF. does not load images

### ISSUE THREAD

**Issue by DudetteonTheEdge** [Scirra/Construct-3-bugs#1274]
## Problem description

When opening a project the images are shown as pink rectangles.

## Steps to reproduce

1. open C3

What happens
Pink rectangles

*What did you expect to happen instead?*
Images to show

* Chrome: no
* Firefox: yes
* Edge:  no
* Safari: na

## System details
Windows 10 

PASTE HERE
![c3 blank images](https://user-images.githubusercontent.com/6223991/36040279-9c52a0a8-0d8a-11e8-8e21-9bfdedd6b0de.png)

</details>

**Comment by AshleyScirra** [comment]
We cannot investigate this unless you follow the bug report guidelines and attach the project file.

**Comment by DudetteonTheEdge** [comment]
It's not specific to one project. Several do the same thing this is why I did not include anything. But thanks. I guess I will get out of the bug reporting.  
Good luck on your development.
