### ISSUE TITLE
R85 Crash when rightclicking search results.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1275]
## Problem description

Using control+F to search then right clicking the search result resulted in a crash. I only tested firefox so far as I don't have chrome installed on this machine. Might be worth testing other browsers as well.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open any project.
2. Use control+F to open search dialog.
3. Right click the result.

## Observed result

Construct Crashes

## Expected result

*Should not crash.

## Affected browsers

* Firefox: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information

Type: unhandled exception
File: https://editor.construct.net/r85/components/bars/findResultsBar/findResultsBar.js, line 1, col 4092
Message: ReferenceError: event is not defined
Stack: ǃXN@https://editor.construct.net/r85/components/bars/findResultsBar/findResultsBar.js:1:4092 ǃnu@https://editor.construct.net/r85/components/bars/findResultsBar/findResultsBar.js:1:3686 window.ǃJF Construct 3 version: r85
URL: https://editor.construct.net/
Date: Sat Feb 10 2018 11:36:59 GMT+0100 (W. Europe Standard Time)
Uptime: 42.8 s
Platform information

Browser: Firefox
Browser version: 58.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
C3 release: r85
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, EXT_disjoint_timer_query, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Firefox only bug. Fixed in r86.
