### ISSUE TITLE
Crash when previewing in debug mode twice

### ISSUE THREAD

**Issue by dru1000** [Scirra/Construct-3-bugs#1276]
## Problem description

C3 Desktop only - bit obscure and was driving me crazy but I was finally able to reproduce it consistently.

C3 crashes when you preview a project first in Debug mode then without closing the preview window preview the project again, closing the second preview window causes the crash.

## Attach a .c3p

Use a blank C3 project

## Steps to reproduce

1. In C3 Desktop preview blank project in Debug mode
2. Leave the preview window open and click preview again (choose either regular preview or debug this time)
3. Close the preview window and C3 crashes

## Observed result

 C3 crashes

## Expected result

Not crash

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
There's a new desktop download based on Chromium 66 / NW.js 0.30.0: https://www.scirra.com/forum/construct-3-desktop-build-beta-currently-win64-only_t199344

With this version I can't reproduce the problem any more. Can you confirm it's resolved for you with the latest download?

**Comment by dru1000** [comment]
Yes confirmed its fixed on the latest version - thanks!
