### ISSUE TITLE
C3 Desktop App fails to export mobile project

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#1277]
## Problem description

I am not able to export a Debug APK from the desktop version of C3, I can successfully export projects in the web app. 

## Attach a .c3p

I was able to reproduce using the Ghost shooter tutorial in the beginner examples 

GIF :  https://drive.google.com/open?id=1Uj7Ba-3o6bN403KmpL13QlylOaoKixdo

After the export these files were generated even though the build failed

Generated Files : https://drive.google.com/open?id=1jBOP-6k2yJAamn034JJWBHNs5KUCvDCB

## Steps to reproduce

1. Create a new project from the beginner tutorial - Ghost Shooter
2. Go to export android (cordova)
3. Have duplicate images, re compress images, and minify script all checked
4. min Version set to 5.0 lollipop, debug apk, hid status bar checked
5. Export project

## Observed result

Project failed to build but some files were still generated, not debug apk file, 

## Expected result

have a debug apk generated

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.140
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
C3 release: r85
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 158 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
It was getting confused about how it should be exporting the project, the "export to folder" code doesn't quite line up with the Android and iOS exporters.

I've written a patch for r89 which fixes this, but it still asks you for a location at the start of the export. Which isn't used for the APK. So some improvement is still needed, but at least it works correctly now.

**Comment by armandoalonso** [comment]
That's awesome, thanks

**Comment by AshleyScirra** [comment]
@shortercode why not just treat it like NW.js and force the zip export mode in the desktop build? Then it won't ask for an export folder.
