### ISSUE TITLE
Request Fullscreen doesn't work using C3 Desktop

### ISSUE THREAD

**Issue by dru1000** [Scirra/Construct-3-bugs#1278]
## Problem description

Adding an event
--Mouse On Any Click
-->Browser Request Fullscreen 
doesn't do anything when previewing from C3 Desktop

## Attach a .c3p

Add that 1 event to a blank project

## Steps to reproduce

1. Add Mouse On Any Click event (C3 Desktop only)
2. Add browser action Request Fullscreen
3. Preview

## Observed result

Nothing happens

## Expected result
The game should go fullscreen

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.
