### ISSUE TITLE
publish ios

### ISSUE THREAD

**Issue by zou9** [Scirra/Construct-3-bugs#1280]
to publish any project on Cordova and then for Xcode it work
the downloaded file where I could open Xcode is white file an is not readable by any software ?

**Comment by shortercode** [comment]
You'll need to give me some more information, you should always fill in the template on bug reports.

Please take a look at our [ios application development and publishing with xcode](https://www.construct.net/gb/tutorials/ios-application-development-and-publishing-with-xcode-25) tutorial. If your still having problems then open an new bug with as much of the template completed as you can.
