### ISSUE TITLE
Preview doesn't work in iframe/other windows

### ISSUE THREAD

**Issue by EntityB** [Scirra/Construct-3-bugs#1281]
## Problem description

If run preview in construct editor, I can't run preview in other windows or iframes. In C2 this was possible. Now we can't test games properly in embed platforms like http://emulator.gameeapp.com . This is still possible with remote preview, but remote preview is not part of free distribution of C3. 

Now for example, if there is a developer that want to develop games for our platform/any other platform, he might not choose C3 because of initals problems with testing. 

## Attach a .c3p

Any project

## Steps to reproduce

1. Run preview of layout/project
2. Copy paste link into other window
3. Nothing is happening there

## Possible solutions

Make previews work in other windows and iframes.

**Comment by AshleyScirra** [comment]
Browsers don't have permission to run web servers, so we can't directly host a game on localhost like C2 did. Potential workarounds:

- export to HTML5 and host on local web server
- use Remote Preview (for paying customers)
- change how the emulator works
