### ISSUE TITLE
Unable to place Objects from Project tab to Layout on iOS.

### ISSUE THREAD

**Issue by sergeypisarev85** [Scirra/Construct-3-bugs#1283]
## Problem description

*Enter a concise description of your problem here*

Unable to place Objects from Project tab to Layout on iOS.
You can only do so in Desktop mode, but it’s not comfortable, since you need to reload Construct 3 to change to Desktop mode from Mobile.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. See the comments in #692.
