### ISSUE TITLE
Cloud Save (Google Drive) issue when closing project with unsaved changes (will lose unsaved changes)

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1285]
## Problem description

Closing Project with unsaved changes then request save when prompted results in project close, no save , and error message

(only tested with google drive - unknown if other cloud save options give the same result)

## Attach a .c3p
[UnsavedChangesIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/1718173/UnsavedChangesIssue.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

Best demonstrated with new blank c3p   (extension changed to zip for attached)

but any new or mature project will do. (as  long as there are unsaved changes)

## Steps to reproduce

(google drive set as cloud save option)

1.  Open attached project
2.  Add a simple sprite box to it    
3.  Do not save in any way
4.  Using menu,  select option to close project
5.  receive pop up message about unsaved changes
6.  select option to save and close

## Observed result

- Project closes
- Changes are not saved
- receive this message

![image](https://user-images.githubusercontent.com/21962641/36127486-a9008d9c-1055-11e8-84ab-396df3ac9150.png)

## Expected result

- project saved and
- project remains open until save is confirmed successful by the editor
- project does not close  if save was not successful with warning message

## Affected browsers

* Chrome: only tested

## System details

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r86
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 12 gb (82.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by shortercode** [comment]
Okay dokes, think I've found this. Looks like a change was made and it no longer waits to complete the save before closing the project. Which obviously causes some problems. I believe this only happens if the project hasn't been saved before, but probably worth avoiding "close and save" for the time being. Should be fixed in r87.

**Comment by shortercode** [comment]
Going to keep this open with the fixed label, in case anyone else has this issue.
