### ISSUE TITLE
Changing size of the sprite stops physics movement.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1286]
## Problem description

I have a sprite that uses physics for movement. When I try to resize the sprite while it's moving, It stops.

## Attach a .c3p

https://drive.google.com/open?id=1_Od2XngxyMX4XyhxlDIyO77v1Zmko_iN

## Steps to reproduce

1. Run the example project and press A. 

## Observed result

It stops.

## Expected result

Keep moving and make the object bigger.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
I've adjusted how the physics body is recreated for the next build and this seems to help. So should be fixed in the next release.
