### ISSUE TITLE
Animations editor, rectangle tool snaps incorrectly.

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#1287]
## Problem description

In the animations editor if your using the rect tool and snap to grid the edge always aligns to the bottom right quadrant. This prevents you from creating a rectangle that fits into part of the grid.

## Attach a .c3p

Can be replicated by adding a sprite to a blank project.

## Steps to reproduce

1. Open a sprite in the animations editor
2. Enable grid overlay and snap to grid
3. Select black as the secondary colour
4. Using the rectangle draw a rectangle

## Observed result

Rectangle edges always align to the bottom right.

![screenshot 2018-02-13 15 09 55](https://user-images.githubusercontent.com/9051865/36157050-c79d0386-10d0-11e8-93ff-20d85a66c3c4.png)

## Expected result

All edges should align to the inner quadrant of the grid. Alternatively the outer edge, but that's probably less useful.

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: untested

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.140
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
C3 release: r86 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 1.9 gb (6.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_get_buffer_sub_data_async
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in r91
