### ISSUE TITLE
Unable to Load project version R86 from R85.

### ISSUE THREAD

**Issue by sergeypisarev85** [Scirra/Construct-3-bugs#1288]
@## Problem description

*Enter a concise description of your problem here*

Hello! I just found that I’m not able to load project that I saved in version R86(beta), in stable version.

And now i’m forced to use beta version, since R85 gives me an error loading my file.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Save your project in R86, to Cloud.
2. Try to load it from Cloud in version R85
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>
https://drive.google.com/open?id=1oT9Yz1DrQb5r3WrwKd70WkByc3m32p8o

Cannot attach file from iPad

**Comment by sergeypisarev85** [comment]
I’ll try right now

**Comment by sergeypisarev85** [comment]
Empty file works fine. I’ll add my c3p file right away.

**Comment by shortercode** [comment]
Thanks @sergeypisarev85

**Comment by AshleyScirra** [comment]
I can open that .c3p just fine in r86. Can you copy-paste in any error message that you see?

**Comment by sergeypisarev85** [comment]
One sec..

**Comment by sergeypisarev85** [comment]
Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.

**Comment by DiegoScirra** [comment]
Can you see any error in the browser console? You can bring it up with **Ctrl + Shift + I**

**Comment by sergeypisarev85** [comment]
@DiegoScirra I’m unable to that right now, cause i’m working from iPad. But maybe if I will find PC, and then try it.

**Comment by DiegoScirra** [comment]
Alright, no worries.

**Comment by shortercode** [comment]
Okay can confirm this, projects created in r86 containing either the text or spritefont plugin will not load in r85. Given that it's a forwards compatibility issue there's not really anything we can do about it at this point.

If you wish I can probably convert your project back to an r85 compatible one, but unless your experiencing any serious issues with r86 I would just stick with it if I were you.

Incidentally @AshleyScirra should properties that aren't usable in release be being added to user projects?

**Comment by AshleyScirra** [comment]
Construct has never been forwards-compatible, i.e. you've never been able to open a project saved in a future version of Construct. So if that's all this is then there's nothing new here, but if you just get a "failed to open project" error then I guess we should improve that.

**Comment by sergeypisarev85** [comment]
@AshleyScirra The main thing for me is, will it work with future versions of construct. If yes, there is no problem.

@shortercode Thank you!

P.S. Btw I can’t remember seeing a Warning sign when I opened my project in beta version.(But maybe I just didn’t saw it)

**Comment by AshleyScirra** [comment]
Yes, we have a very good track record of ensuring even very old projects can still open in newer versions of Construct. It's just you can't open them in older versions of Construct than the one you saved it in.

I'll leave this open to make sure we improve the error message.

**Comment by AshleyScirra** [comment]
OK, I've added an improved error message for the next release, but it relies on a new field saved to the project file so will only take effect from the next release onwards.
