### ISSUE TITLE
Notifications dismissed by closing dialog

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#129]
## Problem description

When a notification appears in the lower-left (e.g. "update available") while a modal dialog is showing (e.g. About dialog), closing the dialog causes the notification to be dismissed.

Quite frequently I find the notification shows just a moment before I close a dialog, so you see a notification flash past but never get to read it.

## Observed result

Closing dialog dismisses notification.

## Expected result

Notification should continue to display after dialog closed.

**Comment by DiegoScirra** [comment]
Fixed in r25.
