### ISSUE TITLE
"Failed to open project. Check it is a valid Construct 3 folder project."

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#1293]
## Problem description

I get this error trying to open a .c3proj in the desktop version of C3:

Failed to open project. Check it is a valid Construct 3 folder project.

I was literally just working on it. Saved, closed C3, opened C3 later, tried to load the project, and this error popped up. No updates or modifications elsewhere.

## Attach a .c3p

Can't attach my project here. I assume this will work with a blank .c3proj. If not I'll see what I can do.

## Steps to reproduce

1. Try to open a .c3proj in the desktop version of C3

## Observed result

"Failed to open project. Check it is a valid Construct 3 folder project."

## Expected result

The project to open.

## System details

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r85
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 21 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by Tokinsom** [comment]
Trying to reproduce with a blank .c3proj with no luck...I can't upload my project publicly though - is there an email and reference number I can send it to?

**Comment by AshleyScirra** [comment]
Posted in #1291:

> @AshleyScirra So it appears that I renamed a layout and the project still thinks the old one is still there somewhere and won't load. Was Dungeon_0, now DungeonEntrance. Console screenshot: https://puu.sh/zqFUK/840f31e9c5.png

**Comment by AshleyScirra** [comment]
According to that screenshot a layout was renamed but a 'Go to layout' action wasn't updated. If you send the project to me I can probably recover it (ashley@scirra.com), but ideally we need steps to reproduce to fix the underlying issue.

**Comment by AshleyScirra** [comment]
Actually I can reproduce: simply save a folder-based project, create a 'go to layout' action, and rename the layout it goes to. Save then reopen; the action hasn't updated.

**Comment by AshleyScirra** [comment]
OK, should be fixed in r88. It's a bit awkward that we don't have a beta release for the desktop builds yet, but hopefully we'll get to a stable branch soonish.

**Comment by pkreemer** [comment]
Ashley, I think this is back in R134, with the beta channel Win64 Chromium desktop build.  Or a close relative, that I see with event sheet renaming in folder projects.

It's easy to repro as:
1) Create new project, save as project folder,
2) Add a second event sheet "Event sheet 2",
3) Include 2nd event sheet in first.
4) Save project, close Construct3, re-start, and verify that project loads.
5) Rename 2nd event sheet to: "Event sheet 2a"
6) Save project, close Construct3, re-start and try to load project.
7) See error "Failed to open project. Check it is a valid Construct 3 project folder."

The event sheet rename is correctly updated in project.c3proj and the actual event sheet filename, but isn't propagating to the _including_ event sheet or to project.uistate.json.

**Comment by AshleyScirra** [comment]
Please file a new issue, this one was closed around a year ago.
