### ISSUE TITLE
Autocomplete inappropriately replaces valid text-based terms in expressions

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1295]
## Problem description

Autocomplete is replacing existing text-based terms (variables, system functions, etc.) if I hit tab to complete a new term that's butting up against an existing one. I want to be able to click at the start of an existing term, start typing a new term, autocomplete the new term, and wind up with both terms still intact.

## Attach a .c3p

Can be easily reproduced with a new project.

## Steps to reproduce

1. Add a global variable, i.e., a number "fred", to an event sheet.
2. In the event sheet, add a condition that takes an expression as a parameter, i.e., System->Compare two values
3. In the expression field, type "fred".
4. Click in the expression field at the start of the term "fred" and begin typing a new term, i.e. "abs".
5. Hit tab to autocomplete the new term

## Observed result

"fred" is replaced with "abs".

## Expected result

Because "fred" is a valid term, I expect the final expression after hitting tab to autocomplete to be "absfred", with the cursor sitting between "abs" and "fred".

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.167
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
C3 release: r85
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 102 mb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think there is a possible conflict with #533 here - the reason it replaces the text to the right of the caret is because of the fix of that. However I've added an exception for the next release so if you autocomplete something that is already fully typed, it won't delete the characters to the right. Hopefully this fixes it without affecting any other use cases.

FWIW you can just type the next `(` character with the autocomplete still open, and it will enter correctly.
