### ISSUE TITLE
Event sheet adjustments aren't memorized

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#1296]
## Problem description

Event sheet adjustments aren't memorized when closing/reopening an event sheet or closing/reopening a project. Numerous users reported this here: https://www.scirra.com/forum/event-sheet-adjustments-aren-t-memorized_t200662

Also, it would be great if these adjustments were global and applied to all event sheets. It's annoying and cumbersome to have various widths throughout all the sheets that constantly need adjusting. Maybe an option in the settings?

## Attach a .c3p

Can use a blank .c3p

## Steps to reproduce

1. Open an event sheet
2. Adjust various event block widths
3. Close and reopen event sheet

## Observed result

Event block adjustments revert to default

## Expected result

Event block adjustments should be memorized.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.
