### ISSUE TITLE
Event groups expand when moved

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#1297]
## Problem description

Moving an event group expands it, making event group organization a bit of a pain. I'm not sure if this is a bug, but it would be nice if they stayed collapsed when moving them around.

## Attach a .c3p

Can use a blank .c3p

## Steps to reproduce

1. Great a few event groups and fill with blank events
2. Move an event group above or below another one

## Observed result

Event group is expanded

## Expected result

Event group should remain collapsed

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.
