### ISSUE TITLE
[Request] Display type for web export

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#1299]
## Problem description

After a HTML5 web export, there is a file called **_appmanifest.json_** and within that file, there is an option for `"display":` . It would be great if it has options for it to be a `standalone` without me doing it manually on each export.

C3's mobile **Add to Homescreen** shows the status bar and navigation buttons but games made with C3 are only fullscreen by default. That's why I suggest an option for it.

**Comment by AshleyScirra** [comment]
Please post suggestions here: https://construct3.ideas.aha.io/
