### ISSUE TITLE
When trying to add a new item to a list, Pressing the enter key closes the expanded text editor

### ISSUE THREAD

**Issue by Stercus1** [Scirra/Construct-3-bugs#130]
## Problem description

Pressing the enter key to add a new item on a list with the new text editor closes it. A temporal solution is to use the smaller text box in the properties window 

## Steps to reproduce

1. Create a new list on the project
2. In the items section on the properties of the list, open a the new text editor
3. Click the text box to focus it
4. Press enter

## Observed result

The window is closed

## Expected result

Add a new line in the text box, thus adding a new item to the List

## Affected browsers

* Chrome: yes
* Firefox: Don't know
* Edge: Don't know
* Safari: Don't know

**Comment by AshleyScirra** [comment]
This is by design. Enter is the global keyboard shortcut to close with OK. Hold shift and press enter to type a newline.

**Comment by Stercus1** [comment]
Ok, then, but you guys should put a message saying this and other useful key combinations in the editor, just saying
