### ISSUE TITLE
Cntrl + W does not close current tab like in C2, on C3 desktop build.

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#1300]
## Problem description

When you're in the layout or event editor, normally in C2 you can press Cntrl + W to close the tab you're on and it switches to a different tab. But this does not occur in C3 desktop build, it's a standard feature for tabs in UI across software like Browsers, Photoshop, etc.

(Obviously it can't occur in the browser C3 versions)

## Attach a .c3p

[default_empty_project.zip](https://github.com/Scirra/Construct-3-bugs/files/1738981/default_empty_project.zip)

## Steps to reproduce

1. Press Cntrl + W in a project

## Observed result

Nothing happens

## Expected result

The current tab/window should close.

**Comment by AshleyScirra** [comment]
Added for next release.
