### ISSUE TITLE
Changes with External image editor do not affect original Sprite correctly.

### ISSUE THREAD

**Issue by supervanz** [Scirra/Construct-3-bugs#1301]
## Problem description

When you use eraser tool or resize tool in external image editor the changes do not affect original sprite correctly.
(Desktop version)

## Attach a .c3p

https://1drv.ms/u/s!AmXbEqgPUA_2ldEJzmiHYBPYxsElRw

## Steps to reproduce

1. Create a sprite in C3 desktop version.
2. Link external image editor (Tested with Photoshop and Aseprite)
3. Click use external editing software button
4. Make any change with eraser tool or resize tool in external edit software and save it.
5. Return to C3 and Click Appy Changes.
6. Close Animation Editor window.

## Observed result

Changes with eraser tool or resize tool in external image editor does not affect Sprite in C3 correctly.

## Expected result

Changes with eraser tool or resize tool in external image editor should affect Sprite in C3 correctly.

## Affected browsers

* Desktop version: Yes
* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r91
