### ISSUE TITLE
[Website] Weird Corrupted Symbols In Follower Notifications

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1302]
## Problem description

The follower notifications have a weird symbol that's probably not supposed to be there.

## Example Image

![notificationbug](https://user-images.githubusercontent.com/15656049/36430681-1a9bbc78-1656-11e8-8dfd-b3cfbc6db62e.PNG)

## Steps to reproduce

1. Open C3 notifications
2. Let someone follow you
3. Notice weird symbol

## Observed result

Just a weird symbol, everything else works fine.

## Expected result

No weird symbol.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: -
* Safari: -

**Comment by shortercode** [comment]
🡺 does this character render as an arrow for you @TheRealDannyyy.

Looks to be that codepoint 0x01F87A isn't rendering for you for some reason.

**Comment by TheRealDannyyy** [comment]
Nope it doesn't @shortercode.
In FF it's that weird corrupted symbol and in Chrome it's just an empty box.

Noticed the same issue on the official plugin pages:
![corsymbagain](https://user-images.githubusercontent.com/15656049/36431766-b52afb1c-1658-11e8-9a2a-1d0fad9e7069.PNG)

**Comment by shortercode** [comment]
For Tom's reference that one looks like [0x01F5D7](https://unicode-table.com/en/1F5D7/).

It's a font rendering fallback icon, some systems/fonts will render a blank square and others will render a square with the character code.

I'm guessing it's falling back to a system font that doesn't have those icons.

**Comment by TheRealDannyyy** [comment]
I'm fairly certain that my Win7 system supports Unicode but it could be possible that is one of those rare cases were something is going wrong on my end only.

**Comment by shortercode** [comment]
I think this may be related [Chrome breaks Windows 7's display of Unicode](https://bugs.chromium.org/p/chromium/issues/detail?id=42984) it's really hard to tell though, as far as I can tell that bug just died out as less people complained about it. 

Do you have problems viewing emojis and the like on that computer?

**Comment by TheRealDannyyy** [comment]
Only with some Unicode chars as it seems and it's worse in Chrome for some reason.
Tests done using this great website: http://www.alanwood.net/unicode/.

**Comment by shortercode** [comment]
Well... it's pretty odd. The website is Tom's work so going to leave it to him!

**Comment by pooyaGames** [comment]
![screenshot 2018-02-21 06 52 24](https://user-images.githubusercontent.com/426713/36461624-cb9fb5ce-16d3-11e8-8341-2fc03a49b3cc.png)
i cant see it either, using chrome on mac 

64.0.3282.167 (Official Build) (64-bit)

**Comment by phillscirra** [comment]
The offended characters in the next update will have been replaced with image files, instead of a font.

However, it does appear this issue is overall machine specific, and related to a long term bug within Chrome/Windows 7 (as noted by the TheRealDannyyy in a posted link, thanks Danny) - you may still experience similar problems with other websites.

**Comment by TheRealDannyyy** [comment]
Everything works fine now btw, thanks again!

**Comment by TheRealDannyyy** [comment]
@phillscirra Not sure if this is worth opening another issue but I found some more chars that need replacing with image files. (Comment section inside user profiles.)

![unibug](https://user-images.githubusercontent.com/15656049/41356314-eedd7eb0-6f23-11e8-88ed-ccbd7b5da774.PNG)

**Comment by phillscirra** [comment]
Thanks Danny; yeah I've noticed a few more since going through the code a little more thoroughly.  We'll keep this issue for this!   We'll just have to blitz them as we find them. Most of them are for aesthetic purposes, it shouldn't affect functionality in the meantime.

**Comment by AshleyScirra** [comment]
Migrated to new website issues repo: https://github.com/Scirra/Construct.net-website-bugs/issues/1
