### ISSUE TITLE
[Website] H1,H2,H3 Wrong Size In Combination With Other Formatting

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1303]
## Problem description

The H1,H2,H3 formatting tags don't seem to work correctly if used in combination with any of the other formatting options. Tested using: Bold, Italic, Underline, Strikethrough.

## Example Image

![boldtest](https://user-images.githubusercontent.com/15656049/36431353-a90e334a-1657-11e8-9cd2-583d1f2fb71c.PNG)

## Steps to reproduce

1. Use H1,H2 or H3 in combination with one of the mentioned formatting options

> [h3]test[/h3]
> [h2]test[/h2]
> [h1]test[/h1]
> [h3][b]testwithbold[/b][/h3]
> [h2][b]testwithbold[/b][/h2]
> [h1][b]testwithbold[/b][/h1]

2. Notice that the other formatting tag works
3. Notice that H size isn't correct

## Observed result

H1,H2,H3 have the wrong size in combination with other formatting options.

## Expected result

H1,H2,H3 should keep their sizing despite other formatting. 
(Size changes should only apply when using the size formatting option.)

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: -
* Safari: -

**Comment by phillscirra** [comment]
The sizing issue for headers made bold will be fixed in the next release.

However, the reason you're not noticing a different when you make a h1,h2 or h3 tag "bold" is that the tags are already in bold by default (in contrast to regular text without a header tag)
