### ISSUE TITLE
Cant See object (sprite) properties if object not in layout

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1305]
## Problem description

If an object is not in a layout then I cannot see its properties when I click on it

## Attach a .c3p

[Cant see properties.zip](https://github.com/Scirra/Construct-3-bugs/files/1741458/Cant.see.properties.zip)

ext changed from c3p to zip

## Steps to reproduce

1.  open attached c3p
2.  in the project window under object types click on sprite 1 which is in the layout then click on sprite 2 which is not in the layout

## Observed result

you will see that sprite 1 properties appear in the properties window but sprite 2 properties do not appear in properties window and still sprite 1 properties appear

Im sure this worked ok before as Im sure I  would have noticed.

## Expected result

see the properties of the sprite opject

## Affected browsers

* Chrome: only tested

## System details

Platform information
Browser: Chrome
Browser version: 63.0.3239.132
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
C3 release: r85
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 13 gb (86.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by DiegoScirra** [comment]
In this case C2 shows only the **Object Type Properties** and C3 is not showing anything.

**Comment by Scoremonger** [comment]
I think the biggest issue in this bug is the fact that whatever was previously selected remains in the properties view (even though that object isn't selected anymore). If the two objects in question are similar (like Sprite1 and Sprite2), this makes the user think that the newly-"selected" object in the project list is actually properly selected and its properties can be edited. I accidentally edited a bunch of properties for the wrong object yesterday because of this - by the time I realized I didn't have the proper object selected when I made my changes (because it wasn't placed in the layout - whoops), it was easier to just revert to my previous save than to try and undo it.

**Comment by NetOneGames** [comment]
And after preview the properties keep changing back to the one before the one you were using before preview which means making incremental changes in properties then previewing becomes a big hasslehof. .

**also I dont think this should be flagged as compatibility ,    
 what has it got to do with compatibility  ????

the properties window should always show the properties of the last selected object, layer, project, other item etc and retain that through preview and other operations until another object, layer, project is selected.**

**Comment by AshleyScirra** [comment]
"C2 compat" means "we need to make C3 do what C2 did". Please be patient when dealing with bug reports, we have a huge workload.

**Comment by NetOneGames** [comment]
yea i get it, sorry didnt mean to sound inpatient, (just typing stuff without thinking ) you know i think you guys rock!

**Comment by AshleyScirra** [comment]
Implemented this for the next release.
