### ISSUE TITLE
Bug if installing addon in developer mode and in normal mode

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#1306]
## Problem description

The editor hangs at launch if I installed an addon through regular means and then again through the developer mode (using a local webserver).
## Attach a .c3p

None

## Steps to reproduce

1. Create an addon
2. Install it regularly
3. Create a local webserver and host the same addon
4. Install it again through developer mode

## Observed result

This happens
![image](https://user-images.githubusercontent.com/11213825/36455839-4dd1b27c-16a2-11e8-87ee-2d92334f2feb.png)

## Expected result

I guess not crashing, ignoring the regular addon, or not allowing me to do that in the first place.

## Affected browsers

Not relevant

## System details

Not relevant

<details><summary>View details</summary>

Not relevant

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.
