### ISSUE TITLE
[r23] Bars popup window is blank

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#131]
## Problem description

When any bar is open to pop-up window, it is blank.

## Steps to reproduce

1. Open to pop-up window of any bar such as Project bar or Tilemap bar.

## Observed result

The pop-up window is blank.

## Expected result
Should display the window.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Good catch, fixed for r24.
