### ISSUE TITLE
Dictionary editor - There is no way to remove keys

### ISSUE THREAD

**Issue by shinkan-fb** [Scirra/Construct-3-bugs#1312]
## Problem description

If you add few new keys and later decide you don't need some of them anymore you are unable to remove/delete them.  All you can do is to clear the row but that does not removes empty keys from dictionary. So if you have 15 keys and you clear 5, You are still left with 15 but 5 of them are empty.

## Attach a .c3p

[dictionaryeditor.zip](https://github.com/Scirra/Construct-3-bugs/files/1746106/dictionaryeditor.zip)

## Steps to reproduce

1. Open the dictionary editor by opening "New Dictionary.json" file
2. add some keys
3. Try to remove some random keys

## Observed result

As you can see, size of the dictionary is still the same, but now you have empty keys in random places.

## Expected result

There should be an option "Remove key" or "delete row".  so if you have 15 keys and you remove 5.  then Dictionary size should be equal to 10.  

## Affected browsers

* Chrome: no
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.167
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
C3 release: r85
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 222 mb (1.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 780 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
You should be able to reduce the size of the dictionary using the size control? I've added in context menu options for more precise row addition and removal, hopefully this makes it a bit easier for you. Should be in r88.

**Comment by shinkan-fb** [comment]
Yes, You can change the overall size using size control any time, but this makes another issue.
Having a dictionary with 6 keys (A) you remove one from the middle (B). And now if you change the size from 6 to 5 the empty key still remains but instead  the 6th key is removed - we don't want that.   
![size](https://user-images.githubusercontent.com/8943525/36536091-039b68c6-17cc-11e8-82c4-853d50be456e.PNG)

Changing the size should take empty rows in considerations and adjust size accordingly.

Anyways, thanks for the quick fix and info.

**Comment by shortercode** [comment]
Empty rows are still considered rows, as a blank string is a valid key. But I get your point. I added in the same methods that the array editor has for rows, which should cover all the bases here.

- Insert row before
- Insert row after
- Delete row
- Insert row start
- Insert row end

So this should allow you to remove that row instead of clearing it.
