### ISSUE TITLE
Crop transparent images without leaving 1 pixel transparent border.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1313]
## Problem description

When you crop an image, it will leave 1 pixel transparent border. In C2 you can CTRL + Click crop to avoid it and C2 does this automatically in TiledBackground.

## Steps to reproduce

1. Open image editor.
2. Press Crop.

**Comment by AshleyScirra** [comment]
@DiegoScirra - note use the plugin IsTiled() flag to determine whether to turn off the 1px border.

**Comment by DiegoScirra** [comment]
Fixed in r91
