### ISSUE TITLE
Object's family and Object's clone.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1314]
## Problem description

When you clone an object that belongs a family, the clone won't be added to the family.

## Steps to reproduce

1. Create a sprite and add it to a family.
2. Clone the sprite.

## Expected result

The clone should be added to the family.

**Comment by NetOneGames** [comment]
Also it is created on the current selected layer instead of the cloned objects layer

**Comment by NetOneGames** [comment]
Also doesn't inherit behaviors. Looks like clone is not working very well

**Comment by AshleyScirra** [comment]
Should be fixed in the next release.
