### ISSUE TITLE
Delete Image Point 1 > close the image editor > hit CTRL + Z > CRASH

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1315]
## Problem description

This happens only with Image Point 1 and to get this error you should have only Image Point 1 and Origin point.

BTW I can't use delete button to delete image points. Can you implement it, please?

## Steps to reproduce

1. Create a sprite.
2. Add Image Point 1.
3. Close the editor.
4. Open the sprite editor again.
5. Delete the Image Point 1
6. Close the image editor
7. CTRL + Z
8. Crash

## Observed result

Crashes.

## System details

Error report information
Type: unhandled rejection
Reason: Error: expected object @ TypeError: expected object at Function.ǃN.ǃmZ (https://editor.construct.net/r87/main.js:1:178450) at e.ǃVO (https://editor.construct.net/r87/main.js:62:197464) at ǃNP.ǃsts.ǃscZ (https://editor.construct.net/r87/main.js:73:47758) at ǃNP.ǃstv.ǃscZ (https://editor.construct.net/r87/main.js:73:36088) at window.ǃsca.ǃscZ (https://editor.construct.net/r87/main.js:73:36088) at ǃNP.ǃstZ.ǃscZ (https://editor.construct.net/r87/main.js:73:36088) at ǃNP.ǃstZ.ǃscZ (https://editor.construct.net/r87/main.js:73:58996) at window.ǃNyx.ǃCI (https://editor.construct.net/r87/main.js:73:34530) at t.ǃCI (https://editor.construct.net/r87/main.js:62:100530) at window.ǃlDp.ǃCI (https://editor.construct.net/r87/main.js:167:63285)
Stack: TypeError: expected object at Function.ǃN.ǃmZ (https://editor.construct.net/r87/main.js:1:178450) at e.ǃVO (https://editor.construct.net/r87/main.js:62:197464) at ǃNP.ǃsts.ǃscZ (https://editor.construct.net/r87/main.js:73:47758) at ǃNP.ǃstv.ǃscZ (https://editor.construct.net/r87/main.js:73:36088) at window.ǃsca.ǃscZ (https://editor.construct.net/r87/main.js:73:36088) at ǃNP.ǃstZ.ǃscZ (https://editor.construct.net/r87/main.js:73:36088) at ǃNP.ǃstZ.ǃscZ (https://editor.construct.net/r87/main.js:73:58996) at window.ǃNyx.ǃCI (https://editor.construct.net/r87/main.js:73:34530) at t.ǃCI (https://editor.construct.net/r87/main.js:62:100530) at window.ǃlDp.ǃCI (https://editor.construct.net/r87/main.js:167:63285)
Construct 3 version: r87
URL: https://editor.construct.net/r87/
Date: Thu Feb 22 2018 22:11:53 GMT+0300 (Turkey Standard Time)
Uptime: 61.7 s

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r87 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 755M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by DiegoScirra** [comment]
Fixed the crash and added the keyboard shortcut in r91
