### ISSUE TITLE
Exporting to an invalid path causes the interface to be unusable

### ISSUE THREAD

**Issue by cihanyakar** [Scirra/Construct-3-bugs#1317]
## Problem description

Exporting to an invalid path like (`c?:/+%+^%+*`) cause the interface to be unusable.

## Steps to reproduce

1. Open a project
2. Choose "Web HTML 5" on export dialog
3. Enter an invalid path like `c?:/+%+^%+*`

## Observed result

Endless dialogue and a unusable interface.

## Expected result
After the error message, it should return back to the export dialog.

## Affected browsers

* Desktop

## System details
 
r85 **desktop** build

![image](https://user-images.githubusercontent.com/5078937/36593483-e4b52b10-18aa-11e8-9ed2-536346b1759c.png)

**Comment by AshleyScirra** [comment]
Thanks, should properly recover the UI after an error in the next release.
