### ISSUE TITLE
[r23] Dock bars when on widescreen start page caused weird glitches

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#132]
## Problem description

When there are any undocked bars while on wide-screen start page, you can drag and dock to any location. But it can cause weird glitches to the window when docked. There will be empty spaces when docked, sometimes it will attached itself at the top.

## Steps to reproduce

1. Undock a bar.
2. Close all projects, if any.
3. Open the start page tab.
4. Dock the previously undocked bar or any other undocked bars in this widescreen start page.

## Observed result

Weird misplacements and blank spaces shown in different docking area.

## Expected result
Should either not be able to dock any currently undock bars, or hide the undock bar until a project is present/open. 

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed in r24 along with a few other unreported problems with the full screen mode of the start page.
