### ISSUE TITLE
Rectangle and Selection tools in the image editor.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1320]
## Problem description

There is a 1 pixel gap while you're using Rectangle and Selection tool. It makes hard to use for low resolution games. I don't understand where it will begin to draw.

C3:
![2018-02-25_11-15-46](https://user-images.githubusercontent.com/2965842/36639425-5f54c876-1a1d-11e8-9c2a-8d8ced9ed3cb.gif)

C2:
![2018-02-25_11-18-12](https://user-images.githubusercontent.com/2965842/36639431-9e70a624-1a1d-11e8-82db-2166e0545f1a.gif)

*Two suggestions for the image editor:

- Add Continuous bucket options. It's time-consuming to change same colors in the sprite.
![chrome_2018-02-25_11-07-56](https://user-images.githubusercontent.com/2965842/36639365-4915d56a-1a1c-11e8-99f5-2471d312fd26.png)

- If it's easy, please add more than one options for the external image editor selection. I use both photoshop and aseprite for my projects so it would be great If I can select without changing the external image editor path.

**Comment by DiegoScirra** [comment]
This should be fixed in r95.

@bilgekaan Can you create separate issues  for the two suggestions? I'll later tag them as improvements and will get to them eventually.

Cheers!

**Comment by bilgekaan** [comment]
Done, thank you!
