### ISSUE TITLE
Moving objects with Shift + Arrow Keys. 

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1321]
## Problem description

In C2 you can move objects 10 pixels when you press Shift + Arrow Keys. In C3 when your grid size is 1x1 and snap to grid is enabled. It moves objects 1 pixel.

## Steps to reproduce

1. Set your grid size 1x1.
2. Set snap to grid is enabled.
3. Select an object and press Shift + Arrow Keys.

## Observed result

It moves the objects 1 pixel.

## Expected result

It should move 10 pixels.

**Comment by AshleyScirra** [comment]
Should be fixed in the next release.
