### ISSUE TITLE
Preview doesn't load in Desktop Build, problem with decoding audio

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#1322]
## Problem description

Preview in Desktop Build doesn't work (stuck at loading) when project contains m4a audio.
Console shows errors with decoding audio.
Same project works fine in when run in browser version of C3.

## Attach a .c3p
https://www.dropbox.com/s/vr3el95r3jlcv68/audio_bug.c3p?dl=0

## Steps to reproduce

1. Preview the project in Desktop Build.

## Observed result

Preview window stuck at loading.
Console shows errors:
runtime.js:1351 Failed to decode audio 'blob:https://preview.construct.net/3aa50ac3-5b7c-409f-b2ba-341a95f1cf92': EncodingError: Unable to decode audio data
C2AudioBuffer.onDecodeError @ runtime.js:1351
index.html:1 Uncaught (in promise) DOMException: Unable to decode audio data

## Expected result

Working preview.

## Affected browsers

* Desktop Build only.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r85
Language setting: en-US

Local storage
Storage quota (approx): 144 gb
Storage usage (approx): 5.1 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by shortercode** [comment]
The desktop build is based on Chromium. Given that the Chromium project is open source it doesn't support m4a, which is patent encumbered. 

Our recommend audio format is webm opus. It generally has good cross browser support and offers good quality. Additionally the runtime includes a webm opus decoder, so that it works on platforms that don't have native support.

Please refer to @AshleyScirra's last [blog post on Audio](https://www.scirra.com/blog/211/opus-audio-in-construct-3).

**Comment by AshleyScirra** [comment]
It's not a supported audio codec in NW.js but it shouldn't prevent the project loading! Re-opening to investigate.

**Comment by AshleyScirra** [comment]
Looks like the root cause is NW.js falsely indicates support for .m4a and then it fails to decode. Filed here: https://github.com/nwjs/nw.js/issues/6485

**Comment by AshleyScirra** [comment]
Worked around this for the next release, so the project can load, but as noted the format is not supported in NW.js so still won't play.
