### ISSUE TITLE
Errors in Console when using GET Parameters in iframe

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1325]
## Problem description
So i dont know if this is the right place/forum for this, but if i post this in "How do I" i will most probably not get many answers as the issue is a bit complex.

So i have my website where i upload Construct Games. When i upload a new Version of a game, i want it to update (so refresh cashe of my users) so i add ?v=1 then ?v=2 etc. to the iframe src attribute. This results in some Errors in the console (they only pop up if the console is closed at the beginning and then opened - at least that happend in my browser) - see image
(website = https://mirakosgames.com/Games/Pixelgrab/ )

https://imgur.com/a/MHjwE

I havent noticed anything different except these Error messages - so i dont know if they are really doing something, so i wanted to ask - is it a bad idea to add ?something=othervalue for construct games? or does it not matter?

It seems the errors are only there on Chrome, i didnt notice them on Firefox.

**Comment by AshleyScirra** [comment]
You shouldn't change the URL for versioning like that, Construct handles updates automatically: https://www.construct.net/tutorials/offline-games-in-construct-3-8

Since this is not recommended and the error does not appear to have any consequence, closing.
