### ISSUE TITLE
Develop plugin with external-script, can't locate external scripts in preview

### ISSUE THREAD

**Issue by EntityB** [Scirra/Construct-3-bugs#1329]
## Problem description

Hey Ash,
I hit a minor problem when I was developing a plugin with external-script (https://www.construct.net/kz/make-games/manuals/addon-sdk/reference/specifying-dependencies), external script works fine but during development (using "add dev addon") you can't preview project in any mode. 

## Attach a .c3p

none

## Steps to reproduce

1. create new plugin from template, use single global plugin
2. add following code to plugin.js file:

			this._info.AddFileDependency({
				filename: "myfile.js",
				type: "external-script"
			});

3. create file `myfile.js`, add some code `console.log("It is working")
4. run server (https://localhost:8080/addon.json)
5. open C3, addon manager, add dev plugin, restart C3
6. create new project (game from template vertical shooter demo), test preview, works
7. add new object to this project, choose MyCustomPlugin
8. test any preview, error

## Observed result

On opening game in C3 is box with alert, following message:

**Message: Uncaught Error: missing addon file 'myfile.js'**. I also tried to specify path relative, like with "./myfile.js", didn't help. If you fix it, could you also provide more specific details in doc where files should be located? Root? c2runtime folder?

If I pack plugin and install it normaly and not as a dev plugin, it works. But I need it for dev purposes to work ofc.

## Affected browsers

* Chrome: yes
* Firefox: didnt test
* Edge: didnt test
* Safari: didnt test

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r85/main.js, line 63, col 475242
Message: Uncaught Error: missing addon file 'myfile.js'
Stack: Error: missing addon file 'myfile.js' at window.ǃnLT.ǃnLu (https://editor.construct.net/r85/main.js:63:475248) at window.ǃBIP.ǃBIS (https://editor.construct.net/r85/main.js:63:500344) at window.ǃBDt.ǃBId (https://editor.construct.net/r85/exporters/preview/exporter.js:1:24884) at window.ǃBDt.ǃBDY (https://editor.construct.net/r85/exporters/preview/exporter.js:1:24012) at window.ǃBrg.ǃBDJ.ǃBrD (https://editor.construct.net/r85/exporters/preview/exporter.js:1:21896) at window.ǃBrg.ǃBrv (https://editor.construct.net/r85/exporters/preview/exporter.js:1:3015) at window.ǃBrg.ǃBrc (https://editor.construct.net/r85/exporters/preview/exporter.js:1:3252) at MessagePort.messageport-received.n.ǃBr_.onmessage (https://editor.construct.net/r85/exporters/preview/exporter.js:1:2462)
Construct 3 version: r85
URL: https://editor.construct.net/index.html
Date: Tue Feb 27 2018 17:49:18 GMT+0100 (Střední Evropa (běžný čas))
Uptime: 30.6 s

Platform information
Browser: Chrome
Browser version: 64.0.3282.167
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
C3 release: r85
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 515 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Please provide the addon you are using so we can reproduce this.

**Comment by EntityB** [comment]
Ok here you go:
https://drive.google.com/open?id=1FNQBYG6w6NtanB0q8Bv0c58yziBx86fd

It is literaly what I just said, I downloaded template, added 1 file and changed those 3 lines of code. Thats it.

**Comment by AshleyScirra** [comment]
Thanks. Very often people forget to mention a step and then we can't reproduce it so I always ask up-front to be sure.

**Comment by EntityB** [comment]
Haha I know what are you talking about! Good point.

**Comment by AshleyScirra** [comment]
You didn't add the file to the `"file-list"` property in addon.json, which is required for developer mode addons. So the error message is correct: it can't find the file because you didn't tell it that it existed. I've updated the [specifying dependencies](https://www.construct.net/make-games/manuals/addon-sdk/reference/specifying-dependencies) documentation to include a note about this.
