### ISSUE TITLE
[r23] Dock indicators flicker in top-left when UI animations disabled

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#133]
## Problem description

Not a critical bug but a visual one. It looks like a misplacement of these square indicators after mouse release from dragging and dropping a window bar such as Project bar or Tilemap bar. Indicator just flashes on the top left when released. Again, not really obvious but cleaning that up could make the process look more professional and solid/rigid feeling.

## Observed result

Small glitch of the blue docking point indicator flashing at top left each time the mouse releases from dragging and dropping a window bar.

## Expected result

No flash on the top left.

[EDIT]: The flash was a mention that the indicator appeared in a frame after you release the mouse from dragging bars.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Can't see anything wrong in Chrome stable or canary here.

**Comment by jaydonteh** [comment]
Here is a screenshot of the indicator appearing and captured in a flash:

![alt text](http://i.imgur.com/p691FBp.png "Indicator appearing on top left corner.")

**Comment by jaydonteh** [comment]
I think I know what's the specific cause of the problem now. I toggled off the "Enable UI animations" and so this visual glitch appears.

**Comment by AshleyScirra** [comment]
Ah yes, I can see it happening if you turn off UI animations. Thanks for spotting that.

**Comment by AshleyScirra** [comment]
Should be fixed in r24.
