### ISSUE TITLE
Saving to PC in Desktop Version.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1330]
## Problem description

When you save to PC in the desktop version, it shows the process and locks the editor until it saved. It should be like the cloud save, hides the process and doesn't lock the editor.

**Comment by AshleyScirra** [comment]
Are you saving as a single file or as a project? How long is it taking? I'd expect folder saves to be very quick, even with large projects.

**Comment by bilgekaan** [comment]
I'm saving as a single file. It takes ~0.7 seconds for a small project. Quick but still annoying when you save a lot. So if it's possible, it would be better to hide it. (Saving as a folder is much faster but still flashing.)

**Comment by AshleyScirra** [comment]
That's... pretty quick, no? It's within the 1 second response time threshold that research has shown as maintaining an uninterrupted flow of thought ([url=https://www.nngroup.com/articles/response-times-3-important-limits/]ref[/url]).

There are three general stages to saving a single-file c3p:

1. Reading the project data
2. Writing the zip
3. Writing file to disk

The first stage can't be made parallel - it has to lock the UI and show the progress dialog, so you can't make any changes while reading project data for the save. The next two can be put in the background (step 3 is "upload to cloud" for cloud save, and AFAIK is the only part we made happen in the background.) However if it's step 1 that is taking 0.7 seconds, we can't hide that in the background.

**Comment by AshleyScirra** [comment]
We're extremely busy, I haven't seen any other reports of this, 1 second seems pretty fast, and folder projects should save faster, so closing as won't fix. We can investigate later if there is evidence of a wider problem.
