### ISSUE TITLE
Googleplay And MobileAdvert Plugins together cause Build Fail

### ISSUE THREAD

**Issue by jagoman85** [Scirra/Construct-3-bugs#1331]
## Problem description

Related to #452 

**Using r88.2**
If you have a project that consists of both the [new] GooglePlay and MobileAdvert Plugins, exporting to Android (Unsigned or Debug APK), causes a Build Error.

## Attach a .c3p

[googleplayAndMovileAdvert.zip](https://github.com/Scirra/Construct-3-bugs/files/1767175/googleplayAndMovileAdvert.zip)

## Steps to reproduce

1. Create a new project. Using r88.2
2. Add The GooglePlay Plugin
3. Add The MobileAdvert Plugin
4. Add ID details to the Properties of both Plugins
5. Export to Android (Cordova), as an Unsigned release APK or Debug APK
6. You will get a Build Fail

## Observed result

Build Fail occurs when BOTH Plugins are included.
Having one or the other in the project does not cause an issue.

## Expected result

Build should not fail if both plugins are present

**Comment by masscube** [comment]
It works when you export the project as cordova project and add the code to config.xml file, before you compile it, with adobe phonegab build or anything other:

`<preference name="phonegap-version" value="cli-8.0.0" />`

**Comment by jagoman85** [comment]
Thanks, but rather wait for the fix than having to do that each time. Seems simple enough though :)

**Comment by jagoman85** [comment]
The MobileAdvert plugin was updated in r90 but the issue is still present.

**Comment by jagoman85** [comment]
Is it possible to get this fix in for r93? Thanks

**Comment by shortercode** [comment]
I've just published a new version of the plugin, which should solve the problem. The build server will use the new version so you should be able to use it on r92 now.
