### ISSUE TITLE
Construct's (Desktop Build) window size / position Not Saved + Maximize option missing

### ISSUE THREAD

**Issue by AlonDan** [Scirra/Construct-3-bugs#1332]
## Problem description
When opening Construct 3 Desktop Build (tested on latest Beta and Stable releases)
The side tabs Properties and Project get squeezed to the sides, need to re-stretch manually for a better view of the text.

*Enter a concise description of your problem here*
The priority of this general issue should be solved before adding extra features because it is the core of what us, all users handle a lot and must be comfortable to work with.

## Steps to reproduce

1. Make Construct **remember last size / position of the main window**, maximize or not, etc..
2. Make the panels inside Construct **remember their width, height**, same for inside-panels, New / Edit Event window's  size and position as well since they're always centered to the middle.
3. Add **Maximize window** option to **Animation Editor Window**, Events or any panel if possible and let Construct remember the last position / size / screen.
4. Add **Workspaces** option to save presets so users can use "Factory Default" window sizes, or manage their own, place other panels on other screens and make their own presets for PC, Workstation, Laptop, etc.. 

## Expected result
It may take time to accomplish all the above, but again at least the basic of Remembering last position and size of windows is a great start.
Second priority is the workspace option to make Construct UI more dynamic on the windows area.

*What did you expect to happen instead?*
I did expect that Construct will "remember" my latest window size, maximized on the specific screen I closed it.  also the side panels to stay on the exact same place when I open Construct again instead stretching to the sides.

## Affected browsers
This issue tested on to the Desktop Builds.

## System details
Windows 10 64bit
Intel Core i7-4770K CPU 3.50 GHz
SSD
32GB RAM
GeForce GTX 980

* Sorry about my bad English, I hope this info helps.

**Comment by AshleyScirra** [comment]
I'd class anything not remembering its state as a bug, but for enhancements like adding a maximize button to the animations editor, please use the feature request system instead: https://construct3.ideas.aha.io/
Also note there's a 'Reset bars & dialogs' button already in Settings.

@shortercode did your changes for the desktop build already cover the remembering size/position things?

**Comment by shortercode** [comment]
The change I committed yesterday should cover the main window position, size and maximization state on desktop. Although I expect some edge cases will come up at some point. It's due in the r89 release.

**Comment by shortercode** [comment]
The items listed under "step 2" have layout persistence disabled I believe?

**Comment by AshleyScirra** [comment]
@shortercode - not sure what you mean - users can't disable layout persistence can they?

**Comment by shortercode** [comment]
They can't no. I was talking about the flag for dialogs that specifies they shouldn't persist, it's used for the std dialogs

**Comment by AshleyScirra** [comment]
I'm not sure if they mean panes, dialogs or both. Either way, all but the standard ones should automatically remember their positions

**Comment by AshleyScirra** [comment]
1. Should be fixed in next build
2. All panes and dialogs should already remember their position. If they don't it's a separate issue so please file a separate report. (In general please don't report more than one issue per bug - it's confusing and makes it difficult to assign, update status etc.)
3. Feature request for https://construct3.ideas.aha.io/
4. Also a feature request, but there's also already a reset button in settings.

So, closing this report.
