### ISSUE TITLE
Cordova Export Black Screen on iOS when using Cocoon.io

### ISSUE THREAD

**Issue by jtate5** [Scirra/Construct-3-bugs#1333]
## Problem description
Get black screen on iOS when using Cocoon.io 

NOTE: Also reported this to Cocoon dev team here:

https://forums.cocoon.io/t/black-screen-on-ios-construct-3-project/7144

## Attach a .c3p

Link to c3p: http://goo.gl/6KcuUe

This is just a blank template with hello world text.

## Steps to reproduce

1. Export as Cordova iOS
2. Zip contents of www folder for Cocoon.io
3. Upload to Cocoon.io and make iOS build
4.  install iOS build to device (iOS 11)

## Observed result

iOS build has only a black screen after Cocoon splash screen (no matter the view engine)

Log error: 

JavaScript Exception (Line: 10889 Tag: ‘timer’): TypeError: undefined is not an object (evaluating ‘window[“cordova”][“file”][“applicationDirectory”]’)

## Expected result

Should see hello world app

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

iPhone 7, iOS 11.2.5

**Comment by AshleyScirra** [comment]
Does it work OK using C3's build service, or another build service like the Cordova CLI or Phonegap Build? If so this would suggest it's a Cocoon bug and up to them to fix.

**Comment by AshleyScirra** [comment]
Also, looking at the error message it looks like it's not including cordova-plugin-file, which is required for the runtime to work. It's always specified in config.xml so maybe Cocoon isn't reading that file.

**Comment by jtate5** [comment]
I was able to build to iOS just fine with no issues by exporting an Xcode project from Construct 3.  Also, Cocoon worked just fine on Android.  Only iOS is an issue.

**Comment by AshleyScirra** [comment]
OK, closing as it appears to be a Cocoon.io bug, please follow it up with them.
