### ISSUE TITLE
Exporting to Android Failed on Large Project when Changin Android ID/Desc/Version

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-3-bugs#1334]
## Problem description

I have a very large project and I noticed that recently if I change the version, ID or description in the "About" section of the project construct generates a fake error, can be any error even the last error that poped up, and this error won't let you export your project and if saved the file will be corrupted forever and you will no longer be able to export it to Android.

IMPORTANT. This only happens in this project, I haven't been able to reproduce it with a brand new project, so I guess some flags or something si broken in the C3P.

## Attach a  @.c3p

Attached project was renamed to ZIP, name it back to C3P to test.

[AndroidExportError.zip](https://github.com/Scirra/Construct-3-bugs/files/1769126/AndroidExportError.zip)

## Steps to reproduce

1. Open project attached
2. Try to export to android as a debug APK, at first it should work perfectly
3. Go back to construct and change the version of the project at the "About" section.
4. Export to android again, immediately an error should popup indicating that your app ID has not been set although it is set, no further navigation to the Android settings screen nor popup with project options (compression, minify, deduplicate).
5. Repeat steps changing any field in the "About" section.

## Observed result

Project won't export and if file is saved it will get corrupted and you will never be able to export to Android again.
![image](https://user-images.githubusercontent.com/10860045/36817396-a78ee23a-1ca6-11e8-8dc3-92915f8b9910.png)

## Expected result

Project should export and must not be corrupted.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r85
Language setting: en-US

Local storage
Storage quota (approx): 60 gb
Storage usage (approx): 1.4 gb (2.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
> Go back to construct and change the version of the project at the "About" section.

What are you changing it to?

If you're deleting it, then the error message is correct: it also mentions the need for a description and a version.

**Comment by sotano42** [comment]
You can change it to anything it doesn't matter, I changed 1.0.0.98 to 1.0.0.98A, then tried ton ut a 1 and tested with any character. The description is also already there as in the screenshot, basically all data needed is there already since I had exported the project before.

**Comment by AshleyScirra** [comment]
1.0.0.98A is not a valid version AFAIK - I think it requires numbers only. If you use 1.0.0.99, does it work?That message appears if any field is invalid. Maybe we just need to change the text on the message to make it clearer.

**Comment by sotano42** [comment]
I see now. It works with only numbers separated by period marks. Yeah, you should change that to be more descriptive. I've been exporting the project over and over to HTML and a few tests for Android, for HTML no warning or anything regarding the version number was shown so therefore I assumed it was a valid number. 1.0.0.99 worked fine, just wanted to have a "branch" for bug fixing of a production version.

I guess this solves it. Thank you.

**Comment by shortercode** [comment]
Hey @sotano42 the requirement is only for mobile exports, which is why you only just hit this. The bundle ID and version have to be something that the app/play store understand, hence the limitation. I think we've had people confused by this before, so perhaps the message needs rewording. 

I'd advise not using version values over 99. The reason is a little awkward but I shall try to explain. 

When publishing to the play store they require 2 version values; `version` and `versionCode`. `version` is basically just a label and is only used to display to the user, `versionCode` is an integer which is used to decide if a build is newer or older. We generate the `versionCode` from the version ( `MAJOR.MINOR.PATCH.BUILD` )  using this sum:
```javascript
MAJOR * 1000000 + MINOR * 10000 + PATCH * 100 + BUILD
```

If you have a value higher than 99 in any of these it will start to overlap with the next value, which could cause issues when publishing. For example:

```javascript
"1.0.0.199" = 1000199 
"1.0.1.55" = 1000155 
```

The second version number is higher than previous, but because of the lower versionCode the store will think it's older.

**Comment by AshleyScirra** [comment]
I've added a separate error message for invalid versions to help avoid confusion in future.

**Comment by sotano42** [comment]
@AshleyScirra Thanks, and just one comment not related to this thread. I noticed that after several hours of working in construct and playtesting it crashes by running out of memory (possible memory leak?) don't know, I have no evidence it just happens every 4-6 hours of working, I have no particular steps to reproduce it but it crashes every day, you may want to take a further look to it. I use Chrome and Windows 10 to work, if I'm able to determine the steps to reproduce it will open a new issue.

@shortercode Good to know that, I'm new at android developing. Thanks.

**Comment by AshleyScirra** [comment]
The memory leak might be #1338.
