### ISSUE TITLE
Can't set Global variable with subevents.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1335]
## Problem description

I created a simple test project. I have a global variable that I want to set on key press. I can't seem to set the value if it's set in a subevent. I don't know what to make of this. Should be pretty straight forward. Subevents are checking the global value, and setting it depending on the current value, to cycle through the 0, 1, 2. 

## Attach a .c3p

https://www.dropbox.com/s/18pv3sgutgo2lym/global_fail.c3p?dl=1

## Steps to reproduce

1. Open attached project and run it.
2. press space to set the global value.
3. Nothing happens.

## Observed result

Can't set the global value. 

## Expected result

Should be able to set the global value.

## Affected browsers

* Chrome: yes

**Comment by tunepunk** [comment]
Seems like it's going through all sub events one by one. So setting it first to 2, then 3, then back to 1 every time i hit space. So it's probably not a bug, and more of logic fail in my example. :p  Case closed.

**Comment by AshleyScirra** [comment]
Yep, events run one at a time so all three subevents end up running. This is a case where "Else" is useful.
