### ISSUE TITLE
Browser crash/freeze while folder dragged over object

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1336]
## Problem description

Browser crashes/freezes while i accidentally drag folder over objects like sprite, 9patch.....

## Attach a .c3p

none

## Steps to reproduce

1. Create new project
2. Create sprite or 9patch
3. Create folder under Object types
4. Try to drag Folder over sprite or 9patch

## Observed result

Browser freeze instantly while folder is dragged over sprite or 9patch.

## Expected result

Folders can be dragger into other folders, but while under folders there are still objects, a small mistake with folder dragging results browser crash.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.
