### ISSUE TITLE
Debug-APK: The connection to the server was unsuccessful

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#1337]
## Problem description

I have a empty new project. When I build a debug-apk-file (and copy them to my smartphone), I always get this error message on my phone ( Samsung Galaxy S7 / Android 7.0 ):

> **The connection to the server was unsuccessful.**

## Attach a .c3p

[Download the Project-File](https://massive-cube.com/files-public/test_bug.c3p)

## Steps to reproduce

1. Create a new empty project file
2. Export the project as android-debug-apk file
3. Copy the apk file to my smartphone
4. Install the apk file
5. Get the error

## Observed result

[Show Error-Image](https://massive-cube.com/files-public/Screenshot_20180301-211649.png)

## Expected result

No error-message.

## Affected browsers

Only the APK-File

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r85
Language setting: en-US

Local storage
Storage quota (approx): 8.8 gb
Storage usage (approx): 38 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
We've seen this issue before, and it's pretty tricky to get a hold on. Certainly I've never been able to replicate it but I believe it's more common to Samsung devices. I tried this quickly on our S8 without any issues. 

Does this happen instantly, or does it take a little while for the error to appear? What android version do you select during the build? Any other settings you use during the build?

**Comment by AshleyScirra** [comment]
Also do you have any security/antivirus apps on the device? It might be some added security feature that is blocking the app loading.

**Comment by masscube** [comment]
Now, i have test something, but nothing works..

First, i tested it on my galaxy S7 with Android 7.0.

**Step by Step Screenshots for the Export-Settings:**

[Step 1](https://massive-cube.com/files-public/screenshots/problemshots/construct3/1.jpg)
Select the Android Export (Cordova).

[Step 2](https://massive-cube.com/files-public/screenshots/problemshots/construct3/2.jpg)
I tested it with and without checked minify script-option.

[Step 3](https://massive-cube.com/files-public/screenshots/problemshots/construct3/2.jpg)
I'm tested it with Android 5 Export, and with Android 7 Export. (Debug APK)

Then, i'm uploading the file to my smartphone, install it, and get error again.

With my other Smartphone Galaxy Note 3 (Android 5) the error-message is the same...


@AshleyScirra There is no a antivirus app or anything. The Note 3 has a completely new installation..

@shortercode 

> Does this happen instantly, or does it take a little while for the error to appear?
It takes a few seconds for the error to appear.

> What android version do you select during the build?
Android 5.0 or Android 7.0

> Any other settings you use during the build?
See the screenshots above :)


Here my exported APK-Files (Android 5):
[Download Android 5 APK-File with script minify](http://massive-cube.com/files-public/test.android.debug-Android5.apk)

[Download Android 5 APK-File without script minify](http://massive-cube.com/files-public/test.android.debug-Android5_without-minify.apk)

**Comment by AshleyScirra** [comment]
The error appears to come from cordova-android: https://github.com/apache/cordova-android/blob/59018ab632e99b3e45a0bf9657c70282aeeac7bf/framework/src/org/apache/cordova/CordovaWebViewImpl.java#L159

It looks like it only happens if the webview times out loading a URL. The default timeout looks like 20 seconds. It ought to be loading a local file so it should be more or less instant. I would guess that something has actually failed but cordova doesn't handle the error properly and ends up hitting a timeout. Maybe USB debugging is the best next step... @shortercode did you have an explanation from another report you could link to?

**Comment by shortercode** [comment]
Yeah I never came up with an answer in the past, the suggested fixes are either load a dummy page that redirects to the main page or increase the timeout to silly values ( 700000ms / ~ 12 minutes  seems to be suggested a lot ).

I probably have instructions for loading the chrome debugger somewhere, I'll take a look.

**Comment by AshleyScirra** [comment]
Increasing the timeout seems to be the de facto solution but I've also seen reports that this helps (no explanation why though):

```
<allow-navigation href="*" />
<content src=“index.html” />
<content original-src=“index.html” />
```

**Comment by masscube** [comment]
@AshleyScirra how can i test it? :)

**Comment by shortercode** [comment]
@masscube If you know how you can try exporting as a cordova project and adding those values to the config.xml

I couldn't find any instructions I'd written for debugging chrome on Android, I'm working on writing a guide for it at the moment. I'd been meaning to publish one anyway.

**Comment by masscube** [comment]
Okay, i have tested it again. It works only with the time-hack:
_<preference name="loadUrlTimeoutValue" value="700000" />_

.... but the app loads very long before i see anything. Its not a good solution.

And a other interessting fact: When i export my project as a html5-website, and upload them to my webspace, i have a long loading time too. The project is empty, has no sprites or anything...

**Comment by masscube** [comment]
Today, i'm exported the same project with construct 2, and this works without any problems!? The problem is only on construct 3.

**Comment by masscube** [comment]
My friend tested the construct 3 export on a Huawei-Smartphone too... don't work (the same problem).

**Comment by shortercode** [comment]
Hmm that's interesting, maybe it will improve when we move to the newest cordova version. But I'm not going to hold up too much hope.

When you exported from construct 2 whats steps did you use?

**Comment by masscube** [comment]
Steps in Construct 2:

- Export to Cordova
**- ( uncheck minifiy script )
- Minimum Supported OS to 5.0 [Webview]
- Hide Statusbar is checked
- Use WKWebView on iOS is checked
- Export Project**
- Upload the zip-Folder to https://build.phonegap.com/
- Compile to APK
- Upload to my smartphone
- Done! Works perfectly

**Comment by masscube** [comment]
I have found a crazy solution for the problem...

When i export the project as debug-apk on my pc, then doesnt work the example-game on my android smartphone (same error as above) ... but when i export the project directly on my samsung galaxy s7 smartphone - then its works! I don't know why?!

**Comment by shortercode** [comment]
well... that does sound like a very strange workaround!

A fair few things have changed in the past few months, do you still have issues loading games on certain devices?

**Comment by shortercode** [comment]
Okay as last I heard it was working, and I haven't got a message back I'm going to close this issue. If anyone is having this same problem can you please create a new bug report.

**Comment by Mathiasfx** [comment]
I have exactly the same problem, I tried to spend it on an android studio project and I do not get up. I get the black screen, did not find the solution of the build of c3?
