### ISSUE TITLE
Jump thru behaviour collision offset

### ISSUE THREAD

**Issue by Lobo93** [Scirra/Construct-3-bugs#1339]
## Problem description

Sometimes, when an object with the Platform behavior lands on the side of an object with the jump-thru behavior, the platform object is moved a few pixels to the top and lands above the jump-thru object, as if the jump-thru behavior had some kind of offset for triggering its "solid" state.

## Attach a .c3p

[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/1776245/New.project.zip)
(I made an example .c3p with a platform object automatically jumping at the exact spot for triggering this bug)

## Steps to reproduce

1. Open a new project
2. Create an object with the platform behavior
3. Create an object with the Jump thru behavior
4. Using the platform object, jump onto the edge of the jump thru object, but not reaching it by a few pixels

## Observed result

The platform object moves upwards, forcing it to reach the jump thru object.

## Expected result

Since the platform didn't reach the jump-thru object, it should fall instead of landing above it.

## Affected browsers

* Chrome: yes
* Firefox: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r85
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 293 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The player and the ground both have a 1px transparent border around the image and the collision polygon includes this. The objects are actually exactly aligned but you're seeing the area of transparency. If you crop it away it looks correct.

**Comment by Lobo93** [comment]
Ah I see
I understand this might be a fix for another problem, but it becomes very noticeable in retro-looking games, with sprites of 8x8 or 16x16 pixels, so I'll have to find a workaround for this :(
It would be nice to have an option to toggle this on or off.

Thanks for the fast answer btw!
