### ISSUE TITLE
APK Build fails when only icon-16 is present

### ISSUE THREAD

**Issue by SoftDevApp** [Scirra/Construct-3-bugs#1341]
## Problem description
"Build Failed. to build project"  for Android APKs, debug APK or unsighned Release APK
*Enter a concise description of your problem here*
"Build Failed. to build project"  for Android APKs, debug APK or unsighned Release APK on any project.
## Attach a .c3p
[Uploading testapk.c3p…]()
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.Menu
2.project
3.export
4.Android Cordova
5.next
6.android build (Cordova build: Debug APK) or select (Cordova build: unsigned release APK)

## Observed result
                Construct 3
Build failed. failed to build project
                    [OK]         
*What do you see happen?*
Construct 3 attempts to build APK then
               Construct 3
Build failed. failed to build project
                    [OK]  
## Expected result
a Debug APK to test or a unsigned release APK to publish
*What did you expect to happen instead?*
To be able to build APK to test or publish an APK file from a downloaded version of construct 3 on my desktop computer
## Affected browsers

* Chrome: built Debug APK, built unsigned release APK
* Firefox: built Debug APK
* Edge: connected to server and did not continue
* Safari: no (not installed)

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE
Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r85
Language setting: en-US

Local storage
Storage quota (approx): 26 gb
Storage usage (approx): 76 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 950 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by shortercode** [comment]
Your example project never completed it's upload, can you please provide it? I validated that the server was working with the ghost shooter project, so it's likely an issue related to a specific plugin your using.

**Comment by shortercode** [comment]
@cb85 can you try building ghost shooter for me, and see if that works? That's what we normally test with for basic functionality. It seems to work correctly for me in r85 and r88.3.

It is possible the issue is related to a built in plugin, but I still need to know which one.

If ghost shooter works correctly for you can you please create a minimal project that doesn't work and upload it here so I can test it?

**Comment by cb85** [comment]
Ghost shooter worked fine, and then my test project worked fine. I cant seem to make one where it doesn't work except for my actual game. I added the same plugins to a test and it worked. but still my normal game keeps saying build failed

**Comment by SoftDevApp** [comment]
Hi,


Today when I opened Construct 3 (r85) on my desktop (downloaded version) an update window popped up.  Construct 3 update to r89 and then tried building ghost shooter debug APK and unassigned APK for android and it worked.  Starting to building other projects to test the APK builder.


Thank you!

Matthew Trout

SOFEVAP, LLC

________________________________

**Comment by cb85** [comment]
It's still not working, the only two projects failing to export are both imported construct 2 apps. So that must be the issue. Every new project I make to test it exports fine. It's only my two imported ones that don't export anymore. They used to before though because I tried testing them many times

**Comment by cb85** [comment]
@shortercode No plugins seem to be the problem. I've also deleted nearly all things on it and it still doesn't build. its like its been corrupted somehow. it was working all before some latest updates. all i added since was keyboard function. I can't recreate a broken one either. only my main game is still broken. I was finished too and about to export to the store but now I can't

**Comment by shortercode** [comment]
@cb85 I tried importing a capx and building it, all seemed fine.

Could you send me one of these cut down version of your project that aren't building for me to try? If you prefer you can send it privately to my email iain@scirra.com.

Sometime soon I'm intending to enable proper build reports from the server, which will hopefully make this sort of thing easier to diagnose.

**Comment by cb85** [comment]
Thanks I sent it to your E-mail

**Comment by shortercode** [comment]
Thanks, I've got it. I gave it a go on my phone and I can confirm that I
can't build it. I couldn't see anything obviously wrong. I'm out of office
at the moment, but if I have time while I'm traveling I'll try to get a
build log from the server.

**Comment by shortercode** [comment]
Okay cb85 so I've found the issue, although I don't quite understand it yet. If your project only has an icon-16 it will fail to build. If you include all the icon sizes the default project has then it will build correctly. Also the icons should match the size the name implies, so icon-16.png should be 16x16 pixels in size.

**Comment by cb85** [comment]
Ahhh thanks its working now! I deleted the other icons by mistake awhile ago. Definitely working now, Thanks

**Comment by shortercode** [comment]
Glad to hear @cb85 I'll keep this open for now, with the hope that we can improve the error a bit.

**Comment by shortercode** [comment]
I've added some better checks on the build service to prevent mislabeled icons, so this shouldn't be a problem anymore.

**Comment by SoftDevApp** [comment]
Error report information
Type: unhandled rejection
Reason: Error: The source image could not be decoded.
Construct 3 version: r182.4
URL: https://editor.construct.net/
Date: Sun Feb 23 2020 15:37:32 GMT-0500 (Eastern Standard Time)
Uptime: 4.4 s

Platform information
Browser: NW.js
Browser version: 0.44.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.0 (like Chrome/80.0.3987.87)
C3 release: r182.4 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

**Comment by AshleyScirra** [comment]
Please note we cannot help you unless you file a new bug report following all the guidelines. There is also no evidence that the report you pasted here has anything at all to do with the original issue.
