### ISSUE TITLE
Random crash at export, no repro

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1344]
## Problem description

I was using remote preview, pressed F5 to refresh 2 of the tabs I was testing in and then realized i didn't build the project for any update to take place. Alt tabbed to the project, pressed F4 while the tabs didn't fully load, and crash.

Couldn't trigger it afterwards, maybe I wasn't fast enough or something. Hopefully the crash report will give you an idea or two.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot convert undefined or null to object @ TypeError: Cannot convert undefined or null to object at Function.entries () at e (https://editor.construct.net/r85/exporters/preview/exporter.js:1:9973) at window.ǃBOb.ǃBGJ (https://editor.construct.net/r85/exporters/preview/exporter.js:1:15999) at window.ǃBGj.ǃBDX (https://editor.construct.net/r85/exporters/preview/exporter.js:1:18979) at 
Stack: TypeError: Cannot convert undefined or null to object at Function.entries () at e (https://editor.construct.net/r85/exporters/preview/exporter.js:1:9973) at window.ǃBOb.ǃBGJ (https://editor.construct.net/r85/exporters/preview/exporter.js:1:15999) at window.ǃBGj.ǃBDX (https://editor.construct.net/r85/exporters/preview/exporter.js:1:18979) at 
Construct 3 version: r85
URL: https://editor.construct.net/index.html
Date: Mon Mar 05 2018 21:34:48 GMT+0200 (GTB Standard Time)
Uptime: 27409.2 s

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r85
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Well, you're still on r85, and we've fixed a ton of bugs since then including one that looks similar to this one, so I'd guess we've already fixed it.

**Comment by JeFawk** [comment]
Yes, I will most likely submit bugs that are on stable releases from now on.
