### ISSUE TITLE
Sprites getting damaged with weird pixels after importing them. C3 r85

### ISSUE THREAD

**Issue by Gatostao** [Scirra/Construct-3-bugs#1345]
## Problem description

After importing a png 28 image to the c3 project either by drag and dropping or by file choosing, you can see a weird edge in the frame thumbnail, even if the image looks good on the editor. After you close the image editor you can see this dammage in the c3 editor. Some weird colored pixels appear on the image all over the edge. This makes the sprite looks awfull and ruff. If you open the image editor again you can see how the image has changed and how now this new colored pixels all around. Reimporting the imgage or replace it doens't fix the problem. (It doesn't appear to happen with all colors but with most of them.)

You can see examples here:

![c3image editor bugd](https://user-images.githubusercontent.com/26916041/37001754-8f9f1544-2095-11e8-83ed-1e85c62f7518.PNG)
![c3image editor bug](https://user-images.githubusercontent.com/26916041/37001109-7631c888-2093-11e8-84c7-82f4d3406b82.PNG)
![c3image editor bugb](https://user-images.githubusercontent.com/26916041/37001117-79560f1a-2093-11e8-8998-48ef873bb435.PNG)
![c3image editor bugc](https://user-images.githubusercontent.com/26916041/37001121-7d24ca3c-2093-11e8-8278-6e293e1cd0bd.PNG)

This is how they should look:

![bugproof](https://user-images.githubusercontent.com/26916041/37001710-62fb9c4c-2095-11e8-81aa-a895cffd439a.png)

## Attach a .c3p

https://drive.google.com/file/d/1TdAOwD3VRKWOHEf5rPA4SUr5qu_lCM8x/view?usp=sharing

## Steps to reproduce

1. Create new project
2. Insert a Sprite object
3. Select a png28 file
4. Close the image editor.

## Observed result

Images are damaged and affected by the editor showing undesidered colored pixels on the edges.

## Expected result

I expect that c3 keeps the image fidelity of any png sprite as c2 does, not changing any pixel beyond optimization.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: Doesn't support remote preview
* Safari: 
* Opera: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r85
Language setting: en-US

Local storage
Storage quota (approx): 38 gb
Storage usage (approx): 188 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 760 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8

</details>

**Comment by AshleyScirra** [comment]
Can you share the original images so we can try importing them ourselves?

**Comment by Gatostao** [comment]
Hi Ashley, of course I can.

Here is a Gdrive folder where you can get them:

https://drive.google.com/drive/folders/1cg5ejSA7KaXst-DzYchsY4gjmOnhtvt_?usp=sharing

![enemyring](https://user-images.githubusercontent.com/26916041/37053398-093657d2-214a-11e8-812f-6d34853a20e5.png)
![enemypad](https://user-images.githubusercontent.com/26916041/37053402-0c5ff166-214a-11e8-81ad-83d60cd30119.png)
![enemypadb](https://user-images.githubusercontent.com/26916041/37053404-0ea1e33a-214a-11e8-9495-f920423bf6b0.png)
![logoword](https://user-images.githubusercontent.com/26916041/37053408-111ef6de-214a-11e8-82fa-3e34e3972bf1.png)

Let me know if you need anything else.

**Comment by vpick001** [comment]
**_I can start a new thread for this if you like, but it seems to be stemming from the same issue._**

I am getting the same issue as well on semi-transparent parts of images.  They look OK in the image editor, but when running the game they get odd black pixelization.  

This occurs on the Desktop version as well as Chrome.  The sprites operate normally in C2, but when importing the project into C3 I get the issue.

I've attached the original image, and an example of how it looks in the game (notice the outline is black instead of white and semi-opaque.
![odd_black_pixels](https://user-images.githubusercontent.com/29590430/37065862-a4ab1c86-2157-11e8-8acf-6e3b61b0ebe1.PNG)
![1](https://user-images.githubusercontent.com/29590430/37065878-b321047e-2157-11e8-84fa-02cebd52005d.png)

**Comment by Gatostao** [comment]
Hi again. My intention is not to bump this issue, but to provide more information.

A new form of image corruption has appeared, this time is not outside of the asset but inside. I provide both, bug imge and original asset for you to try.

Bugged image:
![c3image editor buge](https://user-images.githubusercontent.com/26916041/37229366-bc1356c0-23b1-11e8-97ff-095a4d62302d.PNG)
![c3image editor bugf](https://user-images.githubusercontent.com/26916041/37229372-bf651f8e-23b1-11e8-896d-c7e266d96ca0.PNG)

Original asset:
![uibestscore](https://user-images.githubusercontent.com/26916041/37229380-c8489a22-23b1-11e8-9271-1243081eda69.png)

Also I want to point out that I have Hardware acceleration on google chrome enabled, since I know that disabling this option has graphic and performance repercussions for engine and c2 games.

**Comment by Gatostao** [comment]
**New importat information about this Bug.**

The Issue doesn't happen Using Construct 3 editor on Mozilla Firefox.**

![c3image editor buggmozzila](https://user-images.githubusercontent.com/26916041/37236289-1a631400-23d4-11e8-8811-f0270957a9f3.PNG)

**Comment by AshleyScirra** [comment]
I would guess this is something to do with premultiplied alpha somewhere along the graphics pipeline. We do handle it slightly differently in Chrome due to some extra imaging features that are available.

**Comment by tunepunk** [comment]
I might add a thing I found out: 

That this does not happen if you import the file by right clicking the animation editor and choosing "import frames > From files" 

it only happens if you import by using the folder icon at the top of the sprite editor.

**Comment by tunepunk** [comment]
And forgot to mention. It does not have this artifact of you drag&drop a file in to the sprite editor and choosing import from file. So only when you use the import files folder icon.

**Comment by Gatostao** [comment]
@tunepunk @AshleyScirra For me this happens with any method of importing the image in chrome. And it doesn't happen with any method of importing in Firefox. I should add that if I import the files in firefox and then open the project in chrome, it doesn't damage the graphics.

**Comment by AshleyScirra** [comment]
OK, should be fixed in the next release. In Chrome the editor was doing some lossy roundtrips through premultiplied alpha. Avoiding that keeps the quality of the artwork.

**Comment by Gatostao** [comment]
Great! Thanks Ashley
