### ISSUE TITLE
Project not playing... C3

### ISSUE THREAD

**Issue by sergeypisarev85** [Scirra/Construct-3-bugs#1346]
## Problem description
Hello, my project stops from loading, after I add this: 
Buy menu  object -> is Visible -> SetText to -> RegexMatchAt(Array.At(0,0,iz), "\w+", "g", 1)

This Regex works fine In other part of my code.

## Attach a .c3p

https://drive.google.com/open?id=1Zxrl2RMU-7M1kjhJndNbzMG7500LJkEY

## Steps to reproduce

1. Create isVisible
2. Add SetText to it
3. And try to change text to RegexMatchAt(Array.At(0,0,iz), "\w+", "g", 1)

## Observed result

*What do you see happen?*

Project stops playing. Not loading.

## Expected result

*What did you expect to happen instead?*

Running project as always. ;)

## Affected browsers

* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.2_6
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D100 Safari/604.1
C3 release: r88.3 (beta)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
Service Workers are not supported. Construct 3 cannot be used offline in this browser.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.1.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A10X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by AshleyScirra** [comment]
I can preview the project just fine. Can you provide the steps to follow to reproduce the problem? The steps you've provided appear to be what you've done, not what I need to do to see the problem.

**Comment by sergeypisarev85** [comment]
Sorry for long answer. What i’m doing is written here. I just make it IsVisible and I unable to preview my Project. Although it works perfectly with Is on Screen parameter.

**Comment by AshleyScirra** [comment]
I don't understand what "Create isVisible" means. I have no idea what you are creating. A sprite? A variable? And where? Please provide steps for me to observe the problem once I have opened the project, otherwise I cannot investigate this.

**Comment by sergeypisarev85** [comment]
I’m sorry... 
If you will open my project, on the “Event Sheet 1” on the bottom. I’m checking if my sprite is currently Visible or not. First I tried to check if it was Visible with isVisible action. But project stopped from previewing, it’s just a blank screen. So I decided to change it to “is on screen” action. And it worked.

**Comment by AshleyScirra** [comment]
Please provide the project that doesn't work, not the one that does work. We need to investigate the one that isn't working.

**Comment by sergeypisarev85** [comment]
@AshleyScirra I’m totally sorry! I saved fixed project. Right now I made it back. Now it not previewing anymore. Thank you very much!

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.
