### ISSUE TITLE
"Clone Sprite" crashes Construct 3

### ISSUE THREAD

**Issue by grierdill** [Scirra/Construct-3-bugs#1348]
Selecting a sprite and using the "Clone Sprite" action crashes C3 after updating to the newest version:

Error report information
Type: unhandled exception
File: https://editor.construct.net/r89/main.js, line 63, col 216238
Message: Uncaught Error: animation frame has no content
Stack: Error: animation frame has no content at i.ǃruL (https://editor.construct.net/r89/main.js:63:216244) at i.ǃpR (https://editor.construct.net/r89/main.js:63:219227) at i.ǃrwe (https://editor.construct.net/r89/main.js:63:219617) at t.ǃrwo (https://editor.construct.net/r89/main.js:63:179260) at t.ǃLl (https://editor.construct.net/r89/main.js:63:179570) at ǃr.ǃo.ǃnI.t.ǃUlq [as ǃr$x] (https://editor.construct.net/r89/components/bars/projectBar/projectBar.js:1:23452) at ǃr.ǃo.ǃnI.ǃUlw (https://editor.construct.net/r89/main.js:2:428472) at n.ǃUlw (https://editor.construct.net/r89/main.js:2:499008) at n.ǃUlq (https://editor.construct.net/r89/main.js:2:498985) at window.ǃJ$.ǃJ$.ǃU_q (https://editor.construct.net/r89/components/bars/projectBar/projectBar.js:1:23441)
Construct 3 version: r89
URL: https://editor.construct.net/
Date: Wed Mar 07 2018 09:29:18 GMT-0500 (EST)
Uptime: 1015.7 s

Platform information
Browser: Chrome
Browser version: 64.0.3282.167
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon HD - FirePro D500 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
Can't reproduce using Ghost Shooter demo project in r89. Both the Layout View context menu and Project Bar clone options work for sprites. Please always follow the bug report guidelines to ensure we can fix the issue you are reporting.

**Comment by grierdill** [comment]
Sorry, here is my project file: https://drive.google.com/open?id=1MnzWTW350Xu7U52159iQ3G8xoEwr2WFe

When I right click on the "ShapeCircle" sprite in the Project panel, and click "Clone" it crashes.
