### ISSUE TITLE
MovileAdvert Event causes game to freeze

### ISSUE THREAD

**Issue by jagoman85** [Scirra/Construct-3-bugs#1349]
## Problem description

**Using r89 (or any version above r71)**
If you include any MobileAdvert Event to show an advert, such as "Create banner advert". The game freezes when it reaches that event when previewing.

r71 does not have this issue, but versions after this are affected.

When exported as an APK the game does not freeze at the point

## Attach a .c3p

[MobileAdvertFreeze.zip](https://github.com/Scirra/Construct-3-bugs/files/1789577/MobileAdvertFreeze.zip)

## Steps to reproduce

1. Create a project with something that is animated, so you can visually see the game freezing when it does
2. Add the MobileAdvert Plugin
3. Add the MobileAdvert event "Create banner advert"
4. Preview the game and see where it stops

## Observed result

The game freezes as soon as the MobileAdvert event is triggered, when previewing the game.

## Expected result

The game should not freeze (as in r71)

## Affected browsers

* Chrome: yes
* APK: no

**Comment by shortercode** [comment]
Looks like the invalid callback is clogging up the runtime. I've fixed the callbacks so they initialise correctly even when the mobile advert runtime isn't loaded.
