### ISSUE TITLE
Sound only playing with headphones connected

### ISSUE THREAD

**Issue by Vultwo** [Scirra/Construct-3-bugs#1352]
## Problem description

Playing a sound on iPhone 5s iOS version 11.2.6 only works while headphones are connected.

## Attach a .c3p

[Sound Problem.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1792465/Sound.Problem.c3p.zip)

## Steps to reproduce

1. Export
2. Cordova iOS
3. Check deduplicate images and minify script
4. Select xcode project
5. In xcode select development team and run the game

## Observed result

Sound not playing, after inserting headphones it starts playing.

## Expected result

The sound should be playing without headphones connected.

## Affected browsers

* Chrome: no
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

No crash report

</details>

**Comment by AshleyScirra** [comment]
Normally you have to touch the screen before playback works. You may be accidentally touching the screen while putting in headphones which might make you think it's that. Does audio playback work if you just touch the screen without putting headphones in?

**Comment by Vultwo** [comment]
Sorry i have just noticed other games that aren't construct games have the same issue too.
