### ISSUE TITLE
[Desktop v89] Reload from Original Source on Particles Crashes Program

### ISSUE THREAD

**Issue by ElliottBear** [Scirra/Construct-3-bugs#1355]
## Problem description

Clicking reload from original source on a fresh particles object crashes the C3 editor.

## Attach a .c3p

https://drive.google.com/open?id=1A4wR0ZzfM8YTcvEz3LsIrLcZPs3YU-EO

## Steps to reproduce

1. Start new project
2. Add particles object
3. Click "reload from original source"

## Observed result

C3 crashes.

## Expected result

C3 not to crash.

## Affected browsers

N/A

## System details

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r89 (stable)
Language setting: en-US

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r89/main.js, line 63, col 184073
Message: Uncaught Error: object type does not support animations
Stack: Error: object type does not support animations at t.ǃrQv (https://editor.construct.net/r89/main.js:63:184079) at e.ǃTCJ.ǃTos (https://editor.construct.net/r89/main.js:74:205905) at e.ǃTCJ.ǃTbT (https://editor.construct.net/r89/main.js:74:205299) at e.ǃTCJ.ǃTbF (https://editor.construct.net/r89/main.js:74:186168) at e.ǃTCJ.ǃTCE (https://editor.construct.net/r89/main.js:74:185710) at e.ǃTqV.r.ǃTCI (https://editor.construct.net/r89/main.js:74:167214) at e.ǃTqV.r.ǃTCP (https://editor.construct.net/r89/main.js:74:172664) at Array.e.addEventListener (https://editor.construct.net/r89/main.js:74:172463) at ǃr.Event.ǃUPg.ǃUPb (https://editor.construct.net/r89/main.js:2:268854) at ǃr.ǃo.ǃJK.dispatchEvent (https://editor.construct.net/r89/main.js:2:267090)
Construct 3 version: r89
URL: https://editor.construct.net/
Date: Fri Mar 09 2018 14:53:44 GMT+0000 (GMT Standard Time)
Uptime: 19.7 s

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) Iris(TM) Graphics 540 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r91
