### ISSUE TITLE
Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project. R89

### ISSUE THREAD

**Issue by saltandpixel** [Scirra/Construct-3-bugs#1357]
## Problem description

Attempted to open file from dropbox cloud and received this message: _Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project._

- Attempted to open previous version(s) from dropbox history by downloading and dragging into browser and received same message: _Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project._

## Attach a .c3p

https://www.dropbox.com/s/ykj29aprojluems/crush.tv_remastered.c3p?dl=0

## Steps to reproduce

1. Open editor.construct.net
2. Load c3p from dropbox cloud
3.

## Observed result

- Downloads project
- Starts opening project
- Receive this message: Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.

## Expected result

Open project

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.10_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 18 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The attached project uses the following addons:

- Behavior MoveTo (Rex_MoveTo) by Rex.Rainbow
- Effect normalmap extended (normalmapext) by Donelwero and Matriax

Please provide the exact versions of the addons you have installed so we can investigate further.

**Comment by saltandpixel** [comment]
[CRUSH_C3Addons.zip](https://github.com/Scirra/Construct-3-bugs/files/1797753/CRUSH_C3Addons.zip)

**Comment by saltandpixel** [comment]
I wasn't sure how long this was going take to get resolved so I went ahead and remade what was lost, It was mostly graphical anyways. I also remove the link, because I don't want my game's files out in public. But, if you didn't download the c3p, I can email the file if you want to look into this further.

**Comment by AshleyScirra** [comment]
You filed this just before the weekend - it's Monday and I'm ready to look in to this now, but the link to the .c3p now returns a 404. I definitely want to look in to this since any issues preventing projects opening are very serious and we want to make sure other users cannot be affected. Could you provide the project again?

**Comment by saltandpixel** [comment]
​
 crush.tv_remastered (13).c3p
<https://drive.google.com/file/d/1Ot8WPo_mp607IEWsBvICtRPuJDxyJm7G/view?usp=drive_web>
​
Here is the project.

**Comment by AshleyScirra** [comment]
Thanks, based on that I was able to find a missing check when adding objects to a family that could cause duplicated effect names. This should be fixed in the next release so it won't be able to happen again. In the mean time make sure when you add an object to a family, that it doesn't have the same effect name as a family effect.

**Comment by saltandpixel** [comment]
Thank you Ashley
