### ISSUE TITLE
Dark theme: high contrast when selecting a lot of events

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1358]
## Problem description

Whenever I open a group it selects all the events in that group (no idea why...) and the contrast is pretty big. Actually anything selected using the dark theme is extremely bright, especially compared to everything else. The mouse hover over effect is great, the selected one is like 10x more brighter.

I don't see a need in this. Is this intended for the dark theme?

## Attach a .c3p

![image](https://user-images.githubusercontent.com/7268697/37229561-028e4480-23ed-11e8-8814-06c7ef3fb705.png)

## Expected result

I would expect the selected events to be half as bright as they currently are.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 6.1 gb
Storage usage (approx): 2.6 gb (43.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Tokinsom** [comment]
Agreed. Highlighted events, etc. are way too bright in the dark theme. IIRC they turned orange in C2's dark theme. That or a bright grey would be better.

**Comment by JeFawk** [comment]
Any news on this? I still can't really use the dark theme because of this huge contrast. I'd not recommend orange to be honest, but more of a mid gray color (bright gray wont do much either).

The point is to have feedback on what you clicked, and seeing a solar flare in your face is overdoing it quite a lot.

**Comment by JeFawk** [comment]
Well I kinda modify it like this with inspect element but I need to redo it each time I open up C3 with dark theme and takes a bit to find the values.

![image](https://user-images.githubusercontent.com/7268697/40175822-16624ae4-59e2-11e8-9685-0aba295d818a.png)

**Comment by AshleyScirra** [comment]
I don't think @Animmaniac has any plans to change this, and it's arguably subjective anyway, so closing. It might be better to use the suggestions platform for this type of thing.
