### ISSUE TITLE
File context menu unhandled exceptions

### ISSUE THREAD

**Issue by 3dParadox** [Scirra/Construct-3-bugs#136]
unhandled exception (pasted below) when you attempt to use the Array editor, Dictionary editor, or anything in that context menu. It pops up the not available in the demo version, with the exception behind it.

## Attach a .c3p
open a new project and right click on Files. 

## Steps to reproduce

1. open a new project
2. right click on Files. 
3. select Array editor

It pops up the not available in the demo version, with the exception behind it.
Does it with array object or without. Everytime I tried.

*What did you expect to happen instead?*
It pops up the "not available in the demo version" without the exception behind it.

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r23/main.js, line 63, col 29622
Message: Uncaught TypeError: Cannot read property 'ǃKxV' of null
Stack: TypeError: Cannot read property 'ǃKxV' of null at ǃeb.ǃnm (https://editor.construct.net/r23/main.js:63:29622) at l (https://editor.construct.net/r23/components/bars/projectBar/projectBar.js:1:26796) at W.ǃlJ (https://editor.construct.net/r23/components/bars/projectBar/projectBar.js:1:29771)
Construct 3 version: r23
URL: https://editor.construct.net/
Date: Sat Apr 29 2017 14:43:59 GMT-0500 (Central Daylight Time)
Uptime: 18.4 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.81
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon(TM) R7 370 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Recent changes to the undo buffer in this area didn't expect the free limits to kick in, I've fixed it for the next release.
