### ISSUE TITLE
NW.js Export Failes [The Culprit Found]

### ISSUE THREAD

**Issue by drezgames** [Scirra/Construct-3-bugs#1360]
## Problem description
So I've been having problems exporting NW.js. It would always fail after exporting 2-3 times. I could reboot and it would work for 2-3 times and then fail every time afterwards. 

I never thought to check Diskeeper (http://www.condusiv.com/products/diskeeper)  because for years I've used it and never encountered any problems with any of the software that I use on a daily basis. Turns out something is going on with it and C3 during the export. DK keeps your HD defragged in real-time. There is an option to exclude files/folders and I tried to exclude the two locations that I know about (the install folder and the appdata folder), but that didn't seem to make a difference. I don't know of any other file/folder that I could try to exclude.

So, If I uninstall this program, then the export works as expected. I guess I can keep it uninstalled if I have to but I would rather not because it does a fantastic job of keeping my HD tidy and fast. If there are any other areas that I can try to exclude, I will try this as well.

**Comment by AshleyScirra** [comment]
This sounds like a problem with Diskeeper, not Construct. During export Construct will do normal file I/O operations that any other app could do; if some other app interferes with that then it's not up to us to fix it.
