### ISSUE TITLE
Cloning an object in the "Families" folder crashes Construct

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1364]
## Problem description

Right-clicking an object in a family and choosing "clone" from the context menu crashes Construct.

## Attach a .c3p

Can be reproduced in a blank project with a single sprite in a single family.

## Steps to reproduce

1. Create a new project, create a sprite, and add the sprite to a family
2. Right click the sprite in the "Families" folder in the Project view (not from the "Objects" folder) and choose "Clone" from the context menu

## Observed result

Construct crashes.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r89/main.js, line 63, col 216238
Message: Uncaught Error: animation frame has no content
Stack: Error: animation frame has no content at i.ǃruL (https://editor.construct.net/r89/main.js:63:216244) at i.ǃpR (https://editor.construct.net/r89/main.js:63:219227) at i.ǃrwe (https://editor.construct.net/r89/main.js:63:219617) at t.ǃrwo (https://editor.construct.net/r89/main.js:63:179260) at t.ǃLl (https://editor.construct.net/r89/main.js:63:179570) at ǃr.ǃo.ǃnI.t.ǃUlq [as ǃr$x] (https://editor.construct.net/r89/components/bars/projectBar/projectBar.js:1:23452) at ǃr.ǃo.ǃnI.ǃUlw (https://editor.construct.net/r89/main.js:2:428472) at n.ǃUlw (https://editor.construct.net/r89/main.js:2:499008) at n.ǃUlq (https://editor.construct.net/r89/main.js:2:498985) at window.ǃJ$.ǃJ$.ǃU_q (https://editor.construct.net/r89/components/bars/projectBar/projectBar.js:1:23441)
Construct 3 version: r89
URL: https://editor.construct.net/index.html
Date: Mon Mar 12 2018 00:16:08 GMT-0700 (Pacific Daylight Time)
Uptime: 63.2 s

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I think this is the same underlying issue as #1350, since I can't reproduce it any more in my local dev build, so it should already be fixed for r90.
