### ISSUE TITLE
r90: Rotated objects in Layout view are reset

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#1366]
## Problem description

Opening a file in r90 will reset object rotations in Layout view.

## Attach a .c3p

[bug_r90.zip](https://github.com/Scirra/Construct-3-bugs/files/1803423/bug_r90.zip)

## Steps to reproduce

1. Open attached file in r89
2. Open attached file in r90

## Observed result

Rotated Sprite is reset to default position in r90.

## Expected result

Sprite to stay put.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Oops. Should have a patch out soon.

**Comment by AshleyScirra** [comment]
OK, should be fixed in r90.2.
