### ISSUE TITLE
Construct 3 - Locked Out Of C3 (Broken 3rd Party Addon)

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1367]
## Problem description

 Construct 3 keeps crashing immediately when displaying the start page because of a broken 3rd party plugin. No way for me to access the addon-manager in order to remove it or update it. 

## Attach a .c3p

[Broken Addon.zip](https://github.com/Scirra/Construct-3-bugs/files/1803441/Broken.Addon.zip)

## Steps to reproduce

1. Install broken plugin
2. Restart Construct 3
3. Notice crash on startup because of broken 3rd party plugin

## Observed result

Construct 3 crashes on startup (start page visible) because of a broken 3rd party plugin and locks me out, basically making it impossible for me to remove it because I can't access the addon-manager.

## Expected result

Construct 3 should make it possible to remove the broken plugin (access the addon-manager) instead of locking me out.

## Affected browsers

* Chrome: yes
* Firefox: yes
* NW.js: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r90 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Try visiting https://editor.construct.net/?safe-mode and uninstall it from the Addon Manager.

**Comment by TheRealDannyyy** [comment]
I'm using the NW.js version of C3. Do you know a trick in order to access that page from there?

**Comment by AshleyScirra** [comment]
Ah, interesting, I don't think there's a direct way to activate that from the desktop build. You can edit the URL in package.json. Alternatively you can simply wipe all of the desktop build storage (**note this will reset all settings and downloads and delete all installed addons**) - the desktop build data folder is in `C:\Users\<username>\AppData\Local\construct3`, and if you delete the `construct3` folder you'll revert it to a fresh install.

**Comment by AshleyScirra** [comment]
Or maybe a better way is to press F12 to open dev tools, go to the Application tab, select Clear Storage on the left, and then click "Clear site data".

**Comment by TheRealDannyyy** [comment]
Clearing site data using dev tools worked, thanks!

If possible, I would like to suggest to maybe add a "launch in safe mode" option in the crash dialog to make things easier. I'd imagine a lot of users don't know that safe mode even exists (at least I didn't until now).

**Comment by TheRealDannyyy** [comment]
Clearing site data using dev tools worked, thanks!

If possible, I would like to suggest to maybe add a "launch in safe mode" option in the crash dialog to make things easier. I'd imagine a lot of users don't know that safe mode even exists (at least I didn't until now).
