### ISSUE TITLE
Object search mis-prioritizes the most relevant result under certain conditions

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1369]
## Problem description

Bug #1141 isn't fully fixed. Depending on how things are named, the system sometimes puts objects that perfectly match the search term further back in the list. I discovered this when filtering for "Player" and getting "ParticlePlayerBlood" as my first result.

## Attach a .c3p

[zamazing.zip](https://github.com/Scirra/Construct-3-bugs/files/1804368/zamazing.zip)

## Steps to reproduce

1. Create two objects that both share a string of characters in their names - one that begins with the string, the other that starts with the same character, followed by another character that is lower in the alphabet than the second character of the string. I.e. "zing" and "zamazing".
2. Add a condition or action, and type "zing" into the Search filter.

## Observed result

"zamazing" is sorted ahead of "zing".

![2018-03-12 13_04_35-new project - construct 3 beta](https://user-images.githubusercontent.com/28039905/37306758-f8a69066-25f5-11e8-8f15-d82765ef50d8.jpg)

## Expected result

Any object that exactly matches the search term from the start should be sorted first.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.146
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
C3 release: r90.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 217 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Ah, missed a case for rearranging. This is a bit tricky to get right, but I think it should be sorted for the next release now.
