### ISSUE TITLE
Problem with saved sprite on DeropBox

### ISSUE THREAD

**Issue by mgsoftwaring** [Scirra/Construct-3-bugs#1371]
## Problem description

*Enter a concise description of your problem here*
Construct 3 don't save correctly sprites on dropbox,. I save and when I open the project the image inswide a sprite is disappeared

## Attach a .c3p

I dont been able to create a small projet that recreate the problem

THe sprite have to animation 
one with one image
the second woth 61 element but 60 image

The image are card with 135 X 195 pixels
[KIMERYOS.zip](https://github.com/Scirra/Construct-3-bugs/files/1806653/KIMERYOS.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Firefox: yes

## System details
Windows 10 professional updated at the last 

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
There's not much we can do about this based on the information given. We need reliable steps to reproduce the problem to be able to investigate it.

Are you sure the problem only occurs on Dropbox? The saving code is identical on all platforms, the save location is only where the resulting .c3p file is sent.

**Comment by AshleyScirra** [comment]
Closing as no repro provided and no further response provided.
