### ISSUE TITLE
Can not export a cordova project to apk through export manager

### ISSUE THREAD

**Issue by rasty6557** [Scirra/Construct-3-bugs#1372]
No problem exporting an apk or xcode project directly from c3p project.
But would crash when export a cordova project to apk through export manager.
Both c2 and c3 cordova project.

Error report information
Type: unhandled rejection
Reason: Error: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present. @ TypeError: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present. at ǃr.ǃo.ǃsZ.ǃvis.ǃviy (https://editor.construct.net/r89/main.js:155:19035) at ǃr.ǃo.ǃsZ.ǃvis.ǃviC (https://editor.construct.net/r89/main.js:155:16923) at app.ǃuT.then (https://editor.construct.net/r89/main.js:155:22729) at 
Stack: TypeError: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present. at ǃr.ǃo.ǃsZ.ǃvis.ǃviy (https://editor.construct.net/r89/main.js:155:19035) at ǃr.ǃo.ǃsZ.ǃvis.ǃviC (https://editor.construct.net/r89/main.js:155:16923) at app.ǃuT.then (https://editor.construct.net/r89/main.js:155:22729) at 
Construct 3 version: r89
URL: https://editor.construct.net/index.html
Date: Tue Mar 13 2018 19:39:39 GMT+0800 (中国标准时间)
Uptime: 14643 s

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
Should be fixed in the next release.
