### ISSUE TITLE
Crash when changing "Parameters" values.

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#1373]
## Problem description

Crash when writing values in "Parameters" window dialog on r90.2
( I have a lot of crash like this one today).
Always when I write some parameters in dialog box.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Add action set layer scale or move object X or any action like this.
2. Close the Dialog Box
3. Open the Dialog Box (clic on this action)
4. Replace/ Change a value

## Observed result

Sometimes, it Crash

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r90-2/main.js, line 2, col 228610
Message: Uncaught InvalidStateError: Failed to execute 'surroundContents' on 'Range': The Range has partially selected a non-Text node.
Stack: Error: Failed to execute 'surroundContents' on 'Range': The Range has partially selected a non-Text node. at Function.ǃgOh (https://editor.construct.net/r90-2/main.js:2:228610) at n.ǃhT (https://editor.construct.net/r90-2/main.js:2:228838) at ǃs.ǃG.ǃV.ǃ$Fg.ǃ$FK (https://editor.construct.net/r90-2/main.js:155:117067) at window.ǃ$FL.ǃ$FM (https://editor.construct.net/r90-2/main.js:155:122952) at ǃ$Fw (https://editor.construct.net/r90-2/main.js:155:119380)
Construct 3 version: r90.2
URL: https://editor.construct.net/r90-2/
Date: Tue Mar 13 2018 15:12:56 GMT+0100 (Paris, Madrid)
Uptime: 3014.7 s

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r90.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 950 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by shortercode** [comment]
@Picoti can you give me an example of the text that your changing?

**Comment by shortercode** [comment]
Nevermind, I think I've found an example. Changing something like "12 + 12" to "12 + abs(12)" seems to break it.

**Comment by Picoti** [comment]
Yes, it's difficult to say when it happens, but most often when I use Suppr or Backspace to change values.

**Comment by shortercode** [comment]
It's the text highlighting system, it's trying to highlight an existing highlight and breaking. I think I've got an idea on how to work around it, but the JavaScript DOM text selection API is a little involved.

**Comment by Scoremonger** [comment]
I just wrote up another example of this in #1380  - it may be redundant with this bug report, but I figured it doesn't hurt.

**Comment by shortercode** [comment]
@Scoremonger I hadn't seen that test case so it might help, thanks!

**Comment by shortercode** [comment]
Okay this should now be fixed for r91!
