### ISSUE TITLE
Dropbox file list not updating unless C3 is restarted.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1374]
## Problem description

I noticed this when working on multiple machines. Not a very big issue but I got a bit confused when not finding my files, as I keep an instance of C3 open most of the time sometimes on multiple machines (work & personal) I often switch machines between, Surface and Mac, so that's how I noticed it.

C3 running on 2 machines. Save a project on one of the machines, and the file is not visible to the other machine, unless you restart C3. Even the refresh button does not update file list.

Not very likely to encounter this unless you often switch machines.

## Attach a .c3p

N/A 

## Steps to reproduce

1. Open C3 on two seperate machines or two seperate browsers.
2. Create a new empty project and save it to cloud (dropbox)
3. Check the other browser/C3 instance to find the just saved file.
4. It's not listed and won't be listed until you restart C3.

## Observed result

Files created on other instances of C3 will not be shown in list unless C3 is restarted.

## Expected result

List should be updated every time you use the open dialogue.

## Affected browsers

* Chrome: yes
* Firefox: yes

**Comment by shortercode** [comment]
This is at least partially expected. The file list is cached by the client to reduce network requests and is only updated when you press the refresh button on the dialog or restart construct.

I was a little worried when you mentioned that the refresh button wasn't working, but it seems fine to me. Did you wait until the save had completed before reloading on the other device?

The steps I followed were:
1. Open C3 in Chrome and Firefox
2. On firefox load dropbox in the cloud dialog
3. In Chrome create a new project and save to dropbox
4. Wait for save to finish in Chrome
5. Press the refresh button in Firefox

If this behaviour is confusing your workflow you can disable it in the settings, but you will see the loading screen in the cloud dialog a lot more. The setting is called "Cache cloud metadata"

**Comment by tunepunk** [comment]
OK. it seemed to update now. In some cases the refresh button didn't help either, but couldn't reproduce it now. I'll keep that setting off then, since I'm switching quite frequently. :) Thanks.

**Comment by shortercode** [comment]
No worries! I'm going to mark this as "not a bug", but if you come up with a replicable issue with the refresh button then I'll look into it :)
