### ISSUE TITLE
Pressing keyboard keys in Project Bar.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1375]
## Problem description

In C2, you can press a letter or number key and search the object by their initials. In C3, you can only find the first object that has the initials.

## Steps to reproduce

1. Select the project bar.
2. Press a letter or number.
3. Press again.

**Comment by AshleyScirra** [comment]
In C3 you can search the project bar by typing. It's got a 1 second timeout before it resets. So if you type something like "Player" and each key press is less than 1 second apart, it should search for and highlight the first item in the tree named "Player". Does that work for you?

**Comment by bilgekaan** [comment]
I didn't know that :D It's better than the old system. Thank you!
