### ISSUE TITLE
Alpha 0 acts like 255 in the Image Editor.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1376]
## Problem description

In C2, I can press CTRL + Left Mouse on the transparent area and use the pencil as an eraser. In C3, when the alpha is 0 it draws like alpha is 255.

## Steps to reproduce

1. Select pencil
2. CTRL + Left Click on the transparent area in image border.
3. Draw

**Comment by DiegoScirra** [comment]
It looks like it is only happening in the released version.

**Comment by DiegoScirra** [comment]
Fixed in r91
