### ISSUE TITLE
Pencil with a color less than 255 alpha.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1377]
## Problem description

I select a color and set the alpha to 100. I draw something with the pencil. This happens:

![2018-03-13_20-53-09](https://user-images.githubusercontent.com/2965842/37360371-1baa5d48-2701-11e8-878e-3d8c71be5023.gif)

## Steps to reproduce

1. Select a color.
2. Set alpha to 100.
3. Draw with the pencil.

**Comment by AshleyScirra** [comment]
What is it that you're expecting instead?

**Comment by bilgekaan** [comment]
In C2 it's like this:

![image](https://user-images.githubusercontent.com/2965842/37360812-4edefeca-2702-11e8-997f-6e98fea54a50.png)

In C3, I think it creates more pixels than it should.

**Comment by bilgekaan** [comment]
In C2 it's like this:

![2018-03-13_21-05-43](https://user-images.githubusercontent.com/2965842/37360905-9724f3c4-2702-11e8-980c-15809fabad55.gif)


In C3, I think it creates more pixels than it should.

**Comment by DiegoScirra** [comment]
Fixed in r91
