### ISSUE TITLE
Go to Find Results tab automatically after the search. (not a bug)

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1378]
## Problem description

I use the Find Result page as a tab like an event or layout.

![image](https://user-images.githubusercontent.com/2965842/37360635-e5bcac62-2701-11e8-8cc3-620e675093f9.png)

It would be great if we can go this tab automatically when we search something. I know you're really busy and it's not an urgent thing. When you got time can you please consider it? Thank you!

**Comment by Scoremonger** [comment]
FYI, you can make suggestions here: https://construct3.ideas.aha.io/ideas

**Comment by bilgekaan** [comment]
Thank you, I know that. This one is a small thing compared to what we are suggesting in aha.io so I thought it's okay to write here since it's an improvement instead of a new feature.

**Comment by AshleyScirra** [comment]
This is minor and easy to fix so we can handle things like this on the issue tracker. Should be fixed in r91.
