### ISSUE TITLE
Construct always prompts to download the beta on open, even after updating

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1379]
## Problem description

As of the latest beta, if I've set Construct to update when new betas are available, Construct prompts me every time I open it to update to the latest.

Maybe related (and worse) - hitting the "back" button on a mouse reloads Construct as of the latest beta, losing any changes made to the project. This doesn't happen in the stable release.

## Attach a .c3p

Any project will do.

## Steps to reproduce

1. In Settings, under Updates, "Notify me about updates for" choose "Beta releases".
2. Close and reopen Construct. When prompted to choose whether to download the latest beta, choose "Update".
3. Close and reopen Construct, or hit the back button on the mouse.

## Observed result

Construct prompts the user to update again.

![2018-03-13 13_09_13-construct 3](https://user-images.githubusercontent.com/28039905/37367322-4cd089b0-26c0-11e8-9b49-1d9565bd8e35.jpg)

## Expected result

If Construct is on the latest beta, it shouldn't prompt the user to update.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.146
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
C3 release: r90.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 220 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by tunepunk** [comment]
It seems like every time you go to editor.construct.net you will automatically open latest stable. Then it checks if there's any updates and redirects you to latest beta editor.construct.net/90-2. Notice how the address changes. I think this must be intentional, but not a very nice solution.

**Comment by AshleyScirra** [comment]
`editor.construct.net` always serves the latest stable release (currently r89). If you have beta updates enabled, it will tell you every time you load r89 that there is a newer beta release available. I think that's all that's happening here. Currently this is by design. If you want to use a mix of stable and beta releases maybe just turn the setting off and manually load a beta release? Beta releases always tell you about new beta releases, the setting only really changes anything for stable releases.

**Comment by Scoremonger** [comment]
Thanks, makes sense. I think the back button reload problem I mentioned is a proper bug, though, so I'll write that up as its own issue.
