### ISSUE TITLE
Changing background or text colors of multiple comments at once is not possible

### ISSUE THREAD

**Issue by cihanyakar** [Scirra/Construct-3-bugs#1381]
## Problem description

Although several comment lines are selected, colors cannot be changed at once.

## Steps to reproduce

1. Add multiple comment lines
2. Select them with ctrl key
3. Right click to any one and click to colors/ change background color

## Observed result

Only one item changes

## Expected result

All the elements should be changed

## System details

* Tried on desktop build.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
