### ISSUE TITLE
Hitting the "back" button on a mouse reloads Construct

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1383]
## Problem description

Hitting the "back" button on a mouse reloads Construct as of the latest beta, losing any changes made to the project. This doesn't happen in the stable release.

## Attach a .c3p

No specific project needed.

## Steps to reproduce

1. Open Construct and update to the latest beta (r90.2 in my case)
2. Hit the "back" button on the mouse.

## Observed result

Construct reloads, which nukes any changes made to a project, if one is loaded.

## Expected result

Construct shouldn't reload without at least prompting the user to verify this was the intent. The stable release just ignores the back button afaik.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r90.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 156 mb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
No idea why this would happen - you mean you press a back button on a mouse and the page _reloads_, not navigates back a page?

The page has an unload handler so if you have unsaved changes it ought to prompt you before leaving. If you don't have any unsaved changes it will let you navigate away though.

How does it compare to pressing the browser's back button? Also do you have a control panel or something for the mouse where you can see the button mapping? Is the back button on the mouse mapped to a particular keyboard shortcut or something?

**Comment by Scoremonger** [comment]
Ugh, I'm off my game today - you're correct that it doesn't reload if changes were made to the project. I'm a filthy liar, sorry.
