### ISSUE TITLE
Tilemap Bar shortcuts "X" and "Y" do not toggle back the mirrored/flipped state of tile

### ISSUE THREAD

**Issue by nativepixels** [Scirra/Construct-3-bugs#1384]
## Problem description

Tilemap bar "flip" and "mirror" features do not toggle back using the respective shortcuts"Y" and "X".

## Attach a .c3p

https://drive.google.com/file/d/1wZFNcCCcdfFsq9G7Bw13Chbd_m5dBEHJ/view?usp=sharing

## Steps to reproduce

1. Open project in either desktop or online verision of C3, Select the tilemap object
2. Go in tilemap bar
3. Select "draw" mode and pick a tile of your choice that is not symmetrical
4. Press "X" once , the tile is mirrored horizontally as expected
5. Press "X" again, the tile stays mirrored instead of toggling back to a non mirrored state
6. Repeat steps 4 and 5 but by pressing "Y", notice the same issue

## Observed result

See steps 4, 5 and 6; the tiles do not mirror/flip back when pressing the shortcut X/Y again

## Expected result

As in Construct 2, the shortcuts "X" and "Y" are expected to toggle back the mirrored/flipped state of the selected tile in draw mode

## Affected browsers

* Chrome: yes
* Firefox: N/A
* Edge: N/A
* Safari: N/A

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 42 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in r91

**Comment by nativepixels** [comment]
Awesome, thanks for getting this fixed so quickly!
