### ISSUE TITLE
[r90.2]Opening/Closing/Selecting layouts tabs causes the layout view to be bugged.

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1385]
## Problem description
R90.2 (happened before already as well)
When, in a project using a lot of tabs, closing a couple of layout tabs, the layout view becomes messed up in the way it is displayed and the way mouse position and click is handled within it.

## Attach a .c3p
https://kyatric.com/c3/bugs/20180315-Bug_Closing_Layouts.c3p

## Steps to reproduce

1. Open the file
2. Maximized in 1920X1080
3. Close all the tabs from Layout 6 to Layout 1.
4. You are on the starting page.
5. Double click on the layouts in the project bar to open them up again, Layout 1 to 4.
6. Close Layout 4, it displays the starting page.
7. Select the Layout 1 tab

## Observed result
https://kyatric.com/c3/bugs/20180315-BugTab.PNG

The layout view is "cut in half", and attempting to move the scrolling bars will show the elements, but clicking on them won't allow to select the sprites / the mouse position is handled as if the layout view was full.

## Expected result

Just the layout view as usual :D

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: Not tested
* Safari: Not tested

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.162
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
C3 release: r90.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 12 gb
Storage usage (approx): 748 mb (5.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by joelmayer87** [comment]
Experienced this a lot too, but never was able to reproduce it knowingly.

**Comment by Kyatric** [comment]
Took the time to find the steps to reproduce. 
As far as I can tell, following them reproduces consistently.

**Comment by tunepunk** [comment]
I've experienced this as well. Couldn't figure out a solid repro tough, but seemed to happen more with multiple projects open.

**Comment by mOOnpunk** [comment]
This happens to me when i have 2 projects open then close one, the other one gets messed up. I have to have 2 separate c3's open each with there own project.

**Comment by AshleyScirra** [comment]
Should be fixed in r95.
