### ISSUE TITLE
Bug - Type: unhandled rejection

### ISSUE THREAD

**Issue by METR1C** [Scirra/Construct-3-bugs#1387]
## Problem description

*I removed an object from my project ( an image object ) and now C3 crashes everytime i open it because it can no longer find this object

"**Reason: Not an object: 'BgScroll' is not an object name**" *

## Attach a .c3p

*I cant, i would have to upload my entire project which wont open*

## Steps to reproduce

I dont know, ive removed hundred of objects before and never had this problem. 

## Observed result

*Construct 3 crashes with a bug report, pasted below. *

## Let me open my project

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Not an object: 'BgScroll' is not an object name
Construct 3 version: r89
URL: https://editor.construct.net/
Date: Thu Mar 15 2018 17:31:35 GMT+0000 (GMT Standard Time)
Uptime: 18.9 s

Platform information
Browser: NW.js
Browser version: 0.27.4
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@d8d23fd3b95d7b3c7744027f2ea1c954aec28955) NWjs/0.27.4 (like Chrome/63.0.3239.132)
C3 release: r89 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 680 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I'm afraid there's not much we can do from this report - we need a way to reproduce the problem.

Could you email your project to ashley@scirra.com? I can try to recover it. However without steps to reproduce the problem in the first place, it's unlikely we will be able to fix the original problem.

**Comment by METR1C** [comment]
Hi Ashley, 

Ive sent you an email with a link to the .c3p file there. Much appreciated. If you cant recover it its fine, it would just be nice to know what is causing it so we can avoid it happening again in future. 

Thanks, 
Peter

**Comment by AshleyScirra** [comment]
We can't generally tell what caused it from looking at an already corrupt project. We need the steps to reproduce the problem in the first place to identify and fix the original problem.

**Comment by AshleyScirra** [comment]
This was resolved by email, and should be fixed in r92.
