### ISSUE TITLE
It is possible to drop new objects onto locked layers

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1388]
## Problem description

I normally start working with a locked layer selected because my "UI" layer is global, and it's at the top of my layer list. This layer is almost always locked and hidden. I'll drag and drop some object into the layout, only to realize it's in a locked layer.

It seems intuitive to disallow dropping objects onto locked layers. In typical application with layers, like Photoshop, "locked" means you can't make changes to a layer without unlocking it first. I can't think of any cases where I would want to add objects to a layer while leaving it locked. Normally after placing an object you'll want to fiddle with placement a bit more, and so on.

A related problem in my case (maybe by design?) is that it's not possible to change the layer of objects dropped into global layers. So I'll open a project, accidentally drop an object into the locked, global "UI" layer, try to change the layer with the dropdown, fail, unlock the layer, delete the object, select a new layer and place the object again. But this could all be prevented by prohibiting the adding of stuff to locked layers.

## Attach a .c3p

Any new project with a single sprite object will do.

## Steps to reproduce

1. Create a new project.
2. Select and lock the default layer.
3. Drag and drop any object into the layout.

## Observed result

The object is added to the locked layer.

## Expected result

An error message appears telling me the layer is locked.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.162
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
C3 release: r90.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 221 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
You can create a new object type on a locked layer and it shows a balloon tip warning you the layer is locked. I've applied that to when you drag-and-drop instances in to the layout view as well.

Please only report one issue at a time - we can only assign, close etc. one at a time. If there is anything else you want investigated please file it separately.

**Comment by Scoremonger** [comment]
Sure, apologies. That second bit wasn't meant to be a second nested bug report (but in practice it is, so I get why it annoys you). I was trying to determine if that was intended behavior or not, and if not I planned to write another report. But that wasn't clear. I'll aim to draw harder lines between these things in the future.
