### ISSUE TITLE
[Event sheet] Some keyboard shortcuts only works when events are selected

### ISSUE THREAD

**Issue by shinkan-fb** [Scirra/Construct-3-bugs#1389]
## Problem description

**Add event**, **Add comment,** **Add group** shortcuts work only when event or events are selected.
But **Add global variable** and **Include event sheet** works fine anytime.

## Attach a .c3p

[shortcuts.zip](https://github.com/Scirra/Construct-3-bugs/files/1817342/shortcuts.zip)

## Steps to reproduce

1. Open Event Editor
2. Make sure nothing is selected
3. Press some shortcuts like **A**, **Q** or **G**

## Observed result

If none of the events are selected then nothing will happen.

## Expected result

Assuming that the event editor is opened and in focus, pressing **E** for a shortcut **Add event** as name suggests should create a new event on the very bottom of the events. Same with groups and comments. 
Currently there is no way to quickly create new events or groups by keyboard only. If you want to create new one then you have to use mouse and click on "add event" at the bottom, or select bottom event and then press shortcut or open right mouse button menu.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari:no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 243 mb (1.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 780 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It doesn't make sense to support the 'A' (add action) shortcut with no selection - which event should it add an action to? I've added support for E (add event), G (add group) and Q (add comment) with no selection though.
