### ISSUE TITLE
[Event sheet] There is no way to make or edit events with keyboard only

### ISSUE THREAD

**Issue by shinkan-fb** [Scirra/Construct-3-bugs#1390]
## Problem description

If you open the Event editor there is literally no way to start making or edit current events using only a keyboard. 
You have to move and click mouse button on event, group or comment to be able to move between them with the keyboard and use shortcuts. 
There is no other way to do it.  Pressing **Tab**, to cycle through the interface completely ignores the event sheet. It just moves between _Properties_, _Layers_, _Project_ etc bars.

## Attach a .c3p

[shortcuts.zip](https://github.com/Scirra/Construct-3-bugs/files/1817356/shortcuts.zip)

## Steps to reproduce

1. Open the project
2. Go to event sheet editor
3. Try making new or edit current events without using a mouse

## Observed result

Simply You can't. You have to select something with the mouse first to be able to do it.

## Expected result

I would expect that, doing some stuff on the Layout editor and then, for example pressing **Shift+S** to quickly move to event editor I should be able to start working right away. Press **E** to make new Event, then actions, conditions, comments.....  Instead I'm stuck and can't do nothing.
You have to reach out for the mouse and then move it and select something and only then you can start working on events.
Simple keyboard shortcut to select last event will do. 

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 243 mb (1.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 780 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
After fixing #1389 you can now add events with nothing selected. Adding an event selects it so you can then navigate the selection with the arrow key shortcuts. However there's no way to select anything by keyboard immediately after opening an event sheet. So for the next build I've changed the arrow key shortcuts to select the first event if nothing is selected. So you can then open an event sheet and press any arrow key, and the first event selects, allowing you to navigate further.
