### ISSUE TITLE
[r89] UI lags on larger projects

### ISSUE THREAD

**Issue by nativepixels** [Scirra/Construct-3-bugs#1391]
## Problem description

*UI lags on larger projects:
My project was imported from C2 and I do not use third party plugins. The browser version is barely affected, but the desktop version shows the lag pictured below.

EDIT:
I tried to reproduce the lag with the same project on a different machine and it was much more responsive. Seems to vary from machine to machine.

See screenshots below

## Attach a .c3p
[Dummy test project attached](https://drive.google.com/file/d/1Uwr1OIWP444EbCnDZGuo7nv7RKKdOTQH/view?usp=sharing)

## Steps to reproduce

1.You need a large project to open in the desktop version or you can use the dummy test project file attached.
2. Select the "test sheet" that is nested into the subfolder "New Folder 4"
![image](https://user-images.githubusercontent.com/22468817/37608851-d8712280-2b58-11e8-9a27-9c733985f755.png)

3. Try to resize the UI windows or perform, a search in the event sheet, notice lags
4. Select "Empty sheet" in the same sub folder, repeat step 3. notice less or no lag.
5. Select the layout, repeat step 3, notice less or no lag

## Observed result
![large project](https://i.imgur.com/sJMTwmL.gif)
The edges of the window become impossible to select/grab (see screen capture above) when manipulating the UI with an event sheet with many events is selected int he background.

I recorded another video showing the difference of lag between event sheets with large amounts of events and samller ones: https://i.imgur.com/AH7LMRd.mp4

## Expected result
![small project](https://i.imgur.com/wsefo93.gif)
What you see in the screenshot above, the window resizing should be more responsive.

## Affected browsers

* Chrome: yes
* Firefox: N/A
* Edge: N/A
* Safari: N/A

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r89 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 12 gb
Storage usage (approx): 2 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks like it's just the cursor isn't changing properly, which is similar to #427. Do you have dev tools open? There's a known bug with that causing cursors not to change properly.

**Comment by nativepixels** [comment]
I do have #427 but here, I am referring to the fact that the UI in general was less responsive (dragging, scrolling,  resizing). The search window  seemed to show the most problems with the cursor, so I focused on that, but it might be two separate issues. 

General UI lag happens to me when I load a large project only, the lag varied from machine to machine greatly but it was still perceptible on the machine on which it ws performing better. I can try to give you as much description about the project event count and size when I get home tonight.
I did not have dev tools open and noticed the browser version would lag less consistently than the r89 desktop version.

**Comment by AshleyScirra** [comment]
Can you provide a sample project? You can just stuff a new project with dummy content to simulate a large project so you don't need to share your actual project.

**Comment by nativepixels** [comment]
can I send you my actual project in private`? I have no problem sharing it with Scirra staff, just not publicly

**Comment by nativepixels** [comment]
I noticed that it only affects the UI when the event sheet is active, not when a layout is active, see video below:

[Event Sheet UI lag](https://i.imgur.com/AH7LMRd.mp4)

**Comment by AshleyScirra** [comment]
You can just stuff a new project with dummy content to simulate a large project so you don't need to share your actual project. It is far easier to deal with bug reports this way.

**Comment by nativepixels** [comment]
okay, I edited the original post and attached a dummy file as requested. Thank you

**Comment by nativepixels** [comment]
g drive permissions changed as I changed their client service, re- uploaded a link for the dummy c3p file. Thank you

**Comment by nativepixels** [comment]
knock knock neo...

**Comment by shortercode** [comment]
Just reviewing some of our unassigned bugs. I've assigned to @AshleyScirra as he was taking an active hand in this. 

@nativepixels very large event sheets do tend to stress the browsers layout engine. I've heard that using the default theme instead of the light/dark theme can noticeably improve performance in this situation. Also splitting up your eventsheet into smaller ones will obviously help. These are just 2 workarounds, they obviously don't solve the problem.

**Comment by AshleyScirra** [comment]
The link in the original report no longer works. Please make sure it's available or reupload it otherwise we cannot investigate the report.

As @shortercode mentioned the main issue here is the layout performance of the browser. This is not something we directly control and unfortunately there aren't any good tools to diagnose layout performance at the moment, so it's hard to find out why it's slow or which specific elements or styles are slow. I wrote about this a bit in [this blog post](https://www.construct.net/blogs/ashleys-blog-2/layout-is-the-next-frontier-of-web-app-performance-942). I wouldn't expect any quick movement on this issue I'm afraid, it's really tough.

**Comment by nativepixels** [comment]
I edited the link above, my bad, I had to change G drive location and client and permissions didn't follow. 

@shortercode I did indeed try what you suggested with the theme and I can confirm that it makes no significant difference in my case.

Splitting up event sheets is definitely a workaround I intend to do in the future, but my concern is that I am encountering this issue with a 2 years old large project that I imported from C2 and I am not looking forward refactoring this as it works fine in C2 as far as large event sheets go, but would also like to enjoy my yearly license and keep working on this project. There is a bit of lag noticed, but nothing that breaks the user experience like the problem described above in C3.

**Comment by AshleyScirra** [comment]
I think this case is entirely bounded by the browser's layout performance. We've already done a fair bit of work to optimise layout performance (with CSS containment), but this doesn't seem to be a magic bullet. Unfortunately I think at this point it's infeasible to improve this, especially with the lack of tools focused on layout performance. So ultimately this needs to be improved from the browser side. The good news is there is already a big project in progress to improve the layout engine in Chrome called LayoutNG which you can follow here: https://bugs.chromium.org/p/chromium/issues/detail?id=591099
Hopefully once that's out it should improve the situation with layout performance with complex layouts, such as demonstrated in this case.
