### ISSUE TITLE
Possible string issue in next release

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1395]
## Problem description

"Triggered after 'Load leaderboard' when the data is available."
text.plugins.instantgames.conditions.on-leaderboard-loaded.description
 => No string available exactly named 'Load leaderboard'

"Triggered after 'Load player score' when the data is available."
text.plugins.instantgames.conditions.on-player-score-loaded.description
 => No string available exactly named 'Load player score'

**Comment by AshleyScirra** [comment]
The "Load leaderboard" action is actually named "Load leaderboard scores", so I've updated that. However there is an action named exactly "Load player score" at text.plugins.instantgames.actions.load-player-score.list-name.

**Comment by Kyatric** [comment]
I still see text.plugins.instantgames.conditions.on-leaderboard-loaded.description refering to "Load leaderboard".
I translated accordingly nonetheless.

I guess I messed up my search for the second, I indeed find it and it was already correctly translated.

**Comment by AshleyScirra** [comment]
It's only fixed in my local copy, I only sync the strings to POEditor from time to time, usually in the run-up to a release. It should appear soon.

**Comment by Kyatric** [comment]
Makes sense. Ok then :D
