### ISSUE TITLE
Sprite frames reset when deleting frame from other animation

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1398]
## Problem description

[Test.zip](https://github.com/Scirra/Construct-3-bugs/files/1821847/Test.zip)

see steps to reproduce

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. create a sprite object
2. add an animation
3. add multiple frames
4. copy object multiple times with different frames so you see all in the editor (see upload)

now EITHER:
5. duplicate existing animation
6. delete a frame (or all except 1) in the duplicate animation
7. Notice the other objects in the editor have changed their frames:
if you deleted only one frame, only some will have changed, if you deleted all frames except the first, the ohter objects will have only one frame, even though you did not change the animation they are using at all.

OR:
8. create another animation in the object
6. and 7. are the same as at EITHER

IN THE UPLOAD:
do 6. and 7. to see the result on any object (the one on the right has the second animation)

a gif:
https://imgur.com/a/qBof9
![the gif as gif](https://i.imgur.com/Cfc8Pao.gif)

## Observed result
Objects change their frame

## Expected result
Objects do not change their frame if their animation has not changed

## Affected browsers

* Chrome: yes/no
Using r89 (stable)

## System details
<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can you reproduce this in the latest release r91?

**Comment by Leralasss** [comment]
It also happens in r92 (only recently switched to beta)

**Comment by DiegoScirra** [comment]
Fixed in r95
