### ISSUE TITLE
Can't move the selected area in Image Editor with Arrow Keys

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1399]
## Problem description

In C2 we can move the selected area with arrow keys. 

## Steps to reproduce

1. Use the selection tool to select somewhere in the image.
2. Press arrow keys.

## Observed result

Nothing happens.

## Expected result

Selected area should move one pixel in arrow key direction.

**Comment by BonzerKitten7** [comment]
I was about to open a new issue about that, thanks! Hahaha.

**Comment by DiegoScirra** [comment]
Added in r95
