### ISSUE TITLE
Sprite Editor Unfocused On Open

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#14]
## Problem description

Sprite Editor Unfocused On Open

## Steps to reproduce

1. Edit an existing Sprite Object to open the Sprite editor.
2. Make sure to select a Tool that draws (Pencil/Brush/Fill/Lines/Shapes) before entering the Sprite editor.
3. Draw with only one initial click.

## Observed result

You can't draw on the first click as though the Sprite editor isn't focused on initial launch. It happens all the time whenever you open the Sprite editor. BUT it never was the case when you first entered the Sprite editor by creating a new Sprite object. 

All buttons works fine on the first click, just the editor where you edit the sprite that has this bug.

## Expected result

Should be able to draw or edit the sprite directly on the first stroke/click after opening the Sprite editor.

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed in r17.
