### ISSUE TITLE
Crash when Crop whole animation

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#1401]
## Problem description

Crash when SHIFT Crop on r91

## Attach a .c3p

[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/1822725/New.project.zip)

## Steps to reproduce

1. Create a Sprite with multiple frames.
2. Select a frame and use SHIF + Crop

## Observed result

CRASH

## Expected result
All frames croped

## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r91/main.js, line 2, col 221716
Message: Uncaught RangeError: Offset is outside the bounds of the DataView
Stack: RangeError: Offset is outside the bounds of the DataView at DataView.getFloat32 () at ǃk.DataView.ǃIdm (https://editor.construct.net/r91/main.js:2:221716) at ǃk.DataView.ǃIdG (https://editor.construct.net/r91/main.js:2:220298) at Function.ǃXkW (https://editor.construct.net/r91/main.js:74:427885) at FileReader.n.addEventListener (https://editor.construct.net/r91/main.js:74:389788)
Construct 3 version: r91
URL: https://editor.construct.net/r91/
Date: Sun Mar 18 2018 15:07:12 GMT+0100 (Paris, Madrid)
Uptime: 83.2 s

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r91 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 950 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r93
