### ISSUE TITLE
Text display incorrectly in Thai language.

### ISSUE THREAD

**Issue by Kunnatam** [Scirra/Construct-3-bugs#1402]
## Problem description

Thai language has a very weird character system that sometimes they have to be on top of other characters. That lead to this issue that working on spritefont is impossible and text object will display Thai incorrectly. Problem here is text object only display texts that are within the box which some Thai words are too tall to be in a box.  
I tried to find any document on how to bring the text origin down just a little bit but I couldn't found one.(except for changing the alignment which is not a very great solution) I also post a thread on scirra forum but I haven't got any reply yet which I doubt that many people who doesn't use Thai will encounter this problem. 

## Attach a .c3p

[here](https://www.dropbox.com/s/xow7kdmyutzkvw5/text.c3p?dl=1)

## Steps to reproduce

On text object, type any Thai word that has more than 2 character stacked.

## Observed result

Some portion of the word is disappeared. (example left text in given c3p)

## Expected result

Display the whole word. (example right text in given c3p is what it should look like)

## Affected browsers

* Chrome: yes (both pc and mobile)
* Firefox: unknown
* Edge: unknown
* Safari: unknown

**Comment by AshleyScirra** [comment]
This actually relates to some work I've already done in the C3 runtime for the new text formatting features. The problem with the existing text object is it uses a "top" baseline and draws from there down. However as you've discovered, sometimes text can extend above the "top" baseline. The fact that objects cannot draw outside of their box, and it starts drawing text at the very top of the box, means that in this case there is a small amount of cut-off.

In the C3 runtime I've already changed the text baseline to "alphabetic" and adjusted the draw position to compensate with enough room to draw above the "top" baseline. This was mainly done so it looks correct if the text size changes along a line. However a consequence is that it shifts everything down a little and makes extra room for the top of the text to display correctly. I've checked and it does already solve this problem in the C3 runtime.

The problem with changing the existing text object is unless there's an option, it will break existing projects in subtle ways as text becomes slightly mis-aligned. However we've already got an option to opt-in to this for the C3 runtime (the "enable BBcode" option), so with that enabled it's already fixed. Given that it's already fixed but just not released yet, would you be OK with this issue being closed as resolved when the C3 runtime comes out?

**Comment by Kunnatam** [comment]
Thank you for the clarification. Yes, please marks it as closed since it's already fixed.
Since my only hope for using Thai in my game lies on Text object, I'm so excited for the new Text feature to come out that I actually just found it on the blog a couple minute ago and it looks very promising. Can't wait to try.
Again, thank you for your support.
Cheers!

**Comment by AshleyScirra** [comment]
OK, hopefully we should have an early alpha of the new runtime out soonish for you to try.
