### ISSUE TITLE
Trying to export a 250mb C2 cordova project with C3 Export manager, maximum size exceeded

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#1408]
## Problem description

Was overjoyed to learnt that C3 can export C2 ios projects via cordova! Yeay it's my birthday I can suddenly export 3 other games stuck in the mud otherwise.

But I've been paining with this limit that's stated nowhere what it is supposed to be. My upload gets to about 40% of 250mb so I presume that's the limit, but it would be nice to know that when it stops uploading. 

I'm prepared to pay if there is another way to upload my meticulously compressed (from 650mb) project and get it built for ios in C3.

## Steps to reproduce

1. Upload a project >250mb and try to export with export manager from C3
2. Build project

## Observed result

Maximum size exceeded

## Expected result

A project gets build and I become the happiest person in the world

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r92 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 268 mb (3.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Currently the limit is actually based on the APK size limitations ( 100MB ), which don't really apply to iOS applications so we could probably raise them for exporting to xcode. I'm not sure how it factors into our "cost per build" value if I'm honest, could be negligible to increase it to 300MB. But then I'm not sure what a sensible limit would be.

**Comment by damjancd** [comment]
I'm willing to limit my times that I try exporting a build. The game is finished long ago (a year and a half already) but has been waiting to be able to be exported smoothly to iPads. 

You guys could issue monthly tokens or have a limit for people. Meanwhile it would be incredibly useful if I could make this game run on ipad using all the advantages of C3 exports. 

Our game is a kickstarted one, we gathered enough money and released it for PC but it has been waiting for very long for iPad and you have to understand that when I heard of the smooth export of C2 projects using C3 for iOS, I did about ten mini celebrations with cake and candles :p

Would appreciate any help around this.

**Comment by shortercode** [comment]
How big is your project if you export it for cordova, as the zip file? Just curious what sort of size we should be dealing with.

**Comment by damjancd** [comment]
@shortercode It's 250 mb, after horrendous compression of many images that took 2 days on a powerful desktop :)

**Comment by shortercode** [comment]
Okay well I think I'll increase the limit to 300MB, and we'll see how it goes for a week.

We don't have an option for adjusting the size for Android or iOS specifically, just the overall project. So it would require restructuring the build process to do it for only iOS. So the limit will be raised for Android as well. Part of me keeps hoping they will just increase the APK size limit...

**Comment by shortercode** [comment]
Okay I've increased the limit, let me know how you get on.

**Comment by damjancd** [comment]
Thank you very very much!

But now it keeps loosing connection with build server after it uploads it and unpacks it :(

**Comment by shortercode** [comment]
I think the build server had one of it's occasional lock ups, unfortunately I was away on holiday for a week after I talked to you...

I'm just trying to clear out some of my stale and duplicate bugs, did you manage to get your project to build?

**Comment by damjancd** [comment]
Not yet. I tried to a few weeks back when you guys enabled the lift of the limit and I tried a few times a week ago. Same error and the same problem. 

Hope you had a nice holliday :)

**Comment by damjancd** [comment]
@shortercode "build failed because exceeded maximum upload time" :(

I tried using local wifi at my home and cellular wifi from another provider completely. 
Still just uploading 250mb worth of data.

**Comment by shortercode** [comment]
Did you ever manage to get your project to build? I increased the maximum upload time and project sizes again a little while ago to smooth these sorts of things out. But I haven't heard any reports since then, I'm hoping this is because no body is having these issues anymore!

**Comment by damjancd** [comment]
Yes I managed to run it 5 days ago. Sorry I didn't write back. Preparing to launch the game on iOS :p
Gotta publish it before the world ends :):) or some other sneaky stuff happens with the universe :)

**Comment by shortercode** [comment]
Haha no worries, just glad it's working for you now. I hope the everything goes smoothly for your publish!
