### ISSUE TITLE
Spelling error: URI or URl instead or URL in set sprite to URL Dialogue

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#1410]
## Problem description

Really just a banality: in the Dialogue for setting an image to an URL, there's either a small "L" or an "I" instead of an "L".

![image](https://user-images.githubusercontent.com/30116964/37713604-b2998b9a-2d17-11e8-9858-be473ff4c196.png)

## Steps to reproduce

1.Create Sprite
2.Choose Action "set image to URL"

## Observed result

Wrong spelling.

## Expected result

Right Spelling.

## Affected browsers

* Chrome: yes

**Comment by joelmayer87** [comment]
EDIT: OOOOPS i guess i was being a smartass a bit to early :D URI of course stands for something different. Nevermind, i can't seem to be able to close this report so yea. Take it away :) Sorry for the confusion!

**Comment by AshleyScirra** [comment]
Yeah, a URI is a thing (Universal Resource Identifier)! I'm not really clear on what the difference between a URI and URL is, it seems kind of academic, and sometimes I just copy the term used by the spec or API.
