### ISSUE TITLE
C3 gui issue on Samsung Galaxy Tab (10.1) 

### ISSUE THREAD

**Issue by OrionUk** [Scirra/Construct-3-bugs#1411]
I have come across an issue with C3 that is gui based (no project file to attach), so it does not qualify as an acceptable method for the usual bug reporting process... This is for release build r89 AND r92...

Action and add event sections need to be 'resizable'/ need to be able to scale that area?

Basically, the issue is with using C3 on my Samsung Galaxy tab A6 (10.1)...

<a href="http://s603.photobucket.com/user/mr_potato_head/media/Screenshot_20180320-234249_zpsqrrscyef.png.html" target="_blank"><img src="http://i603.photobucket.com/albums/tt113/mr_potato_head/Screenshot_20180320-234249_zpsqrrscyef.png" border="0" alt="Gui issue photo Screenshot_20180320-234249_zpsqrrscyef.png"/></a>

 I can't read the text in the fields as they are too bunched up! Is there or can there be a way to have 'draggable seperaters' ....(hold and drag left or right) to resize the bunched up fields/sections, so the text can be read properly?...  Think of dragging a table column in a web editor... Being able to 'resize' would solve this gui/display issue in my book? :)

**Comment by shortercode** [comment]
The columns are resizable by dragging on them, but it might be that it doesn't work on mobile.

**Comment by OrionUk** [comment]
Many thanks shortercode, the issue I had with layer toggle was just me not knowing about 'double swipe' ..my mistake! But, having tried (in Chrome beta & stable release) I still can't get the columns to resize ...even if I zoom right in with the intention of assuring I am dragging the right area.
Thanks again for the reply :)

**Comment by AshleyScirra** [comment]
There's no project provided so I tried Ghost Shooter on a Samsung Galaxy Tab S2. It looks fine to me (see below). However I did notice an issue where it's possibly trying to load event sheet column sizes intended for desktop on a mobile device. For the next release I've set the mobile view to always use default sizes which helps with readability. Let me know how it looks once r93 is out.

![screenshot_2018-03-26-14-31-52](https://user-images.githubusercontent.com/768723/37909884-0a7b5268-3104-11e8-8ccb-23b2f3c578f0.png)

**Comment by AshleyScirra** [comment]
r93 is now out, please check again!

**Comment by OrionUk** [comment]
Hi Ashely, Many thanks for your reply and looking in to this.

Here is my repy with results from a **quick** test of r93 (Desktop & Mobile in browser)...
r93 (Samsung Galaxy tab A6 (10.1) Chrome Beta  browser...

[](https://www.dropbox.com/sh/vrbx3dnij7yi86o/AAAAm286CMW1k1zO0cu3nakOa/r93%20Tests?dl=0)

Please excuse it being 'thrown together' so quickly!

Side notes:

Can no longer use two fingers to 'pinch & zoom in/out....to make sure i am on the 'column bar' for resize dragging in either mode.

I tested moble & desktop modes on my tablet just to see the differences in behaviour, but will clearly use mobile mode as rule of thumb :D

(Mobile mode)...

Swiping between project/tilemap/layers window **not** and issue in mobile mode.

I Can now lock/unlock layers fine, but toggle check box for hide layers will not register my tap and some times pressing lock layer results in layer hiding/unhidden too!

Eventsheet column display/manual resizing: Still can not resize manually?

(desktop mode)..

Swiping between project/tilemap/layers window is an issue but not a relevant for tablet use.

I Can lock/unlock layers fine, but toggle check box for hide layers will not register my tap and some times pressing lock layer results in layer hiding/being unhidden too!..like above for mobile mode.

Eventsheet column display/manual resizing: Still can not resize manually?

RE comment on providing no project...

I have been using the demo file provided for these tests- Sample project file = Kiwi Story.

My Tablet info: [](https://www.amazon.co.uk/gp/product/B01ERY87AE/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1)

Many thanks indeed, Orion.

**Comment by OrionUk** [comment]
Hui Ashley, Yes looks better..thank you ;)

Just to confirm, did you gt the ink to my video showing the issues at hand...in this context i am refering to the layers toggle visability issue for one thing...

https://www.youtube.com/watch?v=2VKwWXJA7Z0&feature=youtu.be

https://www.dropbox.com/s/5mxf6f1s9oym428/Mobile%20mode.mp4?dl=0

https://www.dropbox.com/sh/vrbx3dnij7yi86o/AABNT-Nstr8vS2j19ipT5V2xa?dl=0

**Comment by AshleyScirra** [comment]
OK, based on the fact you say the column layout looks better, I'm going to close this report. Please only keep one issue to one report, since otherwise it becomes confusing (we can only assign, label and close issues one at a time, and we often need the full set of bug report fields to be filled out for each individual issue).

**Comment by OrionUk** [comment]
Ok Ashley, Many thanks for your time/help and attention to this. 
Also, my appologies for mixing issues.
I will open a new report regarding the layers toggle issue and try to follow procedure closer ;)
