### ISSUE TITLE
Animations Editor: Comparing C3 to C2, missing "Reload files from"

### ISSUE THREAD

**Issue by bible9230** [Scirra/Construct-3-bugs#1412]
Comparing the Animations Editor of C3 to C2, you are no longer able to "Reload files from" the original source.  The option is not available in C3 when you right click on the animation frames bar.

Without it, you have to inconveniently reselect the file from the "Load an image from a file" icon.

**Comment by AshleyScirra** [comment]
It's supported in the desktop build: https://www.scirra.com/forum/construct-3-desktop-build-beta-currently-win64-only_t199344

Browsers don't have permission to read arbitrary files from disk automatically, so we can only provide the feature in the desktop version.
