### ISSUE TITLE
Open image editor with keyboard shortcut.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1415]
## Problem description

When the sprite covered with another object, we need to go properties bar, scroll down and click edit. If it's possible can you please add a shortcut so when a sprite is selected and the shortcut is used, it will open the image editor. "Enter" might be a good shortcut for this.

**Comment by AshleyScirra** [comment]
Added 'Enter' to do the same thing as double-click with a single instance selection for r95.
