### ISSUE TITLE
Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project. R92

### ISSUE THREAD

**Issue by ExedysDigital** [Scirra/Construct-3-bugs#1416]
## Problem description

Cannot load my project in Construct 3 - Shows message in title

## Attach a .c3p

https://mega.nz/#!A2hhjCia!UwhNNYuVaemnxns2RgN42C5mcn2-SBk2SXHz305jhOA

## Steps to reproduce

1. Open Construct 3
2. Upload file
3. Maybe it happen to you

## Observed result

Displayed a dialog box saying: "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

## Expected result

I expected my project to open and to allow me to edit my game.

## Affected browsers

* Chrome: Yes
* Firefox: Yes
* Edge: Yes

## System details

No crash.

**Comment by shortercode** [comment]
@ExedysDigital It opens fine for me in r92. Can you please check that you are trying to open it on editor.construct.net/r92 NOT editor.construct.net?

Projects from newer versions of C3 will no open in older ones. If you created the project in r92, and are now trying to to open it in r89 ( which is currently the current stable release ) then it will fail to open.

**Comment by ExedysDigital** [comment]
@shortercode Tried on R89 and R88 on both the online editor and the desktop version. No difference.

**Comment by shortercode** [comment]
You need to open it in r90 or later.

**Comment by ExedysDigital** [comment]
And opening it again in r90, r91 and r92 did nothing.

**Comment by shortercode** [comment]
The specific error should have been fixed in [r90](https://www.construct.net/gb/make-games/releases/beta/r90) and I can open the project in r90 successfully.

Any project using the Google Play plugin prior to r88 would not open in r88 or r89, due to a removed property.

**Comment by ExedysDigital** [comment]
Okay so reopening in r90 fixed it for some reason. Thanks!
