### ISSUE TITLE
Publishing to Google Play error when adding "Mobile Advert"

### ISSUE THREAD

**Issue by cmr333** [Scirra/Construct-3-bugs#1417]
## Problem description

I get an error on Google Play when I have "Mobile Advert" object added, it took me an hour trying to find the problem when trying to update my game.

I first created a whole new blank project to see if it works, then I started removing my objects one by one in my main game until I found the problem then I went to a blank project and simply added the "Mobile Advert" object with no modifications (Default settings) and the error occurred.

The error is 

> "Your APK is using permissions that require privacy policy: (Android.permission.READ_PHONE_STATE)"

![screenshot 2018-03-23 14 17 07](https://user-images.githubusercontent.com/29158447/37835323-cff79006-2ea7-11e8-98bb-4bbd40485bd9.png)

## Attach a .c3p

[Test.zip](https://github.com/Scirra/Construct-3-bugs/files/1841900/Test.zip)

## Steps to reproduce

1. Create new project
2. Add "Mobile Advert" object
3. Export to Android (unsigned) 5.0+
4. Sign APK
5. Publish to Google Play

## Observed result

I got an error upon publishing to Google Play

## Expected result

No errors.

## Affected browsers

Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r92 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 163 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Have you tried creating a privacy policy? It appears to be a requirement when using admob.

**Comment by cmr333** [comment]
I don't believe so, how would I do that?

**Comment by shortercode** [comment]
Under "store listing" on the google play console you need to specify a URL to a privacy policy document. I'm afraid I can't really give you any advise on what to put in a privacy policy, but there might be something in the admob documentation. 

If your looking for a good place to host the document, you could try GitHub pages. You get https, it's free and it's pretty easy to use if your used to GitHub. I've hosted projects on there in the past.

**Comment by cmr333** [comment]
Oh that, I've already done that about a month ago.

**Comment by shortercode** [comment]
@cmr333 I'm presuming you solved your problem, as you closed the issue?

**Comment by cmr333** [comment]
Nope, I gave up, not gonna use ads anymore

**Comment by cmr333** [comment]
Found the solution, the link I had placed was not available anymore, I forgot I had changed the name of the .html file few weeks ago.

Thanks <3
