### ISSUE TITLE
Project export working only to HTML

### ISSUE THREAD

**Issue by MassimoF-C3** [Scirra/Construct-3-bugs#1418]
## Problem description
Function Menu->Project->Export: any attempt to export even the smaller/simpler project to Android/iOS goes wrong ("Failed to export project" pops up).  The same function works if 
exporting to HTML.  Happens on release r89 (stable) and r92 (beta).

## Attach a .c3p

any project will do (even with just one layer, one sprite & one event).

## Steps to reproduce

1. Open or create any project.
2. Try to export it to Android or iOS with any settings.
3. Observe the error message "Failed to export project".
4 . Repeat step 2 targeting HTML and the project will be regularly exported.

## Observed result

A message "Failed to export project" is displayed and the export is aborted.

## Expected result

The regular creation of an apk, or Cordova export ecc., ready for download

## Affected browsers

* desktop build

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r89 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 6.7 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here. If a project is not provided, I test with Ghost Shooter, and it exports fine.

When you see "Failed to export project", can you open the browser console (F12) and report if there are any error messages there?

**Comment by MassimoF-C3** [comment]
Thanks for the quick answer. Tried to exoprt Ghost Shooter to HTML (and worked fine, as usual) and to Android (got the usual error, see link below).   BUT: after this I tried again to export Space Shooter to Android (maybe I changed one or two parameters, I don't remember :(  )  and it WORKED! It's the very first time. I feel more confused than ever.

Pls note that in the console snapshot there is an entry related to Space Shooter, bcs I opened that project accidentally before GS. ANother thing, I cut the image, the lines "Failed to load resource" were
a lot more.

Link: https://drive.google.com/open?id=1l93A1FxQWdb7VswvuW0Yi-dRWXGW1dAY

**Comment by AshleyScirra** [comment]
It looks like it's failing to download some resources it needs while exporting. I'm not sure what this could be. It might be your connection is unreliable and keeps cutting out when requesting some resources. Does it reproduce in the Chrome browser, or other browsers like Firefox or Edge?

**Comment by MassimoF-C3** [comment]
Yes, I see.  I'm normally working offline, and anyway my connection should be quite stable...now I'll do some more systematic test, as you suggest,  and I'll let you know. Thx again.

**Comment by AshleyScirra** [comment]
Exports don't work offline - that might be why you're having trouble then :P

**Comment by MassimoF-C3** [comment]
Aah...I was aware of the Scirra service for apk creation, that needs a connection, but I believed that the "normal" export were C2-like...(and anyway, the export to html works offline). Sorry, I messed up a bit:). Thx foto your help & your time.
