### ISSUE TITLE
Random Crash (property boundsKey_)

### ISSUE THREAD

**Issue by MassimoF-C3** [Scirra/Construct-3-bugs#1419]
## Problem description

Sometimes, randomly, after a few minutes or half an hour session, C3 crashes displaying an error report. Some other times, the identical error happens when trying to close C3 (with "Exit"): after 3 or 4 failed attempts I open Windows Task Manager to kill the process and the same error report pops up.

## Attach a .c3p

This issue happens on any  project.

## Steps to reproduce

1. Open any project
2. Without closing the project, try to close C3 via "Exit" 
3. If C3 doesn't close, try again, then open the Task Manager

## Observed result

C3 crashes displaying an error report

## Affected browsers

* desktop version

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: extensions::app.window, line 55, col 40
Message: Uncaught TypeError: Cannot read property 'boundsKey_' of undefined
Stack: TypeError: Cannot read property 'boundsKey_' of undefined at Bounds.get [as left] (extensions::app.window:55:40) at NWWindow.get (extensions::nw.Window:548:43)
Construct 3 version: r89
URL: https://editor.construct.net/
Date: Sat Mar 24 2018 18:16:41 GMT+0100 (W. Europe Standard Time)
Uptime: 395.9 s

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r89 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by MassimoF-C3** [comment]
A little update. I have configured the preview as "Dialog", and I'm working offline with the desktop version. Every time I launch the preview, suddenly the Windows bottom bar disappears (i.e. the C3 GUI covers the entire screen). From that moment on, quitting C3 is impossible, as described (and, when you call the Task Manager, you obtain the error report previously attached here).

**Comment by AshleyScirra** [comment]
This sounds like it might be related to #1413, which should be fixed in the next build, so it's probably worth checking again when that's out.

**Comment by MassimoF-C3** [comment]
Sure, thx.

**Comment by AshleyScirra** [comment]
r94 is out now, can you check if it's still happening?

**Comment by MassimoF-C3** [comment]
yes, asap (I believe half an hour or so)

**Comment by MassimoF-C3** [comment]
Everything ok so far,  I managed to quit in all the regular ways without issues/crashes.
Just one (small) thing, the "Project modified - do you want to save?" msg popups every time, even the poroject was not modified at all.

**Comment by MassimoF-C3** [comment]
Damn, it happened again :(...  but this time I believe I figured out what is going on. Everything's fine until I launch a preview - the preview starts & runs smoothly until a point in which there is a Browser "Request fullscreen". Immediately after, C3 interface (note I'm a desktop version running fullscreen, NOT in a window) expands covering the taskbar of Windows, and from this moment on quitting the application is impossible. The only way is via the Task manager, that causes the error report already described & attached.

**Comment by AshleyScirra** [comment]
The error doesn't relate to anything in our code. It looks like something to do with NW.js calling in to Chromium code. I filed a report here with the NW.js developers: https://github.com/nwjs/nw.js/issues/6553
We'll follow up there, so closing this report.

**Comment by MassimoF-C3** [comment]
Ok thx

Massimo Fabbri

Il gio 5 apr 2018, 18:03 Ashley (Scirra) <notifications@github.com> ha
scritto:
