### ISSUE TITLE
r92 Error when Cropping whole Animation

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1420]
## Problem description

*Enter a concise description of your problem here*
Construct crashes when cropping an entire animation

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
[CropError.zip](https://github.com/Scirra/Construct-3-bugs/files/1844666/CropError.zip)

## Steps to reproduce

1. create a sprite
2. add a bunch of frames with different (?) sizes
3. crop whole animation
4. see error report

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE
Error report information
Type: unhandled exception
File: https://editor.construct.net/r92/main.js, line 2, col 221792
Message: Uncaught RangeError: Offset is outside the bounds of the DataView
Stack: RangeError: Offset is outside the bounds of the DataView at DataView.getFloat32 () at ǃt.DataView.ǃEe_ (https://editor.construct.net/r92/main.js:2:221792) at ǃt.DataView.ǃEeW (https://editor.construct.net/r92/main.js:2:220374) at Function.ǃNtP (https://editor.construct.net/r92/main.js:74:426630) at FileReader.n.addEventListener (https://editor.construct.net/r92/main.js:74:388626)
Construct 3 version: r92
URL: https://editor.construct.net/r92/
Date: Sat Mar 24 2018 19:17:10 GMT+0100 (W. Europe Standard Time)
Uptime: 9426.1 s

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r92 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by joelmayer87** [comment]
Can confirm this, i'm getting the same error...

**Comment by DiegoScirra** [comment]
Fixed in r93
