### ISSUE TITLE
querystring and queryparam expressions from Browser object not working in IOS

### ISSUE THREAD

**Issue by driesdriessen** [Scirra/Construct-3-bugs#1421]
## Problem description
When I launch an IOS app on my iphone with a URL + parameters from a web page, the app launches but the parameters are not available in the queryparam expression. Querystring expression is empty.

## Attach a .c3p

[testurllaunchwithparms.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1844745/testurllaunchwithparms.c3p.zip)

## Steps to reproduce

1. Export to IOS, and open in IOS
2. Add a URL type to the Info section in xcode (otherwise the app does not start from the URL). For the example here, the 'URL Schemes' field should contain the value 'myapp' (without quotes), the field 'identifier' a reverse domain name style identifier, such as 'com.scirra.myapp' (without quotes)
3. Build the app and install on an iphone 
4. Create an HTML page that contains a link to launch the app
<a href="myapp://domain/myapp?test=testing123">Launch my app</a><br/>
5. Launch the app on an IOS device from this web page

## Observed result
The querystring expression is empty. The parameter 'test' with value testing123 is not available

## Expected result
querystring contains '?test=testing123' and queryparam('test') returns 'testing123' like it does when you run the app as HTML5

## Affected browsers

* Chrome: Not applicable
* Firefox: Not applicable
* Edge: Not applicable
* Safari: Not applicable

## System details

<details><summary>View details</summary>

latform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 0.75
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 6.9 gb
Storage usage (approx): 199 mb (2.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel HD Graphics 5000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

xcode: Version 9.2 (9C40b)
device: iphone 7 running IOS 11.2.6

**Comment by AshleyScirra** [comment]
Why are you doing this? It's a really weird way to pass data in to an application. The feature is designed for web browsers with a visible URL bar, so even if it doesn't work, without a good reason to support it I think we might just call it an unsupported feature.

**Comment by AshleyScirra** [comment]
I wouldn't expect a custom protocol handler to forward any query string arguments... it probably uses a separate mechanism. The query string parameter expressions are designed for use in a browser with a visible URL bar, and when built as an iOS app you don't have that. The URL itself in that case is some undefined, vendor-specific detail, so I don't think you can count on it being anything in particular.

**Comment by driesdriessen** [comment]
Hi,
The reason for doing this is to launch my ios app in a specific context. If there is a better way to do that, I will do that of course.

I am writing an app where users can work together on a note. I want to open the app from a link in a mail. That requires some additional settings in Xcode. This works fine. What I can’t do yet is pass a parameter to tell the app what page to open.

Hopefully that clarifies.

Thanks for your help. And thanks for the tremendous work you and the Construct team are doing. You are the most responsive product team I know!

Dries.

Op 26 mrt. 2018 om 14:42 heeft Ashley (Scirra) <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Closed #1421<https://github.com/Scirra/Construct-3-bugs/issues/1421>.

**Comment by AshleyScirra** [comment]
Why did you expect the browser query string parameters to contain this information? Is this a documented part of custom protocol handlers? If not I think the problem is the wrong expectation.

**Comment by driesdriessen** [comment]
Hi Ashley,

When I run the app as html, the browser expressions do exactly what i need. When i build for IOS i can configure xcode to link my app to a local url on the device (eg. myapp://). IOS supports passing url-style values to an app in this way (eg. myapp://domain/app?test=test123). Because this is very similar (to the untrained eye :-) ) to launching an html5 application, I was hopeful that the functionality was mapped to the Browser expressions.

It would be a nice feature ;-)

Thanks and kind regards

Dries

Op 26 mrt. 2018 om 15:18 heeft Ashley (Scirra) <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Why did you expect the browser query string parameters to contain this information? Is this a documented part of custom protocol handlers? If not I think the problem is the wrong expectation.
