### ISSUE TITLE
"Release key" doesn't work for gamepad

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#1422]
## Problem description
Apologies for my "english" but it's not my first language.

So, simply, every action after "Release key" condition doesn't work for any button on gamepad (tested on XBOX360 gamepad)

## Attach a .c3p

[New project (9).zip](https://github.com/Scirra/Construct-3-bugs/files/1844822/New.project.9.zip)

## Steps to reproduce

1.  Create a new project,
2.  add gamepad object
3.  do any action after "Release button"

## Observed result

Doesn't work.

## Expected result

See it's working.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by nalcwap** [comment]
lol i try your sample ,you put button X to press but in the code you have the button Y , are you tryed the button Y?if yes i have an xbox360 command the white command and the button Y work,or i miss the wrong english sorry

**Comment by AshleyScirra** [comment]
It works for me. If I hold down Y, and then when the bar is full tap A a few times while Y is still held down, it spawns a sprite. Did you mix up the buttons?
