### ISSUE TITLE
instant game object offline android

### ISSUE THREAD

**Issue by nalcwap** [Scirra/Construct-3-bugs#1424]
## Problem description

when i add this object offline the preview not work offline in my android ,if i delete this plugin offline the preview work 

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

1.add the instant game object offline in android and try preview
2.
3.

## Observed result

*What do you see happen?*

*What did you expect to happen instead?*
i expect the preview work because become stuck and not work in android
## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

no crash error

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I think Facebook's API currently requires a connection to load. I've asked them what they recommend to do to support offline games.

**Comment by nalcwap** [comment]
ok ,but if imput the object the preview not work, the only fix is not put this but good to know is normal,thanks  AshleyScirra

**Comment by AshleyScirra** [comment]
Facebook have informed me that Instant Games do not support offline sessions. So I'm afraid I don't think there's anything we can do about this.
