### ISSUE TITLE
Importing CAPX hangs if upgrade notice pops up during import

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#1425]
## Problem description

Opening a CAPX in an older release hangs if the 'new release' warning pops up before the import actually starts.
This one is awkward as I can't reproduce it now that I've passed the 'new release' dialog warning.

## Attach a .c3p

N/A

## Steps to reproduce

1. Run C3 - my system was at r85
2. Open a local file - CAPX
3. The new release dialog pops up warning that r89 is available
4. THEN the import dialog pops up over that - but never progresses. It just stays at zero percent.
5. Had to kill browser to clear the condition.

## Observed result

Modal 'import' dialog is over the 'newer release' dialog, blocking access to the release dialog, but also not progressing with the import. Can't cancel anything.

## Expected result

Not that. I'll leave t to you to decide how best to deal with this use case.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
I can force the new release popup to appear every time in testing, and I can still import projects just fine over that. The import process completes normally and leaves the new release popup showing.

Not sure there's anything we can do unless you look in the browser console and find an error message you can report there, or if you can find a better way to reproduce it. (You can make a similar beta popup appear by enabling beta update notifications then loading r89 or any previous beta release other than the latest.)
