### ISSUE TITLE
Export to Android Studio - Waiting to Build - Time-Out

### ISSUE THREAD

**Issue by luisforte** [Scirra/Construct-3-bugs#1427]
## Problem description

Exported project for android studio stuck on Waiting to Build

## Steps to reproduce

Export project to Android Studio

## Observed result

Some times the export process stuck at "Waiting to build - Restored Connection"

## Expected result

Build project

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

**Comment by AshleyScirra** [comment]
No project provided, but appears to reproduce with Ghost Shooter.

**Comment by luisforte** [comment]
No project related issue... any project stuck at Building Server.... service got-back again

**Comment by jaydonteh** [comment]
Just tried to export my apk and got stuck on "waiting to build" then "restored connection". [r94.2]

**Comment by shortercode** [comment]
Realised we had 2 issues for this bug, the other one was a bit more descriptive so I'm closing this one as the duplicate of #1481
