### ISSUE TITLE
It is unable to exit program when there are unsaved changes

### ISSUE THREAD

**Issue by cihanyakar** [Scirra/Construct-3-bugs#1428]
## Problem description

You can't close editor without saving the changes.
 
## Steps to reproduce

1. Open a project
2. Make same changes
3. Try close the app without saving 

## Observed result

Endless confirm dialogs...

## Expected result

Only one dialog

## Affected browsers

* Desktop
## System details

Desktop build

**Comment by luisforte** [comment]
You dont have the checkbox "Dont show anymore.." ?

**Comment by cihanyakar** [comment]
There is. But it is not the solution.I must use task manager to exit.

**Comment by DiegoScirra** [comment]
This looks like a duplicate of #1413
