### ISSUE TITLE
R93: Replace All in XML View is overlapping Button

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#1429]
## Problem description

More of a cosmetic problem but i thought i'd report it anyway ;) When you open the Search/Reply Window in the XML Editor, you can see, that the "Replace All" Label overlaps the button.

![image](https://user-images.githubusercontent.com/30116964/37913794-0633ebb8-3116-11e8-9649-56554c4f69c0.png)

## Steps to reproduce

1. Create a new Project
2. Create a new XML File in the "Files" Folder
3. Open XML File in C3 XML Editor
4. Press Control/CMD + F

## Observed result

Replace All looks wrong.

## Expected result

For the label to be inside the button.

## Affected browsers

* Chrome: yes

**Comment by shortercode** [comment]
I'm not actually sure quite how it's overlapping on your computer. I can't reproduce this at all.. do you have your text size increased somehow?

Either way I've increased the button size a bit and reduced the padding size, so hopefully it should squeeze in now.

**Comment by AshleyScirra** [comment]
@shortercode - FYI you should avoid `px` sizes and use `em` instead, because if you increase the browser text size, text (`em` sizes) get bigger but `px` sizes do not, which can cause text overflow issues like this.
