### ISSUE TITLE
[r23] UI crash because no tab limits

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#143]
## Problem description

After discovering you could create a new project instantly on desktop mode https://github.com/Scirra/Construct-3-bugs/issues/140, I tried to spam that key to have C3 editor opening lots of layout and event sheet tabs. C3 crashes after the tabs fill up the entire screen.

## Steps to reproduce

1. Go into desktop mode.
2. Spam CTRL + "N"
3. Fill the screen with tabs.

## Observed result

Crashed.

## Expected result

Limit the tab so the view does not fill up and crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r23/components/editors/layoutView/layoutView.js, line 1, col 36363
Message: Uncaught Error: invalid shared canvas size
Stack: Error: invalid shared canvas size at window.ǃKak.ǃKIT (https://editor.construct.net/r23/components/editors/layoutView/layoutView.js:1:36369) at window.ǃMN.ǃKet (https://editor.construct.net/r23/components/editors/layoutView/layoutView.js:1:6642) at ǃKeR.Y (https://editor.construct.net/r23/components/editors/layoutView/layoutView.js:1:2127)
Construct 3 version: r23
URL: https://editor.construct.net/index.html
Date: Wed May 03 2017 01:16:23 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 130.2 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Bit of a contrived case but fixed the crash for r24!

**Comment by jaydonteh** [comment]
Perhaps contrived, but it's not the cause of the https://github.com/Scirra/Construct-3-bugs/issues/140 that crash in this case!

I found out the process of reproducing this crash:

1. Go to Desktop Mode.
2. Create a New project.
3. Close the layout tab or the event tab.
4. Resize Construct so that it is so compact that there is no space for the tab to show.
5. Double-click to open the previously closed layout tab or the event tab.

Resulting in a crash because of the limited UI canvas space available.

Is either you resize the screen to a lack of screen space (and open another layout/event sheet tab) or you open so many tabs that it run out of space to put the tab.

**Comment by jaydonteh** [comment]
![Image of bug](http://i.imgur.com/mZGXfAB.png)

Close a layout tab and Resize as shown above. Now, double-click the previously closed layout tab at the project bar to open and crash it.
