### ISSUE TITLE
R93 Open Image Editor Error

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1432]
## Problem description

I opened my project in R93 Desktop and try to edit an image. Get an error. It only happens if you load your project from cloud.

## Steps to reproduce

1. Open your saved project.
2. Double click a sprite.
3. Get error.

Error report information
Type: unhandled exception
File: path.js, line 28, col 5
Message: Uncaught The "path" argument must be of type string
Stack: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string at assertPath (path.js:28:11) at Object.join (path.js:489:7) at Object.ǃg.ǃvA.ǃrIx (https://editor.construct.net/r93/main.js:2:239028) at Object.ǃg.ǃAh.ǃrIx (https://editor.construct.net/r93/main.js:2:246657) at e.ǃNjX.ǃNOY (https://editor.construct.net/r93/main.js:74:207991) at e.ǃNjX.ǃNOJ (https://editor.construct.net/r93/main.js:74:207489) at e.ǃNjX.ǃNFb (https://editor.construct.net/r93/main.js:74:206664) at e.ǃNBU.ǃNBa (https://editor.construct.net/r93/main.js:74:148641) at ǃg.ǃrZ.ǃNy.ǃNvY.ǃgb (https://editor.construct.net/r93/main.js:74:71741) at ǃg.ǃrZ.ǃNy.ǃNvY.ǃNBS (https://editor.construct.net/r93/main.js:74:70725)
Construct 3 version: r93
URL: https://editor.construct.net/r93/
Date: Mon Mar 26 2018 19:32:02 GMT+0300 (Turkey Standard Time)
Uptime: 12.1 s

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r93 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 755M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by DiegoScirra** [comment]
Should be fixed in r94
