### ISSUE TITLE
9-Patch is being rendered as multiple overlapping images

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1433]
## Problem description

Currently the 9-Patch object is being rendered as multiple overlapping images, so if you lower the opacity of the object, the result will not be "flat".

Here's an image showing the difference between a sprite and a 9-patch with 50% opacity.

https://i.imgur.com/89w7jvp.png

## Attach a .c3p

[9PatchBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1849240/9PatchBug.zip)

## Steps to reproduce

1. Add a 9-Patch object.
2. Lower it's opacity.

## Observed result

Multiple overlapping images.

## Expected result

A flat image.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Try setting the 'Seams' property to 'Exact'. There is a deliberate 1px overlap by default to ensure seamless edges, but this doesn't look right with opacity, so you need to change the mode in that case.
