### ISSUE TITLE
Middle-clicking tabs pastes clipboard contents in text editors

### ISSUE THREAD

**Issue by Ludonaut** [Scirra/Construct-3-bugs#1435]
## Problem description

Minor UI bug: When closing editor tabs with a Middle Click while a text editor tab is in focus, the middle-clicked tab will close but the text editor will paste clipboard contents at the same time.

Both are intended results of middle clicks ([as they, while not standardized, often are associated with tab and paste behaviour](https://lifehacker.com/the-many-things-you-can-do-with-a-middle-click-on-your-1565756062)), but the latter should be prevented when closing tabs.

## Attach a .c3p

[middle click bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1853029/middle.click.bug.zip)

## Steps to reproduce

1. Copy some text into your clipboard
2. Middle-click either the Layout 1 or Event Sheet 1 tabs while New File.txt is in focus

## Observed result

Tab closes, text is pasted.

## Expected result

The tab should close but clipboard contents should only be pasted if the middle click happens while the pointer is inside the text editor, not while hovering over the tab bar.

## Affected browsers

* Chrome: yes

**Comment by Ludonaut** [comment]
Oh, I guess I forgot to mention it. Yes I am using Linux and it's pretty much a default keybinding in various Desktop Environments / Window managers I've used over the years. (Maybe it's built into Xorg even? I'm not sure about the specifics). Gnome definitely has it, Budgie as well (I can even disable it, see Tweak Tool screenshot below). [It's mentioned in this freedesktop.org spec on clipboards FWIW](https://specifications.freedesktop.org/clipboards-spec/clipboards-latest.txt).

![image](https://user-images.githubusercontent.com/932664/38382271-b38ea4f6-3909-11e8-91fe-233e593ef43e.png)

If there's no easy way for you to reproduce and fix the issue I'll understand. It's just something I had noticed and I thought it may count as a bug. :)

**Comment by shortercode** [comment]
I haven't been able to reproduce this, I havent got a linux box setup to test this at the moment. I did give it a go on firefox ( win10 ) with it's middle click to paste option but it doesn't seem to cause the issue. 

I've put a change in which I'm hoping will block the pasting, if it doesn't then I'm not sure there's much I can do other than complain to the chrome team.

**Comment by AshleyScirra** [comment]
r108 is out now, please check again!

**Comment by Ludonaut** [comment]
I just checked (Linux / Firefox 60 & Chrome 66) and middle clicking tabs won't paste clipboard contents anymore. It's fixed!

Thank you for your efforts.

**Comment by AshleyScirra** [comment]
Thanks for confirming.
