### ISSUE TITLE
Construct 3 not creating .ogg file

### ISSUE THREAD

**Issue by IJCT95** [Scirra/Construct-3-bugs#1438]
## Problem description
when importing a .wav file, construct 3 is not creating an .ogg file and iOS users cant listen to any sound file.
*Enter a concise description of your problem here*
i was creating a game, i imported a .wav file, i tried to test it on an iphone and no sound was playing,i found out that only .WEBM files were on the project, not OGG.
## Attach a .c3p
not needed
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.right click sounds file
2.add sound
3.DRAG the file

## Observed result
no .ogg file is generated
*What do you see happen?*
only .webm files are created.
## Expected result

*What did you expect to happen instead?*
both .webm and .ogg files should appear.

**Comment by AshleyScirra** [comment]
This is by design. See this blog post: https://www.construct.net/blogs/construct-official-blog-1/opus-audio-in-construct-3-891

WebM Opus audio should be playable on all platforms. Please file a bug report following all the guidelines if you have trouble with that.
