### ISSUE TITLE
Exported html5 game doesn't work on iPad2

### ISSUE THREAD

**Issue by dzibus** [Scirra/Construct-3-bugs#144]
## Problem description

Can't run exported html5 game on iPad2 in latest Chrome version (57.0.2987.137) or Safari, but it runs on Android (Huawei P8 Lite).

## Steps to reproduce

1. Export project as Web (HTML5) with only "Minify script" option selected
2. Upload it to a server
3. Open the web page on iPad2

## Observed result

The exported project just loads css markup and nothing else.

## Expected result

It should load the game without any problems, since it loads Construct 2 projects with ease.

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Safari: yes

**Comment by AshleyScirra** [comment]
What export options are you selecting? Please include everything in the reproduction steps so we can follow exactly what you're doing.

**Comment by dzibus** [comment]
I've edited the issue to be for export only. The export option is not important, I've included it because I thought they might be related.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r25.
