### ISSUE TITLE
Resized sprites are extremely blurry in animation editor at first

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1440]
## Problem description

Resized (down-scaled) sprites are initially extremely blurry inside the animation editor. But this is only after the initial resize, and only in the animation editor. The final result isn't as blurry as it appears.

(This is a different issue than the one reported about the resize algorithm being less than ideal for pixel art - bicubic vs. nearest point, etc.)

## Attach a .c3p

[ResizeBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1853785/ResizeBug.zip)

## Steps to reproduce

1. Create a sprite with some art in it.
2. Open the sprite in the animation editor and scale it down with the resize tool.

## Observed result
The initial resize is very blurry. Then in the layout it looks better. Then after reopening it in the animation editor it still looks better (although some blurriness has been introduced through the resize algorithm as described in #1437).

Initial resize:
![1-initialresize](https://user-images.githubusercontent.com/28039905/37993994-01c8a9ec-31c5-11e8-925b-c83c3d108ee8.jpg)

Same sprite in the layout after being resized:
![2-samespriteinlayout](https://user-images.githubusercontent.com/28039905/37993995-01e0a4ca-31c5-11e8-92b1-a54894eaae45.jpg)

Same sprite after being reopened in the animation editor:
![3-samespritereopenedinanimationeditor](https://user-images.githubusercontent.com/28039905/37993996-01f42f9a-31c5-11e8-82eb-b59bee7d0d2c.jpg)

## Expected result

The resized sprite should look exactly the same in the animation editor as it does in the layout.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r93.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 280 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Is this an up-scaling or a down-scaling issue?

**Comment by Scoremonger** [comment]
This is for down-scaling. I didn't actually check up-scaling though, so it might be an issue there too I guess. Sorry for the lack of specificity there!

**Comment by DiegoScirra** [comment]
Can you post the image you used as an example in the issue?  Also, to what size are you down scaling?

I just want to do exactly the same thing you are doing to see if I am making any progress.

**Comment by DiegoScirra** [comment]
Fixed in r95.

The animations editor and layout images should now be consistent.
