### ISSUE TITLE
High DPI-display poor performance (on mobile)

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#1444]
## Problem description

While executing bigger, or even medium size projects, i turned "High DPI-display" on, and tested the game on my Samsung Galaxy Note 4, it looked very well, but the performance was just poor.

Apologies for my "english", Not my first language.

## Attach a .c3p

Provided to the support.

## Steps to reproduce

1. Enable High DPI-display in the project settings.
2. Test on mobile device
3.

## Observed result

Poor performance on mobile.

## Expected result

Works smooth.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This setting simply increases the rendering resolution, which asks the GPU hardware to do more work, requiring more GPU bandwidth required for rendering, so overdraw-heavy games can suffer from enabling it. This is almost certainly a hardware limitation so it's unlikely there's anything we can do about it.

**Comment by Ind1eed** [comment]
Okay :) Thanks for quick respond.

2018-03-28 17:10 GMT+02:00 Ashley (Scirra) <notifications@github.com>:

**Comment by AshleyScirra** [comment]
I checked the project sent and it appeared to run fine on a Samsung Galaxy Tab S2. Additionally the symptoms sound like a hardware limitation. I don't think there's anything for us to do about this so closing.
