### ISSUE TITLE
Dark Theme: Add Behaviour/Effect Button not working right on the edges

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1446]
## Problem description

*Enter a concise description of your problem here*
See steps to reproduce

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. In dark theme (dont know if it also happens in light theme) create a sprite
2. click Behaviours/Effects on the left -> Behaviour/Effect Window opens
3. click in the middle of the button Add new Behaviour/effect -> Add Behaviour/Effect window opens
4. now cancel and instead click on the edge of the button -> Window doesnt open (button will be white when you click). If you double click it works (Window opens)

Edit: the same with Add Instance Variable Button

## Observed result

*What do you see happen?*
Window doesnt open when clicking on the edge of the buttons

## Expected result

*What did you expect to happen instead?*
Window does open when clicking on the edge of the buttons

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
@Animmaniac - looks like the click event only works on the <a> inside the <div>, but the button styling is on the <div>, so it doesn't always receive click events. I suppose you just need to move the button styling to the <a> instead.

**Comment by Animmaniac** [comment]
Fixed for the next theme release.
