### ISSUE TITLE
Continuous bucket checkbox.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1447]
## Problem description

Continuous bucket checkbox like in Aseprite.

![image](https://user-images.githubusercontent.com/2965842/38103495-20624bda-338f-11e8-8d30-e7bffac9ab9d.png)

**Comment by AshleyScirra** [comment]
It's not clear why you filed this issue. Please note feature requests should be posted here: https://construct3.ideas.aha.io/

**Comment by bilgekaan** [comment]
@DiegoScirra told me in https://github.com/Scirra/Construct-3-bugs/issues/1320#event-1546227870
