### ISSUE TITLE
Chrome does not display some scrolling bar arrows correctly when using a Theme

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1450]
## Problem description

Using the Light and Dark themes in Chrome, some scrolling bar arrows do not display appropriately compared to FireFox or Default.

## Attach a .c3p

None requirred

## Steps to reproduce

1. Open C3 with a theme.
2. Add a sprite
3. Check out the "Animation speed" field

## Observed result

In chrome, using dark or light : No arrows on mouseover or naturally.

## Expected result

Arrows on mouseover (like for the default) or naturally (like in FF).
The only way to change a value is to click the field and write it down, or click the field and use the mousewheel (unpratical, does not always update changes appropriately).

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: not tested
* Safari: not tested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 12 gb
Storage usage (approx): 777 mb (6.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I suspect one of the styles applied by the theme overrides the appearance of the spinner arrows in the number field. Assigning to @Animmaniac to take a look, but sometimes adding any kind of customisation causes the browser to revert to a basic control with minimal features, so it might not be possible to fix.

**Comment by AshleyScirra** [comment]
(Issue had wrong labels) Unfortunately CSS doesn't directly control whether the spinners appear, and generally if any appearance customisations are applied then browsers fall the element back to a basic version, so I don't think there's anything we can do about it. It's a minor feature anyway.
