### ISSUE TITLE
Stop loop does not stop all kinds of loops

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1451]
## Problem description

I noticed that "stop loop" does properly stop a "for" loop aswell as a "Repeat" loop, but does not stop a "For each instance" or "For each XY" (array) loop.

🥚 

## Attach a .c3p

[stoploopbug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1864477/stoploopbug.c3p.zip)

## Steps to reproduce

1. Use a "For each" loop
2. Use stop loop at any point while the loop is running

## Observed result

The loop continues regardless of the stop loop.

## Expected result

The loop to actually stop.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 210 mb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
"Stop loop" does work with "For each instance". Since there are lots of off-screen instances, each iteration will cycle through those instances picking them, and the "overlap" condition will only test if it's overlapping that one instance. If you clone the barrier and test overlap with a different instance to the one being iterated, you'll see it works correctly.

The 'Stop loop' action only stops System loops, currently this is by design, so it won't stop an Array loop.

**Comment by Wackytoaster** [comment]
Ah, this makes sense. An option to stop array loops would be nice to have in that case, but I can work around that. Either way, I´d update the description of stop loop then since it does not stop **any** currently running loop, just to clear up potential confusion.
![except](https://user-images.githubusercontent.com/31101309/38407065-54419c6e-3978-11e8-8cec-ec480e5de0d7.PNG)

Thanks!
