### ISSUE TITLE
Preview rendering use negative default brightness

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#1455]
## Problem description

When I make a preview of an Animation in Animations editor, the background is the negative of the brightness defined

## Steps to reproduce

1. Make a preview of a sprite animation

## Observed result

Negative background

## Expected result

Same defined background

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

**Comment by AshleyScirra** [comment]
No project provided so tested Ghost Shooter. Cannot reproduce any problem - the animation preview for the Player always uses the same background lightness as the main editor setting. Please follow all the bug report guidelines to ensure we can investigate the issue.

**Comment by Picoti** [comment]
Hello. I found the problem. It happen only in Dark Theme.
