### ISSUE TITLE
Image point problem after cropping whole animation

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#1456]
## Problem description

After cropping a whole animation (SHIFT + CROP), the function APPLY to whole ANIMATION doesn't work properly.

## Attach a .c3p

[Test (4).zip](https://github.com/Scirra/Construct-3-bugs/files/1866512/Test.4.zip)

## Steps to reproduce

1. Open the "HAT" object
2. CROP an animation
3. Move the image point of a Frame
4. Use function "Apply to whole animation"

## Observed result

Image point of whole animation are not changing.

## Expected result

Change the Image point on all Frames.

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed in r95
