### ISSUE TITLE
[Firefox] Array editor bugs.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1458]
## Problem description

Several bugs for the Array editor using Firefox. I will list them here as they might be related. 
You can't edit width, can't click height input field, and can't input anything in the array cells.

## Attach a .c3p

N/A

## Steps to reproduce

1. Create a new project using Firefox.
2. Right click "Files" in Project window and add a new Array.
3. Click the width input field to change it. (The field now disappears, and from this point the array editor becomes broken.)
4. Now try to click height field. You can't edit the number, only arrows work.
5. Add some lines using the arrows in the field.
6. Try to add some text in one of the array fields. (Not working)
7. Now try to add a new array while in the array editor.
8. The interface becomes very very slow, and you can't navigate context menus, to add another array.

NOTE: Not doing point 3, and just using the arrows, to change the height and width of the array, the Array Editor will work fine.

## Observed result

Array editor not working in Firefox.

## Expected result

Should work, exactly like in Chrome.

## Affected browsers

* Chrome: no
* Firefox: yes

**Comment by tunepunk** [comment]
No 3. also happens when trying to set number of lines in the Dictionary editor, but if you don't try to change the first size field. you can edit the dictionary cells.

**Comment by shortercode** [comment]
Hmmm yeah I'm not going to lie that looks pretty broken. By the looks of this @DiegoScirra found this and put a fix in last week, but it hasn't seen a release yet. 

Some part of the spinners was causing some serious UI freezing.

Going to mark this as fixed for now, but will double check with him when I see him.

**Comment by DiegoScirra** [comment]
This is fixed in r95
