### ISSUE TITLE
Create new project on Portrait window doesnt work

### ISSUE THREAD

**Issue by IJCT95** [Scirra/Construct-3-bugs#146]
## Problem description
when creating a project a new project and selecting the orientation as "portrait" it wont work
*Enter a concise description of your problem here*
when creating a project a new project and selecting the orientation as "portrait" it wont work

## Steps to reproduce

1. click on new project
2.  select portrait firts in the orientations options and then select anything on "choose preset"
3. click create and observe, the windows is on landscape

## Observed result
the project uses a landscape window

*What do you see happen?*
the project uses a landscape window

## Expected result
the project should be in portrait

*What did you expect to happen instead?*
the project should be in portrait

**Comment by AshleyScirra** [comment]
This is currently by design. Desktop systems don't support changing the display orientation, it only affects mobile devices, and only in certain circumstances.
