### ISSUE TITLE
Safari 11.1 gets stuck on "Rendering spritesheets..."

### ISSUE THREAD

**Issue by KelseyHigham** [Scirra/Construct-3-bugs#1460]
## Problem description

On [Safari 11.1 for Mac and iOS](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html#//apple_ref/doc/uid/TP40014305-CH14-SW1) (bundled with iOS 11.3, and erroneously reported to Construct 3 as "Safari 11.0"), Construct 3 can't render spritesheets larger than 128x128. This prevents
- sprites rendering in the layout window
- downloading a local copy of the game
- previewing the game

## Attach a .c3p

I can't download a copy from Safari due to this bug. I was able to save to Dropbox, and I've attached that. It's just one 250x250 sprite in the default layout.
[One sprite.zip](https://github.com/Scirra/Construct-3-bugs/files/1873202/One.sprite.zip)

## Steps to reproduce

1. Create a new project with one sprite that's 128x128 or larger, and place the sprite in the layout
2. *(Mac only)* Try to Save > Download a copy
3. Try to Preview

## Observed result

1. The sprite doesn't render in the Layout view. The UI status indicator reads "Rendering spritesheets (1 remaining)..."
2. *(Mac only)* When trying to 'Download a copy', a popup briefly appears that says "Working (0%)", then disappears. Nothing else happens; nothing is downloaded. The UI status indicator still reads "Rendering spritesheets (1 remaining)..."
3. When trying to Preview, a popup appears that reads "Preparing images (0%)...". The UI status indicator changes to "Rendering spritesheets (2 remaining)...". It's impossible to get out of this state without closing Construct.

## Expected result

1. The sprite should eventually render in the Layout view.
2. *(Mac only)* The project should eventually save
3. The project should eventually preview.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: *unknown*
* Safari: yes

## System details

This is with the Free edition, and the problem occurs whether logged in or logged out. 

### iOS
<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: webapp
Operating system: iOS
Operating system version: 11.3
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A9 GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 22050 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

### 1st Mac (Sierra)
<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.1
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (2.1 INTEL-10.25.17)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 540
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_blend_minmax
EXT_sRGB
EXT_frag_depth
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBGL_compressed_texture_s3tc
WEBGL_depth_texture
WEBGL_draw_buffers
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

### 2nd Mac (Sierra)
<details><summary>View details</summary>
Platform information
Browser: Safari
Browser version: 11.1
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (2.1 INTEL-10.25.17)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_blend_minmax
EXT_sRGB
EXT_frag_depth
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBGL_compressed_texture_s3tc
WEBGL_depth_texture
WEBGL_draw_buffers
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)
</details>

### 3rd Mac (Sierra)
<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.1
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (2.1 ATI-1.51.8)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon HD 6970M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_blend_minmax
EXT_sRGB
EXT_frag_depth
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBGL_compressed_texture_s3tc
WEBGL_depth_texture
WEBGL_draw_buffers
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

### 3rd Mac again (now High Sierra)

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.1
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (2.1 ATI-1.51.8)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon HD 6970M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_blend_minmax
EXT_sRGB
EXT_frag_depth
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBGL_compressed_texture_s3tc
WEBGL_depth_texture
WEBGL_draw_buffers
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by KelseyHigham** [comment]
I literally just open editor.construct.net and it doesn't work, and hasn't since updating to 94.2 (though that might be a coincidence). I'm on the Free Edition, and the problem occurs whether I'm logged out or logged in, and it still occurs after I clear Safari's local storage for construct.net. It occurs on both my home and work Internet connections. 

I've attached details from a second Mac the problem occurs on. Neither of my Macs are on High Sierra, but my iPhone is up-to-date, so I doubt that's the source of the problem. Still, I'll try to find a machine running High Sierra to test on.

Are there any other steps I should try to narrow down the problem? I'm comfortable with the command line, the Web Inspector, and other relevant dev tools. Is there a way to test out other releases of Construct 3 to see if it's this version that's causing the problem?

**Comment by KelseyHigham** [comment]
A few findings:
1. On the machines I tested, the problem occurs with all versions of Construct 3, not just 94.2, which tells me that it's probably a Safari issue, and it probably started when I updated iOS 11.2 -> 11.3, not when Construct 3 updated.
2. The above results occur when I create one image larger than 128x128. The below results occur when I create two images, 128x128 or smaller. The second one causes a crash.

I'll clean up this information later.

## Steps to reproduce
1. New project
2. Create a sprite, 1x1, and place it in the layout
3. Create a sprite, 1x1, and place it in the layout
4. Crash:

### 1st Mac crash report (Sierra)
<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r94-2/main.js, line 63, col 706137
Message: Error: image sprite collection needs rebuilding
Stack: ǃXx@https://editor.construct.net/r94-2/main.js:63:706093 ǃXK@https://editor.construct.net/r94-2/main.js:63:1036535 ǃXN@https://editor.construct.net/r94-2/plugins/sprite/plugin.js:1:9369 ǃXN@https://editor.construct.net/r94-2/main.js:63:803548 ǃXN@https://editor.construct.net/r94-2/main.js:63:842996 ǃXN@https://editor.construct.net/r94-2/main.js:63:827299 ǃvW@https://editor.construct.net/r94-2/components/editors/layoutView/layoutView.js:1:7176 ǃva@https://editor.construct.net/r94-2/components/editors/layoutView/layoutView.js:1:1812
Construct 3 version: r94.2
URL: https://editor.construct.net/
Date: Wed Apr 04 2018 17:53:52 GMT-0700 (PDT)
Uptime: 27.1 s

Platform information
Browser: Safari
Browser version: 11.1
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
C3 release: r94.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (2.1 INTEL-10.25.17)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 540
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_blend_minmax, EXT_sRGB, EXT_frag_depth, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_standard_derivatives, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context, WEBGL_compressed_texture_s3tc, WEBGL_depth_texture, WEBGL_draw_buffers, ANGLE_instanced_arrays, WEBGL_debug_renderer_info
</details>

**Comment by AshleyScirra** [comment]
Can reproduce on Safari 11.1. Already fixed the crash, looking in to the hang on building spritesheets now.

**Comment by AshleyScirra** [comment]
This is a severe bug in Safari 11.1. I've filed it here: https://bugs.webkit.org/show_bug.cgi?id=184502

Unfortunately we may not be able to work around this in the mean time - it looks like a fundamental messaging API is simply not working. Hopefully Apple will identify and fix this quickly, but their track record on that is not great...

**Comment by AshleyScirra** [comment]
The Safari bug is not yet fixed, but we've added a workaround in r95 to avoid the problem. Can you confirm it's working in r95?

**Comment by KelseyHigham** [comment]
The workaround works for me on my **iOS** and **1st Mac (Sierra)** systems!
