### ISSUE TITLE
Mouse Cursor is not actually where it is supposed to be.

### ISSUE THREAD

**Issue by darthbinks911** [Scirra/Construct-3-bugs#1461]
## Problem description

When in editor mode, mouse cursor selection randomly sets at a 45 degree angle, and 200 pixels away, so your cursor is not actually where it should be on the screen. If you drag the mouse, the selection is highlighted at the position and measurements stated above. Closing the layout tab and reopening does not help. Only closing the browser helps. 

## Attach a .c3p

This happens randomly on many different projects I have, it takes a random amount of time to manifest, I don't believe it's a project bug.

## Steps to reproduce

1. Use Google Chrome
2. Start editing your project
3. Eventually the mouse cursor will set at a 45 degree angle and 200 pixels away, so if you drag to highlight, it will not highlight at exactly where the cursor is, but a small distance away.

## Observed result

While you are moving the mouse cursor, you can only select things or highlight things by "guessing" where the mouse cursor actually is. In this case, at a 45 degree angle, and 200 pixels away(if I forgot to mention that again). This only happens on layouts. Event sheets are unaffected, as well as the startup page.

## Expected result

The mouse cursor should go exactly where I point, not at a 45 degree angle and 200 pixels away.

## Affected browsers

* Chrome: yes
* Firefox: unsure
* Edge: unsure
* Safari: unsure

## System details

No bug report.

**Comment by AshleyScirra** [comment]
This sounds like it would come up in normal usage, but I've never seen it, nor have we ever seen any other reports from other users. I'm afraid there is nothing we can do to investigate it unless you can find some steps to follow to reliably reproduce the issue.
