### ISSUE TITLE
Function param lost after wait sec used

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#1462]
## Problem description

When you call a function with param(0) value and with a [wait x secs] in the function called, following a get value of the param(0) will result in nothing. The function seems to not hold the param values after a [wait x secs] in it. Is this by design?

## Steps to reproduce

1. Create a Global variable.
2. Create a [on Function] --> [wait(x) secs] then a [set value] of the global variable to Function.param(0)
3. Create an event trigger, on start of layout --> call function with param(0) any value.

## Observed result

Does not remember the value of param(0).

## Expected result

Should still retain the value of param(0).

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.2 gb
Storage usage (approx): 296 mb (4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
This is a known limitation of the runtime.

The short answer is that the function finishes when wait is called, so the parameters don't exist when it continues.

The long answer is that the "Function" object uses a stack of scopes. When a function is called inside the current function a new scope ( parameters etc. ) is **pushed** onto the stack and when the current function finishes it's scope is **popped** off the stack. Calling wait is the same as finishing the function, so the stack **pops** back up the chain losing all the scopes. When "wait" continues the stack is empty so there's no parameters

We have talked about it, and it's something we'd like to change in future. But I'm not attaching any ETA or promise to this; it may not be feasible or it could have some excessive performance hit that means we don't include it.
