### ISSUE TITLE
[NW.js Export] User-Agent Is Causing Certain Features To Fail

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1463]
## Problem description

I've recently found out that the current user-agent found inside the package.json manifest that ships with both C2 and C3 exports can cause certain features to not work properly. (Example: https://github.com/nwjs/nw.js/issues/6512)

## Attach an example

**Includes:** package.nw folder for reproduction, 2 manifest files with different user-agents.
[User Agent Issue.zip](https://github.com/Scirra/Construct-3-bugs/files/1875672/User.Agent.Issue.zip)

## Steps to reproduce

**Main reproduction cycle:**

1. Download and unpack files
2. Download NW.js with at least M65 or newer
3. Rename "package (Broken).json" to "package.json"
4. Put _package.json_ into _package.nw folder_ then move it into your _NW.js source folder_
5. Run _NW.exe with the example_* and notice that the haptic feedback feature doesn't work properly
6. Repeat steps 3-5 with "package (Works).json" and notice that this user-agent works fine

***How the example works:**

1. Test haptic feedback using a controller that supports it (e.g. XBox 360 gamepad)
2. Connect gamepad and press button, it should be automatically selected on the top-left
3. Fill in the required information (e.g. 0 | 1.0 | 1.0 | 1000)
4. Click on "rumble" button

## Observed result

The current user-agent inside C2/C3 exports seems to be outdated and is causing problems with certain features of the web (especially experimental ones).

## Expected result

The user-agent shouldn't cause any of these problems and I'd recommend it to be updated to the one I provided or completely removed since NW.js defaults seem to take care of it anyway.

## Affected browsers

* NW.js: yes
* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

**Comment by AshleyScirra** [comment]
The haptic feedback feature is experimental. Experimental features are frequently buggy or missing support in certain circumstances. Consequently I would prefer not to investigate issues with experimental features until they are at least enabled by default on the Canary release channel.

**Comment by TheRealDannyyy** [comment]
Alright no problem.
Could you maybe tell me if C2/C3 games require the current user-agent for something to work right?

I've replaced the current one with the one you're using inside C3 Desktop releases and everything including the experimental feature mentioned here work fine.

**Comment by AshleyScirra** [comment]
A lot of web content, including our engine, uses the user agent to determine some platform-specific details, particularly work-arounds to platform specific bugs. We also use a custom user agent in NW.js for the engine to identify if it is running in NW.js. So in general you should not modify the user agent from the one Construct specifies, and changing it could indeed break things.

**Comment by TheRealDannyyy** [comment]
Ok good to know, thanks.
