### ISSUE TITLE
Particles can have more than 100% opacity

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1466]
## Problem description

In the "initial particle properties" tab you can set the initial opacity to be more than 100%, which doesn't make much sense. The result look like more than one particle on top of each other, which make the image look brighter than what it should.

## Attach a .c3p

[Particles Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1880008/Particles.Bug.zip)

## Steps to reproduce

1. Create a particles object.
2. Add any image to it.
3. Set the opacity to be more than 100% in the "initial particle properties" tab.

## Observed result

A brighter image on each particle.

## Expected result

The opacity field to lock the value between 0% and 100%.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.

**Comment by BonzerKitten7** [comment]
No problem. Thank you, Ashley! :)
