### ISSUE TITLE
Cannot edit images in editor with FF - C3 hangs

### ISSUE THREAD

**Issue by DudetteonTheEdge** [Scirra/Construct-3-bugs#1467]
I have tried several times to edit an image in the image editor and each time C3 hangs. I tried several times to make a button from scratch and then some other times to edit an image in the editor. same result.

just 2 sprites and one text - an added sprite to edit prevented saving further whether it is an image to edit or a sprite image created in editor. I am uploading the capx with the image after reloading the capx and no editiong anything in it. 

[randomStart.zip](https://github.com/Scirra/Construct-3-bugs/files/1881161/randomStart.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. create empty sprite
2. draw on it
3. try to save and return to stage

## Observed result
C3 hangs
*What do you see happen?*
just the wait mouse icon and I cannot do anything else besides killing it by leaving the page
## Expected result

*What did you expect to happen instead?*
save and return to stage
## Affected browsers

* Chrome: no
* Firefox: yes
* Edge: not tried
* Safari: not tried

## System details
WINDOWS 10
*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*
No crash report
<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
That's pretty odd, thanks for the report anyway @DudetteonTheEdge hopefully it stays working!

**Comment by DudetteonTheEdge** [comment]
Well it is still happening on a regular basis in any project. You go into draw mode and then it just won't let you save. Sorry it waited to update but I was working on other projects.  Again this is a FF problem.

**Comment by AshleyScirra** [comment]
If you still have trouble please identify reliable steps to reproduce the issue then file a new issue following all the guidelines.
