### ISSUE TITLE
Animations Editor - Alpha settings bugs

### ISSUE THREAD

**Issue by oosyrag** [Scirra/Construct-3-bugs#1470]
## Problem description

Alpha settings behave oddly.

A. After setting an alpha value (ie. 100), when setting another color by text, the alpha when drawing is 255, but the value in the input box remains 100.

B. When switching to a size 1 OR 2 eraser after drawing with a brush or pencil at not full alpha (ie. 100), the eraser is also set to that alpha amount. Changing the alpha input while on the eraser tool does nothing. This does NOT effect eraser size 3 or higher.

## Attach a .c3p

N/A

## Steps to reproduce

A:
1. Create and place sprite object.
2. Select a color (255,0,0), set alpha to 100
3. Draw on canvas
4. Change color via input boxes (0,255,0), leave alpha at 100
5. Draw on canvas

B:
1. Create and place sprite object.
2. Select a color (255,0,0), set alpha to 100
3. Draw on canvas
4. Change to eraser, set size to 1 or 2 if it isn't already. Erase something. (1 hardness)
5. Change alpha input to 255, Erase something. 

## Observed result
A: First color drawn at 100 alpha, second color drawn at 255 alpha.

B: Changing to eraser size 1 or 2 will inherit alpha value of previously used tool. Changing alpha when eraser selected does nothing. Size 3 and up is always erased completely. (1 hardness)

## Expected result

A: Second color drawn at 100 alpha, OR alpha input updated to 255 (the latter happens when picking a color via the picker)

B: Not sure what the desired behavior is here. Either have the eraser tool consistently respect alpha value or not.

## Affected browsers

* Chrome: yes
* Firefox: unknown
* Edge: unknown
* Safari: unknown

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 28 gb
Storage usage (approx): 244 mb (0.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Both of these issues have been fixed in r97.

For the first one the alpha channel is not respected when changing a color using the number inputs.

The eraser tool is now consistent in that it never uses the alpha value.
