### ISSUE TITLE
Crash with event sheet in separated window

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#1471]
## Problem description

C3 crashes when an event sheet project is moved in a new window and a new condition is inserted in it.

## Attach a .c3p

Just en empty .c3p to test but it occurs with any project.
[bug-event-sheet.zip](https://github.com/Scirra/Construct-3-bugs/files/1883228/bug-event-sheet.zip)

## Steps to reproduce

1. Open the c3p file
2. Go to the event sheet
3. Drag the sheet outside the window (to open it in a new window)
4. Insert a new condition in the even sheet

## Observed result

C3 crashes (cf. message in System details).

## Expected result

The usual behavior (no crash).

## Affected browsers

* Chrome: yes
* Desktop: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃq.ǃqt (https://editor.construct.net/r94-2/main.js:2:108833) at Function.ǃRDm (https://editor.construct.net/r94-2/main.js:2:224806) at Function.ǃRDA (https://editor.construct.net/r94-2/main.js:2:224235) at ǃq.ǃS.ǃU.ǃhUs.ǃRqh (https://editor.construct.net/r94-2/main.js:155:118090) at window.ǃhSq.ǃRqh (https://editor.construct.net/r94-2/main.js:155:122997) at ǃq.ǃS.ǃU.ǃhUY.ǃ$e (https://editor.construct.net/r94-2/main.js:155:141602) at o (https://editor.construct.net/r94-2/main.js:155:109677) at n (https://editor.construct.net/r94-2/main.js:155:109070) at t (https://editor.construct.net/r94-2/main.js:155:108918) at n.then (https://editor.construct.net/r94-2/main.js:155:108974)
Stack: TypeError: unexpected type at Function.ǃq.ǃqt (https://editor.construct.net/r94-2/main.js:2:108833) at Function.ǃRDm (https://editor.construct.net/r94-2/main.js:2:224806) at Function.ǃRDA (https://editor.construct.net/r94-2/main.js:2:224235) at ǃq.ǃS.ǃU.ǃhUs.ǃRqh (https://editor.construct.net/r94-2/main.js:155:118090) at window.ǃhSq.ǃRqh (https://editor.construct.net/r94-2/main.js:155:122997) at ǃq.ǃS.ǃU.ǃhUY.ǃ$e (https://editor.construct.net/r94-2/main.js:155:141602) at o (https://editor.construct.net/r94-2/main.js:155:109677) at n (https://editor.construct.net/r94-2/main.js:155:109070) at t (https://editor.construct.net/r94-2/main.js:155:108918) at n.then (https://editor.construct.net/r94-2/main.js:155:108974)
Construct 3 version: r94.2
URL: https://editor.construct.net/
Date: Fri Apr 06 2018 10:28:04 GMT+0200 (Paris, Madrid (heure d’été))
Uptime: 533.9 s

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r94.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Thanks for the report, I've fixed this for r95.

**Comment by sebastien-c3** [comment]
Thanks a lot Iain. :)
