### ISSUE TITLE
Construct 3 Desktop - NW.js "Mac64" Export Is Causing An Unknown Error

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1474]
## Problem description

Using Construct 3 Desktop (stable branch) exporting with NW.js "Mac64" as a selected platform is causing an unknown error.

## Attach a .c3p

Any project, in my case the KiwiStory example.

## Steps to reproduce

1. Use a clean version of C3 Desktop without NW.js already downloaded and installed
2. Open the example project and export with "Mac64" selected
3. Notice that the exporting process fails for an unknown reason

## Observed result

The exporting process fails because of "Mac64" being selected. I'm using the latest NW.js v0.29.0 release. 
(The messages on the bottom left stay there forever, complete restart is required in order to remove them.)

![errormsg](https://user-images.githubusercontent.com/15656049/38502980-2dc5caba-3c11-11e8-9825-558c12d9c75c.PNG)

Console gives out the following:
![nwjsconsoleerror](https://user-images.githubusercontent.com/15656049/38503213-caaa0d46-3c11-11e8-95eb-cab1d9a39221.PNG)

## Expected result

Construct 3 Desktop should export fine just like it does in Chrome and FireFox.

## Affected browsers

* NW.js Desktop: Yes
* Chrome: no
* Firefox: no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 167 gb
Storage usage (approx): 19 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here, Kiwi Story exports just fine to mac64 in the desktop build. Does this depend on any other export settings? Are you offline when you export? (You must be online to export)

**Comment by TheRealDannyyy** [comment]
![nw js settings](https://user-images.githubusercontent.com/15656049/38624875-771f9e90-3da9-11e8-97c0-8069b2421a03.PNG)

Those are my settings, I also don't use any deduplication or similar settings. It might also be worth mentioning that only NW.js v0.29.0's mac64 is affected, this works fine for all previous NW.js releases.

**Comment by TheRealDannyyy** [comment]
@AshleyScirra I've further investigated this and I'm pretty sure that there is something going wrong during the downloading process. Construct 3 seems to think that the files are already on disk, despite the database showing that they aren't.

Here is a video of my test using the NW.js download manager:
https://drive.google.com/file/d/1OLDJJGrdw6-hUOQNEkO7i9K0Ia8X2_Ly/view?usp=sharing

I guess if there is nothing you can do and it's only me experiencing this issue, I could simply wait for v0.30.0 to be released, which will probably not be affected by this.

**Comment by AshleyScirra** [comment]
Have you tried clearing storage from dev tools and retrying? It might have cached a corrupt or incomplete download or something.

**Comment by TheRealDannyyy** [comment]
Yep, was the first thing I did with no success.

**Comment by TheRealDannyyy** [comment]
Alright I think found a fix. I completely removed the construct3 folder in AppData, now downloading and exporting seems to work fine. I've also tested if closing C3 while and active download is running might have caused this corruption to happen but after 4 tries, C3 is working as expected and continues the download from where it was stopped.

No clue what could've caused this corruption to happen but removing the AppData folder fixes it, might be a good thing to implement a button in the settings menu to "Reset Construct 3" for cases like this.
_(Reset = Completely remove AppData Folder)_
