### ISSUE TITLE
8-direction movement doesn't work properly

### ISSUE THREAD

**Issue by ExedysDigital** [Scirra/Construct-3-bugs#1475]
## Problem description

8-direction seems to have a mind of its own and moves without me pressing anything. Sometimes doesn't move at all. Stops animations from playing also.

Because of the reproduction difficulty I recorded the glitch with my phone so you can see my keyboard and the game.

https://www.youtube.com/watch?v=cOqwoQIhng0&feature=youtu.be&ab_channel=ExedysDigital

## Attach a .c3p

https://mega.nz/#!wv4QHQIR!Q2-K7XpU16qei81te-jx95sEQJAVOPa4-zVhiE8LkW8

## Steps to reproduce

1. Unknown

## Observed result

When pressing the left arrow key once the character kept going till it hit the tilemap then go back to the right of the tilemap and then stop moving.

## Expected result

The character to only move once.

## Affected browsers

* Chrome: yes/no
* Firefox: untested
* Edge: untested
* Safari: untested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r90 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 123 gb
Storage usage (approx): 1.2 gb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Have you been able to reproduce this with the example project you gave? Also do you have any alternative input devices connected? ( Gamepads etc. ). Other than the expected behaviour I didn't see anything strange, and other typical 8 direction games seem to be working fine.

Just looking at the game in your video it seems a lot more complicated, and I was wondering if you are using simulated 8 direction for the enemies? If so it could be that your logic is affecting the player?

**Comment by ExedysDigital** [comment]
No I wasn't able to reproduce this with the example project but I had to attach a .c3p file. No the only input devices connected and in my project is my keyboard and mouse. The enemies use the Bullet behavior for their movement so I don't think it could interfere with the player movement.

**Comment by ExedysDigital** [comment]
If needed I could provide the file for my entire project and you could see the difference to the normal behavior.

**Comment by AshleyScirra** [comment]
The 8 direction behavior is mature, is used in thousands of projects, and we have never seen any such reports over the past years. Therefore if the issue does not reproduce in a new project this is highly likely to just be a mistake in the events of your project, which is very common. Closing.

**Comment by ExedysDigital** [comment]
Ok i just readded 8-direction and that fixed it. sorry for the inconvenience

**Comment by ExedysDigital** [comment]
it wasnt to do with the events so i still have no idea what caused it
