### ISSUE TITLE
Opening files with very long names will cause the editor to extend offscreen

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#148]
## Problem description

So while looking at [bug 143](https://github.com/Scirra/Construct-3-bugs/issues/143) it occurred to me that we may not handle long filenames in tabs very well, turns out I was right and there's some really weird layout bugs with it. I've attached a project with a suitably long name, but it's pretty easy to test.

On mobile and desktop the effect is fairly obvious, part of the editor is stuck offscreen ( at least if your screen width is small enough ). In addition to this I encountered an issue when I tried to rename the long named file and everything was pushed to the left leaving a large chunk of blank screen and the left hand side of the editor stuck offscreen (including the menu button). I also wonder if there needs to be a hard limit on the length of the file name, doesn't windows have a limit on the length of a file path?

## Attach a .c3p

https://www.dropbox.com/s/hsor9tut82094sa/FileNameBug.c3p?dl=0

## Steps to reproduce

1. Open project

## Observed result

On a smaller screen the midPane had a minimum width of the largest tab. Which can push parts of the editor off the screen

## Expected result

To be able to see all of the editor.

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: untested

## System details

N/A

**Comment by AshleyScirra** [comment]
Adding `max-width: 20em` makes this better since the tab doesn't grow beyond 20em and does an ellipsis on the text instead. However that just postpones the problem to 20em, which also causes a problem with the layers bar tab, and in the main view still as well. Ideally we could set a max width of something like `min(20em, 100%)` but I'm not sure if that's supported/would work...

**Comment by AshleyScirra** [comment]
Closing as the worst case of this is basically fixed now, no pressing need to do the shrink-to-fit below 20em.
