### ISSUE TITLE
[edge] Can't edit expressions.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1480]
## Problem description

Entering text in expression fields produces some strange behaviour where you constantly insert characters from the start. 

## Attach a .c3p

N/A

## Steps to reproduce

1. Open any C3 template in edge
2. Go to event sheet and edit a condition or action with an expression.
3. Place cursor at end of the expression, and try to type something.
4. Notice how new characters are placed at beginning of expression, and suggestions don't work.

## Observed result

Strange behaviour when editing expressions using edge.

## Expected result

Should work as in other browsers.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: yes

**Comment by shortercode** [comment]
Ah nice spot, thankfully was pretty easy to fix. The node type constants are only defined on **Node** not **Element** in Edge apparently. Odd compatibility detail that...

Will work correctly in r95.
