### ISSUE TITLE
"Build Failed. Cannot Connect to Build Server."

### ISSUE THREAD

**Issue by lukasinspace** [Scirra/Construct-3-bugs#1481]
## Problem description

Unable to export an Xcode project due to constant failure to connect to build server. 
I export my project for iOS (xcode project) > My project uploads > I get a message saying 'waiting to build' > then a constant loop of 'lost connection' / 'connection restored' for about 10 - 15 minutes until finally I get an error message saying 'Build Failed. Unable to Connect to Server'.

Note I've had successful builds as early as this morning using the process described below. I havent changed anything in the way Im using the build service. 

## Attach a .c3p

[Test.zip](https://github.com/Scirra/Construct-3-bugs/files/1902386/Test.zip)

## Steps to reproduce

1.In C3 > Menu > Project> Export > iOS > Choose xcode project
2.
3.

## Observed result
Messages display saying 'waiting to build', 'connection lost', 'connection restored'.
After about 10 - 15 minutes an error message displays: 'Build Failed. Cannot Connect to Build Server.'
![image](https://user-images.githubusercontent.com/22804707/38669485-de73b6fe-3e89-11e8-8661-04c98a89f4dd.png)

## Expected result

I expected to receive the Xcode project. Or receive a report of what the problem could be?

## Affected browsers

* Chrome: Yes
* Firefox: Yes
* Edge: Yes
* Safari: Unsure

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 6.8 gb
Storage usage (approx): 385 mb (5.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Thanks for the report @lukasinspace I'm looking into it now.

The build queue has locked up on one of the build processes, so some builds will still be succeeding I'm sorry if this has caused you any inconvenience. I'll manually clear the queue which should workaround this, but it's not clear why it has locked up.

**Comment by lukasinspace** [comment]
Hi thanks for the response. I can confirm the build service is working again for me now. Ive been able to get several successful xcode builds from it. Thnx

**Comment by shortercode** [comment]
So the latest version of the build service had a lot of revisions, which I'm hoping have solved the root cause of this bug. But in addition I've added a mechanism to prevent this from locking the server up, so hopefully we've seen the last of this!
