### ISSUE TITLE
Cannot change properties with export manager

### ISSUE THREAD

**Issue by rasty6557** [Scirra/Construct-3-bugs#1483]
Cannot choose export an apk or android studio project with export manager.
But narmal in origin c3 project.

export manager
![2018-04-12 00 34 00](https://user-images.githubusercontent.com/37333617/38682066-c47523b0-3e9c-11e8-8209-651c196afa12.png)

c3 project
![2018-04-12 21 56 55](https://user-images.githubusercontent.com/37333617/38682081-cbbd2154-3e9c-11e8-8206-ea91b52b495c.png)

Platform information
Browser: Chrome
Browser version: 64.0.3282.186
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by rasty6557** [comment]
“by this point the user will have already specified the properties”
This situation happened in export c2 project in c3, and in that moment user have not make any specified the properties.
They just can click the next button and export cordova project only.

**Comment by shortercode** [comment]
When you export from Construct 2 you get the options for versions, permissions, status bar etc. and that's included in the cordova export. 

I made some changes around a month or so back, but at the moment I'm seeing the 2 drop downs for Android target and iOS target when I try to build a C2 project. The only things missing is the whitelist option, but I don't think that many people use that anyway.
