### ISSUE TITLE
Support Expansion APKs on Android Export

### ISSUE THREAD

**Issue by phillnexus** [Scirra/Construct-3-bugs#1488]
## Problem description

As per this topic:

https://www.scirra.com/forum/viewtopic.php?f=191&t=202793

My game / logic / sprites are maybe a few MB. The videos I have are maybe 600MB (40 minutes worth, webm). By the time I am finished I imagine there will be over 1GB of video.

## Steps to reproduce

1. Create a game that is 600MB in size
2. Try to publish via Cordova/Android

## Observed result

Build failed, exceeded maximum project size

## Expected result

A working build

**Comment by shortercode** [comment]
The size cap is mainly to reduce server load but we're open to increasing it.

Unfortunately you will hit another wall even if I increase it; at the moment the APK size limit on Google play is 100MB. It can be worked around with expansion APKs but we don't yet support them.  I increased around a month back from 100MB to 300MB for people building xcode projects, as on iOS the application archive can be up to 4GB.

You can read more about APK expansion files [here](https://developer.android.com/google/play/expansion-files.html).

It's kind of a complicated feature to add as we would need to change how we load every asset in Android and then package them differently. In your case it could possibly be easier to do, given that storing your videos in the expansion file would be sufficient to reduce the main APK file to under 100MB.

**Comment by phillnexus** [comment]
Ok, thanks. So at the moment I assume there's nothing I can do while using Construct 3 to build a debug APK since expansion files are not supported?

**Comment by shortercode** [comment]
Well... It's probably possible to work around it. Do you have any experience with JavaScript?

I believe you could download the video files from a webserver and store them in a indexedDB database. Then when you want to play the video you just need to get the file from the database, create a blob url for it then use that as the video source.

It's a bit of a pain having to download the video files, but if you've read the article you will know that Google Play doesn't guarantee that it will download the expansion file anyway. So anyone using them has to create a "downloading extra assets" screen in case they have to download the file from Google themselves when the app is started.

The major difference is that you would have to find and pay for hosting of the videos ( maybe try Amazon S3 ) and you would need to write the download / cache / load code. The hosting would probably be pretty cheap, as each user would only have to load each video once. But it depends on the number of new users you get.

I can explain some more details if your interested?

If you wanted an easier but poorer solution you could just host the videos on a webserver and stream them each time.

**Comment by Vinz987** [comment]
What about offline devices? is it possible to use this method with local "url"?

**Comment by shortercode** [comment]
@Vinz987 what do you mean by "local? Once the files are downloaded they are local, but at some point the user needs to connect to the internet to get the app contents.

**Comment by Vinz987** [comment]
@shortercode that's the heck... No internet connection! It's for museum application, only one device on a fixed place. I meant a local path to a file already on the device, but I'm a newbie not really able to code, so my question may be stupid... I didn't found a way to do it in construct yet, without adding the files themselves to the project.

**Comment by shortercode** [comment]
@Vinz987 The suggestion I made gets data over the network, either from a webserver on the local network or from a webserver over the internet. It then saves it as files on the device, so that the game can be used offline.

If you intend to install the game on only one device, then that would suggest you do not need to publish to the Play Store and are therefore not limited to 100MB.

**Comment by Vinz987** [comment]
@shortercode There is no network at all in that room. (next time we'll use pc sticks or things like that! ;) )
The app won't install if it exceed 100Mb. I didn't find a way to build it properly in that case. But it was a few months ago, I need to retry with new releases

**Comment by shortercode** [comment]
Could always set it up in a different room, then move it in? Just checking myself to see if I can get an APK > 100MB to install. I presumed it was just an arbitrary limit imposed by the store, I'm not aware of any technical reason why an APK can't be larger than 100MB.

**Comment by shortercode** [comment]
Just tried installing a 240MB debug APK on a S8, worked fine.

**Comment by Vinz987** [comment]
It's wall mounted 32" screen, and the power is off every night, so we should do it everyday and it would be difficult.
I have a big exhibition about another subject to put on paper (screenless... whew!). But when it's over I'll try to fix this and take screenshot to exemplify the problems... Thanks a lot for your help!

**Comment by Vinz987** [comment]
It's also probably about the android versions of the devices (brand is ELO and we didn't hired the online services, as we have no network there...)

**Comment by shortercode** [comment]
Well as I said, the files would be stored locally after the download. So you would only have to do it once, not every night. How are you loading the APK onto the TV?

**Comment by Vinz987** [comment]
USB key... It's an all in one system

**Comment by shortercode** [comment]
Other than a pre release development kit I have had very little to do with Android TV. So I probably can't offer much help on the systems side, but I've heard the manufacturers skins can be quite limiting.

As far as I see it, your problem isn't going to be solved by the expansion APK feature. They are installed via the android store and you don't have an internet connection, so that isn't going to happen. Your best bet is building a single large APK and installing that. If for whatever reason that doesn't work... we'll I'd recommend finding some way to connect it to the internet briefly, because your only other option is some custom code for accessing the general storage on the device.

**Comment by AshleyScirra** [comment]
This is a feature request and it's already been filed here: https://construct3.ideas.aha.io/ideas/C3-I-114

Closing this issue as it's a feature request rather than a bug - please vote on the linked feature request to show your interest.
