### ISSUE TITLE
Request whitelististing of unityads cordova plugin by artemisoftnian on Construct Cloud Compiler

### ISSUE THREAD

**Issue by artemisoftnian** [Scirra/Construct-3-bugs#1490]
As per guide on the Plugin SDK Manual an forums and your consideration, Im asking for the possible whitelisting of my unityads2 cordova plugin, as Is used by my Construct addon UnityAds published already on the addon repository.

Cordova Plugin:
https://www.npmjs.com/package/com-artemisoftnian-plugins-unityads2

Construct 3 addon:
https://www.construct.net/pr/make-games/addons/100/unityads

thanks in advance

**Comment by shortercode** [comment]
Sure I'll take a look for you! As a note when I whitelist a plugin it will be for a particular version, so when you publish a new release you will have to notify us to review it again.

**Comment by artemisoftnian** [comment]
thanks and noted!  Also that would be a good point to adress in the sdk manuals.

**Comment by shortercode** [comment]
Okay I've reviewed the 2.2.0 version of your plugin and it looks fine. It'll be added to the whitelist next time I update the server. I will update this bug when it's live.

**Comment by shortercode** [comment]
Okay the revised whitelist is live!

If you have any issues building project with your plugin and the build service please create an issue with: - an example project
- instructions for use
- copy of your C3 plugin
- error you recieve

and I will take a look at it for you.
