### ISSUE TITLE
C3 runtime: Wheel reversed on Mouse object

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#1496]
## Problem description

C3 runtime: Wheel up and down reversed on Mouse object.

## Attach a .c3p

[test-runtime-mouse-wheel.zip](https://github.com/Scirra/Construct-3-bugs/files/1918532/test-runtime-mouse-wheel.zip)

## Steps to reproduce

1. Open and preview the project (C2 runtime)
2. Use mouse wheel up and down to zoom in and out
3. Change the runtime to C3 runtime in project properties
4. Preview it again, the mouse wheel behavior is reversed

## Observed result

Mouse wheel is reversed with C3 runtime.

## Expected result

Usual behavior.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next release.
