### ISSUE TITLE
[r24] Crash with quick successive clicks on alignment option

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#150]
## Problem description

My mouse just broke not too long ago with the problem of random double-clicking even when it is just a click. With that said, when I was testing out the aligning options for a sprite object, I got a crash. The crash comes with a create new object dialogue window. So, I assumed my broken mouse had quick successive mouse clicks on that align option that is quick enough that the object was deselected into the create new object dialogue window before Construct did the aligning.

I would not want my broken mouse to be an excuse for this bug. I believe someone will eventually click fast enough for Construct to trigger the crash on these options.

## Steps to reproduce

1. Create a sprite object.
2. Quick successive click on aligning option.

## Observed result
Crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r24/components/editors/layoutView/layoutView.js, line 1, col 51162
Message: Uncaught Error: no selection
Stack: Error: no selection at X.ǃXD (https://editor.construct.net/r24/components/editors/layoutView/layoutView.js:1:51168) at window.ǃX$.ǃehu (https://editor.construct.net/r24/components/editors/layoutView/layoutView.js:1:26596) at U.ǃkQ (https://editor.construct.net/r24/components/editors/layoutView/layoutView.js:1:10957)
Construct 3 version: r24
URL: https://editor.construct.net/index.html
Date: Thu May 04 2017 22:39:18 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 30.7 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I can't reproduce this (and doubtful anyone can unless they also have a faulty mouse :P) but I added a speculative fix based on the crash report in r25.

**Comment by AshleyScirra** [comment]
r25 is out now, can you verify this is fixed?

**Comment by jaydonteh** [comment]
Can't seem to reproduce it any more, fixed!

**Comment by AshleyScirra** [comment]
Thanks!
