### ISSUE TITLE
R95.2 Safari - Download a copy

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1505]
## Problem description

*Enter a concise description of your problem here*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open your project or create a new one
2. Click Menu, Save As, Download a Copy
3. Give it a name and click ok

## Observed result
OOPS! Something went wrong.
Reason: browser does not support downloading local content.

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by zumwaltwood** [comment]
Error report information
Type: unhandled rejection
Reason: browser does not support downloading local content
Construct 3 version: r95.2
URL: https://editor.construct.net/r95-2/
Date: Fri Apr 20 2018 08:47:51 GMT-0500 (CDT)
Uptime: 844.8 s

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r95.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A10X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions: EXT_blend_minmax, EXT_sRGB, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_standard_derivatives, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context, WEBKIT_WEBGL_compressed_texture_pvrtc, WEBGL_depth_texture, ANGLE_instanced_arrays, WEBGL_debug_renderer_info

**Comment by AshleyScirra** [comment]
The crash should be fixed in the next release. The main problem is Safari doesn't actually support downloading the exported zip file (since it's generated locally rather than on the server). Annoyingly Safari on macOS supports this feature, but it's missing on iOS. So in the next build it'll open a new tab and show you a file called "unknown.zip" which you can then share somewhere else.
