### ISSUE TITLE
R95.2 Safari on ipad 12.9 and Mobile UI vs Desktop UI

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1507]
## Problem description

*Enter a concise description of your problem here*
Mobile UI was an interesting thought, drop it, keep just the desktop UI for all platforms, I have now tried C3 on both apple and android phones, that mobile UI is just not worth it, I wouldn't waste any more development time in it, keep this down to tablets and desktops only.  Kudos for trying to keep all mobile in mind, but time to put that to rest.

Without the side menu's it is a pain to work with, the multi gesture for moving the scene around is also causing menu options to come up as right click, this is an annoyance but easily overlooked when using touch displays.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by zumwaltwood** [comment]
I know this is not a bug, but it is definitely an end user experience issue.

**Comment by AshleyScirra** [comment]
The mobile UI is designed for reviewing and tweaking projects. It is expected that people will use the desktop UI for heavy productivity work. We have hundreds of users using the mobile UI across Android and iOS, and we plan to keep it. I am sure there would be a great many angry customers if we just cut off a feature they were actively using.
