### ISSUE TITLE
R95.2 Switching from tilemap tool A to B via keyboard while using A breaks A

### ISSUE THREAD

**Issue by hoodloc** [Scirra/Construct-3-bugs#1509]
## Problem description

Affected tilemap bar tools: pencil, eraser, rectangle (2-4 on keyboard)

Using one of the affected tools (drawing with mouse down) while simultaneously switching to a different tilemap bar tool via keyboard shortcut breaks the formerly used tool. The broken tool now functions as if the mouse was permanently down until the mouse is actually clicked.

## Attach a .cp3

[tilemap_tool_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1934433/tilemap_tool_bug.zip)

## Steps to reproduce

1.Use one of the affected tilemap bar tools (A) to draw/erase tiles while simultaneously switching to a different tilemap bar tool (B) via keyboard shortcut. 
2.Release the mouse.
3.Switch back to tool A via keyboard shortcut and move the mouse across the layout.

## Observed result

Tool A behaves as if the mouse was down. Even switching between different tools multiple times via keyboard leaves tool A in this state. It stays like this until the mouse is actually clicked.

## Expected result

The tool shouldn't treat the mouse as if it was down when it actually isn't.

## Affected browsers

* Chrome: yes

## System details

Tested on a PC

**Comment by DiegoScirra** [comment]
Fixed in r97
