### ISSUE TITLE
weird scirra bug

### ISSUE THREAD

**Issue by cori6487** [Scirra/Construct-3-bugs#151]
its not a bug with c3 its a bug with scirra.com the bug is when you upload a new version of a game it gives me the error "D:\\FromC\\V4Arcade\\games\\17468\icons\icon-256.png already exists" and i dont know why. but maybe its trying to see if there are duplicate images, can you change it so it just deletes the old exported file and just makes the new one look like it was always there and i just changed the version? if thats do-able, because its really annoying to have to re-upload a game each time i want to update it

**Comment by cori6487** [comment]
im guessing this will be fixed on the construct website when the arcade gets moved over there?

**Comment by cori6487** [comment]
also the time is really off (but im using p.t. so maybe it correct for you)

**Comment by AshleyScirra** [comment]
Closing, please post to the "Website issues" forum, this tracker is for Construct 3 only.

**Comment by cori6487** [comment]
oops, sorry
