### ISSUE TITLE
A phantom variable in a function is preventing me from completing a drag action in the editor

### ISSUE THREAD

**Issue by TurkMcGill** [Scirra/Construct-3-bugs#1512]
## Problem description

I have a function that used to have a local variable called "temp". When I realized that I no longer needed the variable I deleted it. (Searching for "temp" in the editor reveals no instances of it anywhere.)

Later, I tried to move a block of code in the editor and I got an error message that said: "You can't drop events here because: Unknown expression 'temp'. This is not a system expression or a variable name in this scope.

## Attach a .c3p

I tried to recreate this problem, but couldn't.

## Steps to reproduce

1. Create a function that includes a local variable.
2. Remove the local variable
3. Try to drag events in that function

## Observed result

An error message appears even though the variable was removed.

## Expected result

No error should appear and I should be allowed to move my code around.

## Affected browsers

* Chrome: yes
* Firefox: NA
* Edge: NA
* Safari: NA

## System details

I am using the latest version of Chrome and the latest beta release of Construct 3.
![image](https://user-images.githubusercontent.com/25029302/39092871-8fe1a430-4616-11e8-956b-270ed6ae336f.png)

**Comment by TurkMcGill** [comment]
UPDATE: After trying (unsuccessfully) to recreate the bug I reloaded my game and decided to try dragging the block of code again. It worked this time! (I'm not sure if I have reloaded my game since removing the variable.)

**Comment by AshleyScirra** [comment]
I'm afraid we can't investigate this without a project or steps to reproduce. Please file a new issue if you find a way to reproduce it.
