### ISSUE TITLE
Tilemap Object, can draw/change tilemaps if there is more of them over each other

### ISSUE THREAD

**Issue by EntityB** [Scirra/Construct-3-bugs#1515]
## Problem description

If you have multiple tilemaps objects, each with one instance, but instances covers, you can only draw/erase/etc. to the most top (in Z order) tilemap. 
You can lock this top tilemap to access the one under, but it also does weird behavior. 

## Attach a .c3p

none

## Steps to reproduce

1. create new project
2. add new tilemap object and put one instance into layout (position 0,0)
3. create another tilemap object and do the same
4. now try to draw into both tilemap instances. For one of them it will fail. 

## Observed result

It is still possible to work, but very hard to manage. You need to play with Z-order all the time. 

## Expected result

I need to work with multiple instances of tilemaps of different objects that are over each other. 

## Affected browsers

* Chrome: yes
* Firefox: didnt test
* Edge: didnt test
* Safari: didnt test

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 4.8 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
@EntityB There are no plans to implement such a feature.

If you need to work with many overlapping tilemaps you might consider putting each one of them into a different layer, you can then lock all the tilemap layers you don't want to edit while keeping the one you do want to edit unlocked.

Doing this will still require some back and forth work to lock and unlock layers, but you won't need to fiddle with the Z-order.

**Comment by AshleyScirra** [comment]
@DiegoScirra - assuming you meant to close this?
