### ISSUE TITLE
Upload new version of game bug

### ISSUE THREAD

**Issue by Dan0Randan** [Scirra/Construct-3-bugs#1516]
## Problem description

The file already exists bug.

![deae94340e8d](https://user-images.githubusercontent.com/9051865/39128482-c443ab12-46ff-11e8-8636-cec13c71aa12.png)

I am uploaded construct 3 project over project 2 and all was fine, but from construct 3 to construct 3 causes bug.

## Attach a .c3p

This not just for one project.

## Steps to reproduce

1.
2.
3.

## Observed result

Game not uploaded

## Expected result

Game upload

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: no
* Safari: no

## System details

The file D:\\FromC\\V4Arcade\\games\\22220\media\73.ogg already exists.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
I'm not sure if there's enough information here, but I will assign @TomGullen to take a look.

**Comment by AbelzAu** [comment]
I get same fault trying to upload a new version of a c3 made game. Error file ready exists

**Comment by TomGullen** [comment]
Closing - I'm aware of these issues but not willing to spend time fixing these right now due to bandwidth.  There will be a new arcade which will resolve all these issues an scale a lot better.  In the meantime, feel free to upload a new game.
