### ISSUE TITLE
Minor issue with NWjs.ProjectFilesFolder and wrong path "/" (Windows Only)

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1517]
## Problem description

I've been testing the new project folder expressions and actions, they're all working fine on Mac and Windows. However I've noticed that on Windows the path is using `/` instead of the expected `\`. 
This doesn't seem to break any of the actions though but I felt it was worth mentioning since it might be a minor coding mistake or might cause future projects to fail on Windows.

Screenshot:
![thiserror](https://user-images.githubusercontent.com/15656049/39135517-6a3f3ad6-4719-11e8-8f91-3b72f73d0d0c.PNG)

## Attach a .c3p
[NWjsPath.zip](https://github.com/Scirra/Construct-3-bugs/files/1938879/NWjsPath.zip)

## Steps to reproduce

1. Open Project
2. Export using NW.js to Windows (64bit in my case)
3. Click on "ok" and it should open an attached image file and display folder paths

## Observed result

_NWjs.ProjectFilesFolder_ expression returns a wrong path that ends with `/` instead of expected `\`.

## Expected result

The path should be consistent and change `/`'s depending on the platform it's running on.

## Affected browsers

* NW.js: yes
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r96 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 142 gb
Storage usage (approx): 129 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The mixed slashes actually comes from the node/NW.js code. I don't think it matters, the Windows file parser is pretty relaxed, so as you've noted nothing is actually broken by this.
