### ISSUE TITLE
Rapidly clicking Open Project button on Recent Projects will open multiple copies of the same project ( some fail )

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#152]
## Problem description

I noticed that occasionally I was getting a "Failed to open project" error when opening a recent project, but the project was still opening. I realised that by double clicking the open button it was opening more than one copy of the project, and interestingly they would sometimes open successfully so you had more than one copy of the same project open. When testing on editor.construct.net I managed to get 7 copies of the same project open by clicking rapidly, but only 3 when testing locally ( some race condition no doubt ). 

I'm not that worried about UI not preventing it from opening more than once, although that obviously needs fixing, but more the fact that a project with the same UID can be opened more than once... This could have strange effects elsewhere.

## Attach a .c3p
N / A

## Steps to reproduce

Presumes you have at least one recent project

1. Click on recent projects
2. Rapidly click on Open Project

## Observed result

Multiple copies of the same project open, and some error dialogs saying "Failed to open project"

## Expected result

Only one copy of the project to open.

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: untested

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.96
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 264 mb (0.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I think there are really two issues here:

1. "Failed to open project" in the repro steps (initial investigation showed this is only because it's confused by all the dialogs appearing and closing and tries to close the same dialog twice)
2. User can open the same project twice

For 2), IIRC we already made a change to allow opening the same project UID more than once, because it was too restrictive. There was some case where a user couldn't open a project they wanted to because of the check. Not sure what the best resolution for that is.

**Comment by AshleyScirra** [comment]
Added a flag to block opening a project while still opening another project, which fixes the immediate problem of crashes/errors when spam-clicking to open a recent project. Closing this issue, if opening the same project twice is an issue we should track that separately.
