### ISSUE TITLE
r96: Animation Editor crashes when cropping Animation and moving Origin Point.

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#1520]
## Problem description

Took me a while to reproduce this but when working in the animation editor yesterday i encountered this bug quite a few times. It seems to happen when cropping an animation and then moving the origin point around. As soon as i reselect another frame of the animation, C3 crashes.

## Steps to reproduce

1. Open new Project
2. Create new Sprite
3. Fill with random color
4. Duplicate the frame a few times
5. Use rectangle select tool to select a random area
6. Crop whole animation using Shift+Crop
7. Move Origin point to new Location
8. Right Click -> Apply to whole animation
9. Select another frame of the animation (sometimes only happens after the second or third time).

## Observed result

Construct Crashes.

## Expected result

To be able to move around the Timeline without crashing the Software.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: ǃCtV is not defined @ ReferenceError: ǃCtV is not defined at a.then.then.then.then.then.then (https://editor.construct.net/r96/main.js:74:391524)
Stack: ReferenceError: ǃCtV is not defined at a.then.then.then.then.then.then (https://editor.construct.net/r96/main.js:74:391524)
Construct 3 version: r96
URL: https://editor.construct.net/r96/
Date: Tue Apr 24 2018 11:08:46 GMT+0200 (CEST)
Uptime: 90.5 s

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r96 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r97
