### ISSUE TITLE
Text selection bug

### ISSUE THREAD

**Issue by oosyrag** [Scirra/Construct-3-bugs#1521]
## Problem description

Unable to select/highlight expressions within a text input field from right to left via mouse.

## Attach a .c3p

https://www.dropbox.com/s/b66vdm7r2zk9d2b/selectionbug.c3p?dl=0

## Steps to reproduce

1. Open the condition in event 1.
2. Try to make a text selection by click/drag with a mouse from right to left, starting at the outside of any close parenthesis for an expression/parameter.

## Observed result

Text does not get selected as expected

## Expected result

Text should be selected

## Affected browsers

* Chrome: yes
* Firefox: unknown
* Edge: unknown
* Safari: unknown

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 6.8 gb
Storage usage (approx): 75 mb (1.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Hi @oosyrag thanks for your report, am I right in saying this is only an issue in the "First Angle" value? I believe this is caused by our bracket highlighter.

**Comment by oosyrag** [comment]
It happens for any close parenthesis ")", it happens in all the input
fields. It does look like it has something to do with bracket highlighting.

**Comment by Wackytoaster** [comment]
Can confirm this

**Comment by dop2000** [comment]
Extremely annoying bug, especially when editing long complex expressions.
Exists in both web and desktop versions of C3.
[Demo gif](https://postimg.cc/image/qjhkas24p/)

**Comment by shortercode** [comment]
Sorry this has taken awhile, have to say this bug was very frustrating to try and fix. I'm still not 100% sure of the cause, but I've managed to work around it. The fix will be available in the next beta.
