### ISSUE TITLE
Plugin browser. Dont work properties: unlock, lock devices orientation

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#1525]
## Problem description

Plugin Browser action unlock or lock orientation. The device will not change the orientation of the screen. Also, if you specify a landscape in the project properties, the screen will remain in the same landscape position when you rotate the device.

## Attach a .c3p

all projects

## Steps to reproduce

1.add browser plugin
2.add unlock or lock orientation in action on start layout
3.export with cordova android studio or debug apk

## Observed result

Action unlock orientation will not respond to device rotation

## Expected result

Change screen orientation

## Affected browsers

android system

**Comment by AshleyScirra** [comment]
These actions are designed for mobile browsers and only work after "request fullscreen", as noted in the manual. When exporting to Cordova, the project property for orientation is used instead.

**Comment by ERAgames777** [comment]
@AshleyScirra Well. then why in the project properties, if you put a landscape, then the screen will not turn in two directions along the landscape. Will take a landscape in one direction?
