### ISSUE TITLE
Can't paint with tilemap if there's a sprite above it

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1526]
## Problem description

If you add a tilemap and then add a sprite above it you wont be able to draw with the tilemap in this place until you remove the sprite, which is very counterintuitive for level design.

Demonstration: https://i.imgur.com/KNKGQmq.gif

## Attach a .c3p

[Tilemap Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1951290/Tilemap.Bug.zip)

## Steps to reproduce

1. Add a tilemap object to your layout.
2. Add a sprite object to your layout.
3. Try to paint with the tilemap below the sprite.

## Observed result

The tilemap will skip the spot with the sprite.

## Expected result

The tilemap to paint below the sprite.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r99.
