### ISSUE TITLE
Phonegap Build fail with Google Play plugin...

### ISSUE THREAD

**Issue by Bootfit** [Scirra/Construct-3-bugs#1527]
## Problem description

The following error occurs when project contains the Google Play plugin and exported as Android (Cordova) then taken into Phonegap Build:

Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: ConstructPlayGames.java - You can fix this here

[GooglePlayError.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1951541/GooglePlayError.c3p.zip)

## Steps to reproduce

1. Export project
2. Zip up
3. Try and build via Phonegap Build

## Observed result

Got following error:

_**Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: ConstructPlayGames.java - You can fix this here**_

## Expected result

Expected project to build - usually builds in Phonegap Build when Google Play plugin is not present.

## Affected browsers

Not a browser issue.

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

`
Build Date: 2018-04-26 14:10:42 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.3.3" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
Fetching plugin "cordova-plugin-statusbar" via npm
Installing "cordova-plugin-statusbar" at "2.4.2" for android
Fetching plugin "cordova-custom-config" via npm
Installing "cordova-custom-config" at "5.0.2" for android
Fetching plugin "construct-play-games@1.0.5" via npm
Installing "construct-play-games" at "1.0.5" for android
Subproject Path: CordovaLib
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_1ljvjhb4fjjlyt6nbp9u0ho8k.run(/project/build.gradle:137)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportCompat2520Library
:prepareComAndroidSupportSupportCoreUi2520Library
:prepareComAndroidSupportSupportCoreUtils2520Library
:prepareComAndroidSupportSupportFragment2520Library
:prepareComAndroidSupportSupportMediaCompat2520Library
:prepareComAndroidSupportSupportV42520Library
:prepareComGoogleAndroidGmsPlayServicesAuth1104Library
:prepareComGoogleAndroidGmsPlayServicesAuthBase1104Library
:prepareComGoogleAndroidGmsPlayServicesBase1104Library
:prepareComGoogleAndroidGmsPlayServicesBasement1104Library
:prepareComGoogleAndroidGmsPlayServicesDrive1104Library
:prepareComGoogleAndroidGmsPlayServicesGames1104Library
:prepareComGoogleAndroidGmsPlayServicesIdentity1104Library
:prepareComGoogleAndroidGmsPlayServicesTasks1104Library
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:incrementalReleaseJavaCompilationSafeguard
:compileReleaseJavaWithJavac
:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/project/src/com/scirra/ConstructPlayGames.java:8: error: cannot find symbol
import com.google.android.gms.auth.api.signin.GoogleSignIn;
                                             ^
  symbol:   class GoogleSignIn
  location: package com.google.android.gms.auth.api.signin
/project/src/com/scirra/ConstructPlayGames.java:10: error: cannot find symbol
import com.google.android.gms.auth.api.signin.GoogleSignInClient;
                                             ^
  symbol:   class GoogleSignInClient
  location: package com.google.android.gms.auth.api.signin
/project/src/com/scirra/ConstructPlayGames.java:13: error: cannot find symbol
import com.google.android.gms.games.AchievementsClient;
                                   ^
  symbol:   class AchievementsClient
  location: package com.google.android.gms.games
/project/src/com/scirra/ConstructPlayGames.java:14: error: cannot find symbol
import com.google.android.gms.games.AnnotatedData;
                                   ^
  symbol:   class AnnotatedData
  location: package com.google.android.gms.games
/project/src/com/scirra/ConstructPlayGames.java:16: error: cannot find symbol
import com.google.android.gms.games.LeaderboardsClient;
                                   ^
  symbol:   class LeaderboardsClient
  location: package com.google.android.gms.games
/project/src/com/scirra/ConstructPlayGames.java:18: error: cannot find symbol
import com.google.android.gms.games.PlayersClient;
                                   ^
  symbol:   class PlayersClient
  location: package com.google.android.gms.games
/project/src/com/scirra/ConstructPlayGames.java:47: error: cannot find symbol
	private GoogleSignInClient mGoogleSignInClient;
	        ^
  symbol:   class GoogleSignInClient
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:50: error: cannot find symbol
	private AchievementsClient mAchievementsClient;
	        ^
  symbol:   class AchievementsClient
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:51: error: cannot find symbol
	private LeaderboardsClient mLeaderboardsClient;
	        ^
  symbol:   class LeaderboardsClient
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:52: error: cannot find symbol
	private PlayersClient mPlayersClient;
	        ^
  symbol:   class PlayersClient
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:65: error: cannot find symbol
		mGoogleSignInClient = GoogleSignIn.getClient(
		                      ^
  symbol:   variable GoogleSignIn
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:76: error: cannot find symbol
      		Task<GoogleSignInAccount> task = GoogleSignIn.getSignedInAccountFromIntent(intent);
      		                                 ^
  symbol:   variable GoogleSignIn
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:193: error: cannot find symbol
		return GoogleSignIn.getLastSignedInAccount(cordova.getActivity()) != null;
		       ^
  symbol:   variable GoogleSignIn
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:208: error: cannot find symbol
		mAchievementsClient = Games.getAchievementsClient(activity, googleSignInAccount);
		                           ^
  symbol:   method getAchievementsClient(Activity,GoogleSignInAccount)
  location: class Games
/project/src/com/scirra/ConstructPlayGames.java:209: error: cannot find symbol
    	mLeaderboardsClient = Games.getLeaderboardsClient(activity, googleSignInAccount);
    	                           ^
  symbol:   method getLeaderboardsClient(Activity,GoogleSignInAccount)
  location: class Games
/project/src/com/scirra/ConstructPlayGames.java:210: error: cannot find symbol
    	mPlayersClient = Games.getPlayersClient(activity, googleSignInAccount);
    	                      ^
  symbol:   method getPlayersClient(Activity,GoogleSignInAccount)
  location: class Games
/project/src/com/scirra/ConstructPlayGames.java:461: error: cannot find symbol
        	new OnCompleteListener<AnnotatedData<AchievementBuffer>>() {
        	                       ^
  symbol:   class AnnotatedData
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:463: error: cannot find symbol
            	public void onComplete(@NonNull Task<AnnotatedData<AchievementBuffer>> task) {
            	                                     ^
  symbol: class AnnotatedData
/project/src/com/scirra/ConstructPlayGames.java:704: error: cannot find symbol
				new OnCompleteListener<AnnotatedData<LeaderboardScoreBuffer>>()
				                       ^
  symbol:   class AnnotatedData
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:707: error: cannot find symbol
	            	public void onComplete(@NonNull Task<AnnotatedData<LeaderboardScoreBuffer>> task)
	            	                                     ^
  symbol: class AnnotatedData
Note: /project/src/com/scirra/ConstructPlayGames.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
20 errors
:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.384 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/project/src/com/scirra/ConstructPlayGames.java:8: error: cannot find symbol
import com.google.android.gms.auth.api.signin.GoogleSignIn;
                                             ^
  symbol:   class GoogleSignIn
  location: package com.google.android.gms.auth.api.signin
/project/src/com/scirra/ConstructPlayGames.java:10: error: cannot find symbol
import com.google.android.gms.auth.api.signin.GoogleSignInClient;
                                             ^
  symbol:   class GoogleSignInClient
  location: package com.google.android.gms.auth.api.signin
/project/src/com/scirra/ConstructPlayGames.java:13: error: cannot find symbol
import com.google.android.gms.games.AchievementsClient;
                                   ^
  symbol:   class AchievementsClient
  location: package com.google.android.gms.games
/project/src/com/scirra/ConstructPlayGames.java:14: error: cannot find symbol
import com.google.android.gms.games.AnnotatedData;
                                   ^
  symbol:   class AnnotatedData
  location: package com.google.android.gms.games
/project/src/com/scirra/ConstructPlayGames.java:16: error: cannot find symbol
import com.google.android.gms.games.LeaderboardsClient;
                                   ^
  symbol:   class LeaderboardsClient
  location: package com.google.android.gms.games
/project/src/com/scirra/ConstructPlayGames.java:18: error: cannot find symbol
import com.google.android.gms.games.PlayersClient;
                                   ^
  symbol:   class PlayersClient
  location: package com.google.android.gms.games
/project/src/com/scirra/ConstructPlayGames.java:47: error: cannot find symbol
	private GoogleSignInClient mGoogleSignInClient;
	        ^
  symbol:   class GoogleSignInClient
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:50: error: cannot find symbol
	private AchievementsClient mAchievementsClient;
	        ^
  symbol:   class AchievementsClient
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:51: error: cannot find symbol
	private LeaderboardsClient mLeaderboardsClient;
	        ^
  symbol:   class LeaderboardsClient
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:52: error: cannot find symbol
	private PlayersClient mPlayersClient;
	        ^
  symbol:   class PlayersClient
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:65: error: cannot find symbol
		mGoogleSignInClient = GoogleSignIn.getClient(
		                      ^
  symbol:   variable GoogleSignIn
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:76: error: cannot find symbol
      		Task<GoogleSignInAccount> task = GoogleSignIn.getSignedInAccountFromIntent(intent);
      		                                 ^
  symbol:   variable GoogleSignIn
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:193: error: cannot find symbol
		return GoogleSignIn.getLastSignedInAccount(cordova.getActivity()) != null;
		       ^
  symbol:   variable GoogleSignIn
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:208: error: cannot find symbol
		mAchievementsClient = Games.getAchievementsClient(activity, googleSignInAccount);
		                           ^
  symbol:   method getAchievementsClient(Activity,GoogleSignInAccount)
  location: class Games
/project/src/com/scirra/ConstructPlayGames.java:209: error: cannot find symbol
    	mLeaderboardsClient = Games.getLeaderboardsClient(activity, googleSignInAccount);
    	                           ^
  symbol:   method getLeaderboardsClient(Activity,GoogleSignInAccount)
  location: class Games
/project/src/com/scirra/ConstructPlayGames.java:210: error: cannot find symbol
    	mPlayersClient = Games.getPlayersClient(activity, googleSignInAccount);
    	                      ^
  symbol:   method getPlayersClient(Activity,GoogleSignInAccount)
  location: class Games
/project/src/com/scirra/ConstructPlayGames.java:461: error: cannot find symbol
        	new OnCompleteListener<AnnotatedData<AchievementBuffer>>() {
        	                       ^
  symbol:   class AnnotatedData
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:463: error: cannot find symbol
            	public void onComplete(@NonNull Task<AnnotatedData<AchievementBuffer>> task) {
            	                                     ^
  symbol: class AnnotatedData
/project/src/com/scirra/ConstructPlayGames.java:704: error: cannot find symbol
				new OnCompleteListener<AnnotatedData<LeaderboardScoreBuffer>>()
				                       ^
  symbol:   class AnnotatedData
  location: class ConstructPlayGames
/project/src/com/scirra/ConstructPlayGames.java:707: error: cannot find symbol
	            	public void onComplete(@NonNull Task<AnnotatedData<LeaderboardScoreBuffer>> task)
	            	                                     ^
  symbol: class AnnotatedData
Note: /project/src/com/scirra/ConstructPlayGames.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
20 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
`
</details>

**Comment by Bootfit** [comment]
What do you mean my platform info?

My dev machine?

**Comment by shortercode** [comment]
Tested this with a project generated with r97, worked fine.

The fix included with r97 was an additional tag in the config.xml to tell phonegap build to use cordova 8.

**Comment by Bootfit** [comment]
Did you test with the .c3p that I attached?

**Comment by shortercode** [comment]
> If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to Menu -> About -> Platform information and paste that information there instead.

**Comment by Bootfit** [comment]
OK - i've added the error log above.

**Comment by shortercode** [comment]
I've tested your project as well, works fine. As I said, there is a phonegap build related fix in r97, are you definitely using it?

**Comment by Bootfit** [comment]
This is my current platform info:

`Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 218 mb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)`

**Comment by shortercode** [comment]
Your using r94.2, quite a few fixes have been published on the beta channel since then.

Either wait until the next stable ( hopefully next week ) or use r97 [https://editor.construct.net/r97/](https://editor.construct.net/r97/)

**Comment by Bootfit** [comment]
OK - I'll give that a go - I thought the updates rolled out automatically.
