### ISSUE TITLE
R94.2-R97: Can't install new addon using Construct on iOS

### ISSUE THREAD

**Issue by lonelyclaud** [Scirra/Construct-3-bugs#1528]
## Problem description

When trying to install a new add-on from the Add-on Manager from my iPad on iOS 11.3.1 in either Chrome or Safari (latest versions), results in an error, and the add-on is not installed.
The bigger problem with this is that it's impossible to open any projects from iOS that have custom add-on installed. 

## Steps to reproduce

1. Upload a custom add-on to iCloud from your desktop (making sure you have plenty of space on both iPad and iCloud)
2. Go to your iPad and navigate to editor.construct.net from either Safari, the Construct you've added to Home with Safari or Chrome. 
3. Tap on Menu -> View -> Addon manager -> Install new addon...
4. Select your add-on from iCloud
5. Observe the issue. 

## Observed result

Storage Error prompt:
`Unable to write to storage. The available quota may be full. Try freeing up storage space on your device. `

## Expected result

Add-on should had been installed.

## Affected browsers

* Chrome: yes
* Safari: yes

Using iPad Pro 12.9.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r100.

**Comment by nrusconi** [comment]
Apologies for commenting on a closed issue however I am experiencing this on iOS12, C3R118. Both in Safari & Chrome. Shall I open a new issue?
