### ISSUE TITLE
Build filed. Cannot connect to build server.

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#1529]
## Problem description

Connection to the build server is not installed when you try to export Cordova.

## Attach a .c3p

Any project.

## Steps to reproduce

1.Export cordova->Android studio, debug apk.
2.
3.

## Observed result

I watch the inscription "Waiting to build" at the bottom of the screen. After 2 minutes, "Restored connection" appears. As a result, the error "Build filed. Can not connect to build server."

## Expected result

Stable assembly of the project.

## Affected browsers

* Chrome: yes

## System details

Platform information
Browser: Chrome
Browser version: 66.0.3359.117
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
C3 release: r97 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 46 gb
Storage usage (approx): 220 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by shortercode** [comment]
Thanks for the report, I'll take a look when I get to the office.

**Comment by shortercode** [comment]
Server is back up now, sorry about that.

**Comment by ERAgames777** [comment]
@shortercode
 Its worked! Thanks for the work!
