### ISSUE TITLE
C3 kept running in background

### ISSUE THREAD

**Issue by Unconected** [Scirra/Construct-3-bugs#1531]
## Problem description

Some how c3 r97 beta kept running in background.
(Desktop build)

I didn't know this, after a few hours my computer got slow and almost crashed.
I checked task manager and C3 was showing as running, but I didn't have it open.
It caused my cpu usage to go up to 95%.
I closed C3 in task manager and everything went back to a normal 20%.
It seems like it was accumulative issue. I went hours without noticing a performance issue. 

## Attach a .c3p
A .c3p file wouldn't do much here.

## Steps to reproduce
I don't know how to reproduce.
I was building an unsigned apk for android.
I must have build about 4 times, then closed C3.
I was testing different methods for best performance on mobile.

## Observed result

Nothing, until Windows 10 performance started getting slow.
C3 was running in background.

## Expected result

C3 not running in background

## Affected browsers

I used Desktop build, so I assume it was using Chrome.
I don't think that is an issue.
I may be wrong since Chrome sometimes uses background services

## System details

Windows 10 Pro
10.016299 Build 16299
x64

I was only posting to make the issue aware.
I created an account just to make this post.
I most likely won't see a reply for a while.
This isn't a site I tend to use.

**Comment by AshleyScirra** [comment]
Sorry, without steps to reproduce there's nothing we can do to investigate the issue. Please file an issue with steps if you can find a way to reproduce it.
