### ISSUE TITLE
AJAX - page trying to load scripts from unauthenticated source - preview vs debug preview

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1532]
## Problem description

I´ve run into a pretty annoying problem with AJAX. So when I try to use AJAX to get data from my server (non SSL) Browsers block that attempt. (Also tested all this in the newest beta release)

![boi](https://user-images.githubusercontent.com/31101309/39398008-0148f038-4b08-11e8-933a-488703564613.PNG)

This in itself isn´t the problem though, since the Browser shows this in the URL bar and displays this little icon, where I can allow these sources (this counts until the browser window is closed)
![oi](https://user-images.githubusercontent.com/31101309/39398045-69b1f2d2-4b08-11e8-96ae-b821527b8116.PNG)

BUT said Icon does not show when I use the Debug Layout Preview, and I haven´t found a way to allow it otherwise (I could probably set some flag in Chrome settings but I really don´t wanna do that). That essentially renders the Debugger unuseable in this case.

I don´t want to update my server to SSL just for development/testing purposes.

## Attach a .c3p

[unsecure.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1957856/unsecure.c3p.zip)

## Steps to reproduce

1. Make ajax request to any "http://"
2. Start debug preview

## Observed result

The AJAX requests get blocked and I cannot allow them because the Icon to do so is not shown

## Expected result

Optimally that the AJAX requests don´t get blocked in the first place in the previewer, or at least that the icon is shown to allow it.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 444 mb (3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a standard security feature of browsers. By default you cannot make insecure requests from a secure page, and the preview page is secure. To be honest, these days you should be running everything on HTTPS. There are a number of features that don't work on insecure HTTP, and many new web platform features are HTTPS only.

**Comment by shortercode** [comment]
@Wackytoaster You might want to take a look at [how-can-i-disable-security-checks-for-localhost]( https://superuser.com/questions/772762/how-can-i-disable-security-checks-for-localhost)
