### ISSUE TITLE
Minor issue with "add new object type" in the project bar if there are multiple projects open

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1533]
## Problem description

Sometimes the "Add new object type" option disappears for the active project. Or the other way around, it is shown for the project that is currently inactive (greyed out)

![a](https://user-images.githubusercontent.com/31101309/39398231-36720a8a-4b0b-11e8-9760-f7e865df87d6.PNG)
![b](https://user-images.githubusercontent.com/31101309/39398232-37cebdf6-4b0b-11e8-80ba-b91bdea00c1a.PNG)

I just found out it happens if you switch the project by switching to the open **event sheet** rather than the open layout. If you switch to the layout it works as expected.

## Attach a .c3p

🌾 

## Steps to reproduce

1. Create a new project (A)
2. Now create another new project (B) <-- this should now be the active project by default
3. Switch to the **event sheet** of project A <-- project A is now highlighted as active
4. Try to add a new object type

## Observed result

"Add new object type" is missing from the menu

## Expected result

"Add new object type" beeing available

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r97 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 446 mb (3.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

The Clipboard API is not supported. Some clipboard features may be unavailable.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is actually by design. When you add a new object like a Sprite or Text, the next step is to drop it in to the Layout View. If there is no active Layout View to drop an instance in to, then the option is hidden. You can see the same thing happening if you create a new project and close the layout tab (so you only have the event sheet tab open) - the menu option also disappears then, since there's no active Layout View to drop new objects in to.
