### ISSUE TITLE
Plugin video and advertmobile

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#1535]
## Problem description

If the project has a video plug-in and shows a video banner (multimedia), then in the project when displaying the video plug-in starts the drawdown of FPS from the standard value of 50 to 1. This will not happen if in the banner block all the multimedia.

## Attach a .c3p

any project with video plugin and advertising plugin

## Steps to reproduce

1.add plugin video
2.set loop video
3.add plugin mobileadvert
4.export cordova>android studio.
## Observed result

After showing the video banner with the video plugin showing, the fps will start to drop to 1. If the banner contains a text ad, then the fps has a standard value in the region of 50.

## Expected result

FPS should not fall

## Affected browsers

android mobile system

**Comment by shortercode** [comment]
Thanks for the report, I'll investigate but I'm not hugely hopeful of finding a solution. If possible I would advise avoiding having a banner advert shown at the same time as a video scene.

**Comment by AshleyScirra** [comment]
@ERAgames777 - can you still reproduce this in the latest releases? We recently disabled WebGL 2 to avoid some driver issues, which might have been related.
