### ISSUE TITLE
Main layout drawn incorrectly when changing device orientation

### ISSUE THREAD

**Issue by DiegoScirra** [Scirra/Construct-3-bugs#1536]
Changing the orientation in iOS produces some strange behavior of the main Layout.

It looks like the window "resize" event is triggered before the window.innerWidth and window.innerHeight properties are updated, and this causes several issues.

**Comment by AshleyScirra** [comment]
Finally got to the bottom of this. Worked around buggy resize events on iOS when added to home screen.
