### ISSUE TITLE
r98 stable (Desktop Version)  -  Addon won't appear after installed via ADDON MANAGER

### ISSUE THREAD

**Issue by AlonDan** [Scirra/Construct-3-bugs#1538]
## Problem description
I know it's not officially supported, but maybe it is a general bug after all:
I've added REX C3 addon via the ADDON MANAGER, installation works nice and smooth.

- I restarted C3 and run it again to get the addon to work.
- I checked on the ADDON MANAGER it says it's installed.
- Double click on the canvas to choose the addon "move to" by Rex but it's not there, Can't see it at all.
- I tried the search box just to make sure I didn't miss it, nothing.. it's not there but it is Installed as mentioned.

## Steps to reproduce

1. Download and install  Rex "Move To" addon from his [GitHub page](https://github.com/rexrainbow/C3RexDoc/blob/master/repo/index.md) (link)
2. Install via the ADDON MANAGER in Construct 3 r98 (Desktop Version)
3. Restart Construct 3
4. Try to add the Addon to your project. 
 _(You'll notice that it's not in the addons list after installed)_

## Affected browsers
I only checked it with the DESKTOP version since I'm not using the Browser version anyway.

## System details
Intel i7 4770k CPU - 3.50 GHz
32GB RAM
GeForce GTX 980
SSD 480  (for OS and Construct 3 Desktop)
Extra HDD  (for Files and Projects)
Windows (10 64-bit)

**Comment by AshleyScirra** [comment]
Isn't it a behavior? So it won't appear in the "Insert new object" dialog?

**Comment by AlonDan** [comment]
Maybe I wasn't clear because of my bad English, sorry about that.
Right click on the canvas space, same like "Create New Object Type" popup but it's not there. It should appear under one of the categories I'm guessing...

Can you please check it if it's on this build specifically or maybe a DESKTOP version issue?
