### ISSUE TITLE
Website: Short URL for Manual

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#1541]
This is not really a problem but more of a "feature" suggestion but it was minor enough so i thought i'd open a report here instead of going to the suggestions platform ;)

It would be really convenient, if the manual of C3 would have some sort of short URL. My suggestion would be manual.construct.net. That way it's easier to find and open it. I know you can open the manual from the editor, but sometimes i want to read something up even when not working in Construct at the moment. If you feel this is totally inappropriate in here, just close the report, no hard feelings and thanks for the consideration! :)

**Comment by joelmayer87** [comment]
Cool! Btw i recently saw something they're working on for the new Blender 2.8: their crash dialogue now has a direct link to the bug tracker. Maybe that would save you some hassle too and for new users it would be easier to find the Git right away. Again really just a minor suggestion but just came to mind :D

**Comment by AshleyScirra** [comment]
Crash reports are automatically logged to the server and we already use that data to help improve C3's reliability.

**Comment by phillscirra** [comment]
Quick insert into the code, all done.  Should be accessible as suggested by Ashley at https://www.construct.net/manual next website code release.
