### ISSUE TITLE
[www issue] Can't upload effect.c2addon files

### ISSUE THREAD

**Issue by shinkan-fb** [Scirra/Construct-3-bugs#1544]
## Problem description

Unable to upload my effect to https://www.construct.net/pl/construct-2/addons  using *.c2addon extension.  It says "The extension .fx is not permitted. (Path in archive: '/files/RGBrighter.fx')"
but it works fine for uploading *.c3addons

## Steps to reproduce

1. Go to https://www.construct.net/pl/construct-2/addons
2. try to upload any c2 effect addon
3. it gives an error message

## Observed result

Error shows up "The extension .fx is not permitted. (Path in archive: '/files/RGBrighter.fx')"

## Expected result

Upload just the same as c3addons

**Comment by TomGullen** [comment]
Fixed
