### ISSUE TITLE
Touching a sprite will not open open a link on the browser via mobile.

### ISSUE THREAD

**Issue by mammothinc** [Scirra/Construct-3-bugs#1546]
## Problem description

When trying to open a link on a touched sprite via the browser object. It will not open a link to a new window. 

It does work if you touch a button but not a sprite. 

1. Open a link with the browser object on a remote preview by touching a sprite
2.
3.

More information here. 

https://www.scirra.com/forum/opening-a-link-via-the-browser_t203004
</details>

**Comment by AshleyScirra** [comment]
Please provide all the requested information in the bug report, including a minimal project. We routinely find things work when we try them ourselves without any additional information.
