### ISSUE TITLE
Audio on Start of Layout: Doesn't play until Key is pressed

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#1548]
## Problem description

It's really weird, all worked for me yesterday but today when continuing on my project, i noticed that none of the audio that is being called with the "On start of layout" event are being played anymore unless you press a key. Luckily, it still works with node.js exports. This applies to both Sound and Music Audio.

I'm sorryi have to say this, but since i got a very big convention coming up on Thursday and still have a load of work to do on it it would be great, if this bug could be fixed in timely matter since it makes working on the game pretty hard...

## Attach a .c3p

[audiobug.zip](https://github.com/Scirra/Construct-3-bugs/files/1975634/audiobug.zip)

## Steps to reproduce

1. Open C3 file
2.Press Play
3. Press any Key

## Observed result

No Audio being played.

## Expected result

Audio being played.

## Affected browsers

* Chrome: yes
* Firefox: no
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.139
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 613 mb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 580 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
You probably had Chrome update to v66. This is how the new autoplay policies work. The change was intentional and is imposed by the browser, so Construct cannot work around it. It is intended to prevent web pages annoying you by playing audio before you've interacted with them. There's more info here: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by joelmayer87** [comment]
... But.. that kinda makes my whole game unplayable :O It also happens every time a new audio is played... I got a lot of cutscenes where the user isn't supposed to do anything and just different audio files play after the layout is already loaded... When i stop one audio file, it stops pretty much everything... This is pretty severe actually...

**Comment by joelmayer87** [comment]
Aha or wait... maybe i got something wrong... does that only count for the very first time a layout is loaded? Then it's not that bad... sorry for the panic ;)
