### ISSUE TITLE
[r24] Crash on misplacement of event creation dialogue

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#155]
## Problem description

Even though it was unrelated to https://github.com/Scirra/Construct-3-bugs/issues/154 , during the reproduction of that bug I stumble upon this crash. Basically, when going into popup window for the event sheet, the event creation dialogue can sometimes opened in weird locations. This can be produced either going from normal window to maximise window and back. Keep trying to re-open the add event creation dialogue. While doing so, you could see the dialogue appearing outside of the screen to the right or at least half of it. When that happens, you dock the event sheet back to the main editor. Now, try adding an event and you get a crash every single time unless you reset the UI layout.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r24/main.js, line 2, col 356432
Message: Uncaught TypeError: Cannot read property 'innerWidth' of undefined
Stack: TypeError: Cannot read property 'innerWidth' of undefined at ǃV.ǃz.ǃu.ǃXN_.ǃeST (https://editor.construct.net/r24/main.js:2:356432) at Function.ǃeAC (https://editor.construct.net/r24/main.js:2:339130) at HTMLDocument.Ve.he.document.addEventListener.me (https://editor.construct.net/r24/main.js:2:334119) at HTMLDocument. (https://editor.construct.net/r24/main.js:2:280352)
Construct 3 version: r24
URL: https://editor.construct.net/index.html
Date: Sat May 06 2017 02:32:17 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 518.2 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by jaydonteh** [comment]
After messing around with the crash, turns out it also applies to layout views on the object creation dialogue. When any of the layouts or the event's creation dialogue is displaced by the irregular window sizes from maximising and un-maximising (along with re-opening the creation dialogue in each state), it will even crash after a restart of Construct when adding an object or creating an event.

It really depends of which is displaced, either the layout or the event sheet, the next time you try to use it, it will crash. Below is the report log of a layout view's object creation dialogue that has crashed after a displaced crash. This crash as of below will constantly appear unless you reset the UI layout.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r24/main.js, line 2, col 199510
Message: Uncaught TypeError: expected finite number
Stack: TypeError: expected finite number at Function.ǃV.ǃjA (https://editor.construct.net/r24/main.js:2:199516) at ǃV.ǃz.ǃu.ǃXYy.ǃeig (https://editor.construct.net/r24/main.js:2:355281) at ǃV.ǃz.ǃu.ǃXYy.ǃeiG (https://editor.construct.net/r24/main.js:2:342627) at ǃV.ǃz.ǃu.ǃXYy.ǃeCe (https://editor.construct.net/r24/main.js:2:347649) at ǃV.ǃz.ǃu.ǃXYy.ǃ$K (https://editor.construct.net/r24/main.js:2:346616) at ǃV.ǃz.ǃu.ǃXYy.ǃ$K (https://editor.construct.net/r24/main.js:63:421360) at window.ǃX$.ǃzv (https://editor.construct.net/r24/components/editors/layoutView/layoutView.js:1:16351) at window.ǃX$.ǃCf (https://editor.construct.net/r24/components/editors/layoutView/layoutView.js:1:15961) at HTMLDivElement.ǃMu.ǃV.ǃMA.ǃV.ǃMi.ǃMS.G (https://editor.construct.net/r24/components/editors/layoutView/layoutView.js:1:4116) at HTMLDocument. (https://editor.construct.net/r24/main.js:2:280352)
Construct 3 version: r24
URL: https://editor.construct.net/index.html
Date: Sat May 06 2017 19:46:59 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 6.6 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I'm not sure exactly how to reproduce this. Can you provide numbered steps to follow so I can repeat exactly what you're doing?

**Comment by jaydonteh** [comment]
Steps:
1. Undock event sheet.
2. Open to popup window.
3. Maximise window.
4. Click "Add event" to open the add event dialogue.
5. Un-maximise window. 

At this point your un-maximise window, the add event dialogue is misplaced out of the window.

6. Close window to bring it back to the editor.
7. Click "Add event" to open the add event dialogue.

You should get a crash here.

**Comment by AshleyScirra** [comment]
Ah, I see now, thanks. Should be fixed in r29.
