### ISSUE TITLE
Sprite copied from C2 into C3 can not change animation.

### ISSUE THREAD

**Issue by StefanSava** [Scirra/Construct-3-bugs#1550]
## Problem description

I try to swap the animation of a sprite with another animation. The result is a hidden sprite.
This sprite has been copied from a C2 project - I assume this is the main issue.

## Attach a .c3p

[spriteSwapBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1976475/spriteSwapBug.zip)

## Steps to reproduce

1.Copy a sprite from a C2 project
2.Try to swap animations

## Observed result

Sprite disappears, but is still there in debug mode just invisible.

## Expected result

Change to other animation.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.139
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 2.9 gb
Storage usage (approx): 223 mb (7.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 650 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Your steps to reproduce cannot be followed because you did not provide the C2 project, only a C3 project, so we can't follow the step to import from a C2 project.

The sprite disappears when you change animation because it uses the "Additive" blend mode and switches to an entirely black image. The color black has zero-value color channels, so the additive effect adds zero, meaning the object is invisible. This is a normal result and so everything appears to be working correctly. I suspect you accidentally set the additive blend mode and didn't realise it would make a black object appear invisible, and mis-attributed this to the import from C2.
