### ISSUE TITLE
Sprite facing issue

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1551]
## Problem description

*Enter a concise description of your problem here*
Sprite facing for player is changed at runtime, this seems to be dependent on as soon as you click play. Using a basic sprite I created as a sideways triangle to display facing, in the designer you can see the player should be facing to the right, but when you touch play, the player facing is defaulted to that direction. Additionally when you stop touching the device, the player facing orientation returns to the bad facing instead of holding onto the last known facing angle from mobile touch. Both issues seem related.

See attached video

http://www.youtube.com/watch?v=z1PVA5DOCqo

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Add sprite to scene
2. Add code to sprite to face where player is touching display
3. On tap gesture, every tick, set angle towards Touch.X, Touch.Y

## Observed result

*What do you see happen?*
Player facing altered at runtime, hard to explain, see video

## Expected result

*What did you expect to happen instead?*
Player facing to remain same as design on start, then no longer touching, to leave player facing equal to last known touch spot.

## Affected browsers

* Safari: yes
[cyborg attack facing.zip](https://github.com/Scirra/Construct-3-bugs/files/1979920/cyborg.attack.facing.zip)

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.3
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r98 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A10X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by AshleyScirra** [comment]
You have an event that says "Every tick: set angle towards Touch.X, Touch.Y". This still runs when you're not in a touch. Since Touch.X and Touch.Y must still return a value when not in a touch, they return 0. The position (0, 0) is at the top-left of the layout, so when you're not touching anything, the sprite will point at the top-left of the layout. The events are working correctly and it's not a bug.

There is an empty "On tap gesture" event above the "Every tick" event. I suspect you intended to actually put the "Set angle" action in that event, since it then only changes the angle of the sprite when you do touch, and so will return nonzero values for Touch.X/Y.

**Comment by zumwaltwood** [comment]
The value should be the last known value, not 0,0 so if it is not a bug then this needs pushed to design change request to have it be the last known touch point, wherever that was. So I can touch a point and have it act like a waypoint, then I can have objects go to that point then stop upon arrival.

**Comment by AshleyScirra** [comment]
The expressions will still have to return 0 on startup, so in the given example the sprite will still appear pointing top-left rather than right.

**Comment by zumwaltwood** [comment]
Can use some startup routine to assign X and Y as an override possibly.
Or use object facing to get that for initial angle or point of facing, so whatever the code is attached to, have it keep the initial facing based on object orientation.

**Comment by zumwaltwood** [comment]
![untitled_artwork](https://user-images.githubusercontent.com/4122283/39761370-867e50c6-529d-11e8-83c7-443634674201.png)
I sketched up an example of what I’m thinking as far as initial point. Every image has a bounding box obviously, and the mid point to the right side is the face point, from mid point of object which is local 0,0 if you use that as center of image, then if max right is .5,.5 to local, the point is really 0,0x.5,.5 of local object face, instead of 0,0 to world space, then just take location of 0,0 of object in world space to face angle and point of object initial facing, that should give the value to use in world space for object initial face value other than 0,0
