### ISSUE TITLE
Animations buffer blows up

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1552]
## Problem description

*Enter a concise description of your problem here*
Trying to add a new sprite and load in animations, keeps bugging out, see video
This is not project specific bug, repeatable in any project.

http://www.youtube.com/watch?v=i1ETe0krSPg

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Load project
2. Add a new type, sprite, to project tree
3. Double tap to open in editor
4. Tap and hold on the sprite in project tree to get menu to open
5. Tap on edit animations

## Observed result

*What do you see happen?*
Error

## Expected result

*What did you expect to happen instead?*
Animation list of frames to show to edit

## Affected browsers

* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r98/main.js, line 74, col 1479345
Message: Error: Animations Editor undo buffer is already initialized
Stack: ǃQpu@https://editor.construct.net/r98/main.js:74:1479289 ǃBw@https://editor.construct.net/r98/main.js:74:1186435 https://editor.construct.net/r98/components/bars/projectBar/projectBar.js:1:19806
Construct 3 version: r98
URL: https://editor.construct.net/
Date: Mon May 07 2018 21:36:15 GMT-0500 (CDT)
Uptime: 47.4 s

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.3
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r98 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A10X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions: EXT_blend_minmax, EXT_sRGB, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_standard_derivatives, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context, WEBKIT_WEBGL_compressed_texture_pvrtc, WEBGL_depth_texture, ANGLE_instanced_arrays, WEBGL_debug_renderer_info

</details>

**Comment by DiegoScirra** [comment]
Fixed in r99
