### ISSUE TITLE
SDK typo

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#1554]
Not really a C3 bug. Just a typo. See for yourself:
![image](https://user-images.githubusercontent.com/11213825/39760982-1cec0eac-52d7-11e8-9e8f-a424ecffdd77.png)
You swapped supportsEffects and isSingleGlobal here
https://www.construct.net/fr/make-games/manuals/addon-sdk/reference/iplugininfo

**Comment by AshleyScirra** [comment]
Thanks, fixed.
