### ISSUE TITLE
Construct 3 not reloading editor files in developer mode

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#1555]
## Problem description

I had an error on a plugin I made and then fixed it

## Attach a .c3p

None

## Steps to reproduce

None

## Observed result

C3 didn't reload the files after I changed them, even though it should.
![image](https://user-images.githubusercontent.com/11213825/39769304-1da62340-52ec-11e8-9c23-e3c249a0b028.png)
Full error below in system information
## Expected result

It should have reloaded the file.

## Affected browsers

Desktop C3

## System details

See full error and other info here

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: help URL must begin with http:// or https:// @ Error: help URL must begin with http:// or https:// at window.ǃCd.ǃuin (https://editor.construct.net/r99/main.js:63:484903) at new window.Plugin (https://editor.construct.net/r99/main.js:63:495685) at new window.ǃuEu (https://editor.construct.net/r99/main.js:63:501511) at Function.ǃx.ǃr_ (https://editor.construct.net/r99/main.js:2:138919) at a.ǃyr (https://editor.construct.net/r99/main.js:74:28456) at Object.ǃuEi.n.push.ǃx.ǃNx [as ǃhwj] (https://editor.construct.net/r99/main.js:74:28868) at n (https://editor.construct.net/r99/main.js:2:199190) at t (https://editor.construct.net/r99/main.js:2:198976)
Stack: Error: help URL must begin with http:// or https:// at window.ǃCd.ǃuin (https://editor.construct.net/r99/main.js:63:484903) at new window.Plugin (https://editor.construct.net/r99/main.js:63:495685) at new window.ǃuEu (https://editor.construct.net/r99/main.js:63:501511) at Function.ǃx.ǃr_ (https://editor.construct.net/r99/main.js:2:138919) at a.ǃyr (https://editor.construct.net/r99/main.js:74:28456) at Object.ǃuEi.n.push.ǃx.ǃNx [as ǃhwj] (https://editor.construct.net/r99/main.js:74:28868) at n (https://editor.construct.net/r99/main.js:2:199190) at t (https://editor.construct.net/r99/main.js:2:198976)
Construct 3 version: r99
URL: https://editor.construct.net/r99/
Date: Tue May 08 2018 18:14:24 GMT+0200 (Paris, Madrid (heure d’été))
Uptime: 5 s

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r99 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
It definitely does re-fetch the files, because it has to, it doesn't store them anywhere else. Most likely you have some kind of default caching set up on the HTTP server that will keep serving old content for a period of time. Make sure you specify something like `Cache-Control: no-store`.
