### ISSUE TITLE
lang file not/weirdly loaded

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#1557]
## Problem description

I sent an issure report earlier today: 
https://github.com/Scirra/Construct-3-bugs/issues/1555
However upon further investigation it turned out that this was not the issue.
The bug that kept happening was that help-url wasn't in a correct format.
So instead of leaving it in the lang file like so
![image](https://user-images.githubusercontent.com/11213825/39774189-7df0c6f2-52fa-11e8-8449-4bd86caa551d.png)

I put it in the plugin file directly and it worked, like so
![image](https://user-images.githubusercontent.com/11213825/39774223-94b2dda8-52fa-11e8-9913-c7d7f77f85fd.png)

Another issue then popped up:
![image](https://user-images.githubusercontent.com/11213825/39774249-a3b51988-52fa-11e8-8f09-8f0ee3b345f4.png)
Full error below
This is weird because I can assure you that the category is there:

![image](https://user-images.githubusercontent.com/11213825/39774294-bad13598-52fa-11e8-996d-1548160b23ac.png)

Now I'm having a hard time understanding why this happens. My only guess is that the language file isn't being loaded correctly somehow.

## Attach a .c3p

None

## Steps to reproduce

None

## Observed result

See description

## Expected result

This shouldn't happen

## Affected browsers

desktop and chrome versions of C3

## System details

Full error here

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: category language string missing for 'general' @ Error: category language string missing for 'general' at window.ǃQXv.ǃfO (https://editor.construct.net/r98/main.js:63:335622) at window.ǃQAv.ǃQAp (https://editor.construct.net/r98/main.js:63:496084) at a.ǃqc (https://editor.construct.net/r98/main.js:74:28669) at Object.t.push.ǃc.ǃdc [as ǃnSG] (https://editor.construct.net/r98/main.js:74:29042) at t (https://editor.construct.net/r98/main.js:2:198941) at n (https://editor.construct.net/r98/main.js:2:198727)
Stack: Error: category language string missing for 'general' at window.ǃQXv.ǃfO (https://editor.construct.net/r98/main.js:63:335622) at window.ǃQAv.ǃQAp (https://editor.construct.net/r98/main.js:63:496084) at a.ǃqc (https://editor.construct.net/r98/main.js:74:28669) at Object.t.push.ǃc.ǃdc [as ǃnSG] (https://editor.construct.net/r98/main.js:74:29042) at t (https://editor.construct.net/r98/main.js:2:198941) at n (https://editor.construct.net/r98/main.js:2:198727)
Construct 3 version: r98
URL: https://editor.construct.net/
Date: Tue May 08 2018 18:55:11 GMT+0200 (Paris, Madrid (heure d’été))
Uptime: 3.4 s

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
The addon ID is probably wrong, so it's failing to read any strings from the language file at all. The addon ID in the language file is lowercased and yours has an uppercase character, so it's probably that.
