### ISSUE TITLE
Crash when change Frame after resizing and moving collision polygon point in Animations editor

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#1559]
## Problem description

In animations editor, if you resize a frame with option "Apply to whole animation" and move a collision polygon  point, then select the next frame, Construct 3 CRASH.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Create a sprite
2. Duplicate frame 0 
3. resize image 0 (to 400x400 for exemple) with option "Apply to whole animation"
4. Move a collision polygon  point
5 Clic on frame 1

## Observed result

CRASH

## Expected result

No CRASH

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'values' of undefined @ TypeError: Cannot read property 'values' of undefined at Function.ǃrxl (https://editor.construct.net/r99/main.js:74:398412) at u.then.then.then.then.then (https://editor.construct.net/r99/main.js:74:395110)
Stack: TypeError: Cannot read property 'values' of undefined at Function.ǃrxl (https://editor.construct.net/r99/main.js:74:398412) at u.then.then.then.then.then (https://editor.construct.net/r99/main.js:74:395110)
Construct 3 version: r99
URL: https://editor.construct.net/r99/
Date: Wed May 09 2018 00:31:23 GMT+0200 (Paris, Madrid (heure d’été))
Uptime: 63.9 s

Platform information
Browser: Chrome
Browser version: 66.0.3359.139
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
C3 release: r99 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 950 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by NetOneGames** [comment]
Yea I had exactly this last night.  It happed on the second frame where I changed the collision box after resizing all frames using shift.

However I found you can get around by closing and reopening the editor after resize all.  

So there is some instability creeping in after a resize all frames untill you close the animation/sprite  editor.

**Comment by DiegoScirra** [comment]
Fixed in r100.
