### ISSUE TITLE
[R99]Animation Editor - Resizing with a selected and moved piece of the texture leads to a crash

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1561]
## Problem description

If you try to resize the texture after having selected and moved a piece of it (not "validated" in the editor though, still being selected and having changed position), the editor crashes.

## Attach a .c3p

https://kyatric.com/c3/bugs/2018.05.09.Resize_moved_selected.c3p

## Steps to reproduce

1. Open the project
2. Open the sprite in the image editor
3. Select the light pink part of the sprite on the right with the select tool
4. Move the selected part over to the left (0,0 with the intent to reduce the size of the texture and only use this part as the texture)
5. Click the resize button
6. Set the width to 99
7. Validate

## Observed result

C3 crashes

## Expected result

C3 to not crash.
Possibly the texture to resize right away as intended, or possibly a dialog to trigger and indicate you have to "anchor" the moved part of the texture before resizing the whole texture.

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0. @ Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0. at Function.ǃuqT (https://editor.construct.net/r99/main.js:74:426972) at e.ǃuzK.ǃuqc (https://editor.construct.net/r99/main.js:74:224792) at e.ǃuzK.ǃr (https://editor.construct.net/r99/main.js:74:217889) at Array.ǃuqE (https://editor.construct.net/r99/main.js:74:215673) at ǃx.Event.ǃhwE.ǃhwQ (https://editor.construct.net/r99/main.js:2:196306) at e.ǃuUJ.dispatchEvent (https://editor.construct.net/r99/main.js:2:194541) at e.ǃuUJ.ǃix (https://editor.construct.net/r99/main.js:74:152654) at Array.addEventListener (https://editor.construct.net/r99/main.js:74:465303) at ǃx.Event.ǃhwE.ǃhwQ (https://editor.construct.net/r99/main.js:2:196306) at ǃx.ǃh.ǃGf.ǃufX.dispatchEvent (https://editor.construct.net/r99/main.js:2:194541)
Stack: Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0. at Function.ǃuqT (https://editor.construct.net/r99/main.js:74:426972) at e.ǃuzK.ǃuqc (https://editor.construct.net/r99/main.js:74:224792) at e.ǃuzK.ǃr (https://editor.construct.net/r99/main.js:74:217889) at Array.ǃuqE (https://editor.construct.net/r99/main.js:74:215673) at ǃx.Event.ǃhwE.ǃhwQ (https://editor.construct.net/r99/main.js:2:196306) at e.ǃuUJ.dispatchEvent (https://editor.construct.net/r99/main.js:2:194541) at e.ǃuUJ.ǃix (https://editor.construct.net/r99/main.js:74:152654) at Array.addEventListener (https://editor.construct.net/r99/main.js:74:465303) at ǃx.Event.ǃhwE.ǃhwQ (https://editor.construct.net/r99/main.js:2:196306) at ǃx.ǃh.ǃGf.ǃufX.dispatchEvent (https://editor.construct.net/r99/main.js:2:194541)
Construct 3 version: r99
URL: https://editor.construct.net/r99/
Date: Wed May 09 2018 14:51:56 GMT+0200 (Paris, Madrid (heure d’été))
Uptime: 472.1 s

Platform information
Browser: Chrome
Browser version: 66.0.3359.139
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
C3 release: r99 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r100
