### ISSUE TITLE
[Website] Using Special Chars Inside Comments Is Causing Problems

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1564]
## Problem description

Using chars such as "+" and "&" is causing some problems inside comments posted under blogs and similar. There might be more chars but these are the two I frequently use and did tests with.

## Steps to reproduce

**"+" Char issue:**
1. Go to any C3 blog post ([Example](https://www.construct.net/de/blogs/construct-official-blog-1/a-wild-web-developer-appeared-957))
2. Type something and use "+" (e.g. `Test123 + Test321`)
3. Notice that "+" is invisible and not showing up

**"&" Char issue:**
1. Go to any C3 blog post ([Example](https://www.construct.net/de/blogs/construct-official-blog-1/a-wild-web-developer-appeared-957))
2. Type something and use "&" (e.g. `Test123 & Test321`)
3. Notice that "&" is invisible and removed the part of the comment coming after it

## Observed result

Special chars inside comments can cause the char to be invisible or cause comments to partly disappear.

## Expected result

No issues with special chars inside comments.

## Affected browsers

* Chrome: yes/no
* Firefox: yes
* Edge: yes/no
* Safari: yes/no

## System details

* FireFox 60.0 (64-Bit)

**Comment by TomGullen** [comment]
Fixed in v490
