### ISSUE TITLE
[Website | Feature Request] Hide Deleted Comments That Don't Have Any Replies

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1565]
## Problem description

I've noticed that comments in blogs and similar can be deleted and undeleted. While this is a good idea, it should be noted that a lot of these types of comments could result in "spam" and could generally make comment sections look messy.

## Feature Request

I would like to suggest single comments (without any replies), to be hidden to the public after being deleted and only be available for the user that has posted and deleted the comment.

![del](https://user-images.githubusercontent.com/15656049/39873411-22175fc2-546b-11e8-93d1-a94c9d961931.PNG) _(Removing these from public view is what I mean, just in case.)_

**Comment by AshleyScirra** [comment]
Migrated to https://github.com/Scirra/Construct.net-website-bugs/issues/2
