### ISSUE TITLE
email links no longer work.

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#1566]
## Problem description

I'm signed up to get emails from construct.net but recently any links for new updates or blog posts and i get this error.

Server Error in '/' Application.

The resource cannot be found.

Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /wf/click

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.2623.0

## Attach a .c3p

website issue

## Steps to reproduce

1.
2.
3.

## Observed result

can't get to website

## Expected result

access linked page

## Affected browsers

* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by TheRealDannyyy** [comment]
Same for me, I assume this was one time thing because the 1st version of the blog post got deleted for reasons unknown? Here is a screenshot of the same message:

![errormessage](https://user-images.githubusercontent.com/15656049/39878673-3464d8b8-5479-11e8-8682-5ed47c0b6aed.PNG)

**Comment by mOOnpunk** [comment]
It appears to happen on all links for me, including when they post a new version of c3.

**Comment by AshleyScirra** [comment]
Migrated to https://github.com/Scirra/Construct.net-website-bugs/issues/3
