### ISSUE TITLE
[Website] Sub-Comments Can Be Edited Even If You're Not The Owner

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1567]
## Problem description

It's possible to edit sub-comments by others in comment sections of blogs and similar. Although it will trigger an error message while saving so this is mainly just a visual bug and not critical. 
(This bug does especially occur after clicking on "Load more comments" but it seems to be random.)

## Steps to reproduce
1. Go to any C3 blog post ([Example](https://www.construct.net/de/blogs/construct-official-blog-1/a-wild-web-developer-appeared-957))
2. Go to any comment with one or more sub-comment(s)
3. Notice that you can edit sub-comments depite not being the owner

## Observed result

**Example 1 (3+ sub-comments):**

![editbug](https://user-images.githubusercontent.com/15656049/39879098-44abf1b0-547a-11e8-9504-14670cb60fab.PNG)

**Example 2 (Single sub-comment by Admin):**

![editbug2](https://user-images.githubusercontent.com/15656049/39879107-491cfac8-547a-11e8-890d-d43144f522f1.PNG)

**Example 3 (Single sub-comment by User):**

![editbug3](https://user-images.githubusercontent.com/15656049/39879119-4d741778-547a-11e8-90ce-35df443cfd99.PNG)

## Expected result

You should not be able to edit or see the edit button for comments not posted by yourself.

## Affected browsers

* Chrome: yes/no
* Firefox: yes
* Edge: yes/no
* Safari: yes/no

## System details

* FireFox 60.0 (64-Bit)

**Comment by AshleyScirra** [comment]
Migrated to https://github.com/Scirra/Construct.net-website-bugs/issues/4
