### ISSUE TITLE
[Website] Weird Grey Circle Next To The "Report" Button

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1568]
## Problem description

I've noticed that there is a weirdly aligned grey circle next to the report button. Not sure if intentional or not but it's looking a bit out of place to me.

## Steps to reproduce

1. Go to any C3 blog post ([Example](https://www.construct.net/de/blogs/construct-official-blog-1/a-wild-web-developer-appeared-957))
2. Go to any comment

## Observed result

**Grey Circle Example:**

![reportcircle](https://user-images.githubusercontent.com/15656049/39880194-4ee11bda-547d-11e8-9386-9baca236b9ad.PNG)

## Expected result

This is a tricky one since I don't really know what it does. The HTML code says it's for counting so I assume it will display the amount of reports that a comment received? If that's the case, I personally find that information to be unnecessary for the public since bad/negative comments will be judged by negative ratings anyway in my opinion. 

If you guys decide to keep this feature, I'd recommend only showing it to the owner of the comment and admins. At least doing it in this way, _keyboard wars_ in the comment sections like: "HAHA YOU GOT REPORTED X TIMES AND I DIDN'T!!!" could be avoided, I'm sure you guys get what I mean.

## Affected browsers

* Chrome: yes/no
* Firefox: yes
* Edge: yes/no
* Safari: yes/no

## System details

* FireFox 60.0 (64-Bit)

**Comment by TomGullen** [comment]
Should be fixed.
