### ISSUE TITLE
[r24] umm... what happend?

### ISSUE THREAD

**Issue by cori6487** [Scirra/Construct-3-bugs#157]
## Steps to reproduce

1.leave c3 idle for 30 minutes
2. clear browser cache
3. software crash

## Observed result

it crashed

## Expected result

for it to save my c3p to google drive

## Affected browsers

* Chrome: yes

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. @ Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. at https://editor.construct.net/r24/main.js:2:7401 at 
Stack: Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. at https://editor.construct.net/r24/main.js:2:7401 at 
Construct 3 version: r24
URL: https://editor.construct.net/
Date: Fri May 05 2017 17:48:27 GMT-0700 (Pacific Daylight Time)
Uptime: 304.5 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.96
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 2
User agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce 405 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Clearing the cache with C3 open doesn't seem like a normal use case, and it's probably difficult to fix this since it means any storage access anywhere in the editor could fail at any time, so closing as won't fix. Just make sure C3 is closed before clearing your browser cache.
