### ISSUE TITLE
Objects with bullet change angle depending on the time scale

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1570]
## Problem description

If the time scale is set to "0" (for pausing or something like that) every object that have the bullet behaviour will change it's angle to "0", but when the time scale is set back to "1" everything will go back to what it was before.

## Attach a .c3p

[Bullet bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1993309/Bullet.bug.zip)

## Steps to reproduce

1. Add an object with the bullet behaviour.
2. Change the time scale from "1" to "0" during runtime.

## Observed result

Every object that have the bullet behaviour will change it's angle to "0".

## Expected result

Every object that have the bullet behaviour to keep it's current angle unaffected.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by BonzerKitten7** [comment]
Here's a little .gif just to show what's happening: https://i.imgur.com/r6bsJPX.gif

**Comment by zumwaltwood** [comment]
Uncheck set angle on bullet behavior, that seem to be implied, I’ve adjusted the angle several times and the angle naturally applies without that checked, although probably still a bug and not designed behavior

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.

**Comment by BonzerKitten7** [comment]
Nice! Thank you, Ashley.
