### ISSUE TITLE
C3 runtime set layout angle bugged

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1571]
## Problem description

Set Layout angle in C3 runtime does not work.

## Attach a .c3p

[rotateC3.zip](https://github.com/Scirra/Construct-3-bugs/files/1993606/rotateC3.zip)

## Steps to reproduce

1. Add keyboard to project
2. Add event, on key pressed set layout angle +- "some number"
3.Layout starts to shake. Same thing works in C2 runtime.

## Observed result

Layout starts to shake itself

## Expected result

Like in C2 runtime, sets new layout angle which can be used to rotate layout.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Should be fixed in the next release.
