### ISSUE TITLE
Publish HTML5 doesn't work in all browsers

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1575]
## Problem description

*Enter a concise description of your problem here*
Testing publishing, my project is far from complete but here is the URL:

http://www.cyborgsattack.com/

Now, I have tried with using SSL generic certificate and it wouldn't load at all so I am working through that problem, but a few issues happen when loading the game, Edge won't load at all, it sticks at the loading screen about 85% done it appear, but in Chrome it loads fully, first time through it didn't load all the sound affects, second time, it had the sound affects on a refresh.

This is made for mobile, but you can use the mouse, just touch and hold down to move around the screen, hold over the green, yellow and red blocks to build turret instantly, for now these are your enemies.. refresh when you die to load again for now, no additional maps or anything yet, WIP.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
Test with any project publish, even the ghost tutorial project.
## Steps to reproduce

1. Publish to HTML5
2. Upload to a server
3. Browse to the game

## Observed result

*What do you see happen?*
Doesn't load completely on Edge, hangs about 85% done.
Loads in Chrome, but sounds do not load the first time, have to refresh and load again to get sounds.
Loads just fine in FireFox
## Expected result

*What did you expect to happen instead?*
Load without issues

## Affected browsers

* Chrome: yes - Sound issues
* Firefox: no
* Edge: yes - doesn't finish loading, hangs on load screen
* Safari: yes - doesn't finish loading, hangs on load screen

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 66.0.3359.139
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
C3 release: r99 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 23 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by zumwaltwood** [comment]
Related issue to this, I just loaded the project on my iPad from saving to my dropbox, since I have been working in Chrome at home after adding the Audio, well, on the Safari editor, the sounds will not play at all, so I think the issue is related to Audio all together, the Audio is dead, as in even the Audio Preview doesn't play the Audio on the iPad in Safari.

**Comment by zumwaltwood** [comment]
It does load and work in chrome on my galaxy s7, ironically, but that's actually logical since it is chrome and you've geared all this towards chrome it appears, kind of a challenge running around getting all the turrets activated without dying

**Comment by AshleyScirra** [comment]
Can't reproduce here, it loads just fine in Edge. The fact Chrome doesn't play audio immediately is due to their new autoplay restrictions. You must touch/click/press a key before it allows audio playback.

**Comment by zumwaltwood** [comment]
Still doesn't load in edge or safari on this end at all on published version, hangs, on the ipad tablet i can run but no sound in safari when using the editor test play, i can test play in edge, do not use the editor to test, use only a publish version, it's a problem with published versions

**Comment by zumwaltwood** [comment]
We have reproduced the no play issues on 2 iphones and 1 ipad, it refuses
to finish loading in safari with the latest OS and newest devices, and one
desktop running Windows 10 and two laptops running windows 10, refuse to
finish loading in edge

**Comment by zumwaltwood** [comment]
FYI this is a total load fail on every iPhone in my house, mine, my wife’s and my kids, and a total fail on our Apple tablets. Look at my other bug I just posted about sound import, I think these are totally related issues.

**Comment by AshleyScirra** [comment]
It fails to load in Safari because the following file on your server, necessary for it to function in Safari, returns 404 not found: http://cyborgsattack.com/opus.wasm.wasm

Either you forgot to upload this file, or the server is not serving it, which would usually be because the MIME type configuration is incorrect. Please refer to https://www.construct.net/tutorials/publishing-to-the-web-10 and https://www.construct.net/make-games/manuals/construct-3/tips-and-guides/mime-types

**Comment by zumwaltwood** [comment]
I upload the entire project, I will check mime type
