### ISSUE TITLE
Import Audio and import music fails

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1576]
## Problem description

*Enter a concise description of your problem here*
Trying to import audio into project fails on iPad, never leaves queu pending state, i think this is a related issue to failing to load audio with games in safari for any Apple device of a web hosted game.

I‘ve just uploaded a movie to YouTube!
You can check it out here:
http://www.youtube.com/watch?v=H83CwfwS5vY

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
[ghost shooter.zip](https://github.com/Scirra/Construct-3-bugs/files/1998870/ghost.shooter.zip)

## Steps to reproduce

1. Open any project in your iPad
2. Try to add audio, music or sound effect
3.

## Observed result

*What do you see happen?*
Queued but never loads

## Expected result

*What did you expect to happen instead?*
Music or sound effect added to project

## Affected browsers

* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r98 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A10X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by AshleyScirra** [comment]
Fixed for r100. Issue is just that something in emscripten's code uses `Module["buffer"].slice()`, whereas Safari expects at least one argument (i.e. `Module["buffer"].slice(0)`). MDN does seem to specify that the ArrayBuffer slice method first argument is not optional, but other browsers seem to be relaxed about it and accept it (in line with Array slice()). However this looks like it's in emscripten generated code, so leaving open for Iain to check if there's a way to apply that fix to the generated code, otherwise the next time it's built it will reinsert broken code again.

**Comment by shortercode** [comment]
@AshleyScirra from the segment you've shown I'm reasonably sure that it's from my code to store the initial state, not the emscripten generated code.

I looked through the docs, ArrayBuffer seems to have the only `slice(start,end)` implementation ( TypedArray, Array, Blob, etc. ) where the first value is **not** optional. So I guess this is safari being the only one sticking to the spec and me just not knowing!

I'll take a look at the source to fix this before closing the issue, but the audio encoder is unlikely to be changed anytime in the next few months.

**Comment by zumwaltwood** [comment]
This is now working and I just tested in R100, thanks

**Comment by AshleyScirra** [comment]
@shortercode can this be closed now?

**Comment by zumwaltwood** [comment]
Yes

**Comment by shortercode** [comment]
It can be now, just moved the current encoder build to the main repo.
