### ISSUE TITLE
Cannot add any add-on in "Developer Mode"

### ISSUE THREAD

**Issue by jarvisjang** [Scirra/Construct-3-bugs#1577]
## Problem description

I cannot add my custom add-on on the developer mode.
I didn't change anything from the origin c3-behavior-sdk-1.2.zip.
Yes, I just unzip it, and just added it.

## Steps to reproduce

1. unzip c3-behavior-sdk-1.2.zip
2. Enable Developer Mode and Run the local server.
3. Add the behavior.

## Observed result
Error report information
Type: unhandled rejection
Reason: Error: invalid addon id @ Error: invalid addon id at a.ǃQAH (https://editor.construct.net/r98/main.js:74:28159) at t.ǃmJ (https://editor.construct.net/r98/main.js:63:513271) at ǃc.ǃmr.addEventListener (https://editor.construct.net/r98/main.js:74:11888) at Object.n.push.ǃc.ǃdc [as ǃnSG] (https://editor.construct.net/r98/main.js:2:196515) at t (https://editor.construct.net/r98/main.js:2:198941) at n (https://editor.construct.net/r98/main.js:2:198727)
Stack: Error: invalid addon id at a.ǃQAH (https://editor.construct.net/r98/main.js:74:28159) at t.ǃmJ (https://editor.construct.net/r98/main.js:63:513271) at ǃc.ǃmr.addEventListener (https://editor.construct.net/r98/main.js:74:11888) at Object.n.push.ǃc.ǃdc [as ǃnSG] (https://editor.construct.net/r98/main.js:2:196515) at t (https://editor.construct.net/r98/main.js:2:198941) at n (https://editor.construct.net/r98/main.js:2:198727)
Construct 3 version: r98
URL: https://editor.construct.net/
Date: Mon May 14 2018 21:18:55 GMT+0900 (KST)
Uptime: 2.1 s

Platform information
Browser: Chrome
Browser version: 66.0.3359.139
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Expected result

Behavior should be added correctly.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

**Comment by AshleyScirra** [comment]
Can't reproduce here, the SDK download works OK. The default addon ID is `MyCompany_MyBehavior` which is definitely valid, but for some reason the error reports an invalid addon ID. It must be that you've either already got an addon with the same ID installed, or the HTTP server is incorrectly configured. Check your MIME types and that there aren't further errors in the browser console.
