### ISSUE TITLE
Import Font Crush

### ISSUE THREAD

**Issue by Coyowl** [Scirra/Construct-3-bugs#158]
## Problem description

Crash on pressing Esc twice when font window is open

## Steps to reproduce

1. Create new project
2. Import font 
3. Press Esc twice

## Observed result

*What do you see happen?*
Crash
## Expected result
Not crash
*What did you expect to happen instead?*
Close import font window
## Affected browsers
* Chrome: yes
## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r24/main.js, line 2, col 350870
Message: Uncaught InvalidStateError: Failed to execute 'close' on 'HTMLDialogElement': The element does not have an 'open' attribute, and therefore cannot be closed.
Stack: Error: Failed to execute 'close' on 'HTMLDialogElement': The element does not have an 'open' attribute, and therefore cannot be closed. at ǃV.ǃz.ǃu.ǃXyA.ǃeCX (https://editor.construct.net/r24/main.js:2:350870) at Animation.ǃeSA.onfinish (https://editor.construct.net/r24/main.js:2:350293)
Construct 3 version: r24
URL: https://editor.construct.net/index.html
Date: Sun May 07 2017 11:52:00 GMT+0100 (GMT Daylight Time)
Uptime: 18.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.96
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.800000011920929
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 580 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r25.
