### ISSUE TITLE
Copy as text blows up

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1582]
[ghost shooter.zip](https://github.com/Scirra/Construct-3-bugs/files/2005089/ghost.shooter.zip)
## Problem description

*Enter a concise description of your problem here*
I wanted to copy an event as text, so I held down on the event in the event list, got the pop up menu, did copy as text and this just crashed, I tried it in the ghost demo project also and received the same problem.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open project
2. Open event sheet
3. Select an event
4. Select copy as text

## Observed result

*What do you see happen?*
Unhandled error
## Expected result

*What did you expect to happen instead?*
Event copied as text to clipboard
## Affected browsers

* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: undefined
Construct 3 version: r99
URL: https://editor.construct.net/r99/
Date: Tue May 15 2018 08:05:39 GMT-0500 (CDT)
Uptime: 1748.4 s

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r99 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A10X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions: EXT_blend_minmax, EXT_sRGB, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_standard_derivatives, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context, WEBKIT_WEBGL_compressed_texture_pvrtc, WEBGL_depth_texture, ANGLE_instanced_arrays, WEBGL_debug_renderer_info

</details>

**Comment by AshleyScirra** [comment]
Looks like same issue as #1574. We just released r100 which should fix it, can you test again there?

**Comment by zumwaltwood** [comment]
Doesn’t blow up, but doesn’t copy the event as text to the clipboard.

**Comment by AshleyScirra** [comment]
I think Safari has blocked access to the clipboard. I'm not sure there's any workaround if the browser doesn't let us copy text.

**Comment by zumwaltwood** [comment]
Regular copy/paste of an event is working so that solved #1574
