### ISSUE TITLE
Feature request: scroll bars in layout window

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1584]
You have them on the regular desktop, but the mobile mode and desktop mode do not have scroll bars in layout window, I’ve had a lot of trouble trying to zoom in and out plus move around the layout on the iPad with multi touch, life would be so much easier with horizontal and vertical scroll bars for the layout window in desktop mode on the tablet. They don’t exist in safari on the iPad like they do in chrome on the desktop.

Thanks for your consideration.

**Comment by AshleyScirra** [comment]
It's entirely up to the browser if scrollbars appear. On desktop systems the scrollbars are visible, but mobile platforms differ from desktop systems that they don't show visible scrollbars for scrollable content. This is a deliberate design decision at the operating system level and is consistent across all apps.
