### ISSUE TITLE
Spritefont characters erase overlapping pixels in the new runtime

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#1585]
## Problem description

Spritefont characters erase overlapping pixels in the new runtime

## Attach a .c3p
https://puu.sh/AmFf5/b93701bbd9.c3p

## Steps to reproduce

1. Preview the layout using the construct 2 runtime
2. Preview the layout using the construct 3 runtime

## Observed result

Using the construct 2 runtime the spritefont text looks great,
Using the construct 3 runtime the text look like shit.

## Expected result

I expected the text to look awesome with the construct 3 runtime

## Affected browsers

* Chrome: yes
* Firefox: yes

## System details

<details><summary>View details</summary>

Windows 10

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release. Note it affected the editor too so it's fixed for both editor and C3 runtime.
