### ISSUE TITLE
Missing 'Your licenses' link on mobile website

### ISSUE THREAD

**Issue by KioriSun** [Scirra/Construct-3-bugs#1586]
I dont not see anymore an easy way to access the licenses page. I think it used to be in the profile page somewhere, now it's nowhere to be found, i can only access it via the construct editor, by clicking on my avatar and 'view details', then 'Your Licenses'. Which leads [here](https://www.construct.net/profile/licenses) as expected.

I hope you guys re-add it somewhere or point out my mistake if i've missed it. In the meantime i've bookmarked the page.

Thanks

**Comment by zumwaltwood** [comment]
Can you also add our C2 license to the license page and not just our C3 license?

**Comment by AshleyScirra** [comment]
There is a 'Your licenses' link in the profile menu. However it looks like it's missing from the mobile site. I assume you were looking on a mobile device?

**Comment by zumwaltwood** [comment]
Nope, from the website, and it doesnt show my C2 license. It does show my
C3 license

**Comment by AshleyScirra** [comment]
Construct.net currently only shows C3 licenses. Showing C2 licenses is a different issue and not covered by this issue: the poster was talking about a missing website link.

**Comment by AshleyScirra** [comment]
Migrated to https://github.com/Scirra/Construct.net-website-bugs/issues/5
