### ISSUE TITLE
Origin points change position incorrectly after cropping entire animation, but only with the frames you didn't look at 

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#1587]
Same issues we had last year, for some reason it's back. Using latest beta.

#932

**Comment by DiegoScirra** [comment]
I had a feeling I broke something else when I fixed #1469. But I couldn't recall exactly what.

**Comment by DiegoScirra** [comment]
I can't reproduce the problem with the steps in #932, it looks like it is working fine.

Are you doing the exact same thing?

**Comment by alastajj** [comment]
[mover.zip](https://github.com/Scirra/Construct-3-bugs/files/2008394/mover.zip)

- Open frame 1
- place hotspot near bottom left
- apply hotspot to whole animation
- shift + crop whole animation
- do not change frame
- press Preview animation and look at the animation bounce, when it should be staying the same
- then click on each frame individually, then preview the animation again and notice that it's now healed

**Comment by DiegoScirra** [comment]
Right, that is not working properly

**Comment by DiegoScirra** [comment]
Fixed in r101.

Everything should be working now.
