### ISSUE TITLE
Blog post posted 17 years ago

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#1588]
Website bug
Hi,
There is a weird bug on the website's blogging system. I posted an article yesterday and it worked pretty well, but today, I found out that the website duplicated it twice, and marked them as being posted 17 years ago. I'm pretty sure this is not supposed to happen.

![image](https://user-images.githubusercontent.com/11213825/40106670-a7f4d11c-58f6-11e8-8546-6b11f07816aa.png)

**Comment by AshleyScirra** [comment]
I'm not sure @TomGullen intended to ship the public blog platform yet. Which links did you follow to create and post a blog?

**Comment by skymen** [comment]
It's on the main page x)
![image](https://user-images.githubusercontent.com/11213825/40112972-1dbd69de-5908-11e8-8d77-71bac7a87fe4.png)

**Comment by skymen** [comment]
@shortercode Yes! Stacks are super useful for tons of stuff :D.
I think that it's important to talk about code so you can understand what goes behind C2's visual coding. Imo this helps make it less abstract for people who never coded.

Also thanks! I didnt know about his work I'll definitely check it out! :)

**Comment by AshleyScirra** [comment]
Migrated to https://github.com/Scirra/Construct.net-website-bugs/issues/6
