### ISSUE TITLE
Cannot add Dev Add-ons.

### ISSUE THREAD

**Issue by jarvisjang** [Scirra/Construct-3-bugs#1589]
## Problem description

**This issue happened today. Everything was okay until yesterday.**

## Steps to reproduce

1. Enable Developer Mode
2. Add my plugin that under developing ( using Add dev addon button)
3. [Loaded successfully. I can see the plugin in the Add-on Manager. And no errors]
4. Create or open a project.
5. Add new object

## Observed result

**I cannot see my plugin! It is based on the SingleGlobal.**

## Expected result

**My plugin should be shown**
**Until yesterday, everything was okay.**

## Affected browsers

* Chrome: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by jarvisjang** [comment]
I found the reason. Because I deleted 'c2runtime'.
Actually, my plugin is only for c3runtime. Why should I add c2runtime?
And.. when I run the project, It tries to run c2runtime instead of c3runtime.
Is the c3runtime available???

**Comment by AshleyScirra** [comment]
If your plugin only supports the C3 runtime, it will only appear when you change the runtime property of the project to the C3 runtime.
