### ISSUE TITLE
[r24] Editor remembers preview window size

### ISSUE THREAD

**Issue by glerikud** [Scirra/Construct-3-bugs#159]
## Problem description

I don't know that it's intentional or not, but the editor remembers the preview window size if the user resized it during a previous preview. This poses some problems if the project's fullscreen mode is off.

## Attach a .c3p

It's an editor bug/problem and it happens with a brand new empty project as well.

## Steps to reproduce

1. Create a new project or open an existing one.
2. Turn the fullscreen mode off in the project's settings.
3. Preview the project.
4. Resize the preview window then close it.
5. Preview again.

## Observed result

The preview window remembers it's previous size. This is a problem when the user wants to develop a project with fullscreen mode turned off since she has to resize the preview window carefully to get the full project displayed again. Or if during the resizing the preview window was made bigger, the user has to carefully resize it again to avoid displaying the background during preview. An other solution is to restart the editor.

## Expected result

There should be either an option to automatically resize the preview window to the viewport's size or an option included in the editor to make the preview window forget it's previous state.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 7.7 gb
Storage usage (approx): 124 mb (1.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by jaydonteh** [comment]
It has been discussed here: https://github.com/Scirra/Construct-3-bugs/issues/84

**Comment by glerikud** [comment]
Oh I see, the preview as a browser tab does solve this issue, thank you. However I think since this answer is not too straightforward, there will be posts like mine in the future. Maybe some side-note could be helpful in the settings window.

**Comment by AshleyScirra** [comment]
I've changed it for r25 so when fullscreen mode is off, it always uses the default window size.

**Comment by glerikud** [comment]
Awesome, thank you for fixing this.
