### ISSUE TITLE
Resizing with "smooth" make a black sprite

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#1590]
## Problem description

In animations editor, resizing an image with smooth make all pixels black.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Create a sprite with a colored picture.
2. Use resize option (Alt+R)
3. Make a larger image with Stretch and smooth option

## Observed result

Black image

## Expected result

The same image. Larger.

## Affected browsers

* Chrome: yes/

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Picoti** [comment]
Hi!
Hm... ok.. It's weird.
Perhaps it's a problem with my graphics card? But it work fine with photoshop...
On construct, when I resize image Canvas with option image "stretch" and "Smooth", the image became black...

**Comment by Picoti** [comment]
OK. very strange.
I tried on another computer and it work fine...
I ghave made the Windows 10 update yesterday. Can that be it?

**Comment by DiegoScirra** [comment]
Hmm... I won't lie, I have no idea.

Can you post your platform information from the **About** dialog, it might be useful to investigate this.

**Comment by Picoti** [comment]
Platform information
Browser: Chrome
Browser version: 66.0.3359.139
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
C3 release: r100 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 1.6 gb (5.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 950 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by Picoti** [comment]
and on this computer the problem is the same with mozilla firefox.

**Comment by DiegoScirra** [comment]
Are you able to see any error messages in Chrome's dev tools when this happens? To bring up dev tools just press **(Ctrl + Shift + I)**

This sounds like a strange graphics driver bug, have you updated your drivers recently?

**Comment by Picoti** [comment]
![driver](https://user-images.githubusercontent.com/28705150/40245201-3a456570-5ac5-11e8-99cb-90c042519708.png)

Yes, I thought about this for the graphics driver, so I update my drivers on 7/5/2018 as you can see on the attached file. But the problem remains the same ... very strange bug. And apparently just for me ^^

**Comment by Picoti** [comment]
And it seems there are no error messages in the chrome's dev tool :

![devtool](https://user-images.githubusercontent.com/28705150/40245593-7bf73042-5ac6-11e8-89e5-d2cb11d4cf8c.png)

**Comment by DiegoScirra** [comment]
Make sure to look in the **Console** tab at the bottom, that is where any errors will be logged.

**Comment by Picoti** [comment]
In the console nothing appear. Just this message :

Stop!
main.js:168 This is a browser feature intended for developers. If someone told you to copy and paste something here to enable a feature or "hack" something, it is a scam and may allow them to steal your account information or your work.

**Comment by Picoti** [comment]
Oh ! I go back to r98 and it work fine ! This bug appear only on r100

**Comment by DiegoScirra** [comment]
Can you post the image you are using? Maybe there is something about it.

**Comment by DiegoScirra** [comment]
Ok, I was able to reproduce it, it seems that it is only happening in the release build, there must be some problem with the minification.

**Comment by Picoti** [comment]
OK :-)

**Comment by el3um4s** [comment]
I have the same problem with r101 (linux and Windows 10)

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r101 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 340 mb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

![gif](https://lh3.googleusercontent.com/YFrQKXurqam6TkR_2e5A7sNMGNL_ERupClBlLErNFA_VgfYkL-CHyl0WzksXJdvgGxoSPMkGMKQrsxuEeVf_g3vrBISFToqO_dF-H48H9qOW0OXffiwdEBVtKoKil5pIfzjCYRjkBNs=w752-h577-no)

**Comment by DiegoScirra** [comment]
Is this still happening in r102?

I was about to start working on this, and it seems like it is working fine in the latest version.

**Comment by Picoti** [comment]
YES Diego.
It work fine now on r102. Thanks !

**Comment by DiegoScirra** [comment]
I didn't do anything to fix this one, so I'll leave it open to check it again in later versions.

**Comment by luckyrawatlucky** [comment]
@DiegoScirra 
I got this issue in r152
resizing image with smooth makes all pixels black.
