### ISSUE TITLE
Can't add a number to a global variable 

### ISSUE THREAD

**Issue by NattiL** [Scirra/Construct-3-bugs#1594]
## Problem description

*I have been working on a project for a while and today I purchased the software (Construct 3 for individuals). Now, the global variables in my program doesn't change even if the right condition is met (I tried new variables too and new conditions). I started a new project, tried something similar, and it DOES work. It just doesn't work on the project I already started while I used the trial software. I don't want to start the project all over again. 

## Observed result

*My program doesn't work*

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Please see the guidelines for how to file bugs. If you just need help using Construct, please post to the forum instead.
