### ISSUE TITLE
[Website] Double C3 license holder marker

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#1596]
Basically, for some reason, the fact that a user owns a C3 license is shown twice, with a smaller one on top of the other:

![2018-05-17_15-07-45](https://user-images.githubusercontent.com/11213825/40179280-3b73b578-59e4-11e8-9781-302f7c21b4fe.gif)

![2018-05-17_15-10-34](https://user-images.githubusercontent.com/11213825/40179379-795eed08-59e4-11e8-8b6f-fc32161a39a7.gif)

![2018-05-17_15-12-26](https://user-images.githubusercontent.com/11213825/40179474-bad8d6fe-59e4-11e8-800a-bd03e8a72bf7.gif)

**Comment by AshleyScirra** [comment]
Migrated to https://github.com/Scirra/Construct.net-website-bugs/issues/8
