### ISSUE TITLE
Edit blog is not working

### ISSUE THREAD

**Issue by pooyaGames** [Scirra/Construct-3-bugs#1597]
When i try to edit my blog or after creating one i see this page 
![screenshot 2018-05-17 19 26 07](https://user-images.githubusercontent.com/426713/40185636-4aa20d78-5a08-11e8-9948-de5c274aded1.png)

**Comment by AshleyScirra** [comment]
Migrated to https://github.com/Scirra/Construct.net-website-bugs/issues/9
