### ISSUE TITLE
No repro crash when changing sprite frame after modifying collision poly

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1599]
## Problem description

So a crash related to collision polygons hasn't happened to me in a few months or more. I can't reproduce this. I modified the previous frame's collision polygons then quickly changed frame and it crashed. Maybe the error code gives you an idea.

## Attach a .c3p

![image](https://user-images.githubusercontent.com/7268697/40194603-b134587e-5a13-11e8-86f7-2f3b3205a584.png)

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'values' of undefined @ TypeError: Cannot read property 'values' of undefined at Function.ǃBch (https://editor.construct.net/r98/main.js:74:395237) at i.then.then.then.then.then (https://editor.construct.net/r98/main.js:74:391932)
Stack: TypeError: Cannot read property 'values' of undefined at Function.ǃBch (https://editor.construct.net/r98/main.js:74:395237) at i.then.then.then.then.then (https://editor.construct.net/r98/main.js:74:391932)
Construct 3 version: r98
URL: https://editor.construct.net/index.html
Date: Thu May 17 2018 20:34:55 GMT+0300 (GTB Daylight Time)
Uptime: 21054.8 s

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Assigning @DiegoScirra to look at crash signature. May not be solvable without steps to reproduce though.
