### ISSUE TITLE
C3 Runtime Hangs up during remote preview

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#1600]
## Problem description

I have a kindle fire HD 6 (4th Generation) and any project, even an empty project fails to preview with the c3 runtime

Since there is no way to export yet, im afraid that the new runtime simply dosent work on some devices when the c2 runtime does

## Attach a .c3p

https://puu.sh/Ao1IP/e625419277.c3p

## Steps to reproduce

1.Switch to the c3 runtime
2. Remote preview using an old android device

## Observed result

The construct 3 remote preview starts and goes all the way up to loading scripts and the percentage increases, but then it goes back to and gets stuck on "loading scripts...(0%)"

## Expected result

I expected remote preview to work 

## Affected browsers

Silk Browser ( ???) No

## System details
Application Version 65.5.3.3325.144.10
Operating system Android 5.1.1 ; KFARWI Build/LVY48F

**Comment by AshleyScirra** [comment]
FYI we are aggressively targeting modern browsers only for the C3 runtime. I'll look in to this but the if it's just an old browser with a missing feature then the conclusion may be to not support it in the C3 runtime.

**Comment by AshleyScirra** [comment]
Can't reproduce on a Samsung Galaxy Tab S2 running Android 5 which I think is the nearest in spec to that. We don't have the specific device to test I'm afraid, but I suspect it's just an out-of-date browser that doesn't support the necessary features. If it's important to you to keep supporting old devices then you might want to stick to the C2 runtime for the time being.

**Comment by eleanorawesome** [comment]
Platform information
Browser: Silk
Browser version: 65.5.3
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Android
Operating system version: 5.1.1
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 1 GB
User agent: Mozilla/5.0 (Linux; Android 5.1.1; KFARWI Build/LVY48F) AppleWebKit/537.36 (KHTML, like Gecko) Silk/65.5.3 like Chrome/65.0.3325.144 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 277 mb
Storage usage (approx): 19 mb (6.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

The Clipboard API is not supported. Some clipboard features may be unavailable.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Imagination Technologies
Renderer: PowerVR Rogue G6200
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_pvrtc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
