### ISSUE TITLE
Can't use F2 or CTRL + A with image points

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1602]
## Problem description

Some shortcuts are not working with image points, you can't use F2 to rename the image point or CTRL + A to highlight it's whole name.

## Attach a .c3p

None

## Steps to reproduce

1. Create a sprite object.
2. Add a image point to your sprite.
3. Try to rename it by pressing F2 and try to highlight it's name by pressing CTRL + A.

## Observed result

The F2 and CTRL + A shortcuts are irresponsible.

## Expected result

The F2 and CTRL + A shortcuts to work like in Construct 2.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Can't recall off the top of my head, but I don't think F2 is even implemented to rename image points. As for Ctrl + A to select all, I suspect the default behavior of the browser is being overriden for reasons that escape at the moment.

**Comment by BonzerKitten7** [comment]
Sorry for taking so long to reply, i had a busy weekend. Well, i thought that it was a bug because you can rename objects, animations, sounds, and many more with F2 and highlight any kind of name or text in the entire editor with CTRL + A, so it was a bit weird to not be able to do so with image points. Anyway, it would be nice to have these shortcuts available for every aspect of the editor, but it's ok if it's not possible.

**Comment by DiegoScirra** [comment]
Added in r103
