### ISSUE TITLE
Fullscreen On Joypad Button Press

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1606]
## Problem description

Fullscreen On Joypad Button Press

cant seem to get it working

## Attach a .c3p

[Fullscreen on Joypad Button Press.zip](https://github.com/Scirra/Construct-3-bugs/files/2019823/Fullscreen.on.Joypad.Button.Press.zip)

## Steps to reproduce

1.  Plug in Joypad (tested with xbox type pad)
2.  Load up the atached c3p (file extension changed to zip)
3. Press (a) for full screen

## Observed result

No full screen

## Expected result

Full screen ?

## Affected browsers

* Chrome: yes (only tested) 

## System details

C3 (C2 runtime) R100
Version 66.0.3359.181 (Official Build) (64-bit)
Surface Pro 4 Win 10

**Comment by AshleyScirra** [comment]
This is a Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=381596

It's being worked on.

**Comment by NetOneGames** [comment]
wow open since 2014!

I had to leave a narky comment....
