### ISSUE TITLE
Crash when importing specific json file (too long? corrupted?)

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1607]
## Problem description

Crash when I attempt to open this .json file. If I delete all of the data except the first two and adjust the width to 2 it opens up fine. Not sure if it is the lenght or if the file is somehow corrupted.

## Attach a .c3p

[corrupt.json](https://github.com/Scirra/Construct-3-bugs/files/2019859/corrupt.json.zip)

## Steps to reproduce

1. Import the attached file
2. Try to edit it in construct

## Observed result

Crasherino

## Expected result

No Crasherino

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Unable to setup text editor @ Error: Unable to setup text editor at a.then.catch (https://editor.construct.net/r98/components/editors/textEditor/textEditor.js:1:3957)
Stack: Error: Unable to setup text editor at a.then.catch (https://editor.construct.net/r98/components/editors/textEditor/textEditor.js:1:3957)
Construct 3 version: r98
URL: https://editor.construct.net/index.html
Date: Sun May 20 2018 00:37:36 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 574 s

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
How did you generate this file?

**Comment by shortercode** [comment]
Okay I've put a fix in for the bug, which will be available in r101. It will now follow the correct behaviour, which is to open the text editor instead.

**Comment by Wackytoaster** [comment]
@shortercode 
Nice, thanks! 👍 

Well I gotta admit I frankensteined that file from some data I found online, to no success as you saw. But if my fail lead to the fixing of a bug, that´s fine in my book.

**Comment by shortercode** [comment]
Ironically the fix also threw up another bug, so it was a double whammy.

It wasn't too far off, just had those properties in the wrong order.
