### ISSUE TITLE
[r24] Double click selection problem in the add global variable dialog

### ISSUE THREAD

**Issue by glerikud** [Scirra/Construct-3-bugs#161]
## Problem description

This is just a minor inconvenience, but when the user is in the "Add global variable" dialog, the input field values can only be selected with double click if the user double clicks especially on the value. This should work while double clicking the entire input field (just like it works in some other input fields in the editor). I found no pattern on what input fields are affected, but I found that the first one in the "Compare two values" event and all from the "Create object" action dialogs are affected. Other input fields might have this issue as well.
Side note: Using triple click to select all values in the input field works as intended.

## Attach a .c3p

This is an editor bug and it happens with a blank project as well.

## Steps to reproduce

1. Open up the "Add global variable" dialog.
2. Try selecting the default value (or any other you might have in that field) using double click on the input field (but not on the value).

## Observed result

Nothing happens.

## Expected result

The value (or the last word if it has more) should be selected using double clicking on the entire input field.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 7.7 gb
Storage usage (approx): 123 mb (1.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can't reproduce any issue with the "Add global variable" dialog, every field selects all when I double click it anywhere on the control. I did notice the expression input fields for parameters like in "Compare two values" did not always select all when double clicked, so I've fixed that in the next build.

**Comment by glerikud** [comment]
I can always reproduce this bug in the "Add global variable" dialog, but that might be an issue with my system. Thanks for fixing the other expression input fields.
