### ISSUE TITLE
C3 runtime performance has regressed since release

### ISSUE THREAD

**Issue by jgp1971** [Scirra/Construct-3-bugs#1611]
## Problem description

Performance for the C3 Runtime in specific stress tests have regressed from the initial release of r95 to the latest r101.

## Attach a .c3p

[jankySkullC2.zip](https://github.com/Scirra/Construct-3-bugs/files/2026713/jankySkullC2.zip)
https://drive.google.com/file/d/1rUkWAA0GfFols2a6LbWlmBmvbAsW6pTT/view

## Steps to reproduce

1. Import the project file into an instance of r95 construct 3.
2. Run the project with C2 runtime selected and ramp up the spawns to the desired number until it's janky.
3. Run the project with C3 runtime selected and do the same.
4. Open up an instance of construct 3 r101 and repeat steps 2 and 3.

## Observed result

As it can be seen in the provided gifs or by using the provided project file, the performance of C2 has remained the same through all releases from r95, but the performance of the C3 runtime has regressed substantially.

## Expected result

C3 runtime performance should have stayed the same in this test, or gone better.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r101 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.3 gb
Storage usage (approx): 59 mb (0.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_get_buffer_sub_data_async
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, turns out a bug fix a few weeks ago accidentally regressed the performance of destroying instances. It should be back to full performance in the next release.

**Comment by jgp1971** [comment]
@AshleyScirra As I was told in twitter, just wanted to drop by and confirm that the performance did increase in r101.2 compared to r101, which is great, but overall it's still worse than r95 in this specific test. Would you like me to create a new issue? Is that drop in performance for this specific test expected? Thanks for everything.

**Comment by AshleyScirra** [comment]
I can't reproduce any performance difference between r95 and r101.2. I have a separate performance test for create & destroy instances and it is now identical between r95 and the latest release. This is the issue that was found and fixed by this report.

TBH the test you've provided isn't that great - it's not really a performance test, since it relies on 'dt' it's more of a "v-sync accuracy under stress" test. Also since it relies on semi-randomly creating "jank" indicators rather than providing a numerical measurement, it's difficult to compare it to anything. You just have to watch it for a while and see if the randomly appearing sprites seem kind-of-as-random as another run. I did compare the test between r95 and the latest release anyway, and I couldn't see any obvious difference between them. If you think there is a difference then I'd suggest filing a new issue to investigate that separately, and coming up with a project that consistently and measurably reproduces the issue.
