### ISSUE TITLE
iPad os, layout squished

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1620]
## Problem description

*Enter a concise description of your problem here*
C3 on iPad not honoring layout size
[layoutbug.zip](https://github.com/Scirra/Construct-3-bugs/files/2031644/layoutbug.zip)

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open attached project
2. Run it on iOS iPad 
3. Preview
4. Check all 4 different view options and see results
Note: added second project with border boxes to easily see issues

## Observed result

*What do you see happen?*
Layout on iPad is completely wrong size, squished
Looks like 300 x 450 in size on iPad 12 inch display, was not a problem in R100, so test against R100 then test against r101 then test against r101-2, only displays correct on r100

## Expected result

*What did you expect to happen instead?*
Correct layout display and not squished

## Affected browsers

* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r101.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
Service Workers are not supported. Construct 3 cannot be used offline in this browser.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A10X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by zumwaltwood** [comment]
Any word on this, it's brutal to start in the editor, things shift around and when you hit play to preview your work, it is totally zoomed in and out of wack because of the zoom level, and no, it's not my browser with the problem, and yes I purged everything and reset safari just to test to see if it was me, it's not, it's a problem with 101-2, doesn't exist in prior versions.
Thanks

**Comment by AshleyScirra** [comment]
I'm very confused by this:

- Your title and description refer to iPad, but step 2 of the steps to reproduce says "Run it on any OS". Which do you mean? iPad only or any OS?
- Step 3 says "layout defunct". What does that mean? Please be specific and clear about what you see and what you expected instead.

As far as I can tell this looks like another project where you've set "scale inner", which is working correctly, and then got confused with some things being anchored but other things not being anchored.

**Comment by zumwaltwood** [comment]
iPad which is also what my info is showing in the details from the copy
paste
Literally, when not running any project, just having them open, then
editing an image as an example, the layout scrunches up, this also happens
when you add a new entity to the scene and it pops up the object selection
list, it rescaled that window and you have to try to scale it back out

Finally, when you run the project on the iPad from the run arrow, it makes
the game huge in the window, I will do a video and post on YouTube for you
to see each condition, these conditions only exist on the iPad, sorry, I
don't have either issue in Edge, but haven't tested them in chrome or
Firefox because I can't use either for rearranging events which is a bug
you closed, but that bug work around is just use edge, I was finally able
to get edge to work for that bug.

**Comment by zumwaltwood** [comment]
I‘ve just uploaded a movie to YouTube!
You can check it out here:
http://www.youtube.com/watch?v=hNaUeW5JSJ0

I just also tested in chrome and on windows with chrome it doesn't have the issue, seems only related to iOS. Keeping this response to one issue at a time, so first issue, when running on iOS, it keeps zooming in on the layout at runtime. I had 1 success of running not zoomed in on layout but subsequent runs always reverted to the zoomed in layout, see video, I am showing safari on iPad then chrome on windows.

**Comment by zumwaltwood** [comment]
Keeping it down to one issue at a time, is the game preview issue, this is
a problem in any project I create on my iPad or modify on the iPad.
When I run the preview, the scaling is screwed up, I tested in inner, outer
and box, it appears on the iPad, when inner is selected, it uses the upper
1/4 of the viewable area of the layout, as you can see from the video.
Several more issues in preview than this, but keeping it to this first
issue, if that is fixed, I think the others will resolve naturally.  This
didn't exist as an issue in prior versions of C3

**Comment by zumwaltwood** [comment]
[layoutbug.zip](https://github.com/Scirra/Construct-3-bugs/files/2050445/layoutbug.zip)

I created a quick project, very basic, open this on iPad, switch between the views, you will see the zoom issue between the different types.

**Comment by AshleyScirra** [comment]
It's even more confusing when you provide a video that shows a different project to the one you've provided! I can't compare the video to what I see because it doesn't show the same project.

I have run the provided project on an iPad and I cannot see anything wrong with it. All the scaling modes appear to be working normally and as designed. It looks identical to Chrome on Windows if you resize the preview window to a similar size as it appears on the iPad, which demonstrates it is working the same on iPad as it does on desktop (which makes sense, because it's running the same code). It seems the most likely explanation is you've become confused by what they do, especially since you've added the Anchor behavior to only some of the objects in the layout, so they don't scale the same way with everything else.

There's too much contradictory and confusing information in this issue now to really make much more sense of it. I think we need a clean break for any further issues. If you still think there is something wrong please file a new issue following all the guidelines, stick to one issue per report, and make sure all the information is relevant to only that issue and only the project provided. Please be aware though that as many as 50% of bug reports are simply misunderstandings of Construct features, and this has been the case with a number of your prior reports too. That's not to say there aren't bugs or that you shouldn't file issues, it's just a reason to follow the bug report guidelines as closely as possible, since they are specifically written to try to eliminate cases that are just misunderstandings and focus on the real bugs.

**Comment by zumwaltwood** [comment]
I provided a clean new project to show the full issue, I will start over on this bug report and just use the last project and create videos under 30 seconds per your request, it is literally impossible to preview my projects on the iPad at the moment on r101-2, are the prior version of C3 still available? If so I can reproduce the project in the R100 and show the difference.

**Comment by AshleyScirra** [comment]
Yes, you can try any version of C3 on the releases page: https://www.construct.net/make-games/releases
