### ISSUE TITLE
Layout objects placement not correct when run

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1621]
## Problem description

*Enter a concise description of your problem here*
On window when you run the game, the sprite objects in the layout are odd by a lot, the layout does not honor the position but does honor the display window scale
[layoutbug.zip](https://github.com/Scirra/Construct-3-bugs/files/2031655/layoutbug.zip)

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open project
2. Run to see sprite not positioned as they exist on the layout
3. Test by also adding new sprite to layout then run to see positioning

## Observed result

*What do you see happen?*
Sprites positions not honored at run time against design in layout

## Expected result

*What did you expect to happen instead?*
Sprites in placed position in layout 
## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r101.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 10 gb
Storage usage (approx): 46 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I assume you are resizing the window? It looks correct by default. When you resize the window it's using 'scale inner' mode and some, but not all, of the objects use the Anchor behavior to fix themselves in place in the viewport. The other objects without the Anchor behavior scale normally. It appears to be working correctly, you've just set things up somewhat confusingly for yourself.

**Comment by zumwaltwood** [comment]
No, literally, the objects shift in display at runtime, as in my menu border is correct but the buttons shift, but I will keep playing with it, I know about anchor but the menu border is not anchored neither are the buttons but that doesn't stop them from not honoring the positions.

**Comment by AshleyScirra** [comment]
Yes, that is because some objects have anchor, and others don't so move according to the "scale inner" scaling.

**Comment by zumwaltwood** [comment]
I must have overlooked that, but the menu was still outside the view port
even when i fixed the anchor, but I'm design, the menu is in the view port
including the border, different issue than this issue though, same c3p
