### ISSUE TITLE
Two case that work in c2 but not in C3

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1622]
## Problem description

I had test example in c2 runtime, but when testing it in C3 runtime it does not work. 
First, on start of layout event blocks C3 from starting- switching it with Trigger once fixed it. Bug appears to happen only with this example, not with clean project.
Second, local variables that work in c2, does not work in c3 and need to be make global.

## Attach a .c3p

[test051.zip](https://github.com/Scirra/Construct-3-bugs/files/2031866/test051.zip)

## Steps to reproduce

1. Start project test in C3, c2 runtime, and rotate project with A or D, everything works.
2. switch to c3 runtime and see that project does not start
3. Disable at start of layout and enable trigger once - project  starts.
4. Press A or D inside project but sprites does not update variable.
5. Move Variables b33 and b44 to global fixed it.

## Observed result

Events that work in C2 does not work in C3. Was like this even before latest update.

## Expected result

Project should work in c2 and c3

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
The project starts up for me, and the first issue sounds like issue #1619 (issue with destroy actions) which is already fixed, so I suspect it was that.

The second issue with variables looks like a different bug, but it's very hard to debug complex projects. Can you reduce it to a minimal repro?

**Comment by AshleyScirra** [comment]
I think this is a minimal repro: [varsbug.zip](https://github.com/Scirra/Construct-3-bugs/files/2032294/varsbug.zip)
Looks like local variables reset to 0 in a function call in the C3 runtime

**Comment by AshleyScirra** [comment]
OK, fixed it based on that and the original project works again, so should be fixed in next release.
