### ISSUE TITLE
Major pin issue, can't "unpin" and pin is grabbing other things

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1624]
## Problem description

*Enter a concise description of your problem here*
So basically i removed PIN from my idPlayer and low and behold, pin is now activated on my entire cyborg family group, i would attach that project but i have so much in it now that knowing what happened with PIN is unknown and I don't want to post the entire project here and i can't water it down to figure out where it went wrong, so if you at Scirra have a private way for me to get you my project, let me know, this is too public.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
see attached youtube video, let me know how i can get you my project safe and secure, not this public git

https://youtu.be/ymP3WStQdVg

## Steps to reproduce

1. Add several sprites to scene, give them a family and some events, like spawning over time, path finding
2. Add a player object, then add a name text object, pin that to your player
3. Run the game
4. now go back in and edit the layout, remove pin from the name text object
5. run the game, your family will have inherited the pin most likely

## Observed result

*What do you see happen?*
Cyborgs family unit now has PIN where as before it did not, and it is PIN'ned to the player
## Expected result

*What did you expect to happen instead?*
Unpin and no new pin of anything that i don't want pinned
## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r101.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 105 mb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by zumwaltwood** [comment]
Preparing a video now and posting to youtube

**Comment by AshleyScirra** [comment]
Closing, please see the bug report guidelines around preparing a minimal project. Otherwise reports like these are very likely simply mistakes in events or misunderstandings.

**Comment by zumwaltwood** [comment]
I asked you where i can send a private link to the project, please reopen
and give me a way to send private the project

**Comment by zumwaltwood** [comment]
I will work on a minimum project today, guess I will have to copy and paste the entire bug description again when I'm done

**Comment by zumwaltwood** [comment]
I had to delete the cyborgs family group when I watered down the project because I had removed all cyborgs but 1 and the project would not run, the I created another cyborgs group, added the 1 remaining cyborg, rebooked all events to that family, then the problem went away.  Since this is a closed issue and the fix was to delete the family affected by the ghost pin, I'll just check it up to random problem, not worth dealing with it since it related to removing pin and it ghosted to my cyborgs group, if the continues, I will create a new bug report. Thanks Ashley
