### ISSUE TITLE
Drag mouse selection in layout editor does not work

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#1625]
## Problem description

When you're making levels and have "Parallax in editor" selected in the layer setting, as you try to drag select multiple sprites it becomes impossible, it does not account for the offset.

## Attach a .c3p

[editorparrallax.zip](https://github.com/Scirra/Construct-3-bugs/files/2033947/editorparrallax.zip)

## Steps to reproduce

1. Skip this step if using the c3p: have a layer with 50% parallax and with multiple sprites in it
2. Hold down the left mouse button to create a rectangle selection box, attempt to cover all 4 of the sprites so that they selected

## Observed result

The sprites are not selected

## Expected result

The sprites should be selected.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
