### ISSUE TITLE
Undo folder makes it inaccessible

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1626]
## Problem description

Deleting folders and then undo changes cause folders to bug out and not show assets in it. Which needs project restart to fix it.

## Attach a .c3p

[FolderBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2035991/FolderBug.zip)

## Steps to reproduce

1. Create 4 sprites then 4 folders
2. Add one sprite to each folder
3. Delete all folders
4. Undo changes
5.After first undo, you can already see sprite and folder, but folder is inaccessible. Only second undo fix first folder. But last folder stays bugged.

## Observed result

Undo deleted folders cause folder to become inaccessible.

## Expected result

After undo, folder should be accessible and show sprites.

## Affected browsers

* Chrome: yes

**Comment by SnipG** [comment]
In 103 beta, very similar bug to this"folder delete and undo", if you follow exact folder delete order, C3 will crash.
How to replicate.
1.Open clean project - 103 release.
2.Add 3 sub folders to object types.
3.Create 3 sprites
4. Add one sprite to each folder
5.Open folder 3 and folder 2, but close folder 1.
6. Start deleting them from folder 3, then delete 2 and then delete 1.
7. Now try to undo this.
8. C3 will crash every time when you replicate this.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next release.
