### ISSUE TITLE
Can not change action order

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1627]
## Problem description

*Enter a concise description of your problem here*
In R-100 I could reorder event actions on the event sheet, now in r101-2 I am unable to drag actions on events to alter order of execution

## Attach a .c3p
Not specific to c3p project, I've tested on several projects and can fully reproduce, additionally I have tried this in Edge on windows 10, Firefox on windows 10, chrome on windows 10, safari on iPad, same results, can't change the actions by dragging to new order, drag unavailable.

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Add event
2. Add actions to the event
3. Try to drag them to reorganize the

## Observed result

*What do you see happen?*
Nothing the actions can't be moved

## Expected result

*What did you expect to happen instead?*
A bold bar show up that allows the action to be moved in the actions list
## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes
[musicbug.zip](https://github.com/Scirra/Construct-3-bugs/files/2036321/musicbug.zip)

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r101.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
Service Workers are not supported. Construct 3 cannot be used offline in this browser.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A10X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by zumwaltwood** [comment]
[serverinfo.txt](https://github.com/Scirra/Construct-3-bugs/files/2036369/serverinfo.txt)

Added server info for additional platform

**Comment by AshleyScirra** [comment]
The project provided only has one action so it cannot be dragged anywhere.

This is another limitation of the mobile app BTW - since it's hard to tell apart scrolling from dragging, then drag-and-drop of events is not yet supported on mobile. This is currently by design.

**Comment by zumwaltwood** [comment]
The project I supplied has an event with 2 actions, the last event on the event sheet, but either way, I did it in server 2012 R2 and windows 10, using chrome, Firefox and edge, all same results, can't drag actions to any other order than what they are. So until this is fixed I have to delete the entire list of actions if something is triggered wrong due to my mistake of adding the actions on the event in the wrong order vs what I need.
