### ISSUE TITLE
Search manual uses google web search instead

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1628]
## Problem description

*Enter a concise description of your problem here*
Trying to search the manual online in the forums and it searches the web instead of the manual, returns web search results which is totally irrelevant to what I am searching for, for instance, I searched for network and it gave me dating sites, networking social sites, etc.
## Attach a .c3p
Irreverent 
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Go to scirra website
2. Select construct 3
3. Select manual
4. Enter search criteria
5. Perform search

## Observed result

*What do you see happen?*
Web search results

## Expected result

*What did you expect to happen instead?*
Manual search results

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

Irrelevant 

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
On step 2 it redirects me to construct.net, from where I can go to the new manual via the "learn" tab. The search on construct.net seems to work correctly. 

If I skip step 2 and stay on the scirra.com site then use the search on the manual it's using Google's custom search component. It may look like a Google web search but you will see all the results are of the scirra site.

We are intending to retire the scirra.com website in the future once construct.net has matured further, so we're obviously reluctant to be making changes to scirra.com at this point. You can see a blog post [here](https://www.construct.net/gb/blogs/construct-official-blog-1/constructs-new-website-876) about our plans for the website. That blog post is around a year old, so some things might have changed.

If your looking for manuals or tutorials on Construct 3 I would recommend using construct.net as all the updated manual entries have been published on there. Most of the official tutorials have been rewritten for C3, and there's an increasing number of new ones for features that are only in C3. You may, however, find some tutorials on scirra.com that haven't been rewritten.

**Comment by shortercode** [comment]
I can't see video, it just says it's unavailable. I'm presuming your report
is about scirra.com as that is what it seems to match.

The construct 2 manual uses the custom Google search, from what I can see
it lists 4 adverts then results from the scirra site. It's not pretty but
it works. No feature changes will be implemented on the Scirra site in the
foreseeable future.

**Comment by zumwaltwood** [comment]
Try again to view it, it was marked private and I just marked it as published

**Comment by AshleyScirra** [comment]
The video shows the website working as intended. As @shortercode described we are using a custom Google search there.
