### ISSUE TITLE
Crash On Load ... C3 Killer

### ISSUE THREAD

**Issue by TGeneDavis** [Scirra/Construct-3-bugs#163]
## Problem description

Custom plugin results in permanent crash of C3. Reloading results in C3 crashing before starting.

## Attach a .c3p

Empty unsaved new project. No .c3p needed or ever created. C3 crashes before loading preventing creation of C3 .c3p file.

[maze-generator-101.zip](https://github.com/Scirra/Construct-3-bugs/files/982129/maze-generator-101.zip)

Rename the attached zip to extension ".c3addon".

## Steps to reproduce

1. Create a new empty C3 project.
2. Load the attached c3addon
3. Never start C3 again ; - )

## Observed result

C3 becomes unloadable and you cannot remove the bad *.c3addon

## Expected result

Crashes are not big deal, but an option to remove the offending *.c3addon is needed, or C3 becomes unusable, ... permanently.

## Affected browsers

* Chrome: yes

## System details

Newest OS X and Chrome

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: help URL must begin with http:// or https:// @ Error: help URL must begin with http:// or https:// at window.ǃb.ǃVCC (https://editor.construct.net/r24/main.js:61:404785) at window.ǃXVx.window.Plugin (https://editor.construct.net/r24/main.js:61:414764) at window.ǃXVx (https://editor.construct.net/r24/main.js:61:419884) at Function.ǃV.ǃh (https://editor.construct.net/r24/main.js:2:229036) at ae.ǃeMZ (https://editor.construct.net/r24/main.js:63:22466) at Object.le.push.ǃV.ǃDB [as ǃeNg] (https://editor.construct.net/r24/main.js:63:22920) at ne (https://editor.construct.net/r24/main.js:2:288466) at te (https://editor.construct.net/r24/main.js:2:288217)
Stack: Error: help URL must begin with http:// or https:// at window.ǃb.ǃVCC (https://editor.construct.net/r24/main.js:61:404785) at window.ǃXVx.window.Plugin (https://editor.construct.net/r24/main.js:61:414764) at window.ǃXVx (https://editor.construct.net/r24/main.js:61:419884) at Function.ǃV.ǃh (https://editor.construct.net/r24/main.js:2:229036) at ae.ǃeMZ (https://editor.construct.net/r24/main.js:63:22466) at Object.le.push.ǃV.ǃDB [as ǃeNg] (https://editor.construct.net/r24/main.js:63:22920) at ne (https://editor.construct.net/r24/main.js:2:288466) at te (https://editor.construct.net/r24/main.js:2:288217)
Construct 3 version: r24
URL: https://editor.construct.net/
Date: Sun May 07 2017 19:18:32 GMT-0600 (MDT)
Uptime: 2.4 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by jaydonteh** [comment]
https://www.scirra.com/forum/plugin-error-can-t-open-the-editor-anymore_t190024?sid=8d47e387c46ac291f2b075e39cb16104

**Comment by TGeneDavis** [comment]
Also, the Stack states ... "Error: help URL must begin with http:// or https://". However, the help URL in en-US.json does start with https://

**Comment by TGeneDavis** [comment]
Btw, killing the web app's cache does remove the offending addon, but would also removes all other addons, if there were any. During beta when there aren't many addons around yet, that isn't a big deal, but from experience with C2, a developer will amass quite a few addons over time, and reloading them all will get burdensome very quickly.

**Comment by AshleyScirra** [comment]
Currently you have to clear the browser cache as described in that forum post. I know it's awkward right now, but the next build should have a better way to test addons.
