### ISSUE TITLE
Canvas Snapshot

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#1630]
## Problem description

When you call the Canvas Snapshot action and the Browser plug-in with the download function, this snapshot does not work.

## Attach a .c3p

n/a

## Steps to reproduce

1.Don't work action with export cordova(android) .apk
![snapshot](https://user-images.githubusercontent.com/33450672/40528632-05e7afd6-600b-11e8-9f05-4e8a4092fb8e.png)

## Observed result

When you take a picture of the canvas, the game pause 0.3-0.6 seconds, so snapshot works but the browser not download snapshot. In web its work.

## Expected result

Browser plugin download snapshot.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Please provide a project as per the guidelines.
