### ISSUE TITLE
Compare Instance variable with floor, random expression BUG(r101.2)

### ISSUE THREAD

**Issue by sergeypisarev85** [Scirra/Construct-3-bugs#1632]
## Problem description

Hello!

I have a bug with compare instance variable >= or >. When i try to make code work on a random number ex. floor(random(2,8)), Compare function selects only the first value. In my example it's 2. Always...

Update:

Also i have noticed that expressions cannot take parameter from my array files, while i don't use this array in other functions...
For example:
i have attack calculated as "mage.atk + loot.At(1,2)". While i don't change my weapon, and use this loot Array to change weapon, my attack will be just "mage.atk"... Parameter loot.At(1,2) will not be taken and return NANd...

Update2:
It seems that it happens with all expressions for me...

## Attach a .c3p

[00.zip](https://github.com/Scirra/Construct-3-bugs/files/2040721/00.zip)

## Steps to reproduce

1. Wait for the counter to hit any apropriate value  floor(random(2,8)) in Compare Expression >= or >.
2. It should set text to OK at random 2 to 8 counter...
3.

## Observed result

*What do you see happen?*
It sets text to OK always when counter reaches 2.

## Expected result
It should set text to OK at random counter 2 to 8...

## Affected browsers

* Chrome: yes
* Firefox: 
* Edge: 
* Safari: 

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r101.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 2.6 gb (38.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It appears to work identically in the C2 runtime so I don't think it's a bug with the new expression compiler in the C3 runtime.

The way the events are set up means it is very likely that the "OK" event will run after just over 2 seconds. The "counter >= floor(random(2, 8))" expression is evaluated every tick. Every time it's evaluated it generates a new random number. So as soon as the counter reaches 2, there's a 1/6 chance it's true to match 2. The next tick it re-evaluates and there is again a 1/6 chance it's true. So after just 6 ticks chances are it's matched 2 and will run. So it is likely to be true within 2.1 seconds.

You probably instead intended to store the random number once somewhere and then always compare with that number, until you reset it and generate a new random number.
