### ISSUE TITLE
Saving by downloading project ended with a crash

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1633]
## Problem description

C3 crashed while trying to download a copy of the project. I couldn't get to reproduce this and it's the first I've ever encountered but then again I barely use that function. Maybe the error gives you an idea.

## Attach a .c3p

Couldnt get to reproduce it, no point in attaching anything unfortunately.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃc.ǃnl (https://editor.construct.net/r98/main.js:2:108585) at Function.ǃc.ǃtw (https://editor.construct.net/r98/main.js:2:119664) at window.ǃBAl.ǃxH (https://editor.construct.net/r98/main.js:168:59554)
Stack: TypeError: unexpected type at Function.ǃc.ǃnl (https://editor.construct.net/r98/main.js:2:108585) at Function.ǃc.ǃtw (https://editor.construct.net/r98/main.js:2:119664) at window.ǃBAl.ǃxH (https://editor.construct.net/r98/main.js:168:59554)
Construct 3 version: r98
URL: https://editor.construct.net/
Date: Sun May 27 2018 17:36:45 GMT+0300 (GTB Daylight Time)
Uptime: 2229.5 s

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Huh that's unusual. The error doesn't give me much, but I'll see what I can find. Thanks for the report.

**Comment by shortercode** [comment]
Okay so the issue is that the project failed to save, but the error wasn't displayed. So I've fixed it so we're catching the issues now, but we're still not clearer why the project failed to be archived.
