### ISSUE TITLE
Everytime I open up C3, desktop version, it asks for update 101.2.

### ISSUE THREAD

**Issue by bthansson** [Scirra/Construct-3-bugs#1637]
## Problem description

*Enter a concise description of your problem here*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
If you are launching the stable build and you've opted in to be notified about beta releases, then this is the expected result. Since the report ignored the rest of the guidelines I cannot verify this so I'll just assume that's the case.
