### ISSUE TITLE
c2runtime.js contains use of  "let" keyword

### ISSUE THREAD

**Issue by amirblum** [Scirra/Construct-3-bugs#1640]
## Problem description

The construct runtime makes use of the `let` keyword on line 9454. This is incompatible some mobile browsers such as Safari on iOS 9 and Chrome on Android KitKat.

## Attach a .c3p

Basically an empty project:
[TestProject.zip](https://github.com/Scirra/Construct-3-bugs/files/2052475/TestProject.zip)

## Steps to reproduce

1. Export project to HTML5.
2. Upload to server.
3. Run on device running iOS 9/Android KitKat.

## Observed result

This results in the game throwing an error and displaying a black screen when trying to run the game.

The error in Safari Web Inspector:
<img width="701" alt="screen shot 2018-05-29 at 14 31 00" src="https://user-images.githubusercontent.com/5489116/40700258-857f2f88-63e1-11e8-8687-81335b0e33eb.png">

## Expected result

Display the layout defined in the project, as happens in newer browsers.

## Affected browsers

* Chrome: yes (older versions)
* Safari: yes (older versions)

**Comment by AshleyScirra** [comment]
Should be fixed in the next release.
