### ISSUE TITLE
Status Bar still visible on iOS when checked to 'not visible'

### ISSUE THREAD

**Issue by Bootfit** [Scirra/Construct-3-bugs#1642]
## Problem description

When exporting for iOS as XCode project the 'Hide status bar' box was checked. This was also checked in the General tab once imported into XCode. When the .ipa is exported from XCode
and imported onto iPhone the status bar is still visible.

## Attach a .c3p

[statusbartest.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2054945/statusbartest.c3p.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Export for iOS as XCode project and check "Hide status bar" checkbox. 
2. Import into XCode and run Archive as outlined on this page: https://www.construct.net/gb/tutorials/ios-application-development-and-publishing-with-xcode-25
3. When the .ipa is downloaded then uploaded to an iPhone the status bar is still visible.

## Observed result

Status bar is visible on iOS devices.

Depreciation comment in _CDVStatusBar.m_ file: _**'setStatusBarHidden:' is deprecated: first deprecated in iOS 9.0 - Use -[UIViewController prefersStatusBarHidden]**_

## Expected result

Status bar should not be visible on iOS devices.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 280 mb (0.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Looks like we use a deprecated way of hiding the status bar. Assigning to Iain to look in to this.

**Comment by shortercode** [comment]
The suggested methods for hiding the statusbar don't seem to work for me, Apple tend to change things a lot and I remember this historically being difficult. So to work around this I've set it to be programmatically hidden. This means it will appear for a short duration during loading but it's hidden as soon as the renderer is initialised.

This patch should be in the next release.
