### ISSUE TITLE
Low performance experienced when bad performance when sorting sprites

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#1643]
## Problem description

I'm experiencing incredibly bad performance when sorting sprites

## Attach a .c3p
 
https://puu.sh/AvVKC/82ea5898b1.c3p

## Steps to reproduce

1. Launch the project
2. One or two hundred characters will be created and move around
3. The FPS will drop significantly 

## Observed result

A lower than expected amount of characters can be created before significant performance issues rise up, in the profiler, sorting sprites takes the vast majority of CPU time

## Expected result

I expected to be able to have a larger amount of characters on screen without any significant performance issues

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r102 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 1.3 gb (8.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The "move in front/behind" Z order action is really inefficient to use repeatedly. Every instance it moves, it has to move it in the Z order list, and then shunt along the entire list to accomodate the new position. So if you move an item with 1000 instances it has to shift 1000 entries in the list; if you move all 1000 instances, then it has to shift entries 1,000,000 times (n^2 inefficiency).

Just do everything with the system "sort Z order" action. It's specifically designed to do this much more efficiently.

**Comment by eleanorawesome** [comment]
I did what you said https://puu.sh/AvWPY/a584e14167.c3p

and now I can create twice as many characters and run into a different bottleneck

![image](https://user-images.githubusercontent.com/32940085/40737392-9995c518-640e-11e8-947a-d09790cfedcf.png)

And it leaves me plenty of CPU time for events, thank you very much!
