### ISSUE TITLE
[Website] New Forum Nukes Old Formatting

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1644]
## Problem description

The new forum completely ignores the old formatting and everything looks weird as a result. This should not happen and should be resolved by an automatic conversion process which detects all the old formatting options and changes them to the new format accordingly.

## Broken Forum Post Example

https://www.construct.net/gb/forum/construct-2/construct-2-general-17/-updated-15-05-2018-the-big-nw-119428

## Observed result

New forum formatting doesn't display old formats correctly.

## Expected result

The new forum should automatically detect, replace and update old forum posts with old formatting.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

**Comment by AshleyScirra** [comment]
Tom's aware of this as mentioned in the forum thread so closing this.
