### ISSUE TITLE
Sprite with dragdrop behavior got bug

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1647]
## Problem description

When in C3 runtime, you have sprite with dragdrop. which acts differently while you have small or big window, like it collision box gets offset. And also when adding layers, but not sure about layers as pop-up windows never like to keep it size, so it could just be window size bug.

## Attach a .c3p

[DDropBuggy.zip](https://github.com/Scirra/Construct-3-bugs/files/2058484/DDropBuggy.zip)

## Steps to reproduce

1. Clean project beta 102, switch to c3 runtime
2. create big sprite and add dragdrop to it also add 4-5 layers
3. try drag and dropping sprite, it works bugged like its collision got offset, or layers its on has parrallax or something like that.
5. change window size to very big to small and try again.

## Observed result

Sprite with dragdrop got bug while there are multiple layers or  window size. Sometimes it looks like collision box get offset, sometime it just dosent work. But all works correctly while switching back to c2 runtime

## Expected result

Adding clean layers should not add some offset, parallax or something that makes things acting weird.
Or changing window size should not effect dragdrop behavior.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Looks like it's offset when the black bars of letterbox scale are showing. Should be fixed in the next release.
