### ISSUE TITLE
Adding shadowlight freeze preview

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1649]
## Problem description

Having shadowLight on 102 beta in c3 runtime freezes everything on layout. When you delete it from layout everything works fine or when you switch to c2 runtime
## Attach a .c3p

[ShadowlightFreeze.zip](https://github.com/Scirra/Construct-3-bugs/files/2058805/ShadowlightFreeze.zip)

## Steps to reproduce

1.Open clean project beta 102, c3 runtime
2.Add some sprites with bullet behavior
3.Check preview all sprites moving
4. Add shadowlight and check preview - everything frozen
5. Delete shadowlight from layout, everything works just fine

## Observed result

Shadowlight bugs layout

## Expected result

Just like in c2 runtime, nothing should happen

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.
