### ISSUE TITLE
[r24] Background sprite turns to light-blue while in object placement mode

### ISSUE THREAD

**Issue by glerikud** [Scirra/Construct-3-bugs#165]
## Problem description

When I add a sprite to the project linked below, the background sprite turns to a solid light-blue color while I'm in the object placement mode. As soon as I place the new sprite, it goes back to normal. It's not a big issue, but still looks strange. I noticed that when I tried to reproduce the error with a blank project, the background sprite I added there just flashed to that light-blue color for a second then it immediately returned to normal, not like in the project I linked. This might be a graphical driver issue, but if you can reproduce the error, then it might worth checking out.

## Attach a .c3p

Here's the project file: https://www.dropbox.com/s/79x4pspjdnm3t8c/raktari_rend.c3p?dl=0
And here's a screenshot of the issue: https://www.dropbox.com/s/ekkzaov9touhhcg/editor_screenshot.png?dl=0

## Steps to reproduce

1. Open the project linked.
2. Add a new sprite on the layout.
3. As soon as the cursor turns into placement mode you should see the problem.

## Observed result

The background sprite turns to a solid light-blue color.

## Expected result

The background sprite should be unaffected by adding a new sprite to the project.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 7.7 gb
Storage usage (approx): 125 mb (1.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Good catch, should be fixed in the next build, thanks.
