### ISSUE TITLE
Creating object on layer, which you call by name, wont work

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1650]
## Problem description

Creating objects and calling layer by name wont spawn sprites, in c2 or c3 runtime in latest 102 beta.
Works only if you call layer by order number.
It bugs out when you add layer at bottom and call that layer by name, when you creating new sprites.

## Attach a .c3p

[LayoutNameBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2058923/LayoutNameBug.zip)

## Steps to reproduce

1.Open new project 102 beta
2.Create random sprite
3.Add layer at bottom
4. Try to create sprite on that bottom layer you added by using system create object and calling that bottom layer by name.

## Observed result

No sprites spawn

## Expected result

Sprites should spawn

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
The top layer is opaque with a white background so obscures the lower layer. When you create an object with the name of the lower layer it's therefore invisible. If you make the upper layer transparent you can see it's working correctly.
