### ISSUE TITLE
First layout that loads is set to be always default

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1651]
## Problem description

having more then 1 layout and from project window set layout 3 to load first, it wont. It always loads default layout you have selected. Bugs in c2/c3 in 98 stable and 102 beta.

## Attach a .c3p

[FirstlayoutBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2059070/FirstlayoutBug.zip)

## Steps to reproduce

1.create new project
2.add some layouts 2-3
3.From startup settings, set for example layout 3 to load first, but have layout 1 selected.
4. layout 1 loads instead.

## Observed result

When certain layout is set to load first it does not load.

## Expected result

If first layout setting is set to load as default, it loads layout that i have selected, if i specify certain layout to load first, for example layout 3 it should load 3 and not layout that i have selected.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
The preview defaults to "Preview current layout". Press F4 or choose "Preview project" and it previews from the first layout.
