### ISSUE TITLE
Layout effect in c3 runtime result black screen

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1652]
## Problem description

Added hexagonalPixellate effect to layout, worked in c2 runtime but in c3 runtime preview is just black. Tried some other layout effects same result

## Attach a .c3p

[layouteffect.zip](https://github.com/Scirra/Construct-3-bugs/files/2059408/layouteffect.zip)

## Steps to reproduce

1.Open clean project add sprite
2.Click layout and add effect
3.Check effect in c2 runtime preview all works
4. Try same thing out in c3 runtime, results c3 black screen.

## Observed result

layout effects results c3 for showing black screen.

## Expected result

Should works same as c2 runtime.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
