### ISSUE TITLE
'Unsupported Swift Version' error message when opening in XCode

### ISSUE THREAD

**Issue by Bootfit** [Scirra/Construct-3-bugs#1653]
## Problem description

I updated to r102 today and exported as usual for iOS/XCode. When I tried to open in XCode I get the following error popup:
http://i65.tinypic.com/rvhwcy.jpg

I've attached a stripped back version of my app with only the plugins I've used attached. 

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. export c3p for iOS/Xcode
2. open in XCode and see if you get the error popup.
3.

## Observed result

This error popup:
http://i65.tinypic.com/rvhwcy.jpg

## Expected result

Project to open in XCode as normal.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r102 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 323 mb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by shortercode** [comment]
Mmm I saw this a couple of days ago and thought it was a fluke. I'll take a
look tomorrow and see if I can figure out why it's happening. In the mean
time you can change the swift version in the project settings to get it to
compile

**Comment by Bootfit** [comment]
OK I had a red alert octagon so I did the following:

I've changed the Swift version in 

Build Setting > Swift Compiler Language > 3.1

I then did Product > Clean 

And the octagon went away.

I then tried to Archive and got the following error:

http://i64.tinypic.com/107thcy.jpg

**Comment by Bootfit** [comment]
Sorry - thought I'd attached it.

Here it is:
[testproject.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2065001/testproject.c3p.zip)

**Comment by shortercode** [comment]
No worries, thanks for sending it. I will take a look now

**Comment by shortercode** [comment]
Okay should be fixed, turned out to be an issue with icons randomly. The icons were renamed to lowercase version, but the configuration listed them as their original case. When the server couldn't find the icon it skipped the prep stage but didn't report an error. I've patched the server to ensure the paths are lowercase, so your project should now complete it's prep stage correctly.
