### ISSUE TITLE
[Website] Privacy Setting Is Not Working Properly

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1655]
## Problem description

The privacy setting "Don't show other users if I'm online or not" is not working properly and still shows other users and guests that you're online.

## Observed result

Privacy setting to hide your online status is not working despite being selected. It displays a green "online" circle next to your account picture in forum posts and on the profile page.

## Expected result

When checked, this setting should hide the green blinking circle next to your account picture.

## Affected browsers

* Chrome: yes
* Firefox: yes

**Comment by TomGullen** [comment]
Fixed for next upload

**Comment by TheRealDannyyy** [comment]
Can confirm, thanks for the fix.
