### ISSUE TITLE
Fullscreen mode in c2 and c3 different when layout scale smaller then 1

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1656]
## Problem description

When at start of layout you set layout scale smaller then "1" -  c2 and c3 scale window different. While scale is bigger then 1, everything seems to be okey.

##Example
[Layout_scale_vs_scalemode.zip](https://github.com/Scirra/Construct-3-bugs/files/2064015/Layout_scale_vs_scalemode.zip)

## Steps to reproduce

1.Start beta 102, add red sprites around viewport, or color viewport
2. Add event - at start of layout, set layout scale - for example 0.5
3.Check all fullscreen modes in c2 and c3,  they look different.

## Observed result

When layout scale is under 1, c2 and c3 runtime would not align viewport same way.

## Expected result

C2 and C3 runtime should have no difference.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next release.
