### ISSUE TITLE
preload sounds

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#1659]
## Problem description

When preloading sounds, when the application starts, the percentage text stops and the wait becomes infinite. The result of the application freezes on the initial boot. When disable preload of sounds, the application runs but no sounds are heard in the application, only music files work.

## Attach a .c3p

I can not show the project.

## Steps to reproduce

1.add sounds, add musics
2.preload sounds on
3.export with cordova(android)

## Observed result

![o6clyevpvma](https://user-images.githubusercontent.com/33450672/40885554-0702d024-6742-11e8-8155-c3af6cb2af68.jpg)

## Expected result

Running the application, working sounds.

## Affected browsers

android

**Comment by ERAgames777** [comment]
[](url)

**Comment by AshleyScirra** [comment]
These symptoms are sometimes caused by incorrect [mime types](https://www.construct.net/make-games/manuals/construct-3/tips-and-guides/mime-types) on the server.
