### ISSUE TITLE
Issues with forum and blog

### ISSUE THREAD

**Issue by SupremeTechnopriest** [Scirra/Construct-3-bugs#1662]
## Problem description

*Enter a concise description of your problem here*

Paying by the year for Construct and I'm loosing literal days because:

- Every link on your forum is broken.  Has a bunch of tags that are not being parsed
- Most forum links from google just resolve to homepage.  I've been trying to find the download for spriter plugin for over an hour now.
- Your blog is constantly in a 500 state.  When it is up, it takes 10 seconds - 20 seconds to get content on my 300/300 internet connection.

I really really really like construct, but I have to say that this development process has been anything but smooth.  I can understand that from open source, but not when you are charging subscriptions...

Hope to see this resolved soon.  Keep up the good work!

**Comment by Wackytoaster** [comment]
Took me 10 seconds. Thanks google.
https://webcache.googleusercontent.com/search?q=cache:Jshr8jj9GNQJ:https://www.scirra.com/forum/test-spriter-c3-addon_t198037+&cd=1&hl=de&ct=clnk&gl=at

But I gotta agree that the current transition stage is not that great, I hope they can resolve it soon.

**Comment by shortercode** [comment]
Toms been working hard to try and resolve the issues, sorry for the trouble. Hopefully we'll be stable again soon!

**Comment by SupremeTechnopriest** [comment]
I ended up finding it in an old commit.  Didn't think to use google cache!  Good idea.  Still though. For a subscription based project with no official support to have its knowledge base sending 500s is not a good look.

**Comment by TomGullen** [comment]
The 500's and 404's were all on the Scirra website.  Our goal is to move everything to Construct.net.  Construct.net is hosted in a separate scalable environment where the Construct 3 editor and your access to subscriptions are all contained, and as far as I'm aware these errors you're reporting were exclusively on Scirra.com.

This issue has now been fixed.

**Comment by SupremeTechnopriest** [comment]
Thanks a bunch @TomGullen!
