### ISSUE TITLE
Object sine state to text results bug

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1664]
## Problem description

In c3 runtime, when you assign object sine state(magnitude or period) to text, preview freeze.

## Attach a .c3p

[Sine_to_text.zip](https://github.com/Scirra/Construct-3-bugs/files/2068986/Sine_to_text.zip)

## Steps to reproduce

1. open 103 beta, create sprite and add sine behavior
2. Add text 
3. Add event, on start of layout, set text to sprite.sine.magnitude or period both result freeze
4. start preview

## Observed result

sprite.sine.magnitude or period to text result freeze

## Expected result

Should work like in c2 runtime, no preview freeze.

## Affected browsers

* Chrome: yes

**Comment by SnipG** [comment]
When you try to set object sprite.sine.magnitude or period, like +1 etc - the object will disappear.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
