### ISSUE TITLE
Caught rare C3 startup bug

### ISSUE THREAD

**Issue by NoSoul8** [Scirra/Construct-3-bugs#1665]
## Problem description

If outside C3 start up page a crash occurs on returning to it.
However, i was not able to reproduce it with the same steps again.
I hope that screenshot and error details will help you find a weak spot that caused it.

## Attach a .c3p

Not required

## Steps to reproduce

1. Start Construct 3 normally (https://editor.construct.net/)
2. Switch to any other browser tab and wait 30+ seconds
3. Navigate back to C3 tab

## Observed result

![c3_startup_error](https://user-images.githubusercontent.com/34763413/40940021-82cea1a4-6857-11e8-8135-a3962b18c5c9.PNG)

## Expected result

Normal C3 start up screen

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected function @ TypeError: expected function at Function.ǃc.ǃAh (https://editor.construct.net/r98/main.js:2:107917) at Function.ǃc.ǃh (https://editor.construct.net/r98/main.js:2:138637) at a.ǃqc (https://editor.construct.net/r98/main.js:74:28653) at Object.t.push.ǃc.ǃdc [as ǃnSG] (https://editor.construct.net/r98/main.js:74:29042) at t (https://editor.construct.net/r98/main.js:2:198941) at n (https://editor.construct.net/r98/main.js:2:198727)
Stack: TypeError: expected function at Function.ǃc.ǃAh (https://editor.construct.net/r98/main.js:2:107917) at Function.ǃc.ǃh (https://editor.construct.net/r98/main.js:2:138637) at a.ǃqc (https://editor.construct.net/r98/main.js:74:28653) at Object.t.push.ǃc.ǃdc [as ǃnSG] (https://editor.construct.net/r98/main.js:74:29042) at t (https://editor.construct.net/r98/main.js:2:198941) at n (https://editor.construct.net/r98/main.js:2:198727)
Construct 3 version: r98
URL: https://editor.construct.net/
Date: Tue Jun 05 2018 00:21:37 GMT+0400 (Грузинское время (зима))
Uptime: 28 s

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Do you have any C3 addons installed?

**Comment by NoSoul8** [comment]
@shortercode I use vanilla C3 stable version.
The only outstanding usage is that i sort of often move project files from one google drive account to another - so the "recent projects" featured link can possibly go insane trying to find a file that is not in place.

**Comment by shortercode** [comment]
Okay thanks for confirming, I haven't been able to reproduce this issue. The stacktrace is a little ambiguous but it's failing to find a component ( theme / plugin / effect etc. ). This could be for a number of reasons.

If you succeed in repeating this again can you check the browser console for additional messages.

@AshleyScirra knows more about this so I will leave this in his hands.

**Comment by AshleyScirra** [comment]
The crash report appears to indicate an addon failing to load. There's not much we can do about this without knowing why. I suspect that it was preceded by a network error that caused the addon file to fail to load. If this happens again it would be useful to open the browser console (F12) and look for any other error messages there. Apart from that, not much to be done here, so closing.
