### ISSUE TITLE
Rewarded Video functions not working - Android

### ISSUE THREAD

**Issue by hansonbrody** [Scirra/Construct-3-bugs#1666]
## Problem description

The anticipated behavior of the rewarded video function does not seem to be working. I couldn't get it to work properly in my game so I created a simple c3p to test and am seeing the same behavior. The 'On video ready' trigger does not happen (test is supposed to change when it does), and the 'On Video complete' trigger does not happen (text is also supposed to change when it does, with the rewarded video value). I am exporting to Android debug APK for testing on a Samsung Galaxy S6.

## Attach a .c3p

https://drive.google.com/open?id=1ra0E4Dan_Jw-WaJjh_TZ0pqM8S9yoi8m

## Steps to reproduce

1. 'On video loaded' should change Text to 'Locked and loaded'
2. Pressing button should launch video, and upon completed Text should change to 'Rewarded video bonus = 200'

## Observed result

1. Text doesn't change
2. Rewarded video plays, but the callback function doesn't seem to be received (text doesn't change)

## Expected result

1. 'On video loaded' should change Text to 'Locked and loaded'
2. Pressing button should launch video, and upon completed Text should change to 'Rewarded video bonus = 200'

## Affected browsers

Can only test on mobile. Tried Android.

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Please can you provided your platform information and the project you used to create your APK. Do interstitial and banner work as expected?

**Comment by hansonbrody** [comment]
For the editor, I'm on a PC in the Chrome browser, and the phone is a Samsung Galaxy S6 with the latest update. I first tried editor rev101, and each of 102 and 103. See above the google drive link to the .c3p project I used to create the APK. I first tried to implement the rewarded video in my main game, which has interstitials that are all working. I created this basic file to test if it was something in my large project or if I could recreate it, and I'm getting the same behaviour in the small project so I've attached that.

**Comment by shortercode** [comment]
The link above is for the APK, not the c3p. 

R102/103 will have the new user consent system included, have you included the properties required for this? ( privacy policy, app ID, pub ID )

**Comment by hansonbrody** [comment]
I am soooo sorry!!! Here it is: https://drive.google.com/open?id=1OaAWg2Law-64bURHzxwZKA5lvD_O2NwM

I did not have the privacy policy there. I'll add that and try it and let you know.

**Comment by hansonbrody** [comment]
Nope, still not working.

**Comment by shortercode** [comment]
I'm getting a configuration error when I run your project, the consent dialog screen requires you to use a custom provider list with a maximum of 12 providers.

**Comment by hansonbrody** [comment]
Ok let me check on that.

**Comment by hansonbrody** [comment]
Alright I just made the change in admob to the custom list and selected
only Google.

**Comment by shortercode** [comment]
I think that is what I use on my testings ad, so should hopefully work?

**Comment by hansonbrody** [comment]
K keep this open for the time being and I’ll try it this afternoon and
close it or update.

**Comment by shortercode** [comment]
Sure, I won't close this yet, hopefully we will be able to resolve the problem for you.

**Comment by shortercode** [comment]
@hansonbrody any update on this?

**Comment by hansonbrody** [comment]
I haven’t been able to get it to work, but that did change what happens.
When I initiate the create video call, it triggers video failed to load,
which it wasn’t doing before. I wondered if it had something to do with the
user consent dialogue, so I tried playing around with the show user consent
dialogue action but that action didn’t seem to do anything. Planning on
revisiting it tomorrow.
