### ISSUE TITLE
Rotate acceleration would not apply with events

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1667]
## Problem description

Accelerate does not work in rotate behavior when set by event

## Attach a .c3p

[RotateAccelerate.zip](https://github.com/Scirra/Construct-3-bugs/files/2070608/RotateAccelerate.zip)

## Steps to reproduce

1.Start project, add sprite and give it rotate behavior, Set accelerate 0
2.Add event, set rotate acceleration by xxx number
3.Check preview, it wont accelerate in c3 runtime

## Observed result

Rotate behavior set accelerate with events does not work.

## Expected result

It works in c2 runtime, but does not with c3 runtime.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
