### ISSUE TITLE
Browser request fullscreen not working

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1668]
## Problem description

In c3 runtime fullscreen won't work when requesting fullscreen with "on tap object" or any other way, but it works in c2 runtime. 

## Attach a .c3p

[BrowserFullScreen.zip](https://github.com/Scirra/Construct-3-bugs/files/2070653/BrowserFullScreen.zip)

## Steps to reproduce

1.Open clean project 103 beta.
2.Add sprite, add browser and add touch.
3.Add event on tap sprite request fullscreen
4. Tap sprite, nothing happens
5. Switch C2 runtime, tap makes browser fullscreen.

## Observed result

Browser fullscreen won't work in c3 runtime with touch or mouse.

## Expected result

Browser fullscreen should work like in c2 runtime

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Should be fixed in the next release.
