### ISSUE TITLE
XCode archive - "library not found for -lPods"

### ISSUE THREAD

**Issue by Bootfit** [Scirra/Construct-3-bugs#1669]
## Problem description

When Archiving a project in XCode I get the following error on all of my projects:

```
ld: library not found for -lPods-New project
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've tried to Archive the Space Blaster example and that works fine - but when I archive with the plugins used for my own project it fails. I've attached a blank New Project example with nothing but my used plugins and this fails to archive.

[New Project.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2072257/New.Project.c3p.zip)

## Steps to reproduce

1. Open attached example c3p project
2. You may need to change the signing key to your own and export and relink to it in XCode/General etc 
2. Clean and Archive in XCode
3. Observe error

## Observed result

the following error appears:
```
ld: library not found for -lPods-New project
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Expected result

Expected project to archive correctly as it has before.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r103 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 459 mb (1.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Bootfit** [comment]
The build fails with the same error:

`ld: library not found for -lPods-New project
clang: error: linker command failed with exit code 1 (use -v to see invocation)
 `

I'm opening the . xcodeproj file.

The project name does have spaces in it - however this hasn't been a problem in the past.

Currently running /r103

**Comment by shortercode** [comment]
You should use the workspace file, some project dependencies won't work correctly if you use the project file. Let me know if that helps.

**Comment by Bootfit** [comment]
Yeah that seems to have done the trick. Thanks. Weird one that.

**Comment by shortercode** [comment]
It's a little odd yes, plugins include native modules via the cocoapods dependency manager. Anything included like this can only be accessed when the project is opened via the workspace file.
