### ISSUE TITLE
[r24] Page-brake inside an event block on printed event sheet

### ISSUE THREAD

**Issue by glerikud** [Scirra/Construct-3-bugs#167]
## Problem description

I tried printing out an event sheet (saved as PDF) and I noticed that the page break happened right inside an event block. Since the user has no control on how the events will appear on the page, I think the editor should watch out for breaking the pages correctly to make sure no block is split between 2 pages.

## Attach a .c3p

Since it's an editor bug, no c3p needed, but here's the event sheet I printed out:
https://www.dropbox.com/s/sn5q5ytfo79ijsf/Event%20sheet%201.pdf?dl=0

And this was the project I was working on while I printed the event sheet:
https://www.dropbox.com/s/79x4pspjdnm3t8c/raktari_rend.c3p?dl=0

## Steps to reproduce

1. Open the project linked.
2. Print out the event sheet.

## Observed result

Just as page 1 ends an event block is split between 2 pages.

## Expected result

Since the event block in question didn't fit the first page, the editor should have just pushed it to the next one.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 7.7 gb
Storage usage (approx): 125 mb (1.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
We do use rules to specify not to page break inside those elements, but Chrome ignores them.

I made a minimal repro and filed a Chrome bug for it: https://bugs.chromium.org/p/chromium/issues/detail?id=719908
Closing this report as this will be followed up there.
