### ISSUE TITLE
Restart layout triggers events

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1670]
## Problem description

Restart layout in C3 runtime will triggers events, which are not triggered in C2 runtime.
Example: Having ~100 object on screen which - on destory trigger sound, then  restart layout will trigger all of them. While in C2 runtime thous events would not be triggered.
I had my own project which involves a lot of object etc, and restart layout lags/freeze preview compared to C2 which does it very fast, so C3 must trigger alot of events with restart layout.

## Attach a .c3p

[RestartLayoutBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2073025/RestartLayoutBug.zip)

## Steps to reproduce

1.Open clean 103. Add sprite, add sound.
2.Add event on sprite destory trigger sound
3.Add event time = 5 restart layout
4.Check smooth sound in preview.

## Observed result

Restart layout in C3 runtime trigger events like on destory. Which are not triggered on c2 runtime

## Expected result

Could work like C2 runtime. So project does not need remake.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
