### ISSUE TITLE
Animations editor deleted image points reappear on duplicated frame

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1671]
## Problem description

Deleted image points reappear on duplicated frame, even when you close image editor, reopen and duplicate frame with deleted image points. But is fixed when you save, and reopen whole project.

## Steps to reproduce

1. clean 103 beta, add sprite
2. add image points and then delete them
3. Duplicate your frame
4. New duplicated frame will have deleted imagepoints
5. Even if you close animations editor they reappear on duplicated frame.

## Observed result

Image points that are deleted reappear on duplicated frame

## Expected result

Deleted image points should not reappear on duplicated frame.

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed.
