### ISSUE TITLE
AJAX Json loading doesn't work for iOS Xcode export

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#1672]
## Problem description

Made a simple new project where after I click a button, a json file is loaded into the text field and a sound is made after it successfully loads. 

This works perfectly in preview but doesn't work at all when I build a cordova iOS xcode project and play it on my iPad. 

I found that this happens with my main game and no jsons were loaded. This is our last MAIN obstacle in launching a game in development for 3 years, kickstarted and everything, for iOS. 

If this works, we can launch it immediately since everything else is primed and ready :p

Hope this works, thank you very much and also thank you very very much

## Attach a .c3p

Attached at bottom, the project in c3 AND the compiled version for xcode.

## Steps to reproduce

1. Open c3p 
2. Export for cordova ios
3. download and open xcode workspace
4. preview on a device or virtual device
5. clicking the button does absolutely nothing other than change the color of the button. no sound, no loading of json data.

## Observed result

No data was loaded, ajax seems unreactive

## Expected result

AJAX works like in preview

## Affected browsers

N/A

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 6.9 gb
Storage usage (approx): 3.8 gb (54.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

[jsontested.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2074906/jsontested.c3p.zip)
[jsontests.ios.project.zip](https://github.com/Scirra/Construct-3-bugs/files/2074908/jsontests.ios.project.zip)

**Comment by damjancd** [comment]
Tested it on the BETA version of C3 and the same thing happens :(

**Comment by AshleyScirra** [comment]
The problem appears to be the file datapack.json has an unusual text encoding (UCS-2 LE BOM according to Notepad++). The AJAX plugin appears to be correctly firing its "on error" trigger (which the project doesn't listen for) because iOS doesn't understand this encoding.

We're not sure how this file could have ended up with a weird encoding. Most of the time everything should be dealt with in UTF-8. Did you modify this file externally and reimport it by any chance?

**Comment by AshleyScirra** [comment]
Looks like if you edit the file and re-export then C3 re-encodes it as UTF-8 so it should work again.

**Comment by damjancd** [comment]
It works like that! YESSSSSS my skin is melting in a positive way! thank youyuoyuyuou

**Comment by shortercode** [comment]
Haha glad its working!
