### ISSUE TITLE
 This is probably not a mistake, but a remark.

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#1673]
There is a plugin GooglePlayServices in it all functions work and it's great! But I recently played one game and saw a cloudy save on the same googleplay service! I would like to know from you, will you expand the functions of the Google PlayServices plugin such as cloud saving and tournaments between players in real time?

**Comment by AshleyScirra** [comment]
Please do not use bug reports for questions like this. Use the forums or the feature suggestion system instead.
