### ISSUE TITLE
Website - cannot add a new card

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1674]
## Problem description

So I fill up these fields and I press set new card, nothing happens. The page seems to reload or something but nothing actually happens. No places where I can add my card info to pay for the subscription.

## Attach a .c3p

![image](https://user-images.githubusercontent.com/7268697/41030029-094fed30-6986-11e8-9485-a5b256d705f5.png)

* Chrome: yes
## System details

**Comment by shortercode** [comment]
@JeFawk I've mentioned this to Tom and he is looking into this, hopefully he will be able to resolve this for you soon.

**Comment by TomGullen** [comment]
Apologies for how long it took to fix this, it should now be working.
