### ISSUE TITLE
(C3 Runtime) Uncaught (in promise) TypeError: Cannot set property ‘_changeAnimFrameIndex’ of null

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1675]
## Problem description

Hi Ashley .......  (update) 

I do not shirk from a challenge!

Check out the minimum repro ! 

If you remove any one of these events (including the on destroyed with no action), or the timer, or the container, the error goes. 
(also if you set up the events as a simple > destroy 3d object wait 1s change AF of sprite 2 > which is the same thing,  there is no error)
(just FYI I do realize that , in the spirit of minimum repro, I now have an action on an object that should be destroyed which does not really represent the original events - i hope but it seems to capture the error)

![image](https://user-images.githubusercontent.com/21962641/41067931-41eaa3b6-69df-11e8-92db-ee09f6e73bab.png)

## Attach a .c3p

(updated)
[KLX_CAF_Error (3) - Copy.zip](https://github.com/Scirra/Construct-3-bugs/files/2078318/KLX_CAF_Error.3.-.Copy.zip)

## Steps to reproduce

1. Run the attached c3p i nC3 runtime.
2. Observe console error as above
3.

## Observed result

project not run -  halted with error

## Expected result

C3 runtime goodness.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

Running Windows 7 / and 10
and Version 66.0.3359.181 (Official Build) (64-bit)
Chrome Version 66.0.3359.117 (Official Build) (64-bit)
C3 r103b and 104

</details>

**Comment by NetOneGames** [comment]
Was just having another play over lunch.   Just FYI , Removing the container (Between the text and glow sprites) also kills the issue.

**Comment by AshleyScirra** [comment]
It's incredibly difficult to debug projects like this. Are you able to reduce it down to a minimal repro as per the guidelines at all?

**Comment by NetOneGames** [comment]
That was as lean as I could get it keeping the error even after spending a good few hours.  Dont mind the sheet of globals I just dumped variables there so nothing would break as I deleted stuff. But I'll see if I can narrow down some more Cheers.

**Comment by NetOneGames** [comment]
main body updated with new minimum repro

**Comment by AshleyScirra** [comment]
Thanks for the minimal repro, it helps a lot. I think I've figured out what's going on. It's pretty complicated and the real test is if it works with your full project, so let's check this again when the next release is out.

**Comment by AshleyScirra** [comment]
Can you check if it's working in r105?

**Comment by NetOneGames** [comment]
Awesome.    Game runs with C3 Runtime 105b now and the overlaying glows (which what the sprite 2s were) are all hitting the intended animation frames.   
I can now see that there are a few issues with layers not in the correct place /not visable and arrows keys dont seem to work but it is great to see it running.  
All the faitly complex level swapping and enemy creation, formations and movment all looking good!
Nice one.
