### ISSUE TITLE
Game recorder plugin generating "buggy" videos

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1676]
## Problem description

Every video recorded with the new Game Recorder plugin generates videos that doesn't have a "timeline" so you can't go backward or forward in the video, you can only play it.

Heres an example: https://i.imgur.com/i0nlnAQ.png

This video in the screenshot have a duration of ten seconds and it's currently on the seventh second, but the "timeline bar" is stuck on zero seconds. I already tried to open the video with Chrome, but the problem keep happening. I'm not sure if its a problem with the file format or the plugin, but something is definitely wrong.

## Attach a .c3p

[Video Recorder.zip](https://github.com/Scirra/Construct-3-bugs/files/2077013/Video.Recorder.zip)

## Steps to reproduce

1. Record a video with the Game Recorder plugin.
2. Save the video anywhere.
3. Play the video and try to use the "timeline bar".

## Observed result

It's impossible to go backward or forward with the "timeline bar".

## Expected result

Being able to go backward or forward with the "timeline bar".

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid the browser encodes the video, not our code, so there's not much we can do about this. It looks like Chrome does not add timing metadata to recorded videos and that they marked the relevant issue "WontFix": https://bugs.chromium.org/p/chromium/issues/detail?id=642012

I think it works in Firefox. Perhaps you can also work around it by post-processing the video that Chrome exports, e.g. re-saving it in a video editing tool that adds back in timing info.

**Comment by BonzerKitten7** [comment]
Understandable. Hopefully it will be fixed in the future, because i want use this feature to allow the players to record their own speed runs without any external software. Anyway, thank you, Ashley! :)
