### ISSUE TITLE
C3 shortcut did not update anymore

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#1678]
## Problem description

This report probably will only serve as a signal.
I know that this bug report is not detailed enough to get working on it, so that is why maybe you need to just pay attention if this happens more often.

I had shortcut of C3 (browser version - chrome), which I use daily. It almost always updates to the latest beta update (which is weird to me, because the day before I already updated to that same beta version, but ok. That is not the reason I am writing this report today)
But today C3 suddenly did not update anymore.
So I deleted the shortcut, went to construct.net and launched C3 there and made a new shortcut.
Now it works as before and updates to the latest version.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

I cannot reproduce it.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes
Other browsers not tested.

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Sorry, not much we can do about a report like this. In the past a few people have got confused over which URL they bookmarked/added to home screen, so it could just be that.
