### ISSUE TITLE
Rotate and Fade (C3 Runtime)

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1679]
## Problem description

Today i found two little bugs, one in the rotate behaviour and another one in the fade behaviour.

Rotate - If you create a sprite with the rotate behaviour and disable the behaviour in the editor, the behaviour wont work anymore, even if you try to enable it using events.

Fade - If you create a sprite with the fade behaviour and some glow effects (i haven't tried other effects) the behaviour wont work anymore. BTW, you need to spawn the sprite by events.

And sorry for putting two bugs in a single "issue", i know that it's not right. :/

## Attach a .c3p

[Rotate and Fade.zip](https://github.com/Scirra/Construct-3-bugs/files/2080755/Rotate.and.Fade.zip)

## Steps to reproduce

1. Create a sprite with the rotate behaviour.
2. Disable the rotate behaviour in the editor.
3. Enable the rotate behaviour using events.

1. Create sprite with the fade behaviour and some glow effects.
2. Spawn the sprite using events.

## Observed result

The sprite doesn't rotate.

The sprite stay with 100% opacity.

## Expected result

The sprite to rotate.

The sprite to gradually appear or disappear.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by eleanorawesome** [comment]
I have noticed the same issue with disabling a behavior and re-enabling it with events with scrollto

**Comment by AshleyScirra** [comment]
These are two unrelated issues, but both should be fixed for the next release. The first is that Rotate behavior's 'Set enabled' action did not always work, and the second is that opacity isn't always taken in to account when adding effects to objects. @eleanorawesome - note that neither affects scrollto so please file a separate issue if you have trouble with that.
