### ISSUE TITLE
[R25]Arrow navigation, can select events "hidden" in collapsed group.

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#168]
When using the arrow key to navigate the event sheet, you can find yourself selecting events/actions which are "hidden" because inside a collapsed group. I think C2 used to select the group itself, whereas in C3 you can navigate within the group itself.

## Attach a .c3p

https://kyatric.com/c3/bugs/ArrowNavigation.c3p

## Steps to reproduce

1. Select the action of event 16 (part of Group 2 not collapsed)
2. Press up key
3. Press Enter

## Observed result

You don't see a selected event or action, nevertheless a dialog shows up and offers to modify a variable value.
Close the dialog, expand group 1 and notice that the action of the event 13 is actually selected.

## Expected result

I think in Construct 2 groups were selected. so in that case, possibly the group 2 to be selected, or group 1.
Otherwise, possibly the group 1 to automatically expand so I can see what is the selected action/event and still can track the navigation.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

Local storage
Storage quota (approx): 12 gb
Storage usage (approx): 327 mb (2.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r26.
