### ISSUE TITLE
Bug in update system 

### ISSUE THREAD

**Issue by pooyaGames** [Scirra/Construct-3-bugs#1681]
## Problem description

after updating to 105 from 103 construct recommends to update from 105 to 104

![screenshot 2018-06-08 00 00 56](https://user-images.githubusercontent.com/426713/41121977-3d81d436-6aaf-11e8-8f52-ef76323ccb5c.png)

**Comment by AshleyScirra** [comment]
Afraid there's very little we can do without the other information required by a bug report.
