### ISSUE TITLE
Platformer/Solid subpixel collisions

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1686]
## Problem description

There appear to be some odd subpixel collisions going on with the platform behavior. Hard to really describe it in text, so it´s best to look at the c3p. Another thing is that you can set the collision polygon to really small subpixel increments like 0.01, but once you close and open the image editor again it just says 0. The subpixel increment is still there though (also shown in the c3p)

## Attach a .c3p

[subpixel.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2087670/subpixel.c3p.zip)

## Steps to reproduce

1. Set snap to grid and grid size to (e.g.) 32
2. Create a sprite with size 32x32, add platform
3. Create a tiled background for ground, add solid
4. Set up like in the picture

![b](https://user-images.githubusercontent.com/31101309/41200162-cdb7472e-6c9f-11e8-986f-6d8407ddbd14.PNG)

## Observed result

The block lands on the higher ground by a subpixel.

## Expected result

The block to land next to it.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r104 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 530 mb (3.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm not sure what you are trying to report here - the project doesn't show objects landing on the ground, but the description and screenshot sounds like they are. Still, the platform behavior works to a precision of 1/16th of a pixel by design, so very small gaps are to be expected. Also note that exactly adjacent objects count as colliding.
