### ISSUE TITLE
Crash when I tried to rearrange global vars

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1687]
## Problem description

Tried to change the order of a global (constant) variable.

## Attach a .c3p

[crash.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2088263/crash.c3p.zip)

## Steps to reproduce

pls check the attached c3p
1. change "var2" to a global constant var
2. attempt to drag&drop "var2" above "var1"

## Observed result

The crashening

## Expected result

change the order

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r104/main.js, line 63, col 376805
Message: Uncaught [object Object]
Stack: undefined
Construct 3 version: r104
URL: https://editor.construct.net/index.html
Date: Sun Jun 10 2018 23:47:33 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 7100.8 s

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r104 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
That an odd one. Only seems to happen if you start with a non-constant global variable, make it constant and then move it.

I tried a few other combos without any issue:

- start without constant then move
- start with constant then move
- start with constant, toggle on then off, then move
- start without constant, toggle off, close and reopen event sheet, then move

All of these seem to work correctly! Going to assign @AshleyScirra to look at this, as this is very much his area.

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in the next release.
