### ISSUE TITLE
Crash when creating instance variable

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1688]
## Problem description

Tried to create an instance variable. Worked fine after opening the project again. Not sure what caused it as I cannot recreate it.

## Attach a .c3p

Nop

## Steps to reproduce

1. ?

## Observed result

crash

## Expected result

!crash

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: name already in object class namespace @ Error: name already in object class namespace at n.ǃkw (https://editor.construct.net/r104/main.js:63:170733) at e.ǃkR.then.e (https://editor.construct.net/r104/main.js:155:49142)
Stack: Error: name already in object class namespace at n.ǃkw (https://editor.construct.net/r104/main.js:63:170733) at e.ǃkR.then.e (https://editor.construct.net/r104/main.js:155:49142)
Construct 3 version: r104
URL: https://editor.construct.net/index.html
Date: Mon Jun 11 2018 19:22:57 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 1563 s

Platform information
Browser: Chrome
Browser version: 66.0.3359.181
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
C3 release: r104 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
I've tried a few things, I can tell you it's related to a name collision but I'm not sure how it's happening.

The dialog which allows to create/edit an instance variable should prevent name collisions, but apparently there's still some way of causing one.

**Comment by AshleyScirra** [comment]
Looks like there's some kind of name collision but we can't fix it without steps to reproduce. Please file again if you can find a way to reproduce it.
