### ISSUE TITLE
Website cannot see threads i have replied to

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#1689]
## Problem description

Website cannot see threads i have replied to

## Steps to reproduce

1.Reply to a thread on the forums

## Observed result

I get an error 500 message
https://puu.sh/ADx6y/4d6719a49b.mp4

## Expected result

I expected to see the forum thread

## Affected browsers

* Chrome: yes

**Comment by Wackytoaster** [comment]
Happened to me too with the same thread, other threads seem to work though.
