### ISSUE TITLE
Website - Every C3 desktop version link is broken

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1690]
## Problem description

I couldn't for the life of me find a C3 desktop version download link to be working.

https://www.construct.net/forum/construct-3/general-discussion-7/construct-3-desktop-build-beta-131317 - not working

Tried some other links from google, nothing working.

**Comment by shortercode** [comment]
The links are working for me at the moment, can you confirm that you are still having this issue?

**Comment by JeFawk** [comment]
Yes, they are working now.
