### ISSUE TITLE
Desktop version - picking external software to edit image crashes

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1691]
## Problem description

Once I pressed OK it crashed

![image](https://user-images.githubusercontent.com/7268697/41297895-d8707d82-6e68-11e8-8d79-15f0215ae162.png)

## Attach a .c3p

Empty project works too

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: should not save project as download in desktop app mode
Stack: Error at Function.ǃh.ǃmxo (https://editor.construct.net/r105/main.js:2:138035) at t (https://editor.construct.net/r105/main.js:2:103993) at window.assert (https://editor.construct.net/r105/main.js:2:104400) at window.ǃjln.ǃqx (https://editor.construct.net/r105/main.js:168:65551) at window.ǃjln.ǃjgt (https://editor.construct.net/r105/main.js:168:69066) at ǃh.ǃP.ǃu.ǃjgr.ǃjgO (https://editor.construct.net/r105/main.js:168:793) at HTMLButtonElement.ǃh.ǃP.ǃu.ǃjgr.ǃh.ǃP.ǃww.constructor.ǃjga.onclick (https://editor.construct.net/r105/main.js:155:198287)
Construct 3 version: r105
URL: https://editor.construct.net/r105/
Date: Tue Jun 12 2018 17:44:20 GMT+0300 (GTB Daylight Time)
Uptime: 14173.3 s

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r105 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Looks like it's trying to save the project as a download there. Are you sure it reproduces when you click OK on that dialog? If it only happened once, it might have been a coincidentally timed autosave which somehow crashed.

**Comment by JeFawk** [comment]
Crashes when I press Ok

![image](https://user-images.githubusercontent.com/7268697/41542991-b67b4166-731e-11e8-87d0-e1eb7fcd144a.png)

**Comment by AshleyScirra** [comment]
That's a different crash message to the one in the original report, but matches the one in #1707.

**Comment by JeFawk** [comment]
True.... I guess 2 bugs with 1 click :D

**Comment by DiegoScirra** [comment]
#1707, I will open a new issue for the other bug
