### ISSUE TITLE
Project toolbar -> Popout + Add certain objects = crash

### ISSUE THREAD

**Issue by runthis** [Scirra/Construct-3-bugs#1693]
## Problem description
You can not add certain objects once the "Project" toolbar has been opened as a popup.

## Attach a .c3p
Not applicable. A UI bug causes a crash and nothing gets added to the project before the crash.

## Steps to reproduce
1. Using an untouched New Project; Right-click the "Project" toolbar header and click "Open to popup window".
2. Try to add a "Browser" object by right clicking a blank area in your layout. Other Objects seem affected as well (Multiplayer, Websockets, etc).

## Observed result
Construct 3 crashed

## Expected result
The object get added to the project

## Affected browsers
* Chrome: yes - In standalone window
* Desktop: yes - Stable
Untested in other browsers / scenarios

## System details
<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃW.ǃAI (https://editor.construct.net/r104/main.js:2:110562) at new ǃW.ǃY.ǃVF.ǃVQ (https://editor.construct.net/r104/main.js:2:505484) at Function.ǃW.ǃgN (https://editor.construct.net/r104/main.js:2:140330) at Function.ǃkk (https://editor.construct.net/r104/main.js:50:198) at d.ǃWhk.then (https://editor.construct.net/r104/main.js:74:477488)
Stack: TypeError: unexpected type at Function.ǃW.ǃAI (https://editor.construct.net/r104/main.js:2:110562) at new ǃW.ǃY.ǃVF.ǃVQ (https://editor.construct.net/r104/main.js:2:505484) at Function.ǃW.ǃgN (https://editor.construct.net/r104/main.js:2:140330) at Function.ǃkk (https://editor.construct.net/r104/main.js:50:198) at d.ǃWhk.then (https://editor.construct.net/r104/main.js:74:477488)
Construct 3 version: r104
URL: https://editor.construct.net/r104/index.html
Date: Tue Jun 12 2018 17:42:24 GMT-0500 (Central Daylight Time)
Uptime: 256.6 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.87
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
C3 release: r104 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_get_buffer_sub_data_async, WEBGL_lose_context

</details>

**Comment by runthis** [comment]
On a side-note a very simplistic work-around I am using is to dock the Project toolbar on the right, expand its width to a comfortable size and then resize Construct 3's width in general so that the Project toolbar spills on to my second monitor, giving it the "feel" of being separated without crowding my Layout window.

**Comment by shortercode** [comment]
Thanks for the report, should be resolved in the next release
