### ISSUE TITLE
C3 created keystores have short validity

### ISSUE THREAD

**Issue by shinkan-fb** [Scirra/Construct-3-bugs#1694]
## Problem description

There's an issue somewhere in Cordova options app signing part.  Can't test it properly on this PC but it looks like "Creating a keystore" option don't save all settings properly.  After filling it all (name, city, alias, validity etc)  and creating it  Google Play store gives an error:

> Upload failed
> You uploaded an APK or Android App Bundle signed with a certificate that expires too soon. You need to sign your APK or Android App Bundle with a certificate that expires farther into the future. Find out more about signing.

By default in C3 Validity is set to 10 years, but google play help suggest to set it to default minimum 25.  I've tried setting it to 10, 25, 50 and 100.  and every time Google Play gave me same error bout certificate expire too soon.

And it's all the same with different settings of the keystore, or different projects.

Like I said I can't test it properly nor sign the app manually on this pc.  but some people on Discord channel had same issue and were saying that exporting unsigned app and signing it manually works.
So I believe there must be an issue somewhere in "Creating new keystore"

## Attach a .c3p

Blank new project or any game demos or template will be fine

## Steps to reproduce

1. Export to android as signed app by creating new keystore
2. upload to google play

## Observed result

No matter how many years you enter in Validity while creating new keystore, Google Play will always give an error saying the certificate expires too soon.

## Expected result

Setting Validity to 25 - like google play help suggest, should let upload the apk to the store with no issues.

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.87
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
C3 release: r104 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 708 mb (4.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 780 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Might be that we're not passing the validity option correctly, I'll take a look.

**Comment by shortercode** [comment]
Thanks for this report, your the first to mention this to me. We don't monitor the discord channels, so we're unlikely to pick up on any background chatter.

It looks like the editor isn't reading the validity value, frustratingly this also aligned with a bug in the editor checking that the value was correct. It seems to be defaulting to the minimum value of about 6 months.

I've corrected the error, but given we've just started a beta cycle it's going to be awhile until it reaches a stable release. As such I'm going to patch the server with a higher minimum duration,  25 years seems pretty reasonable. I will update this issue when the server is updated.

I would appreciate it if you could mention this bug on the discord channel, just so that others that have hit this issue are aware.

**Comment by shortercode** [comment]
Thanks very much! I've updated the build server so that it's got a default value now. 

So until the next release all new keys will have an validity of 25 years.

**Comment by shortercode** [comment]
Okay this should be resolved within the current beta, so going to close this issue.
