### ISSUE TITLE
Touch: zooming example capx no longer working 

### ISSUE THREAD

**Issue by IJCT95** [Scirra/Construct-3-bugs#1698]
## Problem description

the example project called "touch: zooming" that construct brings is no longer functional on iphone (havent tested on android yet) 

## Attach a .c3p

Construct 3 already brings that .c3p as an example

## Steps to reproduce

1. open "touch-zooming" capx example
2. remote preview project on phone
3.try to pan or pinch to zoom
4.project goes crazy.

## Observed result

project goes crazy and gives the TOUCH ID variable a value of a huge negative number

## Expected result

normal panning and zooming

## Affected browsers

tested on safari iOS and instant games platform

## System details

testing on iPhone SE with Construct 3 R105

**Comment by IJCT95** [comment]
Ashley so is this a bug?

**Comment by AshleyScirra** [comment]
Yes, looks like a bug. I would guess something has changed in Safari that broke this.

**Comment by AshleyScirra** [comment]
Should be fixed in the next build. For some reason Safari started using negative touch IDs, and the events check for a touch ID >= 0. To fix it just change the events to say != -1 rather than >= 0.

**Comment by IJCT95** [comment]
thanks a lot ashley! i may do a tutorial on this explaining it for the new users, since pinch to zoom is a very important feature that a lot of people ask for.

**Comment by IJCT95** [comment]
thanks a lot ashley! in 106 works perfectly!
