### ISSUE TITLE
[r16] Two Newly Created Sprite Bug & Possible Crash On Exit

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#17]
## Problem description

When you create newly created Sprite Object of a new project, the next created Sprite object will "inherit" the image. It's not really inheriting it but the Sprite Editor will actively run it's previous select tools on the canvas. So if the previous tool was a fill tool, the fill tool is activated and painted the entire canvas on creation. For the crash, I can't consistently produce it. But I can assure that it happened to me twice on closing the project after fiddling with this bug.

## Steps to reproduce

1. Create a Sprite while the fill tool is selected, exit the Sprite editor.
2. Create another Sprite.

## Observed result

If the previous tool was a fill tool, the fill tool is activated and painted the entire canvas on creation.
If the previous tool was a Pen/Brush tool it is activated as though you clicked and hold on the canvas on creation. 

On creation as in on the initial open of the newly created Sprite object.

The editor crashed sometimes on exit, not sure if this is caused by this bug. But mostly the crash happened with fiddling the bug only. Crashed on me twice.

## Expected result

Tools should not activate it's action on the canvas on 2nd creation of a Sprite object.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: TypeError: Cannot read property 'ǃUp' of null
Stack: TypeError: Cannot read property 'ǃUp' of null at a.ǃj.ǃG (https://editor.construct.net/r16/plugins/sprite/plugin.js:1:4928) at ne.ǃG (https://editor.construct.net/r16/main.js:61:203806) at ne.ǃG (https://editor.construct.net/r16/main.js:61:209899) at ie.ǃG (https://editor.construct.net/r16/main.js:61:157696) at be.ǃG (https://editor.construct.net/r16/main.js:61:76375) at Pe.then.Ce (https://editor.construct.net/r16/main.js:153:27437)
Construct 3 version: r16
URL: https://editor.construct.net/index.html
Date: Fri Apr 07 2017 02:28:03 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 104.6 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
@jaydonteh this is possibly related to issue #14.

That one is fixed now. Let me know if this is still a problem in r17 when it is released.

**Comment by AshleyScirra** [comment]
r17 is out, can you verify it's fixed?

**Comment by jaydonteh** [comment]
Fixed in r17.

**Comment by AshleyScirra** [comment]
Great, thanks.
