### ISSUE TITLE
Script error, line zero

### ISSUE THREAD

**Issue by rionhunter** [Scirra/Construct-3-bugs#170]
## Problem description

95% of the time, construct 3 won't open. Sometimes it flukes in after many refreshes. Most often met with a loading error, citing:
javascript error: script error, line 0.
This has been ongoing since the launch of the beta, in google chrome on win10 64 bit
![image](https://cloud.githubusercontent.com/assets/13464477/25933409/ecdf18d4-3659-11e7-9c6c-cc0a143618bd.png)

## Steps to reproduce

1. Open the beta

## Observed result
it shows the loading screen for a while - a pig painting near a happy rock. then it will clunk across

## Affected browsers

* Chrome: yes (most updated version)
* Firefox: downloaded and installed just to check for this. Not supported in this browser, due to a lack of CSS containment or Dialogue element

* Edge: also opened just to check for this, and it's not supported there either. Edge requires CSS grid layout, css variables, css contaimnent and dialog element. Why have it listed here to check if it's not even supported?

**Comment by rionhunter** [comment]
digging deeper into other submitted reports, I see this isn't so isolated - though I couldn't find any examples of it before posting.
If the solution involves disabling certain plug-ins or changing settings in chrome, perhaps have these solutions listed when presented with this error?

**Comment by AshleyScirra** [comment]
This is most likely caused by a browser addon - can you try disabling your addons and see if that fixes it? If you then enable them one-by-one, you should be able to identify which one is causing it. There is nothing we can do unless you can specifically identify what is causing this.

**Comment by rionhunter** [comment]
Hey I started on this yesterday after the initial post - but wasn't any of the obvious ones. Looked in deeper, and have found it's '[StayFocusd](https://chrome.google.com/webstore/detail/stayfocusd/laankejkbhbdhmipfmgcngdelahlfoji)', one of the few plug-ins I wouldn't be willing to let go of.

**Comment by AshleyScirra** [comment]
Thanks, I can reproduce the problem with that extension. The extension crashes on startup because C3 has strict security restrictions which break it. I found a workaround so it should work again with that extension in r27.
