### ISSUE TITLE
XCode app build fail...

### ISSUE THREAD

**Issue by Bootfit** [Scirra/Construct-3-bugs#1700]
## Problem description

App build thats been building fine in XCode previously has suddenly stopped building. Hangs on phone with black screen.

## Attach a .c3p

[Test Project.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2108276/Test.Project.c3p.zip)

## Steps to reproduce

1. Open Test Project in Xcode and build.
2.
3.

## Observed result

- Build hangs with black screen.
- Output log displays the message:
 `Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service `
- If you remove the **_System > Set Score to 0_** from the event sheet the project builds and displays two rotated colour blocks, showing that the **_System > Set Score to 0_** is what makes the app hang on the black screen, however the Output log message (Could not signal service com.apple.WebKit.Networking etc) remains.

## Expected result

Expected app to build.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.87
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
C3 release: r105 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 77 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I can't actually open the project that you've sent me, it looks like it's trying to reference a variable that has been deleted. Have you edited the project somehow?

**Comment by Bootfit** [comment]
Yeah - I've just tried to open it and can't now myself.

It was a completely stripped back version of my project that displayed the issue when building in Xcode.

I now can't seem to replicate the issue by stripping out elements down to a couple of basic files - I can only replicate if I build my whole project and as it's my first project I don't really want to upload it on an open forum. Can you suggest anything?

**Comment by Bootfit** [comment]
I've just stripped the project back again so it exports as an Xcode project and it imports into Xcode fine - however when the c3p is saved it saves as a 0k file.

Here's the Xcode version of the stripped back project - is this enough to work with? You'll be able to view the output log.

[Test app.ios.project 2.zip](https://github.com/Scirra/Construct-3-bugs/files/2112071/Test.app.ios.project.2.zip)

**Comment by shortercode** [comment]
Well... that sounds really odd. If the project itself is in such an odd state that it can't save correctly we probably can't make any assumptions about the xcode project being right unfortunately. Let's solve one problem at a time, once we've got it saving correctly it'll make it easier to find out whats wrong with the xcode project.

When you are producing this stripped down version how are you making it? Are you adding parts to a new project from scratch or are you editing down an existing project?

**Comment by Bootfit** [comment]
OK - in regards to the project being 0k - it's now updated to 1.9mb, so it must have been an issue where the file size didn't update right away. So it does seem to save correctly, just not open when I try to.

When I strip back the project I'm editing down from the full project to just a  couple of layouts and stripped back event sheets that are just complete enough to get the original output log error.

**Comment by Bootfit** [comment]
@shortercode - I've finally got to the bottom of this.

The issue causing the app to stall was a single '@' used in an email address that was in a pre-filled text field. I don't know if that will be an issue with other text fields or if it's something specific to my app - the app itself is pretty basic in regards to actions/events etc so it may be worth testing or taking into consideration to eliminate similar future issues.

Thanks for looking into this though 👍

**Comment by shortercode** [comment]
Well I'm glad you got your project to work. If you do find a way to reproduce this issue from a fresh project then please let me know!
