### ISSUE TITLE
Request Fullscreen does not work with the new runtime

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#1702]
## Problem description

Request Fullscreen does not work with the new runtime

## Attach a .c3p

https://puu.sh/AHguO/3a5d96d431.c3p

## Steps to reproduce

1. Preview the game and try to double tap using the new c3 runtime

## Observed result

nothing happens.

this show up in the console
![image](https://user-images.githubusercontent.com/32940085/41517369-6dea58c4-7288-11e8-804a-56b821d18d1f.png)

## Expected result

fullscreen
## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
This should have been fixed in r105. I assume you are testing r104 so closing. Please always include the requested information so we can verify which version you tested.
