### ISSUE TITLE
[Desktop build R105] default save location is not as expected.

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#1704]
## Problem description

Using the desktop build, when saving the project as a single file (on local disk), the default folder opened is not the folder in which the code is saved, but the last folder used by the editor (for example, the "graphics" folder). 

## Attach a .c3p
- Not relevant as this is a global editor problem.

## Steps to reproduce

1. Create a new project and save it locally.
2. Add a sprite with an image located in another folder.
3. Save you project again, the default location opened is the image's location, not the code's.

## Observed result

When saving, the default location opened is the image's location, not the one of the code.

## Expected result

The code's folder should be the default place to save the code, as it is in C2.

## Affected browsers

Desktop build, R105

**Comment by AshleyScirra** [comment]
Added support for each kind of picker individually remembering its last used path for the next release.

**Comment by RabloGames** [comment]
After closing and reopening C3, this still doesn't work for me.
Here is how to reproduce:
- Open C3 desktop build (nw.js), open a project.
- import any image located in another place on the disk
- Close C3
- Reopen C3
- Click open local file, the suggested location is the one of the image.

**Comment by AshleyScirra** [comment]
This issue was closed 28 days ago. Please file a new issue following all the guidelines and testing with the latest beta if you still have an issue.
