### ISSUE TITLE
New animation origin position is not properly set when validating with enter key.

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#1705]
## Problem description

Image origin is not correctly set when creating a new animation for an existing sprite.

## Attach a .c3p

- not relevant

## Steps to reproduce

1. Create a new project
2. Create a sprite, click the origin button to change the origin
3. Click the X value of the origin, type 9 on the keyboard, then enter to validate
4. Right click the animation list and click Add Animation
5. Click the X value of the new animation origin, type 9 on the keyboard, then enter to validate.
6. The origin is NOT actually moved.

## Observed result

The new animation is not set to the right place. If the animation editor is closed, then reoppened, the origin has not moved. The only solution I found was to used the arrows next to the origin, then typing on the keyboard.

[EDIT June 23rd]: The same problem arises when modifying an image point with the little arrows to increase or decrease the placement by 1 pixel.

## Expected result

We should be able to change the origin with the keyboard and pressing enter to confirm.

## Affected browsers

Desktop Build (R105) + chrome (R105)

**Comment by DiegoScirra** [comment]
Fixed
