### ISSUE TITLE
Impossible to add a parameter with the keyboard when calling a function

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#1706]
## Problem description

When calling a function, pressing enter when ""Add parameter" is hovered (with the tab key) doesn't add a new parameter but closes the dialog.

## Attach a .c3p

- not relevant

## Steps to reproduce

1. Call a function
2. Hit tab until you hover "Add parameter"
3. Press enter, the dialog is closed.

## Observed result

No new parameter is created and the dialog is closed.

## Expected result

I would like to add a new parameter.
If this is a browser-related problem, it should at least work in the desktop build.

## Affected browsers

Chrome + Desktop build.

**Comment by AshleyScirra** [comment]
Press Space instead. 'Enter' is the shortcut for 'Close dialog with OK'. 'Space' is the shortcut for 'activate currently focused thing'.

**Comment by RabloGames** [comment]
Ah ok! Thanks for the info!
