### ISSUE TITLE
Editor preview of shadows treats tilemaps as solid rectangles

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1710]
## Problem description

I've never used the Shadow Caster behaviour seriously before, but today i saw some cool effect in Skytorn and i thought that i could achieve something similar with the Shadow Caster behaviour and the Light Plugin, so i decided to give it a try.

During my tests i found out that the behaviour doesn't ways render in the same way depending on which object you use it. For example, if you use it in a tilemap, the shadow will be rendered above the tilemap, but if you use it in a sprite then the shadow will be rendered below the sprite, which make much more sense.

Tilemap + Shadow Caster and sprite + Shadow Caster (editor): https://i.imgur.com/tlC1FQy.png?1
Tilemap + Shadow Caster and sprite + Shadow Caster (runtime): https://i.imgur.com/aGCtkg3.gif

Another problem that i found is that during runtime the shadows are rendered in square/rectangular shapes (probably due to optimization) and not as a single shape, which can result in some really weird and buggy looking if you lower the opacity of the shadows, which is something normal if you want them to blend with the environment.

50% opacity shadows (.jpeg): https://i.imgur.com/MfE6OGi.png
50% opacity shadows (.gif): https://i.imgur.com/9pLai6h.gif

The last problem that i found is related to the "light radius" property in the Light Plugin, if you use it the light will start to go through the walls, which doesn't make any sense.

Light Radius at 10 (.jpeg): https://i.imgur.com/vJZX63X.png
Light Radius at 10 (.gif): https://i.imgur.com/qFUZAl3.gif

That's everything i could find about the Shadow Caster behaviour and the Light plugin, i hope that you guys will be able to fix theses issues, because they're making the plugin kind of useless for a serious project, but it does have a lot of potential.

BTW, i'll leave some fields empty since everything is already well explained here.

## Attach a .c3p

[Shadow Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2112482/Shadow.Bug.zip)

## Steps to reproduce

*There is no need to explain how you made the attached project. Just explain what to do to with it to observe the issue.*

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The project preview looks the same with both the C2 and C3 runtime for me, so I can't see that there's anything specific to the C3 runtime here. The only thing that looks wrong is enabling the preview in the editor, which seems to draw a large rectangle over everything else.

The opacity and light radius issues are because the shadow is drawn individually for each shadow caster. It's really tough to fix that. We'd probably have to rewrite the entire shadow casting algorithm. You can work around the opacity issue by putting the shadow light on its own layer and changing the layer opacity instead, and the gap issue can be worked around by using invisible shadow casters to block off gaps.

**Comment by BonzerKitten7** [comment]
What? That's not the title i used to open this issue, i might have done something wrong or someone changed it. Look here: https://i.imgur.com/9NDEn1I.png sorry for the inconvenience. Anyway, i haven't checked C2 or the C2 Runtime, I'm trying to only use the new runtime to find more bugs, sorry for making you waste your time with that, it was not my intention.

I ended doing exactly what you said, i made a layer for shadows only so i could change the opacity without making then overlap each other. I guess the only thing that still doesn't make much sense is the fact that the shadows are rendered above tilemaps and below sprites as you can see in the .c3p file. Shouldn't every shadow be rendered below the object?

**Comment by BonzerKitten7** [comment]
BTW, i think i found a bug in the Pin Behaviour, i'll try to discover what is causing the problem and open a new issue for it.

**Comment by AshleyScirra** [comment]
Shadows are rendered at the Z order of the Shadow Light object, which is below the sprites but above the tilemap. If you want shadows to appear below the tilemap, move the shadow light object below the tilemap in the Z order.

**Comment by AshleyScirra** [comment]
The editor does render shadows incorrectly for tilemaps. That's why I renamed the issue.

**Comment by BonzerKitten7** [comment]
Oh, ok! For a moment i thought i was going crazy because i had no idea how i had changed the issue name hehe.

**Comment by AshleyScirra** [comment]
Think this will be a tricky fix since the editor currently doesn't have any concept of per-tile collision masks, so this will probably involve a bunch of implementation work to support that.

**Comment by AshleyScirra** [comment]
Implemented in-editor shadow casting from tilemap tiles for the next beta (finally).
