### ISSUE TITLE
Line Of Sight and Family's

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1711]
## Problem description

*Enter a concise description of your problem here*
Line of Sight does not work with family's targeting family's
[Line-of-sight example.zip](https://github.com/Scirra/Construct-3-bugs/files/2113493/Line-of-sight.example.zip)

Tested in r104 and r105
## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
attached sample project

## Steps to reproduce

*There is no need to explain how you made the attached project. Just explain what to do to with it to observe the issue.*

1. Create 2 families
2. Add 1 object to each family
3. Make 1 family have a Line of Sight Behavior
4. Add 1 object from each family to the layout
5. Add a solid object between the two families
6. Use the Line of Sight example project for opacity setup
7. Run the project, you will see that line of sight is ignored

## Observed result

*What do you see happen?*
Line of sight ignored

## Expected result

*What did you expect to happen instead?*
Line of Sight work correctly

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r105 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 95 gb
Storage usage (approx): 50 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The project appears to be working correctly. You've added 2 line of sight behaviors:
1) on Player, with a cone of view of 120 degrees
2) on Family1, with a cone of view of 360 degrees
The events check using Family1, so it uses a cone of 360 degrees (i.e. line of sight at any angle), which is different to the cone of view of 120 degrees that the basic example uses. I think you've just gotten confused by these different settings.

**Comment by zumwaltwood** [comment]
I forgot to remove it from the player in the example, it doesn't work on families nor family members in family groups, it only works on non-family members in non-family groups, same issue in both the sample project I supplied and my working game project, not critical at the moment but annoying anyway since my turrets in family units shoot through solid objects, I setup the transparent scenario in my working game project and the turrets in family unit ignore the solid object with line of sight, they are clearly blocked even on 365 but the line of sight doesn't acknowledge the solid objects.

**Comment by zumwaltwood** [comment]
My direct problem I am failing at describing= family player has LOS on the family, arc=365, range =1000 (irrelevant really) wall exists to target of family enemy, but family player still sees family enemy as clear LOS when solid wall is between enemy and player family units.

Not sure at the moment how else to describe this other than ansi graphic as follows

P=player
E=enemy
W=wall

E
WWWWWWWW
W P
WWWWW

player family unit (player is actually a family unit containing turrets, just using player for description purpose only)
enemy family unit (enemy contains 9 units in family)

At all times when enemy is in range of player, the player shoots at enemy

Observation in example is same, player family unit always sees enemy family unit.

I will keep chugging at this to try to resolve, will need resolved hopefully by deployment

**Comment by zumwaltwood** [comment]
Found the problem, 365 is not evaluated every tick, first loop it gets LOS, no additional ticks are evaluated, lowering the angle to 364 opens it up to correct evaluation, it's a problem with 365 as the angle for evaluation, I can live with the solution of using 364, that 1 extra degree is a problem with 0 base vs 1 base in the core code

**Comment by zumwaltwood** [comment]
I will submit a new bug tonight with 2 sample projects, no rush on any fix for this bug, but it is a bug and repeatable, hopefully I can show it clearly
