### ISSUE TITLE
Crash when moving group

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1712]
## Problem description

Tried to move a group (a sub-group with sub-groups to be specific). Worked fine after restart, cannot reproduce.

## Attach a .c3p

⚡️ 

## Steps to reproduce

1. Move group

## Observed result

crash

## Expected result

no crash

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: no sequence number assigned
Stack: Error at Function.ǃW.ǃYdH (https://editor.construct.net/r104/main.js:2:138063) at t (https://editor.construct.net/r104/main.js:2:104027) at window.assert (https://editor.construct.net/r104/main.js:2:104434) at e.ǃYGV (https://editor.construct.net/r104/main.js:63:292396) at ǃYKU (https://editor.construct.net/r104/main.js:63:292494) at Array.sort (native) at window.ǃYbH.ǃYKB (https://editor.construct.net/r104/components/editors/eventSheetView/eventSheetView.js:1:11878) at window.ǃYbH.ǃYmt (https://editor.construct.net/r104/components/editors/eventSheetView/eventSheetView.js:1:26328) at window.ǃYbH.ǃYoS (https://editor.construct.net/r104/components/editors/eventSheetView/eventSheetView.js:1:25676) at window.ǃYbH.ǃYo (https://editor.construct.net/r104/components/editors/eventSheetView/eventSheetView.js:1:21671)
Construct 3 version: r104
URL: https://editor.construct.net/index.html
Date: Tue Jun 19 2018 16:34:56 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 2026.9 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.87
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
C3 release: r104 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
The crash report just shows it crashing dropping a selection. I'm afraid we often can't fix issues based on the crash report alone, the steps to reproduce are essential. Please file again if you can find a way to reproduce it.
