### ISSUE TITLE
Elements that have not been translated despite being translated in Poeditor

### ISSUE THREAD

**Issue by DavidCB14** [Scirra/Construct-3-bugs#1713]
In the translations 
![translation issue](https://user-images.githubusercontent.com/11505355/41609934-2cfc253a-73ec-11e8-820b-cd92c7a59c34.png)
(Spanish) there are some elements that are not shown translated in the C3 interface even though they are translated in Poeditor

Items:
- Validity (years)
text.ui.dialogs.createKeystoreDialog.label.validity
- Show passwords
text.ui.dialogs.createKeystoreDialog.label.show-passwords
- Create (This button does not appear in the translation)

In the attachment and marked in red I show the elements that are the ones that fail

**Comment by shortercode** [comment]
Thanks for the report, those elements were added later than the others. I guess I forgot to link in the translation. I've made the changes, and added in new translation entries for the missing items.

The value for `text.ui.dialogs.createKeystoreDialog.placeholder.country` looks to be wrong in the Spanish translation, it should be a [2 letter country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). I presume you are involved in the translation process, so can you look into this please?

**Comment by DavidCB14** [comment]
2 letter country code;
Of course. It's already changed. I would have written ES (Spain) but there are more countries involved ;-) and I have left it in US, as it already was

**Comment by shortercode** [comment]
Awesome, thanks :) Yeah it's probably best to keep the locations in the placeholders as the originals, it's just an example location after all.
