### ISSUE TITLE
 Animations aren't supported in the C3 SDK

### ISSUE THREAD

**Issue by lucidspriter** [Scirra/Construct-3-bugs#1718]
Plugins converted from C2 which use animation features  (this._info.SetHasAnimations(true)) have issues when there are multiple instances.  No equivalent functions to the following code, which can be used to correct this issue for images (this._info.SetHasImage(true))

```
this.spriteX = this.texture_data[3];
this.spriteY = this.texture_data[4];
this.spriteWidth = this.texture_data[5];
this.spriteHeight = this.texture_data[6];
```

**Comment by AshleyScirra** [comment]
It sounds like there are two separate things here:

1. Animation support in the C3 SDK. This is indeed incomplete. Do you have an addon I can test so I can verify it works when the implementation is completed?

2. Rendering from spritesheet co-ordinates, as shown in the code sample. This should already be supported. If you look at the drawingPlugin SDK sample the relevant call is `imageInfo.GetTexRect()` which returns the texture co-ordinates of the rectangle to render from the texture. This is necessary to render correctly from spritesheets.

**Comment by lucidspriter** [comment]
I'm using instanceProto.drawGL

And I'm grabbing individual frames like this:
var cur_frame = this.type.animations[0].frames[0];

Is there an equivalent way to grab the correct section of the spritesheet?

It doesn't actually use animations, but it was written as a C2 plugin and converted to C3, and there's not really time for a rewrite at the moment.  At the time it was written, using animations and frames was the only way I knew to get images into a plugin in C2.

**Comment by AshleyScirra** [comment]
I've been working so much on the C3 runtime lately that I think I just assumed you meant the C3 runtime, but your code samples are actually for the C2 runtime. Actually the C2 runtime should already fully support animations. The code should be identical, but I suppose if the C2 plugin ignored spritesheets, it could get away with it so long as you only ever had one frame, since it would never be spritesheeted with anything else. C3 is more aggressive about spritesheeting images and can share images on a sheet even for different object types, so is more likely to expose this issue.

Here is the code the Sprite plugin uses to detect if a frame is spritesheeted and render it accordingly:

```js
if (cur_frame.spritesheeted)
	glw.quadTex(q.tlx, q.tly, q.trx, q.try_, q.brx, q.bry, q.blx, q.bly, cur_frame.sheetTex);
else
	glw.quad(q.tlx, q.tly, q.trx, q.try_, q.brx, q.bry, q.blx, q.bly);
```

If you use this (and it applies to both C2 and C3) it should correctly draw spritesheets in both cases.

If you only use a single image then it would be more appropriate to set the plugin to use an image instead of animations. It's not much more complicated code-wise (the drawingPlugin sample in the C3 SDK shows how to do it) and that is already fully supported in the C3 runtime. However the bigger problem is that you can't switch an existing plugin from animations to an image - that's not backwards compatible :-\ so you'd have to release a separate plugin with a new ID...

**Comment by lucidspriter** [comment]
Thank you.  I won't be able to release a second version of the plugin for now.   The plugin uses spritesheets created in Spriter, and so I have to cut them up further after C2 does its thing.  What would be the equivalent when directly drawing the frame's texture_img?

  I'm using :

`var cur_image = cur_frame.texture_img;`

and

```
ctx.drawImage(cur_image, 
									
	      atlasInfo.atlasX, 
	      atlasInfo.atlasY, 
									
	      atlasInfo.atlasW, 
	      atlasInfo.atlasH, 
									
	      drawx, 
              drawy, 
									
	      atlasInfo.atlasW * this.scaleRatio, 
	      atlasInfo.atlasH * this.scaleRatio);
```

**Comment by AshleyScirra** [comment]
I'm not sure what you mean - do you want to draw the entire spritesheet the image came from? In C3 that could contain images from other objects.

**Comment by lucidspriter** [comment]
Instead of the plugin loading several individual sprite images, it loads one large sprite image.  This one large sprite is actually a spritesheet with all the individual images on it.   For example:

![Example](https://i.imgur.com/sN3XaiY.png)


So as far as C3 is concerned, it's just a large sprite, but the scml plugin breaks down this large image into its individual pieces.   To do this I'm using drawImage instead of quadTex.   Is there a way to get the spritesheeted version of the image with cur_frame.texture_img?  This is the preferable method to avoid having to recode too much, but if that's not possible, is there an overload of quadTex I can use like drawImage so I can give it texture offsets and retrieve a subsprite?

**Comment by lucidspriter** [comment]
Please disregard my last comment.  I accidentally pasted code from the non-GL portion of the code.

The plugin has a single sprite as far as C3 is concerned, but the sprite is actually a spritesheet, like this:
![Example](https://i.imgur.com/sN3XaiY.png)

I'm currently using:
`glw.quadTex(q.tlx, q.tly, q.trx, q.try_, q.brx, q.bry, q.blx, q.bly, uv);`

where uv is a var with left, top, right, and bottom set appropriately for the subsprite within this spritesheet.

Is cur_frame.sheetTex the equivalent of my uv variable, but for the entire spritesheet?  If so, I suppose I could just add the offset values in uv and sheetTex to fix the issue.

**Comment by AshleyScirra** [comment]
> Is cur_frame.sheetTex the equivalent of my uv variable, but for the entire spritesheet?
Yes - it's the texture co-ordinates for the entire object image on the spritesheet. If you have texture co-ordinates for images within that, then the texture co-ordinates for the sub-image on the overall spritesheet will need to be coverted using `lerp(subU, sheetTex.left, sheetTex.right)` and `lerp(subV, sheetTex.top, sheetTex.bottom)`.

**Comment by lucidspriter** [comment]
Chrome debugger shows sheetTex (var sheetTex= this.type.animations[0].frames[0].sheetTex) as being the full size, even though there's more than one scml object, each with a distinct texture loaded into frame 0:

sheetTex: {left: 0, top: 0, right: 1, bottom: 1}

**Comment by AshleyScirra** [comment]
Not sure what's going on - can you provide an example project?

**Comment by lucidspriter** [comment]
Hi again, Ashley.   I didn't want to waste your time looking through a fairly large plugin, so I did some digging, and I found part of the issue.   The scml plugin uses code from the Construct 2 sprite plugin, the relevant part seems to be:

```
uv = {};
uv.left = 0;
uv.top = 0;
uv.right = 1;
uv.bottom = 1;
frameobj.sheetTex = uv;
```
				
Within this context (this is from the C2 sprite plugin):

```
typeProto.onCreate = function()
{
	if (this.is_family)
		return;
		
	var i, leni, j, lenj;
	var anim, frame, animobj, frameobj, wt, uv;
	
	this.all_frames = [];
	this.has_loaded_textures = false;
		
	// Load all animation frames
	for (i = 0, leni = this.animations.length; i < leni; i++)
	{
		anim = this.animations[i];
		animobj = {};
		animobj.name = anim[0];
		animobj.speed = anim[1];
		animobj.loop = anim[2];
		animobj.repeatcount = anim[3];
		animobj.repeatto = anim[4];
		animobj.pingpong = anim[5];
		animobj.sid = anim[6];
		animobj.frames = [];
			
		for (j = 0, lenj = anim[7].length; j < lenj; j++)
		{
			frame = anim[7][j];
			frameobj = {};
			frameobj.texture_file = frame[0];
			frameobj.texture_filesize = frame[1];
			frameobj.offx = frame[2];
			frameobj.offy = frame[3];
			frameobj.width = frame[4];
			frameobj.height = frame[5];
			frameobj.duration = frame[6];
			frameobj.hotspotX = frame[7];
			frameobj.hotspotY = frame[8];
			frameobj.image_points = frame[9];
			frameobj.poly_pts = frame[10];
			frameobj.pixelformat = frame[11];
			frameobj.spritesheeted = (frameobj.width !== 0);
			frameobj.datauri = "";		// generated on demand and cached
			frameobj.getDataUri = frame_getDataUri;
				
			uv = {};
			uv.left = 0;
			uv.top = 0;
			uv.right = 1;
			uv.bottom = 1;
			frameobj.sheetTex = uv;
				
			frameobj.webGL_texture = null;
				
			// Sprite sheets may mean multiple frames reference one image
			// Ensure image is not created in duplicate
			wt = this.runtime.findWaitingTexture(frame[0]);
				
			if (wt)
			{
				frameobj.texture_img = wt;
			}
			else
			{
				frameobj.texture_img = new Image();
				frameobj.texture_img.cr_src = frame[0];
				frameobj.texture_img.cr_filesize = frame[1];
				frameobj.texture_img.c2webGL_texture = null;
					
				// Tell runtime to wait on this texture
				this.runtime.waitForImageLoad(frameobj.texture_img, frame[0]);
			}
				
			cr.seal(frameobj);
			animobj.frames.push(frameobj);
			this.all_frames.push(frameobj);
		}
			
		cr.seal(animobj);
		this.animations[i] = animobj;		// swap array data for object
	}
};
```

**Comment by AshleyScirra** [comment]
Argh, you copy-pasted all that sprite code? 🙁 It's all written specifically for the Sprite plugin and now I've ended up having to support hacked versions of it... I think making addon source viewable has been our greatest technical mistake in C2...

Did you at least also copy-paste the part in onCreate() that actually assigns `frame.sheetTex` to a useful value?

**Comment by lucidspriter** [comment]
That was the issue.  That part of the code was irrelevant for the C2 plugin because it spritesheeted per object, and the plugin only uses a single frame.  Thanks for the help.

**Comment by AshleyScirra** [comment]
Alright - I'll also separately check that the C3 runtime properly supports animations to make sure it's ready when you come to port it.
