### ISSUE TITLE
[r26] Sprite editor - Grid display

### ISSUE THREAD

**Issue by uboel** [Scirra/Construct-3-bugs#172]
## Problem description

The grid display misses the mid vertical line when the sprite size is divisible by the grid size. It seems to be just a display problem as the edge snapping is working properly around the missing vertical grid line.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

[sprite-editor-incorrect-grid-display.zip](https://github.com/Scirra/Construct-3-bugs/files/995181/sprite-editor-incorrect-grid-display.zip)

## Steps to reproduce

1. Create a sprite. In my case I resize it to 64x64
2. I setup a grid size 8x8 (but also tested 4x4, 8x8, 16x16, 32x32)
3. Activate grid display

## Observed result

When the sprite size is divisible by the grid size. The mid vertical line is not displayed.
If you setup the grid as 5x5 with a 64x64 sprite, all the lines will appear. Below, you'll find some screenshots.

![64x64-sprite-5x5-grid](https://cloud.githubusercontent.com/assets/28643164/25985506/2197aaa0-36eb-11e7-8bd6-43589259677e.PNG)
![64x64-sprite-8x8-grid](https://cloud.githubusercontent.com/assets/28643164/25985508/219c3bd8-36eb-11e7-930c-71d935307eb6.PNG)
![64x64-sprite-4x4-grid](https://cloud.githubusercontent.com/assets/28643164/25985507/219c2cec-36eb-11e7-9aeb-65b346401869.PNG)

## Expected result

A complete grid...

## Affected browsers

* Chrome: yes
## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Can you post your platform information?

I thought this one was going to be easy, but I can't reproduce it.

I think the device pixel ratio might be the problem, I tried it out in my computer which has a pixel ratio of 1 and I tried it out in a MacBook with a pixel ratio of 2. Both work.

**Comment by DiegoScirra** [comment]
I am able to reproduce a similar issue when the zoom of the browser is different to 100%.

Are you using a different zoom level than the default one?

**Comment by DiegoScirra** [comment]
@uboel 

I think I fixed this one, but I am not completely sure.  Drawing of the grid should work properly at different browser zooms now.

Try it out in r27 again to see if it is working.

**Comment by AshleyScirra** [comment]
r27 is now out, please check again!

**Comment by uboel** [comment]
Hi,

Sorry, I was in "unplugged" mode for the week-end and did not see your request for information.

I checked sprite editor in r27 and the grid display issue doesn't seem to be there anymore, whatever the zoom level is.

Great work.

PS: r27 has a problem displaying the "JAM edition" ending date in the popup when loading and also in the "Account > View detail" box.

**Comment by AshleyScirra** [comment]
Thanks for confirming!
