### ISSUE TITLE
Construct 3 doesn't work after installing wrong plugin

### ISSUE THREAD

**Issue by Piponga** [Scirra/Construct-3-bugs#1722]
## Problem description

I converted my own plugin from c2 to c3 and installed it, but after restarting page Construct 3 shows crash screen every time, I can't do anything, can't work.

## Attach a .c3p

No files, it's c3 editor

## Steps to reproduce

1. Install plugin that has some mistakes
2. Restart page

## Observed result

Crash window every time.

## Expected result

Option to remove wrong plugin

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: must specify author @ Error: must specify author at window.ǃUt.ǃeRE (https://editor.construct.net/r104/main.js:63:492646) at new window.Plugin (https://editor.construct.net/r104/main.js:63:503623) at new window.ǃecs (https://editor.construct.net/r104/main.js:63:509439) at Function.ǃW.ǃgN (https://editor.construct.net/r104/main.js:2:140330) at o.ǃRg (https://editor.construct.net/r104/main.js:74:28522) at Object.n.push.ǃW.ǃIG [as ǃYTK] (https://editor.construct.net/r104/main.js:74:28934) at n (https://editor.construct.net/r104/main.js:2:201477) at t (https://editor.construct.net/r104/main.js:2:201262)
Stack: Error: must specify author at window.ǃUt.ǃeRE (https://editor.construct.net/r104/main.js:63:492646) at new window.Plugin (https://editor.construct.net/r104/main.js:63:503623) at new window.ǃecs (https://editor.construct.net/r104/main.js:63:509439) at Function.ǃW.ǃgN (https://editor.construct.net/r104/main.js:2:140330) at o.ǃRg (https://editor.construct.net/r104/main.js:74:28522) at Object.n.push.ǃW.ǃIG [as ǃYTK] (https://editor.construct.net/r104/main.js:74:28934) at n (https://editor.construct.net/r104/main.js:2:201477) at t (https://editor.construct.net/r104/main.js:2:201262)
Construct 3 version: r104
URL: https://editor.construct.net/
Date: Thu Jun 21 2018 18:10:37 GMT+0300 (Саудовская Аравия, стандартное время)
Uptime: 5.5 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.87
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
C3 release: r104 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Please read the SDK documentation. This is what [safe mode](https://www.construct.net/make-games/manuals/addon-sdk/guide/safe-mode) is for, and why it's more convenient to work with [Developer Mode](https://www.construct.net/make-games/manuals/addon-sdk/guide/using-developer-mode).
