### ISSUE TITLE
Addition to whitelist 'cordova-plugin-nativestorage'

### ISSUE THREAD

**Issue by Piponga** [Scirra/Construct-3-bugs#1725]
## Problem description

Could you add this plugin to your whitelist?
https://github.com/TheCocoaProject/cordova-plugin-nativestorage

**Comment by shortercode** [comment]
Do you have a specific version you would like to use or is the latest fine?

**Comment by Piponga** [comment]
Latest is okay

**Comment by shortercode** [comment]
Okay dokes, I'll update this issue when I've completed the review.

**Comment by shortercode** [comment]
Looks fine, I've added it to the cordova-plugin-nativestorage@2.3.1 to the whitelist. If you have any issues let me know.
