### ISSUE TITLE
[Construct 3 Runtime] Tilemap looks bad

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#1726]
## Problem description

I use the new construct 3 runtime for my current project. On PC, the tilemap looks perfect... but on Android, it looks ugly (see the attached screenshot).

With construct 2 runtime, it looks perfect on pc and android.

## Screenshot

[Screenshot Tilemap - PC / Android](https://massive-cube.com/files-public/screenshots/problemshots/construct3/tilemap-Bug.jpg)

## Steps to reproduce

1. Create a new project
2. Place a tilemap on it (16 x 16 px)
3. Start on PC .. and on Android

## Observed result

Ugly Tilemap..

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

Android 7 - Samsung Galaxy S7
PC - Windows 10

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise we cannot help. We can't debug screenshots.
