### ISSUE TITLE
"Aw snap" tab crash exporting with image recompression

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#173]
## Problem description

"Aw snap" crash exporting with image recompression. Forked from #169.

## Attach a .c3p

https://www.dropbox.com/s/iyuvxbhi88hyuua/TrollQuest.c3p?dl=0

## Steps to reproduce

1. Export with image recompression enabled

## Observed result

"Aw snap" tab crash, most likely due to out-of-memory. Task Manager memory use spikes just before it crashes.

## Expected result

Image recompression should succeed.

This is probably another asm.js memory management issue. Replacing it with a WebAssembly build might help.

**Comment by AshleyScirra** [comment]
Some of the Chrome bugs I mentioned here involve memory leaks with posting data to workers: https://github.com/Scirra/Construct-3-bugs/issues/359#issuecomment-308142234

This could affect image recompression as well - it sends blobs around instead of ArrayBuffer but it's possible the real cause is actually Chrome leaks and not anything to do with asm.js.

**Comment by AshleyScirra** [comment]
Yep, seems it exports fine in Canary now - task manager memory use more or less stays flat while export happens, and it exports successfully! Think we can chalk this one up to Chrome leaks which are now fixed. Closing, if any more reports come in check if they work with Chrome 61+.

**Comment by shortercode** [comment]
Sweeeeeeet I did wonder if chrome was leaking somewhere, certainly the devtools memory analysis was showing very little memory usage for this bug but task manager didn't agree!
