### ISSUE TITLE
[Desktop build] Reload from original source doesn't work

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#1733]
## Problem description

When clicking "reload from original source" using the desktop build, nothing happens

## Attach a .c3p

not relevant

## Steps to reproduce

1. Create a new project in the desktop build.
2. Create a sprite and load an image.
3. Modify the image and save it with the same name.
4. Click the "reload from original source" button to update the image.

## Observed result

The image is not modified.

## Expected result

The image should be updated.

## Affected browsers

Desktop build

**Comment by DiegoScirra** [comment]
Fixed
