### ISSUE TITLE
Errror while opening project in 107

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1734]
## Problem description

C3 crash error while opening project in 107.

## Attach a .c3p

--

## Steps to reproduce

1.Open project from local browser
2. Crash
3.

## Observed result

C3 crash "Oops something went wrong"

## Expected result

No crash like 106

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: i.toString(...).ǃeFd is not a function @ TypeError: i.toString(...).ǃeFd is not a function at Array.from.map.i (https://editor.construct.net/r107/main.js:2:137239) at Array.map () at Function.ǃi.ǃeFs (https://editor.construct.net/r107/main.js:2:137217) at Function.ǃi.ǃeFy (https://editor.construct.net/r107/main.js:2:137128)
Stack: TypeError: i.toString(...).ǃeFd is not a function at Array.from.map.i (https://editor.construct.net/r107/main.js:2:137239) at Array.map () at Function.ǃi.ǃeFs (https://editor.construct.net/r107/main.js:2:137217) at Function.ǃi.ǃeFy (https://editor.construct.net/r107/main.js:2:137128)
Construct 3 version: r107
URL: https://editor.construct.net/r107/
Date: Tue Jun 26 2018 15:16:01 GMT+0300 (Eastern European Summer Time)
Uptime: 17.5 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r107 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AnomalyHatchery** [comment]
Same here, only happens when trying to load from cloud save.

**Comment by SnipG** [comment]
Similar error:
1.Update to 107
2.Open new
3.add something
4. Save to local browser
5. Crash

>Error report information
Type: unhandled rejection
Reason: Error: i.toString(...).ǃeFd is not a function @ TypeError: i.toString(...).ǃeFd is not a function at Array.from.map.i (https://editor.construct.net/r107/main.js:2:137239) at Array.map () at Function.ǃi.ǃeFs (https://editor.construct.net/r107/main.js:2:137217) at Function.ǃi.ǃeFy (https://editor.construct.net/r107/main.js:2:137128)
Stack: TypeError: i.toString(...).ǃeFd is not a function at Array.from.map.i (https://editor.construct.net/r107/main.js:2:137239) at Array.map () at Function.ǃi.ǃeFs (https://editor.construct.net/r107/main.js:2:137217) at Function.ǃi.ǃeFy (https://editor.construct.net/r107/main.js:2:137128)
Construct 3 version: r107
URL: https://editor.construct.net/r107/
Date: Tue Jun 26 2018 15:27:21 GMT+0300 (Eastern European Summer Time)
Uptime: 51.1 s
>

**Comment by MonDieu72** [comment]
None of my projects will open in r107:

Error report information
Type: unhandled rejection
Reason: Error: i.toString(...).ǃeFd is not a function @ TypeError: i.toString(...).ǃeFd is not a function at Array.from.map.i (https://editor.construct.net/r107/main.js:2:137239) at Array.map () at Function.ǃi.ǃeFs (https://editor.construct.net/r107/main.js:2:137217) at Function.ǃi.ǃeFy (https://editor.construct.net/r107/main.js:2:137128)
Stack: TypeError: i.toString(...).ǃeFd is not a function at Array.from.map.i (https://editor.construct.net/r107/main.js:2:137239) at Array.map () at Function.ǃi.ǃeFs (https://editor.construct.net/r107/main.js:2:137217) at Function.ǃi.ǃeFy (https://editor.construct.net/r107/main.js:2:137128)
Construct 3 version: r107
URL: https://editor.construct.net/r107/
Date: Tue Jun 26 2018 14:41:18 GMT+0200 (centraleuropeisk sommartid)
Uptime: 13.3 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.87
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
C3 release: r107 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by bilgekaan** [comment]
Error report information
Type: unhandled rejection
Reason: Error: i.toString(...).ǃeFd is not a function @ TypeError: i.toString(...).ǃeFd is not a function at Array.from.map.i (https://editor.construct.net/r107/main.js:2:137239) at Array.map () at Function.ǃi.ǃeFs (https://editor.construct.net/r107/main.js:2:137217) at Function.ǃi.ǃeFy (https://editor.construct.net/r107/main.js:2:137128)
Stack: TypeError: i.toString(...).ǃeFd is not a function at Array.from.map.i (https://editor.construct.net/r107/main.js:2:137239) at Array.map () at Function.ǃi.ǃeFs (https://editor.construct.net/r107/main.js:2:137217) at Function.ǃi.ǃeFy (https://editor.construct.net/r107/main.js:2:137128)
Construct 3 version: r107
URL: https://editor.construct.net/r107/
Date: Tue Jun 26 2018 15:46:29 GMT+0300 (Turkey Standard Time)
Uptime: 10.1 s

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r107 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 755M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by cmr333** [comment]
Same here, 106 works but 107 doesn't

`Error report information
Type: unhandled rejection
Reason: Error: i.toString(...).ǃeFd is not a function @ TypeError: i.toString(...).ǃeFd is not a function at Array.from.map.i (https://editor.construct.net/r107/main.js:2:137239) at Array.map () at Function.ǃi.ǃeFs (https://editor.construct.net/r107/main.js:2:137217) at Function.ǃi.ǃeFy (https://editor.construct.net/r107/main.js:2:137128)
Stack: TypeError: i.toString(...).ǃeFd is not a function at Array.from.map.i (https://editor.construct.net/r107/main.js:2:137239) at Array.map () at Function.ǃi.ǃeFs (https://editor.construct.net/r107/main.js:2:137217) at Function.ǃi.ǃeFy (https://editor.construct.net/r107/main.js:2:137128)
Construct 3 version: r107
URL: https://editor.construct.net/r107/
Date: Tue Jun 26 2018 13:57:05 GMT+0100 (British Summer Time)
Uptime: 46.5 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.87
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
C3 release: r107 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context`

**Comment by shortercode** [comment]
Thanks for the reports guys, we're looking into it now.

**Comment by shortercode** [comment]
Yeah sorry about this, part of my changes to recent projects didn't survive the build process intact. I've made the fixes for our next release.

**Comment by AshleyScirra** [comment]
r107.2 is out now with a fix. Can those affected verify it works again in that release?

**Comment by cmr333** [comment]
yeah tried both loading and saving via cloud, they both work now. Thanks <3

**Comment by zumwaltwood** [comment]
Works for me

**Comment by shortercode** [comment]
Great news, thanks for confirming for us!
