### ISSUE TITLE
R107 won't open project - mobile

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1736]
## Problem description

Opening my cyborgs Attack project in R107 yields error.
Also, due to the click through problem you can only click the copy error information, you can't click the restart button, you have to restart the browser from the browser bar itself 

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

Working on getting you a minimal project where the issue still happens but near nothing left, please bear with me.

## Steps to reproduce

*There is no need to explain how you made the attached project. Just explain what to do to with it to observe the issue.*

1. Load R107 (make sure to totally purge safari cache
2. Sign in
3. Click menu, load project from cloud
4. Load the project

## Observed result

Crash

## Expected result

Project load

## Affected browsers
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: i.toString(16).ǃeFd is not a function. (In 'i.toString(16).ǃeFd(2,"0")', 'i.toString(16).ǃeFd' is undefined) @ https://editor.construct.net/r107/main.js:2:137243 map@[native code] ǃeFs@https://editor.construct.net/r107/main.js:2:137220 asyncFunctionResume@[native code] [native code] promiseReactionJob@[native code]
Stack: https://editor.construct.net/r107/main.js:2:137243 map@[native code] ǃeFs@https://editor.construct.net/r107/main.js:2:137220 asyncFunctionResume@[native code] [native code] promiseReactionJob@[native code]
Construct 3 version: r107
URL: https://editor.construct.net/r107/
Date: Tue Jun 26 2018 07:49:30 GMT-0500 (CDT)
Uptime: 364.2 s

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r107 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A10X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions: EXT_blend_minmax, EXT_sRGB, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_standard_derivatives, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context, WEBKIT_WEBGL_compressed_texture_pvrtc, WEBGL_depth_texture, ANGLE_instanced_arrays, WEBGL_debug_renderer_info

</details>

**Comment by shortercode** [comment]
Thanks for the report, it appears to be the same issue as #1734 so I'm going to close it as a duplicate.

**Comment by zumwaltwood** [comment]
I've stripped everything I could out of the project, I am using my iPad right now, I've already purged the cache, my game only loads in R106, this min won't even load in R107, neither will the full game, both same exact issue.

**Comment by zumwaltwood** [comment]
Thanks
