### ISSUE TITLE
Desktop version reached 12gb ram then it asked me to buy more and crashed

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1738]
## Problem description

Quite unbelivable
![image](https://user-images.githubusercontent.com/7268697/41930555-08830b04-7984-11e8-891e-d3f5bc94f066.png)

And then it started writing to disk until my C: SSD was full, after which it crashed. Didn't get to save my project either which was great.

![image](https://user-images.githubusercontent.com/7268697/41930814-d58daf00-7984-11e8-89d7-012511ddf516.png)

I'm lucky it doesn't have arms cause it would eat from my fridge too.

## Attach a .c3p

I don't know what I could attach here. It's such a tiny project

![image](https://user-images.githubusercontent.com/7268697/41931428-b718bbf8-7986-11e8-87d8-67fc7074bdb6.png)
I just previewed it like 30 times today and that's about it.

## Steps to reproduce

*There is no need to explain how you made the attached project. Just explain what to do to with it to observe the issue.*

1. i got no idea

## Affected browsers

* Desktop: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r106 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 6.5 gb
Storage usage (approx): 101 mb (1.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

The Clipboard API is not supported. Some clipboard features may be unavailable.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Well I'm not really sure where to start with this... Any issue involving long run times and memory leaks is generally pretty hard. If you could come up with some form of loose reproduction based upon what you were doing it would help a lot ( just a general trend in increasing memory usage is fine, you don't have to keep going until your scratch disk is full ).

**Comment by AshleyScirra** [comment]
There's nothing we can do about reports like this. We can look at the screenshots and stroke our chins and go humm, but without the other information required by bug reports there's little else we can do. The bug report requirements are there so we can actually do something about the report.

**Comment by JeFawk** [comment]
Okey @AshleyScirra  @shortercode  I found it seems a/the problem. I run a preview and the ram doesn't get released once I close it. It decreases a bit but not enough. I opened and closed several previews and the ram remained at 3.7gb. Now (after 2 minutes) it's at 3.693.

It's a video compressed so github will accept it.
[2018-06-28_00-16-11.zip](https://github.com/Scirra/Construct-3-bugs/files/2142993/2018-06-28_00-16-11.zip)

After ~ 4 minutes it lowered to 3.6 GB, still not near how much it was before I started everything.

**Comment by NetOneGames** [comment]
i dont use desktop but your system specs say  **you are using nwjs 28 !**

**nwjs 28 uses chrome 64 which has a memory leak issue**

**it was fixed in chrome 65**

if you use a more recent nwjs (it is on 31 now) or chrome you wont have the issue.

**Comment by AshleyScirra** [comment]
Yeah, please verify this reproduces in the latest version and file a new issue with a repro project if it does. You can make a repro full of dummy content so you don't need to share your project.
