### ISSUE TITLE
RegexReplace Bug

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1741]
## Problem description

Regexreplace works in c2 runtime but not in c3.

## Attach a .c3p

[regexreplaceBuggy.zip](https://github.com/Scirra/Construct-3-bugs/files/2139355/regexreplaceBuggy.zip)

## Steps to reproduce

1. Preview example in c2 runtime
2.Switch C3 runtime and see bug

## Observed result

shows <<expressions-table>> text, instead of some numbers.

## Expected result

Like c2 runtime.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
