### ISSUE TITLE
(C3 Runtime) Positioning and scaling issues when changing Canvas size during game.

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1745]
During running a C3 project in C3 run-time changing the canvas size gives strange and incorrect object scaling, sizing and positioning issues. 

## Attach a .c3p

[Positioning Issue.zip](https://github.com/Scirra/Construct-3-bugs/files/2143201/Positioning.Issue.zip)

## Steps to reproduce

Run the attached c3p first  in C2 Runtime to observe correct behavior
Then in C3 to observe issues

The red box has 50% parallax
The blue box has 100% parallax
The green and yellow boxes have 0% parallax
The red box also has behaviors "sine" (for horizontal movement) and "scroll to"
The project simply changes the canvas size after 2 seconds from 1080p to 800x600

## Observed result

C3 - Boxes position and possibly scale incorrectly after canvas size change

(also) 2nd run - remove sine and scroll to from red box and run again
observe strange distorted scaling issue. (appears to scale sprites along with canvas size change)

## Expected result

C2 - Yellow and green boxes remain in position after canvas size change
Other boxes move correctly according to paralax after change

2nd run without behavours on red box no scaling issues after canvas size change

## Affected browsers

* Chrome: only tested

## System details

<details><summary>View details</summary>

PASTE HERE

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r107.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 2.7 gb (17.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next release.

**Comment by NetOneGames** [comment]
Nice,  man you guys dont mess around....    Hope you getting to enjoy some of this sun!

Cheers
