### ISSUE TITLE
Button menu error

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#1746]
## Problem description

If you drag the "menu" button (the menu in the menu bar) it will crash

## Steps to reproduce

1. Enter construct3
2. Drag the Menu button

## Observed result

crash

## Expected result

nothing

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r107-2/components/misc/mainMenu/mainMenu.js, line 1, col 3196
Message: Uncaught TypeError: Cannot read property 'service' of null
Stack: TypeError: Cannot read property 'service' of null at ǃPi.ǃPM.ǃPz (https://editor.construct.net/r107-2/components/misc/mainMenu/mainMenu.js:1:3196) at HTMLDivElement.ǃPX.addEventListener (https://editor.construct.net/r107-2/components/misc/mainMenu/mainMenu.js:1:1014) at HTMLDocument. (https://editor.construct.net/r107-2/main.js:2:194153)
Construct 3 version: r107.2
URL: https://editor.construct.net/r107-2/
Date: Wed Jun 27 2018 20:30:06 GMT-0300 (hora estándar de Argentina)
Uptime: 3.4 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.87
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
C3 release: r107.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 6700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by NetOneGames** [comment]
I cannot repro

**Comment by kingpirux** [comment]
it was something wrong with the update, was fixed after erasing all history from chrome

**Comment by AshleyScirra** [comment]
Reopening until we at least look at crash report

**Comment by AshleyScirra** [comment]
Crash report looks like an issue with recent projects in cloud save, assigning to Iain to see if it can be hardened

**Comment by shortercode** [comment]
I can't see any obvious way that this could happen with the current code, it could be related to legacy format persistent data but I think it's more likely that there was a corrupted entry. It's actually quite an awkward place to be checking the data format as it varies a lot across save types, but I'll see what I can do.

**Comment by shortercode** [comment]
I've put some more checks in, hopefully they should root out any corruption issues and clear any invalid entries.

**Comment by kingpirux** [comment]
:o impressive team work! thank's for the attention
