### ISSUE TITLE
Typo? Can't enable/disable Sine behavior

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#1747]
## Problem description

I think this is a typo? With Sine Behavior, in the properties  you can "enable" the behavior. But in actions I can't see this, I only see a way to set "active" or "inactive", I'm not sure if I've heard that term elsewhere and how it differs from enable/disable. 

## Example

![image](https://user-images.githubusercontent.com/5744908/42023451-3164beac-7b03-11e8-8ec2-3ebf16c86ffa.png)

**Comment by AshleyScirra** [comment]
You're right, it's inconsistent with other behaviors which use "enabled" rather than "active". I've updated Sine to use "enabled" to be consistent with other behaviors in the next release.
