### ISSUE TITLE
(C3-Runtime) Tilemap looks ugly

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#1748]
## Problem description

The tilemap looks ugly with the **construct 3 runtime** on my android 8 smartphone (Galaxy S7). On PC, the Tilemap has no problems.

( With the old Construct 2 Runtime, it works perfectly on any device )

## Attach a .c3p

[Bug Tilemap Example](https://drive.google.com/open?id=19KmA0uBFM9Dg7G7oFrIcHcPv4VZV_7-K)

## Steps to reproduce

*There is no need to explain how you made the attached project. Just explain what to do to with it to observe the issue.*

1. Open the c3p example file
2. Click on "Remote Preview"
3. Start the example on your android device and see the ugly tilemap
(4.) Start the example on pc too for a comparsion

## Observed result

*What do you see happen?*

Android 8 (Looks ugly)
[Screenshot Android](https://drive.google.com/open?id=1IuHOdT_PLUCXjRnZqGLTxOFnKgUQtlZy)

## Expected result

*What did you expect to happen instead?*

PC (No problems)
[Screenshot PC](https://drive.google.com/open?id=1n9oi7jb13-mJNFUGiLvN1O8mbf5COfz_)

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r107.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 543 mb
Storage usage (approx): 543 mb (100%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

The Clipboard API is not supported. Some clipboard features may be unavailable.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release.
