### ISSUE TITLE
Shortcut Issues

### ISSUE THREAD

**Issue by Coyowl** [Scirra/Construct-3-bugs#175]
## Problem description

1. "D" doesn't disable events
2. "Z" Creates 2 Else blocks instead of 1

## Steps to reproduce

1. Press "D"
2. Press "Z"

#169 
# Observed result

On D, nothing happens
On Z it creates 2 Else blocks

## Expected result

On D, Disable event
On Z create 1 Else block

## Affected browsers

* Chrome: yes
* Using r26

**Comment by AshleyScirra** [comment]
Very likely duplicate of #175. 'D' would not work if it was firing twice since it would just toggle the disabled state twice.

**Comment by Coyowl** [comment]
What about the Z? It creates two Else blocks

**Comment by AshleyScirra** [comment]
That's exactly what bug #118 describes.

**Comment by Coyowl** [comment]
Sorry, I didn't understand
Thanks
