### ISSUE TITLE
Construct 3 R107.2 signed release APK error

### ISSUE THREAD

**Issue by Adhebro** [Scirra/Construct-3-bugs#1750]
## Problem description

Sir/ Mam , when I try to export  my created keystore to singed release apk it shows ERROR as…….Failed to load signer 

“signer # 1 ” : tmp/e07c528c-6279-405b-Bd5d-9f185f436d3f entry “BreakBreaker “ does not contain a key 

                Please help me to sort out from this problem….I am stucked . Thanks
## Attach a .c3p

https://github.com/Scirra/Construct-3-bugs/files/2148410/Brick.Breaker.cp3.copy.zip

1. it says "Does not contain a key"
2. help to sign release apk to publish in Google store
3.

## Observed result

Signed Apk not created...shows error

## Expected result
expected to create a signed Apk file 

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>[](url)

**Comment by Adhebro** [comment]
[Brick Breaker .c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2148403/Brick.Breaker.c3p.zip)

**Comment by Adhebro** [comment]
[Brick Breaker .cp3.zip](https://github.com/Scirra/Construct-3-bugs/files/2148407/Brick.Breaker.cp3.zip)

**Comment by Adhebro** [comment]
[Brick Breaker .cp3 copy.zip](https://github.com/Scirra/Construct-3-bugs/files/2148410/Brick.Breaker.cp3.copy.zip)

**Comment by shortercode** [comment]
How did you produce your keystore?

I tried generating a fresh keystore in C3 and signing your project with that and I had no issue.

**Comment by Adhebro** [comment]
I had created keystore as :- 
1. First and Last Name : adhe
2. Organizational unit : mobile
3. Organization : studio adhe
4. City or locality : naharlagun
5. State : arunachal
6. Country code : IN
Alias : breaker game
Validity : 25 yrs

**Comment by shortercode** [comment]
@Adhebro so that worked for you correct? If so I'd like to close this bug.
