### ISSUE TITLE
Cannot escape " in Events (Cannot change strings with " in them)

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1752]
## Problem description
(I dont know if this is intended or not so maybe this is a feature request)

Escaping a " like "\"" doesnt work.
This makes it impossible to do change strings that have " in them.

example:
mystring = replace(otherstring,"\"","'")

also:
It's not possible to copy paste a JSON of something into Events. (replacing the " with ' doesn't work - its possible through the AJAX object)

possible workaround:
allow 'single quotes' to form strings. (allowing \ would probably break some projects)
mystring = replace(otherstring,'"',"'")

## Attach a .c3p
This works (doesn't work) in a new Project

**Comment by AshleyScirra** [comment]
Two double-quote characters produces a single quote in the string, but does not terminate the string. So a string with a single double-quote character is actually four double quotes, i.e.:

" "" "

The first and last start and end the string, and the middle two create a double-quote character in the string.

We specifically want to avoid people pasting data in to expressions. Use project files instead.
