### ISSUE TITLE
bundled addon crash

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#1756]
## Problem description

I just tryed to open this project and it fail to open, as far i can see is for some bundled addon error

## Attach a .c3p

i can't reproduce it, i attach the error data.

## Observed result

I tryed to open a project with bundled addonds, but this fails for some reason. 

## Expected result

Warn me about missing plugins or addons.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: {"type":"missing-addons","ǃ_Zl":[{"type":"behavior","id":"lunarray_LiteTween","name":"Lite Tween","author":"lunarray","version":"1.7","bundled":false}]}
Construct 3 version: r107.2
URL: https://editor.construct.net/r107-2/
Date: Sat Jun 30 2018 13:57:40 GMT-0300 (hora estándar de Argentina)
Uptime: 23.3 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.87
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
C3 release: r107.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 6700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Sorry, there's nothing we can do to investigate this report. If you can reproduce it please file a new issue following all the guidelines so we can investigate.
