### ISSUE TITLE
[R107.2] Dictionary/array crashes because not catching a non existing behavior expression.

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1757]
## Problem description

If you enter a wrong kind of expression for the dictionary/array plugin (I suspect it may apply to any type of "world" plugin) as if it had a behavior, when it does not, Construct crashes.

## Attach a .c3p

Reproduce in empty project

## Steps to reproduce

1. New project
2. Add dictionary
3. Add "On start of layout"
4. Add an action "instance variable set value" (the bug happens in a text field)
5. Write the expression "dictionary.count.get"
6. Make it "dictionary.count.get("
7. Crash.

Note: same thing for array and function.

## Observed result

Crash

## Expected result

No crash, a warning message like it does for the sprite if you do so for example.

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

*## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r107-2/main.js, line 63, col 173914
Message: Uncaught Error: behaviors not supported
Stack: Error: behaviors not supported at n.ǃ_EQ (https://editor.construct.net/r107-2/main.js:63:173920) at ǃ_.ǃ_o.ǃ_W.ǃQJQ.ǃQfx (https://editor.construct.net/r107-2/main.js:155:149086) at ǃ_.ǃ_o.ǃ_W.ǃQJQ.ǃQW$ (https://editor.construct.net/r107-2/main.js:155:148443) at window.ǃQJP.ǃQJC (https://editor.construct.net/r107-2/main.js:155:124269) at window.ǃQJP.ǃQJn (https://editor.construct.net/r107-2/main.js:155:123779) at HTMLDivElement.ǃbDr.ǃ_.ǃK.ǃ_.ǃ_P.ǃ_a (https://editor.construct.net/r107-2/main.js:155:120868)
Construct 3 version: r107.2
URL: https://editor.construct.net/r107-2/
Date: Sun Jul 01 2018 04:35:29 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 1682.9 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r107.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
