### ISSUE TITLE
Adding an already existing addon should update

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#1758]
## Problem description

When adding an already existing addon, C3 says that it cannot add, and that more details can be found in the console. The console then prints that the addon already exists and hence cannot be added.
However, this is problematic for both C3 addon developers and C3 users.

When installing an addon in developer mode, it's pretty cool cause you can do a whole bunch of mods to the code and have C3 reload all of your changes very quickly. However, given I'm not developping a plugin forever, at some point I wanna replace my dev addon with a released one, including in C3 so it doesn't need to reload my addon in the future when I'll be using it. So I wanna replace it with a .c3addon file like any user. 

When installing an addon to a user, it can happen that an update gets pushed later. If I want this update I'll download the new addon, and install it again on C3.

In both these cases, to do it, you need to:
Open C3
Open the addon manager
Delete the addon
Close C3
Open C3
Open the addon manager
Add the addon
Close C3
Open C3

And now you can use the new addon. This is too much for something that could take way less steps. So instead of throwing an error, it should either replace the addon (like C2 does) or prompt the user if they're sure they wanna replace it.

## Attach a .c3p

None

## Steps to reproduce

1. Add an addon (in regular or dev mode)
2. Add it again (like if it was an update or something

## Observed result

C3 throws an error in the console

## Expected result

C3 should update the addon

## Affected browsers

C3

## System details

<details><summary>View details</summary>

None

</details>

**Comment by AshleyScirra** [comment]
Added support for updating existing addons for the next release.
