### ISSUE TITLE
Add raster size for SVG import

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#176]
When importing an SVG to the image editor, it appears to use the "natural" size, which is often very large. For example the C3 logo is 1701x1701 when imported.

It would be useful to show a prompt to allow the user to enter the size to raster at, defaulting to the natural size. The dialog probably should have the "keep aspect ratio" option like the resize image dialog has.

**Comment by AshleyScirra** [comment]
Another case is if the SVG is actually very small, e.g. an icon, and you want to raster it larger.

**Comment by DiegoScirra** [comment]
Added in r33.

**Comment by AshleyScirra** [comment]
Reopening, close when rastered with canvas

**Comment by AshleyScirra** [comment]
BTW I think the raster size should also enable proportional resize by default, I'm sure proportional size is more common than stretching

**Comment by DiegoScirra** [comment]
All done for r34.
