### ISSUE TITLE
Crash on Ctrl + Left Click on Sprite (Desktop/Browser C3Runtime)

### ISSUE THREAD

**Issue by pwrtoppl** [Scirra/Construct-3-bugs#1762]
## Attach a .c3p

Added
[singlespriteproject.c3p.txt](https://github.com/Scirra/Construct-3-bugs/files/2155424/singlespriteproject.c3p.txt)

## Steps to reproduce

This had happened with another project as well when opening it in the c3runtime desktop. So I swapped to the browser editor and encountered another issue when attempting to copy an object

1. Ctrl + Click on a Sprite

## Observed result

Error on Ctrl + Left Mouse Click on Sprite to copy.

## Expected result

Second instance of Sprite created

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r108/components/bars/propertiesBar/propertiesBar.js, line 1, col 21084
Message: Uncaught TypeError: Cannot read property 'ǃXP' of undefined
Stack: TypeError: Cannot read property 'ǃXP' of undefined at y.ǃWO.ǃyfT (https://editor.construct.net/r108/components/bars/propertiesBar/propertiesBar.js:1:21084) at y.ǃyhF (https://editor.construct.net/r108/components/bars/propertiesBar/propertiesBar.js:1:6830) at Array.ǃF$ (https://editor.construct.net/r108/components/bars/propertiesBar/propertiesBar.js:1:1003) at ǃX.Event.ǃyPR.ǃyPt (https://editor.construct.net/r108/main.js:2:199778) at window.ǃhDS.dispatchEvent (https://editor.construct.net/r108/main.js:2:197907) at window.ǃhDS.ǃRh (https://editor.construct.net/r108/main.js:168:84052) at o.ǃRC (https://editor.construct.net/r108/components/editors/layoutView/layoutView.js:1:59985) at o.ǃlj (https://editor.construct.net/r108/components/editors/layoutView/layoutView.js:1:59462) at e.ǃyV (https://editor.construct.net/r108/components/editors/layoutView/layoutView.js:1:68989) at Array.ǃyN (https://editor.construct.net/r108/components/editors/layoutView/layoutView.js:1:67542)
Construct 3 version: r108
URL: https://editor.construct.net/r108/
Date: Mon Jul 02 2018 07:26:05 GMT-0600 (Mountain Daylight Time)
Uptime: 50.7 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release. I think we'll do a hotfix for this since it looks like it will happen a lot.

**Comment by AshleyScirra** [comment]
Should be fixed in r108.2 now.
