### ISSUE TITLE
Switch to layout view - instant crash

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1763]
## Problem description

Opened some old example to test worker, crash on layout view. Both ordinary chrome and canarly

## Attach a .c3p
[C3Freeze.zip](https://github.com/Scirra/Construct-3-bugs/files/2155516/C3Freeze.zip)

## Steps to reproduce

1.Open example
2.Try to look layout
3. Crash

## Observed result

Click on layout view = crash

## Expected result

No crash

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r108/components/bars/propertiesBar/propertiesBar.js, line 1, col 21084
Message: Uncaught TypeError: Cannot read property 'ǃXP' of null
Stack: TypeError: Cannot read property 'ǃXP' of null at y.ǃWO.ǃyfT (https://editor.construct.net/r108/components/bars/propertiesBar/propertiesBar.js:1:21084) at y.ǃMQ (https://editor.construct.net/r108/components/bars/propertiesBar/propertiesBar.js:1:5021) at n.ǃXri (https://editor.construct.net/r108/main.js:63:73373) at n.ǃOS (https://editor.construct.net/r108/main.js:63:70896) at d.ǃOS (https://editor.construct.net/r108/main.js:63:267117) at window.ǃM.ǃOL (https://editor.construct.net/r108/components/editors/layoutView/layoutView.js:1:26483) at window.ǃo.ǃXi (https://editor.construct.net/r108/components/editors/layoutView/layoutView.js:1:45710) at Array.ǃX.ǃy.ǃXA.addEventListener (https://editor.construct.net/r108/components/editors/layoutView/layoutView.js:1:42665) at ǃX.Event.ǃyPR.ǃyPt (https://editor.construct.net/r108/main.js:2:199778) at r.dispatchEvent (https://editor.construct.net/r108/main.js:2:197907)
Construct 3 version: r108
URL: https://editor.construct.net/r108/
Date: Mon Jul 02 2018 17:02:40 GMT+0300 (Eastern European Summer Time)
Uptime: 23.6 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Looks like same crash as #1762
