### ISSUE TITLE
When exporting project minifying script and deduplicating images

### ISSUE THREAD

**Issue by pooyaGames** [Scirra/Construct-3-bugs#1765]
## Problem description

When i export my project, sprites and 9 patch objects appear in places that they should not 
## Attach a .c3p

unfortunately i want able to produce this problem in other in a minimal project, i know that you want  a minimal project but this is problem is causing me not be able to to publish the game.

i can send you .c3p that has problem but not publicly 

## Steps to reproduce

1. export and see difference 

## Observed result

this is an screen shot from preview : 

![screenshot 2018-07-04 20 47 55](https://user-images.githubusercontent.com/426713/42287432-8f6c6028-7fcb-11e8-8cb5-12302ebc0186.png)

and this is after export : 

![screenshot 2018-07-04 20 48 40](https://user-images.githubusercontent.com/426713/42287464-ad8d39e2-7fcb-11e8-8417-d44c3c30b00f.png)

## Expected result

to see same result as preview.
## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 285 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 330M OpenGL Engine
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2047
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by pooyaGames** [comment]
occurred since 107.2, dont know exact release but i think there wasn't such a problem before.

**Comment by pooyaGames** [comment]
minifying script is ok but deduplicating images causes problem.

i do have an sprite with 100+ frames

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. They explain exactly what to do if you don't want to share your project.

**Comment by pooyaGames** [comment]
Actually i just can sit and hope for problem to get solved because its not practical to remove each event and then wait for project to export and  test again and again, while when problem only occurs with deduplicating checked, its obvious that something is wrong with construct 3.
