### ISSUE TITLE
Tilemap X,Y spacing 

### ISSUE THREAD

**Issue by pinellos** [Scirra/Construct-3-bugs#1766]
## Problem description

When a value is set in the X or Y spacing field the tile is not correctly visualized in the editor.

## Attach a .c3p

[issue_tilemap.zip](https://github.com/Scirra/Construct-3-bugs/files/2164413/issue_tilemap.zip)

## Steps to reproduce

Open a new project
add a tilemap 
load a tileset with a non-zero spacing between the tiles, es. 1px
set the tilemap proprieties X spacing=1 Y spacing=1

## Observed result

the tile showed in the editor is 1px stretched on the right and on the bottom.

## Expected result

the tile is correctly showed as it is visible in the editor

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

**Comment by DiegoScirra** [comment]
Fixed in R114
