### ISSUE TITLE
Error publishing game to Scirra arcade

### ISSUE THREAD

**Issue by owlsensei** [Scirra/Construct-3-bugs#1767]
## Problem description

<After exporting a Construct 3 game to the Scirra arcade, loading it and then filling in game descriptions and instruction, when I then go to update details and move to the adding a picture page, I keep getting an error message and can't publish. >

## Attach a .c3p

[Dragon flight.zip](https://github.com/Scirra/Construct-3-bugs/files/2164876/Dragon.flight.zip)

## Steps to reproduce

1. Go to Upload new game on Scirra arcade and exported game zip file
2. On the next page enter some descriptions and instructions 
3. Scroll down and try to click update details to go to the next page on publishing

## Observed result

The next page went straight to an error message (see below for details) and wouldn't let publishing progress to next stage.

## Expected result

Game description/instructions page would be accepted and I would see the page where you attach the game picture which is 450x300 pixels. 

## Affected browsers

* Chrome: yes
* Firefox: yes/no ?
* Edge: yes/no ?
* Safari: yes

## System details

<details><summary>View details</summary>

PASTE HERE

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--
<
[HttpException (0x80004005): Not found]    V4Arcade_Viewgame.Page_Load(Object sender, EventArgs e) +3056    System.Web.UI.Control.OnLoad(EventArgs e) +103    System.Web.UI.Control.LoadRecursive() +68    System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1381
--
ATTACHED FILES
<img width="1149" alt="scirra loading error message" src="https://user-images.githubusercontent.com/30638915/42295342-515443a6-803d-11e8-8a65-5f862ca59789.png">
[Dragon flight.zip](https://github.com/Scirra/Construct-3-bugs/files/2164439/Dragon.flight.zip)

</details>

**Comment by AshleyScirra** [comment]
Migrated to https://github.com/Scirra/Construct.net-website-bugs/issues/10
