### ISSUE TITLE
'Keep aspect ratio' does not always respect image aspect ratio

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#177]
## Problem description

The image editor's resize image dialog does not always use the correct aspect ratio when enabling "keep aspect ratio".

## Steps to reproduce

1. Open image editor
2. Import a square image e.g. 512x512
3. Resize image
4. Change the width, e.g. to 256
5. Enable "keep aspect ratio"

## Observed result

The height does not change. If you change the width, it uses the incorrect aspect ratio of 2:1 rather than the original image aspect ratio of 1:1.

## Expected result

Upon enabling "keep aspect ratio", the width and height should immediately be set according to the original image's aspect ratio, and only use the original image's aspect ratio when further modified.

**Comment by DiegoScirra** [comment]
Fixed in r28.
