### ISSUE TITLE
C3 Runtime: Setting Array Value with Constant Index then changing Constant Value doesn't update Index set

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1770]
## Problem description

When setting something in an Array with a Constant Index Variable then changing this Constant Index Variable the Event does not update itself (Array is the same as when the Constant Value was not changed.)

Workaround:
Copy paste the events with the Constant Variable inside them and delete the old ones.

See Steps to reproduce

## Attach a .c3p

[ArrayConstantTest.zip](https://github.com/Scirra/Construct-3-bugs/files/2169857/ArrayConstantTest.zip)
(See Steps to reproduce: from number 5.)

## Steps to reproduce

1. Create an Array
2. Create a Constant Variable (number)
3. Set a value in the array with the Constant Variable
4. Make code to print array to text after setting
5. Start Preview and see that the right value is set
6. Change Constant Value
7. See in Preview that the value is still set at the old constant index
8. Workaround: Copy Paste Event that sets the value with the Constant Variable
9. See in Preview that now BOTH the old and new index are set to the value
10. delete old event

## Affected browsers

* Chrome: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Did you test r108.2? I thought we fixed a similar issue recently already.

**Comment by Leralasss** [comment]
Yes tested in r108-2

**Comment by AshleyScirra** [comment]
Minimal repro: [constant bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2198449/constant.bug.zip) (please try to remove all unrelated events like this)
Steps to reproduce:

1. Preview
2. Change Variable1 to 4
3. Preview

**Comment by AshleyScirra** [comment]
Fixed for next release
