### ISSUE TITLE
Adding 2 Dictionaries into a Container deletes them at start of layout

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1773]
## Problem description

Dictionaries will be destroyed at the start of layout when they are in a container (Container only contains the 2 Dictionaries)

Happens in C2 runtime and C3 Runtime, tested on r108-2

I don't know if this is a bug or intended, but it is unexpected.

## Attach a .c3p

[DictContainerTest.zip](https://github.com/Scirra/Construct-3-bugs/files/2171863/DictContainerTest.zip)

## Steps to reproduce

1. Create 2 Dictionaries
2. Add some Text&Code to display the Dict1 and Dict2 Count
3. Add Dict2 to Dict1 Container (So both Dictionaries are in a Container)
4. Start Preview
5. See that Count of both = 0

If you remove them from the Container Count of both is 1
You can spawn one Dictionary and the other will spawn too (as expected)

## Observed result

Count = 0 for both Dictionaries

## Expected result

Count = 1 for both Dictionaries

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by zumwaltwood** [comment]
Interesting, this is not the case if you add the dictionaries to another container that isn't a dictionary to begin with. Example, create a text object, add the two dictionaries to the text object in a container, make sure you create the container as the text object being the starting point, aka parent

**Comment by AshleyScirra** [comment]
What's the point in putting two dictionaries in a container together? I'd have thought it's only useful to do this with a different type of object like Sprite, so you get a unique dictionary per Sprite.

**Comment by Leralasss** [comment]
Sometimes i want to add multiple Dictionaries and or Arrays together into a Container.
(Bug also happens with Dictionary+Array in a Container)

## Example 1 - RPG with Skilltree:
A Dictionary for the Skilltree Node Levels (which nodes currently have which level)
Another Dictionary for the character stats

I could of course only use 1 Dictionary and add keys like "skilltree_"&Skill_Name but i like 2 Dictionaries more.

## Example 2 - RPG Skilltree:
An Array with skill values (with multiple levels): Dmg 1,2,3,4,...
Another Array with cost values (unlock cost - again multiple levels): Skillpoints 1,1,1,1,...
And a Dictionary for which attributes scale how much: Strength 0.1, Intelligence 0.9, ...

So i can loop through the cost array when buying the skill and substract that from player resources, and loop through the value array for the values (which i need to calculate from attributes and stuff)

## Container because
If i add them all into a Container i only have to pick one of them to get the whole group - So one of them has a instance variable: name="some node" or something that i can pick by evaluate. Else i would have to pick each one.

## Bug relevancy
Of course if they despawn at the start of layout it doesn't really do much because i have to just spawn a new one. It's only annoying when you don't know about it (then you have to test etc.)

**Comment by Leralasss** [comment]
Yes.

With "Create Object" i spawn one object of the Container (and then the others also spawn) and set the instance variables in one object.

When using it i pick the object with the instance variables. (and the others with it)

**Comment by AshleyScirra** [comment]
OK, thanks for the description. Should be working in the next release.
