### ISSUE TITLE
construct panic's when text input is dragged to screen after removing its instance construct 108.2

### ISSUE THREAD

**Issue by pooyaGames** [Scirra/Construct-3-bugs#1774]
## Problem description

construct panic's when text input is dragged to screen after removing its instance construct 108.2

## Attach a .c3p

[New project (1).zip](https://github.com/Scirra/Construct-3-bugs/files/2172208/New.project.1.zip)

## Steps to reproduce

1. open the project attached or a new project 
2. add new textinput object and add it to screen then remove it ( not tried without removing) 
3. now select text input and drag it to layout 

Video for steps to reproduce : 

[Construct3Crash.zip](https://github.com/Scirra/Construct-3-bugs/files/2172212/Construct3Crash.zip)

## Observed result

construct error shows up

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r108-2/main.js, line 63, col 184840
Message: Uncaught Error: effects not supported
Stack: Error: effects not supported at i.ǃHe (https://editor.construct.net/r108-2/main.js:63:184846) at ǃHe.next () at n.ǃiz.ǃxZ (https://editor.construct.net/r108-2/components/bars/propertiesBar/propertiesBar.js:1:26857) at n.ǃiz.ǃMP (https://editor.construct.net/r108-2/components/bars/propertiesBar/propertiesBar.js:1:20993) at window.ǃin.ǃmGp (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:6269) at window.ǃin.ǃqg (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:5958) at Array.ǃP.ǃG.ǃd.ǃG.ǃT.ǃO (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:2827) at ǃG.Event.ǃmHo.ǃmHU (https://editor.construct.net/r108-2/main.js:2:199322) at ǃG.ǃW.ǃo.ǃqG.dispatchEvent (https://editor.construct.net/r108-2/main.js:2:197626) at ǃG.ǃW.ǃo.ǃqG.ǃGql (https://editor.construct.net/r108-2/main.js:2:431560)
Construct 3 version: r108.2
URL: https://editor.construct.net/r108-2/
Date: Sat Jul 07 2018 03:43:47 GMT+0400 (UAE Daylight Time)
Uptime: 24.7 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 330M OpenGL Engine
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2047
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, EXT_sRGB, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context
</details>

**Comment by shortercode** [comment]
Thanks for the report, looks like this was introduced by changes to the properties bar so that it can display object types with no instances. Should be fixed in the next release.
