### ISSUE TITLE
Construct 3 Image editor Crop no padding moves image points by 1 pixel on both the X and Y axis

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#1776]
## Problem description

In the construct 3 image editor, holding ctrl to crop without padding moves the image'S image points by +1 on the X an
## Attach a .c3p

https://puu.sh/ASiYp/b04a86b939.c3p

## Steps to reproduce

1. Open the image editor
2. Hold down the Ctrl key
3. PRess the crop button

## Observed result

The origin and the image point both move
 
## Expected result

I expected the origin and the image points to not move

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed in r114
