### ISSUE TITLE
Windows construct 3 beta, can't preview same project twice

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1778]
## Problem description

Downloaded windows 3 beta, made new project and clicked preview. When you close preview window,  you can't open preview anymore. It instantly closes itself when you click preview.

## Steps to reproduce

1.Open Windows 3 beta
2.Open new
3.Click preview and close window
4. Try to click preview again, preparing project data window opens for <0.5sec and closes itself.

## Observed result

Windows 3 beta won't allow to preview same project twice. After you close preview, you need to close project  and reopen to preview again. It 

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 17.17134
Browser engine: Edge
Browser architecture: 64-bit
Context: windows-store
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; MSAppHost/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
C3 release: r108.2 (beta)
Language setting: en-US 
Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable) 
Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Canvas toBlob is not supported. Image processing performance may be degraded.
Determining input device capabilities is not supported.
image-set() is not supported. Mouse cursors may appear with reduced quality.
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Microsoft
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:
WEBGL_compressed_texture_s3tc
OES_texture_float
OES_texture_float_linear
EXT_texture_filter_anisotropic
OES_standard_derivatives
ANGLE_instanced_arrays
OES_element_index_uint
WEBGL_debug_renderer_info
WEBGL_depth_texture
EXT_frag_depth
OES_texture_half_float
OES_texture_half_float_linear
WEBGL_lose_context
OES_vertex_array_object
WEBGL_draw_buffers
EXT_blend_minmax
EXT_shader_texture_lod
EXT_color_buffer_half_float
WEBGL_color_buffer_float
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:
Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)
Video information
Supported decode formats:
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by AshleyScirra** [comment]
This appears to be a bug in the Windows Store: when you close the popup window, it actually just hides the window and continues running invisibly! It seems to be impossible to detect the window closing, and since the window continues to run and respond to messages, the next time you press preview it just refreshes an invisible window and nothing new appears.

I can't find any good way to work around this other than to switch the Store app over to dialog preview mode, which seems to work OK, which I've done for the next release. The popup preview mode is now disabled in the Store app until the issue I've filed can be fixed: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18282335/
