### ISSUE TITLE
Can't add image points to a sprite

### ISSUE THREAD

**Issue by jgmy** [Scirra/Construct-3-bugs#178]
## Problem description

*I can't add image points to a sprite*

## Attach a .c3p

[Imagepointsdontwork.zip](https://github.com/Scirra/Construct-3-bugs/files/997911/Imagepointsdontwork.zip)

## Steps to reproduce

1. Open Sprite editor.
2. Draw something.
3. Click on "Image Points"
4. Click on "Add Image Points"

## Observed result
a) The image point changes shape, but ...
b) ... There are no new image points listed on the list of image points, and ...
c) ... If you drag your "new" image point, you are editing the imagepoint 0.

## Expected result

Creation of a new image point.

## Affected browsers

* Chrome: yes
* Firefox: no (since it is not supported at all.)
* Edge: no (since it is not supported at all.)
* Safari: I don't know. If you lend me a mac, I'll tell you.

## System details

---------------------
<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 105 gb
Storage usage (approx): 45 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by jgmy** [comment]
I don't know if imagepoints is a "paid" feature. I had it in C2, but _I used a paid C2.

**Comment by DiegoScirra** [comment]
@jgmy

Are you using the latest version?

I can reproduce it, and a similar bug was fixed in r24. #139

**Comment by jgmy** [comment]
It seems my browser did not upgrade the construct version. It works ok now.


-----
Perdon por  las posibles faltas, escribo desde un móvil...
