### ISSUE TITLE
Marketplace - website request

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1784]
Please add a link on the top menu of the construct 3 home page to the market place.
I like to buy stuff but can't find an easy way to the marketplace on the new website that makes any sense. Actually, I just went through each menu item on the construct 3 website, there is no way to get to the marketplace at all.

This site needs the store link at the top
https://www.construct.net

**Comment by TomGullen** [comment]
Not willing to add outbound links to Scirra.com from Construct.net I'm afraid.
