### ISSUE TITLE
Trigger (e.g. "On Click") ignores parent 'Else' condition

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1786]
## Problem description

Trigger ignore parent conditions and just fire their actions.

I don't know if this is intentional, but it's unexpected.

Tested in C2 and C3 runtime (happens in both) on r108-2

## Attach a .c3p

[TriggerTest.zip](https://github.com/Scirra/Construct-3-bugs/files/2181902/TriggerTest.zip)

## Steps to reproduce

1. Open Project
2. Start Preview
3. Press Right Mouse Button
4. Notice that the sprite rotates to mouse even though only left mouse should be able to activate that

## Observed result

Trigger ignores Parent Condition

## Expected result

Parent Condition restricts Trigger

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
The events make no sense, so marking 'wontfix'.

The 'Else' event means 'the previous event did not meet its conditions'. Triggers fire outside of the normal top-to-bottom flow of events. When a trigger fires, it also checks all its parent events are true to make sure it's allowed to run. However asking an "else" condition whether it's true or not outside of the normal top-to-bottom flow of events doesn't make any sense: the previous event did not run at all, so it is neither true nor false, so it's basically undefined behavior.
