### ISSUE TITLE
So Much Loading While Saving or Opening File which contains only 4.5 mb obb file

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#179]
## Problem description
Time on Saving and opening a file taking too much time 
File containing 4mb obb sound
*Enter a concise description of your problem here*
I insert obb file into a blank project and try to save it to Dropbox
1) It taking too much time approx 10-15 min. sometime 20 minute i have to close browser & restart it again, Tried again Same result found.
2) Sometime after 10-15 min. it never saves my file and a small popup comes with button only "OK" written on that button and then i have to save that again and have to wait again for what will happen next
3) Once it saved. then I do little change on project to make "save button active" and press save button to save the progress. process again longer for 5-10 minutes. and sometimes it asks to save it again with name.

## Attach a .c3p
[Sample File](https://www.dropbox.com/s/8xjsc6d5colneuy/Sample%20file%20for%20Ashley.c3p?dl=0)
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. get obb from my file or try it with any other obb file
2. insert it on project
3. press save button

## Observed result
Processing ... & Processing ...
*What do you see happen?*
processing ... saving...
## Expected result
should save file immediate and open immediate 
*What did you expect to happen instead?*
should save file immediate and open immediate 
## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
What's the upload speed and latency like on your internet connection? Values from an online speed test would be helpful. I timed it to be less than 5 seconds to open the project from dropbox and about 4 seconds to save it. Initial save takes a little longer as it has to create the remote file as well. Still nowhere near as long as your experiencing though obviously.

By the sounds of it there's possibly a few bugs involving an intermittent connection. I can't really make it upload / download any faster. I might be able to tweak the number of requests, which will help with poor latency I guess.
