### ISSUE TITLE
[r102.8] - Crash after cloning FORM CONTROLS

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#1790]
## Problem description

Right-click an object "Form Controls" and choose "clone" from the context menu. Then left-click to the clone:  Construct crash. (Windows 10 and Ubuntu 17.04)

## Attach a .c3p

[bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2185022/bug.c3p.zip)

## Steps to reproduce

See this video: 

[![Construct 3 beta - bug cloning FORM CONTROLS
](https://img.youtube.com/vi/OF0dpYxk1nE/0.jpg)](https://www.youtube.com/watch?v=OF0dpYxk1nE)

1. Right-click an object "Form Controls"
2. Choose "clone" from the context menu
3. Left-click to the clone

## Observed result

Construct crash

## Expected result

Select the object

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details><summary>Console log</summary>
Corrupted recent project data Object__proto__: Object
main.js:168 Registered service worker on https://editor.construct.net/r108-2/
main.js:63 Uncaught Error: effects not supported
    at i.ǃHe (main.js:63)
    at ǃHe.next (<anonymous>)
    at n.ǃiz.ǃxZ (propertiesBar.js:1)
    at n.ǃiz.ǃMP (propertiesBar.js:1)
    at window.ǃin.ǃmGp (projectBar.js:1)
    at window.ǃin.ǃqg (projectBar.js:1)
    at Array.ǃP.ǃG.ǃd.ǃG.ǃT.ǃO (projectBar.js:1)
    at ǃG.Event.ǃmHo.ǃmHU (main.js:2)
    at ǃG.ǃW.ǃo.ǃqG.dispatchEvent (main.js:2)
    at ǃG.ǃW.ǃo.ǃqG.ǃGql (main.js:2)
</details>

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r108-2/main.js, line 63, col 184840
Message: Uncaught Error: effects not supported
Stack: Error: effects not supported at i.ǃHe (https://editor.construct.net/r108-2/main.js:63:184846) at ǃHe.next () at n.ǃiz.ǃxZ (https://editor.construct.net/r108-2/components/bars/propertiesBar/propertiesBar.js:1:26857) at n.ǃiz.ǃMP (https://editor.construct.net/r108-2/components/bars/propertiesBar/propertiesBar.js:1:20993) at window.ǃin.ǃmGp (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:6269) at window.ǃin.ǃqg (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:5958) at Array.ǃP.ǃG.ǃd.ǃG.ǃT.ǃO (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:2827) at ǃG.Event.ǃmHo.ǃmHU (https://editor.construct.net/r108-2/main.js:2:199322) at ǃG.ǃW.ǃo.ǃqG.dispatchEvent (https://editor.construct.net/r108-2/main.js:2:197626) at ǃG.ǃW.ǃo.ǃqG.ǃGql (https://editor.construct.net/r108-2/main.js:2:431560)
Construct 3 version: r108.2
URL: https://editor.construct.net/r108-2/
Date: Wed Jul 11 2018 16:09:07 GMT+0200 (Ora legale dell’Europa centrale)
Uptime: 226 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

Error report information
Type: unhandled exception
File: https://editor.construct.net/r108-2/main.js, line 63, col 184840
Message: Uncaught Error: effects not supported
Stack: Error: effects not supported at i.ǃHe (https://editor.construct.net/r108-2/main.js:63:184846) at ǃHe.next () at n.ǃiz.ǃxZ (https://editor.construct.net/r108-2/components/bars/propertiesBar/propertiesBar.js:1:26857) at n.ǃiz.ǃMP (https://editor.construct.net/r108-2/components/bars/propertiesBar/propertiesBar.js:1:20993) at window.ǃin.ǃmGp (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:6269) at window.ǃin.ǃqg (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:5958) at Array.ǃP.ǃG.ǃd.ǃG.ǃT.ǃO (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:2827) at ǃG.Event.ǃmHo.ǃmHU (https://editor.construct.net/r108-2/main.js:2:199322) at ǃG.ǃW.ǃo.ǃqG.dispatchEvent (https://editor.construct.net/r108-2/main.js:2:197626) at ǃG.ǃW.ǃo.ǃqG.ǃGql (https://editor.construct.net/r108-2/main.js:2:431560)
Construct 3 version: r108.2
URL: https://editor.construct.net/r108-2/
Date: Wed Jul 11 2018 16:10:01 GMT+0200 (Ora legale dell’Europa centrale)
Uptime: 41.4 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

Error report information
Type: unhandled exception
File: https://editor.construct.net/r108-2/main.js, line 63, col 184840
Message: Uncaught Error: effects not supported
Stack: Error: effects not supported at i.ǃHe (https://editor.construct.net/r108-2/main.js:63:184846) at ǃHe.next () at n.ǃiz.ǃxZ (https://editor.construct.net/r108-2/components/bars/propertiesBar/propertiesBar.js:1:26857) at n.ǃiz.ǃMP (https://editor.construct.net/r108-2/components/bars/propertiesBar/propertiesBar.js:1:20993) at window.ǃin.ǃmGp (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:6269) at window.ǃin.ǃqg (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:5958) at Array.ǃP.ǃG.ǃd.ǃG.ǃT.ǃO (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:2827) at ǃG.Event.ǃmHo.ǃmHU (https://editor.construct.net/r108-2/main.js:2:199322) at ǃG.ǃW.ǃo.ǃqG.dispatchEvent (https://editor.construct.net/r108-2/main.js:2:197626) at ǃG.ǃW.ǃo.ǃqG.ǃGql (https://editor.construct.net/r108-2/main.js:2:431560)
Construct 3 version: r108.2
URL: https://editor.construct.net/r108-2/
Date: Wed Jul 11 2018 16:10:51 GMT+0200 (Ora legale dell’Europa centrale)
Uptime: 32.8 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Thanks for the report. Related to #1774. Should be fixed in the next release.
