### ISSUE TITLE
Physic bug with origin imagepoint

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1791]
## Problem description

Apply physic to image point is different when its origin or image point 1. Which is bugged behavior, but i like it as it gives ability to move object with mass and complex polygon, and results does not give object a rotation.
!But this strange good behavior only works at object angle 0. So, image point "origin" should give this good behavior with all angles or non.

## Attach a .c3p

[PhysicBUG2.zip](https://github.com/Scirra/Construct-3-bugs/files/2187499/PhysicBUG2.zip)

## Steps to reproduce

1.Open example
2.Preview example
3.See that objects which have same image point location, act different depending if its origin or image point 1.

## Observed result

Apply forces or impulses give different behavior depending if its image point origin or 1.

## Expected result
Solutions
1. Origin image point should give ability to apply force/impulse to object(with mass)and  complex collision polygon  to move it without changing object angle(like it slide on ice). You can do it, if object does not have mass, but if it has, it will start to spin.
2.Origin image point should act like all other image points.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 603 mb (4.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The problem here is the image point parameters are misleadingly described. It actually uses 0 for the center of gravity (where it normally doesn't cause rotation, which is normally what you want), and -1 refers to the origin (which may not be at the center of gravity and so could still result in rotation). If you change the image point parameters to -1 it works as expected since it uses the actual origin point. Thanks for pointing this out though - I've updated both the manual and the parameter descriptions to explain that 0 is the center of gravity and -1 is the origin.

**Comment by SnipG** [comment]
How to move object with mass + complex polygon with angle something else then 0, in a way that it does not start to rotate. At small angles and 0, using center of mass is better then origin, and is good. But with angles, it turn out a bit bad, both rotate one more then other. Of course if you have square bounding box, then both work with no rotate.

**Comment by AshleyScirra** [comment]
I don't know, the rotation is calculated by the physics engine (box2d). You can either use the center of mass or a custom point, and the resulting simulation is whatever box2d simulates.
