### ISSUE TITLE
Autosaves are going in the wrong place

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#1792]
## Problem description

Autosaves are going to the root of my google drive instead of where the save is
## Attach a .c3p

not applicable

## Steps to reproduce

1.Autosave

## Observed result

My root folder is filled with a ton of different autosaves from different projects and it'S a huge mess

## Expected result

I expected them to go into their respective folders

## Affected browsers

* Chrome: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 2 gb (14.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
What is your backup location set to?

**Comment by eleanorawesome** [comment]
Ah I did not know that you could choose where to auto-save, it probably wasn't a feature when I started using cloud saves, so maybe it defaulted into "google drive" instead of same location or I got confused about what it meant or something.

Sorry about the false bug report

**Comment by shortercode** [comment]
That's okay, it's easy to miss something like that in the settings. I believe "match" is the current default value, and it's probably the one your want in this situation.  But I know some people use local autosaves if they have a slow internet connection.

Provided the autosave setting is "match" or the same as the projects service it should always try to save next to the existing project. But if it isn't it will just save to the root as it has no hints where to save the file.
