### ISSUE TITLE
Remote preview Bug

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1793]
## Problem description

Something that works pc, is not working on remote preview. Tried 2 phone both had same problem.

## Attach a .c3p

[RemotePrevBUG.zip](https://github.com/Scirra/Construct-3-bugs/files/2191888/RemotePrevBUG.zip)

## Steps to reproduce

1.Start example
2.Preview example
3.Move button, button at touch end, moves back centre of its base.
4.Start remote Preview
5.Try it out on some phone, button does not get back centre at its base

## Observed result

Code where there is 2 block. If first block is tru, change variable -1. Secount block, if variable is >= 0, do something. On pc it works correctly, but on phone, even if first block changes variable, secount block still executes. 

## Expected result

Remote preview should work like on PC

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 799 mb (5.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
This seems to be an issue with mobile, not remote preview. If you try remote preview on the desktop the issue does not replicate, I can see the issue on my phone though.

**Comment by SnipG** [comment]
Yeah.  I never needed to remote preview into another browser tab, so i used it with mobile mostly. Could change title if needed.

**Comment by shortercode** [comment]
Took a little while to diagnose this as I'm not massively familiar with the Touch plugin.

You've stumbled onto undefined behaviour in your project I'm afraid. Your event sheet is technically wrong but works when it's run with touch emulation, because the ID and the INDEX are the same value when your using a mouse. The "on touch end" event accepts the touch INDEX and your using the touch ID so the event never fires.

I resolved the issue in your project by adding an extra variable for the index value and that solved the problem. The other option would be to have a "on any touch end" with a second condition "touchID == Touch.TouchID" for the event instead.

**Comment by SnipG** [comment]
Well i had that on any touch end before, but i tought if i use such thing in multiple places + some other condition, then every time i touch screen, alot of events need to be checked. 
But this case came from - i optimized something tested on phone, marked CPU % down, then i thought if remote preview gives similar % i do not need export so often. And then i got this bug. I mean if you export APK this undefined behavior will work!!, it just dont on remote preview

**Comment by SnipG** [comment]
Okey iam back.
Tested debug APK - works
Remote into mobile - does not work
Pc - works
Why does it work in debug APK?

**Comment by shortercode** [comment]
Well storing Touch.TouchIndex in a variable and using that as the value for your "ontouchend" will have exactly the same CPU usage as your existing setup, but works correctly. 

I'm not sure why it works when it's exported as an APK. But by the nature of undefined behaviours they do work in some circumstances, mostly through luck. I can think of 1 situation where it would probably still break as an APK so I would not rely on that working.

**Comment by SnipG** [comment]
You wrote your comment same time as i edited mine, anyway. Yeah using variable is better, it fails with APK to when tested more.

**Comment by SnipG** [comment]
I had nothing to do so i rooted this bad behavior - Its still bugged in remote preview, i opened new issue with better example and title: #1795
