### ISSUE TITLE
Angular Data Sync Error On Multiplayer [C3 Runtime]

### ISSUE THREAD

**Issue by cihanyakar** [Scirra/Construct-3-bugs#1794]
## Problem description
Got error when angle sync
`C3.anglelerp is not a function`
 

## Steps to reproduce

 1. Open "Multiplayer Game Example"
2. Game Events / Sync Peer  set Data to "Position and angle"
3. Change runtime to "Construct 3"

## Observed result

Peer can not move.

## Expected result

Bad experience but no error.

## Affected browsers

* Chrome: yes

## System details

Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r108.2 (beta)
Language setting: en-US

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
