### ISSUE TITLE
Touch.touchID bugged in remote preview with mobile

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1795]
## Problem description

Touch.touchID gets bugged while doing remote preview with mobile. I think it is just touchID count which does not reset.

## Attach a .c3p
[TouchIDBugged.zip](https://github.com/Scirra/Construct-3-bugs/files/2193178/TouchIDBugged.zip)

## Steps to reproduce

1.Preview example
2.Remote preview it with mobile, see touchID does not reset

## Observed result

Touch.touchID bugged in remote preview with mobile, while works in debug APK on mobile 

## Expected result

No bug. Should work like in PC and APK.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 750 mb (5.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I don't see any difference between the APK and remote preview. TouchID increments with each new touch, but that's expected behaviour.

What is it that you think is wrong with the TouchID?

**Comment by shortercode** [comment]
Just to be clear, TouchID is a value provided by the browser and it should always be unique.

**Comment by SnipG** [comment]
When i preview example with PC - TouchID always stays 0 - no increment, does not matter how much times i touch. 
When i remote preview in browser, similar behavior as previous. No increment.
Same in debug APK, no increment.
TouchID does increment if i do multitouch in previours examples, but if i remove my touches, everything will go back 0.

But now when i remote preview into phone. TouchID value gets incremented each time i touch. To 100+ etc. It does gets deincrement if i do multitouch, but base value still stays 50,60. etc

Why all other test are different and why is remote preview into phone special - and have different results?
When i remote preview into phone and first Touch.IID starts from 2(which should be third touch). + Same when i touch multiple times, lets say 10. Then i keep my 10 touch on place, add 3 more fingers. TouchID go 14, i will remove fingers 1 by 1. Touch.ID wil go back 10. Now i touch 1 finger at time, it will go 11, 12...to infinity.

**Comment by SnipG** [comment]
Remote debug pic from phone that is in remote preview
![debugpreview](https://user-images.githubusercontent.com/28864889/42703600-aecc214a-86d5-11e8-944f-8b6701cd923b.jpg)

**Comment by shortercode** [comment]
That image is exactly what I expect, and what I got on everything other
than desktop. When you have a mouse plugged in there is only one pointer
that never starts or finishes so it always has the same ID.

On mobile whenever a touch event starts it has to consider it a new
pointer. The ID is unique to that pointer so it cannot be reused, hence the
counter just increases.

Why is this a problem? The other pointers don't exist past their touch end
event. So it's not like it's a memory leak.

**Comment by SnipG** [comment]
Well my APK does same as your desktop, it does not increment. So my phone could have problem?

**Comment by SnipG** [comment]
If it is like it should be, then its all good. As i only saw this strange increment only on remote preview on phone, as it acted different then other cases, i though it should be bug. If its correct, then all is fine.

**Comment by SnipG** [comment]
Anyway, your variable version is better, and i don't rly need to use that touchIndex or ID anymore. But as you mentioned that you had same increment on APK and remote preview and each touch need new ID.So i looked a bit futher into it, and maybe some info helps you  or not, you decide.
 First i thought my xiaomi with custom android MIUI is causing it.  So i got my hands on Samsung galaxy S9 and did test - no increment.
Was spamming my touches on it: 
![screenshot_20180714-150608_new project](https://user-images.githubusercontent.com/28864889/42724320-9fa8b68a-8778-11e8-8f53-43b162fd62ae.jpg)
And it is bugged behavior on S9 to. Like if i only use 1 finger all ID values etc are good. using multiple fingers/touches bugs touchID super easy, LIke adding 3 finger 1 by 1, and removing first finger - all ID resets 0. 
Maybe my example code it bad i don't know, but i leave this here so it can helps with C3 development. Is similar bugs raise somewhere else.

**Comment by shortercode** [comment]
It's slightly odd behaviour, not sure why the S9 is affected but the S8 I'm using isn't. I guess at least it's semi unique...

The value is coming from the device not us so I can't do much, and not causing a problem here so I'm going to close this bug. Your testing project looks helpful for debugging touch events, so thanks for that.

**Comment by AshleyScirra** [comment]
FWIW there is no guarantee what the touch ID will be at all, it's defined by the system and browser. The only guarantee that all simultaneous touches will have different IDs. Other than that it can choose negative numbers, incrementing numbers, something in the high billions, resetting every time touches are released, etc. It shouldn't matter what it does and apps shouldn't depend on specific touch IDs.

**Comment by SnipG** [comment]
Just some random new info.
When i export same project without minify script enabled, my xiaomi phone starts to increment touchID like it does on remote preview, or when i use my phone to log into C3 and open new project and debug it.

**Comment by NetOneGames** [comment]
There is still issue with touch and minification.
 I am going to get to the bottom of it this weekend.....

**Comment by NetOneGames** [comment]
got it

https://github.com/Scirra/Construct-3-bugs/issues/2592
