### ISSUE TITLE
[Possible Issue] bf_onlyone and SetIsOnlyOneAllowed conflict.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1797]
## Problem description

I have encountered a bug report from a behavior that I made. 
Reference : 
https://www.construct.net/forum/construct-3/general-discussion-7/construct3-construct-2-essenti-136150

I have 2 solutions, one is the easy way and another is the hard way.
I tried to take the hard way route, and I found a workaround but it didn't work the way I expected it. So, I moved on to the easy way.

**That was to prevent _only-once-behaviors_ from adding into families in the first place, if the behavior has already been added on to the object which is included in the family.** But I did not find a way to implement that, but I could ask the Construct Team.

Surprisingly strange though, the [OnlyAddOnce] Behavior, **when added on to the family. You can no longer add that behavior on the specific object that is included in that family.**
But the other way around (which is my problem), is possible.

## Steps to reproduce

A Visual Representation of adding [SetIsOnlyOneAllowed] Behaviors on Construct::

**1) Construct 2 :: Allowed**
```
Add Behavior to Object -> Add Behavior to Family
Add Behavior to Family -> Add Behavior to Object
```
Reference :: https://1drv.ms/u/s!AjcW2ueud6qpgZ0qltPZPnBrWF4Yxw

**2) Construct 3 :: Allowed**
```
Add Behavior to Object -> Add Behavior to Family.
```
Reference :: https://1drv.ms/u/s!AjcW2ueud6qpgZ0oD-WAX6uQINTYuA

**3) Construct 3 :: Not Allowed**
```
Add Behavior to Family -> Add Behavior to Object
```
Reference :: https://1drv.ms/u/s!AjcW2ueud6qpgZ0ps19d4aDJm2iYzg

## Expected result

***Add Only Once Behaviors should only be added once. Even on families.***

## Observed result

***Construct 3 allows / doesn't allow adding multiple [AddOnlyOnce]behaviors, depending on the situation, both Object and Family. But Construct 2 allows either way.***

##Note

Thank you in advance for looking into this.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
