### ISSUE TITLE
Crash when selecting TextInput object in the Project view after all instances have been deleted

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#1798]
## Problem description

Created a TextInput in my layout, deleted it, clicked the TextInput in the project view, crashed.

## Attach a .c3p

Easy to reproduce with a new project.

## Steps to reproduce

1. Create a new TextInput object and click to place the first instance in the layout.
2. Delete the instance.
3. Click the TextInput object in the Project view.

## Observed result

Construct crashes.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r108-2/main.js, line 63, col 184840
Message: Uncaught Error: effects not supported
Stack: Error: effects not supported at i.ǃHe (https://editor.construct.net/r108-2/main.js:63:184846) at ǃHe.next () at n.ǃiz.ǃxZ (https://editor.construct.net/r108-2/components/bars/propertiesBar/propertiesBar.js:1:26857) at n.ǃiz.ǃMP (https://editor.construct.net/r108-2/components/bars/propertiesBar/propertiesBar.js:1:20993) at window.ǃin.ǃmGp (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:6269) at window.ǃin.ǃqg (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:5958) at Array.ǃP.ǃG.ǃd.ǃG.ǃT.ǃO (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:2827) at ǃG.Event.ǃmHo.ǃmHU (https://editor.construct.net/r108-2/main.js:2:199322) at ǃG.ǃW.ǃo.ǃqG.dispatchEvent (https://editor.construct.net/r108-2/main.js:2:197626) at ǃG.ǃW.ǃo.ǃqG.ǃGql (https://editor.construct.net/r108-2/main.js:2:431560)
Construct 3 version: r108.2
URL: https://editor.construct.net/r108-2/
Date: Sat Jul 14 2018 16:21:49 GMT-0700 (Pacific Daylight Time)
Uptime: 30.3 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by pooyaGames** [comment]
seems to be same as #1774

**Comment by Scoremonger** [comment]
Ah, yep, I searched to see if this had already been written, but I guess since this one was already closed it didn't turn up. I believe it's the same bug though.
