### ISSUE TITLE
No way to enable "Fade" behavior in action

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#1799]
## Problem description

I disabled the fade behavior so that it wouldn't start immediately. But now I can't find any action that says "enable" like i can with other behaviors.

![image](https://user-images.githubusercontent.com/5744908/42743748-10997874-890a-11e8-8efb-de5b39b5351c.png)

## Attach a .c3p

NA

## Steps to reproduce

1. Fade behavior
2. add action window

## Observed result

no "enable fade" action

**Comment by Wackytoaster** [comment]
In the time you wrote the bugreport you could have just tried "Start fade" and noticed it does what you are looking for. Though I agree that the naming is not optimal. Instead of "Enabled" it should probably say "Active on start"

**Comment by alastajj** [comment]
This is possibly related to bug #1747

**Comment by AshleyScirra** [comment]
As far as I can tell, Fade has never had a 'Set enabled' action. Looks like an oversight.

**Comment by AshleyScirra** [comment]
Actually, it's not an oversight: turning off "enabled" simply means the fade won't run immediately and it will wait until you use the "Start fade" action. (The property description actually says that!) I think we just named the property "enabled" for consistency with other behaviors.
