### ISSUE TITLE
Bug with tilemaps

### ISSUE THREAD

**Issue by renan-vinicius** [Scirra/Construct-3-bugs#18]
## Problem description

I'm testing the new version of Construct and I have a problem with Tilemap objects. When I put the tilemap on layout, I see the exactly the tile that I chose. Although, when I play the game, the tiles are different. I posted it in the forum and the user Kyatric identified that this occur when we change the value of X spacing.

There's the project: https://goo.gl/pbafG1

## Steps to reproduce

1. Create a Tilemap
2. Change the X spacing value on Properties
3. Put the tiles on layout and play the project.

## Affected browsers

* Chrome: yes
* Firefox: yes

**Comment by Kyatric** [comment]
For further informations : https://www.scirra.com/forum/tilemaps-on-construct3_t190242

**Comment by DiegoScirra** [comment]
Fixed. You can try this out in r17 when it is released.

**Comment by renan-vinicius** [comment]
I believe that this bug returns, because I'm having problem with this in R47.

**Comment by AshleyScirra** [comment]
@renan-vinicius - please file a new bug following all the guidelines, since this issue was already closed and is quite old now.
