### ISSUE TITLE
(C2 Runtime)  Crash deleting Objects sub-folder (only on larger projects?)

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1800]
## Problem description

Have not been able to replicate this on new project
however it happens with my project and it is also replicates with all the C3 demo games.
It only replicates with certain folders I have not been able to identify why.

## Attach a .c3p

Pick any of the C3 demos.

## Steps to reproduce

Open Kiwi Story Demo
Delete the HUD&GUI sub folder
Crash

Open GLokar
Delete Enemies or HUD&GUI or Player Subfolders
Crash

Open Pop Lab
Delete SpriteFonts Subfolder 
Crash

Open Demonoir
Delete Enemies Subfolder
Crash

edit 1) it may not be directly related to the subfolders but rather the number of objects in the sub folder and the order they are deleted.  eg in Glokar if you delete the objects in the enemies folder one by one from the top you get a crash on deletion of one of the lower objects.  But if you start from the bottom and delete up you get a crash on one of the upper objects.

edit 2)  does not happen on stable release however highlights **### new undo issue** with stable release.
i.e. on Glokar.  (with stable release 104)
Delete enemies subfolder then undo.     **folder is returned but is empty**
Then delete the HUDGUI folder and undo .  **Enemies subfolder is repopulated and HUDGUI is returned empty!**

## Observed result

crash with reports similar to below 

## Expected result

no crash

## Affected browsers

* Chrome: yes only tested

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃM' of undefined @ TypeError: Cannot read property 'ǃM' of undefined at window.ǃin.ǃmGg (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:10900) at Array.ǃP.ǃG.ǃd.ǃG.ǃT.ǃO (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:1481) at ǃG.Event.ǃmHo.ǃmHY (https://editor.construct.net/r108-2/main.js:2:199505) at window.ǃIKZ.dispatchEvent (https://editor.construct.net/r108-2/main.js:2:197636) at window.ǃIKZ.ǃGxr (https://editor.construct.net/r108-2/main.js:168:81374) at t.ǃGBF (https://editor.construct.net/r108-2/main.js:63:192981) at i.ǃGSV (https://editor.construct.net/r108-2/main.js:63:178360) at i.ǃGSr (https://editor.construct.net/r108-2/main.js:63:80813) at i.ǃGSr (https://editor.construct.net/r108-2/main.js:63:166622) at i.ǃGSr (https://editor.construct.net/r108-2/main.js:63:168845)
Stack: TypeError: Cannot read property 'ǃM' of undefined at window.ǃin.ǃmGg (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:10900) at Array.ǃP.ǃG.ǃd.ǃG.ǃT.ǃO (https://editor.construct.net/r108-2/components/bars/projectBar/projectBar.js:1:1481) at ǃG.Event.ǃmHo.ǃmHY (https://editor.construct.net/r108-2/main.js:2:199505) at window.ǃIKZ.dispatchEvent (https://editor.construct.net/r108-2/main.js:2:197636) at window.ǃIKZ.ǃGxr (https://editor.construct.net/r108-2/main.js:168:81374) at t.ǃGBF (https://editor.construct.net/r108-2/main.js:63:192981) at i.ǃGSV (https://editor.construct.net/r108-2/main.js:63:178360) at i.ǃGSr (https://editor.construct.net/r108-2/main.js:63:80813) at i.ǃGSr (https://editor.construct.net/r108-2/main.js:63:166622) at i.ǃGSr (https://editor.construct.net/r108-2/main.js:63:168845)
Construct 3 version: r108.2
URL: https://editor.construct.net/r108-2/index.html
Date: Mon Jul 16 2018 21:12:00 GMT+0100 (British Summer Time)
Uptime: 287.1 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r108.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in next release.
