### ISSUE TITLE
Move multiple frames weird

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#1801]
## Problem description

Thanks for adding multiple selection frames in r109 ! Finally! :-)
It's cool that we can delete multi selected frames.
But it's very hard to move them as we want to...
The vertical blue bar is not always present, and the selected images do not move where we would like to put them.

## Attach a .c3p

[TEST_select_multiple_frames.zip](https://github.com/Scirra/Construct-3-bugs/files/2201868/TEST_select_multiple_frames.zip)

## Steps to reproduce

1. Open the Sprite
2. Select the 3 red frames
3. Try to move them before the 3 greens frames

## Observed result

Wrong position

## Expected result

3 red at frame 0,1 and 2.
It's the same if you try to move the 3 blues before the 3 red...etc...
They don't move where we want to...
And sometimes, when you use CTRL Z, the frames are dispatched anywhere...

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This will be fixed for the next version. Turns out the moving logic was completely messed up, sorry about that.

Let me know how does it work in the next version!

**Comment by Picoti** [comment]
Yes now the frames can be moved normally. Thanks!
But ther's just a crash when I move the frames. But I don(t understand why. here is the bug report 

Error report information
Type: unhandled exception
File: https://editor.construct.net/r110/main.js, line 80, col 183578
Message: Uncaught Error: must be array of finite numbers
Stack: Error: must be array of finite numbers at t.ǃSe_ (https://editor.construct.net/r110/main.js:80:183584) at e.ǃTym.ǃTqj (https://editor.construct.net/r110/main.js:80:775238) at Array.ǃLzH.addEventListener (https://editor.construct.net/r110/main.js:80:771478) at ǃS.Event.ǃLKZ.ǃLKG (https://editor.construct.net/r110/main.js:2:200448) at ǃS.ǃQ.ǃm.ǃLFb.dispatchEvent (https://editor.construct.net/r110/main.js:2:198577) at Function.ǃLuW (https://editor.construct.net/r110/main.js:2:466067) at i (https://editor.construct.net/r110/main.js:2:463545) at ǃS.ǃQ.ǃm.ǃLzj.ǃCF (https://editor.construct.net/r110/main.js:2:464878) at HTMLDocument.ǃKS (https://editor.construct.net/r110/main.js:2:458680) at HTMLDocument. (https://editor.construct.net/r110/main.js:2:195329)
Construct 3 version: r110
URL: https://editor.construct.net/r110/
Date: Mon Jul 23 2018 22:45:30 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 960.3 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r110 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 950 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by Picoti** [comment]
I think the bug appear when I move some frames that aren't next to each other (exemple : 2 and 4)

**Comment by Picoti** [comment]
OK I found the problem 
for exemple : If you select frame 1 and 3 and you want to move them before 3

**Comment by AshleyScirra** [comment]
Reopening for @DiegoScirra to investigate crash report

**Comment by DiegoScirra** [comment]
That one crash should be fixed for the next release. Hopefully it is the only one.

**Comment by Picoti** [comment]
OK! It's okay now! It works fine. Thanks.

**Comment by AshleyScirra** [comment]
Thanks for checking!
