### ISSUE TITLE
[Website] Request To Remove Char Limit For Forum Posts

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1803]
## Problem description
I'm the owner of [THIS](https://www.construct.net/forum/construct-2/general-discussion-17/updated-15-05-2018-the-big-nw-119428) huge forum topic.

While trying to update the topic to fix some of the issues caused by the "old forum import", I've reached the new char limit it seems. This new restriction completely renders my topic useless and I would like to request the removal of this newly implemented char limit.

I personally see no point in having this in the first place, since bots are being stopped by the _captcha_ and moderators can simply remove obvious spam posts like they always do.

_Cheers!_

**Comment by Kyatric** [comment]
+1

The plugin/behavior list for C2 is now completely fudged up because of this as well.
The how do I FAQ for C2 should not be edited at all because of it as well.

**Comment by TheRealDannyyy** [comment]
![tempsol](https://user-images.githubusercontent.com/15656049/43073517-306e6d4c-8e7a-11e8-8294-2ab076f303fb.PNG)
Might still be an issue for _mega topics_ but for now I think it should be fine so closing.

**Comment by Kyatric** [comment]
Issue is not fixed.
It is not possible to copy/paste back all links in the OP of the C2 addons list (see the topic, I'm leaving it as it for now).

When editing, it is OK indeed, you can place as many characters as you want.
When you submit, the post is simply truncated.

Check with the How do I FAQ for Construct 2 in relation to a post with a huge number of characters.

Also 60k limit means that in 20k characters the issue will show up again.

**Comment by AshleyScirra** [comment]
@TomGullen said it was fixed in the next update. Maybe the website hasn't actually been updated yet?

**Comment by Kyatric** [comment]
OK I'll wait and test out later.

**Comment by TheRealDannyyy** [comment]
If the charlimit is a MUST for the new forum, perhaps adding a button to manually request a _charlimit unlock_ could help. Just do the request and let a moderator approve or deny it.

**Comment by AshleyScirra** [comment]
I'm not sure it's as simple as that, it's related to how databases work.

**Comment by TheRealDannyyy** [comment]
Alright. Is there a way to check when website updates go live?
Don't want to edit my post and lose half of it just to find out that it's not out yet.

**Comment by Kyatric** [comment]
I've just tested and it does work.
The Plugin list is now back as it should be in the OP.
