### ISSUE TITLE
[Desktop Build Windows Store] Crash when moving the Properties window to second screen.

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#1808]
## Problem description

When moving the properties Window to the second screen on the Windows Store version of C3, the editor crashes every time.
Please note this is working correctly on other versions of C3, and is also working on Windows Store build if moving the properties panel to the same screen.

## Attach a .c3p

not relevant

## Steps to reproduce

1. Open the Windows Store desktop build
2. open a new project or close the start page
3. Move the properties window to a second screen.

## Observed result

the editor crashes

## Expected result

being able to place the properties window on the second screen.

## Affected browsers

Desktop build (Windows Store version only)

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r109/main.js, line 2, col 271079
Message: Un appel COM à ASTA a été bloqué, car la chaîne d’appels provenait d’un autre ASTA ou est passée par ce dernier. Ce modèle d’appel est sujet aux interblocages et a été rejeté par le contrôle d’appel cloisonné. 
Stack: Error at t (https://editor.construct.net/r109/main.js:2:271079) at ǃrtB (https://editor.construct.net/r109/main.js:2:272910) at ǃrtM (https://editor.construct.net/r109/main.js:2:270028) at ǃcB (https://editor.construct.net/r109/main.js:2:269776) at Anonymous function (https://editor.construct.net/r109/main.js:2:268983)
Construct 3 version: r109
URL: https://editor.construct.net/r109/
Date: Wed Jul 18 2018 12:06:13 GMT+0200 (Paris, Madrid (heure d’été))
Uptime: 13.6 s 
Platform information
Browser: Edge
Browser version: 17.17134
Browser engine: Edge
Browser architecture: 64-bit
Context: windows-store
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; MSAppHost/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
C3 release: r109 (beta)
Language setting: en-US 
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Microsoft
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: WEBGL_compressed_texture_s3tc, OES_texture_float, OES_texture_float_linear, EXT_texture_filter_anisotropic, OES_standard_derivatives, ANGLE_instanced_arrays, OES_element_index_uint, WEBGL_debug_renderer_info, WEBGL_depth_texture, EXT_frag_depth, OES_texture_half_float, OES_texture_half_float_linear, WEBGL_lose_context, OES_vertex_array_object, WEBGL_draw_buffers, EXT_blend_minmax, EXT_shader_texture_lod, EXT_color_buffer_half_float, WEBGL_color_buffer_float

</details>

**Comment by AshleyScirra** [comment]
In all browsers, opening a popup window throws a JavaScript exception in the popup due to `cloud` being undefined. For some reason this works in Chrome but prevents the popup window loading in Edge. Assigning to @shortercode to take a look, probably just need to disable cloud code in popup windows. Let's fix that before investigating the MS Store app again.

**Comment by shortercode** [comment]
Just been and resolved that issue and it doesn't seem to have made any difference, so it probably wasn't blocking the popup loading. Also worth noting that while it doesn't load in edge, it crashes on the windows store version with an unpleasant error message.

> A COM call to an ASTA was blocked because the call chain originated in or passed through another ASTA. This call pattern is deadlock-prone and disallowed by apartment call control.

**Comment by AshleyScirra** [comment]
I can't get popup windows to work at all in Edge - it just throws a mysterious exception along the way. The crash in the Store app looks really nasty too (and might be related?) I think the only thing we can do is remove the "open to popup window" feature in Edge and the Store app, which I've done for the next release.
