### ISSUE TITLE
[r26] Crash when drawing rectangular tile area

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#181]
## Problem description

When attempting to paint a rectangular tile area using the Draw Rectangle Areas tool, while two or more tiles in a vertical column were selected, the editor crashed. Note that the editor doesn't crash when painting with a 2x2 group of tiles, 3x3, etc.

## Attach a .c3p
[Proto.zip](https://github.com/Scirra/Construct-3-bugs/files/998838/Proto.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Create a tilemap object and accept the default tiles.
2. Select two or more tiles in a column and choose the Draw Rectangle Areas tool (see attached screenshot).
![2017-05-13 11_02_49-proto - construct 3](https://cloud.githubusercontent.com/assets/28039905/26028006/de48c7d8-37cc-11e7-97a1-1b5ae28b09a1.jpg)
3. Inside the layout view, click and drag to start painting the tiles.

## Observed result

After painting a few tiles, the editor crashes.

## Expected result

No crashes.

## Affected browsers

* Chrome: yes

## System details

Crash report below.

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r26/components/bars/tilemapBar/tilemapBar.js, line 1, col 31807
Message: Uncaught TypeError: Cannot read property '0' of undefined
Stack: TypeError: Cannot read property '0' of undefined at window.ǃdf.ǃbg.ǃUf (https://editor.construct.net/r26/components/bars/tilemapBar/tilemapBar.js:1:31807) at window.ǃdf.ǃbg.ǃmx (https://editor.construct.net/r26/components/bars/tilemapBar/tilemapBar.js:1:31042) at window.ǃdf.ǃbg.ǃmd (https://editor.construct.net/r26/components/bars/tilemapBar/tilemapBar.js:1:26552) at Array.ǃmQ.s (https://editor.construct.net/r26/components/bars/tilemapBar/tilemapBar.js:1:25318) at ǃN.Event.ǃijb.ǃijm (https://editor.construct.net/r26/main.js:2:285388) at window.ǃQg.dispatchEvent (https://editor.construct.net/r26/main.js:2:283969) at window.ǃQg.ǃpG (https://editor.construct.net/r26/components/editors/layoutView/layoutView.js:1:14540) at HTMLDocument.ǃpT.W (https://editor.construct.net/r26/components/editors/layoutView/layoutView.js:1:2374) at HTMLDocument. (https://editor.construct.net/r26/main.js:2:280653)
Construct 3 version: r26
URL: https://editor.construct.net/index.html
Date: Sat May 13 2017 11:08:43 GMT-0700 (Pacific Daylight Time)
Uptime: 166 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r28.

Thanks for the feedback!
