### ISSUE TITLE
Tilemap rotation preview doesn't update on the layout edges

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1811]
## Problem description

If you press "a" or "z" to rotate the selected tile it will be previewed on the layout, but if the cursor is too close to the edge of the layout the tilemap rotation will only be updated if you move the cursor again.
https://i.imgur.com/GH6uqnu.gif

## Attach a .c3p

[Tilemap Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2206238/Tilemap.Bug.zip)

## Steps to reproduce

1. Select a tile.
2. Move the cursor to the edge of the layout.
3. Press "a" or "z" to rotate the tile.

## Observed result

The preview will not work properly.

## Expected result

The preview to work properly.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r114

**Comment by BonzerKitten7** [comment]
Thank you, Diego!
