### ISSUE TITLE
Selection tool ignoring one pixel

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1813]
## Problem description

If you make a selection by clicking and dragging the cursor down and right it will make a selection including the first pixel you selected, but if you click and drag the cursor up and left it will ignore the first pixel you selected.

https://i.imgur.com/4MiGEld.gif

## Attach a .c3p

Unnecessary.

## Steps to reproduce

1. Choose the selection tool
2. Click and drag the cursor up and left.

## Observed result

The selection tool will ignore one pixel.

## Expected result

The selection tool to not ignore one pixel.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r114.

The rectangle tool now also has the same behavior.
