### ISSUE TITLE
[Possible Issue][Part 2] Having Multiple Layers with Different Parallax, changes the Scroll Position to the Bottom Right Edge of the Layout.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1818]
## Problem description

**This happens when changing the Canvas Size + LayoutScale.**

[2/2] This is the second out of the 2 issues.
Part 1 :: https://github.com/Scirra/Construct-3-bugs/issues/1817 

## Minimal Project Sample

[BugReport2.zip](https://github.com/Scirra/Construct-3-bugs/files/2212096/BugReport2.zip)

## Steps to reproduce

1. Preview from first layout.
2. Notice that the Button is now gone.

## Observed result

**The Button doesn't show.**

## Expected result

Having Multiple Layers with Different Parallax when changing the layout scale or canvas size shouldn't move the scroll position to the bottom right. It should stay in place, the top-left by default.

**The Button should show up.**

## System details

Construct 3 :: Release 109
Construct 2 :: Release 261

## Note

There is still a Part 1 version of the issue, which seems similar to this Part 2 version of the issue.

Thank You in advance for looking into this.

**Comment by AshleyScirra** [comment]
Look in the debugger. Your events cause the viewport to be 240-720 on the Y axis, and the button is placed at 150-188 on the Y axis. So it is off the top of the screen. The anchor objects move with the viewport so you can still see them.
