### ISSUE TITLE
[r26] Previously selected tool doesn't function when re-editing a sprite

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#182]
## Problem description

After creating a sprite, editing it (with the Fill tool, for example), closing it, doubling clicking the sprite in the layout editor to edit it, the selected tool doesn't do anything until the user clicks it again.

## Attach a .c3p

[SpriteEditorBug.zip](https://github.com/Scirra/Construct-3-bugs/files/999170/SpriteEditorBug.zip)

## Steps to reproduce

1. Create a sprite.
2. Click the Fill tool, and fill the sprite with a color (I'm using the Fill tool as an example, but this also happens with others like Pencil, Brush, etc.)
3. Close the sprite.
4. In the layout view, double-click the sprite to re-open the sprite editor.
5. Notice the Fill tool is still selected, as-expected. Change the Fill color, then click inside the sprite to fill it with a different color.

## Observed result

Nothing happens.

## Expected result

The Fill tool should function as normal.
Note that clicking the already-selected tool again will restore its full functionality.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 108 mb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Are you still able to reproduce this one in r28?

**Comment by Scoremonger** [comment]
Nope, this looks fixed as of r28!
