### ISSUE TITLE
Global Layer uses "Show Translucent Inactive Layers" from original Layout

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1823]
## Problem description

When having a Global Layer **from another Layout** (you are in a layout where the layer is overwritten) the global Layer uses the "Show Translucent Inactive Layers" from the Global Layer Layout.

This means that
1. When you use Translucent Layers in the Global Layer Layout and the Global Layer is at 33% Opacity, in the other Layouts the Global Layer will also have 33% opacity.
2. When you use Translucent Layers in another Layout and you select a different layer, it is locked BUT at 100% opacity

(Global Layer Layout = Original Layout
another Layout = not original layout - global layer is copied to here)

## Attach a .c3p

[GlobalLayer.zip](https://github.com/Scirra/Construct-3-bugs/files/2216983/GlobalLayer.zip)

## Steps to reproduce

1. Open Project
2. select Layout 1 and Layer 1
3. notice that the Global Layer is still at 100% opacity, but locked

## Observed result

Global layer is at 100% opacity

## Expected result

Global layer is at 33% opacity

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed in r114
