### ISSUE TITLE
Adding a project file that uses text editor breaks construct on chrome

### ISSUE THREAD

**Issue by PerAtwood** [Scirra/Construct-3-bugs#1824]
## Problem description

Empty project (freshly created, nothing has been added) - adding a project file that requires text editor breaks Construct with an error (see below). Problem occurs for json, txt, svg, html, xml, javascript and stylesheet files. 

## Attach a .c3p

 No .c3p attached (it is an empty new project).
## Steps to reproduce

1. Create new project file.
2. Add json, txt, svg, html, xml, javascript or stylesheet file.
3. Receive Construct error

## Affected browsers

* Chrome: **yes**/no

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Unable to setup text editor @ Error: Unable to setup text editor at a.then.catch (https://editor.construct.net/r104/components/editors/textEditor/textEditor.js:1:3922)
Stack: Error: Unable to setup text editor at a.then.catch (https://editor.construct.net/r104/components/editors/textEditor/textEditor.js:1:3922)
Construct 3 version: r104
URL: https://editor.construct.net/
Date: Sun Jul 22 2018 17:07:30 GMT+0200 (Central European Summer Time)
Uptime: 10.7 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r104 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by NetOneGames** [comment]
Not seeing this in 104 or 109 , 
How are you adding the project files?

**Comment by PerAtwood** [comment]
Right click -> New -> JSON

I have just tested it on a mac using chrome, no problem there. I will try deleting cookies and emptying cache and whatnot, will report back here.

**Comment by AshleyScirra** [comment]
Also can't reproduce in either r104 and r109. The original report was using r104; as per the bug report guidelines, please only file bugs that reproduce in the latest version of C3 (currently r109) to avoid reporting issues that we've already fixed. Please file again if you can find a way to reliably reproduce this in the latest version.
