### ISSUE TITLE
Deleting an event sheet not deleting the references to a global variable causes the c3p file to be considered as not valid.

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1826]
## Problem description

Related to https://github.com/Scirra/Construct-3-bugs/issues/1825

If you delete an event sheet that contains a global variable in a project with other event sheets referencing this global variable and save your project, when you open it later again, Construct refuses indicating this is possibly not a valid c3p file.

## Attach a .c3p

https://kyatric.com/c3/bugs/2018.07.22.delete_event_sheet.c3p
https://kyatric.com/c3/bugs/2018.07.22.delete_event_sheet_deleted.c3p

## Steps to reproduce

1. Open 2018.07.22.delete_event_sheet.c3p (basic setup)
2. Delete "Event sheet 2" from the project bar
3. Save as a new c3p file
4. Close the project
5. Try to open the newly saved c3p file

Note: 2018.07.22.delete_event_sheet_deleted.c3p is my version where I deleted the event sheet and saved and that fails to open again.

## Observed result

Construct 3 fails to open the file mentioning the project is possibly not a valid Construct 3 project file.

## Expected result

The c3p should open.

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r109 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 730 mb (5.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by NetOneGames** [comment]
ouch,  good find

**Comment by AshleyScirra** [comment]
This is the same issue as #1825, since once fixed this doesn't happen any more. Verified with the fix that the project still opens after following these steps.
