### ISSUE TITLE
Mobile, letterbox integer scale with portrait will position sprite wrong, when switching back from fullscreen, in remote preview

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1829]
## Problem description

Having letterbox integer scale, and switching fullscreen and back, sprite will disappear as it wont reposition sprite when switching back.

## Attach a .c3p

[BuggyAnchor01.zip](https://github.com/Scirra/Construct-3-bugs/files/2219205/BuggyAnchor01.zip)

## Steps to reproduce

1.Preview example, go full screen and back all good in preview.
2.Remote preview in mobile, tap full screen, click back to exit it
3.Sprite will disappear and will be seen again, if you go back fullscreen.

## Observed result

Does not move sprite back in right position when exit fullscreen

## Expected result

Moves sprite back in right position

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r109 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 536 mb (3.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can't reproduce any issue in either C2 or C3 runtime with this project. Can you add some screenshots to show what you're seeing? Is there any way to more reliably reproduce the problem?

**Comment by SnipG** [comment]
First when i go remote preview all is correct. I tap i get:
![screenshot_2018-07-23-15-31-05-084_com android chrome](https://user-images.githubusercontent.com/28864889/43076721-c71ede4e-8e8d-11e8-9400-349dbf30c401.png)

I go back i get: 
![screenshot_2018-07-23-15-31-10-765_com android chrome](https://user-images.githubusercontent.com/28864889/43076728-cc8d013a-8e8d-11e8-9edd-0c879e14f0b7.png)

When i go full screen back, i get 1 picture, then again 2 picture, when i exit.

**Comment by SnipG** [comment]
This could be phone specific issue.

**Comment by SnipG** [comment]
In c3, i added text object in front of sprite, each tick move top of layer. even tought sprite gets right position when i exit fullscreen. text object cannot be seen anymore. Even if i duplicate whole layout full of them.

**Comment by SnipG** [comment]
Something to add: if i use this browser scale outer event. It will brake most fullscreen modes, act different when switched fullscreen holding phone sideways or portrait. And even sometimes disappear text objects and reappear depending, in which way i holded my phone - landscape or portrait. Everything is fixed if i use. Event - browser fullscreen - Centered.

**Comment by SnipG** [comment]
Indeed, unbounded scrolling fixed all for me.

**Comment by SnipG** [comment]
there is till 1 issue,
if you add text object to this example. Each tick set text. Text object still disappear in C3 runtime. even with unbounded scrolling enabled.

**Comment by AshleyScirra** [comment]
The code in the C2 runtime around this is a bit of a mess, and there's a backwards compatibility concern around changing this too. Since it already works better in the C3 runtime and there's an easy workaround (unbounded scrolling) I think the best thing to do is just leave it as a minor compatibility difference between the runtimes.
