### ISSUE TITLE
[r26] Editor not highlighting selected objects (on the layout) in the project tree

### ISSUE THREAD

**Issue by glerikud** [Scirra/Construct-3-bugs#183]
## Problem description

One of my students popped up a quite logical question: If you can select all instances of an object placed on the layout by clicking on the object's name in the project tree, why doesn't the editor highlight the currently selected object's name in the project tree if the user clicks on an instance on the layout?

I realize that this is just a minor thing and by no means a game breaking bug, but since the issue came up during educational usage, it might be worth looking into this.

## Attach a .c3p

Since this is an editor bug, no c3p needed. The issue happens with a new project as well with only 2 sprites added to it.

## Steps to reproduce

1. Open up a project with objects on the layout or create a new project and add 2 sprites (as 2 separate objects) to the layout.
2. Click on each sprite on the layout and observe the project tree.

## Observed result

The project tree shows no indication on which object has been selected on the layout.

## Expected result

The project tree should either select the object's name in it's list (just like when the user clicks on it) or as indicating that not necessarily all of it's instances were selected it could show a grey rectangle around the object's name in the project tree.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 7.8 gb
Storage usage (approx): 147 mb (1.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Clicking an object in the project bar is essentially a shortcut for "select all instances of that type" in the active layout view. So really the reverse would be if you select all instances of that type in the layout view (not one - all), then select the item in the project bar. I'm not sure this is really a convincing or necessary feature, it doesn't have any functional benefit to change the project bar selection and in some cases manually selecting all instances of a type in a layout view is impractical.

**Comment by glerikud** [comment]
I think if it would select it with a different color in the project tree, indicating that not all of the object's instances are selected could help the learning process, but I understand your reasoning why you don't want to implement this. Thank you for taking the time to look into it.
