### ISSUE TITLE
Editor Autocomplete: Tab doesn't work like other characters

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1831]
## Problem description

When changing an action with a field where you write text, keys that are not letters/numbers autocomplete the text AND write the key you pressed. (e.g. **/** or **(** or **.** or **,** etc.)

The tab key autocompletes but does NOT tab.

(Tested in r109)

## Steps to reproduce

1. Create a Function Object and create a "Call Function" Action
2. Add parameters
3. Try typing text and pressing tab to autocomplete
4. Notice Tab autocompletes but does not tab

## Observed result

Tab autocompletes but does not tab to next field.

## Expected result

Tab autocompletes AND tabs to next field.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
This is by design. Keyboard shortcuts should only do one thing at a time; autocompleting and changing focus means two things happen with one key press, and makes it impossible to use tab to only autocomplete a term without changing focus. You can always just press tab twice.
