### ISSUE TITLE
Line of sight can't see if the other object is too close

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1833]
## Problem description

If you place an object with LOS too close to what it's supposed to detect, it wont be able to see the target unless you increase it's cone of view. I'm using 1 or 2 degrees for the cone of view, which is a low value, but sometimes all we need is a single line of view, like a raycast, but it seems like the LOS behaviour is not optimized for this kind of usage. It would be a nice addition to have a checkbox for "raycast" and an "direction" box to change the cone of view/raycast direction independently of the object angle.

Like this: https://i.imgur.com/C2v5R7k.png

This is how the LOS behaviour see with a 20 degree COV: https://i.imgur.com/d3Qw21u.png

This is how the LOS behaviour see with a 10 degree COV: https://i.imgur.com/tWCRcRD.png

This is how the LOS behaviour see with a 5 degree COV: https://i.imgur.com/yzFxYbc.png

This is how the LOS behaviour see with a 1 degree COV: https://i.imgur.com/k5YOr69.png

It already start to "skip" some sprites with a 10 degrees COV.

I guess it could also be fixed if the LOS behaviour searched for collision polygons instead of origin points.

## Attach a .c3p

[LOS Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2220822/LOS.Bug.zip)

## Steps to reproduce

1. Change the cone view to a really low value.
2. Check how many red blocks it can destroy.

## Observed result

The LOS behaviour "skip" many red blocks.

## Expected result

The LOS behaviour to not "skip" any red block.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's working correctly. LOS is computed by the object origin only. The LOS object is at Y = 233, and the nearest small red sprites are at Y = 231 and Y = 235, i.e. 2px away either side of a straight line extending right from the object. As the cone of view shrinks it gets closer to a perfect straight line, which will go between the nearer objects, excluding them from the view cone. You're essentially seeing aliasing artefacts from representing a very narrow cone with 4x4 blocks.

**Comment by BonzerKitten7** [comment]
I'm still not convinced that it's not a bug. I added the sine behaviour to the blue sprite and it completely ignored the red sprites many times, even when they're in front of the blue sprite.
https://i.imgur.com/V4RFeQP.gif

**Comment by AshleyScirra** [comment]
It's stepping in small jumps every frame. So the chance an extremely thin line, stepping several pixels a frame, intersects with a given point, is very low.

**Comment by BonzerKitten7** [comment]
It may not be a bug, but it's definitely not 100% reliable. In the end i'm still having some problems with it in my game. Anyway, thank you for the explanation! I hope to see this behaviour improve in the future.
