### ISSUE TITLE
C3runtime export issue

### ISSUE THREAD

**Issue by Keevle** [Scirra/Construct-3-bugs#1834]
## Problem description

After seeing the recent release of r110 I immediately wanted to try out the exporting so I opened up the platformer example project and exported then uploaded it to https://themurica.app/c3runtimeplatformer/index.html

## Attach a .c3p

The capx is the default platformer template

## Steps to reproduce

1. Start construct
2.Select the platformer template
3.Enable experimental features
4. Change the runtime to the c3 runtime
5.Export

## Observed result
Uncaught ReferenceError: C3 is not defined

## Expected result

The project runs perfectly fine like it does in the preview mode

## Affected browsers

* Chrome: yes
* Firefox: na
* Edge: yes
* Safari: na

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.31.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@878cd31214ac27a3996927cd5c9c138b10c9fc8d) NWjs/0.31.2 (like Chrome/67.0.3396.87)
C3 release: r110 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 612 gb
Storage usage (approx): 63 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Radeon(TM) RX 460 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
Works in dev, looks like the build system messed this up somehow...

**Comment by AshleyScirra** [comment]
There's a fix for this in r110.2. Can you verify if your project works when exporting with the C3 runtime in that version?

**Comment by Keevle** [comment]
Works on my end 👍

**Comment by AshleyScirra** [comment]
Great, thanks for checking.
