### ISSUE TITLE
Animations editor, animations folder expand/collapse will crash C3

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1838]
## Problem description

Using mouse to collapse/expand animations editor animations folder, will crash C3.

## Steps to reproduce

1.Open new
2.Add sprite -> open animations editor
3.Add subfolder with right click in animations tab.
4. Right click animations subfolder and try expand/collaps
5. C3 crash.

## Observed result

C3 will crash, when you try to expand or collaps animations subfolder.

## Expected result

No crash

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r110/main.js, line 80, col 766204
Message: Uncaught ReferenceError: item is not defined
Stack: ReferenceError: item is not defined at o.ǃtS (https://editor.construct.net/r110/main.js:80:766204)
Construct 3 version: r110
URL: https://editor.construct.net/r110/
Date: Tue Jul 24 2018 14:30:25 GMT+0300 (Eastern European Summer Time)
Uptime: 65.1 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r110 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed.
