### ISSUE TITLE
Disable webgl in C2 runtime+fullscreen quality low -> black screen

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1839]
## Problem description

Webgl disabled in c2 runtime results some window/fullscreen black bug

## Attach a .c3p

[WebGlFullBlackBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2224019/WebGlFullBlackBug.zip)

## Steps to reproduce

1.Open example
2.Preview, see black window
3.Resize window -> fix

4.Cant resize on mobile, so without browser request(to trigger some changes) - permanent black screen.

## Observed result

Black screen on C2 runtime, when webgl is disabled

## Expected result

No black screen.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r110 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 558 mb (4.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SnipG** [comment]
More info: if you resize - stuff gets fixed and you close window and open again and see it works. Or you open first time and it work. 
To reproduce issue again. Preview -> resize window -> close(multiple times, each time change size). So when you open preview, it opens window into that last size you closed. 
Issue here is that, it will show black screen on some sizes!

**Comment by AshleyScirra** [comment]
This might be wontfix. According to webglstats.com only 2% of devices still don't support WebGL, and there's really no good reason to turn WebGL off these days (especially since it reduces performance up to 10x slower). So I'm not sure it's worth spending our limited development time on obscure cases like this if it's not really affecting real-world games.

**Comment by AshleyScirra** [comment]
Resolved by simply ignoring the fullscreen quality mode in canvas2d renderer - it'll always use "high".

**Comment by SnipG** [comment]
Could there be option to disable canvas2d, for game not to fall into that? I tried with my old phone android 4.1.1 and default internet browser(not chrome, havent been updated for years). With that kyatric chrome report on some webgl issue, there he hosts some game example. That old phone with 4.1.1 - does not have webgl 1 or 2. But it opens that game with 2 game windows, literally 2 game canvases one below other, clicking 1 does same action on both canvases. Its super laggy, but such possiblity could open ways to mess/hack leaderboards etc(not sure if that gives this possibility but still).

**Comment by AshleyScirra** [comment]
With our limited development resources, hundreds of other bugs being filed, and other major projects in development, I'd rather not get involved with any kind of maintenance for the ancient canvas2d renderer.
