### ISSUE TITLE
Bounce bullet off object (error in C2 as well)

### ISSUE THREAD

**Issue by 3dParadox** [Scirra/Construct-3-bugs#184]
## Problem description

The manual says if there is no overlap when "bounce off object" is called, nothing will happen, but it appears to give a runtime javascript error in C3:
```
Javascript error!
Uncaught ReferenceError: msg is not defined
https://editor.contruct.net/r36/preview/c2/preview_prelude.js, line 20 (col 37)
```
C2 also errors, but it's error message says:
```
Assertion failure: Bounce normal computed as NaN

(see full stack trace in details below)
```

## Attach a .c3p
https://www.dropbox.com/s/lrd6349fv9nstjm/BounceError.c3p?dl=0

## Steps to reproduce

1. run the attached c3p
2.
3.

## Observed result

Error pop up, and the sprite has vanished on closing of the error message.

## Expected result

The lack of anything to bounce off of, would result in no bounce.

## Affected browsers

* Chrome: yes (both C3 and C2
* Firefox: yes (in C2
* Edge: yes (in C2
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Assertion failure: Bounce normal computed as NaN

Stack trace: 
assert2@http://localhost:50000/preview_prelude.js:16:10
Runtime.prototype.calculateSolidBounceAngle@http://localhost:50000/preview.js:4739:3
Acts.prototype.Bounce@http://localhost:50000/Bullet_behavior.js:291:21
Action.prototype.run_object@http://localhost:50000/eveng.js:1848:5
EventBlock.prototype.run_actions_and_subevents@http://localhost:50000/eveng.js:931:8
EventBlock.prototype.run@http://localhost:50000/eveng.js:888:4
EventSheet.prototype.run@http://localhost:50000/eveng.js:224:4
Runtime.prototype.logic@http://localhost:50000/preview.js:2692:4
Runtime.prototype.tick@http://localhost:50000/preview.js:2380:3
Runtime.prototype.initRendererAndLoader/this.tickFunc@http://localhost:50000/preview.js:700:42

Subsequent failures will now be logged to the console.

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r27, and also next build of C2.
