### ISSUE TITLE
Dark Theme (macOS): Behaviour/Plugin Icons only show up partially

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#1840]
## Problem description

When adding a plugin or behaviour, the icons in the list of available things only show up partially and most won't (see screenshot):

![image](https://user-images.githubusercontent.com/30116964/43144613-deb93b00-8f5d-11e8-8ae3-e8f5f5710bd6.png)

## Steps to reproduce

1. Open C3 in Chrome on macOS
2. Change to Dark Theme
3. Make a new Project
4. Try to add a Plugin through double clicking

## Observed result

See Screenshot.

## Expected result

All icons to show up.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r110 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 131 gb
Storage usage (approx): 462 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce on macOS 10.13.5 with Chrome 67. All icons look fine.

I think we had a similar case on Linux that was a GPU driver issue. Your best bet might to install any available system updates.

**Comment by joelmayer87** [comment]
Just saw this tagged as "can't reproduce" and checked again with the 110.2 update - cheeky, now they show up :D Really weird. But it works so you can close this issue, thank you.

**Comment by AshleyScirra** [comment]
We didn't change anything for this in r110.2, but probably a driver issue if it's sporadic or can't reproduce on other macOS devices.

**Comment by joelmayer87** [comment]
That might very well be, thank you for checking it out though and keep up the great work ^^
