### ISSUE TITLE
Transparent screen on multiplayer with updates

### ISSUE THREAD

**Issue by Nabbo-extreme** [Scirra/Construct-3-bugs#1842]
## Problem description

With reference to #1835, tried to isolate the issue. I added flash behaviour to ball on multiplier ball which caused to goto transparent mode. I suspect something to do with frame rate or flash behaviour. 

## Attach a .c3p

[Multiplayer pong flash (1).zip](https://github.com/Scirra/Construct-3-bugs/files/2225526/Multiplayer.pong.flash.1.zip)

## Steps to reproduce

1. Rename to c3p and Export to android debug apk
2. start android version as host
3. join with any version of browser will cause transparent screen..

## Observed result

frame rate issue or flash behaviour causing transparent screen when multiplier peer joins on android. Tried to use latest built to test but same result. 

## Expected result

Something is causing transparent screen on android please help to trace out as I tried so many option to isolate it. Please note that this issues does not happen on browser either on PC or mobile but happens only on apk. I tried 3 different mobile all showing same result. 

Secondly, it works perfectly if I remove multiplayer here or in my original project also.

## Affected browsers

* Chrome: no
* Firefox: no
* Android: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.87
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Android
Operating system version: 8.0.0
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2.625
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 8.0.0; SM-N950F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36
C3 release: r104 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 3.5 gb
Storage usage (approx): 105 mb (2.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ARM
Renderer: Mali-G71
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by Nabbo-extreme** [comment]
Please note that I tested on R109 also. Couldn't test on R110 as it was crashing on my Mac.

**Comment by AshleyScirra** [comment]
Can't reproduce on an HTC 10 with Android 8: it works fine in an APK either as host or peer.

This may in fact be nothing to do with Multiplayer or the Flash behavior. We've had reports of GPU driver issues with WebGL 2 on Android lately. Due to this we've disabled WebGL 2 on Android as of r111. Could you try with that release and see if you can still reproduce the issue?

**Comment by Nabbo-extreme** [comment]
Hi Ashley, its fixed with R111, thx. But can we expect WebGL 2 fix in future?

**Comment by AshleyScirra** [comment]
It's up to Google or the GPU driver makers to fix WebGL 2.
