### ISSUE TITLE
Manual: Hyperlinks displaying as full URLs

### ISSUE THREAD

**Issue by TheSpydog** [Scirra/Construct-3-bugs#1843]
## Problem description

I noticed when browsing the Interface page of the manual that some links are displaying the full URL before the intended link text. An example:

<img width="624" alt="screen shot 2018-07-24 at 11 18 26 pm" src="https://user-images.githubusercontent.com/8942401/43177782-ed518a2a-8f97-11e8-80e1-9108e2eb4415.png">

## Attach a .c3p

N/A

## Steps to reproduce

Visit the [linked Manual page](https://www.construct.net/make-games/manuals/construct-3/overview/the-interface).

## Observed result

See above.

## Expected result

Just the text "Main menu button" without the URL in front.

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: yes

## System details

N/A

**Comment by TomGullen** [comment]
Fixed in version 490
