### ISSUE TITLE
C3 runtime - cannot export with 'minify script' enabled

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#1844]
## Problem description

When i export the Kiwi project with the C3 runtime enabled (don't know if that makes a difference though) using nw.js and the settings below, i get an export error message.

![image](https://user-images.githubusercontent.com/30116964/43190005-43e61e18-8ff8-11e8-9dcc-2e76b38f508d.png)

![image](https://user-images.githubusercontent.com/30116964/43189974-393d80be-8ff8-11e8-8599-b7f33ce336d3.png)

![image](https://user-images.githubusercontent.com/30116964/43189938-275c532a-8ff8-11e8-94d2-c718c698a89e.png)

## Steps to reproduce

1. Open the Kiwi project
2. Enable C3 runtime
3. Choose export with nw.js
4. Check all options for deduplicating images etc. (see screenshot above)
5. Choose macOS as your export platform and the latest nw.js release

## Observed result

Export fails and error message appears.

## Expected result

That either the export succeeds or getting a more concise message of why it failed exactly.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r110.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 131 gb
Storage usage (approx): 860 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Looks like it happens with a normal HTML5 export too, if you enable "Minify script".

**Comment by AshleyScirra** [comment]
Think this is fixed in the next release. Only seemed to happen with projects using the 'Platform' behavior.
