### ISSUE TITLE
C3 Runtime: Typewriter missing last character

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#1846]
## Problem description

I tried out the new Typewriter Feature on a normal Text object with the C3 runtime. Unfortunately, it seems that it's always missing the last character of a sentence. (See attached .c3p).

## Attach a .c3p

[typewriter.zip](https://github.com/Scirra/Construct-3-bugs/files/2228344/typewriter.zip)

## Steps to reproduce

1. Add text object
2. Start typewriting on start of layout

## Observed result

Last character of a text is missing.

In this example (very fittingly) i tried to write the word "Hello" but only got "Hell" instead :D

## Expected result

The full word to show up.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r110.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 131 gb
Storage usage (approx): 658 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by joelmayer87** [comment]
This is a bit offtopic but it would be really useful if you could add a few conditions to the typewriter function like "if typing" "if typing stopped" etc. as well as some actions like "complete text".

A good example is Toby R's Typewriting Addon:

![image](https://user-images.githubusercontent.com/30116964/43208991-eeab0290-902b-11e8-8fea-7d297178e1f8.png)
![image](https://user-images.githubusercontent.com/30116964/43209030-fe88b91e-902b-11e8-9aff-f9cb65c2ec41.png)

**Comment by AshleyScirra** [comment]
Fixed for next release.
