### ISSUE TITLE
Whitelisting GameAnalytics on Exchange Addons for Construct 3 Build Service

### ISSUE THREAD

**Issue by asdzxc8** [Scirra/Construct-3-bugs#1847]
## Problem description

Addon / Plugin won't work if you directly export as a Xcode or Sign Released APK using the Construct 3 Build Service. Needs to be whitelisted if possible.

I feel that Analytics is as important as Ads and IAP (basic feature) as any serious developers would want to have any sort of data tracking in their app.

GameAnalytics is the only Analytics addon / plugin for C3. If not, Scirra should consider officially supporting at least one of the Analytics out there (just like with Mobile Advert and IAP).

## Observed result

Black Screen
https://www.construct.net/sg/comments/305
GameAnalytics documentation mentioned not working with Xcode Project too.

**Comment by shortercode** [comment]
I'm happy to review the plugin for whitelisting, does it include a cordova plugin? I am unable to see one listed in the `gameanalytics.c3addon/plugin.js` file.

**Comment by shortercode** [comment]
I've read in your documentation that the required plugins are `cordova-plugin-gameanalytics` and `cordova-plugin-device` so I will review those now.

You will need to add them as cordova dependencies to your addon, this way construct will know to include them when exporting. Additionally your users will no longer have to manually add the plugins after export.

See the section on including cordova dependencies within plugins in our SDK documentation [here](https://www.construct.net/gb/make-games/manuals/addon-sdk/reference/specifying-dependencies)

**Comment by asdzxc8** [comment]
I'm the end user actually so it's not my documentation. I've dropped an email to GameAnalytics and hopefully they have someone over to coordinate with you.

**Comment by shortercode** [comment]
Ah well hopefully they get back to us fairly quickly then. In general we're happy to add any plugin that passes a security review if a developer needs it, but I don't think many addon devs are aware you can add cordova plugins as a dependency.

Thanks for filing the report.

**Comment by asdzxc8** [comment]
Thanks for taking the time out to review ! :)

Would be awesome if we don't have to use PhoneGap or Coccon.IO once this is whitelisted.

**Comment by shortercode** [comment]
No worries, we want to make it as easy as possible for people to make Android and iOS games and little things like this can go a long way.

An alternative is that I have been considering allowing users to add additional cordova plugins to their project, it would still be subject to the whitelist but it would allow you to use the build service with addons like this without needing to wait for them to update their addon. Hopefully it could help make addon devs more aware they can add cordova plugins as dependencies as well.

**Comment by shortercode** [comment]
Okay I have reviewed `cordova-plugin-gameanalytics@1.0.11` and `cordova-plugin-device@2.0.2` and both have been added to the whitelist. However, there are some potential compatibility issues with `cordova-plugin-gameanalytics`.

`com.google.android.gms:play-services-base@12.0.1` and `com.gameanalytics.sdk:gameanalytics-android:3.6.2` are included as a sub dependency via a gradle build script. I would be surprised if this works with phonegap build, as they typically block custom build scripts for security so would advise that this is changed. We allow it; hence why plugins have to complete security reviews prior to being whitelisted. Anything from maven.google.com can be included via the normal cordova sub dependency method.

Also the play services dependency is now 3 major versions out of date. The play services libraries do not like the use of mixed versions so including this with any plugin with anything else that uses play services will likely prevent the build from completing. Unless a specific version is required I would advise the use of `<framework src="com.google.android.gms:play-services-base:+" />` to specify the use of the latest version, and allow general compatibility with other addons.

**Comment by shortercode** [comment]
I've published the updated whitelist this morning, so it should now be possible to include the required cordova plugins. I'm going to close this issue now, as it's up to the gameanalytics developer to update their addon.

**Comment by the1schwartz** [comment]
We have updated our cordova plugin (cordova-plugin-gameanalytics) now. We have updated the google play dependency from "compile 'com.google.android.gms:play-services-base:12.0.1'" to "compile 'com.google.android.gms:play-services-ads-identifier:+'" as "compile 'com.google.android.gms:play-services-base:+" gave compile errors. Let us know if everything looks ok now.

**Comment by the1schwartz** [comment]
Sorry for the late update, most people have been on holidays until lately.

**Comment by shortercode** [comment]
No worries. In future if you want an updated version to be reviewed can you please file a new issue? We might miss it if you update an closed issue.

I've reviewed cordova-plugin-gameanalytics@2.0.0 and added it to the whitelist.
