### ISSUE TITLE
Editor: Dragging an Object from Project Bar ignores Snap to Grid

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1849]
## Problem description

Normally when "Snap to Grid" is enabled, dragging aroudn sprites snaps them to the grid, but when dragging an object from the project bar it does not snap.

## Steps to reproduce

1. Create an Object
2. Set "Snap to Grid"
3. Drag Object from Project bar

## Observed result

Does not snap.

## Expected result

Snaps.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
