### ISSUE TITLE
Copy paste sprite in editor on OSX

### ISSUE THREAD

**Issue by driesdriessen** [Scirra/Construct-3-bugs#185]
## Problem description
Copy/paste image from Keynote or Pixelmator to sprite editor does not work

## Attach a .c3p
It is not a problem in my project but a problem in the User Interface

## Steps to reproduce

1. Create drawing in Pixelmator or keynote
2. Copy to clipboard
3. In sprite editor in Construct3 paste the image

## Observed result
The image is not pasted. Nothing happens.

## Expected result
The image is pasted

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details
OSX 10.11.6
Chrome 57.0.2987.133 (64-bit)
Construct3 r23

**Comment by mOOnpunk** [comment]
So is this ever going to be fixed? At least have it work like c2 so it can still be done, even if transparency is lost.

**Comment by AshleyScirra** [comment]
I think @DiegoScirra can add support for pasting opaque images (apparently the alpha channel is lost - perhaps we want to file a Chrome bug for that). However for full support I think we are waiting on a new clipboard API to be introduced.

**Comment by AshleyScirra** [comment]
@DiegoScirra - isn't this supported in the desktop build now?

**Comment by dop2000** [comment]
I'm using Desktop build r85 from 12 Feb - copying/pasting with alpha still doesn't work. Only opaque images are pasted. 
Could you file a bug with Chrome? Most images in games require alpha channel and not being able to paste them directly from graphics editing software is a huge inconvenience..

**Comment by AshleyScirra** [comment]
The desktop build implements clipboard images with NW.js APIs. Something for Diego to check I think.

**Comment by AshleyScirra** [comment]
This has been supported for some time in the desktop build, and is now supported in the next release in the browser using the new async clipboard API, so closing.

**Comment by driesdriessen** [comment]
Wow, super! Thank you for the continuous stream of improvements!

Op 11 jun. 2019, om 19:27 heeft Ashley (Scirra) <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


This has been supported for some time in the desktop build, and is now supported in the next release in the browser using the new async clipboard API, so closing.
