### ISSUE TITLE
C3 Runtime BBCode Text: Cannot Escape [

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1850]
## Problem description

Setting Text with BBCode enabled to "[1]" (to show that this is a keyboard key) shows no text because of the BBCode.
If i try to escape the bracket like "\[1]" the text is shown but the escape slash is also shown.

(Don't know if this is a bug or there is another way of cancelling the opening bracket, but i did not find a documentation for this)

## Steps to reproduce

1. C3 Runtime, Add Text
2. Set text to "[1]"
3. Set text to "\[1]"

Result is the same if you do it in the editor or with Events. But when you write \ in the editor in a text, in the Properties tab Text field it shows that there is automatically another \ added (in the text field it's \\). This may have something to do with this.

## Observed result

\ escapes the bracket, but is visible.

## Expected result

\ escapes the bracket and is invisible.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release. The correct way to escape BBcode tags is to precede the [ with a backslash, and the backslash will be hidden as of the next release. To deliberately show `\[`, use a double backslash to escape the backslash, e.g. `\\[`.
