### ISSUE TITLE
Set Width of a Textbox to TextWidth: Spacing causes new lines

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#1851]
## Problem description

NOTE: I'm not sure if this is a bug or i'm doing something wrong but it appears strange to me so i thought i'd report.

When i set a text in a textbox and then set the WIDTH of the box to the content of the textbox, it only sets the width until the first space in a sentence.

EDIT: This also affects Spritefonts.

![image](https://user-images.githubusercontent.com/30116964/43233790-52bb42c6-9078-11e8-921f-6efec510ce09.png)
![image](https://user-images.githubusercontent.com/30116964/43233794-5a3a29b8-9078-11e8-8410-4a4db1a43ac9.png)

## Attach a .c3p

[text.zip](https://github.com/Scirra/Construct-3-bugs/files/2229950/text.zip)

## Steps to reproduce

1. Run project

## Observed result

Textbox Width is only set until first space between a word.

## Expected result

The textbox width to be set to the whole width of the content of a textbox.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r111 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 2 gb (13.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The text object is only 20px wide. So it does text layout for the string at that width, resulting in pretty much every word wrapping to a new line. Then you ask for the text width, so it tells you how wide the text is with a word on every line, which is about as wide as the first word. It's working correctly.

You probably meant to instead have the initial text instance very wide, so it sizes the text instance to the content. However note that the text layout engine requires a couple of pixels margin at the edges so will still wrap the last word unless you add a bit of extra width (try `Self.TextWidth + 4`).
