### ISSUE TITLE
[Construct 3 SDK][Safe Mode] Missing Files on the .c3addon causes even SafeMode to crash.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1852]
## Problem description

Missing Files can on the c3addon causes even SafeMode to crash.

## Attach a minimal project.

[drawingPlugin.zip](https://github.com/Scirra/Construct-3-bugs/files/2230241/drawingPlugin.zip)

## Steps to reproduce

1. Install the provided .c3addon.
2. Go to [(https://editor.construct.net)]. It will crash.
3. Go to [https://editor.construct.net/?safemode]. It will still crash.

## Observed result

Crash even in safe-mode.

## Expected result

For the safe-mode to be as fail-proof as possible.

## Note

Thank you in advance for looking into this.

**Comment by AshleyScirra** [comment]
You should use [developer mode](https://www.construct.net/make-games/manuals/addon-sdk/guide/using-developer-mode) so you can fix this type of problem easily before you package a .c3addon file. I fixed the case of a missing icon file crashing the editor in the next release anyway.
