### ISSUE TITLE
[C3 runtime] Tint effect glitch when rotating layer

### ISSUE THREAD

**Issue by neverk** [Scirra/Construct-3-bugs#1853]
## Problem description

Graphic glitches when using tint effect in tiled background and rotating layer.
[C3 tint bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2230907/C3.tint.bug.zip)

![tint-glitch](https://user-images.githubusercontent.com/6499334/43248352-49b3f96e-90c0-11e8-8334-1262bc96213b.gif)
The effect is applied to the red rectangle.

## Steps to reproduce

1. Add tiled background 
2. Add tint effect to the tiled background object
3. Rotate layer

## Observed result

Graphic glitches on the object. Doesn't work as supposed.

## Expected result

Tint should cover the object exactly 

## Affected browsers

* Chrome: yes
* Firefox: not tested 
* Edge: not tested
* Safari: yes

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
