### ISSUE TITLE
Editor: Copying a Layout with a Global Layer -> Layer should say "Global: Overridden" not "Global: Yes"

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1855]
## Problem description

When you duplicate a Layout with a global layer in it, the **Global Layer** of the copied Layout says **"Global: Yes"** instead of "Global: Overridden".

(Also the Global Layer is empty then, but that is the same bug probably. If you set "Global: No" in all the copied Layouts it will correctly say "Global: Overriden" and the Global Layer will correctly show objects.

Also "Overridden" is spelt wrong (it is spelled "Overriden" - double D is missing)

(Tested in latest release r111)
## Steps to reproduce

1. Create a Global Layer
2. Duplicate the Layout
3. Notices Global Layer in the copied Layout says "Global: Yes"

## Observed result

"Global: Yes"

## Expected result

"Global: Overridden"

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed in r114
