### ISSUE TITLE
[Build Service] White-list "cordova-plugin-inapppurchase".

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1858]
## Add a new Cordova Plugin to the Construct Build Service.
**Cordova Reference** :: "cordova-plugin-inapppurchase

The Construct 2 &3 plugin is available and will be released after the white-list. Thank You.

**Comment by shortercode** [comment]
Looks fine, I've added `cordova-plugin-inapppurchase@1.2.0` to the whitelist. As we whitelist specific versions of a plugin if you require a different version in future please file an issue for me to review that new version.
