### ISSUE TITLE
Not enough space allocated for iOS Safari running C3, trying to add an addon

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#1860]
## Steps to reproduce

1. Open C3,
2. Add a c3addon from Files.
3. Not allow

## Observed result

Couldn't add an addon.

## Expected result

Add an addon

## Affected browsers

* Safari: yes/no

## System details

11.4.1 iOS Safari iPhone X

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Safari has a very strict limit of 50MB storage per domain local storage; this includes the offline files for construct itself, browser project saves, addons and saved project exports. It fills up pretty quick unfortunately...

As a potential workaround I believe addons that are included with a project don't get loaded into local storage, so you should be able to load projects that include the addons they require.

**Comment by zumwaltwood** [comment]
I've tried adding an addon to my project on windows, save the project in Dropbox, the load the project in the iPad 12.9", but the plugin isn't available to the project on the tablet, only windows. Not sure how to work around this with safari

**Comment by AshleyScirra** [comment]
There is no way for us to work around storage limits in Safari. Apple need to change this.
