### ISSUE TITLE
(Stable R111 ) Reoccurring auto save message when auto save disabled.

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#1862]
## Problem description

I just updated to the latest stable R111 from the last stable release. I've always had backups disabled, but now i get a message every few minutes telling me "local save successful" along with the file name i have open. It doesn't appear to be actually saving or overwriting any files, it looks like its just a message.

## Attach a .c3p

n/a

## Steps to reproduce

nothing just updated c3.

## Observed result

pop up message

## Expected result

only get message when an actual save is performed.

## Affected browsers

* Chrome: yes

## System details

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.13_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r111 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 39 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Thanks for the report, I found a small typo ( "and" instead of "or" ) that seems to prevent autosave from being turned off. Little frustrating that it made it's way into the stable release but there's not much that can be done about it now. I've fixed it for the next beta release. In the meantime the best I can suggest is to change the autosave interval to 60 minutes, which is the maximum value.

**Comment by mOOnpunk** [comment]
So you're saying it is actually autosaving? This is bad. You should really push out a new stable release ASAP in that case.

**Comment by shortercode** [comment]
It should be yes. The autosave doesn't overwrite your project, it saves to a separate file. So I'd consider it a low severity bug. At worst it's creating some files you don't want. As I said you can turn the frequency down to once an hour, which should limit any impact this bug has.

It's frustrating that it slipped through but it's not worth pushing another release in my opinion.
