### ISSUE TITLE
[Build Service] White-list "cordova-plugin-inapppurchase-fixed".

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1864]
## Add a new Cordova Plugin to the Construct Build Service.
**Cordova Reference** :: "cordova-plugin-inapppurchase-fixed".

_This plugin doesn't support CLI 7.0.0_
https://github.com/Scirra/Construct-3-bugs/issues/1858
_As reported here:_
https://github.com/Scirra/Construct-3-bugs/issues/1863

"cordova-plugin-inapppurchase-fixed" supports CLI 8.0.0, to avoid build errors.

The Construct 2 &3 plugin is available and will be released after the white-list. Thank You.

**Comment by shortercode** [comment]
I've removed `cordova-plugin-inapppurchase@1.2.0` from the whitelist, if it has compatibility issues then it's not worth keeping on there. `cordova-plugin-inapppurchase-fixed@1.1.2` has been reviewed and added to the whitelist.
