### ISSUE TITLE
Export Android APK Build Fail Error (related to GooglePlay plugin?)

### ISSUE THREAD

**Issue by DGreen1up** [Scirra/Construct-3-bugs#1865]
## Problem description

Android APK build fails, others are having the same issue:

[Scirra Forum](https://www.construct.net/forum/construct-3/general-discussion-7/error-building-android-136674)

## Steps to reproduce

Steps I have taken (I cannot vouch for others with the same issue)
1. Select "Export"
2. Select "Android"
3. Select "Unsigned release APK"

## Observed result

Pop up states "Build Failed" (see link above)

## Expected result

An Android APK should be built

## Affected browsers

* Chrome: yes
* Firefox: unknown
* Edge: unknown
* Safari: unknown

## System details

(see the link above for build error details)

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r111 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 3.8 gb (24.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Please include a project that repeats the issue

**Comment by DGreen1up** [comment]
It does not affect all my projects. What would be the best way to provide the project without sharing a year and half's worth of assets and programming?

**Comment by DGreen1up** [comment]
I'm unable to attach a file larger than 10mb

Cordova Project Export Statistics:

Estimated download size: 30 mb.

Total script size without minifying is 947 kb (about 218 kb compressed)
Data file size is 515 kb (about 88 kb compressed)
Total image size without recompression is 7 mb
Image deduplication was not enabled
Total sounds size 527 kb, music size 21 mb
Approximately 1 mb app overhead
Overall estimated download size: 30 mb (excluding streamed audio: n/a)

This export took 1 second to complete.

**Comment by DGreen1up** [comment]
Tried attaching a .c3p, but Github does not support that file type?

Anyway, I think I found the issue. It seems to be related to the GooglePlay plugin. Removed just that and the project builds without errors.

**Comment by ChadoriRebornXD** [comment]
This situation might be similar to my case ::
https://github.com/Scirra/Construct-3-bugs/issues/1863

**It might not be the problem with the C3 runtime but the Cordova plugin doesn't support the CLI version 8.0.0..**
You will have no problem using Cocoon.IO though as it doesn't use the latest Cordova CLI version.
Although, you'll have problems with updated ones like the Construct 3 Build Service and Phonegap.

That's what I've gathered from my tests. Although, I could be wrong. But I just want to give my hypothesis on the matter as the error report is quite similar to mine.

**Comment by ChadoriRebornXD** [comment]
Also, The other way around will also get an error. Older Cordova Version supporting a newer Cordova Plugin will also result an error. 
So C3runtime is not supported at the moment with Cocoon.IO.

I also encountered it here, on this closed bug report of mine ::
https://github.com/Scirra/Construct-3-bugs/issues/1859

**My point, this maybe only a conflict between cordova plugin versions and cordova cli versions. Not the C3runtime.** Although I could be wrong, this is just based on my tests.

**Comment by ChadoriRebornXD** [comment]
My solution was to reference an updated version of the Cordova Plugin that will be compatible with the CLI 8.0.0.
Here : https://github.com/Scirra/Construct-3-bugs/issues/1864

**Comment by shortercode** [comment]
I'm fairly sure the issue was just a typo I introduced in the plugin, I've reverted the whitelist to not allow  `construct-play-games@1.0.10`. So it will fallback to 1.0.9, which does compile correctly.

I'll do some more testing and hopefully re-release a fixed version of 1.0.10 later today.
