### ISSUE TITLE
Frustrating "failed to export" error

### ISSUE THREAD

**Issue by Jayed2016** [Scirra/Construct-3-bugs#1866]
## Problem description 

Every time I open a previous saved .c3p file and make some tiny changes, then try to export to HTML5 I get "Failed to export" error, although I was able to export the very earlier version of that file and I know I've done nothing wrong but changing some pieces of codes. Never faced this kind of issue in C2 but in Construct 3 its very frequent problem. In the windows beta version during the export it just runs in continuous loop. 

## Attach a .c3p
[Battugattu_1_6.zip](https://github.com/Scirra/Construct-3-bugs/files/2238198/Battugattu_1_6.zip)

## Steps to reproduce

1. open the project
2. Try to export to HTML5
3.

## Observed result

"Failed to export"

## Expected result

Perfectly exports to a HTML5 folder

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Jayed2016** [comment]
Now I'm getting a constant error on the desktop version. 
And if I try the web version the project exports but exports as a broken file which can't be viewed. :(

**Comment by shortercode** [comment]
When you file a bug can you please provide the system details, it makes it easier to find out where the problem lays.

I haven't been able to reproduce this issue in release r111 in chrome,  I can export correctly and the exported file works the same as the preview version.
