### ISSUE TITLE
Mobile Advert ads not loading iOS

### ISSUE THREAD

**Issue by theBdrive** [Scirra/Construct-3-bugs#1867]
## Problem description

Mobile Advert plugin will display test ads fine on iOS, but when test mode is turned off, both reward and interstitial ads fail to load.

## Attach a .c3p

Make a blank project with Mobile Advert plugin added

## Steps to reproduce

1. Configure your Mobile Advert plugin
2. Try to load reward or interstitial ad

## Observed result

Neither reward or interstial ads load so they are unable to be displayed. Xcode shows reward and interstitial ads both failed to load in console. Mobile Advert was working previously with r104 and r109, but now not even r109 loads the ads.

## Expected result

Reward and interstitial ads are loaded and can be displayed in game.

**Comment by Bootfit** [comment]
Hello folks - any progress on this? I’ve got the same issue.

**Comment by shortercode** [comment]
@Bootfit looking at it today.

**Comment by Bootfit** [comment]
Great 👍

So is this sorted now?

**Comment by Bootfit** [comment]
Any news on this folks?

**Comment by Bootfit** [comment]
Been working on this over the weekend on my app - I've got it set up so if MobileAdvert fails to configure or MobileAdvert fails to load (using 'on configuration failed' and 'on banner failed to load') then text boxes appear indicating which.

Both text boxes appear meaning that MobileAdvert fails to configure on iOS and so the banner fails to load.

So the initial issue is getting the banners to configure on iOS.

**Comment by theBdrive** [comment]
@Bootfit MobileAdvert>Is Configured is always returning true for me, but interstitial and reward are failing to load.

**Comment by shortercode** [comment]
Just as a word of warning, if your not already aware:

> It is important to enable test ads during development so that you can click on them without charging Google advertisers. If you click on too many ads without being in test mode, you risk your account being flagged for invalid activity.

I'm still looking into this issue, it's not 100% clear why this has stopped working at the moment.

**Comment by Bootfit** [comment]
Any update on this or the GDPR popup on iOS?

**Comment by AshleyScirra** [comment]
@shortercode should this be working as of r114?

**Comment by theBdrive** [comment]
@AshleyScirra @shortercode Interstitial ads now load and display fine, but reward ads are still failing to load in r114.

**Comment by Bootfit** [comment]
@theBdrive - have you managed to get footer banners working? If so can you post a screengrab of your event sheet where they appear?

**Comment by theBdrive** [comment]
@Bootfit I don't use banners in any of my games.

**Comment by Bootfit** [comment]
Folks - don't know if this will help at all, but I've just managed to get both footer banners and interstitials to appear on iOS.

Set up your App ID, Publisher ID etc in the MobileAdvert properties. On start up **configure** your ads and then **create** them wherever you need them within your app.

But the issue that prevents the banners appearing is in the phone itself.
In your iPhone go to Settings > Privacy > Advertising > Limit Ad Tracking - turn this to OFF.

Your ads should load now.

I've not tried this with rewarded ads though.

**Comment by shortercode** [comment]
@theBdrive what is the current status of this? I saw you'd managed to get some videos to show in the GDPR thread.

**Comment by theBdrive** [comment]
@shortercode I do have interstitial ads and rewards ads working, but I had an issue with reward ads failing to load about 50% of the time. I load ads on my splash screen with MobileAdvert>Is Configured>Create ad etc, this is where the rewards ads randomly fail. I started adding another check on all the layouts that can display reward ads, MobileAdvert>Is Video Loaded(Invert)>Create reward ad and ads load 100% of the time. Not sure why I get the reward ads failing randomly on Is Configured, because interstitials load 100% of the time on Is Configured.

**Comment by shortercode** [comment]
Okay thanks for the update, I'm not sure what the issue is. My current guess is setup related but it could just as easily be something else. Do you have an event for the `on video failed to load` condition? It would be useful to know what the error message is.

**Comment by shortercode** [comment]
@theBdrive have you looked into that error message yet?

**Comment by shortercode** [comment]
closing as abandoned.
