### ISSUE TITLE
.c3p file does not open and shows error

### ISSUE THREAD

**Issue by Adhebro** [Scirra/Construct-3-bugs#1868]
## Problem description

Error report information
Type: unhandled rejection
Reason: Error: missing file path 'project.c3proj' @ Error: missing file path 'project.c3proj' at ǃI.ǃILc.ǃrLt (https://editor.construct.net/r111/main.js:80:53385) at Function.ǃIll (https://editor.construct.net/r111/main.js:80:92680) at window.ǃExz.ǃEAH (https://editor.construct.net/r111/main.js:174:66607)
Stack: Error: missing file path 'project.c3proj' at ǃI.ǃILc.ǃrLt (https://editor.construct.net/r111/main.js:80:53385) at Function.ǃIll (https://editor.construct.net/r111/main.js:80:92680) at window.ǃExz.ǃEAH (https://editor.construct.net/r111/main.js:174:66607)
Construct 3 version: r111
URL: https://editor.construct.net/
Date: Sun Jul 29 2018 18:08:31 GMT+0530 (India Standard Time)
Uptime: 1547 s

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r111 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Steps to reproduce

1. open .c3p file
2.
3.

## Observed result

 error

## Expected result

 open .c3p file

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

</details>

**Comment by Adhebro** [comment]
[game.zip](https://github.com/Scirra/Construct-3-bugs/files/2238791/game.zip)

**Comment by shortercode** [comment]
The file you've sent me is not a c3p file, it's a capx. Are you renaming it to a c3p to try and open it?

I haven't been able to reproduce the crash you've submitted, please can you fill in the reproduction steps in the report. Particularly how you are opening the file, and what extension the file has when you open it.

**Comment by Adhebro** [comment]
please help me how can i convert a CAPX file into

**Comment by shortercode** [comment]
If you have a file that's a capx, with the correct extension, you can just open it in construct. It will automatically convert it to the C3 project format when it's opened. You will only be able to save as a C3P file though.

**Comment by Adhebro** [comment]
To open it in construct, it says to download a plugin called "LITE TWEEN". I had downloaded the lite tween but it doesn't work. So plz help me how can i come out of it

**Comment by Adhebro** [comment]
To open the capx file in construct 2 or 3 , it says to download a plugin called "LITE TWEEN" by Lunarry. I had downloaded the lite tween but it doesn't work. So plz help me how can i come out of it
