### ISSUE TITLE
 Problems with language selection

### ISSUE THREAD

**Issue by dimielannes** [Scirra/Construct-3-bugs#1869]
I am Brazilian but I prefer to use C3 in English, after the last update, when I open C3 the language automatically comes in Portuguese, I make the change in the configuration and restart the C3 and the language change to English but I have to do it always when i start the C3.

**Comment by AshleyScirra** [comment]
Can't reproduce here, Construct appears to correctly remember the language setting. Please follow all the bug report guidelines otherwise we cannot help.
