### ISSUE TITLE
(R26) Beta open for jam, Faults with lights.

### ISSUE THREAD

**Issue by Mataguiris** [Scirra/Construct-3-bugs#187]
## Problem description

ShadowLight Does not change color.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Observed result

No matter what color I choose in shadows, they always appear black.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
The example 'Shadows - blending multiple lights' appears correctly. With no other information, closing as it appears to be working.
