### ISSUE TITLE
[Firefox] Dimming focused window.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1874]
## Problem description

Graphical bug when editing expressions etc. Expression editor and other popups gets dimmed along with the background.

## Attach a .c3p

N/A
Any project will do.

## Steps to reproduce

1. Open any project in firefox.
2. go to event sheet and edit an expression.
3. Expression editor window is dimmed along with the background.

## Observed result

Everything get dimmed

## Expected result

Only background should get dimmed.

## Affected browsers

* Chrome: no
* Firefox: yes/
* Edge: no

**Comment by tunepunk** [comment]
Was using latest stable in firefox on windows 10. Can check again tonight if the problem is still there. Persisted even if I restarted firefox/construct.

**Comment by tunepunk** [comment]
Clearing cache and app data didn't help. Did a complete firefox refresh, and now it's back to normal. Must have been some strange firefox bug.

**Comment by shortercode** [comment]
I think I found the issue, if you enable the experimental "dom.dialog_element.enabled" flag then the whole screen is dimmed. Chrome is the only browser that supports the dialog element at the moment, we use a polyfill for all the others.

I expect it's a bug with firefox's dialog implementation.

**Comment by shortercode** [comment]
From reading up on the firefox meta bug for this feature somebody wrote the simple bit and nobody wants to write the hard bit. It's been open for 6 years, and hasn't seen much movement for 2 so I'd just recommend to keep that flag disabled :P

**Comment by tunepunk** [comment]
Yeah that might be it.. I often try out some flags to see what they do. So I might have flipped that one at some point and then encountered this in Construct. I'll keep this flag at default then, until firefox fully support it at some point.

**Comment by shortercode** [comment]
Hopefully they will get around to implementing it at some point, it's a useful feature.
