### ISSUE TITLE
Firefox does not linebreak long expressions.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1876]
## Problem description

When using long expressions in firefox they do not linebreak and continue past the popup window.

## Attach a .c3p

N/A

## Steps to reproduce

1. Write a long expression in firefox.

## Observed result

Expression does not linebreak.

## Expected result

Should linebreak.

## Affected browsers

* Firefox: yes

**Comment by shortercode** [comment]
Does your expression contain any spaces? The only way I could get it to continue past the end of the input box was to input a length of text wider than the input with no spaces.

**Comment by tunepunk** [comment]
Yes i used spaces. I had several firefox bugs yesterday but I might try completely clearing cache etc and see if the problems persist. Construct was unusually wonky, so I'll check if clearing app data and cache helps.

**Comment by shortercode** [comment]
Yeah it does seem a little odd...

Anyway I've made some changes anyway to allow expressions to line break between tokens ( not letters ) even if there's no space between them. Might come in handy for those who prefer not to use spaces.

For the record I'm testing with Firefox 61.0.1 ( up to date according to it's updater ) and construct r111.

**Comment by shortercode** [comment]
All good then, thanks for the report :)

**Comment by AshleyScirra** [comment]
Note the fix for this caused #2024 so the implementation has been changed for r117.
