### ISSUE TITLE
[C3 Editor] Mouse Wheel Scroll doesn't work when adding an Object to Family.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1877]
## Problem description

On the C3 Editor, the **Mouse Wheel Scroll doesn't work** on the **Family List : Context Menu** when adding an Object to a Family. 

## Minimal Project Sample

[Bug Report.zip](https://github.com/Scirra/Construct-3-bugs/files/2244158/Bug.Report.zip)

## Steps to reproduce

1. On the Project Bar. **Right-Click** the **AddToFamily** object.
2. On the **Context Menu** Hover to the **Add To Family** Drop-Down option.
3. This shows the **Family List**. Hover to the list.
4. And attempt to **MouseWheel :: Scroll Up/Down.**

## Observed result

Can't Scroll using the _Mouse Wheel_.

## Expected result

Should be able to scroll using the _Mouse Wheel_.

## System details

- Desktop Build :: r111 Stable. [**Jun 19 2018: updated to Chrome 67**]
- Construct 3 :: r111 Stable. [Browser Build]

## Note

Thank you in advance for looking into this.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed for next release.
