### ISSUE TITLE
line of site not working on runtime 3

### ISSUE THREAD

**Issue by dolomite** [Scirra/Construct-3-bugs#1879]
## Problem description

The Line of Site behavior is not properly working on C3 runtime 3. However, when set back to runtime 2 it works correctly again.

## Attach a .c3p
[line_of_site_test.zip](https://github.com/Scirra/Construct-3-bugs/files/2246488/line_of_site_test.zip)

## Steps to reproduce

1. Project is currently set to runtime 3
2. Move the green object (player) to jump past the block barrier to approach the red object (enemy). When the player is past the block barrier and is in the line of site of the red object (enemy), the enemy should start rotating. In runtime 3, it constantly rotates even when the player is still behind the block.
3. Set the project to runtime 2.
4. The red enemy will not rotate until the player is in correctly in the line of site.  

## Observed result

In runtime 3, the red object constantly sees the green object even past the block barrier.

## Expected result

The red object should not see the player until he is past the block barrier.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 61.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2.5
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
C3 release: r111 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 9.8 mb (0.5%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    UI animations are disabled in Firefox 62 and older due to bug 1354501
    ImageBitmap support is disabled in Firefox due to bug 1472194
    CSS containment is not supported. Editor performance may be significantly degraded.
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmap is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
