### ISSUE TITLE
Pasting play audio with missing file gives error instead of cannot paste popup

### ISSUE THREAD

**Issue by Unentokku** [Scirra/Construct-3-bugs#188]
## Problem description

Pasting play audio action using a file not in the project isn't handled

## Attach a .c3p

[test.c3p.txt](https://github.com/Scirra/Construct-3-bugs/files/999868/test.c3p.txt)

## Steps to reproduce

1. Copy the (only) action playing an audio file
2. Paste it to another project with audio object but not the file or just delete the file before pasting the action back.

## Observed result

Error report

## Expected result

The "Cannot paste" dialogue box saying the name of the missing file.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r26/main.js, line 2, col 229389
Message: Uncaught TypeError: Cannot read property 'ǃiz' of null
Stack: TypeError: Cannot read property 'ǃiz' of null at Function.ǃab (https://editor.construct.net/r26/components/editors/eventSheetView/eventSheetView.js:1:78616) at t.ǃwV (https://editor.construct.net/r26/components/editors/eventSheetView/eventSheetView.js:1:78511) at new t (https://editor.construct.net/r26/components/editors/eventSheetView/eventSheetView.js:1:78475) at Function.ǃN.ǃH (https://editor.construct.net/r26/main.js:2:229365) at window.ǃaT.ǃPM (https://editor.construct.net/r26/main.js:61:331489) at t.ǃ_L (https://editor.construct.net/r26/components/editors/eventSheetView/eventSheetView.js:1:69188) at t.ǃ_l (https://editor.construct.net/r26/components/editors/eventSheetView/eventSheetView.js:1:69100) at t.ǃ_w (https://editor.construct.net/r26/components/editors/eventSheetView/eventSheetView.js:1:68993) at new t (https://editor.construct.net/r26/components/editors/eventSheetView/eventSheetView.js:1:73915) at Function.ǃN.ǃH (https://editor.construct.net/r26/main.js:2:229365)
Construct 3 version: r26
URL: https://editor.construct.net/index.html
Date: Mon May 15 2017 03:44:27 GMT+0300 (FLE Daylight Time)
Uptime: 592.4 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.96
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 6670 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for r28.
