### ISSUE TITLE
expression editor quotes within quotes not allowed?

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#1880]
## Problem description

The expression editor will not allow quotation marks within quotations. Dont know if its by design but if you want to add text with a word in quotes to a sting variable it won't allow it. It says expression has ended already.

## Attach a .c3p

n/a

## Observed result

Example set string variable to "hello, you can call me "Bob". "

## Expected result

should allow it in text.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by tunepunk** [comment]
You have to to put double quotes on the word you want to have quoted, so this should work. 

"hello you can call me ""Bob""."

**Comment by shortercode** [comment]
Using quotes within strings is complicated in most programming languages, as it's ambiguous where strings start and stop. As tunepunk says we treat 2 double quote marks as an escaped double quote mark, that means it's ignored when the expression is trying to decide if that character counts as the start or end of a string.
