### ISSUE TITLE
Windows store Build of construct 3 crashes on preview

### ISSUE THREAD

**Issue by eleanorjmorel** [Scirra/Construct-3-bugs#1882]
## Problem description

Windows store Build of construct 3 crashes on preview
## Attach a .c3p

https://puu.sh/B7f3e/7cd3c75e91.c3p

## Steps to reproduce

1. preview any project

## Observed result

![image](https://user-images.githubusercontent.com/32940085/43562305-d2e38794-95e9-11e8-90e6-32ee757caef0.png)

## Expected result

a preview of the project

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r111/exporters/preview/exporter.js, line 1, col 981
Message: Not implemented 
Stack: Error: Not implemented at Global code (https://editor.construct.net/r111/exporters/preview/exporter.js:1:981)
Construct 3 version: r111
URL: https://editor.construct.net/
Date: Thu Aug 02 2018 00:19:19 GMT-0400 (Eastern Daylight Time)
Uptime: 620.2 s 
Platform information
Browser: Edge
Browser version: 17.17134
Browser engine: Edge
Browser architecture: 64-bit
Context: windows-store
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; MSAppHost/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
C3 release: r111 (stable)
Language setting: en-US 
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Microsoft
Renderer: ANGLE (Microsoft Basic Render Driver Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: yes
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: WEBGL_compressed_texture_s3tc, OES_texture_float, OES_texture_float_linear, EXT_texture_filter_anisotropic, OES_standard_derivatives, ANGLE_instanced_arrays, OES_element_index_uint, WEBGL_debug_renderer_info, WEBGL_depth_texture, EXT_frag_depth, OES_texture_half_float, OES_texture_half_float_linear, WEBGL_lose_context, OES_vertex_array_object, WEBGL_draw_buffers, EXT_blend_minmax, EXT_shader_texture_lod, EXT_color_buffer_half_float, WEBGL_color_buffer_float

</details>

**Comment by shortercode** [comment]
I think this is possible the same as #957. I'm unable to reproduce the bug myself and looking at the error it seems to be coming from some browser feature not from our code. Looking around the only search result on google for it is that bug report.

Are you running an N version of windows? If so you should try install the media feature pack.

**Comment by eleanorawesome** [comment]
I am running an N version of windows, and I've reinstalled windows because the media feature pack is not compatible with the windows mixed reality in the Aprils update so I could not update windows to get the windows store version of construct 3 because it said I required a newer version of windows. 

Dang looks like I'm screwed and it was all for nothing.
