### ISSUE TITLE
[C3 Editor] The Tilemap Load Dialog has problems with both the Light and Dark Themes.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1884]
## Problem description

On the C3 Editor, both Browser and Desktop builds have problems with the **Tilmap Load .tmx :: Dialog** using either the Dark or Light Theme.

## Minimal Sample Project

For complying with the guidelines sake, here is the sample project.
[BugReport-Tilemap Editor.zip](https://github.com/Scirra/Construct-3-bugs/files/2252631/BugReport-Tilemap.Editor.zip)

## Steps to reproduce

1. Open Construct 3, either using the Browser or Desktop Build.
2. Select the '**Dark**' or '**Light**' theme.
3. Show the **Tilemap Bar**.
4. Click on the **Load Tilemap(.tmx)** to open the **Load Tilemap Dialog**.
5. Observe results.

## Observed result

**Default Theme**
![bugreport_tilemap_default](https://user-images.githubusercontent.com/31282960/43570758-af6f463e-966d-11e8-8528-4fb827fe10a0.png)

**Light Theme**
![bugreport_tilemap_light](https://user-images.githubusercontent.com/31282960/43570767-b56c3b96-966d-11e8-9279-fcb0283563a3.png)

**Dark Theme**
![bugreport_tilemap_dark](https://user-images.githubusercontent.com/31282960/43570782-bde635a6-966d-11e8-9bb0-1d09742533dc.png)

## Expected result

For the **Load Tilemap Dialog** to support all kinds of Construct 3 themes.

## System details

1. Construct 3 : Browser Build :: r111 (Stable)
2. Construct 3 : Desktop Build :: r111 (Stable) [**Jun 19 2018: updated to Chrome 67**]

## Note
Thank you in advance for looking into this.

**Comment by Animmaniac** [comment]
@shortercode 

There's a `#loadTilemapDialog:before` pseudo element with a blue background and 0 opacity that interferes with a workaround I used to support floating panels with no borders and round corners.

Is this pseudo element used for something or it's just debug code?

**Comment by AshleyScirra** [comment]
Assigning to Diego to check the styles. Perhaps there is something unusual/non-standard about that dialog's styles that interferes with themes.

**Comment by DiegoScirra** [comment]
Changed the HTML so that it doesn't use the pseudo element anymore, and it looks like ti is working fine now.

Check it out in r114.
