### ISSUE TITLE
Sprite editor zoom issue using touchpad.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1885]
## Problem description

I'm not sure if this counts as a bug, feature request or C2 compatibility issue.

When opening sprite editor, on a laptop with touchpad. It would be great if it could be zoomed in the same way that you can navigate the layout with a laptop touchpad. 

It supports scroll, only when scroll bars are present, but not zoom.

For Reference use a laptop with a touchpad in the layout view. Use 2 finger functions to zoom. Very nice and handy.

## Attach a .c3p

N/A

## Steps to reproduce

1. Create a new sprite.
2. While in the sprite editor, try zoom in the sprite editor.

## Observed result

Sprite editor doesn't support any kind of regular touchpad navigation. Currently it only supports Middle mouse for navigation, and ctrl+mousewheel for zooming, and panning using touchpad only if the scrollbars are present.

## Expected result

Would be great if it would have the same functionality as the layout view, where you can zoom using 2 finger pinch.

## Affected browsers

* Chrome: yes

**Comment by shortercode** [comment]
I'd go with enhancement, but then I don't know what the C2 behaviour was in this case. Assigning to @DiegoScirra to take a look.

**Comment by TheBl4ckSh33p** [comment]
Zooming works for me with touch but it's very "blocky" not smooth. I use surface tablet to work and improved TouchPad controls would be nice. 👍

**Comment by DiegoScirra** [comment]
Will be available in the next beta.
