### ISSUE TITLE
C3 bullet behavior lower peformance compared to C2

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1887]
## Problem description

I read some forum post and saw some behavior issue: https://www.construct.net/ee/forum/construct-3/general-discussion-7/c2-c3-runtime-stress-test-136713

Replicated it with my own test, and was getting almost double the sprite count with C2 runtime then C3 runtime. Test uses 3 behaviors: bullet, fade and sine, mainly fade and bullet. Testing Fade and sine seperatly shows massive C3 runtime peformance gain. And bullet in C3 is a bit lower then C2. But using fade and bullet on sprite will mess something up badly. Same as forum test, it is something to do with bullet behavior i think.
There could have been some code regression at some point. Or my bad events, that somehow breake it.

## Attach a .c3p

[BulletBehaviorTest.zip](https://github.com/Scirra/Construct-3-bugs/files/2258129/BulletBehaviorTest.zip)

## Steps to reproduce

1.Preview  example, tap to add sprites, let it settle and try to get FPS around 30
2.Change runtime to C3, try to get fps around ~30.(on my pc I get C3 runtime ~5k sprites vs ~10k sprites on C2 runtime) 

## Observed result

Using some behaviors together make C3 runtime peformance much lower then C2.

## Expected result

C3 having much better peformance on fade and sine, but just little lower bullet peformance, but compined peformance should be better then C2 runtime. But it isen't.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.75
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36
C3 release: r111 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 416 mb (3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This turned out to be pretty complicated - it's slower due to having some compatibility code to match exactly the behavior processing the C2 runtime does, but I managed to find a way to make that compatibility code much more efficient. The provided project is now faster with the C3 runtime, so this should be fixed in the next release.
