### ISSUE TITLE
"Mirrored" reset when changing object size

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1888]
## Problem description

I'm trying to make my player a bit more "juicy" when jumping, but it seems like everytime i try to change the player size to create this "juicy" feel the "mirrored" function reset itself.

## Attach a .c3p

[Mirror Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2259032/Mirror.Bug.zip)

## Steps to reproduce

1. Move to the left to mirror the player
2. Jump

## Observed result

The player mirrored function is resetting.

## Expected result

The mirrored function to not reset.

## Affected browsers

* Chrome: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
"Set Mirrored" is implemented as "Set width to -width". So when you later set the size to a positive width, it overrides the mirroring.
