### ISSUE TITLE
Files don't have the correct mime type

### ISSUE THREAD

**Issue by Keevle** [Scirra/Construct-3-bugs#1890]
## Problem description
If I added any js files to my project and try and access them outside of the ajax plugin there mime type is set to "text/html"
## Steps to reproduce
1.Create a blank project then add the browser plugin
2. Either import or create a new .js file 
3. Use the browser plugin to execute this js code
```
"var js = document.createElement('script');
js.type = 'text/javascript'; 
js.src = 'yourfile.js';
document.body.appendChild(js);
window.libraryLoaded = false;
js.onreadystatechange = js.onload = function()
{
libraryLoaded=true;
};"
```

## Observed result
 Refused to execute script from 'https://preview.construct.net/yourfile.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

## Expected result

The ability to use the js file

## Affected browsers

* Chrome: yes
* Firefox: Na
* Edge: Na
* Safari: Na

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
As a quick warning "onreadystatechange" != "onload". It can fire multiple times during a request, you need to check the readystate value in the request to check it's the value you want [MDN XMLHttpRequest#readystate](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readyState).

I know the replication is fairly simple but could you provide an example project for us to test, thanks.

**Comment by AshleyScirra** [comment]
You request a relative URL, which in preview mode loads https://preview.construct.net/yourfile.js. Look at that URL. Click on it. It returns 404 not found, which is a HTML document. Your code loads a nonexistent script.

**Comment by Keevle** [comment]
@AshleyScirra That was just an example,I'll upload an example proj

**Comment by Keevle** [comment]
Is there no direct route to access project files from within preview?

**Comment by AshleyScirra** [comment]
Yes, using the addon SDK: https://www.construct.net/make-games/manuals/addon-sdk
Local project files don't have a web-hosted URL, because they are stored locally. They need to be handled differently. You should be using addons for any non-trivial JS code anyway.
