### ISSUE TITLE
[Smart Check Issue] Construct 3 : Global Variable to Local Variable, doesn't check for global events conflicts.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1891]
## Problem description

There is some smart checking issue when changing a global variable into a local variable by dragging it into a group. It fails to warn users that changing the scope of a target variable will result into a conflict with other events. Hence, removing them.

## Minimal Sample Project

[IssueReport.zip](https://github.com/Scirra/Construct-3-bugs/files/2259769/IssueReport.zip)

## Steps to reproduce

1. Drag the 'Variable 1' into one of the groups.
2. Observe as the other events are removed without warning.

## Observed result

There aren't any smart checking for that mentioned situation.

## Expected result

There should be a smart check for that situation.

## System details

Construct 3 r111 **[Stable Release]**

**Comment by AshleyScirra** [comment]
C2 has a notification so marking as C2 compat

**Comment by AshleyScirra** [comment]
Fixed for next release.
