### ISSUE TITLE
[C3Runtime] Remote preview results in a permanent black screen

### ISSUE THREAD

**Issue by Keevle** [Scirra/Construct-3-bugs#1892]
## Problem description

Whenever you're using remote preview and you switch to another tab before the scripts get loaded when you switch back to the game tab you get a permanent black screen, When the same project is run on the C2runtime the user can leave the preview tab(sometimes it takes a bit for things to load) and come back to the same preview tab and see a black screen for a moment before the game loads
## Steps to reproduce

1.Grab one of the example templates
2. Start a remote preview
3.Go to the remote preview link and switch tabs before the game gets loaded
4.Go back into the ide and switch the runtime to c3 and repeat step 3

## Observed result
Permanent black screen 

## Expected result

The preview works perfectly 

## Affected browsers

* Chrome: yes
* Firefox: Na
* Edge: Na
* Safari: Na

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.
