### ISSUE TITLE
Mute is not working

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1893]
## Problem description

The "mute" function in the "audio" plugin is not working. When you mute a tag you can still play any sound with that same tag, even if you try to mute the tag every tick it's still possible to hear some "artifacts", which is definitely not right.

## Attach a .c3p

[Mute Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2259956/Mute.Bug.zip)

## Steps to reproduce

1. Press the "play sound" button to hear the bip
2. Press the "mute tag" button to mute the tag
3. Press the "play sound" button to hear the bip again
4. Check the "mute tag" checkbox to mute the tag every tick
5. Press the "play sound" button to hear the bip again (only sound artifacts)

## Observed result

The mute function doesn't really mute the tag.

## Expected result

The mute function to completely mute the tag"

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. "Set muted" only affects currently playing audio. If you mute a tag every tick, then it will have about 16ms of playback between the click event and the next tick which mutes it.

**Comment by BonzerKitten7** [comment]
Oh, that's sad, look like i'll need to make a few more changes on my project before release. Thanks for the explanation, Ashley!
