### ISSUE TITLE
Animations Editor: [data loss] Construct doesn't accept input after interacting with the Animations and Frames panels

### ISSUE THREAD

**Issue by KelseyHigham** [Scirra/Construct-3-bugs#1896]
## Problem description

In the Animation Editor, on iOS Safari, if you open the right sidebar and interact with the Animations or Frames panels, it's possible for the entire screen to become unresponsive to touches.

This makes it impossible to save, which results in data loss. 

## Attach a .c3p

N/A

## Steps to reproduce

This bug can be encountered in a few different ways.

1. Open Construct 3 on iPhone Safari. Create a project and add a sprite
2. Swipe open the right sidebar to access the Animations or Frames panel
3. Performing any of the following actions will result in an unresponsive screen:

**Animations panel**
- Add a subfolder, then select an animation
- Add an animation
- Duplicate the current animation

**Frames panel**
- Add a frame, then select either frame
- Duplicate the current frame
- Duplicate the last frame

## Observed result

The editor becomes unresponsive to touches; the only way to interact with it is to forcibly close and reopening it, resulting in data loss

## Expected result

The editor should stay responsive to touches

## Affected browsers

* Chrome for Android: can't test
* Firefox: no
* Edge: no
* Safari for Mac: no
* Safari for iPhone: yes

## System details

<details><summary>View details</summary>

Here's the platform details for r104, but the same thing happens in r111

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: webapp
Operating system: iOS
Operating system version: 11.4
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r104 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A9 GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by DiegoScirra** [comment]
Fixed in r114.

The behavior should be consistent now. The main UI is locked while there are side panels showing, and is unlocked as soon as all the panels are hidden again.
