### ISSUE TITLE
Problem with trasmit json as multiplayer message

### ISSUE THREAD

**Issue by mgsoftwaring** [Scirra/Construct-3-bugs#1899]
## Problem description

I must update 3 arrays in multiplayer game. I use a broadcast message on host wich have as meggage myarray.asJson
On peer side I have on peer message the array load Multiplayer.message
The array don't udate and on the contrary, instead this array udates when Host go out
On the contrary I close tha peer on tha host appears thi msasge

"Javascript error!
RangeError: offset is outside the bounds of the DataView
https://editor.construct.net/r111/plugins/multiplayer/c2runtime/c2mp-net.js, line 306 (col 3)

This may be a bug in Construct 3 or a third party plugin or behavior - please report it to the developer following the bug report guidelines. Subsequent errors will be logged to the console."

## Attach a .c3p

It's impossible to send you tha cp3 file tah is 245 MB and I removed everything that was not necessary.If I reduce the project in the future you will not be able to make it work and check what's wrong
if you want to take note of the problem it would help me because I'm still. 

## Steps to reproduce

1.
2.
3.

## Observed result

Tha array non upates on multiplayer peer

## Expected result

Tha the array updates on peer

## Affected browsers

* Chrome: no
* Firefox: yes/
* Edge: no
* Safari: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to investigate reports that do not follow the guidelines. Please see the FAQ which explains what to do if you don't want to/can't share your project.
