### ISSUE TITLE
[R16] Edition JSON array file does not reflect without closing the tab - Unexpected line jump

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#19]
When you edit values in the array editor of a JSON project file, edited values don't update without closing the tab of the array editor.
Not really a bug, perhaps more a "feature request", but could edited values be taken into account without closing the tab (perhaps a button "update" to add in the interface).

Moreover a kind of bug: adding and deleting line jump when editing a value does not seem to be taken into account. (see reproduction steps)

## Attach a .c3p

https://www.kyatric.com/c3/bugs/2017-04-06-Array_JSON_Edit.c3p

## Steps to reproduce

consider the provided file.
Try to edit one of the cells (possibly x0, y1) and press return at the end (adding a jump line) and press backspace to "delete" the jumpline.
Close the tab to "validate" the edit.
Execute the program.

## Observed result
See how the text is still displaying a line jump despite it being meant to have been deleted and not appear anymore.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 2.3 gb
Storage usage (approx): 260 mb (10.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 560 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Fixed, was surprisingly just an edge case when files were requested as URLs instead of blobs
