### ISSUE TITLE
Uncaught TypeError: cannot read property 'nid' of null

### ISSUE THREAD

**Issue by esowe** [Scirra/Construct-3-bugs#1901]
## Problem description

This error occurs for the Construct 2 runtime only. I haven't been able to reproduce it for the Construct 3 runtime.

## Attach a .c3p

[Multiplayer TypeError.zip](https://github.com/Scirra/Construct-3-bugs/files/2264176/Multiplayer.TypeError.zip)

## Steps to reproduce

1. Open a remote preview of the project and copy the remote preview URL.
2. Open a new window in Google Chrome.
3. Paste the remote preview URL in the tab and open it.
4. Open two more tabs in Google Chrome and repeat step 3 for both tabs.
5. Go to the first tab and wait until it has connected to the signalling server.
6. When the topmost button changes text to "Online - Login", push it. This tab will then become the host.
7. Change to the second tab and repeat steps five and six above. This tab will then become the first peer.
8. Go back to the first tab and press "Lock game". This will immediately kick any new peer that tries to connect.
9. Go to the third tab and repeat steps five and six above.

## Observed result
 The following error appears:
Uncaught TypeError: Cannot read property 'nid' of null
    at Peer.onOpen (blob:https://preview.construct.net/985a552d-3b30-4b40-ab95-72c5b21754bb:291:24)
    at Peer.maybeFireOpen (blob:https://preview.construct.net/985a552d-3b30-4b40-ab95-72c5b21754bb:268:9)
    at RTCDataChannel.dc.onopen (blob:https://preview.construct.net/985a552d-3b30-4b40-ab95-72c5b21754bb:97:9)

## Expected result

There should be no type error.

## Affected browsers

* Chrome: yes
* Firefox: unknown
* Edge: unknown
* Safari: unknown

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r111 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 32 gb
Storage usage (approx): 164 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here. It's not clear from the description which tab has the error, but after following all the steps none of the three tabs have any error logged. Did you miss a step?

**Comment by esowe** [comment]
It happens here every time I try it. Here are the steps that I use to reproduce it (I have made some of them clearer):
 
1. Open a remote preview of the project and copy the remote preview URL.
2. Open a new window in Google Chrome.
3. Paste the remote preview URL in the tab and open it.
4. Open two more tabs in Google Chrome and repeat step 3 for both tabs.
5. Go to the first tab and wait until it has connected to the signalling server. When the topmost button changes text to "Online - Login", push it. This tab will then become the host.
6. Go to the second tab, wait for it to connect to the signalling server and then push the "Online - Login" button. This tab will join the game as the first peer.
7. Go back to the first tab (the host) and press "Lock game". When the game is locked, a new peer that tries to connect will immediately be kicked by the host.
8. Go to the third tab, wait for it to connect to the signalling server and then push the "Online - Login" button. After a short while (less than a second) the javascript error will occur in this tab.

**Comment by esowe** [comment]
I have now tried this in the new R112 release and I cannot reproduce it with that release.

**Comment by AshleyScirra** [comment]
OK, please file again if you run in to it again.
