### ISSUE TITLE
Regular expressions don't seem to yield results in the new C3 runtime

### ISSUE THREAD

**Issue by bsweileh** [Scirra/Construct-3-bugs#1905]
## Problem description

Regular expressions (i.e. regexMatchAt, regexMatchCount, regexReplace, regexSearch) do not seem to work in the new Construct 3 runtime. 

## Attach a .c3p

Link: https://bit.ly/2ASWJhC

## Steps to reproduce

1. Preview the project in C2 runtime
2. Change project settings to the C3 runtime
3. Then preview the project in the C3 runtime

## Observed result

In the C2 runtime, the preview shows a white layout with Text objects containing examples of regular expressions with correct outputs.

When changing to the C3 runtime and previewing the project, we see a blank or black screen. 

## Expected result

Previewing the project in the C2 and C3 runtimes should yield identical results, namely: we should see the text objects with the correct outputs for those regular expressions. Instead, we don't see anything in the C3 runtime!

## Affected browsers

* Chrome: Yes
* Firefox: Yes
* Edge: Didn't test
* Safari: Didn't test

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 67.0.3396.99
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
C3 release: r111 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 11 gb
Storage usage (approx): 42 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 650M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2047
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
