### ISSUE TITLE
line of site STILL not working on runtime 3

### ISSUE THREAD

**Issue by dolomite** [Scirra/Construct-3-bugs#1906]
## Problem description

This is in reference to issue #1879 where line of site is not functioning on runtime 3. This is issue is still in effect for release r112 beta of C3. Except that now when switching back to runtime 2, the issue still occurs whereas in r111 this didn't happen on runtime 2.

## Attach a .c3p

[line_of_site_test.zip](https://github.com/Scirra/Construct-3-bugs/files/2269186/line_of_site_test.zip)

## Steps to reproduce

1. Project is currently set to runtime 3
2. Move the green object (player) to jump past the block barrier to approach the red object (enemy). When the player is past the block barrier and is in the line of site of the red object (enemy), the enemy should start rotating. In runtime 3, it constantly rotates even when the player is still behind the block.
3. Set the project to runtime 2. The issue still occurs. Note that in r111 this didn't happen with runtime 2.

## Observed result

The red object constantly sees the green object even past the block barrier and automatically starts rotating.

## Expected result

The red object should not see the green object until its past the block barrier. 

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.84
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
C3 release: r112 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 227 mb (1.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The attached project's only event is "Every tick, rotate 1 degree clockwise". So it's unconditional and makes no reference to the line-of-sight behavior. It's working correctly as the events say.

**Comment by dolomite** [comment]
For some odd reason the .c3p that got uploaded was some older incomplete version. Weird.......
But i just checked again with the correct .c3p and can confirm that the line of site is now properly working on runtime 3 and 2.
