### ISSUE TITLE
[Beta] Crash renaming file extension

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#191]
## Problem description

After creating a new empty .json file of an Array or dictionary, you could rename the extension but it will crash.

## Steps to reproduce

1. Create an Array or dictionary file.
2. Rename the extension.

## Observed result
Crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot modify the mimeType to Binary @ Error: Cannot modify the mimeType to Binary at window.ǃyJ.ǃigl (https://editor.construct.net/r26/main.js:61:381955) at j.ǃiv.then.q (https://editor.construct.net/r26/components/bars/projectBar/projectBar.js:1:8312)
Stack: Error: Cannot modify the mimeType to Binary at window.ǃyJ.ǃigl (https://editor.construct.net/r26/main.js:61:381955) at j.ǃiv.then.q (https://editor.construct.net/r26/components/bars/projectBar/projectBar.js:1:8312)
Construct 3 version: r26
URL: https://editor.construct.net/index.html
Date: Mon May 15 2017 12:40:15 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 16.6 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Interesting, I don't think it occurred to me to even try changing the extension while the data editor was still open. Should be relatively easy to fix though. I'll have a look into it when I get to the office

**Comment by shortercode** [comment]
Seems to be specific to converting to non compatible file types and not related to the data editor. So for example: text to audio will cause a crash. Need to add an error dialog for it. Also noted a separate bug that files that look like data editor files will always open in the data editor, even if they aren't json files.

**Comment by shortercode** [comment]
Should be fixed in the next release!
