### ISSUE TITLE
Tilemap flood fill not working properly

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1912]
## Problem description

The tilemap flood fill tool is not working properly, it look like it's taking erased tiles in consideration to calculate the flood.

https://i.imgur.com/RSyTqSE.gif

## Attach a .c3p

[Tilemap Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2276082/Tilemap.Bug.zip)

## Steps to reproduce

1. Select the tilemap.
2. Paint anything with a line in the middle.
3. Erase the line.
4. Use the flood fill tool on one of the side.

## Observed result

The flood fill tool take erased tiles in consideration.

## Expected result

The flood fill tool to not take erased tiles in consideration.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r114
