### ISSUE TITLE
Construct 3 Runtime - No Fullscreen on NW.js

### ISSUE THREAD

**Issue by AlonDan** [Scirra/Construct-3-bugs#1913]
## No Fullscreen on NW.js using the NEW Construct 3 Runtime

Changing from Construct 2 Runtime to Construct 3 Runtime using a Fullscreen on start of the game:
`System | On start of layout | Browser | Rquest fullscreen > Centered`

## Steps to reproduce

On start of the layout try to make Fullscreen works using the browser object:
`System | On start of layout | Browser | Rquest fullscreen > Centered` 

## Observed result

Fullscreen works on the default Construct 2 Runtime, but not when switching to Construct 3 Runtime (using the same code).
## Expected result

I expected it to work just like it did with Constuct 2 Runtime.
## Affected browsers

* NW.js

## System details

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r111 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 138 gb
Storage usage (approx): 567 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

The Clipboard API is not supported. Some clipboard features may be unavailable.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
No project was provided so I created a new project with default settings (notably defaulting to 'letterbox scale' fullscreen mode). It's also unclear from the description what exactly is not working - you just said it doesn't work the same in the C3 runtime. When I try it, the result is a bit confusing. It looks like there is a bug in the C2 runtime where when you request fullscreen centered, it actually stretches the viewport to fill the screen. I'm not sure it's meant to do this. In the C3 runtime it doesn't stretch to fill the screen (which I think is the correct behavior), but aligns the canvas in the top-left of the screen, which appears to be incorrect (but I don't know if this is what you were seeing, because you didn't describe it).

I've fixed the C3 runtime so it now centers the viewport in the screen, but doesn't stretch it to fill the screen. I think that's the correct result for these settings...

**Comment by AlonDan** [comment]
Sorry for not supplying a project file, the reason is it's from my personal project not a new file.

As I tried my best to describe it including the code, I'll try again (sorry about my bad English).
It does put the resolution of the game viewport (640x360 in my case) on the top-left cornet of the resolution of the layout (1280x720 in my case).

Using the C2 Runtime it is automatically stretch the resolution to Fullscreen.
I attached a screenshot so you can understand better what I try to do in C3 Runtime which is:
Stretching the game resolution to Fullscreen.
The code is a very simple one on both, I didn't change anything but switching from C2 Runtime to C3 Runtime.

I hope that this makes the issue more clear.

![c2_vs_c3__runtime__fullscreen_stretch](https://user-images.githubusercontent.com/21152334/43967656-914ae6c0-9ccd-11e8-919d-f48497ea54fe.png)

**Comment by AshleyScirra** [comment]
I think the only remaining issue is the C2 runtime incorrectly stretches when you choose the non-stretching "centered" fullscreen mode. Closing since the C3 runtime handles this correctly.

**Comment by AlonDan** [comment]
It seems like the C3 is not handle this correctly yet, maybe on beta because I just checked it on C3 Stable R111 and it is not working yet same exact problem.
How did you get this to work on C3 runtime? 

Will you fix it until the next stable release? because full screen is really important for my and many other game developers.

**Comment by AshleyScirra** [comment]
I think you wanted "Stretch (letterbox scale)".

**Comment by AlonDan** [comment]
Thanks Ashley, I just changed it and it works like a charm from a quick test.

**OFF TOPIC:**
Since this is already closed issue, I just posted a C3 Runtime on the forums it will be wonderful if you can [have a look](https://www.construct.net/il/forum/construct-3/general-discussion-7/should-i-start-using-construct-137200).

One more thing Ashley, Thank you for all the amazing work you do on C3 !
