### ISSUE TITLE
Parallax layers causes display problems with Z order

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#1914]
## Attach a .c3p

[Parallax.zip](https://github.com/Scirra/Construct-3-bugs/files/2279690/Parallax.zip)

## Steps to reproduce

1. Select a Sprite or a Tiled Background on layer "PARA2"
2. Change the Z order position (UP or DOWN)

## Observed result

Sprite and Tiled Background are "Moving", Box collision are offset...
strange visual rendering

## Expected result

Just changing on Z order

## Affected browsers

* Chrome: yes/

**Comment by Picoti** [comment]
This problem happens when "parallax in editor" is checked

**Comment by AshleyScirra** [comment]
The provided project uses a third-party addon "Shake mod". Please see the bug report guidelines.

**Comment by Picoti** [comment]
[Effect_Parallax_BUG.zip](https://github.com/Scirra/Construct-3-bugs/files/2302657/Effect_Parallax_BUG.zip)

Here's a C3P without addons.
The bug is here if the object on the parallax have an effect.
(If you remove Tint effect in the C3P, it work fine)

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
