### ISSUE TITLE
Fullscreen is not working with C3 RT

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1915]
## Problem description

The fullscreen function is not working with the C3 RT, istead of taking the whole screen it's just a tiny view on the top left of the screen.

## Attach a .c3p

[Fullscreen Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2280446/Fullscreen.Bug.zip)

## Steps to reproduce

1. Just press F5 (i'm using the desktop build).

## Observed result

Fullscreen not using the whole screen.

## Expected result

Fullscreen using the whole screen.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by BonzerKitten7** [comment]
Today i saw the R113 update which have this "C3 runtime: request fullscreen 'centered' in NW.js mode did not center the canvas" as one of the changes so i tested my game just to make sure it's working and well, the canvas was centered, but it was not occupying the whole screen, it was like a tiny game in the middle of a black screen.

**Comment by AshleyScirra** [comment]
That's what 'centered' mode is supposed to do - the other modes all stretch the viewport to fill the screen.

**Comment by AshleyScirra** [comment]
Closing as the C3 runtime handles this correctly.
