### ISSUE TITLE
Hidden project bar blocks interaction

### ISSUE THREAD

**Issue by runthis** [Scirra/Construct-3-bugs#1916]
## Problem description

When popping out the Project, Properties, Layers panels, something remains inside the main editor that causes invisible panels on the left and right, that blocks the ability to click objects underneath it.

## Attach a .c3p

Non specific to any project or platform, happens in online editor, desktop version, etc.
Video of issue:
https://www.slavehack2.com/clip0240.mp4

## Steps to reproduce

1. New Project
2. Pop out the 3 panels
3. Move the mouse inside the editor from left to right slowly to reveal a mouse icon change showing a hidden panel that can be resized, that can block objects underneath it from being clicked. 

## Observed result

The invisible panels block objects behind them and if you resize them, they reset their position when previewing the project. It may not sound like much, but it is extremely inhibiting and ruins the flow of creation.

## Expected result

Invisible panels not existing.

## Affected browsers

Construct Editor

**Comment by shortercode** [comment]
Thanks for the report, I've come up with a patch for the upcoming release.

**Comment by AshleyScirra** [comment]
r113 is out now, please verify fixed!

**Comment by runthis** [comment]
Same:

Open or start project, pop out all the panels, move mouse left to right inside editor to watch for mouse icon changes. Invisible panels still exist

**Comment by shortercode** [comment]
I'm afraid I can't reproduce this anymore, can you double check the version number in the "about" dialog is "r113 beta" for me and then give a click by click reproduction from the default editor state please.

**Comment by runthis** [comment]
Hi.

It was just at editor.construct.net which states it is r111 - If I need to use a different URL please let me know.

**Comment by runthis** [comment]
I see it.

https://editor.construct.net/r113/

It is resolved

**Comment by shortercode** [comment]
Cool you found it. r111 is our current stable release. [editor.construct.net](editor.construct.net) always points to the current stable, you need to go to a specific release to see the betas. If you'd prefer to be on the beta track there is an option in settings to notify you about beta releases. This will show a dialog on launch if your not on the latest beta.
