### ISSUE TITLE
Create by name doesn't allow pick by UID

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#1918]
## Problem description

In starting a new game I accidentally picked Create by name. The create works, and everything seems fine, but I store the UID to pick later, and when I try to pick by UID, it fails to do so. If I change the Create to create by object, no other changes, the pick works.

## Attach a .c3p

I did try to create a simpler example of this, but couldn't get it to fail. But it fails consistently with my original project - I trimmed what I could.

## Steps to reproduce

1. Run - you see a 5x5 grid. Nothing is rotated.
2. Edit event 14. Disable the Create-by-name action, and enable the Create-by-object action.
3. Run - you now see the grid box at 1,1 has rotated. The Pick-by-UID worked.

## Observed result

Nothing is rotated, because pick failed.

## Expected result

Pick should work - rotates sprite.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

[CreateByNamePickUIDBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2280742/CreateByNamePickUIDBug.zip)

</details>

**Comment by AshleyScirra** [comment]
There is no .c3p file attached so we cannot investigate this. If it only reproduces in your full project but not in a new project, this suggests it is simply a mistake in your events.

**Comment by blackhornet2010** [comment]
https://github.com/Scirra/Construct-3-bugs/files/2280742/CreateByNamePickUIDBug.zip

The attachment is there. The browser doesn't let me add a .c3p file, so I renamed it .zip.

**Comment by blackhornet2010** [comment]
[CreateByNamePickBugMini.c3p.ZIP](https://github.com/Scirra/Construct-3-bugs/files/2284325/CreateByNamePickBugMini.c3p.ZIP)

Added .ZIP this time.

Comments inside. Got it down to 5 events.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
