### ISSUE TITLE
Closing the project while loading

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#1920]
## Problem description

Simply press the 'cancel' button while the project is loading from the cloud. It will open regardless in a few seconds (at least in a browser edition).

## Steps to reproduce

1. open construct
2.  open any project from cloud
3. press the close button

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Okay dokes, that should be fixed in the next release!
