### ISSUE TITLE
possible fullscreen viewport bug

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#1921]
## Problem description

I'm trying to make it so my game supports any screen size so i'm using a 16:9 aspect ratio with "scale outer" set.

I'm setting sprite positions based on viewport coordinates so they maintain their distance from the screens edge regardless of screen size.

I'm using the browser object to detect when the screen is resized with the "on resized" condition,
however i've noticed that if the game is in a window and it is resized then things work correctly, but if the game goes from window to "fullscreen", which also works as a "on resized" condition then objects are not repositioned correctly.

## Attach a .c3p

https://www.dropbox.com/s/8t1wou4j10h9rym/resizeIssue.c3p?dl=0

## Steps to reproduce

run the file, try resizing in a window then resize by going fullscreen.

## Observed result

When resized in a window the black square sprite should always be in the top corner, when its fullscreen it not aligned correctly.

## Expected result

black square should stay in top left corner of screen when fullsceen switched on.

## Affected browsers

* Chrome: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r104 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 83 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by mOOnpunk** [comment]
I just noticed that my "is fullscreen" conditions were not working when the screen was changed to fullscreen, but i realised it was when i was going fullscreen via the browser window button in the preview window itself and that if i instead use the "request fullscreen" condition of the browser object with events then things work correctly.

I dont know if its still classed as a bug or if going fullscreen via the browser is not supposed to call fullscreen actions.

**Comment by shortercode** [comment]
On mac the browsers "enter fullscreen" button doesn't actually trigger fullscreen mode, it just maximises the window. The difference being that in fullscreen the top controls for the browser are hidden. The only way to trigger fullscreen correctly on mac is to use the JS request fullscreen method. 

If you test on a windows PC the "enter fullscreen" button works the same as the JS method.

**Comment by mOOnpunk** [comment]
Is it possible to add an "is maximised" condition to the browser object? That way if the maximised button is clicked i can trigger proper fullscreen with events.

**Comment by AshleyScirra** [comment]
I can't reproduce any issue on Windows. However I think this project unwittingly sets up a race condition between whether the 'On resized' trigger or the runtime handles the resize event first. I think the runtime may also wait until the next tick before it updates the viewport in response to the resize event. So in this case I think you probably should just add a short wait. There shouldn't be a need to wait for resize events like that anyway, you could just use the Anchor behavior or position every tick instead.

**Comment by mOOnpunk** [comment]
As its already been established i'm not on Windows so why test on windows?

The point is when people on a mac go fullscreen by clicking the fullscreen icon or select fullscreen from the menu its not triggering the proper fullscreen. Adding an "is maximised" condition so we can set fullscreen mode through events i think is simple solution.

**Comment by AshleyScirra** [comment]
Browsers don't tell the page if it's maximised or not. Those are platform-specific details of the host OS.

**Comment by mOOnpunk** [comment]
So i guess then we'll just ignore the issue?

**Comment by AshleyScirra** [comment]
Yes, especially since:

> you could just use the Anchor behavior or position every tick instead
