### ISSUE TITLE
Should Pin work with scale ?  

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1924]
## Problem description

I was wondering If I pin a gun to a sprite, not in the center ,  at say a corner , and then scale that sprite would it be reasonable to expect the pinned object to move in accordance with the scale of the item it is pinned to ?

## Attach a .c3p

[Pin Position With Scale (1).zip](https://github.com/Scirra/Construct-3-bugs/files/2288221/Pin.Position.With.Scale.1.zip)

## Steps to reproduce

run the attached c3p  (file ext changed to zip)

## Observed result

the pinned gun stays in a position representing original full sized sprite.

## Expected result

gun stays in correct position as per scaled sprite.  

na

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by mOOnpunk** [comment]
As far as i know pin has never worked with scale, even in c2. I think Rex even made a custom plugin to support it. Its also been a feature that has been asked for before on the forums. Dont recall if it was ever implamented.

**Comment by BonzerKitten7** [comment]
Pin never had that option, but there are many little features like this one that could be a great addition to C3. Unfortunately some of these features would probably break compatibility with many projects, so Scirra is not willing to add these features. I already tried to make a suggestion about how scale works a few months ago, but i was ignored. :/

**Comment by AshleyScirra** [comment]
The Pin behavior has never taken in to account scale. It's implemented simply as "keep the same distance and angle from the pinned object".

You could position to an image point instead which does move according to the object scale.
