### ISSUE TITLE
(C3 rt) Sine cannot be enabled in events if initially disabled as default

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1925]
## Problem description

Works in C2 run-time but not in C3 run-time
The sine flash is disabled as default (for all instances /set in properties when object selected in the project win) then enabled by the mouse over.
If you enable the sine as default it works in c3
so with C3 run-time you cannot enable sine (and possible other behaviors) if not enabled as default.

## Attach a .c3p

[SineIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/2288495/SineIssue.zip)

## Steps to reproduce

Run c3p attached (file changed to zip)
works in c2 but not c3

in c3 runtime , enable the sine behavior on the  main sprite object as default then works ok

## Observed result

boxes do not flash

## Expected result

boxes flash

## Affected browsers

* Chrome: yes

ps i think this may happening on other behaviors as well but haven't checked yet.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
