### ISSUE TITLE
Problem in "Google Play" & "Mobile Adverts" Plugin

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#1927]
## Problem description
**1) Google Play**
This Plugin is working good but only when Game is not Published on Play Store. When I publish game in Play Store. It has problems.
in the Unpublished Apk it Shows Leaderboard scores. But after uploading it to Play Store it only attempt Login and never shows Leaderboard Scores.
[Unpublished APK](https://www.dropbox.com/s/pdq7f4g4psp354i/Snaky.apk?dl=0)
[Published APK](https://play.google.com/store/apps/details?id=com.luckyrawat.snaky)
install this apk, Click on Leaderboard Icon and see the result on both 
**2) Mobile Adverts**
This plugin also working but in a wrong way
Basically once ads loaded it should Show Ads on Action "Show Interstitial Adverts" or "Show Banner Adverts" but this is not showing ads on this Action.
It Showing ads on "Create Banner Ads" or "Create Interstitial Ads"

## Steps to reproduce
Google Play
Make Events to show Leaderboard scores 
Mobile Adverts
Make Events to Show Ads.

1.
2.
3.

## Observed result
**Google Play**
(in Published apk) Leaderboard don't showing scores and only displaying sign in 
(in Unpublished apk) Leaderboard showing scores perfectly 
**Mobile Adverts**
Showing ads with Action "Create Banner Ads" or "Create Interstitial Ads" instead of "Show Interstitial Adverts" or "Show Banner Adverts"

**Google Play**
(in Published apk) Leaderboard don't showing scores and only displaying sign in 
(in Unpublished apk) Leaderboard showing scores perfectly 
**Mobile Adverts**
Showing ads with Action "Create Banner Ads" or "Create Interstitial Ads" instead of "Show Interstitial Adverts" or "Show Banner Adverts"

## Expected result
**Google Play** (in Published apk) Leaderboard should show scores.
**Mobile Adverts**
Ads should show with Action "Show Interstitial Adverts" or "Show Banner Adverts" instead of "Create Banner Ads" or "Create Interstitial Ads".

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
It doesn't look like it's actually completing the sign in on the published version. When you signed your debug APK and release APK did you use the same certificate?

As for the advert methods, they have a parameter called "show" that selects if it should show the advert once it has loaded.

**Comment by luckyrawatlucky** [comment]
both are same apk
The attached apk is uploaded in play store.

**Comment by luckyrawatlucky** [comment]
Do you need that SHA1 code?

**Comment by shortercode** [comment]
I was going to cross check it against the APK you sent me, but as it works I know they match.

**Comment by luckyrawatlucky** [comment]
i have used google apk signing service

**Comment by shortercode** [comment]
Okay so you probably know they resign your game with a different certificate after you've uploaded it. This new certificate has a different SHA1 signature to the one you used before so you will need to get that signature and change the value in the Google API console. It may take a little while for the google servers to update.

**Comment by luckyrawatlucky** [comment]
okay I will update that.
and what about Mobile Adverts?

**Comment by shortercode** [comment]
so the issue with mobile adverts was that they always showed when you created them right? In your create method what is the "show" parameter set to?

**Comment by luckyrawatlucky** [comment]
at starting i used 
when "Banner Loaded" > Show Banner Ad
when "Interstitial Loaded" > Show Interstitial Ad
But ads were not showing in this case 
i did some experiments and found that 
I only applied 
When Enemy hit player > "Create Banner Ads" or "Create Interstitial Ads" 
Its working
I never did load "Banner Ad"

**Comment by luckyrawatlucky** [comment]
I updated SHA1 code and now leaderboard score working perfect 
thanks

**Comment by luckyrawatlucky** [comment]
No Update on Mobile Adverts?

**Comment by luckyrawatlucky** [comment]
No Update on Mobile Adverts?

**Comment by shortercode** [comment]
Glad to hear the leaderboard is working correctly now.

I'm not clear on what your issue is with the mobile advert plugin. As it's unrelated to your issue with Google play could you file a new issue with an example project, so that I can see how your using the plugin.

It's worth noting that a fairly large update is due to be released for the mobile advert plugin, so it may be worth testing your problem with that before filing a new report.

**Comment by shortercode** [comment]
Closing this as the primary issue has been resolved
