### ISSUE TITLE
Dt with worker is different then without worker

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1928]
## Problem description

Construct 3 template for GPU test(fillrateperf), if tested with worker is bugged. Dt with worker is different then without worker

## Attach a .c3p
[WorkerDt_Wrong.zip](https://github.com/Scirra/Construct-3-bugs/files/2296155/WorkerDt_Wrong.zip)

## Steps to reproduce

1.Start example -> preview.
2.See that Sprite count will stop rising when dt gets higher.
3.Enable worker -> preview. See dt acts differently, sprite count gets very high and makes chrome laggy. 

## Observed result
When worker is enabled, tests that count on Dt  are unstable and unusable.

## Expected result

Dt should work with and without worker similarly.

## Affected browsers

* Chrome: yes
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3524.0
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3524.0 Safari/537.36
C3 release: r113 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 46 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This looks related to crbug.com/872999 which appears to have been prematurely closed before any investigation was done. The problem appears to be that in a worker under heavy GPU load, the framerate measures higher than the number of frames actually reaching the screen. If I run the stock fillrateperf demo in worker mode, it ends up measuring ~15 FPS, but only visibly rendering 1-2 FPS. Presumably Chrome is not correctly scheduling this, which results in incorrect dt measurements because it's starting the next tick before it knows it can actually schedule the frame to the screen. If the test doesn't have meaningful dt measurements it won't be able to run the test correctly.

dt is measured solely by the rate of requestAnimationFrame callbacks, which the browser controls. So I would suggest re-filing a Chrome issue and allowing it to be investigated.

**Comment by SnipG** [comment]
Was about to make report with 2 examples, but when examples are hosted on github. the GPU reading is NaN. If i test it on construct 3, gpu reading is correct but when exported its NaN,  is there some simple workaround for this?

**Comment by AshleyScirra** [comment]
It depends on if the browser exposes the timer query extension. It's disabled at the moment due to the Spectre attacks but should be enabled again in Canary.

**Comment by SnipG** [comment]
Idk, now i hit some other nasty bug i think. I tried older html5 exports you had, they work fine in lastest dev or canarly. But my examples don't even open... While they do in chrome 68...
They worked before when i uploaded(i think), but now testing while writing report to google,1 test trows oh snap in canarly and in dev just black screen.
Could you try to open links in latest dev or canarly: https://snipg.github.io/GPUWithWorker1/
https://snipg.github.io/GPUWithoutWorker1/
Cant even report if links do not work.
while 2 links below work in 68 and dev, but not in canarly.
https://snipg.github.io/WithoutWorker2/
https://snipg.github.io/WithWorker2/
