### ISSUE TITLE
Crash on Cordova export

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#193]
## Problem description

Tried to export KiwiStory via Cordova

## Attach a .c3p

<demo>

## Steps to reproduce

1. Export
2. Deduplicate/Recompress/Minify
3. Default OSes with "Hide status bar"

## Observed result

"Oops!"

## Expected result

No oops!

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'androidVersion' of undefined @ TypeError: Cannot read property 'androidVersion' of undefined at ǃN.ǃiZ.ǃig.ǃqg.ǃiv (https://editor.construct.net/r26/exporters/cordova/exporter.js:1:2883) at ǃN.ǃiu.ǃfQ.ǃNH (https://editor.construct.net/r26/exporters/cordova/exporter.js:1:7983) at Promise.resolve.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.Le (https://editor.construct.net/r26/main.js:63:12548)
Stack: TypeError: Cannot read property 'androidVersion' of undefined at ǃN.ǃiZ.ǃig.ǃqg.ǃiv (https://editor.construct.net/r26/exporters/cordova/exporter.js:1:2883) at ǃN.ǃiu.ǃfQ.ǃNH (https://editor.construct.net/r26/exporters/cordova/exporter.js:1:7983) at Promise.resolve.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.Le (https://editor.construct.net/r26/main.js:63:12548)
Construct 3 version: r26
URL: https://editor.construct.net/
Date: Sun May 14 2017 21:39:31 GMT-0700 (Pacific Daylight Time)
Uptime: 150.3 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 6570 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Looks like a build related bug, should be an easy fix

**Comment by AshleyScirra** [comment]
Thanks, fixed for r27.
