### ISSUE TITLE
End&Pos1 key not working near Brackets + Cursor stops at anything not text.

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1930]
## Problem description

End key does not move cursor to the end when near a Bracket and instead only moves after the bracket.
Pos1 key also does not work

End key and Pos1 key stop at anything that is not text (e.g. dots, plus, minus etc.).
Repeatedly pressing Pos1 will work something like holding Ctrl+Arrow.

(Tested in r113 - does not happen in r111)

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
@shortercode last looked at this code so assigning to you

**Comment by shortercode** [comment]
This was probably effected by the change to allow line breaks between tokens which went out recently.

**Comment by shortercode** [comment]
Okay so I've patched this for "home" and "end". I can't find much information on "pos1" and it's not on UK keyboards so I can't test it. From what I can see it's just "home" by a different name, as such I'm hoping it has the same keycode and such should be patched for you as well.

Can you check out the next release and let me know if it works for you.

**Comment by Leralasss** [comment]
Pos1 and End Keys work.
Pos1 is probably the same as Home.

**Comment by shortercode** [comment]
Thanks for confirming!
