### ISSUE TITLE
Collision polygon does not match from animation editor to game

### ISSUE THREAD

**Issue by theBdrive** [Scirra/Construct-3-bugs#1931]
## Problem description

The collision polygon in game does not match the collision polygon that is drawn in the animation editor. Many of the collision points are very far off from where they are displayed in the animation editor.

## Attach a .c3p

[collissionTest.zip](https://github.com/Scirra/Construct-3-bugs/files/2299923/collissionTest.zip)

## Steps to reproduce

1. Look at the collision polygons in both hill1 & hill2 sprites, there is a smooth transition between the two where they both meet.
2. Run the game and watch when the ball rolls down the hill

## Observed result

When the ball gets to the bottom/right side of hill1 and the left side of hill2 all of the collision points are much lower on the Y axis than where they are drawn in the animation editor, causing the ball to catch on the lip where the points are actually lower than where they are drawn.

## Expected result

Ball should roll smoothly down the hill1 and roll on to hill2.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
If you zoom in a long way you can see that's actually how you've set it up in the project:

![collmask](https://user-images.githubusercontent.com/768723/44336926-e29c8100-a470-11e8-9c38-ea057b9164ff.png)

This demonstrates that:

1) the collision poly of the ground is aligned with the bottom of the thick black edge, not the top;

2) the join between the sprites is not smooth, hence the bump when it hits it.

**Comment by theBdrive** [comment]
@AshleyScirra Please take a look at this issue again.

[collisionTest_v2.zip](https://github.com/Scirra/Construct-3-bugs/files/2302380/collisionTest_v2.zip)

I adjusted the collission polygons of both hills to be on the top of the black edge and to align perfectly, I also moved the ball down so you can see where the ball stops, showing where the collision polygons actually are(not where they are displayed in the animation editor.

Picture of collision polygons in layout view
![ss1](https://user-images.githubusercontent.com/9151862/44341263-380a6b00-a43c-11e8-9ccf-8321948103c1.png)

collision polygons in game
![ss2](https://user-images.githubusercontent.com/9151862/44341292-4e182b80-a43c-11e8-874d-2b1357e92815.png)

The collision polygon on hill 1 does not dip below the black line, yet in game you can see it clearly does. That ball is 75px, so those collision points on hill1 are are at least 10-15px off on the Y axis of where I have drawn them in the animation editor.

**Comment by AshleyScirra** [comment]
The physics engine has to split concave collision polygons in to a series of convex shapes. Since you have a gentle slope it has to fragment it in to a large number of sometimes tiny convex polygons. Unfortunately the physics engine doesn't handle this well which is resulting in a bump where the slope gently changes. You'll probably get better results if you just line up a bunch of overlapping rectangular physics shapes to create a curve along their edges.

**Comment by theBdrive** [comment]
@AshleyScirra Ah ok thanks for the explanation and recommendation.
