### ISSUE TITLE
Editor: Can't login to Dropbox on /r### URLs on iPhone

### ISSUE THREAD

**Issue by KelseyHigham** [Scirra/Construct-3-bugs#1932]
## Problem description

On iPhone, if you add editor.construct.net/r113 (and all other /r### URLs) to the home screen, it's impossible to login to Dropbox within that webapp instance.

## Attach a .c3p

N/A

## Steps to reproduce

1. Add editor.construct.net/r113 to the home screen, launch it, and tap OPEN to open a project
2. Select Dropbox from the source list
3. Tap 'Try Again' to open the popup

## Observed result

1. Construct redirects to the regular Safari browser and opens a Dropbox authentication page. 
2. Upon signing in, the page says "Redirecting…" and doesn't redirect anywhere.
3. Reopening the C3/r113 home screen icon, Construct isn't logged in to Dropbox.

## Expected result

The Dropbox authentication page should open within the home screen webapp, redirect back to C3/r113, and log in.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Desktop Safari: no
* iPhone Safari: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: webapp
Operating system: iOS
Operating system version: 11.4
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
C3 release: r113 (beta)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A9 GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by shortercode** [comment]
Safari has a few storage issues that are difficult to workaround. I believe whats happening here is that because it opens the popup in "real" safari but construct is in it's closed "webapp" safari they cannot communicate, so it never gets the token back from the login.

I think I have looked at this before and didn't come up with any good answers, I have a couple of new ideas which might be able to workaround it. It's a bit frustrating that safari needs special treatment for this though.

**Comment by AshleyScirra** [comment]
Might be another case of the iOS storage bugs:
https://bugs.webkit.org/show_bug.cgi?id=181849
https://bugs.webkit.org/show_bug.cgi?id=181850

**Comment by shortercode** [comment]
@KelseyHigham just to update you on this; I have revisited the code and tried my new ideas, but there hasn't been any positive progress.

The big issue here is that as soon as the login screen is opened construct is being closed in the background. This makes saving inherently unstable and prone to losing data.

**Comment by KelseyHigham** [comment]
Thanks for the update. This issue isn’t a showstopper for me now that I’ve found a [workaround](https://github.com/Scirra/Construct-3-bugs/issues/1933#issuecomment-415211132) to force C3 to update.

**Comment by shortercode** [comment]
I don't think we ever found a good way to fix this unfortunately. Things have changed a bit on iOS since 2018, it seems like under quite a few situations the background app doesn't close anymore so this isn't an issue. Going to close this issue.
