### ISSUE TITLE
[SDK] Reference Help

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1934]
## Reference List
1. loadingprogress
2. fps

## Need of Help
I need help on how I can get those values on runtime. Thank You.

**Comment by AshleyScirra** [comment]
This is a question, not a bug report. Please post such questions to the forum: https://www.construct.net/forum/construct-3/plugin-sdk-10

**Comment by ChadoriRebornXD** [comment]
Okay. 
But what I originally meant was, I think there are no such references available.
And I think it would benefit for more plugins if it were provided. For example, a Preloader plugin.
Thanks again.
