### ISSUE TITLE
Random error messages while trying to start construct

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1935]
## Problem description

Getting more strange errors lately, while trying to log into construct. Error messages suggest i have some sort addon conflict etc. But i think it comes from cache/cookies. So there could/should be some extra info in error page like:
 Go Settings - Advanced - Content Settings - Cookies - See all cookies and site data - Search Construct. Now Delete ones that do not remove saved project etc.
Error pictures in system details.

## Steps to reproduce
1. Have not deleted cache/cookies for long time
2. Surf web pages before open construct
3. Sometimes shows errors and need page reload for construct to open.

## Observed result
Lately getting more errors while tring to log into construct from chrome, and need to reload page to access construct.

## Expected result
Should not show errors.
Maybe some automatic cache/cookie deleting before logging?

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

![error1](https://user-images.githubusercontent.com/28864889/44336288-b50b0400-a47f-11e8-8155-0574f33fd02f.jpg)
![error2](https://user-images.githubusercontent.com/28864889/44336294-b9372180-a47f-11e8-9ebf-6ea835c47f8e.jpg)
![error3](https://user-images.githubusercontent.com/28864889/44336299-bccaa880-a47f-11e8-9ef5-3cc6bd9a5eaf.jpg)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid there's almost nothing we can do about a report like this. There aren't clear steps to reproduce the issue and the errors look like network fetches are failing, so it could just be a flakey network connection.  Please try to follow the bug report guidelines as closely as possible; they're there so we can actually take action on reports.

**Comment by SnipG** [comment]
Lately getting more of thous errors and yes my internet connection is pretty unstable.
So it is most likely from bad connection.
(Just adding this here if someone else have similar problem.)
![badnetwork](https://user-images.githubusercontent.com/28864889/44846778-0ecab580-ac5a-11e8-9b94-4fbb5dbf7a40.jpg)

**Comment by AshleyScirra** [comment]
Do you have dev tools open when it fails? If so, it could be this Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=878422
It doesn't reproduce if you close dev tools (although you might need to clear cache etc).

**Comment by SnipG** [comment]
Dev tool was not open, errors are random. Sometime random network fetch, sometime some worker error and does not load examples etc. Could be some account cache, i tend to click remember account. But very often when i log, account has been logged out. Maybe it fails to get account info etc and it fails.

I tried that chrome issue steps and i could not replicate that error on canarly or dev.

**Comment by SnipG** [comment]
Other error when it fails to load examples.
![error](https://user-images.githubusercontent.com/28864889/44851552-5e64ad80-ac69-11e8-9741-5b6ac94022d8.jpg)
