### ISSUE TITLE
Global Layers Break When Duplicating a Layout

### ISSUE THREAD

**Issue by daleinen7** [Scirra/Construct-3-bugs#1937]
## Problem description

Duplicating a layout that has a global layer on it will break all the corresponding layers on other layouts.

## Attach a .c3p

https://drive.google.com/file/d/1-0eiVmD3oj3z8fiACE_Vp8LaJZJEpNEn/view?usp=sharing

## Steps to reproduce

The global layer only works on the original layout. The other layouts don't display the contents of the global layer. 

## Observed result

The layouts don't display contents. 

## Expected result

When duplicating a layer, it should treat the duplicate as another layout that has a global layer on it. 

## Affected browsers

Desktop version. 

## System details

N/A

**Comment by DiegoScirra** [comment]
Fixed in r114
