### ISSUE TITLE
r 114 unhandled exception when closing tilemap window

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1940]
use any c3p file
close tilemap window by clicking the x 
unhandled exception

* Chrome: yes

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r114/main.js, line 174, col 40383
Message: Uncaught TypeError: Cannot read property 'ownerDocument' of null
Stack: TypeError: Cannot read property 'ownerDocument' of null at t.ǃeq (https://editor.construct.net/r114/main.js:174:40383) at t.ǃDU (https://editor.construct.net/r114/main.js:174:40416) at t.ǃit (https://editor.construct.net/r114/components/bars/tilemapBar/tilemapBar.js:1:1182) at Array.ǃc_ (https://editor.construct.net/r114/main.js:174:39386) at ǃV.Event.ǃiuL.ǃiuU (https://editor.construct.net/r114/main.js:2:201427) at ǃV.ǃI.ǃi$.ǃiP_.dispatchEvent (https://editor.construct.net/r114/main.js:2:199554) at ǃV.ǃI.ǃi$.ǃiP_.ǃEg (https://editor.construct.net/r114/main.js:2:325899) at ǃV.ǃI.ǃi$.ǃiP_.ǃEg (https://editor.construct.net/r114/main.js:2:330951) at ǃV.ǃI.ǃi$.ǃiP_.ǃEg (https://editor.construct.net/r114/main.js:2:341543) at ǃV.ǃI.ǃi$.ǃiP_.ǃiiA (https://editor.construct.net/r114/main.js:2:338016)
Construct 3 version: r114
URL: https://editor.construct.net/r114/index.html
Date: Tue Aug 21 2018 21:28:14 GMT+0100 (British Summer Time)
Uptime: 9.8 s

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r114 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r115
