### ISSUE TITLE
Greenworks plugins doesn't work properly

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1942]
## Problem description

Today i integrated the Greenworks into my project, but unfortunately it didn't work. I followed every step from the tutorial (I'm familiar with that stuff, it's similar to what i had to with the Steam4C2 plugin), i added the correct file ("steam_api.dll" for my win32 project) and i added a text file called steam_appid.txt with my app id inside, but even so it didn't work. I also tried to to activate the overlay through the plugin function and through the default command (shift + tab), but without any success.

Edit 1: I was able to activate the overlay by adding an extra command line suggested by a comment in the greenworks addon page, the command is "--in-process-gpu". I don't know what kind of effects this command does, but it seems like the plugin function is not working, only the default command (shift + tab) is working, i t works even if i don't have any event or function related to the plugin, i just need to add the plugin itself, which is weird.

Edit 2: Even if can't use the activate overlay function, it's weird to not have a deactivate overlay function in case we need it, which is very likely to happen.

## Attach a .c3p

Unnecessary.

## Steps to reproduce

Unnecessary.

## Observed result

The greenworks plugin doesn't work and is kind of incomplete.

## Expected result

The greenworks plugin to work and have all necessary functions.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Every release of Greenworks is tested and verified that it works. For Greenworks to work, the app ID must be valid and installed in your copy of Steam. Have you done that? The documentation notes what you can do if you don't have one yet:

> for testing you can use Construct 2's app ID of 227240. You must also have Construct 2 installed on your copy of Steam. It can be the free edition, and it works fine side-by-side with a non-Steam install.

**Comment by AshleyScirra** [comment]
I'm confused. The report now starts with "Greenworks doesn't work" and seems to end with "the overlay only sometimes works". What exactly is the problem you're having?

**Comment by BonzerKitten7** [comment]
Sorry if i didn't expressed myself very well, I'll try to be more clear now. My problems with the Greenworks plugin are:
- By following only the steps from the plugin documentation you won't be able to use it.
- There's no mention of this extra command that can make the plugin work (--in-process-gpu).
- Even when you add the extra command the "activate overlay" action doesn't work, only the default command work (shift + tab).
If i can help with anything more just tell me, i'll be here.

**Comment by AshleyScirra** [comment]
>By following only the steps from the plugin documentation you won't be able to use it.

Which steps are missing?

**Comment by BonzerKitten7** [comment]
I never said that there's a missing step, i just said that i followed all the steps in the documentation and it simply didn't work. Okay? That's it.

Luckily someone called "Je Fawk" commented about this extra command line that can make the plugin work, and it did work with hes extra command line, so I'm talking about it because you might be interested on taking a look at why the plugin only work with this extra command line and maybe add a new step in the documentation talking about this extra command line.

I don't know what is the best answer for the problem, I'm just informing what i saw.

There's anything else that i can do to help you find the cause of this bug?

**Comment by AshleyScirra** [comment]
But you went on to discuss getting the overlay to work. So I assumed you then got the plugin to work, and were testing the overlay. So did you in fact not get the plugin to work?

**Comment by BonzerKitten7** [comment]
I'll only answer your question to make it easier.

"So did you in fact not get the plugin to work?"

Yes, i managed to make the overlay work by adding the "--in-process-gpu" command line. Not with what the documentation provides. Maybe it's a problem in the documentation, maybe it's a problem in the plugin itself, i don't know. BTW, the overlay only works with "shift + tab", not with the "activate overlay" action.

There's anything else that i can do to help you solve this?

**Comment by AshleyScirra** [comment]
Right, so I think you're just using Steam's shortcut to show the overlay and not the "activate overlay" action? The question was could you get the Greenworks **plugin** to work, but you just answered that with "yes", but I think you meant "no" because you're not using any plugin features?

This is why it's best to only discuss a single thing per issue report - it gets very confusing otherwise. This has turned in to a mash of "does the Greenworks plugin work" vs. "does the Steam overlay work".

**Comment by BonzerKitten7** [comment]
First of all, i think you're right, I'm sorry for opening a very "generic" issue like that, i should have opened a more specific one.

Anyway, i think i got the "final" report, we ended up with two problems:

1. The plugin doesn't work, the "activate overlay" action is completely unresponsive with or without the extra command line.

2. The default command for overlay (shift + tab) doesn't work with Construct games, i tried to open my game without the plugin and without the extra command line and this is what i get: https://imgur.com/7mobYNA absolutely nothing happens when i press shift + tab.
But, when i export game without the plugin, but adding the extra command line this is what i get: https://imgur.com/oJ2Vqid the overlay works like a charm. So problem here is that Construct games doesn't work with the Steam overlay out of the box.

Guess now we have all the problems listed here, sorry for the confusion.

**Comment by AshleyScirra** [comment]
Can we just limit this report to getting the "Is available" condition in Greenworks to be true? That indicates the plugin is able to work. Everything else would be a separate issue. Can you verify that the condition is not true for you, to make sure that you're not being confused by some other issue with the overlay?

**Comment by BonzerKitten7** [comment]
Okay! Should i open an issue for each problem? I just tested the "is available" condition, i tried to make my player spawn a green sprite when "is available" is true, but no green sprite appeared. I used the correct SDK, the correct NWJS version, etc.

**Comment by AshleyScirra** [comment]
I just tested the latest version of the Greenworks addon (https://www.construct.net/make-games/addons/84/greenworks/0-30-4), using NW.js 0.30.4 and Steamworks SDK 1.42 as documented, and following the setup steps (https://www.construct.net/make-games/addons/84/greenworks/documentation). My test project worked fine - "Is available" was true and it was able to retrieve information from Steam. If you cannot get that working, then I assume you have missed a step or misconfigured something.

If you have it working ("Is available" is true) and there are any other issues, please file separate issues for them.
