### ISSUE TITLE
Google Play enhacments

### ISSUE THREAD

**Issue by MrWonka** [Scirra/Construct-3-bugs#1943]
I would like to see the ability to use google play's save and event features natively in construct 3. This would make it much easier to sync data and collect analytics on an app.

**Comment by AshleyScirra** [comment]
Please file suggestions here: https://construct3.ideas.aha.io/

**Comment by shortercode** [comment]
Other users have requested this in the past, and it's quite complicated to do. It requires hooking into parts of the runtime that plugins don't have access to at the moment.
