### ISSUE TITLE
Object :: Instance Variable : Undo Error with changing data types.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1948]
## Problem description

When changing an object's instance variable's data type, then doing an **undo**. It will result an error.

## Minimal Project Sample

[Bug Report.zip](https://github.com/Scirra/Construct-3-bugs/files/2318829/Bug.Report.zip)

## Steps to reproduce

_From the Event Sheet._
1. Change the Sprite Instance Variable Data Type from "Boolean" to "Number"/"String".
2. Press "Ctrl + Z" or Undo.
3. Observe the error.

## Observed result

**Undo** results an error from restoring the previous state.

## Expected result

For **Undo** to work successfully.

## System details

Construct 3 :: R114

**Comment by shortercode** [comment]
Thanks for the report, it was swapping the value and type in the wrong order during the undo. Fixed in the next release.
