### ISSUE TITLE
Crash after Undo/Redo a cloning object type with Behavior

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#1949]
## Problem description

After "cloning object type" an object with a behavior and CTRL+Z CTRL+Y
---> CRASH

[PIN_Clone_BUG.zip](https://github.com/Scirra/Construct-3-bugs/files/2319131/PIN_Clone_BUG.zip)

## Steps to reproduce

1. Select object TEST and "clone object type"
2. Place instance of clone
3. CTRL + Z
4.  CTRL + Y

## Observed result

CRASH

## Expected result

Redo

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: cannot undelete active project object @ Error: cannot undelete active project object at i.ǃVbn (https://editor.construct.net/r114/main.js:80:54743) at d.ǃVbn (https://editor.construct.net/r114/main.js:80:203967) at d.ǃ_p (https://editor.construct.net/r114/main.js:80:54603) at ǃVw.ǃmp.ǃkqf (https://editor.construct.net/r114/main.js:80:482772) at window.ǃV_K.ǃiih (https://editor.construct.net/r114/main.js:80:480442) at i.ǃiih (https://editor.construct.net/r114/main.js:80:77161) at window.ǃdUk.ǃiih (https://editor.construct.net/r114/main.js:174:79196) at Array.ǃNP.ǃV.ǃe.ǃV.ǃNz.ǃNy (https://editor.construct.net/r114/main.js:174:45818) at ǃV.Event.ǃiuL.ǃiue (https://editor.construct.net/r114/main.js:2:201244) at window.ǃdUk.dispatchEvent (https://editor.construct.net/r114/main.js:2:199544)
Stack: Error: cannot undelete active project object at i.ǃVbn (https://editor.construct.net/r114/main.js:80:54743) at d.ǃVbn (https://editor.construct.net/r114/main.js:80:203967) at d.ǃ_p (https://editor.construct.net/r114/main.js:80:54603) at ǃVw.ǃmp.ǃkqf (https://editor.construct.net/r114/main.js:80:482772) at window.ǃV_K.ǃiih (https://editor.construct.net/r114/main.js:80:480442) at i.ǃiih (https://editor.construct.net/r114/main.js:80:77161) at window.ǃdUk.ǃiih (https://editor.construct.net/r114/main.js:174:79196) at Array.ǃNP.ǃV.ǃe.ǃV.ǃNz.ǃNy (https://editor.construct.net/r114/main.js:174:45818) at ǃV.Event.ǃiuL.ǃiue (https://editor.construct.net/r114/main.js:2:201244) at window.ǃdUk.dispatchEvent (https://editor.construct.net/r114/main.js:2:199544)
Construct 3 version: r114
URL: https://editor.construct.net/r114/
Date: Fri Aug 24 2018 18:18:41 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 85.3 s

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r114 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 950 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.
