### ISSUE TITLE
C3 Greenworks v0.30.4 Overlay and Visual Popup not working on Mac and Linux

### ISSUE THREAD

**Issue by asdzxc8** [Scirra/Construct-3-bugs#1950]
## Problem description

The overlay and achievement visual popup doesn't work on both Mac and Linux.

## Attach a .c3p

Not required.
Tried putting all the 3 necessary files inside all the different folders but still no visual popup nor overlay.

## Steps to reproduce

N/A

## Observed result

>Is available>activate achievement>no visual popup in the bottom right hand corner of the game
Backend is working though:
Alt tab and checked>achievements are supposedly recorded

>Is available>activate overlay>nothing happen

## Expected result

>Is available>activate achievement>visual popup in the bottom right hand corner of the game

>Is available>activate overlay>Steam overlay activated

## Affected browsers

Mac and Linux

## System details

N/A

**Comment by AshleyScirra** [comment]
A project is required. Please see the bug report guidelines.

Also your report suggests you would be trying to show the overlay every tick, which is not advisable. You probably only want to do it in a one-off trigger, e.g. a key press.

**Comment by asdzxc8** [comment]
I did used key press for the Steam Overlay.
**Steam Overlay -**
![1](https://user-images.githubusercontent.com/41488581/44603018-f3a01600-a813-11e8-9be0-5660c450a1eb.jpg)
**Achievement visual popup -**
![2](https://user-images.githubusercontent.com/41488581/44603017-f3a01600-a813-11e8-92d3-227ff721a444.jpg)
By the way that does seems to be related why Steam Overlay and achievement visual popups are not working on Mac and Linux while it works on Windows.

The necessary files are included as highlighted below:
**Linux -**
![3](https://user-images.githubusercontent.com/41488581/44603102-3c57cf00-a814-11e8-95b5-1529a679cb9b.jpg)
**Mac -**
![4](https://user-images.githubusercontent.com/41488581/44603103-3c57cf00-a814-11e8-81af-bfda90de271e.jpg)

**Comment by AshleyScirra** [comment]
This contradicts what you wrote in your report. This is why we require an actual project.

**Comment by asdzxc8** [comment]
@AshleyScirra 
Hi Ashley,

My build just got rejected by Steam because the Steam Overlay and screenshot functionality are not currently implemented on Ubuntu 17.10.
Is this something that the Construct team wants to look at or is this something for the original Greenwork library?

I could pass the Construct team a key to look at the game on Steam but I don't think I'm comfortable enough to share the actual project files publicly here.

Please kindly advise.
Thanks!

On another note, apart from not being able to use the default keys (Alt+Tab) to close Steam Overlay that I've reported.. Steam is also rejecting me because pressing F12 will cause a Developer Tool to appear for all compatible platforms.
F12 by default is supposedly for Steam screenshot functionality;
https://store.steampowered.com/news/5047/

**Comment by MikalDev** [comment]
I know this old, but just in case you are still working on your issues.I am also having problems getting Steam overlay to show in Mac with the Official C3 Greenworks plugin. However looking over at the Greenworks Github, this seems like a common problem (overlay and Mac.) I do have other non C3/Greenworks/njws games in which overlay works on Mac.

For the F12 developer Tool issue check out this post:
https://www.construct.net/en/forum/construct-2/general-discussion-17/the-big-nw-js-roundup-tips-tri-119428

Click on the 'tab' Nw.js- Features

**Comment by asdzxc8** [comment]
Hey @MikalDev ,
Thanks for sharing. Is this issue still present in the latest patch? I'm switching over to C3 runtime soon and I was hoping that the issue _might_ be fixed in the latest version.
There's also this issue that the Steam Overlay hang the entire game in the Window version which I'm not really sure why as well.

I'm actually using the following code to disable the F12 developer Tool;
Steam review approved the Mac version apparently despite having the Overlay issue but I wasn't able to get them to pass the Linux version.
```
"document.onkeypress = function (event) {
event = (event || window.event);
if (event.keyCode == 123) {
return false;  }                                                           }

document.onkeydown = function (event) {
event = (event || window.event);
if (event.keyCode == 123) {
return false;  }
                                                                                       }  "
```

**Comment by MikalDev** [comment]
@asdzxc8 Yah, it looks like Mac with greenworks and steam overlay is still a problem. I tried using the latest official plugin with C3 with nw.js 0.33.3 and GW 0.14 / Steamworks 1.42. Still, no success (I have yet to see the Mac/overlay issue closed on the Greenworks github either.)

Nice trick on intercepting the F12 developer tool keypress.

For Windows though, I can get it to work with my simple test. See this addon doc for details (it's my extension to Greenworks plugin, but the tips should apply to the official C3 addon with Windows also.)
https://www.construct.net/en/make-games/addons/244/greengrinds/documentation
