### ISSUE TITLE
C3 Greenworks v0.30.4 Steam Overlay not able to close without force shutting down the entire game

### ISSUE THREAD

**Issue by asdzxc8** [Scirra/Construct-3-bugs#1951]
## Problem description

When the Steam overlay appears, there's no way to close it other than force shutting down the game.
No close Overlay under ACEs.

## Attach a .c3p

N/A

## Steps to reproduce

>Is available>activate achievement>overlay

## Observed result

Not being able to close Steam overlay without force shutting down the entire game

## Expected result

Being able to close Steam overlay with the instruction (default), which is Shift + Tab

## Affected browsers

Since Steam Overlay is not working on Mac and Linux. This applies to Windows (both 32 and 64 bits) only

## System details

N/A

**Comment by AshleyScirra** [comment]
The Greenworks library we use for the plugin doesn't appear to support closing the overlay (see documentation: https://github.com/greenheartgames/greenworks/blob/master/docs/setting.md - there is only a method to activate it). It would have to be requested to them if you want it.

Surely Steam has a keyboard shortcut or "close" button itself for the overlay though?

**Comment by asdzxc8** [comment]
@AshleyScirra 
Steam does has a default keyboard shortcut which is Shift + Tab to close the overlay but what I'm trying to put across is.. it's not working for me :(
I guess it work for you when you tested it out?
