### ISSUE TITLE
C3 Build Service - C2,C3 Project Unsigned Apk Issue

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#1953]
## Problem description
If you try build C2 project on C3 Build Service. It is give you "app-release-unsigned.apk" if you choose signed apk option.

## Project File
[Test.zip](https://github.com/Scirra/Construct-3-bugs/files/2320884/Test.zip)

## Steps to reproduce
1.
![1](https://user-images.githubusercontent.com/13033837/44621043-fcdac280-a8a7-11e8-9e09-eb98139fcff8.PNG)

2.
![2](https://user-images.githubusercontent.com/13033837/44621045-06642a80-a8a8-11e8-98fb-5fc39a71a837.PNG)

3.
![3](https://user-images.githubusercontent.com/13033837/44621046-0c5a0b80-a8a8-11e8-8eaf-2028ab7a0508.PNG)

**Comment by shortercode** [comment]
I have a feeling this may just have the wrong name, but I will take a look. Needs resolving either way.

**Comment by shortercode** [comment]
Have confirmed that signed APKs were being returned with the name `app-release-unsigned.apk` so I have corrected the name. Fix is already live.
