### ISSUE TITLE
GetProjectFileUrl in c3runtime works wrong when exportoing to Nwjs

### ISSUE THREAD

**Issue by valerypopoff** [Scirra/Construct-3-bugs#1954]
## Problem description

When you export to Nwjs on c3runtime, the project files are placed in root but GetProjectFileUrl returns 'media/namefile.js'

## Steps to reproduce

1. Add a project file
2. Export for Nwjs
3. Call GetProjectFileUrl 

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's not clear how you are doing step 3. Please provide everything in the report necessary to reproduce the problem so we can investigate.

**Comment by el3um4s** [comment]
I have the same issue.

[GetProjectFileUrl.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2349836/GetProjectFileUrl.c3p.zip)

**Comment by AshleyScirra** [comment]
The API you are using is currently undocumented. How do you know you are using an API correctly if it's not documented?

The method is slightly misnamed and is used to locate media files, mainly for the Audio and Video plugins. I think you want to use GetLocalFileUrl() instead.

Undocumented methods are subject to change at any time. For example we may want to rename that method to something more accurate. Doing so will break any code that uses it, hence our advice that you do not use undocumented features.

**Comment by valerypopoff** [comment]
@AshleyScirra got it, thanks!

@el3um4s does GetLocalFileUrl works as expected with Nwjs export (and other platforms)?

**Comment by el3um4s** [comment]
@AshleyScirra 
Sorry, but I don't find reference to GetLocalFileUrl().
I can find reference only in the forum, in your answer. Do you think to document an API to get the url file in preview mode? Or do I miss something?

If I understood [this](https://www.construct.net/it/forum/construct-3/plugin-sdk-10/accessing-project-files-on-run-126433), when I'm in preview mode I must use:

`this._runtime.GetAssetManager().GetProjectFileUrl('namefile.js')`

However, in the exported version I must use ([this](https://www.construct.net/it/forum/construct-3/plugin-sdk-10/how-do-you-download-a-plugin-t-130228?kws=GetLocalFileUrl)):

`this.runtime.getLocalFileUrl('namefile.js)`

@valerypopoff I haven't yet tested GetLocalFileUrl: tomorrow I'll do.

**Comment by AshleyScirra** [comment]
OK, the method names are so confusing, my previous advice I posted to the forum is wrong 😝 I've refactored the methods and documented the ones you should be using here: https://www.construct.net/make-games/manuals/addon-sdk/runtime-reference/manager-classes/assetmanager

The `LoadProjectFileUrl()` method will be available in the next release (the current release does not have it). That is the one you should be using for code to work across all platforms. Note it's async.

**Comment by valerypopoff** [comment]
@AshleyScirra 

So, depending on the version and runtime of Construct I will have to do one of these:

```
//CONSTRUCT2
"test.js"

//CONSTRUCT3 RUNTIME2
this.runtime.getProjectFileUrl( "test.js" )

//CONSTRUCT3 RUNTIME3
this._runtime.GetAssetManager().LoadProjectFileUrl( "test.js" ).then(url=>
{
	
});
```

Right?

**Comment by AshleyScirra** [comment]
Yeah, that looks about right.

**Comment by el3um4s** [comment]
@AshleyScirra Thank you
