### ISSUE TITLE
Animations Editor- Subfolder bug

### ISSUE THREAD

**Issue by Sparsha1232** [Scirra/Construct-3-bugs#1955]
## Problem description

I dragged an animation into a subfolder. And when I accidentally dragged that subfolder into the same animation "Oops..."

## Attach a .c3p

[BugReport.zip](https://github.com/Scirra/Construct-3-bugs/files/2321964/BugReport.zip)

## Steps to reproduce

1. Open the animations editor
2. Drag and drop the subfolder "New Folder" into the "Animation 1"
3. Close the edior
4. Again open the editor

## Observed result

Crash

## Expected result

It is not expected to move a subfolder into an animation

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r114/main.js, line 80, col 529764
Message: Uncaught TypeError: Cannot read property 'ǃVy_' of null
Stack: TypeError: Cannot read property 'ǃVy_' of null at e.ǃkoG.ǃkDe (https://editor.construct.net/r114/main.js:80:529764) at e.ǃkop.ǃkab (https://editor.construct.net/r114/main.js:80:599754) at e.ǃkop.ǃRk (https://editor.construct.net/r114/main.js:80:599488) at ǃV.ǃI.ǃq.ǃkIR.ǃLW (https://editor.construct.net/r114/main.js:80:521359) at ǃV.ǃI.ǃq.ǃkIR.ǃkoI (https://editor.construct.net/r114/main.js:80:520327) at ǃV.ǃI.ǃq.ǃkIR.ǃkoq (https://editor.construct.net/r114/main.js:80:520632) at ǃV.ǃI.ǃq.ǃkIR.ǃkoU (https://editor.construct.net/r114/main.js:80:520025) at a.ǃiei.ǃdfe (https://editor.construct.net/r114/plugins/sprite/plugin.js:1:2155) at a.ǃCW.ǃzO (https://editor.construct.net/r114/plugins/sprite/plugin.js:1:11123) at d.ǃzO (https://editor.construct.net/r114/main.js:80:205130)
Construct 3 version: r114
URL: https://editor.construct.net/r114/
Date: Mon Aug 27 2018 03:30:33 GMT+0530 (India Standard Time)
Uptime: 59.1 s

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r114 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r115.
