### ISSUE TITLE
Important items can be deleted instantly without warning

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#1957]
## Problem description

The following important items can be deleted instantly, without warning, from the project window in Construct 3. Unintentionally or inadvertently deleting these items would prove massively destructive to a project if subsequent work and saves are performed without noticing the deletion. (ie if currently working on and previewing a part of the game that does not use these items.)

- An **Event sheet** containing events. (Warning in C2)
- A **Folder** containing objects, including system objects. (Warning in C2)
- A **Layout** containing layers (Warning in C2)
- A **Layer** containing objects (Warning in C2)

**C3 already gives a warning when deleting families and also individual objects, even when they are not referenced in events or placed in a layout.  It should additionally not be possible to delete the above items without warning.**

## Attach a .c3p

Can use Kiwi Story Demo to test

## Steps to reproduce

Open Kiwi Story and delete the above items.  

## Observed result

They are deleted instantly without any notice or warning.

## Expected result

A warning

## Affected browsers

NA

## System details

NA

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should have this all covered in the next release.
