### ISSUE TITLE
Forced movement to the right when colliding with a moving platform

### ISSUE THREAD

**Issue by jgp1971** [Scirra/Construct-3-bugs#1959]
## Attach a .c3p

[bug_platformer.zip](https://github.com/Scirra/Construct-3-bugs/files/2327757/bug_platformer.zip)

## Steps to reproduce

1. Jump onto the lower edge of the incoming, vertically-moving platform

## Observed result

Even when the right arrow is not pressed, the character is moved to the right automatically.

## Expected result

If neither the left or right arrow are pressed, the character shouldnt be moved.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r114 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 163 mb (2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
These types of problem are extremely difficult to do anything about. The platform is moving very quickly so it's essentially crushing the player. One frame of movement will leave the platform wedged inside the player. Since it's solid and the player isn't allowed to overlap it, it activates it's emergency "get me out of here" routine which moves it to the nearest free space, which happens to be over to the right. This is all currently how it's designed to work.

I think you should just work around this by adjusting the game design to not have objects flying in to the player at high speed. It's very difficult for the engine to work out what to do.

**Comment by jgp1971** [comment]
I'm sorry @AshleyScirra, but I feel it's important to note that this behaviour also occurs (albeit with way lower impact) if you decrease massively the speed of the platform.

[test.zip](https://github.com/Scirra/Construct-3-bugs/files/2332446/test.zip)

That's with a period of 30 (in case you wanna give it a try inside the original .c3p file i submitted), which I assume it's on the realm of what we'd consider not very high speed.

**Comment by AshleyScirra** [comment]
Hmm, actually I realised for this specific case of a vertically moving ceiling, we can handle it similarly to a recent change we made to handle sliding walls. I've updated the next release to try to handle this better.

**Comment by jgp1971** [comment]
Is that recent change the one I mentioned here? https://github.com/Scirra/Construct-3-bugs/issues/1614 Cause that really helped a lot!

In any case, will try it with the next version then.
