### ISSUE TITLE
[Beta] Random delete Sprite object from project bar crash

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#196]
## Problem description

Was just working on a new project when deleting an unused Sprite object from the project bar caused a crash. From then on I cannot reproduce this crash. Hope the crash log able to tell something.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃk' of undefined @ TypeError: Cannot read property 'ǃk' of undefined at window.ǃLO.ǃiNh (https://editor.construct.net/r26/components/bars/projectBar/projectBar.js:1:9435) at Array.ǃZC.ǃN.ǃH.ǃN.ǃeN.ǃei.Q (https://editor.construct.net/r26/components/bars/projectBar/projectBar.js:1:1496) at ǃN.Event.ǃijb.ǃijU (https://editor.construct.net/r26/main.js:2:285589) at window.ǃg_N.dispatchEvent (https://editor.construct.net/r26/main.js:2:283981) at window.ǃg_N.ǃNuH (https://editor.construct.net/r26/main.js:153:39433) at ee.ǃNoF (https://editor.construct.net/r26/main.js:61:150542) at ee.ǃNoF (https://editor.construct.net/r26/main.js:61:172581) at ee.ǃNuM (https://editor.construct.net/r26/main.js:61:172713) at ne.ǃNoF (https://editor.construct.net/r26/main.js:61:159538) at ne.ǃNor (https://editor.construct.net/r26/main.js:61:68621)
Stack: TypeError: Cannot read property 'ǃk' of undefined at window.ǃLO.ǃiNh (https://editor.construct.net/r26/components/bars/projectBar/projectBar.js:1:9435) at Array.ǃZC.ǃN.ǃH.ǃN.ǃeN.ǃei.Q (https://editor.construct.net/r26/components/bars/projectBar/projectBar.js:1:1496) at ǃN.Event.ǃijb.ǃijU (https://editor.construct.net/r26/main.js:2:285589) at window.ǃg_N.dispatchEvent (https://editor.construct.net/r26/main.js:2:283981) at window.ǃg_N.ǃNuH (https://editor.construct.net/r26/main.js:153:39433) at ee.ǃNoF (https://editor.construct.net/r26/main.js:61:150542) at ee.ǃNoF (https://editor.construct.net/r26/main.js:61:172581) at ee.ǃNuM (https://editor.construct.net/r26/main.js:61:172713) at ne.ǃNoF (https://editor.construct.net/r26/main.js:61:159538) at ne.ǃNor (https://editor.construct.net/r26/main.js:61:68621)
Construct 3 version: r26
URL: https://editor.construct.net/index.html
Date: Mon May 15 2017 18:44:04 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 21020.3 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Sorry, in this case we can't fix the problem from the crash report alone. Please file a new issue if you can find steps to reproduce.
