### ISSUE TITLE
android not showing Menu/View/Bar

### ISSUE THREAD

**Issue by winkr7** [Scirra/Construct-3-bugs#1960]
## Problem description

The Menu/View/Bar does not show on a blank or new or big project.  Bar is missing.  It works fine on my windows version for empty and full projects.

## Attach a .c3p

just start up android and pick menu/view you won't have the bar option

## Steps to reproduce

Run an empty project and click menu/view  you won't see bar

1.
2.
3.

## Observed result

no bar option

## Expected result

bar option

## Affected browsers

fine in chrome

just android has the problem

## System details

android r111 installed to desktop.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
The bars do not work the same on the mobile UI, they can be accessed by swiping in from the sides. 

As they cannot be closed or opened it doesn't make sense to have the bars menu.

**Comment by winkr7** [comment]
Thanks Iain--but how do I get to the Tile editor in android or the layer
editor?  The tile editor doesn't swip in just project and properties swipe
in?

**Comment by shortercode** [comment]
While the project bar is open swipe from the right again and it will cycle
through project/layers/tilemap. You can read more in the manual

https://www.construct.net/gb/make-games/manuals/construct-3/getting-started/on-mobile

**Comment by winkr7** [comment]
that works, thanks for the help

**Comment by shortercode** [comment]
No worries, have fun!
