### ISSUE TITLE
Crash when cloning object in Project Bar

### ISSUE THREAD

**Issue by Rhindon** [Scirra/Construct-3-bugs#1963]
## Problem description
C3 crashes when attempting to clone a sprite object via the Project Bar

## Attach a .c3p
[busters escape v8-2 .zip](https://github.com/Scirra/Construct-3-bugs/files/2330626/busters.escape.v8-2.zip)

## Steps to reproduce
1. Right-click on Walls object.
2. Select "Clone".

## Observed result
The entire C3 editor crashes and must be restarted.

## Expected result
The selected object to be cloned as normal.

## Affected browsers
* Chrome: Yes
* Firefox: Untested (not installed on computer)
* Edge: Untested (not used on computer)
* Safari: Untested (not installed on computer)

## System details
<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r114/main.js, line 2, col 142948
Message: Uncaught Error: no content set
Stack: Error: no content set at n.ǃqR (https://editor.construct.net/r114/main.js:80:115169) at t.ǃVyS (https://editor.construct.net/r114/main.js:80:197528) at t.ǃVXp (https://editor.construct.net/r114/main.js:80:161336) at t.ǃVyC (https://editor.construct.net/r114/main.js:80:160973) at t.ǃVyf (https://editor.construct.net/r114/main.js:80:160557) at new t (https://editor.construct.net/r114/main.js:80:188533) at Function.ǃV.ǃe (https://editor.construct.net/r114/main.js:2:142927) at i.ǃVzs (https://editor.construct.net/r114/main.js:80:187276) at i.ǃUz (https://editor.construct.net/r114/main.js:80:178889) at window.ǃNS.ǃNS.ǃUa (https://editor.construct.net/r114/components/bars/projectBar/projectBar.js:1:22199)
Construct 3 version: r114
URL: https://editor.construct.net/r114/
Date: Tue Aug 28 2018 20:37:58 GMT-0700 (Pacific Daylight Time)
Uptime: 189 s

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r114 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
This turned out to be a pretty difficult edge case in the spritesheeting engine. I think it should be fixed for the next release though.

**Comment by Rhindon** [comment]
I must admit ignorance as to what that entails "under the hood" but I totally trust you know what you're doing. Thank you, Ashley.
