### ISSUE TITLE
MobileIAP - complete registration issue

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#1966]
## Problem description

"Complete product registration" triggers only one time in app. If you change Layout it is not trigger again.

## Attach a .c3p
Construct 3 r114
[TestIAPConf.zip](https://github.com/Scirra/Construct-3-bugs/files/2333100/TestIAPConf.zip)

## Steps to reproduce

1. Wait for complete registration
2. Change to layout 2 with click blue sprite
3. Back to layout 1 with click blue sprite

## Observed result

When you go layout 1 back it is not triggering.

## Expected result

It should be trigger when you go layout 1.

**Comment by shortercode** [comment]
Most of the native plugins have a session based lifecycle, not a layout based on. In other words their state persists across layouts.

As it is not possible to complete registration twice, the event does not fire. I would recommend checking the "Is registration complete" condition instead.

**Comment by QuasarX** [comment]
for Example:
If I run app without network it is not complete registration.
Steps:
1. Run app without network connection.
2. Connect network.
3. App still didn't complete registration.

**Comment by QuasarX** [comment]
@shortercode 
Can you review this again with this project?
[TestIAPv2.zip](https://github.com/Scirra/Construct-3-bugs/files/2388582/TestIAPv2.zip)

I was tried with my test app, If player don't have network when app opening and after player connect network. If I click buy button it is not trigger purchase action. So player need restart app, it is annoying.

**Steps:**
1.) Close your network connection (go offline)
2.) Run app and wait 5 sec
3.) Open your network connection (go online)
4.) Click buy button
5.) You can see nothing about purchase screen.
Screen:
![screenshot_2018-09-17-15-37-38](https://user-images.githubusercontent.com/13033837/45623563-74a7a180-ba90-11e8-850d-6b382c57a973.png)


So you need restart app with internet connection.
**After Restart with Network Open - Steps:**
1.) Click buy button
Screen:
![screenshot_2018-09-17-15-38-06](https://user-images.githubusercontent.com/13033837/45623570-796c5580-ba90-11e8-8297-569bdf3c18af.png)
