### ISSUE TITLE
ShadowLight shadows don't always extend off the screen

### ISSUE THREAD

**Issue by LapinChat** [Scirra/Construct-3-bugs#1967]
## Problem description

When a "ShadowLight" follow (always over) an object with the 8Direction behavior and the object touch or is near another object with ShadowCaster behavior, the shadow don't extend off the screen as it's stated in the ShadowLight documentation (https://www.construct.net/ca/make-games/manuals/construct-3/plugin-reference/shadow-light).

## Attach a .c3p

Based on "Shadows - soft penumbras" official exemple.
LINK: https://drive.google.com/file/d/1OMLDiHkiDbsnJ6qrxR7PSvyWggDuv0QA/view?usp=sharing

## Steps to reproduce

1. Move with the arrow the orange dot over the red zone.
2. Closer to the walls is better.

## Observed result

Not all the shadows extend off screen when the light radius of the ShadowLight is bigger than 0.

## Expected result

I expected to see all the shadows extending off screen when the light radius of the ShadowLight is bigger than 0. 

## Affected browsers

* Chrome: yes (Chromebook up-to-date)
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

No crash report

**Comment by AshleyScirra** [comment]
Should be fixed in next release.
