### ISSUE TITLE
performance issue if Fullscreen mode set to "scale outer"

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#1969]
## Problem description
while working on Fullscreen mode i have found that if i set it to "scale outer" it slow down performance of the game and if i set it to "Letterbox scale" then it becomes faster than "scale outer" mode
i am attaching both "Apk with "Letterbox scale" and "Apk with "scale outer" you can see the difference. You just have to see the box moving left to right.

## Attach a .c3p
[Apk with "Letterbox scale"](https://www.dropbox.com/s/8ccui9w8kw1se9x/Apk%20with%20Leterbox%20Scale.apk?dl=0)
[Apk with "scale outer"](https://play.google.com/store/apps/details?id=com.luckyrawat.snaky)

## Steps to reproduce

Set any game's Fullscreen mode to "scale outer" and "Letterbox scale" and see the difference 

## Observed result
in my Apk with "scale outer" box which is moving left to right is slow and flickring 

## Expected result
it should move smoothly as you can see in Apk with "Letterbox scale

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Sorry, we can't investigate issues from an APK only. We need a demo project to be able to investigate. Please see the bug report guidelines.

This issue could also be as simple as the fact "scale outer" renders a larger area, therefore requiring more GPU work, therefore not being able to run as fast.
