### ISSUE TITLE
Crash when i clone object type

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#197]
## Problem description

There 's a crash when i clone object type (the object is a sprite and is in a families and had a familie bahavior)

## Steps to reproduce

1. create a sprite object
2. create a families include this sprite object
3. create a family behavior (solid, for exemple)
4 clone the sprite with "clone object type

## Observed result

CrRASH

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: e is not defined @ ReferenceError: e is not defined at Promise.all.then.V (https://editor.construct.net/r26/components/editors/layoutView/layoutView.js:1:30284) at 
Stack: ReferenceError: e is not defined at Promise.all.then.V (https://editor.construct.net/r26/components/editors/layoutView/layoutView.js:1:30284) at 
Construct 3 version: r26
URL: https://editor.construct.net/index.html
Date: Mon May 15 2017 12:36:31 GMT+0200 (Paris, Madrid (heure d’été))
Uptime: 6688.9 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 950 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for r28.
