### ISSUE TITLE
Error message while loading browser C3.

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#1971]
## Problem description

Starting C3 via (chrome-) shortcut on my desktop resulted in a loading screen. This is normal.
Then it got stuck for about 30 seconds on "loading plugins".
When C3 was finished loading, it showed me an error message.
After I pressed the "restart" button, the loading worked quick and without error message)
So I cannot reproduce it. I have had this before, though. What I did before was remove the short cut and make a new one.
The reason I am doing this bug report, is because the C3 error message asked me to copy paste the text in a bug report (see below).

## Attach a .c3p

Not relevant.

## Steps to reproduce

1. Start short cut, I made with chrome.
2. wait

## Observed result

Error message while loading C3.

## Expected result

C3 loading, so that I can then load a project.

## Affected browsers

* Chrome: yes (but after I pressed the "restart" button, the loading worked quick and without error message)
* Firefox: no
* Edge: no
* Safari: not tested.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected function @ TypeError: expected function at Function.ǃV.ǃWr (https://editor.construct.net/r114/main.js:2:110545) at Function.ǃV.ǃe (https://editor.construct.net/r114/main.js:2:142908) at d.ǃJH (https://editor.construct.net/r114/main.js:80:32607) at Object.t.push.ǃV.ǃtP [as ǃius] (https://editor.construct.net/r114/main.js:80:32996) at t (https://editor.construct.net/r114/main.js:2:204686) at i (https://editor.construct.net/r114/main.js:2:204471)
Stack: TypeError: expected function at Function.ǃV.ǃWr (https://editor.construct.net/r114/main.js:2:110545) at Function.ǃV.ǃe (https://editor.construct.net/r114/main.js:2:142908) at d.ǃJH (https://editor.construct.net/r114/main.js:80:32607) at Object.t.push.ǃV.ǃtP [as ǃius] (https://editor.construct.net/r114/main.js:80:32996) at t (https://editor.construct.net/r114/main.js:2:204686) at i (https://editor.construct.net/r114/main.js:2:204471)
Construct 3 version: r114
URL: https://editor.construct.net/r114/index.html
Date: Fri Aug 31 2018 13:57:14 GMT+0200 (Midden-Europese zomertijd)
Uptime: 112.1 s

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r114 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I'm afraid there's not much useful in the crash report. It sounds like some network fetches failed which caused C3 to fail to load. I don't think we can do anything else without steps to reproduce, or at least any errors reported in the browser console.
