### ISSUE TITLE
Desktop - Failed to export project

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#1972]
## Problem description

I started getting this for a few days now on my main project using C3 desktop version. The repo rate is around 25%, if I restart C3 it sometimes works, sometimes doesn't so I keep restarting it until it works.

The project is 38mb big. Maybe you can look in the code at this and I'll try to reproduce it with a blank project.
If I remove image recompression it still fails.

![image](https://user-images.githubusercontent.com/7268697/44919500-575f9d00-ad46-11e8-89ef-c4d07b98f41e.png)

## Affected browsers

* Desktop

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.31.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.3541666269302368
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@878cd31214ac27a3996927cd5c9c138b10c9fc8d) NWjs/0.31.2 (like Chrome/67.0.3396.87)
C3 release: r111 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 5.8 gb
Storage usage (approx): 213 mb (3.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Do you have dev tools open while you export? There appears to be an issue in Chrome that causes network fetches to randomly fail while you have dev tools open.

**Comment by JeFawk** [comment]
I had dev tools from the Yandex browser, I guess this counts... I actually remember now you told me this a while ago. I'll close them and hopefully keep it in mind, thanks.

**Comment by JeFawk** [comment]
I did try without any dev tools opened and it failed.

**Comment by AshleyScirra** [comment]
I've no idea what this could be I'm afraid, and there's nothing I can do unless you can find a way to reliably reproduce it or at least something that it correlates with. As it stands the error looks exactly like your network connection is cutting out while it's fetching resources for export, so without additional evidence I can only assume it's that. Closing, please re-file if you can find more details.

**Comment by JeFawk** [comment]
I wasnt expecting too much because I don't really know what more info to provide. I'll see maybe it disappears sooner or later just as it appeared. I dont mind closing the project and reopening it. Cheers
