### ISSUE TITLE
Cannot open html files coming with the project

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#1974]
## Problem description

In C2, all I had to do to open an HTML file that was attached to the project was to open the page "/myFile.html" and it would work. It doesn't in C3. In fact I can't access any of the project files without doing an AJAX call which isn't useful if I just want to access the file URL, for image loading or page opening.

## Attach a .c3p

I've got 2 files to demonstrate this:
One with no plugin, only using the browser plugin and one using a custom addon.

[The addon](https://cdn.discordapp.com/attachments/183566321156358144/485502497482342410/beta-skymen_keyframeEditor.c3addon)

[The c3p with plugin](https://cdn.discordapp.com/attachments/183566321156358144/485503391275941889/Test_Keyframe_Editor.c3p)

[The c3p with no plugin](https://cdn.discordapp.com/attachments/311108993739390976/485526747429994506/WithoutPlugin.c3p)

## Steps to reproduce

Open project, click button.

## Observed result

The popup immediately closes.

## Expected result

The html file should open as a new page.

## Affected browsers
n/a

## System details
n/a

**Comment by AshleyScirra** [comment]
Opening "./myFile.html" in preview mode will request "preview.construct.net/local/myFile.html". It should not be a surprise that that file does not exist: it is local to the project and not uploaded to our server. The solution is to ask the runtime for a URL for the file - in preview mode it returns a blob URL that you can request like any other URL and it will load the local file. It appears you've already done this in your plugin, so it is already worked around.

**Comment by skymen** [comment]
"It appears you've already done this in your plugin, so it is already worked around."
But still, it doesn't work!
I do request the blob URL and try to open it and it won't open the window.

**Comment by skymen** [comment]
"When exported to HTML and correctly hosted your project should work."
"If you explain how you want your idea to work I might be able to offer an alternative?"

Alright so basically what I'm trying to achieve is an animation editor.
I made a window based editor using Vue (because I'm much more familiar with it and prefer that rather than loading stuff on top of the canvas).
I made the editor and the plugin supposed to open it. Of course the goal of that editor is to be used within the preview mode, as a debugging/creating tool for the game and not to be shipped with the export at any time.
While it perfectly works in C2, I'd love for it to work in C3 for when i'll want to switch engines.
And I can't host the editor on a different domain because of browser restrictions. I can't transfer data or get/create functions accross windows if they're not on the same domain, which makes the whole editor absolutely impossible to use.

**Comment by AshleyScirra** [comment]
> And I can't host the editor on a different domain because of browser restrictions.

You can. Construct 3's own preview mode runs on a different domain to the editor.

**Comment by skymen** [comment]
What I mean is that I can open the popup, but I can't access each other's functions and I can't set values from accross windows if they're not on the same domain, which breaks the app
![image](https://user-images.githubusercontent.com/11213825/45056806-3bd0fb00-b094-11e8-97a3-1282343e90ec.png)
