### ISSUE TITLE
[Forums] Can't upload an image on the forums. Neither [.jpg] nor [.png] works.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1978]
## Problem description

We can't seem to upload any image on the forums. Neither [.jpg] nor [.png] works.

## Observed result

**With PNG :**
![image1](https://user-images.githubusercontent.com/31282960/44977443-a30a8480-af9a-11e8-9b1f-fd238f0b5008.png)

**With JPEG :**
![image2](https://user-images.githubusercontent.com/31282960/44977446-a43bb180-af9a-11e8-99fa-c107d1870f73.png)

## Note

Thank you in advance for looking into this.

**Comment by AshleyScirra** [comment]
Please file website bugs to the separate tracker: https://github.com/Scirra/Construct.net-website-bugs
