### ISSUE TITLE
Dropdown listbox problem

### ISSUE THREAD

**Issue by Lennaert78** [Scirra/Construct-3-bugs#198]
## Problem description
On a layout with more then 1 listbox;
Listbox dropdown "on selection change" picks wrong listbox or doesnt work propperly

## Attach a .c3p

https://www.dropbox.com/s/pdxm5ppmrryi4xa/list_bug.c3p?dl=1

## Steps to reproduce

1. change value listbox 1
2. change value listbox 2

## Observed result

Second listbox values are not appearing in the text box

## Expected result

The correct listbox text appearing in the textfield

## Affected browsers

Only tested in Chrome

## System details
none needed

**Comment by Lennaert78** [comment]
Ashley, I updated to r27  earlier,  and checked my project with the multiple drop down lists,  and it worked as it should.   Unsure you even started on the issue I thought I check back at r26 to see if it still happens there, and the problem is gone there too. Weird, but fixed it seems.

**Comment by AshleyScirra** [comment]
Seems to be working fine here.
