### ISSUE TITLE
New C3 Runtime: Browser on Full Screen Covers the Debug Panel = GAME over Debug

### ISSUE THREAD

**Issue by AlonDan** [Scirra/Construct-3-bugs#1980]
## My game starting automatically with browser: 
`Request fullscreen - Stretch (integer letterbox scale)`

Fullscreen covers the NEW Debug mode, it cannot be seeing or used

Cannot attach my .c3p since it is my official project, but it's just a fullscreen event / action easy to test on any project.

## Using the Desktop version, do this:
`Start of Layout >> Browser >> Request fullscreen - Stretch (integer letterbox scale)`

## Observed result

You'll get the GAME in-front of the NEW Debug panel, so it is hidden, not acceptable at all.

## Expected result

I would like to see the normal Game/Debug split screen or at least move one of them to my other monitor by default. 

## Affected browsers

* Desktop Beta r115: yes
* Chrome: no (works fine)

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r115 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 142 gb
Storage usage (approx): 640 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

The Clipboard API is not supported. Some clipboard features may be unavailable.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by NetOneGames** [comment]
you cant really have split screen and full screen at the same time.  
you can use the little diagonal arrow in the corner of the debug window to detach your game window then you can have two seperate widows for debus and game and pu them where you want.

**Comment by AlonDan** [comment]
As I tried my best to explain consider English isn't my native language:
The GAME screen covers ALL, it is on top of the Debug mode, you cannot see, and of course click anything because you cannot see it.
I'm using the Debug on the C2 Runtime with no issue, the default is a split screen:
Above = Game Screen
Bottom = Debug Panel

Hopefully this explains the issue better, if not please Try to emulate the way I explained it, it's 1 line of code.
I hope that this helps, sorry about my bad English.

**Comment by AshleyScirra** [comment]
No project provided so tested with this: [fullscreen-test.zip](https://github.com/Scirra/Construct-3-bugs/files/2349352/fullscreen-test.zip)

It works the same as it does with the C2 debugger, so this is not a regression, despite the report seeming to imply it is. You can keep debugging if you open the debugger to a popup window. Presumably this is what everyone did with the C2 debugger, so closing as you can keep doing that with the C3 debugger as well.

**Comment by AlonDan** [comment]
I wish it worked as you shown in your file, but it's not:
To prove my point I just captured a VERY simplistic part of my game, you can see the issue as it appears, also I show that there is nothing weird in my code but just an ordinary 1 line as I explained.
The attached MP4 file will example the issue, it is only happening on the current version for now.

I hope that you can fix that because it is a very important to work with the Debugger, and as you can see impossible. 
And No, it didn't move to another screen, it's just BEHIND the game by default as shown on the Video.

* MP4 video file is zipped
[Construct3__Fullscreen_Debug-Panel__BEHIND-GAME__Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2349824/Construct3__Fullscreen_Debug-Panel__BEHIND-GAME__Bug.zip)
