### ISSUE TITLE
R115 c3 runtime debugger unusable under inspect tab

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#1981]
## Problem description

Under normal preview when i run my game it is 60fps and around 19%cpu. When i launch the new debug preview, under the inspect tab the fps drops to around 18 and cpu is very high causing extreme lag. When i switch to profiler or another tab it goes back to normal. This makes inspect tab unusable for me.

I've tried also checking the "worker" option but it has no effect. Not sure what worker does?

## Attach a .c3p

My game is a commercial project so i will have to send it to you privately. Its worth noting that i dont get this issue with the c3 demos, just my game so far.

## Steps to reproduce

Just run game in debug preview and click inspect tab.

## Observed result

low fps and high cpu causing extreme lag.

## Expected result

should work at normal game performance like other tabs in debugger do.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r115 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 87 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by mOOnpunk** [comment]
Also switching my game over to the c3 runtime has caused a number of other issues, unfortunately since i can't use debugger i can't track down the problems.

**Comment by AshleyScirra** [comment]
Is this worse or better than the old debugger?

If you email your project to ashley@scirra.com I'll give it a spin.

**Comment by jgp1971** [comment]
Same thing happening here (in terms of really bad performance compared to the C2 debugger). Also, from what I've seen checking or unchecking the webworker tick in r115 is irrelevant in chrome 68.0.3440.106: in either case it loads up the c3 runtime without the top-bar flag of using worker.

**Comment by mOOnpunk** [comment]
I sent the file from a temp email address "uzyqlgsr@sharklasers.com" since we have had issues communicating with my main yahoo account in the past. Thanks.

**Comment by mOOnpunk** [comment]
Also while you have the file you might want to check why that running under c2 runtime the "FullScreen Quality" set to low, when its run under the c3 runtime it sets it to high.

**Comment by AshleyScirra** [comment]
FRI Chrome 68 doesn't support worker mode (it's Chrome 69+), and it doesn't work anyway due to #1982 (should be fixed in next release). Unless you see "[worker]" appear in the caption, it's not using worker mode.

**Comment by AshleyScirra** [comment]
I've made some changes to try to improve the layout performance of the inspector. It does appear it can be slow when it's showing a lot of information. It probably also depends on the system spec so let's see how it works out in the next release. By then Chrome 69 should be out with OffscreenCanvas support, and #1982 is fixed, so you should be able to properly test if worker mode helps further. Additionally I've checked Chrome Canary (71), and it looks like its performance is much better, so I guess they did some optimisation there that helps - might be worth a shot checking that with the next release too.

**Comment by mOOnpunk** [comment]
Thanks will check next release.

I'm having other issues running the project under C3 runtime. Even though the debuggers laggy i've managed to track down the issue to the c3 runtime apparently not registering the current opacity value of a layer. In the same project file i sent you it is event line 3205 and 3206. 

Event 3205 lerps the layers opacity to 0 then 3206 detects when its below 1 and closes the menu. This works correctly under c2 runtime but not c3 runtime. Can you look at it? or should i start a new issue. Do you still have the file? Thanks.

**Comment by AshleyScirra** [comment]
Please don't mention multiple issues in one report - it gets incredibly confusing and we need all the bug report details to be able to help anyway, so please file a separate issue. And wherever possible, please try to isolate it in a minimal project, either by building it from scratch, copy-pasting the relevant bits out your project to a new one, or deleting away as much of the original project as possible until you have a minimal example of the problem. Debugging a full project could take months to get to the bottom of the issue, whereas a minimal project can often be a 10 minute fix.

**Comment by AshleyScirra** [comment]
r116 is out now, can you check what the performance is like with that? Hopefully it's better, but if you still have issues, it would be worth checking again with Canary since it seems they've made some kind of improvement recently.

**Comment by mOOnpunk** [comment]
I've updated to the latest version of Chrome. Without worker checked performance its still quite bad. If the game is left its settles to around 40fps and but when i start interacting it becomes unusable again around 4fps. 
With worker checked i get 60fps and very low cpu usage according to the debugger stats, however in reality the game still feels very choppy and there is a distinct delay between user controls and the game.

I guess its usable under worker for finding bugs but far from ideal. The c2 debugger runs better.

**Comment by AshleyScirra** [comment]
Did you try Canary?

**Comment by mOOnpunk** [comment]
Sorry i didn't realise it was a separate version of chrome. I just downloaded it and tested but the results were the same. Its usable but not as good as c2 debugger.

**Comment by tunepunk** [comment]
Having really poor performance while in the inspect tab as well. Especially in firefox. Reducing preview window the performance gets a bit better, but with ful screen preview game feels like still images slide show while in the inspect tab. 

Any updates on this one, as it has been Open for quite a while now? Inspect tab performance is really bad, especially in firefox full screen preview.

**Comment by SnipG** [comment]
I think it has like 10x better peformance, then it had when it first came out. People who test debugger peformance should try latest beta. If you try stable, it has still memory leak with huge amount text objects in inspect tab. Just something to consider!

(i pretty sure memory leak fix has some problematic behavior too, but thats another story)

**Comment by AshleyScirra** [comment]
Is this still a problem in the latest Chrome 75? How about Canary 77? Google recently rewrote the entire layout engine as part of the LayoutNG project and it may have improved things.

IIRC this comes down to the time to update the system inspector page when there's lots of layers, meaning there's a lot of content updating. I took some measurements using this as a test project: 
[debugger-perf.zip](https://github.com/Scirra/Construct-3-bugs/files/3359197/debugger-perf.zip)
and it looks like in Chrome 75 the layout time for both the C2 runtime debugger and C3 runtime debugger is about the same (~7ms on my machine). In Canary 77 it looks like the performance in the C3 runtime debugger is even better, updating in about ~5ms.

**Comment by tunepunk** [comment]
In firefox it's completely lagging. it's like 2 fps or something. But only in inspect tab, showing the system information.. other objects are okay. Used the provided test project.

Chrome 75 is okay. A little bit jaggy at times on a laptop. (Macbook Pro)

**Comment by mOOnpunk** [comment]
It seems ok for me now using chrome, both my original project and your test one. 

There is a but however, even though fps and cpu usage seem ok in reality it often feels laggy or jerky.

**Comment by AshleyScirra** [comment]
It sounds like the latest Chrome updates have sufficiently improved this that redesigning the inspector layout is no longer a worthwhile investment of our limited resources, so closing this issue as wontfix. Note enabling worker mode also moves the runtime off the main thread so the debugger won't slow it down, which should help things further.
