### ISSUE TITLE
C3 Runtime debugger doesn't work with worker mode

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#1982]
## Problem description

When running the new c3 runtime debugger with the runtime in worker mode the preview does not load.

## Attach a .c3p

Repeats with Demonoire.

## Steps to reproduce

1. Load Demonoire
2. Set project to c3runtime with worker enabled
3. Debug any layout

## Observed result

Game does not load

## Expected result

Game loads

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: untested

## System details

<details><summary>View details</summary>

Chrome 68 - C3 Beta r115 and current development version

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release
