### ISSUE TITLE
Layer lock icon is no longer visible unless layer is highlighted(r115)

### ISSUE THREAD

**Issue by theBdrive** [Scirra/Construct-3-bugs#1983]
## Problem description

Using the dark theme the layer locked/unlocked icon is not visible unless the layer is selected. This is a nightmare for projects with lots of layers.

## Attach a .c3p

NA

## Steps to reproduce

1. Open r115 editor, make sure dark theme is enabled.
2. Create a few layers

## Observed result

The lock icon is not visible unless the layer is selected

## Expected result

Locks for all layers should be visible whether selected or not.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

**Comment by AshleyScirra** [comment]
@shortercode why did you assign this as a theme issue? Does it only reproduce in the dark theme? The report didn't mention that

**Comment by theBdrive** [comment]
@AshleyScirra I forgot to add in my OP, since then edited, the problem is only on the dark theme.

**Comment by Animmaniac** [comment]
Fixed for next Theme release.
