### ISSUE TITLE
[website] Opening an attached image that seems to be uploaded (possible character issue in the filename)

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1986]
## Problem description

Clicking an image to have the "big" version of it leads to an error message.

## Steps to reproduce

1. Seen in the first post of https://www.construct.net/forum/game-development/game-development-design-ideas-25/help-with-lighting-mechanics-137571#forumPost949462
2. Click the image at the bottom of the post
3. 

## Observed result

"sin tÃ­tulo-2 not a handled upload."

## Expected result

The image displayed in full.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: not tested
* Safari: not tested

**Comment by Kyatric** [comment]
Issue can be "closed", I posted a report in the forums : https://www.construct.net/forum/scirra-website/website-issues-and-feedback-35/opening-an-attached-image-that-137582

I forgot this wasn't the place to post about website issues.

**Comment by shortercode** [comment]
@Kyatric we actually have a new repo for tracking bugs in the website [Construct.net-website-bugs](https://github.com/Scirra/Construct.net-website-bugs/issues)

**Comment by Kyatric** [comment]
Very good call ! Thanks.
