### ISSUE TITLE
[C3 Runtime] AJAX Request URL for project files does not work

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#1989]
## Problem description

Any AJAX URL requests that was supposed to get a file from the project failed, triggering my AJAX on error events. I recently ported over from the C2 runtime to the C3 runtime and prior to that I could just pass a string of an in-project Array JSON file name through a function.param() and the AJAX will fetch it for me. I intended to use the URL request because it gave me the flexibility to request any project JSON file with a function call.

## Steps to reproduce

1. Create NEW -> Array.json file in the "Files" folder.
2. Write something in the Array editor for this newly created Array.json file.
3. Add AJAX object to project.
4. Add keyboard object to project. (or anything just to trigger an action)
5. Create Event [On Enter key pressed]
6. Add action [AJAX request tag "example", URL "Array.json"]

Additionally you could also make a On AJAX "example" error -> browser.Alert to confirm there's an error.

## Observed result

AJAX error requesting project json file through a string. Only works if it was requested via the "Request project file" action.

## Expected result

Works as in C2 runtime.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r115 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.8 gb
Storage usage (approx): 362 mb (4.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Can you provide a demo project as per the bug report guidelines? It eliminates the possibility of making a mistake following the steps and ending up with a different project to the one you were testing with.

**Comment by jaydonteh** [comment]
I have found the main issue to this. Apparently the AJAX URL throws an error if you request something with a capital letter in the string.

Here's an attached zip file with the C3P file as requested.

[AJAXurlErrorBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2349511/AJAXurlErrorBug.zip)

1. During preview, just hit ENTER to see the browser.alert("ERROR").
2. Switching to C2 runtime and repeat step 1 (You will see it does not have an error).

**Comment by ChadoriRebornXD** [comment]
Yeah. I actually encountered this before. And remembered how the SDK works with **key references**, which are always lower-cased before being passed on, like **Function Names** as an example.
I confronted some other plugin developers on the Construct Community and they guess that it is just how Construct works to avoid case problems and those developers also just follow how the other official addons do it too.

Construct 2 works the same. I don't think it is a bug since all of the external files become lowercase after export. And the **Request URL** is kind of a generalized use. But that is just my opinion on the subject.

## Workaround

You have 3 solutions for this.

**1. Rename all files to a lower case version of their names.** 

![sc1](https://user-images.githubusercontent.com/31282960/45102956-6472f680-b161-11e8-8ea8-b61c7c8feb53.png)

**2. Request by "File" instead of "URL".**

![sc2](https://user-images.githubusercontent.com/31282960/45103010-7eacd480-b161-11e8-87b2-24bad179435a.png)

**3. You can lowercase the filename from the URL input.**

![sc3](https://user-images.githubusercontent.com/31282960/45103056-95532b80-b161-11e8-8789-699999368bd5.png)

**Comment by jaydonteh** [comment]
@ChadoriRebornXD lowercase() is what I'm using currently but I'd prefer C3 to address this as it certainly broke compatibility when I transition to the new C3 runtime. Took me awhile to figure out the issue too.

**Comment by AshleyScirra** [comment]
@ChadoriRebornXD - I think you misunderstood. The issue is this example works in the C2 runtime but doesn't in the C3 runtime.

Fixed for the next release so it also works in the C3 runtime.
