### ISSUE TITLE
Scrollbar doesn't work in animations editor

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#199]
## Problem description

When I zoom on the object, I cannot use the two scrollbars (I can move it but there's no effects)

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. create an animation 
2. zoom on it

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Picoti** [comment]
Hello.
OK. I try in a new empty project and it works..
But when i try it my project, it doesn't work... for all my sprites... is my file corrupted ?

**Comment by DiegoScirra** [comment]
No, I don't think your project is corrupted.

Can you share your project? Or at least a project that demonstrates the problem?

**Comment by Picoti** [comment]
[TEST_01.zip](https://github.com/Scirra/Construct-3-bugs/files/1002662/TEST_01.zip)

**Comment by Picoti** [comment]
Sorry. I closed the issue by mistake.
I send you a zipfile in the post before.

**Comment by Picoti** [comment]
I think I have found the problem.
If I make a new empty project as you say, and create a sprite, there's no problem.
But if I close the Animator editor Sprite and reopen it, the problem is here, I zoom, and the scrollbars doesn't work.

**Comment by DiegoScirra** [comment]
Ah yes, I can see it now. Thanks for figuring that one out, should be easy to fix.

**Comment by DiegoScirra** [comment]
Fixed.

Will be working properly once r28 is released.

Thanks for the help.
