### ISSUE TITLE
R115 c3 runtime - layer bug?

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#1991]
## Problem description

I've tried to reproduce this bug in a blank project but failed so there must be something i'm missing, therefor i've stripped down my project to the basic menu system.

When my menu is open the layer the menu is on becomes visible, then when the user closes the menu the layers opacity is reduced to 0, once that happens the menu should close. It works fine under the c2 runtime but not the c3 runtime.

## Attach a .c3p

[r115c3Layerbug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2349796/r115c3Layerbug.c3p.zip)

delete .zip from filename.

## Steps to reproduce

Load the project, it is currently set to the c2 runtime so you can test it works. Press the z key to open menu then the z key again to close it. You should be able to keep toggling it open and closed.

Now change to the c3 runtime. Press z key to open menu then press z key again to close menu. The menu will not trigger the close because the event to detect the layers opacity is not working.

To test this i added "testVariable" which changes its value as each event line is run. It stops on line 52. Line 53 should read true but it doesn't.

## Observed result

not detecting opacity level

## Expected result

conditional event should detect opacity and close menu.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r115 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 87 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The system 'compare layer opacity' condition wasn't working in the C3 runtime. Thanks for the report, should be fixed in the next release.
