### ISSUE TITLE
[SDK][C3Runtime] There is no reference for a "c3_callfunction".

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1992]
## Problem description

There is no reference for a "**c3_callFunction**". Please add one, thanks.

## Reason

![construct 3 - files](https://user-images.githubusercontent.com/31282960/45064665-9f384880-b0e7-11e8-8ee6-84055d14e19d.png)

It is such a waste supporting **external javascript files** when you can't even let the runtime handle an external callback.

**Comment by AshleyScirra** [comment]
There is one. The function plugin defines both c3_callFunction and c2_callFunction, but as with the C2 runtime, you must include the function plugin in the project since that's what defines them.
