### ISSUE TITLE
Less performance using worker in Chrome 69

### ISSUE THREAD

**Issue by jgp1971** [Scirra/Construct-3-bugs#1994]
## Problem description

While checking C3 in Chrome 69 with a small benchmark, the performance (in fps) when using the worker option is ~5-8 fps less than without the option selected.

## Attach a .c3p

[spawnTest.zip](https://github.com/Scirra/Construct-3-bugs/files/2352137/spawnTest.zip)

## Steps to reproduce

The steps are dependent on the power of the machine at use: just rump up the spawn rate to a number in which chrome starts suffering to maintain 60 fps.

1. Open the project, make sure to uncheck the worker option, run the game and push the spawn rate to 650. In my setup, the project stays between 56-60.
2. Close it, check the worker option and run again. With the same spawn rate of 650, the project stays at around 48-52 fps.
3. (Optional) Change the runtime at use to the C2 runtime and repeat the same tests. With the same spawn rate of 650, the average framerate is 27-29 (yay!).

As I said, the spawn rate needed to observe these results will differ depending on the power of the machine doing the test.

## Observed result

Using the worker decreases performance by a wide margin, compared to the C3 runtime without it active.

## Expected result

Same, or better, performance with the worker active (as understood from this blogpost: https://www.construct.net/blogs/construct-official-blog-1/the-architecture-of-the-construct-3-runtime-911)

## Affected browsers

* Chrome: yes (69)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.81
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
C3 release: r115 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 528 mb (6.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
There's no technical reason for it to be faster or slower in a worker - it's running the same JS code with the same JS engine. I think it's to do with how Chrome schedules frames when under load (when it can't hit 60 FPS). This has showed up in other tests too, e.g. the fillrate test doesn't work properly in worker mode because the dt measurements become inaccurate under load. This was filed as a Chrome issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=877906
I think it needs to be fixed on the Chrome side so we'll wait for that issue to be resolved before investigating further.
