### ISSUE TITLE
Save and close project can cause crash (R115)

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#1995]
## Problem description

Based on the crashlog I first assumed this happens because I haven´t selected/connected a cloudservice yet, but it also happens after I connected to google drive.

## Attach a .c3p

🐎 

## Steps to reproduce

1. Create new project
2. Save to local browser
3. Make any change (e.g. add a sprite)
4. Right click in project bar > close project > save and close

## Observed result

Crash

## Expected result

Not crash

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r115/components/misc/startPage/startPage.js, line 1, col 8387
Message: Uncaught TypeError: Cannot read property 'service' of null
Stack: TypeError: Cannot read property 'service' of null at window.ǃDvd.ǃDiv (https://editor.construct.net/r115/components/misc/startPage/startPage.js:1:8387) at window.ǃDvd.ǃDig (https://editor.construct.net/r115/components/misc/startPage/startPage.js:1:7857) at window.ǃDvd.ǃDnv (https://editor.construct.net/r115/components/misc/startPage/startPage.js:1:7124) at window.ǃDvd.ǃDnP (https://editor.construct.net/r115/components/misc/startPage/startPage.js:1:6344) at Array.ǃn.addEventListener (https://editor.construct.net/r115/components/misc/startPage/startPage.js:1:4764) at ǃM.Event.ǃDec.ǃDeu (https://editor.construct.net/r115/main.js:2:202145) at ǃM.ǃa.ǃH.ǃDTg.dispatchEvent (https://editor.construct.net/r115/main.js:2:200117) at ǃM.ǃa.ǃH.ǃDTg.ǃDzZ (https://editor.construct.net/r115/main.js:2:339305) at ǃDxM.window.setTimeout (https://editor.construct.net/r115/main.js:2:348479)
Construct 3 version: r115
URL: https://editor.construct.net/r115/
Date: Wed Sep 05 2018 16:27:42 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 37.2 s

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r115 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Should be fixed in the next release.
