### ISSUE TITLE
Slow Worker is different then no worker

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1998]
## Problem description

Testing trail spawn every tick, is different when there is worker. With worker every tick is not correct/consistent.

## Attach a .c3p
[LazyWorker.zip](https://github.com/Scirra/Construct-3-bugs/files/2354671/LazyWorker.zip)

## Steps to reproduce

1.Chrome canarly.Open example, preview C3runtime without worker
2.Preview with worker, see trail is not the same. 

## Observed result
Every tick/spawning is somehow different in lenght with worker.

## Expected result
Same as without worker.
Image: No worker VS worker
![worker](https://user-images.githubusercontent.com/28864889/45123418-83788500-b16f-11e8-989a-15b3cb0a530b.jpg)

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3543.0
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3543.0 Safari/537.36
C3 release: r115 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 50 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce in Chrome 69 - looks pretty much the same to me - DOM:
![c69-dom](https://user-images.githubusercontent.com/768723/45153943-b9e4ed00-b1cd-11e8-8b0a-91c359dc208f.png)
Worker:
![c69-worker](https://user-images.githubusercontent.com/768723/45153946-bcdfdd80-b1cd-11e8-834b-e15162bf93d7.png)
You should be aware that Canary can have all sorts of weird quirks - it's probably best only to file issues that happen in Chrome stable or beta, especially since worker mode is now supported in Chrome 69 stable.

**Comment by SnipG** [comment]
I tried it on chrome  dev,beta, canarly, stable. You cannot see different on that small scale. Anyway i made new example, with numbers. And it clearly shows the bug. Without worker. trail part distance is "2.4999" and with worker it 2.55,2.4,2.7. 
I would make chrome issue report myself, but i still have bug that i cannot export C3 without worker. Github just ask some worker.js file. Maybe it caches it from previous export if it had worker or something.
[0004.zip](https://github.com/Scirra/Construct-3-bugs/files/2357265/0004.zip)
Without Worker
![withoutworker](https://user-images.githubusercontent.com/28864889/45161358-5de18f00-b1f4-11e8-9420-b03075377a42.jpg)
Made with stable.
With Worker
![withworker](https://user-images.githubusercontent.com/28864889/45161367-620dac80-b1f4-11e8-8ba3-54432502f4bf.jpg)

**Comment by AshleyScirra** [comment]
The movement of the behavior depends on dt, and crbug.com/877906 indicates that in worker mode the dt measurements are incorrect, so I think it's just a different manifestation of the same bug.

**Comment by SnipG** [comment]
I added yesturday this example to that bug report. 
Today i tried different browers and tested this example there aswell.
Opera exactly same as chrome.
Mozilla bugged.
![firefox](https://user-images.githubusercontent.com/28864889/45549146-69a20680-b82f-11e8-8047-575b0dbf37f6.jpg)

Edge bugged.
![edge](https://user-images.githubusercontent.com/28864889/45549158-758dc880-b82f-11e8-9cf1-392ffb0fc0e8.jpg)

Mozilla and edge both appear to have very similar behavior. Not like chrome with worker. So this could not  be a bug. It just appears Construct occasionally goes out of sync. Not sure how this affects Construct overall, when using those browers and dt.
![mozilla edge](https://user-images.githubusercontent.com/28864889/45549239-d0bfbb00-b82f-11e8-9e25-49243cf89ad2.jpg)
