### ISSUE TITLE
Can Undo/Redo Non-runtime Layout Properties: Editor

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#2]
## Problem description
Just like the issues of "Show Collision Polygons" and "Show Translucent Inactive Layers" filed for r15, now r16 added the "Show grid" and "Snap to grid" interferes with the history of undo/redo with no effect. This should not be the case as a non-runtime action.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Check "Snap to Grid" option.
2. Undo
3. Redo

## Observed result
Action is perceived already undo/redo but no changes really has made.

## Expected result
Should not even be part of the undo/redo history log. Also, for "Show Collision Polygons" and "Show Translucent Inactive Layers" they do have actions get undo/redo, but the point is should not be even part of the undo/redo history log.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

**Comment by AshleyScirra** [comment]
Assigning to Diego - I think we'll standardise on what C2 does, i.e. UI state properties are not included in undo.

**Comment by DiegoScirra** [comment]
Fixed.

As of r18, no property listed under the "Editor" group in the properties bar can be undone. This applies for projects, layouts and layers.
