### ISSUE TITLE
Platform Behavior "Start/Stop ignoring INPUT" doesn't work on C3 runtime

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#2003]
## Problem description

Platform Behavior "Start/Stop ignoring INPUT" doesn't work on C3 runtime

## Attach a .c3p

[Ignoring_input_BUG.zip](https://github.com/Scirra/Construct-3-bugs/files/2357513/Ignoring_input_BUG.zip)

## Steps to reproduce

Look at the attached C3P and try it on C3 runtime and C2 runtime

## Observed result

It doesn't work on C3 runtime

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
