### ISSUE TITLE
Updating text object, blocks sprite spawn, but with debug step it will be spawned

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2004]
## Problem description

Not sure if bug.
Happens with both C2runtime and C3runtime.
Bullet second trail piece will not be spawned. If you use debug step in c2/c3runtime it will be. 
Issue that produces this problem should need checking.

## Attach a .c3p
[0006MissingSpawn.zip](https://github.com/Scirra/Construct-3-bugs/files/2357903/0006MissingSpawn.zip)

## Steps to reproduce

1.Preview example in c2, let circle go outside layout. 
2.See bullet will not spawn second trail piece.
3.Preview in c3runtime, see same behavior.
4.Now test it with debug stepping. Second piece will spawn.

## Observed result
Updating text will block second piece spawn. Same thing happens in chrome beta. If you change window size, which affects GPU and CPU, still sprite won`t spawn.

## Expected result
Should work like debug stepping.
C2runtime
![c2_01](https://user-images.githubusercontent.com/28864889/45171800-0e0ec200-b20c-11e8-9738-4193ad141b59.jpg)
C3runtime
![c301](https://user-images.githubusercontent.com/28864889/45171805-123adf80-b20c-11e8-940c-8ed16c378a14.jpg)

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.81
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
C3 release: r115 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 469 mb (3.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The project essentially visualises delta-time: any frame skips are visible as a gap in the trail. When the object goes outside the layout, it janks because it does a long loop updating the Text object with a lot of text, which then runs word wrap on the text, rasterizes the text to a canvas, and then uploads the canvas as a WebGL texture for rendering - all pretty expensive, and enough to cause a 1 frame jank.

When you step the debugger, there is no immediately previously rendered frame timestamp to use to calculate delta-time, so it simply hard-codes a delta-time of 16.6666... milliseconds, so you step *as if* the framerate is an unbroken 60 FPS. Therefore you cannot observe any jank issues when using debug stepping, because it's not actually using any real delta-time measurements.
