### ISSUE TITLE
[Beta] Deduplicating images on empty project fail

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#201]
## Problem description

Stuck at deduplicating images forever when there isn't any images in the project. This was found by user chadorireborn on the forums.

## Steps to reproduce

1. Export an empty project.
2. Select the option for deduplicating images.

## Observed result
Infinite deduplicating images process.

## Expected result
Should throw an error to user or disable the option.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, fixed for r28.
