### ISSUE TITLE
Gamepad doesn't work with Chromium 69

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2012]
## Problem description

The gamepad plugin is not working anymore if you export the game using the lastest version of Chromium (69).

## Attach a .c3p

[gamepad_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2363945/gamepad_bug.zip)

## Steps to reproduce

1. Export the project using the Chromium 69.
2. Try to move the player by using the controller dpad.

## Observed result

The game doesn't recognize the controller input.

## Expected result

The game to recognize the controller input.

## Affected browsers

* Chrome: no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here, everything still working fine even after a minified export with Chrome 69. Did you include all the necessary information to reproduce the issue?

**Comment by BonzerKitten7** [comment]
Yes, you only need to export it using Chrome 69 and the C2 runtime. I tried it again today, but no success, i was still only able to move the player with Chrome 68. I'll send the exported file to a few friends and see if it's a problem on my side.

**Comment by BonzerKitten7** [comment]
Sorry, it's a problem on my side, my friends said that the controller worked perfectly on theirs PCs, this issue can be closed.

**Comment by jgp1971** [comment]
Just not to open another issue, since it's the same problem: I also have this issue when exporting with NWJS 0.33. 0.32 and older work perfectly.
