### ISSUE TITLE
NWJS error message after changing chromium version

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2013]
## Problem description

I needed to use an older version of Chromium because the Greenworks plugin doesn't support the latest one, but now everytime i start my game i get an error message from NWJS, which is very annoying, i can still play the game, but the message always appear. I believe the message is related to the local storage plugin or something like that.

https://i.imgur.com/obmgd0m.png

## Attach a .c3p

[error_message.zip](https://github.com/Scirra/Construct-3-bugs/files/2363955/error_message.zip)

## Steps to reproduce

1. Export the project with Chromium 69
2. Open the exported project and save any value
3. Export the project with Chromium 66
4. Open the exported project and check the error message

## Observed result

An error message appears when you start the exported project.

## Expected result

No error messages.

## Affected browsers

* Chrome: no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It is NW.js that is showing the prompt so this isn't something we can help with. You could post it to the NW.js tracker, but I suspect they will just say Chromium doesn't support downgrading versions.

You can probably remove the message by clearing all the storage for the app - delete its folder in %appdata%.

**Comment by BonzerKitten7** [comment]
Actually there's a way for you to help me with this problem, if you update the Greenworks plugin to work with a newer version of Chromium i can export the game using 68 or 69, so the error message will not appear for the Steam players when they launch the game.

I don't think it's viable to ask all Steam players to do go to their %appdata% and delete their save and play all the 100 levels again. :(

BTW, where exactly i can clear the local storage? I couldn't find anything related to Construct or NWJS at %appdata%.

**Comment by AshleyScirra** [comment]
We've already updated the Greenworks plugin to the latest release: https://github.com/greenheartgames/greenworks/releases - they need to release an update themselves first for us to support any newer versions.

The folder in %appdata% will have the name of your project.

**Comment by BonzerKitten7** [comment]
Yes, it uses the lastest version of the SDK (1.42) but it not compatible with the latest version of NW.js (v0.33.0), it's only compatible with an older version (v0.30.4). If you update the Greenworks plugin i'll be able to add it to my project (https://store.steampowered.com/app/917290/Duck_Souls/) and avoid the annoying NW.js error message. :)

That's weird, i couldn't find any folder with the name of my project. :(
