### ISSUE TITLE
Crash by copying an image point name from one project and pasting it into a different project

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2014]
## Problem description

I had 2 different projects opened and I was copying some info from one to another. When I pasted the name of an image point from a sprite from one project to another, the 2nd project crashed, 100% repo. I used Yandex for the project I was copying from and desktop version on the other, doubt this matters though.

## Attach a .c3p

Use Glokar and KiwiStory

Check video
[2018-09-09_18-18-28.zip](https://github.com/Scirra/Construct-3-bugs/files/2364382/2018-09-09_18-18-28.zip)

## Steps to reproduce

1. Open up Glokar
2. Open up KiwiStory
3. Open the player ship in Glokar
4. Double click an image point to enter rename mode
5. CTRL+C the name
6. Go to Kiwi Story
7. Make new image point on whatever sprite
8. CTRL+V

## Observed result

Crash

## Expected result

-

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Unexpected token G in JSON at position 0 @ SyntaxError: Unexpected token G in JSON at position 0 at JSON.parse () at ǃI.ǃrr.ǃDC.ǃI.ǃrGN.ǃTw.then (https://editor.construct.net/r111/main.js:80:912687)
Stack: SyntaxError: Unexpected token G in JSON at position 0 at JSON.parse () at ǃI.ǃrr.ǃDC.ǃI.ǃrGN.ǃTw.then (https://editor.construct.net/r111/main.js:80:912687)
Construct 3 version: r111
URL: https://editor.construct.net/
Date: Sun Sep 09 2018 18:18:32 GMT+0300 (Eastern European Summer Time)
Uptime: 21.9 s

Platform information
Browser: NW.js
Browser version: 0.31.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.3541666269302368
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@878cd31214ac27a3996927cd5c9c138b10c9fc8d) NWjs/0.31.2 (like Chrome/67.0.3396.87)
C3 release: r111 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release.

It was a desktop only bug :P
