### ISSUE TITLE
[C3 runtime] [r115] - Export to Desktop (NW.js): ERR_FILE_NOT_FOUND (workerMain.js)

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#2015]
## Problem description

When I try to execute an exe from "_export to Desktop (via NW.js)_", the result is a dark window. In the DevTools I can see an error:

`workerMain.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND`

## Steps to reproduce

See this video: 

[![Construct 3 beta - bug cloning FORM CONTROLS
](https://img.youtube.com/vi/n-kefjmg9QU/0.jpg)](https://www.youtube.com/watch?v=n-kefjmg9QU)

1. Create a new project
2. Set *Runtime Construct 3*
3. Export to NW.js
4. Execute the nw.exe

## Observed result

A dark window

## Expected result

The app should work.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.81
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
C3 release: r115 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 450 mb (3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
We've fixed a bunch of export issues with the C3 runtime in the next release, I think it will be fixed then.

**Comment by AshleyScirra** [comment]
r116 is out now, can you verify it works with that?

**Comment by el3um4s** [comment]
Thank you, it seems to be working 😄

**Comment by AshleyScirra** [comment]
Great, thanks for confirming!
