### ISSUE TITLE
Invoke Download will [not] open in IE or Edge [Microsoft]

### ISSUE THREAD

**Issue by DrathVader** [Scirra/Construct-3-bugs#2016]
## Problem description

Invoke Download (CanvasSnapshot) as well AJAX FileChooser (FileChooser.FileURLAt(0)) will not open the File Menu.

Actions/Events Screenshot: 
URL: **s22.postimg.cc/agghi4tcx/C3_Save.jpg**

## Attach a .c3p
C3p Project File: 
URL: **1drv.ms/u/s!AnjqkTqN7TavhOY61wBt05G0Zu4yYg**

## Steps to reproduce

Microsoft EDGE only:
1. Click PNG button
2. Click JSON button

## Observed result

1. Click PNG button
- Result: HTML1300: Navigation occurred.
- Download triggers in console but wont open file/download window

2. Click JSON button
- Page resets/reloads

## Expected result

1. Click PNG button
- PNG screenshot should download

2. Click JSON button
- Saved State Json should download

## Affected browsers

* Chrome: no
* Firefox: no
*** Edge: yes**
* Safari: Unknown (Mac Unavailable to test)

## System details

NO error in console. 

`HTML1300	"Navigation occurred"	A new page was navigated to, or the current page was refreshed.	This is an informational message and not an error.`

<details><summary>View details</summary>
</details>

**Comment by AshleyScirra** [comment]
I think there are two issues here:

- some browsers don't let you start a download outside of a user input event, e.g. "on button clicked". Since you try to start the download in "on canvas snapshot" which is not a user input event, the download may be blocked. So to test whether this works you probably need to make sure the download starts in another user input event, e.g. using another button.

- having made that change, it still doesn't seem to work, which I think is some kind of bug with Edge. You'll need to report that here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

**Comment by DrathVader** [comment]
Ashley,

Thank you for the feedback. I also had the same issues even with additional buttons for each event as well all in one. Works in other browsers not Edge.

However I am able to save "canvas" screenshots with Javascript other than Construct 3 Canvas.

Please see working Edge examples below:

- Working example in Edge with download prompt: https://eligrey.com/demos/FileSaver.js/
- Another example with plain JS but requires right click save: https://jsfiddle.net/codepo8/V6ufG/2/

However I am unable to get this JS method to work with Construct's Canvas element. It would be a reasonable alternative since the likelihood of Microsoft ever fixing that bug is unlikely.

**Comment by AshleyScirra** [comment]
Alright, I made a few tweaks to use code more similar to FileSaver.js and it seems to help. Note you need to make sure "Invoke download" is done in a user input event and use a valid filename (the canvas snapshot filename is just "screenshot", but should be "screenshot.png" instead). This is done for the next release.

**Comment by DrathVader** [comment]
Ashley,

Thanks for the feedback.  As for the "JSON download". Would this behave the same as the Invoke Download for a "screenshot"?

**Comment by AshleyScirra** [comment]
Yes, they do the same thing.
