### ISSUE TITLE
Facebook Instant Game Ads - Can't Specify Ad Type to Play

### ISSUE THREAD

**Issue by KENYONBcom** [Scirra/Construct-3-bugs#2017]
## Problem description

There is no event to specify which type of ad shows.
The only option is "Show Ad".

We should have the option to show Interstitial or Reward ad like we can with MobileAdvert plugin.

**Comment by AshleyScirra** [comment]
Please post suggestions here: https://construct3.ideas.aha.io/

**Comment by KENYONBcom** [comment]
Done. https://construct3.ideas.aha.io/ideas/C3-I-563
