### ISSUE TITLE
[C3 runtime] Crash on stepping a breakpoint

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#2019]
## Problem description

After a breakpoint is triggered, the "Step" button is enabled for user to do stepping. But it shows weird results while stepping; almost anything randomly has a breakpoint. After a few steps, Construct crashes.

## Steps to reproduce

1. Open any example project files, ie. KiwiStory
2. Set it to C3 runtime.
3. Add a breakpoint to "On start of layout".
4. Debug preview.
5. Breakpoint should trigger a pause. Now press the "Step" button multiple times.

## Observed result

Random events are highlighted as a breakpoint and this never ends until a crash happens.

I can't seem to replicate the crash outside of my project file. The KiwiStory project that I've tested never crashes after multiple clicks on the step button.

## Expected result
No crash and no breakpoints on other events. To be honest, I'm not even sure if the breakpoint feature were intended to behave this way.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r116/components/editors/eventSheetView/eventSheetView.js, line 1, col 39111
Message: Uncaught TypeError: Cannot read property 'ǃSA' of null
Stack: TypeError: Cannot read property 'ǃSA' of null at window.ǃVV.ǃmv (https://editor.construct.net/r116/components/editors/eventSheetView/eventSheetView.js:1:39111) at window.ǃbVp.ǃbVW (https://editor.construct.net/r116/exporters/preview/exporter.js:1:28475) at window.ǃbqU.ǃbVn.ǃbqj (https://editor.construct.net/r116/exporters/preview/exporter.js:1:23007) at window.ǃbqU.ǃbec (https://editor.construct.net/r116/exporters/preview/exporter.js:1:4166) at MessagePort.messageport-received.n.ǃbqT.onmessage (https://editor.construct.net/r116/exporters/preview/exporter.js:1:2994)
Construct 3 version: r116
URL: https://editor.construct.net/r116/
Date: Mon Sep 10 2018 21:05:23 GMT+0800 (Malaysia Time)
Uptime: 53.2 s

Platform information
Browser: Chrome
Browser version: 69.0.3497.81
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
C3 release: r116 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here. It is not highlighting random events - it appears to be correctly highlighting triggers and events in the order the engine is executing. Further, despite pressing 'Step' a lot as quickly as possible, I could not reproduce any crash. Please file again if you can find a way to reliably reproduce the issue.
