### ISSUE TITLE
[r27] Remove global objects from project crash

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#202]
## Problem description

Create an object that cannot be created as an instance on a layout. Then removing the object would result in a crash. This is a heck of a game jam challenge.

## Steps to reproduce

1. Create an object such as Array object.
2. Remove from project.

## Observed result

Crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃP.ǃD (https://editor.construct.net/r27/main.js:2:201555) at window.ǃGW.ǃRE (https://editor.construct.net/r27/components/bars/zOrderBar/zOrderBar.js:1:13004) at Array.ǃRa.k (https://editor.construct.net/r27/components/bars/zOrderBar/zOrderBar.js:1:1221) at ǃP.Event.ǃfbj.ǃfbt (https://editor.construct.net/r27/main.js:2:285256) at window.ǃsvL.dispatchEvent (https://editor.construct.net/r27/main.js:2:283648) at window.ǃsvL.ǃtR (https://editor.construct.net/r27/main.js:161:40092) at te.ǃPIX (https://editor.construct.net/r27/main.js:61:205424) at te.ǃPI$ (https://editor.construct.net/r27/main.js:61:68641) at te.ǃPI$ (https://editor.construct.net/r27/main.js:61:205218) at ie.ǃPI$ (https://editor.construct.net/r27/main.js:61:159093)
Stack: TypeError: unexpected type at Function.ǃP.ǃD (https://editor.construct.net/r27/main.js:2:201555) at window.ǃGW.ǃRE (https://editor.construct.net/r27/components/bars/zOrderBar/zOrderBar.js:1:13004) at Array.ǃRa.k (https://editor.construct.net/r27/components/bars/zOrderBar/zOrderBar.js:1:1221) at ǃP.Event.ǃfbj.ǃfbt (https://editor.construct.net/r27/main.js:2:285256) at window.ǃsvL.dispatchEvent (https://editor.construct.net/r27/main.js:2:283648) at window.ǃsvL.ǃtR (https://editor.construct.net/r27/main.js:161:40092) at te.ǃPIX (https://editor.construct.net/r27/main.js:61:205424) at te.ǃPI$ (https://editor.construct.net/r27/main.js:61:68641) at te.ǃPI$ (https://editor.construct.net/r27/main.js:61:205218) at ie.ǃPI$ (https://editor.construct.net/r27/main.js:61:159093)
Construct 3 version: r27
URL: https://editor.construct.net/index.html
Date: Mon May 15 2017 22:05:15 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 3910.2 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by jaydonteh** [comment]
@DiegoScirra This is breaking the current game jam for me. Hope it is fixed by the next release!

**Comment by DiegoScirra** [comment]
Fixed in r28.

Hope you can continue working.
