### ISSUE TITLE
[Website] Buying C3 License with PayPal doesn't work (running for hours - nothing happens)

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#2021]
## Problem description
I'm trying to buy a C3 license with paypal, but it's stuck at "Your order is being processed - Paypal can be a little slow at times" etc. for 4 hours now.

I tried it yesterday too (then closed the tab after 6 hours or something) - nothing has been substracted from my paypal though.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Please contact support@scirra.com for assistance with payments. Otherwise, website issues should be filed here instead: https://github.com/Scirra/Construct.net-website-bugs
