### ISSUE TITLE
C3 Runtime.  Fullscreen positioning scaling issues in 116

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2022]
## Problem description

related to closed issues
#1988
#2018

The issue has not changed as far as I can see.

I slightly modified the C3P to be clearer.

Note the project full screen mode is set to letterbox scale

Keys 2 3 4 change the canvas size to  1080/1920 - 702/1664 - 600/800 , 
then centers the camera to the relevant sprite
then request fullscreen  (centered)

Key 1 cancels full screen

For each key you should see a change in resolution and see the complete red borderof the relvant sprite with the correct window resolution written badly in the bottom left corner. 

For a 16:9 monitor, It should be letter box for the 702/1664  and side bars for the 800 600 and perfect for the 1080 res. 

If you dont see a complete red border (centered and letterboxed or sidebarred) as well as the display resolution written in the corner then something is wrong with positioning or scaling.

(edit) please note I just noticed that you commented on #2018 that centered does not scale.    I think this is what you were also  saying in #1988 that C2 behaviour is incorrect. (even if the project setting is letterbox scale???)  

However even changing the attached c3p events to fullscreen letterbox scale still gives incorrect results.

## Attach a .c3p

[Fullscreen Issues 2.zip](https://github.com/Scirra/Construct-3-bugs/files/2367159/Fullscreen.Issues.2.zip)

## Steps to reproduce

Run the cp3 in C2 runtime press 2 , 3, 4, 1  

then do the same in C3 runtime

## Observed result

C2 runtime allways displays the sprites with full red border
C3 runtime is all over the place.

## Expected result

as per C2 runtime.

## Affected browsers

* Chrome: tested only.

**Comment by AshleyScirra** [comment]
There are two issues here:

- the 'Scroll To' behavior 'Set enabled' action isn't working in the C3 runtime

- this example uses request fullscreen 'Centered' again, which works correctly in the C3 runtime but incorrectly does letterbox scale in the C2 runtime. This has caused a fair amount of confusion already so I've gone back and fixed this in the C2 runtime as well.

Both are fixed for the next release.
