### ISSUE TITLE
C3 Runtime - Lens2 Effect + Opacity change. Heavy unwanted Screen distortion

### ISSUE THREAD

**Issue by EngBraga** [Scirra/Construct-3-bugs#2025]
## Problem description

I am willing to migrate my current C3 Project to the new C3 Runtime. The only thing holding me is the Lens WebGL Effect that I use to simulate an explosion Shockwave.
Everything was running as intended with Lens+C2 Runtime. Unfortunatelly, this effect is not supported by the new C3 Runtime.

So I disabled the Lens Effect, Switched to the C3 Runtime, and Added the Lens2 updated effect.

The effect is added on a sprite that increase its size every tick, and after a certain size is faded out.

In the new Runtime+Lens2 effect, I noticed that instead of just smoothly fading out the sprite, when the opacity is decreased, the system zooms in on the entire Shockwave Sprite bounding box (this never ocurred with the original Lens effect).

The images show the problem.

![lens2](https://user-images.githubusercontent.com/12936132/45317672-0d7a7200-b511-11e8-9d0e-945f1a63c133.jpg)
![lens](https://user-images.githubusercontent.com/12936132/45317673-0e130880-b511-11e8-8c3b-8852d3bbe21e.jpg)

Attached are the links for two C3p projects, with the same events, differing only by the Runtime and version of Lens Effect.

Just click on screen to spawn a shockwave.

Tested on:

* Chrome: yes
* Firefox: yes
* Edge: no
* Safari: no

https://drive.google.com/open?id=15zV8i_AizO0OfOKDG7Qw2gny5YHeZErE
https://drive.google.com/open?id=140Uzszkc6ixbW48AM0ESCyYcvrmfYQPD

**Comment by AshleyScirra** [comment]
The effects compositor is super complicated so it's hard work to deal with issues like this, but I think it's all sorted - hopefully - for the next release.
