### ISSUE TITLE
Windows exporter issue

### ISSUE THREAD

**Issue by MrWonka** [Scirra/Construct-3-bugs#2027]
## Problem description

Upon exporting my project using the windows exporter, then testing it in visual studio the app gets stuck loading at 100%. It does not make a difference what browser I use nor whether or not script minify is enabled. I had no issues prior to r116 using the construct2 runtime, now using the construct3 runtime and r116 my app has been having issues. It works fine in browser preview. I suspect it has something to do with a plugin, as I was unable to achieve the same issue using a blank project. 

## Affected browsers

* Chrome: yes/no
* Firefox: yes
* Edge: yes
* Safari: yes/no

**Comment by AshleyScirra** [comment]
No project provided so tested with Ghost Shooter. Can't reproduce. Please follow the bug report guidelines to ensure your report can be investigated.
