### ISSUE TITLE
[Firefox] Edge layout touch fix broke firefox touch.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2028]
## Problem description

Problem described in this issue now applies to firefox instead. 
https://github.com/Scirra/Construct-3-bugs/issues/1760

In Layout view:
2 finger input should pan/zoom
1 finger input should draw selection rectangle.

## Attach a .c3p

N/A

## Steps to reproduce

1. Open construct r116 in Firefox.
2. Try the layout view touch input (pan zoon selection rectangle)
3. Firefox does not seem to register the second touch.

## Observed result

Touch input in layout view broke in latest release. (r116)

## Expected result

Should work exactly like in previous releases in firefox, and chrome.

## Affected browsers

* Firefox: yes

**Comment by AshleyScirra** [comment]
This looks like a Firefox bug where it incorrectly assigns different touches the same ID, so it's impossible to tell them apart. I've implemented a workaround for the next release (essentially reverting to what r115 did but only for Firefox).
