### ISSUE TITLE
Splash dialog referenced "Invalid Date"

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#203]
![invaliddate](https://cloud.githubusercontent.com/assets/4206641/26062099/bd638fda-393e-11e7-9cc2-6106843de4ae.jpg)
## Problem description

Bad date in Gamejam popup.

## Attach a .c3p

none

## Steps to reproduce

1. start r27

## Observed result

<attached>

## Expected result

.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

</details>

**Comment by jaydonteh** [comment]
So we getting endless license to Construct? 💯 👍 :trollface:

**Comment by AshleyScirra** [comment]
The end date comes from the server which needs an update. This should be resolved shortly when @TomGullen updates the site.

**Comment by AshleyScirra** [comment]
Server was updated, should be working now.
