### ISSUE TITLE
double Right/Middle click does not trigger 

### ISSUE THREAD

**Issue by SalmanShhh** [Scirra/Construct-3-bugs#2030]
## Problem description

double Right/Middle click does not trigger 

## Attach a .c3p

https://cdn.discordapp.com/attachments/225550155531812865/489114266948075552/doubleClick_rightClick_BUG.c3p

## Steps to reproduce

1. set bullet speed on double right click
2.
3.

## Observed result

bullet doesn't move. changing it to single click or left double click makes it work.

## Expected result

the bullet sprite to move.

## Affected browsers

C3 Desktop application 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@032b3ca19e9af20182f9bd03deefc0faf4695558) NWjs/0.33.0 (like Chrome/69.0.3497.81)
C3 release: r116 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 302 gb
Storage usage (approx): 6.6 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks like out of Chrome, Firefox and Safari, Firefox is the only browser that actually fires dblclick events for middle and right mouse buttons. So this is either a browser bug with both Chrome and Edge, or maybe the spec got changed at some point and it's not supported any more for any button other than left... I'll file some browser bugs and see what they say.

**Comment by AshleyScirra** [comment]
Filed browser bugs:
Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=883351
Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18972037/
Will follow up there.
