### ISSUE TITLE
Windows export bug v2 (r116 c3 runtime)

### ISSUE THREAD

**Issue by MrWonka** [Scirra/Construct-3-bugs#2031]
## Problem description

Holy crap this took a while to figure out. 

If a project is formerly in construct 2 runtime using physics, then converted to c3 runtime, exported visual studio and then run, it will not start. 

## Attach a .c3p

N/A

## Steps to reproduce

1. Open the catapult demo
2. Convert to c3 runtime
3. export to visual studio
4. Test app, black screen/stuck at 100%

**Comment by NetOneGames** [comment]
maybe related to #1981

**Comment by AshleyScirra** [comment]
I can reproduce this with a normal minified HTML5 export so I don't think it's anything to do with the Windows exporter

**Comment by AshleyScirra** [comment]
Found an issue with minifying physics behavior in C3 runtime. Should be fixed in next release.
