### ISSUE TITLE
Maximum call stack size error

### ISSUE THREAD

**Issue by Jayed2016** [Scirra/Construct-3-bugs#2032]
## Problem description

<The game was running or being previewed smoothly but after just adding one or two lines of code there was blank screen while previewing. And if I try debugging then I get "Maximum call stack size error" first then the game runs for a few mins.>

## Attach a .c3p
[Project1.5.zip](https://github.com/Scirra/Construct-3-bugs/files/2372735/Project1.5.zip)

## Steps to reproduce

1. First, open the project
2. Try to preview the project
3.

## Observed result

Only black screen

## Expected result

Getting the view of the game

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is probably just a mistake in your events that results in an infinite sequence of triggers (e.g. creating an object in 'On created'). Please see the bug report guidelines which explain how to make a minimal project. Your project also uses third-party addons which we do not normally support.
