### ISSUE TITLE
 Fullscreen on Chrome (Mac) keyboard input doesn't function, r116b runtime 3

### ISSUE THREAD

**Issue by dolomite** [Scirra/Construct-3-bugs#2033]
## Problem description

On the Mac Chrome 69.0.3497.92 (64bit), using runtime 3 r116b. *Worker IS enabled*
- When requesting fullscreen from in game - nothing happens.
- When manually maximizing the window to fullscreen - all inputs to game no longer functions

When worker is turned off, fullscreen requests works. Inputs to game works.

This only appears to be isolated to only the Chrome browser on the Mac, other browser like Firefox and Safari are fine. Everything works fine on the PC.

## Attach a .c3p

[full_screen_test.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2373505/full_screen_test.c3p.zip)

## Steps to reproduce

1. Run project on Chrome 69.0.3497.92 on an Apple Mac.
2. Request fullscreen by pressing Q on the keyboard. Noticed full screen doesn't work.
3. Manually maximize the game window. Notice keyboard input (arrows keys) now don't work.
4. Exit game and disable Worker.
5. Run project again on Chrome 69.0.3497.92.
6. Press Q and notice it actually works. 
7. Press Q again to return to normal size.
8. Maximize the window. Notice keyboard input still works.

## Observed result

When worker is enable, fullscreen request doesn't work and keyboard input doesn't work when screen is maximize.

## Expected result

Fullscreen request should work and keyboard input should always work when window is maximize.

## Affected browsers
On Mac : 
* Chrome: yes
* Firefox: no
* Safari: no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.92
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
C3 release: r116 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 785 mb (4.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
There are currently two known issues with Chrome using worker mode:

1) user-input limited commands like requesting fullscreen don't count as being in an input event in worker mode - this is being worked on by Google
2) resizing the window freezes the game - already fixed for a future Chrome release
