### ISSUE TITLE
Float does not allow to convert a text input to numerical value properly

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2034]
## Problem description

Trying to use float() to convert a written text (numbers) in Text Input to a numeric value (store in a global variable) only results in a value of 0 instead of the actual input value.

## Attach a .c3p
https://kyatric.com/c3/bugs/2018.09.12.float_results_0.c3p (made with r111, found in r116)

## Steps to reproduce

1. Preview the project
2. Input 123 in the text input
3. Click OK

## Observed result

The text object displays 0; Variable1 value is 0

## Expected result

The text object to display 123; Variable1 value to be 123

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: not tested
* Safari: not tested

Very confusing as this is something I've often used to do this sort of things.
Happens in both C2 & C3 runtime.
No notification in the browser's console.

**Comment by AshleyScirra** [comment]
It's just a typo: you probably intended to do `float(TextInput.Text)` but you wrote `float(Text.Text)`.

**Comment by Kyatric** [comment]
Indeed !
Sorry about that.
