### ISSUE TITLE
Build Fail - Unable to write project to disk

### ISSUE THREAD

**Issue by budochick** [Scirra/Construct-3-bugs#2035]
## Problem description

Attempting to export as an Android debug apk.  Unsuccessful on both Chrome and Safari browsers, with the same error message: "Build Failed - unable to write project to disk".  

## Attach a .c3p

[FontTester.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2378734/FontTester.c3p.zip)

## Steps to reproduce

1. Project -> Export -> Android -> Debug APK  
2. Deduplicate, Recompress & Minify checked  
3. Min version 5+, hide status bar checked

Using version r116

## Observed result

Appears to perform build until the end and the error message pops up.  

## Expected result

Error message: "Build Fail - Unable to write project to disk"  

## Affected browsers

* Chrome: yes
* Firefox: n/a
* Edge: n/a
* Safari: yes

## System details

<details><summary>View details</summary>

PASTE HERE
<img width="351" alt="screen shot 2018-09-13 at 7 05 52 am" src="https://user-images.githubusercontent.com/32998680/45454114-1beda700-b726-11e8-939c-998edf2796ed.png">

</details>

**Comment by dop2000** [comment]
I'm having this issue too! The project doesn't matter, I tried with a blank layout and no events. Same error in the desktop and web versions of C3. 
Only the "Cordova project" option works, any APK exports fail.

**Comment by gloater** [comment]
I'm having this issue too!

**Comment by Teymur969** [comment]
I'm having the same issue right now.

**Comment by AshleyScirra** [comment]
Apologies for the inconvenience - we are currently looking in to this.

**Comment by AshleyScirra** [comment]
The issue should be corrected now, and I just ran a successful debug APK build. Can others affected verify it works for them?

**Comment by Bootfit** [comment]
Yep - works again for me now. Good stuff 👍

**Comment by budochick** [comment]
Hi, It works!  Thank you!! 👍

**Comment by AshleyScirra** [comment]
Thanks for confirming!
