### ISSUE TITLE
[C3 Runtime][R118] Android ads don't work

### ISSUE THREAD

**Issue by cmr333** [Scirra/Construct-3-bugs#2036]
## Problem description

Android ads don't work (test mode) for C3 runtime on latest r116 build.
(I don't know if this is the same for un-test mode)

-----------------------------------

EDIT: I tried on R117.2 as well, same result.

------------------------------

EDIT 2: Tried on R118, still doesn't work. (This time I tried non-test mode and still nothing) (I also added the privacy URL into admob properties just in case the C3 runtime works differently but still nothing)

## Attach a .c3p

[test (1).zip](https://github.com/Scirra/Construct-3-bugs/files/2396784/test.1.zip)

## Steps to reproduce

1. Create admob object (test mode)
2. Add onto event sheets (Mine is on layout startup > create banner advert (admob data))
3. Add admob data to admob object
3. Switch to C3 runtime (via advance settings)
4. Export to Android

## Observed result

I thought I would try C3 runtime for first time and use it to patch my game in beta (also would like to point out that your sava data gets removed when switched from C2 to C3 runtime) and everything was going fine until I noticed I wasn't getting adverts anymore.

However, when going back to C2 runtime with same patch, the adverts will appear back and then removed again when I patched the game again with C3 runtime.

I also tried checking and unchecking all 3 options before export (minify script, comrpess images etc) on C3 runtime and still same result.

(I don't know if un-checking the test mode will make it work)

## Expected result

I expected adverts to appear on C3 runtime.

## Affected browsers

N/A

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.92
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
C3 release: r116 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 396 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by ERAgames777** [comment]
#2045

**Comment by cmr333** [comment]
I just tried creating a new test file for myself to try and recreate the bug with further understanding.

I can send the test .c3p file via secure method if you wish to do so. (The file contains my admob data and the bug doesn't work without it, I don't feel safe giving that data out to the public)

I created a new test file with my admob data and I had same results of C2 runtime admobs working and C3 runtime isn't.

Thank you for your time.

**Comment by shortercode** [comment]
Looking at the runtime now, and I've found a few bugs anyway. Fixing these then can verify if it's the same issue with your project.

Could you replace the number within the ID values with "x" like so: `ca-app-pub-xxxxxxxxxxxxxxxx~xxxxxxxxxx` then share the project? I can test with my own admob credentials.

**Comment by cmr333** [comment]
Updated the post to include the simple test file of the bug with the numbers replaced as requested

(This was the test file recreated with my admob data to cause the same bug from my main project)

**Comment by shortercode** [comment]
Not sure if this was just a copy paste error but you put `pub-xxxxxxxxxxxxxxxx~xxxxxxxxxx` for your publisher ID, which should look like `pub-xxxxxxxxxxxxxxxx`. Just checking my changes with your project.

**Comment by shortercode** [comment]
Okay cool looks like you project works with my changes, I'm going to commit the changes now. Should be available in the next beta release.

Thanks for the report!

**Comment by cmr333** [comment]
Ah my apologies, I just copy pasted the x's. I should've done them manually to replace the numbers.

I'll look forward to the next beta release!

Thank you and have a wonderful day

**Comment by shortercode** [comment]
Not to worry, that's what I thought had happened. Just wanted to make sure you had it right for your actual game.

Hope you have a great day too!
