### ISSUE TITLE
Can't "connect" to r117

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2037]
## Problem description

Ahhhh nuts!
WE COULDN'T FIND THAT!

When trying to access https://editor.construct.net/r117/ or update from r111 to r117 in the added to desktop version.

## Attach a .c3p

No need

## Steps to reproduce

1. Try to access https://editor.construct.net/r117/ in a browser
2.
3.

## Observed result

Ahhhh nuts!
WE COULDN'T FIND THAT!

## Expected result

R117 editor

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: not tested
* Safari: not tested 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
We've pulled the release, hopefully we'll have a working update out soon.
