### ISSUE TITLE
NWJS 0.33.0 export disables gamepad

### ISSUE THREAD

**Issue by jgp1971** [Scirra/Construct-3-bugs#2038]
## Problem description

When exporting a small project with the latest NWJS release, gamepad is unusable. Both C3 and C2 runtimes are affected by this issue.

## Attach a .c3p

[test_nwjs.zip](https://github.com/Scirra/Construct-3-bugs/files/2379366/test_nwjs.zip)

## Steps to reproduce

1. Open the project and export the game with NWJS 0.33.0
2. Download and run the exported game, and see if the square changes color when following the instructions.
3. Open the project and export the game with NWJS 0.32.0 or older.
4. Download and run the exported game, and see if the square changes color when following the instructions.

## Observed result

Square won't change color with the 0.33.0 exported version, but will with 0.32.0

## Expected result

Both versions recognize the gamepad.

## Affected browsers

No browser affected (the latest version of chrome functions correctly in this regard).

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.92
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
C3 release: r116 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 1.3 gb (17%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Looks like an NW.js issue so reported here: https://github.com/nwjs/nw.js/issues/6792
Will follow up there.

**Comment by AshleyScirra** [comment]
FYI I've just released an NW.js 0.33.3 update which includes the fix for gamepad input.
