### ISSUE TITLE
[Edge/Windows Store Version] Export Problems

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2039]
## Problem description

Problems exporting project.

* Html5 export getting stuck on writing files.
* NW.js export download link, not clickable.

Havn't tried other export options, but might be worth checking them too.

## Attach a .c3p

N/A

## Steps to reproduce

1. Try exporting any built in game template, using NW.js or html5
2. Not working

## Observed result

* Html5 export getting stuck on writing files.
* NW.js export download link, not clickable.

## Expected result

Should work like in other browsers.

## Affected browsers

* Edge: yes

**Comment by AshleyScirra** [comment]
I can export successfully using the Edge browser. Did you mean to say this is specific to the Windows Store version only?

**Comment by tunepunk** [comment]
Windows Store version, but I guess it's based on edge so that's why I wrote that as well.

**Comment by AshleyScirra** [comment]
Please always check which platforms are affected - it's important to know for every bug report.

This turned out to need a lot of refactoring to completely solve, but I think it should be fixed for the next release. Let's verify when it's out.

**Comment by AshleyScirra** [comment]
Can you confirm it works in r118?

**Comment by tunepunk** [comment]
Can confirm. Seems to be working now.

**Comment by AshleyScirra** [comment]
Thanks!
