### ISSUE TITLE
[r27] Sprite editor : Pencil tool

### ISSUE THREAD

**Issue by uboel** [Scirra/Construct-3-bugs#204]
## Problem description

Is it normal that a Black (0,0,0,255) pencil "Size 1" draws a grayish [alpha: 25%] (0,0,0,64) 2 pixels wide line?

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

[Test-SpriteEditor.zip](https://github.com/Scirra/Construct-3-bugs/files/1001381/Test-SpriteEditor.zip)

## Steps to reproduce

1. Create a new sprite (I resize it to 64x64 and setup the grid 1x1)
2. Take the pencil, resize to 1
3. Draw a line

## Observed result

![sprite-editor-pencil-size-and-color](https://cloud.githubusercontent.com/assets/28643164/26062756/12804880-398c-11e7-82a8-1834cbecba7a.PNG)

## Expected result

I would like to draw 1px full black pixel

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
</details>

**Comment by DiegoScirra** [comment]
@uboel

Are you trying this out in r27?

**Comment by uboel** [comment]
Yes

Le 15 mai 2017 5:05 PM, "DiegoScirra" <notifications@github.com> a écrit :

@uboel <https://github.com/uboel>

Are you trying this out in r27?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Scirra/Construct-3-bugs/issues/204#issuecomment-301503929>,
or mute the thread

**Comment by uboel** [comment]
It seems even size values are producing perfect square brushes and odd size values are producing rounded square anti-aliased brushes.

![sprite-editor-pencil-size-even-odd-sizes](https://cloud.githubusercontent.com/assets/28643164/26100160/5f44da54-3a2d-11e7-878f-1c2eb1b98ff1.PNG)

**Comment by DiegoScirra** [comment]
Ahhh, I was able to reproduce it.

This only happens when you are using either of the snapping options with an odd size.

The thing in this particular case, is that it is impossible to perfectly snap an odd side square to the grid, because you end up trying to draw in the middle of 2 pixels, which is not possible. If you do it anyway, the browser's anti-alias kicks in, so you see the blury stroke.

I remember trying to round the coordinates to the nearest whole number to avoid the blur, but then what happens is that you are are not able to snap perfectly with the grid. Odd sizes look sharp, but the stroke has a slight offset, which also looks strange and would most likely be reported as a bug.

**Comment by DiegoScirra** [comment]
If you are are using a grid of 1x1, snapping is not needed. If you want to draw each pixel individually, turn snapping off and set the size of the pencil to 1. Will work like a charm.

I will discuss with the team what is the correct way to handle this case.

**Comment by uboel** [comment]
Ok...let's call that a workaround for the 1px pencil. ;-)

**Comment by tunepunk** [comment]
Could it be that the snapping snaps to the actual grid, so it's drawing in both "pixel areas" maybe snap should have like a half pixel offset, or snap to the closest center of each pixel instead of the line between pixels.

**Comment by DiegoScirra** [comment]
@uboel @tunepunk 

So I implemented snapping to whole pixels in r28.

Let me know what you think about it once it is released.

**Comment by AshleyScirra** [comment]
r28 is out, please check again!

**Comment by uboel** [comment]
Hi Ashley,

The pencil tool is now working as expected! 

No more brush rounding, no more anti-aliasing, the pencil behaves always in the same way, no matter the grid is active or not, no matter the snapping is active or not, ...

Great job!
