### ISSUE TITLE
Popup window of "Find Results" crash on multi-screen

### ISSUE THREAD

**Issue by jgp1971** [Scirra/Construct-3-bugs#2040]
## Problem description

The popup window of "Find results" buggies itself and then crashes the program when moved out of the main screen.

## Attach a .c3p

[test_popup.zip](https://github.com/Scirra/Construct-3-bugs/files/2383573/test_popup.zip)

## Steps to reproduce

1. Open project in main screen.
2. View and then undock find results.
3. Open to Popup window find results.
4. Move the popup window to a secondary screen.
5. Search for anything that would return a result (like "scaling" in the example project)
6. Notice how find results gets open, but buggy, in the main screen, and the popup window in the secondary screen displays correctly the results.
7. Close the buggied "find results" in the main screen, and click on the find button again.
8. Now, the popup window in the other screen is the one that gets buggied, and the undocked find results of the main screen looks correct.
9. Without pressing anything else, minimize the popup window of the secondary screen.

## Observed result

When the popup window of the secondary screen gets minimized, C3 crashes.

## Expected result

Not to crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.92
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
C3 release: r117 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 1 gb (13.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by jgp1971** [comment]
Oh, and just to use up the space in a smart way: when visiting the https://editor.construct.net/r117-2/ link, you get prompted to update to 117.2, but clicking on update doesnt stop the prompting to appear every time it reloads.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
