### ISSUE TITLE
Effects not displaying for Some people for published games in chrome

### ISSUE THREAD

**Issue by jinxbunny** [Scirra/Construct-3-bugs#2041]
## Problem description

Its not a problem that I have personally, but I'm working on a project for a client and they can't see any effects that I apply - specifically I'm using the Tint effect to change the colour of a sprite, in the example it's a case of simply clicking / tapping the coloured numbered circles to change the Tint effect RGB numbers to correspond with that of the numbered sprite.

For me it works fine, it works for him in firefox but in his initial version of chrome it wasn't working and even after updating to the latest version of chrome no colour change happens and it only ever shows the white circle at the top.

## Attach a .c3p
[ColourTest.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2384139/ColourTest.c3p.zip)

## Steps to reproduce

1. View the project in chrome - seemingly on a random machine

## Observed result

No effects display, the colour of the big circle never changes despite tapping the sprites at the bottom

## Expected result

tapping the numbered sprites should change the tint effect (colour) of the bigger white circle sprite

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: unknown
* Safari: no

**Comment by AshleyScirra** [comment]
This is expected if their device doesn't support WebGL. It will fall back to the canvas2d renderer.

Ask them to visit chrome://gpu and report what it visits there - if it says WebGL is not supported, that's the cause.

**Comment by jinxbunny** [comment]
The feedback says ‘WebGL: Software only, hardware acceleration unavailable
WebGL2: Software only, hardware acceleration unavailable’

Is this common in chrome like is it something that can be disabled by accident or can a user easily be prompted to enable it (like flash or something)

**Comment by shortercode** [comment]
@jinxbunny it's likely the users device has a major issue with it's GPU; such as a missing feature, a security issue or terrible performance. It's possible that the user has disabled it, but the setting is fairly well hidden and is enabled by default.

You can force it to be enabled via the flags page. But given the list of possible reasons I gave above you can probably understand it's not a great idea, and it might not even work.

The user may be able to resolve the problem by ensuring that all of the following are **fully** up to date: chrome, graphics driver and operating system. If that doesn't work their GPU is probably blacklisted by Chrome.

Currently about 98% of active web devices support webgl, given the amount of old computers/mobiles in the wild it's unlikely that this figure will ever be 100%.

**Comment by AshleyScirra** [comment]
The Construct 2 engine is designed to fall back to canvas2d rendering when WebGL is unavailable. This used to be common - when WebGL was first introduced in 2011 maybe something like 30-50% of devices supported it, so Construct has features specifically to allow you to detect if effects are supported, specify a fallback if WebGL is not supported, and so on.

That's all still there and still working, but the share of devices that don't support WebGL has shrunk to just a few percent. This rarity has probably mistakenly led you to believe it's a bug, but it's not - it's just the fallback working as originally designed.
