### ISSUE TITLE
Fullscreen not working properly C2 RT

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2042]
## Problem description

How fullscreen was working yesterday:
https://i.imgur.com/wZAiICf.jpg

How fullscreen is working now:
https://i.imgur.com/6yca0X6.jpg

For some reason the fullscreen was completely different when i tried to export my game today. I can't update the Steam version until this is fixed.

## Attach a .c3p

[Fullscreen Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2384731/Fullscreen.Bug.zip)

## Steps to reproduce

1. Export the project with NW.js.
2. Open the exported project.

## Observed result

A tiny screen in the middle of a black canvas.

## Expected result

A normal fullscreen.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is due to the following fix:

> Browser plugin: Request fullscreen 'Centered' incorrectly did 'Letterbox scale' in C2 runtime

Your project was relying on fullscreen "Centered" mode to actually do letterbox scale, which was a bug. It's fixed now and properly does centered mode. Just change it to letterbox scale.

**Comment by BonzerKitten7** [comment]
It's working perfectly now, thank you, Ashley! -`ღ´-
