### ISSUE TITLE
[r117-2] Window Beta Update available appears every time

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#2043]
## Problem description

Every time I enter in Construct 3 via [https://editor.construct.net/r117-2/](https://editor.construct.net/r117-2/) I get the message 

> Beta update available
> A new beta version of Construct 3 is available! You are using **r117**, and **r117.2**  is ready to use.

## Attach a .c3p

![sep 14 2018 11_42 pm](https://user-images.githubusercontent.com/23579630/45576823-24a2c200-b879-11e8-9e48-fc9b129b4779.gif)

## Steps to reproduce

1. Go to via [https://editor.construct.net/r117-2/](https://editor.construct.net/r117-2/)
2. Click **Update** to the message _Beta update available_
3. Wait Construct 3 restart
4. Click **Update** on the message _Beta update available_
5. Wait Construct 3 restart
6. ... Repeat ad libitum

## Observed result

The message appears every time.

## Expected result

Construct 3 will be udpate and the message doesn't appear after it.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.92
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
C3 release: r117 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 142 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
This is a known issue which we noted in the comments. It's specific to this release and will stop happening at the next update.

**Comment by AshleyScirra** [comment]
Should have cleared up with r118
