### ISSUE TITLE
Mobil Advert goes not for Construct 3

### ISSUE THREAD

**Issue by Planlosstudios** [Scirra/Construct-3-bugs#2045]
## Problem description

Hi together

I noticed that the Mobile Advert Plugin is not working. Each time I'm told that the advertising could not be loaded. Below you will find a test programming that shows the error.

Please help me.

Kind Regards Philipp

[TestAdMob.zip](https://github.com/Scirra/Construct-3-bugs/files/2386799/TestAdMob.zip)

## Steps to reproduce

1. Make an AdMob Account and Create an App => Banner
2. Start Construct 3 and Create a Test Project with minimal Events for Testing

## Expected result

It shows me the sprite that should come only if the advertisement could not be loaded.

## Affected browsers

* Chrome: yes (starting direct from Construct 3 Installation for the Pc)

**Comment by Planlosstudios** [comment]
@ERAgames777

Thanks for the Answer.

**Comment by Planlosstudios** [comment]
@shortercode 

I tried everything you wrote, but none of it works. In my opinion, the banner does not even load, because the sprite jumps to position 250,250. The Condition on banner loaded is not available for me.

I work with Construct 3 version 111r stable.

Below you will find the customized file.
[TestAdMob.zip](https://github.com/Scirra/Construct-3-bugs/files/2389535/TestAdMob.zip)

**Comment by ERAgames777** [comment]
@shortercode 
I also noticed that before in the test mode it showed exactly the test advertisement from googleAds developers, but now it is shown above the advertisement of the TEST badges and the video ad itself (let's ad Car Lexus)

**Comment by shortercode** [comment]
@ERAgames777 I generally only develop in test mode, as there really isn't any reason why it should behave differently. I haven't seen any issue with rewarded videos so this seems a little odd. I'm not sure how your using the rewarded videos but they can take a comparably long time to load so it could just be that it wasn't ready, or had some form of network error? It's hard to say...

**Comment by ERAgames777** [comment]
@shortercode 
Yes, today I tested the project and noticed that with a long wait, the test video reward display was downloaded and the advertisement was shown.

**Comment by Planlosstudios** [comment]
@shortercode 

Thanks for the fast Fix.

Have a nice Day

kind regards
Planlosstudios
