### ISSUE TITLE
Custom Importer SDK - SetOriginX and SetOriginY don't immediately update sprite in layout view

### ISSUE THREAD

**Issue by lucidspriter** [Scirra/Construct-3-bugs#2053]
## Problem description
After changing the first frame of an animation with IAnimationFrame.SetOriginX and SetOriginY, it shows up in the layout as if the pivot point is still in the center. If you double click the sprite, the pivot point is in the correct location in the image editor . If you change the initial frame in the properties panel to something else and change it back, it corrects the pivot point placement. Reloading the project after it's been saved also corrects the pivot point placement.

> Ashley - Every animation frame has its own origin, and the object itself separately has an origin. Sprites copy the animation frame origin to the object origin. It sounds like we need to make sure this happens when calling the SDK methods.

I modified the CustomImporterPlugin example to set the origin as well.  The change is on lines 88 and 89 of plugin.js
[Here's the modified plugin](https://www.dropbox.com/s/sby280e6nth7mtt/OriginBug.c3addon?dl=0)
For convenience, here's a link to the:
[CustomImporterSampleData.zip](https://s1.construct.net/articles/downloads/1573/customimportersampledata.zip)

**Comment by AshleyScirra** [comment]
It turns out we could fix this without needing any new APIs. Note however that the SDK already gives you control over both the animation frame and object origins - so you can also work around this by calling the SetOrigin methods on the world instance that is created.
