### ISSUE TITLE
Manual - Image points are missing some informations

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2054]
Image points in the manual are lacking some informations : 
Image points pane - Quick assign - and so on...

No mention, no way to link someone to it as it did in C2 :
https://www.scirra.com/manual/63/image-points
https://www.construct.net/make-games/manuals/construct-3/interface/animations-editor

**Comment by AshleyScirra** [comment]
Updated animations editor manual with section on image points: https://www.construct.net/en/make-games/manuals/construct-3/interface/animations-editor
