### ISSUE TITLE
Editor - Allow editing properties of a single object when a container is wrapped (enhancement)

### ISSUE THREAD

**Issue by lucidspriter** [Scirra/Construct-3-bugs#2055]
It would be useful to be able to edit the properties of a single object that is wrapped by the **Select Mode** of a container. Right now, the only way to edit a single object is to find it in the properties panel, which is time-consuming in a large project. 

Less ideal, but still useful would be the ability to change the **Select Mode** of a container back to _Normal_ by right-clicking any instances in the wrap.

The main reason to use wrapped selection is to be able to drag and drop objects together, so the current method of showing the aggregate object properties nullifies the convenience of container wrapping when you need to edit single objects.

**Comment by AshleyScirra** [comment]
This already exists as Alt + Click (see: https://www.construct.net/make-games/manuals/construct-3/interface/layout-view)

Additionally for non-bug feature suggestions please use the feature suggestion platform instead of the bug tracker: https://construct3.ideas.aha.io/
