### ISSUE TITLE
Gamepads not detected with Chromium 69 beta Desktop build (preview and export)

### ISSUE THREAD

**Issue by alastair-games** [Scirra/Construct-3-bugs#2056]
## Problem description

Was hoping to test vibration but noticed that the gamepad isn't working at all.

To test if it was working I made a new app that shows how many gamepads are connected using this event:

![image](https://user-images.githubusercontent.com/5744908/45732284-f4fc0d00-bc1e-11e8-98ea-bed221455f13.png)

Gamepad count shows 0 on desktop, but shows 1 when I press buttons in browsers.

## Affected software

Tested r118 in Firefox - Works
Tested r118 in Chrome 69 - Works
Tested r118 in Chromium 69 beta Desktop build (preview and export) - Doesn't work

## Attach a .c3p

[gamepad detected.zip](https://github.com/Scirra/Construct-3-bugs/files/2395523/gamepad.detected.zip)

## Steps to reproduce

1. connect a gamepad
2. preview the game on latest desktop build
3. Press a button

## Observed result

0

## Expected result

1

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@032b3ca19e9af20182f9bd03deefc0faf4695558) NWjs/0.33.0 (like Chrome/69.0.3497.81)
C3 release: r118 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 733 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
FYI I've updated the desktop build with NW.js 0.33.3 which should have fixed this.
