### ISSUE TITLE
PubCenter always spits out an error

### ISSUE THREAD

**Issue by MrWonka** [Scirra/Construct-3-bugs#2058]
## Problem description

pubcenter interstitial ads always give an error

## Attach a .c3p

[test.zip](https://github.com/Scirra/Construct-3-bugs/files/2399827/test.zip)
I've removed the program and ad IDs for privacy reasons. 

## Steps to reproduce

1. output to windows
2. add winjs, add ad reference, associate with windows store, and change to x64
3. Ad Error

**Comment by AshleyScirra** [comment]
What is the error?

**Comment by MrWonka** [comment]
How do I find debug info? This is the browser platform info if that helps

Platform information
Browser: Edge
Browser version: 17.17134
Browser engine: Edge
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
C3 release: r119 (beta)
Language setting: en-US 
Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

**Comment by AshleyScirra** [comment]
Are there any errors reported in the console?

**Comment by MrWonka** [comment]
In the partner dashboard I went to monetize then I've created the ad with the following properties 

video ad | ArcadeTonic | *********r7 | *********34 | Video interstitial | UWP (Windows 10) | Automatic | Active 
I've copied the r7 and 34 into their respective fields, then I preload pubcenter on start of layout, then call on the ad when an icon is clicked, with the ad field left "". 
If this dosen't help I can send you the project.

**Comment by MrWonka** [comment]
Bump

**Comment by MrWonka** [comment]
Perhaps it has something to do with the app being a private one?

**Comment by MrWonka** [comment]
Any update on the issue? I've noticed the error now "TS6053	(JS) File '//Microsoft.Advertising.JavaScript/ad.js' not found." Is there anything more I can provide to assist with solving this issue?

**Comment by AshleyScirra** [comment]
Did you install the Microsoft Advertising SDK as the documentation describes? That error suggests it is missing.

Other than that I'm not sure what to do about this issue - it might be better to contact Microsoft for support.

**Comment by AshleyScirra** [comment]
Closing, please contact Microsoft if you need further support with pubCenter services.
