### ISSUE TITLE
Cannot use safe mode to uninstall a broken addon I am developing

### ISSUE THREAD

**Issue by paala** [Scirra/Construct-3-bugs#2059]
## Problem description
I go to
https://editor.construct.net/?safe-mode
when I click on add on manager crash happens 

## Steps to reproduce

1.
2.
3.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE
Error report information
Type: unhandled rejection
Reason: Error: r.ǃeB is not a function @ TypeError: r.ǃeB is not a function at r.plugins (https://editor.construct.net/r111/main.js:63:97693) at plugins.next () at ǃI.ǃP.ǃN.ǃtDv.ǃtDq (https://editor.construct.net/r111/main.js:161:33982) at Promise.all.then (https://editor.construct.net/r111/main.js:161:33709)
Stack: TypeError: r.ǃeB is not a function at r.plugins (https://editor.construct.net/r111/main.js:63:97693) at plugins.next () at ǃI.ǃP.ǃN.ǃtDv.ǃtDq (https://editor.construct.net/r111/main.js:161:33982) at Promise.all.then (https://editor.construct.net/r111/main.js:161:33709)
Construct 3 version: r111
URL: https://editor.construct.net/?safe-mode
Date: Thu Sep 20 2018 10:46:06 GMT+0300 (Eastern European Summer Time)
Uptime: 130.4 s

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r111 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
We can't help unless you provide everything necessary for us to reproduce the problem.

You should also use [developer mode](https://www.construct.net/make-games/manuals/addon-sdk/guide/using-developer-mode) so you never end up in this situation in the first place.
