### ISSUE TITLE
Remote Preview not showing in Menu -> Project 

### ISSUE THREAD

**Issue by driesdriessen** [Scirra/Construct-3-bugs#206]
## Problem description

Remove Preview not showing in menu

## Attach a .c3p

This is a UI issue, not a problem with my project

## Steps to reproduce

1. click on Menu 
2. Click on Project
3.

## Observed result

Remote Preview is not visible
Remote Preview is only visible when I right-click on the project name in the project panel.

## Expected result

Remote preview should show next to Preview (during Game Jam)

## Affected browsers

* Chrome: yes
* Firefox: unknown
* Edge: unknown
* Safari: unknown

## System details

OSX 10.11.6
Chrome 58.0.3029.110 (64-bit)
Construct3 R27 (during game jam)

**Comment by AshleyScirra** [comment]
This is done for r28.

**Comment by driesdriessen** [comment]
Thanks for the quick response
