### ISSUE TITLE
Previewing with multiple projects open unexpected result.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2060]
## Problem description

The fix in this issue works great when there is only one project open.
https://github.com/Scirra/Construct-3-bugs/issues/2049

If you have 2 projects open I noticed some odd behaviour.

## Attach a .c3p

N/A any projects will do.

## Steps to reproduce

1. Open project 1 (ex. Endless runner)
2. Close Layout.
3. Open Project 2, but leave layouts open.
4. Switch to project 1 event sheet. (So that project 2 is inactive/greyed in the project window)
5. Press Preview.
6. Project 2 is previewed even if project 1 is the active one.

## Observed result

If there is any layout open in project 2, it will always be the one previewed when pressing preview. 

The new preview behaviour works well, only if both projects has no layouts open.

## Expected result

Preview should always preview the current active project, even if other projects have layouts open.

Suggested:
* Pressing preview while on a layout, preview that particular project layout.
* Pressing preview while on an event sheet or editing project file (dictionary, array, js, etc). Could preview dafault layout set in project settings, for that active project.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Should be fixed in the next release.
