### ISSUE TITLE
Editor moving the panel windows when reloading the page

### ISSUE THREAD

**Issue by jgp1971** [Scirra/Construct-3-bugs#2062]
## Problem description

After distributing the panels different parts of the screen, after reloading the screen, its sizes (widths and heights) can get modified. 

With the panels appropiatedly set:
![image](https://user-images.githubusercontent.com/39523503/45870477-40332e80-bd8b-11e8-991b-04a0f18469c6.png)

After reloading the website:
![image](https://user-images.githubusercontent.com/39523503/45870502-4c1ef080-bd8b-11e8-9bd3-2ce80137f4e5.png)

## Attach a .c3p

This issue is visible without using any .c3p, or using any. It doesn't require the loading of a project.

## Steps to reproduce

1. Open an editor page (for example, https://editor.construct.net/r119/)
2. Rearrange the window panels to something resembling the distribution submitted.
3. (Important) Play with their widths and heights, so that they are custom and not the ones that are by default when arranged in specific positions.
4. Reload the page.

## Observed result

The editor panels get moved all around.

## Expected result

The editor panels remain as arranged.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r119 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 1 gb (13.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Nice find, thanks for reporting that. I've fixed the issue for the next release.

As I had to add some more information to the stored layout it will not restore correctly on the first run of the new release, but it will be correct after that.

**Comment by jgp1971** [comment]
Sorry to bother you @shortercode, but I don't know if I should open a new issue or just comment it here in case it's related: another thing I've noted (again, unrelated to any project and just editor specific) is that what used to be called uistate of the event sheets (the position of columns, the size of name cells, the zoom level) also get completely changed and mangled when reloading and creating event sheets.

Would it be possible to maybe set a uistate as default so we don't have to keep changing the size and zoom of everything all the time? Thanks!

**Comment by jgp1971** [comment]
Oh, I understand, I just didn't know if it could be related, since it also happens when reloading. Will do as you instructed me, then.
