### ISSUE TITLE
[R119] Reading XML within C3 runtime does not seem to work

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2064]
## Problem description

A capx reading XML files works in C2 runtime and does not in C3 runtime.
Originally reported in the forums : https://www.construct.net/forum/construct-3/general-discussion-7/translation-with-xml-dont-work-137902

## Attach a .c3p

"localisation.capx" of this tutorial : https://www.scirra.com/tutorials/444/supporting-multiple-languages/revisions

## Steps to reproduce

1. Open the capx in r119
2. Remove webstorage
3. Pass in c3 runtime
4. Preview
5. Click a flag in the top right

## Observed result

The dialog bubble is empty
It seems as XML.stringvalue is empty, whatever id of the node you are trying to display/access.

## Expected result

The dialog bubble should display different texts, as in the c2 runtime version.

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Ergh, it works in development but not in the build version, so I guess this is something to do with minification which is always difficult...

**Comment by AshleyScirra** [comment]
This turned out to be a bug with babel-minify (https://github.com/babel/minify/issues/908) in the depths of the XML parsing library we use. I found a workaround so this should be working in the next release.
