### ISSUE TITLE
AddOn SDK Custom Import requests

### ISSUE THREAD

**Issue by lucidspriter** [Scirra/Construct-3-bugs#2067]
# Immediately useful
- ~IAnimation SetProperty~
- iProject.GetObjectType(objectName)  returning an IObjectType by that name if it already exists.  This will make it possible to reimport and update the same files to the same objects when something is dropped in, as opposed to creating a new instance.

# Convenience
- **Settings | Advanced | Load Last Project on Startup**.  To streamline plugin development with a single refresh button press to try out changes.

# Long Term / Future Proofing
## Animations
- ~IAnimation GetProperty~
- ~IAnimationFrame SetProperty, GetProperty~

#### Layers
- SetLayer

#### Variables
- GetVariable
- SetVariable
- AddVariable

#### Behaviors
- AddBehavior
- SetBehaviorProperty
- Expose ACEs for Behaviors

#### Effects
- AddEffect
- SetEffectProperty
- Expose Property Ids for Effects

## Layouts
- Layout - GetLayers
- Layout - AddLayerOnTop
- Layout - AddLayerOnBottom

**Comment by AshleyScirra** [comment]
What do you want `IAnimation SetProperty` to do? Normally anything with properties has separate set and get methods per property.

**Comment by lucidspriter** [comment]
For the short term, I just need SetSpeed.

**Comment by AshleyScirra** [comment]
Added IAnimation and IAnimationFrame property setters/getters for the next release. Leaving this open to cover the rest of the API surface at a later time.

**Comment by lucidspriter** [comment]
@AshleyScirra - I also added this to the list in the original post, but I recently realized that without a non-global GetObjectType, it's not possible to allow reimports.  

iProject.GetObjectType(objectName)  // returning an IObjectType if it currently exists.  This will make it possible to reimport and update the same files to the same objects when something is dropped in, as opposed to creating a new instance.

**Comment by AshleyScirra** [comment]
Since we don't normally track suggestions on the bug tracker, and there is now a feature suggestion at https://construct3.ideas.aha.io/ideas/C3-I-924 with some overlap to this issue, closing this issue and will track as a suggestion instead.
