### ISSUE TITLE
[C3 Runtime] 9-Patch not work on Facebook Instant Games

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#2068]
## Problem description

The 9-Patch Object is not visible on Facebook Instant Games (Android 8 / Samsung Galaxy S7). It works only on my pc in Chrome.

## Attach a .c3p

[Download Example](https://massive-cube.com/work/problem/construct/facebook_9patch.c3p)

## Steps to reproduce

1. Open the example file
2. Export the project with : Minify script ON, Recompress Images ON, Deduplicate Images ON
3. Upload the Exported Project to Facebook Instant Games
4. Start the App on Instant Games with a Android-Smartphone
5. After loading - All 9 Patch-Objects invisible.

## Observed result

All 9-Patch objects are hidden. (or not loaded?)

I'm not sure if that's important, but here is the log from my Android-Console:

[Show Screenshot from Android-Console-Warnings](https://massive-cube.com/work/problem/construct/fbinstantgames-9patch-problem.jpg)

## Expected result

All 9-Patch-Objects visible.

## Affected browsers

* Chrome: yes
* Firefox: -
* Edge: -
* Safari: -
* Facebook Instant Games (Android): yes

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r119 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 57 gb
Storage usage (approx): 5.2 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The errors look like a graphics driver bug on the device. Unfortunately there is nothing we can do about such problems. Your best bet is probably to report it to Google at crbug.com and see if they can work around it.

**Comment by masscube** [comment]
I have tested something about that. The problem is **only** on facebook instant games (android), not on chrome (android). I don't know, what is the technical difference between the sprite object and the 9-Patch object!?
Are the graphics loaded differently with the 9patch plugin?

**Comment by AshleyScirra** [comment]
If it works on one platform, it suggests the code in our engine is correct. So it's probably a bug specific to one platform.

Graphics driver bugs can be essentially random, it's not usually worth trying to figure out exactly what's going on if that's the problem.

**Comment by masscube** [comment]
Ok, not work on other devices (randomly it works). But i don't know why only the 9-patch object not work and all other plugins work?

I have found a new bug (post as new ticket).
