### ISSUE TITLE
[R119] Flash behav appear inside other behav properties

### ISSUE THREAD

**Issue by Max19871** [Scirra/Construct-3-bugs#2069]
## Problem description

Adding "Flash" behaviour, appear in beaviours list inside another behaviour properties.

## Attach a .c3p

[Flash behav problem.zip](https://github.com/Scirra/Construct-3-bugs/files/2408446/Flash.behav.problem.zip)

## Steps to reproduce

1. Add few behavs to object
2. Add Flash behav
3. Move it up/down inside behavs list and it will appear in the properties of the behav before him

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Can't reproduce, looks like it's working fine. The Flash behavior has no properties so displays slightly differently to other behaviors, I think you have just misinterpreted that.

**Comment by Max19871** [comment]
Hi Ashley, Have you checked attached file? To me appear a bit confusing
that flash behav, also if does'nt have properties, is listed inside another
behav properties.



Il Lun 24 Set 2018, 13:11 Ashley (Scirra) <notifications@github.com> ha
scritto:

**Comment by AshleyScirra** [comment]
Yes, I did look at it. It appears to be working as designed.
