### ISSUE TITLE
Animations Editor: Eraser at 1 pixel size and 1 hardness not working as expected

### ISSUE THREAD

**Issue by StefanSava** [Scirra/Construct-3-bugs#207]
## Problem description

I'm trying to make a pixel character. Erasing at 1 pixel size and 1 hardness produces a eraser of 2x2 pixels size with fuzzy opacity.

## Attach a .c3p

https://www.dropbox.com/s/924d2rnxnfatgjk/eraserProblem.c3p?dl=0

## Steps to reproduce

1.enter animations editor
2.draw a sprite
3.get eraser set size to 1 and hardness to 1
4.erase 1 pixel

## Observed result

a 2x2 pixel semi-transparent area is being erased

## Expected result

erase just 1 pixel to 0 opacity

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.81
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

Local storage
Storage quota (approx): 5.8 gb
Storage usage (approx): 46 mb (0.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 650 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by uboel** [comment]
Along with the pencil problem I report earlier, I also have the same eraser issue.

**Comment by StefanSava** [comment]
It's weird, the pencil worked fine for me, just the eraser had the problem. I also made a 1x1 grid i forgot to mention.

**Comment by uboel** [comment]
I just check again the eraser in r27. 

It seems to be round...so a 1px large eraser is in fact an anti-aliased 1px diameter circle (2px semi-transparent square)...hence the tone softening instead of the pure 1px wide deletion.
The hardness parameter seems to have no effect below size value 3.

**Comment by uboel** [comment]
@AshleyScirra 

Would it be possible to give the user the possibility to choose between a round or a square eraser?

**Comment by DiegoScirra** [comment]
I just made a change so the eraser behaves like the pencil at sizes 1 and 2, which is way more useful than a really small anti-aliased circle :P. Hardness should be working properly now for all sizes.

This will be ready for r29.

**Comment by uboel** [comment]
Ok. Many thanks. I'll be testing that later when the r29 becomes available.

**Comment by StefanSava** [comment]
Nice, thank you! Any estimate on when r29 will be released? I'm asking because I'd like to use it for the gamejam and I can't make sprites with this problem.

**Comment by AshleyScirra** [comment]
r29 is now out, please take another look!

**Comment by StefanSava** [comment]
Yep, i see the update. I've also checked the eraser and now I see a new problem. There is the clean square eraser and also the problematic circle aliased erasing that is offset to the lower right.  If you make a big black square and try erasing with a 1 px 1 hardness eraser you will see the problem. Should I re-open a issue?
![screenshot 2017-05-18 21 44 51](https://cloud.githubusercontent.com/assets/21075550/26218526/fe862fa4-3c13-11e7-9c64-88c7ea5b3334.png)

**Comment by DiegoScirra** [comment]
@StefanSava 

Yes open a new issue please, otherwise it is likely that this will get lost. Thank you.
