### ISSUE TITLE
[r119] Error using random?

### ISSUE THREAD

**Issue by AndreYin** [Scirra/Construct-3-bugs#2075]
## Problem description

If I set the platform behavior jump height to a random number and then tell the sprite to jump, it doesn't work. Works if you add a "wait 0" between the events, or if you set the jump height to a value directly - but not with a random number.

## Attach a .c3p

[teste.zip](https://github.com/Scirra/Construct-3-bugs/files/2410271/teste.zip)

## Steps to reproduce

1. Create a sprite object with the platform behavior
2. Add any sort of solid object for the ground
3. Add the keyboard object
4. Make an event where if a keyboard key is pressed, set the player jump height to a random number and simulate the jump control

## Observed result

Run in debug mode and notice how the jump height never actually changes

## Expected result

Player should jump at random heights. 

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Can't reproduce here. The jump height does change every time I press space.
