### ISSUE TITLE
Exporting With NW.js Fails (No Internet Connection Error)

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#2076]
## Problem description
I'm trying to export a C3 project using NWjs and it fails to load the exporter and results in an error, telling me that my Internet connection is not working. My Internet connection is fine and this is probably something with the servers that host all NWjs related services.

I assume this is something temporally but still, might be worth giving you guys a heads up about it.

## Steps to reproduce

1. Open any project
2. Click on "export project" and select "NW.js" export
3. Click on "next" to reach the final exporting settings
4. Notice that it tries to load them but fails after ~1min.

## Observed result
**Chrome Error:**
![nwjs export error](https://user-images.githubusercontent.com/15656049/45955085-4b968c00-c00f-11e8-9e7c-bf2fb0490200.PNG)

**FireFox Error:**
![nwjs export error ff](https://user-images.githubusercontent.com/15656049/45955092-4cc7b900-c00f-11e8-956a-06edc50c0578.PNG)

**Chrome Console:**
![console error](https://user-images.githubusercontent.com/15656049/45955094-4e917c80-c00f-11e8-98c3-62930ebd32bb.PNG)

## Expected result
Exporting with NWjs should work fine and I should be able to access all final exporting settings.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Any version of C3 is affected, regardless of hardware.

</details>

**Comment by ACC-Math** [comment]
I have the same problem but it makes my Construct 3 crash when trying to download any nwjs version :
https://downloads.scirra.com/c3-nwjs/v0.32.0/win32.zip

**Comment by AshleyScirra** [comment]
It looks like there's something wrong with the server hosting the files. We're looking in to it.

**Comment by AshleyScirra** [comment]
Looks like it's working now, can you confirm?

**Comment by TheRealDannyyy** [comment]
I could download and export successfully. Thanks for the quick fix.
