### ISSUE TITLE
Construct 3 runtime doesn't work in iOS simulator

### ISSUE THREAD

**Issue by softdevstory** [Scirra/Construct-3-bugs#2079]
## Problem description

I created project uses construct 3 runtime.

I export project for iOS and build it by using Xcode. then I run that by using simulator.

project didn't run and following messages are displayed.

>   Browser not supported
> 
>   This content is not supported in this browser. Try installing any available software updates, or try using a different browser.

Construct 2 runtime works on iOS.

## Attach a .c3p

[runtimeTest.c3p](https://drive.google.com/file/d/1KXAGNSdK44RqUD3856zEEGW0gG5CJuU-/view?usp=sharing)

## Steps to reproduce

1. open project and export project for iOS (xcode project)
2. build xcode project
3. run it on simulator

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Which version of iOS are you running? The C3 runtime currently requires iOS 12+ due to bugs in Safari 11.

**Comment by softdevstory** [comment]
simulator's iOS version is 12.0

**Comment by softdevstory** [comment]
Remote preview works. My iPhone's iOS is 12.0.

**Comment by switchcrook** [comment]
I am having the same issue - ios12, iPad Pro, Construct 3 runtime. Remote Preview works, NW.js build works - but building to the device with an iOS12 Xcode build shows a black screen, and unsupported browser in the logs. Relying on this for a contract job!

**Comment by AshleyScirra** [comment]
Iain, could you take a look at why the iOS simulator fails the C3 runtime support check? Perhaps the simulator doesn't support WebGL - but then we're kind of stuffed...

**Comment by switchcrook** [comment]
@AshleyScirra I saw the title change, just confirming from experience this weekend that it doesn't work building to iOS 12 device through Xcode as well as Simulator. (see above comment)

**Comment by AshleyScirra** [comment]
There are separate issues with running exports in Safari, which were covered by other filed issues that were closed since they should be corrected in the next release. This issue we are focusing solely on the iOS simulator issue since that is the problem mentioned in the original report and is different to the other issues.

**Comment by switchcrook** [comment]
@AshleyScirra Ok, thank you! Just wanted to make sure it was noticed. Looking forward to next release.

**Comment by shortercode** [comment]
Update for this issue.

We've discovered that the ios 12 simulator does not support webassembly, which is used for a number of features in the C3 runtime ( opus audio decoder, physics, advanced random ). It's not clear why this is the case.

Other than a handful of comments about it in bug threads I haven't been able to find any reference to it, @AshleyScirra has opened an issue about it so hopefully we will get a concrete answer soon.

[webkit bug 191064](https://bugs.webkit.org/show_bug.cgi?id=191064)

**Comment by AshleyScirra** [comment]
This is blocked on a webkit bug and shouldn't require any action from us after they fix it, so closing.
