### ISSUE TITLE
Expand project in project bar actions reversed after closing another project

### ISSUE THREAD

**Issue by Unentokku** [Scirra/Construct-3-bugs#208]
## Problem description

When you close another project while a project is collapsed/minimized most actions that should uncollapse/expand the project now does the reverse.

## Steps to reproduce

1.Open 2 projects, 
2.Collapse one of the projects in the Project Bar
3.Close the other project
4.Expand the remaining project
5.Close or open any tab of the project

## Observed result

The project collapses every time you close a tab

## Expected result

For the project to stay expanded or be expanded if it wasn't already

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed in r28.

Thanks for spotting that one.
