### ISSUE TITLE
ReflectY Effect behaves differently on C3 runtime vs C2 runtime

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#2080]
## Problem description
My reflectY effect behaves differently between C2 runtime and C3 runtime. In the C2 runtime the background is reflected across the top line of the box sprite that is controllable via the mouse. In the C3 runtime, the background is not reflected across the top line, instead, it is offset. This is a simple effect, which is sampling the background and rendering based on a parameter passed into the effect. The parameter (0-1) represents how far up from the bottom of the viewport the top of the box sprite is. There are two addons (two effects.)

## Attach a .c3p

[ReflectYSkendTest.zip](https://github.com/Scirra/Construct-3-bugs/files/2422283/ReflectYSkendTest.zip)
[addons.zip](https://github.com/Scirra/Construct-3-bugs/files/2422285/addons.zip)

## Steps to reproduce

1. Install two addons in addons.zip
2. Install and run project
3. Move mouse cursor to move reflection box
4. Change to C3 runtime and observe different results from reflection box

## Observed result
Reflection box effect changes between C2 runtime and C3 runtime

## Expected result

The reflection box effect should appear to be the same between C2 runtime and C3 runtime.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

Tested on both
Mac OSX and Win 10

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I cannot open the provided project even with both addons installed because the provided addon ID for SkendPow does not match the one used by the project. Judging from the report it is not relevant to the problem anyway. Please make sure you provide a minimal project with all unnecessary parts removed to ensure they do not interfere with the report.

**Comment by AshleyScirra** [comment]
No response so closing.
