### ISSUE TITLE
Mobile Advert not working

### ISSUE THREAD

**Issue by WanKIpas** [Scirra/Construct-3-bugs#2083]
## Problem description

Mobile Advert not working

## Attach a .c3p
i made a simple project just to test it, please download it from my google drive share link..

https://drive.google.com/file/d/1mXGDPxd2UojwIdsSgBmz_VT6ufI8-fEd/view?usp=sharing

## Steps to reproduce

1. Export it to Debug.Apk or Signed release Apk
2. Install and run it in your phone/android
3. Usually there's a test ads banner/interstitial ads from admob 

## Observed result

The banner is not showing, interstitial ads also not showing
if i fill up all the admob details in Admob such as Pubication ID, ads ID and everying, only the interstitial ads is showing, but its not running in full screen. The banner ads is not showing at all.

## Expected result

The test ads should be there.

## Affected browsers

Affected on several of my android phones, i did asked in a forum if anyone else having the same prob. and yes they did..

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

No system details

**Comment by shortercode** [comment]
Just tried your project and it's working fine with my credentials in r120, so you've probably got part of your configuration incorrect.

Please ensure that you have included:
- your application ID
- your publisher ID
- a valid privacy URL
- your advert unit IDs

Also ensure that you have set up a custom provider list with no more than 12 advert providers.

I would also like to point out that you do not need to call "show" for your adverts unless in the create call "show" is set to false.

I'm not sure what you mean by interstitial adverts not showing full screen, by their nature they are always full screen.
