### ISSUE TITLE
Construct 3 runtime projects not loading in Safari

### ISSUE THREAD

**Issue by jinxbunny** [Scirra/Construct-3-bugs#2084]
## Problem description

Projects exported using the Construct 3 runtime aren't loading at all in the latest version of safari

## Attach a .c3p

[sampleproject.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2424794/sampleproject.c3p.zip)

There's an example uploaded here too https://www.jmkit.com/c3test/ that loads in Firefox and chrome but not safari version 12.0 (14606.1.36.1.9)

## Steps to reproduce

Open an exported project html file in safari

## Observed result

Project doesn't load

## Expected result

Project should load

## Affected browsers

* Chrome: /no
* Firefox: no
* Edge: not tested
* Safari: yes

## System details
<details><summary>View details</summary>

  Model Name:	iMac
  Model Identifier:	iMac13,2
  Processor Name:	Intel Core i7
  Processor Speed:	3.4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	32 GB
  Boot ROM Version:	IM131.0115.B00
  SMC Version (system):	2.11f14

</details>

**Comment by AshleyScirra** [comment]
Please do attach a .c3p in case we cannot reproduce the issue you are reporting, which is very common.

**Comment by jinxbunny** [comment]
Updated with a zip of the c3p project

**Comment by AshleyScirra** [comment]
Thanks.

**Comment by AshleyScirra** [comment]
We've fixed a number of issues with the C3 runtime in Safari for the next release. It should be working when that's out.
