### ISSUE TITLE
Int expression crashing game when minified ( r120 )

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#2085]
## Problem description

My game doesn't work anymore if I export it to Android or iOS. This only when using the new release r120, in r111 are no problems. Also, a file (with this problem?) saved in r120 cant be opened anymore in r111. In the preview inside Construct everything works fine.
## Attach a .c3p
[bugreport.zip](https://github.com/Scirra/Construct-3-bugs/files/2425341/bugreport.zip)

## Steps to reproduce

1.open attached file in r111
2.export it to Android debug apk (all 3 export options enabled (minify script etc..)
3.test it on an Android device, and do the same with Release 120

## Observed result
 r111 export works fine, r120 export results in a black screen

## Expected result
blue square should be on screen

## Affected browsers

I worked in chrome

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 727 mb (2.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)</details>

**Comment by shortercode** [comment]
Appears to be an issue with minification. I advise that you just don't use it for your project in r120. We shall try to fix the issue for the next beta but code minification issues can be quite hard to resolve.

Code minification generally has quite a small effect on Android projects, so you may find you don't need it anyway. If your project is quite large I would be interested in how much disabling minification affects the APK size.

**Comment by bubbblebub** [comment]
yes it works perfect without minified script, good to know!

the difference of Filesize is 9.9MB nonminified / 9.7MB minified.

thanks!

Simon

**Comment by shortercode** [comment]
Looks to be any project using the `int`expression with minification is broken.

I've had a look through the code and I've identified the problem, and I'm going to reassign this to @AshleyScirra to fix.

Quick summary:

With minification enabled the system expression "int" is being renamed by the property mangler, but the object reference table holds a quoted reference to the expression. Causing a crash when it is called.

This behaviour does not repeat in r111 but I haven't been able to track back to a change that would have caused it.

**Comment by shortercode** [comment]
Thanks for the size difference, it's about what I expected. Native plugin code for android tends to be quite large compared to JS, but there isn't anything we can do about it really.

**Comment by AshleyScirra** [comment]
Fixed for next release.
