### ISSUE TITLE
Reward video ads not showing on iOS devices

### ISSUE THREAD

**Issue by primaldino** [Scirra/Construct-3-bugs#2088]
## Problem description

I cannot get the reward video ad to show on iOS devices. All other ads work fine and the reward video ad shows up on Android devices so I'm not sure if it is an event issue.

## Attach a .c3p

[mobile advert test.zip](https://github.com/Scirra/Construct-3-bugs/files/2430185/mobile.advert.test.zip)

## Steps to reproduce

1.Export to xcode
2.Test app using TestFlight
3.Click display reward videos

## Observed result

Reward video ads did not load.

## Expected result

Expected reward ads to show. They work on Android devices.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

<details><summary>View details</summary>

</details>

**Comment by pedroriddex** [comment]
I have the same issue on Android devices. All since the last update.

**Comment by shortercode** [comment]
I'm not currently experiencing any issues displaying videos in iOS/Android in the C2/C3 runtimes. Are you still having problems?

People have reported issues showing videos in the past, which have basically been attributed to AdMob not sending a video out ( most of these issues fix themselves after a few days ).

Please check if the "video ready" trigger has occurred, it's worth remembering that there is no guarantee that you will receive an Advert. I think the example project is a little out of date at this point ( my fault for slow response ).
