### ISSUE TITLE
[r27] Layout View reset position to top-left corner UI bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#209]
## Problem description

Whenever I access my data editors for Array and Dictionary json files from the layout view, It always resets my current view position on the layout view to the top-left corner. I had to keep adjusting the layout every time I access the data editors.

This also applies to opening the start page when current tab is on a layout view.

## Steps to reproduce

1. Create New project and make sure you are viewing on a layout tab.
2. Create an Array json file from project bar "Files" folder. It should open it as tab by default.
3. Close this Array data editor tab.

## Observed result

Previous position of user's view on the layout got a reset to the top-left corner.

## Expected result

Should remember user's view position on the layout when switching to new tabs, just like navigating newly open layout tabs and event sheet tabs without the user's view position resetting.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 3.2 gb
Storage usage (approx): 342 mb (10.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Looks like this fundamentally comes from a Chrome bug where it spuriously fires a scroll event to (0, 0) when creating the data editor tab. This could be tricky to work around...

**Comment by AshleyScirra** [comment]
I added in a hack to try to work around this for r29. Let's see how things work out after that release.

**Comment by jaydonteh** [comment]
Works perfectly now!
