### ISSUE TITLE
HTML5 export problem with C3 Runtime

### ISSUE THREAD

**Issue by daleinen7** [Scirra/Construct-3-bugs#2090]
## Problem description

HTML5 export won't start if my project is exported using the C3 Runtime. 

## Attach a .c3p

https://drive.google.com/file/d/1iBQFrb1AlCpQfBVZjQKNy9PPKoJds8MN/view?usp=sharing

## Steps to reproduce

1. Export project to HTML5
2. Try to play it

## Observed result

The Construct 3 load screen appears. Afterwards it's a blank screen.

## Expected result

The project to load and play.

## Affected browsers

* Chrome: yes
(I've only tried to upload to itch.io so it may be specific to itch.io? Also I've exported the demo projects with C3 runtime and they work as expected.)

**Comment by AshleyScirra** [comment]
Your project has the experimental "Use worker" mode enabled, which we've hidden by default because it has known issues. If you turn it off it appears to work fine. Since there are known issues with "Use worker" mode that need to be fixed by Chrome, marking as "won't fix".

**Comment by daleinen7** [comment]
On my end turning off "Use worker" makes no difference. It still goes to a black screen after Construct 3 load screen.

**Comment by AshleyScirra** [comment]
Check for any errors in the browser console. Also try hosting the web export somewhere else in case it's a problem with itch.io.

**Comment by daleinen7** [comment]
Found two errors.

Failed to load resource: the server responded with a status of 403 ()

Uncaught (in promise) Error: fetch '
https://v6p9d9t4.ssl.hwcdn.net/html/1072392/redblackset.js' response
returned 403
    at Function.C3.ThrowIfNotOk (c3runtime.js:40)
    at fetch.then (c3runtime.js:40)

**Comment by AshleyScirra** [comment]
That's an issue with the host, so you'll need to take it up with itch.io.

**Comment by daleinen7** [comment]
I confirmed that it works on a different host. Thanks for the help. I'll
follow up with itch.io.

**Comment by daleinen7** [comment]
Itch.io got back to me and said my project was trying to reference a file
called "redblackset.js". But the real file name is "redBlackSet.js". Is
that file specific to the new runtime?

**Comment by saturnproductions1** [comment]
I'm having the exact same issue and its 3 years later. The C3 loader goes to completion then the screen will go black and the game won't play any more. Use worker mode is already off, and similar error messages appear. Any fixes? This is on itch.io using HTML.

**Comment by AshleyScirra** [comment]
This issue is so old it is most likely unrelated to any problem you're now having. Press F12 and check the browser console. It could well be an issue with the host or your Internet connection and nothing to do with Construct. If you think there is an issue with Construct, please file a new issue following all the guidelines.
