### ISSUE TITLE
Website auto charge credit card

### ISSUE THREAD

**Issue by tyler3327** [Scirra/Construct-3-bugs#2091]
## Problem description

 I didnt realize that construct 3 auto charged credit card for subscription for this I have 2 problems. 1 I could not find any where to cancel yearly renewal. I tried google searching and looking on website.2 An automatic email notifying of upcoming charge would be appreciated. I do want to continue my subscription it's just helpful to know. 

## Steps to reproduce

1.
2.
3.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Hi there, this repository is for bugs with the C3 editor. We can't do much to help you here, for help with your subscription please contact [support@construct.net](support@construct.net).

If you feel like there is a bug with the website we have a separate tracker for the website team [here](https://github.com/Scirra/Construct.net-website-bugs) where they can investigate your issue.
