### ISSUE TITLE
Google Play Sign in Issue

### ISSUE THREAD

**Issue by jook00** [Scirra/Construct-3-bugs#2093]
## Problem description

When using the Google Play object, signing in does not initiate sign in properly. Usually a quick flicker or nothing at all.

## Attach a .c3p

[GooglePlaySignIn.zip](https://github.com/Scirra/Construct-3-bugs/files/2431161/GooglePlaySignIn.zip)

## Steps to reproduce

1. Insert the Google Play object (already in the attached)
2. Export as Debug APK
3. Run app

## Observed result

User does not get signed into Google Play services.

## Expected result

User should get the dialog to sign in and successfully sign in.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 357 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by QuasarX** [comment]
@jook00  Did you setup your GooglePlay account?
1.) You need signed apk
2.) You need add "test users" for this app
3.) You need use "Sign-up URL" and accept test program
4.) You need install this app from GooglePlay

**Comment by shortercode** [comment]
Thanks for the extra information @QuasarX 

@jook00 for the google sign in to appear within your app you have to complete several additional security steps, otherwise the sign in dialog will just close itself as soon as you try to open it.

Please refer to the documentation at [https://www.construct.net/gb/make-games/manuals/construct-3/plugin-reference/google-play](https://www.construct.net/gb/make-games/manuals/construct-3/plugin-reference/google-play) for instructions on how to use the Google Play plugin.

If you need to create a keystore then C3 can create one for you, and will give you the SHA1 signature for your key when it is created. Otherwise you will need to use the `keytool` command line tool provided with the JDK ( java development kit ) to get the signature of your key.

**Comment by jook00** [comment]
> @jook00 Did you setup your GooglePlay account?
> 1.) You need signed apk
> 2.) You need add "test users" for this app
> 3.) You need use "Sign-up URL" and accept test program
> 4.) You need install this app from GooglePlay

I have a few signed APK already on the store that worked fine on C2, but not on C3. Do you still need "Test users" even if you are testing on production APK downloaded from GooglePlay? Both games Football Dash and Soccer Dribble Flick do not let the user access GooglePlay.

**Comment by jook00** [comment]
I think I was able to figure it out as I missed the API step. I believe it works now and looking to update the rest of my apps. Thanks.

**Comment by jook00** [comment]
> 1.) You need signed apk
> 2.) You need add "test users" for this app
> 3.) You need use "Sign-up URL" and accept test program
> 4.) You need install this app from GooglePlay

@QuasarX I have followed these instructions as well as the documentation that @shortercode sent. Still have issues with especially Football Dash. Any other information I can provide that might be able to shed some light on this issue?

**Comment by dimielannes** [comment]
i have this problem too....
the login work 100% with runtime construct2 (web and mobile) but NOT work (web and mobile) with runtime construc3 ...

if i preview the project with runtime "C2", login with my google account, close project, run preview with runtime "C3", auto-login works....

I have no more ideas....
![error](https://user-images.githubusercontent.com/8438162/48127774-b1f80680-e26b-11e8-979e-cda9965178ee.png)

**Comment by QuasarX** [comment]
@dimielannes Open new bug report. This closed so can't be fixed

**Comment by lumicreative** [comment]
Resubmitted here
[https://github.com/Scirra/Construct-3-bugs/issues/2275](url)
