### ISSUE TITLE
Trying to drag&drop an event/action that references a local variable, crashes the editor

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#2095]
## Problem description

Trying to drag&drop an event/action that references a local variable into another event (where this variable is not visible), crashes the editor.

## Attach a .c3p

https://www.dropbox.com/s/22u36wx2fcaen7g/bug2.c3p?dl=0

## Steps to reproduce

Try to drag any action from event #2 to event #1

## Observed result

Program crashes.

## Expected result

A warning message should be displayed.

## Affected browsers

* Chrome: YES
* Desktop build: YES

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 113 gb
Storage usage (approx): 373 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

The Clipboard API is not supported. Some clipboard features may be unavailable.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
This doesn't crash in our development builds, so the release build minification is probably interfering somehow, and those problems are always difficult...

**Comment by AshleyScirra** [comment]
Just noting for myself that the verification code involved here seems related to #1729

**Comment by AshleyScirra** [comment]
This is really complicated but I think I've got something which covers this for the next release. It would be worth testing it a bit when it comes out though to make sure it covers all possible cases. Let me know if you have any other issues when it's out.
