### ISSUE TITLE
Desktop build: Trying to paste text into sprite editor crashes the program

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#2096]
## Problem description

If you accidentally press Ctrl-V in sprite editor window, and the clipboard contains text, the program crashes.

## Attach a .c3p

not needed

## Steps to reproduce

1. Open Notepad, type any text, copy it into clipboard.
2. Open Desktop Build, create a new Sprite.
3. In the Animations/Sprite editor press Ctrl-V

## Observed result

Construct crashes.

## Expected result

Should not crash.

## Affected browsers

* Desktop Build only

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Unexpected token a in JSON at position 0 @ SyntaxError: Unexpected token a in JSON at position 0 at JSON.parse () at ǃv.ǃm.ǃpa.ǃv.ǃViW.ǃSw.then (https://editor.construct.net/r120/main.js:81:933207) at 
Stack: SyntaxError: Unexpected token a in JSON at position 0 at JSON.parse () at ǃv.ǃm.ǃpa.ǃv.ǃViW.ǃSw.then (https://editor.construct.net/r120/main.js:81:933207) at 
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Mon Oct 01 2018 22:50:51 GMT+1000 (AUS Eastern Standard Time)
Uptime: 429.7 s

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release
