### ISSUE TITLE
Effects do not work when there is no movement.

### ISSUE THREAD

**Issue by cihanyakar** [Scirra/Construct-3-bugs#2099]
## Problem description

I added some background effects but they stop when there is no moving object.

[pulse.zip](https://github.com/Scirra/Construct-3-bugs/files/2437510/pulse.zip)

## Steps to reproduce

1. Add "Pulse Effect" to any object
2. Run

## Observed result

Animated pulse effect

## Expected result

Paused pulse effect

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>
Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r120 (stable)
Language setting: en-US
</details>

**Comment by shortercode** [comment]
I'm not familiar with the pulse effect, but I can confirm that it appears to pause while the sprite is not moving. I've assigned to @AshleyScirra to review if this is actually a bug, or expected behaviour.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
