### ISSUE TITLE
[R16] Re-ordering layouts result in a crash

### ISSUE THREAD

**Issue by LanciferStudios** [Scirra/Construct-3-bugs#21]
## Problem description

When creating and/or duplicating layouts in the Project window, re-ordering the layouts will cause C3 to crash 100% of the time.
## Attach a .c3p
https://1drv.ms/u/s!AmdqPkCR7Kazg3M3i8CxnhC1LMTl
However, reproduction is possible in a new project. 

## Steps to reproduce

1. Create new project.
2. Add or duplicate 2 or 3 new layouts in the Project window.
3. Attempt to drag-n-drop the layouts in a different order.

## Observed result

C3 crashes on release of the mouse button after attempting to drag-n-drop the layouts.

## Expected result

Re-order the layouts by way of drag-n-drop, without crashing C3.

## Affected browsers

* Chrome: yes
* Firefox: n/a
* Edge: n/a
* Safari: n/a

## System details

Crash report is included below.

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r16/main.js, line 61, col 71864
Message: Uncaught TypeError: ne.ǃoU is not a function
Stack: TypeError: ne.ǃoU is not a function at ee.ǃak (https://editor.construct.net/r16/main.js:61:71864) at window.ǃXX.ǃXX.ǃrw (https://editor.construct.net/r16/components/bars/projectBar/projectBar.js:1:13544) at window.ǃXX.ǃXX.ǃqd (https://editor.construct.net/r16/components/bars/projectBar/projectBar.js:1:13460) at Array.ǃqD.ǃp.ǃz.ǃp.ǃqH.ǃqR.m (https://editor.construct.net/r16/components/bars/projectBar/projectBar.js:1:3231) at ǃp.Event.ǃWXR.ǃWXG (https://editor.construct.net/r16/main.js:2:283188) at ǃp.ǃd.ǃLo.ǃqN.dispatchEvent (https://editor.construct.net/r16/main.js:2:281769) at ǃp.ǃd.ǃLo.ǃqN.ǃpYE (https://editor.construct.net/r16/main.js:2:488082) at ǃp.ǃd.ǃLo.ǃUT.ǃgP (https://editor.construct.net/r16/main.js:2:494666) at HTMLDocument.ǃRP.ǃgX.he (https://editor.construct.net/r16/main.js:2:490605) at HTMLDocument. (https://editor.construct.net/r16/main.js:2:278451)
Construct 3 version: r16
URL: https://editor.construct.net/index.html
Date: Thu Apr 06 2017 17:54:52 GMT-0400 (Eastern Daylight Time)
Uptime: 185.6 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5450 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Previous forum report to also check: https://www.scirra.com/forum/error-change-layout-order-by-mouse-drag-and-drop_t189598

**Comment by AshleyScirra** [comment]
Should be fixed in r17.
