### ISSUE TITLE
Animation Editor crops images instead of resizing, crashes

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#2100]
## Problem description

Resizing the image crops it. When trying to undo, the editor often crashes.

## Attach a .c3p

https://www.dropbox.com/s/rxfqif5c6owh5if/bug3.c3p?dl=0

## Steps to reproduce

1. Double click the sprite to open Animation Editor. 

2. Select the second frame, click Resize tool on the top panel. Enter the following values:
width=200
height=100
Keep aspect ratio=off
Image=Stretch
Smooth=off
Apply to whole animation=On

3. Without closing the editor try pressing Ctrl-Z a couple of times, switching different frames. 

## Observed result

The image will get cropped instead of resizing.  (This seems to only happen in the Desktop Build)

After pressing Ctrl-Z several times very often the editor will crash. This happens in both Web version of C3 and in Desktop Build.

## Expected result

With "Stretch" option the image should be resized, not cropped.
Ctrl-Z should not cause crashes.

## Affected browsers

* Chrome: yes
* Desktop: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃeuf' of null @ TypeError: Cannot read property 'ǃeuf' of null at i.then.then.then.then.then (https://editor.construct.net/r120/main.js:81:866404) at 
Stack: TypeError: Cannot read property 'ǃeuf' of null at i.then.then.then.then.then (https://editor.construct.net/r120/main.js:81:866404) at 
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Wed Oct 03 2018 15:38:02 GMT+1000 (AUS Eastern Standard Time)
Uptime: 16.3 s

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by DiegoScirra** [comment]
Can't figure out the cropping instead of resizing part.

I did fix a crash following those steps though. So maybe the two issues where related. Let me know how it is working in the next beta release.

**Comment by AshleyScirra** [comment]
r123 is now out, please check again!

**Comment by dop2000** [comment]
Appears to be fixed now, thank you!

**Comment by AshleyScirra** [comment]
Thanks for confirming.
