### ISSUE TITLE
Build failed.

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#2101]
Android build fails if exported as "Signed Release APK".
Here is the error in the assembly, I observe:
![scr1](https://user-images.githubusercontent.com/33450672/46403392-cea89800-c71b-11e8-9fcd-9874587dd78a.png)
![scr2](https://user-images.githubusercontent.com/33450672/46403394-cf412e80-c71b-11e8-8bba-925926c00c4d.png)

**Comment by shortercode** [comment]
I'm afraid the only useful line in that build log is `:app:trasnfromDexWithDexForRelease FAILED` and it doesn't tell me much more than it failed to compile the native code.

Can you provide me with a project this repeats with, or does this happen with a blank project?

**Comment by ERAgames777** [comment]
@shortercode Yesterday the build was successful with one of the project, I tried it now, I also get an error.
I try to make an empty project and the error does not occur.

**Comment by shortercode** [comment]
It's possible it's down to a combination of cordova plugins, do you use any third party plugins with that project?

**Comment by ERAgames777** [comment]
Yes, I use Photon plugin also UnityADS. I tried the build with AndroidStudio and it works, in AndroidStudio also manages to make a ready APK. I can throw you a project, that's just not in the general review. @shortercode

**Comment by ERAgames777** [comment]
@shortercode 
Please tell me your mail will be sent to him.

**Comment by shortercode** [comment]
Sure thing, send it to iain@scirra.com and I'll take a look. I would appreciate it if you packaged it up with any required plugins, saves me having to search around for them.

**Comment by ERAgames777** [comment]
@shortercode 
strange, the project is already releasing apk without errors ... maybe it’s a connection failure?

**Comment by jook00** [comment]
@ERAgames777 I had the same issues yesterday night. It resolved this morning. Wondering if it's a server side issue?

**Comment by ERAgames777** [comment]
@shortercode @jook00
Yes, it was a problem with the server, not with the project. Now export without errors.

**Comment by shortercode** [comment]
I'm not aware of any issues with the server, the periodic issue we've had over the last few months should have been resolved and the stack you sent me claimed a compilation error. It could have been an issue with a dependency changing or being unavailable.

Anyway, if the project now builds then that's all good. Would have been nice to know the issue, but we've probably missed the boat if it's working now.
