### ISSUE TITLE
Export Manager Error in Safari

### ISSUE THREAD

**Issue by TinyMartian** [Scirra/Construct-3-bugs#2102]
## Problem description

I'm unable to download my games from the Construct Editor in Safari because of an error. Error reads:

**Safari Can't Open the Page**
Safari can't open the page "blob:https://editor.construct.net/8562ab21-d947-4fc1-9514-caf5bec9ff90". The error is: "The operation couldn't be completed. (WebKitBlobResource error 1.)" (WebKitBlobResource:1)

<img width="594" alt="screen shot 2018-10-03 at 4 03 11 pm" src="https://user-images.githubusercontent.com/32405090/46445495-07506d80-c72c-11e8-87f2-4d6b9dadf652.png">

## Steps to reproduce

1. Menu > Project > Export > Web (HTML5) > Choose export options (Deplicate images, minify script) > click on project zip link > error

or

2.  Menu > Project > Export > Web (HTML5) > Choose export options (Deplicate images, minify script) > Open export manager > select project > Click the download button > error

3. Menu > Project > Save As > Download Copy > Enter the name of the file to download > Script runs > nothing is downloaded

## Observed result

Can't download project from Safari. I can however download the .c3p file from Dropbox.

## Expected result

I expected to be able to download my project.

## Affected browsers

* Chrome: haven't tested
* Firefox: yes and works fine
* Edge: haven't tested
* Safari: yes and doesn't work at all

## System details

Safari 12.0 on a iMac running MacOS High Sierra 10.13.6

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Safari 12 seems to have broken all blob URL downloads. I haven't been able to find a workaround, so I'm assigning to @AshleyScirra to see if he can come up with something.

**Comment by shortercode** [comment]
We've been unable to find a workaround for this. I have filed a bug with webkit [here](https://bugs.webkit.org/show_bug.cgi?id=190351)

**Comment by AshleyScirra** [comment]
Since a bug has been filed with WebKit let's close this issue and follow up on that bug report instead.

**Comment by AshleyScirra** [comment]
An Apple engineer mentioned in that comment it's due to target="_blank" on the link, which is set by a default `<base target="_blank">` tag the editor uses. Setting the download links to use target="_self" (the default) appears to work around the issue!
