### ISSUE TITLE
Zoom stuck!!!

### ISSUE THREAD

**Issue by isaacMuniz** [Scirra/Construct-3-bugs#2103]
## Problem description

In any project, if I zoom out in an event sheet to the max, it will not return, the zoom will get stuck.

## Steps to reproduce

1.Open an event sheet with any c3p.
2.Zoom out in the event sheet to the max with Ctrl + mouse wheel.
3.Try to zoom it back.

## Observed result

It doesn't zoom back.

## Expected result

It should zoom back.

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

**Comment by AshleyScirra** [comment]
It's not getting stuck, and the editor is actually applying a minimum size of 0.1em, but it looks like browsers don't display text any smaller than 0.5em. So any zooming in the 0.1em-0.5em range has no visible difference. I've adjusted the minimum size to 0.5em for the next release so you don't end up zooming in a range that doesn't change anything.
