### ISSUE TITLE
Editor Crash on Preview after swapping objects.

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2104]
## Problem description

this is a user project from the forum I was trying to solve his issue but found this bug when replacing objects

## Attach a .c3p
[busters escape v8-3 .zip](https://github.com/Scirra/Construct-3-bugs/files/2448243/busters.escape.v8-3.zip)

## Steps to reproduce

- Under the Group - 

> Enemy Z-Order

 see this event

> + System: Every 0.1 seconds
> -> GhostHunter: Set ZOrder to round(Self.Y)
> -> System: Sort GhostHunter Z order by ZOrder

- then select both related actions 
- then right click replace object for both actions.   
- replace with the **Ghost hunter Body** Object

Then click preview

## Observed result

editor crash (error report below)

## Expected result

no crash

## Affected browsers

* Chrome: yes only tested

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: cannot find instance variable export index
Stack: Error at Function.ǃv.ǃVPQ (https://editor.construct.net/r120/main.js:2:140703) at t (https://editor.construct.net/r120/main.js:2:104357) at window.assert (https://editor.construct.net/r120/main.js:2:104760) at t.ǃvn_ (https://editor.construct.net/r120/main.js:81:123557) at window.ǃpq.ǃeGK (https://editor.construct.net/r120/main.js:81:349073) at window.ǃpq.ǃv$K (https://editor.construct.net/r120/main.js:81:341817) at v.map (https://editor.construct.net/r120/main.js:81:305149) at Array.map () at e.ǃv$K (https://editor.construct.net/r120/main.js:81:305138) at n.map (https://editor.construct.net/r120/main.js:81:296313)
Construct 3 version: r120
URL: https://editor.construct.net/r120/index.html
Date: Thu Oct 04 2018 22:57:43 GMT+0100 (British Summer Time)
Uptime: 752 s

Platform information
Browser: Chrome
Browser version: 71.0.3570.0
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3570.0 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
This doesn't reproduce in my development build, only the release build, so I suspect script minification is interfering which is always difficult to deal with...

**Comment by AshleyScirra** [comment]
Think I finally got to the bottom of this. Should be fixed for the next release.
