### ISSUE TITLE
There's no way to rotate a 9patch object with actions

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2105]
## Problem description

In the C3 runtime you can rotate 9patch objects in the editor, which is pretty cool, but there's no way to do the same via actions.

## Attach a .c3p

Not needed.

## Steps to reproduce

Not needed.

## Observed result

There's no action to rotate a 9patch object.

## Expected result

A "set angle" action for 9patch object.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Well spotted, bit of an oversight there. Fixed for next release.
