### ISSUE TITLE
Inverting the event "Is overlappping another object" is not picking objects correctly (C3 R120)

### ISSUE THREAD

**Issue by Fib100** [Scirra/Construct-3-bugs#2106]
## Problem description

I'm using "Is overlapping another object" to lower the opacity of sprite objects. That works fine. When the 2 sprites are overlapping the opacity is changed.

But when they are NOT overlapping I want the opacity to be set back to 100. So I use the inverted "Is overlapping another object", but the non overlapping sprites are not getting picked by the inverted event properly.

It appears that the inverted event only occurs when ALL sprite objects are not overlapping, rather than the event occuring for individual instances.

## Attach a .c3p
[Sprite_IsOverlapping_Bug.c3p](https://www.dropbox.com/s/dyoif3a13fdu8cw/Sprite_IsOverlapping_Bug.c3p?dl=1)

## Steps to reproduce

1. Open the .c3p file in Construct 3
2. Run the layout
3. Use the mouse to click and drag the pink box (it has the drag and drop behavior)
4. Drag the pink box over the top of the blue circles

## Observed result

Observe that when the pink box is overlapping the blue circles, the blue circles will have opacity lowered correctly. But the opacity will **not** return to 100 unless **none** of the blue circles are being overlapped by the pink box.

## Expected result

The opacity of the blue circles should return to 100 per individual instance rather than in groups.

## Affected browsers

* Chrome: yes
* Firefox: not sure
* Edge: not sure
* Safari: not sure

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 172 mb (2.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's actually working correctly. "Box is not overlapping sprite" is not true until it's not overlapping any sprites. Otherwise you'd get a nonsensical result: a "box is not overlapping sprite" event running even though it is overlapping a sprite.

There are two simple workarounds:
- swap the objects so it says "sprite is not overlapping box" instead of "box is not overlapping sprite"
- use "every tick - set opacity to 100" above the "is overlapping" event. The overlap check underneath it then overrides the opacity if it is overlapping. This also has the benefit of only doing each collision check once.

**Comment by Fib100** [comment]
Ok I see. Swapping the objects in the event works. Thanks @AshleyScirra.
