### ISSUE TITLE
Tooltip warning about using decimals when creating variables

### ISSUE THREAD

**Issue by 3dParadox** [Scirra/Construct-3-bugs#211]
In the create variable dialog, the tooltip on the number data field warns of an invalid value, suggesting neighboring integers.
Doesn't seem to affect anything if you use decimals. Just a misplaced warning in both global and instance variable dialogs.

![image](https://cloud.githubusercontent.com/assets/8099192/26090711/5098402e-39cc-11e7-82f6-28275879cb2b.png)

## Attach a .c3p

Create a new project

## Steps to reproduce

1. add a global variable. (first noticed it in an Instance variable)
2. enter 4.5 in the number field.
3. the tooltip suggesting you use 4 or 5.

## Observed result

the tooltip is backseat driving man, I don't need this pressure.

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
That's weird. Not sure why Chrome shows that tooltip when it also accepts the value. I had to override the tooltip with a different one, so I just made it say "initial value" for r28.
