### ISSUE TITLE
Mobile Advert Crashes APK on Run

### ISSUE THREAD

**Issue by lumicreative** [Scirra/Construct-3-bugs#2111]
## Problem description

When you have a mobile advert in your file, exporting as APK, and running causes the game to crash.

## Attach a .c3p

[Mobile Advert Crash.zip](https://github.com/Scirra/Construct-3-bugs/files/2453456/Mobile.Advert.Crash.zip)

## Steps to reproduce

1. Create a new project
2. Insert the Mobile Advert object
3. Including project details and export as APK (debug)
4. Install APK
5. Run APK

## Observed result

Game crashes before even opening the first screen.

## Expected result

Should not crash when opening game with mobile adverts.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 420 mb (5.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 690 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by chris200x9** [comment]
Can confirm it also crashes with a signed APK.

**Comment by Kyatric** [comment]
https://www.construct.net/fr/forum/construct-3/general-discussion-7/mobile-advert-crashes-apk-138399
For further reference/reports/discussions of other users.

**Comment by shortercode** [comment]
Just having a look at this, it appears Google have updated the admob SDK to require the application ID to be included in the manifest, and are forcing the app to crash if it isn't. I'm not sure why they decided this was a good idea.

All versions of C3 will be affected by this, as they all use the latest version of the admob SDK.

I'm investigating whether I can fix this temporarily by getting the build server to use an older version of the admob SDK, which should "just work". Although we may experience version mismatch if people are using multiple google services based plugins.

The correct fix for this will require a new C3 release.

**Comment by shortercode** [comment]
Okay I have released  `construct-mobile-advert@1.2.6` which is used by the C3 plugin `Mobile Advert`. As a point release it will be automatically available now.

The only change is to use version 16.0.0 of the admob SDK instead of the latest. This should work correctly, so you won't see the crash anymore.

If you do experience a crash or a build error please post it here and I will see if I can resolve it.

**Comment by MaximMan** [comment]
Thanks guys!!!!!! Admob plugin earned. In test mode for sure.

**Comment by sotano42** [comment]
Following this thread... since the last patch to fix it, interstitial videos are always failing to load... does it have anything to do with this fix?

**Comment by AshleyScirra** [comment]
@shortercode - this has been open for a while with a fixed tag, can it be closed?

**Comment by shortercode** [comment]
I've kept it open as a reminder to myself that I need to add compatibility with the latest version of the admob SDK. I will create a separate bug for that and close this.
