### ISSUE TITLE
Editor crashes when editing events in a eventsheet on a pop-up window on a clean (NEW) project.

### ISSUE THREAD

**Issue by aiaicaptain** [Scirra/Construct-3-bugs#2112]
## Problem description

When I undock the event sheet and then make a pop up window so I use one monitor for eventsheets and one for the editor - when creating and editing events, the whole editor crashes.

## Attach a .c3p

I don't have a project as the issue is not project related. It happens on a new empty project.

## Steps to reproduce

1. Undock eventsheet.
2. Make pop up window.
3. Create an event on the pop up widnow event sheet.

## Observed result

Editor crashes with info I pasted below.

## Expected result

Editor to not crash

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃv.ǃiL (https://editor.construct.net/r120/main.js:2:111390) at Function.ǃvd (https://editor.construct.net/r120/main.js:2:206734) at new ǃv.ǃV.ǃKY.ǃNKL (https://editor.construct.net/r120/main.js:162:119236) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142970) at new window.ǃNq_ (https://editor.construct.net/r120/main.js:162:122491) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142970) at new t (https://editor.construct.net/r120/main.js:162:155552) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142970) at ǃv.ǃV.ǃKY.ǃNKy.ǃXU (https://editor.construct.net/r120/main.js:162:145324) at o (https://editor.construct.net/r120/main.js:162:111214)
Stack: TypeError: unexpected type at Function.ǃv.ǃiL (https://editor.construct.net/r120/main.js:2:111390) at Function.ǃvd (https://editor.construct.net/r120/main.js:2:206734) at new ǃv.ǃV.ǃKY.ǃNKL (https://editor.construct.net/r120/main.js:162:119236) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142970) at new window.ǃNq_ (https://editor.construct.net/r120/main.js:162:122491) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142970) at new t (https://editor.construct.net/r120/main.js:162:155552) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142970) at ǃv.ǃV.ǃKY.ǃNKy.ǃXU (https://editor.construct.net/r120/main.js:162:145324) at o (https://editor.construct.net/r120/main.js:162:111214)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Sun Oct 07 2018 12:31:53 GMT+0300 (Eastern European Summer Time)
Uptime: 41.8 s

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next release.
