### ISSUE TITLE
Custom addons that use svg icon throw exception after installation (on desktop version)

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#2113]
## Problem description

when i install a c3addon file, if the addon is using an svg icon, after the installation is completed an error is thrown, the  installation of the addon happen successfully, i tried the installation of multiple addons and the only difference i find is when an svg icon is used it throws that error. 

## Attach a .c3p

addon with svg icon : https://drive.google.com/open?id=1mRwNJ65N2hXr5xSCoBCKkgLcv3LFrGrK
addon with png icon : https://drive.google.com/open?id=1RjxA-YA9zZemZytKqkeWI16xIw3hRSwz

*these are 2 example i tried with some other plugins as well and the results were consistent  

## Steps to reproduce

install add with svg icon, an error is thrown
install addon with png icon, no error is thrown

## Observed result

an error is thrown

## Expected result

no error is throw

## Affected browsers
i only tried this on the desktop version of c3, i did not try this on the web version, not sure if it's isolated just to the desktop version. 

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: CSS style for dialog min-width must specify the size in units of 'px' @ Error: CSS style for dialog min-width must specify the size in units of 'px' at ǃv.ǃV.ǃXD.ǃVEA.ǃVEO (https://editor.construct.net/r120/main.js:2:294768) at ǃv.ǃV.ǃXD.ǃVEA.ǃVEq (https://editor.construct.net/r120/main.js:2:287635) at ǃv.ǃV.ǃXD.ǃVEA.ǃXU (https://editor.construct.net/r120/main.js:2:286510) at ǃv.ǃV.ǃXD.ǃVEA.ǃXU (https://editor.construct.net/r120/main.js:2:301351) at ǃv.ǃV.ǃKY.ǃNeA.ǃNeJ (https://editor.construct.net/r120/main.js:162:37667)
Stack: Error: CSS style for dialog min-width must specify the size in units of 'px' at ǃv.ǃV.ǃXD.ǃVEA.ǃVEO (https://editor.construct.net/r120/main.js:2:294768) at ǃv.ǃV.ǃXD.ǃVEA.ǃVEq (https://editor.construct.net/r120/main.js:2:287635) at ǃv.ǃV.ǃXD.ǃVEA.ǃXU (https://editor.construct.net/r120/main.js:2:286510) at ǃv.ǃV.ǃXD.ǃVEA.ǃXU (https://editor.construct.net/r120/main.js:2:301351) at ǃv.ǃV.ǃKY.ǃNeA.ǃNeJ (https://editor.construct.net/r120/main.js:162:37667)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Sun Oct 07 2018 09:22:24 GMT-0400 (Eastern Daylight Time)
Uptime: 10.7 s

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by armandoalonso** [comment]
so after trying a few more times, it could also be a timing issue, if you close the install addon dialog before you get the success confirmation, this error is consistent, so it might not have anything to do the icon type. in my testing the addon with png icon must have loaded faster and i did not notice this pattern.

**Comment by armandoalonso** [comment]
here is a gif of me reproducing the issue, and it defiantly seems like a timing issue : https://drive.google.com/open?id=1bZQvrJ1u-aqdkMI-VsjvnEzpKWXa_uON

**Comment by AshleyScirra** [comment]
Gee, I had no idea installing an addon could be slow slow, it's always been semi-instant for me. Anyway I could reproduce it by inserting a wait. It should be fixed in the next build - it'll disable closing the dialog until the install finishes.
