### ISSUE TITLE
Style.css can be overwritten in export

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#2115]
## Problem description

I'm not sure if this is a bug. If you have a css file named "style.css" in project, when you export in _Web (HTML5)_ and _Desktop (NW.js)_  the original style.css is overwritten

![image](https://user-images.githubusercontent.com/23579630/46585388-933a0080-ca70-11e8-816c-d22bf79e50da.png)

The same with "appmanifest.json", "c2runtime.js", "data.js" and "start.js" in Web (HTML5) export.

![image](https://user-images.githubusercontent.com/23579630/46585623-60ddd280-ca73-11e8-93ef-8980198f2f89.png)

## Attach a .c3p

[New project.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2454193/New.project.c3p.zip)

## Steps to reproduce

1. Create a new stylesheet file and call it _style.css_
2. Export the project to NWjs

## Observed result

The original _style.css_ is overwritten with the new.

## Expected result

A warning when you insert a file called style.css. 

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 274 mb (1.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a bit tricky since in general you can't name files the same as any files exported to the root folder of the project, but that's not a fixed list of filenames, since it could vary depending on which dependencies addons require (including arbitrary files brought in by third-party addons). I think the best we can do is ban the common engine filenames, but as I mentioned that only solves it for the common cases.

**Comment by AshleyScirra** [comment]
In the next release it will prevent you from using common filenames that exports use. I think that's the best we can do.

**Comment by el3um4s** [comment]
@AshleyScirra Thank you
