### ISSUE TITLE
Crash when clicked on autocomplete box in animation editor

### ISSUE THREAD

**Issue by cihanyakar** [Scirra/Construct-3-bugs#2116]
## Problem description
The app crashes when clicked on autocomplete box in an animation editor.

## Steps to reproduce

1. Add a sprite
2. Write anything on Name box in Animation Properties
2. When Autocompletebox appears, click it

## Affected browsers

* Desktop build  r120

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: missing key state
Stack: Error at Function.ǃv.ǃVPQ (https://editor.construct.net/r120/main.js:2:140703) at t (https://editor.construct.net/r120/main.js:2:104357) at window.assert (https://editor.construct.net/r120/main.js:2:104760) at Function.ǃK_ (https://editor.construct.net/r120/main.js:2:203869) at e.ǃegi.ǃecO (https://editor.construct.net/r120/main.js:81:776137) at e.ǃegi.ǃVj (https://editor.construct.net/r120/main.js:81:772820) at HTMLDocument.ǃeEZ (https://editor.construct.net/r120/main.js:81:771998)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Mon Oct 08 2018 11:38:20 GMT+0300 (GMT+03:00)
Uptime: 11.3 s

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by cihanyakar** [comment]
![ezgif-2-2dd7f011eddc](https://user-images.githubusercontent.com/5078937/46600091-c4a6e080-caf1-11e8-950b-e3158984541e.gif)

**Comment by DiegoScirra** [comment]
Are you using any third party browser plugins with the desktop build?

The Animations Editor doesn't implement an auto complete box for animation names.

**Comment by cihanyakar** [comment]
@DiegoScirra , i am not sure but I **can't reproduce** it in my laptop. But maybe you can add `autocomplete='off'` attribute to input fields?

**Comment by DiegoScirra** [comment]
@cihanyakar In the computer that you can reproduce this problem, can you check the folder where **Construct3.exe** is, there should be a file called **package.json**.

Can you check if it has a field that looks something like this:

`"webkit": {
	"plugin": false,
	"double_tap_to_zoom_enabled": false
}`

The important bit is the "plugin" entry, it should remain as "false".

**Comment by cihanyakar** [comment]
It is exact same. It seems to be caused by the "chromium" version. There is my test results with different NW.js versions:

```
"0.34.0" ERROR
"0.33.3" ERROR
"0.33.0" ERROR
"0.33.0 beta1" ERROR // Update Chromium to 69.0.3497.81
"0.32.4" OK
"0.32.3" OK
"0.31.2" OK
```

**Comment by AshleyScirra** [comment]
r123 is now out, please check again!

**Comment by cihanyakar** [comment]
Worked, thank you.
