### ISSUE TITLE
LoopIndex Not Incrementing in new Json Plugin

### ISSUE THREAD

**Issue by rhg1968** [Scirra/Construct-3-bugs#2118]
## Problem description

Trying the new json plugin in r121, the loop index in the Json for each appears to stay at 0 when iterating over and array of objects.

https://drive.google.com/open?id=1E4rgrZE_-T7ayOHrlnb92JuY7xfqHFnX

## Steps to reproduce
Run the program and view the loop count

1. Run it.
2. Loops over two items
3. Loop Index stays at 0

## Observed result

Loop Index not incrementing

## Expected result

Loop index should 0 then 1

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
`Loopindex` is for "system" loops. You can get the current index using `JSON.CurrentKey`. When iterating objects this value will be a string, and for arrays it will be a number.

**Comment by rhg1968** [comment]
Ok. Thank you

**Comment by shortercode** [comment]
No worries!
