### ISSUE TITLE
NW.js iframe Playback Doesn't Work (FFmpeg.dll Issue)

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#2119]
## Problem description

Playing back a YouTube video or similar, in an exported NW.js project fails because the _wrong_ FFmpeg binary is being used.

## Attach a .c3p

[NWjs Iframe Video Playback Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2456676/NWjs.Iframe.Video.Playback.Bug.zip)

## Steps to reproduce

1. Open attached project and export it using NW.js
2. Run the win32 or win64 executable
3. Play the YouTube Video and notice error message
4. _Optional:_ Replace ffmpeg.dll with the correct file from [HERE](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases) and retry

## Observed result

Playing back videos in an iframe fails because the wrong FFmpeg binary is being used.

## Expected result

The correct FFmpeg binary should be shipped with all NW.js builds in order to ensure working video playback inside iframes.

## Affected browsers

* NW.js: yes
* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r121 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 1.4 gb (4.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
We cannot ship that other ffmpeg binary, because it includes proprietary patent-encumbered codecs that we do not have permission to distribute. Gaining permission would likely involve royalty payments, either by us or you as the developer, and I don't think it's feasible to go down that path.

NW.js includes support for open media codecs, which should be sufficient to play videos on major sites. If it does not, it's probably something to take up with the site distributor. Alternatively if you're willing to sort out the necessary legal/royalty details then you can switch to the proprietary ffmpeg binary yourself.

This is why we have been blogging so much about open media codecs over the years...

**Comment by TheRealDannyyy** [comment]
Yes I was expecting something like that since there was a similar issue with a 3rd party plugin and NW.js in the past. 

Might still be worth mentioning in the manual that a specific binary, which needs permissions is required in order to playback YouTube videos in NWjs. If mentioning this doesn't require permissions as well of course.
