### ISSUE TITLE
C3 Runtime not worked with Pathfinding behavior (export to Web)

### ISSUE THREAD

**Issue by X-Matrix2018** [Scirra/Construct-3-bugs#2120]
## Problem description

Good evening. I'm making a project of the game (it's not ready yet). If I choose runtime C2, everything works fine, but when I select C3, the load bar reaches 100% and then nothing happens (after export to Web HTML !).
I excluded the maximum possible events from the project and found that this error occurs when the sprite has "Pathfinding"behavior. It has also been tested on a completely new, empty project containing only text, sprite, and specified behavior.

## Attach a .c3p

[testbug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2456802/testbug.c3p.zip)

## Steps to reproduce

1. Export project to Web (HTML5)
2. Open project from the browser

## Observed result

The load bar reaches 100% and then nothing happens

## Expected result

Working project

## Affected browsers

* Chrome: yes
* Opera: yes
* Firefox: no
* Edge: no
* Safari: no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here: both with and without "Minify script" the given project loads fine for me once exported. There might be something wrong with the host or you may have forgotten to upload some files - try pressing F12 to open the browser console and check for any errors there.

**Comment by AshleyScirra** [comment]
Fixed issue #2128 which had a similar problem caused by case-sensitive filenames. This could have affected web exports on case-sensitive servers too. I guess the server I tested on was case insensitive.

**Comment by X-Matrix2018** [comment]
From console:
[SW] Error fetching 'https://lifeatspace.ru/TD/0/redblackset.js' (404 Not Found)

And the server was named redBlackSet.js, after changing the case, everything worked fine. It is strange, but in other intermediate versions of the project such file too was, and it was too in the form of "redBlackSet.js", but no error occurred... And the same mini-project that didn't have "Pathfinding" behavior also worked without errors...

Thanks, now everything works as it should.
C3 is a great tool for creating games and I'm glad I bought it once.
