### ISSUE TITLE
Gamepad commands executes after all other code...

### ISSUE THREAD

**Issue by MihaMS** [Scirra/Construct-3-bugs#2123]
## Problem description
Gamepad commands executes after all other eventsheet code... or something like this.

## Attach a .c3p
[gamepadbug.zip](https://github.com/Scirra/Construct-3-bugs/files/2457947/gamepadbug.zip)
(in same situation keyboard command executes value change, while gamepad - doesn't)

## Steps to reproduce

![image](https://user-images.githubusercontent.com/23280578/46634325-c358d080-cb50-11e8-94a2-e8dcde4092a4.png)

## Observed result
In this example gamepad command doesn't change variable value, like keyboard do.

## Expected result
Gamepad commands executes as commands from a keyboard, in right order...

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Triggers aren't guaranteed to run at any particular time, so different triggers can run at different times.
