### ISSUE TITLE
Windows export issue

### ISSUE THREAD

**Issue by MrWonka** [Scirra/Construct-3-bugs#2124]
## Problem description

running a windows export in visual studio 2017 throws this error. Minifying script does not make a difference. Unhandled exception at line 22, column 3225 in ms-appx://b4c66d69-9c22-4239-8c7c-c11c2628ccfd/scripts/c3runtime.js
0x800a139e - JavaScript runtime error: TextDecoder polyfill only supports utf-8

If needed I can send the project thats causing this

## Steps to reproduce

1.
2.
3.

## Affected browsers

* Chrome: yes/no
* Firefox: yes
* Edge: yes/no
* Safari: yes/no

**Comment by AshleyScirra** [comment]
Please always attach a project otherwise we cannot investigate the problem you are reporting.
