### ISSUE TITLE
Sprite doesn't show up (macOS)

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#2126]
## Problem description

When i create a Sprite in Construct r121, it does only show up in the Layout view as some bright purple color, no matter what color i choose.

![image](https://user-images.githubusercontent.com/30116964/46663046-5c253580-cbbd-11e8-99ab-259459074062.png)

![image](https://user-images.githubusercontent.com/30116964/46662976-1d8f7b00-cbbd-11e8-8ad1-25c2f429d62e.png)

## Steps to reproduce

1. Open C3 121
2. Create a Sprite
3. Flood Fill the sprite with any color
4. Close the Animation Editor

## Observed result

Sprite doesn't take on the chosen color but some totally different.

## Expected result

The sprite to be in the correct color.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r121 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 131 gb
Storage usage (approx): 33 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by joelmayer87** [comment]
I emptied the cache again and now it appears to be working in r121 as well... It did work in r120, i think it would be beneficial to maybe advise users in the popup for updating to delete their complete browser cache, since that seems to be the problem...

**Comment by AshleyScirra** [comment]
It sounds like Construct may have failed to load some resources the first time, and clearing the cache resolved it. Normally this should not be necessary and it seems to be fine for the vast majority of users. Closing since there is nothing to action here, especially without any information from the browser console (this is essential information if anything goes wrong).
