### ISSUE TITLE
Interface randomly missing Icons (Chrome & macOS)

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#2127]
## Problem description

In C3 r121, the interface misses icons on the buttons at random. They all show up if i roll back to r120.

![image](https://user-images.githubusercontent.com/30116964/46663108-870f8980-cbbd-11e8-9e53-59806f92aad8.png)
Missing icons in Project view (Event Sheets/Layouts)

![image](https://user-images.githubusercontent.com/30116964/46663135-955da580-cbbd-11e8-8222-baf67f18a279.png)
Missing icons in Animation Editor (Tool Palette)

## Steps to reproduce

1. Open C3
2. Observe missing icons in UI

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r121 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 131 gb
Storage usage (approx): 33 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by joelmayer87** [comment]
I deleted my cache and tried again and it's even worse now:

![image](https://user-images.githubusercontent.com/30116964/46663514-8f1bf900-cbbe-11e8-9e96-bacef09c5b50.png)
Can't select any color anymore other than black...

AAAH wait, now everything's back... i think, from my limited technical understanding, it's almost like it doesn't fully load the UI because i didn't even restart C3 now but switched tabs and when i went back like three minutes later, everything was back... Didn't happen when i hadn't had the cache emptied though...

**Comment by AshleyScirra** [comment]
Are there any errors in the browser console?

If not then it looks like some kind of GPU driver issue...

**Comment by joelmayer87** [comment]
You may close this issue as well because now it appears to be working. Emptying the cache and restarting Construct seems to have helped especially after waiting a few minutes. If this happens again with future releases i'll make sure to send some Console information ;) Thank you.
