### ISSUE TITLE
Website: Forum search appears to be broken

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#2129]
Sorry for going against rules and not following the step by step guide but it is really kinda self-explanatory:

When you search something on the C3 forums, this shows up:

![image](https://user-images.githubusercontent.com/30116964/46666765-d064d680-cbc7-11e8-82f7-906ecfebb249.png)

A friend of mine whom i'm trying to convince to start using C3 was looking for something in the forums and found it out so it already happens on two computers :D

**Comment by AshleyScirra** [comment]
Please post website bugs here: https://github.com/Scirra/Construct.net-website-bugs
