### ISSUE TITLE
Shortcuts in events no longer work

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#213]
## Problem description

Shortcuts in events no longer work after using image editor.
Tested and affected: D for enable/disable, I for invert.

Don't know how this happens, but it occurs frequently in other contexts.

## Steps to reproduce

With image editor:
1. Open and close image editor.
2. Go into an event sheet.
3. Try to use shortcuts (D or I).

To temporarily correct the problem, C3 must be closed and restarted.

## Affected browsers

* Chrome: yes
Not tested with other browsers.

**Comment by DiegoScirra** [comment]
Fixed in r28.

There was a problem with the image editor still handling keyboard input after being closed.

Please try it out in the next release to make sure everything is working as expected.

**Comment by sebastien-c3** [comment]
Thanks, it also happens without using image editor.
F5 preview key and probably others are affected.
