### ISSUE TITLE
R121 - Draw(iRenderer, iDrawParams) --> iRenderer is null

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#2130]
## Problem description

I think there is a problem with the _Draw(iRenderer, iDrawParams)_ function in plugin SDK. I can replicate it in R121 with the **official Plugin SDK files**.

## Attach a .c3p

[test.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2460220/test.c3p.zip)

[c3-plugin-sdk-v1.4-editorTextPlugin.c3addon.zip](https://github.com/Scirra/Construct-3-bugs/files/2460222/c3-plugin-sdk-v1.4-editorTextPlugin.c3addon.zip)

## Steps to reproduce

[See this video](https://www.youtube.com/watch?v=9eQ9VBY22gw)

[![this.inst.GetQuad()](https://img.youtube.com/vi/9eQ9VBY22gw/0.jpg)](https://www.youtube.com/watch?v=9eQ9VBY22gw)

1. Download the **[Plugin SDK files](https://www.construct.net/en/make-games/manuals/addon-sdk)**
2. Get the **Editor Text Plugin**
3. Add the plugin to a new project

## Observed result

The demo plugin crash

If I insert this in the plugin SDK 

![image](https://user-images.githubusercontent.com/23579630/46669099-bc70a300-cbce-11e8-9394-8593839630cc.png)

**R120**
![image](https://user-images.githubusercontent.com/23579630/46669188-ffcb1180-cbce-11e8-8cbc-c508f45ded76.png)

**R121:**
![image](https://user-images.githubusercontent.com/23579630/46669244-2e48ec80-cbcf-11e8-9cf0-35082fa56b65.png)

## Expected result

The demo plugin works.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details><summary>View details: Console Log</summary>
Uncaught TypeError: Cannot read property 'parentNode' of null
    at content-script.js:159
    at content-script.js:161
    at content-script.js:161
    at content-script.js:620
    at content-script.js:620
    at content-script.js:620
    at content-script.js:927
    at content-script.js:927

blob:https://editor.construct.net/baab585c-b113-429d-ae72-e796d0fe2132:49 
Uncaught TypeError: Cannot read property 'CreateWebGLText' of null
    at MyTextInstance._MaybeCreateWebGLText (blob:https://editor.construct.net/baab585c-b113-429d-ae72-e796d0fe2132:49)
    at MyTextInstance.Draw (blob:https://editor.construct.net/baab585c-b113-429d-ae72-e796d0fe2132:60)
    at ǃu.ǃuIZ.ǃCB (main.js:formatted:42890)
    at u.ǃCB (main.js:formatted:56021)
    at o.ǃCB (main.js:formatted:58650)
    at u.ǃCB (main.js:formatted:57681)
    at window.ǃPa.ǃoM (layoutView.js:1)
    at window.ǃPa.constructor.ǃoC (layoutView.js:1)
_MaybeCreateWebGLText @ blob:https://editor.construct.net/baab585c-b113-429d-ae72-e796d0fe2132:49
Draw @ blob:https://editor.construct.net/baab585c-b113-429d-ae72-e796d0fe2132:60
ǃCB @ main.js:formatted:42890
ǃCB @ main.js:formatted:56021
ǃCB @ main.js:formatted:58650
ǃCB @ main.js:formatted:57681
ǃoM @ layoutView.js:1
window.ǃPa.constructor.ǃoC @ layoutView.js:1
requestAnimationFrame (async)
ǃow @ layoutView.js:1
window.ǃPa.constructor.ǃok.ǃu.ǃSa @ layoutView.js:1
ǃKkb @ main.js:formatted:12995
t @ main.js:formatted:12953
setTimeout (async)
t @ main.js:formatted:12960
</details>

<details><summary>View details: Crash Report Dialog</summary>

Error report information
Type: unhandled exception
File: blob:https://editor.construct.net/baab585c-b113-429d-ae72-e796d0fe2132, line 49, col 32
Message: Uncaught TypeError: Cannot read property 'CreateWebGLText' of null
Stack: TypeError: Cannot read property 'CreateWebGLText' of null at MyTextInstance._MaybeCreateWebGLText (blob:https://editor.construct.net/baab585c-b113-429d-ae72-e796d0fe2132:49:32) at MyTextInstance.Draw (blob:https://editor.construct.net/baab585c-b113-429d-ae72-e796d0fe2132:60:9) at ǃu.ǃuIZ.ǃCB (https://editor.construct.net/r121/main.js:81:6810) at u.ǃCB (https://editor.construct.net/r121/main.js:81:224528) at o.ǃCB (https://editor.construct.net/r121/main.js:81:265066) at u.ǃCB (https://editor.construct.net/r121/main.js:81:249254) at window.ǃPa.ǃoM (https://editor.construct.net/r121/components/editors/layoutView/layoutView.js:1:7048) at window.ǃPa.constructor.ǃoC (https://editor.construct.net/r121/components/editors/layoutView/layoutView.js:1:1803)
Construct 3 version: r121
URL: https://editor.construct.net/r121/
Date: Tue Oct 09 2018 13:21:46 GMT+0200 (Ora legale dell’Europa centrale)
Uptime: 22.1 s

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r121 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Oops, some refactoring in r121 broke this for third-party addons. Should be fixed in the next release.

**Comment by el3um4s** [comment]
@AshleyScirra Thank you
