### ISSUE TITLE
Popup window crash on Chrome

### ISSUE THREAD

**Issue by squalinho** [Scirra/Construct-3-bugs#2136]
## Problem description

Construct 3 crash when i popup the event sheet in a window.

## Attach a .c3p

https://goo.gl/RC3f5L

## Steps to reproduce

1. undock event sheet
2. popup window event sheet
3. in event sheet : system -> every x seconds

## Observed result

Construct 3 crash

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: can't popup

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃv.ǃiL (https://editor.construct.net/r120/main.js:2:111390) at Function.ǃvd (https://editor.construct.net/r120/main.js:2:206734) at new ǃv.ǃV.ǃKY.ǃNKL (https://editor.construct.net/r120/main.js:162:119236) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142970) at new window.ǃNq_ (https://editor.construct.net/r120/main.js:162:122491) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142970) at new t (https://editor.construct.net/r120/main.js:162:155552) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142970) at ǃv.ǃV.ǃKY.ǃNKy.ǃXU (https://editor.construct.net/r120/main.js:162:145324) at o (https://editor.construct.net/r120/main.js:162:111214)
Stack: TypeError: unexpected type at Function.ǃv.ǃiL (https://editor.construct.net/r120/main.js:2:111390) at Function.ǃvd (https://editor.construct.net/r120/main.js:2:206734) at new ǃv.ǃV.ǃKY.ǃNKL (https://editor.construct.net/r120/main.js:162:119236) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142970) at new window.ǃNq_ (https://editor.construct.net/r120/main.js:162:122491) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142970) at new t (https://editor.construct.net/r120/main.js:162:155552) at Function.ǃv.ǃNm (https://editor.construct.net/r120/main.js:2:142970) at ǃv.ǃV.ǃKY.ǃNKy.ǃXU (https://editor.construct.net/r120/main.js:162:145324) at o (https://editor.construct.net/r120/main.js:162:111214)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Thu Oct 11 2018 13:15:32 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 290 s

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 670MX Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
This should have been fixed in r121:

> Event Sheet View: crash adding events in popup window

Please only file bugs which reproduce in the latest beta to avoid filing issues that are already fixed.
