### ISSUE TITLE
Z-Order Bar stops to reorder sprites by Drag and Drop too often

### ISSUE THREAD

**Issue by MihaMS** [Scirra/Construct-3-bugs#2137]
## Problem description
Z-Order Bar stops to reorder sprites by Drag and Drop too often in my project. Restarting Construct fix this, but now I'm tired to restart it, so finally decided to post this issue... I'm tried to reproduce this bug in a more simple situation but unsuccessfully or anyway after opening project it will work alright... The problem seems to appear more often if project uses many objects.
Construct 3 r120, runtime 3, Standalone.

## Attach a .c3p
Hope this screen record will demonstrate the problem - after reordering by drag&drop in z-order bar sprites changes their order in it, but actually - doesn't. After re-selecting it in the scene ("refreshing" z-order bar) sprites again appears in it in in old order...
Sorry my English.
[ZReorderingBug_lq.zip](https://github.com/Scirra/Construct-3-bugs/files/2468851/ZReorderingBug_lq.zip)

## Steps to reproduce

1.
2.
3.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release.
