### ISSUE TITLE
[C3-Runtime] Sprite-Collision works not correctly

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#2138]
## Problem description

The collision about the Tilemap and the Sprite-Object works not correctly on construct 3 runtime. 1 pixel before the object has a collision, the object fire a collision.

**Example:**

No collision found (works correctly):
[Example image 1](https://drive.google.com/open?id=1jgaZVY7yXJDICvlGeAjxZBjFiqlGXPQq)

Collision found (bug):
[Example image 2](https://drive.google.com/open?id=1YjIVwJ-L83oCHCaF8r2DeWzN7MF3eIE8)

**The same left and right:**

No collision found (works correctly):
[Example image 3](https://drive.google.com/open?id=1ZHOptM7gw5LsCnEd4M0IdvvYERFcxSyg)

Collision found (bug):
[Example image 4](https://drive.google.com/open?id=1fZEYWEJe6bzix_uT8rTpm8NulBhPhmwW)

## Attach a .c3p

[Example-File](https://drive.google.com/open?id=1oDx-fSJ1bbSc4mXtdNd4w0yjDGjB6wyP)

## Steps to reproduce

1. Open the example file
2. Go over the object with 1 pixel distance
3. Not works..

## Observed result

Fire a collision, without a collision.

## Expected result

Fire the collision correctly.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r121 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 21 gb
Storage usage (approx): 19 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is by design: exactly adjacent objects count as colliding.

I can't see any difference between the C2 and C3 runtimes with the project, so it doesn't appear to be a C3 runtime issue.
