### ISSUE TITLE
Touch.TouchID is not the same on Android and iOS devices

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2139]
## Problem description

The value returned by Touch.TouchID is not the same (format) on Android and iOS devices

## Attach a .c3p
https://kyatric.com/c3/bugs/2018.11.10.touchID_apple.c3p

## Steps to reproduce

1. Preview the project
2. Touch the screen
3. On touch end, the text displays the touchID

## Observed result

On android it starts at 1 and goes up.
On iPad it starts at 12604200 and goes up.

## Expected result

The same starting value of 1 on both devices

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: not tested
* Safari: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Kyatric** [comment]
As per
https://www.construct.net/en/forum/construct-3/how-do-i-8/touchid-problem-on-safari-138510#forumPost953066

this is likely not an actual bug and likely is to be closed.

**Comment by AshleyScirra** [comment]
Yes, as mentioned you cannot rely on touch IDs having any particular value, other than that each touch has a different value.
