### ISSUE TITLE
Remote preview don't load on Android mobile and tablet

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#214]
## Problem description

Remote preview don't load on Android mobile and tablet.

## Steps to reproduce

1. Lauch remote preview.
2. Try to use url on Android mobile or tablet device.

## Observed result

Remote preview remains stuck on loading screen.
"Loading..." is displayed without ever ending.

## Affected browsers

* Chrome: yes

**Comment by shortercode** [comment]
Please can you give us your platform information ( host device and client device )

**Comment by sebastien-c3** [comment]
All seems to work after Chrome update on different client platforms.
This may be blocking for only testing or deployment on those devices.

**Comment by AshleyScirra** [comment]
Was the device that wasn't working using a cell data connection (e.g. 3G, 4G)? If so I'd suspect NAT/connectivity issues. We're planning on running a TURN server at some point to mitigate that.

**Comment by sebastien-c3** [comment]
Tablet: Samsung Galaxy Tab 4 (wifi only).
Phone: Samsung Galaxy Note 2 (wifi or 3G+).

For friends I don't know. They can play all games via Play Store.
I suppose they have to update and link Chrome by default too.

**Comment by AshleyScirra** [comment]
Was the phone using Wifi or 3G at the time you tested? I meant which connection it was using, not which it has available.

**Comment by sebastien-c3** [comment]
I tried both without the other before updates (eternal loading screen).

**Comment by sebastien-c3** [comment]
NB: After consideration, I'm not sure of anything for the phone.
Homewer, the problem was the same with the tablet using Wifi.

**Comment by sebastien-c3** [comment]
NB: After consideration, I'm not sure of anything for the phone.
However, the problem was the same with the tablet using Wifi.

**Comment by AshleyScirra** [comment]
Closing as I am fairly sure this should be a connectivity issue which is solved when we add a TURN server, which we should be able to do shortly.

**Comment by AshleyScirra** [comment]
@sebastien-c3 - we are now running a TURN server which should ensure devices can always connect using Remote Preview. Can you test whichever devices you have available and see if it works better now?

**Comment by sebastien-c3** [comment]
Yes Ashley, you can ask me all that you want (in a reasonable song and measure :p)! It's very nice news, can we soon be able to copy/paste our "local (not remote)" preview url on diffent browser/tabs like in C2?
Thanks also (off topic) for the TMX import image from project URL, this will make my life easier.
I come back to you after testing, but everything worked after my last laborious updates.

**Comment by sebastien-c3** [comment]
- With mobile data: Eternal loading screen on the phone with the default Samsung browser - but (despite some random bugs probably inherent to my emergency work) seems to work on classic html5 export on my server or on newgrounds -> ok with chrome since it is updated.
- With wifi+data: idem.
- With only wifi: idem.
- With wifi on tablet: same browser problem as phone.
- After installing all Samsung software updates on both: idem.

Definitively a browser compatibility issue?
I'm going to change it for Chrome by default.
