### ISSUE TITLE
Game crashes when in iframe on mobile Safari

### ISSUE THREAD

**Issue by valerypopoff** [Scirra/Construct-3-bugs#2140]
## Problem description

If I export the game and then open it in the iframe, desktop browsers show it fine but my mobile Safari on iPhone 6S crashes after loading and the game never starts: 
![photo_2018-10-11_20-53-04](https://user-images.githubusercontent.com/5064630/46823744-ad891c80-cd97-11e8-8f7f-86f797a22161.jpg)

Same thing with Remote Preview. It reproduces regardless of the runtime2/3. But if I start the game with no iframe, it shows fine on mobile Safari.

If I remove "ArtificialHead" sprite from the top layer, it doesn't crash anymore. If I put it back on the layer, it crashes again. If I remove some other sprite objects from Object types folder, it stops crashing. If I remove some layers, it stops crashing too.

## Attach a .c3p
[Rappers.zip](https://github.com/Scirra/Construct-3-bugs/files/2470084/Rappers.zip)

## Steps to reproduce
1. Open the project
2. Click Remote Preview
3. Open the link in mobile Safari

## Observed result
The page crashes

## Expected result
The game shows up

## Affected browsers
* Chrome: no
* mobile Safari: yes

## System details
iOS 12 (16A366)

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 390 mb (1.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by valerypopoff** [comment]
Updated to r121 but it didn't help

**Comment by valerypopoff** [comment]
Tried from another iPhone with iOS 12.0.1. Crashes too, but 2-3 seconds in

**Comment by AshleyScirra** [comment]
This type of error means the Safari browser itself crashed. It's not normally possible for web page content to do that itself. You should report it to Apple (https://bugs.webkit.org/).

**Comment by valerypopoff** [comment]
@AshleyScirra on another iPhone it looks like this:
![photo_2018-10-11_21-36-25](https://user-images.githubusercontent.com/5064630/46864395-f33ef700-ce22-11e8-802e-c7c934505097.jpg)

Still not web page content?

**Comment by AshleyScirra** [comment]
If Safari crashes often enough it replaces the "a problem occurred" banner with that, and gives up trying to reload the page. So it's the same thing.

**Comment by valerypopoff** [comment]
@AshleyScirra ok, thanks!

I'm gonna report it to Apple (https://bugs.webkit.org/). Do I just go, like, here's the webpage that crashes? Or do I provide details about the engine?

Even if Apple fixes this in the next iOS release, my game won't be working in iOS 12 and iOS 12.1 (≈50% of iPhone users now), is that right?

**Comment by AshleyScirra** [comment]
Follow the same bug report guidelines as we have here and you can't go too wrong.

It's not yet clear what the impact is. However Apple are notoriously slow and unreliable at patching things, which has been something we've been struggling with ourselves for years.

**Comment by valerypopoff** [comment]
@AshleyScirra 
Just in case: problem stops reproducing when I switch "Downscaling quality" from "High" to "Medium". And I needed "High" because otherwise I get half-transparent pixels here and there at the edges of the sprites. I'm nor sure if have to report this because it has already addressed by someone earlier and you said it was going to be fixed

**Comment by AshleyScirra** [comment]
Are you sure you're not just running out of memory? Changing downscaling quality from "High" to "Medium" will save memory. Other than that it just adjusts the packing on spritesheets.

**Comment by valerypopoff** [comment]
@AshleyScirra  You mean iPhone storage? Well the first iPhone has 14GB out of 16GB. The second one has 43GB out of 64GB.

**Comment by AshleyScirra** [comment]
No, RAM. How much image memory does your project use?

**Comment by AshleyScirra** [comment]
Run the debugger or check the ImageMemoryUsage expression.

**Comment by valerypopoff** [comment]
@AshleyScirra it's 707.4 mb on "High" Downscaling quality and 367.4 mb on "Medium"

**Comment by AshleyScirra** [comment]
It sounds like you're killing the browser tab by running out of memory then. 700mb is a pretty extreme level of memory use. See this blog: https://www.construct.net/en/blogs/construct-official-blog-1/remember-not-to-waste-your-memory-796

**Comment by valerypopoff** [comment]
Thanks! It would have made my life easier if had read this blog earlier.

The guys from webkit said the same thing. >600mb is killing the page. Besides that, there's two things about Construct I didn't know that lead to the problem:
– High downscaling quality takes up twice the memory, not twice the computing time. Just counterintuitive to me.
– If a sprite has tons of animations, they are all loaded in to memory even if only one of them is actually used on the layout. This is a surprising and a bitter fact since it was so convenient to use a single sprite's animations for "a database of all possible sprite states used in the game"
