### ISSUE TITLE
Saved files

### ISSUE THREAD

**Issue by lumicreative** [Scirra/Construct-3-bugs#2142]
## Problem description

Saved files are showing up as a series of numbers and letters

## Attach a .c3p

<img width="490" alt="screen shot 2018-10-11 at 9 59 36 pm" src="https://user-images.githubusercontent.com/5299698/46848885-3c4e6700-cda1-11e8-941a-9873ab1dc11e.png">

## Steps to reproduce

1. Save files as versions in Dropbox (e.g. "game_001", "game_002")
2. Open Cloud Open and locate the files
3. Some files appear as, "20c59c92b40"

## Observed result

Some files appear as a series of numbers and letters like, "20c59c92b40". Also, if navigating to that folder location outside of Construct, the files are repeated with (1) indicated a duplicate file.

## Expected result

Files should save with same filename you give it without being scrambled in Construct or having duplication in saved files.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Thanks for the report, there was a typo in the caching code when creating a new file. If your restart the editor or refresh the file dialog it should show you the correct file names, is that correct?

The label your seeing is the files revision ID, it was mistakenly being put into the name parameter when the file is added to the cloud meta data cache.

**Comment by lumicreative** [comment]
Correct, refreshing the editor seems to fix the issue. It keeps happening as I save new versions.

**Comment by lumicreative** [comment]
Refreshing clears it, but it keeps coming back when I save a new version.

**Comment by shortercode** [comment]
Yes it should only appear for files that have been recently created. Any existing files will appear with the correct name, as it's only wrong in the cache. This should be fixed in r123.

**Comment by lumicreative** [comment]
Thanks!
