### ISSUE TITLE
C3 Runtime doesn't work for remote preview ios12 if there's a text object in the project

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#2143]
## Problem description

It's just a black screen when there's a text object testing remote view on an iphone x ios12 , when you remove the text object it runs normally.

## Attach a .c3p

[Nipp.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2472850/Nipp.c3p.zip)

## Steps to reproduce
1. Run Remote Preview on iPhone x or something
2.Doesn't work, black screen
3. Delete Text object and run again
4. works

## Observed result

Black screen in Safari

## Expected result

Running successfully 

## Affected browsers

* Safari: yes

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_0
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r121 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.5 gb
Storage usage (approx): 1.1 gb (14.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by damjancd** [comment]
@AshleyScirra  Tested on another iPhone X, same iOS version and it worked fine. Retested the same link on my iphone and it didn't. I'll try restarting or something and see if that results in anything good.

But I guess the problem is on my side, sorry for bother.

**Comment by damjancd** [comment]
I had some experimental features enabled in iOS Safari and I copied over the setup from the iphone that worked, cleared cache and website data and it works perfectly fine now. 

Next time I'll test on at least two devices before complaining :p

**Comment by AshleyScirra** [comment]
Alright, thanks for checking. If you enable experimental features you might have gotten incomplete WebGL 2 support or something else unfinished that caused the issue, so best to only test with stable-released features.
