### ISSUE TITLE
R121 Construct 3 Runtime doesnt work in ios 12

### ISSUE THREAD

**Issue by kai902000** [Scirra/Construct-3-bugs#2146]
## Problem description

I tried exporting as a cordova project, but it doesnt work.  The screen just show as the default color and it is not going to the start page.

## Attach a .c3p

[test.c3p](https://drive.google.com/open?id=1I0WBn2k6MIy3KtUt5VtndCSAMHYxNMmR)

## Steps to reproduce

1. Exported as Cordova IOS using C3 Runtime
2. Run in xcode

## Observed result

First Page doesnt load.

## Expected result

Should load the start page.  It works for C2 Runtime. (Newly created project doesnt have this issue)

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r121 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 38 gb
Storage usage (approx): 183 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Are you using the iOS simulator? If so it sounds a lot like issue #2079.

**Comment by kai902000** [comment]
Nope, is a real hardware.  If i create a new project and export with c3 runtime.  Everything is fine.  But my previous project wont work.

**Comment by AshleyScirra** [comment]
The attached project just displays a blank white screen. It appears all objects and events that might have created anything have been deleted. Therefore, displaying a blank white screen is the expected result.

Please make sure you attach a project that can usefully demonstrate the issue being reported.

**Comment by kai902000** [comment]
sorry, i will attach another version in the weekend.  Didnt notice i accidentally delete the object.
