### ISSUE TITLE
TiledBackground.imageOffsetX do not update on the tick it was set.

### ISSUE THREAD

**Issue by LapinChat** [Scirra/Construct-3-bugs#2147]
## Problem description

When TiledBackground.imageOffsetX is set, the TiledBackground object will update on the next tick.

## Attach a .c3p

https://drive.google.com/file/d/1Rjt8jhY17VoEcos0AYoFqwEEs1SawuIA/view?usp=sharing

## Steps to reproduce

Run the example project.
You will notice a small lag between level platforms and background.
You can also look at the debug text showing the same lag but with numbers.

## Observed result

A TiledBackground object update his imageOffsetX one tick after being set.

## Expected result

I expected the TiledBackground object to update as soon as it's set. Not one tick later.

## Affected browsers

* Chrome: yes (Chromebook)
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.95
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Chrome OS
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 10895.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.95 Safari/537.36
C3 release: r121 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 3.3 gb
Storage usage (approx): 5 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 400 (Braswell) 
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The tiled background offset does update immediately. You're just reading the scroll position before the Scroll To behavior updates it. Use a scroll action instead of the scroll behavior - then you can make sure the scroll updates before you apply it to the image offset.

**Comment by LapinChat** [comment]
I understand, sorry for this "not a bug" bug report. I did applied what you suggest and it worked! Thanks you.
Now I'm curious (Forum): [In what order everything updates during a tick?  ](https://www.construct.net/en/forum/construct-3/general-discussion-7/in-what-order-everything-updat-138588)

(And thanks for this new offset feature for this plugin)
