### ISSUE TITLE
Tilemap with solid behavior bugs between layers with different scale rates

### ISSUE THREAD

**Issue by kossglobal** [Scirra/Construct-3-bugs#2148]
## Problem description

Tilemap with solid behavior turn all solid when Layer's scale rate is different from the player's scale where it contains a sprite with 8 direction behavior and another sprite with platform behavior.
**It happens in C3 with both C2 and C3 runtime. The same for Construct 2.

## Attach
https://drive.google.com/open?id=1lVujq-MaAvHH1Rrd5GiQdTCJdQLTsfWM

## Steps to reproduce

1. Watch the layer's scale rate
2. Play

## Observed result

Tilemaps in layers that doesn't share the same scale rate with the player's layer have the collision mask bugged. The tilemap turns all solid, ignoring the tile collision mask information.

## Expected result

Take in to account the collision mask of the tilemap.

## Affected browsers

* Chrome: yes
* Firefox: -
* Edge: yes
* Safari: -

## System details

-

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This seems like a weird thing to do: you're testing collisions between instances on different layers, using different transforms (i.e. the different scale rate), and then relying on per-tile collisions to work. This is not currently a case the engine supports, as it would be quite complex, and there doesn't seem to be a good reason for it - why not put the player on the same layer as the tilemap you're testing for collisions with?

**Comment by kossglobal** [comment]
I'm not doing it. I Just changed the scale rate by accident and took me hours to find out the reason. I thought it was a bug so I reported the issue. Regarding to the layer with per tile collision, It's Just for organize things better, but knowing about it I'll change it. Thanks!
