### ISSUE TITLE
Massive frame rate drop after 26 min.

### ISSUE THREAD

**Issue by saltandpixel** [Scirra/Construct-3-bugs#2149]
## Problem description

After the r121 (beta) release: 
While previewing after 26min of play: 

The game I'm working on will slow down dramatically to 6 fps then speed back up to 60 fps then back down to 6-8 fps and stay this way. I'm confused because prior to 10/1, the game preview and builds ran smoothly. 

I've also noticed that the game itself just runs slower since the update.

## Attach a .c3p

Here's a link to the current .c3p file and a zip file of the builds from before 10/8 for comparison.
https://drive.google.com/open?id=1Q3svNWgkpqvGf_cV6GS7_m9FWzf0U6v-

## Steps to reproduce

Play the .c3p for 26 minutes. 

## Observed result

Frame rate will dip and jump

## Expected result

I'm expecting the frame rate to be 30 fps and up.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 803 mb (2.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I'm afraid reports like this are infeasible to investigate. Firstly, see our bug report guidelines - we require a minimal project to rule out that it's just a mistake in your project (e.g. maybe you accidentally start running performance-degrading events at some point in the gameplay), which is not a bug in Construct, and it is very common that people make such mistakes and file them as bugs. Secondly it's almost impossible to deal with a bug report which involves "wait 26 minutes" in the steps to reproduce. We might have to test the project several dozen times during debugging, diagnosing and fixing an issue, and this would make it take so long as to be infeasible to investigate.

You need to find a way to make a minimal project that demonstrates the problem. Then you can file the issue again with that. The ideal reproduction project is automated (requiring no user input at all) and demonstrates the problem as close to immediately as possible.
