### ISSUE TITLE
C3 Run Time-New TileMovement (Else Not Working)

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-3-bugs#2156]
## Problem description

The Else is not working 
The Else it should Trigger making the Blue object Move down when it cannot  move any further to the Left because is blocked by a solid Block

## Attach a .c3p

[https://www.dropbox.com/s/at0681ofvjqhv1f/NewTileMovementTest.c3p?dl=0](url)

## Steps to reproduce

1. There is no need to do anything just observe how the blue sprite moves to the Left until it hits the Black solid sprite 

## Observed result

The Blue sprite Moves to the Left until hits the solid Black Sprite where it stops

## Expected result

After the Blue Sprite is Moving to the Left and hits the Black solid Sprite it should Trigger the Else making the Blue sprite moving Down instead

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

Windows 10

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
The canmoveto condition takes a grid co-ordinate not a world co-ordinate. So your not actually testing the correct position. Changing the expression to `Self.TileMovement.GridX + 1` fixed the behaviour

See my notes on the other bug report.

**Comment by Tarek200** [comment]
> "The canmoveto condition takes a grid co-ordinate not a world co-ordinate. So your not actually testing the correct position. Changing the expression to Self.TileMovement.GridX + 1 fixed the behaviour
See my notes on the other bug report."

Thank you very much for your Time Sir and sorry for the confusion :)
