### ISSUE TITLE
C3 Run Time-New TileMovement (Black Screen)

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-3-bugs#2157]
## Problem description

Using the Action  (Set Grid Position) the Game starts with a black screen
But if I use instead, the Action (Simulate Control) it starts normally without any Black screen

## Attach a .c3p
[https://www.dropbox.com/s/ixpx2f2yqv21ozl/NewTileMovementTest2.c3p?dl=0](url)

## Steps to reproduce

1. Use first the Action (Set  Grid Position) and Run the Project automatically it starts with a Black screen 
2. Use instead the Action (Simulate Control) and Run the Project now it should start normally without any a Black screen 

## Observed result

The project starts with a Black Screen and it freezes there

## Expected result

The project to start without any Black screen

## Affected browsers

* Chrome: Yes

* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

Windows 10

PASTE HERE

</details>

**Comment by shortercode** [comment]
Thanks for the report, there was a typo in the SetGridPosition action. Should be fixed for the next release.

Also you might want to know that most of the ACEs for the plugin work with grid co-ordinates, not world co-ordinates. I noticed you were feeding world co-ordinates in, so I don't think it's going to move to where you think!

```javascript
// GridWidth: width of a grid cell ( default 32 )
// WorldX: x position of object in world co-ordinates
// GridX: x position of object in grid co-ordinates
// GridOffsetX: x offset of object from grid in world co-ordinates

GridX = floor( ( WorldX - GridOffsetX ) / GridWidth )
WorldX = ( GridX * GridWidth ) + GridOffsetX
```

**Comment by shortercode** [comment]
I also found an error in the GridY expression, which will be fixed for the next release.

**Comment by Tarek200** [comment]
> "Also you might want to know that most of the ACEs for the plugin work with grid co-ordinates, not world co-ordinates. I noticed you were feeding world co-ordinates in"

Awesome Thanks very much for the Explanation and for the Awesome Tutorial is gonna be really helpful, indeed you are right I was using it as a normal Behavior I'm bad :)



>  "so I don't think it's going to move to where you think!"

Jejeje I see, I will definitely remember, Thank you for everything and have a good day Sir
