### ISSUE TITLE
object index expressions in platform: set angle of gravity broken

### ISSUE THREAD

**Issue by redglassesnerd** [Scirra/Construct-3-bugs#2158]
## Problem description

When setting the angle of gravity to a specific indexed object, the preview crashes and displays a black screen. It works perfectly fine in the C2 runtime. Works fine without the index expression.

## Attach a .c3p
[https://drive.google.com/open?id=1XmMbJoYmmnONHoWRyUrJta2tEpc-rAIv](url)

## Steps to reproduce

1. Set runtime to c2, preview = works
2. Set runtime to c3, preview = black screen

## Observed result

Black screen

## Expected result

Sprite being visible in layout and player movable around the sprite

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

</details>

**Comment by redglassesnerd** [comment]
Not quite sure what's happening, but it does work when there's more than one object.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
