### ISSUE TITLE
Mozilla switch to fullscreen shuttering/lag

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2159]
## Problem description
Was looking old dt example in mozilla and doing bug report for mozilla about some other issue(https://bugzilla.mozilla.org/show_bug.cgi?id=1499353) and saw some awful bug with fullscreen. I did not want to include this fullscreen bug there because it could be some other case how C3 handles mozilla fullscreen.
Testing html in browser and you click F11 mozilla will shutter like crazy.

## Steps to reproduce

1.Navigate to https://snipg.github.io/CorrectDt/
2. Click f11, see super huge lag/shuttering
3.Switch to fullscreen takes like 1sec+

## Observed result

Switch to fullscreen has super laggy behavior

## Expected result

Instant fullscreen, like in chrome. Or when you open dev tools in fullscreen, it resizes window instantly.

## Affected browsers

* Firefox: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is just because Firefox has a fullscreen animation which gradually resizes the window, and resizing the canvas is very expensive so makes it temporarily slow while it does that. If you think Firefox's behavior should be different, please report it to Mozilla.

**Comment by SnipG** [comment]
Oh that is awful. But if it has been like this before, then there is no point making the report. They just tell to work around it(with countless possible workarounds). We can even do that with events, like just display black screen for while when clicking f11 etc. 

Aint there some list of common  browser differences to take into account when developing something? it would be much easier to take them into account at start then at the end.
