### ISSUE TITLE
Contruct 3 120stable Standalone version: Game freezes when units are mirrored in any way with LoS (C3 Runtime)

### ISSUE THREAD

**Issue by HeraldofTime** [Scirra/Construct-3-bugs#2161]
## Problem description
I'd been really enjoying using the C3 runtime until this problem cropped up. 

Essentially what happens is whenever a unit is flipped in the process of moving in line of sight with another, the entire game freezes completely. No error comes up, it simply freezes irreparably. When I looked up to see if there were similar bugs on here I found that it was a problem in version #119, but its still occuring in my stable version, except even worse because it cannot be rectified by simply flipping the object manually (Self.X *-1).
 
## Attach a .c3p
I'm not sure how to upload to github directly as I'm a new user, but here is a link to the file on google drive
https://drive.google.com/file/d/1eFJRHXOcDVrEA4HpzvkugSFAoz9zk4YA/view?usp=sharing

## Steps to reproduce

1. Create a new project. Add a solid floor sprite and 2 unit sprites, one representing an enemy or follower, one which you will control. Make sure all are visible with color filled and you can mark which direction the 'follower' is facing (give it an 'eye')
2. Give both units the platformer behavior and the enemy/follower the line of sight behavior. Make the range of the line of sight short so it isnt automatically triggered (around 500 or so). Leave the follower to simulate and control the other sprite
3. Set it up with the following: When the enemy/follower has line of sight to the player, it moves left if the player unit is to its left, and ditto for right. 
4. While doing so, create a sub-event that once it is moving in a direction it faces that direction (as a trigger once while true). This could be done using the 'mirrored' option, or manipulating width (Self.Width*-1, abs(Self.Width)). The results are the same
5. Make sure the Runtime is in C3 Runtime

## Observed result

The game freezes completely and irreparably. You will have to exit the preview or game in order to have it function properly again (even restarting if you are in debug mode causes it to not work properly)

## Expected result

The following unit continues to follow you, turning to 'face' you as it does so

## Affected browsers

Standalone: Yes

* Chrome: Yes
* Firefox: Yes
* Edge: Yes
* Safari: N/A, do not own

## System details

There is no crash report that appears. It simply freezes irreparably

**Comment by shortercode** [comment]
@HeraldofTime links to google drive etc. are fine for sharing projects. You can upload files directly to GitHub by dragging the file onto the text field. GitHub doesn't allow files with the c3p extension but you can simply zip the file up and upload that instead.

**Comment by AshleyScirra** [comment]
This was fixed in r121. Please test issues reproduce in the latest release before filing an issue to avoid reporting bugs we've already fixed.
