### ISSUE TITLE
"Failed to export project" (NW.js)

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#2162]
## Problem description

When a project in C3 browser (r122 beta) version is exported to NW.js, C3 cannot export the project and gives an error message: "Failed to export project".
This happens with all projects, even a new empty project.

Firefox (just downloaded and I did not install plugins for FF) gives no problems (with a new empty project) when exporting to win64 or linux32.
When I create a new empty project in Firefox and select a platform that is not win64 or linux32, it gives the error message "Failed to export project".

Edit: 30-45 minutes later: I tried exporting in Chrome again with an empty project and exporting to all platforms suddenly (to my surprise) work as intended.
Was the reason perhaps because another device in my house was streaming a movie? Could it be a connection problem?
I tried Firefox again, but the problem in Firefox is still as I wrote above.

Edit: the next morning (10 hours later and no other devices are streaming): I tried exporting a new emtpy project in Chrome on 1 platform (Mac64) and it works as intented.
The same test in FF gives the error "Failed to export to project".

Edit: 12 hours since I opened this issue:
I used a windows free up space-cleanup (clean bin, clean windows update and other temp files), which freed up space.
I went from 2 GB (but 4 GB in the trash can, I do not know how Windows 10 handles that) free to 6 GB free space.
Now I suddenly can export to all platforms using C3 in chrome and Firefox.
Perhaps C3 can check for available space (relative to the size of the project?) before going ahead with exporting?

## Attach a .c3p

The problem can be tested with an empty project.

## Steps to reproduce

1. open construct 3 in chrome via quick link on desktop
2. Menu->Project->New
3. name of project: test, do not change options (SD landscape 16:9, 854x480, landscape)
4. click "Create"-button.
5. Menu->Project->Export->Desktop (NW.js)
6. unselect all 3 options (although the problem also is present when all 3 are ticked on)
7. click the "Next"-button
8. NW.js version: Latest (v0.33.3, chromium 69)
9. select platform Win64 (leave the rest unchecked)
10: All options checked, except for "Kiosk Mode".
11. Command line options: leave empty
12. Click the "Next"-button.

It says "preparing project data" and then says title: "Construct 3 Beta", message: "Failed to export project".

## Observed result

An error message: "Failed to export project".

## Expected result

The exported version of the project.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: not tested
* Safari: not tested (I do not have an imac)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r122 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 3.7 gb
Storage usage (approx): 294 mb (7.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here, seems to work fine.

Exporting for NW.js involves downloading large files. If your connection is intermittent and this fails then the export will also fail. So I suspect this is just to do with whether the download succeeds. Also if an export fails press F12 and look in the browser console - there should be more detailed information about what went wrong there. It's important to include that with any reports if you can, since without it there's no telling if the problem is just a failed download or something else.
