### ISSUE TITLE
Plugin SDK - Custom Importer API - allow to open Audio Import Dialog

### ISSUE THREAD

**Issue by lucidspriter** [Scirra/Construct-3-bugs#2164]
[reference thread](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/custom-importer-api-now-availa-131293/page-2#forumPost953626) 

When you import a sound file in Construct, it uses an audio import dialog to help you transcode any audio files to WebM Opus before copying the files into the project.  
```
const soundBlob = await zipFile.ReadBlob(entry); 
project.AddOrReplaceProjectFile(soundBlob, fileName, "sound");
```
Allow the audio files imported in the manner above (or a new method, if necessary) to go through that dialog so they get transcoded.  It would preferably be a manual command one could call after importing all files into the Sound or Music directories, so there is just a single dialog that gets opened, as opposed to one dialog per file.

**Comment by shortercode** [comment]
@AshleyScirra there is a generic import audio method that's used by the mainpane drag and drop behaviour, this could probably use that.

**Comment by AshleyScirra** [comment]
Added `IProject.ShowImportAudioDialog()` for the next release.
