### ISSUE TITLE
R122 Construct 3 Runtime doesnt work in ios 12 hardware

### ISSUE THREAD

**Issue by kai902000** [Scirra/Construct-3-bugs#2169]
## Problem description

I tried exporting as a cordova project, but it doesnt work. The screen just show as the default color and it is not going to the start page.  Deployed it on an iphone x.

## Attach a .c3p

 [issue.c3p](https://drive.google.com/open?id=1jzcKvNrwxoxoGDjWc5T4tWqTHOHZyzPY)

## Steps to reproduce

1.Exported as Cordova IOS using C3 Runtime
2.Tick compress and deduplicate
3.Run in xcode

## Observed result

The game doesnt go into start page.  It works on preview mode but doesnt work in phone.

## Expected result

I can see the title and two buttons.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r122 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 38 gb
Storage usage (approx): 189 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The web export works fine on iOS 12, but having trouble getting a Cordova build to work... turning this one over to @shortercode to take a look. In the mean time @kai902000 are you able to get any error log information from Xcode? If it's logging an error anywhere it would be very useful to know what it's saying.

**Comment by kai902000** [comment]
Ok, i will have a look on the weekend on the xcode error log, will post it here.

**Comment by kai902000** [comment]
I tried looking into the logs, but there are no error shown in web inspector or the xcode log.  Not sure what is really happening.  When i tried to run it on a simulator, it did show me this error.  Not sure if it is related as my device doesnt show this error.

![screenshot 2018-10-27 22 13 27](https://user-images.githubusercontent.com/1135109/47605222-702ebb00-da36-11e8-8311-fff540cbeb92.png)

**Comment by shortercode** [comment]
Ah interesting... I've been doing some digging and it looks like the ios 12 simulator doesn't support WebAssembly ( WASM ). It's not clear why though. 

[tweet wasm not working ios 12 sim](https://twitter.com/PhilippSpiess/status/1050004234375221248)

[webkit bug comment - wasm expected to fail ios?](https://bugs.webkit.org/show_bug.cgi?id=179263#c22)

[webkit bug comment- wasm disabled in simulator](https://bugs.webkit.org/show_bug.cgi?id=173892#c15)

That should not be affecting your device though. I will take a look at your test project.

**Comment by shortercode** [comment]
Okay r124 should work **on device only** we haven't resolved the simulator issue yet.
