### ISSUE TITLE
[CS2 Runtime] windowWidth and windowHeight return a different value each for CS2 and CS3

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#2171]
## Problem description

I get on construct 2 runtime a wrong result about the WindowWidth and WindowHeight expression. When you change the example-file to construct 3 runtime, it works perfectly.

Can you fix the windowWidth and the windowHeight expression for construct 2 runtime?

_The problem is, i can't switch my current project to construct 3 runtime (spriter-plugin is missing)._

## Attach a .c3p

**Example:**
https://drive.google.com/file/d/16vdTbl0IqfIa8RuTOkRzYqcY5uM-BkeA/view?usp=sharing

## Steps to reproduce

1. Open the example file
2. Start the example with construct 2 runtime, and after that with construct 3 runtime
3. You see, the windowWidth and windowHeight value is wrong on cs2 runtime

## Observed result

Wrong value on cs2 runtime.

## Expected result

The same result as construct 3 runtime.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r122 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 20 gb
Storage usage (approx): 25 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The events are wrong: if you want to fill the viewport, use `ViewportRight(0) - ViewportLeft(0)` and `ViewportBottom(0) - ViewportTop(0)` instead of WindowWidth and WindowHeight as the size. This works in both runtimes.

The C2 runtime's handling of viewports is a big mess. As far as I can tell the C2 runtime is wrong and the C3 runtime is right for the WindowWidth/Height expressions, which are confusingly named, because they actually return the viewport size rather than the window size. I don't want to make the C3 runtime incorrect, and changing the C2 runtime will cause backwards compatibility issues, so I think it might be best to leave it as is.
