### ISSUE TITLE
Github Issue tracker is bugged, with video

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2173]
## Problem description

Construct github issue tracker is bugged, see video.

Needs vlc player.
[2018-10-22 16-46-54.zip](https://github.com/Scirra/Construct-3-bugs/files/2501582/2018-10-22.16-46-54.zip)

**Comment by AshleyScirra** [comment]
GitHub are having issues today, see: https://status.github.com/messages
