### ISSUE TITLE
Project Opacity Change - Debug Preview - C3Runtime

### ISSUE THREAD

**Issue by SamueleDev** [Scirra/Construct-3-bugs#2176]
## Problem description
I applied a sine behavior to a simple sprite just to change opacity, but when I try to run the project with remove preview, the whole project changes opacity.

I tried to remove the behavior and change the opacity of the object (btnPlay), like in the photos, If I applied Opacity = 40% the whole project changes opacity.

If the btnPlay sprite has opacity 100& the whole project is ok.

## Attach a .c3p
[western.zip](https://github.com/Scirra/Construct-3-bugs/files/2503533/western.zip)

## Steps to reproduce

I am using my Samsung Galaxy S9+ with the last version of Chrome

1.Open Project
2.Use Remote Preview
3.Scan the QR Code and test it on an Android Device

## Observed result

btnPlay opacity=40% 

![problem](https://user-images.githubusercontent.com/26904027/47321701-e9ed3000-d655-11e8-8b99-bff0d6a17679.png)

btnPlay opacity=100% 
![problem2](https://user-images.githubusercontent.com/26904027/47321704-eb1e5d00-d655-11e8-86d2-5c4e8ccb2be5.png)

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

</details>

**Comment by AshleyScirra** [comment]
Please include your system details - it would save me asking: which version of C3 are you using? This should have been fixed in r122.

**Comment by SamueleDev** [comment]
Yes, im using the r120 and with the r122 version everything is ok. Sorry for the post! Thank you Ashley!!!
