### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2178]
## Problem description
test

## Steps to reproduce

1.
2.
3.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
GitHub should be stable as of midnight, that's what their status page is claiming anyway!
