### ISSUE TITLE
The hotkey for debug project doesn't work in web browsers

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2180]
## Problem description

when trying to use the hotkey to debug project (ctrl+f4) it promps "are you sure you want to close this page" if you made an unsaved change or just closes the whole editor if you have no changes if you are using the editor in a web browser tab. It works fine when using construct 3 as a web app and debugs the project

**Comment by AshleyScirra** [comment]
Pretty sure this used to work, I guess browsers have made it a non-overridable shortcut now. We'll probably just change it to something else like shift+F4.

**Comment by AshleyScirra** [comment]
Changed to Shift+F4 for next release. Ctrl+F4 should still work in the desktop build. For consistency also made Shift+F5 do debug layout as well.
