### ISSUE TITLE
Opera right click bugs

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2183]
## Problem description

Right click, clicks through app/animation editor into homepage apps. Which trigger popups > like to leave Construct? or some other page like speed dial.

## Steps to reproduce

1.Use opera, navigate into latest c3 release
2.Open new. Spam right click. See some speed dial pages open up. Which you can also click on homepage. Also if you hit some app homepage, it tries to navigate there and close c3.
3.Open animation editor, try out right click. See it needs extra click to release painting.

## Observed result
Right clicks bug in opera, which clicks homepage apps or tabs which you can open up with right click on homepage, Also does not release right click on animation editor, so you need to reclick for it.

## Expected result
No bug. especially ability to click through Construct app into homepage, and trigger navigate away from Construct editor.

## Affected browsers

*Opera

## System details

<details><summary>View details</summary>

Platform information
Browser: Opera
Browser version: 56.0.3051.52
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36 OPR/56.0.3051.52
C3 release: r122 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 2.3 mb (0%)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Persistent storage is not available. Local storage could be deleted by the browser.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
This just seems to be the default behaviour of opera. Right mouse button down > move > release will trigger "mouse gestures". Moving left is back, right is forward and down is "speed dial".

I can't find any information on how we would block these gestures, so the only workarounds for this are to either not use opera or disable the mouse gestures setting.
