### ISSUE TITLE
Renaming Pathfinding behavior crashes the editor

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#2184]
## Problem description

An attempt to rename Pathfinding behavior crashes the editor if there is "Find path" action in the event sheet.

## Attach a .c3p

https://www.dropbox.com/s/er7ho7e1flt7345/PF_bug.c3p?dl=0

## Steps to reproduce

1. Try to rename Pathfinding behavior on the sprite.

## Observed result

C3 crashes

## Expected result

Should be able to rename.

## Affected browsers

Both Desktop and Browser versions.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot set property 'textContent' of null @ TypeError: Cannot set property 'textContent' of null at e.ǃdL (https://editor.construct.net/r120/components/editors/eventSheetView/eventSheetView.js:1:76954) at e.ǃvLU (https://editor.construct.net/r120/main.js:81:273027) at window.ǃvmm.ǃvM_ (https://editor.construct.net/r120/main.js:81:400013) at e.accept (https://editor.construct.net/r120/main.js:81:272714) at e.accept (https://editor.construct.net/r120/main.js:81:298220) at t.ǃvMF (https://editor.construct.net/r120/main.js:81:292618) at t.accept (https://editor.construct.net/r120/main.js:81:272730) at window.ǃCt.ǃvMF (https://editor.construct.net/r120/main.js:81:279403) at window.ǃCt.accept (https://editor.construct.net/r120/main.js:81:272730) at t.ǃJj (https://editor.construct.net/r120/main.js:81:75830)
Stack: TypeError: Cannot set property 'textContent' of null at e.ǃdL (https://editor.construct.net/r120/components/editors/eventSheetView/eventSheetView.js:1:76954) at e.ǃvLU (https://editor.construct.net/r120/main.js:81:273027) at window.ǃvmm.ǃvM_ (https://editor.construct.net/r120/main.js:81:400013) at e.accept (https://editor.construct.net/r120/main.js:81:272714) at e.accept (https://editor.construct.net/r120/main.js:81:298220) at t.ǃvMF (https://editor.construct.net/r120/main.js:81:292618) at t.accept (https://editor.construct.net/r120/main.js:81:272730) at window.ǃCt.ǃvMF (https://editor.construct.net/r120/main.js:81:279403) at window.ǃCt.accept (https://editor.construct.net/r120/main.js:81:272730) at t.ǃJj (https://editor.construct.net/r120/main.js:81:75830)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Thu Oct 25 2018 21:56:42 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 73.3 s

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
