### ISSUE TITLE
Two different objects with Pathfinding interfere with each other and not working correctly

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#2185]
## Problem description

When there are two sprites with Pathfinding behavior, one has Obstacles=Custom, another Obstacles=Solid, or both with Obstacles=Custom, they are not working correctly.
Changing this property on one sprite somehow affects the other, as if they have the same obstacle map!

## Attach a .c3p

Two examples:

https://www.dropbox.com/s/psk2unug89frci6/PF_bug2.c3p?dl=0
https://www.dropbox.com/s/gwi3f4i8cerbgpu/PF_bug8.c3p

## Steps to reproduce

Run the file, try clicking the screen.

## Observed result

Example 1: Blue box moves through walls, but it shouldn't.
Example 2: Blue arrow has Red block set as an obstacle, but it moves through it.

Changing Obstacle setting on the second sprite, or deleting it from the layout somehow fixes the problem.

## Expected result

Correct movement.

## Affected browsers

* Chrome: yes
* Firefox: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 12 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Closing as discussed at https://www.construct.net/en/forum/construct-3/how-do-i-8/two-objects-with-pathfinding-n-138879
