### ISSUE TITLE
Crash when tilemap resized with negative values

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#219]
## Problem description

Program crash when a tilemap is resized with negative values.

## Steps to reproduce

1. Use or create and place a tilemap on a layout
2. Resize it by dragging bottom right to top left

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r27/main.js, line 61, col 226694
Message: Uncaught RangeError: Invalid array length
Stack: RangeError: Invalid array length at ǃP.ǃtw.ǃPbA (https://editor.construct.net/r27/main.js:61:226694) at ǃP.ǃtw.ǃdK (https://editor.construct.net/r27/main.js:61:222186) at c.ǃi.ǃtb (https://editor.construct.net/r27/plugins/tilemap/plugin.js:1:8518) at c.ǃi.ǃtW (https://editor.construct.net/r27/plugins/tilemap/plugin.js:1:8538) at Array.ǃZc.ǃP.ǃe.ǃP.ǃZL.ǃZy.m (https://editor.construct.net/r27/plugins/tilemap/plugin.js:1:5257) at ǃP.Event.ǃfbj.ǃfbt (https://editor.construct.net/r27/main.js:2:285256) at ne.dispatchEvent (https://editor.construct.net/r27/main.js:2:283648) at ne.ǃPVw (https://editor.construct.net/r27/main.js:61:205545) at ne.ǃXJ (https://editor.construct.net/r27/main.js:61:211658) at ne.ǃPq (https://editor.construct.net/r27/main.js:61:214276)

</details>

**Comment by DiegoScirra** [comment]
Fixed in r28.

Thanks for the help.
