### ISSUE TITLE
Moving multiple instances in the Z-Order-Bar sometimes crashes the editor on mouse release

### ISSUE THREAD

**Issue by birbdoy** [Scirra/Construct-3-bugs#2190]
## Problem description

Selecting multiple instances (two or more) of arbitrary objects in the Z-Order Bar, then left clicking one of them (to move them) and releasing the left click while hovering above another selected instance crashes the editor. See 'Steps to reproduce' for a more precise explanation.

Tested in R120, R122

## Attach a .c3p
 
[zorder_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2518894/zorder_bug.zip)
or simply create a new project, a sprite object and put two instances on the layout.

## Steps to reproduce

0.Do all of the following actions inside the Z-Order Bar
1.Select two or more instances
2.Pick them up by left clicking on one of the selcted instances (A)
3.Release the left click while hovering over a selected instance that isn't A

## Observed result

Construct crashes.

## Expected result

Construct shouldn't crash. I think as long as they are dropped somewhere where no instert line is showing they should simply stay at their current z-position.

## Affected browsers

* Chrome: yes
* Firefox: yes

## System details

<details><summary>View details</summary>

Error report information

Type: unhandled exception
File: https://editor.construct.net/r120/main.js, line 81, col 258794
Message: Error: pivot instance is not part of the layer
Stack: ǃvwa@https://editor.construct.net/r120/main.js:81:258794 ǃoS@https://editor.construct.net/r120/main.js:81:258603 window.ǃG$.prototype.ǃoK@https://editor.construct.net/r120/components/bars/zOrderBar/zOrderBar.js:1:11188 window.ǃG$.prototype.ǃFu@https://editor.construct.net/r120/components/bars/zOrderBar/zOrderBar.js:1:10429 this.ǃWy@https://editor.construct.net/r120/components/bars/zOrderBar/zOrderBar.js:1:1010 ǃVju@https://editor.construct.net/r120/main.js:2:202014 dispatchEvent@https://editor.construct.net/r120/main.js:2:200155 ǃVMf@https://editor.construct.net/r120/main.js:2:435601 ǃVb@https://editor.construct.net/r120/main.js:2:442199 i/this.ǃVY@https://editor.construct.net/r120/main.js:2:438018 e/<@https://editor.construct.net/r120/main.js:2:196882
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Fri Oct 26 2018 12:40:13 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 29.1 s
Platform information

Browser: Firefox
Browser version: 63.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
C3 release: r120 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release
