### ISSUE TITLE
Crash when dragged remote preview out of window, no repo

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2192]
## Problem description

I opened the remote preview, it opened as a window within the app and also as a standalone window which i found pretty odd. The stand alone window had "Loading" text only. I closed the stand alone window and dragged the app window ( the panel ) outside to create the stand alone window again and C3 crashed. I couldnt get it to reproduce but maybe you can figure it out by checking the crash report.

## Affected browsers

* Desktop: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r120/main.js, line 2, col 292095
Message: Uncaught Error: already awaiting popup window
Stack: Error: already awaiting popup window at ǃv.ǃV.ǃKY.ǃNRy.ǃzr (https://editor.construct.net/r120/main.js:2:292101) at Function.ǃVBn (https://editor.construct.net/r120/main.js:2:278593) at HTMLDocument.t.document.addEventListener (https://editor.construct.net/r120/main.js:2:274074) at HTMLDocument. (https://editor.construct.net/r120/main.js:2:196891)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Sat Oct 27 2018 00:53:34 GMT+0300 (Eastern European Summer Time)
Uptime: 14759.3 s

Platform information
Browser: NW.js
Browser version: 0.31.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.3541666269302368
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@878cd31214ac27a3996927cd5c9c138b10c9fc8d) NWjs/0.31.2 (like Chrome/67.0.3396.87)
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Sorry, I don't think we can do anything about this without the steps to reproduce. Please file again if you can find how to reproduce it.
