### ISSUE TITLE
Remote preview not working, hangs on Joined Session (iOS)

### ISSUE THREAD

**Issue by badmiracle** [Scirra/Construct-3-bugs#2195]
## Problem description

Remote preview does not work

Tested on iOS 12.01 (iPhone SE) and iOS 11+ (iPhone 7+)

(I saw a similar issue raised #2186, but this may be different as I'm not seeing the same error message)

## Attach a .c3p

Affects all C3 projects

## Steps to reproduce

1. Preview project with Remote Preview
2. Open remote preview URL on mobile device

## Observed result

Project preview does not load, it hangs on the "Joined Session" message, then after a minute it disconnects.

## Affected browsers

* Safari: yes

**Comment by AshleyScirra** [comment]
I think this was an issue with our TURN server. I just restarted it and it seems like connections are working again. Can you confirm it's working for you now?

**Comment by badmiracle** [comment]
Working now, thanks!

**Comment by AshleyScirra** [comment]
Thanks for confirming.
