### ISSUE TITLE
[r27] crash in animation editor

### ISSUE THREAD

**Issue by M1thrill** [Scirra/Construct-3-bugs#220]
## Problem description

I opened a animation editor. Then I clicked on animation name on right side of the editor. "Ooops, something went wrong" -dialog window pops up. No idea how to reproduce this.

https://www.dropbox.com/s/jz99vuut8h5ujgc/animTest.zip?dl=0
or
[animTest.zip](https://github.com/Scirra/Construct-3-bugs/files/1004895/animTest.zip)

## Steps to reproduce

1. double click on sprite
2. click any animation?

## Observed result

"Ooops, something went wrong" -dialog window pops up.

## Expected result

Be able to edit animation.

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: untested

## System details

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃP.ǃyM (https://editor.construct.net/r27/main.js:2:201735) at ee.ǃs$j.ǃsIk (https://editor.construct.net/r27/main.js:71:250595) at ee.ǃs$j.ǃ$C (https://editor.construct.net/r27/main.js:71:246598) at ǃP.ǃPd.ǃlz.ǃsKD.ǃsLC (https://editor.construct.net/r27/main.js:71:66448) at Promise.resolve.then.then.then.then.then.then (https://editor.construct.net/r27/main.js:71:139068) at 
Stack: TypeError: unexpected type at Function.ǃP.ǃyM (https://editor.construct.net/r27/main.js:2:201735) at ee.ǃs$j.ǃsIk (https://editor.construct.net/r27/main.js:71:250595) at ee.ǃs$j.ǃ$C (https://editor.construct.net/r27/main.js:71:246598) at ǃP.ǃPd.ǃlz.ǃsKD.ǃsLC (https://editor.construct.net/r27/main.js:71:66448) at Promise.resolve.then.then.then.then.then.then (https://editor.construct.net/r27/main.js:71:139068) at 
Construct 3 version: r27
URL: https://editor.construct.net/
Date: Tue May 16 2017 11:40:37 GMT+0300 (EEST)
Uptime: 22714.4 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.9_5
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 650M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 63.375
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r28.

The crash report was very useful, thank you :)
