### ISSUE TITLE
DrawingCanvas fill rectangle alpha value bug

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2200]
## Problem description

Using new drawingCanvas fill retangle alpha value, it seems not working correctly. 

## Attach a .c3p
[DrawingFillRectangleBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2526070/DrawingFillRectangleBug.zip)

## Steps to reproduce

1. Open example, preview. see trail
2. Disable drawingcanvas event and enable one with 0.19 alpha value. Preview
3. See no trail.

## Observed result
Drawingcanvas should be filling viewport with color(0.19 alpha), but it does not

## Expected result

Should able to use alpha value below 0.2/0.199.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 663 mb (4.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SnipG** [comment]
I does not work for me. 0.19 and 0.1. Gonna check if something else affects it.

**Comment by SnipG** [comment]
Still can't find anyway to check why it does not work lower then 0.199. With same example there is other strange artifact(maybe needs new report but i add it atm here)
![artifact](https://user-images.githubusercontent.com/28864889/47665860-ccb2e700-dbaa-11e8-9101-93f0db0398a1.jpg)
If this does not reproduce on you do, then maybe i need to check some webgl 2 settings?Something not supported?

**Comment by AshleyScirra** [comment]
I need a project file and steps to reproduce to be able to help.

There is nothing special about an alpha of 0.2, so this doesn't make any sense at all right now.

**Comment by SnipG** [comment]
I made same test with example in main post. 
I narrowed the alpha value even more.
Image left has 0.196 alpha value, and right on has 0.195.
![alphavalue](https://user-images.githubusercontent.com/28864889/47668358-e5be9680-dbb0-11e8-9cef-32b68f074cdf.jpg)

I tried remote preview to laptop, it had same result.

**Comment by AshleyScirra** [comment]
I just realised, you're using rgba() wrong - all four parameters are in 0-100 range, but you're passing 255 for colors and 0.19 for alpha, which is 2.55x overdriven white with 0.19% alpha (which as an 8 bit value will probably round down to 0, subject to rounding errors in the GPU).

It should work correctly if you pass the right parameters to rgba().

**Comment by SnipG** [comment]
When i use 100,100,100,5 - which should work - but it leaves behaind light grey area.  
I just tried to make super long trail that fades long time. But this rgba makes no sense atm.
Is it even possible to add(without hitting GPU rounding error)  - fill canvas with white color each tick and having color alpha like 0.001% ?

**Comment by AshleyScirra** [comment]
With 8-bit color, the minimum alpha is 1/255, which is about 0.4%. In this range you'll likely get blending artefacts since there is not enough precision to calculate the correct result.
