### ISSUE TITLE
Crash while switching from C2 to C3 runtime

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#2202]
## Problem description

Crash while switching from C2 to C3 runtime.

## Attach a .c3p

[New project (10).zip](https://github.com/Scirra/Construct-3-bugs/files/2526558/New.project.10.zip)

## Steps to reproduce

Change the runtime to C3 in  the project properties.

## Observed result

Crash.

## Expected result

Not crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by NetOneGames** [comment]
and when switching from C3 to C2

**Comment by RichardAstrom** [comment]
I have the same problem. Seems to happen if you have added any standard plugin like "Keyboard", "Touch" or "Audio" to the project and then try to change the runtime.

**Comment by shortercode** [comment]
@RichardAstrom thanks for the extra note. Judging by the error and your comment it is to do with plugins that do not support behaviours. Have assigned @AshleyScirra to investigate further.

**Comment by AshleyScirra** [comment]
Fixed for next release. Will leave this open till the next release since I think there may be a fair few people running in to this...
