### ISSUE TITLE
Picture in Picture, layer position and scale issues with 123 build

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2203]
## Problem description

getting picture in picture with layer positions and scales all over the place 
on latest 123 build (not present on 122 or previous)

am away these next 2 weeks to hard to get time to investigate or pare down project
if its not obvious I can provide project.

## Observed result

[KLX_OCTOBER (C3 runtime) - Google Chrome 29_10_2018 22_11_45.zip](https://github.com/Scirra/Construct-3-bugs/files/2527294/KLX_OCTOBER.C3.runtime.-.Google.Chrome.29_10_2018.22_11_45.zip)

**Comment by AshleyScirra** [comment]
Sorry, nothing we can do with just a video.

**Comment by NetOneGames** [comment]
Yea I get it, I did try to replicate in small project unsuscessfully
I ran my project on work computer and no issue 
so appears to be specific to surface pro 4 only so unless you have sp may not be able to replicate
happens on sp4 even when outputting to different monitor.
you made some dpi related changes in 123?
maybe to do with that as sp4 has high dpi
