### ISSUE TITLE
Anchor bug returns wrong positions

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2205]
## Problem description

giving an object the anchor behavior and then moving it with pin returns anchor positions ( x and y values) instead of pin positions
## Attach a .c3p

https://puu.sh/BTcuU/b1da41b86c.c3p

## Steps to reproduce

1.preview the project
2.the sine behavior will move sprite 1
3.sprite 2 is pinned to sprite 1 relative to where it was placed with the anchor behavior and will move relative that
4. sprite3's position is set to sprite2's position based on the anchor behavior and not the pin behavior

## Observed result

sprite3's position is set to sprite2's position based on the anchor behavior and not the pin behavior

## Expected result

sprite3's position to be set to sprite2's visible position

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 422 mb (2.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This project uses contradictory behaviors: anchor tries to keep the object in the same place, but pin tries to keep moving it. I don't know why you would do this or what you would expect to happen, but I don't think it's worth spending our limited resources fixing cases that don't make sense.

**Comment by eleanorawesome** [comment]
I didn't think it was worth spending your limited resources I thought It was a bug and bugs should be reported. 

I came across it when i  was moving a bundle of pinned objects but one of the object's position changed based on another object's animation so I couldn't use pin for it, and i had given it the anchor behavior months ago because one of the families it was in had the anchor behavior and with lots and lots of efforts I wasn't able to figure out why it wouldn't move to the X and Y i was telling it to and I experienced frustration. and I though that if I reported it then maybe others wouldn't experience the same frustration

I'm really sorry I wasted your time please forgive me.
