### ISSUE TITLE
Problems using "use render cells" C3runtime (r122, r123)

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#2207]
## Problem description

After setting "use render cells" to more than 1 layer, the sprite texture is multiplied.

If you remove "use render cells" or remove the second layer using "use render cells" the problem disappears
## Attach a .c3p

[Архив ZIP - WinRAR.zip](https://github.com/Scirra/Construct-3-bugs/files/2529389/ZIP.-.WinRAR.zip)

## Steps to reproduce

[Video.zip](https://github.com/Scirra/Construct-3-bugs/files/2529393/Video.zip)

**Comment by AshleyScirra** [comment]
Should be fixed in the next release.

**Comment by ibiz3091** [comment]
Thank you for efficiency.
