### ISSUE TITLE
Stuck in Free Edition

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#221]
## Problem description

My account is stuck in free edition with the 25 event limit even after I confirmed my email address.  Reading the game jam blogs I was under the impression I should have a full unlocked account for the next two weeks.  I wasn't sure where to put this issue since it seems like a bug with my account but my account name is Thirstyy using Chrome from my PC and Android phone clearing cached data on each of them with no change in results.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
You need to log in to your account in Construct 3. The game jam only enables full features for logged in users. You should also see a notification telling you that in the start page.

**Comment by 8bitThirsty** [comment]
I was logged in on both devices which should have been clear from my original issue if you had read it completely.

**Comment by 8bitThirsty** [comment]
I logged out and back in which fixed the issue.
