### ISSUE TITLE
C3 Run Time (New TileMovement) causes Object displacement (X,Y) at Start of Layout

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-3-bugs#2210]
## Problem description

Any Object that uses the New TileMovement causes a minor displacement to the object at the Start of the Layout making the object start at the Wrong coordinates.
In this case is the Green object.

## Attach a .c3p

[Capx:](https://www.dropbox.com/s/xtwp8qddauontew/New_TileMovement%20Bug2.c3p?dl=0)

## Steps to reproduce

1. Run the Project and observe how the Green Object starts at the wrong (X,Y)

## Observed result

Green Object Starts on a diferent (X,Y) than where is placed on the Layout

## Expected result

The Green Object to start at the same (X,Y) where is Placed on the Layout

## Affected browsers

* Chrome: Yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.67
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
C3 release: r123.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 31 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by shortercode** [comment]
The tilemovement behaviour requires the instance to always align with the grid, or be moving towards a grid position. Hence, when it starts it is moved to the nearest grid aligned position.

It is aligned by it's origin, which by default is the center of the object. So your seeing it moved slightly to the side. You can adjust this by either making the objects origin ( 0, 0 ) or change the grid offset to the origin position which is ( 32, 32 ) in this case.

**Comment by Tarek200** [comment]
Hoo I see I'm bad, That makes sense now
I didn't think of that, I keep using it as if it was the "MoveTo" Behaviour, probably I should have waited until some Tutorial is available before using it jeje
I apologise for the inconvenience and for wasting your Time
Thanks for the Tips

**Comment by shortercode** [comment]
No worries, have fun with it! We'll try and get some tutorials up for it soon. I'm hoping to see some cool turn based games made with it.
