### ISSUE TITLE
Empty Condition Bug - r123-2

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#2211]
## Problem description
If plugin doesn't have any condition, it is shows you when you edit other condition.

## Steps to reproduce
Look at gif

![buggy](https://user-images.githubusercontent.com/13033837/47728016-9179ec00-dc6e-11e8-806e-17108cc1d510.gif)

## Observed result
![126 06-07-05-7807](https://user-images.githubusercontent.com/13033837/47728272-0f3df780-dc6f-11e8-9997-5f124f4a0ca6.png)

## Expected result
![56 06-07-02-8204](https://user-images.githubusercontent.com/13033837/47728189-e61d6700-dc6e-11e8-8dc0-3350b2b751c0.png)

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Fixed for next release.
