### ISSUE TITLE
"n.push is not a function" when saving

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#2215]
## Problem description

Got this error, vanished after a restart though. I forgot to check the console so this is all I have.

## Attach a .c3p

Don´t think it is tied to a particular project.

## Steps to reproduce

It happened whenever I saved a (google) cloud project. There were 2 projects open at that time. (one local)

## Observed result

![brow](https://user-images.githubusercontent.com/31101309/47755442-8dfe5900-dc9e-11e8-9f9e-c10243786179.PNG)

## Expected result

¯\_(ツ)_/¯

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 1.5 gb (10.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Well... that looks fun to track down. If you can come up with a solid reproduction that would be very handy. I might just try and fix that error dialog so that it only displays error messages, not failures. Been on the to-do list for awhile!

**Comment by shortercode** [comment]
Think I may have finally tracked this down, mostly by accident.

What appears to have happened was that a request to get a list of entries within a folder failed, which corrupted the cache entry for the folder. The cloud cache only exists until the end of the session, which is why this fixed itself after a reload.

After saving a file it updates the cache entry for the file, and it's parent folder. The folder in this case being the one that was corrupted, which caused the error message.

Just finishing up the fix for this, should be in the next release. Although it's pretty difficult to replicate it.
