### ISSUE TITLE
Center aligned sprite font in a pixel game. (C3 runtime)

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2217]
## Problem description

I'm making a game with pixel assets and this is my game's properties

![image](https://user-images.githubusercontent.com/2965842/47790675-d95d4980-dd28-11e8-9b2d-75bcad522f61.png)

I'm using Sprite Font plugin with this properties:

![image](https://user-images.githubusercontent.com/2965842/47790740-001b8000-dd29-11e8-83d1-51227fc920f6.png)

![image](https://user-images.githubusercontent.com/2965842/47790762-0e699c00-dd29-11e8-9b7f-c688d5b5baef.png)

Everything looks good in the editor but when I run the preview some characters look off.

![image](https://user-images.githubusercontent.com/2965842/47790824-35c06900-dd29-11e8-96ac-55c521e41ea5.png)

I was using C2 runtime before and this problem was solved when I gave odd numbers to sprite font's position and size. 

## Attach a .c3p

[spritefont-pixel.zip](https://github.com/Scirra/Construct-3-bugs/files/2534681/spritefont-pixel.zip)

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
