### ISSUE TITLE
Windows VS physics crash

### ISSUE THREAD

**Issue by MrWonka** [Scirra/Construct-3-bugs#2219]
## Problem description

Eporting any project that has physics to VS then spits out this error: SCRIPT5022: Unhandled exception at line 2, column 77931 in ms-appx://eda9c4fb-5cad-444a-af61-7f50a27d3ea0/scripts/c3runtime.js
0x800a139e - JavaScript runtime error: TextDecoder polyfill only supports utf-8

## Attach a .c3p

[demo.zip](https://github.com/Scirra/Construct-3-bugs/files/2536490/demo.zip)

## Steps to reproduce

1. Create a project with a physics object
2. Export to windows
3. Open in VS

**Comment by shortercode** [comment]
Thanks for the report, this should be resolved in the next release.
