### ISSUE TITLE
Importing .tmx to tilemap fails if renderorder is not explicit

### ISSUE THREAD

**Issue by VictoryRice** [Scirra/Construct-3-bugs#2221]
## Problem description

According to the .tmx file format definition presented on [the Tiled map editor website](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/), the **renderorder** attribute of the \<map\> element should default to "right-down":

> renderorder: The order in which tiles on tile layers are rendered. Valid values are right-down (__the default__), right-up, left-down and left-up. In all cases, the map is drawn row-by-row. (only supported for orthogonal maps at the moment)

I noticed that when exporting a .tmx file from [Pro Motion NG](https://www.cosmigo.com/), it does not define a renderorder attribute for \<map\>. When I try to import the .tmx file to Construct 3, I get "Incorrect renderorder attribute / Construct 3 only supports right-down renderer order."

Editing the .tmx file to add **renderorder="right-down"** solves the problem. I'll request the Pro Motion NG developer to change the export to include it, but seeing as the file format calls "right-down" the default behavior, I think you could consider making Construct 3 assume "right-down" if no renderorder is specified. I'm thinking of other developers who may be using this definition in implementing .tmx export.

## Attach a .c3p
There's no specific .c3p required to test, but am attaching a sample tileset and .tmx file output from Pro Motion NG which cannot be imported due to this issue.
[World-1.zip](https://github.com/Scirra/Construct-3-bugs/files/2536646/World-1.zip)

## Steps to reproduce
1. Unzip the attached file. 
2. Open a new, blank project in Construct 3.
2. Add a Tilemap object to the Layout. Close the image editor that pops up.
3. With the Tilemap selected in the Project bar, focus on the Tilemap bar and choose "Load tilemap from TMX file".
4. Under "Choose a tilemap file" click "Choose a file" and select the .tmx file from the attachment, then click Open.
5. Observe the error message stated above. (Alternatively, drop the .tmx file on to the Tilemap bar)
6. Edit the .tmx file and insert renderorder="right-down" as an attribute of the \<map\> element and observe that repeating steps 1-4 above now results in success.

## Observed result

Error message stating "Incorrect renderorder attribute / Construct 3 only supports right-down renderer order."

## Expected result

Construct 3 infers "right-down" when no renderorder is specified.

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: untested

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 90 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
I won't lie, that detail went right past me when I implemented the feature.

It also looks like Construct 2 is not adding that attribute either, so you can can't use tilemaps exported from Construct 2 in Construct 3. That is not right.

This should be easy to fix, expect it on the next beta release.
