### ISSUE TITLE
Tile map .tmx file import fails if tilemap .png is not embedded

### ISSUE THREAD

**Issue by VictoryRice** [Scirra/Construct-3-bugs#2226]
## Problem description

When importing a .tmx format tile map, the import fails unless the tileset bitmap image file is directly referenced in the .tmx. However, the Tiled map editor (likely the most common source of .tmx files users will want to import to C3) by default does not save it this way. Users of Tiled will have to check the box "Embed in map" when attaching a tileset to a map, or later click the Embed Tileset icon and then re-save the map file. The documentation for Tiled actually recommends not to embed, and the C3 documentation makes no mention of making sure the .tsx file is saved with the tileset embedded.

Furthermore, even when the .tmx is saved with the tileset image "embedded," C3 will ask for the location of the image file anyway -- it doesn't actually seem to care about whatever image is file referenced in the .tmx, it only (seems to) care that there is an \<image\> tag with a **source** attribute inside the \<tileset\> ... \</tileset\> tags.

From the [Tiled documentation on tilesets](https://doc.mapeditor.org/en/stable/manual/editing-tilesets/):

> **Note**
> A tileset can be either embedded in a map file or saved externally. Since Tiled 1.0, the default and recommended approach is to save your tilesets to their own file. This simplifies your workflow since it makes sure any meta-information is shared between all maps using the same tileset.

Note that when Tiled saves a map without the "embed in map" option, the .tmx file will refer to a .tsx file within the **source** attribute of its \<tileset\> tag. The tileset will be saved to a separate .tsx file which has an \<image\> tag that refers to the actual bitmap of the tiles. When Tiled is told to embed the tileset in the map, there is no .tsx file and the .tmx refers directly to the bitmap.

## Attach a .c3p

Am attaching two identical simple 5x5 tile maps, one saved as non-embedded, and the other embedded. Observe that the embedded can be imported into C3 where the non-embedded fails with "Missing image on tileset".
[TMX non-embedded.zip](https://github.com/Scirra/Construct-3-bugs/files/2540126/TMX.non-embedded.zip)
[TMX embedded.zip](https://github.com/Scirra/Construct-3-bugs/files/2540127/TMX.embedded.zip)

## Steps to reproduce

1. Unzip the two attachments. 
2. Create a new blank project in C3 and add a Tile Map object to the layout.
3. In the Tile Map bar for the object, trying importing the .tmx file from each attachment.

## Observed result

"Missing image on tileset" error on the non-embedded .tmx

## Expected result

Since I have to manually specify the bitmap file anyway on import, I expected C3 to proceed the same with either version of the .tmx, with the possible additional step of asking for my .tsx file if necessary. Or at least have the documentation explain the limitation since by default I probably did not choose to "embed" the tileset in the map.

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: untested

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 91 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 16000 Hz
Output channels: 1
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Must have forgotten to remove that validation. C3 can't really use that image file path, at least not in browser mode.

In the browser it is not possible to load an image from the local file system without user interaction, you either need an input element to select the file or you need to drag and drop, so that is why C3 can't really use the the image tag of the TMX. Unless it is the desktop version, in which case it can access the local file system, but that is a different issue. 

Tiled must have changed since this was implemented because I don't remember having the option to choose whether to embed the tileset or not.

In any case, it looks like this needs some touching up.

**Comment by DiegoScirra** [comment]
Fixed in the next release.

Now you will be able to add a .tsx file in case you are using a .tmx with out an embedded tileset. Of course,  if you are using an embedded tileset that will still work.
