### ISSUE TITLE
Gamepad controls doesn't work properly

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#2229]
## Problem description

Simply, the object controlled by the gamepad's axis doesn't move properly (or im just an idiot). Moves diagonally, instead of forward.

## Attach a .c3p

[New project (11).zip](https://github.com/Scirra/Construct-3-bugs/files/2541612/New.project.11.zip)

## Steps to reproduce

Control the square using right analog stick. It moves diagonally. 

1. 
2.
3.

## Observed result

moves diagonally

## Expected result

move forward

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details

**Comment by AshleyScirra** [comment]
Gamepad axes are very sensitive. With your events, you will only get perfectly horizontal or vertical movement if the X or Y component of the axis is exactly 0. This is practically impossible; even if close to zero, it'll always be something slightly off like -0.001 or 0.0023, and therefore also trigger movement on the opposite axis as well. Try displaying the axis values in a text object to see for yourself. Note Construct uses a radial deadzone so as soon as you reach the deadzone threshold in any direction, you get the full resolution of both components - e.g. once you go 25 on the X component, you get full raw resolution on the Y component, which can be very small (and much less than the deadzone magnitude).

Instead, apply a deadzone to the comparisons, e.g. greater than 25, less than -25, etc.
