### ISSUE TITLE
Open Z Order Bar not available on open beta

### ISSUE THREAD

**Issue by humbertoraposa** [Scirra/Construct-3-bugs#223]
## Problem description

I can't access the Z Order Bar functionality

## Attach a .c3p

You can test it on any project

## Steps to reproduce

1. Right click on a element
2. Mouse over "Z Order" option
3. Click on "Open Z Order Bar..." option 

![Screenshot1]
(https://drive.google.com/open?id=0B33QhNUlkAVTZEJlYkVTVHI1MWs)

## Observed result

![Screenshot2]
(https://drive.google.com/open?id=0B33QhNUlkAVTSjA4NnVxWG5JSEk)

## Expected result

Opening Z Order Bar

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

Platform information
Browser: Chrome
Browser version: 58.0.3029.81
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

Local storage
Storage quota (approx): 18 gb
Storage usage (approx): 46 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Ivybridge Mobile 
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 255
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by 3dParadox** [comment]
I was going to report that too, it worked while docked. However, it doesn't always seem to update changes.

Plus it doesn't highlight the selected object. (unless you select in the bar manually)

**Comment by AshleyScirra** [comment]
Can't reproduce here, but it looks like from your screenshots your login failed so it didn't activate the license. Try logging out and back in.
