### ISSUE TITLE
LOS does not work out side of viewport (R123.2 C3 Runtime)

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#2232]
## Problem description

LOS works except when the los occurs outside of the games window, viewport dimensions.

In the example i have 2 tile maps, one set to solid which acts as obstacles, and another on top which show which tiles are visible from the mouse position.

It works but once the mouse moves outside the viewport dimensions it no longer works. This is a problem as the screen can be zoomed out.

## Attach a .c3p

[losBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2542399/losBug.c3p.zip)

## Steps to reproduce

Remove .zip from name and run file.

Use middle mouse button to drag, and scroll wheel to zoom screen out.

Mouse mouse about to show all the tiles on the tilemap that can be seen at mouse position.

If the mouse moves out side the original viewport dimensions, but still on the frame, then los no longer works, represented in the example as all tiles becoming visible. 

Check this by resizing the viewport dimensions of the project and running it again.

## Observed result

Los does not work outside of original viewport size regardless of frame size or if unbound scrolling checked (but still in range of los range)

## Expected result

los should work.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 11 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next release.
