### ISSUE TITLE
Starting a tween in an "on tween finished" trigger locks up the tween behavior

### ISSUE THREAD

**Issue by birbdoy** [Scirra/Construct-3-bugs#2233]
## Problem description

Starting a tween following an 'on tween finished' trigger locks up the tween behavior and stops all subsequent tweens from starting.

## Attach a .c3p

[tweenBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2543217/tweenBug.zip)

## Steps to reproduce

1.Hit R, the sprite's angle is interpolated to 90, wait until this is finished.
2.Now the sprite's x position should be interpolated to 0 but nothing happens, the tween behavior is now locked up.
3.Hit space, the sprite's width should be interpolated to 100 but nothing happens.

## Observed result

The tween behavior locks up when a tween is started following an 'on tween finished' trigger.

## Expected result

The tween behavior shouldn't lock up.

## Affected browsers

* Chrome: yes
* Firefox: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 1.2 gb (15.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by bilgekaan** [comment]
This happens with different objects, too. 

![image](https://user-images.githubusercontent.com/2965842/47964820-f73fec80-e04f-11e8-956a-16805a6b84a1.png)

Second tween won't start. But if you add a wait 0 second action before the second tween, it works.

**Comment by DiegoScirra** [comment]
Fixed in the next release.
