### ISSUE TITLE
C3 Build Service : Add to whitelist.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#2235]
## Plugin List

Hey, I have Construct 3 addons I want to support the Build Service. Can you add them to the white-list.
Thanks a lot, in advance.

- cordova-plugin-badge
- cordova-plugin-dialogs
- cordova-launch-review
- cordova-plugin-powermanagement-orig
- cordova-plugin-x-toast
- pushwoosh-cordova-plugin
- cordova-plugin-local-notifications

Hey @shortercode , I remember you suggesting **phonegap-plugin-push** when I asked, it's good but I'm kind of in need of a more automated approach. I don't mind paying for a service, even though **Push Woosh** also has a free plan.

Anyway, I'm looking forward to getting these into the Build Service as soon as you can. Thanks again in advance.

**Comment by shortercode** [comment]
Looking at them today. The versions I am reviewing are:

- cordova-plugin-local-notifications@1.0.0
- pushwoosh-cordova-plugin@7.9.3
- cordova-plugin-x-toast@2.7.0
- cordova-plugin-powermanagement-orig@1.1.2
- cordova-launch-review@3.1.1
- cordova-plugin-dialogs@2.0.1
- cordova-plugin-badge@0.8.7

I will update this list with any dependencies as I find them. Please let me know if any of these are wrong, or you wish to change them.

**Comment by shortercode** [comment]
I've never come across an NPM package with that version syntax... That may require a server update.

So far I've passed:

cordova-plugin-x-toast@2.7.0
cordova-plugin-powermanagement-orig@1.1.2
cordova-launch-review@3.1.1
cordova-plugin-dialogs@2.0.1
cordova-plugin-badge@0.8.7

The other 2 have a lot of sub dependancies, so will take a little longer to look at.

**Comment by shortercode** [comment]
Okay I've updated the build server to understand the semver prerelease format. Also added those 5 that passed to the whitelist.

**Comment by ChadoriRebornXD** [comment]
Thanks a lot for the hard work!
I'm looking forward to the other 2, which are the main plugins I wanted supported.

**Comment by shortercode** [comment]
I'm sorry for the extended delay for the reply on this. I've reviewed those last 2 several times and I cannot guarantee that they are secure or that they will continue to be going forward due to their inclusion of dependencies on unverified repositories. I had hoped to come up with a solution to this issue but I think we will have to live with the restriction for the time being. Perhaps in the future we will rework the cordova dependency system and we can consider it, but it's not currently on the roadmap.

**Comment by ChadoriRebornXD** [comment]
That's unfortunate. Well, I do hope that someday you get a workaround to this and get this supported since notifications are important for game development.
