### ISSUE TITLE
Construct project cannot be closed when object textures are still loading

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2236]
## Problem description

You open project, after project is opened layout sprites&objects still load for a while. But when i open my own project and close it rly quick(can see layout objects havent loaded fully) construct will trow error and ask for restart. For some large project this could be a problem, as you opened wrong project and cant close before stuff is loaded.
(can reproduce everytime)

## Attach a .c3p
[DemonoireLoadBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2545198/DemonoireLoadBug.zip)
## Steps to reproduce

1.Open example, you see objects are without textures for while(depending on pc)
2.You need to manage right click project and select close project(when object textures still loading).
3.See error message(i linked mine, see summary)
Project must open into layout view, not event sheet, if you use your own test project.

## Observed result
If user opens bigger project or chrome is under load from other tabs. Project objects take while to load. But when user managed to click  close project while project layout objects still load, it will trow error and ask for construct client restart.

## Expected result
When big project are opened and closed on weaker pc, it should not trow errors and users should know that they need to wait for project to fully load. Users still open wrong project by mistake and want to close it(as myself i tend to do it fast). 
Or somehow disable close project ability, while project loads.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃL$' of null @ TypeError: Cannot read property 'ǃL$' of null at n.ǃqyn (https://editor.construct.net/r123-2/main.js:81:205480) at n.ǃqyK (https://editor.construct.net/r123-2/main.js:81:163255) at n.ǃmJ (https://editor.construct.net/r123-2/main.js:81:163565) at e.ǃmJ (https://editor.construct.net/r123-2/main.js:81:307827) at new e (https://editor.construct.net/r123-2/components/editors/eventSheetView/eventSheetView.js:1:75522) at new e (https://editor.construct.net/r123-2/components/editors/eventSheetView/eventSheetView.js:1:78829) at Function.ǃq.ǃt (https://editor.construct.net/r123-2/main.js:2:144486) at e.ǃEz (https://editor.construct.net/r123-2/main.js:81:307178) at Object.ǃq.ǃUz [as ǃ$nl] (https://editor.construct.net/r123-2/main.js:81:298256) at n (https://editor.construct.net/r123-2/main.js:2:207831)
Stack: TypeError: Cannot read property 'ǃL$' of null at n.ǃqyn (https://editor.construct.net/r123-2/main.js:81:205480) at n.ǃqyK (https://editor.construct.net/r123-2/main.js:81:163255) at n.ǃmJ (https://editor.construct.net/r123-2/main.js:81:163565) at e.ǃmJ (https://editor.construct.net/r123-2/main.js:81:307827) at new e (https://editor.construct.net/r123-2/components/editors/eventSheetView/eventSheetView.js:1:75522) at new e (https://editor.construct.net/r123-2/components/editors/eventSheetView/eventSheetView.js:1:78829) at Function.ǃq.ǃt (https://editor.construct.net/r123-2/main.js:2:144486) at e.ǃEz (https://editor.construct.net/r123-2/main.js:81:307178) at Object.ǃq.ǃUz [as ǃ$nl] (https://editor.construct.net/r123-2/main.js:81:298256) at n (https://editor.construct.net/r123-2/main.js:2:207831)
Construct 3 version: r123.2
URL: https://editor.construct.net/r123-2/
Date: Sat Nov 03 2018 19:37:34 GMT+0200 (Eastern European Standard Time)
Uptime: 34.5 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
I'm afraid there's nothing we can do without steps to reproduce or at least the crash message.

**Comment by SnipG** [comment]
Updated bug report with better information!

**Comment by AshleyScirra** [comment]
The crash report actually shows it's crashing trying to finish creating an event sheet after closing the project. I found a way to reproduce this, should be fixed for the next release.
