### ISSUE TITLE
Reload from original frames, for animation, not working in Desktop build

### ISSUE THREAD

**Issue by MihaMS** [Scirra/Construct-3-bugs#2238]
## Problem description
After "Import frames from files" - linking isn't happening and if I press "reload from original sources --> Apply to animation" - nothing is updated, and sometime it stucks C3 for about 20 seconds or ends even with C3 crash, or C3 is continue to lag heavily after I press any button in sprite editor... :(
Construct 3 Win64 desktop build Chromium 69 stable-3

_My project contains a lot of animations, and in Construct 2 after I load them at first time (Import frames from files) they linked to its source files automatically and then I need only select "Reload files from Original sources" to reload them, which was very handy!_

## Attach a .c3p
[C3ReloadFramesTest.zip](https://github.com/Scirra/Construct-3-bugs/files/2544720/C3ReloadFramesTest.zip)

## Steps to reproduce

1. Create Sprite object and Import Frames from Files.
2. Change some source frames to see differences...
3. Try to "Reload From Original Source" - "Apply to animation"

## Observed result
Animation frames DON'T updated with new images.

## Expected result
Animation frames updated with new images.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release
