### ISSUE TITLE
Tweening multipe instances simultaneously results in the last one in the pick list trailing behind

### ISSUE THREAD

**Issue by birbdoy** [Scirra/Construct-3-bugs#2239]
## Problem description

Using the tween behavior to interpolate multipe instances simultaneously results in the last one in the pick list trailing behind all others.

## Attach a .c3p

[tweenBug_trailingBehind.zip](https://github.com/Scirra/Construct-3-bugs/files/2544759/tweenBug_trailingBehind.zip)

## Steps to reproduce

1.The repeat loop creates instances from left to right, top to bottom. 
2.Press A and D in short intervals (quicker than the 1s the tweens take to finish). The last instance (bottom right) trails behind all others.
3.Go to the event sheet, reduce the 'Repeat 100 times' to whatever you want greater than 1.
4.Start again, press A and D. 

## Observed result

No matter how many instances you tween simultaneously, the last one in the pick list will always trail behind all others.

## Expected result

All instances should move evenly. I know small seams are to be expected sometimes when moving nonoverlapping sprites like this but there's something going wrong with the last instance in the pick list.

Edit: Don't mind what I wrote down here before. I now understand why the instances start to oscilate even when pressing only D multiple times. That's what the 'allow multiple tweens' checkbox is for I guess.

## Affected browsers

* Chrome: yes
* Firefox: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r122 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 1.2 gb (15.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
@birbdoy I'm still looking at this one, it is quite strange.

I did cap the position the tweens are able to reach, because they are supposed to be absolute. So even though the the oscillation was not really a bug, it wasn't really intuitive either.

**Comment by birbdoy** [comment]
Sounds good!
It was quite a strange find as well. Had two sprites and one was acting a bit wierd, so I thought I'm missing something in my logic. Took a while and different setups to understand what's going on.

**Comment by DiegoScirra** [comment]
Fixed in the next release.
