### ISSUE TITLE
After exporting to debug .apk the game dont show text on start of the game.

### ISSUE THREAD

**Issue by oseq** [Scirra/Construct-3-bugs#2240]
## Problem description
After turning on installed game installed by debug .apk the text is not displayed . The text shows up after around 30 secounds. After disabling webGL (so i had to change back to c2 runtime) issue is gone

## Steps to reproduce

1. create project with webgl turned on
2. insert text object into layout with some sample text
3. export game to debug apk
4. install and turn on the game

## Observed result

i dont see text object

## Expected result

i should see the text, like after exporting to html or when exporting to apk with webgl turned off

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise we cannot help.
