### ISSUE TITLE
Slow preview in C3 runtime in Desktop r123.2

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2242]
## Problem description

Previews are slow in C3 runtime with Desktop r123.2. It takes 5-6 seconds to open the preview. The same project with the same settings can be previewed by chrome PWA in a second.  Desktop version opens the preview window but shows a dark grey screen and waits 5-6 seconds to show the game. I didn't have this issue while I was using C2 runtime. 

I would like to use PWA version but I can't open external editors, save to desktop and copy past images with it.

**Comment by AshleyScirra** [comment]
Can't reproduce here, preview is instant with C3 runtime in r123.2. I'm afraid we can't help with more detailed information (e.g. which browsers are affected; first version that started exhibiting the issue; whether it correlates to specific projects; etc.)
