### ISSUE TITLE
Can't edit an image that drag and dropped to the editor. r123.2

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2243]
## Problem description

When you drag and drop an image to a layout from your desktop, you can't edit it in the image editor.

## Steps to reproduce

1. Drag and drop and image from desktop to the editor.
2. Try to open it in the image editor.

**Comment by Ind1eed** [comment]
Same here.

**Comment by DiegoScirra** [comment]
Fixed in the next release
