### ISSUE TITLE
After exporting to debug .apk the game dont show text on start of the game on C3 runtime

### ISSUE THREAD

**Issue by oseq** [Scirra/Construct-3-bugs#2244]
## Problem description

After turning on installed game exported to debug .apk on c3 runtime the text is not displayed . The text shows up after around 30 secounds if you restart layout.

I cant reproduce this bug on C2 runtime.

## Attach a .c3p

[not text bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2545155/not.text.bug.zip)

## Steps to reproduce
1. make sure project is set to C3 runtime
2. export project with C3 runtime to debug apk
3. install game on device

## Observed result

text is not showned on start of the game, if you restar layout after around 20 s. you should see the text 

## Expected result

to see text

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no
* Android Debug: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Unable to reproduce on a Samsung S8. Can you please provide your device details ( Model, Android version, Chrome version ) and build settings.

**Comment by oseq** [comment]
@shortercode 
Samsung S7, Android 8.0.0, chrome version: newest ;) 
Export settings: no export options checked,  set to min version 5.0+, debug APK, Hide status bar

Bug happend to me on both: r123-2 and stable version of construct

**Comment by oseq** [comment]
@shortercode 
This bug gonna be hard to reporduce, because i could not reproduce it on any other phone. Even having same model (Samsung S7) with same adnroid 8.0.0 did not help. One think that keeps me belifing its not only my phone's bug is this i found forum comments describing same issue (but that user was running C2 runtime and fixed this one by disableing webgl)

**Comment by shortercode** [comment]
Their are several variants of the S7 with different processors if memory serves, so it might be they have different hardware?

Samsung devices have caused various unpleasant driver issues in the past. We have actually disabled WebGL 2 on all Android devices because of a fairly major issue with Samsung drivers, which we do not expect to be fixed any time soon ( they don't have any proper channels for reporting issues like this ). I'm guessing the forum post your looking at is related to that bug, webGL 1 was not effected by it and it reproduced on the S8.

Does this issue also happen if view the same project via a web export or remote preview?

It might be helpful if you could check the browser console for error messages. Do you know how to do this for a mobile? Do you have Android Studio set up on your development computer?

**Comment by oseq** [comment]
@shortercode 
I dont have this issue on Remote Preview, only on apk. 
Verison of my s7 model version is G930FXXU3ERHC, version R16NW/G930FXXS3ERHD, kernel  3.18.91-13895453-QB19588892.

I dont use Android Studio,if it's necessary i can install it.

**Comment by shortercode** [comment]
Sorry for the delays on this issue @oseq I've been looking at feature implementation for awhile, and there was little action I could take on this bug at the time.

We're currently experiencing rendering issues with Mali GPUs again, we will hopefully have a workaround by the time r140 rolls out. Could you check to see if this is still an issue in that release, if it is then I would appreciate it if you could try looking into the Android application log and the Chrome JS log for me.

[Chrome remote debugging guide](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/)

It's also worth noting that Samsung devices are often awkward and require additional steps to get it to appear in the chrome device list. There is a troubleshooting section at the end of the guide. Typically I open Android studio and select "logcat" tab, which starts the connection proper. As a note you have to open a project to actually see the debugger, but it doesn't matter what project...

That logcat tab in android studio is the one which will display the application log messages, there is a box at the top which allows you to choose a "debuggable process" to see the logs for it. You can either install a debug APK on the device and then debug that in Android studio or export as an android studio project and run it as debug on the connected device. You may require additional setup to get the latter to work, Android studio is rather... modular, and generally is missing something you need.

**Comment by AshleyScirra** [comment]
r140 is now out, please check again!

**Comment by AshleyScirra** [comment]
No response so closing.
