### ISSUE TITLE
Trying to move a PixelArt Sprite following the PixelArt guidelines results in shaking

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2247]
## Problem description

Trying to move a PixelArt Sprite following the PixelArt guidelines results in shaking with pixel rounding on

## Attach a .c3p

https://puu.sh/BW3Lr/0eb6058a7f.c3p

## Steps to reproduce

1.Preview the game
2.Move the center sprite with the arrow keys

## Observed result

The sprite centered under scroll shakes

## Expected result

The sprite centered under scroll not to shake

## Affected browsers

* Chrome: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 421 mb (2.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
This happens because your events allow setting the canvas to a fractional size when you want pixel precision. Putting floor() around the "Set canvas size" dimensions appears to fix it.

**Comment by eleanorawesome** [comment]
thank you

**Comment by eleanorawesome** [comment]
Putting floor() around the "set canvas size" dimensions does this on mobile 
![image](https://user-images.githubusercontent.com/32940085/48048191-aa9c0480-e168-11e8-8988-97299f8cb295.png)

**Comment by eleanorawesome** [comment]
I think this is a different issue, I'm going to file it, using fullscreen quality to low on mobile results in extreme zoom ins

**Comment by eleanorawesome** [comment]
it'S still shaking for me https://puu.sh/BXaeE/ff4355b619.mp4

**Comment by eleanorawesome** [comment]
Ok I found out when it shakes @AshleyScirra 

It shakes when the canvas size is an odd number in the axis that the object is moving

**Comment by AshleyScirra** [comment]
It's tough to get the scaling right. It's probably a mistake in your events if it doesn't happen when you let Construct handle the scaling for you.

**Comment by eleanorawesome** [comment]
But there isn't a way to let construct handle scaling for me with pixel art 😿

**Comment by eleanorawesome** [comment]
IT doesn't work because mobile device have tons of different aspect ratios and resolutions it's impossible to have a canvas size that will fit them without those events
