### ISSUE TITLE
Using stop action in tween behavior freezes the game. r123.2

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2252]
## Problem description

When I use the stop action in tween behavior (stop all or stop "x"), it stops the whole game.

![image](https://user-images.githubusercontent.com/2965842/47971235-8543c380-e0a0-11e8-928e-6e2aad02701b.png)

## Attach a .c3p

[tween-stop.zip](https://github.com/Scirra/Construct-3-bugs/files/2546414/tween-stop.zip)

**Comment by DiegoScirra** [comment]
Fixed in the next release

**Comment by Kyatric** [comment]
It seems to still be present in r124.
