### ISSUE TITLE
"Persist" combined with other behaviors freezes game in C3 runtime. r120 stable

### ISSUE THREAD

**Issue by EydiavHamri** [Scirra/Construct-3-bugs#2253]
## Problem description

If a layout contains an object that has "Persist" behavior and either "LineOfSight" or "Platform" behavior, the game will freeze if that layout is revisited later.
Only happens in C3 runtime.

## Attach a .c3p

https://1drv.ms/u/s!Av0tQkU7g1YnmuhBEkavu9uUGqDbUw

## Steps to reproduce

1. Preview from "Init" layout or hit f4.
2. Walk off-screen to get to a layout that contains an object with the behaviors.
3. Go to another layout or head back to the previous layout.
4. Go back to the layout with the object. And the game will freeze.

## Observed result

Game freezes completely.

## Expected result

Be able to freely walk between layouts without any issues, like when previewed with C2 runtime.

## Affected browsers

* Chrome
* Edge
* Firefox

**Comment by shortercode** [comment]
Also effects current development version. The persistence code for LOS appears to not work. Assigning to @AshleyScirra

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
