### ISSUE TITLE
(r123-2 C3 runtime) HTML exports not working with minification enabled

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2255]
## Problem description

make Demonoir HTML export with minification and host

just get black screen   (also console errors about icons)

works fine without minification

**Comment by AshleyScirra** [comment]
Can't reproduce, works for me.

**Comment by NetOneGames** [comment]
Dang... 
There is definitly something happening (on my end at least) when minifcation used.   There were console errors wrt to not recognising the icons pngs as valid formats. I'll have a propper look over Christmas.

**Comment by AshleyScirra** [comment]
Any errors about icons is probably unrelated to minification. If you at least include the error logs then I could guess at what might be going on. This is why we always ask for detailed bug reports, it's never as simple as anyone thinks.
