### ISSUE TITLE
Desktop version (only) can't upload new icons

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2256]
## Problem description

![image](https://user-images.githubusercontent.com/7268697/48036136-aaebce00-e16f-11e8-9b50-b7c3b17ba239.png)

I made an empty project and tried to change an icon to this one which i saved first in paint.net and tried which failed, then saved through photoshop and failed again.

Attached is the image: 
![d_128x128](https://user-images.githubusercontent.com/7268697/48036168-d7074f00-e16f-11e8-906f-16f534621d8c.png)

The web version works. This might be related to the bug in which the names of the files imported come in with the WHOLE path for some reason. So if I upload a file A.txt it will come with "C:\Users\JeFawk\Desktop\A.txt"

## Attach a .c3p

Use an empty project

## Steps to reproduce

1. open desktop version of C3 using C2 runtime (if that makes any difference)
2. try to change icon-128.png by opening it and uploading the attached image

## Observed result

You will get an error even though the icon is of the correct format.

## Affected browsers

* Desktop: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.31.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.3541666269302368
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@878cd31214ac27a3996927cd5c9c138b10c9fc8d) NWjs/0.31.2 (like Chrome/67.0.3396.87)
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 5.1 gb
Storage usage (approx): 210 mb (4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by NetOneGames** [comment]
interesting. there are also console errors about icons when uploaded html export with minifiction, when checking the icons folder on the server they are not the ones that should be exported but are some old ones from some other file.

**Comment by DiegoScirra** [comment]
The issue reported by @JeFawk is fixed in the next release.

@NetOneGames, that sounds like a different problem, better make a new report for that one.
