### ISSUE TITLE
When a layer uses it'S own texture with "fullscreen quality set to low" the layer scaling is zoomed in

### ISSUE THREAD

**Issue by eleanorjmorel** [Scirra/Construct-3-bugs#2257]
## Problem description

When a layer uses it'S own texture with "fullscreen quality set to low" the texture is zoomed in 
## Attach a .c3p

https://puu.sh/BXa0k/f4f0bd1c2a.c3p

## Steps to reproduce

1.preview the game with force own texture on
2.preview the game with force own texture off

## Observed result

Force own texture off is on the left side, force texture on is on the right side
![image](https://user-images.githubusercontent.com/32940085/48048739-71fd2a80-e16a-11e8-9059-337899aa8719.png)

(It creates even more problems with different layers with and without force own texture the scaling is all over the place)

if a layer has an opacity that isn'T 100%, it will uses it'S own texture and everything will be out of whack

## Expected result

I don'T expect the scaling of layers to be different depending on if force own texture is on or off

## Affected browsers

* Chrome: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 422 mb (2.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by eleanorawesome** [comment]
Tested with r124

https://puu.sh/BXn5l/6c8bf467dd.c3p

Minimal project, one layer with force own texture, the other layer without

The higher the scaling, the bigger the sprite on the layer with force own texture

https://puu.sh/BXnab/9afb2ddcad.mp4

**Comment by NetOneGames** [comment]
simlar same issue
https://github.com/Scirra/Construct-3-bugs/issues/2274
