### ISSUE TITLE
Crash When Exiting App With Active Dialog Preview

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#2258]
## Problem description

Construct 3 desktop crashes when trying to exit the app with an active dialog preview window. I could not reproduce this with other browsers so marking it as desktop only is recommended.

## Attach a .c3p

New project will do, this is an editor issue.

## Steps to reproduce

1. Set preview mode to "dialog"
2. Open any project and preview it
3. Exit app using any method and notice crash while exiting

## Observed result

Construct 3 crashes when exiting with an active dialog preview.

## Expected result

Construct 3 should exit fine like it does in all other browsers.

## Affected browsers

* NW.js: yes
* Chrome: no
* Firefox: no

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property '0' of undefined @ TypeError: Cannot read property '0' of undefined at Object. (extensions::nw.Window:145:118) at Object.handleRequest (extensions::binding:64:27) at Object. (extensions::binding:377:32) at NWWindow.get (extensions::nw.Window:592:40)
Stack: TypeError: Cannot read property '0' of undefined at Object. (extensions::nw.Window:145:118) at Object.handleRequest (extensions::binding:64:27) at Object. (extensions::binding:377:32) at NWWindow.get (extensions::nw.Window:592:40)
Construct 3 version: r124
URL: https://editor.construct.net/r124/
Date: Tue Nov 06 2018 14:40:32 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 42.2 s

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r124 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
The crash is in NW.js. I filed it with them some time ago but they haven't dealt with it yet: https://github.com/nwjs/nw.js/issues/6553
