### ISSUE TITLE
[firefox] Paste missing from right click context menu.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2261]
## Problem description

Somehow the option to paste is missing from right click context menu. cut and copy still there.

## Attach a .c3p

N/A

## Steps to reproduce

1. Go to any event sheet and right click to copy event.
2. Right click to paste is missing.

## Observed result

Paste missing

## Expected result

Should be there like before.

## Affected browsers

* Firefox: yes

**Comment by AshleyScirra** [comment]
Construct can only show a "Paste" option when the browser supports the clipboard read permission. So far this is only supported in Chrome. Otherwise you can only activate paste by a keyboard shortcut or browser menu.

**Comment by tunepunk** [comment]
But it has always been there up until recently... Firefox is my main goto browser for C3. Now I can't use it anymore since other browsers have crappy pen support. It should be shown with the internal clipboard option in settings at least then.

**Comment by AshleyScirra** [comment]
I thought it was never there? If there was a change then that should be investigated.

**Comment by tunepunk** [comment]
By the way.. The paste option dialog works in firefox on mac though... but not on my windows machine.

**Comment by AshleyScirra** [comment]
It's useful to include the specific versions you are using. I suspect the recent Firefox 63 update may have broken this.

**Comment by tunepunk** [comment]
Updated to 63 on My mac, and now the paste option went missing there too. Hmmmm

**Comment by AshleyScirra** [comment]
It turns out Firefox 63 shipped a broken clipboard.readText implementation which breaks our clipboard code 🤦‍♂️ worked around it for the next release.

**Comment by tunepunk** [comment]
Awesome Thanks a lot for the quick fix!
