### ISSUE TITLE
Tween behavior freezes the game "on finished" r124

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2262]
## Problem description

When the first "On finished" Tween behavior's condition of my game is reached, the game freezes.

## Attach a .c3p

https://kyatric.com/c3/bugs/2018.11.06.FDAP.a.c3p

## Steps to reproduce

1. Open the project
2. Preview
3. Press space

## Observed result

A random green character starts moving. When it stops, the clock of the game stops.
Moreover, the console of the browser throws an error about a property "length" that cannot be read.

## Expected result

The game to keep on going (another tween to kick in, and then another one, forming a sort of parabola).

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
@Kyatric I fixed this crash and a couple of others that showed up after fixing that one.

As for the expected result, that's a different story.

If you wish to produce a sort of curve using tweens you need to have two different tweens, one for X coordinate and another for Y coordinate. The trick is that each tween should use a different easing function, that will produce the effect of a curve motion.
