### ISSUE TITLE
Game freezes if particle system's Object (to spawn) isn't placed in any layout

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#2265]
## Problem description

If you assign a particle system's Object parameter an object type that doesn't have an instance placed in a layout, the game freezes at runtime, with only an error in the browser console.

## Attach a .c3p

[ParticleSystemBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2555975/ParticleSystemBug.zip)

## Steps to reproduce

1. Create a particle system.
2. Create a sprite, but do not place the sprite in any layout.
3. Set the particle system's Object parameter to the sprite.
4. Launch the game.

## Observed result

The game freezes with an error in the browser console, like so:

Uncaught (in promise) TypeError: Cannot read property '1' of null
    at C3.Runtime.CreateInstanceFromData (runtime.js:1)
    at C3.Runtime.CreateInstance (runtime.js:1)
    at C3.Plugins.Particles.Instance._OnParticleCreate (instance.js:1)
    at _spawnObjectClass.c.onparticlecreate (instance.js:1)
    at self.Particle.Init (particle.js:1)
    at self.ParticleEngine._CreateParticle (particleEngine.js:1)
    at self.ParticleEngine._SpawnContinuous (particleEngine.js:1)
    at self.ParticleEngine.Tick (particleEngine.js:1)
    at C3.Plugins.Particles.Instance.Tick (instance.js:1)
    at Array._isTicking._tickFunc._tickFunc (sdkInstanceBase.js:1)

## Expected result

The editor should warn the user that an instance of the object type being spawned by the particle system hasn't been placed in a layout (or better yet not require instances of things to be placed in a layout at design time for things to work at runtime - previewing the particle system in the editor works just fine even without an instance of the Object sprite being placed in the layout ahead of time, so it's unintuitive that this is the cause of the game hanging), or this should fail with a more user-friendly message at runtime.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r124 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 6.6 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in the next build - the C3 runtime can now support creating instances that aren't placed in any layouts. However all its properties will default to empty values, so you should place an instance if you want to control the initial values, or use actions to change them after creation.
