### ISSUE TITLE
windows UTF-8 file encoding error

### ISSUE THREAD

**Issue by MrWonka** [Scirra/Construct-3-bugs#2266]
## Problem description

Exporting a project to windows store triggers an error

## Attach a .c3p

N/A

## Steps to reproduce

1. Export project to UWP
2. Create a package in VS
3. Upload to Windows Partner Center

## Observed result

FAILED
    UTF-8 file encoding

    Error Found: The UTF-8 file encoding test detected the following errors:
        File box2d.wasm.js is not properly UTF-8 encoded. Re-save the file as UTF-8 (including Byte Order Mark).
        File scripts\dispatchWorker.js is not properly UTF-8 encoded. Re-save the file as UTF-8 (including Byte Order Mark).
        File scripts\jobWorker.js is not properly UTF-8 encoded. Re-save the file as UTF-8 (including Byte Order Mark).
        File scripts\supportCheck.js is not properly UTF-8 encoded. Re-save the file as UTF-8 (including Byte Order Mark).
    Impact if not fixed: HTML, CSS, and JavaScript files must be encoded in UTF-8 form with a corresponding byte-order mark (BOM) in order to benefit from bytecode caching and to avoid other runtime error conditions.
    How to fix: Open the affected file, and select "Save As..." option from the File menu in Visual Studio. Select the drop-down control next to the Save button and select "Save with Encoding..." option. From the Advanced save options dialog, choose the "Unicode (UTF-8 with signature)" option and click the OK button.

**Comment by AshleyScirra** [comment]
Ugh, they are encoded in UTF-8, but looks like the store is super fussy about this...

**Comment by AshleyScirra** [comment]
Also which version exactly did you export with? Please always follow the bug report guidelines so we don't have to ask.

**Comment by MrWonka** [comment]
10.0.17134.0

**Comment by AshleyScirra** [comment]
No, the version of Construct 3. Please always follow the bug report guidelines and fill in all the requested information so we can deal with your report more effectively.

**Comment by MrWonka** [comment]
r124

**Comment by AshleyScirra** [comment]
Still no project provided so closing
