### ISSUE TITLE
Assigning a Family with more than one sprite to a particle system crashes Construct

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#2268]
## Problem description

Assigning a Family with two sprites in it to a particle system's Object parameter immediately crashes the editor.

## Attach a .c3p

[ParticleSystemBug2.zip](https://github.com/Scirra/Construct-3-bugs/files/2556183/ParticleSystemBug2.zip)

## Steps to reproduce

1. Create a particle system and place it in the layout.
2. Create two sprites in the layout.
3. Assign both sprites to a family.
4. Assign the family to the particle system's Object parameter.

## Observed result

Construct crashes.

## Expected result

Families should work as particle system objects.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r124/plugins/general/particles/plugin.js, line 1, col 3545
Message: Uncaught TypeError: a.ǃ$F is not a function
Stack: TypeError: a.ǃ$F is not a function at a.ǃHj.ǃws (https://editor.construct.net/r124/plugins/general/particles/plugin.js:1:3545) at a.ǃHj.ǃq_ (https://editor.construct.net/r124/plugins/general/particles/plugin.js:1:2708) at o.ǃq_ (https://editor.construct.net/r124/main.js:81:226315) at d.ǃq_ (https://editor.construct.net/r124/main.js:81:266753) at d.ǃq_ (https://editor.construct.net/r124/main.js:81:250995) at window.ǃO.ǃl (https://editor.construct.net/r124/components/editors/layoutView/layoutView.js:1:6982) at ǃm (https://editor.construct.net/r124/components/editors/layoutView/layoutView.js:1:1729)
Construct 3 version: r124
URL: https://editor.construct.net/r124/index.html
Date: Tue Nov 06 2018 21:48:17 GMT-0800 (Pacific Standard Time)
Uptime: 286 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r124 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
