### ISSUE TITLE
Google Play and VS

### ISSUE THREAD

**Issue by MrWonka** [Scirra/Construct-3-bugs#2272]
## Problem description

VS seems to hate google play. Including it in a project makes the project crash. Removing it "fixes" the problem, which is what I've been doing internally, but I would appreciate a more user friendly solution, such as the problem code being removed during exports?

## Attach a .c3p
[demo.zip](https://github.com/Scirra/Construct-3-bugs/files/2557412/demo.zip)

## Steps to reproduce

1. Create a project with google play
2. Export to UWP
3. Open in VS

## Observed result
SCRIPT5022: Unhandled exception at line 2, column 417582 in ms-appx://0d3ae010-6e87-4602-a986-af5f119b96f8/scripts/c3runtime.js
0x800a139e - JavaScript runtime error: [object Event]

**Comment by shortercode** [comment]
I don't think it's feasible to remove it during export. I'm not sure but Google Play ( web ) might work in UWP anyway; even if it didn't it's a complicated change for next to no win ( removing a single, very small, text file). If you wish to avoid including the code then I advise not including the plugin on your UWP version.

I will investigate why it is having a problem and try and stop it causing a failure.

**Comment by shortercode** [comment]
Okay this should be resolved in the next release, sorry this took me awhile to look into. The plugin was failing to the load the webAPI script and then preventing the runtime from starting. It now allows the runtime to continue once the script load has failed ( which appears to be instant ). I don't know why it doesn't load, it's presumably a platform security restriction.
