### ISSUE TITLE
Objects Scale affected by layer blend and effects

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2274]
## Problem description

note: cant seem to replicate this in non full screen as per my project but can in full screen
Ive made this seperate from the other issue which is more about fullscreen overall scale
this is about layout/object scaling

Object scaling is affected by layer effects and blend mode

See attached file  (filename changed to zip)

## Attach a .c3p

edit new improved file

[Scaling Issues.zip](https://github.com/Scirra/Construct-3-bugs/files/2558000/Scaling.Issues.zip)

view in full screen mode
but also happens if game window touches top/bottom monitor screen edge

file automatically changes layer blend mode to additive and back to normal every second.
observe change in size of sprite.

does not happen if underneath layer removed
does not happen if high quality scaling
does not happen in non full screen if no edges touching screen sides.
also happens if replace additive with tint

## Affected browsers

* Chrome: only tested

## System details

</details>

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.75
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36
C3 release: r124 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 47 gb
Storage usage (approx): 929 mb (1.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro K3100M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
Can you try to produce repro projects that are as minimal as possible? Projects such as attached here are actually pretty complicated with lots of options and modes, and it makes it harder to deal with the issue. Ideally it would just be a single sprite and reproduce the problem automatically with no user input.

**Comment by AshleyScirra** [comment]
FYI the additive blend or tint modes are probably switching the layer to force own texture mode, so you can probably just make a repro based on that alone instead of having different things that variously enable force own texture as a side effect.

**Comment by NetOneGames** [comment]
I did try with force own texture on/ off but I could not replicate. 

But does happen with additive and tint.

I will pare down the project,,,  one moment.......

**Comment by NetOneGames** [comment]
OK here you go

[Scaling Issues.zip](https://github.com/Scirra/Construct-3-bugs/files/2557998/Scaling.Issues.zip)

**Comment by AshleyScirra** [comment]
Thanks, that's exactly the kind of project we need. Should be fixed in the next release.
