### ISSUE TITLE
Google Play Sign in Issue

### ISSUE THREAD

**Issue by lumicreative** [Scirra/Construct-3-bugs#2275]
## Problem description

When using the Google Play object, signing in does not initiate sign in properly. Usually a quick flicker or nothing at all.

[See thread here](https://www.construct.net/en/forum/construct-3/general-discussion-7/googleplay-not-working-on-runt-139020#forumPost955559)

## Attach a .c3p

[GooglePlaySignIn.zip](https://github.com/Scirra/Construct-3-bugs/files/2560257/GooglePlaySignIn.zip)

## Steps to reproduce

1. Insert the Google Play object (already in the attached)
2. Export as Debug APK (or export as signed APK and launch on GooglePlay store).
3. Run app

## Observed result

User does not get signed into Google Play services.

## Expected result

User should get the dialog to sign in and successfully sign in.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 357 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by sotano42** [comment]
in my experience, Debug APK never signs in... so this won't be an issue I guess, unless Scirra guys says otherwise. Anyway, just trying to help...

**Comment by shortercode** [comment]
@sotano42 debug APKs need to be manually signed with the key that matches the signature you provided to Google Services. Otherwise the sign in dialog closes instantly.

@lumicreative I'm aware of an issues with the web version, due to an error in loading checks it would not sign in unless it had been signed in during that session. That should be fixed in the next release. I will review if there is an issue with the mobile version.

**Comment by lumicreative** [comment]
@shortercode Actually, this also happens with my signed APK. Checkout Football Dash on GooglePlay. It's supposed to sign in on load as well as if you click on the leaderboard button if you're not signed in. It has the correct Application ID from GooglePlay on the GooglePlay plugin.

**Comment by dimielannes** [comment]
![error](https://user-images.githubusercontent.com/8438162/48271445-7c961900-e423-11e8-9088-8876a3dfbbfa.png)
![error2](https://user-images.githubusercontent.com/8438162/48271494-98012400-e423-11e8-9bdb-7c827217e1af.png)

**Comment by luckyrawatlucky** [comment]
I know what happening with Google Play and MobileIAP. after some experiments i found that 
Google Play and MobileIAP are not working in C3 runtime but when i switched from C3 runtime to C2 runtime then both of them are working correctly.

**Comment by lumicreative** [comment]
Yup, we just need both to work on C3 runtime.

**Comment by shortercode** [comment]
There was a patch for Mobile IAP ( c3runtime ) in r128 which should have fixed the major issues.

There's a patch coming in the next release for Google Play ( c3runtime ) which fixes an initialisation problem in the Android app version.

I've also just fixed an issue in Google Play ( c3runtime ) that stops the chrome pop up blocker showing the sign in dialog in the web version.

I'm currently not aware of any more issues with the c3runtime version of these plugins, I believe the latter issue is the one which this thread refers to?

**Comment by shortercode** [comment]
Can anyone confirm that this issue is resolved? @lumicreative

**Comment by shortercode** [comment]
Given this bug has been inactive for a month and I believe it has been resolved I'm closing it. Please file a new issue if you have a reproducible bug.
