### ISSUE TITLE
Unable to export UWP game on xbox one Dev from visual studio 2017 - Error MSB3842

### ISSUE THREAD

**Issue by chucknorris447** [Scirra/Construct-3-bugs#2276]
## Problem description

After having followed the steps from this  [tutorial](https://www.scirra.com/tutorials/9540/using-xbox-live-in-uwp-apps#h2a1) to test a UWP game on a XBOXOne Dev, I'm getting the following error:

**Warning**	_

> MSB3842	Project "D.A.R.K" depends upon SDK "Visual C++ 2015 Runtime for Universal Windows Platform Apps v14.0" which supports apps targeting "UAP 10.0". To verify whether "Visual C++ 2015 Runtime for Universal Windows Platform Apps v14.0" is compatible with "UAP 10.0.17763.0", contact the SDK author or see http://go.microsoft.com/fwlink/?LinkID=309181.	D.A.R.K	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

Line 2377	

![msb_3842](https://user-images.githubusercontent.com/44848302/48155057-234dae80-e298-11e8-87db-ba9a5255ccf2.jpg)

The export from Construct 3 (v 124) UWP gives win 10 SDK 10.0.17763.0
![export_c3_sdkwin10](https://user-images.githubusercontent.com/44848302/48159203-98be7c80-e2a2-11e8-909d-0c6353a2ea85.jpg)

## Attach a .c3p

Download [here](https://1drv.ms/u/s!AmKrqqR19_8ujzYUUTIoSKSfDN7x)

## Steps to reproduce

1. Follow the steps from this tutorial (https://www.scirra.com/tutorials/9540/using-xbox-live-in-uwp-apps#h2a1)
2. In visual studio 2017, from the top bar, select Debug / X64 / Remote test and press play button
3. Notice that the output generates the warning MSB3842 related to wrong target Visual C++ 2015 Runtime

## Observed result

Notice that attempting to test the game remotely generate a warning MSB3842 related to wrong target Visual C++ 2015

## Expected result

The game UWP is deployed remotely on the Xbox One dev, so the game can be tested.

## Affected browsers

N/A

## System details

OS: Win 10
Construct 3 v 124

Microsoft Visual Studio Community 2017 
Version 15.8.9
VisualStudio.15.Release/15.8.9+28010.2050
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA283
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.13.10627.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.8.05085.0
ASP.NET and Web Tools 2017

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IncrediBuild Build Acceleration   1.5.0.3
IncrediBuild effectively reduces compilation and development times by up to 90%.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   15.8.20822.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.9.0-beta8-63208-01
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.27924.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Apache Cordova   15.123.7408.1
Visual Studio Tools for Apache Cordova

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.28010.2046
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I can reproduce the warning here, but it looks like an informational message and then the app continues to run normally. So it doesn't appear to prevent anything working.

Other than that the SDK, libraries and the rest of Visual Studio are all Microsoft's software - if you need support with them it would be best to contact Microsoft about it.
