### ISSUE TITLE
Custom fonts appear differently in Windows and MacOS browsers

### ISSUE THREAD

**Issue by valerypopoff** [Scirra/Construct-3-bugs#2278]
## Problem description

Custom fonts appear differently in Windows and MacOS browsers. It seems to be OK in Windows browsers but in MacOS browsers the text is shifted several pixels lower. It reproduces on both edittime (when you're on editor.construct.net) and runtime (in preview mode and when you upload the game to the server). 

Windows:
![screen shot 2018-11-08 at 2 48 20 pm](https://user-images.githubusercontent.com/5064630/48198245-4a27e580-e369-11e8-8e10-e7308a605957.png)

MacOS:
![screen shot 2018-11-08 at 2 48 06 pm](https://user-images.githubusercontent.com/5064630/48198250-4eec9980-e369-11e8-8e05-6b222768175a.png)

## Attach a .c3p
[New project (5).c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2561645/New.project.5.c3p.zip)

## Steps to reproduce
1. Open the project on Windows and see that text touches the corners
2. Run the project and see that text touches the corners
3. Export the project and upload the game to the server, see that text touches the corners
4. Open the project on MacOS and see that text doesn't touch the corners
5. Run the project and see that text doesn't touch the corners
6. Open the uploaded game, and see that text doesn't touch the corners

## Observed result
Text appears shifted on MacOS

## Expected result
Text appears the same on Windows and MacOS

## Affected browsers

* Chrome: yes
* Safari: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r122 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 134 mb (0.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon HD 6770M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Construct doesn't render the text, the browser does - and the browser may pass the job on to the OS to do the text rendering. Since text rendering is not identical across all platforms there may be slight differences. Construct is running identical code across all platforms (I can't think of anything platform specific we do in text rendering), so I am sure it is issuing identical drawing commands across platforms. If the browser or OS renders text differently in response to that I'm afraid I don't think there's anything we can do about that. You could try reporting the issue directly to browser vendors.
