### ISSUE TITLE
Problem with collision polygon

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#228]
## Problem description

Sometimes, when I select a polygon point (Animations editor > Collision Polygon) and enter a value X or Y, the value is not the same value of point position in the screen. I don't know when it happens, but it happen many times for me. (like a difference of 50 pixels or more)
The focus on the number is not very clean : When I click on a value : first there's a selection of the numbers and after the cursor go right.
Are the values round up to an integer ? Because points are no snaping to a real pixel in the window.
It would be great if the snap grid coul snap the collision box points too.

## Steps to reproduce

I haven't found a step to reproduce this bug, but It happen many times.

## Observed result

An offset between the digit and the real position of the point

## Expected result

The real position of the point

## Affected browsers

* Chrome: yes/

**Comment by DiegoScirra** [comment]
Are you using a browser zoom different to 100%

**Comment by AshleyScirra** [comment]
@Picoti please remember to always include the requested information in the guidelines, if you had included it, it would have answered Diego's question already.

**Comment by Picoti** [comment]
Right. The bug happens when I resize the Animations editor Windows.

**Comment by AshleyScirra** [comment]
This does not answer Diego's question, please provide the requested information otherwise we cannot help you.

**Comment by Picoti** [comment]
@DiegoScirra : The browser zoom is 100%

**Comment by Picoti** [comment]
My impression is as if the collision box was blocked by a sprite edge that does not exist visually. As if a point of the collision box was included in a sprite size different from that shown on the screen.
Sorry for my English, this is not my original language.
And sorry but I haven 'seen in the guidelines that we must specify the zoom of the explorer.

**Comment by DiegoScirra** [comment]
I found a bug in the tool by reading your description, but I am not quite sure if it is the same thing you are describing. Here it is how to reproduce it.

1) Select the collision polygon tool
2) Select a vertex, it should become yellow.
3) Set a position in either of the number inputs
4) While the number input still has focus, resize the main panel

This reverts the change you just made.

Does this look like the problem you are having?

**Comment by Picoti** [comment]
No this is not the problem i'm having.
I think the issue you mentioned is not really a bug, because the new number is not validate.
The problem i had is when i stay in the animations editor, I select a point and this point stay at the same place whatever the number I set in either of the number inputs
Sorry to bother, i'll try to understand why this problem happen sometimes (for exemple yesterday I use Construct 3 all the afternoon and this bug happen 3 or 4 times)

**Comment by Picoti** [comment]
[Collision_polygon.zip](https://github.com/Scirra/Construct-3-bugs/files/1025413/Collision_polygon.zip)

Hello. Here is a C3P with the problem.
Double clic on PlatformTomb2 and go to Edit Collision Polygon.
The point Up Right is X=140
The point down Right is X=128.
If you try to enter the value 140 to X for the Down Right point, it doesn't Work.

**Comment by DiegoScirra** [comment]
Alright, this is fixed in r34.

@Picoti, thank you for finding the reproduction steps.
