### ISSUE TITLE
Hitting ctrl+left arrow in the text editor moves location of text input but not cursor

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#2285]
## Problem description

If you're at the end of a word in the text editor and you hit ctrl+left arrow, the cursor stays put, but if you start typing, the new characters appear at the start of the word. But then if you hit backspace or delete, the backspace/delete starts at the end of the word, where the cursor still is.

## Attach a .c3p

Can be reproduced in an empty project.

## Steps to reproduce

1. Create a text file in Construct 3.
2. Double click it to open the text editor.
3. Type a word.
4. With the cursor at the end of the word, hold the ctrl key and hit the left arrow on the keyboard. Note that the cursor doesn't move.
5. Type something else.

## Observed result

The newly-typed text appears at the start of the word, rather than the end, where the cursor still is.

Note: Other keys like backspace or delete still use the cursor's location. Also, this only seems to be an issue with ctrl+left arrow, not ctrl+right arrow.

## Expected result

Ideally the cursor would jump to the start of the word and all input should use that as the operating location, just like Notepad and most other text editors, and everything would work for both left and right arrows, but otherwise the location of newly-typed text should just match the visible location of the cursor.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r124 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 3.8 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Okay I have updated to the latest version, which seems to have resolved the issue. Will be resolved in the next release.
