### ISSUE TITLE
Backspace key in Cloud Save dialog deletes entire filename instead of character at insertion point

### ISSUE THREAD

**Issue by VictoryRice** [Scirra/Construct-3-bugs#2287]
## Problem description

When saving a .c3p project using Cloud Save As (Menu > Project > Save as > Cloud save), the dialog pops up offering me the choice to change the filename. When I click my mouse to put the insertion point into the filename and then press the Backspace key, **it often, but not always** deletes the entire filename instead of only deleting the character to the left of the insertion point. (Typing other keys such as letters behaves as expected, inserting those letters into the filename from the insertion point.)

Please see a couple of animated GIFs here showing the issue. The first one shows my current project doing a Save As, and you'll see it very consistently deletes the whole filename when I press backspace. I try highlighting some characters and pressing backspace, which in one case deletes everything but in the next case works as expected:
![cloud_save1](https://user-images.githubusercontent.com/8423528/48248313-a4499a80-e3ab-11e8-9cf8-bf011aca104c.gif)

I tried creating a new project, totally blank, and doing Save As. It for whatever reason seemed to have proper behavior more often than not (whereas in my current project it seems to only occasionally behave correctly), but it still happens sometimes as you'll see:
![cloud_save2](https://user-images.githubusercontent.com/8423528/48248371-e4a91880-e3ab-11e8-8c20-ad3af52a7111.gif)

This is an issue because I like to frequently save new versions, so I want to delete the old version number from the current filename and increment it by one.

## Attach a .c3p

I don't think it's applicable but happy to send if you think it will help.

## Steps to reproduce

1. Create a new project
2. Click Menu > Project > Save as > Cloud save
3. Click in the filename input box and press backspace. If it works as expected, repeatedly click on other files in the folder to load their file names into the filename input box, and repeat until you observe the issue.

## Observed result

Filename is completely deleted when I press backspace

## Expected result

Only the character to the left of the insertion point would be deleted

## Affected browsers

* Chrome: yes
* Firefox: did not test
* Edge: did not test
* Safari: did not test

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 73 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5800 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Thanks for the report, and the excellent gifs they were helpful finding the replication behaviour. 

The issue seems only replicate if you have a file selected and then you type a name that matches another file ( it updates as you type ). It would deselect the old file ( clearing the filename input ) but when selecting the new one it would not update the filename input because it was being edited.

**Comment by VictoryRice** [comment]
Ah! That explains it why it was only happening sometimes (and only started happening recently): I now have enough versions saved in that folder that if I try to change xxxx_v24.c3p to xxxx_v25.c3p, I'm deleting the '4' and creating xxxx_v2.c3p which matches an older file name.

**Comment by shortercode** [comment]
Okay we've gone ahead with it, should be resolved in the next release.

**Comment by AshleyScirra** [comment]
r126 is now out, please check again!

**Comment by VictoryRice** [comment]
Confirmed, issue resolved in beta r126 :)
