### ISSUE TITLE
How do I get my (object) buttons to work again?... They were working in C2... (New to C3:) 

### ISSUE THREAD

**Issue by guanstar** [Scirra/Construct-3-bugs#2288]
## Problem description
Can you please help me out? They're not working anymore with c3 (I tested it on a 5.1 Android phone), but they were working with c2:( 

Pinned objects (the leftButton, rightButton, and exit button) do not appear when they should, and if I force them to appear (with the Tween behavior), nothing happens when I click on them.

Also, when I click in the general middle area of the screen, the screen goes black, except for the text:(

## Attach a .c3p
[The Gospel of Luke.zip](https://github.com/Scirra/Construct-3-bugs/files/2565971/The.Gospel.of.Luke.zip)

## Steps to reproduce

1. If you open it up/test it, and click on any button, the pinned objects I stated above, don't show up.
2. If you click in the middle area of the screen, the whole screen just goes black, except for the text.

**Comment by AshleyScirra** [comment]
The project uses a third-party addon (Lite tween). Please see the bug report guidelines. If you just need general help, please post to the forum first.

**Comment by guanstar** [comment]
Hey @AshleyScirra I did post it on Construct, but didn't get any help. Why are you closing this issue? Can you please, check the /ecp3?
https://www.construct.net/en/forum/construct-3/how-do-i-8/how-do-i-get-my-object-buttons-139204

**Comment by AshleyScirra** [comment]
The problem could be caused by the third-party addon. Removing it proves it is not the cause. Please see the bug report guidelines which explain this. I'm afraid we cannot be responsible for supporting third-party addons.

**Comment by guanstar** [comment]
@AshleyScirra So, let me get this straight, is there no way of using any Tween plugin? Is there no Tweening build into c3? Instead of a tween behavior, should I just make the objects invisible to visible, when a button is pushed?  

Also, if there's no Tweening in c3, will there ever be?

**Comment by AshleyScirra** [comment]
We added an official Tween behavior in [r123](https://www.construct.net/en/make-games/releases/beta/r123).

**Comment by guanstar** [comment]
If it's an official Tween behavior in r123, how can you considered it a third-party behavior. Please, can you just check .c3p, and tell me for sure, if the problem is the Tween behavior? I don't won't to do a bunch or pointless wondering and work:(

**Comment by guanstar** [comment]
Wow. I made so many spelling mistakes in that last reply, lol.

**Comment by guanstar** [comment]
If it's an official Tween behavior in r123, how can you consider it a third-party behavior? It's official, lol. Please, can you just check .c3p, and tell me for sure, if the problem is the Tween behavior? I don't want to do a bunch or pointless wondering and work:(

**Comment by guanstar** [comment]
Hello?

**Comment by AshleyScirra** [comment]
The project you provided used 'Lite tween', which is a third-party tween addon.
