### ISSUE TITLE
Crash when moving folder

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#2291]
[test.zip](https://github.com/Scirra/Construct-3-bugs/files/2568855/test.zip)

## Problem description

When moving a self made folder (in the project bar, under "object types") by dragging a folder up or down by mouse, C3 crashes.

## Attach a .c3p

test.zip attached.

## Steps to reproduce

1. Click on a folder (named "f" or "g") and drag it up or downwards.
2.
3.

## Observed result

C3 crash.

## Expected result

Folder moves above or under the folder you did not dragged.

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: do not own

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r124/components/bars/projectBar/projectBar.js, line 1, col 14787
Message: Uncaught ReferenceError: ǃCA is not defined
Stack: ReferenceError: ǃCA is not defined at window.ǃzn.ǃzn.ǃFU (https://editor.construct.net/r124/components/bars/projectBar/projectBar.js:1:14787) at window.ǃzn.ǃzn.ǃdj (https://editor.construct.net/r124/components/bars/projectBar/projectBar.js:1:13752) at Array.ǃWE.ǃW.ǃRe.ǃW.ǃWj.ǃWk (https://editor.construct.net/r124/components/bars/projectBar/projectBar.js:1:3622) at ǃW.Event.ǃSuE.ǃSuU (https://editor.construct.net/r124/main.js:2:204494) at ǃW.ǃS.ǃIr.ǃGl.dispatchEvent (https://editor.construct.net/r124/main.js:2:202637) at ǃW.ǃS.ǃIr.ǃGl.ǃSlB (https://editor.construct.net/r124/main.js:2:442107) at i.ǃSL (https://editor.construct.net/r124/main.js:2:448132) at HTMLDocument.ǃi_.ǃSn (https://editor.construct.net/r124/main.js:2:444519) at HTMLDocument. (https://editor.construct.net/r124/main.js:2:199371)
Construct 3 version: r124
URL: https://editor.construct.net/r124/index.html
Date: Sat Nov 10 2018 23:34:25 GMT+0100 (Midden-Europese standaardtijd)
Uptime: 29.7 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r124 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce in development build, so may already be fixed - let's check when it's out.

**Comment by DiegoScirra** [comment]
This was fixed already.
