### ISSUE TITLE
DrawingCanvas Freezes preview 

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2295]
## Problem description

In certain event case DrawingCanvas will freeze preview and you can see console error. If you rearrange events(put every tick in front of compare time) there is no error. Or when you change time compare to something else then 1, then there is no error.

## Attach a .c3p
[DrawCanvas_Error.zip](https://github.com/Scirra/Construct-3-bugs/files/2569436/DrawCanvas_Error.zip)

## Steps to reproduce

1.Preview example, see freeze and error message in console
2.Rearrange events, put everytick in front of time compare, preview.

## Observed result
Preview freeze and console error

Adding picture, as it might need different time then 1, on different pc.Which could be difficult to find.
![drawingcanvas_consoleerror](https://user-images.githubusercontent.com/28864889/48314191-84de8780-e5ce-11e8-8d49-d13da3665dbc.jpg)

## Expected result
No error

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r124 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 740 mb (5.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SnipG** [comment]
Similar/same console error happens when you got event: every tick paste object. And now you destroy the object you paste.
So overall problem could be: DrawingCanvas error when pasted object is destroyed, but paste event is not disabled.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
