### ISSUE TITLE
Error publishing in App Store from XCode  ITMS-90700 

### ISSUE THREAD

**Issue by MaximMan** [Scirra/Construct-3-bugs#2296]
## Problem description

Error publishing in App Store from XCode  ITMS-90700 

## Attach a .c3p

This is not practical to me. It gets you nowhere since this provides none of my signing certificates and so on. The problem is not the app but the requirements of the Apple App Store. Even if I give you my .c3p, I can't see how you will reproduce the error with the store.

## Steps to reproduce

1) Export via standard C3 service to xCode project - OK
2) Archiving the application in xCode - Ok
3) It remains only to upload, click publish to App Store account, time goes by, BUT at the end there is an error ...  
screenshot - https://yadi.sk/i/uXWuNaduLWRr8Q

## Observed result

error ...  ATMS-90700 Incorrect platform. You included the iOS arm64 executable "MFH.app/MFH" in you iOS bundle. Only iOS executables can be included.

## Expected result

Successful download in App Store

## Affected browsers

* Chrome: yes
* Firefox: yes
* Safari: yes

## System details

XCode 9

///

Note: loading in Google Play is normal.

I wrote on the forum, but they are silent there!

https://www.construct.net/en/forum/construct-3/how-do-i-8/error-when-publishing-xcoda-ap-139131

**Comment by shortercode** [comment]
I can't say I've come across this before, I tried googling around and haven't discovered anything particularly useful. It sounds like your build isn't targeting the correct CPU architecture, or that a precompiled library is missing a required architecture. 

You should ensure that your initial build is set to target "generic iOS device" and that the flag 'Build Active Architecture Only' is set to false and the check your build warnings/errors.

**Comment by MaximMan** [comment]
Creating an application through Unity > xcode does everything perfectly, through Construct > xcode error. Scirra - This is terrible ((((

**Comment by shortercode** [comment]
Without a project to look into here there's probably not much we can do, as you say 

> [...]I can't see how you will reproduce the error with the store[...]

If we cannot reproduce an issue it's very hard to even diagnose the problem, let alone successfully fix it.. I read your comments on including the project and it's true that sharing information about signing keys etc. is impractical, being able to see build settings and included code would likely be the only way to discover what your problem is here though.
