### ISSUE TITLE
Set angle + paste object on DrawingCanvas will freeze preview

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2299]
## Problem description

When setting DrawingCanvas angle and pasting will cause preview freeze and console error. Console error message is same as my issue report #2298 

## Attach a .c3p

[DrawingCanvas_SelfRotateBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2569873/DrawingCanvas_SelfRotateBug.zip)

## Steps to reproduce

1.Preview example, see preview will freeze when sprite touches canvas
2.See console error.

## Observed result
Rotating and pasting object to DrawingCanvas causes error

## Expected result
If pasting and rotating is not allowed - then paste nothing/stop rotating ? OR disable set angle?Or info that thous 2 are not allowed together.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r124 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 740 mb (5.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Drawing Canvas is not supposed to be rotatable. It is extremely complicated to implement all features with a rotated canvas so it's omitted for the time being. Note it has no angle property. The angle actions were included by accident; they've been removed in the next release.

**Comment by SnipG** [comment]
Was testing DrawingCanvas angle stuff from previous release and Well, DrawingCanvas never been rotatable(rotate effect just set height/width). 
The effect it had with set angle, can still  "1:1" replicated with set height/width(ofc this does not bug, like set angle action).
 
So if you test/add the real rotating behavior could it still bug? maybe not?
