### ISSUE TITLE
Crash On Mobile Updated Dialogue "Later" Clicked

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#23]
## Problem description

Updating from r15 to r16 on mobile prompts an updated dialogue to view release notes, but crashed when clicked on "Later". I can't reproduce as my C3 on mobile already updated.

## Steps to reproduce

1. Updates C3
2. Press "Later" on the updated dialogue.

## Observed result

Crashed.

## Expected result

Don't crash and close the updated dialogue prompt.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: [object Event]
Construct 3 version: r16
URL: https://editor.construct.net/
Date: Fri Apr 07 2017 13:30:25 GMT+0800 (MYT)
Uptime: 13.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.42
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Android
Operating system version: 6.0
Operating system architecture: 32-bit
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Linux; Android 6.0; U FEEL Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.42 Mobile Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ARM
Renderer: Mali-T720
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1024
Extensions: EXT_disjoint_timer_query_webgl2, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
r17 is out, is this still a problem?

**Comment by jaydonteh** [comment]
No crash was found on **r18.2**.
