### ISSUE TITLE
When you Click+Del already selected event, it will trow error

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2303]
## Problem description

Having events and you like to delete them. You can select event by mouse and then click delete button, but when you have event already selected and you fast click on it and press delete, Construct trows error and asks for client restart. Ofc who would select already selected event? 
Issue comes when Construct auto select next event, but you also try to select it with mouse and click delete. So its instant error again, and user wouldn't be happy.

I think this is main cause of alot of random errors i have had previously.

## Attach a .c3p

[New project (5).zip](https://github.com/Scirra/Construct-3-bugs/files/2570066/New.project.5.zip)

## Steps to reproduce
1.Open example, go event sheet view
2.Select event by mouse.
3.Now click on selected event first and fast press delete.

## Observed result

Construct editor will trow error and asks for client restart

## Expected result

No restart

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: cannot select detached view
Stack: Error at Function.ǃW.ǃSTR (https://editor.construct.net/r124/main.js:2:142488) at t (https://editor.construct.net/r124/main.js:2:104359) at window.assert (https://editor.construct.net/r124/main.js:2:104762) at window.ǃMR.ǃsv (https://editor.construct.net/r124/components/editors/eventSheetView/eventSheetView.js:1:11784) at window.ǃMR.ǃdX (https://editor.construct.net/r124/components/editors/eventSheetView/eventSheetView.js:1:10159) at window.ǃMR.ǃcn (https://editor.construct.net/r124/components/editors/eventSheetView/eventSheetView.js:1:25242) at window.ǃMR.ǃSh (https://editor.construct.net/r124/components/editors/eventSheetView/eventSheetView.js:1:21281) at HTMLDocument.ǃSK (https://editor.construct.net/r124/components/editors/eventSheetView/eventSheetView.js:1:1910) at HTMLDocument. (https://editor.construct.net/r124/main.js:2:199371)
Construct 3 version: r124
URL: https://editor.construct.net/r124/
Date: Mon Nov 12 2018 02:00:22 GMT+0200 (Eastern European Standard Time)
Uptime: 30.9 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r124 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I'm not clear how to reproduce this. To be clear: you're selecting the entire event, not just an action?

Step 3 seems ambiguous. Are you clicking on the same selected event, or a different one? There is only one event though. Are you really clicking on an action? Is it the same action or a different one? I've tried a few combinations and can't see anything wrong. Please try to be specific and clear.

**Comment by SnipG** [comment]
Oh yeah, i ment action. 
Look picture, 1 event selected. Now click it by mouse and delete button almost together.
![showcase](https://user-images.githubusercontent.com/28864889/48347075-d8f87300-e685-11e8-83f0-ec1eda4e7e39.jpg)

**Comment by AshleyScirra** [comment]
Ah, I think I can reproduce this now. "Do this fast" in bug reports usually means there's a specific sequence that you hit by chance when you do it quickly. I think I can reproduce this with:

1. select the last action
2. mouse down
3. 'del' down
4. mouse up
5. 'del' up

**Comment by AshleyScirra** [comment]
OK, I think I found a fix for this. Thanks for the report, we've been trying to track this one down for a while. Given it's quite fiddly to reproduce let's double check this is working correctly after the next release.

**Comment by AshleyScirra** [comment]
r125 is now out, can you find any way to reproduce it there?

**Comment by SnipG** [comment]
Good job on new release. 
Nope, can't reproduce it anymore.

**Comment by AshleyScirra** [comment]
Thanks for confirming.
