### ISSUE TITLE
Sprite naming -> Autocomplete can interrupt doing math

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#2305]
## Problem description

If there are sprites in the project that have names starting with numbers, autocomplete will insert the object whenever you attempt to type any number. It makes sense but it´s also annoying. Not sure if there is a good way to deal with it other than the obvious: "don´t use numbers in the beginning of sprite names". Maybe not autocomplete if you type math operators?

I only noticed that behavior because I named a sprite "1up"

## Attach a .c3p

[hmm.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2572273/hmm.c3p.zip)

## Steps to reproduce

1. Create any condition/action (e.g. compare two values)
2. Type in some math stuff like 1+1*5

## Observed result

Autocomplete will fill in the objects. It´s also pretty persistent in doing so, makes typing simple math pretty annoying.

## Expected result

Hmm...

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r123 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 150 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is indeed annoying, so I've changed it for the next release so autocomplete is ignored if you've only typed a number so far. So autocompleting `1` does not add an object name, but you can still autocomplete `1s` to get `1sprite`, since there is a non-numeric character typed. There is also an exception if a dot precedes the number, so typing `Sprite.8` can still autocomplete `Sprite.8Direction`. I think this is a reasonable compromise, and is done for the next build.
