### ISSUE TITLE
Maximizing window sometimes does not resize viewport correctly

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2306]
## Problem description

Bug that has been with c3runtime from beginning. Least as far as i can remember. But i still don't have a reliable way to reproduce it. But still happens sometimes pretty often and is very annoying.
When you preview and maximise window or just preview in certain case, the viewport won't be correctly scaled. Resultsing bad alignment of viewport, see pic. Sometimes you can preview 10+times in row without it happening.
How it looks when bugged.
![maxwindowbug](https://user-images.githubusercontent.com/28864889/48364579-68ffe200-e6b1-11e8-8ec6-509732169209.jpg)

How it should be.
![correctscale](https://user-images.githubusercontent.com/28864889/48364654-a2d0e880-e6b1-11e8-91cd-056b1db01c5f.jpg)

## Steps to reproduce
It happens randomly, haven't come up with 100% way to replicate it. But sometimes it can happen 3 out of 5 previews etc.

1.New project. Preview, before you see layout - maximize window
2.For best results,  first scale window small. So when you preview it should start up as very small
3.

## Observed result
Scaling viewport is bugged.

## Expected result
Correct viewport scale every preview or when window is maximized.
Haven't had such issue with c2runtime. 

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r125 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 743 mb (5.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by NetOneGames** [comment]
Yea I've had this a fair few times. Glad you have raised.  I think it is almost impossible to replicate as it is something to do with timing of resizing after preview launch.  It also happens on hosted and nwjs.  I assume at runtime construct checks the window size and then builds the game scaling appropriately. But if you resize the windows in that fraction of a second between when construct checks the window size and then builds and scales the game you get the issue. I'm just speculating but it seems like something like that.

**Comment by AshleyScirra** [comment]
I have never seen this happen. I'm afraid there is almost nothing we can do without steps to reproduce, or at least some kind of hint at what's going on, such as any errors in the browser console.

Does subsequently resizing the window update the canvas size? i.e. is it only the one-off resizing to maximize that does not work?

Are you absolutely sure you are not using fullscreen mode "off" in which case the first screenshot is actually correct? There was no project provided so I cannot verify this.

**Comment by NetOneGames** [comment]
I did try to fid a way to replicate some months ago but no joy.
If you run a big project that takes a while to load.
Then make the preview window pretty small.
Then close the window.
Then when run the preview again
it should start preview at the small size
while that construct loading logo is up at that small size quickly maximise the screen before the game starts.  When the issue occours the game dosent scale to the larg size but stays at the original small window size.
That's generally the sequence of events that trigger it for me.
But cannot repliably replicate and it happens very rearly.
There has been a lot of scaling related issues gone thorugh recently
maybe it has bee picked off by one of those.

**Comment by SnipG** [comment]
There are no errors on console.
Ye its one time bug, resizing again can fix it. 
I most use letterbox scale, so it could be letterbox scale issue. Problem is it has been happing so long. It was litterary first bug i saw when i tried c3runtime when that came out. I tought after time it will get fixed, but instead I have got used to it and just overlook the scale problem, just refresh window when it happens. But it have gotten better overtime, i think there was multiple issues like this at beginning.

Does not happen with c2runtime. 
It happens more often when preview is loading and you maximize window, but also happened when preview is loaded.
Sometimes happens very often - Could be cause Chrome other tabs  have peformance impact/window defender is doing scan...
As noted Ashley pc does not replicate, it is high chance that some checks on weaker pc fail.
It could be chrome issue, when you change tab size, resize does not trigger(some minute ago i tried to replicate but couldent, but changed window width smaller but instead viewport scale it just cut it off).

Its just so random and no way to check errors.
 Maybe it needs some test project, do see how internal checks behave on events like: brower resized etc

**Comment by SnipG** [comment]
Video when replicating this. Time window for it to trigger is pretty small.
[2018-11-13 17-45-45.zip](https://github.com/Scirra/Construct-3-bugs/files/2576944/2018-11-13.17-45-45.zip)

**Comment by NetOneGames** [comment]
ooooo,  nice   you caught it  !

**Comment by AshleyScirra** [comment]
I think this is a kind of race condition where window resize events at certain points during initialisation may be lost. I managed to reproduce it by inserting a couple of seconds wait during initialisation, and resizes during that wait were indeed lost, reproducing the same result. I worked around it by queuing any events until the runtime is ready to handle them, which seems to fix it. Let's check the next release and see if anyone can reproduce any issue once that's out.

**Comment by SnipG** [comment]
Very nice indeed. 
C3 always had longer preview load time then c2 on empty previews(like 30-40% longer) that why problem popped up so often. I tried to reproduce it on c2runtime too but couldnt as it load so fast.

**Comment by AshleyScirra** [comment]
r126 is now out, please check again!

**Comment by SnipG** [comment]
I think this is fixed. I tried few dozen times and couldn't reproduce.

**Comment by AshleyScirra** [comment]
Thanks for confirming.
