### ISSUE TITLE
Some tween easing options are not working correctly. r125

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2308]
## Problem description

Some tween easing options are not working correctly. For example, out back, out bounce etc.

They were fine in r124

in r125 ease out back

![2018-11-13_00-56-20](https://user-images.githubusercontent.com/2965842/48377484-fc9bd780-e6de-11e8-982a-5e16371e8007.gif)

## Attach a .c3p

[tween-bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2573758/tween-bug.zip)

**Comment by DiegoScirra** [comment]
Fixed in the next release.
