### ISSUE TITLE
[r28] Drag & drop multiple images into layout at once bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#231]
## Problem description

So, in C2 you could drag & drop into the layout the entire animation that were split into multiple images and have all of these images as one Sprite object. But in C3 it just creates individual objects for each and every image added.

## Steps to reproduce

1. Drag in multiple images at once into the layout view.

## Observed result

Creates an object for each individual images dragged in.

## Expected result

Put all dragged in images as frames of an animation under a single Sprite object just like in C2.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
C3 release: r28

Local storage
Storage quota (approx): 3 gb
Storage usage (approx): 364 mb (12%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by mfoster98** [comment]
Could possibly be a new change rather than a bug maybe?  I'm getting this too.

**Comment by DiegoScirra** [comment]
This sounds like a missing feature. @AshleyScirra ?

**Comment by AshleyScirra** [comment]
Yep, looks like an oversight.

**Comment by shortercode** [comment]
Yeah when I implemented this I wasn't aware of the behaviour in C2, I was more thinking along the lines of dragging a set of assets in from a folder.

**Comment by mfoster98** [comment]
That could be cool, then there's an option in there

**Comment by AshleyScirra** [comment]
Updated for r29.
