### ISSUE TITLE
Spritefont [C2Runtime] different from the [Construct 3 Editor] and [C3Runtime]

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#2312]
## Problem description

There is a difference in **SpriteFont** preview with the **c2runtime** and the **C3Editor** and **C3Runtime**.

## Attach a .c3p

I have sent you a personal email. Because, the **SpriteFont** is mine and I don't want it lying on public.
It is called **Spritefont_Bug.c3p**.
The email and .c3p has a reference to this post.

## Steps to reproduce

1. Observe the **SpriteFont** on the editor.
2. Preview on **C2Runtime** and observe. 
3. Preview on **C3Runtime** and observe.

## Observed result

**C2Runtime :: Spritefont** preview is different from the **C3Editor** and **C3Runtime**.

## Expected result

The **C2Runtime :: Spritefont** preview to be the same with the **C3Editor** and **C3Runtime**.
The **C2Runtime preview of the spritefont** should be the right preview. Because that's how it works on **Construct 2**. 
I would know because I upgraded a project from Construct 2 to Construct 3 and saw this happened for a long time but I thought it would get fixed anyway without reporting. But it didn't, so I thought I have to really report. **Besides, C3Runtime working well is important.**

## System details

**Construct 3 :: r125**

**Comment by AshleyScirra** [comment]
I'm confused by the project - where does the "Username" text come from? There are no events and it's not in the initial text of the object...

**Comment by AshleyScirra** [comment]
After a bit of initial confusion... figured out an issue with calculating space character widths, and should be fixed in the next release. Thanks for the report.
