### ISSUE TITLE
Scaling browser window while doing snapshot of Drawing Canvas clears Drawing Canvas

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#2315]
## Problem description

Scaling browser window while doing snapshot of Drawing Canvas clears Drawing Canvas

## Attach a .c3p

[DrawingCanvasResizeBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2582724/DrawingCanvasResizeBug.c3p.zip)

## Steps to reproduce

1. Run project
2. Rescale browser window (i.e. drag window size up and down)
3. Drawing canvas clears

## Observed result

After snapshot while resizing, Drawing Canvas clears

## Expected result

Drawing Canvas not to clear.

## Affected browsers

* Chrome: yes

## System details

MacOS 10

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
