### ISSUE TITLE
Music & sounds not playing on iOS even after user's interaction

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2318]
## Problem description

I'm trying to make music & sound play "in the background" on an application targeting iOS.
I'm aware of the autoplay limitations, and so I'm trying to have the "audio engine" start to play after a user's touch on a button (an actual DOM button).

It does not seem to work, no sound is coming through.

I have another application, which is using a kind of similar logic, sound is not coming through at first, but in later layouts, audio fx start playing, although I still cannot get my background music to play as I intend it to.

## Attach a .c3p

https://kyatric.com/c3/bugs/2018.11.15.test_son_ios.c3p

## Steps to reproduce

1. Preview
2. Try to click "Play music" or "Play audio"
3. alternatively, you can click  "Next layout" and click "Play music" there

## Observed result

On my iPad, whether you click in the first layout or go to the next layout and click the buttons there, no sound is playing at all.

## Expected result

Sound & music to play.

## Affected browsers

* Safari: yes

Perhaps I'm doing something wrong in my logic.
The frustrating part is that on Android and desktop Browser, this code works as intended.

**Comment by shortercode** [comment]
Can you provide the platform details for the iOS please? I can't remember the Safari version off the top of my head, but a browser bug prevents the audio decoder from being started.

**Comment by Kyatric** [comment]
My iPad runs iOS 11.4 at this moment.

**Comment by AshleyScirra** [comment]
iOS 11 has bugs that prevent the WebAssembly opus decoder working. We can't work around them. Apple fixed them for iOS 12, so that's all we can support for audio playback on iOS I'm afraid.

**Comment by Kyatric** [comment]
Thanks, the issue is indeed fixed in iOS 12.
I still have audio issue on my other project, even in iOS 12 so I'll have to investigate further in where it may be coming from. 

It is still confusing as background music is not playing from the start of the app and UI sounds like "buttons" are not playing either, nevertheless, when you play some of the mini-games, the sound for those is playing as intended...
