### ISSUE TITLE
Parameter title is wrong for position tween. r125

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2319]
## Problem description

It says End X / End Y. It should be End Width / End Height.

![image](https://user-images.githubusercontent.com/2965842/48551630-1f004180-e8e7-11e8-9158-5b13a1b2e022.png)

**Comment by AshleyScirra** [comment]
The labels are correct for a "position" tween. We currently have no mechanism for changing labels based on a combo parameter (to change the labels when switching to "size"). This would be potentially a lot of architecture work for a minor issue, and arguably the labels are not misleading anyway if you consider them referring to the X and Y axes.
