### ISSUE TITLE
[r28] Rename family crash

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#232]
## Problem description

You can't rename families because it will crash.

## Steps to reproduce

1. Create a family.
2. Rename the family.

## Observed result

Crashed.

## Expected result
No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃK.ǃn (https://editor.construct.net/r28/main.js:2:201552) at le.ǃBC (https://editor.construct.net/r28/main.js:61:236452) at ǃBC.next () at window.ǃjr.ǃjJ (https://editor.construct.net/r28/components/bars/zOrderBar/zOrderBar.js:1:13156) at Array.ǃjm.k (https://editor.construct.net/r28/components/bars/zOrderBar/zOrderBar.js:1:1229) at ǃK.Event.ǃH_b.ǃH_c (https://editor.construct.net/r28/main.js:2:285323) at window.ǃTfg.dispatchEvent (https://editor.construct.net/r28/main.js:2:283715) at window.ǃTfg.ǃKyt (https://editor.construct.net/r28/main.js:162:39640) at ee.ǃTo (https://editor.construct.net/r28/main.js:61:151927) at ee.ǃKR (https://editor.construct.net/r28/main.js:61:152428)
Stack: TypeError: unexpected type at Function.ǃK.ǃn (https://editor.construct.net/r28/main.js:2:201552) at le.ǃBC (https://editor.construct.net/r28/main.js:61:236452) at ǃBC.next () at window.ǃjr.ǃjJ (https://editor.construct.net/r28/components/bars/zOrderBar/zOrderBar.js:1:13156) at Array.ǃjm.k (https://editor.construct.net/r28/components/bars/zOrderBar/zOrderBar.js:1:1229) at ǃK.Event.ǃH_b.ǃH_c (https://editor.construct.net/r28/main.js:2:285323) at window.ǃTfg.dispatchEvent (https://editor.construct.net/r28/main.js:2:283715) at window.ǃTfg.ǃKyt (https://editor.construct.net/r28/main.js:162:39640) at ee.ǃTo (https://editor.construct.net/r28/main.js:61:151927) at ee.ǃKR (https://editor.construct.net/r28/main.js:61:152428)
Construct 3 version: r28
URL: https://editor.construct.net/index.html
Date: Wed May 17 2017 20:49:27 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 229.3 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
C3 release: r28

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by mfoster98** [comment]
Staff please note, this doesn't occur when I tried to reproduce.  Maybe add more info?

**Comment by jaydonteh** [comment]
**UPDATE:**

@mfoster98 I had my Z order opened which caused the crash when renaming a family. It is specified on the crash log but good to emphasise here.

**Comment by mfoster98** [comment]
Can confirm this bug now happens with the Z Order bar displayed.

**Comment by DiegoScirra** [comment]
Fixed in r29

**Comment by jaydonteh** [comment]
Go! Diego go! 💓

**Comment by mfoster98** [comment]
ayy!
