### ISSUE TITLE
Expressions dictionary issues

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#2322]
There are two minor issues with the expressions dictionary:

1. Objects with no expressions are still listed. E.g. the "Share" plugin has no expressions, so should not appear in the expressions dictionary. If you do choose it, the dialog is left showing a "Loading..." screen.

2. Objects with no instance variables still create an empty "Instance variables" group in their expression list. The group should be omitted if there are no instance variables to show. E.g. add a Text object and view it in the expressions dictionary; it has an empty "Instance variables" group.

**Comment by DiegoScirra** [comment]
Fixed.
