### ISSUE TITLE
"Add" button in event sheets is not clickable on mobile in horizontal orientation

### ISSUE THREAD

**Issue by Gonusi** [Scirra/Construct-3-bugs#2323]
## Problem description

The "Add" link in event sheets (not the "Add event") does nothing if touched while in horizontal orientation. The horizontal orientation is very useful to view the events without them wrapping, but unusable due to this issue. 

## Affected browsers

* Chrome: yes

## System details

Xiaomi Redmi Note 5, Android 8.1, Chrome.

**Comment by AshleyScirra** [comment]
It looks like they're conflicting with the right swipe-in hit region for the bars. I've moved them further over to the left for the next release which should avoid this.
