### ISSUE TITLE
R135 - Instances not getting created if not on layout 

### ISSUE THREAD

**Issue by SantiagoEstrade** [Scirra/Construct-3-bugs#2325]
## Problem description

R125 is supposed to have evolved by not having to create an 'assets' layout to add a first instance of every sprite for referencing at creation. I have just tried deleting that layout, so there are no instances on any layout.

Game crashes as for previous versions.

## Example

https://1drv.ms/u/s!AojCIgmN1VlPiXHgVYT1aGqqT9-6

## Steps to reproduce

1. Prev and see there is a tilemap and some chess
2. Just delete Assets layout and prev

## Observed result

Blank screen

## Expected result

Instances should be showing up at creation by referencing to their object's default values

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: ?
* Safari: yes

## System details

Platform information
Browser: Chrome
Browser version: 70.0.3538.80
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Android
Operating system version: 8.0.0
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2.625
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 8.0.0; SM-G965F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.80 Mobile Safari/537.36
C3 release: r125 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 3.5 gb
Storage usage (approx): 34 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2 is currently disabled on Android due to reports of GPU driver bugs.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: ARM
Renderer: Mali-G72
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1024
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_sRGB
OES_element_index_uint
OES_standard_derivatives
OES_vertex_array_object
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The project uses a third-party addon (MoveTo). I'm afraid we cannot support such cases, please see the bug report guidelines.
