### ISSUE TITLE
Tween resume is not working. r125

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2326]
## Problem description

tween resume is not working. r125

## Steps to reproduce

1. Pause a tween.
2. Try to resume it.

![image](https://user-images.githubusercontent.com/2965842/48653104-f6299a80-ea13-11e8-97e8-3254548b5de6.png)

## Observed result

It won't resume.

## Expected result

It should resume the tween.

**Comment by DiegoScirra** [comment]
Fixed in the next release
