### ISSUE TITLE
(c3 runtime) Music and Video don't play on iOS 12.1

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#2329]
## Problem description

Video-play and Music-play don't work on my iPhone with iOS 12.1 in the Safari Browser.

## Attach a .c3p

[Example File](https://drive.google.com/open?id=16yO4SPdYtL-x7jaOgeo_CJ3lQaYK4tGr)

## Steps to reproduce

1. Open the example-file
2. Test/Start Layout "test_video" on iPhone

## Observed result

The Video don't play and the music, too. (Sounds play perfectly, only music don't play)

## Expected result

Music and Video play without problems.

## Affected browsers

* Safari: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r125 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 45 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a bug in iOS: it never fires the "canplay" event for the MP3 audio, so it never considers it to have loaded. You could report it to Apple, but I think the easiest solution is to transcode audio to WebM Opus, which is our recommended format. iOS does not directly support WebM Opus, but we use a WebAssembly decoder for it, so it doesn't depend on the system decoder.

Safari does not support WebM video formats, so that aspect is not a bug. You need to transcode your video to a format iOS supports (i.e. MPEG-4). Due to the complexity, performance and patent issues around video codecs, we do not have a WebAssembly decoder for it.
