### ISSUE TITLE
Visual bug of Sprites

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#233]
## Problem description

Sometimes, when I work on a sprite in the animations Editor, and I close it, other sprites in the layout take the visual of the last sprite i have working on. The size change too.
It's not just a visual bug, because the size change too. But when I restart Construct 3, the images are good again but the size has changed.
My Sprites are resized with Xscale and Ycale.

## Steps to reproduce

1. Create many different Sprites
2. Work on a sprite (import frames from files), create animations
3. Close the animations editor

## Observed result

Sometimes, other sprites take the visual of the last edited sprites and changes size
(it happens 3 times for me today)

## Affected browsers

* Chrome: yes/  Zoom of the browser : 100%

**Comment by AshleyScirra** [comment]
Can you provide more specific steps to reproduce? We need to be able to follow these steps to repeat what you're doing.

**Comment by Picoti** [comment]
OK I think I have found the bug.  But the bug is only on my project.
[TEST_BUG.zip](https://github.com/Scirra/Construct-3-bugs/files/1008230/TEST_BUG.zip)


1. OPen my project
2. Double clic on the sprite named "Maxi"
3. Delete the "Renait" animation
4. Duplicate "Appear" animation
5 Rename this new animation as "Renait"
6 Close the Animations editor

Now all the sprites have the same image.

**Comment by DiegoScirra** [comment]
Fixed in r29.

Thanks for help.
