### ISSUE TITLE
Touch Issue ?

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2330]
## Problem description

This may not be a bug, maybe I am misunderstanding something 
it appears that it should be so simple but  the logic is not working correctly 

I am trying to assess exactly which touch is touching a button to remove some bugs with touch in my game.

shouldnt this event transfer the ID of the specific touch touching the button to the button instance variable ?

![image](https://user-images.githubusercontent.com/21962641/48664248-a1c5ff80-ea93-11e8-9bdd-8c30ce84cb08.png)

## Attach a .c3p

[TouchTest02 (5).zip](https://github.com/Scirra/Construct-3-bugs/files/2592092/TouchTest02.5.zip)

##  First Test

1.  Run preview
2. Using only one finger. Touch somewhere on screen not on a button
3. Without removing finger from screen move finger to buttons in sequence
4. The button should record the ID of the touch that touched it

## Observed result

The button appears to correctly record the ID of the touch that touched it

## Expected result

OK, expected result

##  Second Test

1.  Run preview
2. Using only one finger. Touch somewhere on screen but not on a button
3. Without removing first finger from screen add another or more touches in sequence do not touch the buttons
4.  Now without removing any touches move the first touch finger to any of the buttons
5. The button should record the ID of the touch that touched it

## Observed result

The button records the ID of the latest touch NOT the touch that is touching it.

## Expected result

the events clearly want to transfer the touch ID of the  touch touching the button to the  button instance variable

but instead the latest created touch ID is transferred ,
 
that touch ID may not even be touching the box so why is the ID transferred to the box ?

although construct can clearly track and maintain the ID of each multi touch 

it thus appears impossible to assess exactly which touch in a multi-touch situation is touching an object

in this multi touch situation I want to know exactly which touch ID is touching the box

**the event should only pick the touch that is touching the box and transfer that ID to the box**

or am I being thick?

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r125 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 13 gb (80.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by tunepunk** [comment]
You probalby have to use "on touched", otherwize the LastTouchedBy_ID will be updated with the second touch. Had similar problems... The Touch.TouchID seems to always be the latest TouchID number, no matter where you touch, or how many touch points.

**Comment by AshleyScirra** [comment]
"Is touching object" does not set the value of the TouchID expression. This is because there can be multiple touches on the object that make "Is touching object" true, so it doesn't attempt to tell you which one was responsible. Your events assume it is set though so they won't work. However the trigger "On touched object" does set the TouchID expression, since it knows which specific touch is responsible for firing the trigger. You should probably adjust your events to use that instead.

**Comment by NetOneGames** [comment]
Ok I see, that makes sense, i should have realised, sorry for raising.
"you think Im not stupid but I am" as my uncle once said by accident!
thanks tunepunk
thanks Ashley

**Comment by NetOneGames** [comment]
No, no, no 
this dosent work
"On touched object"
is only triggered when a touch starts  not when object is touched
if the touch is already touching then there is no trigger if that touch touches the object
:((((( so I back to square one.   unless I do something with invisible sprites then I cannot test which touch touches an object (if the touch is already touching)

Isn't this an oversight for this trigger....  ????

**Comment by tunepunk** [comment]
Create a forum thread and explain what you're trying to do and i will help there, so we don't spam the bug tracker.

**Comment by NetOneGames** [comment]
thanks man I will try to get something up during the week.  
 Basically if a button is activated by a particular touch im trying to track if that touch goes off and back on to that particular button it reactivate it only if the same touch is touching it and not another touch. I think I could do it with sticking invisible sprites to the individual touches but seems not possible using built in touch actions. anyway yea will hit the forums hopefully tomorrow. cheers
