### ISSUE TITLE
System Pick causes low fps in some edge case

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2333]
## Problem description

Having no moving sprites and you use System pick by comparison, and you compare object.X against some value,it will cause low fps. While comparing object.X against same value does not.
So system pick causes fps drop, while you have moving sprite fps will be even lower(so its not pure fill rate test). So its some strange case, that should be looked into. 
Could be similar to my other bug report where webgl had some issues with physic and saw sprites still moving, while they didn't.
Both runtimes affected

## Attach a .c3p
[SystemPick_Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2592431/SystemPick_Bug.zip)

## Steps to reproduce

1.Preview example, see low fps when object count(70k) is reached. 
2.Disable system pick sprite and enable  sprite.X = -100
3.Preview and see high fps(~60) when  sprite spawning stops.

If you have better PC, increase object count&spawning speed.

## Observed result
System pick causes something to refresh, which will drag fps down, when no sprite is moving.
While object own compare does not.
Both system pick and object compare have similar cpu usage so its strange case.
I had 30 fps at 70k sprites with system pick, while 60fps with object.x compare.
I also tried system pick by evaluation, similar results with fps drop.

## Expected result
No fps drop with system pick, if it comes from some bug.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r125 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 775 mb (5.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The system "pick by comparison" condition is a more general-purpose condition, so is slower than a specific "compare X" condition. (Notably "pick by comparison" evaluates two expressions, but "compare X" evaluates one.) I don't see why this is a problem, it's to be expected in software that more general features are slower than specific ones.
