### ISSUE TITLE
Spritefont Spacing Data Issue - r125

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#2337]
## Problem description

When you paste spacing data in editor. It is remove this char " **\\** "

**Try this spacing data**
> [[7," "],[6,"'"],[8,"Iil!|"],[9,"j1.,;:-`"],[10,"\"()[]"],[11,"Jft\\\°"],[12,"rz?*"],[13,"acdehqsvxy57/=<>"],[14,"Lbgknopu023689~+€"],[15,"CEFXZ4_#$"],[16,"ABDGHKNPQRSTUVY£"],[17,"Ow"],[18,"%"],[19,"MWm@"],[20,"&"]]

## Steps to reproduce

Look gif please. (Open in new tab for quality)

![bug](https://user-images.githubusercontent.com/13033837/48674422-11ec8800-eb5d-11e8-958b-aa04caa9235c.gif)

## Observed result

> [11,"Jft\°"]

## Expected result

> [11,"Jft\\\°"]

**Comment by AshleyScirra** [comment]
Please attach a project as per the bug report guidelines.

`\` is escaped in the text field so you can use special values like `\n` for a newline. However there is no need for this in the text dialog since it can display newlines. So this appears to be intentional.

**Comment by QuasarX** [comment]
@AshleyScirra  I think you don't understand what I said.
**It is not for newline.** I just use SpriteFont plugins **spacing data**, when I paste it in editor it is removing this char "\\"
Just try to paste this in editor with spritefont plugin.

> [[7," "],[6,"'"],[8,"Iil!|"],[9,"j1.,;:-`"],[10,""()[]"],[11,"Jft\\\°"],[12,"rz?*"],[13,"acdehqsvxy57/=<>"],[14,"Lbgknopu023689~+€"],[15,"CEFXZ4_#$"],[16,"ABDGHKNPQRSTUVY£"],[17,"Ow"],[18,"%"],[19,"MWm@"],[20,"&"]]

Observed result
> [[7," "],[6,"'"],[8,"Iil!|"],[9,"j1.,;:-`"],[10,""()[]"],[11,"Jft\\°"],[12,"rz?*"],[13,"acdehqsvxy57/=<>"],[14,"Lbgknopu023689~+€"],[15,"CEFXZ4_#$"],[16,"ABDGHKNPQRSTUVY£"],[17,"Ow"],[18,"%"],[19,"MWm@"],[20,"&"]]

Expected result
> [[7," "],[6,"'"],[8,"Iil!|"],[9,"j1.,;:-`"],[10,""()[]"],[11,"Jft\\\°"],[12,"rz?*"],[13,"acdehqsvxy57/=<>"],[14,"Lbgknopu023689~+€"],[15,"CEFXZ4_#$"],[16,"ABDGHKNPQRSTUVY£"],[17,"Ow"],[18,"%"],[19,"MWm@"],[20,"&"]]

Did you see that difference?

**Comment by AshleyScirra** [comment]
Yes, and that is the escaping feature I described working as intended.

**Comment by QuasarX** [comment]
This should be fixed? It is really bug. Just look this gif. If you want project file it is here too. This breaking spacing feature SpriteFont's
[SF Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2595169/SF.Bug.zip)

![bug](https://user-images.githubusercontent.com/13033837/48705896-91389500-ec0b-11e8-9200-eee18a9d25ff.gif)

**Comment by AshleyScirra** [comment]
I don't see what the problem is, especially since using `\\` in spritefont spacing data has no effect, because you can only set the width for the character once. Specifying it twice is redundant. So even if you get the escaping wrong, it has no effect.

**Comment by QuasarX** [comment]
@AshleyScirra  I hope this better explain what's difference.
**NOTE:** I paste totally same data

1. ) When you paste text in this area it is removing this char "\\"
![3](https://user-images.githubusercontent.com/13033837/48706447-5cc5d880-ec0d-11e8-986b-6fb9a4504f6d.PNG)

Result (Broken spacing data)
![1](https://user-images.githubusercontent.com/13033837/48706503-8aab1d00-ec0d-11e8-898f-1c1f0c2e66ea.PNG)

But When you paste text in this area this is works fine. Don't removing anythink.
![4](https://user-images.githubusercontent.com/13033837/48706462-6b13f480-ec0d-11e8-8c38-0948b39da7a9.PNG)

Result (Works fine)
![2](https://user-images.githubusercontent.com/13033837/48706528-9ac2fc80-ec0d-11e8-9b00-07e0f5115899.PNG)

You can se Results not same.

**Comment by QuasarX** [comment]
![aa](https://user-images.githubusercontent.com/13033837/48706812-6bf95600-ec0e-11e8-9ae2-28e01926b92f.PNG)
![bb](https://user-images.githubusercontent.com/13033837/48706813-6bf95600-ec0e-11e8-84d6-067715ac86e8.PNG)
You can see difference with big images.

**Comment by AshleyScirra** [comment]
Yes, the escaping feature is replacing the double-backslash. You can paste it in to the text dialog instead to bypass escaping.
