### ISSUE TITLE
Mobile Advert Using Old version Cordova Plugin -r125

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#2338]
## Problem description

It is using this and this version broken.
`<plugin name="construct-mobile-advert" spec="1.2.5" />`

## Steps to reproduce

1. Add Mobile Advert plugin your project
2. Export
3. Look in config.xml

## Observed result

`<plugin name="construct-mobile-advert" spec="1.2.5" />`

## Expected result

`<plugin name="construct-mobile-advert" spec="1.2.6" />`

### NOTE!

When you click ### Download [Project name], it should be return file name in ### Windows dialog.

C3 Export Dialog
![1](https://user-images.githubusercontent.com/13033837/48699338-49f5d880-ebfa-11e8-9c8c-0fb81c26e3b4.PNG)

Windows Dialog (for save file)
![222](https://user-images.githubusercontent.com/13033837/48699342-4b270580-ebfa-11e8-9a1d-d0dacb7a0bf3.png)

**Comment by shortercode** [comment]
Ah well noticed. The build service automatically upgrades to the latest whitelisted maintenance version, so this wouldn't have effected it. I'll update the entry in the plugin so that it includes the latest version.

**Comment by shortercode** [comment]
Should be fixed in the next release.
