### ISSUE TITLE
Tilemap - Editor Crash

### ISSUE THREAD

**Issue by adamprack** [Scirra/Construct-3-bugs#234]
## Problem description

When changing the tile size of a filled tilemap to 128 (or possibly other numbers), pressing tab to go to the next input box in the Properties panel causes a full crash.

## Attach a .c3p

[https://drive.google.com/open?id=0B4Cyki0BEAFdVmxueU41SmxUVHM](https://drive.google.com/open?id=0B4Cyki0BEAFdVmxueU41SmxUVHM)

## Steps to reproduce

1. Start a new project
2. Insert a tilemap
3. Fill the tilemap with any tile
4. Lock the current layer (the layer the tilemap is on)
5. If necessary, re-select the tilemap from the project bar
6. In the Properties pane, manually type 128 into the Tile width space.

From the provided .c3p, simply follow steps 5 and 6. 

## Observed result

Construct 3 crashes.

## Expected result

The tilemap object should increase the tile dimensions.

## Affected browsers

* Chrome: Yes
* Firefox: n/a
* Edge: n/a
* Safari: n/a

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r28/main.js, line 2, col 199515
Message: Uncaught TypeError: expected finite number
Stack: TypeError: expected finite number at Function.ǃK.ǃKx (https://editor.construct.net/r28/main.js:2:199521) at c.ǃTG.ǃHul (https://editor.construct.net/r28/plugins/tilemap/plugin.js:1:4016) at c.ǃTG.ǃHrU (https://editor.construct.net/r28/plugins/tilemap/plugin.js:1:3803) at c.ǃTG.ǃHrf (https://editor.construct.net/r28/plugins/tilemap/plugin.js:1:3196) at c.ǃTF.ǃlt (https://editor.construct.net/r28/plugins/tilemap/plugin.js:1:6571) at ne.ǃlq (https://editor.construct.net/r28/main.js:61:207437) at s.ǃGY (https://editor.construct.net/r28/components/bars/propertiesBar/propertiesBar.js:1:27964) at ǃK.ǃZ.ǃu.ǃbQ.ǃKoz (https://editor.construct.net/r28/main.js:2:477944) at ǃK.ǃZ.ǃu.ǃKoK.ǃKoP (https://editor.construct.net/r28/main.js:2:443214) at ǃK.ǃZ.ǃu.ǃKoK.ǃrS (https://editor.construct.net/r28/main.js:2:450090)
Construct 3 version: r28
URL: https://editor.construct.net/index.html
Date: Wed May 17 2017 12:07:47 GMT-0400 (Eastern Daylight Time)
Uptime: 19.1 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.96
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36
C3 release: r28

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 640 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
While I was looking at this bug I came across a different, but related bug. I fixed that one, and now I can't reproduce this one.

I think I fixed this, but I am not sure :P

Please check the next release r29 to see if this is still happening. Thanks for the report.

**Comment by adamprack** [comment]
Cool. Yeah, I could make it crash a few different ways, but that one was a sure-fire way to do it. I'll be sure to check and let you know!

**Comment by AshleyScirra** [comment]
r29 is now out, please check again!

**Comment by adamprack** [comment]
This particular issue seems fixed!
