### ISSUE TITLE
Launch Error in 94.2 version construct 3 in chrome

### ISSUE THREAD

**Issue by LokeshKanumoori** [Scirra/Construct-3-bugs#2341]
When I open the construct3 tool, the tool is asking to restart. Even after I restarted it, it is asking the same continuously.
When I open the same version of construct3 in incognito mode from chrome browser, it is working fine.
I don't know why it is giving an error every time in chrome (In normal mode means Not in incognito).

Affected browsers
Chrome: yes/no

I don't know about the other browsers as I'm using chrome.

System details

Error report information
Type: unhandled rejection
Reason: Error: The prompt() method must be called with a user gesture
Construct 3 version: r94.2
URL: https://editor.construct.net/r94-2/
Date: Mon Nov 19 2018 14:51:47 GMT+0530 (India Standard Time)
Uptime: 5 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.77
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
C3 release: r94.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
This is an old version. Please just use a newer version.

**Comment by LokeshKanumoori** [comment]
my requirement is 94.2 version only.

**Comment by AshleyScirra** [comment]
Why?
