### ISSUE TITLE
Debugger inspect tab Flickering in Firefox

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2342]
## Problem description

As per description. Inspect tab is flickering in firefox. and causes performance issues.

## Attach a .c3p

N/A any project will do.

## Steps to reproduce

1. open any project.
2. run preview with debugger in firefox
3. notice inspect tab flickering.

## Observed result

Data in inpect tab flickering, which also causes performance issues.

## Expected result

Should not flicker

## Affected browsers

* Chrome: no
* Firefox: yes
* Edge: not tested
* Safari: not tested

**Comment by tunepunk** [comment]
https://www.dropbox.com/s/msrfbt849lseoah/New%20project%20%28C3%20runtime%29%20-%20Mozilla%20Firefox%2019_11_2018%2019_57_37.mp4?dl=1

looks like this here. Maybe only when previewing in new window?

**Comment by tunepunk** [comment]
Seems to happen for me in all debug modes as long as the window is big enough to produce columns.

**Comment by tunepunk** [comment]
Tested in Firefox on mac as well and didn't have the same problem with the flickering.. Although the Preview performance was very dependant on the size of the window, while in the inspect tab. Larger window... very laggy.. smaller window more smooth..

**Comment by tunepunk** [comment]
Uninstalling and reinstalling Firefox solved the flickering issue. But the performance while in inspect tab is still terrible. I think this issue is detailing that problem. 

https://github.com/Scirra/Construct-3-bugs/issues/1981

**Comment by AshleyScirra** [comment]
OK, closing and will follow up in #1981. Think we will need to rewrite the debugger styling which is frustrating...
