### ISSUE TITLE
Crash when I opened project

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#2343]
## Problem description

Opened my project, I didn´t do much except checking the eventsheet to find where I left off. Opened fine the second time. The project was indeed supposed to open up the text editor (I left a .txt file with some notes open) but that obviously didn´t happen.

## Attach a .c3p

Don´t think it will help, if you really want I can send you the c3p (don´t wanna put it public)

## Steps to reproduce

?

## Observed result

Crash

## Expected result

No crash

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Unable to setup text editor @ Error: Unable to setup text editor at a.then.catch (https://editor.construct.net/r126/components/editors/textEditor/textEditor.js:1:4028)
Stack: Error: Unable to setup text editor at a.then.catch (https://editor.construct.net/r126/components/editors/textEditor/textEditor.js:1:4028)
Construct 3 version: r126
URL: https://editor.construct.net/r126/
Date: Mon Nov 19 2018 18:55:55 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 56.9 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r126 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Hmm yeah I'm not really sure where to go with this. I tried a few ideas out and can't break it. I can tidy some stuff up around here, so that it won't crash any more, but it may not be able to load the text editor component.

If you find a surefire way of doing this, which might involve a specific project, then let me know!

**Comment by shortercode** [comment]
I've done some cleanup of the lazy loading code for the text editor, it shouldn't crash anymore. It's supposed to display a "attempt reload" button and an error message but it had been broken at some point, it happens so rarely that it hadn't been noticed. Going to close this issue, if you find a situation where the text editor fails to load for some reason please file an issue for me to look into it.
