### ISSUE TITLE
Image Editor: cropping image offsets colision polygon by -1/-1

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2347]
## Problem description

cropping an image in the image editor changes collision polygon positions by -1,-1.

I'm guessing this bug is because the collision polygon is changed when cropping, then after the crop the image is then cropped/expanded a second time to add a 1 pixel transparent border, however the polygon is not updated with the second iteration.

![image](https://user-images.githubusercontent.com/5744908/48753295-95cf7d00-ece1-11e8-9b8c-2627acde795b.png)

## Attach a .c3p

[crop.zip](https://github.com/Scirra/Construct-3-bugs/files/2598182/crop.zip)

## Steps to reproduce

1. crop image

## Observed result

polygon changes position

## Expected result

stay the same

## Affected browsers

yes

## System details

<details><summary>View details</summary>

nope

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release
