### ISSUE TITLE
r126 crashes when trying to find expressions for AdvancedRandom plugin

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#2348]
## Problem description

Program crashes when you click "Find Expressions" and select Advanced Random.

## Attach a .c3p

Not required.

## Steps to reproduce

1. Add Advanced Random plugin to a project.
2. Add any event/action, in expression editor window click "Find expressions" and then click Advanced Random.

## Observed result

Program crashes.

## Expected result

Should not crash.

## Affected browsers

* Chrome: yes
* Desktop build: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r126/main.js, line 81, col 166338
Message: Uncaught Error: instance variables not supported
Stack: Error: instance variables not supported at r.ǃgJ (https://editor.construct.net/r126/main.js:81:166344) at ǃgJ.next () at ǃq.ǃ_.ǃSN.ǃoir.ǃoin (https://editor.construct.net/r126/main.js:177:55671) at ǃq.ǃ_.ǃSN.ǃoir.ǃD$ (https://editor.construct.net/r126/main.js:177:59337) at Array.ǃqQp.addEventListener (https://editor.construct.net/r126/main.js:177:51909) at ǃq.Event.ǃrYL.ǃrYT (https://editor.construct.net/r126/main.js:2:204643) at ǃq.ǃ_.ǃSN.ǃqoP.dispatchEvent (https://editor.construct.net/r126/main.js:2:202682) at ǃq.ǃ_.ǃSN.ǃqoP.ǃqqg (https://editor.construct.net/r126/main.js:2:464879) at HTMLElement.ǃfI (https://editor.construct.net/r126/main.js:2:468820) at HTMLDocument. (https://editor.construct.net/r126/main.js:2:199416)
Construct 3 version: r126
URL: https://editor.construct.net/r126/
Date: Tue Nov 20 2018 19:45:21 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 102.3 s

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r126 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release.
