### ISSUE TITLE
Importing Tilemap on locked layer

### ISSUE THREAD

**Issue by David-Cheal** [Scirra/Construct-3-bugs#235]
## Problem description

When editting the tilemap that is on a locked layer it will crash this can be avoided by unlocking the layer doing the changed then relocking.

## Attach a .c3p

[BugTilemap.zip](https://github.com/Scirra/Construct-3-bugs/files/1008365/BugTilemap.zip)

## Steps to reproduce

1. Create a tilemap
2. Paint some tiles
3. Add the tilemap to its own layer and lock that layer
4. Make a change
5. Click anywhere on the layout
6. Crash

## Observed result

After applying the changes the tilemap doesn't update, on clicking the tilemap in the layout it wil crash.

## Expected result

Tilemap to apply new changes and update accordingly. 

## Affected browsers

Opera V44 Yes 

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃca' of null @ TypeError: Cannot read property 'ǃca' of null at ǃCy.ǃls.ǃYD.ǃYD.then.u (https://editor.construct.net/r28/components/bars/tilemapBar/tilemapBar.js:1:3483)
Stack: TypeError: Cannot read property 'ǃca' of null at ǃCy.ǃls.ǃYD.ǃYD.then.u (https://editor.construct.net/r28/components/bars/tilemapBar/tilemapBar.js:1:3483)
Construct 3 version: r28
URL: https://editor.construct.net/
Date: Wed May 17 2017 17:02:22 GMT+0100 (GMT Summer Time)
Uptime: 224.9 s

Platform information
Browser: Opera
Browser version: 44.0.2510.857
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36 OPR/44.0.2510.857
C3 release: r28

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r29.
