### ISSUE TITLE
Crash on app close

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2350]
## Problem description

The app shows a crash reports when closing the desktop app.

## Attach a .c3p

n/a

## Steps to reproduce

I wasn't able to determine a precise reason this happens, just that it triggers from closing the app

## Observed result

A crash report

## Expected result

The app should close

## Affected browsers

Desktop

## System details

Error report below

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property '0' of undefined @ TypeError: Cannot read property '0' of undefined at Object. (extensions::nw.Window:145:118) at Object.handleRequest (extensions::binding:64:27) at Object. (extensions::binding:377:32) at NWWindow.get (extensions::nw.Window:592:40)
Stack: TypeError: Cannot read property '0' of undefined at Object. (extensions::nw.Window:145:118) at Object.handleRequest (extensions::binding:64:27) at Object. (extensions::binding:377:32) at NWWindow.get (extensions::nw.Window:592:40)
Construct 3 version: r126
URL: https://editor.construct.net/r126/
Date: Tue Nov 20 2018 12:35:27 GMT+0100 (heure normale d’Europe centrale)
Uptime: 693.8 s

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r126 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
This is a known NW.js bug: https://github.com/nwjs/nw.js/issues/6553
