### ISSUE TITLE
Opening the Expressions Dialog for an object whether an addon or the system object causes a crash.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#2351]
## Problem description

Opening the **Expressions Dialog** for any object or addon including the **System Object** will result in a crash.

## Attach a .c3p

[Sample Project.zip](https://github.com/Scirra/Construct-3-bugs/files/2599761/Sample.Project.zip)

## Steps to reproduce

1. Add an event.
2. Compare two values
3. On the Expressions dialog. Select either the **System Object** or the **Mobile Advert** object.
4. Observe the crash on **r126**.

## Observed result

An application crash.

![bugreport - 1](https://user-images.githubusercontent.com/31282960/48774551-8e21cf80-ed05-11e8-8363-52c46425bf65.png)

![bugreport - 2](https://user-images.githubusercontent.com/31282960/48774606-ab569e00-ed05-11e8-9f7f-3e0644e8a5f8.png)

## System details

**Construct 3 r126**

## Additional Info

It might be related to this: https://github.com/Scirra/Construct-3-bugs/issues/2348
I want to confirm if it is fixed for generally all objects.

**Thanks in advance for looking into this.**

**Comment by DiegoScirra** [comment]
This was fixed already. Leaving this open until next release because anyone using this version will bump into this one.

**Comment by ChadoriRebornXD** [comment]
@DiegoScirra can we get this released soon. It's hard to use some addons with references from the **Expressions dialog**. Thanks a lot.

**Comment by AshleyScirra** [comment]
r127 is now out, and should be fixed there.
