### ISSUE TITLE
Cosmetic Dark and Light theme bugs in firefox.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2352]
## Problem description

Some elements does not seem to style correctly in firefox. Especially scrollbars and dropdowns etc. Double scrollbars in some cases.

## Attach a .c3p

![firefox](https://user-images.githubusercontent.com/27011641/48807512-05fbf400-ed1e-11e8-8327-dc34fa0a410e.JPG)
![chrome](https://user-images.githubusercontent.com/27011641/48807541-20ce6880-ed1e-11e8-9a51-2b9af4bc68a9.JPG)

## Steps to reproduce

1. Run C3 in firefox with dark and light theme on.
2. Notice some elements missing styling

## Observed result

Some elements missing correct styling.

## Expected result

Should look nice as in chrome.

## Affected browsers

* Chrome: no
* Firefox: yes
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in next release.
