### ISSUE TITLE
Tween.Tags can cause crash

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#2356]
## Problem description

I did notice just now that the documentation states that it is specifically for returning the tag in the "on any finished" trigger, but it shouldn´t crash regardless tho. Also I guess I just expected it to return the tag of the currently active tween but I kinda forgot why I wanted this, I think I wanted to do something like this **Sprite.Tween.Value(Sprite.Tween.Tags)**

When checked (every tick), this just returns empty.

When placed like this, it returns the tag properly.
![1](https://user-images.githubusercontent.com/31101309/48846361-42bbff80-ed9f-11e8-8dde-0a925a719f5b.PNG)

However when placed like this, it crashes the preview.
![2](https://user-images.githubusercontent.com/31101309/48846372-4c456780-ed9f-11e8-8775-5e446e845e51.PNG)

## Attach a .c3p

[tagErrors.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2604501/tagErrors.c3p.zip)

## Steps to reproduce

1. Preview the project, text doesn´t change
2. Rearrange it like in the images above
3. Observe different bahavior/crash

## Observed result

-

## Expected result

-

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r126 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 245 mb (0.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release. The expression now works either before or after starting a new tween.
