### ISSUE TITLE
C3 runtime iOS export Bug (probably caused by .webm audio)

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#2358]
## Problem description

my project works now smoothly with the C3 runtime inside the Browser. Export to Android works, remote Preview on iOS also, but export to iOS with Xcode not. After Progress Bar and Logo, it stops working. With C2 runtime its no Problem.  if I delete the .webm audio file the problem is gone. Earlier imported .m4a files cause no problem.

## Attach a .c3p
[iOS_Bugtest_14.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2605957/iOS_Bugtest_14.c3p.zip)

## Steps to reproduce

1.  r.126, export project to iOS, all 3 export options enabled, 12.0+,  xCode project, hide Status Bar enabled
2.  open in Xcode 10.1 (10B61), in the issue manager I update the alerts to recommended settings

3. preview on attached device (i used iPad iOS 12.1)

## Observed result

progress bar and Logo remains on the screen

## Expected result

after progress bar and logo a blue screen should appear (works in C2 runtime)

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_1
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r126 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 791 mb (2.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Okay this issue should resolved in the next release.
