### ISSUE TITLE
Pasting a Canvas in a Canvas seems broken

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2359]
## Problem description

Pasting a Canvas inside another Canvas object makes the object get pasted offsetted and the offset is different depending on the camera's scrollx and scrolly it seems

## Attach a .c3p

https://cdn.discordapp.com/attachments/311108993739390976/514985175277633648/MultiLights.c3p

## Steps to reproduce

1. Run project
2. Move the camera around (arrow keys)

## Observed result

It seems to be offsetted depending on the camera
Looks like this
![image](https://user-images.githubusercontent.com/11213825/48877584-361dc280-ee04-11e8-8b60-010eb155ee9b.png)

## Expected result

It should paste it correctly like on the exact same project made in C2 with the Paster addon
https://cdn.discordapp.com/attachments/311108993739390976/514985565742039060/MultiLights.capx
It should look like this:
![image](https://user-images.githubusercontent.com/11213825/48877605-577eae80-ee04-11e8-9d9e-1905582e5d32.png)

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

n/a

**Comment by tunepunk** [comment]
This looks similar to the issue I han in this issue. Maybe the info from this bug report can help you fix it. 

https://github.com/Scirra/Construct-3-bugs/issues/2209

**Comment by skymen** [comment]
No because I'm not using snapshot, and I used the same pixel density as the layout. In fact pasting anything that is not a canvas on the canvas works fine.

**Comment by SalmanShhh** [comment]
![](https://cdn.discordapp.com/attachments/506948218840547330/514915694916403212/unknown.png)
here is another example using the BBox positions of the drawing canvas to draw a fill rectangle. notice how off it is.

seems to go out of wack in loops somehow

**Comment by AshleyScirra** [comment]
Minimal repro: 
[canvas-paste-canvas.zip](https://github.com/Scirra/Construct-3-bugs/files/2699594/canvas-paste-canvas.zip)

**Comment by AshleyScirra** [comment]
The minimal repro case is fixed for the next build, but doesn't seem to help with the originally attached project. However that project is too complex to debug (especially since shadowlight issues lots of complex rendering commands). We will need to find a minimal repro, closer to the example I attached, to be able to solve this.

**Comment by skymen** [comment]
It seems like you linked a zip file instead of a c3p file and even renaming it to c3p doesn't seem to allow it to load in C3.

I will try to reproduce it again in the next version
