### ISSUE TITLE
Hard to see parentheses and cursor in Dark Theme.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2361]
## Problem description

![image](https://user-images.githubusercontent.com/2965842/48904614-fc82a100-ee6f-11e8-9631-9f67a4999520.png)

![image](https://user-images.githubusercontent.com/2965842/48904634-0f957100-ee70-11e8-9f23-3c3035411a95.png)

## Steps to reproduce

1. Open an input window.
2. Write expression with several parentheses.

## Observed result

It's hard to see parentheses and where the cursor at.

## Expected result

Easily visiblle cursor and parentheses like in default theme or C2.

## Affected browsers/platforms

I tried Desktop Version, Chrome and Windows Store version with r125, r127.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r127 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 23 gb
Storage usage (approx): 198 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 755M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by BonzerKitten7** [comment]
I love the dark theme, but the lack of support for it is very annoying. For example, the invisible layer locker have been a problem for months.

**Comment by AshleyScirra** [comment]
Relevant CSS classes are (with their defaults):

```css
.sh-bracket-highlight {
	background-color: rgb(192, 192, 192);
}
.sh-bracket-highlight::selection {
	color: white;
	background-color: #3390FF;
}
```

**Comment by bilgekaan** [comment]
Can we edit the themes?

**Comment by Animmaniac** [comment]
Fixed for next theme release.

**Comment by alastajj** [comment]
Still an issue so I made an open issue:  #2681
