### ISSUE TITLE
cant export to android.apk (build failed) pls help

### ISSUE THREAD

**Issue by recca20** [Scirra/Construct-3-bugs#2362]
## Problem description

 im trying to export my app to debug.apk
to try it fails.

## Attach a .c3p
![image](https://user-images.githubusercontent.com/45266094/48909573-ee338580-ee6d-11e8-9391-01f803291fe6.png)

![image](https://user-images.githubusercontent.com/45266094/48909582-f55a9380-ee6d-11e8-8235-bd6c804624f2.png)

## Steps to reproduce

1.
2.
3.

## Affected browsers/platforms

android Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Can you please provide the information requested in the template. Your screenshot holds next to no information unfortunately.

**Comment by shortercode** [comment]
@recca20 without any additional information I cannot move forwards with this bug. If you are still experiencing this problem then please file another issue, with the template completed this time.
