### ISSUE TITLE
Expressions Dialog :: Can't lookup addons inside folders.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#2365]
## Problem description

Can't search addons if inside a folder.

## Attach a .c3p

[Bug Report.zip](https://github.com/Scirra/Construct-3-bugs/files/2609519/Bug.Report.zip)

## Steps to reproduce

1. Create an event condition
2. Compare two values
3. Find Expressions
4. On the Search Bar :: Search for "Mobile". To lookup the MobileAdvert.

## Observed result

Can't find an existing addon. If inside a folder.
![report](https://user-images.githubusercontent.com/31282960/48926230-060b1800-ef07-11e8-9ca4-52a8c3d9d25a.png)

## Expected result

Can find the searched addon if existing.

## System details

**Construct 3 r127**

## Additional Info

Thanks in advance for looking into this.
**If possible please, patch this up immediately. We've been patiently waiting for the Expressions Dialog to work properly. It's hard to use Construct without the expression references from addons which contains a lot of expressions.** 

## Similar References

https://github.com/Scirra/Construct-3-bugs/issues/2351
This is a bug from how long we've been waiting for a properly working Expressions Dialog.

**Comment by DiegoScirra** [comment]
Fixed.
