### ISSUE TITLE
Error at put sprites on animation editor

### ISSUE THREAD

**Issue by sielxm3d** [Scirra/Construct-3-bugs#237]
I am having a problem after click on the second animation of my project
in this project i want to replace the sprites of animation

![error-image](https://cloud.githubusercontent.com/assets/28766366/26177211/2fe05006-3b2f-11e7-9bca-2762861a61de.png)

Error report information
Type: unhandled rejection
Reason: Error: The source image cannot be decoded.
Construct 3 version: r28
URL: https://editor.construct.net/index.html
Date: Wed May 17 2017 18:29:39 GMT-0300 (Hora oficial do Brasil)
Uptime: 35 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r28

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce 8400GS Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by mfoster98** [comment]
If you can lay down the steps on how to reproduce this, I wouldn't mind checking on my end if it recreates the bug :)

**Comment by mfoster98** [comment]
- issues can be harder to fix if you dont use the template :P  I'd recommend resubmitting

**Comment by sielxm3d** [comment]
I makes the Sprites Nimation with Blender as PNG wirhout compressão with
the resolution 60x60 with RGBA mode

Em 17 de mai de 2017 6:44 PM, "mfoster98" <notifications@github.com>
escreveu:

**Comment by mfoster98** [comment]
Like steps on how to reproduce that nasty error message you have there inside the construct 3 editor (I'm not part of staff, just willing to help out for a bit :) )

**Comment by sielxm3d** [comment]
![error-imag2](https://cloud.githubusercontent.com/assets/28766366/26177982/629edfdc-3b32-11e7-8dac-27c9da6d898a.png)
Now complicated even more, while rendering the game appeared some horrible rectangles.

**Comment by mfoster98** [comment]
Think this is one for the team haha

**Comment by sielxm3d** [comment]
Thank you @mfoster98 I do not know why this was happening, nor do I know the solution when you import some png that construct3 does not accept, but I do not know why my project stopped giving that error that closes our beloved software.

**Comment by mfoster98** [comment]
I've got an issue not allowing me access to the engine right now :(  My fault! 

Good luck with this report though :)  Sorry I couldn't be or more help!

**Comment by sielxm3d** [comment]
OK thank you.

**Comment by DiegoScirra** [comment]
@sielxm3d 

Have you been able to reproduce this problem consistently? It is very hard and time consuming to try and fix problems without clear steps to reproduce them.

**Comment by AshleyScirra** [comment]
Closing, please see the guidelines. Reports like this are almost impossible to fix. We need the requested information to actually be able to help you.
