### ISSUE TITLE
Iframe HTML content not load on android

### ISSUE THREAD

**Issue by nyuszi008** [Scirra/Construct-3-bugs#2370]
## Problem description

If write directly HTML content in iframe, it will not load on android

## Attach a .c3p

https://drive.google.com/open?id=1tXtG3SUEe9T-PVYerKeyeAVMJtVmP53j

## Steps to reproduce

1. Paste iframe.
2. Delete URL and paste any HTML text
3. Export to Android

## Observed result

Iframe will not load on android.

## Expected result

Iframe will load on android.

## First affected release

r127

## Affected browsers/platforms

* Android: yes

## System details

<details>
<summary> platform info </summary>
Platform information
Browser: Chrome
Browser version: 70.0.3538.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
C3 release: r127 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 19 gb
Storage usage (approx): 98 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by shortercode** [comment]
I expect this is a security limitation, cordova has several whitelists for network connections. What value are you using for "URL whitelist" in the android export?

**Comment by shortercode** [comment]
Thanks @nyuszi008 I'm still looking into this.

**Comment by shortercode** [comment]
Okay should now be resolved for build service exports. Cordova exports will be fixed in the next release.
