### ISSUE TITLE
Failed to invoke download screenshot

### ISSUE THREAD

**Issue by danielpalaversich** [Scirra/Construct-3-bugs#2371]
## Problem description

Tengo un error cuando invoco la descarga a través del plugin browser, referenciado por "CanvasSnapshot" de sistema, lo mismo sucede cuando lo quiero realizar con el complemento de multimedia. 

En el motor de ejecución de C3 no estaría funcionando. Pero si funciona en el de C2.

## Attach a .c3p

- Sistema
- Multimedia
- Navegador

## Steps to reproduce

1.
2.
3.

## Affected browsers/platforms

* Chrome: yes
* Firefox: no
* Edge: no
* Safari: no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Please can you provide a project demonstrating this issue, along with replication steps and your platform information. I don't speak Spanish, so I am using Google translate. If you do speak English then that is preferred.

Puede proporcionar un proyecto que demuestre este problema, junto con los pasos de replicación y la información de su plataforma. No hablo español, así que estoy usando el traductor de Google. Si hablas inglés entonces es preferible.
