### ISSUE TITLE
Animation Editor Moving a Folder Above Animation Crashes C3 Everytime

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2372]
**## Problem description**

In the animation editor, I created a folder under an animation and then moved the folder above the animation and the project crashed.

**## Attach a .c3p**

https://www.dropbox.com/s/wrizqq95jgayw5x/Animation%20Editor%20Folder%20Move%20Bug.c3p?dl=0

**## Steps to reproduce**

1. Right Click > Insert New Object
2. Select Sprite
3. Under the Animations list, right click and create a new folder.
4. Move the folder above the animation file. If it ignores you the first time you do this, do it again.
5. The project will crash. Happens every time.

**## Observed result**

An error message comes up with error information, allowing me to copy the information, save my project which is risky or restart the project. The background turns a transparent red colour.

**## Expected result**

I expect the folder to move above the animation file.

## First affected release

I have only noticed it on r120 stable release

## Affected browsers/platforms

Chrome.

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: Unknown (It seems to happen consistently with the others, it's possible that it will work with safari, I just don't have this browser and don't really want it).

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r120/main.js, line 81, col 57590
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at t.ǃQm (https://editor.construct.net/r120/main.js:81:57596) at t.ǃeWs.ǃPk (https://editor.construct.net/r120/main.js:81:788347) at t.ǃeWs.ǃFC (https://editor.construct.net/r120/main.js:81:787895) at Array.ǃFL.addEventListener (https://editor.construct.net/r120/main.js:81:781020) at ǃv.Event.ǃVjz.ǃVju (https://editor.construct.net/r120/main.js:2:202014) at ǃv.ǃV.ǃKY.ǃFT.dispatchEvent (https://editor.construct.net/r120/main.js:2:200157) at ǃv.ǃV.ǃKY.ǃFT.ǃVMf (https://editor.construct.net/r120/main.js:2:435606) at i.ǃV$ (https://editor.construct.net/r120/main.js:2:441610) at HTMLDocument.ǃHb.ǃVr (https://editor.construct.net/r120/main.js:2:437997) at HTMLDocument. (https://editor.construct.net/r120/main.js:2:196891)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Tue Nov 27 2018 14:39:15 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 279.5 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Confirmed this happens in the current development version, it appears to be triggered during the drag not the drop hence why it doesn't reproduce all the time. Assigning to @DiegoScirra to review

**Comment by DiegoScirra** [comment]
Fixed in the next release.
