### ISSUE TITLE
[C3 runtime only] Tile State check condition is broken

### ISSUE THREAD

**Issue by SalmanShhh** [Scirra/Construct-3-bugs#2377]
## Attach a .c3p
https://cdn.discordapp.com/attachments/517079142681018368/517079228001550343/Tile_State_Check_error.c3p

## Steps to reproduce

1. run the project
2. check for the text box to show the tile ID
3. check to see if the actions in the tile compare state events are appending the text object with "Mirror: " with yes or no

## Observed result

just becomes a black screen and some errors in the console log.
![image](https://user-images.githubusercontent.com/21278459/49110959-c043ac00-f286-11e8-9cb7-b036be5bb227.png)

## Expected result

not a black screen and the text getting appended.
## First affected release
Latest Beta release **R127**

## Affected browsers/platforms

* Chrome: yes
* C3 Desktop: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Thanks for the report, should be resolved in the next release.
