### ISSUE TITLE
Behaviors UI text has its own col-resize spot

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2379]
## Problem description

Rearranging behaviors UI reflects some strange behavior, where text has its own resize point. Not sure if it should be like this. And if others UI has same behavior.

## Attach a .c3p
The reproduce video
[2018-11-28 22-00-32.zip](https://github.com/Scirra/Construct-3-bugs/files/2626418/2018-11-28.22-00-32.zip)

## Steps to reproduce
See video instead, its hard to explain

## Observed result
Rearranging behaviors UI shows some strange behavior. There are 2 resize/dragging point instead 1. Both offers different behavior

## Expected result
Text should not have its own UI dragging point. If it has, mark it with something? Also text dragging point drags UI around differently then the correct one.

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
C3 release: r127 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 950 mb (7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
This doesn't seem to be limited to the behaviour dialog, it can be reproduced with anything that uses the table control. I've looked at the code and it appears that it's using the hitbox for the text as well as the column header, which I'm guessing is accidental. You can actually drag from the right hand side of the text as well. So there's effectively 4 hit areas per column. 

I've changed it to specifically use the column hitbox, and also increased the size of the drag area slightly. The text box was effectively increasing the drag area before, so the change had made it harder to use.

As this code was originally written by @DiegoScirra I'm assigning him to review the fix.
