### ISSUE TITLE
Cannot use engine due to a bad mod install, need a little info.

### ISSUE THREAD

**Issue by mfoster98** [Scirra/Construct-3-bugs#238]
## Problem description

I have installed a mod using the addon manager and once I restarted the engine it says "try disabling browser addons".  **How do I go about doing this?**  I've searched everywhere in my files for a construct 3 or scirra names folder but came up empty, only found an empty construct 2 folder in appdata.

## Attach a .c3p

I don't feel this is necessary for this issue.

## Steps to reproduce

1. I installed a zip file that I re-filetyped as a .c3addon file as I thought it would work, alas it didn't and now i've broken everything (I've no longer got this file as I have deleted it from my storage.

## Observed result

On-editor-launch error message allowing no continuation with the engine.

![screenshot_1](https://cloud.githubusercontent.com/assets/11301023/26178053/3bd3bc52-3b54-11e7-9764-9c50244d1d7c.png)

## Expected result

I expected the editor to load up normally

## Affected browsers

* Chrome: yes - Zoom: 100%

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Unable to access editor

</details>

**Comment by jaydonteh** [comment]
Try clearing your browsing data for now.

**Comment by mfoster98** [comment]
Thanks for the help, but this didnt work for me unfortunately

**Comment by mfoster98** [comment]
Found the fix, I used chromes developer console and found everything.  Cleared my application cache and reloaded the engine, all working now 🗡
