### ISSUE TITLE
SetColor doesn't work

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#2383]
## Problem description

Can't make setColor work, it just doesn't react

## Attach a .c3p

[sadfsaf.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2632725/sadfsaf.c3p.zip)

## Steps to reproduce

1.click on the map of singapore
2.nothing happens
3.

## Observed result

nothing happens to the color of the map

## Expected result

color changes randomly
## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_1
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
C3 release: r127 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.5 gb
Storage usage (approx): 1.2 gb (15.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
This is just down to the colours you are blending I believe, it's just not having much of a difference. It blends with the luminosity of the destination. As your image is very close to black it doesn't change the value very much, then the low opacity reduces the effect even more.

Increasing the opacity and making the image lighter produce a clearer colour change. Also the rgbEx expression can hold values larger than 100% for a colour channel, for exactly these sorts of situations.

**Comment by damjancd** [comment]
I changed the values to rgbEx(random(300),20,200) still no dice, change the image to contain lighter colors and I can easily set the color in C3 but at runtime it doesn't react at all.

**Comment by damjancd** [comment]
@shortercode I can add another bugreport  project with these new changes if you like.

**Comment by damjancd** [comment]
@shortercode Sorry for the bother, it was my bad. I mixed up the Set Color on the object with the Set Color parameter effect 

I don't even know why the set color on object exist or how to use it :p

Anyway, my stupid mistake
