### ISSUE TITLE
Memory usage increasing with no limit until crash

### ISSUE THREAD

**Issue by Bgimet** [Scirra/Construct-3-bugs#2384]
## Problem description

I have a simple application, who display random videos, on a player. Videos are available in a folder, who is loaded at the start of the application. Every ends of the video displayed at the screen, another video is shown. Today, I have only two videos on my folder. 

After several days of testing, I figure out that there is something wrong with the memory management : 

If I let my app run during several days (which is supposed to be, because my app runs on shows), the memory usage jump from 600mb to 2,5 go and my app crash when I try to use it. 

I don't understand why the memory is increasing that way, because only two videos are displayed once after another.

## Attach a .c3p

I can't give a .c3p file, because my client is a big industrial actor and the content is sensitive.

## Steps to reproduce

My app is construct this way : after 30s of innactivity, a video player is shown with a video loader from an external folder. At the end of the video, I play another video from that folder.

## Observed result

The memory usage is increasing to more that 2go, and the app crash.

## Expected result

Well I guess the memory should not be increasing without end.

## First affected release

Construct 3 r120 stable

## Affected browsers/platforms

Windows build

**Comment by shortercode** [comment]
Could you provide a project approximating your usage, with dummy videos?

**Comment by AshleyScirra** [comment]
Nothing we can do about this report I'm afraid, please see the bug report guidelines which you must follow for us to be able to help. It also explains what to do if you don't want to share your project.
