### ISSUE TITLE
[C3 Runtime][Performance] Memory Management needs a conditional trigger "On Progress".

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#2385]
## Problem description

I'm sorry for not posting it in the **ideas & suggestions** but this look to be a feature that is needed but missed from the **Memory Management** feature implementation from the **written suggestion** on the **Construct 3 ideas & suggestions.** 
Since the **Memory Management** was already pushed, it would look trivial to make another request for something that is already submitted and approved but only missing a few parts. 
Regardless, this feature is still very important.
It is a matter of good practice in terms of development and performance.

Reference :: https://github.com/Scirra/Construct-3-bugs/issues/2098

## Attach a .c3p

If it's alright, I won't add a reproducible project for this one. It already looks straightforward.

## Observed result

No trigger to track changes from memory loading **progress**.
Not so good performance practice. 

## Expected result

Available trigger for memory loading **progress**. 
A good performance practice.

## System details

**Construct R127**

## Additional Note

**Thank you for your time.**

**Comment by AshleyScirra** [comment]
Closing as this is a suggestion, please post to the suggestions platform instead.
