### ISSUE TITLE
Offline mode (logged out)

### ISSUE THREAD

**Issue by redfoc** [Scirra/Construct-3-bugs#2386]
## Problem description

i use 2 version of C3, r120 and r127, since i can't open my project with stable r120.
So, if i logged in on r120, and open r120 while offline, it's says logged in, but if i open r127 my account are logged out.
I open back to r120 but it's now says logged out, so i don't know what i want to do for my project while offline, since i get guest mode.

## Steps to reproduce

1.
2.
3.

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Login state is only kept once - if you log out, you log out of all versions of Construct. I'm afraid we have no plans to change this.

**Comment by redfoc** [comment]
> Login state is only kept once - if you log out, you log out of all versions of Construct. I'm afraid we have no plans to change this.

Hi Ashley

I use same account for both version, and i never log out on any version.
Just switch the version while offline, and my account are logged out
