### ISSUE TITLE
Cannot open project

### ISSUE THREAD

**Issue by Dimostic** [Scirra/Construct-3-bugs#239]
## Problem description
Cannot open project 
*Enter a concise description of your problem here*
All attempts to open this project from local file fails
## Attach a .c3p
[MOBILE PALPATE MD.zip](https://github.com/Scirra/Construct-3-bugs/files/1009321/MOBILE.PALPATE.MD.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result
A pop up window giving error report information
*What do you see happen?*

## Expected result
Project should open 
*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no- Yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: missing layout in layout parameter
Stack: Error at Function.ǃK.ǃHEp (https://editor.construct.net/r28/main.js:2:226676) at te (https://editor.construct.net/r28/main.js:2:196045) at window.assert (https://editor.construct.net/r28/main.js:2:196465) at window.ǃHZK.ǃK$V (https://editor.construct.net/r28/main.js:61:334106) at ee.ǃK$D (https://editor.construct.net/r28/main.js:61:291714) at Function.ǃKeR (https://editor.construct.net/r28/main.js:61:297256) at ee.ǃKms (https://editor.construct.net/r28/main.js:61:288439) at Function.ǃKeR (https://editor.construct.net/r28/main.js:61:267701) at ee.ǃKAV (https://editor.construct.net/r28/main.js:61:271592) at ee.ǃKms (https://editor.construct.net/r28/main.js:61:288492)
Construct 3 version: r28
URL: https://editor.construct.net/index.html
Date: Wed May 17 2017 23:58:54 GMT+0100 (W. Central Africa Standard Time)
Uptime: 18.8 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r28

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by mfoster98** [comment]
Possibly a system error, project opens fine for me but with a little lag, maybe your computer can't handle the project anymore? Although the capx file says you are using only 200kb in-game.  Consider trying to lower the size of sound files, etc.

**Comment by Dimostic** [comment]
Thanks. Project opens and works fine using construct 2. This error is observed when I open using construct 3

**Comment by shortercode** [comment]
Okay I've had a look through, one of the layouts has a space at the end of the name ("Answers "). C3 considers this an invalid name so removes the space, but then there's a reference in an event sheet to the layout name. I'll make a fix for it, but it the mean time you can fix it by renaming the layout.

**Comment by shortercode** [comment]
Okay it's fixed, should be in release 29

**Comment by Dimostic** [comment]
Thanks shortercode. I can now open the project.
However, I can't  preview my game on construct 3; after clicking the preview button I see a blank layout screen. Attempts to preview all other layouts give a similar result.

**Comment by shortercode** [comment]
@Dimostic Well glad thats one thing sorted! I'm probably going to be a little busy looking at the build server tomorrow but will try to take a look in at this if I have a chance... Could you create a new bug for the issue with the preview please?

**Comment by Dimostic** [comment]
Thanks. I have created a new bug report as suggested
