### ISSUE TITLE
Crash if using Preview with Dialog and closing the project afterwards

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2390]
## Problem description

I started using the preview as Dialog to bypass a bug with touch that was crashing some browsers but after i saved the project and tried to quit, C3 crashed.

## Attach a .c3p

Can use an empty project, i had 100% repo rate 4/4

## Steps to reproduce

1. change the settings to not preview as popup but as dialog, restart c3
2. start a new project, preview it and close the preview frame
3. quit c3, notice it crashes

* Desktop: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property '0' of undefined @ TypeError: Cannot read property '0' of undefined at Object. (extensions::nw.Window:145:118) at Object.handleRequest (extensions::binding:64:27) at Object. (extensions::binding:377:32) at NWWindow.get (extensions::nw.Window:592:40)
Stack: TypeError: Cannot read property '0' of undefined at Object. (extensions::nw.Window:145:118) at Object.handleRequest (extensions::binding:64:27) at Object. (extensions::binding:377:32) at NWWindow.get (extensions::nw.Window:592:40)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Mon Dec 03 2018 10:33:09 GMT+0200 (Eastern European Standard Time)
Uptime: 48.3 s

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Yet another case of https://github.com/nwjs/nw.js/issues/6553.
