### ISSUE TITLE
First movement will cause fps&cpu spike

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2391]
## Problem description

Not sure if this is specific to my system or even a bug, but least some strange case that needs checking.
Was testing expressions with larger count of objects, but everytime i move my main sprite first time i get huge cpu&fps spike. It does not matter how long i wait, or if I make it rotate every tick. It happens every single time when screen size is not the default that it opens up first time.
Also when i stress cpu to 30 or 50, fps&cpu still spike alot with first movement.
I tried with firefox and coulden't reproduce, but firefox lags a lot for frist ~3-4 sec, still it turns stable. So maybe chrome does some internal optimize for code and changing it will breake it and cause peformance spike for first time.

## Attach a .c3p
[Test_Col (3).zip](https://github.com/Scirra/Construct-3-bugs/files/2638540/Test_Col.3.zip)

## Steps to reproduce

1.Preview example, maximize window
2.Wait a bit for cpu&fps settle, tap somewhere to move sprite
3. See cpu&fps spike, all following moves are smooth

## Observed result
Frist time tap and sprite move will put cpu to 100% and spike fps lot. All following moves are fine. At 40 fps it spikes down to 30 or less. At 30fps it will spike down to 15 etc.
It does not happens frist time when i open up project and it has default small screen size. But when i reproduce it with maximized screen size and then next time i preview it with even smaller  screen size then default, bug will reproduce.

## Expected result
No fps spike. 
If internal code optimizes sprite location and first movement changes that and will cause spike, then there isent much to do, but least this needs check if thats the case or this is something else.

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
C3 release: r127 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 950 mb (7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Which runtime is this? Do you see the same behaviour in the other runtime?

**Comment by SnipG** [comment]
Both runtimes. C3runtime with worker mode has this fps&cpu spike also.

**Comment by AshleyScirra** [comment]
I can reproduce, but only in Chrome - Firefox and Edge seem unaffected - so this strongly suggests it's a Chrome quirk. I can't tell much from a profile but it looks like they might have a heuristic that kicks off a garbage collection on the first user input to the page. This is out of the control of our engine, if you want to take it further you could try reporting it to Google at crbug.com.

**Comment by SnipG** [comment]
I tested the idea of first user input.
All of this also happens with mouse(both use same js input i guess)
I added new sprite, if tap destroy -> no lag. 
If tap, set self.x+50 -> no lag. 
On tap set variableX to touchX - no lag.
On tap set text to touchX - no lag
But, if i have on tap set object.X to touch.X - instant lag.
If i update variableX each tick into touchX and on tap set Object to variableX - still lag.

! If i set variableX with ROUND(touch.X) and now i set object.X with variableX - No lag
! Same if i set object X&Y with round(touch.x), round(touch.y) - No lag

So problem only occures if i set sprite with unrounded input.X or Y

All of this does not happen with default size that open first time project preview. Also when i set touch.x to text. At default size, text shows touch.X without decimals(150;290 etc). But when window size is modified, it is always 129.325235235 etc. 

So many chrome or runtime does some rounding etc for objects, which causes bug first time.
 
PS. The problem from looks of it, if you navigate menu etc before game, you can dodge this bug and get lag spike when maniplulating ingame objects, so in most games user gets lag spike each time the game start and users starts playing, which seems bad.

**Comment by SnipG** [comment]
Took a even further look into this. It does not involve touch plugin at all, just First unrounded set position causes lag spike.
[Unrounded_LagSpike.zip](https://github.com/Scirra/Construct-3-bugs/files/2648230/Unrounded_LagSpike.zip)

**Comment by TheRealDannyyy** [comment]
@AshleyScirra is there a tracking bug for this or does it still require one?

**Comment by AshleyScirra** [comment]
If this only happens in Chrome, it essentially proves it is a browser-specific issue. As mentioned these need to be reported to the browser vendors. If you can reproduce an issue across different browsers that may be related to our code so I can take a look, but this issue does not appear to have involved cross-browser testing and appears to have only so far identified a Chrome-specific issue.

**Comment by TheRealDannyyy** [comment]
I got that part, was just asking if there is already an open bug in crbugs or if it still needs one to be opened up.

**Comment by AshleyScirra** [comment]
I'm not aware of any.

**Comment by TheRealDannyyy** [comment]
I've tried to reproduce this and it's GC+DOM doing full heap collections. From my tests it doesn't seem to matter, if the user inputs something or not. ([Lagspike Testing.zip](https://github.com/Scirra/Construct-3-bugs/files/2649511/Lagspike.Testing.zip))

![gc heap](https://user-images.githubusercontent.com/15656049/49525786-c81ad600-f8ae-11e8-9afa-61260da0bc4e.PNG)



This seems to be another case of Chromium's bad GC, doing the job whenever it likes to. [Here](https://bugs.chromium.org/p/chromium/issues/detail?id=815259) is a similar issue, they don't seem to care about. I'm honestly not sure if it's worth it to create another bug report for this.

**Comment by SnipG** [comment]
This is does not involve GC(your case could be something different), if i get time i test this case more and probably "someday"  report it to google.

If following this issue tracker guidline and instantly reporting stuff to google, it would take, depending on case, forever for google guys look into cases that are way to Chaotic. If they even look into them.

**Comment by TheRealDannyyy** [comment]
Your "Unrounded_LagSpike" test project also showed that GC is at fault on my end. If you got any measurements that suggest something else being at fault, feel free to post them here.

**Comment by AshleyScirra** [comment]
Google have fixed issues I've filed within days in the past. If you file a good report they can often deal with it quickly.

**Comment by TheRealDannyyy** [comment]
They do, but for some reason GC related bug reports often result in them not being able to reproduce it on their ends and ignoring the bug. 

Anyway looking forward to @SnipG doing a report about this.

**Comment by SnipG** [comment]
http://crbug.com/912225

It seems if project already contains visible object(text,sprite etc) with decimal point value(in some case even 0.5 will do), there is just single lag spike beginning of layout and this bug will go unnoticed. 

Anyway, lets see if chrome guys can fix this.

**Comment by TheRealDannyyy** [comment]
Starred. 

Interesting that the lagspike in this example isn't caused by GC. Something with the animation frame firing and microtasks seem to be the cause this time around.

![lagspike](https://user-images.githubusercontent.com/15656049/49536788-aa0d9f80-f8c7-11e8-8221-7ed401ecf71d.PNG)

**Comment by SnipG** [comment]
TheReal, your old report if it uses c3runtime then you need to redo it. After c3runtime memory leak as fixed, the chrome dev that did it, wrote in some other post:
 "This changes increases the amount of GC we do. Before ImageBitmap objects were not being cleared at all (leading to bugs that looked like memory leaks)."

So you need to redo your tests with latest beta at least.

**Comment by TheRealDannyyy** [comment]
My old report was done in C2 and I think is something completely different than this issue. It isn't technically the fault of C2 or C3, but more how they handle unloading audio from memory.

At some point I'll have to create a simple html5 project without Construct and open up another issue, if the existing one leads nowhere. I'll give it a couple more weeks.

**Comment by SnipG** [comment]
Its more then month and seems google devs have hard time to analyse 3th party software export with minified code. Could Ashley look into this and maybe give them some internal info. I tried c3 but its way to hard to read anything and c2 gives NaN.

[First_Undround_lag2.zip](https://github.com/Scirra/Construct-3-bugs/files/2733535/First_Undround_lag2.zip)

![oonee](https://user-images.githubusercontent.com/28864889/50781772-e78e8f80-12ae-11e9-8794-96cf6f17ac13.jpg)

![oonee2](https://user-images.githubusercontent.com/28864889/50782097-bbbfd980-12af-11e9-88be-a73d68ddb141.jpg)


It seems at unround placement it checks every object again, or something like that.

If bug like this happens on other cases too, not just unround placement, it would not be good.

**Comment by AshleyScirra** [comment]
I can't explain why this happens - the first call seems to take an unusually long time, then subsequent calls are fast again. So it's identical code running slower on the first input event.

I would guess this is the way JS engines don't optimise code until it's called, and the first touch activates a whole stack of JS functions that get tiered up in to a higher optimisation mode. Either the first run optimises on-the-spot, or maybe it leaves it running in a slower interpreter mode while it JITs it in the background; either way, the first run is slow and by the time it does the second run it's fully optimised so is fast again. That would just be the normal behavior of JIT-compiled languages.

**Comment by SnipG** [comment]
Almost every user input is float, sprite move when fullscreen is scaled- results float positions. If it does not need much rewrite, could you do test with dev build, convert sprite draw/move Int to float by default.
But if it uses Int for every object  and need this convert later which could trigger "maybe" even all old object with floats, then this lag could happen more then just once. But does INT gives some benefits at somepoint?

Having float by default, maybe can decrease layout load lag too.

**Comment by AshleyScirra** [comment]
JavaScript doesn't distinguish between float and int, it just has one number type which is a float. However JS engines profile code and if a variable happens to only ever store whole numbers, it optimises it as an integer because it's faster. However if you later pass a fractional number, the optimisation is now invalid so it bails out, updates the type of the variable, and reoptimises. The V8 blog is a good place to read the technical details of how its optimisations work: https://v8.dev/blog

While everything is a float in the engine (because all JS numbers are floats), I suspect if all your objects happen to be at integer positions, the JS engine can observe everything involves whole numbers and optimise based on that assumption. Then as soon as you start involving fractions, it has to re-optimise as it realises its past assumptions were wrong. This can apply to pretty much any parameter - position, angle, size and so on.

One way to test this theory is try placing an object in the layout with a fractional position and angle, and see if that fixes the lag on first input - this way the JS engine will see right away on startup all those variables really are fractional and optimise with the right types from the start.

I suspect that real-world games will pretty much always have enough fractional content to avoid this problem - I'd guess it only comes from small tests where, by chance, everything happens to use whole numbers until you do something involving fractional numbers.

**Comment by SnipG** [comment]
Yeah found it at: 
https://v8.dev/blog/elements-kinds 
and
https://www.html5rocks.com/en/tutorials/speed/v8/

They even have "--trace-elements-transitions" to check the transitions
 Going to check it myself, if i can make use out of it.

Anyway, ty for looking into this issue.
