### ISSUE TITLE
Random crash Cannot read property 'ǃW' of null at window.ǃka.ǃjN 

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2392]
## Problem description

Started appearing quite frequent, I close tabs and get that crash + this wonky frame in the crash.

![image](https://user-images.githubusercontent.com/7268697/49376166-109b8d80-f70f-11e8-98c4-1863f4ff06ac.png)

When I try to save the project from the crash dialog, I also get this: 
![image](https://user-images.githubusercontent.com/7268697/49376189-1e511300-f70f-11e8-913d-2c27df86699e.png)

Guess what, i can't reproduce it, it's too random.

* Desktop: yes
## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r120/components/editors/eventSheetView/eventSheetView.js, line 1, col 50424
Message: Uncaught TypeError: Cannot read property 'ǃW' of null
Stack: TypeError: Cannot read property 'ǃW' of null at window.ǃka.ǃjN (https://editor.construct.net/r120/components/editors/eventSheetView/eventSheetView.js:1:50424) at viewsUIState.map (https://editor.construct.net/r120/main.js:81:52211) at Array.map () at t.ǃSC (https://editor.construct.net/r120/main.js:81:52200) at window.ǃCt.ǃjN (https://editor.construct.net/r120/main.js:81:273603) at window.ǃCt.ǃjN (https://editor.construct.net/r120/main.js:81:280958) at window.ǃnk.ǃvt (https://editor.construct.net/r120/components/editors/eventSheetView/eventSheetView.js:1:3908) at Array.ǃvU.ǃv.ǃNm.ǃv.ǃvZ.ǃvd (https://editor.construct.net/r120/components/editors/eventSheetView/eventSheetView.js:1:1988) at ǃv.Event.ǃVjz.ǃVjk (https://editor.construct.net/r120/main.js:2:202197) at ǃv.ǃV.ǃq.ǃVnW.dispatchEvent (https://editor.construct.net/r120/main.js:2:200167)
Construct 3 version: r120
URL: https://editor.construct.net/
Date: Mon Dec 03 2018 15:18:06 GMT+0200 (Eastern European Standard Time)
Uptime: 13878.8 s

Platform information
Browser: NW.js
Browser version: 0.31.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.3541666269302368
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@878cd31214ac27a3996927cd5c9c138b10c9fc8d) NWjs/0.31.2 (like Chrome/67.0.3396.87)
C3 release: r120 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Appears to be an issue with the event sheet view persistence. Assigning to @AshleyScirra to review.

**Comment by AshleyScirra** [comment]
The crash report is using r120. By this point it seems likely it's something we've already fixed. Please only report issues that can be observed in the latest beta. FYI crashes are automatically logged on our server (providing you don't use blocking extensions), so if all you have is a crash report, there's no need to report it, it'll come up in our logs anyway.

**Comment by JeFawk** [comment]
Okey, good to know about the logging. I only use the stable releases so for random crashes I will not swap to beta to just work on my current projects for the next few days until another random crash appears.
