### ISSUE TITLE
iPhone XR & XSMAX showing black bars near notch area.

### ISSUE THREAD

**Issue by HRTStudio** [Scirra/Construct-3-bugs#2396]
## Problem description

Construct 3 r128
iPhone XR & iPhone XS MAX
showing black bars near notch area on landscape mode.

### C3 project:

[iPhone XR,XS MAX.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2683407/iPhone.XR.XS.MAX.c3p.zip)

## Steps to reproduce

1. In C3 build project with option Cordova or Xcode project.
2. Build in PhoneGap and run on device with IOS12 or run in Xcode in simulator with iOS 12

## Observed result

Showing black bars near notch area on iPhone XR & iPhone XS MAX

## Expected result

Not to show Black Bars since it's not showing in iPhone X & iPhone XS

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by sangeeth786** [comment]
Did you get solution for this.

**Comment by sangeeth786** [comment]
@Teymur969
can you help me out on this.

**Comment by sangeeth786** [comment]
@AshleyScirra 

Please let me know when you get an solution for this.

**Comment by AshleyScirra** [comment]
From the bug report guidelines:

> Don't troll the developers
> ...
> - Repeatedly nagging developers to investigate an issue ahead of schedule, or repeatedly bumping the thread.

Please be patient. We deal with thousands of reports and many issues are difficult and take time to diagnose and resolve. As with all issues, we will post comments if and when we find a solution.

**Comment by sangeeth786** [comment]
Hey,
@AshleyScirra 

Did you get an solution for this.

**Comment by KekGames** [comment]
@AshleyScirra 
> Please be patient. We deal with thousands of reports and many issues are difficult and take time to diagnose and resolve. As with all issues, we will post comments if and when we find a solution.
Hi Ashley, I guess, you just need to replace this line in c2runtime.js:
`this.isiPhoneX  =  this.isiPhone  &&  screenWidth  ===  1125 && screenHeight  ===  2436; `
with this:
`this.isiPhoneX  =  this.isiPhone  &&  screenWidth  ===  1125 && screenHeight  ===  2436 ||  screenWidth  ===  828 && screenHeight  ===  1792 ||  screenWidth  ===  1242 && screenHeight  ===  2688;`
or add similar "hacks" for this.isiPhoneXR, this.isiPhoneXS, this.isiPhoneXSMax. Unfortunately I can't test it on real device, but I heard it works fine there (unlike on simulator)

**Comment by HRTStudio** [comment]
@KekGames 
https://www.construct.net/en/forum/construct-3/general-discussion-7/iphone-xr-xsmax-showing-black-139998

**Comment by KekGames** [comment]
@HRTStudio Yes, I know, though it would be much more convenient if this solution was built-in and we didn't have to manually change code every time

**Comment by HRTStudio** [comment]
@KekGames Yes. they are working on the solution to fix it.

**Comment by KekGames** [comment]
@HRTStudio since December? It looks like a solved issue already, they only need to  copy-paste one line of code.

**Comment by HRTStudio** [comment]
@KekGames Hmm.

**Comment by JACLEMGO** [comment]
@AshleyScirra any update on this issue?

**Comment by AshleyScirra** [comment]
This issue is assigned to @shortercode

**Comment by AshleyScirra** [comment]
@shortercode - is this fixed now with Cordova 9?

**Comment by shortercode** [comment]
Okay so I've merged in a fix that should resolve this. Can you please check the next release.

**Comment by AshleyScirra** [comment]
r156 is now out, please test again!

**Comment by shortercode** [comment]
From our feedback from other users it sounds like this is resolved, so I'm going to close this issue
