### ISSUE TITLE
Using C3 runtime sprite disappears after stopping movement

### ISSUE THREAD

**Issue by FrozenWellStudios** [Scirra/Construct-3-bugs#2399]
## Problem description

When using an on screen virtual joystick to move player using 8 direction movement, on releasing joystick player sprite disappears. This is using the C3 runtime. There is no issue with the C2 runtime as the sprite does not disappear

## Attach a .c3p

[test.zip](https://github.com/Scirra/Construct-3-bugs/files/2645601/test.zip)

## Steps to reproduce

using C3 runtime
move the player using the onscreen virtual stick and then release and player sprite disappears

## Observed result

player sprite disappears

## Expected result

player sprite does not disappear

## First affected release

visible in r120 and latest beta r128

## Affected browsers/platforms

tested in chrome, firefox and android debug apk

**Comment by AshleyScirra** [comment]
It's because you have some weird actions:

> Set conAngle to 0
> Set conAngle to int("")

You set the value twice, and the second time by converting an empty string to an integer. The C2 runtime returned 0 here, but the C3 runtime returned NaN. It's a real edge case, but fixed for the next release anyway.
