### ISSUE TITLE
Crash when rotating copied path in tilemap manipulation

### ISSUE THREAD

**Issue by Drestin** [Scirra/Construct-3-bugs#24]
## Problem description

A crash when manipulating tilemaps. In particular rotation when the brush is a copied path.

## Example project

Just a simple project with one Tilemap object. Otherwise, just create a project with one Tilemap.
File renamed to .zip to be accepted by GitHub.
[New project.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/904990/New.project.c3p.zip)

## Steps to reproduce

1. Select the Tilemap object
2. Select the tool "Select a path of the tilemap"
3. Select several tiles
4. Select the pencil tool (you should be able to paste the selected bundle of tiles)
5. Click on rotate 90 degrees

## Observed result

Crash

## Expected result

The brush should have rotated without crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r16/components/bars/tilemapBar/tilemapBar.js, line 1, col 39345
Message: Uncaught ReferenceError: ǃWhO is not defined
Stack: ReferenceError: ǃWhO is not defined at window.ǃWEa.ǃWEs.ǃWzt (https://editor.construct.net/r16/components/bars/tilemapBar/tilemapBar.js:1:39345) at l.window.ǃWEa.ǃWzt (https://editor.construct.net/r16/components/bars/tilemapBar/tilemapBar.js:1:10074) at l.window.ǃWEa.ǃWU$ (https://editor.construct.net/r16/components/bars/tilemapBar/tilemapBar.js:1:22615) at window.ǃWEa.ǃWEs.ǃWzZ (https://editor.construct.net/r16/components/bars/tilemapBar/tilemapBar.js:1:38513) at l.window.ǃWEa.ǃWzN (https://editor.construct.net/r16/components/bars/tilemapBar/tilemapBar.js:1:8452) at l.window.ǃWEa.ǃWzo (https://editor.construct.net/r16/components/bars/tilemapBar/tilemapBar.js:1:7019) at ǃp.Event.ǃWXR.ǃWXM (https://editor.construct.net/r16/main.js:2:283389) at ǃp.ǃd.ǃWif.dispatchEvent (https://editor.construct.net/r16/main.js:2:281781) at ǃp.ǃd.ǃLo.ǃpEK.ǃp$.ǃpzg (https://editor.construct.net/r16/main.js:2:542674) at ǃp.ǃd.ǃLo.ǃpEK.ǃp$.ǃpzz (https://editor.construct.net/r16/main.js:2:541398)
Construct 3 version: r16
URL: https://editor.construct.net/
Date: Fri Apr 07 2017 10:27:31 GMT+0200 (Central Europe Daylight Time)
Uptime: 48.1 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed on r17.
