### ISSUE TITLE
[Request] Event sheet's width issues

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#240]
## Problem description

This is an issue on the inconsistencies of the widths of each event and is also known on C2 as well. I'm referring to the widths of the columns in each line of event that could be dragged to lengthen or shorten them. But when Construct is resized as an un-maximised window, these widths are also affected in that it shortens itself, which does not re-lengthen when Construct is maximised. You would have to manually resize the widths for each individual events including all the nested sub events and sub events in groups. It gets really frustrating when that happens. If only a reset event's width is an option other than resetting font sizes. A feature request to smooth out this issue that has been there for years.

**Comment by jaydonteh** [comment]
@AshleyScirra Reset width has been implemented, close! 😄

**Comment by AshleyScirra** [comment]
OK!
