### ISSUE TITLE
APKs with Google Play launch to blackscreen

### ISSUE THREAD

**Issue by ReflextionsDev** [Scirra/Construct-3-bugs#2402]
## Problem description

As soon as I add the Google Play plugin to my game, all exported APKs will stop functioning entirely. I have added the app ID and signed the APK. These functions worked in the Construct 2 build. Additionally I tried compiling a build from scratch using the same GPG information but had the same issue.

## Attach a .c3p

[GPG_Test.zip](https://github.com/Scirra/Construct-3-bugs/files/2647306/GPG_Test.zip)

## Steps to reproduce

1. Create a new project
2. Add the Google Play Plugin
3. Add the Android ID to the google play ID on google play services
4. Set the project ID to you android project ID google play service
5. Export the project as a signed apk, or unsigned then sign it manually

## Observed result

Black Screen

## Expected result

The game should load

## First affected release

r120, this also happens on beta

**Comment by shortercode** [comment]
I have been unable to reproduce this using my development build or r120. Have you tried to reproduce this with your example project? Your example was set to the C2 runtime, but I also tried it in the C3 runtime.

**Comment by shortercode** [comment]
You mentioned compiling a build from scratch; did you try this with a cordova or Android studio project?

**Comment by ReflextionsDev** [comment]
Turns out this only happens on my emulator, Nox App Player. The game launches correctly on actually android devices. Still weird that this causes black screen on the emulator.

**Comment by shortercode** [comment]
I would expect the emulator not to have play services on it, which probably causes issues when play games attempts to start.

Emulators in general are less than ideal for testing or general usage for reasons like this. I would advise always testing on a physical device if feasible.
