### ISSUE TITLE
SetColor only allows first parameter to be changed.

### ISSUE THREAD

**Issue by emoaeden** [Scirra/Construct-3-bugs#241]
## Problem description

SetColor is not functioning properly, it only lets you change the first parameter.

## Attach a .c3p

https://www.dropbox.com/s/44o31mrd0d2osz4/GoodThingsComeIn3s.c3p?dl=0

## Steps to reproduce

Make a sprite
Use SetColor
Set color to 255,0,0 OR 0,255,0 OR 0,0,255

## Observed result
It only lets the first parameter (Red) to be changed

## Expected result

I thought each colour would be changed

## Affected browsers

Chrome: Version 60.0.3102.0 (Official Build) canary (64-bit)

## System details
Platform information
Browser: Chrome
Browser version: 60.0.3102.0
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3102.0 Safari/537.36

Local storage
Storage quota (approx): 6.8 gb
Storage usage (approx): 25 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 610 Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
This isn't a bug. Notice in C3 the effect only has one parameter now. So you should only set the first parameter. Use the rgb expression to set a color, e.g. `rgb(0, 255, 0)` for green.
