### ISSUE TITLE
Can't save as > save as a single file. (Desktop build 71)

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2412]
## Problem description

I can't use save as > save as a single file option. Instead of saving it looks like it tries to open a project.

## Steps to reproduce

1. Create a new projcet.
2. Try to save it or use save as > save as a single file.

## Observed result

It opens the file browser window but instead of saving, it tries to open a c3p file.

## Expected result

It should save the project.

## First affected release

Desktop build 71

## Affected browsers/platforms

* Desktop: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.0 (like Chrome/71.0.3578.80)
C3 release: r128 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 26 gb
Storage usage (approx): 246 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 755M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
Looks like a bug in NW.js 0.35... filed it here: https://github.com/nwjs/nw.js/issues/6888

Will follow up there; assuming it's fixed and an update released, will release a new desktop build update after that.

**Comment by bilgekaan** [comment]
It works, thank you!

**Comment by AshleyScirra** [comment]
Thanks for confirming!
