### ISSUE TITLE
Google Play Not Working In C3 Runtime!

### ISSUE THREAD

**Issue by drg8** [Scirra/Construct-3-bugs#2413]
## Problem description

Google Play Sign in not working in C3 Runtime. my project is finally completed and ready to be published but now there is this new problem :( . I've already generated 30+ signed apk and tested to see if there is anything wrong with the events itself but still no success. an hour ago I checked shortcode's .c3p file which he has posted in one of the previous issues with the plugin, and it is working as it should with my id. so I checked his project to see why his file is working and mine is not, I saw that he is using C2 Runtime instead of C3 :/ . please fix the plugin.

## Attach a .c3p
[playSignin.zip](https://github.com/Scirra/Construct-3-bugs/files/2652857/playSignin.zip)

## Steps to reproduce

1. run the project and click on red box to sign in.

## Observed result

nothing

## Expected result

google play sign in window should open as it does in C2 Runtime
## First affected release
none. the Google Play plugin itself is not updated for C3 Runtime.

## Affected browsers/platforms

* Android: yes
* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.31.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@878cd31214ac27a3996927cd5c9c138b10c9fc8d) NWjs/0.31.2 (like Chrome/67.0.3396.87)
C3 release: r128 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 142 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 1030 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Should be resolved in the next release. A typo snuck through into the initialisation code.

**Comment by drg8** [comment]
Thanks 😊

**Comment by ScHuLLe186** [comment]
Actually this dont work for me also. When the fix will be installed? I've setup everything, also the ads are working, but the login to Google play isnt working.

**Comment by shortercode** [comment]
@ScHuLLe186 please don't comment on closed bugs, this issue was marked as resolved in Dec 2018.

We are not aware of any issues related to the Google Play plugin at the moment, if you think one exists then you should file an issue. Please note that there are several awkward steps required by Google for you to actually use the SDK which are common to fall foul of. You have likely missed one of these.

Please refer to the documentation https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/google-play

> Click the button to link an Android app. You will need to select an application that you have already registered with Google Play and provide the SHA-1 signature for the certificate you will use to sign your application. **It is important that you have provided the signature and that when you are testing that you sign your application with the correct certificate. Your application will be unable to login unless you do this!**

> When working with an unpublished Android application you will **only be able to log in with the registered test users** for that application. To add a test user click the Testing section while editing the game in the developer console, click Add Testers and type in the email address associated with the Google Account registered on your testing device.
