### ISSUE TITLE
Special characters auto fill problem.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2414]
## Problem description

Special characters act like TAB in expression windows and auto fills the text bar unintentionally. For example, I use color in "rgb(x,x,x)" format. When I type "rgb" and press "(", it auto fills it and writes "rgba(". This happens with almost all special characters and what you type is not important, it will write the first suggested expression when you type a special character.

![2018-12-07_03-19-44](https://user-images.githubusercontent.com/2965842/49619754-03142b00-f9cf-11e8-89f7-7bfbeb3b77f1.gif)

## Steps to reproduce

1. Try to set color of an object.
2. Write "rgb" and press "("
3. It will write "rgba(" instead of "rgb("

## First affected release

all

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by tunepunk** [comment]
Seems like rgb is not on the list. If I recall corecctly they removed it in favor of rgba in a recent update.

**Comment by tunepunk** [comment]
from r124 release notes: 
C3 runtime: deprecated rgb() expression. Use rgbEx() or rgba() instead. (Note these use values in the 0-100 range instead of 0-255)

**Comment by bilgekaan** [comment]
RGB still works but it's not listed. It's similar rgbEx255. 

This kind of autofill seems helpful for listed expressions. So this might be a feature instead of a bug.

**Comment by AshleyScirra** [comment]
The rgb expression has been deprecated. This means existing projects can continue using it, but the editor acts as if the expression doesn't exist. You should use the other expressions instead.
