### ISSUE TITLE
[Expressions Dialog Issue] We have again a new expressions issue on R129.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#2417]
## Problem description

A new problem with the expressions dialog has came up. And it behaves abnormally in 2 ways.

2. You crash after selecting the **search textbox** from the **expressions dialog**..
1. You can't **back**, after clicking on an addon from the **expressions dialog**.

## Attach a .c3p

[BugReport.zip](https://github.com/Scirra/Construct-3-bugs/files/2659574/BugReport.zip)
(An empty project, that's all we need.)

### 1. Reproduce Crash.
1. Create Even :: System :: Is between angles.
2. Find Expressions.
3. Click on the **Search** Textbox.
4. Then **type** anything.
5. (The image below).
![bug1](https://user-images.githubusercontent.com/31282960/49684763-19c39a80-fb13-11e8-9ee2-88e7f2bd5cd6.png)

### 2. Reproduce can't back
 This is where the expressions dialog has failed, but didn't crash.
1. Create Even :: System :: Is between angles.
2. Find Expressions.
3. Double-click on **System**.
4. **Search works.** 👍 
5. Go back to the **base directory** of the **expressions dialog**.
6. Try to search on the **base directory**. And the **System :: Expressions Dialog** will open and list its result of the searched keywords. 👎 This is a bug.
7. But because you aren't on the **System Addon**'s directory on the **Expressions Dialog**. You can't press **back**, because you are still on the **Base Directory**. (Refer to the image below.)
![bug2](https://user-images.githubusercontent.com/31282960/49684824-314f5300-fb14-11e8-9374-807cfac6a825.png)
  
That sums it all. I'm not sure if there are other bugs, but I'm sure you'll figure it out.

## First affected release

**Construct 3 :: r129**

## System details

**Construct 3 :: r129**
- Desktop
- Browser

### Related Past Issues
1. https://github.com/Scirra/Construct-3-bugs/issues/2351
2. https://github.com/Scirra/Construct-3-bugs/issues/2365

**Thanks a lot in advance for looking into this.**

**Comment by ChadoriRebornXD** [comment]
## First affected release
**Construct 3 :: r128**
I just checked, it was also in the previous version. It just slipped through the users.

**Comment by AshleyScirra** [comment]
Think @DiegoScirra might have already spotted and fixed this but assigning to him to check.

**Comment by DiegoScirra** [comment]
Both of the issues are fixed in the next release.
