### ISSUE TITLE
[C3 - R129] GameRecorder webm filesize 0 bytes

### ISSUE THREAD

**Issue by Javanie7** [Scirra/Construct-3-bugs#2418]
## Problem description

GameRecorder issue the first recording, result file (webm) can be played, on the second recording after stop recording and invoke download result file with size of 0 bytes and unplayable.

## Attach a .c3p
[GameRecorder_R129.zip](https://github.com/Scirra/Construct-3-bugs/files/2659977/GameRecorder_R129.zip)

## Steps to reproduce

1. Play Looping an audio file for test record an audio.
2. Then start recording (None (no video) @ 0 fps, Auto, 2500 kbps).
3. After  stop recording record result can be played.
4. Try record again (without reload the browser or restart layout) then after stop record the result file is 0 bytes and file is not playable".
5. Trying restart layout after first recording, result same as no 4.
6. Trying restart the browser, result same as no 4.
7. Testing record with video only, result same as no 4
8. Testing whole video format and audio format, result same as no 4.

## Observed result

downloaded record file with file size 0 bytes from the second recording.
## Expected result
result should can be playable

## First affected release
C3 runtime - R129 Beta

## Affected browsers/platforms

* Chrome: yes 
Tested on Desktop & Mobile Version 70.0.3538.110 (Official Build) (64-bit)

* Firefox: yes
Desktop version: 63.0.3 (64-bit)
Mobile version: 63.0.2

Note: on firefox, second recording after invoke download GameRecorder url doesn't change, the blob address result same with the first blob recording and file fail to download.

* Edge: yes
Tested on desktop version:
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

Mobile version:
42.0.0.2801 (update Nov 23,2018)

* Safari: yes/no
On Safari 12.0.1 
Note: audio is not playable, start recording then stop recording nothing happen.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
