### ISSUE TITLE
Function trigger not working with name as const global var

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#242]
## Problem description

A function does not trigger the On call trigger if the name following the On call is a Constant Global Variable of type string.

## Attach a .c3p

Attached with .zip extension.
[FunctionBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1010476/FunctionBug.c3p.zip)

## Steps to reproduce

1. create a global var static string 
2. use the function On call trigger with the name of that global var

## Observed result

*What do you see happen?*
In the browser console I saw this warning: 
[Construct 2] Function object: called function 'RandomName', but no event was triggered. Is the function call spelt incorrectly or no longer used?

The Function.Call as an action does seem to work.

## Expected result

I expect for the trigger to function.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Good catch, should be fixed in r29.
