### ISSUE TITLE
129/130 Beta Release issue

### ISSUE THREAD

**Issue by RedMachine124** [Scirra/Construct-3-bugs#2425]
## Problem description
Issue 1:   
There are two issues I have found one previous with the C3 runtime the buttons in my app do not work so I have to use C2 runtime to debug and test.  It has been stated that eventually, it will be C3 runtime only which will leave me unable to continue my project. 

Issue 2: 

I upgraded to 129 and now 130 hoping to fix an issue with loading saved games.  When I click the button to load it keeps half of the previous layout on the screen in the background and loads the new one including bits and pieces of each layout.  

Seems to work fine on my computer but when I update my APK is when I have this issue.  I have to revert back to an APK from the 128 beta to be able to pull up my saved data successfully.  

I have attached images showing a message I get now in the preview mode when I try to load a saved game.  Along with a screenshot of it, half loading saved game on my device.  

![screenshot_20181210-103720_the mop bucket 2 new team 4](https://user-images.githubusercontent.com/45766454/49746957-f9592480-fc67-11e8-8263-f3bec68d93e2.jpg)

![20181210_104227](https://user-images.githubusercontent.com/45766454/49747268-adf34600-fc68-11e8-8d9d-150dcfa8335c.jpg)

![20181210_104211](https://user-images.githubusercontent.com/45766454/49747386-f6126880-fc68-11e8-91af-fada6b73399b.jpg)

![20181210_104221](https://user-images.githubusercontent.com/45766454/49747387-f6126880-fc68-11e8-943b-becc8777fee5.jpg)

Not sure if this will help or explain it enough.

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise we cannot help: we need all the requested information to be able to investigate the issue. Please also only describe one issue per report, since otherwise we cannot track the progress of investigation and resolution of each issue separately.
