### ISSUE TITLE
Construct 3 Audio Looping Issue

### ISSUE THREAD

**Issue by RacerN2O** [Scirra/Construct-3-bugs#2426]
## Problem description

Using an inverted "Tag is playing" condition to loop sounds/music by name makes the Contruct 3 runtime fire the following event more than once, as opposed to the Construct 2 Runtime where this behaviour works as expected.

## Attach a .c3p

[Soundtest C3 Runtime Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2664069/Soundtest.C3.Runtime.Bug.zip)

## Steps to reproduce

1. Open the project in Construct 3 Beta 130.
2. Run the project using the Construct 2 Runtime using the default settings. The 2 example sounds should never play at once and shouldn't be so loud that they peak.
3. Run the project using the Construct 3 Runtime using the default settings. The 2 example sounds will appear to be extremely loud and often play at once because of the amount of times the event is fired. 

## Observed result

You will hear the sounds too often at once, resulting in them being louder and different sounds playing at the same time. (Construct 3 Runtime)

## Expected result

There should only be one sound playing at once and once it finishes a randomly chosen sound will fire once in an endless cycle. (Construct 2 Runtime)

## First affected release

I can't recall not having run into this issue with the new runtime.

## Affected browsers/platforms

* Construct 3 Desktop Release: yes
* Firefox: yes

I haven't tested others.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r130 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 645 gb
Storage usage (approx): 191 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Internally audio playback in the C3 runtime is asynchronous, so it takes a moment for "is playing" to become true after using a "play" action. We can probably correct this, but in the mean time it's easy to work around by just adding a "Trigger once" condition.

**Comment by RacerN2O** [comment]
Ah, that makes sense. I didn't know that "Trigger once" was a thing.

**Comment by AshleyScirra** [comment]
OK, should be fixed in the next release.
