### ISSUE TITLE
Problem with the angle in the Behavior Platforms in C2 and C3

### ISSUE THREAD

**Issue by iwambu92** [Scirra/Construct-3-bugs#2427]
## Problem description

The problem is as soon as a solid changes its angle with a platform object. The object with the behavior Platforms slides like crazy from one side to another and falls from it.

## Attach a .c3p

 https://1drv.ms/u/s!Akv5tZozuuaheQPUhz0d-2ZWUPA

https://www.mediafire.com/file/1md7ujblidmnz4a/Problem_Angle.c3p/file

## Steps to reproduce

 The problem is as soon as the angle changes in the object, the sprites on top of it slide and fall

1. Create a Sprite (possibly a rectangle) with a "Behavior" "Solid" and a "Sine" with an "angle" movement.
 (With a magnitude of: 8 and a Period of: 12)
2. Create a Sprite with a behavior of "Platform" and place it on the top of the rectangle sprite almost in a corner
3. Start the test and you will see how the problem occurs

## Observed result

 The objects fall from the slide and fall from the solid when it is moving along with an angle movement.

## Expected result

 What should happen is that these objects do not fall when they are on the solid, or the solid moves. 

## First affected release

The problem persists from the r260 version of Construc 2 and the beginnings of C3

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

The problem persists even if the movement of "Angle" is made with events.

-

I regret to have written the other Post in a very hurried way, is that I did not have time.
Conditional greetings

**Comment by shortercode** [comment]
Your example project is private, I cannot download it.

**Comment by iwambu92** [comment]
The link has already changed, I apologize I hope you can download one of the two.

**Comment by drg8** [comment]
I found a workaround, adding 8-directional behavior to platform behavior objects fixes the sliding issue.

set properties of 8-directional behavior as follows:
1) set all the values to 0
2) set default controls "unchecked"
3) set angle to "No"

here's the project file
[Angle_Fixed.c3p](https://drive.google.com/open?id=1ex4l5YKcwVNN7Ifh1khKs-uwCZFCcNCp)

**Comment by iwambu92** [comment]
What I have tried and solves the failure in "Part". Although it is not quite right.
When the "Sprite Rectangle" is added an 8 directions (without the "Set Angle") and moves it: makes the Sprite with "Platafaorma" begin to shake and get out of place.

(The idea is for the "rectangle" sprite to move freely while containing a slight angle tilt and for the objects above to not fall or slip)

**Comment by AshleyScirra** [comment]
These kinds of cases are very difficult to deal with. You're essentially teleporting a solid over a Platform behavior object, which causes it to try to find a way to escape the object that got moved in to it. The effect is more subtle in this case because you're using a slowly rotating object. Currently it's treating it as a moving wall hitting the player so it first attempts to move it out of the way horizontally, which is why it slides along. We can try to adjust this to try vertically first, but it may break other cases involving moving walls, in which case we might have to revert it. You should try to avoid designing games that move solids in to objects with behaviors that aren't allowed to be intersecting a solid.

**Comment by AshleyScirra** [comment]
I've got a change for the next release aimed at improving this case. I'm a bit worried it will cause other regressions but we'll see how it goes.

**Comment by alastajj** [comment]
I think this platformer slope issue may have been fixed incidently from this release too.

#1609
