### ISSUE TITLE
Use Worker crashes the editor when previewing 

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2428]
## Problem description

Use Worker crashes the editor when previewing in a tab with chrome debugging and the device toolbar
## Attach a .c3p

https://puu.sh/CfAva/72031036c0.c3p
## Steps to reproduce

1.preview the project
2.in the preview window or tab or whatever, open the console or debugger or whatchamucallit with ctrl+shift+j
3.in the console  click this button its call device toolbar i think it lets you see how the game runs on mobile 
![image](https://user-images.githubusercontent.com/32940085/49759905-01798a00-fc91-11e8-813d-5e25fe4a3fd4.png)
4. preview the game again so it previews in that window with the console opened

## Observed result
the console and the editor both crash

## Expected result

no crashes
## First affected release
it does that in r110 too when i tested it so i'm assuming it does that in all releases with webworker support

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
C3 release: r130 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 565 mb (3.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by eleanorawesome** [comment]
![image](https://user-images.githubusercontent.com/32940085/49897111-34538780-fe23-11e8-946f-e3c62513c37e.png)
![image](https://user-images.githubusercontent.com/32940085/49897135-4a614800-fe23-11e8-91ca-1fa0e8bc0be5.png)

r131 chrome 71
tested with the file i sent, and enabling use worker

**Comment by eleanorawesome** [comment]
same thing with canary 
![image](https://user-images.githubusercontent.com/32940085/49898542-4df6ce00-fe27-11e8-9b88-47dc2bda5ca0.png)
![image](https://user-images.githubusercontent.com/32940085/49898572-61a23480-fe27-11e8-9782-c463daa3b444.png)

**Comment by AshleyScirra** [comment]
"Aw snap" means the browser crashed, not Construct. So you'll need to report this type of issue to Google instead.
