### ISSUE TITLE
Cannot add more than 1 blank space in comments nor use Tab

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#243]
## Problem description

Cannot add more than 1 blank space in comments nor use the Tab key which is useful for indenting.

## Attach a .c3p

Attached with .zip extension
![commentbug](https://cloud.githubusercontent.com/assets/7268697/26198074/5514b4cc-3bcd-11e7-8623-7c49049f8d34.jpg)
[CommentBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1010518/CommentBug.c3p.zip)

## Steps to reproduce

1. Open a project
2. Add a comment with more than 1 space between words and also at the beginning before everything
3. Try adding a TAB

## Observed result

Spaces don't get rendered, they are still there if you double click on the comment to edit it.

## Expected result

I expect spaces to show up and for the TAB to actually add a TAB or the specific number of blank spaces.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Fixed for r29.
