### ISSUE TITLE
Video plugin not strecthing over the screen of the devices to fill the screen in Scale Outer mode.

### ISSUE THREAD

**Issue by sangeeth786** [Scirra/Construct-3-bugs#2430]
## Problem description

Construct 3 r130
All devices Android & IOS
Video plugin not stretching all over the screen of the device in Scale Outer mode.
but if i choose Scale Inner mode the video gets fullscreen **but Crops the Video.**

## Attach a .c3p
can't attach a file because the file is more than 10 MB

## Steps to reproduce

1. In C3 build project with option cordova, Xcode or debug APK for Android.
2. Build and run on IOS & Android devices.

## Observed result

Video not stretching all over the screen of devices but showing the background objects on its sides in Scale Outer mode.

## Expected result

Video to stretch all over the screen of devices (i.e. IOS & Android) and not to show the background objects in Scale Outer Mode.

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines regarding attaching a project. You can either use a smaller test video file to keep the file size down or use a different cloud file service.
