### ISSUE TITLE
Google Play Games Leaderboards [Submitting global variable]

### ISSUE THREAD

**Issue by Vultwo** [Scirra/Construct-3-bugs#2431]
## Problem description

Submitting a currency score to Google Play sends a wrong score. Possibly because the currency leaderboard requires a double or float?

## Attach a .c3p

No minimal .c3p available (game needs to be published).

## Steps to reproduce

1. Submit a number global variable to Google Play
2. Check score
3. Score displays incorrectly

## Observed result

The number displays incorrectly. Google Play displays currency units as 1/1.000.000 but even after multiplying the number by 1.000.000 the value is incorrect.

## Expected result

Global variable to be displayed as a currency in the leaderboard.

## First affected release

r130

## Affected browsers/platforms

Android signed release .apk: yes
* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
C3 release: r130 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 732 mb (1.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce 9500 GT Direct3D11 vs_4_0 ps_4_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_disjoint_timer_query
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Vultwo** [comment]
Numeric values get displayed wrong too. A submitted score of 31.200.000.000 gets displayed as 1.135.228.928 by Google.

**Comment by AshleyScirra** [comment]
We cannot confirm this is not just a mistake in your events if you do not provide a project.

Assigning to @shortercode in case you can glean anything from this, otherwise we will have to close as per our procedures.

**Comment by Vultwo** [comment]
@AshleyScirra I'm sorry for ignoring the guidelines, but there really is no other way of addressing this. Creating a 'fake' signed release .apk in the Google Developer Console with a minimal .c3p takes a very long time.

**Comment by shortercode** [comment]
How are you reading your scores? Just displaying the native leaderboard dialog or using request hi scores?

Looking at the documentation Google Play only accepts integers for scores, and returns integers.

**Comment by shortercode** [comment]
I can't see any obvious issues with the code, but I admit I'd only checked it with numerical values. I did note that changing a leaderboard type generally broke it. So creating new ones is advisable if your swapping.

It would be appreciated if you could provide a minimal project here, with details of how you set up your leaderboard.

**Comment by shortercode** [comment]
I believe I've recognised the issue after an email discussion with a user. We are reading values as int not long, so any value over ~2 billion will be truncated. Will publish the revision soon.

**Comment by shortercode** [comment]
Revision 1.0.14 has been published.
