### ISSUE TITLE
Scaling a single layer DOWN scales whole project.

### ISSUE THREAD

**Issue by andygilbert** [Scirra/Construct-3-bugs#2432]
## Problem description

When full screen mode is anything apart from 'off', when scaling a single layer SMALLER than 1 it scales the whole project. You can scale a single layer up and back to 1 without any issues, it is only when you scale the layer below 1.

## Attach a .c3p

[scalelayererror.zip](https://github.com/Scirra/Construct-3-bugs/files/2667175/scalelayererror.zip)

## Steps to reproduce

1. Open example, and test in browser. 
2. Press increase scale button to scale layer 1 UP (no issue)
3. Press decrease scale button to scale 1 DOWN (no issue until scale goes below 1)

## Observed result

The whole project scales instead of the just the single layer.

## Expected result

The single layer to be scaled, not the whole project.

## First affected release

r120

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes
* Safari: yes/no
*iOS native: yes

**Comment by AshleyScirra** [comment]
Please test the latest release (currently r130) to ensure you're not reporting bugs that have already been fixed.

**Comment by andygilbert** [comment]
Hi Ahsley, I have tested in the latest r130 release and the bug still remains.

**Comment by andygilbert** [comment]
Just to add, this happens in both C2 and C3 runtimes.

**Comment by AshleyScirra** [comment]
This is because "unbounded scrolling" is not enabled. Since you have bounded scrolling, the runtime will try to avoid anything outside the layout bounds ever becoming visible. Then you zoom out so more than the layout area is visible, which the runtime tries to prevent, but the situation is impossible. Just turn on "unbounded scrolling" in this case.
