### ISSUE TITLE
Event sheets list in the "Event sheet" property of a layout is not ordered alphabetically

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2433]
## Problem description

When you have a lot of event sheets in the project, and try to assign an event sheet to a layout in its property "Events sheet", the events sheets are ordered by last added instead of being in alphabetical order as in the project's bar.

## Attach a .c3p

https://kyatric.com/c3/bugs/2018.12.11.event_sheet_order.c3p

## Steps to reproduce

1. Open project
2. Select Layout 1
3. Check its "Event sheet" property

## Observed result

The Event sheets are ordered by they order of addition to the project

## Expected result

Ordered in alphabetical order, like in the project bar, in their own folder.

## First affected release

R 129, possibly prior to it as well.

## Affected browsers/platforms

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta release.
