### ISSUE TITLE
C3 Runtime "on collision with" issue

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#2434]
## Problem description

in some circumstances the "on collision" event does not trigger in C3 runtime. In C2 runtime it is no problem. It may also have to do with the combination of "on collision with"- "or"- "on collision with"
 another object. If I delete the working collision event out of the "or" block, the corrupted collision trigger starts to work.

## Attach a .c3p
[Bugtest12.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2667586/Bugtest12.c3p.zip)

## Steps to reproduce

1. Preview Project in C3 Runtime
2.
3.

## Observed result

Two combined squares move from left to right

## Expected result

on collision of blue square with red square, the red square should disappear

## First affected release

tested in r130 
sorry I cant check with the old releases, it refuses to open as it is saved in a newer version of C3

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_1
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
C3 release: r130 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 940 mb (3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)</details>

**Comment by AshleyScirra** [comment]
'OR' events are super complicated, so this may be hard work...

**Comment by SnipG** [comment]
Should fake triggers even work with OR? And if they are made to work, is there any perf gain over 2 seperate event?

**Comment by AshleyScirra** [comment]
>Should fake triggers even work with OR?

The various internal implementation details should not affect this. The typical user has no idea what a "fake trigger" is and there is no visible distinction for them inside Construct.

> And if they are made to work, is there any perf gain over 2 seperate event?

[Answer your own performance questions with measurements](https://www.construct.net/en/blogs/ashleys-blog-2/answer-your-own-performance-questions-with-measurements-925)

**Comment by AshleyScirra** [comment]
Minimal repro: [or-collision-bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2737724/or-collision-bug.zip)

**Comment by AshleyScirra** [comment]
Wasn't too bad in the end, should be fixed in the next release.
