### ISSUE TITLE
New version 130 can't preview my project

### ISSUE THREAD

**Issue by tuzke** [Scirra/Construct-3-bugs#2438]
## Problem description

New version 130 can't preview my project. It was open and working on new version 130 but when I preview the project it crashed.

## Steps to reproduce

1. preview the project
2.
3.

## Observed result

the console and the editor both crash

## Expected result

no crashes

## First affected release

I still open and preview the project with version 129 but when i switch to version 130 it fails

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: expected content
Stack: Error at Function.ǃO.ǃZyz (https://editor.construct.net/r130/main.js:2:142882) at e (https://editor.construct.net/r130/main.js:2:104265) at window.assert (https://editor.construct.net/r130/main.js:2:104590) at window.ǃOQa.ǃOuQ (https://editor.construct.net/r130/main.js:81:118084) at window.ǃOvj.ǃOuI (https://editor.construct.net/r130/main.js:81:112999) at window.ǃOvj.ǃOur (https://editor.construct.net/r130/main.js:81:112375)
Construct 3 version: r130
URL: https://editor.construct.net/r130/
Date: Wed Dec 12 2018 10:09:42 GMT+0700 (Indochina Time)
Uptime: 1154.7 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
C3 release: r130 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 740 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
As with #2429, it is impossible for us to help unless you provide more information. I offered my email address in the other issue in case you don't want to share your project. You should not simply re-file the same issue; I'm afraid reports like this are useless, there is simply nothing we can do about them due to the lack of information.
