### ISSUE TITLE
Video plugin not strecthing over the screen of the devices to fill the screen in Scale Outer mode.

### ISSUE THREAD

**Issue by sangeeth786** [Scirra/Construct-3-bugs#2439]
## Problem description

Construct 3 r130
All devices Android & IOS
Video plugin not stretching all over the screen of the device in Scale Outer mode.
but if i choose Scale Inner mode the video gets fullscreen **but Crops the Video.**

## Attach a .c3p

[videoscaleouterrr.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2670527/videoscaleouterrr.c3p.zip)

## Steps to reproduce

1.In C3 build project with option cordova, Xcode or debug APK for Android.
2.Build and run on IOS & Android devices.

## Observed result

Video not stretching all over the screen of devices but showing the background objects on its sides in Scale Outer mode.

## Expected result

Video to stretch all over the screen of devices (i.e. IOS & Android) and not to show the background objects in Scale Outer Mode.

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It appears to be working correctly. 'Scale outer' affects the viewport size, not the video size. And if the viewport is larger than the video, then the video won't fill the screen.

**Comment by sangeeth786** [comment]
@AshleyScirra 
My Viewport Size is exactly same to the Video Size but its the showing the background objects.
Viewport size :- 960*640
Video size :- 960*640
Fullscreen Mode :- Scale Outer

**Comment by AshleyScirra** [comment]
Scale outer and scale inner allow the aspect ratio of the viewport to change. See this tutorial: https://www.construct.net/en/tutorials/supporting-multiple-screen-sizes-17
