### ISSUE TITLE
Crash when moving comment block (cannot reproduce)

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#244]
## Problem description

When I moved a comment block above a group, C3 crashed with a crash dialogue. I could not reproduce this though, figured it could be of some use perhaps. Added the log in the view details.

## Steps to reproduce

1.
2.
3.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r28/main.js, line 61, col 312902
Message: Uncaught TypeError: Cannot read property 'ǃKo' of null
Stack: TypeError: Cannot read property 'ǃKo' of null at window.ǃKct.ǃKzC (https://editor.construct.net/r28/main.js:61:312902) at window.ǃKct.ǃKAT (https://editor.construct.net/r28/main.js:61:311987) at window.ǃHZw.accept (https://editor.construct.net/r28/main.js:61:263811) at ee.ǃKAl (https://editor.construct.net/r28/main.js:61:289246) at ee.accept (https://editor.construct.net/r28/main.js:61:263827) at ee.accept (https://editor.construct.net/r28/main.js:61:289171) at ee.ǃKAl (https://editor.construct.net/r28/main.js:61:283750) at ee.accept (https://editor.construct.net/r28/main.js:61:263827) at ee.ǃKAl (https://editor.construct.net/r28/main.js:61:270280) at ee.ǃKAl (https://editor.construct.net/r28/main.js:61:283784)
Construct 3 version: r28
URL: https://editor.construct.net/index.html
Date: Thu May 18 2017 14:09:05 GMT+0300 (GTB Daylight Time)
Uptime: 16592.9 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r28

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
It's not clear from the crash report why this is happening, so I'm afraid there's nothing to be done unless you can find steps to reproduce.
