### ISSUE TITLE
few action-conditions in MobileIAP plugin not working

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2440]
## Problem description

I have tried this plugin everything fine except few things not working

- Restore Purchase not working
- Condition "Has product" not checking if product is already purchased.

## Attach a .c3p
.c3p file i can share only in private. Please tell me where i can send my c3p file (If you really need that).

## Steps to reproduce

1. Create Buy, Restore buttons
2. After buying try to check status weather purchased or not.
3. also try to restore purchases. 

## Observed result

nothing happens when checking buy Status and restoring purchases.

## Expected result

its should show Status about buy and should restore our purchases when reinstall app.

## First affected release
I never did before in any release.

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
@luckyrawatlucky is this specific to a runtime? Which platform are you testing on?

**Comment by shortercode** [comment]
Android doesn't require purchase restoration, it's dealt with at a service level.

**Comment by luckyrawatlucky** [comment]
but what about Condition "Has product" which not checking if product is already purchased.

**Comment by shortercode** [comment]
That should be working, but it will be quite time consuming for me to test so I just want to make sure I have all the information before testing it.

If you could provide an outline of your eventsheet for me and what types of purchases you are using that would be very helpful. Also you didn't answer my question about which runtime this effects, is it both?

**Comment by luckyrawatlucky** [comment]
did you found the these issues too or do you want more information ?
Please Let me know.

**Comment by BrandonWhitton** [comment]
There is a definite bug with regard to checking whether a product has been purchased. 
![IAP](https://user-images.githubusercontent.com/13290448/56425295-f1388200-62f6-11e9-8399-263302f2a88d.jpg)

I am using the C2 runtime and am exporting for iOS via Xcode. I have used similar code to the attached image in a number of live apps on the App Store. I have recently been made aware that someone purchasing one of my IAP's has been unable to restore their purchases. The issue seems to relate to the IAP plugin not properly querying the appstore on whether a product has been previously purchased. I use the  - Has Product "ProductID" -  to determine whether the product has been previously purchased and then set a variable which unlocks parts of the app. When the "Has Product" fails to query properly it essentially breaks the functionality of the app. This is a major problem to me and it seems to be a bug that is affecting others too. It would be good for this to be investigated promptly.

**Comment by kingpirux** [comment]
same problem here :(

**Comment by CliffOnCrypto** [comment]
Same Problem here!

**Comment by luckyrawatlucky** [comment]
@shortercode  this issue is still pending.  Condition "Has product" not checking if product is already purchased.

**Comment by shortercode** [comment]
I'm doing some testing for the plugin for a new update today, I will look into this while I'm at it.

**Comment by kingpirux** [comment]
actually it's working fine in the last days, maybe its because i do the export in android studio with all the dependencies updated for the gradle

**Comment by shortercode** [comment]
Well I updated the cordova plugin on Tuesday I think it was, but the stable and beta channels won't be using that version yet. I'm still testing it but I'm not aware of any show stopping issues with it, so you can use it if you want `construct-mobile-purchase@1.2.0`. Also there's a number of small patches to the Object runtime I'm going to add at the start of the next beta cycle.

**Comment by shortercode** [comment]
Okay so following my testing I have resolved the following bugs:
- registration success was not being triggered in the C3 runtime
- purchase fail was sometimes not being triggered in either runtime
- product availability was being triggered twice during startup of the C3 runtime 

I reviewed the situation with "Has Product", and it appears to be working. But with a fairly confusing caveat. That is **at the time registration is deemed complete; owned products are marked as available and not owned**. After a short delay these transition to owned. If you check product ownership immediately after registration completion this can cause some major confusion. I don't think there is a robust correction I can apply to the plugin at this time. The only modification that comes to mind is to delay registration completion by an arbitrary amount of time, and hope it has settled. Which could still produce incorrect results. Hence it's something that users will have to be aware of for the time being. To improve the situation I've added the triggers "on product owned" and "on any product owned" which will hopefully help.

These changes will be in the next beta release, which will probably be next Monday. If additional work is required I intend to resolve it during this release cycle, so feedback is appreciated.

**Comment by AshleyScirra** [comment]
r172 is now out, please confirm if issue is resolved.

**Comment by luckyrawatlucky** [comment]
"on product owned" didn't worked here for me 
owned products showing as available, not showing as owned.

**Comment by shortercode** [comment]
@luckyrawatlucky on what platform please?

**Comment by luckyrawatlucky** [comment]
Android

**Comment by shortercode** [comment]
Strange, that was my primary test platform. Are you sure they are never firing? As I noted above there is an unfortunate situation that owned products will appear as "available" for a short duration after registration. This was my primary reason for adding the "on owned" triggers.

**Comment by BrandonWhitton** [comment]
I'm glad this is being looked into given how long this problem was ignored. For me though, this is too little, too late. This was a major issue to me and I'm sure for most Construct 3 developers with apps being sold.  I've long since ceased development with Construct 3 due to this and other similar issues and have moved to  a more reliable development platform (Swift). Good luck though with this. I hope it gets resolved properly.

**Comment by luckyrawatlucky** [comment]
@shortercode 
i tried "on product owned" then set  text to "product purchased". and also did set alert for this
but nothing happened. even i did purchase again and still it doesn't triggered. 
![iap](https://user-images.githubusercontent.com/17684135/67258475-72432280-f4ae-11e9-91a1-f3cf2864cbeb.png)

**Comment by shortercode** [comment]
@luckyrawatlucky could you post a brief example project for that use flow so I could take a look?

**Comment by luckyrawatlucky** [comment]
[example file.zip](https://github.com/Scirra/Construct-3-bugs/files/3755245/IAP.zip)

**Comment by shortercode** [comment]
@luckyrawatlucky your product type is marked "consumable" is this as you intended?

**Comment by luckyrawatlucky** [comment]
My product type is non-consumable (so that purchase can be made only once to remove ads)

**Comment by shortercode** [comment]
Okay but it's set as "consumable" in the project you sent. I will change it
to non-consumable.

**Comment by shortercode** [comment]
When changed to "non-consumable" your project behaves as I would expect. Although it is setting the user personalisation state every frame...

**Comment by luckyrawatlucky** [comment]
my only purpose is to remove ads from app after purchase. can you guide me how can i achieve this? or can you update my example file?

**Comment by shortercode** [comment]
Change the product type to "non-consumable"

**Comment by luckyrawatlucky** [comment]
I found it working now. Thanks
