### ISSUE TITLE
Build Service Fails To Export Project!

### ISSUE THREAD

**Issue by drg8** [Scirra/Construct-3-bugs#2441]
## Problem description

my project is 26MB in size and whenever I try to export it via Android Studio Project, Debug APK or Signed APK it fails to export successfully (also fails with/ without selecting deduplicate, recompress and minify).

 most of the time it says "lost connection to build server" even when the transfer progress is at 100%. "can't connect to build servers" dialog pop's up a few seconds later.

desktop build and browser version both have same issue, deleted construct's user data from AppData folder too but it didn't fix the issue.

when exporting small projects the "lost connection to build server" status is shown once or twice, but the project is exported successfully.
I'm unable to test my project and experiencing this issue since last 4 days.

## Attach a .c3p
you already have previous project :D. if still required I'll email it to you.

## Steps to reproduce

1. try to export with debug, signed & android studio project options.

## Observed result

1) lost connection to build server, retrying in 5 seconds ( )
   Build Service: Transfer Progress 100% (every time it fails at 100% progress)

2) can't connect to build servers - dialog pop's up when export fails.

## Expected result

Project should get exported successfully

## First affected release

r129 
## Affected browsers/platforms

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Who did you send the project to? Might be easier just to send it again, I generally delete projects I receive after around a week ( we get quite a lot ).

**Comment by shortercode** [comment]
Sometimes the build server will disconnect if there is an error in the build, which can cause these re-connection loops ( until the retry count is maxed out ).

**Comment by drg8** [comment]
Ashley has my previous project. I was able to export the project successfully 2 days ago (after failing few times).
I don't have your email to send the project.

**Comment by shortercode** [comment]
iain@scirra.com

**Comment by drg8** [comment]
just sent you email with subject "Project Files to Test Build Service Export Failure!"

**Comment by drg8** [comment]
I just tested the old version of my project and it is also failing to export :/

**Comment by shortercode** [comment]
How long does it take for your project to upload? I'm not having any issues at the moment with either project in my debug environment. I'll try r129 next

**Comment by drg8** [comment]
for me 2minutes to upload, my internet is 4mbits up&down

**Comment by drg8** [comment]
may be project is taking longer to upload and hence my pc is unable to maintain proper connection with build server :? but also it was working without any issues earlier :??

**Comment by shortercode** [comment]
The build server should allow connection recovery at any stage of the build. Within reasonable time limits anyway. I had noticed that people are being kicked from queues far too quickly so it could just be that we've been too busy and it's resulting in your build failing. That code is kind of hard to test unfortunately... and very timing related.

I just tried with r131, my first attempt failed because of some network glitch getting runtime code. Seems to be working now though, could you try again? If it does fail could you take a look at the browser console and tell me whats being printed?

**Comment by drg8** [comment]
it was failing on r131 because I didn't saved it with latest build :D, now same issue continues "cant connect to build servers"

**Comment by drg8** [comment]
idk why but transfer progress is much slower than before :/ , here's the console image [console image](http://prntscr.com/lu0nab)

**Comment by shortercode** [comment]
Mmmm suggests that you might be having some general network trouble, C3 also failed to connect to the account service there. The connected message is triggered when the connection is successfully opened to the build server, but it doesn't say how long that connection lasts or if the server actually responds. You don't even get as far as a queue...

**Comment by drg8** [comment]
hey I've sent you an email with all the details you requested.

**Comment by shortercode** [comment]
Thanks, just finished reviewing the build logs. Unfortunately the logs didn't have much information. Although your connections are a bit unusual.

By the looks of it the connection is established, it does nothing for just over 2 minutes then disconnects. Then we terminate the session not long after. Then whats unusual is that a new connection comes in before the 2 minutes have completed, but doesn't attempt to reconnect to the session.

I'm guessing that although the connection is made no information is passed between the server and the client. The connection fails but neither half is aware, then eventually individually time out. If that's so then there's a problem between your computer and the server.

Do you use a proxy or a VPN at all? Might be that they are having issues with the traffic type.

**Comment by drg8** [comment]
I don't use any proxy or vpn. I just successfully exported the project with my mobile data which took over 45minutes (network issues ^_^! ) so indeed something is wrong with my internet connection. will test with some free vpn to see if it works or not.

**Comment by drg8** [comment]
Update: I just tried betternet vpn and the export is working without any connection issues :D .

**Comment by shortercode** [comment]
I'm glad to hear! Networking issues can be hard to track down, but hopefully it's just a temporary glitch with your ISP or something.

We can't do much more for you at this point, so I'm going to close this issue.
