### ISSUE TITLE
(C3 Editor) Event sheets' UI states are erased when closing project (if closed)

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#2443]
## Problem description

If you close and reopen a project, any event sheets that were not open revert to the default UI state.

## Attach a .c3p

Can use a blank .c3p

## Steps to reproduce

1. Open project and place some events. Adjust event width or collapse/expand groups.
2. Close event sheet & save project
3. Open project

## Observed result

Event sheet's UI state has reverted to default.

## Expected result

Event sheet's UI state should have stayed as I left it.

## First affected release

r131, probably all previous releases.

**Comment by AshleyScirra** [comment]
Should be fixed in the next release.
