### ISSUE TITLE
(C3 Editor) Issue with highlighting text with mouse

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#2444]
## Problem description

In, say, the expression editor, if you highlight some text with a left mouse click/hold, but then move the mouse outside the window, the text will become unhighlighted.

## Attach a .c3p

.c3p not needed

## Steps to reproduce

1. Type some text into the expression editor.
2. Using the left mouse button, highlight some text from right to left.
3. Keep moving the mouse left until it is outside the window.

## Observed result

The text becomes unhighlighted

## Expected result

The text should stay highlighted

**Comment by AshleyScirra** [comment]
Closing as this is a Chrome issue so will follow up at crbug.com/854637
