### ISSUE TITLE
Animations editor - tring to undo resize will scale bounding box wrong

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2448]
## Problem description

You resize 2 frames seperatly, undo won't correctly restore collision polygon.

## Attach a .c3p

[New project (4).zip](https://github.com/Scirra/Construct-3-bugs/files/2674000/New.project.4.zip)

## Steps to reproduce

1.Open example
2.Open sprite, select frame 2. Resize it from 100x100 to 200x200
3.Select frame 1, resize it to 200x200. Exit animation editor
4.Click undo, open editor, see frame 1 has wrong collision polygon.

## Observed result

IF frames are resized seperatly, undo won't undo correctly

## Expected result

Undo to work correctly

## First affected release
127

## Affected browsers/platforms

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed in the next release.
