### ISSUE TITLE
Save / Load issue (C3 runtime only)

### ISSUE THREAD

**Issue by kyleol** [Scirra/Construct-3-bugs#2449]
## Problem description

Hi, Construct Team.
 
 I got an issue on save and load, ( c3p link below ).
 
 When game start on worldmap, game will be auto saved.
 
 Player click the yellow dot, then click[ yes], will enter the next layout,
 
 then click [pause]icon on layout will load back to world map's save file.
 
 but when you repeat doing this 2-3 times, the [yes][no] buttons won't spawn out anymore.
 
 (same issue happened to my project with enemies, they disappeared or game freezed on enemy defeated after loading.)
 
 I have no clue why this happened,
 
 My game is almost done , but stuck on this save and load issue :(
 
 
 Really need help on this one. Thank you!
 

## Attach a .c3p

drive.google.com/file/d/1st9xWUxQLXPo4k-BNrhCcL9V56KHr6R6/view

## Steps to reproduce

1, click yellow dot on world map to enter next level
2, click pause to load world map save
3, repeat this 2-3 times, [yes][no] buttons on world map layout won't spawn

## Observed result

[yes][no] buttons on world map layout won't spawn

## Expected result
[yes][no] buttons on world map layout should spawn

## First affected release
r129

## Affected browsers/platforms

* Chrome: yes
* Safari: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 12.0.1
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_1
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15
C3 release: r131 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (2.1 INTEL-12.2.18)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) UHD Graphics 617
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_blend_minmax
EXT_sRGB
EXT_frag_depth
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBGL_compressed_texture_s3tc
WEBGL_depth_texture
WEBGL_draw_buffers
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 48000 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here - it works like this for me in both runtimes:

1. Click yellow dot on map
2. Prompt "Enter?" appears; click "Yes"
3. Click pause button, loops back to step 1

Did this 10 times in a row, worked every time.

I'm afraid we can't help unless we can observe the problem. Try finding a way to more reliably reproduce it.
