### ISSUE TITLE
can't set animation speed above 60

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2450]
When I try to set the animation speed to 75 in the animation editor, it caps it at 60.

Even when I set the animation speed in events to 150, I notice no difference than when it was 60.

Yet the framerate is not capped at 60, so I'm not sure what's going on here.

Using desktop build.

**Comment by AshleyScirra** [comment]
This is currently by design: currently animations cannot advance more than one frame per tick, so setting a framerate above 60 will have no effect on widespread 60 Hz displays.

**Comment by alastajj** [comment]
it should play it faster but skip some frames on devices where the framerate is below the animation speed
