### ISSUE TITLE
Worker mode - stretching screen causes high Gpu use and Gc won't clean it.

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2451]
## Problem description
This most likely need issue report to chrome, but i make one here first.
When don't use worker and you stretch window from small to large with mouse. Gpu will go for example 60,000k - to 150,000k+ but soon after GC will push it back down and you end up 70,000k gpu.
But when using worker mode, gpu memory stays super high. Could be how worker mode works, but if you use maximize button , gpu memory use will be 50% lower.

## Attach a .c3p
[WorkerGpuMem.zip](https://github.com/Scirra/Construct-3-bugs/files/2676923/WorkerGpuMem.zip)

## Steps to reproduce
1.Preview example, maximize window.
2.See low gpu memory use, close preview
3.Preview example, strech window small, then strech it max
4. See high gpu memory, you can double-tap to add sprites, gpu memory stays high

## Observed result
When using worker and streching chrome window by small increments, will cause high gpu use and leaked gpu memory won't get collected by Gc.

Image, when clicked preview and maximize: 95,000k
![kuvatommis 133](https://user-images.githubusercontent.com/28864889/49954528-57586700-ff09-11e8-8e05-89153e55b0cf.png)

Image, when preview is stretched small and then back max: 174,000k
![kuvatommis 134](https://user-images.githubusercontent.com/28864889/49954555-66d7b000-ff09-11e8-8d7a-6332545c32bb.png)

## Expected result
No bugs.

## First affected release
NaN
## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 989 mb (7.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Did you test Chrome 72? You should only test worker mode with 72+ due to known bugs in prior versions. That's why it's still behind the experimental setting.

**Comment by SnipG** [comment]
I used chrome dev, its 72.
https://snipg.github.io/Bugs/WorkerGpu/

Clean dev open, maximize.
![kuvatommis 139](https://user-images.githubusercontent.com/28864889/49958665-2cbfdb80-ff14-11e8-8cc6-f4c868bc76bd.png)


Chrome dev, resize super small then back max again:
![kuvatommis 138](https://user-images.githubusercontent.com/28864889/49958697-3ea17e80-ff14-11e8-9fb4-9100f1426f83.png)

**Comment by SnipG** [comment]
Worker in 72 has one other bug also, that will make anything that moves sprites by small increments like new tween plugin, very bad to use when fps drops below 60.  Sprites will start to stutter/shake alot, havent done bug report yet, need better example and some testing.....

**Comment by SnipG** [comment]
Made chrome report: http://crbug.com/915255
