### ISSUE TITLE
Strange thing happening when project switched from C2 runtime to C3 runtime.

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2453]
## Problem description
I have made video on what is actually happening. I don't know how to explain this issue.
and I can't share my project here publicly but if you want I can share it private at your email ID.  
[Video Link](https://youtu.be/5ob0vam2XR8)
## Attach a .c3p

I can share my C3p file only in private.

**Comment by AshleyScirra** [comment]
Sorry, there's nothing we can do about reports like this, please see the bug report guidelines.
