### ISSUE TITLE
Multiplayer Using my own signalling server doesn't work

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2454]
## Problem description

using my own signalling server dosen'T seem to work
## Attach a .c3p

https://puu.sh/ChFEs/fd0db7829b.c3p
## Steps to reproduce

1.remote preview and connect to the game with at least 2 players

## Observed result

the host connects to the signalling server just fine and hosts the game, but when a peer joins the console throws an error 
![image](https://user-images.githubusercontent.com/32940085/50026599-87f6da00-ffb7-11e8-80a7-33ce11439a93.png)
![image](https://user-images.githubusercontent.com/32940085/50026660-bd9bc300-ffb7-11e8-8dd9-c73da11387b4.png)

## Expected result

I expect it to work just like when using scirra's signalling server
## Affected browsers/platforms

* Chrome: yes
affects both c2 and c3 runtime

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 531 mb (3.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The error refers to `WrappedRTCPeerConnection`, which I don't recognise as being any part of the official client or server. What exactly are you doing? If you've modified the server to use other libraries, I'm afraid we cannot provide support for that, you'd need to contact those library authors.

**Comment by eleanorawesome** [comment]
I haven't modified the server, I can email you the files if you want.

**Comment by eleanorawesome** [comment]
Ubuntu 18.04.1 LTS
nodejs v8.10.0
colors 1.3.3
ws 6.1.2

**Comment by eleanorawesome** [comment]
firefox throws these errors 
![image](https://user-images.githubusercontent.com/32940085/50059520-e8238280-0155-11e9-8dca-9ee5f4f259da.png)

**Comment by eleanorawesome** [comment]
Ok so I removed some STUN/TURN servers so that it would be below 5 and now it works

**Comment by eleanorawesome** [comment]
Is there a non minified version of the server so that I can request turn server credentials through an API instead of hard-coding them in?

**Comment by AshleyScirra** [comment]
OK, closing as seems to be just a STUN/TURN configuration issue.

If you're talking about STUN/TURN credentials, those are handled by the STUN/TURN server, not the signalling server.
