### ISSUE TITLE
Tween behavior does not listen to 'set object timescale'

### ISSUE THREAD

**Issue by rilem** [Scirra/Construct-3-bugs#2456]
## Problem description

Tween behavior does not listen to 'set object timescale'. 
Game running at 0.1 timescale and object set to 1.0 results in object listening to game timescale.

## Attach a .c3p

.c3p is blocked by github, zipped it
[tween-timescale.zip](https://github.com/Scirra/Construct-3-bugs/files/2682717/tween-timescale.zip)

## Steps to reproduce

1. set timescale
2. set object timescale
3. start tween

## Observed result

slow game object.

## Expected result

normal speed gameobject

## First affected release

r131 stable

**Comment by DiegoScirra** [comment]
Fixed in the next release.
