### ISSUE TITLE
[C3Runtime][SDK][Cordova Library] C3Runtime has issues loading some cordova libraries.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#2457]
## Problem description

The **Test Project** will work on **C2Runtime** but not on **C3Runtime**.
The problem is that, it isn't within my control to workaround. I'm receiving **C3Runtime Errors** even without calling any events.

![report image](https://user-images.githubusercontent.com/31282960/50056788-9c47fc00-019c-11e9-90d8-9100f0f429b3.png)

The functions getting an error, are really not within my control anymore, and seems that it needs some **reviewing**.

I'm using the **cordova plugin**, **cordova-plugin-facebook4**. Also, you can't build on the **C3 Build Service**, because the **config.xml** requires this:

```
========================================================
<plugin name="cordova-plugin-facebook4" >
    <param name="APP_ID" value="(Insert Value)" />
    <param name="APP_NAME" value="(Insert Value)" />
</plugin>
========================================================
```
Since, it configures the **Facebook Credentials** on **build**.

But no worries, I already made you a **Report.zip** where you can just import to **Phonegap**. It contains no events like the **Report.c3p**. The **Report.zip** is an export from the **Report.c3p** that already has a **config.xml** that is already configured.

## Attach a .c3p

I have sent a **Debugging Package** through **support@scirra.com**.
For further easy identification, I have included a **Note** that references here. 
(The package contain private information, that I don't want to be made public).

#### C3Runtime Package [Issue] [From Scratch]
1. Open **Report.c3p** on Construct 3 r131.
2. Export to **Android** as **Cordova Project**.
3. Extract the **exported .zip** and replace with the provided **config.xml**.
4. Build on **Phonegap**.
5. Install the **.apk** on Android.
6. It results in a **black screen**.
7. Set Developer Options to **On**.
8. Turn **On** USB Debugging.
9. Debug your android phone with **chrome://inspect/#devices**.
10. See the **C3Runtime error references**. Which is out of the SDK user's control.

#### C3Runtime Package [Issue] [Pre-Made :: 1]
1. Import the **Report.zip** provided in the **Debugging Package**, on Phonegap.
2. Build on **Phonegap**.
3. Install the **.apk** on Android.
4. It results in a **black screen**.
5. Set Developer Options to **On**.
6. Turn **On** USB Debugging.
7. Debug your android phone with **chrome://inspect/#devices**.
8. See the **C3Runtime error references**. Which is out of the SDK user's control.

#### C3Runtime Package [Issue] [Pre-Made :: 2]
1. Install the provided **.apk** from the **Debugging Package**, on Android.
2. It results in a **black screen**.
3. Set Developer Options to **On**.
4. Turn **On** USB Debugging.
5. Debug your android phone with **chrome://inspect/#devices**.
6. See the **C3Runtime error references**. Which is out of the SDK user's control.

## Observed result

A **Runtime Error** on **C3Runtime**.
![report image](https://user-images.githubusercontent.com/31282960/50056850-a1597b00-019d-11e9-80e3-1909a4764c14.png)
(Similar to the image above)

## Expected result

To work just like on **C2Runtime**.

## System details

**Construct 3 :: r131**

## Additional Notes

Remember, **Cordova CLI** or **Phonegap** only.
Thank you in advance for the time.

**Comment by AshleyScirra** [comment]
I'm afraid we can't take responsibility for supporting third-party Cordova plugins. FYI the error reported is with WebGL, nothing to do with Cordova, but is simply using a normal browser function; I suspect the Cordova plugin is overriding or otherwise breaking some browser functions.

If the problem only occurs with cordova-plugin-facebook4, please report it to that plugin's developer. If the problem occurs without the plugin, please file an issue demonstrating the problem without the use of the plugin.
