### ISSUE TITLE
Undock layout/eventsheet crashed "Open to popup window" if still in loading

### ISSUE THREAD

**Issue by Silversen** [Scirra/Construct-3-bugs#2458]
## Problem description

Undock layout/eventsheet crashed "Open to popup window" if still in loading
## Attach a .c3p

No simply .c3p attached, because this error appear when open project Demonoire from editor Start page-Game Example
this link show snapshot of error images
https://www.dropbox.com/s/nd6ecsvr83xymz6/C3%20r131%20ERROR%20Demonoire.png?dl=0

## Steps to reproduce

1. Open Demonoire project from Startpage - Game Examples
2. Undock any event sheet or layout
3. Choose "Open to popup window"
4. Popup window appeared but still loading
5. When the popup still loading, Choose "open to popup window" again
6. Crash message box appear

## Observed result

Crash with message box "Oops! Something went wrong ... ... ..."
Screenshot attached in c3p section

## Expected result

Not crash. It should contain error execption handling if waiting for "loading layout" too long

## First affected release

Stable version r131

## Affected browsers/platforms

* Chrome: yes
* Firefox: no tested
* Edge: no tested
* Safari: not tested

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r131/main.js, line 2, col 348170
Message: Uncaught Error: already awaiting popup window
Stack: Error: already awaiting popup window at ǃu.ǃA.ǃM.ǃHrc.ǃvX (https://editor.construct.net/r131/main.js:2:348176) at ǃu.ǃA.ǃuf.ǃuym.ǃu.ǃHH.ǃMt.ǃHKR.n.ǃuQ [as ǃuHz] (https://editor.construct.net/r131/main.js:2:350408) at ǃu.ǃA.ǃuf.ǃuym.ǃ_p (https://editor.construct.net/r131/main.js:52:40007) at HTMLElement.ǃjG (https://editor.construct.net/r131/main.js:52:37841) at HTMLDocument. (https://editor.construct.net/r131/main.js:2:200108)
Construct 3 version: r131
URL: https://editor.construct.net/
Date: 
Uptime: 847.7 s

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next release.
