### ISSUE TITLE
Projet saved on r120 crashes when loading is complete.

### ISSUE THREAD

**Issue by ACC-Math** [Scirra/Construct-3-bugs#2459]
## Problem description

I have a project that was first released with c3 r96, and recently modified with r120. It worked fine on both but now when I try to open it, I am getting the "Aw, Snap" error instead of a webpage because Chrome is having problems loading.

After opening the project with FireFox, I could manage to find what is making the loading crash in Chrome :
It's a CSV "Load table" parameter for Rex plugin which I load in an Event Sheet. It contains 500+ lines and it's size is 136kb.

## Attach a .c3p

[simpleCSV.zip](https://github.com/Scirra/Construct-3-bugs/files/2686153/simpleCSV.zip)

## Steps to reproduce

Open the project, wait for the opening prompt to end, wait for 1/2 second and then automatically the error message appears.

## Observed result
![capture d ecran 2018-12-17 10 40 14](https://user-images.githubusercontent.com/38421222/50078799-31bcad80-01e8-11e9-8426-2ce748383db2.png)

## Expected result

Open the last opened page of this project.

## First affected release

Error happens with r131 / 120 / 111

## Affected browsers/platforms

Crash happens in downloaded Construct 3 app and on Google Chrome.
It does not happen on FireFox on the same computer.

## System details

Windows 7 64 bits professional with 8Gb of DDR3 ram

**Comment by squalinho** [comment]
Same problem here Si tu thé same projet file. Can not open the project, Construct crash.

**Comment by shortercode** [comment]
We don't have enough information here to reproduce this issue.

Please detail how the project is saved, and how you are opening it. Also provide the system details ( can be found in the about dialog ). If you can repeat this with a minimal project then please provide that and reproduction steps.

**Comment by AshleyScirra** [comment]
It looks like you've pasted an entire file in to an event. Don't do that, use project files instead. We won't support such inefficient alternatives.
