### ISSUE TITLE
imagePoint was blocked by the sprite fill at Animations Editor

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#2461]
## Problem description

imagePoint was blocked by the sprite fill at Animations Editor

![imagepoint_bug](https://user-images.githubusercontent.com/45864744/50088314-a0782600-023d-11e9-94a3-1b0b4f312d7a.gif)

## Attach a .c3p
[imagepoint_bug[c3p].zip](https://github.com/Scirra/Construct-3-bugs/files/2686063/imagepoint_bug.c3p.zip)

## Steps to reproduce
1. Draw a Rectangle. 
2. Crop transparent edges.

## Observed result
imagePoint was blocked by the sprite 

## Expected result
imagePoint at the top
![imagepoint_ok](https://user-images.githubusercontent.com/45864744/50088932-5a23c680-023f-11e9-892e-a05740f5d1dc.gif)

**Comment by DiegoScirra** [comment]
Fixed.
