### ISSUE TITLE
Can´t Save or Load

### ISSUE THREAD

**Issue by Nekodex777** [Scirra/Construct-3-bugs#2462]
## Problem description

I can not save or load because every time I try it gives an error, when i try to save or load in Cloud, it says "Failed to update file list"/ when i try to save on browser it says "entry already exists [...]"

## Attach a .c3p

its a software issue, not the project

## Steps to reproduce

1.Go to Project
2.Save as
3.Save on Cloud/Save on browser
4.Be sad :(

## Observed result

it **doesn't** save

## Expected result

Save the Project

## First affected release

Construct 3 Stable R131

## Affected browsers/platforms

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details>
Platform information
Browser: Chrome
Browser version: 70.0.3538.110
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 84 mb
Storage usage (approx): 84 mb (100%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by shortercode** [comment]
The "Failed to update file list" in the desktop build has been resolved, please refer to #2408. If you update to the latest version of the client linked in that bug it should be resolved.

As for the other error as far as I can tell it can only be triggered by a browser save, not a cloud save. Could you give me a complete replication for that issue?

**Comment by shortercode** [comment]
Closing as inactive. Please file a new issue if the bug still exists.
