### ISSUE TITLE
editor.construct.net clashes with kaspersky

### ISSUE THREAD

**Issue by NoSoul8** [Scirra/Construct-3-bugs#2465]
## Problem description

Kaspersky free antivirus somehow blocks launching C3 at https://editor.construct.net

I've tried to manually whitelist editor.construct.net and construct.net but it didn't help.

https://editor.construct.net/r131 works fine with no issues from kaspersky.

## Attach a .c3p

Not needed

## Steps to reproduce

1. Go to https://editor.construct.net with Kaspersky free antivirus running version: 19.0.0.1088(d) 18.12.2018 7:56
2. Check the results 
3. Go to https://editor.construct.net/r131 with Kaspersky free antivirus running
4. Check the results

## Observed result

At step 2, C3 fails to launch, made screenshots of top and bottom of the console:

![c3kasper1](https://user-images.githubusercontent.com/34763413/50135314-2e3f2a00-02ad-11e9-869a-631844d35f85.PNG)

![c3kasper2](https://user-images.githubusercontent.com/34763413/50135316-3008ed80-02ad-11e9-92d1-06d101dcd0fe.PNG)

At step 4 C3 runs as usual

## Expected result

C3 runs as usual at https://editor.construct.net

## First affected release

r131

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 33 gb
Storage usage (approx): 1.1 gb (3.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Sorry, this is a problem with Kaspersky, so you'll need to take it up with them.
