### ISSUE TITLE
[Request] Add accessor for DOMHandlerClasses

### ISSUE THREAD

**Issue by irphilli** [Scirra/Construct-3-bugs#2467]
## Problem description

I'm working on a project where I'm looking to override a couple classes and it would be helpful if we could somehow access / modify the DOMHandlerClasses variable (currently ```l``` within ```RuntimeInterface```).

Here's one suggestion on what could work:
* The variable for DOMHandlerClasses no longer declared as a constant
* Additional method added to ```RuntimeInterface```:
```javascript
static FilterDOMHandlerClasses(a) {
    l = l.filter(a)
}
```

**Comment by AshleyScirra** [comment]
Please post suggestions to the suggestion platform, or discuss them in the forum. You should include a complete description of the rationale and use cases, because so far I cannot see any reason why this would be necessary.
