### ISSUE TITLE
Editor not responding to touch on smartphones since R129

### ISSUE THREAD

**Issue by SantiagoEstrade** [Scirra/Construct-3-bugs#2469]
## Problem description

As I have been told from other members and I myself have been able to test, from R129 on (R128 did not have the bug yet), the editor is not responding to touch when working on smartphones. I am not talking about the touch plugin, but the touch input of the editor when trying to add an object, select it, move it, resize, scroll the screen or zoom it... This happens just on layouts, it actually lets you work on the event sheets.

## Attach a .c3p

https://1drv.ms/u/s!AojCIgmN1VlPgYRCCWfLdH6vKTZRmg

## Steps to reproduce

No steps needed. Just open the c3p (which is an empty project, for I cannot even double tap to add an object and start working) with a smartphone and try to do something.

1. open the example on a smartphone
2. double tap on layout to add an object: nothing
3. zoom the layout: nothing
4. scroll the screen: nothing
5. create a blank project on PC by yourself and add any object with an instance on the layout. Go to the smartphone, open the project and try to tap the object to select it and work with it: nothing

## Observed result

Finger is not acting as input on layout screens when in the editor on a smartphone.

## Expected result

I should be able to work on my smartphone, as per R128 and every previous version.

## First affected release

R129

## Affected browsers/platforms

Chrome on Android (WebGL supported)
Tested on Moto G6, Samsung Galaxy S6, Samsung Galaxy S9, Samsung Tab A, Sony Xperia ZX, Huawei Nova

* Chrome: affected
* Firefox: -
* Edge: -
* Safari: -

## System details

Platform information
Browser: Chrome
Browser version: 71.0.3578.99
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Android
Operating system version: 8.0.0
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2.625
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 8.0.0; SM-G965F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 3.5 gb
Storage usage (approx): 123 mb (3.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2 is currently disabled on Android due to reports of GPU driver bugs.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: ARM
Renderer: Mali-G72
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1024
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_sRGB
OES_element_index_uint
OES_standard_derivatives
OES_vertex_array_object
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
After looking in to this it seems that the fix for #2393 that went out in r129 included a change that caused this regression. Now the Z order bar is hit-testing touches even though it's not visible, which blocks things like zooming the layout view. Assigning to @DiegoScirra to find an alternative fix for the previous issue that also fixes this regression.

**Comment by DiegoScirra** [comment]
This should be fixed in the next release.

**Comment by SantiagoEstrade** [comment]
Thanks so much for the effort. It's nice to see how you guys handle this
kind of stuff. Really appreciate your work.

And btw, the new Z elevation is outstanding! I've come already to dozens of
different spicy ideas to implement it on my games.

Have a nice year and keep on, you're doing great!
