### ISSUE TITLE
[r28] "Replace object" remains remnants of previous object reference

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#247]
## Problem description
This is a hard to spot one and it drives me crazy for about an hour figuring it out. Hopefully by following the steps you could understand the underlying problem, because I don't know how to explain this.

## Steps to reproduce

1. Create a Sprite object and Touch object.
2. Make an event:

`+ Touch: On touched Sprite
-> Sprite: Set X to Sprite.​X+​10
`

3. Now create a second Sprite.
4. Duplicate that event that we just created.
5. Select the entire event block (Not just the triggers nor just the actions) of the duplicated event.
6. Right-click and click "Replace Object".
7. Choose the second Sprite we created for this replacement.
8. Preview and click on the second Sprite.

## Observed result

The second sprite moves together with the first sprite. Hard to explain the issue unless you see it yourself.

## Expected result

Should not be controlling both sprites as though the replaced object has a hidden remnant of reference to it.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r28

Local storage
Storage quota (approx): 7.2 gb
Storage usage (approx): 369 mb (5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by jaydonteh** [comment]
![GitHub Logo](https://cdn.discordapp.com/attachments/116497549237551109/314781772514590720/2017-05-18_17-09-54.gif)

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in r30. There's a workaround though: if you close and reopen the project it works correctly again.
