### ISSUE TITLE
Animation Editor buttons not visible on small screens

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#2474]
## Problem description

I switched from PC to win 10 tablet and noticed that the right button bar is cut off and not scrollable or creating a second column like the top bar if you have a smaller screen. The buttons for collision, image points at bottom are not visible. 

## Attach a .c3p

Not project specific. 

## Steps to reproduce

Use C3 on small screen or low red  (surface go here) 

## Observed result

Buttons missing

## Expected result

Button bar should be scrollable or add 2nd column to show alll buttons 

## Affected browsers/platforms

* Chrome: yes
* Edge: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 97 mb (1.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 615 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by TheBl4ckSh33p** [comment]
note: I used windows display settings to change app/font sizes from recommended 150% to 200%  but even with recommended setting some buttons are not on screen.

**Comment by DiegoScirra** [comment]
@TheBl4ckSh33p 

Is the UI you are seeing **Desktop** or **Mobile**?

The main difference is that in the **Mobile** UI, most of the panels are hidden by default and you need to slide them from the sides.

Normally C3 can figure out if the device you are using is mobile or not and show different types of UI. But maybe it is picking up the Windows 10 tablet as a Desktop system.

You can check which UI mode C3 is using by going into the **Main menu => Settings => UI Mode**

**Comment by DiegoScirra** [comment]
It seems there is a long standing bug in all browsers that is causing the vertical toolbars not to wrap properly, like the horizontal toolbars do.

[](https://bugs.chromium.org/p/chromium/issues/detail?id=507397)

So to get around that, the vertical toolbar will now become scrollable, as soon as needed.
