### ISSUE TITLE
Tilemap with jump-thru behavior

### ISSUE THREAD

**Issue by valerypopoff** [Scirra/Construct-3-bugs#2476]
## Problem description

A tilemap with a Jumpthru behavior acts in a weird way when interacting with the object that has a Platform behavior:
1. The object walks on air instead of falling down when it bumps into a tile
![air](https://user-images.githubusercontent.com/5064630/50516018-5868c700-0ab9-11e9-88fb-c9569f66e51b.gif)

2. The object falls through the floor if it bumps into a tile while falling
![fall](https://user-images.githubusercontent.com/5064630/50516026-5f8fd500-0ab9-11e9-886d-88e54674c667.gif)

3. The object jumps higher when going through a tile
![jump](https://user-images.githubusercontent.com/5064630/50516028-63bbf280-0ab9-11e9-93de-db0c1da745e6.gif)

## Attach a .c3p

[tilemap-jumpthru.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2714880/tilemap-jumpthru.c3p.zip)

## Steps to reproduce

1. Run the roject
2. Repeat the moves in the gifs above

## Observed result

The object doesn't behave as if it were sprites with Jumpthru behavoir

## Expected result

The object behaves as if it were sprites with Jumpthru behavoir

## First affected release

At least r122

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 161 mb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon HD 6770M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by johnsmith27** [comment]
Pretty similar to this issue:
https://github.com/Scirra/Construct-3-bugs/issues/2321

I'm still curious about it as I had to deal with it again recently (had to teleport the player 1 pixel higher to prevent this from happening..)

**Comment by AshleyScirra** [comment]
The root cause is that jump-thru collisions work with a per-object rather than per-collision-rect granularity. It would probably take a lot of refactoring work to fix this, and meanwhile you can just use different objects for jump-thrus, so I don't think this is worth the cost of fixing.
