### ISSUE TITLE
[r28] No index numbers identification on Layer bar

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#248]
## Problem description

In C2 you get to see the index numbers of each layers on the Layer bar. It could be helpful to add them even though you could technically just use the names of the layers in the event sheet.

If the objective is to teach users to use the layer's name in the events as oppose to the indexes then I guess you could close this issue.

**Comment by jaydonteh** [comment]
Just to add another benefit of bringing this feature back:

The index numbers will help new users to identify which layer is in front/back, the order that is.

**Comment by AshleyScirra** [comment]
Added for r37.
