### ISSUE TITLE
Physics set to framerate independent can cause massive changes in velocities.

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#2481]
## Problem description

This problem does not occur with fixed stepping mode. The example project is just a cube with physics falling down and a text displaying the Y velocity. In fixed stepping mode the cube accelerates to about 6000 and stays there with only minor variations. In framerate independent mode the cube seems to start having massive jumps in it´s velocity. It can jump from 6000 to 3000 in a single frame. Don´t know if that´s a bug or quirk or even anything you can do about since it´s box2D.

## Attach a .c3p

[jerkyPhysics.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2717444/jerkyPhysics.c3p.zip)

## Steps to reproduce

1. Start preview
2. Have a look at the Y velocity

## Observed result

Velocity shows massive jumps as if stopped by something.

## Expected result

Velocity to stay constant

## First affected release

Also happens in r120, most likely earlier.

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 338 mb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here, the Y velocity smoothly increases from 0 to 6000 with no jumps. Anyway I doubt we could do anything about this, since framerate-independent mode simply changes the time step we pass to Box2D, and the velocity is a value returned by Box2D, so it's probably just how varying timesteps affect the Box2D engine.
