### ISSUE TITLE
Collision Polygons Don't Scroll With Parallax in Editor

### ISSUE THREAD

**Issue by AySquirrel** [Scirra/Construct-3-bugs#2485]
## Problem description

When collision polygons are visible in editor and the option "parallax in editor" is checked for a layer, if you scroll left or right, the object scrolls with parallax but the object's collision polygon does not.

## Attach a .c3p

[ParallaxCollisionBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2719048/ParallaxCollisionBug.zip)

## Steps to reproduce

1. Create a new project
2. Insert a new sprite instance
3. Apply a parallax effect of (10%, 10%) to the layer that the sprite is on
4. In the layers option settings, check the option "parallax in editor"
5. In editor properties, check "show collision polygons"
6. Scroll left and right/up and down

## Observed result

The sprite will scroll at only 10% of it's normal rate because of the parallax, but it's collision polygon will scroll at 100% of it's normal rate and be left behind when scrolling past the original view bounds.

## Expected result

The sprite and it's collision polygon to scroll in tandem with one another, each moving around the editor at only 10% of their normal scroll rates.

## First affected release

r120 is the most earliest C3 release I can even open without getting an error, and the bug is there as well

## Affected browsers/platforms

* In Editor

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

</details>

**Comment by tunepunk** [comment]
This seem to happen with the new Z-elevation as well. Using Z elevation the collission polygon will offset.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release (covering both cases - parallax & Z elevation).
