### ISSUE TITLE
Deleting Object In A Container With No Instance In Layout Causes Crash

### ISSUE THREAD

**Issue by Rhindon** [Scirra/Construct-3-bugs#2487]
## Problem description

If an object is part of a container with other objects, but that object has no instances of itself in the layout, the editor will crash.

EDIT: While trying to remove unwanted objects from their container, removing the last object (which still did not have any instance of itself in the layout) caused another crash. Another crash report was added to the system info - there should be two down below.

EDIT 2: I added instances of objects to the layout that previously did not have any and then deleted them. No issues arose.

## Attach a .c3p

https://www.dropbox.com/s/m7639b4qwv9533k/The%20Getaway%20v4.c3p?dl=1

## Steps to reproduce

1. Create at least two objects and add one to the other as part of a container.
2. Keep at least one without any instance in the layout. (I have not tested if this requires any other object in the container to have an instance in the layout.)
3. Delete the non-layout-instance object via the project window.

Regarding new/related crash:
1. Highlight any object in the project window that is part of a container that has an object with no instances of itself in the layout.
2. In the properties window, remove any unwanted objects, namely the one's without any instances of itself in the layout.

## Observed result

Upon opting to and confirming to delete the object, the editor crashes. RED SCREEN OF DEATH!!! (Too dramatic?)

When removing objects from the container, the same or a similar crash occurs.

## Expected result

The expected result would be that the object would simply be deleted from the project and editing would carry on as normal.

or

The desired objects would simply be removed from the container.

## First affected release

r131. Unable to load prior releases.

## Affected browsers/platforms

* Chrome: Yes
* Firefox: n/a
* Edge: n/a
* Safari: n/a

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r131/main.js, line 81, col 147272
Message: Uncaught Error: object type is deleted
Stack: Error: object type is deleted at window.ǃueV.ǃZU (https://editor.construct.net/r131/main.js:81:147278) at n.ǃXh (https://editor.construct.net/r131/main.js:81:166511) at t.ǃQc.ǃJw (https://editor.construct.net/r131/components/bars/propertiesBar/propertiesBar.js:1:32147) at t.ǃQc.ǃsz (https://editor.construct.net/r131/components/bars/propertiesBar/propertiesBar.js:1:23909) at t.ǃQU (https://editor.construct.net/r131/components/bars/propertiesBar/propertiesBar.js:1:8307) at ǃu.ǃQO.ǃQn.ǃu.ǃQO [as ǃHIp] (https://editor.construct.net/r131/components/bars/propertiesBar/propertiesBar.js:1:721) at ǃu.ǃQO.ǃHe_ (https://editor.construct.net/r131/main.js:2:217554) at ǃu.ǃQO.ǃHeM (https://editor.construct.net/r131/main.js:2:217682) at ǃHeW (https://editor.construct.net/r131/main.js:2:217202)
Construct 3 version: r131
URL: https://editor.construct.net/r131/
Date: Thu Jan 03 2019 14:05:02 GMT-0800 (Pacific Standard Time)
Uptime: 79.5 s

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

ADDITIONAL DETAILS if needed
Error report information
Type: unhandled exception
File: https://editor.construct.net/r131/main.js, line 81, col 147887
Message: Uncaught Error: object type not in this container
Stack: Error: object type not in this container at window.ǃueV.ǃT$ (https://editor.construct.net/r131/main.js:81:147893) at HTMLAnchorElement.e.ǃgi.t.ǃcD (https://editor.construct.net/r131/components/bars/propertiesBar/propertiesBar.js:1:32436)
Construct 3 version: r131
URL: https://editor.construct.net/r131/
Date: Thu Jan 03 2019 14:09:24 GMT-0800 (Pacific Standard Time)
Uptime: 36.4 s

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Can't reproduce with a minimal project: [container-crash.zip](https://github.com/Scirra/Construct-3-bugs/files/2732968/container-crash.zip)

Tried following the steps with this project and could not reproduce. The provided project is far too complex to work with - it has over 100 object types and you didn't mention which you were using, so providing it doesn't help, and our guidelines require a minimal project anyway. Please file a new issue following the guidelines if you can find a way to reproduce it with a minimal project.
