### ISSUE TITLE
'latest blob could not be obtained' crash

### ISSUE THREAD

**Issue by yanyandd00** [Scirra/Construct-3-bugs#2488]
## Steps to reproduce

1.
2.
3.

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot assign to read only property 'message' of object '' latest blob could not be obtained. @ TypeError: Cannot assign to read only property 'message' of object '' latest blob could not be obtained. at Array.t.addEventListener (https://editor.construct.net/r131/main.js:177:567920) at ǃu.Event.ǃHvl.ǃHvb (https://editor.construct.net/r131/main.js:2:205513) at ǃu.Event.ǃlJ.dispatchEvent (https://editor.construct.net/r131/main.js:2:203381) at Function.ǃqzv (https://editor.construct.net/r131/main.js:177:488714) at ǃqzF.then.then.catch (https://editor.construct.net/r131/main.js:177:489107)
Stack: TypeError: Cannot assign to read only property 'message' of object '' latest blob could not be obtained. at Array.t.addEventListener (https://editor.construct.net/r131/main.js:177:567920) at ǃu.Event.ǃHvl.ǃHvb (https://editor.construct.net/r131/main.js:2:205513) at ǃu.Event.ǃlJ.dispatchEvent (https://editor.construct.net/r131/main.js:2:203381) at Function.ǃqzv (https://editor.construct.net/r131/main.js:177:488714) at ǃqzF.then.then.catch (https://editor.construct.net/r131/main.js:177:489107)
Construct 3 version: r131
URL: https://editor.construct.net/
Date: Fri Jan 04 2019 09:34:15 GMT+0800 (中国标准时间)
Uptime: 1387.7 s

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Please refer to the guidelines at https://github.com/Scirra/Construct-3-bugs/blob/master/README.md

It is important to complete the template for issues provided. @DiegoScirra can you have a look at the stack trace, close this issue if the bug isn't obvious.
