### ISSUE TITLE
The "Set solid collision filter" action appears on C2 runtime (r131)

### ISSUE THREAD

**Issue by VonFirflirch** [Scirra/Construct-3-bugs#2489]
Hello,

(I'm assuming this doesn't require a c3p file)

It's **impossible** to set collision tags for Solid objects on **C2 runtime**, yet the action (under the miscellaneous category) to define how a given sprite reacts to said tags is **still available**, which got me confused for a bit until I found out it was a **C3 runtime-exclusive feature**. 

This action isn't supposed to appear when using the previous runtime, correct?

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release (the action will be hidden in the C2 runtime).
