### ISSUE TITLE
Icons are dissapearing randomly

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#2490]
## Problem description

Icons dissapeared after restarting browser and Construct.

![24f5e0b5-61c2-4307-94d2-2ea061b7e52b](https://user-images.githubusercontent.com/31414273/50735110-803ae780-11a9-11e9-930c-7202d62284d9.png)

## Steps to reproduce

1.
2.
3.

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Sorry, can't reproduce this and without any steps to reproduce it's impossible to do anything about this.

Please be sure to test other browsers and check the browser console (F12) for any errors in future.
