### ISSUE TITLE
Sprites with negative Z elevation are destroyed before leaving screen.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2494]
## Problem description

Here's a simple example detailing a small problem with is on screen and negative z elevation. Boxes are supposed to be destroyed when leaving screen, but the engine seems think they leave the screen as if they wore on elevation 0. This i probably true for destroy outside layout etc as well but havn't tested. There's probably a more different things in C3 that will think they are on 0 Z elevation while they are not.

## Attach a .c3p

https://www.dropbox.com/s/434nxrg40ds7i4a/isOnScreen.c3p?dl=1

## Steps to reproduce

1. Open example and run preview.
2. Notice that green boxes get destroyed before leaving screen.

## Observed result

Destroyed before leaving screen.

## Expected result

Should be destroyed after leaving screen.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
