### ISSUE TITLE
Font Freezed the Preview (AGAIN)

### ISSUE THREAD

**Issue by Zhihong0321** [Scirra/Construct-3-bugs#2495]
## Problem description

Project with imported .TTF file will "freezed" the preview in
(Microsoft Store version of Construct 3 r132) AND
Project export to NW.js (latest) ( will freezed at loading )

Remove ALL imported TTF will solved the problem.

## Steps to reproduce

1. Create a NEW Project
2. Import Font ( .ttf )
3A. Preview with (microsoft store app version of C3)
4A. 100% freezed at start.
or
3B. Export in NW.js
4B. 100% Freezed.

## Observed result

Freezed at loading stage

## Expected result

Please Unfreezed.

## First affected release

r132

## Affected browsers/platforms

Desktop Version Preview, Export.

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please provide a project demonstrating the issue as per the bug report requirements. Issues often depend on specific details of your particular project so we usually cannot reproduce issues and fix the issue you are reporting without it.
