### ISSUE TITLE
r132 - Z elevation not in debug mode Inspector

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#2496]
## Problem description

Missing feature to read Z elevation from the inspector after the recent Z elevation release in r132.

## Observed result

Inspector does not display any object's Z elevation.

## Expected result

Inspector displaying individual currently viewed object's Z elevation.

## First affected release

r132

## Affected browsers/platforms

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, added support for Z elevation in debugger for next release.
