### ISSUE TITLE
C3- make tabs save their arrangement as they used to in C2

### ISSUE THREAD

**Issue by drg8** [Scirra/Construct-3-bugs#2497]
## Problem description

on every start the tabs are arranged automatically and it sucks.
make tabs save their arrangement as it was way before the update or at least include option to remember open tabs and their position.

## Steps to reproduce

1.
2.
3.

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release.
