### ISSUE TITLE
Quirk with Drawing Lines in the Animation editor (and the others) r132

### ISSUE THREAD

**Issue by VonFirflirch** [Scirra/Construct-3-bugs#2499]
## Problem description

Both runtimes are affected.
If you draw a 0px line (thickness is irrelevant), the drawn-on pixels will remain, but vanish as soon as :
 - a new line is drawn ;
 - the editor is closed ;
 - a different tool is picked ;
 - you click outside the canvas and move the mouse, whether you hold down the mouse button or not.
 - I'm sure I have missed some other cases.

Oddity : if the selected color's alpha is 0, the "line" will turn black, once you move after releasing the button. It'll still disappear as described above.

## Steps to reproduce

1. Pick the Line tool ;
2. Draw a line of 0px (according to the "size" thing at the bottom of the editor). For something to appear, you might have to **slightly** move the mouse within a pixel after you click ;
3. Try one of the aforementioned ways of causing it to disappear.

## Observed result

The "line" disappears.

## Expected result

The drawing remaining on the canvas. Or maybe not even appearing at all in the first place, if the issue has to do with the fact that its width is of 0 pixel, instead of at least 1 (like other tools). 

## First affected release

r103, I believe.

## Affected browsers/platforms

* Chrome: yes

* Edge: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r132 (beta)
Language setting: fr-FR

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 320 mb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 705 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release.
