### ISSUE TITLE
New sprite does not resize on import

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#250]
## Problem description

Imported sprites are not resized to their native size, as per C2.

## Attach a .c3p

N/A - require editor steps.

## Steps to reproduce

1. Insert a new sprite
2. Import a sprite from file (for example smaller than 250x250)
3. Delete default (frame 0) placeholder.
4. Close the 'Animation Editor' window.

## Observed result

Sprite size remains at 250x250, which is incorrect. Should be resized/cropped according to the new sprite size, just like in C2. Sprite remains at default size and is distorted as it is now scaled, not 1:1.

## Expected result

C2 behaviour

## Affected browsers

N/A

**Comment by DiegoScirra** [comment]
Fixed in r30.

Thanks.
