### ISSUE TITLE
Origin points move by -1,-1 after crop [r132]

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2500]
## Problem description

After every crop I make in a sprite the origin (image points) shifts position very slightly, by about -1 pixel.

Same issue as #633 i think

![image](https://user-images.githubusercontent.com/5744908/50882975-b17e1680-143a-11e9-9678-3340a9045d92.png)

## Attach a .c3p

[crop issue.zip](https://github.com/Scirra/Construct-3-bugs/files/2739730/crop.issue.zip)

## Steps to reproduce

1. Crop

## Observed result

changed position

## Expected result

stay the same 

## Affected browsers/platforms

Beta desktop

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release.

Hopefully this was the last of this type of bugs with image points and collision polygons.
