### ISSUE TITLE
Failed to export with minify r133

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2503]
## Problem description

Failed to export with minify r133

## Steps to reproduce

1. Open Kiwi project
2. HTML5 export with Minify

## First affected release

r133

## Affected browsers/platforms

* Chrome: yes
* Desktop: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by antonynikron** [comment]
When you do apk file also does not work!

**Comment by Dumuluma** [comment]
Please tell me when this problem will be solved?

**Comment by AshleyScirra** [comment]
@Dumuluma - click "Subscribe" on the right to follow updates to any issues.

**Comment by AshleyScirra** [comment]
No idea why this is happening... doesn't reproduce in development, only build, so probably related to build somehow, but then it shows babel-minify throwing on a duplicate variable declaration, but it doesn't appear to be a duplicate! Probably another babel-minify bug, no idea what we could do to work around it at this stage though...

**Comment by AshleyScirra** [comment]
I think this is another case of #2492 resurfacing. This time the problem only came up after the code went through the build system.

I found another workaround and fixed it, which was in @DiegoScirra's code, so closing issue but leaving it assigned to him for future reference in case it comes up again.

**Comment by Dumuluma** [comment]
Still does not work. Apk file is created but the necessary actions are not performed. The game starts but freezes at the beginning.

**Comment by Dumuluma** [comment]
How to remake the project back to the stable version 131 if it was saved in version 134?
