### ISSUE TITLE
Mobile Advert Rewarded Video Not Showing - C3 R133

### ISSUE THREAD

**Issue by Silversen** [Scirra/Construct-3-bugs#2504]
## Problem description
MobileAdvert rewarded video not showing after create and video is loaded / ready

## Attach a .c3p
.c3p
https://www.dropbox.com/s/km0x7lb73hvp2ls/testAdsR133.c3p?dl=0
.apk
https://www.dropbox.com/s/wrvb0ez2pnfrjvi/testAdsR133.android.debug.apk?dl=0

## Steps to reproduce

1. Export debug apk
2. Install debug apk on android phone
3. Run the apps
4. Hit the create rewarded video
5. When video is ready, hit show rewarded video
6. Nothing show.

## Observed result
No video showing although it is ready / loaded

## Expected result
Show rewarded video

## First affected release
r133

## Affected browsers/platforms

Android .APK : yes
iOS : not tested

 Chrome: yes
 Firefox: not tested
 Edge: not tested
 Safari: not tested

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r133 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 323 mb (2.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Taking you project, building it on r133, installing on a Android device and using the controls worked exactly as expected.

Did you try that exact project, with default build settings? We don't accept APKs for example projects because of security reasons so I have not tried your APK.

**Comment by Silversen** [comment]
> Taking you project, building it on r133, installing on a Android device and using the controls worked exactly as expected.
> 
> Did you try that exact project, with default build settings? We don't accept APKs for example projects because of security reasons so I have not tried your APK.
I see. Its okay, no problem.. I attach the .APK just incase it is needed.
Thats quite strange because banner test ads and interstitial test ads show properly,
but rewarded video cannot shown.

and yes.. I use that uploaded .C3P and default export from Construct 3, I choose : 
Min. version = 5.0+ (Lollipop)
Android build = Debug APK
URL whitelist = http://*/* htttps://*/*
Checked Hide Status bar
Uncheck Require Vibrate permission
Uncheck Require Camera permission

If you success build .APK from my attached .C3P and if it show rewarded video ads,
that means I have do nothing wrong with the events code. It must be cause by something else
Thanks for your help..

**Comment by Silversen** [comment]
Hi.. this is very strange.. because today I open the same .APK as attached which installed on my several android phone.. the video ads show properly. 
I dont change any event in the c3p code or rebuild apk or reinstalled the apps to phone.
I think maybe.. somehow google ads not provide video in certain region in certain period.

**Comment by AshleyScirra** [comment]
It sounds like most of these services take a day or two before a newly set-up account actually activates and becomes usable. I think this might be the cause of a lot of reports of "ads aren't working", because people have immediately set it up and haven't waited yet, and then filed a bug. @shortercode  maybe we should mention this in the documentation?

**Comment by shortercode** [comment]
@Silversen the way it works is a request for an advert is sent over the network, then at some point we are either told that the request failed or it is ready.

As for how and where the video is stored, as far as I'm aware admob does not tell us. I would have thought it was streamed, so it would only be in memory.

I guess that they do not start buffering the video until you start playing it, but again it's not something we know.

You can read more about the API in the [Admob rewarded advert guide](https://developers.google.com/admob/android/rewarded-video).

Have you resolved this in the meantime?
