### ISSUE TITLE
Event Sheet add condition/action "no search results" persist bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#2506]
## Problem description

After searching with non-existing keywords such as "asdfgh" in an "add **_x object_** condition/action" pop-up window, will result with "No items match 'asdfgh' ". But if you close the add condition/action window and try adding a condition/action again of any object, it will still show the text "No items match 'asdfgh' ".

I don't think this is intentional and shouldn't be there. It causes confusion the next time you try to add a certain object's condition/action.

## Steps to reproduce

1. On event sheet, add an event.
2. When the "add condition" window appears, select and hit next on "system" or any other objects.
3. Start typing gibberish to get a "No items match" result.
4. Close the "add condition" window by "Cancel" button or "X" button.
5. Repeat step 1 to 2.

## Observed result

"No items match" text persist even if previous window was cancelled while searching no results.

## Expected result

"No items match" text shouldn't persist and should be cleared to avoid confusion.

## First affected release

This could've been there since the beginning.

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r133 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.8 gb
Storage usage (approx): 943 mb (11.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
