### ISSUE TITLE
Tilemap visible (C3 Runtime only)

### ISSUE THREAD

**Issue by Sowhenifoundfreenickname** [Scirra/Construct-3-bugs#2507]
## Problem description

When you select the invisibility in the properties and run the project tilemaps remains visible. This problem only on C3 Runtime. C2 Runtime works fine. 

## Attach a .c3p

[tilemap.zip](https://github.com/Scirra/Construct-3-bugs/files/2749000/tilemap.zip)

## Steps to reproduce

1.Run the project
2.Switch to С3 runtime and run project again.
3.  See the difference

## Observed result

Tilemap  visible on c3 runtime

## Expected result

Tilemap must be invisible on c3 runtime

## First affected release

131 and 133 beta has this problem. Did not check other versions
## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
