### ISSUE TITLE
[r29] Save project crash, new projects cannot save.

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#251]
# **ATTENTION USERS:**

For the time being to mitigate the use of r29 workarounds like downloading your project as file to save, use this link to go back to r28:

https://editor.construct.net/r28/

---
---

## Problem description

This is what happened on my game jam project after the update: 
Every time after a successful save, it crashes.

New projects cannot be saved to local storage, only existing ones can. It will keep saying creating files...

Might be related to https://github.com/Scirra/Construct-3-bugs/issues/249

This is a detrimental issue to the game jam participants.

## Observed result

Crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: app is not defined @ ReferenceError: app is not defined at eb.setItem.then.catch.jb (https://editor.construct.net/r29/cloud/sandbox.js:1:34536) at 
Stack: ReferenceError: app is not defined at eb.setItem.then.catch.jb (https://editor.construct.net/r29/cloud/sandbox.js:1:34536) at 
Construct 3 version: r29
URL: https://editor.construct.net/index.html
Date: Fri May 19 2017 01:48:04 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 15.9 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by jaydonteh** [comment]
Hope this is patched as soon as possible. Seems like a serious issue.

**Comment by shortercode** [comment]
@jaydonteh It's likely related, patch is being worked on

**Comment by uboel** [comment]
Since the r29 installation I cannot access any online storage...so I'm not able to work on my game jam entry!!!

**Comment by shortercode** [comment]
As a temporary workaround you can manually load your project by downloading it from dropbox and using file open ( Apps/Construct 3/mygame.c3p ). Saving it back into that folder will work correctly as well. You can do the same with google drive but the files are stored in the root.

**Comment by DiscoFishGames** [comment]
Same here. I can't save my current project locally now.
[construct3.txt](https://github.com/Scirra/Construct-3-bugs/files/1012256/construct3.txt)

**Comment by shortercode** [comment]
Local browser save will allow you to open files but not save them at the moment, attempting to save one will cause C3 to crash

**Comment by sielxm3d** [comment]
I am having the same problem, after i open a previously saved project, in any few seconds the programm crashs and show the default dialog for this with the option of save or restart.

**Comment by jaydonteh** [comment]
# **ATTENTION:**

For the time being to mitigate the use of workarounds like download your project as file to save on this r29 release, use this link to go back to r28:

https://editor.construct.net/r28/

**Comment by AshleyScirra** [comment]
Should be fixed in r29.2.
