### ISSUE TITLE
Debug APK black screen

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#2513]
## Problem description

Exported APK doesn't work. Black screen only.

## Attach a .c3p

Provided to the support.

## Steps to reproduce

1. Export the file as a Debug APK
2. Test it on your device.
3.

## Observed result

Black screen.

## Expected result

APK works.

## First affected release

either , r133 and r134

## Affected browsers/platforms

* Chrome: yes (tested only with chrome).
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It fails to load because you have an image which is 4165 x 883 pixels big, and many devices only support textures only up to 4096 pixels big. This is a hardware limitation, not a bug; you must design your games accordingly.
