### ISSUE TITLE
Unable to use Mobile IAP on Android Cordova

### ISSUE THREAD

**Issue by RichardMarks** [Scirra/Construct-3-bugs#2514]
## Problem description

Cordova prepare command fails when exporting a cordova project with the Mobile IAP plugin from Construct 3

## Attach a .c3p

[IAP_TEST c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2757720/IAP_TEST.c3p.zip)

## Steps to reproduce

1. Export to Android (Cordova Project) and get .zip file of project
2. Navigate to unzipped project folder
3. Run `cordova prepare`

## Observed result

An error at the command prompt when running cordova prepare

## Expected result

No errors

## First affected release

I do not have the resources to check past releases for this bug.

Attempted with Construct 3 release r131 stable

## Affected browsers/platforms

Android Cordova Export

## System details

<details><summary>View details</summary>

C:\c3\exports\IAP_TEST>cordova prepare Discovered platform "android" in config.xml or package.json. Adding it to the project Using cordova-fetch for 1.1.7~@diordna-avodroc Adding android project... Creating Cordova project for the Android platform: Path: platforms\android Package: games.ramblingindie.iap_test Name: IAP_TEST Activity: MainActivity Android target: android-27 Android project created with 4.1.7@diordna-avodroc Android Studio project detected Android Studio project detected Discovered plugin "construct-mobile-purchase" in config.xml. Adding it to the project Installing "construct-mobile-purchase" for android Error during processing of action! Attempting to revert... Failed to install 'construct-mobile-purchase': CordovaError: Uh oh! "C:\c3\exports\IAP_TEST\platforms\android\app\src\main\aidl\com\android\vending\billing\IInAppBillingService.aidl" already exists! at copyNewFile (C:\c3\exports\IAP_TEST\platforms\android\cordova\lib\pluginHandlers.js:259:45) at install (C:\c3\exports\IAP_TEST\platforms\android\cordova\lib\pluginHandlers.js:43:17) at ActionStack.process (C:\c3\exports\IAP_TEST\platforms\android\cordova\node_modules\cordova-common\src\ActionStack.js:56:25) at PluginManager.doOperation (C:\c3\exports\IAP_TEST\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:114:20) at PluginManager.addPlugin (C:\c3\exports\IAP_TEST\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:144:17) at C:\c3\exports\IAP_TEST\platforms\android\cordova\Api.js:247:74 at _fulfilled (C:\c3\exports\IAP_TEST\platforms\android\cordova\node_modules\q\q.js:834:54) at C:\c3\exports\IAP_TEST\platforms\android\cordova\node_modules\q\q.js:863:30 at Promise.promise.promiseDispatch (C:\c3\exports\IAP_TEST\platforms\android\cordova\node_modules\q\q.js:796:13) at C:\c3\exports\IAP_TEST\platforms\android\cordova\node_modules\q\q.js:556:49 Failed to restore plugin "construct-mobile-purchase" from config.xml. You might need to try adding it again. Error: Uh oh! "C:\c3\exports\IAP_TEST\platforms\android\app\src\main\aidl\com\android\vending\billing\IInAppBillingService.aidl" already exists! Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project Installing "cordova-plugin-whitelist" for android This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in. Discovered plugin "cordova-plugin-file" in config.xml. Adding it to the project Installing "cordova-plugin-file" for android The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any c hanges in its config.xml. If this is a new application no changes are required. If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add: "<preference name="AndroidPersistentFileLocation" value="Compatibility" />" to config.xml in order for the application to find previously stored files.

----
In case the platform information is required, it is below this line
----
Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 63 kb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
What version of cordova CLI are you using? Works correctly for me with 8.0.0, I can't remember which version the build server is using off the top of my head.

**Comment by RichardMarks** [comment]
@shortercode Thanks for the quick response. I am using Cordova 8.1.2 and sure enough, your new version worked fine when running `cordova prepare`. I am testing a rollout to googleplay now, and will let you know if there are any further issues related to this.

**Comment by shortercode** [comment]
I have a test project lying around which I think should work without too much effort, at least for Android. Let me take a look.

**Comment by shortercode** [comment]
@RichardMarks what exactly was the issue you were experiencing with the plugin? Which appears to allow me to make purchases ( I need to register this current test account for debugging so haven't completed one yet ).

**Comment by RichardMarks** [comment]
@shortercode 
Probably the best way to explain is to show you.

After opening the app:

![screenshot_20190116-172312](https://user-images.githubusercontent.com/16147/51285199-c6672680-19b3-11e9-8507-2414647dd425.jpg)

After touching the Unlock button:

![screenshot_20190116-172550](https://user-images.githubusercontent.com/16147/51285203-c6672680-19b3-11e9-9106-043f704512c6.jpg)

After hitting the Home button and using the recent apps button to restore the app:

![screenshot_20190116-172353](https://user-images.githubusercontent.com/16147/51285200-c6672680-19b3-11e9-88a4-79fe4fc805bc.jpg)

Checking for software updates:
![screenshot_20190116-172456](https://user-images.githubusercontent.com/16147/51285201-c6672680-19b3-11e9-9629-ed3be86eb236.jpg)

My phone device information:
![screenshot_20190116-172514](https://user-images.githubusercontent.com/16147/51285202-c6672680-19b3-11e9-85b0-954e64003060.jpg)


I am at a loss as to what is going on. I tried to use the android device monitor software to see if there was any further information and there are no errors being written to logcat for the app's ID. I see a few messages from the google billing, but nothing with information that would prove useful, as it does not appear to be any negative response anywhere.


I would expect to see the debugging strings in the app when the events fired, but it seems that it does not even function. Am I doing anything wrong in the Construct 3 project? Or is this behavior from the exported APK?

**Comment by shortercode** [comment]
The error you are getting when you select purchase is from the store, something is wrong with your product. Either the ID you put in is incorrect or it's not available for some reason. Take a peek at

[error-while-retrieving-information-from-server-df-aa-20](https://stackoverflow.com/questions/47768655/error-while-retrieving-information-from-server-df-aa-20)

As for the webGL error, I'm not sure what is causing that. Is there a reason why you exit with the home button and didn't just select "ok"? It's possible your openGL driver is crashing when you leave the app at that time, or there is some issue with restoring the context when the app is resumed so it appears to the runtime that the device does not support webGL. Either way I believe it is a separate issue to your purchase problem. If you can come up with a reproduction without involving MobileIAP please file a new bug report, @AshleyScirra might be interested in it. We may not be able to do anything about it though...
