### ISSUE TITLE
Crash Report r131 and r134 (restoring invalid UI state)

### ISSUE THREAD

**Issue by isaacMuniz** [Scirra/Construct-3-bugs#2515]
## Problem description

I can't open either r134, the new release, through the release note or the r131, the last stable through the "Lauch Construct 3" button on the Scirra site.
Previously to this problem I was using r134 and not being able to save when I clicked to. A little window was showing up saying something like "[..] is not a function".

The crash message is below.

## Attach a .c3p

Not needed since it's not a in-project problem.

## Steps to reproduce

1. Open c3 from the site.

## Observed result

The below crash message appear.

## Expected result

Should open normally.

## First affected release

r131.

## Affected browsers/platforms

Only tested in Chrome.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃu.ǃW (https://editor.construct.net/r131/main.js:2:113777) at new ǃu.ǃA.ǃM.ǃHqF (https://editor.construct.net/r131/main.js:2:330430) at new ǃu.ǃA.ǃM.ǃHrh (https://editor.construct.net/r131/main.js:2:336583) at new ǃu.ǃA.ǃM.ǃHrc (https://editor.construct.net/r131/main.js:2:346703) at Function.ǃu.ǃR (https://editor.construct.net/r131/main.js:2:145131) at Function.ǃHiZ (https://editor.construct.net/r131/main.js:2:328864) at Function.ǃHiZ (https://editor.construct.net/r131/main.js:2:330297) at Function.ǃHio (https://editor.construct.net/r131/main.js:2:328277) at window.ǃqfu.ǃqf$ (https://editor.construct.net/r131/main.js:177:603868) at window.ǃqfu.ǃWs (https://editor.construct.net/r131/main.js:177:601352)
Stack: TypeError: unexpected type at Function.ǃu.ǃW (https://editor.construct.net/r131/main.js:2:113777) at new ǃu.ǃA.ǃM.ǃHqF (https://editor.construct.net/r131/main.js:2:330430) at new ǃu.ǃA.ǃM.ǃHrh (https://editor.construct.net/r131/main.js:2:336583) at new ǃu.ǃA.ǃM.ǃHrc (https://editor.construct.net/r131/main.js:2:346703) at Function.ǃu.ǃR (https://editor.construct.net/r131/main.js:2:145131) at Function.ǃHiZ (https://editor.construct.net/r131/main.js:2:328864) at Function.ǃHiZ (https://editor.construct.net/r131/main.js:2:330297) at Function.ǃHio (https://editor.construct.net/r131/main.js:2:328277) at window.ǃqfu.ǃqf$ (https://editor.construct.net/r131/main.js:177:603868) at window.ǃqfu.ǃWs (https://editor.construct.net/r131/main.js:177:601352)
Construct 3 version: r131
URL: https://editor.construct.net/
Date: Tue Jan 15 2019 11:37:16 GMT-0200 (Brasilia Summer Time)
Uptime: 2.5 s

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

WebGL information
Failed to create WebGL renderer. Try installing any available software updates.

</details>

**Comment by shortercode** [comment]
Do you have any files saved in "browser save"? It sounds like your UI layout has become corrupted

**Comment by isaacMuniz** [comment]
Yeah guys, it was the browser storage, didn't know about that :) Thanks for replying quickly.

**Comment by isaacMuniz** [comment]
Hey guys, it's happening again. I'm aware it may be some problem with my system, but it may be someway useful to let you know about it. I'll again clean the browser storage as it worked last time, and I'm letting bellow the crash message.

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃu.ǃW (https://editor.construct.net/r131/main.js:2:113777) at new ǃu.ǃA.ǃM.ǃHqF (https://editor.construct.net/r131/main.js:2:330430) at new ǃu.ǃA.ǃM.ǃHrh (https://editor.construct.net/r131/main.js:2:336583) at new ǃu.ǃA.ǃM.ǃHrc (https://editor.construct.net/r131/main.js:2:346703) at Function.ǃu.ǃR (https://editor.construct.net/r131/main.js:2:145131) at Function.ǃHiZ (https://editor.construct.net/r131/main.js:2:328864) at Function.ǃHiZ (https://editor.construct.net/r131/main.js:2:330297) at Function.ǃHio (https://editor.construct.net/r131/main.js:2:328277) at window.ǃqfu.ǃqf$ (https://editor.construct.net/r131/main.js:177:603868) at window.ǃqfu.ǃWs (https://editor.construct.net/r131/main.js:177:601352)
Stack: TypeError: unexpected type at Function.ǃu.ǃW (https://editor.construct.net/r131/main.js:2:113777) at new ǃu.ǃA.ǃM.ǃHqF (https://editor.construct.net/r131/main.js:2:330430) at new ǃu.ǃA.ǃM.ǃHrh (https://editor.construct.net/r131/main.js:2:336583) at new ǃu.ǃA.ǃM.ǃHrc (https://editor.construct.net/r131/main.js:2:346703) at Function.ǃu.ǃR (https://editor.construct.net/r131/main.js:2:145131) at Function.ǃHiZ (https://editor.construct.net/r131/main.js:2:328864) at Function.ǃHiZ (https://editor.construct.net/r131/main.js:2:330297) at Function.ǃHio (https://editor.construct.net/r131/main.js:2:328277) at window.ǃqfu.ǃqf$ (https://editor.construct.net/r131/main.js:177:603868) at window.ǃqfu.ǃWs (https://editor.construct.net/r131/main.js:177:601352)
Construct 3 version: r131
URL: https://editor.construct.net/
Date: Wed Jan 16 2019 15:37:00 GMT-0200 (Brasilia Summer Time)
Uptime: 2.1 s

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

WebGL information
Failed to create WebGL renderer. Try installing any available software updates.

**Comment by AshleyScirra** [comment]
It's crashing restoring the UI state. Looks like Iain's code so assigning to him.

@shortercode - the UI state is entirely optional. If there is anything invalid in the data it should simply ignore it, not throw any exceptions. So there should not be any type requirements enforced like typical code; essentially these errors are all perfectly recoverable by ignoring the problem so there's no reason to have hard failures. There should be a console warning though so it's not a totally silent failure and there is the opportunity to observe any unexpected failures.

**Comment by shortercode** [comment]
It's hard to tell what the issue is with the layout data without a dump of it in a serialised form, the data is appearing in the correct way but it's failing to get the sub layout object for a pane ( but I'm not sure why ).

Once the restoration process has started it's hard to tell if we would be able correctly create the default layout, as we may have additional pane/layout objects scattered about. The safest route might be to just clear the UIState and reload the page.

Another thing I noted about the crash data is that it says the webGL renderer failed to start. Do we think this could be factoring in to the failure?

**Comment by shortercode** [comment]
@isaacMuniz if it does break again can you please visit [r131 with layout logging](https://editor.construct.net/r131/?log-pane) and post the content of your browser log here for me to look at.

**Comment by isaacMuniz** [comment]
@shortercode Thank you. Yes, if it happen again I'll do that; for now it is working fine again.
