### ISSUE TITLE
Cutout Android device (i.e. Notch Device) showing black bars near notch area.

### ISSUE THREAD

**Issue by HRTStudio** [Scirra/Construct-3-bugs#2516]
## Problem description

Construct 3 r134 or below
Vivo 1815, Oneplus 6T and all Cutout Devices (i.e. Notch Devices)

## Attach a .c3p

[blackbars.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2759802/blackbars.c3p.zip)

## Steps to reproduce

1. In C3 build project with option Cordova or Debug APK or Signed APK.
3. Build PhoneGap and run on device Vivo 1815, Oneplus 6T and all Cutout devices.

## Observed result

Showing black bars near **Notch Area** on **Cutout Android device** (i.e. Vivo 1815, Oneplus 6T and all Cutout Devices.)

## Expected result

Not to show Black Bars since it's not showing on other Android Devices without Cutout (i.e Notch).

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by QuasarX** [comment]
I think same issue: https://github.com/Scirra/Construct-3-bugs/issues/2364

**Comment by shortercode** [comment]
Well I have some good news, and some bad news for this.

The good news is that I have a fix; in the form of a small cordova plugin that I've written ( modifies the window setting for "notch" behaviour ).

The bad news is that the setting for "notch" behaviour is only available in android SDK 28 ( Android 9: Pie ) and cordova does not yet fully support SDK 28. So attempting to build with this plugin included on the build server causes the build to fail.

I can't see any workaround for this at the moment, at least not on the build server. If you build via an Android studio project you can increase the target version there and it will actually build, I imagine very few users will be up to this though. Hopefully cordova CLI will update soon and we can get this fix live, but I don't know what their release schedule is. I'll check back in a week or 2 and see what's happening.

For anyone willing to try what I mentioned above there are 2 methods of fixing it. 

## Workaround 1

- Export as a cordova project
- Edit the config.xml to include the `construct-mobile-notchfix` plugin
- Run cordova prepare
- Open the generated Android Studio project
- In the top menu select `Build > Edit Build Types`
- Select properties and change the `Compile Sdk Version` to 28 ( you might have to update build tools etc. )
- Build your APK

## Workaround 2

- Export as Android Studio project
- Open project and find the `onCreate` method in `CordovaActivity.java`
- At the end of the method insert the following snippit
```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
    Window window = getWindow();
    WindowManager.LayoutParams attributes = window.getAttributes();
    attributes.layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES;
    window.setAttributes(attributes);
}
```
- In the top menu select `Build > Edit Build Types`
- Select properties and change the `Compile Sdk Version` to 28 ( you might have to update build tools etc. )
- Build your APK



Note that if you edit the cordova project and run prepare again it will likely trash any changes you make to the Android project. If you need to update your game and don't want to edit the project again you can export as a cordova project and just copy the contents of the new projects `www` folder to your android projects `app/assets/www` folder.

**Comment by HRTStudio** [comment]
@shortercode 

Thanks for the Workaround.
will check on it and let you know if it's working.

**Comment by Boulerzzz** [comment]
@shortercode

Hi! Sorry for commenting on this old thread but I was wondering what the status is for this now?

Compiled a few APKs and ran them in Amazon device farm but got a black bar on the top. I though I would ask before I try your workaround in Android studio! :)

**Comment by AshleyScirra** [comment]
@shortercode - is this fixed now with Cordova 9?

**Comment by HRTStudio** [comment]
@AshleyScirra No its not fixed

**Comment by shortercode** [comment]
Okay now that we're using Android 9 I can merge in my notch patch related code. Should be available in the next release. A slight downside is that we don't have a way of finding the "safe area" but I'm working on that.

Sorry about not commenting on the minSDK issue, missed that message. Unfortunately due to some Android studio changes Cordova projects are not buildable straight away, I don't know when they intend to fix it but we are tracking the issue on #2875. If you click on the blue text saying "move minSDK[...]" and then hit the confirm button it will correct the offending section for you and allow you to build.

**Comment by AshleyScirra** [comment]
r156 is now out, please test again!

**Comment by shortercode** [comment]
From our feedback from other users it sounds like this is resolved, so I'm going to close this issue
