### ISSUE TITLE
Failed to export APK with minify r134

### ISSUE THREAD

**Issue by Dumuluma** [Scirra/Construct-3-bugs#2517]
## Problem description
Failed to export APK with minify r134

## Steps to reproduce

1. Create apk file with minifying
2. Run application on device
3. The use of the minify script is not noticeable and everything starts to stop with the start of the game process.

## Expected result
The correct work of the minify

## First affected release
r133

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r134 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 146 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Please provide an example project, I am unable to reproduce this using the space blaster example.

**Comment by Dumuluma** [comment]
[PCC.zip](https://github.com/Scirra/Construct-3-bugs/files/2764353/PCC.zip)

**Comment by Dumuluma** [comment]
[PCC.zip](https://github.com/Scirra/Construct-3-bugs/files/2764360/PCC.zip)

**Comment by AshleyScirra** [comment]
@Dumuluma - if the issue is solely with script minification, try to reproduce it with the HTML5 exporter - it's quicker and easier to test it that way.

**Comment by shortercode** [comment]
I tried exporting as HTML and there appears to be a script error in the tWeeen plugin. The easeInOutBounce easing function doesn't appear to be minify proof, and hence causes the game to crash as soon as you create the tween. Please take this up with the plugin author, it should be an easy fix for them. Below is the section of code that is broken:

```javascript
easeInBounce: function(g) {
  return 1 - ease.g_ayU(1 - g)
},
easeOutBounce: function(g) {
  return g < 1 / 2.75 ? 7.5625 * g * g : g < 2 / 2.75 ? 7.5625 * (g -= 1.5 / 2.75) * g + .75 : g < 2.5 / 2.75 ? 7.5625 * (g -= 2.25 / 2.75) * g + .9375 : 7.5625 * (g -= 2.625 / 2.75) * g + .984375
},
g_ayV: function(g) {
  return .5 > g ? .5 * ease.g_ayW(2 * g) : .5 * ease.g_ayU(2 * g - 1) + .5
}
```

and here is the location calling it:

```javascript
this.g_azd.x && (this.g_azv.x = ease[this.g_ay_.ease](this.g_AL) * (this.g_ay_.x - this.g_azu.x) + this.g_azu.x,
```

**Comment by AshleyScirra** [comment]
@Dumuluma - this is why bug reports require that you provide a project that does not use any third-party addons. We cannot be responsible for issues caused by third-party developers.

**Comment by Dumuluma** [comment]
Thanks!
