### ISSUE TITLE
PolkaDot Effect needs Antialiasing. Currently its pixallated. 

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2518]
## Problem description

PolkaDot effect it not anti aliasing. I am using it for LED purpose but it pixallate. as you can see in image below

![img_20190116_133452](https://user-images.githubusercontent.com/17684135/51234717-94de6300-1993-11e9-8e70-84aa59988263.jpg)

## Steps to reproduce

Add Polka Dot Effect 

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's currently working as intended. Please file this as a feature suggestion.
