### ISSUE TITLE
Frame Drops On APK Buiild. 

### ISSUE THREAD

**Issue by supyoo** [Scirra/Construct-3-bugs#2524]
## Problem description

The project(to Export on Androin APK) will slow down when you exit and restart the app.

It works normally. on PC Browser mode.

## Attach a .c3p

https://play.google.com/store/apps/details?id=com.ananasgame.potmonrush
Alpha test version is being released.
I will add tester account request.

https://www.dropbox.com/s/cj72jlllgv2xrt6/PotMon%20Rush.android.debug.apk?dl=0
Debug APK LINK

## Steps to reproduce

1. Export Project on APK (131 Stable)
2. Install Android Phone
3. Play Game. (nothing is wrong. Normal Speed Play)
4. End App. (and Tap Button to Close All.)
5. ReRun Game.
6. Frame rate DROPS more Than Twice. 

## Observed result

Frame rate DROPS more Than Twice, On RERUN

## Expected result

NORMALLY PLAYING on APK Build

## First affected release

131 Stable

## Affected browsers/platforms

On Pc Browser -> OK NO problem

On Apk Build -> Frame rate Drops

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_2
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 128 mb (0.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid we cannot diagnose issues based only on exported/built projects. For this reason, we require a minimal project demonstrating the issue for bug reports.

FWIW I cannot think of any technical reason this would be the case; two separate runs of the game ought to be identical. I've never seen/heard of any similar issues, so my best guess is that this would be some kind of graphics driver weirdness on the device - in which case it's not to do with Construct and there's nothing much we can do about it.
