### ISSUE TITLE
Safe mode not catching 404 error when it cannot find addon.json or if local server is disable

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#2527]
## Problem description

When developing c3 plugins using a local web server, safe mode does not catch a 404 when trying to locate the addon.json file. for example lets say i shutdown the local web server and did not uninstall the development addon, c3 will not load in safe mode, unless i clear browser cache or restart web server and uninstall the addon. 

## Attach a .c3p

I dont think .c3p file have information about development addons, this happens on all project regardless of weather the adodn is used or not

## Steps to reproduce

1. start local web server 
2. install development addon (very simple addon) you can use the single global template
3. turn off web server
4. restart c3 in safe mode using safemode flag /?safe-mode

## Observed result

you get an error that addon.json cannot be found, opening teh chrome console shows a 404 on the network tab 

Uncaught (in promise) TypeError: Failed to fetch (url: http://localhost:8080/addon.json)

## Expected result

running the editor in safe mode should load construct 3 editor and ignore that addon file 

## First affected release

i was trying this on the latest beta 

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
Safe mode is not designed to protect against all possible faults. There are a number of other potential errors and misconfigurations that prevent the editor from loading in the same way. Safe mode is mainly intended to ensure finished addons (.c3addon files) can be removed even if they are misconfigured. In development mode, the assumption is that if there is an error, you simply correct it in the hosted files and reload the editor.

In this case the error is also clearly described (it states that it failed to fetch the URL to the addon), and is also trivial (just restart the web server), so closing as wontfix.
