### ISSUE TITLE
AJAX.LastData not loading .json files into array once debug apk is built

### ISSUE THREAD

**Issue by cubits12x** [Scirra/Construct-3-bugs#2530]
## Problem description

After creating a large .json array using Construct 3 array editor, AJAX.LastData is used to parse the data into an array. It works fine on web and PC but doesn't work for 1 particular array once the debug apk is built. The affected apk is very large (100,1000 size array) 

## Attach a .c3p

https://drive.google.com/open?id=1YBktLt81R0OSoIbL5vTpYFQPOt6_satW

## Steps to reproduce

1.Load .c3p and build debug apk
2.Install apk and run the game
3.Observe the debug text on the menu screen display 0s (the debug text reads data from the array that is supposed to get filled using AJAX.LastData)

## Observed result

Of the 3 arrays to be filled using AJAX, only 2 are filled. The largest array (100,1000 in size) does not get filled at all

## Expected result

All the arrays are supposed to be filled with their respective .json files using AJAX. This expected outcome works fine on web and PC 

## First affected release

Constrcut 3 r131 stable release

## Affected browsers/platforms

* Chrome: yes/no (No)
* Firefox: yes/no (No)
* Edge: yes/no (No)
* Safari: yes/no (No)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines - we require a minimal project. The provided one has nearly 200 events. Given the high number of reports we get that are just mistakes in events, we require a minimal project to prove it's a problem in Construct.

**Comment by cubits12x** [comment]
Apologies....

I'll prepare a minimal project and re-author the bug report.

Cheers

**Comment by cubits12x** [comment]
Hello, thank you for your help.

I've re-opened a bug report with a minimal project.
Please find it in the link below
https://github.com/Scirra/Construct-3-bugs/issues/2534

Thanks once again. Regards
