### ISSUE TITLE
[r135] Platform behavior can't jump off slope while moving

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#2532]
## Problem description

There was a recent bug fix with the platform behavior in r135 that I believe introduced this new one. I am unable to jump while moving on 45° slopes unless my jump strength is very high.

## Attach a .c3p

https://www.dropbox.com/s/05rekj99chk7wxu/PlatformSlopeJumpBug.c3p?dl=0

## Steps to reproduce

1. Hold right
2. When player is on 45° slopes, press [Up Arrow] to jump. Keep holding right.

## Observed result

The player should jump and turn blue.

## Expected result

The player flickers blue, showing an attempt to jump, but instantly pops back down to the slope.

## First affected release

r135

## Affected browsers/platforms

NW.js

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r135 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 70 gb
Storage usage (approx): 879 mb (1.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can't reproduce anything wrong - it jumps fine every time. Is there a way you can find to reproduce it more reliably?

**Comment by Tokinsom** [comment]
@Ashley I've not gotten a successful jump once over here. Lowering the jump strength might help - I have no issue when it's above 400 or so. You are holding right while jumping on the first slope, correct?

**Comment by AshleyScirra** [comment]
I think I can reproduce this on the gentler slope with a jump strength of 100. I guess delta-time variations make this non-deterministic.

Likely is a side-effect of the fix for #2321 - I'm not surprised, the platform behavior is almost impossible to change without breaking things 😞

**Comment by AshleyScirra** [comment]
I'm still amazed at how many edge cases crop up even years down the line. The behavior is pretty much a towering pile of edge cases at this point.

I think I found a workaround - issue #2321 was specific to jump-thrus, but the fix also applied to solids which seems to have caused this problem. I adjusted the fix to apply exclusively to jump-thrus, so it doesn't come up with solid slopes any more (and jump-thrus cannot be used as slopes). We don't seem to be seeing quite the same thing here so let's check it works as expected when the next release is out.

**Comment by Tokinsom** [comment]
@ashley I suppose it's bound to happen with so many different object types and situations. I remember years ago I suggested a 'modular' element for it that let us disable certain features and interactions as needed, due to bugs & difficulties from trying to cover all bases and find that perfect balance. Though, ideally, it would "just work" with everything so it never gained any traction.

**Comment by Tokinsom** [comment]
@ashley It's fixed! Thank you so much for the quick response and 135.2 release.

**Comment by AshleyScirra** [comment]
Thanks for confirming.
