### ISSUE TITLE
Replace color effect bug

### ISSUE THREAD

**Issue by givemeapixel** [Scirra/Construct-3-bugs#2533]
## Replace color effect bug

I think there might be a glitch in the C3 Runtime. I have an event: On start of layout; Set effect replace color, parameter index 1, to: Dictionary.Get("Player_1_Cape_Color") and the color is replaced with black. So I opened the debugger and found the dictionary key: "Player_1_Cape_Color". I copied the key value. I duplicated the same event as above except instead of: Dictionary.Get("Player_1_Cape_Color") I pasted the key value: rgba255(255, 0, 0, 255). This works perfectly.

I know it is not the parameter because I tried parameters 0 - 5. I also duplicated the same event as above except instead of: Dictionary.Get("Player_1_Cape_Color") I put 0 and the cape was black there too. I don't know what is wrong. Is there a glitch in the C3 Runtime, or am I not doing something right, or can you not replace the effect with an expression like that? Can anybody help me? 

Thank you

**Comment by AshleyScirra** [comment]
Please post to the forum if you need general help or simply want to discuss something. Issues filed here must follow the guidelines.
