### ISSUE TITLE
AJAX.LastData not loading .json files into array once debug apk is built

### ISSUE THREAD

**Issue by cubits12x** [Scirra/Construct-3-bugs#2534]
## Problem description

After creating a large .json array using Construct 3 array editor, AJAX.LastData is used to parse the data into an array. It works fine on web and PC but doesn't work for 1 particular array once the debug apk is built. The affected apk is very large (100,1000 size array)

## Attach a .c3p

https://drive.google.com/open?id=1h2L6EP2cp5S4qWhS0mVQi_7G16WgVbYh

## Steps to reproduce

1.Load .c3p and build debug apk
2.Install apk and run the game
3.Observe the debug text on the menu screen display 0s (the debug text reads data from the array that is supposed to get filled using AJAX.LastData)... The debug2 text displays data from the other arrays filled using the same method.

## Observed result

Of the 3 arrays to be filled using AJAX, only 2 are filled. The largest array (100,1000 in size) does not get filled at all

## Expected result

All the arrays are supposed to be filled with their respective .json files using AJAX. This expected outcome works fine on web and PC

## First affected release

Constrcut 3 r131 stable release

## Affected browsers/platforms

* Chrome: yes/no (No)
Firefox: yes/no (No)
Edge: yes/no (No)
Safari: yes/no (No)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks for the reduced project. It looks like a bug in Cordova. I found a workaround which should fix this for the next release.

**Comment by cubits12x** [comment]
Awesome!  Thank you so much...
I'm really grateful for this.
Thank you.
