### ISSUE TITLE
Renaming included event sheet breaks folder project 

### ISSUE THREAD

**Issue by pkreemer** [Scirra/Construct-3-bugs#2535]
## Problem description
Renaming an _included_ event sheet causes folder project to become invalid (fails to load). 

[rename_sheet.zip](https://github.com/Scirra/Construct-3-bugs/files/2783940/rename_sheet.zip)

## Steps to reproduce
1. Create new project, save as project folder,
2. Add a second event sheet "Event sheet 2",
3. Include 2nd event sheet in first.
4. Save and close project. Re-open and see that project loads.
5. Rename 2nd event sheet to: "Event sheet 2a"
6. Save and close project, and try to re-open.
7. See error "Failed to open project. Check it is a valid Construct 3 project folder."

## Observed result
The event sheet rename is correctly updated in project.c3proj and the actual event sheet filename, but isn't propagating to the including event sheet or to project.uistate.json.
## Expected result
Project should open - event sheet should be correctly renamed in all project files.

## First affected release
Noticed in R134, persists into R135.2

## Affected browsers/platforms
 Win64 Chromium desktop build  (beta channel)

**Comment by AshleyScirra** [comment]
Thanks, good catch. Fixed for next release.

**Comment by pkreemer** [comment]
Nice, thanks!
