### ISSUE TITLE
Webgl blog - links with shader effects not supported on phone

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2536]
## Problem description

Came across blog link while surfing Internet with Phone: https://www.construct.net/en/blogs/construct-official-blog-1/webgl-shader-effects-in-construct-2-780

All three links there, when clicked, show some webgl not supported message on my phone. 
But still links should work on my phone nevertheless. Rly strange they don't.

All three links run just fine on my PC. Are they just some effects to show or they are copypaste from shaders used in c2runtime/c3runtime?

Not sure why this happens, but it might be worth checking out.

## System details

<details><summary>View details</summary>

Graphics Feature Status
Canvas: Hardware accelerated
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Disabled
Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
Out-of-process Rasterization: Disabled
Hardware Protected Video Decode: Unavailable
Rasterization: Hardware accelerated
Skia Deferred Display List: Disabled
Skia Renderer: Disabled
Surface Control: Disabled
Surface Synchronization: Disabled
Video Decode: Hardware accelerated
Viz Service Display Compositor: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
Driver Bug Workarounds
broken_egl_image_ref_counting
clear_uniforms_before_first_program_use
disable_framebuffer_cmaa
disable_program_caching_for_transform_feedback
disable_program_disk_cache
disable_timestamp_queries
dont_disable_webgl_when_compositor_context_lost
force_cube_map_positive_x_allocation
max_copy_texture_chromium_size_1048576
max_msaa_sample_count_4
max_texture_size_limit_4096
multisample_renderbuffer_resize_emulation
scalarize_vec_and_mat_constructor_args
unbind_egl_context_to_flush_driver_caches
use_es2_for_oopr
use_virtualized_gl_contexts
wake_up_gpu_before_drawing
disabled_extension_GL_EXT_disjoint_timer_query
disabled_extension_GL_EXT_disjoint_timer_query_webgl2
disabled_extension_GL_KHR_blend_equation_advanced
disabled_extension_GL_KHR_blend_equation_advanced_coherent
disabled_webgl_extension_EXT_disjoint_timer_query
disabled_webgl_extension_EXT_disjoint_timer_query_webgl2
Problems Detected
Protected video decoding with swap chain is for Windows and Intel only
Disabled Features: protected_video_decode
Non-virtual contexts on Qualcomm sometimes cause out-of-order frames: 289461
Applied Workarounds: use_virtualized_gl_contexts
The first draw operation from an idle state is slow: 309734
Applied Workarounds: wake_up_gpu_before_drawing
Clear uniforms before first program use on all platforms: 124764, 349137
Applied Workarounds: clear_uniforms_before_first_program_use
Always rewrite vec/mat constructors to be consistent: 398694
Applied Workarounds: scalarize_vec_and_mat_constructor_args
glFinish doesn't clear caches on Android: 509727
Applied Workarounds: unbind_egl_context_to_flush_driver_caches
Android Adreno crashes on binding incomplete cube map texture to FBO: 518889
Applied Workarounds: force_cube_map_positive_x_allocation
CHROMIUM_copy_texture with 1MB copy per flush to avoid unwanted cache growth on Adreno: 542478
Applied Workarounds: max_copy_texture_chromium_size_1048576
EGLImage ref counting across EGLContext/threads is broken: 585250
Applied Workarounds: broken_egl_image_ref_counting
Limit max texure size to 4096 on all of Android
Applied Workarounds: max_texture_size_limit_4096
Use GL_INTEL_framebuffer_CMAA on ChromeOS: 535198
Applied Workarounds: disable_framebuffer_cmaa
Disable KHR_blend_equation_advanced until cc shaders are updated: 661715
Applied Workarounds: disable(GL_KHR_blend_equation_advanced), disable(GL_KHR_blend_equation_advanced_coherent)
Program binaries don't contain transform feedback varyings on Qualcomm GPUs: 658074
Applied Workarounds: disable_program_caching_for_transform_feedback
Certain Adreno 4xx and 5xx drivers often crash in glProgramBinary.: 699122
Applied Workarounds: disable_program_disk_cache
Multisampled color renderbuffers can't be resized on Qualcomm 4xx/5xx: 696126
Applied Workarounds: multisample_renderbuffer_resize_emulation
eglSwapBuffers intermittently fails on Android when app goes to background: 744678
Applied Workarounds: dont_disable_webgl_when_compositor_context_lost
glGetQueryObject(GL_QUERY_RESULT_AVAILABLE) blocks unexpectedly on Adreno: 750306, 764526
Applied Workarounds: disable(GL_EXT_disjoint_timer_query), disable(GL_EXT_disjoint_timer_query_webgl2)
Don't expose disjoint_timer_query extensions to WebGL unless site isolation is enabled: 808744
Limit MSAA to 4x on Android devices: 797243
Applied Workarounds: max_msaa_sample_count_4
A deleted query id for GL_TIMESTAMP cannot be reused for other query targets: 858879
Applied Workarounds: disable_timestamp_queries
Frequent crashes on Adreno (TM) on L and below: 866613, 860021
Applied Workarounds: use_es2_for_oopr
Raster is using a single thread.
Disabled Features: multiple_raster_threads
Native GpuMemoryBuffers have been disabled, either via about:flags or command line.
Disabled Features: native_gpu_memory_buffers
Surface Control has been disabled by Finch trial or command line.
Disabled Features: surface_control
Surface synchronization has been disabled by Finch trial or command line.
Disabled Features: surface_synchronization
Viz service display compositor is not enabled by default.
Disabled Features: viz_display_compositor
Skia renderer is not used by default.
Disabled Features: skia_renderer
Skia deferred display list is not used by default.
Disabled Features: skia_deferred_display_list
Version Information
Data exported	2019-01-22T21:42:25.417Z
Chrome version	Chrome/71.0.3578.99
Operating system	Android 7.0
Software rendering list URL	https://chromium.googlesource.com/chromium/src/+/dec090ce558f4dbef3830f7d236d3abecf770594/gpu/config/software_rendering_list.json
Driver bug list URL	https://chromium.googlesource.com/chromium/src/+/dec090ce558f4dbef3830f7d236d3abecf770594/gpu/config/gpu_driver_bug_list.json
ANGLE commit id	f2ed299569c0
2D graphics backend	Skia/71 7469a9341afab19271b8ef07af5c16a0f2c4ccc1-
Command Line	--use-mobile-user-agent --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5 --use-mobile-user-agent --enable-pinch --enable-viewport --validate-input-event-stream --enable-longpress-drag-selection --touch-selection-strategy=direction --main-frame-resizes-are-orientation-changes --disable-composited-antialiasing --enable-dom-distiller --flag-switches-begin --flag-switches-end
Driver Information
Initialization time	163
In-process GPU	false
Passthrough Command Decoder	false
Sandboxed	false
GPU0	VENDOR = 0x0000 [Qualcomm], DEVICE= 0x0000 [Adreno (TM) 506] *ACTIVE*
Optimus	false
AMD switchable	false
Driver vendor	
Driver version	145.0
Driver date	
GPU CUDA compute capability major version	0
Pixel shader version	3.20
Vertex shader version	3.20
Max. MSAA samples	4
Machine model name	Redmi Note 4
Machine model version	
GL_VENDOR	Qualcomm
GL_RENDERER	Adreno (TM) 506
GL_VERSION	OpenGL ES 3.2 V@145.0 (GIT@I3d52eaf367)
GL_EXTENSIONS	GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_multisampled_render_to_texture GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers
Disabled Extensions	GL_EXT_disjoint_timer_query GL_EXT_disjoint_timer_query_webgl2 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent
Disabled WebGL Extensions	EXT_disjoint_timer_query EXT_disjoint_timer_query_webgl2
Window system binding vendor	
Window system binding version	
Window system binding extensions	
Direct rendering	Yes
Reset notification strategy	0x8252
GPU process crash count	0
Compositor Information
Tile Update Mode	One-copy
Partial Raster	Enabled
GpuMemoryBuffers Status
R_8	Software only
R_16	Software only
RG_88	Software only
BGR_565	Software only
RGBA_4444	Software only
RGBX_8888	Software only
RGBA_8888	Software only
BGRX_8888	Software only
BGRX_1010102	Software only
RGBX_1010102	Software only
BGRA_8888	Software only
RGBA_F16	Software only
YVU_420	Software only
YUV_420_BIPLANAR	Software only
UYVY_422	Software only
Display(s) Information
Info	Display[0] bounds=[0,0 360x640], workarea=[0,0 360x640], scale=3, external.
Color space information	{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}
Bits per color component	8
Bits per pixel	24
Video Acceleration Information
Decode vp8	up to 3840x2160 pixels
Decode vp8	up to 3840x2160 pixels (encrypted)
Decode vp9 profile0	up to 3840x2160 pixels
Decode vp9 profile0	up to 3840x2160 pixels (encrypted)
Decode vp9 profile1	up to 3840x2160 pixels
Decode vp9 profile1	up to 3840x2160 pixels (encrypted)
Decode vp9 profile2	up to 3840x2160 pixels
Decode vp9 profile2	up to 3840x2160 pixels (encrypted)
Decode vp9 profile3	up to 3840x2160 pixels
Decode vp9 profile3	up to 3840x2160 pixels (encrypted)
Decode h264 baseline	up to 3840x2160 pixels
Decode h264 main	up to 3840x2160 pixels
Decode h264 extended	up to 3840x2160 pixels
Decode h264 high	up to 3840x2160 pixels
Decode h264 high 10	up to 3840x2160 pixels
Decode h264 high 4:2:2	up to 3840x2160 pixels
Decode h264 high 4:4:4 predictive	up to 3840x2160 pixels
Decode h264 scalable baseline	up to 3840x2160 pixels
Decode h264 scalable high	up to 3840x2160 pixels
Decode h264 stereo high	up to 3840x2160 pixels
Decode h264 multiview high	up to 3840x2160 pixels
Encode vp8	up to 1280x720 pixels and/or 30.000 fps
Encode h264 baseline	up to 1280x720 pixels and/or 30.000 fps

</details>

**Comment by AshleyScirra** [comment]
The blog is 6 years old. If it doesn't reproduce with modern Construct, it's probably some compatibility issue we fixed years ago.
