### ISSUE TITLE
AdjustHSL Effect Not Rendering Transparency Correctly with Certain Colors

### ISSUE THREAD

**Issue by AySquirrel** [Scirra/Construct-3-bugs#2539]
## Problem description

Using the AdjustHSL effect creates a rather unsightly pixealated effect when using alpha channels with certain colors (most notably purple and magenta).

## Attach a .c3p

[AdjustHSL_Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2785787/AdjustHSL_Bug.zip)

## Steps to reproduce

1. Drag the slider bar slowly from left to right, taking note of the appearances of both the circle and the text object as you move further and further right

## Observed result

Upon reaching the purple/magenta hues, anti-aliasing effects within the images turn from transparent and smooth to dark and pixelated, and correct themselves when moving back towards other hues.

## Expected result

The effect to create smooth transparency gradients for all hue values within the gradient.

## First affected release

r120

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: N/A

## System details

<details><summary>View details</summary>

Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

</details>

**Comment by AshleyScirra** [comment]
Huh, looks like some kind of floating point precision or range issue. I've found a workaround for the next release, but note it still happens if you set the hue outside the 0-100% range, so make sure it stays within that range to avoid it happening again.

**Comment by AySquirrel** [comment]
I'll keep that in mind.  Thank you!!
