### ISSUE TITLE
Locked Objects Can Still Be Selected via Drag Box Selection or with Ctrl+A 

### ISSUE THREAD

**Issue by AySquirrel** [Scirra/Construct-3-bugs#2540]
## Problem description

Locked objects can still be selected by clicking and dragging a box around them, or by using the keyboard shortcut Ctrl+A to select all objects (and by selecting the object from the project bar, but I'm guessing that one might be intentional?).  Additionally, all locked objects become unlocked upon closing and reopening the project.

## Attach a .c3p

[LockedObjectTest.zip](https://github.com/Scirra/Construct-3-bugs/files/2789551/LockedObjectTest.zip)

## Steps to reproduce

1. Right click on the sprite in the center of the viewport, and click Lock>Lock selection
2. Once the sprite is locked, click drag a box around it to select it
3. Click anywhere in the layout view off of the sprite to deselect it, and then select it again using the keyboard shortcut Ctrl+A
4. Click off of the object to deselect it once more, and then click on the object again from the Project Bar to select it one last time

## Observed result

The object can still be selected from a multitude of ways even after being locked

## Expected result

The object to remain deselected by any means other than right clicking and unlocking all, or by having some sort of keyboard shortcut to immediately be able to unlock all objects or similar

## First affected release

r120

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: N/A

## System details

<details><summary>View details</summary>

Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed for next release.
