### ISSUE TITLE
IOS Game Stucks & Freezes 

### ISSUE THREAD

**Issue by yeaaqbi** [Scirra/Construct-3-bugs#2543]
## Problem description

I have exported my game to android and IOS, it works perfect on Android but it is some times freezes on iphone! I have debugged the game on XCode and noticed that it gives me the following error. 

IOS: 12.1.2
IPhone 7
<img width="426" alt="screen shot 2019-01-24 at 12 05 25 pm" src="https://user-images.githubusercontent.com/3922086/51671318-53703800-1fd1-11e9-9867-befb0ea61495.png">

**Comment by shortercode** [comment]
@yeaaqbi please complete the full issue template, you have not provided enough for us to replicate this issue.
