### ISSUE TITLE
Advanced Random Plugin breaks mobile export.

### ISSUE THREAD

**Issue by SalmanShhh** [Scirra/Construct-3-bugs#2545]
## Attach a .c3p

https://cdn.discordapp.com/attachments/517079142681018368/538039871311446016/advanced_random_plugin_is_bugged.c3p

## Steps to reproduce

1. open any touch example, but in our case open the "Touch: zooming" example project.
2. add the advanced random plugin to the project.
3. export debug APK.

## Observed result

freezes on the loading screen.  nothing loads. when the project is loaded on a cordova export.
normal HTML5 export played from a phone it works but not from cordova export. 

## Expected result

the example project working as intended.

## First affected release

Noticed first in r134.

## Affected browsers/platforms

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r135.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 158 gb
Storage usage (approx): 361 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Unconected** [comment]
It took me about 3 hours to figure out that Advanced Random was causing it too...
I was exporting to Andoroid 6.0.1
I am using C3 r131 stable.

I had to remove a Text Object and Advanced Random to change to C2 runtime and it started worked when exported.
I added Advanced Random again and it got stuck on loading when exported.
I exported as a signed apk release all times..

**Comment by shortercode** [comment]
Can confirm, the plugin isn't loading correctly in cordova builds. I've written a patch, should be fixed in the next release.
