### ISSUE TITLE
R135-2 exported projects(c2 runtime) don't work in internet explorer 11

### ISSUE THREAD

**Issue by paala** [Scirra/Construct-3-bugs#2546]
## Problem description

R135-2 exported projects(c2 runtime) don't work in internet explorer 11
R131 DO work

## Attach a .c3p

any blank new project with some text can work

## Steps to reproduce

1.Create a new project c2 runtime
2.export
3.host on netlify or any other host.
4. play on internet explorer 11 -
5. the result after loading is just a white image

## Observed result

the result after loading is just a white image

## Expected result

the game loads

## First affected release

not sure R 135 for sure

## Affected browsers/platforms

only internet explorer 11

**Comment by AshleyScirra** [comment]
Thanks, good catch. Fixed for next release.
