### ISSUE TITLE
135-2 editor crashed on adding event

### ISSUE THREAD

**Issue by NoSoul8** [Scirra/Construct-3-bugs#2547]
## Problem description

Editor had a random crash on adding a new event.
It looks like a toxic bug - can't reproduce it myself on a stable basis.
MB at least worth checking screenshot and error message 

## Attach a .c3p

Any sample project

## Steps to reproduce

1. Click on any existing event
2. Press E to add a new event
3. 

## Observed result

![selection_138](https://user-images.githubusercontent.com/34763413/51747000-901b5c80-20c1-11e9-88f3-fca47e771b93.png)

## Expected result

Editor works with no errors

## First affected release

135.2

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: The source image could not be decoded.
Construct 3 version: r135.2
URL: https://editor.construct.net/r135-2/
Date: Fri Jan 25 2019 16:49:44 GMT+0400 (+04)
Uptime: 1955.2 s

Platform information
Browser: Chrome
Browser version: 66.0.3359.117
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
C3 release: r135.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Haswell Desktop 
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, EXT_sRGB, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Going to assign to @AshleyScirra the crash report doesn't have much information in it, but he might be able to locate the problem.

**Comment by AshleyScirra** [comment]
FWIW in the console it looks like there are some network failures so maybe some parts of C3 have failed to load and that is making it unstable.
