### ISSUE TITLE
"Close" action doesn't work in debug mode.

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2549]
## Problem description

The "close" action from the Browser plugin doesn't work if you're on debug mode. It's not a big deal since the final user will probably not be able to access the debugger, but i personally like to use "Esc > Close" during development instead of "Alt+F4".

## Attach a .c3p

[Close Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2796792/Close.Bug.zip)

## Steps to reproduce

1. Start the project in debug mode
2. Try to close it by pressing "Esc"

## Observed result

The "Close" action doesn't work with the debugger.

## Expected result

The "Close" action to work with the debugger.

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release.
