### ISSUE TITLE
Collision boxes are affected by their layers parallax percentage.

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2550]
## Problem description

Collision boxes can be displayed improperly depending on their layers parallax percentage.

Demonstration: https://i.imgur.com/ms7MS5n.gif

## Attach a .c3p

[Parallax Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2796863/Parallax.Bug.zip)

## Steps to reproduce

1. Move the viewport around while in the editor.

## Observed result

Collision boxes are affected by their layers parallax percentage.

## Expected result

Collision boxes to not be affected by their layers parallax percentage.

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Possibly a duplicate of #2485? What release are you using @BonzerKitten7

**Comment by BonzerKitten7** [comment]
Probably, my bad. I'm using the latest beta (R135.2).

**Comment by shortercode** [comment]
I believe the patch for that should have been included in R135.2 so perhaps there is still an issue here. Going to assign to @AshleyScirra to review further.

**Comment by BonzerKitten7** [comment]
Thank you very much, @shortercode.

**Comment by AshleyScirra** [comment]
Fixed for next release.
