### ISSUE TITLE
more problem

### ISSUE THREAD

**Issue by Roguelike2018** [Scirra/Construct-3-bugs#2554]
In the latest stable version, I discovered two problems.

1) when exporting to NW.js in Windows 64, the plug-in video stops working
2) when exporting to NW.js in Windows 64, music does not work

although it all works well in html5

**Comment by Roguelike2018** [comment]
Why did you close this topic without writing anything to me?

**Comment by AshleyScirra** [comment]
Please see the [bug report guidelines](https://github.com/Scirra/Construct-3-bugs). We cannot help you if you do not follow them.
