### ISSUE TITLE
Text from the JSON editor is rendered over the Export popup and other popups

### ISSUE THREAD

**Issue by narFnarF** [Scirra/Construct-3-bugs#2556]
## Problem description

If the JSON editor is currently open in a tab, when opening the Export menu (to pick the export platform), the text from the JSON is rendered on top of the export popup.

This behavior can also be observed with other popups:
* Export popup: https://i.imgur.com/jOYlOma.png
* About popup: https://i.imgur.com/4t5PGHO.png
* New project popup: https://i.imgur.com/lMC7x9Y.png
* Save project popup: https://i.imgur.com/B3tzGxQ.png

In most of these cases, it is not possible to interact with the popup because the cursor clicks in the json text instead (put the cursor in the text instead of clicking the buttons in the popup). **When this happens, the popup cannot be closed and the user must exit and relaunch Construct.**

## Attach a .c3p

https://www.dropbox.com/s/gyomdlrrgan85fp/bug%20json%20text%20over%20popups.c3p?dl=0

## Steps to reproduce

1. Open the JSON file in the project so that it is in the currently opened tab
2. Menu > Project > Export

## Observed result

The JSON text from the JSON editor is rendered over the Export popup. 

## Expected result

The JSON text is rendered behind the Export popup.

## Affected browsers/platforms

* Firefox on Mac OSX Maverick
* Firefox on Windows 10
* _I haven't tested others_

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 64.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
C3 release: r131 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 33 mb (1.6%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    ImageBitmap support is disabled in Firefox due to bug 1472194
    CSS containment is not supported. Editor performance may be significantly degraded.
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmap is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I expect this effects every browser other than Chrome, as it's the only one that supports the dialog element correctly ( we use a polyfill for other browsers ). The text editor library we use was applying some z-index rules to it's content, I've put a reset rule on it which appears to have resolved the problem ( checked in Edge ).
