### ISSUE TITLE
Jumping while next to wall sometimes doesn't work

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2557]
## Problem description

Here is an image of me next to a wall, I am holding right but it doesn't let me jump. This happens in this spot maybe 30% of the time for me?

![image](https://user-images.githubusercontent.com/5744908/51814831-58a2ef00-2311-11e9-8c13-308f4aee612b.png)

![image](https://user-images.githubusercontent.com/5744908/51814960-1928d280-2312-11e9-91fe-4c29adf9b679.png)

I think it only happens that sometimes when I hold right it pushes me 1 pixel into the wall which prevents me from jumping. 

But sometimes when I hold right, it doesn't push me into the wall but I stand next to it, in this lucky case everything works fine.

## Attach a .c3p

[bug with jumping.zip](https://github.com/Scirra/Construct-3-bugs/files/2801431/bug.with.jumping.zip)

## Steps to reproduce

1. Hold right, until you're overlapping the wall by 1 pixel
2. Press Jump (up)

## Observed result

Nothing jumps when you press Jump. 

## Expected result

You should jump, or at least not be allowed to push yourself into the wall by 1 pixel.

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r135.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 111 gb
Storage usage (approx): 789 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can reproduce, but it seems nondeterministic. It looks like the slope tracking and wall hugging algorithms are conflicting somehow. It's very difficult to figure out how precisely. It still reproduces in the C2 runtime so presumably this has been around since forever.

It's absolutely unbelievable the sheer number of incredibly difficult edge cases that keep coming up in the platform behavior. It's been 8 years and they still keep coming...

**Comment by alastajj** [comment]
Thanks for looking into it! Yeah it's crazy, I'm very grateful for being able to use the platform behavior in organize no-grid style of platformers. But yeah there are a lot of strange things, the player and enemies get randomly stuck on things like this a lot!

Is the age of this code making it unwieldy or something?

**Comment by AshleyScirra** [comment]
No, the code is actually better organised in the C3 runtime. It is the sheer subtlety of it. Every single line of code has ramifications and changes are extremely difficult to make without breaking some other extremely specific edge case. I would guess we've had 50+ similar reports over the history of Construct, there just seems to be no end to them.

**Comment by alastajj** [comment]
That's fair. I think we're getting pretty close to having solved all the problems now! Thanks for your work  😃

**Comment by alastajj** [comment]
One way to fix this is to push the platform sprite back 1 pixel from the wall.

Here is a workaround that I think might help:

![image](https://user-images.githubusercontent.com/5744908/59963048-d40b7400-9530-11e9-93e6-95b366800eb6.png)

**Comment by alastajj** [comment]
If it helps, I've created an updated project file to make the bug clearer and included the work around

[platform goes into walls and prevents jumping.zip](https://github.com/Scirra/Construct-3-bugs/files/3316784/platform.goes.into.walls.and.prevents.jumping.zip)

**Comment by AshleyScirra** [comment]
I think I finally got to the bottom of this. Thanks for the improved repro from your last comment, it helped. In theory it could have affected any point solids were intersecting near the Platform behavior, so it's probably quite an important fix. It should all be working correctly in the next release!
