### ISSUE TITLE
Some sounds and music do not work and the "video plugin" does not work either.

### ISSUE THREAD

**Issue by Roguelike2018** [Scirra/Construct-3-bugs#2558]
## Описание проблемы

When exporting to NW.js on Windows 10 x64, there are some issues with some sounds and videos.

He does not want to reproduce some of the sounds and music that I poured into the project. also does not want to work the plugin video

## Прикрепить .c3p

https://roguelike2018.github.io/myprojectx/GE-NE-RA-TOR/GE-NE-RA-TOR pre alfa 0.029 (11).c3p

## Действия по воспроизведению

1. Export to NW.js win64
2. Play
3. To check the video plugin click on "b" to wait until the bonus with bubbles falls on the card and then take this bonus.

## Наблюдаемый результат

<! - Что ты видишь, что происходит? ->

## Ожидаемый результат

The music does not work when the game starts, some sounds do not work and the video does not play when you pick up this bonus on the map

## Первый уязвимый релиз

latest stable version

## Затрагиваемые браузеры / платформы

Windows 10 deskop

* Хром: нет
* Firefox: нет
* Край: нет
* Сафари: нет

## Системные данные

**Comment by AshleyScirra** [comment]
The provided project uses third party addons:

- Plugin Шкала времени (Rex_TimeLine) by Rex.Rainbow
- Behavior Печатная машинка (Rex_text_typing) by Rex.Rainbow

Please see the bug report guidelines, specifically around providing a minimal project, and not using third-party addons. We don't want your entire project.
