### ISSUE TITLE
Some sounds and music do not work and the "video plugin" does not work either

### ISSUE THREAD

**Issue by Roguelike2018** [Scirra/Construct-3-bugs#2559]
## Problem description

When exporting to NW.js on Windows 10 x64, there are some issues with some sounds and videos.

## Attach a .c3p

https://roguelike2018.github.io/myprojectx/GE-NE-RA-TOR/ts.c3p

## Steps to reproduce

1. Export to NW.js win64
2. Play
3. Walk around You will hear no sounds of footsteps or music. Also press 1 to check the video. It will not work

## Expected result

The music does not work when the game starts, some sounds do not work and the video does not play

## First affected release

latest stable version

## Affected browsers/platforms

Windows 10 deskop

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

**Comment by AshleyScirra** [comment]
Some of your music is in MP3 format, and the videos are in MP4 format, neither of which NW.js supports. Ensure all your media is in WebM formats (WebM Opus for audio; WebM VP8/VP9 for video) to ensure they are supported in NW.js. See the manual entries on [Sounds & music](https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/sounds-and-music) and [Video](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/video) for more information.
