### ISSUE TITLE
Duplicate last frame not focused

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#256]
## Problem description

When I Duplicate a frame in the Animations editor, a new frame is created, but is not selected, so when I draw it's not on the last new frame.

## Steps to reproduce

1. Duplicate a frame

## Observed result

You still stay on the current frame

## Expected result

Focus on the new frame duplicated

## Affected browsers

* Chrome: yes/

**Comment by Picoti** [comment]
And it would be great to allow us to select all the frames with SHIFT or CTRL + clics  :-)

**Comment by Picoti** [comment]
And it's very strange : the "Apply to whole animation" option for the Origin Point just work for 1 or 2 frames.

**Comment by DiegoScirra** [comment]
Can you create different issues for each of your comments?

They are not related to the original issue and it will be a lot easier to track them individually.

**Comment by Picoti** [comment]
OK. Done :-)

**Comment by DiegoScirra** [comment]
Fixed in r30.

Thanks for creating the separate issues.
