### ISSUE TITLE
Bug avec polygone objet

### ISSUE THREAD

**Issue by DieppedalleDavid** [Scirra/Construct-3-bugs#2560]
## Problem description

The game does not start.
Object polygon bug.

## Attach a .c3p

https://drive.google.com/open?id=15V7-tpJ0ji-d0d0ggY9PeWHA027Q2SH2

## First affected release

Version R131.

## Affected browsers/platforms

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

No crash report dialog, nothing.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.

**Comment by DieppedalleDavid** [comment]
Merci !
