### ISSUE TITLE
Scrolling issues when editing collisions in images

### ISSUE THREAD

**Issue by Roguelike2018** [Scirra/Construct-3-bugs#2561]
## Problem description

When you edit the collision in an image on a very large scale, the scrolling is reset.

For example, if you take the zoom of the edited image as maximally as possible and scroll in the lower right corner, then when you click on the red collision point, the scrolling becomes in the upper left corner, that is, it is reset.

## Steps to reproduce

1. Create a new project
2. Draw a large image
3. Make the maximum scale in the image editor and move the scroll to the right or lower or upper right corner.
4. Capture the mouse on the red point of the image collision.

## Expected result

Scrolling is reset

## First affected release

latest stable version

**Comment by DiegoScirra** [comment]
Fixed. Thanks for reporting.
