### ISSUE TITLE
Problem with entering the same two-digit number as position for multiple collision polygon vertices

### ISSUE THREAD

**Issue by birbdoy** [Scirra/Construct-3-bugs#2570]
## Problem description

When entering the same two-digit number multiple times consecutively as the x or y position for differing collision polygon vertices (even across differing sprite objects), the second digit will oftentimes be dropped as if you'd only entered one digit. 

A practical example (this is how this happens to me all the time): whenever you want to create any kind of rectangle parallel to both axis, every x and y value will be used twice and this bug will show repeatedly.

No matter what I do, this only happens for two-digit numbers, three-digit numbers work fine.

## Attach a .c3p

No demo project needed, simply create a new project and create a sprite.

## Steps to reproduce

1. Create a sprite, open it in the animation editor and select the collision polygon tool
2. Select a vertice and enter a two-digit number as the x position and a two-digit number as the y position.
3. Select a different vertice and enter the same values again for x and y.

## Observed result

One or both values will be processed incorrectly. The vertice acts as if only one (the first) digit was input. This isn't just a display bug. Deselecting and reselecting the vertice or closing the animation editor, reopening it and selecting the vertice again shows that only the first digit was accepted.

## Expected result

The input should be processed correctly.

## First affected release

r106 seems to be the first release that included this bug. r105 works perfectly but 106 behaves similar to current releases (even if a bit more extreme, repeated numbers are ignored completely in r106).

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r135.4 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.9 gb
Storage usage (approx): 1.5 gb (19.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed.
