### ISSUE TITLE
Crash once several objects delete (all at the same time, selected) from the object list (right).

### ISSUE THREAD

**Issue by DieppedalleDavid** [Scirra/Construct-3-bugs#2574]
## Problem description

Crash once several objects delete (all at the same time, selected) from the object list (right).

## Attach a .c3p

https://drive.google.com/open?id=1pSF8v2y-5u43JqFqQy24CjELg0QL22FZ

## Steps to reproduce

Cannot be reproduced

## First affected release

r135.4 bêta

## Affected browsers/platforms

* Chrome: yes

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r135-4/main.js, line 81, col 149596
Message: Uncaught Error: object type is deleted
Stack: Error: object type is deleted at window.ǃPkn.ǃaI (https://editor.construct.net/r135-4/main.js:81:149602) at t.ǃUA (https://editor.construct.net/r135-4/main.js:81:168867) at n.ǃFX.ǃSI (https://editor.construct.net/r135-4/components/bars/propertiesBar/propertiesBar.js:1:33230) at n.ǃFX.ǃdM (https://editor.construct.net/r135-4/components/bars/propertiesBar/propertiesBar.js:1:24556) at n.ǃFn (https://editor.construct.net/r135-4/components/bars/propertiesBar/propertiesBar.js:1:8310) at ǃP.ǃFE.ǃFo.ǃP.ǃFE [as ǃQBb] (https://editor.construct.net/r135-4/components/bars/propertiesBar/propertiesBar.js:1:720) at ǃP.ǃFE.ǃQWA (https://editor.construct.net/r135-4/main.js:2:222035) at ǃP.ǃFE.ǃQWX (https://editor.construct.net/r135-4/main.js:2:222163) at ǃQWe (https://editor.construct.net/r135-4/main.js:2:221683)
Construct 3 version: r135.4
URL: https://editor.construct.net/r135-4/
Date: Fri Feb 01 2019 18:02:34 GMT+0100 (heure normale d’Europe centrale)
Uptime: 8007.3 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.81
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
C3 release: r135.4 (beta)
Language setting: fr-FR

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
<details><summary>View details</summary>

**Comment by AshleyScirra** [comment]
Sorry, there's almost nothing we can do without steps to reproduce. In this case the crash message does not identify the cause of the problem either. I tried selecting all object types in the project and deleting them all, but it worked fine. Please see the bug report guidelines; do file a new issue if you can find a way to reproduce the issue.

**Comment by DieppedalleDavid** [comment]
Hello, Yes, I remember making a copy of the objects between this project and a new project, otherwise, I don't know, thank you to you.
