### ISSUE TITLE
Animation editor - some frames show bugged behavior when crop applied whole animation

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2578]
## Problem description
I had picture drawn before i draw box on it. Before box i had also other shapes there too, but i did alot of undo and redo, before i end up with this strange bug. 

Not sure if same case, but very similary in some strange case when crop is applied whole animation, it can cut off  sprite edges, when they are not same size.

Long story short, last images disappear, reappear or change their behavior(size etc).  Involves redo&undo and crop applied whole animation, when frames are different size.

## Attach a .c3p
When saved or you close animation editor bug disappears.

## Steps to reproduce
I don't have 100% reliable reproduce yet.

Something along the line: create sprite resize it 50x50. duplicate 3x times. resize each one of them like 40x50,30x50. And apply crop whole animation and undo it. Draw circles on animations, apply crop on all animations again.

In some case crop can cut off animation edges(could be other bug)

## Observed result
Video how it happens. Secount time it happened, frames bugged changed their size.
[LastDrawingsDisappear.zip](https://github.com/Scirra/Construct-3-bugs/files/2824727/LastDrawingsDisappear.zip)

## Expected result

No strange behavior

## First affected release
I don't know

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.81
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
C3 release: r135.4 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.2 gb (9.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SnipG** [comment]
100% reproduce:
1. Create sprite
2. Open animation editor
3. Draw some box,dublicate it 2 times.
4. Select 2 frame, click crop all, undo
5. Select 1 frame, click crop all, undo
6. Select 0 frame, click crop all, undo
7.Click undo 3 times, see 1 frame different - frame 0 will dissapear when you move cursor there when circle tool selected.

**Comment by DiegoScirra** [comment]
This is fixed in the next beta release.

Thanks for reporting.
