### ISSUE TITLE
Кажется плагин "ввод текста"не закрывается любым спрайтом при предварительном просмотре

### ISSUE THREAD

**Issue by Roguelike2018** [Scirra/Construct-3-bugs#2579]
## Problem description

Если вставить плагин "ввод текста" а затем нарисовать спрайт и закрыть спрайтом ввод текста то спрайт в редакторе закрывание "ввод текста" а вот при предварительном просмотре "ввод текста всё равно становится виден"

## Steps to reproduce

1. создать проект
2. создать ввод текста и куда нибудь поставить на макете
3. нарисовать спрайт например чёрный квадрат и закрыть ею "ввод текста"
4. запустить предварительный просмотр

## Observed result

плагин "ввод текста" всё равно показывается выше спрайта

## First affected release

стабильная 131

## Affected browsers/platforms

Предварительный просмотр

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

**Comment by AshleyScirra** [comment]
Please only file bugs in English.
