### ISSUE TITLE
In Add Condition/Action dialog, cursor does not default to search field (Firefox, Safari)

### ISSUE THREAD

**Issue by scmborg** [Scirra/Construct-3-bugs#2583]
## Problem description

When using Firefox (on Mac) or Safari, opening the Add Condition/Action dialog does not automatically move the cursor to the search field as it does on Chrome.

Since there is no keyboard shortcut to move the cursor to the search field, users must manually move the mouse cursor to begin searching.

_Note: I've found that Construct runs much more smoothly in Firefox than Chrome on my 2012 MacBook Pro. However, this one tiny UI issue makes it harder to use Firefox since my funky shoulder limits how effectively I can use the trackpad/mouse._

## Steps to reproduce

1. Open an Event Sheet
2. Press 'E' to add a new event
3. Type some text

## Observed result

Nothing :)

## Expected result

Objects are filtered based on text input

## First affected release

r131 stable

## Affected browsers/platforms

* Chrome: no
* Firefox: yes
* Edge: not tested
* Safari: yes

**Comment by AshleyScirra** [comment]
Fixed for next release.
