### ISSUE TITLE
Line with 1.5 size does not keep its drawn image

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2584]
## Problem description
It could fall under feature request but i put it here anyway.
In animation editor you can draw line with 1 or 2 thickness. But you can also insert for example 1.5
1.1-1.9 have same result. You can have different lines with thickness 1,1.1-1.9, 2 . But when using values between 1 and 2, the line will revert back to 1, when you switch frame or close animation editor. But if you draw it and copy it with selection tool, it keeps it image.
It seems line with unusable thickness 1.5 is real thickness of 2, and 2 is 3

Image: line with thickness 1, then 2, then 1.5, then copy of 1.5
![linethickness_bug](https://user-images.githubusercontent.com/28864889/52222089-590c2e80-28ab-11e9-9599-aae6ef0eac05.jpg)

## Steps to reproduce

1.Draw line with thickness 1, then 2, then with thickness between 1-2
2.See line with thickness between 1-2 will revert it image back to 1

## Observed result
When using float point thickness for line, it will revert its image. But you can still copy it and keep it, but it will need selection tool.

## Expected result

As line with thickness 2 seems to have thickness 3 and not 2.
Values we draw should be corresponding to different lines, not line to value. Atm we have no way to draw some lines bc, there is no value for it.
Input should be like 1,2,3,4 corresponding to different line thickness not some other value.

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.81
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
C3 release: r135.4 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.2 gb (9.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
It looks like fractional thicknesses are only being applied properly the first time around. After that, anything that triggers a change, like changing the current frame, changing the current animation, undoing or closing the editor will produce the wrong width line.

I imagine fractional widths would only make sense when the smooth toggle in on, though. When drawing sharp lines it would only make sense to clamp the thickness as there is no way to draw half pixels. 

I don't understand what you mean by lines of thickness 2 being of thickness 3 though. It looks like when you draw a horizontal line with thickness 2 the tool produces a line of 2 pixels width and the same goes for thickness 3 and so on.

**Comment by SnipG** [comment]
Yeah, when i tried drawing line with ideal angle 0 , 45 , 90  Even 1.5 line is correct, you see difference when line thickness is between them.

I don't know how it should be. Just made issue as there is such behavior. You can close if it is correct. ye you can apply this 1.2 etc to pencil too get smooth values. So not sure if it should be fixed or let users use it who like to input custom values.

**Comment by DiegoScirra** [comment]
I ended up finding out that all the drawing tools where producing inconsistent results when manually inputting sizes with a fractional part.

Now all tools that use a size (or similar input) will just use the whole part of the number. Will later look into making sure the inputs only allow for whole numbers.
