### ISSUE TITLE
INVALID ICON FILE (256.PNG) WHEN BUILD PROJECT

### ISSUE THREAD

**Issue by FalconApp** [Scirra/Construct-3-bugs#2587]
## Problem description

Hi, I just bought the C3 license. When I export to "android cordova", the result says an invalid icon / icon / 256.png error. Please help me to fix that.

## System details

Construct3 r131 [stable]

**Comment by DiegoScirra** [comment]
Can you provide the project which is causing the error?

We can look at it and figure out what is happening?
