### ISSUE TITLE
for projects that have been saved "before" a stable version of r131 I do not work new plugins.

### ISSUE THREAD

**Issue by Roguelike2018** [Scirra/Construct-3-bugs#2589]
## Problem description

![image](https://user-images.githubusercontent.com/46905225/52291337-2df50e00-2983-11e9-9b34-1587c728a35c.png)

![image](https://user-images.githubusercontent.com/46905225/52291424-5aa92580-2983-11e9-8083-730a758e22ec.png)

although the add-ons managers have these new plugins

## Attach a .c3p

[test2.zip](https://github.com/Scirra/Construct-3-bugs/files/2833134/test2.zip)

## Steps to reproduce

1. open the attached project and try to add these new plugins to the layout and you will see that they will not be listed

## First affected release

stabile 131

## Affected browsers/platforms

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

**Comment by AshleyScirra** [comment]
Check the project runtime setting. See the blogs and documentation about the release of the new runtime.

**Comment by Roguelike2018** [comment]
![image](https://user-images.githubusercontent.com/46905225/52299906-abc31480-2997-11e9-94ca-602ae3600a7f.png)
