### ISSUE TITLE
Sphere Effect in C3 spreads when it is been dragged to the edge of the screen.

### ISSUE THREAD

**Issue by sangeeth786** [Scirra/Construct-3-bugs#2590]
## Problem description

Construct3  r135-4
**Sphere Effect** spreads when it is been dragged to the edge of the screen.

## Attach a .c3p

[zoom_sniper.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2836282/zoom_sniper.c3p.zip)

## Steps to reproduce

1. Preview in C3 and drag the object to any edge of the screen
2. Preview in real device and drag the object to any edge of the screen

## Observed result

Sphere Effect spreads when it is been dragged to the any edge of the screen.

## Expected result

Sphere Effect not be spread when it is been dragged to the edge of the screen because the effect works well on the centre of the screen.

## First affected release

Construct3 r135-4

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release.

**Comment by sangeeth786** [comment]
@AshleyScirra it has not been fixed in r136

**Comment by AshleyScirra** [comment]
The next release is not out yet.

**Comment by sangeeth786** [comment]
@AshleyScirra ok thanks alot,
please do have a look out on this issues too
https://github.com/Scirra/Construct-3-bugs/issues/2516
https://github.com/Scirra/Construct-3-bugs/issues/2396

**Comment by sangeeth786** [comment]
@AshleyScirra this effect has not been fixed in r-137 still the effect spreads at the viewport edges.

**Comment by AshleyScirra** [comment]
I verified this was working. If something else is wrong please file a new issue following all the guidelines.

**Comment by sangeeth786** [comment]
@AshleyScirra you can check this file once again and just drag the effect to the left edge of the screen .

**Comment by AshleyScirra** [comment]
I double-checked, and yes, it is still working correctly for me now.

**Comment by sangeeth786** [comment]
@AshleyScirra ![screen shot 2019-02-18 at 5 32 09 pm](https://user-images.githubusercontent.com/40767502/52949741-2a11b480-33a3-11e9-8a5f-97f19a7fc24a.png)

**Comment by sangeeth786** [comment]
to the left edge of the preview the effect gets spread out like a square shape you can see in the screenshot attached above

**Comment by AshleyScirra** [comment]
That's different to what it used to do, so would be a different bug report. It also may be the correct result since it's trying to sample pixels off-screen that have not been rendered.
