### ISSUE TITLE
Adding two Replace Color effects to a layout flips the canvas

### ISSUE THREAD

**Issue by backontheteam** [Scirra/Construct-3-bugs#2591]
## Problem description

When your project's fullscreen quality is set to Low, adding two Replace Color effects to a layout flips the canvas when you preview the layout. If you add a third Replace Color effect or change fullscreen quality to high, it will show the canvas right-side-up on preview. 

## Attach a .c3p

[flippy.zip](https://github.com/Scirra/Construct-3-bugs/files/2837971/flippy.zip)

## Steps to reproduce

1. The attached project has two Replace Color effects applied to one layout, and there are no events.
2. Make sure fullscreen quality is set to Low.
3. Preview the layout, and it should flip the sprite upside-down.
4. Remove one of the Replace Color effects (or add a third one), and the canvas will display correctly on preview.
5. You can also have two Replace Color effects on a layout with fullscreen quality set to High, and it will display correctly.
6. This doesn't seem to affect the canvas the same way when your Replace Color effects are applied to Sprites.

## Observed result

The canvas is flipped when you have an even number of Replace Color effects applied to a layout, and fullscreen quality is set to low.

## Expected result

I expected the new colors to be applied to the layout without flipping it.

## First affected release

I traced this back to r122. It was displaying correctly in r121, but r122 had it flipped.

## Affected browsers/platforms

On Windows 10:

* Chrome: yes
* Firefox: yes
* Edge: no - it displayed correctly on Edge

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r136 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 92 mb
Storage usage (approx): 27 mb (28.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
May be related to #2121

**Comment by Wackytoaster** [comment]
FYI I just encountered this with noise+warpLayout on a layer.

**Comment by Dramamini** [comment]
It doesn't matter what effect you are using. Problem occurs using any effect on the layout. For example, in Ghost Shooter Demo:  Let's say I want to add brightness to Layout1. First thing I notice is that explosion spite has now black background. (Explosion spite has blend mode set to additive and with layout effect inserted, is like going back to normal blend mode) Then, if I add a second effect to the layout -for example contrast- the hole background in working area, is being black and canvas is flipped on preview.

Some photos:

(No effect)
![no effect](https://user-images.githubusercontent.com/53188782/61868568-51385900-aee2-11e9-9c79-34f328088da2.jpg)

First effect added:
![effect-1](https://user-images.githubusercontent.com/53188782/61868594-61e8cf00-aee2-11e9-9080-d2635f8c9016.jpg)

Second effect added:
![effect-2](https://user-images.githubusercontent.com/53188782/61868617-6b723700-aee2-11e9-80c4-5a5faad5e6e7.jpg)

**Comment by QuasarX** [comment]
Tint + DropShadow flipping too.

**Comment by AshleyScirra** [comment]
OK, fingers crossed this should be fixed in the next release...
