### ISSUE TITLE
Phonegap build does not support construct-mobile-plugin

### ISSUE THREAD

**Issue by cjl014** [Scirra/Construct-3-bugs#2593]
## Problem description

After your stable release, building to https://build.phonegap.com after exporting via Android/Cordova shows errors. No changes were made to the project, just the upgrade to the stable release of Construct..
My project uses your MobileIAP plugin.

## Steps to reproduce

1.
2.
3.

## Affected browsers/platforms

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

.........
.................Updating icons at ../app/src/main/res
  delete ../app/src/main/res/mipmap-hdpi/icon.png (no source)
  delete ../app/src/main/res/mipmap-ldpi/icon.png (no source)
  delete ../app/src/main/res/mipmap-mdpi/icon.png (no source)
  copy  www/icons/icon-128.png ../app/src/main/res/mipmap-xhdpi/icon.png (updated file)
  delete ../app/src/main/res/mipmap-xxhdpi/icon.png (no source)
  copy  www/icons/icon-256.png ../app/src/main/res/mipmap-xxxhdpi/icon.png (updated file)
Updating splash screens at ../app/src/main/res
  delete ../app/src/main/res/drawable-land-hdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-ldpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-mdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-xhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-xxhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-xxxhdpi/screen.png (no source)
  copy  www/icons/default@2x~universal~anyany.png ../app/src/main/res/drawable-mdpi/screen.png (new file)
  delete ../app/src/main/res/drawable-port-hdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-ldpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-mdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-xhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-xxhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-xxxhdpi/screen.png (no source)
This app does not have additional resource files defined
Prepared android project successfully
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser" at "3.0.0" for android
Android Studio project detected
Fetching plugin "construct-mobile-purchase@1.1.0" via npm
Installing "construct-mobile-purchase" at "1.1.0" for android
Android Studio project detected
Fetching plugin "construct-mobile-advert@1.2.6" via npm
Installing "construct-mobile-advert" at "1.2.6" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.3.3" for android
Android Studio project detected

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
Fetching plugin "construct-play-games@1.0.14" via npm
Installing "construct-play-games" at "1.0.14" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Android Studio project detected
--------------------------------------------------------------------------------
PROJECT PROPERTIES
--------------------------------------------------------------------------------
# This file was originally created by the Android Tools, but is now
# used by cordova-android to manage the state of the various third party
# libraries used in your application

# This is the Library Module that contains the Cordova Library, this is not
# required when using an AAR

# This is the application project.  This is only required for Android Studio Gradle projects

# Project target.
target=android-26
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=com.google.android.gms:play-services-ads:16.0.0
cordova.system.library.2=com.google.android.ads.consent:consent-library:1.0.3
cordova.system.library.3=com.google.android.gms:play-services-games:+
cordova.system.library.4=com.google.android.gms:play-services-identity:+
cordova.system.library.5=com.google.android.gms:play-services-auth:+
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Android Studio project detected
studio
:wrapper

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
Exception while marshalling /opt/android-sdk/build-tools/26.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/extras/google/instantapps/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platform-tools/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-28/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/build-tools/26.0.3/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/extras/google/instantapps/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platform-tools/package.xml. Probably the SDK is read-only
Exception while marshalling /opt/android-sdk/platforms/android-28/package.xml. Probably the SDK is read-only
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_d34awd51nh0qbzvqa99grlcbh.run(/app/build.gradle:143)
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:checkReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:prepareLintJar
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:platformAttrExtractor
:CordovaLib:processReleaseManifest
:CordovaLib:javaPreCompileRelease
:CordovaLib:processReleaseJavaRes NO-SOURCE
:app:preBuild UP-TO-DATE
:app:preReleaseBuild
:app:compileReleaseAidl
:CordovaLib:packageReleaseRenderscript NO-SOURCE
:app:compileReleaseRenderscript
:app:checkReleaseManifest
:app:generateReleaseBuildConfig
:app:prepareLintJar
:app:generateReleaseResValues
:app:generateReleaseResources
:app:mergeReleaseResources
:app:createReleaseCompatibleScreenManifests
:app:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:app:splitsDiscoveryTaskRelease
:app:processReleaseResources
:app:generateReleaseSources
:app:javaPreCompileRelease
:app:compileReleaseJavaWithJavac/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:33: error: package com.android.vending.billing does not exist
import com.android.vending.billing.IInAppBillingService;
                                  ^
/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:102: error: cannot find symbol
    IInAppBillingService mService;
    ^
  symbol:   class IInAppBillingService
  location: class IabHelper
/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:234: error: package IInAppBillingService does not exist
                mService = IInAppBillingService.Stub.asInterface(service);
                                               ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /app/src/main/java/com/scirra/ConstructPlayGames.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
27 actionable tasks: 27 executed
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:33: error: package com.android.vending.billing does not exist
import com.android.vending.billing.IInAppBillingService;
                                  ^
/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:102: error: cannot find symbol
    IInAppBillingService mService;
    ^
  symbol:   class IInAppBillingService
  location: class IabHelper
/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:234: error: package IInAppBillingService does not exist
                mService = IInAppBillingService.Stub.asInterface(service);
                                               ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /app/src/main/java/com/scirra/ConstructPlayGames.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
</details>

**Comment by shortercode** [comment]
I patched this plugin during the last cycle to work with the latest version of cordova CLI, no doubt this has broken compatibility with PGB. I will investigate this, but if it turns out we can only be compatible with one then cordova CLI will get preference over PGB.

You should still be able to build by specifying `construct-mobile-purchase` to be an older version ( 1.0.7 should work with PGB I believe ).

**Comment by cjl014** [comment]
Okay great, thanks. The workaround works for now.

**Comment by shortercode** [comment]
Okay I've reviewed this and without breaking cordova CLI compatibility we cannot support PGB at the moment as well.

Basically we need cordova `8.1.4+`to build the `construct-mobile-purchase` plugin, the highest you can select on PGB is `8.1.1` and we request 8.0.0 in the config file ( for some crazy reason 6.5.0 is the default version... ). Supporting `8.1.1` would break `8.1.4` builds so I'm just going to leave it as the newer version for now. PGB should catch up eventually, and then the config generation script will need updating.

**Comment by cjl014** [comment]
Okay sounds good. Thanks for looking into this.

**Comment by kingpirux** [comment]
so we have to wait for cordova 9 ? it aslo breaks in android studio.

**Comment by AshleyScirra** [comment]
In July 2019 PhoneGap Build [added support for CLI-9.0.0](https://blog.phonegap.com/cli-9-0-0-support-has-been-added-to-phonegap-build-da92fff6d588). As of C3 r184, we now export Cordova projects that are set to use this (`<preference name="phonegap-version" value="cli-9.0.0" />`), and we use `cordova-plugin-purchase` for Mobile IAP (v10.0.1, which is the latest). For some reason PhoneGap Build complains if the deployment target is set to 12.0 for iOS; you can work around that by setting it back to 10.0 (`<preference name="deployment-target" value="10.0" />`). Then it builds but fails with the following error:

`Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-plugin-purchase`

The build log shows errors compiling `cordova-plugin-purchase`. I don't know why their build fails (our own build service seems to handle this fine), it might be connected to the fact the deployment target of 12 does not appear to be supported. Anyway this is out of our hands - we don't have control over PhoneGap Build. It would be best to contact PhoneGap Build's support and follow up with them.
