### ISSUE TITLE
Unable to open construct 3 r136

### ISSUE THREAD

**Issue by RichardMarks** [Scirra/Construct-3-bugs#2594]
## Problem description

Was previously able to load the editor fine. Just tried to load the editor and get an error 

## Attach a .c3p

No project is applicable, cannot open the editor itself suddenly.

## Steps to reproduce

1. Navigate to https://editor.construct.net in Chrome on Windows 8.1
2. N/A
3. N/A

## Observed result

```
Error loading! Try disabling browser addons, they can sometimes break Construct 3.
Javascript error: Uncaught SyntaxError: missing ) after argument list
https://editor.construct.net/r136/behaviors/movements/pathfinding/behavior.js, line 1
```

## Expected result

The Construct 3 editor start page like was there every day for weeks now...

## First affected release

r136 is what it says

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes
* Edge: N/A
* Safari: N/A

## System details

<details><summary>View details</summary>

...no editor == no menu

</details>

**Comment by AshleyScirra** [comment]
We've tried loading it on several devices and it works fine. We've also not had any reports from other users, so it appears isolated to your case. I would guess it's either a buggy browser extension - try disabling them like it suggested - or maybe some kind of caching issue (try clearing the browser cache).

**Comment by RichardMarks** [comment]
@AshleyScirra isolated or not, I have already done everything the error suggested, and I have cleared the cache and tried restarting the browser and restarting the computer. This being a paid subscription, it's not acceptable to simply dismiss the issue. I need someone to work with me to resolve the issue.

**Comment by RichardMarks** [comment]
@AshleyScirra I don't know what you did, or if you didn't do anything, why it works, but all of a sudden it's now working as it should and I didn't do anything different, so thanks.
