### ISSUE TITLE
Facebook Instant Game Ads - After showing an ad tween animations slow down 

### ISSUE THREAD

**Issue by cerxer** [Scirra/Construct-3-bugs#2595]
## Problem description

There is a slow down with tween animations with r136 after showing a couple inter or rewarded ad. If i build game with r131 there is no problem, but with r136 after showing 2-3 ad when player returns game tween animations really slow down. I use new Instant game plugins "show inter ad" and "show rewarded ad" actions with r136; with r131 "show ad".
There seem to be a problem with updated Instant game plugin. 

## Attach a .c3p

Cant provide a c3p but below is a link to a video recording of the problem
https://drive.google.com/open?id=1MkZBAkr8E90YSAW7cmi4fHDe03OS4ZLs

## Steps to reproduce

1. Click show ad button
2. After showing ads 2-3 times, click image to observe getting bigger and slower

## Observed result

After showing some ads tween animations plays jerky and slow.

## Expected result

Playing tween animations with no problem.

## First affected release

after updated Instant game plugin

## Affected browsers/platforms

I'm facing it with an android device.

**Comment by AshleyScirra** [comment]
I think this is another case of #2403. It's a bug in Instant Games which we're still waiting on Facebook to fix: https://developers.facebook.com/support/bugs/557900621304566/
