### ISSUE TITLE
Verify autocomplete works on Android

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#26]
## Problem description

Original report here: https://www.scirra.com/forum/android-canary-events-actions-input-unusable_t189539

> Trying to add a simple touch.x to an action, and autocomplete is going crazy.
Text goes red, and intellisense kicks in, obstructed by the keyboard(landscape mode), and original text and additional letters are concatenated to "TTo"
Hitting the x gets even crazier.

**Comment by pigmalien** [comment]
![screenshot_2017-04-07-11-11-44](https://cloud.githubusercontent.com/assets/16654934/24806619/6c8a6d8c-1b83-11e7-8c3b-5a89684bdc4c.png)
Just wanted to add that text worked fine for naming a project in r16. I don't really care for intellisense any way. Disabling it would be a welcome option, as well as a quick fix.

**Comment by AshleyScirra** [comment]
I've tested this on a Nexus 9 and a HTC 10. I can't reproduce any issue with the text inserting extra characters. When the on-screen keyboard pops up, if I enter "Touch", then that is what is entered in to the parameter.

**Comment by AshleyScirra** [comment]
I made some improvements to the autocomplete usability for r32, it'd be worth checking if that helped when it's out.

**Comment by pigmalien** [comment]
Just tested on the original device( Amazon Fire Tablet), and it appears to be working with out the concatenation. (r31)

**Comment by AshleyScirra** [comment]
@pigmalien r32 is out now, can you check if it is working OK?

**Comment by pigmalien** [comment]
Editing is obstructed by intellisense, and the on screen keyboard in landscape.
For portrait, when you select something from intellisense it returns nothing.
Normal input seems fine.

**Comment by AshleyScirra** [comment]
Think the autocomplete covering the input is really due to #138 (the Android keyboard shunts the whole viewport around which is really awkward, Google is working on a better way to handle it)

It works to accept autocomplete by pressing enter on the keyboard on Android, but you're right, double-tapping an actual autocomplete entry doesn't work. I think I'll file a separate issue for that.

**Comment by AshleyScirra** [comment]
Filed #397
