### ISSUE TITLE
Construct crashed on loading a c3p file

### ISSUE THREAD

**Issue by kondokuro** [Scirra/Construct-3-bugs#260]
After downloaded a c3p file from google drive, possibly saved on r27 and being opened on r29 the project crashed. The file saved on r28 did not crash.

[https://drive.google.com/open?id=0B7FXwkkANhsJZUxjLUJ5MnJCdGs](https://drive.google.com/open?id=0B7FXwkkANhsJZUxjLUJ5MnJCdGs)

## Steps to reproduce

1. Load a c3p file, saved on a couple of release version previous to the current one
2. Construct crashes

## Observed result

Construct crashes

## Expected result

Construct loads the c3p file

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: tree item count mismatch
Stack: Error at Function.ǃJ.ǃugV (https://editor.construct.net/r29/main.js:2:226980) at te (https://editor.construct.net/r29/main.js:2:196353) at window.assert (https://editor.construct.net/r29/main.js:2:196773) at ǃJ.ǃT.ǃVH.ǃVa.ǃrX (https://editor.construct.net/r29/main.js:2:496764) at window.ǃuB.ǃuB.ǃvr (https://editor.construct.net/r29/components/bars/projectBar/projectBar.js:1:32321) at window.ǃuB.ǃuB.ǃIM (https://editor.construct.net/r29/components/bars/projectBar/projectBar.js:1:32378) at Array.ǃJv.ǃJ.ǃH.ǃJ.ǃJ_.ǃJn.m (https://editor.construct.net/r29/components/bars/projectBar/projectBar.js:1:1978) at ǃJ.Event.ǃuOB.ǃuXu (https://editor.construct.net/r29/main.js:2:285656) at window.ǃxya.dispatchEvent (https://editor.construct.net/r29/main.js:2:284047) at window.ǃxya.ǃTP (https://editor.construct.net/r29/main.js:162:38568)
Construct 3 version: r29
URL: https://editor.construct.net/
Date: Thu May 18 2017 19:48:35 GMT-0400 (EDT)
Uptime: 157.9 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Ivybridge Mobile 
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by sielxm3d** [comment]
The same problem again.

**Comment by kondokuro** [comment]
reproduced once on my end

**Comment by DiegoScirra** [comment]
That link you posted is no longer working, was that your project?

**Comment by AshleyScirra** [comment]
@DiegoScirra the markup for the link was wrong, I fixed it so it's clickable now

**Comment by DiegoScirra** [comment]
Fixed in r30.

Thanks for reporting and look out for the next release!
