### ISSUE TITLE
Canvas pastes image without considering object Z order change.

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2600]
## Problem description
Was playing around with canvas, and saw some strange case.
When you paste with canvas and like to move the pasted object z order, then canvas always paste before the move, giving you different output.
At first i thought i paste just last instance and it appears on top.  
Maybe i am missing something, so i am not sure here.
I have read: https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/drawing-canvas
And i know canvas does paste at end event logic. But from this it should take z order into account. 

## Attach a .c3p
[CanvasPaste_Zorder_Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2850324/CanvasPaste_Zorder_Bug.zip)

[Canvaspaste_Zorder_Bug2.zip](https://github.com/Scirra/Construct-3-bugs/files/2850331/Canvaspaste_Zorder_Bug2.zip)

## Steps to reproduce
1. Preview examples
2. First create sprite, move it below others and do canvas paste. Canvas paste it top of others, but should paste image when last instance appears bottom.
3. 

## Observed result
When object z order changes, canvas paste does not take it into account.

## Expected result
Able to move object z order and paste accordingly?

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.96
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
C3 release: r136 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 969 mb (7.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SnipG** [comment]
In second example if i move paste action under first system  create action, it somehow works. Not sure why it works there and not under second  system create?

**Comment by AshleyScirra** [comment]
The first case should be fixed for the next release (it's pasting in instance order, not Z order).

I don't think the second case is a bug. You move an object under the Drawing Canvas itself and then paste it in to the canvas. In this case it still pastes on top of everything else drawn in the canvas. So in this case the canvas will still appear to be continually drawing on top.

**Comment by SnipG** [comment]
I fiddled aroud with case, when i spawn particles/sprites behaind canvas, paste particles on canvas and canvas has effect applied. So you get correct effect result/position. If effect is on layer you might get incorrect result on some effects, or when it's on particles and particles are not middle of layer.  

Anyway, case you fixed might change this behavior too.
