### ISSUE TITLE
Screen Recording - Manual stop doesn't trigger "on recording ready" condition

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#2602]
## Problem description
When starting a screen recording, everything works as expected but when manually closing it using the native overlay, there doesn't seem to be a way for C3 to know that the recording has stopped. I assume this is a bug with the "on recording ready condition", thinking that the recording is still going.

## Attach a .c3p

_Screen recording example_

## Steps to reproduce

1. Open and run example project
2. Start screen recording
3. Select screen (if dual monitor)
4. Click on "Stop sharing"

_Native UI:_
![screenrecbug](https://user-images.githubusercontent.com/15656049/52576741-012c7500-2e21-11e9-8657-6f5ea52d8d89.PNG)

## Observed result
There is no way to know if a screen recording has been stopped manually. The condition that detects if a recording has been stopped and ready, isn't working as expected.

## Expected result

The condition "On Recording Ready" should fire when a screen recording has been manually stopped.

## First affected release

r137 (beta)

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.96
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
C3 release: r137 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 309 mb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by TheRealDannyyy** [comment]
This comment has nothing to do with the issue itself. 
Just out of interest. Is there a way to replace "share" with "record" or disable the native UI as a whole?

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.

There's currently no way to customise the message. If you click "Hide" then the UI appears to be removed as a whole.
