### ISSUE TITLE
"Pick nth instance" doesn't work

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#2603]
## Problem description

Picking nth instance doesn't work, resulting that picked instance doesn't tween.

## Attach a .c3p

[pick_nth_instance_bug (1).zip](https://github.com/Scirra/Construct-3-bugs/files/2853333/pick_nth_instance_bug.1.zip)

## Steps to reproduce

1. use left and right arrow keys to navigate between instances

## Observed result

Doesn't work.

## Expected result

Picked instance should tween.
## First affected release

R136, R137

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's a mistake in your events. "Pick SQUARE instance SQUARE_SELECTED" is constantly true, but with a different instance picked. "Trigger once" does not care that a different instance is picked; it just sees that it's constantly true. So it triggers once only and prevents the event running until it's false.
