### ISSUE TITLE
Facebook instant games export failed with build r137

### ISSUE THREAD

**Issue by cerxer** [Scirra/Construct-3-bugs#2604]
## Problem description

Can't get a Facebook Instant Game export with build r137. I try with chrome (71) and safari browsers.

## Steps to reproduce

1. 
2.
3.

## Observed result

Seeing "Failed to export project" pop up.

## Expected result

Successful build.

## Affected browsers/platforms

Chrome: yes
Safari: yes

## System details

This is the error:

Failed to load resource: the server responded with a status of 404 ()
main.js:177 Error exporting:  Error: error fetching https://editor.construct.net/r137/exporters/instant-games/files/index.html (404 )
    at t (main.js:2)
ǃQK @ main.js:177
/r137/exporters/instant-games/files/index.html:1 Failed to load resource: the server responded with a status of 404 ()
main.js:177 Error exporting:  Error: error fetching https://editor.construct.net/r137/exporters/instant-games/files/index.html (404 )
    at t (main.js:2)
ǃQK @ main.js:177
The FetchEvent for "https://editor.construct.net/r137/" resulted in a network error response: the promise was rejected.
Promise.catch (async)
(anonymous) @ sw.js:444
The FetchEvent for "https://editor.construct.net/r137/cloud/sandbox.html" resulted in a network error response: the promise was rejected.
Promise.catch (async)
(anonymous) @ sw.js:444
sw.js:386 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at HandleFetch (sw.js:386)
HandleFetch @ sw.js:386
Promise.then (async)
(anonymous) @ sw.js:444

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RichardAstrom** [comment]
I get the same error!

**Comment by AshleyScirra** [comment]
There was an issue with the build system that is causing this to fail. It's fixed for the next release - in the mean time continue exporting with r136. Separately, Facebook advise that the Instant Games bug should be fixed shortly, so the workaround won't be needed.
