### ISSUE TITLE
ERRORS OF THE BROWSER VERSION IN THE PLAY MARKET

### ISSUE THREAD

**Issue by idjer83** [Scirra/Construct-3-bugs#2605]
Hello! I do not speak English, I use Google translator. It is hard for me to write once again about the problem that I have already written on the construct.net forum, there are screenshots to understand the problem. Please solve the problem
https://www.construct.net/en/forum/construct-3/general-discussion-7/errors-of-the-browser-version-141688

**Comment by AshleyScirra** [comment]
Please don't cross-post forum posts to the bug tracker. You must follow all the bug report guidelines to post here, or your report will be closed.
