### ISSUE TITLE
Tilemap collision polygons doesn't show in editor anymore

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2606]
## Problem description

Even with the "show collision polygons" ticked the collision polygons wont show on any tilemap.

## Attach a .c3p

[Tilemap.zip](https://github.com/Scirra/Construct-3-bugs/files/2856233/Tilemap.zip)

## Steps to reproduce

1. Tick the "show collision polygons" in the editor.

## Observed result

The collision polygons doesn't show.

## Expected result

The collision polygons to show.

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Looks like a regression from r135+. Thanks, fixed for next release.
