### ISSUE TITLE
the action "fade volume" is not supported at runtime c2

### ISSUE THREAD

**Issue by Roguelike2018** [Scirra/Construct-3-bugs#2607]
how to fix?

![image](https://user-images.githubusercontent.com/46905225/52676862-a38d4b00-2f3c-11e9-8ded-e5920b6979d4.png)

**Comment by shortercode** [comment]
The "Fade volume" action is only supported in the C3 runtime.

You haven't completed the issue report, so I am unable to tell what you are doing. If you are trying to change from the C3 to the C2 runtime then you should remove that action.

If you believe this is a bug please file a report with reproduction steps and a project that demonstrates the problem.

**Comment by Roguelike2018** [comment]
> The "Fade volume" action is only supported in the C3 runtime.
> 
> You haven't completed the issue report, so I am unable to tell what you are doing. If you are trying to change from the C3 to the C2 runtime then you should remove that action.
> 
> If you believe this is a bug please file a report with reproduction steps and a project that demonstrates the problem.

I would like this feature to be supported at runtime c2

**Comment by AshleyScirra** [comment]
No new features will be added to the C2 runtime.

**Comment by Roguelike2018** [comment]
why?

**Comment by AshleyScirra** [comment]
It's been replaced with the C3 runtime, which has a better architecture which makes new features possible where they were infeasible before. We're also a small team and we don't have the resources to add new features to both.
