### ISSUE TITLE
Nodes connecting events are "broken"

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#2608]
## Problem description

Simply, the nodes that are connecting events in the event sheet, are "broken". Also, i think it could be more visible for more elegance. 
![aa17b8a6-cefc-4580-9007-fc3f9e8f20df](https://user-images.githubusercontent.com/31414273/52678248-4b048080-2f31-11e9-80a8-0d25b78904ac.png)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Please file suggestions to change existing features here: https://construct3.ideas.aha.io
