### ISSUE TITLE
Crash Every Time I change animation Name

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2609]
## Problem description

When changing the name of the default animation when inserting sprite, C3 crashes.

## Attach a .c3p

https://www.dropbox.com/s/c87uv0zie768j02/Animation%20Name%20Crash%20Bug.c3p?dl=0

## Steps to reproduce

1. Double click or right click to insert a new object
2. Select Sprite
3. Click somewhere so it opens the animation window
4. Change the name of the animation.

Note: This does not just happen when inserting an object, the crash also occurs when you edit a sprite and try to change the name of an animation.

## Observed result

I got a crash error and had to restart my project. Please see error information log below.

## Expected result

I expected my animation name to change without crashing, TYVM :P.

## More details

**Affected browsers/platforms:** Sorry I only use Chrome. It is possible that it happens on other browsers, but I have not tested this.

**First affected release:** r137 beta - Currently the latest version, I have only noticed it on this version.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r137/main.js, line 2, col 222078
Message: Uncaught TypeError: this.ǃsVA is not iterable (cannot read property Symbol(Symbol.iterator))
Stack: TypeError: this.ǃsVA is not iterable (cannot read property Symbol(Symbol.iterator)) at ǃu.ǃjo.ǃsVv (https://editor.construct.net/r137/main.js:2:222078) at ǃu.ǃjo.ǃsVN (https://editor.construct.net/r137/main.js:2:222236) at ǃsV$ (https://editor.construct.net/r137/main.js:2:221726)
Construct 3 version: r137
URL: https://editor.construct.net/r137/
Date: Wed Feb 13 2019 18:37:59 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 246.9 s

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r137 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta release.
