### ISSUE TITLE
Offline creating project, opening project, preview fails

### ISSUE THREAD

**Issue by boris1dev** [Scirra/Construct-3-bugs#2610]
## Problem description

I have a subscription for the personal version of C3.
If I'm online everything works as expected: I've created a project based on the official "Getting Started" Tutorial and saved it in the local storage.

But when I go offline I cannot create new project, cannot open existing ones and cannot preview opened projects (if I I opened them when I was online)

## Attach a .c3p

[Getting Started Shoort.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2859310/Getting.Started.Shoort.c3p.zip)

## Steps to reproduce
1. Ensure the wifi connection is established
2. Open editor in a new chrome window
3. Login with my construct 3 user account
4. Go offline
5. Create a new project - fails with the error message "Failed to create new project. Try reloading Construct 3"
6. Try to open the existing project from the browser storage. Fails with message "Failed to open project. Try reloading Construct 3"
7. Going online
8. Load project
9. Close project 
10. Go offline
11. Open project - it loads
12. Open project in preview mode - just a black screen

## Observed result

Error messages and black screen

## Expected result

When I open C3 and I login (even if I'm not logged in) and I go offline I want to
- create new projects
- open existing projects from the local storage
- preview the project

## More details

**Affected browsers/platforms:** 
Chrome version 71.0.3578.98
macOS Mojave 10.14.2 (18C54)
Construct 3, release r136 stable

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.96
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_2
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
C3 release: r136 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 8.7 gb
Storage usage (approx): 8.6 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics 655
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by boris1dev** [comment]
By the way: I can also provide a screencast and in the official construct forum I've created a thread with 2 screenshots: [link](https://www.construct.net/en/forum/construct-3/how-do-i-8/how-do-i-create-new-project-an-141696)

**Comment by AshleyScirra** [comment]
If you do not wait for the "Construct 3 is ready to use offline" notification to appear, then Construct 3 won't work offline, since it hasn't finished downloading. This can take a while after first loading C3. Your steps to reproduce should include waiting for this message to appear, otherwise I'd assume you are simply going offline too early, before it's finished downloading in the background.

I suspect this is also related to crbug.com/899196 - a Chrome (or CloudFlare - we haven't figured out which yet) bug which is preventing the offline caching from working. If this bug happens, the "ready to use offline" notification will never appear, and C3 will not work offline. Unfortunately there's nothing we can do about this right now since the problem is not caused by Construct. As a workaround you can try another browser - e.g. I just tried Firefox and it shows the "ready to use offline" notification.
