### ISSUE TITLE
New Sub-Group with the G key disorganises

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2612]
## Problem description

When using the G key to add a subgroup to a group where code already exists will not add the group at the bottom or the top of the code, instead it plants inself at the bottom of the events but above the last event.

## Attach a .c3p

https://www.dropbox.com/s/y5ac5sw867hsx08/Event%20Sheet%20New%20Sub-Group%20Not%20Created%20Bug.c3p?dl=0

## Steps to reproduce

1. Select a group with code and no other sub-groups inside it.
2. Press G and add the group accordingly.

## Observed result

You will find the group at the bottom of the events but above the bottom event.

## Expected result

I expected the group to appear at the top above the code.

## More details

Windows 10.

**Affected browsers/platforms:**  Chrome

**First affected release:** I have always noticed this but never got time to report it, sorry. The current version it is currently happening on is r137 beta.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r137 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 128 mb (0.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by LukeNecklace** [comment]
Can I just point out that I think if you add a sub-group, the latest sub-group should appear at the bottom of all the groups if there are any existing groups but above any code.

**Comment by LukeNecklace** [comment]
Something else I forgot to mention yesterday is that you have this right in Construct 2 in my opinion.

**Comment by AshleyScirra** [comment]
Changed to insert above first selected item rather than last selected item for the next release.

Note the behavior for groups specifically may change in future if we implement https://construct3.ideas.aha.io/ideas/C3-I-453

**Comment by LukeNecklace** [comment]
I believe that is if you highlight the code and create a group -- That's a good idea to implement too.

@AshleyScirra I meant if you add a subgroup without highlighting any code in particular; At the moment new sub-groups appear at the top of the other sub-groups. My suggestion was for the empty new sub-group to appear at the bottom of the groups.

Sorry if this is confusing, it's very hard to explain properly and it's 2:00am.
