### ISSUE TITLE
[R137] Template "Flying along" cannot be downloaded/opened

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2613]
## Problem description

In the start page, templates category, when clicking on the "OPEN PROJECT" button (or "PREVIEW") for the "Flying Along" template, Construct tries to download the template and an error dialog appears containing the message : 
"Failed to download project. Check your Internet connection is working."

## Expected result

For the template to open like all the others templates, as the internet connexion is working.

**Affected browsers/platforms:**
Chrome 72.0.3626.96
FireFox 65.0 (with R136)

**Comment by shortercode** [comment]
@AshleyScirra I can't find the file related to this project, I'm not sure it's ever been present in a release. Did we just forget to add it?

**Comment by AshleyScirra** [comment]
Oops, looks like its project file was accidentally deleted when everything was switched over to the C3 runtime! Added it back for the next release, thanks for spotting it @Kyatric
