### ISSUE TITLE
Tween Colour & Text Colour Properties - Inconsistent Properties

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#2614]
## Problem description

When you tween the colour of a text object using the Tween behaviour, it just tweens the hidden common properties without giving the user the ability to check current colour because it is separate from the colour properties (which only dictates font colour).

This brings confusion as every other object like Sprites, TiledBackgrounds, etc. has a common property for colours, except the text objects. And it's common colour value cannot be retrieved nor set.

## Observed result
Inconsistent, confusing and missing common property colour on Text objects.

## Expected result
Proper implementation of the Tween behaviour without inconsistency with it's attached object.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.96
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
C3 release: r137 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.8 gb
Storage usage (approx): 1.5 gb (19.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is an awkward design issue... I wanted to switch the Text object to using the built-in color property instead of having its own font color property, but keeping compatibility with the C2 runtime makes that difficult, so it ends up keeping its own font color and disabling the built-in color. Tween provides a fixed drop-down list of things to tween which includes the built-in color property, but this has no effect on Text. I think the only workaround is to special case Text objects in the Tween behavior...

**Comment by DiegoScirra** [comment]
Added in the next release.
