### ISSUE TITLE
Blocking cookies crashes local storage and the game

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2615]
## Problem description

Players are reporting that my game won't start if they block cookies on the domain, the console shows this error which I'm guessing is related to the local storage especially that the crash happens when I know the local storage is being checked? Still, shouldn't the game start either way?
![image](https://user-images.githubusercontent.com/7268697/52778001-acba0d00-304d-11e9-96b4-68b57a546b43.png)

## Attach a .c3p

https://jefawk.com/Games/Nightwalkers/Game

## Steps to reproduce
1. Block cookies in Google Chrome via Settings -> Advanced -> Content settings
<img width="515" alt="screenshot_11" src="https://user-images.githubusercontent.com/7268697/52779784-86966c00-3051-11e9-870c-6aef4bcdab56.png">

Cookies and Block all, navigate to https://jefawk.com/Games/Nightwalkers/Game

2. Notice the loader layout loads and the next layout that holds the local storage crashes
3. Check console

## Observed result

"No available storage method" error in console and game won't start.

## Expected result

Expected for the game to work, even though cookies are blocked and local storage might not work with local storage warning in the console.

## More details

**Affected browsers/platforms:** Tested on Chrome

**First affected release:** noticed in r136, C3 editor and C2 runtime

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r136 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 50 gb
Storage usage (approx): 7.2 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon 550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
As per the guidelines please provide a project that demonstrates the problem without any third-party addons. We cannot test changes against already-published projects, and the problem could be caused by a third-party addon (the console log you showed includes Socket.io).

**Comment by JeFawk** [comment]
I mean...... 
![image](https://user-images.githubusercontent.com/7268697/52797816-55cd2b80-307f-11e9-87cc-038ea1ac7ef0.png)

**Comment by AshleyScirra** [comment]
That is a different issue to your original report which affected the runtime, please report it separately.
