### ISSUE TITLE
Animation editor crashes when trying to change an animation name

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2616]
## Problem description

The animation editor crashes everytime i try to rename an animation to "ani_1".

## Attach a .c3p

There's no need to attach a .c3p file since it happen on any file.

## Steps to reproduce

1. Create a new project.
2. Insert a new sprite object.
3. Try to rename the animation to "ani_1".

## Observed result

The animation editor crashes.

## Expected result

The animation to renamed.

## More details

**Affected browsers/platforms:** 
Google Chrome

**First affected release:** 
R137
## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r137/main.js, line 2, col 222078
Message: Uncaught TypeError: this.ǃsVA is not iterable (cannot read property Symbol(Symbol.iterator))
Stack: TypeError: this.ǃsVA is not iterable (cannot read property Symbol(Symbol.iterator)) at ǃu.ǃjo.ǃsVv (https://editor.construct.net/r137/main.js:2:222078) at ǃu.ǃjo.ǃsVN (https://editor.construct.net/r137/main.js:2:222236) at ǃsV$ (https://editor.construct.net/r137/main.js:2:221726)
Construct 3 version: r137
URL: https://editor.construct.net/r137/
Date: Thu Feb 14 2019 12:22:23 GMT-0200 (Horário de Verão de Brasília)
Uptime: 17.8 s

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r137 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed already, will be available in the next beta release.
