### ISSUE TITLE
Sound not playing on IOS 12 with HTML5 browser game

### ISSUE THREAD

**Issue by rsgourley** [Scirra/Construct-3-bugs#2617]
I'm developing a slot machine game, based on a template that I purchased (though at this point it's 80% original). However, I'm running into an issue with audio (sound effect) playback when viewed in a browser on IOS devices. In my version, they just don't play. Construct has converted the files to webm.

However, when I try the original template, they do work. The difference is that it is a Construct 2 file brought into Construct 3, and there are .m4a versions of the audio (which get exported with the game).

From what I've observed, this issue is only affecting devices with IOS 12 (though I only have 2 devices to test on, one with 11 and one with 12). The old template (that included m4a versions) does work on IOS 12.

Is this I known issue, and if so what would a workaround be? Is there a way to force IOS browsers to use an .m4a version? (I've tried including as an external file). Is the current Opus audio decoding code not compatible with IOS 12?

I have tried using both the latest stable and beta versions, as well as the Construct 2 and 3 runtimes.

I have tried creating a simple file where a sound should play when a button is clicked, and the same things happens.

I can't share the game file at this point (client won't allow) but attached is my simple test file.

[soundtest.zip](https://github.com/Scirra/Construct-3-bugs/files/2865737/soundtest.zip)

## Steps to reproduce

1. Import sound
2. Export as html
3. View on IOS 12 device

## Observed result

Sound does not play.

## Expected result

Sound should play

## More details

**Affected browsers/platforms:** 

Safari IOS 12

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It works fine for me on iOS 12 testing with Remote Preview. Assigning to @shortercode to double-check.

**Comment by rsgourley** [comment]
Is there anything you'd suggest doing to troubleshoot? This device has a fresh install of ios 12. Sound is fine in that older game I mentioned (which exports m4a with it), as well as playing video (within this new game).

**Comment by AshleyScirra** [comment]
Can you reproduce the issue using Remote Preview?

**Comment by luckyrawatlucky** [comment]
Remote preview works always but when export to web and then test it to iPhone then it doesn't worked.

**Comment by AshleyScirra** [comment]
I'd guess that this will come down to a server configuration issue then, since if Remote Preview works it proves both Construct and Safari are capable of playing the sound. Check the server [MIME types](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/mime-types) are set up correctly.

**Comment by rsgourley** [comment]
But it's strange that in my testing, it worked on other devices (Android phone, iPad, desktop), just not on my iPhone (an SE running ios 12). Would a MIME type issue be device/browser specific?

**Comment by rsgourley** [comment]
I tried using remote preview (https://preview.construct.net/#mhyzbs9i) and it still works on all devices but my iphone, so I don't think it's a MIME type issue?

**Comment by AshleyScirra** [comment]
> Would a MIME type issue be device/browser specific?

Yes, it can be.

**Comment by shortercode** [comment]
@rsgourley I'm not experiencing any problems getting the audio to play on an iPad pro running 12.1.4

Steps followed:
1. Export sample project as HTML ( internal C3 build )
2. Host on local server ( node.js based HTTP server )
3. Visit site with safari on iPad
4. Click button

If you can provide your system details then I will check whatever version your using to export, in case this is a release only issue. But I think to go any further you may need to check the safari developer tools and report back to us, as this doesn't seem easily reproducible.

**Comment by AshleyScirra** [comment]
Can't reproduce and no response so closing.
