### ISSUE TITLE
Animation editor - incorrect resizing when pasting

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#2619]
## Problem description

If you paste a wider but shorter image (i.e. 48x16) on top of another image (i.e. 32x32) and choose to enlarge the canvas, the canvas changes size to match the wider/shorter image rather than expanding to accommodate but images (i.e. 48x32).

## Attach a .c3p

[AnimationEditorBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2866790/AnimationEditorBug.zip)

## Steps to reproduce

1. Create a sprite that's 32x32.
2. Create another that's 48x16.
3. Hit ctrl+a to select everything in the 48x16, and ctrl+c to copy it.
4. Edit the 32x32 sprite.
5. Hit ctrl+v to paste, and choose "Enlarge Canvas".

## Observed result

The 32x32 sprite resizes to 48x16.

## Expected result

The sprite should resize to 48x32 so that nothing is cropped.

## More details

**Affected browsers/platforms:** 

Chrome on Windows, at least.

**First affected release:** 

I tested as far back as r120 before my lunch break ended, so this one is pretty old (but it also seems like a trivial thing to fix, so hopefully you don't need the exact point it was introduced). The attached project and system information are from r137.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r137 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 273 mb
Storage usage (approx): 27 mb (10%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GRID K120Q Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.

This was indeed a very old issue, been there since the feature was implemented.
