### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#262]
## Problem description
The system crashed after adding new animations to a previously created sprite.  I previewed the new sprites animation and then closed the preview window then closed the sprite editor window and it crashed.  c3p is attached in the .zip and crash report pasted below.

Also I cannot access cloud saving after using it many times successfully in many previous builds.
[HWAS.zip](https://github.com/Scirra/Construct-3-bugs/files/1012790/HWAS.zip)

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes 

## System details
Error report information
Type: unhandled exception
File: https://editor.construct.net/r29/main.js, line 61, col 128192
Message: Uncaught Error: image sprite collection needs rebuilding
Stack: Error: image sprite collection needs rebuilding at ue.ǃjk (https://editor.construct.net/r29/main.js:61:128198) at ie.ǃjk (https://editor.construct.net/r29/main.js:61:199978) at a.ǃxU.ǃjJ (https://editor.construct.net/r29/main.js:61:395983) at a.ǃxU.ǃjJ (https://editor.construct.net/r29/plugins/sprite/plugin.js:1:7966) at a.ǃxU.ǃxD (https://editor.construct.net/r29/plugins/sprite/plugin.js:1:7766) at ne.ǃxD (https://editor.construct.net/r29/main.js:61:217100) at oe.ǃxD (https://editor.construct.net/r29/main.js:61:252698) at ae.ǃxD (https://editor.construct.net/r29/main.js:61:238363) at window.ǃtK.ǃRL (https://editor.construct.net/r29/components/editors/layoutView/layoutView.js:1:6915) at ǃRN.X (https://editor.construct.net/r29/components/editors/layoutView/layoutView.js:1:2086)
Construct 3 version: r29
URL: https://editor.construct.net/
Date: Thu May 18 2017 20:44:30 GMT-0400 (Eastern Daylight Time)
Uptime: 192.7 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
<details><summary>View details</summary>

</details>

**Comment by sielxm3d** [comment]
i am having the same problem, we need this fix it on the next release

**Comment by 8bitThirsty** [comment]
This wasn't happening consistently but happened multiple times with the same steps to reproduce described above.  It wasn't a huge issue since I could save and restart quickly but I will post if it happens again.

Have not run into this issue within the past hour and I attempted to recreate it multiple times.  The cloud server storage seems to be working again as well.
