### ISSUE TITLE
Dialogue Box Highlighting Bug

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2620]
## Problem description

Highlighting text in dialogue boxes de-highlight when the mouse goes off the dialogue box. Many times I highlight text in these small boxes and naturally I move my mouse past the box and it de-selects.

## Attach a .c3p

https://www.dropbox.com/s/szbd029z515fkqe/Dialogue%20Box%20Highlighting%20Bug.c3p?dl=0

## Steps to reproduce

1. Open any dialogue box in the program where it gives you the ability to highlight text or numbers
2. Click and drag to highlight the text or numbers.
3. Continue dragging in the same direction, keeping your mouse click down and move it off the area where the dialogue box is on the screen.

## Observed result

The text or numbers de-highlight. 
This is consistent with every dialogue box.

## Expected result

The text should remain highlighted until there is a separate click -- like it does in Construct 2 and every other program that has a dialogue box with text input mechanics.

## More details

**Affected browsers/platforms:** Windows 10 - Google Chrome (Sorry I have not tested other browsers).

**First affected release:** I have always known this to happen with Construct 3. I just have not had time to report it before, sorry. Current version is r137 Beta.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 71.0.3578.98
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
C3 release: r137 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 130 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
This is an old Chrome bug in their modal dialog implementation, I can't find a bug related to it on our tracker but we are aware of it. I filed a bug with the chrome team quite awhile back, but I think it's very low on their priority list ( Chrome is the only browser that actually supports the dialog element, we use a polyfill for it )

[chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=854637)

**Comment by LukeNecklace** [comment]
Is there nothing that Scirra can do to work around this at all?

**Comment by shortercode** [comment]
Well the issue here is actually with Chrome, the browsers using the polyfill don't have the bug. I don't think there is an easy workaround, ideally the Chrome team would just fix the issue. There is the drastic option where we stop using the dialog element, but it's a lot of work for a minor issue and will likely cause other issues.

**Comment by AshleyScirra** [comment]
If there's nothing for us to action, closing - follow up at crbug.com/854637.
