### ISSUE TITLE
Effect on Drawing canvas and you paste sprite with effects. Results bug

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2623]
## Problem description
When you add alpha clamp on drawing canvas and sprite has effects blur horizontal&vertical or one of them. Will end up bug.

## Attach a .c3p
[CanvasEffectrBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2872748/CanvasEffectrBug.zip)

## Steps to reproduce

1. Open example, see drawing canvas location, preview.
2. Move mouse, see sprite follows.
3. Move mouse over canvas and hold it down and move
4. See sprite freezes

## Observed result
Error in console:
renderEffectChain.js:1 Uncaught (in promise) TypeError: Cannot read property 'GetEffectList' of null
    at j (renderEffectChain.js:1)
    at Function.C3.RenderEffectChain (renderEffectChain.js:1)
    at C3.Layer._DrawInstanceWithEffects (layer.js:1)
    at C3.Layer._DrawInstanceWithEffectsAndRestore (layer.js:1)
    at C3.Layer._DrawInstances (layer.js:1)
    at C3.Layer.Draw (layer.js:1)
    at C3.Layout.Draw (layout.js:1)
    at C3.Runtime.Render (runtime.js:1)
    at C3.Runtime.Tick (runtime.js:1)

## Expected result
Correct effect paste and no error in console

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 

Bug from start: R123, when canvas was released

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.109
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
C3 release: r137 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 971 mb (7.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
