### ISSUE TITLE
Solid Collision Filter Events Unrecognised with Tile Movement Behaviour

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2625]
## Problem description

Using the event sheet to make some objects inclusive or exclusive of tags does not get recognised during run time. Objects with an inclusive tag are being ignored when the object they are colliding with has a tag that is inclusive. So all tags are inclusive with my C3P. However, the blue square should be the one that collides but it doesn't.

@AshleyScirra I understand you decided against looking into this a couple of years ago at Consider blocking movement + solid behavior combos#546

However with the introduction to solid tags, it encourages game designers to use a combo of movement + a solid behaviours and then use the event sheet to manipulate this to their liking.

Basically Construct 3 says you can use this combination of behaviours to create a game that allows you to actively manipulate the solids between objects depending on certain conditions at any time. For example: If a monster was to spawn in the middle of a cave so they can move out of it exclusively once but you did not want to give other objects such as the player object the ability to access that cave at all even when a monster is spawning.

## Attach a .c3p

https://www.dropbox.com/s/4trdk7ut8jwcwuv/Solid%20Collision%20Filter%20Events%20Unrecognised%20with%20Tile%20Movement%20Behaviour.c3p?dl=0

## Steps to reproduce

1. The events indicate that only inclusive tags should collide at every tick. Check the variable to ensure that two are the same and one is different.
2. Run the project and use the arrow keys to move both the red and blue blocks to collide with the purple block.

## Observed result
The blue block that has the same tag does not stop when colliding with the purple block, it just goes straight through it.
**Issue 2:** You will not be able to move the red and blue blocks even though the default controls are enabled for the tile movement behaviour on both objects.

## Expected result

The blue block should have collided with the purple block and stopped moving so it could not go through it.

## More details

**Operating system:** Windows 10
**Affected browsers/platforms:** Chrome, Firefox and Microsoft Edge

**First affected release:** I only noticed this on current r137 Beta

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.109
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
C3 release: r137 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 155 mb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by LukeNecklace** [comment]
I have edited this issue to only include one issue. I have posted the second issue separately. This is to adhere to your guidelines. I do apologise for not following them initially. Please let me know if you need anything else from me.

**Comment by AshleyScirra** [comment]
It's not a bug, you just got "Set collision filter" confused with the solid collision tags. "Sprite" (i.e. the object with only a solid behavior) has no solid tags; its "Set collision filter" action has no effect. The other two objects specify an *Inclusive* collision filter with different tags; since "Sprite" has no tags, it doesn't match either tag, so collisions with it are disabled.
