### ISSUE TITLE
[R138] Cannot preview projects using event groups

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2627]
## Problem description

When previewing the "Turret Defense" template the screen stays black and the console indicates errors.

## Steps to reproduce

1. In the start page, click "Preview" next to the "Turret Defense" template

## Observed result

Screen stays black, browser's console raises errors : 

Uncaught (in promise) TypeError: Class constructor  cannot be invoked without 'new'
    at C3.Action._RunObject_ParamsConst (action.js:1)
    at C3.EventBlock._RunActionsAndSubEvents (eventBlock.js:1)
    at C3.EventBlock._RunAndBlock (eventBlock.js:1)
    at C3.EventBlock.Run (eventBlock.js:1)
    at C3.EventSheet.Run (eventSheet.js:1)
    at C3.EventSheetManager.RunEvents (eventSheetManager.js:1)
    at C3.Runtime.Step (runtime.js:1)

## Expected result

The game to preview without issue.

## More details

**Affected browsers/platforms:** 
Chrome
Firefox

**First affected release:**
R138

Works as intended in r136 & r137.
Please also note changing to C2 runtime provides a different error but has a similar effect.

**Comment by AshleyScirra** [comment]
Lots of projects fail to preview in r138 (any that use event groups), including Turret Defense. It's fixed for the next release, we'll probably have a .2 release out tomorrow for this.

**Comment by luckyrawatlucky** [comment]
How can i revert back to r137 in Desktop Version?

**Comment by Madiosn** [comment]
And this is not the only problem.

It does not open in the old version!

+ all this scripts have stopped working. I can not go to the button to the new layout.

**Comment by LukeNecklace** [comment]
> How can i revert back to r137 in Desktop Version?

You can revert back to an earlier version of construct 3 by going here: https://www.construct.net/en/make-games/releases/beta/r137 - This is a direct link to the previous version.

**Comment by alastajj** [comment]
Thanks for the hotfix, will help us all. Makes me wish I just stuck with stable versions!

**Comment by Madiosn** [comment]
Will there be an update today?

**Comment by LukeNecklace** [comment]
Yes, there is going to be an update today.
