### ISSUE TITLE
DrawingCanvas pastes invisibile sprites incorrect

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2628]
## Problem description
First, Drawing canvas pastes invisible sprites. If it bugs, most likely is, but maybe fixing it you could consider( I am going to make idea suggestion in aha, to able to paste object onto canvas that are invisible. To have more correct paste and destroy, As you can't put them below it, which causes other behaviors.) 

Secondly, pasted sprites, while they are invisible, have wrong Z order.

## Attach a .c3p
[DrawingCanvas_InvisibilityOrder_Bug2.zip](https://github.com/Scirra/Construct-3-bugs/files/2876494/DrawingCanvas_InvisibilityOrder_Bug2.zip)

## Steps to reproduce

1.Open example, preview
2.Close preview, set sprite visible, preview
3.

## Observed result
Sprites, while they are visible keep z order. But if they are invisible they are still pasted, but with incorrect z order. Both behaviors seems to be incorrect, but second behavior, wrong z order, should also be fixed if there would new feature to allow canvas to paste invisible  sprites.

## Expected result
No wrong behaviors

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
125. 
123/124 can't preview example and have other errors.

138 has bug also, system details are from 137.
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.109
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
C3 release: r137 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 974 mb (7.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's working correctly. You're spawning the sprites on a layer above the DrawingCanvas, but moving them to back on creation. When the sprite is invisible, it still correctly pastes in to the canvas (so it can still be pasted even though it was set to invisible). However DrawingCanvas always pastes on top so you get a drawing-on-top effect. When the sprite is visible, you see them all stack up on Layer 1 on top of the DrawingCanvas, but because you move them to the bottom of the layer on creation you get a drawing-underneath effect. Both ways are working correctly, it's just what you set up the project to do.

**Comment by SnipG** [comment]
Wow yeah, i could order them while they invisible and paste, and not paste when not needed :D Mind blown.
