### ISSUE TITLE
Runtime3 - remote viewing is impossible to see the video as someone checks the project

### ISSUE THREAD

**Issue by Roguelike2018** [Scirra/Construct-3-bugs#2629]
in runtime2 everything is working fine

**Comment by LukeNecklace** [comment]
This is related to #2627

**Comment by Roguelike2018** [comment]
no no no this is happening in my last stable version and this is remote access

**Comment by LukeNecklace** [comment]
Okay, I recommend fill out the template that you were given man so it gets heard because it looked like it was related to me.

**Comment by Madiosn** [comment]
> Okay, I recommend to fill out the template that you were given when you create an issue man so it gets heard because it looked like it was related to me. They will not investigate bug reports that do not follow the template as per the directed guidelines.
What kind of template? where to get it and how to fill?
