### ISSUE TITLE
Construct 3 Randomly crashes for no visible reason

### ISSUE THREAD

**Issue by martipops** [Scirra/Construct-3-bugs#263]
## Problem description

Construct randomly crashes

## Attach a .c3p

[Martio.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1012822/Martio.c3p.zip)

## Steps to reproduce

1. It just happens out of nowhere

## Observed result

A dialog shows up saying it crashed

## Expected result

I would be able to continue working

## Affected browsers

Chrome

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'catch' of undefined @ TypeError: Cannot read property 'catch' of undefined at Sa (https://editor.construct.net/r29/cloud/sandbox.js:1:32469) at Wa (https://editor.construct.net/r29/cloud/sandbox.js:1:32958) at Za.eb.keys.then.gb (https://editor.construct.net/r29/cloud/sandbox.js:1:33324) at 
Stack: TypeError: Cannot read property 'catch' of undefined at Sa (https://editor.construct.net/r29/cloud/sandbox.js:1:32469) at Wa (https://editor.construct.net/r29/cloud/sandbox.js:1:32958) at Za.eb.keys.then.gb (https://editor.construct.net/r29/cloud/sandbox.js:1:33324) at 
Construct 3 version: r29
URL: https://editor.construct.net/
Date: Thu May 18 2017 21:14:54 GMT-0400 (EDT)
Uptime: 456.3 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce 320M OpenGL Engine
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2047
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_disjoint_timer_query, EXT_frag_depth, EXT_shader_texture_lod, EXT_sRGB, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Looks like same error as #251, should be fixed in r29.2.
