### ISSUE TITLE
[#2625 SPLIT] Deleting Events involving objects with Tile Movement and Solid Behaviours Renders Movement Inoperable

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2630]
## Problem description

**Please note: I split this issue from #2625 so it is in accordance with the directed guidelines.** 

If you have events referencing the solid collision filter in this manner and you delete those events, it makes it no longer possible to use the default controls of the tile movement behaviour, rendering the objects uncontrollable.

Before attempting to do this myself in my project involving tile movement, I decided to learn more about the solid tags in conjunction with the tile movement behaviour and ran into these two issues.

If you are able to fix this issue, it will really make Construct 3 truly awesome. Please let me know if you need me to do anything else in relation to these issues because it's this type of thing that is impacting my ability to conveniently create my projects. In the mean time, I am going to have to find some alternative to get around this and my experience is limited.

## Attach a .c3p

https://www.dropbox.com/s/4trdk7ut8jwcwuv/Solid%20Collision%20Filter%20Events%20Unrecognised%20with%20Tile%20Movement%20Behaviour.c3p?dl=0

## Steps to reproduce

1. Delete the every tick event block that is assigning the variable to the solid tag.
2. Run the project and try to move using the default controls 

## Observed result

You will not be able to move the red and blue blocks even though the default controls are enabled for the tile movement behaviour on both objects.

## Expected result

The objects with tile movement behaviour should move like normal.

## More details

**Affected browsers/platforms:** Windows 10 - Chrome, Firefox and Microsoft Edge.

**First affected release:** Noticed this on r137. Sorry I have not checked the others but I believe it is still a current despite very recent issue since it was not logged as a fix in r138's change-log.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.109
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
C3 release: r137 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 155 mb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's not a bug: the behaviors don't move because you have the Solid behavior on the objects with movements, so the objects block themselves. It only works with the "Set collision filter" action because you set an inclusive filter that makes the objects ignore their own solid behaviors.

**Comment by AshleyScirra** [comment]
Heads up @shortercode - you might want to make sure that the tile movement isn't able to collide with itself, to avoid this case. I can't remember if other behaviors do this though.

**Comment by LukeNecklace** [comment]
Thanks Ash, I'll learn to do more thorough research before posting in here!
