### ISSUE TITLE
Can't remote preview on mobile, while worker is enabled

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2631]
## Problem description

Remote preview on mobile, while worker is enabled results black screen. It similar to bug:long time ago you could not host html5 with worker and you got workermain.js etc Not found.
Now on mobile you get same error on console: workermain.js not found

## Attach a .c3p
[RemotePreview_MobileWorkerBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2879303/RemotePreview_MobileWorkerBug.zip)
## Steps to reproduce

1.use example or new project
2.Try remote preview
3.Mobile shows console error: workermain.js not found

## Observed result
Can't remote preview with mobile, while worker is enabled. Shows console error on phone: workermain.js not found

![remotepreview_mobileworkerbug](https://user-images.githubusercontent.com/28864889/53004176-4fe99880-3439-11e9-9410-d35569753e05.jpg)

## Expected result
User can remote preview while worker is enabled. No error

## More details

**Affected browsers/platforms:** 
Chrome - remote preview

**First affected release:** 
R134

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.105
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Android
Operating system version: 7.0
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 3
Logical CPU cores: 8
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Linux; Android 7.0; Redmi Note 4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.105 Mobile Safari/537.36
C3 release: r138 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 1.6 gb
Storage usage (approx): 124 mb (7.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Qualcomm
Renderer: Adreno (TM) 506
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
