### ISSUE TITLE
When saving a project in version r138, it cannot be opened in version r137.

### ISSUE THREAD

**Issue by Madiosn** [Scirra/Construct-3-bugs#2632]
When saving a project in version r138, it cannot be opened in version r137. The system displays the message: project saved with future release of C3

https://yadi.sk/d/L7xloCKP6RTcyQ
Project.c3p

## Steps to reproduce

1. Opened a project that was created in version r 137 in version r138
2. Saved project in version r138. Shut it down.
3. Loaded the r137 version and tried to open the project. Does not work

## Observed result

The system displays the message: project saved with future release of C3

## More details

The problem occurs in browsers Safari, Chrome on Mac OS

The problem was taken with the first release of r138 and the error for which the weaver did not start

## System details

<details><summary>View details</summary>

SCREENSHOT
https://yadi.sk/i/dgeRJAMdV2uhUA

</details>

**Comment by AshleyScirra** [comment]
This has always been the case, and is by design.
