### ISSUE TITLE
No array editor text wrap.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2633]
I was setting up a dialogue system using the array editor for various responses. I noticed that the cells have no word wrap, which is a bit annoying. Text strings often end up outside of the cell unless I scale them.

N/A

## Steps to reproduce

1. Create a new project
2. Add file - Array and edit it. set rows and cols to something desirable and scale them a bit.
3. Write something in any of the cells, and notice that words don't wrap when longer than cell.

## Observed result

No text wrap in Array editor Cells.

## Expected result

Expected text wrap in array editor, for use with longer strings and dialogue.

PASTE HERE

</details>

**Comment by tunepunk** [comment]
To clarify. It wraps when you enter text, but when text is entered, the cell does not show the text wrapped.

**Comment by tunepunk** [comment]
Hmmmm... Okay. Maybe another solution then would be to have a preview or insert pane for the selected cell? Kind of like in excel where you can enter the value for the cell above the sheet. 

When a cell is selected this input box would show the content of the current cell.

**Comment by tunepunk** [comment]
![test](https://user-images.githubusercontent.com/27011641/53029022-57746600-3468-11e9-8778-2d1807d88727.jpg)

Maybe something like that is better then? so you can see the whole string in one insert/edit box?

**Comment by AshleyScirra** [comment]
If it's a suggestion let's move it on to https://construct3.ideas.aha.io/
