### ISSUE TITLE
Layer is suddenly invisible in my project (r135 and later)

### ISSUE THREAD

**Issue by VictoryRice** [Scirra/Construct-3-bugs#2635]
## Problem description

My project was working fine on Stable r131 and up through Beta r134. Starting with Beta R135, the layer in my project containing the tilemap for platforms is invisible when previewing. (It is still perfectly visible in the editor.) I've tested Stable r136 and up through Beta 138.2, and the issue persists.

## Attach a .c3p

See "jotsu_v27.c3p" contained in the attached .zip file
[jotsu_v27.zip](https://github.com/Scirra/Construct-3-bugs/files/2881347/jotsu_v27.zip)

## Steps to reproduce

1. Open jotsu_v27.c3p in r134 (https://editor.construct.net/r134/)
2. Ensure the layout tab called "Action" is selected in editor and choose Preview Layout
3. Observe that the screen is filled with a variety of platforms and other scenery just as seen in the editor
4. Open jotsu_v27.c3p in r135 (https://editor.construct.net/r135/)
5. Ensure the layout tab called "Action" is selected in editor and choose Preview Layout
6. Observe that all the platforms and scenery which are contained on the layer "Platforms" are invisible, though can still be interacted with as if they were visible. (Use left/right arrows to move player character, and Z key to flap wings/fly.) The missing graphics come from the tilemap called "tm_Platforms".

## Observed result

The platforms and scenery which are contained on the layer "Platforms" are invisible in r135 and higher.

## Expected result

I expected that previewing the layout would produce identical results in all versions of C3 release since November (when I last edited the project).

## More details

Have not tested in other browsers or systems.

**Affected browsers/platforms:** 
Chrome 72.0.3626.109 on Windows 10.

**First affected release:** 
Beta r135
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.109
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
C3 release: r135 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 966 mb (6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The tilemap `tm_Platforms` has "Initially visible" unchecked. So the object is hidden on startup. r135 is working correctly; r134 was broken. The fix was noted in the r135 changelog:

> C3 runtime: Tilemap 'Initially visible' setting not working

Just tick "Initially visible" and you can see it again.

**Comment by VictoryRice** [comment]
Thanks! 🤦
I had tried switching the initially visible on the layer, but didn't think to check the tilemap.
