### ISSUE TITLE
[C3 Desktop] Crash when "Preview Effects" & "Show Translucent Inactive Layers" enabled

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#2636]
## Problem description

Consistent/reproducible crash when I enable "Show Translucent Inactive Layers" when "Preview Effects" is enabled. Only happens when a specific layer of mine is highlighted, but there's nothing special about it. I tried removing all of its objects' effects and so on.

EDIT: I have a different layer with a "Brightness" effect. Removing this stops the crash.

## Attach a .c3p

Occurs in commercial project. Will try to make a .c3p with identical situation.

## Steps to reproduce

1. Enable "Show Translucent Inactive Layers" while "Preview Effects" is already enabled

**Affected browsers/platforms:**

C3 Desktop 138.2 / NW.js

**First affected release:**

C3 Desktop 138.2 / NW.js

## System details

Error report information
Type: assertion failure
Message: setting texture to current render texture
Stack: Error at Function.ǃx.ǃOBF (https://editor.construct.net/r138-2/main.js:2:147114) at e (https://editor.construct.net/r138-2/main.js:2:108297) at window.assert (https://editor.construct.net/r138-2/main.js:2:108622) at ǃx.ǃQX.ǃQA.ǃC$ (https://editor.construct.net/r138-2/main.js:63:49052) at r (https://editor.construct.net/r138-2/components/editors/layoutView/layoutView.js:1:42478) at Function.ǃx.ǃQN (https://editor.construct.net/r138-2/components/editors/layoutView/layoutView.js:1:43650) at d.ǃTDg (https://editor.construct.net/r138-2/main.js:81:275159) at d.ǃCm (https://editor.construct.net/r138-2/main.js:81:274180) at a.ǃCm (https://editor.construct.net/r138-2/main.js:81:257686) at window.ǃOf.ǃmm (https://editor.construct.net/r138-2/components/editors/layoutView/layoutView.js:1:7107)
Construct 3 version: r138.2
URL: https://editor.construct.net/r138-2/
Date: Tue Feb 19 2019 12:35:19 GMT-0600 (Central Standard Time)
Uptime: 101.3 s

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r138.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
I'm afraid we cannot investigate this until you provide a project demonstrating the issue, as per the bug report requirements. Please reopen if you can provide that.
