### ISSUE TITLE
Runtime3 - remote viewing is impossible to see the video as someone checks the project 

### ISSUE THREAD

**Issue by Roguelike2018** [Scirra/Construct-3-bugs#2637]
## Problem description

Runtime3 - remote viewing is impossible to see the video as someone checks the project >

## Attach a .c3p

no

## Steps to reproduce

1. create or open any project
2. check that the runtime was 3
3. launch remote access
4. Give someone a link let him run the game
5. after the user has “downloaded the scripts” and “starts the game,” then the one who has enabled remote access does not change the text from “the video is not yet available” to “Watch the video”

## More details

stabile r137

**Comment by AshleyScirra** [comment]
Should be fixed for the next release. This involves a server-side change though, so marking this as something to verify when the next release is out.

**Comment by AshleyScirra** [comment]
The server-side change was made and I was able to verify this works with the development build already. So it should all be working in the next release. Note you may need to clear the browser cache after the next release to ensure you get the latest remote preview files.
