### ISSUE TITLE
Crash at move z / save / family change

### ISSUE THREAD

**Issue by Jau-Al** [Scirra/Construct-3-bugs#264]
## Problem description

Crashes when moving objects between layers and changing Z order. Also when adding / removing objects in famillies.

## Attach a .c3p

[blingiling.zip](https://github.com/Scirra/Construct-3-bugs/files/1013266/blingiling.zip)

( blingiling.c3p renamed  blingiling.zip )

## Steps to reproduce
1. Select the "exit" object
2. Move it to different Z levels. Sometimes work but when I try to save it in browser cache : crash.

## Observed result
Crash. Z order menu is often empty. I also crashed while creating the families.

## Expected result
Maybe not crash ? lol

## Affected browsers

In editor in Chromium.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: app is not defined @ ReferenceError: app is not defined at eb.setItem.then.catch.jb (https://editor.construct.net/r29/cloud/sandbox.js:1:34536) at 
Stack: ReferenceError: app is not defined at eb.setItem.then.catch.jb (https://editor.construct.net/r29/cloud/sandbox.js:1:34536) at 
Construct 3 version: r29
URL: https://editor.construct.net/
Date: Fri May 19 2017 08:21:48 GMT+0200 (CEST)
Uptime: 884.2 s

Platform information
Browser: Chromium
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36
C3 release: r29

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 1070/PCIe/SSE2
Major performance caveat: no
Maximum texture size: 32768
Point size range: 1 to 189.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by Jau-Al** [comment]
I imported it in Chrome 58 and now, no crash, but instead, it looks like my font doesn't work. It's using the default one Oo

**Comment by Jau-Al** [comment]
1. 1. I re-imported the font, saved, closed the browser and opened it again. Now the font is in use. 
2. I decided to save but it turned... turned... 
3. I re-opened chrome (again) and tried to delete the "save file" from the browser cache. It never ends.

![capture d ecran de 2017-05-19 11-27-34](https://cloud.githubusercontent.com/assets/15030964/26241829/71e92fce-3c86-11e7-8f95-bd863aa3a7df.png)

**Comment by AshleyScirra** [comment]
Looks like same error as in #251 so closing, should be working in r29.2.
