### ISSUE TITLE
Timeline crashed while updating keyframe

### ISSUE THREAD

**Issue by shinkan-fb** [Scirra/Construct-3-bugs#2640]
After changing some parameters I've right click on the sprite to update current keyframe and then it crashed

[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/2889042/New.project.zip)

1. Move a keyframe from 3s  to 1s on the timeline,
2. Change X position of the sprite
3. Right clicked on sprite to update a keyframe

## Observed result

Error report information dialog showed up

## Expected result

Timeline should update the keyframe for current Sprite

## More details

Chrome 

r138.2 (beta) 

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: undo point type not supported
Stack: Error at Function.ǃx.ǃOBF (https://editor.construct.net/r138-2/main.js:2:147114) at e (https://editor.construct.net/r138-2/main.js:2:108297) at window.assert (https://editor.construct.net/r138-2/main.js:2:108622) at ǃxc.ǃlh.ǃTQF (https://editor.construct.net/r138-2/main.js:81:548256) at window.ǃTtR.ǃOU (https://editor.construct.net/r138-2/main.js:81:518068) at t.ǃxa (https://editor.construct.net/r138-2/main.js:81:84427) at window.ǃOf.ǃr_ (https://editor.construct.net/r138-2/components/editors/layoutView/layoutView.js:1:31563) at d.ǃrD.i.ǃrg.t.ǃxk (https://editor.construct.net/r138-2/components/editors/layoutView/layoutView.js:1:12704)
Construct 3 version: r138.2
URL: https://editor.construct.net/r138-2/
Date: Thu Feb 21 2019 12:18:47 GMT+0100 (Central European Standard Time)
Uptime: 395.8 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.109
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
C3 release: r138.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
The crash is fixed in the next release.

@shinkan-fb For the **Update** options to work, the current time marker, the red line, must be on top of the keyframes you want to update with the current values of the instance. Otherwise the timeline has now way of knowing which keyframes you want to update.
