### ISSUE TITLE
Sounds not working in iPhone When Export to Web (Html5)

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2641]
I simply tested sound in iPhone which not working
File attached

## Problem description

<Sound not playing in iPhone>

## Attach a .c3p
[Test Sound for iPhone.zip](https://github.com/Scirra/Construct-3-bugs/files/2890663/Test.Sound.for.iPhone.zip)

## Steps to reproduce

1. Import sound in project
2. Export to Web (Html5)
3. Test it on iPhone

## Observed result

<Sound not working>

## Expected result

<Sound should play>

## More details
it works very well in Android, Chrome browser and Sarafi.

**Comment by AshleyScirra** [comment]
What version of iOS is the iPhone running? The C3 runtime only supports audio on iOS 12+. Please always provide all relevant device details.

**Comment by luckyrawatlucky** [comment]
iOS version is 12.1.2

**Comment by luckyrawatlucky** [comment]
1 important thing i forget to say my project uses C2 runtime.

**Comment by AshleyScirra** [comment]
Can you provide a link to where you have published the game? These issues often come down to upload errors or server configuration issues.

**Comment by luckyrawatlucky** [comment]
http://12punch.com/clients/KB/TEST/DinoParade/index.html

**Comment by AshleyScirra** [comment]
Did you mean to close this?

**Comment by luckyrawatlucky** [comment]
Yes, It looks like issue with iPhone, tried in iPad and anther iPhone its working there. So closing it.
Thanks

**Comment by luckyrawatlucky** [comment]
@AshleyScirra still i have one doubt if this was iPhone issue then why it was working while doing remote preview.

**Comment by AshleyScirra** [comment]
Normally these issues are caused by misconfiguration on your web server. Remote Preview does not use a normal server and is configured separately (by Construct).
