### ISSUE TITLE
Web Worker and NWjs do not play well together.

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#2642]
## Problem description

Placing a NWjs plugin in a project with web worker active won't load for preview.

## Attach a .c3p

[https://drive.google.com/open?id=1Qyp6yitRdJ3UU5sVKTknQ8fLOXptSveI](https://drive.google.com/open?id=1Qyp6yitRdJ3UU5sVKTknQ8fLOXptSveI)

## Steps to reproduce

1. Activate web worker.
2. Place an NW.js plugin in the project.
3. Run a preview.

## Observed result

The project will never preview, it's just stuck on a black screen and if you're running debugger, it says the project is stuck loading at 100%.

## Expected result

The project should allow me to preview.

## More details
That's pretty much it.

**Affected browsers/platforms:**
Desktop build of Construct 3 and possibly others.

**First affected release:**
r138.2 beta

## System details
<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r138.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 138 gb
Storage usage (approx): 32 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I had a quick look into this, as I've been looking at the NW.js plugin recently. Will leave it to @AshleyScirra though as he's grabbed it. My findings so far are that in worker mode we attempt to 'require' the 'fs' and 'path' modules in the instance, but require is not available in the worker. Either we need to move all the file reading code to the domside script or ask the NW.js team to add modules to workers...

**Comment by AshleyScirra** [comment]
NW.js actually supports adding the node features to web workers via `--enable-node-worker`. Exported NW.js projects already set this, so it should work once exported. However I forgot to add the option to the desktop builds so it doesn't work in preview. It's added for the next release. The desktop builds are on a slower release cycle but they should be updated in a couple of weeks.
