### ISSUE TITLE
Sphere Effect in C3 spreads when it is been dragged to the Viewportedge of the screen. 

### ISSUE THREAD

**Issue by HRTStudio** [Scirra/Construct-3-bugs#2645]
## Problem description

Construct3  r138-2
**Sphere Effect** spreads when it is been dragged to the edge of the screen.

## Attach a .c3p

[sphereeffect.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2894259/sphereeffect.c3p.zip)

## Steps to reproduce

1. Preview in C3 and drag the object to any edge of the screen mainly the top left edge
2. Preview in real device and drag the object to any edge of the screen
3.

## Observed result

Sphere Effect spreads when it is been dragged to the any edge of the screen.

## Expected result

Sphere Effect not be spread when it is been dragged to the edge of the screen because the effect works well on the centre of the screen.

## More details

**Affected browsers/platforms:** 

**First affected release:** 
Construct3 r135-4

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It looks correct to me. This was fixed in r137, are you sure you're using the latest release? Can you show with a screenshot what you're seeing?

**Comment by sangeeth786** [comment]
@AshleyScirra This is what it looks at the viewport edges.
![screen shot 2019-02-26 at 10 19 08 am](https://user-images.githubusercontent.com/40767502/53388112-fc82c780-39af-11e9-9800-6b453d2d9693.png)

**Comment by AshleyScirra** [comment]
I can't figure out how to get that result in your project. It looks like you have a different sprite placement in your screenshot than in the project you provided. However it looks like you're using the Sphere effect to distort the background in a way that tries to display pixels outside the window. Nothing is rendered outside the window, so the GPU will repeat the last row of pixels instead. That produces the stripe effect against window edges that you're seeing. Unfortunately this is just the way sampling works at the window edges with distorting effects; there's not much we can do about it, so closing as wontfix.

**Comment by HRTStudio** [comment]
@AshleyScirra 
Hey,
Just the Crosshair sprite object by mouse to the edges of the viewport, this is the same object i provided you with a screenshot that is used in the capx file.
