### ISSUE TITLE
DrawingCanvas: pasting 9patch object with effects misplaces the image

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#2646]
## Problem description

Pasting 9patch object with effects misplaces the image, and it may become cropped.

## Attach a .c3p

https://www.dropbox.com/s/wwto1u4j0s97xic/CanvasBug.c3p?dl=0

## Steps to reproduce

Run the file. Press Capture button.

## Observed result

Pasted image is misplaced on the canvas and cropped.

## Expected result

Pasting with or without effects should not affect image position.

## More details

**Affected browsers/platforms:** 
Chrome
Firefox

**First affected release:**

have tested on r136 and r138, didn't try earlier version.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r136 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 82 gb
Storage usage (approx): 310 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DieppedalleDavid** [comment]
Thank you Dop2000 for reporting my problem:)

**Comment by DieppedalleDavid** [comment]
Has this bug been fixed with version 139?
Is that the bug?:

"Drawing a canvas: crash when gluing an object
with effects in a canvas with effects"

Because I always have problems with sticking objects in a canvas.

**Comment by AshleyScirra** [comment]
Issues are closed when they are fixed. This issue is still open.

**Comment by DieppedalleDavid** [comment]
Ok, Thx.

**Comment by AshleyScirra** [comment]
I think this is another case of #2624, so marking as duplicate. I'll double-check this case when working on that though.
