### ISSUE TITLE
Timing problems with Tweens & Timers & timescale

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#2647]
## Problem description

I noticed that tweens & timers do not run synchronous. It seems that tweens are off by about 1 frame. (timed it with console.time) One frame doesn´t sound like a big deal, but the problem gets way worse once timescale comes into play. But even without timescale it will rather quickly desync, but I intend to use timescale quite a bit so that´s not great.

**Update: I think the 1 frame doesn´t actually matter, the timescale is the problem!** But I wouldn´t mind the one frame thing also to be fixed... :V

## Attach a .c3p

[timingbug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2896904/timingbug.c3p.zip)

## Steps to reproduce

1. Preview the layout
2. Wait for a few seconds. Notice the blue square & green rectangles desyncing more and more
3. Click anywhere on the layout, a square should spawn
4. The square moves right and should turn red exactly when it stops moving
5. Change the text input to 20 (sets timescale to 2)
6. Click again, the tween finishes way before the timer
7. Change text input to 5 (so, timescale 0.5)
8. Click again, the square turns red way before the tween finishes

## Observed result

Tweens act wrong with timescale

## Expected result

Tweens don´t act wrong with timescale

## More details
I noticed that at a timescale of 0.5 a one second timer took about 2000ms (that is correct) while a one second tween took 4000ms. Looks like timescale is applied twice or something?

![timertween](https://user-images.githubusercontent.com/31101309/53288208-35d7ef00-3786-11e9-867d-6ff073e4bc5b.PNG)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.109
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
C3 release: r131 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 1.8 gb (12.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Wackytoaster** [comment]
Also I just realised how nasty that issue actually is. Projects could rely on it working this way...

**Comment by DiegoScirra** [comment]
@Wackytoaster

The issue with timescales was solved some time ago in a beta release. It should be already out in r139 or r140.

The issue with the accumulation of error over time can not really be solved. This is because the **Regular** timer, like the one in your example corrects itself each time it starts over too make sure it keeps up with real time. The **Tweens** on the other hand, are fire and forget, they don't need to worry about error correction over time, because once they are done... that's it.

If you take your example project and replace the tweens with timers that execute only once, as time goes by they will start to diverge from the regular timer, for the same reason as the tweens do.
