### ISSUE TITLE
Using gamepad unresponsive if plugged in after opening project?

### ISSUE THREAD

**Issue by tyler3327** [Scirra/Construct-3-bugs#2648]
## Problem description

So if I open my project doesn't matter what version of construct I am using but for example I am using r136 and I plug in my game-pad I am using xbox 1 controller and start my game the game-pad is unresponsive I have to close chrome browser and reopen with controller connected before I open my game and browser. Now I wasn't sure if this was a limitation of the chrome browser itself or if it was a construct 3 issue. I did add the some events before plugging in the controller on (A) button pressed do this. Any help is appreciated thank you.

**Comment by prominentdetail** [comment]
@tyler3327 I'm having this same problem in C2.. I figured out that when you plug in the controller, it assigns it to index 1, not  index 0. If it is plugged in prior to starting the game, it is assigned to index 0.
The quick fix for me is to just use both indexes to control the player, but it'd be nice if there was a way to find which controller is being used.

**Comment by prominentdetail** [comment]
@tyler3327  also, it appears that you need to create some event that triggers something to happen, like an Alert in the browser, of if you use nw.js then you can use the Request Attention action.. There might be another way, but those are what Ive found works. Then it will be assigned to index 1.
