### ISSUE TITLE
Progress Bar Appears above all other objects

### ISSUE THREAD

**Issue by tyler3327** [Scirra/Construct-3-bugs#2649]
## Problem description

Okay so I am not sure if this is a chrome limitation or construct 3 issue but I have a cursor that is created to simplify my xbox1 game controls but the cursor appears below progress bars r136 the cursor is on a layer above the progress bar there isn't even a layer change option under progress bar. That is why I am assuming this is a chrome limitation but wanted to double check?

**Comment by AshleyScirra** [comment]
Form controls float above the canvas so cannot be layered with other objects.
