### ISSUE TITLE
Exported game doesn't work

### ISSUE THREAD

**Issue by DiscoFishGames** [Scirra/Construct-3-bugs#265]
## Problem description

*Enter a concise description of your problem here*
Exported game doesn't load (red progress bar). I have tried with Web and Desktop - same result.
When I trying Remote preview I have error (see attached bellow) and also red progress bar.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*
![image](https://cloud.githubusercontent.com/assets/28790727/26239383/7b4d6720-3c85-11e7-93dc-19f7b991fbff.png)

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Closing, see the bug report guidelines. There is nothing we can do about a report like this.
