### ISSUE TITLE
AJAX.LastData not loading .json files into dictionary once debug apk is built r138-2 (or in preview mode)

### ISSUE THREAD

**Issue by eonianvr** [Scirra/Construct-3-bugs#2651]
## Problem description

After loading a json, AJAX.LastData is used to parse the data. it doesnt work in r138-2 (in both browser preview on PC and debug apk

## Steps to reproduce

same issue that was reported here and closed (https://github.com/Scirra/Construct-3-bugs/issues/2534) related to loading data from JSON but now the problem is happening in both browser preview and debug apk when the previous issue was only mentionning the bug when doing a debug apk

So you can use the c3p project from the previous ticket which now is not loading the json again when the debug apk is generated from r138-2 and this time it does not work either in preview mode in browser on PC

## Observed result
JSON data is supposed to be loaded and array are supposed to be filled with their respective .json files using AJAX.
## More details

on the ticket https://github.com/Scirra/Construct-3-bugs/issues/2534 it used to work at least in preview mode in the browser, this time it doesnt work at all (and not only when doing a debug apk)

**Affected browsers/platforms:** 

* Chrome: NO
debug apk: YES

**First affected release:** 
Constuct 3 r138-2  release

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It works for me in preview mode in r138.2. You have to preview project (F4) instead of preview layout (F5) though, since it makes the requests on a different layout. Please make sure you attach a truly minimal project demonstrating the issue, since that avoids gotchas like this. If AJAX really is just broken, you should be able to demonstrate that with a trivial project (say, two events); if that works it points to a problem with your project. I'm assuming this is simply a mistake so closing; please re-file following all the guidelines with a minimal project if you still think there is an issue.

**Comment by eonianvr** [comment]
I comfirm it works as apreview but did you test as a debug apk, because it is still not working for me. Does it for you?

**Comment by AshleyScirra** [comment]
Please file a new report using a minimal project as mentioned. Your original report stated it wasn't working in preview mode, but it does, so that must have been a mistake, and you may have also made a mistake on Android.

**Comment by eonianvr** [comment]
I will , but i need to clean up as  much before giving it to you.
But just to let you know, when I saw my app was not loading the json in the debug apk (but worked in preview mode) I checked if an issue was opened related to the same problem and found the one mentionned (2534)
So I downloaded the capx from the previous issue and open it in R138-2 to see if there was the same problem and it was the case.
Sorry to have thought the problem was in previous mode too , it was due to the amount of data the capx of the previous issue was trying to load. I was mislead on that.
Still the debug  apk from issue 2534  doesnt load the json  when you generate a debug apk. You can check that until I clean up my capx and open a new issue. Thanks for the great response time! REALLY APPRECIATE.

**Comment by eonianvr** [comment]
new ticket opened: https://github.com/Scirra/Construct-3-bugs/issues/2655
