### ISSUE TITLE
issue in viewport when there is not instance in layout

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2652]
Suppose Sprite name is "Button"
i am trying to create "Button" at start of the layout and set position to center of the layout by using x = ViewportWidth(0)/2 and y = ViewportHeight(0)/2
Now problem is When i keep at least 1 "Button" in layout then event works good and sprite is creating in center but if i delete "Button" from layout then Top Left corner of "Button" is positioned in the center of layout. and then if i again just insert a "Button" in layout then it work good.
I don't know if this is a bug or if this is how it was made.

## Problem description

On create object and x = ViewportWidth(0)/2 and y = ViewportHeight(0)/2 doesn't center the sprite when there is not sprite in the layout but it works very well if we keep at least single sprite in the layout.

## Attach a .c3p
[create sprite center of layout.zip](https://github.com/Scirra/Construct-3-bugs/files/2900085/create.sprite.center.of.layout.zip)

## Steps to reproduce

1. Insert Sprite in Project panel and don't inset it in layout
2. in event sheet On start of the layout > create that sprite and  x = ViewportWidth(0)/2 and y = ViewportHeight(0)/2
3. preview it

## Observed result

Top Corner of the sprite is positioned to the center of the layout

## Expected result

Origin of the layout should be center of the layout

## More details
insert sprite in layout and preview, Check this result and delete sprite from layout and preview then see result. You'll notice the difference.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by kingpirux** [comment]
that's how it works, if you dont have an instance to save the initial configuration then construct doesn't know how to deal with it, create a storage layout and drop all the instances that needs information or starting configurations there.

**Comment by AshleyScirra** [comment]
It's a bug, the origin should be correct even if there are no instances in the layout. Thanks for the report, it should be fixed in the next release.
