### ISSUE TITLE
Deleting and Undoing assigns wrong icon to sprite

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#2653]
## Problem description

Latest Beta:

When deleting a Sprite object from the objects bar and then immediately undoing the delete, the sprite preview icon in the objects bar is changed to the default icon for sprites:

![image](https://user-images.githubusercontent.com/30116964/53334395-f41b8580-38f8-11e9-804f-d2ff9addd77e.png)

## Steps to reproduce

1. Create new project
2. Add a sprite
3. Delete Sprite from Objects bar (to remove from project)
4. Press CTRL/CMD+Z

## Observed result

Sprite icon is changed to the space invaders icon.

## Expected result

Icon to stay the same as before it was deleted.

## More details

Chrome   macOS

**Comment by AshleyScirra** [comment]
Fixed for next release.
