### ISSUE TITLE
NWjs, Worker, and AJAX

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#2658]
## Problem description

If you export to NWjs while having worker enabled and having an AJAX object in your project, the resulting export won't load.

## Attach a .c3p

[https://drive.google.com/open?id=1V430_bITXVSc9jJO2VTb8kiDBDfXkZyH](https://drive.google.com/open?id=1V430_bITXVSc9jJO2VTb8kiDBDfXkZyH)

## Steps to reproduce

1. Place AJAX in the project.
2. Enable worker.
3. Export to NWjs.
4. Run the export.

## Observed result

The export refuses to load. You just get NWjs with a black screen.

## Expected result

The export should run normally.

**Affected browsers/platforms:** 

NWjs

**First affected release:**

R139

## System details

<details><summary>Platform information
Browser: Chrome
Browser version: 74.0.3717.0
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3717.0 Safari/537.36
C3 release: r139 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 100 gb
Storage usage (approx): 52 gb (52.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)</summary>

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
