### ISSUE TITLE
Construct3 Export in Android And iOS option not running on real devices, Just stuck on the Construct3 splash screen.

### ISSUE THREAD

**Issue by HRTStudio** [Scirra/Construct-3-bugs#2659]
## Problem description

Construct 3 r139 
Export in Android or iOS, Application just stuck on Construct3 splash screen.

## Attach a .c3p

[stuck on splash screen.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2903866/stuck.on.splash.screen.c3p.zip)

## Steps to reproduce

1. In C3 build project with option Xcode for iOS.
2. In C3 build project with option DebugAPK for Android.
3.

## Observed result

The Application doesn't run, just gets stuck on the Construct3 splash screen.

## Expected result

The Application should run.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce on Android here - a debug APK runs just fine. Assigning to @shortercode to double check.

@HRTStudio - it looks like you used the noise textures demo as the project. Is the problem specific to Advanced Random, Drawing Canvas or another plugin?

**Comment by HRTStudio** [comment]
@AshleyScirra 
The export of my project too, lags on construct splash screen.

**Comment by AshleyScirra** [comment]
The attached project is unique in that it does a lot of CPU work on startup, to generate the noise map. Are you sure it's not just waiting to do that? On a slow device it could take a while.

**Comment by HRTStudio** [comment]
@AshleyScirra 
I waited for a while to get the layout loaded but didn't, tried on device iPhone 6s, Google Pixel

**Comment by HRTStudio** [comment]
@AshleyScirra 
Today the build exported from Construct3 is working on both ios and Android, So closing this issue.

Thanks
