### ISSUE TITLE
[r29] Crash when hitting "Done" while an invalid parameter is in an action or condition dialog

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#266]
## Problem description

Entering an invalid value into some parameter for an action or condition and clicking the "Done" button several times causes the editor to crash. When I discovered this it was in the course of working normally and happened after only a click or two (I may have double-clicked), but the conditions were similar to the case described below - I'd misspelled a family name in my project in some action (can't recall which but it doesn't seem to matter) and hit "Done", and the editor crashed.

## Attach a .c3p

A new, empty project can produce this crash so I didn't upload anything.

## Steps to reproduce

1. Create a new project.
2. Open the default event sheet and add an event. "System: Is between angles", for example.
3. In the dialog "Parameters for System: Is between angles", in the "Angle" parameter, type some non-numeric nonsense like "fred".
4. Repeatedly hit the "Done" button, ignoring the error message popups. You may have to really spam it when reproducing the bug this way, but it crashes 100% of the time for me.

## Observed result

Editor crashes.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r29/main.js, line 2, col 572013
Message: Uncaught TypeError: Cannot read property 'ownerDocument' of null
Stack: TypeError: Cannot read property 'ownerDocument' of null at ǃJ.ǃT.ǃVH.ǃhO.ǃJHO (https://editor.construct.net/r29/main.js:2:572013) at ǃJ.ǃT.ǃVH.ǃhO.ǃJHU (https://editor.construct.net/r29/main.js:2:572301) at Animation.app.ǃka.ǃuRS.onfinish (https://editor.construct.net/r29/main.js:2:572215)
Construct 3 version: r29
URL: https://editor.construct.net/index.html
Date: Fri May 19 2017 01:11:02 GMT-0700 (Pacific Daylight Time)
Uptime: 75.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I spammed the button really hard and didn't see anything go wrong. Crash report looks like something to do with balloon tip so maybe worth Diego taking a look.

**Comment by Scoremonger** [comment]
As of r29.2 I'm not able to reproduce this either. I'll leave the report open in case Diego still wanted to look into it, but it seems fixed.

**Comment by DiegoScirra** [comment]
Fixed in r30.

You need to spam the mouse click real bad.
