### ISSUE TITLE
Undo option not working for resize sprites in layout.

### ISSUE THREAD

**Issue by HRTStudio** [Scirra/Construct-3-bugs#2660]
## Problem description

Construct r139,r138-2,r-138
Undo option not working for sprite resize.

## Attach a .c3p

[Undo Resize.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2903890/Undo.Resize.c3p.zip)

## Steps to reproduce

1. Just Resize the sprite objects in the layout editor and press the command+Z to Undo the changes.

## Observed result

The resize sprite objects in the layout editor doesn't gets to its original size when the Undo option has been done.

## Expected result

The resize sprite objects in the layout editor should get to its original when the Undo option has been done.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta release
