### ISSUE TITLE
"Pay for the ad-free version" button appears on the Mobile Ads consent screen even though it's set to false

### ISSUE THREAD

**Issue by RichardAstrom** [Scirra/Construct-3-bugs#2661]
The "Pay for the ad-free version" button appears on the Mobile Ads consent screen, even though I have stated that I don't want to show it in the parameters for the Configure action in the Mobile Ads plugin.

I have left the plugin settings blank and I'm calling the Configure manually.

_Note: It works if plugin properties is already filled in and it starts automatically._

![consentbug2](https://user-images.githubusercontent.com/3534495/53408695-6f476f00-39bf-11e9-86e1-1fff23772f14.png)
![consentbug](https://user-images.githubusercontent.com/3534495/53408707-7a020400-39bf-11e9-84db-95339ff85bae.png)

## Steps to reproduce

1. Build a project. with the Mobile Ads plugin.
2. Keep the settings blank and call it manually from an event sheet.
3. Set "Show Ad Free on consent" to false.

## Observed result

"Pay for the ad-free version" button appears when you call configure.

## Expected result

The "Pay for the ad-free version" button shouldn't show.

## More details

Happens both on iOS and Android.

r139

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.109
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
C3 release: r139 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 426 mb (2.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Looks like the parameter was being read inversely, I don't think many people use this option ( it's kind of legacy but useful for people that want to show the configure screen later on ). I've patched for the C2 and C3 runtimes. Will be available in the next beta.
