### ISSUE TITLE
[r29] Add variable with "Enter" key - minor bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#267]
## Problem description

When trying to add a new variable or global variable at an existing global variable location with the "enter" key will cause C3 to also open the edit dialogue for that existing global variable because it was highlighted.

This is also affected when adding a new global variable with the "enter" key at an existing group header.

## Steps to reproduce

1. Create a global variable.
2. Right-click this global variable that just been created and click "add another variable".
3. This time, press "enter" key rather than clicking "ok" to complete the creation process.

## Observed result

The initially created global variable's edit dialogue is open..

## Expected result
Does not open the initially created global variable just because I add another variable here.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29

Local storage
Storage quota (approx): 7.2 gb
Storage usage (approx): 390 mb (5.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce in r30. Is this still happening there for you?

**Comment by jaydonteh** [comment]
Yes it can still be reproduced on r30.

**Comment by AshleyScirra** [comment]
I've tried following your steps and it worked OK. Is there another way to reproduce it, or something I'm missing?

**Comment by jaydonteh** [comment]
Try this one, as it is the same issue:

1. Create a group.
2. Right-click the group's header and click "add global variable".
3. Press enter in the global variable edit dialogue.

You should see the group's edit dialogue opened.

**Comment by jaydonteh** [comment]
UPDATE: I had my UI animation disabled which caused this bug.

**Comment by AshleyScirra** [comment]
Thanks, that did the trick. Fixed for r31.
