### ISSUE TITLE
Greenworks Steam overlay does not work on Mac 

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#2670]
## Problem description
Overlay does not activate on Mac. On other Mac games, overlay activates.

## Attach a .c3p

Remove *.zip from filename.
[GreenworksOfficialTest.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2917448/GreenworksOfficialTest.c3p.zip)

## Steps to reproduce
Build nw.js project for Mac.
Use nw.js 0.33.3
Add steam libs to app.nw
Add steam_appid.txt to app.nw (use '480' as steam_appid.txt if needed.)
On Steam client, Games->Add non-steam Game, point to application bundle.
From Steam, launch new shortcut.
On game click activate overlay.

## Observed result
Log displays user name and game language (shows Greenworks API is working.)

Overlay does not appear.

## Expected result

Overlay should appear.

## More details
I see mixed issue reports on the Greenworks github about issues with Greenworks/nwjs/Electron with overlay with Mac, however wanted to see if there was any extra insight or work around for C3. This same test works with overlay in Windows 10 and nw.exe export.

## System details
Mac OSX
Other non C3 games (e.g. Darkest Dungeon) have working overlay on this system.

**Comment by AshleyScirra** [comment]
I'm afraid this isn't controlled by Construct's code. The overlay is invoked by Greenworks, and it is rendered by Steam. If it works on a different platform this suggests Construct's code is correct (because it is platform neutral and makes the same call on all platforms) and that the problem lies elsewhere. You'll need to pursue this with Greenworks or Valve.

**Comment by MikalDev** [comment]
Thanks for checking, was hoping for a 'hail Mary' from Construct for a workaround, but not surprised about the answer. There are already a number of open issues for this on the Greenworks github.
