### ISSUE TITLE
Physics and parallax/z-elevation don´t work together

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#2671]
## Problem description

Physics does not take parallax layers into account. Z-Elevation does seem to be taken into account, but not correctly. I have the feeling that this maybe isn´t intended to work (or impossible to get working) but I want to report it anyway.

## Attach a .c3p

[parallaxphysics.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2918720/parallaxphysics.c3p.zip)

## Steps to reproduce

1. Preview project

## Observed result

With parallax, the objects collision poly stays as if the parallax is at 100% while the sprite moves at the proper rate.
With z-elevation the collision poly appears to be moving, but not at the proper position/scale/rate

## Expected result

Physics objects to reflect the visual changes made by parallax or z-elevation settings.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.119
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
C3 release: r139 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 1.9 gb (12.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Parallax breaks the connection between real position and displayed position. Z elevation can be thought of as doing the same (because collisions etc. continue to work as if it was at Z=0). The physics engine has no concept of displayed positions and works only in real positions. In Construct's engine we've hacked in support for collision testing across parallaxed layers, because - for reasons that have never been clear to me - people seem to want it. I don't think it's feasible to make the same change to the box2d engine that powers the Physics behavior - it has no concept of parallax at all. Besides, why would you need this? It makes no sense to me - you want objects that are not actually overlapping to count as colliding because display effects moved them?

**Comment by Wackytoaster** [comment]
> Besides, why would you need this? It makes no sense to me - you want objects that are not actually overlapping to count as colliding because display effects moved them?

Stuff like this emerges simply because I do a lot of prototyping, I just see something or have an idea pop into my head and first thing I do is drop it into construct and see what I can do. That´s also the case here. I think the platform behavior will actually do fine here with some tweaks (thanks to your hacking), but the physics looked potentially bugged to me so I reported it. As I mentioned, I had a suspicion that this was actually not intended to work together, but I obviously can´t be sure about that.

As for why people want that... it makes sense? If it visually collides, it collides. I know that they technically don´t actually overlap, but visually it makes sense. And I think generally people work off of visuals and not technicalty.

**Comment by AshleyScirra** [comment]
> As for why people want that... it makes sense? If it visually collides, it collides.

How would you use this in a meaningful gameplay mechanic though? Suppose you have some clouds or mountains in the background and you parallax them to simulate the distance, which is what parallax is for. Now if you collide between them the visual result is nonsensical - you're colliding with something that is visually far off in the distance. It's like running along an empty field but bumping in to a mountain in the background half way across. Given that parallax is intended to be used for a fake background depth effect, what useful gameplay mechanics are enabled by allowing collisions between them? I can't think of any.

**Comment by Wackytoaster** [comment]
Let´s just say I saw something that made an awesome use of parallax layers. Nonsensical... yeah, sort of. But does it have to always make sense? What if I just make sense of it :)

In any case, what if I have a game that uses elements in the foreground. These elements could obscure the player and I want to prevent that by slightly changing opacity when they overlap the player. The easiest way is of course to check if they overlap. Yes, they are not literally overlapping, just visually, but I still need to know if they visually do overlap.
