### ISSUE TITLE
Whitelist version 2.1.0 of "cordova-plugin-taptic-engine"

### ISSUE THREAD

**Issue by RichardAstrom** [Scirra/Construct-3-bugs#2673]
Hi! We're making our own plugin for Haptic Feedback on iOS devices. Is it possible that you could whitelist version 2.1.0 of the "cordova-plugin-taptic-engine"?

[https://github.com/EddyVerbruggen/cordova-plugin-taptic-engine](
https://github.com/EddyVerbruggen/cordova-plugin-taptic-engine)

According to this post: [https://github.com/Scirra/Construct-3-bugs/issues/558](https://github.com/Scirra/Construct-3-bugs/issues/558) version 2.0.0 is already whitelisted, but unfortunately that version crashes on device. We have tried version 2.1.0 with Cordova CLI and it works fine.

Thanks!

## Steps to reproduce

1.
2.
3.

## More details

iOS 

139 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Looks fine, I've updated the whitelist and published it to the server. I kept the old version on the whitelist so if your referencing 2.0.0 anywhere you will need to update it.
