### ISSUE TITLE
Z-order bar slows down performance on big layouts

### ISSUE THREAD

**Issue by Mak14** [Scirra/Construct-3-bugs#2674]
## Problem description

Hi, i have one  big layout with lots of objects in it. 
When z order bar is enabled it causes a slow downs when selecting an object on scene and deselecting it ( click on the empty space). It takes almost 0.5 of a second to react to the click
Without Z order bar there is no issues with selecting sprites

## Attach a .c3p

https://www.dropbox.com/s/lu4vz3ntma009dy/Z%20order%20test.c3p?dl=0

## Steps to reproduce

1. Enable Z order bar in the View menu
2. Open layout 1
3. Select an object on the scene
4. Touch the empy space to deselect it

## Observed result

With Z order bar enabled there is delay when you selecting and deselecting a sprite.

## Expected result

No delay when you selecting an object ( Like when Z order bar is not shown)

## More details

**Affected browsers/platforms:**  

Happens on Win7 in Chrome and Firefox

**First affected release:** 
I'm on the r139 now and dont know is it presents on the previous builds

## System details

Platform information
Browser: Chrome
Browser version: 72.0.3626.119
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
C3 release: r139 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 4.1 gb
Storage usage (approx): 256 mb (6.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by DiegoScirra** [comment]
The performance has been improved for the next release.

**Comment by Mak14** [comment]
Hi, thanks for the update, but is it possible to make it work without any delay in selecting? 
There is still tiny delay, but it is noticeable. Without z order bar it is still works smoother.

Thanks!
