### ISSUE TITLE
Cannot edit properties of an object from different layout

### ISSUE THREAD

**Issue by Mak14** [Scirra/Construct-3-bugs#2676]
## Problem description

Trying to edit variable or a behaviour properties of an object that is not on the current layout,  but the row with instances is not active and  shows "(no instances)" sign.
But. When i have 2 layouts, and L1 has the Sprite on the scene, i can move to the event sheet and select this object in project bar, then i see the instances and i'm able to edit them.
But if i have L2 opened and then moving to the event sheet, selecting this sprite object on the project bar, and i see inactive rows with (no instances) text in there.

## Attach a .c3p

Happens in any project

## Steps to reproduce

1. Open C3
2. Create sprite object
3. Add any behaviour or variable to the sprite
4. Create 2 layouts
5. Drag Sprite object to any of them
6. Move to the layout that doesn't have the sprite object on it.
7. Select Sprite object in the Project bar to edit variable or behaviour

## Observed result

There is inactive rows of the behaviour or variable, and i cannot edit them

## Expected result

Ability to edit properties of the object which is not on the current active Layout .
Like it was in C2

## More details

**Affected browsers/platforms:**  Chrome and Firefox both have this issue

**First affected release:**  r136,139

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.119
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
C3 release: r139 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 3.8 gb
Storage usage (approx): 407 mb (10.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Selecting objects in the Project Bar shows properties for instances on the last active layout, which is the last one you looked at. If you want to edit instances across different layouts, use 'Select all in project' from the Project Bar instead.
