### ISSUE TITLE
 Possible bug C3 as text appears flipped on X axis on Chrome OS

### ISSUE THREAD

**Issue by lulucrystacake** [Scirra/Construct-3-bugs#2677]
## Problem description

Text flipped on x axis on ChromeOS windowsOS is fine 

## Attach a .c3p

![screenshot-editor construct net-2019 03 02-10-16-04](https://user-images.githubusercontent.com/48164635/53687927-46014880-3d09-11e9-83df-472b01b88fc7.png)

link to file created in Version 74.0.3713.0 (Official Build) dev (64-bit)

[https://drive.google.com/open?id=1aJJ8hAyxpe5qvXXsTtv4sJQGhr9Hi5xn](url)

[text flipped chromeos.zip](https://github.com/Scirra/Construct-3-bugs/files/2922517/text.flipped.chromeos.zip)

## Steps to reproduce

1. open C3 add text object to layout
2.
3.

## Observed result

text flipped x axis no workaround

## More details

only chromeOS 

windows Chrome browser is fine

**Affected browsers/platforms:** 
ChromeOS

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce on an Acer Chromebook 14 running Chrome 72.0.3626.117 (stable). Note generally if something works everywhere but is only broken on one device/platform, that indicates a problem with the device/platform, not Construct. Additionally you noted you are using a pre-release (dev) version of Chrome, which can be very buggy. If you don't think this is just a quirk of the pre-release version and still want it investigated, please report this issue to Google.

**Comment by lulucrystacake** [comment]
ok i will try stable release thanks for reviewing - llc
