### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property '_GetLastCachedZIndex' of null

### ISSUE THREAD

**Issue by esowe** [Scirra/Construct-3-bugs#2678]
## Problem description
Occasionally when using render cells and scrolling the layout, the execution freezes for a few seconds and the layout seems to reset to its initial state, but without restarting properly. In the debugger, the time stands still, but all objects can be accessed. The console shows the following two error messages:

Uncaught (in promise) TypeError: Cannot read property '_GetLastCachedZIndex' of null
    at a (renderCell.js:1)
    at Array.sort (<anonymous>)
    at C3.RenderCell._EnsureSorted (renderCell.js:1)
    at C3.RenderCell.Dump (renderCell.js:1)
    at C3.RenderGrid.QueryRange (renderGrid.js:1)
    at C3.Layer._GetRenderCellInstancesToDraw (layer.js:1)
    at C3.Layer._DrawInstances_RenderCells (layer.js:1)
    at C3.Layer.Draw (layer.js:1)
    at C3.Layout.Draw (layout.js:1)
    at C3.Runtime.Render (runtime.js:1)

renderCell.js:1 Uncaught (in promise) TypeError: Cannot read property '_GetLastCachedZIndex' of null

## Attach a .c3p
[RenderCells.zip](https://github.com/Scirra/Construct-3-bugs/files/2922578/RenderCells.zip)

## Steps to reproduce
I have been unable to reproduce this reliably. Occasionally it happens quite often but most of the time not at all for long periods. I thought I'd report this anyway, in case the console error log is of any help.

## Observed result

See description above.

## Expected result
The execution should continue and no error messages should be shown.

## More details

**Affected browsers/platforms:** 
Only tested in Chrome

**First affected release:** 
First noticed in R139.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.109
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
C3 release: r139 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 32 gb
Storage usage (approx): 128 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)ASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I couldn't reproduce this after leaving it running for a while.

I'm afraid in general we cannot investigate bugs that cannot be reliably reproduced. Debugging issues could involve observing it a few dozen times, so it makes it nearly impossible to deal with if we can't reliably repeatedly observe the issue happening. Can you find a more reliable way to reproduce the problem?
