### ISSUE TITLE
[r29] Drag a trigger or action when its entire event block is selected bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#268]
## Problem description

In C2 you could just drag individual triggers or actions around in an event block even if the entire event sheet's events was selected. Which basically means C2 will deselect when you try to drag from the triggers or the actions position. But in C3 it does not deselect perhaps by design. In my experience of using C3 there are countless times when I have to select a trigger or action first before I drag because I'm already highlighted the entire event block. This happens usually when I copy pasted an event block in which I would want immediately to sort the triggers or actions.

## Steps to reproduce

1. Create any event block with a condition; no need actions.
2. Duplicate this event block.
3. Select the entire event block of either event blocks.
4. Try dragging the condition of the selected event block into the other event block. So that the other event block now has 2 conditions.

## Observed result
You cannot drag the condition. It drags the entire selected event block.

## Expected result

Should deselect the event block and able to drag only the condition around just like in C2.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29

Local storage
Storage quota (approx): 7.2 gb
Storage usage (approx): 389 mb (5.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Well spotted, should work more like C2 in r31.
