### ISSUE TITLE
Selecting object by UID Bug on trigger

### ISSUE THREAD

**Issue by ome6a1717** [Scirra/Construct-3-bugs#2682]
## Problem description

It's a bit hard to decipher, but from what I can tell, if a sprite is triggered via pathfinding (ie On Path Found, or On Path Arrived, etc. etc.), you cannot select another sprite by UID if there are multiple of the same sprites.

The best way to describe this is this:

1. Have a sprite called enemy
2. Have a SINGLE sprite called Pathfinder that is pinned to every enemy (as not to have a specific sprite PER enemy)
3. Set an instance variable on the pathfinder to the enemy UID that it is pinned to.
4.  On a path found trigger, select the enemy by UID (compared to the instance variable on the pathfinder sprite) and "move along path"

What ends up happening is that if there is 1 of each object on screen, everything works perfectly.  However, if you have multiple enemies, only 1 will work at a time.

## Attach a .c3p

https://www.dropbox.com/s/tjfjogob2tkjsjd/Instance%20Picking%20Bug%20UID.c3p?dl=0

(couldn't figure out how to attach)

## Steps to reproduce

1. Run the project and observe
2. Each enemy and pathfinding should be randomly moving around the screen
3. Only one will

## Observed result

Only 1 enemy runs around the screen.

## Expected result

All of the enemies should be running around on the screen randomly.

## More details

I've tried not having every x seconds under for each and instead having an instance variable that I subtract from, but that had no effect.  I've tried to wrap the instance variable into a number var before parsing it into the UID check, but that also had no luck.

**Affected browsers/platforms:**

Chrome (Windows)

Most recent stable version (136), but this is new code that was put in after the update.

## System details

<details><summary>View details</summary>

Browser: Chrome
Browser version: 72.0.3626.119
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
C3 release: r136 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 6.7 gb (21.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is not a bug. There are two mistakes in your events:

1. At event 7, you have "Every 1 seconds" inside a for-each loop. The event really means "this event has not run for the past 1 second". However since you repeatedly check that, on the first iteration of the loop it runs, but all subsequent iterations of the loop are immediately afterwards so it has not been 1 second again yet and so the event does not run.

2. In event 10, you use the expression `Enemy.UID` while multiple enemies are picked. This expression can only return one value, so cannot represent the fact multiple enemies are picked. You need another 'For each Enemy' in event 9.

Also it looks like you are trying to reinvent [containers](https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/objects/containers) using UIDs - putting Enemy and Pfer in a container should radically simplify the events.
