### ISSUE TITLE
Picking multiple instances  with UID doesn't work

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#2684]
## Problem description

Picking instances with UID doesn't work if there are more than one in one event.

## Attach a .c3p

[picking instance bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2926563/picking.instance.bug.zip)

## Steps to reproduce

Separate the "pick UID events" and it should work. 

1.
2.
3.

## Observed result

Doesn't work.

## Expected result

It should work as intended.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The events don't make sense. You have two conditions picking different UIDs. The first condition picks a single instance with UID 1. Subsequent conditions then work with the instances so far. So the second condition has a single instance picked with UID 1, and checks if it has the UID 3. That is never the case, so the event never runs.
