### ISSUE TITLE
[Desktop] Window State Resets After Restarting C3 With Modified Display Scale

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#2685]
## Problem description

The display scale now stays but there is still an issue with the maximized window state not applying correctly. 

## Steps to reproduce

1. Open C3 (r140) desktop and maximize the window
2. Inc/Decrease the display scale and restart C3
3. Notice that C3 didn't restore the window state (maximized)

## Observed result

The maximized window state doesn't load correctly after a restart with applied display scale

## Expected result

The window state should restore correctly.

## More details

**Affected browsers/platforms:** NW.js (Windows 7)

**First affected release:** r140 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r140 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 153 gb
Storage usage (approx): 143 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by TheRealDannyyy** [comment]
Reference issue #2304

**Comment by shortercode** [comment]
Looks like the resize watcher is triggering the "not maximised" label when the display scale changes, will see if I can workaround it somehow.

**Comment by shortercode** [comment]
Okay, this issue is kinda of awkward but I think I have a good workaround in place. Patch will be in the next release.

**Comment by TheRealDannyyy** [comment]
Thanks will check it out as soon as the next release goes live.

To give some positive feedback, the new implementation to restore all the window states is much faster than the old one. Generally feels a lot more responsive.

**Comment by TheRealDannyyy** [comment]
Thanks for the fix! Checked out several cases and it all works as intended now.
--- Closing issue ---

**Comment by shortercode** [comment]
Glad to hear, thanks @TheRealDannyyy
