### ISSUE TITLE
Timeline - Crash on right click on timeline dark grey seconds bar

### ISSUE THREAD

**Issue by justifun** [Scirra/Construct-3-bugs#2686]
## Problem description

Timeline crashes with a "oops something went wrong" error

When right clicking the dark grey seconds bar in the timeline while running C3 r 140 you get a hard crash

## Attach a .c3p

https://www.dropbox.com/s/n3a1hlky38e0rxe/Timeline%20Example.c3p?dl=0

## Steps to reproduce
1. Right click the dark seconds bar in the timeline view

## Observed result

Oops! Something went wrong Crash. (see below for crash log)

## Expected result

not crash

## More details

**Affected browsers/platforms:** 

C3 r 140 windows latest beta desktop build
C3 r 140 chrome web version of C3

c3 r140

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r140/main.js, line 2, col 117273
Message: Uncaught TypeError: expected finite number
Stack: TypeError: expected finite number at Function.ǃKl (https://editor.construct.net/r140/main.js:2:117279) at o.ǃSy (https://editor.construct.net/r140/main.js:81:437225) at e.ǃoUN (https://editor.construct.net/r140/components/bars/timelineBar/timelineBar.js:1:48627) at HTMLDocument. (https://editor.construct.net/r140/components/bars/timelineBar/timelineBar.js:1:44957) at HTMLDocument. (https://editor.construct.net/r140/main.js:2:206628)
Construct 3 version: r140
URL: https://editor.construct.net/r140/
Date: Mon Mar 04 2019 13:08:15 GMT-0800 (Pacific Standard Time)
Uptime: 21.7 s

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r140 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by justifun** [comment]
![image](https://user-images.githubusercontent.com/2512933/53763410-96021b80-3e7f-11e9-999b-9b0e04786684.png)

**Comment by DiegoScirra** [comment]
Fixed
