### ISSUE TITLE
speech synthesis plugin does not work on android

### ISSUE THREAD

**Issue by rrcard** [Scirra/Construct-3-bugs#2687]
good night.

In the attached file, the speech synthesis plugin works in the chrome browser forecast.

It does not work when I export to android. How to solve this bug?

[speech.zip](https://github.com/Scirra/Construct-3-bugs/files/2928919/speech.zip)

**Comment by AshleyScirra** [comment]
The event 'Supports speech synthesis' is not true in an APK, so you should not expect its features to work.

It looks like Google do not yet support speech in the webview (which is what APKs use): https://bugs.chromium.org/p/chromium/issues/detail?id=487255
Follow that issue for updates.
