### ISSUE TITLE
Local Variable bug

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#2690]
## Problem description

Some events doesn't work for local variable, But works fine for global.

## Attach a .c3p

[localVariable.zip](https://github.com/Scirra/Construct-3-bugs/files/2931778/localVariable.zip)

## Steps to reproduce

1. Test the project with the whole LOCAL group enabled,
2. See it doesn't work,
3. Now go back to the event sheet, disable whole LOCAL group, and enable the whole GLOBAL group.
4. Test the project. It should work fine.

## Observed result
Nothing happens.

## Expected result

It should work as for global.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Wackytoaster** [comment]
Local variables automatically reset every tick, that´s why it isn´t working. You can set the local variable to be static though and it will work fine.

![static](https://user-images.githubusercontent.com/31101309/53820768-bbb91e80-3f6c-11e9-87ad-b469e4308c9d.PNG)

**Comment by Ind1eed** [comment]
Im idiot :D thank you

Wt., 5 mar 2019, 17:35 użytkownik Wackytoaster <notifications@github.com>
napisał:
