### ISSUE TITLE
Unable to preview projects in r137

### ISSUE THREAD

**Issue by scmborg** [Scirra/Construct-3-bugs#2693]
## Problem description

Previewing a project in r137 results in a black screen (normal preview) or hangs at 0% loading (debug mode).

## Steps to reproduce

1. Open a project in r137
2. Attempt to preview project

## Observed result

Construct displays a black screen (normal preview) or hangs at 0% loading (debug mode).

## Expected result

Projects preview as intended.

## More details

• Tested on Chrome, Firefox, and Safari on Mac and Chrome on PC
• Tried clearing all cookies and history
• Issue occurs with new projects and template projects

**Comment by luckyrawatlucky** [comment]
latest version is r140. Stay updated.

**Comment by scmborg** [comment]
Thanks, Lucky--I didn't quite understand how things worked when using beta version. Will migrate to r140.

**Comment by AshleyScirra** [comment]
As per the guidelines please only report issues that reproduce in the latest release.

**Comment by scmborg** [comment]
Sorry, Ashley, I hadn't seen the guidelines. I'll be sure to review them before reporting any bugs in the future!
