### ISSUE TITLE
undo (ctrl + z) causes crash

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-3-bugs#2694]
## Problem description

using the shortcut ctrl+z (undo) crashes the program. Have had this happen multiple times on two different computers. Seems to happen at random, though I would say it's more prevalent when stepping back through multiple steps. Today it happened after adding an image point to an object, closing the animation editor, then pressing undo.

See error report

## Steps to reproduce

1. ctrl + z
2. ctrl + z
3. ctrl + z

## More details

Been happening since I started using C3  which was Decemeber. Have only been using stable releases.

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected object @ TypeError: expected object at Function.ǃZ.ǃct (https://editor.construct.net/r136/main.js:2:116118) at e.ǃfo (https://editor.construct.net/r136/main.js:81:187878) at ǃZJ.ǃKTQ.ǃKTD (https://editor.construct.net/r136/main.js:81:529040) at ǃZJ.ǃKpV.ǃKTD (https://editor.construct.net/r136/main.js:81:516441) at window.ǃxW.ǃKTD (https://editor.construct.net/r136/main.js:81:516441) at ǃZJ.ǃKpm.ǃKTD (https://editor.construct.net/r136/main.js:81:516441) at ǃZJ.ǃKpm.ǃKTD (https://editor.construct.net/r136/main.js:81:543044) at window.ǃZdS.ǃPHg (https://editor.construct.net/r136/main.js:81:514814) at t.ǃPHg (https://editor.construct.net/r136/main.js:81:84185) at window.ǃDFd.ǃPHg (https://editor.construct.net/r136/main.js:177:635285)
Stack: TypeError: expected object at Function.ǃZ.ǃct (https://editor.construct.net/r136/main.js:2:116118) at e.ǃfo (https://editor.construct.net/r136/main.js:81:187878) at ǃZJ.ǃKTQ.ǃKTD (https://editor.construct.net/r136/main.js:81:529040) at ǃZJ.ǃKpV.ǃKTD (https://editor.construct.net/r136/main.js:81:516441) at window.ǃxW.ǃKTD (https://editor.construct.net/r136/main.js:81:516441) at ǃZJ.ǃKpm.ǃKTD (https://editor.construct.net/r136/main.js:81:516441) at ǃZJ.ǃKpm.ǃKTD (https://editor.construct.net/r136/main.js:81:543044) at window.ǃZdS.ǃPHg (https://editor.construct.net/r136/main.js:81:514814) at t.ǃPHg (https://editor.construct.net/r136/main.js:81:84185) at window.ǃDFd.ǃPHg (https://editor.construct.net/r136/main.js:177:635285)
Construct 3 version: r136
URL: https://editor.construct.net/r136/index.html
Date: Wed Mar 06 2019 11:56:38 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 14963.2 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.119
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
C3 release: r136 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
FYI often we are unable to do anything about reports that do not include reliable steps to reproduce the problem. Your steps do not include any actions beforehand so cannot be followed since there will be nothing to undo.

**Comment by AshleyScirra** [comment]
No response from reporter for ~3 months so closing.
