### ISSUE TITLE
TimeLine Crash

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#2695]
## Problem description

https://imgur.com/jBiK96z

## Steps to reproduce

1.  Create Sprite
2.  Create Timeline
3.  Add timeline
4.  Left Click Sprite in Layout
5.  Right Click Timeline Sprite Master track bar
6.  ~~Construct 3 crash~~

## More details
**First affected release:** r140

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r140/components/bars/timelineBar/timelineBar.js, line 1, col 47017
Message: Uncaught TypeError: this.ǃtl(...).ǃoUj is not a function
Stack: TypeError: this.ǃtl(...).ǃoUj is not a function at e.ǃoUV (https://editor.construct.net/r140/components/bars/timelineBar/timelineBar.js:1:47017) at HTMLDivElement. (https://editor.construct.net/r140/components/bars/timelineBar/timelineBar.js:1:44863)
Construct 3 version: r140
URL: https://editor.construct.net/r140/
Date: Wed Mar 06 2019 11:30:03 GMT+0800 (中国标准时间)
Uptime: 66.6 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.119
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
C3 release: r140 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release.
