### ISSUE TITLE
Issue in debug & Boolean variable when there is no instance in layout

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2696]
## Problem description

there are 2 issues found when there is no sprite in layout.
1) It doesn't shows Sprite's properties in debug mode when we select sprite.
2) Toggle Boolean also doesn't toggle.
but if we insert a sprite in layout then both of these are working properly. 

## Attach a .c3p
[create sprite center of layout.zip](https://github.com/Scirra/Construct-3-bugs/files/2934581/create.sprite.center.of.layout.zip)

## Steps to reproduce

1. Create Sprite and delete it from layout.
2. Add a Boolean to Sprite.
3. On start of the layout > Create Sprite
4. On any click > Toggle Boolean
5. Now check these in debug mode.

## Observed result

I can't see sprite variable or properties in debug mode
Boolean toggle is not working.

## Expected result

Both of them should work correctly.

## More details
Inset a instance in layout and check debug mode and then remove instance from layout and check debug mode and see the difference

I tested it in Desktop Chrome

**Affected browsers/platforms:** <!-- Chrome

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
