### ISSUE TITLE
Vsync Issue with Moving Platform and Player Standing on Platform

### ISSUE THREAD

**Issue by Bat-Computer** [Scirra/Construct-3-bugs#2697]
## Screenshot https://imgur.com/ArVjLLP

1) Create a low resolution scene (320x180) scene with a moving platform using Bullet, Bounce off Solids and Solid Behavior. 
2) Create a Floor Sprite with Solid Behavior. 
3) Create a wall at each end of the scene for the Platform to rebound off. 
4) Create a Player with Platform Behavior. 

## I have tested this issue previously and it occurred with Construct 2 also. I have asked the community many times for a possible fix. Other that suggesting to try with Pixel Round on or off, no one seems to know a what to do. This also happens in Firefox, Chrome, NWJS and also the Offline Windows 10 Beta App. 

[Construct 3 Platform test.zip](https://github.com/Scirra/Construct-3-bugs/files/2935664/Construct.3.Platform.test.zip)

**Comment by AshleyScirra** [comment]
The project at the first link is corrupt and doesn't open: a bunch of the files are renamed .tmp. If I rename them back it opens, but is a different project to the one shown in the screenshot. Please follow the bug report guidelines and attach the correct project to ensure we can investigate your report.
