### ISSUE TITLE
Find All References dialog does not close without mouse

### ISSUE THREAD

**Issue by locohost** [Scirra/Construct-3-bugs#2701]
## Problem description

The "Find All References" dialog box has no key to close. You MUST use your mouse to click the [X] to close it. The [Esc] key or (preferably hit enter or double click on find result) should close the dialog.

## Attach a .c3p

This is not a code bug, it's missing C3 editor dialog key. Any project with any function will demonstrate.

## Steps to reproduce

1. Open any C3 project that contains any function call
2. Right click on the function, select "Find all references"
3. On "find all references" dialog, double click any result to find/highlight it in editor

## Observed result

4. Dialog does not close. It absolutely should after double click
5. Press [Esc], dialog does not close. It really should as [Esc] closes most other dialogs 

## Expected result

6. Dialog should close after double click and/or pressing [Esc]

## More details

Happens in Chrome and Firefox and Edge

**Affected browsers/platforms:** 

**First affected release:** r136 stable

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.119
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
C3 release: r136 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 63 gb
Storage usage (approx): 53 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics P630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
Added for next release.
