### ISSUE TITLE
pick a web font from this project don't appear in Edge

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2705]
## Problem description

pick a web font from this project don't appear in Edge, only gives option to pick a local font available on this device. Do i need to create new bug report on this?

## Attach a .c3p

no need

## Steps to reproduce

1. insert text plugin and type something
2. select text instance in layout 
3. choose font picker.

## Observed result

pick a web font from this project don't appear in Edge

## Expected result

pick a web font from this project should appear in Edge

## More details
Working in Browser and Desktop version. Only problem in Edge.

**Comment by AshleyScirra** [comment]
It doesn't appear in any browser, when there are no web fonts imported to the project. This is by design.

**Comment by luckyrawatlucky** [comment]
I imported a font into project but its not showing that option.

**Comment by AshleyScirra** [comment]
Please always follow the bug report guidelines. They are designed to ensure you file useful bug reports. If you don't attach a project, forget to include reproduction steps, and then only provide a screenshot, we cannot follow what you are doing.

**Comment by luckyrawatlucky** [comment]
First of all I am really sorry. I never ever read those guidelines. Today I am going to read all those guidelines.

[Font Picker issue.zip](https://github.com/Scirra/Construct-3-bugs/files/2946218/Font.Picker.issue.zip)

**Comment by AshleyScirra** [comment]
I can reproduce in Edge now, so reopening.

**Comment by AshleyScirra** [comment]
Fixed for next release.
