### ISSUE TITLE
[r29] Copy pasting events fast bugs at 1000 and new events don't render

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#271]
## Problem description

Events more than 1000 (probably kinda random number) won't render.

## Attach a .c3p

Attached 2 as .zip. The initial one is named CursorBug because I was testing something else.
[CursorBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1013904/CursorBug.zip)
[EventBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1013910/EventBug.zip)

## Steps to reproduce

1. Open a blank project
2. Create 20 x *On start of layout* 
3. Copy and paste this group until you reach above 1000 events
![image](https://cloud.githubusercontent.com/assets/7268697/26244934/92b38182-3c9a-11e7-902c-f00b374c0788.png)

## Observed result

Events over 1000 wont render

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

Local storage
Storage quota (approx): 5.3 gb
Storage usage (approx): 369 mb (6.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
WTF - turns out there's a Chrome bug where CSS grid layout is deliberately limited to 1000 rows: https://bugs.chromium.org/p/chromium/issues/detail?id=688640

We need Chrome to lift the limit to fix this. Closing this issue, follow up at that Chrome bug.
