### ISSUE TITLE
Tween 'Set time' not working

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#2711]
## Problem description

Setting the 'time' value does not position correctly if the starting position is not zero.

## Attach a .c3p

[TweenOffsetTimeBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2948938/TweenOffsetTimeBug.zip)

## Steps to reproduce

1. Let the layout run. Everything looks fine. (Initial StartY offset is 100).
2. Now drag the green arrow back and forth.
3. You'll see at 100% it stops in the correct position, but for everything in between, it's offset.
4. Change the StartY value to zero. Do the same steps.
5. Everything works.

## Observed result

The time based calculation seems to be not accounting for the initial position/offset correctly.

## Expected result

Setting the time offset should match the play offset.

## More details

**Affected browsers/platforms:** 

**First affected release:** r136

## System details

N/A

**Comment by Fib100** [comment]
I've also observed this issue.

One more thing I want to ask about. It appears to me that when using "Set Time" on a tween, it also **pauses the tween**. You have to make a subsequent call to "Resume" to get the tween to start playing from the time you specified. Is that intended or a bug?

**Comment by DiegoScirra** [comment]
Fixed. Will be available in the next beta release.

@Fib100 That is the intended behavior.

**Comment by DiegoScirra** [comment]
@blackhornet2010

Here is a project that does the same thing as the one you posted but it is a little bit more efficient. Instead of continualy creating new tweens and setting their time, it creates one on the drag start action and then only sets it's time while dragging the handle.

[Example.zip](https://github.com/Scirra/Construct-3-bugs/files/2993320/Example.zip)
