### ISSUE TITLE
Base Container object changes when you rename any child

### ISSUE THREAD

**Issue by locohost** [Scirra/Construct-3-bugs#2712]
## Problem description

When you create a Container initially, you're setting the base/controlling (this object) object. Then you add other objects to the Container. If you rename any object in the Container, the renamed object becomes the new (this object) object.

## Attach a .c3p

This is an editor functionality bug. You can recreate in any C3 project.

## Steps to reproduce

1. Select any object in layout or project objects panel
2. Use the Create Container button to create a new Container
3. Add another couple objects to this Container
4. In project panel, rename any object in this Container

## Observed result

The (this object) object is replaced by the child object you just renamed.

## Expected result

Container (this object) object **should not change** when you rename a child.

## More details

**Affected browsers/platforms:** 

Happens in all Chrome, FF and Edge

**First affected release:** 

r136

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.121
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
C3 release: r136 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 63 gb
Storage usage (approx): 44 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: (unavailable)
Renderer: (unavailable)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is not a bug. "(this object)" means that container object is the one that is currently selected and showing properties for. In step 4, you select a different object type, in order to rename it. This changes the selection to that object's properties and the "(this object)" indicator swaps to that accordingly.

I did notice one small bug where the names of the container properties are not updated after renaming; this is fixed for the next release.
