### ISSUE TITLE
Project crashes immediately upon opening

### ISSUE THREAD

**Issue by yeahyeah333** [Scirra/Construct-3-bugs#2713]
## Problem description

After switching from r140 to r141, the project crashes immediately upon opening.

## Attach a .c3p

This would be very hard to do. Project is very large and the problem is clearly something to do with switching from r140 to r141. Hopefully the answer can be found in the crash report.

## Steps to reproduce

Open my project

## Observed result

Project crashes

## Expected result

Project doesn't crash

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** first started happening in r141

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃrMG' of undefined @ TypeError: Cannot read property 'ǃrMG' of undefined at ǃl (https://editor.construct.net/r141/main.js:2:271748) at window.ǃJHu.ǃJIz (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:6186) at new window.ǃJHu (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:3142) at Function.ǃr.ǃX (https://editor.construct.net/r141/main.js:2:151615) at window.ǃJHS.ǃsL (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:709)
Stack: TypeError: Cannot read property 'ǃrMG' of undefined at ǃl (https://editor.construct.net/r141/main.js:2:271748) at window.ǃJHu.ǃJIz (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:6186) at new window.ǃJHu (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:3142) at Function.ǃr.ǃX (https://editor.construct.net/r141/main.js:2:151615) at window.ǃJHS.ǃsL (https://editor.construct.net/r141/components/editors/textEditor/textEditor.js:1:709)
Construct 3 version: r141
URL: https://editor.construct.net/r141/
Date: Mon Mar 11 2019 09:45:59 GMT-0500 (Central Daylight Time)
Uptime: 79.5 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.121
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
C3 release: r141 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro FX 2800M Direct3D11 vs_4_0 ps_4_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_disjoint_timer_query, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, EXT_sRGB, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Please send the project to ashley@scirra.com and I'll take a look.

**Comment by AshleyScirra** [comment]
Based on crash signature assigning to @DiegoScirra, but we'll still need a project to verify.

**Comment by DiegoScirra** [comment]
Fixed
