### ISSUE TITLE
R141 - Timeline crashes when selecting new ease in ease view mode

### ISSUE THREAD

**Issue by justifun** [Scirra/Construct-3-bugs#2715]
Change the timeline to "ease" view mode, then select an ease between 2 keyframes and try to change it to a different one -> Crash

R141 - C3 crashes when trying to change an ease type in ease view mode in the timeline

## Steps to reproduce

Change timeline view to ease view mode, then click the name of the ease and pick a new one -> crash

## Observed result

"Oops something went wrong crash - see below for crash log

## Expected result
 
to switch ease type to selected one without crashing

**Affected browsers/platforms:** 
r141 C3 web and desktop version

**First affected release:** 
R141

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r141/main.js, line 2, col 151636
Message: Uncaught Error: missing placeholder '{0}' in string substitution
Stack: Error: missing placeholder '{0}' in string substitution at Function.ǃJY_ (https://editor.construct.net/r141/main.js:2:183413) at ǃJKV (https://editor.construct.net/r141/main.js:2:193453) at Object.ǃNZp (https://editor.construct.net/r141/main.js:81:554295) at new (https://editor.construct.net/r141/main.js:81:554160) at Function.ǃX (https://editor.construct.net/r141/main.js:2:151615) at https://editor.construct.net/r141/components/bars/timelineBar/timelineBar.js:1:140229
Construct 3 version: r141
URL: https://editor.construct.net/r141/
Date: Mon Mar 11 2019 10:17:34 GMT-0700 (Pacific Daylight Time)
Uptime: 1062.5 s

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r141 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by justifun** [comment]
[timeline-crash.zip](https://github.com/Scirra/Construct-3-bugs/files/2953492/timeline-crash.zip)

**Comment by DiegoScirra** [comment]
Fixed in the next beta release.
