### ISSUE TITLE
[THEME] Animation Editor Colour Balls Inconsistent

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2719]
## Problem description
This problem only occurs when you have a theme selected that is not the default theme, so currently the light or dark theme.

I do not know the correct name for these things so please correct me: [Colour Balls](https://i.imgur.com/32CCuNT.png)
However, I do know what they are for. They are suppose to represent which mouse click has that colour (the right click or the left click). 
As you see in the screenshot; The red is on the right yet it works for the left click.
Please switch these around the other way so they are representing the correct mouse click. It can be a bit confusing and it's a little frustrating to notice this all the time.

## Attach a .c3p

https://www.dropbox.com/s/4n2fz08b0bty8gw/Test_Animator_Colour_Balls.c3p?dl=0

## Steps to reproduce

1. Change your theme in settings to the light or the dark theme.
2. Reload so the theme takes effect.
3. Open the sprite. The colours selected should be black and white
4. Choose fill.
5. Click on image to fill the colour using both mouse clicks.

## Observed result

You will notice that the colour selected for the click is on the opposite side to what the mouse buttons are.

## Expected result

I expected the right colour ball to represent the right mouse click and the left colour ball to represent the left mouse click regardless what theme is selected.

## More details
This seems consistent with every version

**Affected browsers/platforms:** 
Chrome
Firefox
Microsoft Edge
Desktop version

**First affected release:** 
I have always known this to happen with Construct 3 as I like to use the dark theme despite some of it's inconsistencies in appearance compared to the default theme (Can I report other inconsistencies with the theme even if I don't know if they are bugs or not?). Sorry it's been like this for a while I have not had the time to report it. I do not have enough time to find the first version it happened in.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r141 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 726 mb (2.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta release.

I call them Colour Swatches, but I am not sure if that is the correct term either :P
