### ISSUE TITLE
r141 Dragging New/First Instance of an Object into Layout Causes Crash

### ISSUE THREAD

**Issue by Rhindon** [Scirra/Construct-3-bugs#2722]
## Problem description

Dragging a new sprite object into the layout to create the first instance thereof causes the editor to crash.

## Attach a .c3p

[Raise The Roof.zip](https://github.com/Scirra/Construct-3-bugs/files/2955011/Raise.The.Roof.zip)

## Steps to reproduce

1. Create new sprite object with an event sheet selected in the main view.
2. Assign it the Sine behavior (this appears to have no bearing on the crash).
3. Select the layout and make it viewable in the project.
4. Drag the first instance of that new object into the layout.
5. Upon releasing the mouse button, the editor should crash.

## Observed result

The editor crashed.

## Expected result

The first instance of a new object should have appeared.

## More details

**Affected browsers/platforms:** 

Tested using Chrome.
I do not have the other browsers on my computer.

**First affected release:** r141 - I just updated moments ago.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r141/components/bars/zOrderBar/zOrderBar.js, line 1, col 17240
Message: Uncaught ReferenceError: ǃIZ is not defined
Stack: ReferenceError: ǃIZ is not defined at Object.ǃIv (https://editor.construct.net/r141/components/bars/zOrderBar/zOrderBar.js:1:17240) at Object.ǃHp (https://editor.construct.net/r141/components/bars/zOrderBar/zOrderBar.js:1:16908) at Object.ǃWS (https://editor.construct.net/r141/components/bars/zOrderBar/zOrderBar.js:1:15698) at Array. (https://editor.construct.net/r141/components/bars/zOrderBar/zOrderBar.js:1:853) at Object.ǃJxm (https://editor.construct.net/r141/main.js:2:212127) at Object.dispatchEvent (https://editor.construct.net/r141/main.js:2:209989) at Object.ǃN$f (https://editor.construct.net/r141/main.js:177:649742) at t.ǃBD (https://editor.construct.net/r141/main.js:81:167903) at i.ǃsc (https://editor.construct.net/r141/main.js:81:225334) at Object.ǃjr (https://editor.construct.net/r141/components/editors/layoutView/layoutView.js:1:32091)
Construct 3 version: r141
URL: https://editor.construct.net/r141/
Date: Mon Mar 11 2019 19:13:49 GMT-0700 (Pacific Daylight Time)
Uptime: 25.4 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.121
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
C3 release: r141 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next release.
