### ISSUE TITLE
Issue found in Touch plugin or may be in Drag Drop plugin

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2723]
## Problem description
In older version i created a Sprite and added Drag Drop behavior to it and in events. 
On touch 0 start      >     Set Sprite Position to > Touch.X and Touch.Y
by doing this i click and drag Touch anywhere on layout then sprite also drags. 
but in latest version when i recreated everything then sprite drags only when i click and drag over the sprite. I have attached both older and new file. if i open older file in latest version then it still working. but recreating in newer version doesn't work. 

![Construct Issue](https://user-images.githubusercontent.com/17684135/54196484-933ea080-44e7-11e9-8abb-2a60932f9df8.gif)

## Attach a .c3p
[Construct Issues.zip](https://github.com/Scirra/Construct-3-bugs/files/2956480/Construct.Issues.zip)

## Steps to reproduce

1. Insert Sprite 
2. Add behavior Drag Drop to it
3. Add Touch plugin
4. Add Event On Touch 0 Start then set Sprite position to Touch.x and Touch .y
5. Now preview project click and drag anywhere in layout 

## Observed result

in Older version file if i click and drag anywhere on screen then sprite drags too but in recreating in latest version it doesn't drag. But it drags only when click over the sprite.
Please check and  preview both attached files.

## Expected result

Sprite should drag same as working in older version.

## More details

**Affected browsers/platforms:** 

** I didn't remember which older version i used for this file i tried to recreate working file with many older versions but i was unable to recreate working file till r125.  

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Your events contain a race between which object handles the touch event:

1) if the Touch plugin receives it first, it moves the object. Then the drag&drop behavior receives it, and sees the object under the mouse, so the drag works.
2) if the drag&drop behavior receives it first, it sees the object is NOT under the mouse so does not start a drag. Then the touch plugin receives it and moves the object.

Currently Construct doesn't make any guarantee about the order touch events fire in. Basically you shouldn't set up events to rely on such fine sequencing of operations. You should probably just do this all in events so you can control it properly.

**Comment by luckyrawatlucky** [comment]
then how its working in second file?

**Comment by AshleyScirra** [comment]
Undefined ordering means pretty much any ordering can be used, including a random order. I think in this case it's using an ordering based on the order things were added to the project.

**Comment by luckyrawatlucky** [comment]
Yes, You are right its using ordering based the order things were added to the project.
I deleted everything and first insert touch plugin and then sprite with drag and drop and now its working.

Thanks 
Today i learned something new.
