### ISSUE TITLE
Mouse Bug

### ISSUE THREAD

**Issue by DieppedalleDavid** [Scirra/Construct-3-bugs#2724]
description

The mouse coordinates are never updated if the mouse is not on the window!
Any version, including C2!

https://www.construct.net/out?u=http%3a%2f%2f%2f%2fwww.blackhornettechnologies.com%2fC3bugs%2fMouseBug.c3p

Normally the mouse coordinates should always be updated, even if the mouse is not on the window, but nothing happens if the mouse is not on the window, the events are still executed, but the mouse coordinates are not updated!

**Comment by AshleyScirra** [comment]
This is a privacy feature of browsers. Please note if you do not follow the bug report guidelines, your report will not be investigated.

**Comment by DieppedalleDavid** [comment]
What? What?
What is this joke, are you kidding me?

So how do we fix this problem?
