### ISSUE TITLE
Timeline - Intermittent crash when selecting the Play action

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2725]
## Problem description

Timeline crashes Construct when selecting the Play action.

## Attach a .c3p

https://www.dropbox.com/s/8v4dqrx97en6kvd/Timeline%20Play%20action%20Crashes%20Desktop%20Version.c3p?dl=0

## Steps to reproduce

1. Go to the event sheet
2. On event 1, add action for timeline
3a) Select 'Play' and press next 
3b) Double click on play

## Observed result

Intermittently will crash when selected either by mouse or by pressing next.

## Expected result

Add the action to the event sheet like every other action for objects.

## More details

**Affected browsers/platforms:**
Desktop
Chrome
Have not tested other platforms with this yet

**First affected release:** Unknown.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃrI (https://editor.construct.net/r141/main.js:2:119812) at Object.ǃNGY (https://editor.construct.net/r141/main.js:177:124083) at r.ǃNGY (https://editor.construct.net/r141/main.js:177:137252) at Object.ǃAg (https://editor.construct.net/r141/main.js:177:126803) at o (https://editor.construct.net/r141/main.js:177:142249) at t (https://editor.construct.net/r141/main.js:177:141650) at r (https://editor.construct.net/r141/main.js:177:141498) at https://editor.construct.net/r141/main.js:177:141554
Stack: TypeError: unexpected type at Function.ǃrI (https://editor.construct.net/r141/main.js:2:119812) at Object.ǃNGY (https://editor.construct.net/r141/main.js:177:124083) at r.ǃNGY (https://editor.construct.net/r141/main.js:177:137252) at Object.ǃAg (https://editor.construct.net/r141/main.js:177:126803) at o (https://editor.construct.net/r141/main.js:177:142249) at t (https://editor.construct.net/r141/main.js:177:141650) at r (https://editor.construct.net/r141/main.js:177:141498) at https://editor.construct.net/r141/main.js:177:141554
Construct 3 version: r141
URL: https://editor.construct.net/r141/
Date: Wed Mar 13 2019 00:34:43 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 433.8 s

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r141 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release.
