### ISSUE TITLE
R141 - Crash while re ordering the Z Order bar

### ISSUE THREAD

**Issue by justifun** [Scirra/Construct-3-bugs#2727]
## Problem description

C3 Crashed while re ordering a 9 patch object from the top of the z order bar to the bottom - undocked z order window - 

[crash.zip](https://github.com/Scirra/Construct-3-bugs/files/2957739/crash.zip)
## Steps to reproduce

Try to re order the 9 patch object to the bottom of the z order window while undocked.

## Observed result

Oops Something went wrong error while re ordering the z order bar from top to bottom

## Expected result

To re order object in z order bar without crashing

**Affected browsers/platforms:** 

R141 - Desktop C3

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r141/components/bars/zOrderBar/zOrderBar.js, line 1, col 17240
Message: Uncaught ReferenceError: ǃIZ is not defined
Stack: ReferenceError: ǃIZ is not defined at Object.ǃIv (https://editor.construct.net/r141/components/bars/zOrderBar/zOrderBar.js:1:17240) at Object.ǃHp (https://editor.construct.net/r141/components/bars/zOrderBar/zOrderBar.js:1:16908) at Object.ǃIP (https://editor.construct.net/r141/components/bars/zOrderBar/zOrderBar.js:1:11651) at Object.ǃJc (https://editor.construct.net/r141/components/bars/zOrderBar/zOrderBar.js:1:11051) at Array. (https://editor.construct.net/r141/components/bars/zOrderBar/zOrderBar.js:1:1099) at Object.ǃJxa (https://editor.construct.net/r141/main.js:2:211944) at Object.dispatchEvent (https://editor.construct.net/r141/main.js:2:209979) at Object.ǃrDH (https://editor.construct.net/r141/main.js:2:454253) at n.ǃVP (https://editor.construct.net/r141/main.js:2:462067) at HTMLDocument. (https://editor.construct.net/r141/main.js:2:457309)
Construct 3 version: r141
URL: https://editor.construct.net/r141/
Date: Tue Mar 12 2019 09:08:42 GMT-0700 (Pacific Daylight Time)
Uptime: 59866.1 s

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r141 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Already fix, will be available in the next beta release.
