### ISSUE TITLE
Wrong Tileset appear and one that should be invisble to the player

### ISSUE THREAD

**Issue by holywarrior756** [Scirra/Construct-3-bugs#2729]
## Problem description

i created a project that has two tipes of tile maps, one of colision (purple and invisible to the player) and the other with a art that can be seen, and for some kind of reason when i start the layout "Fase" , the visible tileset gets the image of the one with colision (purple one) not the image it was suppouse to have.

## Attach a .c3p

[Roguelike.zip](https://github.com/Scirra/Construct-3-bugs/files/2959257/Roguelike.zip)

## Steps to reproduce

1. run "Fase" layout
2. move with "w" "a" "s" "d"

## Observed result

some tilesets will have some image, an art, for some reason sometimes the tileset gets gets the image from other tileset, that i used to do the colision/solid part and should be invisible to the player

## Expected result

only the expected tileset should appear to the player and shouldn't get the image from another tileset

## More details
the error appeared when trying to reproduce an idea of procedural generation seen in the youtube channel "Marcos game dev" who is focused on giving tutorials about construct 2 and 3, on a playlist called "criando roguelike no construct 2 (ou 3)", most precisely on the videos 11, 12 and 13
11 ->https://youtu.be/2wGbakDfmhc
12 ->https://youtu.be/8KnJabC4-xE
13 ->https://youtu.be/jBJew2u5WIg

##Occured on chrome, windows 10

**Comment by AshleyScirra** [comment]
The provided project has over 70 events. Reports like this are usually just mistakes in events. Please see the bug report guidelines about providing a minimal project, to ensure you prove there is a problem in Construct rather than just the wrong events.
