### ISSUE TITLE
[r29.2] Copying an event from one C3 tab to another C3 tab crashes C3 if the event has an object the other project doesn't and instance vars attached

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#273]
## Problem description

I tried to reproduce that bloody cursor bug that I've attached zips for other bugs for. I copied from one c3 instance to another chrome tab with a c3 instance running. The event had an object attached to it which the second instance didn't have. This lead to the 2nd instance crashing.

## Attach a .c3p

Attached as .zip
[CrashFromCopyPaste.zip](https://github.com/Scirra/Construct-3-bugs/files/1013998/CrashFromCopyPaste.zip)

## Steps to reproduce

1. Open the project attached
2. Select like so
![image](https://cloud.githubusercontent.com/assets/7268697/26245896/12850026-3c9f-11e7-8dc6-be7c0c21310c.png)

3. Copy it, and paste it in a new C3 blank project running concurrently

## Observed result

C3 crashed
![image](https://cloud.githubusercontent.com/assets/7268697/26245677/de6ea1e4-3c9d-11e7-90a8-33e981768d2c.png)

I attached info in the view details

## Expected result

I expect to get an error stating what happened and not to crash. I think it could be because of the local variables.

## Affected browsers

* Chrome: yes/

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: missing object class in parameter
Stack: Error at Function.ǃC.ǃmWC (https://editor.construct.net/r29-2/main.js:2:226691) at te (https://editor.construct.net/r29-2/main.js:2:196051) at window.assert (https://editor.construct.net/r29-2/main.js:2:196475) at window.ǃmlH.ǃFy (https://editor.construct.net/r29-2/main.js:61:331918) at ee.ǃCAY (https://editor.construct.net/r29-2/main.js:61:291938) at Function.ǃmnV (https://editor.construct.net/r29-2/main.js:61:297294) at ee.ǃFy (https://editor.construct.net/r29-2/main.js:61:288246) at Function.ǃmni (https://editor.construct.net/r29-2/main.js:61:267831) at ee.ǃCAJ (https://editor.construct.net/r29-2/main.js:61:271753) at ee.ǃFy (https://editor.construct.net/r29-2/main.js:61:288266)
Construct 3 version: r29.2
URL: https://editor.construct.net/
Date: Fri May 19 2017 14:11:27 GMT+0300 (GTB Daylight Time)
Uptime: 775.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r30
