### ISSUE TITLE
r141.2 Sudden Crash by changing layout view

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#2730]
## Problem description

This issue occur suddenly when I'm switching layouts around. Can't figure what causes it. Sometimes moving a layer and undo will cause the exact same crash.

## Steps to reproduce

1. Switch layout view randomly.

## Observed result

crash even just changing layout view.

## Expected result

No crashes.

## More details

Its most likely have to do with the Z order's recent break. I will be stuck in an unusable version if the this bug persist.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r141-2/main.js, line 2, col 458014
Message: Uncaught TypeError: Cannot read property 'ǃtaj' of null
Stack: TypeError: Cannot read property 'ǃtaj' of null at i.ǃN (https://editor.construct.net/r141-2/main.js:2:458014) at Object.ǃgx (https://editor.construct.net/r141-2/components/bars/zOrderBar/zOrderBar.js:1:6846) at Object.ǃgh (https://editor.construct.net/r141-2/components/bars/zOrderBar/zOrderBar.js:1:5275) at Object.ǃJz (https://editor.construct.net/r141-2/components/bars/zOrderBar/zOrderBar.js:1:8130) at Array. (https://editor.construct.net/r141-2/components/bars/zOrderBar/zOrderBar.js:1:488) at Object.ǃJPA (https://editor.construct.net/r141-2/main.js:2:212102) at Object.dispatchEvent (https://editor.construct.net/r141-2/main.js:2:209970) at Object.ǃSw (https://editor.construct.net/r141-2/components/editors/layoutView/layoutView.js:1:48017) at Object.ǃIf (https://editor.construct.net/r141-2/components/editors/layoutView/layoutView.js:1:27489) at Object.ǃxp (https://editor.construct.net/r141-2/components/editors/layoutView/layoutView.js:1:27468)
Construct 3 version: r141.2
URL: https://editor.construct.net/r141-2/index.html
Date: Wed Mar 13 2019 14:47:35 GMT+0800 (Malaysia Time)
Uptime: 32.7 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.121
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
C3 release: r141.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed.

Indeed, this has to do with the recent changes to the Z Order Bar.

**Comment by Rewindedness** [comment]
> Fixed.
> 
> Indeed, this has to do with the recent changes to the Z Order Bar.

Ok so what do we have to do to fix it??
