### ISSUE TITLE
Function fails to read object count for first spawn

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2733]
## Problem description
Not sure if bug.
Having action, creating particle, calling function. Inside function i use particle.count, it fails to read it first time, but does it correct for all following particles. Using param to pass the particle count work just fine, but using particle.count causing this case: you call first time count=0, next time it's 2.
Same for c2runtime.

## Attach a .c3p

[FuncReadCountBug.zip](https://github.com/Scirra/Construct-3-bugs/files/2963376/FuncReadCountBug.zip)

## Steps to reproduce

1.Start example
2.Preview
3.Click green box, first there are values 0,1. Click Green box again there is 2,2. 

## Observed result
First object create won't pass value. When i use On start of layout and create particle it updates value same tick, but destroy seems to update value at end of events. From here it should update function value to.

## Expected result
Not sure what, maybe should work like this, it just need checking out.
I don't remember coming across this issue before or when i think i know something i don't know anything.

## More details

**Affected browsers/platforms:** 

**First affected release:** 
Same in c2runtime.
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.121
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
C3 release: r141.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 791 mb (5.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a variant of "created objects don't really exist until the end of the next top-level event".

When the first 'Particles' object is created it's not fully created until the next top-level event; like with sibling sub-events, calling in to a function that uses it means it can't access the newly created instance yet, because it hasn't finished creation. In this case the calling event can use the instance picked by 'Create object', but the first function call considers there to be no instances, so all expressions return 0.  Subsequent calls can at least find previously created instances to call the count expression on, so this only happens the first time.

It's a difficult corner case in the engine. I don't think it's feasible to fix - at least not without adding more overhead to every expression in the entire event engine.

**Comment by SnipG** [comment]
Ty for your explanation. Ye, it should remain as a quirk

Linking other similar issue here that i found,  so users can find it easier and workaround it, if needed. 
#1149
"Note in C3 you can work around it with the "pick last created" condition to still be able to pick it in an immediately following sub-event."
So one can use "pick last created" inside function, if needed.
