### ISSUE TITLE
Drawing Canvas - Can't draw polygon that intersect itself.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2737]
## Problem description

When drawing a polygon in the canvas. If the lines between the points intersect it doesn't draw the polygon.

## Attach a .c3p

https://www.dropbox.com/s/iabze56hjvrboyo/Curve2_test.c3p?dl=1

## Steps to reproduce

1. Open attached c3p and press preview.
2. When the points creates a polygon that intersects it does not draw.

## Observed result

Can't draw polygon that intersects itself.

## Expected result

It's crucial for a project I'm doing that the polygon can draw even if it intersects itself. When intersecting the shape should look like hourglass or 2 triangles on top of eachother.

**First affected release:** 

I don't think this has ever worked.

**Comment by shortercode** [comment]
Going to assign to @AshleyScirra. I believe we don't have any systems for doing triangularization of concave polygons in the runtime at the moment, it's very complex compared to convex.

**Comment by tunepunk** [comment]
Thanks. This is the kind of shapes I'm looking for. 
![image](https://user-images.githubusercontent.com/27011641/54428542-1d704a00-471e-11e9-82ca-6b06a6c4e90a.png)

**Comment by AshleyScirra** [comment]
This is [noted in the manual](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/drawing-canvas):

> This action supports both convex and concave polygons, but not self-intersecting polygons.

Please file this as a feature request if it's something you want to be supported.

**Comment by tunepunk** [comment]
Filed as a request here.

https://construct3.ideas.aha.io/ideas/C3-I-794
