### ISSUE TITLE
OR block condition not working

### ISSUE THREAD

**Issue by DieppedalleDavid** [Scirra/Construct-3-bugs#2739]
## Problem description

The third condition (Or) is ignored.

+ Mouse: When the left button is clicked.
----+ Mouse: The cursor is over the Reduce Button.
----+ OR Mouse: The cursor is over the Enlarge Button.
----+ OR Mouse: The cursor is over the Close Button.
-----> TitleBar: Set Drag&Drop as Off.

If I change the order, condition 3 is always ignored.

## Attach a .c3p

https://drive.google.com/open?id=1a1PHjx95oYlS8oKugMIsGMFapBOBit4Q

## Steps to reproduce

How in the example.

+ Mouse: When you click the left button

----+ Mouse: The cursor is over OBJECT
-----+ OR Mouse: The cursor is over OBJECT
-----+ OR Mouse: The cursor is over OBJECT
-----> Do...

## Observed result

Only condition 1 + 2 is taken into account, not condition 3.

## Expected result

If one of the conditions is true, then the action must be taken.

**Comment by AshleyScirra** [comment]
Minimal repro: [or-block-click-minimal.zip](https://github.com/Scirra/Construct-3-bugs/files/2977726/or-block-click-minimal.zip)
Looks like it's related to containers - if you remove the buttons from a container it works correctly.
It also works correctly if you use three "On object clicked" triggers in an OR block. The sub-event with "Is mouse over object" is redundant, so there is an easy way to work around this.

**Comment by DieppedalleDavid** [comment]
It also works correctly if you use three "On object clicked" triggers in an "OR" block.
Exactly, but it's still a bug ^^

**Comment by AshleyScirra** [comment]
Finally figured this out, should be fixed in the next release.
