### ISSUE TITLE
Exported game with ShadowLight doesn't work

### ISSUE THREAD

**Issue by DiscoFishGames** [Scirra/Construct-3-bugs#274]
## Problem description

Exported game with ShadowLight object doesn't work (red progress bar). Also error message when Remote preview. If I remove ShadowLight than exported game work fine.

## Attach a .c3p
[ShadowLight.zip](https://github.com/Scirra/Construct-3-bugs/files/1013986/ShadowLight.zip)

## Steps to reproduce

1. Add ShadowLight
2. Export game with Web or Desktop

## Observed result

![image](https://cloud.githubusercontent.com/assets/28790727/26245756/4e88304e-3c9e-11e7-8fee-d32a1733f18a.png)
![image](https://cloud.githubusercontent.com/assets/28790727/26245777/6daf623a-3c9e-11e7-94e8-943e4c36fc38.png)

## Expected result

Working exported project with ShadowLight

## Affected browsers

* Chrome: yes

## System details

Tested on r28 and r29.
Asus Zenbook UX31E
Win 10

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r30.
