### ISSUE TITLE
Mac Chrome pwa desktop creates multiple previews

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#2740]
C3 version: r136 Stable
Browser: Chrome 73
OS: macOS Mojave
Running preview to the Chrome browser creates a second tab of the preview that never gets loaded.
This happens on the second launch of the browser preview.
Subsequent launches do the same.

**Comment by AshleyScirra** [comment]
Can't reproduce. Reports like this are generally useless, please always follow the bug report guidelines, they're there to avoid this happening.
