### ISSUE TITLE
Loader style switches to "C3 Splash screen" after loading the project from cloud

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#2742]
## Problem description

The loader style switches to C3 Splash Screen after loading proejct from cloud

## Attach a .c3p

No needed.

## Steps to reproduce

1. Set the loader style to "percentage text" in project settings,
2. save the project to cloud (google drive),
3. load the proejct and go back to project settings.. You should see the loader switched to C3 splash screen.

## Observed result

Switches.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here, works fine. Note if you're using the free edition you are only allowed to use the splash mode.
