### ISSUE TITLE
IOS MobileAds Plugin

### ISSUE THREAD

**Issue by yeaaqbi** [Scirra/Construct-3-bugs#2744]
## Problem description
I have a game that uses the MobileAds plugin, when exporting the project XCODE with the plugin it fails to compile, but if exporting it without the plugin it works fine.
## Attach a .c3p
size > 10mb

## Steps to reproduce
- Export the project as XCode project with the Ads plugin.
- Run the game on Xcode fails to compile due to the attached image errors
![Screen Shot 2019-03-18 at 3 44 02 PM](https://user-images.githubusercontent.com/3922086/54535004-426ef200-4996-11e9-8465-d6744631d7d6.jpg)
## Observed result

Fails to compile the project

## Expected result

It should work without failing in compilation at least.

## More details
It compiles without the plugin

**Affected browsers/platforms:**

can not detect since it fails in . combilation

**First affected release:** 

R 142 -- since I have waited this stable one to see if it is resolved, it has begun with the stable release before this one I don not remember its number may be it is R 133
## System details
MAC OS

**Comment by AshleyScirra** [comment]
Please attach a minimal project demonstrating the problem as per the guidelines.

**Comment by yeaaqbi** [comment]
@AshleyScirra sure I will add a simple project with the same problem now with the plugin

**Comment by yeaaqbi** [comment]
@AshleyScirra I have tested it on another empty project it works fine, I need to check again what happens with my project. Thanks a lot
