### ISSUE TITLE
Touch.TouchID returns zero

### ISSUE THREAD

**Issue by AnttiTam** [Scirra/Construct-3-bugs#2747]
## Problem description

Touch.TouchID returns zero every single time.

## Attach a .c3p

[touchID problem.zip](https://github.com/Scirra/Construct-3-bugs/files/2978990/touchID.problem.zip)

## Steps to reproduce

1. Run project.
2. Click anywhere.
3. Touch ID stays zero (as evident by the text object)

## Observed result

TouchID is always zero

## Expected result

Like the manual says, i'm expecting an "arbitrary number" on every different touch

## More details
Tested browsers: Chrome, Edge, Firefox

**Comment by AshleyScirra** [comment]
0 is an arbitrary number. The only guarantee about the touch ID is that it is different to all simultaneous touches.
