### ISSUE TITLE
Dekstop Beta version: whenver we're on a stable release, C3 asks you to update to stable but then it reverts back to beta

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2748]
## Problem description

I'm on the latest Desktop Beta build.

When I start C3 it asks you to update, this normally works great!

However, when we're up to a Stable build, I say sure and update to the latest.

But then I close the program and open it up later, and it asks again! It won't stop asking you to update every single day until we finally get to the next beta release. No matter which option you select!

![image](https://user-images.githubusercontent.com/5744908/54580361-dbb40c00-4a5b-11e9-95de-a9de31c1a733.png)

This has been happening for a long time.

I think it does actually update afterwards:

![image](https://user-images.githubusercontent.com/5744908/54580436-2a61a600-4a5c-11e9-8011-8dcb4a481fc7.png)

But then if I close the program, open it again, it asks to update to 142, I click "not now", then check the version number:

![image](https://user-images.githubusercontent.com/5744908/54580467-55e49080-4a5c-11e9-99b1-ee04e70bde42.png)

This seems to indicate that it reverts back to the previous Beta build every time, which is why I have to install the stable build every day while it's the newest build.

## Steps to reproduce

1. open C3

## Observed result

stable release doesn't stay installed

## Expected result

releases shouldn't revert without consent

## More details

**Affected browsers/platforms:** 

desktop beta

**First affected release:** 

r1

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r141.3 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 125 gb
Storage usage (approx): 897 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by LukeNecklace** [comment]
This might be a bug to report but have you tried to change your settings to "Notify me about..." stable releases after you press update on the pop up, then close your program and open it again, and it should be on r142?

I did not have this problem you experienced, it just updated me to 142 but I immediately changed my settings to stable releases only and after doing some work on my projects and then seeing this issue, I checked it and it did tell me I was on r142. I did try to replicate this issue myself but my circumstances may have been different to yours. Try that combination as a work around anyway and see if that fixes the issue for you.

**Comment by AshleyScirra** [comment]
The beta desktop download points at editor.construct.net/beta, which is only redirecting to the latest beta release (r141.3). I filed a website issue https://github.com/Scirra/Construct.net-website-bugs/issues/80 for that, so closing this issue. The workaround is super simple, just click "update" after launching.
