### ISSUE TITLE
Tween behaviour freezes and causes lag if it stops and starts a lot

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2749]
## Problem description

Tween behaviour causes freezing of the preview if it stops its tag and then starts again. Can also cause lag.

## Attach a .c3p

https://www.dropbox.com/s/2gmqhegsvvdbiyh/Destroying%20and%20stopping%20a%20tween%20freezes%20the%20preview.c3p?dl=0

## Steps to reproduce

1a. Change the direction of the TweenSprite by pressing 2 and 1.
1b. Move the Target1 and 2 sprites using the keyboard away from the incoming TweenSprite
2. Wait for the tween sprite to collide with Target1 or Target2 sprites.

## Observed result

Preview freezes.
In some cases this causes massive lag with construct if the preview is left open in this state.

## Expected result

The TweenSprite should just destroy without freezing the preview or causing lag.

## More details
Any combination of events that causes the tween to stop and start a lot can also cause this issue.

**Affected browsers/platforms:** 
Desktop
Chrome

**First affected release:** 
Currently r142 - Unknown if this occurs in previous releases.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.121
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
C3 release: r142 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 94 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release.
