### ISSUE TITLE
Select many frames would be great

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#275]
## Problem description

This is not a bug, but it would be great to allow us to select all the frames with SHIFT or CTRL + clics in the Animations Editor.
(exemple : if we have 30 frames and we want to delete 15 frames quickly, or we want to reverse 15 frames etc...)

**Comment by AshleyScirra** [comment]
I'm closing all issues here which are suggestions not already in C2. We want to focus on bugs only in this tracker, or minor TODOs. For new features please write up suggestions at: https://construct3.ideas.aha.io/
