### ISSUE TITLE
Touch: zooming Example project does not work on Safari Browser (iOS)

### ISSUE THREAD

**Issue by MuriloBeraldo** [Scirra/Construct-3-bugs#2750]
## Problem description

The example project "Touch: zooming" available on http://editor.construct on the Templates section does not work properly when exporting to HTML or remote previewing on iPhones using Safari browser.

This issue has already been addressed in the link below, but seems like the solution no longer works (notice that the project already has the mentioned changes).

https://github.com/Scirra/Construct-3-bugs/issues/1698

Thank you in advance

## Attach a .c3p

https://editor.construct.net/#open=touch-zooming

## Steps to reproduce

1. Open the project;
2. Start a Remote Preview;
3. Scan the QR code or copy the link on an iPhone;
4. Zoom in and out a couple times;
5. Notice that the screen goes blank and the only solution is to close the preview.

## Observed result

The screen goes blank after zooming in and out a couple times.

## Expected result

The zooming function should work no matter how many times the user zooms in and out.

## More details

**Affected browsers/platforms:** 
Safari/Iphone

**First affected release:** Construct 3 r136, but already tried on the most recent release (r142) 

## System details

Testing on various Iphones using Safari browser

**Comment by AshleyScirra** [comment]
It looks like it works fine for the first few touches, then eventually freezes. I assume it crashed, but (typically) Safari's debugger crashes at this point, so doesn't provide any useful information.

I suspect this is a Safari bug but it's hard to tell without better diagnostics, and I'm not sure what else we could do right now... maybe the next Safari update will fix it...

**Comment by MuriloBeraldo** [comment]
I see...well that's a bummer...but thanks anyway for the quick response!

I assume it will work on a app build instead of HTML export then? I didn't get the chance to try it.

**Comment by damjancd** [comment]
> I see...well that's a bummer...but thanks anyway for the quick response!
> 
> I assume it will work on a app build instead of HTML export then? I didn't get the chance to try it.

I'm curious too if it's going to work on export. Anyone knows?

**Comment by dop2000** [comment]
Can it be related to this bug, where touchID gets _stuck_ and "On touch end" event is never triggered?
https://github.com/Scirra/Construct-3-bugs/issues/1639

**Comment by sjrya** [comment]
Hi, 

 Is there any update on this situation? I believe it could be effecting me also. 

I have an on-screen joystick that uses touchID, on touch, on touch end. 

It works fine on Android but about 20% of sessions on IOS it is completely unresponsive. It's very frustrating as I can't seem to identify what makes it work on some sessions but not others. 

I can submit a separate bug if you think this is something different. 

Thanks

**Comment by AshleyScirra** [comment]
If anyone has an iOS device running the iOS 13 beta, it would be worth trying this out again. Safari 13+ supports pointer events, which is a new API to replace the old touch events API, which seem to be causing Safari to crash in this example. The runtime automatically uses pointer events if it detects they're supported so it might work around Safari crashing with touch events.

**Comment by damjancd** [comment]
@AshleyScirra  It works! Tried my darnest to break it but it wouldn't break. iOS13 with an iPhone X fresh install. AWASEOME!

**Comment by AshleyScirra** [comment]
Good to hear - however given the near impossibility of debugging this in Safari 12, and the high likelihood it's a Safari crash we can't directly do anything about anyway, closing this issue. Basically it's fixed in Safari 13+.
