### ISSUE TITLE
8 Direction max speed value can be exceeded

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2756]
## Problem description

I was working on my analog stick movement template when i realized that the player with the 8 direction behaviour was not respecting the max speed value. As you can see in this .gif i could reach almost 300 pixel per second even if limit estabilished was 256 pixels per second.
https://i.imgur.com/KCjOtdi.gif

## Attach a .c3p

[Speed Test.zip](https://github.com/Scirra/Construct-3-bugs/files/2993743/Speed.Test.zip)

## Steps to reproduce

1. Open the project.
2. Run in a diagonal direction.

## Observed result

The player is not respecting the max speed value.

## Expected result

The player to only move in 256 pixel per second.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release. Note with the fix it still occasionally flickers the "above speed" warning, but that is due to floating point rounding errors, with the fix it stays very close to the max speed.

**Comment by BonzerKitten7** [comment]
Thanks a lot for the quick fix, Ashley. Would you mind about explaining what was causing this issue? I tried to replicate it in another project, but it started to respect the max speed value and I don't know why.

**Comment by AshleyScirra** [comment]
In 8 direction setting the vector X/Y components directly did not clamp to the max speed.
