### ISSUE TITLE
TileMovement's TargetX/Y is specified in pixels instead of grid cells.

### ISSUE THREAD

**Issue by ffdd** [Scirra/Construct-3-bugs#2758]
## Problem description

TileMovement TargetX/Y is specified in pixels, not grid cells, as described in the documentation. Please see the screenshot instead of a .c3p

## Attach a .c3p

https://imgur.com/a/bKrPldm

**Affected browsers/platforms:** Chrome/macOS (Probably all)

**First affected release:** r142.2

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.75
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 166 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Fixing this would be a breaking change. It might be better to update the documentation and add a separate expression if necessary.

**Comment by shortercode** [comment]
Yeah I don't think changing the behaviour is the correct fix, the only places we use the terminology `Target[X|Y]` are the expression and the debugger, and they both return the same values. Also I think the naming is consistent with the values, but obviously there was some confusion in the descriptions.

I will update the ACES description and the documentation so that it matches what it's actually doing. Considering how users could get the target in grid co-ordinates; calculating it is somewhat awkward in events and we already have it internally so I'm going to add 2 new expressions that just return the internal value.

**Comment by shortercode** [comment]
Okay above changes should be in the next release. I've updated the documentation already as it was technically incorrect, but conflicts with what the expression dictionary says.
