### ISSUE TITLE
ID of a button changes when button is disabled

### ISSUE THREAD

**Issue by dasMarts** [Scirra/Construct-3-bugs#2759]
## Problem description
When you change the id of a button (via Browser -> Execute JavaScript action) everything works fine. But if the button is disabled, the old (initial) id of the button is restored (and that should **not** happen).
**EDIT:** The bug is also triggered when you change the button's text or the tooltip.

## Attach a .c3p
https://drive.google.com/open?id=13fyX1Mw-VxHEQiIrleKJPqsUpAK6MvP8

## Steps to reproduce

1. Wait 1 second, the id of the of the button will automatically change from "falseId" to "rightId"
2. Click the button in order to set it disabled

## Observed result

You will see how the id of the button changes to "falseId" although no such action was triggered
## Expected result

The button should have been disabled without its id changing at all
## More details

**Affected browsers/platforms:** 
Chrome and Windows

**Side note:** 
I didn't want to start a new topic for this but... why can't we add classes to buttons in the editor if we can add id's? I wouldn't have had to do the steps that reproduce this bug if this feature was available.

**Comment by AshleyScirra** [comment]
Fixed for next release, but the fundamental problem is if you execute JavaScript strings you can end up conflicting with the internal state of the plugin. You should use the plugin actions where possible.
