### ISSUE TITLE
Sometimes "Apply to whole animation" doesn't work properly

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#276]
## Problem description
Sometimes the "Apply to whole animation" (Origin Point option in the Animations Editor) just work for 1 or 2 frames.

## Steps to reproduce

1. Move an Origin Point on a serie of Frames.
2. Click on the image point in th list and Apply to whole animation

## Observed result

Sometimes It apply it just to 1 frames (or 2 or 3 sometimes)
Sorry, I cannot reproduce the bug. It appears sometimes.

## Expected result

Apply to all the frames.

## Affected browsers

* Chrome: yes/

**Comment by DiegoScirra** [comment]
Fixed in r52. Took a while.
