### ISSUE TITLE
Missing translation of Timeline Bar

### ISSUE THREAD

**Issue by DavidCB14** [Scirra/Construct-3-bugs#2760]
## Problem description

In the view menu > bars you can see the Timeline bar is not translated
The string is not in Poeditor to be translated

## Attach a .c3p

No example needed

## Steps to reproduce
Go to menu > View > Bars (In a language other than English)

## Expected result

In Spanish => Barra de Línea de tiempo instead [Timeline Bar]

## More details

![timeline_bar](https://user-images.githubusercontent.com/11505355/54823158-3db48180-4ca7-11e9-9741-d05c5289f7bd.png)

**Comment by AshleyScirra** [comment]
This is a known issue; we're holding off adding the timeline terms to POEditor until it's enabled by default, which hopefully will be soon.
