### ISSUE TITLE
crash - z-order bar when using ctrl + z (undo)

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-3-bugs#2763]
## Problem description

Reordering objects to different layers using the z-order bar and then pressing ctrl+z caused crash

## Attach a .c3p

[undo z order test.zip](https://github.com/Scirra/Construct-3-bugs/files/2998880/undo.z.order.test.zip)

## Steps to reproduce

1. select s3
2. in z order bar, drag to layer 0
3. deselect s3
4. press ctrl+z on keyboard to trigger crash

## Observed result

program crashes

## Expected result

not to crash

## More details

Win 10
stable channel 142.2
Chrome

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected HTML element @ TypeError: expected HTML element at Function.ǃei (https://editor.construct.net/r142-3/main.js:2:121025) at Function.ǃimN (https://editor.construct.net/r142-3/main.js:2:271794) at d.ǃJL (https://editor.construct.net/r142-3/main.js:2:467946) at Object.ǃrh (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:17105) at Object.ǃMR (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:16846) at Object.ǃdN (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:14956) at Array. (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:756) at Object.ǃiGL (https://editor.construct.net/r142-3/main.js:2:212166) at Object.dispatchEvent (https://editor.construct.net/r142-3/main.js:2:210034) at Object.ǃJmT (https://editor.construct.net/r142-3/main.js:177:648704)
Stack: TypeError: expected HTML element at Function.ǃei (https://editor.construct.net/r142-3/main.js:2:121025) at Function.ǃimN (https://editor.construct.net/r142-3/main.js:2:271794) at d.ǃJL (https://editor.construct.net/r142-3/main.js:2:467946) at Object.ǃrh (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:17105) at Object.ǃMR (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:16846) at Object.ǃdN (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:14956) at Array. (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:756) at Object.ǃiGL (https://editor.construct.net/r142-3/main.js:2:212166) at Object.dispatchEvent (https://editor.construct.net/r142-3/main.js:2:210034) at Object.ǃJmT (https://editor.construct.net/r142-3/main.js:177:648704)
Construct 3 version: r142.2
URL: https://editor.construct.net/r142-3/index.html
Date: Sat Mar 23 2019 12:17:25 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 59 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.121
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta release.
