### ISSUE TITLE
Timeline - crashing when trying to add an instance with instance variable

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#2764]
## Problem description

Program crashes when I'm trying to add a sprite instance with instance variable to the timeline.

## Attach a .c3p

https://www.dropbox.com/s/cxr49mdeast3yh9/timeline_test.c3p?dl=0

## Steps to reproduce

1. Open the project
2. Try to add sprite instance onto the timeline

## Observed result

Crash

## Expected result

Instance added to timeline.

## More details

Seems to happen only when there are instance variables added to the object.

**Affected browsers/platforms:** 

Chrome
Desktop build

**First affected release:** 
r142.2

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: ǃdLm is not defined @ ReferenceError: ǃdLm is not defined at t.ǃdLE (https://editor.construct.net/r142-3/main.js:81:467692) at t.ǃdLx (https://editor.construct.net/r142-3/main.js:81:468123) at t.ǃdvo (https://editor.construct.net/r142-3/main.js:81:466616) at t.ǃdBu (https://editor.construct.net/r142-3/main.js:81:464448) at new t (https://editor.construct.net/r142-3/main.js:81:458356) at Function.ǃJ.ǃl (https://editor.construct.net/r142-3/main.js:2:151597) at t.ǃdvv (https://editor.construct.net/r142-3/main.js:81:441048) at t.ǃaS (https://editor.construct.net/r142-3/main.js:81:441200) at https://editor.construct.net/r142-3/components/bars/timelineBar/timelineBar.js:1:10780
Stack: ReferenceError: ǃdLm is not defined at t.ǃdLE (https://editor.construct.net/r142-3/main.js:81:467692) at t.ǃdLx (https://editor.construct.net/r142-3/main.js:81:468123) at t.ǃdvo (https://editor.construct.net/r142-3/main.js:81:466616) at t.ǃdBu (https://editor.construct.net/r142-3/main.js:81:464448) at new t (https://editor.construct.net/r142-3/main.js:81:458356) at Function.ǃJ.ǃl (https://editor.construct.net/r142-3/main.js:2:151597) at t.ǃdvv (https://editor.construct.net/r142-3/main.js:81:441048) at t.ǃaS (https://editor.construct.net/r142-3/main.js:81:441200) at https://editor.construct.net/r142-3/components/bars/timelineBar/timelineBar.js:1:10780
Construct 3 version: r142.2
URL: https://editor.construct.net/
Date: Sat Mar 23 2019 23:45:57 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 153.5 s

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced
</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta release.
