### ISSUE TITLE
Mobile Banner Advs Not Showing

### ISSUE THREAD

**Issue by yeaaqbi** [Scirra/Construct-3-bugs#2767]
## Problem description

Mobile Banner not showing on Android device

## Attach a .c3p
https://drive.google.com/file/d/1wh6PopWR7v4vQORtvsnHSgxW3Os4m-zQ/view?usp=sharing

## Steps to reproduce

1. Build singed APK with the Ads plugin
2. Open the app, there is no banner ads shown

## Observed result

The banner ads not shown anymore, they shown for 1 day then they disappeared.

## Expected result

The banner should be shown since the other ads types are working fine.

## More details
There is no emails from google side.
The banner ads shown in the first day, but when I have reached around 5k installs the banner ads disappears, I tried so many ways and dimple projects to show them without success.
## Browser:
Chrome 

**First affected release:** 
C3 latest stable release

Attached the image for debugging the android app

**Comment by shortercode** [comment]
Have you checked to see if they are still giving you adverts? Admob doesn't guarantee to give you an advert when you request one.

**Comment by yeaaqbi** [comment]
@shortercode sorry can not understand "Admob doesn't guarantee to give you an advert when you request one" ?

**Comment by shortercode** [comment]
When you ask to load an advert, the **Mobile Advert** plugin _requests_ an advert from Admob. Normally they send you an advert to show. But they sometimes do not send you an advert. There are many reasons for this. I advise people using the plugin to allow for this when creating games. The plugin includes conditions that allow you to tell if the advert request was successful.
