### ISSUE TITLE
Duplicating 2 sprites without deselect

### ISSUE THREAD

**Issue by Mak14** [Scirra/Construct-3-bugs#2771]
## Problem description

Hi Scirra team! I don't know if this a feature or a bug, but deselecting an object to duplicate the other object on the scene is not so productive. 
For me the problem is when i'm working with 2 objects and instant drag unselected sprite without release of the mouse button ( tablet pen). 

C2 worked fine in that case.
Please see below

vvv

## Steps to reproduce

1. Create any 2 sprite objects on the scene
2. Click on one of the objects
3. Hold down Ctrl and Drag the OTHER object

## Observed result

It will clone both objects. 

## Expected result
Clone the last selected object and auto deselect previously selected sprite.

## More details
You can try to do the same in C2.
In C2 it works as expected result and it's perfect. 
It's difficult and unproductive to deselect an object each time i need duplicate the other object.
Especially on crowded scenes.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release.
