### ISSUE TITLE
Crash iOS 12.1.4 on Wifi

### ISSUE THREAD

**Issue by QkyGames** [Scirra/Construct-3-bugs#2773]
AppStore reject my app.
The Game crash on iOS 12.1.4 on wifi when try to purchase a non-consumible iap.

## Attach a .c3p

https://www.dropbox.com/s/l7mg1eix94ckhtr/IAP%20Test.c3p?dl=0

## Steps to reproduce

1. Touch in No Ads button

## Observed result

Game Crash

## Expected result

Purchase the IAP.

## More details

**Affected browsers/platforms:**  iOS 12.1.4
**First affected release:** 142

**Comment by AshleyScirra** [comment]
The provided project uses a third-party addon (Lite tween). Please provide a minimal project that does not use any third-party addons as per the bug report requirements.

**Comment by QkyGames** [comment]
Sorry for this problem, please download the new file here:

https://www.dropbox.com/s/0mdfa49q9l8bevs/IAP%20Test%20Update.c3p?dl=0

**Comment by shortercode** [comment]
@QkyGames could you let me know what your mean by crash? Does the application close or freeze?

**Comment by QkyGames** [comment]
I have not iOS 12.1.4 but I have this info from AppStore:

Application Specific Information:
abort() called

you can download the crash log here:
https://www.dropbox.com/s/b1q5es66o4qhq8g/crashlog-DFA26B92-5B5E-41AF-936C-3AE6BC8A7AD7.txt?dl=0

**Comment by QkyGames** [comment]
new news about this? I release my game without IAP

**Comment by AshleyScirra** [comment]
@QkyGames - it's extremely difficult to help with issues reported like this. Please see the bug report guidelines for information on how to file issues that we are more easily able to investigate.

**Comment by shortercode** [comment]
@QkyGames the links to your examples and crash reports are dead, could you upload the files to GitHub instead so that you don't have to host them? I appreciate it's been a little while since the issue was filed but I am trying to investigate the issue now.

**Comment by AshleyScirra** [comment]
3 weeks with no response so closing
