### ISSUE TITLE
Debug mode fails, then editor window fails automatically

### ISSUE THREAD

**Issue by Graham-s** [Scirra/Construct-3-bugs#2774]
## Problem description

Debug mode is non responsive and crashes.
A minimal project cannot be created to reproduce, however the issue can reproduce with the attached project every time.
I suspect it is multiplayer related, but I don't anticipate a complete failure as it occurs.
## Attach a .c3p

https://www.dropbox.com/s/rt4wo65q5xjx9d3/GRIFT-HOCK-SPACE_BETA-E_3-23-19-2221_2.c3p?dl=0

## Steps to reproduce

1. Run the project in DEBUG mode on layout main menu, select either Single or Multiplayer game
2. Project will start and partially display the screen then stop
3. Press PAUSE then PLAY and things will move, then it will stop again
4. A few moments later the debug window will automatically close on error
5. The C3 editor window will also automatically close on error resulting in project loss.

## Observed result

Debug freezes and then the Chrome window and editor windows fail
## Expected result

Debug to work as it usually does.
## More details

Tested on Chrome and FFox.
**Affected browsers/platforms:** 

Only discovered on the latest version but never tried it on earlier ones. (142.2)
**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 65.0
Browser engine: Gecko
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0
C3 release: r142.2 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 610 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    ImageBitmap support is disabled in Firefox due to bug 1472194
    CSS containment is not supported. Editor performance may be significantly degraded.
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmap is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 460 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

    EXT_color_buffer_float
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The problem is you have circular event sheet includes: "evt Main Game" includes "evt Player Control", which also includes "evt Main Game". The crash in the debugger is fixed for the next release, but you can also work around it by not using circular includes.
