### ISSUE TITLE
Moving objects moving through walls

### ISSUE THREAD

**Issue by Link64U** [Scirra/Construct-3-bugs#2775]
## Problem description

The enemies in my game will sometimes slide ride through the walls. Obviously, I don't want that.

## Attach a .c3p

[The Dark Temple.zip](https://github.com/Scirra/Construct-3-bugs/files/3010149/The.Dark.Temple.zip)

## Steps to reproduce

1. Load any scene with enemies in them. It will be easier to observe the issue in small areas, and happens often with the spider enemies.
2. Observe the enemy's movements. It can sometimes take a while before they finally slide through the walls.

## Observed result

The enemy slides through the walls, or begins sliding through them then gets pushed back.

## Expected result

Obviously, they aren't supposed to go through the walls.

## More details

The enemies use the Custom movement behavior to move around. Their angle of movement changes at random intervals. The walls are repeated backgrounds with the Solid behavior enabled. The walls and enemies are on different layers, though I have putting the enemies on other layers and the issue still remained.

**Affected browsers/platforms:**

The issue was witnessed on Chrome and Safari, on the most recent macOS update and Windows 10. It was not tested on other browsers or platforms.

**Comment by AshleyScirra** [comment]
This project has 168 events. The problem is likely just a mistake in your events. Please see the bug report requirements regarding providing a minimal project to prove the problem is with Construct and not a mistake in your events.
