### ISSUE TITLE
Large text objects not rendered on android phone

### ISSUE THREAD

**Issue by Boulerzzz** [Scirra/Construct-3-bugs#2777]
## Problem description

Large text objects are not rendered. Limit seems to be around 200x200.

Small text objects are shown just fine. But once the object is larger it wont be shown. Before I had no problem with this. I noticed it when I updated an existing project and noticed all large text objects was gone after export.

## Attach a .c3p

[TEST (1).zip](https://github.com/Scirra/Construct-3-bugs/files/3012292/TEST.1.zip)

## Steps to reproduce

1. Export project using android and C3 build service to create an APK
2. Run APK on android phone

## Observed result

The large text object in the middle is not rendered. The small one at the top corner is.

## Expected result

All text to be rendered.

## More details
I'm testing on a Honor Phone with Mali GPU

Both FBIG and Android export seems to produce this issue for me

Problem began a few weeks ago. Same project could be exported before without issue but now large text objects wont be shown

Have not tested on other phones so could be an issue with my phone only.

Also the admob consent form has the same issue. It wont be shown. It's there, because I can press the buttons. But all I can see is a white screen. But if I put the app in the background and reopens it a minute later the consent form is shown.

**Comment by AshleyScirra** [comment]
Can't reproduce here, it looks fine on a Pixel 3 both with Remote Preview and built as a debug APK. You did not include your system information - please make sure you are using the latest release of Construct 3. I would assume you are using an old version and this is a bug we have already fixed. Otherwise I'm afraid there is nothing we can do unless we can reproduce the problem.

**Comment by Boulerzzz** [comment]
Okok. I tried both latest stable and 136.
The project was so small I just used c2 runtime instead (which has no problem with text objects) so no problem.

And in C3 runtime I guess I'll have to use small text objects or just Sprite font.
