### ISSUE TITLE
Status bar visible on iPhone 7 & 8 when exporting a project with C2 + C3 export manager

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#2778]
## Problem description

When exporting a C2 game with Cordova, then using C3's export manager to create an iOS app, the status bar is visible on iPhone 7 & 8, even though I checked the option to hide status bar in both Construct 2 and Xcode.

## Attach a .c3p

[statusBarTest.zip](https://github.com/Scirra/Construct-3-bugs/files/3013200/statusBarTest.zip)
A blank project could also do the job. Also, this is a capx, as the problem is in the export manager of C3 when exporting a C2 project.

## Steps to reproduce

1. Export any C2 project with Cordova.
2. In the export options, check "Hide status bar"
3. Create a zip file with the resulting files
4. Open C3's export manager and select the zip file you juste created
5. Click Build application
6. Copy the exported file on a Mac
7. Launch Xcode and open the .xcworkspace file located inside the iOS folder
8. Check "Hide status Bar" in Xcode.
9. Select iPhone 7 or iPhone 8 on top of the screen and launch the simulator.
10. The status bar is still visible.

## Observed result

The status bar is visible.

## Expected result

The status bar should not be visible.

## More details
On iPhone X the Status bar is correctly hidden.
When exporting a C3 project, the status bar is also correctly hidden, even on iPhone 7 & 8. 
The problem only arises with C2 + C3 export manager on iPhone 7 & 8.

**Affected browsers/platforms:** 

Last version of Xcode. 
C2 r265
C3 r141

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.7 gb
Storage usage (approx): 5.3 gb (68.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
C2's Cordova export uses an older approach to this - it includes `cordova-plugin-statusbar` and `cordova-custom-config`, and sets the following config.xml tags;

```
<config-file parent="UIStatusBarHidden" platform="ios" target="*-Info.plist"><true/></config-file>
<config-file parent="UIViewControllerBasedStatusBarAppearance" platform="ios" target="*-Info.plist"><false/></config-file>
```

I think this no longer has any effect. C3 was updated to use a different approach that works. I guess this is actually an issue with C2's Cordova export, but @shortercode maybe the build server can spot this and apply some backwards-compat patching? Otherwise I think this should be filed as a C2 issue.

**Comment by shortercode** [comment]
Mmm well it's possible that we could apply a custom solution for C2 by patching in a special plugin. At the moment the C2.5 and C3 runtimes include the `cordova-plugin-statusbar` plugin at export time ( iOS only ), then if the runtimes detects the plugin it calls a method to hide the statusbar.

**Comment by AshleyScirra** [comment]
Maybe as a cheap workaround the C2 project could just use browser's 'Execute JavaScript' to run the relevant code?

**Comment by shortercode** [comment]
Yeah that should be easy for a user to implement, the JS snippet we use is:

```javascript
if (typeof window["StatusBar"] === "object")
    window["StatusBar"]["hide"]();
```

Should be fine to run this in a layout start event or similar. It does require the `cordova-plugin-statusbar` plugin, but by the sounds of it construct 2 is already including it.

**Comment by AshleyScirra** [comment]
C2 only includes cordova-plugin-statusbar when you tick 'Hide status bar' (which I think is the same basis C3 does). So I've just pasted that workaround code back in to the C2 runtime. This is a C2 issue really but is fixed for the next C2 release anyway. As a workaround you can use the Browser object to execute that JS on startup.

**Comment by RabloGames** [comment]
Thank you so much! \o/

**Comment by RabloGames** [comment]
Just to give feedback the solution worked perfectly ! Thanks a lot ! Is it automatic in the newest version of C2 ? I didn't see it in the change list.
