### ISSUE TITLE
Background of a project exported with C2 +C3 export manager is always black on iPhone X

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#2779]
## Problem description

When exporting a project with C2 + C3 export manager, the background on an iPhone X can't be set to white, it is always black.

## Attach a .c3p

[WhiteBG_iPhoneX.zip](https://github.com/Scirra/Construct-3-bugs/files/3013298/WhiteBG_iPhoneX.zip)

## Steps to reproduce

1. In C2, export the attached project with Cordova.
2. Create a zip file with the resulting files
3. Open C3's export manager and select the zip file you juste created
4. Click Build application
5. Copy the exported file on a Mac
6. Launch Xcode and open the .xcworkspace file located inside the iOS folder
7. Select iPhone X on top of the screen and launch the simulator.
8. The background is still black

## Observed result

The background around the green area is black on iPhone X

## Expected result

the background should be white

## More details

I tried everything the community suggested [here](https://www.construct.net/en/forum/construct-2/how-do-i-18/replace-black-bars-letterbox-141559), including various modification of the index.html file, executing javascript in C2, but nothing works.

![](https://s1.construct.net/images/v635/uploads/articleuploadobject/0/images/25238/c2-letterbox-color.png)

Please note that the background is correctly white in all other platforms (Android, PC, browser, any other iPhones than iPhone X), the problem only happens on iPhone X.

The background is also correct if the project is created in C3. Only C2 + C3's export manager doesn't work.

**Affected browsers/platforms:** 

iPhone X

**First affected release:** 

C3 r142.2
C2 r265

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.7 gb
Storage usage (approx): 5.3 gb (68.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
FYI in C3 the runtime does not include jQuery by default, so using jQuery in 'Execute Javascript' (i.e. `${...)`) won't work in C3 unless you specifically add a jQuery dependency again. C3 also has a project property for setting the background color - have you tried that? Does that not work either?

**Comment by RabloGames** [comment]
When the project is exported from C3, everything works just fine. I managed to have a white background on iPhone X. The problem comes when exporting the game from C2 (Cordova), then with C3 export manager to make an Xcode project.
In C3 I only have access to the export manager, so I don't think changing the background color will have an effect on the export manager. (?)

**Comment by shortercode** [comment]
@RabloGames there's not much you can change once it's in the export manager, the game has already been packaged up by that point.

**Comment by AshleyScirra** [comment]
All Construct 3's background color setting does is apply this CSS style:

```css
html, body {
    background: #000; /* based on "background color" project property */
}
```

Construct 2 does not set that, and your JS code setting it is invalid because it relies on jQuery, which isn't included in C3. So I would assume you just need to change the style properly when exported from C2.
