### ISSUE TITLE
XCode project not compiling 

### ISSUE THREAD

**Issue by yeaaqbi** [Scirra/Construct-3-bugs#2780]
## Problem description

I can not compile my exported game project in Xcode

## Attach a .c3p
https://drive.google.com/file/d/1b4Qs_W1n0WjSx0RuwVkZi89A9633nP1d/view?usp=sharing

## Steps to reproduce
1. Export the C3 game to XCode project.
2. Open the exported project with XCode
3. Trying to compile the project using XCode without success. 

## Observed result

![Screen Shot 2019-03-28 at 1 02 45 AM](https://user-images.githubusercontent.com/3922086/55117967-b0858880-50fd-11e9-867b-9ea9162c8c04.jpg)

## Expected result

It should compile the project as usual

## More details
It was working in the previous releases 
## System details

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.8 gb
Storage usage (approx): 776 mb (9.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by shortercode** [comment]
Please provide a minimal reproduction AKA not a 40MB project that requires a third party plugin.

**Comment by yeaaqbi** [comment]
@shortercode  I tried to add the plugins to other project, it compiles fine. I do not know why this happen in this project

**Comment by shortercode** [comment]
Could you remove the third party plugin and check if the issue still exists? If it does then send me that modified version, hopefully the issue will be clear enough for me.

**Comment by yeaaqbi** [comment]
I have removed the MobilrAds Plugin, it works. Strange behaviour

**Comment by shortercode** [comment]
The errors are because xcode project not being able to find components of the MobileAdvert plugin. So it's not surprising that removing the plugin resolves the problem.

I have tried an example project including the MobileAdvert plugin and not had this issue. Either this is related to how you are treating the project after you receive it, or your project includes something else which is causing this problem.

As such could you please provide the project I requested so I can test this.
