### ISSUE TITLE
Initially not visible buttons are rendered outside the canvas on visible area.

### ISSUE THREAD

**Issue by nagyv** [Scirra/Construct-3-bugs#2783]
## Problem description

I have a few button elements that should be hidden from the user by default and are only shown when needed. (e.g. the close button "X" of a message box)

When I set these buttons' "initially visible" option to false, they still get rendered just outside the canvas. On larger-than-canvas monitors they show up in the upper-right corner of the screen. See the attached images.

![editor](https://user-images.githubusercontent.com/126671/55216653-9cc14b80-51fd-11e9-9053-ad06c98b6b26.png)
![preview](https://user-images.githubusercontent.com/126671/55216652-9cc14b80-51fd-11e9-911c-199023f84a42.png)

## Attach a .c3p

https://www.dropbox.com/s/0gpaxcn8x3v84p8/not-visible-button.c3p?dl=0

## Steps to reproduce

1. Create a button
2. Set it to initially not visible
3. Start preview
4. Resize screen to be bigger than canvas

## Observed result

The button is visible on the top right corner outside the canvas.

## Expected result

Should not see the button. 

## More details

Setting the `display: none` on the button initially would solve the problem.

**Comment by NoSoul8** [comment]
I've encountered the same issue (button rendering outside canvas) but never payed attention - thought it was some browser specific issue.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
