### ISSUE TITLE
Add as App (Mac) Color wheel behind window. (stable)

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2784]
## Problem description

When changing color of a spirte or a layer, in the C3 app when added as app, the color when shows up behind the app.

## Attach a .c3p

N/A

## Steps to reproduce

1. Create a new project when C3 is added as an app (Mac)
2. Select layer 0, and try to change the color by clicking the box.
3. Color wheel is not showing. Minimize app, and you will see color box.

## Observed result

Color wheel does not show.

## Expected result

Should be on top, and not behind the app.

I don't have access to a Win PC to test this. Only Mac at the moment.

**Comment by AshleyScirra** [comment]
Construct doesn't control this, it looks like a browser bug. Filed [a chrome issue here](https://bugs.chromium.org/p/chromium/issues/detail?id=948065), will follow up there.
