### ISSUE TITLE
Add as app (Mac) Pinching on touchpad to zoom in layout zooms UI.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2785]
## Problem description

When using pinch to zoom the Layout when C3 is added as an app, the whole UI zooms.

## Attach a .c3p

N/A

## Steps to reproduce

1. Open C3 when added as an app (Mac)
2. Go to layout and use pinch on a macbook touchpad to zoom layout.
3. Notice the whole UI zooms.

## Observed result

UI is zooming

## Expected result

Should only zoom the layout, same like when going to editor.construct.net in chrome.

**Comment by AshleyScirra** [comment]
I think this is another case of #2786 - let's check when the next release is out.

**Comment by AshleyScirra** [comment]
r143 is now out, does the issue still reproduce there?

**Comment by AshleyScirra** [comment]
No response, can't reproduce in r144, and think this is the same case as #2786 which was fixed, so closing.
