### ISSUE TITLE
Cannot run c3 on mobile

### ISSUE THREAD

**Issue by oosyrag** [Scirra/Construct-3-bugs#2788]
## Problem description

Crash with error message upon trying to run c3 on mobile. Happens immediately after full screen and add c3 to home screen prompts. Haven't used on phone for a long time, r89, but doesn't seem to get update before crashing.

## Attach a .c3p

N/A

## Steps to reproduce

1. Run c3 from chrome browser

## Observed result

Crash after error message

## More details

**Affected browsers/platforms:** 
Chrome, Android 8, miui global 10.2, xiaomi mi5

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: The prompt() method must be called with a user gesture
Construct 3 version: r89
URL: https://editor.construct.net/
Date: Sat Mar 30 2019 12:02:15 GMT-0700 (Pacific Daylight Time)
Uptime: 7.9 s

Platform information
Browser: Chrome
Browser version: 72.0.3626.105
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Android
Operating system version: 8.0.0
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 3
Logical CPU cores: 4
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Linux; Android 8.0.0; MI 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.105 Mobile Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Qualcomm
Renderer: Adreno (TM) 530
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by oosyrag** [comment]
I'm guessing some chrome or Android update broke the older version of construct. How would I go about clearing whatever is cached on my phone to download the latest version?

**Comment by MikalDev** [comment]
Try going to a newer beta using: https://editor.construct.net/r142-3/

**Comment by AshleyScirra** [comment]
The crash is already fixed (because that release is so old) but it's currently not updating due to https://github.com/Scirra/Construct.net-website-bugs/issues/82. This should be fixed shortly; in the mean time either clear the browser cache or visit the version URL directly.
