### ISSUE TITLE
Button click event triggering twice

### ISSUE THREAD

**Issue by laice** [Scirra/Construct-3-bugs#2790]
## Attach a .c3p
[ButtonTextBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3026658/ButtonTextBug.zip)

## Steps to reproduce

1. Click Ok Button
2.
3.

## Observed result

'Not Ok Clicked' displays in output

## Expected result
The text field should be made visible, the button should change to 'Not Ok' and the output text should display 'Ok clicked'

## More details

When the 'Ok' button is clicked in example .cap, expected behaviour would be to change button text to 'Not Ok', make the invisible text field visible, and set the output text to 'Ok Clicked'. Clicking does this, but the second event also activates which changes the button text back to Ok, makes the text field invisible again, and outputs the text 'Not Ok Clicked' after a single click of the initial Ok button.

**Affected browsers/platforms:** 
Chrome 73.0.3683.86 for OSX 10.14.4 (latest at posting)

**First affected release:** 
r142.2
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 25 gb
Storage usage (approx): 213 mb (0.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2047
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)

WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's working correctly. When the button is clicked, the "On clicked" events run in sequence, from top to bottom. The first "On clicked" event changes the button text, making the next trigger true.
