### ISSUE TITLE
Calling a function across event sheets

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2792]
## Problem description

You can call a function from another event sheet even if said event sheet isn't included. This works fine, unless the function is set as a subevent, or part of a group. I also tried calling legacy functions from the same non included event sheet as the new function, but I got a warning from the function plugin telling me that my call didn't do anything.

## Attach a .c3p

[Bug Functions.zip](https://github.com/Scirra/Construct-3-bugs/files/3030172/Bug.Functions.zip)

## Steps to reproduce

1. Enable the two events, one at a time
2. Run game

## Observed result

The game is black, and the console prints an error

## Expected result

It should work I guess.

## More details

**First affected release:** r143

**Comment by RorySoh** [comment]
It seems to be that any function in any group is not working

**Comment by AshleyScirra** [comment]
Fixed functions not working in sub-events for the next release.

Note your example confusingly combines old and new functions: old functions only work when the function is included to the current sheet (as per the trigger mechanism), whereas new functions work in any event sheet. The project exposes the difference by calling a new function which calls an old function, which won't make the call to the old function unless it's included.

**Comment by skymen** [comment]
Yes I know, I was just trying to see if it would include the whole event sheet or just the function block
