### ISSUE TITLE
C3 IDE crash when searching for new function parm (or name?)

### ISSUE THREAD

**Issue by pkreemer** [Scirra/Construct-3-bugs#2794]
## Problem description
C3 editor crashes when searching for a function parameter

[search-test.zip](https://github.com/Scirra/Construct-3-bugs/files/3031514/search-test.zip)

## Steps to reproduce
1.  Do ctrl-F search for new function parameter name

## Observed result
IDE crashes

I've also see R143 crash when searching for a new function name, but couldn't repro that in the little test project attached here.

## Expected result
New function line(s) should be listed in search results

## System details
C3 R143 beta:
- Win64 NW.js version of C3 IDE, and,
- C3 running in Chrome 73.0.3683.86 

- tested only w/ Windows 10 OS

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r143/components/bars/findResultsBar/findResultsBar.js, line 1, col 1897
Message: Uncaught TypeError: a is not a function
Stack: TypeError: a is not a function at Object.ǃFzM (https://editor.construct.net/r143/components/bars/findResultsBar/findResultsBar.js:1:1897) at Object.ǃLzd (https://editor.construct.net/r143/components/bars/findResultsBar/findResultsBar.js:1:1689) at ǃI.ǃw.ǃS.ǃLzP.ǃNPs (https://editor.construct.net/r143/main.js:81:601157) at ǃI.ǃw.ǃS.ǃLzP.ǃki (https://editor.construct.net/r143/main.js:2:289331) at d.ǃki (https://editor.construct.net/r143/main.js:2:261676) at HTMLDocument.t.document.addEventListener (https://editor.construct.net/r143/main.js:2:259973)
Construct 3 version: r143
URL: https://editor.construct.net/r143/
Date: Mon Apr 01 2019 14:58:30 GMT-0700 (Pacific Daylight Time)
Uptime: 25.9 s

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r143 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

Edit: typo in observed result, where it listed vR134, and should be R143.

**Comment by AshleyScirra** [comment]
Thanks, fixed the crash searching for the next release. I also noticed you couldn't search for the new function by its name with a text search, so I fixed that for the next release too.

**Comment by pkreemer** [comment]
Thanks Ashley, and the new function system is much appreciated.  Good stuff!
