### ISSUE TITLE
The AdvancedRandom plugin does not work in Safari

### ISSUE THREAD

**Issue by nilsnordmark** [Scirra/Construct-3-bugs#2796]
## Problem description

The AdvancedRandom plugin does not work in Safari because it uses WebAssembly.instantiateStreaming() which is not supported in Safari.

## Steps to reproduce

1. Add AdvancedRandom plugin 
2. Export to HTML5 and run in Safari. Mobile or Desktop

## Observed result

Game won't start properly

## Expected result

Game starts ok

## More details
The AdvancedRandom plugin does not work in Safari because it uses WebAssembly.instantiateStreaming() which is not supported in Safari.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming

c3runtime.js:
    ...
    C3.Plugins.AdvancedRandom.Instance = class  extends C3.SDKInstanceBase{
            constructor(a, b)
            {
                super(a), this._core = null, this._currentSeed = null, this._octaves = 1, this._gradients = new Map, this._currentGradient = null, this._permutation = [0];
                const c = b[0],
                    d = b[1];
                this._CreateGradient("default", "rgb"), this._AddGradientStop(0, C3.PackRGBEx(0, 0, 0)), this._AddGradientStop(1, C3.PackRGBEx(1, 1, 1)), this._runtime.AddLoadPromise(this._InitWASMModule(c, d))
            }
            async _InitWASMModule(a, b)
            {
                const c = await this._runtime.GetAssetManager().FetchBlob("noise.wasm"),
                    d = new Response(c, {
                        "headers": {
                            "content-type": "application/wasm"
                        }
                    }),
                    e = await WebAssembly.instantiateStreaming(d);
                this._core = e.instance.exports, "" === a && (a = this._RandomSeed(10)), this._UpdateSeed(a), b && this._runtime.SetRandomNumberGeneratorCallback(() => this._core.randomXorshiro(0, 1))
            }
    ...

If I add a polyfill for WebAssembly.instantiateStreaming in index.html everything seems to work:
    ...
    <script>
    if (!WebAssembly.instantiateStreaming) {
        WebAssembly.instantiateStreaming = async (resp, importObject) => {
            const source = await (await resp).arrayBuffer();
            return await WebAssembly.instantiate(source, importObject);
        };
    }
    </script>
    ...

## System details

Latest iOS and Safari. Tested on Macbook pro and iphone 8

</details>

**Comment by shortercode** [comment]
Thanks for the report, I've updated the module to optionally use streaming instantiation where supported and fallback to standard instantiation. Fix should be in the next release. Functionally it's not too different from your polyfill, so it's safe for you to use that workaround for the time being.
