### ISSUE TITLE
Duplicating layouts crash the engine

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2798]
## Problem description

Duplicating layouts crash the engine everytime.

## Attach a .c3p

No needed since any blank project will also crash.

## Steps to reproduce

1. Open a blank project.
2. Try to duplicate the "Layout 1".

## Observed result

The engine crash.

## Expected result

The layout to be duplicated without crashing the engine.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Came up due to #2781 and already fixed for next release, closing as duplicate.

**Comment by BonzerKitten7** [comment]
Thanks for the quick fix and sorry for the duplicate.
