### ISSUE TITLE
Graphics get jumbled when I plug in an external projector

### ISSUE THREAD

**Issue by mammothinc** [Scirra/Construct-3-bugs#2800]
When I plugin my macbook pro to an external projector, the editor's icons change. There are also other issues. I can't move around in my layouts. It gets frozen.

## Steps to reproduce

Plugin a macbook pro to a projector

**Comment by AshleyScirra** [comment]
Sounds like a graphics driver issue which isn't to do with Construct. There's nothing we can do anyway unless you follow the guidelines.
