### ISSUE TITLE
Crash on Timeline add textobject to timeline

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#2801]
## Problem description

I recived this crash report after adding TEXTOBJECT to timeline

## More details
r143
## System details

<details><summary>Error report information</summary>
Type: unhandled exception
File: https://editor.construct.net/r143/main.js, line 2, col 126148
Message: Uncaught Error: unexpected type
Stack: Error: unexpected type at o.ǃYX (https://editor.construct.net/r143/main.js:81:222541) at n.ǃLtv (https://editor.construct.net/r143/main.js:81:485814) at n.ǃLts (https://editor.construct.net/r143/main.js:81:486617) at n.ǃLCO (https://editor.construct.net/r143/main.js:81:484620) at n.ǃLWP (https://editor.construct.net/r143/main.js:81:482405) at new n (https://editor.construct.net/r143/main.js:81:476328) at Function.ǃW (https://editor.construct.net/r143/main.js:2:126127) at n.ǃLCu (https://editor.construct.net/r143/main.js:81:458986) at n.ǃvx (https://editor.construct.net/r143/main.js:81:459196) at Object.ǃOi (https://editor.construct.net/r143/components/editors/layoutView/layoutView.js:1:31550)
Construct 3 version: r143
URL: https://editor.construct.net/r143/
Date: Tue Apr 02 2019 12:14:34 GMT-0300 (hora estándar de Argentina)
Uptime: 1581.8 s

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r143 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon(TM) RX 460 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context</summary>

</details>

**Comment by shortercode** [comment]
@kingpirux your report is somewhat short on details, does this always happen given this action or was this a onetime crash that you haven't been able to reproduce?

Assigned to @DiegoScirra to review the crash report.

**Comment by kingpirux** [comment]
it happend twise at least :( but i cant reproduce again... that's the last report information.

**Comment by kingpirux** [comment]
@DiegoScirra i found it, if you add textobject to new timeline it crashes
an other report:
Error report information
Type: unhandled exception
File: https://editor.construct.net/r143/main.js, line 2, col 126148
Message: Uncaught Error: unexpected type
Stack: Error: unexpected type at o.ǃYX (https://editor.construct.net/r143/main.js:81:222541) at n.ǃLtv (https://editor.construct.net/r143/main.js:81:485814) at n.ǃLts (https://editor.construct.net/r143/main.js:81:486617) at n.ǃLCO (https://editor.construct.net/r143/main.js:81:484620) at n.ǃLWP (https://editor.construct.net/r143/main.js:81:482405) at new n (https://editor.construct.net/r143/main.js:81:476328) at Function.ǃW (https://editor.construct.net/r143/main.js:2:126127) at n.ǃLCu (https://editor.construct.net/r143/main.js:81:458986) at n.ǃvx (https://editor.construct.net/r143/main.js:81:459196) at Object.ǃOi (https://editor.construct.net/r143/components/editors/layoutView/layoutView.js:1:31550)
Construct 3 version: r143
URL: https://editor.construct.net/r143/
Date: Wed Apr 03 2019 13:47:15 GMT-0300 (hora estándar de Argentina)
Uptime: 28.6 s

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r143 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon(TM) RX 460 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by DiegoScirra** [comment]
Fixed in the next beta release
