### ISSUE TITLE
Animation editor background grid graphic glitz

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2803]
## Problem description
It used to be correct, it only appears on chrome now. The editor grid cells have diagonal line which should not be there. Affects all backgrounds that use that CSS

## Steps to reproduce

1.Use chrome, open new project
2.Open animation editor, see background grid
3.See that grid cells have diagonal line glitz

## Observed result
Animation editor draw area background cells have diagonal lines which were not there before.
![CellGlitz](https://user-images.githubusercontent.com/28864889/55434737-f086b880-55a0-11e9-95d5-5a7995b9b60d.jpg)

## Expected result
No diagonal lines on any grid

Fix: linear-gradient(45deg,#f0f0f0 26%,transparent 26%,transparent 74%,#f0f0f0 74%,#f0f0f0),linear-gradient(45deg,#f0f0f0 26%,transparent 26%,transparent 74%,#f0f0f0 74%,#f0f0f0)

"All 25 values to 26 and 75 to 74"

## More details

**Affected browsers/platforms:** 
Chrome only

**First affected release:** 
Not sure which, but i remember it was not there like 2month ago. It's all correct on firefox
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.1 gb (8.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Going to assign to @DiegoScirra to review. As a small note: I have infrequently experienced this issue for months myself. I'm unsure what the reproduction situation is, but it's not new.

**Comment by DiegoScirra** [comment]
Fixed in the next beta release.
