### ISSUE TITLE
Editor Crashes when adding string parameter to New Functions

### ISSUE THREAD

**Issue by yeahyeah333** [Scirra/Construct-3-bugs#2806]
## Problem description

If you have an event that calls a New Function, and then you try to add a new string parameter to the called function, and you don't change the default value from blank, or you enter a value without quotation marks, construct crashes

## Attach a .c3p

[FunctionsBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3038706/FunctionsBug.zip)

## Steps to reproduce

1. Right click Crash Function
2. Click "Add Parameter"
3. Select Type String
4. Leave default value blank
OR
4. Type a value without quotation marks
5. Click OK

## Observed result

Construct crashes

## Expected result

Construct doesn't crash

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** First started happening in R143

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Unknown expression 'gdsfds': This is not a system expression or variable name in this scope.
Construct 3 version: r143
URL: https://editor.construct.net/r143/
Date: Wed Apr 03 2019 07:57:01 GMT-0500 (Central Daylight Time)
Uptime: 220.4 s

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r143 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro FX 2800M Direct3D11 vs_4_0 ps_4_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_disjoint_timer_query, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, EXT_sRGB, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
