### ISSUE TITLE
Duplicate Animation Name error

### ISSUE THREAD

**Issue by bgerards** [Scirra/Construct-3-bugs#2807]
## Problem description

c3p file will not open. It says "Duplicate Animation Name"

## Attach a .c3p

[Final Game (Beta).zip](https://github.com/Scirra/Construct-3-bugs/files/3040028/Final.Game.Beta.zip)

## Steps to reproduce

1. Error happens on trying to open. It won't allow the user into the file.
2.
3.

## Observed result

Error message - "Duplicate Animation Name"
![image](https://user-images.githubusercontent.com/49248188/55500714-b26bb200-55fd-11e9-9a52-f85ba45ad536.png)

## Expected result

Open the file

## More details
User used animation names that were similar, but not identical. The program shouldn't have allowed repeated animation names to begin with. 

**Affected browsers/platforms:** Only tried on Chrome. This is the only browser we have access to at this time.

Happened with current stable version - r142.2

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 19 gb
Storage usage (approx): 1.4 gb (7.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon Pro 555 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Do you have steps to reproduce how to cause this to happen in the first place? We can recover the project but we can't fix the problem that caused it in the first place if we don't know how it happened.

**Comment by AshleyScirra** [comment]
Also @shortercode / @DiegoScirra - the error message here is insufficient, there should never be OK dialogs that just dump an exception message to the screen.

**Comment by bgerards** [comment]
@AshleyScirra  - I'm not sure how the problem began. It's a file that was created by a student of mine. He said it worked just fine on Friday the 22nd and he saved and logged out of the machine. Then two days ago when he returned to it he got the error message as seen in the pic above. He didn't receive any error messages during the creation of the project up to that point.
I've never seen this problem before so I don't know how to trace it, and we can't get into the project in Construct because of it.
Also, the error message in the pic is what we've gotten from that file on more than one machine, so it definitely seems to be file-related and not system-related.

**Comment by DiegoScirra** [comment]
In the current version there is a problem with how the default names for animations are created, so you can end up with animations having the same name.

The bug is fixed now, will post back a fixed project so your student can continue using it.

**Comment by DiegoScirra** [comment]
@bgerards 

Try out this file, it should work.

[Final Game (Beta) Fixed.zip](https://github.com/Scirra/Construct-3-bugs/files/3047836/Final.Game.Beta.Fixed.zip)

**Comment by bgerards** [comment]
Awesome. I was able to open it on my machine. I'll pass it along to the student and make sure he can get into it this afternoon. 
Thanks so much for everyone's help.
