### ISSUE TITLE
Sprite doesn't get picked when an offset is introduced

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#2808]
## Problem description

When I introduce an offset of -96 (or any) the idme sprite does not get picked. When I enter a value it does get picked, when I remove the offset (-96) it does get picked. But when any + or - is introduced, and such a sprite exists like in the example here, it doesn't work.

## Attach a .c3p

[buggy.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3041893/buggy.c3p.zip)

## Steps to reproduce

1. Run project
2. click on any of the sprites
3. nothing happens

## Observed result

nothings happens 

## Expected result

idme gets destroyed like when you remove -96 and it works.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_1
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 61 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 615
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by damjancd** [comment]
I think I've narrowed it down further. It doesn't react to picked at all. This is a simpler example:
[buggy2.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3041940/buggy2.c3p.zip)

It reacts if it's touched, then it is picked properly, but when picked by uid, or comparison or anything like that, it doesn't react doesn't pick it

**Comment by damjancd** [comment]
Picked by n-th instance and picked by random instance works fine :O

**Comment by AshleyScirra** [comment]
This is not a bug. You have an equal number of `main` and `idme` instances, so for the purposes of expression evaluation, Construct pairs them up. Therefore as it iterates `idme` determining which it should pick, every time it evaluates `main.Y` or `main.X` it picks the instance it is paired with; since the paired instance is at the same position, if you add or subtract anything this is never true, so nothing is picked. You should use a different approach in this case, e.g. using 'For each' loops.
