### ISSUE TITLE
Visually difference of objects Z elevation in Layout editor and in Preview

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2811]
## Problem description

2 objects in the layout with different Z elevation Shows different gap between them as compared in layout editor and in preview mode

## Attach a .c3p
[Z Elevation issue.zip](https://github.com/Scirra/Construct-3-bugs/files/3044223/Z.Elevation.issue.zip)

## Steps to reproduce

1. Insert Sprite and make 2 instances 
2. Set 1st instance Z elevation value 0
3. Set 2nd instance Z elevation value -60
4. Place them together with minimum gap between them (So we could see the difference in gap between them in preview)
5. do preview

## Observed result

gap between both instance is larger than we placed in the layout

## Expected result

gap between both instance should be same as we set them in layout.

## More details

**Affected browsers/platforms:** 

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is just because the viewport and scroll position in the editor are different.

**Comment by luckyrawatlucky** [comment]
i just only wants to spawn object outside layout on different z elevation.
i did negetive values to y 
0 zelevation is good but other numbers like - 20,-40,-60 makes object spawning in front of eyes. 
how can i avoid this
