### ISSUE TITLE
Facebook Playable Ads do NOT display (black screen)

### ISSUE THREAD

**Issue by facecjf** [Scirra/Construct-3-bugs#2812]
## Problem description

As mentioned before - Facebook playable ads are not displaying. The "scriptElt" error is in fact a FB error, as pointed out by Ashley. 

I've deployed on other ad networks with same requirements (like applovin) with zero problems. So it's hard to trouble shoot either side FB or C3.

## Attach a .c3p
Link to .c3p file : https://www.dropbox.com/s/p3jw9g1us456jun/720x1280_FB_Template.c3p?dl=0
[720x1280_FB_Template.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3045002/720x1280_FB_Template.c3p.zip)

## Steps to reproduce

1. Open attached file and export for "Facebook Playable"
2. Goto Facebook Ads Manager and create an ad and check "Add Playable Asset"
3. Click "Upload Playable" and upload "exported "index.html" file
4. Black screen presented in the preview 

## Observed result

Black Screen

## Expected result

Should load game / playable

## More details

It appears at first it was only a FB dashboard issue - but when pushed live, I am getting the same result of a black screen. I checked the console and saw the "scriptElt" error and dug a little deeper.
Below is the FB code block that seems to handle this : 

`Object.defineProperties(element, {
 'src': {
 get() {
 return originalDescriptors.src.get.call(element)
 },
 set(value) {
 if (proto === HTMLImageElement.prototype || proto === HTMLMediaElement.prototype) {
 if (hasValidProtocolForPlayable(value)) {
 return originalDescriptors.src.set.call(element, value)
 }
 else {
 // If it's not a valid protocol then just set an empty
 // string as a src to avoid unnecessary observer calls
 return originalDescriptors.src.set.call(element, '')
 }
 } else if (proto === HTMLScriptElement.prototype) {
 if (needsToBeBlacklisted(value, scriptElt.type)) {
 scriptElt.type = 'javascript/blocked'
 }
 return originalDescriptors.src.set.call(element, value)
 }
 }
 },
 'type': {
 set(value) {
 if (proto === HTMLScriptElement.prototype) {
 return originalDescriptors.type.set.call(
 element,
 // If a third-party code tries to set the type, but the source is blacklisted then prevent.
 needsToBeBlacklisted(element.src, element.type) ?
 'javascript/blocked' :
 value
 )
 } else {
 return originalDescriptors.src.set.call(element, value)
 }
 }
 }
 });`

I'm taking a shot in the dark here - but it appears that FB is blacklisting C3s JS. Not sure if that is actually whats going on. I have reached out to FB about this and they stated it's not a FB issue. 

**Affected browsers/platforms:** 
Facebook

**First affected release:** 
R134

## System details

NA

**Comment by AshleyScirra** [comment]
The problem is in Facebook's code, so they need to fix it. Please report it to them, there's nothing we can do about it.

**Comment by facecjf** [comment]
Appreciate it Ashley. Noting here that I have tech call with them today or Monday to try and resolve this.
