### ISSUE TITLE
new function bug - crash

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#2815]
## Problem description

I can reproduce a crash when using the new functions but don't know what exactly is causing it. So i have stripped down my project to just a couple of lines and the crash can be reproduced by following the steps.

Also here is the crash log.

Error report information
Type: unhandled rejection
Reason: Error: ǃLaD is not defined @ ReferenceError: ǃLaD is not defined at Object.ǃLap (https://editor.construct.net/r143/main.js:177:64012) at Object.ǃLaA (https://editor.construct.net/r143/main.js:177:63031) at Object.ǃFA (https://editor.construct.net/r143/main.js:177:67220) at Array. (https://editor.construct.net/r143/main.js:177:58926) at Object.ǃNuH (https://editor.construct.net/r143/main.js:2:191611) at Object.dispatchEvent (https://editor.construct.net/r143/main.js:2:189652) at Object.ǃNHW (https://editor.construct.net/r143/main.js:2:458010) at HTMLElement. (https://editor.construct.net/r143/main.js:2:461955) at HTMLDocument. (https://editor.construct.net/r143/main.js:2:186389)
Stack: ReferenceError: ǃLaD is not defined at Object.ǃLap (https://editor.construct.net/r143/main.js:177:64012) at Object.ǃLaA (https://editor.construct.net/r143/main.js:177:63031) at Object.ǃFA (https://editor.construct.net/r143/main.js:177:67220) at Array. (https://editor.construct.net/r143/main.js:177:58926) at Object.ǃNuH (https://editor.construct.net/r143/main.js:2:191611) at Object.dispatchEvent (https://editor.construct.net/r143/main.js:2:189652) at Object.ǃNHW (https://editor.construct.net/r143/main.js:2:458010) at HTMLElement. (https://editor.construct.net/r143/main.js:2:461955) at HTMLDocument. (https://editor.construct.net/r143/main.js:2:186389)
Construct 3 version: r143
URL: https://editor.construct.net/r143/
Date: Fri Apr 05 2019 16:06:20 GMT+0100 (British Summer Time)
Uptime: 140.1 s

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r143 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Attach a .c3p

[functionBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3048578/functionBug.c3p.zip)

## Steps to reproduce

1. open project
2. Go to line 3 (sub event) and click "add action"
3. Double click "functions built in" object
4. Double click "function1"
5. in param1, click "find expressions" button, 
6. click "Army" family object
7. Construct crashes.

## Observed result

construct crashes

## Expected result

to be able to add an expression to a function param.

## More details

**Affected browsers/platforms:** 

just tested in chrome.

**First affected release:** 

r143 beta

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r143 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 533 mb (0.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
@DiegoScirra - I think you already fixed this one judging by the crash message.

**Comment by DiegoScirra** [comment]
Yeah, this is fixed already. Will be available in the next beta.
