### ISSUE TITLE
new function text colour with dark theme.

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#2816]
## Problem description

I'm colour blind and the colour of the new function event text on the dark theme is unreadable to me.

![Screen Shot 2019-04-05 at 16 30 22](https://user-images.githubusercontent.com/30123541/55639052-6e74da80-57c0-11e9-907a-1b5fdff18298.png)

I can only see the text when its selected.

![Screen Shot 2019-04-05 at 16 30 38](https://user-images.githubusercontent.com/30123541/55639091-88162200-57c0-11e9-9bb5-dcce1e6d1366.png)

Please can it be changed in the next release?

## Attach a .c3p

n/a

n/a

## Observed result

can't see text of function event.

## Expected result

to be a colour better suited for the dark theme.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Yes, the blue color was only temporary and has been removed in the next release.
