### ISSUE TITLE
Editor Crash When Reordering Layers

### ISSUE THREAD

**Issue by AySquirrel** [Scirra/Construct-3-bugs#2817]
## Problem description

Reordering layers causes the editor to crash

## Attach a .c3p
[Layer Crash Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3050025/Layer.Crash.Bug.zip)

## Steps to reproduce

1. Open the project
2. In the layers panel, drag Layer 1 below Layer 0
3. Drag Layer 0 below Layer 1
4. Click anywhere in the layout

## Observed result

A crash report immediately appears on screen, and the project is forced to be closed

## Expected result

The project to continue running normally

## More details

Guessing this is somehow related to #2763 since they're both new?  But I checked both the newest stable and beta releases, and this crash still occurs on both

**Affected browsers/platforms:** 

Chrome, Firefox

**First affected release:** 

Only happens in r142 and up; checked r136 and no crash occurs

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r142/main.js, line 2, col 121017
Message: Uncaught TypeError: expected HTML element
Stack: TypeError: expected HTML element at Function.ǃJ.ǃVe (https://editor.construct.net/r142/main.js:2:121023) at Function.ǃgPp (https://editor.construct.net/r142/main.js:2:271731) at i.ǃJI (https://editor.construct.net/r142/main.js:2:467957) at window.ǃHk.ǃWj (https://editor.construct.net/r142/components/bars/zOrderBar/zOrderBar.js:1:17105) at window.ǃHk.ǃNW (https://editor.construct.net/r142/components/bars/zOrderBar/zOrderBar.js:1:16846) at window.ǃHk.ǃgn (https://editor.construct.net/r142/components/bars/zOrderBar/zOrderBar.js:1:5909) at window.ǃHk.ǃIu (https://editor.construct.net/r142/components/bars/zOrderBar/zOrderBar.js:1:7896) at Array.ǃIi (https://editor.construct.net/r142/components/bars/zOrderBar/zOrderBar.js:1:462) at ǃJ.Event.ǃgXv.ǃgXY (https://editor.construct.net/r142/main.js:2:211922) at window.ǃgB.dispatchEvent (https://editor.construct.net/r142/main.js:2:209963)
Construct 3 version: r142
URL: https://editor.construct.net/r142/
Date: Fri Apr 05 2019 20:09:50 GMT-0500 (Central Daylight Time)
Uptime: 55.7 s

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta release
