### ISSUE TITLE
Construct 3 crash

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#2818]
## Problem description

When i select the obj_ed_temp object on expressions, construct 3 crashes. I get this error:

> Error report information
> Type: unhandled rejection
> Reason: Error: ǃLaD is not defined @ ReferenceError: ǃLaD is not defined at Object.ǃLap (https://editor.construct.net/r143/main.js:177:64012) at Object.ǃLaA (https://editor.construct.net/r143/main.js:177:63031) at Object.ǃFA (https://editor.construct.net/r143/main.js:177:67220) at Array. (https://editor.construct.net/r143/main.js:177:58926) at Object.ǃNuH (https://editor.construct.net/r143/main.js:2:191611) at Object.dispatchEvent (https://editor.construct.net/r143/main.js:2:189652) at Object.ǃNHW (https://editor.construct.net/r143/main.js:2:458010) at HTMLElement. (https://editor.construct.net/r143/main.js:2:461955) at HTMLDocument. (https://editor.construct.net/r143/main.js:2:186389)
> Stack: ReferenceError: ǃLaD is not defined at Object.ǃLap (https://editor.construct.net/r143/main.js:177:64012) at Object.ǃLaA (https://editor.construct.net/r143/main.js:177:63031) at Object.ǃFA (https://editor.construct.net/r143/main.js:177:67220) at Array. (https://editor.construct.net/r143/main.js:177:58926) at Object.ǃNuH (https://editor.construct.net/r143/main.js:2:191611) at Object.dispatchEvent (https://editor.construct.net/r143/main.js:2:189652) at Object.ǃNHW (https://editor.construct.net/r143/main.js:2:458010) at HTMLElement. (https://editor.construct.net/r143/main.js:2:461955) at HTMLDocument. (https://editor.construct.net/r143/main.js:2:186389)
> Construct 3 version: r143
> URL: https://editor.construct.net/r143/
> Date: Sat Apr 06 2019 04:00:34 GMT+0200 (Central European Summer Time)
> Uptime: 474.3 s
> 
> Platform information
> Browser: NW.js
> Browser version: 0.35.1
> Browser engine: Chromium
> Browser architecture: 64-bit
> Context: nwjs
> Operating system: Windows
> Operating system version: 10
> Operating system architecture: 64-bit
> Device type: desktop
> Device pixel ratio: 1
> Logical CPU cores: 8
> Approx. device memory: 8 GB
> User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
> C3 release: r143 (beta)
> Language setting: en-US
> 
> WebGL information
> Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
> Numeric version: 2
> Supports NPOT textures: yes
> Supports GPU profiling: yes
> Supports highp precision: yes
> Vendor: Google Inc.
> Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
> Major performance caveat: no
> Maximum texture size: 16384
> Point size range: 1 to 1024
> Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Attach a .c3p

[Example](https://drive.google.com/open?id=1Df1AVA80Gb81hmTFtPTWsr60Hzgk1nDV)

## Steps to reproduce

1. Open the example-file
2. Select the obj_ed_temp object on any expression
3. Construct 3 crash

## Observed result

Construct 3 crashes

## Expected result

No crash/error

**Affected browsers/platforms:** 

Windows - Standalone-Application from construct 3 board.

**First affected release:** 

r143

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r143 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 39 gb
Storage usage (approx): 497 mb (1.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta
