### ISSUE TITLE
[r29.2] Swap animation name by renaming them then undo crash

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#282]
## Problem description

Let's say you have 2 animations each named JAMES then the other JOHN. Now, close the animation editor of this Sprite object and re-open it. This time, rename JAMES to XXX and rename JOHN to JAMES. Then rename XXX to JOHN. This way both animation names are swapped. Close the animation editor. At this point if you try to undo them, Construct will crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r29-2/main.js, line 61, col 185351
Message: Uncaught Error: duplicate animation name
Stack: Error: duplicate animation name at te.ǃCU (https://editor.construct.net/r29-2/main.js:61:185357) at ǃnO.ǃ_h.ǃJtq (https://editor.construct.net/r29-2/main.js:71:36816) at ǃnO.ǃJGv.ǃJtq (https://editor.construct.net/r29-2/main.js:71:35200) at window.ǃCMy.ǃGz (https://editor.construct.net/r29-2/main.js:71:33566) at we.ǃGz (https://editor.construct.net/r29-2/main.js:61:89155) at window.ǃJDv.ǃGz (https://editor.construct.net/r29-2/main.js:162:35215) at Array.ǃE.ǃC.ǃw.ǃC.ǃA.ǃN.je (https://editor.construct.net/r29-2/main.js:162:12935) at ǃC.Event.ǃm$A.ǃm$d (https://editor.construct.net/r29-2/main.js:2:285164) at window.ǃJDv.dispatchEvent (https://editor.construct.net/r29-2/main.js:2:283743) at ee (https://editor.construct.net/r29-2/main.js:162:43798)
Construct 3 version: r29.2
URL: https://editor.construct.net/index.html
Date: Sat May 20 2017 01:45:41 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 15816.3 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r30.
