### ISSUE TITLE
cannot open .c3proj

### ISSUE THREAD

**Issue by allowiscous** [Scirra/Construct-3-bugs#2820]
original post here [here](https://www.construct.net/en/forum/construct-3/how-do-i-8/unable-open-project-143021)

> hi. i saved my construct 3 game, and closed the program. i'm attempting to open it, but the >program is giving me an error; 'Failed to open project. Check it is a valid Construct 3 folder project.'

>anyways to fix such? also, if that's not possible, how can i import the event sheets, sprites, and layout from the files in the folders?

>EDIT: tried changing the extension around, no luck. i opened it in a text editor as well, and it doesn't seem awfully changed. not that i would know the nuance, but w/e. the file type is. c3proj

>EDIT2: this may or may not be relevant, but it may be wise to take a look at the brightness effect. i added it to my game, and oddly enough when enabled it acted as the effect that flips the game vertically. i say this may be relevant because i saw that project files may not open if there's a conflict in file names within them (someone mentioned renaming their layout caused issues), and if the brightness is acting as the vertical warp effect that may have some relevance. just a thought.

>EDIT3: another edit, because edits are good. i attempted to open the file in older versions (and newer versions, lol) but no luck. apparently i am running 142.2, (which is 142.3, technically)

## Problem description

cannot open 

## Attach a .c3p

https://www.dropbox.com/s/fss2l1s280rm3lv/proj.zip?dl=0

link to full project folder. check it out, it's dope

## Steps to reproduce

attempt to open w/ desktop client or browser client

## Observed result

error message, file not opening

desktop

"Failed to open project. Check it is a valid Construct 3 folder project."

browser

"Unknown file extension. Please choose a valid Construct 3 or Construct 2 project file."

## Expected result

project to open

## System details

<details><summary>platform info</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 850 gb
Storage usage (approx): 55 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by dop2000** [comment]
Your project is missing a file "button-animation 1-000.png"
If you add a file with this name to images folder, you'll be able to open the project.

**Comment by allowiscous** [comment]
thankie. works now. i do however still have question about brightness. i noticed the y flip effect only appears whens both brightness and scanline effects are present for the layout. is this known?

**Comment by AshleyScirra** [comment]
File is now 404 so cannot investigate. Please follow all the bug report guidelines - including providing steps to reproduce the problem - otherwise there's nothing we can do to fix the underlying problem.
