### ISSUE TITLE
Dictionary Data editor inconsistency: some rows change position

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2821]
## Problem description

After closing and opening a dictionary file, the bug changes some rows randomly without me asking it to. 

It seems to sort them irregularly, some rows are sorted but not all are. 

One solution, would be to just automatically sort every row so there's no inconsistency. Or another option would be to not sort rows at all. Or a button could be added that applies a sort to all keys, making it easier to find keys and manage the data workflow better.

## Image of an example problem

1. Working in the dictionary edit, then close it

![image](https://user-images.githubusercontent.com/5744908/55679980-64d1ab00-5957-11e9-9f7c-205d58e3eccf.png)

2. When I open the data editor, notice how the bug has changed positions of most of the keys! Seems to even have done some inconsistent sorting, the keys with numbers in them but not the other keys with letters  

![image](https://user-images.githubusercontent.com/5744908/55679779-8e3d0780-5954-11e9-8bad-a087b5582e9b.png)

## Attach a .c3p

[blankWithDictionaryFile.zip](https://github.com/Scirra/Construct-3-bugs/files/3051290/blankWithDictionaryFile.zip)

## Steps to reproduce

1. Open the dictionary data file
2. Click on the key "4"
3. Paste the following data:

menu_options

player_dexterity

enemy_hp

player_strength

enemy_damage

menu_quit

player_intelligence

enemy_poison

menu_start

4. Close the tab
5. Open the data file again

## Observed result

All the data has been rearranged inconsistently!

## Expected result

The data should be sorted consistently, or not at all. Or perhaps should have a button to optionally apply the sort.

For instance, the keys with numbers go together but notice how the keys that start with "enemy" are not grouped after the numbers.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Dictionary objects don't guarantee order, although the behaviour varies depending on what browser your in. So other than UX we won't be able to change much.

The ordering you see is numerical, so it is consistent even if it's not what your expecting. I don't believe we are actually sorting the data, so this might be a browser thing when the data is parsed. You've left your system details empty, as well as the browser details. Could you tell me what browser you are using for this? If it's being reordered when it's parsed then the original order is unfortunately unrecoverable, but we can probably implement a custom sort with a nicer ordering at least.

**Comment by AshleyScirra** [comment]
@shortercode - we should be able to preserve user-edited order so long as the key sequence is preserved when saving and loading to JSON.

**Comment by alastajj** [comment]
This was in Desktop beta editor.

**Comment by shortercode** [comment]
Thanks @alastajj 

It appears that the order is being lost during the serialisation process, which isn't really fixable. One solution is that the key order could be saved to the table customisation data ( row/column sizes ). Going to see how easy that would be.

**Comment by shortercode** [comment]
Okay this should be resolved in the next release. The only issue at the moment is that the customisation data is lost when files are duplicated at the moment, so if you clone a dictionary it will be "sorted". I will look into resolving this as well, but we can close this specific issue I think.

**Comment by shortercode** [comment]
Additional issue has also been resolved for next release.
