### ISSUE TITLE
Drawing Canvas polygon fill artifacts

### ISSUE THREAD

**Issue by oosyrag** [Scirra/Construct-3-bugs#2822]
## Problem description

Certain triangular artifacts appear in recurring positions, multiple positions possible. Can be induced to appear and disappear when resizing the container window/scaling.

## Attach a .c3p

https://www.dropbox.com/s/a8ql38pudrx4y57/canvasbug.c3p?dl=0

## Steps to reproduce

Preview project. Resize browser window until a darker triangular area appears or disappears. Objects can be drag and dropped within the preview to other positions to have the problem appear in different locations. The positions are consistently reproducible from my experiments.

## Observed result

Rendering artifacts occur under various circumstances, breaking the poly fill.

## Expected result

Poly fill should be a consistent fill.

## More details

I have made efforts to avoid drawing an intersecting polygon, although there are concave and convex sections. The fill does render, as opposed to not rendering at all with an intersecting poly, just not correctly.

The array contains two sets of data, y0 is the angle data used to position the lines, and y1 (recorded for debugging) is the angle for the point used to draw the polygon. The polygon points are (or should be) added in the same order as listed in the array.

**Affected browsers/platforms:** Chrome, Win10 and Chrome, Android tested and observed.

**First affected release:** Attempted only in r143

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r143 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.7 gb
Storage usage (approx): 237 mb (3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX 570 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's not clear that this isn't just a bug in your events (i.e. how do you know your events aren't putting a poly point there?) - can you come up with a simpler way to reproduce the problem? Ideally the project should demonstrate a problem without requiring any user input at all, to guarantee we match exactly what you are seeing.

**Comment by oosyrag** [comment]
I have updated the project and reduced the number of points. There were more occurrences when moving things around with a lot of points, so it was easier to see happening.

I was able to check the poly points as they are recorded in the array by pausing in debug mode and did not see any event based mistakes.

It shows up consistently for me every time in the same location without input. It depends on the resolution/window size though, which is unlikely to match across our systems or different platforms, thus I suggested resizing the window until it shows up.

Here is a screen capture https://www.dropbox.com/s/5zzinl1crquyuzg/polybug.PNG?raw=1. Also note the outline does not get drawn to the outside location. 

I'm guessing it has to do with more complex poly shapes only. I would proceed by manually drawing triangles only instead of a single poly with many points as a workaround, but thought this might be worth looking in to.

**Comment by SnipG** [comment]
Min case:(on image you can see case that should not be possible, use mouse to move blue line around)
![Polybuggy](https://user-images.githubusercontent.com/28864889/55754481-6da8a680-5a55-11e9-8766-8615d5ac58d0.jpg)
[PolyBug02.zip](https://github.com/Scirra/Construct-3-bugs/files/3056147/PolyBug02.zip)

**Comment by AshleyScirra** [comment]
Thanks for smaller repro @SnipG. I think this comes down to the polygon decomposition algorithm that breaks up concave polys in to convex ones. When the polygon has colinear points (i.e. multiple points along a straight line) the algorithm seems to break down, presumably due to floating point rounding errors when handling decomposition along points with an internal angle close to 180 degrees. The workaround is to remove colinear points within an angle tolerance, which seems to fix it.

**Comment by SnipG** [comment]
Still happens:
![PolyBug03](https://user-images.githubusercontent.com/28864889/56140212-21a0b900-5fa3-11e9-9a5a-f9237e93d2b7.jpg)

[PolyBug03.zip](https://github.com/Scirra/Construct-3-bugs/files/3080584/PolyBug03.zip)

**Comment by SnipG** [comment]
![PolyBug04](https://user-images.githubusercontent.com/28864889/56140751-2a45bf00-5fa4-11e9-94f0-4a50183415f4.jpg)
[Polybug04.zip](https://github.com/Scirra/Construct-3-bugs/files/3080609/Polybug04.zip)

**Comment by AshleyScirra** [comment]
I can't reproduce any issue with that project. I'm not sure there's anything more we could do about this anyway - if you have colinear points with a concave polygon it's a really difficult problem to accurately break it up in to convex polys.

**Comment by SnipG** [comment]
I played around with it inside editor and saw possible case to over everything is getting very complex. And when it gets complex it's most likely wrong course.
So i just applyed Round(X)  to every polygon X and it fixed the oosyrag original example and mine in R144 and using same thing could not reproduce any bugs in 145 with any example not even once(which all bugged massively before)!!. And there is no artifact to be seen by eye.
So you could revert some complex math with removing some polygon points on streight line etc. And just  ask users to apply round() if users see artifact!! Which seems much more reasonable and less buggy

Original oosyrag example..Try in R144: 
[CanvasPolyBug_Fixed.zip](https://github.com/Scirra/Construct-3-bugs/files/3081285/CanvasPolyBug_Fixed.zip)
My own example in R144: 
[Polybug03_fixed.zip](https://github.com/Scirra/Construct-3-bugs/files/3081293/Polybug03_fixed.zip)



R145: [PolyBug01Fixed.zip](https://github.com/Scirra/Construct-3-bugs/files/3081278/PolyBug01Fixed.zip)
R145: [PolyBug02Fixed.zip](https://github.com/Scirra/Construct-3-bugs/files/3081279/PolyBug02Fixed.zip)
