### ISSUE TITLE
Family UID passed to built-in function is always the lowest UID of all objects in the family

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#2823]
When passing a UID to a new function using the .UID property of a family object, the function is always passed the lowest UID of all the objects in the family. So, if there is a family called "Family1" with placed instances, "Sprite1", "Sprite2", and "Sprite3", with UIDs of 2, 3, and 4, respectively, and a function is passed the UID of one of them using the Family1.UID property, the value of 2 is always passed.

## Attach a .c3p

[BrokenPickingWithFunctionParams.zip](https://github.com/Scirra/Construct-3-bugs/files/3052149/BrokenPickingWithFunctionParams.zip)

## Steps to reproduce

1. Create a family with a sprite object and place a few instances of the sprite in the layout.
2. Create another stand-alone sprite object and set it to the mouse position each frame.
3. Create a new built-in function with a number parameter (for a UID).
4. Add an event to detect collision between the stand-alone sprite and the family.
5. On collision, pass the function the UID of the family object instance that collided with the stand-alone sprite using the .UID property of the family.

## Observed result

No matter which family instance is collided with, the function is only passed the lowest UID of all the family instances.

## Expected result

The function should get the same UID returned by the collision event.

## More details

**Affected browsers/platforms:** Tested in desktop version and Firefox.

**First affected release:** 143

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r143 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 35 gb
Storage usage (approx): 190 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in next release.
