### ISSUE TITLE
Raycast fails to register collision at corners

### ISSUE THREAD

**Issue by oosyrag** [Scirra/Construct-3-bugs#2824]
A raycast at a corner of a solid can fail to register collision, and penetrate to the opposite edge.

## Attach a .c3p

https://www.dropbox.com/s/0ntnizla5ulsbfg/raycastbug.c3p?dl=0
## Steps to reproduce

Open project, preview.

## Observed result

The line cast at the nearest corner sometimes penetrates the object.

## Expected result

The lines should not go through the object.

## More details

**Affected browsers/platforms:** Chrome Win10

**First affected release:** 143

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r143 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.7 gb
Storage usage (approx): 237 mb (3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX 570 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I suspect this may come down to a floating-point precision issue: if you cast a ray *exactly* at a corner of a polygon, given that floating point calculations are imprecise, whether or not it intersects will depend on floating point rounding errors. It may be that you have to work around this by adding a small tolerance (e.g. if you want to guarantee an intersection, cast the ray to a point fractionally inside the object).

**Comment by shortercode** [comment]
@AshleyScirra yes it was exactly that, I expected that there might be a few edge cases like this, so it's good to get a test case.

If a ray intersects EXACTLY the end of the line the segment fraction value should be 1, but was periodically slightly higher due to precision errors. Adding a small threshold value corrected this ( 1 millionth of a pixel ). This theoretically adds a tiny zone around the rectangle which will record as a hit, even though it's not. Given the tiny size I don't think this should cause any issues, and hit positions already reported as outside the collision ( resolves issues with reflections colliding with the origin surface ).

**Comment by shortercode** [comment]
Okay issue should be resolved in next release.

**Comment by SnipG** [comment]
I tested the corner trace hit too, before it could pass trought, but now in certain case and angle i can do it also.
![45degree](https://user-images.githubusercontent.com/28864889/55727250-41bbff80-5a1a-11e9-8750-b5081033eaea.jpg)
