### ISSUE TITLE
Saving to Google Drive: Failed to load resource, no way to stop it, stuck at 0%

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2826]
## Problem description

Using the C3 Web App I saved to my google drive a few times, the last one froze at 0% with the following error regarding google API.

I understand this can happen but a fallback with an error message would be great. I can't save to google drive unless I close the project.

![image](https://user-images.githubusercontent.com/7268697/55724094-5ba61400-5a13-11e9-95ef-7937ff78fbb5.png)

## Steps to reproduce

1. Open up demonoir project
2. Try saving to google drive several times

## Observed result

At some point it will fail with the failed to load resource and the progress status bar will remain at 0%.

## Expected result

I expect to have a message box saying it couldn't save and the progress status bar to disappear so that I can try saving again.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** Noticed it in 142.2 since this is when I started using the save to google drive.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 60 gb
Storage usage (approx): 121 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon 550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I haven't been able to reproduce this, do you have "pause on exception" enabled perchance?

**Comment by JeFawk** [comment]
I do not have it enabled.

![image](https://user-images.githubusercontent.com/7268697/55726868-73809680-5a19-11e9-8cf2-f74ab58d9119.png)

Any more info that I can provide to help with this? Or some way to tracks things? I can open up the console and track the network or something.

**Comment by JeFawk** [comment]
Indeed, it keeps opening up a new window panel to ask for authorization about every 2 hours. 

The bug report I made is not valid in this way, the panel probably opened up in the background or something and I didn't notice it.

**Comment by shortercode** [comment]
Ah yeah so access tokens for Google Drive expire after an hour ( this is a hard limit, and cannot be changed ). So we have to ask for a new one token which required showing the auth window again. I'm not sure why it appeared in the background, but ironically the "windowing" system in Windows can be a little flaky...

We might be able to show a status indicator that C3 is awaiting authentication. If the window is closed it will show a "Authentication cancelled" dialog.

**Comment by shortercode** [comment]
Okay dokes, I've added a status message that should appear next to the "Saving FILENAME to SERVICE [N]%" message when it's waiting on the authentication pop up. Hopefully this should make it more obvious when a sign in window is hiding somewhere... Should be in the next release.
