### ISSUE TITLE
Remote preview freezing when loading 

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2827]
## Problem description

Remote preview about 1 out of 5-10 times freezes from loading.
I loaded Demonoire and started 4 remote previews. I updated the project a few times and refreshed 3 times more (so updated the project about 4 times, refreshed 12ish). 1 out of 4 clients stopped with the Connected to Host and the Client disconnected notification.
![55719892-0b758480-5a08-11e9-836b-7d336f3f8a73](https://user-images.githubusercontent.com/7268697/55725878-44692580-5a17-11e9-9305-b15e5e92ea7f.png)

The console log  for the Demonoir project that didn't load only has "Peer connection established to host".

## Attach a .c3p

Use Demonoir project.

## Steps to reproduce
1. Open the project in the Web App or Desktop version under Windows 10 and using Google Chrome
2. Use Remote Preview
3. Open up a few instances
4. Update the project and refresh the pages
5. Repeat several times

## Observed result

Some clients stop loading.

## Expected result

Expect all clients to load properly.

## More details

**Affected browsers/platforms:** Chrome/

**First affected release:** This issue has been around for a long time, a few months, however it barely happened before ~140 or so, now it's extremely often to the point that from a small annoyance it has started to lower productivity.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 60 gb
Storage usage (approx): 121 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon 550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by JeFawk** [comment]
Anything of value that I can provide from here? I selected the WS data

![image](https://user-images.githubusercontent.com/7268697/55726580-c9087380-5a18-11e9-8502-a82fedd7bf3f.png)

**Comment by AshleyScirra** [comment]
The most important information to provide is any errors that appear in the console tab.

**Comment by JeFawk** [comment]
As stated in the bug report, the console log for the Demonoir project that didn't load only has "Peer connection established to host" unfortunately.

**Comment by kingpirux** [comment]
i had the same issue :(

**Comment by AshleyScirra** [comment]
I can't reproduce this: I had 4x simultaneous remote previews of Demonoire, and successfully edited project  & reloaded all 4 (in as quick succession as possible, so they tended to be loading in parallel), and all 4 successfully loaded every time. I would guess this is either an intermittent networking issue, or the simultaneous reloading is temporarily overloading the system's ability for C3 to serve the connections (reloading multiple remote previews at once is a bit like a mini DDoS). It seems minor anyway - presumably you can just reload the tab if remote preview fails to load and it comes back? I don't think there's anything we can do about this I'm afraid, it seems Construct's code is all working OK.

**Comment by JeFawk** [comment]
If you reload the tab it has a 50%+ chance of working indeed. It might seem minor to you but I'm working on networked games and when I need to test with 8 clients and have to reload half of them a few times to get everyone in with a game of 25mb+ that's a heck of a downtime just pressing F5 and waiting for the load to find it got disconnected.

**Comment by JeFawk** [comment]
This also happens with only 1 remote preview. I had to refresh the same preview 4 times until it worked.
