### ISSUE TITLE
Modify the tabs of opened layouts/event sheets to make it visible which one is opened

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#283]
## Problem description

Not sure if it's a bug or not, more like an overlook or a theme thing. The tabs of opened things (layouts/event sheets) have a barely visible change for the one that's opened. Please take a look at the image below.
It takes me so long time to realize which is opened that I just start clicking them randomly to figure it out. Any possibility of maybe making the text bold like in C2?

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
![image](https://cloud.githubusercontent.com/assets/7268697/26260279/49358bf0-3cd5-11e7-8d6c-b34243862dd7.png)

## Affected browsers

* Chrome: yes
## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by jaydonteh** [comment]
Yes, it's hard to spot when opening lots of tabs at once. I think the screenshot is showing the "[E] Adventure Data" tab as active.

**Comment by JeFawk** [comment]
It does indeed. And it takes way too much time to spot it.

**Comment by AshleyScirra** [comment]
I don't think bold is a good choice because it makes the text wider which affects layout which can have weird consequences (e.g. click a tab and it moves somewhere else because it went bold and no longer fits in the same place).

What styling do you think would be effective that does not alter the size of the tab?

**Comment by jaydonteh** [comment]
I think having a more profound colour would suffice. Maybe Paulo could come up with a better contrast for the active tabs. Or I guess another easier way is to underline the name of the active tab, or create outlines for all inactive tabs.

**_'Main E' is the current active tab._**

![tabsa](https://cloud.githubusercontent.com/assets/20452123/26788873/2e6222c4-4a41-11e7-8801-6608fbfd1cf0.png)

![tabsb](https://cloud.githubusercontent.com/assets/20452123/26789008/88f61664-4a41-11e7-9b34-a8c36940f478.png)

**Comment by JeFawk** [comment]
Bold was a sloppy idea indeed. Maybe underline the text like @jaydonteh suggested?

**Comment by AshleyScirra** [comment]
I'm not sure I like the underline approach, it doesn't distinguish it that much and clutters the text a bit. What if the inactive tabs were made darker to distinguish them more? ![darkertabs.png](https://user-images.githubusercontent.com/768723/26927378-8607d6cc-4c49-11e7-8783-2111d73d5d39.png)

**Comment by JeFawk** [comment]
The tabs have a lot of colors, so won't it be confusing when a darker colored tab is active (say, dark blue) and you have bright tab colors darker? (so normal blue becomes dark blue?) 
I do see the shadow around so it will still be spotted much faster than currently.

![image](https://user-images.githubusercontent.com/7268697/26934474-25963d64-4c72-11e7-8729-5fcf8b15a1d6.png)

On a side note, planning any custom tab coloring that will remember the color after you close and reopen the project?

**Comment by AshleyScirra** [comment]
The tab colors only rotate hue, not lightness, so it doesn't pick dark colors. If the darkest tab color is picked it looks like this: 
![darkertabs2](https://user-images.githubusercontent.com/768723/26936494-bf298eb0-4c66-11e7-91e0-7688505a5402.png)

Does that look reasonable?

**Comment by JeFawk** [comment]
Hue, I get it now. Uhm, to be honest there's not much difference. It's just slightly better than now.

Since inactive tabs get darker, how about setting their name color to white, instead of dark? So only the active one would have a dark name, and due to this possibly making them a tad darker as well for the name to be readable easily.

**Comment by jaydonteh** [comment]
I feel that the darker colours just kills the lovely pastel colours, making C3 a tad bit ugly. That said, there must be another way.

**Comment by JeFawk** [comment]
If we're to talk how we feel, I feel that pastel colors makes it look terrible since the UI has a consistent color theme whilst there's a rainbow on the top of my screen.

**Comment by AshleyScirra** [comment]
I'm open to suggestions, I think this is clearer than the underline but I'm happy to look at any mockups anyone comes up with. I know some people don't like the general appearance but I'm only concerned with making the active tab obvious here. Paulo is working on a full theme which completely changes the editor appearance, so hopefully that will improve the subjective appearance.

**Comment by jaydonteh** [comment]
![tabsc](https://user-images.githubusercontent.com/20452123/26938237-36129a14-4ca6-11e7-84eb-7703eb1d359e.png)

So, I made the inactive tab texts about transparency alpha 50. This is seems to be a nice solution!

**Comment by JeFawk** [comment]
Maybe allow the user to set the opacity % in the settings next to the Icon color? Using a flat number might be making things less visible depending on screen brightness etc. 

People will know what the active tab is, but they'll have to struggle to see the names of the inactive ones.

Something minimalistic like 

![image](https://user-images.githubusercontent.com/7268697/26942978-b342093a-4c8c-11e7-8d82-be4192c723d9.png)


Could work, but yeah, no more random colors in this case so my example is quite irrelevant.

**Comment by AshleyScirra** [comment]
@jaydonteh - that appearance is usually used as a metaphor for disabled items in software UI, so I'd rather use something else.

**Comment by jaydonteh** [comment]
Tbh I wasn't expecting C3 to inherit the colour tabs since many themes for C2 does not have them but it does add some pizazz. If we would to keep everything consistent, I think you should consider minimalistic like what @JeFawk mentioned.

![tabsd](https://user-images.githubusercontent.com/20452123/27031750-21c53d18-4fa4-11e7-94ec-e05166d30d44.png)

Inspired by Firefox Compact Light theme.

**Comment by AshleyScirra** [comment]
r37 is out, do you think the new shading helps?

**Comment by JeFawk** [comment]
This is much better, thank you very much.

![image](https://user-images.githubusercontent.com/7268697/27037266-15372c14-4f90-11e7-9301-1babce05381a.png)

**Comment by jaydonteh** [comment]
@AshleyScirra Gotta say, I'm eager to see what the new overhauled theme looks like!

**Comment by AshleyScirra** [comment]
OK, closing for now. Paulo should have new themes in a few weeks too.
