### ISSUE TITLE
Save-As-Project-Folder doesn't create timelines folder

### ISSUE THREAD

**Issue by pkreemer** [Scirra/Construct-3-bugs#2831]
Desktop build doesn't create "timelines" folder when saving as project folder.

## Steps to reproduce
Unzip project folder project and try to open it.

But to _cause_ this:

1.  Create new empty project,
2.  Save as project folder, 
3.  In Project Bar, add new timeline.
4.  Save project and close C3 IDE.
5.  Launch C3, and,
6.  Try to re-open project.

## Observed result
Error dialog after failing to open project: _Failed to open project. Check it is a valid Construct 3 folder project._
[timlin_test.zip](https://github.com/Scirra/Construct-3-bugs/files/3055434/timlin_test.zip)

The project.c3proj file has a timelines entry saved (see json snippet below), but no timelines folder or [timeline name].json file has been created.

`"timelines": {
		"items": [
			"test"
		],
		"subfolders": []
	},`

## Expected result
Project would be loaded. And in the project folder structure, a timelines folder and any needed .json files should be created at the same time the project.c3proj file is updated with a new timeline.

## More details

**Affected browsers/platforms:** 
NW.js 64-bit build - C3 IDE
Windows Store build - C3 IDE

**First affected release:**  noticed in r143, persists in r144

## System details
Error dialog after failing to open project states: Failed to open project. Check it is a valid Construct 3 folder project.

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r144 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 195 gb
Storage usage (approx): 690 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
There are two different issues here.

The first, where timelines were not saved properly to project folders, is already fixed.

The second issue, where project folders on "Open Recent" menu are not opening because they seem to be pointing to the incorrect path.

**Comment by shortercode** [comment]
@DiegoScirra I have just committed a patch for the open recent problem, could you review if it resolves the problem for you? Assign back to me if additional work needs doing for this issue.

**Comment by DiegoScirra** [comment]
This looks like it is fixed.
