### ISSUE TITLE
Raycast doesn't move past disabled solid

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2832]
## Problem description

When the raycast is set to look past a solid object set to disabled, it still stops at that object

## Attach a .c3p

[RaycastBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3055941/RaycastBug.zip)

## Steps to reproduce

1. Run the game

## Observed result

The raycasting stops when collision is on, no matter if solid is disabled or not

## Expected result

The raycast should move past objects that have solid set to disabled

**First affected release:** r144

**Comment by shortercode** [comment]
Thanks for the report, turned out to be a stealthy typo that caused the raycast to always occur. Should be resolved in the next release.
