### ISSUE TITLE
Spritefont and Text not wrapping by word when applying a tag on every letter

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2834]
## Problem description

When I apply a tag on every letter, the object no longer wraps by word

## Attach a .c3p

[spritefont bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3056864/spritefont.bug.zip)

## Steps to reproduce

1.change the width of both objects
2. The same applies to Text

## Observed result

When every letter has a tag the object doesn't wrap by word

## Expected result

The object should still wrap by word even if surrounded by tags

**First affected release:** Since BBCodes for spritefont and text were introduced

**Comment by AshleyScirra** [comment]
This is really complicated. The BBcode formatting and text layout engine currently fragment text per style, and then processes word wrap on fragments, thereby effectively causing style boundaries to be word wrap breakpoints. Word wrapping across style boundaries introduces complications like the fact a single word can change style, and therefore change size, which in turn requires multiple measurements. This will require a major overhaul of the BBcode/text layout engines.

**Comment by skymen** [comment]
Well if you'd allow me I can try to do it. Since I'm currently making a new version of Spritefont Deluxe for  C3 runtime, having a tag per letter is very common, and so I'd like to be able to make it work without having to force/rewrite wrapping in the behavior.
So if you don't have time to do it at the moment, and would allow me to take a look at the Spritefont plugin, I'd be very interested in making changes to it to try and fix that issue.

**Comment by AshleyScirra** [comment]
The text layout engine is built in to the runtime and shared between Text and Spritefont. I'm afraid we are not prepared to share engine code development at this time.

**Comment by skymen** [comment]
Oh ok no problem then

**Comment by AshleyScirra** [comment]
I had a look at the existing code for this and it might be a bit easier than I thought - hopefully it can be implemented only in the word wrap engine without having to affect any other inputs or outputs. I'll try take a look at it this week.

**Comment by skymen** [comment]
Great! Thanks

**Comment by AshleyScirra** [comment]
OK, this was pretty complicated and involved a rewrite of the word wrapping engine, but wasn't quite as bad as I initially thought (the change is only to the word wrap internals, the inputs and outputs stay the same). It should be fixed in the next release - hopefully the new code is backwards compatible... (I did test it carefully but there are lots of edge cases!)

**Comment by skymen** [comment]
Thank you very much. I'll be sure to tell you if I come accross any issue with that
