### ISSUE TITLE
Anchor behaviour glitched with "bottom edge: viewport bottom" and bottom origin

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#2836]
## Problem description
When the bottom edge is anchored to bottom and the object's origin is set to bottom/bottom-left/bottom-right, the object will not stay at the bottom when window is resized taller/narrower.

## Attach a .c3p

[AnchorBug3.zip](https://github.com/Scirra/Construct-3-bugs/files/3059009/AnchorBug3.zip)

## Steps to reproduce

1. Open attached project file.
2.  Preview.
3. Resize the preview window narrower/taller.

## Observed result
object does not anchor to the bottom but rather became taller.

## Expected result

Anchors to the bottom.

## More details
After the glitch fix on #2753, this bug appeared.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r144 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.8 gb
Storage usage (approx): 940 mb (11.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think this is the same issue as #2835 (objects with non-top-left origin grow in the wrong direction), so closing as duplicate.

**Comment by jaydonteh** [comment]
Just a note, this particular issue I submitted was to address the position of the object not being anchored to the bottom of the screen, while the issue #2835 is more of wrong width.

**Comment by jaydonteh** [comment]
@AshleyScirra This is still occurring. The object just stretches and becomes taller. It should just stay the same height.

**Comment by AshleyScirra** [comment]
I think it's working correctly. Anchoring the right and bottom edges is intended for resizing the object according to the viewport size. If you just want to keep it the same distance from the viewport bottom without changing height, anchor the top edge to the viewport bottom.
