### ISSUE TITLE
Moving objects in the project bar may also move other bars.

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2837]
## Problem description

Moving objects in the project bar may also move other bars. In this example I tried to move the "eve_gameplay" file, but I also started to move the layer bar around.
https://i.imgur.com/wqRKsT8.gif

## Attach a .c3p

Not needed.

## Steps to reproduce

1. Try to move any object in the project bar that's close to another bar.

## Observed result

Moving objects in the project bar may also move other bars.

## Expected result

Only one aspect of the editor to be interactable at time.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Looks specific to the dark/light themes as it doesn't reproduce in default theme. Found a workaround for next release.

**Comment by BonzerKitten7** [comment]
Thanks for the quick fix.
