### ISSUE TITLE
[SDK][C3Runtime] c3_callFunction does not handle multiple parameters correctly for new built-in function.

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#2838]
## Problem description

c3_callFunction SDK does not handle multiple parameters correctly for new built-in function.

## Attach a .c3p
[FunctionCall.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3061634/FunctionCall.c3p.zip)

Since this is a SDK issue. This project includes a bundled plugin. The plugin is the JS plugin which allows easy testing of the C3 SDK. No parameters are passed from the JS plugin to the JS. The c3_callFunction call is made from JS. See the project JS file 'func.js'.

Remove 'zip' from file to use.

## Steps to reproduce

1. Load project file (includes bundled plugin.)
2. Run project file with preview.
3. Look at log (and console log.)

## Observed result

Log shows that the first parameter includes the first, second and third parameters. The second and third parameters are not passed through as numbers (the log show NaN for the second and third parameters.)

## Expected result

The first, second and third parameters should be passed separately to the function defined in the event sheet.

## System details

Mac 10.14
Chrome 73+

**Comment by AshleyScirra** [comment]
Fixed for next release. As per the bug report guidelines please try to avoid using third-party addons in bug reports - this could have been reproduced using the Browser object's 'Execute JS'.

**Comment by MikalDev** [comment]
Thanks Ashley. Will use browser exec in the future, if it alone can replicate the issue.
