### ISSUE TITLE
Audio doesn't play in exported APK

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#2841]
## Problem description

Music doesn't play in exported debug APK. But works perfectly on PC preview.

## Attach a .c3p

Provided to the support.

## Steps to reproduce

More info in ticket

1.
2.
3.

## Observed result

Doesn't play

## Expected result

To play.

## More details

**Affected browsers/platforms:**  Chrome/Android

**First affected release:** 144

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines regarding filing issues, in particular we need a minimal project to be able to help. If it's not a mistake in your events and music really does not play, it should be easy to reproduce in a new project.
