### ISSUE TITLE
Nw.js reading json string from file for tilemap object fails with C3 runtime but works with C2 runtime.

### ISSUE THREAD

**Issue by MichaelVParent** [Scirra/Construct-3-bugs#2842]
## Problem description

I've made a 1 event project that simply loads a .json file into a tilemap object. It works when exported from C2 or from C3 using trhe C2 runtime, but it fails to load the json data from the file if you export it using the C3 runtime.

## Attach a .c3p

c3p file and json file attached in a zip.

## Steps to reproduce

1.export the project from C3 (or C2) using the C2 run-time 
2. add THIS.json file in the resulting run-time folder (I'm only testing with Windows 64 bit) and when you run the .exe you'll see the map data sucessfully loads from the .json file.
3. Repeat this using the C3 runtime and see that when you run the program it no longer sucessfully loads and displays the json data into the tilemap object.

## Observed result

The resulting app successfully loads the tile-map data from the Json file only using the c2 runtime and fails if it's using the C3 runtime.

## Expected result

The app should sucessfully load and display the map-data from the .json file regardless of the runtime used.

## More details
I can't think of anything else worth mentioning

**Affected browsers/platforms:** 

NW.js (I'm testing Windows 64 bit only)

**First affected release:** 
I'm not sure how far back this problem goes.

## System details

Windows 10 64 bit
[TilemapBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3065546/TilemapBug.zip)

**Comment by MichaelVParent** [comment]
UPDATE!
Upon further experimenting, this problem occurs when trying to set the tilemap from a global string value as well, from any browser or via NW.js. It works perfectly fine using the C2 runtime and fails with the c3 runtime, so it seems to have nothing to do with reading files or NW.js, and has to do with the tile-map object failing to properly read the json data.

**Comment by AshleyScirra** [comment]
The JSON data is the full tilemap object state (AsJSON expression), instead of just the tile data (TilesJSON). In the move to the C3 runtime, the object state data format changed, but the tiles data format did not. Since you're trying to load C2 runtime object data in to the C3 runtime it detects it's invalid and skips loading. I suggest just saving the tiles data instead so you don't rely on the full object state data.
