### ISSUE TITLE
Spritefont doesn't update when changing line height

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2845]
## Problem description

In the editor when changing line height of a spritefont object, it doesn't update the instance.

## Attach a .c3p

n/a

## Steps to reproduce

1. Add a spritefont object
2. Change line height

## Observed result

The object doesn't update with he new line height

## Expected result

The object should update with the new line height

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
