### ISSUE TITLE
duplicate functions not deleting

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#2846]
There is a bug in my project that i can't isolate.

I created a function (no return value) and called it.
Then i copied it, renamed it and altered some of the code, but construct it still showing the duplicate functions even though they no longer exist (have been renamed) and are not being called anywhere.

![Screen Shot 2019-04-13 at 10 26 14](https://user-images.githubusercontent.com/30123541/56077648-9ffc3000-5dd6-11e9-940d-f1757b7a7f9e.png)

In the above screenshot function "checkEachTileInMoveRange2" was a copy and was renamed to "checkAIPath" but construct is still showing them both even though "checkEachTileInMoveRange2" no longer exists. Also "getCharsMoveRange2" was deleted completely from the project.

Doing a search for events using the function yealds 0 results.

![Screen Shot 2019-04-13 at 10 35 19](https://user-images.githubusercontent.com/30123541/56077753-e00fe280-5dd7-11e9-87b9-e6aeb99799ba.png)

## Steps to reproduce

1.
2.
3.

## Expected result

function should not be there to be called.

## More details

**Affected browsers/platforms:** 

Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r144 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 573 mb (0.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm sorry, there's nothing we can do without steps to reproduce, or at least a project we could look at. Please always follow the bug report guidelines to ensure we can investigate.
