### ISSUE TITLE
Unclear errors in the console

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2847]
## Problem description

I write addons, and I often get crashes in the editor due to something I forgot to do in the addon I'm writing. Usually when I write addons, I do it in a separate C3 instance free of anything else that might cause an error. However, when I'm working with multiple addons, or if I have installed lots of other addons, and an error occurs, I have litterally no idea what plugin is causing the error.
![image](https://user-images.githubusercontent.com/11213825/56092045-32740080-5eb7-11e9-8c21-2d0cfda8266e.png)

Please make these error more clear by adding at least the name or ID of the concerned addon.

## Attach a .c3p

n/a

## Steps to reproduce

n/a

## Observed result

A cryptic error message occurs and I can't know what addon is causing the issue.

## Expected result

I'd like to be able to know what addon is faulty to be able to fix it, instead of having to try out all 70 addons I have installed.

## More details
In fact, other error messages are very unclear. Another exemple of this is the error you get when trying to open a file from a future version. It does a console.error saying that the file is from a future version, but the error dialogue that appears just says "failed to open file". Most users would think this might be because the file got corrupted overnight, but the truth is they just worked on the file on latest beta to try a new feature and the next morning they opened the default editor link which goes to the latest stable and didn't realise their mistake.

**Comment by AshleyScirra** [comment]
Well, in the case of missing file errors, the 404 errors that accompany it should point to the exact file including the addon path in the URL... but I went through and added the addon ID to more error messages anyway for the next release.
