### ISSUE TITLE
Build failed Signed apk

### ISSUE THREAD

**Issue by eonianvr** [Scirra/Construct-3-bugs#2849]
## Problem description
When I try to generate a signed apk in construct R144 it failed with the following message:
Error failed to load signer "signer #1": tmp/5ca5a192-4701-4d35-b787-4b604f691001 entry "ashandthelittleflame" does not contain a key

## Attach a .c3p
https://drive.google.com/file/d/1oz7UpIGLOxzu7xxhFGZ5p-gADg2EOJmN/view?usp=sharing

## Steps to reproduce

1. open project
2. export as signed release apk
3. create a keystore
4. choose the keystore file generated
3. export as signed release apk

## Observed result

error message at the end of the export process
Error failed to load signer "signer #1": tmp/5ca5a192-4701-4d35-b787-4b604f691001 entry "ashandthelittleflame" does not contain a key
## Expected result
to generate a signed release apk for android

## System details
Chrome Version 73.0.3683.103 (Official Build) (64-bit)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Have you previously used this keystore to produce a build? This is a standard error message either when your keystore is invalid, or you have provided the incorrect key name when.

**Comment by eonianvr** [comment]
when the first i generated a keystore file  inside construct3 i got the error message when I tried to create a signed apk with it. i generated a new one twice with the same result.
How the keystore can be invalid when you are the one generating it from scratch. Did I miss something?
From what you wrote, it seems the key name needs to match something somewhere else?

**Comment by shortercode** [comment]
When creating the key you are asked to provide a name for it, you have to provide that exact same name when you wish to use it. If the name doesn't match it will tell you that it cannot find a key with the given name. Normally people call the key something like "publish" or "production".

**Comment by eonianvr** [comment]
I'm not sure what you are referencing to or where but I did make sure in a new test that the Key Name in the cordova option window match the alias when creating the keystore folowing your answer above.

I clicked the next button after the new keystore was created and associated with the button choose, and end up with this failed built error message
[failed build capture screenshot](https://drive.google.com/file/d/1Tizy9Kgu2as9WCdwTVkiky2WDeoMjtva/view?usp=sharing)

Is it related? or something completely new?

thank you for your quick response as always!

**Comment by eonianvr** [comment]
I was able to create a signed apk but the failed build error seems to be related to mobile IAP object. As soon as I add it to the project I get this error. Should I open a new ticket about it?

**Comment by eonianvr** [comment]
it seems to be the same problem that was closed on
https://github.com/Scirra/Construct-3-bugs/issues/2514

**Comment by shortercode** [comment]
@eonianvr sorry about any issues you had with the build service yesterday, we were performing some server upgrades that caused builds to fail for awhile. There is still a lingering issue with MobileIAP which I am looking into.

**Comment by eonianvr** [comment]
thank you Shortcode. Really appreciate construct and the awesopme job you are doing on it.  Hope you will find how to fix the mobile IAP quickly and without too much trouble. let me know when it is solve that I can test a buld again.

**Comment by eonianvr** [comment]
any new on the bult problem related to the Mobile IAP? thank you

**Comment by shortercode** [comment]
@eonianvr I've performed a temporary change to the server to allow projects including MobileIAP to build again. So you should be to try this again now.

**Comment by eonianvr** [comment]
seems to be working now! Thanks shortercode!
