### ISSUE TITLE
Crash on attempts to export to windows ump

### ISSUE THREAD

**Issue by Dimostic** [Scirra/Construct-3-bugs#285]
## Problem description
Attempts to export game to windows ump results in error message
*Enter a concise description of your problem here*

## Attach a .c3p

[MOBILE PALPATE MD.zip](https://github.com/Scirra/Construct-3-bugs/files/1015395/MOBILE.PALPATE.MD.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.clicked on menu, then
2.clicked on export then,
3.clicked on windows and Xbox(ump)

## Observed result
error message as outlined below
*What do you see happen?*

## Expected result

*What did you expect to happen instead?*
Completed export
## Affected browsers

* Chrome: yes/no Yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Failed to fetch @ TypeError: Failed to fetch
Stack: TypeError: Failed to fetch
Construct 3 version: r29.2
URL: https://editor.construct.net/index.html
Date: Fri May 19 2017 20:38:47 GMT+0100 (W. Central Africa Standard Time)
Uptime: 526.5 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Works fine for me. The error message suggests a network request failed. Maybe try checking you're online.
