### ISSUE TITLE
Spritefont not respecting character spacing when having tags between letters

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2850]
## Problem description

This is a very similar problem to https://github.com/Scirra/Construct-3-bugs/issues/2834 so it might already have been fixed. Basically character spacing is set to 0 between tag groups

## Attach a .c3p

[spritefont bug (1).c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3079979/spritefont.bug.1.c3p.zip)

## Steps to reproduce

1. Create spritefont
2. Add lots of tags
3. Change character spacing

## Observed result

spacing behaves like it's set to 0

## Expected result

Spacing should not behave like it's set to 0 when it's not

## More details
I'm guessing that this is caused by the same issue in the wrapping engine so I hope that you fixed it already, but just in case, here's the bug report

**Comment by skymen** [comment]
Tried with r145, the bug is still here

**Comment by AshleyScirra** [comment]
It's a slightly different issue, character spacing was not being applied across style boundaries. Should be fixed in the next release.
