### ISSUE TITLE
Functions don't automatically rename occurrences in expressions

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2851]
## Problem description

This was a tough one to reproduce. Basically there is a specific case where renaming a function doesn't rename the occurrences of it.
![image](https://user-images.githubusercontent.com/11213825/56131795-5c452a00-5f80-11e9-8df7-7bc65f6bf6c1.png)

## Attach a .c3p
[Functions bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3080009/Functions.bug.c3p.zip)

## Steps to reproduce

1. Create a function with a return value
2. Call it from anywhere in the project **in an expression**
3. Cut and paste the function
4. Rename the function

## Observed result

Where you called the function doesn't update and is still calling the old function
Running the game like this results in a blackscreen and an error stating it can't get the event block from null (aka the function it was trying to call)

## Expected result

The functions in expressions should behave like the direct function calls and get updated.

## More details
This happened to me when working on my game and I wanted to move the functions for the player in their own event sheet and then rename them following the Player_Function convention.

**Comment by skymen** [comment]
Tried with r145, still happens and worst thing is that this actually corrupts the project, so I'm guessing that you won't be able to open the c3p I linked

**Comment by AshleyScirra** [comment]
Thanks for the report, it's an important catch. The issue is actually just that if you delete a function block (and 'cut' deletes the selection too) the expression references are left behind when they ought to be removed. This is fixed for the next release and also fixes the cut-paste case.

BTW please don't attach corrupt projects to bug reports - they're not useful. We need the originally working project to diagnose how it became corrupt.

**Comment by skymen** [comment]
Hi, sorry I only realised it was corrupted after trying it in r145. Also I figured that the state before being corrupt was a blank project with one function call so I didn't send another c3p file. I'll make sure to do it next time I get something like that though.
