### ISSUE TITLE
Today. There was a critical error when building the application in XCode

### ISSUE THREAD

**Issue by Madiosn** [Scirra/Construct-3-bugs#2853]
## Problem description

Critical error when converting to Xcode

## Attach a .c3p
I did not attach the project, because the error goes with any project even with a test on the site from the examples.

## Steps to reproduce

1. Turning a project into Xcode
2. ios build xCode
3. opens the Xcode project
4. Run the build

## Observed result
pic.
https://yadi.sk/i/wtH2L-yjtsoLsw

Log fail:
https://yadi.sk/d/gwmvCvIytexBPw

## More details

The problem appeared today after the release of the new version. But I did not use the new version I work in version r142

**Affected browsers/platforms:** 

I work in XCode latest version on Mac pro. And in the morning everything worked.
**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
The server was down for some maintenance today while updating to cordova 9, unfortunately a critical issue was discovered with it so we were forced to downgrade again until it can be resolved. Apologies for any delays this has caused you, you should find everything functional again for now.

**Comment by Madiosn** [comment]
> The server was down for some maintenance today while updating to cordova 9, unfortunately a critical issue was discovered with it so we were forced to downgrade again until it can be resolved. Apologies for any delays this has caused you, you should find everything functional again for now.

Is there an approximate understanding of when the problem will be solved? At least in days? What could I plan for the release of my game?

**Comment by shortercode** [comment]
Yeah as I said it's back up now :)

It wasn't obvious there was a problem initially, as it didn't occur on all projects. Once we were sure that it couldn't be quickly resolved we reverted back to the old version. We try to minimise downtime on the server, as we know people rely on it.  It appears to be stable for now, but if you do discover any build issues please let us know.
