### ISSUE TITLE
Crash when deleting an object and then after action cancel

### ISSUE THREAD

**Issue by DieppedalleDavid** [Scirra/Construct-3-bugs#2854]
## Problem description

Crash when deleting an object and then after action cancel

## Attach a .c3p

https://drive.google.com/open?id=1--hrTXEhOxBGnDH6P9RnL4oRos40k2V1

## Steps to reproduce

Create objects, put them on the scene, select all objects from the list on the right, delete them, cancel!

-----------------------------------------

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃoE' of null @ TypeError: Cannot read property 'ǃoE' of null at i.ǃoE (https://editor.construct.net/r145/main.js:2:445226) at https://editor.construct.net/r145/components/bars/projectBar/projectBar.js:1:21825
Stack: TypeError: Cannot read property 'ǃoE' of null at i.ǃoE (https://editor.construct.net/r145/main.js:2:445226) at https://editor.construct.net/r145/components/bars/projectBar/projectBar.js:1:21825
Construct 3 version: r145
URL: https://editor.construct.net/r145/
Date: Mon Apr 15 2019 19:54:50 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 487.7 s

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r145 (beta)
Language setting: fr-FR

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
I can't reproduce based on the steps to reproduce provided: pressing 'Cancel' at the delete confirmation does not perform deletion of the selected objects, and in fact does nothing, so is not surprising this does not cause a crash. I can reproduce though if you proceed with deletion and then press "Undo", which is what I think you meant, and matches the crash report. This is why you should always try to follow the bug report guidelines thoroughly and not skip anything or assume it's obvious. Fixed for next release.
