### ISSUE TITLE
Android Build Crashes when using MobileIAP

### ISSUE THREAD

**Issue by sam467** [Scirra/Construct-3-bugs#2855]
## Problem description

I am trying to build Android app with mobile IAP and it crashes the build and gives error dailog I also tried using phonegap but its same there. I thought my project is having some issue so  i build a sample project just MobileIAP plugin but again it crashed. I am using construct 3 build 142.2 also i tried to use the beta 145 but the result is same

## Attach a .c3p

https://mega.nz/#!O9ZzkIoS!DKI76dYWhMonnyNmuuLe5lHOTgJMGidsoekAt1gW9Iw

## Steps to reproduce

1. Open project
2. Press F6 to build
3. Choose Android (cordova)
4. Crash

## Observed result

A pop-up frame with a crashlog

## Expected result

Build APK successfully

## More details

I tested on firefox, chrome and safari all had same error

**Affected browsers/platforms:** 

**First affected release:** first started happening in r142.2

## System details

Platform information

Browser: Firefox
Browser version: 66.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
C3 release: r142.2 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 18 mb (0.9%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    ImageBitmap support is disabled in Firefox due to bug 1472194
    CSS containment is not supported. Editor performance may be significantly degraded.
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmap is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro K2100M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

</details>

**Comment by shortercode** [comment]
I believe this is related to the server upgrade we attempted yesterday, we discovered a critical bug the new version so had to downgrade. But I believe the version we downgraded to was still slightly newer than we had been previously using, and is obviously clashing with the mobileIAP plugin. You may have more success on PGB if you try a slightly older version ( 8.0.0 should work correctly ).

https://build.phonegap.com/current-support

I will look at finding the issue with mobileIAP so that it works on cordova 8.1+

**Comment by sam467** [comment]
Hey I tried 7.1.0, 7.0.1 and 6.5.0. But nothing works its crashing the build on phonegap too

**Comment by antares330** [comment]
Do we have an ETA on when the build server will be working? or should I try to export some other way?

**Comment by ArtRow** [comment]
I have this issue with IAP plugin as well. It started yesterday. Hope you'll fix it. Thanks!

**Comment by kingpirux** [comment]
i think is the same issue with r145 
![imagen](https://user-images.githubusercontent.com/6506303/56311638-e9c17f00-6124-11e9-95ed-9a6fd26c821a.png)

**Comment by sam467** [comment]
Yes its same issue no matter which version you try to use. Hope it will get solved soon

**Comment by kingpirux** [comment]
hope so because is affecting the stable releases as well :(

**Comment by eonianvr** [comment]
should close my bug report since I mentionned it too as i discovered it trying to solve a signed apk problem
https://github.com/Scirra/Construct-3-bugs/issues/2849
Glad I'm not the only one trying to use mobile IAP!

**Comment by shortercode** [comment]
We've rolled back the server to the same version of cordova we were previously using for the time being, so all builds should be working correctly now. ( I've checked this myself, but if anyone else is having issues please let us know ).

I expect this issue will return when we do successfully upgrade to cordova 9, but hopefully we can patch the plugin so that it works with both.

@eonianvr if you have managed to resolve your signing problem then you can close your issue.

**Comment by kingpirux** [comment]
what i noticed is the tremendously drop on upload speed :P ¿that's for the new server or for overload?

**Comment by AshleyScirra** [comment]
Networking speed depends on every device on the internet between you and the server, so it could be nothing to do with the server.

**Comment by kingpirux** [comment]
> 
> 
> We've rolled back the server to the same version of cordova we were previously using for the time being, so all builds should be working correctly now. ( I've checked this myself, but if anyone else is having issues please let us know ).
> 
> I expect this issue will return when we do successfully upgrade to cordova 9, but hopefully we can patch the plugin so that it works with both.
> 
> @eonianvr if you have managed to resolve your signing problem then you can close your issue.

working fine now! :D

**Comment by kingpirux** [comment]
> 
> 
> We've rolled back the server to the same version of cordova we were previously using for the time being, so all builds should be working correctly now. ( I've checked this myself, but if anyone else is having issues please let us know ).
> 
> I expect this issue will return when we do successfully upgrade to cordova 9, but hopefully we can patch the plugin so that it works with both.
> 
> @eonianvr if you have managed to resolve your signing problem then you can close your issue.

it exports but Android Studio fails on build with:
Could not find method leftShift() for arguments [build_30r7rop0inymues98q2h9ui5d$_run_closure6@739db225] on task ':app:cdvPrintProps' of type org.gradle.api.DefaultTask.

**Comment by shortercode** [comment]
The changes haven't touched the upload system, so any speed variations are unrelated. Doesn't look like the server is currently overloaded, so it's probably just something between you and the server as @AshleyScirra said.

Not sure what the leftShift issue is about, probably related to specific gradle versions. You might be able to resolve it by upgrading gradle, or it might be that your having the opposite problem ( gradle is too new).

**Comment by kingpirux** [comment]
> 
> 
> Not sure what the leftShift issue is about, probably related to specific gradle versions. You might be able to resolve it by upgrading gradle, or it might be that your having the opposite problem ( gradle is too new).

thats right, i found the problem is gradle 5.1.1, i didnt have any issue with 4.10 but now (this is new) Android Studio force you to use 5.1 and it breaks everything :( luckly i just jump all the updates and skip all the automatic gradle upgrade and force it to use 3.2 and it worked again.
But you should start checking that too, upgrade gradle system.
