### ISSUE TITLE
spelling mistake in manual

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#2856]
## Problem description

The first paragraph contains the word "encoutnered".

https://www.construct.net/en/tutorials/multiplayer-tutorial-concepts-579/page-9

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed. Note it's a tutorial, not the manual.
