### ISSUE TITLE
Can't fill or paint objects in Animations Pane

### ISSUE THREAD

**Issue by kclinch** [Scirra/Construct-3-bugs#2857]
## Problem description

<When creating objects in Construct 3, the Animations Pane will not let you fill or paint objects. Not all of my students are having this issue, only a handful.

It won't let me attach the gamefile.

## Steps to reproduce

1. Double click on the PorkChop object 
2. Try to fill the square with a color
3. Doesn't work

## Observed result

Nothing happens

## Expected result

Should have colored pink

## More details

 Tested on Chrome.

**Affected browsers/platforms:** 

**First affected release:** 

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
@kclinch

To attach a c3p project file change it's extension to .zip, github does not allow to upload files with the extension .c3p.

**Comment by kclinch** [comment]
Thanks!

[pork chop the pig.zip](https://github.com/Scirra/Construct-3-bugs/files/3085878/pork.chop.the.pig.zip)

**Comment by DiegoScirra** [comment]
Have you checked the Alpha value of the selected color?

If it is 0, the color is fully transparent, so it would look like none of the tools are doing anything if you try to draw on top of an image which is already transparent.

**Comment by DiegoScirra** [comment]
@kclinch

You might also want to check the luminance slider, which is right below the color picker.

If it is all the way to the left, the color will always be black, and if it is all the way to the right, the color will always be white.

**Comment by kclinch** [comment]
It was the Alpha value! Thank you so much!
