### ISSUE TITLE
[???] ease option in timeline bar

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2858]
## Problem description

There is an [???] option in the timeline bar for easing and for path modes
![image](https://user-images.githubusercontent.com/11213825/56238452-dd8ae280-608e-11e9-969e-9d554255d9e4.png)

## Attach a .c3p

n/a

## Steps to reproduce

1. Open timeline
2. Add instance
3. Switch to easing or path modes

## Observed result

The last easing function is [???] and Linear gives [???] in the bar. Hitting play crashes the editor

## Expected result

Uh. That should not happen.

**Comment by DiegoScirra** [comment]
Fixed for the next beta release.  The additional entry shouldn't appear in the first place.
