### ISSUE TITLE
Creating a timeline by right clicking a subfolder creates it at root

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2859]
## Problem description

Creating a timeline by right clicking a subfolder creates it at root of the timeline folder

## Attach a .c3p

n/a

## Steps to reproduce

1. Create a subfolder in the timeline folder
2. Right click on it
3. Create timeline

## Observed result

The timeline gets created at the root of the folder

## Expected result

The timeline should be created in the subfolder.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
