### ISSUE TITLE
[r29.2] Crash when deleting objects that were in a previously-deleted Family

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#286]
## Problem description

If you delete a Family and then delete the object that was in the Family, the editor crashes.

## Attach a .c3p

[DeletionCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/1015550/DeletionCrash.zip)

## Steps to reproduce

1. Open a project containing a Family.
2. Delete the Family.
3. Delete the object(s) in the Family.

## Observed result

The editor crashes.

## Expected 

No crashes.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃmn' of undefined @ TypeError: Cannot read property 'ǃmn' of undefined at window.ǃVH.ǃLT (https://editor.construct.net/r29-2/components/bars/projectBar/projectBar.js:1:9153) at Array.ǃE.ǃC.ǃw.ǃC.ǃA.ǃN.c (https://editor.construct.net/r29-2/components/bars/projectBar/projectBar.js:1:1429) at ǃC.Event.ǃm$A.ǃm$k (https://editor.construct.net/r29-2/main.js:2:285365) at window.ǃJDv.dispatchEvent (https://editor.construct.net/r29-2/main.js:2:283755) at window.ǃJDv.ǃCyZ (https://editor.construct.net/r29-2/main.js:162:39499) at ee.ǃCUt (https://editor.construct.net/r29-2/main.js:61:150936) at ee.ǃCUt (https://editor.construct.net/r29-2/main.js:61:172898) at ee.ǃCP_ (https://editor.construct.net/r29-2/main.js:61:173030) at ie.ǃCUt (https://editor.construct.net/r29-2/main.js:61:159886) at ie.ǃCUn (https://editor.construct.net/r29-2/main.js:61:69027)
Stack: TypeError: Cannot read property 'ǃmn' of undefined at window.ǃVH.ǃLT (https://editor.construct.net/r29-2/components/bars/projectBar/projectBar.js:1:9153) at Array.ǃE.ǃC.ǃw.ǃC.ǃA.ǃN.c (https://editor.construct.net/r29-2/components/bars/projectBar/projectBar.js:1:1429) at ǃC.Event.ǃm$A.ǃm$k (https://editor.construct.net/r29-2/main.js:2:285365) at window.ǃJDv.dispatchEvent (https://editor.construct.net/r29-2/main.js:2:283755) at window.ǃJDv.ǃCyZ (https://editor.construct.net/r29-2/main.js:162:39499) at ee.ǃCUt (https://editor.construct.net/r29-2/main.js:61:150936) at ee.ǃCUt (https://editor.construct.net/r29-2/main.js:61:172898) at ee.ǃCP_ (https://editor.construct.net/r29-2/main.js:61:173030) at ie.ǃCUt (https://editor.construct.net/r29-2/main.js:61:159886) at ie.ǃCUn (https://editor.construct.net/r29-2/main.js:61:69027)
Construct 3 version: r29.2
URL: https://editor.construct.net/index.html
Date: Fri May 19 2017 13:56:29 GMT-0700 (Pacific Daylight Time)
Uptime: 152.8 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r30.
