### ISSUE TITLE
Crashing on timeline doesn't save when hitting save open projects

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2860]
## Problem description

In issue https://github.com/Scirra/Construct-3-bugs/issues/2858 I describe a problem with the timeline that can end up in a crash. when hitting save open projects, the editor doesn't actually save anything but instead downloads the latest saved version

## Attach a .c3p

n/a

## Steps to reproduce

1. Reproduce https://github.com/Scirra/Construct-3-bugs/issues/2858 with the ease function **without saving**
2. Hit play on timeline
3. Hit Save open project
4. Open saved project

## Observed result

The saved project is the latest save made before the crash

## Expected result

It should save the project

## More details

This might be a weird one as saving a timeline crash might or might not end up in corruption, I can't know.

**Comment by DiegoScirra** [comment]
#2858 is now fixed, so this should be fixed aswell.
