### ISSUE TITLE
r???-r145 / 'Sort Z order'-action does not run when run 'Every X seconds'

### ISSUE THREAD

**Issue by Kramdos** [Scirra/Construct-3-bugs#2861]
## Problem description

The System 'Sort Z order'-action will not run if it is run 'every X seconds' in r145.

## Attach a .c3p

[zSortEveryXSeconds.zip](https://github.com/Scirra/Construct-3-bugs/files/3087101/zSortEveryXSeconds.zip)

## Steps to reproduce

1. Toggle disabled for each test in the .c3p. and see if the colored blocks sort themselves.

## Observed result

zOrder doesn't run at all, the colored blocks don't sort themselves.

## Expected result

All the colored block be sorted by their Y position every X seconds.

## More details

Only tested in r145 in Chrome.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r145 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 3.7 gb
Storage usage (approx): 423 mb (11.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 690 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The problem is only that 'Sort Z order' does not cause the screen to be redrawn. If anything else about the game is changing at all it will redraw and update (including resizing the window). However if nothing is changing and the only change is 'Sort Z order' it did not update. Fixed for next release.
