### ISSUE TITLE
Deleting timeline doesn't delete actions

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2862]
## Problem description

When I delete a timeline, it doesn't delete the actions and conditions referring to that timeline

## Attach a .c3p

n/a

## Steps to reproduce

1. Create timeline and add timeline object
2. Call "Play timeline" in events
3. Delete timeline

## Observed result

The action stays there. Opening the action says that there aren't any timeline updates it to the right status

## Expected result

The action should get deleted automatically.

## More details
It doesn't seem to be producing any crash when trying to play a timeline that doesn't exist.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
