### ISSUE TITLE
Function Parameters don't fit dark theme

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2863]
Function parameters don't seem to be following the dark theme style, they're unusually bright.

![image](https://user-images.githubusercontent.com/5744908/56265029-c6e69900-612b-11e9-8be4-2ef6e1d90f47.png)

Look at the difference between the local variables at the top, and the function parameters near the bottom of this image.

**Comment by alastajj** [comment]
@Animmaniac

**Comment by alastajj** [comment]
Affects the highlighting too, notice the orange here, it's different than normal event/variable highlighting:

![image](https://user-images.githubusercontent.com/5744908/56266411-78d39480-612f-11e9-8a27-cf8d3f835110.png)

This is slightly related to #1358

**Comment by AshleyScirra** [comment]
@Animmaniac - probably just need to apply event variable styles to the function parameter elements with an additional selector.

**Comment by Kramdos** [comment]
Adding a +1 to this, hoping it is an easy change.

**Comment by QuasarX** [comment]
@AshleyScirra Can you change white color in dark theme please. This is really hurts eyes.

![image](https://user-images.githubusercontent.com/13033837/59876892-5c610c00-93ad-11e9-88ca-b7befd666b79.png)

**Comment by AshleyScirra** [comment]
Note the next release (r173) just applies the event variable styles to function parameters as a short-term fix, but leaving open for @Animmaniac to review since he may well want to make changes to the styling.

**Comment by AshleyScirra** [comment]
I don't think this will be changed in the near term, and since the report the design was changed to be more appropriate, so closing.
