### ISSUE TITLE
"Advanced audio supported" condition available only in C2 legacy and still present in a C3 runtime example

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2864]
## Problem description

The audio condition "Advanced audio supported" is only available in the C2 runtime legacy.
Nevertheless, the intermediate example "Microphone input", being a C3 runtime example does display this condition.
As reported in this forum topic (https://www.construct.net/en/forum/construct-3/general-discussion-7/advanced-audio-supported-143288) double clicking the condition opens the condition dialog in which the condition is not available, causing some confusion.

## Steps to reproduce

1. Open the intermediate example "Microphone input"
2. Double click event 2 condition "is not Advanced audio supported"

## Observed result

Notice the condition is not available.

## Expected result
In Construct : If used as part of a C3 runtime example, perhaps the condition should be available for the C3 runtime anyway ? Perhaps this is an actual bug ?

If not a bug, in the manual article : Possibly a label "C2 legacy runtime only" next to the condition.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I've updated the example for the next release to not use any deprecated features. I also updated the Audio Analyser example which worked similarly.
