### ISSUE TITLE
Invalid project name causes build failure

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#2865]
## Problem description

Via: https://www.construct.net/en/forum/construct-3/general-discussion-7/build-failed-143270

Using an invalid project name will cause an Android debug APK build to fail.

## Attach a .c3p

Use built-in Ghost Shooter example

## Steps to reproduce

1. Rename project to `1`
2. Build as debug APK

## Observed result

Build failed

## Expected result

The build should either succeed, or show an error before exporting about the invalid project name before attempting a build.

The "build failed" dialog in this case also does not appear to show any useful diagnostics. Further:
- Construct should never just dump an error message in a dialog - it's a poor user experience and leads to confusion, especially since in this case, there is nothing in the log that is helpful. It also will not be translated. The dialog should have a translated header e.g. "Sorry, the build failed. The build log is included below in case it includes any information about the problem. You may need to adjust project settings or included plugins." and then include the build log beneath that.
- The build log text isn't selectable - it should be so bug reports can easily copy-paste.

**Comment by shortercode** [comment]
Okay both issues should be resolved in the next release.

**Comment by AshleyScirra** [comment]
@shortercode - is there a reason this is still open?

**Comment by shortercode** [comment]
@AshleyScirra nope
