### ISSUE TITLE
New Functions: Editor still thinks deleted function exists.

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2866]
I know this will get closed as I cant repo in minimal project
but just FYI
it looks like similar issue to
#2846 duplicate functions not deleting 
raised by mOOnpunk

**Issue**

- function (new / built in ) has been deleted from project but actions calling it were not deleted (maybe because deactivated ?) 
- search all references from the deactivated action shows that the editor still thinks the function exists.
- trying to recreate the function gives an "already existing" so cannot recreate with same name.
- function still exists in the list of callable functions , it appears under "functions"rather than "built in functions", what is the difference ,between the two?  all the functions listed are using the new function feature including the play sfx one.

**please before you close would you recommend rolling back project to before offending function was created??  or safe to continue with ghost function?????**

![image](https://user-images.githubusercontent.com/21962641/56328859-cde7c880-6178-11e9-93e1-a105c718c155.png)

![image](https://user-images.githubusercontent.com/21962641/56329388-261fca00-617b-11e9-8dc6-befbafc3ebdf.png)

![image](https://user-images.githubusercontent.com/21962641/56329476-89a9f780-617b-11e9-92fa-f83081f58775.png)

**Comment by AshleyScirra** [comment]
It might be related to issue #2851 (deleting functions did not remove calls in expressions - although action calls were correctly removed). That issue is already fixed for the next release. Other than that unless you follow the bug report guidelines I'm afraid there's nothing we can do, so closing.
