### ISSUE TITLE
Changes to Function results in multiple different versions of function with same name.

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2867]
## Problem description

Changes to Function results in multiple different versions of function with same name.

I have started adapting the function maps example from start page by changing the functions to accept multiple parameters

## Attach a .c3p

[Function maps adapted for pass multi parameters.zip](https://github.com/Scirra/Construct-3-bugs/files/3094284/Function.maps.adapted.for.pass.multi.parameters.zip)

## Steps to reproduce

This is the advanced example from the start page but I was adapting for multiple parameter pass. i didnt finish what I was doing because of bug.

## Observed result

observe multiple different functions with same name.

## Expected result

just updated function exists for calling

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.75
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
C3 release: r145 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 47 gb
Storage usage (approx): 99 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can't see any functions with the same name in the provided project. Did you attach the right file or miss some steps to reproduce?

**Comment by NetOneGames** [comment]
ok  let me have a look.

**Comment by NetOneGames** [comment]
ok that strange when reopening there are no duplicates.   this is definitely a thing though. was happening in my own project aswell last night at home.   give me a few mins I will go through the steps again.

**Comment by NetOneGames** [comment]
Sorry cant repo.  :(  

hopefully get some time on weekend for some dev work so will keep checking dupe functions to see what causes.

cheers

**Comment by AshleyScirra** [comment]
Please file again if you can identify the steps to reproduce.

**Comment by SnipG** [comment]
If you delete group where function was in, function can still be called and name is reserved, so you cant make new one with same name.
Reproduce: Click group and delete it
(NetOnegame owe me 20min.. :D)

**Comment by AshleyScirra** [comment]
@SnipG - that is a different issue, please file a new bug

**Comment by NetOneGames** [comment]
Hey yes @SnipG that was happening to me last night.   Actually @AshleyScirra  I think it is all related.  
This gave me an idea.  I tried moving a group after changing a few things (The one thing I didn't try during repo was moving a group which I had done in both cases. )   and I have created duplicates.    It looks like it is related to moving or deleting a group.   Will pin down....

**Comment by NetOneGames** [comment]
OK can repo.    
Just take the functions maps demo
then move the "Dispatching CAlls" group to the top.
You will see that the callcolor function is duplicated (look under actions functions) 
thanks @SnipG

**Comment by NetOneGames** [comment]
@SnipG  I will raise no worries.

**Comment by NetOneGames** [comment]
https://github.com/Scirra/Construct-3-bugs/issues/2871

**Comment by AshleyScirra** [comment]
> Just take the functions maps demo
> then move the "Dispatching CAlls" group to the top.
> You will see that the callcolor function is duplicated (look under actions functions)

Nope, can't reproduce that either... I don't know what you mean by "actions functions" either.

**Comment by AshleyScirra** [comment]
I see what you meant now in #2871, will follow up there.
