### ISSUE TITLE
Pasting events into comments

### ISSUE THREAD

**Issue by 3dParadox** [Scirra/Construct-3-bugs#287]
I copied the comment event instead of the text, but it still pasted inside another comment like this:
{"is-c3-clipboard-data":true,"type":"events","items":[{"eventType":"comment","text":"ScanFor(param0=uid , Param1=uid of ball to swap back on fail. -1 if none)"}]}

You can copy any event and paste it as text in the comment.  I am unsure if I want this fixed or not, now that I see I am able to copy it back out of the comment, and paste it back into events. Makes me think sharing code on the forums could be copied as text pasted into the events.  :-)

## Attach a .c3p

Copy an event and paste it into a comment.

## Steps to reproduce

1. Select event and press Control C
2. Select a comment as to edit it, with cursor flashing.
3. press control V

## Observed result

A glimpse behind the scenes.

## Expected result

It wouldn't paste anything as that's not a good place to store events.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Currently this is by design: the event clipboard format is text-based JSON so that it can be pasted elsewhere, e.g. on the forum. A side-effect of this is you can paste in to any text fields, including in comments.
