### ISSUE TITLE
Issues Deleting or Moving Groups with (new) Functions

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2871]
## Problem description
1) If you move a Group containing a function the function is duplicated (see call function action)
2) If you delete a Group containing a function the function is not deleted from / still available  to the editor. (see call function action)

## Attach a .c3p

Use the Function Maps advanced project

## Steps to reproduce

1) Move the Dispatching calls Group to the very top of all groups

Re open same project
2) Delete the Dispatching calls Group

## Observed result

1) Duplicate CallColor Function
2) CallColor Function is still retained and can be called.

1.)
![image](https://user-images.githubusercontent.com/21962641/56373223-6a04e480-61f8-11e9-913b-9113a0166b12.png)

2.)
![image](https://user-images.githubusercontent.com/21962641/56373411-c962f480-61f8-11e9-9dd5-a3d6003c280f.png)

## Expected result

No duplicate and no retaining after delete.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.75
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
C3 release: r145 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 47 gb
Storage usage (approx): 147 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
This is a pretty tricky area, but I think I've got it all sorted out for the next release.

**Comment by NetOneGames** [comment]
IMPORTANT!:   Hi Ashley you may want to issue a warning on the forums as this bug corrupts projects making them un-openable.
I have had to roll back to before I utilized the new functions to be able to open my project.
This is not such a big deal for me as I save by downloading which gives me a new copy each time but I know that many users just overwrite  in the browser each time so this will ruin their projects.
Cheers. Anyway good stuff with the fix and have a nice weekend.!




for users not to use the new functions.
