### ISSUE TITLE
function object not available in R144 and +

### ISSUE THREAD

**Issue by eonianvr** [Scirra/Construct-3-bugs#2872]
## Problem description
the function object is not available starting on R144 on a new project
## Steps to reproduce
1. load the R144 or R145 editor in chrome
2. add object (look for function)
3. function is nowhere to be found

## Observed result

function object is not available
## Expected result

being able to use the function object

## More details
Google Chrome is up to date
Version 73.0.3683.103 (Official Build) (64-bit)

When you open a project created on previous version of the editor inside R1444 or R145 , the function is included in the project

**Comment by AshleyScirra** [comment]
Please read the release notes, this was an intentional change. It's been replaced by the new built-in functions feature.

**Comment by eonianvr** [comment]
Sorry to be stupid. I read the release and  nowhere I found that function object would not be available if you create a project with R144 and above.
Do we have to create a dummy project in previous version , drop  a function object in it, then reopen it in R144 and above to be able to use function?

**Comment by AshleyScirra** [comment]
See the r144 release notes:

> The old Function plugin is also now deprecated in favor of the new built-in functions feature.
