### ISSUE TITLE
GooglePlay plugin has issue with native "log out"

### ISSUE THREAD

**Issue by ArtRow** [Scirra/Construct-3-bugs#2873]
## Problem description

It seems GooglePlay plugin has issue with native "log out" option. When user is logged in and he uses "log out" option from native interface/dialog - the plugin's "On signed out" doesn't trigger. 

## Attach a .c3p

There is no file, because it's needed of creating game service. I've tested this issue in 2 my different games on different Android devices.

## Steps to reproduce

1. Log In to google play service via GooglePlay plugin
2. Call a **native dialog** with achievements (GooglePlay - Display achievements) and log out via this dialog

## Observed result

All actions that should trigger after plugin's condition "On signed out" won't work.

## Expected result

All actions that should trigger after plugin's condition "On signed out" must be executed.

## More details

First time I found it in r142.2 stable version. Thanks for your support.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 50 gb
Storage usage (approx): 502 mb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 670 Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Have confirmed this, I expect the callback is firing but because the webview isn't in focus it never gets the event. Might be able to workaround this by firing the event after the dialog has closed.

**Comment by shortercode** [comment]
Looks like we didn't get any feedback after the dialog closed that we'd been signed out. I added a quick check after the dialogs close to update the state, seems to work fine now. As the change is based on the cordova plugin the fix has already been pushed out to the build server, so if you try now you should see it working.
