### ISSUE TITLE
Spritefont TextWidth and TextHeight not working properly

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2877]
## Problem description

The behavior of the TextWidth and TextHeight considers that the first line has a height of 0

## Attach a .c3p

[BugTextSizeSpritefont.zip](https://github.com/Scirra/Construct-3-bugs/files/3099592/BugTextSizeSpritefont.zip)

## Steps to reproduce

1. Preview the project

## Observed result

![image](https://user-images.githubusercontent.com/11213825/56448584-b04d6700-6310-11e9-95ee-babdcf56cd98.png)

## Expected result

The text should either match the square or the square should match the text. (The square being set to TextWidth and TextHeight

**Comment by AshleyScirra** [comment]
The measured size is correct - the problem is SpriteFont applies the line height above the line instead of below when drawing. If you compare to a Text object with a large line height you can see it gets it right. Fixed so SpriteFont draws consistently with Text for the next release.
