### ISSUE TITLE
Can't open my project. Error: No master keyframe was found for property keyframe.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2878]
## Problem description

I tried timeline yesterday and everything was fine. Today I tried to open my project it crashes the C3.

Error report information
Type: assertion failure
Message: no master keyframe was found for property keyframe
Stack: Error at Function.ǃpJp (https://editor.construct.net/r145/main.js:2:123922) at e (https://editor.construct.net/r145/main.js:2:84960) at https://editor.construct.net/r145/main.js:2:85285 at n.ǃywW (https://editor.construct.net/r145/main.js:82:524544) at n.ǃywi (https://editor.construct.net/r145/main.js:82:525019) at https://editor.construct.net/r145/main.js:82:527347 at Function.ǃyfS (https://editor.construct.net/r145/main.js:82:475627) at Function.ǃyfL (https://editor.construct.net/r145/main.js:82:475707) at Function.ǃyfq (https://editor.construct.net/r145/main.js:82:475873) at n.ǃox (https://editor.construct.net/r145/main.js:82:527309)
Construct 3 version: r145
## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: no master keyframe was found for property keyframe
Stack: Error at Function.ǃpJp (https://editor.construct.net/r145/main.js:2:123922) at e (https://editor.construct.net/r145/main.js:2:84960) at https://editor.construct.net/r145/main.js:2:85285 at n.ǃywW (https://editor.construct.net/r145/main.js:82:524544) at n.ǃywi (https://editor.construct.net/r145/main.js:82:525019) at https://editor.construct.net/r145/main.js:82:527347 at Function.ǃyfS (https://editor.construct.net/r145/main.js:82:475627) at Function.ǃyfL (https://editor.construct.net/r145/main.js:82:475707) at Function.ǃyfq (https://editor.construct.net/r145/main.js:82:475873) at n.ǃox (https://editor.construct.net/r145/main.js:82:527309)
Construct 3 version: r145
URL: https://editor.construct.net/r145/
Date: Sat Apr 20 2019 18:14:48 GMT+0300 (GMT+03:00)
Uptime: 27.1 s

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r145 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by bilgekaan** [comment]
I unzip the file and edit the json file of the timeline I created. stepTime was 0 and I changed it to 1. This fixed the project.

**Comment by DiegoScirra** [comment]
@bilgekaan 

Do you have a copy of the project that produces the crash?

**Comment by bilgekaan** [comment]
I managed the find how to reproduce it.

1. add a sprite and timeline plugin.
2. add a timeline.
3. set the timeline step to 0 seconds.
4. try to add an instance to timeline, it will crash.

You can try to add an instance to an existed timeline in the project below to see the crash.

[timeline-crash.zip](https://github.com/Scirra/Construct-3-bugs/files/3108031/timeline-crash.zip)

**Comment by DiegoScirra** [comment]
Thanks for that, i'll look into it.

**Comment by DiegoScirra** [comment]
I see what the problem is, a step of 0 produces divisions by 0 at certain points, which end up causing problems.

**Comment by DiegoScirra** [comment]
Fixed for the next beta release
