### ISSUE TITLE
Use SUPPR on a selection make a copy

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#288]
## Problem description

When i use SUPPR with a rectangle selection in the Animations Editor, it make a copy.
That cause problems when I make a COPY on a another image before, because the copy is not the copy I want.

## Steps to reproduce

1. Make a COPY of a Frame
2. Select another frame.
3. Select this frame with rectangle select
4. Press SUPPR
5. Use Past (CTRL+V)

## Observed result

The frame I have deleted appear

## Expected result

The frame I have copied

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed in r30.
