### ISSUE TITLE
Soft Nav Buttons not hidden in fullscreen - (HTML5 game, Android Chrome)

### ISSUE THREAD

**Issue by lukasinspace** [Scirra/Construct-3-bugs#2881]
## Problem description

Android's soft navigation buttons (back, home, recent) are not hidden in Chrome for Android when the the Browser > Request fullscreen action is used in a html5 project. The Android status bar is hidden as expected.

In the attached c3p I have added a sprite button with a single event to say:
On touched, Browser > Request fullscreen

Testing the game on a mobile device using **Chrome for Android**, when the the button is touched the game scales up to fullscreen, but the soft navigation buttons remain visible. 

Testing in **Firefox** for Android, the soft nav buttons **are** hidden as expected when fullscreen action is used. 

So it seems to be a problem with Chrome for Android? 

Im testing by hosting the game on the website itch.io. Please note that I tried to test this by exporting the project for the Scirra Arcade and uploading there, but I kept getting the 'Server Error in '/' Application' error when attempting to upload the project. So Im unable to test there. But it would be good to test this on either the Scirra Arcade, or by hosting the project  somewhere other than itch.io to rule out itch.io being the source of the problem. 

## Attach a .c3p

[fullscreenTest.zip](https://github.com/Scirra/Construct-3-bugs/files/3105439/fullscreenTest.zip)

## Steps to reproduce

1. Export project for html5 from the attached c3p project.
2. Upload to itch.io.
3. Use Chrome for Android on an Android mobile device to access the  game on itch.io.
4. When game loads, press the pink button to request fullscreen.

## Observed result

The project goes to fullscreen but the soft navigation buttons remain visible on the Android device. 

## Expected result

The soft nav buttons should be hidden, like occurs in Firefox for Android. 

## More details

**Affected browsers/platforms:** 
Chrome for Android

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r145 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 32 gb
Storage usage (approx): 1 gb (3.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Currently the browser decides what kind of UI to show in fullscreen mode. However I noticed there's a new feature to be able to customise this and it was straightforward to add. So the next release has a new "Navigation UI" parameter which you can set to "Hide" to get true fullscreen in Chrome for Android.

**Comment by lukasinspace** [comment]
Hi Ashley I just tested the 'Nav UI - Hide' parameter in r146. Unfortunately it doesn't seem to help when I host the game on itch.io. The soft nav buttons still dont get hidden when the project goes to fullscreen.
I guess it could be something on the itch.io website. So i will message their support, describe the situation to them and see what they reply with. Thnx
