### ISSUE TITLE
android user media (camera) not working

### ISSUE THREAD

**Issue by eonianvr** [Scirra/Construct-3-bugs#2884]
## Problem description

Trying to access and display the camera of the device (tried samsung s7 and samsung tablet) using the User Media plugin does not seem to work as intended.

## Attach a .c3p
[debug apk](https://drive.google.com/file/d/1sGUSOFrTcWOSrmq2gq4etSAIh5j0NrpH/view?usp=sharing)
[project c3p R142 compile with C3 runtime](https://drive.google.com/file/d/1Se-XpK088OoO1SWVFvNPk4CucZV7jldl/view?usp=sharing)

## Steps to reproduce

install the debug apk on android
Press the button "Start camera"
It doesnt ask for permission and nothing happens

## Observed result

The user media area stays black.

## Expected result

The content of the camera to be displayed.

## More details

I compiled the project with C2 runtime to determinate if it was linked to C3 runtime.
with C2 runtime, the camera shows up properly and you have a permission request to access it but the app crash when you try to take a snapshot and no picture is saved.

**Affected browsers/platforms:** 
android (didnt test on iphone)

**First affected release:** 
Not known. Compiled the project on R142
Same issue was reported on august 29,2018 on iOS via safari. Not related plateform wize, but that's the closest I found: https://github.com/Scirra/Construct-3-bugs/issues/1964

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
The C3 runtime appears to be missing the Android permission check code for user media, was fixed in the C2 runtime in #1261.

The crash when trying to take a picture is a separate issue.

**Comment by eonianvr** [comment]
Thank you for the update. it is an easy fix (for C3) since you had the problem before or should I drop the ball on that?

**Comment by shortercode** [comment]
Working on it now, so hopefully resolved for next weeks release. But I will update this issue when it's completed.

**Comment by shortercode** [comment]
Okay this should hopefully be resolved in the next beta. I also resolved a separate issue that I discovered in the C2 runtime that it wasn't possible to use the microphone input.

**Comment by eonianvr** [comment]
R147?
