### ISSUE TITLE
autocomplete oppsie doopsies when moving the cursor with the mouse

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2886]
## Problem description

when i type the name of a variable or somethng in construct 3 autocomplete does not go away when i click to move the cursor it keeps the same autocompleted thing word variable thing highlighted no matter what key i press until i press spacebar or enter and then it inserts that word where the cursor is breaking my code
## Attach a .c3p

https://puu.sh/DiSCt/d6aa6996b8.c3p
## Steps to reproduce

1.start typing something that autocompletes 
![image](https://user-images.githubusercontent.com/32940085/56615113-6ef6d900-65e8-11e9-92ac-e475717779df.png)

2.move the cursor somewhere else with a click
![image](https://user-images.githubusercontent.com/32940085/56615142-7ae29b00-65e8-11e9-8971-8bd0b6dbc05f.png)

3.shenanigans, can'T hit space-bar or else it pastes the highlighted thingy thing
![image](https://user-images.githubusercontent.com/32940085/56615421-065c2c00-65e9-11e9-9fe1-cd983bdf4886.png)

## Observed result

the thing 
## Expected result
autocomplete to go away when i click somehwere else just like when i use the arrow keys

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by kingpirux** [comment]
i hate that too

**Comment by SnipG** [comment]
Ye this pretty annoying.
When something like this is unreported so long, maybe users like it ? :D

**Comment by AshleyScirra** [comment]
Fixed for next release.
