### ISSUE TITLE
Difficulty selecting Bitrate in Import dialog when adding audio files

### ISSUE THREAD

**Issue by LanciferStudios** [Scirra/Construct-3-bugs#2887]
## Problem description

Difficulty selecting Bitrate in **Import sounds** dialog when adding audio files. 
Only a thin portion of the dropdown menu is clickable.

## Attach a .c3p

[AddingSound.zip](https://github.com/Scirra/Construct-3-bugs/files/3109626/AddingSound.zip)

## Steps to reproduce

1. Create new project.
2. Open **Import sounds** dialog window.
3. Attempt to select bitrate from dropdown menu.

## Observed result

![Bitrate selection](https://i.imgur.com/XDsKwMol.png)

Also including a 19sec video showing the issue:
[https://youtu.be/MMt_T5q22oo](https://youtu.be/MMt_T5q22oo)

## Expected result

![Bitrate selection](https://i.imgur.com/xQKBBIgl.png)

## More details

**Affected browsers/platforms:** Desktop release

**First affected release:** Release r146 Beta

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r146 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 101 gb
Storage usage (approx): 604 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Looks to be an issue with the light/dark theme changing the layout. Works correctly in the default theme.

**Comment by AshleyScirra** [comment]
@Animmaniac - it's best not to change the layout from themes because it makes it difficult to make changes later down the line.

**Comment by AshleyScirra** [comment]
Reverted dialog layout to default theme for next release, which gets the bitrate dropdown working again.
