### ISSUE TITLE
Spritefont text in r146 being cutoff by 1 character

### ISSUE THREAD

**Issue by lukasinspace** [Scirra/Construct-3-bugs#2888]
## Problem description

When a the spritefont size is set to be textWidth and the spritefont character spacing has been set to -1, one character is chopped off the spritefont's text when previewed.
## Attach a .c3p

[spritefontTest.zip](https://github.com/Scirra/Construct-3-bugs/files/3110427/spritefontTest.zip)

## Steps to reproduce

1. Create a spritefont, set character spacing to be -1.
2. On start of layout create spritefont, set text to be anything, set size to be Spritefont.TextWidth x Spritefont.TextHeight.
3. Preview project. One character is chopped off. 

## Observed result

One character is chopped off the the spritefont's text.
## Expected result

Expect to see complete text set for the spritefont.
## More details

I see that in r146 changes have been made to how spritefont character spacing and line height are treated. I guess its a bug introduced by these changes as it wasnt occurring prior to r146. 

Note that this can be quickly fixed in project by setting width to TextWidth+1. In that case the final character is shown as expected.

**Affected browsers/platforms:** 

**First affected release:** 
r146 (beta)
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r146 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 32 gb
Storage usage (approx): 1015 mb (3.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This was caused by the fix to #2850, since it now applies the character spacing to trailing characters, causing a 1px shortfall at the end of the line in this case given the character spacing is -1. I've adjusted the text dimensions for the next release to take in to account negative character spacings at the end of the line.
