### ISSUE TITLE
Crash after using undo with ctrl-z (error log)

### ISSUE THREAD

**Issue by johnsmith27** [Scirra/Construct-3-bugs#2889]
## Problem description

C3 "randomly" crash when using ctrl+z to undo a change.
Happens in the editor layout view (deleting sprite instances and Z order sorting) and also in the event view, can't be more specific unfortunately as I dont remember what I was undoing exactly.. I just remember it crashed.

I'm including my error log after crashing by hitting ctrl+z to undo a change in the Z order panel (in the layout view)

Sorry no C3p, i'm just sharing my error log in case it could be useful.
My project is pretty big, dont know if it's related or not.. but I seem to crash more and more when using ctrl+z thus why I'm posting this issue.
If needed, I may post any new crash report here if I encounter this problem again.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected HTML element @ TypeError: expected HTML element at Function.ǃJ.ǃei (https://editor.construct.net/r142-3/main.js:2:121025) at Function.ǃimN (https://editor.construct.net/r142-3/main.js:2:271794) at d.ǃJL (https://editor.construct.net/r142-3/main.js:2:467946) at window.ǃdI.ǃrh (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:17105) at window.ǃdI.ǃMR (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:16846) at window.ǃdI.ǃdN (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:14956) at Array.ǃdm (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:756) at ǃJ.Event.ǃiGQ.ǃiGL (https://editor.construct.net/r142-3/main.js:2:212166) at window.ǃMPh.dispatchEvent (https://editor.construct.net/r142-3/main.js:2:210034) at window.ǃMPh.ǃJmT (https://editor.construct.net/r142-3/main.js:177:648704)
Stack: TypeError: expected HTML element at Function.ǃJ.ǃei (https://editor.construct.net/r142-3/main.js:2:121025) at Function.ǃimN (https://editor.construct.net/r142-3/main.js:2:271794) at d.ǃJL (https://editor.construct.net/r142-3/main.js:2:467946) at window.ǃdI.ǃrh (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:17105) at window.ǃdI.ǃMR (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:16846) at window.ǃdI.ǃdN (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:14956) at Array.ǃdm (https://editor.construct.net/r142-3/components/bars/zOrderBar/zOrderBar.js:1:756) at ǃJ.Event.ǃiGQ.ǃiGL (https://editor.construct.net/r142-3/main.js:2:212166) at window.ǃMPh.dispatchEvent (https://editor.construct.net/r142-3/main.js:2:210034) at window.ǃMPh.ǃJmT (https://editor.construct.net/r142-3/main.js:177:648704)
Construct 3 version: r142.2
URL: https://editor.construct.net/
Date: Wed Apr 24 2019 18:01:27 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 29564 s

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Normally we cannot do anything without steps to reproduce, and the crash report indicates you are using the latest stable release. Please only report issues that reproduce in the latest beta release - we may well have fixed this already.
