### ISSUE TITLE
Can't access gamepad controller vendor or product ID for Xinput devices

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2890]
## Summary

The expression GamepadID returns info about a controller, but it's not so useful for Xbox controllers as all it returns there is "Xinput", making it difficult to assess which controller is being used. 

Xbox 360 and Xbox One controllers have different buttons, so they require different icons.

Please provide vendor and product ID for Xinput.

## Why it's an issue

Users expect their controller to be accurately represented in games. If you're using a PlayStation controller you don't want to see Xbox 360 graphics in the game.

For instance in the game below, it's showing Nintendo 64 buttons graphics instead of PlayStation buttons because the player is using a Nintendo 64 controller.

![image](https://user-images.githubusercontent.com/5744908/56719471-1fe5ab00-6784-11e9-8d67-e1e1d5b2099a.png)

While 360 is the most popular controller still (as of September 2018) there are millions of other controllers being used

https://steamcommunity.com/games/593110/announcements/detail/1712946892833213377

![image](https://user-images.githubusercontent.com/5744908/56719655-8a96e680-6784-11e9-842b-f57e47880d08.png)

## Xbox 360 gamepadID

Chrome: Xbox 360 Controller (XInput STANDARD GAMEPAD)

Firefox: xinput

## Xbox One gamepadID

Chrome: Xbox 360 Controller (XInput STANDARD GAMEPAD)

Firefox: xinput

## PS4 Dualshock 4 v2 gamepadID

Chrome: Wireless Controller (STANDARD GAMEPAD Vendor: 054c Product: 09cc)

Firefox: 054c-09cc-Wireless Controller

## Nintendo Switch Pro controller gamepadID

Chrome: Wireless Gamepad (Vendor: 057e Product: 2009)

Firefox: 057e-2009-Wireless Gamepad

## Observations

In Chrome the id for Xbox One controller outright lies, saying it's an Xbox 360 controller. How am I to distinguish between Xbox One and Xbox 360 controllers?

It's much easier to identify the non-Xbox controllers. To tell if its a Sony controller I can at least search the string for "057e" and then if it's DS4v2 search for "09cc".

**Comment by AshleyScirra** [comment]
Construct simply returns the browser-provided [Gamepad.id](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/id) property. If that doesn't have what you need in it you'll need to file an issue with the browser vendor (crbug.com in this case).

**Comment by alastajj** [comment]
For future people: apparently Xinput API can't retrieve this information.
