### ISSUE TITLE
Crash using Beziers in Timeline

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2891]
## Problem description

Chrash moving bezier handles as below

## Attach a .c3p

[BezierIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/3116271/BezierIssue.zip)

## Steps to reproduce

Open the attached project,
Put timeline for sprite in edit mode and adjust either of the two handles highlighted in the picture below.

![image](https://user-images.githubusercontent.com/21962641/56726608-fe1a0300-6746-11e9-9f60-9eb6607a8fc8.png)

## Observed result

Crash

## Expected result

No crash

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.75
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
C3 release: r146 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 47 gb
Storage usage (approx): 199 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro K3100M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

CRASH REPORT

Error report information
Type: unhandled exception
File: https://editor.construct.net/r146/main.js, line 2, col 126402
Message: Uncaught TypeError: Cannot read property 'ǃfm' of undefined
Stack: TypeError: Cannot read property 'ǃfm' of undefined at new (https://editor.construct.net/r146/main.js:82:558182) at Function.ǃd (https://editor.construct.net/r146/main.js:2:126381) at Object.ǃgRe (https://editor.construct.net/r146/components/editors/layoutView/layoutView.js:1:68364) at e.ǃKO (https://editor.construct.net/r146/components/editors/layoutView/layoutView.js:1:59026) at Array. (https://editor.construct.net/r146/components/editors/layoutView/layoutView.js:1:57437) at Object.ǃxRp (https://editor.construct.net/r146/main.js:2:192741) at Object.dispatchEvent (https://editor.construct.net/r146/main.js:2:190782) at Object.ǃKO (https://editor.construct.net/r146/components/editors/layoutView/layoutView.js:1:18698) at HTMLDivElement. (https://editor.construct.net/r146/components/editors/layoutView/layoutView.js:1:3964) at HTMLDocument. (https://editor.construct.net/r146/main.js:2:187519)
Construct 3 version: r146
URL: https://editor.construct.net/r146/
Date: Thu Apr 25 2019 10:46:35 GMT+0100 (British Summer Time)
Uptime: 389.1 s

Platform information
Browser: Chrome
Browser version: 73.0.3683.75
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
C3 release: r146 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro K3100M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
The crash is fixed now, along with the drawing of the curves which was wrong under some circumstances.
