### ISSUE TITLE
Can't change bullets angle of motion on creation

### ISSUE THREAD

**Issue by WeariedCoffee2** [Scirra/Construct-3-bugs#2894]
## Problem description

 Can't change a bullets angle of motion on creation. I can only change its angle of motion a minimum of 0.017 seconds after it is created.

## Attach a .c3p

 https://drive.google.com/file/d/17ASmcAbJcQ4mbNtXpP8G0iCcXbEBZd_8/view?usp=sharing

## Steps to reproduce

1. hold the left mouse button to fire bullets.
2. in layout 1 the bullets do not change angle of motion
3. in layout 2 the bullets change angle of motion 0.017 seconds after they are created

## Observed result

 In layout 1 I see the bullets go straight not changing their angle of motion.

## Expected result

 In layout 1 the bullets should change their angle of motion when they are created

## More details
 The bullet uses the Bullet behaviour. I can change the bullets angle of motion at a minimum of 0.017 seconds after it is created shown in layout 2.

**Affected browsers/platforms:**  Windows 10

**First affected release:**  Don't know

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 391 gb
Storage usage (approx): 115 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by oosyrag** [comment]
This has to do with the Bullet "Set Angle" property. When disabled, in layout 1 the bullet will get the randomized angle, but always from angle 0. When disabled and the event changed to use the gun angle instead of the bullet behavior's angle of motion expression (as below), it works as expected. If bullet's Set Angle is enabled, it doesn't work in either case.

-> bullet: Set Bullet angle of motion to gun.Angle + random(-30, 30) degrees

**Comment by AshleyScirra** [comment]
As @oosyrag mentioned since 'Set angle' is enabled on the bullet behavior, the angle of motion is set to the object angle. Either change the object angle, or disable the 'Set angle' property.

**Comment by oosyrag** [comment]
This seems inconsistent with the manual entry.

Set angle

If disabled, the behavior will never change the object's angle. If enabled, the behavior always sets the object angle to the angle of motion.

It seems like it should be the other way around?
