### ISSUE TITLE
Autocomplete when erasing something the thing you erased stays autocompleted and you can'T get rid of it

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2895]
## Problem description

when erasing something the thing you erased stays autocompleted and you can'T get rid of it
## Attach a .c3p

https://puu.sh/Dkl6Y/50d6f87ff6.c3p
## Steps to reproduce

1.I start typing something and it autocompletes
![image](https://user-images.githubusercontent.com/32940085/56834027-5122b180-683e-11e9-9328-9408a747e0b7.png)

2. I erase it because i realized i was trying to type a string 
![image](https://user-images.githubusercontent.com/32940085/56834060-6992cc00-683e-11e9-8bb9-ab4d31d4c4d9.png)

3.i hit the " key to start typing my string and auto complete fills in for some reason
![image](https://user-images.githubusercontent.com/32940085/56834116-87f8c780-683e-11e9-921d-dca7231c0f40.png)

4. I erase it to re-type the " symbol and it does the same thing again !!!
![image](https://user-images.githubusercontent.com/32940085/56834159-a3fc6900-683e-11e9-9d4b-71a39d650b0e.png)
![image](https://user-images.githubusercontent.com/32940085/56834163-ae1e6780-683e-11e9-8778-297a98e8bb29.png)

## Observed result

I lose my mind why does it keep doing this !
## Expected result

I expect it to type " when i press " to begin a string layer name thing
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r146 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 755 mb (4.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It hides autocomplete if you backspace one more time or press 'Escape', but I agree this is an annoying case, so changed for the next release.
