### ISSUE TITLE
Crash when an action group is moved to a function

### ISSUE THREAD

**Issue by DieppedalleDavid** [Scirra/Construct-3-bugs#2898]
## Problem description

Crash when an action group is moved to a function.

## Attach a .c3p

Image:
https://drive.google.com/open?id=1P2Dp8epwjbBv2se9kuPJSv-SwtkA951Z

Project:
https://drive.google.com/open?id=1RJe5VaPlNyBZ35efoN_kPtoIjEwNbM0J

## Steps to reproduce

See Image

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r146/main.js, line 82, col 294685
Message: Uncaught Error: cannot add another trigger to event branch
Stack: Error: cannot add another trigger to event branch at n.ǃgr (https://editor.construct.net/r146/main.js:82:294691) at Object.ǃGJ (https://editor.construct.net/r146/components/editors/eventSheetView/eventSheetView.js:1:28702) at Object.ǃBg (https://editor.construct.net/r146/components/editors/eventSheetView/eventSheetView.js:1:26333) at Object.ǃKa (https://editor.construct.net/r146/components/editors/eventSheetView/eventSheetView.js:1:22200) at HTMLDocument. (https://editor.construct.net/r146/components/editors/eventSheetView/eventSheetView.js:1:2252) at HTMLDocument. (https://editor.construct.net/r146/main.js:2:187519)
Construct 3 version: r146
URL: https://editor.construct.net/r146/
Date: Sun Apr 28 2019 17:19:50 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 2469.9 s

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r146 (beta)
Language setting: fr-FR

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Minimal project: [trigger-event-drag.zip](https://github.com/Scirra/Construct-3-bugs/files/3126909/trigger-event-drag.zip)

**Comment by AshleyScirra** [comment]
Should be fixed in the next release.
