### ISSUE TITLE
Additional Jump-Thru Objects Ignored Already Standing On One

### ISSUE THREAD

**Issue by AySquirrel** [Scirra/Construct-3-bugs#2902]
## Problem description

When an object with the platform behavior is standing on top of a jump-thru object and they both pass through another jump-thu object, collision with the second jump-thru object is ignored

## Attach a .c3p

[MovingJumpThruPlatformBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3129603/MovingJumpThruPlatformBug.zip)

## Steps to reproduce

1. Start the project
2. Using the arrow keys, jump onto the left edge of the blue platform
3. Once on the blue platform, move over to the right edge
4. Stand still for a moment, and notice that the red square passes through the green platform
5. Jump off of the blue platform and move onto the right edge of the green platform
6. Once on the green platform, move over the the left edge
7. Stand still for a moment, and notice that the blue platform passes through the red square

## Observed result

The red square ignores additional jump-thru objects when it is already "attached" to one

## Expected result

The red square to stay on top of the green platform when passing through it, and to be picked up by the blue platform when standing above it

Not sure if this is actually a bug or if this is how it's intended to work... But it'd be nice to choose which platform gets priority in a situation like this

## More details

**Affected browsers/platforms:** 

Chrome, Firefox

**First affected release:** 
r120

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r147 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 4.4 gb (7.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Jump-thrus aren't really solid since you can jump through them from underneath. Use solids if you want to make sure moving platforms pick up the player.

**Comment by AySquirrel** [comment]
Okay. Thanks for the clarification!
