### ISSUE TITLE
Construct 3 UWP visual studio export

### ISSUE THREAD

**Issue by tyler3327** [Scirra/Construct-3-bugs#2903]
## Problem description

When exporting using latest stable version on construct 3 I receive 2 errors Google play and failure to login attached is the code I used for login. I followed Ashley's UWP export tutorial to the dot I'm not sure what I did wrong or if something is wrong. I also receive an error telling me file needs to be opened in visual studio and re saved as a utf-8 file error comes from windows certification. Now if I cut part of the code out for Google console error it fixes that but the xbox live login still doesnt work. I am developing this app across multiple platforms I deleted all Google related things mobile iap etc and tried again still nothing changed the code several times same errors. I isolated the first layout and event sheet all alone for the test also as seen below.

## Attach a .c3p

![56929610-191ea700-6aa8-11e9-8089-88f9284793e0](https://user-images.githubusercontent.com/32486148/56939352-d70c5a00-6ad5-11e9-83cd-7db18f957cda.png)
![56929611-19b73d80-6aa8-11e9-95c1-f559cf4a44e5](https://user-images.githubusercontent.com/32486148/56939359-dd023b00-6ad5-11e9-927e-22ef3d9604be.png)

## Steps to reproduce

1.Export to latest uwp version of visual studio 
2.import to visual studio
3.multiple errors

## Observed result

Multiple errors

## Expected result

No errors lol

## More details

I'm using visual studio 2017 the latest version windows 10 laptop. I'm really not sure if this is a glitch in construct or visual studio.

**Affected browsers/platforms:** 
Windows

Latest construct 3 stable release

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please provide a minimal project demonstrating the problem as per the bug report requirements, otherwise we cannot investigate.

**Comment by tyler3327** [comment]
Visual studio file or the construct 3 file?

**Comment by AshleyScirra** [comment]
The Construct 3 project, as described in the guidelines.

**Comment by tyler3327** [comment]
https://www.dropbox.com/s/kggs9lgmb2h2ewi/Ashley%20Test%20c3.c3p?dl=0

I uploaded the file to my dropbox.

**Comment by tyler3327** [comment]
Also if you could give me a heads up after you download it so I can remove the file from dropbox I made it public and I'm worried about someone else downloading it.
Thank you

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. We don't want your full project, and that means you don't have to share it publicly either.

**Comment by tyler3327** [comment]
Okay sorry the issues above are included xbox live sign in faild Google play error but I can get around that by chopping off console error. And the windows certification error. I will chop up my game and reupload the example in 2 hours from now my apologies for the time I will be more concise with the issue also.
