### ISSUE TITLE
No keyboard shortcut for Functions

### ISSUE THREAD

**Issue by Kramdos** [Scirra/Construct-3-bugs#2906]
## Problem description

There is currently no keyboard-shortcut to add a new function into an eventsheet. You have to rightclick in the eventsheet to open the menu and select 'add function'.

Most other functions have shortcuts:
e - add event
c - add condition
a - add action
q - add comment
g - add group
and more.

## Attach a .c3p
N/A

## Steps to reproduce

Tested most buttons on the keyboard.

## Observed result

None added a 'On Function' in the eventsheet.

## Expected result

Having a shortcut that opens the 'New function'-window (maybe 'F'?)

## More details

It is very quirky having to move the hand to the mouse when using the keyboard most of the time to write in the eventsheet.

**Affected browsers/platforms:** 

N/A

**First affected release:** 

Tested in r147.

**Comment by Kramdos** [comment]
There's also no keyboard shortcut for adding parameters to the new functions (maybe 'P'?).

Just want to say this is a nitcpick and I love how the new functions work, great work as usual, even with some birth difficulties. 

***thumbs up***

**Comment by AshleyScirra** [comment]
Added 'F' and 'P' shortcuts to add a function and a parameter (respectively) for next release.
