### ISSUE TITLE
there is a bug in loop when there is no instance in layout

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2908]
## I am trying to create a loop which is working perfectly when i insert required number instances in layout for a loop. But if i delete all instances from layout or keep less instance than required for that loop and create them through events and after that i apply that loop then preview only shows a infinite black screen, it stuck on black screen and when i try to close construct 3 then it doesn't close unless i do end task from task manager.
I have attached c3p file. please check that file.

## Attach a .c3p

[new bug issue.zip](https://github.com/Scirra/Construct-3-bugs/files/3134157/new.bug.issue.zip)

## Steps to reproduce

1. download the attached file
2. and preview both grouped events one by one

## Observed result

infinite black screen 

## Expected result

both grouped events in attached 

## More details

in attached file there are 2 groups 
one is working and and second is not working.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
'Create object' does not truly create objects until the end of the next top-level event. You can however use it in the same event and its sub-events, but not other events. Therefore the instance created by 'Create object' cannot be picked in the next sub-event; 'Pick random instance' won't ever pick anything, so pickedCount never increases, so you have an infinite loop.

**Comment by luckyrawatlucky** [comment]
is there any documentation related this so i can read more about this? I don't know logic behind this, how it actually works or what is behind the scene.
