### ISSUE TITLE
Crash when closing project file.

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#2910]
I think we had that one already https://github.com/Scirra/Construct-3-bugs/issues/1601
It occationally happens (again?). Not sure if it is back again or a new error or was never 100% resolved for all cases. Again lot´s of Ctrl+Z while editing project files involved so hard to pinpoint. I had a bunch of Project files open, saved and started to close them when it happend. If I find out how to reproduce I´ll update, but maybe it just snuck back in and is an easy fix.

## Attach a .c3p
🍞 

## Steps to reproduce

1. Editing, saving, ctrl+Z in project files
2. close them

## Observed result

The crash

## Expected result

No crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r147/main.js, line 82, col 553956
Message: Uncaught Error: Undopoint not present in buffer
Stack: Error: Undopoint not present in buffer at Object.ǃlI (https://editor.construct.net/r147/main.js:82:553956) at t.ǃtsh (https://editor.construct.net/r147/main.js:82:86788) at Object.ǃlz (https://editor.construct.net/r147/components/editors/textEditor/textEditor.js:1:3352) at Array. (https://editor.construct.net/r147/components/editors/textEditor/textEditor.js:1:5801) at Object.ǃFvF (https://editor.construct.net/r147/main.js:2:192822) at Object.dispatchEvent (https://editor.construct.net/r147/main.js:2:190688) at Object.ǃlI (https://editor.construct.net/r147/main.js:2:322700) at Object.ǃlI (https://editor.construct.net/r147/main.js:2:327889) at Object.ǃlI (https://editor.construct.net/r147/main.js:2:338482) at Object.ǃFzp (https://editor.construct.net/r147/main.js:2:334934)
Construct 3 version: r147
URL: https://editor.construct.net/r147/index.html
Date: Thu May 02 2019 00:16:39 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 7139.6 s

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r147 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by LukeNecklace** [comment]
I'm not sure if this bug is related to the desktop version or not but I noticed this happens if you have an event sheet open in a completely separate window on the desktop version and you close your project.

**Comment by LukeNecklace** [comment]
I'm not sure if this bug is related to the desktop version or not but I noticed this happens if you have an event sheet open in a completely separate window on the desktop version and you close your project.

**Comment by shortercode** [comment]
Looking at the crash log it appears to be related to a text editor trying to clear it's undo ( or redo ) points as the project closes. I guess a couple of ways for this to happen, but haven't had any luck causing the crash. Could you come up with a reproduction for me?

**Comment by shortercode** [comment]
As we have no replication for this issue I'm going to close it, there's no action to be taken for it unfortunately. Hopefully someone will come forward with a reproduction in future.

**Comment by Wackytoaster** [comment]
Sure thing, it didn´t happen again in a while now anyway.

I have to say that from every program I´ve ever used Construct 3 has probably the most "pleasant" crashes. I´m a crazy Ctrl+S spammer so I usually never lose more than a couple of seconds of work (not to mention I could still save the open project even when it crashes) and C3 is back up and running in like 10 seconds.

Compared to the likes of Maya, where it first freezes for a minute, takes another minute to start up and then tells you your file is now corrupted because you didn´t purge the object history for too long, forcing you to go back to your last incremental save from hopefully not hours ago... :V
