### ISSUE TITLE
key is not defined

### ISSUE THREAD

**Issue by Madiosn** [Scirra/Construct-3-bugs#2911]
## Problem description
A couple of days ago there was an error when working in the browser with construct 3.

The message constantly flies: Construct 3 beta / key is not defined

The message comes out after a certain amount of time constantly when working in the browser
screen
https://yadi.sk/i/iZ8YGTb9QbqYIw
The browser does not matter - it happens in all browsers
## Attach a .c3p
I can not lay out the project, because it does not affect the problem even if you just open a new project

## Steps to reproduce

I do nothing, the message comes out every time constantly and arbitrarily.
1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE
https://github.com/Scirra/Construct.net-website-bugs/issues/94
</details>

**Comment by AshleyScirra** [comment]
I'm afraid there's nothing we can do unless you follow the bug report guidelines as closely as possible. We don't even have your system details.

**Comment by Madiosn** [comment]
Do I need to complete this post in detail? Or create a new maximally filled information?
