### ISSUE TITLE
.capx problem in save to .c3p and loading project in C3

### ISSUE THREAD

**Issue by AmirrezaAhsani** [Scirra/Construct-3-bugs#2915]
## Problem description
I worked on project more then 8 month in C2. 
but I had imported my project to C3 and worked on it more than 3 hours in C3 and I saved it in my local Drive and local browser in web on chrom, internet explorer, fire fox or desktop version.

Now when I want to open it, I encounter this errors:

ailed to open project. Check it is a valid Construct 3 single-file (.c3p) project!
or
Invalid name!

## Attach a .c3p
I can provide a .c3p or .capx file of my project if I can send it via email somewhere, privately

## Steps to reproduce

1.open a .capx file in C3 desktop or web version 
2.save it in c3p format in local browser or local drive
3.open the saved c3p file 

## Observed result

the game fails to load, get a message that it is not a valid c3 project
## Expected result

I expected the project to save and load it
## More details

**Affected browsers/platforms:** 
Chrom 
Fire fox
Internet explorer

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. I'm afraid there's nothing we can do unless we have steps to reproduce the problem, going from a working project, to a not working project. If the project is broken, we can try to recover it, but that does nothing to solve the problem that caused the broken project.

**Comment by AmirrezaAhsani** [comment]
this is my .capx file download link
please open it in construct 3, then save it to .C3p and close project.
now try for load or open it again in Construct 3!
I don't know really what is problem!?

[Doonaminula.capx](https://www.mediafire.com/file/4aqoj798aovotp7/Doonaminulaen.zip/file)

**Comment by AshleyScirra** [comment]
The project uses several third-party addons:

Plugin MagiCam (MagiCam) by Chris Hackmann (aka linkman2004)
Plugin Touch wrap (rex_TouchWrap) by Rex.Rainbow
Behavior MoveTo (Rex_MoveTo) by Rex.Rainbow
Behavior RotateTo (Rex_RotateTo) by Rex.Rainbow

I'm afraid we cannot support projects using third-party addons - they could well be the cause of the problem, and if they are you need to contact the developer. Please see the bug report guidelines.

**Comment by AmirrezaAhsani** [comment]
there is no problem for plugins 
I deleted the plugins and tested it, there is no problem from plugins or behaviors because I encountered again with that erors!

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. We are happy to help if you can reproduce the issue in a project that does not use third-party addons.
