### ISSUE TITLE
Collapse / Expand won't collapse event blocks

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2916]
## Problem description

Implementing a part of https://construct3.ideas.aha.io/ideas/C3-I-297 was awesome, but the event block part is either a bug or was ignored. The idea is flagged as shipped but the event blocks don't collapse when right clicking on the group they're in. Ideally the collapse / expand would appear when right clicking just the empty space on an event sheet to fold all groups and blocks.

## Attach a .c3p

Any blank project

## Steps to reproduce

1. Right click a group from an event sheet with a few sub-blocks and groups inside the main group
2. Press collapse
3. Notice the groups fold but the event blocks do not

## Expected result

Was expecting to be able to fold event blocks.

## More details

**Affected browsers/platforms:** Chrome / Desktop

**First affected release:** since the idea was implemented

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 356 gb
Storage usage (approx): 99 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX550/550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Changed the next release to expand/collapse all events, and moved it to the common menu.

**Comment by JeFawk** [comment]
Thanks a lot for adding this, it helps enormously!
