### ISSUE TITLE
CAN MULTIPLAYER WORK IN BACKGROUND? C2/C3 RUNTIME

### ISSUE THREAD

**Issue by kt3v** [Scirra/Construct-3-bugs#2917]
Hello! I had a problem with multiplayer. If host minimizes the window or just goes to another tab, the signal disappears. And all synchronized objects disappear from sight.

This happens in the browser and in the nwjs.

[Proof youtube](youtu.be/t_1GPa7eIcE)

You can see bug in Multiplayer Game template

## More details

**Affected browsers/platforms:** Chrome/Firefox/Safari, Windows/macOS

**First affected release:** first started happening in r142.2

**Comment by kt3v** [comment]
Excuse me. But this is the first time I use a githги and my English is not at the highest level.
So your attitude towards users is not the best. And I told you about your mistakes.

“ignored guidelines” and closing a topic sounds just as stupid as not being able to understand the essence of the above problem.

**Comment by kt3v** [comment]
So the price for Construct 3 is not justified. "Pay and use what you have. Bugs are your problems."

**Comment by AshleyScirra** [comment]
We cannot investigate issues if there is not enough information for us to look in to the problem. Please see the bug report guidelines. We hold all reports to the same standard. The aim is to make sure we can help you.
