### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#292]
## Problem description
Application crashing multiple times today always while working in the sprite editor.

## Attach a .c3p

attached in zip

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes
## System details
Error report information
Type: unhandled rejection
Reason: Error: The source image cannot be decoded.
Construct 3 version: r29.2
URL: https://editor.construct.net/
Date: Sat May 20 2017 08:26:49 GMT-0400 (Eastern Daylight Time)
Uptime: 4176.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

[HWAS.zip](https://github.com/Scirra/Construct-3-bugs/files/1016155/HWAS.zip)

</details>

**Comment by 8bitThirsty** [comment]
It's happening very frequently now.  Another save attached.

Error report information
Type: unhandled rejection
Reason: Error: The source image cannot be decoded.
Construct 3 version: r29.2
URL: https://editor.construct.net/
Date: Sat May 20 2017 08:32:47 GMT-0400 (Eastern Daylight Time)
Uptime: 118 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
[HWAS 2.zip](https://github.com/Scirra/Construct-3-bugs/files/1016160/HWAS.2.zip)

**Comment by 8bitThirsty** [comment]
Ok I found consistent steps to reproduce:
1) Open the project within the HWAS 2.zip folder
2) Navigate to the sprite sheet layout
3) Double click the light orange box looking sprite (HubbleSaucer) (it shouldn't look like a light orange box but it does on my screen see attached screen shots which are in chronological order)
4) Select the Back animation

Expected:
Back Animation Displayed

Actual:
App Crashes

![1](https://cloud.githubusercontent.com/assets/11980014/26275806/c8987a1c-3d37-11e7-944c-ad10bf303a3e.png)
![2](https://cloud.githubusercontent.com/assets/11980014/26275807/c89b2d8e-3d37-11e7-8fc3-48247ba70091.png)
![3](https://cloud.githubusercontent.com/assets/11980014/26275808/c89bb056-3d37-11e7-9c66-cb85f4ad3c6c.png)

**Comment by jaydonteh** [comment]
Thank you for the elaborate report! It's definitely similar to mine https://github.com/Scirra/Construct-3-bugs/issues/284 but yours I believe is the accurate way of explaining it.

**Comment by 8bitThirsty** [comment]
Happened again with different steps to reproduce.
[HWAS 3.zip](https://github.com/Scirra/Construct-3-bugs/files/1016356/HWAS.3.zip)


1) Created new sprite in layout "Spritesheet"
2) Added "Front" animation with imported png images
3) Added "Right" animation with imported png images
4) Right clicked on "Right" animation title with the intention on duplicating the animation

Expected:
Right click option drop down box appears

Actual:
System crashed

Error report information
Type: unhandled rejection
Reason: Error: The source image cannot be decoded.
Construct 3 version: r29.2
URL: https://editor.construct.net/
Date: Sat May 20 2017 13:12:40 GMT-0400 (Eastern Daylight Time)
Uptime: 814.3 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by DiegoScirra** [comment]
@8bitThirsty

The problem with your project is that it is already corrupted. Anything that you do in it will likely produce unexpected results.

I fixed one of the projects you posted, so you should be able to continue working on it.

[HWAS 4.zip](https://github.com/Scirra/Construct-3-bugs/files/1021944/HWAS.4.zip)
 
I can't do much about the real problem though, unless I have reproduction steps that lead to saving a corrupted project file.

**Comment by 8bitThirsty** [comment]
I deleted the corrupted sprite and have moved on already.  It was some image files on the back animation that didn't load in correctly for some reason.  They were png images and I loaded them in the same as many other sprites and I was duplicating and deleting frames but that is all I can really remember about it.
