### ISSUE TITLE
Crash after deleting sprite instance in family and container then deleting from project

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2920]
## Problem description

Deleting an object inside family and container from the project after deleting an instance of the targeted object will crash Construct.

## Attach a .c3p

https://www.dropbox.com/s/goa9fvyobxofazw/Crash%20after%20deleting%20sprite%20instance%20in%20family%20and%20container%20then%20deleting%20from%20project.c3p?dl=0

## Steps to reproduce

1. Delete one of the instances in the layout
2. Delete the object you just deleted an instance of from project all together.

## Observed result

Crash.

## Expected result

The object gets removed from the container and family and then deleted from the project without experiencing a crash.

## More details

For this crash to happen:
The object that is being deleted must be in a container and a family.
The container objects must also be in a family.

**Affected browsers/platforms:** 
Desktop

**First affected release:** 
Only tested on r147.2

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r1472/main.js, line 82, col 153777
Message: Uncaught Error: object type is deleted
Stack: Error: object type is deleted at Object.ǃVv (https://editor.construct.net/r1472/main.js:82:153783) at t.ǃj_ (https://editor.construct.net/r1472/main.js:82:173682) at n.ǃzk (https://editor.construct.net/r1472/components/bars/propertiesBar/propertiesBar.js:1:34248) at n.ǃyn (https://editor.construct.net/r1472/components/bars/propertiesBar/propertiesBar.js:1:25490) at n.ǃLI (https://editor.construct.net/r1472/components/bars/propertiesBar/propertiesBar.js:1:8309) at Object.ǃokH (https://editor.construct.net/r1472/components/bars/propertiesBar/propertiesBar.js:1:718) at Object.ǃoLu (https://editor.construct.net/r1472/main.js:2:206683) at Object.ǃoLD (https://editor.construct.net/r1472/main.js:2:206830) at https://editor.construct.net/r1472/main.js:2:206296
Construct 3 version: r147.2
URL: https://editor.construct.net/r1472/
Date: Mon May 06 2019 12:19:58 GMT+1000 (Australian Eastern Standard Time)
Uptime: 2413.5 s

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r147.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, good catch. Fixed for next release.
