### ISSUE TITLE
Crash when closing a project with a layout/event sheet tab in a separate independent window

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#2921]
## Problem description

If you separate an event sheet or layout tab to a completely independent window all together (so you can read it on a second screen), then close the project in that state, Construct will crash.

## Attach a .c3p

https://www.dropbox.com/s/plmnms1bf1fs9a9/Crash%20when%20closing%20a%20project%20with%20an%20event%20sheet%20in%20a%20separate%20dialogue%20window.c3p?dl=0

## Steps to reproduce

1. Separate the event sheet or layout tab to a completely independent window, so down the bottom of the task bar you have two construct windows open on your PC. 
2. Right click your project name in the project pane and close it
3. Construct will react normally but the separate dialogue window will not - move the dialogue window around or try to close it.

## Observed result

Construct will crash.

## Expected result

Construct should just close the project and all independent windows associated with that project without crashing (If changes were made, ask to save etc).

## More details

**Affected browsers/platforms:**
Desktop

**First affected release:** r147.2 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r1472/main.js, line 2, col 95741
Message: Uncaught TypeError: expected HTML element
Stack: TypeError: expected HTML element at Function.ǃGl (https://editor.construct.net/r1472/main.js:2:95747) at Function.ǃVY (https://editor.construct.net/r1472/main.js:2:253598) at Object.ǃojj (https://editor.construct.net/r1472/main.js:2:259707) at d.ǃaT (https://editor.construct.net/r1472/main.js:2:263329) at Object.ǃowH (https://editor.construct.net/r1472/main.js:2:340819) at https://editor.construct.net/r1472/main.js:2:338113
Construct 3 version: r147.2
URL: https://editor.construct.net/r1472/
Date: Mon May 06 2019 13:11:15 GMT+1000 (Australian Eastern Standard Time)
Uptime: 32.5 s

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r147.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, good catch. Fixed for next release.
