### ISSUE TITLE
New Functions - keyboard shortcut missing to edit an existing parameter

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2923]
## Problem description

Parameters of a function can be navigated using the arrows of the keyboard.
Pressing Enter won't open the edit dialog though (unlike for conditions).

## Attach a .c3p

Use the Function maps example.

## Steps to reproduce

1. Event 5 click "ColorType" parameter
2. Use the up and down arrows.
3. Press enter

## Observed result

The arrows allow to select the other parameter ("Message")
Pressing enter has no result.

## Expected result

Pressing enter to open a dialog allowing to edit the parameter.

**Comment by AshleyScirra** [comment]
Thanks, well spotted. Fixed for next release.
