### ISSUE TITLE
Built-in Function Parameters does not update after function is moved

### ISSUE THREAD

**Issue by jarnMod** [Scirra/Construct-3-bugs#2925]
## Problem description
The editor does not update the function parameters (in action block) when the built-in function block is moved.

## Attach a .c3p
I don't know how to attach, so I provide DL link
https://www.dropbox.com/s/pzdc8yd7so0v9x2/bugDemon.c3p?dl=0

## Steps to reproduce
1. Click the function event
2. CTRL+X the function
3. Go to Event Sheet 2 and CTRL+V
4. Come back to Event sheet 1

## Observed result
1. See the button action that calls the function. The call is there, as well as the parameters
2. Double Click the function call. You can see that Actual value being ""

## Expected result
Either the function call in Observed 1 is ""
Or the parameter value is the same as shown in Observation 1 action block*

*I think this will be more convenient

## More details
The game is running with the parameter value = "", not the one shown in editor. 
I've tried it on Web Editor both in chrome and installed as an app.

**Affected browsers/platforms:**
Web editor, haven't tried any other platform

**First affected release:** 
r148 stable

## System details
<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.131
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
C3 release: r148 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.4 gb
Storage usage (approx): 338 mb (4.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
