### ISSUE TITLE
Issue about converting old functions to Built-in Functions where old functions were disabled

### ISSUE THREAD

**Issue by renatofd** [Scirra/Construct-3-bugs#2926]
## Problem description

One issue I noticed here trying to convert the functions of a project, is that when I convert a function, all actions where the function is called that it is originaly disabled, the respective action of the build-in function is not disabled.

Example: (tried to upload screenshots, but it seems image upload is not working, so I'm using 'Copy as text' feature)

Old function :

-> [DISABLED] Function: Call "test" ()

Converted to build-in-function:

-> Functions (built-in): Call test

It seems like a little issue, but in large projects it can create big trouble.

## Steps to reproduce

Open the c3p file attached;
Convert the 'test' fuction to built-in function

## Observed result

Note that the result action on 'start of the layout' event was disabled before, but not after the convertion

## Expected result

The action should keep disabled

[function.zip](https://github.com/Scirra/Construct-3-bugs/files/3157465/function.zip)

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
