### ISSUE TITLE
Construct 3 Not offering Function Object Type for certain students?

### ISSUE THREAD

**Issue by kclinch** [Scirra/Construct-3-bugs#2927]
## Problem description

When certain students are adding in a function object, they don't have function as an option. Most students are fine, but a few don't have it.

## Steps to reproduce

On Game layer, right click on Object Types, Click add new object type, then choose function, but function isn't an option for some.

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details
Using Chrome browser.

**Comment by shortercode** [comment]
The function object has been depreciated in favour of the new inbuilt functions as of stable release 148 ( published yesterday ) . Projects which include the old function object will still be able to use it, but it won't appear in the "insert object" menu anymore. It is likely that the students that can still see it are on an older version of C3. 

You can read more about the new inbuilt functions on the release notes [here](https://www.construct.net/en/make-games/releases/stable/r148)

**Comment by kclinch** [comment]
Thank you!
