### ISSUE TITLE
Exported project with Physics and Worker enabled doesn't work

### ISSUE THREAD

**Issue by RichardAstrom** [Scirra/Construct-3-bugs#2928]
A project that uses the Physics plugin and has Worker enabled doesn't run. It does work in preview mode but not as an exported HTML5 project.

It also works fine if Worker is not enabled.

I get the following error in Chrome:

![worker_error](https://user-images.githubusercontent.com/3534495/57436079-405f3c00-723f-11e9-8b7a-5d2a9e7784de.png)

Here's the link to the hosted project: [https://quizzical-easley-fcc469.netlify.com/](https://quizzical-easley-fcc469.netlify.com/)

## Attach a .c3p

[worker_physics.zip](https://github.com/Scirra/Construct-3-bugs/files/3160885/worker_physics.zip)

## Steps to reproduce

1. Export the project as Web HTML5.
2. Upload it to a host.
3. Test it.

## Observed result

Black screen and an error message.

## Expected result

It should run?

## More details

Chrome/Windows 10/Desktop 

r148

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.131
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
C3 release: r148 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 564 mb (4.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)</details>

**Comment by AshleyScirra** [comment]
This took quite a bit of refactoring, since the underlying problem is some addons specify external dependencies, and the dependency system didn't properly support indicating whether dependencies should load in the DOM or in the worker. I think this is all sorted out for the next release though.
