### ISSUE TITLE
Physics settings on created object (initial disabled physics) no longer change (r148)

### ISSUE THREAD

**Issue by SwiftIllusion** [Scirra/Construct-3-bugs#2929]
## Problem description
As of the latest stable release (Construct 3 r148), part of my project is broken because changing the settings of physics on a created object, before enabling physics, no longer works.
Note this still works for at least the orbit behavior I included in the below attached .c3p as part of the demonstration.

## Attached .c3p
[ObjectCreatePhysicsBehavior.zip](https://github.com/Scirra/Construct-3-bugs/files/3163250/ObjectCreatePhysicsBehavior.zip)

## Steps to reproduce
-- 1. Play in debug mode and view Sprite, you'll see its density is 1, even though it is set to 5 just after creation.
Note that the gravity setting changes correctly (though it won't work if above the Sprite creation/before a physics object exists). And that Sprite2 can be both pinned and have its orbit changed before enabling the orbit behavior.
(See 'Storage' layout for their default settings/the fact both aren't enabled by default)
-- 2. Move 'physics enabled' above 'set physics density to 5' and run in debug mode to view Sprite, and that its physics density is now 5.

## Observed result
No changes to objects physics settings
## Expected result
Changes to objects physics settings

## More details
_The reason I encountered this issue, and why I had to change physics settings before enabling it in my project:_ I needed to create a second object and join them together with a physics joint without physics enabled otherwise they'd push out of eachother because of my setup.
Additionally I've tried since finally working out this bug just moving the physics settings changes below when I enable the physics, however that completely changes the way forces is applied to the object, which was crafted over many iterations for a specific experience.

**Affected browsers/platforms:** Chrome/Windows (tested in Construct 3 desktop version)

**First affected release:** Construct 3 r148

## System details
<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r148 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 35 gb
Storage usage (approx): 326 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's helpful if you can identify which beta release first started having the problem.

**Comment by SwiftIllusion** [comment]
Wasn't using the beta releases, was using stable desktop version so just discovered it in the new stable.
I made a smaller mockup of the problem to test in the beta releases on the site, and it happens immediately from beta R143. Tried 144/145 too with the same result.
https://i.gyazo.com/851a63bd54b6f231736c8063d8e189e6.png

**Comment by AshleyScirra** [comment]
Here's a project I saved with r142.3 (last stable release) which demonstrates exactly the same issue: 
[physics-set-density.zip](https://github.com/Scirra/Construct-3-bugs/files/3167679/physics-set-density.zip)

Therefore it appears this is not a regression in r148. Moving the 'Set enabled' action fixes it because you cannot set the density of a disabled Physics behavior, because when it is disabled it destroys the physics body, which is what has a density. This has been the case ever since Construct 2. So I think you probably just changed something in your project and misattributed this to the Construct update.
