### ISSUE TITLE
tokencount returns wrong numbers

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2930]
## Problem description

Using tokencount returns 0 if there's no text, 1 if there is anything and 2 if it finds the char once, 3 if it finds it twice, etc.

## Attach a .c3p

[TokenCountBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3167793/TokenCountBug.c3p.zip)

## Steps to reproduce

1. open project
2. notice the token is 1 for char 'a' where in the input box there's char 'e'
3. add an 'a'
4. notice tokencount is now 2

## Expected result

I expect for tokencount to return the correct number.

## More details

**Affected browsers/platforms:** 

**First affected release:** since beta

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.131
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
C3 release: r148 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 60 gb
Storage usage (approx): 240 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX550/550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It is counting tokens using the string as a separator. That's different to counting how many occurences of the character there are. A more obvious example is using `,` as a separator:

empty string = no tokens
`foo` = 1 token
`foo,bar` = 2 tokens (one occurence of token character `,`)
etc.

**Comment by JeFawk** [comment]
OOOooooooohh wow kinda weird :octocat: thanks for clarifying
