### ISSUE TITLE
C3 desktop crashes - with repo

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2933]
## Problem description

After many attempts on reproducing the bug that was crashing on me 20+ times a day I managed to find out that all the desktop version of C3 until r69 (excluding this one) crash when opening a project and then opening the dev tools (to see the console which I use to log info to).

Opening Demonoir and then opening the dev tools of the preview, subsequently closing the preview crashes the C3 desktop app.

I reproduced the issue a few times on a machine and then on another one as well.

## Attach a .c3p

This is the video for the crashes (remove .zip): 
[2019-05-12 22-06-19.mp4.zip](https://github.com/Scirra/Construct-3-bugs/files/3170458/2019-05-12.22-06-19.mp4.zip)

## Steps to reproduce

1. Use the latest C3 desktop app (74 https://downloads.scirra.com/c3-desktop/win64/construct3-win64-c74-stable.zip )
2. Open Demonoir 
3. Preview it as the video shows
4. Open the dev tools
5. Close the preview

## Observed result

Notice how the whole app crashes

## Expected result

The app not to crash

## More details

**Affected browsers/platforms:** Desktop

**First affected release:** started happening since a few months ago, i wrote a report ~ 2 weeks after it occurred first which was closed cause I couldn't provide any repo steps

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r148 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 349 gb
Storage usage (approx): 156 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX550/550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can reproduce, but since it doesn't happen in Chrome and isn't a JavaScript error, it would appear to be an NW.js-specific crash, so it would be best to report it directly to NW.js on [their issue tracker](https://github.com/nwjs/nw.js/issues). Link me to the issue and I'll follow it to answer any Construct-specific questions that come up.

**Comment by JeFawk** [comment]
@AshleyScirra their bug report asks that the app is using the latest NW.js which is 0.38.2 while the C3 desktop app uses 0.38.0

**Comment by AshleyScirra** [comment]
I can still reproduce with 0.38.2 so just file it anyway. You can test any version of nw.js by downloading it, extracting it over the C3 desktop app, and running nw.exe.

**Comment by JeFawk** [comment]
@AshleyScirra  https://github.com/nwjs/nw.js/issues/7051 thanks
