### ISSUE TITLE
Breakpoints do not trigger in function blocks that get executed as expressions. 

### ISSUE THREAD

**Issue by eberkain** [Scirra/Construct-3-bugs#2934]
Having a step-through debugging tool and knowing how to use it is one of the most powerful pieces of any programming IDE.   As I do more and more advanced things in C3 I find that this one fails me and I have to rely on printing variables out to text objects to see what is going on.  

If you place a breakpoint inside a function body that is called as an expression, then the breakpoint does not trigger.  Likewise, if you are stepping through code and get to an expression that leads to a function somewhere, you do not get taken to that function, it just skips over to the next statement and treats the function call like any other assignment statement. 

[functionbug.zip](https://github.com/Scirra/Construct-3-bugs/files/3170732/functionbug.zip)

## Steps to reproduce

1. Start the project in debug layout or project->debug 
2. if the squiggle is moving, then the event triggered and the function was called

## Observed result

the debugger never kicked in

## Expected result

The debugger should have paused execution when the breakpoint was hit

## More details

I believe that this is probably a feature that was left out for technical reasons.  With the recent push to making C3 a more robust development tool with new behaviors and the built-in functions,  I hope this topic will be revisited.  

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r148 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 105 gb
Storage usage (approx): 451 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
This is a known limitation of the debugger, because the engine does not support suspending execution during expression evaluation, and implementing this would be very difficult and complicated. Closing since we don't currently have any plans to support this, if you still want it you can post it as a suggestion to the suggestion platform instead.
