### ISSUE TITLE
Kongregate export does not seem to support webm files

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2935]
Uploading a game to Kongregate, the console seems to indicate audio files are not compatible.

## Problem description

Use the kongregate exporter to upload a simple test project.
Audio does not work, console brings up issue about decodeAudioData and the encoding format for the file

## Attach a .c3p

https://kyatric.com/c3/c3p/2019.05.13.Audio_Kongregate_Test.c3p
https://kyatric.com/c3/c3p/Audio_Kongregate_Test.zip

## Steps to reproduce

1. Export as Kongregate (or use the provided zip file)
2. Follow Kongregate steps in order to upload
3. Once in preview, click the button, open the console

## Observed result

No sound played,
The console raises some errors : 

Made with Construct 3, the game and app creator :: https://www.construct.net 
[C3 runtime] Hosted in DOM, rendering with WebGL 2 [ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)] 

Les données passées à decodeAudioData possèdent du contenu de type inconnu. 
(=> Datas passed to decodeAudioData own content of unknow type)

[Construct 3] Failed to load audio 'media/chip_kick_1.webm':  DOMException: "MediaDecodeAudioDataUnknownContentType"
    g_FA https://game308015.konggames.com/gamez/0030/8015/preview/scripts/main.js:1
EncodingError: The given encoding is not supported.

## Expected result

Sound to play, no error in the console

**Comment by AshleyScirra** [comment]
The Kongregate export is simply a re-branded HTML5 export, there is no difference to the files. If the export works normally elsewhere, this is probably an issue with Kongregate's servers serving the files incorrectly, so it'll need to be taken up with them.
