### ISSUE TITLE
Random Movement Problem

### ISSUE THREAD

**Issue by aryd44** [Scirra/Construct-3-bugs#2936]
I've created an abbreviated version of my larger project to demonstrate a problem with random movement.  See attached zip file.

[Random-Movement.zip](https://github.com/Scirra/Construct-3-bugs/files/3174375/Random-Movement.zip)

There's a PLAYER object and four KILLER objects.  They move with the Tile Movement behavior.  KILLERs additionally have the SOLID behavior.

After PLAYER moves one square left or right, the four KILLERs are supposed to move randomly LEFT or UP depending on a random(2) result of 0 or 1.

The problem is that ALL of the KILLERs are moving left or up in unison rather than independently left or up.  Since each KILLER is a separate instance, shouldn't they move independently?

**Comment by AshleyScirra** [comment]
It's a mistake in your events. Please post to the forum for help with your projects. Bug reports here are required to follow the guidelines in order to prove the problem is not a mistake in your events.
