### ISSUE TITLE
Canvas doesn't paste with right opacity

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2938]
Canvas doesn't keep in mind the opacity to paste with when the paste action is called.

## Attach a .c3p
[CanvasPastingOpacityBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3177248/CanvasPastingOpacityBug.zip)

## Steps to reproduce

1. Change the sprite's opacity
2. Hit play

## Observed result

All of the pasted instances have the right position and angle but keep the final sprite's opacity

## Expected result

The canvas should remember the opacity as well when the paste action is called.

## More details
I am making a game with a dynamic light system with casted shadows and wanted to make it so lights can have a sharpness value and the lower the sharpness the blurrier the shadow. Canvas cannot paste invisible objects when pasting with effects so I decided to make my own blur effect, but it looks like this because of the bug
![image](https://user-images.githubusercontent.com/11213825/57692888-cca6a000-763f-11e9-90d9-16ff77d51c39.png)

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
