### ISSUE TITLE
Objects are hidden after preview of particles object

### ISSUE THREAD

**Issue by yojona** [Scirra/Construct-3-bugs#294]
## Problem description

When I press "Preview" in the particles object, all anothers objects (sprites) are hidden, I can select them, but they are transparent even after uncheck "preview" box in particles properties.

## Attach a .c3p

[particles.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1016539/particles.c3p.zip)

## Steps to reproduce

1. Open editor.construct.net
2. Open project
3. check "Preview" in particles properties

## Observed result

Objects (sprites) are hidden

## Expected result

Keep watching all my sprites.

## Affected browsers

* Chrome: yes

## System details

MacOS Sierra 10.12.4

## EDIT
*  Works perfectly on windows, the problem is in Chrome for Mac :c

**Comment by damjancd** [comment]
Can confirm this, also on Chrome on a Mac.

**Comment by AshleyScirra** [comment]
Thanks, I could reproduce on macOS, should be fixed for r35.
