### ISSUE TITLE
Arrow keys Move Object Undo bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#2943]
## Problem description

This issue was addressed years ago on #756, but it seems to be an unintentional partial fix. Apparently, moving more than one of any object (one at a time) using arrow keys will cause the undo to not work properly for the 2nd, 3rd and other following moved objects with arrow keys.

## Attach a .c3p

[undoBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3181809/undoBug.c3p.zip)

## Steps to reproduce

1. Select the first green square sprite.
2. Move it to the right using the right arrow key by one step. (Note project has snap to grid on.)
3. Select the second green square sprite.
4. Move it to the right using the right arrow key by one step.
5. Undo.

## Observed result

The first sprite moved back to its previous position but the second isn't, even if it was the most recently moved object with the arrow key.

## Expected result

To undo to their previous position.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.131
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
C3 release: r149 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.5 gb
Storage usage (approx): 227 mb (3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) UHD Graphics 617
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release. Note with the fix you'll get 2 undo points, since changing the selection creates a new undo point for arrow key movement.
