### ISSUE TITLE
New function don't have their return value set properly when using c3_callFunction

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2944]
## Problem description

The new built-in functions don't have the return value set properly when called from c3_callFunction, it's 0 compared to the old functions which work.

## Attach a .c3p

[c3_callFunction issue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3181949/c3_callFunction.issue.c3p.zip)

## Steps to reproduce

1. open project
2. open preview
3. open console

## Observed result

You will see 0 and 1366 on different lines.

## Expected result

I expect the new built in function to work from c3_callFunction because it's extremely useful.

## More details

**Affected browsers/platforms:**  Chrome

**First affected release:** noticed it now in r148, didn't use it before

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.131
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
C3 release: r148 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 60 gb
Storage usage (approx): 245 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX550/550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by JeFawk** [comment]
Seems actually that c3_callFunction doesn't quite work.
Only the 2nd one works in this small example (triggered on button click)

![image](https://user-images.githubusercontent.com/7268697/57773696-4bbfd500-7721-11e9-872b-fb0d9ac10566.png)

**Comment by Wackytoaster** [comment]
I had noticed that c3_callFunction will always attempt to call the old plugin. You have to entirely delete the old function plugin from the project for it to call the new function block.

**Comment by JeFawk** [comment]
Wow you're right! Thanks for the help @Wackytoaster !

**Comment by AshleyScirra** [comment]
@Wackytoaster is right, this is currently by design.

**Comment by JeFawk** [comment]
Shouldn't c2_callFunction call the old plugin and c3_callFunction call the new one?
