### ISSUE TITLE
[r149] Bookmarking Functions will crash the bookmarks bar

### ISSUE THREAD

**Issue by 7Soul** [Scirra/Construct-3-bugs#2945]
## Problem description

If you bookmark a function and try to open the bookmarks bar, C3 crashes. Then opening the project again gives a "project is corrupted" message but it opens normally, with the bookmarks bar open but empty

## Attach a .c3p

https://drive.google.com/open?id=1rfcJ23_5GRG74lhijKAyACQp4NnwcYww

## Steps to reproduce

1. Create a function and bookmark it
2. Open the bookmarks bar

## More details

C3 version r149

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected event object @ Error: unexpected event object at Object.ǃUCa (https://editor.construct.net/r149/components/bars/bookmarksBar/bookmarksBar.js:1:2980) at Object.ǃKbX (https://editor.construct.net/r149/components/bars/bookmarksBar/bookmarksBar.js:1:678) at Object.ǃKXV (https://editor.construct.net/r149/main.js:2:206806) at Object.ǃjk (https://editor.construct.net/r149/main.js:2:206684) at Function.ǃFI (https://editor.construct.net/r149/components/bars/bookmarksBar/bookmarksBar.js:1:5869) at https://editor.construct.net/r149/components/misc/mainMenu/mainMenu.js:1:6803 at new Promise () at Object.ǃUIY (https://editor.construct.net/r149/components/misc/mainMenu/mainMenu.js:1:6416) at https://editor.construct.net/r149/components/misc/mainMenu/mainMenu.js:1:7109
Stack: Error: unexpected event object at Object.ǃUCa (https://editor.construct.net/r149/components/bars/bookmarksBar/bookmarksBar.js:1:2980) at Object.ǃKbX (https://editor.construct.net/r149/components/bars/bookmarksBar/bookmarksBar.js:1:678) at Object.ǃKXV (https://editor.construct.net/r149/main.js:2:206806) at Object.ǃjk (https://editor.construct.net/r149/main.js:2:206684) at Function.ǃFI (https://editor.construct.net/r149/components/bars/bookmarksBar/bookmarksBar.js:1:5869) at https://editor.construct.net/r149/components/misc/mainMenu/mainMenu.js:1:6803 at new Promise () at Object.ǃUIY (https://editor.construct.net/r149/components/misc/mainMenu/mainMenu.js:1:6416) at https://editor.construct.net/r149/components/misc/mainMenu/mainMenu.js:1:7109
Construct 3 version: r149
URL: https://editor.construct.net/r149/
Date: Wed May 15 2019 14:05:37 GMT-0300 (Brasilia Standard Time)
Uptime: 307.3 s

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r149 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
