### ISSUE TITLE
New functions crash when pasting code with var they don't have, adding it as param and pasting again

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2948]
## Problem description

New functions crash when pasting code with var they don't have, adding it as param and pasting again as shown in this gif:

![Animation](https://user-images.githubusercontent.com/7268697/57876558-4b593400-781e-11e9-9df1-f12f4d49b3d6.gif)

## Attach a .c3p

[FunctionIssue (1).c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3188409/FunctionIssue.1.c3p.zip)

## Steps to reproduce

1. open the attached project
2. try to copy paste the block from on start of layout in the function
3. notice you cant since you're missing the Variable1
4. add it as a parameter in the function
5. copy - paste again

## Observed result

C3 crashes

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r148

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r148/main.js, line 2, col 126414
Message: Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
Stack: Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node. at window.ǃYD.ǃcn (https://editor.construct.net/r148/components/editors/eventSheetView/eventSheetView.js:1:53966) at window.ǃIh.ǃcP (https://editor.construct.net/r148/components/editors/eventSheetView/eventSheetView.js:1:50858) at window.ǃIh.ǃcu (https://editor.construct.net/r148/components/editors/eventSheetView/eventSheetView.js:1:49190) at new window.ǃIh (https://editor.construct.net/r148/components/editors/eventSheetView/eventSheetView.js:1:57080) at Function.ǃk.ǃm (https://editor.construct.net/r148/main.js:2:126393) at e.ǃfP (https://editor.construct.net/r148/main.js:82:299824) at n.ǃgQm (https://editor.construct.net/r148/main.js:82:295809) at n.ǃgQm (https://editor.construct.net/r148/main.js:82:310376) at https://editor.construct.net/r148/main.js:82:295673 at window.ǃia.ǃHb (https://editor.construct.net/r148/components/editors/eventSheetView/eventSheetView.js:1:41845)
Construct 3 version: r148
URL: https://editor.construct.net/
Date: Thu May 16 2019 23:36:11 GMT+0300 (Eastern European Summer Time)
Uptime: 1374.8 s

Platform information
Browser: Chrome
Browser version: 74.0.3729.131
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
C3 release: r148 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX550/550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by JeFawk** [comment]
Sometimes this happens randomly too, the repo steps provide 100% but the random occurrences, well...

So maybe have that in mind for a fix 🍰

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in the next release.
