### ISSUE TITLE
Copy text from elsewhere and pasting it in editor is weird, maybe it's not pasting as plain text but has formatting

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2949]
## Problem description

Copy text from Google Spreadsheets and pasting it in the expression editor is weird, maybe it's not pasting as plain text but has formatting? 

## Steps to reproduce

Cntrl+C a cell in Google Spreadsheets

![image](https://user-images.githubusercontent.com/5744908/57966625-06590d00-7998-11e9-95a7-44d5bb09858f.png)

Go to expression editor
![image](https://user-images.githubusercontent.com/5744908/57966658-5e900f00-7998-11e9-8dea-fe7c9fea3938.png)

Cntrl + V to paste in there

## Observed result

OwO what's this?
![image](https://user-images.githubusercontent.com/5744908/57966665-75cefc80-7998-11e9-81a3-a87c7b494a3e.png)

If I paste the data here, I don't get the same effect: gamepad_reset

## Expected result

![image](https://user-images.githubusercontent.com/5744908/57966667-81babe80-7998-11e9-995e-14334c7bc5a3.png)

## More details

C3 desktop Stable

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r148 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 118 gb
Storage usage (approx): 920 mb (0.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by alastajj** [comment]
I'm not sure if this is just a poor design decision by Google, or if it's a formatting problem in C3, or if I'm doing something wrong.

**Comment by 7Soul** [comment]
I tested this here and it only happens if you paste it inside quotes. There's a second delay and then the formatting text appears

Btw you can use Ctrl+Shift+V to paste without formatting, this is a Windows feature

**Comment by shortercode** [comment]
Okay I think I have a workaround for this, it would be appreciated if people could look out for any errors in text selection, syntax highlighting and undo when pasting text. Mechanically text selection is complicated and somewhat fragile so this might have broken something.

This might fix a related syntax highlighting error when copying text from a web browser to the expression editor, when not in a string literal as above.

**Comment by shortercode** [comment]
Revision is included in the next release
