### ISSUE TITLE
The Construct3 Game Jam user Temporary Licence is over?

### ISSUE THREAD

**Issue by sielxm3d** [Scirra/Construct-3-bugs#295]
I need to acomplish my game for the Jam attempy, but my license is free now, the new version is logango in my account as free user, it should be the theme license of GameJam, what is happening? The contest ends on the 28th and today, the 20th, I can not get access.

**Comment by yojona** [comment]
Logout and login.

**Comment by AshleyScirra** [comment]
If you see the cloud with the cross through it as the user icon, try log out and log in again. The game jam is still running.
