### ISSUE TITLE
Set Vector Y For The Platform Behavior Doesn't Work

### ISSUE THREAD

**Issue by JackieChan2** [Scirra/Construct-3-bugs#2950]
## Problem description

If you jump and then immediately set the vector y, the platform behavior's vector Y will not change. This bug also happens in construct 2.

## Attach a .c3p
[Set Vector Y bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3195378/Set.Vector.Y.bug.zip)

## Steps to reproduce

Run the project in layout 1 and you will see that the vector y is not changing even though I'm setting it to -2000

However, if you run layout 2 it will work because there is a "Wait" action before changing the vector y. The bug only happens if you set the vector y right after a jump.

## Observed result

The vector y is not changing.

## Expected result

The vector y should change to -2000

**Affected browsers/platforms:** 

All browsers

**First affected release:** 

r148

## System details

<details><summary>View details</summary>

Browser: Chrome
Browser version: 74.0.3729.157
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
C3 release: r148 (stable)
Language setting: en-US

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Jumping sets the platform vector Y. Behaviors process their movement at the end of the tick, so the jump will override the vector Y you set in events at the end of the tick. There's no point doing this anyway: since jumping sets the vector Y, if you want to manually set the vector Y, just set it and don't use the jump action.
