### ISSUE TITLE
"Oops! Something went wrong"

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#2951]
## Problem description

I cut an action with CTRL X and pasted it in another condition block, on the same event sheet, then C3 suddenly gave the Oops! Something went wrong-screen.
The reason why I am filing a bug report, is because the Oops! Something went wrong-screen is requesting me to do so.

## Attach a .c3p

No .c3p attached.

## Steps to reproduce

I could not reproduce it.

## Observed result

I pasted with CTRL+V and I saw an error message from C3.

## Expected result

Press CTRL+V and see the action appear in a condition block.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r149/main.js, line 85, col 316263
Message: Uncaught ReferenceError: c is not defined
Stack: ReferenceError: c is not defined at t.ǃjjL (https://editor.construct.net/r149/main.js:85:316263) at e.ǃfU (https://editor.construct.net/r149/main.js:85:325303) at o.ǃLk (https://editor.construct.net/r149/components/editors/eventSheetView/eventSheetView.js:1:42934) at o.ǃVV (https://editor.construct.net/r149/components/editors/eventSheetView/eventSheetView.js:1:40952) at Array. (https://editor.construct.net/r149/components/editors/eventSheetView/eventSheetView.js:1:2841) at ǃt.Event.ǃKdm.ǃKdI (https://editor.construct.net/r149/main.js:2:192903) at ǃt.ǃa.ǃtR.ǃKin.dispatchEvent (https://editor.construct.net/r149/main.js:2:190938) at ǃt.ǃa.ǃtR.ǃKin.ǃVV (https://editor.construct.net/r149/main.js:2:260944) at d.ǃVV (https://editor.construct.net/r149/main.js:2:263873) at HTMLDocument. (https://editor.construct.net/r149/main.js:2:262188)
Construct 3 version: r149
URL: https://editor.construct.net/r149/
Date: Sun May 19 2019 22:07:34 GMT+0200 (Midden-Europese zomertijd)
Uptime: 2199.1 s

Platform information
Browser: Chrome
Browser version: 74.0.3729.157
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
C3 release: r149 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce 315 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by rogerty** [comment]
I think the problem lies here: 
- if you have a condition block with a local variable
- and in this condition block you have an expression that calls the local variable (for example "set locvar to 1")
- if you cut (CTRL+X) this action
- and paste it outside the scope of the local variable
- an error message appears from C3.

**Comment by AshleyScirra** [comment]
Fixed for next release.
