### ISSUE TITLE
Changing name/value of global constant variable causes crash, renders project unopenable, and corrupts browser's local storage

### ISSUE THREAD

**Issue by AySquirrel** [Scirra/Construct-3-bugs#2953]
## Problem description

I changed the name and value of a global constant variable in my project, and got a crash and error report--whatever, not uncommon. I then save the project, restart, and attempt to open the saved project. However, upon opening the project, I immediately get a new popup, something I haven't seen before:

![InvalidExpression](https://user-images.githubusercontent.com/46288002/57991132-8358b500-7a72-11e9-9868-98f04096feb3.PNG)

I wasn't on a previous version of construct, and I can't open the file on ANY version of construct without immediately receiving this pop up and being forced to close the project, unable to make any changes to it.

So that was a little annoying, but okay, I can go to one of the backups in my browser's local storage... Except that performing this sequence of events causes all recent projects to fail to load, and checking chrome's local storage simply says "Failed to refresh file list", no matter how many times I refresh:

![FailedToRefresh](https://user-images.githubusercontent.com/46288002/57991239-2b6e7e00-7a73-11e9-85db-c8caf3838295.PNG)

## Attach a .c3p

[VariableBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3195942/VariableBug.zip)

## Steps to reproduce

CAUTION: Please read the observed result before performing these steps, as doing so appears to tamper with recent projects in browser storage. Not too sure how this works, but I've gotten it to happen every time on multiple browsers, so I would recommend performing this on a browser where no important C3 files are stored.
 
1. Open the project, and go to event sheet 1
2. Double-click "Variable123" to open up the dialogue box
3. Change the name to "Variable1", and change it's initial value to 0
4. Press "Okay" to confirm and close the dialogue box
----------*First Crash*----------
5. To observe the second part of the bug, when the crash report comes up, save the project, and then restart Construct 3
6. Attempt to open the project you saved
7. When the "Invalid expressions" dialogue box pops up, close the project
8. Attempt to load a project from the browser's local storage

## Observed result

Construct 3 crashes, saving and reopening bricks the project and permanently opens up the "Invalid expressions" dialogue box when attempting to open, AND CRITICALLY; all recent projects fail to load from browser's local storage

## Expected result

The variable's name and value to be changed with no crash, and local storage to remain intact

## More details

A few interesting things to note:

1. This only works with global CONSTANT variables; doing so with a normal global variable causes no crash
2. Based on the invalid expressions dialogue box that comes up, I gather that the first bug has to do with changing values of a variable on one event sheet that also appears on other event sheets that aren't currently open BECAUSE:
3. The crash also only occurs if event sheet 2 is NOT OPEN; opening event sheet 2 and then performing the steps causes no crash

**Affected browsers/platforms:** 

Chrome, Opera

**First affected release:**

Not something new; can be observed as far back as r120

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Empty expression: You must enter an expression.
Construct 3 version: r148
URL: https://editor.construct.net/
Date: Sun May 19 2019 20:53:30 GMT-0500 (Central Daylight Time)
Uptime: 106.4 s

Platform information
Browser: Opera
Browser version: 60.0.3255.95
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.95
C3 release: r148 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I've fixed the crash at step 4 for the next release. As for the local storage issue, none of the steps involved local storage at all, so we have nothing to go on to investigate it, and I suspect it is actually unrelated to the crash being reported. Still, assigning @shortercode in case he can divine anything from this.

**Comment by shortercode** [comment]
I've tried the complete replication and I don't see any effect to browser storage, which is about what I expected as none of those steps involve browser storage until step 8. Are you sure browser save was not broken before performing these steps? If it wasn't could you check the browser console for any errors for me.

**Comment by AySquirrel** [comment]
Positive that is was working before; I've saved and made new projects in local storage and was just able to make it happen again.  This is what the console shows:

![KeyNotDefined](https://user-images.githubusercontent.com/46288002/58048702-cb2e1980-7b10-11e9-928a-735f85d52f7f.PNG)

**Comment by shortercode** [comment]
Ah well that's interesting. That error message doesn't have much ( or really any ) stack information, but I've found what I believe caused it. It's a minor typo in the corruption recovery code for browser saves. Basically there's a small block of code that checks for files that don't have any related metadata ( name, location, modified time, etc. ) and adds them back to the root folder so they aren't lost in event of a partial filesystem corruption. Given that it's only run in unexpected error cases it doesn't get triggered very often... Which is probably why I was unaware there was an issue with it. It's only run when browser file system is initially loaded, but it would prevent browser saves from working if it failed. Unfortunately it doesn't tell us WHY the filesystem is corrupted in the first place. I'm working on something for the next release which might be able to help diagnose further, but I will try your replication again. It might be related to actions you take with browser save prior to performing the replication steps.

**Comment by AySquirrel** [comment]
I see... I'll look into what was done prior to the steps to see if I can find anything specific that may have triggered it.

If you are able to find why this is corrupting the filesystem, though, will I be able to retrieve the missing files from my local storage in a newer release? I do have some other backups downloaded onto my computer that I can use, but quite a bit of work will still be lost if I have to go that far back.... I normally back up to a few locations after finishing a work session, but I wasn't expecting this to happen out of the blue

**Comment by shortercode** [comment]
@AySquirrel It depends on the nature of the corruption, the line that the error I found was on suggests that there are projects without metadata so those projects will likely exist but without a name. The existing code SHOULD recover those files for you once you have that fix but they will have identifier values instead of names. Additionally I have implemented a new feature for the next release that allows you to download the entire contents of your local browser saves in a single ZIP file, this skips the automatic recovery systems so it's possible to see what state your saves are in and access them when the dialog is unable to read them.

**Comment by AySquirrel** [comment]
Oh okay! That's cool

Right now, though, I started messing around trying to save to local storage again, and it turns out that it didn't just remove the ability to open old files--it won't let me save ANY new files to local storage. It just shows the blank list with no option to save, and pressing enter to override it just results in a pop-up that says "Key not defined."  So for the time being I can only save to cloud storage or download a copy... Rather puzzling

**Comment by shortercode** [comment]
That's expected. The first time you use browser save in a session it will initialise itself by reading all the metadata and attempting to recover from any corruptions it finds, this is where it is failing. As it cannot initialise you will not being to interact with it in any way.

**Comment by shortercode** [comment]
@AySquirrel with the release of r151 you should have been able to open your browser saves again, is it working as you expect?

**Comment by shortercode** [comment]
No response and bug is expected to be fixed, so closing this issue. If you are still experiencing problems then I will reopen this issue and review again.
