### ISSUE TITLE
[Theme] Light theme has eye bothering background when previewing a sprite animation with dark background

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#2954]
## Problem description

The Light theme has eye bothering background when previewing a sprite animation with dark background, the contrast is huge!

This is ok
<img width="319" alt="Screenshot_9" src="https://user-images.githubusercontent.com/7268697/58024709-8196fc00-7b1b-11e9-879e-306a715f0aff.png">

This is not ok
<img width="354" alt="Screenshot_8" src="https://user-images.githubusercontent.com/7268697/58024726-88be0a00-7b1b-11e9-8b39-1b90089b6102.png">

## Attach a .c3p

Any project using light theme

## Steps to reproduce

1. open up a blank project
2. create a sprite
3. use light background in the sprite editor
4. preview the animation, notice its background is consistent
5. change the sprite editor background to dark
6. preview the animation

## Observed result

You may get retina burn

## Expected result

No retina burn pls :( 

## More details

**Affected browsers/platforms:**Chrome

**First affected release:** noticed it in r148

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.157
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
C3 release: r148 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 60 gb
Storage usage (approx): 263 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX550/550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Not sure if this is directly related to the theme or integration with code that @DiegoScirra has written so have assigned to @Animmaniac as well.

**Comment by DiegoScirra** [comment]
Fixed.
