### ISSUE TITLE
debug layout won't open r150

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2955]
## Problem description

You can't debug in r150

## Steps to reproduce

1. Open a project
2. Try to debug layout

## Observed result

white screen

![image](https://user-images.githubusercontent.com/2965842/58030873-0720a900-7b28-11e9-86ad-5492a2ee9ed2.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
We had to make a server-side change for this release, it should be working now.
