### ISSUE TITLE
Jump Sustain Blocks Set Vector Y

### ISSUE THREAD

**Issue by JackieChan2** [Scirra/Construct-3-bugs#2957]
## Problem description

If you jump with jump sustain the set vector y action will not work. This bug affects construct 2 as well.

## Attach a .c3p

[Broken Vector Y.zip](https://github.com/Scirra/Construct-3-bugs/files/3198905/Broken.Vector.Y.zip)

## Steps to reproduce

Run the project and press Z when the player jumps.

## Observed result

The vector y is not changing.

## Expected result

The vector y should change to -2000

**Affected browsers/platforms:** 

All browsers

**First affected release:** 

r148

## System details

<details><summary>View details</summary>

Browser: Chrome
Browser version: 74.0.3729.157
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
C3 release: r148 (stable)
Language setting: en-US

</details>

**Comment by AshleyScirra** [comment]
Similar to issue #2950, jump sustain is implemented by the behavior setting the vector Y for the duration of the sustain. If you don't want this, don't use jump sustain and control the vector Y separately.

**Comment by JackieChan2** [comment]
I didn't know jump sustain worked liked that so thank you for that information.  I found this issue when I made a spring object in my game that would launch the player up but it wouldn't launch him when he was using jump sustain.

Another workaround is to temporarily deactivate the player's jump when setting the vector Y, then reactivate the jump after he's launched. This way you can still use the jump sustain feature. Here's an example: 

[Fixed Vector Y.zip](https://github.com/Scirra/Construct-3-bugs/files/3202400/Fixed.Vector.Y.zip)
