### ISSUE TITLE
my project is failed to open and says "check it is a valid Construct 3 single-file (.c3p) project"

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2959]
## Attach a .c3p
.c3p file is send to support@construct.net

## Steps to reproduce

1. open my .c3p project which showing this message

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Closing as will take this up via email. Reports handled here should follow the guidelines to be followed up here.
