### ISSUE TITLE
System:Set value lets you pick and change Constants

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#296]
## Problem description

**Set value** lets you select and change a Constant.

## Attach a .c3p

N/A

## Observed result

<stated>

## Expected result

Constants should not show in the variable list.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

N/A

</details>

**Comment by AshleyScirra** [comment]
Oops! Well spotted, should be fixed in r31.
