### ISSUE TITLE
Deduplicate Images bug r149

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#2960]
## Problem description

If export using Deduplicate images and a Tiledbackground has the same image than a sprite object, then the entire exported image is glitched in the game.

## Attach a .c3p

https://drive.google.com/open?id=1pfwzBoHhOPxBzRPIcHl_BUrHguZI-cVf

## Steps to reproduce

1. Export normal HTML5 with Deduplicate Images and Resize Images options turned on
2. Upload and test the game

## Observed result

In the title screen all images are going to be glitched.

## Expected result

To see the title screen (kiwi story)

## More details
This happens only if the Deduplicate option is used AND a tiledbackground object has the same image as a sprite object.-

**Affected browsers/platforms:** 

**First affected release:** first started happening in r149 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
