### ISSUE TITLE
r150 image editor reduces anti aliasing at each copy/paste or move

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2961]
## Problem description

I hope this explains better:

![19-05-22-23 48 49](https://user-images.githubusercontent.com/2965842/58207851-2d8f4180-7cec-11e9-99a8-714b5f906d91.gif)

Please don't break things that already work :'(

## Steps to reproduce

1. Select an image in the image editor
2. Move it
3. Cancel the selection by left click

## More details

Desktop Version

r150

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by bilgekaan** [comment]
Any news?

**Comment by DiegoScirra** [comment]
@bilgekaan

Just got back from holidays and looking at this now. The good news is that it is only a visual bug with the selection tool.  If you make a selection, then move it and confirm the move by clicking out side the selection, it looks like it is pasting the content twice in the new position.

What is happening is that the overlay layer that the editor uses to move a selection around is not getting cleared after finishing with the move, so it looks like it added more color that it should in the new position. This is noticeable if you have translucent colors in your selection, if you have 100% opaque colors it is not noticeable.

**Comment by DiegoScirra** [comment]
Fixed in the next beta release.
