### ISSUE TITLE
R150 - Timeline crashes when adding instance

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#2963]
See title.

## Problem description

When adding an instance in the Timeline bar using the "+" button, Construct crashes.

## Steps to reproduce

1. Open a new project in r150
2. Add a sprite.
3. Add a Timeline.
4. Via the Plus-Button in the Timeline bar, click to add instance.

## Observed result

Construct crashes.

## Expected result

No crash.

**Affected browsers/platforms:** Chrome

**First affected release:** r150

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r150/main.js, line 2, col 268695
Message: Uncaught Error: dialog name 'PickTimelineInstances' not found
Stack: Error: dialog name 'PickTimelineInstances' not found at Function.ǃubb (https://editor.construct.net/r150/main.js:2:268701) at Function.ǃGQ (https://editor.construct.net/r150/main.js:2:276450) at t.ǃGLq (https://editor.construct.net/r150/components/bars/timelineBar/timelineBar.js:1:10771) at https://editor.construct.net/r150/components/bars/timelineBar/timelineBar.js:1:11265
Construct 3 version: r150
URL: https://editor.construct.net/r150/
Date: Thu May 23 2019 15:08:05 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 32.9 s

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_0
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r150 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This was fixed in r151.
