### ISSUE TITLE
macOS - Color picker is hidden behind window (installed C3)

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#2964]
## Problem description

Everytime i try to use the color picker in Construct's Layout view (i.e. to change the background color) the picker opens behind the Construct window or in an open chrome browser (only happens if Construct was installed via Chrome)

## Steps to reproduce

1. Start Construct on macOS
2. Via Chrome, choose "Install Construct 3"
3. Exit Construct Tab in Browser (but leave Chrome open)
4. Open Construct on Desktop
5. Create new Project
6. Choose a background color from the Layout window by clicking on the color square.

![image](https://user-images.githubusercontent.com/30116964/58255583-98cd2800-7d6d-11e9-99c6-9ce840455edd.png)

## Observed result

At first it appears like no color selector appears. But often times it opens up in the Chrome browser itself instead of Construct, which was installed to the desktop.

## Expected result

Color picker opening up in main Construct Window.

**Affected browsers/platforms:** Chrome/C3 installed from Chrome

**First affected release:**noticed it in r148

## System details

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_0
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r150 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 132 gb
Storage usage (approx): 487 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's a Chrome bug, previously reported as #2784 and filed as [crbug.com/948065](https://bugs.chromium.org/p/chromium/issues/detail?id=948065) - it's being followed up there.
