### ISSUE TITLE
Multiplayer reconnect peer causing endless destroy objects

### ISSUE THREAD

**Issue by redfoc** [Scirra/Construct-3-bugs#2966]
## Problem description

I don't know it's my mistake or a bug.

If player/peer get killed by another player, then Host will kick this peer.

Player/peer can reconnect to this room and restart it's layout to retry the game again.

But if player are connected again, all synced object are destroyed every tick/time, but object that are destroyed is not the main objects, i really confused to explain this, it's take a while to find what causing my game bugs.

## Attach a .c3p

[multiplayer bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3217675/multiplayer.bug.zip)

## Steps to reproduce

1.Open c3p file, it's just Realtime-multiplayer template with another synced object.
2.Play it as peer
3.After player connected
4.Press 'Q' to disconnect
5.Then press 'R' to restart layout
6.After reconnected again, open console.log , you will see a continously log here.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by redfoc** [comment]
I think this bug is happened if using C3 runtime. but i can't change to C2 runtime since i use C3 features.

**Comment by AshleyScirra** [comment]
OK, this was tough to figure out, but I think I finally got to the bottom of it. Should be fixed in the next release.
