### ISSUE TITLE
Multiplayer on FB Instant Games not work (r150 Beta)

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#2967]
## Problem description

The Multiplayer-Plugin for construct 3 runtime can't connect to server on facebook instant games (Android: Samsung Galaxy S7). I get always the simple error-message: **error** (yea, thats all)

## Attach a .c3p

[Download Example-File](https://massive-cube.com/work/problem/construct/multiplayer-plugin-problem.c3p)

## Steps to reproduce

1. Open the example file
2. Export the project as facebook instant games project
3. Add and run this project on Android-App: facebook instant games. Now, you see, the game can't connect to the signalling server. (On pc: instant games works! Only on android not)

## Observed result

Multiplayer-plugin **can't** connect to signalling server

## Expected result

Multiplayer-Plugin **can** connect to signalling-server

## More details

I have tested with STUN-Server too, but don't work again...

**Affected browsers/platforms:** 

Android : Facebook Instant Games App

**First affected release:** 

r150 Beta

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r150 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 20 gb
Storage usage (approx): 480 mb (2.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can't attach a debugger to a Facebook Instant Game, which I suspect is because Facebook have deliberately disabled it, so only they can investigate this. Further I suspect they also deliberately block all connections to outside origins (thus blocking access to the signalling server) for security reasons, and only they can change that. You'll have to take this up with Facebook.

**Comment by masscube** [comment]
This is strange, it worked earlier. On Windows, Instant Games works. 
I'm check this and write again. :)

**Comment by masscube** [comment]
Hmm.. sorry.. now, i have tested it again (r151 Beta). I get "new" error on log/console on facebook instant games (android):

> Signalling server error: {"isTrusted":true}

@AshleyScirra I do not know is that a new information for you, but that sounds strange !?

**Comment by AshleyScirra** [comment]
I don't know, sorry. But I just realised it might be the same issue as another issue filed about WebSockets not connecting in release APKs. That appears to be a WebView bug that we filed with Google.

**Comment by masscube** [comment]
Ok, i don't know why, but the multiplayer works now on facebook instant games.
