### ISSUE TITLE
Plugin Advanced Random: "minify-script" bug (r150 Beta)

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#2968]
## Problem description

When the game export as NW.js or Instant Game (or anything other export-option), the game don't work with minify.

I get always this error in the console:

> Uncaught (in promise) ReferenceError: g_apX is not defined
>     at g_aQ.g_FZ.g_apw.g_HC.g_apW (c3runtime.js:2)
>     at g_aQ.g_FZ.g_apw.g_HC.g_apS (c3runtime.js:2)
>     at async g_aQ.g_FZ.g_apw.g_HC.g_YP (c3runtime.js:2)

## Attach a .c3p

[Download Example-File](https://drive.google.com/open?id=1n5Pmfk24z_TvhJ0XnUJZZbPJaT9CYBfU)

## Steps to reproduce

1. Open the example file
2. Export the project with NW.js (or anything other export option)
3. Check "Minify Script" on
4. Test/Run the exported game/app and get the error-message.

## Observed result

Game don't run. (Advanced Random don't work with Minify-Script)

## Expected result

Advanced Random works with Minify-Script

## More details

**Affected browsers/platforms:**

**Tested on:**
Node-Webkit and Facebook Instant Games

**First affected release:**

r150 Beta

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r150 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 24 gb
Storage usage (approx): 480 mb (2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by shortercode** [comment]
I've fixed a couple of references to methods on the WASM module that shouldn't have been minified, looks like the term "WebAssembly" is being mangled incorrectly though which prevents module instantiation.  Assigning to @AshleyScirra to ensure the term is on the global var list for the next build.

**Comment by AshleyScirra** [comment]
Updated our list of properties to not minify to match APIs in Chrome 74, which should help avoid such problems in future. Looks like this is all sorted now so closing.
