### ISSUE TITLE
[Request] Show Last location saved

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#297]
## Problem description

At times during the game jam I learn to use the local browser to do quick saves and use dropbox once every few hours. Countless times I forgot where this project was previously saved to. Then I realised, how do I know if this project is currently open from/previously saved on local browser or cloud services? In my case, the same file name is on both locations.

It would be great to have an indicator somewhere to show what this project was previously saved on or where it was fetched to open.

In C2 you have less of this problem because they are all local files and it also benefits from the recent menu displaying individual project's stored paths. In C3 the dropdown menu for recent projects doesn't highlight much information and it is impossible to tell where this project was previously saved unless you try to save again.

**Comment by shortercode** [comment]
Related fix as part of [#45](https://github.com/Scirra/Construct-3-bugs/issues/45), the recent projects menu now displays the icon for it's respective service next to each project. I guess something similar could be done on/near the save button to resolve this bug?

**Comment by jaydonteh** [comment]
Or could have a different icon for the project's root folder in the project bar.

**Comment by shortercode** [comment]
So I've been working on [#455](https://github.com/Scirra/Construct-3-bugs/issues/455) which prevents users from reopening the same project twice from the same service. I've chosen to allow opening the same project from different services, as they could arguably be completely different projects. In addition saving the same project under two names on the same service is considered different as well. 

This change highlights the need for this enhancement though I think, as these edge case could become extra confusing without the labels!

**Comment by shortercode** [comment]
Just finishing up on #624 and there's a fairly obvious place to add @jaydonteh suggestion in at the same time, are you happy with me stealing this bug @AshleyScirra ?

**Comment by shortercode** [comment]
@jaydonteh changes are in r45 which has just gone out, see what you think!

**Comment by jaydonteh** [comment]
@shortercode Looks great! But I found that when you collapse the project folder, the icon resets back to a folder until you save again.

**Comment by shortercode** [comment]
Ah... yeah I might have forgot it changed the icon then. Thanks for letting me know! I'll fix that

**Comment by shortercode** [comment]
Okay should be sorted for r46 (sometime this afternoon)
