### ISSUE TITLE
Iphone 8+ copy/look up popup while playing

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-3-bugs#2971]
## Problem description

A user reported that when they are playing my game, a copy/look up prompt appears on screen and it looks as if the whole canvas is selected. As this is hardware specific, I haven't been able to reproduce it on my system. However, I have provided a gif of the error that the user recorded for me. Likewise, if someone has an Iphone8+, they might be able to reproduce the issue by downloading my game through Testflight. 

testflight.apple.com/join/eCnnLN4l

https://i.imgur.com/HAvBGlp.gif

## Steps to reproduce

As best I can tell, this occurs when the user is walking left or right and jumps at the same time. 

## Observed result

a non-Construct related prompt highjacks the screen, obscuring the view.

## Expected result

This shouldn't happen at all

## More details
User informs me that the copy/look up prompt is similar to when he highlights text. I believe it is related to two fingers, however, I can't recreate this without an iphone 8+ (other users on different iPhones have reported no such issue)

Construct build is r148 stable

**First affected release:** 

## System details

So far has only occured on iPhone 8+

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
@shortercode maybe there's another event we need to block?

@Ldwebster111 - as with all bug reports it will be much quicker to fix if you can provide a minimal project and steps to reproduce the problem. Otherwise this could well roll on for months.

**Comment by Ldwebster111** [comment]
@AshleyScirra I was reluctant to even post this as a bug as I didn't have a project to submit with it, or any idea what's actually causing this so that I could narrow down the cause. The only thing I could suggest is providing you access to my entire game project. Obviously I wouldn't be uploading it through github, but if you feel it's needed, I can set up a shared drive somewhere and provide access that way. Of course, the problem there is that it's in no shape or form a minimal project so may not be helpful.

**Comment by AshleyScirra** [comment]
Do you even know what version of iOS the affected device is running? We're even missing basic details like that which mean we can only guess as to what's going on. We may have many more questions, and getting anywhere with answers to those questions is slow and difficult if nobody involved here can reproduce the problem.

**Comment by shortercode** [comment]
I can do some testing, see if I can replicate it on a few of our devices. We don't have much of a mix of iOS versions/devices though. It could be useful to have a project that approximates your UI. I expect our testing results will be similar to yours though @Ldwebster111

**Comment by Ldwebster111** [comment]
okay, I got the os info:

software version: 12.2 (16E227)
model name: iPhone 8 Plus

**Comment by AshleyScirra** [comment]
Does it still reproduce in r151?

**Comment by Ldwebster111** [comment]
I'm running an export now on r151. I can't upload to Testflight until tomorrow as I don't have a Mac at home, and it takes about another 24 hours for the release to go live, so I won't have an answer to that for at least 36 hours.

**Comment by Ldwebster111** [comment]
Getting the same issue on r151. Also, one of my students also had this happen on their device:

iPhone 7+
os: 12.3.1

They said they would record it and get some footage of it happening.

**Comment by AshleyScirra** [comment]
Unfortunately videos are not generally helpful - we can see what is happening but we need to know why, which involves identifying reliable steps to reproduce the problem.

**Comment by Ldwebster111** [comment]
Okay. I was on class all day today, so didn't get a chance to try it out myself, and only got to speak to him for 10 minutes in the morning. However, on Monday, I will have a bit of time to see if we can consistently make this appear and report back.

One thing I did notice was that it felt a bit unpredictable about when the popup was coming up. He seemed to think that it happened more often when he was doing a quick double tap on the screen, but then he started spamming taps and it didn't happen at all. One thing I will ask him to try is disabling 3D touch on his iPhone and see if it stills happens.

Also, I've tried several times to make a cut down version of this as an example project, and I've given up each time as trying to cut parts out of my project makes it unusable pretty quickly. I can either make one from scratch, or provide the full project, but unless a dev member thinks it's absolutely vital for testing, I'm probably going to hold off on that as I'm already under the pump with a lot of things.

**Comment by shortercode** [comment]
I had a look through our devices and our closest match is an iPhone 7 Plus with 12.2, hopefully that's closes enough. I will try with a minimal project and see if I can figure out how to replicate it and get back to you.

**Comment by Ldwebster111** [comment]
@shortercode I know Ashley said videos weren't much help, but one of my students worked out how to get this to appear everytime and I recorded it (with permission). As you can see, it happens when the user touches around the edge of the screen. Not sure if it matters, but I'm using letterbox scale.

https://youtu.be/ET4UYy9FiJI

Also worth noting that this has now been recreated on iPhone 6, 7 and 8.

**Comment by AshleyScirra** [comment]
@Ldwebster111 - can you reproduce this with r153? There was a fix in that release that might have affected this.

**Comment by Ldwebster111** [comment]
No worries. I won't have an answwr till Friday though.

**Comment by shortercode** [comment]
I think @AshleyScirra has beaten me to the punch while I was finishing off my current bits of work. @Ldwebster111 let me know how you get on, if it's still an issue I will look at it tomorrow afternoon.

**Comment by Ldwebster111** [comment]
Unfortunately, the student who's phone I've been using to test this was away today (it's flu season here), so now I won't be able to test till Monday. Cheers.

**Comment by shortercode** [comment]
Okay I found a much easier replication. Just need a project with a 1:1 aspect ratio, remote preview to an iPhone and perform a long press outside of the viewport area. Copy dialog pops up almost immediately in r152, doesn't appear at all in r153. So I think we can consider this fixed.

**Comment by AshleyScirra** [comment]
OK, that lines up with my theory about blocking default events in the letterbox margins, so closing. Hopefully @Ldwebster111 can later also confirm it's working.

**Comment by Ldwebster111** [comment]
Just spoke with the student who was able to consistently recreate this bug and they have confirmed that they can no longer do this, so seems to be fixed.

Well done 👍

**Comment by shortercode** [comment]
Glad to hear! Best of luck with the game @Ldwebster111

**Comment by AshleyScirra** [comment]
Thanks for confirming!
