### ISSUE TITLE
Sprite issue

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#2973]
Hello everyone
I am making games in construct 3 but currently i am facing some abnormal issues
whenever i use my sprites,randomly(sometimes happen,sometimes not),sprites are accompanied by light,bluish lines at the boundary.I also have attached the images
![Capture](https://user-images.githubusercontent.com/46170077/58426979-dad2d280-80bb-11e9-956c-f63ddb3c573d.PNG)
If you want the source file then please post your email id as i would like my project to be private.But please do not shut this issue like the last one

**Comment by shortercode** [comment]
@layilpaht I didn't see your previous issue but you have completely ignored the issue template, our reporting guidelines are quite clear that if you do not fill the template in then we will close your issue. 

Please refer to the following sections of the [guidlines](https://github.com/Scirra/Construct-3-bugs/blob/master/README.md)

> # Read these guidelines or your bug may be closed!
> Many users file bugs which are useless because they don't contain enough information for us to do anything about them. We just close these bugs without investigating them. Please follow these guidelines to avoid having your bug closed and help make sure we can fix the bug you're reporting.
>
> [...]
> # Use the bug report template
> The bug submission page is pre-filled with a template. **We need all this information to help you**. Do not delete it. Please provide as much of the requested information as you can, including the system details or crash report information with every report.

**Comment by layilpaht** [comment]
Now i have also tested same sprites in another game engine and they are running perfectly.Surely a construct 3 issue
Also ,did you provided me the email id where i will share the source file ???

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines regarding providing a minimal project. People routinely report their own mistakes as Construct bugs so we require this process to prove the problem really is with Construct and is not something you've done wrong.
