### ISSUE TITLE
[r29.2] Go to bookmarked event crash

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#298]
## Problem description

Anything that is bookmarked will crash when trying to navigate them using the bookmark bar.

## Steps to reproduce

1. Create a global variable or empty group or a simple trigger event.
2. Toggle bookmark.
3.Use book mark bar to navigate to it.

## Observed result
Crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected object @ TypeError: expected object at Function.ǃC.ǃcj (https://editor.construct.net/r29-2/main.js:2:200287) at Function.ǃC.ǃOo (https://editor.construct.net/r29-2/main.js:2:200356) at window.ǃYj.ǃIa (https://editor.construct.net/r29-2/components/editors/eventSheetView/eventSheetView.js:1:10067) at window.ǃYj.ǃmg (https://editor.construct.net/r29-2/components/editors/eventSheetView/eventSheetView.js:1:9628) at k.ǃmv.then (https://editor.construct.net/r29-2/components/bars/bookmarksBar/bookmarksBar.js:1:1683) at 
Stack: TypeError: expected object at Function.ǃC.ǃcj (https://editor.construct.net/r29-2/main.js:2:200287) at Function.ǃC.ǃOo (https://editor.construct.net/r29-2/main.js:2:200356) at window.ǃYj.ǃIa (https://editor.construct.net/r29-2/components/editors/eventSheetView/eventSheetView.js:1:10067) at window.ǃYj.ǃmg (https://editor.construct.net/r29-2/components/editors/eventSheetView/eventSheetView.js:1:9628) at k.ǃmv.then (https://editor.construct.net/r29-2/components/bars/bookmarksBar/bookmarksBar.js:1:1683) at 
Construct 3 version: r29.2
URL: https://editor.construct.net/index.html
Date: Sun May 21 2017 15:53:21 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 19.9 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r31.
