### ISSUE TITLE
Crash when opening on mobile

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#2980]
## Problem description
Editor crashes on last update when opening on mobile

## Attach a .c3p
N/a

## Steps to reproduce

1.Open editor on mobile

## Observed result

A crash

## Expected result

The editor starts

## More details

**Affected browsers/platforms:** 
Chrome Android

**First affected release:** r151

## System details

The crash happens but the crash window contains no info to copy and it hides the loading page which has an error on it. All I managed to read was the word Function

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
It looks like some of the editor loading optimisations broke the mobile version. Appears to be a straightforward fix so should be working in the next release. I expect a number of people will notice this so will leave the issue open until the next release.
