### ISSUE TITLE
Error: already loaded texture

### ISSUE THREAD

**Issue by jcardenaslie** [Scirra/Construct-3-bugs#2982]
## Problem description

C3 crashing when loading a layout
## Attach a .c3p

Cannot share the build, It's a clients game

## Steps to reproduce

It can't be reproduce at will, but it happens when changing to a specific layout in the game, the layout that contains all the game logic

## Observed result
Browser debug:
c3runtime.js:2 Uncaught (in promise) Error: already loaded texture
    at g_bA.g_Zb.g_Bm (c3runtime.js:2)
    at c3runtime.js:2
    at Array.map (<anonymous>)
    at g_bA.g_Zs.g_ZA (c3runtime.js:2)
    at c3runtime.js:2
    at Array.map (<anonymous>)
    at g_bA.g_Gg.g_awG.g__K.g_FL (c3runtime.js:2)
    at g_bA.g_ZY.g_FL (c3runtime.js:2)
    at g_bA.g_Fb.g_FM (c3runtime.js:2)
    at g_bA.g_Gg.g_Gf.g_aiL (c3runtime.js:2)

## Expected result

No error, and the layout loading correctly
## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines otherwise I'm afraid we cannot investigate your report. Note the section on "Do I need to share my entire project?" which explains what to do in your situation.
