### ISSUE TITLE
Color palette Save Color BUG

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#2987]
## Expected result

if  Select a color from the Color palette That OK.
https://giphy.com/gifs/W1lVxMm1qFzVNllbrE

## Problem description

1.When Copy a Hex code that. it can't work.
https://giphy.com/gifs/Rk2D9VfdNzB5YienYt

2.When Copy a Hex code that. and switch as primary secondary again. That OK.
https://giphy.com/gifs/Jso1LZgy4w1Uvojy39

And When input the Hex Code, The Alpha value can auto set 255 ?
https://giphy.com/gifs/THgYAnc3Hxxym3dy7G

**Comment by DiegoScirra** [comment]
@XHXIAIEIN 

The first issue has been fixed.

Additionaly when pasting a hex code, the alpha value will be set to 255, but only if it was previously 0. In all other cases the old alpha value will be kept.
