### ISSUE TITLE
Editor colours issue

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2988]
## Problem description

So, I kind of already reported it, but Ashley asked me to open a new issue with and "old vs new" thing.

Left is new (wrong) and right is old (correct).

Layout icons: https://i.imgur.com/s1xOrtK.png

Families icons: https://i.imgur.com/O9YzG0W.png

Effects icons: https://i.imgur.com/MAWu6x6.png

As you can see everything have less constrast now, which is bad for visualization.

## Attach a .c3p

Not needed.

## Steps to reproduce

1. Check layout icons.
2. Check families icons.
3. Check effects icons.

## Observed result

Dark colours for the icons.

## Expected result

Bright colours for the icons.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next release.

**Comment by BonzerKitten7** [comment]
Great! Thanks.
