### ISSUE TITLE
[r29.2] UI blur issues

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#299]
## Problem description

I started noticing some UI being blurry. Firstly, I suspect because I'm using Window's custom scaling so it might not be Construct's issue. Some of the UI I noticed that was affected are all the UI bars and the eventsheet expression's popup guide.

---
Just to clarify, the expression's pop guide look like this:
![blur bug image](http://i.imgur.com/PrJH1Ro.png)
The popup that shows the parameters of the function anglelerp() is blur.

---
Also a blur Tilemap UI:

![blur bug image](http://i.imgur.com/71n5X5N.png)

## Steps to reproduce

1. Close an opened UI such as Properties bar or the Layer bar.
2. Re-open them from the View menu. They should appear undock.

Of course you could also directly open any currently closed UI.

## Observed result

The UI is blurred compared to the UI that were docked. Interestingly when you try to move the blur UI, it does not look blur any more but does not "un-blur" when you focus/use it, only when moving it.

## Expected result

Refresh the UI scaling so it looks sharp each time the UI is tampered or opened.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

Local storage
Storage quota (approx): 7.2 gb
Storage usage (approx): 414 mb (5.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can't see any issues on my desktop which is scaled to 110% (Device pixel ratio: 1.100000023841858). The UI code is specifically written to do pixel-snapping depending on the device pixel ratio. Not sure what's going wrong on your system. Does it go away or change if you alter the browser zoom?

**Comment by jaydonteh** [comment]
Turns out it was really caused by Window's 10 custom scaling. Once I used Window's recommended scaling which is 125% for my screen, I have no issue. Previously was scaling at around 117% which have caused the visual glitches.

**Comment by AshleyScirra** [comment]
Hmm, assuming it's rare to chose a custom scaling, I don't think many people will run in to this, and I'm not sure there's much we can do about it anyway.
