### ISSUE TITLE
AddOn SDK Requests (reimport and z-order)

### ISSUE THREAD

**Issue by lucidspriter** [Scirra/Construct-3-bugs#2990]
- iProject.GetObjectType(objectName) returning an IObjectType by that name if it already exists. This will make it possible to reimport and update the same files to the same objects when something is dropped in, as opposed to creating a new instance.

- A way to set z-index of objects.  Specifically something that will allow the insertion of multiple objects at a time between two other objects without having to shift around indexes in an array, or manually loop through every object on top of the inserted objects and update them manually.  For instance, it might be useful to be able to set the z-index to a float (like setting 20 objects between the z-indexes of 2 other objects : eg between index 1 and 2, setting multiple sprites to 1.1, 1.2, 1.3, etc), and then make a call that z-indexes had changed and have the objects update that way.

As a side note, I've attempted to use various combinations of splicing the instances array, _SetZIndex(z), _SortInstancesByLastCachedZIndex(), SetZIndicesChanged(), and manually setting _zIndex and I wasn't able to get anything stable and consistent going.

**Comment by shortercode** [comment]
Assigned to @AshleyScirra to review

**Comment by AshleyScirra** [comment]
Please post this to https://construct3.ideas.aha.io/ in the SDK category if you haven't already, thanks. (We don't track feature requests on GitHub)

**Comment by lucidspriter** [comment]
k.  I posted it there now.  I was still posting them here as this is where you asked me to put addon sdk requests last year when I was making multiple requests on the forums.
