### ISSUE TITLE
Dragging function call above comment results in crash

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#2991]
Crash when I drag a function call above a comment in action.

## Attach a .c3p

[crashy.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3235061/crashy.c3p.zip)

## Steps to reproduce

1. Drag the function call above the comment
2. Observe crash

## Observed result

Crash

## Expected result

No crash

## More details

I just noticed, this also happens when I try to directly create the function call above the comment block.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r151/main.js, line 2, col 94595
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Function.ǃb (https://editor.construct.net/r151/main.js:2:94601) at Function.ǃel (https://editor.construct.net/r151/main.js:2:94670) at s.ǃNl (https://editor.construct.net/r151/projectResources.js:1:293311) at s.ǃwIR (https://editor.construct.net/r151/projectResources.js:1:273875) at https://editor.construct.net/r151/projectResources.js:1:273750 at a.ǃRT (https://editor.construct.net/r151/components/editors/eventSheetView/eventSheetView.js:1:30106) at a.ǃRk (https://editor.construct.net/r151/components/editors/eventSheetView/eventSheetView.js:1:27516) at a.ǃSV (https://editor.construct.net/r151/components/editors/eventSheetView/eventSheetView.js:1:23365) at HTMLDocument. (https://editor.construct.net/r151/components/editors/eventSheetView/eventSheetView.js:1:2269) at HTMLDocument. (https://editor.construct.net/r151/main.js:2:188071)
Construct 3 version: r151
URL: https://editor.construct.net/r151/
Date: Thu May 30 2019 03:19:46 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 89.7 s

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r151 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
