### ISSUE TITLE
Replacing an object in a call function (built-in) action is not displayed in the editor

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#2993]
## Problem description

(in this issue, all mentions of functions are related to the NEW built-in function)
I created a function where I did the following:
1) pick an object "Sprite" from a family, based on a family instance variable
2) Call another function with a parameter of the function set to the picked object family instance variable.

![testFunction_replace](https://user-images.githubusercontent.com/29117306/58628956-65454d00-82db-11e9-9e4c-1f34ae4bbe85.JPG)

Then I selected the whole function and replaced the object with another object from the same family.
The object referred to, to set the new called function parameter was NOT updated in the editor (still Sprite instead of Sprite2). However, opening the action by double clicking it correctly displays the replaced object Sprite2.

## Attach a .c3p

[functionParam_Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3236710/functionParam_Bug.zip)

## Steps to reproduce

1. Open the attached C3P or reproduce it based on the image above
2. Select the whole function (or only the action) and replace Sprite by sprite 2

## Observed result

The name of the object is not replaced in the editor. However, opening the action displays it correctly.

## Expected result

The display in the editor should be the same than when the action is opened

## More details

**Affected browsers/platforms:** 

Desktop Build r151
Chrome r151

**First affected release:** 

r151

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r151 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 2.9 gb (18.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.

**Comment by RabloGames** [comment]
You're very welcome, thanks for the fix.
