### ISSUE TITLE
Issue with copy & paste content from c2 runtime to c3 runtime

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2995]
When If i do copy-paste objects from c2 runtime to c3 runtime and in the c2 runtime If there is an object which contains some third party plugins for example in c2 runtime i add LiteTween behavior to a Sprite and then paste this object in c3 runtime where LiteTween behavior is not installed then C3 successfully do paste that object in C3 runtime and it doesn't alert me that the object has plugin which is not installed. and i we select that object in c3 runtime then property also shows LiteTween behavior's properties. 
If we have lots of object to copy - paste then it became very challenging to find out the issue. Because we don't know we have pasted object having behaviors which are not installed.
So in Short there should be alert for this.

## Attach a .c3p
[Issue in Construct 3.zip](https://github.com/Scirra/Construct-3-bugs/files/3236942/Issue.in.Construct.3.zip)

## Steps to reproduce

1. Install LiteTween Behavior ( Attached in Zip folder)
2. Open Construct 3 Editors for 2 times (make one C2 runtime and another C3 runtime)
3. In C2 runtime Editor Insert any sprite and add LiteTween behavior
4. now paste this sprite to c3 runtime. that's it

## Observed result
Editor didn't notified me that object i pasted is containing a behavior which is not available in C3 runtime.

## Expected result
it should give alert about this

## More details

**Affected browsers/platforms:** 
I tried in Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, this is a bit of a tricky case but should be fixed in the next release.
