### ISSUE TITLE
Copy-pasting functions from another C3 results in a hidden duplicate function

### ISSUE THREAD

**Issue by Souls3** [Scirra/Construct-3-bugs#2996]
## Problem description

Copying a function from another C3 project shows a "Cannot paste" message if it contains objects not in the destination project.
When I fix the issue and try again, C3 duplicates the function, with one duplicate being hidden.

## Attach a .c3p

[CopyPaste.zip](https://github.com/Scirra/Construct-3-bugs/files/3237089/CopyPaste.zip)

## Steps to reproduce

1. Copy "TestFunction" to another project that has an Array object called "Test"
2. A message will appear because "Array" is missing.
3. Rename "Array" in the attached project to be "Test".
4. Copy the function again and paste it in the other projects.

## Observed result

The pasted result will be "TestFunction2". Trying to rename it to "TestFunction" will tell you that "TestFunction" already exists, even though it is no where to be found in the project!

## Expected result

Paste the function as it was copied, and with the same name (e.g. "TestFunction"), without hidden duplicates.

## More details

**Affected browsers/platforms:** Firefox 67.0 (64-bit). Windows 10

**First affected release:** r148

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, this is a tricky edge case. It should be fixed in the next build.
