### ISSUE TITLE
Sudden Crash

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#2997]
## Problem description
Error report information
Type: unhandled exception
File: https://editor.construct.net/r148/main.js, line 178, col 555951
Message: Uncaught InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Stack: Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0. at Function.ǃUUU (https://editor.construct.net/r148/main.js:178:555951) at t.ǃgav.ǃUUg (https://editor.construct.net/r148/main.js:178:345654) at t.ǃgav.ǃes (https://editor.construct.net/r148/main.js:178:342716) at Array.ǃOZ (https://editor.construct.net/r148/main.js:178:334882) at ǃk.Event.ǃQFc.ǃQFJ (https://editor.construct.net/r148/main.js:2:192620) at ǃk.ǃB.ǃD.ǃgxK.dispatchEvent (https://editor.construct.net/r148/main.js:2:190661) at e.ǃDi.ǃUBA (https://editor.construct.net/r148/main.js:178:434360) at e.ǃDi.ǃgoK (https://editor.construct.net/r148/main.js:178:433824) at HTMLDocument.ǃgou (https://editor.construct.net/r148/main.js:178:304551) at HTMLDocument. (https://editor.construct.net/r148/main.js:2:187394)
Construct 3 version: r148
URL: https://editor.construct.net/
Date: Thu May 30 2019 20:12:11 GMT+0530 (India Standard Time)
Uptime: 4167.9 s

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r148 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

(Also i have 6 gb RAM .No idea why it is showing 4 gb)

Figure it out what it means 
## Attach a .c3p
It is neither in my pc nor in google drive.What to do ?
## Steps to reproduce
I was editing a sprite in sprite editor window.Suddenly this message popped up.It was written that post the message so i posted it.(I was editing a 3 mb picture)
## Observed result

Already told,I lost my project
## Expected result
Relaxed Life 
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
@layilpaht - it's unlikely we will be able to do anything about this without steps to reproduce the problem. Please see the bug report guidelines.

**Comment by layilpaht** [comment]
I thought that the bug report will be of some value to you
Close this thread

**Comment by ibiz3091** [comment]
Сonstruct 3 does not open projects
@AshleyScirra 
Error report information
Type: unhandled rejection
Reason: {"response":"{\n \"error\": {\n \"errors\": [\n {\n \"domain\": \"global\",\n \"reason\": \"internalError\",\n \"message\": \"Internal Error\"\n }\n ],\n \"code\": 500,\n \"message\": \"Internal Error\"\n }\n}\n","code":500,"status":
Construct 3 version: r151
URL: https://editor.construct.net/r151/
Date: Mon Jun 03 2019 00:43:37 GMT+0300 (Москва, стандартное время)
Uptime: 41.7 s

Platform information
Browser: Chrome
Browser version: 77.0.3812.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3812.0 Safari/537.36
C3 release: r151 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
@ibiz309 - that error is unrelated to this one and will need to be filed separately following all the guidelines for any investigation to happen.

**Comment by DiegoScirra** [comment]
@layilpaht

I pushed a change that should avoid this crash in the future, but it is difficult to tell without reproduction steps.
