### ISSUE TITLE
[r16] Spam Preview Crashed

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#3]
## Problem description
While preview double-clicking does not crash it, spamming it does the trick.

## Steps to reproduce

1. Create New Project.
2. Spam Preview button.

## Observed result
Crashed.

## Expected result
No crash but preview says fail to load perhaps.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r16/exporters/preview/exporter.js, line 1, col 20491
Message: Uncaught TypeError: Cannot read property 'ǃKU' of null
Stack: TypeError: Cannot read property 'ǃKU' of null at window.ǃVG.ǃVI (https://editor.construct.net/r16/exporters/preview/exporter.js:1:20491) at window.ǃTr.ǃVw.ǃTn (https://editor.construct.net/r16/exporters/preview/exporter.js:1:19716) at window.ǃTr.ǃTe (https://editor.construct.net/r16/exporters/preview/exporter.js:1:1173) at ǃTF.p (https://editor.construct.net/r16/exporters/preview/exporter.js:1:641)
Construct 3 version: r16
URL: https://editor.construct.net/index.html
Date: Fri Apr 07 2017 00:48:54 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 16 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I can't reproduce this here with a new project or Space Blaster. Based on the crash report though I added in some extra checks for r17. Let me know if it's better when that's out.

**Comment by AshleyScirra** [comment]
r17 is out, can you check if this is still an issue?

**Comment by jaydonteh** [comment]
Continuous clicking in quick successions of the preview button still crashes construct. This time, a different error log report.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r17/exporters/preview/exporter.js, line 1, col 2948
Message: Uncaught TypeError: Cannot set property 'from' of null
Stack: TypeError: Cannot set property 'from' of null at window.ǃmm.ǃmP (https://editor.construct.net/r17/exporters/preview/exporter.js:1:2948) at window.ǃmm.ǃYb (https://editor.construct.net/r17/exporters/preview/exporter.js:1:1143) at ǃmB.p (https://editor.construct.net/r17/exporters/preview/exporter.js:1:641)
Construct 3 version: r17
URL: https://editor.construct.net/index.html
Date: Wed Apr 12 2017 01:16:51 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 109.3 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
OK, based on that report I added an extra check for r18. Please check again when it's out.

**Comment by AshleyScirra** [comment]
r18 is out now, can you verify if it's fixed?

**Comment by jaydonteh** [comment]
Working flawlessly, fixed!

**Comment by AshleyScirra** [comment]
Great, thanks for verifying!
