### ISSUE TITLE
Imported C2 project effect color params sometimes wrong

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#30]
## Problem description

Sometimes when importing a Construct 2 project, effect color parameters change to 0,0,0 or 1,1,1 instead of their original colors.

This has been spotted in a few cases during development but it seems there is something inconsistent about conversion to/from [0,1] float format and [0-255] integer format.

Original report: https://www.scirra.com/forum/effects-not-working_t189646

**Comment by shortercode** [comment]
So in testing this I found that C2 is storing the colour values in the range 0 - 2.55 ( tested in r244 and r250 ), and that we are expecting 0 - 255. So we end up being out by a factor of 100.

There's a note next to the conversion that this format has changed over the years @AshleyScirra any word on this? Trying to match compatibility is likely to be hard based on only a number. The best I can come up with would have 2 invalid values: 1 / 255 and 2 / 255 which would be interpreted as 100 / 255 and 200 / 255.

**Comment by AshleyScirra** [comment]
@shortercode - no, C2 uses different ranges in different places, that fix will simply swap to the other half of cases working and breaking the existing half. To properly solve this issue we need to figure out which places C2 uses which ranges.

**Comment by shortercode** [comment]
Okay well I committed a change as per my suggestion above, which should work in the majority of cases for both scales.

**Comment by AshleyScirra** [comment]
I think you should revert it, as the comment says I've done it both ways already and there's no point changing it again until we fix it properly.

**Comment by AshleyScirra** [comment]
Also the change looks wrong, IIRC C2 never used a 0 - 2.55 format, only 0-1 or 0-255. TBH I think this will need reviewing the C2 source code so best leave this one to me.

**Comment by AshleyScirra** [comment]
There's something very confusing about this. I can't find anything that uses the 0-255 range, but IIRC there were some cases I found in the past, and code history shows me updating to support them. Here's a C2 project that uses tint as a layout, layer and object effect (i.e. all three cases): [tintfx.zip](https://github.com/Scirra/Construct-3-bugs/files/1632213/tintfx.zip)
Every tint effect is set to 50% red. This definitely imports wrong to C3, setting the red parameter to 1, because it incorrectly divides by 255. So, for what looks like the third time, I'm reverting to interpreting C2 effect parameters in the [0-1] range instead of [0-255], which fixes this test case. In the absence of other test cases this looks like it's all sorted, but I guess there is some other edge case to cover. I'll close this and if any new cases are filed we can repro them, attach the test cases here, and make sure we cover everything.
