### ISSUE TITLE
[Request] Start page settings

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#300]
## Problem description

I love the start page of C3, especially the full width sized start page for C3. Here's the thing, I usually don't touch that start page any more after opening a project. So I would like it to be closed. But when I close the project, I would like the start page to be open by default rather than showing the "What next?" blank screen with limited options. The only thing I like about the "What next?" page is Miss Piggy's fearless cousin.

Would be nice to have a setting to toggle close the start page whenever there is a project currently opened. So that whenever I use Construct and start working on a project, the start page is closed. Something like C2 having a setting where it closes after whatever I clicked.

Replacing the "What next?" page with the start page would reduce steps taken to perform what-next things.

**Comment by AshleyScirra** [comment]
Added the settings for r46.
