### ISSUE TITLE
Wait for previous actions + AJAX sometimes mixes up AJAX.lastdata

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3000]
### Happy 3000th bugreport 🎂 

When using the new wait for previous actions to complete it sometimes mixes up the ajax.lastdata.

## Attach a .c3p

[waitforpreviouserror.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3239146/waitforpreviouserror.c3p.zip)

## Steps to reproduce

1. Start preview
2. Check console for errors

## Observed result

The data from one call sometimes ends up somewhere else, causing the error logs. (due to comparisons with ajax.lastdata failing)

## Expected result

The data to reliably end up where expected.

## More details

I tried a couple of different ways to arrange the events but all of them had the same problem.

FYI the php files that are called do nothing else but echo either "foobar", "hello" or "world"

![true](https://user-images.githubusercontent.com/31101309/58672925-6614c800-8349-11e9-9fd5-4a89f56b700b.PNG)
Doing it like this remedies the issue because the ajax requests are not send out at the same time, but in my project the requests are send out on two entirely different places in the event sheet (but still at basically the same time) This means when using wait for previous actions you´d need to make sure that it absolutely never waits for two different things simultaniously.

**Affected browsers/platforms:** 
Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r151 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 813 mb (5.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Wackytoaster** [comment]
I just noticed I deleted the php files by accident, they are up again now.

**Comment by AshleyScirra** [comment]
This is a weird example, your server has the wrong CORS configuration so all requests fail. In the failure case I would not expect LastData to contain anything useful at all. So I don't think it's a valid test case.

Anyway the way you have structured your events means all requests are dispatched in parallel, which is essentially equivalent to this:

+ On function call
-> Request testA.php
-> Request testB.php
-> Request testC.php
-> Wait for previous actions to complete
-> Log AJAX.LastData

In this case there's no provision for 'Wait for previous actions to complete' to handle parallel requests, because it hasn't been designed for that. So the best thing to do is just go back to using the tags and separate On complete/On error triggers.
