### ISSUE TITLE
Weird issue with one object R151

### ISSUE THREAD

**Issue by Lexsernn** [Scirra/Construct-3-bugs#3001]
There is something very weird about the application I'm trying to make. 

When you release the app for internal test on google play and open the application, it shows a black screen.
If you open the APK and not installing it from google play it shows the application without any issues.

I had a big application and pretty much removed everything in it to find out what caused the issue.
Right now I got it to work if I remove one of the image objects. Whenever that image is in the project there is an issue with google play. 
I thought it was just that object that was weird, so I removed it from my big application and it still does not work there, so I guess most of the image objects in the application is acting this way too.

I have got this to work before with the object image, I must have done something to most of the images to cause this issue.

I'll include a stripped down C3P file here so you guys can take a look.

https://drive.google.com/open?id=1ZoZva3XcFUMGhP0aj7_g89BxttlKEYte

The object in question is hacker_login_logo.png
I also thought it might be the name but its still an issue even if you rename it.
Also another weird thing, if you delete everything else than the object, then it starts working.. 

Anyone got any idea what the issue is with that object, so I can apply a fix to all of my objects and see if I can get my application working again?

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines and ensure you fill out the full bug report template. The provided project uses a third-party addon "Simple Virtual Keyboard". This may be the cause of the problem, in which case you need to take up the issue with the addon developer. To ensure this is not the problem please ensure any issues you file do not use third-party addons.
