### ISSUE TITLE
Crash trying to use Cloud Save (to my Google Drive at home)

### ISSUE THREAD

**Issue by TurkMcGill** [Scirra/Construct-3-bugs#3004]
## Problem description

I have been working on a demo for work. I have saved my work locally, but mostly I was saving to my company's work drive (cloud). This worked all day until a few minutes ago. I kept getting errors that the file couldn't be saved, so I saved a local copy (which seems to be okay).

I need access to my project at work tomorrow, so I tried to save it to my person google drive. This seemed to work, but after nearly a minute it was reporting that 0% of my file had been saved. I clicked on this text message, hoping to get more information, but the instant I did my screen went kind of red and I got an unrecoverable error message. I copied what it told me to copy and that is pasted below.

## Attach a .c3p

I'm pretty sure the .c3p didn't cause this issue. It's sensitive information from my company so I hope it's okay that I didn't include this file...

## Steps to reproduce

1. I was saving my project a variety of ways all day. (Including Cloud Saves to my Google Drive at work)
2. I tried to save to my Google Drive at work but I kept getting a "Can't Save" error.
3. I tried to do a Cloud Save, chose my home Google account, but the little gray dialog in the lower left corner said "Saving to Google Drive 0%". After several minutes it was still at 0%.
4. I wondered if clicking on the gray dialog box, but the second I did the screen turned red and I got a fatal error with the attached error report.

## Observed result

My program crashed and was unrecoverable.

## Expected result
I expected to be able to save my file.

(I don't understand this question.)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: {"response":"{\n \"error\": {\n \"errors\": [\n {\n \"domain\": \"global\",\n \"reason\": \"internalError\",\n \"message\": \"Internal Error\"\n }\n ],\n \"code\": 500,\n \"message\": \"Internal Error\"\n }\n}\n","code":500,"status":
Construct 3 version: r151
URL: https://editor.construct.net/r151/
Date: Sun Jun 02 2019 20:56:27 GMT+0200 (Central European Summer Time)
Uptime: 18062.3 s

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r151 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Google services had an outage yesterday I believe, I haven't looked into it properly but there were some people talking about it on twitter. The error you are seeing is from their servers. Although I admit it shouldn't be crashing, I'm not sure why it did. Could you provide a replication please? "Use cloud save" is very vague, there are many ways to save files which often have their own way to display error messages.

**Comment by shortercode** [comment]
I've spent a fair amount of time trying to find any gaps where this error could be thrown, but haven't found anything. Without a solid replication I don't think this is going anywhere unfortunately.

I did resolve a probably unrelated issue I discovered while looking for this though, so not entirely a waste of time. If you find a way for me to reproduce this error please file a new issue with the replication steps.
