### ISSUE TITLE
Can't even open Construct 3

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#3006]
## Problem description

I try to run Construct 3 and it just crashes immediately.

## Attach a .c3p

I can't open it to even produce a CAPX.

## Steps to reproduce

1. I have no clue. I just try to open C3.

## Observed result

It crashes instantly.

## Expected result

It should open.

## More details
**Affected browsers/platforms:** Desktop build

**First affected release:** r151

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃpIN' of null @ TypeError: Cannot read property 'ǃpIN' of null at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:320867) at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:322022) at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:322022) at Function.ǃpRc (https://editor.construct.net/r151/main.js:2:319983) at Object.ǃKzk (https://editor.construct.net/r151/main.js:159:47933) at Object.ǃKzk (https://editor.construct.net/r151/main.js:159:48085) at Object.ǃwBY (https://editor.construct.net/r151/main.js:159:45308) at async s (https://editor.construct.net/r151/main.js:159:91122) at async https://editor.construct.net/r151/main.js:159:93147
Stack: TypeError: Cannot read property 'ǃpIN' of null at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:320867) at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:322022) at Function.ǃpRz (https://editor.construct.net/r151/main.js:2:322022) at Function.ǃpRc (https://editor.construct.net/r151/main.js:2:319983) at Object.ǃKzk (https://editor.construct.net/r151/main.js:159:47933) at Object.ǃKzk (https://editor.construct.net/r151/main.js:159:48085) at Object.ǃwBY (https://editor.construct.net/r151/main.js:159:45308) at async s (https://editor.construct.net/r151/main.js:159:91122) at async https://editor.construct.net/r151/main.js:159:93147
Construct 3 version: r151
URL: https://editor.construct.net/r151/
Date: Mon Jun 03 2019 00:48:21 GMT-0600 (Mountain Daylight Time)
Uptime: 1.6 s

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r151 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Seems to be some sort of issue with the layout system, I will investigate.

**Comment by AshleyScirra** [comment]
Same crash report as #2992 so closing as duplicate.
