### ISSUE TITLE
Game freeze after while in play

### ISSUE THREAD

**Issue by qrq** [Scirra/Construct-3-bugs#3008]
## Problem description

Game freeze after while in play

I try to downgrade ver but no way
also try to change runtime to c2 but Popup message talk about you cant change with long error in some element in the game scene 

It freeze without any error msg when the game create many of elements in level. 

This problem happen in all desktop and mobile browser ( android & iphone ) also in apk ver 
Please help :(

C3 r151

## Attach a .c3p
https://drive.google.com/file/d/1Ef1wVvUAYd2Jm9xZ3BK2aftDttdsbuDW/view?usp=drivesdk

link to apk :

http://www.nooh.me/ice/1.apk

I send this msg form mobile, so cant attach

## More details

I try to back to release r148 but idon’t know how?

**Affected browsers/platforms:** 

**First affected release:** 

## System details
C3 r151

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid we're unable to investigate reports like this. Please see the bug report guidelines - they are there to make sure we can help.

**Comment by qrq** [comment]
Thanks for help :)
