### ISSUE TITLE
Screen is draggable up/down in iOS Safari

### ISSUE THREAD

**Issue by RichardAstrom** [Scirra/Construct-3-bugs#3009]
Starting from r151, when exporting a HTML5 project, the window is not fixed and you can drag it up/down. This happens on my iPhone 7 with Safari iOS 12.3.1. Versions 148-150 works fine with the exact same project so this seem to have been introduced in version 151. I have tested on one Android device as well and was not able to reproduce the issue.

[instant scroll bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3247617/instant.scroll.bug.zip)

## Steps to reproduce

1. Export the project.
2. Upload as an Instant Game.
3. Drag the window up/down.

## Observed result

You can drag the window up/down.

## Expected result

It should be static/fixed.

## More details

![instant_scroll](https://user-images.githubusercontent.com/3534495/58803814-a2c61500-8610-11e9-903e-c5e450549bb7.gif)

**Affected browsers/platforms:** 

Safari for iOS

**First affected release:** 

r151

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r151 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 703 mb (4.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Does this happen in Safari or iOS apps? Instant Games are particularly hard to debug (it appears Facebook have disabled developer tools for them).

**Comment by RichardAstrom** [comment]
@AshleyScirra 

Ok! It's the same in Safari for iOS when I export as a regular HTML5 project.
I've just uploaded a test here:

[https://sad-lamarr-0afd74.netlify.com/](https://sad-lamarr-0afd74.netlify.com/)

**Comment by AshleyScirra** [comment]
Thanks, should be fixed for the next release.
