### ISSUE TITLE
Crashes when you close Find Results tab. r152

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3011]
## Problem description

Crashes when you close Find Results tab. r152

Error report information
Type: unhandled exception
File: https://editor.construct.net/r152/components/bars/findResultsBar/findResultsBar.js, line 1, col 1223
Message: Uncaught TypeError: Cannot read property 'clear' of null
Stack: TypeError: Cannot read property 'clear' of null at Object.ǃV (https://editor.construct.net/r152/components/bars/findResultsBar/findResultsBar.js:1:1223) at Array. (https://editor.construct.net/r152/main.js:159:36624) at Object.ǃcWD (https://editor.construct.net/r152/main.js:2:193402) at Object.dispatchEvent (https://editor.construct.net/r152/main.js:2:191270) at Object.ǃaF (https://editor.construct.net/r152/main.js:2:324100) at Object.ǃaF (https://editor.construct.net/r152/main.js:2:329330) at Object.ǃaF (https://editor.construct.net/r152/main.js:2:340038) at Object.ǃcri (https://editor.construct.net/r152/main.js:2:336421) at Object.ǃci_ (https://editor.construct.net/r152/main.js:2:347597) at Object.ǃcIK (https://editor.construct.net/r152/main.js:2:347627)
Construct 3 version: r152
URL: https://editor.construct.net/r152/
Date: Mon Jun 03 2019 21:18:22 GMT+0300 (GMT+03:00)
Uptime: 70.8 s

## Steps to reproduce

1. Open a project
2. Close find results tab

## More details

**Affected browsers/platforms:** Desktop

**First affected release:** r152

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r152/components/bars/findResultsBar/findResultsBar.js, line 1, col 1223
Message: Uncaught TypeError: Cannot read property 'clear' of null
Stack: TypeError: Cannot read property 'clear' of null at Object.ǃV (https://editor.construct.net/r152/components/bars/findResultsBar/findResultsBar.js:1:1223) at Array. (https://editor.construct.net/r152/main.js:159:36624) at Object.ǃcWD (https://editor.construct.net/r152/main.js:2:193402) at Object.dispatchEvent (https://editor.construct.net/r152/main.js:2:191270) at Object.ǃaF (https://editor.construct.net/r152/main.js:2:324100) at Object.ǃaF (https://editor.construct.net/r152/main.js:2:329330) at Object.ǃaF (https://editor.construct.net/r152/main.js:2:340038) at Object.ǃcri (https://editor.construct.net/r152/main.js:2:336421) at Object.ǃci_ (https://editor.construct.net/r152/main.js:2:347597) at Object.ǃcIK (https://editor.construct.net/r152/main.js:2:347627)
Construct 3 version: r152
URL: https://editor.construct.net/r152/
Date: Mon Jun 03 2019 21:18:22 GMT+0300 (GMT+03:00)
Uptime: 70.8 s

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r152 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
