### ISSUE TITLE
Build failed r52

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#3012]
## Problem description

When i build with construct 3 c2runtime for android open window (build failed) with message:
Error: Discovered platform "android@^8.0.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@^8.0.0
Adding android project...
Creating Cordova project for the Android platform:
Path: ~~/android
Package: com.ERAgames.Legendaryfishing
Name: Legendary_Fishing_HD
Activity: MainActivity
Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.0.0
Plugin 'construct-mobile-advert' found in config.xml... Migrating it to package.json
Plugin 'construct-mobile-purchase' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-inappbrowser' found in config.xml... Migrating it to package.json
Plugin 'construct-play-games' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-x-socialsharing' found in config.xml... Migrating it to package.json
Plugin 'cordova-launch-review' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-dialogs' found in config.xml... Migrating it to package.json
Plugin 'com-artemisoftnian-plugins-unityads2' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-vibration' found in config.xml... Migrating it to package.json
Discovered saved plugin "construct-mobile-advert". Adding it to the project
Installing "construct-mobile-advert" for android
Subproject Path: CordovaLib
Subproject Path: app
Discovered saved plugin "construct-mobile-purchase". Adding it to the project
Installing "construct-mobile-purchase" for android
Discovered saved plugin "cordova-plugin-inappbrowser". Adding it to the project
Installing "cordova-plugin-inappbrowser" for android
Discovered saved plugin "construct-play-games". Adding it to the project
Installing "construct-play-games" for android
Subproject Path: CordovaLib
Subproject Path: app
Discovered saved plugin "cordova-plugin-x-socialsharing". Adding it to the project
Installing "cordova-plugin-x-socialsharing" for android
Installing "es6-promise-plugin" for android
Subproject Path: CordovaLib
Subproject Path: app
Discovered saved plugin "cordova-launch-review". Adding it to the project
Installing "cordova-launch-review" for android
Discovered saved plugin "cordova-plugin-dialogs". Adding it to the project
Installing "cordova-plugin-dialogs" for android
Discovered saved plugin "com-artemisoftnian-plugins-unityads2". Adding it to the project
Installing "com-artemisoftnian-plugins-unityads2" for android
Subproject Path: CordovaLib
Subproject Path: app
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for android

This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Discovered saved plugin "cordova-plugin-vibration". Adding it to the project
Installing "cordova-plugin-vibration" for android

**Comment by ERAgames777** [comment]
I understood the problem, this error appears due to the UnityAds plugin.

**Comment by shortercode** [comment]
I've been seeing some errors reported on the server from the UnityAds plugin, it appears that it does not compile. Are you using it with a construct addon? If so you should contact the developer.

**Comment by ERAgames777** [comment]
@shortercode yes i use unityads construct addon. hmm, the developer did not respond to questions 7 months :((( Perhaps he stopped his support.

**Comment by shortercode** [comment]
I expect the developer produced it in their spare time, so they might just be on a break or doing other things. Fairly common for open source for the maintainer just to vanish unfortunately... Hard to tell what the situation is if they aren't responding.

Will have to be quite low priority but I'll put a note on my TODO list to investigate why it isn't compiling.
