### ISSUE TITLE
In the script editor, copying pastes

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3013]
## Problem description
in the script editor when i try to copy a line of code it does either a paste or a cUT instead

## Attach a .c3p
https://puu.sh/DBmCl/37a255416e.c3p

## Steps to reproduce

1.open construct 3
**2. copy something on like chrome or whatever
3.Select some code in a script in a project
4. right click the selection
![image](https://user-images.githubusercontent.com/32940085/58851269-0e839e80-8660-11e9-9e6a-f68dc9eb8231.png)

5.click copy 
![image](https://user-images.githubusercontent.com/32940085/58851301-29561300-8660-11e9-993f-145ed05f403e.png)
![image](https://user-images.githubusercontent.com/32940085/58851375-7e922480-8660-11e9-9853-8b192a8b67ae.png)

** alternatively skip step 2  and it will CUT instead of pasting but like only if it's a fresh tab i think ???
## Observed result
it pastes instead of copying

## Expected result
to copy my selection

## More details

**Affected browsers/platforms:** 

151 and 152
**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r151 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 762 mb (4.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Thanks for the report, turned out to be a simple typo. Should be resolved in the next release.
