### ISSUE TITLE
Blank screen on mobile preview

### ISSUE THREAD

**Issue by mammothinc** [Scirra/Construct-3-bugs#3014]
When I preview this game on mobile preview it shows a blank. It might be because of large tilemaps that I am using. If so, then there should be some error that lets me know what the problem is. 

https://www.dropbox.com/s/8d445cem1zbkr1d/Farm%20Game%20p07%20Kevin.c3p?dl=0

## Steps to reproduce

Mobile preview on an iPhone. 

## Observed result

Blank screen

## Expected result

A playable game.

**Comment by kingpirux** [comment]
i had reports from users of this issue too but couldnt reproduce :( i dont know if it is related with the Mali GPU again, but it's the only clue i have

**Comment by AshleyScirra** [comment]
Press 'Export' and you get this warning which explains why it's not working:

> This project has images larger than 4096 pixels (e.g. *TiledBackground3* has a 5762 x 616 image). This exceeds the maximum texture size on some devices, so the project will fail to load on those devices. Are you sure you want to continue?

It's a hardware limit so there's nothing much that can be done about it. I've added that warning to also appear on remote preview for the next release, but that's all - you need to avoid using such huge images.
