### ISSUE TITLE
R148 Stable: Microsoft Edge: Syntax Error in "supportCheck.js" 

### ISSUE THREAD

**Issue by DrathVader** [Scirra/Construct-3-bugs#3015]
## Problem description

C3: R148 Stable

- Microsoft Edge wont load any Construct 3 exports.

- Created a "blank" new project in Construct 3, exported and errors in EDGE. Works in other browsers.

SCRIPT5022: SyntaxError
supportCheck.js (1,25)

**Comment by AshleyScirra** [comment]
I think we already fixed this. Please only test the latest beta release to avoid reporting bugs that we've already fixed.
