### ISSUE TITLE
LocalStorage plugin doesn't save on android APK

### ISSUE THREAD

**Issue by huwpascoe** [Scirra/Construct-3-bugs#3016]
## Problem description

LocalStorage plugin doesn't work on android APK

## Attach a .c3p

https://editor.construct.net/#open=localstorage-hiscore

## Steps to reproduce

1. Set the company and description, then export Cordova debug APK
2. Run the demo, set a high score.
3. Close the app fully swiping it from from the activities list
4. Launch the app again

## Observed result

"First run, no high score"

## Expected result

"Existing high score:"

## More details
When saving it triggers a LocalStorage.OnError but LocalStorage.ErrorMessage remains empty.

**Affected browsers/platforms:** Android 7.1.2

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.80
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
C3 release: r148 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 308 mb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I tried to replicate this on a Samsung S8 and experienced no problems, do you have a different device to test on? I'm curious if it's related to the device and or Android version.

**Comment by huwpascoe** [comment]
I'm afraid the only other device I have is an AVD emulated one, and I'm unable to test there due to a webGL problem.

**Comment by huwpascoe** [comment]
I have tried getting log info out of the apk,, but as mentioned elsewhere I just get this response from cordova: https://stackoverflow.com/questions/51519636/google-chrome-developer-tools-android-debugging-returns-http-1-1-404-not-found

**Comment by shortercode** [comment]
Yes the WebGL issue is a known problem, in the emulator Chrome WebView doesn't support WebGL. There isn't anything we can do about it unfortunately. The Chrome team might fix it at some point but I'm not aware of any changes there. You can switch to normal WebView for the virtual device but the WebGL implementation is super buggy.

I haven't come across that remote debug issue, so not really sure what to suggest. What versions of chrome/webview is the device on VS your PC?

**Comment by shortercode** [comment]
There isn't any action I can take here, so I'm going to close this. I expect this is related to the device but without working debugging tools on the device it's hard to resolve the reason. If you manage to get any additional information from the device file an issue and I will take another look.
