### ISSUE TITLE
Regression with spawning sprites in r151+

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3018]
## Problem description
Using some random test to spawn sprites with while loop and test how many you can spawn before you start to drop frames. Then r151 has clearly somekinds regression etc, while in r150 its seems same as previous builds. Not sure what it is, but it has somekind regression.

## Attach a .c3p
[SpawnTest (1).zip](https://github.com/Scirra/Construct-3-bugs/files/3259169/SpawnTest.1.zip)

## Steps to reproduce

1.Open example in r150, preview, maximise screen, spawn sprites still you see freguent Jank message on-screen. Note count
2.Open example in r151, preview, maximise screen, spawn same many sprites. See jank message pops up constantly. 
3.

## Observed result
Its could be hard to tell (test it not the best), but r151 has sprite spawn count regression around ~10-15%. 
In test with r150, i can have spawn per frames 150, occasional jank messages appear. Same  test in 151 janks much much more. Even on low fps ~30, r150 can hold much better results then 151. So regression seems be around ~10% etc. 
I tried other tests like: quad issue example etc, but could not see any difference.

## Expected result
What is cause of this, does new script feature has impact on events?

## More details

**Affected browsers/platforms:** 

**First affected release:** 
r151
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r150 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.7 gb (12.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can reproduce, but the difference comes from initialising the script interfaces for the scripting feature. I couldn't immediately find any way to speed it up. It's not realistic to expect benchmarks to never change over time as the engine changes - especially since the engine is already so fast, even a tiny change or single extra line of code added for another feature can result in measurable differences. We can investigate if the difference is significant and impacts real-world games, but if it's only a minor difference in a synthetic benchmark then I don't believe it's worth spending our already stretched resources on it.
