### ISSUE TITLE
[r29.2] Duplicate with right-click twice crash - A right-click select design flaw

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#302]
## Problem description

In the Sprite animation editor, when trying to duplicate an animation using right-click rather than left-click (provided that you access the menu using right-click) will cause it to open a second right-click menu on that object. And if you click duplicate again, it will crash.

The solution here would have to be applied to the entire C3's UI design. You should not be able to select any menu options in a right-click menu by right-clicking. Just as you couldn't use the middle-button to select options in C3. It is already weird enough that you could navigate the menus with the middle-button but cannot select things with it. There is no design consistency in this operation. Perhaps due to the fact that the multi-platform menus are navigated with "Touch" controls but triggered by "Mouse" controls?

## Steps to reproduce

1. Create a Sprite object.
2. Right-click the default "Animation 1".
3. Right-click on the "Duplicate" option but make sure your cursor is still in the boundaries of the "Animation 1" box.
4. You should see the menu again. This time just left-click or right-click the duplicate option.

## Observed result

Crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r29-2/main.js, line 71, col 288653
Message: Uncaught TypeError: Cannot read property 'ǃsr' of null
Stack: TypeError: Cannot read property 'ǃsr' of null at ee.ǃJer.ǃJVh (https://editor.construct.net/r29-2/main.js:71:288653) at le.ǃmw (https://editor.construct.net/r29-2/main.js:71:291149)
Construct 3 version: r29.2
URL: https://editor.construct.net/index.html
Date: Sun May 21 2017 21:00:55 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 14.9 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by jaydonteh** [comment]
Prevent the underlying problem of the crash reported here by issuing a redesign in that you cannot select/navigate menus with the middle-button nor by right-clicking.

**Comment by DiegoScirra** [comment]
Just found out this only happens when UI animations are turned off.

**Comment by DiegoScirra** [comment]
Fixed in r31.

**Comment by AshleyScirra** [comment]
Reopening: the menu system is designed to work like Windows, which allows both left and right clicks to select menu items, but not middle clicks. @DiegoScirra - your r31 fix just bans right clicks which breaks consistency with Windows. Right clicks should be allowed on menus, but only to pick the item, it shouldn't do anything else like spawn another menu.

**Comment by DiegoScirra** [comment]
Fixed.

Right clicks on menu items now work in the same way as left clicks.
