### ISSUE TITLE
App Crashing and Reloading upon "Game Start" on iPhone and iPad

### ISSUE THREAD

**Issue by asdzxc8** [Scirra/Construct-3-bugs#3023]
## Problem description

I've been breaking down my file for the past week but I can't seem to find the root of the issue.

Remote preview on an iPhone or iPad;
Upon clicking "Start Game" button on the Main Menu layout of the app, app crashed and reload from loader layout again. "This web page was reloaded because a problem occurred" appears on top of the browser when the app crashed."

Exported and tested on Testflight;
Same thing as above but without the error written.
What I also realized is after the crash and reload, Game Center is totally inaccessible. IAP which is on another layout doesn't work and unable to open the High Score on Game Center. This can be fixed by killing the app completely and opening it up again.

I've 2 project files (latest version running C3 runtime and one that have been exported on C3/released 9 months back) and both of them have this issue. By theory, the file from 9 months back which is running C2 runtime shouldn't have this issue since I've already done it once successfully. I'm just doing exactly the same thing now with almost no deviations.

## Attach a .c3p

I'm willing to provide the project files (both if needed) through email to the person assigned instead of putting the file up online if that's alright.

## Steps to reproduce

1. Remote preview the provided project file on an Apple device (iPhone 7 and iPad Mini 2 in my case)
or
2. Exported as a Xcode project, built and uploaded to Testflight. Code can be given upon request if necessary.
or
3. Opening the project file directly on Apple device's default browser (Safari), previewing straight from there.

## Observed result

On the very first load of the app, Start Game > Cutscene > Skip Tutorial > Main Game (app crashed and reload back to loader layout).
Subsequently, just need to click on Start Game > Main Game (app crashed and reload).
On very rare occasion, the app doesn't crash immediately upon pressing the button but right as the game starts, the app crashed and reload within the first minute.

After the crash and reload, Game Center features are totally inaccessible. IAP which is on the "Shop" layout doesn't work and unable to open the High Score on Game Center (Main Menu > More > Achievements). This can be fixed by killing the app completely and opening it up again.

[Extra Informations - Unconfirmed]
Let me know if I need to create a different tracker on this but I think it might be related, hence the mention.
I don't have an Android device so I had one of my friend tested it out to see if the scenario is the same.

The first load; he didn't skip tutorial and the app froze/hang at the end of the Cutscene layout, which is about to go into the Main Game layout.
The 2nd load (after killing the app completely each time) onwards seem to be fine according to him, except lots of lag and unresponsiveness at the start of the Main Game layout (which is normal due to the big layout I guess).
But he wasn't able to access the Game Service (Main Menu > Achievement and IAP) throughout unlike the older version of the app from 9 months back. Proper permission have been set accordingly on Google Play Console (both tester and Game Service).
In the iOS version, you can still access the various Game Center features upon opening the app/as long as you doesn't go straight into the Main Game to crash the app.

## Expected result

App should not crashed and reload right from the start again. Game should start normally as usual. Game center features/IAP should work accordingly too.

## More details

**Affected browsers/platforms:** 
[Confirmed] Affected on iPhone and iPad's Safari browser/ or as an exported app from Testlight.
Doesn't affect Chrome on Win 10 (PC) and Safari on macOS.

**First affected release:** 
Tested/Exported on r148 (stable release) first.
Later tried r111 (stable - which I used 9 months back), r150 (beta), r151 (beta) and r152 (beta).
EDIT: Tested on r142.3, r120, r104 and r98 (stable) as well.

## System details

<details><summary>View details</summary>

![1](https://i.imgur.com/Knl71td.png)
This is actually from the project file 9 months back.

I tried debugging with Web Inspector (during Remote Preview) and got the following the first time; (tbh not sure if those are the right lines to grab since I'm not sure what I should be looking out for)
![2](https://s1.construct.net/images/v680/r/uploads/articleuploadobject/0/images/27961/screenshot-2019-05-31-12-51_v800.png)
![3](https://s1.construct.net/images/v680/uploads/articleuploadobject/0/images/27962/screenshot-2019-05-31-12-49.png)

[Unconfirmed] On another occasion, I got;
"Unable to use local storage because indexdb is not defined."
</details>

**Comment by AshleyScirra** [comment]
I'm afraid this type of problem indicates that iOS, Safari, or the driver crashed, instead of it being a problem with Construct. At best we could attempt to work around it, but this is extremely difficult, time-consuming, not guaranteed to work, and does not solve the underlying problem so it can later re-surface again. Given we're a tiny team dealing with thousands of reports, this is not generally feasible unless we have a minimal project as per the bug report guidelines, with reliable steps to reproduce. I think your best bet would be to report the issue to Apple directly.
