### ISSUE TITLE
Issue with 9-patch

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3024]
## there are two issues with 9-patch
1) if i paste round corner image then it makes image pixelate. while we can see smooth in image edit mode but in the layout corners are pixelated. When i check this in Construct 2  then there in C2 corners are smooth. So I am sure it is a bug with 9-patch.
2) if i do stretch this image in layout then corners are also stretching, i think corners should never be stretched. I don't know if this is a bug of plugin or it is normal.

## Attach a .c3p
[9-patch issue .zip](https://github.com/Scirra/Construct-3-bugs/files/3268552/9-patch.issue.zip)

## Steps to reproduce

1. open attached file
2. check the 9-patch image (in layout and in image editor)
3. see the difference in corners ( pixelated vs smooth corners)

a) stretch the image in the layout and see corners they are stretching too.

## Observed result

1) pixelated image.
2) stretching image corners.

## Expected result
1) image should be smooth.
2) image corners should not stretch.

## More details

**Affected browsers/platforms:** 
Chrome Browser

**First affected release:** 
r152
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by luckyrawatlucky** [comment]
Another issue found [Resizing with "smooth" make a black sprite](https://github.com/Scirra/Construct-3-bugs/issues/1590), Do i need to recreate this bug because that bug report was closed but now it happens again.

**Comment by AshleyScirra** [comment]
I can't see anything wrong with the project. Note that the rounded corner on the 9-patch image is about 50 pixels across, but you have the margin properties set to 16 pixels, which is too small and produces odd looking results. I assume this is just a mistake in your project.

**Comment by luckyrawatlucky** [comment]
Compare between Original image vs 9-patch image
![9patch compare](https://user-images.githubusercontent.com/17684135/59191250-9efc3a80-8b9c-11e9-9986-474d45168534.png)

**Comment by AshleyScirra** [comment]
I can't see that happening in the project you provided. The main problem appears to be the incorrect margin sizes.

**Comment by luckyrawatlucky** [comment]
i changed margin to zero but still same issue
try to switch Fill between stretch and Tile several times and keep an eye on edges
you can see how corners are changing
