### ISSUE TITLE
Very thin line appearing on image edge

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3025]
## Problem description
I am getting very thin line on the edge of the image and a very weird thing is happening here. There are few images in the project which are affecting this line .
1. When i delete any one of those images then the line disappears but when i do undo then it appears again.
2. When i delete any one of those images then the line disappears but when i recreate a new sprite with same size then thin line appears again.
3. If i resize any other image then thin line disappears but if i revert it to its original size then it comes again.

## Attach a .c3p
[very thin line issue .zip](https://github.com/Scirra/Construct-3-bugs/files/3268615/very.thin.line.issue.zip)

![Thin line issue](https://user-images.githubusercontent.com/17684135/59148325-14dd9600-8a25-11e9-89e1-d9462039fd20.png)
screenshot

## Steps to reproduce

1. Open attached file
2. Try above steps in description.

## Observed result
a thin line appears in edge of the image

## Expected result
no thin line

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
r152
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Since the image is downscaled a long way, in rare cases this can result in adjacent images on the spritesheet bleeding through. Set downscaling quality to "High" and it goes away.
