### ISSUE TITLE
Calling function from script can cause runtime crash

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3029]
## Problem description

Quite a specific case. I have a function that sets layers visible/invisible. I call this function from a script file, after doing something with async (firebase to be exact, but it works with any async function). Without the async there seems to be no problem.

![err](https://user-images.githubusercontent.com/31101309/59232221-da6e2780-8be3-11e9-8ed9-0f1d94173d15.PNG)

## Attach a .c3p

[asyncBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3274071/asyncBug.c3p.zip)

## Steps to reproduce

1. Start preview
2. Check console
3.

## Observed result

Game freezes

## Expected result

No crash

## More details
I used c3_callFunction, but same thing happens with runtime.callFunction()

**Affected browsers/platforms:** 

**First affected release:** 
Not sure but I first saw it in r152

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.80
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
C3 release: r153 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 906 mb (6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
**Note: don't use c3_callFunction in project scripts** - it does not work correctly in that context. It's also undocumented in the scripting reference so counts as an undocumented unsupported feature in this context. Use `runtime.callFunction()` instead. (This is not directly related to this issue though.)

This turns out to be an issue with calling a function when no other events are running (in this case on a timer callback). It should be fixed in the next release.

**Comment by Wackytoaster** [comment]
> Note: don't use c3_callFunction in project scripts

Aye aye, captain. Thx for the quick fix :)
