### ISSUE TITLE
There's no Black Background in preview animations

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#303]
## Problem description

When we test an animation with the preview option, there's no Black background, so if an animation is white, we cannot see anything.

## Steps to reproduce

1. create a sprite with white colors
2. Make a preview

## Observed result

White with white > Nothing to see

## Expected result

Change the background color

## Affected browsers

* Chrome: yes/

**Comment by AshleyScirra** [comment]
Maybe the preview should respect the light/dark background of the editor itself.

**Comment by Picoti** [comment]
Yes.

**Comment by DiegoScirra** [comment]
Fixed in r31.

The preview dialog now uses the same chequered background as the main editing area and it also respects the background color of the editor.
