### ISSUE TITLE
Animation editor brush tool opacity option not working

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3030]
## Problem description
When you use brush tool in animation editor and change opacity - nothing happens. If i use line tool and change opacity, line opacity changes depending opacity value. But opacity option does not change anything in brush tool!

## Steps to reproduce

1.Open new project, create sprite and open animation editor
2.Select Brush tool, put opacity to 1 and draw something.
3.Now change opacity to 0.5, draw something nothing changes.
4. Do same thing with line tool, see opacity changes color value.

## Observed result
Opacity value does not work with brush tool, but it works with line tool.

## Expected result
Opacity works with brush tool same as line tool.

## More details

**Affected browsers/platforms:** 

**First affected release:** 
I tried few releases down to R100, which had same issue.
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.800000011920929
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r153 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 20 gb
Storage usage (approx): 384 mb (1.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Mobility Radeon HD 5000 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Just to clarify, this only happens when the **smooth toogle is off** and **hardness is 1**. In that case the opacity is ignored. Should be easy to fix.

**Comment by DiegoScirra** [comment]
This is fixed now, will be available in the next beta.
