### ISSUE TITLE
R153: HTML EXPORT: Filenames are not correct case. Result in broken 404 paths to .js files in Index.html & offline.js

### ISSUE THREAD

**Issue by DrathVader** [Scirra/Construct-3-bugs#3032]
## Problem description

HTML exports. Paths to filenames are incorrect in "index.html" and "offline.js"

Filenames are mix-case and they are being called as all lowercase.

For example:

"scripts/supportcheck.js" (VS) "scripts/supportCheck.js"
"scripts/offlineclient.js" (VS) "scripts/offlineClient.js"

![filenames](https://user-images.githubusercontent.com/4141075/59266392-6a1fd000-8bfc-11e9-80d2-c28b66cfe837.PNG)

## Attach a .c3p

(Blank project, all defaults)
https://1drv.ms/u/s!AnjqkTqN7TavkqJtYK2X4d39H-0rEg?e=oNuUa3

## Steps to reproduce

Look in "index.html" and "offline.js" Notice the incorrect filenames. "Case sensitive"

## Observed result

Paths are 404, wrong URL to .js files.

## Expected result

Correct paths with the case sensitive filenames are needed. Differences between Unix/Windows servers.

## More details

All Browsers depending on the server you use.

## System details

404 to .js files.

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
It looks fine to me. All the filenames in the zip are lowercase. Then in index.html it has:

```html
	<script src="scripts/supportcheck.js"></script>
	<script src="scripts/offlineclient.js"></script>
	<script src="scripts/main.js"></script>
	<script src="scripts/register-sw.js"></script>
```

These are all lowercase. Then in offline.json the file list is `["scripts/c3runtime.js","data.json","style.css","scripts/offlineclient.js","scripts/main.js","scripts/dispatchworker.js","scripts/jobworker.js","scripts/workermain.js","scripts/supportcheck.js","icons/loading-logo.png","icons/icon-16.png","icons/icon-32.png","icons/icon-64.png","icons/icon-128.png","icons/icon-256.png","icons/icon-512.png","scripts/register-sw.js"]`. These too are all lowercase.

**Comment by DrathVader** [comment]
You are correct, it was the same folder. I should have caught that, my apologies. Thanks once again for your support and time and R153 is an excellent update.
