### ISSUE TITLE
Preview failing after beta update (Not a script error)

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#3034]
## Problem description

I was loading up a project in the new version https://editor.construct.net/r153/ and I get an error when trying to preview the new project, stating to restart construct 3, digging into the console log of the browser we get this error:

projectResources.js:15 Error starting preview:  Error: not a script
    at Object.ǃVRZ (projectResources.js:1)
    at projectResources.js:1
    at Array.map (<anonymous>)
    at n.ǃVha (projectResources.js:1)
    at o.ǃWGf (projectResources.js:23)
    at o.ǃWGU (projectResources.js:15)
    at o.ǃWGF (projectResources.js:15)
    at Object.ǃWGF (main.js:159)
    at Object.ǃfv (main.js:159)
    at Object.ǃyOS (mainMenu.js:1)

## Attach a .c3p

https://drive.google.com/open?id=1SS0k2cB-q4WhBiOcDmU4uQcwjwOgn9qM

## Steps to reproduce

1. Have a c3p file with some javascript (both inline script + js script files)
2. Update to R153
3. Open project and try to preview the project

## Observed result

We get error message check screen shot below
https://drive.google.com/open?id=1gj0Qlo_6leHlfpHqNSig78MtEHhgWJZv

## Expected result

The preview window displays the game and no errors appearr

## More details

**Affected browsers/platforms:**  CHROME (only use chrome)

**First affected release:**  R153

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r153 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 268 mb (1.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD FirePro W2100 Graphics Adapter Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Looks like Chrome uses a different MIME type for .js files in some cases, which breaks preview... easy to fix though, should be working in the next release.
