### ISSUE TITLE
Is there a search button I'm not seeing?

### ISSUE THREAD

**Issue by 3dParadox** [Scirra/Construct-3-bugs#304]
## Problem description
I can't find a search button. I tried Control F, not expecting it to work, and found it's undockable popup. 

## Attach a .c3p

editor only

## Steps to reproduce

1. Click the search button.
2.
3.

## Observed result

I can't find search. I used to add a search box to the mini-menu on the top of C2, so am spoiled by that.

## Expected result

Have a search button to open it's popup, or make it dock-able.
edit: Or maybe since the results are dockable, put a search button on that bar to open the popup.

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: /no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Picoti** [comment]
Right CLIC >Event sheet > Find

**Comment by Kyatric** [comment]
Also, Right-click any object of the project in the project bar/layout "Find all references"

**Comment by AshleyScirra** [comment]
The feature is implemented a little differently, the dialog you see when you press Ctrl+F is the replacement. You can dock the results window, the dialog is just for entering the search.
