### ISSUE TITLE
Game screen goes white

### ISSUE THREAD

**Issue by kidswithcrowns** [Scirra/Construct-3-bugs#3041]
## Problem description
The game suddenly freezes and goes white. The only thing I can still see is a text input box. The project is a really big game so I can't attach a c3p

I don't know if this helps but this is from the console:

layer.js:1 Uncaught (in promise) TypeError: Cannot read property 'GetWorldInfo' of undefined
    at C3.Layer._UpdateZIndices (layer.js:1)
    at C3.Layer.Draw (layer.js:1)
    at C3.Layout.Draw (layout.js:1)
    at C3.Runtime.Render (runtime.js:1)
    at C3.Runtime.Tick (runtime.js:1)

"use strict";{function a(c,a){return c.GetWorldInfo()._GetLastCachedZIndex()-a.GetWorldInfo()._GetLastCachedZIndex()}function b(c,a){return c.GetWorldInfo().GetZElevation()-a.GetWorldInfo().GetZElevation()}const c=new C3.Rect,d=new C3.Quad,e=[],f=new C3.Rect,g=new C3.Rect,h=vec3.fromValues(0,1,0);C3.Layer=class extends C3.DefendedBase{constructor(a,b,c){super(),this._layout=a,this._runtime=a.GetRuntime(),this._name=c[0],this._index=b,this._sid=c[2],this._isVisible=!!c[3],this._backgroundColor=C3.New(C3.Color),this._backgroundColor.setFromJSON(c[4].map((a)=>a/255)),this._isTransparent=!!c[5],this._parallaxX=c[6],this._parallaxY=c[7],this._color=C3.New(C3.Color,1,1,1,c[8]),this._premultipliedColor=C3.New(C3.Color),this._isForceOwnTexture=c[9],this._useRenderCells=c[10],this._scaleRate=c[11],this._blendMode=c[12],this._srcBlend=0,this._destBlend=0,this._curRenderTarget=null,this._scale=1,this._zElevation=c[16],this._angle=0,this._isAngleEnabled=!0,this._viewport=C3.New(C3.Rect),this._viewportZ0=C3.New(C3.Rect),this._startupInitialInstances=[],this._initialInstances=[],this._createdGlobalUids=[],this._instances=[],this._zIndicesUpToDate=!1,this._anyInstanceZElevated=!1,this._effectList=C3.New(C3.EffectList,this,c[15]),this._renderGrid=null,this._lastRenderList=[],this._isRenderListUpToDate=!1,this._lastRenderCells=C3.New(C3.Rect,0,0,-1,-1),this._curRenderCells=C3.New(C3.Rect,0,0,-1,-1),this._iLayer=new ILayer(this),this._UpdatePremultipliedColor(),this._useRenderCells&&(this._renderGrid=C3.New(C3.RenderGrid,this._runtime.GetOriginalViewportWidth(),this._runtime.GetOriginalViewportHeight()));for(const d of c[14]){const a=this._runtime.GetObjectClassByIndex(d[1]);this._layout._AddInitialObjectClass(a),a.GetDefaultInstanceData()||(a.SetDefaultInstanceData(d),a._SetDefaultLayerIndex(this._index)),this._initialInstances.push(d)}C3.shallowAssignArray(this._startupInitialInstances,this._initialInstances)}static Create(a,b,c){return C3.New(C3.Layer,a,b,c)}Release(){this._layout=null,this._runtime=null}CreateInitialInstances(a){const b=this._layout.IsFirstVisit();let c=0;const d=this._initialInstances;for(let e=0,f=d.length;e<f;++e){const f=d[e],g=this._runtime.GetObjectClassByIndex(f[1]);let h=!0;if(!g.HasPersistBehavior()||b){const b=this._runtime.CreateInstanceFromData(f,this,!0);a.push(b),g.IsGlobal()&&(h=!1,this._createdGlobalUids.push(b.GetUID()))}h&&(d[c]=d[e],++c)}C3.truncateArray(d,c),this._runtime.FlushPendingInstances(),this.SetZIndicesChanged()}_AddInstance(a,b){const c=a.GetWorldInfo();if(c.GetLayer()!==this)throw new Error("instance added to wrong layer");this._instances.push(a),0!==c.GetZElevation()&&(this._anyInstanceZElevated=!0),b&&this._useRenderCells&&a.GetWorldInfo().SetBboxChanged(),this.SetZIndicesChanged()}_MaybeAddInstance(a){this._instances.includes(a)||(this._instances.push(a),0!==a.GetWorldInfo().GetZElevation()&&(this._anyInstanceZElevated=!0),this.SetZIndicesChanged())}_PrependInstance(a,b){const c=a.GetWorldInfo();if(c.GetLayer()!==this)throw new Error("instance added to wrong layer");this._instances.unshift(a),0!==c.GetZElevation()&&(this._anyInstanceZElevated=!0),this.SetZIndicesChanged(),b&&this._useRenderCells&&a.GetWorldInfo().SetBboxChanged()}_RemoveInstance(a,b){const c=this._instances.indexOf(a);0>c||(b&&this._useRenderCells&&a.GetWorldInfo()._RemoveFromRenderCells(),this._instances.splice(c,1),this.SetZIndicesChanged(),this._MaybeResetAnyInstanceZElevatedFlag())}_SetAnyInstanceZElevated(){this._anyInstanceZElevated=!0}_MaybeResetAnyInstanceZElevatedFlag(){0===this._instances.length&&(this._anyInstanceZElevated=!1)}_SortInstancesByLastCachedZIndex(b){if(b){const a=new Set;for(const b of this._instances){const c=b.GetWorldInfo()._GetLastCachedZIndex();0<=c&&a.add(c)}let b=-1;for(const c of this._instances){const d=c.GetWorldInfo();if(!(0<=d._GetLastCachedZIndex())){for(++b;a.has(b);)++b;d._SetZIndex(b)}}}this._instances.sort(a)}_Start(){this.SetBlendMode(this.GetBlendMode(),!0)}_End(){for(const a of this._instances)a.GetObjectClass().IsGlobal()||this._runtime.DestroyInstance(a);this._runtime.FlushPendingInstances(),C3.clearArray(this._instances),this._anyInstanceZElevated=!1,this.SetZIndicesChanged()}RecreateInitialObjects(a,b){const c=this._runtime.GetEventSheetManager(),d=this._runtime.GetAllObjectClasses(),e=a.IsFamily();for(const f of this._initialInstances){const g=f[0],h=g[0],i=g[1];if(!b.containsPoint(h,i))continue;const j=d[f[1]];if(j!==a)if(!e)continue;else if(!a.FamilyHasMember(j))continue;const k=this._runtime.CreateInstanceFromData(f,this,!1);if(c.BlockFlushingInstances(!0),k._TriggerOnCreated(),k.IsInContainer())for(const a of k.siblings())a._TriggerOnCreated();c.BlockFlushingInstances(!1)}}GetInstanceCount(){return this._instances.length}GetLayout(){return this._layout}GetName(){return this._name}GetIndex(){return this._index}GetSID(){return this._sid}GetRuntime(){return this._runtime}GetEffectList(){return this._effectList}UsesRenderCells(){return this._useRenderCells}GetRenderGrid(){return this._renderGrid}SetRenderListStale(){this._isRenderListUpToDate=!1}IsVisible(){return this._isVisible}SetVisible(a){a=!!a;this._isVisible===a||(this._isVisible=a,this._runtime.UpdateRender())}GetViewport(){return this._viewport}GetViewportForZ(a,b){const c=this._viewportZ0;if(0===a)b.copy(c);else{const d=this.Get2DScaleFactorToZ(a),e=c.midX(),f=c.midY(),g=.5*c.width()/d,h=.5*c.height()/d;b.set(e-g,f-h,e+g,f+h)}}GetOpacity(){return this._color.getA()}SetOpacity(a){a=C3.clamp(a,0,1);this._color.getA()===a||(this._color.setA(a),this._UpdatePremultipliedColor(),this._runtime.UpdateRender())}_UpdatePremultipliedColor(){this._premultipliedColor.copy(this._color),this._premultipliedColor.premultiply()}GetPremultipliedColor(){return this._premultipliedColor}HasDefaultColor(){return this._color.equalsRgba(1,1,1,1)}GetScaleRate(){return this._scaleRate}SetScaleRate(a){this._scaleRate===a||(this._scaleRate=a,this._runtime.UpdateRender())}GetParallaxX(){return this._parallaxX}GetParallaxY(){return this._parallaxY}SetParallax(a,b){if((this._parallaxX!==a||this._parallaxY!==b)&&(this._parallaxX=a,this._parallaxY=b,this._runtime.UpdateRender(),1!==this._parallaxX||1!==this._parallaxY))for(const a of this._instances)a.GetObjectClass()._SetAnyInstanceParallaxed(!0)}SetParallaxX(a){this.SetParallax(a,this.GetParallaxY())}SetParallaxY(a){this.SetParallax(this.GetParallaxX(),a)}SetZElevation(a){this._zElevation=+a}GetZElevation(){return this._zElevation}SetAngle(b){this._angle=C3.clampAngle(b)}GetAngle(){return this._isAngleEnabled?C3.clampAngle(this._layout.GetAngle()+this._angle):0}GetOwnAngle(){return this._angle}HasInstances(){return 0<this._instances.length}_GetInstances(){return this._instances}GetBackgroundColor(){return this._backgroundColor}IsTransparent(){return this._isTransparent}SetTransparent(a){this._isTransparent=!!a}IsForceOwnTexture(){return this._isForceOwnTexture}SetForceOwnTexture(a){this._isForceOwnTexture=!!a}SetBlendMode(a,b){if(this._blendMode!==a||b){this._blendMode=a;const b=this._runtime.GetWebGLRenderer();if(b){const b=this._runtime.GetWebGLRenderer().GetBlendByIndex(a);this._srcBlend=b.srcBlend,this._destBlend=b.destBlend}this._runtime.UpdateRender()}}GetBlendMode(){return this._blendMode}GetSrcBlend(){return this._srcBlend}GetDestBlend(){return this._destBlend}_IsCollisionCompatibleWith(a){return this._parallaxX===a._parallaxX&&this._parallaxY===a._parallaxY&&this._scale===a._scale&&this._scaleRate===a._scaleRate&&this._angle===a._angle}_RemoveAllInstancesInSet(a){if(0!==a.size){const b=C3.arrayRemoveAllInSet(this._instances,a);0<b&&(this._MaybeResetAnyInstanceZElevatedFlag(),this.SetZIndicesChanged())}}SetZIndicesChanged(){this._zIndicesUpToDate=!1,this._isRenderListUpToDate=!1}_UpdateZIndices(){if(!this._zIndicesUpToDate){if(C3.stableSort(this._instances,b),this._useRenderCells)for(let a=0,b=this._instances.length;a<b;++a){const b=this._instances[a].GetWorldInfo();b._SetZIndex(a),this._renderGrid.MarkRangeChanged(b.GetRenderCellRange())}else for(let a=0,b=this._instances.length;a<b;++a)this._instances[a].GetWorldInfo()._SetZIndex(a);this._zIndicesUpToDate=!0}}MoveInstanceAdjacent(a,b,c){const d=a.GetWorldInfo(),e=b.GetWorldInfo();if(d.GetLayer()!==this||e.GetLayer()!==this)throw new Error("can't arrange Z order unless both objects on this layer");const f=d.GetZIndex();let g=e.GetZIndex();C3.arrayRemove(this._instances,f),f<g&&g--,c&&g++,g===this._instances.length?this._instances.push(a):this._instances.splice(g,0,a),this.SetZIndicesChanged()}_MergeSortedZArrays(c,a){const b=[];let d=0,e=0,f=c.length,g=a.length;for(;d<f&&e<g;){const f=c[d],g=a[e];f.GetWorldInfo()._GetLastCachedZIndex()<g.GetWorldInfo()._GetLastCachedZIndex()?(b.push(f),++d):(b.push(g),++e)}for(;d<f;++d)b.push(c[d]);for(;e<g;++e)b.push(a[e]);return b}_MergeAllSortedZArrays_pass(a){const b=[],c=a.length;for(let d=0;d<c-1;d+=2){const c=a[d],e=a[d+1];b.push(this._MergeSortedZArrays(c,e))}return 1==c%2&&b.push(a[c-1]),b}_MergeAllSortedZArrays(a){for(;1<a.length;)a=this._MergeAllSortedZArrays_pass(a);return a[0]}_GetRenderCellInstancesToDraw(){return this._UpdateZIndices(),C3.clearArray(e),this._renderGrid.QueryRange(this._viewport,e),e.length?1===e.length?e[0]:this._MergeAllSortedZArrays(e):[]}_IsOpaque(){return!this.UsesOwnTexture()&&!this.IsTransparent()}ShouldDraw(){return this.IsVisible()&&0<this.GetOpacity()&&(this.HasInstances()||!this.IsTransparent())}UsesOwnTexture(){return this.IsForceOwnTexture()||!this.HasDefaultColor()||0!==this.GetBlendMode()||this._effectList.HasAnyActiveEffect()}GetRenderTarget(){return this._curRenderTarget}_CanFastPathDrawLayer(a){if(0===a.length)return!0;if(2<=a.length)return!1;const b=a[0],c=b.GetShaderProgram();return!c.MustPreDraw()&&!c.UsesDest()&&!c.UsesCrossSampling()&&this.HasDefaultColor()}Get2DScaleFactorToZ(a){const b=this.GetCameraZ();return b/(b-a)}GetCameraZ(){return 100/this.GetNormalScale()}_SetTransform(b,c=0,d=0){const e=this._runtime.GetRenderScale(),f=(this._viewport.midX()+c)*e,g=(this._viewport.midY()+d)*e,i=this.GetCameraZ();b.SetCameraXYZ(f,g,i),b.SetLookXYZ(f,g,i-100);const j=this.GetAngle(),a=h;0===j?vec3.set(a,0,1,0):vec3.set(a,Math.sin(j),Math.cos(j),0),b.ResetModelView(a),b.Scale(e,e),b.UpdateModelView()}Draw(a,b,c){const d=this._runtime.GetCanvasManager(),e=this.UsesOwnTexture();let f=null,g=null;if(this._runtime.IsGPUProfiling()&&a.SupportsGPUProfiling()){const b=d.GetLayerTimingsBuffer(this);b&&(g=b.AddTimeElapsedQuery(),a.StartQuery(g))}if(e){const b={sampling:this._runtime.GetSampling()};"low"===d.GetCurrentFullscreenScalingQuality()&&(b.width=d.GetDrawWidth(),b.height=d.GetDrawHeight()),f=this._runtime.GetAdditionalRenderTarget(b),a.SetRenderTarget(f),this.IsTransparent()&&a.ClearRgba(0,0,0,0)}else a.SetRenderTarget(b);if(this.IsTransparent()||a.Clear(this._backgroundColor),this._curRenderTarget=f||b,this._SetTransform(a),a.SetBaseZ(this.GetZElevation()),this.GetNormalScale()>Number.EPSILON){this._UpdateZIndices();const b=this._useRenderCells&&0===this.GetZElevation()&&!this._anyInstanceZElevated;b?this._DrawInstances_RenderCells(a):this._DrawInstances(a,this._instances)}a.SetBaseZ(0),a.SetCurrentZ(0),a.SetCameraXYZ(0,0,100),a.SetLookXYZ(0,0,0),e&&this._DrawLayerOwnTextureToRenderTarget(a,f,b,c),g&&a.EndQuery(g),this._curRenderTarget=null}_DrawInstances(a,b){const c=this._viewport,d=this._curRenderTarget;let e=null;for(let f=0,g=b.length;f<g;++f){const g=b[f];if(g===e)continue;e=g;const h=g.GetWorldInfo();h.IsVisible()&&h.IsInViewport(c)&&(h.HasAnyActiveEffect()?this._DrawInstanceWithEffectsAndRestore(g,h,a,d):this._DrawInstance(g,h,a))}}_DrawInstances_RenderCells(a){const b=this._renderGrid,c=this._curRenderCells,d=this._lastRenderCells,e=this._viewport;let f;c.set(b.XToCell(e.getLeft()),b.YToCell(e.getTop()),b.XToCell(e.getRight()),b.YToCell(e.getBottom())),this._isRenderListUpToDate&&c.equals(d)?f=this._lastRenderList:(f=this._GetRenderCellInstancesToDraw(),this._isRenderListUpToDate=!0,d.copy(c)),this._DrawInstances(a,f),f!==this._lastRenderList&&C3.shallowAssignArray(this._lastRenderList,f)}_DrawInstance(a,b,c){const d=b.GetWebGLStateGroup();c.GetCurrentStateGroup()!==d&&d.Apply(),a.Draw(c)}_DrawInstanceWithEffectsAndRestore(a,b,c,d){this._DrawInstanceWithEffects(a,b,c,d,null)&&this._SetTransform(c)}_DrawInstanceWithEffects(a,b,c,d,e){const f=b.GetInstanceEffectList().GetActiveEffectTypes();if(1===f.length){const d=f[0],e=d.GetShaderProgram();if(!e.NeedsPostDrawOrExtendsBox()&&b.HasDefaultColor()&&!a.MustPreDraw())return this._DrawInstanceWithEffects_FastPath(a,b,d,e,c),!1}const g=C3.RenderEffectChain(c,this._runtime,a,d,f,e);return c.SetBaseZ(this.GetZElevation()),g}_DrawInstanceWithEffects_FastPath(a,b,c,d,e){e.SetProgram(d),e.SetBlend(b.GetSrcBlend(),b.GetDestBlend()),d.IsAnimated()&&this._runtime.UpdateRender();let h=0,i=0;if(d.UsesAnySrcRectOrPixelSize()){const b=a.GetCurrentImageInfo();if(b){g.copy(b.GetTexRect());const a=b.GetTexture();a&&(h=1/a.GetWidth(),i=1/a.GetHeight())}else g.set(0,0,0,0)}const j=b.GetInstanceEffectList().GetEffectParametersForIndex(c.GetIndex());e.SetCurrentZ(b.GetZElevation()),e.SetProgramParameters(null,f,g,g,b.GetBoundingBox(),h,i,this.GetOwnScale(),this.GetAngle(),this._runtime.GetGameTime(),j),a.Draw(e)}_DrawLayerOwnTextureToRenderTarget(a,b,c,d){const e=this._effectList.GetActiveEffectTypes(),h=this._runtime;if(this._CanFastPathDrawLayer(e)){if(a.SetRenderTarget(c),1===e.length){const b=e[0],c=b.GetShaderProgram();a.SetProgram(c),g.set(0,0,1,1);const d=this._effectList.GetEffectParametersForIndex(b.GetIndex());a.SetProgramParameters(null,f,g,g,this._viewport,1/h.GetDrawWidth(),1/h.GetDrawHeight(),this.GetNormalScale(),this.GetAngle(),h.GetGameTime(),d),c.IsAnimated()&&h.UpdateRender()}else a.SetTextureFillMode();d&&0===this._blendMode&&this.HasDefaultColor()&&0===e.length?a.CopyRenderTarget(b):(a.SetBlend(this._srcBlend,this._destBlend),a.SetColor(this._premultipliedColor),a.DrawRenderTarget(b)),a.InvalidateRenderTarget(b),h.ReleaseAdditionalRenderTarget(b)}else C3.RenderEffectChain(a,h,this,c,e)}GetOwnScale(){return this._scale}SetOwnScale(a){this._scale===a||(this._scale=a,this._layout.BoundScrolling(),this._runtime.UpdateRender())}GetRenderScale(){return this.GetNormalScale()*this._runtime.GetRenderScale()}GetDisplayScale(){return this.GetNormalScale()*this._runtime.GetDisplayScale()}GetNormalScale(){return(this._scale*this._layout.GetScale()-1)*this._scaleRate+1}UpdateViewport(){var a=Math.round;this._isAngleEnabled=!1;let[b,e]=this.CanvasCssToLayer(0,0);this._isAngleEnabled=!0,this._runtime.IsPixelRoundingEnabled()&&(b=a(b),e=a(e));const f=1/this.GetNormalScale(),g=this._viewportZ0;g.set(b,e,b+this._runtime.GetViewportWidth()*f,e+this._runtime.GetViewportHeight()*f);const h=this.GetAngle();0!==h&&(c.copy(g),c.offset(-g.midX(),-g.midY()),d.setFromRotatedRect(c,h),d.getBoundingBox(c),c.offset(g.midX(),g.midY()),g.copy(c)),this.GetViewportForZ(this._zElevation,this._viewport)}CanvasCssToLayer(a,b,c=0){return this._CanvasToLayer(a,b,c,this.GetDisplayScale())}DrawSurfaceToLayer(a,b,c=0){return this._CanvasToLayer(a,b,c,this.GetRenderScale()*self.devicePixelRatio)}_CanvasToLayer(b,c,d,e){const f=this._runtime.GetParallaxXOrigin(),g=this._runtime.GetParallaxYOrigin(),h=(this._layout.GetScrollX()-f)*this._parallaxX+f,i=(this._layout.GetScrollY()-g)*this._parallaxY+g,j=this.GetNormalScale(),k=this._runtime.GetViewportWidth()/j,l=this._runtime.GetViewportHeight()/j;let m=h-k/2+b/e,n=i-l/2+c/e;const o=this.GetAngle();if(0!==o){m-=h,n-=i;const a=Math.cos(o),b=Math.sin(o),c=m*a-n*b;n=n*a+m*b,m=c,m+=h,n+=i}if(0!==d){const a=this._viewportZ0.midX(),b=this._viewportZ0.midY(),c=this.Get2DScaleFactorToZ(d);m=(m-a)/c+a,n=(n-b)/c+b}return[m,n]}CanvasCssToLayer_DefaultTransform(a,b){const c=this._scale,d=this._scaleRate,e=this._parallaxX,f=this._parallaxY,g=this._angle;this._scale=1,this._scaleRate=1,this._parallaxX=1,this._parallaxY=1,this._angle=0;const h=this.CanvasCssToLayer(a,b);return this._scale=c,this._scaleRate=d,this._parallaxX=e,this._parallaxY=f,this._angle=g,h}LayerToCanvasCss(a,b,c=0){return this._LayerToCanvas(a,b,c,this.GetDisplayScale())}LayerToDrawSurface(a,b,c=0){return this._LayerToCanvas(a,b,c,this.GetRenderScale()*self.devicePixelRatio)}_LayerToCanvas(b,c,d,e){if(0!==d){const a=this._viewportZ0.midX(),e=this._viewportZ0.midY(),f=this.Get2DScaleFactorToZ(d);b=(b-a)*f+a,c=(c-e)*f+e}const f=this._runtime.GetParallaxXOrigin(),g=this._runtime.GetParallaxYOrigin(),h=(this._layout.GetScrollX()-f)*this._parallaxX+f,i=(this._layout.GetScrollY()-g)*this._parallaxY+g,j=this.GetAngle();if(0!==j){b-=h,c-=i;const d=Math.cos(-j),e=Math.sin(-j),f=b*d-c*e;c=c*d+b*e,b=f,b+=h,c+=i}const k=this.GetNormalScale(),l=this._runtime.GetViewportWidth()/k,m=this._runtime.GetViewportHeight()/k,n=b-(h-l/2),o=c-(i-m/2);return[n*e,o*e]}_SaveToJson(){const a={"s":this.GetOwnScale(),"a":this.GetOwnAngle(),"vl":this._viewport.getLeft(),"vt":this._viewport.getTop(),"vr":this._viewport.getRight(),"vb":this._viewport.getBottom(),"v":this.IsVisible(),"bc":this._backgroundColor.toJSON(),"t":this.IsTransparent(),"px":this.GetParallaxX(),"py":this.GetParallaxY(),"c":this._color.toJSON(),"sr":this.GetScaleRate(),"fx":this._effectList.SaveToJson(),"cg":this._createdGlobalUids};return a}_LoadFromJson(a){this._scale=a["s"],this._angle=a["a"],this._viewport.set(a["vl"],a["vt"],a["vr"],a["vb"]),this._isVisible=!!a["v"],this._backgroundColor.setFromJSON(a["bc"]),this._isTransparent=!!a["t"],this._parallaxX=a["px"],this._parallaxY=a["py"],this._color.setFromJSON(a["c"]),this._scaleRate=a["sr"],C3.shallowAssignArray(this._createdGlobalUids,a["cg"]),C3.shallowAssignArray(this._initialInstances,this._startupInitialInstances);const b=new Set(this._createdGlobalUids);let c=0;for(let d=0,e=this._initialInstances.length;d<e;++d)b.has(this._initialInstances[d][2])||(this._initialInstances[c]=this._initialInstances[d],++c);C3.truncateArray(this._initialInstances,c),this._effectList.LoadFromJson(a["fx"]),this._SortInstancesByLastCachedZIndex(!1),this.SetZIndicesChanged()}GetILayer(){return this._iLayer}}}

## Steps to reproduce

1. 
2.
3.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** First started happening in r153 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r153 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 751 mb (2.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro FX 2800M Direct3D11 vs_4_0 ps_4_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_disjoint_timer_query
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I'm afraid there's nothing we can do about reports like this. Please see the bug report guidelines - we need all that information to be able to help.
