### ISSUE TITLE
Using the export manager to build C2 games doesn't work anymore

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#3043]
## Problem description

After exporting a C2 project using Cordova, creating the zip file, importing the zip file into C3's export manager and trying to build it, the build always fail.
I've done this hundreds of times and right now all seems to be broken. This happen with my big project as well as with a very simple project with just a sprite that I attach below.

## Attach a .c3p

This is the file already exported with C2 and zipped, ready to be imported in C3: 
[Uploading testExport.zip…]()

This is the C2 capx:
[testExportC2project.zip](https://github.com/Scirra/Construct-3-bugs/files/3293851/testExportC2project.zip)

## Steps to reproduce

1. Export any C2 project using cordova
2. zip the file
3. import it into C3's Export manager
4. click the build button

## Observed result

The build is never completed.
This message shows up:
![build_failed](https://user-images.githubusercontent.com/29117306/59559469-29fb8b80-9008-11e9-9e84-371900205cba.jpg)
I tried this on the Desktop Build, and on web-based editor r153, r148 and r142, all give the same result.

## Expected result

The build should complete successfully

## More details

**Affected browsers/platforms:** Desktop Build, Chrome.

r142, r148, r153, Desktop Build

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r153 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 19 gb
Storage usage (approx): 3.6 gb (19.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Thanks for the report. We did some upgrades to the build server a few weeks back and it apparently regressed Construct 2 compatibility. I've resolved the issue now, as it's a server change the revisions are already available. Let me know if you find any more issues.

**Comment by RabloGames** [comment]
Everything is working fine again. Thanks a lot !
