### ISSUE TITLE
Desktop version crashes without any message

### ISSUE THREAD

**Issue by tatosgames** [Scirra/Construct-3-bugs#3044]
## Problem description
With the new desktop version https://downloads.scirra.com/c3-desktop/win64/construct3-win64-c75-stable.zip the editor close suddently without error message, warning or time to save. Simply it close without saving losing all the edits :\
I would like to report better the error but I can't get any error message

## Attach a .c3p
[musictest.zip](https://github.com/Scirra/Construct-3-bugs/files/3294260/musictest.zip)

## Steps to reproduce
1. work on the project
2. preview the game varios times (the project is not relevant)
3. the preview and the editor closes

## Observed result
The software close without any message

## Expected result
I would like any information message to know what happened

## More details

**Affected browsers/platforms:** 
Windows 10 N destkop, old version overwritten on the with the new one. Maybe a force cache clear? or an unistaller of the old one?

**First affected release:** 
First happening in desktop stable C75
## System details

<details><summary>View details</summary>
Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r148 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 230 gb
Storage usage (approx): 455 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by tatosgames** [comment]
Additional information: it seems the closing error without message (also the debug.log is empty) happens when using a lot the browser debugger (f12, nw.js debugger)

**Comment by AshleyScirra** [comment]
Looks like the same issue as #2962 so closing as duplicate
