### ISSUE TITLE
Construct 3 r148 and is really slow and crashed

### ISSUE THREAD

**Issue by Underdog-debug** [Scirra/Construct-3-bugs#3046]
## Crash Construct 3 & slow in use

 Random crashes and really slow to use since last update r148 Construct 3

## Attach a .c3p
I had an Error Report information, see below

## Steps to reproduce

No steps, just crashed - However, I was in the Animation Editor.
But, Construct 3 is really slow to use now and saving time takes for ever.

## Observed result

Really slow time to save and crashed (error report pasted)

## Expected result
No crash and no slow :)
Using App Desktop. It was working well when I used the online app.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

**Error report information**
Type: unhandled exception
File: https://editor.construct.net/r148/main.js, line 2, col 94673
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Function.ǃk.ǃUa (https://editor.construct.net/r148/main.js:2:94679) at e.ǃgcE.ǃgcw (https://editor.construct.net/r148/main.js:178:255826) at https://editor.construct.net/r148/main.js:178:257502
Construct 3 version: r148
URL: https://editor.construct.net/
Date: Sun Jun 16 2019 17:32:18 GMT-0400 (heure d’été de l’Est)
Uptime: 8642 s

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r148 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid there's nothing we can do about reports like this. Please see the bug report guidelines - we need all that information to be able to help.
