### ISSUE TITLE
Google Play plugin condition 'On error' not working

### ISSUE THREAD

**Issue by ConstructCreativeMind** [Scirra/Construct-3-bugs#3047]
## Problem description

The condition 'On error' of the official Google Play plugin is not triggering when errors are occuring. Triggering is not happening when a manual sign-in fails or a leaderboard can not be shown. 

## Attach a .c3p

[bugreport.zip](https://github.com/Scirra/Construct-3-bugs/files/3299274/bugreport.zip)

## Steps to reproduce

1. Install the signed APK on an Android device
2. Enable internet connection
3. Start the APK
4. Wait for the Google Play login to be completed and then several seconds more

## Observed result

The app is signing into your Google Play account.
If succeeded, it tries to open a non-existing leaderboard. There is no error message shown.
If not succeeded, there is no error message shown.

## Expected result

It is expected that the lower text object states 'Error', as soon as the manual Google Play login fails or the leaderboard opening fails.

## More details
The minimal example is being provided with fake app IDs and fake Google Play Game IDs. The same issues happen when using IDs from real, published apps.

The minimal example uses the C2 runtime.

**Affected browsers/platforms:** Android

**First affected release:** Not all releases tested for affection. So far observable in C3 r148 stable.

## System details

No crah report. Device details enclosed.

<details><summary>View details</summary>

Samsung Galaxy S5 mini
Modell number SM-G800F
Android version 6.0.1
Build number MMB29K.G800FXXU1CRG3

</details>

**Comment by shortercode** [comment]
Unfortunately it doesn't look like Play games actually generates an error when you attempt to show a non existing leaderboard... even though it can't load the leaderboard it considers it a success. So there's not much we can do about that.

We didn't have a condition for catching errors from a sign in, so I've added one for the next release. I think most devs are probably just use "OnSignedIn", "OnSignedOut" and "IsSignedIn" but we should still have a handler for this. 

In terms of the error message you get Play games basically only gives you an error code which you have to go look up online. Typically the error code is pretty useless though.
