### ISSUE TITLE
Audio plugin sometimes messes up "is tag playing" condition

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3049]
## Problem description

That was a tough one to figure out and reproduce, and it's mainly due to its suuuuuuuuper weird nature. Basically, with Mateus Sales, we noticed that in his in dev game, the audio would sometimes play two music on top of each other. However that didn't make any sense because the system was designed to not do that. 

We figured out that it would happen in a very specific scenario, when trying to play a music (on tag 'tag_music') when a sound was already playing on 'tag_sound' and only if the music to be played was chosen using the 'choose' expression

## Attach a .c3p

This sounds very confusing, here is a minimal replica of what was happening
[audio tags bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3302513/audio.tags.bug.zip)

## Steps to reproduce

1. Hit play a few times, a variable will keep track of the double triggers
2. If a double trigger happened, there you have it
3. If no double trigger happened after a while, then you might need to restart the game by pressing F5

## Observed result

This is not consistent, but sometimes, the event double triggers.
Here is a video Mateus made that shows this happening 
https://www.youtube.com/watch?v=nIGhzTUnNmI&feature=youtu.be

## Expected result

This should not be happening

## More details
A very weird part about this was that it would only work when choose was used. I have no idea why, but a plausible explanation would be as following:
when choose is ran, it generates a random number from 0 to arguments.length and picks the item at the id generated, however if something fails for any reason (and I have no clue why it would), a safety thing runs the event block again.

However, that only happens if the audio plugin received another request for playing something but on a different tag, so maybe the thing that fails happens in the audio plugin???

I have no clue.

**Affected browsers/platforms:** 

**First affected release:** r154

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by BonzerKitten7** [comment]
Thank you very much for writing the whole report, Ossama! It really is a super weird and specific bug.

**Comment by AshleyScirra** [comment]
Thanks for the minimal repro. The state handling in this case is complicated, because to support worker mode playback is actually asynchronous, and then for compatibility with the C2 runtime "is playing" has to update synchronously after the "Play" action until real playback state is received. It looks like that it was possible in some cases to update the state too early resulting in "is playing" being false just after starting playback.

I could occasionally but not reliably reproduce this in the first place, and I can't reproduce it any more with my fix, but given the unreliable/probabilistic nature of the issue I think it's worth verifying this works for you after the next release is out.

**Comment by skymen** [comment]
Alright, great. Thanks for fixing this. We'll look into it on the next release and close this thread if we can't manage to reproduce it :)

**Comment by AshleyScirra** [comment]
r155 is out, can you verify if it's working there?

**Comment by BonzerKitten7** [comment]
I tried to reproduce the bug using my game (where we first encountered it) and using Skymen's minimal repro, but apparently the bug is gone. However, I think we should wait for Skymen's tests before closing this issue. Thank you very much, Ashley.

**Comment by skymen** [comment]
Tried to reproduce it as well, can confirm that it doesn't happen anymore. Though I doubt it will happen again (and I hope it won't), if it does, I'll open a new bug report with a new minimal c3p as this method doesn't seem to make it happen consistently anymore.
Thanks for the fix.
