### ISSUE TITLE
I can't preview my game (all i get is a black screen)

### ISSUE THREAD

**Issue by GreatProgressPluto** [Scirra/Construct-3-bugs#305]
## Problem description

*Enter a concise description of your problem here*
I was working on a game for the NG game jam, and could preview the project fine, but just a few minutes ago, the preview doesn't work, no matter how many objects, events i delete, it says it's stuck on 90% (in inspector mode), while other projects and examples run fine.

And i have tested on another computer, the same results, a black screen...

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
[Problematic.zip](https://github.com/Scirra/Construct-3-bugs/files/1017347/Problematic.zip)

(I should note this is almost empty, because i wanted to get rid of everything that might cause an issuse, but even without most of the stuff, its still not working (i have a backup where i didn't delete, but it doesn't work either)

## Steps to reproduce

1.Open the project
2.Run in preview (or in debug mode)

## Observed result

*What do you see happen?*
If you encounter what i encountered, it should display a black screen, with no signs of loading.

## Expected result

*What did you expect to happen instead?*
I want to be able to preview my game normally, for checking to see if the game works.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

Local storage
Storage quota (approx): 29 gb
Storage usage (approx): 22 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
There would appear to be something wrong with the roboto slab font, still looking at why it's causing it to break but you should be able to recover your project by deleting that font.

**Comment by shortercode** [comment]
@AshleyScirra I would appreciate a second set of eyes on this. It seems to be triggering an awkward network condition. I believe document.fonts.load might be triggering it, but not throwing the error in the correct context so the promise is kinda useless.

**Comment by shortercode** [comment]
Scratch that, I think I've got it... debugger wasn't loading the changes correctly. We can catch it in the promise chain.

**Comment by GreatProgressPluto** [comment]
Thanks!

i did what you said (deleting the roboto slab font) and the game now works! Thank you!
