### ISSUE TITLE
Clicking Del or Backspace when editing keyframe time, deletes the keyframe

### ISSUE THREAD

**Issue by trueicecold** [Scirra/Construct-3-bugs#3054]
Clicking Del or Backspace when editing keyframe time, deletes the keyframe altogether.

## Steps to reproduce

1. Create a timeline and add an instance of a sprite to it
2. Click on a keyframe to edit its time
3. Click delete/backspace in the "Time" field

## Observed result

The keyframe is deleted.

## Expected result

Text Input there should act like a normal text input, accepting delete/backspace to edit it.

## More details

Right now, only way of editing it is by selecting the text inside and then typing another one.

**Comment by DiegoScirra** [comment]
Fixed already available in the latest beta.
