### ISSUE TITLE
Mobile Advert build error

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#3056]
c2runtime export android debug or signed does not work due to the google play services plugin.
I see its error:

Error: Discovered platform "android@^8.0.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@^8.0.0
Adding android project...
Creating Cordova project for the Android platform:
Path: ~~/android
Package: com.eragames.fishingrain
Name: Fishing_rain
Activity: MainActivity
Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.0.0
Plugin 'construct-mobile-purchase' found in config.xml... Migrating it to package.json
Plugin 'construct-mobile-advert' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-inappbrowser' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-vibration' found in config.xml... Migrating it to package.json
Plugin 'construct-play-games' found in config.xml... Migrating it to package.json
Discovered saved plugin "construct-mobile-purchase". Adding it to the project
Installing "construct-mobile-purchase" for android
Discovered saved plugin "construct-mobile-advert". Adding it to the project
Failed to restore plugin "construct-mobile-advert" from config.xml. You might need to try adding it again. Error: Variable(s) missing (use: --variable ADMOB_APP_ID=value).
Discovered saved plugin "cordova-plugin-inappbrowser". Adding it to the project
Installing "cordova-plugin-inappbrowser" for android
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for android

This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Discovered saved plugin "cordova-plugin-vibration". Adding it to the project
Installing "cordova-plugin-vibration" for android
Discovered saved plugin "construct-play-games". Adding it to the project
Installing "construct-play-games" for android
Installing "cordova-plugin-androidx" for android
Subproject Path: CordovaLib
Subproject Path: app

**Comment by shortercode** [comment]
The errror is actually in the mobile advert plugin

```
Failed to restore plugin "construct-mobile-advert" from config.xml. You might need to try adding it again. Error: Variable(s) missing (use: --variable ADMOB_APP_ID=value).
```

You seem to have ended up with a development version of the plugin, sorry about that.

**Comment by sizcoz** [comment]
This is a thing, it crashes C3 every time when I try to builed a signed APK
Error report information
Type: unhandled rejection
Reason: undefined
Construct 3 version: r154
URL: https://editor.construct.net/r154/
Date: Wed Jun 19 2019 18:20:42 GMT+0100 (British Summer Time)
Uptime: 99047.6 s

Platform information
Browser: Chrome
Browser version: 75.0.3770.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36
C3 release: r154 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by shortercode** [comment]
The build server had a few hitches while I was updating, should be resolved now. I'm not sure why it was causing a crash for you though. I'll do some additional testing tomorrow and see if I can figure out why.

**Comment by sizcoz** [comment]
Ok, cheers

**Comment by shortercode** [comment]
@ERAgames777 is this resolved for you now? I would like to close, and it would be good to know if the server is stable again.

**Comment by ERAgames777** [comment]
No, now I see this error:

Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
:wrapper

BUILD SUCCESSFUL

Total time: 0.963 secs
Subproject Path: CordovaLib
Subproject Path: app
> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest
> Task :CordovaLib:processDebugManifest
> Task :app:preDebugBuild
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript
> Task :app:checkDebugManifest
> Task :app:generateDebugBuildConfig
> Task :app:prepareLintJar
> Task :app:generateDebugSources
> Task :CordovaLib:compileDebugRenderscript
> Task :CordovaLib:generateDebugBuildConfig
> Task :CordovaLib:generateDebugResValues
> Task :CordovaLib:generateDebugResources
> Task :CordovaLib:packageDebugResources
> Task :CordovaLib:generateDebugRFile
> Task :CordovaLib:prepareLintJar
> Task :CordovaLib:generateDebugSources
> Task :CordovaLib:javaPreCompileDebug

> Task :CordovaLib:compileDebugJavaWithJavac

> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
> Task :app:javaPreCompileDebug
> Task :app:mainApkListPersistenceDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:mergeDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:processDebugManifest
> Task :app:processDebugResources

> Task :app:compileDebugJavaWithJavac

> Task :app:compileDebugNdk NO-SOURCE
> Task :app:compileDebugSources
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders
> Task :app:generateDebugAssets
> Task :CordovaLib:mergeDebugShaders
> Task :CordovaLib:compileDebugShaders
> Task :CordovaLib:generateDebugAssets
> Task :CordovaLib:packageDebugAssets
> Task :app:mergeDebugAssets
> Task :app:validateSigningDebug
> Task :app:signingConfigWriterDebug
> Task :app:transformClassesWithDexBuilderForDebug

> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
35 actionable tasks: 35 executed

**Comment by shortercode** [comment]
I think that's related to #3057

**Comment by ERAgames777** [comment]
@shortercode Yes, I added the google play plugin and an error occurs, if the plugin is removed from the project, the construction is successful.

**Comment by shortercode** [comment]
Okay dokes, let's track that on the other issue.
