### ISSUE TITLE
r???-r154 Function categories sorts in alphabetical order.

### ISSUE THREAD

**Issue by Kramdos** [Scirra/Construct-3-bugs#3058]
## Problem description

In the "Add 'Functions' action" menu, when a category has a name that comes before 'Function Maps' and 'Functions' alphabetically, those categories gets pushed down.

## Steps to reproduce

1. Create a function category with a name that comes alphabetically before 'Function Maps' or 'Functions'.
2. Try to add a 'Functions' action.

## Observed result

'Function Maps' and 'Functions' gets lost in the menu. See image for example.
![image](https://user-images.githubusercontent.com/49698600/59805749-6eca3f80-92f2-11e9-941f-68ca3f3623f9.png)

## Expected result

'Function Maps' and 'Functions' staying at the top of the menu above all the categories.

**Comment by AshleyScirra** [comment]
This is by design. Nowhere else in Construct are those categories sorted differently to alphabetic.
