### ISSUE TITLE
Remote Preview does not work with Physics behavior in beta 154.

### ISSUE THREAD

**Issue by SloRey** [Scirra/Construct-3-bugs#3060]
## Problem description
Remote Preview does not work with Physics behavior in beta 154.
Stuck at loading/splash screen.

Console error:
`Uncaught (in promise) TypeError: self.Box2DWasmModule is not a function
    at 3802895b-d76a-41ed-90ff-82e8a252f830:1
    at new Promise (<anonymous>)
    at C3.Behaviors.Physics._LoadBox2DWasm (3802895b-d76a-41ed-90ff-82e8a252f830:1)`

Works fine in beta 153 and earlier.
Beta 154 also loads in regular preview, debug, export to Web HTML5, export to NW.js.

## Attach a .c3p

[PhysicsRemotePreview154.zip](https://github.com/Scirra/Construct-3-bugs/files/3308738/PhysicsRemotePreview154.zip)

## Steps to reproduce

1. Open attached c3p in beta 154 or create a new project and add a sprite/object with physics behavior.
2. Preview through Remote Preview.
3. Redo step 1 and 2 in beta 153.

## Observed result

Stuck at splash screen/ loading screen for beta 154 but fine in beta 153.

## Expected result

Beta 154 to load like beta 153.

## More details

**Affected browsers/platforms:** 
Chrome (Windows, Mac)
Firefox (Windows)
Safari (Mac, iOS)

**First affected release:** 

Beta 154.

## System details

<details><summary>View details</summary>

`Uncaught (in promise) TypeError: self.Box2DWasmModule is not a function
    at 3802895b-d76a-41ed-90ff-82e8a252f830:1
    at new Promise (<anonymous>)
    at C3.Behaviors.Physics._LoadBox2DWasm (3802895b-d76a-41ed-90ff-82e8a252f830:1)`

</details>

**Comment by AshleyScirra** [comment]
The fix for this has been done on the server-side, but if it's cached you won't get the update yet. If you clear your browser cache and retry, is it working for you?

**Comment by AshleyScirra** [comment]
Looks like the server-side update is complete and this is working correctly now.

**Comment by SloRey** [comment]
Still affects safari (iOS) in the current latest build (r/156-2)
