### ISSUE TITLE
Unselected layout tab defaults to white in dark theme when tabbed on independent layout window

### ISSUE THREAD

**Issue by LukeWolfGames** [Scirra/Construct-3-bugs#3064]
## Problem description

Unselected layout tab defaults to white in dark theme when tabbed on independent layout window.

It's a bit hard to explain so I'll show you a screenshot of how I've laid out my editor:

![kxjEBid](https://user-images.githubusercontent.com/28833199/59959690-b5d95000-94ff-11e9-86ea-fe2748263699.png)

## Attach a .c3p

https://www.dropbox.com/s/pro3gm8veh3sojx/Layout%20tab%20text%20colours%20changing%20to%20white%20when%20tabbed%20on%20indepedant%20window.c3p?dl=0

## Steps to reproduce

1. Make sure dark theme is selected in your settings!
2. Separate the layout window so it's independent to the event sheet tabs.
3. Open the layouts (or add more of them).
4. Move the new layout tab to be tabbed underneath the previous layout so it creates tabs for layouts.
5. Make sure one of the layouts tabs are selected.

## Observed result

The layout that you have not selected default to white and impossible to read especially with the default background colours Construct gives them.

## Expected result

The default text colour should be black like the event sheet text so it's readable.

## More details

**Affected browsers/platforms:** Desktop

**First affected release:** r155

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r155 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 74 gb
Storage usage (approx): 1.8 gb (2.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks like the dark theme doesn't have styles to cover this case. The main tabs are separately styled using a lower opacity to fade out inactive tabs. The bar tabs however use a dark grey background with white text for inactive tabs, and invert that to a white background with dark grey text when selected. This does not take in to account the case where multicolor editor tabs are docked as bar tabs - it keeps the tab background color but leaves the text white. It makes sense to have the theme treat all tabs the same way so this type of thing doesn't happen. I think that will have to be handled by the theme designer @Animmaniac.

**Comment by DiegoScirra** [comment]
Better late than never. This will be fixed for the next beta.
