### ISSUE TITLE
Window Move, Resize not work with Debugger [r155]

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3065]
## Problem description

This action not work when I use "Debug Project"
![image](https://user-images.githubusercontent.com/13033837/59966512-46c32200-9526-11e9-9e71-e96020878f99.png)

But it is work with "Preview Project"

[TestResize.zip](https://github.com/Scirra/Construct-3-bugs/files/3317036/TestResize.zip)

## Observed result

Resize and move not work

## Expected result

It should work as Preview

**Affected browsers/platforms:** Chrome

**Comment by AshleyScirra** [comment]
In this case the window is an iframe and therefore those calls have no effect. I don't think it's feasible to fix this given that you are directly executing strings of JS code.
