### ISSUE TITLE
"Tint Effect" changes other created objects without effect (r155 beta)

### ISSUE THREAD

**Issue by cerxer** [Scirra/Construct-3-bugs#3066]
[tintproblem.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3317766/tintproblem.c3p.zip)

When I use "tint effect" on an object, other new created objects which didnt have "tint effect" get tint effect. 

https://www.dropbox.com/s/pzlg5ozl2pp32xl/tintproblem.c3p?dl=0

## Steps to reproduce

1. Sprite has tint effect, monster didn't.
2. Run project.
3. Observe that they both have tint effect in preview

## Observed result

Both objects get tint.

## Expected result

Just one should get tint.

## More details

If i put object in layout (not create freshly) there is no problem. If there is no instance of that object in layout then you get this problem.

**Affected browsers/platforms:** 

**First affected release:** 

No problem in stable version.Only r155.

**Comment by AshleyScirra** [comment]
After fixing #3068 I can't reproduce this any more, and the fix for that issue came down to a mistake in how WebGL state groups are handled which could have affected effect rendering too. So I suspect it's the same underlying issue and so should be working in the next release.
