### ISSUE TITLE
Wall clock stops for no reason.

### ISSUE THREAD

**Issue by Doupiz** [Scirra/Construct-3-bugs#3068]
## Problem description

Time stops/pauses without a specific event or crash. The issue started after updating to R155 beta. Everything was working on R154.

## Attach a .c3p

[Cashew-Broken.zip](https://github.com/Scirra/Construct-3-bugs/files/3318349/Cashew-Broken.zip)

## Steps to reproduce

1. Click on add category button in project.
2. Enter any text in the text field
3. Click confirm button.

## Observed result

A gray object is tweened to a position (THAT IS NOT FINAL) and stops. 
The debug wall clock stops.
When you click on a button again, it doesn't get destroyed (although debug mode says they are) and the should-be-destroyed buttons are active

## Expected result

The newly created gray object should be tween to fit the screen. 
The application shouldn't become stopped. 
On clicking the button object (add category) the object should get destroyed.

## More details
I don't have an older build saved on earlier version to see if its still working on an older version of construct.

**Affected browsers/platforms:** I have tested the issue on chrome, firefox and mobile chrome.

**First affected release:** R155 Beta

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36
C3 release: r155 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 876 mb (5.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Doupiz** [comment]
I was able to find a working older version. I have tested it on 154 and its working as intended. Its producing totally different results in 155. Project is not broken (whew).

[Cashew-working-on-154.zip](https://github.com/Scirra/Construct-3-bugs/files/3318362/Cashew-working-on-154.zip)

**Comment by AshleyScirra** [comment]
The wall clock stops because it's crashing. Thanks for the report, should be fixed in next release.
