### ISSUE TITLE
Create object by name with Family.UID doesn't work [r155]

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3069]
## Problem description

I use `Create object by name` action
 `-> Family1: Set Ready to True` action works fine but `Family1.UID` returns only first created object's UID.

![image](https://user-images.githubusercontent.com/13033837/59980823-9592b980-9603-11e9-8012-4aad652a2c4b.png)

 It is return me every time same number.
![image](https://user-images.githubusercontent.com/13033837/59980841-d985be80-9603-11e9-87c2-daf1b4d98603.png)
You can see in chrome logs.
![image](https://user-images.githubusercontent.com/13033837/59980847-ea363480-9603-11e9-9e32-4cc913befac4.png)

When I use **Rex Nickname** plugin with Construct 2, it was works fine.
![image](https://user-images.githubusercontent.com/13033837/59980899-ba3b6100-9604-11e9-8eac-2ad518f9f466.png)

**C3 `Create object by name` doesn't put object into Family?**
and why `-> Family1: Set Ready to True` action works but I can't get Family object's UID with `Family1.UID` expression?

## Attach a .c3p

[TestPick.zip](https://github.com/Scirra/Construct-3-bugs/files/3318439/TestPick.zip)

## Steps to reproduce

1. Run project and look Family Object's instance variables
2. Only first one `OK=True`, others `False`

## Observed result

Only return first created objects UID

## Expected result

Should return created objects UID

**Comment by AshleyScirra** [comment]
The "Create object" action does not create using the name "Family1", so nothing in "Family1" is picked. This is by design. Instead use the "Pick last created" event and choose "Family1".

**Comment by QuasarX** [comment]
1.) I tried this and **don't run that function.**
![image](https://user-images.githubusercontent.com/13033837/60022332-4a78b500-969c-11e9-8efc-90f387fbcfed.png)

2.) I tried this and **I get only 7 in console logs**
![image](https://user-images.githubusercontent.com/13033837/60022443-827ff800-969c-11e9-9ea5-84d1674471f2.png)

Console logs
![image](https://user-images.githubusercontent.com/13033837/60022500-a04d5d00-969c-11e9-955b-ec7fe579f45f.png)

**Comment by AshleyScirra** [comment]
This works fine:

![ui-layout-3071](https://user-images.githubusercontent.com/768723/60023356-8eb08900-968d-11e9-98f2-ea0057fd2a90.png)

You're probably running in to the fact that newly created instances cannot be picked by other events until the end of the next top-level event.

**Comment by QuasarX** [comment]
But still you can't select Object's UID with expression. I need get that value for using some special actions.
Just made this example for minimal bug report.

**Comment by QuasarX** [comment]
OK made another example

**Browser log shows last created Family Object's UID** but **Function don't run**. How?
![image](https://user-images.githubusercontent.com/13033837/60024523-8e6db900-96a0-11e9-8a66-25cd8bbf883e.png)

Console logs. You can see funciton don't run
![image](https://user-images.githubusercontent.com/13033837/60024566-a7766a00-96a0-11e9-9301-aea5b2383e83.png)

**Comment by QuasarX** [comment]
Updated comment and added another example.

**Comment by AshleyScirra** [comment]
I already explained:

> You're probably running in to the fact that newly created instances cannot be picked by other events until the end of the next top-level event.

**Comment by QuasarX** [comment]
So I need use `wait 0` ? This works.
![image](https://user-images.githubusercontent.com/13033837/60028472-09869d80-96a8-11e9-9e0d-ab628339deec.png)

**Comment by AshleyScirra** [comment]
The easiest solution is to both create and initialise the object in a function, instead of creating an object then calling a function to initialise it. That way you don't have to work around the issue with picking newly created objects.

**Comment by AshleyScirra** [comment]
Actually, another way to fix it is to use the "Pick by unique ID" condition. That is specially designed to allow picking newly created instances. For some reason you're instead using the "Pick by comparison" condition to test based on the Family1.UID expression, which does not support this case. You should use the built-in conditions when they can do what you want.

**Comment by QuasarX** [comment]
"Pick by unique ID" This is works, thanks.
