### ISSUE TITLE
Preview dialog stop to resize unless you drag very slowly

### ISSUE THREAD

**Issue by narFnarF** [Scirra/Construct-3-bugs#307]
## Problem description
The Preview dialog don't resize when dragging the edge of the dialog at anything other than very slow speed. Especially when trying to shrink down the size of the dialog.

## Attach a .c3p
Use the Glokar demo project

## Steps to reproduce

1. Open the Glokar demo project
2. Menu > Settings >Preview with > Dialog
3. Close Settings
4. Click the Preview button
5. Resize the preview window by holding on the edge of the dialog
6. Try resizing at various speed (slow or fast drag)

## Observed result
When dragging the edge at medium or fast speed, the dialog stops resizing.
This is especially noticeable when you try to reduce the size of the dialog.

## Expected result
The dialog continue to resize as long as I hold the edge, regardless of speed.

## Affected browsers

* Chrome: yes (latest Version 58.0.3029.110 (64-bit))
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 88 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 745 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
@narFnarF are you using the setting "preview in dialog"?

**Comment by narFnarF** [comment]
Yes. I mention it in step 3.

**Comment by shortercode** [comment]
@narFnarF ah sorry missed that, thanks for confirming 👍

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r31.
