### ISSUE TITLE
Double clicking action/expression woes

### ISSUE THREAD

**Issue by 7Soul** [Scirra/Construct-3-bugs#3070]
I noticed sometimes double clicking an option would select the wrong one, but now I figured out why:

![record2](https://user-images.githubusercontent.com/5599828/59981425-797a2280-95d9-11e9-86ac-4f15affef46d.gif)

When you click an option that has a description with a different number of lines of the previously selected option, the entire list will shift up or down. 

In the case shown in the gif, if I double click "Regenerate obstacles map", the first click selects it, causes the list to move down, and then the second click selects and confirms the option above it

**Comment by AshleyScirra** [comment]
I'm not sure what to do about this. If we use a fixed size header, the longer descriptions will be truncated. We could add a scroll bar, but that seems odd (and still won't be all visible at once, making the description less useful). We could move the whole header to the bottom instead, but that seems quite a drastic change for this. So there don't seem to be any good options...

**Comment by shortercode** [comment]
Could we just add a delay of say 500ms to changing the description? Would resolve the issue for most people. Users might perceive the UI as being laggy though with that much delay though, and it doesn't guarantee people with slow double clicks will avoid the problem.

**Comment by AshleyScirra** [comment]
Yeah that's another option, but as you note a 500ms is clearly visible which makes it look like the UI is laggy.

**Comment by AshleyScirra** [comment]
Maybe we could ignore a double click if the two mousedowns are over different items.

**Comment by shortercode** [comment]
100ms is considered the acceptable latency, so yeah it's quite a bit slower than that. We could check how it feels, but I expect the effect will be negative to the experience.

Filtering double click by the item would work well I think, and wouldn't be too complex.

**Comment by SnipG** [comment]
Change description text location to bottom

**Comment by 7Soul** [comment]
Maybe always keep enough space at the top for 3 lines

**Comment by AshleyScirra** [comment]
I don't want to make a drastic UI change over a relatively minor issue, and reserving more space does not actually fix the problem, it just means it only happens with longer descriptions. I've implemented a change for the next release that just ignores a double-click if the second click is not over the same item as the first. It means the items move up and down without closing the dialog. It's still a bit odd but at least it forces you to pick the right item, and should still be pretty rare.
