### ISSUE TITLE
Separate tabbed layout window causes premature scrolling when dragging events

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#3071]
## Problem description

Premature scrolling of the event sheet occurs whilst dragging events and you have a tabbed layout window separate to the event sheet. 

## Attach a .c3p

https://www.dropbox.com/s/3fj10d1zxkrwq32/Separate%20tabbed%20layout%20window%20causes%20inappropriate%20scrolling%20when%20dragging%20events.c3p?dl=0

## Steps to reproduce

1. Separate the layout window so it's independent to the event sheet tabs.
2. Open the layouts (or add more of them).
3. Move the new layout tab to be tabbed underneath the previous layout so it creates tabs for layouts.
4. Highlight at least one of the actions at the bottom of the event sheet (you can also highlight the entire block and do this).
5. Drag them to event 40.

## Observed result

The event sheet scrolls prematurely causing disorientation and making it very difficult to place events in desired places.

## Expected result

The event sheet does not scroll unless my mouse is at the top of the event sheet poking the edge regardless whether or not there are tabbed layout windows elsewhere.

## More details
It's important to re-organise your layout like this when following the steps to reproduce. It will not work unless there is a tabbed layout window separate to the event sheet. So if you are having trouble reproducing this bug, check the screenshot for how I have laid everything out:

![ufxTnLy](https://user-images.githubusercontent.com/28833199/60008501-8ff6ab80-96b7-11e9-9403-0e5086f5258c.png)

If you still can't reproduce it, try changing your theme to the dark theme.

**Affected browsers/platforms:** Desktop

**First affected release:** r155

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r155 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 72 gb
Storage usage (approx): 1.8 gb (2.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I can reproduce this, but only in the dark theme, not the default theme.

**Comment by AshleyScirra** [comment]
This looks complicated. For some reason a stale bounding rect is cached deep in the UI library, but only when using the dark theme, despite all the JS code being the same.

**Comment by AshleyScirra** [comment]
OK, I tracked this down and should be fixed in the next build. Not sure why it only affects the dark theme but found where it needed to update the bounding rect.
