### ISSUE TITLE
Preview window will rewind itself back to small, after you max it.

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3072]
## Problem description
Bug when you preview project with weak pc, maximize preview screen and preview window will resize few ms later back to small or the default size it opened up.
Probably same race case issue which didn't scale viewport correctly after you change window size.
I can't record video on this laptop but i can reproduce it constantly, recording with 30fps misses the change and 60fps recordings lag. So thats that.

## Steps to reproduce

1.Hope to get lucky with correct timing click or find old laptop
2.Open kiwi example project
3.Click preview and when you see preview window click maximise pretty fast
4.Preview window goes max for few ms then rewinds back to small and moves to top-left corner!

## Observed result
Changing preview window sometimes show buggy behavior. Maximising window rewinds back to small and moves it top-left corner.

## Expected result
No preview rewinds back to small.
One could avoid it and click maximise after few seconds, ,but bug could manifest itself differently too, somehow that user could not detect so easily.

## More details

**Affected browsers/platforms:** 

**First affected release:** 
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.800000011920929
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
C3 release: r156 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 20 gb
Storage usage (approx): 1.6 gb (8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Mobility Radeon HD 5000 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SnipG** [comment]
I tried release 125 and possible race condition fix in 126 and they seems to be ok.
The window resizing to small and moves top-left corner is happening both of them, as could be chrome own issue after you exit from max screen.

So the automatic rewind back to small issue could started happening sometime between r126-156, possible when you added your own fix to correct viewport size. But i don't have time to test all thous releases atm.

Both of them seems to be connected, as it seems preview window might reguest its sizes midterm and it gets that small top left corner ones. and resizes to it. fixing one of the issues will lazy fix both.

**Comment by AshleyScirra** [comment]
If this only happens soon after the window opens, I think it is a conflict with our workaround to issue #2918. That requires us to manually resize the window a couple of times shortly after startup to try to get the correct popup window size. If we remove that, it will bring back the original issue. So I think we just need to wait for the underlying Chrome issue to be fixed and then remove our workaround.
