### ISSUE TITLE
Crash - Oops something went wrong when closing docked timeline window

### ISSUE THREAD

**Issue by justifun** [Scirra/Construct-3-bugs#3073]
Crash - Oops something went wrong when closing docked timeline window.

## Attach a .c3p

Attached scene is a new blank scene with the timeline window docked.

## Steps to reproduce

Dock the timeline window at the bottom and then press the X to close it.

## Observed result

Crash - Oops something went wrong error

## Expected result

close the timeline window successfully without crashing.

## More details
Error report information
Type: unhandled exception
File: https://editor.construct.net/r156/components/bars/timelineBar/timelineBar.js, line 1, col 6242
Message: Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
Stack: TypeError: Cannot read property 'getBoundingClientRect' of null at e (https://editor.construct.net/r156/components/bars/timelineBar/timelineBar.js:1:6242)
Construct 3 version: r156
URL: https://editor.construct.net/r156/
Date: Mon Jun 24 2019 12:39:23 GMT-0700 (Pacific Daylight Time)
Uptime: 10474.6 s

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r156 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, [WEBGL_lose_context](url
[TimelineWindowCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/3322311/TimelineWindowCrash.zip)

)

**Affected browsers/platforms:** 

c3 - r156

## System details
Tested on latest Chrome (installed as app) - windows 10

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
It's difficult to know if this is fixed. Will have to check the next beta release.

**Comment by AshleyScirra** [comment]
r158 is now out, please check again!
