### ISSUE TITLE
Unable to open the .c3p project (error message: invalid function name "function name")

### ISSUE THREAD

**Issue by agouibo** [Scirra/Construct-3-bugs#3074]
## Problem description

Cannot open C3 project. It stars with "opening" message and then gives an error message "invalid function name [function name]". Problem occurred after copying part of the code, which included function and it's call, from one project to another. Both projects had new redesigned functions, not the old ones. It's quite difficult to reproduce the situation, because i have only one copy of the project.

## Attach a .c3p

I will send the .c3p project file which i'm not able to open, and a picture of the code that i copied.

Project "A" that i'm not able to open: https://www.dropbox.com/s/ul88ktmj4oq5fum/Castle.c3p?dl=0
Part of the code that i copied from Project "B" to Project "A": https://www.dropbox.com/s/1wxgxank0mpbakb/function_code.png?dl=0

## Steps to reproduce

1. Copied the code from Project "B" to Project "A"
2. Saved Project "A"
3. Tried to open project "A"

## Observed result

Project was downloaded from Dropbox. Then it started opening and after that the error message was shown:
![invalid_function](https://user-images.githubusercontent.com/52178538/60051090-e1fcf880-96da-11e9-8699-56ce7b0e21ba.png)

## Expected result

Project should be opened normally.

## More details

**Affected browsers/platforms:** 
Chrome and Edge were tested. Dragging file from desktop to browser gives a different error message than downloading and opening it from Dropbox:
![opening_cp3_from_desktop](https://user-images.githubusercontent.com/52178538/60051355-7cf5d280-96db-11e9-89be-990248bd50cc.png)

**First affected release:** r148 stable

## System details

<details><summary>View details</summary>

Error log:
![image](https://user-images.githubusercontent.com/52178538/60051801-7d429d80-96dc-11e9-8206-ec07bd586706.png)

</details>

**Comment by AshleyScirra** [comment]
This is the same issue as #2996 and was already fixed in r152. As per the guidelines, please only report issues that reproduce in the latest beta release to avoid reporting issues we've already fixed. I assume you have a backup you can restore; if not let me know and I can restore the project.

**Comment by agouibo** [comment]
Hmm, i tried to open the project in the latest beta release r156, but it gives the same error.
It would be appreciated if You can restore the project.

**Comment by AshleyScirra** [comment]
Here's the recovered project: 
[Castle-recovered.zip](https://github.com/Scirra/Construct-3-bugs/files/3329534/Castle-recovered.zip)

**Comment by agouibo** [comment]
Thank You!
