### ISSUE TITLE
construct 3 crashes !!!

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#3075]
I have sended the project to support@construct.net as It was my personal project.The problem is pretty much simple:-the browser crashes !!!No report,nothing.Also the cpu runs at full throttle(thats does not happen even on playing a heavy game)
I have sended two files:-one works properly and another one blows the browser.Difference between them is line 18.In line 18 ,I just added:-"create object coin at...." and browser crashes
Also,all of my files from local browser are blown away.Now it seems that there was nothing called "local browser saves"
Atleast acknowledge the problem( I know it will take a lot of time to solve the problem !!!)

**Comment by layilpaht** [comment]
Voila !!! I discovered a new bug
Just after the above incident,I said that my local saves are destroyed.Usually construct 3 automatically saves my work in local browser every 10 minutes.Now every 10 minutes i get a message
![image](https://user-images.githubusercontent.com/46170077/60070712-3b921100-9735-11e9-85fa-ec33a81bbfee.png)
"key is not defined"
And when i look at my local browser saves,it says that "failed to refresh file list"
I just tried to upload a file in local browser and again i got that message:-key is not defined.Then i learned about this bug
Try to also solve this problem

**Comment by shortercode** [comment]
@layilpaht before you report a bug please read the [guidelines](https://github.com/Scirra/Construct-3-bugs/blob/master/README.md) and then complete the template.

> # Please only test the latest version of Construct 3
> To avoid reporting bugs we've already fixed, please only test the latest version of Construct 3, including the latest beta release.


> # Use the bug report template
> The bug submission page is pre-filled with a template. We need all this information to help you. Do not delete it. Please provide as much of the requested information as you can, including the system details or crash report information with every report.

This bug was fixed in beta 151 and hasn't reached a stable release yet. You haven't completed the system details so I cannot see what version your using, but by the URL in your screenshot I can tell it's one of the stable releases.
