### ISSUE TITLE
Bug in animation editor

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#3076]
This happened for the first time
Normally i used to edit my png images in animation editor in construct 3.Today i was editing the following image when i noticed an unusual problem.The color filler was not working properly
![rsz_1rsz_cursor_png11](https://user-images.githubusercontent.com/46170077/60074240-13f47600-9740-11e9-8fc3-331563d72e68.png)
like i wanted to fill the inside part with blue color.But when i am trying to do it,it is filling the whole image with that color.Following are the steps to replicate the bug
1.)open https://www.construct.net/en
2.)click on https://www.construct.net/en
3.)now click on new project.Size of screen does not matter
4.)now go to project window.Right click on object types and click "sprite"
5.)now open the sprite.Upload my image(arrow).
6.)now click on fill tool and select any color from left hand side.Try to fill it inside the arrow.The whole screen gets filled
7.)Now press ctrl+z to reverse the process.Now select eye dopper tool and carefully select the arrow's black part.Black color will be selected.Or alternately fill 0 value in red,blue and green parameter box.
8.)Now select the fill tool and try to fill it inside the arrow.Now arrow gets filled.
Try to solve the problem as soon as you can.Best of luck

**Comment by DiegoScirra** [comment]
I think this is a problem with the tolerance slider of the fill tool, it seems to not be working properly.

**Comment by layilpaht** [comment]
@AshleyScirra  just prove that I have not followed the guidelines.What did you more expected from me ??? I want to also learn

**Comment by AshleyScirra** [comment]
@layilpaht - you omitted many details that are often crucial, such as which C3 version you were using. This can make it more difficult and take longer to deal with the issue. Please always provide all the requested information.

**Comment by DiegoScirra** [comment]
The tolerance was not accounting for alpha properly, and that could cause the fill tool to just fill up the whole image under certain circumstances. That is fixed now, will be available in the next beta.
