### ISSUE TITLE
Debugger popup double objects issue [r156]

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3077]
## Problem description

When you click popup button in debugger it is show everything double.

## Attach a .c3p

Use any project with some objects.

## Steps to reproduce

Debug your project or click refresh and click popup button fastly. I was click popup button when loading didn't finish.
Look gif

![Bugg](https://user-images.githubusercontent.com/13033837/60078779-49e02d00-9735-11e9-8faa-eb3e25f2b733.gif)

Tested on only Chrome.

**Comment by AshleyScirra** [comment]
I could only reproduce by opening a popup, then closing it again. Then the double content appears back in the main window. This should be fixed in the next release.
