### ISSUE TITLE
Navigation bar is always visible on Android

### ISSUE THREAD

**Issue by RichardAstrom** [Scirra/Construct-3-bugs#3078]
The navigation bar is always visible in exported projects on Android so I don't get fullscreen anymore. I have tested with an exported debug .apk with "Scale outer" on a Nexus 5X with Android 8.1.0 and "Hide status bar" checked.

[Navigation_bar_visible.zip](https://github.com/Scirra/Construct-3-bugs/files/3324952/Navigation_bar_visible.zip)

1. Export the project as a debug apk.
2. Install it on a device.
3. The navigation bar is visible.

![IMG_8939](https://user-images.githubusercontent.com/3534495/60094533-a733a880-974c-11e9-8c53-f250bf1635ca.JPG)

## Observed result

The navigation bar is visible.

## Expected result

The navigation bar should be hidden.

## More details

Android 8.1.0.

r156

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
C3 release: r156 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 955 mb (6.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
You don't specify but I presume you ticked the "hide status bar" option on export?

**Comment by RichardAstrom** [comment]
Yes, "hide status bar" is checked! I forgot to mention that.

**Comment by shortercode** [comment]
Thanks for confirming.

I made some changes to how Android devices swap into fullscreen mode to work around a bug on some older devices, I expect that change is the one causing problems. I will take a look.

**Comment by RichardAstrom** [comment]
Great! I just tested on an old Nexus 7 tablet with Android 6.0.1 and the navigation bar is visible on that as well.

**Comment by shortercode** [comment]
Okay this should be resolved in the next release, which is our stable candidate.
