### ISSUE TITLE
Construct 3 - Importing Not Supported Files Crash

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#308]
## Problem description

Importing not supported files into Construct 3 just crashes the editor.
I would suggest additional checks in order to assure that users can only import supported files.
(Sounds, Music, Video, Fonts and Icons are affected.)
## Attach a .c3p

Download [HERE](https://cdn.discordapp.com/attachments/225550155531812865/315991400044822528/Bug_Report_-_Import.c3p)

## Steps to reproduce
1. Open the import dialog of sound, music, video, fonts or icons
2. Set the file selection to "any type of file"
3. Import an unsupported file (e.g. text file as music)
4. Notice crash after clicking on import

## Observed result

Construct 3 crashed when importing files which are not supported.

## Expected result

The importing dialog should mark unsupported files in red and tell users that the selected file cannot be imported, since it's not an audio; video; font or image file.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: te.ǃoA is not a function @ TypeError: te.ǃoA is not a function at ǃnO.ǃ_g (https://editor.construct.net/r29-2/main.js:71:35975) at h.ǃcF.then.g (https://editor.construct.net/r29-2/components/bars/projectBar/projectBar.js:1:31375) at 
Stack: TypeError: te.ǃoA is not a function at ǃnO.ǃ_g (https://editor.construct.net/r29-2/main.js:71:35975) at h.ǃcF.then.g (https://editor.construct.net/r29-2/components/bars/projectBar/projectBar.js:1:31375) at 
Construct 3 version: r29.2
URL: https://editor.construct.net/index.html
Date: Mon May 22 2017 01:14:24 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 131.1 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 670 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Okay has been fixed, a bit more work than I'd anticipated getting it actually show a warning but it's now all there. Should be available in the next release.
