### ISSUE TITLE
Dark theme Bug [r156]

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3081]
## Problem description

Look gif please. I tried with only Dark theme. I don't know about other themes.

1.) Background color change when I resize expression tab.
2.) I can't move little dialog when Expression tab opened.

System: Chrome 75, Windows 10

![Bug2](https://user-images.githubusercontent.com/13033837/60114149-e4fbf580-977b-11e9-90fc-971c736b517f.gif)

**Comment by AshleyScirra** [comment]
Can't reproduce here. Please always follow the guidelines to ensure we can help.

**Comment by QuasarX** [comment]
If you don't understand what you see, I can't help too.
¯\_(ツ)_/¯
