### ISSUE TITLE
Touch on Android Chrome being treated as Mouse?

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#3082]
## Problem description

My game detects a change between Touch input, Keyboard Mouse Input and Gamepad input and then changes the control code used automatically to suit. 

Testing on android recently the control was totally broken where it worked previously.

It seems some time recently there has been a change where touch input is now also regarded as mouse input. and also slow taps (just less than 1 second apart each) in the same place are regarded as a mouse click.

So my game control is now broken as is unable to differentiate between Touch and Mouse defaulting to mouse when using touch on android device.  (I will test windows device tomorrow and update but I think this is specific to android)

## Attach a .c3p
[Touch is Mouse.zip](https://github.com/Scirra/Construct-3-bugs/files/3327081/Touch.is.Mouse.zip)

## Steps to reproduce
run the attached c3p on android and see that ....

## Observed result

touch is being registered as mouse input.

## Expected result

touch to be registered as touch and mouse as mouse

## More details

This is on android chrome only  (not tested apk, just browser)

## System details

android phone (android 8.1) only tested
construct 3 r156

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
This was a change in r155 

> Updated runtime to use Pointer Events API for mouse input

Assigning to @AshleyScirra to review if this was the intention when that change was made.

**Comment by AshleyScirra** [comment]
Ah yes, our switch to pointer events accidentally made Mouse start responding to touch input. Well spotted, fixed for next release.
