### ISSUE TITLE
Window says "Global Variable" when it's actually a "Local Variable"

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#3084]
I selected a sub event, pressed the secret shortcut 'V' to make a local variable, it then popped up with the create/edit variable window which is good but the title was wrong! It made me confused because I wasn't wanting to make a global variable, but a local variable. 

But it turns out that it still does make the variable perfectly, the title is just a deceptive typo.

![image](https://user-images.githubusercontent.com/5744908/60233066-2d352800-98e2-11e9-933d-d60e1928b843.png)

**Comment by shortercode** [comment]
Nice spot, looks like a simple typo so I'll grab this.

**Comment by shortercode** [comment]
Ah looks like ashley beat me to it!

**Comment by AshleyScirra** [comment]
Fixed for next release (will make stable since change is trivial)
