### ISSUE TITLE
404 error on startup 156.2

### ISSUE THREAD

**Issue by Fengist** [Scirra/Construct-3-bugs#3086]
## Problem description
Console error when starting C3 from pwa.

Registered root service worker on https://editor.construct.net/
main.js:159 Registered service worker on https://editor.construct.net/r156-2/
/startPageMessage/st…=en-US&theme=dark:1 Failed to load resource: the server responded with a status of 404 ()
startPage.js:1 [Start page] Failed to retrieve message banner status:  Error: error fetching https://editor.construct.net/startPageMessage/status.json?c3release=r156.2&uimode=desktop&userId=221567&lang=en-US&theme=dark (404 )
    at n (main.js:2)
    at async window.ǃ$LJ.ǃ$NT (startPage.js:1)
ǃ$NT	@	startPage.js:1
preview.construct.ne…l/bootPreview.js:35 Registered service worker on https://preview.construct.net/local/
root-sw.js:273 [Root-SW-Offline] Up to date

**Comment by AshleyScirra** [comment]
This has no effect and is currently part of an intentional change we're still designing.
