### ISSUE TITLE
Can't Detect Online [r156-2]

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3087]
## Problem description

I can't detect ConnectionType on mobile and PC. I'm using Ethernet connection on PC, it is return me "unknown". Also I tried it with Android phone still same result.

**PC Preview:**
ConnectionEffectiveType: 4G
ConnectionType: unknown

**Android Preview:**
ConnectionEffectiveType: 4G
ConnectionType: unknown

if I change my connection this event don't detecting.

+ PlatformInfo: On network change
-> SpriteFont: Set text to "ConnectionEffectiveType: " & PlatformInfo.ConnectionEffectiveType & newline & "ConnectionType: " & PlatformInfo.ConnectionType

--------------------------------------------------------------------
+ Browser: Is online
Return me every time "Online" on Android.

## Attach a .c3p

[TestNetwork.zip](https://github.com/Scirra/Construct-3-bugs/files/3335063/TestNetwork.zip)

**Affected browsers/platforms:** Chrome, Android
Chrome v75
Android 5.0.2

**Comment by AshleyScirra** [comment]
ConnectionType just returns `navigator.connection.type`, which [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/type) is currently only supported in Chrome on Android and Chrome OS. I checked on a Pixel 3 and it does appear to work there since it returned "wifi". "unknown" is a valid thing for the expression to return if it otherwise can't be detected so that is not in itself a bug.

I also checked the online/offline status and it was working on Android. Again we just forward what the browser tells us. So basically in both cases it depends solely on browser support.

**Comment by QuasarX** [comment]
I do another test. Just added Googleplay plugin in project and do debug.apk
When I install this apk it is show me this permission.

`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>`
 
**This time PlatformInfo plugin works perfectly**. But **Browser didn't detect** when you change connection on/off.

**Steps to reproduce.**
1.) Make debug apk with this example and add Googleplay plugin. Do debug.apk
2.) Install on phone, you will see it is show you access internet state.
3.) Close network connection.
4.) Open app, I get this results;

```
ConnectionEffectiveType: 4G
ConnectionType: none
```
```Offline```

5.) Open network connection. I used wifi connection. I get this results:

```
ConnectionEffectiveType: 4G
ConnectionType: wifi
```
```Offline```

Why browser plugin doesn't detect? It must show "online".
It is not run every tick?

![image](https://user-images.githubusercontent.com/13033837/60279884-8e70f180-990a-11e9-94f8-f2e70d197ac6.png)

**Comment by AshleyScirra** [comment]
It's based solely on what the browser status is, so I think it just depends on the support between Android and Chrome.

**Comment by QuasarX** [comment]
I'm still thinking it is permission issue. You can try with Android 5 device. Application if doesn't have that permission it can't access that values. Thats why it is return me everytime unknown, when I don't add Googleplay plugin. It is just add permission in AndroidManifiest file.
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

**Comment by QuasarX** [comment]
> It's based solely on what the browser status is, so I think it just depends on the support between Android and Chrome.

How can I show you Browser plugin totally not work with Construct 3 C3Runtime.

Okay. Last time I show you.

I just used Construct 2 with **Browser** plugin. And It is works. How ?? **Same phone but I used this time Construct 2. So, do you still think it is not a bug?**
@AshleyScirra 

[testC2.zip](https://github.com/Scirra/Construct-3-bugs/files/3335783/testC2.zip)

1.) Used this example and do export.
2.) edit config.xml and add this for android permission request.

```
	<plugin name="construct-play-games" >
		<variable name="APP_ID" value="111111111111" />
	</plugin>
```
3.) Change your phones network state. It will show you Online or Offline every time.

Can you explain it is not a bug? Than why Construct 2 exported apk works on same phone?

**Comment by QuasarX** [comment]
@AshleyScirra 
I don't want make new bug report. Just look up, I posted new project.
Just tell me what is wrong? We are try to tell you what is a problem but you don't want fix.

I'm talking about **Browser** plugin.

When I use C3 C2Runtime apk, it is works.
When I use C3 **C3Runtime** apk, **it is not work.**

Just tell me how it is not a bug?

**Comment by simonpaulkeating** [comment]
I have the same issue on device. IsBrowserOnline does not work and there doesn't seem to be a way to check for network connection on device.

**Comment by AshleyScirra** [comment]
There's probably no point checking if you're online anyway. Just go ahead and do whatever networking you need to do, and if that fails, you're probably offline. Detecting "is online" is tricky since it's hard to class intermittent connections, and may result in situations like telling the user they're offline when it would actually work.
