### ISSUE TITLE
Construct 3 - Tilemap Property Crash

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#309]
## Problem description

Construct 3 crashes when clicking on the "initially visible" tilemap property.
(Maybe because it's a checkbox now, compatibility issue?)

## Attach a .c3p

Download [HERE](https://cdn.discordapp.com/attachments/225550155531812865/315994632754429952/Bug_Report_-_Tilemap.c3p)

## Steps to reproduce

1. Open c3p file
2. Click on the tilemap object
3. Click on the "initially visible" property

## Observed result

Construct 3 crashes as soon as you click on the mentioned property.

## Expected result

Construct 3 shouldn't crash while doing that.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r29-2/plugins/tilemap/plugin.js, line 1, col 6661
Message: Uncaught Error: invalid property name
Stack: Error: invalid property name at c.ǃCL.ǃC$ (https://editor.construct.net/r29-2/plugins/tilemap/plugin.js:1:6667) at ne.ǃJz (https://editor.construct.net/r29-2/main.js:61:207751) at s.ǃTQ (https://editor.construct.net/r29-2/components/bars/propertiesBar/propertiesBar.js:1:28572) at ǃC.ǃl.ǃb.ǃ_K.ǃCtw (https://editor.construct.net/r29-2/main.js:2:478024) at ǃC.ǃl.ǃb.ǃCGe.ǃCtQ (https://editor.construct.net/r29-2/main.js:2:464414) at ǃC.ǃl.ǃb.ǃCGe.ǃGO (https://editor.construct.net/r29-2/main.js:2:464667) at HTMLInputElement.ǃCFx (https://editor.construct.net/r29-2/main.js:2:463256)
Construct 3 version: r29.2
URL: https://editor.construct.net/index.html
Date: Mon May 22 2017 01:32:23 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 248.7 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 670 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r31.
