### ISSUE TITLE
Remote Preview on iOS does not work with Physics behavior in beta 156-2.

### ISSUE THREAD

**Issue by SloRey** [Scirra/Construct-3-bugs#3092]
## Problem description
Remote Preview for iOS does not work with Physics behavior in beta 156-2.
Stuck at loading/splash screen.

Works fine in beta 153 and earlier.
Works on Chrome and Firefox on Windows, see: https://github.com/Scirra/Construct-3-bugs/issues/3060

## Attach a .c3p

[PhysicsRemotePreview154.zip](https://github.com/Scirra/Construct-3-bugs/files/3308738/PhysicsRemotePreview154.zip)

## Steps to reproduce

1. Open attached c3p in beta 156-2 or create a new project and add a sprite/object with physics behavior.
2. Preview through Remote Preview, open via iOS.
3. Redo step 1 and 2 in beta 153.

## Observed result

Stuck at splash screen/ loading screen for beta 156-2 but fine in beta 153.

## Expected result

Beta 156-2 to load like beta 153.

## More details

**Affected browsers/platforms:** 
Safari (iOS)

**First affected release:** 

Beta 156-2.

## System details

<details><summary>View details</summary>

</details>

**Comment by SloRey** [comment]
Chrome on Windows is working fine, iOS is still having trouble. Opens fine with older version of C3.
See: https://github.com/Scirra/Construct-3-bugs/issues/3060

**Comment by AshleyScirra** [comment]
It works fine for me if I clear Safari's cache. We made a server-side update around then so I think it just needs a refresh to get working.
