### ISSUE TITLE
Android Phonegap DevApp Issue with C3Runtime

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3093]
## Problem description

I was using PhoneGap DevApp for previewing game. This way saving time. No need build apk, just using exported project with Phonegap's Wifi preview. It is works with Construct2 but C3Runtime have some problems.

![image](https://user-images.githubusercontent.com/13033837/60384367-7c678e00-9a85-11e9-8c0f-5927effdf7c8.png)

## Attach a .c3p
If you want make PhonegapDevApp for Android you can use this cordova project
[PhonegapDevApp v1.3 -  CordovaCLI.zip](https://github.com/Scirra/Construct-3-bugs/files/3341870/PhonegapDevApp.v1.3.-.CordovaCLI.zip)

If you don't want, I made for you. You can use this apk for Android
[DevAppApk.zip](https://github.com/Scirra/Construct-3-bugs/files/3341872/DevAppApk.zip)

## Steps to reproduce

Before you need setup something.

1. Download and install this Desktop App
https://phonegap.com/products/#desktop-app-section

2. Create blank example using Desktop App
![image](https://user-images.githubusercontent.com/13033837/60384204-a6b84c00-9a83-11e9-9bff-6f8325e89b58.png)

3. Choose "Hello World", select path folder and write any project name.
![image](https://user-images.githubusercontent.com/13033837/60384222-e2531600-9a83-11e9-9765-b8da653f554a.png)

4. Wait a bit and stop server using this button
![image](https://user-images.githubusercontent.com/13033837/60384244-20e8d080-9a84-11e9-8480-009bd93b46b9.png)

5.) Go your project folder and delete "www" folder. Mine is (_C:\Users\X\Desktop\GAME\HelloWorld_)

6.) Create any example and export as "Cordova project" using C3Runtime.

7.) Copy exported project's "www" folder and put your Desktop App's area.
Like this;
![image](https://user-images.githubusercontent.com/13033837/60384295-9b195500-9a84-11e9-8046-c03cf41ba25c.png)

8.) Start Preview on Desktop App with this button
![image](https://user-images.githubusercontent.com/13033837/60384352-45917800-9a85-11e9-85e0-e7d29d12d05f.png)

9.) Open your wifi on phone and open DevApp on phone

10.) Write this on your phone and click "Connect" button.
![image](https://user-images.githubusercontent.com/13033837/60384319-d61b8880-9a84-11e9-8e9b-b2d27937fa73.png)

11.) Open this in chrome "chrome://inspect/#devices"
You will see error.
![image](https://user-images.githubusercontent.com/13033837/60384359-68bc2780-9a85-11e9-86b3-3420a98234f5.png)

## Observed result

It should work like C2 runtime works.

## Expected result

Can't open any C3 project

## More details

**Affected browsers/platforms:** Android (Idk about IOS)

**First affected release:** Tried with r156-2

**Comment by shortercode** [comment]
If memory serves the C3 runtime uses the file plugin to read some of the application assets due to a security restriction on Android devices, we already used a similar technique to work around something on iOS. It's not an ideal situation but it works for normal builds.

I'm guessing what is happening here is that the DevApp is viewing the app over the webserver, and hence it doesn't have any of the assets locally. The errorcode your getting is NOT_FOUND_ERR, so we're trying to read a required asset from the archive but it doesn't exist ( it's only on the server ).

**Comment by AshleyScirra** [comment]
Your steps to reproduce won't work because you don't copy the configuration file (config.xml), so as written the app will run with the wrong config.

I just tried this and @shortercode is basically right - we use cordova-plugin-file to read local files on Android, but it looks like this doesn't work correctly in the DevApp. It looks like they're falling back to Chrome's file system API (which is nonstandard IIRC) and is completely sandboxed from all other storage so cannot read other files in the bundle. You'll need to report this to them instead.

In general if something works on a real device but doesn't work in a test app, it's a problem with the test app. It's the job of the test app to work like a real device.

**Comment by QuasarX** [comment]
> Your steps to reproduce won't work because you don't copy the configuration file (config.xml), so as written the app will run with the wrong config.

you did not understand this part. Just use empty project. If u add something Google play plugin or IAP or ADS this needs cordova dependencies. So you need add that plugins only in DevApp.apk not your exported project.

And you didn't answer why it is works with C2?
Ohh nvm totally my fault. I'm trying to explain something to you, when you don't understand all.....

**Comment by shortercode** [comment]
@QuasarX see my explanation about the file plugin. The C2Runtime doesn't depend on the file plugin, so it won't have this issue.

**Comment by QuasarX** [comment]
I report this issue to Phonegap. I hope they will do something. Just want to say.
Something really hard with new Construct 3. Everything really good with C2 but C3 everytime give us problem..
Anyway thanks for answers @shortercode

**Comment by shortercode** [comment]
While there's a few edge cases with the C3 runtime I think most of this is down to the C2 runtime being older. It's had more time for people to find bugs, and for us to fix things.

Also by having 2 runtimes supported we often have to implement fixes/features for both. The runtimes are quite different internally, so we have to write 2 different patches. This explains why sometimes things behave slightly differently, or there's a bug in one of them but not the other.

**Comment by QuasarX** [comment]
I was look something for crypt resources for Construct games. I found this
https://github.com/tkyaji/cordova-plugin-crypt-file
This was work with C2. But Construct 3 really hard to edit something to works like C2.

> Also by having 2 runtimes supported we often have to implement fixes/features for both. 
I agree. It is hard. So you only focus C3 at this time. And we don't have any alternative with C3.

Also someone request this idea for C3
https://construct3.ideas.aha.io/ideas/C3-I-882

I found way to add custom cordova plugins for DevApp and it was works with C2.
Just want to say, we need something for easy development. If we don't have any alternative we can't do things faster.
**So this time I need every time:** Export, build, install, test...

**Comment by AshleyScirra** [comment]
> > Your steps to reproduce won't work because you don't copy the configuration file (config.xml), so as written the app will run with the wrong config.
>
> you did not understand this part. Just use empty project.

No, you've misunderstood: Construct projects won't work unless you use the config.xml file generated by Construct. Your steps did not include using this file and instead only used the default, which guarantees the project won't work.

**Comment by QuasarX** [comment]
DevApp alredy using default C3's cordova plugins. So don't need do anything with config.xml

And this steps will work perfectly if you use Construct 2.
You break something with C3 and saying it is DevApp's fault. Good developer 👍

**Comment by AshleyScirra** [comment]
It's not our software so it's not our responsibility to fix it. Please take up such issues with the developers. I don't believe there's any particular reason to use the DevApp anyway since most users test on real devices or simulators, or just click Preview in C3.
