### ISSUE TITLE
JSON plugin - Unable to add object to array element.

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#3095]
## Problem description

JSON plugin - Unable to add object to array element. Using the push only works with a value, not an object. When using the Set object action, the 'path' does not allow for JSON array addressing (For example - My.Path.Array[0])

## Attach a .c3p

[JSONArrayPath.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3343627/JSONArrayPath.c3p.zip)

Remove *.zip

## Steps to reproduce

Run project, see output log on screen.

## Observed result

Instead of adding an object at the path in the array, a new key is created and object created there.

## Expected result

An object to be created at the index of the array in the path.

## More details

Any method is OK (e.g. push object into array, or set JSON with an array path, etc.)

My current workaround is to 'manually' create a JSON array of objects string and then do set JSON at the path I want the array of objects. Ok, but not too clean.

**Affected browsers/platforms:** 

All

## System details

Mac OSX

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
The path syntax is wrong. `array[0]` is not valid, use `array.0` instead. See the section on arrays in the [JSON plugin manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/json).

**Comment by MikalDev** [comment]
@AshleyScirra thanks for the pointer. I read the manual entry while working on this and somehow missed the separate section on Arrays! Sorry for the false report, but thanks for the help.
