### ISSUE TITLE
Click Save button in Animation Editor force Project to close on iPad

### ISSUE THREAD

**Issue by Parwitch** [Scirra/Construct-3-bugs#3096]
## Problem description
On iPad, when clicking save button in Animation Editor. It pop up new window (blob:) after swipe back to project it force-close the project.

## Steps to reproduce

1. double click on any existing sprite object
2. click save button from Animation Editor
3. New pop up window named blob: appear. It is a white blank full screen window with edited sprite on it
4. Swipe from the left edge to go back to main page
5. Close Animation Editor (or wait a few seconds and the Animation Editor will close itself)
6. The main page show buy now tab, account log out, all project tabs that I opened are disappeared.

## Observed result
After Animation Editor close, even I have many event sheet open, I was force to "Buy now" tab with my account log out and all project tab were closed. (in other word, Construct 3 was reset to the initial stage.)

## Expected result

Sprite is saved. I should be able to close the Animation Editor and go back to work on event sheet or layout sheet

## More details

**Affected browsers/platforms:** 
Chrome-iPad, Safari-iPad

**First affected release:** 
r148
## System details
iPad Pro 9.7-inch

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 12.1.1
Browser engine: WebKit
Browser architecture: (unknown)
Context: webapp
Operating system: iOS
Operating system version: 12.3_1
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/604.1
C3 release: r148 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by AshleyScirra** [comment]
It looks like a general problem with the download mechanism in Safari - it also happens if you save the project as a download.

Safari has buggy "download" attribute support and we already have hacks to try to make it work, but these don't seem to be effective. It looks like it's working in Safari 13 though, so it should be fixed once that update rolls out.
