### ISSUE TITLE
HTML export: "icons" folder can cause problems

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3097]
Under certain conditions the "icons" folder in the HTML export can cause troubles, ending up not beeing able to be accessed. Renaming it to anything (e.g. iconss) will work just fine. Also all other folders (images, scripts,...) work fine.

References
https://ubuntuforums.org/showthread.php?t=2114496
https://loess.ru/apache2-siteicons-directory-forbidden/

I checked .htaccess and whatnot, but this cannot be overridden (unless changing the apache settings directly)

🍰 If you want to take a look yourself I´ll email you the link. I don´t wanna go public with it just yet.

## Steps to reproduce

1. I used multidomain to point to a subdirectory of my server
2. Uploaded app to said subdirectory

## Observed result

These errors for all icon files.
sw.js:1 [SW] Error fetching 'https://........./icons/icon-16.png' (404 Not Found)

This further seems to cause the app update not to be completed properly, causing "on update found" to trigger everytime.

## Expected result

To find the icons

## More details

This is the error I get when just going to the directory itself

> Forbidden
> You don't have permission to access /icons/ on this server.

**Affected browsers/platforms:** 

**First affected release:** 
I mean this must have been like this since forever :V

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 660 mb (2.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks like this only happens on Apache-based servers, serving from the root of the origin, and you can change the server configuration to work around it by editing `alias.conf`. This seems too niche to have to rename the icons folder to something non-obvious and appears to be easy to solve, so closing as wontfix.

**Comment by Wackytoaster** [comment]
I don´t think it´s entirely true to be easy to work around. Changing some line is one thing, but this isn´t a dedicated server, it´s shared hosting (That I´d assume is true for most users). I don´t have access to the config files. Well, I´ll ask my provider if they could give me access, but that´s not a guarantee.

For now I´ll just rename it by hand, not exactly the best solution but it works.

**Comment by Wackytoaster** [comment]
As expected, my hosting provider cannot allow such changes on shared hosting as it would globally impact any user on that server. Obviously I didn´t want to go ahead and rename all that stuff by hand all the time so I came up with this solution:

1. Download FART (yes FART) https://sourceforge.net/projects/fart-it/
2. create a batch file
`rem rename icons because apache doesn´t like that name
ren ".\exportedProject\icons" epicIcons

rem update references to icons folder
fart.exe -r ".\exportedProject\*" "icons/" "epicIcons/"`

3. Drop your exported project into the folder and doubleclick the bat. Done. Obviously you can change epicIcons with anything you like.

Actually I made the file to do some more adjustments that I needed, so all in all I can´t complain :) But I´d still argue that a change should at least be considered. Actually I´m surprised that it never really came up before. @AshleyScirra

**Comment by AshleyScirra** [comment]
It also looks like you can work around it by just serving from a subfolder, since the "icons" alias only appears to affect the root origin.
