### ISSUE TITLE
Tilemaps BAAAD!

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#3099]
## Problem description

Tilemaps seem to increase memory use in Construct 3 in layouts that aren't even open.

## Attach a .c3p

[https://drive.google.com/open?id=1dUaWqB2h8TRiQyArPCK0i_3ocscHTL6J](https://drive.google.com/open?id=1dUaWqB2h8TRiQyArPCK0i_3ocscHTL6J)

## Steps to reproduce

1. Press F12 and look at the memory use in the debugger. Preferably desktop C3 as I'm sure that will be easiest to check.

## Observed result

Even though my actual project doesn't use any tilemaps this big and I don't even know if this is why mine is going crazy with memory use to begin with, but it still holds true that the memory use is affected by tilemaps in layouts not even open.

## Expected result

I'm not a C3 developer so maybe this is something that needs to happen, but I expected tilemaps would not use memory unless their layout was open.

## More details
**Affected browsers/platforms:** Chrome, Firefox, Desktop C3 are what I tested, probably any others are impacted too.

**First affected release:** r157

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 101 gb
Storage usage (approx): 1.1 gb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Construct has to keep your project in memory. The tilemap has 8 million tiles, which is an extreme case, and they have to be in memory somewhere, which is why they use up memory. Given it's an extreme case and the unavoidable fact your project has to be in memory, I don't think this counts as a bug.
