### ISSUE TITLE
Touch Input (C3 Desktop Version)

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#31]
## Problem description

Touch input in Layout View (Desktop Version) is not working as expected. As touch enabled desktop computers/laptops/tablet hybrids are becoming more common it's good if this worked properly. I'm working on a Surface Pro 4, for example.
For reference try google maps webpage on a touch capable device. 

## Attach a .c3p

Not applicable

## Steps to reproduce

1. Create New Project
2. Add New Sprite
3. Try manipulate sprite handles with touch input. Rotate, scale, move. (Not working) It just de-selects the sprite.
4. Try zooming and scrolling using 2 finger input. (Not working) Layout is jumping around. 
5. Try selecting using select rectangle (Touch and drag rectangle) This scrolls the layout view and draws selection rectangle.

## Observed result

Touch is not working as expected in Layout view.

## Expected result

Touch should be working for manipulating objects, zooming, and scrolling.

## Affected browsers

* Chrome: **yes**/no

## Suggested Input

* Pinch should zoom.
* Two finger input should scroll.
* 1 finger input drag should draw the selection rectangle.
* Touching Sprite handles should rotate, scale and move the sprite. (It would be good to add a visable icon for rotate handle)

**Comment by tunepunk** [comment]
Any update on this issue? It would be awesome if this was resolved before the newgrounds jam, so I can design try to complete my jam entry in the hammock, instead of at a desk ;)

**Comment by AshleyScirra** [comment]
We're aware of it, we have lots of issues and other things going on though. I'll try to look in to it soon.

**Comment by AshleyScirra** [comment]
In r37 I've allowed support for using resize and rotate handles via a touchscreen. Other than that I can't see anything wrong with using a touchscreen (I used a Windows 10 laptop with touch-sensitive screen). Everything else seems to work OK. We made some tweaks aimed at mobile systems which may have helped for desktop touch input as well. So I'm going to close this now, but please file a new issue from r37+ if you still have issues.
