### ISSUE TITLE
C3 Image editor does not works like C2 Image editor

### ISSUE THREAD

**Issue by yojona** [Scirra/Construct-3-bugs#310]
## Problem description

Is hard to work with C3 image editor when we have our way to work, "shortcuts" or features in c2.

## Expected results

* Painting with transparent color works like eraser
* Ctrl+click, copy selected color in image
* keeping primary and secondary color in editor when open another image

Also, I think the color palette should always be the same, 'cause usually we make a color palette to work in whole project. But the swatches are different for each image en c3.

**Comment by DiegoScirra** [comment]
2) Is an oversight and will work on it.
3) Will be working on this one as well as it has been mentioned by another user and I think it makes sense.

1) Will not be working on this. Painting with a transparent color is not the same as erasing.

**Comment by AshleyScirra** [comment]
@DiegoScirra - I think C2 did deliberately treat a completely transparent brush the same as an eraser - trying to draw transparency is useless anyway so it's a handy shortcut to an eraser. I think C3 should match the same way C2 works on this point.

**Comment by mOOnpunk** [comment]
@DiegoScirra  you closed my bug report 754, but the issue wasnt just with transparency not being treated as an erazer, but more that at max hardness the "edge" of the brush is still soft, like an opacity gradient, when it should be clean. The pixel edge should go from 1 fully transparent pixel to 1 fully opaque pixel. I hope you understand the issue fully. Thanks.

**Comment by mOOnpunk** [comment]
@AshleyScirra @DiegoScirra 

Can we please have an ETA on when this and the hardness issue is going to be fixed?

Both bugs combined to make a big issue. If i draw some pixel art and need to delete some pixels i cant set colour to transparent and use pencil tool or paint bucket because alpha does nothing, and cant use the erazer tool because its max hardness has soft edges.

**Comment by mOOnpunk** [comment]
Can you please fix these for the next build? As i say the problems combine and currently there is not solution around the problem.

**Comment by yojona** [comment]
I hope you guys add th  transparent color eraser soon, actually is the only thing that stops me to pay my suscription, (I love C3, but I make my pixel art sprites in C2 Editor, and there is no sense pay for something that I wont use), I understand that has a lower priority but the UX is important too.

**Comment by mOOnpunk** [comment]
Any news on transparency and soft edge problems being fixed? These issues are going on a really long time.

**Comment by AshleyScirra** [comment]
I think @DiegoScirra is currently working on drawing with transparency working as eraser.

**Comment by mOOnpunk** [comment]
Thats good. What about issue 754?

**Comment by DiegoScirra** [comment]
Added in r80.

Now I will sort out the hardness problem. I have it on the private bug tracker, so I am closing this one.

**Comment by AshleyScirra** [comment]
@DiegoScirra - might be worth moving that to the public tracker so people can follow it.
