### ISSUE TITLE
"Start ignoring input" not working as expected

### ISSUE THREAD

**Issue by dchartfield** [Scirra/Construct-3-bugs#3100]
#2630  Problem description

The Platformer behavior's "Start ignoring input" action will cause subsequent calls to the "Simulate control" action to be ignored. However, I would expect Simulated controls to still work and only user input to be disabled.

## Attach a .c3p

[test-ignoring-input-and-simulate.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3346773/test-ignoring-input-and-simulate.c3p.zip)

## Steps to reproduce

Look at the attached c3p file. The character box should be moving to the right due to Event 2 Action 1 that executes "Simulate press right" on every tick. If you disable Event 1 Action 4 "Start ignoring Input" and re-run then the simulated control of moving to the right will happen.

## Observed result

Setting the Platformer Behavior's action "Start ignoring Input" disables subsequent calls to "Simulate control"

## Expected result

Setting the Platformer Behavior's action "Start ignoring Input" should still allow calls to "Simulate control" to work. 

## More details
I expect "Start ignoring Input" to work the same way as turning "Default controls" off. In this scenario, the only instance of the sprite with Platformer behavior is created at run-time so "Default controls" cannot be used.

**Affected browsers/platforms:** 
Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's working as designed. I think arguably it's incorrect to expect "Simulate control" to work while input is ignored, since it ignores all types of input, not just certain types of input. A bigger problem is this is a backwards incompatible change and would break existing projects that expect it to work as it does.

It doesn't seem to matter anyway - simply disable "default controls" and then the only thing that controls the behavior are the "simulate control" actions, which you have full control over in events.

**Comment by dchartfield** [comment]
> It doesn't seem to matter anyway - simply disable "default controls" and then the only thing that controls the behavior are the "simulate control" actions, which you have full control over in events.

We don't have access to this if there are no instances on the layout at startup. I assumed that "Start ignoring input" was way to control this from actions. If not then there is no way to disable "default controls" for an object that does not exist on initial layout?

**Comment by dchartfield** [comment]
For others who arrive here looking for the ability to enable/disable "Default Controls" on the Platformer behavior by action: please upvote this suggestion to have this important feature added: https://construct3.ideas.aha.io/ideas/C3-I-980

**Comment by AshleyScirra** [comment]
You could also:

1. Place an instance on the layout and destroy it on startup
2. Place an instance on a layout that is never loaded

**Comment by dchartfield** [comment]
For future reference the Construct team has added an Action to enable/disable "Default Controls" currently in r159.
https://www.construct.net/en/make-games/releases/beta/r159

Tested this out myself and it is working great. I really appreciate the Construct team jumping on this functionality, and the progress that has been made recently really proves Construct to be a mature gaming solution.
