### ISSUE TITLE
Issue with resolution when C2 game is exported to iPhone X through C3's export manager

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#3101]
## Problem description

When a game is optimized for iPhoneX, with resolution 2+/1 instead of 16/9, when exported with C3's export manager and previewed in the simulator, the game doesn't use the full screen on iPhone X.

To be more understandable, here is my game optimized for iPhone X on desktop (editor preview):
![iphoneX_bug2](https://user-images.githubusercontent.com/29117306/60462243-10ce1e00-9c49-11e9-8785-da1c7852398b.jpg)

and here is the result in the simulator:
![iphoneX_bugb](https://user-images.githubusercontent.com/29117306/60462406-7b7f5980-9c49-11e9-832e-4be53a2c8aea.jpg)

As you can see a large part of the background is missing, and large black borders are present.

[EDIT]
I also tried on a 2/1 resolution Android device, and it works fine. Problem only arise on iPhoneX.
![66224427_512005106211040_7243298109449568256_n](https://user-images.githubusercontent.com/29117306/60494214-9fc15180-9cae-11e9-9c37-e67eb5aac1af.jpg)

This is a very big deal as I cannot pretend to an Apple featuring if my game isn't correctly optimized for iphone X. I just passed 2 weeks to optimize the full game and had the nasty surprise that it's not working. :-/

For the information, I'm using a 1663x768 window, with scale inner, so that it's working on older (16/9) iPhones too.

Please note this problem seems strangely similar to this one: https://github.com/Scirra/Construct-3-bugs/issues/2779

Looks like there is a serious trouble with the iPhone X resolution.

## Attach a .c3p

I cannot attach the full game here, but I can send it by email if you wish. Just contact me at rablogames@gmail.com

## Steps to reproduce

1. Create a project optimized for iPhoneX (2,436 x 1,125 pixels resolution) in Construct 2
2. Set fullscreen scaling to Scale inner, so that it also works on older iPhones.
3. Export the project with Cordova and  then for iOS using C3's export manager
4. Open the project in Xcode on a Mac and run the simulator

## Observed result

There are black bars on the border of the game instead of the game.

## Expected result

The game should be displayed in the same way than in the preview of the editor, without black bars on the side.

## More details

**Affected browsers/platforms:** Chrome / C3 desktop build

**First affected release:** 
C2 r269
C3 r156.2

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 22 gb
Storage usage (approx): 1.6 gb (7.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I'd say this is technically a C2 bug, as the build service doesn't really apply any modifications to C2 projects.

We've recently patched the behaviour on iOS devices to resolve this in C3. But of course this hasn't affected exports from C2. It might be that we can resolve this by getting C3 to patch the build as it passes through. It's something I've considered in the past if something like this came up, but the changes we can make at that point are quite limited. I will check out how feasible it would be for this issues and report back here. If it's completely infeasible it will have to go on the C2 buglist.

**Comment by RabloGames** [comment]
Thanks for your help. Looking forward to learn more.

**Comment by shortercode** [comment]
Okay so my plan worked out fairly well I think. Once the next release goes out newly imported C2 projects in the export manager are patched to include several fullscreen layout fixes for iOS and Android which haven't been backported to construct 2.
