### ISSUE TITLE
MobileAdvert plugin crashes on Android mobile

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#3102]
## Problem description

MobileAdvert plugin causes Android apk to crash on launch.

## Attach a .c3p

https://www.dropbox.com/s/ch98scnaw14yhfe/test-apk.c3p?dl=0
Template project with added MobileAdvert plugin.

## Steps to reproduce

1. Build debug apk
2. Install on a phone
3. Run

## Observed result

App crashes.

## Expected result

App shouldn't crash.

## More details

Happens in r157, was working in previous versions.
Tried building for Android 5.0+ and 8.0+, tested on several phones.

**First affected release:** r157

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 144 mb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by Bioded** [comment]
Hello, have same problem!

**Comment by QuasarX** [comment]
You're using wrong App ID
You need find your **App ID in Admob Dashboard.**

Like this;
Sample AdMob App ID: `ca-app-pub-3940256099942544~3347511713`

**Help Page:** https://support.google.com/admob/answer/7356431?hl=en

**Forum thread:** https://www.construct.net/en/forum/construct-3/how-do-i-8/breaking-change-mobile-advert-145087

**Comment by dop2000** [comment]
@QuasarX , Thank you so much! This indeed has fixed the issue!

**Comment by shortercode** [comment]
I'll update the thread with the example app ID, hopefully make it clearer for other people.

**Comment by dop2000** [comment]
@shortercode , I didn't see your thread, unfortunately. In the future, could you please include information about critical changes like this into the release notes?

**Comment by shortercode** [comment]
In hindsight I would have definitely included the information in the release notes. But it wasn't immediately obvious to me how much of a problem it was going to be. My mistake.

We have updated the build server to produce a specific warning which includes the forum post URL. But it only checks if the value has been specified, not if it's valid, so you probably didn't get that message.
