### ISSUE TITLE
R157 - Z order panel is empty

### ISSUE THREAD

**Issue by johnsmith27** [Scirra/Construct-3-bugs#3103]
## Problem description

The Z order panel is empty/blank even though I have a lot of stuff on all my layers.

I've tried with a new project, same results, Z order panel remains empty when adding some new sprites on a single layer.

Also tried to move the panel around, tried to toggle the option "active layer only", cleared Chrome cache, no success..

https://i.imgur.com/3UVWQTI.jpg

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** first started happening in r157 stable (I only use stable versions)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 521 mb (3.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
It looks like it works correctly for me. No project was provided so I tested Ghost Shooter. Please always follow the bug report guidelines to ensure we can help.

**Comment by QuasarX** [comment]
Same here. I see what is a problem.

1.) Make sure "Z-Order" panel opened before open any project.
![image](https://user-images.githubusercontent.com/13033837/60583886-8561a380-9d94-11e9-9c29-8466ff769e36.png)

2.) Open ghost shooter. That's it.
![image](https://user-images.githubusercontent.com/13033837/60583960-a924e980-9d94-11e9-8273-a7bb20e7eddd.png)

**How you can fix?**
Close and reopen your Z-Order panel.
![image](https://user-images.githubusercontent.com/13033837/60584031-cf4a8980-9d94-11e9-9226-f990cbc139ee.png)

**Comment by johnsmith27** [comment]
Thanks QuasarX, the close/open did the trick :)

**Comment by DiegoScirra** [comment]
This happens when the bar is showing but empty, for example when C3 is first started and there are still no projects, if you then load a project the bug will be triggered.

This was introduced along with the project resources background loading. The Z order bar is expecting to find a few things which simply are not there.

I suspect a similar problem is happening with the Bookmarks Bar.

**Comment by Dramamini** [comment]
Same problem here. Close and re-open, works

**Comment by DiegoScirra** [comment]
fixed in the next beta release.
