### ISSUE TITLE
r157: Webfonts don't show up in Text Dropdown

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#3107]
## Problem description

When importing a Webfont (any format) into a project, they don't show up in the dropdown selection of a text object.

## Steps to reproduce

1. Open a new project
2. Import a woff or similiar font into the project
3. Create a new Text object
4. Try changing the font with the Font selector

## Observed result

Only the dropdown for the System-installed fonts shows up.

## Expected result

Dropdown for Webfonts to appear.

## More details

Funnily enough, if i double click on my Webfont in the project window, it appears and the preview shows. Also, if i just manually type in the font name that i want to use it work within the Layout view but when i preview the project, the font is gone again.

**Affected browsers/platforms:** 
Chrome, macOS

r157

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_0
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 132 gb
Storage usage (approx): 549 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It works for me. Please follow the bug report guidelines to ensure we can help.

**Comment by joelmayer87** [comment]
@AshleyScirra Wait wait :D :D Haha, i uploaded a file and screenshot to show you how it looks on my side... Maybe i'm doing something wrong here i have no idea :S

**Comment by joelmayer87** [comment]
![image](https://user-images.githubusercontent.com/30116964/60584562-e3d75380-9d8d-11e9-8211-f47682224053.png)

![image](https://user-images.githubusercontent.com/30116964/60584598-f6518d00-9d8d-11e9-9a30-286431c574ec.png)

As you can see, the uploaded font works in preview but there is no dropdown...

**Comment by joelmayer87** [comment]
GEEEEZUS... sorry, my mistake, i imported the font to the main "Files" folder instead of fonts... So silly... Maybe there should be a popup or something or moving these kind of files into the correct folder automatically? In any case, it works and this can remain closed. Sorry for the confusion!
