### ISSUE TITLE
Tiled background artifact(r157)

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#3109]
## Problem description

Tiled background leaves artifact at top of texture with a transparency.
## Attach a .c3p

https://www.dropbox.com/s/viyv3i77ijjugpn/tbgwave-artifact.c3p?dl=0

## Steps to reproduce

1. Run project
2. Note line at top of object
3. Not a rounding error, drag and drop to test that

## Observed result

Line appears to be from its own texture

## Expected result

No line

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's the fact it is using fractional scaling and the bottom row of pixels is wrapping around to display at the top - since that's what tiling does.

Either use pixel-perfect rendering settings, or if you don't vertically tile the object, clear the bottom row of pixels to transparent.
