### ISSUE TITLE
Bug when setting effect parameter.

### ISSUE THREAD

**Issue by Sl0b** [Scirra/Construct-3-bugs#311]
## Problem description

*When setting effect parameter, in this case SetColor or ReplaceColor, it affects all instance of
the object even when an instance is specifically selected.*

[Here is the forum discussion](https://www.scirra.com/forum/setting-effect-parameter-affects-all-instances_t191842)

## Attach a .c3p

*[exemple project](https://drive.google.com/file/d/0B7WXHEWesGIlTWFRUF9SRUdaMmM/view?usp=sharing)*

## Steps to reproduce

1. Create different instance of object, here it's every second.
2. Change the SetColor parameter when you create an instance

## Observed result

*Every instance of the object changes color, it doesn't on Construct 2*

## Expected result

*I'd like to change only the newly created instance, same as C2*

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 68 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by emoaeden** [comment]
I have a similar issue, that I have a sprite, and am creating one every 128 pixel to fill the layout. When I set the colour, based on a variable, it sets every instance to the same colour; even though I have used a For Each condition.

https://www.dropbox.com/s/44o31mrd0d2osz4/GoodThingsComeIn3s.c3p?dl=0

**Comment by AshleyScirra** [comment]
Can you provide the equivalent Construct 2 project as well? This makes it easier to test side-by-side, since the .capx can also import to C3.

**Comment by AshleyScirra** [comment]
Never mind, figured it out anyway. Should be fixed for r32.
