### ISSUE TITLE
Shortcut Not work

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3110]
# Problem description

**Chrome**
https://support.google.com/chrome/answer/157179?hl=en

**Firefox**
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

All popular browsers using **Ctrl+ F4** for **Close tab**. So it is not work. How did you test?

https://www.construct.net/en/make-games/manuals/construct-3/interface/keyboard-shortcuts

**Ctrl + F4** Debug from first layout

**Comment by AshleyScirra** [comment]
We actually changed it a while ago to Shift+F4 and Shift+F5 for this reason. I updated the manual to reflect this.
