### ISSUE TITLE
C3 Mobile - Cannot exit sprite animation frame menu

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#3113]
## Problem description

The Animation Menu of a sprite cannot be closed if the whole viewport of the panel is full with frames. 
I'm guessing since there's no swiping space for the gesture to trigger. This should be made possible on the menu's title. In fact I believe every swiping menu should have buttons to open/close them as I've had a lot of problems finding the proper space to swipe from (you need to have blank spaces on the event sheet/paneles to do it)

## Attach a .c3p

Blank project works.

See attached images:
![Screenshot (5 Jul 2019 17_11_58)](https://user-images.githubusercontent.com/7268697/60729270-ff3b8d80-9f4a-11e9-8ba9-798cf1d9b819.png)
![Screenshot (5 Jul 2019 17_28_40)](https://user-images.githubusercontent.com/7268697/60729271-ffd42400-9f4a-11e9-9309-48583a7237e7.png)

## Steps to reproduce

1. open a new project
2. create a new sprite
3. close any menu (such as sprite animation if opened)
4. open the project panel
5. hold on sprite, Edit 
6. add blank frames until the panel could scroll
7. try to close the panel

## Observed result

The Animation Frames panel doesn't close no matter where you swipe from.

## Expected result

I'd expect to close the panel by swiping on the title

## More details

**Affected browsers/platforms:** Chrome on Android 9

**First affected release:** noticed it since r157 since now i started using the phone occasionally for C3 development

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.101
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Android
Operating system version: 9
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2.625
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 9; Nokia 7.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.101 Mobile Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 3.3 gb
Storage usage (approx): 100 mb (2.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Qualcomm
Renderer: Adreno (TM) 509
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This is fixed in the next beta release.
