### ISSUE TITLE
Android "Back" button doesn't work in fullscreen

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#3115]
## Problem description

When an APK is exported with "Hide status bar" option checked, "Browser On mobile Back button pressed" event doesn't work.

## Attach a .c3p

https://www.dropbox.com/s/mdhkdlmghloiv4s/BackTest.c3p?dl=0

## Steps to reproduce

1. Build the app with "Hide status bar" option checked.
2. Run on Android device
3. Press Back button.

## Observed result

Nothing.

## Expected result

Text "Back pressed" should appear on the screen.

## More details

**Affected browsers/platforms:** Android, tested on several different mobiles.

**First affected release:** not sure, but it was working fine in r142

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 11 gb
Storage usage (approx): 101 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by QuasarX** [comment]
Which Android versions you tested?

**Comment by dop2000** [comment]
@QuasarX, We tested on 4 different devices with various Android versions from 6.0 to 9.0
Also, today I tried building the same test project with C3 r142 and it doesn't have this issue.

**Comment by QuasarX** [comment]
@dop2000 
I know what is problem.
Can you try with this? Default C3 export using this **"false"**
![image](https://user-images.githubusercontent.com/13033837/60807554-ac521800-a18e-11e9-93ec-bc24e5ca03e8.png)

in config.xml you need set true and do apk with this.

**Comment by shortercode** [comment]
It's probably worth noting that we changed the value of fullscreen to false to fix a bug on some older devices. Cordova tries to enter immersive mode immediately on startup, which causes a race condition on those devices and ends up with a statusbar sized black bar at the bottom of the display.

We instead start immersive mode later, when the runtime is starting up.

**Comment by dop2000** [comment]
@QuasarX , I tried changing this preference to "true", but nothing changed.. With "Hide status bar=OFF" the Back button is working, but the app is not in full screen. With "Hide status bar=OFF" the Back button doesn't work.
Tested on Android 9.0 and Android 6.0 phones.

**Comment by QuasarX** [comment]
it was work for me. Tested on Android 5

**Comment by dop2000** [comment]
@QuasarX Could you share you apk? Here is mine:
https://www.dropbox.com/s/83dgs1hykvrp5qs/TestBackFullscreenTrue.apk?dl=0
When you press Back, a message should appear on the screen, this doesn't happen on my two android phones.

**Comment by riocascade** [comment]
I've encountered the same issue.

here my apk, the working back button only when the exported app not in fullscreen.

https://drive.google.com/open?id=1_-Z7Alqj7cBURE8Zl-s03bUjEu7sYrW2

my android version is 8.1.0 OPM1.171019.026

**Comment by QuasarX** [comment]
@dop2000 Here is mine. 

**Note:** I was used Cordova CLI 9.0 (Android 8.0) not C3 Export Manager for build apk.
**Export Setting:** "Hide status bar=ON"
**Test Phone:** Android 5.0
[TestBlackBar.android.debug.zip](https://github.com/Scirra/Construct-3-bugs/files/3371610/TestBlackBar.android.debug.zip)

**Comment by QuasarX** [comment]
@shortercode 
If it is true, can we see C3 Build Service changes in Construct 3 release notes?
It is easy to fix some issues if others using Cordova CLI or Phonegap.

**Comment by shortercode** [comment]
@QuasarX This was a construct change, not build service. The change was merged together with a few other layout fixes in the release notes.

Changes to the build service aren't linked to construct releases, we only ever have 1 version of the build service that all versions of construct use. So it's not appropriate to include build service changes in that changelog.

You were the OP for the issue, see [my comment on the fix](https://github.com/Scirra/Construct-3-bugs/issues/2364#issuecomment-504486610)

**Comment by QuasarX** [comment]
I'm still thinking we need to see that changes anywhere. Forums or dedicated page like Construct 3 release notes has.
Why?
You see that Default Cordova CLI and C3 Build Service apks not totally works same. One buggy other not (maybe)
Same project but different behavior.
It is just think.
`¯\_(ツ)_/¯`

**Comment by shortercode** [comment]
Changes to the build service are generally maintenance related, or facilitate a construct release adding additional fixes. So in practice they should have no effect on existing releases.  The issue we're talking about here didn't have any changes on the build service, only the project configuration that construct generates. Building this project in the cordova CLI should give you exactly the same behaviour as the build service. The only differences come down to dependency versions, and the build environment.

**Comment by shortercode** [comment]
Is anyone here using the splashscreen plugin?

https://github.com/apache/cordova-android/issues/687

https://github.com/apache/cordova-plugin-splashscreen/issues/186

**Comment by QuasarX** [comment]
No. I was tried but it doesn't work with CLI v9.0 when I tried.

**Comment by shortercode** [comment]
Well I haven't pinned down the reason why it doesn't work, it looks like the event isn't being fired by the webview object. There's some interesting comments on those issues about changes in sdk 28 related to changing the visibility.

I've tried disabling the code that enables fullscreen mode, which does allow the back button to work. But the app is then of course not fullscreen. I'm going to investigate the differences between how the cordova fullscreen flag works against how the fullscreen plugin enables it. Hopefully I will be able to find a tweak I can make that resolves the problem.

**Comment by shortercode** [comment]
Okay I've found the reason. It's a bug in the fullscreen plugin we're using, I'll take a look at the plugin repo and see if they are inclined to fix it. But I think it might be easier if I move the fullscreen logic into the cordova plugin we published to add notch support.

**Comment by shortercode** [comment]
Turns out we we're using an older version of that plugin. I've updated the whitelist on the build server to include the latest version. So should be resolved for you now.

**Comment by dop2000** [comment]
@shortercode , Can confirm it works now, thank you so much!

**Comment by shortercode** [comment]
Glad to hear!
