### ISSUE TITLE
Physics behavior slowed down on some mobile devices

### ISSUE THREAD

**Issue by HinzDesign** [Scirra/Construct-3-bugs#3117]
## Problem description

**Physics behavior based controls of the Player object get very different results on different mobile devices. (Feels like if the _density_, _apply physics force_ or apply _physics torque_ would change).**

Many other reasons that could end with this result, that feels similar to lag, have been tested / temporarily removed. Cause it seems so much like a performance related topic. **But when an old version, that used to run perfectly, all of a sudden started to have the same issue, things started looking strange. Keep on reading for a detailed report ;)**

## Attach a .c3p

**I ) Current Version** [Physics_Problem_On_Mobile.zip](https://github.com/Scirra/Construct-3-bugs/files/3365665/Physics_Problem_On_Mobile.zip)

## Steps to reproduce

1. Test it on Computer and Browser to see how it is supposed to be.
2. When testing with a PC browser, resize the window to a mobile size and refresh the project
3. Controls are "W" = accelerate, "O" and "P" = rotate

4. Test it on mobile. Controls for mobile: Touch bottom left corner = accelerate, bottom right corner = rotate.

## Observed result

**Player controls are like in slow motion, way to slow, not consistent**. On some mobile devices the rotation e.g. takes about 6 seconds for 360°. While on PC or other mobile devices it only takes about 2 seconds.

## Expected result

The player controls work fine on PC and many devices. They should be smooth and consistent. They feel like the density of the player is doubled, or the applied forces are too weak all of a sudden.

## More details

I tried applying delta time to my physics based controls and see if this helps; (didn't). But I am pretty sure that since the physics behavior works in pixels over time, delta time is already taken into account.

I also got rid of anything that could cause lag. Like all effects, all procedual level generation, z-elevationed elements etc.

**I still wasn't believing in a bug. But than came the moment of "wait what?!". I tested an older version of the game, that worked just fine and the "slow controls" appeared here as well!! Making me think that something else must have changed.**

**II ) Older Version** (that definetly worked, but doesn't anymore)
[older_version.zip](https://github.com/Scirra/Construct-3-bugs/files/3365681/older_version.zip)
This is the older version that was working perfectly fine on the device I have suddenly problems on now. If testing: follow "_Steps to reproduce_" for guidance 

I also uploaded the game to my server, to see if it had anything to do with the remote preview. Still got the same results.

**III ) Online Version**
http://hinz.design/testserver/akima/
If testing: follow "_Steps to reproduce_" for guidance 

Also the debug mode does not show anything that looks like a problem:
![Unbenannt](https://user-images.githubusercontent.com/37619057/60769260-bcee8980-a0cd-11e9-8230-2d6ec98ed294.JPG)

**Affected browsers/platforms:** 
No inconsistency / runs well on:
- Windows / Chrome Version 75.0.3770.100 (Offizieller Build) (64-Bit)
- iPhone 6s / IOS 12.3.1 / Safari
- iPhone 5s
- Samsung Galaxy s8

Inconsistent / slow physics based controls on:
- Samsung J7 Prime 2017 / Operating System Android 8.1.0; SM-G610F Build/M1AJQ / Chrome
- NVIDIA Shield Tablet K1 / Build/NRD90M / Android Version 7.0 / Chrome 75.0.3770.101
- Google Nexus 5X

**First affected release:** 
Accured with _Release r157 stable_

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 193 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

## Summary

Testing the game on some devices, let's the game appear very very slow; not really laggy, but as if the physics behavior based controls are freaking out. I still don't believe it being a bug and hoping for a different mistake, hopefully on my side. But as soon as I saw that even an older version, that was running fine, all of a sudden has the same issue as the newer versions, I started questioning if it was anything I did wrong :P

I'm hoping for help in any shape, size or form.
Thank you very much!
All the best,
Chris

**Comment by shortercode** [comment]
Sounds like a possible regression, although I can't think of any physics related changes that happened recently. Do you remember what version of construct you used to build the known good version?

**Comment by HinzDesign** [comment]
Hi shortercode,

i think there was none. Both where build on Release r157 stable. The "definate good version" was done on the 5th July, and the problem started on the late 6th.

I continued testing on more devices and will continue to improve the bug report. I'm thankful for any help, don't know what is wrong.

Best,
Chris

**Comment by AshleyScirra** [comment]
I'm afraid there are far too many events in this project for it to be feasible to debug it. In these cases it usually is simply a mistake in your events. It could also be non-deterministic behavior in your events, including performance-sensitive behavior, that only occurs on certain devices, or even at random which you've falsely attributed to specific devices (an easy mistake to make). I'd also point out that r157 came out on July 1st, so assuming you used r157 in both cases on the 5th and 6th, there was no Construct release in between so any change in behavior could not have been caused by a Construct update, which again suggests it is instead a mistake in your project.

Please see the bug report guidelines around providing a minimal project - that requirement is there to decisively prove that the problem really is with Construct.
