### ISSUE TITLE
When you remove and re-add something. Removed all codes coming reback

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3118]
## Problem description

Two problems with one bug report.

1.) Please watch video and do that steps for reproduce. When you remove something in event sheet and when you add with same names, all codes coming back. (All removed)

2.) When you remove function and if it is used anywhere, it doesn't show warning.

## Attach a .c3p

Use any project.

## Steps to reproduce

https://streamable.com/w2jeh

## More details

**Affected browsers/platforms:** Chrome
Construct 3 r157

**Comment by AshleyScirra** [comment]
This is the same cause as issue #2478. See my comment there for context.
