### ISSUE TITLE
Name correction blocks the insert object action

### ISSUE THREAD

**Issue by kondokuro** [Scirra/Construct-3-bugs#312]
## Problem description

On any project, when attempting to insert a new object, if the user writes the name of the object with non valid characters (space in this case) a name correction will happen and show a pop up notification that non valid characters have been removed. After clearing out the pop up message by clicking anywhere on the screen, the insert button does not complete the action, requiring for the user to close the insert object dialog and write the name without any non valid characters.

## Attach a .c3p

[bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1018223/bug.zip)

## Steps to reproduce

1. Open Construct 3
2. Create a new project
3. Right click on an open space in the layout
4. Use the insert object action
5. Select any object type
6. Name it with at least a non valid character, like with a space between two words, "not valid" for example.
7. Press Enter or Click insert

## Observed result

The name changed, a pop up showed up and the insert button does not work

## Expected result

The object is inserted in the layout with the corrected name.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected HTML element @ TypeError: expected HTML element at Function.ǃC.ǃfq (https://editor.construct.net/r29-2/main.js:2:202652) at me.ǃ_r (https://editor.construct.net/r29-2/main.js:61:246035) at n.ǃ_e.then.p (https://editor.construct.net/r29-2/components/bars/layersBar/layersBar.js:1:3839) at 
Stack: TypeError: expected HTML element at Function.ǃC.ǃfq (https://editor.construct.net/r29-2/main.js:2:202652) at me.ǃ_r (https://editor.construct.net/r29-2/main.js:61:246035) at n.ǃ_e.then.p (https://editor.construct.net/r29-2/components/bars/layersBar/layersBar.js:1:3839) at 
Construct 3 version: r29.2
URL: https://editor.construct.net/
Date: Mon May 22 2017 04:29:29 GMT-0400 (EDT)
Uptime: 3160.4 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Ivybridge Mobile 
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r31.
