### ISSUE TITLE
can't upload some music

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3120]
## Problem description
I can't upload some music files

## Attach a .c3p
https://puu.sh/DQ5xo/504e492a95.WAV

## Steps to reproduce

1.download the .WAV file
2.try and import it in a project
3.

## Observed result

nothing
## Expected result

the music to be imported in the project
## More details

i tried blank projects, different construct versions, different browsers, none seem to work

**Affected browsers/platforms:** 
chrome, firefox, current stable, older stable versions

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 724 mb (4.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Interesting catch, the dialog doesn't like uppercase file extensions. So it immediately decides the file isn't something it can use. If you change it to ".wav" it will accept the file. I've corrected it to ignore the case on the file extension, so this will be resolved in the next release.

I wouldn't really advise using uppercase file names/extensions. It's mostly personal choice what you use, but case sensitivity in file names/extensions causes problems all over the place. Particularly if your sharing your work between windows and *nix systems. Windows is supposed to be case insensitive, but when using the windows open file dialog the file extension limits are case sensitive. So you have to pass in both "wav" and "WAV"... and that providing nobody is going to try files like "wAv" or "WaV". Of course people can just change the dropdown to "all files", but that's just one example I've encountered this morning as to why using mixed case filenames is a bad idea!

Thanks for the report anyway, just my morning ramble.
