### ISSUE TITLE
Debugger laggy on start, while service workers are still working

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3121]
## Problem description
Using slow laptop i had issue, whenever i check debugger i see fps spikes and FPS then goes down to ~50 and stays there for a while, but project does not do anything so fps should be solid 60. After a while it does go back to 60, but user must wait around ~30sec, which messes up debugger readings. Noone should wait so long to get solid readings.
It took me sometime to connect it to something, but only thing that changes same time when FPS goes back to 60 is service workers get disabled/ or go to sleep.

See pic below, whenever thous two service workers go to sleep etc, FPS does not spike anymore.
![Debugger_StartLagg](https://user-images.githubusercontent.com/28864889/60802990-d3a2e800-a182-11e9-8858-d52a6036b92a.jpg)

I don't have solid example and it does not produce on my main PC, but could still need investigation to see if thous service workers affect debugger FPS readings.

## Steps to reproduce

1. Start chrome Task manager.
2. Start debugger on some simple example
3. See debugger fps is unstable, but when service workers go to sleep, FPS does not spike anymore.

## Observed result
Debugger does not show solid FPS on start, user might need to wait for a while to get solid readings. Only things i found that may be connected to it, is service workers that are working for a while when debugger is opened.

## Expected result
Debugger to have solid readings on start, or some inticator inside debugger to show that project is still loading, so user knows readings are wrong first ~20 sec or so.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.4 gb (10.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
No project provided so tested with Ghost Shooter, and can't reproduce there, it starts running at 60 FPS right away. If this really is caused by awake Service Workers that would be a Chrome issue to file with Google. Normally the Service Workers will be idle doing nothing. However if you only just opened C3 for the first time it's possible the editor SW is caching the editor for offline use in the background, which could impact performance on a low-end device until it finishes.
