### ISSUE TITLE
new functions not seeing booleans! 

### ISSUE THREAD

**Issue by stuatk** [Scirra/Construct-3-bugs#3122]
## Problem description

Functions cannot "see" a variable of type boolean - even if they are at the same scope level i.e. Global boolean and function defined in the root of the event sheet.

Functions cannot "see" a variable of type boolean - even if they are at the same scope level i.e. Global boolean and function defined in the root of the event sheet.

## Steps to reproduce

1. create a boolean
2. create a new style function
3. inside the function add an action - "System - Set Value" 

## Observed result

the function does not show the boolean in the drop down list (it does if the value is turned into a number!)

the function does not show the boolean in the drop down list (it does if the value is turned into a number!)
## Expected result
be able to access the boolean in the drop down list

## More details

seems to be an oversight - new functions have not have boolean access added to them!

**Affected browsers/platforms:** 
ALL!

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
`System: Set Value` does not work for booleans, regardless of whether you are in a function or not. You should be using `System: Set Boolean` instead.

**Comment by stuatk** [comment]
Thanks Yep! Catches me out all the time! Booleans have there own special actions... where string and numbers use the same action... wonder how many other people this confuses??
