### ISSUE TITLE
Some icons hover on top of Log in Dialog in Mozilla

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3124]
## Problem description
Some icon hover on top of Dialog. See pic below:
![Mozilla-Ui](https://user-images.githubusercontent.com/28864889/60907988-82c6e880-a283-11e9-9c8e-34f4e8c19830.jpg)

## Steps to reproduce

1. Open mozilla, navigate c3 editor homepage
2. Open log in Dialog, move it over project icons
3.

## Observed result
Project cload or local icon hover ontop of Dialog

## Expected result
No wrong icon hovering

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 67.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
C3 release: r157 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 240 kb (0%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    ImageBitmap support is disabled in Firefox due to bug 1472194
    CSS containment is not supported. Editor performance may be significantly degraded.
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmap is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
This is probably down to the z-index of the icons. We have to use a polyfill for the dialog element on mozilla which doesn't behave the same way as the real dialog element when it comes to z sorting.

I'm not sure what the state of the HTMLDialogElement specification is, last I checked Chrome was the only browser to support it, and it's a little buggy. Firefox has an incomplete implementation behind a developer flag that hasn't changed for a number of years. As such I wouldn't be surprised if it was depreciated at some point in the future. It might be something we should take into account for our dialog system...

As for this bug I'll leave it to @AshleyScirra to take a look at, as he does most of the work on the start page. I expect it's a simple style change.

**Comment by SnipG** [comment]
Long time ago i reported timeline dialogs/icons, but Diego fixed that one.
I am not aware of any other. Even though I only use Mozilla for Theme changing, I encountered this only now and because there are so many dialogs and icons and combination between them. There easily could be more.

**Comment by AshleyScirra** [comment]
Fixed for next release.
