### ISSUE TITLE
Even in Safe Mode, plugin conflict crashes C3 editor

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3126]
## Problem description
Was testing around my theme, made few changes and tried to make new verion and changed everything inside addon files. But main plugin name was left unchanged. Even in safe mode the name causes conflict, not sure if should crash or not.
See pic below:
![SafeMode_Error](https://user-images.githubusercontent.com/28864889/60995960-5af78380-a35c-11e9-9c4a-2e049686b7f9.jpg)

## Attach a .c3p
1. [nightlight.zip](https://github.com/Scirra/Construct-3-bugs/files/3379002/nightlight.zip)

2. [nightlight-1.0.4.9-stable.zip](https://github.com/Scirra/Construct-3-bugs/files/3379005/nightlight-1.0.4.9-stable.zip)

## Steps to reproduce

1.Add 1. addon and change theme to it.
2.Add 2. addon. Reload c3
3.

## Observed result
C3 does not load up because name conflict. Using safe mode still crashes c3

## Expected result
Able to remove plugin in Safe mode, when there is name conflict.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: n.ǃE_m is not a function @ TypeError: n.ǃE_m is not a function at n.plugins (https://editor.construct.net/r157/main.js:63:114573) at plugins.next () at ǃp.ǃEh.ǃLk.ǃE$h.ǃE$m (https://editor.construct.net/r157/main.js:159:18219) at https://editor.construct.net/r157/main.js:159:17946
Stack: TypeError: n.ǃE_m is not a function at n.plugins (https://editor.construct.net/r157/main.js:63:114573) at plugins.next () at ǃp.ǃEh.ǃLk.ǃE$h.ǃE$m (https://editor.construct.net/r157/main.js:159:18219) at https://editor.construct.net/r157/main.js:159:17946
Construct 3 version: r157
URL: https://editor.construct.net/?safe-mode
Date: Wed Jul 10 2019 21:37:33 GMT+0300 (Eastern European Summer Time)
Uptime: 3.2 s

Platform information
Browser: Chrome
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by SnipG** [comment]
Tried to improvide and deleting plugin values from Application storage directly:
![Plugins](https://user-images.githubusercontent.com/28864889/61047410-1b767900-a3e8-11e9-9a6d-bbb3472bfb60.jpg)
C3 does not even open up in Safe mode now.

**Comment by QuasarX** [comment]
Safe mode will be good option for remove selected plugins.

When you delete IndexedDB, you will need reinstall all addons.

**Comment by shortercode** [comment]
You can actually edit the contents of "c3-addon-list" to not include the broken plugin using that part of chrome dev tools. Saves you having to delete everything.

**Comment by AshleyScirra** [comment]
I can't reproduce any problem in safe mode here - after following your steps it does crash on startup after installing the second addon, but when switching in to safe mode it loads OK and allows the addons to be uninstalled with no issues.

I think there are some known cases where if you install mutually conflicting addons it can crash the editor even in safe mode, but your next fallback after that is just to clear browser storage using the "Clear storage" button in dev tools, so there is still a way around it.

**Comment by SnipG** [comment]
Clear storage - i did, but i unchecked indexedb, so it did not get fixed. Clearing IndexedDB also clears browser saves? if so should plugins be moved somewhere else?

**Comment by AshleyScirra** [comment]
If you have browser saves you can also do what @shortercode suggested.

**Comment by QuasarX** [comment]
@shortercode 
> You can actually edit the contents of "c3-addon-list" to not include the broken plugin using that part of chrome dev tools. Saves you having to delete everything.

This doesn't allow you edit. When you remove this. You need re-install all plugins.
![image](https://user-images.githubusercontent.com/13033837/61219285-91e2e600-a71c-11e9-95e3-ccc3b4500495.png)

**Comment by shortercode** [comment]
@SnipG 
indexedDB is used to store pretty much all the persistent data in C3: layout state, recent exports, browser saves, addons, etc. It's the best place to put it, and there isn't really an alternative. Chrome doesn't really provide any granularity to users about what they want to delete. The standard user dialog doesn't even mention indexedDB, probably because most people won't understand what it is. 

I think they might have changed the debugger, you used to be able to edit the data just by double clicking it. But I don't seem to be able to do this now.

**Comment by shortercode** [comment]
They don't explicitly mention removing it, but [this page](https://developers.google.com/web/tools/chrome-devtools/storage/indexeddb) says you cannot edit it. So I guess they depreciated it for some reason.

Try running this in the console, should remove "lunarray_LiteTween" from the behaviour list.

```javascript
const addonlist = await localforage.getItem("c3-addon-list");
addonlist.behavior.pop();
await localforage.setItem("c3-addon-list", addonlist);
```

**Comment by QuasarX** [comment]
@shortercode Thx.

![image](https://user-images.githubusercontent.com/13033837/61220455-0b7bd380-a71f-11e9-8f1b-86d575d08b7b.png)

This for remove specific one. (Deleting GA plugin)
```js
const addonlist = await localforage.getItem("c3-addon-list");
addonlist.plugin.splice(0, 1);
await localforage.setItem("c3-addon-list", addonlist);
```
