### ISSUE TITLE
Raycast behaves very weird

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3129]
For some reason this causes things to get offset. For example, player.X is suddenly quite a bunch to the right of the player object. This also only happens when the function is called via the touchinput and not when just called on start of layout for some reason.

## c3p
[raybug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3388742/raybug.c3p.zip)

## Steps to reproduce

1. Cast a bunch of rays by swiping (The ray target is the little green dot)

## Observed result

If the ray target is properly overlapping the ground, it works fine. Also works fine if the target is far from hitting the ground. But if the ray is cast so that the little green target is close to the ground (but not actually hitting it) the bug occurs.

![what](https://user-images.githubusercontent.com/31101309/61171247-29a5d000-a575-11e9-8b79-35ac16837e2a.PNG)

The blue-ish rectangle is supposed to be created on player.X, player.Y. I´m not sure if the ray is supposed to register a hit in this case actually but it appears that the player sprite size is taken into account there.

## Expected result

The ray to properly miss/not have things weirdly offset.

## More details

I tried disabling collision cells but that didn´t help.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 602 mb (4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
It appears to be something related to the platform behavior, although I'm not sure how. I'm not at the office so can't take a look at the source code, I only took a look at this because I happened to be at my PC and this piqued my curiosity.

Player.x/Player.y are resolving to different locations only within the "ray intersected" condition, and only at certain angles. During on start of layout whatever is causing the problem appears to be inactive, putting a short wait into the condition will make the bug appear. Removing the platform behavior stops the bug.

A workaround is to pass the player.x/player.y values in as arguments to the function instead of reading the player position in the condition.

**Comment by Wackytoaster** [comment]
Heh I see, thanks for the workaround :)

**Comment by SnipG** [comment]
It is casting from other player object, not offset. You got second player object on disabled layer: See pic below
![Uhhh](https://user-images.githubusercontent.com/28864889/61172515-16532e80-a58e-11e9-95b5-c382eb3120a8.jpg)

**Comment by Wackytoaster** [comment]
🤦‍♂ Lmao ok, let´s forget about that. That was defenitely the problem.

**Comment by shortercode** [comment]
It did occur to me that there might be another instance involved, but I didn't think about checking disabled layers!
