### ISSUE TITLE
Crash when trying to set point of origin (low repro rate)

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#313]
## Problem description

C3 crashes when you try to set a sprite's point of origin after initially setting it. You can probably close this directly since it's random. It crashed ~ 8 times for me but I really can't reproduce it whenever I want.
I just hope the crash details could possibly help.

## Attach a .c3p

Couldn't reproduce on any c3p I created as a test.

## Steps to reproduce

1. Open a sprite
2. Change the point of origin
3. Open it again
4. (notice even though you didn't press on the point of origin button you might have the crosshair as a cursor but if you click to set the point of origin it won't work)
5. When you click on the point of origin button or the text Origin on the left panel it crashes

## Affected browsers

* Chrome: yes
## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r29-2/main.js, line 71, col 247826
Message: Uncaught TypeError: Cannot read property 'removeEventListener' of null
Stack: TypeError: Cannot read property 'removeEventListener' of null at ee.ǃJjl.ǃJqV (https://editor.construct.net/r29-2/main.js:71:247826) at ee.ǃJjl.ǃJqE (https://editor.construct.net/r29-2/main.js:71:176723) at ee.ǃJjl.ǃJjw (https://editor.construct.net/r29-2/main.js:71:176011) at ee.ǃJeh.te.ǃJaS (https://editor.construct.net/r29-2/main.js:71:163507) at ee.ǃJeh.te.ǃJjI (https://editor.construct.net/r29-2/main.js:71:163001) at Array.oe.addEventListener.me (https://editor.construct.net/r29-2/main.js:71:162523) at ǃC.Event.ǃm$A.ǃm$k (https://editor.construct.net/r29-2/main.js:2:285365) at ǃC.ǃl.ǃaF.dispatchEvent (https://editor.construct.net/r29-2/main.js:2:283755) at ǃC.ǃl.ǃb.ǃCrk.ǃwd.ǃCQw (https://editor.construct.net/r29-2/main.js:2:552732) at ǃC.ǃl.ǃb.ǃCrk.ǃwd.ǃCQg (https://editor.construct.net/r29-2/main.js:2:552036)
Construct 3 version: r29.2
URL: https://editor.construct.net/index.html
Date: Mon May 22 2017 17:52:13 GMT+0300 (GTB Daylight Time)
Uptime: 548.6 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Haven't been able to reproduce it.

I made a small change that will prevent the crash. Check it out in the next release, r31.

**Comment by DiegoScirra** [comment]
Didn't mean to close this one just yet.

**Comment by AshleyScirra** [comment]
r31 is out!

**Comment by JeFawk** [comment]
Seems to be ok now. If I get a crash caused by this I'll come back here. Can close it I guess.
