### ISSUE TITLE
Animations Editor 60FPS animation cap.

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#3132]
as recommended by Ashley on per this forum thread
https://www.construct.net/en/forum/construct-3/general-discussion-7/animation-cap-60fps-145276

## Problem description

Animation speed is limited to 60 FPS in editor.

## Attach a .c3p

Use any c3p demo, template, example

## Steps to reproduce

Create and or open an animated sprite within the editor.
under the animations options try to raise the animation speed to above 60FPS

## Observed result

speed cannot be raised above 60FPS

## Expected result

speed can be set at any FPS (maybe dependent on other limitations)

note statement has been made that "animation can only be advanced 1 frame per tick".
Thus introducing possibility of animation speed higher than game frame-rate probably introduces some further complications in the engine would have to calculate frames to be skipped.

**Comment by shortercode** [comment]
Assigned to @DiegoScirra as he works on the Animation Editor

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
