### ISSUE TITLE
Mac combination for { and [ opens the preview

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3133]
## Problem description

typing a { or a [ in a JS block is done by pressing Alt + 5 or Alt + Shift + 5 but Alt + 5 on mac launches the preview and overrides writing [ or {
Note it is also impossible to write [ or { in an expression field but doesn't launch the preview

## Attach a .c3p

n/a

## Steps to reproduce

1. Focus a JS block/script or an epxression field
2. Write [ or {

## Observed result

On a JS block/script the preview is launched, on an expression field, nothing happens

## Expected result

it should write [ or { if a field is focused

## More details
Note that that could either be fixed by changing the key for starting the preview to something else on mac, or by adding a check to see if something is focused and it should be writing instead of executing the shortcut.

**Affected browsers/platforms:** macOS

edit: Replaced "Option" with  "Alt" for more clarity

**Comment by shortercode** [comment]
What style of keyboard are you using? The Mac English UK and American both have keys next to the enter keys for these brackets.

**Comment by skymen** [comment]
This is the keyboard layout I am using (french one)
https://keyshorts.com/collections/language-keyboard-stickers/french

Quote from keyshorts.com: "Used in France, Belgium, Morocco, Algeria, French Guyana, Chad, Cote d'Ivoire. It's also used in parts of Luxembourg and Switzerland. You can buy a MacBook or Apple keyboard with this layout."

Also note that I said "Option + 5" but in the english Layout, Option is named Alt

**Comment by shortercode** [comment]
Thanks for confirming. I think the shortcut choice didn't take into account mac keyboard compatibility. The comparable key combo on windows doesn't do anything. I think we might be able to make some changes to the text editor and expression editor to not trigger the "preview project" action when they are focused.

**Comment by joelmayer87** [comment]
I'm from Switzerland and had the same problem, thanks for reporting!

**Comment by shortercode** [comment]
Looks like the shortcuts are explicitly enabled when in a text input or similar, @AshleyScirra will disabling them cause any negative effects?

**Comment by AshleyScirra** [comment]
That might mean you can't preview your project by keyboard if you have a code editor open.

**Comment by shortercode** [comment]
Well there's 2 shortcuts that this effects, which are: PreviewLayoutMultiple, DebugLayoutMultiple.

It probably isn't an issue on event sheets, but yes I imagine if a text editor is open those shortcuts wouldn't work. Other than changing the shortcut keys I can't see a different solution unfortunately. At least it's a less common shortcut. I don't think there's any similar issues on the UK or US keyboards, but not being able to type square or curly brackets on some devices is worse than an uncommon shortcut not working in some places I think.

**Comment by AshleyScirra** [comment]
On further thought the Alt+4/5 shortcuts only start multiple previews, which is presumably less common than starting normal previews, so disabling them if you have a code editor open might not be that big of a usability issue. It's tempting to make the change macOS-specific, but without researching all possible keyboard layouts, I don't think we can say for sure that this only happens on macOS devices, so we should probably assume Alt+number could potentially type a character on any system. Therefore I've just disabled the Alt+number shortcuts while typing for the next release, I think that's the best option for now.
