### ISSUE TITLE
On Mac you can't add a google drive account if C3 is added to desktop

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3134]
## Problem description

On Mac, if you have C3 added as a desktop app, and you try to open the cloud saving stuff, when adding an account, the popup will be stuck on the "redirecting" phase and never actually add the account. Tried with Google Drive, can't confirm for other cloud services though.

## Attach a .c3p
n/a

## Steps to reproduce

1. Add C3 to desktop on Mac
2. Try opening or saving a file to cloud, a popup will appear to select the service and link an account
3. Connect the account in the popup

## Observed result

The popup gets stuck in the "redirecting" page and never closes

## Expected result

The popup should successfully redirect and work properly

## More details
This only happens when added to the desktop. When opened from chrome directly it doesn't happen. I have also not tried on other OS, the problem might be similar on WIndows or Linux, but I can't confirm.
Similarly, the issue might or might not happen with DropBox and OneDrive, but I cannot confirm either

**Affected browsers/platforms:** Chrome macOS

**Comment by shortercode** [comment]
I can't replicate this on either windows or mac. Does the popup appear immediately or do you have to grant permission to it?

**Comment by skymen** [comment]
The popup appears and I go through the whole signing in process, and when I log in, the popup is supposed to close and grant access to C3 but it never closes and stays blocked on a white page with the text "redirecting".

I'm not on my mac today, I'll try to make a more detailed comment when I can.

**Comment by shortercode** [comment]
Mmm thanks for confirming. The redirecting page should close itself pretty much instantly, either it's failing for some reason or you have an cached older version.  If you could get the console log from the popup ( not the editor ) then it would be appreciated.

**Comment by skymen** [comment]
![image](https://user-images.githubusercontent.com/11213825/61713960-a4c76d00-ad51-11e9-877d-b64823da6551.png)
This is what I get

**Comment by shortercode** [comment]
well... I had kind of hoped that there would be some sort of error there. But that's all normal stuff.

Could you show me the source for the page? Want to see if you have an older cached version than what I was getting.

**Comment by AshleyScirra** [comment]
Had 'need info' tag for ~3 weeks but no response, so closing.
