### ISSUE TITLE
Hidden Condition Parts [r158]

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3138]
## Problem description

Some condition parts hiding

## Attach a .c3p

[JSONPathExample.zip](https://github.com/Scirra/Construct-3-bugs/files/3395859/JSONPathExample.zip)

## Steps to reproduce

1. Open project
2. Just do like in gif

![Bug4](https://user-images.githubusercontent.com/13033837/61275337-68769880-a7b6-11e9-8a3f-3cdd07f9552c.gif)

## Observed result

Hiding some parts

## Expected result

Show all parts

**Affected browsers/platforms:** Chrome

**Comment by AshleyScirra** [comment]
I can reproduce in Chrome 75 but not Canary 77 or Firefox release/nightly. In Chrome 75 dev tools shows the elements are there for the rest of the condition text, but for some reason are invisible. Therefore I think this is a Chrome paint bug that is already fixed for an upcoming release.
