### ISSUE TITLE
No resizing when paste a larger frame

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#314]
## Problem description

When I copy a frame and paste it in a smaller other frame, the Animations Editor dont ask to enlarge the frame. In construct 2 a message ask you if you want to enlarge canvas.

## Steps to reproduce

1. Make a 128*128 frame
2. Make a 256*256 frame
3. Copy the 256*256 frame
4. Paste it on the 128*128

## Observed result

The image is croped in the 128*128

## Expected result

Program ask to enlarge canvas

**Comment by DiegoScirra** [comment]
Added in r36.
