### ISSUE TITLE
crash happened

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3141]
getting crash don't know why I just opened project create a function and added array. 
crash didn't happened instantly, I left my project open and minimize after few minute when i return to my project it was crash. 

## Attach a .c3p
I am unable to reproduce it but may be crash report help you.

## Observed result
crash

## Expected result
no crash

## More details

I only have this crash report and don know why this crash happened.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.ǃlb (https://editor.construct.net/r158/main.js:2:92364) at Function.ǃXM (https://editor.construct.net/r158/main.js:159:130585) at e (https://editor.construct.net/r158/main.js:159:117512) at https://editor.construct.net/r158/main.js:159:118222
Stack: TypeError: expected string at Function.ǃlb (https://editor.construct.net/r158/main.js:2:92364) at Function.ǃXM (https://editor.construct.net/r158/main.js:159:130585) at e (https://editor.construct.net/r158/main.js:159:117512) at https://editor.construct.net/r158/main.js:159:118222
Construct 3 version: r158
URL: https://editor.construct.net/r158/
Date: Tue Jul 16 2019 17:13:09 GMT+0530 (India Standard Time)
Uptime: 300.4 s

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r158 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Sorry, there is nothing we can do in this case from the crash report alone (which is typical, which is why we require a full report with things like the steps to reproduce).

Construct automatically sends us crash reports which we investigate from time to time, so if you only have a crash report and nothing else, there's no need to file an issue. If we can fix it from the crash message alone, we probably will be able to anyway via the reports.
