### ISSUE TITLE
Player falling through multiple Jump Thur Objects.

### ISSUE THREAD

**Issue by Hellfish74** [Scirra/Construct-3-bugs#3142]
## Attach a .c3p

https://drive.google.com/file/d/1kwRJkQQe0EczKgw8AI0ymvGy23okp56i/view?usp=sharing

## Steps to reproduce

1. Move ball to Bar
2. Slow move ball left and right
3. Ball falls though object

![falling](https://user-images.githubusercontent.com/52963449/61295460-fad76600-a7cf-11e9-91b2-55547e63732a.png)

## Observed result

Ball falls through bar Object

## Expected result
As there are no Gaps, and collision box is full on box object, I would expect the ball to stay onto and not fall through.

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
157/158 Beta
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 134 mb (0.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The problem is the bottom of the player's collision mask is very slightly diagonal (28.07 to 28.04 on the Y axis). A diagonal base means the player can slide down along the platform as it moves, and once it's below the height of the next jump-thru, it will move through it instead of remaining on top (by design). The object must have a flat base to work correctly with the platform behavior. In fact we recommend using a rectangular collision mask with the player sprite placed on top.

**Comment by Hellfish74** [comment]
Even With the Bottom set perfectly Flat (both points at 28) it still fall through.

https://drive.google.com/file/d/1cPkxDRZrwLKg7AIFGMalqHwjyQK1I_KI/view?usp=sharing

**Comment by SnipG** [comment]
This seems old case, bugs even in c2runtime. So most likely always been like that.
Case when you got big platform, which consist of small objects with jumpthus and you tap fast left or right and your player object has complex collision polygons, then it will fall through them on object edges, while you tap movement.
Fix is having 90 degree bottom corners; having just 1 object as bottom platform; doing all the logic with physics etc.

**Comment by AshleyScirra** [comment]
@Hellfish74 - if you placed it by hand it's probably still not exactly flat due to floating point imprecision. As I mentioned, you should use a rectangular sprite with a bounding box collision polygon, and place a sprite on top of that. That's what I tested and it did work correctly.
