### ISSUE TITLE
tooltip dissapears when selecting a variable with the arrow keys in autocomplete

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3144]
## Problem description
when selecting an autocomplete word thing the tooltip dissapears 
https://puu.sh/DTHGd/4766935e78.mp4

## Steps to reproduce

1.start typing something with a tooltip like setbit
2.open the parenthesis and autocomplete appears
3.pick the autocomplete word with the arrow keys and the tooltip goes away

## Observed result

the tooltip goes away
## Expected result

for the tooltip to stay there so that i know what I'm doing
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release
