### ISSUE TITLE
 Web Worker black screen

### ISSUE THREAD

**Issue by Sirtaximan** [Scirra/Construct-3-bugs#3145]
## Problem description

When I activate Web Worker, I only get a black screen on android.

With other projects this does not happen.

## Attach a .c3p

 I can send my project to your email.

## Steps to reproduce

1.Check the web worker box.
2.Export for android.
3.Run the .APK file on android.

## Observed result

black screen

## Expected result

The game should work

## More details

I've only tried it on android

**Affected browsers/platforms:** Android

It's the first time I do this test (r158)

**First affected release:** I do not know

## System details

Android 5.0 and 6.0

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines regarding providing a project.
