### ISSUE TITLE
Desktop Version crashes when Sign in to Dropbox

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3147]
Desktop version crashes when we do sign in to dropbox cloud
## Attach a .c3p
no need

## Steps to reproduce

1. start desktop version 
2. click to cloud
3. select dropbox
4. sign in 

## Observed result
Crash

## Expected result
Sign in 

## More details

**Affected browsers/platforms:** 
Desktop Version

**First affected release:** 
r158
## System details

<details><summary>View details</summary>

no crash report appeared

</details>

**Comment by AshleyScirra** [comment]
This looks like another case of the NW.js issue https://github.com/nwjs/nw.js/issues/7088 which is fixed for the next NW.js update, so it should be working again when we release that.

**Comment by luckyrawatlucky** [comment]
Still i am unable to login in Dropbox in Desktop version r159

**Comment by AshleyScirra** [comment]
We haven't issued an update yet.

**Comment by luckyrawatlucky** [comment]
Is there any way to use older version of construct 3 in desktop? So i could sign in in older version.
