### ISSUE TITLE
Shift Key sometimes locks up other keys for controls

### ISSUE THREAD

**Issue by RorySoh** [Scirra/Construct-3-bugs#3148]
## Problem description
If you have for example, a run key to hold down "Shift" and WASD controls, if you press simultaneously the shift key and a WASD key over and over again, if they are pressed at the same time, the movement won't be triggered.

It is the same when there is no Shift to run.

This didn't happen in previous versions of construct 3 and my version running on r146 is fine with no changes.

## Attach a .c3p
[testingshift.zip](https://github.com/Scirra/Construct-3-bugs/files/3401671/testingshift.zip)

## Steps to reproduce

1. 8 Direction movement object
2. Disable default controls and Map keys to WASD with keycodes
3. Spam Shift + mapped keycodes

## Observed result
Every time Shift + the keycode is pressed at the same time, they don't move.
Perhaps, it is using the capitalized version of the event key?

## Expected result

They should trigger them individually

## More details

This affects my gameplay controls, when running around normally, it just freezes up and a movement key doesn't register quite frequently.

**Affected browsers/platforms:** 

**First affected release:** 

First time noticing it is the latest stable. But it could've been happening awhile back. But its fine in 146

## System details

Windows 10

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Reliable steps to reproduce:

1. Press `A` down
2. Press `Shift` down
3. Release `A`
4. Release `Shift`
5. Press `A` again

Next press of `A` does not work, although one after that does.

**Comment by AshleyScirra** [comment]
The browser KeyboardEvent is kind of a mess and some earlier refactoring mixed up properties which caused this - it was indeed mixing up the lowercase and uppercase A character. Should be fixed for the next release now.

**Comment by RorySoh** [comment]
Thank you Ashley!
