### ISSUE TITLE
A suggestion for the frames use

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#315]
This is just a suggestion for the Animations editor.

The fonction copy a selection of frames and paste this selection of frames would be very cool.
For exemple, if you select 3 frames in an animation, and you could paste them in another animation (after or before the current frame)

**Comment by AshleyScirra** [comment]
I'm closing all issues here which are suggestions not already in C2. We want to focus on bugs only in this tracker, or minor TODOs. For new features please write up suggestions at: https://construct3.ideas.aha.io/
