### ISSUE TITLE
Extendbox breaks pixelSize in effects SDK

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3150]
## Problem description

This is an issue with the effects SDK. Extending the box breaks the pixelSize uniform

## Steps to reproduce

1. Take any effect that depends on pixelSize (like an outline effect or anything)
2. Set extendbox to any value that isn't 0
3. Preview

## Observed result

PixelSize breaks and doesn't give the in game pixelsize anymore and instead gives an "on screen, real" pixel size

## Expected result

pixelSize should stay consistent.

## More details
In fact I'm pretty sure that it breaks other stuff as well like srcOrigin but I'm not 100% sure.

**Comment by AshleyScirra** [comment]
It's not supposed to stay constant. It's the size of a pixel on the *source rendering surface*, which is sometimes the object texture, and sometimes a viewport-sized intermediate surface, depending on the stage of the effect compositor. This is always the correct size to sample an adjacent pixel, which is what the uniform is for. I checked and 29 of Construct's built-in effects use pixelSize, and as far as I am aware they all work correctly. There's also no reproduction provided here so I can't test it anyway.

**Comment by skymen** [comment]
[soothoutline_1_0_0_0.zip](https://github.com/Scirra/Construct-3-bugs/files/3406483/soothoutline_1_0_0_0.zip)

here is an effect I've been writing. Setting extend box to anything that isn't 0 makes the pixelsize be a screen pixel. Setting extendbox back to 0 fixes the issue

**Comment by AshleyScirra** [comment]
> Setting extend box to anything that isn't 0 makes the pixelsize be a screen pixel

This is pretty vague terminology - a "screen pixel" could be a physical pixel, a device pixel, a CSS pixel, a layout pixel, etc. All pixels end up on the screen so that term could mean pretty much anything. Similarly a "game pixel" could be any of the above, or a layout pixel, or a layer pixel, or an object pixel, etc. It's important to be clear about precisely what you mean. The comment in the shader file you provided actually describes screenPixel accurately:

> The size of a texel in the foreground texture in texture co-ordinates

That's what it's for and that's what it does. What is it you actually want to use in your shader?

**Comment by skymen** [comment]
For clarity I am talking about the pixels defined by the window resolution. If my game is 200x300 then I want to be able to set sizes based on that. 
Similarly I would also be OK with object pixels, since I don't upscale nor downscale my assets.
I want to write an effect that makes outlines and circles that have specific pixel size (a circle with a max radius of 10 pixels, or an outline of 1 pixel)

**Comment by AshleyScirra** [comment]
> For clarity I am talking about the pixels defined by the window resolution.
...which could be measured in layout co-ordinates, CSS pixels or device pixels. I assume you mean device pixels on the final render surface?

In that case I think you can just set the "must predraw" flag on the shader and it will always be processed via a viewport-sized surface, in which case `pixelSize` is always the size in texels of a device pixel. Except in the case you use low-quality fullscreen mode, in which case it's a texel on the render surface before scaling... but I think that's what you want anyway.

> Similarly I would also be OK with object pixels

Again that's too vague a term to comment on. Objects can be measured in layout co-ordinates, in object space, layer space, layout space, render surface pre-scaling (for low-quality fullscreen mode), render surface post-scaling, window space or screen space. There's a whole lot of transforms going on!

> I want to write an effect that makes outlines and circles that have specific pixel size
Normally that's not actually what you want. If you have a 5px outline of an object, then you set the layout scale to 2x, presumably you want that to turn in to a 10px outline. Or do you want it to stay the same size even in that case?

**Comment by skymen** [comment]
> Normally that's not actually what you want. If you have a 5 device pixel outline of an object, then you set the layout scale to 2x (or, equivalently, render on a high-DPI display with a device pixel ratio of 2), presumably you want that to turn in to a 10 device pixel outline. Or do you want it to stay the same size even in that case?

Yeah that's not what I want. This is what happens when I put the extend box params to higher values though. The effects started to be specific device pixel sizes which isn't the desired effect

> Similarly I would also be OK with object pixels
> Again that's too vague a term to comment on.

Here I'm talking about the object's size in the spritesheet.

> In that case I think you can just set the "must predraw" flag on the shader and it will always be processed via a viewport-sized surface, in which case pixelSize is always the size in texels of a device pixel.

Ok now I see the ambiguity. I am talking about this
![image](https://user-images.githubusercontent.com/11213825/61471143-87c22100-a982-11e9-8ef2-c0e8be739c7a.png)

What I want is to have the effect consistently stay attached to the game's resolution (aka if I set an outline of 1 pixel and the game is running at default resolution, then I get a 1 device pixel outline, and if I run the game at 10 times the size, then I get a 10 device pixel outline) however my issue is that when extending the box, the effect starts to get attached to device pixels instead of in game pixels

This is the same sprite with the same effect params at the same spot on the editor but at varying zoom scales
![image](https://user-images.githubusercontent.com/11213825/61471336-e38caa00-a982-11e9-94b6-991893809a37.png)

![image](https://user-images.githubusercontent.com/11213825/61471365-ef786c00-a982-11e9-8b88-d3ed59ce336a.png)

![image](https://user-images.githubusercontent.com/11213825/61471387-f8693d80-a982-11e9-93f9-f8031642b869.png)

And I don't want this happening.

**Comment by AshleyScirra** [comment]
> Here I'm talking about the object's size in the spritesheet.

That is already what pixelSize gives you.

I think you just need to get the math in your shader right. I can't help you with that I'm afraid, it looks super complicated.

Did you try the "must predraw" flag as well?

**Comment by skymen** [comment]
I did, and the must predraw flag just forces (as you said) the pixelsize to be a device pixel's size. 

Well, the whole calculation for size are these two lines:
![image](https://user-images.githubusercontent.com/11213825/61473089-ffde1600-a985-11e9-9dfc-83900916e7ee.png)

There's this line as well for circle size
![image](https://user-images.githubusercontent.com/11213825/61473106-0b314180-a986-11e9-8c41-5314629064f3.png)

**Comment by skymen** [comment]
Ok I have tried to replace pixelsize with a fixed value and it still did the weird issue. 

Does extending the background change the size of the texture to draw? 
Aka, if I'm zoomed in, the texture get's upscaled and THEN ran through the effects? That would explain what is happening.

**Comment by AshleyScirra** [comment]
> What really troubles me is the fact that the effect drastically changes just by extending the box size.

It shouldn't any more after you set the "must predraw" flag - because extending the box size also forces it to pre-draw. (Otherwise sampling pixels in the extended area could return unrelated images from the spritesheet.)

Anyway either way `pixelSize` should still be the correct value: the size of a texel in texture co-ordinates on the foreground surface. So if your shader does something different in each case, that suggests there's a problem with your math.

The effect compositor is incredibly complicated. It's often difficult to get effects just right, but it's possible. I covered a bit about how it works in these two blog posts:
https://www.construct.net/en/blogs/ashleys-blog-2/constructs-effect-compositor-1024
https://www.construct.net/en/blogs/ashleys-blog-2/constructs-effect-compositor-1025

**Comment by skymen** [comment]
Ok, the "must predraw" flag did work when previewed, but not when rendered on the editor, but ONLY if the extendbox params are set to 0. 

As soon as I set the extend box params to some other values, the rendering on the editor did not change, but it changed when previewed. 

Yet again, extending the box changes the way effects are applied.

With "must predraw" set to true and extend box set to 0,0 during preview
![image](https://user-images.githubusercontent.com/11213825/61476040-6a925000-a98c-11e9-990d-a3a788780b5c.png)

With "must predraw" set to true and extend box set to 0,0 in the editor
![image](https://user-images.githubusercontent.com/11213825/61476069-7ed64d00-a98c-11e9-8a8f-c8fe27dee2f7.png)

With "must predraw" set to true and extend box set to anything else during preview 
![image](https://user-images.githubusercontent.com/11213825/61476169-b3e29f80-a98c-11e9-9108-ae4e6c5fb2dd.png)

With "must predraw" set to true and extend box set to anything else in the editor
![image](https://user-images.githubusercontent.com/11213825/61476201-c4931580-a98c-11e9-8bca-b532015115d0.png)
