### ISSUE TITLE
Applying effect on layer breaks pixelsize.

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3151]
## Problem description

Pixelsize gives the right pixelsize based on the whole texture. It doesn't work on a layer and instead gives the size of a "real" pixel (aka the same issue as this: https://github.com/Scirra/Construct-3-bugs/issues/3150 )

## Steps to reproduce

1. Take effect that depends on pixelsize (like outline)
2. Put on layer
3. Send help

## Observed result

Pixelsize breaks when applied on a layer and gives real screensize pixel

## Expected result

Pixelsize should be consistent and give the in game pixel size.

## More details
Help, I want to write glsl effects but stuff keeps breaking for no reason and it's not making it easy

**Comment by AshleyScirra** [comment]
This is the same as issue #3150. I'm pretty sure it's working correctly and you're expecting it to do something it's not designed for.
