### ISSUE TITLE
Functions In Sample Projects

### ISSUE THREAD

**Issue by ReallyBasic1** [Scirra/Construct-3-bugs#3152]
## Problem Description

I have opened up one of the multiplayer templates and they use the "function" object. However, this isn't helpful for a quick copy-paste for use in other games. Is there any way the function obj could be switched to the built-in version in the templates?

## Attach a .c3p

I cannot attach the c3p file, but any of the multiplayer templates are a good example

## Steps to reproduce

none of the functions are built-in, they are all objects

## Observed result

none of the functions are built-in, they are all objects

## Expected result

It would be helpful to have built-in functions for the templates, not object based ones

**Comment by shortercode** [comment]
We've started transitioning the existing templates and examples to the new built in functions, but we haven't done all of them yet.

**Comment by AshleyScirra** [comment]
I thought I already updated all the examples, but it looks like I missed the multiplayer ones for some reason. I've updated them to use built-in functions for the next release. That should be all of them updated now - let me know if you find any other examples still using the old Function object.
