### ISSUE TITLE
r158 Preview Crash

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3154]
## Problem description

I just tried preview Pop Lab example with r158. Chrome didn't answer and using %99 CPU.

![image](https://user-images.githubusercontent.com/13033837/61437139-0a2bf000-a945-11e9-92c9-0144434010f4.png)

![image](https://user-images.githubusercontent.com/13033837/61437171-1adc6600-a945-11e9-9ccc-7aeeb2f48b48.png)

## Attach a .c3p

Pop Lab example

## Steps to reproduce

1. Open Pop Lab example
2. Click preview or Debug
3. No answer

**NOTE:** r157 works fine.

**Affected browsers/platforms:** Chrome

**First affected release:** r158

**Comment by shortercode** [comment]
@AshleyScirra has already fixed this for the next release I believe. It's likely that other will discover this, so I've marked it as fixed instead of closing it.

**Comment by AshleyScirra** [comment]
Yeah, we spotted this in Demonoire already (actually Laura found it!) and it should be fixed in the next release.
