### ISSUE TITLE
Dictionary Bugs

### ISSUE THREAD

**Issue by CyrusCHAU** [Scirra/Construct-3-bugs#3156]
## Problem description

Hi, 
Dictionary - Has Key Action sometime have bug, cannot detect exactly right every time. And my project is a text based game.

Really thanks

## Attach a .c3p

[Text Game_v3.zip](https://github.com/Scirra/Construct-3-bugs/files/3407091/Text.Game_v3.zip)

## Steps to reproduce

1. 
![image](https://user-images.githubusercontent.com/51374083/61467978-22d0f000-a9af-11e9-9d10-67a04475d247.png)
Build some data in dictionary editor

2. Some key was modify / add, "3.1" "3.2".... These was a 3 dot 2.
3. 
![image](https://user-images.githubusercontent.com/51374083/61468194-76dbd480-a9af-11e9-9750-acb40b411495.png)
The event is that if next key is not a integer, then try to read the currentNumber + 0.1.

4. E.g. If Key now is 3, then if is has a 3.1, it will read 3.1 not 4.

5. This is good in "3" -> "3.1" -> "3.2", but next is not "3.3", it read "4".

6. Missed "3.3"

## Observed result

This is good in "3" -> "3.1" -> "3.2", but next is not "3.3", it read "4".

Missed "3.3"

## Expected result

"3" -> "3.1" -> "3.2" -> "3.3" - "4"

## More details

![image](https://user-images.githubusercontent.com/51374083/61468928-f027f700-a9b0-11e9-8876-22b806aa0c5f.png)

If I print a GetKey("3.3"), it can normally read. Single action can call this. But it the "Has Key" action, it cannot detect.

**Affected browsers/platforms:** 
Chrome/Firefox/Safari
Windows 7.

**First affected release:** 
first started happening in R157 stable, my project create r157.

## System details

Platform information
Browser: Chrome
Browser version: 75.0.3770.142
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 1.4 gb
Storage usage (approx): 76 mb (5.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This looks like a mistake in your events. Please see the bug report guidelines. If the Dictionary object really doesn't work, it should be possible to demonstrate that with one or two events only.

Note your project appears to rely on imprecise floating point calculations being exact. For example at one point you add 0.1 to a global number variable. Due to the limits of the CPU circuitry in dealing with fractional values, this kind of calculation is not exact - for example 0.1 + 0.2 is actually 0.30000000000000004, not 0.3. You should not rely on this kind of calculation to be exact and instead allow a small tolerance, or track two separate whole numbers for section and sub-section. I assume this is the cause of the problem in your project.
