### ISSUE TITLE
Construct 3 crashes on start

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#3157]
## Problem description

When starting Construct 3 r158 (Deskop build and Chrome), the editor immediately crashes.

## Attach a .c3p

Just open the editor.

## Steps to reproduce

1. Open the editor in r158

## Observed result

The editor crashes immediately on Chrome. On the desktop build, it takes a couple seconds before crashing.

## Expected result

The editor working.

## More details

If it can be of any help, before the first crash I tried to access the export manager, but it crashed.
Release 155 and 157 works well in Chrome. Only 158 is crashing for me.

I restarted my computer and it didn't help. 

**Affected browsers/platforms:** 

Chrome and desktop build

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Addon 'TR_Set' ACE 'foreach0' uses "variadic" parameter which is not supported in the SDK. Refer to the SDK documentation for supported types. Note support for condition/action variadic parameters has been removed - see: https://www.construct.net/en/forum/construct-3/plugin-sdk-10/variadic-parameters-removed-143189 @ Error: Addon 'TR_Set' ACE 'foreach0' uses "variadic" parameter which is not supported in the SDK. Refer to the SDK documentation for supported types. Note support for condition/action variadic parameters has been removed - see: https://www.construct.net/en/forum/construct-3/plugin-sdk-10/variadic-parameters-removed-143189 at window.ǃXBS.ǃXWI (https://editor.construct.net/r158/main.js:63:112884) at X.ǃn$ (https://editor.construct.net/r158/main.js:63:166246) at Object.ǃwSh.n.push.ǃw.ǃdSk [as ǃwis] (https://editor.construct.net/r158/main.js:63:166595) at n (https://editor.construct.net/r158/main.js:2:199266) at t (https://editor.construct.net/r158/main.js:2:199051)
Stack: Error: Addon 'TR_Set' ACE 'foreach0' uses "variadic" parameter which is not supported in the SDK. Refer to the SDK documentation for supported types. Note support for condition/action variadic parameters has been removed - see: https://www.construct.net/en/forum/construct-3/plugin-sdk-10/variadic-parameters-removed-143189 at window.ǃXBS.ǃXWI (https://editor.construct.net/r158/main.js:63:112884) at X.ǃn$ (https://editor.construct.net/r158/main.js:63:166246) at Object.ǃwSh.n.push.ǃw.ǃdSk [as ǃwis] (https://editor.construct.net/r158/main.js:63:166595) at n (https://editor.construct.net/r158/main.js:2:199266) at t (https://editor.construct.net/r158/main.js:2:199051)
Construct 3 version: r158
URL: https://editor.construct.net/r158/
Date: Fri Jul 19 2019 10:35:40 GMT+0200 (Romance Daylight Time)
Uptime: 11 s

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r158 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
See the crash message. It's a problem with a third-party addon that the developer needs to fix.
