### ISSUE TITLE
r158 HTML5 export crash when not in HTTPS

### ISSUE THREAD

**Issue by Fengist** [Scirra/Construct-3-bugs#3158]
## Problem description
Exported the attached c3p to HTML5.  Uploaded it to my server and it crashes with this error when not using HTTPS

Uncaught (in promise) TypeError: Cannot set property 'g_Zb' of undefined
    at Function.g_aQ.g_Y$ (c3runtime.js:2)
    at g_aQ.g_ab_.g_acf (c3runtime.js:2)
    at g_aQ.g_ajX.g_amb (c3runtime.js:2)
    at g_aQ.g_ajX.g_afi (c3runtime.js:2)
    at async a (workermain.js:1)

www.twistedvoid.com/antz/

Produces the error

https://www.twistedvoid.com/antz/ 

does not produce the error

## Attach a .c3p

[Antz.zip](https://github.com/Scirra/Construct-3-bugs/files/3411079/Antz.zip)

## Expected result

A visible error to the end user or an attempt to connect via https.  Instead it produces a hard crash and displays a white screen.

**Comment by AshleyScirra** [comment]
The insecure HTTP URL works fine for me here. Try clearing your browser cache.
