### ISSUE TITLE
[r29.2] Sprites bleeding

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#316]
## Problem description

So my sprites have some bleeding like so:
![bleedbug](https://cloud.githubusercontent.com/assets/7268697/26318176/f71e8cea-3f22-11e7-8860-0de2c75b5ae5.gif)

I made sure the following:
1. there's at least 1 transparent pixel at the border
2. the sprite is 1:1 size

I've changed the downscaling to low, medium and high. Different sprites were bleeding for different downscaling modes.

The only way to stop it is to set the sampling to point, but that makes the game look pixelated so it's not an acceptable workaround.

Quite similar to what was posted here: https://www.scirra.com/forum/linear-sampling-bleeds_t189842

Here's an example of this happening in the editor.
![bleedbug2](https://cloud.githubusercontent.com/assets/7268697/26318277/51e2f166-3f23-11e7-9e5e-3ff7ad51d17b.gif)

## Attach a .c3p
(update: since sprites were removed this does not reproduce the problem, please see bottom comments)
[BleedingBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1019572/BleedingBug.c3p.zip)

The bleeding on that sprite appears in the editor when zoomed to 37%. Other sprites have more visible bleeds even when the editor is zoomed to 100% when you first start the project.

![image](https://cloud.githubusercontent.com/assets/7268697/26319529/105fc822-3f28-11e7-99e9-b6a4d9df71cd.png)

## Steps to reproduce

Can't with a blank project.

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 486 mb (7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by JeFawk** [comment]
Restarting the project or changing downscale size and sampling changes the bleeding to other random sprites. However that violet WIP arch seems to always have bleeding on the bottom when downscaling is set to medium.
![image](https://cloud.githubusercontent.com/assets/7268697/26318607/6668ee28-3f24-11e7-895c-414298af019b.png)

**Comment by JeFawk** [comment]
I tried r15 as **jaydon** suggested and the bleeding still happens, on different sprites ofc.
![image](https://cloud.githubusercontent.com/assets/7268697/26319168/96ff926a-3f26-11e7-9dad-e019e5034565.png)

It's visible in the editor when I zoom out, however my game has zoom in and zoom out, so things like these appear in the final product too.

**Comment by JeFawk** [comment]
As jaydon helped we've found some more info.

The strip down project won't be helpful. The bleeding is on a different device. For some reason deleting assets on the PC, didn't delete them from the project's spritesheet (right clicked project -> sprite sheet and everything was still there). The moment I went incognito the bleeding disappeared as my spritesheet now contained only 2 sprites.

The only way to figure this out I think is for me to send over the full project since the full project reproduces the problem on my laptop.
I could send it via a private channel if it's going to be of help.

**Comment by JeFawk** [comment]
As an important update, I've checked the spritesheet and added some MORE transparent pixels around the sprites that had problems. This lead to nothing. Then I figured I should add some to the sprites around them, which turned out that it kinda fixed the problem (since it appears to random sprites, I said kinda)

It would be great though if you'd fix this, or at least add the option to include some transparent pixels as a border in the resizing tool you have in the image editor.

**Comment by AshleyScirra** [comment]
The provided project does not appear to reproduce the problem.

If you're downscaling a long way, then seams along edges are a possible consequence of using spritesheets. This is a normal result in computer graphics. We added the 'downscaling quality' option to mitigate this: try setting that to 'high'.

There's an unrelated bug where deleting objects did not remove them from the spritesheet until you closed and reopened the project, that should be fixed in r30.

**Comment by JeFawk** [comment]
I did mention that the project attached doesn't reproduce it anymore but that my full project does. Also I did mention the sprites are 1:1 so that means no downscaling.
I mentioned about the downscaling quality as well: "I've changed the downscaling to low, medium and high. Different sprites were bleeding for different downscaling modes."

Since I managed to fix it by adding a transparent 2 pixel border I guess it's kinda okey right now, though the automatic resize you have in the image editor could use some improvement (by adding himself these pixels - maybe as an option)

**Comment by AshleyScirra** [comment]
The spritesheet engine already adds a 2px transparent border. I cannot comment further without a reproducing project, I can't debug screenshots.

**Comment by JeFawk** [comment]
Give me a way to send you my project then.

**Comment by AshleyScirra** [comment]
Send it to ashley@scirra.com

**Comment by JeFawk** [comment]
I wish I could reproduce it with a test project, but it won't work. I sent you the email, thanks for your time. You could also try reproducing https://github.com/Scirra/Construct-3-bugs/issues/319 with my project as well if you got a chance.

**Comment by AshleyScirra** [comment]
As I said by email, looks exactly like a downscaling quality issue which is fixed by choosing "high quality" mode.

**Comment by JeFawk** [comment]
I've emailed you back, changing the quality didn't help much. Maybe it's related to the 1px transparency crop bug?

**Comment by AshleyScirra** [comment]
So yes, turned out there was a legit seaming case even with high-quality downscaling. Hopefully r31 should fix it!
