### ISSUE TITLE
Editor crashes when pasting a unicode arrow in a text field

### ISSUE THREAD

**Issue by ItemME** [Scirra/Construct-3-bugs#3160]
## Problem description

Editor crash when trying paste unicode arrow in a text field, see below

![image](https://user-images.githubusercontent.com/6894037/61569783-60a24700-aa89-11e9-99dd-7254a3c16746.png)

## Attach a .c3p

You can reproduce it with any project, as it's not linked to any project, but more likely the editor.

## Steps to reproduce

1. For example, create a new action for setting a new text in a global var (doesn't really matter)
2. Paste " 🠖 " this arrow
3. It crash

## Observed result

Editor crashes, for somes reasons, all I can tell you is that, it does work when you want to place that arrow in the text editor in the layout, not event sheet, without any issues.

## Expected result

It shouldn't be crashing, I assume

## More details

I'm using the latest beta for this test, and the desktop version of Construct 3

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r158/projectResources.js, line 1, col 1103866
Message: Uncaught TypeError: expected string
Stack: TypeError: expected string at Function.ǃlb (https://editor.construct.net/r158/main.js:2:92364) at t (https://editor.construct.net/r158/projectResources.js:1:402117) at a (https://editor.construct.net/r158/projectResources.js:1:402477) at Object.ǃlR_ (https://editor.construct.net/r158/projectResources.js:1:404293) at Object.ǃlRX (https://editor.construct.net/r158/projectResources.js:1:403262) at Object.ǃlXj (https://editor.construct.net/r158/projectResources.js:1:403095) at Object.ǃlXj (https://editor.construct.net/r158/projectResources.js:1:364588) at Object.ǃwb_ (https://editor.construct.net/r158/projectResources.js:1:1100758) at Object.ǃwvk (https://editor.construct.net/r158/projectResources.js:1:1103812) at HTMLDivElement. (https://editor.construct.net/r158/projectResources.js:1:1100034)
Construct 3 version: r158
URL: https://editor.construct.net/r158/
Date: Sat Jul 20 2019 00:55:48 GMT+0200 (Central European Summer Time)
Uptime: 120.1 s

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r158 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by ItemME** [comment]
I gave an arrow as an example, but can work with any unicode special characters like this one (stars etc..)

**Comment by AshleyScirra** [comment]
Can't reproduce here. No project was provided so tested with Ghost Shooter, and it correctly highlights it as an error and says "Unknown expression '🠖'".

I noticed you're using an old version of the desktop download. It's probably crbug.com/914409 which was already fixed. Please make sure you're using the latest version before reporting issues.
