### ISSUE TITLE
Properties menu UI grid is bugged

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3161]
## Problem description
Closing properties menu display tab, won't close orientation setting. But closing startup will close orientation even if display is open.
![Bugggy_UI](https://user-images.githubusercontent.com/28864889/61571782-b03f3d80-aa9e-11e9-971e-0644d9834e32.jpg)

## Steps to reproduce

1.Open new empty project
2.Navigate and open properties bar
3. Close display tab, see orientation is open.
4. Open display tab, close Startup tab, see orientation setting disappear

## Observed result
Properties bar has some glitzes

## More details

Tested even in incognite mode.

**Affected browsers/platforms:** 

**First affected release:** 
Tested r100, still same outcome
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release.
