### ISSUE TITLE
Crash when duplicating an object that's in a timeline and totally unselected in the timeline

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#3162]
## Problem description

Ctrl-clicking and dragging a sprite in the layout view that's also in a timeline and totally unselected in the timeline is causing a crash as of r158.

## Attach a .c3p

[TimelineCrash2.zip](https://github.com/Scirra/Construct-3-bugs/files/3415718/TimelineCrash2.zip)

## Steps to reproduce

1. Create a timeline
2. Create a sprite, and add it to the timeline
3. Click in the timeline view in the white space below the sprite and its properties so that neither the sprite nor its properties are highlighted in the timeline
4. Hold down ctrl, and click and drag the sprite in the layout view to duplicate it

## Observed result

Construct crashes.

## More details

**Affected browsers/platforms:** 

Only tested in latest Chrome on Windows

**First affected release:** 

Introduced in r158

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r158/components/bars/timelineBar/timelineBar.js, line 1, col 159919
Message: Uncaught TypeError: Assignment to constant variable.
Stack: TypeError: Assignment to constant variable. at p.ǃpRg (https://editor.construct.net/r158/components/bars/timelineBar/timelineBar.js:1:159919) at Array. (https://editor.construct.net/r158/components/bars/timelineBar/timelineBar.js:1:158827) at Object.ǃwiv (https://editor.construct.net/r158/main.js:2:194460) at Object.dispatchEvent (https://editor.construct.net/r158/main.js:2:192328) at Function.ǃprx (https://editor.construct.net/r158/components/bars/timelineBar/timelineBar.js:1:126347) at Function.ǃhk (https://editor.construct.net/r158/components/bars/timelineBar/timelineBar.js:1:123741) at p.ǃpdg (https://editor.construct.net/r158/components/bars/timelineBar/timelineBar.js:1:44289) at Array. (https://editor.construct.net/r158/components/bars/timelineBar/timelineBar.js:1:37159) at Object.ǃwiv (https://editor.construct.net/r158/main.js:2:194460) at Object.dispatchEvent (https://editor.construct.net/r158/main.js:2:192328)
Construct 3 version: r158
URL: https://editor.construct.net/r158/
Date: Sun Jul 21 2019 21:14:07 GMT-0700 (Pacific Daylight Time)
Uptime: 66.7 s

Platform information
Browser: Chrome
Browser version: 75.0.3770.142
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
C3 release: r158 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
