### ISSUE TITLE
Crash when pressing play in a timeline that was deleted then restored by undo while it was playing

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#3163]
If you delete a timeline while it's playing, then hit undo, hit play on the timeline again, then click inside the timeline view again, Construct crashes.

## Attach a .c3p

[TimelineCrash2.zip](https://github.com/Scirra/Construct-3-bugs/files/3415741/TimelineCrash2.zip)

This project was created in r158, not r148, by the way.

## Steps to reproduce

1. Create a sprite and timeline, and add the sprite to the timeline
2. Hit play on the timeline
3. Delete the timeline while it's still playing
4. Hit ctrl+z to undo the deletion
5. Hit play on the timeline again a couple times

## Observed result

Construct crashes

## More details

**Affected browsers/platforms:** 

Only tested on Chrome for Windows 

**First affected release:** 

Happens in r148, the earliest build where timelines were officially enabled, afaik.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r148/main.js, line 82, col 473100
Message: Uncaught TypeError: this.ǃgbO is not a function
Stack: TypeError: this.ǃgbO is not a function at a.ǃQVc (https://editor.construct.net/r148/main.js:82:473100) at U.ǃUMJ (https://editor.construct.net/r148/components/bars/timelineBar/timelineBar.js:1:4442) at U.e.ǃUZq (https://editor.construct.net/r148/components/bars/timelineBar/timelineBar.js:1:10239) at ǃk.ǃB.ǃD.ǃQXz.ǃQai.ǃQJg (https://editor.construct.net/r148/components/bars/timelineBar/timelineBar.js:1:8711) at ǃk.ǃB.ǃD.ǃQXz.ǃQai.ǃQJl (https://editor.construct.net/r148/main.js:2:485576) at ǃk.ǃB.ǃD.ǃQXz.ǃQai.ǃQom (https://editor.construct.net/r148/main.js:2:499107) at ǃk.ǃB.ǃD.ǃQXz.ǃQai.ǃQob (https://editor.construct.net/r148/main.js:2:498279) at ǃk.ǃB.ǃD.ǃQXz.ǃQai.ǃQor (https://editor.construct.net/r148/main.js:2:498832) at ǃQoK (https://editor.construct.net/r148/main.js:2:495538)
Construct 3 version: r148
URL: https://editor.construct.net/r148/
Date: Sun Jul 21 2019 21:52:44 GMT-0700 (Pacific Daylight Time)
Uptime: 30.2 s

Platform information
Browser: Chrome
Browser version: 75.0.3770.142
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
C3 release: r148 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
