### ISSUE TITLE
Log in to account every time I open it both on PC and android.  Once logged in it is fine.

### ISSUE THREAD

**Issue by winkr7** [Scirra/Construct-3-bugs#3164]
On Three windows 10 PCs using chrome and two androids (not sure version number) I have to log in every time.  This started at 1pm EST on july 21, 2019.

## Problem description

I don't get as far as a .c3p, it is just a log in problem

## Attach a .c3p

Log in with my ID (from the east coast of the USA, or perhaps everywhere).

## Steps to reproduce

1.  Bring up C3 under winkr7 ID on PC or ANdroid.  You always have to log in.
2.
3.

## Observed result

I have to log in

## Expected result

I expect to be able to use it without always logging in.  Esp when I am out of internet range.

## More details

**Affected browsers/platforms:** 

version 157 after a few days of it working fine.

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Logins are always remembered for me and we've not heard of any other users having similar issues. I don't think there's anything we can do about this, it sounds like a browser configuration blocking storage on your end.
