### ISSUE TITLE
Save the current state - not load groups state [r159]

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3165]
## Problem description

Save the current state - not load groups state

## Attach a .c3p

[SaveGameBUG.zip](https://github.com/Scirra/Construct-3-bugs/files/3417612/SaveGameBUG.zip)

## Steps to reproduce

1. Open project with Debugger
2. wait 1,2 sec
3. Click "Save the current state"
4. Double click screen
5. Load game
6. "Test" group not active.

## Observed result

Load groups state

## Expected result

not loading  groups state

**Affected browsers/platforms:**  Chrome

**First affected release:** r158/r159

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
