### ISSUE TITLE
[r159] Crash using "Find all references"

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#3166]
## Problem description

Using the contextual menu to find all references of a function when right-clicking the function block for the function causes r159 to crash.

## Attach a .c3p

http://cloud.kyatric.com/index.php/s/mFzp8aS9pXDf8Go

## Steps to reproduce

1. Open project
2. Go into event sheet 1
3. Event 96 - Right-Click, Find all references

## Observed result

Construct crashes.

## Expected result

Construct to not crash, and all the references for the function to be displayed.

## More details
**Affected browsers/platforms:** 

Happened in Chrome 75.0.3770.142
**First affected release:** 159 - no issue in r158

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'add' of undefined @ TypeError: Cannot read property 'add' of undefined at Object.ǃdZs (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:4290) at Object.ǃRoP (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:3874) at Object.ǃRoO (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2560) at Object.ǃRoX (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2008) at Object.ǃif (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:1726)
Stack: TypeError: Cannot read property 'add' of undefined at Object.ǃdZs (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:4290) at Object.ǃRoP (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:3874) at Object.ǃRoO (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2560) at Object.ǃRoX (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2008) at Object.ǃif (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:1726)
Construct 3 version: r159
URL: https://editor.construct.net/r159/
Date: Mon Jul 22 2019 15:38:31 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 1109.9 s

Platform information
Browser: Chrome
Browser version: 75.0.3770.142
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
C3 release: r159 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by QuasarX** [comment]
Same issue with sprites too maybe all others was affected too.

<details><summary><code>Error Logs</code></summary>
<pre><code>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'add' of undefined @ TypeError: Cannot read property 'add' of undefined at Object.ǃdZs (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:4290) at Object.ǃRoT (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2819) at Object.ǃRoO (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2405) at Object.ǃRoX (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2008) at Object.ǃif (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:1726)
Stack: TypeError: Cannot read property 'add' of undefined at Object.ǃdZs (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:4290) at Object.ǃRoT (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2819) at Object.ǃRoO (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2405) at Object.ǃRoX (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2008) at Object.ǃif (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:1726)
Construct 3 version: r159
URL: https://editor.construct.net/r159/
Date: Tue Jul 23 2019 13:12:06 GMT+0300 (GMT+03:00)
Uptime: 217 s

Platform information
Browser: Chrome
Browser version: 75.0.3770.142
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
C3 release: r159 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</code></pre></details>

**Comment by AshleyScirra** [comment]
Fixed for next release. Will leave open since I imagine others will run in to this.

**Comment by BonzerKitten7** [comment]
I'm also having problems when I try it with the gamepad plugin. When this will be fixed?

<details><summary>Error logs</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'add' of undefined @ TypeError: Cannot read property 'add' of undefined at window.ǃiA.ǃdZs (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:4290) at window.ǃiA.ǃRoT (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2819) at window.ǃiA.ǃRoO (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2405) at window.ǃiA.ǃRoX (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2008) at window.ǃiA.ǃif (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:1726)
Stack: TypeError: Cannot read property 'add' of undefined at window.ǃiA.ǃdZs (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:4290) at window.ǃiA.ǃRoT (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2819) at window.ǃiA.ǃRoO (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2405) at window.ǃiA.ǃRoX (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:2008) at window.ǃiA.ǃif (https://editor.construct.net/r159/components/bars/findReferencesBar/findReferencesBar.js:1:1726)
Construct 3 version: r159
URL: https://editor.construct.net/r159/
Date: Thu Jul 25 2019 12:26:18 GMT-0300 (Horário Padrão de Brasília)
Uptime: 66.9 s

Platform information
Browser: Chrome
Browser version: 75.0.3770.142
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
C3 release: r159 (beta)
Language setting: pt-BR

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by XHXIAIEIN** [comment]
I using "Find all references" in Start page anyone ‘Game Demos’, and this problem also happened.
