### ISSUE TITLE
Comment formatting bugs out when changing theme

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3168]
## Problem description
Case when i changed theme and comment formatting bugged out. It pretty rare and only had this happening once long time ago. But this time I took screenshots. Not sure what causes it and problem does not have big impact, but it could affect and cause problems somewhere else!! I don't have insight on C3, so it's more simple report that stuff like this happens, and it's developers that should know what impact this could have and what else could it affect.
Possible cause could be how scripts are loaded in etc.
1 Image. How bug shows up
2 Image. How it looks when selected
3 Image. How it looks correctly.
![ThemeLoadingBug](https://user-images.githubusercontent.com/28864889/61646984-fff75200-acb4-11e9-8425-49ed8da799be.jpg)

**Comment by AshleyScirra** [comment]
Please always provide a project when filing issues. It speeds up dealing with bug reports (essential as we're a small team dealing with thousands of reports) and is essential for us to see what you're seeing.
