### ISSUE TITLE
ERROR RUNTIME.CALLFUNCTION

### ISSUE THREAD

**Issue by marcelokohl** [Scirra/Construct-3-bugs#3169]
Calling an event sheet function via scripting but it returns error.

Function print:
https://s1.construct.net/images/v684/uploads/articleuploadobject/0/images/29681/mx2rzqx.png

Error print:
https://s1.construct.net/images/v684/uploads/articleuploadobject/0/images/29682/6f8oyts.png

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise we cannot help.
