### ISSUE TITLE
Crash when closing the sprite editor

### ISSUE THREAD

**Issue by narFnarF** [Scirra/Construct-3-bugs#317]
## Problem description
Construct 3 crashed when I closed the sprite editor after having created a new sprite.
This is the 1st time I get this issue. I was not able to reproduce it. I will update if I get this issue again.

## Attach a .c3p
[peggle rpg.zip](https://github.com/Scirra/Construct-3-bugs/files/1019810/peggle.rpg.zip)
The attached .c3p was saved from the crash screen. The object "canon" is the object I had just created.

## Steps to reproduce
No clear steps, as this is the 1st time it happens and I was not able to reproduce. I will update later if I find how to reproduce.
1. I created a new sprite called "canon" by right-clicking on the Object folder in the Project panel
2. I selected the position of the new object on the layout
3. The sprite editor appeared as normal
4. I played with the color picker for a while, to pick a good color
5. I used the paint bucket to fill the entire object with dark green
6. I closed the sprite editor
7. Crash occurred.

## Observed result

Construct 3 crashes.

## Expected result

The new sprite is saved and appears on the layout.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r29-2/main.js, line 61, col 128130
Message: Uncaught Error: image sprite collection needs rebuilding
Stack: Error: image sprite collection needs rebuilding at ie.ǃlU (https://editor.construct.net/r29-2/main.js:61:128136) at oe.ǃlU (https://editor.construct.net/r29-2/main.js:61:199878) at a.ǃCL.ǃoF (https://editor.construct.net/r29-2/main.js:61:396446) at a.ǃCL.ǃoF (https://editor.construct.net/r29-2/plugins/sprite/plugin.js:1:8198) at a.ǃCL.ǃnN (https://editor.construct.net/r29-2/plugins/sprite/plugin.js:1:7998) at ne.ǃnN (https://editor.construct.net/r29-2/main.js:61:216943) at me.ǃnN (https://editor.construct.net/r29-2/main.js:61:252468) at ae.ǃnN (https://editor.construct.net/r29-2/main.js:61:238138) at window.ǃQE.ǃul (https://editor.construct.net/r29-2/components/editors/layoutView/layoutView.js:1:6830) at ǃuG.B (https://editor.construct.net/r29-2/components/editors/layoutView/layoutView.js:1:2079)
Construct 3 version: r29.2
URL: https://editor.construct.net/index.html
Date: Mon May 22 2017 13:47:13 GMT-0400 (Est (heure d’été))
Uptime: 67119.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 745 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Not enough information to do anything useful about this.
