### ISSUE TITLE
Unhandled exception Uncaught Object object And 

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#3170]
## Problem description

Not sure tbh, everything worked fine last night, saved fine, now when I open it on the same build (latest table build) I get errors 10 seconds or so after opening the project.

## Attach a .c3p

Is the project public or private once posted here? I have spent quite a while on it, would need it to be private.

## Steps to reproduce

1. Open project

## Observed result

10 seconds then the error.

## Expected result

Nothing. I just loaded the project, I expect it to load and idle until I do something.

## More details
Worked last night, saved last night. No changes since last night that I can recall. 
1) One of the errors is not repeatable (Unhandled exception Uncaught Object object)
2). The error I posted here is understandable in how it could happen however, it traps the user into not being able to use their project if it lets you save with the error (out of scope variable) but not load with that error.
3). Maybe it's too early to say but so far firefox does not prohibit the user from opening and using the project despite this error, unlike chrome.

Chrome: not working
Edge: project doesn't make it past loading stuck at 1.5%
Firefox: no error if I do nothing, I haven't tested further than just letting it load and idle as that is where I experienced the problem. ***After further exploration, firefox allows me to load and open the project but what appears to be the affected event sheet never loads. (stuck at "loading...")

r157 (stable)

## System details

First Error: 

Error report information
Type: unhandled rejection
Reason: Unknown expression 'tabButtonVerticalSeperationDistance': This is not a system expression or variable name in this scope.
Construct 3 version: r157
URL: https://editor.construct.net/
Date: Tue Jul 23 2019 08:52:57 GMT-0700 (Pacific Daylight Time)
Uptime: 28.9 s

Platform information
Browser: Chrome
Browser version: 75.0.3770.142
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon(TM) Vega 8 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

Error 2:

If I manage to click on what I think is the affected event sheet before the idle error occurs:

Error report information
Type: unhandled exception
File: https://editor.construct.net/r157/components/editors/eventSheetView/eventSheetView.js, line 1, col 12566
Message: Uncaught TypeError: Cannot read property 'ǃvm' of null
Stack: TypeError: Cannot read property 'ǃvm' of null at o.ǃus (https://editor.construct.net/r157/components/editors/eventSheetView/eventSheetView.js:1:12566) at o.ǃLu (https://editor.construct.net/r157/components/editors/eventSheetView/eventSheetView.js:1:8047) at Array. (https://editor.construct.net/r157/components/editors/eventSheetView/eventSheetView.js:1:2714) at ǃp.Event.ǃpxO.ǃpxF (https://editor.construct.net/r157/main.js:2:194070) at ǃp.ǃEh.ǃXA.ǃpVx.dispatchEvent (https://editor.construct.net/r157/main.js:2:191938) at ǃp.ǃEh.ǃXA.ǃpVx.ǃLu (https://editor.construct.net/r157/main.js:2:266223) at ǃp.ǃEh.ǃEHE.ǃEHm (https://editor.construct.net/r157/main.js:52:46243) at ǃp.ǃEh.ǃEHY.ǃzA (https://editor.construct.net/r157/main.js:52:46981) at https://editor.construct.net/r157/main.js:52:46389
Construct 3 version: r157
URL: https://editor.construct.net/
Date: Tue Jul 23 2019 09:08:05 GMT-0700 (Pacific Daylight Time)
Uptime: 22.5 s

Platform information
Browser: Chrome
Browser version: 75.0.3770.142
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon(TM) Vega 8 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
I'm afraid in general we cannot do anything about reports unless they follow the bug report guidelines. This includes providing a project, reliable steps to reproduce, and verifying the issue reproduces in the latest release (r159).

**Comment by OneRepCloser** [comment]
Hey Ashley are the projects we post here to reproduce public?

**Comment by AshleyScirra** [comment]
Yes. See the bug report guidelines about what to do if you don't want to share your project.
