### ISSUE TITLE
Issue with nw.js window size with web worker

### ISSUE THREAD

**Issue by RorySoh** [Scirra/Construct-3-bugs#3171]
## Problem description

If you use nw.js to set resolution of the window (it doesn't work too) while webworker is on, it gives an error and the game doesn't continue loading. Sometimes running another webpage in chrome refreshes it and it loads up.

## Attach a .c3p

https://streamable.com/b426z

## Steps to reproduce

https://snag.gy/rC3ZQP.jpg

1. Add nw.js to your project
2. On startup change window size
3. Export with nw.js any version

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by gedaerm** [comment]
The same happens when using other nw.js actions, like "set window resizable". Webworker off: works, webworker on: fails.

**Comment by AshleyScirra** [comment]
No project was attached. Please follow the bug report guidelines to ensure we can investigate your report.
