### ISSUE TITLE
Fail to open save file after edit timeline property

### ISSUE THREAD

**Issue by jarnMod** [Scirra/Construct-3-bugs#3172]
#Problem description
This bug corrupts save file and it cannot be opened.

With an existing timeline animation, if one of the object property "result mode" is changed and the file is saved, the save file will be corrupted and cannot be opened. An error [TypeError: Cannot read property 'ǃOY' of undefined] or similar such as !oW will be detected in Chrome console upon trying to open the save file.

I've lost 2 days worth of work. This information is acquired with a lot of coffee and tears. Please, make good use of it.

## Attach a .c3p
https://www.dropbox.com/s/a3ehxdtnt5bcmfb/Crash.c3p

## Steps to reproduce

1. Open the attached project file
2. Click project structure Timeline > New Folder > titleButtons to open the timeline for edit
3. Click the X property of the first object in the timeline. 
4. Change "result mode" in property track from "Absolute" to "Relative"
5. Save the project as another file 

## Observed result

The new save file, which "result mode" is changed, will be corrupted and cannot be opened.

## Expected result

The save file will be opened as normal

## More details

Tested using cloud storage and local file save, all corrupt
Tested using Chrome and Edge, both produce a corrupted file
I've recorded the issue to a video clip if you want to see:
https://www.dropbox.com/s/f367x3macnfg4j7/C3CrashTimelineSave.flv?dl=0

**Affected browsers/platforms:** 
Chrome and Edge on Win10

**First affected release:** 
C3 Stable 157

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.142
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.4 gb
Storage usage (approx): 857 mb (11.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This is fixed. Your file should open properly in the next beta release.

Unfortunately there is nothing I can do to help in the current version. Thanks for reporting.

**Comment by jarnMod** [comment]
Thanks Diego. Don't worry about my file. I can handle that. At least it's fixed.
