### ISSUE TITLE
Construct 3 theme graphics and text are blurry

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#3173]
## Problem description

Construct 3 (desktop build) theme graphics and text, are blurry and makes it difficult to work. Only at increased scale icons are shown correct (text problem is minor but remains) but fonts are extremely big to work. In Construct 2, graphics and text are nice, sharp and clean. Also, I think that going from default scale to decreased scale makes big difference, maybe there should be a smaller change, a"mid" condition.

Click on the images bellow in order to see clearly the problem and the difference between C2 and C3!

## Observed result

C3 default scale: (Blurry icons and most of the text)
![C3 default scale](https://user-images.githubusercontent.com/53188782/61795948-2b04b180-ae2d-11e9-8569-e10be2ecafa7.jpg)

C3 increased scale: (Icons are ok and sharp, some letters still blurry)
![c3 increased scale](https://user-images.githubusercontent.com/53188782/61795956-2cce7500-ae2d-11e9-9eb4-e938f280b1ba.jpg)

C3 decreased scale: (Blurry)
![C3 decreased scale](https://user-images.githubusercontent.com/53188782/61795926-20e2b300-ae2d-11e9-9802-18faafd6093c.jpg)

## Expected result

![C2](https://user-images.githubusercontent.com/53188782/61795913-1cb69580-ae2d-11e9-91c3-38625a304f6c.jpg)

## More details

**Affected browsers/platforms:** C3 desktop build

C3 r157

**First affected release:** 

## System details

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.7 gb
Storage usage (approx): 577 mb (7.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
C2 used bitmap icons and C3 uses SVG icons since it scales better, especially on high-DPI displays, which C3 is optimised for; however SVG antialiasing can make them look softer on low-DPI displays. This is just the text and SVG rendering done by the browser so I don't think we can do anything about this, and IIRC nobody else has mentioned this since C3 was first released in 2017, so I don't think it's a major issue.
