### ISSUE TITLE
Problem in admob (Banner)

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#3176]
## Problem description

I was tinkering with admob addon and i encountered a bug.It is in banner section of addon. After hiding the banner,it does not appear again
## Attach a .c3p

https://drive.google.com/open?id=1Hl1p97gCvfo1Z3RtXd0dyxLV1T2IhcRI
## Steps to reproduce

Simple,i have given the same code.Just remember one thing.There are three buttons(sprites used as buttons)."B" stands for banner."I" stands for interstitial and "V" stands for video.
Export my file to debug apk.Now after everything, launch the app.Wait for 5-6 seconds(it takes time to load data).Then click on "B".The banner will appear at the bottom of the screen.Now again press the banner button("B").The banner will hide.Till now everything is going fine
Now again press the "B" button. Alas,nothing happens 
## Observed result
After a cycle,it doesn't works
## Expected result
"B" button was designed to show/hide the banner accordingly
If "B" is pressed and banner is not there then show the banner
If "B" is pressed and banner is there,show the banner
## More details
Platform information
Browser: Chrome
Browser version: 75.0.3770.142
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 9.8 gb
Storage usage (approx): 332 mb (3.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

I am using latest version of construct 3

**Comment by shortercode** [comment]
Once a banner has been hidden it cannot be re-shown, you have to request a new one.

Your events for interstitial and rewarded video adverts bypass this by immediately trying to load a new advert if one isn't loaded (i.e. after it has been hidden)
