### ISSUE TITLE
Two Effects On same Layer Causing Layer to Flip Vertically

### ISSUE THREAD

**Issue by shubhamrathi9** [Scirra/Construct-3-bugs#3177]
## Problem description

Two Effects On same Layer Causing Layer to Flip Vertically
Its happening with combinations of Toon/HardLight/Exclusion/Screen to name a few, i did not checked many other effects.

## Attach a .c3p

[LayerFlipTest](https://www.construct.net/out?u=https%3a%2f%2fdrive.google.com%2ffile%2fd%2f10tQb-o-PJMT2JJ7Q1e6q79uHwtwqIEkv%2fview%3fusp%3dsharing)

## Steps to reproduce

1.Run the File in Preview Mode
2.Observe Flipped Layer

## Observed result

Observe Flipped Layer

## Expected result

Normal Unflipped Layer with both effects intact

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Looks like the same issue as #2591
