### ISSUE TITLE
Form is not responding When Cancel Delete form project

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#3178]
## Steps to reproduce
1. I selected an object and accidentally pressed the delete key.
2. I pressed the Esc key quickly.
3. The form darkens and no response...
[Delete form project?](https://i.imgur.com/iivWRiS.png)

## More details
**Affected browsers/platforms:** Chrome, macOS
**First affected release:** r159

[Console](https://i.imgur.com/38FP0pz.png)

**Comment by XHXIAIEIN** [comment]
The most important thing, I can't save the project!!!

**Comment by XHXIAIEIN** [comment]
HHHHHH, I deleted the dialog from Elements. It works again!!!

**Comment by shortercode** [comment]
When filing bug reports please take the time to complete the whole form, the details are important to help us diagnose issues.

I followed the instructions you gave and have been unable to replicate the issue. If you follow these instructions from a clean start do you see the issue every time?

1. Create new project
2. Add sprite
3. Select sprite in project tree
4. Press "delete" key
5. Immediately press the "esc" key
