### ISSUE TITLE
go back bug C3 r159 Chrome browser

### ISSUE THREAD

**Issue by aulavirtualmusica** [Scirra/Construct-3-bugs#3182]
the go back condition of the browser does not work in Chrome. nor if I run it as javascript.
 This happens with the C3 engine in C2 running correctly.

Tested in r159 on Chrome.

Will this bug be fixed ???

**Comment by shortercode** [comment]
Please read the [guidelines](https://github.com/Scirra/Construct-3-bugs/blob/master/README.md) before submitting an issue:

> ## Read these guidelines or your bug may be closed!
> Many users file bugs which are useless because they don't contain enough information for us to do anything about them. We just close these bugs without investigating them. Please follow these guidelines to avoid having your bug closed and help make sure we can fix the bug you're reporting.

> ## Use the bug report template
> The bug submission page is pre-filled with a template. We need all this information to help you. Do not delete it. Please provide as much of the requested information as you can, including the system details or crash report information with every report.
