### ISSUE TITLE
Keyboard shortcuts interfering with the game

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3183]
## Problem description
if I bind keys to shift and ctrl and alt and X or C or V 
( since when in a regular WASD configuration your pinky and thumb fingers are free and they can press those keys while WASD is pressed)
then it sometimes trigger browser shortcuts like ctrl+shift+c opens the console and the game loses focus and the player loses inputs, or worse ctrl+w then the browser window closes without warning

## Steps to reproduce

1.press and hold ctrl
2. press W

## Observed result

the browser window closes
## Expected result

for the game to play as usual and so whatever those combined inputs are supposed to do in the game
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
It would be useful to see an example project; are you using "is key pressed" or "on key pressed"?

I copied this from the manual.

> BROWSER SHORTCUT KEYS
> In some browsers, some keys are shortcuts for browser actions. For example, space bar sometimes is a shortcut to scroll down the page. If any events exist for On key pressed with a given key, Construct blocks the browser from performing its normal action. For example, if you wish to prevent space bar scrolling down the page, add an empty On Space pressed event, if you don't have one already.

**Comment by eleanorawesome** [comment]
https://puu.sh/E0ALs/68fd35c2fc.c3p

what the manual says doesnt work, probably because it'S a multi key thing ?

**Comment by AshleyScirra** [comment]
Browser shortcuts like Ctrl+W cannot be overridden, to avoid pages abusing users by blocking them from performing key actions. In this case Ctrl+W is the shortcut to close the tab which pages are not allowed to prevent, to ensure the user can always close the tab whenever they want.
