### ISSUE TITLE
Editor scrolling issues in Safari on macOS when moving mouse cursor

### ISSUE THREAD

**Issue by quackgyver** [Scirra/Construct-3-bugs#3185]
When using the Construct 3 editor in version 12.1.1 of Safari on version 10.14.5 of macOS, scrolling down in any panel, page or view that has a vertical scrollbar causes the scrolling to immediately scroll back to the top again after the downwards-scrolling has stopped, as soon as the mouse cursor is moved. 

This makes it impossible to see what's outside of the bottom side of the viewport in the event editor or any of the panels, as it scrolls back to the top as soon as you scroll down in any of those contexts and move the mouse cursor.

## Steps to reproduce 

1. Use an Apple computer with the latest version of macOS and Safari installed. 
2. Navigate to http://editor.construct.net
3. Create a new project. 
4. Scroll to the bottom of any window with a vertical scroll bar - for instance the item list in the project "Properties" panel. 
5. Wait until the web page is done scrolling to the bottom. 
6. Move the mouse cursor over the panel. 

## Observed result

The panel scrolls to the top again. 

## Expected result

The panel does not scroll to the top again. 

## More details
- This happens regardless of any c3p project no matter what the circumstances. 
- It does not happen in other browsers on macOS. 
- It does not happen in the cloud project picker dialogue on the start page. 
- I can't verify whether the bug applies to the main list of contents on the start page (i.e. the content section that is controlled by the left side bar) because I can't scroll at all in that view.

**Affected browsers/platforms:** Safari on macOS. 

**First affected release:** No idea, but the problem persists in version r157.

**Comment by nukvar** [comment]
I have the same problem

**Comment by shortercode** [comment]
@nukvar please add a thumbs up reaction to comments instead of adding "me too" style replies. Issues with too many comments can be difficult to follow.

**Comment by AshleyScirra** [comment]
It looks like a Safari bug - no other browsers do it and there's no reason for Safari to change the scroll position when you move the mouse, but it does. I tried in Safari tech preview 89 and it appears to be fixed. So it looks like something Apple already fixed, and we just have to wait for the next version of Safari to come out.

**Comment by quackgyver** [comment]
This seems to be an issue with the UI framework or UI code that Construct 3 uses since it's not a behavior that is present in the default overflow: scroll-behavior in Safari. This is supported by the fact that if the bug-affected element's element type is changed and all of its attributes are removed (so that it can no longer be targeted by the UI framework), it suddenly works as expected.

I see no evidence that this bug lies with Safari when it is just as likely (if not more) that it lies with Construct 3.

**Comment by AshleyScirra** [comment]
The fact it works in the next version of Safari, and all other major browsers, essentially proves this is a Safari 12.x bug.

**Comment by quackgyver** [comment]
I don't think that's a reasonable response for three reasons: 

1) Vendors/user agents handle erroneous code differently. The fact that something works as intended in multiple browsers but doesn't in another is in no way an indication that the error doesn't lie in the code. The fact that the error is resolved in a future beta version of a browser is also not an indication that the error doesn't lie in the code. It could just as easily mean that the code breaks conventions and that all but one browser interprets is as expected. 

2) Scrolling in HTML elements work perfectly fine in Safari, but for some reason doesn't in Construct 3. This indicates that there's something in Construct 3's frontend code that actively interferes with the scrolling or handles scrolling differently from the standardized or expected behavior. 

3) It's virtually *impossible* to build a page where scrolling doesn't work as intended unless you actively interfere with the scrolling.

**Comment by quackgyver** [comment]
I can confirm that the issue has been resolved in the latest version of Safari based on some superficial testing, by the way. I'll keep testing and report back if the bug persists in some manner.
