### ISSUE TITLE
Please add cordova-plugin-screen-orientation to whitelist [Android/iOS]

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#3187]
## Problem description

Two problems with the build-service from scirra:

1. When i export any android-project (debug-apk) with the build-service from scirra and add this to my plugin:

> this._info.AddCordovaPluginReference(
>             {
>                 id: "cordova-plugin-screen-orientation"
>             });

The cordova-plugin-screen-orientation api is missing on the exported apk!

2. The same as above, but when i export as a iOS-XCode-Project, the plugin (and any reference) is missing too.

With manually compile a apk with cordova cli and node.js (https://www.npmjs.com/package/cordova) it works! Its a build-service problem from scirra? :)

## Attach a .c3p & Steps to reproduce

You don't need a c3p, but you can use this plugin to see the problem with the build-service from scirra:
https://www.construct.net/en/make-games/addons/311/cordova-screenlock-c3-runtime

+ Build with scirra-build-service and again directly with cordova node.js to see what happens.

## Observed result

cordova-plugin-screen-orientation is not on the whitelist on build-service from scirra

## Expected result

cordova-plugin-screen-orientation works with build-service from scirra

**Affected browsers/platforms:** 

+ Tested on Android 8 ( samsung galaxy s7 )

**First affected release:**

r159

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r159 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 144 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
@masscube the build service has a whitelist for cordova plugins, I'm guessing the one your requesting is not on it. I will have to perform a review of the plugin, I will get back to you here once I have made my decision.

**Comment by masscube** [comment]
Any news about this? For me is very important, the exported xcode project have the cordova-plugin-screen-orientation api. Currently, the xcode project don't have this api.

**Comment by shortercode** [comment]
Apologies for the delay, we are investigating an improvement to how we deal with dependencies on the build server. It should be complete soon, and this will be resolved immediately after.

**Comment by shortercode** [comment]
The dependency update has been delayed, refer to my comment on #3130 about that. In the meantime I've added this plugin to the existing whitelist, so closing this issue.
