### ISSUE TITLE
Desktop build r159 is unstable

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#3188]
## Problem description

Desktop build is unstable and crashes quite often. Even with only a small new project loaded.
Crash occurs about every 15 minutes to 1 hour.

## Attach a .c3p

[crash_desktop.zip](https://github.com/Scirra/Construct-3-bugs/files/3464347/crash_desktop.zip)

## Steps to reproduce

Sorry I don't really have steps to reproduce here. I just work on the project, and it crashes after 15 minutes to 1 hour.

## Observed result

Editor crashes

## Expected result

No crash

## More details

At first I thought it was due to the fact that I'm using unsupported 3rd party addons, but even after removing them, the editor is still unstable. At the very least, the editor is not telling me to uninstall unsupported addons as it was doing before I uninstalled them. I still wonder if it is not related to that, since in r158 the editor crashed every time due to unsupported addons.

One time, the editor crashed, then when restarting it, all the tabs where closed. Only the main window remained. When I tried to open the tabls with view/bars/properties, nothing happened at all.
When I restarted it again, only the tilemap bar was opened (floating) for some reason. Every time I tried to close it, the editor crashed, with the log files mentionned below.

the other times the editor crashed without nothing else special happening.

**Affected browsers/platforms:** 

Desktop build r159

**First affected release:** r159

## System details

As the editor crashed multiple times, I join 2 crash reports.

<details><summary>View details</summary>
(This report is what I have now, no other tab than the main tab open, the tilemap is open even though I never used it and when I try to close it, it crashes)

Error report information
Type: unhandled exception
File: https://editor.construct.net/r152/main.js, line 159, col 59960
Message: Uncaught Error: layout view manager unavailable
Stack: Error: layout view manager unavailable at window.ǃOZx.ǃOh (https://editor.construct.net/r152/main.js:159:59966) at o.ǃiu (https://editor.construct.net/r152/components/bars/tilemapBar/tilemapBar.js:1:3785) at o.ǃV (https://editor.construct.net/r152/components/bars/tilemapBar/tilemapBar.js:1:1228) at Array.window.ǃwz.constructor.ǃciX (https://editor.construct.net/r152/main.js:159:36624) at ǃc.Event.ǃcWB.ǃcWD (https://editor.construct.net/r152/main.js:2:193402) at ǃc.ǃOi.ǃrT.ǃcxx.dispatchEvent (https://editor.construct.net/r152/main.js:2:191270) at ǃc.ǃOi.ǃrT.ǃcxx.ǃaF (https://editor.construct.net/r152/main.js:2:324100) at ǃc.ǃOi.ǃrT.ǃcxx.ǃaF (https://editor.construct.net/r152/main.js:2:329330) at ǃc.ǃOi.ǃrT.ǃcxx.ǃaF (https://editor.construct.net/r152/main.js:2:340038) at ǃc.ǃOi.ǃrT.ǃcxx.ǃcri (https://editor.construct.net/r152/main.js:2:336421)
Construct 3 version: r152
URL: https://editor.construct.net/r152/
Date: Fri Aug 02 2019 07:38:16 GMT+0200 (Romance Daylight Time)
Uptime: 3.8 s

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r152 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

<details><summary>View details of crash 2</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.ǃd.ǃEW (https://editor.construct.net/r159/main.js:2:92364) at Function.ǃRq (https://editor.construct.net/r159/main.js:159:130423) at e (https://editor.construct.net/r159/main.js:159:117375) at ǃd.ǃh (https://editor.construct.net/r159/main.js:159:118084)
Stack: TypeError: expected string at Function.ǃd.ǃEW (https://editor.construct.net/r159/main.js:2:92364) at Function.ǃRq (https://editor.construct.net/r159/main.js:159:130423) at e (https://editor.construct.net/r159/main.js:159:117375) at ǃd.ǃh (https://editor.construct.net/r159/main.js:159:118084)
Construct 3 version: r159
URL: https://editor.construct.net/r159/
Date: Sat Aug 03 2019 23:01:59 GMT+0200 (Romance Daylight Time)
Uptime: 9001.6 s
Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r159 (beta)
Language setting: en-US
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by DiegoScirra** [comment]
@RabloGames 

What are you auto **Save & backup** settings? I am not quite sure what is happening here, but maybe it is the auto save that is failing, that would explain a seemingly random crash at around 15 minutes of use.

**Comment by RabloGames** [comment]
I think it's the default values. Here they are :
![image](https://user-images.githubusercontent.com/29117306/62676881-8a75cc00-b9ac-11e9-81b1-56426b5c887b.png)

I'll try deactivating the auto save to see if it helps.
Thanks!

**Comment by AshleyScirra** [comment]
The first crash uses an old C3 version (r152, latest is r159), and both crashes use an old NW.js version (0.30, latest is 0.39.0). Please only report issues that occur in the latest versions to ensure they're not things we've already fixed. Additionally as per the bug report guidelines we need reliable steps to reproduce issues to be able to investigate.
