### ISSUE TITLE
[r29.2] NWjs export crashes C3 if the project is big (> 59 mb, 3477 events, 3407 conditions, 6202 actions, etc)

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#319]
## Problem description

My bigger project crashes the NWjs export whilst smaller ones work. I tried on my desktop and laptop, and also different NWJS versions.

These are the statistics of my big project:
Layouts: 16
Event sheets: 49
Total number of events: 3477
Total number of conditions: 3407
Total number of actions: 6202
Object types: 467
Families: 16

## Attach a .c3p

I would agree to send the project over for investigations privately.

## Steps to reproduce

1. get the project from me :)
2. load it 
3. export as nwjs with only the 2 windows exports 32 and 64, no minify, no deduplicate and no recompress images

## Observed result

Notice it crashes on different machines

![image](https://cloud.githubusercontent.com/assets/7268697/26322782/229c8036-3f35-11e7-84c7-14598922c83f.png)

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃGI' of undefined @ TypeError: Cannot read property 'ǃGI' of undefined at ǃC.ǃmeA.ǃVE.ǃmIs (https://editor.construct.net/r29-2/exporters/nwjs/exporter.js:1:17971) at ǃmhn.then.G (https://editor.construct.net/r29-2/exporters/nwjs/exporter.js:1:17476) at 
Stack: TypeError: Cannot read property 'ǃGI' of undefined at ǃC.ǃmeA.ǃVE.ǃmIs (https://editor.construct.net/r29-2/exporters/nwjs/exporter.js:1:17971) at ǃmhn.then.G (https://editor.construct.net/r29-2/exporters/nwjs/exporter.js:1:17476) at 
Construct 3 version: r29.2
URL: https://editor.construct.net/index.html
Date: Mon May 22 2017 20:59:55 GMT+0300 (GTB Daylight Time)
Uptime: 96.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
It crashes because the project has no icons :P fixed for r31 (although the exported project won't have any icon), and you should be able to work around now by adding an icon to the icons folder (e.g. icon-256.png).

**Comment by JeFawk** [comment]
hahahahaha
