### ISSUE TITLE
c3runtime gets loaded at root instead of at relative path

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3190]
## Problem description

Hi, I've been trying to work with Airconsole on C3 but I've encountered issues. The 

## Attach a .c3p

Not a c3p but an exported project
[Output.zip](https://github.com/Scirra/Construct-3-bugs/files/3467120/Output.zip)

## Steps to reproduce

1. Export a project
2. Put it in a folder
3. Upload folder to website

Already hosted the files at http://testairconsole.surge.sh/screen 

## Observed result

![image](https://user-images.githubusercontent.com/11213825/62457721-ae9e9680-b77b-11e9-8ce4-f5ae25428749.png)
For some reason, c3runtime.js only seems to be gathered from the root and it breaks as long as the script folder isn't at root

## Expected result

Should work.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by daedeloth** [comment]
The problem is not really related to the relative path, but to the base href that is set in the index file. The base href seems to be ignored when loading the dependencies.

**Comment by AshleyScirra** [comment]
The export is modified to alter the base href. This is not currently supported. If you need it, please file a feature request. In the mean time ensure the folder structure is preserved.

**Comment by daedeloth** [comment]
Since all other files are loaded in the correct way, and only the runtime file is loaded at the 'wrong' location, I don't consider this a feature, but a bug.
