### ISSUE TITLE
r157+ IOS iframe touch issues

### ISSUE THREAD

**Issue by dabontv** [Scirra/Construct-3-bugs#3191]
## Problem description

In release r157+ the touch event is not fired if the game is inside of an iframe on IOS (tested on iPhone and iPad with v12.3 and v12.4)

## Attach a .c3p
Using default touch panning build

## Steps to reproduce
Export and place the build in an iframe:

r148 (working): http://supergames.esy.es/dom/bulletfire3/iframe_touch_r148/
r157 (not working): http://supergames.esy.es/dom/bulletfire3/iframe_touch_r157/

## Observed result

r157: No touch events fired on IOS (tested on iPhone and iPad with v12.3 and v12.4)

## Expected result

Touch events should trigger, you should be able to pan screen

**Comment by dabontv** [comment]
Still not working in r160 (test: http://supergames.esy.es/dom/bulletfire3/iframe_touch_r160/)

**Comment by AshleyScirra** [comment]
This looks like a weird quirk of Safari... it looks like it first regressed in r151 when we just changed the target of an event further up the heirarchy, and this appears to have blocked touch input in an iframe. I just put back the original bit of code used before r151 in addition to our new code and it gets it working again. I don't know why that works, but it's done for the next release...
