### ISSUE TITLE
External event sheet window crash after editing, pressing backspace and CRTL + Z

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#3194]
## Problem description

Construct will crash if you make an event sheet an external window and start editing it. 

I discovered this while I was trying to refactor my enemy AI characters and needed to compare the spreadsheets like this. I was editing a comment and needed to backspace something and then this happened.

## Attach a .c3p

https://i.imgur.com/N2Pnmjw.png

## Steps to reproduce

1. click the event sheet window tab and drag it off Construct so it creates an external window.
2. Highlight the comment.
3. Press backspace.
4. Press the combination CRTL + Z to undo.

## Observed result

When pressing backspace the blocks would disappear as if you deleted them. 
After pressing the CRTL + Z combination to undo, Construct will crash.

## Expected result

No deletion of blocks with the backspace key.
No Crash.

## More details
In order to reproduce this crash, you need to separate the event sheet from construct so it's on it's own window, like this: https://i.imgur.com/N2Pnmjw.png (there are two of them in this screenshot but you can do it with just one).

If you have trouble reproducing the bug, you may have to edit the event sheet a bit (moving things around, deleting things, redoing things, adding comments, undoing those, etc, it will eventually crash).

**Affected browsers/platforms:** Desktop

**First affected release:** r159

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r159/components/editors/eventSheetView/eventSheetView.js, line 1, col 61803
Message: Uncaught TypeError: Cannot read property 'scrollHeight' of null
Stack: TypeError: Cannot read property 'scrollHeight' of null at Object.ǃISj (https://editor.construct.net/r159/components/editors/eventSheetView/eventSheetView.js:1:61803) at HTMLTextAreaElement. (https://editor.construct.net/r159/components/editors/eventSheetView/eventSheetView.js:1:61495)
Construct 3 version: r159
URL: https://editor.construct.net/r159/
Date: Tue Aug 06 2019 19:10:00 GMT+1000 (Australian Eastern Standard Time)
Uptime: 46.9 s

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r159 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
No project was provided so I cannot follow your steps. I tried with Ghost Shooter and it seemed to work fine. Please always follow the bug report guidelines to ensure we can investigate the issue you are reporting.

**Comment by LukeNecklace** [comment]
Oh wow, sorry I linked the screenshot only. I'll post another one linking the .c3p!
