### ISSUE TITLE
White bars on iPhone X exported project and multiple loading screens. 

### ISSUE THREAD

**Issue by mammothinc** [Scirra/Construct-3-bugs#3195]
## Problem description

There are multiple loading screens and there there are white bars when I export to Cordova via xcode project. This only happens on the iPhone X resolution. 

## Attach a .c3p

https://www.dropbox.com/preview/Apps/Construct%203/Crow%20Flying%20game/Crow%20Flying%20Preschool%20game%20p50%20John.c3p?role=work

## Steps to reproduce

Basically, Exporting the project to iOS

Also, the multiple loading screens happens everywhere.

**Comment by shortercode** [comment]
@mammothinc the link you provided does not work. Also are you exporting with "hide statusbar" enabled?

**Comment by mammothinc** [comment]
Try this link.

https://www.dropbox.com/s/xvg79biu1jhkpka/Crow%20Flying%20Preschool%20game%20p50%20John.c3p?dl=0

Yes, I am hiding the statusbar.

**Comment by shortercode** [comment]
All your icons a subtly the wrong size BTW... prevents me from building it

**Comment by mammothinc** [comment]
That's another bug we have found actually. We set the size of the icons to the right size then they change.

**Comment by shortercode** [comment]
@mammothinc I don't know how that would happen, but if you think it's a problem you should file another issue for that as it's a different part of the editor. The img files themselves are the wrong size when they reach the server though, and visually they appear to be the wrong size? Are the assets you importing for the icon the correct size?

**Comment by mammothinc** [comment]
Yes, they are, for whatever reason, we export it and the size changes randomly. The icons are not really the issue though. The bars and loading screens are a bigger issue. 

On another note, I have noticed the editor has been a bit buggy at times in the last release.

**Comment by shortercode** [comment]
Well @DiegoScirra may have changed something in the animations editor recently that could cause changes in image size, I'm not sure. As I said it needs following up in a new issue.

If you have specific examples we're happy to follow up on whatever parts are a "bit buggy".

I'll investigate the original issue and get back to you.

**Comment by mammothinc** [comment]
That would be great. I have a lot of games in the pipe and will probably report the issues here.

**Comment by shortercode** [comment]
You need to change your viewport fit setting to "cover" it's in project settings. It's basically a "do special things for iPhone X" flag that Apple added. I also swapped the Fullscreen mode to "scale inner" I can never remember which way round those are, but after changing those it made it fill the entire screen for me.

I agree the loading screens are a little frustrating I'm guessing they are:
1. iOS app loading screen ( we do actually have an option for customising this, but I don't think it ever made it into the docs - the fallback is to generate one using an icon on a white background ) its' basically a big square image that gets cropped for the device. It can be turned off but is needed for fullscreen...
2. Presume this is short "initialising runtime" esque loading bar, probably need to talk to @AshleyScirra  about that.
3.  Actual loading screen!

The first one needs to stay, but can be changed. I should think the second and the third could be merged together.

**Comment by shortercode** [comment]
The progress screen problem should be a separate issue I believe, hence why I closed this. If you are still having issues with "white bars" then I will reopen this.
