### ISSUE TITLE
Can't remove broken addons in safe mode

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#3198]
## Problem description
I've installed a purposefully broken plugin (missing aces) to test safe mode. Construct 3 crashes even with safe mode enabled.

## Steps to reproduce

1. Download: [brokenaddon.zip](https://github.com/Scirra/Construct-3-bugs/files/3482896/broken.zip)
2. Install and restart C3
3. Notice crash on startup
4. Run https://editor.construct.net/r159/?safe-mode
5. Notice crash in addon manager

## Observed result
Construct 3 safe mode doesn't make it possible to get rid of installed and broken addons.

## Expected result
I should be able to remove broken addons in safe mode.

**Affected browsers/platforms:**
- Chrome

**First affected release:** Just tested in r159

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: t.ǃRJY is not a function @ TypeError: t.ǃRJY is not a function at t.plugins (https://editor.construct.net/r159/main.js:63:115254) at plugins.next () at Object.ǃRAK (https://editor.construct.net/r159/main.js:159:18208) at https://editor.construct.net/r159/main.js:159:17935
Stack: TypeError: t.ǃRJY is not a function at t.plugins (https://editor.construct.net/r159/main.js:63:115254) at plugins.next () at Object.ǃRAK (https://editor.construct.net/r159/main.js:159:18208) at https://editor.construct.net/r159/main.js:159:17935
Construct 3 version: r159
URL: https://editor.construct.net/r159/?safe-mode
Date: Thu Aug 08 2019 19:15:33 GMT+0200 (Central European Summer Time)
Uptime: 432.3 s

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r159 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release.

**Comment by TheRealDannyyy** [comment]
Thanks for the fix. 

I hope this covers other cases as well, since this was more of a deliberately broken addon instead of something more specific like a missing semicolon or similar.
