### ISSUE TITLE
Families: adding a variable to family doesn't work if it's already in one of the family's objects

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#3199]
## Problem description

Adding a variable to a family, it doesn't allow me to do so if the object already has that variable name. 

This is quite inconvenient and tedious, because now I have to rewrite all the code that uses that variable if I want to use it in the family.

![image](https://user-images.githubusercontent.com/5744908/62756459-34437e80-babb-11e9-86a6-288545285056.png)

It falsely says this family has the variable already, when it doesn't, it's only in one of the family members - the conflict is unneccessary it should just allow the family to use it as well.

Thank you for fixing 😊

## Attach a .c3p

[family_variable_conflict.zip](https://github.com/Scirra/Construct-3-bugs/files/3484931/family_variable_conflict.zip)

## Steps to reproduce

1. add variable "grab" to the "food" family

## Observed result

Cannot create variable in family

## Expected result

Variable should be created or transfered

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by ChadoriRebornXD** [comment]
I didn't check the project. But based on your description,
it's not a bug, cause it would have a conflict. That's how Construct 2 works, at least. 

It wouldn't know which variable to read/write from the 2 families.

Well, unless the Construct Team wants to change it.

**Comment by AshleyScirra** [comment]
This is by design. The error is referring to the fact that using that name would cause a naming collision, i.e. `meat.grab` is already an expression, and therefore cannot be used as a family instance variable since it would make `meat.grab` ambiguous (it could refer to either the object's own instance variable or the family instance variable).
