### ISSUE TITLE
Set BinaryObject buffer via padded base64 string

### ISSUE THREAD

**Issue by Magistross** [Scirra/Construct-3-bugs#3200]
## Problem description
When setting the buffer from base64 string, and said string needed to be end-paded with "=", it fails and an error is logged to the console.

## Attach a .c3p
[BinaryObjectError.zip](https://github.com/Scirra/Construct-3-bugs/files/3487982/BinaryObjectError.zip)

## Steps to reproduce

1. Run as is

## Observed result
Blank layout, error logged into console

## Expected result
base64 is decoded in the buffer, encoded back to base64 and displayed as text in the layout

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Thanks for reporting this, I thought I had worked out the kinks out in this ages ago, but I guess I was wrong. The resulting string length calculation was slightly off and the trailing padding characters were being treated as illegal characters.

Slightly unrelated but the project your provide is actually invalid, as the base64 string you hardcoded contains illegal newlines characters. I'm guessing you copy pasted it with formatting from the wiki page.
