### ISSUE TITLE
Tween "set endvalues" behaves janky with certain eases, doesn´t work properly on others

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3203]
For example, I want to tween collectibles towards the (moving) player and I still want the collectibles to arrive after 1 second no matter the distance/player movement. I´d like to give them a little Back ease in for extra fancyness, but this kinda breaks the tween. I then noticed that it also doesn´t work as expected on other eases.

**Linear**: Seems to be the only one that works
**Ease in**: The objects barely move at first, then instantly jump at the player position right at the end
**Ease out**: Doesn´t seem to take the easing into account and looks just like the linear ease. (Especially noticeable with Out Elastic, as there isn´t any elasticity to see, in particular on the Y axis that doesn´t even change)

My guess is that the action resets the objects initial position, starting the ease all over again instead of keeping the objects initial position, recalculating where it should be. If you add an Every one second to the update event you can actually see the Ease in repeating.

## Attach a .c3p

[updateendvalue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3490237/updateendvalue.c3p.zip)

## Steps to reproduce

1. Preview
2. Observe

## Observed result

The Tween starts over/behaves weird.

## Expected result

The Tween not to reset/start over and instead actually update and recalculate.

## More details

**Affected browsers/platforms:** 

I checked back to r125 and it was also present there, even worse actually so there´s that :)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r159 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 179 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This is fixed in the next beta release.
