### ISSUE TITLE
Spritefont "Set width" not taken into account until next tick for "TextWidth" expression

### ISSUE THREAD

**Issue by Magistross** [Scirra/Construct-3-bugs#3204]
## Problem description

Upon setting a Spritefont's width using the "Set width" action, the "TextWidth" expression won't take it into account until the next tick. Interestingly, this problem does not occur when using the C2 runtime.
## Attach a .c3p
[SpriteFont_SetWidth.zip](https://github.com/Scirra/Construct-3-bugs/files/3491038/SpriteFont_SetWidth.zip)

## Steps to reproduce

1. Run as is, inspect the debug text.

## Observed result

Expected values do not match actual values.
## Expected result

Matching values.
## More details

Changing the runtime to C2 will make the problem disappear.

**Affected browsers/platforms:** 

**First affected release:** 
Probably since launch.
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
