### ISSUE TITLE
Drag and Drop in Pr

### ISSUE THREAD

**Issue by HammerFox** [Scirra/Construct-3-bugs#3205]
## Problem description

I cannot seem to drag and drop objects between subfolders on the mobile editor within the projects bar. I am trying to move a sprite from one subfolder to another, and can't do so. This turns out to also be the case for anything else.

## Attach a .c3p

This isn't related to a project. This happens in every project I have. It is related to the editor.

## Steps to reproduce

 This is an editor issue.
1. Try to move an object between subfolders on mobile.

## Observed result

It doesn't move.

## Expected result

The object moving.

## More details

I tried it in Chrome and Firefox on mobile.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 75.0.3770.143
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Android
Operating system version: 9
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 1.75
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 9; SM-N960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.143 Mobile Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.4 gb
Storage usage (approx): 84 mb (1.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Qualcomm
Renderer: Adreno (TM) 630
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Currently the mobile version of the editor has various limited features, one of which is drag-and-drop. This is because these features would need to be redesigned to work with touch input. For example dragging a touch normally just scrolls without changing anything, whereas for a mouse a click and a drag does drag-and-drop, so the way it's done on mobile needs to be different. For further improvements to the mobile editor please file feature requests here instead: https://construct3.ideas.aha.io/

**Comment by HammerFox** [comment]
That is completely understandable. Thank you for the reply.

**Comment by HammerFox** [comment]
I can live without drag and drop, but is there anyway to move objects between folders? I really don't want to be a bother, I just really love the cross platform nature of the editor.
