### ISSUE TITLE
C3 Color Issue

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3206]
## Problem description

I used image colored: **RGB(133,217,224)**
But when I use C3 color picker it is show me: **RGB(101, 220, 226)**
I was used set color for white image, you can see results.
![image](https://user-images.githubusercontent.com/13033837/62855343-abb32100-bcfa-11e9-8b81-801d6892fe12.png)

## Attach a .c3p

[BUGg.zip](https://github.com/Scirra/Construct-3-bugs/files/3491639/BUGg.zip)

## Steps to reproduce

1. Open project and look color values

**Affected browsers/platforms:**  Chrome

**First affected release:** r158

**Comment by AshleyScirra** [comment]
This just looks like a mistake. The top object really is colored 101,220,226 with no filter but the project mis-labels it as 113,217,224. The right object is white but uses a filter of 101,220,226 so has the same color. The left object is white but has a different filter so appears a slightly different color.

**Comment by QuasarX** [comment]
I think you misunderstood problem.
I use same image but C3 shows different color value

![aaa](https://user-images.githubusercontent.com/13033837/62877485-d075bb80-bd2f-11e9-816f-a5c08d8e3497.png)

**Comment by QuasarX** [comment]
@AshleyScirra Can you recheck this? I don't want make another duplicate bug report.

**Comment by AshleyScirra** [comment]
It all looks correct from within your project. Are you importing an external image file or something? If so you need to make sure that file and the steps you followed to import the file are included in the report, otherwise we can't follow what you're doing.

**Comment by QuasarX** [comment]
@AshleyScirra 
Yes I'm using one image file and C3 color picker show me different color value as I said in my first report.

Real image color: **RGB(133,217,224)**
C3 color picker shows: **RGB(101, 220, 226)** - (Wrong)

I also add that image file in bug report. You can import project and look with C3 color picker. It will show you wrong RGB value. Also you can test that image file with other applications. They will show real RGB value. I also post that you can see my 2. reply

**Comment by AshleyScirra** [comment]
The steps to reproduce in the original report weren't clear, but I still can't reproduce any issue. If I open the project and edit the top sprite the color is 100,219,226; if I export to Paint.NET and check with that instead, it is the same. So it appears to be correct.

**Comment by QuasarX** [comment]
@AshleyScirra I made video record. You don't need to edit any color value. Just watch video. C3 Color values wrong. That's all. Same image different color value.

https://streamable.com/88fey

**Comment by AshleyScirra** [comment]
You still haven't included the original image file you used, so it's still impossible to follow your steps. The file can be extracted from the project, but it does not reproduce in that case. Please be sure to follow the bug report guidelines and provide any information we ask for, otherwise it's impossible to deal with your report.

**Comment by QuasarX** [comment]
ok I give up
