### ISSUE TITLE
Timeline crash when removing all properties

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3207]
## Problem description

Crash when removing properties and trying to add some again

## Attach a .c3p

 n/a

## Steps to reproduce

1. Create a timeline
2. Add an instance
3. Remove X/Y props
4. Right click, add properties

## Observed result

Crash

## Expected result

No crash hopefully

## More details

**Affected browsers/platforms:** 

**First affected release:** Latest

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r160/main.js, line 2, col 279213
Message: Uncaught Error: dialog name 'PickTimelineProperty' not found
Stack: Error: dialog name 'PickTimelineProperty' not found at Function.ǃAFK (https://editor.construct.net/r160/main.js:2:279219) at Function.ǃqz (https://editor.construct.net/r160/main.js:2:286982) at i.ǃgDz (https://editor.construct.net/r160/components/bars/timelineBar/timelineBar.js:1:58638) at https://editor.construct.net/r160/components/bars/timelineBar/timelineBar.js:1:75388
Construct 3 version: r160
URL: https://editor.construct.net/r160/
Date: Tue Aug 13 2019 15:39:48 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 212.8 s

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r160 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Can't reproduce this one, but according to the crash it should be an easy fix. Will have to check it on the next beta.
