### ISSUE TITLE
Spritefont "Set character width" problem

### ISSUE THREAD

**Issue by Magistross** [Scirra/Construct-3-bugs#3208]
## Problem description

Problem is twofold. First, the "Set character width" has no effect when executed on a "Start of layout" trigger. Second, the "Set character width" never work for the space character.
## Attach a .c3p

[SpriteFont_SpaceWidth.zip](https://github.com/Scirra/Construct-3-bugs/files/3497290/SpriteFont_SpaceWidth.zip)

## Steps to reproduce

1. Run the project
2. Wait 2 seconds

## Observed result

First group of spritefonts shows discrepancies from the start. Doesn't get corrected by a subsequent "Set character width" call. The space character width stays at 16 pixels.

Second group of spritefonts shows discrepancies from the start. Gets corrected by a subsequent call to "Set chracter width". The "e" character width is now 32 pixels.
## Expected result

Both groups of spritefonts should be identical from the start.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should all be fixed for next release.
