### ISSUE TITLE
Corrupting bug duplicating timelines

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3209]
## Problem description

This is a pretty important issue and must be fixed as fast as possible!

## Attach a .c3p
[TimelineBreaks.zip](https://github.com/Scirra/Construct-3-bugs/files/3497463/TimelineBreaks.zip)

## Steps to reproduce

1. Duplicate the timeline
2. Change the play action in the 3rd event to play the duplicated timeline
3. Save

Like this:
![image](https://user-images.githubusercontent.com/11213825/62950353-27d76280-bde8-11e9-9b04-9aca3632b99d.png)

## Observed result

![image](https://user-images.githubusercontent.com/11213825/62950388-36be1500-bde8-11e9-9698-630d4e5a9ee9.png)

## Expected result

We should still be able to save

## More details
Note that this CORRUPTS the project. No amount of removing the timeline or events will fix it

**Affected browsers/platforms:** 

**First affected release:** r160

## System details

No crash, but a log error

<details><summary>View details</summary>

[Project] Exception saving:  TypeError: e.ǃtM is not a function
    at projectResources.js:1
    at Array.map (<anonymous>)
    at g.ǃzl (projectResources.js:1)
    at t.ǃsR (projectResources.js:1)
    at t.ǃsR (projectResources.js:1)
    at r.ǃrMc (projectResources.js:1)
    at Object.ǃqdT (main.js:210)
    at Function.ǃqGA (main.js:210)
    at i.ǃCZ (main.js:210)
    at Function.ǃqdJ (main.js:210)
ǃqdT @ main.js:210

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
