### ISSUE TITLE
Crash when trying to preview during saving

### ISSUE THREAD

**Issue by narFnarF** [Scirra/Construct-3-bugs#321]
## Problem description

Saving to dropbox, then starting the Preview quickly, while the saving to Dropbox is still happening, causes Construct 3 to crash.

## Attach a .c3p
[peggle rpg 2.zip](https://github.com/Scirra/Construct-3-bugs/files/1020145/peggle.rpg.2.zip)

## Steps to reproduce

1. Save to dropbox by hitting Ctrl+S
2. Immediately Start a preview with Ctrl+F5
3. Wait 1-2 sec
4. Crash

## Observed result

Construct 3 crashes

## Expected result

The preview continues normally without crashing.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

I'm not sure if it's relevant, but I'm using Construct in Chrome in a native window. Also, I'm using Preview in Popup Window:
![2017-05-22 16_36_25-peggle rpg - construct 3](https://cloud.githubusercontent.com/assets/3538115/26327377/34da04f8-3f0d-11e7-9bf8-7d60908d76cd.png)

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: dialog not open @ Error: dialog not open at ǃC.ǃl.ǃJ_.ǃmdz.ǃmDZ (https://editor.construct.net/r29-2/main.js:2:349442) at ǃC.ǃl.ǃJ_.ǃmdz.ǃmDZ (https://editor.construct.net/r29-2/main.js:2:364172) at ǃC.ǃl.ǃJ_.ǃmdz.ǃmSR (https://editor.construct.net/r29-2/main.js:2:350617) at te.then.we (https://editor.construct.net/r29-2/main.js:162:5284) at 
Stack: Error: dialog not open at ǃC.ǃl.ǃJ_.ǃmdz.ǃmDZ (https://editor.construct.net/r29-2/main.js:2:349442) at ǃC.ǃl.ǃJ_.ǃmdz.ǃmDZ (https://editor.construct.net/r29-2/main.js:2:364172) at ǃC.ǃl.ǃJ_.ǃmdz.ǃmSR (https://editor.construct.net/r29-2/main.js:2:350617) at te.then.we (https://editor.construct.net/r29-2/main.js:162:5284) at 
Construct 3 version: r29.2
URL: https://editor.construct.net/index.html
Date: Mon May 22 2017 16:33:15 GMT-0400 (Est (heure d’été))
Uptime: 45.3 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 745 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in r31.
