### ISSUE TITLE
ScrollTo Doesn't Have Any Expressions

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3214]
## Problem description

I'm not sure if it's a bug or a missing thing but I was looking for ScrollTo expressions to see if I can check the shaking magnitude. While typing there is ScrollTo but after that, there are no expressions. I will use the magnitude to vibrate the gamepad relative to screen shake magnitude, while it's shaking.

![image](https://user-images.githubusercontent.com/2965842/63026063-27f06480-beb3-11e9-9fac-27ccd0965559.png)

**Comment by AshleyScirra** [comment]
The behavior has no expressions.
