### ISSUE TITLE
Expressions are not shown in categories

### ISSUE THREAD

**Issue by colludium** [Scirra/Construct-3-bugs#3216]
## Problem description

I am creating a large behavior that presents the user with dozens of Expression values to choose from. In the SDK, ACEs can be grouped logically and, in the editor, Actions and Conditions are grouped in the same categories. However, there is no grouping for Expressions (only alphabetical). 

It would make for a better user experience if editor Expressions were grouped in the same categories as Actions and Conditions.

## Attach a .c3p

[Plugin_and_blank_project.zip](https://github.com/Scirra/Construct-3-bugs/files/3504909/Plugin_and_blank_project.zip)

## Steps to reproduce

Load the plugin and project, then try to use the Sprite expressions to view the format of the list.

## Observed result

There is no grouping by category for Expressions.

## Desired result

It would make it easier for the user to be able to read a plugin's Expressions if they were ordered by category (in the same way as Actions and Conditions are).

## More details
I expect to have literally dozens of expressions in my plugin and I am concerned that alphabetical sequencing won't be sufficient.

**Affected browsers/platforms:** N/A

**First affected release:** r157

## System details

N/A

**Comment by ChadoriRebornXD** [comment]
I have a few addons that have lots of expressions, around hundreds. And the SDK seems to provide a way to group categories.

Not sure if this is what you mean though. But you can see for yourself, below.

![image](https://user-images.githubusercontent.com/31282960/63078431-06a07e80-bf6e-11e9-8532-c086179f71f5.png)

In the **aces.json**, the parent property is the category for a group of actions, conditions and expressions.

![image](https://user-images.githubusercontent.com/31282960/63078533-626b0780-bf6e-11e9-9af0-702230beb50f.png)

**Comment by colludium** [comment]
@ChadoriRebornXD - that's exactly what I've done, and the Actions and Conditions do group correctly :/

![aces](https://user-images.githubusercontent.com/2897225/63079954-b6a6c500-bf37-11e9-9018-2b05ea2bb23c.png)

And this is what it appears like in the editor - the boxes denote items that should be grouped together. As you can see, they all come under one group heading that is the plugin name...

![expressions](https://user-images.githubusercontent.com/2897225/63080010-e0f88280-bf37-11e9-8720-5dac973eec1d.png)

**Comment by colludium** [comment]
Ok, I realise that a couple of screen shots won't help. Here's a blank of the plugin with the aces.json and en-US.json intact. Just load the plugin and then the project - then look at Sprite's LFJS expression list. Any help would be appreciated - I don't know if this is a formatting issue or a bug yet.

[Plugin_and_blank_project.zip](https://github.com/Scirra/Construct-3-bugs/files/3504892/Plugin_and_blank_project.zip)

**Comment by ChadoriRebornXD** [comment]
@colludium Ohh right! This happens only on behaviors. I noticed this before too.

**Construct 2**
![image](https://user-images.githubusercontent.com/31282960/63090815-05cc1480-bf8f-11e9-9bb0-2fed5f97b583.png)

**Construct 3**

![image](https://user-images.githubusercontent.com/31282960/63090830-13819a00-bf8f-11e9-8686-cef2fe143a63.png)

-----

**I guess this passes for c2 compatibility. I'd like this fixed too.**

**Comment by AshleyScirra** [comment]
This is actually a general problem with the expressions dictionary - the official Physics behavior actually uses different expression categories but has the same problem. It's fixed for the next release.

**Comment by colludium** [comment]
Thanks @AshleyScirra !
