### ISSUE TITLE
Frames from the same animation get put on different spritesheets

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3219]
## Problem description
Frames from the same animation get put on different sprite-sheets
![image](https://user-images.githubusercontent.com/32940085/63140314-8bf85300-bfaf-11e9-912d-c0c1fb8cca11.png)
![image](https://user-images.githubusercontent.com/32940085/63140376-b813d400-bfaf-11e9-8feb-59f8d3f82b55.png)

## Steps to reproduce

i have no idea

## Expected result
frames from the same animation to be on the same spritesheet

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Sirtaximan** [comment]
It is not a bug, I have been with the subject for some time, and it works like this. You have the option of reducing your sheets to 512, it is useless, but you have it.

**Comment by AshleyScirra** [comment]
This is currently by design.
