### ISSUE TITLE
[r29.2] Can't edit family instance variables or behaviors when instances of them aren't in an open layout

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#322]
## Problem description

I am unable to edit instance variables or behaviors on a family if it contains multiple objects and there is no _open_ layout containing them (AKA, if there is no tab with that layout visible). So, even though instances of the objects in the family are placed in the project in some layout or another, if that layout isn't open in a tab it's not possible to see or edit the family's instance variables or behaviors. If the family contains only one object, it can be edited regardless of whether or not it is placed in a currently loaded layout, which is how Construct 2 worked iirc. See example families in attached project.

## Attach a .c3p

[FamilyPropertiesBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1020199/FamilyPropertiesBug.zip)

## Steps to reproduce

1. Create two new sprites
2. Add the sprites to a new family
3. Create two new layouts
4. Place instances of the sprites into one of the layouts, and close the tab
5. With the second layout still open, click the family in the project view

## Observed result

The family's instance variables and behaviors won't be displayed and can't be edited. 

## Expected result

Instance variables and behaviors for the family should be shown and be editable.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 24 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This looks like it's working in the latest releases, so closing.
