### ISSUE TITLE
spritesheets do not use their "max spritesheet size" and are broken into little pieces instead

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3220]
## Problem description
spritesheets do not use their "max spritesheet size" and are broken into little pieces instead
![image](https://user-images.githubusercontent.com/32940085/63140564-4ee09080-bfb0-11e9-963c-68ddf3f382ae.png)

## Steps to reproduce

I don't know

## Expected result
sprites to get packed into a larger spritesheet 

## More details
it's pixel-art so there won't be memory problems because the resolution is so low, and i could use the extra performance

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is by design, to save memory.
