### ISSUE TITLE
It's very hard to format the expression thingy things 

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3221]
## Problem description
![image](https://user-images.githubusercontent.com/32940085/63140767-05447580-bfb1-11e9-9c32-4ee75bd01545.png)
formatting the expression things code thingy is very difficult and tons of spacebar must be used to write something readable, there is no way to indent or add comments or things like that

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The parameters dialog is not designed to use multi-line expressions. You could simplify it using functions anyway. File a feature request if you think this should be supported.

**Comment by eleanorawesome** [comment]
The performance is many times faster when using events this way, it would be a great thing if it was better supported and documented
