### ISSUE TITLE
The tooltip only shows up when writing new code

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3222]
## Problem description
when trying to edit code to fix bugs or refactor or whatever, the tooltips telling you what your code does don't show up:
![image](https://user-images.githubusercontent.com/32940085/63140930-a3384000-bfb1-11e9-90f0-97fe1315bebf.png)

to make them appear, you have to delete the parenthesis and type is back again
https://puu.sh/E5L3Q/62f970e8dd.mp4

which is cool and all but if you move your cursor sideways to edit the piece of the code you were looking for the tooltip goes away
https://puu.sh/E5L4Z/f3b4d1e8ec.mp4

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Call tips are only designed to work while writing the expression in the first place, due to the complexity of supporting other cases. If you want these cases to be supported please file a feature request.

**Comment by OverboyDev** [comment]
Submitted this as feature request with details about a possible implementation here : 
https://construct23.ideas.aha.io/ideas/C23-I-316
