### ISSUE TITLE
External event sheet window crash after editing comment and CRTL + Z

### ISSUE THREAD

**Issue by LukeWolfGames** [Scirra/Construct-3-bugs#3224]
## Problem description

Crash when you edit a comment in an external event sheet window and press CRTL + Z.

## Attach a .c3p

https://www.dropbox.com/s/s2fpzi2h4gjf8wo/External%20event%20sheet%20window%20crash%20when%20pressing%20backspace%20with%20selected%20block.c3p?dl=0

## Steps to reproduce

1. Open event sheet.
2. Separate the event sheet so it's on an independent window (so you have two tabs in your task bar for Construct 3) 
3. Double click the comment so you can edit it.
4. Highlight the text.
5. Type something so it replaces the text with something else.
6. Press enter to finish your comment.
7. Hold CTRL then press the letter Z on your keyboard.

## Observed result

Construct 3 Crashes and returns an error with error information.

## Expected result

Undo the edited comment without crashing.

## More details

![bMi9fXs](https://user-images.githubusercontent.com/28833199/63179622-e49f1d00-c08f-11e9-8a99-cf6f54be07c5.gif)

**Affected browsers/platforms:** Desktop

**First affected release:** r159

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r160/components/editors/eventSheetView/eventSheetView.js, line 1, col 62971
Message: Uncaught TypeError: Cannot read property 'scrollHeight' of null
Stack: TypeError: Cannot read property 'scrollHeight' of null at window.ǃrAT.ǃrnL (https://editor.construct.net/r160/components/editors/eventSheetView/eventSheetView.js:1:62971) at HTMLTextAreaElement. (https://editor.construct.net/r160/components/editors/eventSheetView/eventSheetView.js:1:62664)
Construct 3 version: r160
URL: https://editor.construct.net/r160/
Date: Sat Aug 17 2019 01:11:49 GMT+1000 (Australian Eastern Standard Time)
Uptime: 723.9 s

Platform information
Browser: NW.js
Browser version: 0.40.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.40.1 (like Chrome/76.0.3809.100)
C3 release: r160 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

@AshleyScirra If you need more information from me or something does not make sense to you, please just ask me about it so I can provide you with the information you need to resolve the issue instead of nit picking things I say in my posts and close my bug reports one after the other, forcing me to re-post them. It's not really appropriate treatment to give a paying customer that's taking out their valuable personal free time in an attempt to debug your program. I understand and respect your community guidelines but it's not professionally ethical to treat paying customers like employees. Showing a bit of appreciation goes a long way for the ones trying to do the right thing by you.

**Comment by AshleyScirra** [comment]
With these more detailed steps to reproduce, I could finally reproduce the issue. It should be fixed in the next release.

Please take care to always follow the bug report guidelines as thoroughly as possible with every report. They are there precisely to avoid this problem of repeatedly filing issues that we cannot do anything about. The first report was missing a project and the second report had insufficient steps to reproduce. If you make sure your report is fully complete with clear and comprehensive information from the start, we are much more likely to be able to fix the problem right away, and this will save both our time and your time.

**Comment by LukeWolfGames** [comment]
I acknowledge that there were issues with the detail in my original bug report where I **accidentally** posted the wrong link. I made a mistake, it wasn't intentional, and in turn; instead of closing them one after the other, you could have just addressed both issues in the one bug report and not only saved both of us time but also saved yourself from dealing with an irate customer. The fault became yours in the end, and the difference you need to understand, Ashley, is that me, as a paying customer, taking out valuable time to send you feedback in an attempt to be helpful to you and your product. In return what I receive from you (the business) is a behaviour that indicates that that my money, time and helpful intentions is not appreciated. This is proven once again by another critical comment coming from you after I had something to say about it. It's not acceptable treatment to give to your customers and if you want to save yourself from further damage to your brand and reputation, I strongly recommend getting a customer service mindset and stop jumping down your customer's throats when we are doing the best we can to help you.

With that out of the way, thank you for fixing the bug.

**Comment by AshleyScirra** [comment]
I appreciate dealing with bug reports can be frustrating. However our goal is to teach people to file useful reports and our process is oriented towards this. We're a tiny team and we deal with thousands of bug reports, and we simply don't have the resources to investigate reports unless they contain all the necessary information and prove there is an issue in Construct. Users routinely file reports that are more or less useless and this ends up wasting everyone's time; we need these users to learn how to file useful reports to be able to help them. Therefore our process is geared towards guiding users to filing useful reports, and not acting on them until all the guidelines are followed. This amounts to training users how to file useful reports, and it takes up a major part of the time we spend in dealing with bug reports. I hope that what happened here illustrates the importance of following the guidelines as closely as possible from the start, how we try to ensure users get in the habit of filing useful reports that we can actually act on, and how that can make the process quicker for everyone and more likely to end with the issue being resolved.

**Comment by LukeWolfGames** [comment]
I appreciate everything you have said. I also appreciate the pressure I am feeling you are experiencing from your explanation, but it's not bug reports that are frustrating me, Ash, it's how I am treated as a customer giving you feedback. You can still teach your customers to file bug reports without making them feel unappreciated as customers, because that's what it feels like when I make a mistake in spite of doing my best to get it right for you. After experiencing the same treatment over a period of time you can come across more critical than anything else. That can really put people off.

It goes without saying that I'm not really that good at it and there are going to be more people that are worse than I am trying to do this. As the community grows, so will the pressure and I don't fully understand the numbers in your business in terms of not having the resources, but I hope one day you will be able to hire more people so that you and the team have the help there to deal with bug reports, test and debug your program without experiencing so much stress.
