### ISSUE TITLE
[JS] custom subclasses don't get instantiated with worldinstance

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3226]
## Problem description

I'm guessing it's by design? Basically, I have written a monster in JS, and that monster has an AI that is started in the constructor, but the class isn't instantiated until I first pick it (by using getFirstInstance)

## Attach a .c3p
Here's a super minimal repro of the issue:
[ClassBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3511812/ClassBug.zip)

## Steps to reproduce

1. Open the preview
2. Open the console

## Observed result

The square gets resized after 2 seconds and the console logs the call order

## Expected result

The resize should happen immediately since it's done in the object's constructor and the object is already in the layout

## More details

I'm guessing this is by design and I can see why it is, but I really think that for projects that want to use JS for part of the project, this should have an option somewhere to allow auto instantiation of classes with the world Instances. 

I'm making an RPG, and I'm using JS for enemies AI and skills because JS has coroutines (and overall better perf than JS)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
In #3040 we fixed a user-reported performance regression in part by lazy-creating the script classes until they're first used, since otherwise they have a performance overhead. However with custom subclasses this becomes observable and is indeed unexpected. I've fixed it for the next release by only lazy-creating the script classes if there isn't a custom subclass; if there is it will create it straight away. This should fix subclassing to work as expected, and still not regress performance benchmarks that do not use scripting at all.

**Comment by skymen** [comment]
Great. Can this have unexpected behavior for custom subclasses that extend classes that extend ISpriteInstance? 
Like, if I have a middleman class that is never used as a custom subclass, is there a chance that they'll get loaded after the custom subclass, breaking the subclass in the process?

Exemple from my game
class SpriteBase extends ISpriteInstance

class Pawn extends SpriteBase

class Watcher extends Pawn

runtime.object.Watcher.setCustomSubclass(Watcher)

I use that to define general behavior for all JS managed sprites, and get closer and closer to each sprite as I go down heritage.

**Comment by AshleyScirra** [comment]
It should always work as of the next release any time you use a sub class.
