### ISSUE TITLE
Android export as Cordova project with phonegap shows black screen

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#3228]
## Problem description

A blank android project exported as Android Cordova with Cordova project file and loaded on phonegap with the Desktop - Mobile duo app opens up a black screen only.

## Attach a .c3p

[Cordova export and phonegap (1).c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3512032/Cordova.export.and.phonegap.1.c3p.zip)

## Steps to reproduce

1. open the project
2. export as in this image
![image](https://user-images.githubusercontent.com/7268697/63212225-b9f1aa80-c109-11e9-9f03-ba1e8b4eb1a2.png)

3. have Phonegap desktop installed (https://phonegap.com/getstarted/)
4. have Phonegap the Android app installed
5. drag the folder on the Phonegap desktop program
6. open the Android app and connect to the address

## Observed result

The project opens with a black screen

![Screenshot_20190817-161306](https://user-images.githubusercontent.com/7268697/63212248-11901600-c10a-11e9-93d1-d2c4cc154ec7.png)

## More details

**Affected browsers/platforms:** Latest Android version

**First affected release:** tested with r157, r159 and r160

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 205 gb
Storage usage (approx): 233 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon 550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by JeFawk** [comment]
I also tried with Android version 5 in the export options

**Comment by AshleyScirra** [comment]
I think this is the same as #3093. The PhoneGap desktop app doesn't implement the cordova-plugin-file plugin correctly. They will need to fix it for PhoneGap desktop to be compatible with Construct exports.

**Comment by JeFawk** [comment]
@AshleyScirra I also tried Android Studio and that didnt seem to work either, is there any reliable way of publishing games via Android right now?

**Comment by AshleyScirra** [comment]
This issue only affects specifically the PhoneGap desktop app. The PhoneGap build service and all other build options should not be affected. If they are please file a new report following all the guidelines as it is unlikely to be related to this issue.
