### ISSUE TITLE
Desktop build r160 crashes sometimes

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#3229]
## Problem description

This is probably the same problem as #3188 (https://github.com/Scirra/Construct-3-bugs/issues/3188) but as it still happens in r160 I start a new bug post.

C3 desktop build crashes randomly.
It already seems more stable than in r159 though, as crashes did happen less often.

## Attach a .c3p

/

## Steps to reproduce

No steps to reproduce was found as the crashes occured after about 2 hours of usage and in 2 different situations.

## Observed result

The editor crashes.

## Expected result

The editor should work properly.

## More details

It happened 2 times in r160, in 3 session of about 2 hours each.
The first time I was just adding a new condition when it crashed.
The second time I didn't see it crash because a preview was running, and when I went back to the editor, the message "Oops! Something went wrong" was displayed.

**Affected browsers/platforms:** Desktop build r160

**First affected release:** r160

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.ǃA.ǃgl (https://editor.construct.net/r160/main.js:2:92366) at Function.ǃqz (https://editor.construct.net/r160/main.js:210:130545) at e (https://editor.construct.net/r160/main.js:210:117488) at ǃA.ǃw (https://editor.construct.net/r160/main.js:210:118195)
Stack: TypeError: expected string at Function.ǃA.ǃgl (https://editor.construct.net/r160/main.js:2:92366) at Function.ǃqz (https://editor.construct.net/r160/main.js:210:130545) at e (https://editor.construct.net/r160/main.js:210:117488) at ǃA.ǃw (https://editor.construct.net/r160/main.js:210:118195)
Construct 3 version: r160
URL: https://editor.construct.net/r160/
Date: Sun Aug 18 2019 08:45:32 GMT+0200 (Romance Daylight Time)
Uptime: 4201.8 s

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r160 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by RabloGames** [comment]
Third crash happened after +-15 minutes of usage, during a preview.
Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.ǃA.ǃgl (https://editor.construct.net/r160/main.js:2:92366) at Function.ǃqz (https://editor.construct.net/r160/main.js:210:130545) at e (https://editor.construct.net/r160/main.js:210:117488) at ǃA.ǃw (https://editor.construct.net/r160/main.js:210:118195)
Stack: TypeError: expected string at Function.ǃA.ǃgl (https://editor.construct.net/r160/main.js:2:92366) at Function.ǃqz (https://editor.construct.net/r160/main.js:210:130545) at e (https://editor.construct.net/r160/main.js:210:117488) at ǃA.ǃw (https://editor.construct.net/r160/main.js:210:118195)
Construct 3 version: r160
URL: https://editor.construct.net/r160/
Date: Sun Aug 18 2019 15:39:55 GMT+0200 (Romance Daylight Time)
Uptime: 601.8 s

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r160 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by RabloGames** [comment]
Fourth crash happened after +-10 minutes of usage, while I was editing an action (changing the X, Y reference of an array action). Desktop build is definitely not usable, so I stop usig it.
<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.ǃA.ǃgl (https://editor.construct.net/r160/main.js:2:92366) at Function.ǃqz (https://editor.construct.net/r160/main.js:210:130545) at e (https://editor.construct.net/r160/main.js:210:117488) at ǃA.ǃw (https://editor.construct.net/r160/main.js:210:118195)
Stack: TypeError: expected string at Function.ǃA.ǃgl (https://editor.construct.net/r160/main.js:2:92366) at Function.ǃqz (https://editor.construct.net/r160/main.js:210:130545) at e (https://editor.construct.net/r160/main.js:210:117488) at ǃA.ǃw (https://editor.construct.net/r160/main.js:210:118195)
Construct 3 version: r160
URL: https://editor.construct.net/r160/
Date: Mon Aug 19 2019 06:48:01 GMT+0200 (Romance Daylight Time)
Uptime: 601.6 s

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r160 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
All three crashes you posted are still using an old version of NW.js (0.30, latest 0.40.1) so you still have not addressed my comment from #3188. Closing as duplicate.

**Comment by RabloGames** [comment]
You're right, my apologies.
I updated NW.js and the desktop build crashed again. Here is the information:
<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.ǃX.ǃvi (https://editor.construct.net/r161/main.js:2:92366) at Function.ǃzZ (https://editor.construct.net/r161/main.js:210:131090) at e (https://editor.construct.net/r161/main.js:210:118033) at https://editor.construct.net/r161/main.js:210:118740
Stack: TypeError: expected string at Function.ǃX.ǃvi (https://editor.construct.net/r161/main.js:2:92366) at Function.ǃzZ (https://editor.construct.net/r161/main.js:210:131090) at e (https://editor.construct.net/r161/main.js:210:118033) at https://editor.construct.net/r161/main.js:210:118740
Construct 3 version: r161
URL: https://editor.construct.net/r161/
Date: Mon Aug 19 2019 20:16:33 GMT+0200 (Central European Summer Time)
Uptime: 601.1 s

Platform information
Browser: NW.js
Browser version: 0.40.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.40.1 (like Chrome/76.0.3809.100)
C3 release: r161 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by RabloGames** [comment]
<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.ǃX.ǃvi (https://editor.construct.net/r161/main.js:2:92366) at Function.ǃzZ (https://editor.construct.net/r161/main.js:210:131090) at e (https://editor.construct.net/r161/main.js:210:118033) at https://editor.construct.net/r161/main.js:210:118740
Stack: TypeError: expected string at Function.ǃX.ǃvi (https://editor.construct.net/r161/main.js:2:92366) at Function.ǃzZ (https://editor.construct.net/r161/main.js:210:131090) at e (https://editor.construct.net/r161/main.js:210:118033) at https://editor.construct.net/r161/main.js:210:118740
Construct 3 version: r161
URL: https://editor.construct.net/r161/
Date: Tue Aug 20 2019 04:59:24 GMT+0200 (Central European Summer Time)
Uptime: 1200.9 s

Platform information
Browser: NW.js
Browser version: 0.40.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.40.1 (like Chrome/76.0.3809.100)
C3 release: r161 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by RabloGames** [comment]
<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.ǃX.ǃvi (https://editor.construct.net/r161/main.js:2:92366) at Function.ǃzZ (https://editor.construct.net/r161/main.js:210:131090) at e (https://editor.construct.net/r161/main.js:210:118033) at https://editor.construct.net/r161/main.js:210:118740
Stack: TypeError: expected string at Function.ǃX.ǃvi (https://editor.construct.net/r161/main.js:2:92366) at Function.ǃzZ (https://editor.construct.net/r161/main.js:210:131090) at e (https://editor.construct.net/r161/main.js:210:118033) at https://editor.construct.net/r161/main.js:210:118740
Construct 3 version: r161
URL: https://editor.construct.net/r161/
Date: Tue Aug 20 2019 05:21:20 GMT+0200 (Central European Summer Time)
Uptime: 1201.7 s

Platform information
Browser: NW.js
Browser version: 0.40.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.40.1 (like Chrome/76.0.3809.100)
C3 release: r161 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Unfortunately the crash report doesn't contain anything useful, and the report doesn't have any reproducible steps to follow. So there is nothing we can do to investigate this so far. I'm afraid you'll need to try to figure out a way to reproduce the problem for us to follow up on this.
