### ISSUE TITLE
Bullet odd behavior ("For Each" picking as sub-event)

### ISSUE THREAD

**Issue by 3dParadox** [Scirra/Construct-3-bugs#323]
## Problem description

Edit: see comment below, may be picking failure

created bullets seem to still exist after being destroyed, triggering For Each, and holding values.
And newly created bullets seem to add their default values to previous bullets, as in speed. 

EDIT:  Ok, after more experiments, it may not be the bullet at all, but the "For Each" being a sub-event...
taking the routine out of the "Every Tick" event, fixed it.  So "For each" in a sub-event breaks bullets?

## Attach a .c3p

https://www.dropbox.com/s/9gucj3u60xfkv4e/destroybug.c3p?dl=0

## Steps to reproduce

first one, minor:
1. run the C3P
2. click on the lower part of the screen to create a text object bullet that travels to the score spot, and adds it's value and is destroyed.
3. un-disable the action in event 4 to work around that one. run to compare. 

second bigger oddity:
1. Click multiple times to see the second odd behavior, very fast bullets, with nothing increasing their speed. (I even turned off acceleration, comments may still mention it on.)

*** EDIT: Solution is to take Event 3 out of the "each tick" event, and bullets behave correctly again. both problems go away. However this doesn't work if it has to be in a sub-event.

## Observed result

Destroyed bullets still exist somehow.
and created bullets seem to add their default values to previously created bullets.

## Expected result

Destroying a bullet wouldn't include it in "For Each" anymore, and it wouldn't have a value to check.
Bullets would be created with the values of the bullets that were destroyed on the start of the layout.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by 3dParadox** [comment]
I gave up on the Jam entry.  This also affected other sprites in my game. They weren't bullets, but "destroy" still didn't register in a "for each" sub-event so it was acting erratically. 

It seemed like sprites weren't being destroyed until a top level event, but "wait 0" didn't fix it.

**Comment by 3dParadox** [comment]
I made up another example showing what looks like it might be a picking failure causing it.

https://www.dropbox.com/s/f1kr4vs2ig3fvqc/ForEachSub.c3p?dl=0

Steps: (copied from the C3P comments)
Run it once, notice the birds patterns.
tap spots to spawn new birds. notice the new patterns.
Now drag Event 1 to be a sub-event of the "Every tick" event, and run again.
the pattern is the same, try clicking to spawn a bird.
Notice the other birds flew the coop.

**Comment by AshleyScirra** [comment]
Thanks for the reduced test case, it really helps. The smaller the repro the better.

After looking in to this, it turns out it's unique to "create object by name", which you happen to be using in C3 instead of the normal version with an object picker. That's also why it doesn't repro in C2, it doesn't have "create object by name". It took me a while to spot that! I should be able to figure out a fix for this soon.

**Comment by AshleyScirra** [comment]
OK, should be fixed in r40.
