### ISSUE TITLE
Worker mode dt is still unstable and not usable

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3230]
## Problem description

 Same case as #1998, reported almost a year ago.
Using Worker mode dt is unstable. Any game that scrolls or needs smooth moving with dt: tweens, platform behavior, bullet etc etc. Cannot be used because objects start to jump back and forth, it is very bad to look at and causing nausea from long exposure to this behavior.
## Attach a .c3p
[WorkerDT_lag.zip](https://github.com/Scirra/Construct-3-bugs/files/3513489/WorkerDT_lag.zip)

## Steps to reproduce

1.Open example
2.Click Preview
3.Click Fullscreen
4.Observe black ball lag
5.Disable worker see clean movement

## Observed result
Worker mode has unstable dt, which results lagged movement of everything that use dt.

## Expected result
Smooth movement.

## More details

Even though dt lags on some weaker pc(mostly laptops)even when worker disabled. But still, on computers that are able to do smooth dt, should do it with worker mode also.

**Affected browsers/platforms:** 
All browsers, but chrome has dt good without worker, so worker mode should be fixed too if possible. 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r160 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.2 gb (8.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Any issues in jank or dt are the responsibility of the browser. You can report this type of thing directly to the browser makers. I filed [crbug.com/995235](https://bugs.chromium.org/p/chromium/issues/detail?id=995235) to follow up with Google.

**Comment by SnipG** [comment]
I now tested this in Canary and it seems to be better in there. Like the irregular spacing is much better in Canary. Even though in Dev is all back to bad spacing, when i ran first time. But tried multiple times, when later ones are much better.
Same with worker mode, if you keep it on long time in canary the ms jankiness gets better. 

These stuff are rly complex and hard to report for myself or make case for, with solid example that they can work with.

Another strange thing is, in Canary and Dev first trail parts fail to spawn, because the internal loop. But in Normal chrome all trails spawn. So internal stuff in chrome Dev and Canarly might take up even more frame time % then in chrome normal. And it's in worker mode. So i think they constantly clog chrome with stuff that take up a lot of % frame time, and less % is left for engines/websites.
 But as before, if you keep chrome running for long time with example, it will get better. So they might apply some battery saver technology, that fails to deactivate if only few frames take huge amount of cpu power to give out smooth results etc.
