### ISSUE TITLE
Eraser tool hardness bugs and does not provide solid edges

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3231]
## Problem description

While writing idea suggestion(https://construct3.ideas.aha.io/ideas/C3-I-1072)
I came across case that eraser tool hardness does not clamp to maximum and even when hardness is 1, it does not provide solid edges.
See pic below.
Erase with red circle is clean try to make solid erase with hardness 1.  While erases with blue circle where same, but before swapping options randomly.
![EraserBug2](https://user-images.githubusercontent.com/28864889/63274176-01ae3880-c2a8-11e9-86c4-ce2f7ea8b2d1.jpg)

## Steps to reproduce

1.Open animation editor
2.Pick eraser tool, try deleting some color.
3.Change zoom level, swap tools, change hardness from 1 to 0.5 etc and then back.
4. See it starts to clean with clean edges.

## Observed result
Erases tool sometimes erases with smooth edges, then with solid edges. Like hardness does not clamp to 1.0 etc

## Expected result
erases tool to clean with solid edges with hardness 1.0 . And with smooth edges with hardness lower then 1.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r161 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.2 gb (9.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
@SnipG

It took me a little while to figure it out, but it looks like odd eraser sizes are causing the problem.

**Comment by DiegoScirra** [comment]
Fixed will be available in the next beta.
