### ISSUE TITLE
Problem in exporting to HTML with r161 and r159

### ISSUE THREAD

**Issue by mgsoftwaring** [Scirra/Construct-3-bugs#3232]
## Problem description

when I export my game in html5 it works correctly I am with Edge, while with firefox, chrome and safari it makes confusion with the sprite

## Attach a .c3p
I cannot put the .c3p in as it is a commercial product and I am not authorized to do so, I am only the developer but you can see the product in  beta testing at: http://www.ludikproject.com/wp-content/uploads /games/iframe/fastball/index.html

## Steps to reproduce
you can see the problem already from the first screen by entering two different nik the sprites below should be a pad, a mouse, a series of flags of some countries and a Play button, instead a mix of many sprites comes out that have nothing to do with it

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines to ensure you file reports that we can investigate.
