### ISSUE TITLE
List and Text Input form controls completely unresponsive in R161

### ISSUE THREAD

**Issue by dru1000** [Scirra/Construct-3-bugs#3233]
## Problem description
Add a List or Text Input form control to an empty project, preview the game and you'll see neither component can be interacted with.

Works fine on R160

Its such a simple bug to test i'll leave the rest blank but if you need more info let me know.

**Comment by AshleyScirra** [comment]
Accidentally broke this while trying to work around some Safari quirks with pointer events. Should be fixed in next release.
