### ISSUE TITLE
Weird console logs from commonAces

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3234]
## Problem description

Sometimes, commonAces.js logs weird stuff for no reason
## Attach a .c3p

I couldn't manage to reproduce it, it doesn't even seem consistent as it doesn't always happen

## Observed result
![image](https://user-images.githubusercontent.com/11213825/63357870-6f229d80-c36a-11e9-9e2d-553d98a28b2d.png)

## Expected result

No logs, or at least not tons of them at every frame

## More details

This seems to happen to me only when I launch some layouts of my game without going through the loader layout :/.

No idea why it happens though.

**Affected browsers/platforms:** 

**First affected release:** SEEMS TO have first started happening in r160 or r159, but I'm unsure

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
@DiegoScirra left in a console log for testing, removed for next release. You can just ignore those logs.
