### ISSUE TITLE
Editor zoom bug

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#3235]
## Problem description

When you hold ctrl + shift and roll the mouse scroll the editor is supposed to move 100% closer to the objects in the screen (zoom), and it works well from 100% to 200%, but when you try to go from 200% to 300% it goes straight to 400%.

## Attach a .c3p

Not needed.

## Steps to reproduce

1. Open a blankj project.
2. Hold ctrl + shift and roll the mouse scroll.
3. Try to reach 300% zoom.

## Observed result

The editor skips the 300% value.

## Expected result

The editor to not skip the 300% value.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by BonzerKitten7** [comment]
I'm writing a book about C3 and sometimes it's hard to capture screenshots without this features working properly, that's how I ended with such a "niche" bug report.

**Comment by AshleyScirra** [comment]
> When you hold ctrl + shift and roll the mouse scroll the editor is supposed to move 100% closer to the objects in the screen (zoom)

Actually no - it zooms to 2x the current zoom (or half if zooming out). This is by design.

**Comment by BonzerKitten7** [comment]
There's at least a reliable way to manually set the zoom?
