### ISSUE TITLE
Running a blank project crashes.

### ISSUE THREAD

**Issue by Fengist** [Scirra/Construct-3-bugs#3236]
r161

Console shows this error.

index.html:1 Access to fetch at 'https://editor.construct.net/r161/preview/c3/workers/jobworker.js' from origin 'https://preview.construct.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
editor.construct.net/r161/preview/c3/workers/jobworker.js:1 Failed to load resource: net::ERR_FAILED
domSide.js:1 Uncaught (in promise) TypeError: Failed to fetch

Reloaded Chrome, created a blank project, ran it and got this.

c8f99a89-f5d7-4f57-bec8-386b8fce72c7:1 [C3 runtime] Failed to load all engine scripts in worker:  DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://editor.construct.net/r161/lib/queryParser.js' failed to load.
    at a (blob:https://preview.construct.net/c8f99a89-f5d7-4f57-bec8-386b8fce72c7:1:475)
    at blob:https://preview.construct.net/c8f99a89-f5d7-4f57-bec8-386b8fce72c7:1:1812

Tried this in Edge as well.  Dropped a text input on a form, ran it and it crashed.

No c3p needed.  This happens with a blank project.

Create a new project, run it.

**Comment by shortercode** [comment]
I think this is the same issues as #3237 some files were intermittently 404ing on the latest release. This should hopefully now be resolved.

**Comment by AshleyScirra** [comment]
I think this was an intermittent server issue which is fixed now so closing.
