### ISSUE TITLE
UNABLE TO ACCESS CONSTRUCT 3 AFTER UPDATING TO BETA R161

### ISSUE THREAD

**Issue by pktora** [Scirra/Construct-3-bugs#3237]
Help, I can't seem to run Construct 3 using the r161 beta. I keep getting this message...

"
Error loading! Try disabling browser addons, they can sometimes break Construct 3. Unhandled promise rejection: Error: error fetching loader/lang/precompiled-en-US.json (404 ) at n (https://editor.construct.net/rl 61/main.js:2:109788) at async https://editor.construct.net/rl 61 /main.js:2:179023 at async Promise.all (index O) at async !X.!t.!XFU.!x_q (https://editor.construct.net/rl 61 /main.js:2:178980) at async Promise.all (index O) at async https://editor.construct.net/rl 61/main.js:210:113473
"

Has anyone come across this issue with the latest beta version (r161) of C3? The latest version of my game is using r161.

**Comment by shortercode** [comment]
We had some minor issues in the publishing process for the newest release. It should hopefully now be resolved if you try again. You might have to try reloading a few times to bypass any caching.

**Comment by Fengist** [comment]
Appears to be working now. Thanks!
