### ISSUE TITLE
TextInput don't work on Android

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#3239]
## Problem description

The TextInput don't work anymore on Android. I can't "select" the field and/or the keyboard don't comes up. 

## Attach a .c3p

[Download Example-File](https://drive.google.com/open?id=1mIHOXBvRWAPz-CR1H62HLhjz5QxszrJK)

## Steps to reproduce

1. Open the example file
2. Run per remote (or as apk) on android
3. You see, you can't select the TextInput anymore.

## Observed result

I can't select the TextInput or write something on it with android.

## Expected result

I can select the TextField and the keyboard comes up.

## More details

**Affected browsers/platforms:**
Android 8.0 - Samsung-Galaxy S7
( Don't work as apk or directly on browser )

**First affected release:**

Dont run on r161 Beta.  (Works on r160 Beta) 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r161 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 43 gb
Storage usage (approx): 416 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Sounds like this might be related to a change @AshleyScirra made recently so assigning to him to review.

**Comment by AshleyScirra** [comment]
Same as #3233
