### ISSUE TITLE
Phonegap build fails

### ISSUE THREAD

**Issue by Boulerzzz** [Scirra/Construct-3-bugs#3242]
## Problem description

Phonegap fails when using C3 runtime.

## Attach a .c3p

[Test.zip](https://github.com/Scirra/Construct-3-bugs/files/3525200/Test.zip)

## Steps to reproduce

1. Build IOS cordova
2. Build Phonegap build

## Observed result

Build fails with a large error log

## Expected result

Ipa file to be built

## More details

1. Tried to change the cli version in the config. By default C3 exports with 8.0.0 and I also tried 9.0.0. That also failed but with a different error.

2. This seems to be related to this bug report:
https://github.com/Scirra/Construct-3-bugs/issues/2548

3. C2 runtime works.

**First affected release:** r157. Have always used Xcode before without problems but needed to use cordova this time so don't know how long this has been an issue.

## Error log

The error log was apparently too large to paste. I only pasted what I think was most important.

<details><summary>View details</summary>

** ARCHIVE FAILED **

The following build commands failed:
	ProcessPCH /private/project/build/sharedpch/Test-Prefix-gkpvionowkwdmtbnnaalowlfgspg/Test-Prefix.pch.pch Test/Test-Prefix.pch normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/private/project/cordova/build-release.xcconfig,-workspace,Test.xcworkspace,-scheme,Test,-configuration,Release,-destination,generic/platform=iOS,-archivePath,Test.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/project/build/device,SHARED_PRECOMPS_DIR=/private/project/build/sharedpch,-UseModernBuildSystem=0

</details>

**Comment by shortercode** [comment]
@AshleyScirra could you review if this is failing for you? My certificate has expired so I can't build through PGB at the moment.

**Comment by AshleyScirra** [comment]
@Boulerzzz does this still reproduce for you? Have you contacted PhoneGap Build support about it?

**Comment by AshleyScirra** [comment]
It looks like a problem with PhoneGap Build. I'm not sure what's going on, so I asked here: https://community.adobe.com/t5/phonegap-build/ios-builds-fail-if-specifying-deployment-target-12-0/m-p/10886462?page=1

We'll follow up there. In future it would probably be quickest to contact PhoneGap Build's support directly yourself for any issues with their service.

**Comment by Boulerzzz** [comment]
Alright. I have not used phonegap since this was posted. I used to use it when building IPAs but now I have a mac so I don't need it anymore. 👍
