### ISSUE TITLE
Multiple loading screens

### ISSUE THREAD

**Issue by mammothinc** [Scirra/Construct-3-bugs#3243]
When I release this game on iOS there are multiple loading screens. 

In addition, when I preview this game, there are multiple loading screens. I have tried to fiddle with the selection multiple times. 

https://www.dropbox.com/s/xvg79biu1jhkpka/Crow%20Flying%20Preschool%20game%20p50%20John.c3p?dl=0

There's not much else I can do on my end.

**Comment by shortercode** [comment]
As per #3195 when I ran the project I saw 3 distinct stages. First it shows the launch storyboard, which is a static image. We unfortunately have to use this to support fullscreen on iPhone X. The second was a blue loading bar by itself, and the third was a blue loading bar and the games loading image.

**Comment by AshleyScirra** [comment]
The project 'Loader style' property is set to 'Progress bar & logo', and it sounds like that's what it's showing. If you don't want that, change the loader style property, and/or use a loader layout.

**Comment by mammothinc** [comment]
Hi there, this is what I am seeing. 

I think I know what the problem is. The loading image isn't actually loading on the start. 


[Capto_Capture 2019-08-22_07-44-53_AM.mov.zip](https://github.com/Scirra/Construct-3-bugs/files/3530640/Capto_Capture.2019-08-22_07-44-53_AM.mov.zip)

**Comment by AshleyScirra** [comment]
It doesn't show the image until the image itself has loaded. That is by design.

**Comment by mammothinc** [comment]
It looks like error, or two loading screens. Is there anyway to priortize the image to load first?

**Comment by mammothinc** [comment]
Or, usually when you pull up an app, there's an image that is displayed, is it possible to display the native Xcode loading image first?

**Comment by AshleyScirra** [comment]
It does prioritise loading the image. But if the image loads slowly, it shows the progress bar alone until then.
