### ISSUE TITLE
When I export a game to iOS there are black bars and the screen is not centered

### ISSUE THREAD

**Issue by mammothinc** [Scirra/Construct-3-bugs#3244]
I have exported the game via Cordova. In the previous bug, I have now pushed the cover button. 

It still isn't centred properly. 

![IMG_9070](https://user-images.githubusercontent.com/31543676/63462359-98e1d000-c40f-11e9-9389-7a471750ba17.png)

Here is the file 

https://www.dropbox.com/s/ypu9mh8savydohe/Crow%20Flying%20Preschool%20game%20p51%20John.c3p?dl=0

**Comment by shortercode** [comment]
When you say "exported via cordova" are you exporting as a cordova project, then building that project locally or on PhoneGapBuild?

**Comment by mammothinc** [comment]
When I say exported to Cordova, it's an Xcode project. I'll attach the Xcode Project as well. 

[Flappy_Learn_Preschool.ios.project_4 v2ak 2.zip](https://github.com/Scirra/Construct-3-bugs/files/3530651/Flappy_Learn_Preschool.ios.project_4.v2ak.2.zip)

**Comment by shortercode** [comment]
Mmm that's not what I'm seeing unfortunately. I presume that is a physical device? What model and iOS version is that?

<img width="879" alt="Screenshot 2019-09-02 at 16 57 08" src="https://user-images.githubusercontent.com/9051865/64125895-92563f80-cda3-11e9-9d41-19a28a51ea3b.png">

**Comment by mammothinc** [comment]
I just tested it again and the problem is gone. What? Meanwhile, a newer game that I exported has the same issue. I don't get it.

**Comment by shortercode** [comment]
The iPhone X behaves weirdly. The fact that we had to put in place specific hacks to prevent it doing this kinda tells you that. The fact they don't always works doesn't surprise me, but it is very frustrating. I'm afraid I don't have answers as to why it might not always be working. I've been meaning to look into better ways to resolve this issue, but I haven't come up with a good starting place yet.

**Comment by shortercode** [comment]
Closing this issue, as I wasn't able to reproduce it and the OP isn't experiencing the issue anymore. We should look into improving the iPhone X layout workarounds at somepoiint though.
