### ISSUE TITLE
Using "Fade Audio" Action Ignores Master Volume

### ISSUE THREAD

**Issue by AySquirrel** [Scirra/Construct-3-bugs#3245]
When using the "fade volume" action while the master volume is set to a value lower than 0 db (let's say -10 db in this case), the volume will fade in to 0 instead of -10 when fading in audio. This effect can be seen with fading out audio as well, as audio that is playing at -10 and then programmed to fade out to -100 will suddenly jump up to 0 and then fade out from there instead of fading out from -10.

## Attach a .c3p

[Audio Fade Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3527189/Audio.Fade.Bug.zip)

## Steps to reproduce

Fading Out

1. Start the layout
2. Press the top left button to start the song, taking note of what volume it's playing at
3. Press the top right button to fade out the song, and notice that is suddenly jumps in volume

Fading In

1.  Start the layout
2. Press the top left button to start the song, taking note of what volume it's playing at
3. Press the bottom right button to fade in the song, and notice that it fades in to a volume higher than what it was originally playing at

## Observed result

The volume fades in to 0 db and fades out starting at 0 db instead of the master volume, -10 db.

## Expected result

The volume to fade in to the master volume and fade out starting the master volume

## More details

**Affected browsers/platforms:** 

Chrome, Firefox

## System details

<details><summary>View details</summary>

Platform information
Browser: Opera
Browser version: 62.0.3331.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 OPR/62.0.3331.116
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 3.6 gb (5.8%)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Persistent storage is not available. Local storage could be deleted by the browser.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
