### ISSUE TITLE
Timeline properties object crashing c3 editor

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3246]
## Problem description
Was tring timeline bar, and on few clicks it crashed editor. Clicking on retangle object on timeline crashes C3 editor.
See pic below, inside yellow circle are object that crash c3 editor.
![timelinecrash](https://user-images.githubusercontent.com/28864889/63480119-6086d400-c499-11e9-9ba5-25c7a1f23d6f.jpg)

## Steps to reproduce

1.Open new -> create sprite
2.Project UI -> timeline -> add new timeline
3.Timeline bar - > add instance -> X value has some retangle object on timeline bar -> click it
4.

## Observed result
Clicking retable object on timeline bar results instant c3 crash

## Expected result
No crash when clicking  on timeline bar.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r161/main.js, line 2, col 93932
Message: Uncaught TypeError: expected function
Stack: TypeError: expected function at Function.ǃix (https://editor.construct.net/r161/main.js:2:93938) at Function.ǃ$ (https://editor.construct.net/r161/main.js:2:126673) at Object.ǃwn (https://editor.construct.net/r161/components/bars/propertiesBar/propertiesBar.js:1:65145) at n.ǃLi (https://editor.construct.net/r161/components/bars/propertiesBar/propertiesBar.js:1:65397) at n.ǃnh (https://editor.construct.net/r161/components/bars/propertiesBar/propertiesBar.js:1:46291) at e.ǃtiz (https://editor.construct.net/r161/components/bars/timelineBar/timelineBar.js:1:160145) at Array. (https://editor.construct.net/r161/components/bars/timelineBar/timelineBar.js:1:158743) at Object.ǃXHX (https://editor.construct.net/r161/main.js:2:194607) at Object.dispatchEvent (https://editor.construct.net/r161/main.js:2:192475) at Function.ǃtMc (https://editor.construct.net/r161/components/bars/timelineBar/timelineBar.js:1:137187)
Construct 3 version: r161
URL: https://editor.construct.net/r161/
Date: Thu Aug 22 2019 04:44:55 GMT+0300 (Eastern European Summer Time)
Uptime: 38 s

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r161 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed on the next beta, this was a regression from the previous version.
