### ISSUE TITLE
Construct 3 crashes after add overlay-effect (r162)

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#3247]
## Problem description

Construct 3 (Desktop) crashes when i add the overlay-effect to the sprite object:

> Error report information
> Type: unhandled exception
> File: https://editor.construct.net/r162/components/editors/layoutView/layoutView.js, line 1, col 43405
> Message: Uncaught ReferenceError: ǃIM is not defined
> Stack: ReferenceError: ǃIM is not defined at r (https://editor.construct.net/r162/components/editors/layoutView/layoutView.js:1:43405) at Function.ǃIZ (https://editor.construct.net/r162/components/editors/layoutView/layoutView.js:1:44385) at a.ǃcTT (https://editor.construct.net/r162/projectResources.js:1:244041) at a.ǃZi (https://editor.construct.net/r162/projectResources.js:1:243063) at Q.ǃZi (https://editor.construct.net/r162/projectResources.js:1:226642) at Object.ǃHL (https://editor.construct.net/r162/components/editors/layoutView/layoutView.js:1:7249) at https://editor.construct.net/r162/components/editors/layoutView/layoutView.js:1:1844
> Construct 3 version: r162
> URL: https://editor.construct.net/r162/
> Date: Thu Aug 22 2019 18:03:07 GMT+0200 (Mitteleuropäische Sommerzeit)
> Uptime: 74.9 s
> 
> Platform information
> Browser: NW.js
> Browser version: 0.38.0
> Browser engine: Chromium
> Browser architecture: 64-bit
> Context: nwjs
> Operating system: Windows
> Operating system version: 10
> Operating system architecture: 64-bit
> Device type: desktop
> Device pixel ratio: 1
> Logical CPU cores: 8
> Approx. device memory: 8 GB
> User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
> C3 release: r162 (beta)
> Language setting: en-US
> 
> WebGL information
> Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
> Numeric version: 2
> Supports NPOT textures: yes
> Supports GPU profiling: yes
> Supports highp precision: yes
> Vendor: Google Inc.
> Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
> Major performance caveat: no
> Maximum texture size: 16384
> Point size range: 1 to 1024
> Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Attach a .c3p

[Download example](https://drive.google.com/open?id=1ySWc8lzhuigZi4uPMaXvYNDFIaDjzFqu)

## Steps to reproduce

1. Open example-file
2. Add overlay-effect to the sprite
3. crash

## Observed result

Construct 3 crashes

## Expected result

No crash

## More details

**Affected browsers/platforms:**
Tested on Construct 3 Desktop

**First affected release:**

Problem is only on : **r162 Beta**

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r162 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 46 gb
Storage usage (approx): 461 mb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by LukeWolfGames** [comment]
Please consider testing this by adding the sprite to a layout and then adding the effect to the sprite when you are not viewing the layout and see if that does not cause a crash. If it doesn't cause a crash, view the layout the sprite was placed on.

**Comment by AshleyScirra** [comment]
This was affecting any projects using effects, so released an r162.2 patch to fix this which is now out.
