### ISSUE TITLE
failed to load javascript code use  in this events please check all your javascript codes has valid syntex

### ISSUE THREAD

**Issue by YashKute** [Scirra/Construct-3-bugs#3248]
## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by YashKute** [comment]
please help me

**Comment by shortercode** [comment]
@YashKute Please refer to our [guidelines](https://github.com/Scirra/Construct-3-bugs/blob/master/README.md) on filing bugs.

> ## Read these guidelines or your bug may be closed!
> Many users file bugs which are useless because they don't contain enough information for us to do anything about them. We just close these bugs without investigating them. Please follow these guidelines to avoid having your bug closed and help make sure we can fix the bug you're reporting.

> ## Use the bug report template
> The bug submission page is pre-filled with a template. We need all this information to help you. Do not delete it. Please provide as much of the requested information as you can, including the system details or crash report information with every report.

This sounds like you have a typo in your project. If you believe that the JavaScript code in your project is valid then please file an issue **with the template completed** for us to investigate. If you need help with writing JavaScript you will likely find help easier to come by on the forums.
