### ISSUE TITLE
Crash when selecting tab in editor that has Sprites with Glass effect

### ISSUE THREAD

**Issue by LukeWolfGames** [Scirra/Construct-3-bugs#3250]
## Problem description

Selecting a layout that has a sprite object with the Glass effect.

This crash is similar to #3247 except it's specifies the Glass effect causing the crash only when viewing the layout the effect is on from the editor and not from just purely adding the effect.

## Attach a .c3p

https://www.dropbox.com/s/qlg6bfuuh9s3tgv/Crash%20when%20selecting%20tab%20with%20a%20sprite%20object%20that%20has%20the%20Glass%20effect.c3p?dl=0

## Steps to reproduce

1. Go to Layout 2 if you are not already on it.
2. Add the Glass effect to the sprite object from the project bar
3. Go to Layout 1 (the location where the Sprite object has already been placed)

## Observed result

Crash.

## Expected result

No crash and view the selected layout in the editor.

## More details
Could impact projects with object banks which have glass effect on.
This seems to be impacting other effects as well. It is recommended to test other effects.

**Affected browsers/platforms:** Desktop (untested on browsers)

**First affected release:** r162 (this crash does not happen on other releases).

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r162/components/editors/layoutView/layoutView.js, line 1, col 43405
Message: Uncaught ReferenceError: ǃIM is not defined
Stack: ReferenceError: ǃIM is not defined at r (https://editor.construct.net/r162/components/editors/layoutView/layoutView.js:1:43405) at Function.ǃIZ (https://editor.construct.net/r162/components/editors/layoutView/layoutView.js:1:44385) at a.ǃcTT (https://editor.construct.net/r162/projectResources.js:1:244041) at a.ǃZi (https://editor.construct.net/r162/projectResources.js:1:243063) at Q.ǃZi (https://editor.construct.net/r162/projectResources.js:1:226642) at Object.ǃHL (https://editor.construct.net/r162/components/editors/layoutView/layoutView.js:1:7249) at https://editor.construct.net/r162/components/editors/layoutView/layoutView.js:1:1844
Construct 3 version: r162
URL: https://editor.construct.net/r162/
Date: Fri Aug 23 2019 10:53:14 GMT+1000 (Australian Eastern Standard Time)
Uptime: 592.4 s

Platform information
Browser: NW.js
Browser version: 0.40.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.40.1 (like Chrome/76.0.3809.100)
C3 release: r162 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
It's an identical crash report so closing as duplicate.
