### ISSUE TITLE
Audio preview has button with no function

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#3256]
## Problem description

There seems to be a button without any function when previewing audio.

## Steps to reproduce

1. Open any example project with audio
2. Right click to preview file from project bar
3. Click on "3 dots" and notice no function

## Observed result
Button with "3 dots" inside audio preview has no function.
![AudioButton](https://user-images.githubusercontent.com/15656049/63614907-6c32e180-c5e4-11e9-9c11-6b2535ed3585.PNG)

## Expected result

I assume it offers some additional features?

## More details
Most recent beta release with Chrome.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r162.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 111 gb
Storage usage (approx): 632 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a built-in feature of Chrome and it looks like a recent change (I don't recall seeing a menu button there before). On other sites it looks like it opens a menu with a 'Download' option. I'm not sure why clicking it does nothing, it might be a Chrome bug.

**Comment by AshleyScirra** [comment]
Yeah, looks like a Chrome bug - the menu appears but in the wrong location. Might be something to do with the fact it's in a dialog. Will file an issue with Google soon.

**Comment by TheRealDannyyy** [comment]
Alright thanks for doing the work. Feel free to close after posting a link to the bug report.

**Comment by AshleyScirra** [comment]
Filed here: https://bugs.chromium.org/p/chromium/issues/detail?id=998106
