### ISSUE TITLE
sprite font vertical alignment bug

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3258]
## Problem description
sprite font vertical alignment top works okay but 
spritefont vertical alignment bottom does not. you cannot see the bottom of the text, you still see the top if there is no room for more text, so it shows old text instead of new text

## Attach a .c3p
https://puu.sh/E8Nsb/d2cda6320a.c3p

## Steps to reproduce
https://puu.sh/E8Nqc/dedd7c678b.mp4

1.
2.
3.

## Observed result
the bottom most text dissapears

## Expected result
the top most text to dissapear

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release
