### ISSUE TITLE
Sound sfx not playing after exporting

### ISSUE THREAD

**Issue by Bigbeto123** [Scirra/Construct-3-bugs#3263]
## Problem description

When I run the nw.exe generated by the exportation of my projects, no sounds (except for the music) play correctly... They're all mute. 
[GJ.zip](https://github.com/Scirra/Construct-3-bugs/files/3537921/GJ.zip)
PS.: Also, the "stop all sounds" action is NOT working correctly over the "Death" group.

## Steps to reproduce
Export my project (I've tried with preload sounds on/off and minify on/of, and nothing changed) and then run the nw.exe. The footsteps, gun shot and death sounds won't play (even though they play correctly on the preview mode)

1.Explained right above
2.
3.

## Expected result
Sound sfx SHOULD play like they do on the preview mode.

## More details
...

**Affected browsers/platforms:** 
Chrome, Windows

**First affected release:** 

Windows 10 Pro

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 6.3 gb
Storage usage (approx): 736 mb (11.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by Bigbeto123** [comment]
Third bug I ran into just in 3 days...
Getting quite frustrated with Construct.

**Comment by AshleyScirra** [comment]
It's not a bug. Your sounds are in MP3 format, which is not supported on all platforms. Note the manual entry on [Sounds & music](https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/sounds-and-music):

> To ensure your audio can be played across a wide range of platforms, Construct will encode them to WebM Opus when importing, if possible. It is recommended to import 16-bit PCM WAV files to ensure they can be encoded without any unnecessary quality loss.

In short, import WAV files and they'll be transcoded to WebM Opus for you and everything will work. Otherwise you will need to transcode them to WebM Opus yourself using other software to guarantee that they can play on all platforms.
