### ISSUE TITLE
Unable to save file. Try checking you have permission to access the chosen folder.

### ISSUE THREAD

**Issue by Bat-Computer** [Scirra/Construct-3-bugs#3264]
## Unable to save a Project or Single File in Construct 3 Windows 10 Desktop App.

Construct 3 Windows 10 Desktop App (Version Release r162.2 beta) is showing an error when attempting to save a project or file. The error is:

**Unable to save file. Try checking you have permission to access the chosen folder.**

[https://imgur.com/Uh5ARMZ](url)

![error](https://user-images.githubusercontent.com/40317509/63649423-32bdbb80-c735-11e9-8907-ebc18f1d80ac.jpg)

## Steps to reproduce
Just open any project and attempt to save.
The older Desktop version (Not Windows 10 app) is able to save (Version: Release r157 stable).

## Observed result

An error is produced stating you don't have access to save a project or file. A file is created, but it is 0kb.

## Expected result

You would expect the file to save.

## More details

**Affected Version:** 

Release r162.2 beta

## System details

Windows 10 64bit, 8GB Ram etc.

**Comment by AshleyScirra** [comment]
I think we have a fix for this in the next release, but it's difficult to test this right now, so will check when it's out.

**Comment by AshleyScirra** [comment]
Looks like it's working correctly now in r163.
