### ISSUE TITLE
Array Editor issue on displaying data table

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3265]
when we do switch between layout or event sheet and array editor then data table doesn't show unless we do cursor hover over width editing text-box.

no need .c3p file 

## Steps to reproduce

1. create new empty project
2. create new array in **files** folder
3. give it a width and height 
4. Now do switch between layout, event sheet and then array editor in the last and do not move your mouse.( see array editor's data table not showing)
5. Now move mouse and hover over the width text box (now data editor will be visible)
## Observed result

data table is hidden until we hover over the width of table.

## Expected result

always visible

## More details

**Affected browsers/platforms:** 
Chrome , Windows

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
It appears to be a Chrome bug. Certainly I cannot reproduce this on Firefox.

A more precise reproduction:
1. create project
2. create new array
3. switch to another tab
4. switch back
5. observe editor is not visible
6. move mouse over one of the array editor toolbar text boxes
7. observe still no editor
8. move mouse off of text box
9. observe editor appear

I checked and certainly we are drawing the editor, it's the correct size and place. But Chrome does not draw it. Moving off of the text box triggers a chrome paint for the editor, and it then appears. So the text box isn't really all that special, just happens to trigger a paint when the mouse leaves it's bounding box.

While debugging I realised we are resizing the editor to (0, 0) when the tab is closed, I added a case to prevent this and the bug doesn't appear to occur anymore. So my best guess is that there is a race condition in Chrome related to the fact it was briefly has no size during a paint, but then didn't trigger a new paint when it was resized.

**Comment by shortercode** [comment]
I've added a patch for the next release, given the potential impact I will also migrate it to the upcoming stable as well.
