### ISSUE TITLE
Remote preview doesn't work starting on r150 onwards

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3268]
## Problem description
Remote preview doesn't work starting on r150 onwards on my tablet, it displays 

## Attach a .c3p
affects every single project, even empty ones

## Steps to reproduce

1.
2.
3.

## More details

149 works: 
![image](https://user-images.githubusercontent.com/32940085/63660725-c7500a00-c785-11e9-997e-b60cf7b6bce2.png)

r150 and all versions afterwards do this :
![image](https://user-images.githubusercontent.com/32940085/63660789-1433e080-c786-11e9-83f3-80cf77db3c8d.png)
![image](https://user-images.githubusercontent.com/32940085/63660844-3d547100-c786-11e9-9c29-b83cc1dbe440.png)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.111
Browser engine: Chromium
Browser architecture: 32-bit
Context: browser
Operating system: Android
Operating system version: 5.1.1
Operating system architecture: 32-bit
Device type: mobile
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 1 GB
User agent: Mozilla/5.0 (Linux; Android 5.1.1; KFARWI) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.111 Mobile Safari/537.36
C3 release: r157 (stable)
Language setting: en-US
 
Local storage
Storage quota (approx): 344 mb
Storage usage (approx): 43 mb (12.6%)
Persistant storage: No
 
Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.
 
Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Imagination Technologies
Renderer: PowerVR Rogue G6200
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:
 
EXT_color_buffer_float
EXT_texture_filter_anisotropic
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_pvrtc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:
 
Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:
 
WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:
 
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:
 
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I tried r162.2 and it works fine here. Try clearing your browser cache.
