### ISSUE TITLE
Error: unable to attach BBString link handler

### ISSUE THREAD

**Issue by Vultwo** [Scirra/Construct-3-bugs#3270]
## Problem description

When I try to export the project using Android there is a message saying: "Project can't be exported". The console error log says:

Error exporting:  Error: unable to attach BBString link handler
    at Object.ǃ_vY (/r162-2/main.js:2)
    at Function.ǃucM (/r162-2/main.js:2)
    at Object.ǃte (/r162-2/main.js:63)
    at a.ǃ_aL (/r162-2/projectResources.js:17)
    at async Object.ǃPW (/r162-2/main.js:210)
ǃPW @ /r162-2/main.js:210

When I set the language to English there is no error message (Dutch does show an error) and the build automatically fails after sending it to the server.

## Attach a .c3p

https://www.dropbox.com/s/v41pqbe2cocr5f8/test.c3p?dl=0

## Steps to reproduce

1. Export Project
2. Choose Android (Cordova)

## Observed result

Project can't be exported.

## Expected result

Exporting the project

## More details

**Affected browsers/platforms:** 

Chrome
Android
r162-2

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r162.2 (beta)
Language setting: nl-NL

Local storage
Storage quota (approx): 230 gb
Storage usage (approx): 101 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Vultwo** [comment]
Note: My big project won't export when I set the language to English, but the empty attached test.c3p does export to android when the language is English (takes some time though).

**Comment by Vultwo** [comment]
I have fixed my problem! I had my whole store description pasted inside the project's description box. Removing the last 5 paragraphs fixed my problem.

**Comment by AshleyScirra** [comment]
I can't reproduce with the attached project. I can proceed with an Android export just fine (I used the mode 'Cordova project' since you didn't specify one).

Your last comment suggested the project description caused it; the description of the attached project is only the word "test". Export should not crash even if you use a very long description. Please file an issue including the project with the full description that caused the problem so we can investigate.
