### ISSUE TITLE
Pressing D will disable the JS script but won't show anything

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#3275]
## Problem description

Added more info for #3266 

The shortcut "D" to disable a script "action" doesn't show any feedback that it's disabled. There is also no menu item when right clicked to "toggle disabled"

![Disabled script block problem](https://user-images.githubusercontent.com/7268697/63859557-46c12180-c9b0-11e9-9a54-785f6049a143.gif)

## Attach a .c3p

[Script problem.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3551081/Script.problem.c3p.zip)

## Steps to reproduce

1. open an empty project
2. On start of layout condition -> make a script as action with a basic alert
3. select the script (so the action only) and press D
4. run the project

## Observed result

Script won't run, there is no feedback that it's disabled

## Expected result

I expect it to see it disabled

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r 157

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 171 gb
Storage usage (approx): 321 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon 550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Your using the stable release right? I don't think the stable supports disabling scripts, it's only in the beta channel at the moment.

**Comment by JeFawk** [comment]
@shortercode it's r157 indeed, however the disable works, it just doesn't show visually in the editor. This made me waste about an hour cause I accidentally disabled a script, and then I was wondering why it won't work :) (cause I didnt realize it was disabled)

**Comment by shortercode** [comment]
Ah interesting... I expect it's working by accident! Sorry to hear about the confusion, but hopefully we can get the next stable out soon so it won't happen again.

In r163 it shows the text with a strikethrough and has a `toggle > disable` option in the context menu.

**Comment by AshleyScirra** [comment]
It appears to be working fine in r163. As per the bug report guidelines please only report issues that reproduce in the latest release, to avoid reporting issues we've already fixed.

**Comment by JeFawk** [comment]
You're right, it is fixed, sorry about that.
