### ISSUE TITLE
Find all references shows events and actions as deactivated.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3277]
When you search something everything looks okay but if you right click an object and click find all references, it will show shows events and actions as deactivated.

## Steps to reproduce

1.
2.
3.

## Observed result

163 Beta

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can't see any way to investigate this so closing. Please always follow the bug report guidelines
