### ISSUE TITLE
Platform behavior: walking past a Jumpthru object causes an automatic jump

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#3278]
## Problem description

With the platform behavior, while walking down a slope, if you pass by a sprite with the "jumpthru" behavior you are propelled into the air — it's as if you've walked over a bump!

![image](https://user-images.githubusercontent.com/5744908/63940725-68ec9980-caad-11e9-870c-3d5323b3dd26.png)

## Attach a .c3p

[JumpThru BUG.zip](https://github.com/Scirra/Construct-3-bugs/files/3555550/JumpThru.BUG.zip)

## Steps to reproduce

1. walk right
2. watch the player's animation, it will change when they're in the air
3.

## Observed result

Bouncing in the air 

## Expected result

Stay on the ground

## More details

Tested beta with Chrome and stable on Desktop build

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
These cases are super difficult to deal with, and I suspect is down to the fact jump-thrus don't support slopes, but this has been introduced by overlapping a jump-thru with a solid slope. However I don't see any reason why you'd need to use tall jump-thru objects like that. Why not just make them thin platforms along the top edge like this?

![platform-workaround](https://user-images.githubusercontent.com/768723/63953626-9a4b7200-ca79-11e9-8481-c6dca3d3c35e.png)

As far as I can tell this collides exactly the same as before with regards to how you can jump on top of them, and avoids these weird large-areas-of-jumpthru that the engine was not designed to handle. If there's no reason to use tall jump-thrus, I'd rather avoid spending hours digging in to yet another platform edge case.

**Comment by SnipG** [comment]
Better is to set collision polygon like this:
![jumpThru](https://user-images.githubusercontent.com/28864889/63975259-465f7e00-cab7-11e9-82c7-987aac43618e.jpg)

So they still look the same, but no bugged behavior.

**Comment by alastajj** [comment]
The ones in my games are like ladders/trees, I have to be able to overlap them to climb them, but I want to be able to stand on top. 

I suppose I could just workaround, and apply an additional sprite on top for detection.

**Comment by alastajj** [comment]
I also give some enemies jumpthru as well, so the player can jump on them. 

The best method as it appears to me is to, on level start, create and attach a separate thin jumpthru sprite to every object in a family.

**Comment by alastajj** [comment]
It's possible to have Jumpthru on physics objects too, so you'd want to have the collision polygon using the proper shape there too.

**Comment by SnipG** [comment]
I think there should be way to simulate jumpthru with other behaviors. change pushout angle for platform behavior etc.
Ashley would never able to cover all the cases.

With platform and jumpthru, not to mention others. There are hundrets of edge cases like this bug report. If you mix behaviors together with multiple ways, strange behaviors happen. It would be good if you can change the base solid interaction a bit more ways(like custome behaviors does it) and make few events to simulate same jumpthru effect.

**Comment by AshleyScirra** [comment]
> The ones in my games are like ladders/trees, I have to be able to overlap parts at the bottom to climb them, but I want to be able to stand on top.

I don't understand why this is necessary for a ladder. A tall jump-thru object is not like a ladder, since you can't land on a jump-thru half-way up, only when landing on top. Therefore only the top edge of a jump-thru object really matters, so there's no need to make it tall. It sounds like any issues with tall jump-thrus can be worked around just by doing that (or pinning a jump-thru object where necessary), so I don't think there's a case to figure out another difficult platform edge-case, especially since in the past such changes have been particularly likely to break other aspects of the platform behavior.
