### ISSUE TITLE
Apply to whole animation new option idee

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#328]
Another suggestion 

in edit collision polygon mode when we right clic on the collision polygon we can choose > Apply to whole animation (or to all animations)

It would be great to let us choose : 

- Apply to whole animation / Stretch
or
- Apply to whole animation / Align center

The option stretch is the actual default option
Align center would keep the same polygon to all the frames. that would be very useful

**Comment by AshleyScirra** [comment]
I'm closing all issues here which are suggestions not already in C2. We want to focus on bugs only in this tracker, or minor TODOs. For new features please write up suggestions at: https://construct3.ideas.aha.io/
