### ISSUE TITLE
Bullets travel through solids

### ISSUE THREAD

**Issue by BanksySan** [Scirra/Construct-3-bugs#3280]
## Problem description

Bullets contained withing solid sprites will escape the container (bounding sprites)

## Attach a .c3p

[Bounding Containers.c3p](https://drive.google.com/file/d/1DZmmNT8-QfUCoqFLqq5jauHDusfP8K6N)

## Steps to reproduce

1.  Create a set of sprites with the _solid_ behavior and arrange them so they there is a contained void (e.g. box/circle/some other closed polygon).
2.  Put a sprite in the contained area; give the sprite the _bullet_ behavior and the bounce off solids bullet property.
3.  Run project, the sprite will bounce around for some time, then it will escape the bounds.

## Observed result

Sprite passes through solid boundaries.

## Expected result

Sprite cannot escape boundaries.

## More details

The attached example shows this behavior with thin walls, thick walls and with walls overlapping each other.

Construct 3 IDE

**First affected release:** Unknown.  Only tested on `r157 (stable)`

## System details

```plaintext
Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 102 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2070 with Max-Q Design Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
```

**Comment by shortercode** [comment]
This is known restriction with the bullet behaviour. It tests for collisions by moving forwards and then checking if it is inside a solid, if it is then it moves backwards and emits a collision event. You can improve this with stepping but if your using fast bullets and small walls it will still be a problem.

I will leave this open in case @AshleyScirra has anything to say, but I don't believe this will change.

I can think of 2 potential workarounds. The first is to use the physics behaviour, but I'm not sure if Box2D has similar stepping problems with fast moving objects or not.

The second is to roll your own system using the Line of Sight behaviour. It includes ray tracing methods that can find the exact point of collision with solids ( if any ) and allow you to calculate the path reflected off the surface as well. The downside of this system is that it only allows you to simulate a point, but as your examples use bouncing balls this might be enough?

**Comment by shortercode** [comment]
[Bounding Containers Revised.zip](https://github.com/Scirra/Construct-3-bugs/files/3559763/Bounding.Containers.Revised.zip)

I tried out the raycasting idea, works pretty well. Only needs a few events. Worth noting it cannot simulate gravity like the bullet behaviour can, because that require that the projected ray be a curve. But the example does do acceleration. Bear in mind that because it needs to recurse on each bounce if it gets too fast then it will probably overflow the call stack. So it probably makes sense to add a limit to the speed somehow. Perhaps calculate acceleration using a constant propulsive force and air resistance derived from current velocity?

```javascript
travel(velocity * dt)
velocity = velocity + dt * (100 + velocity * -0.1) // should max out at velocity of 1000 I think
```

**Comment by AshleyScirra** [comment]
This is what bullet stepping is for. See the [manual entry](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/bullet).
