### ISSUE TITLE
Bookmark and breakpoint icons aren't ment to work together

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3284]
## Problem description
Bookmark and breakpoint icons won't work together, and vice versa. It's rare someone use them together, so not sure if it should work better.
See image:
![BookmarkBreakepoint](https://user-images.githubusercontent.com/28864889/64049945-40cd6b00-cb7f-11e9-9354-966c211b5e31.jpg)

## Steps to reproduce

1.Open new project
2.Add event
3.Toggle breakpoint and bookmark to same event

## Observed result
Two icons won't work together

## Expected result
Breakpoint and bookmark should have merged icon, something cool that fits the empty space. Just 1 icon without need for extra empty space

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r163 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.4 gb (10.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
@AshleyScirra Should we use a new single icon that combines a bookmark and a break point? Or should I just make the icons smaller in the the case both are shown?

**Comment by AshleyScirra** [comment]
I don't know what to do about this, really. Basically there's no room for the icons. It probably needs a change to the design of the event sheet view to fix. However I'd prefer not to make a design change if the issue is regarded as relatively minor. @SnipG - can you live with this?

**Comment by AshleyScirra** [comment]
I think the easiest way to solve this actually is just to let the icons overlap the event number when it runs out of space. I found some CSS styles to do that so that's done for the next beta.

**Comment by SnipG** [comment]
I don't rly need this, i just saw it and reported. From my view maybe if breakpoint is ontop of bookmark or close to would look nicer then overlapping some other element.
![045](https://user-images.githubusercontent.com/28864889/65536080-58dca400-df0b-11e9-8ce3-d66943146534.jpg)
