### ISSUE TITLE
Unexpected result from loading a data URI with "Resize to image size" 

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-3-bugs#3287]
## Problem description

Changing the window size changes the size of the loaded image.
The DrawingCanvas in the attached .c3p file is always 256x256 so i would expect "Resize to image size" would mean that the sprite sets its size to 256 x 256 as well.
Idk if this is the desired behavior, but if it is it certainly doesn't feel intuitive.

## Attach a .c3p

[bug_resize_to_image_size.zip](https://github.com/Scirra/Construct-3-bugs/files/3562001/bug_resize_to_image_size.zip)

## Steps to reproduce

1. Open bug_resize_to_image_size.c3p and start a preview
2. Change the size of the preview window
3. The image on the right should become bigger and smaller

## Observed result

The image loaded into the 128x128 sprite changes to random sizes dependent on the window size
![resize](https://i.imgur.com/RV1Jm5v.gif)

## Expected result

The image should be set to the size of the data URI image in resolution and size. So it should have the same size as the original image on the left.
![expected](https://i.imgur.com/aEuyzpj.png)

## More details

**Affected browsers/platforms:** 

Desktop r157 stable
Chrome r163 beta

**First affected release:** 
???

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.40.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.40.1 (like Chrome/76.0.3809.100)
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 8388608 tb
Storage usage (approx): 336 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 760 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's not a bug; the Drawing Canvas resolution is changing with the window size, and the sprite is adopting the size of the Drawing Canvas surface, hence the change in size. See the section on handling resizing and resolution in the [Drawing Canvas manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/drawing-canvas):

> By default, the canvas uses the same display resolution as the game. However the display resolution usually changes when the window is resized...

I did spot a crash happening in the engine while previewing this though so I'll leave this open for me to investigate that separately.
