### ISSUE TITLE
DrawingCanvas doesn't use the projects sampling setting

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-3-bugs#3288]
## Problem description

The DrawingCanvas plugin doesn't use the projects sampling setting, in the attached .c3p file the sampling in the project is set to Nearest but the DrawingCanvas behaves more like it is set to Bilinear or Trilinear sampling

## Attach a .c3p

[drawing_canvas_bugs_03.zip](https://github.com/Scirra/Construct-3-bugs/files/3562129/drawing_canvas_bugs_03.zip)

## Steps to reproduce

1. Open drawing_canvas_bugs_03.c3p 
2. Look at the project properties sampling setting
3. Start a preview
4. The image should switch between blurry ( DrawingCanvas ) and none blurry ( Sprite )

## Observed result

The DrawingCanvas is blurry when resized 
![DrawingCanvas](https://i.imgur.com/Y28PBoz.png)

## Expected result

The DrawingCanvas respects the sampling mode set in the projects properties and looks the way a sprite looks when scaled up with nearest neighbor.
As with #3286 it would be the best to have an option for the DrawingCanvas to choose the sampling mode it uses.
![sprite](https://i.imgur.com/CVKCuXU.png)

## More details

**Affected browsers/platforms:** 

Desktop r157 stable
Chrome r163 beta

**First affected release:** 
???

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.40.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.40.1 (like Chrome/76.0.3809.100)
C3 release: r157 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 8388608 tb
Storage usage (approx): 337 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 760 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release.
