### ISSUE TITLE
Importing sounds: doesn't remember bitrate

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#3289]
## Problem description

![image](https://user-images.githubusercontent.com/5744908/64061931-14b7f580-cc24-11e9-937f-33682729074e.png)

It says 96kbs, even though last time I imported audio I used 128kbs. 

When you close the program it forgets the setting and goes back to 96kbs.

Using Stable Desktop.

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Fixed for next beta release.
