### ISSUE TITLE
Loading project with removed Behaviour crashes

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#329]
## Problem description

If you remove a 3rd-party Behavior and then try to load a c3p file, C3 crashes.

## Attach a .c3p

LiteTween has been converted. Load the plugin, load the demo capx, save as c3p.
https://www.scirra.com/forum/behavior-litetween_t70700?&hilit=litetween
https://www.dropbox.com/s/5dy6rz2mj94hp7j/lunarray.litetween.c3addon?dl=0
http://labs.magphi.com/files/litetweenv0.9.capx

## Steps to reproduce

1. Load the plugin (restart)
2. Load the demo CAPX
3. Save as C3P
4. Uninstall the plugin (restart)
5. Load the C3P file
6. (if you load the CAPX it actually catches the problem ;)

## Observed result

Crash log appended.

## Expected result

.

## Affected browsers

N/A

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'toString' of undefined @ TypeError: Cannot read property 'toString' of undefined at Function.ǃJ.ǃOEy (https://editor.construct.net/r30/main.js:2:260570) at ǃOTu (https://editor.construct.net/r30/main.js:2:268567) at ǃJ.ǃU.ǃUu.ǃyia.ǃOg (https://editor.construct.net/r30/main.js:149:15255) at Ce.ǃOcn.then.then.catch.Ie (https://editor.construct.net/r30/main.js:162:26364) at 
Stack: TypeError: Cannot read property 'toString' of undefined at Function.ǃJ.ǃOEy (https://editor.construct.net/r30/main.js:2:260570) at ǃOTu (https://editor.construct.net/r30/main.js:2:268567) at ǃJ.ǃU.ǃUu.ǃyia.ǃOg (https://editor.construct.net/r30/main.js:149:15255) at Ce.ǃOcn.then.then.catch.Ie (https://editor.construct.net/r30/main.js:162:26364) at 
Construct 3 version: r30
URL: https://editor.construct.net/
Date: Tue May 23 2017 07:44:15 GMT-0700 (Pacific Daylight Time)
Uptime: 12.5 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r30

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 6570 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r31.
