### ISSUE TITLE
Multiplayer host cannot send message to the peer but peer can!

### ISSUE THREAD

**Issue by Macmachi** [Scirra/Construct-3-bugs#3290]
## Problem description

If the PEER disconnects and then the HOST disconnects. If you reconnect to a room with the old PEER as HOST and the old HOST as PEER, the new HOST can no longer send a message to the new PEER while the new PEER sends messages 2 times to the new HOST.

## Attach a .c3p

https://mon-partage.fr/f/qlYZzVoA/

## Steps to reproduce

I wite steps in the example file too ;)

1. Login to the chat room on the login page with A HOST and A PEER
2. With the PEER (FIRST) Exit the chat room with the "Leave..." button then with the HOST. 
3. (No need step) You will be sent on a temporary layout... In my game it works like this
4. Wait to be returned from this layout to the layout login (it's automatic) 
5. Reconnect to the chat with the old PEER first he will become the new HOST and then connect the old HOST. He will become the new PEER. 
6. Now try to send messages with each (HOST and PEER)

## Observed result

The host cannot send messages while the peer can but they are sent in duplicate.

## Expected result

Send messages normally between host and peer

## More details

I used the chat template (multiplayer tutorial 1) to reproduce this bug

**Affected browsers/platforms:** BRAVE (chromium web browser) on windows 10, Chrome (windows 10), with remote preview from C3. 

**First affected release:**  r163 (beta)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r163 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 47 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Macmachi** [comment]
no update ? Please you need to fix this bug I cannot release my commercial game with a such bug.

**Comment by AshleyScirra** [comment]
Please refer to the "Why haven't you responded to my bug report yet?" FAQ question in the bug report guidelines.

**Comment by AshleyScirra** [comment]
This is not a bug, it's just a mistake in your events. The "Host" and "Peer" groups start deactivated, and the right one is activated when joining the room. However when you leave and restart, the groups are not deactivated again. So if you start as host then rejoin as peer, or vice versa, you end up with both the "Host" and "Peer" groups active, which is an incorrect state. If you deactivate both groups when leaving the layout it works correctly.
