### ISSUE TITLE
ALT + Shift + Arrow Keys shortcut for navigation isn't working.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3293]
## Problem description

ALT + Shift + Arrow Keys shortcut for navigation isn't working without clicking the window if there is a textbox in the window. In r158 it was working as it should.

## Steps to reproduce

![19-09-02-02 25 34](https://user-images.githubusercontent.com/2965842/64083455-07d0fa00-cd29-11e9-9674-5ec0f5862a84.gif)

1) Open an event or action window that has a textbox. 
2) try to use alt + shift + arrow keys to go forward or backward.

## More details

**Affected browsers/platforms:** 
chrome/desktop

**First affected release:** 
After r159. It is working fine in r158

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This was an intentional change in r159 to fix the following issue:

> Alt+Shift+Left/right no longer perform next/back navigation shortcuts when typing, since on some systems these navigate the caret

**Comment by bilgekaan** [comment]
Can we have an option for this, please? This shortcut makes editing events faster and I've been using it since 2013. It's like ctrl+c, ctrl+v for me. It's useless now because you need to click on the window to use it.

**Comment by AshleyScirra** [comment]
I'm not sure what keyboard shortcuts we have left that are available. For example shift+left/right selects text; ctrl+shift+left/right selects a word at a time; etc. I think we would have to pick an entirely different keyboard shortcut to not conflict with text selection shortcuts. What do you think would be appropriate?

**Comment by bilgekaan** [comment]
Thank you! What about "ctrl + shift + N" (next) ,  "ctrl + shift + B" (back)?

**Comment by bilgekaan** [comment]
any news?

**Comment by AshleyScirra** [comment]
I've added Alt+Shift+N/B for the next release.

**Comment by bilgekaan** [comment]
Thank you <3
