### ISSUE TITLE
HTML export causes an "invalid size" error when loaded in iframe

### ISSUE THREAD

**Issue by vanessaeggs** [Scirra/Construct-3-bugs#3295]
## Problem description

When using an iframe inside an ad unit, the hosted HTML throws an invalid size error and the project never loads (this happens intermittently).

## Attach a .c3p

[ScaleOuter.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3572005/ScaleOuter.c3p.zip)

## Steps to reproduce

1. Create iframe inside HTML unit
2. Load unit -> console shows an Error: Invalid Size warning
Example: http://justeggs.celtra.com/preview/751ed9a0

## Observed result

Nothing loads inside iframe

## Expected result

When using the same setup on C2 the iframe project loaded fine, since using C3 this error has become a problem. Usually projects load fine and can be used on multiple devices.

## More details

Link usually always loads on Samsung devices.
Desktop and iPhone are more temperamental and loading varies

**Affected browsers/platforms:** 
Tested across iPhone, Samsung and MacOS platforms

**First affected release:** 
Previously made a game on r157 and this error never occurred

**Comment by AshleyScirra** [comment]
I can't reproduce the problem with the given URL. I tried loading it 5 times and it appeared to work correctly every time. However there are no console messages at all; if the C3 runtime starts up normally it logs something, so it looks like the provided URL is not even loading a Construct project.

Without a way to reproduce this I have to rely solely on guesswork, and I guess from the error message you mentioned it's doing something weird like creating a 0x0 iframe and trying to load the project inside that. I've added a workaround for that in the next release, so I think all that can be done is wait for that to come out and test again.

**Comment by AshleyScirra** [comment]
r165 is now out, please check again with that!

**Comment by vanessaeggs** [comment]
Thanks Ashley, the update doesn't seem to help but we managed to find a workaround. 
If we loaded the game on a second page inside the iframe we never came across the invalid size issue, so we just wait for the first frame to load and re-direct it to the game and it all works fine. 

Thank you for looking into this

**Comment by GokulJagadheesan** [comment]
Hi, @AshleyScirra  I'm also facing the exact same issue. 
@vanessaeggs , can you please let me know what is the workaround you have made?

**Comment by vanessaeggs** [comment]
Hi @GokulJagadheesan 
My problem was loading from an ad unit, when clicked on, expanded to full screen. Once the initial full screen size loaded this is when the issue occured, I needed to redirect to a second screen at the expanded size and loaded the iframe in there. Hope this helps?

**Comment by GokulJagadheesan** [comment]
Thanks a lot, @vanessaeggs This helps. I'm also using Celtra expandable unit and this workaround solves the issue.

**Comment by Usvatron** [comment]
This exact same error is occurring again. I can't understand how the suggested (by vanessaeggs) workaround is done, @AshleyScirra can this please be fixed asap?

**Comment by vanessaeggs** [comment]
@Usvatron sorry I cant help
Both @GokulJagadheesan and myself were using Celtra when this error occured so the workaround is specific to this build

**Comment by Usvatron** [comment]
@vanessaeggs Thank you <3. Yeah, I'm not using Celtra. 
This messes up a lot of things for me and my customers, I wish there will be a fix soon.

**Comment by Usvatron** [comment]
Now that I've taken a closer look,
if I'm correct, it looks like the issue was already fixed in the last patch 3 days ago.

Phew and thanks!

**Comment by AshleyScirra** [comment]
If you still have trouble please file a new issue following all the guidelines. In general old, closed bug reports are not monitored and we will not be able to help you if you reply to them.
