### ISSUE TITLE
Since upgrade to stable r164 ,without changes the screen turns black when running the project with F4.

### ISSUE THREAD

**Issue by bartalluyn** [Scirra/Construct-3-bugs#3296]
Yesterday, on the old stable version everything was working correctly.  Today it no longer works with below error in the console 

My project uses no external plugins what so ever (I don't trust the backwards compatibility). And uses no javascript.  Furthermore it doesn't even use timelines (as it uses C3.TimelineManager in the message).

I've attached the full project, but I realise it's far from minimal.  It seems to me some bug that creeped into the last stable, so maybe other people have it too, but with more minimal projects.
If i'm the only one I'm will to slim down the project for you, but that feels like a lot of loss of time from my behalf for something that aught to be working actually.

In file : pluginSourceAdapter.js:1 Uncaught (in promise) TypeError: Cannot read property 

Uncaught (in promise) TypeError: Cannot read property 'GetPlugin' of undefined
    at a.Interpolate (pluginSourceAdapter.js:1)
    at C3.PropertyTrackState.Interpolate (propertyTrackState.js:1)
    at C3.TrackState.Interpolate (trackState.js:1)
    at C3.TrackState.SetInitialState (trackState.js:1)
    at C3.Tween.SetInitialState (timelineState.js:1)
    at C3.Tween.SetInitialState (tween.js:1)
    at C3.TimelineManager._OnTick (timelineManager.js:1)
    at Array._tickFunc (timelineManager.js:1)
    at C3.Event.Handler._FireNonCancellable (handler.js:1)
    at C3.Event.Dispatcher.dispatchEvent (dispatcher.js:1)
pluginSourceAdapter.js:1 Uncaught (in promise) TypeError: Cannot read property 'GetPlugin' of undefined
    at a.Interpolate (pluginSourceAdapter.js:1)
    at C3.PropertyTrackState.Interpolate (propertyTrackState.js:1)
    at C3.TrackState.Interpolate (trackState.js:1)
    at C3.TrackState.SetInitialState (trackState.js:1)
    at C3.Tween.SetInitialState (timelineState.js:1)
    at C3.Tween.SetInitialState (tween.js:1)
    at C3.TimelineManager._OnTick (timelineManager.js:1)
    at Array._tickFunc (timelineManager.js:1)
    at C3.Event.Handler._FireNonCancellable (handler.js:1)
    at C3.Event.Dispatcher.dispatchEvent (dispatcher.js:1)
Interpolate @ pluginSourceAdapter.js:1
Interpolate @ propertyTrackState.js:1
Interpolate @ trackState.js:1
SetInitialState @ trackState.js:1
SetInitialState @ timelineState.js:1
SetInitialState @ tween.js:1
_OnTick @ timelineManager.js:1
_tickFunc @ timelineManager.js:1
_FireNonCancellable @ handler.js:1
dispatchEvent @ dispatcher.js:1
Step @ runtime.js:1
async function (async)
Tick @ runtime.js:1
SetSuspended @ runtime.js:1
_OnVisibilityChange @ runtime.js:1
(anonymous) @ runtime.js:1
_OnEventFromDOM @ runtime.js:1
_OnMessageFromDOM @ runtime.js:1
_messagePort.onmessage @ runtime.js:1

## Attach a .c3p

not minimal, but if  you need my help to slim it down, please let me know.
[Hotels.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3572707/Hotels.c3p.zip)

## Steps to reproduce

Just start the project with F4.
should start a menu.  ==> turns black.

## Observed result

Black screen and error message in the developer tools

## Expected result

The project just starting

## More details

Google Chrome | 76.0.3809.132 (Officiële build) (64-bits)
-- | --
Revisie | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
Besturingssysteem | Mac OS X
JavaScript | V8 7.6.303.29
Flash | 32.0.0.238 /Users/bartalluyn/Library/Application Support/Google/Chrome/PepperFlash/32.0.0.238/PepperFlashPlayer.plugin
User-agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Opdrachtregel | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --flag-switches-begin --flag-switches-end
Uitvoerbaar pad | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Profielpad | /Users/bartalluyn/Library/Application Support/Google/Chrome/Default

first happened in r164

## System details

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r164 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 291 mb
Storage usage (approx): 94 mb (32.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GTX 775M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2047
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by bartalluyn** [comment]
Edit: just been testing a bit further, and the problem origin is easy to find with the attached project.

The problem lies in the fact that
1. There is a black overlay in the layout that should fade away in .2 seconds to add a fade in effect.
2. it uses a timer called "FadeInGameMenu" started on start of layout in _Game Menu_ event sheet, which is the standard event sheet behind the first layout. Logging shows that it actually does the logic, so it should start the timer
3. However, the handling over de timer (On Timer) is in another event sheet that is in included called _Menu Common Logic_;  At the bottom you see the trigger for the timer, and the call to a function that should start the fade.  According to my tests, the timer never fires, so the fade doesn't occur, so it stays black because the overlay is on top of all the rest.

The timer doesn't fire ... where it did yesterday in the prior version.
Maybe related to some stuff not being loaded because of the error message or something?

**Comment by shortercode** [comment]
Would appear to be an issue with a tween, assigning to @DiegoScirra to review.

**Comment by shortercode** [comment]
Possible related comment on the release https://www.construct.net/en/comments/22881

**Comment by DiegoScirra** [comment]
@bartalluyn

This bug is only triggered in the latest stable if you do a tween of the color property of a text plugin instance. In every other case it works properly. The stack trace can be misleading because under the hood tweens are a special case of timelines, so you see a lot of references to timeline related code, but little or no mention of tweens.

This will be fixed in the next beta, in the mean time, use the Find dialog **(Ctrl + F)**, to find all the places where those type of tweens are used and disable them or do something different. Search for **property Color** and you should be able to find all of them, they aren't that many.

**Comment by AshleyScirra** [comment]
Moving this over to stable patch.

**Comment by bartalluyn** [comment]
Thanks, that seems to have done the trick

Op wo 4 sep. 2019 om 15:06 schreef Ashley (Scirra) <notifications@github.com
