### ISSUE TITLE
Iframe "display HTML string" action not working in r164

### ISSUE THREAD

**Issue by cerxer** [Scirra/Construct-3-bugs#3298]
I use an iframe that displays simple HTML text. It worked in preview but when i export the project via Xcode or Cordova project, iframe failed on both builds. There was no problem in stable r157 version.

## Steps to reproduce

1. Create an iframe to display Html Text.
2. Set an iframe visible or invisible by action.
3. Export IOS project.

## More details

Started in version r164, no problem in r157. Error was:

ERROR: Exception in 'iframe' handler 'set-visible': TypeError: undefined is not an object (evaluating 't.style')

**Comment by AshleyScirra** [comment]
No project provided so used this one: 
[iframetest.zip](https://github.com/Scirra/Construct-3-bugs/files/3574350/iframetest.zip)
Tested with both remote preview & minified export and it worked fine.

Please always follow the bug report guidelines to ensure we can fix the problem you are reporting.

**Comment by cerxer** [comment]
I think the problem was "display html" action. I make 2 projects that you can check. r164 version not showing the text and the other is just fine. The error for r164 is: 

domSide.js:1 Exception in 'iframe' handler 'display-html': TypeError: Cannot read property 'src' of undefined
    at a._SetSrc (domSide.js:1)
    at a._OnDisplayHTML (domSide.js:1)
    at domSide.js:1
    at domElementHandler.js:1
    at e._OnEventFromRuntime (domSide.js:1)
    at e._OnMessageFromRuntime (domSide.js:1)
    at MessagePort._messageChannelPort.onmessage (domSide.js:1)


[test.zip](https://github.com/Scirra/Construct-3-bugs/files/3574445/test.zip)

**Comment by AshleyScirra** [comment]
I can reproduce now, and looks like it just happens in preview, no need to make it invisible or export it. This is why we require a project to be attached, it is essential for us to be able to investigate your report.

**Comment by AshleyScirra** [comment]
OK, fixed for next release. I think we'll have a stable patch coming out soon so this fix will go in with that.
