### ISSUE TITLE
Tilemap Duplicate with CTRL + Mouse Drag

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3299]
## Problem description

If you create more than one scene with a tilemap, when you duplicate it with CTRL + Mouse Drag, it duplicates the first scene no matter which you want to duplicate. It's not a big issue though, you can still copy and paste.

## Steps to reproduce

![19-09-04-13 51 06](https://user-images.githubusercontent.com/2965842/64248914-167f0300-cf1b-11e9-98a7-4f188f009df6.gif)

## More details

**Affected browsers/platforms:** Desktop

**First affected release:** r164

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Already fixed, it didn't make it into the last stable though. You'll be able to try this out in the next beta release.

**Comment by AshleyScirra** [comment]
@DiegoScirra - I take it this is a duplicate of #3251?
