### ISSUE TITLE
Renaming file does not update data editor tab name

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#33]
## Problem description

Open the Array editor for a new file. Rename the file in the project bar while the editor is open. The tab name does not update.

**Comment by shortercode** [comment]
Leaving this for now in the hope as it will be effected by the data editor enhancements, but if I don't have time to complete those I will fix the existing version in time for the game jam.

**Comment by shortercode** [comment]
Fixed
