### ISSUE TITLE
Error with imagepoints and scroll!

### ISSUE THREAD

**Issue by mundogame** [Scirra/Construct-3-bugs#330]
## Problem description

We cant add more image points.

## Steps to reproduce

1. Add a Sprite in Construct 3
2. Edit the Sprite to add imagepoints
3. Add many imagepoints, and you cant see more. The imagepoint window, dont have a scroll. If you have a low resolution, you see only near 10. In high resolutions, near 20 imagepoints.

In many projects, you need many imagepoints to make random spawnings or controls.

## Observed result

*What do you see happen?*
No scroll in the imagepoint window.

## Expected result

*What did you expect to happen instead?*
imagepoint window scrolling, to add and see more.

## Affected browsers

* Chrome: yes, affected

**Comment by AshleyScirra** [comment]
Please include the platform information as requested, so we don't have to ask for the information. Which Construct 3 version are you using?

**Comment by 3dParadox** [comment]
In r30 I see what he means, I see 32 image points before they extend out the bottom of the window.
Scroll wheel, touch and drag, cursor keys, nothing lets you select the bottom entered points.

You can add more, you just can't edit them after first placing them.

Unrelated, using the arranging arrows doesn't keep the focused point highlighted.

**Comment by DiegoScirra** [comment]
Fixed in r31.
