### ISSUE TITLE
failed to export project 

### ISSUE THREAD

**Issue by lealgabriel** [Scirra/Construct-3-bugs#3300]
I can't export any project to any platform.
[test.zip](https://github.com/Scirra/Construct-3-bugs/files/3574817/test.zip)

The error happens in any new project. I attached a test project, but basically any project gives the error, "failed to export project" for any platform.

**Comment by AshleyScirra** [comment]
That project exports just fine for me in r164. Please follow all the bug report guidelines otherwise we can't help.

It's also useful if you can press F12 to open the browser console and check if any error messages appear there.
