### ISSUE TITLE
Android exports not working with r164

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#3303]
## Problem description
Running remote preview on the phone works fine but when I export to android (APK) with built in build service the exported app stops working after a few moments.

No buttons (sprites with touch, on tap) work, no layer visibility toggle works. Flashing sprite stops to work etc. Web Worker is disabled in my project. I tried minify option simple and advanced.

more details here:
https://www.construct.net/en/forum/construct-3/general-discussion-7/new-stable-build-broken-touch-146587

## Steps to reproduce

1. export to andriod (debug / signed)
2. 
3.

## Observed result
touch stops working, flashing stops, toggle layer visibilty not working

## Expected result
should behave like preview on pc and remote preview on phone but it does not.

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
r164 ( previouss stable worked fine but i cant go back, autosave has overwritten my project file)
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r164 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 23 gb
Storage usage (approx): 735 mb (3.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 615 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Sorry, there's nothing we can do unless you follow the bug report guidelines. Can you attach a minimal project that demonstrates the issue?

**Comment by TheBl4ckSh33p** [comment]
I can try to make one later but I'm away for eye surgery and can't see for the next ~24 hours.

But I changed nothing in my project and it worked in prev. Stable build. Now when I build for Android it's broken. And I can't go back cause autosave has overwritten my project file.

**Comment by AshleyScirra** [comment]
I'm afraid there's literally nothing we can do without the project, so I'll close issue until it can be provided. The first thing we do when investigating reports is open the provided project and then follow the steps to reproduce, so this is not currently actionable until then.
