### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'GetSdkInstance' of undefined

### ISSUE THREAD

**Issue by winkr7** [Scirra/Construct-3-bugs#3304]
## Problem description

I get this error message when using on destroyed 

action.js:1 Uncaught (in promise) TypeError: Cannot read property 'GetSdkInstance' of undefined
    at C3.Action._RunObject_ParamsConst (action.js:1)
    at C3.EventBlock._RunActions_Fast (eventBlock.js:1)
    at C3.EventBlock._RunAndBlock (eventBlock.js:1)
    at C3.EventBlock.Run (eventBlock.js:1)
    at C3.EventBlock._RunSubEvents_Fast (eventBlock.js:1)
    at C3.EventBlock._RunSubEvents (eventBlock.js:1)
    at C3.EventBlock._RunAndBlock (eventBlock.js:1)
    at C3.EventBlock.Run (eventBlock.js:1)
    at C3.EventSheet._ExecuteTrigger (eventSheet.js:1)
    at C3.EventSheet._TriggerForObjectClass (eventSheet.js:1)
_RunObject_ParamsConst @ action.js:1
_RunActions_Fast @ eventBlock.js:1
_RunAndBlock @ eventBlock.js:1
Run @ eventBlock.js:1
_RunSubEvents_Fast @ eventBlock.js:1
_RunSubEvents @ eventBlock.js:1
_RunAndBlock @ eventBlock.js:1
Run @ eventBlock.js:1
_ExecuteTrigger @ eventSheet.js:1
_TriggerForObjectClass @ eventSheet.js:1
_Trigger @ eventSheet.js:1
_Trigger @ eventSheetManager.js:1
Trigger @ runtime.js:1
Trigger @ sdkInstanceBase.js:1
_OnKeyUp @ instance.js:1
(anonymous) @ instance.js:1
_FireAndWaitAsyncSequential @ handler.js:1
dispatchEventAndWaitAsyncSequential @ dispatcher.js:1
_OnEventFromDOM @ runtime.js:1
_OnMessageFromDOM @ runtime.js:1
_PostToRuntimeMaybeSync @ domHandler.js:1
_OnKeyEvent @ runtimeDomEvents.js:1
(anonymous) @ runtimeDomEvents.js:1
async function (async)
dispatchEventAndWaitAsyncSequential @ dispatcher.js:1
_OnEventFromDOM @ runtime.js:1
_OnMessageFromDOM @ runtime.js:1
_PostToRuntimeMaybeSync @ domHandler.js:1
_OnKeyEvent @ runtimeDomEvents.js:1
(anonymous) @ runtimeDomEvents.js:1

## Attach a .c3p

https://www.dropbox.com/s/bajtplqachzqy19/sog.c3p?dl=0

## Steps to reproduce

run the program

hit the G key
hit the D key

1. hit the G key
2. hit the D key
3.

## Observed result

error message in console from C3

## Expected result

no error messages

no error messages

## More details

I think the problem has to do with on destroyed and families and the order of destroying things.

**Affected browsers/platforms:** 
chrome

I am running latest release didn't notice the error before but not sure

**First affected release:** 

## System details
i ran this on several macines all the same result.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The provided project has 277 events and 18 objects. It's extremely difficult to debug such large projects. Are you able to provide a minimal project as per the guidelines?

I backported the project to r157 and it still reproduced, so treating as an existing issue rather than a regression.

**Comment by winkr7** [comment]
Ashley;

Thanks for looking at it.  I will try to reduce the problem.

yours
winkr7 (burleigh)

**Comment by winkr7** [comment]
I have attached a very very small cp3 with the bug.  Just hit key T and
then D.

yours
winkr7

**Comment by AshleyScirra** [comment]
I don't see any new attachment, there is only the original project with 277 events. You also provided new steps to reproduce which differ from the original report, and so it's no longer clear how to interpret the report. Whenever this happens it rapidly becomes too confusing to make sense of the report any more, so I'd ask you to please file a new issue starting over and follow all the guidelines, including a minimal project (ideally one layout with <5 events and <5 objects) and the steps to reproduce with that project.
