### ISSUE TITLE
C3 hang up after positioning a ViewBar

### ISSUE THREAD

**Issue by NitidOnline** [Scirra/Construct-3-bugs#3307]
#2630  Problem description

C3 hang up after positioning a ViewBar under the Property bar, since r164.

## Attach a .c3p

Any empty project can be used.

## Steps to reproduce

1. Drag a view bar into the mid position option under Properties Bar
2. It crashes
3.

## Expected result

Work ok.

## More details

**Affected browsers/platforms:** 

Standalone Windows C3.

**First affected release:** 

r164

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r164-2/main.js, line 2, col 356293
Message: Uncaught TypeError: e.ǃFAG is not a function
Stack: TypeError: e.ǃFAG is not a function at ǃH.ǃFr.ǃjk.ǃHtD.ǃHJm (https://editor.construct.net/r164-2/main.js:2:356293) at D.ǃFVp (https://editor.construct.net/r164-2/main.js:2:368937) at D.ǃFVn (https://editor.construct.net/r164-2/main.js:2:368319) at D.ǃVzm (https://editor.construct.net/r164-2/main.js:2:365976) at HTMLDocument. (https://editor.construct.net/r164-2/main.js:2:360035) at HTMLDocument. (https://editor.construct.net/r164-2/main.js:2:190260)
Construct 3 version: r164.2
URL: https://editor.construct.net/
Date: Thu Sep 05 2019 17:57:40 GMT+0200 (hora de verano de Europa central)
Uptime: 311.3 s

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r164.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX 560 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I can't reproduce any issue. I'm not clear what you mean by "view bar" though, nor exactly which of the dock locations you're using. Can you provide more exact details, screenshots or a video? Incomplete reports are the #1 reason we can't fix issues, please be detailed.

**Comment by NitidOnline** [comment]
Here it goes. I hope it helps.

[issue  #3307 - test - Construct 3 05_09_2019 18_42_32.zip](https://github.com/Scirra/Construct-3-bugs/files/3580356/issue.3307.-.test.-.Construct.3.05_09_2019.18_42_32.zip)

**Comment by NitidOnline** [comment]
Chrome: Versión 76.0.3809.132 (Build oficial) (64 bits)

**Comment by AshleyScirra** [comment]
I still can't reproduce it. I tried creating a new project, undocking the layers bar, and docking it back again beneath the project bar. It seems to work fine.

**Comment by NitidOnline** [comment]
I'm using the stand alone version win64. 

It only happens when I try to dock in the mid dock (the one that makes the bar occupy all blank space).

If I use any other dock it works perfect.

**Comment by NitidOnline** [comment]
@AshleyScirra Hi. You can close it. I've deleted "User Data" and re-started C3 and it works ok now.
I will keep User Data files for a while in case you want to review them.

Thank you.
