### ISSUE TITLE
r30 Multiplayer Crash on Preview

### ISSUE THREAD

**Issue by gundrust** [Scirra/Construct-3-bugs#331]
## Problem description

After updating to the last version (r30) the program instantly crashes upon trying to preview any project, be it normal preview, remote preview or debug preview. Then i tried opening the multiplayer game example (because I'm trying to make a multiplayer game) with the same result, so after making a new blank project and trying to preview it with only a multiplayer object i confirm that it crashes instantly upon trying to preview it.
 I also cleared all caches and i dont have any addons on chrome (just downloaded it for this), just in case.

## Steps to reproduce

1. Create an empty project.
2. Add Multiplayer Object.
3. Try to preview it in any way.

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r30/exporters/preview/exporter.js, line 1, col 21348
Message: Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
Stack: TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided. at window.ǃyPc.ǃyPN (https://editor.construct.net/r30/exporters/preview/exporter.js:1:21348) at window.ǃyPc.ǃyPV (https://editor.construct.net/r30/exporters/preview/exporter.js:1:21793) at window.ǃyhy.ǃyPM.ǃyAl (https://editor.construct.net/r30/exporters/preview/exporter.js:1:20825) at window.ǃyhy.ǃyhn (https://editor.construct.net/r30/exporters/preview/exporter.js:1:1247) at ǃyhS.p (https://editor.construct.net/r30/exporters/preview/exporter.js:1:689)
Construct 3 version: r30
URL: https://editor.construct.net/
Date: Tue May 23 2017 11:30:04 GMT-0400 (CLT)
Uptime: 12.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r30

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by 3dParadox** [comment]
I'm not getting a crash, but my game is showing a black screen on previews.

Console: 
/r30/preview/[object%20Object]/ Failed to load resource: the server responded with a status of 404 ()
[object%20Object] Failed to load resource: the server responded with a status of 404 ()
editor.construct.net/:1 Uncaught (in promise) Event

**Comment by jaydonteh** [comment]
In the meantime, you could revert to the r29.2 using this link: https://editor.construct.net/r29-2/

**Comment by 3dParadox** [comment]
Thank you for that, will keep that for future use, My preview started working again when I deleted the "User Media" object. So it was unrelated to this bug.

**Comment by AshleyScirra** [comment]
Should be fixed in r31, roll back to r29.2 for the time being if you're having trouble with this.
