### ISSUE TITLE
Variable description not showing when setting value

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#3311]
![image](https://user-images.githubusercontent.com/5744908/64468147-44a35380-d164-11e9-80bd-bdf694393802.png)

I selected an instance variable but I can't see the custom description that was given to the variable to describe what it does, even when I click in the value field: 

![image](https://user-images.githubusercontent.com/5744908/64468160-63094f00-d164-11e9-8a24-16b0b45f72a6.png)

When I navigate to the families panel in the side bar, then right click to view the variables then select the variable, I can see that it does actually have description: 

![image](https://user-images.githubusercontent.com/5744908/64468173-95b34780-d164-11e9-8e1f-b20f9dbf4330.png)

**Comment by AshleyScirra** [comment]
The description is set as the tooltip for dropdown items. This is currently by design; if you think there should be a different design please file a feature request.

![instvar-desc](https://user-images.githubusercontent.com/768723/64522681-7518f800-d2f2-11e9-941b-6817ece33c23.png)

**Comment by alastajj** [comment]
This has been added to C3 suggestions: 

https://construct3.ideas.aha.io/ideas/C3-I-1235
