### ISSUE TITLE
Export issue, can't update the game

### ISSUE THREAD

**Issue by LucaDiMeglio** [Scirra/Construct-3-bugs#3316]
## Problem description
It's from like a month that I can't update my game(on android, never exported for iOS), I export using the Cordova project and using phonegap build, I don't have any error in the log.
The problem started when on screen when downloading the game appeared the write: "Blocked from Play Protect, Play Protect doesn't recognize the developer of this app. Sometimes the apps of unknown delevoper could be not safe"; I have then click on install anyway and after that:
-If I have another version of the app installed on the device it says me: app not installed
_ If  I don't have another version i can download without issue but of course i start from zero
So every time I export I have to unistall the old version and install the new one (or change the ID of the app so they became 2 different games and I can have both).
The problem of course is that it isn't an update so i lose all my data and I start from zero.
I tried on a lot of version of Construct (r164 too) but I don't know what is the problem, I don't think the problem is the version of Construct.

## Observed result
I can't update my game

## Expected result
I should be able to update the game as I have always done and continue from where I left.

**Comment by AshleyScirra** [comment]
I suspect this is a problem with APK signing or not enabling developer mode on your device, and not a Construct bug. It might be more appropriate to take it up on the forums instead. I've assigned to @shortercode in case he has anything to add but I doubt this will require changes to Construct.

**Comment by shortercode** [comment]
This is just the behaviour of play protect. Under some circumstances it can be very aggressive. I haven't really discovered what in particular triggers it. I certainly haven't seen it as frequently as you suggest, but have experienced similar issues that even when granting permission it seems to prevent installation sometimes.

You may have a better experience if you publish a closed alpha on the Play store, and then invite yourself to it. Play protect may be less irritating in this situation.

**Comment by shortercode** [comment]
Going to close this as external, as it's a bug in how Play Protect works. I'm not sure if there's any particular plugin or piece of code that we have that triggers it. It seems quite random to me, and it varies from device to device... I may try to review this further, but it's a difficult task and somewhat low priority.
