### ISSUE TITLE
Bookmark Scroll not work

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#3317]
## Problem description

When you click bookmark it doesn't go to bookmarked line.

## Attach a .c3p

[BookmarkBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3587951/BookmarkBug.zip)

## Steps to reproduce

1. Open bookmarks dialog.
2. Click bookmark.

## Observed result
Don't go to bookmarked line

## Expected result

Go to bookmarked line

**Affected browsers/platforms:** Chrome

**First affected release:** r163

**Comment by DiegoScirra** [comment]
Clicking on a bookmark should make sure that all parent's of the event are expanded, before moving to the location of the bookmark.

**Comment by CrackHub** [comment]
It should auto expand that bookmarked line. Why we need all expanded, it is bad workaround.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
