### ISSUE TITLE
Corrupt Project due to being allowed to switch animation while sprite strip still importing

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#3318]
## Problem description

Corrupt project caused by switching animation after initiating import of animation strip 

Looked like the import of the animation strip into one animation had not completed when I switched to another animation.  Last thing I saw was half the unfinished import of the animation being pasted into  second newly opened animation.

## Attach a .c3p

extension changed to zip

[Swapped to animation 2 before import of animation 1 finished.zip](https://github.com/Scirra/Construct-3-bugs/files/3592464/Swapped.to.animation.2.before.import.of.animation.1.finished.zip)

## Steps to reproduce

Corrupted file attached.   Click on sprite in project window to cause crash.

## Observed result

Was able to swap to animation 2 while import of animation strip to animation 1 was still ongoing.

## Expected result

Should not be able to swap animation while import of animation strip is ongoing.

**Comment by DiegoScirra** [comment]
@NetOneGames 

Can you upload the image you tried to import?

**Comment by NetOneGames** [comment]
So I cannot replicate this in a stripped down or basic project.  So it looks like something that appears in larger projects.
See this video 
[](https://drive.google.com/open?id=13EEnS5mFtFlKEEiZdZEBBe_hbCMAv2j6)
where I recreate the crash. Ive only captured the browser window so you cant see the folder pop ups bou can see that after I import the sprite I quickly change animations then you can see the remainder of the strip get pasted into the second animation.
I think this is easily solved by locking the editor until importing is finished.
Offending sprite strip
[](https://drive.google.com/open?id=13EEnS5mFtFlKEEiZdZEBBe_hbCMAv2j6)

**Comment by DiegoScirra** [comment]
Couldn't reproduce the crash, but locking the UI when an image is being loaded should avoid the problem entirely.
