### ISSUE TITLE
[R165] "Open local file" crash

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#3319]
## Problem description

Construct crashes when clicking "open local file" from menu.

## Attach a .c3p

[project.zip](https://github.com/Scirra/Construct-3-bugs/files/3593224/project.zip)

## Steps to reproduce

1. Open Construct r165 beta on Firefox, Chrome or Desktop version
2. go to Menu -> Project -> Open local file and Construct crashes.

## Observed result

![Screenshot_2019-09-09 Construct 3 r165 ★★★★★](https://user-images.githubusercontent.com/53188782/64576893-45fe9700-d383-11e9-9a0c-a4049cfd272c.png)

## Expected result

No crash

## More details

**Affected browsers/platforms:** Chrome/Firefox/Windows

**First affected release:** First started happening in r165beta

## System details

<details><summary>View details</summary>

Error report information

Type: unhandled rejection
Reason: Error: ǃOXR is not defined @ ǃOXh@https://editor.construct.net/r165/main.js:210:91748 ǃKO@https://editor.construct.net/r165/main.js:210:90886 ǃOiv/<@https://editor.construct.net/r165/components/misc/mainMenu/mainMenu.js:1:3476 ǃdd@https://editor.construct.net/r165/main.js:52:40803 this.ǃdU@https://editor.construct.net/r165/main.js:52:38629 e/<@https://editor.construct.net/r165/main.js:2:190473
Stack: ǃOXh@https://editor.construct.net/r165/main.js:210:91748 ǃKO@https://editor.construct.net/r165/main.js:210:90886 ǃOiv/<@https://editor.construct.net/r165/components/misc/mainMenu/mainMenu.js:1:3476 ǃdd@https://editor.construct.net/r165/main.js:52:40803 this.ǃdU@https://editor.construct.net/r165/main.js:52:38629 e/<@https://editor.construct.net/r165/main.js:2:190473
Construct 3 version: r165
URL: https://editor.construct.net/r165/
Date: Mon Sep 09 2019 23:19:54 GMT+0300 (Eastern European Summer Time)
Uptime: 15.5 s
Platform information

Browser: Firefox
Browser version: 69.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
C3 release: r165 (beta)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by Kyatric** [comment]
Same error when clicking the "File" button in the start page.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.

**Comment by AshleyScirra** [comment]
Leaving open with fixed tag to avoid duplicates.
