### ISSUE TITLE
"Exit" crash

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#3320]
## Problem description

Construct desktop version crashes when you click "Exit" from menu.
(Also, cannot exit by clicking as usual the red (x) button at the upper right corner of the main windows application. It does nothing.)

## Attach a .c3p

[project.zip](https://github.com/Scirra/Construct-3-bugs/files/3593288/project.zip)

## Steps to reproduce

1. Open project, or create an empty project
2. Click preview project
3. Close preview
6. Go to menu -> Exit

## Observed result

![exit crash](https://user-images.githubusercontent.com/53188782/64578554-69781080-d388-11e9-8bed-99ecc7e1e22d.jpg)

## Expected result

No crash

## More details
Crash occurs if you have previewed your project. If you open a project without previewing it, construct exits normally.

**Affected browsers/platforms:** Windows Desktop version r165 beta

**First affected release:** first started happening in r158 beta

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r165/main.js, line 2, col 243352
Message: Uncaught Error: Extension context invalidated.
Stack: Error: Extension context invalidated.
Construct 3 version: r165
URL: https://editor.construct.net/r165/
Date: Tue Sep 10 2019 04:55:34 GMT+0300 (Θερινή ώρα Ανατολικής Ευρώπης)
Uptime: 16.2 s

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r165 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
It works fine for me in the latest NW.js version (0.40.1). It looks like you're using an old version (0.39.0) which is probably the cause of the problem. You can update here: https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-desktop-build-beta-131317

**Comment by Dramamini** [comment]
I updated desktop version to Chromium 76 NW.js version 0.40.1 but it still crashes.. both on stable or beta version.

![v76 stable](https://user-images.githubusercontent.com/53188782/64613058-eb465900-d3dd-11e9-87ba-b05b3f346bba.jpg)

Error report information
Type: unhandled exception
File: https://editor.construct.net/r165/main.js, line 2, col 243352
Message: Uncaught Error: Extension context invalidated.
Stack: Error: Extension context invalidated.
Construct 3 version: r165
URL: https://editor.construct.net/r165/
Date: Tue Sep 10 2019 15:13:09 GMT+0300 (Θερινή ώρα Ανατολικής Ευρώπης)
Uptime: 34.2 s

Platform information
Browser: NW.js
Browser version: 0.40.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.40.1 (like Chrome/76.0.3809.100)
C3 release: r165 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
I can't reproduce this though I'm afraid, and there's little I can do if I can't. The error message doesn't make any sense either, so I've no idea what could be happening. I've not heard any other reports from other users about this either so it might be a one-off...

**Comment by Dramamini** [comment]
I found what's going wrong. Problem occurs when selecting Preview with -> Dialog, from Menu->Settings. If you select the "Popup Window" option, construct exits normally.
