### ISSUE TITLE
Mousebutton 3 and 4 are not detected by the mouse plugin

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3323]
## Problem description
Mousebutton 3 and 4 are not detected by the mouse plugin
![image](https://user-images.githubusercontent.com/32940085/64610131-8e767e80-d39c-11e9-828f-fcec6b86be99.png)

![image](https://user-images.githubusercontent.com/32940085/64610151-99311380-d39c-11e9-8860-eca6c7743c5f.png)

## Steps to reproduce

1.
2.
3.

## Observed result
mouse button 3 and 4 are nowhere to be found

## Expected result
mouse button 3 and 4 to be present

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is a feature request, not a bug - please post feature requests here: https://construct3.ideas.aha.io/
