### ISSUE TITLE
when using the expression editor, if an autocomplete is done, the expression editor scrolls back to the top if it has a scrolling bar and the mouse is used to select the autocomplete

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3324]
## Problem description
when using the expression editor, if an autocomplete is done, the expression editor scrolls back to the top if it has a scrolling bar and the mouse is used to select the autocomplete

https://puu.sh/Efyhh/cd33f0c09a.mp4
## Attach a .c3p
affects all projects

## Steps to reproduce

1.have a super long expression that makes the expression editor have a scrolling bar
2. start writing something that autocompletes
3.click the desired autocomplete result

## Observed result
the scrolling bar goes back to the top

## Expected result
the scrolling bar to stay where it is, just like when autocomplete is done with the keyboard

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
As noted in #3221 the expressions editor is not currently designed to be used in such a way with large, multiline expressions. Construct is designed for this logic to be used in events instead. As such we will not be fixing bugs relating to this particular style of using the expressions editor. It appears you already filed a suggestion to improve this case here: https://construct3.ideas.aha.io/ideas/C3-I-1086
Therefore we will track this suggestion there.
