### ISSUE TITLE
Tween - Angle problem [C3 Runtime] (Not solved!) R165

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#3329]
Same problem on r165 : [Bug Report](https://github.com/Scirra/Construct-3-bugs/issues/3310)
I don't know is there already fixed on next version?!

**Comment by AshleyScirra** [comment]
I believe r164.3 fixed this issue, since it includes this fix:

> Tweening angles could sometimes end with wrong value 

However note that r164.3 came out *after* r165. That means the fix in that release is not yet in the beta release. It should be fixed when the next beta release comes out.
