### ISSUE TITLE
Crop does not always add 1px transparent border

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#333]
## Problem description

In the image editor, crop should always leave a 1px transparent border round the edge of the image. At the moment it works, but only if crop shrinks the image. If there is already image content right up to the edges, crop should add an extra 1px border (making the image size larger). That's what C2 does, but C3 does not do that.

The algorithm C2 uses is something like:

- identify the size of the image content bounds
- create a new surface with 1px padding
- copy image content to that surface, at a 1px offset
- use as new image

That works in all circumstances, including the possibility to grow the image.

## Steps to reproduce

1. Create new project
2. Add sprite
3. Fill entire image solid color
4. Press crop

## Observed result

Nothing happens.

## Expected result

Add a 1px transparent border.

**Comment by JeFawk** [comment]
I guess here's my Sprite Bleeding problem?

**Comment by AshleyScirra** [comment]
No, that is most likely to do with mipmap generation. The spritesheeting engine adds another 1px border, this is more to do with ensuring a consistent display quality.

**Comment by DiegoScirra** [comment]
Fixed in r32.
