### ISSUE TITLE
when selecting a variable in a drop-down list, and typing to get the correct variable, it will highlight the first result at the bottom of the list instead of the top of the list to see other relevant results

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3331]
## Problem description
when selecting a variable in a drop-down list, and typing to get the correct variable, it will highlight the first result at the bottom of the list instead of the top of the list to see other relevant results

## Steps to reproduce

1.choose an instance variable to change
2.click on the dropdown list
3.start typing

## Observed result
the highlighted variable is at the bottom obscuring the other relevant variables 

## Expected result
for the highlighted result to be at the top so that I can see other relevant variables

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce. Please always follow the bug report guidelines to ensure we can actually investigate your report.
