### ISSUE TITLE
r166 Drag event to position above a comment crash

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#3334]
## Problem description

Crash when trying to move or drag any event line (even if its blank) to a position above a comment line.

## Steps to reproduce

1. Create a comment.
2. Create any event line, even if its blank.
3. Drag the event line and place above the comment.

## Observed result

Crashed.

## Expected result

Don't crash.

**Affected browsers/platforms:** 

Chrome on MacOS.

**First affected release:** 

r166

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r166/main.js, line 2, col 94554
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Function.ǃs (https://editor.construct.net/r166/main.js:2:94560) at d.ǃl_t (https://editor.construct.net/r166/components/editors/eventSheetView/eventSheetView.js:1:31577) at d.ǃl$f (https://editor.construct.net/r166/components/editors/eventSheetView/eventSheetView.js:1:29833) at d.ǃlFC (https://editor.construct.net/r166/components/editors/eventSheetView/eventSheetView.js:1:28685) at d.ǃc_ (https://editor.construct.net/r166/components/editors/eventSheetView/eventSheetView.js:1:24384) at HTMLDocument. (https://editor.construct.net/r166/components/editors/eventSheetView/eventSheetView.js:1:2338) at HTMLDocument. (https://editor.construct.net/r166/main.js:2:190509)
Construct 3 version: r166
URL: https://editor.construct.net/r166/
Date: Mon Sep 16 2019 21:24:00 GMT+0800 (Malaysia Time)
Uptime: 16.2 s

Platform information
Browser: Chrome
Browser version: 76.0.3809.87
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
C3 release: r166 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) UHD Graphics 617
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Looks like the fix for issue #3325 regressed this (drag-and-drop is actually super complicated...). Updated the fix so this should be fixed for the next release. Probably will be a common issue so leaving open with fixed tag.

**Comment by Wackytoaster** [comment]
Just in case this is a slightly different issue:
Dragging a comment above a variable (or the variable below a comment) will also crash
![image](https://user-images.githubusercontent.com/31101309/65048523-90c07600-d964-11e9-80be-5103ed1721ba.png)

**Comment by masscube** [comment]
I have the same with functions. Move/change up (or down) = Crash.

Event Sheet problem example-file: 
[Download Example](http://massive-cube.com/work/problem/construct/bug-events-and-functions.c3p)

**Comment by AshleyScirra** [comment]
All these cases come down to the same issue, it should all be fixed in the next release.

**Comment by kidswithcrowns** [comment]
Hotfix possible? This is making it impossible for me to work

**Comment by masscube** [comment]
> Hotfix possible? This is making it impossible for me to work

that would be very good. I can't change everthing in my project without crash.

**Comment by jaydonteh** [comment]
I agree we should have a hot fix or an update real soon. I’m away from my projects because of this issue. Practically almost impossible to work on.

**Comment by AshleyScirra** [comment]
Alright, I'll see if we can get an update out today.

**Comment by AshleyScirra** [comment]
r167 is out now, hopefully properly fixes this.
