### ISSUE TITLE
calling function from family on destroyed crashes

### ISSUE THREAD

**Issue by winkr7** [Scirra/Construct-3-bugs#3335]
## 

## run the C3 attached.  It crashes right away.
or just type in these 7 lines of code see below

+ System: On start of layout
----+ (no conditions)
-----> boxFamily: Destroy

+ boxFamily: On destroyed
----+ (no conditions)
-----> Functions: Call anyFunct

* On function 'anyFunct'
-> (no actions)

1.just run it
2.
3.

## Observed result

 it crashes

## Expected result
it shouldn't crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE
+ System: On start of layout
----+ (no conditions)
-----> boxFamily: Destroy

+ boxFamily: On destroyed
----+ (no conditions)
-----> Functions: Call anyFunct

* On function 'anyFunct'

-> (no actions)

</details>

**Comment by winkr7** [comment]
how do I attach a cp3 file.  It tells me it won't attach the file.

**Comment by AshleyScirra** [comment]
Please read the bug report guidelines. It covers that.

**Comment by winkr7** [comment]
here is the very very short cp3

**Comment by AshleyScirra** [comment]
Closing as #3337 was filed with a project attached
