### ISSUE TITLE
Minor issue previewing "move along path" example

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#3336]
## Problem description

When previewing the new "move along path" example project from the start page, it doesn't seem to function as expected. Events don't seem to fire at all. The Console is giving no error messages as well.

## Steps to reproduce

1. Open latest version of C3
2. Search for "move along path" example
3. Click preview (on start page)

## Observed result

Start page previewing the new move along path example doesn't work right.

## Expected result

Opening and previewing this example works as expected. 
Start page preview should be working in the exact same way.

## More details
**Affected browsers/platforms:** NW.js; FireFox; Chrome

**First affected release:** r166

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.41.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.41.0 (like Chrome/77.0.3865.75)
C3 release: r166 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 100 gb
Storage usage (approx): 433 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Huh, that's odd. It looks like the timeline is missing when previewed from the start page. Assigning to @DiegoScirra to look in to that.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
