### ISSUE TITLE
calling function from " on family destroyed "crashes

### ISSUE THREAD

**Issue by winkr7** [Scirra/Construct-3-bugs#3337]
## a function call from inside a family level on destroyed crashes 
[boxTest.zip](https://github.com/Scirra/Construct-3-bugs/files/3617212/boxTest.zip)

## just run the cp3 (it crashes in on start of layout).

1.run the cp3 
2.
3.

## Observed result

the screen stays black and an error code appears on the console

## Expected result

I expect it not to crash and to delete the family member after the function call

## More details

I keep trying to submit this, sorry about all the tries.  I got the cp3 to attach this time.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by winkr7** [comment]
I don't want to pester you guys.  I believe I got the cp3 attached as a zip file this time.  
I think I can work around the crash so I will quit bothering you.

**Comment by AshleyScirra** [comment]
Thanks, this type of report & project is ideal. I was able to identify the issue and it should be fixed for the next release. I also checked the project attached with issue #3304 and it appears to have fixed that too.

**Comment by winkr7** [comment]
thanks lots Ashley.
