### ISSUE TITLE
When I apply a Normal Map effect and stretch the property bar or any bar the project also stretches

### ISSUE THREAD

**Issue by LucasGuerra007** [Scirra/Construct-3-bugs#3338]
## Problem description
When I apply a Normal Map effect and stretch the property bar or any bar the project also stretches

When I apply a Normal Map effect and stretch the property bar or any bar the project also stretches
## Steps to reproduce

1. insert Normal map efect in any object
2. strech bar propieties
3. look the proyect

## Observed result

streech all proyect
## Expected result
no streech
![a](https://user-images.githubusercontent.com/55405267/64978013-e7598180-d88a-11e9-9698-065a3074a894.JPG)
![b](https://user-images.githubusercontent.com/55405267/64978015-e7598180-d88a-11e9-9bc3-df97fc64fe46.JPG)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Construct doesn't come with an effect named "Normal map". Presumably this is a third-party addon, in which case you'll need to report any issues with it to the addon developer.

**Comment by LucasGuerra007** [comment]
Hello Ashley, is the effect call Bumpmaping but in spanish call Normal efecto
is an effect native from construct3

**Comment by AshleyScirra** [comment]
Oh, OK. Well, no project was provided, so I tried with Ghost Shooter, and it appeared to work fine. The picture in your screenshot looks like it could be a graphics driver bug or something, so without further evidence, I'd assume it's not a Construct issue.

**Comment by LucasGuerra007** [comment]
ok, i try in two different pc and the same result. sorry for no atach any project i m in work sorry. but the bug is real.
