### ISSUE TITLE
r30 Pathfinding crash on Preview, Debug, Remote Preview

### ISSUE THREAD

**Issue by Piggybank** [Scirra/Construct-3-bugs#334]
## Problem description

This seems to be a very similar problem to what was previously reported for the Multiplayer object, but I'll make a separate report for this just in case.  After updating to r30, my current project will fail to preview, simply displaying a black screen and not giving an error.  This is the same for debug mode as well, while Remote Preview will immediately crash C3 upon someone loading the URL provided for the project.  I'll include the crash report provided by remote preview lower on this page.

Another note is that the project will export and run in NW.js with no errors at all, so the problem seems to extend to just the browser itself, but that's speculation on my end.

After rewinding back to my earlier backups of my project, I found that the Pathfinding behavior seems to be the source of the error, as both the eariler backup of the project and the latest build will run fine without it being present.

## Steps to reproduce

1. Create an empty project.
2. Create sprite, add pathfinding behavior.
3. Preview the project.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.ǃJ.ǃJO (https://editor.construct.net/r30/main.js:2:199807) at ǃJ.ǃOIg (https://editor.construct.net/r30/main.js:2:215960) at Array.map (native) at window.ǃyPc.ǃyPT (https://editor.construct.net/r30/exporters/preview/exporter.js:1:22909) at window.ǃyPc.ǃyPo (https://editor.construct.net/r30/exporters/preview/exporter.js:1:22169) at window.ǃyvZ.ǃyPM.ǃyAZ.h [as ǃyAZ] (https://editor.construct.net/r30/exporters/preview/exporter.js:1:20889) at h.ǃyhD.then.then.then.then.then (https://editor.construct.net/r30/exporters/preview/exporter.js:1:15780) at 
Stack: TypeError: expected string at Function.ǃJ.ǃJO (https://editor.construct.net/r30/main.js:2:199807) at ǃJ.ǃOIg (https://editor.construct.net/r30/main.js:2:215960) at Array.map (native) at window.ǃyPc.ǃyPT (https://editor.construct.net/r30/exporters/preview/exporter.js:1:22909) at window.ǃyPc.ǃyPo (https://editor.construct.net/r30/exporters/preview/exporter.js:1:22169) at window.ǃyvZ.ǃyPM.ǃyAZ.h [as ǃyAZ] (https://editor.construct.net/r30/exporters/preview/exporter.js:1:20889) at h.ǃyhD.then.then.then.then.then (https://editor.construct.net/r30/exporters/preview/exporter.js:1:15780) at 
Construct 3 version: r30
URL: https://editor.construct.net/
Date: Tue May 23 2017 13:25:16 GMT-0400 (Eastern Daylight Time)
Uptime: 28.8 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r30

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by jaydonteh** [comment]
In the meanwhile, you could revert to the r29.2 using this link: https://editor.construct.net/r29-2/

**Comment by Piggybank** [comment]
Thank you for the link!  I completely forgot you could wind back to a previous version that way.  That will help me out in the meantime.

**Comment by adamprack** [comment]
Yep, this happens for me too. Too bad I narrowed it down the hard way instead of just reading this report first :-P I just get a black preview window.

**Comment by AshleyScirra** [comment]
No longer happens after fixing #331 so think this is the same underlying issue. Should be fixed in r31.
