### ISSUE TITLE
Construct 3 Crashing

### ISSUE THREAD

**Issue by ArrowArrowArrowArrow** [Scirra/Construct-3-bugs#3340]
## Problem description

Attempting to start the Construct 3 editor within a browser.

## Attach a .c3p

N/A
A project file is not needed for this issue as none was used at the time.

## Steps to reproduce

1. Start the editor within a browser.
2. Become stunned as the editor failed due to a unhandled rejection. On startup of the editor across multiple days on the same web browser and on the same device. Note: Construct 3 has worked many times on the device and browser before (My Laptop).

## Observed result

OOPS SOMETHING WENT WRONG!!!

## Expected result

Construct to start.

## More details
Only seems to happen on my laptop and on firefox.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
@ArrowArrowArrowArrow can you please provide the crash log from the dialog, I do not believe there is enough information here for us to investigate.

**Comment by AshleyScirra** [comment]
Even a crash report isn't sufficient to be able to investigate this, since we need reliable steps to reproduce, and I can successfully open the editor in Firefox.

It might be more useful to press F12 and report any more information that appears in the browser console, e.g. in case any network requests failed prior to that.

**Comment by SnipG** [comment]
Maybe is related but, opening C3 in ingognite mode firefox will results crash.
So maybe he has some setting on firefox that have same result.
<details><summary>View details</summary>

Error report information

Type: unhandled rejection
Reason: Error: The operation is insecure. @ ǃwKJ@https://editor.construct.net/r164-3/components/misc/startPage/startPage.js:1:5643 ǃwKq/<@https://editor.construct.net/r164-3/components/misc/startPage/startPage.js:1:4445 n@https://editor.construct.net/r164-3/main.js:2:199600 t@https://editor.construct.net/r164-3/main.js:2:199385
Stack: ǃwKJ@https://editor.construct.net/r164-3/components/misc/startPage/startPage.js:1:5643 ǃwKq/<@https://editor.construct.net/r164-3/components/misc/startPage/startPage.js:1:4445 n@https://editor.construct.net/r164-3/main.js:2:199600 t@https://editor.construct.net/r164-3/main.js:2:199385
Construct 3 version: r164.3
URL: https://editor.construct.net/
Date: Tue Sep 17 2019 19:04:45 GMT+0300 (Eastern European Summer Time)
Uptime: 2.3 s
Platform information

Browser: Firefox
Browser version: 69.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
C3 release: r164.3 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
> opening C3 in new private window mode firefox will results crash.

Ah, using a private window was the crucial missing detail. I can reproduce that in Firefox only, it looks like a Firefox bug, but it's straightforward to work around, so that's fixed for the next release.

**Comment by KatieKoolYT** [comment]
I'm in permanent private browsing mode - is there any other way around private browsing?

**Comment by AshleyScirra** [comment]
This is fixed in the latest beta release.
