### ISSUE TITLE
Scrolling Tiled Background Set Image Offset stutters when Image Angle is other than 0

### ISSUE THREAD

**Issue by RichardAstrom** [Scirra/Construct-3-bugs#3341]
Tiled Backgrounds that scroll by using Image Offset (X or Y or both) and also has an Image Angle set to something other than 0, 90, 180 or 360, skips and stutters.

[tiledbackground_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3620175/tiledbackground_bug.zip)

1. Create an Tiled Background object.
2. Use Set Image Offset to scroll the background every tick.
3. Set Image Angle to anything other than 0, 90, 180 or 360.

## Observed result

The Tiled Background stutters.

## Expected result

It should scroll smoothly.

## More details

Chrome on Windows

First noticed in r166

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r166 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 17 gb
Storage usage (approx): 659 mb (3.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think the change to the Tiled Background offset clamping in r166 broke this. I've just reverted that for the next release.

**Comment by iftikharlove555** [comment]
This trouble again on mobile

**Comment by AshleyScirra** [comment]
This issue was fixed back in 2019. Please file a new issue following all the guidelines if you have an issue, as the one described here was most likely resolved some time ago.
