### ISSUE TITLE
Cannot uninstall plugin

### ISSUE THREAD

**Issue by Thersippos** [Scirra/Construct-3-bugs#3342]
I have installed "ValerypopoffUniversalDie" plugin. After some Construct updates this plugin is no longer compatible. Every time I open Construct it shows this error message:

"Error loading plugin ValerypopoffUniversalDie because it uses unsupported features...."

On "Addon Manager" the plugin is not listed, so I cannot uninstall it.

**Comment by shortercode** [comment]
Please do not delete the issue template, it exists for a reason. When filing a bug fill in all the sections you can to help us reproduce the problem.

[Issue guidelines](https://github.com/Scirra/Construct-3-bugs/blob/master/README.md)

> ## Use the bug report template
> The bug submission page is pre-filled with a template. We need all this information to help you. Do not delete it. Please provide as much of the requested information as you can, including the system details or crash report information with every report.

I will assign to @AshleyScirra to review this anyway, as the description might be enough.

**Comment by AshleyScirra** [comment]
If you read the rest of the error message...

> To uninstall the addon, use the Addon Manager in an earlier release of Construct.
