### ISSUE TITLE
Dragging an XML Project file to a second monitor causes a crash

### ISSUE THREAD

**Issue by DrSquidge** [Scirra/Construct-3-bugs#3343]
Turns out this is reproducible with XML, JSON or JS project files. When working on two monitors, dragging a project file tab to the second monitor causes C3 to crash. Dictionary tabs and event sheets appear to work fine. 

.c3p file: https://1drv.ms/u/s!Al0pc3FK6sBEgYkdsJQxA7CyS6mIiA

## Steps to Reproduce:

1. Open the XML project file in C3
2. Attempt to drag the tab to a second monitor

## Observed result

Construct 3 will crash

## Expected result

Tab to move to second monitor in a new window

## More details

**Affected browsers/platforms:** 
Chrome on both Windows and MacOS
Safari on MacOS

**First affected release:** 
Only tested as far back as r157 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r166/main.js, line 2, col 92313
Message: Uncaught TypeError: expected string
Stack: TypeError: expected string at Function.ǃi.ǃgS (https://editor.construct.net/r166/main.js:2:92319) at Function.ǃixa (https://editor.construct.net/r166/main.js:2:281102) at ǃi.ǃaH.ǃLE.ǃiUO.ǃlOE (https://editor.construct.net/r166/main.js:2:355874) at I.ǃgbA (https://editor.construct.net/r166/main.js:2:370833) at HTMLDocument. (https://editor.construct.net/r166/main.js:2:364718) at HTMLDocument. (https://editor.construct.net/r166/main.js:2:190509)
Construct 3 version: r166
URL: https://editor.construct.net/r166/
Date: Tue Sep 17 2019 12:06:13 GMT+0100 (British Summer Time)
Uptime: 145.2 s

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r166 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 6000
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
The crash was straightforward to fix (the text editor did not assign an ID where one was needed), but it still seems to have odd behavior here when closing the popup window - the pane comes back at an odd position and can't be resized properly. This doesn't happen to layout views or event sheet views, so presumably the text editor is doing something else that is messing up the pane somehow - assigning to Iain to look in to that.

**Comment by shortercode** [comment]
Seems to be a styling issue that's clashing with the floating pane. Should be able to fix it with a CSS tweak I think, but the codemirror embed is somewhat fragile. I will give it a whirl.

**Comment by shortercode** [comment]
Should be resolved in the next beta release.
