### ISSUE TITLE
Timeline 'Set instance' action should accept empty track ID

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#3344]
The Timeline plugin 'Set instance' action currently ignores empty strings for the track ID. This means it still does not work even if there is a track ID in the timeline that is the empty string. In the end this makes it harder to set up instance playback since you have to set a non-empty track ID before it can work.

It would be more convenient if an empty track ID was treated as "use the first track in the timeline". Since single-track timelines are probably a common case this avoids having to set a track ID at all. To make this discoverable the action description should also add "Leave empty to use the first track in the timeline".

**Comment by DiegoScirra** [comment]
Added in the next beta.

I made it so if you don't use a track id in the action, the instance will be set to the first track which isn't already set. This way it is possible to replace several instances of a timeline without using a track id at all. The caveat is that the **SetInstance** calls need to be in the same order as the tracks in the timeline.

**Comment by AshleyScirra** [comment]
Great idea, that's even better!
