### ISSUE TITLE
Browser.Referrer does not work on exports

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#3347]
## Problem description

Browser.Referrer does not work on exports

## Attach a .c3p

https://www.dropbox.com/s/0io5dclvb6ii6g7/browserReferrer.c3p?dl=1

## Steps to reproduce

1.Run the project in preview to see the url
2.Export the project to html5
3.Upload the project to a server(like Netlify)
4.Run the export using referrer link

## Observed result

No url
## Expected result

Text should display the referring url 

## More details
Tested using multiple circumstances:
No worker
No minification

## System details

<details><summary>View details</summary>

W10 
Chrome

</details>

**Comment by AshleyScirra** [comment]
The expression just returns `document.referrer`. It's not always set depending on the security settings of the forwarding website, or the circumstances of the navigation. So it's not a bug unless `document.referrer` has a value but the Browser plugin doesn't return that; unless the report specifies that I would just assume the referrer is not being set at all.
