### ISSUE TITLE
Crash on duplicating a Timeline

### ISSUE THREAD

**Issue by Valettus** [Scirra/Construct-3-bugs#3349]
## Problem description

Duplicating specific Timelines in the project causes a crash.

The project also fails to save with the same message as the crash:
![SaveFail](https://user-images.githubusercontent.com/23408658/65160718-40005a00-da04-11e9-91df-2202b0fac1bc.png)

## Attach a .c3p

Because this issue prevents saving the project, I am unable to provide a stripped project. I apologize. I have also been unable to re-create the issue in a fresh project.

https://www.dropbox.com/s/davhc36nwlqu232/Cannon%20Array%20-%20Copy.c3p?dl=1

## Steps to reproduce

1. Duplicate either Timeline ScoreTextFlash or TitleFly-In

The other timelines in the project do not cause a crash. I can't remember doing anything different with the corrupted timelines, but I may have.

## Observed result

Crash

## Expected result

Duplicated Timeline

## More details

Deleting the affected Timelines allows the project to save.

**Affected browsers/platforms:** Reproduced in Chrome and Firefox on 2 Windows computers

The crash report varies slightly between Chrome and Firefox (different names for the unreadable property).

**First affected release:** 164.3

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃds' of undefined @ TypeError: Cannot read property 'ǃds' of undefined at https://editor.construct.net/r164-3/projectResources.js:1:16240 at Array.map () at n.ǃSM (https://editor.construct.net/r164-3/projectResources.js:1:16229) at i.ǃpj (https://editor.construct.net/r164-3/projectResources.js:1:437947) at https://editor.construct.net/r164-3/components/bars/projectBar/projectBar.js:24:10804
Stack: TypeError: Cannot read property 'ǃds' of undefined at https://editor.construct.net/r164-3/projectResources.js:1:16240 at Array.map () at n.ǃSM (https://editor.construct.net/r164-3/projectResources.js:1:16229) at i.ǃpj (https://editor.construct.net/r164-3/projectResources.js:1:437947) at https://editor.construct.net/r164-3/components/bars/projectBar/projectBar.js:24:10804
Construct 3 version: r164.3
URL: https://editor.construct.net/
Date: Wed Sep 18 2019 11:06:46 GMT-0400 (Eastern Daylight Time)
Uptime: 550.2 s

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r164.3 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon (TM) RX 570 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
