### ISSUE TITLE
Timeline - Cant add negative % values for relative opacity

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#3352]
## Problem description
When I change opacity to 0 in relative mode keyframes are set to "-100%" but when I try to manually change the value in the keyframe properties it defaults back to 0 and does not allow a negative value. Rightclick to set keyframe adds the "-100%" and works.

Not sure if this requires an example project.

## Steps to reproduce

1. Add Timeline with relative mode
2. Enable Edit mode for a sprite
3. add property Opacity
4. change the value to 0 and set keyframe (works)
5. change the value of keyframe (square) manually and it goes back to 0

## Observed result
manual changes do not allow negative values

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
164.3
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This is fixed in the next beta.
