### ISSUE TITLE
safari 12+ black screen

### ISSUE THREAD

**Issue by q3olegka** [Scirra/Construct-3-bugs#3354]
safari 12+ black screen (game not loading at iphone and mac, C3)

![photo_2019-09-19_16-53-14](https://user-images.githubusercontent.com/50992459/65251025-40315000-daff-11e9-8e94-b90009f6a33d.jpg)
![photo_2019-09-19_16-54-52](https://user-images.githubusercontent.com/50992459/65251027-40c9e680-daff-11e9-9bc2-7906dbfc9fee.jpg)

last beta r167

android and windows works fine
no capx, sorry

**Comment by AshleyScirra** [comment]
No project provided so tested Ghost Shooter. It worked fine on Safari 12.1.2 on macOS.

The bug report guidelines are written specifically to avoid this happening. Please use the bug report template and follow all the guidelines to ensure your report is useful.
