### ISSUE TITLE
Group Select/Deselect Enhancements [Color Edit]

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#3355]
## Problem description

When you want to select one group it is selecting all inner, it is ok. But when you try to deselect it is only apply selected not all inner.

When you try to change **TOPGROUP** color, it is apply other inner groups.

## Attach a .c3p

[ColorEdit.zip](https://github.com/Scirra/Construct-3-bugs/files/3636513/ColorEdit.zip)

## Steps to reproduce

Before Expand all groups.
**1.** Collapse Group3
**2.** Select TOPGROUP
**3.** Ctrl + Left Click on Group3
**4.** Use change background action for TOPGROUP (Right Click > Colors > Change background color)
**5.** So we want to change color for only TOPGROUP but it is change all other inners. It should be don't affect others, Group3 deselected and it was collapsed.

## Observed result

![1](https://user-images.githubusercontent.com/54614906/65337157-50fdc680-dbd0-11e9-8179-499f156e0c0e.PNG)

## Expected result

![2](https://user-images.githubusercontent.com/54614906/65337162-52c78a00-dbd0-11e9-9846-ecac9be879cd.PNG)

## More details

https://github.com/Scirra/Construct-3-bugs/issues/3321

**First affected release:** r165 (tested with)

**Comment by AshleyScirra** [comment]
This is the same as #3356 (ctrl+unselect collapsed event does not unselect its contents) and is fixed for the next release.
