### ISSUE TITLE
Group Select/Deselect Enhancements [Disable]

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#3356]
## Problem description

When you want to select one group it is selecting all inner, it is ok. But when you try to deselect it is only apply selected not all inner.

## Attach a .c3p

[Disable.zip](https://github.com/Scirra/Construct-3-bugs/files/3636468/Disable.zip)

## Steps to reproduce

Before Expand all groups.
**1.** Collapse Group4
**2.** Select Group3
**3.** Ctrl + Left Click on Group3
**4.** Ctrl + Left Click on Group4
**5.** Press D
**6.** Expand Group4. You can see Group4 events disabled. It should be enabled because we deselect Group4 and it was collapsed.

## Observed result

![1](https://user-images.githubusercontent.com/54614906/65336319-d54f4a00-dbce-11e9-8e42-1dc0c5404047.PNG)

## Expected result

![2](https://user-images.githubusercontent.com/54614906/65336329-d8e2d100-dbce-11e9-87c9-01bf57df64c5.PNG)

## More details

https://github.com/Scirra/Construct-3-bugs/issues/3321

**First affected release:** r165 (tested with)

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
