### ISSUE TITLE
Pinned Canvas rotate causes Canvas distortion

### ISSUE THREAD

**Issue by colludium** [Scirra/Construct-3-bugs#3358]
## Problem description

If a Canvas object is pinned to a sprite with Pin Position and Angle set and the sprite rotates, the Canvas does not rotate. Instead, it becomes distorted.

## Attach a .c3p

[canvas pin angle bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3640059/canvas.pin.angle.bug.zip)

## Steps to reproduce

Rotate the sprite using the left/right arrow keys. You'll see that as the sprite rotates, the Canvas object distorts.

## Observed result

Canvas distorts.

## Expected result

Canvas should rotate.

## More details

Not required.

**Affected browsers/platforms:** 

Chrome

**First affected release:** 

Not known.

## System details

N/A.

**Comment by AshleyScirra** [comment]
Drawing Canvas currently does not support rotation. Note it has no angle property and no angle related actions. If you use the Pin behavior to side-step this and force it to rotate, it won't work.
