### ISSUE TITLE
Outdated manual entry for Mobile IAP

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#3359]
## Problem description
The manual does not explain what the **Transaction** expression does and ProductDescription seems to work anywhere with ID but the expression list in C3 says used in Trigger only.

**And the page does not tell if you should use the registratoin commands only once or if it can be used on start of any layout without problems.**

PS: The manual entry does not tell where you can find your public key for Android.

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Okay I've revised documentation to include information on where to find your public key, the missing entry for the Transaction expression and the information about when you should call the registration actions.

I've also updated the description for the "Product Description" expression in Construct itself.

Thanks for letting us know about these corrections. There should be some updates and fixes coming for the plugin in the next beta, just completing some testing at the moment.
