### ISSUE TITLE
Dark Theme Boolean Issue

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#3360]
## Problem description
Dark theme don't show boolean if they have different values. (One sprite has true one sprite has false instance variable.)

## Attach a .c3p

[Boolean.zip](https://github.com/Scirra/Construct-3-bugs/files/3642466/Boolean.zip)

## Steps to reproduce

1. Use dark theme.
2. Select all sprites.
3. Look test instance variable. It is shows they all false.

## Observed result

![image](https://user-images.githubusercontent.com/54614906/65432080-4424e100-de23-11e9-99ca-61c5e66b3ba6.png)

## Expected result

Should be show similar Default theme.

## More details
I think you can check Light theme too. I didn't check because I don't wanna lost my theme settings.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by CrackHub** [comment]
Before
```
	/* Checkbox input elements in ui-propvalue elements should use the full width of the cell but not the full height since that also increases the size of the checkbox */
	ui-propvalue > input[type='checkbox'] {
		position: relative;
		cursor: pointer;
		outline: 0;
		-webkit-appearance: none;
		background: var(--gray6);
		border-radius: 3px;
	}
	ui-propvalue > input[type='checkbox']:checked:after {
		content: "";
		display: flex;
		align-items: center;
		justify-content: center;
		position: absolute;
		top: 0; right: 0; bottom: 0; left: 0;
  
		width: 70%;
		height: 30%;
		border: 0 solid var(--gray29);
		border-width: 0 0 0.125em 0.125em;
		transform: translate(10%,50%) rotate(-45deg);
	}
```
After
```
/* Checkbox input elements in ui-propvalue elements should use the full width of the cell but not the full height since that also increases the size of the checkbox */
	ui-propvalue > input[type='checkbox'] {
		position: relative;
		cursor: pointer;
		outline: 0;
		/* EDITED */
		/* -webkit-appearance: none; */
		background: var(--gray6);
		border-radius: 3px;
	}
	/* EDITED */
	/* ui-propvalue > input[type='checkbox']:checked:after { */
		/* content: ""; */
		/* display: flex; */
		/* align-items: center; */
		/* justify-content: center; */
		/* position: absolute; */
		/* top: 0; right: 0; bottom: 0; left: 0; */
  
		/* width: 70%; */
		/* height: 30%; */
		/* border: 0 solid var(--gray29); */
		/* border-width: 0 0 0.125em 0.125em; */
		/* transform: translate(10%,50%) rotate(-45deg); */
	/* } */
```

I just edit this codes, now it is using browser's default css for checkbox
![image](https://user-images.githubusercontent.com/54614906/86297576-621a4000-bc04-11ea-9528-4a3a67145cd2.png)

**Comment by Fib100** [comment]
This issue seems pretty simple to fix but is almost 1 year old. The person who created this issue even provided a potential solution. Could this potentially get fixed for the next release (r212)?

**Comment by bobatealee** [comment]
bump. i think this would be an easy fix.

**Comment by CrackHub** [comment]
Yes, i don't know why we are waiting for Animmaniac, He doesn't fix anything, he doesn't follow any theme issues.

**Comment by Fib100** [comment]
This is why I don't use dark theme in C3. I just stick with the default theme cause there's been multiple bugs with dark theme, they're pretty simple to fix, but no one fixes them for years.

**Comment by AshleyScirra** [comment]
This looks like it works in r295 with Chrome 101. I would guess browsers did not previously support the indeterminate style with custom CSS, but now they do, so this was probably fixed by a browser update.

**Comment by CrackHub** [comment]
This is broken again. I don't wanna create new issue. I tried latest beta with chrome and firefox.
