### ISSUE TITLE
safari 12+ black screen

### ISSUE THREAD

**Issue by q3olegka** [Scirra/Construct-3-bugs#3362]
Error in safari 12+. Black screen after loading. The game does not go to the starting layout. Unfortunately, I do not have apple devices to track the cause of the black screen by events, or by added straights. All I know is that the game doesn't work on iphone and mac devices

r168
The source has sent to Ashley's mail

![2-safari-error](https://user-images.githubusercontent.com/50992459/65449379-91b14600-de43-11e9-8021-966f6115c779.jpg)

**Comment by AshleyScirra** [comment]
Please use the bug report template. The project you provided uses third-party addons, so I am afraid we cannot support it.
