### ISSUE TITLE
chrome and opera black screen after added effect warpObjectMask

### ISSUE THREAD

**Issue by q3olegka** [Scirra/Construct-3-bugs#3363]
Error in chrome (v77) and opera browsers (firefox is fine). Black screen after loading. The game does not go to the starting layout. The error occurs after adding the "warpObjectMask" effect to the "boom" sprite, which is located on the "Instanse" layout. But if you create an empty project and add this effect, then there is no problem.

The problem happens after export or through remote preview. In the normal preview, no error occurs

r168
The source has sent to Ashley's mail

![1-chrome-error](https://user-images.githubusercontent.com/50992459/65449165-0fc11d00-de43-11e9-9c08-3b7ccc2b725c.jpg)

**Comment by AshleyScirra** [comment]
Please use the bug report template. The project you provided uses third-party addons, so I am afraid we cannot support it.
