### ISSUE TITLE
Solid tilemap disappearing for no reason whatsoever

### ISSUE THREAD

**Issue by Bigbeto123** [Scirra/Construct-3-bugs#3366]
3rd floor's tilemap disappear when you're midway to the leftmost part of the layout. No events, collision nor objects are even triggered in that region, so this is interesting to say the least.
I'm truly sorry for posting such a lenghty project once again. But this time I swear, I could not find a way to reproduce this bug outside of this project... And I tried a lot of times.
Since it's kinda complete, here are the controls: F = Flashlight; E = Inventory; 1-6 = item hotkeys; c = smoke.
Also, don't press space cause it's a debug key (and will cause your death)

https://drive.google.com/open?id=1QVUkvaara73-0Va3ViqcQZyzN0emKObV

Get to the third floor, and then start walking towards the leftmost part of the layout, then the solid tilemap (floor) will simply disapper for no reason... And it only comes back if you go back to the right side.

1.Get to the third floor (solving puzzles, don't worry, they're pretty easy)
2.Start walking to the leftmost side of the map
3.Bug found

## Observed result

The tiles shouldn't disappear...

The solid tiles disappeared

Chrome, Windows 10 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r164.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 104 gb
Storage usage (approx): 1.5 gb (1.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Bigbeto123** [comment]
It only affects the solid tileset for some reason... It's literally identical to the other floor's solid tileset, except for the fact that it disappears midway through the left.
Once again, sorry for the lenght of the file, I just could not find a way to reproduce this bug outside of it.

**Comment by Bigbeto123** [comment]
UPDATE: Solved it by unchecking the "Use Render Cells" box from the solid tilemap's layer. It's clearly a rendering bug then (since I even checked the tile properties in the debug mode and it showed it was 100% opacity, visible and on the right layer)

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. I'm afraid we cannot investigate such large and complex projects.

If you have found a way to resolve the issue, that could help you narrow it down to a minimal project that you can then file as a bug report which we will be able to investigate.
