### ISSUE TITLE
Debug APK fails to open if Desync'd Compositing is selected

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#3369]
## Problem description

Debug APK fails to open if Desync'd Compositing is selected under project properties.

## Attach a .c3p

**cp3 basic 1080 portrait project with desync'd selected**
https://drive.google.com/open?id=1Wql8WF6ID9xKbI1AnAPCWdC4FNmCJ5e1
**apk built from above project**
https://drive.google.com/open?id=1Qp1Zda29PFeko2KErHBMJqCqebssB6_8

## Steps to reproduce

**New Project** 
1080 Portrait
**Compositing Mode - Low Latency**

**Android Build**
Deduplicate yes
Recrompress yes
Minification Advanced 
Min Version - 8.0+ (Oreo)
**Type Debug APK**
Check Hide Status Bar

## Observed result

App black screen for 1 second then closes out.

## Expected result

open as normal

## More details

Tested only on CUBOT POWER Android 8.1

**Comment by AshleyScirra** [comment]
Looks like a bug in the Android WebView. Filed it here: https://bugs.chromium.org/p/chromium/issues/detail?id=1008842

The next update will disable the option in Cordova to work around it.

**Comment by NetOneGames** [comment]
Ahh that's a shame, it does noticeably improve input>sound lag in the phone browser version, assume it would be the same for webview.   Cheers...
