### ISSUE TITLE
Export to Cordova issue

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#337]
## Problem description
I have filled information like description, ID & version etc but when export to cordova. It always  asking for ID, description and version
*Enter a concise description of your problem here*
I have filled information like description, ID & version etc but when export to cordova. It always  asking for ID, description and version, Also tried on a blank project and just filled project form of ID, description but still its asking for that 
## Attach a .c3p
No .c3p required 
Problem on blank projects too
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. just fill ID, Description, version & other detail
2. Export to cordova

## Observed result
Popup Message for filling form of ID, description and version
*What do you see happen?*
message for filling form
## Expected result
Export to cordova next Step
*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Does your version number match the 3 digit format 1.0.0?
Does your ID match the format com.company.name?

These are requirements for cordova, there was a lot of invalid projects being sent to the build server so we have tightened up the validation. The error message does say this?

**Comment by luckyrawatlucky** [comment]
yes

**Comment by shortercode** [comment]
Could you send a project? I've just tested it and it works for me

**Comment by luckyrawatlucky** [comment]
Sorry I have set version to 4 digits i.e 1.0.0.0
Now i have set to 1.0.0.0 its working 
Thanks

**Comment by shortercode** [comment]
That's okay, we're planning to adjust it back to accepting 4 value version numbers for the next build. It's a little too confusing that the required format doesn't match our default.

Cordova will actually allow 4 value version numbers, but the play store will not take into account the 4th digit when deciding if a build is newer than the last. We're going to add a warning somewhere about this saying what the effective versionCode will be.
