### ISSUE TITLE
iOS app stuck on splashscreen when installed via Test Flight. Xcode simulator giving error too.

### ISSUE THREAD

**Issue by DaveedA13** [Scirra/Construct-3-bugs#3370]
#2630  Problem description

I tried my first XCode archive 2 days ago and it worked fine.

Today with a second build I can't even make the device simulator work in Xcode, I have a strange error, IN the simulated device itself:

"**Software update needed**
Note: The iOS simulator is not currently supported due to an Apple bug"
...with "Missing features: WebAssembly" at the bottom. :/

Any idea on what is causing this...?

I have the **latest** MacOS **and** version of Xcode, and it worked 2 days ago.

When testing on a real machine via TEST FLIGHT this build is stuck on the splash screen, I tried "Percentage text" for "Loader Style" and I'm stuck at 0%.

I'm using Construct 3 runtime.

Thanks in advance.

## Steps to reproduce

1. I'm exporting my project via EXPORT -> iOS (Cordova), without minifying (is it necessary for Xcode?).
2. I'm selecting Xcode project for ios build.

I did the same 2 days ago with the same project, didn't do any major change to it, and all worked fine then.

## System details

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.0416666269302368
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r164.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 415 mb (3.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by shortercode** [comment]
As the error message says, the simulator doesn't have WebAssembly. Apple hasn't given a reason for this yet, but I presume it's an issue with emulation. You can track the issue on the WebKit bug tracker here:

https://bugs.webkit.org/show_bug.cgi?id=191064

**Comment by shortercode** [comment]
@DaveedA13 this issue could do with rewriting, it's confusing 2 separate issues and is missing several parts of the issue template. 

We can't do anything about the issues with the iOS simulator, so we won't track that as an issue. Can you note the last revision of C3 this worked with, and the version that isn't working. As well as providing a minimal project for us to replicate this issue.

**Comment by DaveedA13** [comment]
@shortercode 

Thanks for the quick reply about WebAssembly, so it's just the Xcode simulator, it doesn't affect the finalised app?

Sorry for the confusion, the 2 issues appeared at the same time so I was sure it was linked. If the "WebAssembly" is dated that much, I don't understand why it worked on my first try, 2 days ago with Xcode.

I had the same C3 version, my version of Construct 3 is R 164.3, the update is from september 10 so I had the same version 2 days ago...

I'll try to create a new project step by step and retry it in Xcode and I'll come here with a minimal project if (or when) I'll have the same issue.

I bought Construct 3 to try my hand at iOS apps, and I hope really hope I'll be able to properly import/xport into Xcode soon. :/ 

Many thanks for the quick replies.

**Comment by AshleyScirra** [comment]
Regarding WebAssembly - the error message is already telling you what's going on:

> Note: The iOS simulator is not currently supported due to an Apple bug

Click the linked issue to see the relevant Apple bug.

**Comment by shortercode** [comment]
iOS has supported WebAssembly ( WASM ) since version 11, so it shouldn't affect the finalised app. If you need to support devices running an older version of iOS then we recommend using the C2 runtime ( select-able in advanced project properties ) which does not require WASM for any features. The lack of support in the simulator is a quirk of it not being a real iOS device. It's unfortunate, but we can't do much about it ( I find it equally frustrating ).

If you did not experience the problem with the simulator in the past, you might have been using a project with the C2 runtime. The C3 runtime is the default in the editor for new projects, and has been for awhile. But older projects will be using the C2 runtime. Issues occur independently on each runtime, so it's possible that you have found a bug in the C3 runtime.

If you can track down what situation creates your bug we are happy to investigate, but this is too vague for us to look into at the moment.

**Comment by AshleyScirra** [comment]
This report is not actionable so as per our policy I'm closing it.

Please file a new issue following all the guidelines, such as including a project, when you can narrow down the issue.
