### ISSUE TITLE
Can't Use Construct3 Editor !!!

### ISSUE THREAD

**Issue by KatieKoolYT** [Scirra/Construct-3-bugs#3371]
## Modal Comes Up Saying **"Oops, something went wrong!"**
ERROR MESSAGE:

Error report information

Type: unhandled rejection
Reason: Error: The operation is insecure. @ ǃwKJ@https://editor.construct.net/r164-3/components/misc/startPage/startPage.js:1:5643 ǃwKq/<@https://editor.construct.net/r164-3/components/misc/startPage/startPage.js:1:4445 n@https://editor.construct.net/r164-3/main.js:2:199600 t@https://editor.construct.net/r164-3/main.js:2:199385
Stack: ǃwKJ@https://editor.construct.net/r164-3/components/misc/startPage/startPage.js:1:5643 ǃwKq/<@https://editor.construct.net/r164-3/components/misc/startPage/startPage.js:1:4445 n@https://editor.construct.net/r164-3/main.js:2:199600 t@https://editor.construct.net/r164-3/main.js:2:199385
Construct 3 version: r164.3
URL: https://editor.construct.net/
Date: Fri Sep 27 2019 09:01:11 GMT-0700 (Pacific Daylight Time)
Uptime: 3.8 s
Platform information

Browser: Firefox
Browser version: 69.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
C3 release: r164.3 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7520G Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Attach a .c3p

Please Note - I could NOT make a .c3p file because I couldn't get past the error message! Do not ignore my bug report, please.

## Steps to reproduce

1.Logged in.
2.Opened the editor through the "Free Trial" url.

Please note, I did disable my ABP and my Ghostery - it didn't change anything.

## Observed result

I saw the modal popup:
![Construct3](https://user-images.githubusercontent.com/55889672/65784454-efc18000-e106-11e9-93da-6ba85fe5476e.png)

## Expected result

I expected the 'Welcome' modal, and wanted to start making my game.

## More details

I use Mozilla Firefox 69.0.1. I don't use any other browser, for my own reasons. The issue came up in Construct3 R164.3. I just created my account today. I even verified my account and tried to use the editor again.

## System details

Error report information

Type: unhandled rejection
Reason: Error: The operation is insecure. @ ǃwKJ@https://editor.construct.net/r164-3/components/misc/startPage/startPage.js:1:5643 ǃwKq/<@https://editor.construct.net/r164-3/components/misc/startPage/startPage.js:1:4445 n@https://editor.construct.net/r164-3/main.js:2:199600 t@https://editor.construct.net/r164-3/main.js:2:199385
Stack: ǃwKJ@https://editor.construct.net/r164-3/components/misc/startPage/startPage.js:1:5643 ǃwKq/<@https://editor.construct.net/r164-3/components/misc/startPage/startPage.js:1:4445 n@https://editor.construct.net/r164-3/main.js:2:199600 t@https://editor.construct.net/r164-3/main.js:2:199385
Construct 3 version: r164.3
URL: https://editor.construct.net/
Date: Fri Sep 27 2019 09:01:11 GMT-0700 (Pacific Daylight Time)
Uptime: 3.8 s
Platform information

Browser: Firefox
Browser version: 69.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
C3 release: r164.3 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7520G Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
Please press F12 and report any other error messages that come up in the browser console. I'm afraid there's nothing we can do based on this information alone. Presumably something else has failed before this that caused this to happen, but we have no idea what.

**Comment by AshleyScirra** [comment]
This is the same as #3340 which is already fixed. Please only test the latest version of Construct 3 as the bug report guidelines require, to avoid reporting issues we've already fixed.
