### ISSUE TITLE
No math inputs in image editor

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3373]
## Problem description

This is supported in many places in construct, namely the properties bar, but I noticed it isn´t in the image editor. It would be very handy, for example if you have an image point that needs to be set X+30 pixels through the whole animation. (On a sidenote, it would also be handy to be able to offset an image point by a value through the whole animation/all animations)

## Attach a .c3p

![image](https://user-images.githubusercontent.com/31101309/65835378-f0fcd380-e2e5-11e9-8955-512277729f6d.png)

## Steps to reproduce

1. Open image editor
2. Try and insert a math equation for the image point coordinates

## Observed result

Value just gets set to 0

## Expected result

The equation to be solved and used as the new value.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r168 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 26 gb
Storage usage (approx): 332 mb (1.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a suggestion, not a bug, so please post it here instead: https://construct3.ideas.aha.io/

**Comment by Wackytoaster** [comment]
I think I've mistyped there. I only want the math thing to work because it's very convenient and it isn't a new feature. Nothing more.

I needed to adjust an image point through an animation and it would be nice if I could've just copy&paste "+30" into the fields on each frame instead of doing the math in my head.

The "apply to whole animation" was just an afterthought of that.
