### ISSUE TITLE
Inconsistent Behavior using pathfinding 

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#3378]
## Problem description

When using path finding behavior, trying to calculate path inside a solid, produces inconsistent results. The trigger failed to find path never gets executed, and one instance gets a partial node list close to the point it was trying to calucate a path to, but all he other instances find a different path to somewhere in the layout that is unrelated (see gif attached)

[gif of issue here](https://drive.google.com/file/d/1H-TE5Adzs0-Oqt4PB1kRt-bPkf5U8XIc/view?usp=sharing)

 
## Attach a .c3p

[link to c3p file](https://drive.google.com/open?id=1S3dDCgS7ppdNuAnHHeErv422HvAnCxzg)

## Steps to reproduce

1. click on a solid tile (the darker tiles)
2. 
3.

## Observed result

one entity calculates a path close to the clicked on point, the other 3 entity calculate a path to a different point in the layout. the issue seems to be in the generation of of pathfinding nodelist, changing the mechanism that moves the object (pathfinding, moveto, manual) does not seem to effect the end result. by the time the movement starts that nodes in the path are already calculated

## Expected result

i would expect this will trigger the path not found condition, but at the very least send all the instances to the same location

## More details

**Affected browsers/platforms:** Chrme

**First affected release:** r169 (the latest beta)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r169 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 500 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release.
