### ISSUE TITLE
Drag any event line to the bottom of event sheet crash

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#3380]
## Problem description

Event line will crash if you drag it to the bottom of the event sheet. It crashes even if there is only 1 event line in the event sheet. It doesn't event matter if it is a function or a group or a comment, it will still crash.

## Steps to reproduce

1. Create an empty comment in an event sheet or any event triggers/conditions or a group.
2. Drag and move it to the bottom as though if you are trying to move that event line to the bottom of the event sheet.

## Observed result

Crash when dragged to the bottom.

## Expected result

Don't Crash.

## More details
Might be related to #3334 crash report.

**Affected browsers/platforms:** 

Chrome.

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r169/main.js, line 2, col 94549
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Function.ǃ_ (https://editor.construct.net/r169/main.js:2:94555) at d.ǃEWR (https://editor.construct.net/r169/components/editors/eventSheetView/eventSheetView.js:1:31724) at d.ǃRQ (https://editor.construct.net/r169/components/editors/eventSheetView/eventSheetView.js:1:29976) at d.ǃEWv (https://editor.construct.net/r169/components/editors/eventSheetView/eventSheetView.js:1:28827) at d.ǃMp (https://editor.construct.net/r169/components/editors/eventSheetView/eventSheetView.js:1:24521) at HTMLDocument. (https://editor.construct.net/r169/components/editors/eventSheetView/eventSheetView.js:1:2340) at HTMLDocument. (https://editor.construct.net/r169/main.js:2:190779)
Construct 3 version: r169
URL: https://editor.construct.net/r169/
Date: Thu Oct 03 2019 00:07:03 GMT+0800 (Malaysia Time)
Uptime: 299.5 s

Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r169 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) UHD Graphics 617
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Yep, another drag-and-drop edge case... thanks, should be fixed for next release.
