### ISSUE TITLE
Cannot open the project due to type mismatch. 

### ISSUE THREAD

**Issue by Thersippos** [Scirra/Construct-3-bugs#3382]
I cannot open the project. Software is forcing me to close and restart Construct 3, due to "type mismatch". The crazy part, is that construct allowed me to save the project with the latest 169 version, so now I cannot open the project with any previous version.... I am in a loop.

Here is the whole bug report from the software:

Error report information
Type: unhandled rejection
Reason: Type mismatch: * does not work with 'number' and 'string'
Construct 3 version: r169
URL: https://editor.construct.net/r169/
Date: Thu Oct 03 2019 12:31:16 GMT+0300 (Eastern European Summer Time)
Uptime: 69.2 s

Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r169 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by shortercode** [comment]
@Thersippos we cannot debug why a project cannot be opened, without the project. Please do not ignore the issue template, each part is there for a reason.

[Bug report guidelines](https://github.com/Scirra/Construct-3-bugs/blob/master/README.md)

> ## Use the bug report template
> The bug submission page is pre-filled with a template. We need all this information to help you. Do not delete it. Please provide as much of the requested information as you can, including the system details or crash report information with every report.

If you fill in a complete bug report, then we will investigate the issue.
