### ISSUE TITLE
Move To behavior - Move to object

### ISSUE THREAD

**Issue by KENYONBcom** [Scirra/Construct-3-bugs#3383]
## Problem description

The Move To behavior does not work when using Move To Object.

## Attach a .c3p

[move to test.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3685829/move.to.test.c3p.zip)

## Steps to reproduce

1. create player sprite
2. add move to behavior to player sprite
3. create target object sprite
3. set move to object on mouse click

## Observed result

the sprite disappears

the player sprite should move to the target object

the sprite should move to the target object sprite

## More details

**Affected browsers/platforms:** 

all

**First affected release:** I've never been able to get this to work since the first beta it was released in.

## System details

C3 beta r169

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Oops, the behavior was misconfigured and it broke the 'Move to object' action. The other move actions should work though. Fixed for next release.
