### ISSUE TITLE
A script error occurs when hardware acceleration is disabled in the browser.

### ISSUE THREAD

**Issue by horyu1234** [Scirra/Construct-3-bugs#3385]
## Problem description

A script error occurs when hardware acceleration is disabled in the browser.

Construct 2 is works good with disabled hardware acceleration

## Attach a .c3p

[Test Project.zip](https://github.com/Scirra/Construct-3-bugs/files/3688884/Test.Project.zip)

## Steps to reproduce

1. Open chrome browser
2. Paste the following in the URL area: chrome://settings/system
3. Disable this option. [Use hardware acceleration when available]
4. Open game that created with Construct 3

## Observed result

Run normally without script errors

## Expected result

A script error occurs, and the screen appears only black.
```
Uncaught (in promise) TypeError: Failed to execute 'getContext' on 'OffscreenCanvas': The provided value 'experimental-webgl' is not a valid enum value of type OffscreenRenderingContextType.
    at m (c3runtime.js:2)
    at new g_aQ.g_nY.g_vP (c3runtime.js:2)
    at Function.g_aQ.g_el (c3runtime.js:2)
    at g_aQ.g_akk.g_gd (c3runtime.js:2)
    at g_aQ.g_ami.g_aoq (c3runtime.js:2)
    at g_aQ.g_ami.g_ahs (c3runtime.js:2)
    at async a (workermain.js:1)
```

## More details

**Affected browsers/platforms:** 
Chrome, Windows 10

**First affected release:** 
Latest stable version

<details><summary>chrome://gpu</summary>

Graphics Feature Status
Canvas: Software only, hardware acceleration unavailable
Flash: Software only. Hardware acceleration disabled
Flash Stage3D: Software only. Hardware acceleration disabled
Flash Stage3D Baseline profile: Software only. Hardware acceleration disabled
Compositing: Software only. Hardware acceleration disabled
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
Hardware Protected Video Decode: Disabled
Rasterization: Software only. Hardware acceleration disabled
Skia Renderer: Disabled
Video Decode: Software only. Hardware acceleration disabled
Viz Display Compositor: Enabled
Viz Hit-test Surface Layer: Disabled
WebGL: Software only, hardware acceleration unavailable
WebGL2: Software only, hardware acceleration unavailable

Data exported | 2019-10-04T03:55:25.395Z
-- | --
Chrome version | Chrome/77.0.3865.90
Operating system | Windows NT 10.0.18362
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/58c425ba843df2918d9d4b409331972646c393dd/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/58c425ba843df2918d9d4b409331972646c393dd/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | 7cf862c9fcd2
2D graphics backend | Skia/77 a10014304cba4f24b7af17191f59490faa8aee77
Command Line | "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --disable-quic --flag-switches-end

</details>

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r164.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 33 gb
Storage usage (approx): 49 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions:

EXT_color_buffer_float
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Turns out there is a nasty edge case in Chrome that unexpectedly makes it throw an exception instead of failing normally. Fixed this for the next release - in the mean time disable worker mode in project advanced settings to work around it.
