### ISSUE TITLE
Viewport(Width/Height) Calculating Wrong

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#3386]
## Problem description

Red Dot placed center of layout. I used event for place other Dot to center but it doesn't work.

## Attach a .c3p

[Viewport.zip](https://github.com/Scirra/Construct-3-bugs/files/3690038/Viewport.zip)

## Steps to reproduce

1. Preview project
2. Change screen size

## Observed result

![image](https://user-images.githubusercontent.com/54614906/66199898-74cd0c00-e6a8-11e9-9301-bdd25a8737fa.png)

## Expected result

Center of screen

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r168

**Comment by Wackytoaster** [comment]
I don´t think this is a bug, I think you are misunderstanding how the code you wrote works. Here is a fix. But I don´t actually know if it does what you intend it to do.
[fix.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3690611/fix.c3p.zip)

**Comment by CrackHub** [comment]
Still thinking it is a bug. This working
![image](https://user-images.githubusercontent.com/54614906/66210433-802d3100-e6c2-11e9-94bc-86e344f05b81.png)

**Comment by ariepert** [comment]
I have run into this before - it is because there is an inherent assumption in your code that ViewportLeft is zero. With Scale Outer, you can not be sure that the top left corner is 0,0.

try ViewportLeft(1) + ViewportWidth(1) / 2  and ViewportTop(1) + ViewportHeight(1) / 2

with Scale Outer, always add in the left and top coordinates. It is amazing how subtle that assumption can be and it will show up in your code in places you would never expect!

**Comment by AshleyScirra** [comment]
As noted this is not a bug. The viewport middle is not always half its size, since it could be offset. The correct solution has already been given.

**Comment by gloomie** [comment]
If viewport is offset and middle is not in middle of some other rectangle, then the right of this rect cannot be called "viewport right"! 

I also believe this is a bug of some sort. Either a technical bug or a naming bug. Eitherway, having the viewport middle to be something other than (vright-vleft)/2 is misleading.

**Comment by AshleyScirra** [comment]
This is a closed bug report that was already reviewed and already established that there is no bug. The project incorrectly assumed that if you position an object at half the viewport size, it will be centered. This is not true if the view has scrolled somewhere else. It's as simple as that.
