### ISSUE TITLE
Animation editor preview - Animation frame duration 0 has unexpected behavior

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#3387]
## Problem description

In a serie of animations frame, on frame of duration 0 will cause the preview animation to act unexpected (when previewed in the animation editor only).

## Attach a .c3p

[2019.10.04.anim.frame.duration.zip](https://github.com/Scirra/Construct-3-bugs/files/3690263/2019.10.04.anim.frame.duration.zip)

## Steps to reproduce

1. Open the file
2. Open Sprite in the animation editor.
3. Preview animation 1 (right click on Animation 1 - Preview)

## Observed result

The start of the animation is as intended (alternate between left and right).
When the animation reaches frame 3 (the only frame of duration 0) it looks like the frames are then "melted" and it looks like all frames from then on are of duration 0.

## Expected result

For the animation frame duration to not stay 0.
You can live preview or preview the project and see how the animation is supposed to display.

**Comment by AshleyScirra** [comment]
FYI the attached project does not set any frame to duration 0 - so to reproduce make sure frame 3 is selected and the duration set to 0 before previewing.

Also BTW an animation frame duration of 0 isn't really useful - the runtime playback never skips frames, so a duration of 0 will show it for a single frame, which is technically framerate-dependent as well. Still I don't think there's a sensible minimum we could set... maybe if it's set to 0 we could just set it back to 1 so the user can't pick exactly 0 as the duration.

**Comment by Wackytoaster** [comment]
Logically, it should be skipped imo. But I don´t see why anyone would need this.

**Comment by Kyatric** [comment]
It was during a teaching event for teachers, to later use with their students.
They were asked to make several frames to make an enemy. One of the teachers did duplicate existing frame and somehow found himself with the value modified, hence causing the bug.
On the moment, it was more of a matter for me to determine and help him having the "correct" animation he was expecting of alternating frames.
One of the frames had a duration of 0 and displayed wrongly in the preview mode, leading to the discovery of that issue.

**Comment by DiegoScirra** [comment]
Fixed in the next beta. The animations editor preview should no produce the same results as the runtime.
