### ISSUE TITLE
Physics objects don´t listen to object timescale

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3388]
Physics objects do not take the object timescale into account. However, they do take the global timescale into account. I don´t know if this is a restriction on the side of box2d or a bug.
(The reason I intended to increase the timescale is the fact that with a high world gravity objects will start jittering on the floor instead of going to sleep, and I feel like the standard gravity is way too floaty and moonlike. The jittering seems to be a general issue with box2d and not construct related from what I managed to google)

[timescalephysics.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3690503/timescalephysics.c3p.zip)

## Steps to reproduce

1. Start preview
2. Right and left blue square have different timescale
3. Right and left red square should have different timescale, but don´t
4. If you reenable the disabled action of setting the global timescale, they will jump faster.

## Observed result

The object timescale is ignored

## Expected result

The object timescale to be taken into account

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r169 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 94 gb
Storage usage (approx): 460 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think this is either not a bug or something we just can't fix anyway. Normally the time scale is multiplied with dt to give the time step per instance. However the physics world is globally stepped using a single dt measurement, so there is no opportunity to alter it per instance. It's possible we could do something like multiply forces by the time scale, but I don't think that is physically correct. Therefore I think per-instance time scales are simply not compatible with Physics.

**Comment by Wackytoaster** [comment]
I kinda suspected that. Bummer, but I guess working with the global timescale should be fine too.
