### ISSUE TITLE
spritefont vertical alignment text shown incorrectly when bbcode is used

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3389]
## Problem description
spritefonts with bottom vertical alignment don'T show correctly when bbcode is used

## Attach a .c3p
https://puu.sh/EoQrX/0d714b947b.c3p

## Steps to reproduce

1.use a spritefont object
2.add multiple lines of text to it and make one of them use like scale bbcode or height bbcode

## Observed result
the text dosent show up properly 
![image](https://user-images.githubusercontent.com/32940085/66238056-abb11b00-e6c4-11e9-99a8-e6bb9a69fb27.png)

## Expected result
for the text oto render properly

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta cycle.
