### ISSUE TITLE
Editor crash on "Clone object"

### ISSUE THREAD

**Issue by yojona** [Scirra/Construct-3-bugs#339]
## Problem description

When I try to clone a Sprite object, editor crash.

## Attach a .c3p
[clone.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1024949/clone.c3p.zip)

## Steps to reproduce

1. Open project
2. Right click
3. "Clone"

## Observed result

Crash

## Expected result

Clone object

## Affected browsers

* Chrome: yes/no

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r30/main.js, line 61, col 198910
Message: Uncaught Error: animation frame has no content
Stack: Error: animation frame has no content at ae.ǃJDN (https://editor.construct.net/r30/main.js:61:198916) at ae.ǃJEN (https://editor.construct.net/r30/main.js:61:200699) at ae.ǃJDF (https://editor.construct.net/r30/main.js:61:196647) at ae.ǃIP (https://editor.construct.net/r30/main.js:61:203286) at ae.ǃNy (https://editor.construct.net/r30/main.js:61:203747) at te.ǃJTi (https://editor.construct.net/r30/main.js:61:191877) at ee.ǃIs (https://editor.construct.net/r30/main.js:61:184340) at window.ǃOA.ǃOA.ǃID (https://editor.construct.net/r30/components/bars/projectBar/projectBar.js:1:18989) at d.ǃtH.ǃrS.m.ǃw (https://editor.construct.net/r30/components/bars/projectBar/projectBar.js:1:18264)
Construct 3 version: r30
URL: https://editor.construct.net/
Date: Wed May 24 2017 01:54:15 GMT-0700 (MST)
Uptime: 167.3 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r30

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for r31.
