### ISSUE TITLE
Remote Preview makes new client on update with every client refresh resulting in multiple false connected clients.

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#3391]
Remote Preview makes a new client update with every client refresh resulting in multiple connected clients.

## Attach a .c3p

Use a new default blank c3 project (or any other project)

## Steps to reproduce

1. Launch remote preview.
2. Scan code with mobile to launch preview on mobile
3. change something in the editor, or not, it dosent matter
4. press preview again.
5. see the update message on the mobile
6. refresh the mobile browser to get the update
7. notice new connected client in remote preview pop up.
repeat for more clients.

## Observed result

![image](https://user-images.githubusercontent.com/21962641/66258332-ee91f200-e79b-11e9-98c0-36c970082335.png)

## Expected result

not multiple clients ?

## More details

previewed in chrome 77 on android 8

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r169 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 215 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro K2000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by NetOneGames** [comment]
also totally unrelated. I noticed the system / platform info states Aprox 8 GB device memory but I triple checked I have, and my system is using, 32GB memory.

**Comment by AshleyScirra** [comment]
We try to close the connection when the page unloads, but it seems the connection simply times out in this case. It looks like a recent change in Chrome means we have to add new code to detect the timing out case. I've added this and it appears to fix the problem, but I'm not completely sure what the impact will be, so the fix will come out in the next beta cycle after the next stable release.
