### ISSUE TITLE
Construct's save doesn't save changes to its Jsons objects.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3392]
## Problem description

Whenever I save and load from the basic Construct's method, it works fine for mostly everything, but C3 Jsons object seem to not save. I'm providing two .c3p files as zip, The first (Saving_Normal) showing the method working normally and a second one (Save_json) trying to save Jsons and failing to load them.

It might be because I didn't understand some part of the documentation, but I tried my best, sorry on any oversight on my part.

## Attach a .c3p

[Saving_Normal.zip](https://github.com/Scirra/Construct-3-bugs/files/3693812/Saving_Normal.zip)
[Saving_Json.zip](https://github.com/Scirra/Construct-3-bugs/files/3693811/Saving_Json.zip)

## Steps to reproduce

1. Create a Json file.
2. Use Ajax to load said file into a C3 Json object.
3. Change some value in the C3 Json object.
4. Use common Construct's save method to try to save some change in a json object.
5. Try to load this save and check the C3 Json object value.
6. The value most likely did not change.

## Observed result

The values of a C3 Json object do not persist through sessions by using the basic save method from C3.

## Expected result

I thought whenever I changed any value on a C3 Json object, it would persist through sessions even using the basic save method from C3.

## More details

**Affected browsers/platforms:** Chrome for sure, maybe others too.

**First affected release:** never seen it work

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r164.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 463 gb
Storage usage (approx): 70 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
The implementation for this in the JSON object appears to be entirely missing. Assigned to @shortercode to implement.

**Comment by shortercode** [comment]
Fixed for next beta release.
