### ISSUE TITLE
Drawing Canvas Save Image fails on iOS

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#3394]
## Drawing Canvas Save Image fails on iOS

Webgl2 error on Save image on iOS (iPhone XR)

## Attach a .c3p
[DCSaveMobile.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3695434/DCSaveMobile.c3p.zip)

## Steps to reproduce

Run, observe error on remote console debug (e.g. Safari on Mac connected to iPhone)

## Observed result

Image not saved. Error report in remote console (see details summary.)

## Expected result

Image saved and loaded to second sprite (which works on Mac in Chrome.)

## More details

Error log on iOS

**Affected browsers/platforms:** Safari iOS

**First affected release:** 

## System details
iPhone XR

<details><summary>View details</summary>

[Error] WebGL: INVALID_ENUM: bufferData: invalid usage
	bufferData
	(anonymous function) (blob:https://preview.construct.net/fa6bcba0-9064-4313-98c2-d6f382c36a58:1:32534)
	asyncFunctionResume
	Do (blob:https://preview.construct.net/fe11d3fe-efa2-49c7-bb7a-519b0e7b5b1e:1:476)
	Tick2 (blob:https://preview.construct.net/7ab695c7-7888-4c68-8803-4ba4e03f8e5f:1:3515)
	_FireNonCancellable (blob:https://preview.construct.net/d3976c65-52b3-4036-aa95-3bbef1a0bad6:1:2446)
	(anonymous function) (blob:https://preview.construct.net/ca81dccc-3687-42af-9afd-de0761dc5013:1:28431)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
[Error] Unhandled Promise Rejection: TypeError: Argument 7 ('pixels') to WebGL2RenderingContext.readPixels must be an instance of ArrayBufferView
	(anonymous function) (blob:https://preview.construct.net/fa6bcba0-9064-4313-98c2-d6f382c36a58:1:32569)
	promiseReactionJob
</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here, tested both iOS 12 and iOS 13 and in both cases Sprite2 successfully loaded a copy of the Drawing Canvas image. Please always include the full system details - I would guess you are using a buggy beta version of iOS or something.

**Comment by MikalDev** [comment]
Software version: iOS 12.4.1, not beta.

WebGL 2.0 enabled for Safari the issue occurs.
WebGL 2.0 disabled and the issue does not occur.

However, from your comment, it looks like you will not support this.

**Comment by shortercode** [comment]
@MikalDev WebGL 2 is incomplete in Safari, and quite a few things don't work on it. I would not advise using it.

**Comment by MikalDev** [comment]
Thanks for the comments, will steer clear of WebGL2 on iOS / Safari.

I previously had it enabled due to some work I was doing with WebGL2 VAOs for the Spine plugin, however, I now have added a WebGL1 code path to use OES_vertex_array_object instead, so now I can disable WebGL2 on iOS/Safari.

An idea to improve user experience - if C3 runtime is running on iOS, do not have C3 ask for a WebGL2 context since it's incomplete.
