### ISSUE TITLE
C3 TEXT BBCODE OUTLINE ISSUE

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#3395]
## Problem description

Text using bbcode outline is not being rendered correctly 

## Attach a .c3p
https://www.dropbox.com/s/f0mfb7ntpijfksc/bbcodeOutline.c3p?dl=1

## Steps to reproduce

1.Run the project
2.Type some text into the text box, and hit the OK button.
3.Note the output text in the text object
4.Leave the tab for approximately 30 seconds
5. Return to the tab and repeat the original steps

## Observed result

The first rendered text appears overdrawn
The second time the text appears correctly

## Expected result
No harsh lines.

## More details
https://www.construct.net/en/forum/construct-3/general-discussion-7/c3-text-bbcode-outline-issue-147404

**Affected browsers/platforms:** 
Chrome
170

**First affected release:** 
Unknown
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta cycle.
