### ISSUE TITLE
Edge case with Safe Mode and Beta URL

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#3398]
## Problem description
It's currently not possible to enable safe mode using the beta URL.

## Steps to reproduce

1. Open: https://editor.construct.net/beta/?safe-mode
2. Notice "beta" being replaced by latest beta version
3. Notice safe mode tag not being applied as expected

## Observed result

Enabling safe mode while using the beta URL isn't enabling safe mode.

(Since there is no "safe mode is enabled" indicator, I've used [this broken addon](https://github.com/TheRealDannyyy/Construct-3-Desktop-Launcher/raw/master/Workspace/Experiments/Safemode%20Test/broken.c3addon) for testing. Just run the latest beta release, install it and it should crash on startup if safe mode is disabled.)

## Expected result
The web link "parser" should respect safe mode and automatically add it, after changing the beta tag to the latest beta release version.

**Example**
1. Enter: https://editor.construct.net/beta/?safe-mode
2. Parse (version): https://editor.construct.net/r170/
3. Parse (safe mode): https://editor.construct.net/r170/?safe-mode

## System details
Windows 7, Chrome.

**Comment by AshleyScirra** [comment]
Does this matter? You can just enable safe mode for a specific release. It's designed for one off use for developers so that seems fine. The redirect is handled by the service worker which is a huge pain to deal with, and I'd prefer not to get in to that if there's not a compelling reason to do so.

**Comment by TheRealDannyyy** [comment]
I just thought it was a minor oversight that could be fixed in matter of seconds. If it's deeply integrated into the whole system, might just leave it as is. Personally not that big of a deal.

**Comment by AshleyScirra** [comment]
OK, closing as wontfix.
