### ISSUE TITLE
Object Selected UI Issue with ALT Key Pressed

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#34]
## Problem description

After selecting any object on the layout view, pressing ALT key will remove the **visual** indicators for resize and rotate.

## Steps to reproduce

1. Select any object from layout view
2. press ALT key

## Observed result

**visual** indicators for resize and rotate disappears.

## Expected result

Nothing changed.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
This is by design. It lets you select objects under the resize handles, for example, without having to first deselect the object.
