### ISSUE TITLE
[Request] Half transparency UI for Expression dictionary

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#340]
## Problem description

I always appreciate the feature in C2 where the Expression dictionary has a half-transparency look when the mouse is not hovering over it. This really helps in getting some visual aids when working on the event sheets. Now in C3 it just does not do that any more.

Would be nice to have this effect for both when the UI Animation is disabled & enabled.

**Comment by DiegoScirra** [comment]
Added in r31.

The expressions dictionary now fades out if the pointer is not on top of it and it doesn't have focus.

Once the dialog gains focus by being interacted with, it will remain opaque until the parameters dialog regains focus.

At least that is what I think C2 is doing :P

**Comment by jaydonteh** [comment]
@DiegoScirra Great job adding it so quickly! Would be a little better if it has lower opacity like around 10%

**Comment by tunepunk** [comment]
Sorry to revisit this old issue. But can we have a setting for this? I find it really frustrating that it's constantly fading.
