### ISSUE TITLE
Functions, Return Type issue

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#3402]
## Problem description

"Return Type" field is disabled when adding a new function.

## Attach a .c3p

Create a new project

## Steps to reproduce

1. Create a project
2. Go to event sheet
3. Right click -> Add Function (Return type is enabled, leave it "None")
3. Add an event: On start of layout
4. Add an action: Call Function1
5. Right Click on Function1 - > Edit Function (Return type is disabled)
6. Add a new function (Return type is disabled)

## Observed result

Return type is disabled when adding a new function.

## Expected result

Return type to be enabled when adding a new function

## More details

Return type remains disabled, even if you close project and start another new project. You have to close and restart construct in order to have Return type available again.

**Affected browsers/platforms:** Desktop/Firefox, Windows

**First affected release:** r170? I'm not sure about this

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.41.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.41.0 (like Chrome/77.0.3865.75)
C3 release: r170.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 3.8 gb
Storage usage (approx): 1 gb (26.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Your original report didn't mention that. I can reproduce that so will take a look.

**Comment by AshleyScirra** [comment]
Yeah, that was a simple oversight, it should be fixed in the next release.

**Comment by Dramamini** [comment]
Sorry, step 7 was not clear, indeed.. I should write "Add a new function, Function2" or something like that..
