### ISSUE TITLE
onTouched bug for Safari on iOS 

### ISSUE THREAD

**Issue by TheWebGuruDotNet** [Scirra/Construct-3-bugs#3403]
Hello guys,

your system gave me the best solution for the time i had to develop this game for a client
yet i am facing a huge issue where the link (browser - Go To) is not functional on iOS

i am sure that you have been asked this over and over since this is common block thing from Safari as usual.

here is my game: 503020.ie
this game aims to drive people to that FINANCIAL TEST link.
so if this does not work the whole thing is useless.

have you found a work around for iOS?

please get back to me as this is urgent

thank you!

## Steps to reproduce

1. Open the game at 503020.ie on iphone (Safari over iOS)
2. Play the game and it ends few rounds after
3. Click on "take the financial test, link will not open

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE
[503020.zip](https://github.com/Scirra/Construct-3-bugs/files/3716887/503020.zip)

</details>

**Comment by shortercode** [comment]
I'm not aware of any restrictions related to links in Safari, @AshleyScirra ?

**Comment by AshleyScirra** [comment]
I would guess it's simply the popup blocker - you can only generally open links in a user input trigger. Or it could be that the event that opens the link is simply false, but it's hard to rule that out since there are so many events in the project. Please see the bug report guidelines: they are there to rule out a mistake in your project and ensure we can help.

**Comment by TheWebGuruDotNet** [comment]
The proper way of testing this is to open 503020.ie on your iphone using Safari
This works perfect everywhere else.
how would you set a link to a URL in a new tab properly? is it not like the screenshot attached ?

![src1](https://user-images.githubusercontent.com/56264102/66652204-0a2e4a00-ec2d-11e9-8b10-a46f7cd816f6.jpg)
![src2](https://user-images.githubusercontent.com/56264102/66652206-0a2e4a00-ec2d-11e9-9534-5cd654b74b61.jpg)

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines; it should be easy to provide a minimal project demonstrating this. Further if it only happens in one browser, that strongly suggests a limitation in that browser, not a problem with Construct, hence the theory it's a popup blocker.

**Comment by TheWebGuruDotNet** [comment]
Bug Report Guidelines? 
Any work around for this ? Javascript maybe?

**Comment by AshleyScirra** [comment]
The guidelines are here: https://github.com/Scirra/Construct-3-bugs
