### ISSUE TITLE
Iframe dont work on Android

### ISSUE THREAD

**Issue by derem444** [Scirra/Construct-3-bugs#3404]
## Problem description

I created an iframe inside my project to open HTML files that are along with my project, the process seems to run normally, but in the exported apk the HTML is not rendered, just lines of code and the images never show

what am i doing wrong? i'm attaching the project here with the example.

The problem happend when i export to android :(

## Attach a .c3p

https://www.mediafire.com/file/0y8tc0xmj88rhk1/iframe_test.c3p/file

## Steps to reproduce

1. export the project to Android Cordova (debug or signed or non signed)
2. open the apk in some device or some emulator
3. try to see a clean html or any image

## Observed result

All the HTML is lost, and the images dont appear

## Expected result

I expected that just work like a normal iframe, i like to see simple html files, with text and images

## More details
in the final version, on the android apk, the html dont show images or nothing than a plain code

**Affected browsers/platforms:** 

The issue happends i all browsers i tried, Android Emulador "Nox", and when i upload the apk signed to the GooglePlay

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r164.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 68 gb
Storage usage (approx): 545 mb (0.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Kyatric** [comment]
Issue treated in the support, the project is not using correct code for what it is intended to do.

**Comment by AshleyScirra** [comment]
iframes are designed to load content from web servers. In a mobile app, it doesn't run from a web server - all resources are stored locally. Local resources have extremely stringent security limitations, far more so than on the web, since there are a number of security issues associated with displaying local files in a browser. Therefore iframes are unlikely to work properly in contects where they don't display from a web server.

I'm not sure it's feasible to work around this I'm afraid. The web is just not meant to work that way.
