### ISSUE TITLE
Preparing project data... getting stuck

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3407]
I preview the project, but I get stuck right there
![image](https://user-images.githubusercontent.com/31101309/66674408-17662b80-ec63-11e9-9cda-ebb177b1f747.png)
The bar is moving as if something is happening but nothing happens, even after some minutes of waiting. I also cannot cancel it forcing me to exit the project. Not entirely sure why or when it happens, I´m just regularely working on a project, saving/editing/previewing. So sadly no real reproduction.

EDIT: I was saving on google cloud and noticed that the notification on the bottom said **"Saving "bla.c3p" to Google Drive 0%. Archiving "bla"** but it was never progressing, even after some time.

So I tried to use "download a copy" but got stuck there...
![image](https://user-images.githubusercontent.com/31101309/66674818-31ecd480-ec64-11e9-96fe-28b533cb17bf.png)

EDIT2: It seems that it randomly fails to save and gets stuck there. I cannot reliably reproduce it...

## Attach a .c3p

Don´t think this helps here?

## Steps to reproduce

I wish I knew

## Observed result

I get stuck on this

## Expected result

Preview to start

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
I think it could be 170.2 but I really don´t know.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r170.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 19 gb
Storage usage (approx): 734 mb (3.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Wackytoaster** [comment]
Well... seems like restarting did the trick. But I´m still not sure why it would get stuck like this :V But I´m glad it was eventually fixed with the classic "have you tried turning it off and on again"

**Comment by AshleyScirra** [comment]
I'm afraid there is nothing we can do about a bug report like this. At the very minimum you need to press F12 and let us know about any more errors that appeared in the browser console. Without that it is impossible to even guess as to what might have happened.

**Comment by Wackytoaster** [comment]
Yeah understandable. There were no errors in the console btw. I always check that :)

**Comment by Hug0h22** [comment]
IF YOU NEED TO SAVE before closing construct you can still hit Ctrl+S to save the project, so you don't lose your progress. Hope this helps!
