### ISSUE TITLE
Google Play Games not working with C3 Runtime

### ISSUE THREAD

**Issue by spinbas** [Scirra/Construct-3-bugs#3409]
## Problem description

Google Play Games Services not work when compile our app with C3 Runtime.

It seems that the plugin makes the automatic login, as appear the welcome popup from Google Play Services, but after the login, the plugin not make any other operations.

Can't get any data from Google Play, make logout...

If we compile it with C2 runtime, works fine.

I attach a .c3p with a reduced app to test only the Google Play Games funcionality.

## Attach a .c3p

I attach a .c3p with a reduced app to test only the Googe Play Games funcionality, and two signed .apk one compiled with C2 and the other with C3,

## Steps to reproduce

1. Click Logout Button
2. Click Login Button

## Observed result

Do nothing

## Expected result

Logout and login to Google Play services as you click the buttons showing and alert after the operation completes, and show the ID from Google Play Games after login.

## More details

In the LogCat we see this 

**Affected browsers/platforms:**
Android

**First affected release:** 
Not sure

## System details

Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 274 gb
Storage usage (approx): 61 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 515 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by spinbas** [comment]
Sorry here are the files:

[TestGooglePlay.zip](https://github.com/Scirra/Construct-3-bugs/files/3720560/TestGooglePlay.zip)

And the logcat output:

2019-10-12 12:07:25.711 14208-12001/? W/GamesServiceBroker: Client connected with SDK 19266000, Services 19420037, and Games 122750048
2019-10-12 12:07:25.737 14208-14305/? W/Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
2019-10-12 12:07:25.738 14208-14305/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@19420037@19.4.20 (100400-271418971):2)
2019-10-12 12:07:25.739 14208-14305/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@19420037@19.4.20 (100400-271418971):2)
2019-10-12 12:07:25.746 14208-14305/? W/Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
2019-10-12 12:07:25.746 14208-14305/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@19420037@19.4.20 (100400-271418971):2)
2019-10-12 12:07:25.746 14208-14305/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@19420037@19.4.20 (100400-271418971):2)

**Comment by luckyrawatlucky** [comment]
I just tested google play plugin few days ago and its working fine in c3 runtime, i did not found any login or logout issue.

**Comment by AshleyScirra** [comment]
> C3 release: r120 (stable)

You are using a version of Construct that is over a year old. We have released over 50 updates since then. I assume the problem is something we have already fixed. Please follow the bug report guidelines and only report issues that occur in the latest release to avoid reporting problems that are already fixed.
