### ISSUE TITLE
Crash - Value with Function(built-in) reference

### ISSUE THREAD

**Issue by Everade** [Scirra/Construct-3-bugs#3410]
## Problem description
I was in the middle of defining the value which shall be saved into a variable.
Typed out the function, then deleted a few signs (one too much), and continued with a **(**
`Functions.Bounds2(`
It crashed at the time when i typed the **(**
Note:
The correct function name would be Bounds2D

## Attach a .c3p
[FunctionsCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/3721251/FunctionsCrash.zip)

## Steps to reproduce
1. Double click the `System test to Functions.Bounds2D(0)` action
2. Remove the last 4 digits until it says `Functions.Bounds2`
3. Now type `(`

Only seems to crash when you actualy remove the last digits first rather than selecting and replacing them with a ( directly.

## Observed result
**Oops! Something went wrong.**
Construct 3 crashed and had to be restarted.

## Expected result
No crash

## More details
**Affected browsers/platforms:** 
- Chromium C3 ->App
- Microsoft Edge
_no other browsers tested._

**First affected release:**
Unknown, only tested with beta **r170.2**

## System details
<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r170-2/projectResources.js, line 1, col 1138570
Message: Uncaught TypeError: Cannot read property 'ǃEl' of null
Stack: TypeError: Cannot read property 'ǃEl' of null at Object.ǃwhB (https://editor.construct.net/r170-2/projectResources.js:1:1138570) at Object.ǃwqf (https://editor.construct.net/r170-2/projectResources.js:1:1137865) at Object.ǃwqC (https://editor.construct.net/r170-2/projectResources.js:1:1108854) at Object.ǃwqS (https://editor.construct.net/r170-2/projectResources.js:1:1108364) at HTMLDivElement. (https://editor.construct.net/r170-2/projectResources.js:1:1105282)
Construct 3 version: r170.2
URL: https://editor.construct.net/r170-2/
Date: Sun Oct 13 2019 00:57:17 GMT+0200 (Central European Summer Time)
Uptime: 60.4 s

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r170.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
I followed the steps to reproduce and it works fine. Did you miss a step?

**Comment by AshleyScirra** [comment]
Fixed for next release - it was simple so merged in for the upcoming stable release.
