### ISSUE TITLE
Android App freezes when returning from background

### ISSUE THREAD

**Issue by Boulerzzz** [Scirra/Construct-3-bugs#3411]
## Problem description

When you build your app bundle in android studio there is an issue when returning to the app after it has been in the background. The game will sometimes freeze when you return after a longer period of time (more than 10 minutes at least)

Usually games will do a cold start when you return after a long period of time. But all my C3 games freeze after being in the background for a longer period of time now.

You can still interact with the elements in the game but the frame is stuck as it was when you left the game.

## Steps to reproduce

1. Export android app as android studio project
2. Build an app bundle
3. Launch app on phone
4. Return to homescreen and place app in the background
5. Wait 10-15 minutes and reopen.
6. App is now frozen the frame you left it in. You can still interact with the elements but the frame is frozen

## Observed result

App freeze

## Expected result

Return to the app directly or for the app to perform a cold start.

## More details

I tried on several phones. All running android 9 though.

First affected release I can't say. I just noticed it but I can reproduce this issue on older apps as well.

## System details

I debugged the issue in android studio and here is that the console said when I exited and entered the app and it froze.

<details><summary>View details</summary>

W/HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:13.987061, limit is:60The moving distance of Y is:134.9375, limit is:60
D/CordovaActivity: Paused the activity.
D/ZrHung.AppEyeUiProbe: stop checker.
I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
D/ViewRootImpl[MainActivity]: surface should not be released
D/CordovaActivity: Stopped the activity.
W/libEGL: EGLNativeWindowType 0x73de750010 disconnect failed
D/SystemWebChromeClient: file:///android_asset/www/scripts/c3runtime.js: Line 2 : [Construct 3] Suspending
I/chromium: [INFO:CONSOLE(2)] "[Construct 3] Suspending", source: file:///android_asset/www/scripts/c3runtime.js (2)
W/chromium: [WARNING:sync_reader.cc(170)] ASR: No room in socket buffer.: Broken pipe (32)
D/: PlayerBase::stop() from IPlayer
D/AudioTrack: stop() called with 6465600 frames delivered
D/ZrHung.AppEyeUiProbe: Current Activity:false
    not watching, wait.
E/: [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
D/: TrackPlayerBase::~TrackPlayerBase()
    PlayerBase::~PlayerBase()
D/CordovaActivity: Started the activity.
D/ZrHung.AppEyeUiProbe: notify runnable to start.
D/ZrHung.AppEyeUiProbe: restart watching
D/CordovaActivity: Resumed the activity.
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
W/InputMethodManager: startInputReason = 1
W/HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:65.04089, limit is:60The moving distance of Y is:34.6687, limit is:60

</details>

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. We cannot investigate reports unless you follow the guidelines.
