### ISSUE TITLE
[Whitelist] cordova-plugin-icloudkv

### ISSUE THREAD

**Issue by Kraudi** [Scirra/Construct-3-bugs#3415]
Hi!

Is it possible to add **cordova-plugin-icloudkv** to the whitelist? I would like to add iCLoud support to my apps.

**Link**
https://www.npmjs.com/package/cordova-plugin-icloudkv

Thank you
Kraudi

**Comment by shortercode** [comment]
Yeah looks fine. I'll add it to the list.
