### ISSUE TITLE
Custom addon not working in one specific browser

### ISSUE THREAD

**Issue by kokolihapihvi** [Scirra/Construct-3-bugs#3418]
## Problem description

I made an effect for Construct 3, it works for me and a few other people on Google Chrome, however one of my friends reported that the effect does not work on Chrome, but works on Firefox. (detailed versions below)

The error given in chrome console does not really make sense, it's telling me that a float is missing precision, but all the floats have precision specified.

## Attach a .c3p

[weird effect issue.zip](https://github.com/Scirra/Construct-3-bugs/files/3726015/weird.effect.issue.zip)

## Steps to reproduce

1. Install the addon
2. Open the included project

## Observed result

Construct crashes.

## Expected result

You see a circle with a red/green outline.

## More details

**Affected browsers/platforms:** 
Effect works for me on Firefox 70.0b14 as well as Chrome 77.0.3865.120
Effect does not work for my friend on Chrome 77.0.3865.120, but does work on Firefox 69.0.2.

**First affected release:** 
Made the addon in r164.3, still works on r171 for me, does not work for my friend in any version.
## System details

<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r171/main.js, line 63, col 129642
Message: Uncaught Error: effect shader program not compiled
Stack: Error: effect shader program not compiled at n.ǃMn (https://editor.construct.net/r171/main.js:63:129642) at a.ǃWev (https://editor.construct.net/r171/projectResources.js:1:245169) at a.ǃWeR (https://editor.construct.net/r171/projectResources.js:1:245043) at a.ǃIr (https://editor.construct.net/r171/projectResources.js:1:244086) at Z.ǃIr (https://editor.construct.net/r171/projectResources.js:1:227650) at window.ǃvq.ǃns (https://editor.construct.net/r171/components/editors/layoutView/layoutView.js:1:7249) at ǃnM (https://editor.construct.net/r171/components/editors/layoutView/layoutView.js:1:1844)

Construct 3 version: r171
URL: https://editor.construct.net/
Date: Mon Oct 14 2019 22:44:07 GMT+0300 (Eastern European Summer Time)
Uptime: 10.6 s
Platform information
Browser: Chrome
Browser version: 77.0.3865.120
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
C3 release: r171 (stable)
Language setting: en-US
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

<details><summary>Chrome console log</summary>
register-root-sw.js:17 Registered root service worker on https://editor.construct.net/
main.js:2 Error while parsing the 'sandbox' attribute: 'allow-storage-access-by-user-activation' is an invalid sandbox flag.

ǃE.ǃE$L @ main.js:2
main.js:210 Stop!
main.js:210 This is a browser feature intended for developers. If someone told you to copy and paste something here to enable a feature or "hack" something, it is a scam and may allow them to steal your account information or your work.
main.js:210 Note: this is the developer tools console for the Construct editor. If you're looking for developer tools for preview, be sure to open developer tools for the preview window instead.
main.js:210 Registered service worker on https://editor.construct.net/r171/
main.js:63 Failed to compile shader program:  Error: Error compiling fragment shader: ERROR: 0:14: '' : No precision specified for (float) 
    at Function.ǃkUe (main.js:63)
    at async Function.ǃfr (main.js:63)
    at async ǃE.ǃxB.ǃNh.ǃkyA (main.js:63)
    at async n.ǃWAf (main.js:63)
    at async Function.ǃWHM (projectResources.js:1)
    at async Promise.all (/index 0)
    at async t.ǃWJx (projectResources.js:1)
    at async t.ǃuv (projectResources.js:1)
    at async Function.ǃWKe (projectResources.js:1)
    at async Promise.all (/index 0)
(anonymous) @ main.js:63
main.js:63 Uncaught Error: effect shader program not compiled
    at n.ǃMn (main.js:63)
    at a.ǃWev (projectResources.js:1)
    at a.ǃWeR (projectResources.js:1)
    at a.ǃIr (projectResources.js:1)
    at Z.ǃIr (projectResources.js:1)
    at window.ǃvq.ǃns (layoutView.js:1)
    at ǃnM (layoutView.js:1)
main.js:63 Uncaught Error: effect shader program not compiled
    at n.ǃMn (main.js:63)
    at a.ǃWev (projectResources.js:1)
    at a.ǃWeR (projectResources.js:1)
    at a.ǃIr (projectResources.js:1)
    at Z.ǃIr (projectResources.js:1)
    at window.ǃvq.ǃns (layoutView.js:1)
    at ǃnM (layoutView.js:1)
main.js:63 Uncaught Error: effect shader program not compiled
    at n.ǃMn (main.js:63)
    at a.ǃWev (projectResources.js:1)
    at a.ǃWeR (projectResources.js:1)
    at a.ǃIr (projectResources.js:1)
    at Z.ǃIr (projectResources.js:1)
    at window.ǃvq.ǃns (layoutView.js:1)
    at ǃnM (layoutView.js:1)
</details>

**Comment by AshleyScirra** [comment]
In general shader compiler errors are problems with your shader file and not Construct bugs.

In this case it looks like you use a uniform named `color2`, which is actually reserved for internal use by Construct, so it causes a clash. Try renaming it to something else.

**Comment by AshleyScirra** [comment]
I noticed there was also a reserved uniform names list which normally logs an error if you try to do this, but it wasn't up-to-date, so I've updated it for the next release.

**Comment by kokolihapihvi** [comment]
Hey, thank you for your time

Renaming the variables to `stripecolor1` and `stripecolor2` did not fix the issue.
Also, the issue can't be in the shader code as the shader works for me as well as a few other people.

**Comment by AshleyScirra** [comment]
The shader worked fine for me after correcting the uniform. Other than that as I said:

> In general shader compiler errors are problems with your shader file and not Construct bugs.

Differing WebGL support and browser engines could explain why your shader code works for some people but not others.

**Comment by kokolihapihvi** [comment]
After some trial and error we figured out that adding `precision lowp float;` at the top of the shader file fixes the problem for him.

I'm not sure why this one instance requires it, since I have specified a precision for all the variables in the shader.

**Comment by AshleyScirra** [comment]
I've seen similar issues in the past which were bugs in the browser's shader compilers, so if you can narrow it down to a test case you could report it to the browser vendor.
