### ISSUE TITLE
Inconsistent revolute joint behavior since r166

### ISSUE THREAD

**Issue by RorySoh** [Scirra/Construct-3-bugs#3420]
## Problem description

Ever since r166, an established feature of mine making use of revolute joints in the physics behavior has been bugged. It is the same way in the latest stable version.

## Attach a .c3p
[RevoluteJointCursorTest.zip](https://github.com/Scirra/Construct-3-bugs/files/3732983/RevoluteJointCursorTest.zip)

## Steps to reproduce

1. Run the project
2. Move cursor around

## Observed result

Physics joints fly everywhere

## Expected result

Physics joints should hold together like a chain. This worked fine in every version before r166.

## More details
I will be sending in my entire project file to an email!
What it should do
![itsfine](https://user-images.githubusercontent.com/5456478/66897826-6bd62600-f02a-11e9-9085-24040ae345b8.gif)
![ShuYM1](https://user-images.githubusercontent.com/5456478/66897923-a17b0f00-f02a-11e9-9020-346b97296c2c.gif)
What it is doing:
![cursorthing](https://user-images.githubusercontent.com/5456478/66897935-a9d34a00-f02a-11e9-9b9e-efcf782e0cc0.gif)

**Affected browsers/platforms:** 

**First affected release:** 
r166

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Your project works identically for me in r164.3, r165 and r166. So there does not appear to have been a recent change in Construct that affects this. People commonly mis-attribute changes in their own project to C3 updates - I can only assume this is the case here.

I'd add the project uses a third-party addon (advancedLog). The guidelines require that third-party addons be removed from bug reports to eliminate them as a possible cause of the problem. Further the project has about a dozen layers and several dozen object types - the simpler you can make the project, the better. Ideally you would be able to create a new empty project and demonstrate the object with just a couple objects and events. However from this report there does not appear to be any evidence anything actually changed in r166, so I'm afraid there's nothing to investigate here.

**Comment by AshleyScirra** [comment]
Oh, I just figured it out completely by accident. You initialise the physics behavior in 'On load complete' (as in after loading a savegame) rather than 'On start of layout'. In this example that event never runs, so you never set the physics settings that include increasing the precision of the simulation, which is necessary for the joints to behave correctly. If you change it back to 'On start of layout' it works like you want it to.

So yes, it's a mistake in your project and not an issue with Construct.
