### ISSUE TITLE
Construct 3 App - Inconsistent Opening

### ISSUE THREAD

**Issue by Everade** [Scirra/Construct-3-bugs#3421]
## Problem description
Depending on how i start the Construct 3 App, i somehow end up in a different Version of Construct 3. Even though there's only one app installed.
It's not just a visual issue but related to save options as well.

## Steps to reproduce
1. Install Construct 3 as Chrome App
2. Start Construct 3 via Desktop icon -> ("C:\Program Files (x86)\Google\Chrome\Application")
3. Have a .c3p test file on your desktop and start it directly by double click
4. Make sure the settings are identical on both apps (experimental features and so on)

You now have 2 different Construct 3 running with some very specific differences noted below.

## Observed result
**Started via Construct 3 Chrome App**
![OpenedApp](https://user-images.githubusercontent.com/12261601/67036276-9b189000-f11b-11e9-89f8-6c4809ee48b5.png)
- Does NOT offer local saving, instead it's basically a Website Construct 3 with no actual benefits whatsoever.
- Top Bar is shown black

**Started via .c3p project file**
![OpenedFile](https://user-images.githubusercontent.com/12261601/67036342-ba172200-f11b-11e9-8917-2ff103d6443f.png)
- Offers local saving options
- Top Bar is shown white
- Shows Exit option at the bottom of the menu
- Will never open within the initialy started App, but in this own version instead. If you open another .c3p, it will open within this same instance just as expected.

## Expected result
I expect that there shouldn't be any differences between starting the App or by opening a project file directly.
Was very confused when i realised that the local saving option wasn't always available.
Now i know the reason.

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
Tested with r171.2

**Comment by AshleyScirra** [comment]
You also have the desktop build installed, which is what you are getting in the second picture.
