### ISSUE TITLE
When I export a file in HTML using C3runtime, publish in a site, it dosen't work in any browser

### ISSUE THREAD

**Issue by reinaldo-cpt** [Scirra/Construct-3-bugs#3422]
## Problem description

When I export a file in HTML using C3 Runtime, publish in a site, it doesn't work in any browser

## Attach a .c3p
[PhysicsC3.zip](https://

This facility didn't permit attach *.c3p files

![shared-0-sheet0](https://user-images.githubusercontent.com/56726503/67096219-04d18200-f18e-11e9-88f6-5fc0b2aa04a2.png)

github.com/Scirra/Construct-3-bugs/files/3743946/PhysicsC3.zip)

## Steps to reproduce

1.Insert an sprite with Physics behavior
2.Export in HTML5 <F6>
3.publish the folder with index.html in a site
4.when you browse via web the project it dosen't work

## Observed result
Nothing happens

## More details

**Affected browsers/platforms:** 
all browsers

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
I tried serving your project locally and experienced no issues. This is likely a configuration problem with your host, check the browser log for any messages. I expect they are serving the incorrect mimetype for WASM files.

For future reference to upload c3p files either change the extension to .zip or place the c3p in a zip file.

**Comment by AshleyScirra** [comment]
Also if a project fails to load on your server, try pressing F12 and look in the browser console for errors. For example some files may be returning 404 not found and that would be why it's not loading.

**Comment by AshleyScirra** [comment]
Since this is a likely issue with the particular server in question and is a common kind of mistake, it seems unlikely to really be a bug in Construct, so closing. Please post more details about the particular problem as noted if you still think this is a problem with Construct and not with your web server.

**Comment by AshleyScirra** [comment]
The most likely problem is the server doesn't have a MIME type for WebAssembly files so is returning 404 not found for that file. See this manual entry: https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/mime-types

**Comment by reinaldo-cpt** [comment]
It works, thank you
