### ISSUE TITLE
Tweening a platform vertically causes issues with Platform behavior.

### ISSUE THREAD

**Issue by TommyOliverSays** [Scirra/Construct-3-bugs#3423]
## Vertical moving platforms cause objects with Platform behavior to toggle into a jumping state

1. Create an object with a Platform behavior
2. Create a Solid or Jump Thru platform.
3. Jump on it.

## Observed result

<Platform object stays or enters the jump/air state while the platform moves.>

## Expected result

<Platform object would be treated as on floor, like with any other method of moving a platform.>

**Comment by dop2000** [comment]
Small project demonstrating the issue:
https://www.dropbox.com/s/ayri8cqeglg79ek/TweenPlatformBug.c3p?dl=0

**Comment by DiegoScirra** [comment]
@dop2000 

Thanks! That is really helpful!

**Comment by DiegoScirra** [comment]
Fixed on the next beta.
