### ISSUE TITLE
Mistakes in English text

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#3425]
While translating I found a few mistakes/typos in English text:

_text.behaviors.moveto.actions.move-to-position.params.x.desc
"The X co-ordinate to find a path to."
text.behaviors.moveto.actions.move-to-position.params.y.desc
"The Y co-ordinate to find a path to."_

These were probably copied from Pathfinding. Should be "...to move to."

_text.plugins.drawingcanvas.actions.outline-ellipse.description
text.plugins.drawingcanvas.actions.outline-ellipse.params.color.desc 
text.plugins.drawingcanvas.actions.outline-rect.params.color.desc_

These all read "Fill with color" or "Color to fill"
Should be "Outline..."

_text.plugins.cordovaiap.expressions.product-price.description
"Return the formatted price of a produce from its ID."_

Shoudl be "product"

Also, could you please tell where text.model.expression.types.*  strings are used? For example:
_text.model.expression.types.call-function-expression-ref 
"function expression reference"_
I can't find this text anywhere in the program.

**Comment by AshleyScirra** [comment]
Thanks, fixed these in the code and will update POEditor soon.

> Also, could you please tell where text.model.expression.types.* strings are used?

IIRC these are only used in error reporting for invalid expressions, e.g. `Sprite + 1`.
