### ISSUE TITLE
[r30] No scrollbar for image point panel

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#343]
## Problem description

The image points panel in the image editor does not have a scroll bar so it's impossible to see more than 21 or so on a 1920x1080 resolution.

## Attach a .c3p

[testqwr.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1025546/testqwr.c3p.zip)

![image](https://cloud.githubusercontent.com/assets/7268697/26404263/e9cd2650-4099-11e7-8ea8-2eefb1b40560.png)

## Steps to reproduce

1. Create a project and a sprite
2. Add a lot of image points until they go off screen

## Observed result

A scroll bar does not appear to allow scrolling, nor does it scroll when going down with the arrow in the list.

## Expected result

Scroll bar would magically appear making life easier.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r30

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 172 mb (1.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in r31. You can check it out now! It's already live.

**Comment by JeFawk** [comment]
Any possibility to allow F2 to rename the Image Points instead of having the right click -> rename ? :)

**Comment by JeFawk** [comment]
Is this normal though? To have it hidden if the panel < of a certain width?

![hidden](https://cloud.githubusercontent.com/assets/7268697/26413584/1d37915e-40b5-11e7-8323-01b1c711aa8e.gif)

**Comment by JeFawk** [comment]
Or this 
![scrollbarbug](https://cloud.githubusercontent.com/assets/7268697/26449272/fa2108a8-4159-11e7-92c7-6dd7b18e742e.gif)
