### ISSUE TITLE
Update function parameter styles for light/dark themes

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3430]
## Problem description

The function parameters and inner scripts (the ones that exist inside actions) are totally out of the style pattern of the dark theme.

## Attach a .c3p

n/a

## Steps to reproduce

(for function params)
1. Open any project
2. Build a function
3. Add parameters to this function
4. Observe the colors

(for inner scripts)
1. Open any project
2. Use "add script" to any action in any event sheet
3. Observe the colors

## Observed result

mismatch of styles
![000](https://user-images.githubusercontent.com/34659544/67225512-c7792880-f409-11e9-84e1-77f71001ab08.png)
![002](https://user-images.githubusercontent.com/34659544/67225513-c7792880-f409-11e9-9129-3fdcd1fb74b9.png)

## Expected result

a same style direction
![001](https://user-images.githubusercontent.com/34659544/67225534-cfd16380-f409-11e9-91e0-dc7a473140c4.png)
![003](https://user-images.githubusercontent.com/34659544/67225537-cfd16380-f409-11e9-9468-c73d395e3a38.png)

## More details

**Affected browsers/platforms:** 

Chrome, maybe others

**First affected release:** 

many moons ago

## System details

<details><summary>View details</summary>
there was no crash, everything is working fine
</details>

**Comment by AshleyScirra** [comment]
Script blocks are a separate issue so split off in to its own issue at #3446. This issue will be treated as only referring to function parameters.

As a quick fix I've simply applied the event variable styles to function parameters, but our designer may want to revisit this, so assigning to him for review.

**Comment by AshleyScirra** [comment]
Actually function parameters are already covered by #2863, so closing this issue.
