### ISSUE TITLE
Color Selected Bug

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#3432]
#2630  Problem description

When I pick a color and leave the image editor and come back, the RGB values are slightly off when I come back from what I had selected.

## Attach a .c3p

[https://drive.google.com/open?id=1k5ZPf6PcpNegGG6Yol117v4p6K4Ex0Gz](https://drive.google.com/open?id=1k5ZPf6PcpNegGG6Yol117v4p6K4Ex0Gz)

## Steps to reproduce

1. Open the object I provided and hold CTRL and click the color in the object.
2. Close the image editor.
3. Reopen the object in the image editor.

## Observed result

The RGB values of the color selected are slightly off.

## Expected result

The color selected I'd assume should not be changed as was true in C2 and C3 up until a certain build.

## More details
I didn't report this for a while because I assumed someone else would catch it and report it long before now, but I guess not. This makes doing colors for retro style games very annoying because if I close the image editor and come back, if I forget to fix the skewed RBG values, the color I had selected will be off and screw up everything like fake palette cycling effects.

**Affected browsers/platforms:** Chrome, NWjs

**First affected release:** Unsure, but reporting for r164.3

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3928.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3928.0 Safari/537.36
C3 release: r164.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 139 gb
Storage usage (approx): 45 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
