### ISSUE TITLE
Open local project folder keeps requesting to view the same files

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#3434]
## Problem description
I'm not sure if this an issue with the API or Construct 3. When loading a local project folder, Chrome keeps requesting to view files, even if you already allowed it.

## Attach a .c3p

Used Glokar Example.

## Steps to reproduce

1. Open Glokar and save as project folder (experimental feature)
2. Close all projects
3. Open the local project folder
4. Allow Chrome to view files (prompt)
5. Close all projects
6. Open the same local project folder again
7. Notice Chrome requesting to view files again

## Observed result
The request to view files prompt keeps appearing despite already allowing the same request. 

## Expected result
Chrome/Construct 3 should remember that I already allowed viewing files inside selected folders, during the current session (until I close the tab).

## More details
**Affected browsers/platforms:** Chrome

**First affected release:** Basically since this got implemented.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.70
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
C3 release: r172 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 95 gb
Storage usage (approx): 618 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
If my understanding of the Chrome permission model is correct I believe it should be possible to hold onto the permission object for the duration of the session. But @AshleyScirra is much more familiar with the API so it might be that there is good reason for not doing this.

Note this is different to remembering permissions across sessions, it's currently not possible to store a file permission in indexedDB so we have no way to persist them into a new session. If I'm reading the bug tracker correctly this is not likely to appear [until Chrome 80](https://bugs.chromium.org/p/chromium/issues/detail?id=955193)

**Comment by AshleyScirra** [comment]
I don't think holding on to permission ourselves is useful because we don't necessarily know that the second folder choice is the same as the first. I think Chrome gives us a second folder handle which needs prompting again, as if it's an entirely different folder.

Permission prompting is handled by the browser so in general we cannot control that. Also it seems minor (one extra click to open), is easily circumvented by the user (just keep the project open), and may well be the intended design (accessing a whole folder of files is a sensitive permission so it ought to ask the user to confirm every time).
