### ISSUE TITLE
Game crash on startup if "test mode" is unchecked in the MobileAdvert object.

### ISSUE THREAD

**Issue by DaveedA13** [Scirra/Construct-3-bugs#3435]
## Problem description

It crashes in TEST FLIGHT on my iPad and on my iPhone, but not when "test mode" is checked.

## Attach a .c3p

**Github won't let me attach my zipped c3p currently.** :( Got the message "Something went really wrong, and we can't process the file" each time)

EDIT: Here is a Google Drive link to the shared files: https://drive.google.com/open?id=1S9auOBw5by5N5UC6pZkPFCIjxdiQs04L

## Steps to reproduce

1. Create a new project
2. Add the MobileAdvert object
3. Fill the properties (3 IDs and privacy policy url)
4. Uncheck the "test mode" on MobileAdvert object.
5. Export it to iOS, then into XCode and test it with TEST FLIGH app.

## Observed result

The game crash on startup, even before showing the 1st layout, but after the "Loader" (I selected the "Percentage text" for "Loader style")

## Expected result

The game should start, and then I could debug if I entered something wrong in the MobileAdvert properties, but I can't debug with conditions like "on configuration failed" or "is configured" since the game crash **on startup**.

## More details
The exact same game load fine with "test mode" checked, and the test ads display correctly.

I really created 2 simple c3p files with just the MobileAdvert to be sure, after 155 builds of my games (lol) that it was just that "checked option" and I get the same crash. I'm really sad that I can't attach them since I would really like you guys to take a look at this bug.

...if it works for you, what could I did wrong? Yesterday I selected custom ads providers in my admob account, wich was **not really explained** in the **manual entry** for the MobileAdvert object.

...but do an error in configuration should really make the **whole game not start at all**...?

Thanks in advance for the help.

No bug in a browser, just in TEST FLIGHT since the **MobileAdvert** works only "**in-app**".

My current C3 version is **r171.3**.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.0416666269302368
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.8 gb
Storage usage (approx): 931 mb (11.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
@DaveedA13 for reference GitHub doesn't like .c3p files because it doesn't recognise the file format. You can work around this by changing the file extension to .zip or putting the c3p into a zip archive. As they do recognise and allow zip files.

After investigation I've found a memory bug, that causes the application to crash when NOT in debug mode. It's quite a weird one, but the reasoning behind it is quite technical and specific to the swift programming language so I won't go into extended explanation. The fix basically involved moving a few variables around.

I've tested and published the fix to the build server. If you could review that the problem is now resolved for you then that would be appreciated.

**Comment by DaveedA13** [comment]
**Many thanks** for the fix, it's **working**!!! :)

Really appreciate it, can't wait to submit **my very first iOS app**! ;)

_Thanks for the info about zip files, I tried it in compressed file format but I still had the error, didn't try just changing the extention of the c3p through... ...but I think it was a temporary bug of github. :/_

**Comment by shortercode** [comment]
@DaveedA13 thanks for confirming, glad to hear it's resolved :)

Ah yeah I did wonder with the error message (  "Something went really wrong[...]" ), I think your probably right that it was a temporary issue with GitHub.
