### ISSUE TITLE
Behavior instance.js functions not being called

### ISSUE THREAD

**Issue by colludium** [Scirra/Construct-3-bugs#3437]
## Problem description

Behavior / editor instance.js functions OnCreate() and OnPropertyChanged() are not called as expected.

[bugBehaviorInstanceCalls.zip](https://github.com/Scirra/Construct-3-bugs/files/3765576/bugBehaviorInstanceCalls.zip)

This is a slightly modified version of the behavior .c3addon template v1.3, with a .c3p test project that uses the behavior.

## Steps to reproduce

1. Install behavior from zip, open c3p project, observe console.
2. Edit "Test Property" in behavior object properties.

## Observed result

There are no console logs or errors for OnCreate() or OnPropertyChanged().

## Expected result

The contents of OnCreate() and OnPropertyChanged() should throw errors and console logs.

## More details

None.

**Affected browsers/platforms:** Chrome.

**First affected release:** r172, not tried earlier.

## System details

N/A.

**Comment by AshleyScirra** [comment]
Ah, well it turns out OnPropertyChanged and SetPropertyValue were simply not implemented for behaviors. It's not surprising that the behavior interfaces aren't actually documented either... implemented these for the next release, now the following code works as a limit:

```js
OnPropertyChanged(id, value)
{
	if (value > 100)
		this.GetBehaviorInstance().SetPropertyValue(id, 100);
}
```

**Comment by colludium** [comment]
Thanks, @AshleyScirra
