### ISSUE TITLE
GooglePlay Plugin not loading Avatar

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#3438]
## Problem description

I used Google Play Avatar but it did not work in exported and signed android game.

## Attach a .c3p

[GooglePlayBugs.zip](https://github.com/Scirra/Construct-3-bugs/files/3766322/GooglePlayBugs.zip)

## Steps to reproduce

1. add Google Play
2. Use Avatar from PlayerData
3. export as signed apk for play store

## Observed result

No Avatar loaded. I used anonymous and none as origin.

## More details

I don't know if you have a test app in play store to test this. I can give you access to my internal alpha of my game if it helps.
Leaderboards and unlocking achievement worked fine in it. 

**Affected browsers/platforms:** 
Chrome / Android APK

**First affected release:** 
171.2 / 171.3
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.70
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 856 mb (5.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 615 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I have a feeling that the avatar URI is an internal device URI that the webview cannot access, we probably need to read it and convert it to a data URI before passing it back to the webview.

I probably have a test project already that I can use for this, I will investigate and confirm what the situation is.

**Comment by shortercode** [comment]
I've confirmed that URI that Google Play returns is unreadable in the WebView. In fact it's unreadable in the main application code as well, you're forced to use a special manager that exists only to load images from Google Play services into an abstract representation of the image. I had get a little creative to convert this into something I could actually read the pixel data from. 

As you might be able to tell this patch turned into a little adventure to say the least. But I eventually managed to convert it into a data URL. I've just published a revision to the cordova plugin, and will update the build service shortly. This patch will not required a C3 release.

**Comment by shortercode** [comment]
Revision should now be live on the build service. Let me know if you have any other issues.

**Comment by TheBl4ckSh33p** [comment]
Thanks! Did you change anything else? I'm constantly getting "undefined" as error message (on Google Play error: alert popup with error message). Seems im Auto signed in but I can't show built in leaderboards or achievements dialog. Just says undefined. Using 171.3 stable.

**Comment by shortercode** [comment]
Mmm I pushed a change yesterday which was supposed to resolve an issue where we would crash if the sign in state and our expected state went out of sync. I will take a look.
