### ISSUE TITLE
Effects weird bug

### ISSUE THREAD

**Issue by Bigbeto123** [Scirra/Construct-3-bugs#3439]
A non-transparent layer using two effects at the same time while having less than 100% opacity gets completely buggy. It literally goes out of the layout when scrolling in the editor and doesn't shows whenever playtesting it.
Obs: This also applies to particles, as tested by me in multiple occasions. They tend to get completely crazy, stretch out absurdly and such.
Please take a good at effects in general when layered.

https://drive.google.com/drive/u/0/folders/1QVUkvaara73-0Va3ViqcQZyzN0emKObV

Create a non transparent layer. Set its opacity to anything in between 100% and 0%. Apply two effects to it. Done.... May have unexpected results with some other specific effects, but it always bugs out with both Pixellate and Noise.

1.Explained
2.In the section above
3.Also, this section in the template is kinda redundant. Please allow people to attach actual cp3 files in the issue instead of having to copy and paste external links.

The layer/particle goes completely crazy, stretching out to absurd lenghts, moving in high speeds when scrolling in the editor and such.

Should just work out normally, like it does with a layer with 100% opacity.

## More details

Chrome, Windows 10 

Since AT LEAST one stable release ago... And a good handful of betas ago. 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 21 gb
Storage usage (approx): 1.1 gb (5.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is another case of #2121. Unfortunately that has been slow going due to the extreme complexity of this part of Construct.

**Comment by Bigbeto123** [comment]
So... Any workarounds for this?
(specially about particles)
