### ISSUE TITLE
«Edit» button does not have a translation when using Light/Dark themes

### ISSUE THREAD

**Issue by allyoe3** [Scirra/Construct-3-bugs#3440]
## Problem description

![ButtonTranslationC3](https://user-images.githubusercontent.com/56956534/67589217-24663d00-f782-11e9-8b7c-6e44565e481c.png)

«Edit» button (in the properties bar) will always display english text even though other language is selected in settings. Occurs only when the Light/Dark theme is selected.

## Steps to reproduce

1. Select Light or Dark theme in settings
2. Open/create new project
3. Open the properties bar

## Observed result

«Edit» button displays english text. 

## Expected result

«Edit» button should display translated text.

## More details

Default theme displays correct translation for the «Edit» button.

**Comment by AshleyScirra** [comment]
Ah, it turns out our designer who made the light/dark themes included hard-coded English text in the theme CSS, which can't be reached by the translation system. These cases will need to be removed, but doing so may alter the design of the theme, so I think our designer will need to revisit this.

**Comment by XHXIAIEIN** [comment]
This issue is still not resolved :(

**Comment by AshleyScirra** [comment]
Reverted the style changes that are not translatable for the next beta.
