### ISSUE TITLE
resize image canvas - align center makes the image blurry

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3442]
## Problem description

When you change canvas size in Animations Editor and select Image: Align Center option, it makes the image blurry 

## Steps to reproduce

1. Open Image editor.
2. Select Image: Align Center
3. Change width and height of the canvas.

## Expected result

It should just change the canvas size.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
