### ISSUE TITLE
Solid bounce angle bug

### ISSUE THREAD

**Issue by colludium** [Scirra/Construct-3-bugs#3443]
## Problem description

Bullets with bounce off solid enabled bounce incorrectly at sprite corner.

[solid bounce bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3774889/solid.bounce.bug.zip)

This can be seen in this image - sprites with bullet behavior are spawned every 0.5 sec and move right, then bounce on collision with the corner of the angled solid sprite. The bounce angle is exactly the reverse of the fall angle, so the bullets bounce and then reverse direction, moving to the left (in this example) instead of bouncing naturally to the right.

![bullet bounce bug](https://user-images.githubusercontent.com/2897225/67620549-02130480-f800-11e9-8c09-029aac27c68c.png)

## Steps to reproduce

Run the example and observe the bullet bounce response.

## Observed result

Bullets hit the corner and bounce at the wrong angle (the exact reverse of their fall angle).

## Expected result

Bullets should bounce at a correct reflection angle for the surface that was collided with. 

## More details

None.

**Affected browsers/platforms:** N/A

**First affected release:** r172

## System details

N/A

**Comment by AshleyScirra** [comment]
The example is misleading because it uses a round image for the sprite, but a square collision box. So the collision results won't match the appearance of the object.

If you 'guess collision poly' to get a roughly round shape, then move the solid so it collides at the corner again, it seems to work correctly:
![fixed-collision-mask](https://user-images.githubusercontent.com/768723/67676361-36f69700-f979-11e9-9671-08d7d2f4d245.png)

**Comment by colludium** [comment]
@AshleyScirra - err - did you even read this bug report? Should I resubmit with a square sprite image, as if that makes any difference to the reverse-direction of the bounce?

**Comment by colludium** [comment]
The point being that, for sprites that have a square collision shape, this is a real bug...

**Comment by AshleyScirra** [comment]
If you file a collision issue with a round image using a square collision mask, it looks exactly like you just made a mistake with the collision mask. People routinely file issues that are just mistakes, and so this issue looks exactly like that. It's important to get details like this right in bug reports to avoid making a confusing or misleading example.

With poly-poly collisions it has to estimate the surface normal for bounces, and the estimation isn't perfect, especially near corners. If you move it to collide nearer the middle you'll see it works fine. It's just an artefact of the bounce angle calculation.
