### ISSUE TITLE
Json Object conditions don't have "Is boolean set" as an option

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3444]
## Problem description

Below are the options available.

![image](https://user-images.githubusercontent.com/34659544/67623154-8cf00100-f7f8-11e9-8025-03ab108b012f.png)

I believe there should be such a thing because otherwise we end up having expressions like below.

![image](https://user-images.githubusercontent.com/34659544/67623163-b7da5500-f7f8-11e9-9fd8-f8d917d58523.png)

## Attach a .c3p

Every file should present it.

## Steps to reproduce

1. Open any file.
2. Add a Json Object.
3. Set a common boolean to it.
4. Use it as a condition.

## Observed result

There is no "Is boolean set" option.

## Expected result

I believe there should be since it would follow C3's pattern, also it would make it more legible.

## More details

**Affected browsers/platforms:** Chrome
**First affected release:** found on a 172, but maybe always?

## System details

There were no crashes.

**Comment by shortercode** [comment]
Seems quite reasonable, I've added it for the next beta.
