### ISSUE TITLE
Functions - Return Type Bug

### ISSUE THREAD

**Issue by Everade** [Scirra/Construct-3-bugs#3445]
## Problem description
_Functions (Built-In)_
If you don't set the proper return type **prior setting a return value comparison**, the system will no longer allow you to change it. Even though the function is clearly _unfunctional._
Instead of automatically setting it to either number, string or any, it may return either none or the wrong type **and renders the entire function useles.**

**This means that in this attached example, the second Function called ReturnString, is never actualy being called!**

**This forces you to:**
- delete all functions calls again (because you can't change type when it's already in use)
- then set the type to the proper setting
- then recreate everything you've just deleted

## Attach a .c3p
**This doesn't work:**
[BrokenFunctions.zip](https://github.com/Scirra/Construct-3-bugs/files/3775228/BrokenFunctions.zip)

**This works:**
[WorkingFunctions.zip](https://github.com/Scirra/Construct-3-bugs/files/3775235/WorkingFunctions.zip)

Both are absolutely identical, the only difference being the second function returnType.
Please note that in both cases: We are not allowed to change the Return Type anymore.

## Steps to reproduce

1. Hit Enter to call Functions.Call
2. **ReturnString Function is never called**

Reason: ReturnString function is set to String return type which can no longer be modified.

## Observed result
If you set a breakpoint, you can see that the second function "ReturnString" is never called, or it doesn't work properly due the wrong return type.

## Expected result
ReturnString function should in any case be called, because we forward the required parameter, doesn't matter if the return type is wrong.

**Possible Solutions:**
Either set the return type automatically by checking the return values being set (number, string, any or none). I think that's the best solution.

Or don't block the return type from being changed.

## More details
![image](https://user-images.githubusercontent.com/12261601/67625249-eb8a9e80-f83b-11e9-913a-f6406f0fbef0.png)

**Comment by Everade** [comment]
**Also:**
Why can't we call a function with an action as soon as it returns something?
This is extremely limiting and i can't see a reason why this should be blocked in the first place.

There are a lot of cases where i would want to call a function and maybe use an if check at the same time **but i simply can't**. It worked just fine with the old function plugin.


While the built-in functions comes with great improvements, it comes with quite big limitations along the way.

My guess is that both, my initial report and this aren't considered a bug.
But i wonder why you would limit it in the first place...

And if you don't plan to change this, could you please enlight me on how to use functions in such particular cases? Your video and manual doesn't cover it, and I don't want to create 2 identical functions just to have 1 of them return a state while the other doesn't.

**Comment by AshleyScirra** [comment]
This is by design. Once the function has references, changing the return type could make expressions invalid. For example if the return type is passed to an action that requires a string and using a number is an error, then changing the function return type to a number will cause an error in that action. Therefore changing the return type is not allowed. You can still set the return type if there are no references to the function yet, since the problem won't happen.

Unfortunately Construct's architecture does not allow for enforcing the return type in the 'Set return value' action, so you are allowed to enter a number for a function returning a string. However this will be ignored and the function will continue to return the default empty string.

Note that in your example where you say *ReturnString Function is never called*, in fact the function is called. It is the comparison that fails, since an empty string does not equal the number 1. Add an action to the function itself and you'll see it is run.

**Comment by Everade** [comment]
@AshleyScirra 
Thanks for the answer.
Hope you can read this through too.

**1.)**
You're right, it actualy runs through the function.
Then that means that your debug system does not truly show every step.

How shall i debug something properly if i don't see every step ?
---> **Putting up a breakpoint within the second function never triggers.** <---

Putting up a breakpoint in the first function stops, but when i then want to follow every step then it skips every step within the second function.

-------------------------------------------

**2.)**
You say it's by design.
Not trying to offend you, but it sucks.
Let me show you this from the perspective of an actual user of your product:

Here's an exagarated example:
If someone creates a function, then calls it >100 times throughout his entire project.
Then realises that it isn't working because hey.... the return type was initialy set wrong.

Guess what?
Just delete your entire project and start all over, that's most likely faster.
Because you can't change it anymore unless you delete all calls!

That's neither user friendly, nor beginner friendly, nor a good design.

I personaly have this problem right now, because i don't test everything every 2 minutes.
Who would expect that the engine itself punishes you so hard.
Once you've got some really complex functions and code all over the place, this is getting extremely tidious to debug.
1. You have to find the hidden culprit (or multiple ones)
2. You must delete tons of calls
3. Rewrite it from scratch and find all the right spots

Please improve this....

--------------------------------------

**3.)**
Why can't we call a function with an action as soon as it returns something?

Right now the only way to still call such a function is by forcing an IF comparison.
Why not by action?
