### ISSUE TITLE
CalculateBounceAngle() bug

### ISSUE THREAD

**Issue by colludium** [Scirra/Construct-3-bugs#3447]
## Problem description

Certain collision shapes cause CalculateBounceAngle() to provide incorrect solid bounce angle values to the behaviors that use solid bounce. 

Where there is a small overlap at collision (like two corners overlapping, as in this example) the returned bounce angle is the reciprocal of the angle of travel, instead of the reflection angle.

[solid bounce bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3778788/solid.bounce.bug.zip)

## Steps to reproduce

Run the .c3p and you'll see two streams of bullets, red and blue. The blue bullets collide at the corner of the solid and bounce incorrectly. The red are spawned a few pixels to the left and bounce with a proper reflection angle.

## Observed result

![bullet bounce bug](https://user-images.githubusercontent.com/2897225/67681492-58f61680-f985-11e9-8ca7-7eed6170ce06.png)

## Expected result

The CalculateBounceAngle algorithm, as used by bullet etc, should provide a correct reflection angle even when there is a small overlap at the time of collision.

## More details

None.

**Affected browsers/platforms:** N/A

**First affected release:** r172

## System details

N/A

**Comment by AshleyScirra** [comment]
We have to rely on an imperfect estimation as described in #3443. The example project is just carefully set up to expose the imperfection.
