### ISSUE TITLE
Cant launch version 172, 173

### ISSUE THREAD

**Issue by Thersippos** [Scirra/Construct-3-bugs#3449]
Can't launch version 172, 173 at all

## Attach a .c3p

It has nothing to do with the project files. When I launch those versions, it crashes

## Observed result

It shows the error message when launching the version, but it doesnt include any information (its blank, so copy information doesnt work)

I have copied the chrome browser log to see if you can understand something from this:

main.js:63 Uncaught (in promise) Error: [Effects] Effect 'lineargradient' parameter 'color2' specifices a uniform 'color2', but this name is reserved for internal use by Construct. Please use a different uniform name.
    at n.ǃzPw (main.js:63)
    at a.ǃzIh (main.js:63)
    at t.ǃzPw (main.js:63)
    at window.ǃzy_.ǃzsI (main.js:210)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.120
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 19 gb
Storage usage (approx): 1 gb (5.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's a problem with the third-party 'lineargradient' effect which is using a name reserved by Construct. In theory it should never have done this and was always broken... but I renamed the internal name instead so third-party effects can continue using it.
