### ISSUE TITLE
Problem after the last update ?

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#345]
## Problem description

Don't know if it's a problem by me but the Gamepad does'nt work since I update to release r31...

**Comment by Picoti** [comment]
One time the gamepad work !
Dont understand.... My gamepad work fine on all my games.
With the new release of construct 3, it work about 1 times out of 10...

**Comment by Picoti** [comment]
Now with more preview I've made, I can say about 1 times out of 15

**Comment by AshleyScirra** [comment]
Sounds like this Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=711252

Please star the issue to help raise awareness. You should be able to work around it by changing the preview mode.
