### ISSUE TITLE
Construct 3 crashes when trying to use picker in timeline bar

### ISSUE THREAD

**Issue by allyoe3** [Scirra/Construct-3-bugs#3450]
## Problem description

Construct 3 will crash unexpectedly when using timeline bar features. Usually happens when trying to add a new property to the current track, but also can occur randomly.

## Attach a .c3p

[Timeline.zip](https://github.com/Scirra/Construct-3-bugs/files/3782592/Timeline.zip)

## Steps to reproduce

1. Open the timeline
2. Try to add new instances. If Construct 3 doesn't crashes, go to the third step.
3. Add a new timeline property
4. Instead of selecting property from the list try to use the search box

## Observed result

![timelinebug](https://user-images.githubusercontent.com/56956534/67752445-9336e500-fa65-11e9-9e28-79645c5c0c18.png)

## Expected result

Instance picker should be displayed/search box should work normally.

## More details

**Affected browsers/platforms:**
Chrome, Firefox, Construct 3 beta for Windows 10

**First affected release:** 171 (approximately)

## System details

**Adding new property**
<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r171-3/components/bars/timelineBar/timelineBar.js, line 1, col 168488
Message: Uncaught TypeError: e.ǃPgU is not a function
Stack: TypeError: e.ǃPgU is not a function at ǃp.ǃYz.ǃef.ǃPgz.ǃpHk (https://editor.construct.net/r171-3/components/bars/timelineBar/timelineBar.js:1:168488) at ǃpiV (https://editor.construct.net/r171-3/components/bars/timelineBar/timelineBar.js:1:166428) at ǃp.ǃYz.ǃef.ǃZGR.ǃYiU (https://editor.construct.net/r171-3/main.js:2:481746) at ǃp.ǃxi.ǃZYo (https://editor.construct.net/r171-3/main.js:2:474841) at ǃp.ǃxi.ǃpSQ (https://editor.construct.net/r171-3/main.js:2:209258) at ǃp.ǃxi.ǃxW (https://editor.construct.net/r171-3/main.js:2:209136) at ǃp.ǃYz.ǃef.ǃZGR.ǃpHU (https://editor.construct.net/r171-3/main.js:2:481643) at ǃp.ǃYz.ǃef.ǃPgz.ǃjHK (https://editor.construct.net/r171-3/components/bars/timelineBar/timelineBar.js:1:167884) at HTMLInputElement. (https://editor.construct.net/r171-3/components/bars/timelineBar/timelineBar.js:1:166400)
Construct 3 version: r171.3
URL: https://editor.construct.net/
Date: Tue Oct 29 2019 15:41:13 GMT+0700 (Индокитай)
Uptime: 99.8 s

Platform information
Browser: Chrome
Browser version: 75.0.3900.0
Browser engine: Chromium
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3900.0 Iron Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Adding new instance (less common)**
<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: dialog name 'PickTimelineInstances' not found @ Error: dialog name 'PickTimelineInstances' not found at Function.ǃpdu (https://editor.construct.net/r171-3/main.js:2:284962) at Function.ǃYq (https://editor.construct.net/r171-3/main.js:2:292720) at P.ǃYSR (https://editor.construct.net/r171-3/main.js:210:58454)
Stack: Error: dialog name 'PickTimelineInstances' not found at Function.ǃpdu (https://editor.construct.net/r171-3/main.js:2:284962) at Function.ǃYq (https://editor.construct.net/r171-3/main.js:2:292720) at P.ǃYSR (https://editor.construct.net/r171-3/main.js:210:58454)
Construct 3 version: r171.3
URL: https://editor.construct.net/
Date: Tue Oct 29 2019 15:46:01 GMT+0700 (Индокитай)
Uptime: 56.2 s

Platform information
Browser: Chrome
Browser version: 75.0.3900.0
Browser engine: Chromium
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3900.0 Iron Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by allyoe3** [comment]
Sometimes Construct 3 can crash when you are adding new keyframes to the timeline. The following error will be displayed:

<details><summary>Type: unhandled exception</summary>
Type: unhandled exception
File: https://editor.construct.net/r171-3/components/bars/timelineBar/timelineBar.js, line 1, col 48091
Message: ReferenceError: event is not defined
Stack: e.ǃPRr@https://editor.construct.net/r171-3/components/bars/timelineBar/timelineBar.js:1:48091 e.ǃPZr/<@https://editor.construct.net/r171-3/components/bars/timelineBar/timelineBar.js:1:46109
Construct 3 version: r171.3
URL: https://editor.construct.net/
Date: Tue Oct 29 2019 17:08:37 GMT+0700
Uptime: 89.3 s
Platform information

Browser: Firefox
Browser version: 56.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.3
C3 release: r171.3 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, EXT_disjoint_timer_query, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, MOZ_WEBGL_lose_context, MOZ_WEBGL_compressed_texture_s3tc
</details>

It also can happen when you are moving keyframes or use other elements of the timeline bar:
<details><summary>Type: unhandled exception</summary>
Error report information

Type: unhandled exception
File: https://editor.construct.net/r171-3/components/bars/timelineBar/timelineBar.js, line 1, col 85307
Message: ReferenceError: event is not defined
Stack: ǃPi$@https://editor.construct.net/r171-3/components/bars/timelineBar/timelineBar.js:1:85307 window.ǃnM.ǃPKZ Construct 3 version: r171.3
URL: https://editor.construct.net/
Date: Tue Oct 29 2019 17:12:21 GMT+0700
Uptime: 205.6 s
Platform information

Browser: Firefox
Browser version: 56.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.3
C3 release: r171.3 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, EXT_disjoint_timer_query, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, MOZ_WEBGL_lose_context, MOZ_WEBGL_compressed_texture_s3tc
</details>

**Comment by DiegoScirra** [comment]
@allyoe3 

What method are you using to add instances?

**Comment by DiegoScirra** [comment]
Fixed all of the crashes mentioned except for the one about adding an instance. The fixes will be available in the next beta.

**Comment by DiegoScirra** [comment]
From looking at the crash reports posted, it looks like all of this problems have already been solved in the latest beta.
