### ISSUE TITLE
"Apply to whole animation" moves point to click at the same time

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#3451]
## Problem description
in the image editor, with the image point tool, doing "apply to whole animation" clicking inside the image editor canvas, moves the image point to the click place.
## Steps to reproduce

1. open image editor
2. select image point tool
3. right click in the image point menu on the origin point, but trying that the click ends in the canvas like the image 
![imagen](https://user-images.githubusercontent.com/6506303/67821006-402b5500-fa9a-11e9-9a5b-bcf3fa7b91f7.png)

## Observed result
the image point is moved

## Expected result
dont move it

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
