### ISSUE TITLE
Revolute joint offset from origin when modifying height/width

### ISSUE THREAD

**Issue by johnsmith27** [Scirra/Construct-3-bugs#3454]
## Problem description
I need to set the width of my object before creating a revolute joint to it to have different lengths (it's based on the distance between 2 objects, which is constantly changing).
However I've found out that when I do that, the object is always moved away from its origin point when creating the joint. 

This was working fine some time ago (like 2 years ago I think..) as it's from an older C2 project, but when imported in C3 all my rope system is now messed up and I can't seem to get it right anymore if I want to set a different length before creating the joint. Is it a bug or is it supposed to work like that ?

## Attach a .c3p

https://www.dropbox.com/s/6tu8z6elb2ggh3t/revolute_height.c3p?dl=0

## Steps to reproduce

Click the "normal" button will show the object being attached without modifying the height which works perfectly fine.

The "height" button however, changes the height of the object before attaching it and shows that the object isn't attached to its origin point anymore.

## Expected result

I expect the object to still being attached to it's origin point, since height/width are also modified from the origin.

## More details

**Affected browsers/platforms:** Chrome/Android

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.70
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 104 gb
Storage usage (approx): 676 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by johnsmith27** [comment]
Maybe, the thing is, the object I need to attach the rope to has different angles as well.

In the example, when I set the Logo angle to random(360) before creating the shield, the shield is offseted again.
But if I had a boolean "pinned" to the shield 
Then when unpinned -> set position to logo.x, logo.y -var_height/2
And on start of layout wait 0.2sec before creating the joint
It kinda works with a very little offset.
If I remove the wait action though, the big offset is back again...which is pretty strange no ?

Here is the modified example:
https://www.dropbox.com/s/k239hmpte1k0zfc/physics-joint-fixed-2.c3p?dl=0

**Comment by AshleyScirra** [comment]
Construct reconciles the physics object and Construct object at the end of a tick, which is why adding a delay works. This is pretty tricky but I think I've got something that works for the next release, by forcing the physics bodies to update just before creating a joint, which seems to get it working providing the origins are centered. Hopefully that helps get this working more easily.
