### ISSUE TITLE
300-400ms Touch to Audio Lag on Android Devices

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#3455]
## Problem description

large 300-400ms touch to audio lag on majority android devices tested.

## Attach a .c3p

**c3p** [Link](https://drive.google.com/open?id=1ReMGWOnP3l8yU0AgqqE-hzCwbVnOHXbs) note I am aware that I am setting frequency every tick this is deliberate as it reflects the behavior of the real app as the frequency can be changed by other events eg like pitch bend however  i get exactly the same results if I change the frequency only once on the button press)

## Steps to reproduce

[hosted test app](https://yamaforce.com/ironpan/open/soundlagtest/)
[debug apk](https://drive.google.com/open?id=1RBg31xg3gHwkdZTHCQcOFtUmzzxkEWRb)

Press Top Button to start sound.
Tap the bottom button to change sound frequency.

## Observed result

observe 300-400ms lag when chaging frequency on majority devices tested.
see video tests  below.
generally apk is more laggy than website by maybe 50ms but still laggy

## Expected result

minimum lag at least somewhere in the 5-50ms range
at least something in this range
[Cubot Power - Android 8](https://drive.google.com/open?id=19TechS7xCVrYKvetwk2cg9rs-KAXRoIz)
this is a cheap Chinese £140 phone, why is it performing better than £800 Samsung devices. Just brute force CPU power?

## More details

**Video Tests**
Note: screen being tapped with nail so you can hear the nail tap then the change in sound to hear the lag.

[Moto G5 - Android 8 = lag](https://drive.google.com/open?id=19PN2R4vuiZfXaBgTjRCO1Dv46_QoFIpZ)

[Moto G4 - Android 7 = lag. ... ](https://drive.google.com/open?id=19dl7DEuRsnqW8eA4lxZwd6ofVVIfJF2J)

[Samsung S7 Android 8 = lag](https://drive.google.com/open?id=1Qj6y2U70y2De4v44TBgaTktPk3yx3Ms5)

[Hawaei P10 Android 8 = lag](https://drive.google.com/open?id=1rVyJFwsn-Bg1hgk1zh6rweRkruqO7zgM)

[Galaxy Tab A Android 8= lag](https://drive.google.com/open?id=19nO9lVGOlpow4ooNF3h2A-rptXjIevt5)

[Galaxy S8 Android 9 = lag](https://drive.google.com/open?id=19l2LjiqPSWfl4g0g_21seXqyM2kQhpon)

## System details

Android various.

</details>

**Comment by Wackytoaster** [comment]
Probably add the thread to, maybe it helps
https://www.construct.net/en/forum/construct-3/general-discussion-7/big-touch-lag-android-148079

On that note, I do not experience any lag in the Samsung Internet Browser (10.1.01.3). According to [wikipedia ](https://en.wikipedia.org/wiki/Samsung_Internet) it should run on Chromium M71

I do experience lag with the regular Chrome browser (78.0.3904.62) (and the apk)

**Comment by AshleyScirra** [comment]
I'm afraid this is a problem with the Android OS or the devices themselves. To avoid splitting the discussion I posted more details in a reply on the forum thread here: https://www.construct.net/en/forum/construct-3/general-discussion-7/big-touch-lag-android-148079/page-2#forumPost991827
