### ISSUE TITLE
Weird boolean instance variable effect

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3456]
## Problem description

When running this code:
![image](https://user-images.githubusercontent.com/34659544/68076262-24bd9400-fd91-11e9-8d01-ea2cbe057b87.png)

I expected to be told what other string than "Story" I would get if it wasn't "Story", but this is what I get:
![image](https://user-images.githubusercontent.com/34659544/68076276-559dc900-fd91-11e9-825a-db427b5bc59e.png)

But when I thought "well, this is my fault", this worked perfectly:
![image](https://user-images.githubusercontent.com/34659544/68076294-9695dd80-fd91-11e9-910a-18298e890dc2.png)

They are both the exact same bit, at exactly the same place in the code asking if "Blackout.Context_Now" is equal to "Story", but through the instance variable block it is broken, while in the "Compare two values" block, it works perfectly as expected.

## Attach a .c3p

Now I 100% believe this is a bug in the boolean instance variable process, but I could only disclose the file in which it was found through a pm.

## Steps to reproduce

I can't reproduce myself.

Even in the same event sheet, the boolean instance variable block works perfectly everywhere except for this line (again, in the same exact place as the "Compare two values" that does work).

## Observed result

I ask what is the string "Blackout.Context_Now" if not "Story" and I get "Story" (which should have been impossible).

## Expected result

I would expect it to work like every other block, because it works everywhere else, including the same event sheet and because another redundant code, "Compare two values", works.

## More details

**Affected browsers/platforms:** Chrome, maybe others
**First affected release:** 173

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.120
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
C3 release: r173 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 356 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
If you cannot reproduce this in a new project, it is a strong signal this is just a mistake in your events. I cannot find any project for this report either publicly or privately so there is nothing I can do to investigate. Please see the bug report guidelines which are intended to avoid this happening.

Note that it is incorrect to assume a system comparison works the same as an instance variable comparison. The former skips picking, using an arbitrary instance, while the latter respects picking, checking which instances meet the condition and running actions on only those that matched the condition.

**Comment by dupuqub** [comment]
I can totally provide the file, just didnt know where to send it to. If you please let me know the best way to do it, that would be nice.

Also I did a little more testing and found out this weird thing, hope youll reconsider this issue once you have the file in your hands.

![image](https://user-images.githubusercontent.com/34659544/68179512-f09fca00-ff6e-11e9-8a43-7a21ad9525c2.png)

I don't believe this should happen at all and it is happening.

![image](https://user-images.githubusercontent.com/34659544/68179575-2b096700-ff6f-11e9-8081-52b3576255d9.png)

By the working examples I think the weird point is very clear, also I really don't understand whats going on here, I would really appreciate any more light on that. I'm pretty aware that maybe I'm doing something really stupid. Cheers.

**Comment by dupuqub** [comment]
Also, as I hope youll see, there is only 1 instance of the object "Blackout", so maybe picking an arbitrary instance wouldn't be the issue, correct?
