### ISSUE TITLE
'On key pressed' event won't stop firefox to go back when the backspace key is pressed

### ISSUE THREAD

**Issue by Telecs** [Scirra/Construct-3-bugs#3459]
## Problem description

Hi everybody,

I tried disabling the backspace function when I open my game in firefox and even when I'm using the empty "on key press" event, the browser moves 1 website back whan I press backspace. This method is initially described in [the documentation](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/keyboard) and I tried to follow it, without success.

## Attach a .c3p

Here is [the .c3p](https://www.dropbox.com/s/1ao0mgb3inc7c5b/test%20backspace.c3p?dl=0)

## Steps to reproduce

1. Go to [autofocusgames.ch/test](https://autofocusgames.ch/test/) where I hosted the html version of the project.
2. Try to press backspace.

## Observed result

When I tested it with Firefox, the browser moved 1 website back. Nothing happened when I tested it with Chrome (since it doesn't seem to have the same shortcut.)

## Expected result

When I was in firefox, I expected nothing to happen.

## More details

**Affected browsers/platforms:** 

Firefox, not Chrome.

**First affected release:** 

I don't know, I never used this before.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 45 gb
Storage usage (approx): 528 mb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon(TM) RX 460 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The documentation is actually out of date - as of the C3 runtime, due to its new architecture to support running in a worker, it's no longer possible for events to affect whether the browser default keyboard shortcuts work. I've removed the part of the documentation that says that, of course it would have caused confusion.

I've fixed this for the next release by specifically blocking the backspace key in the runtime itself. It's possible there are other browser keyboard shortcuts that we might want to disable by default though, so let me know if you find any more.

**Comment by Telecs** [comment]
Hi Ashley,

Thanks a lot for your follow-up and thank you for the fix to come! I feel that perhaps the spacebar should also be blocked (that makes the webpage scroll down, at least in firefox and Chrome). Other than that, I didn't identify any shortcut that might be troublesome in the context of a game.

Best,
Telecs

**Comment by AshleyScirra** [comment]
AFAIK Construct games never use scrollable pages. It's possible they are iframed in a scrollable page, but then the parent page needs to block spacebar from scrolling, since the iframe doesn't see the key press. So I don't think that needs to be handled in the engine.
