### ISSUE TITLE
Crash on picking colour picker

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#346]
## Problem description

Crash on clicking colour picker in sprite editor

## Attach a .c3p

No .cp3 as crashed before save but was minimal 2 sprites 10  or so events drawing lines between sprites.

## Steps to reproduce

may not consistently happen ( but I will do some investigation)

## Observed result

Crash with report below.

## Expected result

No crash .

## Affected browsers

* Chrome: yes
* Firefox: 
* Edge: 
* Safari: 

## System details

HP Zbook Laptop CAD workstation
windows 7 64
i7 
4GB quadro m graphics 
16GB ram

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r30/main.js, line 71, col 248447
Message: Uncaught TypeError: Cannot read property 'removeEventListener' of null
Stack: TypeError: Cannot read property 'removeEventListener' of null at ee.ǃycN.ǃy$O (https://editor.construct.net/r30/main.js:71:248447) at ee.ǃycN.ǃy$u (https://editor.construct.net/r30/main.js:71:177244) at ee.ǃycN.ǃycp (https://editor.construct.net/r30/main.js:71:176532) at ee.ǃySG.te.ǃy_j (https://editor.construct.net/r30/main.js:71:164038) at ee.ǃySG.te.ǃycx (https://editor.construct.net/r30/main.js:71:163532) at Array.ae.addEventListener.de (https://editor.construct.net/r30/main.js:71:163053) at ǃJ.Event.ǃOiK.ǃOiG (https://editor.construct.net/r30/main.js:2:285425) at ǃJ.ǃU.ǃJF.dispatchEvent (https://editor.construct.net/r30/main.js:2:283816) at ǃJ.ǃU.ǃUu.ǃJnA.ǃOu$.ǃJgu (https://editor.construct.net/r30/main.js:2:552893) at ǃJ.ǃU.ǃUu.ǃJnA.ǃOu$.ǃJgU (https://editor.construct.net/r30/main.js:2:552197)
Construct 3 version: r30
URL: https://editor.construct.net/
Date: Wed May 24 2017 15:42:59 GMT+0100 (GMT Daylight Time)
Uptime: 1988 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
C3 release: r30

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro K3100M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Does this still happen in r31? We just fixed a lot of bugs in that release.

**Comment by DiegoScirra** [comment]
I did a small fix that should prevent this one. But I am not sure because no one has been able to provide reproduction steps.

**Comment by NetOneGames** [comment]
Oh didn't see an update notification.    will update and around a bit again .....

**Comment by NetOneGames** [comment]
Ok tried 100 different things to repo.  including starting a new project and trying to break the sprite editor colour picker,  also loading in a 500 event c2 project and again messing with the sprite editor pressing random buttons swiping through multiple buttons clicking everything and I cant get to repo so maybe fixed. Close if you like and I will raise again if it crops up.  I don't have time to keep testing but I am dipping in from time to time to test stability.

**Comment by TheBl4ckSh33p** [comment]
btw, a Color picker for text objects would be nice. I cant just click on another Color in the editor to set text Color. :(
