### ISSUE TITLE
Getting error on export with projects on r174

### ISSUE THREAD

**Issue by medervolfr** [Scirra/Construct-3-bugs#3462]
## Problem description

I'm using curently construct 3 beta 174.
Once i try to export this project, for android or ios i get an error saying "failed to export project" .

## Attach a .c3p

https://filebin.net/0osen8hbju8lhq48

## Steps to reproduce

1.export to android
2.check everything + advanced minify mode
3. 5.0+ lolipop, android sudio project - > next

## Observed result
 At the mimifyng script step, it gives the error mentioned above

## Expected result

build succesfully

## More details

This is an old project which was exporting succesfully on beta version 173. 
So i may believe it contains something outdated which cannot compile.
It can succesfully export if i don't mimify the script.

**Affected browsers/platforms:** 

 i cannot export to no platforms

**First affected release:** 

worked on r 173 but not on r174

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.120
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
C3 release: r174 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 22 gb
Storage usage (approx): 747 mb (3.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Seems to be an issue minifying C2 runtime projects, going to assign this to @AshleyScirra as I'm not sure of the purpose of the block that is causing the issue.

**Comment by kingpirux** [comment]
> 
> 
> Seems to be an issue minifying C2 runtime projects, going to assign this to @AshleyScirra as I'm not sure of the purpose of the block that is causing the issue.

its happening with all c2 exports 
![imagen](https://user-images.githubusercontent.com/6506303/68411081-95392c00-0168-11ea-82dd-674b1b9553d7.png)

**Comment by AshleyScirra** [comment]
Fixed for next beta.
