### ISSUE TITLE
"set cursor from sprite" reverts to default cursor when the sprite is partially outside of the window

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#3467]
## Problem description

When using "set cursor from sprite" (Mouse plugin action), the cursor is set correctly, but when you approach the border of the screen and the cursor is partially outside of the window, the cursor reverts to the default arrow.

## Attach a .c3p

[cursor_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3817953/cursor_bug.zip)

## Steps to reproduce

1. Create a 64x64 pixel cursor
2. create a "set cursor from sprite" action and select the sprite you created.
3. Run the game and approach the border of the screen with the cursor
(alternatively, just open the capx and follow instructions)

## Observed result

The cursor returns to the default arrow when the sprite is partilly out of the window.

## Expected result

the cursor should be the sprite I defined as the new cursor at all times.

## More details

**Affected browsers/platforms:** NW.js, chrome preview (desktop build & chrome version)

**First affected release:** bug was already there in r150. Didn't check farther.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.87
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
C3 release: r150 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 28 gb
Storage usage (approx): 6.2 gb (22.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Chrome logs the following message to the console which appears to indicate it is intentional:

> [Deprecation] Custom cursors with size greater than 32x32 DIP intersecting native UI is deprecated and will be removed in M75, around June 2019. See https://www.chromestatus.com/features/5825971391299584 for more details.

The link provides more information:

> Custom cursors with widths or heights greater than 32 DIP will be removed if they intersect native UX (i.e. are not fully contained in the visual viewport). Large cursors are being used abusively on the web, to confuse users (see https://crbug.com/880863). Specifically, large custom cursors can be used to cover important (sometimes security related) browser native UX with an arbitrary image to mislead users into thinking they are clicking outside the content area.

It works fine if you limit the cursor to 32x32.
