### ISSUE TITLE
C2 games cannot be build with C3's export manager anymore (still working on C3 r160)

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#3468]
## Problem description

I exported my game from C2 with Cordova, zipped all the files in a zip archive, then tried to import it in C3's export manager, but it doesn't work anymore.
![image](https://user-images.githubusercontent.com/29117306/68376894-b5a5be00-0149-11ea-8288-e8dcb7d46161.png)

When reverting to C3 r160, the export manager is working correctly.

## Attach a .c3p

Here's a file exported from Construct 2 (Cordova for iOS) and zipped. It's an empty project with just a sprite.
[test2.zip](https://github.com/Scirra/Construct-3-bugs/files/3818819/test2.zip)

## Steps to reproduce

1. Export a game from construct 2
2. Select Cordova - iOS
![image](https://user-images.githubusercontent.com/29117306/68377441-ab37f400-014a-11ea-9b83-6330fb32de84.png)
3. Once built, open the folder and put the folder and the 2 files in a zip archive
4. Open C3's export manager and import the zip archive

## Observed result

Construct 3 export manager tells me this is not a Cordova project project exported with C2 or C3, but it is.

![image](https://user-images.githubusercontent.com/29117306/68374230-c1db4c80-0144-11ea-89ce-0fedb8f8e31a.png)

## Expected result

C3's export manager should be able to open a file exported with C2, as it did in the past.

## More details

**Affected browsers/platforms:** Tested with C2 r269 and 274, C3 export manager has been tested in desktop build and chrome. Reverting to r160 makes it work again.

**First affected release:** r172

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.40.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.40.1 (like Chrome/76.0.3809.100)
C3 release: r174 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 8388608 tb
Storage usage (approx): 745 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Looks to be a regression in r172. I believe you can workaround this for the time being by uploading the project in r171, then doing the build in the latest. In practice I don't believe that will actually make much difference, you should probably just use r171 for the time being.

The fix appears to be simple enough, the bug might actually effect some third party plugins in Construct as well.

**Comment by shortercode** [comment]
this issue is basically cordova configuration expecting in@AshleyScirra

**Comment by shortercode** [comment]
Should be resolved for the next release. Thanks for the report.
