### ISSUE TITLE
Timeline - On Finished doesn't immediately replay a timeline.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#3470]
## Problem description

Timeline - On Finished doesn't immediately replay a timeline.

**Issue :**
![image](https://user-images.githubusercontent.com/31282960/68554325-94531380-0462-11ea-9a87-47ab345ff6ef.png)

**Fix :**
![image](https://user-images.githubusercontent.com/31282960/68554310-84d3ca80-0462-11ea-833e-0f0eda9a1993.png)

Without a `Wait (0) Seconds`, it'll fail to run.

## Attach a .c3p

**With Issue :**
[Bugged.zip](https://github.com/Scirra/Construct-3-bugs/files/3829321/Bugged.zip)

**Workaround :**

[Workaround.zip](https://github.com/Scirra/Construct-3-bugs/files/3829323/Workaround.zip)

## Steps to reproduce

1. Press the `Play timeline` button, from the modified Construct 3 demo project.
2. Check the events, and observe the difference of both projects.

## Observed result

The project with the issue, doesn't replay the timeline after finishing. Unlike how it's declared through the events.

## Expected result

Timeline to be played immediately after the `On Finished` trigger.

------ 

Thanks!

**Comment by DiegoScirra** [comment]
Fixed in the next beta
