### ISSUE TITLE
Setting time scale to zero during an opacity tween instantly sets opacity to zero

### ISSUE THREAD

**Issue by AySquirrel** [Scirra/Construct-3-bugs#3471]
## Problem description

So while playing around with a pause feature in my game, I noticed that if you pause the game (i.e., set the current time scale to zero) while an opacity tween is playing,  the tweened object will instantly become completely transparent, setting it's own opacity to zero instead of just pausing the tween like with other types of tweens. Then, after unpausing (setting the timescale back to 1), it will jump back to where it will attempt to restart the tween from the beginning, but won't always finish and will outright disappear if repeated a few times.

## Attach a .c3p

[TweenTimeScaleBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3830230/TweenTimeScaleBug.zip)

## Steps to reproduce

1. Run the layout
2. Press the top button to start the tween
3. While the tween is still playing, press the second button to set the time scale to 0, and observe that the object disappears
4. Press the third button to set the time scale back to 1, and again interrupt the tween by setting the time scale to 0 while the tween is still playing
5. Finally, press the third button to set the time scale back to 1, but let the tween attempt to finish, and notice that the object will disappear part way through. If the tween does finish, simply repeat the steps with more interruptions until the tween fails to finish.

## Observed result

The red square disappears while the tween is paused, and fails to finish at all if interrupted with a pause too many times

## Expected result

The red square to have it's tween paused normally, and then finish after unpausing

## More details

**Affected browsers/platforms:** Chrome, Firefox

## System details

<details><summary>View details</summary>

Platform information
Browser: Opera
Browser version: 63.0.3368.107
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36 OPR/63.0.3368.107
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 6.2 gb (10.1%)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Persistent storage is not available. Local storage could be deleted by the browser.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta
