### ISSUE TITLE
changing the text inside a text input object with events does not trigger the "on text changed" text input trigger

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3472]
## Problem description
changing the text inside a text input object with events does not trigger the "on text changed" text input trigger

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is by design.
