### ISSUE TITLE
Platform info resizing bug

### ISSUE THREAD

**Issue by Keevle** [Scirra/Construct-3-bugs#3473]
## Steps to reproduce

1.Make a blank project
2.Add platform info 
3.preview project then resize the window

## Observed result
Exception in 'platform-info' handler 'window-resize': ReferenceError: data is not defined
    at C3.Plugins.PlatformInfo.Instance._OnWindowResize (instance.js:1)
    at instance.js:1
    at C3.Runtime._OnEventFromDOM (runtime.js:1)
    at C3.Runtime._OnMessageFromDOM (runtime.js:1)
    at MessagePort._messagePort.onmessage (runtime.js:1)
(anonymous) @ b2bf71a0-1288-43c5-8941-30c9f70bd2e0:5
_OnEventFromDOM @ runtime.js:1
_OnMessageFromDOM @ runtime.js:1
_messagePort.onmessage @ runtime.js:1

## Expected result

No errors
## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

No Crash
</details>

**Comment by shortercode** [comment]
Appears to be a simple typo. But is a typo in todays release. Assigning to @AshleyScirra as it's his revision.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
