### ISSUE TITLE
Booleans are written sometimes with upper and sometimes lower case.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3476]
## Problem description

The image below shows "False" and "false". I don't know if this is by design or a minor oversight, because it is truly unimportant, but here it is.

![image](https://user-images.githubusercontent.com/34659544/68763436-2db32e80-05f7-11ea-8b61-0518b8a48e75.png)

## Attach a .c3p

Any file should present it.

## Steps to reproduce

1. Have a Json boolean and a normal boolean set to either true or false.

## Observed result

A different pattern.

## Expected result

The same pattern.

## More details

**Affected browsers/platforms:** Chrome, maybe others.
**First affected release:** 174, maybe others.

## System details

No crash.

**Comment by AshleyScirra** [comment]
Various boolean parameters across Construct are implemented using a combo box with "false" and "true" items. Each time it is separately specified meaning there could be inconsistencies in various places. There is a new boolean parameter that shows as a checkbox and thus avoids this problem, but switching existing events to it is actually quite complicated. If we switch everything over to that it will solve it, but given that we're a tiny team under a great deal of time pressure, I don't think this is significant enough to justify dropping other more important work to spend time on this.
