### ISSUE TITLE
Orbit Behavior with Zero Speed acts like it's disabled when manually adjusted

### ISSUE THREAD

**Issue by broknecho** [Scirra/Construct-3-bugs#3478]
## Problem description

When using the Orbit behavior and setting the rotation manually, setting the speed to 0 acts as if it's disabled.

## Attach a .c3p

[Orbit Issue.zip](https://github.com/Scirra/Construct-3-bugs/files/3849996/Orbit.Issue.zip)

## Steps to reproduce

1. Open attached project
2. Note that Orbit A example has speed set to 0 and Enabled is set to true
3. Note that Orbit B example has speed set to 1 and Enabled is set to true
4. Run project and move mouse around

## Observed result

Start layout and see that A orbit is not initialized to it's Pinned Base and it does not react to the mouse movement when rotation is manually set

## Expected result

Orbit B reacts as I would expect when trying to manually set the rotation if you don't want automatic Orbiting with the speed parameter.

## More details

Not much more detail needed from the sample project.

**Affected browsers/platforms:** 

Tested in Chrome

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.97
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 7.4 gb
Storage usage (approx): 732 mb (9.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Fairly simple fix, there was some logic to skip recalculating the position if the speed was 0. With the assumption that the position wouldn't change if it wasn't moving. But this of course did not take into account that actions/pinning could change the position while it was the speed was 0. The check was flawed so I just removed it.  It might have mild performance cost for some projects as immobile instances will now be updated once per tick, but there is still the option of disabling the behaviour.

Fixed for next beta release.
