### ISSUE TITLE
Snapshot is extremely slow on mobile, when objects with Physics behaviour are on the layout

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#3480]
## Problem description

I'm working on a physics game where when my character dies, I need to take a snapshot of its final moment, it's an essential part of the game.
I noticed that on Android phone it takes over 4 seconds to make the snapshot!

I spent an entire day experimenting and here are my findings:

1. This bug affects both "System Take snapshot" and "Drawing Canvas Save Image" actions, and the lag is 4 seconds in both cases.
2. Most, but not all Physics objects are causing this lag:
_TiledBackground+Physics = always lag
Sprite+Physics = lag with some animation frames, no lag with others._
3. Setting objects as Immovable doesn't help.
4. This happens only in apk, not in remote preview.
5. "Use worker" option has no effect.
6. The number of Physics objects/instances and their positions don't matter, lag duration is always the same ~4 seconds.
7. Destroying objects or disabling Physics behavior removes the lag
8. LiteTween behavior causes the same issue. I know you don't support this addon, but maybe this detail will help you to find the cause.
9. The lag is the same 4 seconds on an old phone with Android 5.1 and on a modern phone with Android 9

## Attach a .c3p

C3P:
https://www.dropbox.com/s/y20w1kujt00vav1/SnapshotPhysicsBug.c3p?dl=0
APK:
https://www.dropbox.com/s/s10x1jm0l8szwnp/SnapshotPhysicsBug.apk?dl=0

## Steps to reproduce

1. Build an apk, run on Android device
2. Press buttons to make snapshots
3. Tap on objects to remove them, try to make snapshots again.

## Observed result

4 seconds lag with some Physics objects.

## Expected result

No lag.

## More details

**Affected browsers/platforms:** 
Android 5.1.1, Android 9
Don't have an iOS device to test.

**First affected release:** 
Tested with r171.3 and r175

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.40.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.40.1 (like Chrome/76.0.3809.100)
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 8388608 tb
Storage usage (approx): 562 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by Dramamini** [comment]
I have the same snapshot delay.. Without using any physics. On desktop snapshot works fine. On android (Preview or apk) has 4 second delay.

I have made a post and an example, here:
https://www.construct.net/en/forum/construct-3/general-discussion-7/snapshot-delay-148113

**Comment by AshleyScirra** [comment]
It's not a Construct bug - the fact it works fine in the Chrome browser shows Construct's code is working fine. It looks like another Android Webview bug.

It's nothing to do with Physics - it happens when the screen is redrawing every frame. A spinning sprite does that, and Physics happens to force it as well as part of updating the physics simulation.

It looks like either a GPU issue or a scheduling problem that only happens in the Android WebView. I filed a Chrome issue with Google about it here: https://bugs.chromium.org/p/chromium/issues/detail?id=1025695

**Comment by dop2000** [comment]
Thanks, Ashley. A quick question - is there any other way to copy image from DrawingCanvas into a sprite, without using "Save image" action?

**Comment by AshleyScirra** [comment]
I don't think so.

**Comment by Dramamini** [comment]
Maybe a solution is to stop screen redrawing (pause the game?) and then take the screenshot?

**Comment by AshleyScirra** [comment]
That would visibly jank the game, which always results in complaints.

**Comment by dop2000** [comment]
@Dramamini Unfortunately it didn't help. I tried setting timescale to 0, run "Save image" on the next tick, it still takes 4 seconds to trigger "On saved image".
Maybe temporarily disabling Physics for all objects will work, but I can't do this in my game.

**Comment by AshleyScirra** [comment]
@dop2000 - in reporting a separate issue, a Google developer requested the original source to this issue as it was related and they need to verify they don't actually regress this issue, but the links in the original report are now dead. Do you still have the original .c3p project by any chance?

**Comment by dop2000** [comment]
@AshleyScirra 
Here are the original files:
https://www.dropbox.com/s/8p0unrqdir8z9rj/SnapshotPhysicsBug.c3p?dl=0
https://www.dropbox.com/s/iurzpt9jlllezb8/SnapshotPhysicsBug.apk?dl=0

**Comment by AshleyScirra** [comment]
Great, thanks!
