### ISSUE TITLE
Some places have "complete" written and some places "completed"

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3483]
## Problem description

A very minor issue if it even is an issue.

## Attach a .c3p

Every file should present it.

## Steps to reproduce

1. Open any project.
2. Set Ajax triggers.
3. Set Load triggers.
4. Compare both instances.

![image](https://user-images.githubusercontent.com/34659544/69030030-286a3100-09b5-11ea-8ad5-8b2b76482876.png)

## Observed result

Two patterns?

## Expected result

One pattern.

## More details

**Affected browsers/platforms:** Chrome, maybe others
**First affected release:** 175, maybe older

## System details

No crash.

**Comment by AshleyScirra** [comment]
As a small team pushed for time, I don't think this is worth the time investment reviewing all the thousands of strings in the editor. There may be some inconsistencies but it still seems perfectly understandable.
