### ISSUE TITLE
Brownser reload action doesn't work on c3 desktop version (NWJS)

### ISSUE THREAD

**Issue by cb130felix** [Scirra/Construct-3-bugs#3486]
## Problem description

Brownser reload action seems to work fine on c3 web but doesnt work on desktop version. When I try to use reload action on desktop version I get a  "Loading..." on the window name and the game screen goes blank.

## Attach a .c3p

https://drive.google.com/open?id=1tDqyrEx6H2Vvtuy0MTQuIEROKi1Qlc0W

## Steps to reproduce

1. Start project and press any key to run the reload action

## Observed result

On c3 desktop version the game doesn't reload

## Expected result

For the project to restart

**Affected browsers/platforms:** 

NWJS

**First affected release:** 

Not sure, just tried in r176

**Comment by AshleyScirra** [comment]
Fixed for next beta.
