### ISSUE TITLE
iOS 13 required new method for requesting device orientation?

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#3487]
## Problem description

iOS 13 required new method for requesting device orientation?

## Attach a .c3p
[OrientationTest.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3862064/OrientationTest.c3p.zip)

## Steps to reproduce

1. Load project
2. Run remote preview, use iPhone w/ iOS 13.x
3. Tap screen to request orientation.

## Observed result

Orientation request is denied (and no pop up appears to request permission.)

## Expected result

Orientation permission pop up and on 'Allow' from user, orientation request is granted.

## More details

Layout 2 uses JS to create a button and request orientation.

Change starting Layout to Layout 2 and run again with remote preview. It will now work in terms of a pop up appearing and orientation permission granted.

Note: once granted it will work be granted for future requests from preview, so Layout 1 will have permission granted also.

One description of the issue and fix:
https://medium.com/flawless-app-stories/how-to-request-device-motion-and-orientation-permission-in-ios-13-74fc9d6cd140

**Affected browsers/platforms:**
Chrome MacOS

## System details
Chrome

<details><summary>View details</summary>
</details>

**Comment by AshleyScirra** [comment]
From the [manual](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/touch):

> This must be used in a user input event, normally *On touch end* (note that *On touch start* may not work).

The project uses *On any touch start*. Switch it to *On any touch end*.

**Comment by MikalDev** [comment]
Thanks Ashley - sorry I misread the manual!
