### ISSUE TITLE
[R176] No horizontal scroll bar at project/layers/tilemap tabs

### ISSUE THREAD

**Issue by NoSoul8** [Scirra/Construct-3-bugs#3488]
## Problem description

Horizontal scrollbar won't appear when reducing the width of tabs menus.
## Steps to reproduce

1. Open any project in the r176 version of C3
2. Resize right hand menu to reduce the width of project/layers/tilemap tabs
3. Check with different color schemes (screenshots are provided at the "More details" section)

## Observed result
Horizontal scrollbar won't appear (it was there a build or two ago)

## Expected result
Horizontal scrollbar appears, making it possible to navigate the outside of view space

## More details

I've tested this issue with all 3 color schemes available:
1 Dark theme - no scrollbars appear
![DarkTheme](https://user-images.githubusercontent.com/34763413/69125230-c8f84800-0abe-11ea-9191-284f640f8d5c.png)
2 Light theme - no scrollbars appear
![Lighttheme](https://user-images.githubusercontent.com/34763413/69125275-e3cabc80-0abe-11ea-8c7b-1d44dd731263.png)
3 No theme - project bar text adjusts to fit the screen (making it vertical, and poorly readable if there are many subfolders), tilemap bar has a scrollbar
![NoTheme](https://user-images.githubusercontent.com/34763413/69125391-27252b00-0abf-11ea-8186-137c049d96d7.png)

**Affected browsers/platforms:** 
Observed at Google chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Has this always been the case, or are you saying this worked in r175 and regressed in r176?

**Comment by shortercode** [comment]
Couple of observations: this appears to be on a macOS system with either a trackpad or magic mouse, where scrollbars are often ( not always ) hidden when not in use. Also the parent pane of the project and tilemap bars appear to be overflowing off the edge of the screen in these shots, so they might not actually be scroll-able.

**Comment by AshleyScirra** [comment]
@NoSoul8 - as ever it would be useful to include your system details so we don't have to guess.

**Comment by NoSoul8** [comment]
Sorry, my bad. As @shortercode has correctly stated, I've originally raised this issue for MacOS, but I've double checked it at Windows PC and got the same result in R176, here is a screenshot:
![C3scrollbar](https://user-images.githubusercontent.com/34763413/69166055-0df69b80-0b0c-11ea-84db-3bf5fd912e66.PNG)

As for the version, @AshleyScirra  i can't recall at which version it _exactly_ stopped working, but the horizontal scroll bar is there in the stable R171.3 , here is a screenshot (tested in the Fireworks demo, google chrome, win7):
![C3scrollbarr1713](https://user-images.githubusercontent.com/34763413/69166237-5b730880-0b0c-11ea-9fd1-44ef438230a5.PNG)

**Comment by shortercode** [comment]
The tilemap bar requires slightly more space than the layers bar. If you look at the close button for the bar you can see that it is off the side of the screen in your image of Cold Shell but it's visible when looking at the layers bar. So it's not really an apples to apples comparison.

**Comment by NoSoul8** [comment]
@shortercode  The true purpose of this bug is the project tab horizontal scroll bar gone missing. I need it to navigate through subfolders. Feel free to split/drop other issues at will, if they are hard to fix/irrelevant .

**Comment by shortercode** [comment]
My point being that the panel doesn't think it needs a scrollbar because it's wide enough to hold it's content, but in reality part of the panel is off the screen.

**Comment by AshleyScirra** [comment]
Looks like it regressed in r173

**Comment by AshleyScirra** [comment]
Should be fixed in the next build, just some CSS cleanup done for r173 that went too far.
