### ISSUE TITLE
[r31] Text Z-order wrong after using CTRL+Drag or CTRL+V

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#349]
## Problem description
When I use CTRL+Drag to create a new instance/copy of an object with text above the text is suddenly behind the object. Same when I  use CTRL+V to paste the 2 objects.

## Attach a .c3p
[ZAligmentBroken.zip](https://github.com/Scirra/Construct-3-bugs/files/1026221/ZAligmentBroken.zip)

## Steps to reproduce

1. Place text above another object like 9patch
2. ctrl+drag or ctrl+c/ctrl+v to paste both objects

## Observed result

text is suddenly behind and has a lower z-order

## Expected result

text should be above like it is in the original object

## Affected browsers
C3 Editor (Chrome)

**Comment by TheBl4ckSh33p** [comment]
I tried it again a few times and it worked as expected now. But it happened many times before.

**Comment by AshleyScirra** [comment]
The Z order was indeed not always correct. Thanks, should be fixed in r32.
