### ISSUE TITLE
Speech recognition doesn't request microphone permission on Android.

### ISSUE THREAD

**Issue by Hodgekins** [Scirra/Construct-3-bugs#3490]
#2630  Problem description

I'm unable to use the speech recognition plugin on an Android device.
Triggering the _Request speech recognition_ action results in a _not-allowed_ error.
I'm using Construct 3 r176

## Attach a .c3p

Problem can be reproduced using the _speech recognition demo_.

## Steps to reproduce

1. Load speech recognition demo project from start page
2. Export Android Studio project
3. Trigger _request speech recognition_ action by tapping the "Start" button

## Observed result

Speech recognition plugin reports that _Speech recognition is supported_
But the the plugin returns a _not-allowed_ error.

## Expected result

A dialogue requesting permission to use the device microphone.

## More details

I've tested on Chrome using remote preview. It works perfectly with no issue. Permission to use the microphone is requested the first time speech recognition is requested.

The issue only happens after I export the project to Android Studio or upload the project to Google Play. 

**Affected browsers/platforms:**

Android mobile device

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.87
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
C3 release: r176 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 207 gb
Storage usage (approx): 678 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2047
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Hodgekins** [comment]
Just noticed I'm getting the following error in Android Studio when the device requests speech recognition:

**W/cr_media: Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording
D/SystemWebChromeClient: onPermissionRequest: [android.webkit.resource.AUDIO_CAPTURE]**

**Comment by shortercode** [comment]
Ticking "require microphone permission" on export should give you those 2
permissions. We may also need to add in a call to the permissions dialog
though.

**Comment by Hodgekins** [comment]
Thanks for your reply!

I can confirm those permissions were ticked on export.

Following advice on this thread:
https://stackoverflow.com/questions/38917751/webview-webrtc-not-working

I changed a line in the manifest file:
`    <uses-sdk android:targetSdkVersion="28" />`
to
`    <uses-sdk android:targetSdkVersion="22" />`

I'm not entirely sure of the consequences of this but it now seems to work ok. It's not asking me for permission but it is working.

**Comment by shortercode** [comment]
We probably need to request the permissions at runtime, the usermedia
plugin already does this but I expect speech recognition doesn't have it.

**Comment by AshleyScirra** [comment]
FYI you can add the permission prompt but I can't remember if the Android webview actually supports speech recognition yet, and [this Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=487255) doesn't appear to be conclusive. It's probably worth adding the permission code for future-proofing, but it may be that it still doesn't work after permission is granted. Try using the *Supports speech recognition* condition to check it's actually supported (hopefully that feature detects correctly...)

**Comment by Hodgekins** [comment]
Thanks Ashley & Iain for helping with this. It seems to work perfectly now I've reduced the target SDK version. To make sure, I'm working on adding the permission code as you suggested.

I'm also having issues with speech recognition in iOS devices. With iOS, it just doesn't seem to be supported at all. I realise this isn't a Construct 3 bug, and I don't want to hijack my own thread so I asked a question on the forum: https://www.construct.net/en/forum/construct-3/how-do-i-8/speech-recognition-ios-devices-148527

**Comment by AshleyScirra** [comment]
Changing the target SDK version is a workaround, not a fix - we'll leave this issue open until we have a fix (or other conclusion).

**Comment by shortercode** [comment]
It would appear to work correctly in an Android project. Although it's hard to know what the official status of the API is in WebView.

I've refactored our permissions code from UserMedia into common runtime code, and added the required calls to speech recognition to allow it to request the microphone permission.

Should be resolved in the next beta release.
