### ISSUE TITLE
Bug on Rename Sound Files and undo

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3491]
## Problem description

Renaming a sound (.webm) file and then undo makes c3 crash.

## Attach a .c3p

no file need

## Steps to reproduce

1. New Project
2. Import sound
3. Rename sound
4. Undo (Ctrl+Z)

## Observed result

Crash

## Expected result

Undo Rename

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:**  worked in r175 but broke in r176

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: ǃA.ǃZKb is not a function @ TypeError: ǃA.ǃZKb is not a function at t.ǃY (https://editor.construct.net/r176/projectResources.js:1:419715) at Object.ǃZnr (https://editor.construct.net/r176/projectResources.js:1:548897) at Object.ǃCwe (https://editor.construct.net/r176/projectResources.js:1:545552) at t.ǃCwe (https://editor.construct.net/r176/projectResources.js:1:51383) at Object.ǃCwe (https://editor.construct.net/r176/main.js:210:106293) at Array. (https://editor.construct.net/r176/main.js:210:65020) at Object.ǃAPo (https://editor.construct.net/r176/main.js:2:197366) at Object.dispatchEvent (https://editor.construct.net/r176/main.js:2:195317) at e (https://editor.construct.net/r176/main.js:210:117634) at Object.ǃZpC (https://editor.construct.net/r176/main.js:210:118259)
Stack: TypeError: ǃA.ǃZKb is not a function at t.ǃY (https://editor.construct.net/r176/projectResources.js:1:419715) at Object.ǃZnr (https://editor.construct.net/r176/projectResources.js:1:548897) at Object.ǃCwe (https://editor.construct.net/r176/projectResources.js:1:545552) at t.ǃCwe (https://editor.construct.net/r176/projectResources.js:1:51383) at Object.ǃCwe (https://editor.construct.net/r176/main.js:210:106293) at Array. (https://editor.construct.net/r176/main.js:210:65020) at Object.ǃAPo (https://editor.construct.net/r176/main.js:2:197366) at Object.dispatchEvent (https://editor.construct.net/r176/main.js:2:195317) at e (https://editor.construct.net/r176/main.js:210:117634) at Object.ǃZpC (https://editor.construct.net/r176/main.js:210:118259)
Construct 3 version: r176
URL: https://editor.construct.net/r176/
Date: Thu Nov 21 2019 12:13:55 GMT+0530 (India Standard Time)
Uptime: 39.5 s

Platform information
Browser: Chrome
Browser version: 78.0.3904.97
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
C3 release: r176 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Would appear that the "rename" undo method was not updated during the project file refactor. Fixing it is relatively simple, but there may be other places in the editor effected by the change in method name.

Assigning @AshleyScirra to review as he has done the bulk of the work on this refactor. Feel free to reassign to me if there are any component specific changes you would like me to look at.

**Comment by AshleyScirra** [comment]
Looks like a fairly small oversight, should be fixed for the next beta.
