### ISSUE TITLE
Documentation: Dead/private embeds from Giphy

### ISSUE THREAD

**Issue by gedaerm** [Scirra/Construct-3-bugs#3494]
## Problem description

Some parts of the official C3 documentation embed gifs hosted on Giphy. Some (or possibly all) of those are not showing, but instead show a "the owner has set this gif to private".
Example: The timeline plugin reference:
https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/timeline
In the "About picking" section

## Attach a .c3p

n/a

## Steps to reproduce

n/a

## Observed result

Embedded Gifs don't show.

## Expected result

They should.

## More details

n/a

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

n/a

</details>

**Comment by AshleyScirra** [comment]
I think @DiegoScirra wrote this particular manual content so assigning to him.

This is why we shouldn't host any aspect of the official documentation on third-party services. I think we could get away with a YouTube embed, but it's probably best to go with an actual (heavily-compressed) GIF file.

**Comment by shortercode** [comment]
@DiegoScirra I have used [this website](https://ezgif.com/maker) for creating gifs from videos, resizing, clipping and compressing in the past. Works reasonably well.

**Comment by DiegoScirra** [comment]
They must have changed something about how the privacy settings were working. It should be working now.
