### ISSUE TITLE
Audio doesn't convert to webm format after imported (some times)

### ISSUE THREAD

**Issue by cb130felix** [Scirra/Construct-3-bugs#3496]
## Problem description

Please, look a the image

https://ibb.co/SP6QG3B

if you drag a audio to where the blue arrow points the audio is converted to webm format
if you drag to where the red arrow pointed area it's not converted

## Attach a .c3p

I guess there's no need, you need to create a project a project with audio plugin and try it yourself to see the file not being converted

## Steps to reproduce

1. Add audio plugin to the project
2. Open the "import audio" window
3. Import audio draging it inside the "drag and drop audio files here" area, audio gets converted to webm format
4. Import audio draging it outside the "drag and drop audio files here" area, audio doesn't get converted to webm format

## Observed result

Audio file is not converted to webm files in some cases

## Expected result

For the audio to be converted

## More details

I'm on r176 using c3 desktop version (NWJS)

**Comment by shortercode** [comment]
This seems to actually cover 2 issues.

First being that having a modal dialog open does not prevent you from dropping a file onto the project area. Dropping a PNG file outside of a modal dialog will cause it to create a sprite in the background.

The second appears to be that dropping sound files onto the layout view doesn't import the audio track correctly after the project file refactor.

I'll take the latter one, @AshleyScirra could you take a look at the first?

**Comment by AshleyScirra** [comment]
Fixed the first case for the next beta and I think that may cover both cases anyway. Since it incorrectly handled background drops to the main window, dropping an audio file would try to bring up the audio import dialog again, but it was already showing, so it probably had some kind of conflict. It looks like it works properly now. Leaving assigned to @shortercode to verify but I expect this can be closed.

**Comment by shortercode** [comment]
Appears to be fine after the correction, so going to close this issue.
