### ISSUE TITLE
Sprite icon isn't updated in event sheet and project bar after I import a new spritesheet into it

### ISSUE THREAD

**Issue by cb130felix** [Scirra/Construct-3-bugs#3497]
## Problem description

After I import a new spritesheet into a sprite the sprite icon isn't updated in the project bar and neither it is updated in the event sheet while referencing the sprite in actions and conditions

## Attach a .c3p

No need, since you can't see the bug by a uploaded project since the icons will be refreshed after you restart c3, you'll need to try to reproduce it yourself

## Steps to reproduce

1. Create a new project
2. Create a new sprite
3. Right click in the window that show the sprite animation and select "import frames -> from strip"
4. Import a spritesheet
5. in the "import sprite strip" window, select "replace entire animation" and import the sheet
6. make sure to NOT edit anything using the c3 image editor
7. close the sprite editor
8. Sprite icon isn't updated in the "project" bar and in the event sheets while referencing it until you edit the sprite in c3 editor or you restart c3

## Observed result

Sprite icon isn't updated in the "project" bar and in the event sheets while referencing it until you edit the sprite in c3 editor or you restart c3

## Expected result

For the sprite icon to be updated to the new animation imported

## More details

C3 r176, I could reproduce the bug both in web and desktop versions

**Comment by AshleyScirra** [comment]
Since all other edits appear to update the icon, this looks like an issue with importing frames from a strip specifically, so assigning to @DiegoScirra.

**Comment by DiegoScirra** [comment]
Fixed in the next beta
