### ISSUE TITLE
Can't set angle if sprite is spawned instead of created?

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#3499]
## Problem description
I spawned bullets from my player sprite and noticed that setting a random bullet angle does not work as soon as you change the default (0) angle and all spawned objects have the same angle as the parent. Is this intended or a bug?

And when I made the example project I noticed create object only seems to create the bullets at the first instance of the object. While spawn creates it for every instance.

Are both behaviors intended?

## Attach a .c3p
[BulletAngleBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3884016/BulletAngleBug.zip)

## Steps to reproduce

1. add bullet behavior to a sprite
2. spawn bullets at an angle

## Observed result

spawned items are always using the parent object angle even if you set a different bullet angle of  motion

## Expected result
angle of motion should be the value you set?

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
175
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r175 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 22 gb
Storage usage (approx): 1.1 gb (5.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 615 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's not actually a bug: 'Spawn' sets the object angle after creation, and the bullet behavior's 'Set angle' property is enabled, which also means "when the object angle is changed, set the angle of motion to that", which ends up setting the angle of motion.

It should be easy to work around - you've already found another way to achieve the same result, or you can set the object angle instead of the angle of motion, or you can disable 'Set angle' to customise the angles separately without any automatic handling.
