### ISSUE TITLE
CTRL + X Then Cancel Bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#35]
## Problem description

Doing a Cut and Paste process with right-click Cut is fine. But when done with CTRL + X, Construct will immediately delete the instance before checking if the user presses cancel or copy.

## Steps to reproduce

1. Create an object.
2. Select it and CTRL+X
3. Press Cancel.

## Observed result

The selected instance was deleted before the copy prompt appears.

## Expected result

What for user's choice of Cancel or Copy before doing any action, just like the right-click Cut process.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r17.
