### ISSUE TITLE
[r31] C3 crash when holding DEL to delete multiple images of a sprite

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#350]
## Problem description

When holding DEL key to delete multiple images of a sprite fast C3 crashes

## Attach a .c3p

[HoldDelToDelSpriteImages.zip](https://github.com/Scirra/Construct-3-bugs/files/1026653/HoldDelToDelSpriteImages.zip)

## Steps to reproduce

1. add images to sprite
2. hold del to delete some images
3. crash

## Observed result

C3 Crash!

## Expected result

no crash :)

## Affected browsers
Editor (Chrome)

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r31/main.js, line 61, col 198915
Message: Uncaught Error: animation frame has no content
Stack: Error: animation frame has no content at oe.ǃB_W (https://editor.construct.net/r31/main.js:61:198921) at oe.ǃMD (https://editor.construct.net/r31/main.js:61:200827) at a.ǃUc.ǃzJd (https://editor.construct.net/r31/plugins/sprite/plugin.js:1:5945) at ǃB.ǃ$t.ǃzJx.ǃB.ǃ$t.f [as ǃzrv] (https://editor.construct.net/r31/plugins/sprite/plugin.js:1:4089) at ǃB.ǃ$t.ǃzfF (https://editor.construct.net/r31/main.js:2:296529) at ǃB.ǃ$t.ǃzfJ (https://editor.construct.net/r31/main.js:2:296657) at ǃzfa (https://editor.construct.net/r31/main.js:2:296190)
Construct 3 version: r31
URL: https://editor.construct.net/index.html
Date: Wed May 24 2017 20:18:49 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 4034.9 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by mfoster98** [comment]
I also get this crash!

**Comment by DiegoScirra** [comment]
Fixed in r32.

Thanks for reporting :)
