### ISSUE TITLE
Crash on Find all References on Used Addon Bar

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#3501]
## Problem description

Crash on find al references when right click on the "used addon" bar

## Steps to reproduce

1. Open project
2. Right click on the project folder of the project bar for "Tools"> view used addons
3. Pick an addon and right click find all references

## Observed result

crash

## Expected result

search and find objects and events

## More details

Error report information
Type: unhandled rejection
Reason: Error: this.ǃMUD.ǃFq is not a function @ TypeError: this.ǃMUD.ǃFq is not a function at Object.ǃBw (https://editor.construct.net/r177/components/bars/findReferencesBar/findReferencesBar.js:1:1718)
Stack: TypeError: this.ǃMUD.ǃFq is not a function at Object.ǃBw (https://editor.construct.net/r177/components/bars/findReferencesBar/findReferencesBar.js:1:1718)
Construct 3 version: r177
URL: https://editor.construct.net/r177/
Date: Mon Nov 25 2019 15:34:16 GMT-0300 (hora estándar de Argentina)
Uptime: 114.3 s

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r177 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon(TM) RX 460 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
No project attached so tried Ghost Shooter. It worked fine. Please always attach a project as per the bug report guidelines to ensure we can investigate the issue you are reporting.

**Comment by kingpirux** [comment]
i just tryed with gosht shooter and the problem showed... maybe some problem with cache? ill try to clean my browser
![imagen](https://user-images.githubusercontent.com/6506303/69639292-01f26880-103b-11ea-946e-e62260fde914.png)

**Comment by kingpirux** [comment]
browser clean. didnt work, still having the same error, just in case here is the steep by steep: 
![imagen](https://user-images.githubusercontent.com/6506303/69641884-b2626b80-103f-11ea-8d11-7a6862e1f377.png)
![imagen](https://user-images.githubusercontent.com/6506303/69641925-c27a4b00-103f-11ea-827e-8730cc277340.png)
![imagen](https://user-images.githubusercontent.com/6506303/69641944-cad28600-103f-11ea-823a-c723a3466559.png)

**Comment by AshleyScirra** [comment]
I tried following those exact steps and it still works fine. I don't know what could be wrong and we can't investigate it if we can't reproduce it. Try disabling all browser addons maybe.

**Comment by kingpirux** [comment]
nothing... removed, Restarted, reseted the chrome configuration.- If it helps, if i try to do it without entering my account, it doesn't crash and show the "only paid account"

More data:
main.js:2 Error while parsing the 'sandbox' attribute: 'allow-storage-access-by-user-activation' is an invalid sandbox flag.

findReferencesBar.js:1 Uncaught (in promise) TypeError: this.ǃMUD.ǃFq is not a function
    at Object.ǃBw (findReferencesBar.js:1)
ǃBw @ findReferencesBar.js:1
async function (async)
ǃBw @ findReferencesBar.js:1
ǃBD @ main.js:210
(anonymous) @ main.js:210
setTimeout (async)
ǃnX @ main.js:52
ǃna @ main.js:52
(anonymous) @ main.js:2

**Comment by kingpirux** [comment]
it also happens in firefox... might be a compatibility error with something?

Error report information

Type: unhandled rejection
Reason: Error: this.\u01C3MUD.\u01C3Fq is not a function @ ǃBw@https://editor.construct.net/r177/components/bars/findReferencesBar/findReferencesBar.js:1:1718
Stack: ǃBw@https://editor.construct.net/r177/components/bars/findReferencesBar/findReferencesBar.js:1:1718
Construct 3 version: r177
URL: https://editor.construct.net/r177/
Date: Wed Nov 27 2019 00:49:12 GMT-0300 (hora estándar de Argentina)
Uptime: 67.1 s
Platform information

Browser: Firefox
Browser version: 70.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
C3 release: r177 (beta)
Language setting: es-ES
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon(TM) RX 460 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
