### ISSUE TITLE
Lots of (new) compiler errors in constructad.swift

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3504]
Lots of new compiler errors popping up. This used to work not too long ago, not sure if it has to do with r177 or if something changed in the build service.

xCode 12.2.1

![err](https://user-images.githubusercontent.com/31101309/69660830-718b4680-1081-11ea-9e93-79f65fab9eda.png)

![err2](https://user-images.githubusercontent.com/31101309/69661211-47865400-1082-11ea-8cb3-1a7d1ad4e1f5.png)

## Attach a .c3p

Not sure if you need one, I suppose this just happens with any export that contains mobile advert

## Steps to reproduce

1. export xcode project
2. open in xcode

## Observed result

Lots of compiler errors that prevent building.

## Expected result

The opposite

## More details

Build with r177

**Affected browsers/platforms:** 

**First affected release:** r177 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r177 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 1.6 gb (11.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
We added some new methods to Mobile Advert in r177, it will be related to that. I'll take a look. If you build in r176 you should be fine for the meantime.

**Comment by shortercode** [comment]
Builds in r177 should be working now, I've pushed the newer version to the server.

**Comment by trueicecold** [comment]
Still happens on r178...

**Comment by trueicecold** [comment]
Just checked r177 as well, still has those errors...

**Comment by shortercode** [comment]
What method are you using to build your project?

**Comment by trueicecold** [comment]
Exporting as ios Cordova project then in cli:

cordova platform add ios

**Comment by shortercode** [comment]
Ah right, you shouldn't need to add the platform. You can run `cordova prepare` and it will restore the project from the config.xml ( including installing any required platforms and plugins ).

It might be building with the wrong `construct-mobile-advert` version when exporting as a cordova project.

**Comment by shortercode** [comment]
Yes I followed your export steps and it's still using 1.5.1. The correct version being 1.5.2. When exporting via the build server ( not used when exporting as "cordova" ) it automatically uses the newest whitelisted maintenance version for plugins, hence why it's only affecting a limited number of users. I will update the reference so that this will be fixed in the next release.
