### ISSUE TITLE
Crash while adding a new instance variable

### ISSUE THREAD

**Issue by ecations** [Scirra/Construct-3-bugs#3505]
Construct 3 crashed when I tried to add a new instance variable to an object. Another object already had that same variable name too (but that shouldn't really be a problem). Below is the crash information from Construct:

Error report information
Type: unhandled rejection
Reason: Error: name already in object class namespace @ Error: name already in object class namespace at t.ǃ$d (https://editor.construct.net/r171-3/projectResources.js:1:127845) at https://editor.construct.net/r171-3/projectResources.js:1:1084424
Stack: Error: name already in object class namespace at t.ǃ$d (https://editor.construct.net/r171-3/projectResources.js:1:127845) at https://editor.construct.net/r171-3/projectResources.js:1:1084424
Construct 3 version: r171.3
URL: https://editor.construct.net/
Date: Tue Nov 26 2019 20:26:08 GMT+0200 (Itä-Euroopan normaaliaika)
Uptime: 83044 s

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
I'm afraid we have no way to investigate this from this information alone. Please see the bug report guidelines to make sure we can help.
