### ISSUE TITLE
"Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

### ISSUE THREAD

**Issue by gippleup** [Scirra/Construct-3-bugs#3507]
## Problem description

I can't open the project.

It started about a week ago.

When I tried to open the project through 'cloud', the error message showed up. But it worked fine through 'file system'.

So I downloaded the project from the cloud and opened the project through file system.

It's been like this for a week.

But now, I can't open the project through file system, too.

To find the cause, I checked if my project uses any third-party plugin.
But, no. I don't use it.

As far as I can remember, I modified a few functions and variables in the project. Because I can't open the afftected project, I only can tell what I remember.

The functions that I modified were:

> 1. [ePlayscene] - [Playscene] - [Generation_Target] - "enableRandomButton"
> 2. [ePlayscene] - [Playscene] - [Control] - "setButtonTouched"
> 3. [ePlayscene] - [Playscene] - [Control] - "checkifCorrect"

above functions exists on both projects.

> 4. [ePlayscene] - [Playscene] - [Control] - "setButtonPosition"

this function exist only on the affected project.

and the variables that I modified were

> 1. [ePlayscene] - "isColorMode"
> 2. [ePlayscene] - "controlPositionType"

these variables are added to the affected project, but not in the previous version of the project.

**Unusual thing that I did was using lots of 'undo's and 'redo's.** I guess it has something to do with the problem because I saw this pattern - an error occurs after lots of 'undo's and 'redo's, and the project get unable to be opened through cloud but able to be opened through file system - at least 7 or 8 times.

## Attach a .c3p

This is the previous version of the project which cannot be opened through cloud but able to be opended through file system.

This is the latest version of the project which cannot be opened through both(cloud and file) system.

Both projects are quite large to see through, but I guess it has less linkage to events or variables. I guess the problem is more linked to the system which handles the changes of variable because I experienced the same problem with much smaller project. It occured mainly when I uses lots of 'redo's and 'undo's.

## Steps to reproduce

1. Open .c3p file

## Observed result

Can't open the project.

## Expected result

I want to open the project through cloud and file system without any error message.

## More details

**Affected browsers/platforms:** 
Chrome/Firefox

**First affected release:** 
Not this projuect, but it happened with r164.3, too.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 69 gb
Storage usage (approx): 283 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 610 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by gippleup** [comment]
I just decided to make it again.

**Comment by shortercode** [comment]
@gippleup if you can replicate this issue then we would be interested in investigating it, as we take any issues with project corruption very seriously.

Ideally you would provide the steps that you took to produce the broken project, as well as the broken project file itself so we can investigate what is wrong with it. Even if you cannot open a project you can download it from the open project dialog by right clicking and choosing "download". Also you should be able to download the project via the web interface for whatever cloud service your using.
