### ISSUE TITLE
Quite a few bugs on my Huawei P8 Lite

### ISSUE THREAD

**Issue by mfoster98** [Scirra/Construct-3-bugs#351]
## Problem description

Here are a few bugs I've ran into while using Android.

When typing in value boxes during adding an event (eg. adding a variable comparison equal to Score will make it SScScoScorScore just by typing Score on my phone's keyboard)  This has happened on more than 1 occasion and makes making games on my phone harder than it has to be.

Loss of work due to Android back button not working with the engine.  Now this one is down to my own stupidity but it's quite annoying.  Say I'm adding an event and click into the wrong objects events and so I want to go back to the object picker and I press the system back button instead of the engine's back button and I haven't saved my work when the engine closes down and restarts when opened back up from my phones task manager.

On Fade Out finished triggers too quickly and not when the fade out has actually finished.  This is quite an annoying bug haha. 

## Attach a .c3p

These are general bugs and should appear on normal 

## Steps to reproduce

= For problem 1 =
1. Create a variable on android mobile
2. Create a variable comparison event and start typing an expression
3. The bug should then occur.

= For problem 2=
1. Create a new event
2. Go into System for example
3. Press your phone system's back button
4. Shuts down the engine and has to be restarted from scratch.  Losing any unsaved work.

= For problem 3 = 
1. Create a sprite and assign the fade behaviour
2. Create an event that calls On Fade Out Finished
3. Create a variable (Int)
4. Have 1 added to the variable when fade out finishes
5. The variable will add 1 before the fade out is finished (Seen via Every tick event setting text to the variable value)

## Observed result

Mentioned above for each problem

## Expected result

Problem 1:  I expected to be able to write expressions without it adding any text that I haven't told it to.
Problem 2: I do expect it to quit the engine but I think that it should do the same as the engine's back button.
Problem 3: The variable should only have 1 added to it when the fade out has actually finished and the sprite is off the screen/destroyed.  In my case I can't just use the On Destroyed event as I am already using it for doing something else and it wouldn't work as I want it to.

## Affected browsers

* Chrome: yes Zoom 100% ( Using the "Saved the Home Screen" version of the engine (Web-App I think it's called)

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r29.2

Local storage
Storage quota (approx): 39 gb
Storage usage (approx): 38 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7900 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_get_buffer_sub_data_async
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by mfoster98** [comment]
Sorry this is such a big bug report I just felt it was better putting them all in one instead of individual reports.

**Comment by AshleyScirra** [comment]
Please file separate bugs for each individual issue. It's harder to track bugs if you put them all in one, because we can't close them individually, can't assign them to different people, can't label them differently, etc.

**Comment by mfoster98** [comment]
Okay no problem

**Comment by mfoster98** [comment]
- Created separate bug reports (Closing original?)
