### ISSUE TITLE
IOS 13 and Tilt doesn't work

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#3510]
## Problem description

iOS 13 and Tilt (Touch.Beta) doesn't work, on iOS 12.4 its no problem.

## Attach a .c3p

[a_Tilt_Bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3912007/a_Tilt_Bug.c3p.zip)

## Steps to reproduce

1. export the project to Xcode- I tested with two version without success:

v1: deduplicate images, recompress images activated- minify mode advanced
min Version 12.0 - xcode project - hide status bar activated

v2: deduplicate images, recompress images  NOT activated- minify mode None
min Version 12.0 - xcode project - hide status bar, require vibrate and camera permission activated

no difference in the result

2. open project in Xcode (Version 11.2.1 (11B500))- update to recommended settings- no other changes

3. run on attached device

## Observed result

on a iOS 13.2.3 device there is written on the screen "Tilt: 0"

## Expected result

the Tilt number should not be 0 but the actual touch.Beta number - works on iOS 12

## More details

exported it with latest Beta r178 but the problem was here already with stable r171.3

**Affected browsers/platforms:** 

I work in Chrome, on Mac OS 10.14.6 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r178 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 66 gb
Storage usage (approx): 933 mb (1.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The project doesn't request orientation permission, which is now required on iOS 13+. Use the *Request permission* action before trying to read the values. Note this must be done in a user input event. For an example see the *Infinite jumping* template.

**Comment by bubbblebub** [comment]
thanks Ashley, I see. In the Infinite jumping example, each time I start the app, I have to give again the permission - is it possible to save somehow the information that the user gave the permission, so it has to be done only once? I am asking because this pop up request gives a bit an unclean experience.

**Comment by AshleyScirra** [comment]
I don't think so, it's entirely handled by the browser. Last I tried it Safari did remember the setting.
