### ISSUE TITLE
Multiplayer plugin error while using c2 runtime.

### ISSUE THREAD

**Issue by El3mancer** [Scirra/Construct-3-bugs#3515]
## Problem description
Multiplayer plugin error while using c2 runtime.

## Attach a .c3p

https://www.dropbox.com/s/5qxcxh5ow6j35v2/bug%20report.c3p?dl=0

## Steps to reproduce
Open project with 2 tabs in browser, wait few seconds still they connect and when error show up.
Error just show up when a player join room.

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Even on "clear cut" issues it's important to provide as much information as possible. If you have the exact conditions for a bug, but we don't, it can use up a lot of time on our part finding out the exact problem.

I saw something similar on the forums so I guess your the same user. It would have been useful if you provided: the stacktrace from the error, your system details and a link to the forum post.

**Comment by AshleyScirra** [comment]
It looks like there was a typo in the C2 runtime multiplayer code. It should be fixed for the next release.
