### ISSUE TITLE
Clicking "+" on Timeline bar may crash if no instances exist.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3517]
## Problem description

Clicking the "+" on the Timeline bar crashes if there are no Timeline instances... I think.

## Attach a .c3p

Every project should present it.

## Steps to reproduce

1. Create new project.
2. Click the "+" in the Timeline bar.

## Observed result

Crash.

## Expected result

Some type of warning.

## More details

**Affected browsers/platforms:** Chrome, maybe others.
**First affected release:** 178, maybe sooner.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: dialog name 'PickTimelineInstances' not found @ Error: dialog name 'PickTimelineInstances' not found at Function.ǃRRY (https://editor.construct.net/r178/main.js:2:293901) at Function.ǃRK (https://editor.construct.net/r178/main.js:2:301728) at h.ǃEt (https://editor.construct.net/r178/main.js:210:65781) at h.ǃEP (https://editor.construct.net/r178/main.js:210:65919) at h.ǃhwd (https://editor.construct.net/r178/components/bars/timelineBar/timelineBar.js:1:10854) at Object.ǃRJD (https://editor.construct.net/r178/components/bars/timelineBar/timelineBar.js:1:8529) at Object.ǃRJP (https://editor.construct.net/r178/main.js:2:517448) at Object.ǃRrB (https://editor.construct.net/r178/main.js:2:552910) at Object.ǃRrA (https://editor.construct.net/r178/main.js:2:550913) at https://editor.construct.net/r178/main.js:2:550709
Stack: Error: dialog name 'PickTimelineInstances' not found at Function.ǃRRY (https://editor.construct.net/r178/main.js:2:293901) at Function.ǃRK (https://editor.construct.net/r178/main.js:2:301728) at h.ǃEt (https://editor.construct.net/r178/main.js:210:65781) at h.ǃEP (https://editor.construct.net/r178/main.js:210:65919) at h.ǃhwd (https://editor.construct.net/r178/components/bars/timelineBar/timelineBar.js:1:10854) at Object.ǃRJD (https://editor.construct.net/r178/components/bars/timelineBar/timelineBar.js:1:8529) at Object.ǃRJP (https://editor.construct.net/r178/main.js:2:517448) at Object.ǃRrB (https://editor.construct.net/r178/main.js:2:552910) at Object.ǃRrA (https://editor.construct.net/r178/main.js:2:550913) at https://editor.construct.net/r178/main.js:2:550709
Construct 3 version: r178
URL: https://editor.construct.net/r178/
Date: Tue Dec 03 2019 11:42:10 GMT-0300 (Horário Padrão de Brasília)
Uptime: 6134.5 s

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r178 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
This has been going on for a while now, not to sure why. Since it is a transient issue, I imagine people that see it, do so once then refresh the app and never see it again.

**Comment by AshleyScirra** [comment]
I think we eventually figured out what's behind this and we've adjusted some loading code to ensure it doesn't happen again. Marking as 'check next release' since we should verify this by looking at crash reports.

**Comment by AshleyScirra** [comment]
This should be fixed in r181.2. @dupuqub - are you able to verify it's fixed there?

**Comment by dupuqub** [comment]
it is fixed :)

**Comment by AshleyScirra** [comment]
Thanks for confirming!
