### ISSUE TITLE
Dragging track folders in Timeline bar will cause a crash

### ISSUE THREAD

**Issue by allyoe3** [Scirra/Construct-3-bugs#3518]
## Problem description

Construct 3 stops working when trying to change track folders order.

## Attach a .c3p
[Timeline2.zip](https://github.com/Scirra/Construct-3-bugs/files/3917422/Timeline2.zip)

## Steps to reproduce

1. Open included .c3p file **OR** create a new timeline and add some track folders
2. Try to switch two track folders order by dragging them with mouse
![crash1](https://user-images.githubusercontent.com/56956534/70065203-48d4f500-161d-11ea-9706-e960af5556b6.png)

## Observed result
![crash2](https://user-images.githubusercontent.com/56956534/70065609-f8aa6280-161d-11ea-8da3-1674e7e1764e.png)

## Expected result

Folders order should be swapped.

## More details

**Affected browsers/platforms:**
Chrome, Chrome Web App, Windows 10 App (beta)

**First affected release:**
178 (approximately)

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r178/projectResources.js, line 1, col 575013
Message: Uncaught TypeError: j.ǃjeU is not a function or its return value is not iterable
Stack: TypeError: j.ǃjeU is not a function or its return value is not iterable at https://editor.construct.net/r178/projectResources.js:1:575013 at Array.map () at new (https://editor.construct.net/r178/projectResources.js:1:574999) at Object.ǃhZh (https://editor.construct.net/r178/components/bars/timelineBar/timelineBar.js:1:115673) at Object.ǃhk_ (https://editor.construct.net/r178/components/bars/timelineBar/timelineBar.js:1:114159) at HTMLDivElement. (https://editor.construct.net/r178/components/bars/timelineBar/timelineBar.js:1:110889) at HTMLDocument. (https://editor.construct.net/r178/main.js:2:193503)
Construct 3 version: r178
URL: https://editor.construct.net/r178/
Date: Tue Dec 03 2019 22:35:01 GMT+0700 (Индокитай)
Uptime: 36.3 s

Platform information
Browser: Chrome
Browser version: 73.0.0.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Iridium/2019.04 Safari/537.36 Chrome/73.0.0.0
C3 release: r178 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
