### ISSUE TITLE
[r31] Button hidden by dropdown in expression dialog, ESC not closing dropdown

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#352]
## Problem description

I copy pasted some text and the dropdown appeared for me to select stuff. However, the dropdown was above the Done button. Pressing Enter would just select whatever is selected in the dropdown and I'd have random stuff written. Pressing Esc didn't close the dropdown like it should normally.

## Attach a .c3p

![hiddenbutton](https://cloud.githubusercontent.com/assets/7268697/26421288/2cb69b84-40ce-11e7-9719-068ec83b501d.gif)

## Steps to reproduce

1. create a project
2. make some long named variables
3. make an expression
4. use the variables in the expression using copy-paste

## Observed result

The dropdown is on top of buttons, which is fine, however the ESC key does not close it.

## Expected result

I expect the Esc key to close the dropdown. I think it does it in C2.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 195 mb (1.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
There isn't a .c3p so I tested with Ghost Shooter, and I could always close autocomplete with Esc. However I guess it's not useful for autocomplete to appear when pasting content, so I've changed r32 to not show autocomplete on paste.

**Comment by JeFawk** [comment]
I tested again (browser data, cache , etc reset) and I could indeed close the dropdown menu with the Esc key.
