### ISSUE TITLE
Updating Particle values via Function requires a Wait action to work

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#3521]
## Problem description
Hi. I use an array to store particle values like size, speed etc. and call a function to assign them to the used Exhaust in my game. It works fine in the garage with a fixed exhaust object but when I create a new exhaust object, pin it to player and then update the values it does not work until I add a short 0.1 Wait action. 

After testing it in a new project I found the particle values seem to be updated but not used. Only when I add a short wait the particles are properly updated. Without wait the example shows different values but show the same result (default values). 

## Attach a .c3p
[SetParticleValuesWithFunction.zip](https://github.com/Scirra/Construct-3-bugs/files/3921523/SetParticleValuesWithFunction.zip)

## Steps to reproduce

1. use function to set particle values

## Observed result
Values I get from object change but dont change the behavior until a Wait is added

## Expected result
It should update without the extra wait action

## More details

Tap once to spawn without wait, double tap to spawn with 0.1 wait in function.

**Affected browsers/platforms:** 

**First affected release:** 
178
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r178 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 20 gb
Storage usage (approx): 1.2 gb (5.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 615 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I think this is just down to picking, newly created instances don't go into the main group until the following tick. Normally creating a new instance will pick it specifically, which allows you to modify it's values. But picked instances are reset inside of a function call. Hence you are seeing:

- destroy all global particle instances
- create instance
- pick new particle instance
- call function
  - pick all global particles
  - modify particles // none picked
- add new particle instance to global particles

By adding the wait you are ensuring the new instances is added to the global particle group before modifying them

In my projects I will either create the new instance inside the function, or pass the UID of the instance to the function as a parameter and then pick using the UID. I modified your example to demonstrate the latter.

[SetParticleAfterWait.zip](https://github.com/Scirra/Construct-3-bugs/files/3921619/SetParticleAfterWait.zip)

**Comment by AshleyScirra** [comment]
This is just another variant of "newly created objects aren't fully created until the end of the next top level event". Using a function you essentially try to run an action on an unpicked instance that has not yet finished creating, so the action does not actually run. Adding a 'Wait 0 seconds' will delay until the end of the event sheet when the instance has finished creating and so work correctly.

As noted you can pass the UID of the instance to pick to work around this, or alternatively use a function to both create and set the properties for the instance in the same event, avoiding the problem completely.
