### ISSUE TITLE
Error when navigating back from a condition using a family (only on beta)

### ISSUE THREAD

**Issue by hcatarrunas** [Scirra/Construct-3-bugs#3525]
## Problem description
When trying to change a condition from a family, the editor shows an arrow to go back and crashes.

## Attach a .c3p
c3p: https://www.dropbox.com/s/4coukjf46jt517a/BackFromFamily.c3p?dl=0
video: https://www.dropbox.com/s/elxqlhbcbm708vo/BackFromFamily.mkv?dl=0

## Steps to reproduce (video description)
1. On the beta version of the editor try to change a condition using a family
2. Go back till the interface shows an Arrow to the left
3. On trying the arrow the editor crashes.

## Observed result
On trying the arrow the editor crashes.

## Expected result
I believe the editor should have been showing the list of objects. It works ok on the non beta editor.

**Comment by AshleyScirra** [comment]
Thanks, well spotted. This was accidentally broken when we added the family folders feature. It should be fixed in the next release.
