### ISSUE TITLE
A function that returns a string cannot be called

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3527]
## Problem description

As in the image below, one of the functions cannot be found in the action section, therefore it cannot be called.

"Write_Story" returns a string and "Skip_Story" returns nothing, and as you can see they are both empty, this is their only difference.

Also I'm trying to call them through a keyboard press event.

![image](https://user-images.githubusercontent.com/34659544/70260837-e3dde400-176f-11ea-82fb-caaa984260fe.png)

## Attach a .c3p

Any project should present it.

## Steps to reproduce

1. Add a function
2. Make it return a string
3. It won't be callable

## Observed result

A function not being callable.

## Expected result

Being able to call it.

## More details

**Affected browsers/platforms:** Chrome, maybe others.
**First affected release:** 178, maybe sooner

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r178 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 138 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Functions that return values can only be called as expressions, not actions
at the moment.

**Comment by dupuqub** [comment]
I just realized that this is maybe not a bug at all, just a quirk because there is really nowhere the returned value can go, maybe should be closed?

**Comment by AshleyScirra** [comment]
As noted it is currently by design that functions returning a value are used as expressions, not actions. We don't normally investigate reports without a .c3p project anyway.
