### ISSUE TITLE
Condition Interface Error (r178)

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#3528]
Issue:  If I click back when viewing the objects to select from when adding or modifying a condition it will throw this error every time if I do it relatively quickly and if there are enough families to have more than 1 condition page (aka if you can click the back button (the big arrow-included back button to go to another condition page.)

1) Create 20 ish families (however many are required to get more than 1 condition interface page when modifying or adding conditions)

2) Once you have clicked a family object from the 2nd condition page and are now in the objects list of conditions, then click back to get to the conditions page and then click the back arrow button to get to the 1st condition page: this if it is not an exclusive situation, should throw the error.

Here is the project with the families already set up: [New project.zip](https://github.com/Scirra/Construct-3-bugs/files/3931936/New.project.zip)

**Error Report**

Error report information
Type: unhandled exception
File: https://editor.construct.net/r178/projectResources.js, line 1, col 1152201
Message: Uncaught TypeError: Cannot read property 'ǃDq' of null
Stack: TypeError: Cannot read property 'ǃDq' of null at Object.ǃmkd (https://editor.construct.net/r178/projectResources.js:1:1152201) at Object.ǃUhh (https://editor.construct.net/r178/projectResources.js:1:1151732) at Object.ǃjIc (https://editor.construct.net/r178/projectResources.js:1:1150785) at Object.ǃmAL (https://editor.construct.net/r178/main.js:2:212146) at Object.ǃlv (https://editor.construct.net/r178/main.js:2:212024) at Object.ǃUjl (https://editor.construct.net/r178/projectResources.js:1:1153547) at https://editor.construct.net/r178/projectResources.js:1:1153335
Construct 3 version: r178
URL: https://editor.construct.net/r178/
Date: Fri Dec 06 2019 04:16:18 GMT-0700 (Mountain Standard Time)
Uptime: 223 s

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r178 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon(TM) Vega 8 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
This looks like the same issue as #3525 which is already fixed, so closing as duplicate.
