### ISSUE TITLE
C3 Crashed when loading an image to a new frame

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-3-bugs#353]
## Problem description
Reporting crash as requested by pop-up prompt.

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

I opened up a sprite in the sprite editor.
The sprite had a single frame on a single animation. 
I added a new blank frame, opened the load an image window and added the image.
The image was added correctly.
I closed the editor window.

Reproduced once, can't reproduce again.

## Observed result

The game crashed and generated an error report

## Expected result

No crash :)

## Affected browsers

Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r31/main.js, line 61, col 128784
Message: Uncaught Error: image sprite collection needs rebuilding
Stack: Error: image sprite collection needs rebuilding at ie.ǃMm (https://editor.construct.net/r31/main.js:61:128790) at oe.ǃMm (https://editor.construct.net/r31/main.js:61:201174) at a.ǃUc.ǃMY (https://editor.construct.net/r31/main.js:61:398994) at a.ǃUc.ǃMY (https://editor.construct.net/r31/plugins/sprite/plugin.js:1:8650) at a.ǃUc.ǃME (https://editor.construct.net/r31/plugins/sprite/plugin.js:1:8450) at ne.ǃME (https://editor.construct.net/r31/main.js:61:218276) at ae.ǃME (https://editor.construct.net/r31/main.js:61:253834) at de.ǃME (https://editor.construct.net/r31/main.js:61:239467) at window.ǃDA.ǃxN (https://editor.construct.net/r31/components/editors/layoutView/layoutView.js:1:6834) at ǃxT.$ (https://editor.construct.net/r31/components/editors/layoutView/layoutView.js:1:2083)
Construct 3 version: r31
URL: https://editor.construct.net/index.html
Date: Wed May 24 2017 20:18:46 GMT+0100 (GMT Summer Time)
Uptime: 8357.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

Error report information
Type: unhandled exception
File: https://editor.construct.net/r31/main.js, line 61, col 128784
Message: Uncaught Error: image sprite collection needs rebuilding
Stack: Error: image sprite collection needs rebuilding at ie.ǃMm (https://editor.construct.net/r31/main.js:61:128790) at oe.ǃMm (https://editor.construct.net/r31/main.js:61:201174) at a.ǃUc.ǃMY (https://editor.construct.net/r31/main.js:61:398994) at a.ǃUc.ǃMY (https://editor.construct.net/r31/plugins/sprite/plugin.js:1:8650) at a.ǃUc.ǃME (https://editor.construct.net/r31/plugins/sprite/plugin.js:1:8450) at ne.ǃME (https://editor.construct.net/r31/main.js:61:218276) at ae.ǃME (https://editor.construct.net/r31/main.js:61:253834) at de.ǃME (https://editor.construct.net/r31/main.js:61:239467) at window.ǃDA.ǃxN (https://editor.construct.net/r31/components/editors/layoutView/layoutView.js:1:6834) at ǃxT.$ (https://editor.construct.net/r31/components/editors/layoutView/layoutView.js:1:2083)
Construct 3 version: r31
URL: https://editor.construct.net/index.html
Date: Wed May 24 2017 20:31:04 GMT+0100 (GMT Summer Time)
Uptime: 616.9 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Sorry, we need reliable steps to reproduce to be able to fix bugs. Please let us know if you can find a way to make it happen reliably.

**Comment by jakemay74** [comment]
Hi Ashley, will do, tried to get a repro with a minimal file but no success.  

Incidentally, when you get a crash such as this that generates a report it asks you to log the bug and post the report, which is what I did in this instance.  Do you still want these reported if I can't get a reliable repro? I'd have thought the report was useful by itself, but if not I won't bother unless I can reproduce.

**Comment by AshleyScirra** [comment]
Bug reports are generally not useful unless they provide reliable steps to reproduce. Please see the guidelines for more information.

**Comment by jakemay74** [comment]
@AshleyScirra
Understood, I've already read the guidelines (and worked in QA for a number of years so I'm kinda au fait with how to report bugs :) ), however the wording on the crash report pop-up makes it sound like you want the reports regardless. I'll hold off sending from now on unless I can get a reproducible.
