### ISSUE TITLE
Advanced minification - Properties of runtime.objects are not marked as enumerable

### ISSUE THREAD

**Issue by rhg1968** [Scirra/Construct-3-bugs#3530]
## Problem description

When using script files I created a simplified Entity Control System that enumerates over the runtime.objects collection looking for objects that contain certain components. This works fine with no and simple minification. 
However, when I switch to advanced minification the keys of the runtime.object comes back as an empty array. I am using Object.keys(). If I switch to a method that looks over non-enumerable keys, like Object.getOwnPropertyNames() ,  it works in all minification scenarios. 

## Attach a .c3p

[TestAdvanceMin.zip](https://github.com/Scirra/Construct-3-bugs/files/3935130/TestAdvanceMin.zip)

## Steps to reproduce

1.  Download the attached file and change it's extension back to c3p
2.  Open the project in r178
3.  Press F4 or export the project to html, with no minification, and run in a web server. The console will log 3 items iterated.
4.  Export the project to Html with advanced minification and run in a web server and run.

## Observed result

With advanced minifcation the console will log 0 properties enumerated of the runtume.objects object

## Expected result

It should have logged 3 items, just with no and simple minification

## More details
This appears to be an issue that properties of the runtime.objects object are getting marked non-enumerable during property mangeling .

This problem can be resolved by using a method that iterates over non-enumerable properties as well, like Object.getOwnPropertyNames() 

**Affected browsers/platforms:** 
I have only tested this in Chrome 78.0.3904.108

**First affected release:** 
r178 is the only version I have tested this in.

## System details
No error message associated with this issue.

<details><summary>View details</summary>

N/A

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report. It turns out the `enumerable` property in our code was accidentally being mangled by advanced minification and so stopped taking effect. This is fixed for the next release so it stays the same and the enumerability is preserved. (Note after advanced minification different property names are logged, but this is the [intended effect](https://www.construct.net/en/make-games/manuals/construct-3/scripting/guides/advanced-minification).)
