### ISSUE TITLE
Mobile Advert not building on Cordova!

### ISSUE THREAD

**Issue by gberenst** [Scirra/Construct-3-bugs#3531]
## Problem description

We have always built our project without any issues. Now added the MobileAdvert plugin and fails building in both Cordova CLI and PhoneGap. Also fails in C3 cloud build service. If we remove plugin it builds fine.

## Attach a .c3p

https://drive.google.com/open?id=1aRtv_uP2q1mHFeUFvZbByEIjAKVDnqcS

## Steps to reproduce

For example, in cordova CLI
1.  Export from C3 as cordova project
2. make Cordova Build in Cordova CLI
3. Build fails with error.

## Observed result

It fails, log says:
Android Studio project detected
ENOENT: no such file or directory, open 'C:\cordova\PROJECT_NAME\platforms\android\gradle.properties'

## Expected result

Succesful APK build

## More details

Built with android 7.1.1 in Cordova CLI. However it takes latest android in PhoneGap Build and fails too.
Cordova Version; 9.0.0 (cordova-lib@9.0.1)
Cordova plugin version: construct-mobile-advert 1.5.1 "ConstructAd"

**Comment by shortercode** [comment]
I tried exporting your project via the build service and had no issue.

As noted in the comments of #3504 cordova exports in r178 are importing construct-mobile-advert@1.5.1, but it should be using 1.5.2 which corrects some issues.

I've updated the version for the next release, but you should be able to use the newer version by changing the plugin version in the config.xml to 1.5.2 before running cordova prepare.

**Comment by gberenst** [comment]
THank you Iain, I´ve changed to 1.5.2 in the exported config.xml, created a
new cordova project, but still same issue when adding android platform.
Here´s the log. Any idea?

Using cordova-fetch for cordova-android@7.1.1
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.paukgames.wordshapes
        Name: Word_Shapes
        Activity: MainActivity
        Android target: android-27
Android project created with cordova-android@7.1.1
Android Studio project detected
Android Studio project detected
Plugin 'cordova-plugin-inappbrowser' found in config.xml... Migrating it to
package.json
Plugin 'construct-mobile-advert' found in config.xml... Migrating it to
package.json
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to
package.json
Plugin 'construct-plugin-file' found in config.xml... Migrating it to
package.json
Plugin 'cordova-plugin-fullscreen' found in config.xml... Migrating it to
package.json
Plugin 'construct-mobile-notchfix' found in config.xml... Migrating it to
package.json
Discovered saved plugin "cordova-plugin-inappbrowser". Adding it to the
project
Installing "cordova-plugin-inappbrowser" for android
Adding cordova-plugin-inappbrowser to package.json
Discovered saved plugin "construct-mobile-advert". Adding it to the project
Installing "construct-mobile-advert" for android
Subproject Path: CordovaLib
Subproject Path: app
Adding construct-mobile-advert to package.json
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for android
Adding cordova-plugin-whitelist to package.json
Discovered saved plugin "construct-plugin-file". Adding it to the project
Installing "construct-plugin-file" for android

The Android Persistent storage location now defaults to "Internal". Please
check this plugin's README to see if your application needs any changes in
its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an
"AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation"
value="Compatibility" />"

to config.xml in order for the application to find previously stored files.

Adding construct-plugin-file to package.json
Discovered saved plugin "cordova-plugin-fullscreen". Adding it to the
project
Installing "cordova-plugin-fullscreen" for android
Adding cordova-plugin-fullscreen to package.json
Discovered saved plugin "construct-mobile-notchfix". Adding it to the
project
Installing "construct-mobile-notchfix" for android
Adding construct-mobile-notchfix to package.json
ENOENT: no such file or directory, open
'C:\cordova\ws2\platforms\android\gradle.properties'

**Comment by gberenst** [comment]
Just to add info, here´s the plugin list of the projects:

C:\cordova\ws2>cordova plugin list
construct-mobile-advert 1.5.2 "ConstructAd"
construct-mobile-notchfix 1.0.2 "NotchPatch"
construct-plugin-file 1.0.0 "File"
cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-whitelist 1.3.4 "Whitelist"

C:\cordova\ws2>cordova prepare
Android Studio project detected
ENOENT: no such file or directory, open
'C:\cordova\ws2\platforms\android\gradle.properties'

**Comment by shortercode** [comment]
Tried here and had no issues I'm afraid. Perhaps try running `cordova --verbose prepare` ? I'm using the same version of cordova CLI as you, but mine is resolving to cordova-android@8.1.0, so I'm thinking it's down to the version variation.

**Comment by gberenst** [comment]
Sorry Iain, I´ve downgraded cordova to 8.1.0, error persist. Also when
building on phonegap we get the following error which is not shown when
removing that plugin:

Build Date: 2019-12-10 08:28:03 +0000
--------------------------------------------------------------------------------
PREPARE OUTPUT
--------------------------------------------------------------------------------
Generating platform-specific config.xml from defaults for android at
/var/gimlet/tmp/47052611752920/383294/app/src/main/res/xml/config.xml
Merging project's config.xml into platform-specific android config.xml
[Gradle Properties] Preparing Configuration
[Gradle Properties] File missing, creating file with Cordova defaults.
[Gradle Properties] Appending default configuration properties
[Gradle Properties] Appending configuration item: org.gradle.daemon=true
[Gradle Properties] Appending configuration item: org.gradle.jvmargs=-Xmx2048m
[Gradle Properties] Appending configuration item: android.useDeprecatedNdk=true
[Gradle Properties] Appending custom configuration properties
[Gradle Properties] Appending configuration item: cdvMinSdkVersion=21
[Gradle Properties] Updating and Saving File
Merging and updating files from [www, ../platform_www] to
../app/src/main/assets/www
  copy  www/arrayabc.json ../app/src/main/assets/www/arrayabc.json (new file)
  copy  www/arraylanguages.json
../app/src/main/assets/www/arraylanguages.json (new file)
  copy  www/arrayletters.json
../app/src/main/assets/www/arrayletters.json (new file)
  copy  www/arrayspecialletters.json
../app/src/main/assets/www/arrayspecialletters.json (new file)
  copy  www/arraytips.json ../app/src/main/assets/www/arraytips.json (new file)
  mkdir ../app/src/main/assets/www/cordova-js-src
  mkdir ../app/src/main/assets/www/cordova-js-src/android
  copy  ../platform_www/cordova-js-src/android/nativeapiprovider.js
../app/src/main/assets/www/cordova-js-src/android/nativeapiprovider.js
(new file)
  copy  ../platform_www/cordova-js-src/android/promptbasednativeapi.js
../app/src/main/assets/www/cordova-js-src/android/promptbasednativeapi.js
(new file)
  copy  ../platform_www/cordova-js-src/exec.js
../app/src/main/assets/www/cordova-js-src/exec.js (new file)
  copy  ../platform_www/cordova-js-src/platform.js
../app/src/main/assets/www/cordova-js-src/platform.js (new file)
  mkdir ../app/src/main/assets/www/cordova-js-src/plugin
  mkdir ../app/src/main/assets/www/cordova-js-src/plugin/android
  copy  ../platform_www/cordova-js-src/plugin/android/app.js
../app/src/main/assets/www/cordova-js-src/plugin/android/app.js (new
file)
  copy  ../platform_www/cordova.js
../app/src/main/assets/www/cordova.js (updated file)
  delete ../app/src/main/assets/www/css (no source)
  delete ../app/src/main/assets/www/css/index.css (no source)
  copy  www/data.json ../app/src/main/assets/www/data.json (new file)
  mkdir ../app/src/main/assets/www/fonts
  copy  www/fonts/aqua.ttf ../app/src/main/assets/www/fonts/aqua.ttf (new file)
  copy  www/fonts/gilroy-extrabold.otf
../app/src/main/assets/www/fonts/gilroy-extrabold.otf (new file)
  mkdir ../app/src/main/assets/www/icons
  copy  www/icons/default@2x~universal~anyany.png
../app/src/main/assets/www/icons/default@2x~universal~anyany.png (new
file)
  copy  www/icons/icon-128.png
../app/src/main/assets/www/icons/icon-128.png (new file)
  copy  www/icons/icon-16.png
../app/src/main/assets/www/icons/icon-16.png (new file)
  copy  www/icons/icon-256.png
../app/src/main/assets/www/icons/icon-256.png (new file)
  copy  www/icons/icon-32.png
../app/src/main/assets/www/icons/icon-32.png (new file)
  copy  www/icons/icon-512.png
../app/src/main/assets/www/icons/icon-512.png (new file)
  copy  www/icons/icon-64.png
../app/src/main/assets/www/icons/icon-64.png (new file)
  copy  www/icons/loading-logo.png
../app/src/main/assets/www/icons/loading-logo.png (new file)
  mkdir ../app/src/main/assets/www/images
  copy  www/images/alert_icon-sheet0.png
../app/src/main/assets/www/images/alert_icon-sheet0.png (new file)
  copy  www/images/avatars-sheet0.png
../app/src/main/assets/www/images/avatars-sheet0.png (new file)
  copy  www/images/avatars-sheet1.png
../app/src/main/assets/www/images/avatars-sheet1.png (new file)
  copy  www/images/avatars-sheet2.png
../app/src/main/assets/www/images/avatars-sheet2.png (new file)
  copy  www/images/avatars-sheet3.png
../app/src/main/assets/www/images/avatars-sheet3.png (new file)
  copy  www/images/bg_timer-sheet0.png
../app/src/main/assets/www/images/bg_timer-sheet0.png (new file)
  copy  www/images/bgpoints-sheet0.png
../app/src/main/assets/www/images/bgpoints-sheet0.png (new file)
  copy  www/images/bgwords-sheet0.png
../app/src/main/assets/www/images/bgwords-sheet0.png (new file)
  copy  www/images/bgwords-sheet1.png
../app/src/main/assets/www/images/bgwords-sheet1.png (new file)
  copy  www/images/bgwords-sheet2.png
../app/src/main/assets/www/images/bgwords-sheet2.png (new file)
  copy  www/images/bgwords-sheet3.png
../app/src/main/assets/www/images/bgwords-sheet3.png (new file)
  copy  www/images/bonus-sheet0.png
../app/src/main/assets/www/images/bonus-sheet0.png (new file)
  copy  www/images/bonus-sheet1.png
../app/src/main/assets/www/images/bonus-sheet1.png (new file)
  copy  www/images/bonus-sheet2.png
../app/src/main/assets/www/images/bonus-sheet2.png (new file)
  copy  www/images/bonus-sheet3.png
../app/src/main/assets/www/images/bonus-sheet3.png (new file)
  copy  www/images/bonus-sheet4.png
../app/src/main/assets/www/images/bonus-sheet4.png (new file)
  copy  www/images/bonus-sheet5.png
../app/src/main/assets/www/images/bonus-sheet5.png (new file)
  copy  www/images/bulletsymbols-sheet0.png
../app/src/main/assets/www/images/bulletsymbols-sheet0.png (new file)
  copy  www/images/gameover_-sheet0.png
../app/src/main/assets/www/images/gameover_-sheet0.png (new file)
  copy  www/images/gameover_-sheet1.png
../app/src/main/assets/www/images/gameover_-sheet1.png (new file)
  copy  www/images/gift_icon-sheet0.png
../app/src/main/assets/www/images/gift_icon-sheet0.png (new file)
  copy  www/images/info_icon-sheet0.png
../app/src/main/assets/www/images/info_icon-sheet0.png (new file)
  copy  www/images/letterbonus-sheet0.png
../app/src/main/assets/www/images/letterbonus-sheet0.png (new file)
  copy  www/images/lettershape-sheet0.png
../app/src/main/assets/www/images/lettershape-sheet0.png (new file)
  copy  www/images/lettershape-sheet1.png
../app/src/main/assets/www/images/lettershape-sheet1.png (new file)
  copy  www/images/lettershapesymbolbg-sheet0.png
../app/src/main/assets/www/images/lettershapesymbolbg-sheet0.png (new
file)
  copy  www/images/lettersholdercircle-sheet0.png
../app/src/main/assets/www/images/lettersholdercircle-sheet0.png (new
file)
  copy  www/images/loader-sheet0.png
../app/src/main/assets/www/images/loader-sheet0.png (new file)
  copy  www/images/loader-sheet1.png
../app/src/main/assets/www/images/loader-sheet1.png (new file)
  copy  www/images/myshapes_cirle-sheet0.png
../app/src/main/assets/www/images/myshapes_cirle-sheet0.png (new file)
  copy  www/images/myshapes_cirle-sheet1.png
../app/src/main/assets/www/images/myshapes_cirle-sheet1.png (new file)
  copy  www/images/progress_points-sheet0.png
../app/src/main/assets/www/images/progress_points-sheet0.png (new
file)
  copy  www/images/progress_points-sheet1.png
../app/src/main/assets/www/images/progress_points-sheet1.png (new
file)
  copy  www/images/progress_points-sheet2.png
../app/src/main/assets/www/images/progress_points-sheet2.png (new
file)
  copy  www/images/progress_words-sheet0.png
../app/src/main/assets/www/images/progress_words-sheet0.png (new file)
  copy  www/images/progress_words-sheet1.png
../app/src/main/assets/www/images/progress_words-sheet1.png (new file)
  copy  www/images/progress_words-sheet2.png
../app/src/main/assets/www/images/progress_words-sheet2.png (new file)
  copy  www/images/selector-sheet0.png
../app/src/main/assets/www/images/selector-sheet0.png (new file)
  copy  www/images/selector_gift_letter-sheet0.png
../app/src/main/assets/www/images/selector_gift_letter-sheet0.png (new
file)
  copy  www/images/shared-0-sheet0.png
../app/src/main/assets/www/images/shared-0-sheet0.png (new file)
  copy  www/images/shared-0-sheet1.png
../app/src/main/assets/www/images/shared-0-sheet1.png (new file)
  copy  www/images/shared-0-sheet2.png
../app/src/main/assets/www/images/shared-0-sheet2.png (new file)
  copy  www/images/shared-0-sheet3.png
../app/src/main/assets/www/images/shared-0-sheet3.png (new file)
  copy  www/images/shared-0-sheet4.png
../app/src/main/assets/www/images/shared-0-sheet4.png (new file)
  copy  www/images/shared-0-sheet5.png
../app/src/main/assets/www/images/shared-0-sheet5.png (new file)
  copy  www/images/shared-0-sheet6.png
../app/src/main/assets/www/images/shared-0-sheet6.png (new file)
  copy  www/images/shared-0-sheet7.png
../app/src/main/assets/www/images/shared-0-sheet7.png (new file)
  copy  www/images/shared-0-sheet8.png
../app/src/main/assets/www/images/shared-0-sheet8.png (new file)
  copy  www/images/shared-0-sheet9.png
../app/src/main/assets/www/images/shared-0-sheet9.png (new file)
  copy  www/images/speaker-sheet0.png
../app/src/main/assets/www/images/speaker-sheet0.png (new file)
  copy  www/images/speaker-sheet1.png
../app/src/main/assets/www/images/speaker-sheet1.png (new file)
  copy  www/images/speaker-sheet2.png
../app/src/main/assets/www/images/speaker-sheet2.png (new file)
  delete ../app/src/main/assets/www/img (no source)
  delete ../app/src/main/assets/www/img/cordova.png (no source)
  delete ../app/src/main/assets/www/img/logo.png (no source)
  copy  www/index.html ../app/src/main/assets/www/index.html (updated file)
  delete ../app/src/main/assets/www/js (no source)
  delete ../app/src/main/assets/www/js/index.js (no source)
  copy  www/lettervalues.json
../app/src/main/assets/www/lettervalues.json (new file)
  copy  www/levelinfo.json ../app/src/main/assets/www/levelinfo.json (new file)
  mkdir ../app/src/main/assets/www/media
  copy  www/media/alert.webm
../app/src/main/assets/www/media/alert.webm (new file)
  copy  www/media/bonus.webm
../app/src/main/assets/www/media/bonus.webm (new file)
  copy  www/media/gift.webm ../app/src/main/assets/www/media/gift.webm
(new file)
  copy  www/media/layouttrans.webm
../app/src/main/assets/www/media/layouttrans.webm (new file)
  copy  www/media/letter picked.webm
../app/src/main/assets/www/media/letter picked.webm (new file)
  copy  www/media/level failed.webm
../app/src/main/assets/www/media/level failed.webm (new file)
  copy  www/media/level shapes.webm
../app/src/main/assets/www/media/level shapes.webm (new file)
  copy  www/media/shuffle.webm
../app/src/main/assets/www/media/shuffle.webm (new file)
  copy  www/media/word made.webm ../app/src/main/assets/www/media/word
made.webm (new file)
  copy  www/media/word wrong.webm
../app/src/main/assets/www/media/word wrong.webm (new file)
  copy  www/media/ws background loop.webm
../app/src/main/assets/www/media/ws background loop.webm (new file)
  copy  www/noise.wasm ../app/src/main/assets/www/noise.wasm (new file)
  copy  www/palabras_diccionario.txt
../app/src/main/assets/www/palabras_diccionario.txt (new file)
  copy  www/penumbra.png ../app/src/main/assets/www/penumbra.png (new file)
  mkdir ../app/src/main/assets/www/scripts
  copy  www/scripts/c3runtime.js
../app/src/main/assets/www/scripts/c3runtime.js (new file)
  copy  www/scripts/dispatchworker.js
../app/src/main/assets/www/scripts/dispatchworker.js (new file)
  copy  www/scripts/jobworker.js
../app/src/main/assets/www/scripts/jobworker.js (new file)
  copy  www/scripts/main.js ../app/src/main/assets/www/scripts/main.js
(new file)
  copy  www/scripts/supportcheck.js
../app/src/main/assets/www/scripts/supportcheck.js (new file)
  copy  www/scripts/workermain.js
../app/src/main/assets/www/scripts/workermain.js (new file)
  copy  www/strings-da.xml ../app/src/main/assets/www/strings-da.xml (new file)
  copy  www/strings-de.xml ../app/src/main/assets/www/strings-de.xml (new file)
  copy  www/strings-en.xml ../app/src/main/assets/www/strings-en.xml (new file)
  copy  www/strings-es.xml ../app/src/main/assets/www/strings-es.xml (new file)
  copy  www/strings-fr.xml ../app/src/main/assets/www/strings-fr.xml (new file)
  copy  www/style.css ../app/src/main/assets/www/style.css (new file)
  copy  www/words_da.txt ../app/src/main/assets/www/words_da.txt (new file)
  copy  www/words_daold.txt ../app/src/main/assets/www/words_daold.txt
(new file)
  copy  www/words_de.txt ../app/src/main/assets/www/words_de.txt (new file)
  copy  www/words_en.txt ../app/src/main/assets/www/words_en.txt (new file)
  copy  www/words_es.txt ../app/src/main/assets/www/words_es.txt (new file)
  copy  www/words_es_old.txt
../app/src/main/assets/www/words_es_old.txt (new file)
  copy  www/words_es_orig.txt
../app/src/main/assets/www/words_es_orig.txt (new file)
  copy  www/words_fr.txt ../app/src/main/assets/www/words_fr.txt (new file)
  copy  www/xmldom.js ../app/src/main/assets/www/xmldom.js (new file)
  copy  www/xpath.js ../app/src/main/assets/www/xpath.js (new file)
Wrote out android application name "Word Shapes" to
/var/gimlet/tmp/47052611752920/383294/app/src/main/res/values/strings.xml
Wrote out Android package name "com.paukgames.wordshapes" to
/var/gimlet/tmp/47052611752920/383294/app/src/main/java/com/paukgames/wordshapes/WordShapes.java
Updating icons at ../app/src/main/res
  copy  www/icons/icon-64.png
../app/src/main/res/mipmap-mdpi/ic_launcher.png (new file)
  copy  www/icons/icon-128.png
../app/src/main/res/mipmap-xhdpi/ic_launcher.png (new file)
  copy  www/icons/icon-512.png
../app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (new file)
Updating splash screens at ../app/src/main/res
  delete ../app/src/main/res/drawable-land-hdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-ldpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-mdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-xhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-xxhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-land-xxxhdpi/screen.png (no source)
  copy  www/icons/default@2x~universal~anyany.png
../app/src/main/res/drawable-mdpi/screen.png (new file)
  delete ../app/src/main/res/drawable-port-hdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-ldpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-mdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-xhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-xxhdpi/screen.png (no source)
  delete ../app/src/main/res/drawable-port-xxxhdpi/screen.png (no source)
This app does not have additional resource files defined
Prepared android project successfully
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser" at "3.1.0" for android
Fetching plugin "construct-mobile-advert@1.5.2" via npm
Installing "construct-mobile-advert" at "1.5.2" for android
Subproject Path: CordovaLib
Subproject Path: app
Fetching plugin "cordova-plugin-androidx-socialsharing@1.0.0" via npm
Installing "cordova-plugin-androidx-socialsharing" at "1.0.0" for android
Fetching plugin "es6-promise-plugin@^4.1.0" via npm
Installing "es6-promise-plugin" at "4.2.2" for android
Subproject Path: CordovaLib
Subproject Path: app
Fetching plugin "construct-mobile-rate@0.4.0" via npm
Installing "construct-mobile-rate" at "0.4.0" for android
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.3.4" for android
Fetching plugin "construct-plugin-file" via npm
Installing "construct-plugin-file" at "1.0.0" for android

The Android Persistent storage location now defaults to "Internal".
Please check this plugin's README to see if your application needs any
changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify
an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation"
value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
Fetching plugin "cordova-plugin-fullscreen" via npm
Installing "cordova-plugin-fullscreen" at "1.1.0" for android
Fetching plugin "construct-mobile-notchfix" via npm
Installing "construct-mobile-notchfix" at "1.0.2" for android

--------------------------------------------------------------------------------
PROJECT PROPERTIES
--------------------------------------------------------------------------------
# This file was originally created by the Android Tools, but is now
# used by cordova-android to manage the state of the various third party
# libraries used in your application

# This is the Library Module that contains the Cordova Library, this is not
# required when using an AAR

# This is the application project.  This is only required for Android
Studio Gradle projects

# Project target.
target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=com.google.android.gms:play-services-ads:+
cordova.system.library.2=com.google.android.ads.consent:consent-library:+
cordova.system.library.3=com.android.support:support-v4:24.1.1+
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
:wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
To honour the JVM settings for this build a new JVM will be forked.
Please consider using the daemon:
https://docs.gradle.org/4.10.3/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :app
Exception while marshalling
/opt/android-sdk/build-tools/26.0.3/package.xml. Probably the SDK is
read-only
Exception while marshalling
/opt/android-sdk/build-tools/28.0.3/package.xml. Probably the SDK is
read-only
Exception while marshalling
/opt/android-sdk/extras/google/instantapps/package.xml. Probably the
SDK is read-only
Exception while marshalling
/opt/android-sdk/platform-tools/package.xml. Probably the SDK is
read-only
Exception while marshalling
/opt/android-sdk/platforms/android-28/package.xml. Probably the SDK is
read-only
Exception while marshalling
/opt/android-sdk/platforms/android-29/package.xml. Probably the SDK is
read-only
Exception while marshalling
/opt/android-sdk/build-tools/26.0.3/package.xml. Probably the SDK is
read-only
Exception while marshalling
/opt/android-sdk/build-tools/28.0.3/package.xml. Probably the SDK is
read-only
Exception while marshalling
/opt/android-sdk/extras/google/instantapps/package.xml. Probably the
SDK is read-only
Exception while marshalling
/opt/android-sdk/platform-tools/package.xml. Probably the SDK is
read-only
Exception while marshalling
/opt/android-sdk/platforms/android-28/package.xml. Probably the SDK is
read-only
Exception while marshalling
/opt/android-sdk/platforms/android-29/package.xml. Probably the SDK is
read-only

> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preReleaseBuild UP-TO-DATE
> Task :CordovaLib:checkReleaseManifest
> Task :CordovaLib:processReleaseManifest
> Task :app:preReleaseBuild
> Task :CordovaLib:compileReleaseAidl NO-SOURCE
> Task :app:compileReleaseAidl NO-SOURCE
> Task :CordovaLib:packageReleaseRenderscript NO-SOURCE
> Task :app:compileReleaseRenderscript
> Task :app:checkReleaseManifest
> Task :app:generateReleaseBuildConfig
> Task :app:prepareLintJar
> Task :app:generateReleaseSources
> Task :CordovaLib:compileReleaseRenderscript
> Task :CordovaLib:generateReleaseBuildConfig
> Task :CordovaLib:generateReleaseResValues
> Task :CordovaLib:generateReleaseResources
> Task :CordovaLib:packageReleaseResources
> Task :CordovaLib:generateReleaseRFile
> Task :CordovaLib:prepareLintJar
> Task :CordovaLib:generateReleaseSources
> Task :CordovaLib:javaPreCompileRelease

> Task :CordovaLib:compileReleaseJavaWithJavac
Note: /var/gimlet/tmp/47052611752920/383294/CordovaLib/src/org/apache/cordova/engine/SystemCookieManager.java
uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :CordovaLib:processReleaseJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
> Task :app:javaPreCompileRelease
> Task :app:mainApkListPersistenceRelease
> Task :app:generateReleaseResValues
> Task :app:generateReleaseResources
> Task :app:mergeReleaseResources
> Task :app:createReleaseCompatibleScreenManifests
> Task :app:processReleaseManifest
> Task :app:processReleaseResources

> Task :app:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :app:compileReleaseNdk NO-SOURCE
> Task :app:compileReleaseSources
> Task :app:lintVitalRelease
> Task :app:mergeReleaseShaders
> Task :app:compileReleaseShaders
> Task :app:generateReleaseAssets
> Task :CordovaLib:mergeReleaseShaders
> Task :CordovaLib:compileReleaseShaders
> Task :CordovaLib:generateReleaseAssets
> Task :CordovaLib:packageReleaseAssets
> Task :app:mergeReleaseAssets
> Task :app:validateSigningRelease
> Task :app:signingConfigWriterRelease
/.gradle/caches/transforms-1/files-1.1/play-services-ads-18.3.0.aar/239c3ddd3b48e8f3060af119824e88da/jars/classes.jar:
D8: Type `sun.misc.Unsafe` was not found, it is required for default
or static interface methods desugaring of `void
com.google.android.gms.internal.ads.zzdfs$zzi.<clinit>()`
/.gradle/caches/transforms-1/files-1.1/play-services-ads-lite-18.3.0.aar/1ff19c36af500543fa534bd88aafc2f6/jars/classes.jar:
D8: Type `libcore.io.Memory` was not found, it is required for default
or static interface methods desugaring of `void
com.google.android.gms.internal.ads.zzduy$zza.zza(long, byte)`
/.gradle/caches/transforms-1/files-1.1/play-services-ads-lite-18.3.0.aar/1ff19c36af500543fa534bd88aafc2f6/jars/classes.jar:
D8: Type `libcore.io.Memory` was not found, it is required for default
or static interface methods desugaring of `void
com.google.android.gms.internal.ads.zzduy$zzb.zza(long, byte)`
> Task :app:transformClassesWithDexBuilderForRelease

> Task :app:transformDexArchiveWithExternalLibsDexMergerForRelease FAILED
35 actionable tasks: 35 executed
D8: Program type already present:
android.support.v4.app.INotificationSideChannel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task
':app:transformDexArchiveWithExternalLibsDexMergerForRelease'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  Learn how to resolve the issue at
https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel

* Try:
Run with --stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output. Run with --scan to get full
insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
Error: /var/gimlet/tmp/47052611752920/383294/gradlew: Command failed
with exit code 1 Error output:
Note: /var/gimlet/tmp/47052611752920/383294/CordovaLib/src/org/apache/cordova/engine/SystemCookieManager.java
uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
D8: Program type already present:
android.support.v4.app.INotificationSideChannel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task
':app:transformDexArchiveWithExternalLibsDexMergerForRelease'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  Learn how to resolve the issue at
https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel

* Try:
Run with --stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output. Run with --scan to get full
insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
    at ChildProcess.whenDone
(/var/gimlet/tmp/47052611752920/383294/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by shortercode** [comment]
Sounds like you have a permission issue with the directory your Android SDK is in. There's an awful lot of "Probably the SDK is read-only" errors in there.

**Comment by gberenst** [comment]
Ok i'll check that out, and what do you think about the phonegap error?

**Comment by shortercode** [comment]
So "Android X" is a replacement for the "Android support" library, which is used by lots of things.

If your not aware Phonegap is just a wrapper around Cordova, as is our own build service.

Cordova doesn't enable Android X support by default, and requires a script to enable it. Phonegap doesn't allow you to run scripts. The build service allows scripts, but they must pass a security review first.

The reason cordova doesn't enable Android X at the moment is that if you include Android support AND Android X in the same project it cannot compile. Because you end up with duplicates which cannot be resolved. Which is the error you saw:

> Program type already present: android.support.v4.app.INotificationSideChannel

Current versions of the Google Services libraries ( such as Admob and Google Play Games ) already use Android X. Our plugins "Mobile Advert" and "Play Games" use these. So for all our plugins to work together, all of the plugins we have that used Android Support now have to use Android X. This has the side effect that none of those plugins now work on PhoneGap build.

This issue can only be resolved by cordova coming up with a fix at the tooling level, but they haven't talked about yet.

If I remember correctly the affected plugins are:
- Mobile Advert
- Mobile IAP
- Share
- Google Play

**Comment by shortercode** [comment]
@gberenst can you confirm what issues you are having on the build service? I had no trouble building your project.

**Comment by gberenst** [comment]
Ok thank you for the explanation, it all make sense now (except for mi
local cordova CLI ENOENT error), when updating to r178 it builds fine at
your scirra service. We'll have to define which way to build ios file as
yours is good but much more steps than phonegap. May be using old plugins
and javascript code inside c3p until cordova fixes the android x issue.
Thanks for your support!

**Comment by shortercode** [comment]
You should be able to use a local copy of Cordova as well, provided it's up to date.

Yes the additional steps are frustrating, but due to Apple restrictions it's impractical to set up the build server to generate IPA files. Out of interest what do you use to publish iOS applications after you have built the IPA file via PhoneGap build? As far as I'm aware you need a mac to publish an IPA to the app store, and xcode is capable of publishing a project after building the IPA.

**Comment by gberenst** [comment]
First I make certificates in Apple developer
http://docs.phonegap.com/phonegap-build/signing/ios/

2. These I use in PGB for the ipa

3. Setup the App in  Appstore in ITunes Connect.. Info, description,
icons,ect.

4. Use Xcode > Application loader on my mac for uploading the ipa

5. Back to Itunes Connect prepare for Submission

I am trying now to use old cocoon ads plugin (1.0.12 for android and 1.0.8
for ios) with scripting in C3 as an alternative to keep using phonegap.

**Comment by shortercode** [comment]
Ah okay so you are using Application Loader then. I've been keeping an eye out for a good method that users without a Mac can upload to the store. But as far as I'm aware it's not possible.

Thanks for telling me about your dev process.

Okay if we're basically labelling this issue as Phonegap Build then I will mark this as external and close it.

You may have some luck with a 3rd party advert addons for C3, several exist. If you need help with scripting then post on the C3 scripting forum, sure someone will be able to help.
