### ISSUE TITLE
SVG Not rendering in firefox. r178

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#3535]
SVG not rendering in firefox. Either in editor or in preview.

## Steps to reproduce

1. Import SVG file using construct in latest firefox stable.
2. add it to the sprite object.
3. Nothing is shown.

## Observed result

SVG's do not display using firefox.

## Expected result

Should work as in chrome.

**Comment by AshleyScirra** [comment]
Works fine for me. Please follow the bug report guidelines to ensure we can investigate your report.

![firefox-svg](https://user-images.githubusercontent.com/768723/70442739-cf129080-1a8e-11ea-91d4-5f421981cd6f.png)

**Comment by tunepunk** [comment]
![image](https://user-images.githubusercontent.com/27011641/70443666-d179e800-1a98-11ea-81f1-3acb77b10080.png)

It's completely blank here. Win10, Firefox v71 .. Construct r179 as well.

Any not sure what could be causing it. I get no errors or warnings.

**Comment by shortercode** [comment]
System details? WebGL details might be useful.

**Comment by tunepunk** [comment]
Platform information

Browser: Firefox
Browser version: 71.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.7647058823529411
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
C3 release: r179 (beta)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 49 mb (2.4%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
It could well depend on the specific SVG file. Please just include a project as per the bug report guidelines, this is usually the quickest way to deal with it and can avoid this whole back and forth.

**Comment by tunepunk** [comment]
https://www.dropbox.com/s/045p8uemydubi3v/svgtest.c3p?dl=1

I've tried many different svg files and none work. They all work in chrome but not firefox.

**Comment by AshleyScirra** [comment]
I can reproduce with that specific SVG. It looks like it depends on using `width="100%" height="100%"` on the root SVG element. Firefox has some weird rules on how it handles SVG sizes that are different to other browsers, and we have special code to handle that, but I guess this case isn't handled correctly still.

In the mean time if you set a fixed width and height, e.g. `width="100px" height="100px"`, it should work in Firefox too.

**Comment by tunepunk** [comment]
Ahh i see. Looking though the SVG's that i tested all were width="100%" height="100%", so that makes sense that none of them worked. Thanks for providing a temporary fix.

**Comment by AshleyScirra** [comment]
Alright, just applied the workaround to overwrite percentage width/height attributes, whereas previously it would skip the workaround if those attributes were present at all. Looks like this gets these SVGs working in Firefox again.
