### ISSUE TITLE
Mistakes in English translation in r179

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#3536]
A few mistakes in English strings I found while translating:

_text.ui.editors.data-editor.rename-row.message
Choose a new name for the column_ 
should be "for the row"

_text.ui.editors.data-editor.rename-row.label 
Column name_ 
should be "Row name"

_text.plugins.advert.actions.tag-for-child-directed-treatment.params.option.desc 
Specifies the Admob SDK should return child directed content_ 
looks like some word is missing, maybe it should read "Specifies **if** the Admob SDK ..."?

**Comment by shortercode** [comment]
Thanks for the feedback, I'll update the strings.
