### ISSUE TITLE
[r31] Layout paralaxes randomly (low repro, no steps)

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#354]
## Problem description

I've noticed starting with r30 that the layout paralaxes in the editor at random times. I cannot reproduce it but maybe you guys have an idea what could be the issue.

I only have this gif :| 

![layoutactingweird](https://cloud.githubusercontent.com/assets/7268697/26424581/66cb09b6-40da-11e7-8823-7ded4b339d43.gif)

If I undock the properties panel which I have on the right side of the screen, the bug disappears. If I dock it back, it reappears again. 

Restarting C3 fixes this, until it randomly appears again.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. no idea

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 195 mb (1.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by JeFawk** [comment]
Seems to happen if I resize the window too. I just downloaded my project on my computer and chrome's download bar on the bottom triggered the bug.

**Comment by JeFawk** [comment]
I opened my project today in incognito, rearranged the panels like so and it bugged.

![image](https://cloud.githubusercontent.com/assets/7268697/26448152/888f24d6-4154-11e7-9902-ad241f5070d4.png)

**Comment by AshleyScirra** [comment]
Does it always reproduce?

**Comment by JeFawk** [comment]
Seems like it for me nowadays. I even cleared the cache and browsing data.


![dockingbug](https://cloud.githubusercontent.com/assets/7268697/26499892/c6664d00-423c-11e7-9229-e3621de17ecd.gif)

**Comment by AshleyScirra** [comment]
That video is too heavily cropped to make sense of, can you post a full size window version?

**Comment by JeFawk** [comment]
Here you go. It's a tiny video of that I added the .zip extension to.
[2017-05-26 19-56-48.mp4.zip](https://github.com/Scirra/Construct-3-bugs/files/1032523/2017-05-26.19-56-48.mp4.zip)

**Comment by AshleyScirra** [comment]
Closing as this is an old issue and we've fixed a few similar looking bugs since May. I suspect this is fixed now, but if not please file again.

**Comment by JeFawk** [comment]
I've noticed this appearing quite often lately (though i'm working on a project with a lot of layouts that i switch to often).

How do I help? It's still random and the project settings dont seem to matter (since I swapped projects)

**Comment by AshleyScirra** [comment]
As ever, finding a way to reliably reproduce the issue is critical.
