### ISSUE TITLE
Timers won't trigger more than once

### ISSUE THREAD

**Issue by ItemME** [Scirra/Construct-3-bugs#3540]
## Problem description

As mentioned in the title, sometimes Timers won't trigger for all objects (result observed on r179)

## Attach a .c3p

[TimersBroken.c3p](https://drive.google.com/open?id=1sLUtuOZpSQrMk6McUuxOWxu3hHUT5SO4)

## Steps to reproduce

1. Open the project on r179 (latest beta)
2. Press "SPACE" to see the expected result (working one)
3. Press "R" to see the broken result 

I detailed everything in the code, but it will look pretty obvious to you

## Observed result

No objects get triggered unless the timer trigger is placed in a for each loop

## Expected result

They should all be triggering, and not be placed in a for each loop, as it's a trigger event.

## More details

This was tested on the latest beta (r179) but I'm not sure since when this problem appeared

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.42.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.42.0 (like Chrome/78.0.3904.70)
C3 release: r179 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 161 gb
Storage usage (approx): 740 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is not a bug. From the [manual entry on the 'On timer' trigger](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/timer):

> **Note:** this trigger can fire with multiple instances picked, if their timers all reach their time in the same tick. This can sometimes work unexpectedly if the actions expect there to be just one instance picked. The workaround is to add a For each condition after this trigger to ensure the actions run once per instance.

In both cases the timer runs with multiple instances picked. In the "NOTOK" case, you use "Pick instance by UID", and the expression `Object1.ChildUID` can only return one number, so it returns the first one only. Using the for-each loop as recommended by the manual ensures you repeat the "Pick instance by UID" condition for each individual instance that the timer is running for. I'd recommend using it as a second condition though, i.e.:

- Object1: on timer
- For each Object1

I checked and it works identically in the last stable release (r171.3) which confirms this is not a regression.
