### ISSUE TITLE
Shadow light: Light radius stays in effect despite beeing greyed out

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3541]
Shadow lights with a light radius must have a light height of 0, so far so good. (Out of curiosity though, why is that?) However, when you have a light radius set and enter some light height, light radius will be greyed out and "disabled", however, light radius stays in effect while the light height gets ignored. Was rather confusing why my lights went haywire when closer to walls, not thinking that light radius was still in effect.

![image](https://user-images.githubusercontent.com/31101309/70719463-56ac0980-1cf2-11ea-9d2f-c479396e232d.png)

## Attach a .c3p

[lightradius.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3956116/lightradius.c3p.zip)

## Steps to reproduce

1. Check properties of the shadow light

## Observed result

Light radius is greyed out due to having a light height > 0. However, the light still uses the light radius regardless. (Preview to see it in effect)

## Expected result

When light radius is greyed out, it should not be used/set to 0

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r179 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 6.9 gb
Storage usage (approx): 1.4 gb (21%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.

> Out of curiosity though, why is that?

The geometry calculations for penumbra rendering are pretty complicated, and only cover an infinite shadow distance, since that's a lot easier to handle.
