### ISSUE TITLE
Preview sound crash

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#3543]
## Problem description

Construct crashes when previewing an audio file

## Attach a .c3p

[SoundPreviewBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3957453/SoundPreviewBug.zip)

## Steps to reproduce

1. Open attached project
2. Add an action: Play audio file
3. Try to preview audio file by clicking the black play button
4. Construct crashes

## Observed result

![1](https://user-images.githubusercontent.com/53188782/70742012-4c573300-1d25-11ea-8094-a03e505b8d83.jpg)

![2](https://user-images.githubusercontent.com/53188782/70742037-55480480-1d25-11ea-80c4-0a954b618698.jpg)

## Expected result

no crash

## More details

**Affected browsers/platforms:** Chrome/Firefox

**First affected release:** r179

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r179/projectResources.js, line 1, col 1130512
Message: Uncaught ReferenceError: Cannot access 'e' before initialization
Stack: ReferenceError: Cannot access 'e' before initialization at window.ǃGEB.ǃGEo (https://editor.construct.net/r179/projectResources.js:1:1130512) at HTMLButtonElement.ǃGEF.onclick (https://editor.construct.net/r179/projectResources.js:1:1129375)
Construct 3 version: r179
URL: https://editor.construct.net/r179/
Date: Thu Dec 12 2019 21:16:27 GMT+0200 (Eastern European Standard Time)
Uptime: 2508.3 s

Platform information
Browser: Chrome
Browser version: 79.0.3945.79
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
C3 release: r179 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Looks like the same issue as #3537 which is already fixed, so closing as duplicate.
