### ISSUE TITLE
Crash r179 when open animation editor android

### ISSUE THREAD

**Issue by LucasGuerra007** [Scirra/Construct-3-bugs#3544]
## crash when open editor animation object (sorry my english)

 since last release r179 cant open any object with sprite. Crash with a red screen and a message error

## create a sprite object and the error appear

1.create a object sprite
2.error appear
3.

## Observed result

 the proyect crash

## Expected result no crash

 no crash

## More details
 i no understand why 

**Affected browsers/platforms:** 

r179

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r179/projectResources.js, line 1, col 903871
Message: Uncaught TypeError: Cannot read property 'tagName' of undefined
Stack: TypeError: Cannot read property 'tagName' of undefined at Object.ǃGWL (https://editor.construct.net/r179/projectResources.js:1:903871) at Object.ǃSad (https://editor.construct.net/r179/projectResources.js:1:903784) at Object.ǃSCo (https://editor.construct.net/r179/projectResources.js:1:590555) at Object.ǃSC_ (https://editor.construct.net/r179/projectResources.js:1:583666) at Function.ǃmNS (https://editor.construct.net/r179/main.js:2:294479) at Function.ǃm$ (https://editor.construct.net/r179/main.js:2:302150) at e.ǃeA (https://editor.construct.net/r179/components/editors/layoutView/layoutView.js:1:106242) at Array. (https://editor.construct.net/r179/components/editors/layoutView/layoutView.js:1:105603) at Object.ǃGxB (https://editor.construct.net/r179/main.js:2:198242) at Object.dispatchEvent (https://editor.construct.net/r179/main.js:2:196193)
Construct 3 version: r179
URL: https://editor.construct.net/r179/
Date: Thu Dec 12 2019 20:03:32 GMT-0300 (hora estándar de Argentina)
Uptime: 55.7 s

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 32-bit
Context: webapp
Operating system: Android
Operating system version: 6.0.1
Operating system architecture: 32-bit
Device type: mobile
Device pixel ratio: 4
Logical CPU cores: 8
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Linux; Android 6.0.1; SM-N910U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36
C3 release: r179 (beta)
Language setting: es-ES

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: ARM
Renderer: Mali-T760
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I believe @DiegoScirra already caught this and fixed it, so it should be fixed in the next release.
