### ISSUE TITLE
Drawningcanvas bug also makes sprite disappear on different layer

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3547]
## Problem description
Pasting sprite with effect on drawningcanvas and changing layout scale, will make sprite on different layer to disappear.

Could be same issue when drawningcanvas bugs with effect paste.  But this time it also makes sprite on different layer to disappear, so might be something else but related. 
This needed new issue report to check or later to test, if main issue is worked on.

## Attach a .c3p
[DrawningCanvas_Bugs03.zip](https://github.com/Scirra/Construct-3-bugs/files/3962648/DrawningCanvas_Bugs03.zip)

## Steps to reproduce

1.Open example
2.Hold down mouse and see layout scaling smaller
3.At around 0.5 scale, see sprite on different layer disappear.(you can use debug mode if needed)

## Observed result
Drawningcanvas buggs and also bugs sprite on different layer.

## Expected result
Drawningcanvas bug should not affect other objects.

## More details

Pasted sprite and sprite on other layer share spritesheet!

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.79
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
C3 release: r179 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.8 gb (1.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This seems specific to "Paste object with effects" with a sprite using Blur Horizontal and Blur Vertical effects. This is an extremely complicated part of Construct and is very difficult to debug.

Since there are known issues with this - issue #2624 already covers the fact pasting a sprite with these same effects is buggy - I'll close this issue as another variant of that issue to review along with that.

**Comment by DieppedalleDavid** [comment]
AshleyScirra, please do something, you said it's very hard ok, but I would love for you and me to fix this problem, please fix this problem, it's been going on for too long and my projects have been blocked because of this!
