### ISSUE TITLE
Google Play: Request hi-scores is not valid.

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#3550]
When I use the googleplay plugin and try to request my result and output it via (Request hi-scores) and output (On hi-score request success), the request is not processed, that is, the result is not received, as if this function is dead. Please check, in the past, I did it on android and the result was shown!

**Comment by AshleyScirra** [comment]
I'm afraid we can't help unless you follow the bug report guidelines.

**Comment by ERAgames777** [comment]
Sorry, I ignored the error in the project and a high score was received!
