### ISSUE TITLE
(Android) last Google Chrome update deleted user data

### ISSUE THREAD

**Issue by RobinBloood** [Scirra/Construct-3-bugs#3551]
last Google Chrome update deleted user data from all my games. Also if you have the last Google Chrome and you'll delete it, you'll lost all your saves in the game.
It erases all data from localstorage, webstorage and system->Save/Load

For example:
this one: https://play.google.com/store/apps/details?id=com.robinblood.switchornot it uses webstorage

How to check:
1) uninstall Chrome update in google play
2) install my game and pass few levels
3) install Chrome update in google play
4) launch my game again and see that you start from 1-st level

 .c3p file with localstorage and system->Save/Load test:
https://drive.google.com/open?id=1OiG_n83EILtROH0EhJ7nbdOLsJxh5qoz

How to check:
1) update Chrome
2) compile c3p as android
3) lounch and press on "0" to change number
4) click "S" and "S stor" button to save game with two ways 
5) reload app and click "L" or "L stor" to load game to check that load is working
3) uninstall Chrome update in google play
4) launch app again and try to load

**Comment by AshleyScirra** [comment]
This is an Android WebView dataloss bug which is currently causing a lot of trouble: https://bugs.chromium.org/p/chromium/issues/detail?id=1033655

It's nothing to do with us or Construct, so I'm afraid you will have to follow that issue for updates.

According to that report Google are treating the issue with maximum emergency-priority and are working on a fix. The M79 WebView rolled out to ~10% of users, which should at least limit the impact (90% of users should be unaffected).

**Comment by shortercode** [comment]
Linking to a discussion on the forum related to this issue https://www.construct.net/en/forum/construct-3/how-do-i-8/players-lost-saves-android-148822
