### ISSUE TITLE
Latest Construct 3 Desktop Fails To Restore Maximized State (Regression)

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#3552]
## Problem description

When maximizing the window and re-opening Construct 3, the window maximized state doesn't get restored as expected. This issue is most-likely caused by the recent NW2 update.

## Steps to reproduce

1. Open latest C3 desktop
2. Maximize window and close C3 desktop
3. Open again and notice maximized state is not being applied

## Observed result

Window maximized state is not being restored.

## Expected result

It should work like in the previous versions and restore the maximized state.

## More details

**Affected browsers/platforms:** NWjs

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.43.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.43.1 (like Chrome/79.0.3945.79)
C3 release: r180 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 173 gb
Storage usage (approx): 121 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by TheRealDannyyy** [comment]
If this can't be worked around. Would be nice if the underlying code that's at fault could be reported to the NWjs team. Feel free to close this issue if that's the case.

**Comment by shortercode** [comment]
The code responsible for this hasn't been touched for quite a while I believe, so it might be related to the NW2 change. Their current advise is to test with the "--disable-features=nw2" flag and file an issue if that resolves the problem, as the changes are intended to be "internal only" by their team.

**Comment by AshleyScirra** [comment]
It's a small bug in NW2, filed here: https://github.com/nwjs/nw.js/issues/7278

Easy to work around though so patched for the next release.

**Comment by TheRealDannyyy** [comment]
Thanks for reporting it. I didn't know the code behind it so I couldn't really report it myself.
