### ISSUE TITLE
Instant Games LoadPlayerScore from leaderboard fails if no score has been set previously

### ISSUE THREAD

**Issue by cesarvarela** [Scirra/Construct-3-bugs#3553]
## Problem description

Instant Games LoadPlayerScore from leaderboard fails if no score has been set previously

## Attach a .c3p

just the c3p doesn't make sense when talking about Instant Games.

## Steps to reproduce

- Create a  non-contextual leaderboard
- Use the LoadPlayerScore action from the Instant Games object to load the score from that leaderboard

## Observed result

```
main.js:11 [Instant Games] Failed to load player score:  TypeError: Cannot read property 'getScore' of null
    at b._OnLoadPlayerScore (main.js:11)
```
## Expected result

Shouldn't fail or a CheckScoreExists method should be added.

## System details
 This happens inside IG besides of being desktop or mobile

**Comment by AshleyScirra** [comment]
Can you provide a minimal project demonstrating this as per the bug report guidelines? It always helps.

**Comment by cesarvarela** [comment]
[Leaderboards.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3978895/Leaderboards.c3p.zip)

You'll have to create an Instant Game, and create a leaderboard called "scores" to see the error

**Comment by AshleyScirra** [comment]
Loading the player score *should* fail if they haven't submitted a score. There's no score to load, so it doesn't make sense to return a value from this. It was already triggering 'On error' accordingly.

However when this happened the console message was a JavaScript error. I've changed this so the error is now "player has no score" which should be clearer. This only affects the console message (which is sufficiently minor it won't be noted in the changelog); as before it still triggers 'On error' so there is no real change in functionality here.

**Comment by cesarvarela** [comment]
Well; that works for me, I was afraid the js error was breaking something else 👍
