### ISSUE TITLE
SVG files are invisible on mobile devices

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#3558]
## Problem description

I'm working on a new mobile game and we were so excited about the new SVG file support that we decided to replace almost every sprite in the game for SVG files, however, after replacing everything and finally compiling a debug APK we got a huge surprise, only sprites, tiled background, texts, etc were visible. For some weird reason, SVG files are not rendered on any mobile (Android) devices we tested.

## Attach a .c3p

[SVG Test.zip](https://github.com/Scirra/Construct-3-bugs/files/3987866/SVG.Test.zip)

## Steps to reproduce

1. Build a debug APK using this C3P, which contains a simple Android logo (SVG) and a background (Tile Background).
2. Install it on your phone and check if it's possible to see the logo or only the background.

## Observed result

SVG files are simply not rendered.

## Expected result

SVG files to be rendered just like any other accepted file format.

## More details

**Affected browsers/platforms:** 

**First affected release:** R180

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report, good catch. It turns out there is a small compatibility tweak we needed to make to get it working in Cordova. This is done for the next release so it should be working again then. (Note due to staff holidays this won't come out until early January though.)
