### ISSUE TITLE
Crash on mobile start

### ISSUE THREAD

**Issue by mfoster98** [Scirra/Construct-3-bugs#356]
## Problem description

I just launched the engine on my phone and the error appeared

## Steps to reproduce

1.start engine on android 
2.scroll down recent projects 
3.crash appeared

## Observed result 
Nasty Engine crash
## Expected result
Engine not to crash

## Affected browsers

* Chrome: yes/no zoom 100%

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Event 'error': [object Event]
Construct 3 version: r31
URL: https://editor.construct.net/index.html
Date: Thu May 25 2017 09:44:47 GMT+0100 (BST)
Uptime: 26.5 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.83
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Android
Operating system version: 5.0
Operating system architecture: 32-bit
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Linux; Android 5.0; ALE-L21 Build/HuaweiALE-L21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36
C3 release: r31

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: ARM
Renderer: Mali-450 MP
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 100
Extensions: EXT_blend_minmax, EXT_shader_texture_lod, OES_standard_derivatives, OES_vertex_array_object, WEBGL_compressed_texture_etc1, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Sorry, the error message is not useful in this case and there's nothing we can do without more information about what's causing the problem.
