### ISSUE TITLE
Bug with color expressions

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#3560]
## Problem description

Using the rgbEx255() expression seems to not put out accurate RGB values. When I put the replace color effect as I did, it works as intended until I try to set the source color parameter with the rgbEx255() expression to the exact same RGB values I put in the editor. The tolerance is set to the lowest possible amount of 0.01% so as to make it highly sensitive to any values put in for the source color. I know Ashley wrote a thing about how computers often take shortcuts in math formulas due to they can't realistically store things like true infinity because they are finite in memory, but this causes color inaccuracies in my retro style game with palette swapping I faked with replace color, unless I am misunderstanding how to set the source color precisely and am doing this wrong. It works for 0, 0, 0 and 255, 255, 255 just fine, but something like 0, 0, 252 I tried to set does not work as is demonstrated in my example file.

## Attach a .c3p

[https://drive.google.com/open?id=1DtJie-x4UmwTbEIqMNW4hL9gWCeEReEL](https://drive.google.com/open?id=1DtJie-x4UmwTbEIqMNW4hL9gWCeEReEL)

## Steps to reproduce

1. Press the button.

## Observed result

The editor settings I put made some of the dark blue in Mega Man change to red as was accurate. But once the button is pressed to set the source color in the editor to the same RGB values via the rgbEx255() expression, the sprite returns to normal implying the source was not set accurately enough.

## Expected result

I would expect replace color to replace a color no matter how pedantic I am about what it should be. I'd expect it at the very least to be able to replace only a very specific RGB value as it can do in the editor but not with rgbEx255() unless, again, I misunderstood how to use that expression, but after reading the manual it appears I am only supposed to put in RGB values literally.

## More details

**Affected browsers/platforms:** NWjs

**First affected release:** r180

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.43.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.43.1 (like Chrome/79.0.3945.79)
C3 release: r180 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 88 gb
Storage usage (approx): 169 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SnipG** [comment]
use rgb(0,0,252) instead. It does not show up in expression dictonary, but it still is there. They added rgbEx, but most likely did not extend support for every possibly case.

**Comment by corlenbelspar** [comment]
How do those differ in functionality and are they going to remove rgb()?

**Comment by SnipG** [comment]
It should not differ, but i don't know how it's coded.  They might remove it in future.

**Comment by corlenbelspar** [comment]
It works exactly as it should while rgbEx255() does not, though it is annoying trying to use it with how C3's vigorous autocorrect fights me every step of the way trying to change rgb to rgba.

**Comment by AshleyScirra** [comment]
This happens because GPUs actually process colors in a fractional [0, 1] range, fractional calculations are not exactly accurate, and the different RGB expressions apply different amounts of rounding for backwards compatibility reasons.

The initial source color is set with an actual blue component of `0.9882352941176471`. The action then sets it with a blue component of `0.9873046875`. As you can see these are different values, and the tolerance specified is extremely small so makes the difference visible. In general such tiny tolerances are not a good idea anyway, since it works almost entirely in the range of rounding errors, meaning the problem could easily invert and happen the opposite way around by chance in different circumstances.

I can't think of anything that could be done to make these calculations identical, especially when using something like a 0-255 range, which necessarily must be divided by 255, which is guaranteed to introduce rounding errors. I think you will just have to adjust the color parameters and tolerance until it works.

**Comment by corlenbelspar** [comment]
So I guess the editor in C3 does entirely different math than if you set the parameter with the rgbEx255() expression?

Is there a better way to do fake retro palette swapping then besides using the replace color? Clearly it is not a good option for this by what you said.

**Comment by SnipG** [comment]
I don't think it is just  some 0.001% rounding error case, where one expression jumps over and other does not. I think they have something more that applies to them.

Even though i checked the shader out in c2, and it can produce anomalies: ie, color mixing in some cases. Solid color replace should not do mixing(replaces color or does not). But shader has nothing to do it with when:
 *Using rgbEx255 - you never get somewhat correct color under 0.3 tolerance, only bad mixed colors.
 *source (252.1 , 0, 0)  - you have to use tolerance 1.0, to get default color that looks same to eye
              252.3  - you have to use tolerance 3.0
              252.6 - you have to use tolerance 8.0 
While using rgb. 252.0 -> 253.0 they all produce 100% correct color down to 0.0001% tolerance.
And  i mean correct, you can paste image to drawingcanvas and export, then import back to c3 image editor and use eye dropper and get 100% correct color.

While rgbEx255 never gives correct color, when you use it to set color inside replace color effect.  I replaced color to 126, 241, 4 then best what rgbEx gave was 125, 240, 5.  Even when  you leave color to 0, like (252,0,0) rgbEX will export with (252, 2, 2), in low tolerance values. You can raise it but more you raise more other color gets replaced or mixed.

Both expressions act strange when used, even though when rgbEx could be newer and apply number more correctly, while rgb() compensates somehow but gives correct output.
Given all that, rgbEx can be only used with high tolerance and will pretty much only work if you got colors with huge differences. Setting color (252,0,0), then you need to use least tolerance 8 which will replace 252 and but will mix color at 245. You need to insert value 252.1 for 252 to use tolerance 1.0, which will not mix color at 245. 

But given all of this, tolerances and values etc are not extremely tight or tiny. They affect much larger scale. Rgb could do some magic and rgbEx255 round correctly with very tiny error, but outputs etc are effected much larger scale. 

RGB() is like miles ahead of rgbEx255() and should'nt get expired and removed.

**Comment by corlenbelspar** [comment]
Yeah when you use the rgbEx255() expression to set the color, even if you set it to like 0.5% tolerance, it will never fully set it to the target color you specified while simultaneously drastically altering other colors that are close. I thought replace color was a decent effect, but if we're going to eventually have rgb() removed entirely as is implied where the C3 editor violently tries to autocorrect it into rgba() and it is hidden from everywhere, I guess C3 is not very good for a lot of retro style games.

I don't even know where the rgbEx() or rgbEx255() expressions even come from as a concept except it looks like some purely proprietary expression made for C3 because all that comes up when I try to Google it is Construct.

I already have major gripes now with C3 as it is where I found out it has a hard memory limit of 4GB no matter what with the NWjs EXE version due to Chromium has a memory limit of 4GB per tab. I tried actually editing the package.json file of C3 to put in the flag --max-old-space-size=8192 to try to increase the memory limit, but C3 always crashing instantly going past 4GB memory use in test I ran on it. It wouldn't be so bad in theory, but the previews you run also contribute to the memory use the editor is using, so if you start making a rather large game, you're probably going to end up halfway through development that C3 will just crash anytime you try to run a preview because Ashley also basically told me he will never make it unload anything from your project from memory at any time, so everything you make is loaded into this 4GB capacity at all time. I already ran into this issue happening way sooner than it should've because of a bug in C3 where the maxwidth and maxheight of your tilemaps in your layouts can be set to huge numbers by accident by C3 and you cannot change this unless you export your tilemaps and edit them in Tiled in size and then import them back in... which I'm expected to pay $99 a year for this and I'm supposed to use third party software to fix error in C3's basic editing it's supposed to be able to do by itself. The fact I also cannot get accurate color setting with the expression I'm expected to use is also pretty bad.

**Comment by AshleyScirra** [comment]
'Replace color' uses a gradient when colors are within the tolerance but not exactly on the source color. I think the best solution is some kind of new effect like 'Replace solid color' that has a tolerance but does not use a gradient and always substitutes the replacement color. This is a better fit for pixel art and avoids needing to make exactly precise color calculations, which is difficult to do for a variety of reasons.
