### ISSUE TITLE
Crash while Tween event is moved

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-3-bugs#3561]
## Problem description
I have found that when I try to move an event that contains an action with the Tween behaviour AND a customized Ease, C3 editor will crash.
This happen  using the latest R180 version with Chrome and Firefox on Windows 7 64bit

## Attach a .c3p

[C3 Crash report and project files.zip](https://github.com/Scirra/Construct-3-bugs/files/4006154/C3.Crash.report.and.project.files.zip)
the above zip file contains the test .c3p file and the saved crashing file as well plus the chrome crash report. PLEASE NOTE THAT ONE FILE MAY CRASH YOUR C3 EDITOR. DO NOT OPEN IT IF YOU DIDN'T SAVE YOUR PROJECT!

## Steps to reproduce

1. Open "C3 Editor Crash Test.c3p"
2. Move line 4 to line 3 at the line level.
3. you'll get your C3 crash.

## More details

Please note that the crash will happen if you use a custom Ease into the Tween behavior only.

**Affected browsers/platforms:** 
The problem happen on both Chrome and Firefox browsers,

**First affected release:** 
This has been tested into R180 version only.
## System details

Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.!$.!mE (https://editor.construct.net/r180/main.js:2:92410) at Function.!qMw (https://editor.construct.net/r180/main.js:2:153272) at window.!qt$.!qGG (https://editor.construct.net/r180/projectResources.js:1:368760) at Function.!qGs (https://editor.construct.net/r180/components/editors/eventSheetView/eventSheetView.js:1:125331) at e.!vA (https://editor.construct.net/r180/components/editors/eventSheetView/eventSheetView.js:1:125224) at new e (https://editor.construct.net/r180/components/editors/eventSheetView/eventSheetView.js:1:125151) at Function.!$.!k (https://editor.construct.net/r180/main.js:2:128680) at window.!qt$.!qk_ (https://editor.construct.net/r180/projectResources.js:1:368609) at window.!qus.!qiy (https://editor.construct.net/r180/components/editors/eventSheetView/eventSheetView.js:1:99018) at window.!qus.!qiX (https://editor.construct.net/r180/components/editors/eventSheetView/eventSheetView.js:1:98926)
Stack: TypeError: expected string at Function.!$.!mE (https://editor.construct.net/r180/main.js:2:92410) at Function.!qMw (https://editor.construct.net/r180/main.js:2:153272) at window.!qt$.!qGG (https://editor.construct.net/r180/projectResources.js:1:368760) at Function.!qGs (https://editor.construct.net/r180/components/editors/eventSheetView/eventSheetView.js:1:125331) at e.!vA (https://editor.construct.net/r180/components/editors/eventSheetView/eventSheetView.js:1:125224) at new e (https://editor.construct.net/r180/components/editors/eventSheetView/eventSheetView.js:1:125151) at Function.!$.!k (https://editor.construct.net/r180/main.js:2:128680) at window.!qt$.!qk_ (https://editor.construct.net/r180/projectResources.js:1:368609) at window.!qus.!qiy (https://editor.construct.net/r180/components/editors/eventSheetView/eventSheetView.js:1:99018) at window.!qus.!qiX (https://editor.construct.net/r180/components/editors/eventSheetView/eventSheetView.js:1:98926)
Construct 3 version: r180
URL: https://editor.construct.net/r180/
Date: Fri Dec 27 2019 19:51:30 GMT+0100 (Ora standard dell’Europa centrale)
Uptime: 166.8 s

Platform information
Browser: Chrome
Browser version: 79.0.3945.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
C3 release: r180 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_float_blend, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed

**Comment by rraffo** [comment]
Thank you
