### ISSUE TITLE
Project bar unfocus after renaming object, using keyboard

### ISSUE THREAD

**Issue by IcticStep** [Scirra/Construct-3-bugs#3563]
## Problem description

Project bar get unfocused after renaming object, using F2 on keyboard and user should click one more time on it to continue navigation.

## Attach a .c3p
Simpe project to reproduce my problem: [GoogleDrive](https://drive.google.com/open?id=1_bHrxLATsdDJhg3APklGSwzSil9fdA_y)

## Steps to reproduce

1. Select with mouse any object in project bar. (Now it`s focused and you can navigate in it using arrows keys)
2. Press F2(renaming is unnecessary)
3. Press "ENTER" to confirm renaming
4. Press arrows on your keyboard and see - you cannot use arrows navigation in project bar, until one more mouse click on it.

## Observed result

Project bar is unfocused after renaming the object and no more keyboard navigation possible until one more click to make it focused.
## Expected result

I was expecting opportunity to continue navigation in project bar, using arrows, because it`s often useful to navigate with keys, when you have a lot of objects to rename.
## More details

**Affected browsers/platforms:** 
Windows: yes
Chrome: yes

**First affected release:** 
Worked in Construct 2 but broke in Construct 3.
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 28 gb
Storage usage (approx): 216 mb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed for next beta.
