### ISSUE TITLE
[Timeline] Crash when you click on a master keyframe while holding CTRL

### ISSUE THREAD

**Issue by birbdoy** [Scirra/Construct-3-bugs#3564]
## Problem description

C3 crashes when you click (LMB or RMB) on a master keyframe in a timeline while holding CTRL.

## Attach a .c3p

[TimelineCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/4014351/TimelineCrash.zip)

## Steps to reproduce

1. Open Timeline Bar
2. Hold CTRL and click with either LMB or RMB on a master keyframe

## Observed result

C3 crashes

## Expected result

No crashing

## More details

**Affected browsers/platforms:** 
Chrome/Firefox

**First affected release:** 
Seems to be in every release since r158

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r180/components/bars/timelineBar/timelineBar.js, line 1, col 30294
Message: Uncaught TypeError: this.ǃ_XG is not a function
Stack: TypeError: this.ǃ_XG is not a function at _.e.ǃ_Xi (https://editor.construct.net/r180/components/bars/timelineBar/timelineBar.js:1:30294) at Function.ǃ$Np (https://editor.construct.net/r180/components/bars/timelineBar/timelineBar.js:1:137273) at window.ǃxT.ǃ_Gp.ǃ_id (https://editor.construct.net/r180/components/bars/timelineBar/timelineBar.js:1:136117) at HTMLDivElement. (https://editor.construct.net/r180/components/bars/timelineBar/timelineBar.js:1:135105) at HTMLDocument. (https://editor.construct.net/r180/main.js:2:194017)
Construct 3 version: r180
URL: https://editor.construct.net/r180/
Date: Wed Jan 01 2020 18:55:37 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 9.3 s

Platform information
Browser: Chrome
Browser version: 79.0.3945.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
C3 release: r180 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Fixed.
