### ISSUE TITLE
Bluetooth Keyboard on iOS App not recognized

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#3565]
## Problem description

I just realized that probably the same I reported here #3557 for Gamepad is also true for Bluetooth Keyboards. A Keyboard works nice in the Browser, I can make a remote Preview, it works perfect with a connected Bluetooth keyboard. But when it is exported with X code to an App, the keyboard doesn't exist anymore.

## Attach a .c3p

[keyboard_iOS.zip](https://github.com/Scirra/Construct-3-bugs/files/4018624/keyboard_iOS.zip)

## Steps to reproduce

1. Export project to X Code
2. Export it from X Code to your Apple Mobile Device
3. be sure a Bluetooth keyboard is connected and works otherwise on this Device
4. Run the App
5. Press the Space bar

## Observed result

nothing happens

## Expected result

text should change to Spacebar is pressed

## More details

-I worked in Chrome Version 79.0.3945.88
-X Code Version 11.3 (11C29)
-I used a Wacom Wireless Bluetooth keyboard, it works nice elsewhere on the Device
-I tested in on IPAD MLMV2TY/A with iOS 13.3
-Construct 3 r180

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 79.0.3945.88
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_2
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
C3 release: r180 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 75 gb
Storage usage (approx): 791 mb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
@bubbblebub could you quickly check if it works via remote preview, or local preview. I believe @DrSquidge has had similar issues in the past with a keyboard case.

**Comment by bubbblebub** [comment]
-Yes it works in remote preview, running C3 on my computer, remote preview on my iPad
-Local preview on my local Computer no Problem.
-I quickly tested it when I open the project on my iPad in C3. In Construct the Bluetooth keyboard works, but in the local Preview it doesn't. So local Preview from Construct 3 running on my Ipad doesn't work.

**Comment by DrSquidge** [comment]
To add my two cents:

Not quite a Bluetooth keyboard, but still external to the iPad - I'm using an iPad Pro and Apple's Smart Keyboard Folio. The keyboard works fine in the editor, I have no issues typing but the keyboard is no longer recognised when previewing a project. 

I did a quick test using a keycode detector in the browser on the iPad and it detects keycodes without an issue. But when debugging in C3, you can see that when pressing keys, no keycode seems to be registered.

**Comment by shortercode** [comment]
Thanks for the additional feedback, most curious that it works in remote preview. We don't have a iPad compatible keyboard in the office to check with as far as I'm aware. I expect the easiest thing would be for me to *ahem* borrow one from @DrSquidge when she's next in the office and run some tests. While the keyboard isn't quite the same I expect the issue will be common to both.

**Comment by AshleyScirra** [comment]
FWIW, if it's similar to #3557, I'd guess that it's another case of something that doesn't work in WKWebView.

**Comment by shortercode** [comment]
@AshleyScirra note that it apparently doesn't work in local preview, so
might not be related to wkwebview

**Comment by bubbblebub** [comment]
I quickly made the same tests I've done for the keyboard with the Controller #3557 
it seems to be similar (found no difference): 
-Project running on my Computer, remote Preview on my Ipad - Controller found
-Project running on my Computer, Local Preview on Computer - Controller found
-Project running on my Ipad, Local Preview on Ipad - Controller NOT found
-and of course the main Issue for me, Controller not found when exported with X Code as an App

hope that helps.

**Comment by shortercode** [comment]
Okay so been a bit of fun figuring this out. So this only occurs in 2 specific situations:
1. Game exported as an iOS application
2. Local preview of a game, on iOS when C3 has been added to homescreen

The latter situation appears is subtly different when C3 is added to homescreen or just used through Safari. When added to homescreen the preview appears in a popup, not a tab. I expect the pop up is actually a webview instead of a true Safari instance and hence has the same issue as situation 1.

My best guess is that the keyboard only works when a suitable input has been interacted with. I tested this by adding a button to the layout, and clicking it. Amazingly this makes the keyboard work.  But doesn't really help us fix the issue. I've tried a few standard tricks focusing the document but the restriction appears to not be limited by whats in focus.

This is definitely in the realm of "external bug". I'll file an issue with webkit but I'm not particularly hopeful.

**Comment by AshleyScirra** [comment]
OK, this was something of a nightmare, but I think I got to the bottom of it. If we call preventDefault() on "touchstart", keyboard input never works in WKWebView only. (Safari is not affected.) It's probably some bizarre focus thing where the app needs a touch before keyboard input is received.

We have to call preventDefault() in "touchstart" to work around #3191, which is another bizarre bug involving iframes. However we can assume WKWebView is not going to appear in an iframe, so we can disable the call in WKWebView to work around the keyboard bug, but leave it enabled in Safari to work around the iframe bug. (We also had an Android bug with this event - we now have about 3 paragraphs of comments for one line of code :P )

I made a minimal repro of the keyboard bug and filed it with Apple here: https://bugs.webkit.org/show_bug.cgi?id=206887
However they are utterly useless at dealing with bugs so I wouldn't expect any resolution there. At least our workaround seems to do the trick - but if there is another bug involving "touchstart" we'll really be snookered...

**Comment by bubbblebub** [comment]
thanks a lot for working on this, I quickly made a test and exported my game with Xcode to my IPad.
A short summary of what I found out:

-it works, bluetooth keyboard found!

-first input recognition doesn't work (so Input method recognition at app start doesn't work, I think it needs first a tap/click or something), no problem for me

-seems to have nothing to do with the similar looking controller problem #3557, Gamepad still not found

-main issue, now it seems to see the whole Game as a Text input field. I switched to "touch input" inside my app, then when I clicked a bit wildly, everything gets marked blue, sometimes inclusive "copy/look up", sometimes it gets black, it became completely unplayable. I never had this problem before, so it is probably related..  (I still talk about an app exported with xcode)
![IMG_0728](https://user-images.githubusercontent.com/35291800/73696880-87e6fb80-46dd-11ea-9160-4314324ee86e.PNG)

**Comment by AshleyScirra** [comment]
Note the fix for this was reverted due to introducing a worse problem (shown in the previous comment and also filed at #3642). The only way to get this working is for Apple to fix the issue filed here: https://bugs.webkit.org/show_bug.cgi?id=206887
