### ISSUE TITLE
More quickly version jump dialog.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#3567]
## Problem description
When I opening newer Beta versions of files. Always have trouble  
Have to go through these steps every time

1. -> [  Open File ]

> This project cannot be opened since it was saved in a newer version of Construct 3. The project was saved in r180, and you are currently using r171.3. Use a newer version of Construct 3 to open the project. 

2-> [  ok  ]
**3. -> Move Mouse to url bar and Reload the Page[  https://editor.construct.net/r180 ]**  
**4. -> again [  Open File ]**

But why not:

> This project cannot be opened since it was saved in a newer version of Construct 3. The project was saved in r180, and you are currently using r171.3. Use a newer version of Construct 3 to open the project. 

**Click [yes]  jump to the r180 and reload the file.**
2 -> [  yes ]

then can leave out
X -> [  https://editor.construct.net/r180 ]
X -> [  Open File ]

It ’s very comfortable to experience.

Incidentally, When I am not logged in, show the 'Buy now' page it Can't drag files into open project

**Comment by AshleyScirra** [comment]
This is a suggestion, not a bug. Please post suggestions here: https://construct3.ideas.aha.io/
