### ISSUE TITLE
[R180]Storage Cleaning crashes on bloated storage FireFox

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#3568]
## Problem description

I have not updated the editor on FireFox since at least r148.
I have tried updating to the new r180, the storage cleaner dialog opens and indicates it is scanning.
After a while Construct crashed.

## Steps to reproduce

No c3p, not sure how to reproduce.
I just have FireFox with its storage capacity already full for a while (I've been using Construct 3 on FF at first, at least until r148 which was the last one "in storage".

## Observed result

The storage cleaner dialog appeared after I have clicked the dedicated button to open it.
It indicated it was scanning. Nothing more appeared for a while.
A crash report appeared.

## Expected result

Some sort of file listing to manage and possibly clear to clean the storage.

## More details

**Affected browsers/platforms:**
FireFox 71 64 bits

**First affected release:** r180

## System details

<details><summary>View details</summary>
Error report information

Type: unhandled rejection
Reason: Error: NetworkError when attempting to fetch resource.
Construct 3 version: r180
URL: https://editor.construct.net/r180/
Date: Fri Jan 03 2020 23:22:38 GMT+0100 (heure normale d’Europe centrale)
Uptime: 882.2 s
Platform information

Browser: Firefox
Browser version: 71.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
C3 release: r180 (beta)
Language setting: fr-FR
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I'm afraid I can't see anything to do about this. I just tried storage cleanup in Firefox and it worked fine (and as usual I tested it several times in Firefox while developing the feature). The crash report doesn't have any useful details in this case. And the storage cleanup dialog already has lots of error handling to catch anything that might go wrong without crashing, so I don't know how this could have happened. It may even be unrelated to the storage dialog. In cases like this looking for any further messages in the console can be helpful, but I guess it's too late for that now. If you can find a way to reproduce it, let me know...

**Comment by Kyatric** [comment]
I launched the editor again, and now the content of the storage is available in the dialog and no more crash.
Perhaps it was a temporary issue, specific to my computer at that time.

**Comment by SnipG** [comment]
Changing from older release to newer has always been buggy and results crash very often. Eg: like 130 to 170.
It happens totally random and will go away with 1 refresh, when crash happens. 
It could be constant crash issue but i never tried to reproduce because old releases full of bugs and because 1 refresh fixes it. 
Tends to happen more if you go like this, for example 120->121->160. Could possible cause by editor settings conflict etc.
