### ISSUE TITLE
[Timeline] Updating a keyframe only updates one property at a time

### ISSUE THREAD

**Issue by birbdoy** [Scirra/Construct-3-bugs#3569]
## Problem description

Updating an existing keyframe only updates the first/topmost affected property, all other changed properties are ignored. 

## Attach a .c3p

[TimelineUpdateBug.zip](https://github.com/Scirra/Construct-3-bugs/files/4022114/TimelineUpdateBug.zip)

## Steps to reproduce

1. Change the x and y position of the sprite in one of both keyframes
2. Press s or use the update function to update the keyframe
3. Notice how the change to y was ignored
4. Now only change the y position in one of both keyframes ( by holding down shift while moving the sprite )
5. Update the keyframe
6. Notice that y was updated
7. Add additional properties that appear below the x and y tracks ( like angle or width/height )
8. Play around with changes, e.g. change only the y position and the angle ( the angle change will be ignored )

## Observed result

Only one property ( the topmost one ) is updated at a time.

## Expected result

All changed properties should get updated.

## More details

The exact same bug applies if you update an existing keyframe with newly added properties. E.g. adding an angle change to one of both keyframes works correctly whereas adding an angle change and a position change ignores everything except for one axis of the position change.

**Affected browsers/platforms:** 
Chrome/Firefox

**First affected release:** 
r169 seems to be the first release affected by this.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
C3 release: r180 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 41 gb
Storage usage (approx): 817 mb (2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta
