### ISSUE TITLE
Multiplayer : Not Working On Layout Restart 

### ISSUE THREAD

**Issue by shubhamrathi9** [Scirra/Construct-3-bugs#3571]
## Problem description

Multiplayer connection gets stuck on "logging in" or "joining room" state when we restart or leave & come back to the layout
## Attach a .c3p

[MultiplayerRestartBugc3p](https://drive.google.com/open?id=1JYCSZiUGFROxN1bnM11npB214F9w9jKu)

## Steps to reproduce

It happens when we restart the layout or leave the layout and come back to it.
Here i have modified the "Multiplayer Chat Example File" with two buttons : Restart and GoBack

1. Open File and Run Login Layout
2. Enter a Name and hit "Join"....
3. Everything works as it is supposed to and you an see feed on top left screen connected...logging....joining....joined....your host/peer.
4. Click "Restart", layout restarts and you can see in feed that it gets stuck to "logging in....."
5. Now follow steps 1,2 & 3 once again, and this time click "GoBack", Now Login, and in feed you can see that it gets stuck to "joining room..."
## Observed result

Multiplayer connection stucks on "joining room..." or "logging in....." when we restart a layout with multiplayer connection.
## Expected result

Multiplayer connection should complete the signal connection..., logging in.... and joining room... processes on restart of the layout.
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.38.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.38.0 (like Chrome/74.0.3729.108)
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 507 gb
Storage usage (approx): 1.1 gb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's not a bug. The project restarts the layout without resetting the Multiplayer object (e.g. leaving room, disconnecting from signalling, etc). So you restart the layout still in the chat room and try to re-join it, which doesn't work.

**Comment by shubhamrathi9** [comment]
Thank you for replying, i also tried to leave room and disconnect signalling at end of layout, but that didn't work either because  was using leave room and disconnect signalling at the same time. 

I was confused so i read manual for more clarity on this but it wasn't there, I think this should be added to the manual for future users.
