### ISSUE TITLE
IPlatformBehaviorInstance can't set VectorY

### ISSUE THREAD

**Issue by DreiAugenFrosch** [Scirra/Construct-3-bugs#3573]
## Problem description

When usign the Platform behavior, vectorY can't be changed.
I tried to rewirte the Flappy Bird Demo in JavaScript. Therefor I created a class Player wich extends the ISpriteInstance. In the jump method (wich will be called, when the user clicks on the screen) I tryed to change the vectorY Value like this: `this.behaviors.Platform.vectorY = -this.behaviors.Platform.jumpStrength;`. But nothing happens.

https://www.construct.net/en/forum/construct-3/scripting-51/trying-update-vectory-via-149176

## Attach a .c3p

[FlappyBirdJS.zip](https://github.com/Scirra/Construct-3-bugs/files/4026057/FlappyBirdJS.zip)

## Steps to reproduce

1. Create a Object
2. Add the platform behavior
3. Try to change the vectorY via js, so the object should jump

## Observed result

Nothing happens.

## Expected result

The object should jump.

## More details
I try to debug the problem, and think I found the problem. The setter for vectorY changes vectorX.

`set vectorY(a) { b.get(this)._SetVectorX(a) }`

**Affected browsers/platforms:** All

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.79
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 46 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced
WEBGL_video_texture
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Ah, there was a typo that meant it was setting the vectorX instead of vectorY internally. Fixed for next release.
