### ISSUE TITLE
crash after change size of sprite

### ISSUE THREAD

**Issue by thanhcuong90** [Scirra/Construct-3-bugs#3574]
## Problem description

after change sprite size -> Crash

## Steps to reproduce

MAC - firefox on MAC
1. Create new sprite , color it!
2. double click on sprite has been create
3. touch to change size to: 32x32 

=> Crash 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I can't reproduce this in r181. Please follow the bug report guidelines to ensure we can investigate your report.
