### ISSUE TITLE
Sprite Scale Problem

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#3576]
## Problem description

I found a strange Behavior, I think its quite new. If you switch through the Frames of a Sprite (which has frames with different aspect ratio) using the small arrows of the "initial Frame" tab, the sprite get deformed, the Scale changes. If you dont use the arrows but enter the frame Number, the Scale doesn't change.

## Attach a .c3p
[Sprite Error.zip](https://github.com/Scirra/Construct-3-bugs/files/4033019/Sprite.Error.zip)

## Steps to reproduce

1.Put the testSprite on the canvas. Be sure it has Xscale 100% ; Yscale 100%
2.switch through the frames back and foreward, using the arrows in the "initial Frame" tab
3.

## Observed result

Frames change their aspect ratio

## Expected result

Frames should always have an Scale of 100% x 100%

## More details

**Affected browsers/platforms:** 
I tested it in Chrome and Safari on a Mac

**First affected release:** 

## System details

<details><summary>View details</summary>
Platform information
Browser: Safari
Browser version: 13.0.4
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_2
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15
C3 release: r181 (beta)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_blend_minmax
EXT_sRGB
EXT_frag_depth
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBGL_compressed_texture_s3tc
WEBGL_depth_texture
WEBGL_draw_buffers
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)
</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
