### ISSUE TITLE
Group Description can't display line breaks correctly

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#3580]
## Problem description
Event Group Description can't display line breaks correctly.

Group Description  preview: [ [Construct 2](https://imgur.com/W90t24L) ] vs  [ [Construct 3](https://imgur.com/jtsydUN) ]

## Attach a .c3p
[link](https://www.construct.net/en/tutorials/turret-aim-1215)

_

**Comment by AshleyScirra** [comment]
Fixed for the next beta cycle. Note since we have a stable release scheduled soon, non-essential changes are being made only for the next beta cycle, so this will be fixed in the first beta release after the stable release.
