### ISSUE TITLE
[Whitelist] Build Service plugin cordova-plugin-email

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#3583]
I would like to request support for my new plugin: 

**cordova-plugin-email @latest_version**

Thank you :)

**Comment by ERAgames777** [comment]
https://github.com/Scirra/Construct-3-bugs/issues/3130#issue-467713780 when will mediation plugins be added?

**Comment by shortercode** [comment]
cordova-plugin-email@1.2.7 has been added to the whitelist
