### ISSUE TITLE
Failure to load javascript on start events

### ISSUE THREAD

**Issue by blueFireGames** [Scirra/Construct-3-bugs#3586]
## Error message says "Failed to load JavaScript on start of events" and I have not entered any JavaScript at all.

When trying to run the attached project it C3 crashes.  See screen shot of crash.

## .c3p attached.
[Template.zip](https://github.com/Scirra/Construct-3-bugs/files/4061086/Template.zip)

![temp](https://user-images.githubusercontent.com/8551252/72375666-7ca24080-36da-11ea-80e3-ae7c77e2ced3.png)

## Steps to reproduce

1.  Load Project
2.  Press the Preview Button
3.

## Observed result

  Project fails to start with an error message.

## Expected result

  Project going to the Splash Screen layout.

## More details

**Affected browsers/platforms:** Occurred on Microsoft Edge.

**First affected release:** <Release  171.3 Stable>

## System details

Platform information
Browser: Edge
Browser version: 18.18362
Browser engine: Edge
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362
C3 release: r171.3 (stable)
Language setting: en-US 
Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable) 
Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Canvas toBlob is not supported. Image processing performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
image-set() is not supported. Mouse cursors may appear with reduced quality.
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Microsoft
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:
WEBGL_compressed_texture_s3tc
OES_texture_float
OES_texture_float_linear
EXT_texture_filter_anisotropic
OES_standard_derivatives
ANGLE_instanced_arrays
OES_element_index_uint
WEBGL_debug_renderer_info
WEBGL_depth_texture
EXT_frag_depth
OES_texture_half_float
OES_texture_half_float_linear
WEBGL_lose_context
OES_vertex_array_object
WEBGL_draw_buffers
EXT_blend_minmax
EXT_shader_texture_lod
EXT_color_buffer_half_float
WEBGL_color_buffer_float
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:
Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)
Video information
Supported decode formats:
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This looks like an old bug we fixed ages ago, but for some reason some people still have old cached copies of a broken file. Clear your browser cache and try again and it should work. BTW the latest C3 release is r182 and your report was for r171.3.
