### ISSUE TITLE
iOS Browser Object Won't Open Links

### ISSUE THREAD

**Issue by adamjhoward** [Scirra/Construct-3-bugs#3588]
## Problem description

When using an iOS mobile device, such as an Iphone or Ipad, running the Safari browser, URLs don't seem to be opening or are blocked no matter what combination or workaround events I seem to use.

## Attach a [.c3p]
[iphone link test.zip](https://github.com/Scirra/Construct-3-bugs/files/4073722/iphone.link.test.zip)

## Steps to reproduce

1. Run the project either remotely or directly on an iOS device
2. Click on the button, or either of the solid rectangles (one is a 9patch, the other is a tiled background)

## Observed result

Observe that links do not open 

## Expected result

Should open google.com

## More details

Seems to be working on other operating systems and browsers (Windows, Android)

**Affected browsers/platforms:** 

Observed on r182

## System details

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.1_2
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0 Mobile/15B202 Safari/604.1
C3 release: r182.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
Service Workers are not supported. Construct 3 cannot be used offline in this browser.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Downloading local content is not supported.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Apple A7 GPU - 111.40)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple A7 GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by adamjhoward** [comment]
@shortercode  Thank you for looking into this

**Comment by AshleyScirra** [comment]
This should be fixed in the next beta; we had some code that could accidentally be blocked by popup blockers.

Note even with the fix, some ways of opening links in the project still don't work, because you can only open popups in a touch end event, and 'On touched object' fires when a touch starts. So you might need to adjust your events to take that in to account.

**Comment by adamjhoward** [comment]
Thank you @AshleyScirra, I'm glad it was something that was able to better Construct 3 as a whole - I'll take that into account and I'm looking forward to the next beta release.
