### ISSUE TITLE
Documentation - Scripting loadScripts nested folder clarification

### ISSUE THREAD

**Issue by broknecho** [Scirra/Construct-3-bugs#3589]
## Problem description

On the [iassetmanager](https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/interfaces/iassetmanager) documentation page, the `loadScripts` method description describes how to load scripts from a projects `Files` section but it does not describe the behavior of how scripts nested in folders work.  From trial and error, I figured out that even if you have scripts nested under folder names, you still just load them with their script name (no folder names needed).  This is a little confusing thinking how folders work normally but I see this is by design.

Would be good to just add another note to the documentation showing an example of loading nested files and showing you don't need the relative path folder name.

## Attach a .c3p

![image](https://user-images.githubusercontent.com/3253547/72583109-4adbd600-38a2-11ea-8f86-998c5ab51515.png)

## Steps to reproduce

See image above for example.  The issue is the difference between:

```
runtime.assets.loadScripts("script1.js", "nested/script3.js", "script2.js");  // ERROR loading script3.js (404)
```

and 

```
runtime.assets.loadScripts("script1.js", "script3.js", "script2.js"); // LOADS script3 fine (by design)
```

Contents of each script is:
```
console.log("script[1,2,3]");
```

## Observed result

Documentation does not show how to load a nested script.

## Expected result

Just a little clarification note on the documentation as to not trip someone up on this detail.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 79.0.309.65
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36 Edg/79.0.309.65
C3 release: r182.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 139 gb
Storage usage (approx): 46 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Hmm, good point. This applies to all IAssetManager methods, so I added a section at the top of the page explaining how to handle subfolders.
