### ISSUE TITLE
Rare crash "Aw snap" on preparing images for preview + a lot of RAM usage

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#359]
## Problem description

![alotofmemory](https://cloud.githubusercontent.com/assets/7268697/26449604/ca0beb4a-415b-11e7-902f-d1a2cf051530.gif)

My project crashes chrome every now and then with the "Aw snap... out of memory" message.
I checked the memory usage and it's really weird. Sometimes it can get up to **3.8 Gb** of usage while Preparing images happens.

![3gb](https://cloud.githubusercontent.com/assets/7268697/26449846/45015032-415d-11e7-8b2c-1534fb9b9a84.png)

![image](https://cloud.githubusercontent.com/assets/7268697/26449803/f9c39f26-415c-11e7-903f-f09869b80958.png)

Here's an example where I think windows compressed the memory, released something or stored it to the HDD, otherwise it would have crashed since I reached the usage of almost 100% of the memory (not C3 only of course....2 of them actually, and that's it :) )

![memoryproblem2](https://cloud.githubusercontent.com/assets/7268697/26449813/09c4d32c-415d-11e7-99ff-6baec3b049f6.gif)

## Attach a .c3p

The project I sent to Ashley could work. I barely did any modifications.

## Steps to reproduce

1. Load my project and start it
2. While it's preparing the images check the memory usage
3. (might need to close it and retry, the repro rate seems to not be great)

## Observed result

C3 sometimes using a lot of memory for "Preparing images"

## Expected result

I expect C3 to also release memory while it's preparing the images.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 193 mb (1.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Just to confirm it's different to #173, you don't have 'image recompression' enabled?

**Comment by JeFawk** [comment]
The "Preparing images" in this case happens when I try to preview the project locally. I've only found "Recompress images" option if I try to export it as NWjs.
Is it somewhere else as well?

**Comment by JeFawk** [comment]
It happened again today but on my desktop which has 16gb RAM compared to my laptop which has 8 if I remember correctly.
![alotofram](https://cloud.githubusercontent.com/assets/7268697/26588452/0cd3134e-455e-11e7-9d75-9c9642929171.gif)

**Comment by AshleyScirra** [comment]
There must be a memory leak somewhere. Surely with 64-bit Chrome and 16 GB RAM it should have enough memory to process even a very large project.

**Comment by triptych** [comment]
I'll bet this memory issue is related to the Android crash I'm seeing 100% of the time on bigger projects because memory is tighter on mobile devices https://github.com/Scirra/Construct-3-bugs/issues/436

**Comment by AshleyScirra** [comment]
Doubtful Glokar is relevant to this bug since it has minimal memory requirements.

**Comment by triptych** [comment]
I doubt it's that specific project, it's just an example of a larger project. The crash happens on the other demo projects as well

**Comment by JeFawk** [comment]
For some reason, after I loaded my project, Google Chrome kept using ~ 2GB of RAM for like 3 minutes even though I was not doing anything with the project.

**Comment by JeFawk** [comment]
Half of the time when it's preparing images it never frees up any memory.

![image](https://user-images.githubusercontent.com/7268697/26947200-896db308-4c9a-11e7-829f-0c3720e7db24.png)

When I'm done with the game it will have at least twice as many images, I don't wanna think what will happen then :S

**Comment by triptych** [comment]
Try running the same code in "Chrome Canary" the latest build for Chrome and see if you get the same results. I ran Chrome Canary on Android where I was crashing all the time on preview, and it seems to no longer happen. Perhaps you might also see different results.

**Comment by JeFawk** [comment]
Thanks, I'll do that when I'll get very desperate though.

**Comment by JeFawk** [comment]
I did try Canary and the memory usage was SO SMALL whilst preparing the images. However, it took 4 times longer than usual.
The compressing and such went very very slow. I'm unsure if it's a good trade off or not.

**Comment by triptych** [comment]
Canary builds are not final - it could just be that the builds are not optimized for speed yet.

**Comment by JeFawk** [comment]
It's super laggy when putting expressions in. Can't use :(

**Comment by triptych** [comment]
Yes, but is it crashing?  If not at least there's hope for a future chrome build to fix the memory issue as this will eventually get moved to chrome.

**Comment by JeFawk** [comment]
It did not crash, but I couldn't use it for long due to other numerous issues.

This is also related to issue #482 . When I loaded that file at some point in the image editor, **Aw, snap!**

**Comment by JeFawk** [comment]
**This thing has started appearing very often now. Any chance for a fix? I mean each time I load up my project it almost always crashes once or twice when preparing the images.**

**Comment by AshleyScirra** [comment]
Memory issues are one of the most difficult and time-consuming types of problem to investigate and solve. As ever, a minimal, public repro is an enormous help. Private projects are not as useful as we sometimes want to forward them on to a browser bug report, but that would make it public.

Also if Canary is not actually crashing due to memory usage, that does suggest it's a Chrome issue that's already been fixed. Canary can be very buggy for other reasons though, since it's had minimal testing.

**Comment by JeFawk** [comment]
I'll try these days to make a project in which this issue occurs. I guess I'll use a lot of public domain images that will replace my own. I'll be back :P

**Comment by JeFawk** [comment]
I've notice the following: if I open the project and check the spritesheets via right click on the project in the panel, the memory gets dumped way more often and I've almost never experienced a crash. C3 does peak between 2.7GB and 3.3GB but almost never crashes.
After this I can preview the project because it doesn't need to render/compress the images anymore.

Also 10-20 seconds after the spritesheet rendered, C3 goes to about 1GB ram, and then to 500 after several more seconds. So to my amazement, it's using 650MB now while previewing the game (so that's another 650MB). This is a **huge** improvement, even for a workaround.

**Comment by AshleyScirra** [comment]
Preview does the same thing as viewing spritesheets (i.e. one of the early steps of preview is to build and render all spritesheets, so they can be used at runtime). So I'd guess this is a GC timing issue, and simply doing "view spritesheets" and closing it gives the browser more time to run GC before starting preview.

**Comment by JeFawk** [comment]
Most of the crashes happen even before the preview starts, kinda when Preparing Images reaches 85%-95%

**Comment by JeFawk** [comment]
**By the way, I found a great (so far, I didn't test it **too much**) workaround for this.** I start up Chrome's dev tools of C3 and check my RAM usage when Preparing Images.
Till now the collect garbage has worked flawlessly and using it a few times made C3 not exceed 2GB RAM usage whilst previously it was going to 3.4GB regularly.

![image](https://user-images.githubusercontent.com/7268697/27046023-a679c4be-4fab-11e7-8323-7d65b846fbf5.png)

**Comment by AshleyScirra** [comment]
Canary updates daily, it'd be worth keeping an eye on that and seeing if it works better after a while.

**Comment by JeFawk** [comment]
Last time I tried everything was laggy. The daily updates are good and bad. I need a stable environment for my work, this is not a hobby for me. I really enjoy the garbage collection button ^^

**Comment by AshleyScirra** [comment]
Yeah, I just meant to see if this specific issue is resolved or not.

**Comment by AshleyScirra** [comment]
So it turns out Google are aware of some memory leaks and have been working on fixing them already. Spritesheet rendering involves heavy use of posting ArrayBuffers to a worker, which is exactly what some of these bugs describe:

https://bugs.chromium.org/p/chromium/issues/detail?id=702902
https://bugs.chromium.org/p/chromium/issues/detail?id=697192
https://bugs.chromium.org/p/chromium/issues/detail?id=698981

Two were fixed recently so will probably only be in Canary or Dev, and the only unfixed one appears related to iframes instead of workers, so may not affect spritesheet rendering. So chances are if you run Canary it should already work. Canary is a bit of a minefield and random other issues can crop up, but it seems a bit better today. I suspect this issue is already fixed and we just need to wait for the fix to work its way down to stable channel.

@JeFawk - could you confirm Canary no longer crashes? If you see any other bugs/issues/lag you can probably just ignore it as Canary quirks, so long as the original problem does not occur it's likely fixed.

**Comment by AshleyScirra** [comment]
OK, I think that pretty much confirms it's a Chrome leak that they fixed, so closing this report now. (It's no surprise if Canary has other issues, they'll likely catch them in testing)
