### ISSUE TITLE
Animations editor toolbar scrolling bug on mobile device

### ISSUE THREAD

**Issue by theprinceofdorkness** [Scirra/Construct-3-bugs#3590]
## Problem description

The top toolbar in the animations editor freezes up and will not continue to scroll left and right.

## Attach a .c3p

Not necessary.

## Steps to reproduce

Open any new project in latest version r182(and r182.2) and add a Sprite object. When attempting to edit the Sprite object in the animations editor the top toolbar freezes up after attempting to scroll left and right. 

## Observed result

Top toolbar freezes up and will not scroll left and right. 

## Expected result

The toolbar will continue to scroll left and right just as it did in previous stable releases. 

## More details

**Affected browsers/platforms:**
I've tested in Samsung browser and Chrome. Bug occurs in both browsers. I am using Android 10 on a Samsung S10e.

**First affected release:**
Works in r171.3 but not in r182+.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
