### ISSUE TITLE
Tilemap collision is not working using C2 runtime

### ISSUE THREAD

**Issue by Javanie7** [Scirra/Construct-3-bugs#3592]
## Problem description

When I was try to update my old game based C2 runtime, the tilemap collision is not working using Construct 3 r182, r182.2  but everything works good using version r171, r171.2, r171.3

## Attach a .c3p

[Tilemap Collision C2 Runtime.zip](https://github.com/Scirra/Construct-3-bugs/files/4083025/Tilemap.Collision.C2.Runtime.zip)

## Steps to reproduce

1. Add a sprite with platform behavior.
2. Add a solid collision for platform.
3. Add a tilemap
4. Draw tilemap on canvas
5. Add Browser plugin
6. Add a event: 
```
+ Sprite2: On collision with Tilemap
-> Browser: Alert "Collision"
```
7. Run preview

## Observed result

When the sprite2 on collision with Tilemap, nothing happen but when I try switch to C3 runtime then re-run preview, Sprite2 on collision with tilemap is working (browser alert "Collision")

## Expected result
Tilemap collision should be working on C2 runtime.

## More details

Affected browsers/platforms: Chrome on Windows 10

worked in lower version r171.3 but broke in above r182

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.117
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
C3 release: r182.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 123 gb
Storage usage (approx): 200 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon Pro 560 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
