### ISSUE TITLE
Can't navigate with arrow keys in Event Windows (Dark Theme)

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3593]
Same issue : https://github.com/Scirra/Construct-3-bugs/issues/2360

![20-01-19-23 34 43](https://user-images.githubusercontent.com/2965842/72688007-7d8d0500-3b14-11ea-99c1-b787b0274a36.gif)

## Steps to reproduce

1. Use Dark Theme or White Theme
2. Open event/action, add behavior/effect/object windows and try to navigate with arrow keys.

**Comment by AshleyScirra** [comment]
Looks like a different cause this time, with the item boundaries having floating point precision errors for some reason. Should be fixed in the next beta.
