### ISSUE TITLE
Audio plugin not setting the volume right on "playing"

### ISSUE THREAD

**Issue by ItemME** [Scirra/Construct-3-bugs#3594]
## Problem description

Audio plugin, is sometimes, for some reasons, playing an audio file way too high compared to the value you're putting in. And it will happen until you reboot (video down below)

## Attach a .c3p

We can't manage to reproduce it on 100% case.. We have no clue whatsoever is causing this, we just know for sure that it's not coming from our game's code (we tried for several hours with @skymen which is working on the game)

## Steps to reproduce

Watch the video, I'm afraid we have nothing more (and we know it's gonna be hard to reproduce, but please, consider this)

## Observed result

https://www.youtube.com/watch?v=pRholHzxNKQ

We recorded this after hours trying to reproduce it for this bug report, so you'll hear me trying to explain what's going on, and showing it with some console logs to prove my point.

## Expected result

Audio shouldn't play that loud, especially when the volume that has been set, seems to be the right one.

## More details
I'm afraid as I said, we have no clue what's causing this, we think it's a bug from the web audio itself, but we could be wrong, what we're sure is, it's not the code, since we're just setting the volume as we wish it to be.

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.43.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.43.1 (like Chrome/79.0.3945.79)
C3 release: r182.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 196 gb
Storage usage (approx): 182 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid we have no way to investigate this. The bug report guidelines are required because they are necessary for us to be able to help.

FWIW, the audio engine is managed by the browser/OS, not Construct. So chances are this isn't a Construct bug either. It would be useful to test across different browsers and OSs to see if it reproduces consistently or only on certain systems since that may help identify the circumstances the issue occurs in.

I also noticed your system information includes an unusual system sample rate (`System sample rate: 192000 Hz`). This is an unusual consumer setup; most consumer systems run at 44.1 KHz or 48 KHz. 192 KHz suggests an uncommon studio-grade setup which may be related to the issue.

**Comment by ItemME** [comment]
Just so you know @AshleyScirra - we really wish me and @skymen that we could have reproduce it perfectly, but right now, this issue seems to be happening for very random reasons.

Also you said that it might be specific to my hardware or configuration, it's not, we've a few testers that had this issue too (and they have various audio configuration, not the same as me which indeed, is very specific) but it's not caused by this for sure. We also reproduced it on a Chrome browser, the desktop version of construct in preview, and our exported build, under Electron.

This seem to be a very important bug, as on our side, there's nothing code wise we can do to solve this, pre-load doesn't help, changing volume doesn't help (as you saw in the video) and functions such as "fade audio" won't work either.

So I'm really unsure what to tell you, other than, we have no clue whatsoever is happening, and we hope someone in the scirra team has any idea where that could come from, because it's annoying, and we as users of Construct, can't solve it.

**Comment by AshleyScirra** [comment]
I suggested that you test other browser engines, such as Firefox, Edge and Safari. So far you have only tested the Chromium engine. This will help you identify whether the issue is specific to the Chromium engine.
