### ISSUE TITLE
Sound buffer problem in Safari 13

### ISSUE THREAD

**Issue by QkyGames** [Scirra/Construct-3-bugs#3595]
Hello,

my last construct 3 games arenot working in safari, I get this debug message.

Construct 3 version: r182.2 (c2 runtime)

The operation is not supported: createBuffer c2runtime.js.22313

Best,
Maxi.

qkygames.com/knife-climb

**Comment by AshleyScirra** [comment]
I'm afraid this type of issue is not useful (please see the bug report guidelines) but I just filed https://github.com/Scirra/Construct-3-bugs/issues/3596 for the same issue anyway.
