### ISSUE TITLE
C2 runtime projects not working in Safari 13

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#3596]
## Problem description

C2 runtime projects using WebM Opus audio don't work in Safari 13.

## Attach a .c3p

Use Space Blaster

## Steps to reproduce

1. Switch Space Blaster to C2 runtime
2. Preview project

## Observed result

Preview fails to load. Error in console about `createBuffer` operation not supported

## Expected result

Preview should load successfully

## More details

It looks like the Opus decoder returns an ArrayBuffer, and buffer.length is passed to createBuffer. However this property does not exist on ArrayBuffer. It has a byteLength, but that's probably not what you want to pass to createBuffer, since it needs to be in samples not bytes. I would guess this was meant to be a typed array but gets a raw ArrayBuffer instead.

Looks like the C3 runtime isn't affected. Not sure why this has only just come up, maybe Safari used to have a non-standard length and removed it?

**Comment by shortercode** [comment]
Appears that it was broken in the #3481 fix, so it's probably just not been noticed during the beta cycle ( kinda frustrating ).

It appears that originally the decoder was returning a ArrayBufferView in the C2 runtime, but a ArrayBuffer in the C3 runtime.

**Comment by shortercode** [comment]
Resolved for next beta.
