### ISSUE TITLE
Build Service doesn't work for Signed exports (r183)

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#3598]
## Problem description

The buildservice throws a error message when i choose - Export - Android - Signed Android App Bundle 

**Error: Unknown build mode**

[View Screenshot](https://drive.google.com/open?id=1JwA7WZgCFrKVx37mrlUsY1Z3WAHxfnLb)

.. and dont work with " **signed android apk** " too ...

## Steps to reproduce

1. Create/Open any project.
2. Go to Export - Android - Signed App Bundle
3. After "Build" - Error Message

## Observed result

Error Message

## Expected result

No Error Message

**Affected browsers/platforms:** 

Windows 10 - Construct 3 Standalone Application

**First affected release:** 

r183 Beta

## System details

( Sorry, but this dont work too - [another bug](https://github.com/Scirra/Construct-3-bugs/issues/3599) )

**Comment by shortercode** [comment]
Confirmed that this appears to be an issue in the release, interestingly doesn't appear to affect my test environment so going to have to take a closer look at what the release is doing.

**Comment by shortercode** [comment]
It would appear that some changes to a particular file didn't end up in the release. I've added it now, should be fixed in the next beta.

**Comment by masscube** [comment]
Thank you. Is a "fast" hotfix possible?
..i need that for a customer...

**Comment by shortercode** [comment]
I think we're considering a beta release tomorrow, but it makes sense to wait a little longer to see if any other issues appear. This should only be affecting the beta release, could you not just use the stable release?

If you do need the beta then you can export an unsigned release and sign it yourself.
