### ISSUE TITLE
Construct 3 crash when i click on about -platform information

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#3599]
## Steps to reproduce

Sorry for the short description, but construct 3 standalone application (windows 10) crashes when i click on **about** - **platform information**

The error-message:

Error report information
Type: unhandled rejection
Reason: Error: t.push(...).catch is not a function @ TypeError: t.push(...).catch is not a function at Object.ǃNIV (https://editor.construct.net/r183/main.js:156:1018) at Object.ǃNj (https://editor.construct.net/r183/main.js:210:1027) at HTMLAnchorElement.ǃqaN.onclick (https://editor.construct.net/r183/main.js:63:176833)
Stack: TypeError: t.push(...).catch is not a function at Object.ǃNIV (https://editor.construct.net/r183/main.js:156:1018) at Object.ǃNj (https://editor.construct.net/r183/main.js:210:1027) at HTMLAnchorElement.ǃqaN.onclick (https://editor.construct.net/r183/main.js:63:176833)
Construct 3 version: r183
URL: https://editor.construct.net/r183/
Date: Mon Jan 20 2020 20:50:09 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 138.3 s

Unable to collect further diagnostic information because a promise rejection occurred while trying to collect it.

**Comment by AshleyScirra** [comment]
Looks like all platforms are affected, not just the desktop app. Oops, one of our changes broke it. Should be fixed in the next release.
