### ISSUE TITLE
Crash when pasting events that contains objects that aren't in your project

### ISSUE THREAD

**Issue by IJCT95** [Scirra/Construct-3-bugs#36]
## Problem description

R16
if you try to paste any event that contains an object that you don't have on your project it won't show a pop up telling you that you can't paste that (like in c2), instead C3 will crash

## Steps to reproduce

1. create a new project
2. create a variable and any event using that variable
3. copy just the event using the variable
4. delete all the events and the variable
5. paste
6. crash error

## Observed result

Construct 3 decided to crash instead of showing a pop up

*What do you see happen?*
fatal error

## Expected result
a pop up must appear telling the user that it can't do that like in C2.

*What did you expect to happen instead?*
a pop up must appear telling the user that it can't do that like in C2

## Affected browsers

* Chrome: YES

## System details

im on a MAC

**Comment by jaydonteh** [comment]
Just to add to this report:

C3 helper actually prompts and does not crash if you paste an event with an object referenced that is not recognised or not in this project, **but** if the pasted event has an unknown instance, it will crash.

**Comment by jaydonteh** [comment]
## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Unknown expression 'helloWorld': This is not a system expression or variable name in this scope.
Construct 3 version: r16
URL: https://editor.construct.net/index.html
Date: Sat Apr 08 2017 00:14:05 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 825.6 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
This report sounds like it's to do with objects but the repro steps only cover variables. I could reproduce a problem with variables and it should be fixed in r18. If there is another problem involving objects, please file that separately.

**Comment by jaydonteh** [comment]
No issues involving objects as far as I can check, only variables are the culprit.
