### ISSUE TITLE
When you change the initial animation of a sprite, it doesn't change its size.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3603]
## Problem description

When you change the initial animation of a sprite, it doesn't change its size. The size will be same as the last animation and new animation won't be 1:1.

![20-01-22-16 43 31](https://user-images.githubusercontent.com/2965842/72901516-fc638700-3d3a-11ea-8b91-11602a2d115f.gif)

## Steps to reproduce

1. Change the initial animation of an object.

**Affected browsers/platforms:** 

**First affected release:** r182.2

**Comment by DiegoScirra** [comment]
This is fixed in the next beta. There were some changes around that part of the code base in the previous beta cycle, and this one slipped through unnoticed.
