### ISSUE TITLE
Tilemap with Solid behavior still blocks 8Direction movement when collision on tiles is disabled

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#3605]
## Problem description

If a sprite with the 8Direction movement is on a tilemap tile, and the tilemap has the Solid behavior, the 8Direction sprite is blocked, even if the tile's collision is disabled.

## Attach a .c3p

[Bug.zip.zip](https://github.com/Scirra/Construct-3-bugs/files/4099991/Bug.zip.zip)

## Steps to reproduce

1. Create a new project with a sprite and a tilemap
2. Assign the 8Direction behavior to the sprite
3. Assign the Solid behavior to the tilemap
4. Fill the visible area of the tilemap with any tile
5. Disable tile collision for that tile
6. Put the sprite on the visible tiles and run the game
7. Use the arrow keys to move the sprite

## Observed result

The sprite doesn't move

## Expected result

Tiles without collision shouldn't block sprites with the 8Direction behavior (or any other behavior that reacts to the Solid behavior).

## More details

**Affected browsers/platforms:** 

**First affected release:** 

I assume the first affected release was the one where tilemap collision disabling was added since that was so recent, but I'm on 183.2 Beta.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
C3 release: r183.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 2.4 gb
Storage usage (approx): 274 mb (11.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GRID K120Q Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I can't produce any issue myself on r183-2. Created a new project using your steps and it worked as expected. Also tried your example project and that appeared to work correctly. Assigning to @DiegoScirra to see if he has anything to suggest.

**Comment by Scoremonger** [comment]
I just tried it again and you're right, there seems to be no problem now. I got a crash that I wasn't able to reproduce soon after reporting this - maybe something weird was going on with my C3 instance? Or perhaps I made a mistake when testing. Wouldn't be the first time... Anyway, sorry for wasting your time if this was my error - seems likely!

**Comment by shortercode** [comment]
Could be related to the crash I guess. Do you often have the chrome developer tools open while working? I know some users do. Due to the way Chrome often shares processes for windows if one window is paused on a breakpoint it can cause others to freeze. I've been caught out by this in the past, thinking one thing is broken when in fact it's just been paused by something seemingly unrelated.

**Comment by Scoremonger** [comment]
Ah, yes, I sure do have the Chrome dev tools open almost all the time. I didn't consider that it might've been something like that. Good to know, thanks!

**Comment by DiegoScirra** [comment]
It looks like it is working fine, closing.
