### ISSUE TITLE
Low quality on resized sprite

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#3607]
## Problem description

Hi! When you try to resize a sprite (using mouse, inside a layout), it loses it's quality and finaly looks like it has bad resolution. I made a random shape and a simple project in order to reproduce the problem.

## Attach a .c3p

[resize bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4105360/resize.bug.zip)

## Steps to reproduce

1. Open attached project
2. Resize the sprite
3. Observe quality loss

## Expected result

Not losing quality

## More details
(Resize was made simply, using mouse and dragging a corner of the sprite)
![resize](https://user-images.githubusercontent.com/53188782/73022298-fe5c4180-3e31-11ea-8999-a9ab0e63a52c.jpg)

**Affected browsers/platforms:** Chrome/Firefox

**First affected release:** Not sure

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.130
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
C3 release: r183.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 122 gb
Storage usage (approx): 180 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is how mipmapping works and it is a normal result in computer graphics. The GPU uses the smaller dimension of the image for the quality. Normally when images resize keeping the aspect ratio, this doesn't matter.
