### ISSUE TITLE
There is something doesn't work

### ISSUE THREAD

**Issue by Timurezik** [Scirra/Construct-3-bugs#361]
## Problem description

*There is something wrong in my program. If you know, please answer to me. Maybe there is a bug.*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.Look in event sheet
2.Play the project
3.Try to press buttons.

## Observed result

*My program doesn't work.*

## Expected result

*It must work*

## Affected browsers

* Chrome: yes/no
* Firefox: 
* Edge: 
* Safari:

## Sy
[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/1029850/New.project.zip)
stem details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This is not the correct way report an issue. You have to explain what is wrong and how to reproduce the problem. Otherwise we can't help you.
