### ISSUE TITLE
Open default email program on mobile

### ISSUE THREAD

**Issue by OziAz** [Scirra/Construct-3-bugs#3611]
## Problem description

Have a link that opens up the default email program on phone by visiting a "mailto" link. All seems to work until it is used in a APK installed file.

## Attach a .c3p

Included is a project file and the export that I tried on my phone which is not working.
[SupportEmail.zip](https://github.com/Scirra/Construct-3-bugs/files/4113122/SupportEmail.zip)

## Steps to reproduce

1. Create a browser plugin in the layout. 
2. Create a button and have an action on to open url in a new window. The url used is "mailto:recipient@example.com".
 OR make a button and have it run javascript "window.location.href = 'mailto:address@dmail.com';"
3. Run a remote preview on a phone. Everything works as expected.
4. Export apk file and install on phone.
5. Try pushing the buttons and nothing happens.

## Observed result

Nothing happens when pressing the buttons.

## Expected result

Open default email program on the phone as it does in preview mode

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in next beta.
