### ISSUE TITLE
No ok button to close and confirm include event sheet dialog on mobile

### ISSUE THREAD

**Issue by theprinceofdorkness** [Scirra/Construct-3-bugs#3612]
## Problem description

When trying to include one event sheet with another, no ok button appears in the dialog box to confirm and close the dialog. 

## Attach a .c3p

Couldn't get zip to work... here's an example pic. 
![Screenshot_20200126-170405_Chrome](https://user-images.githubusercontent.com/60025228/73143426-490ed100-405f-11ea-8de4-3486186b0e64.jpg)

## Steps to reproduce

1. Open any new project.
2. Add a new event sheet.
3. In event sheet tab click to include event sheet. The dialog as pictured above appears. 

## Observed result

Dialog box appears. You can select the event sheet to include, but there is no ok button to confirm and close the dialog. 

## Expected result

Dialog box will have an ok button just as it appears on desktop. 

## More details

**Affected browsers/platforms:** 
Chrome browser on Android device. 

**First affected release:** 
Problem has occurred in every release that I've used. 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Huh, that's odd, looks like it's always been like that. Must have been an oversight. Should be fixed in the next beta.
