### ISSUE TITLE
NWjs Fullscreen Allows Exiting With ESC Key

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#3614]
## Problem description

It's currently possible to exit out of fullscreen mode in NWjs using the ESC key. This behavior can only be reproduced using Construct 3 and works fine in Construct 2.

## Attach a .c3p
[Fullscreen Test.zip](https://github.com/Scirra/Construct-3-bugs/files/4117209/Fullscreen.Test.zip)

## Steps to reproduce

1. Open example in C3
2. Run NWjs preview or export using NWjs
3. When ready, press mentioned key to enter fullscreen
4. Press ESC key and notice exit out of fullscreen mode

## Observed result

You can exit fullscreen in NWjs using the ESC key. (Only able to reproduce in C3.) 
I can reproduce this in versions below r125 but only with the C3 runtime enabled. Able to reproduce with any runtime when using r125+.

## Expected result

The ESC key should automatically be blocked as it is in C2.

## More details

**Affected browsers/platforms:** NWjs 0.43.1 (Desktop build)

**First affected release:** Broke in r125 ([changelog](https://www.construct.net/en/make-games/releases/beta/r125))

## System details

<details><summary>View details</summary>
Platform information
Browser: NW.js
Browser version: 0.43.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.43.1 (like Chrome/79.0.3945.79)
C3 release: r183.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 136 gb
Storage usage (approx): 171 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
In r125 we changed the fullscreen implementation from NW.js's own one ([enterFullscreen](http://docs.nwjs.io/en/latest/References/Window/#winenterfullscreen)) to the standards-based requestFullscreen as used in browsers. We use the browser code wherever possible to ensure we have the same code everywhere, and to make sure code works the same as it does, since any divergences tend to result in bug reports. For example if NW.js blocks ESC in fullscreen but browsers do not, we could equally expect a bug report along the lines of "ESC lets me exit fullscreen in the browser, but not in NW.js, please make it work the same in both". This type of thing causes compatibility problems when porting between platforms, and a key goal of Construct is to eliminate as many such barriers as possible.

So although the behavior changed, this aligns it with what browsers do, which is our intent.

**Comment by TheRealDannyyy** [comment]
Well a user reported that he doesn't want that behavior to happen inside his desktop game and I wouldn't want that either. What options do we have to prevent players from exiting fullscreen using the ESC key?

**Comment by TheRealDannyyy** [comment]
@AshleyScirra I know you don't like it when people overstate the severity of their issues. This is however one of those cases where it is serious. In my opinion, there isn't a single desktop game without an "ESC Pause Menu". This change makes it difficult if not impossible for users to provide such a menu, while the game is in fullscreen mode.

I'm fully aware and respect the decision you made, to make the browser plugin more convenient to work with but leaving mostly unaware users out in the dark like this, without a workaround is not a good look in my opinion. Again I fully accept your decision but I highly recommend to at least provide a workaround in form of plugin actions, as being shown in my example below. This would require next to no maintenance and coding it into the NWjs plugin should be an easy task for your team.

Workaround Example: 
[FullscreenKeyWorkaround.zip](https://github.com/Scirra/Construct-3-bugs/files/4117979/FullscreenKeyWorkaround.zip)

**Comment by AshleyScirra** [comment]
It's been over a year since we made this change, which suggests it is a low impact issue.

NW.js has a kiosk mode, maybe that would do the trick?

**Comment by TheRealDannyyy** [comment]
Based on community feedback we've received in the unofficial Construct Discord. Most people seem to be afraid or straight up refuse to report bugs anymore, since the reports are mostly being closed without further help or workarounds. 

My workaround is basically just using the code that has been removed (can be found in the manual). I'm currently unaware of any other methods to block the "ESC" key from exiting fullscreen mode, while allowing users to access the key with events. Would appreciate a link so we can continue the conversation there. I still recommend providing the mentioned code of my example, as actions inside the NWjs plugin. Would make it more convenient on both ends in my opinion.

**Comment by AshleyScirra** [comment]
This change was made in November 2018 so it hardly seems like an emergency. I sent an email to the NW.js email group to find out more about this. (You can always send this group emails too if you have questions/thoughts/requests, which is what I was getting at.)

On the issue of reporting bugs, unfortunately sometimes people file issues that are impossible to investigate. As described in the bug report guidelines, our policy is to close these, which is aimed at guiding people to getting in the habit of filing bugs that we can actually help them with, ultimately resulting in better quality software for everyone. Leaving the issue tracker to clog up with hundreds of issues we can't do anything about would hardly be an improvement (and would probably make things worse as it would signal that reports lacking essential details are acceptable, or just awaiting later investigation).

Insisting that we do the impossible and fix issues that cannot be investigated, and then using it as a reason to pressure us in other bug reports, qualifies as unnecessarily combative under our [forum & community guidelines](https://www.construct.net/en/forum/general/open-topic-33/forum-community-guidelines-141035) so I'm locking this issue thread now.
