### ISSUE TITLE
Timeline's absolute result mode not previewing correctly in editor

### ISSUE THREAD

**Issue by Animmaniac** [Scirra/Construct-3-bugs#3615]
## Problem description

"Absolute" Result Mode for timeline doesn't preview correctly in editor, only runtime. It wrongly previews as "Relative" in editor.

## Attach a .c3p

[timeline-result-absolute-bug-A01.zip](https://github.com/Scirra/Construct-3-bugs/files/4120693/timeline-result-absolute-bug-A01.zip)

## Steps to reproduce

1. Preview the project
2. Observe correct result on preview
3. Open the timeline "Timeline 1" on the Timeline Bar
4. Press play on the Timeline Bar
5. Observe wrong result in editor

## Observed result

On step 2 (project preview): the blue sprite moves from position (0,0) to (500,500) since "Timeline 1" Result Mode is set to "Absolute"

On step 4 (in editor preview): blue sprite moves from it's current position (1000,500) to (1500,1000) as if "Timeline 1" Result Mode was set to "Relative"

![timeline-result-absolute-bug-A01](https://user-images.githubusercontent.com/29487913/73236232-5cf62800-4170-11ea-96b9-651de1e3d074.jpg)

## Expected result

The blue sprite should be moving along the blue path in editor

## More details
**Affected browsers/platforms:** Chrome, Windows 10

**First affected release:** only tested on r184 Beta

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 79.0.3945.130
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
C3 release: r184 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 224 gb
Storage usage (approx): 296 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 850M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
