### ISSUE TITLE
Functions and Families and UIDs bug

### ISSUE THREAD

**Issue by kidswithcrowns** [Scirra/Construct-3-bugs#3617]
## Problem description

If you use For Each to pass the UID of objects into a function, and then have that function pick a Family Object that has the same UID, and then return a variable based on that object, it doesn't work UNLESS you put the "Pick By UID" as a subevent

## Attach a .c3p

[Buggg.zip](https://github.com/Scirra/Construct-3-bugs/files/4124552/Buggg.zip)

## Steps to reproduce

1. Open Project
2. Note how one square has "2" as a variable and the other has "10"
3. Run Preview
4. Open the console and view results
5. Disable incorrect group and enable correct group
6. Run Preview Again
7. Open console again and view results

## Observed result

The output in the first group is "2" and "0", which is incorrect

The output in the second group is "2" and "10", which is correct

## Expected result

It should be returning "2" and "10"

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** First noticed in r/184

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.70
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36
C3 release: r184 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 7.8 gb
Storage usage (approx): 94 mb (1.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
Thanks for the report, this turned out to be a complicated initialisation sequencing issue when optimising instance picking on startup. I think I found a way to cleanly resolve it so it should be fixed in the next beta.
