### ISSUE TITLE
Sprite editor: Mirror horizontally & Mirror Vertically Tooltips

### ISSUE THREAD

**Issue by Straskal** [Scirra/Construct-3-bugs#3618]
## Problem description

The tooltips for mirror horizontally & mirror vertically are switched.
The tooltip for mirror horizontally is Ctrl + F (which is the shortcut for mirror vertically) & vice versa.

Browser: Chrome
Construct version: v 182.2 stable

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
