### ISSUE TITLE
Regression in r184 where C3 desktop fails to open a folder project

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3619]
## Problem description

My game opens fine with 183-2, and fails to open with 184

## Attach a .c3p

n/a Given the minified nature of the bug, and the fact that it happens so inconsistently, I have no idea what would be causing it, and there is no plausible way for me to find out.

## Steps to reproduce

n/a Given the minified nature of the bug, and the fact that it happens so inconsistently, I have no idea what would be causing it, and there is no plausible way for me to find out.

## Observed result

![Construct3_2020-01-29_01-28-16](https://user-images.githubusercontent.com/11213825/73317533-ac069080-4236-11ea-965d-57e3a36d2f13.png)

## Expected result

The project should open

## More details

**Affected browsers/platforms:** Desktop NW.js, I tested on Chrome with the experimental folder opening feature and it worked fine 

**First affected release:** r184

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.43.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.43.2 (like Chrome/79.0.3945.88)
C3 release: r184 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 2.9 gb
Storage usage (approx): 632 mb (21.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to do anything about a report like this. We have no way to investigate it.

Can you find a way to reproduce the issue?

**Comment by AshleyScirra** [comment]
Actually you're in luck, this time I was able to reverse engineer it from the crash message alone.

It happens every time if your project uses bundled addons. It's a regression caused by fixing #3604. It should be working in the next beta.
