### ISSUE TITLE
iOS XCode project generated from the build service issue

### ISSUE THREAD

**Issue by rhg1968** [Scirra/Construct-3-bugs#362]
## Problem description
I generated an XCode project for iOS 10+ through the build service for a few of the sample games on the C3 home page. For each one I unzipped the file on my mac, opened it in XCode, and attempted to run it on the iOS simulator. In each case the app launched, I saw the cordova splash screen, and then the screen just went to black and the game never displayed.
*Enter a concise description of your problem here*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.Open the Flappy Bird clone template
2.Export the project for Cordova and select all the check boxes. Also select iOS 10+
3.Click on the build button and download the zip file.
4.Extract the zip file on the mac and open the xcode project
5.Run the project on the simulator, I did the IPhone 7+

## Observed result
The cordova splash screen appeared and then the screen went black. Nothing else would happen.
*What do you see happen?*

## Expected result
The flappy bird clone game running in the simulator

*What did you expect to happen instead?*

## Affected browsers
Chrome
* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by pwrtoppl** [comment]
I too have seen this issue on every export for iOS I have done. Tested on iPhone 7 and iPhone 5SE as Testflight apps. 
The emulator does also run blank.
I saw a note about someone getting iOS to work by disabling 'preload sounds,' but it didn't work for me.

**Comment by shortercode** [comment]
Okay can confirm this, looks like an issue with the minifier. Should work if you don't enable minification for the time being.

**Comment by shortercode** [comment]
Right patch is done, part of the iOS specific runtime was being broken when it was minified. You'll have to wait for the next release to see the fix, but as I said you can just build without minification for the time being.
