### ISSUE TITLE
Unexpected results adding keyframes to timeline with "Absolute" result mode

### ISSUE THREAD

**Issue by Animmaniac** [Scirra/Construct-3-bugs#3620]
## Problem description

Adding new keyframes to a timeline with "Absolute" Result Mode after the object's initial position has been changed causes unexpected results.

## Attach a .c3p

[timeline-result-absolute-bug-A01.zip](https://github.com/Scirra/Construct-3-bugs/files/4126095/timeline-result-absolute-bug-A01.zip)

*The example was generated by:

> 1. Creating timeline "Timeline 1"
> 2. Placing Sprite to position (0, 0)
> 3. Adding the Sprite instance to "Timeline 1"
> 4. Entering "Editing mode" on the Timeline Bar
> 5. Setting a keyframe at 0s
> 6. Moving timeline's cursor to 5s
> 7. Moving Sprite to position (500, 500)
> 8. Setting a keyframe at 5s
> 9. Exiting "Editing mode" on the Timeline Bar
> 10. Setting "Timeline 1" Result Mode to "Absolute"
> 11. Moving Sprite's initial position to (1000, 500)

## Steps to reproduce

1. Open the timeline "Timeline 1" on the Timeline Bar
2. Enter "Editing mode" on the Timeline Bar
3. Move the timeline's cursor to 2s
4. Set Sprite position to (1000, 0)
5. Set keyframe on Sprite
6. Observe unexpected result

## Observed result

![timeline-result-absolute-bug-B02](https://user-images.githubusercontent.com/29487913/73327013-17e6fa00-4233-11ea-9d41-d4b4de66159f.jpg)
A node is inserted at an unexpected place, as if the saved position was relative to the Sprite's original position instead of current position.

## Expected result

![timeline-result-absolute-bug-B01](https://user-images.githubusercontent.com/29487913/73327188-c12df000-4233-11ea-9450-c7286e4b5f1d.jpg)
A node should be added to Sprite's current position.

## More details

**Affected browsers/platforms:** Chrome, Windows 10

**First affected release:** only tested on r184 Beta

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.130
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
C3 release: r184 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 224 gb
Storage usage (approx): 296 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 850M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed as result from fixing #3615
