### ISSUE TITLE
layout scale/resolution - influence on z elevation

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#3621]
## Problem description

I just realized that I have to adapt the z Elevation if a want to change the resolution/Layout Scale of my project. I am not sure if this is a Bug, so I report it here before I adapt my project. The Idea is to change the resolution for some low end devices, but having the same visual result in the end (in lower quality of course). By making this Bugreport Repro, another Thing appeared that may be related, not sure.

## Attach a .c3p

[a_parallax_problem.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4128542/a_parallax_problem.c3p.zip)

## Steps to reproduce

1.preview Project- press "go to next Layout"
2.take a look at the blue square- then go back
3.change to half resolution- "go to next Layout"
4.see the difference of the square compared to full resolution
(an additional thing - not sure if this is related)
5. go back change to to full resolution
6. "go to next Layout" -the blue Square is not there at all
7. go back, go again to next Layout without manipulation resolution - the blue Square is there

## Observed result

the blue Square change its place

## Expected result

the blue square remains on the same place
## More details

if you activate the z elevation actions in the project then everything is ok. (only the first disappeared blue square after changing back to full resolution problem remains)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.130
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_2
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
C3 release: r184 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 67 gb
Storage usage (approx): 405 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think this is a combination of 2 mistakes:
1) you change the layout scale with bounded scrolling on the layouts, so the layout size interferes with the scroll position. Tick 'unbounded scrolling' to stop that.
2) the layer scale is a 2D transform, and Z elevation is a 3D transform. So changing the layout scale will not display the same Z elevation result afterwards.

**Comment by bubbblebub** [comment]
ok, thanks for the answer!
