### ISSUE TITLE
Selecting sprite (sheet) file does not  show .gif files

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#3622]
## Problem description
If you select a file to load images into a sprite object .gif files are not shown in the dialog.

## Steps to reproduce

1. add sprite object
2. load image OR rightclick > import frames
3. the dialog does not  show .gif files (but loading gif works)

## Observed result
GIF files are not shown by default.

## Expected result
GIF files should be listed

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
r183
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.130
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
C3 release: r184 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 1.1 gb (1.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 615 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Note we can allow picking GIF files but it will only import the first frame, because browsers currently don't have any way to extract all the frames of a GIF file.

**Comment by TheBl4ckSh33p** [comment]
Would be very nice if you could add it. Most of the preloaders and some sprites I use are .gif spritesheets.

**Comment by AshleyScirra** [comment]
I'm afraid it's not really feasible right now since we have no way to extract the subsequent frames.

**Comment by XHXIAIEIN** [comment]
You can use this tool split gif to sprite sheet
https://ezgif.com/gif-to-sprite

**Comment by DiegoScirra** [comment]
As of the next beta it is possible to import .gif files into the Animations Editor. Only the first frame of the animation though, as rolling out our own implementation would be extremely error prone and not really worth the trouble.
