### ISSUE TITLE
[Warnings / Deprecated] iOS

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#3623]
## Problem description

I got a lot of warnings (deprecated) on iOS (xcode). Look here:
[Screenshot 1](https://drive.google.com/open?id=1ViZ44aj0X4l8WpmhVmGURUB3JZkDNUBc)
[Screenshot 2](https://drive.google.com/open?id=1_UxuUc3C4InPLY26djGWm-hJS3_vwqAj)
## Attach a .c3p

( empty project )

## Steps to reproduce

+ Export to iOS xcode.
+ Build App

**Comment by AshleyScirra** [comment]
These all appear to be warnings in internal Cordova code. Often warnings are unimportant (for example warning about deprecated features that are only there to support old platforms). If it doesn't affect the build in any way you can probably just ignore it. Also it's all Cordova's code so it would be up to them to make any changes there anyway. You could try reporting it to Cordova directly, but they may say the same thing.
