### ISSUE TITLE
IOS Build (export xcode proj) = can't disable SplashScreen (small C3 logo)

### ISSUE THREAD

**Issue by smallsim** [Scirra/Construct-3-bugs#3624]
## Problem description
When IOS Build (export xcode project), then build App in Xcode and release (or using TestFlight), SplashScreen (small Construct3 logo on very start of app) still shows.

In C3:
- Use Loader layot = Yes;
- LoaderStyle = Nothing;

## Steps to reproduce

1. Export from C3 - xcode project
2. Build xcode
3. Release or TestFlight the App

## Observed result

Unexpected picture on start of the App.

## Expected result

No any picture on start of the App (how it was before).

## More details

This image with c3-logo named Defaultx2-anyany.png Even delete this  file or replace(!) it = nothing chages, it shows anyway. Tried disable it via xcode (total disable spalshes or loading images) = still show this small logo.

(!) Replace to other image do not work - I tried to replace this .png to another picture to see it when the App will launched but there is still this image with c3-logo, so the problem in this somewhere.

## Version C3
Since r182 I think but I'm not sure.
Reproduce in stable 182.2 and latest beta.

**Comment by AshleyScirra** [comment]
This is an issue with iOS, not Construct. The correct files to change are in LaunchStoryboard under Images.xcassets in Xcode. However iOS will cache the first one you used until you:

1. Delete the app from the device
2. Power down the device
3. Power up the device
4. Re-run the app

See [this StackOverflow answer](https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update). This worked for me.

**Comment by smallsim** [comment]
It did not help. The issue is still here.

**Comment by AshleyScirra** [comment]
I followed those steps and verified they did indeed work.
