### ISSUE TITLE
Function fails to pick family object in the function's top event

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#3627]
## Problem description

I pass a UID between functions, and if I try to pick a family in the top block of the final function, it fails to pick the family. If I pick within a sub-event of the final function, it picks the object fine. Also, if I pass the UID directly to the final function, with no intermediate function, it picks the object fine.

Note that the object I'm trying to pick is in two families - one of the families is picked in the first function, and the other is picked in the final function. If I just pick the Sprite directly in the first function, I am able to pick the family properly in the final function, so I'm guessing the fact that I'm trying to pick the same object twice in a row by picking both the families it's in might be part of the problem. But I can't see any logical reason (end user-wise) that this shouldn't work.

## Attach a .c3p

[FunctionPickingBug.zip](https://github.com/Scirra/Construct-3-bugs/files/4141842/FunctionPickingBug.zip)

## Steps to reproduce

Since there are a couple points of failure here and they seem to be related, I'll just step through some of the permutations.

1. In the attached project, launch Layout1 and click the sprites.
2. Note that only the first sprite you click ever triggers the function to spawn the particles.
3. In the Mouse click event, comment out the Test function call and un-comment the Spawn function call.
4. Launch and click the sprites in Layout1 again.
5. Note that the sprites all spawn the particles as expected.
6. In the Mouse click event, comment out the Spawn function call and un-comment the Test function call to restore the project to its initial state.
7. In the "Spawn" function, comment out the Spawner pick condition in the top event, and un-comment the Spawner pick condition in the second event block.
8. Launch and click the sprites in Layout1 again.
9. Note that the sprites all spawn the particles as expected.

## Expected result

Picking in a function's top event should never fail if a valid UID was passed to the function, regardless of whether it was passed from another function or not, and regardless of whether the object is already picked in another function as a different family or not.

## More details

**Affected browsers/platforms:** 

**First affected release:** 
I tested as far back as 171.3 and got the same issues, but I have a feeling this is at least as old as the new Functions feature.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.130
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
C3 release: r184 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 80 gb
Storage usage (approx): 277 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can reproduce step 2 in r184, but it works correctly in the latest development build. I suspect it may be the same as #3617 which we already fixed for the next beta. Please review this again once that release is out and verify if it's working correctly.

**Comment by AshleyScirra** [comment]
r185 is out, could you verify if the issue is resolved there?

**Comment by Scoremonger** [comment]
Yes, it looks like my function is picking properly in 185. Thanks!

**Comment by AshleyScirra** [comment]
Thanks for confirming.
