### ISSUE TITLE
(!) IOS IAP plugin broken - Xcode build failed with IAP plugin.

### ISSUE THREAD

**Issue by smallsim** [Scirra/Construct-3-bugs#3633]
## Problem description

Cant't build app in Xcode with IAP-Plugin in later versions of C3.
Build failed with error in file **InAppPurchase.m**

Error message line1: **_Use of undeclared identifier 'SKProductDiscountTypeIntroductory_**
Error message line2: **_Use of undeclared identifier 'SKProductDiscountTypeSubscription_**

## Attach a .c3p

[test.zip](https://github.com/Scirra/Construct-3-bugs/files/4166255/test.zip)

## Steps to reproduce

1. Create any project in C3
2. Adding IAP Plugin
3. Build Xcode-Project via C3-Build-Service
4. Open compiled project in Xcode
5. Build project (Archive)
6. Build failed

## Observed result

Build failed. Can't build any app with IAP plugin.

## Expected result

Build should be ok.

## More details

It seems like Apple's bug. But the word "subsciption" in error message it is interesting, because C3 unfortunely do not support ios subscriptions.

**Affected browsers/platforms:** 

Xcode IOS App

**First affected release:** 

I tried C3-r148 = it works, build successful.
I tried C3-r182.2 (latest stable) = build failed.
I tried C3-r185 (latest beta) = build failed.

## System details

<details><summary>View details</summary>

c3 runtime (c2/c3 modes tried)
c3-build-service
xcode v.10.1

</details>

**Comment by AshleyScirra** [comment]
Generally you need all your software to be up-to-date to successfully build iOS apps. If you update everything to the latest version, including Xcode, does it work?

**Comment by smallsim** [comment]
Ok, I have xcode 10.1 and can't update it to upper version, beacause I need to update my macOS to macOS 10.15.4 Catalina... But I can't update my macOS because Apple sais I have old MacBookPro.

**Summary:** I can't use Construct3 Runtime, until I buy a new MacBookPro ?

So, Team, it's over? Any possibility to repair this iap for older versions of xcode?
I am so sad

**Comment by AshleyScirra** [comment]
I'm afraid these are all Apple's software and services and they decide what the rules are. Usually they require you have both recent hardware and the latest software.

I don't think there's any action we can take on our side about this, so closing.
