### ISSUE TITLE
IOS: restart game over time (frequency of 20-30 minutes) + Touch issue

### ISSUE THREAD

**Issue by tuzke** [Scirra/Construct-3-bugs#3634]
## Problem description

Issue 1.Restart game over time (frequency of 20-30 minutes): The game lagged over time leading to a restart - Android and PC debug don't have this problem. From beta version r183 onwards, this error occurs

Issue 2.When holding touch, the game is greened, displaying a coppy dialog box.

## Attach a .c3p

It is a big project of mine. cannot be public
>Try it on every project

## Steps to reproduce

Issue 1.Restart game over time (frequency of 20-30 minutes): The game lagged over time leading to a restart - Android and PC debug don't have this problem. From beta version r183 onwards, this error occurs

Issue 2.When holding touch, the game is greened, displaying a coppy dialog box.

## Observed result

Issue 1: Restart the game
Issue 2: Displaying a coppy dialog box, It annoys the player

## Expected result

Fix 2 issues above

## More details

**Affected browsers/platforms:** 
IOS

**First affected release:** 

Worked in R181.2 but broke in r183

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help you unless you follow the bug report guidelines. They are there because they're essential for us to be able to do anything, and provide important information.
