### ISSUE TITLE
Copy & Pasting a string adds an additional character of text

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#3636]
## Problem description

In various editor places, when you copy and paste text it will add a blank " " space to it after pasting.

I use desktop darktheme editor.

## illustration of issue, step by step

I highlight and copy the first part of this text:
![image](https://user-images.githubusercontent.com/5744908/74003745-c9babf00-49c7-11ea-96ed-33fadc3e9291.png)

I go to a different place (in this case another sprite):
![image](https://user-images.githubusercontent.com/5744908/74003795-f8389a00-49c7-11ea-84cd-4e0014f10205.png)

I then paste the text I coppied earlier into this text box:
![image](https://user-images.githubusercontent.com/5744908/74003928-62e9d580-49c8-11ea-92ac-ef0834bf814d.png)

## Observations

- As you may notice there was a space added in the text that was no present in "sprite_one", as the result "sprite_ two". 

- Zoom in to show there is a space there!
![image](https://user-images.githubusercontent.com/5744908/74004207-397d7980-49c9-11ea-8216-d3595cae2025.png)

- This happens in numerous places, in the string variables too
![image](https://user-images.githubusercontent.com/5744908/74004054-cbd14d80-49c8-11ea-95ad-a27e08049a52.png)

- It's very apparent in the name box because it gives an error
![image](https://user-images.githubusercontent.com/5744908/74004145-076c1780-49c9-11ea-900e-ebe2b48bedee.png)

## Attach a .c3p

[copy_ paste.zip](https://github.com/Scirra/Construct-3-bugs/files/4169186/copy_.paste.zip)

## Steps to reproduce

1. copy
2. paste

## Observed result

Space added

## Expected result

No space added

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.43.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.43.1 (like Chrome/79.0.3945.79)
C3 release: r185 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 68 gb
Storage usage (approx): 1.2 gb (1.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Another NW.js bug. Filed here, will follow up there: https://github.com/nwjs/nw.js/issues/7363
