### ISSUE TITLE
Exporting iOS Xcode Project

### ISSUE THREAD

**Issue by KENYONBcom** [Scirra/Construct-3-bugs#3638]
## Problem description

Exporting a C3 poject as iOS Xode project fails and returns an error if the Mobile Advert plugin is added.

## Attach a .c3p
Here is a stock demo with the Mobile Advert plugin added.
https://www.dropbox.com/s/b0zqfli7hfeo03b/export-ios-bug.c3p?dl=0

## Steps to reproduce

Any project with the Mobile Advert plugin fails.

## Observed result

it fails with the following error:

Error: Discovered platform "ios@5.1.1" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-ios@5.1.1
Adding ios project...
Creating Cordova project for the iOS platform:
Path: ~~/ios
Package: com.mycompany.myapp
Name: Pop Lab
iOS project created with cordova-ios@5.1.1
Plugin 'construct-mobile-advert' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Plugin 'construct-plugin-file' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-wkwebview-engine' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-vibration' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-statusbar' found in config.xml... Migrating it to package.json
Discovered saved plugin "construct-mobile-advert". Adding it to the project
Installing "construct-mobile-advert" for ios
Installing "cordova-plugin-add-swift-support" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Discovered saved plugin "construct-plugin-file". Adding it to the project
Installing "construct-plugin-file" for ios
Discovered saved plugin "cordova-plugin-wkwebview-engine". Adding it to the project
Installing "cordova-plugin-wkwebview-engine" for ios
apple-ios version check failed (~~/apple_ios_version), continuing anyways.
Discovered saved plugin "cordova-plugin-vibration". Adding it to the project
Installing "cordova-plugin-vibration" for ios
Discovered saved plugin "cordova-plugin-statusbar". Adding it to the project
Installing "cordova-plugin-statusbar" for ios
Running manual pod update
Pod update failed
~~/sh: 1: pod: not found

CordovaError: Promise rejected with non-error: undefined
at ~~/cordova:29:15
at processTicksAndRejections (~~/task_queues.js:94:5)

## Expected result

it should build without error like it used to.

## More details

**First affected release:** 

it's failing from version 182 to 185

**Comment by AshleyScirra** [comment]
We did some security updates on the build server on Friday and it looks like it accidentally changed the configuration. I just reinstalled something that appears to have gone missing and it seems to work now. Can you confirm?

**Comment by KENYONBcom** [comment]
It works now. thanks.

**Comment by KENYONBcom** [comment]
here's something else I haven't encountered. the project fails to build. the error is found in the ConstructAd.swift file:
import CommonCrypto
No such module 'CommonCrypto'

what does this mean and how can I fix it?

**Comment by AshleyScirra** [comment]
Thanks for confirming the build service is working again. I did an iOS Xcode export yesterday and it successfully built in Xcode. I'm not sure what that means, I guess it must be something to do with the configuration of Xcode. I don't think it's related to the original build service issue, so closing.
