### ISSUE TITLE
MoveTo resets angle to the angle from previous movement

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#3639]
## Problem description

MoveTo remembers the angle from previous movement. And when you start a new movement, it immediately sets that previous angle, even if it has since changed.

## Attach a .c3p

https://www.dropbox.com/s/h6zb3kbcisjxapo/MoveTo_bug.c3p?dl=0

## Steps to reproduce

1. Click anywhere.
2. When NPC arrives, it will rotate 80 degrees clockwise.
3. Click a new spot, you will see that before moving there, it will immediately reset the angle to previous angle value.

## Observed result

Angle is reset to previous value.

## Expected result

This should not happen in "Direct" mode.

## More details

**Affected browsers/platforms:** all

**First affected release:** I believe this never worked correctly.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.40.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.40.1 (like Chrome/76.0.3809.100)
C3 release: r182.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 8388608 tb
Storage usage (approx): 215 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
This is basically by design. The behavior has 'Set angle' enabled, which means "override the object angle with the behavior's angle of motion". Therefore setting the object angle disconnects the two until it's overridden again. The solution is to either turn off 'Set angle' and set the object angle manually, or rotate the object by changing the angle of motion instead of the object angle.

I just tried the latter and setting the angle of motion does not alter the object angle while the behavior is stopped. I fixed that for the next release so it works as expected.
