### ISSUE TITLE
Application shutdown issue when browser console or running project window is closed

### ISSUE THREAD

**Issue by esradogan** [Scirra/Construct-3-bugs#3641]
## Problem description

When I execute the project and the project start, if I press F12 to observe console logged messages and then if I close the working app window or browser console window the application is completely shut ting down to itself

## Attach a .c3p

[yilan.zip](https://github.com/Scirra/Construct-3-bugs/files/4181056/yilan.zip)

## Steps to reproduce

1. Project executes and starts
2. Press the F12 key
3. The working application window is closed
4. and application is observed as the last situation

## Observed result

Construct 3 application is shutting down to itself and it creates a difficult situation for me

## Expected result

Construct 3 application should not shutting down to itself

## More details

**Affected browsers/platforms:** Chrome 

**First affected release:** I don't remember clear but a few months ago.

**Comment by AshleyScirra** [comment]
I followed the steps and it works fine here. Typically if the whole browser closes, that indicates a browser crash rather than a problem with Construct, so it would be out of our hands. You could try a different browser.

Please provide your system information as per the bug report guidelines - it's essential information and it's very difficult to help without it.

**Comment by esradogan** [comment]
No, not the whole browser close, when I close running app window, app and browser console window are shutting down and the problem is also happening at Opera browser

## System details

Platform information
Browser: NW.js
Browser version: 0.39.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.39.0 (like Chrome/75.0.3770.80)
C3 release: r186 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 19 gb
Storage usage (approx): 239 mb (1.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 1030 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
It looks like you're using an old version of the desktop app from last June. Please download the latest version here: https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-nw-js-desktop-app-131317

If that doesn't help, I can only assume it's a problem specific to your system only, since it works fine for me and we've not heard of anyone else having the same problem so far.

**Comment by AshleyScirra** [comment]
We can't reproduce this and important details are missing, so closing.
