### ISSUE TITLE
iOS Touch Problem

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#3642]
## Problem description

When you export an App with touch input with X Code to iOS following problem appears: 
Its like the whole app is seen as a text box, if you tap and hold, everything gets market blue, if you release the dialogue box "Copy/Look Up" appears. 

I reported this issue already here #3565, but I make now its own Bugreport to be sure you have seen it. It is possibly related to this keyboard fix.
I have seen it mentioned also in #3634

## Attach a .c3p

[iOS_touch_text_Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4182394/iOS_touch_text_Bug.zip)

## Steps to reproduce

1.export project to iOS, minified script etc all 3 options enabled.
2.export from X Code to your iOS Device
3.run the app- tap, tap and hold, release.

## Observed result

whole screen gets blue, Copy/Look up Dialogue appears

## Expected result

not marked blue, no Dialogue Box

## More details

Bugreport made with r186,
Xcode Version 11.3.1 (11C504)
tested on iPad and iPhone SE

**Affected browsers/platforms:** 

**First affected release:** 
r185
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.87
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
C3 release: r186 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 126 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks like the entire canvas is selectable. This is mysterious since we already attempt to block selections using several approaches. It seems the fix to #3565 caused this issue, which is worse than the original problem, so we have no choice but to revert the fix which will reintroduce the original problem with hardware keyboards. I did file an issue with Apple about that though: https://bugs.webkit.org/show_bug.cgi?id=206887
The only feasible solution to get hardware keyboards to work properly will be for Apple to fix that issue. However having dealt with them in the past, I wouldn't hold your breath...
