### ISSUE TITLE
Whitelist GooglePlus plugin request.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#3643]
## Whitelist Request

Could you whitelist `chadori-mobile-googleplus@8.2.2`, thanks!

**Comment by ChadoriRebornXD** [comment]
Hi. I've updated it to `chadori-mobile-googleplus@8.4.0`, thanks again.

**Comment by Chadori** [comment]
Another update `chadori-mobile-googleplus@8.4.1`, sorry about that. Thanks.

**Comment by AshleyScirra** [comment]
It looks like the plugin uses hooks to run an additional `npm install` command on install, which brings in two additional dependencies: `xcode` and `plist`. Normally we avoid hooks since they involve arbitrary code execution on the build server, and between these two dependencies it appears the plugin could make arbitrary changes to the Xcode project, which makes it difficult to predict what kind of code the build server will be running and whether or not this could be remotely or maliciously controlled. Would you be able to modify the plugin to work without the hook or these dependencies?

**Comment by Chadori** [comment]
Thank you for informing me @AshleyScirra . 
The thing is, it's still dependent on the `cordova-plugin-googleplus`, it's still just a fork. I just added a very very slight difference that could allow it to work with the GooglePlay plugin. I barely looked into the files yet.

I think Nepeo made a judgement call to still whitelist it. I hope you can still do the same for this.
I will surely remove the excess code in the future, when I get the time and chance.

Sorry for the inconvenience.

**Comment by Chadori** [comment]
Hi @AshleyScirra , it seems I can remove it, it doesn't seem to be hardcoded. In the meantime, would you whitelist it, I will remove the non-needed files on the next update.

Thanks.

**Comment by AshleyScirra** [comment]
If you make changes to the plugin it will get a new version and I'll need to review it again. Please let me know which version is the new one to check when it is published.

**Comment by Chadori** [comment]
Alright, should be able to make a new version soon.

**Comment by GeometriXza** [comment]
Hi Ashley, please reconsider implementing the necessary whitelist for this issue. At present it's not possible for me to use the official Google Play plugin with Chador's MobileGooglePlus (which I need for PlayFab integration).

**Comment by AndyNormore** [comment]
Hey I need this too

**Comment by Chadori** [comment]
Hi @AshleyScirra . The dependencies for iOS are required, I'm afraid. 
And about the Browser hooks, it is necessary to be able to get the server credentials.

Sorry for only finding out about it now. 
I hope you can still whitelist it, since it is only similar to the `cordova-plugin-googleplus`.

Save version: `chadori-mobile-googleplus@8.4.1`

Thanks!

**Comment by AshleyScirra** [comment]
`chadori-mobile-googleplus@8.4.1` is now whitelisted on the build server and change is live.

**Comment by Chadori** [comment]
Thank you.
