### ISSUE TITLE
Whitelist plugin request

### ISSUE THREAD

**Issue by tuzke** [Scirra/Construct-3-bugs#3645]
Could you whitelist:    

cordova-plugin-firebase-analytics@latest_version

cordova-plugin-facebook4@latest_version

cordova-plugin-inapppurchase-fixed@latest_version

onesignal-cordova-plugin@latest_version

cordova-plugin-wkwebview-engine@latest_version

cordova-plugin-vibration@latest_version

cordova-plugin-statusbar@latest_version

Thanks! 😀

**Comment by AshleyScirra** [comment]
Please specify specific versions, or we may end up whitelisting a different version to the latest available now.

**Comment by tuzke** [comment]
cordova-plugin-firebase-analytics@4.0.1

cordova-plugin-facebook4@6.3.0

cordova-plugin-inapppurchase-fixed@1.1.2

onesignal-cordova-plugin@2.8.3

cordova-plugin-wkwebview-engine@1.2.1

cordova-plugin-vibration@3.1.1

cordova-plugin-statusbar@2.4.3

Thanks! 😀

**Comment by tuzke** [comment]
> Please specify specific versions, or we may end up whitelisting a different version to the latest available now.



> Please specify specific versions, or we may end up whitelisting a different version to the latest available now.

cordova-plugin-firebase-analytics@4.0.1

cordova-plugin-facebook4@6.3.0

cordova-plugin-inapppurchase-fixed@1.1.2

onesignal-cordova-plugin@2.8.3

cordova-plugin-wkwebview-engine@1.2.1

cordova-plugin-vibration@3.1.1

cordova-plugin-statusbar@2.4.3

Thanks! 😀

**Comment by tuzke** [comment]
@shortercode Can you check it out for me soon? I need it for the next build. Thanks!

**Comment by AshleyScirra** [comment]
Added the following plugins (including subdependencies) to the whitelist and updated the [documented list](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/build-server-cordova-plugin-149266. Changes are now live on the build server. Note `cordova-plugin-inapppurchase-fixed@1.1.2` was already whitelisted.

- cordova-plugin-firebase-analytics@4.0.1
- cordova-support-android-plugin@1.0.1
- cordova-support-google-services@1.3.2
- cordova-plugin-facebook4@6.3.0
- onesignal-cordova-plugin@2.8.3
- cordova-plugin-wkwebview-engine@1.2.1
- cordova-plugin-vibration@3.1.1
- cordova-plugin-statusbar@2.4.3
