### ISSUE TITLE
Change font size for textfield 

### ISSUE THREAD

**Issue by friesenpole** [Scirra/Construct-3-bugs#3646]
## Problem description

i created a text field on the layout and wanted to change the font size. the application crashed.

## Steps to reproduce

1. textfield created in layout
2. change font size for this textfield
3. application crash

## Observed result
bug report (see below SystemDetails)

## More details

**Affected browsers/platforms:** 
see below SystemDetails

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information

Type: unhandled exception
File: https://editor.construct.net/r182-4/3rdparty/codemirror/codemirror.js, line 1, col 103728
Message: Error: Permission denied to access property "parentNode"
Stack: hl@https://editor.construct.net/r182-4/3rdparty/codemirror/codemirror.js:1:103728 ld.prototype.pollSelection@https://editor.construct.net/r182-4/3rdparty/codemirror/codemirror.js:1:145988 e@https://editor.construct.net/r182-4/3rdparty/codemirror/codemirror.js:1:145170
Construct 3 version: r182.4
URL: https://editor.construct.net/
Date: Fri Feb 14 2020 07:34:00 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 30.2 s
Platform information

Browser: Firefox
Browser version: 68.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
C3 release: r182.4 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro P2000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I'm afraid there's nothing we can do about reports like this. Without a project and steps to reproduce, we have no way to investigate. In rare circumstances we can speculatively fix reports based on a crash report alone, but as is usually the case we are unable to do that here. Please see the bug report guidelines.
