### ISSUE TITLE
First preview with worker mode is super slow

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3647]
## Problem description
When user first time opens the editor and clicks preview, user needs to wait around 20-30sec, to see project.
This only happens first time. All following previews with worker mode are fast enough.

Does not happen everytime, is pretty chaotic. Not sure what triggers this and i have gotten used to it, if preview window does not load instantly, i just restart. But it should not bug with super long load times.

## Steps to reproduce

1.Close all chrome windows.
2.Navigate and open c3 editor
3.Navigate to start menu, under templates open project race track.
4.Click preview

## Observed result
User has to wait 20-30sec with black screen before preview can be  seen

## Expected result
Faster preview

## More details

**Affected browsers/platforms:** 

**First affected release:** 
Always, as long worker has been with C3.
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.106
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36
C3 release: r186 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 975 mb (0.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I tried several times with a new incognito Chrome window (which loads from scratch), loading r186, loading the race track template, and previewing. It was fast every single time.

As ever without a way to reproduce the issue it will be difficult to do anything at all about it. If you could find a way to grab a dev tools profile of a slow load, that might give us at least something to go on, but it may be as simple as your Internet connection having a blip and going slow for a bit, which is not an issue with Construct.

**Comment by SnipG** [comment]
Indeed. It could come from Internet connection, editor fail to go offline mode and results some bug in loading(very often in past I have seen that offline mode pop-up never shows up), or some other chaotic problem. 
While i thought i could reproduce this more often, when i got annoyed by the slow load, i could couldn't because of the chaotic nature of it. 

So this issue can be closed. Will reopen if ever manage to get more info.

**Comment by AshleyScirra** [comment]
OK, closing as no way to reproduce or investigate so far.

**Comment by SnipG** [comment]
Video of it happening:
[2020-02-28 17-58-31.zip](https://github.com/Scirra/Construct-3-bugs/files/4267904/2020-02-28.17-58-31.zip)
And that profile:
[Profile-20200228T175934.zip](https://github.com/Scirra/Construct-3-bugs/files/4267907/Profile-20200228T175934.zip)

100% happen if i open it atm, and needs to be resized for preview to be seen. Does not matter if i resize and it open up with different size.

**Comment by SnipG** [comment]
Nvm, this comes from event. When i paste 9patch with effects on canvas, in start of layout.
