### ISSUE TITLE
The export manager from version 184 onwards is faulty

### ISSUE THREAD

**Issue by tuzke** [Scirra/Construct-3-bugs#3648]
## Problem description

The export manager from version 184 onwards is faulty and I cannot manually build the ios game. I have to use editor version 183 to build it. 

## Steps to reproduce

1. Open a project
2. Export to IOS cordova project
3. Open export manager and Add archive IOS cordova zip file
4. Click Build Application

## Observed result

Nothing happens

## Expected result

The build process is done

## More details

worked in r183 but broke in >r184

## System details

<details><summary>View details</summary>

Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
    at Object.ǃEmc (main.js:114)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release. You don't need to do this though - you can just build it when exporting to iOS, which is still working in the latest releases.
