### ISSUE TITLE
Frequent use of tilemap rotation, resulting in abnormal

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#3649]
## Problem description

I'm drawing tilemap for hours.Rotate a tile back and forth like a jigsaw puzzle. edit tilemap and  preview layout.

Normally, when I press the Rotate button, the button responds immediately, highlights, and then darkens immediately.

Because the editor does not give me the preview state after rotation, only show a angle.  I always cannot get the desired direction. When using rotation is very continuous, the rotation button may become unresponsive and cannot be rotated again.

like it:[imgur](https://imgur.com/ZzrHmzv)
It is not necessarily that both are invalid at the same time, sometimes only one, sometimes two.

When I stop editing, select other objects and select back again. The icon returns to normal, but clicking on the rotation again is still unresponsive.

Of course, these problems returned to normal after refreshing the browser and restarting the project.

## More details

**Affected browsers/platforms:**  Chrome,macOS
**First affected release:** r185 - r187

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.106
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36
C3 release: r187 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 67 gb
Storage usage (approx): 241 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics 655
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I've assigned this to @DiegoScirra for a brief review but please note normally we are unable to help unless you follow all the bug report guidelines.

**Comment by DiegoScirra** [comment]
@XHXIAIEIN I was able to reproduce the issue by spamming the keyboard shortcuts to rotate a title. Spamming mouse clicks doesn't seem to be a problem though.

**Comment by DiegoScirra** [comment]
This is fixed in the next beta.
