### ISSUE TITLE
Tilemap Collision Polygons Show Abnormal When erased tile

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#3650]
## Problem description

When Show Collision Polygons, If the tiles are erased, the collision polygons of other connected tiles may display abnormally. 

If continue to erased, collision polygon of the entire tilemap will disappear until unselect tilemap and then reselect.

[imgur](https://imgur.com/SZzkKmW)

**First affected release:** r187

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise we cannot investigate your report.
