### ISSUE TITLE
"Set cursor from sprite" has a huge delay with the worker

### ISSUE THREAD

**Issue by ArtRow** [Scirra/Construct-3-bugs#3652]
## Problem description

"Set cursor from sprite" works immediately without worker, but has a huge delay with it.

## Attach a .c3p
[CursorHugeDelayWithWorker.zip](https://github.com/Scirra/Construct-3-bugs/files/4216173/CursorHugeDelayWithWorker.zip)

## Steps to reproduce

1. Open attached file
2. Run a preview
3. Toggle "Use worker" and run preview again

## Observed result

When worker is on – cursor changes sprite after a second
When worker is off – cursor changes sprite immediately

## Expected result

Shouldn't cursor changes its sprite immediately in both options?

## More details
I wrote about similar issue where described that option "Set cursor from sprite" works without any delay with Runtime 2, but has some delays with Runtime 3. Delays were less than 0.1 second and it can be ok. With worker that delays are now about 1 second or more.

**Affected browsers/platforms:** 
Uses standart construct preview (no browsers)

**First affected release:** 
Found it accidentally. Construct r182.4 Stable

## System details

Windows 7

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
This looks like a bug in Chrome. I filed it here: https://bugs.chromium.org/p/chromium/issues/detail?id=1053477

Will follow up at that issue, so closing this one.
