### ISSUE TITLE
Dark Theme: missing "close" icon on tabs

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#3659]
When I mouse over around here on a tab:

![image](https://user-images.githubusercontent.com/5744908/74900540-42704100-53f4-11ea-8f7c-2dd376a7907b.png)

Then click, it closes, indicating that there is an invisible "X" close button there, but it's not visible, at least in this official dark theme. 

I like to close tabs because I sometimes have a lot open, so closing them quickly is handy.

However, if I select the sheet, the "X" is only visible then

![image](https://user-images.githubusercontent.com/5744908/74900768-e78b1980-53f4-11ea-8f49-210054cb02cb.png)

How google shows the X on chrome tabs for reference:

![image](https://user-images.githubusercontent.com/5744908/74900891-42247580-53f5-11ea-99e5-c652c2bdbc17.png)

Using desktop build

**Comment by alastajj** [comment]
closed because I couldn't replicate for some reason

**Comment by SnipG** [comment]
![Design](https://user-images.githubusercontent.com/28864889/74939376-6cc3fd80-53f8-11ea-9bff-36f56a01002f.jpg)

Not sure how you could not replicate this. This is dark theme by design change, i bet. Close X only appears when you select it.

**Comment by alastajj** [comment]
Yeah it's an issue, but maybe they'd classify it as feature request.

The bug and replication issue is to do with it sometimes just clicking the right edge of a non-selected tab will close it, when what's visually expected is that it will select it instead of closing. But in another sense, we do expect tabs to close when clicking in that region regardless of whether it's selected or not, so either way we lose, unless they just add the close symbol to the tabs like normal software. 

I'll open back up just in case and let others close it  if they desire.

**Comment by alastajj** [comment]
It may be possible to duplicate the bug by having a full span of tabs open, but I don't have the time to make a proper report so I'll close this.
