### ISSUE TITLE
Sprite Jumps Back to Its Original Position Before Rotating

### ISSUE THREAD

**Issue by ziggyhere** [Scirra/Construct-3-bugs#3660]
## Problem description

After updating my C3 to the latest version, I encountered an issue with my game. A sprite is supposed to move towards the centre of the screen from left and right side (outside screen), stop, then start rotating. However, in this case (after the update), they move towards the centre but then they "jumped" back to their previous position and start rotating there instead. It worked just fine before the update. Also, I checked whether it is my error but all my other previous files (which worked well before the update) showed the same problem using the new updated version. So I suspect the newer version is causing this mess. Please check the c3p file and suggest any solution to this problem.

## Attach a .c3p
[Error.zip](https://github.com/Scirra/Construct-3-bugs/files/4230231/Error.zip)

## Steps to reproduce
Was working perfectly before the update. 

## Observed result
Object move towards the centre as intended (performed Custom movement), but when then **suddenly disappear and reappear back at its original position** before rotation starts. Happened after the update.

## Expected result
Before update: Object move towards centre as intended (performed Custom movement), stopped
as intended (velocity set to zero) and started rotating. Works perfectly fine and as intended before the update. Checked with other files using similar action to see if it is only affecting current file but all exhibit Observed Result as stated above.

## More details
Happened on Chrome yesterday after I logged in and C3 pop up asking me to update to latest version. So I suspect issue may be caused by the latest version.

## System details
No crash report.

PASTE HERE

**Comment by AshleyScirra** [comment]
I backported your project to r171.3: [project-r171-3.zip](https://github.com/Scirra/Construct-3-bugs/files/4230672/project-r171-3.zip)

It works identically in r171.3, r182.4 and r187. Therefore there has not been any change in Construct affecting your project. It is probably just a mistake in your events.

**Comment by ziggyhere** [comment]
There is certainly nothing wrong with my event.

**Comment by AshleyScirra** [comment]
It looks like your events are missing a 'Set target' action in the Orbit behavior. As it stands when the Orbit behavior is enabled it will still try to orbit the original location. Changing the target position to Self.X and Self.Y when you enable it updates the position to orbit around. This looks like an oversight in your events and doesn't appear to be related to any change in Construct.

**Comment by ziggyhere** [comment]
Thanks Ashley but the strange thing is that I had it running perfectly
before I update C3 to the latest version. And I didn't make any changes on
the event. It just worked fine in the previous C3 versions. The issue only
happened after I use the latest version of C3. Does it mean in the older C3
version there is no need to set the Self and yet it worked fine?

Also, I have been getting this pop up message "Failed to start preview. Try
reloading Construct 3 before trying again" whenever I tried to preview
offline (even though C3 tells me I can use it offline). I am having these
funny issues with the latest version that didn't have in the other previous
versions and I have been using C3 for more than a year already. It seems to
me that this latest version of C3 r182.4 must havr been jinxed.

**Comment by AshleyScirra** [comment]
As I mentioned, the project runs identically in r171.3, which is proof that there has been no change in Construct affecting this project.

People commonly make changes to their projects (either accidentally or intentionally) at the same time as a Construct update, and then mis-attribute the change to the Construct update. I would guess that is what happened here.
