### ISSUE TITLE
When adding a new Event the Dialogue title reads 'AddCondition'

### ISSUE THREAD

**Issue by simonpaulkeating** [Scirra/Construct-3-bugs#3661]
## Problem description

When adding an event via right click or shortcut key the dialogue reads New Condition. This can be confusing as its not a condition- its an event. 

## Steps to reproduce

1.Hit e in the event sheet. 

## Observed result

New event dialogue reads- Add Condition.

## Expected result

New event dialogue should read- Add Event.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It is actually correct. Creating an event involves adding the first condition to the event block. When that dialog is showing, you are choosing the condition.

**Comment by simonpaulkeating** [comment]
Ok sorry, I get it. Apologies.




Get Outlook for Android







On Thu, Feb 20, 2020 at 9:36 AM -0300, "Ashley (Scirra)" <notifications@github.com> wrote:












Closed #3661.
