### ISSUE TITLE
Issue with Physics Engine Implementation

### ISSUE THREAD

**Issue by XanthorXIII** [Scirra/Construct-3-bugs#3662]
## Problem description

When Physics gets enabled for an object I see weird rounding errors on the Objects Position

## Attach a .c3p

[TestPhysics.zip](https://github.com/Scirra/Construct-3-bugs/files/4234560/TestPhysics.zip)

## Steps to reproduce

1. Play Test Game in Debug Mode
2. Check the Object Position before pressing the G Key to Enable Physics. Notice it's nice even numbers in X: 320 and Y: 180

3. Hit the G key to now notice that the values are no longer Integers but appear to be doubles and have odd rounding errors.

## Observed result
For example, X is no longer 320, but now 320.0000047683716 and Y is no longer 180 but 179.99999523162842 which doesn't make much sense. 

## Expected result

If you need to convert/cast the values to a double or some other value type, I would expect it to keep it at 0's so it doesn't cause object placement issues
For example, X should be 320.00000000 and Y would be 180.0000000

## More details
I tested both with enabling and disabling Phyiscs on the objects. Even if you disable it, it will keep those values. 

**Affected browsers/platforms:** Tested both on Chrome on PC and Safari on iPad. Does the same thing on both

**First affected release:** All I know is that this is affected in r182.4 Stable. 

## System details
Platform information
Browser: Chrome
Browser version: 79.0.3945.130
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
C3 release: r182.4 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 154 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
With the Physics behavior enabled, object positions are set from a simulated physics world in the Box2D engine. This probably has rounding errors. All fractional calculations on computers are only done with a limited amount of precision. I don't see that this has any meaningful impact on anything anyway.
