### ISSUE TITLE
issue related to construct.net Forum section

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3663]
I don't know where to post issues related to website

When i make new post and reply to any question 
when i click on "insert image" icon then nothing happen. No image uploader pop appear.
This issue happens most of the time. it appears back after 2-3 hours later.

I tried it on Chrome and Microsoft Edge Browser with same result.

**Comment by AshleyScirra** [comment]
There's a separate tracker for the website. It looks like it was already filed here: https://github.com/Scirra/Construct.net-website-bugs/issues/135
