### ISSUE TITLE
Cannot edit SpriteFont text via timeline properties 

### ISSUE THREAD

**Issue by pinellos** [Scirra/Construct-3-bugs#3666]
## Problem description
Cannot edit SpriteFont text via timeline properties, even the UI seems to be bugged because continue to add "properties" fields in the top left of the editor...

## Attach a .c3p

[err_repo.zip](https://github.com/Scirra/Construct-3-bugs/files/4239773/err_repo.zip)

## Steps to reproduce

1.add a spritefont object to a timeline
2.add the "text" property to the spritefont instance in the timeline bar
3.Create a keyframe, try to edit the text field in the text property of the spritefont plugin

## Observed result

impossible to write something, there not text-input fields - everytime the keyframe relative to the property is selected, an empty field appears in the up-left:

![Immagine](https://user-images.githubusercontent.com/40840723/75097473-6924a800-55ab-11ea-9cc7-ee487e0c2b35.png)

## Expected result
can modify the text of the spritefont in the timeline editing the appropriate field 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta release.
