### ISSUE TITLE
NWjs Window Actions Don't Work At All Now

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#3667]
## Problem description

I reported earlier that resizing the window was inaccurate... now nothing related to the window works. In some cases it even cases code placed with it to freak out hardcore.

## Attach a .c3p

[nwjswindoweditdoesnotwork.zip](https://github.com/Scirra/Construct-3-bugs/files/4239862/nwjswindoweditdoesnotwork.zip)

## Steps to reproduce

1. Press A key to move the sprite back 20px to see that the project is doing something.
2. Press S to see it not do anything despite it should.

## Observed result

None of the NWjs actions do anything. In my actual game I'm doing, when it tries to change the window size, the game flips out bad cycling through all possible window sizes in a single frame or two until it loops back to the fullscreen option which is part of the browser plugin, unrelated to NWjs.

## Expected result

NWjs window actions used to work.

## More details

**Affected browsers/platforms:** Chrome, NWjs C3, Projects exported to NWjs Windows 32 and 64 bit.

**First affected release:** r187

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.100
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36
C3 release: r187 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 89 gb
Storage usage (approx): 1.1 gb (1.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Ah, it's due to the new web worker mode. You can work around it by turning off 'Use worker'. It should be fixed in the next beta too.

**Comment by corlenbelspar** [comment]
Thanks. My game also has a ton of different modes that alter things like the graphics style itself for the whole game or the getting rid of the lives system entirely, so I can easily see how something can work fine in one mode, but easily be missed not working in another.
