### ISSUE TITLE
Orbit Actions doesn't show Orbit icon

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#3669]
## Problem description

Some orbit behavior actions doesn't show you orbit icon on action.

## Attach a .c3p
[Orbit.zip](https://github.com/Scirra/Construct-3-bugs/files/4257156/Orbit.zip)

## Observed result

![image](https://user-images.githubusercontent.com/54614906/75368867-73a8af80-58d3-11ea-8b15-27a792f3a4ac.png)

## Expected result

Show orbit icon on actions

## More details

**Affected browsers/platforms:** 

**First affected release:** Tested with r188

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta cycle. (We're close to a stable release now and this would be too late a change to send to translators.)
