### ISSUE TITLE
Audio crackling issues

### ISSUE THREAD

**Issue by phantomfuxor** [Scirra/Construct-3-bugs#3670]
I've added a file (audio) to my music folder (at 32 kbps) and  exported my project.

**Observed result** 
Running my project has massive performance issues and sound is working but making crackling noises. 

**Expected result** 
No performance issues and working sound without crackling. 

**More details**
I've made the simplest solution where it does crackle but a lot less since it's not in a game.
It's really a performance killer and wierd thing. Not much detail i have about what is going on, but i can tell you what i've tried:

- webm, ogg, wav, different kbps
- the file plays fine in winamp for example.
- worker / no worker mode
- using stable version r182.4
- tried on nokia 6.1, Android 10 (Q), fully updated. 
- works fine in browser on PC (quad 3.6 GHz, 8 gb ram, gtx 980) 

Did a cordova build, did a service build, both produce the same problem. 

**Attachments** 
https://drive.google.com/file/d/1MT8veReWyBjqVa4mawSrgIiIyueR_UPU/view?usp=sharing  this is the link to c3p 

https://drive.google.com/file/d/1BOc-veAqi-78oVwupSdp0BSXXBhUReyn/view?usp=sharing this is the link to a debug APK generated from the c3p file. Try installing it and listen to the crackling noises.

**Comment by AshleyScirra** [comment]
This is far too large a project to investigate for a bug report, and it also uses third-party addons. Please see the bug report guidelines, we can't help unless you follow them.

Note that in general if it works on one device but not on another, that generally means Construct is working fine and there is a problem with that device.

**Comment by SnipG** [comment]
Most likely same issue as:
Which i made: https://crbug.com/1041182
And way older one: https://crbug.com/1002093

Both is blocked, because there is no minimal repo.

Both issues seems to come from HRTF mode.

Change it to Equal power and it could be better. Try it out and report back.

**Comment by phantomfuxor** [comment]
No help, i've tried the  same project with Equal power and it's the same. 

Starts crackling when after it's run. The funny thing is that in my game project the game works way slower with music, when i remove the audio it works fine (as in no dropped frames). 


I've tried on a several other phones and they have no problems (P30 pro, Asus Nexus 7 ,  etc..). 
Though! The same issue appears on Sony Xperia L7, same cracking noises. 

It could be a webView issue, but i've noticed that Asus has android 6.1, p30pro has android 10, and Xperia has android 7.0

**Comment by phantomfuxor** [comment]
I'll try a different file.

**Comment by phantomfuxor** [comment]
ok i think i found the source of the problem. The Webm format is broken or the player doesn't play that correctly.  I'd prefer if you can still play ogg files. WebM is so broken. I've tried now an MP3 file it plays better than webm. Tried other files and they work fine. webm file is completely broken and doesn't work, no matter the settings i've tried.

**Comment by AshleyScirra** [comment]
There is no technical reason for that to be the case. It will be storing the same audio, but just in a different format. All other aspects of playback are identical.
