### ISSUE TITLE
Create Object by Name appears in all search results

### ISSUE THREAD

**Issue by RorySoh** [Scirra/Construct-3-bugs#3671]
## Problem description

all events of type: Create object by name (System) appear in all search results, unrelated to it.

https://i.imgur.com/fjIdPkn.png

## Steps to reproduce

1. Add any create object by name into a project
2. Right click > find all references to any other object

## Observed result

It floods your search results

## Expected result

Nothing should show up

## More details

**Affected browsers/platforms:** 

**First affected release:** It's been awhile now, but it's still like this in r188

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's by design. The editor doesn't know whether those expressions will end up creating the object you are searching for or not, so it shows them as ambiguous results (with the question mark icon).
