### ISSUE TITLE
JS Linter doesn't recognize decomposed arguments renaming

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3673]
## Problem description

When using the {oldName:newName} format, the linter still thinks that the name it should be looking for is oldName.

## Attach a .c3p
n/a

## Steps to reproduce

write this in a JS script:

```JS
eval(`globalThis.myImport = (arg) => {return import(arg)}; console.log("done")`);
Promise.all([
	globalThis.myImport('https://unpkg.com/preact?module'),
	globalThis.myImport('https://unpkg.com/htm?module')
]).then(([{ h, Component, render }, {default:htm}]) => {
	// Initialize htm with Preact
	const html = htm.bind(h);

	const app = html`<div>Hello World!</div>`
	render(app, getApp());
})
```

## Observed result

![image](https://user-images.githubusercontent.com/11213825/75440098-6800cb80-595b-11ea-93f5-82f28f933753.png)

## Expected result

The linter shouldn't highlight this

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Minimal repro because one wasn't provided: 
[linter-destructure.zip](https://github.com/Scirra/Construct-3-bugs/files/4281505/linter-destructure.zip)

I'll only be testing with that.

**Comment by AshleyScirra** [comment]
OK, should be fixed in the next build. (I'm not surprised there was a mistake, personally I find these destructuring declarations really confusing!)
