### ISSUE TITLE
Timeline's absolute result mode unexpected behavior at runtime

### ISSUE THREAD

**Issue by Animmaniac** [Scirra/Construct-3-bugs#3674]
## Problem description

At runtime, "Absolute" Result Mode for timeline only acts as absolute at the start of an animation and not every frame as one would expect.

## Attach a .c3p

[timeline-result-absolute-bug-B01.zip](https://github.com/Scirra/Construct-3-bugs/files/4264307/timeline-result-absolute-bug-B01.zip)

## Steps to reproduce

1. Just preview the project

## Observed result

The Sprite stays to the right (x=1000) after it's X position is set through events once.

## Expected result

The Sprite should stay to the left (x=100) always, except for one frame every time it's X position is set through events (when it flashes white).

## More details

**Affected browsers/platforms:** NW.js, Windows 10

**First affected release:** only tested on r188 Beta

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.43.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.43.1 (like Chrome/79.0.3945.79)
C3 release: r188 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 24 gb
Storage usage (approx): 226 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 850M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
