### ISSUE TITLE
JS linter throwing error for 'return statement outside of function' even though return is in a function 

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#3675]
## Problem description

JS linter throwing error for 'return statement outside of function', this is happening inside inline java script event block which are wrapped in a function during the games execution. same as await error were being thrown a few releases ago. 

discussion in forum : https://www.construct.net/en/forum/construct-3/scripting-51/return-outside-function-150315

## Attach a .c3p

https://drive.google.com/open?id=1oMcItclis2DDBUSSUfRrJ0A-75dCyCn5

* notice return statement is commeneted out that throws linting error

https://drive.google.com/open?id=1503NNgUMJqwp6nk9W9Be32yH_vgfwrNL

* notice that the return statement ends up in a function during game execution and in this state is valid javascript

## Steps to reproduce

1. create inline javascript block
2. add if condition
3. inside if condition return
4. this throws error

## Observed result

get error message from linter

## Expected result

this not throw an error, and when the game is execute and the return state is hit, no other javascript in the event block is executed

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.122
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
C3 release: r188 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 317 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Attaching repro project since one wasn't provided: [return-lint.zip](https://github.com/Scirra/Construct-3-bugs/files/4281429/return-lint.zip)

**Comment by AshleyScirra** [comment]
I feel a bit uncertain about this, since technically the use of a function is an implementation detail, and from the editor itself there's no sign that it's actually running a function since you only see the body statements. But I guess we do mention in the documentation you can use `await` because it's inside an async function, and it's a useful feature for control flow, so removed the warning for the next release.
