### ISSUE TITLE
Animation editor - input boxes bug

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#3676]
## Problem description

Input boxes where you can enter different numeric values in Animation Editor are buggy. 

## Attach a .c3p

N/A, see explanation and gif below.

## Steps to reproduce

Problem 1
When editing image point position, shortly click a small arrow Up or Down to increase/decrease the X/Y number. If you don't move mouse cursor, the number will continue changing as if you continue holding mouse button.
This happens with other tools that have input boxes.

Problem 2
If after that you press Ctrl-Z to undo this change, it won't work, because cursor is still inside the input box. Even if you click anywhere on the image to manually set image point position, blinking cursor still remains inside the input box, so again you can't press Ctrl-Z and undo these changes.
You need to switch to another tool or press Tab several times to get the cursor out of the input box.

This happens with other tools as well. For example, select Brush, enter a number in Size input box and start drawing. You will not be able to undo with Ctrl-Z, because the Size input box still has the focus.

See this GIF - note, that I only clicked once to increase X from 32 to 33, but it quickly went up to 55:

[![anim-editor-bug.gif](https://i.postimg.cc/Zqkp5Bmf/anim-editor-bug.gif)](https://postimg.cc/MnDvsGvR)

## Observed result

Clicking input boxes sometimes result in values changing uncontrollably.
Also they retain focus, not allowing to undo.

## More details

**Affected browsers/platforms:**
Chrome and Desktop Build - both problems.
Firefox - only problem # 2  

**First affected release:** 

This started happening in the last few releases, not sure which one.
Tested r176, it works fine.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.122
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
C3 release: r188 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 674 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
@DiegoScirra - I think you already found and fixed this?

**Comment by DiegoScirra** [comment]
The first problem has already been fixed and will be landing in the next stable release.

The second issue is not a bug, the Animations Editor has been working like that for a long time now. As long as a any text input has focus undo/redo is not allowed because it is assumed that if the text box has focus, it is being edited, so in that case the browser's built in undo behavior should take precedence when you hit Ctrl-Z or Ctrl-Y.

Having said that, I have made a change so that in the case of the image points tool and the collision polygon tool, focus is removed from the toolbar when you make a change by explicitly using the tool. That won't land on the next stable because it would be a little bit reckless to just include it.

**Comment by dop2000** [comment]
Hi Diego, I just checked r176 and the input box loses focus there as soon as I start drawing with a brush/pencil tool, or click to select a new position for image point, or move collision polygon point. So it's possible to undo there. 
In r182 and later versions the input box retains focus, and the only way to get the cursor out of it is to press Tab key or switch to another tool..

**Comment by DiegoScirra** [comment]
@dop2000 Thanks, I was able to figure out when both issues started happening, They showed up in r179 and r183 respectively. Were fairly simple fixes, so they will show up inn the next stable.
