### ISSUE TITLE
Letterbox scale issue

### ISSUE THREAD

**Issue by ArtRow** [Scirra/Construct-3-bugs#3679]
## Problem description

Game area ends below bottom line of viewport. All custom cursors become standard. If there is hidden cursor it becomes visible too. 
To be correctly, cursors don't become standard. There is out of the game area. It begins just rigth after bottom edge of viewport. 
So, physically, we are not in the game area more. Top, left and right spaces are still the game area.

![image](https://user-images.githubusercontent.com/46167226/75612074-6557cf00-5b31-11ea-8005-b482b15fc84f.png)

## Attach a .c3p

[Letterbox scale issue.zip](https://github.com/Scirra/Construct-3-bugs/files/4270626/Letterbox.scale.issue.zip)

## Steps to reproduce

1. Open and run attached file
2. Run it with letterbox scale (or letterbox integer scale) and resize window to create black bars
3. Move cursor to the bottom black area

## Observed result

We are outside of the game area

## Expected result

Should game area end below bottom edge? Especially for fullscreen windows games where cursor is used by players. Is there a possibility to add bottom margin with the same height as top one?

_I understand that black outside area isn't an area for playing and game triggers, but appearing of cursor is a bit annoying._

## More details

**Affected browsers/platforms:** 

**First affected release:** r182.4 stable

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r182.4 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 44 gb
Storage usage (approx): 658 mb (1.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
