### ISSUE TITLE
C3 crashes every time I load project file

### ISSUE THREAD

**Issue by bdleggett** [Scirra/Construct-3-bugs#368]
## Problem description

*I saved my newgrounds jam project last night (it was working just fine at this point, no crashing) I went to continue working on the game this morning but everytime I open my project I instantly get a construct 3 error dialog and have to restart, I can't get into the project at all. I have included the error dialogs readout but I can't attach a new project file and I don't really want to share my entire project anyway*

## Attach a .c3p

*Can't attach a new file as the problem seems to be confined to my project however I can't check events etc as I can't even open it*

## Steps to reproduce

1. Open my project file
2.
3.

## Observed result

*I get a construct 3 error dialog as soon as the project loads*

## Expected result

*The project to open*

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: The source image cannot be decoded.
Construct 3 version: r31
URL: https://editor.construct.net/index.html
Date: Fri May 26 2017 12:42:38 GMT+0100 (GMT Summer Time)
Uptime: 13.4 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Please provide the project that reproduces this or there is nothing we can do.

**Comment by bdleggett** [comment]
Sorry about that, the guidelines suggested posting the entire project file wouldn't be overly helpful, I wasn't trying to ignore them. I have updated the post to include a link to the project.
