### ISSUE TITLE
Crash when importing C2 project to C3 Type: unhandled rejection

### ISSUE THREAD

**Issue by CSL2adam** [Scirra/Construct-3-bugs#3681]
## Problem description

 When I try to import my Construct 2 project over it says: "Failed to open project. Check it is a valid Construct 2 single-file (.capx) project." However my project is already saved as a single file type. Construct 3 then crashes. I will copy in the Error report below. My project only uses one third party plugin, the Spriter plugin.

## Attach a .c3p

 I will send a link to scirra support with my single project file.

## Steps to reproduce

1.Try to open C2 project in C3
2.
3.

## Observed result

 Project fails to open in Construct 3 and crashes.

## Expected result

 Project opens in Construct 3

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r182.4

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected a child with tag name 'animation-folder' @ Error: expected a child with tag name 'animation-folder' at ǃS.ǃh$.Element.ǃhG (https://editor.construct.net/r182-4/main.js:2:216332) at Function.ǃQOQ (https://editor.construct.net/r182-4/projectResources.js:1:149332)
Stack: Error: expected a child with tag name 'animation-folder' at ǃS.ǃh$.Element.ǃhG (https://editor.construct.net/r182-4/main.js:2:216332) at Function.ǃQOQ (https://editor.construct.net/r182-4/projectResources.js:1:149332)
Construct 3 version: r182.4
URL: https://editor.construct.net/
Date: Sun Mar 01 2020 17:31:40 GMT+0000 (Greenwich Mean Time)
Uptime: 17.1 s

Platform information
Browser: Chrome
Browser version: 80.0.3987.122
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
C3 release: r182.4 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
There is nothing we can do about this without the project file. If you sent this to support, we will take it up there instead.
