### ISSUE TITLE
Additional touch events seem to be skipped in very specific circumstances

### ISSUE THREAD

**Issue by natebluewizard** [Scirra/Construct-3-bugs#3682]
## Problem description
While testing my game on a mobile browser (Safari on iOS 13), I noticed that sometimes my on-screen buttons failed to trigger. I set up a clean project with only a single event: print the Touch.TouchCount to a text fields. In testing this clean project on multiple iOS phones, I am noticing that if i hold my left thumb down on the left side of the screen and press multiple times on the right side of the screen over and over again, I can sometimes find a 'dead spot' where tapping my right thumb does not trigger a second touch event. Letting go of my left thumb, the right thumb will start triggering touches again, put my left thumb back down, and now only the left will trigger a touch, right thumb does not trigger touches despite multiple taps.

## Attach a .c3p

https://bluewizard.com/nate/touchtest/TouchTest.c3p

## Steps to reproduce

1. On an iOS device, go to www.bluewizard.com/nate/touchtest (its basically a built / uploaded version of the c3p file provided above. 
2. Hold your left thumb on the red square.
3. Tap your right thumb on the green square

## Observed result

As you keep your left thumb static in the red square and tap with your right thumb in the green square, you'll notice that you will be able to find spots in the green square where tapping is no longer registered. While in that spot, lift your left thumb, and you'll notice touches with your right thumb will start registering again, then put your left thumb down and youll see they stop again.

## Expected result

Multiple Touches should register regardless of position on the screen / position of other touches.
 
## More details

I was able to replicate this in other spots on the screen but it usually seems to be when my thumbs are on roughly the same horizontal line.. If i move one of my thumbs higher / lower than the test squares, i cant seem to reproduce it as easily. Unfortunately the easiest place for me to reproduce is in the position where my actual on-screen buttons are.

**Affected browsers/platforms:** 

Tested on 2 separate iOS devices in Safari. Replicated in chrome on the same devices. Unable to test touch events on laptop.

**First affected release:**

Unable to test previous releases. First noticed on 182.4

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.100
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36
C3 release: r182.4 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 919 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro Vega 20 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
Construct has no control over touch events. They come straight from the browser or OS. If a touch event doesn't fire, it means the browser/OS didn't pass it along.

iOS has system-wide touch gestures that are handled by the OS rather than the app. So it's not true that all touches will be registered in all circumstances. I think this is partially activating a system gesture which prevents the app seeing the touches. There is nothing that can be done about this - iOS has long had deadzones and system-wide gestures for various purposes, and apps have to be designed around that.

**Comment by natebluewizard** [comment]
@AshleyScirra Would you expect the same behaviour on all applications / games built in other engines as well?

**Comment by AshleyScirra** [comment]
Yes.
