### ISSUE TITLE
Construct 3 Manual Tilemap collision errata

### ISSUE THREAD

**Issue by renolc** [Scirra/Construct-3-bugs#3685]
## Problem description

The [Construct 3 Manual](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/tilemap) claims:

>Note however the collision polygon cannot be entirely removed from a tile: only an erased tile counts as not colliding at all.

But if you double click a tile in the tilemap panel, you have the option to disable collisions for that specific tile.

![image](https://user-images.githubusercontent.com/4680221/75728856-1045c580-5cb7-11ea-9ebb-adbd6459d3f3.png)

Upon testing, this allows a tile to be filled while not registering as part of the solid object. This seems to contradict the manual which states this is impossible and only empty tiles will not collide, so it recommends using 2 tilemaps -- one for drawing and one for collision. However, since you can disable collisions per tile on a single tilemap, this no longer seems necessary.

## Attach a .c3p

[tilemap_test.zip](https://github.com/Scirra/Construct-3-bugs/files/4278586/tilemap_test.zip)

## Steps to reproduce

1. attached .c3p has a basic setup with a solid tilemap and movable box
2. observe the tilemap has 2 tiles, 1 green with collisions disabled, 1 black with them enabled
3. observe tilemap is filled and moveable box is within tilemap
4. when previewed you can move the box around the tilemap and it will collide with only the tiles that still have their collisions enabled

## Observed result

Moveable objects can move over tilemaps that are marked solid, so long as the tiles they are on have collisions disabled.

## Expected result

According to the manual, it should be impossible to disable collisions on individual tiles.

## More details

Recommend updating the manual to indicate collisions may indeed be disabled on a per tile basis, and the recommendation to use 2 layers of tilemaps should probably be removed as well.

**Affected browsers/platforms:** all of them?

**First affected release:** unsure when the option to disable collisions was added, but it was present in the last 2 stable versions at least (r189 and... whatever was before that)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.123
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Chrome OS
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 12607.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.123 Safari/537.36
C3 release: r189 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 64 gb
Storage usage (approx): 376 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Amber Lake (Kabylake) GT2
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, we only recently added this feature and as you rightly spotted the manual was not updated to cover that. I've now modified the manual page to include disabling individual tile collisions.
