### ISSUE TITLE
Offline mode limits scripts on paid account

### ISSUE THREAD

**Issue by renolc** [Scirra/Construct-3-bugs#3686]
## Problem description

Using my paid account, offline mode says
>Scripting feature limit reached [...] Purchase a plan to continue using it

![Screenshot 2020-03-03 at 12 49 11 PM](https://user-images.githubusercontent.com/4680221/75804339-cb20a280-5d4d-11ea-9809-1d8843e8ccee.png)
![Screenshot 2020-03-03 at 12 49 28 PM](https://user-images.githubusercontent.com/4680221/75804349-cd82fc80-5d4d-11ea-9498-4342ef35cabf.png)

## Attach a .c3p

[offline.zip](https://github.com/Scirra/Construct-3-bugs/files/4282813/offline.zip)

## Steps to reproduce

1. go offline and start construct with a paid account logged in
2. attempt to add another script action to the `On start of layout` event
3. receive error

## Observed result

Construct limits the amount of script objects that can be added to paid accounts while offline.

## Expected result

Offline should work the same as online. The account details page seems to confirm I am on a paid account, so it should not limit my account as if I weren't.

## More details

Going online and opening the same project works as expected. It seems to only happen when construct is started in offline mode.

**Affected browsers/platforms:** Tested in Chrome 79 on ChromeOS (editor installed as a PWA)

**First affected release:** confirmed in latest stable, r189

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.123
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Chrome OS
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 12607.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.123 Safari/537.36
C3 release: r189 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 64 gb
Storage usage (approx): 374 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Amber Lake (Kabylake) GT2
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report, should be working offline in the next beta. Sorry for the inconvenience.
