### ISSUE TITLE
Crash on Save

### ISSUE THREAD

**Issue by blueFireGames** [Scirra/Construct-3-bugs#3687]
## Problem description

Crashes when pressing the save button in the menu.  I also noticed the save project as single file option is missing from the drop down Menu/Project/Save As sub-menu.

## Attach a .c3p

Attached.

## Steps to reproduce

1.  Open attached project.
2.  Click the save icon on the dropdown menu
3.  Observe result

## Observed result

Crash report and needing to restart C3.

## Expected result

Save the project

## More details

**Affected browsers/platforms:** 

r189

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: web filesystem not supported
Stack: Error at Function.ǃy.ǃyOm (https://editor.construct.net/r189/main.js:2:127018) at e (https://editor.construct.net/r189/main.js:2:85095) at window.assert (https://editor.construct.net/r189/main.js:2:85425) at window.ǃ$fA.ǃyY$ (https://editor.construct.net/r189/main.js:210:106118) at window.ǃ$fA.ǃfRz (https://editor.construct.net/r189/main.js:210:110325) at https://editor.construct.net/r189/components/misc/mainMenu/mainMenu.js:1:1411
Construct 3 version: r189
URL: https://editor.construct.net/
Date: Tue Mar 03 2020 18:41:30 GMT-0500 (Eastern Standard Time)
Uptime: 161.6 s

Platform information
Browser: Edge
Browser version: 80.0.361.62
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36 Edg/80.0.361.62
C3 release: r189 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

[test.zip](https://github.com/Scirra/Construct-3-bugs/files/4284235/test.zip)

**Comment by AshleyScirra** [comment]
From a few educated guesses it looks like you changed the default save location to "Save As" in Settings while the experimental local file/folder saves were enabled, and then later that was disabled (possibly because it's disabled by default in stable releases since it's still experimental), and now the default save option of "Save As" doesn't work because it requires the experimental feature.

I've fixed this for the next release so it falls back to cloud save, but you can also work around it by changing the default save location in settings, or enable experimental features to get local file/folder saves back in the stable release.
