### ISSUE TITLE
Can't open project

### ISSUE THREAD

**Issue by RichardAstrom** [Scirra/Construct-3-bugs#3688]
## Problem description

I can't open a project anymore that I previously have been able to open. It seems to have something to do with a specific third-party plugin (Game Distribution) that's referred to in the project.

Here's the latest version of the plugin: [gamedistribution-sdk-1.1.2.c3addon.zip](https://github.com/Scirra/Construct-3-bugs/files/4287245/gamedistribution-sdk-1.1.2.c3addon.zip)

I also tried an older version of the plugin but it threw the same error.

## Attach a .c3p

Unfortunately I can't share the project file here as it's the complete game. We have signed a deal with a publisher and we need to make some adjustments to the game but it's not possible right now. I could share it by mail if you would be willing to have a look at it?

## Steps to reproduce

1. I try to open the project file in C3.
2. I then get the following error "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."
3. Here's the console log error:

![c3_error](https://user-images.githubusercontent.com/3534495/75879720-26b96180-5e1c-11ea-9235-ad209df2ed49.png)

## Observed result

I get the following error "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

## Expected result

It should open the project.

## More details

**Affected browsers/platforms:** 

Chrome

**First affected release:** 

The project was saved with r154 but it doesn't open with that version either anymore.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
C3 release: r189 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 12 gb
Storage usage (approx): 220 mb (1.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid we can't offer support for third-party addons. You will need to report this to the addon developer and get them to fix it.

It looks like you saved the project with a condition `rewarded-ad-preloaded`, and then the addon developer deleted the condition and released an update. Addon developers should never delete ACEs, we provide a deprecation mechanism specifically to avoid this. Now you have a version of the addon with the condition missing and Construct can't find the condition when opening the project. You'll need to contact the addon developer to sort out which version of the addon they broke and get them to re-add the condition marked as deprecated instead. Alternatively you can try editing the JSON of your project directly to remove any uses of the condition with that ID (although be sure to make a backup first).

**Comment by RichardAstrom** [comment]
Yes, I understand. I did contact them and got them to send the first version of the plugin, but it didn't work either. But I will ask them to send every version so I get the exact one that I used in the project. I also tried to remove the condition in the JSON but I don't think I did it correctly, I wasn't sure how to properly edit it. Perhaps I'll give it another shot as well.

Thanks!
