### ISSUE TITLE
C3 crashes every time I open my project

### ISSUE THREAD

**Issue by bdleggett** [Scirra/Construct-3-bugs#369]
## Problem description

*Everytime I open my Newgrounds jam project I get an error dialog, I can't get into the project at all, it seemed to be fine last and then I saved and closed it and since then I can't open it.*

## Attach a .c3p

*
[Threeknights (1).zip](https://github.com/Scirra/Construct-3-bugs/files/1031779/Threeknights.1.zip)
*

## Steps to reproduce

1. Open the project file
2.
3.

## Observed result

*The second the project finishes loading I get an error dialog*

## Expected result

*The project to open without issue*

## Affected browsers

* Chrome: YES
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: The source image cannot be decoded.
Construct 3 version: r31
URL: https://editor.construct.net/index.html
Date: Fri May 26 2017 13:12:03 GMT+0100 (GMT Summer Time)
Uptime: 554.7 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
The project is corrupt. There are three image files (enbullet_bigring-animation 1-000.png and two other frames) which are empty files. You can recover the project by renaming .c3p to .zip and updating those image files to have content. However we can't fix the problem unless you can find a way to reproduce the problem in the first place. Please let us know if you can find the original problem.
