### ISSUE TITLE
Offline use not work in browser.

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#3691]
## Problem description

Offline use not work in browser.

## Attach a .c3p

https://drive.google.com/file/d/1DLwIUZzdlROITUKketfa1I4AjvutHinc/view?usp=sharing

## Steps to reproduce

1. Export project to HTML
2. Publish on web
3. Run the game and wait the cache.
4. switch to offline
5. refrest the page or open in new tab with offline mode
6. cannot load the game

## Observed result

after refresh or open in new tab in offline mode the game cannot run.

## Expected result

**console log:**  The FetchEvent for "https://test.epicsoft.hu/test/1/" resulted in a network error response: the promise was rejected.

**in code:**  in "self.addEventListener("fetch", (a) => {});" part "c = HandleFetch(a, b);" cannot resolve the promise. 

**Affected browsers/platforms:** HTML

**First affected release:** r189.2

## System details

Platform information
Browser: Chrome
Browser version: 80.0.3987.122
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 130 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 640M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
Works fine for me with an export of Space Blaster on our server: https://www.scirra.com/labs/offlinetest/index.html

I'd guess there's something different about your server configuration.

**Comment by henrikszucs** [comment]
Thank you ;)
The problem was in my server.
Gzip caused the issue.
