### ISSUE TITLE
Vibrate does not stop when game window closed

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#3693]
## Problem description

Joypad rumble  does not stop when game window closed

## Attach a .c3p

[RumbleTest (1).zip](https://github.com/Scirra/Construct-3-bugs/files/4300156/RumbleTest.1.zip)

## Steps to reproduce

run c3p press a

ensure rumble is rumbling

close preview window  

## Observed result

rumble no stop

## Expected result

rumble stop

i understand this can be solved with a reset rumble action on close window / suspended event etc
but I think perhaps is an overstight that rumble not automatically stopped by the engine if there is no dedicated event.

Chrome
Windows 10

**Comment by AshleyScirra** [comment]
Fixed for next beta.
