### ISSUE TITLE
Cannot set vibrate to more than 5 seconds

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#3694]
## Problem description

Cannot set vibrate more than 5 seconds

## Attach a .c3p

[RumbleTest (1).zip](https://github.com/Scirra/Construct-3-bugs/files/4300165/RumbleTest.1.zip)

## Steps to reproduce

move top slider to set  re-trigger rumble time.

## Observed result

 will not rumble if set to >5000 ms

## Expected result

should be allowed to set more than 5 seconds

I understand that you maybe do not want to allow indefinite rumble 
and I understand that can be re triggered, however there is a slight jar on re-trigger sometime.
perhaps allow maximum 30 seconds or 1 minute ??  ,maybe there is an earthquake in game.

or best  IMO ....  dont place limit 

Chrome Version 80.0.3987.132
Win10

**Comment by AshleyScirra** [comment]
Construct does not impose any limit. Any limit must come from the browser, OS or hardware, which is beyond our control. It's also possible the limit exists to avoid damaging the hardware, so you may want to comply with the limit anyway.
