### ISSUE TITLE
MoveTo behavior affects Bullet behavior

### ISSUE THREAD

**Issue by Vladimir7527** [Scirra/Construct-3-bugs#3695]
## Problem description
When object with MoveTo behavior is moving to indicated position, bullets fly fast. When object with MoveTo behavior is not moving, bullets fly slow.
In my game, when the camera did not move, the bullets stopped. And when the camera began to move, then the bullets began to fly again. But I could not reproduce it. I just noticed that the two behaviors influence each other.

## Attach a .c3p
[https://yadi.sk/d/Lj1hvi4KIVOtDQ](url)

## Steps to reproduce
1. press right arrow
2. press E key - bullet will fly fast
3. press left arrow
4. press E key - bullet will fly slow

## Observed result
bullet behavior somehow depends on moveTo behavior. It changes the speed of bullets.

## Expected result
Bullet speed should not change.

## More details

**Affected browsers/platforms:**
Chrome, Windows

**First affected release:**
r189.2 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 81 gb
Storage usage (approx): 5.3 gb (6.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
At first this looked bizarre, but it looks like the problem stems from every tick you use "Move to", even if the camera is already on the player; this causes it to rapidly alternate between starting and stopping movement. When it stops it removes itself from an internal queue of behaviors to tick, and accidentally ends up ticking the bullet behavior twice, causing those bullets to move twice as fast. It's an unusual bug and ought to be rare but it's a good find so thanks, and it should be fixed in the next beta.
