### ISSUE TITLE
Guided tour When unfocus, will lose responsiveness

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#3696]
## Problem description

In the steps guide to create a new object. 'Click anywhere in the Layout View to place the Tiled Background.' if the window unfocus and the Sprite cannot be properly placed, it will lose its response. That is, the image editor does not appears, So the steps will not continue. Even if the object is readded, the steps will not continue. just can only restart editor.

This problem is appears whenever there is create a new object.
1. Click anywhere in the Layout View to place the Tiled Background.
2. [b]Click[/b] somewhere on the background to place the Sprite there.
...

## Steps to reproduce

_1.  [b]Double-click[/b] to create a new object again._
_2.  objects are Sprites. [b]Double-click[/b] it to add._
**3.  The cursor becomes a cross key, do Not place the object to layout. Toggle the window process and open other browser tabs. Switch back.**

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in the next release.
