### ISSUE TITLE
Small problem of placement in the guided tour (in Spanish at least)

### ISSUE THREAD

**Issue by DavidCB14** [Scirra/Construct-3-bugs#3698]
## Problem description
(Only in Spanish translated version) 
In the step of the guided tour that you select the mouse shows you with a tooltip in the project tree. But this tooltip points to the player object instead of the mouse object

## Attach a .c3p
No .c3p projects involved

## Steps to reproduce
Put construct3 in Spanish and restart the application
Click on menu item Guided Tours -> Beginers Guide

You must arrive in the guided tour to the step where we choose the mouse object. Once the mouse is located in the scene, a tooltip appears that points in the project tree. But this tooltip points to the player object and not to the mouse object

## Observed result

Wrong tooltip destination point

## Expected result

The tooltip should point to the mouse object

**Affected browsers/platforms:** None

**First affected release:** r190beta

![mouse-tooltip](https://user-images.githubusercontent.com/11505355/76291872-4df5b000-62ae-11ea-8683-00480af1fada.png)

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.
