### ISSUE TITLE
Event Copy As Text Bugs

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#37]
## Problem description

Text copied does not indicate whether the copied events is an AND block or an OR block. It also does not indicate nor filter out disabled events.

## Steps to reproduce

1. Create a simple line of event.
2. Select it and right-click "Copy as text"
3. Paste the copied text on any text editor to see the copied text.

## Observed result

Text copied does not indicate whether the copied events is an AND block or an OR block. It also does not indicate nor filter out disabled events.

## Expected result

For an OR block to be indicated and AND block left no change as current default.
For the disabled events, C3 should perhaps filter and omit them in the copy process or just address them as disabled.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
I've fixed r18 to indicate OR block conditions when copying as text. It's hard to see a good text representation for disabled events, and I don't think it's helpful to omit them entirely. There's other state not included in the copied text like breakpoint or bookmark status, so I think disabled state will simply be left out.
