### ISSUE TITLE
If the [up arrow key] is still pushing after the jump end, [Event> Simulate control> Jump] does not work.

### ISSUE THREAD

**Issue by niceplugin** [Scirra/Construct-3-bugs#3702]
## Problem description

Added `sprite` to jump platform(player) when colliding with `sprite && platform`.

At this time, if the `up arrow` key is still pushing after the jump end, `Event> Simulate control> Jump` does not work.

If you don't press the up arrow key, it will work again.

See the attached project for details.

## Attach BUG.c3p

[BUG.c3p](https://drive.google.com/file/d/1t4LFBVJzwfeeTuHZM76PHx5uom8Mu0nd/view?usp=sharing)

## Steps to reproduce

1. When the project runs, press the up arrow. (Do not lift your finger from the up keys.)
2. When the jump is over, press the right arrow to move to the red box. (Still do not lift your finger from the up keys.)
3. Platform will drop and finally collision to red box.

## Observed result

Just dropped on the red box. Nothing happens.

## Expected result

The platform should jump by the event control.

## More details

If you add another action, like playing a sound, to the **Platform: On collision with Red_Box** event, you'll see this event worked.

Only `Simulate controls` do not work.

I tested it in your PWA Construct3 Editor.

My Chrome Version is 80.0.3987.132 (Official Build) (64-bit).

**Affected browsers/platforms:** 

**First affected release:**

**Comment by AshleyScirra** [comment]
This is not a bug. 'Simulate control Jump' has no effect if you are already holding the jump key - the key is already down. The player does not jump when falling on to the red box with the jump key still held down for the same reason they don't jump if you just press and hold the jump key: jumping again when the key is held down long-term is called 'bunnyhopping', and users asked us to disable this by default in the Platform behavior. If you want to force a jump ignoring the control scheme, use 'Set vector Y'.
