### ISSUE TITLE
Drawing canvas cannot paste object with 2 of the same effect

### ISSUE THREAD

**Issue by RorySoh** [Scirra/Construct-3-bugs#3704]
## Problem description

Drawing canvas cannot paste object with 2 of the same effect.
Effect being tested with is ReplaceSolidColor

## Attach a .c3p

[2replacesolidsequalsnowork.zip](https://github.com/Scirra/Construct-3-bugs/files/4322680/2replacesolidsequalsnowork.zip)

## Version
r189.2 stable

**Comment by AshleyScirra** [comment]
Please take care to fill out the bug report guidelines. It is difficult to figure out what I'm meant to do with the project you provided without additional information like the steps to reproduce. I can make some guesses, but then I might not identify or fix the issue you intend to report.

**Comment by RorySoh** [comment]
Hey I totally understand, it's just I found this while messing around and it doesn't really affect me personally, but I just thought I'd mention it, but I can't really be bothered to do a full write up since I don't plan to use it any time soon.

I'll just close it.
