### ISSUE TITLE
bullet behavior + Orbit behavior together disabled Bullet behavior

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3705]
## Problem description

I am not sure if it is a bug or it is how its made. by adding both behaviors Orbit and Bullet to Sprite it only rotates on orbit but doesn't move.

## Attach a .c3p
no need

## Steps to reproduce

1. Create New Project
2. Insert Sprite
3. Add orbit and Bullet behavior to it
4. Preview 

## Observed result

Only Orbit behavior works

## Expected result

both behavior should work.  Sprite should move and also should orbit at same time

## More details

I am not sure if it is a bug

**Affected browsers/platforms:** 
Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The behaviors will conflict. Should it orbit the fixed position or move in a straight line? There is no good answer.
