### ISSUE TITLE
Guides tours Removing UI States

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#3706]
## Problem description

When you click "Guides tours"  your UI positions, Dialog sizes etc.. all removed. Also I report this before, when you change theme it is removing everything.
Should we have "save UI state" feature?

## Steps to reproduce

1. Open guided tours.
2.
3.

## Observed result
UI state changed.

## Expected result
UI state not changed.

## More details

**Affected browsers/platforms:** 

**First affected release:** r190

**Comment by AshleyScirra** [comment]
This is by design. The tour might not work if you have customized the UI. For example if you have closed the Properties Bar, tour steps that involve editing properties won't work. Therefore it reverts your UI layout to the default before starting the tour.
