### ISSUE TITLE
File Chooser doesn't work on android exports.

### ISSUE THREAD

**Issue by bedfl2016** [Scirra/Construct-3-bugs#3709]
## Problem description

When you export a construct 3 project (containing the file chooser object) to an android APK. The file chooser doesn't seem to even open up on android.

## Attach a .c3p
https://www.dropbox.com/s/ajghqcbjy79b70z/FileChooserHack.c3p?dl=0
## Steps to reproduce

1. Export this project to an android APK
2. Open on an android device
3. Then click the file button.

## Observed result

When you click on the file button the file chooser doesn't show.

## Expected result

The file chooser should have opened up and let the user choose a file.

**Affected browsers/platforms:** 

Android

**Comment by AshleyScirra** [comment]
Did this ever work?

I suspect it never worked, since file choosing is probably like the 'invoke download' feature which is provided by the browser UI, and inside an app there is no browser UI.

**Comment by bedfl2016** [comment]
> Did this ever work?
> 
> I suspect it never worked, since file choosing is probably like the 'invoke download' feature which is provided by the browser UI, and inside an app there is no browser UI, therefore it is not supported.

Im confused,

How do I get the user to be able to select a file? - Does the file chooser not work at all on android?

Or is this genuinely a bug?

**Comment by AshleyScirra** [comment]
The question I am asking, and need to know the answer to, is: did this used to work, and it's now broken? Or has it always been like this as far as you can tell?

**Comment by bedfl2016** [comment]
> The question I am asking, and need to know the answer to, is: did this used to work, and it's now broken? Or has it always been like this as far as you can tell?

@AshleyScirra 

Oh sorry,

To answer you question,
I have only just started using the file chooser so Im not to sure whether its been working or not on android exports. I have seen some topics on the forum regarding the filechooser on exports:

https://www.construct.net/en/forum/construct-2/closed-bugs-22/file-chooser-not-working-108837
https://www.construct.net/en/forum/construct-2/how-do-i-18/file-chooser-97609
https://www.construct.net/en/forum/construct-2/how-do-i-18/open-sd-card-file-manager-97600

These seem to reference other things as well so I don't know if they are relevant.

**Comment by AshleyScirra** [comment]
Those threads are several years old and refer to a retired platform, so I don't think they are relevant any more. I will assume this is not a regression and never worked.

**Comment by bedfl2016** [comment]
> Those threads are several years old and refer to a retired platform, so I don't think they are relevant any more. I will assume this is not a regression and never worked.

@AshleyScirra 

Will you be able to add support for the file chooser on android exports?

**Comment by AshleyScirra** [comment]
It actually works for me on Android. You have to make sure you export not minified, though. You use this ancient deprecated feature of referring to elements by a global variable with their ID in a code snippet; if you export it minified the global variable name will be mangled to something else (e.g. `x.click()`) which will break it. Exporting unminified works fine in an Android app here.

Referring to elements by their ID like that is an ancient design mistake of the web from the 90s, and probably the only reason it hasn't been removed is because it would break too many websites. Always use `document.getElementById()` instead.

To avoid having to use scripting to activate the `click()` method, I added a 'Click' action to the File Chooser object in the next release so you don't need to resort to scripting for that.

**Comment by bedfl2016** [comment]
Hi @AshleyScirra as you have closed this does this mean this won't be added?

**Comment by bedfl2016** [comment]
> It actually works for me on Android. You have to make sure you export not minified, though. You use this ancient deprecated feature of referring to elements by a global variable with their ID in a code snippet; if you export it minified the global variable name will be mangled to something else (e.g. `x.click()`) which will break it. Exporting unminified works fine in an Android app here.
> 
> Referring to elements by their ID like that is an ancient design mistake of the web from the 90s, and probably the only reason it hasn't been removed is because it would break too many websites. Always use `document.getElementById()` instead. (That was added in IE 5.5 in the year 2000, and has been best practice for 20 years since then!)
> 
> To avoid having to use scripting to activate the `click()` method, I added a 'Click' action to the File Chooser object in the next release so you don't need to resort to scripting for that.

Thanks, man I really appreciate it!

Stay well!

**Comment by AshleyScirra** [comment]
Just to be clear, Construct 3 has always supported File Chooser on Android and it's always been working correctly. Your project didn't work due to an entirely different reason (incorrect use of scripting).

**Comment by bedfl2016** [comment]
Oh sorry about the confusion. I understand now!

Many Thanks,

Laurence
