### ISSUE TITLE
Set Color ignores Opacity on transparent Layer

### ISSUE THREAD

**Issue by jobel0092** [Scirra/Construct-3-bugs#3712]
I found a problem when using the Set Color ACTION.  When applied to an object on a Layer that is transparent, when you Set Color, it will not preserve the opacity.

let's say you have 2 layers: Layer0(background) and Layer1(transp).  Then if you place a sprite on Layer1 with the opacity set to 20%.  When you set color to that sprite it makes it 100% opaque (also tinted with your color).  In the debugger, the sprite still thinks it's 20% opaque.  Any attempts to change opacity after a 'set color' fail.

## Attach a .c3p
https://drive.google.com/file/d/1TRFBnodcpuPp2GnfKA483H5VQ_RFcc9o/view?usp=sharing

## Steps to reproduce

1.create a top layer (defaults to transparent)
2.create a sprite on that layer, set it's opacity to 20% (use paint-can to fill some solid color)
3.create an event that applies Set Color to that sprite

## Observed result

the Set Color tint works, but then the sprite looks fully opaque. even though the debugger says its still at 20%
## Expected result

I would expect the sprite to be tinted the Set Color values and preserve the opacity
## More details

Chrome
**Affected browsers/platforms:** 

r189.2
**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It looks like it is working correctly. If I open the project and press space, it changes the color of a sprite but preserves its opacity, since you can still see another object underneath it, as shown below. Did you attach the right project?
![issue3712](https://user-images.githubusercontent.com/768723/76755755-56515d80-677c-11ea-93f7-d590cf7ea9b2.png)

**Comment by AshleyScirra** [comment]
Can't reproduce and no response for a week, so closing.

**Comment by jobel0092** [comment]
sorry, not abandoned, I was stuck out of the country, I am finally home and back in front of a computer.  

If you look at the example before and after you see the change.  It still has *some* transparency, but it definitely does not retain the same level.  

I found a work around to just paint my sprites with the desired transparency, that way I don't have to rely on Construct doing it.  but the BUG is still very much there.  it's up to you if you want to fix it.

**Comment by AshleyScirra** [comment]
I don't see what the problem is though, it looks like it's working correctly.

**Comment by jobel0092** [comment]
@AshleyScirra 
I modified the Google Drive doc..

-I have 2 instances of a TiledBackground (which is just a white background image).
-on one of the instances, I manually set the color in the properties bar to: (139, 122, 205) and the other one I keep white.
-both have 25% opacity
-I created an event when you hit the SPACE BAR to Set Color of both instances to (139, 122, 205)
-but the result is that the one that was only white goes to the correct color but is definitely not at 25% opacity. Whereas the other one doesn't change at all (which is what I would expect).
I would expect both to look identical.

Maybe this is not the intended function of Set Color?  if not, then how would you use Events to get them to look that same purple color with 25% opacity?

**Comment by AshleyScirra** [comment]
Alright, this is a bit clearer. But why does the project change the color of the sprite as well? Is there some kind of problem with that as well or is it irrelevant? We ask to use the fewest events and objects possible because it makes it clearer what the problem is. Each unrelated thing makes me think, "is that related to the problem and do I need to investigate that?"

**Comment by jobel0092** [comment]
@AshleyScirra ah yes, I was thinking originally that the Sprite object wasn't effected by this issue and that it was only the TiledBackground, but I don't think that's the case.

In addition, I think I originally found that if objects were on the bottom (non transparent) layer this issue didn't happen at all.  Which could maybe be a clue as to why this is happening?

I will remove that sprite if it creates confusion.

**Comment by AshleyScirra** [comment]
I just realised it's a mistake in the project. rgbEx takes values in the 0-100 range, but you pass values in the 0-255 range. Use rgbEx255 for that. The color looks wrong because you're basically applying an overdrive tint effect (e.g. 205% blue).

**Comment by jobel0092** [comment]
okay but why isn't it "overdriven" in the editor when I applied 205 blue in the color properties bar?

the point remains that they are not the same.   

Is 'Color' in the properties bar supposed to be different than the Set Color Action?

**Comment by AshleyScirra** [comment]
The color property uses a 0-255 range. Yes, it's inconsistent... we kind of have to live with it since artists are used to a 0-255 range for color selection, but all GPU programming uses a 0-1 range (which Construct normalizes to a 0-100 range).
