### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#3714]
## Problem description

C3 randomly crashes after a while of use.

## Attach a .c3p

I don't know how to reproduce this.

## Steps to reproduce

1. ???
2. ???
3. ???

## Observed result

Random crashes.

## Expected result

No crashes.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r189.2

## System details

<details><summary>View details</summary>

Error report information Type: assertion failure Message: language context stack reached 100 items - is this right? Stack: Error at Function.ǃc.ǃcUm (https://editor.construct.net/r189-2/main.js:2:127010) at e (https://editor.construct.net/r189-2/main.js:2:85090) at window.assert (https://editor.construct.net/r189-2/main.js:2:85420) at Function.ǃk (https://editor.construct.net/r189-2/main.js:2:182595) at e.ǃmRA (https://editor.construct.net/r189-2/components/editors/eventSheetView/eventSheetView.js:1:101878) at e.ǃ$f (https://editor.construct.net/r189-2/components/editors/eventSheetView/eventSheetView.js:1:99784) at HTMLDivElement.ǃPg (https://editor.construct.net/r189-2/components/editors/eventSheetView/eventSheetView.js:1:51937) Construct 3 version: r189.2 URL: https://editor.construct.net/ Date: Sun Mar 15 2020 17:57:14 GMT-0500 (Central Daylight Time) Uptime: 118398.8 s
Platform information
Browser: Chrome
Browser version: 80.0.3987.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
C3 release: r189.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to do anything about reports like this. Please see the bug report guidelines.

**Comment by corlenbelspar** [comment]
I'm afraid it's impossible to follow the guidelines 110% with a randomly occurring crash, so I guess I'll just have to suck it up and deal with it.
