### ISSUE TITLE
broken project part 2

### ISSUE THREAD

**Issue by rilem** [Scirra/Construct-3-bugs#3715]
## Problem description

After working on the Mighty Goose project in r191 the project fails to open. (this has happened before in an earlier build, see issue https://github.com/Scirra/Construct-3-bugs/issues/3604)

## Attach a .c3p

I'd rather invite someone from scirra to the Mighty Goose repository. Especially since this happened before. Also sent Ashley an email describing the issue.

## Steps to reproduce

Really hard to put a finger on this. The previous issue was something with bundled addons, which are now turned off in my project.

## Observed result

Failed to open project. Console doesn't shed light on the situation.

## Expected result

Open project

## More details

Checking out a commit from before 191 allows me to open the project.

Happens in Chrome and in the Chrome PWA.

First affected release: 191

**Comment by AshleyScirra** [comment]
We took this up by email so closing this issue. For the record it looks identical to #3604, but that was already fixed, so it's not clear what could have happened here.
