### ISSUE TITLE
Construct 3 - Can't open project ("Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.")

### ISSUE THREAD

**Issue by alexpelliarmus** [Scirra/Construct-3-bugs#3717]
## Problem description

Suddenly can not open my project file, which I have saved on my google drive account. Have no idea what could have occured, except that before I saved it and closed the file the sound file "Super ballerina run - meny låten" had suddenly stopped working in-game, and so I tried restarting to see if it would fix itself, only to be unable of opening the file again.

## Attach a .c3p

https://drive.google.com/open?id=1aomnW0pruMEasbe-_MiI3wcD3OpOIi1p

## Steps to reproduce

1. Open the .c3p project file

## Observed result

Can not open the project file.  I get the error message: "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

## Expected result

I want to be able to open the project file without any error messages.

## More details

**Affected browsers/platforms:** Chrome/Safari, macOS

## System details

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 13.0.4
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_2
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_blend_minmax
EXT_sRGB
EXT_frag_depth
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBGL_compressed_texture_s3tc
WEBGL_depth_texture
WEBGL_draw_buffers
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by AshleyScirra** [comment]
It doesn't open in r189.2, but it does open fine in r190 onwards. I suggest just using those releases for the time being. It looks like this is a unicode normalization issue we already fixed - note our bug report guidelines request to only report issues that reproduce in the latest release to avoid reporting issues we've already fixed.
