### ISSUE TITLE
Touch+Drag&Drop behavior bug

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#3718]
## Problem description

Touch with Drag&Drop behavior work differently depending on the order objects were added to the project.

## Attach a .c3p

https://www.dropbox.com/s/rvmtkgjk02e68l5/Scroll_bug1.c3p?dl=0
https://www.dropbox.com/s/4wcoii3nkre73lh/Scroll_bug2.c3p?dl=0

## Steps to reproduce

1. Run each project
2. Try to scroll the panel up and down.

## Observed result

In the first project the panel will continue to scroll after touch end.
In the second project it won't, because Touch.AngleAt and Touch.SpeedAt expressions return 0 when "On drop" is triggered.

The only difference between the two projects is that in one project Touch was added first, in another Panel was added first.

## Expected result

Consistent results.

## More details

**Affected browsers/platforms:** Chrome/Firefox

**First affected release:** I remember seeing this issue a long time ago.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.149
Browser engine: Chromium
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 17 gb
Storage usage (approx): 170 mb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The problem is the project events have a dependency on the precise order the touch events are handled. The engine has to do these in *some* order, so there is no way to completely fix this. The best solution is to fix the events so it doesn't depend on this order.

I would argue that after "On drop", the touch has ended, and therefore the correct behavior is that the touch angle and speed are zero, because the touch has ended.

To work around this, track the touch angle and speed during a touch with global variables, and then refer to these variables in "On drop".
