### ISSUE TITLE
[Request] Inverting viewport dotted lines relative to background colour

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#372]
## Problem description

Whenever a dark colour is used on a non transparent layer, the black dotted lines that represents the viewport size can be very hard on the eye. If only the dotted lines would either invert colour relative to it's foreground or turn white when the foreground colour is dark.

Of course, there's a few ways around this. Such as by adding a dark coloured background layer that you don't place things on or change background colour of the layer "On start of layout" just to avoid the black doted lines blending in with any projects that have dark background colours.

**Comment by AshleyScirra** [comment]
Good point, it actually disappears entirely when the background is black. In r34 I've made it draw both black and white lines, much like the 'show grid' option, so it's easier to see regardless of the background color.
