### ISSUE TITLE
Apk built

### ISSUE THREAD

**Issue by Pianura11** [Scirra/Construct-3-bugs#3721]
I can't built in apk. The program give me a problem. 

## Attach a .c3p

I try to built an apk with cordova. 
The built start, but, in the end, it give me an error. 

1. 
2.
3.

## Observed result

Appare an error dialogue. 
I want to return to ecport in apk without problems. 

I want to return to built the apk. 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

"Culd not calculate current default file timestamp. " 
> No space left on device
"Command failed with exit code 1"

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by ERAgames777** [comment]
Through the construct 3 build service, it is also impossible to build a signed apk file.

**Comment by AshleyScirra** [comment]
Apologies, we had a brief outage on the build server. It should be working again now.
