### ISSUE TITLE
Worker + Desktop C3 + NW.js Object  = Excessive Preview Boot Up Times

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#3722]
## Problem description

Adding the NW.js object to desktop C3 causes previews to have excessive boot up time after the first initial preview if you have worker enabled.

## Attach a .c3p

[nwjsbug.zip](https://github.com/Scirra/Construct-3-bugs/files/4370612/nwjsbug.zip)

## Steps to reproduce

1. Run a preview a few times.

## Observed result

After the first time or two, the previews take much longer to start, especially if you have a full-fledged project rather than this example file.

## Expected result

It should take the same amount of time to run a preview as if you have worker disabled or no NW.js object or both.

## More details

**Affected browsers/platforms:** NW.js C3

**First affected release:** Been an issue for a while, but reporting finally for r189.2.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.44.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.0 (like Chrome/80.0.3987.87)
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 43 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Another weird NW.js bug. I filed it with them here: https://github.com/nwjs/nw.js/issues/7423

**Comment by corlenbelspar** [comment]
Thanks a bunch! It will be cool when you fix it.

**Comment by AshleyScirra** [comment]
To be clear, this is an issue with NW.js, and I've filed it with them since they need to fix it.

**Comment by corlenbelspar** [comment]
Is there some work around to this until NW.js is fixed? I'm getting tired of constantly swapping between Chrome and NW.js C3, turning off worker and possibly exporting with it turned off because I forgot about it, etc. My internet is slow, so uploading a 100+ MB file all for naught because I forgot to turn worker back on is not just a minor inconvenience.

**Comment by AshleyScirra** [comment]
Can you just use Chrome instead?

**Comment by corlenbelspar** [comment]
No because a core part of it uses file system actions. From the sounds of it, I'll just have to keep doing what I'm doing until they reply.
