### ISSUE TITLE
C3 doesn't load user profile

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3723]
## Attach a .c3p
No need file

## Steps to reproduce

1. Open Construct 3 
2. log in 
3. check your account info.

## Observed result
No Image at your profile

## Expected result
Profile Image

## More details

This occurs after r191 and is working fine in r190

**Affected browsers/platforms:** 
Chrome / WIndows

**First affected release:** 
 worked in r190 but broke in r191 and r192
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's a minor issue with the website affecting beta releases, it should be corrected soon.

**Comment by TomGullen** [comment]
I believe this is now fixed?

**Comment by luckyrawatlucky** [comment]
yes fixed

**Comment by AshleyScirra** [comment]
Thanks for confirming.

**Comment by luckyrawatlucky** [comment]
@TomGullen  this happening again in r194
