### ISSUE TITLE
Text - Custom woff font scaling doesn't respect project filter setting

### ISSUE THREAD

**Issue by broknecho** [Scirra/Construct-3-bugs#3726]
## Problem description

Using a custom woff web font at a really low resolution and then have the window maximized while scaling the layout will blur out the font.

## Attach a .c3p

[WebFontScalingIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/4377243/WebFontScalingIssue.zip)

## Steps to reproduce

1. Open attached project
2. Run layout at the low resolution
3. Observe the crip text at low resolutions
4. Maximize the preview window
5. Observe that the text has been filtered and is no longer crisp

## Observed result

When scaled out, the text is no longer crisp

## Expected result

The text to stay crisp when maximized respecting the pixel perfect settings of the project filtering.

Using Sprite fonts would be a workaround for this but I was just wondering if this was a bug, by design, or a limitation of how web fonts are used.

## More details

**Affected browsers/platforms:** 
Tested in Chrome

**First affected release:** 
189.2 Stable

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.149
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 139 gb
Storage usage (approx): 180 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Scale up the rendered image and you can see it is correctly using the 'Nearest' sampling as set in the project:

![text-aliasing](https://user-images.githubusercontent.com/768723/77533648-2a765c00-6e8f-11ea-8f67-1ef22b512dc0.png)

What's happening is the text is rendering with antialiasing at a small size, and then the rendered image is scaled up with 'Nearest' sampling. It is not blurry, it is a pixellated resize of text antialiasing. Note antialiasing is different to sampling, and currently browsers don't provide a way to turn it off for text rendering. Text is designed to be antialiased to improve the readability and rendering quality - if you don't want that then use a SpriteFont instead.

**Comment by broknecho** [comment]
@AshleyScirra Sorry that I didn't differentiate between anti-aliasing and filtering there.  I would think it is a good explanation for the Manual along with a caveat that the `Text` object is not suitable for `pixel art` games.  I don't think most users understand clearly the mix of `"Browser behaviors"` vs `"game engine behaviors"`.  That's probably my biggest hurdle when I teach Construct to new programmers.

I have never actually noticed this scaling issue as I've only used sprite fonts due to the Text object not supporting fonts that are packaged along with the game.  I thought the Text object was going to be more convenient now that you can include a `woff` file but it's limitations don't allow it to be used.  Good to know!

This would be a great blog post as per your twitter: The design complications mixing canvas rendering with the browsers html controls.

I personally do not ever use the HTML controls with Construct due to their drastic limitations (i.e. rendered on top of everything, CSS requirement to style them).  Would prefer a true UI system built using the same rendering technique as the rest of the engine.  For every project, I need to copy over event sheets like "Buttons" or "Text Input" so I can recreate those controls with sprites.

I'll go back to using spritefonts again :sadface:

Thanks for the explanation and hopefully just adding an item to the manual will clear this up!
