### ISSUE TITLE
End sound trigger problem

### ISSUE THREAD

**Issue by rozpustelnik** [Scirra/Construct-3-bugs#3730]
## Problem description

Hi. I'm using SpriteFont for Subtitles. When Sound is being played Spritefont should be Visible. When ->On sound ended Spritefont should become invisible, but somehow it is still visible, as if On sound ended didn't pass the sound tag for the trigger.

## Attach a .c3p

[endSoundTriggerError.zip](https://github.com/Scirra/Construct-3-bugs/files/4393995/endSoundTriggerError.zip)

## Steps to reproduce

1. See the EventSheet
2. Run Layout
3. 

## Observed result

After sound ends, Spritefont is still visible. 

## Expected result

After sound ends, Spritefont shouldn't be visible.

## More details

Desktop version of Construct3 - release 189.2 stable

**Affected browsers/platforms:** 

Desktop Construct3 so I think it's Nodejs

**First affected release:**  It is my first and only version of C3.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, you're right that 'Is playing' could be true for one tick after 'On ended' triggered. It's fixed for the next release, but in the mean time you can work around it by setting the SpriteFont visible when you use the "Play" action, rather than in the "Is playing" condition.

**Comment by rozpustelnik** [comment]
Thanks!
