### ISSUE TITLE
(IOS) Unable to build any C3 project with PhoneGap 

### ISSUE THREAD

**Issue by smallsim** [Scirra/Construct-3-bugs#3731]
Unable to build any C3 project with PhoneGap for IOS.
On PhoneGap tere is an error. Log:

** ARCHIVE FAILED **

The following build commands failed:
	ProcessPCH /private/project/build/sharedpch/testproject-Prefix-avlayafcpgggodfvmovsewvatnbc/testproject-Prefix.pch.pch testproject/testproject-Prefix.pch normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
## Attach a .c3p

[testproject.zip](https://github.com/Scirra/Construct-3-bugs/files/4397044/testproject.zip)

## Steps to reproduce

1. Build simple project in C3: export -> cordovaIOS -> cordova project.
2. Upload cordovaProject.zip to PhoneGap
3. Add key on PhoneGap and try to Build IOS
4.  Cannot build - error.

## Observed result

Cannot build any app with cordova IOS on PhoneGap.

## Expected result

Build .ipa file as normally.

## More details

I have tried several various keys and apps. Doesn't work.
C3 cannot build cordova-IOS for now. 
It is important because Apple will delete all apps if it will not support IOS13 sdk on 30 June.
XCode-export option is not a variant for me cause of my MacBook do not support xcode with needed sdk. So for now it seems like C3 _cannot does any IOS build_. Please help.

**Affected browsers/platforms:** 

C3 - r189.2 Latest Stable.

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by smallsim** [comment]
It seems like Adobe cancelled PhoneGap service... I think this is their problem, not C3. May I be right?

**Comment by smallsim** [comment]
@AshleyScirra I remember your words from your blog post - that "C3 will be able to build .ipa later like it does with Android .apk". Did Scirra rejected this feature?

**Comment by AshleyScirra** [comment]
According to Adobe PhoneGap Build is in maintenance mode. It will probably be retired at some point. We also can't be responsible for problems with third-party services, so you would need to contact Adobe to see if they could do something about this, but it seems unlikely they will keep working on it.

**Comment by smallsim** [comment]
You should edit manuals and official tutorials with PhoneGap. :)
So can you answer about making .ipa from C3 building service?

**Comment by AshleyScirra** [comment]
Apple's restrictions make it too difficult to be feasible.
