### ISSUE TITLE
[Drawing Canvas] Offsets draw position from 0,0 position

### ISSUE THREAD

**Issue by SalmanShhh** [Scirra/Construct-3-bugs#3733]
## Problem description

I noticed that if I move the drawing canvas object all the drawing positions i pass to it get offset based on the distance from 0,0 position.

## Attach a .c3p

https://cdn.discordapp.com/attachments/517079142681018368/694011728228253747/Drawing_canvas_bugged_-_Bugged.c3p

## Steps to reproduce

1. left click to toggle camera scroll, move with arrow keys.
2. using the arrow keys move the character away from the corner of the layout
3.

## Observed result

![drawing canvas - bug  ](https://user-images.githubusercontent.com/21278459/77868976-e4295000-7234-11ea-9473-f963b9c38a94.gif)
(in the gif - red = scrolling |  white = not scrolling)

in the gif, I toggle scrolling to show the issue in action

## Expected result

![drawing canvas - bug fix  ](https://user-images.githubusercontent.com/21278459/77869206-995c0800-7235-11ea-9fae-559c00d400ff.gif)
this is what I expected to happen but the only way i figured out how to make it work was by adding the following actions on the position I'm passing to drawing plugin object in my drawing function.
![image](https://user-images.githubusercontent.com/21278459/77869241-ba245d80-7235-11ea-8a68-ff16b5f62378.png) 

since Im moving drawing object with the anchor behaviour it seems to work but I don't believe this is intended to work like this.  expected it to draw within the positions passed to it.

which i do in this https://cdn.discordapp.com/attachments/517079142681018368/694011889658888223/Draw_FOV_-_Working.c3p

its the same file but with the changes from the image above to make it work. 

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's not a bug. As described in the [Drawing Canvas manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/drawing-canvas), draw co-ordinates are relative to the object, not the layout.
