### ISSUE TITLE
Pin behavior angle changed on R193

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-3-bugs#3734]
## Problem description

1) Pin to object with position and angle behave differently into version R193.
The attached C3 project created with R192 show sprite2 and sprite3 able to rotate.
Sprite2 is pinned to Sprite
Sprite3 is NOT pinned
both rotate using R192
Only sprite3 rotate using R193

2) Pin to object action created with version R192 can't be modified  using new parameters. In order to see the new pin to object option I need to create the action from scratch.

## Attach a .c3p
[r193 New Pin bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4404102/r193.New.Pin.bug.zip)

## Steps to reproduce

For issue 1 - Just run the C3 file into R192 and into R193 to see the differences.
For issue 2 - doble click the action into R192 and into R193 to see the differences.

## Observed result

On R192 the 2 red cross rotates
On R193 just sprite2 rotate.
## Expected result

I do expect both red cross rotates.
## More details

**Affected browsers/platforms:** 
It has been test on Chrome only.

**First affected release:** 
R193

## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Browser: Chrome
Browser version: 80.0.3987.149
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
C3 release: r193 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 273 gb
Storage usage (approx): 253 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
The behaviors seem to conflict: should the object angle be controlled by the Rotate behavior (making it spin), or by the Pin behavior (keeping it at a fixed relative angle)? What do you expect Construct to do in this case? It's kind of awkward because when you set up conflicting behaviors, changes to the engine can make the conflict resolve a different way.

**Comment by rraffo** [comment]
Analyzing the behavior into both R192 and R193 it appears that it makes more sense and correct what it is happening into the R193 version.
Actually if I pin an object into another and anchor it to a position and an angle I do expect that the behavior is driven by the pinning object (the Sprite on my example). But what if I apply a rotation to the pinned object (Sprite2)? Who is the commander? it is a matter of hierarchies but also of design.
In the real world probably since I pin an object to another I do expect the pinned object will be driven by the pinning.
I agree with you it is a kind if awkward...
What is your opinion?

**Comment by avishaymizrav** [comment]
Same issue with just setting position, the action showed in the eventsheet is still the old one (mode: position only), it though the debugger shows the object is pinned, moving the pinned to object doesn't affect the pinned object.

If I add a new action with the new X Y, then it works fine.

But I believe the editor should automatically convert old actions into new one, if the old one are not functioning anymore.

**Comment by AshleyScirra** [comment]
Well, I think we have to match the old behavior regardless for backwards compatibility, we can't really allow breaking changes like this for no reason.

It looks like it was deliberately done in C2, probably years ago (I don't have the C2 code logs to check at the moment while working from home). It's special treatment for the angle property only: if something else rotates the object, the pin behavior detects this and compensates its pin angle. I added back the same detection to the pin behavior and it seems to work consistently to how it used to again, so it should be fixed in the next beta.

@avishaymizrav - I think you are talking about an unrelated issue. Pinning to position only was accidentally broken in r193 due to unrelated causes. However I separately found and fixed that too.

**Comment by rraffo** [comment]
> Well, I think we have to match the old behavior regardless for backwards compatibility, we can't really allow breaking changes like this for no reason.
> 
> It looks like it was deliberately done in C2, probably years ago (I don't have the C2 code logs to check at the moment while working from home). It's special treatment for the angle property only: if something else rotates the object, the pin behavior detects this and compensates its pin angle. I added back the same detection to the pin behavior and it seems to work consistently to how it used to again, so it should be fixed in the next beta.
> 
> @avishaymizrav - I think you are talking about an unrelated issue. Pinning to position only was accidentally broken in r193 due to unrelated causes. However I separately found and fixed that too.

I perfectly understood and agreed with your decision.
Thanks for sharing the consideration.
Riccardo
