### ISSUE TITLE
Sprite Font not working

### ISSUE THREAD

**Issue by ClauSita** [Scirra/Construct-3-bugs#3736]
## Problem description

The Sprite Font is not working correctly when I open the Editor I can see the Sprite properly, but in the screen, the font looks black (originally it is white with black border).
I already export the project and it is still wrong. I have reloaded construct and tried with different Sprite Fonts and however, the results are the same. The Sprite that I use in the attached project I already use it in another project and it worked perfectly fine.

## Attach a .c3p

[spriteFontNotWorking.zip](https://github.com/Scirra/Construct-3-bugs/files/4412223/spriteFontNotWorking.zip)

## Steps to reproduce

1. Open the project
2. Run the project
3.

## Observed result

The SpriteFont doesn't look correctly.

## Expected result

Sprite Fonte looking like the one in the Editor.

## More details

I exported the project to Instant Facebook Games, to Android and to HTML games and it doesn't work.

**Affected browsers/platforms:** 

Google Chrome
Versión 80.0.3987.149 (Build oficial) (64 bits)

**First affected release:**  I can't remember the last time I used it, but now I'm in the r.189.2 stable

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.149
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 43 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 8000 Hz
Output channels: 1
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The SpriteFont color is set to black, so it will draw all black. If you don't want a color filter on the sprite font, change the color property to white.

**Comment by ClauSita** [comment]
Thank you!
