### ISSUE TITLE
Pin behavior break in C3, C2 -> C3

### ISSUE THREAD

**Issue by rozpustelnik** [Scirra/Construct-3-bugs#3737]
## Problem description

Newly released pin behavior breaks the project.

## Attach a .c3p

[pin_C2_to_C3_break.zip](https://github.com/Scirra/Construct-3-bugs/files/4420591/pin_C2_to_C3_break.zip)
[pin_C3_import_break.zip](https://github.com/Scirra/Construct-3-bugs/files/4420592/pin_C3_import_break.zip)

## Steps to reproduce

1. Run C2 project -> pin works as expected.
2. Import C2 into C3 or use C3 project -> pin not working.
3.

## Observed result

Pin doesn't work, even if it worked OK in previous C3 release.

## Expected result

Pin should work regardless of importing C2 project or previous C3 project.

## More details
Tested on Node.js and Chrome

**Affected browsers/platforms:** 

r193 beta

**First affected release:** 

## System details

Platform information
Browser: NW.js
Browser version: 0.44.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.0 (like Chrome/80.0.3987.87)
C3 release: r193 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 85 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 570 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
There was a regression in r193 that broke the "Position only" mode specifically, the others should still work. This is fixed for the next release.

**Comment by rozpustelnik** [comment]
Excellent! Thanks!
