### ISSUE TITLE
C3proj file changes unreliably on save

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3738]
## Problem description

This is a problem that's hard to reproduce. Basically, when using git on a fairly large Construct project, very often, between two branches, the list of files, or musics, or sounds can change their order, and this causes merge conflicts for no reason.

## Attach a .c3p

n/a

## Steps to reproduce

1. Have a project with a lot of files (something like kiwi story)
2. Start a git project, make multiple branches and commits on each branch.
3. make a merge

## Observed result

This is a PR on a project i'm workin on, and you can see the diff on the music files in the game, but the music files weren't touched at all.
![image](https://user-images.githubusercontent.com/11213825/78251382-8bd2a680-74f1-11ea-916d-11d2dd948e0e.png)

The same with project files lower 
![image](https://user-images.githubusercontent.com/11213825/78251508-bb81ae80-74f1-11ea-9ac1-604f70be1343.png)

## Expected result

This shouldn't happen

## More details

I supposed this was due to some optimisation done during saving that caused this, and also I have no idea what actually causes this to happen and I couldn't manage to reproduce it in a small project. it just seems random, and more likely the more you made changes to the project (aka did actual work not dummy tests).

The worst thing is when the auto merge badly merges together files, and it causes a file to be listed multiple times or removed entirely from the list, so I need to manually edit the file each time and write the correct names and correct number of files. It's a very tedious and very unnecessary process to go through.

**Affected browsers/platforms:** dekstop

**First affected release:** forever afaik

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by skymen** [comment]
So you can see how much of an issue this is, all of these are project files, and in this PR, I added no layout, no object and didn't remove anything. I just changed events code.

![image](https://user-images.githubusercontent.com/11213825/78251977-685c2b80-74f2-11ea-8dec-04f9b43d477c.png)


Might be a good idea to mention that this project has been worked on the desktop version of C3, so this might be related, no idea.

**Comment by AshleyScirra** [comment]
I assume this only happens with project files and nothing else? I checked our code and despite everything trying to preserve the ordering of project files, there was an accidental race condition, meaning they got added in the order they finished loading, which would have been a source of unpredictability. I've fixed that for the next release so they properly preserve the order regardless of how long each individual file takes to load. I think it will be worth verifying this doesn't happen any more with your project after the next release since it seems non-deterministic.

Let me know if you find any more cases of unpredictable/unwarranted changes to project files like this, it's important we fix them so source control works smoothly, as you've noted.

**Comment by skymen** [comment]
It happened once with scripts, but never again.
But yeah, assuming you mean musics and sound files are project files, then yeah it's only project files. Objects, layouts etc are all in the order displayed in the editor

**Comment by AshleyScirra** [comment]
Scripts are internally treated as another kind of project file too, so this should cover them as well.

**Comment by skymen** [comment]
Great then, I'll try with the next release and let you know

**Comment by AshleyScirra** [comment]
r194 is now out, please check again!

**Comment by AshleyScirra** [comment]
No response so closing on the assumption this is resolved.
