### ISSUE TITLE
Pathfinding Collision Bug

### ISSUE THREAD

**Issue by Bigbeto123** [Scirra/Construct-3-bugs#3739]
Objects using the pathfinding behavior plus physics/solid will simply ignore the collision restrictions in order to walk through their paths.

## Attach a .c3p

[bugreport.zip](https://github.com/Scirra/Construct-3-bugs/files/4422468/bugreport.zip)

Create an object with pathfinding plus solid OR physics behavior. Make it find a path (32 sized cell, -1 border; objects size = 32x32) through some random (solid) obstacles and see them occasionally walk through it (specially their corners).

1.Already
2.Said
3.Before

## Observed result

They should respect the obstacle borders and don't walk through them

they walk through the solid obstacles

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
Current beta r193, but seen it happen long ago as well
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.149
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
C3 release: r193 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 395 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is currently by design: the Pathfinding behavior ignores solids for movement. It only uses them to calculate paths around. This is because if the movement stops on solids, objects constantly get stuck, which is an even worse problem. You need to adjust the cell size, border size, object sizes and movement properties to ensure this does not become an obvious problem. For example smaller objects with a cell border means the paths are always calcuated a certain distance away from the solids, which avoids any movement overlapping them.

**Comment by Bigbeto123** [comment]
I've tried multiple cell border sizes, and none worked... They all make the objects to be completely still (99% of the time)
