### ISSUE TITLE
[r31] Dragged in images as Sprite objects still reference local paths

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#374]
## Problem description

Into simplifying the reproduce steps, I found the shortest way to crash with the same issue without having to play around with frames which was initially how I got a crash.

This could make some sense on this issue too: https://github.com/Scirra/Construct-3-bugs/issues/284

## Steps to reproduce

1. Drag in an image onto a layout.
2. Delete the source image on your local disk file manager.
3. Undo and Redo Construct editor.

## Observed result
crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: The source image cannot be decoded.
Construct 3 version: r31
URL: https://editor.construct.net/index.html
Date: Sat May 27 2017 12:03:16 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 90491.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
This is pretty interesting, I didn't know browsers kept references to the original file like that. I've added an extra copy step in r32 to avoid this problem. Thanks for the repro.
