### ISSUE TITLE
C3 NWjs beta - keeps defaulting my loader style to C3 splash screen.

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#3744]
## Problem description

Every time I run a C3 project when C3 is not loaded, the loader style option keeps changing into C3 splash screen.

## Attach a .c3p

Happens on all c3p files.

## Steps to reproduce

1. Create a new project.
2. Change loader style to anything but C3 splash.
3. Save project.
4. Close C3.
5. Open project by double clicking it in windows.

## Observed result

Loader style defaults back to C3 splash.

## Expected result

Keep project selected loader style.

## More details

Note, this only happens if I open the c3p from windows with no C3 instance running.
If C3 is already running it doesn't happen.

Windows 

r192

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.44.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.0 (like Chrome/80.0.3987.87)
C3 release: r193 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 11 gb
Storage usage (approx): 192 mb (1.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 750 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I couldn't reproduce this at first, but I think it's a tricky timing issue: since the app launches and opens a project right away, it might finish opening the project before the account service has figured out if you've got a subscription or not. In that case it will default to the free edition and impose the free limits, which switches the loader style. The fix is to wait for the account service to finish identifying its state before trying to open the project, but this can take several seconds (especially if working offline). So I added a progress message while it waits for that so you know why it hasn't opened the project yet.

Given the unpredictable timings involved, please check again on your side when the next release is out to verify it's working.

**Comment by AshleyScirra** [comment]
r194 is now out, please check again!

**Comment by avishaymizrav** [comment]
Yes, it works fine now, thank you!

**Comment by AshleyScirra** [comment]
Thanks for confirming.
