### ISSUE TITLE
The Tilemovement Template on start page not working since r193

### ISSUE THREAD

**Issue by sizcoz** [Scirra/Construct-3-bugs#3749]
The Player_box Pinned to the player, does not move with Pin to (Position only) in the Template, but if you change it to (Position & Angle) it works again.

On Start page

Open Tile based Template in r193, and Player does not move.

1.
2.
3.

## Observed result

Player to move

Player did not move

Only tried chrome

broke in r193,  works in r189.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Same as #3737, fixed
