### ISSUE TITLE
Crash, possibly while adding "Else" block with "X" key.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3751]
## Problem description

I don't exactly remember what was the very last thing I did, because I was storming through some process, but it was probably related to adding an "Else" block through "X" key.

## Attach a .c3p

n/a

## Steps to reproduce

Could not reproduce.

## Observed result

Crash.

## Expected result

Not crashing.

## More details

n/a

**Affected browsers/platforms:** latest chrome.
**First affected release:** 194

## System details

<details><summary>View details</summary>
Error report information
Type: assertion failure
Message: cannot select detached view
Stack: Error at Function.ǃk.ǃgfB (https://editor.construct.net/r194/main.js:2:127848) at e (https://editor.construct.net/r194/main.js:2:85068) at window.assert (https://editor.construct.net/r194/main.js:2:85398) at o.ǃjs (https://editor.construct.net/r194/components/editors/eventSheetView/eventSheetView.js:1:13985) at o.ǃMi (https://editor.construct.net/r194/components/editors/eventSheetView/eventSheetView.js:1:12184) at o.ǃZfn (https://editor.construct.net/r194/components/editors/eventSheetView/eventSheetView.js:1:21453) at Array. (https://editor.construct.net/r194/components/editors/eventSheetView/eventSheetView.js:1:2783) at ǃk.Event.ǃgIZ.ǃgIy (https://editor.construct.net/r194/main.js:2:200113) at ǃk.ǃbE.ǃKL.ǃkRB.dispatchEvent (https://editor.construct.net/r194/main.js:2:197895) at ǃk.ǃbE.ǃKL.ǃkRB.ǃrc (https://editor.construct.net/r194/main.js:2:281404) at d.ǃrc (https://editor.construct.net/r194/main.js:2:284956) at HTMLDocument. (https://editor.construct.net/r194/main.js:2:283086)
Construct 3 version: r194
URL: https://editor.construct.net/r194/
Date: Tue Apr 07 2020 12:53:37 GMT-0300 (Brasilia Standard Time)
Uptime: 21819.7 s

Platform information
Browser: Chrome
Browser version: 80.0.3987.149
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
C3 release: r194 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2
</details>

**Comment by AshleyScirra** [comment]
I'm afraid in general it's impossible to investigate reports without steps to reproduce. This is why they are required.

**Comment by dupuqub** [comment]
you did see the crash report, right? no clues there?

**Comment by AshleyScirra** [comment]
No, the crash report alone is usually not enough. Besides all crashes are automatically logged with us and we periodically review them and fix any issues that we can figure out with a bit of guesswork from the crash report alone. So there's no need to manually report just a crash report alone, and usually it means we already couldn't figure it out from that alone.
