### ISSUE TITLE
On tween end & destroy object not working as expected

### ISSUE THREAD

**Issue by dru1000** [Scirra/Construct-3-bugs#3755]
## Problem description

When using the "Destroy on tween end" with multiple sprites it doesn't destroy the sprite. 
But it does work when only one sprite is used.
Plus having an object pinned to the sprites also seems to affect whether the sprites are destroyed or not.

Very odd.

## Attach a .c3p
[Destroy with pinned object.zip](https://github.com/Scirra/Construct-3-bugs/files/4455428/Destroy.with.pinned.object.zip)

## Steps to reproduce

1. Play the attached project. The 5 sprites are set to destroy on end of tween.
2. The sprites remain after the tween ends.
3. If you remove the "Destroy with pinned object" check box from the pinned text it should now work. Also using just one sprite works fine.

## Observed result

Nothing gets destroyed.

## Expected result

All sprites and text objects are destroyed.

## More details
On R194 and Chrome.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next beta.
