### ISSUE TITLE
Flood Fill in Animation Editor - tolerance slider issue

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#3757]
## Problem description

The Flood Fill tool in Animation Editor doesn't detect colors very well and in many situations is practically unusable.

## Attach a .c3p

https://www.dropbox.com/s/b9o8xw8589zts8f/FloodFillBug.c3p?dl=0

See this gif:
https://media.giphy.com/media/MXR7z2evZJ3YEopZ6O/giphy.gif
![gif](https://media.giphy.com/media/MXR7z2evZJ3YEopZ6O/giphy.gif)

## Steps to reproduce

1. Paste almost any image with opaque background and try to erase the background

## Observed result

Very difficult to find the right tolerance. 
Practically no difference between tolerance 0 and 250.
Then I move tolerance slider just 1mm and it floods almost the entire image.

## Expected result

Working tolerance slider.

## More details

Similar to this bug:
https://github.com/Scirra/Construct-3-bugs/issues/3076

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.44.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.0 (like Chrome/80.0.3987.87)
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 63 gb
Storage usage (approx): 309 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's worth comparing this to the tolerance for flood fill in Paint.NET. It does seem to do a better job of handling tolerance there. Also Paint.NET uses a percentage tolerance rather than just a number, so perhaps the tolerance algorithm it uses is different and better.

**Comment by DiegoScirra** [comment]
I think this is working better now, check it out in the next beta!

**Comment by AshleyScirra** [comment]
r198 is now out, please check again!

**Comment by dop2000** [comment]
@AshleyScirra @DiegoScirra 
It's better now, but still not quite there. The scale goes from 0 to 500, but there is not much difference between 50 and 500. I expect at 500 it should fill a very wide range of similar colors, but it doesn't, for example:
[![Capture.jpg](https://i.postimg.cc/15WdBBjs/Capture.jpg)](https://postimg.cc/HVy3swmh)

I also experimented on grayscale palettes [like this one](https://1.bp.blogspot.com/-2wsOF9awhCQ/Vl8GqWa8OaI/AAAAAAAAA9s/iFjSnJc_m3A/s1600/grayscale.jpg), and it only fills one line no matter what the  tolerance setting is.

**Comment by SnipG** [comment]
I think this is the issue for release 198 bucket tool flood fill change.

Bucket tool flood fill is in r198 much much worse then in r197. It should be reverted!!

**Comment by DiegoScirra** [comment]
I thought I could solve this quickly, but it seems it is more difficult than I thought, so I'll be reverting this to the previous state in r197.

**Comment by DiegoScirra** [comment]
I found out a rather obvious issue with how tolerance was applied, that is fixed now and I think the tool works a little bit better now, you will need to check it out in the next release.

**Comment by AshleyScirra** [comment]
r202 is now out, can you check again there?

**Comment by dop2000** [comment]
It's definitely much better now!

**Comment by AshleyScirra** [comment]
This sounds like it was successfully fixed so closing.
