### ISSUE TITLE
When pressing command+s multiple times C3 crashes

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#376]
## Problem description

*Just mash command+s to save, multiple times. While the popup appeared "saving to dropbox", a second or so later it crashes.*

## Attach a .c3p

*It does that on any demo project in C3*

## Steps to reproduce

1.Open demo project
2.save project in dropbox
3.make a change so saving could be done
2.Mash command+s multiple times in quick succession  while saving to dropbox already appeared
3.????
4.Profit. (crash)

## Observed result

*C3 crashes*

## Expected result

*Not crash*

## Affected browsers

* Chrome: **yes**
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: dialog not open @ Error: dialog not open at ǃB.ǃo.ǃRO.ǃzCQ.ǃzCP (https://editor.construct.net/r31/main.js:2:349583) at ǃB.ǃo.ǃRO.ǃzCQ.ǃzCP (https://editor.construct.net/r31/main.js:2:364356) at ǃB.ǃo.ǃRO.ǃzCQ.ǃzVz (https://editor.construct.net/r31/main.js:2:350757) at te.then.be (https://editor.construct.net/r31/main.js:162:5281) at 
Stack: Error: dialog not open at ǃB.ǃo.ǃRO.ǃzCQ.ǃzCP (https://editor.construct.net/r31/main.js:2:349583) at ǃB.ǃo.ǃRO.ǃzCQ.ǃzCP (https://editor.construct.net/r31/main.js:2:364356) at ǃB.ǃo.ǃRO.ǃzCQ.ǃzVz (https://editor.construct.net/r31/main.js:2:350757) at te.then.be (https://editor.construct.net/r31/main.js:162:5281) at 
Construct 3 version: r31
URL: https://editor.construct.net/
Date: Sat May 27 2017 19:52:37 GMT+0800 (+08)
Uptime: 65.1 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Has been fixed with (#375)[https://github.com/Scirra/Construct-3-bugs/issues/375], should see it in the next release!
