### ISSUE TITLE
Whitelist followup request. [Mobile IronSource]

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#3760]
Hi, thank you for adding the plugins today.
Reference: 
https://github.com/Scirra/Construct-3-bugs/issues/3725

**Although**, I would like to request a few follow-up updates to the following plugins:
```
chadori-mobile-ironsource@0.0.2
chadori-mobile-ironsource-debug@0.0.2
```
-----

I made a few minor dependency updates.
3 days ago, the **IronSource Android SDK** updated their mediation sdk from `jar` to `aar`.
```
implementation 'com.ironsource.sdk:mediationsdk:+'
```
And, I've also added these:
```
    implementation 'com.google.android.gms:play-services-ads-identifier:+'
    implementation 'com.google.android.gms:play-services-basement:+'
```
To be able to retrieve the `advertising id` independently from **Admob Ads**.

-----

I hope this is expedited, having only 3 changes. Thank you.

**Comment by Chadori** [comment]
By the way, we can't use the **C3 Build Service** without this update, I'm afraid.

**Comment by AshleyScirra** [comment]
Is there a GitHub repository I can look at or could you provide a diff between the versions? It's much quicker to review only the changes between versions when updating a plugin version. Otherwise I have to treat every new version as a whole new plugin and review it from scratch again.

**Comment by AshleyScirra** [comment]
Actually I found the combination of WinMerge and npm pack can show a diff between versions which should help speed this up. I noticed in the diffs it also adds `implementation fileTree(dir: 'libs', include: ['*.jar'])` to IronSourceC.gradle which you didn't originally mention. Is this necessary? It looks like a wildcard include for .jar files, but there don't appear to be any in the plugin. I'd rather keep the dependencies to the strict minimum if possible.

**Comment by Chadori** [comment]
@AshleyScirra Yeah there is, it's a private repository. I've added you as a collaborator.

**Comment by AshleyScirra** [comment]
I think you commented at the same time as my previous comment - thanks, I appreciate it, but I think WinMerge and npm pack will be OK actually, and is probably better since it goes by what npm really serves. If you prefer to remove me as a collaborator for security then that's OK.

**Comment by Chadori** [comment]
Ah I see. Thanks for looking at it.

-----

![image](https://user-images.githubusercontent.com/31282960/79129069-22974100-7dd7-11ea-8155-1221f0218694.png)

`implementation fileTree(dir: 'libs', include: ['*.jar'])`
Unfortunately, it is a requirement to obtain the `Google Advertising ID`.

**Comment by AshleyScirra** [comment]
It's easier to review these details if you just link to the page instead of screenshotting it. After some Google searching, I think you are referring to this page: https://developers.ironsrc.com/ironsource-mobile/android/android-sdk
Is that correct?

**Comment by Chadori** [comment]
Yes, that is correct.

**Comment by AshleyScirra** [comment]
OK, thanks. Updated both plugins to 0.0.2 in whitelist, changes are now live on build server.

**Comment by Chadori** [comment]
Thank you very much!
