### ISSUE TITLE
Tween behavior doesn't tween floats anymore

### ISSUE THREAD

**Issue by rilem** [Scirra/Construct-3-bugs#3761]
## Problem description

Since a recent update the tween behavior doesn't work as it used to anymore. I use a lot of small float tweens in my projects: tweening a position from 1 to 1.5 for example. 

I noticed the tween behavior doesn't support this atm, it just rounds to the nearest int until the tween is complete. Then it pops to the desired value.

## Attach a .c3p

[buggedtween.zip](https://github.com/Scirra/Construct-3-bugs/files/4469263/buggedtween.zip)

## Steps to reproduce

tween an position from 1 to 0.5 for example and see the debugger position of the object. Also the case for angles, width, height etc.

## Observed result

Object stays in place until tween is complete. Then snaps to end value.

## Expected result

Smooth transition.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
