### ISSUE TITLE
r189.2 runtime.callFunction('name', ['param1', 'param2']) fails

### ISSUE THREAD

**Issue by Sanquen** [Scirra/Construct-3-bugs#3762]
According to doc https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/events/functions
![image](https://user-images.githubusercontent.com/63592788/79121222-b394fa80-7d8c-11ea-8478-5f96dfc4df66.png)
But it fails invariably
![image](https://user-images.githubusercontent.com/63592788/79121289-daebc780-7d8c-11ea-8a14-c2c9d1f02a3f.png)
See attached .c3p project
[bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4469522/bug.zip)

**Comment by AshleyScirra** [comment]
This issue contradicts the attached project. You highlight a call to `c3_callFunction` about which the documentation states:

> Do not call this with Construct's scripting feature. It will not work correctly. In that context you must use `runtime.callFunction()` instead.

The attached project does call `runtime.callFunction()`, which [as documented](https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/iruntime), uses the signature `callFunction(name, ...params)`. The project uses the wrong signature (`runtime.callFunction('Function1', [0, 1])`), and works correctly if you use the right one (`runtime.callFunction('Function1', 0, 1)`).

**Comment by Sanquen** [comment]
ok, thanks, slightly confusing though, doc
https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/events/functions
should highlight the only diff is the way params are passed since methods
have the same name...

**Comment by AshleyScirra** [comment]
You're not even meant to read that part of the documentation if you're using scripting - before that it says:

> **Scripting**
> When using scripts in Construct, use runtime.callFunction() to call an event function from script.

If you click through to that it documents the method and its parameters.

**Comment by Sanquen** [comment]
fair enough
