### ISSUE TITLE
Youtube iFrame not loading (IOS)

### ISSUE THREAD

**Issue by klssem** [Scirra/Construct-3-bugs#3763]
## Problem description
iFrame does not load a youtube video when the game is exported to IOS.

I am trying to embed a youtube video in one of my layouts. Using the iFrame object, I added the url information in the properties panel. When I export the game to android it works as expected. When I export for IOS it does not load.

## Attach a .c3p

[iFrame test.zip](https://github.com/Scirra/Construct-3-bugs/files/4470438/iFrame.test.zip)

## Steps to reproduce

1. export to ios
2. Build and run to/in an IOS device
3. 

## Observed result
         

 Nothing happens. The iframe will not load the video. It works in the preview and also when exported to android

## Expected result

     It should show an embedded video, inline.

## More details

    When I try remote preview with an iPad it does work.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Looks like we need to apply `<allow-navigation>` in Cordova for iframe URLs. This change has been made for the next release and the change has also been applied to the build server which is live now - so it may be fixed already if you use Construct's build service.
