### ISSUE TITLE
[Whitelist] Power Management

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#3765]
Hi, 

Hopefully this is my last whitelist request for a while.

I would like to request to replace the `cordova-plugin-powermanagement-orig@1.1.2`,
with the `chadori-mobile-powermanagement@0.0.1`.

This is to remove the unnecessary code from the original plugin, including support for `windows` and `windows-phone`. I also fixed the iOS build issue from the original plugin.
But, in terms of functionality for Android, it should still work, so no rush. 

If you guys are busy, please take your time, we can wait. Thank you.

**Comment by AshleyScirra** [comment]
`chadori-mobile-powermanagement@0.0.1` is now on the whitelist.

**Comment by Chadori** [comment]
Thanks!
