### ISSUE TITLE
[Whitelist] Build Service plugin support request.

### ISSUE THREAD

**Issue by bedfl2016** [Scirra/Construct-3-bugs#3766]
Hi. I would like to request support for a plugin,

Please can you add:

https://github.com/missive/cordova-plugin-openwith

I would like an addon to get supported by the **C3 build Service** So that I don't have to export through Cordova CLI to be able to build directly.

**Comment by AshleyScirra** [comment]
Plugins are whitelisted by their npm package. `cordova-plugin-openwith` does not appear to be on npm, therefore we cannot whitelist it. What is the relevant npm package name?

**Comment by bedfl2016** [comment]
@AshleyScirra 

Hi I have contacted the dev and he has said he does not plan on adding npm support. Are there any tutorials on how to convert a Cordova plugin to an npm package? If not I will have to hire someone to convert it.

**Comment by AshleyScirra** [comment]
I'm afraid that's out of scope for what we can help you with. I'll close this issue for the time being but feel free to open a new one once you have an npm id. Also take note of the tips about Cordova plugins here: https://www.construct.net/en/forum/construct-3/plugin-sdk-10/build-server-cordova-plugin-149266

**Comment by bedfl2016** [comment]
Ok thank you!
