### ISSUE TITLE
Documentation Discrepancy: Wait Action In Functions

### ISSUE THREAD

**Issue by Lowcanrihl** [Scirra/Construct-3-bugs#3767]
## Problem description

 
This is not a bug within the software, but an error within the documentation. I am unsure if this is the correct place to report this, but I will anyhow. In the system action page at the first following url there is link in the wait action that goes to a construct 2 wait action tutorial. Most of the information is accurate for construct 3, but function parameters are no longer forgotten when using the new built in functions. This may cause others confusion as it did me. I almost went through my entire project correcting the issue even after testing when I noticed the function parameters were not forgotten as I was unsure if it was a for certain thing. 

The second link added confusion as I kept finding it when searching for the solution and finally after much searching the third link resolved the issue. Scirra I commend all of you and the software, but I would like to stress the importance of discrepancies like this in the official manual especially in software that is designed to be geared toward not as technical people. Keep up the good work and continue to polish. 

Thank you for your time and if this is not the right place for the above issue I apologize and would like to ask if I could please be directed where to report issues similar to this one. Thank you again.

[https://www.construct.net/en/make-games/manuals/construct-3/system-reference/system-actions](url)

[https://www.construct.net/en/forum/construct-2/closed-bugs-22/function-parameters-dont-stay-85435](url)

[https://www.construct.net/en/forum/construct-3/how-do-i-8/prevent-function-parameter-145353](url)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Well spotted, there were actually a few old links to scirra.com in that part of the manual which all redirect to Construct 2 pages. These should all be updated to construct.net links to Construct 3 pages now. However in the case of 'Wait' it linked to a 9 year old tutorial (!) for C2 that was never updated for C3, so I just removed the link to avoid misleading info. The functions feature was redesigned last year, and the ability to keep parameters past 'Wait' was added then, so it was correct until then!
