### ISSUE TITLE
NWjs object is not creating folders and files.

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#3773]
## Problem description

NWjs object is not creating folders and files.

## Attach a .c3p

[saveNwjs.zip](https://github.com/Scirra/Construct-3-bugs/files/4487205/saveNwjs.zip)

## Steps to reproduce

1. Try creating a folder in the user's system directory
2. If folder is created manually, trying to write the file doesn't work either

## Observed result

Files and folder are not created.

## Expected result

Files and folder created.

## More details
I tried testing the latest 3 version of NWjs and also version 33.3 which I know works on my C2 project.

**Affected browsers/platforms:** NWjs

**First affected release:** tested on r195

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.44.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.0 (like Chrome/80.0.3987.87)
C3 release: r195 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 8.8 gb
Storage usage (approx): 843 mb (9.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 750 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It seems to be working fine here. I verified it successfully created Saved Games\Test Game\save.sav in my user folder.

**Comment by avishaymizrav** [comment]
What do you purpose I do?

The fileError expression returns "no such file or directory" when creating the folder, which doesn't help much. Anyway other way to debug it?

I tried updating my windows, I tried running as administrator.
Running the exact same actions on C2 works, I just doubled check, so it's not something related to my system.

I can't have saved games not working for some users, for whatever reason that is.

**Comment by avishaymizrav** [comment]
OK, I have more details!

I looked in the dev console, and I noticed it was looking for 
/Users/Username

The game is not installed on my root drive, so it looks in z:\users\username
Where it should be systemDrive:\users\username

moving the project to C:\ fixed the issue.

**Comment by AshleyScirra** [comment]
Ah, I see, running the app on a different drive was the key detail here.

I don't know why Node was never returning the drive letter for that, and always assumed Windows figured out what to do, but I guess not. I found a different way to get the user folder in Node which looks like it includes the drive letter, so switched to that for the next release.

**Comment by avishaymizrav** [comment]
Thanks, I appreciate it!
