### ISSUE TITLE
[whitelist] GameAnalytics Cordova Plugin to version 3.0.8

### ISSUE THREAD

**Issue by SalmanShhh** [Scirra/Construct-3-bugs#3774]
Hi,

Would you please update an existing plugin version to cordova-plugin-gameanalytics@3.0.8.
Thanks. 

https://www.npmjs.com/package/cordova-plugin-gameanalytics/v/3.0.8

builds using the GA plugin currently fail to build

**Comment by AshleyScirra** [comment]
`cordova-plugin-gameanalytics@3.0.8` is now on the build service whitelist.
