### ISSUE TITLE
Collision Polygons disappearing in editor.

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#3775]
## Problem description

Collision Polygons on the right side of the cursor disappear after using the Draw Tile tool to erase tiles from a tilemap.

Example: https://i.imgur.com/tEvvEto.gif

## Attach a .c3p

[Collision Polygons Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4488743/Collision.Polygons.Bug.zip)

## Steps to reproduce

1. Select the Draw Tile tool and erase a few tiles.

## Observed result

Collision Polygons simply disappear.

## Expected result

Collision Polygons to stay in place.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.

**Comment by BonzerKitten7** [comment]
Thanks for the great work, Diego! Really appreciate it. 👏
