### ISSUE TITLE
Tween is not properly synced

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#3777]
## Problem description

Multiple instances of the same object using the same tween values have different results, they're not properly synced.

Example: https://i.imgur.com/FNKNBf5.gif

## Attach a .c3p

[Tween Sync Issue.zip](https://github.com/Scirra/Construct-3-bugs/files/4488828/Tween.Sync.Issue.zip)

## Steps to reproduce

1. Press the "Start" button.

## Observed result

Tween is not properly synced.

## Expected result

Tween to be perfectly synced

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed.

**Comment by BonzerKitten7** [comment]
Thanks for the amazing work, Diego. 👏
