### ISSUE TITLE
Keyboard scales content down on android export

### ISSUE THREAD

**Issue by bedfl2016** [Scirra/Construct-3-bugs#3778]
## Problem description

Hi I export my app to android with hide status bar ticked. I have a text input box and when I exported the app recently when I go to type the text on android into the input box my content on my app scales down.

What should happen is the keyboard goes over the content that's what used to happen until I update my construct.

## Steps to reproduce

1. export to android a project with the text input box
2. open your exported apk on an android mobile device and click the text input box and go to types some text in.

Another way to reproduce is download my app:

Here's a promo code for Google play:

https://www.promies.net/promotion/a488c60d-2155-41d6-afb0-714c35a410a9/

Once downloaded open the app and click on the text box and you will see the content scales down when the keyboard appears.

## Observed result

The text input box will shrink so it does not go behind the keyboard.
## Expected result

The text input box should not have moved
## More details

**Affected browsers/platforms:** 

**First affected release:** 
Latest beta

**Comment by AshleyScirra** [comment]
Unfortunately this is how Android handles the on-screen keyboard (OSK). When using letterbox scaling, Construct adjusts the view to fit the available screen area. However when the OSK appears, Android resizes the available screen area, and Construct adjusts the view accordingly, resulting in it shrinking. iOS handles this much more elegantly: the OSK does not resize the view, it just layers on top and scrolls the remaining view (without resizing it) to ensure the input field is visible.

Ideally Android would use the same approach as iOS. An issue has been filed to adjust Android to do that: https://bugs.chromium.org/p/chromium/issues/detail?id=404315
However it doesn't appear to be making much progress. I've tried hacking around the Android limitation in the past, such as by ignoring vertical window sizing, but it causes more problems than it solves and is too hard to get right. So I think really it needs to be solved by Google as part of Android.

**Comment by bedfl2016** [comment]
@AshleyScirra 

My app used to not scale down though. What can I do to fix this?

Do I change letterbox view or what ever as this affects my app crucially.
