### ISSUE TITLE
[Whitelist] Build Service plugin support request

### ISSUE THREAD

**Issue by bedfl2016** [Scirra/Construct-3-bugs#3779]
Hi. I would like to request support for a plugin:

https://www.npmjs.com/package/open-with-cordova-plugin

I finally want my addon to get supported by the C3 Build Service, so that the users, including me, won't have to always rely on PhoneGap and be able to build directly.

Thank you.

**Comment by AshleyScirra** [comment]
`open-with-cordova-plugin@1.0.3` is now on the build service whitelist.
