### ISSUE TITLE
Family edit dialog doesn't sort object in project list

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#378]
## Problem description

The 'object types in project' list is not sorted, as C2 does.

## Attach a .c3p

N/A

## Steps to reproduce

1. Add some sprites
2. Create a Family
3. View list on left side.

## Observed result

Objects are in the order they were created.

## Expected result

Sorted

## Affected browsers

N/A

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

N/A

</details>

**Comment by AshleyScirra** [comment]
Well spotted. Thanks, fixed for r32.
