### ISSUE TITLE
Keyboard Bug Issue

### ISSUE THREAD

**Issue by General-Baker** [Scirra/Construct-3-bugs#3781]
## Problem description

Game engine throws a critical error when you go click the button shown in the picture in the c3p file

## Attach a .c3p

[https://drive.google.com/open?id=1mU-apGaTMvYm4loCa6wQG1NZGh97XPZ2](url)

## Steps to reproduce

Shown in c3p file

## Observed result

Game engine throws critical error and forces exit

## Expected result

exit the popup normally

## System details

<details><summary>View details</summary>
Error report information

Type: unhandled rejection
Reason: Error: this.\u01C3Aw is null @ ǃc$h@https://editor.construct.net/r189-2/projectResources.js:1:1140653 ǃc$D/<@https://editor.construct.net/r189-2/projectResources.js:1:1140608
Stack: ǃc$h@https://editor.construct.net/r189-2/projectResources.js:1:1140653 ǃc$D/<@https://editor.construct.net/r189-2/projectResources.js:1:1140608
Construct 3 version: r189.2
URL: https://editor.construct.net/
Date: Fri Apr 17 2020 22:00:11 GMT-0500 (Central Daylight Time)
Uptime: 405.7 s
Platform information

Browser: Firefox
Browser version: 75.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
C3 release: r189.2 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release. Firefox doesn't support the `<dialog>` element so some nested dialog scenarios like this have to be handled differently.
