### ISSUE TITLE
screen orientation when device is rotated not work on IOS (saved from Safari to homepage)

### ISSUE THREAD

**Issue by COGames66** [Scirra/Construct-3-bugs#3789]
## Problem description
On iPad or iPhone when game is saved from safari to the homescreen, when device is changed (tilted/rotated) from portrait to landscape or landscape to portrait, the viewport shrinks and full screen view is lost and there's large black margins. This problem does not happen with Construct 2.

## Attach a .c3p
1drv.ms/u/s!AobC4q3rBlr6wrVB2dVq8Zr6pTm6Jw

## Steps to reproduce
1. Export project to HTML5
2. Open on iPad or iPhone
3. Tilt the device to change orientation

## Observed result
The viewport shrinks (not full screen). When tilted (or rotated) back it stays shrunk.

## Expected result
When tilted the viewport should fill the screen completely.

## More details
Note that the cp3 project is only the background as a color with the settings:
Viewport Fit: Cover
Orientations: Any
Fullscreen Mode: Scale outer

When saved and installed on Edge and Chrome it works when tilted/rotated.

**Affected browsers/platforms:** 
homescreen saved from Safari (it works on Safari)

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Urgh, it's yet another iOS viewport sizing bug that we have to work around. I think I got it working for the next release so it should be fixed there.

**Comment by COGames66** [comment]
I tested on today's release, R197, and it has the same result.

**Comment by AshleyScirra** [comment]
I did observe the issue, make a change, and then verify it was working afterwards. If you are using a HTML5 export and still have an issue, I would guess it is using a cached older version. Try clearing the cache or exporting to a different URL.

**Comment by COGames66** [comment]
I did erase the cache and changed the color of the background (from blue to turquoise) so I could see it has the latest C3 build. It worked a few times when I tilted it (so I thought it was fixed), but then it started changing the view again. And once it changed the view, it wouldn't work at all. Go to www.phonicsblaster.com to see it (built today with C3 newest version).

**Comment by AshleyScirra** [comment]
This doesn't rule out that the server or something else along the way has cached it. I would advise starting a new bug report following all the guidelines if you believe there is still a problem.

**Comment by rumesh99** [comment]
This problem is still there. Also device orientation from browser plugin doesn't work on ios devices

**Comment by AshleyScirra** [comment]
This issue was resolved over a year ago. Any new issues should be filed separately.
