### ISSUE TITLE
Crash related to idling and webfonts?

### ISSUE THREAD

**Issue by narFnarF** [Scirra/Construct-3-bugs#379]
## Problem description

Got a crash as I was trying webfonts. After trying some fonts, I left the editor and the game running to get new fonts. When I came back, Construct had crashed. It did not allowed me to save my project :(

First time I have this crash. I'm submitting this report only so that you have the crash log. Will update if it reoccurs.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Event 'error': [object ProgressEvent]
Construct 3 version: r31
URL: https://editor.construct.net/index.html
Date: Sat May 27 2017 17:17:43 GMT-0400 (Est (heure d’été))
Uptime: 23405.5 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 745 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Sorry, the crash report is not useful in this case, so without steps to reproduce there is nothing we can do.

**Comment by narFnarF** [comment]
@AshleyScirra In the future, is there something I can do to turn these no-repro crashes into something useful for you? Is there any other logs I could grab? Do you even want me to continue submitting crash logs when I don't have clear repro steps?

**Comment by AshleyScirra** [comment]
The repro steps are probably the single most important part - fixing a bug can involve following those steps a dozen times or so to figure it out, and not having them makes it semi-impossible to do anything. Sometimes the crash reports are helpful, but sometimes not. I'd only file an issue if you have repro steps.

**Comment by narFnarF** [comment]
Ok! Got it!
How do you handle the "random crashes" though? I get the feeling that the random crashes I got so far involve using Construct for extended period of time, or coming back to Construct after doing something else for a while (ex: browsing facebook or computer went asleep). It will be hard coming with repro-steps for that kind of stuff. You kinda need a dedicated QA tester for that. 

Any suggestions? I really want to help :)

**Comment by AshleyScirra** [comment]
The way to handle "random" crashes is to find what reliably reproduces them! Sometimes that's hard.
