### ISSUE TITLE
Whitelist Request [InAppPurchase] patch plugin

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#3790]
Hi,

Would you please whitelist the `cordova-plugin-inapppurchase-new@1.4.2`. This is a fork from an existing white-listed plugin `cordova-plugin-inapppurchase-fixed@1.1.2`.
I just changed some files to allow chaining the `getProducts()` request to lift the 30+ SKU limit.

Thanks.

**Comment by AshleyScirra** [comment]
`cordova-plugin-inapppurchase-new@1.4.2` is now on the build service whitelist.
