### ISSUE TITLE
Error when attempting to play audio

### ISSUE THREAD

**Issue by dana-and-monsters** [Scirra/Construct-3-bugs#3791]
![image](https://user-images.githubusercontent.com/30321989/79746958-24975d80-830b-11ea-8a33-5892d2b53c82.png)

[virtualInsanity.zip](https://github.com/Scirra/Construct-3-bugs/files/4503126/virtualInsanity.zip)

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to investigate reports unless you follow the guidelines.
