### ISSUE TITLE
Light radius bug

### ISSUE THREAD

**Issue by Bigbeto123** [Scirra/Construct-3-bugs#3792]
Light radius looks quite whenever you pin the shadowlight object to a movable object. EVEN with the light radius set below than a 100 (eg.: 70)

## Attach a .c3p

[bugrep.zip](https://github.com/Scirra/Construct-3-bugs/files/4503127/bugrep.zip)

## Steps to reproduce

1. create shadowlight w/ pin behavior
1. pin it to any movable object
3.create anything w/ shadow caster behavior and move the obj around it

the 'smooth' shadow looks as pixelated and sharp instead of smooth

it should not look like so

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.163
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
C3 release: r195 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 86 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Bigbeto123** [comment]
Had to repost this because someone got heated about my harsh criticism (which is self admittedly so).
The bug happens even with a radius below 100 and with the shadowlight object far away from the caster.
Btw, I did not in a single moment did any kind of personal attack, so I'd advise you to take care as well with these precocious thread lockups. Since I believe censorship also goes against Github's guidelines.

**Comment by AshleyScirra** [comment]
We have the right to do our jobs without dealing with an abusive attitude. Despite multiple warnings this user has repeatedly broken our [Forum & Community guidelines](https://www.construct.net/en/forum/general/open-topic-33/forum-community-guidelines-141035) so they are now banned. I have also invested quite some time in a good-faith effort to explain the various difficulties and design trade-offs involved in Construct, but to no avail. We do not investigate bug reports that do not follow the Forum & Community guidelines, so this issue will not be investigated. If anyone else wishes it to be investigated, they may file a new issue complying with our Forum & Community guidelines, which I'd add the vast majority of our users do.
