### ISSUE TITLE
Light radius issue

### ISSUE THREAD

**Issue by theprocrastinator-dev** [Scirra/Construct-3-bugs#3793]
## Attach a .c3p

Light radius looks quite whenever you pin the shadowlight object to a movable object. EVEN with the light radius set below than a 100 (eg.: 70)

1.create shadowlight w/ pin behavior
2.pin it to any movable object
3.create anything w/ shadow caster behavior and move the obj around it

the 'smooth' shadow looks as pixelated and sharp instead of smooth

it should not look like so

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.163
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
C3 release: r195 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 86 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by theprocrastinator-dev** [comment]
> Using racist, sexist, homophobic or hateful language.
> Threats of violence or other personal attacks.
> Posting spam or otherwise promoting off-topic deals/offers. Note we routinely ban spammers that sign up new accounts and mention commercial products or services. New users should avoid this in order to avoid falling in to the spam filter.
> Promoting illegal activities, including piracy.
> Linking to or distributing malicious software.
> Linking to scams or otherwise suspicious projects or organisations.
> Posting with an alternative account while banned or otherwise attempting to circumvent a ban/moderator’s decision.
> Posting any other user’s real-life information (aka doxxing), or otherwise displaying confidential information that is not intended to be public.

As a side note, I'd like you to point out where was the previous user who reported this bug's behavior in here; exactly (that caused the ban). Quoted directly from the official guideline.
No curse words, no homophobic slurs, no personal attacks, no spam, no illegal activies, and son on. I'm really curious about that.

**Comment by AshleyScirra** [comment]
Please refer to the [Forum & Community guidelines](https://www.construct.net/en/forum/general/open-topic-33/forum-community-guidelines-141035), which cover many things other than the things you quoted. Also see another guideline:

> ...excessive discussion and questioning of the rules themselves, raising suspicion that you are looking for loopholes or testing the limits, or otherwise attempting to circumvent our rules.

I believe this is what is happening here, so closing. I will only investigate issues that fully comply with the Forum & Community guidelines. This is a clear and perfectly reasonable requirement that the vast majority of our users have no problem with.
