### ISSUE TITLE
Cannot change position of objects that use the Orbit behavior

### ISSUE THREAD

**Issue by gg3l** [Scirra/Construct-3-bugs#3798]
## Problem description
If an objects is using the Orbit behavior and is enabled, it's position cannot be changed. Furthermore, if the behavior is disabled and it's position is changed, it will snap back to it's original position once the behavior is re-enabled.

## Attach a .c3p
[orbit_behavior_issue.zip](https://github.com/Scirra/Construct-3-bugs/files/4514496/orbit_behavior_issue.zip)

## Steps to reproduce

1. Create an object (Sprite for example) and add the Orbit behavior to it
2. Attempt to change the position of said object (Set position X,Y)
3. Observe that the position is not being changed
4. Set the Orbit behavior to Disabled
5. Repeat step 2
6. Observe that Set position is working as intended
7. Re-enable the Orbit behavior
8. Observe that the object has snapped back to it's original position (where it was first created)

## Observed result
An object that is using the Orbit behavior, while enabled, cannot have it's position changed and/or will always return to it's original position.

## Expected result
An object that is using the Orbit behavior, while enabled, should be repositionable.

## More details

**Affected browsers/platforms:** Tested on Brave/Firefox/Chrome

**First affected release:** Tested on r189.2 stable 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is by design. The position the Orbit behavior moves around is different to the object position. You set the position it orbits around with the 'Set target' action in the behavior.
