### ISSUE TITLE
Pallette in editor sets wrong color when setting from secondary color

### ISSUE THREAD

**Issue by sirsnowy7** [Scirra/Construct-3-bugs#3799]
## Problem description

When setting colors in the animation editor, choosing "set from secondary color" will not set the color to the same color as the secondary color selected.

## Attach a .c3p

https://drive.google.com/open?id=10S5YQtSAoL1FlZURwfXenDM-RiezPJ1g

## Steps to reproduce

1. Pick a color and set it in the secondary color slot in the animation editor
2. Right click on a slot in the pallette editor and choose "set as secondary color"
3. It will not be the same as the color selected by the user. To prove this, switch your secondary and primary colors, then set the slot you used to the color which is, now, the primary color, and the displayed color will change.

## Observed result

The color shown in the pallette is not the color selected by the user.

## Expected result

The color should be the color set by the user, whether it is set by primary or secondary color.

## More details

**Affected browsers/platforms:** 

I could only test the issue in Chrome.

**First affected release:** 

I don't know the first affected release

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 81.0.4044.103
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Chrome OS
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.0499999523162842
Logical CPU cores: 2
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 12871.76.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.103 Safari/537.36
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 6.1 gb
Storage usage (approx): 42 mb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 400 (BSW)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Can you provide some more information?

What is the difference in the colors? Are you using alpha? Are you using the luminosity slider?

I can't see that test project, don't have permission to download from your google drive.

I can see that there is a minute difference in colors when you switch between the primary and secondary colors, probably some color conversion rounding error. But I don't know if that is the error that you are seeing.

**Comment by DiegoScirra** [comment]
Should be fixed in the next beta.
