### ISSUE TITLE
ESC After Object Creation Bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#38]
## Problem description

Hitting the ESC key just after trying to place the newly created object will cause Construct to still be partially in "placing object" mode. Even after clicking away, the cursor is still stuck at this mode and will refuse to select any object with a click in the layout view.

## Steps to reproduce

1. Create an object that can be placed with a coordinate on the layout view.
2. Create another object just like the first step but press "ESC" when placing the object.

## Observed result
Cursor is still at moving mode near the edge as though you are trying to place the object. After you clicked anywhere else, you **cannot** selecting anything by clicking on objects in the layout view now. Highlight selecting still works.

If you try creating another object, the cursor that looks like a "+" sign isn't shown. After you created a new object, it fixes itself.

## Expected result

After hitting that ESC key when trying to place the created object, perhaps resetting the cursor or return to the state before the creation of the object, but keep the created object in the project.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 2.4 gb
Storage usage (approx): 72 mb (2.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by jaydonteh** [comment]
Additional info:

Also affects when cloning an object, but canceled with ESC key.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r17.
