### ISSUE TITLE
Crash when setting tilemap to cover layout

### ISSUE THREAD

**Issue by calminthenight** [Scirra/Construct-3-bugs#3800]
## Problem description

Encountered a crash when selecting the cover layout option for a tilemap object.

[https://1drv.ms/u/s!AkmrWgxeuxlKg_txR7U16RaAi6uFdg?e=u7Nxb7]  Project file

## Steps to reproduce

1. Click on tilemap object on floor layout (anywhere in editor)
2. Right-click and select align->cover layout

## Observed result

![image](https://user-images.githubusercontent.com/64178259/80050600-71707380-8559-11ea-9753-61a06e499396.png)

## Expected result

Set tilemap to cover layout

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Crash report: "Error report information
Type: unhandled exception
File: https://editor.construct.net/r189-2/projectResources.js, line 1, col 203836
Message: Uncaught Error: object not rotatable
Stack: Error: object not rotatable at m.ǃVy (https://editor.construct.net/r189-2/projectResources.js:1:203842) at window.ǃEH.ǃGZ (https://editor.construct.net/r189-2/components/editors/layoutView/layoutView.js:1:35613) at https://editor.construct.net/r189-2/components/editors/layoutView/layoutView.js:1:16102
Construct 3 version: r189.2
URL: https://editor.construct.net/
Date: Thu Apr 23 2020 11:43:15 GMT+1000 (Australian Eastern Standard Time)
Uptime: 2902.8 s

Platform information
Browser: Chrome
Browser version: 81.0.4044.113
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
C3 release: r189.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2"

</details>

**Comment by AshleyScirra** [comment]
Thanks, good catch, was a simple oversight. Fixed for next release.
