### ISSUE TITLE
UWP Multiplayer doesn't work

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#3801]
## Problem description

I am unable to use the Scirra Multiplayer Plugin with a project on a UWP project. As a simple test I create a short program that will connect to the signalling server, then change the text to "Connected" when it's successfully connected. This works with the HTML5 export, as well as the NW.js export. However, as soon as I try to export it for Windows or Xbox, then test it within Visual Studio, it never connects.

This is an issue on both Construct 2 and 3 exports.

[c3p_Project.zip](https://github.com/Scirra/Construct-3-bugs/files/4523319/c3p_Project.zip)

## Steps to reproduce

I have included both the c3p as well as an exported project in case it helps. If you want to simply use the cp3 project, then all you need to do is open it, press test to see that it connects, then export a UWP and try running it again within Visual Studio.

The Windows 10 SDK version number I am using to export is 10.0.17763.0

## Observed result

Within Visual Studio, it will never connect to the signalling server, and will simply sit there showing the text "Connecting".

## Expected result

It should connect to the signalling server, and therefore show the word "Connected".

## More details

It works fine on all browsers, but will not work on either Visual Studio (2017 in my case) nor the Xbox One.

As mentioned, it doesn't even work in Construct 2, which my actual project was built in. I've simply built this example in Construct 3. Until Construct 3 includes circular cap on the Drawing Canvas, rather than butt or square, I can't move the project over. It's entirely possible that multiplayer has never worked on Construct 2 or 3 for UWP, and simply nobody has ever tried to build a multiplayer project before.

## System details

Platform information
Browser: Chrome
Browser version: 81.0.4044.122
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
C3 release: r196.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 117 gb
Storage usage (approx): 277 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
UWP uses the (legacy) Microsoft Edge browser engine, which does not support WebRTC DataChannels, which is what the Multiplayer plugin uses. Therefore multiplayer isn't (and has never been) supported in UWP. You should check the 'Is supported' condition of the Multiplayer object as all the built-in multiplayer examples do; if that is not true it will not work.

The new Chromium-based Edge supports WebRTC as it inherits it from the Chromium engine used by Google Chrome. However it's not yet clear when or how this support will come to UWP.
