### ISSUE TITLE
SocialSharingPlugin breaks Android Signed Release APK build

### ISSUE THREAD

**Issue by Bootfit** [Scirra/Construct-3-bugs#3804]
## Problem description

Building an Android Signed Release APK breaks when the project has the SocialSharingPlugin object included.

## Steps to reproduce

1. Try building an Android Signed Release APK with the SocialSharingPlugin as part of the project.
2. Build will fail
3. Delete SocialSharingPlugin and rebuild. Project will now build.

## Observed result

Project doesn't build but displays error log.

## Expected result

Project should build and allow download once complete.

## More details

Not used C3 for about a year. The project always built fine in the past and was able to deploy to app stores. Project no longer builds though.

**Affected browsers/platforms:** 

**First affected release:**  Project was last worked on 14/06/19 - it built an deployed fine then.
[Jack Jumps.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4536267/Jack.Jumps.c3p.zip)

## System details

<details><summary>View details</summary>

Error: Discovered platform "android@8.1.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@8.1.0
Adding android project...
Creating Cordova project for the Android platform:
Path: ~~/android
Package: net.bootfit.jackjumps
Name: Jack_Jumps
Activity: MainActivity
Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.1.0
Plugin 'cordova-plugin-inappbrowser' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-x-socialsharing' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-androidx-socialsharing' found in config.xml... Migrating it to package.json
Plugin 'construct-mobile-rate' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-fullscreen' found in config.xml... Migrating it to package.json
Plugin 'construct-mobile-notchfix' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-inappbrowser". Adding it to the project
Installing "cordova-plugin-inappbrowser" for android
Discovered saved plugin "cordova-plugin-x-socialsharing". Adding it to the project
Installing "cordova-plugin-x-socialsharing" for android
Installing "es6-promise-plugin" for android
Subproject Path: CordovaLib
Subproject Path: app
Discovered saved plugin "cordova-plugin-androidx-socialsharing". Adding it to the project
Installing "cordova-plugin-androidx-socialsharing" for android
Plugin dependency "es6-promise-plugin@4.2.2" already fetched, using that version.
Dependent plugin "es6-promise-plugin" already installed on android.
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-androidx-socialsharing': CordovaError: Uh oh!
"~~/SocialSharing.java" already exists!
at copyNewFile (~~/pluginHandlers.js:234:45)
at install (~~/pluginHandlers.js:34:17)
at ActionStack.process (~~/ActionStack.js:56:25)
at PluginManager.doOperation (~~/PluginManager.js:114:20)
at PluginManager.addPlugin (~~/PluginManager.js:144:17)
at ~~/Api.js:210:74
at _fulfilled (~~/q.js:854:54)
at ~~/q.js:883:30
at Promise.promise.promiseDispatch (~~/q.js:816:13)
at ~~/q.js:877:14
Failed to restore plugin "cordova-plugin-androidx-socialsharing" from config.xml. You might need to try adding it again. Error: Uh oh!
"~~/SocialSharing.java" already exists!
Discovered saved plugin "construct-mobile-rate". Adding it to the project
Installing "construct-mobile-rate" for android
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for android

This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Discovered saved plugin "cordova-plugin-fullscreen". Adding it to the project
Installing "cordova-plugin-fullscreen" for android
Discovered saved plugin "construct-mobile-notchfix". Adding it to the project
Installing "construct-mobile-notchfix" for android

</details>

**Comment by AshleyScirra** [comment]
I think that was a temporary plugin released a couple of years ago that become redundant after the official built-in Share plugin was introduced. Since it's been unsupported for a long time we won't be fixing any issues with it. Please switch to the built-in Share plugin.
