### ISSUE TITLE
Dictionary "Compare Value"

### ISSUE THREAD

**Issue by theprocrastinator-dev** [Scirra/Construct-3-bugs#3805]
As demonstrated in the file uploaded, there's 2 conditions (first: if key = 0; second: if key != 0). None of them trigger; even thought its intial value is 0. Even if you click the mouse's left button (which sets it to "LongBarrel") the other condition will not trigger as well.

[bugreport.zip](https://github.com/Scirra/Construct-3-bugs/files/4536415/bugreport.zip)

1.Create a dictionary key with any value
2.Later, check whether its equal to any value OR not equal to it
3.None of those conditions will trigger

Conditions will not trigger, despite it not making logical sense.

One of them should trigger .

## More details

**Affected browsers/platforms:** 

**First affected release:** 
r196.2
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 81.0.4044.122
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
C3 release: r196.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 169 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by theprocrastinator-dev** [comment]
Don't know if it's STRICTLY related to the dictionary object; but that's what caused me trouble so far

**Comment by AshleyScirra** [comment]
It's working correctly. For some reason there's a "Wait 10 seconds" action in there, so it won't check the sub-events until 10 seconds have elapsed. If you wait 10 seconds, the sprite moves 100 pixels, indicating the event was indeed true.

**Comment by theprocrastinator-dev** [comment]
My bad, it was a stupid mistake of mine.
The actual "bug" (don't know if I can call it so), is that:
Whenever you assign a dictionary key (initial value = 0; final value = string) to a string; and then check whether it's equal or not equal to 0, none of those conditions would fire. Find a workaround by setting the key's initial value to "empty" instead of 0, and then checking whether it's equal or not equal to "empty".
Never used dictionaries in an actual programming language before (only used to mess around with lists), so don't know if it's supposed to happen like that or a construct issue.
