### ISSUE TITLE
Set Focused for TextInput not working as intended on iOS

### ISSUE THREAD

**Issue by badmiracle** [Scirra/Construct-3-bugs#3807]
## Problem description

TextInput Object "Set Focused" action does not work as intended on iOS

## Attach a .c3p

[focustextinput_ios.zip](https://github.com/Scirra/Construct-3-bugs/files/4540100/focustextinput_ios.zip)

## Steps to reproduce

1. Add a TextInput object
2. Add a button or key press with an action that sets the TextInput object to focused

## Observed result

The textinput box will be highligted but the iOS keyboard does not appear on screen. To get the keyboard to appear you must click inside the TextInput area. The "Set focused" action does not automatically prompt the keyboard to appear on iOS.

## Expected result

Setting the focus with an action should open up the keyboard on the iOS device automatically.

## More details

Fixing set focus to open the keyboard automatically would make for a better user experience with our apps.

iOS - Safari

196.2 beta

## System details

<details><summary>View details</summary>

No crash

</details>

**Comment by AshleyScirra** [comment]
Hmm, iOS seems really fussy about how focusing is handled. I adjusted the timing of the call and it seems to have fixed it, so it should be working in the next release.
