### ISSUE TITLE
Crashing in less than a minute

### ISSUE THREAD

**Issue by ReallyBasic1** [Scirra/Construct-3-bugs#3808]
## Problem description

Construct crashed in less than one minute every time i open it. I don't even have to do anything, such as open a project or edit something.

I denied looking at the tutorial if that helps at all.

## Attach a .c3p

N/A

## Steps to reproduce

Just opening on with chromebook on chrome makes it crash 

## Observed result

Crashed with error: unhandled rejection

## More details

 

Chrome (on chromebook)

worked in r189 but broke in r197

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: undefined
Construct 3 version: r197
URL: https://editor.construct.net/
Date: Mon Apr 27 2020 12:26:49 GMT-0500 (Central Daylight Time)
Uptime: 41.4 s

Platform information
Browser: Chrome
Browser version: 80.0.3987.162
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Chrome OS
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.0499999523162842
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 12739.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36
C3 release: r197 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 400 (Braswell)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by JeFawk** [comment]
This is the most useless bug report I've ever seen in my life.

**Comment by ReallyBasic1** [comment]
Thanks for making me look at this again, there was lots of stuff I apparently submitted wrong :/

**Comment by JeFawk** [comment]
> Thanks for making me look at this again, there was lots of stuff I apparently submitted wrong :/

I deleted my message cause i remembered i saw something worse a few years ago :D 

Can you open the console and see if there is any error there? Did you try to open the web app in Mozilla to see if it crashes?

**Comment by ReallyBasic1** [comment]
I am on a Chromebook. The only browser is chrome. It is also locked down so I can't see task manager or anything that would give me any more information.

**Comment by JeFawk** [comment]
> I am on a Chromebook. The only browser is chrome. It is also locked down so I can't see task manager or anything that would give me any more information.

I was talking about the browser's. In Windows if you press F12 or Ctrl+J you get a frame appearing which has a Console tab where errors can appear.

**Comment by ReallyBasic1** [comment]
Yeah, sorry I can't be of more help, but my computer is REALLY locked down. You can't even open that. :/

**Comment by AshleyScirra** [comment]
Unfortunately we're under lockdown in the UK, and all our testing devices are over in the office and largely inaccessible at the moment, which is where both our Chromebooks are!

I'm afraid the information provided so far gives us very little to work with, especially since the crash report was unable to identify a reason. Pressing F12 and seeing the browser console is the absolute bare minimum for us to be able to do anything at all about this.

I don't believe we had any similar reports across the entire beta testing period. It could be a network error and failing to load. Some loading does continue after the Start Page appears, and some types of network errors will crash it at that point. So you might just need to clear cache and try again, or try an incognito window. Pressing F12 would help identify this. Or if you manage to get it working after doing that, I'd guess it was that.

**Comment by ReallyBasic1** [comment]
It seems fixed now, not sure what I did. I opened construct 3 in a new window and it has never happened since.  I will post again if I find any more information if it happens again.

**Comment by AshleyScirra** [comment]
OK, I suspect this was a connection issue then.
