### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'then' of undefined - console error only

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#3809]
Starting with r197 I get this odd error in the console:
![image](https://user-images.githubusercontent.com/7268697/80406853-6147f380-88cd-11ea-9b2b-282526e65241.png)

In my original project it appears every few seconds throughout the whole gameplay. In the attached project it appears only once. I could not get it to appear multiple times as in my original project.

I am unsure what to think about this error as it does not seem to cause any visible problems but I'm a bit skeptic.

## Attach a .c3p

[C3 bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4541400/C3.bug.zip)

## Steps to reproduce

1. open the project using the web app (Google Chrome)
2. run it
3. open the console

## Observed result

Notice the error appearing from creating only 2 objects.

## Expected result

I'd expect no errors.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r197

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 81.0.4044.122
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
C3 release: r197 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 536 gb
Storage usage (approx): 318 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX550/550 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I opened the project and previewed it, and there were no errors in the console. So, not sure what can be done about this...

**Comment by AshleyScirra** [comment]
Oh, it looks like you have to preview the whole project, not just the first showing layout, I think that was a detail that was missed out.

I've fixed the console error for the next release, and looking at the code I don't think this will actually break anything. It's a dynamic texture load that throws the error, but it only happens for things that don't actually load any textures, so I don't think there will be any consequence to that.

**Comment by JeFawk** [comment]
Yeah I missed out on the info stating you need to preview the whole project. Thanks for the fix!

**Comment by AshleyScirra** [comment]
Had what appears to be two reports of this issue already, so leaving open marked as fixed for visibility.
