### ISSUE TITLE
Crash when opening the sprite editor

### ISSUE THREAD

**Issue by narFnarF** [Scirra/Construct-3-bugs#381]
## Problem description

I got this crash as I opened the sprite editor by double-clicking an object in the Project panel. I usually never crash doing that. It's the 1st time.

The object in question has 3 different animations. I don't know if that's what's causing the issue.

See the crash report below. I'll update if I get the issue again.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'firstChild' of null @ TypeError: Cannot read property 'firstChild' of null at ee.ǃRAm.ǃRE_ (https://editor.construct.net/r31/main.js:71:258346) at ee.ǃRAm.ǃRKe (https://editor.construct.net/r31/main.js:71:265898) at ee.ǃRAm.ǃRKm.ie [as ǃRKm] (https://editor.construct.net/r31/main.js:71:256068) at ee.ǃRAm.ǃYV (https://editor.construct.net/r31/main.js:71:258287) at ǃB.ǃo.ǃJ.ǃRNr.ǃRML (https://editor.construct.net/r31/main.js:71:70380) at Promise.resolve.then.then.then.then.then.then (https://editor.construct.net/r31/main.js:71:142963) at 
Stack: TypeError: Cannot read property 'firstChild' of null at ee.ǃRAm.ǃRE_ (https://editor.construct.net/r31/main.js:71:258346) at ee.ǃRAm.ǃRKe (https://editor.construct.net/r31/main.js:71:265898) at ee.ǃRAm.ǃRKm.ie [as ǃRKm] (https://editor.construct.net/r31/main.js:71:256068) at ee.ǃRAm.ǃYV (https://editor.construct.net/r31/main.js:71:258287) at ǃB.ǃo.ǃJ.ǃRNr.ǃRML (https://editor.construct.net/r31/main.js:71:70380) at Promise.resolve.then.then.then.then.then.then (https://editor.construct.net/r31/main.js:71:142963) at 
Construct 3 version: r31
URL: https://editor.construct.net/index.html
Date: Sat May 27 2017 22:21:55 GMT-0400 (Est (heure d’été))
Uptime: 8992.7 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 745 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r34.
