### ISSUE TITLE
Mobile GUI inputs boxes don't scale

### ISSUE THREAD

**Issue by Huwans** [Scirra/Construct-3-bugs#3813]
I've been using the mobile version of construct 3 on my phone pretty frequently. My phone has a very high resolution of 3120 x 2560. For the most part, game editing on my phone works well! Incredible! The only issue I keep running into is with the sprite editors x, y coordinates for collision polygons and image points. My first issue is that the X coordinate input is chopped off so I cannot see it. The second issue is when tapping the X or Y input bar, my phones keyboard pops up and then is too big and disappears. Overall, this is an issue with the pop up "center" windows not scaling well with a mobile interface. These issues could be fixed by making the sprite editor window have smaller input boxes that only fit 4-6 digits for an X or Y coordinate, instead of boxes that stretch across the whole width of the screen. The very long input boxes create a horizontal scroll bar just to view a few 3 digit numbers that would otherwise fit easily on the screen. The good news is, this seems like it could be fixed with a simple CSS change to construct 3's mobile editor code and some phone based GUI testing. Thanks, -Huwans

**Comment by AshleyScirra** [comment]
I'm afraid it's generally impossible to investigate reports like this. Please see the bug report guidelines, they're there so we can actually help.
