### ISSUE TITLE
OR operator issue 197 - Logic goes on but loses Picked context but not exactly.

### ISSUE THREAD

**Issue by aiaicaptain** [Scirra/Construct-3-bugs#3815]
I was told a bug was fixed with the OR operator in 193, sometimes passing even if conditions were not true. This here is not the case. The project is huge and messy, so I will try to convey the gist of it with screenshots, numbered and linked below. So I will explain shot by shot.

Demo1.png

1.(YELLOW) The yellow box shows 3 OR conditions, for test purposes I have made sure that the first one is 100% true, it is a local var InGoldyLocks. 

2.(RED) A sub event of the OR block, this event fires a DEBUG function that prints the value of the InGoldyLocks var so I'm 10000% certain the value is true. Probably becoming obvious, that a serious issue is already visible. If the OR block conditions arn't met, how come I'm firing a sub event? This is where it gets stange. As you can see, in the DEBUG function I also print the UID of the World_Objects family object I have in context, outside of this pic I've made sure that a specific sprite's UID is set to the DEBUG var, so this fires only when the specific sprite is worked through this logic. The log prints both "1" for the InGoldyLocks var and the correct World_Objects.UID, so I know i have the correct context of the above events. however - moving on to the third(blue) box.

3. (BLUE) Here I change several vars of the World_Object I hold in context (the one which's UID I print in the below function), however, nothing happens. I can even place a Destroy action of Wolrd_Objects and the object will not get destroyed. NOTHING concerning the World_Objects object happens. Except that the DEBUG print function prints its UID in the log - from the RED box.

Demo2.png

In the second pic, I have disabled the other OR conditions. I have left just the InGoldylocks=1 one on and the logic progresses without issue. All changes to the World_Object object are done and visible. The issue is resolved.

Demo3.png

The third pic I have returned the OR conditions, and again the logic will not progress ONLY concerning the World_Objects object in question. To bring the point home, i have added in the blue box a Destroy action for all Destructable family objects. The World_Object I hold in context (and print its UID in the first pic) also is a member of this family. The logic is satisfied and all Destructable family objects, including the World_Object one I can't change anything for, are destroyed.

This is also true for the below OR condition visible in the pics, but I won't go on there...it's the same

LogShot.png

Shot of the log that prints the InGoldyLocks value and World_Objects.UID so I know these are OK.

RECAP:

Having the OR conditions Enabled somehow allows for the logic to progress to the subevents, but doesn't execute changes to the World_Objects object I have picked and hold in context from above conditions - these are subevents. Everything i wish to do Prior this OR condition block works fine for the World_Objects. Disableling the OR conditions it works fine. It is not correct to say I lose the context of the World_Object, as these actions should affect all World_Objects, but none are.

I am back to using version 189.2 for now and really wan't to use the good stuff from version 197.

Cheers

![Demo1](https://user-images.githubusercontent.com/43926483/80600239-c538fc00-8a34-11ea-8ad9-03327955fdf0.png)

![Demo2](https://user-images.githubusercontent.com/43926483/80600252-c9fdb000-8a34-11ea-9a9b-61b8bde458a9.png)

![Demo3](https://user-images.githubusercontent.com/43926483/80600268-d08c2780-8a34-11ea-876d-1341fdbc52af.png)

![LogShot](https://user-images.githubusercontent.com/43926483/80600277-d41fae80-8a34-11ea-9af0-3c277c55ab5c.png)

**Comment by AshleyScirra** [comment]
I'm afraid it's simply not possible to investigate this report. Please follow the bug report guidelines: we need all that information to actually be able to do something about your report.

**Comment by aiaicaptain** [comment]
Can I attach a project without it being public here?

**Comment by aiaicaptain** [comment]
Just for you guys?

**Comment by AshleyScirra** [comment]
Please read the bug report guidelines - in general we do not accept that nor is it actually useful towards solving the problem. We need a minimal project, because large projects are almost impossible to debug.
