### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by LouBagel** [Scirra/Construct-3-bugs#3818]
Relaying bug info for your benefit - no response needed for me (assuming issue doesn't repeat - will comment if so)

Error report information
Type: unhandled exception
File: https://editor.construct.net/r197-2/main.js, line 2, col 94465
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Function.ǃt.ǃj (https://editor.construct.net/r197-2/main.js:2:94471) at Function.ǃt.ǃSb (https://editor.construct.net/r197-2/main.js:2:94540) at t.ǃwYh (https://editor.construct.net/r197-2/projectResources.js:1:49519) at ǃwYh.next () at O.ǃOWP (https://editor.construct.net/r197-2/main.js:2:258631) at https://editor.construct.net/r197-2/main.js:2:264250 at d (https://editor.construct.net/r197-2/3rdparty/codemirror/codemirror.js:1:259226) at o (https://editor.construct.net/r197-2/3rdparty/codemirror/codemirror.js:1:262915) at r (https://editor.construct.net/r197-2/3rdparty/codemirror/codemirror.js:1:262984) at d (https://editor.construct.net/r197-2/3rdparty/codemirror/codemirror.js:1:259206)
Construct 3 version: r197.2
URL: https://editor.construct.net/
Date: Thu Apr 30 2020 15:04:37 GMT-0500 (Central Daylight Time)
Uptime: 14850.2 s

Platform information
Browser: Chrome
Browser version: 81.0.4044.129
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 965M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

**Comment by AshleyScirra** [comment]
I'm afraid there is nothing we can do about reports like this. The bug report guidelines are there because we need that information to help you.

**Comment by LouBagel** [comment]
I understand.  Though I know not having that info would not allow you to look into this specific issue I thought that passing along crash data would be help in some fashion - unless that info is already recorded.

I don't see it logical to attach the project for a commercially release game to a public GitHub ticket. I believe you need the project to look into the issue.

I will tell you it was when typing localVars.da... in a script area nested under a Construct function.

**Comment by AshleyScirra** [comment]
Crash reports like this are automatically logged so they do not need to be manually reported. We already fix issues if we are lucky and can figure it out from that alone. But most of the time we need a full bug report to do anything.
