### ISSUE TITLE
Construct 3 Runtime Problem

### ISSUE THREAD

**Issue by karimlahbach** [Scirra/Construct-3-bugs#3819]
[Screen effect.zip](https://github.com/Scirra/Construct-3-bugs/files/4565569/Screen.effect.zip)

## Steps to reproduce

1. Create a sprite
2. Apply effect (screen for Example)
3. Try to use Not mirrored

## i use Google chrome windows 10 

**Affected browsers/platforms: Chrome** 

**First affected release:r197.5** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next release.
