### ISSUE TITLE
Sprite or 9Patch expands from wrong origin point based on if physics is on/off

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#3821]
## Problem description

[bugagain.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4567213/bugagain.c3p.zip)

## Steps to reproduce

1. Press Space to enlarge width * 2
2. It enlarges on both sides even though its left origin
3. Press Shift to turn off physics 
4. Press space again to enlarge * 2. Enlarges properly as if left origin is the origin

## Observed result

Physics behaviour causes the origin of a sprite or 9 patch to go into middle and not where its set

## Expected result

When I set an origin it follows it as the origin it doesn't suddenly overwrite their own origin

## More details

**Affected browsers/platforms:** 

Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 81.0.4044.129
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_0
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.7999999523162842
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 844 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 615
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Better late than never - should be fixed in the next beta.

**Comment by AshleyScirra** [comment]
Reopening as this turned out to be far more complicated than originally anticipated and it won't make this release cycle. I'll have another go in the next release cycle. Refer to issues #6138, #6160, #6161 and #6170 as test cases.

**Comment by AshleyScirra** [comment]
I've had another go at fixing this and it looks like it works for this issue and all follow-up issues, but the fix will be held back until the next release cycle to maximise the testing period for it (first beta release after the next stable release).
