### ISSUE TITLE
localVars. inside a Function crashes the Construct 3 Editor since r192.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#3822]
## Problem description

The `localVars.` reference inside a Function crashes the **Construct 3 Editor** since `r192`.

## Attach a .c3p

[localVars Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4567558/localVars.Bug.zip)

## Steps to reproduce

1. Kindly continue the line `localVars. to write `localVars.Output`.

## Observed result

The **Construct 3 Editor** will crash.

## More information

**First affected release:** Works on `r191`, breaks on `r192` onwards.

**Thank you.**

**Comment by Chadori** [comment]
It seems we are currently blocked from our project, because of new conflicting Construct 3 features preventing us to revert, like the `Pin to object`.
Unfortunately we cannot practically revert back to old versions after the stable update.

**Comment by Chadori** [comment]
Fortunately, I have found a workaround, by placing an `=` after `localVars.VariableName`. It seems I can proceed.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next beta.
