### ISSUE TITLE
Layer Scale Bug

### ISSUE THREAD

**Issue by Sanchopi** [Scirra/Construct-3-bugs#3823]
[

## Problem description

Layer scale action scales all layers instead of just one specified in the name line.

## Attach a .c3p

https://drive.google.com/open?id=16hkqf14GfgbBdzf8tYsmyhs-JvGvED6A

## Steps to reproduce

Just open the attached project an run it ...

## Observed result

All layer will be scaled down by 0.5

## Expected result

Only the layer "Layer_Player" should be scaled down by 0.5

## More details

Tested only in the downloaded desktop app of construct (win7)

## System details

Platform information
Browser: NW.js
Browser version: 0.33.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@8920e690dd011895672947112477d10d5c8afb09) NWjs/0.33.3 (like Chrome/69.0.3497.100)
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 11 gb
Storage usage (approx): 360 mb (3.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

[layer_scale_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4570236/layer_scale_bug.zip)

**Comment by AshleyScirra** [comment]
You have a small layout with bounded scrolling, and you scale a layer such that the view would have to include an area outside the layout, which is not allowed by the bounded scrolling setting. This causes an unintended view (since the engine is trying to comply with bounded scrolling). Tick 'Unbounded scrolling' in layout properties and it works as you expect.
