### ISSUE TITLE
Global object tween bug

### ISSUE THREAD

**Issue by theprocrastinator-dev** [Scirra/Construct-3-bugs#3824]
Global objects currently do not maintain their tween state while transitioning to another layout (even if the tween is called by a global event sheet; already tested it in my current project in every way possible, besides the demonstration file's way).

## Attach a .c3p
[bugrep.zip](https://github.com/Scirra/Construct-3-bugs/files/4572743/bugrep.zip)

## Steps to reproduce

1.Create a global object
2.tween any property of it
3.change the layout in the mid of its tween duration

it will reset, despite being a **global** object 

the tween state should be transferred, since the behavior is inside a global object, and therefore it should be global as well - just like any of the object properties, like opacity, for example.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 81.0.4044.129
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 332 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by theprocrastinator-dev** [comment]
Just one more thing as well: If you put that object in a global layer (in front of all other layers), for some reason, it will appear below them whenever you "interrupt" its tween.

**Comment by DiegoScirra** [comment]
The first issue is solved. Bear in mind that when changing layouts, all active tweens are discarded. Global instances will remain in their current state, but any tweens that were playing before changing layout are no longer available.

This means you can't resume them, only start new ones.

@theprocrastinator-dev Please make a different report for your follow up post. It's a lot easier to manage bugs that way. Thank you.

**Comment by theprocrastinator-dev** [comment]
> The first issue is solved. 
Does that means that global objects will now keep their opacity from their tweens? (not that the tweens will not be discarded, but the opacity from the global objects changed via tween 'till the interruption).

> Global instances will remain in their current state, but any tweens that were playing before changing layout are no longer available.
> 
> This means you can't resume them, only start new ones.

Oh alright. Just a question tho: Would that be viable for a future implementation? For the tween to be resumed/paused throughout multiple layouts when inside of a global object?
In either way I have a workaround in mind - just need to know about the first question for planning out for the next update.

> @theprocrastinator-dev Please make a different report for your follow up post. It's a lot easier to manage bugs that way. Thank you.
My bad. Turns out it was an issue of mine (I guess?). Since I've put a global object inside of a global layer, and I suppose this causes weird interactions. Made the layer local and now put an event block to re-place the object inside of the layer for each layout changed, and now it works fine.
