### ISSUE TITLE
Construct 3 crashes when console is open

### ISSUE THREAD

**Issue by GeometriXza** [Scirra/Construct-3-bugs#3825]
## Problem description

On the desktop version of Construct 3, using the F12 console in preview causes Construct 3 to crash.

## Attach a .c3p

Use a blank project.

## Steps to reproduce

1. Create a new project or open an existing one.
2. Preview the project using F4 or F5 with or without holding Shift/Ctrl.
3. Open the console window using F12.
4. Close the preview without first closing the console window.

## Observed result

Construct 3 will instantly close.

## Expected result

The preview window will close as per normal, likely with the console window closing as well.

## More details
Nothing much else to it.

**Affected browsers/platforms:**

Windows

**First affected release:**

Not sure, but this isn't a new issue.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 10 gb
Storage usage (approx): 468 mb (4.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I assume this is an NW.js bug, but the NW.js version you are using (0.37.0) is out of date. Presumably this is a problem that was already fixed in a subsequent update. Update your version of NW.js, and in future please only report issues that occur with an up-to-date version to avoid reporting issues that were already fixed.
