### ISSUE TITLE
Timeline Crash

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#3826]
Crash in timeline

## Problem description

Crash in timeline when timeline past itself

## Attach a .c3p

https://drive.google.com/file/d/1TCfYs1DKYDz7JVMZln1ECkpeInKOyusD/view?usp=sharing

## Steps to reproduce

1. Edit "timeline 2"
2. Left click to "timeline 1" in "timeline 2" 's editor
3. "Timeline" option
4. "add timelines"
5. Select "timeline 2"
6. CRASH

## Observed result

Not crash

## Expected result

crash

## More details

**Affected browsers/platforms:** Chrome  81.0.4044.129 (Offical build)

**First affected release:** r198

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Maximum call stack size exceeded @ RangeError: Maximum call stack size exceeded at a.ǃBEm (https://editor.construct.net/r198/projectResources.js:1:460465) at ǃBEm.next () at a.ǃIp (https://editor.construct.net/r198/projectResources.js:1:460976) at ǃIp.next () at a.ǃBo_ (https://editor.construct.net/r198/projectResources.js:1:461232) at ǃBo_.next () at a.ǃBo_ (https://editor.construct.net/r198/projectResources.js:1:461246) at ǃBo_.next () at a.ǃBo_ (https://editor.construct.net/r198/projectResources.js:1:461246) at ǃBo_.next ()
Stack: RangeError: Maximum call stack size exceeded at a.ǃBEm (https://editor.construct.net/r198/projectResources.js:1:460465) at ǃBEm.next () at a.ǃIp (https://editor.construct.net/r198/projectResources.js:1:460976) at ǃIp.next () at a.ǃBo_ (https://editor.construct.net/r198/projectResources.js:1:461232) at ǃBo_.next () at a.ǃBo_ (https://editor.construct.net/r198/projectResources.js:1:461246) at ǃBo_.next () at a.ǃBo_ (https://editor.construct.net/r198/projectResources.js:1:461246) at ǃBo_.next ()
Construct 3 version: r198
URL: https://editor.construct.net/r198/
Date: Mon May 04 2020 17:03:12 GMT+0200 (közép-európai nyári idő)
Uptime: 159.3 s

Platform information
Browser: Chrome
Browser version: 81.0.4044.129
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
C3 release: r198 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 640M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.
