### ISSUE TITLE
Timeline Breaks When Resuming After R198 Update

### ISSUE THREAD

**Issue by hammanneric6** [Scirra/Construct-3-bugs#3828]
## Problem description

I got the R198 beta automatically today and didn't think much of it.  I had pre-existing timelines in this game.  When one tries to play the timeline will run fine until it pauses and then resumes.  On resume my particular game goes to a black screen.  I believe the black screen is due to how layers are set up in my game.  Checking the debugger I watched all the viewport values go to NaN if that helps.

On the example capx below this doesn't happen.  The change seems to be that the sprite disappears and its X and Y values go NaN instead.  Not sure what to make of that.  I'm guessing its all part of the same issue but maybe not.

## Attach a .c3p

https://drive.google.com/open?id=147c_LF1Avarc-kCVJvgQEecs0JhmBVrI

## Steps to reproduce

More like notes than steps but,

-The timeline runs on startup after 0.5 seconds.
-There are only 3 points in the timeline.
-Once the first point is reached the timeline pauses via a keyframe
-Press any key to resume the timeline, this is when the sprite is disappearing

## Observed result

The sprite disappears and the timeline never finishes, I assume, hard to tell when the sprite disappears.

## Expected result

The timeline should have resumed and finished.

## More details

I don't really have any.  My particular game is using a far more complex timeline than the one in the example but I'm assuming the base problem is linked to pausing and resuming.

**Affected browsers/platforms:** 

All testing done on Windows 10 (64 bit) (Version 1903)
NWjs - bug occurs
Chrome - bug occurs
Sorry I literally don't have any other browsers on my computer.

**First affected release:** 

My Construct 3 is set to automatically update.  I don't honestly know what came before R198 but that's what I was on.  I also opt into betas.  The issue started to occur on R198, whatever version was right before that worked fine.

## System details

Platform information
Browser: Chrome
Browser version: 81.0.4044.129
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
C3 release: r198 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 2.6 gb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
