### ISSUE TITLE
Image Editor Fill Tool Crash r198

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3829]
## Problem description

C3 crashes if you use fill tool in img editor.

## Steps to reproduce

1. Use the fill tool

## More details

**Affected browsers/platforms:**  Chrome PWA

**First affected release:**  r198

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r198/projectResources.js, line 1, col 1000899
Message: Uncaught TypeError: this.ǃUTZ is not a function
Stack: TypeError: this.ǃUTZ is not a function at Function.ǃUTg (https://editor.construct.net/r198/projectResources.js:1:1000899) at Function.ǃV_Q (https://editor.construct.net/r198/projectResources.js:1:1000047) at Object.ǃkB (https://editor.construct.net/r198/projectResources.js:1:830434) at Array. (https://editor.construct.net/r198/projectResources.js:1:828303) at Object.ǃtgP (https://editor.construct.net/r198/main.js:2:200836) at Object.dispatchEvent (https://editor.construct.net/r198/main.js:2:198621) at Object.ǃUqZ (https://editor.construct.net/r198/projectResources.js:1:701093) at Object.ǃUqY (https://editor.construct.net/r198/projectResources.js:1:881077) at Object.ǃUqE (https://editor.construct.net/r198/projectResources.js:1:881581) at https://editor.construct.net/r198/projectResources.js:1:880116
Construct 3 version: r198
URL: https://editor.construct.net/r198/
Date: Tue May 05 2020 02:45:52 GMT+0300 (GMT+03:00)
Uptime: 5.5 s

Platform information
Browser: Chrome
Browser version: 81.0.4044.129
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
C3 release: r198 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2
</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
