### ISSUE TITLE
Color tween on r198 is not working

### ISSUE THREAD

**Issue by pralista** [Scirra/Construct-3-bugs#3831]
## Problem description
When i used r197.2 version, the color tween was working perfectly. Now, everytime i used color tween in r198 version, it got crashed and the preview screen went freeze

## Attach a .c3p
[bug_tween_color.zip](https://github.com/Scirra/Construct-3-bugs/files/4582065/bug_tween_color.zip)

## Steps to reproduce

1. Open any projects
2. Make tween (one property) action
3. Change the property into color and fill the end value (in my case i use rgba255(255,0,0,255))
4. When you run the preview, everytime it execute the action, it went freeze

## Observed result
The color tween didn't run and the program get freeze

## Expected result
The object change its color based on our rgb value (in my case it should be red)

## More details
In this c3p you'll find when we pressed the green button the screen will freeze and the color tween didn't run

**Affected browsers/platforms:** 

**First affected release:** 
worked in r197.2 but broke in r198

## System details

<details><summary>View details</summary>

Browser: Chrome
Browser version: 81.0.4044.129
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
C3 release: r198 (beta)
Language setting: en-US

</details>

**Comment by pralista** [comment]
Thanks for fixing the bug! But may I ask what does "duplicate" label means?

**Comment by DiegoScirra** [comment]
It means that someone already reported the same issue.

This tends to happen with pretty glaring bugs, like this one. So instead of just closing the issue, I label it **duplicate** and **fixed**. That way people can see if what they are about to report has already been fixed.

I don't really know if this works, but I do it anyway :P
