### ISSUE TITLE
Window position look weird after a month not opening Construct

### ISSUE THREAD

**Issue by redfoc** [Scirra/Construct-3-bugs#3832]
![uy87](https://user-images.githubusercontent.com/30024213/81112249-8fba7400-8f48-11ea-8b39-cb09dd5c2993.PNG)
![guy](https://user-images.githubusercontent.com/30024213/81112258-921cce00-8f48-11ea-8859-dae57fc23db0.PNG)

Lets image explained

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to investigate reports without steps to reproduce the problem. Please see the bug report guidelines.

Note Construct does not do anything while you are away, so the length of time should not have affected this.
