### ISSUE TITLE
Global layer bug

### ISSUE THREAD

**Issue by theprocrastinator-dev** [Scirra/Construct-3-bugs#3835]
First happened to me roughly 1 year ago... And is still happening.
Whenever you create a global layer (and it gets overriden in other layout(s)), whenever you put an object on it and then try to change its layer, the object will either simply become inaccessible (literally vanishes from existence) or you won't even be able to change its layer at all (like it happened in ~3 projects of mine where I used global layers to keep save/load related info texts in the top z order of all layouts.

## Attach a .c3p
[bugrep.zip](https://github.com/Scirra/Construct-3-bugs/files/4585110/bugrep.zip)

## Steps to reproduce

1.Create a global layer
2.Create another layout and reproduce the layer so it can get overriden by the original instance of it
3.Place an object inside the overriden layer and then try to move it to other layers

It will either break if it gets placed on certain layers or they will simply not appear as an option (in the object "Layer" tab).

It should behave normally.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 81.0.4044.129
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 245 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
@theprocrastinator-dev

This is working as expected. It's a little bit confusing to explain what is going on, but I'll try.

An overridden layer shows the content of the source global layer. That means that changing the **layer property** of an instance in an overridden layer is the same as changing it in the original.

That is why even though you are in the layout **go here**, the instance shows the layers of **Layout 1** as the possible options, because it is in fact the same instance in **Layout 1**.

**Comment by theprocrastinator-dev** [comment]
Hmm, I understand I guess.
But just a question tho.
How can I move those objects to the desired layer then? Do I have to re-create the instance in a non-global layer ? Or there's another way?

**Comment by DiegoScirra** [comment]
Doing this by changing the layer property would be an improvement feature, as it can't be done that way right now.

As a workaround you can cut the instances from the overridden layer, change to the the layer you want and paste them in there. Doing this removes the instances from the global layer, so if you go back to the original, they won't be there.

**Comment by theprocrastinator-dev** [comment]
Ok, thank you!
And yes, it would be a good idea.
