### ISSUE TITLE
Odd sprite crash bug

### ISSUE THREAD

**Issue by RorySoh** [Scirra/Construct-3-bugs#3837]
## Problem description

There seems to be a consistent enough, but yet random bug that is caused by doing this specific sequence of events. However, I'm not sure why it is not replicated each time, but has happened 4 out of 5 times I've tried it.

**This is a video of my demonstrating the crash**
https://streamable.com/8g9pll

## Attach a .c3p

[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/4588148/New.project.zip)

## Steps to reproduce

1. Create a new project in the latest beta editor with no name.
2. Add timeline.
3. Add Sprite object
4. Paint bucket fill the sprite object.

## Observed result

An editor crash.

## Expected result

Paint filling the sprite.

## More details

Here are some console logs screenshots
https://imgur.com/a/Dv1wJP4

**Affected browsers/platforms:** 

Chrome

**First affected release:** r198

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r198/projectResources.js, line 1, col 1000899
Message: Uncaught TypeError: this.ǃUTZ is not a function
Stack: TypeError: this.ǃUTZ is not a function at Function.ǃUTg (https://editor.construct.net/r198/projectResources.js:1:1000899) at Function.ǃV_Q (https://editor.construct.net/r198/projectResources.js:1:1000047) at Object.ǃkB (https://editor.construct.net/r198/projectResources.js:1:830434) at Array.ǃVMw (https://editor.construct.net/r198/projectResources.js:1:828303) at Object.ǃtgP (https://editor.construct.net/r198/main.js:2:200836) at Object.dispatchEvent (https://editor.construct.net/r198/main.js:2:198621) at Object.ǃUqZ (https://editor.construct.net/r198/projectResources.js:1:701093) at Object.ǃUqY (https://editor.construct.net/r198/projectResources.js:1:881077) at Object.ǃUqE (https://editor.construct.net/r198/projectResources.js:1:881581) at https://editor.construct.net/r198/projectResources.js:1:880116
Construct 3 version: r198
URL: https://editor.construct.net/r198/
Date: Thu May 07 2020 00:41:51 GMT+0800 (Singapore Standard Time)
Uptime: 30.3 s

Platform information
Browser: Chrome
Browser version: 81.0.4044.129
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
C3 release: r198 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
This has been fixed already, but it is pretty obvious, so a lot of people are reporting it. It's the fill tool in the Animations editor at fault.

**Comment by RorySoh** [comment]
Ahh, no problem. Great work!
Just made this because I reported it on the update log but Ashley said he couldn't replicate it.
