### ISSUE TITLE
Status bar not hidden when exporting to android

### ISSUE THREAD

**Issue by Bighands22** [Scirra/Construct-3-bugs#3839]
## Problem description

Selecting hide status bar does not hide the status bar when exporting to android

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's usually impossible to deal with reports if you ignore the bug report guidelines.

To try this anyway, I exported Space Blaster as a debug APK with "hide status bar" enabled. As expected, it hid the status bar. So it appears to be working correctly.
