### ISSUE TITLE
Not hiding status bar on android (updated with more detail)

### ISSUE THREAD

**Issue by Bighands22** [Scirra/Construct-3-bugs#3840]
## Problem description

I export my game to android and select hide status bar, when opening the app on android the status bar is still showing.

## Attached video to show steps to reproduce
https://youtu.be/cDiZd4F84AM

## Steps to reproduce

I have attached a video 

but it goes something like.

1.select Export file to android devices 

2.deduplicate images and recompress selected

3.minify none

4. min version 7.0

5.signed release

6. select hide status bar and require external storage.

7. add signing key

9. click export

10. send to google drive

11. download from google drop

12. open app and see black bar still at the top.

## Observed result

Status bar is not hidden, it shows a block bar at the top of screen. Shown in the video.

## Expected result

no status bar

## More details
r189 stable release still works fine and removes the status bars for me

android only, I can hide the bars for IOS using xcode

## System details

r197, r198 and r198.2 all same

**Comment by AshleyScirra** [comment]
I'm afraid it's still impossible to investigate this, because there is no provided project for me to try out. Please follow the bug report guidelines: they are there because we actually need all that information to be able to help you.
