### ISSUE TITLE
Weird square green artifacts in the exported project

### ISSUE THREAD

**Issue by theprocrastinator-dev** [Scirra/Construct-3-bugs#3843]
Despite them not appearing in the construct preview (project preview), there are square green artifacts spawning nearby the player and enemies whenever an sfx sprite spawns in. Only in the exported version of the project. I'm sorry but I have absolutely no idea on how to reproduce this bug, and would like to know if there's a known reason for that happening. It almost looks like a bugged 'green screen' effect.

## Attach a .c3p
https://robertonascimento.itch.io/project-cybergladiator (link to the exported project)

## Steps to reproduce

1.Not known
2.
3.

No green square should spawn nearby spawning sprites.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 81.0.4044.138
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 252 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by theprocrastinator-dev** [comment]
Update:
Erased the whole "player" sprite (which is a green square, even though its set to be invisible for the whole game) and the artifacts stopped showing up...

**Comment by AshleyScirra** [comment]
There's no project attached, so I can't try this in Construct. I tried the exported project, and everything looked normal. Even if something unusual appeared, I can't prove it's not actually an intended part of the project without the project file. Also I don't know what to look for because no screenshots have been provided. Even if screenshots are provided, I can't debug a screenshot, so it provides very little to go on.

Without more to go on, I would guess this is some kind of graphics driver bug. Since there is no further action that can be taken, closing. Please always follow the bug report guidelines - they are there because it is impossible to help you unless you provide that information. If you file issues without that information, all we can do is close them because there is actually nothing we can do about it.

**Comment by theprocrastinator-dev** [comment]
Alright.
Yeah, currently in the exported version there's nothing wrong because of my workaround above (I erased the green player sprite in the animation editor).

But from what I could've gather is: There's is some minor problem after exportation related to object's initial visibility whenever something spawns nearby it (a particle or sprite). After exportation only, since it looks fine inside the construct's preview mode.
And yes, I am aware of that. I'm sorry but so far I could not find a way to reproduce the issue. Gonna try again later and see if I can find anything.
