### ISSUE TITLE
r197.2 iOS 13.3.1 Browser SW updates related events don't fire on Safari and Chrome

### ISSUE THREAD

**Issue by Sanquen** [Scirra/Construct-3-bugs#3844]
## Problem description
Safari doesn't update the game with the ServiceWorker. One must invalidate the all Safari cache to get the latest version. None of the Browser updates related events (onupdatefound/onupdateready/onoffineready) fire.

Same with Chrome 81.0.4044.124. The SW log entries can't be seen on chrome://inspect.
*But* the SW works since the game is updated on the next page refresh. 

Works fine on Windows and Android (Chrome and Samsung Internet): events fire. Meaning the connection is HTTPS and no server cache issue. 

## Attach a .c3p

[test_update.zip](https://github.com/Scirra/Construct-3-bugs/files/4601011/test_update.zip)

## Steps to reproduce

Export to HTML5, put on HTTPS server, invalidate the server cache if any. Browse with Safari.
Do this twice.

## Observed result

SW updates related events don't fire.

## Expected result

SW updates related events to fire so we can keep the user informed an update is in progress and make him wait on a specific layout or the like...

## System details

r197.2 stable

**Comment by AshleyScirra** [comment]
The SW related events fire based on messages sent by a `BroadcastChannel`, which iOS doesn't support, so the messages cannot be sent, so the triggers do not fire. Other than that the SW should be working normally.

FYI Apple ban all other browser engines on iOS, so other browsers like Chrome are just skins over Safari, so generally there's no point testing them to find any differences, they just do the same thing as Safari.

**Comment by Sanquen** [comment]
Ok, thanks.
