### ISSUE TITLE
Fullscreen Quality Low fps depends on Window Size

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#3845]
## Problem description

I am not sure if I misunderstood something, but I thought with Fullscreen quality Low, the frame rate will be constant, independent of the Screenresolution /Window Size. This seems not to be the case, with the attached sample project I measured those differences in Fullscreen:

3008x1692 = 44fps
2560x1440 = 56fps (jerky)
2404x1296= 60fps (but visible still jerky/not regular)
1920x1080 = 60fps (visible very smooth)

I changed the resolution of my screen and went to Fullscreen mode. I used a quit powerful macbook pro.

## Attach a .c3p

[fullscreen_fps.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4601960/fullscreen_fps.c3p.zip)

## Steps to reproduce

1. Start the project on a screen with High resolution (for example 3008x1692)
2. Preview in Fullscreen
3. Now switch your monitor to 1920x1080 and do the same

## Observed result
different frame rate

## Expected result
same frame rate

## More details

**Affected browsers/platforms:** 

**First affected release:** 
I tested in the latest stable and also in the lates Beta r198
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 81.0.4044.138
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 1.4 gb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
> I thought with Fullscreen quality Low, the frame rate will be constant, independent of the Screenresolution /Window Size.

This is not true. The entire game renders at a fixed size - but then the result must be stretched up to the final display size. This still requires rendering a larger area depending on the view size.

This saves lots of GPU bandwidth if you have a rendering-heavy game, such as using lots of own-texture layers or lots of images overlapping each other. However if you have a simple game then it doesn't save much GPU bandwidth, as stretching the result up to fill the screen uses as much GPU bandwidth as the game probably would have anyway without "low quality" fullscreen mode. On a device with a high-resolution display and a weak GPU, this may be a measurable difference.

For example, consider a 4K display at 3840 x 2160. A single frame uses about 32mb of memory. Updating it at 60 FPS will require about 2 GB/s memory bandwidth, just to update the screen. The browser/OS may also have to copy that once or twice for buffering, making it 4 or 6 GB/s. Then everything your game actually does is added on top of that. The hardware requirements quickly become very high with such high resolution displays.

**Comment by bubbblebub** [comment]
ok, thanks a lot for the insight!
