### ISSUE TITLE
Delete object from Families. it wii delete object type from project.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#3846]
## Problem description

When I select the object to delete from Families, it does not remove the object type in Family, it is delete from the project. This question has had been bothering me for a long time.Because I'm currently working in the Families folder, selecting family object to delete.

If I really need to delete the object type, I should select it from the object types folder and delete it, not in Families.

## Steps to reproduce
1. select one object in Families
2. pressed ‘Delete’ 

## Observed result
1. select one object from Families
2. pressed ‘Delete’ 
3. delete from project. ×

## Expected result

1. select one object from Families
2. pressed ‘Delete’ 
3. remove this object from Families. √

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Updated 'Delete' keyboard shortcut to remove members from family instead of deleting object types for the next beta.
