### ISSUE TITLE
[Whitelist] Vinoos IAP

### ISSUE THREAD

**Issue by miladesign** [Scirra/Construct-3-bugs#3847]
Hi,
I would like to request to add the `vinoos-cordova-iap` plugin.

thanks.

**Comment by mostafanastary** [comment]
@AshleyScirra , How long do you think it will take to do this? please let us know.

**Comment by AshleyScirra** [comment]
Updated whitelist on build server.

**Comment by VinoosIr** [comment]
hi. please whitelist these plugins update:
`vinoos-cordova-iap@1.1.4`

**Comment by rafieimohammad82** [comment]
@AshleyScirra

**Comment by AshleyScirra** [comment]
Please note closed issues are not generally monitored.
