### ISSUE TITLE
Rotating Objects in Timeline will Crash

### ISSUE THREAD

**Issue by TMsimonW** [Scirra/Construct-3-bugs#3848]
Make any blank C3 file in r198 with a timeline. When trying to rotate any object C3 will instantly crash

1. Create a blank C3 file
2. Create a sprite and timeline 
3. Add the angle to the time
4. Click edit on the time line editor 
5. Attempt to rotate the Sprite

## Observed result

Crash

## Expected result

For the sprite to rotate

## More details

**Affected browsers/platforms:** 

R198

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r198/components/editors/layoutView/layoutView.js, line 1, col 99552
Message: Uncaught ReferenceError: ǃKo is not defined
Stack: ReferenceError: ǃKo is not defined at m.ǃkB (https://editor.construct.net/r198/components/editors/layoutView/layoutView.js:1:99552) at Array. (https://editor.construct.net/r198/components/editors/layoutView/layoutView.js:1:97722) at Object.ǃtgP (https://editor.construct.net/r198/main.js:2:200758) at Object.dispatchEvent (https://editor.construct.net/r198/main.js:2:198621) at Object.ǃkB (https://editor.construct.net/r198/components/editors/layoutView/layoutView.js:1:19431) at HTMLDivElement.ǃah (https://editor.construct.net/r198/components/editors/layoutView/layoutView.js:1:18858) at HTMLDocument. (https://editor.construct.net/r198/main.js:2:196240)
Construct 3 version: r198
URL: https://editor.construct.net/r198/
Date: Sat May 09 2020 14:08:55 GMT+0100 (British Summer Time)
Uptime: 62.8 s

Platform information
Browser: Chrome
Browser version: 81.0.4044.127
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Chrome OS
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 12871.91.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.127 Safari/537.36
C3 release: r198 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) UHD Graphics 600 (GLK 2)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
