### ISSUE TITLE
Parallax in editor doesn't work

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#385]
## Problem description

I have made a game with parallax. It work great when i play the game. But in the Layer properties, if I use "Parallax in editor" it doesn't work.

## Steps to reproduce

1. Create layer with parallax in a scrolling game.
2.Activate the "Parallax in editor" option.

## Observed result

Nothing

## Expected result

Parallax in editor

## Affected browsers

* Chrome: yes/

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r34.
