### ISSUE TITLE
Timeline Keyframe on Start Bug

### ISSUE THREAD

**Issue by hammanneric6** [Scirra/Construct-3-bugs#3850]
## Problem description

I'm back again, sorry.  The issue this time is that if you have a keyframe in a timeline that performs an action immediately upon a timeline starting it won't register.  I guess the simple way to put it would be a keyframe on the 0 seconds mark of timeline won't register any "On keyframe reached" events.

## Attach a .c3p

https://drive.google.com/open?id=1uyMxr5opTLmCdh5S-tIthoaSw3-TJRfi

## Steps to reproduce

1. Run the project
2. Timeline starts 2 seconds after the game loads

## Observed result

The sprite has two animations, it does not start to switch between these animations until the second keyframe.

## Expected result

The sprite should immediately set itself to "animation2" (turn red) due to the keyframe at the start.  It instead doesn't do this until it hits the second keyframe.

## More details

Tested in NWJS and Chrome.  Issue occurred in both.

**Affected browsers/platforms:** 

I downloaded the beta release of Construct today so Version r199 Beta.  My computer is running Windows 10 Version 1903.

**First affected release:** 

Version r199 Beta

## System details

Platform information
Browser: Chrome
Browser version: 81.0.4044.138
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
C3 release: r199 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 2.6 gb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
@hammanneric6 

This isn't a bug, it's how it should have worked from the start. The idea being that the condition is only triggered when a keyframe is reached during playback, rather than any time the play head is on top a given keyframe. 

From now on you shouldn't rely on the old behaviour, hopefully is not too much of a problem.
