### ISSUE TITLE
Array & Dictionary Editor bugged on IOS (Ipad)

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3851]
## Problem description

I found two main issues, the smaller one: cmd+c or cmd+x don‘t work. (I assume that one is because of the clipboard API not supported?) The bigger one: I cannot add more than one character into a cell. For example, if I try to change a value typing „hello“ the cell will only be filled with „h“ and any further input is ignored. I have not found any workaround for that. I tried it with the onscreen keyboard and an added keyboard. Also, deleting doesn‘t work and you have to resort to using leftclick > clear.

## Attach a .c3p

Reproduces in a fresh project.

## Steps to reproduce

1. Open array editor
2. Attempt to fill a cell with more than one character
3. Attempt to delete a cell using backspace

## Observed result

Cell gets filled with only the first input, then all inputs are ignored. Deleting with backspace does nothing.

## Expected result

To be able to fill it properly and to be able to copypaste.

## More details

**Affected browsers/platforms:** 
Chrome & Safari

Tried it with the previous stable release, same thing. I suppose this is either a new issue or has been present for a while from an ios release.

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome for iOS
Browser version: 81.0.4044.62
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 13.3
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/81.0.4044.62 Mobile/15E148 Safari/604.1
C3 release: r199 (beta)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS containment is not supported. Editor performance may be significantly degraded.
Service Workers are not supported. Construct 3 cannot be used offline in this browser.
The <dialog> element is not supported. A polyfill is in use.
The Clipboard API is not supported. Some clipboard features may be unavailable.
Web Animations are not supported. Animations are disabled.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by Wackytoaster** [comment]
https://youtu.be/H6AV8nLZqQU

I just thought I‘d make a quick recording of it. Glad to see it being worked on since I don‘t have access to any other device only my phone and Ipad and I really don‘t want to use my phone <3

**Comment by AshleyScirra** [comment]
It reproduces in Safari on macOS so doesn't appear to be iOS specific. It looks like some awkward difference about how Safari handles these fields. I found a workaround though so it should be working in the next release.
