### ISSUE TITLE
I found a small glitch on right click "menu"

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3852]
## Problem description
on layout select few object and right click move cursor over "Align" and sub-menu is opened then If move mouse from "Align" menu to sub-menu "Edge" or "Space" or "Size" slowly then its normal but if we move mouse quickly then sub-menu go hide. see the gif below.

## Attach a .c3p
![glitch](https://user-images.githubusercontent.com/17684135/81649656-45f0f280-944e-11ea-9bf5-a689282a99db.gif)

## Steps to reproduce

1. Open any Demo project
2. select more than 1 object
3. right click over the selected object
4. move mouse over the "Align" option
5. move mouse quickly over sub-menu options "Edge" or "Space" or "Size"

## Observed result

sub-menu hides

## Expected result

sub-menu should stay open

## More details

I noticed this glitch many many many releases before its very old but i thought its not a big issue. but now when i got this too many times So i think its time to report this.

**Affected browsers/platforms:** 
i found this on Chrome and Desktop version both.

**First affected release:** 
worked in r134 but broke in r135
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
I think I fixed this one. It's hard to be sure so make sure to check it in the next beta release.

**Comment by AshleyScirra** [comment]
r200 is now out, please check again!

**Comment by luckyrawatlucky** [comment]
yes its fixed 
thanks

**Comment by AshleyScirra** [comment]
Thanks for confirming.
