### ISSUE TITLE
Browser crash deleting timeline R199

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-3-bugs#3853]
## Problem description
Chrome crash when deleting a timeline.

## Attach a .c3p
[timeline crash.zip](https://github.com/Scirra/Construct-3-bugs/files/4615170/timeline.crash.zip)

## Steps to reproduce
Try to create a timeline. Then right click on timeline name and select DELETE. Chrome crash.

1. create a new project.
2. create a new timeline.
3. right click and try to delete it.
4. chrome crash.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE
Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃtII' of undefined @ TypeError: Cannot read property 'ǃtII' of undefined at a.ǃtII (https://editor.construct.net/r199/projectResources.js:1:467117) at a.ǃtww (https://editor.construct.net/r199/projectResources.js:1:470300) at a.ǃtwx (https://editor.construct.net/r199/projectResources.js:1:25081) at a.ǃdN (https://editor.construct.net/r199/projectResources.js:1:24961) at a.ǃdN (https://editor.construct.net/r199/projectResources.js:1:469951) at Object.ǃdH (https://editor.construct.net/r199/components/bars/projectBar/projectBar.js:1:11316)
Stack: TypeError: Cannot read property 'ǃtII' of undefined at a.ǃtII (https://editor.construct.net/r199/projectResources.js:1:467117) at a.ǃtww (https://editor.construct.net/r199/projectResources.js:1:470300) at a.ǃtwx (https://editor.construct.net/r199/projectResources.js:1:25081) at a.ǃdN (https://editor.construct.net/r199/projectResources.js:1:24961) at a.ǃdN (https://editor.construct.net/r199/projectResources.js:1:469951) at Object.ǃdH (https://editor.construct.net/r199/components/bars/projectBar/projectBar.js:1:11316)
Construct 3 version: r199
URL: https://editor.construct.net/r199/
Date: Tue May 12 2020 13:11:10 GMT+0200 (Ora legale dell’Europa centrale)
Uptime: 180.4 s

Platform information
Browser: Chrome
Browser version: 81.0.4044.138
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
C3 release: r199 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2
</details>

**Comment by TheRealDannyyy** [comment]
I experienced this in the NWjs desktop version as well, without the entire thing just crashing.
Here is the info:
Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃtII' of undefined @ TypeError: Cannot read property 'ǃtII' of undefined at a.ǃtII (https://editor.construct.net/r199/projectResources.js:1:467117) at a.ǃtww (https://editor.construct.net/r199/projectResources.js:1:470300) at a.ǃtwx (https://editor.construct.net/r199/projectResources.js:1:25081) at a.ǃdN (https://editor.construct.net/r199/projectResources.js:1:24961) at a.ǃdN (https://editor.construct.net/r199/projectResources.js:1:469951) at window.ǃps.ǃdH (https://editor.construct.net/r199/components/bars/projectBar/projectBar.js:1:11316)
Stack: TypeError: Cannot read property 'ǃtII' of undefined at a.ǃtII (https://editor.construct.net/r199/projectResources.js:1:467117) at a.ǃtww (https://editor.construct.net/r199/projectResources.js:1:470300) at a.ǃtwx (https://editor.construct.net/r199/projectResources.js:1:25081) at a.ǃdN (https://editor.construct.net/r199/projectResources.js:1:24961) at a.ǃdN (https://editor.construct.net/r199/projectResources.js:1:469951) at window.ǃps.ǃdH (https://editor.construct.net/r199/components/bars/projectBar/projectBar.js:1:11316)
Construct 3 version: r199
URL: https://editor.construct.net/r199/
Date: Tue May 12 2020 18:38:09 GMT+0200 (Central European Summer Time)
Uptime: 30.9 s

Platform information
Browser: NW.js
Browser version: 0.44.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.0 (like Chrome/80.0.3987.87)
C3 release: r199 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 SUPER Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
