### ISSUE TITLE
Construct 3 crashes when opening project

### ISSUE THREAD

**Issue by bedfl2016** [Scirra/Construct-3-bugs#3856]
Hi Guys,

When I open a .c3p file from my Google Drive I get this:

I have tried different versions of c3 and this file was made and saved through c3 so I haven't modified it outside of c3.

Error report information
Type: unhandled rejection
Reason: Error: invalid function name 'Card1' @ Error: invalid function name 'Card1' at t.ǃciW (https://editor.construct.net/r199/projectResources.js:1:308812) at t.ǃmu (https://editor.construct.net/r199/projectResources.js:1:308729) at window.ǃtU$.ǃciy (https://editor.construct.net/r199/projectResources.js:1:333352) at t.accept (https://editor.construct.net/r199/projectResources.js:1:263564) at t.accept (https://editor.construct.net/r199/projectResources.js:1:299365) at t.ǃcio (https://editor.construct.net/r199/projectResources.js:1:285376) at t.accept (https://editor.construct.net/r199/projectResources.js:1:263580) at t.ǃcio (https://editor.construct.net/r199/projectResources.js:1:270811) at t.ǃcio (https://editor.construct.net/r199/projectResources.js:1:285421) at t.accept (https://editor.construct.net/r199/projectResources.js:1:263580)
Stack: Error: invalid function name 'Card1' at t.ǃciW (https://editor.construct.net/r199/projectResources.js:1:308812) at t.ǃmu (https://editor.construct.net/r199/projectResources.js:1:308729) at window.ǃtU$.ǃciy (https://editor.construct.net/r199/projectResources.js:1:333352) at t.accept (https://editor.construct.net/r199/projectResources.js:1:263564) at t.accept (https://editor.construct.net/r199/projectResources.js:1:299365) at t.ǃcio (https://editor.construct.net/r199/projectResources.js:1:285376) at t.accept (https://editor.construct.net/r199/projectResources.js:1:263580) at t.ǃcio (https://editor.construct.net/r199/projectResources.js:1:270811) at t.ǃcio (https://editor.construct.net/r199/projectResources.js:1:285421) at t.accept (https://editor.construct.net/r199/projectResources.js:1:263580)
Construct 3 version: r199
URL: https://editor.construct.net/r199/
Date: Wed May 13 2020 14:46:20 GMT+0100 (British Summer Time)
Uptime: 22.6 s

Platform information
Browser: Chrome
Browser version: 81.0.4044.138
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
C3 release: r199 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 with Max-Q Design Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help unless you follow the report guidelines. Do you have steps I can follow to produce this error in the first place? Anything that results in a corrupt project would be a high priority to fix.

If you provide the project file it may be able to be recovered, but it might happen again unless we fix the underlying problem.

**Comment by bedfl2016** [comment]
@AshleyScirra 

I didn't do anything I made my project and saved it and now I can't open it there are no steps to reproduce if I post the .c3p file please could you recover it.

**Comment by AshleyScirra** [comment]
If you provide the project file I can attempt to recover it, but it might happen again unless we fix the underlying problem.

**Comment by bedfl2016** [comment]
@AshleyScirra 

Here is the link to the file:

https://github.com/bedfl2016/Upload/blob/master/Squadv7.c3p

I have tried opening the file on other computers in c3 and get the same error.

**Comment by AshleyScirra** [comment]
Here is the recovered project:
[squadv7-recovered.zip](https://github.com/Scirra/Construct-3-bugs/files/4623325/squadv7-recovered.zip)

All I did was remove an action that called a function named "Card1" on start of layout. There is no such function in the project. This should be impossible - deleting a function should remove all actions calling it too. Maybe there is a loophole somewhere though. If you can find the loophole it would be a high priority to fix. Unfortunately without those steps there's no further action we can take though, so closing for now.

**Comment by bedfl2016** [comment]
@AshleyScirra 

Thanks for the quick response. I will try and find this bug for you and some steps to recreate it.
