### ISSUE TITLE
Animation properties menu gets blocked by the description of it

### ISSUE THREAD

**Issue by RyanCuzalina** [Scirra/Construct-3-bugs#3857]
![](https://construct-static.com/images/v786/uploads/articleuploadobject/0/images/41163/screen-shot-2020-05-11-10-54.png)

![](https://construct-static.com/images/v786/uploads/articleuploadobject/0/images/41164/screen-shot-2020-05-11-10-54.png)

Basically what is happening is if I open any sprite and go to there animations and try to click things in there animation properties tab,like loop or repeat count, it just gets blocked by the description for that object, for example if I try to click loop, it just blocks it with "Repeat the animation forever". This has never happened to me when I started months ago, but recently it just won't stop.

Snubs Fight (5).c3p

**Comment by AshleyScirra** [comment]
It seems to be working fine here. Please follow the bug report guidelines otherwise it's impossible to help.

**Comment by RyanCuzalina** [comment]
> It seems to be working fine here. Please follow the bug report guidelines otherwise it's impossible to help.

I think you did help cuz now it works just fine
