### ISSUE TITLE
Multiplayer Room Leaving Bug

### ISSUE THREAD

**Issue by givemeapixel** [Scirra/Construct-3-bugs#3859]
## Steps to reproduce

1. Put a nickname in the 'nickname' chat box, click the 'create' button on the right, then put in a name in the 'room name' chat box. Then click the 'join' button.
2. You should be able to move via the joystick around and attack via the sword button. Click the 'menu' button to return to the login page. 
3. Re-enter a nickname in the 'nickname' chat box, then enter the same or a different room name in the 'room name' chat box. Click the 'join' button.  I recommend trying the same and a different room name.

## 

**Affected browsers/platforms: Built and tested on Chrome and tested (via remote preview) on Amazon fire (Silk Browser)** 

**First affected release: Not exactly sure, but it has never worked in any release** 

## System details

<details><summary>View details</summary>

Browser: Chrome
Browser version: 81.0.4044.138
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 541 gb
Storage usage (approx): 204 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Jase0000** [comment]
Hello!
I'm sorry if I'm incorrect, but this sounds very similar to an issue I have reported, but I'm not too sure! If you feel it is similar.

https://github.com/Scirra/Construct-3-bugs/issues/3834

My issue is that, randomly, when joining a room (sometimes on the first try, sometimes 2nd try, sometimes 6th try, etc.), messages fail to send and (recently I realised) the peer will lose connection after a some time too. But then retrying to join room (without leaving the preview), it might work perfectly, so it's very unpredictable.

I didn't know how to demonstrate my bug report further (no errors on my side, not in console, nowhere, Ashley could not reproduce), so I've made a workaround for my project to get past this for now.

**Comment by AshleyScirra** [comment]
The attached project has over 200 events. I'm afraid such projects are almost impossible to debug and it's difficult to rule out that you've just made a mistake, which is very common. Please see the bug report guidelines.

People have recently filed a few similar-sounding issues that were also mistakes in their events: when leaving a room you must both disconnect from the host, *and* leave the room on the signalling server. You must also wait for both to complete before attempting rejoining again. Without a minimal project, I would assume this is the same mistake made in your project.

**Comment by givemeapixel** [comment]
@AshleyScirra 
Here is a link to a modified chat room example that showcases the bug. It is very similar to the file I put in the report; the instructions are basically the same and the same thing happens. Do you want me to file another report? https://www.dropbox.com/s/tdbdptwi9szdnzc/Multiplayer%20room%20leaving%20bug.c3p?dl=0

**Comment by AshleyScirra** [comment]
No, that's exactly the mistake I described. You try to do everything at once without waiting for previous operations to complete.

**Comment by givemeapixel** [comment]
Yes! It was not a bug, I fixed it. I found this issue: [https://github.com/Scirra/Construct-3-bugs/issues/3817](url) and read your comment. I tried it and it worked perfectly. Thank you!
