### ISSUE TITLE
[Request] Tilemap Editor buttons

### ISSUE THREAD

**Issue by anty21ro** [Scirra/Construct-3-bugs#386]
When I select a tool in the Tilemap Editor, mirror or rotate, I would like to see them highlighted (like the erase button is, for example) so I know the tiles are mirrored or rotated. It would be easier this way, for some specific tiles, instead of verifying if the tile is on default rotation of mirroring.

**Comment by DiegoScirra** [comment]
Added this in r36.

I did something I little bit different thought.  You will now be able to see the current transformation state at the bottom of the Tilemap Bar. 

Ej. **Mirror:** _Yes_  **Flip:** _No_  **Rotation:** _90°_
