### ISSUE TITLE
Old projects have the Function object still in them.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3862]
## Problem description

It is an issue as minor as it gets, but since they are nowadays not an object anymore, I believe it would stand to reason to remove them from sight whenever an older project is loaded up.

I am able to delete the object myself, but then I have to rebuild the function name blocks and recall every function and it is just unfeasable.

**Comment by AshleyScirra** [comment]
This is not a bug, and the legacy Function object is actually already deleted if it has no references. If it still has references, it cannot be deleted without breaking the project, so it doesn't.
