### ISSUE TITLE
error when compiling for android

### ISSUE THREAD

**Issue by RenamGM** [Scirra/Construct-3-bugs#3866]
## Problem description

 Error generating apk

## Attach a .c3p

 
[test.zip](https://github.com/Scirra/Construct-3-bugs/files/4644942/test.zip)

## Steps to reproduce

1. export >> android

## Observed result

 Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=~~/androidSDK (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
:wrapper

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Script '~~/cordova.gradle' line: 132

* What went wrong:
A problem occurred evaluating project ':app'.
> No match found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 1s
~~/gradlew: Command failed with exit code 1 Error output:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Script '~~/cordova.gradle' line: 132

* What went wrong:
A problem occurred evaluating project ':app'.
> No match found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 1s

## Expected result

 An android application

## More details

 yes, it occurs in chrome, fire fox

**Affected browsers/platforms:** 

version :  r197.2

**First affected release:** 

## System details

 
![erro2](https://user-images.githubusercontent.com/65552816/82230220-d1acc800-9901-11ea-8067-79b982791822.png)
![erro3](https://user-images.githubusercontent.com/65552816/82230222-d2455e80-9901-11ea-8820-2847417ff7c1.png)
![errro1](https://user-images.githubusercontent.com/65552816/82230224-d2455e80-9901-11ea-952f-2fc996a5f1b0.png)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I tried a debug APK build and it worked fine.

The report is confusing. The screenshots include a warning about Mobile Advert. However Mobile Advert is not used in the provided project. Why did you include that picture? How does that relate to the issue?

**Comment by RenamGM** [comment]
because the screenshots were from another project, but the error happens in this project too.

**Comment by AshleyScirra** [comment]
As I said, it builds fine for me. Can you describe the exact build settings you are using?

**Comment by RenamGM** [comment]
Exporting>>android>>signed android app bundle..

Note: When I generate apk through the debugger it works normal. but when I put it on the phone the apk doesn't work

**Comment by AshleyScirra** [comment]
Have you tried the latest release? The report says you used r197.2, but the latest release is r200, and the guidelines require that you test the latest release.

**Comment by RenamGM** [comment]
In the r200 beta version there is also an error going in : Exporting >> android >> signed android app bundle ..

look at this project
[testando 2.zip](https://github.com/Scirra/Construct-3-bugs/files/4650562/testando.2.zip)

**Comment by RenamGM** [comment]
this is my project without the images, but with events...

[teste 3 com eventos.zip](https://github.com/Scirra/Construct-3-bugs/files/4651068/teste.3.com.eventos.zip)

**Comment by RenamGM** [comment]
Here is a piece of my project without the images, but with the events
[test com eventos.zip](https://github.com/Scirra/Construct-3-bugs/files/4651486/test.com.eventos.zip)

**Comment by AshleyScirra** [comment]
When exporting to Android it has two warnings, the first about the version number, and the second about Mobile Ad being incorrectly configured. These could be causing the problem. If you fix those issues, does it build successfully?

**Comment by RenamGM** [comment]
How do I fix the ad error and version error?

I removed the ad and still can't generate the apk ..

**Comment by AshleyScirra** [comment]
The warnings tell you what to change. You need to have a full version number and all fields of the Mobile Ad object filled out.

I tried building a signed Android App Bundle and it worked fine, even without the warnings addressed.

Your previous comment said you couldn't build an Android App Bundle (AAB), but now you said you tried an APK. This confuses the issue, it's not clear which you're actually using - or does it affect both?

Since my builds seem to work fine, I would guess there is a problem with your keystore. Try creating a new one, and make sure you enter the correct password. I think this is likely to be the problem, since my builds are working fine, and we've not heard any other users having issues, so closing this report.

**Comment by RenamGM** [comment]
I did another keystore it worked when I removed the ad ..

how do I solve the error of the ad?

**Comment by RenamGM** [comment]
problem solved!  the apk did not work because the ad settings were wrong, and I put the version 3 code and resolvable
