### ISSUE TITLE
Multiplayer Object Breaks Debug Pause Button

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#3867]
## Problem description

When I try to pause the game in debug while the multiplayer object is present, it refuses to properly pause.

[MultiplayerBug.zip](https://github.com/Scirra/Construct-3-bugs/files/4647480/MultiplayerBug.zip)
## Steps to reproduce

1. Create a new project
2. Debug the game
3. Pause the game
4. Note how the time and ticks stop
5. Add the multiplayer object
6. Debug the game
7. Note how the time and ticks no longer stop

## Observed result

When I try to pause the game in debug, time continues forward.

## Expected result

I expect pause to... pause :)

## More details
In Construct 2, the ticks and time stop when paused in the debug, but the world clock time continues. However, in Construct 3, nothing stops.

## System details

Platform information
Browser: Chrome
Browser version: 81.0.4044.138
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
C3 release: r200 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 117 gb
Storage usage (approx): 299 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
This is actually intended to happen for the host of a room. If the host is paused, then it cannot respond to the network making it look like it's gone offline, and so the peers time out and get kicked off.

The problem here is it accidentally did it for any use of the Multiplayer plugin. I've fixed this so it doesn't happen all the time, and only happens for active hosts.

I could also fix it for active hosts, but then when you hit 'Pause' in the debugger, it will kick off all the connected peers, which doesn't sound like it's going to be awfully useful. So that's one quirk to be aware of.
