### ISSUE TITLE
DrawingCanvas "Save image..." not fast enough for realtime.

### ISSUE THREAD

**Issue by whistlegraph** [Scirra/Construct-3-bugs#3869]
I'm working on a project (a painting game) in which I am transferring DrawingCanvas data to Sprite data, so _that I can paste those sprites multiple times_ in a single tick on another Drawing Canvas.

The current method for this is quite difficult and I have a feeling it could be optimized, perhaps through a specialized action, either to freeze a DrawingCanvas (making it uneditable so that it can be pasted multiple times a tick, or to transfer its information to a sprite frame without encoding it as a PNG DataURI.

Here is a test project that can be used for testing the current delay.

[DrawingCanvas _Save image_.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4654412/DrawingCanvas._Save.image_.c3p.zip)

**Comment by AshleyScirra** [comment]
This does not appear to be a bug report. Please follow the bug report guidelines when filing issues. For general help please post to the forum instead.

**Comment by whistlegraph** [comment]
Thanks for the quick response. I agree it's not a bug and it's a feature request after reviewing your guidelines. I have requested an action be added to the Sprite plugin: "Load from DrawingCanvas" here: https://construct3.ideas.aha.io/ideas/C3-I-1394
