### ISSUE TITLE
H264 Videos not being played on Safari

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#3870]
## Problem description

I recently did a project where i used both Webm and H264 videos to support all browsers. While the Webm videos play without problem in Chrome and Firefox, Safari just won't play the H264 videos no matter what i do. I tried different containers, framerates, etc. nothing worked... They didn't play on iOS devices either (tested with latest iPhone 11 Pro with newest iOS release and an iPad 2017 also with the newest iPadOS).

## Attach a .c3p

[videoerror_safari.zip](https://github.com/Scirra/Construct-3-bugs/files/4657234/videoerror_safari.zip)

## Steps to reproduce

1. Open Project on Safari Browser
2. Run project

## Observed result

Video "ink_full.mp4" is not being played. Screen just stays white.

## Expected result

That the video plays.

## More details

**Affected browsers/platforms:** Safari

**First affected release:** Since last stable release, didn't test it earlier.

## System details

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 13.1
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
C3 release: r199 (beta)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_blend_minmax
EXT_sRGB
EXT_frag_depth
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBGL_compressed_texture_s3tc
WEBGL_depth_texture
WEBGL_draw_buffers
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 48000 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by AshleyScirra** [comment]
It works fine here in Safari 13.1 on macOS. Due to Safari's autoplay restrictions, you have to click or tap before the video plays. I assume you're not doing that and so are just seeing a white screen before the video plays!
