### ISSUE TITLE
Rotating Drawing Canvas produces odd results

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#3871]
## Problem description

I created a game in Construct 2 that used the Paster plugin. It has a spinning blade, and when the player touches it, a little blood splatter is produced which is then pasted onto a canvas that is pinned to the blade.

Seeing the drawing canvas in Construct 3 was one of the main reasons why I made the transition over.

So I repeat the process, pinning the canvas onto the spinning blade. However, now when the blade spins, I get a weird squashing effect.

## Attach a .c3p

[BladeBug.zip](https://github.com/Scirra/Construct-3-bugs/files/4658307/BladeBug.zip)

## Steps to reproduce

1. Pin a canvas to a rotating object or give the canvas the rotation behaviour.
2. Paste an image onto the canvas, or look at the c3p example (where I use an alpha).

## Observed result

The canvas squashes and stretches.

## Expected result

I expect it to be able to be set to any angle without creating issues. The Paster Plugin in Construct 2 managed it with ease, so it's frustrating to see Construct 3 unable to do things an older plugin can.

## More details
This also applies to when the layout is rotated, meaning I can't do camera shakes or the like.

**Comment by AshleyScirra** [comment]
Drawing Canvas does not support rotation. It has no angle property and no actions to rotate it. It looks like using the Rotate behavior circumvents this, and unsurprisingly it doesn't work. The fix will be to prevent the Rotate behavior working with Drawing Canvas.

**Comment by 4demon** [comment]
Will the same be done for the pin behaviour in that case? As I discovered the issue due to pinning it to a spinning object?

Is this to say that we'll never get rotating canvases? As I said, we were able to do this in Construct 2 with the Paster Canvas plugin.

**Comment by AshleyScirra** [comment]
Fixed for next beta so that behaviors cannot force non-rotatable objects to be rotated.

Fully supporting rotation in Drawing Canvas is really complicated, and so far has never been supported. Please post a suggestion for that if it's something you want.
