### ISSUE TITLE
issue in Object scaling while in Timeline Editing mode

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3874]
## Problem description

On Timeline Edit mode try to scale object with press and hold shift key. Object is scaling wrong 

## Attach a .c3p
![Timeline scale issue ](https://user-images.githubusercontent.com/17684135/82535531-9a8a2100-9b64-11ea-9e79-bf7843bf2773.gif)

## Steps to reproduce

1. Open any demo project
2. Add a timeline 
3. Add any object into timeline
4. Turn on Editing mode
5. Select object press and hold shift key and try to scale object from corner (as shown in gif file)

## Observed result

object scale wrong

## Expected result

scale object

## More details

**Affected browsers/platforms:** Chrome and Windows

**First affected release:** since Timeline was introduced r138

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
