### ISSUE TITLE
Crash on Timeline

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3875]
## Problem description

while in editing mode if we delete multiple properties in Timeline bar then it crash.

## Steps to reproduce

1. new project
2. add sprite
3. add sprite to timeline
4. turn on editing mode
5. select more than one property in Timeline (I selected x and y track)
6. right click and delete

## Observed result

Crash 

## Expected result

x and y property should delete from timeline

## More details

**Affected browsers/platforms:** Chrome only. No crash on desktop version

**First affected release:** worked in r199 but broke in r200

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r200/components/editors/layoutView/layoutView.js, line 1, col 65868
Message: Uncaught TypeError: Cannot read property 'ǃiA' of undefined
Stack: TypeError: Cannot read property 'ǃiA' of undefined at t.ǃiJ (https://editor.construct.net/r200/components/editors/layoutView/layoutView.js:1:65868) at t.ǃwH (https://editor.construct.net/r200/components/editors/layoutView/layoutView.js:1:62967) at Array. (https://editor.construct.net/r200/components/editors/layoutView/layoutView.js:1:60115) at Object.ǃbDa (https://editor.construct.net/r200/main.js:2:199877) at Object.dispatchEvent (https://editor.construct.net/r200/main.js:2:197489) at Object.ǃqu (https://editor.construct.net/r200/components/editors/layoutView/layoutView.js:1:7519) at https://editor.construct.net/r200/components/editors/layoutView/layoutView.js:1:1894
Construct 3 version: r200
URL: https://editor.construct.net/r200/
Date: Fri May 22 2020 10:37:15 GMT+0530 (India Standard Time)
Uptime: 188.7 s

Platform information
Browser: Chrome
Browser version: 83.0.4103.61
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
C3 release: r200 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
