### ISSUE TITLE
Touch.Y is wrong on iPhone's Safari when the keyboard is displayed on the screen

### ISSUE THREAD

**Issue by jtiret** [Scirra/Construct-3-bugs#3877]
## Problem description

On iPhone Safari, the value returned by Touch.Y is wrong when the keyboard in on the screen (basically when a text input is focused). The Touch.Y value seems to be subtracted by the keyboard's height. For example, if I touch the top-left corner of the screen it will return something like 0;-120 instead of 0;0 when the keyboard is visible on the screen.

## Attach a .c3p

See this minimal project that reproduces the problem: 
[TouchXY.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4668024/TouchXY.c3p.zip)

## Steps to reproduce

1. Listened for the trigger "any touch started" and display the Touch.X and Touch.Y on the screen
2. Put a text input on the layout
3. Preview the project on iPhone Safari
4. Touch the input to field to have the keyboard appear
5. Then, touch the top-left corner of the screen in order to trigger "any touch started"

## Observed result

You see that Touch.Y is equal to something close to -120.

## Expected result

Touch.Y should be closed to 0.

## More details
I tested on Safari iPhone.
The -120 value actually seems to be the height of the keyboard. The value seems to be the one that we would get if we touched the exact same place on the screen if the keyboard wasn't here.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next release.

**Comment by jtiret** [comment]
Thanks @AshleyScirra
