### ISSUE TITLE
C3 Desktop Standalone Error Message Caused By Small Window Size: Please Restart!

### ISSUE THREAD

**Issue by 234626** [Scirra/Construct-3-bugs#3878]
## Problem description

Upon launching the standalone desktop version of Construct 3, sometimes the window automatically resizes incredibly small causing an error message caused by one of the pane sizes to be <= 0 pixels. Upon pressing the restart button the same bug occurs, you then need to maximise the window and restart again to prevent it from happening again, from there you can resize the window at will without an error. Sometimes though, the same error can occur again without resizing manually.

## Attach a .c3p

This error is not related to a project, rather C3 itself.

## Steps to reproduce

This bug was produced on Windows 10 64bit on a 24 and 28" monitor and can occur on any of Construct 3s' themes. The only way to accurately produce the error continuously that I have found is to do the steps listed below, however this error does occur randomly without resizing the window first.

1. Download and run the latest beta or stable standalone version from here: [LINK!](https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-nw-js-desktop-app-131317).
2. Run the application and resize it to almost as small as possible.
3. Close and re-open.
4. The application should now show an error message displaying this error in greater detail:

Error report information
Type: assertion failure
**Message: Maximum pane size is <= 0**

5. Steps to fix temporarily:
  a. Maximise the window using the maximise window button on the top-right of Construct 3.
  b. Restart.
  c. Grab the window to de-maximise it, let it go and resize in a large fashion without fully maximising. 
  d. Opening a project will display the left pane full extended across the screen, you'll need to re-adjust it to an appropriate size and re-add the ProjectPane. 
  note: Restarting from here generally allows you to keep the previously sized window.

## More details

Seen to occur in r200. I don't recall it happening in earlier versions but that doesn't necessarily mean anything.

## Unsuccessful Attempted Fixes
Attempt 1. 
Editing a theme via CSS and changing either/both of the [dockleft]/[dockright] {} pane AND/OR the projectBar/propertiesBar {} with "max-size: 500px;" does not work.

Attempt 2.
#propertiesBar {
  min-width: 200px !important;
}
#projectBar {
  min-width: 200px !important;
}
#midPane {
  min-width: 100px !important;
}
#startPage {
  min-width: 100px !important;
}

## System details

Error report information
Type: assertion failure
Message: Maximum pane size is <= 0
Stack: Error at Function.ǃbHG (https://editor.construct.net/r200/main.js:2:126929) at e (https://editor.construct.net/r200/main.js:2:83836) at https://editor.construct.net/r200/main.js:2:84166 at Object.ǃbiB (https://editor.construct.net/r200/main.js:2:340343) at Object.ǃYC (https://editor.construct.net/r200/main.js:2:354962) at Function.ǃbiF (https://editor.construct.net/r200/main.js:2:342798) at Function.ǃEUp (https://editor.construct.net/r200/main.js:2:341664) at Object.ǃKJm (https://editor.construct.net/r200/main.js:210:80306) at Object.ǃBKA (https://editor.construct.net/r200/main.js:210:77535) at async o (https://editor.construct.net/r200/main.js:210:136961)
Construct 3 version: r200
URL: https://editor.construct.net/r200/
Date: Sat May 23 2020 17:41:50 GMT+0800 (Australian Western Standard Time)
Uptime: 0.5 s

Platform information
Browser: NW.js
Browser version: 0.44.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.0 (like Chrome/80.0.3987.87)
C3 release: r200 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

**Comment by AshleyScirra** [comment]
Have you tested Chrome? Does it reproduce there? Or is it specific to the desktop build only?

**Comment by 234626** [comment]
> Have you tested Chrome? Does it reproduce there? Or is it specific to the desktop build only?

It only seems to be a desktop only issue, I don't think the browser windows can get that small to allow it to happen.

Bare with me, I'm new to all of this.

**Comment by AshleyScirra** [comment]
I think the easiest way to solve this is just to impose a minimum window size. Can you try these updated versions and check it solves the problem?

[c3-nwjs-package-stable.zip](https://github.com/Scirra/Construct-3-bugs/files/4676975/c3-nwjs-package-stable.zip)
[c3-nwjs-package-beta.zip](https://github.com/Scirra/Construct-3-bugs/files/4676976/c3-nwjs-package-beta.zip)

**Comment by 234626** [comment]
> I think the easiest way to solve this is just to impose a minimum window size. Can you try these updated versions and check it solves the problem?
> 
> [c3-nwjs-package-stable.zip](https://github.com/Scirra/Construct-3-bugs/files/4676975/c3-nwjs-package-stable.zip)
> [c3-nwjs-package-beta.zip](https://github.com/Scirra/Construct-3-bugs/files/4676976/c3-nwjs-package-beta.zip)

Well done Ashley, I cannot reproduce the issue on either version stable or beta after several attempts, I think it is safe to say it is fixed. Thank you. -Dreamer

**Comment by AshleyScirra** [comment]
Thanks for confirming, updated the server with these downloads.
