### ISSUE TITLE
[Whitelist] Tapsell Ad Service

### ISSUE THREAD

**Issue by miladesign** [Scirra/Construct-3-bugs#3882]
Hi,
I would like to request to add the `tapsell-cordova-plugin` plugin.

thanks.

**Comment by mostafanastary** [comment]
@AshleyScirra , How long do you think it will take to do this? please let us know.

**Comment by mostafanastary** [comment]
@AshleyScirra, After 20 days , this request is open! please add it to build server.

**Comment by mostafanastary** [comment]
@AshleyScirra, Add this to build server Please!

**Comment by AshleyScirra** [comment]
Added `tapsell-cordova-plugin@4.5.0` to the build service.

Please note every cordova plugin request goes through a full security review, and we're a small team, so please allow several weeks for requests to be approved.
