### ISSUE TITLE
Local Storage File Corruption

### ISSUE THREAD

**Issue by hammanneric6** [Scirra/Construct-3-bugs#3883]
## Problem description

The game I am creating uses the Local Storage object to keep track of save data.  The issue I am running across happens very infrequently, but I've seen it occur several times, twice to myself.  And by infrequent I mean literally the game has been downloaded nearly 10,000 times and this issue has been reported like 3 times.  Not the best statistic, but I'm at a loss here.

In short when the game saves data it sets an item called "saveData" which consists of a dictionary made into a JSON.  When the bug occurs it manifests on the load screen.  The game has 3 save slots, which all appear blank when the bug happens.  Normally they should fill in data based on the local storage data that is loaded in prior.

To cover my bases yes I am aware that local storage is asynchronous, but the data is loaded on a previous layout and there is a promise in place where the game doesn't advance until the local storage data has finished loading.

Normally, I wouldn't post a bug report here with such a vague request.  I'm basically doing this because I have no other options.  I don't have an example capx because I can't even replicate it in my own game.  In any other situation I'd say it was my code but this is such a simple function that I don't know how it could be.  

I'm hoping the severity of a problem like this will warrant some attention despite the lack of an example.  Instead of a capx I'm posting a drive link to something else.  The most recent person to encounter the error was kind enough to send me their save data.  I didn't design C3 so I can't be certain, but some file monitoring as the game saves and it seems to point to these files as the local storage files.  I can't open the .ldb files myself because I don't have microsoft access.

My current running theory is that something got corrupted, which causes the files to simply not load, but I have no way to verify it.  I did ask the user if they closed the game as it was saving and they claimed that they did not for what it is worth.  Although it seems like saving takes less than a second, even trying to break it I seem to be unable to close the game as it's saving.

## Attach a .c3p

The files linked come from the game's directory (Verdant Village is the name of the game): C:\Users\*USERNAME*\AppData\Local\VerdantVillage\User Data\Default\IndexedDB\chrome-extension_eedajaekaphbiebanmcgeooghfcngago_0.indexeddb.leveldb

https://drive.google.com/open?id=1xilCXGeb4sZC1Qlyb_v3--7jToAyU79T

## Steps to reproduce

I don't have any steps.

## Observed result

On a rare occasion save files will not appear in the load screen.

## Expected result

Save files should always appear.

## More details

**Affected browsers/platforms:** 

The game is being run in NWjs.  However I've seen this occur in both the exported NWjs version as well as just the preview version of the game launched from C3 if that helps.

**First affected release:** The observed cases have been few and far between I honestly have no idea when it started.

## System details

Platform information
Browser: Chrome
Browser version: 81.0.4044.138
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
C3 release: r200 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 4 gb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
I'm afraid there's nothing we can do unless you follow the bug report guidelines. They are there because we need that information to help you. The first thing we do when investigating a report is follow the steps to reproduce and try to observe the problem; if these are missing there is nothing to be done.

Further there isn't yet any specific evidence identifying that Construct is actually the source of the problem. It could be something else. Also the leveldb database files are managed by the browser engine, not Construct, so we aren't involved in the management of those files.

I'm afraid you'll need to try to track down a more reliable way to reproduce the problem. With storage the most common kind of error is that it fails due to the storage quota running out. You might just need to handle errors.
