### ISSUE TITLE
On iPadOS, Construct 3 side windows occasionally get stuck open. 

### ISSUE THREAD

**Issue by pMatt1988** [Scirra/Construct-3-bugs#3884]
## Problem description

When using my iPad in the Safari browser, occasionally the side panes get open. The only fix I’ve found is to refresh the browser. When the left pane is stuck open, I have no choice but to wait for the autosave before I can refresh as the menu and save button are obscured. 

I am using the default theme (no theme)

## Steps to reproduce

This happens randomly and I haven’t found a way to reproduce. 

## More details

**Affected browsers/platforms:** 
Safari, iOS on the iPad Pro 2020 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 13.1
Browser engine: WebKit
Browser architecture: (unknown)
Context: webapp
Operating system: iOS
Operating system version: 13.1
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 511
Extensions:

EXT_texture_filter_anisotropic
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_lose_context
WEBGL_debug_renderer_info
Audio information
System sample rate: 48000 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by pMatt1988** [comment]
Construct reported the wrong version/os. It’s 13.4.1 of iPadOS

**Comment by AshleyScirra** [comment]
Random issues are very difficult to investigate. Can you find any way to reliably reproduce the problem?

Also it's designed so that at any time you can swipe a pane back again. Are you sure you can't close the pane again by swiping it back to the side?

**Comment by pMatt1988** [comment]
Oh yes. I’m quite sure...  I will update as I find out more but I wanted to get it up here in case anyone else had this problem and it was simple user error that I could fix myself.

**Comment by pMatt1988** [comment]
In trying to find a way to reproduce this glitch reliably, I did find another but. On Safari on iPad, if you open the right side panel in the sprite editor (animation list and frame list) and slide out to change the visible panel, it scrolls over to show both. What is very strange about this bug is that it ONLY happens when I run Construct from my home screen. Running it in a tab on Safari I don’t get this issue.

**Comment by pMatt1988** [comment]
[![Video](http://img.youtube.com/vi/mSV2ZXnOd6U/0.jpg)](http://www.youtube.com/watch?v=mSV2ZXnOd6U "Video")

This video was taken on a fresh project. Safari, iPad OS 13.5

**Comment by pMatt1988** [comment]
An update on the issue outlined in the comment above, when hiding the url bar in Safari, I experience this same issue.

**Comment by AshleyScirra** [comment]
Have you only observed this in the Animations Editor, or have you seen it in other parts of the editor? The Animations Editor uses its own implementation of the pane swiping, so this affects which part of the code may be affected.

**Comment by AshleyScirra** [comment]
I could only reproduce this in the animations editor, but there was too much scrolling going on in the rest of the editor too. I think I found some quirks about iPadOS that might have been affecting this, it should be better in the next release.

**Comment by AshleyScirra** [comment]
r202 is now out, can you check again there?

**Comment by pMatt1988** [comment]
I am at work so I did just a really quick test, but it’s looking good! When
I slide out the panes, it doesn’t overshoot and the animation editor seems
to be work*ing correctly. *

**Comment by pMatt1988** [comment]
After messing around in the editor a bit more, I’m not getting panes stuck
open. The problem is tentatively solved for me.

**Comment by AshleyScirra** [comment]
OK, thanks for confirming.
