### ISSUE TITLE
Cloud save black screen on Google Chrome Canary

### ISSUE THREAD

**Issue by jogosgratispro** [Scirra/Construct-3-bugs#3885]
I get a black screen when I try to save or open using the Cloud option on Google Chrome Canary

It happens to either a new file or a working game even with the examples provided.

**Here is how to reproduce the error:**

Open a new file
Menu > Projects > Save as > Cloud save

OR

Click on the CLOUD button on the Start page

**Here is what I see**

<img src="https://i.imgur.com/ytYfFYG.png" />

**Here is what I should see**

<img src="https://i.imgur.com/Y9vbFIX.png" />

## More details

When I open browser's console. I see this error for some reason
main.js:2 Error while parsing the 'sandbox' attribute: 'allow-storage-access-by-user-activation' is an invalid sandbox flag.

<img src="https://i.imgur.com/WEPFain.png" />

**Affected browsers/platforms:** 

Chrome Canary Version 85.0.4154.0 (Official Build) canary (64-bit)

**First affected release:**  r197.2 

## System details

<details><summary>View details</summary>

Windows 7 Ultimate

</details>

**Comment by AshleyScirra** [comment]
Chrome Canary is frequently glitchy because it is not well tested. Please don't report bugs that only happen in Canary.
