### ISSUE TITLE
(Editor / Tilemap Bar)  - Shift Key to select patch stops working after preview (Now reproducible!)

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#3886]
## Problem description

I have figured out how to reproduce the bug in the closed report #3711 which states:

"When editing a tilemap, holding the [Shift] key temporarily switches to the "select a patch from the tilemap" tool. For whatever reason, this consistently stops working after ~10 minutes of editing tilemaps."

It turns out it's due to previewing the project while a tilemap is being edited (i.e. tilemap object selected, pencil tool active)

## Attach a .c3p

[tilemapPickerBug.zip](https://github.com/Scirra/Construct-3-bugs/files/4678678/tilemapPickerBug.zip)

## Steps to reproduce

1. Left click on the tilemap object that is pre-placed in the layout.
2. In the tilemap bar, select the pencil tool.
3. Press F5 to preview the project.
4. Close the preview.
5. Repeatedly tap [Shift] to see if the "select a patch from the tilemap" tool becomes activated.
5b. If it does, repeat steps 3 and 4.

## Observed result

Holding the [Shift] key to temporarily switch to the "select a patch from the tilemap" tool stops working after the preview is opened and closed.

## Expected result

Holding the [Shift] key to temporarily switch to the "select a patch from the tilemap" tool should continue working.

## More details

-I've recorded a video of the bug occuring by following the steps above. You can hear me smacking the shift key, yet the corresponding tool is never selected.
[2020-05-25 14-53-05.zip](https://github.com/Scirra/Construct-3-bugs/files/4678693/2020-05-25.14-53-05.zip)
-The only way to fix it is by restarting the editor. Closing & reopening the project does not work.

**Affected browsers/platforms:** Chrome

**First affected release:** All releases

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.44.6
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.6 (like Chrome/80.0.3987.162)
C3 release: r201 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 806 gb
Storage usage (approx): 118 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
I was able to reproduce it this time, it seems it only happens when you preview by pressing F5, otherwise it works fine. This is very strange, but it's something.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
