### ISSUE TITLE
DrawingCanvas' getImagePixelData() flips the Y axis of the ImageData.

### ISSUE THREAD

**Issue by whistlegraph** [Scirra/Construct-3-bugs#3888]
## Problem description

When writing pixels to a DrawingCanvas using the scripting API, the imageData is flipped on the Y axis which makes it annoying to combine drawing commands with scripted pixel manipulation. (The image needs to be flipped back every time.)

## Attach a .c3p
[DrawingCanvas.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4686421/DrawingCanvas.c3p.zip)

## Steps to reproduce

Please see the sample project and screenshots.

<img width="1244" alt="Screen Shot 2020-05-26 at 9 16 07 PM" src="https://user-images.githubusercontent.com/3620017/82977529-015d6f00-9f97-11ea-8036-2302442cc910.png">

## Observed result

The image is flipped on the Y axis.

## Expected result

The pixel data should be oriented to match the coordinate system of the DrawingCanvas actions.

## More details

**Affected browsers/platforms:** 

macOS / Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 81.0.4044.138
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 574 gb
Storage usage (approx): 86 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Getting the Y direction right in WebGL is surprisingly hard! It does some things in the opposite direction. Thanks for spotting this, should be fixed in the next release.

**Comment by whistlegraph** [comment]
Yeah I've dealt / worked around this problem countless times when writing WebGL calls! Thanks for the patch.

**Comment by whistlegraph** [comment]
Hi, I pushed out an update to my app using Construct r204 and I'm seeing new issues with y-axis flipping of textures, specifically in Desktop and Mobile **Safari**. 

I don't experience these issues in Chrome. 

I also can't reproduce these issues in older builds of my app pre-204, so I have a feeling this fix may have caused a regression or have had some unintended side effects involving a race condition. Some of my Sprite objects with animations are rendering incorrectly due to y-flipping, and the behavior is not consistent and hard to pin down in an isolated c3p to attach here. But I'm working on it!

**Comment by whistlegraph** [comment]
> Getting the Y direction right in WebGL is surprisingly hard! It does some things in the opposite direction. Thanks for spotting this, should be fixed in the next release.

I was able to workaround the regression by running these actions on some dummy objects after each getImagePixelData() manipulation:

![Uploading Screen Shot 2020-06-19 at 6.36.10 PM.png…]()
