### ISSUE TITLE
Editor crashes after I use the "go to" option with bookmarks after changing the bookmarked event position

### ISSUE THREAD

**Issue by cb130felix** [Scirra/Construct-3-bugs#3889]
#  Problem description

Pretty much the tittle

## Attach a .c3p

You'll need to replicate it yourself

## Steps to reproduce

1. Create two diferent event blocks in a event sheet
2. bookmark one of the events
3. Change the position of the bookmarked block
4. In the bookmark window, use the "go to" option to go to the bookmarked event
5. See editor crashing

## Observed result

Editor crashed after using "go to" option to changed bookmarked event position

## Expected result

For the editor not to crash

## More details

`Error report information
Type: assertion failure
Message: event sheet has no bookmarks
Stack: Error at Function.d.ǃTVM (https://editor.construct.net/r201/main.js:2:126674) at e (https://editor.construct.net/r201/main.js:2:83860) at window.assert (https://editor.construct.net/r201/main.js:2:84211) at d.ǃXW (https://editor.construct.net/r201/components/editors/eventSheetView/eventSheetView.js:1:12185) at https://editor.construct.net/r201/components/bars/bookmarksBar/bookmarksBar.js:1:1862
Construct 3 version: r201
URL: https://editor.construct.net/r201/
Date: Thu May 28 2020 10:40:07 GMT-0300 (Brasilia Standard Time)
Uptime: 38.5 s

Platform information
Browser: Chrome
Browser version: 81.0.4044.138
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
C3 release: r201 β
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2`

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
