### ISSUE TITLE
Editor color selection

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#3890]
## Problem description

The editor color selector requires the user to hit the enter key when done.

## Attach a .c3p

[enter the drag-on color.zip](https://github.com/Scirra/Construct-3-bugs/files/4697458/enter.the.drag-on.color.zip)

## Steps to reproduce

1.Open file in editor
2.Click the Sprite to select it
3.Click the Color Selector in object properties
4.Click a color
5.Click outside the selector

## Observed result

The selected color is not saved

## Expected result

The selected color should be used.

## More details

The selector should use the last selected color, and not require the enter key

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The system details were not included. I assume you are using Chrome 83, which introduced a new kind of color picker control which works differently. It also does not require pressing enter; it's just if you click something which shows different properties, it doesn't apply the change - e.g. clicking in the properties bar still works correctly. This required some updates to our code to handle it. I think it should be working correctly in the next release.

**Comment by pigmalien** [comment]
Sorry, yes, I'm on 83.
Thanks. Looking forword to it.
