### ISSUE TITLE
Can't change deceleration in JavaScript

### ISSUE THREAD

**Issue by EydiavHamri** [Scirra/Construct-3-bugs#3891]
#1932  Problem description
When scripting, somehow I'm not allowed change deceleration value of platform behavior.

## Attach a .c3p
https://1drv.ms/u/s!Av0tQkU7g1Ynm6QFEHcF3Bgsl0Zvpw?e=NkrbWE

## Steps to reproduce
1. Run game in debugger.
2. Hold space to change acceleration and deceleration to 0 (but only acceleration changes)
3. Release space to change to 1 (again only acceleration changes)

## Observed result
Holding space bar changes acceleration to 0. Releasing space bar changes acceleration to 1.

## Expected result
Holding space bar changes acceleration AND deceleration to 0. Releasing space bar changes acceleration AND deceleration to 1.

## More details
I wrote a simple platformer game in JavaScript and noticed I could never change deceleration. I don't see how the JavaScript is wrong.

## System details
Construct 3 release r201 beta
Tested on Chrome Edge and Firefox.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
