### ISSUE TITLE
timeline crash

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3892]
## Problem description

I wanted to try the timeline feature but when I try to add an instance to the timeline, it crashes.

## Steps to reproduce

1. Create a timeline
2. Add an instance to the timeline.

## More details

**Affected browsers/platforms:**  Chrome PWA

**First affected release:**  r201

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃwh' of undefined @ TypeError: Cannot read property 'ǃwh' of undefined at Object.ǃhzu (https://editor.construct.net/r201/projectResources.js:1:543040) at Function.ǃhOc (https://editor.construct.net/r201/projectResources.js:1:546396) at n.ǃhOy (https://editor.construct.net/r201/projectResources.js:1:504994) at n.ǃhAg (https://editor.construct.net/r201/projectResources.js:1:503638) at n.ǃhjm (https://editor.construct.net/r201/projectResources.js:1:501488) at new n (https://editor.construct.net/r201/projectResources.js:1:494147) at Function.d.ǃF (https://editor.construct.net/r201/main.js:2:129085) at o.ǃhAh (https://editor.construct.net/r201/projectResources.js:1:465225) at o.ǃeLp (https://editor.construct.net/r201/projectResources.js:1:465436) at https://editor.construct.net/r201/components/bars/timelineBar/timelineBar.js:1:12798
Stack: TypeError: Cannot read property 'ǃwh' of undefined at Object.ǃhzu (https://editor.construct.net/r201/projectResources.js:1:543040) at Function.ǃhOc (https://editor.construct.net/r201/projectResources.js:1:546396) at n.ǃhOy (https://editor.construct.net/r201/projectResources.js:1:504994) at n.ǃhAg (https://editor.construct.net/r201/projectResources.js:1:503638) at n.ǃhjm (https://editor.construct.net/r201/projectResources.js:1:501488) at new n (https://editor.construct.net/r201/projectResources.js:1:494147) at Function.d.ǃF (https://editor.construct.net/r201/main.js:2:129085) at o.ǃhAh (https://editor.construct.net/r201/projectResources.js:1:465225) at o.ǃeLp (https://editor.construct.net/r201/projectResources.js:1:465436) at https://editor.construct.net/r201/components/bars/timelineBar/timelineBar.js:1:12798
Construct 3 version: r201
URL: https://editor.construct.net/r201/
Date: Fri May 29 2020 02:25:29 GMT+0300 (GMT+03:00)
Uptime: 28.5 s

Platform information
Browser: Chrome
Browser version: 83.0.4103.61
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
C3 release: r201 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Mentioned in the comments of #3876. Already fixed.
