### ISSUE TITLE
Game jerky and unplayable with new interface

### ISSUE THREAD

**Issue by ziggyhere** [Scirra/Construct-3-bugs#3894]
![New Interface Slider Blue](https://user-images.githubusercontent.com/61274109/83243687-dc544080-a1d0-11ea-9f11-33873bd8d0ac.png)

A few days back I noticed C3 had a new interface changes (the progress bar slider has a bright blue colour with rounded edges which was previously rectangular and low dim blue with sharp edges with scaled lines within. Also the tick boxes at the Layer section is now bright blue where previously was just a simple box (as attached in the attached image). It was then that my game started becoming jerky and experienced significant drop in fps to a point it is no longer playable. Initially I thought it was my computer problem. So I tested it in another computer that is still running the old interface without the bright blue stuffs. I know for a fact that the new interface or whatever new changes is causing this problem because I have been working on this game for several months without such problem. The issue came when the bright blue interface started. And the issue is not about my computer because the same problem appeared when using separate computers. Kindly assist on this matter. Much appreciated.

**Comment by rilem** [comment]
I came to see if there was anyone else experiencing slowdowns. Ticking the Use Worker option in the project settings seemed to solve the issue for me.

**Comment by ziggyhere** [comment]
Nope. The screen is black and nothing happens after ticking Use worker.

**Comment by ziggyhere** [comment]
Okay, the black screen was temporary. Took about a minute before it actually starts. The issue seems to be solved at this moment. Many thanks for the speedy solution.

**Comment by AshleyScirra** [comment]
The change in the UI controls was made in the Chrome 83 update. It's not a change we made in Construct. It should have nothing to do with runtime performance. You also need to follow the bug report guidelines otherwise it's impossible for us to investigate.
