### ISSUE TITLE
Physics bug when velocity is 50 or less.

### ISSUE THREAD

**Issue by awb11** [Scirra/Construct-3-bugs#3895]
## Problem description

Physics does not work properly when velocity is 50 or less. In the C3p the ball should bounce of the red immovable wall. When the velocity of the ball is 51+ it bounces properly. 

## Attach a .c3p

https://drive.google.com/file/d/1H82iK5b5s59kSNVkqslGgUUlns6QTNOM/view?usp=sharing

## Steps to reproduce

Preview the project. 

## Observed result

All 3 balls stick to the Red Wall if velocity is under 50. 

## Expected result

All 3 balls should bounce off the Red Wall.

## More details

If the Velocity is 51+ they bounce correctly. If Velocity is under 50 than they do not bounce at all.

This bug makes it impossible to create even a simple billiards game.

This affects C3 runtime, C2 Runtime and Construct 2. Should I report this bug in Construct 2 forum as well?

**Affected browsers/platforms:** 

Chrome/ Firefox

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The collision is handled entirely by the physics engine (Box2D), not Construct, so this is out of our control.

It looks like you have an unrealistic setup: all the objects have a friction of 0, meaning they have even less friction than an incredibly slippery icy surface. No real-world objects would have such properties, especially not a billiards table. If you set the friction of the ball and the wall to 0.3, it does bounce off. So it looks like you've just got an unrealistic physics setup.

**Comment by awb11** [comment]
@AshleyScirra If you select Collision Mask to Circle even with friction 0.3 the problem persists. Something weird is going on there.

**Comment by AshleyScirra** [comment]
I'm afraid as I mentioned, this is how the physics engine handles the collision. Box2D is widely used across the industry in many games, I doubt it's a problem with the physics engine itself. There's probably a combination of settings or adjustments that will get a better result.
