### ISSUE TITLE
Construct 3 Editor Crashes when Adding Objects to a Timeline (r201)

### ISSUE THREAD

**Issue by Mr-Now** [Scirra/Construct-3-bugs#3896]
## Problem description

Currently adding any object to a timeline is causing me to get an "Oops, something went wrong" red screen. 

## Steps to reproduce

New timeline:
1. Create new timeline under Timeline folder in Project bar.
2. Open new timeline
3. Hit "+" to add a new object
4. Select object from the popup

NOTE: This also happened repeating these steps but adding an object to an existing timeline. 

## Observed result

Red screen. "Oops, something went wrong" with diagnostics. Forced restart of Construct.

## Expected result

That my object would be added to my new timeline.

**## PASTING ERROR REPORT TEXT BELOW**

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'ǃwh' of undefined @ TypeError: Cannot read property 'ǃwh' of undefined at Object.ǃhzu (https://editor.construct.net/r201/projectResources.js:1:543040) at Function.ǃhOc (https://editor.construct.net/r201/projectResources.js:1:546396) at n.ǃhOy (https://editor.construct.net/r201/projectResources.js:1:504994) at n.ǃhAg (https://editor.construct.net/r201/projectResources.js:1:503638) at n.ǃhjm (https://editor.construct.net/r201/projectResources.js:1:501488) at new n (https://editor.construct.net/r201/projectResources.js:1:494147) at Function.d.ǃF (https://editor.construct.net/r201/main.js:2:129085) at o.ǃhAh (https://editor.construct.net/r201/projectResources.js:1:465225) at o.ǃeLp (https://editor.construct.net/r201/projectResources.js:1:465436) at https://editor.construct.net/r201/components/bars/timelineBar/timelineBar.js:1:12798
Stack: TypeError: Cannot read property 'ǃwh' of undefined at Object.ǃhzu (https://editor.construct.net/r201/projectResources.js:1:543040) at Function.ǃhOc (https://editor.construct.net/r201/projectResources.js:1:546396) at n.ǃhOy (https://editor.construct.net/r201/projectResources.js:1:504994) at n.ǃhAg (https://editor.construct.net/r201/projectResources.js:1:503638) at n.ǃhjm (https://editor.construct.net/r201/projectResources.js:1:501488) at new n (https://editor.construct.net/r201/projectResources.js:1:494147) at Function.d.ǃF (https://editor.construct.net/r201/main.js:2:129085) at o.ǃhAh (https://editor.construct.net/r201/projectResources.js:1:465225) at o.ǃeLp (https://editor.construct.net/r201/projectResources.js:1:465436) at https://editor.construct.net/r201/components/bars/timelineBar/timelineBar.js:1:12798
Construct 3 version: r201
URL: https://editor.construct.net/r201/
Date: Thu May 28 2020 19:49:44 GMT-0400 (Eastern Daylight Time)
Uptime: 185.7 s

Platform information
Browser: Chrome
Browser version: 81.0.4044.138
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
C3 release: r201 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

**Comment by DiegoScirra** [comment]
This issue was brought up in the comments of #3876 and has already been fixed.
