### ISSUE TITLE
Multiplayer: wrong objects synchronization

### ISSUE THREAD

**Issue by jtiret** [Scirra/Construct-3-bugs#3897]
## Problem description

When connecting to a room as peer, then leaving this room to join another room as a peer, the synchronization of the objects can be wrong for a few seconds, putting back objects that were synchronized with the previous peer.

You can see a video of the problem attached below:
[Screen Recording 2020-05-29 at 19.07.16.mov.zip](https://github.com/Scirra/Construct-3-bugs/files/4703245/Screen.Recording.2020-05-29.at.19.07.16.mov.zip)

I have 3 instances of the same project:
- One which connects as HOST in the first room/layout
- One which connects as HOST in the second room/layout
- The last one which connects as PEER in the first room/layout, then in the second room/layout

Each layout has a dedicated room (apart from the Start Screen).

The first room synchronizes 6 orange squares and the second one only one square.
When going to the first room as a peer, 6 orange squares appear (the blink is normal because it's the delay for syncing the objects).

When leaving (disconnecting from) the first room, then connecting to the second one, you can notice that 6 squares appear briefly, for a few seconds, then disappear. They are in no way created by the peer and apparently lasted from the previous connection. You can also notice some weird/unstable movements in the squares.

## Attach a .c3p
[MultiplayerIssue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4703244/MultiplayerIssue.c3p.zip)

## Steps to reproduce

1. Open the project
2. Launch 3 instances (by clicking on "play" while pressing ALT)
3. On the first instance, join room 1
4. On the second instance, join room 2
5. On the third instance, join room 1, wait 2 seconds, then leave the room
6. Join the room 2

## Observed result

6 squares appear briefly, with unexpected movements.

## Expected result

They shouldn't appear. Sometimes it's necessary to repeat these actions to observe the issue.

## More details

**Affected browsers/platforms:** 

Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**First affected release:** 

## System details

<details><summary>View details</summary>

Chrome Version 83.0.4103.61 (Official Build) (64-bit)

</details>

**Comment by jtiret** [comment]
Hi there ( @AshleyScirra @DiegoScirra @TomGullen )
Have you been able to reproduce the issue?
Do you have any clue or at least a workaround to handle this by the time it get fixed?

**Comment by AshleyScirra** [comment]
Fixed for next beta.
