### ISSUE TITLE
Adaptive Icons cause building an Android APK to fail

### ISSUE THREAD

**Issue by TetroniMike** [Scirra/Construct-3-bugs#3898]
## Problem description

Setting an icon file Purpose property to "Adaptive foreground" or "Adaptive background" causes building an APK to fail.

## Attach a .c3p
[AdaptiveIconTest.zip](https://github.com/Scirra/Construct-3-bugs/files/4703250/AdaptiveIconTest.zip)

## Steps to reproduce

1. Open the test .c3p file
2. Menu -> Project -> Export -> Android -> Debug APK (or other APK build)
3. Click Next, then wait

## Observed result

APK build fails, please see attached error log.
[AdaptiveIcon_ExportErrorLog.txt](https://github.com/Scirra/Construct-3-bugs/files/4703262/AdaptiveIcon_ExportErrorLog.txt)

## Expected result

I expect a working APK to be exported without error.

## More details

Removing the Adaptive icon files or changing their Purpose to something else causes the APK to export properly.

**Affected browsers/platforms:** Android

**First affected release:** Beta R201

## System details

Error log attached above, platform information below.

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.61
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
C3 release: r201 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 94 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Huh, this is weird. I tested it at the time and verified it worked. The error seems to be in the Cordova CLI rather than anything to do with Construct, since a separate CLI build shows the same error log. I guess it's a Cordova bug, I'll try dig in to it and see what's going on.

**Comment by AshleyScirra** [comment]
Since it looks like a Cordova bug I filed this issue with them: https://github.com/apache/cordova-cli/issues/506

I'll follow it up there.
