### ISSUE TITLE
can't change the color of tabs, groups or comments

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3899]
## Problem description

I think it's because of the new color picker that comes with chrome 83 before that we were using the windows' default color picker.

## Steps to reproduce

1. Try to change the color of tabs, groups or comments

## More details

**Affected browsers/platforms:**  Chrome 83

**First affected release:**  201

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is related to the new color picker control in Chrome 83 and was fixed as part of #3890.
