### ISSUE TITLE
Animation Properties: "Repeat to" Revert Unacceptable Number Bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#39]
## Problem description & Steps to reproduce

When keying in a frame index number that the animation does not have in the "Repeat to" box, it will not revert until you close the animations editor(Sprite editor) window.

## Expected result

Revert the number on key enter. So that user will know instantly if they made a mistake.

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed. This is now working in the same way as the properties bar.

When a value goes below or over it's range, it is clamped to the minimum or maximum respectively.

Will be available in r17.
