### ISSUE TITLE
Cannot open project after undoing - redoing a lot of deleted objects/events

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#390]
## Problem description

I was deleting a lot of content from a big project of mine in order to send it and file a bug report about a crash with moving a function having local variables outside of the code block containing the vars....anyway it seems that whenever I want to strip down my project to file the bug report, another bug appears.

I've started deleting things and I made a backup before triggering the bug, backup which now I cannot open.

![image](https://cloud.githubusercontent.com/assets/7268697/26562571/1404431a-44d0-11e7-8ae1-e3dcacc24e1b.png)

I used undo a lot and redo a lot, then made the backup.
Is this worth investigating? I got a lot of backups so it's not a problem for me.

## Attach a .c3p

I've put it in the dropbox folder I've shared with you. It's _Bug_CannotOpenProject.c3p_

## Steps to reproduce

1. get the project
2. try to open it
3.

## Observed result

Can't.

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 23 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
We need steps to reproduce the problem in the first place otherwise there is little we can do other than recover the project. Already-broken projects are not enough information to fix a bug from.

I can't see where you've shared a Dropbox folder with us. I would try to recover the project if you send it to me. Send it direct to ashley@scirra.com if you want me to take a look.

**Comment by JeFawk** [comment]
It's fine, I used a backup. I tried reproducing it but it didn't work, thanks anyway though!
