### ISSUE TITLE
Canvas Plugin Pin to Object Angle stopped working in r201

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#3901]
## Problem description

Plugin canvas attached via Pin (Angle) to the object ,stopped setting the angle of the object in r201. In the r200 version, this worked.
https://drive.google.com/file/d/12sMxUEnRa319FPQIwYBAQBX5wqqVqyCj/view?usp=sharing

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It sounds like you were relying on a bug fixed in r201:

> Can no longer use behaviors to force non-rotatable objects to rotate 

However you did not follow the bug report guidelines so this is impossible to confirm.

**Comment by ibiz3091** [comment]
Whether the set angle function will be added in the Canvas plugin in the future. You have a request for this function https://construct3.ideas.aha.io/ideas/C3-I-1050 , my game is built on turns Layouts.

**Comment by ibiz3091** [comment]
> It sounds like you were relying on a bug fixed in r201:
> 
> > Can no longer use behaviors to force non-rotatable objects to rotate
> 
> However you did not follow the bug report guidelines so this is impossible to confirm.

Whether the set angle function will be added in the Canvas plugin in the future. You have a request for this function https://construct3.ideas.aha.io/ideas/C3-I-1050 , my game is built on turns Layouts.
