### ISSUE TITLE
beta channel won't work while offline

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3902]
## Problem description

I can use the stable version while offline but the beta version won't work. It says "this site can't be reached.".

## Steps to reproduce

1. Open https://editor.construct.net/beta
2. Wait until the offline use popup
3. Disconnect from the wifi and try to open https://editor.construct.net/beta

## More details

**Affected browsers/platforms:**  Chrome 83

**First affected release:**  r201

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
There's a mistake in r201 that accidentally broke offline support, it should be working again in the next beta.
