### ISSUE TITLE
Issue in Animations Editor

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3905]
## Problem description

On Animation editor: select an area with select tool and copy it and in new frame paste it. pasted content and the selection shows on different place.

## Attach a .c3p
no file need

## Steps to reproduce

1. new project
2. add sprite
3. color fill on first frame
4. select any area with selection tool (do not pick from center otherwise you can't notice this error)
5.  create new frame and paste it.

## Observed result

selection and the pasted content are showing on different places
![animation editor](https://user-images.githubusercontent.com/17684135/83424979-d10c4980-a44a-11ea-8245-923536c3dbeb.png)

## Expected result

should on same place

## More details

**Affected browsers/platforms:** Chrome, Windows

**First affected release:** worked in r197 but broke in r198

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Should be fixed in the next beta.
