### ISSUE TITLE
Dragging or Adding sprite to new timeline causes crash

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-3-bugs#3909]
## Problem description
Adding a sprite to a new timeline either by dragging into the timeline panel or using the drop-down menu crashes the editor

## Attach a .c3p
[timelineTest.zip](https://github.com/Scirra/Construct-3-bugs/files/4716293/timelineTest.zip)

## Steps to reproduce
1. Open attached .c3p 
2. Select Timeline "test"
3. Drag the sprite from the layout onto the timeline

## Observed result
Editor crashes

## Expected result
Sprite added to timeline

## More details
Tested in Chrome (desktop editor)

**First affected release:** 
Only tested in latest Beta (r201)

## System details
Crash report:

Error report information
Type: unhandled exception
File: https://editor.construct.net/r201/main.js, line 2, col 129106
Message: Uncaught TypeError: Cannot read property 'ǃwh' of undefined
Stack: TypeError: Cannot read property 'ǃwh' of undefined at Object.ǃhzu (https://editor.construct.net/r201/projectResources.js:1:543040) at Function.ǃhOc (https://editor.construct.net/r201/projectResources.js:1:546396) at n.ǃhOy (https://editor.construct.net/r201/projectResources.js:1:504994) at n.ǃhAg (https://editor.construct.net/r201/projectResources.js:1:503638) at n.ǃhjm (https://editor.construct.net/r201/projectResources.js:1:501488) at new n (https://editor.construct.net/r201/projectResources.js:1:494147) at Function.d.ǃF (https://editor.construct.net/r201/main.js:2:129085) at o.ǃhAh (https://editor.construct.net/r201/projectResources.js:1:465225) at o.ǃeLp (https://editor.construct.net/r201/projectResources.js:1:465436) at window.ǃeEZ.ǃec_ (https://editor.construct.net/r201/components/editors/layoutView/layoutView.js:1:33532)
Construct 3 version: r201
URL: https://editor.construct.net/r201/
Date: Tue Jun 02 2020 10:44:54 GMT+0100 (British Summer Time)
Uptime: 139.3 s

Platform information
Browser: Chrome
Browser version: 83.0.4103.61
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
C3 release: r201 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

**Comment by DiegoScirra** [comment]
This issue was brought up in the comments of #3876 and has already been fixed.
