### ISSUE TITLE
Moving function with local vars crashes C3

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#391]
## Problem description

I've moved a function using local variables outside and was expecting an error that it's using local variables and I can't move it. Instead, it crashed C3.

## Attach a .c3p

[MovingBug_02.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1036724/MovingBug_02.c3p.zip)

![crashbug](https://cloud.githubusercontent.com/assets/7268697/26562794/721a0956-44d2-11e7-8e79-7e67168af6ad.gif)

## Steps to reproduce

1. open the project
2. move the function as the gif shows
3.

## Expected result

An error saying that it can't be moved

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r31/main.js, line 2, col 229181
Message: Uncaught [object Object]
Stack: undefined
Construct 3 version: r31
URL: https://editor.construct.net/index.html
Date: Tue May 30 2017 00:51:24 GMT+0300 (GTB Daylight Time)
Uptime: 78.7 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r31

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by JeFawk** [comment]
Also if you try to save the project and load it you get this.

![image](https://cloud.githubusercontent.com/assets/7268697/26562819/af5b2a3e-44d2-11e7-8d92-8e7cdf2393a6.png)

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in r32.
