### ISSUE TITLE
[R202] Sprites created in code that have not been pre-loaded don't show on screen

### ISSUE THREAD

**Issue by rhg1968** [Scirra/Construct-3-bugs#3910]
## Problem description
When creating a sprite in R202, the sprite won't show on the screen unless the sprite has first been added to layout to pre-load it. 

## Attach a .c3p
[TestSpriteIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/4718782/TestSpriteIssue.zip)

## Steps to reproduce

1. Load the attached C3 project
2. Run it, and the sprite box will not show on the screen
3. Add the Box sprite to the layout outside of the layout
4. Re-run the project and the sprite will now appear

## Observed result
No sprite appears when it's created in script.

## Expected result

The sprite should display on the screen

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Thanks for bringing this up, this should be fixed for the next beta.
