### ISSUE TITLE
[r202] ctx is not defined error / preview suspended

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#3911]
## Problem description

I am getting a suspended preview and this error in the console:

![Annotation 2020-06-02 124200](https://user-images.githubusercontent.com/36490901/83551805-7a485380-a4ce-11ea-954c-20dbe0e62ae1.png)

It appears to be caused by stacking shaders. Removing one of the shaders from the sprite object in the attached .c3p results in no error.

## Attach a .c3p

[ctx_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4718819/ctx_bug.zip)

## Steps to reproduce

1. Preview the project
2. Open console

## Observed result

Suspended preview and console error

## Expected result

No error

## More details

**Affected browsers/platforms:** 
chrome / nw.js preview

**First affected release:** 
r202
## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.44.6
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.6 (like Chrome/80.0.3987.162)
C3 release: r202 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 800 gb
Storage usage (approx): 150 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SnipG** [comment]
Yep some big bug with shaders etc! Would fix!

**Comment by MathNook1** [comment]
Yes I'm seeing the same error.  A game that worked fine 2 days ago is now black screening with that error showing in the console.

**Comment by gameglaux** [comment]
Overlay effect produces this error also.

**Comment by Kernonen** [comment]
Same here.

**Comment by jaydonteh** [comment]
Can confirm I'm having this issue too. Issues like this can sometimes crop up and not appear in the C3 debugger, causing confusion in users who doesn't know the F12 debugger in chrome existed or how to even read those errors. Though this is a separate issue but might as well mention it here.

**Comment by MikalDev** [comment]
Scirra - need any more info / examples to track this down? It continues to be an issue with R202 and using multiple effects on a new project.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.
