### ISSUE TITLE
Crash using undo in anim editor

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#3912]
## Problem description

Had done a number of things in an animation: importing frames, placing image points, selecting other frames, cropping.

After cropping each frame, I realized I forgot to apply the image points to the entire animation in the correct position - so I kept pressing cntrl + Z to go back in time to before all the cropping and such, but then it crashed.

Don't know how to replicate, maybe the crash report will help.

## Crash details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r202/main.js, line 210, col 102652
Message: Uncaught TypeError: Cannot read property 'ǃLH' of null
Stack: TypeError: Cannot read property 'ǃLH' of null at window.ǃXzZ.ǃWka (https://editor.construct.net/r202/main.js:210:102652) at t.ǃWWG (https://editor.construct.net/r202/projectResources.js:1:2711) at t.ǃDu (https://editor.construct.net/r202/projectResources.js:1:2630) at n.ǃDu.ǃWtc (https://editor.construct.net/r202/projectResources.js:1:596442) at self.ǃSm.ǃWno.ǃWtc (https://editor.construct.net/r202/projectResources.js:1:593305) at n.ǃQa_.ǃPy (https://editor.construct.net/r202/projectResources.js:1:595196) at Function.ǃQae (https://editor.construct.net/r202/projectResources.js:1:974672) at Function.ǃPy (https://editor.construct.net/r202/projectResources.js:1:970019) at t.ǃQGI.ǃQ_q (https://editor.construct.net/r202/projectResources.js:1:883674) at t.ǃQGI.ǃQ_L (https://editor.construct.net/r202/projectResources.js:1:768306)
Construct 3 version: r202
URL: https://editor.construct.net/r202/
Date: Wed Jun 03 2020 17:24:21 GMT+1000 (Australian Eastern Standard Time)
Uptime: 16838.1 s

Platform information
Browser: NW.js
Browser version: 0.45.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.45.0 (like Chrome/81.0.4044.92)
C3 release: r202 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
From the crash report I can tell that it has something to do undoing the addition of image points, but it's hard tell exactly what is the problem. I'll fiddle with it for a little bit and see what I can find.

**Comment by DiegoScirra** [comment]
I was able to find the bug.

It happens if you add a new image point, by either adding a single new one or using an option that will create new image points. Then do some change to an animation frame which has a newly added image point. Finally undo everything, and eventually it should crash.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
