### ISSUE TITLE
Support "maxlength" `<input type="text">` HTML attribute for TextInput plugin.

### ISSUE THREAD

**Issue by whistlegraph** [Scirra/Construct-3-bugs#3914]
## Problem description

It's an unsatisfactory experience to implement length limits on TextInputs using the existing TextInput plugin's "On text changed" event, because there is a flicker effect that occurs when trimming the input.

Here is an example of my current solution on iOS (reproduced in the example .c3p as well) –
![TextInput](https://user-images.githubusercontent.com/3620017/83722144-5598cc80-a5f1-11ea-8eac-8a5863b0c21f.gif)

## Attach a .c3p
This example compares TextInput in contrast to an `<input type="text" maxlength=12">` hosted in an iframe.

[Text Entry.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4727892/Text.Entry.c3p.zip)

## Steps to reproduce

1. See the project file.

## Observed result

Characters that are beyond the set limit using current methods flicker before going away.

## Expected result

Characters should not show up and respect a length limit.

## More details

**Affected browsers/platforms:** 

macOS & iOS Safari / Chromium

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.61
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 294 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics 655
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Please post suggestions to https://construct3.ideas.aha.io/

**Comment by whistlegraph** [comment]
Thank you. Idea reposted here: https://construct3.ideas.aha.io/ideas/C3-I-1414
