### ISSUE TITLE
The Tween behaviour can crash the engine after using the native Save/Load actions.

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#3916]
## Problem description

Hi! I started to implement a temporary checkpoint system for one of my games, but I stumbled upon a fatal error that could completely crash the engine and throw an error in the console. I'm sure it's not related to my code, because the game was released in September of 2019 and no issues were ever found.

To implement this checkpoint system I though the native Save and Load actions would be perfect, because they have the power to save absolutely everything in a JSON string and then load it all back when needed, since the checkpoints were temporary there couldn't be any problems related to future updates (adding or removing objects from the scene).

When I started to implement the Save and Load actions into the game I noticed some "random" crashes every now and then, so I decided to investigate and try to reproduce the crash in a consistent way. After 2-3 days of testing I figured out you need a few thing to make Construct crash:
1. Save and load the game at least once.
2. Have objects with the Tween behavior attached to them.
3. Load the game a few times until one the Tween behaviors "go crazy".

I'm not completely sure if anything else is needed, but I made a very simple c3p file (20 events), which was partially taken from the game, where you can easily trigger the bug and see the full error in the console.

I also recorded this video showing how to reproduce the bug step-by-step and the error in the end. I'm not an expert in programming, but believe "C3" is the base class from which "Tween" inherits, this makes me think saving and loading the game can make something weird happen in the "Tween" class, I don't really know, just trying to share my "conclusions". 

Video showing the problem: https://youtu.be/vME240eIesU

## Attach a .c3p

[Tween and Load Crash Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4736588/Tween.and.Load.Crash.Bug.zip)

## Steps to reproduce

1. Start the project by pressing "F4", it will take you to the right layout.
2. Wait until the green enemy is all the way to the right in its sine cycle.
3. Touch the yellow block to set a checkpoint.
4. Let the green enemy touch you to kill at least 2-3 times, it will result in a consoles error and the game will freeze completely.

## Observed result

After saving and loading the game, ones of the objects with the Tween behavior will start to act weird and then the game will freeze while trowing an error in the console.

## Expected result

No errors, just an accurate save and load feature.

## More details

**Affected browsers/platforms:** Google Chrome/Windows 10

**First affected release:** R197.2 (current stable version)

## System details

<details><summary>View details</summary>

worldInfo.js:1 Uncaught (in promise) TypeError: Cannot read property '_SetAnyCollisionCellChanged' of null
    at C3.WorldInfo.SetBboxChanged (worldInfo.js:1)
    at C3.TrackState.Interpolate (trackState.js:1)
    at C3.Tween.Tick (timelineState.js:1)
    at C3.Tween.Tick (tween.js:1)
    at C3.TimelineManager._OnTick (timelineManager.js:1)
    at Array._tickFunc (timelineManager.js:1)
    at C3.Event.Handler._FireAndWait_AsyncOptional (handler.js:1)
    at C3.Event.Dispatcher.dispatchEventAndWait_AsyncOptional (dispatcher.js:1)
    at C3.Runtime.Tick (runtime.js:1)
    at normal (runtime.js:1)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.

**Comment by BonzerKitten** [comment]
@DiegoScirra Fantastic news! Thank you very much. 👏
