### ISSUE TITLE
The "Set enabled" action for the "Move to" Behavior is different from the others.

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#3918]
## Problem description

Not sure if that could be considered a bug, it's just a bit weird. Anyway, here's an image showing the issue in the editor: https://imgur.com/sv7y9Us

## Attach a .c3p

[Enable Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4736906/Enable.Bug.zip)

## Steps to reproduce

1. Open the project.
2. Check the "Set enabled" action for the Move to Behavior and any other Behavior that have the same action.

## Observed result

There's a different visual approach for each action.

## Expected result

A unified visual approach.

## More details

**Affected browsers/platforms:** Google Chrome/Windows 10

**First affected release:** R197.2 (current stable version)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The checkbox parameter in actions/conditions is new. Actions/conditions added before the checkbox was added don't use it. Switching it over is actually quite a big backwards compatibility headache, so I don't think it's worth changing.

**Comment by BonzerKitten** [comment]
@AshleyScirra Fair enough.
