### ISSUE TITLE
Eraser tool is not as responsive as the brush tool with 0% opacity.

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#3919]
## Problem description

The eraser tool from the animation editor doesn't erase a pixel when you reach it while holding the left mouse button, it only erases a pixel after you leave the one you were hovering before. The brush tool on the other hand works perfectly if you set the alpha to 0%.

Demo video: https://imgur.com/HGAoMx4

## Attach a .c3p

Not necessary.

## Steps to reproduce

1. Open any sprite in the animation editor.
2. Test both eraser and brush with 0% opacity.

## Observed result

The eraser tool doesn't have a very responsive behavior.

## Expected result

The eraser tool to immediately erase a pixel when its reached.

## More details

**Affected browsers/platforms:** Google Chrome/Windows 10

**First affected release:** R197.2 (current stable version)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.

**Comment by BonzerKitten** [comment]
@DiegoScirra Awesome! Thanks a lot. 👍
