### ISSUE TITLE
It's not possible to use Ctrl+F4 anymore.

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#3920]
## Problem description

Ctrl + F4 is a very very hand shortcut to execute the first layout with the debugger, but apparently it's making the whole engine to close, it's probably a default Chrome thing.

## Attach a .c3p

Not necessary.

## Steps to reproduce

1. Open Construct 3.
2. Hit Ctrl + F4 on your keyboard.

## Observed result

The engine is closed.

## Expected result

The first layout to be executed with the debugger on.

## More details

**Affected browsers/platforms:** Google Chrome/Windows 10

**First affected release:** R197.2 (current stable version)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I don't believe this was ever supported. It's always been a shortcut to close the tab in Chrome. Web pages cannot override important browser keyboard shortcuts to prevent abuse.

**Comment by BonzerKitten** [comment]
@AshleyScirra So... Can't you replace this shortcut by another one? I mean, it used to be a very useful shortcut and now it's completely gone. 😕

**Comment by AshleyScirra** [comment]
We did replace it. Look in [the manual](https://www.construct.net/en/make-games/manuals/construct-3/interface/keyboard-shortcuts). It's Shift + F4 now.

**Comment by BonzerKitten** [comment]
@AshleyScirra Oh, I was not aware of that, thanks a lot! 👍
