### ISSUE TITLE
Right mouse button doesn't work as a eraser for the auto-tiling brush.

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#3921]
## Problem description

The title says it all, the right mouse button doesn't work as an eraser for the auto-tiling brush, I believe it's bug because the standard brush does work as eraser if you use the right mouse button, also it doesn't make much sense to have two buttons (left and right mouse button) doing the same thing. If the right mouse button could erase and rearrange tiles that would be perfect.

## Attach a .c3p

[Tilemap.zip](https://github.com/Scirra/Construct-3-bugs/files/4737494/Tilemap.zip)

## Steps to reproduce

1. Open the project.
2. Select the auto-tiling brush.
3. Try to erase a tile by using the right mouse button.

## Observed result

The right mouse button doesn't erase tiles, just place new ones.

## Expected result

The right mouse button to erase and rearrange tiles.

## More details

**Affected browsers/platforms:** Google Chrome/Windows 10

**First affected release:** R197.2 (current stable version)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Added in the next beta.
