### ISSUE TITLE
IOS in-app purchases issue - does not work in release version.

### ISSUE THREAD

**Issue by smallsim** [Scirra/Construct-3-bugs#3922]
## Problem description

In-app purchases don't work in app's **release** version (from Appstore) but work in TestFlight.
Apple says that is the "code-level" problem.

In TestFlight I can purchase the items (in-app-purchases work properly). But in Appstore version I cannot (nothing happens).

When I tap "buy-button" purchase should happen and it is working on TestFlight. But in Appstore-version of the app it does not work. Also it can 'parse' (and show in the app) the price of the in-app purchases.

The problem was occured when I started using new Xcode 11.4.

In Xcode there are some warnings that you will be interesting in:

**File:** InAppPurchase.m
**Warning:** Dead store: Althought the value stored to 'state' is used in the enclosing expression  the value is never actually read from 'state'.

**File:** InAppPurchase.m
**Warning:** Dead store: Althought the value stored to 'productId' is used in the enclosing expression the value is never actually read from 'productId'.

What could it be?

## Attach a .c3p

[test-inapps.ios.project2.zip](https://github.com/Scirra/Construct-3-bugs/files/4738369/test-inapps.ios.project2.zip)

## Steps to reproduce

1. I upload the app in TestFlight via Xcode11.4.
2. In-app purchase work properly in TestFlight tests.
3. I send to review and the app succesfully "Ready for sale".
4. I download the app from Appstore on my iPad.
5. In-app purchases DO NOT WORK (when I try to buy there is nothing happens). Internet connection is ok. Apple inc. can't help me, they say it is a code error...

## Observed result

In TestFlight = working in-app purchases.
In Appstore version = not working in-app purchases.

## Expected result

Working in-app-purchases in release version (from AppStore).

## More details

Earlier I thought this is provisionning profiles problem, but Apple says nothing.
I use virtual machine with macOS Catalina and new Xcode, maybe there is some problem?

**Affected browsers/platforms:** 

IOS

**First affected release:** 
C3 Latest Stable release

## System details

MacBook Pro 17inch (late 2011, macos HighSierra): the app was delivered from Xcode 11.4.1 installed on Virtual Machine (vmWare Fusion 11.5) with MacOS Catalina 10.15.4.
I use IPad 2018 for testing.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
We can't investigate bugs unless you follow the bug report guidelines (e.g. attach a Construct project).

Further if it works in TestFlight, that suggests Construct's code is actually working correctly. If the problem was in Construct's code, it probably wouldn't work in TestFlight either. I don't know why it would not work after publishing, but I would guess it is some configuration issue with the App Store.

**Comment by smallsim** [comment]
@AshleyScirra Here is Apple Developer Technical Support reply:

"I would expect to see the app make the addPayment call, but there is nothing. So either you didn’t include the complete log, or you need to determine why the app didn’t make the addPayment call. BTW - the YRL request for the addPayment method is “inAppBuy”. It’s doesn’t appear in the log."

addPayment and inAppBuy methods missed or the log gives the wrong information?

**Comment by AshleyScirra** [comment]
That doesn't sound like it's in any of Construct's code, so it's difficult to offer any help.
