### ISSUE TITLE
Cant Build to IOS

### ISSUE THREAD

**Issue by bedfl2016** [Scirra/Construct-3-bugs#3927]
When I try and export my project to XCODE i get the following error:

- I believe it is to do with a custom addon - but it builds with android without any errors. I only get this error with IOS exports.

-- the lines aren't crossed out when I get the error - GitHub does that automatically

## System details

<details><summary>View details</summary>

Error: Discovered platform "ios@5.1.1" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-ios@5.1.1
Adding ios project...
Creating Cordova project for the iOS platform:
Path: ~~/ios
Package: com.company.rize
Name: Rize
iOS project created with cordova-ios@5.1.1
Plugin 'cordova-plugin-inappbrowser' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-androidx-socialsharing' found in config.xml... Migrating it to package.json
Plugin 'construct-mobile-rate' found in config.xml... Migrating it to package.json
Plugin 'open-with-cordova-plugin' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Plugin 'construct-plugin-file' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-wkwebview-engine' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-statusbar' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-inappbrowser". Adding it to the project
Installing "cordova-plugin-inappbrowser" for ios
Discovered saved plugin "cordova-plugin-androidx-socialsharing". Adding it to the project
Installing "cordova-plugin-androidx-socialsharing" for ios
Installing "es6-promise-plugin" for ios
Discovered saved plugin "construct-mobile-rate". Adding it to the project
Installing "construct-mobile-rate" for ios
Installing "cordova-plugin-add-swift-support" for ios
Discovered saved plugin "open-with-cordova-plugin". Adding it to the project
Installing "cordova-plugin-openwith" for ios
Failed to install 'cordova-plugin-openwith': Error: Variable(s) missing: IOS_URL_SCHEME, IOS_BUNDLE_IDENTIFIER
at Object.mergeVariables (~~/variable-merge.js:58:15)
at ~~/install.js:307:44
at processTicksAndRejections (~~/task_queues.js:94:5)
Failed to restore plugin "open-with-cordova-plugin" from config.xml. You might need to try adding it again. Error: Error: Variable(s) missing: IOS_URL_SCHEME, IOS_BUNDLE_IDENTIFIER
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for ios
[cordova-plugin-openwith] Adding ShareExt target to XCode project
[cordova-plugin-openwith] Parsing existing project at location: ~~/project.pbxproj…

Error: ENOENT: no such file or directory, scandir '~~/ShareExtension'

</details>

**Comment by Sanquen** [comment]
As far as I know, when exporting to Cordova/IOS, C3 doesn't include the 'open-with-cordova-plugin' in the config.xml. Is it a plugin you manually added after the export?
Could you attach the Cordoba IOS export .zip file before any cordova manipulation to your bug report pls? (maybe delete the www folder from it, to remain confidential)

**Comment by bedfl2016** [comment]
@Sanquen 

It is a custom addon that I use in my project. I have not built it anywhere else. I open the .c3p file and go to build it to XCODE and get that error. 'cordova-plugin-openwith' is whitelisted, and it works with android exports. It is an error on constructs side.

**Comment by Sanquen** [comment]
Well it all depends how to add 'cordova-plugin-openwith' to the config.xml after the C3 export. It seems you're missing some paramters needed byt the 'cordova-plugin-openwith' plugin:
`the plugin to Failed to install 'cordova-plugin-openwith': Error: Variable(s) missing: IOS_URL_SCHEME, IOS_BUNDLE_IDENTIFIER`

**Comment by bedfl2016** [comment]
@Sanquen 

I think you may be confused. The problem is in construct 3 - The error comes up when exporting to Xcode in construct 3 itself. The addon works as I can export with android on the build server and get no errors. There is no need to tamper with the config outside of c3. - the error happens in construct 3.

**Comment by Sanquen** [comment]
ho ok, thought you were building locally :) I tend to stay away from C3 build servers, not that they're not fit for purpose but it slows down development workflow. 
cheers

**Comment by bedfl2016** [comment]
@Sanquen  

No worries , that is why I filed it as a bug as its scirras side that is going wrong.

**Comment by AshleyScirra** [comment]
Note nothing in Construct uses `cordova-plugin-openwith` so this strongly suggests a problem with a third-party addon

**Comment by bedfl2016** [comment]
@AshleyScirra 

yes, it is a third party addon - I had it whitelisted on the build server a few weeks ago and it exports perfectly fine with android. But it encounters errors on your side when exporting to XCODE.

**Comment by AshleyScirra** [comment]
Please report issues with third-party addons to the addon developer. If their addon fails to build they need to fix that, not us.

**Comment by bedfl2016** [comment]
@AshleyScirra 

It is not a fault with the plugin it is the build server I have been rummaging around online and it is an error on your side which is to do with building the project with the plugin. - I can even provide the plugin so you can recreate this if needed?

**Comment by AshleyScirra** [comment]
I'm afraid if their addon fails to build they need to fix that, not us.
