### ISSUE TITLE
r197.2 construct-plugin-file www/Entry.js contains reference to cordova-plugin-file

### ISSUE THREAD

**Issue by Sanquen** [Scirra/Construct-3-bugs#3928]
causing fileEntry.copyTo() and fileEntry.moveTo() success callbacks to fail

![Screenshot 2020-06-07 at 11 59 32](https://user-images.githubusercontent.com/63592788/83967412-f4a31a00-a8b8-11ea-9ad1-35c470e2e211.png)

easy fix, must be replaced with ./FileEntry

**Comment by AshleyScirra** [comment]
It's not clear why this is a problem and if it has no consequence to projects then there's no reason to change anything. Please always follow the bug report guidelines.
