### ISSUE TITLE
Tiled background edge render bug.

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#3929]
## Problem description
Tiled background apply "smooth transition" effect in the edge with neighbour tiles.
![original-img](https://user-images.githubusercontent.com/47735877/84005559-971cd500-a96d-11ea-9ad0-dd1a7abed0ed.png)

rendered:
![rendered-img](https://user-images.githubusercontent.com/47735877/84005582-a1d76a00-a96d-11ea-8249-a6b9a0b6448e.PNG)

I do not know it is by design or it is a bug.
I cannot find anything about it in the documentation or forum.

## Attach a .c3p

https://drive.google.com/file/d/1TCfYs1DKYDz7JVMZln1ECkpeInKOyusD/view?usp=sharing

## Steps to reproduce

1. Create Tiled Background with image
2. Rendered edges will be modified

## Observed result

Rendered edges will be modified with and color washed with neigbour tile edge.

## Expected result

The tiled background will be rendered "pixel perfect"

## More details
**Affected browsers/platforms:** Chrome/Firefox/Safari, Windows/macOS/Android

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.97
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
C3 release: r202 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 418 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 640M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's the green side wrapping around to the other side. For pixel perfect rendering use the pixel art settings (nearest sampling, pixel rounding, letterbox integer scale, possibly low-quality fullscreen mode).
