### ISSUE TITLE
Mipmaps still generated when downscale is set to low

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3932]
## Problem description
Not sure if bug,  I don't know how things work internally!
Problem  manifested itself when i want disable mipmap for some shader effects. Was making myself better pixel renderer shader. After searching wideweb i came across a topics that describe multiple problems but one also is with mipmaps. 

"Because of the imprecisions, adjacent pixels share the same UV, thus the differences between them (or the 'partial derivatives') are null. This makes the texture() function sample the lowest mipmap level on those identical pixels, thus creating discontinuities."

Long story short, it uses automatically mipmaps when it should'nt resulting " glitzy line like seems" between some pixels.

When i made test, i saw editor displays effect correctly, but at runtime it does not. 

* Does it still generates mipmap internally when downscale is set to low? 
* why editor shows test effect differently.

**Test effect just uses texture bias to fetch mipmap version, ineditor the fetch seems to work correctly when downscale is set to low(not able to fetch mipmaps), but in runtime texture bias is still able to fetch mipmap versions?**

## Attach a .c3p

[TestMipMap.zip](https://github.com/Scirra/Construct-3-bugs/files/4746052/TestMipMap.zip)

## Steps to reproduce

1. Open project, install shader effect. 
2. Look image ineditor, then preview.
3. Runtime is able to use mipmaps!

## Observed result
Editor effect compositor is able to disable mipmap fetch, runtime isent.

## Expected result
Runtime to look same as editor. when downscale is set to low

## More details

I don't know why it is like this, just curious if runtime compositor does still generates mipmaps when downscale is set to low in some cases? If it is like this, then i just will search other workaround for my other shader which generates glitzy seems because of it

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.61
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
C3 release: r201 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.4 gb (1.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
You're right, the C3 runtime still does create mipmaps when downscaling quality is set to "low". It's a detail that seems wasn't ported from the C2 runtime which handles this correctly (and the editor handles it too). An easier way to see it is just resize a detailed sprite really small; if mipmaps are off it will show aliasing. I've fixed this for the next release so downscaling quality "low" does not create mipmaps.
