### ISSUE TITLE
The List object doesn't work correctly with the persist behavior

### ISSUE THREAD

**Issue by cb130felix** [Scirra/Construct-3-bugs#3935]
## Problem description

The List object from Form controls doesn't work correctly whit the persist behavior. After restarting the layout a couple of times the object doesn't retain it's old data (the items in the list vanish)

## Attach a .c3p

https://drive.google.com/file/d/12O9G9o319Xo1-EkQTNnQIA9F07bO5zqJ/view?usp=sharing
## Steps to reproduce

1. Run the project
2. There are a slider and a list object with the persist behavior in the layout, play with their values and restart the layout a couple of times (clicking in the button in this layout)
3. Items in the list object disapear

## Observed result

After a couple of times restarting a layout with an list object with the persist behavior their items disapear

## Expected result

For the items of the list object don't disapear and for it to remember the last selected item on layout changes

## More details

Running on chrome 83+, windows 10, c3 r203

**Comment by AshleyScirra** [comment]
The .c3p link doesn't work (it says I need to request access). Please provide a public link.

**Comment by cb130felix** [comment]
Sorry, I made it public now. You can try the link in the orignal post again.

**Comment by AshleyScirra** [comment]
Thanks, it works now.

**Comment by AshleyScirra** [comment]
OK, should be fixed in the next beta.
