### ISSUE TITLE
UWP export - Beginning of music is cut off

### ISSUE THREAD

**Issue by rayray989** [Scirra/Construct-3-bugs#3939]
##  Problem description

When i export project as Windows UWP and run app after opening file in Visual Studio, the beginning of the music is cut off when it starts playing. I have set the events so music starts playing at the end of the splash screen layout.

When i test this in C3, the music plays fine, from the beginning. I'm not 100% certain, but it could be to do with the webm format as I've opened a C2 project in C3 with Ogg & m4a files (with same set events), and plays fine when testing in Visual Studio.

I've attached a zip file that contains the C3 project and also the UWP exported folder. You can also export yourself but nothing has been changed from the folder.

## Attach a .c3p

[Audio Test.zip](https://www.dropbox.com/s/qxfs14hou0gxysk/Audio%20Test.zip?dl=0)

## Steps to reproduce

1. Export as UWP and open in Visual Studio.
2. Run the app from local machine.

## Observed result

When the music starts playing, the beginning of the music is cut off.

## Expected result

The music to play from the beginning, like it does in the C3 preview.

## More details
Created and exported project using C3 Desktop (r197.2 stable).
Using the latest version of Visual Studio 2017.

Windows SDK version 10.0.17763.0

## System details

Browser: NW.js
Browser version: 0.44.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.0416666269302368
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.0 (like Chrome/80.0.3987.87)
C3 release: r197.2 (stable)
Language setting: en-US

**Comment by AshleyScirra** [comment]
I can reproduce, but the audio playback is handled by the (legacy) Edge browser engine for UWP apps, and so it's Edge that is cutting off the audio. You'll need to report this to Microsoft for them to fix it, or work around it some other way, such as by padding the start of the audio with silence.

Note Microsoft are in the process of switching Edge to the Chromium browser engine, so if you can hold out until they switch over UWP apps to Chromium, then that will probably fix it too. I don't know what their timetable for that is though.
