### ISSUE TITLE
Z Order Window Issue

### ISSUE THREAD

**Issue by Coyowl** [Scirra/Construct-3-bugs#394]
## Problem description
I have docked the Z order window on the same panel as the layer as I used to have it in C2.
Every time I launch the software, the Z order windows doesn't display anything. I have to close it and reopen it to work properly
## Attach a .c3p

Unfortunately I cannot create a test project to display that, its the UI
## Steps to reproduce

1. Dock Z Order window
2. Close app
3. Reopen app

## Observed result
Z Order window doesn't display anything at all
*What do you see happen?*
Just an empty window
## Expected result
List Z order of layers

## Affected browsers

* Chrome: yes
Using C3 r32

## System details

The app doen't crash

**Comment by DiegoScirra** [comment]
The fix for this is already live in r32.

Can you go check it out and confirm everything is working properly?

**Comment by Coyowl** [comment]
Will do and let you know

**Comment by 3dParadox** [comment]
Actually it's still not highlighting the selected sprite. Unless you click around in the list and find which one it is. they do highlight when clicked directly in the bar.

**Comment by DiegoScirra** [comment]
@3dParadox 

You are talking about a different issue. Please open a new bug report, it is easier for us to track each problem if it has it's own issue.
