### ISSUE TITLE
Possible Tiled Background bug on iOS?

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#3944]
## Problem Description

A game we just released as beta is getting multiple reports of graphics glitches on iOS. In particular the ground tile, which is a tiled background object that uses setImageOffsetX to simulate movement. The issue does not happen on any other platforms and devices. Only in Safari iOS. The level of glitchyness increases as the game progress.

Project can be found here.
https://agentvegan.com/redrunner/

## Attach a .c3p

Can send offical project file if requested. But it's basically just a tilemap object setting offset.
![image](https://user-images.githubusercontent.com/27011641/84590422-b072c500-ae36-11ea-9657-0aa6b689ea16.png)

## Steps to reproduce

1. Start the game on iOS safari.
2. Press Start Game
3. Play for a while until you get at least 300+ points and see the ground glitch.

## Observed result

Ground will start to glitch more the longer the player playes.

## Expected result

Should not glitch like ohter devices and platforms.

## More details
Only happens on iOS Safari. Other elements such as bacgrounds are using exactly same type of offset to simulate movement, but it does not happen on those. Like the cloud background. And startscreen background.

**Affected browsers/platforms:** 

iOS Safari.

**First affected release:** 

## System details

iOS.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by tunepunk** [comment]
Here are 2 videos from two seperate iphone users who experience the problem. Watch the ground rocking back and forth.

https://www.dropbox.com/s/i6l991wy4684l7w/video1.mp4?dl=0
https://www.dropbox.com/s/3pou2a36rj3f1ay/video2.mov?dl=0

I reviewd my code and can't find any sensible explanation to why it only happens on iOS since it does not happen on any other device or browser.

Any idea what could be causing this?

**Comment by AshleyScirra** [comment]
I think this is what the [manual warns about](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/tiled-background):

> Avoid indefinitely increasing the image offset, such as by always adding to it. On some devices, a very large image offset can start to exhibit rendering glitches due to precision issues on the GPU. You can avoid this by wrapping the image offset back to 0 after it exceeds the image size.

Your events appear to do exactly that. Try making sure they wrap around.

**Comment by tunepunk** [comment]
Thanks a lot. I never checked the manual for this object so missed that. I will try to see if that resolve the issue. Thanks again.

**Comment by tunepunk** [comment]
Bug resolved as that fixed it. Was much easier to fix once I figured out how to do modulo on negative numbers. It would be quite helpful if there was a built in feature of the plugin itself as this was a pretty easy "bug" to stumble across unless you noticed and remembered the warning in the manual.

Thanks for helping me resolve the issue. Been bugging me for days.

**Comment by AshleyScirra** [comment]
We tried to add a built-in limit and it broke the cases when you scale or rotate the tiled background image. We had to revert it. So it's more complicated than it seems. Anyway, closing.
