### ISSUE TITLE
Safari (macOS/iOS) Audio "Stop" error if Audio Tag is Paused.

### ISSUE THREAD

**Issue by whistlegraph** [Scirra/Construct-3-bugs#3945]
When trying to stop a tagged audio file in Safari, a JavaScript error occurs which keeps that audio tag around indefinitely, so new audio that plays with the tag plays the same sound twice.

## Attach a .c3p

[Safari_Sound_Stop.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4778801/Safari_Sound_Stop.c3p.zip)

## Steps to reproduce

Please run the existing project file in Safari on macOS or iOS with the JavaScript console open.

## Observed result

<img width="544" alt="Screen Shot 2020-06-14 at 11 55 18 PM" src="https://user-images.githubusercontent.com/3620017/84632106-4ba18400-aea3-11ea-95d8-3b9e922bdd0a.png">

## Expected result

The Audio Stop function should run without exception, so the same tag can be expired and reused later.

## More details

**Affected browsers/platforms:** 

Safari / macOS & iOS

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.97
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 44 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 5500M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release. We have a stable release scheduled soon but the fix is very minor so I've merged the fix in for the stable release.

**Comment by whistlegraph** [comment]
Excellent, thank you!
