### ISSUE TITLE
Host Disconnecting w/ Console Errors - Linux NodeWebkit export with Multiplayer Plugin

### ISSUE THREAD

**Issue by badmiracle** [Scirra/Construct-3-bugs#3946]
## Background Info
I have a NodeWebkit export of my Multiplayer game "server" (which is just the Host peer) running on an Ubuntu VPS from DigitalOcean (export was done using --headless --disable-gpu params).

NOTE: I'm looking more for insight into the console errors that I'm seeing and what they might mean. I realize this issue may not be a bug related to Construct 3 and rather the infrastructure being used. I'm not even sure if the errors caused the host to disconnect or if it's something else entirely. 

I'm hoping to address two questions:
1. What do the console errors mean (any insight is greatly appreciated!) 
2. If the Host keeps tab/NodeWebkit export open/running, will Scirra's listening server always maintain it's connection? Is it safe to assume if the connection is stable, it will continue running indefinitely? If not, is there anyway to maintain a consistent connection? I haven't purchased my own Listening Server from the marketplace yet, but is there a configuration in there that may help and prevent a time out?

**Console Errors:** https://imgur.com/uJ6Dd2C
**VPS Connection:** https://imgur.com/p91zpTh (Evidence that the connection remained stable)

## Problem description

The game server/clients ran great for 12 hours, then the server started spamming these errors (occasionally these errors would appear throughout the 12 hour period, usually when messages were sent/received, but didn't result in the host disconnecting until after 12 hours). After 12 hours the host disconnect. Oddly, the peers who were in-game at the time, did not receive any Kick/disconnected message notification, but they were no longer able to send/receive messages to each other indicated the Host had left/was down.

Note: This may appear as a niche issue, but I'm hoping to write a how-to guide on running a dedicated host on a VPS using this setup for Multiplayer C3 games. This method seems to be fairly efficient and gives us a way of running a multiplayer dedicated server persistently which several C3 users have requested.

## Attach a .c3p

Multiplayer Real Time Demo

## Steps to reproduce

1. Export Multiplayer real-time demo using NodeWebkit (Linux)
2. Package and run on a Linux system (as "Host")
3. Join as a peer (I used Remote Preview)
4. Send a few text messages (Errors on Host console may appear)
5. Continue running for 12 hours (Note: Errors might be occasionally shown in console of the Host peer, indicating something is wrong but the host disconnecting may not happen for some time... in my case it was just after 12 hours)

## Observed result

Host disconnected after about 12 continuous hours of a solid connection, console errors in screenshot above.

I refreshed the game on Windows 10, and the Windows 10 client became the host (confirming the Ubuntu host was no longer connected, even though it was still "running"). I then closed the Windows host client.

When I opened the terminal in Ubuntu, I noticed several errors in the console (screenshot above), and oddly when I went to do some debugging, I added a blank new line to the terminal to create some separation between errors, it seems to have un-paused/reconnected the host peer, and I was then able to rejoin the Ubuntu host on my Windows machine as a peer (without restarting the application!)

## Expected result

Maintain persistent connection as "host" peer, for any joining peers.

## More details

**Affected browsers/platforms:** 

Peer: Chrome - Windows 10
Host: NodeWebkit 0.46.2 - Ubuntu 20.04 (LTS) x64

**First affected release:** r203.3 Beta

## System details
Peer: Windows 10
Host: Ubuntu 20.04 (LTS) x64

**Comment by AshleyScirra** [comment]
Sorry, I don't know what those errors mean. It also does not appear to be anything related to Construct. I would guess it's a connection issue with the server. Maybe your hosting company has a maximum time limit of 12 hours for a connection or something like that. I'd suggest contacting them first, I doubt I can offer much more help on this.

**Comment by badmiracle** [comment]
Thanks Ashley.

According to the bandwidth monitor the VPS never lost connection/went down.

I just purchased the signalling server and I'm now thinking there may be a timeout feature on Scirra's public signalling server that has something to do with the disconnects. 

1. Is the public signal server using the default settings?
2. Is there a way to remove the timeout? IE. could the "Host" issue periodic broadcast messages with no players online to ensure the connection remains open?

I'll have to do some more testing but as I am currently relying on the public signalling server until I get my own configured, the tests take a bit of time so any input is appreciated!

**Comment by AshleyScirra** [comment]
So long as you have joined a room, there is no timeout on the signalling server.

Besides, if there was, it would just disconnect, not start throwing socket errors.

I think you should ask your hosting provider about timeouts.

**Comment by badmiracle** [comment]
I've sent them a message. Thanks Ashley - could we keep this issue on hold in case I'd like to contact you directly should any questions pop up around the plugin/server? Alternatively, is there a better way to contact you... perhaps the support email?

**Comment by AshleyScirra** [comment]
I don't believe this is an issue with Construct, so closing this issue. As noted I don't think we're the right people to ask about this.

**Comment by badmiracle** [comment]
Hi Ashley,

I saw this default setting in the Signal server source. Could this be the reason? The host was getting kicked after 5 failed connections. Does this have to be 5 failed connections in a row, or 5 failed connections total?

//host_max_unconfirmed: 5,

**Comment by AshleyScirra** [comment]
It means that if 5 peers fail to connect to the room host, the host is kicked on the assumption nobody can establish a connection to them so somebody else should be the host. Whether or not someone can connect to the host happens peer-to-peer and does not involve the signalling server.
