### ISSUE TITLE
Text Sine Issue

### ISSUE THREAD

**Issue by Coyowl** [Scirra/Construct-3-bugs#395]
## Problem description
Applying Sine to a text object with Size as Movement doesn't scale the object but instead it moves it on a diagonal angle. 

## Attach a .c3p
[test.zip](https://github.com/Scirra/Construct-3-bugs/files/1038255/test.zip)

## Steps to reproduce

1. Create new text object
2. Add Sine behavior to it
3. Select Size for Movement

## Observed result
It moves diagonally

## Expected result
Scale the text object

## Affected browsers
* Chrome: yes/no
Construct 3 r32

## System details
It doesn't crash

**Comment by AshleyScirra** [comment]
It's working correctly: the Sine behavior is set to change the width and height, not the font size. It's working the same as resizing the text object in the layout view, which if you do, you'll notice also moves the text since it's center-aligned.

**Comment by Coyowl** [comment]
Thanks for letting me know, I will play with the font size instead 😃
