### ISSUE TITLE
Can't draw on the selected tilemap

### ISSUE THREAD

**Issue by Wolod** [Scirra/Construct-3-bugs#3950]
## Problem description

If there are several tilemaps on the same layer I can draw tiles only on the top one. In other words I can't draw on the tilemap (even if I selected it via z-order bar) if there is any other tilemap over it on the same layer. It is very inconvenient.

## Attach a .c3p

[TilemapBug.zip](https://github.com/Scirra/Construct-3-bugs/files/4792152/TilemapBug.zip)

## Steps to reproduce

1. Create at least 2 tilemap objects on the same layer.
2. Select the tilemap that is at the bottom of the layer via z-order bar.
3. Try to draw or erase tiles using the tilemap bar.

## Observed result

Selected tilemap doesn't change.

## Expected result

I expect new tiles to appear when I draw them or disappear when I erase them.

## More details

**Affected browsers/platforms:**

Chrome, Windows 10

**First affected release:** 

I started using C3 only few days ago. So for me it's r204 stable.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.106
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
C3 release: r204 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 122 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by NoSoul8** [comment]
Come to think of it - i've encountered this aswell. 
Had to move the second tilemap away and put it back after i'm done. 
Hope it can be fixed.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
