### ISSUE TITLE
User cannot set a negative or floating value to an image point on mac osx 10.15

### ISSUE THREAD

**Issue by Alvalol** [Scirra/Construct-3-bugs#3952]
## Attach a .c3p
[c3bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4801531/c3bug.zip)

## Steps to reproduce

1. Open C3 with Chrome on Mac
2. Select a sprite
3. Try to set a negative value or a float value to one of the imagepoints

## Observed result

User is unable to set a negative value to one of the image points. Erasing a value in one of the coordinate values results in the image point being deleted or in C3 Crashing.

## Expected result

User is able to set a negative or floating point value to the coordinates of an imagepoint.

## More details

**Affected browsers/platforms:** Tested on CHrome

**First affected release:** Current, as far as I know.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.106
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.15_0
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
C3 release: r204 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 113 gb
Storage usage (approx): 282 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 555X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed along with #3960
