### ISSUE TITLE
iOS PhoneGap Build Failure

### ISSUE THREAD

**Issue by whistlegraph** [Scirra/Construct-3-bugs#3954]
## Problem description

Hello, Construct's documentation suggests using Adobe's PhoneGap Build service, but that build service fails with my project for reasons that should affect any project.

I'm attaching a failed PhoneGap Build iOS log file from my new project in case the information is relevant. For now, I'll simply go through XCode.

[build.phonegap.txt](https://github.com/Scirra/Construct-3-bugs/files/4801994/build.phonegap.txt)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
PhoneGap Build is semi-retired and basically nobody should use it any more. If our documentation mentions it anywhere, it should be removed. Can you point out where it says that?

Other than that if you have issues with third-party services, you'll need to take it up with the service - we don't run PhoneGap Build.

**Comment by whistlegraph** [comment]
Hey, it was suggested here: https://www.construct.net/en/tutorials/publish-mobile-apps-26 Not part of the official documentation but, it still got me headed in that direction.
