### ISSUE TITLE
Change keystore 'Validity' default value

### ISSUE THREAD

**Issue by plinkieant** [Scirra/Construct-3-bugs#3956]
When you are creating a keystore the default value for Validity is 10 which isn't accepted by the google store (must be 25 or above), hope that default value can be increased to 25 to avoid users reporting errors from google 'signed certificate expires too soon'

n/a on the project file

## Steps to reproduce

1. export as signed APK
2. create new keystore
3. observe the validity field default value of 10

## Observed result

Default value is 10 which isnt acceptable by the store

## Expected result
Default value should be 25 or greater to be allowed by the store and avoid user reported errors

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I've not heard of this before, maybe it's a new requirement. It's easy to change though, so updated for the next release. We'll probably to a 204.2 release next week, and this will be included there.
