### ISSUE TITLE
Sprite Jump Form Layout to author layout

### ISSUE THREAD

**Issue by karimlahbach** [Scirra/Construct-3-bugs#3958]
## Steps to reproduce

1. Create layout 1 and 2 to switch between them 
2. add image in layout 2
3.  Switch between layout using touch and button

## More details

**Affected browsers/platforms: *Chrome/Windows* 

**First affected release: *r204* 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's working correctly. UIPLAY12 is set to global so won't be destroyed when changing layout.

**Comment by karimlahbach** [comment]
Thanks Ashley sorry about this (my bad)
