### ISSUE TITLE
Persistent storage request needs to be in synchronous handler

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#396]
Choosing the 'Save to local browser' save option checks for persistent storage, requests it if necessary, and prompts the user if it can't get it.

Since the request is not done in a synchronous input event, it could be declined. Persistent storage should be immediately requested in the event handler that opens the dialog. I adjusted the menu options to open the dialog in a synchronous callback, but the dialog itself uses some promises so the persistent request is not made in the user input event.

**Comment by shortercode** [comment]
Since the test for persistence being enabled is async I've chosen to display a dialog "requesting" the user enable persistence. Figured this should give me a sync user input to work with.

**Comment by AshleyScirra** [comment]
The committed fix has two issues:

1. It asks the user a question but doesn't give them a choice ("would you like to request persistence? [OK]") - use a Confirm dialog to give options [Request] and [Cancel]
2. It still doesn't use a synchronous callback - the promise returned by ShowModal is async. The Confirm dialog has an onconfirm handler you can use instead which fires synchronously.

**Comment by shortercode** [comment]
New fix issued, awaiting review by @AshleyScirra before closing

**Comment by AshleyScirra** [comment]
LGTM
