### ISSUE TITLE
Crashes and problem with editing image points in Animation Editor

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#3960]
## Problem description

Pressing Del or Backspace when manually entering image point coordinates removes the image point.
Pressing Ctrl-Z to restore image point crashes the editor.

## Steps to reproduce

1. Add an image point to any sprite
2. Click the input box to change image point X or Y.
3. Press Del or Backspace to erase numbers in the input box, this will remove the image point instead!
4. Press Ctrl-Z to restore the image point.
5. Click anywhere on the image, the editor will crash.

## Observed result
As described above.

## More details

**Affected browsers/platforms:** all

**First affected release:** r204

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r204/projectResources.js, line 1, col 614407
Message: Uncaught TypeError: Cannot read property 'clear' of null
Stack: TypeError: Cannot read property 'clear' of null at t.ǃO$S.ǃ$ (https://editor.construct.net/r204/projectResources.js:1:614407) at r.ǃZyA.ǃZ_x (https://editor.construct.net/r204/projectResources.js:1:977540) at Function.ǃO$O (https://editor.construct.net/r204/projectResources.js:1:976681) at Function.ǃZyP (https://editor.construct.net/r204/projectResources.js:1:970775) at Function.a.ǃOFJ.ǃZOa (https://editor.construct.net/r204/projectResources.js:1:977899) at i.ǃZeX.ǃrcb (https://editor.construct.net/r204/projectResources.js:1:868433) at Array.ǃrca (https://editor.construct.net/r204/projectResources.js:1:860963) at e.Event.ǃKmg.ǃKmE (https://editor.construct.net/r204/main.js:2:199962) at t.ǃOB.ǃuV.ǃrcf.dispatchEvent (https://editor.construct.net/r204/main.js:2:197743) at r.ǃrcD.ǃZur (https://editor.construct.net/r204/projectResources.js:1:726793)
Construct 3 version: r204
URL: https://editor.construct.net/
Date: Sat Jun 20 2020 19:18:53 GMT+1000 (Australian Eastern Standard Time)
Uptime: 18 s

Platform information
Browser: Chrome
Browser version: 83.0.4103.106
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
C3 release: r204 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_video_texture, OVR_multiview2
</details>

**Comment by DiegoScirra** [comment]
This is related to issues #3957 #3952

**Comment by AshleyScirra** [comment]
@DiegoScirra - this is fixed for the patch release, right?

**Comment by DiegoScirra** [comment]
Yeah, this should be fixed now.

**Comment by dop2000** [comment]
@DiegoScirra  @AshleyScirra 
It's no longer crashing, and the decimal point works, thanks for fixing it!
However, pressing Del or Backspace while editing image point coordinates still removes the image point.
