### ISSUE TITLE
Touch in top level menu buttons broken for Windows 10 devices. Working for 2nd level menus. 

### ISSUE THREAD

**Issue by Milesloh** [Scirra/Construct-3-bugs#3964]
## Problem description
When you open a menu like the "Add Event" menu touch does not work to press buttons on Windows 10 devices. It does however work for later menus such as Parameters menus. 

## Attach a .c3p

N/A an empty project reproduces the bug. 
## Steps to reproduce

On Windows 10 devices:
1. Add a new event
2. Choose System, tap next (touch will not work for the button so click next with the mouse)
3. Choose Compare Two Values, tap next (touch will not work for the button so click next with the mouse)
4. Tap done on the "Parameters for System: Compare Two Variables" menu. (touch will work)

## Observed result
Touch does not work on the "Add New Event" and "Add 'System' Condition" menu buttons.

Touch does work on the "Parameters for System: Compare Two Variables" menu buttons.

## Expected result
touch should either work on all buttons, (or if that isn't possible no buttons for consistency I guess?)

## More details

**Affected browsers/platforms:** 
Windows 10
Firefox, Edge Chromium

All versions I can test up to 204 stable
**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 85.0.545.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4166.0 Safari/537.36 Edg/85.0.545.0
C3 release: r204 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 142 gb
Storage usage (approx): 443 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, looks like we had some old code in certain places that incorrectly handled touch events. It should be fixed in the next beta.
