### ISSUE TITLE
InputText object doesn't have a "is visible" condition nor a "toggle visible" action.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3967]
## Problem description

Not really a bug, but seems minor enough for a fast unobtrusive solution, also it would make this feature more complete and robust through the code.

I understand this is a feature request, but the scope is so minimal I was afraid it would get lost in the fog of the feature request page forever.

## Attach a .c3p

Any file should present it.

## Steps to reproduce

1. Add an InputText.
2. Try to check if it is visible through a condition.
3. Try to toggle its visibility.

## Observed result

Options not available, unlike mostly every other object that has them.

## Expected result

Being able to check and toggle visibility for InputText objects.

**Comment by dupuqub** [comment]
In the spirit of improving the InputText even more, there also isn't an "append text" action to it.

**Comment by AshleyScirra** [comment]
There's a new 'minor suggestions' category on the feature suggestions platform for quicker/easier suggestions like this, please post it there instead: https://construct3.ideas.aha.io/?category=6819616584590062429
