### ISSUE TITLE
Line of sight seeing destroyed objects

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#3972]
## Problem description

I have an object A that will move toward an object B when it sees it. When it collides with it, it will destroy the object. However, it will not stop confirming that it can see the object.

I have an event that says "If object A does not have line of sight to object B, change state". If Object A moves away from Object B, this works fine, but if Object B is destroyed while Object A can see it, it will never revert state.

## Attach a .c3p

[SightBug.zip](https://github.com/Scirra/Construct-3-bugs/files/4814068/SightBug.zip)

## Steps to reproduce

1. Create 2 sprites, giving one of them the line of sight behaviour and the drag and drop behaviour.
2. Create a var or colour change for when it sees the object or not.
3. Create 2 events that will check whether or not the object has line of sight to the other or not.
4. If the two object collide, destroy the detected object.

## Observed result

When the object is destroyed, the first object continues to claim that it can see it.

## Expected result

The object should stop reporting that it can see it.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
