### ISSUE TITLE
Issue with the last version of Construct 3

### ISSUE THREAD

**Issue by didakcode** [Scirra/Construct-3-bugs#3974]
## Problem description: the game works fine on the preview and also the remote preview. But once exported on my website seems to be blocked in an System>wait time instruction

 The url of the uploaded project https://aprendomusica.com/const2/38measures/index.html

## Steps to reproduce

1.When you tap one of the buttons on the first screen, the game have to jump to the next exercise. 
2.
3.

## Expected result

 Jump to the next exercise
[38measures.zip](https://github.com/Scirra/Construct-3-bugs/files/4815996/38measures.zip)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to investigate this report. Please see the bug report guidelines, they're there to make sure we can help.
