### ISSUE TITLE
"Time" action doesn't work on exported project

### ISSUE THREAD

**Issue by didakcode** [Scirra/Construct-3-bugs#3977]
## Problem description: Time action doesn't work on exported project

 The game works perfectly on a preview, local and also remote. But when you export it and upload it on a server, an "time" action doesn't work and the game stops.

## Attach a .c3p
[38measures.zip](https://github.com/Scirra/Construct-3-bugs/files/4819543/38measures.zip)

## Steps to reproduce When the first layout appears, you have to press one of the 3 options in orange. The game responds if it is correct or not, and jump to another exercise. This last action is delayed 1.5 seconds by a "time" action. It works correctly on the preview, but it don't in the exported game. So the game remains blocked. The url of the  exported game is https://aprendomusica.com/const2/38measures/index.html

1.When the first layout appears, you have to press one of the 3 options in orange.
2.The game shows if the choosed option is correct or not
3.After 1.5 sec, the game shows a new exercise. It works on the preview, but not in the exported game.

## Observed result Step 3 works in a preview, but it doesn't in the exported game. I'm pretty sure that is the 'time' action in line 27 of the event sheet "sh-intro" fault.

Observed result Step 3 works in a preview, but it doesn't in the exported game. 

## More details
I'm pretty sure that is the 'time' action in line 27 of the event sheet "sh-intro" fault.

 I have checked it in different browsers, devices and I have exported several times. If I toggled the time action in line 27 sh-intro, the game works (obviosuly without the delay I want) So I think is this instruction that is the reposible of the issue.

**Affected browsers/platforms:** 

 last version r-204-2

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's infeasible to investigate bug reports like this. We need a minimal project, as per the bug report guidelines. If you think one action is the problem, you can prove it, and provide a minimal project, by making a project just using that action. If that works, it must be something else. Very frequently people file issues that are mistakes in their events or problems with the server configuration; we have this process to prove the problem is with Construct.
