### ISSUE TITLE
Fatal crash after using the native save/load action

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#3979]
## Problem description

Hi! I found another bug related to the native save and load actions in Construct 3. I made a very very minimal version of my game (around 20 events) that can reproduce the fatal crash consistently.

Here's a video I recorded showing the problem: https://youtu.be/prBxQCDacZk

As you can see I'm able to load the game if the character dies to the red enemy, however if the character dies to the pink enemy while the red enemy is shooting it's a 100% chance of crash.

I'm not an expert, but I believe the crash is related to the internal function responsible for grabbing objects by UID, because I can easily prevent this crash from happening by disabling a single action in the code, which uses the "Pick by UID" condition. Also, the console shows an error saying "at C3.Runtime.GetInstanceByUID (runtime.js:1)".

I believe this is the third bug related to the native save and load actions in Construct 3 that I found in a few weeks, so I guess it would be great if this feature could be more carefully tested by the developers, since it can cause a few headaches and slowdowns during the development of commercial projects.

## Attach a .c3p

[Pick by UID fatal error.zip](https://github.com/Scirra/Construct-3-bugs/files/4821001/Pick.by.UID.fatal.error.zip)

## Steps to reproduce

1. Move the blue character towards the red enemy line of sight so it can shoot the blue character.
2. Allow the blue character to be hit once, so you can see the save and load actions working properly.
3. Move the blue character towards the red enemy line of sight again, but this time keep walking left until the blue character is hit by a pink enemy while the red enemy projectile is flying.
4. Press F12 to check the console error after the fade animation is frozen.
5. Disable the event in line 14 and notice that the error doesn't happen again.

## Observed result

The save and load actions can cause a fatal crash for no reason.

## Expected result

The save and load actions to not freeze the game.

## More details

**Affected browsers/platforms:** Chrome / Windows 10

**First affected release:** R204.2 (current stable)

## System details

<details><summary>View details</summary>

sw.js:53 [SW-Preview] Up to date
bootPreview.js:14 Registered service worker on https://preview.construct.net/local/
runtime.js:1 [C3 runtime] Hosted in DOM, rendering with WebGL 2 [ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)] (standard compositing)
runtime.js:1 [Construct 3] Saved state to storage (5786 chars)
actions.js:1 Save complete!
actions.js:1 Load requested.
runtime.js:1 [Construct 3] Loaded state from storage (5786 chars)
runtime.js:1 [Construct 3] Failed to load state from storage:  Error: cannot call while loading state - wait until afterload event
    at C3.Runtime.GetInstanceByUID (runtime.js:1)
    at ha (commonACEs.js:1)
    at C3.ObjectClass.ga (commonACEs.js:1)
    at C3.Condition._RunStatic (condition.js:1)
    at C3.EventBlock._RunAndBlock (eventBlock.js:1)
    at C3.EventBlock.RunAsFunctionCall (eventBlock.js:1)
    at C3.EventBlock._RunActions_Fast (eventBlock.js:1)
    at C3.EventBlock._RunAndBlock (eventBlock.js:1)
    at C3.EventBlock.Run (eventBlock.js:1)
    at C3.EventSheet._ExecuteTrigger (eventSheet.js:1)
_DoLoadFromSlot @ runtime.js:1
actions.js:1 Load failed!
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

</details>

**Comment by AshleyScirra** [comment]
The problem is loading a savegame triggers 'On destroyed', and 'Pick by UID' crashes if used half-way through loading a savegame, because it hasn't finished loading (and so can't know which instance the UID corresponds to).

I think the simplest fix is to not trigger 'On destroyed' when loading a savegame - it's probably not a time you actually want to handle an object being destroyed in events anyway, since it's only being removed for the purposes of loading a savegame. This change is made for the next release and it avoids the crash.

**Comment by BonzerKitten** [comment]
@AshleyScirra Thank you for the insightful explanation, now that you mentioned the fact that "Load" triggers the "On destroyed" event it makes a lot more sense on why it's crashing the engine. Do you believe the change you're about to make could somehow affect other parts of the project? Should I be concerned about anything? Thank you very much for your attention.
