### ISSUE TITLE
tween tags incorrectly triggering other tween events

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-3-bugs#3980]
## Problem description

If a tween tag contains the same starting string as another tween tag, the event that triggers this is being run even if the rest of the tag string is different. Created an example of this, basically, the first tween uses the tag 'jump' which triggers an event on finished. However, another tween tag called 'jump right' is also setting off the 'jump' tween event.

## Attach a .c3p

[tween bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4822601/tween.bug.zip)

## Steps to reproduce

1. create two tween events, have the tags match at the start, but have the end tag separate to the first. Notice how the second tween event can trigger the first one
2.
3.

## Observed result

Incorrect event 

## Expected result

Event should only trigger if exact string match to tag with no additional characters

## More details

Using 204.2 stable

## System details

Platform information
Browser: Chrome
Browser version: 83.0.4103.106
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36
C3 release: r204.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 67 gb
Storage usage (approx): 2.7 gb (4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This is not a bug. 

Tweens can be given multiple tags separated by spaces. The string "jump right" is setting the tween with 2 different tags, "jump" and "right".

The "on finished" condition then checks if the finished tween matches the tags provided. A tween with tags "jump" and "right" will match "jump", a tween with the single "jump" tag will also match it. This allows to share the same conditions between similar tweens.

If you need a single tag avoid using spaces.

**Comment by Ldwebster111** [comment]
That makes sense, thanks.
