### ISSUE TITLE
Pathfinding behavior causes a JS error during preview

### ISSUE THREAD

**Issue by Wolod** [Scirra/Construct-3-bugs#3981]
## Problem description

Preview of my project doesn't work after I updated to the r205. Here is the error message I get in console:

```
    Uncaught (in promise) TypeError: b is not a function

    at MakeFilledArray (instance.js:1)

    at instance.js:2

    at MakeFilledArray (instance.js:1)

    at instance.js:2

    at MakeFilledArray (instance.js:1)

    at new C3.Plugins.Arr.Instance (instance.js:2)

    at Function.c.New (jsutil.js:8)

    at C3.Instance._CreateSdkInstance (instance.js:5)

    at C3.Runtime.CreateInstanceFromData (runtime.js:40)

    at C3.Layout._CreateGlobalNonWorlds (layout.js:17)
```

If you click on instance.js:1 in your console you'll see the piece of code that causes the error. It's related to the pathfinding behavior. So I removed it from my project and it worked fine again. After a little investigation I realized that this error happens only if you have at least one array in the project.

## Attach a .c3p

[path_array_error.zip](https://github.com/Scirra/Construct-3-bugs/files/4825303/path_array_error.zip)

## Steps to reproduce

1. Create any object.
2. Add pathfinding behavior to it.
3. Create an array.
4. Run preview.

## Observed result

All I see is a black screen and error message in the console.

## Expected result

Preview has to run successfully.

## More details

**Affected browsers/platforms:** Chrome, Windows 10

**First affected release:** broke in r205

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r205 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 205 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This was caused by a bug in Closure Compiler; I've [filed the issue](https://github.com/google/closure-compiler/issues/3623) and worked around it for the next release.
