### ISSUE TITLE
Error exporting with script minification enabled in r205

### ISSUE THREAD

**Issue by MathNook1** [Scirra/Construct-3-bugs#3983]
Project exported in r205 does not export and displays "Failed to export project" box.  The same project exports fine under r204.2.  It also exports successfully if minify mode is set to none.  Fails with this error if minify mode is set to either simple or advanced.

Attaching image showing this message along with the Chrome console output.
## Attach a .c3p

Cannot provide one at this time.  Will try and submit .c3p file if needed.

## Steps to reproduce

1.  Select Project/Export/Web HTML5
2.  Choose dedup, recompress, and a minify mode of Simple or Advanced 

## Observed result

Project export does not complete and shows the "Failed to export project" message box.

## Expected result

![construct r205 failed to export console output](https://user-images.githubusercontent.com/34988250/85561403-2c1c0100-b5f1-11ea-9804-97aa68e877c7.png)
![construct r205 failed to export project](https://user-images.githubusercontent.com/34988250/85561405-2d4d2e00-b5f1-11ea-8048-4e3c062e13d2.png)

**Comment by mgsoftwaring** [comment]
I have the same problem with my 3 games, all do this error with some games no changes were made and with previous versions it exported to HTML 5, now by mistake

**Comment by AshleyScirra** [comment]
No project was provided, so I tried a HTML5 export with Ghost Shooter. It worked fine. This is usually what happens if no project is provided, which is why one is required. Please follow the guidelines to make sure we can help.

**Comment by AshleyScirra** [comment]
OK, by change I stumbled across the fact this happens if you enable script minification. I guess it's another thing broken by Closure Compiler. I'll take a look since this reproduces with Ghost Shooter.

**Comment by MathNook1** [comment]
Yes, it only happens when you choose script minification.  Sorry I was unable to provide a project at the time.

**Comment by MathNook1** [comment]
I did mention that it only happens when minifying.

**Comment by mgsoftwaring** [comment]
I haven't tried to exclude minifying, but I can't think that to solve a problem I have to choose a function other than the one I've used to date. The problem must be solved.
Mimmo

**Comment by mgsoftwaring** [comment]
I can't attach code, mine is a commercial product, I would violate the agreements between me and the game manager, who is my client
Mimmo

**Comment by MathNook1** [comment]
Mimmo,  I feel sure that Ashley will address the issue.  That said, I'm always cautious when it comes to using the Beta version especially if I'm in a time crunch as issues do crop up from time to time.

**Comment by AshleyScirra** [comment]
This turned out to be an incompatibility between the new editor minifier (Closure Compiler) and the old export minifier (babel). In r206 the editor now uses Closure Compiler as well, so there is no incompatibility, which appears to have fixed the "Failed to export" error.
