### ISSUE TITLE
Tween of text color bug

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3985]
## Problem description

The tween of a text seems to start to change even if its value is already where it is supposed to go.

For comparison, the color of a sprite will behave accordingly, if its already at say rgbEx(80,80,80) and I ask for it to tween to the same rgbEx(80,80,80) it will remain static, since its value is the same.

To observe the bug, just hover over the Blue and Pink sprites and see that the Sprites themselves behave normally, but the Pink_Text will "freak out" a little.

## Attach a .c3p

[Tween_Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4830035/Tween_Bug.zip)

## Steps to reproduce

1. Very hard to explain, but the file is extremely minimal and as clear as I can make it.

## Observed result

A text flicker when I tween its color to the color it already is tweened to.

## Expected result

For it to not flicker since its value is already where it is supposed to be, just like Sprites behave.

## More details

**Affected browsers/platforms:** Latest chrome build.
**First affected release:** Since 205 has been without cloud save, I've been using 204-2.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
