### ISSUE TITLE
Image editor grid invisible on black sprite

### ISSUE THREAD

**Issue by 3dParadox** [Scirra/Construct-3-bugs#399]
## Problem description
Never mind, I see the change color ability now.

On a black sprite in the image editor, you can't see the image editor grid. Maybe toggle it to a light shade when the background brightness is on? (probably feature request)

## Attach a .c3p

editor

## Steps to reproduce

1. fill a sprite with black.
2. turn on the grid.
3.

## Observed result

The grid doesn't show on black.

## Expected result

XOR or reversed color when over black.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
You can change the color of the grid. It's not automatic, but it should work well for this cases.

**Comment by AshleyScirra** [comment]
@DiegoScirra - the layout view uses both black and white grid lines at the same time to ensure it's always visible, possibly something to add to the image editor too?

**Comment by 3dParadox** [comment]
Since you can change colors, a second color would probably have to be a shadow for light colors, and a highlight for dark colors. 
Or, you could make it two shades of the chosen color, that way it's visible on a matching color.
