### ISSUE TITLE
Assertion failure when opening saved project.

### ISSUE THREAD

**Issue by SkylerEvans** [Scirra/Construct-3-bugs#3990]
## Problem description

I'm attempting to load a project I worked on last night and am getting an error report that requires me to restart construct 3 and asks to verify it's a proper c3p file. I've tried removing the ._autosave_. and renaming the file, no luck. I have tried downloading and running it locally from my computer, rather than browser storage, but am getting the same results. I'm really hopeful that this is repairable and not just corrupt, as I put a decent amount of work into it over the last few days.

## Attach a .c3p

[https://drive.google.com/file/d/1kUp7RrdT76IfhVh-ys-oX_L7yRwf5G__/view?usp=sharing](url)

## Steps to reproduce

1. Attempt to open the c3p file.
2. Observe error report.

## Observed result

Construct 3 throws an "assertion failure" error, stating "missing nested data". 

## Expected result

The project would open without issue, as it had previously.

## More details
Unable to open the file in Chrome on Android or PC, so I expect that the file itself is likely bad at this point.

**Affected browsers/platforms:** 

using version 204.2, unsure if issue is related to version.

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: missing nested data
Stack: Error at Function.a.ǃxl$ (https://editor.construct.net/r204-2/main.js:2:126941) at e (https://editor.construct.net/r204-2/main.js:2:83857) at window.assert (https://editor.construct.net/r204-2/main.js:2:84210) at I.ǃkTO (https://editor.construct.net/r204-2/projectResources.js:1:176891) at I.ǃkVn (https://editor.construct.net/r204-2/projectResources.js:1:204885) at v.ǃkeq (https://editor.construct.net/r204-2/projectResources.js:1:518807) at v.ǃkNj (https://editor.construct.net/r204-2/projectResources.js:1:558087) at async window.ǃXb_.ǃkeV (https://editor.construct.net/r204-2/main.js:210:78973)
Construct 3 version: r204.2
URL: https://editor.construct.net/
Date: Thu Jun 25 2020 10:46:26 GMT-0800 (Alaska Daylight Time)
Uptime: 106 s

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r204.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by dupuqub** [comment]
Hi there, I'm not a dev, but sometimes for a quick fix I boot an older version of Construct (just change the version number on the address bar) and try saving it there and then reloading it again in the newest version possible until you get to the newer, or somewhere you can still work with it and/or recover stuff.

**Comment by SkylerEvans** [comment]
I have tried rolling back to r242, but was unable to load up the c3p file, since it was saved in a newer version. I may be missing a process to load up on an older revision, though.

**Comment by DiegoScirra** [comment]
Hello, try this project https://www.dropbox.com/s/ojmltt9nwj7asmh/Railways_TutorialFix.zip?dl=0. It should load.

The bug still exists though, so it might break again in the future. Something caused the project to be saved incorrectly.  Any information about what you were doing before saving the project will be very useful. If you don't remember anything specific don't worry.

The one thing I can see is that there is a nested timeline in the project and it has something to do with the issue, but I'm still not too sure what went wrong. Were you expecting for the nested timeline to be saved or not? I imagine the bug must be somehow related to deleting nested timelines, but I need to investigate a bit more. Again any bits of information are useful, even if you think they are not related.

**Comment by SkylerEvans** [comment]
It was my first time working with Timelines, so if I did something incorrectly that messed it up, that might be on me. I didn't do anything special with saving them, I had assumed the nested timeline would have saved with the rest of the project. I hadn't intended to delete the nested one, but if I didn't explicitly save it then that may have been my problem.

I was using a "keyframe" timeline to do discrete steps (sets of instructions for a tutorial), and then the nested one was an animated one showing specific mouse gestures. Aside from using a few actions to jump to different points in the Keyframe timeline, I didn't THINK I was doing anything too weird with them.

**Comment by DiegoScirra** [comment]
It sounds like you were using the tool normally, I wouldn't blame it on you.

There must be a specific, non obvious, order of actions that trigger the bug.

**Comment by AshleyScirra** [comment]
Issue open with "need info" tag and no response for a few weeks, so closing as can't reproduce.
