### ISSUE TITLE
File save doesn't overwrites when file opened through drag and drop 

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3991]
## Problem description

When we open files through drag and drop, do some changes and save . It pops up "save as" dialogue and doesn't overwrite.

## Attach a .c3p

you can choose any from your pc

## Steps to reproduce

1.Open any file through drag and drop
2. do some change and save it

## Observed result

pops up save as options

## Expected result

Save Overwrite

## More details

**Affected browsers/platforms:** Chrome / Desktop

**Comment by AshleyScirra** [comment]
Chrome's Native File System API (which we use for local file & folder saves) currently does not integrate with drag & drop, so we have no way of writing back over a file that was drag & dropped in to the editor. I'm afraid you will have to save-as over the original file. I filed this as a specification issue with Native File System API a while ago: https://github.com/WICG/native-file-system/issues/82
If support is added there then we can add this to Construct.
