### ISSUE TITLE
Go to URL does not function on iOS or Android

### ISSUE THREAD

**Issue by whistlegraph** [Scirra/Construct-3-bugs#3992]
## Problem description

Go to URL no longer functions on iOS at all, and on Android builds, URLs stay within the WebView. It did work in previous releases. Maybe this is related to a Cordova update? Example project below.

## Attach a .c3p
[URL Test.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4839476/URL.Test.c3p.zip)

## Steps to reproduce

1. Build the project and test on an iOS device through XCode, or an Android device.

## Observed result

iOS: No response.
Android: URL does not open in a new window or in the user's browser.

## Expected result

The documented behavior for the API.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r204.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 137 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) UHD Graphics 630
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Mr-Josh-web** [comment]
+1 

Tested on iOS and it does not work.

**Comment by AshleyScirra** [comment]
A recent Cordova update looks like it broke this, but found an alternative which works for the next beta.

In case you need to work around this, you can add a script action and run this line instead:

`self["cordova"]["InAppBrowser"]["open"]("https://www.construct.net", "_system");`

Update the URL in that call accordingly. It will only work in Cordova and still requires the Browser plugin to be in the project, but it will open the system webview instead of navigating in the app itself.

**Comment by AshleyScirra** [comment]
I've also removed the affected cordova plugin version from the build service, which should also prevent it happening from subsequent builds. So that should mean it's fixed already if you rebuild. I'll wait until the next stable release to redeploy the update along with the updated code that works with it.

**Comment by Mr-Josh-web** [comment]
Hi Ashley,

I have just exported the C3 project using the latest beta version (r206) and see what I got. Yesterday, it was working fine so it has to be something that has been changed on the server side and related with this topic.


![image](https://user-images.githubusercontent.com/67290437/86384563-33957700-bc8f-11ea-86c0-b166579c6955.png)

I do not give you more information as it is something that you have done recently and it is also pretty easy to test. Anyway, let me know if you need more information.

Regards.

**Comment by AshleyScirra** [comment]
Urgh, another complicated cordova compatibility problem. We have to choose whether it works on the stable channel or the beta channel. I've changed back the build service to work with the latest beta release. You'll have to use the other workaround I posted above in the mean time.

**Comment by Mr-Josh-web** [comment]
In that case, I will wait for the next stable release as I prefer not to do tricky stuff.

Thanks.

**Comment by whistlegraph** [comment]
Thanks Ashley for the current workaround. I know that integrating with Cordova can be a nightmare at times. 😱
