### ISSUE TITLE
Canvas Paste is cleared when scaling layout

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#3995]
## Problem description

I have a game that zooms in and out to keep multiple players in view. When they get injured, a blood splat is spawned, which is then pasted onto the canvas. The scene can zoom and pan without issues, but I note that if the canvas is zooming and a new object is pasted onto the canvas, the most recent paste will remain, but the others are cleared. It's as though the canvas is erased, then the new item is pasted. As far as I can tell, this only happens when zooming, and not when panning.

## Attach a .c3p

[PasteZoomBug.zip](https://github.com/Scirra/Construct-3-bugs/files/4843236/PasteZoomBug.zip)

## Steps to reproduce

1. Place an object, the mouse object and the Drawing Canvas into a layout.
2. Set up events that will have the object paste onto the canvas upon mouse click.
3. Have it set that the layout will start to scale when the object is pasted.

## Observed result

As soon as it starts zooming and a new object is pasted, every other pasted object is deleted. Note that if another object isn't pasted, there is no issue with zooming.

## Expected result

I expect the previously pasted objects to remain, and the new object pasted. Not for them to be cleared away.

## More details

This was possible on Construct 2 with the Paster object.

**Comment by AshleyScirra** [comment]
This is currently by design. See the section "Handling resizing and resolution" in the [manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/drawing-canvas).

**Comment by KekGames** [comment]
In that case, does keeping thousands of static invisible sprites with no behaviors affect performance in any way?

**Comment by AshleyScirra** [comment]
As ever, by far the best way to identify if something matters to performance or not, is to measure it.
