### ISSUE TITLE
After using the "Load" System Action, an event, in which a new instance of an object is created, seems to pick EVERY instance instead of the new one

### ISSUE THREAD

**Issue by VonFirflirch** [Scirra/Construct-3-bugs#3998]
## Problem description

My project is divided into many rooms across several layouts. When entering a room, spawner objects within will each generate an enemy based on certain parameters. This works perfectly fine.

However, when I started implementing a Save system, I found out that, **after Loading a slot**, the actions of the spawner object with the last Unique ID **apply to EVERY enemy instance instead of only the one spawned** in its own sub-event.

To make matters worse, it feels inconsistent. Sometimes it doesn't happen. Sometimes it does and fixes itself by exiting the room and coming back. On occasion it takes several attempts to fix itself. And rarely, another, similar event will break and not the one I noticed.

I'm very sorry for being rather vague, I really don't fully grasp what's going on here, myself.

<details><summary>I've recorded videos of it happening, just in case</summary>

Error in the submitted project, available below (shorter) :

https://youtu.be/gDWS8bk3leA

Error in my actual project :

https://youtu.be/RlghULmifm4

</details>

## Attach a .c3p

https://www.dropbox.com/s/zz1efjz0nsdhu5s/Save_Loading_Issue.c3p?dl=0

Things break in the Function called "F_Spawn Enemy"

## Steps to reproduce

1. Preview the project, a slot is saved to as soon as the layout starts ;
2. Using the arrow keys, fall down the pit ;
3. Notice how every enemy spawns and works correctly. The text at the top of the screen should show only 1 instance picked ;
4. Touch the spikes at the bottom to load the slot ;
5. Fall again. I've observed that it might take a few suicide attempts ;
6. If the issue occurs, you can perform a high jump with the down arrow key to leave the room and come back, which can sometimes, somehow, fix things.

## Observed result

Every enemy will spawn as the one specified in the last Spawner Object. The text at the top of the screen will show that every instance was picked, including the one that was just destroyed when changing rooms.

## Expected result

Things should play out the same as before the slot was loaded.

## More details

**Affected browsers/platforms:** 

Chrome/Microsoft Edge on Windows

**First affected release:** 

It first happened to me using r204

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r205 (beta)
Language setting: fr-FR

Local storage
Storage quota (approx): 274 gb
Storage usage (approx): 170 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 705 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

Thank you for your time and my apologies if this turns out to just be an issue on my end.

**Comment by AshleyScirra** [comment]
It's nearly impossible to debug a project with more than a few events, which is why the guidelines ask to provide a minimal project. Can you provide one?

**Comment by VonFirflirch** [comment]
> It's nearly impossible to debug a project with more than a few events, which is why the guidelines ask to provide a minimal project. Can you provide one?

Sorry about that, I thought this would be small enough. I'll try to narrow things down.

**Comment by VonFirflirch** [comment]
I've shrunk it down to 11 events, will it be okay?
https://www.dropbox.com/s/zz1efjz0nsdhu5s/Save_Loading_Issue.c3p?dl=0

**Comment by AshleyScirra** [comment]
Thanks, it turned out to be a subtle issue in the savegame system and the 'Spawn' action. It should be fixed in the next beta.
