### ISSUE TITLE
Bluetooth in APK

### ISSUE THREAD

**Issue by HarperLewis309** [Scirra/Construct-3-bugs#3999]
---
name: Bluetooth in APK
about: Bluetooth won't work in APK, works in Remote Preview
title: ''
labels: ''
assignees: ''

---

## Problem description

Bluetooth connection work when I use Remote Preview on my phone, but it doesn't when I build a DebugAPK? It simply won't connect with the device, even though everything is identical in browser and apk.

## Attach a .c3p

Your own example file: 
[https://editor.construct.net/#open=bluetooth-device-name](url)

## Steps to reproduce

1. Run in Remote Preview on an Android phone and connect to any Bluetooth device. It should work.
2. Build a DebugAPK. Same thing, but it cannot connect.
## Observed result

"Requesting device failed" message.

## Expected result

"Device connected! (ID: [i]" & Bluetooth.DeviceID & "[/i])"

## More details

**Affected browsers/platforms:** Android

**First affected release:** I never got it to work, but I'm a new user.

## System details

<details><summary>View details</summary>

Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r204.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 139 gb
Storage usage (approx): 154 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon (TM) R9 380 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks like the Android WebView doesn't support bluetooth. There are a few features that Chrome has that don't work in WebView, and I guess this is one of them. It's probably because it involves the browser UI for listing and pairing with bluetooth devices, which is not available in the WebView. I filed a Chrome issue here which you can follow for updates, but I doubt anything will change quickly: https://bugs.chromium.org/p/chromium/issues/detail?id=1100993
