### ISSUE TITLE
Paste Copied Object With Middle Click Crashed

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#4]
## Problem description

Seems like pasting a copied object with Middle-click crash the engine even using CTRL+Drag then Middle-click.

## Steps to reproduce

1. Copy an object from the editor.
2. CTRL+V
3. Middle-click to paste at cursor location rather than using left-click.

## Observed result

Crashed with the cursor in moving layout view mode.

## Expected result

Don't crash and just paste the object.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r16/main.js, line 2, col 285224
Message: Uncaught Error: pointer already captured
Stack: Error: pointer already captured at Function.ǃQr (https://editor.construct.net/r16/main.js:2:285230) at s.ǃgs (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:37586) at Array.ǃxP.u (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:37094) at ǃp.Event.ǃWXR.ǃWXG (https://editor.construct.net/r16/main.js:2:283188) at window.ǃUN.dispatchEvent (https://editor.construct.net/r16/main.js:2:281769) at window.ǃUN.ǃgs (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:13559) at HTMLDivElement.ǃqD.ǃp.ǃqx.ǃp.ǃqH.ǃqR.j (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:3958) at HTMLDocument. (https://editor.construct.net/r16/main.js:2:278451)
Construct 3 version: r16
URL: https://editor.construct.net/index.html
Date: Fri Apr 07 2017 01:00:24 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 19.2 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Fixed for r17
