### ISSUE TITLE
Trying to swap order of layouts in Project bar

### ISSUE THREAD

**Issue by dzibus** [Scirra/Construct-3-bugs#40]
## Problem description

When i tried to swap order of layouts in Project bar by dragging last one to the top, it crashed.

## Steps to reproduce

1. Make new layout
2. Drag it above existing

## Observed result

Crash with unhandled exception

## Expected result

Expected to swap order of displayed layouts in Project bar

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r16/main.js, line 61, col 71864
Message: Uncaught TypeError: ne.ǃoU is not a function
Stack: TypeError: ne.ǃoU is not a function at ee.ǃak (https://editor.construct.net/r16/main.js:61:71864) at window.ǃXX.ǃXX.ǃrw (https://editor.construct.net/r16/components/bars/projectBar/projectBar.js:1:13544) at window.ǃXX.ǃXX.ǃqd (https://editor.construct.net/r16/components/bars/projectBar/projectBar.js:1:13460) at Array.ǃqD.ǃp.ǃz.ǃp.ǃqH.ǃqR.m (https://editor.construct.net/r16/components/bars/projectBar/projectBar.js:1:3231) at ǃp.Event.ǃWXR.ǃWXG (https://editor.construct.net/r16/main.js:2:283188) at ǃp.ǃd.ǃLo.ǃqN.dispatchEvent (https://editor.construct.net/r16/main.js:2:281769) at ǃp.ǃd.ǃLo.ǃqN.ǃpYE (https://editor.construct.net/r16/main.js:2:488082) at ǃp.ǃd.ǃLo.ǃUT.ǃgP (https://editor.construct.net/r16/main.js:2:494666) at HTMLDocument.ǃRP.ǃgX.he (https://editor.construct.net/r16/main.js:2:490605) at HTMLDocument. (https://editor.construct.net/r16/main.js:2:278451)
Construct 3 version: r16
URL: https://editor.construct.net/
Date: Fri Apr 07 2017 22:45:05 GMT+0200 (Central Europe Daylight Time)
Uptime: 303.3 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.54
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.54 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 6450 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by jaydonteh** [comment]
Duplicate: https://github.com/Scirra/Construct-3-bugs/issues/21
