### ISSUE TITLE
Z-bar isn't highlighting the sprite selected via layout.

### ISSUE THREAD

**Issue by 3dParadox** [Scirra/Construct-3-bugs#400]
## Problem description

Z-bar isn't highlighting the sprite selected via layout. 

(click a sprite in the layout, all the sprites touching it show in the Zbar, but the one highlighted in the layout isn't highlighted in the zbar list. )

(edit: ooh #400, do i get a prize? 
posted report as suggested by DiegoScirra)
## Attach a .c3p

https://www.dropbox.com/s/t2fsel0mvmpios5/Z-barHighlights.c3p?dl=0

## Steps to reproduce

1. look at the layout in the editor of the attached C3P.
2. click on the blue sprite.
3. Look at the z-order bar, and notice you can't tell where the selected blue sprite is, using the list alone.

## Observed result

The Z-Order bar shows all sprites touching the selected sprite, but doesn't highlight the selected one.
The other way around does work. Click in the list and the sprite gets highlighted in the layout and the zbar.

## Expected result

When all the sprites touching the selected one are shown, the selected one should be obvious in the list.

## Affected browsers

* Chrome: yes/

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r32

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 269 mb (0.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R7 370 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in r33.
