### ISSUE TITLE
Tween Crash r206

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#4002]
## Problem description

Changing layout while a tween is running crashes the game.
![image](https://user-images.githubusercontent.com/2965842/86160457-7252f200-bb14-11ea-952f-0c10a92bbc89.png)

I think it's connected to this fix https://github.com/Scirra/Construct-3-bugs/issues/3997

## Attach a .c3p

[tween crash.zip](https://github.com/Scirra/Construct-3-bugs/files/4853649/tween.crash.zip)

## Steps to reproduce

1. Open the attached c3p and start from Layout 1.
2. Press "S" to go Layout 2 while tween is running.
3. Crash

## More details

**Affected browsers/platforms:** 

**First affected release:** r206

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by chunchuna** [comment]
I'm in the same situation as you! The problem is that I don't use any tween or timeline at all.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.

**Comment by Mr-Josh-web** [comment]
Hi Diego,

Do you when the next beta version will be released?

Regards.

**Comment by alastajj** [comment]
My game is unplayable, I hope this gets hotfixed! thanks

**Comment by bilgekaan** [comment]
Any news from the new beta?
