### ISSUE TITLE
Apk generate version 206 error

### ISSUE THREAD

**Issue by guimaraf** [Scirra/Construct-3-bugs#4003]
## Problem description

I have a project that was generating and signing normally, I updated the engine to version 206 beta, which is using Cordova 9, since then it no longer generates APK.

## Steps to reproduce

As I have a good knowledge of Cordova, having the necessary configuration on my equipment, I installed Cordova Android 8.1.0 in my project and managed to generate it without problem and with all the resources of the APK.
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=~~/androidSDK (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
Using Android SDK: ~~/androidSDK
:wrapper

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
> Task :app:preBuild UP-TO-DATE
> Task :app:preReleaseBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preReleaseBuild UP-TO-DATE
> Task :CordovaLib:packageReleaseRenderscript NO-SOURCE
> Task :app:compileReleaseRenderscript NO-SOURCE
> Task :app:generateReleaseResValues
> Task :app:generateReleaseResources
> Task :CordovaLib:compileReleaseRenderscript
> Task :CordovaLib:generateReleaseResValues
> Task :CordovaLib:generateReleaseResources
> Task :CordovaLib:packageReleaseResources
> Task :app:createReleaseCompatibleScreenManifests
> Task :app:extractDeepLinksRelease
> Task :CordovaLib:extractDeepLinksRelease
> Task :CordovaLib:processReleaseManifest
> Task :app:processReleaseManifest
> Task :CordovaLib:compileReleaseLibraryResources
> Task :CordovaLib:compileReleaseAidl NO-SOURCE
> Task :CordovaLib:generateReleaseBuildConfig
> Task :app:mergeReleaseResources
> Task :CordovaLib:parseReleaseLocalResources
> Task :CordovaLib:generateReleaseRFile
> Task :CordovaLib:javaPreCompileRelease
> Task :CordovaLib:compileReleaseJavaWithJavac
> Task :app:bundleReleaseResources
> Task :CordovaLib:bundleLibRuntimeToJarRelease
> Task :app:checkReleaseDuplicateClasses
> Task :app:compileReleaseAidl NO-SOURCE
> Task :app:generateReleaseBuildConfig
> Task :app:javaPreCompileRelease
> Task :app:processReleaseResources
> Task :CordovaLib:bundleLibCompileToJarRelease

> Task :app:compileReleaseJavaWithJavac

> Task :app:dexBuilderRelease
> Task :app:desugarReleaseFileDependencies
> Task :app:mergeReleaseShaders
> Task :app:compileReleaseShaders NO-SOURCE
> Task :app:generateReleaseAssets UP-TO-DATE
> Task :CordovaLib:mergeReleaseShaders
> Task :CordovaLib:compileReleaseShaders NO-SOURCE
> Task :CordovaLib:generateReleaseAssets UP-TO-DATE
> Task :CordovaLib:packageReleaseAssets
> Task :app:mergeReleaseAssets
> Task :app:processReleaseJavaRes NO-SOURCE
> Task :CordovaLib:processReleaseJavaRes NO-SOURCE
> Task :CordovaLib:bundleLibResRelease NO-SOURCE
> Task :app:mergeReleaseJavaResource
> Task :app:mergeReleaseJniLibFolders
> Task :CordovaLib:mergeReleaseJniLibFolders
> Task :CordovaLib:mergeReleaseNativeLibs
> Task :CordovaLib:stripReleaseDebugSymbols NO-SOURCE
> Task :CordovaLib:copyReleaseJniLibsProjectOnly
> Task :app:mergeReleaseNativeLibs
> Task :app:stripReleaseDebugSymbols NO-SOURCE
> Task :app:collectReleaseDependencies
> Task :app:configureReleaseDependencies
> Task :app:parseReleaseIntegrityConfig
> Task :app:mergeExtDexRelease
> Task :app:mergeDexRelease
> Task :app:buildReleasePreBundle
> Task :app:packageReleaseBundle
> Task :app:signReleaseBundle
> Task :app:bundleRelease

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https:/~~/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 11s
44 actionable tasks: 44 executed
Built the following bundle(s):
~~/app-release.aab

</details>

**Comment by guimaraf** [comment]
I downloaded the project from my google drive, to change the saved version, so it was possible to open it again in the stable version and the APK was generated without problems.

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to investigate reports unless you follow the guidelines - in particular attaching a project. I just tried both a debug and signed APK build and both worked fine. Also the log you provided seems to indicate that the build succeeded...

**Comment by guimaraf** [comment]
However did not generate the project for download

**Comment by guimaraf** [comment]
I use the following plugins in the project.
GooglePlay
MobileAdvert
MobileIAP

All officers

I remember having problems working only with Cordova CLI in the past, where Cramberry's google play game plugin didn't compile for Cordova Androir 7, so I had to change the plugin's internal dependency in order to be able to compile. This was done to generate APK of construct 2 with this feature.
