### ISSUE TITLE
Timeline - Ease name not changed dynamically in timelines when rename

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#4007]
## Problem description

Ease name not changed dynamically in timelines when rename.
It cause crash.

## Attach a .c3p

https://drive.google.com/file/d/1L0tXcBqck-NvME4HWu21kPSkF3196daD/view?usp=sharing

## Steps to reproduce

1. Add ease to timeline
2. Rename ease
3. In timeline ease not renamed

## Observed result

In timeline ease not renamed. Later it cause crash

## Expected result

In timeline ease renamed dynamically.

## More details
Before:
![before](https://user-images.githubusercontent.com/47735877/86222570-baaaf800-bb86-11ea-8469-c6cb9ae21d66.png)

After:
![after](https://user-images.githubusercontent.com/47735877/86222620-c991aa80-bb86-11ea-9e1a-87e45ca465d0.png)

## System details
<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r206/projectResources.js, line 512, col 375
Message: Uncaught TypeError: l.sea(...) is not a function
Stack: TypeError: l.sea(...) is not a function at h.co (https://editor.construct.net/r206/projectResources.js:512:375) at t.co (https://editor.construct.net/r206/projectResources.js:462:203) at h.r3c (https://editor.construct.net/r206/components/editors/layoutView/layoutView.js:119:224) at h.O3 (https://editor.construct.net/r206/components/editors/layoutView/layoutView.js:115:74) at Array. (https://editor.construct.net/r206/components/editors/layoutView/layoutView.js:110:72) at Object.x4c (https://editor.construct.net/r206/main.js:429:387) at Object.dispatchEvent (https://editor.construct.net/r206/main.js:425:135) at Object.zld (https://editor.construct.net/r206/components/editors/layoutView/layoutView.js:14:197) at https://editor.construct.net/r206/components/editors/layoutView/layoutView.js:4:355
Construct 3 version: r206
URL: https://editor.construct.net/r206/
Date: Wed Jul 01 2020 10:26:19 GMT+0200 (közép-európai nyári idő)
Uptime: 175.3 s

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r206 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 640M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_video_texture, OVR_multiview2
</details>

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r206 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 943 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 640M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
