### ISSUE TITLE
Tilemap crash when undo and redo tile with collision disabled

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4014]
## Problem description
Case when you remove tile collisions, remove tile and you undo and redo it

## Steps to reproduce

1.Open new, add tilemap, set resize 1x1, close tilemap editor
2.Select tilemap, set tilesize in properties to 1x1, open tilemap resize to 1x2, close editor
3.Select tilemap editor, zoom in, select '1' tile, open tile edit and remove collosions, click on tilemap and reize tilemap to 1x1
4.Click undo and redo. 3 undo should crash

## Observed result
Tilemap/C3editor will crash

## Expected result
No crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: animation frame has no content @ Error: animation frame has no content at m.KH (https://editor.construct.net/r206/projectResources.js:189:232) at m.va (https://editor.construct.net/r206/projectResources.js:196:441) at Object.Qf (https://editor.construct.net/r206/projectResources.js:1098:34) at Object.Qf (https://editor.construct.net/r206/projectResources.js:1085:428) at Object.Qf (https://editor.construct.net/r206/projectResources.js:1163:228) at Object.Lh (https://editor.construct.net/r206/projectResources.js:1089:153) at ja.Lh (https://editor.construct.net/r206/projectResources.js:979:9) at Object.Lh (https://editor.construct.net/r206/main.js:2060:206) at Array. (https://editor.construct.net/r206/main.js:1991:98) at Object.n4c (https://editor.construct.net/r206/main.js:429:217)
Stack: Error: animation frame has no content at m.KH (https://editor.construct.net/r206/projectResources.js:189:232) at m.va (https://editor.construct.net/r206/projectResources.js:196:441) at Object.Qf (https://editor.construct.net/r206/projectResources.js:1098:34) at Object.Qf (https://editor.construct.net/r206/projectResources.js:1085:428) at Object.Qf (https://editor.construct.net/r206/projectResources.js:1163:228) at Object.Lh (https://editor.construct.net/r206/projectResources.js:1089:153) at ja.Lh (https://editor.construct.net/r206/projectResources.js:979:9) at Object.Lh (https://editor.construct.net/r206/main.js:2060:206) at Array. (https://editor.construct.net/r206/main.js:1991:98) at Object.n4c (https://editor.construct.net/r206/main.js:429:217)
Construct 3 version: r206
URL: https://editor.construct.net/r206/
Date: Sun Jul 05 2020 16:03:36 GMT+0300 (Eastern European Summer Time)
Uptime: 9526.2 s

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r206 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
