### ISSUE TITLE
Tilemap will crash when tilemap editor had tile collisions disabled last time you used it

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4015]
## Problem description
Previous project you had tile collision disabled with tilemap, you close  that one and open new project add tilemap and boom crash. See error message

## Steps to reproduce

1.(incognito mode)Open new, add tilemap, resize to 1x1, close editor
2.Select tilemap and resize  size in properties to 1x1
3.Navigate to tilemap editor zoom in much as you can. Click on tile and disable collisions. Close project
4.Open new project, add tilemap.  --- > crash

## Observed result
Old settings 'tile collision disabled' will crash new project with tilemap

## Expected result
No crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: cannot find id @ Error: cannot find id at Object.drb (https://editor.construct.net/r206/projectResources.js:27:438) at Object.drb (https://editor.construct.net/r206/projectResources.js:17:215) at g.u (https://editor.construct.net/r206/projectResources.js:31:416) at mIa (https://editor.construct.net/r206/projectResources.js:179:287) at m.u (https://editor.construct.net/r206/projectResources.js:179:99) at Object.u (https://editor.construct.net/r206/projectResources.js:1199:45) at Object.p0a (https://editor.construct.net/r206/projectResources.js:1177:441) at Object.rpd (https://editor.construct.net/r206/projectResources.js:1178:152) at https://editor.construct.net/r206/projectResources.js:1178:348
Stack: Error: cannot find id at Object.drb (https://editor.construct.net/r206/projectResources.js:27:438) at Object.drb (https://editor.construct.net/r206/projectResources.js:17:215) at g.u (https://editor.construct.net/r206/projectResources.js:31:416) at mIa (https://editor.construct.net/r206/projectResources.js:179:287) at m.u (https://editor.construct.net/r206/projectResources.js:179:99) at Object.u (https://editor.construct.net/r206/projectResources.js:1199:45) at Object.p0a (https://editor.construct.net/r206/projectResources.js:1177:441) at Object.rpd (https://editor.construct.net/r206/projectResources.js:1178:152) at https://editor.construct.net/r206/projectResources.js:1178:348
Construct 3 version: r206
URL: https://editor.construct.net/r206/
Date: Sun Jul 05 2020 16:21:57 GMT+0300 (Eastern European Summer Time)
Uptime: 132.3 s

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r206 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
