### ISSUE TITLE
Local Storage plugin does not resume if saved in c2runtime and run in c3runtime.

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#4018]
If you add the LocalStorage plugin to the C3 (c2runtime) project and save the values ​​by running C3 (c2runtime), and then switch to C3 (c3runtime), then the LocalStorage values ​​will not be loaded from the c2runtime launch, but will be saved and loaded in the c3runtime environment. This should not be, LocalStorage values ​​from c2runtime should be loaded into c3runtime, as well as vice versa.

**Comment by AshleyScirra** [comment]
I can't investigate a report like this, but I think it's by design anyway, we intentionally changed storage compatibility with the C3 runtime.
