### ISSUE TITLE
Problems playing videos on MacOS (Safari)

### ISSUE THREAD

**Issue by zaxonica** [Scirra/Construct-3-bugs#4022]
## Problem description
Video does not play on MacBook (macOS Catalina, Safari 13.1.1 and Safari 14.0)
Video: mp4, h264

## Attach a .c3p
https://drive.google.com/file/d/1qvzEcW0dNsMAgxmojucUft9voK-UG0jc/view?usp=sharing

## Steps to reproduce

1.Use MacBook click on the link: https://clever-williams-b38577.netlify.app/
2.Click on the video

## Observed result
The video doesn't play back

## Expected result
The video is being played

## More details

**I found an error. When you switch runtime to Construct2, the video is played. If I switch runtime to Construct3, the video doesn't work.**

Log console:
https://construct-static.com/images/v817/uploads/articleuploadobject/0/images/43874/zaksoid.jpg
**Affected browsers/platforms:** 
macOS Catalina, Safari 13.1.1 and Safari 14.0

**First affected release:** 
Release r204.2 stable
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It works fine here on both macOS and iOS. You just have to tap twice, because of Safari's autoplay restrictions.
