### ISSUE TITLE
[Whitelist] Request adding  cordova-plugin-device-orientation

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#4024]
Hi,

I would like to request the whitelisting of the cordova-plugin-device-orientation@2.0.3

This is needed for getting absolute compass heading, the current Touch orientation ACEs get a relative compass heading (relative to app start position.)

Thank you.

**Comment by AshleyScirra** [comment]
The plugin [states it is deprecated and not needed any more](https://github.com/apache/cordova-plugin-device-orientation), so I don't think you should be using it. Why do you think it's needed?

**Comment by MikalDev** [comment]
Yes, we have been through the details, of the deprecation, etc. The issue is that the web api (and the C3 Touch orientation ACEs) implementations only give _relative_ compass heading. They do not give absolute compass heading. We are using it for a map based app for C3, so of course absolute heading is required.

This plugin does give access to the absolute compass heading (we have tested it with C3 on iOS and Android devices by doing a local Cordova CLI build with a custom C3 addon.) Testing the same devices with the C3 Touch orientation only gives relative compass heading (e.g. it gets zeroed out on app start and only reports delta from initial heading.)

The geolocation  web api and C3 plugin do have absolute heading, but it requires that the user to be in motion (it detects heading based on changes in movement and translates it into a compass heading vector.) So this does not work well when the user is standing is still and just rotating the mobile device, which is very useful for a app which includes a map.

If you see another way to get absolute compass heading (e.g. magnetic heading, not relative) from the Touch orientation, that would be good also of course!

**Comment by AshleyScirra** [comment]
Huh, that sounds like a bug if the alpha value is not relative to north. It's [documented on MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Orientation_and_motion_data_explained) as being relative to north:

> The alpha angle is 0° when top of the device is pointed directly toward the Earth's north pole, and increases as the device is rotated toward the left.

It looks like on iOS we should use `webkitCompassHeading` instead for the compass heading (which I thought was what the alpha value is for). Is it only iOS that you need this for? If so I'd prefer to change the alpha value returned by Construct's Touch object to that, which should then mean we don't have to add support for a deprecated Cordova plugin.

**Comment by MikalDev** [comment]
Unfortunately it does not seem to be implemented as documented and originally there have been changes down the line:

https://developers.google.com/web/updates/2016/03/device-orientation-changes

A new event was added for absolute, but my investigations so far on iOS Safari and iOS Chrome show they don't exist.

We do want support in both iOS and Android (as best we can, even with the Cordova plugin I had one Android phone show absolute and one show relative still, the iOS phone showed absolute.)

So, unfortunately the standard web api implementations look like they still do relative and don't support the new absolute event on mobile Chrome / Safari in iOS. So they only way we know of is use the deprecated plugin (yes we would prefer not to, but it seems like we don't have a real choice if we want both iOS and Android support.)

I keep searching for another 'cleaner' answer, one thought now is to try:

- Window.ondeviceorientationabsolute for Android only (some phones may support it, it is also non-standard)
(see: https://developer.mozilla.org/en-US/docs/Web/API/Window/ondeviceorientationabsolute)
- webkitCompassHeading in iOS, which does seem reliable (perhaps the cordova plugin uses this.)

**Comment by AshleyScirra** [comment]
Relying on deprecated features is asking for trouble really - a future update could break it, nobody will support it since it's deprecated, and then you're back to square one looking for another way to solve the problem. So it's best to find another way to solve the problem if at all possible. I'll look in to those other features for absolute orientation.

**Comment by AshleyScirra** [comment]
I've added a `CompassHeading` expression to the Touch object for the next release to separately provide the true compass heading, relying on either `webkitCompassHeading` or `deviceorientationabsolute`. Hopefully this eliminates the need to rely on a Cordova plugin for the purpose, and also provides the feature on the web too. I've tested it myself but it would be useful if you could review it at the next release and verify if it suits your particular purpose.

**Comment by AshleyScirra** [comment]
r208 adds a 'CompassHeading' expression to the Touch object. Can you check if this solves the problem?

**Comment by MikalDev** [comment]
Thanks for adding this, will test it out on a few devices this week and reply here.

**Comment by MikalDev** [comment]
I tried it out:

- ios / iPhone XR: works! Absolute compass heading is provided.
- Android / Moto G6: fails (only relative setting)
- Android / S6: fails (only relative setting)

Comparing to the device orientation plugin:
- iOS / XR works (absolute)
- Android / Samsung works (absolute)
- Android / MotoG6 fails (relative)

It looks the implementation of the various compass APIs is not very consistent unfortunately (for web API or for cordova implementation.) I am thinking to close this, I'm not sure of any more progress to make. Thanks for the update so that at least iOS seems fairly reliable. I understand your comments about not including a deprecated plugin, so for now we may have to live with using the Cordova CLI instead of C3 build service.

**Comment by AshleyScirra** [comment]
FWIW, I get a CompassHeading on a Pixel 3 with Android 10. I'm not sure why it wouldn't provide a value on some devices 🤷‍♀️ Chrome 69+ appears to also support `AbsoluteOrientationSensor` via the generic sensor API, but no other browsers support that, and adding it to Construct would require quite a significant reworking of how the sensor code all works. This is quite a mess 😕 If you're happy with a bit of JavaScript coding, I'd give the `AbsoluteOrientationSensor` a go for Chrome support, it might work across more devices.

Anyway, closing this issue as there's no intent to add support for the Cordova plugin.

**Comment by MikalDev** [comment]
Thanks for the work Ashley, at least iOS will generally be ok.

**Comment by AshleyScirra** [comment]
@MikalDev - it's not in the changelog but in r209 I made a slight change to how CompassHeading is read, which might help it work on more devices. I'm not sure if it'll fix things but it might be worth testing again with the Android devices.
