### ISSUE TITLE
AJAX triggers "ON REQUEST COMPLETED" with Old Data!

### ISSUE THREAD

**Issue by shubhamrathi9** [Scirra/Construct-3-bugs#4027]
## Problem description

Hi,

I have implemented AJAX in one of my games to retrieve data and i noticed that it showed the same data even after i restarted the game with no internet!

After some testing, it seems like once the data is retrieved by AJAX, it stays saved somewhere even after closing the game! And when we open it again, it triggers the "ajax request completed" with the old data!

Also, I noticed that once data is retrieved, even with the internet on it does not update the data, it just triggers request completed with old data saved in it somewhere!

## Attach a .c3p
[AJAX Test](https://drive.google.com/file/d/19t1H2dQQS9gnjBFDGinqbnWf0LJw4HT6/view?usp=sharing)

## Steps to reproduce

Steps to reproduce :

AJAX "On Request Completed" gets triggered and Old Data Still gets retrieved!
1. Preview with Internet connection!
2. Close Preview!
3. Preview again with/without Internet Connection!
4. Old data is shown, doesn't matter if there is no internet connection, or if you have updated the data on your server!
5. You can try the above steps with a link of your own and change data, it happens with apk installed on a device, you can close the app and relaunch it without internet, the old data is received!

## Observed result

Old data is shown, doesn't matter if there is no internet connection, or if you have updated the data on your server!
You can try the above steps with a link of your own and change data, it happens with apk installed on a device, you can close the app and relaunch it without internet, the old data is received!
## More details

The AJAX should not trigger "On request completed" without actually retrieving data! Also once the data is retrieved, the updated data doesn't get retrieved even with an internet connection and it keeps getting triggered with old data!

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r204 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 381 gb
Storage usage (approx): 164 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
It's just caching. The server sends a response with `cache-control: max-age=604800`, 604800 being one week in seconds. So the server is saying "here's some data, and you don't need to ask for this again for one week". Even if you go offline the browser will keep loading it from the local cache, since the server said it could.

**Comment by shubhamrathi9** [comment]
I did not know that! Thank you very much for the info!
