### ISSUE TITLE
Flip Horizontally and Flip Vertically are switched.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4029]
## Problem description
**Flip Horizontally** and **Flip Vertically** functions are switched.

Kindly fix, thanks.

**Comment by AshleyScirra** [comment]
It's not clear which feature you are referring to. Please always follow the bug report guidelines.

**Comment by Chadori** [comment]
I thought it was pretty obvious. **The image editor**.
Looks pointless to make a sample reproduction, if it's the editor's button.

**Comment by Chadori** [comment]
![image](https://user-images.githubusercontent.com/31282960/87325760-73e4d700-c564-11ea-8dd0-0a77afe3def0.png)
(Just in case.)

**Comment by AshleyScirra** [comment]
There are many flip/mirror features across the editor (tilemap, runtime, etc.) They seem to work correctly in the animations editor for me.

This is why we always require following the bug report guidelines. If you miss out all those details, it ends up just not making any sense.

**Comment by Chadori** [comment]
Alright, got it.
