### ISSUE TITLE
Built-in Effect parameters do not account for pixel density of the display.

### ISSUE THREAD

**Issue by whistlegraph** [Scirra/Construct-3-bugs#4031]
## Problem description

Some of the built-in effect parameters lead to unexpected results when being used on displays with varying pixel densities. I feel that these effects / shaders should adjust accordingly.

**Normal Display**
![Screen Shot 2020-07-14 at 12 20 46 AM](https://user-images.githubusercontent.com/3620017/87384006-b4deea80-c568-11ea-83b5-bbdd8bbc9347.png)

**High Density**
<img width="812" alt="Screen Shot 2020-07-14 at 12 20 38 AM" src="https://user-images.githubusercontent.com/3620017/87384098-e952a680-c568-11ea-9bbc-dc29ebf689c5.png">

## Attach a .c3p

[PixelDensityEffectTester.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4916524/PixelDensityEffectTester.c3p.zip)

## Steps to reproduce

1. Run the example project from two different display types.

## Observed result

The parameters of the shader are multiplied in relation to the display density.

## Expected result

The shader parameters should be divided to account for the density delta.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r204.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 138 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 5500M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This might involve a significant overhaul of the effects compositor, which is one of the most complex parts of all of Construct so could prove difficult.

**Comment by whistlegraph** [comment]
Maybe it's something that could eventually be handled during the future migration to WebGPU?
