### ISSUE TITLE
Reopen: https://github.com/Scirra/Construct-3-bugs/issues/3888

### ISSUE THREAD

**Issue by whistlegraph** [Scirra/Construct-3-bugs#4032]
## Problem description

Hello, I would like to call attention to this previous bug that was fixed. I believe it should be re-opened because there is a regression that could affect quite a number of projects out there. Please see my comments here: https://github.com/Scirra/Construct-3-bugs/issues/3888#issuecomment-646866856

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I verified it was working when I closed that issue. If there is still a problem please file a new issue following all the guidelines again, since usually that means it's something different.
