### ISSUE TITLE
Color Selector Bug Part 2

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#4033]
## Problem description

Construct 3 has the same color selector bug again that I reported months ago.

## Attach a .c3p

[Colorbugagain.zip](https://github.com/Scirra/Construct-3-bugs/files/4916697/Colorbugagain.zip)

## Steps to reproduce

1. Open the object I provided in image editor.
2. Pick its color with CTRL + left click.
3. Close the image editor.
4. Reopen the object in image editor.

## Observed result

The RGB values are slightly skewed again.

## Expected result

This was determined to be incorrect behavior and the RGB values should be the same.

## More details

**Affected browsers/platforms:** Chrome, NWjs

**First affected release:** r204.2

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.44.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.44.0 (like Chrome/80.0.3987.87)
C3 release: r204.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 53 gb
Storage usage (approx): 235 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Can you point me to the old issue?

**Comment by DiegoScirra** [comment]
It looks like it was a regression starting in r198, it should be working properly again in the next beta.

**Comment by corlenbelspar** [comment]
Sorry, forgot to check for comments. Thanks for fixing it.
