### ISSUE TITLE
Minified exports not working in r207

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#4034]
## Problem description

Project fails to export (android) when minification is set to simple/advanced. Export works perfectly when no minification is set

## Attach a .c3p

Works with any file. Even empty one

## Steps to reproduce

Press f6 to export. Navigate to android option
Then set minification to either simple or advanced

## Observed result

A message appears" project failed to export"

## Expected result

I should get an APK at the end

Version is r207 latest beta

**Comment by LanciferStudios** [comment]
Yes, I'm also experiencing the same problem. No minification is possible with this version. Had to wait 20+ minutes just to see the error "Failed to export project". Works fine in latest stable.

**Comment by AshleyScirra** [comment]
There's a bug in Closure Compiler that is causing it to crash when minifying the runtime code, but it got fixed recently. I think updating the Closure Compiler version is sufficient to fix this, and that's done for the next beta. Note this isn't specific to any particular exporter (the original issue cited Android only). Leaving this issue open and marked fixed since I expect this will be a common thing people run in to.

**Comment by eleanorawesome** [comment]
In my project is works with simplified but fail with advanced
![image](https://user-images.githubusercontent.com/32940085/88094743-105d3980-cb62-11ea-942d-09a7bde5048a.png)
<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 84.0.4147.89
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
C3 release: r208 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 251 gb
Storage usage (approx): 796 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by layilpaht** [comment]
@AshleyScirra I am really sorry but still it is not working
Earlier in 207 beta the minification was failing.Now in 208 beta, APK file gets made in advanced mode,but on launching the app on mobile the game does not moves ahead of loading icon and loading bar.It simply gets hanged at that point
Sorry but this problem is hanging from last 3 betas

**Comment by AshleyScirra** [comment]
No project was provided with this report, so I could not test the issue in the first place. I tried Ghost Shooter instead, and reproduced the issue; that issue is now fixed in r208. Therefore as far as I can see the issue is fixed. If you believe there is a different issue, please file a new issue following all the guidelines, it's impossible to help without that.
