### ISSUE TITLE
9patch Object Displays Artifacts When Opacity < 100

### ISSUE THREAD

**Issue by netdzynr** [Scirra/Construct-3-bugs#4036]
## Problem description

The 9patch object displays visual artifacts at its margin joints when the object's opacity is set to less than 100.

Project is available here:  https://www.dropbox.com/s/9h5e5iuwbsxk1fr/9patch_artifacts.c3p?dl=0

## Steps to reproduce

Load the attached project in the Construct editor and run in preview.

## Observed result

Artifacts in the object are visible where the margins apparently overlap.

## Expected result

No artifacts should be visible.

**Affected browsers/platforms:** 

Chrome Version 83.0.4103.116

**First affected release:** 

Have never seen this working correctly.

## System details

MacOS 10.14.6 running on 2017 iMac

**Comment by dop2000** [comment]
Set Seems=Exact in 9patch properties.

**Comment by AshleyScirra** [comment]
@dop2000 is right. See the [9-patch manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/9-patch) for an explanation of that property.
