### ISSUE TITLE
Mirror vertically and horizontally are switched.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4037]
## Problem description

Mirror `vertically`and `horizontally` are switched.
![image](https://user-images.githubusercontent.com/31282960/87525931-c0dbc100-c6bc-11ea-807d-77c4a4ee74b3.png)

This focused icon should be for a `horizontal` flip.

**Comment by AshleyScirra** [comment]
The icon and image alteration is correct. I think the confusion comes from a misleading tooltip. "Mirror vertically" seems to really mean "mirror around a vertical axis". In other parts of Construct "mirror" implies invert on the X axis, and "flip" implies invert on the Y axis, so I think all we need to change is the tooltip to say "Mirror" and "Flip" only.
