### ISSUE TITLE
ANDROID EXPORT FAILED r206. r207.

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#4039]
I can't export my project in new versions of construct. Here is the error log when exporting. If you create a new project, the export process is  correctly.

## Steps to reproduce

Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=~~/androidSDK (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
Using Android SDK: ~~/androidSDK
:wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
The following AndroidX dependencies are detected: androidx.versionedparcelable:versionedparcelable:1.0.0, androidx.fragment:fragment:1.0.0, androidx.slidingpanelayout:slidingpanelayout:1.0.0, androidx.core:core:1.0.0, androidx.customview:customview:1.0.0, androidx.swiperefreshlayout:swiperefreshlayout:1.0.0, androidx.interpolator:interpolator:1.0.0, androidx.loader:loader:1.0.0, androidx.drawerlayout:drawerlayout:1.0.0, androidx.viewpager:viewpager:1.0.0, androidx.collection:collection:1.0.0, androidx.localbroadcastmanager:localbroadcastmanager:1.0.0, androidx.lifecycle:lifecycle-common:2.0.0, androidx.arch.core:core-common:2.0.0, androidx.annotation:annotation:1.0.0, androidx.legacy:legacy-support-core-ui:1.0.0, androidx.lifecycle:lifecycle-livedata:2.0.0, androidx.lifecycle:lifecycle-viewmodel:2.0.0, androidx.lifecycle:lifecycle-livedata-core:2.0.0, androidx.arch.core:core-runtime:2.0.0, androidx.legacy:legacy-support-core-utils:1.0.0, androidx.documentfile:documentfile:1.0.0, androidx.cursoradapter:cursoradapter:1.0.0, androidx.lifecycle:lifecycle-runtime:2.0.0, androidx.coordinatorlayout:coordinatorlayout:1.0.0, androidx.asynclayoutinflater:asynclayoutinflater:1.0.0, androidx.print:print:1.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 989ms
Command failed with exit code 1: ~~/gradlew cdvBuildRelease -b ~~/build.gradle

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
No project or steps to follow were provided, so I opened Ghost Shooter and built a debug APK. The build was successful.

Please always follow the bug report guidelines - they are there because we need that information to be able to help you.

**Comment by ibiz3091** [comment]
> Никаких проектов или шагов для выполнения не было предусмотрено, поэтому я открыл Ghost Shooter и построил отладочный APK-файл. Сборка прошла успешно.
> 
> Пожалуйста, всегда следуйте рекомендациям по сообщению об ошибках - они есть, потому что нам нужна эта информация, чтобы быть в состоянии помочь вам.

I found an error that is caused by the google play plugin. I made a project file for you: https://drive.google.com/file/d/1AojLctNW4KuGLeTL8D3t1JnLlBIEc4dR/view?usp=sharing

**Comment by AshleyScirra** [comment]
Thanks for the project, it did reproduce the problem. It looks like we have to adjust the AndroidX configuration since updating to cordova-android@9.0.0. It should be working again in the next beta.
