### ISSUE TITLE
Using RMB with brushes - doesn't erase tiles

### ISSUE THREAD

**Issue by KekGames** [Scirra/Construct-3-bugs#4043]
## Problem description

Using RMB while using brushes - doesn't erase tiles, but draws new ones.

## Attach a .c3p

[TilemapProject.zip](https://github.com/Scirra/Construct-3-bugs/files/4943138/TilemapProject.zip)

## Steps to reproduce

1. Select a tilemap brush
2. Try to erase tiles using RMB

## Observed result

Using RMB while using brushes - doesn't erase tiles, but draws new ones.

## Expected result

Erasing a tile without having to manually switch to eraser

**Comment by DiegoScirra** [comment]
In the latest beta you can use Ctrl+Click as a shortcut for the eraser.
