### ISSUE TITLE
Z order bar

### ISSUE THREAD

**Issue by iftikharlove555** [Scirra/Construct-3-bugs#4046]
## Error report information
Type: unhandled exception
File: https://editor.construct.net/r204-2/main.js, line 2, col 129370
Message: Uncaught Error: component id 'zOrderBar' already registered
Stack: Error: component id 'zOrderBar' already registered at window.ǃXb_.ǃiJ (https://editor.construct.net/r204-2/main.js:54:13791) at new window.ǃdv (https://editor.construct.net/r204-2/main.js:210:47245) at new window.ǃ$_ (https://editor.construct.net/r204-2/components/bars/zOrderBar/zOrderBar.js:1:243) at Function.a.ǃt (https://editor.construct.net/r204-2/main.js:2:129349) at Function.ǃdy (https://editor.construct.net/r204-2/components/bars/zOrderBar/zOrderBar.js:1:9834) at https://editor.construct.net/r204-2/components/editors/layoutView/layoutView.js:1:14813 at https://editor.construct.net/r204-2/main.js:52:43040
Construct 3 version: r204.2
URL: https://editor.construct.net/
Date: Mon Jul 20 2020 15:40:46 GMT+0400 (Gulf Standard Time)
Uptime: 201.4 s

Platform information
Browser: Chrome
Browser version: 84.0.4147.89
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Android
Operating system version: 10
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2.75
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 10; Redmi Note 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Mobile Safari/537.36
C3 release: r204.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: ARM
Renderer: Mali-G76 MC4
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_filter_anisotropic, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This error should be impossible. I'm afraid there's nothing we can do to help unless you follow the guidelines, we need that information to be able to help you.

**Comment by iftikharlove555** [comment]
It was first post on GitHub and i was editing it but I don't know how fast you came and closed it it was funny
