### ISSUE TITLE
Color selector size bugs

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4048]
## Problem description
Could be new chrome issue or some other issue. I don't know rly.

Case when default CSS bugs color selector size out, even in incognito mode.

See video. Bugs my theme out even harder!
[Buggy.zip](https://github.com/Scirra/Construct-3-bugs/files/4954004/Buggy.zip)

Default property: height: 100%  has bad influence on themes. Could need remove or change to revert, as i did!

## Steps to reproduce

1.Open default theme, new project, 
2.Properties bar, Witness color selector size, resize it left and right.
3.See color selector size changes size
4. Selecting layer  and going back to project bar reset size bug.

## Observed result
Color selector changes size because bad css property

## Expected result
No bug or bug other themes

## More details

also bugs previous releases, could origin from chrome.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I can't reproduce here, it works fine in both the default and dark theme.

I don't recognize the look of the Project Bar. If you are using a custom theme, the theme probably broke it, so you'd need to report it to whoever made the theme.

**Comment by SnipG** [comment]
I fixed it for myself and my theme. So i pointed it out for here too, so official themes could be fixed. But it does not affect me anymore, so it's no big deal if it says like that.

**Comment by AshleyScirra** [comment]
As far as I can tell, it doesn't affect the official themes. I couldn't reproduce it.
