### ISSUE TITLE
Export to nw.js v0.33.3 leads to a project that opens with unexpected results

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#4049]
## Problem description

Opening the executable of a nw.js v0.33.3 exported project leads to unexpected results.
Because of the official plugin Greenworks I have to (see documentation https://www.construct.net/en/make-games/addons/84/greenworks/0-33-3-r2-253) use nw.js v0.33.3. 
But exporting a project in this nw.js version to windows leads to unexpected results when opening the executable.
(Some examples: I used it on my game: no text objects visible, when full screen the screen does not get refreshed. I used it on a test project with a sprite and text object: only a black screen when running the exported project.)
When I export using the latest nw.js, the project can be opened fine.
I have tried to change several options when exporting to v0.33.3 but nothing changed the outcome. (examples: turned off minifier, turned off deduplicate, turned off decompress, only exported to win64, only exported to win32)

## Attach a .c3p

(see below in the comments)

## Steps to reproduce

1. Run the executable (of the in nw.js v0.33.3 exported project)
2.
3.

## Observed result

A window appears, inside there is a black colour.

## Expected result

A window to appear, with inside a white background and 2 objects: a sprite and a text object (the sample project).

## More details

The last time I tried this - and it worked as expected - was in februari 2020.
I always update C3 to use the latest beta releases and I am always connected to the internet.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 84.0.4147.89
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
C3 release: r208 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 38 gb
Storage usage (approx): 2.5 gb (6.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by rogerty** [comment]
[nwjsv0333.zip](https://github.com/Scirra/Construct-3-bugs/files/4954200/nwjsv0333.zip)

**Comment by rogerty** [comment]
The attachment is a renamed c3p file. It is a sample project with only 2 objects added. This project is what I used to export to win64 and nw.js v0.33.3

**Comment by BonzerKitten** [comment]
That's very interesting. I'm leaving a reply here so I can get more notifications about this topic, I'm interested because I also use the Greenworks plugins extensively.

**Comment by AshleyScirra** [comment]
Does it work better if you set 'Use worker' to 'No' in project properties?

NW.js 0.33.3 is really old now and there's not much point trying to support it. We should update Greenworks instead, but they [haven't made any official releases since then](https://github.com/greenheartgames/greenworks/releases), which makes it trickier and is why we haven't updated it so far, since it means figuring out some alternative...

**Comment by rogerty** [comment]
Thanks for the quick reply!
I have set 'Use worker' to 'No', here's the result:
- tested on the attached sample: runs as expected.
- tested on my game project: runs as expected. (*)

*exporting using minifying script still gives me the error "failed to export", but I will ignore this for now, because the export works when I turn off minifying.

So this workaround works for me, thanks!

About figuring out an alternative to Greenworks, perhaps make a tutorial on how to use javascript to access some features of the Steam API + an example? I am not skilled at javascript, but your tutorials are helpful and with an example and learning basic knowledge of Javascript, I might get it working perhaps.

**Comment by AshleyScirra** [comment]
I've updated the Greenworks plugin to work with NW.js 0.47.0: https://www.construct.net/en/make-games/addons/84/greenworks

Does it work better with that if you leave "Use worker" enabled?

**Comment by rogerty** [comment]
Yes, the update on the Greenworks plugin you made seems to solve the problem!
I exported my game to JW.js v0.47 en the problems I mentioned before are gone, the game works as expected.
Thank you!

Note: I still get a "failed to export" when using minify, but that could be my project, or something on my computer. I have to investigate that another time and fix it or turn that into a new bug report.

**Comment by AshleyScirra** [comment]
OK, thanks for confirming. Closing since there's no need to get NW.js 0.33.3 to work now.

**Comment by BonzerKitten** [comment]
@AshleyScirra I was not sure if I should open a new issue, because I believe the problem I just found is related to this change in the Greenworks plugin. Today I released a new update for one of my games and couldn't trigger any achievement, after checking my console I found this error: https://i.imgur.com/4DLPdWe.png

Would you like me to open a new issue or is it related to this one?
