### ISSUE TITLE
[r32] Load Image from URL still broken for tiled BG when loading r31 project

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#405]
## Problem description
/UPDATE: removed all other actions, events etc. - image is still always the default image and not loaded on start of layout.

I tried exporting it to nw.js and preview and changed the load from url to a specific image and used choose(x,y,z) but it always displays the default image and does not load one of the images. It works fine if I create a new project, why not in the r31 project? I tried on start of layout and on touch to load the image.

## Attach a .c3p

[TiledBG_BugMinimal.zip](https://github.com/Scirra/Construct-3-bugs/files/1042289/TiledBG_BugMinimal.zip)

## Steps to reproduce

add tiled bg (sprite not tested)
add project files
load image from url using project file ("filename.png")

just run game to test if background in menu and in "new game" changes.

## Observed result

*What do you see happen?*

## Expected result

no image loaded

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r32

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 278 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by TheBl4ckSh33p** [comment]
forgot to delete a few objects in example above. below is only tiled background object.

[TiledBG_Bug_oneobject.zip](https://github.com/Scirra/Construct-3-bugs/files/1042295/TiledBG_Bug_oneobject.zip)

**Comment by AshleyScirra** [comment]
Ah, I think there's a case-sensitivity issue here: all filenames are lowercased on export but the filenames referenced use uppercase characters. You should be able to work around it simply by lowercasing the filenames in the action.

By the way, I can't see any good reason to do this - why not just put the images in the objects themselves? This allows them to be spritesheeted, work with layout-by-layout memory management, etc. all of which is essentially circumvented by loading them from a URL.

**Comment by TheBl4ckSh33p** [comment]
Thanks. Tiled bg has only 1 sprite so I would need 4 objects and create a random object? I thought I t's easier to load a random image instead of adding new objects, a family to randomly create one and new events for the family, right?

**Comment by TheBl4ckSh33p** [comment]
And it allows modding by replacing the images on pc builds.  But that's not needed for this one. 🙂

**Comment by TheBl4ckSh33p** [comment]
I just updated to r33 and changed all to lowercase but it's still not loading a new image. :(

**Comment by AshleyScirra** [comment]
I'll take another look...

**Comment by AshleyScirra** [comment]
Actually the project is corrupt, the image files are all 0 bytes. That's the only reason it's not working, it's not loading any image at all.

**Comment by TheBl4ckSh33p** [comment]
I did not check the filesize only had them in c3 in files list. I try to reimport them. Don't know why they are 0kb suddenly. Thanks for the update.

**Comment by TheBl4ckSh33p** [comment]
It works after reimporting the files! 😃
