### ISSUE TITLE
Open to popup window breaks dragging of events.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4050]
## Problem description

**Continuation**: https://github.com/Scirra/Construct-3-bugs/issues/4038
`Open to popup window` a layout causes dragging of events to work incorrectly.
```
I made a quick test on other laptops using the browser to confirm. Having it reproduce easily makes it a non-isolated case.
So you should be able to reproduce the issue by strictly following the steps.
```

## Attach a .c3p

[Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4954945/Bug.zip)

## Steps to reproduce

(**Warning**: For best effect, follow the steps in its order.)
(**Important:** Must have at least two monitors.)

1. Open `Layout 1`.
2. Open `Event sheet 1`.
3. Right click on the `Layout 1` tab.
4. Click `Undock` then `Open to popup window`.
5. Drag the popup window of `Layout 1` to the `2nd display`.
6. Move the mouse back to the `1st display` (Main C3 editor).
7. The `Event Sheet 1` should still be the active event sheet tab.
8. Drag `1st` event condition to the `24th` event.

## Observed result

The dragged event will just keep moving up. Ignoring your mouse's drag direction.
I suspect the `popped up window layout` is interfering with the actual mouse position coordinates.

## Expected result

The dragged event should move according to the mouse's position.

## More details

As soon as the popped up window layout is normalized into the main Construct 3 editor, the issue disappears.

This issue affects multi-monitor environments.
**First affected release:** It's been like this since the feature was available.

## System details
**Construct 3 r208** - NWJS Browser &
**Construct 3 r208** - Web version.

**Comment by Chadori** [comment]
**Here's the observed effect in video:**
This happens after following the previously mentioned steps.
![GIF](https://user-images.githubusercontent.com/31282960/88084454-0b76a500-cbb7-11ea-8f2a-3e925058a3da.gif)

**Comment by AshleyScirra** [comment]
Thanks, I can reproduce with these details. It should be fixed for the next beta.
