### ISSUE TITLE
C3 crashes when moving all collision polys at once

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#4051]
## Problem description

C3 consistently crashes when selecting all collision polys and moving incrementally with arrow keys.

## Steps to reproduce

1. Create numerous collision polys
2. Right Click > Select All
3. Move incrementally with arrow keys.
3b. Deselect collision nodes and apply poly to all frames (seems to make it more likely to crash)
3c. You might need the grid enabled / snap to edges for the crash to occur.

## Observed result

![image](https://user-images.githubusercontent.com/36490901/88098266-1bfb3100-cb5f-11ea-9a1b-6b6d3ec9f36c.png)

## Expected result

Not that ^^^

## More details

**Affected browsers/platforms:** 
Chrome / Desktop

**First affected release:** 
r208 but this has been on and off for a while now
## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r208/main.js, line 216, col 392
Message: Uncaught TypeError: expected finite number
Stack: TypeError: expected finite number at Function.o (https://editor.construct.net/r208/main.js:216:398) at f.n5b (https://editor.construct.net/r208/projectResources.js:149:362) at f.Qx (https://editor.construct.net/r208/projectResources.js:150:41) at Object.z0b (https://editor.construct.net/r208/projectResources.js:1613:39) at Object.mF (https://editor.construct.net/r208/projectResources.js:1629:242) at HTMLDocument.pba (https://editor.construct.net/r208/projectResources.js:1606:163)
Construct 3 version: r208
URL: https://editor.construct.net/r208/
Date: Tue Jul 21 2020 14:35:13 GMT-0500 (Central Daylight Time)
Uptime: 247.2 s

Platform information
Browser: NW.js
Browser version: 0.47.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.47.0 (like Chrome/84.0.4147.89)
C3 release: r208 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
