### ISSUE TITLE
Storyboard splash not working

### ISSUE THREAD

**Issue by karimlahbach** [Scirra/Construct-3-bugs#4052]
## Attach a .c3p
[TESTV2.zip](https://github.com/Scirra/Construct-3-bugs/files/4956597/TESTV2.zip)

## Steps to reproduce

1. Just open any simple project and add 2048 X 2048 in icon folder
2. Set image parameter to storyboard Splash
3. Export debug apk

## Observed result
construct 3 loader still show up
and storyboard Splash not showing up

## Expected result
Storyboard splash show up
and construct 3 loader not to show up

## More details

**Affected browsers/platforms:*google chrome* 

**First affected release:* Stable and last beta* 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I've adjusted the configuration for Android so it should be showing up there now in the next release.

**Comment by karimlahbach** [comment]
Thank you so much Ashley you are the best man

**Comment by karimlahbach** [comment]
Ashley the Splash screen still not showing up
i try to both android studio end Construct build service
