### ISSUE TITLE
Can't launch user scripting in chrome

### ISSUE THREAD

**Issue by thanhcuong90** [Scirra/Construct-3-bugs#4054]
## Problem description
The user script can you on old version of construct 3: r190 both Google Chrome and Firefox.
But it can't be launch in GG Chrome in new version: r204+

## Steps to reproduce

1. Start file in GG Chrome
2. Press F12 to view console debug
3. Check Console Tab

## Observed result
Show message error:
action.js:31 Unhandled exception running script Event sheet 1, event 1, action 1: Invalid board character encountered at index replaceAll: function replaceAll(find,replace){return this.replace(new RegExp(C3.EscapeRegex(find),"g"),()=>replace)}

## Expected result
Can run the code genboard sudoku

## More details
Devices: MAC OS - Chrome.
WINDOWS 10 - Chrome.

**Affected browsers/platforms:** Chrome on iPhone, Chrome on Android 

**First affected release:** r204+
## System details

<details><summary>View details</summary>

[bugGGChrome.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4960108/bugGGChrome.c3p.zip)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to investigate reports like this. Please see the bug report guidelines, they're there to make sure we can help.

**Comment by thanhcuong90** [comment]
Sorry about my bad English, it's not my mother language. So i try to typing it again ! 
So @AshleyScirra can you check this issue again ?!

**Comment by AshleyScirra** [comment]
It looks like a problem with the `replaceAll()` method which I had already fixed separately. It doesn't show that error in the development copy of Construct, so it should be fixed in the next release. Note however it still shows JavaScript errors in the console, because your JavaScript code doesn't work.
