### ISSUE TITLE
Description doesn't show for functions that return something.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4055]
## Problem description

When typing a function that returns some value, its description will not show.

## Attach a .c3p

Any file should present it.

## Steps to reproduce

1. Make a function return something.
2. Call it anywhere it is callable, like making a string for example.
3. See that its description is not shown.

## Observed result

Not seeing my description.

## Expected result

Seeing it.

## More details

**Affected browsers/platforms:**  Latest Chrome.

**First affected release:**  Tested in 208.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's shown in the expression dictionary, and it seems to be working fine. Please follow the bug report guidelines if you want the issue investigated further.

**Comment by dupuqub** [comment]
![bug](https://user-images.githubusercontent.com/34659544/88327954-1ab43a80-ccfe-11ea-9232-289f61c0bc3f.PNG)
This is where it happens. I realize now how unclear I was.

**Comment by dupuqub** [comment]
Hi there @AshleyScirra, have you seen my new comment? It illustrates the bug.
