### ISSUE TITLE
Hitting "Enter" on a function doesn't open its edit window.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4056]
## Problem description

Hitting "Enter" on a function doesn't open its edit window like literally everything else in Construct.
May be a bug, maybe not, but it's definitely something that should not be this way.

## Attach a .c3p

Any file should present it.

## Steps to reproduce

1. Try hitting "Enter" on anything in the event sheet editor.
2. You'll enter its edit window.
3. This doesn't happen for functions.

## Observed result

Not working for functions, but working for everything else.

## Expected result

Working for everything.

## More details

**Affected browsers/platforms:** Latest Chrome.

**First affected release:** Teste on 208

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
