### ISSUE TITLE
Mobile UI - Image points cannot manage

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#4057]
## Problem description

In mobile UI cannot add or delete image points just set origin.

## Attach a .c3p

https://drive.google.com/file/d/1h5JYuPvN00KIf9LOnn1Z7qY0QJAYzNvS/view?usp=sharing

## Steps to reproduce

1. Edit Sprite
2. Edit image points
3. Try press long

## Observed result

Just origin set.

## Expected result

Can add or delete image points.

## More details
It might be duplicated but now I cannot find the original post.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 84.0.4147.89
Browser engine: Chromium
Browser architecture: 32-bit
Context: browser
Operating system: Android
Operating system version: 9
Operating system architecture: 32-bit
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Mobile Safari/537.36
C3 release: r204.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 5.8 gb
Storage usage (approx): 42 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Imagination Technologies
Renderer: PowerVR Rogue GE8320
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_color_buffer_float
EXT_float_blend
EXT_texture_filter_anisotropic
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_pvrtc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
There seem to be two problems with the mobile view of the animations editor:

1) Swiping in bars from the left unintentionally changes tool if the touch goes over a tool on the toolbar. This should not happen and makes it difficult to reach the Image Points bar, because it's easy to accidentally switch to another tool while swiping in the bar, which hides the Image Points bar

2) If you are careful the Image Points bar can be accessed, and includes the ability to add new image points by long press. However the image point crosshair never seems to appear in the image editor window.

**Comment by henrikszucs** [comment]
I notice that Animation editor cannot handle the mouse with "simulate touch". It is not a problem but strange because the project bar and other bar can handle.

**Comment by henrikszucs** [comment]
The base mechanic when add objects, see layout or event sheet it is work pefectly. It looks like the sprite editor has different mechanic.

**Comment by AshleyScirra** [comment]
> I notice that Animation editor cannot handle the mouse with "simulate touch".

What do you mean by "simulate touch"? That doesn't seem to make sense, either you use real mouse input or real touch input, nothing is simulated.

**Comment by henrikszucs** [comment]
I mean "Simulate touch" is that the mobile UI can control with mouse. I know it is not the priority because the mobile UI developed for touchscreen but interesting that Sprite cannot handle mouse.

**Comment by AshleyScirra** [comment]
Are you attaching a physical mouse to a mobile device?

That is real mouse input, it's not simulated.

**Comment by henrikszucs** [comment]
I tried Mouse on desktop chrome and in mobile too. (real physical mouse)

**Comment by henrikszucs** [comment]
Here is a video: https://drive.google.com/file/d/1-3rZVVa9BNqdOtrJrAcS7P7WER-yrcp7/view?usp=sharing

**Comment by henrikszucs** [comment]
At the end of the video I cannot close the sprite editor window or click to button.

**Comment by iftikharlove555** [comment]
While the any bars are open and editing the image point and you click on the bar  the image point set it's position to where you touched on the bar this should never happened when the side bars are open and setting the image point up Down left right positions or setting the animation

**Comment by DiegoScirra** [comment]
There are a lot of things going on in this issue. The next beta includes a few changes that should improve the usability of the Animations editor in mobile devices.

**Comment by AshleyScirra** [comment]
@henrikszucs - r215 is now out, can you verify everything is working as expected with that release?

**Comment by iftikharlove555** [comment]
> @henrikszucs - r215 is now out, can you verify everything is working as expected with that release?

Thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you thank ❤️❤️❤️❤️❤️❤️❤️❤️❤️

**Comment by iftikharlove555** [comment]
Everything is fine now

**Comment by henrikszucs** [comment]
Mobile UI - Image points cannot manage #4057:
Yes the touch in sprite editor work perfectly.
In sprite editor I can access any feature.

But I found other possible bug but I do not that:
Does the mobile UI support mouse input?
For example I connect a mouse to my phone and it is a phisical mouse but mobile UI recognize as a single point touch.

The others higly possible busgs are:
"Bookmarks", "Find result", and "Find all references" windows display as a table but in mobile UI when try to swipe a result to read or rearrange the UI think I want to close or swap window.
I will test a bit more. If I am sure about the bug I will open an another issue.

**Comment by iftikharlove555** [comment]
That is not the problem of construct 3 but some mobile don't support mouse as pc can do

**Comment by DiegoScirra** [comment]
I will be closing this issue then. If you have other problems with the mobile UI, please file new issues.
