### ISSUE TITLE
Values for instance variables round to the nearest thousandth in the properties bar

### ISSUE THREAD

**Issue by Milesloh** [Scirra/Construct-3-bugs#4058]
## Problem description

If you try to enter a value less than 0.001 in an instance variable in the properties bar it appears to round to the nearest thousandth. 0.0009 rounds to 0.001 while 0.0002 rounds to 0. The values don't truly round i.e. if you debug the game you can see their true value, but seeing the value = 0 in the editor is confusing. If you click on the value again in the properties bar it does not restore the value with all the digits so it becomes truly zero. 

I'm guessing this is intentional to keep the numbers clean, but sometimes tiny decimals are useful. For instance, a time of a few seconds in units of days. 

## Attach a .c3p

One is attached but any project with an object with an instance variable will reproduce. 

## Steps to reproduce

1. Open any project
2. Give any object an instance variable
3. try to change the instance variable to 0.0001
4. Preview the project in debug mode: the instance value is truly 0.0001
5. click on the instance variable value again in the properties bar.
6. Preview the project again: the instance value is now 0.0000

## Observed result

the instance variable changes to 0 in the properties 

## Expected result

keep the digits that I added

## More details

**Affected browsers/platforms:** 

Tested on Windows Edge Chromium and Firefox

**First affected release:** 

Don't know. Tested on 204.2 stable
## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 85.0.564.13
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.26 Safari/537.36 Edg/85.0.564.13
C3 release: r204.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 142 gb
Storage usage (approx): 410 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
[Rounding Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4966781/Rounding.Bug.zip)

</details>

**Comment by AshleyScirra** [comment]
Construct has rounded these values to 3 decimal places ever since its launch in 2017. AFAIK this is the first time anyone's pointed this out as a problem.

The reason it rounds is to avoid any floating point imprecision showing up in the properties bar, e.g. displaying a value as 0.3000000000000000000000001 instead of 0.3, which is quite a common consequence of imprecise floating point calculations. I guess I could increase the rounding to 6 decimal places. Do you think that would be acceptable?

**Comment by Milesloh** [comment]
6 decimal places would work for my use case. Really 3 decimal places works OK now that I know what's going on. A tooltip warning me it was rounding the number would be just as good.

**Comment by AshleyScirra** [comment]
OK, the next release does 6 d.p. instead.
