### ISSUE TITLE
Crash editing image in project file

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#406]
## Problem description

The image editor crashes editing an image added as a project file.

## Attach a .c3p

From a different report: https://github.com/Scirra/Construct-3-bugs/files/1042295/TiledBG_Bug_oneobject.zip

## Steps to reproduce

1. Open the project
2. In the project bar, double-click one of the .png project files, e.g. bgCastle.png

## Observed result

Crashes: "Error: The source image cannot be decoded."

## Expected result

Should edit the image.

**Comment by DiegoScirra** [comment]
As of r35, the image editor will detect corrupted image files and replace them with empty place holder images.

The real problem is figuring out why those image files were corrupted in the first place :P
