### ISSUE TITLE
Whitelist 'chadori-mobile-masteriap'.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4060]
Hi, kindly replace the `cordova-plugin-inapppurchase-new` with the `chadori-mobile-masteriap@1.0.0`. 
Thank you.

**Comment by AshleyScirra** [comment]
`chadori-mobile-masteriap@1.0.0` now live on the allowlist.

**Comment by Chadori** [comment]
Thanks!
