### ISSUE TITLE
Requesting fullscreen doesn't work immediately

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#4062]
## Problem description

Hi! I recently realized that my game was not going fullscreen immediately after opening it, even with the correct code to do so. After a little bit of investigation I found many instances of the same error on my console, and thankfully I also found a very reliable way to reproduce the error.

Apparently the issue happens right when you start the game (work on both editor and nwjs export), it will try to request the fullscreen, but something will "block it" until you make some sort of interaction, like clicking on the game window or hitting a key on your keyboard. If you don't interact with the window it wont become fullscreen and will fill the console with errors and warnings.

Oh, if you press "Esc" while in fullscreen it will also cancel the fullscreen and start to send errors again, but I'm not sure if this only happens in the editor.

I recorded a very short video to display how everything happens: https://youtu.be/m4Po7b9n9ns

## Attach a .c3p

[Fullscreen Error.zip](https://github.com/Scirra/Construct-3-bugs/files/4973426/Fullscreen.Error.zip)

## Steps to reproduce

1. Preview the project.
2. Interact with the window.
3. Press F12 to check the console and see the errors.

## Observed result

Fullscreen doesn't work and keep making the console send errors.

## Expected result

Fullscreen to work as expected and no console errors.

## More details

**Affected browsers/platforms:** Chrome/Windows 10

**First affected release:** r208 (current beta release)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
For security reasons browsers only respond to fullscreen requests in user input events. This is [noted in the manual](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/browser):

> Note the browser may ignore this request unless the action is in a user-initiated event, such as a mouse click, key press, touch event or button press.

A normal 'compare variable' or 'is boolean set' event does not run in any user input trigger, so is not allowed to enter fullscreen.

**Comment by BonzerKitten** [comment]
@AshleyScirra Oh, I see. Isn't there anyway to go around this with NW.js?

**Comment by AshleyScirra** [comment]
NW.js can enter fullscreen at any time. It should already work.

**Comment by BonzerKitten** [comment]
@AshleyScirra It's my bad then, I actually tested it with both Chrome and NW.js, but either returned a bunch of console errors. I kind of managed to avoid the errors by testing if the player has sent any input after opening the game, but I'm not sure if that's an ideal solution, since it doesn't actually fix the problem. If you would like to investigate this issue with NW.js the same minimal repro file can be used.
