### ISSUE TITLE
r208 fails to export with advanced minification

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#4063]
## Problem description
r208 fails to export with advanced minification with scripts

## Attach a .c3p
https://drive.google.com/file/d/1635HzXu-VT4juTKOTq5pGxC7ED-EAjI4/view?usp=sharing

## Steps to reproduce

Export the project with advanced minification

## Observed result

Failed to export project
![image](https://user-images.githubusercontent.com/32940085/88444465-31848b00-cdeb-11ea-83a7-e6f28b45a942.png)

## Expected result
successful export

## More details

using an external script, the game uses it successfully when previewed.

exports with advanced minification and runs successfully when exported before the new minification

**Affected browsers/platforms:** 

**First affected release:** 
worked with the old minification
## System details

![image](https://user-images.githubusercontent.com/32940085/88444710-6218f480-cdec-11ea-8873-c1ffd44f76db.png)

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 84.0.4147.89
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
C3 release: r208 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 251 gb
Storage usage (approx): 785 mb (0.3%)
Persistent storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
A consequence of our change to Google Closure Compiler for minifying exports is that it handles global variables differently. You'll need to make the same changes outlined in [this post](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/third-party-addon-changes-153959), i.e. using `self.` or `globalThis.` to reference global variables.

The failing line appears to be `nakamajs.Session.restore(sessionString);`. Changing that to `self.nakamajs.Session.restore(sessionString)` allows for a successful export. I'll update the scripting documentation to cover this at the next stable release too.
