### ISSUE TITLE
Date Bug

### ISSUE THREAD

**Issue by NOAHGengo** [Scirra/Construct-3-bugs#4064]
## Problem description

Using Date.ChangeDay() doesn't work 

## Attach a .c3p

[DateBug.zip](https://github.com/Scirra/Construct-3-bugs/files/4974716/DateBug.zip)

## Steps to reproduce

1. Preview Project

## Observed result

Nothing happens. There's also an error in the console:

Uncaught (in promise) TypeError: (intermediate value).setDay is not a function
    at expressions.js:3
    at DateInstance.ChangeDay (expressions.js:9)
    at ExpressionParameter._expressionFunc (expFuncs.js?id=hsuujbcx131:103)
    at ExpressionParameter.GetExpression (parameter.js:5)
    at EvalParams (action.js:1)
    at Action._RunObject_ParamsDontVary (action.js:17)
    at EventBlock._RunActions_Fast (eventBlock.js:25)
    at EventBlock._RunAndBlock (eventBlock.js:23)
    at EventBlock.Run (eventBlock.js:20)
    at EventSheet._ExecuteTrigger (eventSheet.js:18)

## Expected result

Text object gets the date

## More details

**Affected browsers/platforms:** Chrome 

**First affected release:** First noticed in r208 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 84.0.4147.89
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
C3 release: r208 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 221 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
