### ISSUE TITLE
Tilemap hotkeys no longer work until you place a tile first.

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#4069]
## Problem description

Tilemap hotkeys (such as "x" to mirror or "y" to flip) no longer work until you place a tile first.

## Attach a .c3p

Can use a default tilemap instance in new project.

## Steps to reproduce

1. Create a tilemap object
2. Select the tilemap object and then pick a tile with pencil tool
3. Hover the mouse over the tilemap object to get a preview of the tile you're about to place
4. Press any of the hot keys a few times (x, y, r, etc.)
5. Now place the tile and press some hotkeys again

## Observed result

The hotkeys don't work unless a tile has been placed.

## Expected result

The hotkeys should work without having to place a tile.

## More details

**Affected browsers/platforms:** 
Chrome / Desktop

**First affected release:** 
Around r207
## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.47.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.47.1 (like Chrome/84.0.4147.89)
C3 release: r208 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 796 gb
Storage usage (approx): 242 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This is fixed in the next beta.
