### ISSUE TITLE
Search dialog doesn't focus when open

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#407]
## Problem description

Search dialog doesn't focus in "Find" field when already open.

## Steps to reproduce

1. Open search dialog box in events:
Right click>Event sheet>Find... (or CTRL+F on Windows)
2. Do the same when the dialog box is already open

## Affected browsers

* Chrome

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r33.
