### ISSUE TITLE
When multi-touching exceeds the number of devices supported, the touch will end.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4070]
## Attach a .c3p

I used the simple example by dop2000 Attach at the time.  https://github.com/Scirra/Construct-3-bugs/issues/1639
  
There are only two events in it.
```
+ System: Every tick
-> DebugText: Set text to ""

+ Touch: Is in touch
----+ System: For "x" from 0 to Touch.TouchCount-1
-----> DebugText: Append "Touch " & LoopIndex & "  X: " & int(Touch.XAt(LoopIndex)) & "  Y:" & int(Touch.YAt(LoopIndex)) & newline
```

## Steps to reproduce

I used the iPhone11 for remote preview testing. supports up to 5 fingers.

1.Hold down the screen with 5 fingers. At the same time, the DebugText appears with 5 postion text.
2.When the sixth finger is pressed on the screen, the touch end.

## Observed result

touched reset

## Expected result

I think that the fingers beyond the devices  limit can be temporarily not recognized by the game, and the fingers pressed at present are still valid. Until a certain finger is released, new fingers will continue to be recorded. Instead of resetting the current touch.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I can reproduce on an old iPhone 7+, but it looks like a hardware limitation on the device. Once you exceed the maximum touch count, the device cancels all the existing pointers. I guess it isn't able to tell them apart so you have to start over. On an iPad Pro it supports 10 simultaneous touches, so it's hard to test more! And a Pixel 3 looks like it supports 6-7 maximum touches, but can keep the first touches and just ignore later touches if it doesn't support that many. In all cases Construct is just listening to the touch events the browser sends it, so I don't think there is anything that can be done about it.
