### ISSUE TITLE
Sounds not working

### ISSUE THREAD

**Issue by hassanrasheed7** [Scirra/Construct-3-bugs#4073]
## Problem description

I make the event. Audio -> Play -> "sound" not lopping 0db tag ""

## Attach a .c3p

[sound_issue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4982922/sound_issue.c3p.zip)

## Steps to reproduce

1. I make an event
2. Audio
3. Play "sound"

## Observed result

I play the game and the sound is not working.

## Expected result

I expected that the sound will work normally.

## More details

**Affected browsers/platforms:** 

Chrome 84.0.4147.89

**First affected release:** 
I first started construct r197 so im not sure that older versions have the same bug.

## System details

Construct 3 r204.2-r197 stable

<details><summary>View details</summary>

No sounds and music.

Browser: Chrome 84.0.4147.89 64-Bit
Computer: MacBook Pro (13-inch, Late 2011)
Processer: 2.4 GHz Intel Core i5
Memory: 8 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 3000 512 MB
Storage: 9.93 GB Available of 239.85 GB 

System: MacOS High Sierra version 10.13.6 64-Bit

</details>

**Comment by AshleyScirra** [comment]
The .webm audio files are not valid. They are actually signed PCM WAV files. It appears they have the wrong file extension. Since Construct will assume they actually contain valid WebM Opus audio data, they won't work correctly. Make sure you import valid audio files.

**Comment by hassanrasheed7** [comment]
You mean that I should use .WAV files? if it is i tried to do that too but
its not working too.

‫في الاثنين، 27 يوليو 2020 في 7:53 م تمت كتابة ما يلي بواسطة ‪Ashley
(Scirra)‬‏ <‪notifications@github.com‬‏>:‬

**Comment by hassanrasheed7** [comment]
Thanks for your help!

‫في الاثنين، 27 يوليو 2020 في 7:53 م تمت كتابة ما يلي بواسطة ‪Ashley
(Scirra)‬‏ <‪notifications@github.com‬‏>:‬
