### ISSUE TITLE
Android API level is low

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#4075]
Today I was trying to upload an APK file but I was greeted with a message
![Screenshot_20200728_085939_com android chrome](https://user-images.githubusercontent.com/46170077/88649345-68a5b580-d0e5-11ea-9935-06fa86e23d9d.jpg)
Only few days are left for August.And if it is not updated quickly then no one will be able to add an app to the play store

**Comment by layilpaht** [comment]
I may sound greedy but try to fix the issue by giving it a top priority

**Comment by AshleyScirra** [comment]
I already updated this for the next release. The API requirement increases every year so this is a routine update.

**Comment by layilpaht** [comment]
When will latest beta be launched ? Actually due to corona-virus their publishing time is now approx 2-3 days

**Comment by AshleyScirra** [comment]
We already released r209 earlier today. It's already out at the time of your comment.
