### ISSUE TITLE
Android instant app requires few more variables in androidmanifest.xml

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#4076]
Android instant app is a brilliant way to promote your app.Besides your app, a "try now" option comes through which user can get a taste of the app before even installation. And it is a boon for those who want to sell their app on play store. And I strongly believe that Construct 3 users deserve a chance to take advantage of it
So I also wanted to maximize my app reach to the public and hence submitted a "modified APK" of the original APK (Condition is that the size must be less than 10 MB so that user can quickly access instant app, so I stripped all music files and big sized photos)
But the ending was not great.I was greeted with a message
![Screenshot_20200728_093534_com android chrome](https://user-images.githubusercontent.com/46170077/88650803-afe07600-d0e6-11ea-9239-e116b3c7420c.jpg)
Hence I did a research on the internet and learned that before the app compilation,there should be a line added in androidmanifest.xml.I am adding two links which will clear all of your doubts regarding the whole topic 
https://developer.android.com/topic/google-play-instant/getting-started/instant-enabled-app-bundle
https://developer.android.com/guide/topics/manifest/manifest-element#targetSandboxVersion

I strongly believe that you will help me regarding it.If you want more details then surely ask me about it.Today I will reply you in about 5 minutes interval

**Comment by layilpaht** [comment]
I may sound greedy but I am currently in hurry. I am working on an app since last 2 years.I have invested a lot of sweat,determination and hard work in it. It is a collection of 222 games and apps inside a single app. And I want it to give a more professional look to it. And android instant app will be an important factor in it
I did research on the internet and other users gave me suggestions like:- use apktool to reverse engineer you app,edit the androidmanifest.xml yourself manually.Then compile it again.Since apktool only generates unsigned apk files hence using other application,I will have to sign it
But the main issue is that if I would have been a nerd like that then why would I have been using no-programming-game engine in the beginning itself?

**Comment by AshleyScirra** [comment]
This is a feature request, not a bug, so please post it to the suggestions platform instead: https://construct3.ideas.aha.io/

I suspect there will be several more changes required than you mentioned so I would expect it to be more work.

Note the existing web export is also a good way to provide a no-install-needed trial to help promote your app.

**Comment by layilpaht** [comment]
Just a small question:- will android app bundle solve my issue?
