### ISSUE TITLE
Greenworks console error after update

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#4079]
## Problem description

Hi! The Greenworks plugin was recently updated (#4049 ), which is cool since the previous version required a very old version of NW.js, however this update brought a console error to one of my games and it can't trigger achievements anymore.

Console error: https://i.imgur.com/4DLPdWe.png

The Steam overlay still works, but the rest of the API is inoperative. In order to update my project I followed these steps:

1. Updated my Greenworks plugins to latest version available in the addons store.
2. Imported the "sdkencryptedappticket.dll", "sdkencryptedappticket.lib", "steam_api.dll" and "steam_api.lib" files from the SDK 1.49 version to my "Files" folder in Construct 3, because that's a very easy way to make sure they will all be sent to the "Package.nw" file.  
3. Exported everything with the correct version of NW.js, 0.47.0 in this case.
4. After exporting the project I included my appid text file to the base folder as well.

I don't think I missed any step... I've been doing this whole process for quite a while now. Do you think it's a problem on my side? 🤔

## Attach a .c3p

This file have a .c3p file containing the latest version of the Greenworks plugin and the NW.js exported project.
https://we.tl/t-FS27lMhJv6

Screenshot of my export settings: https://i.imgur.com/kqfOiox.png

## Steps to reproduce

1. Execute the "Greenworks Bug.exe" file in the "win32" folder.
2. Check the console by pressing "F12" on your keyboard.

## Observed result

A console error that prevents the Greenworks from being initialized.

## Expected result

The Greenworks plugin to be able to perform its actions without any issues.

## More details

**Affected browsers/platforms:** Chrome (NW.js) / Windows 10

**First affected release:** r209 (latest beta release)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please attach a project as per the guidelines otherwise we cannot investigate the report.

**Comment by BonzerKitten** [comment]
@AshleyScirra Included a .c3p file and some basic instructions. 👍

**Comment by BonzerKitten** [comment]
@AshleyScirra I know you guys are a small company and deal with many other things (bug reports, new features, etc), but do you have any news on the Greenworks plugin? I already have a few players on my back asking me when achievements will be back online. Thanks for the hard work! 👍

**Comment by AshleyScirra** [comment]
The link you provided has expired, so I can't investigate this. Please use one of our recommended cloud file services to avoid this happening (Dropbox, OneDrive or Google Drive).

**Comment by BonzerKitten** [comment]
@AshleyScirra Uploaded it to my personal Drive account.
https://drive.google.com/file/d/1nNWWeXwnSwVvYNbDEL3c54X0oKAfM0pN/view?usp=sharing

**Comment by AshleyScirra** [comment]
The project appears to bundle the 32-bit Steamworks DLLs. If I do a 32-bit NW.js export and follow the rest of the steps, it works fine and there is no console error. If I do a 64-bit NW.js export and follow the rest of the steps, it does log a console error, because you have the wrong DLLs. If I then delete the 32-bit Steamworks DLLs and put in the 64-bit Steamworks DLLs (from SDK 1.49 as per the instructions), it works fine again. So it looks like you just used the wrong Steamworks DLLs.

**Comment by BonzerKitten** [comment]
@AshleyScirra You're absolutely right about this min-repro file, I definitely messed my export settings here. However, after trying to compile a new version of my game, I still got errors on my console regarding the Greenworks plugins, so I decided to investigate a little further and I actually found the reason why it's having issues! The problem is that I've some arrays (json files) in my project as well, I tried to add some empty arrays to the min-repro project and it indeed threw an error just like my game, so that's definitely a bug. I always had those arrays in my project and never had issues before, so maybe it's still related to the latest Greenworks plugin update? Well, here's the updated min-repro file. https://drive.google.com/file/d/1LPbN-lflXYRysQd_N57-c2SnhOsGfVLf/view?usp=sharing

**Comment by BonzerKitten** [comment]
@AshleyScirra I was very surprised with your answer to this issue, because I was somehow still getting errors on my console, so I decided to investigate a little further and after a few hours I actually found the source of the problem and was able to solve it. I'll explain everything.

After you sent your reply, I tried to export my game (Rabisco) again, using the correct DLLs and settings, but I was still getting the same error. So I thought to myself "well, maybe this project is just somehow corrupted?!", then I tried to create a blank project and use the same DLLs and settings, guess what? It worked! Now... Why it worked? The answer is simple: bundle assets.

Yes, bundle assets was causing the error and I guess it makes sense. Rabisco's project was created using the previous version of the Greenworks plugin while also having "bundle assets" on, so even after I updated the plugin using my addon manager, this specific project was still accessing the old version and probably resulting in some weird errors, since everything was being combined with the newer DLLs and NW.js version.

I'm not sure if it could be considered a bug, but I guess it would be a good idea to force the projects to access the most recent version if it's available and bundle it again, right? Well, that's on you to decided, but I'll probably never use "bundle assets" again lol.

By the way, this is kind of an edge case, so I'm sorry if I made you feel like you wasted your time. I'm saying that because I saw your latest tweet, which was perfectly timed with the "end" of this bug report. https://twitter.com/AshleyGullen/status/1295430888868773890

I didn't meant to waste your time, I'm sorry!

**Comment by AshleyScirra** [comment]
It's alright, it happens! I suspected it was somehow a version mismatch between all the dependencies, they all have to be exactly right. Do you mean you were using the "bundle addons" feature to embed the Greenworks plugin with the project file? If so, IIRC you can go to the "view used addons" dialog for the project, and update the Greenworks plugin bundled with the project to the latest version there.

**Comment by BonzerKitten** [comment]
@AshleyScirra Exactly! I actually meant to say "bundle addons", I'm sorry. I was not aware of that possibility in the "view used addons", but apparently it's listed in the manual (https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/installing-third-party-addons). Well, five years using Construct and I'm still finding some surprises here and there. Thanks for the tip, Ashley! Also, congratulations on releasing the first version of the scene graph feature, it's very exciting.
