### ISSUE TITLE
Object position problem on resizing

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#408]
## Problem description

Object position problem on resizing.

## Steps to reproduce

I don't know exactly how to reproduce it, but try to manipulate objects while working (fonts, sprites, tilemaps, whatever), this happens often but not every time. Instead of being placed at its real position or holding its real position (like in c2 or other environment), the object is recentred at the same time it is resized, which has for effect to completely modify its logical position and selection size.

* Chrome

**Comment by sebastien-c3** [comment]
It's so special and difficult for me to express clearly this in english! :)
Here a more speaking gif: http://spinof.com/support/c3/resize-object-bug.gif

**Comment by AshleyScirra** [comment]
Sorry, there's nothing we can do unless you provide your project (.c3p) and steps to reproduce the problem. Note that the behavior shown in the gif is correct in some circumstances, if you're holding a keyboard shortcut.

**Comment by sebastien-c3** [comment]
Ok Ashley, no key is down, I have this problem since the beginning and it's really random to one click to another. I'll try to reproduce it and furnish a c3p or a better gif.
