### ISSUE TITLE
My html game is not loading files inside the project folder

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#4080]
I have made a mobile game in html ( thaplisupergamearcade.netlify.app ). It has many text files as project files inside its respective folder (for making levels). But the issue is that the game is not downloading projects files in advance. Rather it downloads the "wanted text file" when it is needed
But I don't want that. It creates a good amount of lag (and my game fails). I want to load all of my project files when the loader layout is running(I have even added that and it downloads all of the game related file (but not project files)). And when I asked regarding it, you told me that it automatically downloads everything. And I guess I have encountered a bug where the html game is not downloading project files in advance
 And if it is not a bug then I strongly believe that html games should download project files in advance

**Comment by layilpaht** [comment]
Update:-
I noticed that after playing the game for the first time,the game runs without ANY issues later on(even internet is not required after first time the game loads).This implies that it was rather a bug:- for first time the game was "demanding" project files from the server in spite of the fact that the game was already having project files in it. Later on when the game was played second time it did not demanded the file from the server (the game was told not to do it as now the game was in offline mode) 
So as I guess, a new thing should be added to the game,saying "you already have project files.Just relax"

**Comment by AshleyScirra** [comment]
I'm afraid as we emphasise in the bug report guidelines, we cannot do anything about issue reports unless you follow the template.
