### ISSUE TITLE
Mobile Html game do not use project files from the main game during first run

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#4081]
## Problem description

I have made a mobile html game. It has lots of text files in project folder. And for accessing them I use Ajax plugin. So I made a html game and uploaded to netlify.

First time playing the game
I noticed that the game was not using text files from the game loaded,it always tried to download it from the server when needed. If the internet is slow you can feel the lag in the game( for example I have put "help text" in the txt file. So when help is to be shown , for 1 second nothing happens,then the help is shown---> means that first it will download that particular text file then help will be shown

Second time playing the game
No problems. Everything runs smoothly. The game behaves like it has all the file with it

## Attach a .c3p

No need. I have explained the bug clearly. Still link of my game thaplisupergamearcade.netlify.app

## Steps to reproduce

It is basically told above. This bug was not to be explained using the given template but you rejected my earlier bug report

## Observed result

When the game is played for the first time, the game acts in such a way that it assumes that it does not have project files with it,hence it tries to download it from the server hence causing unnecessary delay
But after playing for the first time, the issue does not occur. The game then "learns" that it already had projects file with it,hence no need to download it again from the server

## Expected result

The game should not ask for project file from the server.

## More details

It is definitely a bug. Why game is asking for project files from the server even if it already has files with it? And why game suddenly admits that it had files with it after first run?
And obviously I am using loader layout . And currently this is happening for text files in project folder. 

**Affected browsers/platforms:** 

I am facing this issus in r209 but earlier versions are also having the same issue

**Comment by layilpaht** [comment]
I am making a demo for customers so that they can try the app before purchasing it
It would be shameful for me if I will tell them to first load the demo, then close it then again open the demo for best experience

**Comment by AshleyScirra** [comment]
No project has been provided, nor any steps to follow in the provided URL to observe when it makes these requests, so I cannot investigate this report.

Anyway, the entire project is downloaded on the first run to save it for use offline. I think the offline cache only takes over on the 2nd load though, hence possible requests to network on the first run. However the caching is still within your control. If the server specifies [Cache-Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) headers that allow caching on the static resources, the browser can still go to the cache for subsequent requests on the first run. Currently the server sends `Cache-Control: public, max-age=0, must-revalidate` on the text files, which means the server is telling the browser *not* to cache file file, and that it *must* request from the server any time it needs it. So you've disabled caching on these resources.
