### ISSUE TITLE
C3 Editor Tips Cloud authentication Login

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4083]
## Problem description

When using the cloud service, the account login window will pop up. if login account, Construct will getting the files. 

like it
https://imgur.com/Red4qNk

But if the cloud service login window is open,  Construct should be Tips to "Sign in to your cloud account" rather than say "Getting files from...". 

Sometimes, the login window will be placed underneath other browser Windows. If don't notice the taskbar, it be assumed that Construct is getting files slowly instead of I forgetting to log in.

This happens to me all the time.

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
> Sometimes, the login window will be placed underneath other browser Windows.

It should always appear on top. Do you have a browser extension that changes that or something?

**Comment by XHXIAIEIN** [comment]
> > Sometimes, the login window will be placed underneath other browser Windows.
> 
> It should always appear on top. Do you have a browser extension that changes that or something?

No, I did not install this type of extension. I mean I click on other tabs in my browser (not Construct tabs) and that puts the new window on top of the login window.

I usually open a lot of tabs at the same time at work,Construct is just one of them. However,  If  login window pops up, then if I click the Construct editor again, the login window will also be set to the bottom.So in C3 I only see getting files.

**Comment by AshleyScirra** [comment]
Construct already shows a "Awaiting user authentication" message in the status bar when it's waiting for you to complete the login. I made it show that message inside the dialog as well to make it even clearer.
