### ISSUE TITLE
Two Finger Gestures do not function correctly in the Desktop Interface

### ISSUE THREAD

**Issue by HammerFox** [Scirra/Construct-3-bugs#4084]
## Problem description

Sometimes I choose to use Construct 3 without a mouse on my iPad, and the desktop interface is pretty much completely manageable with touch, aside from the fact that attempting to zoom or pan with two finger gestures results in moving multiple objects at once. However, when the space key is held, it does work, though it selects objects still but thankfully does not move them.

## Expected result
I expected multitouch to work as it does in the mobile mode. 

## More details

I assume that there are some under the hood differences that prevent the touch events from being handled the same way as in the mobile interface, but I’d like to ask if there could possibly be a toggle added in the settings to have the desktop interface’s layout editor handle touch events like the mobile interface. Or if this could just be implemented flat out that would be ideal.

**Affected browsers/platforms:** 

Safari on iOS 14 ( Though this also happens on 13.4)

**First affected release:**  I am unsure as this has been something I’ve noticed for a while now.

**Comment by AshleyScirra** [comment]
I've adjusted the Layout View to handle touch input on desktop (or in desktop mode) the same as it does on mobile for the next beta release.

**Comment by HammerFox** [comment]
You guys are awesome. Thank you!
