### ISSUE TITLE
Array Editor: Unwanted linebreaks occuring 

### ISSUE THREAD

**Issue by sseekins** [Scirra/Construct-3-bugs#4085]
## Problem description

In the Array Editor, when typing text into a cell, it will sometimes add a line break after the first letter. 
Typing in 
"Yellow" 
for example will sometimes result in
"Y
ellow"

## Attach a .c3p
[This is a copy of the file I was working on when I discovered the bug.](https://drive.google.com/file/d/1NVJnoAS6N9b7Yv1sYAosgbo4QS3qxhAT/view?usp=sharing)  "NewArray.json" contains texted I just entered quickly, most entries being affected by the error.

## Steps to reproduce

1. If no arrays exist in the project, create one in the Files folder in the Project window (Files -> New ->Array).
2. Open an array file in the Array editor.
3. Click a cell *once* and begin to enter text at least two characters in length.

## Observed result

When entering the text, the first character typed is correctly entered. The next character to be typed will cause a line break to be inserted before it. Subsequent characters are able to be input without any additional errors.

## Expected result

The text entered should appear as typed without any errant line breaks.

## More details
This bug does NOT occur if you *double click* the cell.

**Affected browsers/platforms:** 
I've only tested Firefox

**First affected release:** 
Release r204.2 stable

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 79.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
C3 release: r204.2 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 255 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks specific to Firefox only, it doesn't reproduce in Chrome. I think it's some weird Firefox quirk. I found a workaround for the next release so it should be fixed there.
