### ISSUE TITLE
Audio changes volume when looping on UWP

### ISSUE THREAD

**Issue by NeonArgon** [Scirra/Construct-3-bugs#4088]
## Problem description

When playing music with a volume lower than default (0dB) in a Windows Store App (UWP), the music resets the volume when looping. Also, the volume can't be controlled afterwards (but the music can still be stopped). 

## Attach a .c3p

https://www.dropbox.com/s/riomu0jm4kbol9k/AudioTest.c3p

## Steps to reproduce

1. Create project that plays music looping with volume different to 0DB
2. Export as Windows Store (UWP), (SDK Version 10.0.17763.0)
3. Open with Visual Studio 2017
4. Run Project

## Observed result

The audio will get louder when looping for the first time. The Volume of the audio can not be controlled (for example by pressing Q when using attached project)

## Expected result

Audio plays consistently at the same volume and volume stays controlable.

## More details

**Affected browsers/platforms:** Visual Studio 2017 (SDK Version 10.0.17763.0)
**First affected release:** r204.2 (earlier versions might also be affected)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 84.0.4147.105
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.2000000476837158
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
C3 release: r204.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 1 gb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can reproduce, but I'm afraid it looks like a bug in the Edge browser engine. Construct does everything right as far as I can tell - we just create an `<audio>` element, set its volume and looping tag, and start playing it. The browser engine seems to get this wrong.

You can try reporting this to Microsoft, but they're currently in the process of phasing out the old EdgeHTML engine and replacing it with a new Chromium-based engine. So you might have to just work around it.
