### ISSUE TITLE
Can't press enter

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#409]
## Problem description
When entreting a system action which creates an object, I can't click "Enter" to choose the object. I must click on the <click to choose> button.
This happens on all action dialogs which requires to choose an object: create object, scroll to object, spawn new object, restore object time scale, set position to another object, move to object.

## Steps to reproduce
1. create a simple sprite
2. create a new action : System / create object
3. press enter, an error dialog appears, asking you to click the button.

## Observed result
Error dialog pops-up : 
"Choose an object for 'Object to create'
Click the button to pick an object"

## Expected result
Immediately show up the object list, as in C2.

## Affected browsers
* Chrome: yes

**Comment by AshleyScirra** [comment]
'Enter' is the shortcut to close the dialog. To push a focused button, press Spacebar instead.

**Comment by RabloGames** [comment]
Thanks, didn't know about that.
