### ISSUE TITLE
[Addon SDK] Plugin Property -> Cordova Plugin Dependency Variable cannot export if the plugin property is "check" (boolean).

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4090]
## Problem description

**[Addon SDK]** `Plugin Property` -> `Cordova Plugin Dependency Variable` cannot export if the plugin property is `check` (boolean).

## Attach a project kit
The `.zip` includes the `.c3addon`, addon folder, error image, script image, export notification image and `.c3p`. 

[Variable Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5030902/Variable.Bug.zip)

## Steps to reproduce

1. Open `Project.c3p`. 
2. Then, export to `Android`.
3. Observe `Failed to export project`.

## Observed result
From the **Construct 3 Editor**.
![Export notification](https://user-images.githubusercontent.com/31282960/89458271-5852a200-d799-11ea-84a4-b0935876b606.png)

From the **Construct 3: Web Developer Console**
![Error](https://user-images.githubusercontent.com/31282960/89458306-686a8180-d799-11ea-9d27-bc0cb0031d28.png)

## Expected result

For it to accept **check** (boolean) plugin properties for the `Cordova Plugin Dependency Variable` input parameter.

## More details

Here is the script that causes the issue.
![Script](https://user-images.githubusercontent.com/31282960/89458457-a2d41e80-d799-11ea-8205-5695369ad174.png)

```JS
            const booleanProperty = new SDK.PluginProperty("check", "booleanProperty", true)

            this._info.SetProperties([
                booleanProperty
            ]);

            this._info.AddCordovaPluginReference(
            {
                id: "cordova-plugin-firebase-analytics",
                plugin: this,
                variables: [
                    ["FIREBASE_ANALYTICS_COLLECTION_ENABLED", booleanProperty]
                ]
            });
```

## Other details

A lot of other Cordova plugins that I'm using now requires boolean variables, due to some major changes. I hope you can fix this.
Thank you.

**Comment by Chadori** [comment]
I think converting a `(toggle)` (`check` plugin property) to `"true"` or `"false"` would resolve the issue.
Let me know what you think.

Thank you.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta. The boolean will set a value of `"true"` or `"false"` in the XML, e.g. `<variable name="FIREBASE_ANALYTICS_COLLECTION_ENABLED" value="true"/>`.
