### ISSUE TITLE
PlatformInfo.WindowInnerWidth / Height is not responsing after screen rotation on iOS

### ISSUE THREAD

**Issue by vascco47** [Scirra/Construct-3-bugs#4091]
## Problem description

PlatformInfo.WindowInnerWidth / Height is not responsing after screen rotation on iOS (tested with iPhone 11 Pro and iPhone 6s)

## Attach a .c3p

![c3p screenshot](https://user-images.githubusercontent.com/69270843/89460217-37bf2380-d76a-11ea-90bb-2ebe213ba519.jpg)

Github doesn't allow me to attach up .c3p

## Steps to reproduce

1. Add PlatformInfo Object
2. System -> Every tick
3. Set canvas size to -> Width: PlatformInfo.WindowInnerWidth; Height: PlatformInfo.WindowInnerHeight

## Observed result

On startup canvas is adapted to screen and problem occurs after screen rotation, when the canvas covers only about half of the screen and it only happens on iPhone (tested with iPhone 11 Pro and iPhone 6s), with iOS 13.6, while on Android and Windows it works perfectly.

![IMG_5822](https://user-images.githubusercontent.com/69270843/89499659-aa5aee00-d7c0-11ea-86f7-7a7da576a3c9.PNG)

![IMG_5821](https://user-images.githubusercontent.com/69270843/89499667-af1fa200-d7c0-11ea-917a-08a9f56f6f5d.PNG)

## Expected result

The canvas should fill all the empty space on the phone screen.

## More details
Issue occurs on iOS (tested on Safari and Chrome), but works on Android and Windows.

**Affected browsers/platforms:** 

Chrome/Safari, iOS

r209, r210

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 84.0.4147.105
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
C3 release: r210 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 90 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It works fine for me. This project demonstrates the PlatformInfo window inner size updating correctly after rotation with iOS 13.6: [window-inner-size.zip](https://github.com/Scirra/Construct-3-bugs/files/5042437/window-inner-size.zip)

Using 'Set canvas size' with that size doesn't really make any sense - I don't know why you'd want to do that, the project fullscreen mode normally handles that for you, and trying to set the canvas size like that will probably just conflict with the built-in scaling to window size. I tried adding the action anyway, and it didn't do what your pictures show (but it didn't seem to produce a useful result either, since as I noted I don't see why you'd want to do that)

Since no project attached I can't investigate further, closing. Please see the bug report guidelines (which include instructions on how to attach a project).
