### ISSUE TITLE
r210 Playable Ads Compilation not working

### ISSUE THREAD

**Issue by EnriqueAlbirCodi** [Scirra/Construct-3-bugs#4092]
When compiling with the newest stable version r210 a playable ad with all the minification options activated, the resulting .html does not load (the same project compiled with the previous stable verison r204.2 works perfectly).

There seems to be a problem related with the audio.

![errorMessage_r210](https://user-images.githubusercontent.com/58432696/89525777-033d7d00-d7e7-11ea-87ed-86dbbe1d0470.png)

**Comment by AshleyScirra** [comment]
Can you provide all the requested details in this report please, including the project you emailed me? It will take longer to deal with otherwise, and it can be confusing if information is spread around different places, especially since we deal with thousands of reports.

**Comment by AshleyScirra** [comment]
Following up by email, so closing this issue.
