### ISSUE TITLE
I have the same error of not loading the application. 

### ISSUE THREAD

**Issue by erissonamorim** [Scirra/Construct-3-bugs#4093]
I have the same error of not loading the application. It simply freezes on the loading screen and displays the application icon (versions 207, 209 and 210).
Support asks to register a bug on the website: https://github.com/Scirra/Construct-3-bugs, but there, there is no clear way to post the error. I’m like my app for more than three days on Google Play without being able to resolve it. Already ordering more than a thousand installations.
I await action...

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to do anything about reports like this - please see the bug report guidelines, we need that information to be able to help you.
