### ISSUE TITLE
Sound doesn't work after export both on FB and Android

### ISSUE THREAD

**Issue by iamcmnut** [Scirra/Construct-3-bugs#4094]
## Problem description

I export my game to Web and Android and it doesn't work and it print a log in to a console like this.

![image](https://user-images.githubusercontent.com/2133659/89607641-380c0b80-d89d-11ea-8887-6a4a85bcb649.png)

## Attach a .c3p
[ninjafrog-vs-chicken.zip](https://github.com/Scirra/Construct-3-bugs/files/5039247/ninjafrog-vs-chicken.zip)

## Steps to reproduce

1. Menu -> Project -> Export
2. Facebook InstantGames
3. [Y]Deduplicate images, [Y]Recompress images, minify mode: Advanced

## Observed result

Any sound doesn't work on both FB Instant game and Android

## Expected result

Sound should work at the beginning till the end of the game.

## More details

**Affected browsers/platforms:** Chrome, Android 5+

**First affected release:** worked in r204 but broke in r210

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by unai6666** [comment]
Having the same problem

**Comment by AshleyScirra** [comment]
It's a bug in the Closure Compiler minifier that mangles the audio code incorrectly. You can work around it by using 'Simple' or 'None' for the minify mode on export. I think we can get a stable patch release out soon too to fix this.
