### ISSUE TITLE
Minified export doesnt  work

### ISSUE THREAD

**Issue by bedfl2016** [Scirra/Construct-3-bugs#4095]
## Problem description

There is a bug when exporting to IOS the modification fails:
![image](https://user-images.githubusercontent.com/45516393/89634181-dea3dc80-d89c-11ea-978d-ce852221c6fe.png)

I have tried on many projects and it fails on Android and IOS

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines, otherwise it's impossible to do anything about the report.

**Comment by bedfl2016** [comment]
@AshleyScirra I cant post a .c3p as its commercial how can I share my project file to you without the public having access to it?

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. They cover this.
