### ISSUE TITLE
C3 Desktop Editor

### ISSUE THREAD

**Issue by C3GameDev** [Scirra/Construct-3-bugs#4096]
## Problem description

Since the last Stable-Update the Desktop-Editor of C3 has some weird errors:
A "grey bar" appears when loading a project, exporting a project and at some other loading points:

The editor still work, just at loading times / exporting this weird grey bar appears.
Also closing the editor takes much more time than before (around 2 seconds, normally closed instantly).
And last thing I have to mention:
When exporting with advanced minify activated, there is always a export error at the end without any error-logs.

## Steps to reproduce

1. Download the newest Stable Dektop C3 Editor
2. Open a Project: File -> ...
3. When the project loads, a "grey bar" appears in the top mid section of the editor.
OR
4. Export a project: instead of showing some loading information (for example "recompressing images...") it shows an empty "grey bar" as long as the project needs to export. After exporting the normal export window shows up where you can download the project.

## Observed result

Grey bar appears
Screenshot when loading File (when exporting, same grey bar appears, but it can have a bigger height):
[screen.png](https://kkgames.de/screen.png)

## Expected result

Normally it shows some loading / exporting information

## More details

**Affected browsers/platforms:** 

**First affected release:** Construct 3 r210 

## System details

Windows 7 64 bit
Downloaded the newest C3 Desktop Version with newest NW.js SDK version

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I think this is some kind of rendering bug in NW.js. It looks like it's fixed in the latest nightly release though, so it should be working again when the next NW.js update comes out.
