### ISSUE TITLE
r210 "On mobile back button pressed" does not work correctly.

### ISSUE THREAD

**Issue by Fakerock** [Scirra/Construct-3-bugs#4097]
## Problem description

Browser Plugin Condition "On mobile back button pressed" does not work correctly after Android export. The application closes immediately. I also noticed that if you use the Share function and then return to the application, the back button starts working correctly. (move through application levels)

## Attach a .c3p

n/a

## Observed result

Application closes

## Expected result

Correct work "On mobile back button pressed"

## More details

Lastest Chrome

Tested in r210.

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise we cannot investigate the report and verify that the issue is fixed.
