### ISSUE TITLE
Change Inverted event to Trigger event bug

### ISSUE THREAD

**Issue by Kryhalla** [Scirra/Construct-3-bugs#41]
## Problem description

Changing inverted event to trigger event cause crash.

## Attach a .c3p

https://1drv.ms/u/s!AkqW7J1eLD1hgccvcDQ1sNrXGONK4A

## Steps to reproduce

1. Create Sprite
2. Add inverted event ( Sprite   [ X Is visible ] )
4. Change event to Trigger event ( Sprite [ On created ] )

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: condition not invertible
Stack: Error: condition not invertible at ee.ǃlj (https://editor.construct.net/r16/main.js:61:290946) at ǃp.ǃDx.then.f (https://editor.construct.net/r16/components/editors/eventSheetView/eventSheetView.js:1:72348)
Construct 3 version: r16
URL: https://editor.construct.net/
Date: Fri Apr 07 2017 23:46:08 GMT+0300 (FLE Summer Time)
Uptime: 19.2 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r18.
