### ISSUE TITLE
Typing to select conditions/actions should focus best matches first

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#410]
## Problem description
Problem has been explained in details here : https://www.scirra.com/forum/viewtopic.php?f=191&t=192270&p=1125484&sid=07468fc00f785ccca0c5b9b806a68a2d#p1125484

When typing to select a given action/condition in a dialog, results based on the description often appear before the results that contains the typed characters.
For example, typing "tr" will focus "compare two values: "Compare two arbi**tr**ary values" before "trigger once while true"

## Steps to reproduce

1. just type anything in an add action/condition dialog
2. basic entries such as "compare two values" or "triggers once while true" are now quite hard to select with the keyboard only.

## Observed result
typing "tr" gives "compare two values" as the first result
typing "compare" gives "is between angles" as the first result

## Expected result
typing "tr" should give "trigger once while true" as the first result.
typing "co" should give "compare two values" as the first result.
Both were working that way in C2.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, this is a good catch on usability. I've updated r34 so the default selected item is now the first item that has a match directly in the name, so now cases like typing "tr" by default select "trigger once" (even though "compare two values" is still in the results list). So you can still type "tr" and hit Enter and get a "trigger once" event.

**Comment by RabloGames** [comment]
Thanks Ashley! Looking forward to R34! :)

**Comment by AshleyScirra** [comment]
It's already out!
