### ISSUE TITLE
Error when saving for the first time

### ISSUE THREAD

**Issue by Ludipe** [Scirra/Construct-3-bugs#4101]
## Problem description

I get an error when saving using the Ctrl + S shortcut (if I press it a second time right after that it tends to work). Construct and NW are fully updated. The error message is:

"Unable to save the project. Try checking you have permission to save in the chosen location. Alternatively, try saving a different way."

## Attach a .c3p

https://drive.google.com/file/d/1iegt0tL_xxAnRw3mesYFZxDD52-kQnGa/view?usp=sharing

## Steps to reproduce

1. Save the attached project as a folder.
2. Change something in the project.
3. Try to save the changes pressing Ctrl + S.

## Observed result

It shows the following error:

"Unable to save the project. Try checking you have permission to save in the chosen location. Alternatively, try saving a different way."

If I close that window and press Ctrl + S again it finally goes on and saves. But after 4-5 minutes, when I'm about to save again, the same thing happens. A couple of times I had to press the saving shortcut 3-4 times before it saved it. 

## Expected result

It should work on the first try. I shouldn't get an error when trying to save.

## More details

I'll be attaching a .c3p version of the project I just created after updating Construct. But this is happening in all my older projects as well (all of them saved as a folder on my hard drive).

I' using the desktop version on W10 and this started happening ONLY after the last update. So far it seems to be working as long as I keep closing the errors and saving twice, but getting saving errors is always quite worrying.

**Affected browsers/platforms:** W10

**First affected release:** r210 (stable).

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.47.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.47.2 (like Chrome/84.0.4147.105)
C3 release: r210 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 60 gb
Storage usage (approx): 1.8 gb (3.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It works fine for me. If you press F12, are there any more error details logged in the console?

My best guess is the error message is actually correct, and for some reason your access to that folder is being revoked.

**Comment by Ludipe** [comment]
I had my project inside a dropbox folder (that is synched and updating with every change). Last night I moved my project out of that folder and I stopped getting the warning message. Could it be linked to that?

I'll try moving it back to Dropbox and seeing if it triggers again so I can check the console.

**Comment by AshleyScirra** [comment]
Yes, I think that would cause the problem: every time you write to the file, Dropbox will immediately start to try to sync the file, which may conflict with Construct's attempt to write to the file. Whether or not it succeeds will be effectively random depending on which program wins the race to access the file. Hopefully it's not too much trouble to move the file somewhere else - or just use the Cloud Save feature to access Dropbox files directly.
