### ISSUE TITLE
Loading an image URL from File Chooser into a Sprite crashes Chrome if the picture was taken on a mobile phone camera

### ISSUE THREAD

**Issue by TinyHatGames** [Scirra/Construct-3-bugs#4102]
## Problem description

Loading an image URL from File Chooser into a Sprite crashes Chrome if the picture was taken on a mobile phone camera.

## Attach a .c3p

[File Chooser Image Display Test C3P.zip](https://github.com/Scirra/Construct-3-bugs/files/5051472/File.Chooser.Image.Display.Test.C3P.zip)

## Steps to reproduce

1. Take a picture on a phone camera (tested on Android)
Here is a picture triggering the bug attached, in case you can't replicate it with pictures taken on your devices: 
[IMG_20200624_150052.zip](https://github.com/Scirra/Construct-3-bugs/files/5051517/IMG_20200624_150052.zip)
2. Pick the picture using the file chooser.
3. Use "Load an image URL" to load the picture into a Sprite.

## Observed result

As soon as the URL tries to load, the Chrome tab crashes with no error message in the console.

![image](https://user-images.githubusercontent.com/30088507/89795117-491c7d00-db28-11ea-9be9-85508213c089.png)

## Expected result

The picture should be loaded into the Sprite.

## More details

I believe this issue started with Chrome 84, I know it's fairly recent but I don't know the exact date it started happening. Please note it works properly in Firefox. Please also note it works ok with regular pictures: the bug only happens with pictures taken on a mobile phone.

In an Android app, the picture still loads but looks glitchy: 

![image](https://user-images.githubusercontent.com/30088507/89795069-3ace6100-db28-11ea-9312-db8d60b6ccce.png)

**Affected browsers/platforms:**

Windows, Android - Chrome 84

**First affected release:**

r209 (although I believe the version itself is irrelevant, it's an issue with Chrome and the way this feature is implemented in the Construct 3 engine).

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 84.0.4147.105
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 314 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid a tab crash is a Chrome bug, not a Construct bug. Could you file this with Google at crbug.com instead? If you share the bug number I'll star the issue and follow up if Google have any Construct-specific questions.

**Comment by TinyHatGames** [comment]
Thanks for your reply @AshleyScirra. I realized the bug came from the orientation metadata, only vertical images are affected by this bug. I found a way to make it work in my project by modifying this metadata thanks to the Binary object. I will try to report it to chrome, in the meanwhile, I'm closing this issue. Cheers!
