### ISSUE TITLE
iOS exports won't work

### ISSUE THREAD

**Issue by TechBoxNorth** [Scirra/Construct-3-bugs#4103]
## Problem description
Project exported to iOS doesn't work

Trying to run a simple game exported to iOS on physical device and simulator, all I get is "Build successful" then nothing. I have no problem running simple sample games made in other engines.

Provided project exported to android seems to be working fine.
## Attach a .c3p

[Mobile Test.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5055641/Mobile.Test.c3p.zip)

## Steps to reproduce

1. Export provided project with iOS export -> Xcode project
2. Open it in Xcode
3. Try to run in on a device or in a simulator

## Observed result
Project builds but won't install and start on device or simulator

## Expected result
It should be installed and started on both a simulator and on a device

## More details

**Affected browsers/platforms:** 
iOS

**First affected release:** 
r210.2 not tested with earlier versions
## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Browser: Chrome
Browser version: 84.0.4147.105
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.15_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 1.2 tb
Storage usage (approx): 387 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 580X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by TechBoxNorth** [comment]
Tried opening it in xcode using the .xcworkspace file and now it builds and installs  the game but it gets stuck on loading screen just as previously described in the forums. I guess Xcode chooses the .xcworkspace file when opening a project by just selecting the folder that holds the project.

**Comment by AshleyScirra** [comment]
It's working absolutely fine for me. It's [documented](https://www.construct.net/en/tutorials/ios-application-development-and-publishing-with-xcode-25) that you must open the .xcworkspace file or it won't work. The iOS simulator is also currently not supported due to [this iOS bug](https://bugs.webkit.org/show_bug.cgi?id=191064) (although that appears to be fixed for a future version of iOS). So in short you have to use the .xcworkspace file and test on a physical device. I would assume you've not done that, or have misconfigured the development setup.
