### ISSUE TITLE
"Enable UI Animation" bug.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4104]
## Problem description

When "Enable UI Animation" is disabled, if you close a tile (from a tilemap) edit window, C3 crashes.

## Attach a .c3p

Every file should present it.

## Steps to reproduce

1. Create a tilemap.
2. Under "Settings", disable "Enable UI Animations".
3. Edit any tile and close the edit window.
4. C3 crashes.

## Observed result

Crash.

## Expected result

No crash.

## More details

**Affected browsers/platforms:** Latest Chrome.

**First affected release:** 210.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'rj' of null @ TypeError: Cannot read property 'rj' of null at https://editor.construct.net/r210-2/components/bars/tilemapBar/tilemapBar.js:35:365
Stack: TypeError: Cannot read property 'rj' of null at https://editor.construct.net/r210-2/components/bars/tilemapBar/tilemapBar.js:35:365
Construct 3 version: r210.2
URL: https://editor.construct.net/
Date: Tue Aug 11 2020 08:58:09 GMT-0300 (Brasilia Standard Time)
Uptime: 97.8 s

Platform information
Browser: Chrome
Browser version: 84.0.4147.125
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (ATI Radeon 3000 Graphics Direct3D11 vs_4_0 ps_4_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_disjoint_timer_query, EXT_float_blend, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, EXT_sRGB, KHR_parallel_shader_compile, OES_element_index_uint, OES_fbo_render_mipmap, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
