### ISSUE TITLE
angleLerp got messed up in R211 (R210.2 was still ok)

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4106]
## Problem description

angleLerp is no longer working as it should, some angles (207 degree and above) are jumping all over the place.

## Attach a .c3p

[angleLerp.zip](https://github.com/Scirra/Construct-3-bugs/files/5057758/angleLerp.zip)

## Steps to reproduce

1. Try feeding 208 into the textbox, or just go through the angles.

## Observed result

Objects angles are jumping, it seems like a sprite and a 9patch react a bit different to this bug.

## Expected result

Rotate normally.

## More details
Tried it on NWjs 47.2.0 and latest chrome with the online version.

**Affected browsers/platforms:** 

**First affected release:** r211

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
@DiegoScirra - I would guess some of the angle related timeline changes ended up breaking this

**Comment by skymen** [comment]
I did some digging:
Turns out the angleLerp function has been rewritten and it breaks some calculation (I got especially spectacular results with 90 angles)
OLD ANGLELERP:
```
function angleLerp(a, b, x) {
    let diff = C3.angleDiff(a, b);
    if (C3.angleClockwise(b, a))
        return C3.clampAngle(a + diff * x);
    else
        return C3.clampAngle(a - diff * x)
}
```

NEW ANGLELERP:
```
function angleLerp(a, b, x, r=0) {
    let diff = C3.angleDiff(a, b);
    const revs = TWO_PI * r;
    if (C3.angleClockwise(b, a))
        return C3.clampAngle((a + diff + revs) * x);
    else
        return C3.clampAngle((a - diff - revs) * x)
}
```

This is what the change did to my game by the way lol https://youtu.be/3ztfvnYitw0 

Did you mean to write this maybe? Cause the way you placed parenthesis makes it so a gets multiplied by x when it didn't used to.
```
function angleLerp(a, b, x, r=0) {
    let diff = C3.angleDiff(a, b);
    const revs = TWO_PI * r;
    if (C3.angleClockwise(b, a))
        return C3.clampAngle(a + (diff + revs) * x);
    else
        return C3.clampAngle(a - (diff - revs) * x)
}
```

**Comment by DiegoScirra** [comment]
Should be fixed in the next beta.
