### ISSUE TITLE
Copy & Paste does not work for Event Sheets.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4108]
## Problem description

I cannot use Copy & Paste in Event Sheets because the Paste option never shows.
https://giphy.com/gifs/construct-el2Zwscd88mRqAktxh

## Attach a .c3p

Any file should present it.

## Steps to reproduce

1. Copy any Event Sheet.
2. Try to Paste it anywhere, mainly in the Event Sheets folder or another Sheet.
3. See that it is not possible.

## Observed result

No Paste option shows.

## Expected result

Paste option showing.

## More details

**Affected browsers/platforms:** Latest Chrome.

**First affected release:** 211.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It works fine for me. Please follow the bug report guidelines, such as including all your system details, there might at least be some clue in there. Are you sure you haven't blocked clipboard permission for the page? Are you using any browser extensions that might be blocking permission to access the clipboard? That's all I can think this could be.

**Comment by dupuqub** [comment]
Found it. It only works with "Use in-app clipboard" disabled. Also happens in Edge.

**Comment by AshleyScirra** [comment]
Ah, that was the key missing detail. Thanks, should be fixed for the next release.
