### ISSUE TITLE
Inconsistent Behaviour When Requesting Fullscreen on Desktop/Browser

### ISSUE THREAD

**Issue by SecondDimension** [Scirra/Construct-3-bugs#4109]
## Problem description

I mainly create games for desktop, so in many of my projects I use a variable to determine if the game will start in fullscreen mode, if selected the game will call a function which requests fullscreen using the browser plugin. This has worked successfully for at least a year in C3, but has stopped working on my projects since I updated. I have recreated the issue in a very minimal file (attached below), but the difficult part is that is _does sometimes work_.  In the minimal project, it seems to work as required when previewing from the project view, but if you use the preview layout or preview project shortcuts from the dropdown above the layout view, then it does not work (the variables are updates but the fullscreen request is denied).  In my other projects it  works every now and then despite using the same method to preview the project.

In the console there is an error that "fullscreen can only be called from a user gesture", which I would expect from mobile but not from browser or desktop, and as mentioned above sometimes it does work fine without a user gesture.  This has been working fine for a long time, and launching in fullscreen is expected for desktop games released on Steam/itch.io etc

## Attach a .c3p

Attached, would not allow a .c3p so zipped it up:
[Fullscreen Bug Test.zip](https://github.com/Scirra/Construct-3-bugs/files/5058132/Fullscreen.Bug.Test.zip)

## Steps to reproduce

1. Open file in browser or nwjs
2. Use the shortcut above the layout view to preview
3. Observe the fullscreen variable change but the fullscreen request be ignored

## Observed result

The browser or nwjs did not go fullscreen

## Expected result

The browser or nwjs should go into fullscreen mode

## More details
Tested on Chrome, Edge & nwjs

Noticed the issue in r210, tested r210-2 and issue remains

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 84.0.4147.125
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 64 gb
Storage usage (approx): 158 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
For security reasons, browsers (on all platforms, desktop and mobile) may ignore fullscreen requests. Note it's termed "request", not a command.

Typically browsers decline fullscreen requests that are not in a user input trigger. In this case if you look in the console it's also declining the first fullscreen request, because the document does not have focus yet, i.e. the first input event in the page is not allowed to immediately enter fullscreen mode.

It's incorrect to use your own variable to track fullscreen mode because your variable assumes fullscreen requests always succeed, but they may be declined, in which case the variable ends in the wrong state. Use the Browser object's 'Is fullscreen' condition to test whether you're really in fullscreen mode or not.

**Comment by SecondDimension** [comment]
This has worked for years, on C2 and C3 it has worked for years, it always worked 100% consistently with no issues. It worked and now the software updated and it doesn't.  It's just so incredibly demoralising to have something work for years, stop working and then be told it's not a bug.

**Comment by SecondDimension** [comment]
Something I feel you skipped over is why it works when previewing the project when using right-click on the project name, but not when previewing the project from the shortcut button above the layout. This is 2 inconsistent behaviours from construct when doing the exact same thing.

**Comment by AshleyScirra** [comment]
This is to do with the restrictions imposed by browsers, not Construct. I guess maybe recently browsers adjusted how their restrictions work. Sorry, sometimes these things change, and it's out of our hands. Most of the time software has to be maintained with occasional updates to match changes in other areas, and that's what you need to do with your project here too.

**Comment by TheRealDannyyy** [comment]
This seems to be caused by NWjs itself. I've reported it here: https://github.com/nwjs/nw.js/issues/7542

**Comment by SecondDimension** [comment]
Thanks for the replies and to everyone who looked into this. For anyone reading this thread with a similar issue, there is workaround for fullscreen in nwjs in the following forum thread, thanks to Fib for documenting it:
https://www.construct.net/en/forum/construct-2/general-discussion-17/big-nw-js-roundup-news-tips-119428/page-30#forumPost1019336
