### ISSUE TITLE
Impossible to access "Add Parameter" in a Call function dialog without using the mouse

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#411]
## Problem description
In C2, in a Call Function dialog, it was possible to press TAB then ENTER to define any number of parameters. It doesn't seem to be possible to add parameters in C3 without using to the mouse.

## Steps to reproduce

1. create a new event, add a function / call function action.
2. enter the Function's name then press TAB
3. Add parameter isn't focus. 

## Observed result
Add parameter can't be selected without using the mouse.

## Expected result
Pressing TAB once should select "Add parameters" so that the user can add parameters without switching to the mouse.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in r34.
