### ISSUE TITLE
(R211) Timeline: Initial Frame on Sprite does not change correctly while playing a timeline in editor

### ISSUE THREAD

**Issue by Fib100** [Scirra/Construct-3-bugs#4110]
## Problem description

In a timeline, the Initial Frame property on a Sprite does not visually update in the **layout view** while playing the timeline in the editor. If you preview the layout then it works just fine.

## Attach a .c3p

[initialframe_timeline_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5058908/initialframe_timeline_bug.zip)

## Steps to reproduce

1. Add a timeline to the project in the Project Bar
2. Add the Timeline object to the project
3. Open the Timeline Bar so you can manipulate the timeline
4. Add a Sprite object to your project
5. Add frames to the sprite animation that are very different from other frames
6. Add a sprite instance to the Timeline Bar
7. Right click on the mater track and add a property
8. Select "Initial Frame" and click "Ok"
9. Create some keyframes that modify the Initial Frame track
10. Click the Play button in the timeline bar
11. Observe that the frame of animation never changes
12. Click the Preview button to preview the layout
13. Observe that the frame of animation does change

## Observed result

The frame of animation never changes in the layout view when playing the timeline in the editor.

## Expected result

The frame of animation should change in the layout view so we can preview what the full timeline is doing.

## More details

**Affected browsers/platforms:** 

Just tested it on Chrome version 84.0.4147.105 (64bit).

**First affected release:** 
Just affects R211.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
