### ISSUE TITLE
(R211) Timeline: When you stop and restart a timeline from the beginning (during runtime) the playback rate increases

### ISSUE THREAD

**Issue by Fib100** [Scirra/Construct-3-bugs#4111]
## Problem description

When you stop a timeline at runtime in the middle of playback, then you restart it from the beginning (during runtime) the playback rate increases more and more each time you do it.

## Attach a .c3p
[speedup_timeline_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5059045/speedup_timeline_bug.zip)

## Steps to reproduce

1. Run the provided c3p file in R211 and preview the layout
2. Use the spacebar to stop it in the middle of playback (it's a 10 second long timeline so that shouldn't be too hard), it will also set the timeline time to zero and re-play it (see the event sheet for details of how I'm doing it)
3. Observe that each time the timeline re-plays the playback speed increases

## Observed result

The playback speed of the timeline keeps increasing each time you stop and re-play the timeline during runtime.

## Expected result

The playback rate of the timeline should never change except when explicitly done so with the "Set playback rate" action.

## More details

**Affected browsers/platforms:** 
Just tested it on Chrome version 84.0.4147.105 (64bit).

**First affected release:** 
First noticed it in R211. But I can't open the attached project in earlier versions so not sure if it happens in any earlier versions.
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
