### ISSUE TITLE
Latest Edge won't load from cloud.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4112]
## Problem description

Latest Edge won't load from cloud.
![bug](https://user-images.githubusercontent.com/34659544/89972010-25922900-dc33-11ea-97f8-3cf54a2c02b2.PNG)

## Attach a .c3p

n/a

## Steps to reproduce

1. Open a clean lastest Edge (no addons)
2. Open C3.
3. Try to load from cloud.

## Observed result

Blank panel.

## Expected result

Load from cloud.

## More details

**Affected browsers/platforms:** Latest Edge.

**First affected release:** Tested in 211.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This looks like some kind of rendering bug in Edge that also seems to have appeared in NW.js lately. I can reproduce in Edge 84.0.522.59 - Construct's doing everything right, all the elements are there, but Edge is not showing them for some reason - but it works fine in Edge Dev (86.0.594.1). I would guess this is some kind of bug in the Chromium engine that has already been fixed, so we just need to wait for the next update.
