### ISSUE TITLE
Tilemap drag-and-drop doesn't take the .tsx file

### ISSUE THREAD

**Issue by 7Soul** [Scirra/Construct-3-bugs#4114]
## Problem description

The Tilemap Bar manual entry says you can drop all files and just press OK, but the "tileset file" doesn't get filled

## Attach a .c3p

It's an interface problem so a .c3p doesn't do anything

## Steps to reproduce

1. Select a tmx, tsx and png file at once
2. Drop into the tilemap bar

## Observed result

The tsx field isn't filled in

https://i.imgur.com/4xsHPF2.png

## Expected result

All fields filled in

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 211

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
