### ISSUE TITLE
Multiplayer and Remote Preview not working correctly

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#4115]
## Problem description

Multiplayer getting RTC errors. Doesnt connect to the turn servers.
But it doesnt work neither from two computers in different ip.

Also the exact same error jumps when trying to remote preview in the smartphone.

## Attach a .c3p
use chat example

## Steps to reproduce
Remote Preview
1. Try to remote preview to a smartphone in chrome

Multiplayer
1. Try to connect to the chatroom from different IP's (or different computers)

## Observed result
the error en chrome

## More details

Firefox:
WebRTC: ICE failed, add a TURN server and see about:webrtc for more details

Chrome:
PeerConnection error:  RTCErrorEvent
KU @ exporter.js:29
error: RTCError: Transport channel closed

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Both multiplayer and remote preview are working fine for me.

Whether or not it can connect depends on your network connectivity and configuration. It's not to do with Construct.
