### ISSUE TITLE
Local Storage plugin not saving on IOS

### ISSUE THREAD

**Issue by cerxer** [Scirra/Construct-3-bugs#4117]
## Problem description

Local storage plugin saves data on web and android browsers but not on IOS. im using poki platform to publish games. I found out that my games were not saving on IOS devices. I tested on my Ipad (IOS 12.4.8) device with safari and chrome. I use local storage template and have the same result so i ll give the link to playable project or you can upload yourself. 

## Attach a .c3p

https://qa.po.ki/#?key=94224199-3a22-492f-8e85-d0233d65ff31
[Local Storage - High score.zip](https://github.com/Scirra/Construct-3-bugs/files/5078391/Local.Storage.-.High.score.zip)

## Steps to reproduce

1. Set a highscore.
2. Refresh or Restart the browser.

## Observed result

Highscore not saved on IOS device, no problem with web or android.

**Affected browsers/platforms:** 

IOS(12.4.8) - Chrome and Safari

**First affected release:** 
r210.2

**Comment by AshleyScirra** [comment]
No project file has been provided - only exported projects - so I tried the 'Local storage - high score' example in C3 with Remote Preview on an iPad Pro running iOS 13.6. It worked fine.

The Poki link provided has expired. Given it seems to work fine for me, I would guess this is either an issue with the Poki service, or an iOS storage bug (iOS has pretty awful bugs in this area) - neither of which is related to Construct so would need to be pursued separately.
