### ISSUE TITLE
#4041 Still not fixed?

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#4119]
***Apologies for not using a template, but i hope i attached all the neccessary information.***

Probably related to #4041. Save and load (in my case only load) still crashes/freezes the game and doesn't work. 

*****IMPORTANT**:***

**Also important, I'm using a Tween immediately after "On load completed".**

Tested with:
r203 - **works perfectly** 
r208, and the newest r211 - **same project, and the same events**, crashes/freezes

**Comment by DiegoScirra** [comment]
This could be a similar, but different issue. Please follow the guidelines.

The most important is to provide steps to follow to reproduce the issue along with a test project.

**Comment by AshleyScirra** [comment]
Our policy is to close reports that are not actionable, so closing.
