### ISSUE TITLE
Crash when attempting to duplicate layout

### ISSUE THREAD

**Issue by BernardWrangle** [Scirra/Construct-3-bugs#412]
## Problem description
Duplicating a specific layout crashes app in Chrome

## Attach a .c3p

https://drive.google.com/open?id=0B2mi7Z0OwMDqb3JhUU1lVXpRTjg

## Steps to reproduce

1. Right click on the layout 'Debug Local Map'
2. Select 'Duplicate'
3. Watch C3 crash :*(

NOTE: It does not crash if you duplicate the 'Debug Main Menu' layout.

## Observed result

Pop-up reading "Oops! Something went wrong."

## Expected result

The layout would be duplicated in the project toolbar

## Affected browsers

* Chrome: yes
* Firefox: *Unable to use firefox, construct says it's not supported though it is up-to-date*
* Edge: Don't use
* Safari: Don't use

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r33/main.js, line 61, col 198856
Message: Uncaught TypeError: Cannot read property 'ǃyM' of null
Stack: TypeError: Cannot read property 'ǃyM' of null at d.ǃuP (https://editor.construct.net/r33/main.js:61:198856) at k.ǃyy.ǃJv (https://editor.construct.net/r33/plugins/tilemap/plugin.js:1:2135) at s.ǃuT (https://editor.construct.net/r33/main.js:61:154257) at u.ǃm_x (https://editor.construct.net/r33/main.js:61:243314) at r.ǃm_L (https://editor.construct.net/r33/main.js:61:229705) at r.ǃYO (https://editor.construct.net/r33/main.js:61:228406) at i.ǃvZ (https://editor.construct.net/r33/components/bars/projectBar/projectBar.js:1:23728)
Construct 3 version: r33
URL: https://editor.construct.net/
Date: Thu Jun 01 2017 10:45:44 GMT-0400 (Eastern Daylight Time)
Uptime: 53.9 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r33

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon(TM) HD 7450 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

BTW, besides the growing pains, I'm loving C3! Thanks for your hard work.

**Comment by DiegoScirra** [comment]
Look out for the fix in the next release, r34.

**Comment by BernardWrangle** [comment]
Very cool! Thanks for the quick reply.
