### ISSUE TITLE
Saving in a secondary tab opens "save as HTML" window.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4125]
## Problem description

When saving through CTRL + S in a secondary tab (tested with secondary tabs of the text editor) the project saves normally, but it also opens a window trying asking to save the contents of the page as an HTML file.

## Attach a .c3p

Every file should present it.

## Steps to reproduce

1. Detach a panel from the main tab of the editor (tested with the text editor and sheet editor).
2. Press CTRL + S.
3. See the project saves normally, but also a window appears trying to save the page as an HTML file.

## Observed result

Save window.

## Expected result

No save window.

## More details

**Affected browsers/platforms:** Latest Edge.

**First affected release:** 211.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

ps: On an "unrelated" note, just a small question, recently I've posted an idea about being able to put more than 1 panel per secondary tab, is it too farfetched? No pressure, just to keep my hope in check, recently I've been working a lot with secondary tabs, they are awesome. 💯

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
