### ISSUE TITLE
TextInput Object isn't aligned correctly to it's BoundingBox

### ISSUE THREAD

**Issue by Unconected** [Scirra/Construct-3-bugs#4130]
I didn't think this was a big deal, I was only giving feedback.
I didn't consider this a bug, so I contacted Scirra Support.
I was asked to make this post.

## Problem description
TextInput Object isn't aligned correctly to it's BoundingBox.

## Attach a .c3p
https://media.discordapp.net/attachments/720015379333906484/745419431198326845/Annotation_2020-08-18_033301.png

A .c3p wouldn't help here.

## Steps to reproduce
Create a TextInput Object
Have Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)

## Observed result
TextInput Object isn't aligned correctly to it's BoundingBox.

## Expected result

TextInput Object is aligned correctly to it's BoundingBox.

## More details

Email Chain
****************************
To Scirra Support
There is a minor visual error on TextInput Object

I have a TiledBackground that is 400 width at 0X,0Y
I created a TextInput Object at 320 width. at 40X, 20Y.
The TextInput should appear in the middle of the TiledBackground.
40 + 320 + 40 equals 400.

If I highlight the TextInput the BoundingBox is in the middle of the TiledBackground, but the 'White Box' behind the BoundingBox is offset a small bit. Visually the 'White Box' does not appear to be in the middle.
It makes either a visual difference with the 'White Box' or an alignment difference with the BoundingBox.

I am aware this isn't much of a deal and understand it may not get fixed. I was only pointing it out. It isn't causing me issues.
Since the BoundingBox will most likely not change, I don't see it causing any problems for existing projects if the alignment gets adjusted.

****************************
From Scirra Support
I'm afraid this is how browsers render this DOM element and I'm not sure there is much we can do about it.

In regards to issues with Construct 3, please visit our bug database and make sure your bug was not already reported.

If it was, you may add informations as comment to the ticket.
Otherwise create a new report and fill all the informations required to allow our devs to investigate in order to fix in the next releases of Construct 3.

Kind regards

## System details
C3 r210.2 stable
Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by AshleyScirra** [comment]
Please attach a .c3p file. It always helps - we routinely can't reproduce issues that people report because they often depend on far more specific circumstances than you imagined, and so attaching a .c3p up-front can save a lot of time.

**Comment by Unconected** [comment]
https://www.dropbox.com/s/7rp676lewqt9gwj/TextInput.c3p?dl=0

I didn't think a C3P was needed if it was a Chrome rendering issue.
I added details and marked where I see the bounding box and the 'White Box Field' where you enter text along with C3 and Chrome Version. The 'White Box Field' seems aligned correctly on the top and left, but is about 2 or 3 pixels to long on the right and bottom of the Bounding Box. Doesn't seem to big of a  deal to me, but I guess it could cause problems for some.

**Comment by AshleyScirra** [comment]
This is just due to the CSS box model. By default the border size is not included in the element dimensions. If you want it to be included, you can set the CSS style `box-sizing: border-box`.
