### ISSUE TITLE
This project will not open after export

### ISSUE THREAD

**Issue by medervolfr** [Scirra/Construct-3-bugs#4133]
## Problem description

After I Export the project on my android pixel 2 device, the game is stuck at the preload bar.

## Attach a .c3p

https://easyupload.io/vfiwcp

## Steps to reproduce

Simply export the project , as a signed android  apk.
Install it in your android device and open it.

## Observed result

It freezes in the preload screen. The preload bar keeps being 0.

## Expected result

Load and go to the splash/home screen.

## More details
The problem is the MobileAdvert plugin. In case i want to take it out, the app is loading properly on my android device. 
I've added the same way the same plugin(mobile advert) to my other c3 projects and they all load fine.
Something in this project is (together with mobile advert ) crashing the app.

I've spend all day to figurite it out, but i don't see anything wrong with my code implementation.

This is a simple C3 proj file, with 2-3 layouts and a few lines only. It will not take much to check it out.

**Affected browsers/platforms:** 

I've tested it out with the latest c3 stable version(r210.2) and as well with the latest beta version(r212)

## System details

<details><summary>View details</summary>

I don't get any crash report. The app just freezes.

</details>

**Comment by layilpaht** [comment]
I am facing the same issue but I am unable to prove it. And even more furious fact, it happens only with my project 
Just few more points left:- does it happen only with advanced minification? Mine hangs on the loading bar only in advanced minification. But with simple minification the project works.
And Ashley please this time test with "signed version". Maybe this has to do with the bug.
Thanks for reporting the error. It may also solve my issue

**Comment by medervolfr** [comment]
Update: layilpaht has been right, if i use Simple minification, it works fine.
Update2: Google play plugin is the one crashing together with mobile advert plugin. If you take out one of them, the app is working. You cannot have both of them.

**Comment by layilpaht** [comment]
Why did you closed the bug?
I was facing the same issue and this is a very important issue. And I am neither using admob nor google play,so this issue must have some internal connections. So maybe in future you may encounter the bug again
And anyway advanced minification is very important specially for projects where admob is used. In this way it becomes very very tough for the crackers to steal and edit admob details. Hence you should strictly go with advanced minification
Anyway it is up to you whether you want to open the bug or not. Best of luck for the project !!!

**Comment by AshleyScirra** [comment]
FYI, advanced minification does not do anything to conceal your Admob settings. It doesn't work like that. It just renames properties and variables in the surrounding JavaScript code.

**Comment by layilpaht** [comment]
> FYI, advanced minification does not do anything to conceal your Admob settings. It doesn't work like that. It just renames properties and variables in the surrounding JavaScript code.

Still issue is very important

**Comment by layilpaht** [comment]
@AshleyScirra any update regarding the bug ?

**Comment by AshleyScirra** [comment]
I suspect this is a bug we've seen a couple of times in the latest version of Closure Compiler. It should be fixed in the next release of Closure Compiler, so we first need to wait for that release to come out.

**Comment by AshleyScirra** [comment]
The original URL has expired so it is no longer possible to investigate this report. Closing.

Please note this from the bug report guidelines:

> If you choose a different file host and it spams us with ads, asks us to sign up or enter information, or expires by the time we look at it, we will not investigate the bug. We recommend the three services mentioned previously since they work well.
