### ISSUE TITLE
Official Facebook Plugin popup blocked by Iphone Safari

### ISSUE THREAD

**Issue by ikzuquan** [Scirra/Construct-3-bugs#4134]
## Problem description
Facebook login popup prompt is blocked by **iphone safari** (safari **does not even prompt error or ask to unblock**, so it makes it look like a bug) 
- I have tried using button to trigger the popup
- Touch Event (tap and double tap) to trigger the popup
- Mouse event to trigger the popup

None of the above works. The user have to manually turn off the popup blocker in order to continue.

## Attach a .c3p

http://ikzq.net/testfb/FacebookLogin.c3p

## Steps to reproduce

1. Add Official Facebook Plugin
2. Add App ID (Can use my Sample App ID: 1880111698702875)
3. Add Button
4. Add Event -> Onclick Button, Prompt FB Login

## Observed result
Nothing Happens in Iphone Safari, no error, no prompt, no warnings

## Expected result
It should prompt for login like other browser

## More details
Construct 2 Official Facebook Plugin works fine compare to C3

**Affected browsers/platforms:** 
Iphone Safari only, probably ipad as well.

**First affected release:** 
First time using FB plugin on C3, so not sure which version broke it
## System details

<details><summary>View details</summary>

No error shown

</details>

**Comment by AshleyScirra** [comment]
Safari is fussy about exactly when windows can be opened. I adjusted our code to make sure it keeps any user-input trigger, since Safari can only open popups in such events. It should be working in the next release.
