### ISSUE TITLE
Search doesn't show objects in family

### ISSUE THREAD

**Issue by NOAHGengo** [Scirra/Construct-3-bugs#4135]
## Problem description

There are times when you want to have access to each of the objects in a family individually, such as to configure their family variables. When you search for a family, the family shows up but none of the objects in the family show up. This makes it useless to search for a Family since you don't have access to the objects within it

## Attach a .c3p

[Search.zip](https://github.com/Scirra/Construct-3-bugs/files/5096399/Search.zip)

## Steps to reproduce

1. Open Project
2. Search for "family"

## Observed result

Family1 shows up in the search

## Expected Result

Family1, along with all the objects within it show up

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** It's been like this for as long as I can remember 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 84.0.4147.125
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 295 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
This is currently by design. If an item matches search, it does not match any of its children unless they also match search. For example if you open Space Blaster and search for "Backgrounds", it matches the "Backgrounds" subfolder in the Object Types section, but not the actual objects inside it.

The reason for this is if it did, the search results would get full of unrelated results. For example searching "Famil" would include the "Families" folder, and therefore include the entire contents of the families folder including families of all names, which doesn't seem to be appropriate.

If you want to request that design aspects are changed, file a suggestion on the features platform: https://construct3.ideas.aha.io/

**Comment by NOAHGengo** [comment]
Why would you want to search for a folder but not it's contents? Just to check if it exists? That doesn't make sense. That's like if you could only search for folders on your computer but you couldn't open them and had to instead manually navigate to them

The main top-level project folders like Families obviously shouldn't be searchable. Excluding them from the search would solve your proposed problem

There are often cases where you want to adjust parameters individually for each object in a family. Right now that becomes extremely tedious when a project becomes large and the search function does absolutely nothing to help it

-------- Original Message --------
