### ISSUE TITLE
Resizing the preview window messes up the timing in timeline

### ISSUE THREAD

**Issue by Inth** [Scirra/Construct-3-bugs#4136]
I use timeline in my project to synchronize red border movement with the song that is playing.
When I resize the preview window to super small or medium and press the play button it works ok when I refresh the preview and resize the window to super big and hit the play button the red rectangle movement is much slower then it should. 
the timing is greatly changed and no longer reflect my initial settings.

## Attach a .c3p
[bug discovered.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5096769/bug.discovered.c3p.zip)

## Steps to reproduce

1.run the project in preview mode
2.resize the preview window to super small 
3.press play button and observe how the red rectangle is moving through the notes according to the song
4.refresh the preview window
5.resize it to super big
6.press play button 
7.observe how the red rectangle is much slower then it was before not really following the music

has been reproduced by another used from Discord as well
checked also on beta 212 version same result

## Observed result

- when preview window is resized to super big the red rectangle during playing the song is following the notes too slow
not really following the timing in the timeline

## Expected result

no matter the size of the preview window the red rectangle should follow the timing in the timeline

## More details

**Affected browsers/platforms:** 

- happens on Chrome Version 84.0.4147.125 (Official Build) (64-bit)
- not happening on Opera
- not happening on Firefox

**First affected release:** 

r210.2 stable

## System details

<details><summary>View details</summary>

PASTE HERE

Platform information
Browser: Chrome
Browser version: 84.0.4147.125
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 142 gb
Storage usage (approx): 651 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions:

EXT_color_buffer_float
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
I can't reproduce this one with those steps. Everything seems to work properly in the stable release and the latest beta,

**Comment by skymen** [comment]
I managed to reproduce it by resizing the window to be very small then very big very quickly a bunch of times. It seems to mess up the timeline's timing and offsets the timeline timer from the music timer

**Comment by Inth** [comment]
can we remove the "can't reproduce" tag since skymen could reproduce this issue as well

**Comment by DiegoScirra** [comment]
I still can't, I tried resizing the preview window repeatedly while the timeline is playing and still can't see the problem, at times it seems like there is a problem, but by the end of playback it looks like it is in the correct place.

How big is the offset? Is it glaring? Or rather small?

**Comment by simstratic** [comment]
@Inth are you dropping below 30FPS when using a very large window? A slow down when increasing window size (resolution) usually indicates being GPU limited - and in your system information it says you are using a software renderer (no GPU or maybe a blacklisted GPU?). Construct has a minimum frame rate - by default 30FPS - which limits dt (delta time) to 0.033. If you frame rate goes below 30FPS - objects start to move in slow motion but it won't slow down music - I suspect this is what is causing the red square to desynchronize with your music. If this is the problem, there is a System action 'Set minimum framerate', use this to set a lower framerate at the beginning and it might fix the problem.

**Comment by AshleyScirra** [comment]
@DiegoScirra asked for further details about a month ago and no response has been forthcoming, so closing as the problem cannot be reproduced.
