### ISSUE TITLE
Freezes with array in container with a sprite

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#4137]
## Problem description

I have an object that is in a container with an array.

I have a DUMP layout which I use to store all of my objects. If I accidentally have the DUMP layout open, I have it immediately send me to another layout. I've been able to narrow it down to these objects that are causing the error.

I've had this in place for months, but these last few updates have really broken my project. With the last stable version having the tween plugin broken, I've been forced to upgrade to the beta, which is causing even more problems.

When I look at the browser console, I see the following:

```
Uncaught (in promise) TypeError: Cannot read property 'GetChildren' of null
    at Instance.GetChildren (instance.js:10)
    at Instance.children (instance.js:10)
    at C3Runtime.DestroyInstance (runtime.js:48)
    at C3Runtime.DestroyInstance (runtime.js:48)
    at Layer._End (layer.js:10)
    at Layout._StopRunning (layout.js:23)
    at async C3Runtime._DoChangeLayout (runtime.js:70)
    at async C3Runtime._MaybeChangeLayout (runtime.js:68)
    at async C3Runtime.Tick (runtime.js:61)
```
## Attach a .c3p

[ArrayCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/5100250/ArrayCrash.zip)

## Steps to reproduce

1. Put an array and an object in the same container.
2. Create two layouts, and have the layout with the objects in it go to the other layout at the start.
3. Enjoy the black screen!

## Observed result

It crashes.

## Expected result

It should move onto the other screen without issue.

## More details
A similar issue is happening when I open another layout in the project, but this one's error message talks about physics... so I'll likely post that bug as well once I've narrowed it down.

Both cause a crash in the same way, so they might be related... I'm not sure.

**First affected release:** It seemed to be working fine on the previous broken stable version, but this popped up when I started using r212.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
