### ISSUE TITLE
Wake lock request display for both actions in editor

### ISSUE THREAD

**Issue by TMsimonW** [Scirra/Construct-3-bugs#4142]
When choosing either the wake lock request or the wake lock release in the event sheet they both display as wake lock request

https://drive.google.com/file/d/1WpwqCb7052-69Cor4Td9Ox5gvJdMojRS/view?usp=sharing

## Steps to reproduce

1. Create a project and put 2 buttons on the layout
2. Attach wake lock to one of the buttons on click actions
3. Attach wake lock release to the other button
4. Both buttons actions will display as request wake lock

## Observed result

Both buttons appear to be requesting wake lock 

## Expected result

one button shoud have wake lock request displayed and the other should have wake lock release

## More details

**Affected browsers/platforms:** 

Chrome 84

**First affected release:** 
R212

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks for spotting this, there was a mistake in the language string. Fixed for next release.
