### ISSUE TITLE
Fail to Export to HTML using Advanced Minify when a custom plugin is used

### ISSUE THREAD

**Issue by Sparsha1232** [Scirra/Construct-3-bugs#4143]
## Problem description

Fail to Export to HTML using Advanced Minify in C3 r212 (also occurs in the latest stable release) when a custom plugin is used.

I am using the _singleGlobalPlugin.c3addon_ from the official SDK example. Plugin file is attached below in "Steps to Reproduce"

## Attach a .c3p

[C3 Test Project.zip](https://github.com/Scirra/Construct-3-bugs/files/5112137/C3.Test.Project.zip)

## Steps to reproduce

1. Install the [singleGlobalPlugin.zip](https://github.com/Scirra/Construct-3-bugs/files/5112145/singleGlobalPlugin.zip) plugin
2. Open Test Project and select HTML export
3. Select Advanced Minify

## Observed result

Message on screen: **Failed to export project**

Console Error:
![Error](https://user-images.githubusercontent.com/42723600/90952732-b19e1f00-e483-11ea-9eb3-c9aa45fbd29c.PNG)

## Expected result

Successful Export

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** I have only tried in the latest stable release and also in the latest beta release r212

(Not tested for other export types. Error might exist for other exports too) 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 84.0.4147.135
Browser engine: Chromium
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
C3 release: r212 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 29 gb
Storage usage (approx): 137 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions:

EXT_color_buffer_float
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Third-party addons need to be [updated for the new minifier](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/third-party-addon-changes-153959). You're right that the SDK download samples weren't updated. I just updated them so they should be compatible with the new minifier again: https://www.construct.net/en/make-games/manuals/addon-sdk

**Comment by SparshaDhar** [comment]
Thanks Ashley
