### ISSUE TITLE
GameAnalytics Cordova Plugin to version 3.3.0

### ISSUE THREAD

**Issue by SalmanShhh** [Scirra/Construct-3-bugs#4145]
Hi,

Would you please update an existing plugin version to cordova-plugin-gameanalytics@3.3.0
Thanks.

https://www.npmjs.com/package/cordova-plugin-gameanalytics/v/3.3.0

builds using the GA plugin currently fail to build and urgently need it for an upcoming app store featuring!

**Comment by AshleyScirra** [comment]
I'm afraid we cannot make any guarantees about when Cordova plugin security reviews can be completed. I'll try to get to this soon, but in normal circumstances please expect a few weeks.

**Comment by AshleyScirra** [comment]
`cordova-plugin-gameanalytics@3.3.0` is now on the allowlist.
