### ISSUE TITLE
(R210.2) Typewriter text does not obey the text objects own timescale

### ISSUE THREAD

**Issue by Fib100** [Scirra/Construct-3-bugs#4146]
## Problem description

When using typewriter text on a Text Object, it does not use the object's timescale, it always uses the global timescale.

## Attach a .c3p

[typewriter_text_timescale_issue.zip](https://github.com/Scirra/Construct-3-bugs/files/5114933/typewriter_text_timescale_issue.zip)

## Steps to reproduce

1. Add a Text object to the project
2. On start of layout set the global time scale to 0, then set the text object's timescale to 1.
2. Also, On start of layout, start typewriter text and run the layout
4. Observe that the typewriter text does nothing
5. Remove the action to set the global time scale to 0 and run the layout again
6. Observe that the typewriter text works again

## Observed result

The typewriter text does nothing. If you remove the action to set the global time scale to 0 and run the layout again, observe that the typewriter text works again.

## Expected result

The typewriter action should take into account the object's timescale.

## More details

**Affected browsers/platforms:** 

Only tested it on Chrome 84.0.4147.135.

**First affected release:** 
Only tested it on R210.2.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed for next release.
