### ISSUE TITLE
Error in Families due to Text and Sprites

### ISSUE THREAD

**Issue by FlippyDolphin** [Scirra/Construct-3-bugs#4149]
After adding Text and 2 sprites (in the form or a health bar) construct 3 crashed and gave an error

## Attach a .c3p

File type not supported?

## Steps to reproduce

1. Create new family
2. Add Text and 2 sprites.
3. Error

## Observed result

Crashed. Saved project and it came back exactly the same before i tried to add the family

## Expected result

Expected to create a family

## More details

Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

Error report information
Type: unhandled rejection
Reason: Error: wrong plugin @ Error: wrong plugin at g.qY (https://editor.construct.net/r210-2/projectResources.js:143:15) at https://editor.construct.net/r210-2/components/bars/projectBar/projectBar.js:57:234
Stack: Error: wrong plugin at g.qY (https://editor.construct.net/r210-2/projectResources.js:143:15) at https://editor.construct.net/r210-2/components/bars/projectBar/projectBar.js:57:234
Construct 3 version: r210.2
URL: https://editor.construct.net/
Date: Tue Aug 25 2020 09:18:50 GMT+1000 (Australian Eastern Standard Time)
Uptime: 61077.1 s

Platform information
Browser: Chrome
Browser version: 84.0.4147.135
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

**Comment by AshleyScirra** [comment]
I can't reproduce this here, it correctly imposes the limitation. No project was provided so I made my own: 
[family-test.zip](https://github.com/Scirra/Construct-3-bugs/files/5122922/family-test.zip)

If I create a new family and then add the Text object to it, all Sprites disappear from the list. This is because it is correctly enforcing the restriction that all objects in a family must be from the same plugin. Therefore it is not possible to complete step 2 in your instructions to add both Text and Sprites to a family.

Please always follow the bug report guidelines, they're specifically intended to avoid this outcome.

**Comment by FlippyDolphin** [comment]
Here
![ARTIOIO](https://user-images.githubusercontent.com/70178995/91164524-7feeb780-e712-11ea-87c5-354d66c11114.png)
![ARtio](https://user-images.githubusercontent.com/70178995/91164528-811fe480-e712-11ea-9b3b-1d50fdf36f75.png)

I couldnt figure out how to share a cp3 file here. but i made a new file, created text and a sprite, and put them into a family

**Comment by FlippyDolphin** [comment]
I could reproduce it in edge as well.
![EDGELORD](https://user-images.githubusercontent.com/70178995/91165397-e6280a00-e713-11ea-957e-ab71b1b6bfb9.png)
![iuseconstructtocopewithmygirlfriendcheatingonmeformybrother](https://user-images.githubusercontent.com/70178995/91165419-ef18db80-e713-11ea-8aab-cfefa6ec3246.png)

**Comment by AshleyScirra** [comment]
I can't find any way to add both a Text and Sprite to a family. Everything I do in the dialog blocks that.

I need to know *exactly* what you're doing, click by click, to do that.

Please file a new issue following all the guidelines, in general we don't monitor closed reports. See the bug report guidelines for more information.
