### ISSUE TITLE
Crash shift+selecting different plugin types when adding to family

### ISSUE THREAD

**Issue by FlippyDolphin** [Scirra/Construct-3-bugs#4152]
Families can include text and sprites when SHIFT is used to select and SPRITES are included first

Still can't figure out how to do this but I'll do you one better!
https://www.youtube.com/watch?v=BwQ1XoNqW6U
(I used onscreen keyboard in the video because it allows you to see when im pressing shift and control.
I also had a bit of trouble using it as I had never used onscreen keyboard or bandicam before)

1. Open blank project
2. Create text and sprite objects
3. Create new family
4. While holding shift select the sprite
5. Still holding shift select the text
6. Create family

## Observed result

Crashed

## Expected result

I expected a family which i could use however according to you guys it wasn't meant to even let me add both

## More details

In the video it is a bit long due to me not knowing how to use bandicam or onscreen keyboard. Originally I did not use either when the issues started happening

Using a HP windows laptop on chrome or microsoft edge (haven't tested others of yet) 

**First affected release:** 

## System details

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
OK, I can reproduce now - the key detail that was missing before is it only happens if you hold shift and click to select a range. It does not reproduce if you hold control and click to multi-select. Thanks for clarifying. (For the record, most bugs are like this, being non-obvious and requiring very specific circumstances, which is why we ask for detailed reports.)

**Comment by FlippyDolphin** [comment]
> OK, I can reproduce now - the key detail that was missing before is it only happens if you hold shift and click to select a range. It does not reproduce if you hold control and click to multi-select. Thanks for clarifying. (For the record, most bugs are like this, being non-obvious and requiring very specific circumstances, which is why we ask for detailed reports.)

I hadnt realized at this point. I only realized when I tried recording it for the video.

Personally I believe that it should be doable to have multiple types in the same family as this allows for set position for stuff like health (which often includes multiple sprites for health bars and text as numbers representing health number) (although I believe this could be done with containers)

**Comment by AshleyScirra** [comment]
Multiple plugin types in the same family is not supported because it creates difficult/nonsensical problems in events. For example what should a 'Set text' action do if run on a Sprite? What should 'Set animation' do if run on a Text object? This all becomes possible if you can put multiple plugins in the same family. Rather than come up with complicated ways to answer those difficult questions, it's just not supported.

**Comment by FlippyDolphin** [comment]
Ah okay. Could this not be solved by only allowing the actions that work on both?

**Comment by AshleyScirra** [comment]
I guess, but it creates more awkward edge cases, like having new restrictions on whether you can add an object type to a family or not depending on whether any of your events reference plugin-specific features (which if we get wrong result in crashes, like in this issue), or whether or not it's actually useful for most users to do so. It's not clear how it would play out, it's pretty complicated. So we tend to focus on a simple subset that definitely works. If you want to suggest new/altered features then we have a voting platform for that anyway: https://construct3.ideas.aha.io/ - although it would be sensible to plan the full implications of the feature and how these edge cases would be handled.

**Comment by AshleyScirra** [comment]
Minimal repro: [families-issue.zip](https://github.com/Scirra/Construct-3-bugs/files/5139005/families-issue.zip)

**Comment by AshleyScirra** [comment]
Fixed for next beta.
