### ISSUE TITLE
Drawing Canvas does not paste object properly when object has 2 or more "Replace Color" effects

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#4154]
## Problem description

When using the Drawing Canvas to paste an object with 2 or more "Replace Color" effects, it seems to paste it at a large offset, if at all. (Note this bug occurs with either "Replace Color" and "Replace Solid Color" effects.)

## Attach a .c3p

[Paste Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5133680/Paste.Bug.zip)

## Steps to reproduce

1. Simply preview the layout and observe the effect.
2. Remove one of the "Replace Color" effects from the sprite object and preview again.

## Observed result

This is the bugged result with 2 or more "Replace Color" effects applied:
![Bugged](https://user-images.githubusercontent.com/36490901/91376842-a9c3df00-e7e3-11ea-8b59-ed7021614235.gif)

## Expected result
This is the intended result with both "Replace Color" effects removed (note that removing only 1 effect works as well)
![NotBugged](https://user-images.githubusercontent.com/36490901/91376853-b3e5dd80-e7e3-11ea-88dc-4d4913a50889.gif)

## More details

**Affected browsers/platforms:** Chrome / Desktop

**First affected release:** This bug has been present for a long time (the last year to my knowledge) but I only recently discovered what exactly caused it.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.47.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.47.3 (like Chrome/84.0.4147.125)
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 784 gb
Storage usage (approx): 239 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Issue #2624 reproduces when using two 'Replace color' effects as well, so I think this is just another variant of that issue.
