### ISSUE TITLE
Gamepad Actions Missing

### ISSUE THREAD

**Issue by PeaceOfCakeGames** [Scirra/Construct-3-bugs#4155]
## Problem description
In the Gamepad documentation, the actions are listed as "none". However, there are two Gamepad actions, which should be listed in the actions. This led me and other people to believe certain features did not exist.

## Steps to reproduce

1. Go to Construct.net>Learn>Documentation>Plugins>Gamepad
2. Scroll to the "Gamepad Actions"

## Observed result
No Gamepad actions are listed.

## Expected result
All of the Gamepad actions (Vibrate and Reset Vibration) should be listed.

**Comment by AshleyScirra** [comment]
Thanks for spotting this, it must've been an oversight when it was added. Updated the manual entry to include the actions: https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/gamepad
