### ISSUE TITLE
Construct Crashes When Creating Family

### ISSUE THREAD

**Issue by 1AL3X** [Scirra/Construct-3-bugs#4157]
When attempting to create a family where the automatic object type sorting kicks in, if I select two objects seperated in the object list by at least one other object, construct crashes.

![Screenshot 2020-08-27 at 5 20 02 PM](https://user-images.githubusercontent.com/24207572/91496227-c0247600-e889-11ea-8070-c446f1f78389.png)

1. In case the screenshot does not render (for witch I apologize, git hub was not allowing me to attatch a .c3p file)
          A. Add (at least) three of any object type and (at least) one of any other object type. I added three progress bars and one sprite.
          B. Rename one of the progress bars so that it is separated from other two in the object list by the sprite (I chose Z).
2. Begin creating a family in the families folder.
3. Add the first (ProgressBar) progress bar to the family.
4. Now that the family creation UI is showing only progress bars, add the other two (ProgressBar2, Z).
5. Press OK

Construct 3 crashed

I expected a created family

Occurs on chrome, unsure about any other browsers, sorry.

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: incompatible plugin
Stack: Error at Function.d.ASa (https://editor.construct.net/r210-2/main.js:288:242) at Lb (https://editor.construct.net/r210-2/main.js:201:29) at window.assert (https://editor.construct.net/r210-2/main.js:201:330) at d.f.G.kDd.t7b (https://editor.construct.net/r210-2/projectResources.js:2102:400) at HTMLButtonElement.MQ.onclick (https://editor.construct.net/r210-2/projectResources.js:2098:472)
Construct 3 version: r210.2
URL: https://editor.construct.net/
Date: Thu Aug 27 2020 17:29:00 GMT-0400 (Eastern Daylight Time)
Uptime: 775.4 s

Platform information
Browser: Chrome
Browser version: 84.0.4147.110
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Chrome OS
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 13099.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.110 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 515 (SKL GT2)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by 1AL3X** [comment]
Just realized I for got to specify this, step 4 should be say to select both and add them together

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines (in particular, attach a project file), otherwise it's impossible to help with your report. The bug report guidelines emphasise this - we need the requested information to be able to do anything.
