### ISSUE TITLE
Construct Crashes While Creating Family

### ISSUE THREAD

**Issue by 1AL3X** [Scirra/Construct-3-bugs#4158]
## Problem description

 

When creating a family, if I select (at least) one of any object type, then select any two others of the same object type that are separated by (at least) one object of a different type and try to create a the family, construct crashes

## Attach a .c3p

[Bug Report.zip](https://github.com/Scirra/Construct-3-bugs/files/5139026/Bug.Report.zip)

## Steps to reproduce

1. begin creating a family
2. select the first of (at least) 3 of an object type (in this case, ProgressBar) and add it to the family
3. select the other (at least) 2 of the same family (in this case, ProgressBar2 and Z) and add them to the family together. If, in the objects folder, they are separated by (at least) one object of another type, construct should crash

## Observed result

Construct crashed

## Expected result

A new family

## More details

**Affected Browsers/Platforms:** 

I've only tested on Chrome, sorry

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: incompatible plugin
Stack: Error at Function.d.ASa (https://editor.construct.net/r210-2/main.js:288:242) at Lb (https://editor.construct.net/r210-2/main.js:201:29) at window.assert (https://editor.construct.net/r210-2/main.js:201:330) at d.f.G.kDd.t7b (https://editor.construct.net/r210-2/projectResources.js:2102:400) at HTMLButtonElement.MQ.onclick (https://editor.construct.net/r210-2/projectResources.js:2098:472)
Construct 3 version: r210.2
URL: https://editor.construct.net/
Date: Thu Aug 27 2020 18:31:46 GMT-0400 (Eastern Daylight Time)
Uptime: 208.7 s

Platform information
Browser: Chrome
Browser version: 84.0.4147.110
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Chrome OS
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 13099.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.110 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 515 (SKL GT2)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I'm not sure how to follow your steps to reproduce. Step 2 appears to say to select 3 object types. Step 3 appears to say to select 2 more object types, totalling 5. But the attached project only has 4 object types. Are these steps correct? I can't see how to follow them.

Are you holding shift+selecting by any chance? If so that would be the same as issue #4152.

**Comment by 1AL3X** [comment]
I intended to say select the first object type from a set of at least three, sorry. It does involve shift clicking in what I beleive may be a related bug, but with this the issue occurs when you select multiple object types (say, progress bars) from the " 'Project Bars' object types in project " and you  shift click to select two that are on either side of at least one object of a different type. Then, when creating the family, construct crashes.

**Comment by 1AL3X** [comment]
![Screenshot 2020-08-27 at 10 36 36 PM](https://user-images.githubusercontent.com/24207572/91514846-d0524a80-e8b5-11ea-9663-6bbccf5f6a78.png)

Should look like this after step 2 (Selecting either of the unnamed progress bars works), and for step 3 you shift click to add both the other two, which (to my understanding) is different from #4152 because you would be selecting two of the same object type rather than two different types.

**Comment by AshleyScirra** [comment]
I think it's a variant of #4152 and should be fixed in the next release. I'm still not 100% clear on the steps here so marking this to check again when the next release is out.

**Comment by AshleyScirra** [comment]
@1AL3X - can you verify this is now working in r214?

**Comment by 1AL3X** [comment]
Just checked, it no longer crashes.

**Comment by AshleyScirra** [comment]
Great, thanks for confirming.
