### ISSUE TITLE
Crash when move text input outside scope

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#416]
Crash when move action on text input with local variable outside scope

1. Open .cp3 file attached
2. Move action in Function B to Function A (or elsewhere outside scope)

[move-text-input-local-variable.zip](https://github.com/Scirra/Construct-3-bugs/files/1045774/move-text-input-local-variable.zip)

**Comment by sebastien-c3** [comment]
NB: Crash with copy/paste too.

**Comment by sebastien-c3** [comment]
JFYI: Several other crashes move outside scope bugs since this post, sorry I don't have noted them yet...

**Comment by AshleyScirra** [comment]
Yep I think since r33 due to some refactoring any invalid move will crash instead of an error. Looking in to it now, should be able to fix for r34.

**Comment by sebastien-c3** [comment]
Great! Fortunately I save very very very often ...

Wait a minute... Save? CTRL+S?! Like CTRL?!
OMG: It was that, we found another...

**Comment by AshleyScirra** [comment]
Okay, think this should all be covered in r34...
