### ISSUE TITLE
Portrait photos (taken by Pixel3aXL) can't load correctly

### ISSUE THREAD

**Issue by amaebiJP** [Scirra/Construct-3-bugs#4160]
## Problem description
Hi, Recently I changed my smart phone to Pixel3aXL.
Then, I found portrait photos that taken by Pixel3aXL can't load correctly using "Sprite.LoadImage".
(It happen just portrait photos, not happen landscape photos)

## Attach a .c3p
Here is an example project i used.
[ImageLoadTest.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5144808/ImageLoadTest.c3p.zip)

## Steps to reproduce
Here are 2photos taken by Pixel3aXL.
![IMG_20200828_193928](https://user-images.githubusercontent.com/6070887/91629510-a491aa80-ea04-11ea-9a7a-f1a3d7b1d11b.jpg)
![IMG_20200828_193925](https://user-images.githubusercontent.com/6070887/91629516-afe4d600-ea04-11ea-842c-64adc73e524a.jpg)

1. Run applicaton I attached.
2. Press file chooser button.
3. Select portrait photo attached above.
   ( If you select landscape photo, this problem not cause)

## Observed result
When I load portrait photo on Android(Chrome), sprite image seems broken.
<img width="686" alt="スクリーンショット 2020-08-29 0 32 06" src="https://user-images.githubusercontent.com/6070887/91629694-246c4480-ea06-11ea-92f9-ff0e17ac67aa.png">

When I load portrait photo on Mac(Chrome), the web application is shutting down!

## Expected result
Load image correctly.

## More details
It caused only photos that taken by Pixel3aXL, I test it with Pixel3aXL(Chrome, Android10), MacbookAir(Chrome, MacOSCatalina)

Broke in r210.2.

**Comment by AshleyScirra** [comment]
I can reproduce a tab crash in Chrome on Windows 10 (but only with the portrait photo).

Tab crashes mean Chrome has crashed, not Construct. It also seems to work fine in Firefox, which is further evidence it's a Chrome bug. You'll need to file this with Google at crbug.com to have it investigated.

**Comment by amaebiJP** [comment]
I reported this bug to crbug.com. Issue number is 1125337.

**Comment by AshleyScirra** [comment]
Thanks, I starred that issue and will keep an eye on it.
