### ISSUE TITLE
Event sheet loses focus if the search bar or search results are opened

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4161]
## Problem description

If the search/result bar is opened, after every event edit/change the focus on the event sheet is lost.
Also selecting an event from the list, will go to it, but not focus on it. (i.e keyboard shortcuts not working)

## Attach a .c3p

This is not c3p related, but an editor bug which happens on all files both in the web and NWjs versions of C3.

## Steps to reproduce

1. Search for any text on the event sheet.
2. Double click the result to show it in the event sheet, try to use keyboard shortcuts (arrows, enter), the focus remains on search bar.
3. Manually click on the event on the event sheet to select and edit it, then save or cancel.
4. Try any keyboard shortcuts, focus lost again (but not to the search bar, no idea where it goes).

## Observed result

Focus on event sheet is lost if search/result bar is opened.

## Expected result

Focus should remain on the last selected window between edits, regardless of any pop ups (it might also happens with other windows).

## More details

**Affected browsers/platforms:** Chrome, NWjs

**First affected release:** Can't tell exactly when it started, at the very least since march 2020.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Updated the next release to transfer focus to the event sheet view when navigating to a find result.
