### ISSUE TITLE
Tilemap - Can't draw tiles

### ISSUE THREAD

**Issue by AlonDan** [Scirra/Construct-3-bugs#4162]
## Using the Desktop version Stable or Beta (latest version + latest NW.js version up to date)
It's impossible to draw tiles on the tilemap object using the pencil.

## Steps to reproduce

1 - Create a Tilemap object
2 - Import an image file (I used PNG) with 16x16 grid
3 - Set the Grid on the Tilemap to 16x16
4 - Select the tile piece you like to draw and the Pencil tool 
5 - Try to draw on the Tilemap object...  it's not working.

## Observed result

Instead of showing the selected tilemap piece, it shows the default mouse arrow sign.
While clicking on the tilemap object with the pencil tool, it won't create anything.

## Expected result
It should show the selected tilemap piece as the mouse cursor once it's selected from the tilemap image area and allow to draw it over the tilemap object.

## More details
There is no reason to add C3 file, since I tried it on NEW clean projects and it works fine on the broswer (chrome) but not on the latest desktop built both: stable and beta.

**First affected release:** 
Unfortunately I just started using C3 after a long time so I only tested it on the latest versions,
It's broke on versions: **r210.2** stable and : **r213** beta 

## System details
<details><summary>View details</summary>
Platform information
Browser: NW.js
Browser version: 0.48.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.48.0 (like Chrome/85.0.4183.83)
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 72 gb
Storage usage (approx): 280 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Can't reproduce this with the steps provided.

Can you reproduce the problem from opening a blank project? That is what I am doing, and it looks like it is working properly.

**Comment by AshleyScirra** [comment]
No response for 2 weeks so closing.
