### ISSUE TITLE
Tile Movement+Bound To Layout causes sprite to get stuck on edge

### ISSUE THREAD

**Issue by ccalima** [Scirra/Construct-3-bugs#4166]
## Problem description

If you assign both Tile Movement and Bound To Layout as behaviors for a sprite and try to move the sprite past the edge of the layout (just moving to the tile next to the edge is fine - it's when you try to move again past the edge that the problem happens), the sprite will get stuck there and arrow keys will no longer move it.

## Attach a .c3p

[tile movement bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5148123/tile.movement.bug.zip)

## Steps to reproduce

1. Preview the .c3p and hold Up Arrow/Left Arrow until the sprite reaches the edge of the screen. Keep holding it down as if trying to move past the edge.
2. Press arrow keys to move the sprite in any other direction.

## Observed result

The sprite doesn't move/the arrow keys no longer work, and the sprite is now stuck in place.

## Expected result

The sprite should be able to move when you press arrow keys.

## More details

This only happens when you attempt to move past the edge at least once. If the sprite stops just short of the edge, it won't get stuck (so if you move along the grid tile by tile and stop next to the edge, it works fine - it's only if you try to continue moving toward the edge that the issue happens).

This seems to be exclusive to tile movement; I didn't get the same issue with 8-way movement. The issue is also present in isometric mode but presents a bit differently (the character would glide along the top edge, but it got stuck when it reached the left edge).

**Affected browsers/platforms:** Tested on Firefox and Chrome.

**First affected release:** I just started using Construct 3 today, so I can't say if it worked before. Current stable release and current beta both have the issue.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 80.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0
C3 release: r210.2 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 1 gb
Storage usage (approx): 301 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a really difficult problem. Both behaviors are working correctly but conflicting with each other.

The Tile movement uses an algorithm that basically says "keep moving a bit further until you reach the destination tile, then stop". The Bound to Layout behavior moves the object back inside the layout if it's outside. So when you try to move with the tile movement outside the layout, the tile movement gets stuck in moving state forever: it moves a bit further towards its target, then bound to layout moves it back, then the next frame it tries to move again, then bound to layout moves it back, and so on forever.

I can't think of a good way to solve this. As I said both behaviors are working as designed, but the way they work conflicts.

A simple workaround would be to surround the layout with solid objects instead of using the bound to layout behavior.

**Comment by AshleyScirra** [comment]
OK, I added a heuristic for the next release to detect if the Tile movement is blocked by outside factors, such as the Bound to Layout behavior. In this case it will reverse the direction of movement and go back to the previous tile. Hopefully this kind of detection won't break anything else...
