### ISSUE TITLE
Load image from URL not picking the correct instance - Stable r210.2

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-3-bugs#4167]
## Problem description

When loading an image from an URL using the sprite plugin construct doesn't pick the correct instance to update the image, instead, it picks all the instances of the same plugin overwriting the texture.

## Attach a .c3p
[imageUrlTest.zip](https://github.com/Scirra/Construct-3-bugs/files/5150774/imageUrlTest.zip)

## Steps to reproduce

1. Open the attached file and run the project
2. The project will try to update only one instance of the plugin using Load Image from URL by picking just one instance
3. The project changes the texture for all the objects, not only the instance intended.

## Observed result

Sprite instance is not picked correctly.

## Expected result

Should only affect one instance of the object, not all the objects.

## More details

Construct r210.2

**Affected browsers/platforms:** 

Chrome

Construct r210.2

## System details

<details><summary>View details</summary>

NA

</details>

**Comment by layilpaht** [comment]
I also faced the same issue
Load the image in different frame (in advance make many frames as per requirement)

**Comment by sotano42** [comment]
> I also faced the same issue
> Load the image in different frame (in advance make many frames as per requirement)

I know that works but the problem remains. I use to create lots of objects dynamically to simplify some parts of the game. For instance, on a leaderboard, I want to create the list of players dynamically, therefore I need each sprite to have its own "picture" of the player. Creating many sprites will just make it less flexible when more players are added to the leaderboard.

**Comment by layilpaht** [comment]
> > I also faced the same issue
> > Load the image in different frame (in advance make many frames as per requirement)
> 
> I know that works but the problem remains. I use to create lots of objects dynamically to simplify some parts of the game. For instance, on a leaderboard, I want to create the list of players dynamically, therefore I need each sprite to have its own "picture" of the player. Creating several sprites statically will just make it less flexible when more players are added to the leaderboard.

1.) Create an object through code
2.) Select a frame through code
3.) Assign an image to it

**Comment by AshleyScirra** [comment]
This is currently by design. All instances share the same set of images, so when you replace an image, it updates all instances regardless of picking.

**Comment by sotano42** [comment]
> > > I also faced the same issue
> > > Load the image in different frame (in advance make many frames as per requirement)
> > 
> > 
> > I know that works but the problem remains. I use to create lots of objects dynamically to simplify some parts of the game. For instance, on a leaderboard, I want to create the list of players dynamically, therefore I need each sprite to have its own "picture" of the player. Creating several sprites statically will just make it less flexible when more players are added to the leaderboard.
> 
> 1.) Create an object through code
> 2.) Select a frame through code
> 3.) Assign an image to it

ty, I'll work around with this...
