### ISSUE TITLE
Desktop Built: Lags / Slow Performance

### ISSUE THREAD

**Issue by AlonDan** [Scirra/Construct-3-bugs#4168]
## Problem description
I've noticed that my player is lagging (milliseconds of stops while moving) so I tried C3 debug first and I noticed that the FPS are lower and not always stable.
When I tried it on Chrome and the FPS are pretty stable and no lagging at all but I can't stand using a browser for C3, that's why I share this.

I prefer using the Desktop built and not the browser:
The main problem is that there are lagging (stops every X milliseconds) while in Chrome browser it is smooth, no lagging, and FPS are more stable.

## Attach a .c3p
Nothing specific, the same happens on any project on the Desktop built.

## Steps to reproduce

1. Run ANY project in Desktop built, for example: Simple platformer movement on floor.
2. Check the FPS while moving from left to right.
3. There will be lags (stops) and lower FPS in general compare to Chrome browser.

## Observed result

Mini stops / lagging and lower FPS compare to Chrome browser.

## Expected result
Same as Chrome browser, means: Smooth, no lagging.

I expected to have the same performances on the Desktop built as the Browser, smooth FPS without lagging.

## More details

**Affected browsers/platforms:** 
Windows 10 64-bit: Desktop built (latest version)

 I started to use C3 after a while, Since I only used the latest version of Desktop Built and NW.js  I can't compare to anything older and can't tell if the issue is C3 Desktop built or NW.js

**First affected release:** 
Can't say if it worked before since I didn't use older version.
Broke in r210.2 stable (same in Beta r213)

## Visual Demonstration of the Issue
Desktop Built:
![C3 - Test - Desktop](https://user-images.githubusercontent.com/21152334/91737730-2249e780-ebb8-11ea-9b5f-e89f9984cf18.gif)

Chrome Browser:
![C3 - Test - Chrome](https://user-images.githubusercontent.com/21152334/91737763-2e35a980-ebb8-11ea-86d0-878f9a6cf8d7.gif)

Notice:
This is just one of any experiments I did before reporting the issue, This is the reason why I didn't attach .c3 file, the issue appears on ANY project.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.48.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.48.0 (like Chrome/85.0.4183.83)
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 280 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I can't reproduce this here, it works just fine - I get exactly the same framerate in Chrome as in both the NW.js editor and after an NW.js export. (On this system, that's 60 FPS.)

Besides, if it works in Chrome, that means Construct is working correctly and the problem is probably with NW.js instead, so there is nothing we could do about it ourselves directly anyway. But it works fine for me, and NW.js uses an identical browser engine to Chrome, so I can't think of any reason there would be any difference between them.

Why not just use the browser anyway? If you install the web app it will look and work pretty much identically to the NW.js app. And we are trying to point people in that direction in part to avoid these occasional weird and sometimes unexplainable problems that come up with NW.js.

**Comment by AlonDan** [comment]
Thanks for the reply Ashley, 
I just tried it earlier on a different PC  (lenovo laptop i7 16GB and SSD) and I had the same result, so I think you got a point, maybe it's the latest NW.js after all, but I had to share it here because I'm not technical so I'm glad you explained it.

Sorry about my bad English, let me try to explain:

**Why I'm not using browser:**
I can't stand working on my browser and need to cancel every-time my many usable extensions, pop-ups, notifications and whatever bothers me.
Also, I really LOVE the clean look of the Desktop Built, I mean yeah it's a NW.js wrapper but the UI have no chrome extensions that I use, no extra tabs while browsing, no tools and icons and what so ever (I'm a heavy chrome user with many tools so I can't just get rid of them).

The Desktop built is a dedicated application after all (wrapped browser of course) but stand alone window, it have nothing to do with my chrome browser or anything else, it's running it's own NW.js, it's (usually beside that FPS issue I'm having) but it's usually fast and most of all CLEAN UI with bigger space like most apps.
So I don't need to use "Full Screen" (F11) to enable/disable every time I need to check my email or my other tabs / tasks I do on the background, I just have it there, just like any other application I use on windows which is GREAT! I believe that this is the reason why the Desktop Built users like it so much.

**Conclusion:**
TBH - If there was no **Desktop Built** I wouldn't use C3 at all, I don't like any application that is browser-based (again, I understand that it IS a wrapped browser but I mean Stand-Alone).

I hope that you guys won't stop releasing the Desktop Built in the future because it's really MUCH better workspace compare to a busy-browser as I explained, and it's the only reason for me to use C3.

Unless you're planning a native (exe) standalone that is not NW.js / Browser based, just like most game engines, that will be BRILLIANT! but I guess this is not the marketing-wise direction you are interested in as a company and I respect that but.. a user can keep dreaming, right? ;)

**Most Important:**
Thank you Ashley and rest of the team for keep making Construct 3 AMAZING!
please keep up the good work :)

**Comment by AshleyScirra** [comment]
But you get exactly the same clean UI when you install the web app in Chrome. It looks nearly identical - no tabs, no address bar etc. So you don't need the desktop app for a clean UI.
