### ISSUE TITLE
Global Layers do not maintain object states - Stable r210.2

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-3-bugs#4169]
## Problem description

When using global layers, construct no longer keeps the state of the objects. If you create objects dinamically on a global layer, they simply disappear after transitioning to another layer

## Attach a .c3p
[GlobalLayer.zip](https://github.com/Scirra/Construct-3-bugs/files/5151173/GlobalLayer.zip)

## Steps to reproduce

Attached file has a "Transition" layer to place a pink texture while changing between layouts, the first scenario is just changing from layout 1 to layout 2 showing the "transition" and keeping it visible in the global layer.

Scenario 1 - Static object with attributes change

1. Run attached project
2. Press "Goto Layout 2"
3. Pink tilemap will be shown, then it changes to layout 2.
4. Tilemap is reset to its original state on the layer, not respecting the fact that now it was set "visible"

Scenario 2 - Creating objects dynamically in the global layer
1. Run attached project
2. Press "Create Object" 
3. Press "Goto Layout 2"
4. Objects are destroyed, even though they were created on the global layer and are expected to remain after changing the layout.

## Observed result

Objects in the global layer are destroyed always an reset to its original state, instead of respecting the new state.

## Expected result

Objects in the global layer must keep their state.

## More details

**Affected browsers/platforms:** 

Chrome

**First affected release:** 

Construct r210.2

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Global layers are an editor feature, not a runtime feature, so it's not correct to expect them to change the way things work at runtime. See the description of [global layers in the manual](https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/layers) for more details.
