### ISSUE TITLE
issue with remembering local file path location

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4170]
## Problem description

If i open .c3p file and next time i want to open another file then it remember last location.
If i insert sound files then it remembers last location for sound file too. 
but problem is now if i again open file (construct file) it show sound file location instead of .c3p file location and once i opened .c3p file and import sound it keep remember sound file location but it will again show sound location if i open .c3p file next time.

## Attach a .c3p
no file need

## Steps to reproduce

1. On "start page" click "open" and select any .c3p file from your pc.
2. close the file and again click "open" in "start page".
3. check if the location is same as file opened in step 1.
4. open any file.
5. Import any sound from different location.
6. close project now.
7. click "open" in "start page".
8. check if the location is same as file opened in step 4 (Here it shows location of sound folder).
9. open any file.
10. insert sound (Here location of sound is same as we inserted in step 5).

here my point is if construct can remember sound file type path location even after we open .c3p file then it should also remember .c3p file type location even after we import any sound. 

## Observed result

construct forget file path location for .c3p file but it remembers location for sound file type.

## Expected result

for each file type it should remember its path location.

## More details

**Affected browsers/platforms:** 
Chrome / Desktop

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid currently Construct has no control over the initial directory of any prompts. These are controlled by the browser and AFAIK no API exists that can influence the initial state.

If any such features are added, we can add them to improve the usability of these dialogs, but until then there is nothing we can do.
