### ISSUE TITLE
Scene graph - selecting parent/child does not select container

### ISSUE THREAD

**Issue by simstratic** [Scirra/Construct-3-bugs#4171]
## Problem description

Picking a Parent/Child using Hierarchy Events in r230 beta, does not pick other Objects that are in a container with the picked Parent/Child.

## Attach a .c3p

https://drive.google.com/file/d/1GGJ917O6nunr9OLcFEQLrdNWVAE3YrPV/view?usp=sharing

## Steps to reproduce

1. Left click green square.
2.
3.

## Observed result

Green square is child of one red square. Black square is in container with red square. Black square has flash behavior for illustration. Clicking the green square selects the Parent red square instance, but causes ALL black squares to flash, not only the instance in container with Parent.

## Expected result

Only the one black square instance in container with the Parent red square instance should flash.

## More details

Clicking the blue square demonstrates the expected result. Blue square is also a child of red square. However it includes a work-around: after picking Parent, it has a sub-event to make the Parent pick itself using UID, which then picks the container.

**Affected browsers/platforms:** 
Tested with Windows 10/Edge Chromium, Android 10/Chrome

**First affected release:** 
r230 beta
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, good catch, fixed for next release.
