### ISSUE TITLE
Event sheet loses focus after edit action/condition, if the search bar or search results are opened

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4173]
## Problem description

If the search/result bar is opened, after every event edit/change the focus on the event sheet is lost.

## Attach a .c3p

https://github.com/Scirra/Construct-3-bugs/issues/4161
The first part of the bug was fixed, double clicking put the focus on the event, but after you edit it the focus is lost again (try going up/down to next/previous action/condition, or press enter to edit it again.

This is not c3p related, but an editor bug which happens on all files both in the web and NWjs versions of C3.

## Steps to reproduce

1. Search for any text on the event sheet.
2. Edit the event.
3. Try to use keyboard shortcuts to navigate the event sheet.

## Observed result

Focus on event sheet is lost after editing any event if search/result bar is opened.

## Expected result

Focus should remain on the last selected window between edits, regardless of any pop ups (it might also happens with other windows).

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by avishaymizrav** [comment]
@AshleyScirra This bug seems to happen with any undocked window, focus on event sheet is lost after every edit.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release. It was just restoring focus to the topmost window, which could be any undocked pane. It now stores a history of the last active windows and makes sure it restores the previous one when a dialog or any other window closes. This keeps keyboard focus in the event sheet view in your example.
