### ISSUE TITLE
Plugin Canvas (Set angle doesn't work correctly)

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#4175]
r214 canvas plugin does not display inserted objects correctly when rotated. I attached a video and a project to describe the problem. in r200, set angle worked correctly.

https://drive.google.com/file/d/1JefwjxtIRsgym7kVQB5Asz9zLJ7sqUy2/view?usp=sharing

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please provide a minimal project and steps to reproduce as per the bug report guidelines.

**Comment by ibiz3091** [comment]
I provided a project and a video of how it should work correctly when rotating 
Here is a link to the project:
https://drive.google.com/file/d/1JefwjxtIRsgym7kVQB5Asz9zLJ7sqUy2/view?usp=sharing

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. Videos are not normally helpful and we need a minimal project.

**Comment by ibiz3091** [comment]
@AshleyScirra  is the link to the project: https://drive.google.com/file/d/1U3K3h1kGJA7KclZb-iaArRz95jfGFrxx/view?usp=sharing

**Comment by AshleyScirra** [comment]
That is not a minimal project. Please see the bug report guidelines.
