### ISSUE TITLE
Trigger once does not properly function with for each 

### ISSUE THREAD

**Issue by 1AL3X** [Scirra/Construct-3-bugs#4176]
## Problem description

If I use the for each command with the trigger once command, it triggers once for the first object, but still triggers continuously for the other objects of the same type.

## Attach a .c3p

[Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5162588/Bug.zip)

## Steps to reproduce

1. Run the project in debug mode (In order to observe the value of C)

## Observed result

C is increasing once per tic, If there is only one text object, it only increases once.

## Expected result

I expected it to increase twice.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by avishaymizrav** [comment]
You need to put the trigger once before the for each.

**Comment by 1AL3X** [comment]
Thanks. Are there any other similar cases where the trigger once goes before the condition?

**Comment by avishaymizrav** [comment]
I think any event that does picking or going through an array of instances will need the trigger once before it.
I don't remember all the conditions by heart, there are way too many of them, just try it out.

**Comment by 1AL3X** [comment]
Cool
