### ISSUE TITLE
Resize object on layout problem

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#418]
It continues to happen randomly (no key down).
It's not linked to a specific file or project...

Sorry Ashley, it's frequent and I really don't know how it occurs. But I think it's perhaps a lost or recalculate coords/object points after focus and come back from another window/GUI element (in C3 or not). Or something like that... See the new gif in action (black magic inside ^^).

http://spinof.com/support/c3/resize-object-problem.gif

**Comment by AshleyScirra** [comment]
Sorry, there's nothing we can do without steps to reproduce. We can't debug gifs. And as before, this is the intended behavior in some circumstances, so without steps to reproduce we can't tell if it's meant to be like that or not.

**Comment by sebastien-c3** [comment]
Ok I understand Ashley but it happens with new or not project (empty or not, since the beginning of the beta), it's why I can't send a project file.

It appears and it disappears, and it's not the normal behavior, cause when all is right, objects are normally resized (if I close and reopen layout, this strange behavior return to normal).

Can't reproduce it since (trying, trying) but it continues to happen sometimes and randomly with no reason, I'm pretty sure I'm not the only one with that. Perhaps because I'm on a dual screen too with different resolutions and I switch from one window to another for previews and other stuff, I don't know.

Sorry for not being able to bring more informations for now,
If I find something wich trigger it, I post a detailed step by step.
