### ISSUE TITLE
minify crash browser . Release R210.2

### ISSUE THREAD

**Issue by ManuelSanMatin** [Scirra/Construct-3-bugs#4180]
To build whit C2runtime and minify crash. in my project have addons that work only with C2 runtime
Release R210.2

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to do anything about reports like this. Please see the bug report guidelines, we need that information to help you.
