### ISSUE TITLE
Crash while "Reload from original source"

### ISSUE THREAD

**Issue by MihaMS** [Scirra/Construct-3-bugs#4183]
## Problem description
Using Construct 3 standalone (for using "Reload from original source" functionality):
1. In a test case C3 crashes when pressing this button
2. In a work project it reload sprite (and sprite animations) not from sources but from last saved state

[C3_testCase.zip](https://github.com/Scirra/Construct-3-bugs/files/5178540/C3_testCase.zip)

Update: in a web-version of Construct 3 (if enable experimental features to get access to save files locally to a folder) get same error and crash ((

## Steps to reproduce

1. Start C3 standalone and create a new project
2. Create Sprite object and load any png image by "Load an image from a file", close sprite editor
3. Save project as "Save as project folder" to get access to "Reload from original source" functionality
4. Open again created sprite in editor, press "Reload from original source"

## Observed result

Construct 3 crashed.

## Expected result

Image updated with proper image.

## More details
"Reload from original source" - is crucial for my project with a lot of graphics! Before this function works fine (even while project saved as a single file), now it only available when project saved as a folder... And even now it doesn't work properly(( I spend more than a year working on my project and now I stopped because of this!((
Construct 3 version r210.2 stable
NodeWebkit nwjs-sdk-v0.48.0-win-x64
Windows 10

Error report information
Type: unhandled rejection
Reason: Error: empty path @ Error: empty path at Object.d.Ol.Qdb (https://editor.construct.net/r210-2/main.js:544:217) at Object.d.Ol.Szc (https://editor.construct.net/r210-2/main.js:547:198) at e.z2.xsa (https://editor.construct.net/r210-2/projectResources.js:1468:449) at Function.tl (https://editor.construct.net/r210-2/projectResources.js:1955:427) at e.z2.tl (https://editor.construct.net/r210-2/projectResources.js:1467:396) at e.z2.Alb (https://editor.construct.net/r210-2/projectResources.js:1423:288) at e.z2.Qs (https://editor.construct.net/r210-2/projectResources.js:1420:207) at e.z2.Ck (https://editor.construct.net/r210-2/projectResources.js:1467:169) at e.z2.B2c (https://editor.construct.net/r210-2/projectResources.js:1420:492) at e.z2.kq (https://editor.construct.net/r210-2/projectResources.js:1420:6)
Stack: Error: empty path at Object.d.Ol.Qdb (https://editor.construct.net/r210-2/main.js:544:217) at Object.d.Ol.Szc (https://editor.construct.net/r210-2/main.js:547:198) at e.z2.xsa (https://editor.construct.net/r210-2/projectResources.js:1468:449) at Function.tl (https://editor.construct.net/r210-2/projectResources.js:1955:427) at e.z2.tl (https://editor.construct.net/r210-2/projectResources.js:1467:396) at e.z2.Alb (https://editor.construct.net/r210-2/projectResources.js:1423:288) at e.z2.Qs (https://editor.construct.net/r210-2/projectResources.js:1420:207) at e.z2.Ck (https://editor.construct.net/r210-2/projectResources.js:1467:169) at e.z2.B2c (https://editor.construct.net/r210-2/projectResources.js:1420:492) at e.z2.kq (https://editor.construct.net/r210-2/projectResources.js:1420:6)
Construct 3 version: r210.2
URL: https://editor.construct.net/
Date: Sat Sep 05 2020 21:24:12 GMT+0200 (Eastern European Standard Time)
Uptime: 60 s

Platform information
Browser: NW.js
Browser version: 0.48.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.48.0 (like Chrome/85.0.4183.83)
C3 release: r210.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

**Comment by MihaMS** [comment]
Update: in a web-version of Construct 3 (if enable experimental features to get access to save files locally to a folder) get same error and crash ((

**Comment by AshleyScirra** [comment]
Reopening as this needs a different fix

**Comment by DiegoScirra** [comment]
Should be ok now.

**Comment by MihaMS** [comment]
Hello!
Updated Construct to a new version (r218) and - yes crash is gone, but when I press "Reload from original source" - sprite is not updates... :(
It looks like Construct updates it not form Original source but from it's last saved state.

**Comment by AshleyScirra** [comment]
Please file a new issue following all the guidelines. Comments on closed issues won't be investigated.
