### ISSUE TITLE
Pathfinding Obstacle Map Load Bug

### ISSUE THREAD

**Issue by Lowcanrihl** [Scirra/Construct-3-bugs#4184]
## Problem description

 It's quite complicated, but under a series of conditions outlined within the cp3 file the regenerate obstacle map region will not work.

## Attach a .c3p

[ObstacleMapFamilyLoadBug.zip](https://github.com/Scirra/Construct-3-bugs/files/5178619/ObstacleMapFamilyLoadBug.zip)

## Steps to reproduce

1. Just click play in the cp3 file and the instructions within the text objects tell you what to do. 
2. The comments in the event sheet show what can be done to make the project work.
3.

## Observed result

 Pathfinding does not work in layout 2.

## Expected result

 Pathfinding should work in all layouts without having to disable certain events.

## More details
 I have been using the desktop version, but I just tested it in the chrome browser version of construct 3 and it doesn't work there either.

**Affected browsers/platforms:** 

Not sure.

**First affected release:**  Not sure.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.48.1
Browser engine: Chromium
Browser architecture: 32-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.48.1 (like Chrome/85.0.4183.83)
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 38 gb
Storage usage (approx): 375 mb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks like the 'regenerate' actions never get marked complete if you pass an invalid or empty area for the region. This means it's getting stuck in 'Wait for previous actions to complete', since it's never marking the regenerate action as complete. It should be fixed for the next release.
