### ISSUE TITLE
crash at build whit minify

### ISSUE THREAD

**Issue by ManuelSanMatin** [Scirra/Construct-3-bugs#4186]
[minify_test17.zip](https://github.com/Scirra/Construct-3-bugs/files/5179890/minify_test17.zip)

## Problem description
crash at build whit minify and runtime2,the problem is whit tilemap

## Attach a .c3p

ready. Zip

## Steps to reproduce

step1: open the project
step2: change to Runtime2
step:3: build whit minify , cordova for Android or Ios

## More details

 
ALL , Chrome, explorer, firefox and brave

**Affected browsers/platforms:** 

r210.2

**First affected release:**  
I'm not sure

## System details

Platform information
Browser: Chrome
Browser version: 85.0.4183.83
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 67 gb
Storage usage (approx): 242 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

It took me a long time trying to debug the project to find the error. with the tilemap.
[minify_test17.zip](https://github.com/Scirra/Construct-3-bugs/files/5179901/minify_test17.zip)

</details>

**Comment by AshleyScirra** [comment]
What actually happens? You left "Observed result" empty so I don't know what you saw, and just saying "crash" is vague and could mean many things. I can reproduce a tab crash in Chrome only, showing `STATUS_BREAKPOINT` (no idea why!). It works fine in Firefox. Tab crashes are normally browser bugs, and it works for me in Firefox, which is strong evidence this is a problem with Chrome. If you want it investigated further report it to Google at crbug.com. The C2 runtime is being retired in July BTW, so we won't be doing further maintenance or updates on it ourselves, I'd strongly advise to do whatever it takes to switch to the C3 runtime ASAP.
