### ISSUE TITLE
Cannot open a folder-based project.

### ISSUE THREAD

**Issue by loicmorvan** [Scirra/Construct-3-bugs#4188]
## Problem description

The option "Open a folder-based project." is no more available since today.
All my projects are unusable :'(

## Attach a .c3p

No c3p.

## Steps to reproduce

1. Open Construct 3
2. Try to open a folder based project

## Observed result

The option "Open folder based project" is not available.

## Expected result

The option "Open folder based project" is available and I'm able to open my projects (they are versioned in git repositories).

## More details

Construct 3: Release r210.2 stable with option "Enable experimental features" checked
Chrome on macOS: Version 85.0.4183.83 (Official Build) (64-bit)
macOS: 10.15.6 (19G2021)

## System details

None

**Comment by AshleyScirra** [comment]
Due to the way Google's origin trial experiments work, they periodically expire and we have to renew them. Clear your browser cache and reload C3 and it should start working again, or use the latest beta. Once the feature is fully released we won't have to use an origin trial so this won't happen.

**Comment by loicmorvan** [comment]
It did work, thanks a lot!

**Comment by Davikin** [comment]
This problem is happening again. I tried deleting the cache and even switched to the latest Construct version (r218). Then I saw that Chrome just updated to v85, so I guess it has to do with the origin trial issue.

**Comment by AshleyScirra** [comment]
Please see [this post](https://www.construct.net/en/forum/construct-3/general-discussion-7/local-file-folder-saves-chrome-147071/page-5#forumPost1023910).

**Comment by JoseDinis1** [comment]
How can i open a project made in version 204 (itrs a folder), made in a few months ago?
Version 204, doent have the open folder option
Version 225, says isnt a valid folder
Version 229, says isnt a valid folder

Thanks
