### ISSUE TITLE
F5 preview key doesn't work when tilemap selected

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#419]
Finally found when this other one happens (by trying reproduce "object resize on layout problem")

1. Select a tilemap on a layout
2. Try to preview project with F5 key
3. Nothing happens (preview doesn't work)
4. Unselect the tilemap and press again F5: preview works

**Comment by sebastien-c3** [comment]
NB: Happens also when a tilemap is selected on a layout and we are on a event sheet.

**Comment by DiegoScirra** [comment]
Duplicate of #417
