### ISSUE TITLE
If 2 or more instances has Pathfinding behavior, they won't have individual collision targets, it's all based on first instance

### ISSUE THREAD

**Issue by Guif0da** [Scirra/Construct-3-bugs#4190]
## Problem description

The attachment capx is basically the original pathfinding example with a second instance of 'Sprite' which has the pathfinding behavior. first one is set to collision 'Solid' and the second one to 'Custom', nothing new changed in event sheet.
When I click somewhere to start looking for a path and they start moving, the first instance of sprite should follow his path with solid as obstacle, so, it should avoid the solids, the second instance of sprite set as custom on obstacle should just ignore the solids and go straigth to the end of the path, this is because, it has nothing set as obstacle on eventsheet. But instead both follows the collision option of the first instance.

## Attach a .c3p
[Pathfinding_demo_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5185688/Pathfinding_demo_bug.zip)

## Steps to reproduce

1. open the project and notice that the first instance of sprite (the one bellow) is set collision as solid, the second as custom, then run the game
2. click on the opposite place of sprites to set a path and wait them start moving.
3. Notice both travels at the same path, independently the collision property set on each of them.

## Observed result

the first instance of sprite should follow his path with solid as obstacle, so, it should avoid the solids, the second instance of sprite set as custom on obstacle should just ignore the solids and go straigth to the end of the path, this is because, it has nothing set as obstacle on eventsheet.

## Expected result

both the sprite instances follow the same path of the first instance, if the second, or any other instance has a different option of collision, it will be ignored, they follow only the option set on the first instance, but other properties options of pathinding like speed, acceleration, etc, they each work in an independent way, if first is set to speed, acceleration and desaceleration to 2000 and the second set to 200, the first one will be faster, like it's supposed to be, but the collision properties doesn't work as an independent property.

Even if you try and use 'Clone object type' on the first instance of sprite, copy the same events and replace the object to the new sprite but instead of solid you set to 'custom' obstacle, it still gonna use 'solid' as an obstacle because of the first sprite.

## More details
tested on C3 free version version '210.2 stable' and basically clicked on F5 to preview it, didn't found any option on project properties for other browsers to test like on C2.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.83
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 52 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX 570 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
It's not a bug - all instances share the same obstacle map. This avoids wasting vast amounts of memory when using large numbers of instance. If you set contradictory settings, you'll get an obstacle map for one setting or another (arbitrarily, based on whichever setting the engine happens to use), since it doesn't track the obstacle map per-instance. There are more details about how the obstacle map works in the [Pathfinding behavior manual entry](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/pathfinding).

**Comment by Guif0da** [comment]
In terms of design this is far from being intuitive, how a new user supposed to know that? The memory thing isn't an excuse for not to do what others pathfinder behaviors can do, as an official behavior, it's a shame this decision but to be honest I'm not surprised..

Also please note that adding another object(not another instance) with pathfinding still uses the obstacle map from the first object sprite

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by AshleyScirra** [comment]
I've updated the manual to make it clearer this is how it works.

It works this way because if each instance had its own pathfinding map, and the map was say 1mb, and then you had 1000 instances, it would use 2 GB of memory. If you had 4000 instances, it would probably crash the system. It's so extremely inefficient it's not remotely scalable. So it's designed to share the pathfinding map and avoid the exploding memory usage completely.

**Comment by Guif0da** [comment]
But you need to understand not every Project gonna have 1000 simultaneous instances doing paths at the same time, my game for example it's a turn based RPG with top view angle, in most of the cases it will have only a few things using pathfinding at the same time for a very small period of time, so the memory thing in my case wouldn't be a problem, second my game is intended only for PC, not mobile. In a developer point of view you should give us the chance to choose which option do we want to use that suits the project we working on.
Also thats why games on PC has minimum specs configuration, if his game hes working on uses 2/4gb of memory during his stress tests and thats intended, thats okay, he gonna point out for the consumers the pc specs required to run his game.
Please do not cut out features like this on your engine, give us the options to work on according to the project we have in mind, things like that will only make construct stronger.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
