### ISSUE TITLE
Button is Focused doesn't fire when set to Checkbox

### ISSUE THREAD

**Issue by ariepert** [Scirra/Construct-3-bugs#4191]
When a Button is added to a project and set to CheckBox, the "is focused" event doesn't work.

## Attach a .c3p
[ButtonFocus.zip](https://github.com/Scirra/Construct-3-bugs/files/5185700/ButtonFocus.zip)

(just renamed the .c3p to .zip)

1. add a button to a project,
2. change Type to CheckBox
3. add an "On focused" event to the eventsheet
4. (event won't run)

## Observed result

"on focused" works fine when Type set to Button, but not CheckBox (on Chrome and Edge). I just tried this on my iPad and the "on focused" event doesn't work when the Type is Button as well.

## More details

in my sample file, click a button, the text object should get updated if the button has focus.  Pressing tab key should also change focus, but Construct doesn't realise the focus has changed when the type is CheckBox.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report, fixed for next release.
