### ISSUE TITLE
AJAX not loading variable data from object's saved json

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4192]
I save objects as JSON where object has some variable with values. but when  i load that back then it retrieving all data except variable data.
## Attach a .c3p
I am uploading 2 files here 
one is working fine and which was create in older version which is working fine in r214 and second file which is recreated in r214 but not working 
[instance variable in json.zip](https://github.com/Scirra/Construct-3-bugs/files/5189255/instance.variable.in.json.zip)

## Steps to reproduce

1. in attached .c3p file there is "positions.json" file which contains objects "dots" data.
2. try to implement that into object and check it variable if it getting variable data from json file.

## Observed result

object not getting its variable data from json file.

## Expected result

object should get its variable data from json file.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can you provide a minimal project as per the bug report guidelines? If the problem is as stated you should be able to demonstrate it with 1-2 objects and 1-2 events.

**Comment by luckyrawatlucky** [comment]
files updated to minimal project.

> open both files one by one 
> preview in debug mode
> check object "dots"'s  variable

**Comment by luckyrawatlucky** [comment]
hi @AshleyScirra 
here i noticed something new I tired to recreate the file in older version where it should work fine. But its not working. I remember that "working file" was created about between r190 to r210 but when i tried to recreate. It was not working there. I reached upto r120 but in all releases i am getting same issue. I thought it might be chrome issue but then i tried in Mozilla Browser but I am getting same issue there.

**Comment by AshleyScirra** [comment]
It looks like you are loading JSON data that was saved from a different and incompatible project. The instance variable's internal IDs are all different, so it fails to find any and doesn't attempt to load them. Loading data from different projects is not supported.

**Comment by luckyrawatlucky** [comment]
@AshleyScirra 
"from different project" do you mean I saved data in other software? if yes then No I used construct 3 to save this data. I just save it in another file and restoring in another file.
