### ISSUE TITLE
SliderBar Is Focused condition doesn't work with touch.

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#4194]
## Problem description

You can change slider bar with touch, but it's not getting focus.

## Attach a .c3p

https://www.dropbox.com/s/kdi6cbggz5vyarc/SliderFocusBug.c3p?dl=0

## Steps to reproduce

1. Run the project
2. Try changing slider bar with mouse and touc

## Observed result

When using touch control, "Is focused" condition is never true.
Similar issue with Button (if you touch it and continue holding the finger, the button doesn't have focus), and probably other form controls.

## Expected result

Consistent behavior with mouse and touch.

## More details

**Affected browsers/platforms:** all

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 85.0.4183.83
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
C3 release: r215 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 577 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
As far as I can tell, this is a customisation to how sliderbar focus works by the browser. You didn't mention any specific device, so I tried Chrome for Android. The browser allows the slider to be moved without the slider gaining focus (and it does not update the browser document.activeElement); however if you touch-and-hold then the focus does get placed on the slider and the 'Is focused' condition becomes true. The condition is set to true after the browser "focus" event anyway, so we do not have any custom logic to this, we rely on what the browser tells us. I also could not reproduce anything similar with the button plugin - it got focus right away as soon as I touched it.
