### ISSUE TITLE
Scene Graph - Save/Load game not saving parent/child relationships

### ISSUE THREAD

**Issue by simstratic** [Scirra/Construct-3-bugs#4197]
## Problem description

After using 'save game' action, then switching layout or restarting game, then using 'load game' action - instances no longer have their parent/child relationships.

## Attach a .c3p

https://drive.google.com/file/d/1M7SNoSh88IB9Hb3wTwXGEm8MI28tjahF/view?usp=sharing

## Steps to reproduce

1. Run preview.
2. Click 'add child' button. Blue square will now be a child of red square.
3. Click 'save' button.
4. Click 'load' button. This works - parent/child relationship maintained.
5. Click 'switch layout' button then on next layout click 'load' button. (OR restart game and press 'load' button on first layout)
6. Observe parent/child relationship has been lost.

## Observed result

Parent/child relationship is lost when loading game (after changing layout or restarting game).

## Expected result

Saving/loading game should preserve parent/child relationship.

## More details

Not sure if this a bug or just something that hasn't been implemented yet.

**Affected browsers/platforms:** 

Only tested on Windows 10, Edge Chromium.
**First affected release:** 
Only tested on r215 beta

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 85.0.564.44
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Edg/85.0.564.44
C3 release: r215 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 251 gb
Storage usage (approx): 1.1 gb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX 570 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report, this was indeed an oversight. It should be working in the next beta.
