### ISSUE TITLE
Advanced Minify Failed Export (Project Sent Via Email)

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#4198]
**## Problem description**

Project fails to export if advanced minification is selected.

**## Attach a .c3p**

Project sent via email to Scirra Support.

**## Steps to reproduce**

1. Click Export.
2. Select Android Export Method.
3. Select Android Studio Project.
4. Select Advanced Minification.
5. Start Export.

**## Observed result**

Error message: "Failed to export project"

**## Expected result**

The usual small window with exported file shown.

**Affected browsers/platforms:**

Chrome

**First affected release:** 

r210.2 and r215 (I can't recall successfully exporting an advanced minification android studio project in the past.)

**## System details**

Platform information
Browser: Chrome
Browser version: 85.0.4183.83
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 269 gb
Storage usage (approx): 741 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon(TM) Vega 8 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

Abbreviated Error Report: 

minifyWorker.js:2 [Minify] Closure Compiler had 10 compile errors:  Array(10)0: {file: "Input_0", description: "variable C3 is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 2514, charNo: 1}charNo: 1description: "variable C3 is undeclared"file: "Input_0"lineNo: 2514type: "JSC_UNDEFINED_VARIABLE"__proto__: Object1: {file: "Input_0", description: "variable _accessToken is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 6323, charNo: 32}2: {file: "Input_0", description: "variable _index is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 12474, charNo: 65}3: {file: "Input_0", description: "variable debugCommonLog is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 12687, charNo: 8}4: {file: "Input_0", description: "variable Call is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 16284, charNo: 6}5: {file: "Input_0", description: "variable _obj is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 16621, charNo: 15}6: {file: "Input_0", description: "variable _subGroup is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 16634, charNo: 15}7: {file: "Input_0", description: "variable objInfo is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 25627, charNo: 24}8: {file: "Input_0", description: "variable fabs is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 26015, charNo: 8}9: {file: "Input_0", description: "variable speedRatio is undeclared", type: "JSC_UNDEFINED_VARIABLE", lineNo: 30238, charNo: 8}charNo: 8description: "variable speedRatio is undeclared"file: "Input_0"lineNo: 30238type: "JSC_UNDEFINED_VARIABLE"__proto__: Objectlength: 10__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Object
self.JobHandlers.minify @ minifyWorker.js:2
main.js:2069 Error exporting:  Exception in job handler: Error: closure compiler error
Hdb @ main.js:2069

</details>

**Comment by AshleyScirra** [comment]
The provided project still used 4 third-party addons. It's most likely one of those causing the minify to fail, and it will need to be taken up with the addon developer.
