### ISSUE TITLE
Error changing fonts on Text Object

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#420]
## Problem description
When you try and change the font of a text object you get an unhandled promise rejection.

here is a gif of the error happening in real time:
https://drive.google.com/open?id=0B-BWGR6TVR6BSkY5WC13Smw2QkU

*Enter a concise description of your problem here*

## Attach a .c3p

and here is a link to the c3p file:
https://drive.google.com/open?id=0B-BWGR6TVR6BTlU4cWdJalM3aUk

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. I Added a TTF file in the fonts folder (don't think this matters since the error is not related to any fonts)
2. Create Text Object
3. Click on the arrow in the properties window to change font

## Observed result

*What do you see happen?*

I get an error box stating that an unhandled rejection happened and i get a system log of my computers specs

## Expected result

*What did you expect to happen instead?*

I get some type of font dialog or modal where i can select a font to use

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

happened on chrome did not try others

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r33

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 419 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Chrome doesn't seem able to read the .ttf file: it reports an error `OTS parsing error: loca: Out of order offset 28002 < 28156 for glyph 219`. I'd suggest using WOFF instead if you can. Still C3 shouldn't crash, so I've improved the error handling in this case to not crash C3, but you still can't choose the font.
