### ISSUE TITLE
Drawing Canvas - Pasting a 9-patch with an effect is glitched

### ISSUE THREAD

**Issue by Jase0000** [Scirra/Construct-3-bugs#4202]
## Problem description
If you have a 9-patch that has an effect (e.g. Black and White), and you use "Paste Object" with a Drawing Canvas, the result is the pasted image appears in a different position to what is expected.

## Attach a .c3p
https://drive.google.com/file/d/1RaZWKLL2keliYfdejUGKalx0PfNiTtdm/view?usp=sharing

## Steps to reproduce
1. Create a 9-patch object, with an effect (e.g. AdjustHSL)
2. Create Drawing Canvas
3. Paste 9-patch onto Drawing Canvas
4. Observe glitchy positioning of the paste result

## Observed result
The paste sort of offsets upwards and slightly left. Screenshot below:
https://drive.google.com/file/d/1TOpV2yr6x4Xyndf7imtsT9P0CkWAK0RV/view?usp=sharing

## Expected result
In this c3p file, nothing should happen when left-clicking.

**Affected browsers/platforms:** Chrome

**First affected release:** Both r210.2 and r215, so it's not to do with the Scene Graph stuff at all at least!

## System details
Windows 10 64-bit

**Comment by AshleyScirra** [comment]
I'm afraid this is another variant of #2624. Due to the enormous complexity of the effects compositor, some plugins render differently to others, and so that issue may affect different plugins in different circumstances.
