### ISSUE TITLE
Sprite rendering issue on r215

### ISSUE THREAD

**Issue by Nickeron** [Scirra/Construct-3-bugs#4203]
## Problem description
Τhe sprites randomly get chopped up.
This bug first appeared on another project when; upon creating a new Layer on top of the rest, the sprite I put there did not appear on runtime but was displaying properly on the editor.
Tried changing the image resize to either: Align Top, Align Left or Stretch but with no avail.

## Attach a .c3p
[Game with the issue.zip](https://github.com/Scirra/Construct-3-bugs/files/5201038/Game.with.the.issue.zip)

## Steps to reproduce

1. Open the c3p. 
2. On all of the layouts the described problem can be observed directly from the editor
3. To verify open any sprite that shows chopped up or is "invisible" to see that the image is ok

## Observed result
Some sprites not rendering correctly both on editor and on runtime

## Expected result
Expecting to see the sprites rendering normally as did in previous versions of Construct 3.

## More details

Issue NOT present on Firefox.
**Affected browsers/platforms:** 
Chrome latest version (85.0.4183.102)

**First affected release:** 
worked in r120 but broke in r125
## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 85.0.4183.102
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.9250000715255737
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
C3 release: r215 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 251 gb
Storage usage (approx): 300 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can't see anything wrong with this project in the editor at all. But I don't know what I'm looking for or what it's supposed to look like. Can you share some screenshots of what you see vs. what you expect to see?

Please also see the bug report guidelines regarding providing a minimal project - usually it is virtually impossible to debug projects this big.

**Comment by AshleyScirra** [comment]
No response for a week so closing.
