### ISSUE TITLE
desktop NW.js can no longer run fullscreen on start of layout

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-3-bugs#4206]
## Problem description

As per the manual:

'Fullscreen mode

To run NW.js exports in fullscreen mode, as with other platforms use the Browser object's Request fullscreen action. Normally in a browser this cannot be used automatically, and requires a user input event to work; however it can work automatically in NW.js. Therefore you can use Request fullscreen in On start of layout to automatically put an NW.js game in to fullscreen mode.' - https://www.construct.net/en/tutorials/exporting-desktop-apps-nw-js-15

This is no longer the case. Now on a desktop NW.js (at least for Win64), input is required from user to initiate fullscreen.

## Attach a .c3p

[fullscreen.zip](https://github.com/Scirra/Construct-3-bugs/files/5211806/fullscreen.zip)

## Steps to reproduce

1. create a project with browser object and request fullscreen on start of layout
2. export to desktop NW.js and run
3.

## Observed result

Game launches in a window

## Expected result

Game should launch in fullscreen

## More details

Confirmed with another user over Discord. Also, on researching this issue I found a forum thread from 3 months ago by another user also having the same issue: https://www.construct.net/en/forum/construct-3/how-do-i-8/fullscreen-start-layout-am-152984

**Affected browsers/platforms:** Windows 64 bit. There may be others

210.2 for me, but as per that forum thread, it's been an issue for at least 3 months

## System details

Win 10 64 bit, tried on desktop and laptop and both create same results.

**Comment by simstratic** [comment]
@Ldwebster111 this issue was reported #4179  and Construct team have already filed a bug report with NW.js. I have been testing this in my own project too - a couple of workarounds that might help you for now:

use NW.js version 0.45 instead (looks like bug started in 0.46)
or
request fullscreen after a user input (mouse or keyboard press)

**Comment by Ldwebster111** [comment]
I didn't see that. Will do a better search next time before posting an issue.
