### ISSUE TITLE
crash report on Copy paste Layout from one project to another

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4207]
## Problem description
i just tried to copy paste a layout from one project to another and i got error and crashed. 
crash report pasted below

## Steps to reproduce

1. copy and paste layout from one project to another.

## Observed result
crash

## Expected result
paste layout

## More details

some object are available on both side
when i do copy paste in absolutely new project then no crash. 

**Affected browsers/platforms:** 
chrome / desktop

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'u' of null @ TypeError: Cannot read property 'u' of null at Object.QIa (https://editor.construct.net/r215/components/bars/projectBar/projectBar.js:75:81) at Array. (https://editor.construct.net/r215/components/bars/projectBar/projectBar.js:3:426) at Object.$6c (https://editor.construct.net/r215/main.js:429:387) at Object.dispatchEvent (https://editor.construct.net/r215/main.js:425:135) at Object.C$ (https://editor.construct.net/r215/main.js:2079:154) at p.Ch (https://editor.construct.net/r215/projectResources.js:565:337) at p.xi (https://editor.construct.net/r215/projectResources.js:6:6) at p.xi (https://editor.construct.net/r215/projectResources.js:89:141) at p.xi (https://editor.construct.net/r215/projectResources.js:565:7) at p.Wa (https://editor.construct.net/r215/projectResources.js:5:418)
Stack: TypeError: Cannot read property 'u' of null at Object.QIa (https://editor.construct.net/r215/components/bars/projectBar/projectBar.js:75:81) at Array. (https://editor.construct.net/r215/components/bars/projectBar/projectBar.js:3:426) at Object.$6c (https://editor.construct.net/r215/main.js:429:387) at Object.dispatchEvent (https://editor.construct.net/r215/main.js:425:135) at Object.C$ (https://editor.construct.net/r215/main.js:2079:154) at p.Ch (https://editor.construct.net/r215/projectResources.js:565:337) at p.xi (https://editor.construct.net/r215/projectResources.js:6:6) at p.xi (https://editor.construct.net/r215/projectResources.js:89:141) at p.xi (https://editor.construct.net/r215/projectResources.js:565:7) at p.Wa (https://editor.construct.net/r215/projectResources.js:5:418)
Construct 3 version: r215
URL: https://editor.construct.net/r215/
Date: Sat Sep 12 2020 11:56:03 GMT+0530 (India Standard Time)
Uptime: 111.1 s

Platform information
Browser: NW.js
Browser version: 0.46.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.46.3 (like Chrome/83.0.4103.116)
C3 release: r215 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Please don't file issues unless you can follow all the guidelines. We need all that information to be able to help. A crash report on its own is usually impossible to act on.

**Comment by luckyrawatlucky** [comment]
@AshleyScirra  I thought crash report contains information about crash. 
btw i did lots of experiments with crash and found steps to recreate. 

1. Open two construct 3 editor at the same time
2. insert sprite in both editor with same name.
3. in editor one add any behavior to sprite.
4. now copy layout of editor 1
5. paste it in editor 2 and crash.

**Comment by AshleyScirra** [comment]
Please file a new issue following all the guidelines.

Crashes are automatically logged with us already, so there's no need to file an issue with just a crash report. However most of the time the cause of the problem is still a mystery. This is why we need steps to reproduce and the other details we ask for.
