### ISSUE TITLE
Cannot open cloud open in Opera 70.0

### ISSUE THREAD

**Issue by phantomfuxor** [Scirra/Construct-3-bugs#4208]
Basically this is a small report for bug and it maybe might be a Opera bug,

when i go to https://editor.construct.net/ 
and try to click the Cloud button, nothing happens. 

This is what appears:
![image](https://user-images.githubusercontent.com/175284/92991368-ac148180-f4e3-11ea-8b26-90e4b818b314.png)

and nothing after that. 

On another PC with opera it opens a selection of accounts from which it will take the files, but on this one no. 

Here's a screenshot of the developer console:
![image](https://user-images.githubusercontent.com/175284/92991399-d49c7b80-f4e3-11ea-9348-09c6101450dd.png)

Can you see why it doesn't work on one and works on another pc?

**Comment by AshleyScirra** [comment]
It's a bug in Chrome 84, which Opera 70 is based on. The next version of Chromium fixes it.
