### ISSUE TITLE
Image editor's hotkeys not working in Edge

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4209]
## Problem description

Title is self explanatory.

## Attach a .c3p

Any new file should present it in Edge, maybe other browsers too, maybe older files too.

## Steps to reproduce

1. Open any image, be it a sprite or a tilemap.
2. Press "F" to pay respects... I mean, to choose fill tool.
3. Observe the tool isn't selected.

## Observed result

Hotkeys not working in Edge.

## Expected result

Hot keys working.

## More details

**Affected browsers/platforms:** Latest Edge.

**First affected release:** 215.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by luckyrawatlucky** [comment]
me also getting issue. No short keys working of left side toolbars in image editor.

**Comment by DiegoScirra** [comment]
Thsis will be fixed in the nexte issue. Leaving this one open and tagged as fixed because it is quite noticeable.
