### ISSUE TITLE
Bugs on Tilesmap

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#421]
## Problem description
always restart on using tilemap
*Enter a concise description of your problem here*
inserted tilemap when i click on DrawTiles tool then restart option comes
## Attach a .c3p
no .c3p required 
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Create New Project
2. Insert Tilemap
3. just click on Drawtiles

## Observed result
restart
*What do you see happen?*
restart
## Expected result
work
*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r33/components/bars/tilemapBar/tilemapBar.js, line 1, col 20599
Message: Uncaught TypeError: Cannot read property '0' of undefined
Stack: TypeError: Cannot read property '0' of undefined at e.window.ǃ_N.ǃNmJ (https://editor.construct.net/r33/components/bars/tilemapBar/tilemapBar.js:1:20599) at window.ǃ_N.ǃrs.ǃNzG (https://editor.construct.net/r33/components/bars/tilemapBar/tilemapBar.js:1:29541) at window.ǃ_N.ǃrs.ǃNNP (https://editor.construct.net/r33/components/bars/tilemapBar/tilemapBar.js:1:26173) at e.window.ǃ_N.ǃNNQ (https://editor.construct.net/r33/components/bars/tilemapBar/tilemapBar.js:1:7481) at e.window.ǃ_N.ǃKM (https://editor.construct.net/r33/components/bars/tilemapBar/tilemapBar.js:1:7172) at ǃm.Event.ǃNqZ.ǃNqd (https://editor.construct.net/r33/main.js:2:254173) at ǃm.ǃN.ǃ_i.dispatchEvent (https://editor.construct.net/r33/main.js:2:252652) at ǃm.ǃN.ǃCW.ǃmzp.ǃst.ǃmun (https://editor.construct.net/r33/main.js:2:507514) at ǃm.ǃN.ǃCW.ǃmzp.ǃst.ǃmuG (https://editor.construct.net/r33/main.js:2:506853) at ǃm.ǃN.ǃCW.ǃmzp.ǃst.ǃmuW (https://editor.construct.net/r33/main.js:2:507259)
Construct 3 version: r33
URL: https://editor.construct.net/
Date: Fri Jun 02 2017 11:50:19 GMT+0530 (India Standard Time)
Uptime: 38.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
User agent: Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r33

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in r34.
