### ISSUE TITLE
OR conditions not working properly

### ISSUE THREAD

**Issue by Lobo93** [Scirra/Construct-3-bugs#4210]
## Problem description

In some specific cases, an action is not triggered, even when a condition in an "OR" block is true.

## Attach a .c3p

[OR bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5212829/OR.bug.zip)

## Steps to reproduce

1. Create a Sprite object with the Platform behavior
2. Create a Sprite object with the Solid behavior for the first object to interact with
3. Add the Keyboard object
3. Give the first object two different animations
4. Add the condition: If spacebar is down, change object 1 to second animation
5. Add the condition: If spacebar is not down **or** if object 1 is not on floor, change object 1 back to first animation

## Observed result

Object changes back to first animation by jumping (not on floor), but not when spacebar is released

## Expected result

Object should change back to first animation either by jumping (not on floor) or by releasing spacebar (spacebar id not down)

## More details

Tested in Windows 10
Browsers: Chrome v 85.0.4183.102 64 bits and Microsoft Edge v 85.0.564.51 64 bits

**First affected release:** C3 r215 (beta)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.102
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
C3 release: r215 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 267 gb
Storage usage (approx): 1.4 gb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's not a bug. This is a common misunderstanding with OR blocks.

The OR block runs because space bar is not down, but "Platform is not on floor" is not true (i.e. it is on the floor). Therefore the false condition has un-picked Sprite. The event runs with zero Sprite instances picked because none met the event's conditions; it's only running because a different condition is true. Therefore the Sprite action does not affect any instance.

If the action ran, it would mean an action ran on an instance that did *not* meet the event's conditions, which contradicts how conditions work.
