### ISSUE TITLE
Can't draw a 64x64 circle

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4213]
## Problem description

The Animation Editor can't draw a 64x64 circle. It either stops at 63x63 or snaps to 65x65.

## Attach a .c3p

Any new project.

## Steps to reproduce

1. Start a new project (I used 320x180, optimized for pixel art) 
2. Create a new sprite object.
4. Edit the sprite in the Animation Editor.
3. Resize the canvas to 64x64.
4. Set the grid to 4x4, no snap.
5. Select the circle tool (fill, but no border).

7A. Hold shift and draw a circle from 0,0. Notice the first row/column are not used to draw the circle, resulting in a 63x63 circle, despite the readout on the status bar showing 64x64.

7B. Clear the canvas, then hold shift and draw a circle from -1,-1. The circle now uses the first row/column, but will snap outside the canvas when you make the circle 64x64, or snap inside the canvas at 63x63.

## Observed result

See above; the circle is either 63x63 or 65x65

## Expected result

A 64x64 circle.

## More details

[https://ibb.co/LpyNKMq](url)

**Affected browsers/platforms:** Chrome, Safari on Construct 215 Beta

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.83
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
C3 release: r215 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 140 gb
Storage usage (approx): 260 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics 655
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
