### ISSUE TITLE
Crash while pressing TAB in Animation Editor (Safari)

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4214]
Pressing TAB while the "resize sprite" dialog is open moves the Animation Editor window to the foreground. Closing the sprite editor reveals the Resize Sprite dialog was underneath it. Closing it causes a crash.

## Attach a .c3p

Any new project.

## Steps to reproduce

1. Open Safari
2. Open Construct and start a new project.
3. Create a sprite object, and open it in the Animation Editor.
4. Click Resize Image Canvas.
5. Press TAB, returning to the Animation Editor window.
6. Close the Animation Editor, revealing the Resize Image Canvas window.
7. Click OK.
 
## Observed result

The program crashes.

## Expected result

1. Any/all Animation Editor related windows should be closed when you exit the Animation Editor window.
2. Pressing TAB shouldn't switch away from the Resize Image Canvas window; instead it should highlight the first resize field.

## More details

N/A

**Affected browsers/platforms:** Safari

**First affected release:** 215 Beta

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: undefined is not an object (evaluating 'n.length') @ cb@https://editor.construct.net/r210-2/projectResources.js:1825:73 fJb@https://editor.construct.net/r210-2/projectResources.js:1791:54 Qs@https://editor.construct.net/r210-2/projectResources.js:1420:210 Sgd@https://editor.construct.net/r210-2/projectResources.js:1471:116 https://editor.construct.net/r210-2/projectResources.js:1471:95 asyncFunctionResume@[native code] [native code] promiseReactionJobWithoutPromise@[native code] promiseReactionJob@[native code]
Stack: cb@https://editor.construct.net/r210-2/projectResources.js:1825:73 fJb@https://editor.construct.net/r210-2/projectResources.js:1791:54 Qs@https://editor.construct.net/r210-2/projectResources.js:1420:210 Sgd@https://editor.construct.net/r210-2/projectResources.js:1471:116 https://editor.construct.net/r210-2/projectResources.js:1471:95 asyncFunctionResume@[native code] [native code] promiseReactionJobWithoutPromise@[native code] promiseReactionJob@[native code]
Construct 3 version: r210.2
URL: https://editor.construct.net/
Date: Sun Sep 13 2020 09:27:25 GMT-0400 (EDT)
Uptime: 13.7 s

Platform information
Browser: Safari
Browser version: 13.1.2
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
C3 release: r210.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics 655
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_blend_minmax, EXT_sRGB, EXT_frag_depth, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_standard_derivatives, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context, WEBGL_compressed_texture_s3tc, WEBGL_depth_texture, WEBGL_draw_buffers, ANGLE_instanced_arrays, WEBGL_debug_renderer_info

</details>

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta. Pressing tab will no longer hide dialogs behind the Animations editor.
