### ISSUE TITLE
(Physics Behavior) Disabling the physics collision of an object also disables the collision of other unsolicited objects

### ISSUE THREAD

**Issue by marcelokohl** [Scirra/Construct-3-bugs#4215]
## Problem description

When I disable the physics collision of an object type ("box" object in .c3p), sometimes other objects of the same type also lose the collision.

## Attach a .c3p

[BUG - Disable Physics collisions with.zip](https://github.com/Scirra/Construct-3-bugs/files/5214253/BUG.-.Disable.Physics.collisions.with.zip)

## Steps to reproduce

1. Preview the .c3p and drag an object written "drag" to the yellow area.
2. The object that touches the yellow area will be disabled from physical collision, and will be 50% opaque
3. Sometimes the other objects that did not touch the yellow area also lose their physical collision, drag these over the other non-opaque "drag" objects to see that they have lost the collision.
4. If you stack some objects and drag a "drag" to the yellow area, the stacked objects do not seem to lose the physical collision.

## Observed result

When I disable the physical collision of an object, sometimes the sister objects also lose the physical collision without having been requested it.

## Expected result

Any object that touches the yellow area disables the physical collision and no longer collides with its brothers, but the other brothers continue to collide with each other.

## More details
Play de project:
https://c3-physics-bug.herokuapp.com/

Video demonstrating the problem:
https://www.loom.com/share/ae477bba2c694814a1aefe983c40559d

**Affected browsers/platforms:** 
Chrome, Firefox, Opera, Edge
Windows, Android

**First affected release:** 
r210.2
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.102
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 153 gb
Storage usage (approx): 63 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's not a bug. [The documentation](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/physics) explains that 'Enable/disable collisions' affects all instances of an object type (i.e. it affects object types, not instances):

> **Enable/disable collisions**
> By default, all Physics objects collide with each other. You can disable collisions between the object and another Physics object so they pass through each other. **This affects all instances of both object types.**

**Comment by marcelokohl** [comment]
@AshleyScirra, any chance that this will change in the future and start to disable only the selected instance, like it works with opacity? As it is, it is impossible to disable only the object I need.
