### ISSUE TITLE
Exceeding tile number in Tilemap->Set tile action displays other parts of spritesheet in Tilemap

### ISSUE THREAD

**Issue by simstratic** [Scirra/Construct-3-bugs#4216]
## Problem description

In the Tilemap -> Set tile action, if you enter a Tile parameter that exceeds the number of tiles in the tilemap image, other parts of the spritesheet will be displayed in the tilemap.

## Attach a .c3p

https://drive.google.com/file/d/1gyDli5CXErnoFUZvPTNtiWmfDzy4Ayhd/view?usp=sharing

## Steps to reproduce

1. Preview the project.
2.
3.

## Observed result

The red square (which is a separate sprite object) is displayed in the tilemap.

## Expected result

Not sure - I think this is unintended use case coming from improper use of the Tile number parameter - not really a bug - but please see more details.

## More details

This isn't my own issue, but it came from investigating this forum post:
https://www.construct.net/en/forum/construct-3/general-discussion-7/c3-tilemap-visual-bug-155160#forumPost1022471

As I mentioned this is improper coding on the user's side, maybe with no bounds checking to catch it, but then I remembered this post:
https://www.construct.net/en/forum/construct-3/general-discussion-7/possible-bug-changing-155060

So I felt it should be reported in case there's some deeper problem going on with tilemap image UVs etc.

**Affected browsers/platforms:** 
Only tested on Windows 10, Edge Chromium

**First affected release:** 
Only tested on r215
## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Browser: Edge
Browser version: 85.0.564.51
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51
C3 release: r215 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 251 gb
Storage usage (approx): 2.3 gb (0.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX 570 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
Just to be clear, this report deals with setting a tile to an invalid value, and how the error is dealt with. It's true that it should not display unrelated content from the rest of the spritesheet even with invalid values.

At the moment the runtime doesn't know what the highest allowed tile number is. I think the editor needs to export it, since the calculations for tile number assignment are nontrivial. Assigning to @DiegoScirra for that part.

**Comment by simstratic** [comment]
Yes that is correct, this issue comes from user error setting tiles to invalid values. If you export the maximum tile number and apply a bounds check, my concern is it might negatively impact users who are repeatedly using 'Set tile' on a large number of tiles (which is already fairly costly). Use cases where they might be doing this are tile based lighting, fog of war, simulation of spreading fire etc., procedural generation and large scale (or even infinite scale) worlds where you use a tilemap just bigger than the viewport and 'stream' data into the tilemap. Just wanted to mention it as something to consider.

**Comment by DiegoScirra** [comment]
The editor now exports the maximum tile index.

**Comment by AshleyScirra** [comment]
OK, implemented tile ID validation for the next release, which should fix this. Any attempt to set an invalid tile ID will simply be ignored and not change the tilemap.
