### ISSUE TITLE
crash on copy paste a layout from one project to another

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4218]
## Problem description
copy pasting a layout crashes when there is a object on both side with same name but copied object has additional behavior or variable or effect.

## Attach a .c3p
no file need

## Steps to reproduce

1. Open two construct 3 editor at the same time
2. insert sprite in both editor with same name.
3. in editor one add any behavior / effect / variable to sprite.
4. now copy layout of editor 1
5. paste it in editor 2 and crash.

## Observed result
crash on paste layout

## Expected result
There should no crash. But in this case where object has same name but one has variable / behavior / effect and other don't then it should show us msg with details like 
"the layout you are trying to paste contains duplicate object 'object name' which has a behavior / variable / effect. These behavior / variable / effect are not added in existing object."
and there should buttons "Merge object" and "paste it"
Merge object will add behavior / variable / effect to existing object
Paste it will just create another object by adding number "object name1".

something like this

## More details

**Affected browsers/platforms:** 
I tested it in Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'u' of null @ TypeError: Cannot read property 'u' of null at Object.QIa (https://editor.construct.net/r215/components/bars/projectBar/projectBar.js:75:81) at Array. (https://editor.construct.net/r215/components/bars/projectBar/projectBar.js:3:426) at Object.$6c (https://editor.construct.net/r215/main.js:429:387) at Object.dispatchEvent (https://editor.construct.net/r215/main.js:425:135) at Object.C$ (https://editor.construct.net/r215/main.js:2079:154) at p.Ch (https://editor.construct.net/r215/projectResources.js:565:337) at p.xi (https://editor.construct.net/r215/projectResources.js:6:6) at p.xi (https://editor.construct.net/r215/projectResources.js:89:141) at p.xi (https://editor.construct.net/r215/projectResources.js:565:7) at p.Wa (https://editor.construct.net/r215/projectResources.js:5:418)
Stack: TypeError: Cannot read property 'u' of null at Object.QIa (https://editor.construct.net/r215/components/bars/projectBar/projectBar.js:75:81) at Array. (https://editor.construct.net/r215/components/bars/projectBar/projectBar.js:3:426) at Object.$6c (https://editor.construct.net/r215/main.js:429:387) at Object.dispatchEvent (https://editor.construct.net/r215/main.js:425:135) at Object.C$ (https://editor.construct.net/r215/main.js:2079:154) at p.Ch (https://editor.construct.net/r215/projectResources.js:565:337) at p.xi (https://editor.construct.net/r215/projectResources.js:6:6) at p.xi (https://editor.construct.net/r215/projectResources.js:89:141) at p.xi (https://editor.construct.net/r215/projectResources.js:565:7) at p.Wa (https://editor.construct.net/r215/projectResources.js:5:418)
Construct 3 version: r215
URL: https://editor.construct.net/r215/
Date: Sat Sep 12 2020 11:56:03 GMT+0530 (India Standard Time)
Uptime: 111.1 s

Platform information
Browser: NW.js
Browser version: 0.46.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.46.3 (like Chrome/83.0.4103.116)
C3 release: r215 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2
</details>

**Comment by AshleyScirra** [comment]
Minimal repro:
[proj1.zip](https://github.com/Scirra/Construct-3-bugs/files/5225188/proj1.zip)
[proj2.zip](https://github.com/Scirra/Construct-3-bugs/files/5225189/proj2.zip)
Please always include relevant project files as per the bug report guidelines - it's slower and more difficult to deal with issues without them.

**Comment by AshleyScirra** [comment]
Should be fixed in next beta
