### ISSUE TITLE
Multiplayer peer : weird motion on collisions with local input prediction

### ISSUE THREAD

**Issue by Rikette** [Scirra/Construct-3-bugs#4219]
## Problem description

Multiplayer peer : weird motion on collisions with local input prediction

## Attach a .c3p
[Google Drive Link (needs R215)](https://drive.google.com/file/d/1RkcpC2tGJVIFYB8wX2P3qOyzMofYj7e0/view)

## Steps to reproduce

1. Run the game. Make sure to connect 2 clients (one host and one peer).
2. Start moving the peer client using the left and right keys until it collides with a solid.

## Observed result

The player sprite suddenly moves vertically although no vertical movement has been input. It then creates a position desync between the host and the peer.

## Expected result

The player sprite should stop right away on a collision.

## More details
Before posting, I googled and found [someone that had the exact same issue but never got any answer](https://www.construct.net/en/forum/construct-2/bugs-21/multiplayer-peer-spurious-141332).

I'm not exactly sure if this is a bug, and how could I fix this if it's not.

**Affected browsers/platforms:** 
Chrome / Firefox on Windows

**First affected release:** 
Problem discovered in r210 and r215, but seems like any version is affected.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.102
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
C3 release: r215 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 66 gb
Storage usage (approx): 967 mb (1.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The problem is the host is authoritative, and you can see the player collides with the solid and stops dead on the host.

On the peer, local input prediction tries to keep the player moving, but it cannot move on the host. Because of the mismatch (the peer thinks the player can move but the host thinks it cannot), the peer will keep getting moved back as it tries to correct the discrepency between its local position and the position the host is saying it's really at.

You need to design your game to avoid this problem. It's one of the reasons multiplayer games are difficult to get right. Perhaps you could disable the solid behaviors on the peers and rely on collision detection done by the host only.

**Comment by Rikette** [comment]
@AshleyScirra I tried it and unfortunately it makes the peer going "into" the wall almost entirely before going back to his normal position.
