### ISSUE TITLE
Crash when comparing sprite.platform.(...)

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#422]
## Problem description
The editor crashes when you try to access any value of a platformer object.
Just type "sprite.platform." then any character and the crash will occur in various dialogs. Tested with
System / Compare two values
Sprite / Compare X
Sprite / Compare Speed

## Attach a .c3p
Just use the platformer template.

## Steps to reproduce

1. You need to have an object type with a platform behavior 
2. add a new "compare" condition in which you can type something. e.g. System/compare two values 
3. type [name of the object type].platform. followed by any character (for example, "v")

## Observed result
The editor crashes

## Expected result
be allowed to access the desired value.

## Affected browsers

* Chrome: yes
## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r33/main.js, line 149, col 94552
Message: Uncaught ReferenceError: ǃIa is not defined
Stack: ReferenceError: ǃIa is not defined at window.ǃmX$.ǃmk (https://editor.construct.net/r33/main.js:61:346253) at i.ǃmk (https://editor.construct.net/r33/main.js:61:334081) at i.ǃmk (https://editor.construct.net/r33/main.js:61:334050) at window.ǃBg.ǃmkB (https://editor.construct.net/r33/main.js:61:329347) at window.ǃBg.ǃmkL (https://editor.construct.net/r33/main.js:61:330674) at window.ǃzhp.ǃzhP (https://editor.construct.net/r33/main.js:149:92019) at window.ǃzhp.ǃzhH (https://editor.construct.net/r33/main.js:149:94498) at ǃzhQ (https://editor.construct.net/r33/main.js:149:91624)
Construct 3 version: r33
URL: https://editor.construct.net/index.html
Date: Fri Jun 02 2017 12:31:19 GMT+0200 (Central Europe Daylight Time)
Uptime: 3278.5 s
Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r33
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Oops, thanks, should be fixed in r34.
