### ISSUE TITLE
Reward Vids not working, But Banner Does! 

### ISSUE THREAD

**Issue by alargha** [Scirra/Construct-3-bugs#4220]
## Problem description
Mobile Advert plugin has been implemented correctly, all Required inputs as well, exported as:
1- cordova project , results was : Banner working, Reward Video NOT! ( not even the Test video ).
2- Debug apk, results was : Banner working, Reward Video NOT! ( not even the Test video ).
3- Signed release apk, results was : Banner working, Reward Video NOT! ( not even the Test video )
and so on.
All settings at Admob are correctly fine, including "Vid Ads Unit ID", but i have no clue what cause this behavior.
App has been tested on different android devices, results remain the same!!
C3 Release : r210.2

## Attach a .c3p
[Test Ads.zip](https://github.com/Scirra/Construct-3-bugs/files/5222105/Test.Ads.zip)

## Steps to reproduce

1.Add Mobile Advert plugin.
2.Test Reward ads ( Create ) and ( Show ).
3. Reward video complete then add 20 to Coins variable.

## Observed result
Mobile Advert plugin not functioning correctly.

## Expected result

On touch sprite , show Reward video, when video is finished then add 20 to Coins variable . 

## System details

Android 

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
I replaced all the IDs with known good ones I've used for testing, and the rewarded video ad showed just fine in a debug APK. I would guess you have configured it incorrectly. Please refer to the [documentation](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/mobile-advert). You may also want to try ensuring 'On configuration complete' has triggered before attempting to create any ads, to ensure they can abide by any startup permission/consent requests, and try only creating one ad at a time.
