### ISSUE TITLE
Project File Does not Open

### ISSUE THREAD

**Issue by simonpaulkeating** [Scirra/Construct-3-bugs#4221]
The attached project (.c3p) will not open withe error : Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project. I am using Construct version  210.2 stable

## Attach a .c3p
[Verge3DTest.zip](https://github.com/Scirra/Construct-3-bugs/files/5224522/Verge3DTest.zip)

## Steps to reproduce

Attempt to open the attached file in construct 3

## Observed result
Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project

## Expected result
The project should open

## More details

**Affected browsers/platforms:** 

Testing in Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**First affected release:** 

Was working AUgust 16th (unsure of version) but in recent version (210.2) does not work

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 312 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The problem is the project file has events that reference a file named `C3_InterfaceTest.html`, but no such file exists in the project. (Press F12 to see the error message stating this in the browser console.)

You should be able to fix it by renaming the .c3p project to .zip, extracting to a folder, adding any missing files, then adding back to a zip file (or just [open directly as a folder project](https://www.construct.net/en/forum/construct-3/general-discussion-7/local-file-folder-saves-chrome-147071)).

The project uses third-party addons, so my best guess is one of those corrupted the project. Any problems with third-party addons need to be reported to their respective developers. Whoever deals with the issue would also need to know steps to reproduce the problem in the first place in order to do anything about it.

**Comment by simonpaulkeating** [comment]
OKay cheers. Maybe the error message could be improved to point me in the right direction (specific plugin/missing file) otherwise I just end up wasting your time. Cheers!

**Comment by simonpaulkeating** [comment]
I tried your solution but sadly I now just get the error: Error: missing file path 'project.c3proj'
