### ISSUE TITLE
The problem of display of the inserted objects in the canvas when rotating layers

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#4226]
The problem of display of the inserted objects in the canvas when rotating layers

Run the project:
https://drive.google.com/file/d/1KsS0FGs3b8DJJpSqRxFU5LrpAMPSjxrV/view?usp=sharing

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's not clear what to do with the provided project, what you're seeing, or what you expect it to do. Please always follow the full bug report guidelines. As always it's helpful to provide a minimal project, using the fewest objects and events possible.

**Comment by ibiz3091** [comment]
> Неясно, что делать с предоставленным проектом, что вы видите, или что вы ожидаете от него сделать. Пожалуйста, всегда следуйте полным рекомендациям по сообщению об ошибках. Как всегда, полезно обеспечить минимальный проект, используя как можно меньше объектов и событий.

What's not clear here? The canvas must insert an SVGPicture and Sprite object on the layer (Light). Turn on the Visible Light button and click Rotate Player. and you will see that canvas inserts these objects incorrectly.

This is how it should look, it worked correctly in r200:
https://drive.google.com/file/d/12d3CNIQ_yP89Ps0OzX8hq8UZC7iVQBOc/view?usp=sharing

**Comment by ibiz3091** [comment]
> Please always follow the bug report guidelines. If you miss out details, I cannot investigate the report. That is why we require that all the details are provided.

I made a very simple project for you, it looks like the canvas does not take into account the angle of the layer on which the sprite is located.:
https://drive.google.com/file/d/1lzPk0-TSGK07b3qwNFIIRY9K_PYlczlo/view?usp=sharing

**Comment by ibiz3091** [comment]
> Please always follow the bug report guidelines. If you miss out details, I cannot investigate the report. That is why we require that all the details are provided.

Have you seen my project?

**Comment by AshleyScirra** [comment]
Once again, please follow the bug report guidelines. I must emphasise that if you do not follow the bug report guidelines, we cannot help you.

> **My report was closed for not following the guidelines. What should I do next?**
> Please do not reply to closed bug reports. Instead, please file a new report, and make sure you follow all the guidelines and provide any missing information.
