### ISSUE TITLE
Crash on copy paste event sheet

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4227]
## Problem description
copy paste event sheet from one project to another gives crash If event sheet is using a variable from another event sheet

## Attach a .c3p
[crash eventsheet.zip](https://github.com/Scirra/Construct-3-bugs/files/5232147/crash.eventsheet.zip)

## Steps to reproduce

1. open both files on two separate editors.
2. copy eventsheet 1 from "file1" 
3. paste it to "file 2".

## Observed result
crash report

## Expected result
no crash only copy paste

## More details

**Affected browsers/platforms:** 
tested only in chrome

**First affected release:** 
## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'toString' of undefined @ TypeError: Cannot read property 'toString' of undefined at Function.bZa (https://editor.construct.net/r216/main.js:371:230) at PHc (https://editor.construct.net/r216/main.js:394:255) at Object.W2c (https://editor.construct.net/r216/components/bars/projectBar/projectBar.js:92:45) at Object.bN (https://editor.construct.net/r216/components/bars/projectBar/projectBar.js:31:35) at Object.uJ (https://editor.construct.net/r216/components/bars/projectBar/projectBar.js:30:244)
Stack: TypeError: Cannot read property 'toString' of undefined at Function.bZa (https://editor.construct.net/r216/main.js:371:230) at PHc (https://editor.construct.net/r216/main.js:394:255) at Object.W2c (https://editor.construct.net/r216/components/bars/projectBar/projectBar.js:92:45) at Object.bN (https://editor.construct.net/r216/components/bars/projectBar/projectBar.js:31:35) at Object.uJ (https://editor.construct.net/r216/components/bars/projectBar/projectBar.js:30:244)
Construct 3 version: r216
URL: https://editor.construct.net/r216/
Date: Wed Sep 16 2020 18:03:01 GMT+0530 (India Standard Time)
Uptime: 14.8 s

Platform information
Browser: Chrome
Browser version: 85.0.4183.102
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
C3 release: r216 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
