### ISSUE TITLE
Add Child, Cannot read property release of null, calling Instance.Release

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#4229]
## Problem description

A java script error is thrown after navigating across layouts when using the SceneGraph actions, It seems some resource is not being released, Disabling the Add Child actions before navigating does not throw any JavaScript errors.

## Attach a .c3p

c3p project 
https://drive.google.com/file/d/1BIYumnSPNqcSh0VpeD9ZBopmdPYGqMXT/view?usp=sharing

error screenshot
https://drive.google.com/file/d/1nNIuhj91w3hBt71Te_VwTRScN4Cz5bVi/view?usp=sharing

problem actions
https://drive.google.com/file/d/1aAj8RpplYw2CpI3-Sp0PUggNNJEC-3zy/view?usp=sharing

## Steps to reproduce

1.  Have a global layout
2.  in a separate layout, Add children to object in global object 
3. Navigate to separate layout

To reproduce error in c3p provided, 

1. start the project from title_screen layout
2. click the play button (takes to to new layout)
               (this layout has a global layer, and on start of layout, is adding children to instance on that global layout)
3. open dev tools to spot error
4. click on the green check mark in lower right hand to navigate to new layout, (this action throws the exception)

If you disable the add child actions in the in inn_events (event id #2) and rerun the same steps the error does not occur

## Observed result

when the js exception is thrown the game freezes, there is an infinite loop of console errors, and no logic on the event sheet is ran.

## Expected result

no errors are thrown, and game logic is executed as expected

## More details

**Affected browsers/platforms:** 

Working on the new Edge browser, on Windows

**First affected release:** 

https://editor.construct.net/r215/
have not tried with any other release

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 85.0.564.51
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51
C3 release: r215 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 423 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce in r216. Please only test the latest release as per the bug report guidelines, to avoid reporting problems we've already fixed.
