### ISSUE TITLE
Medium Quality Downscaling shows Transparent Edges in Billinear/Trillinear

### ISSUE THREAD

**Issue by XpMonster** [Scirra/Construct-3-bugs#4231]
## Problem description

When Medium Quality Downscaling is used, project in preview/exported shows edges around object when shrinking the size of the window. 

## Attach a .c3p

https://drive.google.com/file/d/1UgYWBRHpUBzfmaYXWE4csVtlMyiZWqEu/view?usp=sharing

## Steps to reproduce

1. Create project, use recommended "Medium" downscaling quality & trillinear OR billinear sampling. 
2. Create square sprites and place them next to each other avoiding overlap. 
3. Preview the project and shrink the resolution. 

## Observed result

The transparent edges around squares appear.
While scrolling, edges would disappear and appear again. 

This has been a problem of Construct for a long time now. 

![chrome_ftrdUW0mYn](https://user-images.githubusercontent.com/28805581/93645994-faf37700-fa0d-11ea-89f4-c710c7ebc9bf.png)

## Work Around
1) Use High Quality Downscaling, but waste a huge amount of memory
2) Use Low Quality Downscaling, but significantly reduce quality of your images on all devices with resolution below original 
3) Use Nearest sampling which would ruin intended vector/raster visuals.
4) Draw at least 4 extra pixels around edges and make images overlap. A nightmare for the artist. 

## Expected result
Never see transparent edges regardless of resolution.

**Affected browsers/platforms:**
Not exclusive to preview. Same results in exported Desktop project.

**First affected release:**
It was always the issue, but my project is on r210.2 (stable)

**Comment by XpMonster** [comment]
I will also add here. That if I add

**Comment by XpMonster** [comment]
Extra issue on top of that is that if I use same square images with transparent edges and try shrinking resolution, it will give me the problem on any downscaling quality. And one apparently must have transparent edges to apply AA algorithm to soften/clean the edges.

**Comment by luckyrawatlucky** [comment]
This is not a bug. see this #3025

**Comment by AshleyScirra** [comment]
It's not a bug. See [this blog post](https://www.construct.net/en/blogs/ashleys-blog-2/surprising-difficulty-1528) for a detailed explanation. It's also why high quality downscaling exists as an option, since it solves this.
