### ISSUE TITLE
iOS export doesnt work anymore with recently updated XCode

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#4232]
## Problem description

With the new XCode Update to Version 12.0 (12A7209), iOS export doesnt work anymore, Xcode crashes on startup

## Steps to reproduce

1.open Kiwi Story example game
2.export to Xcode (I used deduplicated images/recompress Images /Minify: None/ min Version 13 / Hide Status bar active
3.open in Xcode Version 12.0 (12A7209)

## Observed result
doesnt open, crash

## Expected result
it should open Xcode

## More details

**Affected browsers/platforms:** 
I used lates Beta r216, and with stable same problem with my own project. I exported it in chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.102
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
C3 release: r216 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 450 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Are you saying Xcode crashes? If so that is a bug in Xcode that will need to be reported to Apple instead.

**Comment by bubbblebub** [comment]
Yes its Xcode that crashes. I will try to downgrade Xcode until the problem is solved, thanks for the answer

**Comment by bubbblebub** [comment]
just for your information, Xcode had a new update and now it works fine. Even the Device Simulators seems to work now!

**Comment by AshleyScirra** [comment]
Thanks, good to know.
