### ISSUE TITLE
Splash Storyboard shows the navigation bar and status bar during launch.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4233]
## Problem description

Splash Storyboard shows the **navigation bar** and **status bar** during launch.
(And momentarily, that left portion in the first image.)

![image](https://user-images.githubusercontent.com/31282960/93688553-3d45b280-faf9-11ea-8fa0-5aa981bcf3af.png)
![image](https://user-images.githubusercontent.com/31282960/93688558-40d93980-faf9-11ea-85e4-b1234b82143e.png)

It is not visually appealing the longer the splashboard is shown, especially for game applications.

Here is a comparison from **Unity**:
![image](https://user-images.githubusercontent.com/31282960/93688618-9e6d8600-faf9-11ea-9532-e0dd59bbe7f0.png)

It doesn't have the issue on **Unity**, **Cocos2d** and other game engines.

## Attach a .c3p

**Project file:**
[Splash Project.zip](https://github.com/Scirra/Construct-3-bugs/files/5250556/Splash.Project.zip)
**Project .apk:**
[Splash - APK.zip](https://github.com/Scirra/Construct-3-bugs/files/5250557/Splash.-.APK.zip)

## Steps to reproduce

1. Open application.
2. Review the Splash Storyboard.

## Observed result

The `status bar` and `navigation bar` shows during splash storyboard launch.

## Expected result

The **Splash Storyboard** to not show the `status bar` and `navigation bar` during launch.

## More details

Thank you!

**Comment by karimlahbach** [comment]
any news about this one Ashley ?

**Comment by AshleyScirra** [comment]
Note: this is the expected result if you don't tick "Hide status bar". It's not in your steps to reproduce, but I assume you are ticking that.

I'm afraid as far as I can tell Cordova does not provide a way to do this on Android. At the moment we can only do this by API calls, but our code only runs after the splash screen is already shown. I tried adjusting the config file to specify fullscreen mode, but it did not affect the splash screen.

I filed a [feature suggestion](https://github.com/apache/cordova-android/issues/1107) with Cordova. If they add support for this, we can use it then.

**Comment by karimlahbach** [comment]
Hi Ashley i found this maybe the bug already solved by Cordova team you need just to update cordova on the server
[https://github.com/apache/cordova-android/pull/733](https://github.com/apache/cordova-android/pull/733)

**Comment by AshleyScirra** [comment]
That appears to be a pending change that has not yet been accepted by the Cordova team. I'm afraid we can't use it until it reaches a full release of cordova-android.

**Comment by fredriksthlm** [comment]
@AshleyScirra Cordova 9.1.0 is now in a official release now, and this fix (and a lot other!) is included.
So maybe you can change to 9.1.0 now?

**Comment by AshleyScirra** [comment]
I'll look in to it.

**Comment by karimlahbach** [comment]
i'm still having this bug even with the last Cordova update 
Any idea to fix this ?

**Comment by AshleyScirra** [comment]
This needs to be supported by Cordova. I filed a request with them here: https://github.com/apache/cordova-android/issues/1107

**Comment by karimlahbach** [comment]
Is there any Hack to solve this issue ?
( it seem like Cordova Team not really planning to do something since it been 1 years )
(opened this issue on Oct 22, 2020)
i found this a solution but i don't know if going to work or not because i'm not good at coding
[https://github.com/apache/cordova-android/issues/844#issuecomment-924016189](https://github.com/apache/cordova-android/issues/844#issuecomment-924016189)
Check Last comment
