### ISSUE TITLE
Construct 3:  Нет кнопки /раздела"свойств" объекта

### ISSUE THREAD

**Issue by Stellardurman** [Scirra/Construct-3-bugs#4234]
в бесплатной версии констракта 3 не вижу свойств объекта :) типа Name и тд и тп 

![image](https://user-images.githubusercontent.com/71601345/93715793-36a85100-fb74-11ea-9f56-570ff0ae6b4c.png)

**Comment by luckyrawatlucky** [comment]
Menu  > View > Bars > Properties bar

**Comment by DiegoScirra** [comment]
Closing this, we only accept reports in English and this isn't even a bug.
