### ISSUE TITLE
Whitelist a few Cordova plugins.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4235]
Hi, would you please whitelist the following Cordova plugins:

1. `cordova-launch-review@4.0.0`
2. `cordova-plugin-appsflyer-sdk@6.0.30`
3. `chadori-mobile-masteriap@1.0.1`
4. `chadori-mobile-ironsource@0.0.4`
5. `chadori-mobile-ironsource-debug@0.0.4`
6. `chadori-mobile-ironsource-adcolony@0.0.3`
7. `chadori-mobile-ironsource-admob@0.0.3`
8. `chadori-mobile-ironsource-amazon@0.0.3`
9. `chadori-mobile-ironsource-applovin@0.0.3`
10. `chadori-mobile-ironsource-chartboost@0.0.3`
11. `chadori-mobile-ironsource-facebook@0.0.3`
12. `chadori-mobile-ironsource-fyber@0.0.3`
13. `chadori-mobile-ironsource-hyprmx@0.0.3`
14. `chadori-mobile-ironsource-inmobi@0.0.3`
15. `chadori-mobile-ironsource-maio@0.0.3`
16. `chadori-mobile-ironsource-pangle@0.0.3`
17. `chadori-mobile-ironsource-tapjoy@0.0.3`
18. `chadori-mobile-ironsource-unityads@0.0.3`
19. `chadori-mobile-ironsource-vungle@0.0.3`

Thank you!

**Comment by Chadori** [comment]
Hi, would you also whitelist these plugin versions, I need these for iOS 14.
Thank you!
```
chadori-mobile-ironsource@0.0.4
chadori-mobile-ironsource-debug@0.0.4
chadori-mobile-ironsource-adcolony@0.0.3
chadori-mobile-ironsource-admob@0.0.3
chadori-mobile-ironsource-amazon@0.0.3
chadori-mobile-ironsource-applovin@0.0.3
chadori-mobile-ironsource-chartboost@0.0.3
chadori-mobile-ironsource-facebook@0.0.3
chadori-mobile-ironsource-fyber@0.0.3
chadori-mobile-ironsource-hyprmx@0.0.3
chadori-mobile-ironsource-inmobi@0.0.3
chadori-mobile-ironsource-maio@0.0.3
chadori-mobile-ironsource-pangle@0.0.3
chadori-mobile-ironsource-tapjoy@0.0.3
chadori-mobile-ironsource-unityads@0.0.3
chadori-mobile-ironsource-vungle@0.0.3
```

**Comment by Chadori** [comment]
Hi, would you also whitelist these plugin versions, I need these for iOS 14.
Thank you!
```
chadori-mobile-ironsource@0.0.4
chadori-mobile-ironsource-debug@0.0.4
chadori-mobile-ironsource-adcolony@0.0.3
chadori-mobile-ironsource-admob@0.0.3
chadori-mobile-ironsource-amazon@0.0.3
chadori-mobile-ironsource-applovin@0.0.3
chadori-mobile-ironsource-chartboost@0.0.3
chadori-mobile-ironsource-facebook@0.0.3
chadori-mobile-ironsource-fyber@0.0.3
chadori-mobile-ironsource-hyprmx@0.0.3
chadori-mobile-ironsource-inmobi@0.0.3
chadori-mobile-ironsource-maio@0.0.3
chadori-mobile-ironsource-pangle@0.0.3
chadori-mobile-ironsource-tapjoy@0.0.3
chadori-mobile-ironsource-unityads@0.0.3
chadori-mobile-ironsource-vungle@0.0.3
```

**Comment by AshleyScirra** [comment]
How often are you going to need to request updates to this many plugins? I hope it's not too often - this creates a lot of security review work, and we're a small team with limited resources.

**Comment by Chadori** [comment]
Hi, sorry for the bother. 😅
For the IronSource plugins, it's hopefully only going to be the last time this year, it's only for iOS 14.
I don't think I would update it if it wasn't required. But, I guess you can defer them (IronSource) gradually.

Although, for the rest, I'd appreciate if you can whitelist them the usual way, since those are needed.
```
cordova-launch-review@4.0.0
cordova-plugin-appsflyer-sdk@6.0.30
chadori-mobile-masteriap@1.0.1
```

**Comment by AshleyScirra** [comment]
The build service allowlist has now been updated for all 19 requests.
