### ISSUE TITLE
Whitelist UnityAds3 cordova Plugin - 3.4.8  And UnityAds2 Depreciation

### ISSUE THREAD

**Issue by artemisoftnian** [Scirra/Construct-3-bugs#4237]
Hi, long time no see!!

I just Publish a new UnityAds cordova Plugin. Can it be whitelisted?, I'll be greatfull.

NEW - Cordova Plugin UnityAds3 (3.4.8)
https://www.npmjs.com/package/com-artemisoftnian-plugins-unityads3

----------------------------------------------------------------------------

OLD - Cordova Plugin UnityAds2 (Now Depreciated) Can be removed from server as its beeing depreciated and  no longer in maintence.
https://www.npmjs.com/package/com-artemisoftnian-plugins-unityads2

UnityAds2 Construct Plugin its beeing depreciated too, replaced by the new UnityAds3 Construct 3 Addon

Thanks in advance.

**Comment by KekGames** [comment]
Considering how few free monetization plugins exist for C3, I hope we don't have to wait for months for this plugin to be whitelisted

**Comment by artemisoftnian** [comment]
Hi Ashley, 

Had to update the Cordova Plugin UnityAds3 to  3.5.0 as a new version of the UnityAds SDK came out with mayor improvements.  I did some other maintenance to the plugin also as I have to update anyways.

If there is not any important changes in the UnityAds SDK, this will be last version for a while.

[https://www.npmjs.com/package/com-artemisoftnian-plugins-unityads3](https://www.npmjs.com/package/com-artemisoftnian-plugins-unityads3)

changelog:

## [3.5.0] - 2020-10-6
### Added
- Added UnityAds SDK 3.5.0

### Maintenace Changes
- Removed references of ARCore from AndrodManifest
- README modified to reseamble the ARCore changes.  
- Remove unessesary javascript logging.

Thanks in advance.

**Comment by AshleyScirra** [comment]
The build service allowlist has been updated with `com-artemisoftnian-plugins-unityads3@3.5.0`.

**Comment by artemisoftnian** [comment]
Hi Ashley, 

I just update the plugin  to 3.6.0 : **com-artemisoftnian-plugins-unityads3@3.6.0**
This update address a bug in the SKAdNetwork functionality in 3.4.8 and 3.5 that prohibits these versions from correctly passing SKAdNetwork. 

Thanks as always

**Comment by AshleyScirra** [comment]
Please file a new issue. Closed issues are not monitored.
