### ISSUE TITLE
The "Remove Tile" action from "Tile map brush editor" doesnt work for Auto 47 brushes

### ISSUE THREAD

**Issue by cb130felix** [Scirra/Construct-3-bugs#4238]
##  Problem description

When editing tilemap brushes for auto tilling, the "Remove Tile" action, for removing one of the multiple possibilities from a configured tile, doesn't work. This is only for auto 47 brushes.

## Attach a .c3p

Link: https://drive.google.com/file/d/1QTZ3lY7SqXh843SxuxU2TDCbqK4YxuA-/view?usp=sharing

## Steps to reproduce

1. Open attached project
2. Select tilemap object and go to the Tilemap bar
3. In the tilmeap bar, select "Edit brushes" under brush options
4. Select the "Brush 0" and select the auto tile with Id 0 (top left one)
5. There are three diferent tiles configured for this auto-tile. Right click in one of them and select "remove tile".

## Observed result

Tile seted for auto tilling is not removed.

## Expected result

For the tile seted to be removed

## More details

I'm on latest beta (r216) and chrome. Looks like removing a configured tile works for auto 16 brushes, but doesn't for auto 47.

**Comment by DiegoScirra** [comment]
This will be fixed in the beta cycle after the next stable release
