### ISSUE TITLE
Platform Behavior Jump Bug

### ISSUE THREAD

**Issue by EydiavHamri** [Scirra/Construct-3-bugs#4239]
## Problem description

When an object with platform behavior is standing on an object with solid behavior, and another solid object moving upward comes up under the player's feet and pushes them up, the player becomes unable to jump while being pushed up. The bug can only be reproduced when platform object gravity is set very high. In this example 4000.

Works in r189.2 broke in r190.

## Attach a .c3p

[PlatformerJumpBug.zip](https://github.com/Scirra/Construct-3-bugs/files/5259818/PlatformerJumpBug.zip)

## Steps to reproduce

1. Stand on blue platform. Wait until green platform comes up.
2. When standing on green platform. Press up while green platform is moving upward.

## Observed result

Player is unable to jump while green platform is moving up.

## Expected result

I expected player to be able to jump, like when standing on the green platform without being pushed up from the blue one.

## More details

Problems begin to occur when player gravity is bigger than ca. 2540

**Affected browsers/platforms:** 
Chrome
Edge
Firefox

**First affected release:** 
Worked in r189.2 broke in r190 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.121
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
C3 release: r216 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 423 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Repro that opens in r189.2: [project.zip](https://github.com/Scirra/Construct-3-bugs/files/5260773/project.zip)
Seems likely it's a regression caused by this change in r190:

> Platform behavior: increased precision when detecting floor landing (possible breaking change)

which was done for issue #3631. It's incredibly difficult to change the Platform behavior without causing regressions, so marking difficult.

**Comment by brushfe** [comment]
In case it's helpful: if you jump off the blue platform, but land on the green platform as it rises, you can continue to jump freely on the green platform (it only seems to cause a problem when the green platform carries you off the blue platform.)

**Comment by EydiavHamri** [comment]
Yeah, that's what I was trying to communicate but perhaps not very well. Thanks for clarifying.

**Comment by AshleyScirra** [comment]
OK, these cases are pretty difficult and often risky to change, but I've adjusted the platform floor detection code for the next beta which I think should fix this. Previously the platform behavior did not recognise the solid moving upwards as being the new floor, and just kept nudging the player out of it, which is why you couldn't jump (since you can only jump when the behavior recognises that you're standing on the floor). I've updated the floor tracking code to identify the upwards moving solid as the new floor, which should handle this.

**Comment by EydiavHamri** [comment]
Great! Thank you! Looking forward to testing it out.
