### ISSUE TITLE
Set Text Object Height from TextHeight using BB Code doesn't work.

### ISSUE THREAD

**Issue by andygilbert29** [Scirra/Construct-3-bugs#4241]
## Problem description

When you use BB code to set font size, and then set the Text object height based on TextHeight it has no effect, does nothing.

## Attach a .c3p

[BBCODE_BUG.zip](https://github.com/Scirra/Construct-3-bugs/files/5268040/BBCODE_BUG.zip)

## Steps to reproduce

1. Use BB code to set font size
2. Set the Text object height to the TextHeight
3. Run

## Observed result

Height not set.

## Expected result

The height to adjust to fit the text in, like the width does.

## More details

Chrome was used in this instance.

R210.2

## System details

<details><summary>View details</summary>

</details>

**Comment by andygilbert29** [comment]
Sorry Wrong version, I meant 210.2 Stable.

**Comment by ariepert** [comment]
Ashley, I was just about to post a bug report, but I think it is related to this one. And is also part of a thread you commented on today: 
[https://www.construct.net/en/forum/construct-3/how-do-i-8/correct-text-height-155398#forumPost1023503](url)
The bug appears to be that when BBcode is enabled, the text in the Text object gets shifted down. You can clearly see this if you start a new project, add a Text object, then click the Enable BBcode checkbox off and on. You will see the text move up and down. So, when people set the Text object to its TextHeight, it is offset by the amount that the BBcode option adds, and not all the text shows.

**Comment by andygilbert29** [comment]
> Ashley, I was just about to post a bug report, but I think it is related to this one. And is also part of a thread you commented on today:
> [https://www.construct.net/en/forum/construct-3/how-do-i-8/correct-text-height-155398#forumPost1023503](url)
> The bug appears to be that when BBcode is enabled, the text in the Text object gets shifted down. You can clearly see this if you start a new project, add a Text object, then click the Enable BBcode checkbox off and on. You will see the text move up and down. So, when people set the Text object to its TextHeight, it is offset by the amount that the BBcode option adds, and not all the text shows.

I believe there is a separate bug report for that issue, which may be related deep down but definitely isn’t the same issue here. From my testing setting the Text Height does not change at all regardless of the BB code size, it’s not just the offset.

**Comment by AshleyScirra** [comment]
Slightly clearer repro visualising the reported text size: 
[bbcode-text-size.zip](https://github.com/Scirra/Construct-3-bugs/files/5327021/bbcode-text-size.zip)

**Comment by AshleyScirra** [comment]
OK, fixed for next beta. The problem is TextHeight did not take in to account BBcode size tags.

Note that setting the text size to TextWidth / TextHeight is not guaranteed to display all the text - for more details see [this forum post](https://www.construct.net/en/forum/construct-3/how-do-i-8/correct-text-height-155398#forumPost1023573).
