### ISSUE TITLE
Functions containing loops called from expression not returning values

### ISSUE THREAD

**Issue by Raadiolained** [Scirra/Construct-3-bugs#4243]
## Problem description
I have a loop that runs an action where another loop is called from expression, but it does not return value or is triggered at the wrong time. "Wait for complete" causes other things to hang. See project file.
I attached the debug function to steps which prints out results and shows what order it should be. Order of execution/printout is nothing like it should be.

## Attach a .c3p

https://drive.google.com/file/d/1ZA73lkadR781hUufXNhE52ySyu1MP7tt/view?usp=sharing

## Steps to reproduce

Run the project and look "DeBugger" array or console to see order of execution and return values. See if "TestArray" gets filled with a function return value.

Or make your own:

1. Make a function(1) that runs loop and count the loops.

2. In that loop, fill in a counted array value with a function(2) (as an expression) that also runs loops.

3.  Make function(2) calculate a number from loops and set it as a return value. 

Watch how order of things runs havoc.

## Observed result

Order of execution of loops is wrong.
Function return value gets ignored.
Array "TestArray" is filled with emptyness as function return value is empty (not NaN, just nothing).
"Wait for complete" makes the event stop.

## Expected result
Value from each function is printed out according to its called-order.
Function return value is accepted.
Array "TestArray" is filled with function return values.

## More details

If this is not a bug, It would be useful for newcomers to explain how function loops act in expressions and what the order of execution is, as C3 is targeted towards artists and non-coder types. Documentation on Functions briefly mentions recursion, but is not clear weather or not rest of the action waits for the loop. 

**Affected browsers/platforms:** 

Chrome/Edge, haven't tested with others.

**First affected release:** 

r210.2 stable, haven't been on earlier versions.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.121
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 97 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks like a mistake in your events. The function SubFunctionLoop is set to return a string, but you return a number. Because it's the wrong type, it ignores the return value and returns an empty string.

If you clone the function, swap it to return a number, and update the references to the one that returns a number, it seems to print numbers instead of empty strings.
