### ISSUE TITLE
Export to Desktop became very slow with newest nw.js version

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#4245]
## Problem description

I am not sure if this is a third party bug or if you can do anything about it. At the moment I cant do a Desktop export that works fine, but it still works with older nw.js version. 

-with v_0.44 (chromium80) it works fine. 

-with v_0.45 (chromium81) the bugreport file works fine. My own project doestn run smooth on powerfull mac, on a old windows machine it still works fine.

-with v_0.48 (chromium85) it doesn't work at all. Very jerky, it changes between 15 fps and 60 fps
I tried to send you the exports, but as they are more than 200MB I can attach just the Bugreport c3p file
## Attach a .c3p

[a_JS_bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5281972/a_JS_bug.c3p.zip)

## Steps to reproduce

1.export to Desktop nj.js
2.make two versions, one with js v0.44 and one with js v0.48
3.run the app

## Observed result

the v.0.44 works fluently
v.0.48 not
## Expected result

the newest version should run smooth too

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Browser: Chrome
Browser version: 85.0.4183.121
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
C3 release: r217 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 4.3 gb (1.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
Works fine for me - both NW.js 0.44 and 0.48 run at a perfectly smooth 60 FPS on my Windows 10 64-bit system.

We can't do anything about this kind of report anyway - we don't make NW.js, so the best you can do is wait for the next update and see if that fixes it, or report it to the NW.js developers directly. But in the past this usually comes down to some combination of GPU driver bugs and Chrome's driver blacklist, which ultimately needs to be fixed by the GPU vendor.
