### ISSUE TITLE
SpriteFont colour value can't be replaced (Chrome)

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4246]
## Problem description

Chrome: When changing the colour value of a SpriteFont, selecting black (0,0,0) from the colour gradient causes problems when you try to adjust the numeric colour value below.

Safari's colour picker is different, and doesn't get affected by this.

## Attach a .c3p

https://drive.google.com/file/d/1higGx4mYGspJyYhocQWg058_l0ebCuNK/view?usp=sharing

## Steps to reproduce

1. Open the project. 
2. Select the SpriteFont object
3. Click the Colour Picker in Properties
4. Select black from the colour gradient. Make sure the RGB values are 0,0,0.
5. Press TAB twice to move the cursor to the Red (R) numeric value
6. The cursor will be in the wrong position. 
7. Type in a new number. The existing value will not be replaced.

## Observed result

The cursor is wedged against the right-hand side of the input field. Inputting new numbers doesn't replace the existing value.

## Expected result

Pressing TAB to enter the R/G/B value fields should highlight the current value, and allow user input to replace it with a new value. 

## More details

Cursor in wrong position: https://drive.google.com/file/d/197OgCty6rHAPsHViA6QqWt9aO8RHcS88/view?usp=sharing

Typing in new value: https://drive.google.com/file/d/1LVmZv9zh46FpVkof8qn1dAC5ucY3Tl9R/view?usp=sharing

**Affected browsers/platforms:**  Chrome 85.0.4183.121 (Desktop)

**First affected release:** r217 Beta 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.121
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
C3 release: r217 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 140 gb
Storage usage (approx): 348 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics 655
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
The color picker is managed by the browser (in this case Chrome). We have no control over it so I'm afraid we cannot do anything about reports like these.

It seems to work correctly for me anyway: tabbing to the "R" value field shows the cursor blinking to the right of the number. This doesn't seem to be obviously wrong, and I can successfully hit backspace and type in a new number, and everything seems to work fine.

If you still think Chrome is doing something wrong you can report it to Google at crbug.com, and it should affect any website using a color input.
