### ISSUE TITLE
Cut (Cmd+X) doesn't work in Project Bar search field 

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4247]
## Problem description

After entering a term into the search field above the Project Bar, using Cmd+X to cut that text instead cuts whatever object/layout/etc is selected in the Project Bar. Because the contents of the Project Bar are hidden by the search field's results, you have no idea that you're cutting something from your project - especially when you think you should be cutting the highlighted text.  

## Attach a .c3p

Any project; I've used the Kiwi Story game demo.

## Steps to reproduce

1. Open the Kiwi Story game demo.
2. In the search field above the Project Bar, type "test" and press enter/return. No items will be found.
3. Press Cmd+A or use the mouse to highlight the word "test" in the search bar.
4. Press Cmd+X to cut the text. 

## Observed result

A prompt appears confirming the deletion of a selected layout (or whatever you've last highlighted in the Project Bar)

## Expected result

The text from the search field should be moved to the clipboard.

## More details

**Affected browsers/platforms:** Chrome 85, Safari 14

**First affected release:** This problem exists in 217, but does _not_ exist in 210. 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.121
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
C3 release: r217 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 140 gb
Storage usage (approx): 357 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics 655
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report - I also found a related issue involving using arrow keys to move the selection while a search is active. I've fixed this for the next release - we have a stable release due tomorrow, and late changes are sometimes risky, but I think this is both significant enough and the fix low-risk enough to warrant inclusion in that release.

**Comment by brushfe** [comment]
Awesome, glad it was helpful!
