### ISSUE TITLE
Cloud Save/Load Dialog Doesn't Show All Files

### ISSUE THREAD

**Issue by whscienceteacher** [Scirra/Construct-3-bugs#4248]
## Problem description

Cloud Save/Load Dialog doesn't show all files if there are too many files and folder. (Only tested on OneDrive because I don't have another cloud service with enough Construct 2 or 3 files in it.)

I believe it is a maximum of 72 or 73 files and folders based on a hand count of two folders with this problem. 

## Attach a .c3p

N/A the problem is in the cloud dialog.

## Steps to reproduce

1. Have a folder with a lot of c3ps capxs or folders.
2. Try to open something in the folder.

## Observed result

It will not show all the files. Files later in the alphabet don't show. 

## Expected result

Show all the files. 

## More details

**Affected browsers/platforms:** Tested on Windows 10 1909, Edge Chromium and Firefox

**First affected release:** Unknown, tested on current Stable.

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 87.0.644.4
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4265.0 Safari/537.36 Edg/87.0.644.4
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 142 gb
Storage usage (approx): 215 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
How many files do you have on the entire OneDrive account? I think there may be some limit related to that.

**Comment by whscienceteacher** [comment]
Do you mean in all folder in my OneDrive together? No idea, hundreds of thousands probably? I don't think the number in the entire OneDrive is the issue though because individual folders that don't have many c3ps don't have a problem, even if they have a lot of other files. 

In each of the folders that cause trouble I have about 100-150 c3p/capx/folders.

**Comment by AshleyScirra** [comment]
Thanks, I've made a change for the next release to work around the limit. It's quite difficult to test very large folders so marking to verify once the release is out.

**Comment by AshleyScirra** [comment]
@whscienceteacher - r219 is now out and should fix this - can you verify it's working as expected there?

**Comment by whscienceteacher** [comment]
I checked. It loads them all now. Thanks so much.

**Comment by AshleyScirra** [comment]
Great, thanks for confirming.
