### ISSUE TITLE
Xcode crash after trying to open the project 

### ISSUE THREAD

**Issue by karimlahbach** [Scirra/Construct-3-bugs#4249]
## Attach a .c3p
Any project can reproduce the problem

## Steps to reproduce

1. just open any project 
2. export to IOS and choose XCode project
3. open the file in XCode last version

## Observed result
XCode close and crash

## Expected result
to open the project

## More details

**Affected browsers/platforms:*last version of chrome/mac OS Catalina 10.15.7* 

**First affected release:*stable and the Last beta r217* 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I've made a few exports with Xcode 12 and they all have worked fine so far.

I'm afraid Apple make Xcode and so any issues with it will need to be reported to them instead.
