### ISSUE TITLE
Crash while moving event groups

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#425]
## Problem description
App crashed while moving an event group up the list.  It was moving sub group Player 1 above sub group Player 2.  It's not reproducible with those steps and this file with a few attempts.

[Bitmen.zip](https://github.com/Scirra/Construct-3-bugs/files/1047909/Bitmen.zip)

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*
Error report information
Type: assertion failure
Message: no sequence number assigned
Stack: Error at Function.ǃm.ǃNGH (https://editor.construct.net/r33/main.js:2:200367) at t (https://editor.construct.net/r33/main.js:2:171849) at window.assert (https://editor.construct.net/r33/main.js:2:172256) at n.ǃmI_ (https://editor.construct.net/r33/main.js:61:253273) at ǃNCP (https://editor.construct.net/r33/main.js:61:253371) at Array.sort (native) at window.ǃNuD.ǃNCy (https://editor.construct.net/r33/components/editors/eventSheetView/eventSheetView.js:1:10788) at window.ǃNuD.ǃNmL (https://editor.construct.net/r33/components/editors/eventSheetView/eventSheetView.js:1:22953) at window.ǃNuD.ǃNpf (https://editor.construct.net/r33/components/editors/eventSheetView/eventSheetView.js:1:22419) at window.ǃNuD.ǃNW (https://editor.construct.net/r33/components/editors/eventSheetView/eventSheetView.js:1:19599)
Construct 3 version: r33
URL: https://editor.construct.net/
Date: Fri Jun 02 2017 10:07:49 GMT-0400 (Eastern Daylight Time)
Uptime: 4469.7 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.82
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.82 Safari/537.36
C3 release: r33

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
Sorry, in this case the crash report isn't too useful on its own, and without steps to reproduce there's little we can do.
