### ISSUE TITLE
Dark theme - Sprite palette is empty, cannot choose colours

### ISSUE THREAD

**Issue by plinkieant** [Scirra/Construct-3-bugs#4252]
When using dark theme it looks like the palette selection for the Sprite object is broken, empty. I cannot select any colours.

## Steps to reproduce

1. Set Dark theme and create a new project
2. Create a sprite and look at the palette in the image editor
3.

## Observed result

The palette is empty, shows some grey squares

## Expected result

I expect the colour wheel to be there so I can select colours, this seems to be fine on the default theme

## More details

Screenshot : https://www.dropbox.com/s/y24u0w3jbcob0pw/palette_dark.jpg?dl=0

**Affected browsers/platforms:** 

**First affected release:** 
Stable 210.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's working just fine for me:

![color-palette-dark](https://user-images.githubusercontent.com/768723/94552582-038a4f80-024f-11eb-90b9-f6f97a8e47a9.png)

Please note always follow the full bug report guidelines, since in this case we cannot further investigate the issue, so we close it.
