### ISSUE TITLE
Pressing Enter/Return should accept "Update to Latest Beta" prompt

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4253]
## Problem description

When C3 launches and you are prompted to accept/decline the latest beta update, pressing Enter/Return does _not_ accept it, despite "Update" being the highlighted default option.

## Attach a .c3p

(Editor-based issue)

## Steps to reproduce

1. Open editor.construct.net
2. In Settings, opt-in for beta release notifications.
3. Close the browser window, return to editor.construct.net
4. When prompted to accept/decline the latest beta update, press Enter/Return.

## Observed result

The latest beta does not apply; instead, C3 remains on the latest stable release.

## Expected result

C3 switches to the latest beta version.

## More details

Screenshot of default highlight, indicating that pressing Enter/Return will choose the "Update" option: https://drive.google.com/file/d/1EGtK37Q9lmt7oQB7Dx4rVGpdyiBRKCg5/view?usp=sharing

**Affected browsers/platforms:** Chrome 85, Safari 14

**First affected release:** Stable 210 (upgrade prompt to 217)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.121
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 140 gb
Storage usage (approx): 356 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics 655
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
Thanks, this was actually a general problem with some confirmation prompts, which also affected the update prompt. Fixed for next beta (but note you won't see a working prompt until the beta after that).
