### ISSUE TITLE
1.Reload from original source - does not work  2.  c3 crash

### ISSUE THREAD

**Issue by MihaMS** [Scirra/Construct-3-bugs#4254]
Hello!
related to https://github.com/Scirra/Construct-3-bugs/issues/4183
- this bug not fixed completely (https://github.com/Scirra/Construct-3-bugs/issues/4183)
Updated Construct to a new version (r218) and - yes crash is gone, but when I press "Reload from original source" - sprite is not updates... :(
It looks like Construct updates it not from Original source but from it's last saved state - which is wrong.

how to reproduce:

    Create new project and save it as folder
    Create Sprite and load any image
    Change image (in other program like photoshop)
    Press "Reload from Original source"

    sprite is not updated.

P.S.: found also another crash: Create new roject --> Save as folder --> Create Sprite --> press "Update from original source" = CRASH.
Tryed this from Chrome (not Standalone) with Enabled experimental features.
https://drive.google.com/file/d/1s4ZgTYyb6J6jVkCe020YZ_qd1AP-04Zk/view?usp=sharing

**Comment by AshleyScirra** [comment]
Please follow all the bug report guidelines. It may not be possible to investigate your report if you omit the details we ask for - we need them to help you.

**Comment by DiegoScirra** [comment]
@MihaMS

Construct can only access the files saved in the project folder. This means that in order for external changes to be picked up, you need to edit the image files found in the **images folder of your project**. If you edit the file you loaded in the Animations editor from elsewhere in your file system, Construct won't pick up those changes. 

I will look into the other issue.

**Comment by DiegoScirra** [comment]
The crash will be fixed in the next beta release.

**Comment by MihaMS** [comment]
> Construct can only access the files saved in the project folder. This means that in order for external changes to be picked up, you need to edit the image files found in the **images folder of your project**. If you edit the file you loaded in the Animations editor from elsewhere in your file system, Construct won't pick up those changes.
> 

I'm really sad to hear that. Earlier Construct can reload sprites from outside his project folder, which was very handy, now I need to find some workaround to re-upload files with different naming convention and placed in a separate folders by "logic elements" (interface, characters, level graphics e.t.c...) in one C3 folder with thousands files and do this quite often... (((
@AshleyScirra is there no way to return old functionality for this (to allow access C3 to another folder and it sub-folders)?

**Comment by AshleyScirra** [comment]
Unfortunately the security measures in browser permissions mean it's impossible to do it the same way it worked before. We have to find a different workflow to work within the permissions model.
