### ISSUE TITLE
Desktop Build crashes on log in

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#4258]
## Problem description

When I entered my username and password and pressed "Login" button, the program crashed. 
At least 3 other people on the forum reported the same issue in the past few days.

## Attach a .c3p

N/A

## Steps to reproduce

1. Try to login in Desktop build.

## Observed result

Program closes, nwjs process keeps running in Task Manager.

## More details

Clearing absolutely everything and updating NWJS to the latest version didn't help. 
Changing my password on the Construct website somehow fixed the issue.

**Affected browsers/platforms:**

Desktop App

**First affected release:** 210

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.48.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.48.2 (like Chrome/85.0.4183.83)
C3 release: r218 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 43 gb
Storage usage (approx): 247 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
It's working fine for me here with NW.js 0.48.3 and C3 r218. I tried logging in a couple of times with a test account, entering the username/password each time, and it successfully logged in every time.

**Comment by dop2000** [comment]
Here's what triggered this bug for me - 
Most of the time I'm using stable release only. That time I installed and launched beta version of Desktop App (r217). Tried to login there and it crashed. 
After that I tried to run the stable version, discovered that it logged me out, tried to log back in, and it crashed too..

**Comment by AshleyScirra** [comment]
JavaScript code can't normally crash the browser process, so I would guess this is a NW.js bug. Maybe it will be fixed by the next update.

**Comment by nerdError** [comment]
> JavaScript code can't normally crash the browser process, so I would guess this is a NW.js bug. Maybe it will be fixed by the next update.

As of today, this problem has also appeared for me. And up to this point, everything worked well. I didn't change either C3 (r218) or nw.js (v0.48.3) builds

NW.js creates a log with text:

`[1007/120324.995:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: Operation completed successfully. (0x0)`

**Comment by AshleyScirra** [comment]
According to @nerdError this is now fixed in NW.js 0.48.4, and there's also NW.js 0.49.0 just released with the Chrome 86 update. Can anyone else confirm if these versions resolve the issue?

**Comment by AshleyScirra** [comment]
Nobody is responding so closing on the assumption it works now.

**Comment by nerdError** [comment]
Exactly today, the problem appeared again on version 0.48.4. The only not usual thing I did today was to try out the new version of Construct 3 r220 in Chrome. Perhaps this is due to logging in to your Scirra account elsewhere?
