### ISSUE TITLE
Browser plugin event "On Back Button" closes the application.

### ISSUE THREAD

**Issue by Fakerock** [Scirra/Construct-3-bugs#4259]
## Problem description

A bug after the update, which added support for API level 29. On some smartphones (Redmi note 5 and some others) there is a problem with the Browser plugin event "On Back Button". When you press the back button on your smartphone, the app exits completely, and does not perform the prescribed actions.

Most devices do not have this problem. But some users of my apps are reporting a problem.

## Attach a .c3p

[apk](https://drive.google.com/file/d/1pUn-SzNPJChyEsi1z-o-UYWDXgrD6elk/view?usp=sharing)
[cp3](https://drive.google.com/file/d/1uB-mYThnvRt6tYL8WW1d8CX_m7XkULt1/view?usp=sharing)

## Steps to reproduce

1. Tap a sprite to go to Screen 2.
2. Press the Back on smartphone hardware button.

## Observed result

On some smartphones, the application is closed immediately.

## Expected result

Correct working of Back button

## More details

**Affected browsers/platforms:** Chrome/Firefox/Android 9

**First affected release:**  worked in  r204 but broke in  r210

</details>

**Comment by Fakerock** [comment]
After opening the Share dialog, everything works correctly.

**Comment by AshleyScirra** [comment]
I can reproduce on a Pixel 3 running Android 11. It's probably a regression since it used to work. Our code couldn't be simpler, we just listen for a "backbutton" event. So I think it's an issue with Cordova. I filed an issue with them here and will follow up there: https://github.com/apache/cordova-android/issues/1106

**Comment by Boulerzzz** [comment]
Seems like the cordova splashscreen plugin could cause this behavior. As a workaround commenting line 103 in SplashScreen.java solves this issue.
