### ISSUE TITLE
Crash when clicking on erase tool in tilemap window without selecting a tile first

### ISSUE THREAD

**Issue by BernardWrangle** [Scirra/Construct-3-bugs#426]
## Problem description

Clicking on the eraser tool in the tilemap window without selecting a tile first causes C3 to crash. It's not huge deal, if I select a tile then the eraser tool everything works as expected. Just thought you'd like to know!

## Attach a .c3p

https://drive.google.com/open?id=0B2mi7Z0OwMDqb3JhUU1lVXpRTjg

## Steps to reproduce

1. Select tilemap 'Tilemap_hard_forest'
2. Without selecting a tile, click the eraser tool
3. C3 crashes

## Observed result

Immediately after clicking the eraser tool C3 crashes

## Expected result

To be able to erase tiles.

## Affected browsers

* Chrome: yes
* Firefox: can't use
* Edge: don't use
* Safari: don't use

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r33/components/bars/tilemapBar/tilemapBar.js, line 1, col 20599
Message: Uncaught TypeError: Cannot read property '0' of undefined
Stack: TypeError: Cannot read property '0' of undefined at e.window.ǃ_N.ǃNmJ (https://editor.construct.net/r33/components/bars/tilemapBar/tilemapBar.js:1:20599) at window.ǃ_N.ǃrI.ǃNzG (https://editor.construct.net/r33/components/bars/tilemapBar/tilemapBar.js:1:35118) at window.ǃ_N.ǃrI.ǃNNP (https://editor.construct.net/r33/components/bars/tilemapBar/tilemapBar.js:1:26173) at e.window.ǃ_N.ǃNNc (https://editor.construct.net/r33/components/bars/tilemapBar/tilemapBar.js:1:7717) at e.window.ǃ_N.ǃKM (https://editor.construct.net/r33/components/bars/tilemapBar/tilemapBar.js:1:7222) at ǃm.Event.ǃNqZ.ǃNqd (https://editor.construct.net/r33/main.js:2:254173) at ǃm.ǃN.ǃ_i.dispatchEvent (https://editor.construct.net/r33/main.js:2:252652) at ǃm.ǃN.ǃCW.ǃmzp.ǃst.ǃmun (https://editor.construct.net/r33/main.js:2:507514) at ǃm.ǃN.ǃCW.ǃmzp.ǃst.ǃmuG (https://editor.construct.net/r33/main.js:2:506853) at ǃm.ǃN.ǃCW.ǃmzp.ǃst.ǃmuW (https://editor.construct.net/r33/main.js:2:507259)
Construct 3 version: r33
URL: https://editor.construct.net/
Date: Fri Jun 02 2017 10:23:56 GMT-0400 (Eastern Daylight Time)
Uptime: 144.4 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r33

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon(TM) HD 7450 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by DiegoScirra** [comment]
This should be working properly in r34, which was just released. You can go check it out.

**Comment by BernardWrangle** [comment]
Looks like it works, thanks again.
