### ISSUE TITLE
Crash: Renaming animation with the same name and escaping 

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#4261]
## Problem description

In animation editor, if renaming an animation name to the same name as an existing animation it will cause a crash if you also press Escape.

When I realized the name was the same, I instinictively pressed the Escape key thinking it would quit renaming but it closed the window and crashed.

## Example

![image](https://user-images.githubusercontent.com/5744908/94877028-b69bb880-049c-11eb-91ad-4c6f0401a42b.png)

![image](https://user-images.githubusercontent.com/5744908/94877056-d206c380-049c-11eb-8d90-da32e6ffac93.png)

![image](https://user-images.githubusercontent.com/5744908/94877087-e5199380-049c-11eb-8c30-66df7873e2b3.png)

## Attach a .c3p

[animation.zip](https://github.com/Scirra/Construct-3-bugs/files/5315439/animation.zip)

(it's just a sprite with 2 animations)

## Steps to reproduce

1. Rename the 2nd animation to "Animation 1"
2. While renaming press Escape key

## Observed result

Crash

## Expected result

Stop renaming and revert to previous name

## More details

**Affected browsers/platforms:** NWJS latest, Windows 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'getComputedStyle' of null @ TypeError: Cannot read property 'getComputedStyle' of null at new (https://editor.construct.net/r218/main.js:1098:63) at Function.l (https://editor.construct.net/r218/main.js:294:207) at Function.Pa (https://editor.construct.net/r218/main.js:1150:176) at g.Rl (https://editor.construct.net/r218/projectResources.js:169:181) at Object.m6c (https://editor.construct.net/r218/projectResources.js:1707:379) at https://editor.construct.net/r218/projectResources.js:1699:376
Stack: TypeError: Cannot read property 'getComputedStyle' of null at new (https://editor.construct.net/r218/main.js:1098:63) at Function.l (https://editor.construct.net/r218/main.js:294:207) at Function.Pa (https://editor.construct.net/r218/main.js:1150:176) at g.Rl (https://editor.construct.net/r218/projectResources.js:169:181) at Object.m6c (https://editor.construct.net/r218/projectResources.js:1707:379) at https://editor.construct.net/r218/projectResources.js:1699:376
Construct 3 version: r218
URL: https://editor.construct.net/r218/
Date: Fri Oct 02 2020 10:48:48 GMT+1000 (Australian Eastern Standard Time)
Uptime: 273 s

Platform information
Browser: NW.js
Browser version: 0.48.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.48.3 (like Chrome/85.0.4183.121)
C3 release: r218 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
