### ISSUE TITLE
"Unable to save project" prompt appears

### ISSUE THREAD

**Issue by 619rm** [Scirra/Construct-3-bugs#4266]
## Problem description

The "UNABLE TO SAVE PROJECT, TRY CHECKING YOU HAVE PERMISSION TO SAVE"! is appearing quite often when using Local Project Folder system.

Please check below screenshot to get more idea about the error.

![1](https://user-images.githubusercontent.com/72460529/95229807-ab3ee900-081e-11eb-96f4-d478747c82af.jpg)

## Attach a .c3p

Tested with C3 built in templated KIWI Project

## Steps to reproduce

1- Open any project, here I opened C3 default Kiwi Project

2- Save it as Project Folder (C:\Kiwi)

3- Firstly I changed something minor then hit the save button, It saved successfully.

4- Duplicated a layout and hit the save button, here the error messages pop.

5- After pressing OK (from the error message) and re-hit the save button, now it saves successfully.

## Observed result

In Chrome 85 Browser Console , got the following error 

"[Project] Exception saving: DOMException: A requested file main.js:2060 or directory could not be found at the time an operation was processed." 

Please check the bellow attached screenshot

![2](https://user-images.githubusercontent.com/72460529/95229818-aed27000-081e-11eb-90d2-1ff155a798f1.jpg)

## Expected result

It have to save the file without giving the warning.

## More details
Once if I press "OK" then hit the save button it saves successfully but after some while when I hit the save button (again) it once again it appears. (though not every time but quite often for the same open project).

**Affected browsers/platforms:** 

Tested on Chrome 85 with Native File System API enabled.

**First affected release:** 

Current Stable r218 & Current Beta r219

## System details

Platform information
Browser: Chrome
Browser version: 85.0.4183.121
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
C3 release: r218 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 481 mb
Storage usage (approx): 247 kb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 610 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
Thanks, this was quite tough to track down but it should be fixed for the next beta.
