### ISSUE TITLE
Embedded HTML IFrame does not run On Android Build

### ISSUE THREAD

**Issue by simonpaulkeating** [Scirra/Construct-3-bugs#4267]
The project will run a html project file as an iframe in a regular web build but NOT when built to Android device.

## Attach a .c3p
[Verge3d_Test_V2.zip](https://github.com/Scirra/Construct-3-bugs/files/5339281/Verge3d_Test_V2.zip)

## Steps to reproduce

1. Build the attached project as Android Debug apk
2. Notice how the c3_interface_test.html file is not loaded

NOTE: this will not work in preview mode as the project points at a local file  (on my PC when previewing)

## Observed result

 c3_interface_test.html file is not loaded or doesn't run. There are no errors in the console.

## Expected result

The html file should load correctly. If you build the same project and export for web the embedded html file works correctly.

## More details
Tested in Chrome as a web build which works great but will not work on my ANdroid device (Huwaii Mate 10)

A working web build can be seen here: http://www.pigobo.com/TestC3/TestV3d_v2/index.html

My original forum post: https://www.construct.net/en/forum/construct-3/how-do-i-8/run-embedded-html-iframe-155400

**Affected browsers/platforms:** 

**First affected release:** 
All versions that I have tested seem to have this issue . Currently using r218 stable.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r218 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 141 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The provided project uses a range of third party addons:

- Plugin ProUI (aekiro_proui) by Aekiro
- Plugin jsZip (Massive_Cube_jsZip) by Massive_Cube
- Behavior Game Object (aekiro_gameobject) by Aekiro
- Behavior Dialog (aekiro_dialog) by Aekiro

Please remove these as per the bug report guidelines, since they could be causing the problem. In particular I recently fixed a different issue and verified that iframes do display correctly on Android in issue #3976.

**Comment by simonpaulkeating** [comment]
[Uploading TestV3d_NoAddons.zip…]()
Hi, I have attached the same file without any external addons. Everything else is the same.

**Comment by simonpaulkeating** [comment]
Apologies, I have attached the same file without any external addons. Everything else is the same.
[TestV3d_NoAddons.zip](https://github.com/Scirra/Construct-3-bugs/files/5358793/TestV3d_NoAddons.zip)

**Comment by simonpaulkeating** [comment]
Do I need to re-submit a completely new issue for this? Cheers

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines:

> Please do not reply to closed bug reports. Instead, please file a new report, and make sure you follow all the guidelines and provide any missing information.

**Comment by simonpaulkeating** [comment]
OKay Thanks. Will remember for the future. I have done this. Cheers
