### ISSUE TITLE
Error using Tiled Background with 'Pixel rounding' enabled in r219.2

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#4268]
## Problem description

Tiled background throwing error in renderer reference wi is not defined

## Attach a .c3p

https://drive.google.com/file/d/1EMnS670W0Secp8HyU6MfdgALc0vCCR4k/view?usp=sharing
## Steps to reproduce

1. add tiled background
2. run game
3.

## Observed result

console.error

Uncaught (in promise) ReferenceError: wi is not defined
    at TiledBgInstance._DrawStandard (instance.js:4)
    at TiledBgInstance.Draw (instance.js:4)
    at Instance.Draw (instance.js:8)
    at Layer._DrawInstance (layer.js:30)
    at Layer._DrawInstances (layer.js:28)
    at Layer.Draw (layer.js:26)
    at Layout.Draw (layout.js:28)
    at C3Runtime.Render (runtime.js:73)
    at C3Runtime.Tick (runtime.js:61)
    at C3Runtime.Start (runtime.js:35)

## Expected result

the game renders tiled background

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 85.0.564.68
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 Edg/85.0.564.68
C3 release: r219.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 298 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Looks like a regression in r219.2 when using the 'Pixel rounding' setting. You can work around it for now by turning that off. Fixed for the next release, but leaving issue open since I expect others might run in to this.

**Comment by BonzerKitten** [comment]
Thanks for the quick fix! I was about to report this issue as well.
