### ISSUE TITLE
Event Sheet Adjustment is Quite Awkward

### ISSUE THREAD

**Issue by Scott943** [Scirra/Construct-3-bugs#427]
## Problem description

*Enter a concise description of your problem here*
 In Chrome, it is particularly difficult to adjust the size of events in the event sheet - for me, it takes about five attempts to get the adjustment cursor to pop up! It's just a very small problem, but can become quite annoying with prolonged use in my opinion. This may just be Chrome's way of handling things, but I would like to see it fixed! : 
![untitled](https://cloud.githubusercontent.com/assets/8079722/26732506/b808d5b6-47af-11e7-87a7-c0f5ee945ec3.png)
The cursor does not change to adjustment easily

## Affected browsers

* Chrome: yes
* Firefox: 
* Edge: 
* Safari:

**Comment by AshleyScirra** [comment]
It works every time for me here, but I have noticed Chrome seems to have a bug where the mouse cursor doesn't always change correctly. It might be that it's possible to drag if you click in the right place, even if the right cursor isn't showing. Does it work if you ignore the mouse cursor and just try dragging from the separator locations?

**Comment by Scott943** [comment]
Yes, it does work easier that way. I guess it's just a bug with Chrome then. :) Thanks Ashley

**Comment by AshleyScirra** [comment]
Will leave open until I get round to filing a bug with Chrome

**Comment by AshleyScirra** [comment]
@Scott943 - can you still reproduce this? All we've ever found that could be related to this is that if you have dev tools open, the mouse cursor doesn't change properly any more. But if dev tools is closed, it looks like it works fine, and in that case I've never seen anything wrong with the cursor changing. We're trying to close off some old issues, so let us know if you still have any issues.

**Comment by AshleyScirra** [comment]
Had needinfo tag for a couple of months with no response so closing
