### ISSUE TITLE
Image "bleeding" with TiledBackground object

### ISSUE THREAD

**Issue by Rhindon** [Scirra/Construct-3-bugs#4271]
## Problem description

Regarding tiled background objects...
There is noticeable bleeding of pixels at the edges of the object in the layout and beyond images of other objects of the same width.
When compared to an image of the same dimensions, I noticed that the first image appears to be "bleeding" past the image that's on top. The actual OBJECTS are different widths when doing a 1x1 comparison. (Per my .C3P file) the "HunterStatusFrame" tiled background object is 60x30 while the "HunterStatusBars" tiled background object is 70x30.

In the image, itself, the "HunterStatusBars" object is also 60x30 with an extra 10 pixels of blank space added so that I can easily adjust that object as it resides behind the "HunterStatusBars" object in the layout. That little blank space is like a "custom handle" so I can pick it without having to constantly move the "Frames" object all the time.

This is when I discovered the image for the "Bars" object has a single pixel that bleeds past the "Frames" image even though the images (not the objects at 1x1 sizing) are the same. The "Bars" object, also when at a 1x1 sizing, begins to repeat the left edge of the image, as if bleeding over before the actual width of the object is extended and the tiled image continues.

The layout is set to "lock to grid" and the layout grid cells are set to 10x10. Since all size values of the objects are multiples of ten and the images in the objects are also drawn at multiples of ten, I don't understand why these pixel bleeding details are arising.

## Attach a .c3p

[Tilebackground image bleed.zip](https://github.com/Scirra/Construct-3-bugs/files/5351409/Tilebackground.image.bleed.zip)

Included in this zip file is a copy of my .C3P file and a simple MS Paint image of two screenshots to try to better illustrate the issue I'm describing. I hope that helps.

## Steps to reproduce

1. Create tiled background object.
2. Include a blank space in the image, itself, up to the edge of the image's full width. Make sure the other side of the image is drawn to that edge. (So if the blank space is on the right, make sure the left edge has something drawn right up to the left edge.)
3. In the layout, side the tiled background object to its 1x1 size as depicted in the image editor. Do not resize the object so that the image begins to tile-repeat.
4. Note that there is a small edge of the left side of the original image that already begins to "bleed" at the right side of the object as if the tile were repeating (yet the object is sized only according to the object's original image size.

## Observed result

The image begins to tile-repeat even though the object's size is still exactly that of the image's original (base) dimensions. If the object is 20x20 and the original image is 20x20, there is bleeding of the image at the edge of the object as if the objects, for example, 21x20.

## Expected result

I expect to see only the original image since the object is the same size as the original image. Since I have a blank space at the right side of the original image (along with whatever else I have drawn), I expect to see only a blank space there. Not a pixel's worth of the left edge of the image being repeated at the right.

## More details
The image transform details are:
Offset X and Y: 0
Image scale X and Y: 100%
Image angle: 0°

Properties (for both the tiled background object in question and the other tiled background object that is related to the issue at hand):
Origin: Top-left
Wrap horizontal and vertical: Repeat

**Affected browsers/platforms:**
Currently, I am only using Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**First affected release:**

The issue was first noticed in C3 r219.2 beta

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.121
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
C3 release: r219.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 142 gb
Storage usage (approx): 240 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's not a bug - it's a normal result in computer graphics. Unless you have pixel perfect rendering, a wrapping image will repeat at the edge of an object due to rendering fractional pixels.

This is one of the reasons there is the "Clamp to edge" repeat modes - you can use it to turn off horizontal repeating and only have vertical repeating, eliminating the seam.
