### ISSUE TITLE
Drawing canvases look odd with different layout scales

### ISSUE THREAD

**Issue by 1AL3X** [Scirra/Construct-3-bugs#4274]
## Problem description

When the layout scale is a neither an integer nor an integer devided by two, some adjacent drawing canvases will have a small separation between them

## Attach a .c3p

[Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5358313/Bug.zip)

## Steps to reproduce

1. Set the layout scale command to your non-integer of choice
2. Run the project

## Observed result

There is a black rectangle bisected by vertical white lines

## Expected result

I expected to see a solid black rectangle

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
I am unsure, sorry.
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.131
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Chrome OS
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.625
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 13310.91.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.131 Safari/537.36
C3 release: r218 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 1.1 gb (7.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 515 (SKL GT2)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's not a bug. It's a normal result in computer graphics: you cannot guarantee that adjacent objects will appear without seams when you use fractional scaling. It works correctly when you set the layout scale to 5 instead of 5.01. (By setting the scale to 5.01, you defeat the "integer" part of "letterbox integer scale", and the integer scaling is a requirement for pixel-perfect display.)
