### ISSUE TITLE
Sprites deleted in projects saved as Project Folders are not deleted from disk

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#4275]
## Problem description

Sprites deleted in projects saved as Local Folders are not deleted from disk

## Attach a .c3p

- [AsSingleFile.c3p](https://github.com/Scirra/Construct-3-bugs/files/5358990/AsSingleFile.c3p.zip)
- [AsProjectFolder.zip](https://github.com/Scirra/Construct-3-bugs/files/5358991/AsProjectFolder.zip)

## Steps to reproduce

1. Create a new project
2. Create a sprite
3. Save the project as Project Folder
4. Delete the sprite
5. Save again the project
6. Check the folder: the sprite image is still present

## Observed result

![image](https://user-images.githubusercontent.com/23579630/95655762-cef97c00-0b09-11eb-924a-481ea931cc38.png)

## Expected result

The deleted sprite image is no longer present

## More details

**Affected browsers/platforms:** Chrome, Windows 10

**First affected release:** I do not know. I think it has always been like that.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next release.
