### ISSUE TITLE
Tilemap brush configuration is missing when you clone the object

### ISSUE THREAD

**Issue by rafaeldematos** [Scirra/Construct-3-bugs#4276]
Problem description
Tilemap brush configuration is missing when you clone the object

Attach a .c3p
https://drive.google.com/file/d/1EVeKYhFMDewVTVTuaFB1Q82HKei3Oaiv/view?usp=sharing

Steps to reproduce
add tilemap 
set some tiles to a new brush or to the default one
clone this tilemap
see the cloned object missing this brush configuration

Expected result
See the exact same brush configuration in both objects

More details
Affected browsers/platforms:

First affected release:
Any

System details
Nome do Sistema Operacional	Microsoft Windows 10 Pro
Versão	10.0.19041 Compilação 19041
Outra Descrição do Sistema Operacional 	Não disponível
Fabricante do Sistema Operacional	Microsoft Corporation
Nome do sistema	DESKTOP-5C3SO59
Fabricante do sistema	Dell Inc.
Modelo do sistema	Inspiron 5490
Tipo do sistema	PC baseado em X64
SKU do sistema	0955
Processador	Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz, 2304 Mhz, 4 Núcleo(s), 8 Processador(es) Lógico(s)
Versão/data do BIOS	Dell Inc. 1.11.0, 13/08/2020
Versão do SMBIOS	3.2
Versão do Controlador Incorporado	255.255
Modo da BIOS	UEFI
Fabricante da BaseBoard	Dell Inc.
Produto BaseBoard	0YMVR1
Versão da BaseBoard	A00
Função da Plataforma	Móvel
Estado da Inicialização Segura	Ativado
Configuração PCR7	Avaliação Necessária para Exibição
Pasta do Windows	C:\WINDOWS
Pasta do sistema	C:\WINDOWS\system32
Dispositivo de inicialização	\Device\HarddiskVolume1
Localidade	Brasil
Camada de Abstração de Hardware	Versão = "10.0.19041.488"
Nome de usuário	DESKTOP-5C3SO59\fmato
Fuso horário	Hora oficial do Brasil
Memória Física (RAM) Instalada	16,0 GB
Memória física total	15,8 GB
Memória física disponível	7,57 GB
Memória virtual total	18,2 GB
Memória virtual disponível	7,81 GB
Espaço do arquivo de paginação	2,38 GB
Arquivo de paginação	C:\pagefile.sys
Proteção de DMA de Kernel	Desativado
Segurança baseada em virtualização	Não habilitado
Suporte à Criptografia de Dispositivo	Avaliação Necessária para Exibição
Hyper-V - Extensões de Modo Monitor VM	Sim
Hyper-V - Extensões de Conversão de Endereços de Segundo Nível	Sim
Hyper-V - Virtualização Habilitada no Firmware	Sim
Hyper-V - Proteção de Execução de Dados	Sim

**Comment by DiegoScirra** [comment]
A quick update, cloning from the Project Bar does keep the brushes in the clone, this is already in the latest beta. Cloning from the context menu of the layout view does not work though.

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta release **r221**.
