### ISSUE TITLE
Local browser saves not showing in Open Project/Open Recent dialog box

### ISSUE THREAD

**Issue by NicotineLL** [Scirra/Construct-3-bugs#4277]
## Problem description

Last night I worked on two small projects and saved then using the Local browser save feature. This is how I've setup my saves in Construct 3 options. Today when I look for them, they were nowhere to be seen in the Open project dialog box, they were not in Open recent either. Since I have backup enabled I decided to download that from the Menu -> Settings -> Download browser saves and check whether they will be in there.

In Construct 3 I have 33 saved projects including auto saves, checking the backup folder I downloaded I see 39 files including the metadata.json file. On further investigation when I read through the metadata I've noticed 5 projects named similar to "unknown_a0ecb61c7dce0282".

Example entry from metadata.json

{
"type":"file",
"id":"a0ecb61c7dce0282",
"name":"unknown_a0ecb61c7dce0282",
"ext":"",
"date":1602416950490,
"parent":"ad99dc24fdebb365",
"size":79835
}

I found the file with that name "a0ecb61c7dce0282", added .c3p extension to it (by default the backups don't have it for some reason) and opened it in Construct, and to my surprise it was one of the projects from last night that was missing.

## Attach a .c3p

There is no .c3p file to be added, since it's not relevant to the issue.

## Steps to reproduce

I sincerely have no idea how to reproduce this error.

## Observed result

Saved projects are not visible on Open project/Open recent dialog boxes

## Expected result

Saved projects must be visible on Open project/Open recent dialog boxes

## More details

**Affected browsers/platforms:** Opera / Windows 10

**First affected release:** r218 stable

## System details

Platform information
Browser: Opera
Browser version: 71.0.3770.228
Browser engine: Chromium
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.228
C3 release: r218 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 514 mb (0.4%)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Persistent storage is not available. Local storage could be deleted by the browser.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024

Extensions:
EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:
Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:
WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
I just tried it and it works fine for me.

I'm afraid without steps to reproduce the problem it's impossible to investigate this. That's why the steps are required when filing an issue. If you can find a way to reproduce it, please file a new issue providing the steps.
