### ISSUE TITLE
case variable name sort error

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4278]
## Problem description

Sometimes, this strictly alphabetical sorting of variable names may be correct in machine-thinking logic. But in terms of the way humans think, it may not be so friendly..

I'm not sure if this is a bug or if it should be submitted as a suggestion.In my opinion, maybe he should be more intelligent.

He should put capital names first.

1. ~~or He should put local variables before global variables.~~
2. ~~or Maybe he should do a Category. (local > global > expression)~~ 

## Observed result

![Imgur](https://i.imgur.com/oglosc5.jpg)

1. energy_init
2. Energy_Max
3. Energy_Now
4. energy_target
5. energy_temp
6. Energy_Type

## Expected result

1. Energy_Max
2. Energy_Now
3. Energy_Type
4. energy_init
5. energy_target
6. energy_temp

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's currently by design that we use case-insensitive sorting. Most features in Construct are case-insensitive by design, because otherwise it will confuse beginners who don't expect case sensitivity to be a problem.
