### ISSUE TITLE
Iphone Audio Stops working when exit and return to browser

### ISSUE THREAD

**Issue by PapitoMyKing** [Scirra/Construct-3-bugs#4280]
**## Problem description**

EVERY time you exit the browser and come back in the audio stops working.

**## Attach a .c3p**

drive.google.com/file/d/13f8Bxn0P2VGZDIQxxNC7_lT6EcdQYXWP/view

**## Steps to reproduce**

1. Be in a web game.
2. Open another app.
3. Return.

**## Observed result**

No audio.

**## Expected result**

Working audio.

**## More details**

Video:
https://www.dropbox.com/s/n5hg5jrap62vrx4/IMG_6082.mov?dl=0

Bugs on iPhone XR, iPhone SE, 7plus, iPhone 6. Safari and chrome.

Minimal project on itchio:
papitomyking.itch.io/episode-7-minimal

**Comment by AshleyScirra** [comment]
I can reproduce on iOS 14. I'm pretty sure this used to work, were you testing on iOS 14 on all the devices you tried as well?

I assume this is a regression in iOS 14 so I filed a bug with Apple here: https://bugs.webkit.org/show_bug.cgi?id=217606
