### ISSUE TITLE
Iphone vibrate mode mutes audio

### ISSUE THREAD

**Issue by PapitoMyKing** [Scirra/Construct-3-bugs#4281]
## Problem description

If the iPhone is in vibrate mode, it disables the audio which is not common - for example, you can still watch a video with sound on an iPhone while it is in vibrate/silent mode, so why not these construct games?

## Attach a .c3p

drive.google.com/file/d/13f8Bxn0P2VGZDIQxxNC7_lT6EcdQYXWP/view

## Steps to reproduce

1. Turn vibrate mode on.
2. Play the game

## Observed result

No audio.

## Expected result

Working audio.

## More details

Bugs on iPhone XR, iPhone SE, 7plus, iPhone 6. Safari and chrome.

Minimal project on itchio:
papitomyking.itch.io/episode-7-minimal

**Comment by AshleyScirra** [comment]
What do you mean by "vibrate mode" specifically? iOS has a ton of settings for notifications, volume, vibration, silent mode, etc.

**Comment by AshleyScirra** [comment]
Note issue #3477 has some related discussion about silent mode - the conclusion being this is something controlled by iOS and that we can't change. (I'd also argue that by definition no audio should be played in "silent mode".)

**Comment by natebluewizard** [comment]
This also matches unity exports, and i believe expected behaviour. If your phone is in silent mode, no audio should play.

**Comment by AshleyScirra** [comment]
No response from the submitter and I strongly suspect this is related to the discussion in issue #3477 - besides, "no audio played in silent mode" hardly sounds like a bug, it's what silent mode is for, so closing.
