### ISSUE TITLE
Bug on physical, the box didn't fall when the bottom box was drag out

### ISSUE THREAD

**Issue by kimarutaGM** [Scirra/Construct-3-bugs#4282]
**Problem description:**
 Physic of the box (Box B) next to the bottom box (Box A)  was wrong. This box (Box B) did not fall when box A was move out.

**Attach a .c3p**
https://drive.google.com/file/d/1v38926S0oSnL2jiFf8ner3ULhZ-tykPI/view?usp=sharing

**Video:**
https://drive.google.com/file/d/1ynmxBeQuTqdFFHYm0oVtpGnoaAFKCLah/view?usp=sharing

**Steps to reproduce**
Add some of box with physic and the bottom box was set to Immovable. 
Preview it, waiting for all box finish to fall, wait about 1 or 2 second  and move the bottom box. All box should fall down. but nothing happen after that.
Note: If we destroy bottom box, all box will fall down normally.

**Expected result**
All box above bottom box should fall down immediately when bottom box was move out of balance point.

System details
Operating System: Windows 10 Enterprise 2016 LTSB 64-bit (10.0, Build 14393) (14393.rs1_release.200901-1914)
BIOS: P3.30
Processor: AMD Ryzen 3 3200G with Radeon Vega Graphics     (4 CPUs), ~3.6GHz
DirectX Version: DirectX 12
DX Setup Parameters: Not found
User DPI Setting: Using System DPI
System DPI Setting: 96 DPI (100 percent)
DWM DPI Scaling: Disabled
Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
[testPhysic.zip](https://github.com/Scirra/Construct-3-bugs/files/5362782/testPhysic.zip)
DxDiag Version: 10.00.14393.2457 64bit Unicode

**Comment by AshleyScirra** [comment]
You set an object to "immovable" and then move it. That doesn't make sense, so the physics engine doesn't handle it.

See also the section about using other behaviors to move physics objects in the [Physics basics tutorial](https://www.construct.net/en/tutorials/physics-construct-basics-6).
