### ISSUE TITLE
Timeline - screen is not updated when moving between keyframes in Editing mode

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#4285]
## Problem description

When in Editing mode, clicking to select another keyframe, or using keyframe navigation buttons on the toolbar, does not update/refresh the object position and its properties on the layout. 

## Demo project

It's not really needed, but here is the link:
https://www.dropbox.com/s/mozcoaf5v91oqqn/TimelineDemo.c3p?dl=0

## Steps to reproduce

1. Open any timeline. 
2. Enable Edit mode.
3. Try to navigate to another keyframe.

## Observed result

Please see this picture:

![Example](https://i.postimg.cc/5ttxPdyv/timeline-bug1.png)

Keyframe 1 is selected, however object position is still at keyframe #2
All the highlighted properties on the left panel also show wrong values.

To refresh position and values, you need to briefly disable/enable Editing mode.

## Expected result

Everything should be refreshed automatically.

## More details

**Affected browsers/platforms:** Chrome/Firefox/Desktop

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.48.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.48.2 (like Chrome/85.0.4183.83)
C3 release: r218 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 39 gb
Storage usage (approx): 259 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment]
A few small changes will appear in the next beta to address this.

A feature already exists to preview a timeline by dragging the current time marker (red line) while while pressing Ctrl/Cmd. To make this behaviour more consistent, the following actions will also preview the timeline to the current time:

1) Pressing Ctrl/Cmd while clicking on the time ruler.
2) Pressing Ctrl/Cmd while using the toolbar buttons to move between keyframes.
3) Using the keyboard shortcuts to move between keyframes.

Additionally, selecting a keyframe by clicking on it will move the time marker to it and preview the timeline.
