### ISSUE TITLE
Update notifications

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4290]
## Problem description

Getting beta updates notifications when updates notification is set to Stable releases.

## Attach a .c3p

Not c3p related

## Steps to reproduce

1. Set construct to show updates for stable release only
2. Set the package.json to an earlier beta version. 
3. Launch construct 3

## Observed result

Update notification for a newer beta version keeps popping up with every launch.

## Expected result

Updates to pop up only for stable release, or for betas if I choose it on the setting.

## More details

I usually use the latest beta, so I only noticed it recently when I choose to stay on r219, and not update to r219.2 or r220 because of some of the issues they have.

P.S, maybe you should allow the beta version to load c3p files saved in newer versions, add a disclaimer about it if you're worried (maybe even block it to only the next version if you are really worried, i.e. if I'm using r219 and trying to open a project saved in r220), but give us the choice.
Currently you're locking people from continue working if they accidently saved on a new broken version.
I know I can edit the project file and change it myself, but many other don't know that, and you don't advertise it anywhere either.

**Affected browsers/platforms:** NWjs

**First affected release:** As far as I know since day one for me.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. If you use a beta release, it will always notify you about new beta releases. The setting only applies to stable releases.
