### ISSUE TITLE
TURRET BEHAVIOR FOR FAMILIES

### ISSUE THREAD

**Issue by BroGames86** [Scirra/Construct-3-bugs#4291]
## Problem description

 Good afternoon! 
 
I found such a mistake: if a family is given the turret behavior, then when assigning each family member different targets for attack - all family members still use the same targets. This is very critical for many projects. I ask you to help. the same problem in c2

## Attach a .c3p 
[Bag turret.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5378327/Bag.turret.c3p.zip)

## Steps to reproduce

1. combine sprites into a family
2. give the family a turret behavior
3. assign each family member different objects for purposes

## Observed result

 all family members have the same goals

## Expected result

 all family members should have different goals

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. There is only one turret behavior, on the family, so both 'Add target' actions affect the whole family.

**Comment by BroGames86** [comment]
> This is currently by design. There is only one turret behavior, on the family, so both 'Add target' actions affect the whole family.

Well. I hope to review this feature in the future.
