### ISSUE TITLE
C3 folder project gets corrupted after some interactions with the animation editor

### ISSUE THREAD

**Issue by cb130felix** [Scirra/Construct-3-bugs#4293]
## Problem description

Well, pretty much the tittle. More info in the steps to reproduce

## Attach a .c3p

Link to a project saved using the steps bellow: https://drive.google.com/file/d/1vXE1ZzZvD3mpAGWxt2lCxQbwPLQg08nt/view?usp=sharing

## Steps to reproduce

1. Create new project
2. Add a sprite to the project
3. Save the project as a project folder
4. Close the project
5. Open the project again
6. Open the sprite in the Animation editor and change the sprite animation name
7. Save the project again (as a project folder)
8. Try opening the project and it'll be corrupted

## Observed result

Projects is corrupted after changing sprite animation name.

## Expected result
 
For the project to not get corupted.

## More details

- C3 Version: r200.2
- Browser used: Chrome (uptodate version)

**Comment by AshleyScirra** [comment]
This is the same issue as in #4292, and I've verified the fix for that also fixes these steps.
