### ISSUE TITLE
Mesh deformation: In relative mode, -1 should not be used for 'unchanged' in texture position

### ISSUE THREAD

**Issue by simstratic** [Scirra/Construct-3-bugs#4294]
## Problem description

In the 'Set mesh point' action, setting -1 in texture position uses the unchanged position, but this does not make sense in relative mode. In relative mode, -1 can be a valid position, for example with a 2x2 mesh, setting column/row [1,0] to texture position [-1,0] should translate to absolute texture position [0,0]. But under the current implementation it translates to absolute texture position [1,0].

## Attach a .c3p

https://drive.google.com/file/d/1FQjwTQscTM1H2ECgt4GI9XL9s3NsuRwQ/view?usp=sharing

## Steps to reproduce

1. Preview the project
2.
3.

## Observed result

The 'Piggy' sprite is smeared because the corners have the same texture position.

## Expected result

The texture of the 'Piggy' sprite should be flipped horizontally.

## More details

The attached example works if you change the texture position from -1 to -1.1 (or any value less than -1), but this is technically incorrect and not intuitive to the user.

@AshleyScirra asked me to submit this issue following my post on the forums:

https://www.construct.net/en/forum/construct-3/general-discussion-7/mesh-tips-feedback-155689#forumPost1024568

**Affected browsers/platforms:** 
N/A

**First affected release:** 
r219 beta

## System details
N/A

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, updated for next beta.
