### ISSUE TITLE
Unable to open project with pick unique ID anywhere in the event sheet

### ISSUE THREAD

**Issue by CrazyBooze** [Scirra/Construct-3-bugs#4295]
## Problem description

I created a project and was able to save and open it in the latest beta (220.2) until I added a condition "Pick by unique ID". After saving and attempting to load the project it threw an error.

## Attach a .c3p

https://www.dropbox.com/s/ab3fuyizlfodq9z/SPS_Construct.c3p?dl=1

## Steps to reproduce

1. Create a file and add a sprite condition "Pick by Unique ID"
2. Save and load the same project
3. It crashes

## Observed result

C3 Crash upon opening the project file

## Expected result

To be able to open the project and resume work

## More details

**Affected browsers/platforms:** 

**First affected release:** 

Seems to be exclusive to r220-2?

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: missing child after uid lookup
Stack: Error at Function.OTa (https://editor.construct.net/r220-2/main.js:286:41) at https://editor.construct.net/r220-2/main.js:201:149 at Object.Zf (https://editor.construct.net/r220-2/projectResources.js:259:1) at n.Zf (https://editor.construct.net/r220-2/projectResources.js:221:340) at n.Zf (https://editor.construct.net/r220-2/projectResources.js:113:214) at xa.xeb (https://editor.construct.net/r220-2/projectResources.js:973:171) at xa.hbc (https://editor.construct.net/r220-2/projectResources.js:1042:303) at async Object.MY (https://editor.construct.net/r220-2/main.js:2053:47) at async m.Sga (https://editor.construct.net/r220-2/main.js:2152:60) at async Function.e3 (https://editor.construct.net/r220-2/main.js:2126:321)
Construct 3 version: r220.2
URL: https://editor.construct.net/r220-2/
Date: Sat Oct 17 2020 02:40:04 GMT-0400 (Eastern Daylight Time)
Uptime: 228.2 s

Platform information
Browser: Edge
Browser version: 86.0.622.38
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36 Edg/86.0.622.38
C3 release: r220.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
