### ISSUE TITLE
Bug with hierarchy and saving/loading

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4297]
## Problem description

Loading a saved state of a layout with hierarchy fails if loading from a different layout (note, if I try to load the save without switching layouts it works.

## Attach a .c3p

[hierarchySaveBug.zip](https://github.com/Scirra/Construct-3-bugs/files/5397269/hierarchySaveBug.zip)

## Steps to reproduce

1. Click save.
2. Click load.
3. Look at browser console for error log.

## Observed result

While it switches to the right layout, it doesn't manage to load the whole state and it affects other objects too.

## Expected result

Loading should work.

## More details

**Affected browsers/platforms:** NWjs 0.49.0

**First affected release:**  r220-2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
