### ISSUE TITLE
The construct HTML5 build fails to load in an iframe, throwing Error: Invalid size

### ISSUE THREAD

**Issue by hamidalitintash** [Scirra/Construct-3-bugs#4298]
## Problem description

I have a construct project that is loaded in an iframe of React component. The project loads fine most of the time but fails intermittently. The console displays Error: Invalid size.

The issue is similar to the one below:
https://github.com/Scirra/Construct-3-bugs/issues/3295

## Attach a .c3p

[Example.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5397398/Example.c3p.zip)

## Steps to reproduce

1. Create an iframe
2. Use the Construct3 build url to load the project into iframe.
3. Console displays error (see system details below for stack trace) and a grey screen in displayed in iframe.

## Observed result

Grey screen in iframe

## Expected result

The construct3 build should be loaded into iframe and display the first layout.

## More details

**Affected browsers/platforms:** 

Chrome

**First affected release:** 

I am using r220.2beta

## System details

<details><summary>View details</summary>

Uncaught (in promise) Error: invalid size
at CanvasManager.SetSize (c3runtime.js:2240)
at CanvasManager.CreateCanvas (c3runtime.js:2236)
at async C3Runtime._InitialiseCanvas (c3runtime.js:2319)
at async C3Runtime.Init (c3runtime.js:2308)
at async RuntimeInterface._InitDOM (main.js:36)
at async RuntimeInterface._Init (main.js:26)

</details>
@AshleyScirra

**Comment by hamidalitintash** [comment]
@AshleyScirra

**Comment by AshleyScirra** [comment]
I exported the project and ran it in an iframe, and it worked just fine.

To investigate this report you'd need to provide the HTML code you're using for the iframe.

I would guess you are doing something like creating a zero-sized iframe, which is not valid.

**Comment by mohsin-tintash** [comment]
We are using React to render the iframe:

```
<div class="unlocked-3-dashboard-content-area">
    <div style="display: contents;">
        <div class="gameplayer-container">
            <iframe title="Unlocked3-Professors" src="https://unlocked3-construct.tegunlocked.com/" class="responsive-iframe"></iframe>
        </div>
    </div>
<div>
```
Css behind the iframe:

```
.gameplayer-container .responsive-iframe {
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    width: 100%;
    height: 100%;
    max-height: 76vh;
}
```

The parent div:

```
.unlocked-3-dashboard-content-area {
    width: 100%;
    height: 66vh;
}
```


Is there anything else needed to debug this issue?

**Comment by AshleyScirra** [comment]
Please provide a minimal reproduction that we can run. We can't test snippets of code, we need a complete working demonstration.

**Comment by mohsin-tintash** [comment]
Use this [Game Link](http://unlocked3-testing.s3-website.us-east-2.amazonaws.com/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJSbE5jXC9aazJ1ckxPVWR6a0d1TW03TDJyOEgyQ0I5WHlGQzZoT00ybXhUaz0iLCJpc3MiOiJodHRwczpcL1wvdGVndW5sb2NrZWQuY29tXC8iLCJpYXQiOjE2MDEyOTk0NjgsIm5iZiI6MTYwMTI5OTQ2OCwiZXhwIjoxNjAzODkxNDY4LCJ1c2VyIjp7InVzZXJfaWQiOiI3ODk4ODAiLCJmdWxsX25hbWUiOiJNb2hzaW4gSGF5YXQiLCJlbWFpbCI6Im1vaHNpbmhheWF0MTA0QGdtYWlsLmNvbSJ9fQ.X-8y0yoBLUB9D0Srl-aXKQRW5LaInqvI-AgrbsjZjnA) to login and play around in the application. This is the staging server.

**Comment by AshleyScirra** [comment]
It seems to work fine there. Besides we can't debug production apps post-export, we need the project file and a minimal test case for the embedding page with the iframe that causes the problem, since a trivial case works fine.

**Comment by AshleyScirra** [comment]
There's been no response for about a week and there's still no reliable reproduction provided. I put a speculative fix in to r222 which may help. If you still have trouble with r222+ please file a new issue following all the guidelines, in particular providing a minimal complete test case that I can run myself and reliably demonstrates the problem.
