### ISSUE TITLE
Cordova/XCode Export is not recognizing certain export settings.

### ISSUE THREAD

**Issue by natebluewizard** [Scirra/Construct-3-bugs#4299]
## Problem description

When exporting even a brand new project to an xcode workspace, certain settings defined in the Construct 3 project are being ignored:

1. "Hide Status Bar" option from the export window in Construct 3 is not working, when opening the xcode workspace, the "Hide Status Bar" option on the General tab is unchecked and needs to be manually enabled.

2. Icon definitions in the Construct 3 project are not being translated to actual Xcode workspace icons, and the xcode workspace is using the 'default' cordova icon that then must be manually overridden. 

## Attach a .c3p

Any project will demonstrate these issues, but I've attached a blank project for easy export here:

http://www.3030.ca/proto/bugrep/TestiOS.c3p

## Steps to reproduce

1. Build demo project to Xcode / iOS 
2. Ensure "Hide Status Bar" is checked & default construct icons are set.
3. Open resulting xcode workspace.

## Observed result

Xcode workspace has cordova icons & Hide Status Bar is NOT checked.

## Expected result

XCode workspace should have Construct icons & Hide Status bar should be checked / enabled.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 86.0.4240.80
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36
C3 release: r218 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 989 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro Vega 20 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
The "Hide status bar" option seems to be working fine for me - if I tick it on export, then run the exported Xcode project on an iOS device, the status bar is hidden.

As for icons, it seems none of the stock icons match the variety of icon sizes Xcode uses, so the defaults are filled with stock Cordova icons. However if you add an icon in the size and format Xcode uses, it is automatically included. For example I added an icon named `icon60@2x.png` sized 120x120, and it was used in Images.xcassets. Like most platforms, it requires so many icons in such a wide range of formats, with requirements that regularly change over time. So we long ago gave up trying to track all the icon formats in Construct itself. We already [advise to manually adjust icons after export](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/icons-splash). So you can either add all the possible icons that iOS needs to your Construct project, or just edit them in Xcode after export.
