### ISSUE TITLE
Construct 3 won't run

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#43]
## Problem description

Thoughout the day I get a lot of problems with ERR_FAILED errors. If I do a hard refresh in Chrome, the site will start. On a similar note, I have a lot of problems with preview failing. I get some junk in the window, and a bunch of errors in the log.

Clearing the "Application:Clear site data" doesn't fix it. I have to clear out the entire days cache via "Clear browsing data...".

## Attach a .c3p

N/A - any of the demo apps will do it.

## Steps to reproduce

Unsure.

## Observed result

Screen shots & console logs attached.

## Expected result

Not that ;)

## Affected browsers

N/A

## System details

<details><summary>View details</summary>

![previewfails](https://cloud.githubusercontent.com/assets/4206641/24824846/37b488f0-1bc8-11e7-9969-a70448fe8987.jpg)
[editor.construct.net-1491617845140.log.txt](https://github.com/Scirra/Construct-3-bugs/files/907168/editor.construct.net-1491617845140.log.txt)
[console-1491617769806.log.txt](https://github.com/Scirra/Construct-3-bugs/files/907169/console-1491617769806.log.txt)
</details>

**Comment by AshleyScirra** [comment]
It looks like the browser failed to fetch the main document. Perhaps you were offline or the server was briefly unavailable. Normally it would be in the offline cache preventing this but I guess you got unlucky and hit this when the editor hadn't managed to offline cache yet.

Anyways without repro steps not a lot we can do, so closing.
