### ISSUE TITLE
Particles with a sprite object - set color

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4300]
## Problem description

First, note that you can't unset the sprite object from the particle plugin in the layout editor, once you set it, it's for good.

Changing the color of the particles plugin with a sprite object set, does not affect the color of the sprite object in run-time, in the editor and live preview it does seem to work.
Also If I change the sprite object color in the layout editor, it will work, but not if I change the color in run-time.
Either way, I think it's better that the main particle plugin will control the color and not the sprite object, though I think both should work in run-time.

## Attach a .c3p

[particlesObject.zip](https://github.com/Scirra/Construct-3-bugs/files/5401550/particlesObject.zip)

## Steps to reproduce

1. Try live preview and see the particle is black
2. Try normal preview, see it is red.
3. See start of layout actions to set color not working.

## Observed result

Particle sprite object is sprayed with original color

## Expected result

Particle sprite object should use the particle plugin colors settings.

## More details

**Affected browsers/platforms:** NWjs 0.49.0

**First affected release:** Probably a long time ago.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.

Note:

> First, note that you can't unset the sprite object from the particle plugin in the layout editor, once you set it, it's for good.

Click in a space in the object picker dialog to unselect the chosen object, then click OK. That clears the chosen object back to empty restoring the default particles display.
