### ISSUE TITLE
Projects using the "project folder" option takes several minutes to save if they have a lot of files

### ISSUE THREAD

**Issue by cb130felix** [Scirra/Construct-3-bugs#4301]
## Problem description

Pretty much the tittle. I'm working on a big project (as in it have lot's of files) in C3 and today after we got the release 221 it took me more than 5 minutes to be able to save the project using the folder project option. 
It's also worth noticing that I'm only editing a few layouts and sheets before trying to save, but even in this situation it takes a lot of time for the save process to finish.

## Attach a .c3p

I'll be providing the project I'm working on instead of a minimal project since this problem should occur (I think) only with big projects. That said, recreating the issue shouldn't be a problem, the steps to reproduce should be simple enough.
The shared file is a comercial project so I'm not alowed to share it publicly. It'll be needed to request access to the file before being able to download it. I also ask to please not share this project with others. Sorry for the incovenience!

The project shared is not a .c3p file, instead it was saved in the format of "project folder" and is inside a .zip file.
Project file: https://drive.google.com/file/d/19vkzYOezi_lXyqShHLw63MEa9ZkepKHx/view?usp=sharing

## Steps to reproduce

After downloading the file in Gdrive

1. Extract the project (content in the downloaded .zip file) in a folder
2. Open the project in C3 r221 using the "Open local project folder" option
3. Add a empty comment into any event sheet in the project
4. Save the project using the "Save" option

## Observed result

Saving the project can take up to several minutes even with only few file changes.

## Expected result

For the saving process to be faster (at least in the case where few files were changed)

## More details

C3 release with the issue is the r221
I tried using both web version with chrome v86.0.4240.111 and the desktop version with NWjs v0.49.0 but I had the issue with saving taking too long to complete in both of them.

P.S.: For some reason sometimes construct 3 will get stuck while trying to open that project. This happens only with this project and it's seemgly at random. This is another issue not related to the one described in this topic, but I think it's worth letting you guys know about it.

**Comment by rilem** [comment]
Can confirm the same on the Mighty Goose project. Doing a simple object drag and saving causes a save of 30-60 seconds.

Was planning on creating creating a sample project with dummy files but haven't gotten around to it yet.

**Comment by cb130felix** [comment]
Request access received and granted!

**Comment by AshleyScirra** [comment]
I could not open the provided project - it uses a range of third-party addons I don't have installed. (This is one of the reasons why the bug report guidelines say we don't want your full project, we need a minimal repro, or a basic but artificially large project for testing in this case.)

I dug out an old large project we had from someone else and it did reproduce there. It's another regression from #4292. Tracking the file system changes in folder projects is very complicated, and it's difficult to change it without breaking other things. It was re-saving all images in the entire project every time you saved, regardless of whether they were really changed or not, hence the slowdown (and the provided project has over 10,000 images!).

I've updated the changed file tracking to fix this and ensure saves are quick when you make simple changes. I've gone back and re-tested the previous cases to make sure they still work too. Hopefully everything will be working fine in the next beta release - we'll see...
