### ISSUE TITLE
Timeline crashes the game when change initial frame

### ISSUE THREAD

**Issue by igordias2** [Scirra/Construct-3-bugs#4302]
## Problem description

Timeline animation crashes the game when initial frame is different

## Attach a .c3p

(change zip to c3p)
[crash_timelinebug.zip](https://github.com/Scirra/Construct-3-bugs/files/5418697/crash_timelinebug.zip)

## Steps to reproduce

(on the c3p file)
1. Starts the game

(on new project)
1.  create a timeline thats change initial frame
2.  Starts the game
3. Start, Play timeline and play again the same or other timeline that change same initial frame

## Observed result

The game stops with a console error

## Expected result

Can play the same timeline or a different one changing initial frame

## More details

**Affected browsers/platforms:**  (not tested in others platforms)

**First affected release:**  (not tested in others releases)

## System details

<details><summary>View details</summary>

Uncaught (in promise) RangeError: invalid frame
    at AnimationInfo.GetFrameAt (animationInfo.js:2)
    at SpriteInstance.SetPropertyValueByIndex (instance.js:27)
    at SpriteInstance.OffsetPropertyValueByIndex (sdkInstanceBase.js:8)
    at numericInterpolationAdapter.js:8
    at NumericInterpolationAdapter._PickSource (propertyInterpolationAdapter.js:8)
    at NumericInterpolationAdapter._Setter (numericInterpolationAdapter.js:8)
    at numericInterpolationAdapterForTimeline.js:4
    at NumericInterpolationAdapter._PickResultMode (propertyInterpolationAdapter.js:6)
    at NumericInterpolationAdapterForTimeline.ChangeProperty (numericInterpolationAdapterForTimeline.js:4)
    at NumericInterpolationAdapter.ChangeProperty (numericInterpolationAdapter.js:7)

Platform information
Browser: Chrome
Browser version: 87.0.4280.20
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.20 Safari/537.36
C3 release: r220.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 207 gb
Storage usage (approx): 218 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics 655
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
The crash will be fixed in the next beta.

**Comment by igordias2** [comment]
Thx!
