### ISSUE TITLE
Mobile Advert not working on iOS - Test environment and production

### ISSUE THREAD

**Issue by Mr-Josh-web** [Scirra/Construct-3-bugs#4304]
## Problem description

Mobile Advert not working on iOS - Test environment and production. It works fine on Android

## Attach a .c3p

[TestAd.zip](https://github.com/Scirra/Construct-3-bugs/files/5430162/TestAd.zip)

## Steps to reproduce

1. Fill the banner ID, published ID and ios application id of the project
2. Generate the .ipa
3. Check that the banner does not show up

## Observed result

Check that the banner does not show up

## Expected result

The banner should show up

## More details

I have used r218 stable version

Many thanks for your help

Edit: I think it has to be something related to IDFA, App Tracking transparency, Admob configuration and/or Google Funding choices.

**Comment by AshleyScirra** [comment]
No ad will appear because your events are wrong - you can't show an ad in 'On start of layout'. See the section on initialisation in the [Mobile Advert manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/mobile-advert) for more details.

**Comment by Mr-Josh-web** [comment]
Hi Ashley,

As soon as the build service for iOS works (right now it does not work), I will try again without creating the banner inside the "on start of layout" and see what happens.

I am pretty sure I have tried to create and show the banner after a button has been clicked and it did not work.

Thanks.

Regards.
