### ISSUE TITLE
[Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#4305]
When debugging via USB debug apk, each time you click on the touch screen, this error occurs. When debugging via remote Preview in the browser, the error does not occur

Screenshots:
https://drive.google.com/file/d/1cv8IiMTD8cMhyyr4EcqPNjKFyhC-PRAR/view?usp=sharing
https://drive.google.com/file/d/1vhz3__FYowPBskjXQPaC_io-0LEWiQDL/view?usp=sharing

Error:
[Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I don't think this causes any particular problem, it's just log spam that Chrome generates for some reason.
