### ISSUE TITLE
"E" shortcut doesn't work if a comment is selected

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#4306]
## Problem description

It's not possible to add a new event by using the "E" shortcut if a comment is selected.

## Attach a .c3p

Can be reproduced on an empty project, a .c3p file is not necessary.

## Steps to reproduce

1. Add a comment to the event sheet by pressing "Q".
2. Press "Enter" to finish the comment.
3. Press "E" to add a new event. 

## Observed result

The "Add condition" window is not shown.

## Expected result

The "Add condition" window to be shown and a new condition to be added below the selected comment.

## More details

**Affected browsers/platforms:** Chrome / Windows 10

**First affected release:** r218 (current stable release)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.

**Comment by BonzerKitten** [comment]
Thanks for the quick fix! 😊✨
