### ISSUE TITLE
9 patch lugin crashes Construct when changing margins

### ISSUE THREAD

**Issue by Nhdeitmers** [Scirra/Construct-3-bugs#4307]
## Steps to reproduce

1. Create new project
2. Create 9 patch object with png image loaded
3. select margins field and drag to change the value

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'NE' of null @ TypeError: Cannot read property 'NE' of null at window.FNc.jtd (https://editor.construct.net/r218/plugins/allEditorPlugins.js:20:339) at async window.FNc.pyc (https://editor.construct.net/r218/plugins/allEditorPlugins.js:20:133) at async l.bb.l1b (https://editor.construct.net/r218/plugins/allEditorPlugins.js:18:182)
Stack: TypeError: Cannot read property 'NE' of null at window.FNc.jtd (https://editor.construct.net/r218/plugins/allEditorPlugins.js:20:339) at async window.FNc.pyc (https://editor.construct.net/r218/plugins/allEditorPlugins.js:20:133) at async l.bb.l1b (https://editor.construct.net/r218/plugins/allEditorPlugins.js:18:182)
Construct 3 version: r218
URL: https://editor.construct.net/
Date: Sun Oct 25 2020 14:15:49 GMT+0100 (Central European Standard Time)
Uptime: 65.8 s

Platform information
Browser: Chrome
Browser version: 86.0.4240.111
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
C3 release: r218 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
