### ISSUE TITLE
C3 build service for iOS creates corrupted XCode project

### ISSUE THREAD

**Issue by Mr-Josh-web** [Scirra/Construct-3-bugs#4308]
## Problem description

C3 build service for iOS creates corrupted XCode project

## Attach a .c3p

[TestBuild.zip](https://github.com/Scirra/Construct-3-bugs/files/5441420/TestBuild.zip)

## Steps to reproduce

1. Fill the properties of the Mobile Advert plugin (Publisher ID, iOS Applicattion ID and privacty policy) as needed.
2. Open the attached C3 project
3. Export it to XCode project
4. Go to to XCode and try to generate the .ipa file

## Observed result

Find the error in the following image: https://construct-static.com/images/v833/uploads/articleuploadobject/0/images/48887/error.png

Compile and generate the .ipa file correctly

## More details

The issue happens with the r218 stable version

**Comment by AshleyScirra** [comment]
I can reproduce, but this is bizarre - we haven't changed anything related to this for months, and indeed I recently tested it successfully for other support reasons. So what could have changed? I don't think it's anything to do with us, it must be something AdMob have done.

The error says it can't find UserMessagingPlatform.xcframework. But it is there in Pods\GoogleUserMessagingPlatform\Frameworks\Release.

I've no idea why this has happened or what to do about it. I guess I'll have to contact AdMob support.

**Comment by Mr-Josh-web** [comment]
Ok, thanks. Let me know what they say so we can continue building and update iOS app with C3 as I have an app on the App Store that needs to be fixed...

**Comment by AshleyScirra** [comment]
I posted asking for help on the [AdMob SDK forum](https://groups.google.com/g/google-admob-ads-sdk). The post hasn't appeared yet, I guess they have to moderate it, but will follow this up there.

**Comment by Mr-Josh-web** [comment]
Ok, thanks Ashley

**Comment by Mr-Josh-web** [comment]
For some reason your previous post has disappeared :( 

They have replied to the new one you have created (https://groups.google.com/g/google-admob-ads-sdk/c/YCAtBIwPt88)

**Comment by Mr-Josh-web** [comment]
Hi Ashley, 

I believe the procedure is to create a post in the "Cordova Admob" plugin page or contact their developers. Have you managed to contact them or open a post?

Many thanks.

Regards.

**Comment by Mr-Josh-web** [comment]
Hi Ashley,

Any updates? I have a game on production that has a bug and I need to update it.

Thanks.

Regards.

**Comment by karimlahbach** [comment]
Any news About this issue Ashley
is the problem from admob or cordova ?

**Comment by AshleyScirra** [comment]
I'm afraid I have no idea what is going on here or what to do about it. AdMob claimed the project built OK. But it fails for me no matter what I try.

As best as I can tell this is some kind of Xcode build problem introduced by the Google UMP SDK 1.3.0 update, which is one of AdMob's dependencies. I don't believe it is actually anything to do with Construct. It looks like AdMob released a breaking update.

It would be best to contact AdMob support yourself and make your own posts asking for help in the [AdMob SDK forum](https://groups.google.com/g/google-admob-ads-sdk). The more people they see asking for help, the higher a priority it will be for them to fix it.

**Comment by Mr-Josh-web** [comment]
Hi Ashley,

Do they compile and build the project with the same XCode version as yours? I am using the latest one as it does not work.
They have built the app with an iPhone 8 iOS 14 simulator which is quite weird. As far as I know construct 3 apps do not work  with the iOS simulator.

You sent him a xcode project and I am sure they changed some configuration within the project that made the app built.

Regards.

**Comment by AshleyScirra** [comment]
As of Xcode 12 Construct projects do work in the simulator. But I don't know exactly what they did. They didn't provide any more details than are in that message thread.

**Comment by karimlahbach** [comment]
i add this post in google [https://groups.google.com/g/google-admob-ads-sdk/c/VTM93fWaXwY](url)
also i report a bug in cordova [https://github.com/apache/cordova-ios/issues/1021](url)
i hope one of them know the solution because this problem driving me crazy

**Comment by theBdrive** [comment]
@AshleyScirra  I'm getting this error as well, the UserMessagingPlatform.xcframework is no where to be found in the Xcode project generated by C3. I tried downloading the SDK directly from Google at https://developers.google.com/admob/ump/ios/download and manually add the framework to the project but it still get framework not found. Then I noticed in the Xcode Build Settings> Other Linker Flags the UserMessagingPlatform.xcframework had a -framework under it, if I remove the -framework from UserMessagingPlatform I don't get the previous framework not found error, but am now getting "clang error: no such file or directory: 'WebKit' Command Ld failed with a nonzero exit code.

**Comment by Mak14** [comment]
Hi, I had the same issue and read somewhere that this might be a pods outdated version.
So I have re-installed pods, brew etc, and then I did something with the Xcode project folder itself. 
It was terminal command ' pod install --repo update' inside the project folder, as I remember.

Here is link to the blog where I found the solution.
https://kacchanblog.com/programming/swift-admob-cocoapods-error

Hope that helps

**Comment by Mr-Josh-web** [comment]
Hi Ashley,

Could you please try if what Mark14 has commented solves the problem?

Thanks.

Regards.

**Comment by karimlahbach** [comment]
i found a solution from google support [https://groups.google.com/g/google-admob-ads-sdk/c/VTM93fWaXwY](https://groups.google.com/g/google-admob-ads-sdk/c/VTM93fWaXwY)
how to solve the problem 
1 - open your xcode project
2- open terminal and then add this command 
3- add "cd (your project directory )" then press entre
4- add this code "pod install --repo-update"
Congratulation problem solved

**Comment by Mr-Josh-web** [comment]
Ok, thanks @karimlahbach and @Mak14  for your comments and solutions. I am glad it works on your side. I will try with my project in order to see if it works too.

@AshleyScirra could you please fix that on server side so we do not have to run the above command. Thanks.

Regards.

**Comment by theBdrive** [comment]
Confirmed, pod install --repo-update fixes the issue.

**Comment by Mr-Josh-web** [comment]
Are banners, intersticial and reward videos working at your end after running that command? Thanks

**Comment by Mak14** [comment]
> Are banners, intersticial and reward videos working at your end after running that command? Thanks

Banners are ok, but rewarded on the iPhone sometimes are black screen. On iPad it worked well.

**Comment by Mr-Josh-web** [comment]
Ok, thanks @Mak14 .  I cannot make them work. It has to be something that I do wrong. I'll keep trying.

**Comment by AshleyScirra** [comment]
The workaround does not seem to work for me - running `pod install --repo-update` fails with:

```
[!] CocoaPods could not find compatible versions for pod "GoogleUserMessagingPlatform":
  In snapshot (Podfile.lock):
    GoogleUserMessagingPlatform (= 1.3.0, ~> 1.1)

  In Podfile:
    GoogleUserMessagingPlatform (= 1.2.0)

Specs satisfying the `GoogleUserMessagingPlatform (= 1.2.0), GoogleUserMessagingPlatform (= 1.3.0, ~> 1.1)` dependency were found, but they required a higher minimum deployment target.
```

I don't know what this means, it looks like some kind of dependency misconfiguration in AdMob.

**Comment by AshleyScirra** [comment]
`pod install --repo-update` seems to fix it for me too. I don't know why though.

I tried updating the build server and rebooting it, but it hasn't changed anything, you still need the workaround.

I guess there is still a configuration problem on AdMob's side. At least we have a workaround until they fix it. As noted before if you need further help please post to the [AdMob SDK forum](https://groups.google.com/g/google-admob-ads-sdk).

**Comment by karimlahbach** [comment]
Hi Ashely i just get a reply from Cordova Team
they said that you need to update the CocoaPods to 1.10.0 or newer
[https://github.com/apache/cordova-ios/issues/1021#event-4016282511](https://github.com/apache/cordova-ios/issues/1021#event-4016282511)

**Comment by karimlahbach** [comment]
can you fix this on the build sever ?

**Comment by AshleyScirra** [comment]
Today I updated the build server to CocoaPods 1.10.0 and it seems to have resolved the problem - I can now build an Xcode project using AdMob with no changes. I guess AdMob updated their minimum requirements and failed to notify anyone, so we had to figure it out on our own! Can anyone else confirm it's working now for them?

**Comment by karimlahbach** [comment]
it working fine for me

**Comment by AshleyScirra** [comment]
That's at least two confirmations it's working, so I think this is now resolved.

**Comment by GameLevel71** [comment]
Hello Ashley ! I've been doing compilation tests for my game on iOS for 3-4 days. The update of cocoapods that you have done works perfectly and Xcode works the Builds perfectly.
The problem for me is that it doesn't show me any ads, I've tried everything, and it doesn't show interstitial ads or reward videos.
I have been able to verify in Admob that the request for ads does it well, but it does not show them in the game.
Can you check to see what happens?

**Comment by Mr-Josh-web** [comment]
Hi @GameLevel71 

I have released a new version of my game on iOS 3-4 days ago and I can confirm that banners, intersticial and reward videos work fine. 

I have exported the game using the latest stable version of C3 (r255). Have you used this version of C3?

Regards.

**Comment by GameLevel71** [comment]
Hi Mr-Josh-web

I confirm that the version of C3 that I have exported with is the latest, C3 R255.

If it works well for you, I don't understand why you don't put the ads on me ...

Let's see if it happens to someone else and if not I will continue investigating.

Regards.

**Comment by GameLevel71** [comment]
I finished trying another new build correcting the position of the ads and it doesn't work.
It does not show either reward ads or interstitial ads ...
In construct event I load the ads in the on start of layout as I have always done, and I show them when closing the store that appears at the end of each level. On android it works perfectly but not on iOS.
I don't know what to do, because the most curious thing of all is that in Admob it recognizes that request, but does not show them.
All this happens in the version that I use for development in Xcode, with the ipad connected to the mac, as I have always done and playing the game on the ipad (as always).
Someone who can help me with this problem please!

**Comment by Mr-Josh-web** [comment]
Hi @GameLevel71 

Perhaps Ashley can help you in a better way, but could you please share a minimal C3 project that only shows a banner ad so I can test your code and see if I can see where the problem is?

Regards.

**Comment by AshleyScirra** [comment]
The most common problem is that you've misconfigured the ads. Double-check your configuration with AdMob, and double-check your events according to the manual entry guide. Given ads are working for others, there does not appear to be any problem with Construct.

**Comment by GameLevel71** [comment]
hi @Mr-Josh-web and @AshleyScirra 

I have been doing many tests, I have checked that everything is fine many times and everything is correct, it has not been possible to make the ads work.

I have prepared a special program in C3 to show ads that you could try to see if it works for you or not ...

It is a program with 6 buttons:
Load interstitial
Show interstitial
Upload Video Reward
Show Video Reward
Load and show interstitial
Upload and show video reward.

Interstitial ads only work if you activate Test Mode in the C3 mobileAdlert configuration. Even with this activated it only shows the interstitials and does not show the Reward video.

If the Test Mode is not activated, it does not show ads of any kind, neither the interstitials nor the Video Reward.

Can you give me an email so I can share my project with you?

I would not like to share it here because my ad unit is on.

Please help!

Regards,

**Comment by Mr-Josh-web** [comment]
Hi @GameLevel71 ,

Remove your admob ids and share the project here. I will use my admob ids to see if it works or not.

Regards.

**Comment by GameLevel71** [comment]
Perfect !

Here is the project that I used to test this. I leave you data on how I had it configured so that you can eliminate some errors.

The configuration that I have deleted from the MobileAdlert plugin:
iOS Apliccation ID
Publisher ID
Privacy Policy URL

In the actions of the event sheet I have simply deleted the identifiers of the Admob ad units that I create for the iOS system. The interstitial block and the Video Reward block. Those that begin with "ca-app-pub- ..."

I hope you can help me!

Thank you !

[Test Ads on iOS.zip](https://github.com/Scirra/Construct-3-bugs/files/5622866/Test.Ads.on.iOS.zip)

**Comment by theBdrive** [comment]
@GameLevel71 I tried your sample project and both interstitial and rewarded ads work fine for me. I created a test app in my Admob, used that app ID and created my own interstitial and rewarded ads and those units work fine in your project. I also tested using the Admob test ad units found at https://developers.google.com/admob/ios/test-ads and those work fine for me as well. The mobile advert plugin is working correctly, this is user error either in your Admob setup or C3 events, in which case you should be looking for help on the C3 forums not here in a bug report.

**Comment by Mr-Josh-web** [comment]
> @GameLevel71 I tried your sample project and both interstitial and rewarded ads work fine for me. I created a test app in my Admob, used that app ID and created my own interstitial and rewarded ads and those units work fine in your project. I also tested using the Admob test ad units found at https://developers.google.com/admob/ios/test-ads and those work fine for me as well. The mobile advert plugin is working correctly, this is user error either in your Admob setup or C3 events, in which case you should be looking for help on the C3 forums not here in a bug report.

Have you also tested on iOS? I think @GameLevel71 had an issue only on iOS.

**Comment by theBdrive** [comment]
@Mr-Josh-web My last post said I tested iOS ads?

**Comment by Mr-Josh-web** [comment]
> @Mr-Josh-web My last post said I tested iOS ads?

Yes, it does. Sorry I miread it.

**Comment by Mr-Josh-web** [comment]
Hi @GameLevel71 

@theBdrive says your c3p project work fine on iOS. Could you please try to create a new Admob project and see if it works? Not sure what else you could try... :(

Regards.
