### ISSUE TITLE
Problem with Player video 

### ISSUE THREAD

**Issue by anacassia** [Scirra/Construct-3-bugs#4309]
I have a project that serves as a video player, when I click the video for the first time, it happens correctly several times, but randomly I need to double-click to play the video.
This happens when I put more than one button and more than one video in my project.

https://github.com/anacassia/player

**Comment by anacassia** [comment]
Hi
I send the bug, and see in the github Ignore guideline.


I would like to understand why you entered ignore. I really need this
function to touch the button and play the video without fail.

thanks
<http://www.agenciagr8.com.br/>

*Ana Cássia Corrêa*
ana@agenciagr8.com.br
 (11) 3805.6668

 (11) 99856-5734

www.agenciagr8.com.br
@agenciagr8 <http://www.twitter.com/AgenciaGr8>
/agenciagr8 <http://www.facebook.com/agenciaGr8>


Em ter., 27 de out. de 2020 às 08:39, Ashley (Scirra) <
notifications@github.com> escreveu:

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. We need all the required information to help you, and we make it clear that we close issues that do not provide sufficient information.
