### ISSUE TITLE
Cloning a dictionary that is in a family with variables will crash the project

### ISSUE THREAD

**Issue by Tobye** [Scirra/Construct-3-bugs#4312]
## Problem description

When you clone a Dictionary that is part of a family, and that family has variables, the project crashes.

## Attach a .c3p

[The c3p](https://drive.google.com/file/d/182wrRCUhAIjTlPpQki8DH9qBon5D3yUC/view?usp=sharing)

## Steps to reproduce

1. Right click the dictionary object in the sidebar, select 'clone'.  The project will crash.

## Observed result

The project crashed

## Expected result

The dictionary would be cloned

## More details
It happens in the editor, which I have as a downloaded app on Windows 10 laptop.

I can't be sure in which version it first became a bug because I never tried to do it before version 222, but I first observed it in version 222.

## System details

Platform information
Browser: Chrome
Browser version: 86.0.4240.111
Browser engine: Chromium
Browser architecture: 32-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
C3 release: r222 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 42 gb
Storage usage (approx): 848 mb (2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
Please provide a public link to the project.

**Comment by Tobye** [comment]
Oops, sorry thought it was.  [Updated](https://drive.google.com/file/d/182wrRCUhAIjTlPpQki8DH9qBon5D3yUC/view?usp=sharing)

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
