### ISSUE TITLE
Bug on updating animation frames in the layout.

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4313]
## Problem description
If I delete a animation frame then in the layout current frame switch to 0.
in the attached file delete second frame which is yellow and exit animation editor and see. In the layout current frame of (yellow) instance changed from 1 to 0.

## Attach a .c3p
[animation update issue.zip](https://github.com/Scirra/Construct-3-bugs/files/5451098/animation.update.issue.zip)

## Steps to reproduce

1. Insert Sprite and give it 4 frame and fill random colors on it
2. in the layout place 3 copies of the sprite.
3. change their initial frame 0, 1 & 2
4. now double click on sprite to open animation editor and delete frame 1. 
5. look in layout now

## Observed result

Initial frame reset to 0 

## Expected result

should same initial frame

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
