### ISSUE TITLE
Few tabs on screen are not saving

### ISSUE THREAD

**Issue by IcticStep** [Scirra/Construct-3-bugs#4314]
## Problem description

If you put a few tabs on the screen at the same time, save and reopen project, all tabs, except of main tab will be closed.

## Attach a .c3p

[testProject.zip](https://github.com/Scirra/Construct-3-bugs/files/5452162/testProject.zip)

## Steps to reproduce

1. Put Event sheet 2 on the right part of screen. (You sholud have two paralel tabs opened at the same time)
2. Do anything like creating a new object in order to make Construct 3 let you to save your project.
3. Save project.
4. Close project.
5. Open project.

## Observed result

Event sheet 2 is not at the right part of the screen. It is not even at screen. It is closed.

## Expected result

Event sheet 2 shoul stay opened in the right part of screen.

## More details

**Affected browsers/platforms:** 
Definetely Constuct 3 Chrome app 86.0.4240.111, but I think all platforms.

It is in r218. No idea about others.

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 86.0.4240.111
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
C3 release: r218 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 60 gb
Storage usage (approx): 648 mb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
As of the next beta, all open event sheets, layouts, text and data editors will be restored as tabs in the main pane when loading a project.

This means the exact pane layout will not always be restored.
