### ISSUE TITLE
Speech synthesis is facing some issue

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#4316]
## Problem description

I am making a project which use speech synthesis.Since I am new to it,so I headed to the tutorial section (available on start page).I opened the example given on speech synthesis and I noticed 2 bugs
1.) "resume" and "pause" buttons simply on pressing just kills the plugin (you will have to start the project again)
2.) the pitch option:- It says that enter value among 0-2. 1 is fine. but 0 and 2 sounds EXACTLY same.

## Attach a .c3p

go to start page of editor.constuct.net and open text to speech project

## Steps to reproduce

1.) open the project and run it
2.) play the text-to-sound.In between it,press the pause button.The project will now onwards not work
3.) now in pitch section, test values 0,1,2.Notice 0 and 2 sounds exactly same

## Observed result

1.) pause and resume button do not work
2.) 0 and 2 in pitch section gives same effect

## Expected result

1.) pause and resume should work
2.) 0 and 2 (in pitch section) should give different voices

## More details
I tested it on pc and my mobile (obviously both were using chrome).And chrome is latest

**Comment by layilpaht** [comment]
Few additions
1.) in pitch issue, '0' is not working.Otherwise I tested with 0.1 and it was working

**Comment by AshleyScirra** [comment]
I can reproduce in Chrome stable (86), but in Chrome Canary (88) it seems to be working fine.

This points to a bug in Chrome that was already fixed. Can you verify it's working for you in Canary?

**Comment by layilpaht** [comment]
I don't use canary (I am hearing it for the first time). Don't take me wrong but isn't it wrong to tell the user to change the browser to solve the issue (safari is an exception BTW)

**Comment by AshleyScirra** [comment]
Canary is a pre-release version of Chrome. This looks like a Chrome bug. Checking Canary will help verify the Chrome bug is fixed. Then, in the next couple of months, the fix will come to the stable version of Chrome. Nobody has to change browser.

**Comment by AshleyScirra** [comment]
No response and evidence is this is a Chrome bug that was already fixed, so closing.
