### ISSUE TITLE
Project saved using "project folder" option corrupts if you clone objects

### ISSUE THREAD

**Issue by cb130felix** [Scirra/Construct-3-bugs#4317]
## Problem description

C3 projects saved using the "Save as project folder..." option will get corrupted if you clone objects.

## Attach a .c3p

It's needed to reproduce the steps yourself 

## Steps to reproduce

1. Create a new project and save it using the "Save as project folder..." option
2. Close the project
3. Open the project
4. Create a sprite object
5. Clone the created sprite object
6. Save the project
7. Close the project
8. Open the project -> Project is corrupted

## Observed result

Project gets corrupted

## Expected result

For the project to not get corrupted

## More details

I'm on chorme (up to date) and C3 r222

**Comment by AshleyScirra** [comment]
Ergh, after all the recent folder project save changes (#4275, #4292, #4301), there was one more missing check in the code for saving folder projects. I've added it for the next beta which should fix this. Leaving open with fixed tag as I imagine this is another one anyone using folder projects will run in to.

**Comment by AshleyScirra** [comment]
This should be working correctly in r223 now. Hopefully that's the last of it...
