### ISSUE TITLE
Guided Tour resets workspace bars locations

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4318]
## Problem description

Selecting the 'Guided Tour' from the menu resets all the positions of your workspace: project bar, tilemap bar, layers bar, etc.

## Attach a .c3p

N/A 

## Steps to reproduce

1. Open https://editor.construct.net/
2. Relocate the Project Bar, Properties Bar, Tilemap Bar and/or Layers Bar
3. Select Guided Tour -> Beginner's Guide
4. Click the top right corner of the 'Welcome' dialog box that appears. Select Exit tour.
5. Close the Start page.

## Observed result

The customized location of the workspace bars is reset to the C3 default.

## Expected result

The bars remained where they were.

## More details

Anecdotally:

It would be great to have a Save/Load Workspace feature. Different projects, and different points in development, require different bars. 

Also because C3 also resets your workspace if it doesn't have enough space to draw it. If you're working on an external monitor in session one and customize your workspace to that resolution, and then open C3 in session two on your laptop screen, the workspace is reset to the default.

**Affected browsers/platforms:** 

**First affected release:** r218

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. We can't guarantee that the tour can be successfully completed if the UI has been customised. So it resets it to the default when starting the tour. It's also designed for beginners who are likely to have the default UI setup anyway.
