### ISSUE TITLE
[r34] Various built-in functions fail when string variables or string constants are used for parameters.

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#432]
## Problem description

(Original bug report)
When attempting to create an object using a variable or constant as the layer name, the object fails to spawn. The object will spawn if the layer number is passed in as a variable, or if the string for the layer name is typed into the Layer parameter manually.

(New info)
I also discovered I couldn't pass string variables into the ImagePointX() and ImagePointY() functions (again, string literals and numbers/number variables work fine). Likewise I was unable to Set Animation on a sprite by passing in the animation name as a variable. So perhaps all built-in functions are failing when passed string variables or constants?

## Attach a .c3p

[CreateObjectBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1049304/CreateObjectBug.zip)

## Steps to reproduce

1. Create a variable or constant to hold the name of a layer, i.e. "Layer 0".
2. Add an event to create an object, and use the variable in the Layer parameter.
3. Launch the project.

## Observed result

The object fails to spawn.

## Expected result

The object should spawn.

## Affected browsers

* Chrome: yes

## System details

Platform info below.

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r34

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 47 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Scoremonger** [comment]
Looks like this is actually a widespread problem with string variables right now - I'm not able to use them for image point name parameters, animation names, etc.

**Comment by AshleyScirra** [comment]
It's not a bug - the initial value of an event variable is not a string so you don't need the double-quotes around it. This means you end up requesting a layer named `"Layer 0"` instead of just `Layer 0` which does not exist.

**Comment by Scoremonger** [comment]
Ah, thanks, sorry for the false alarm.
