### ISSUE TITLE
Something went  wrong

### ISSUE THREAD

**Issue by GamingGri** [Scirra/Construct-3-bugs#4325]
Error report information
Type: unhandled rejection
Reason: Error: crosshair tool already placing @ Error: crosshair tool already placing at f.TUc (https://editor.construct.net/r218/components/editors/layoutView/layoutView.js:205:378) at window.Cl.tlb (https://editor.construct.net/r218/components/editors/layoutView/layoutView.js:40:86)
Stack: Error: crosshair tool already placing at f.TUc (https://editor.construct.net/r218/components/editors/layoutView/layoutView.js:205:378) at window.Cl.tlb (https://editor.construct.net/r218/components/editors/layoutView/layoutView.js:40:86)
Construct 3 version: r218
URL: https://editor.construct.net/
Date: Thu Nov 05 2020 21:23:52 GMT+0300 (Москва, стандартное время)
Uptime: 1595.6 s

Platform information
Browser: Chrome
Browser version: 86.0.4240.183
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
C3 release: r218 (stable)
Language setting: ru-RU

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 240 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. I'm afraid it's impossible to help unless you provide that information, in particular the steps to follow to reproduce the problem.
