### ISSUE TITLE
importing to c3

### ISSUE THREAD

**Issue by daronalds** [Scirra/Construct-3-bugs#4326]
![Captureerror](https://user-images.githubusercontent.com/47309093/98316241-df790700-1f8e-11eb-96e7-230681e0e2a5.PNG)

## Problem description

 c3 ran into a problem and is unable to continue. this is what i get when i import a project done in c2 r275 to c3 r18

## Steps to reproduce

1. i saved as a single file in c2
2. open file and locate file in c3
3.

## Observed result

 my project tries to open and at the end i get an error loading project. but i could see some of the assets and the layout.

## Expected result

 open project

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Syntax error: '-' can't go here - are you missing something before it?
Construct 3 version: r218
URL: https://editor.construct.net/
Date: Thu Nov 05 2020 17:20:44 GMT-0800 (Pacific Standard Time)
Uptime: 70.8 s

Platform information
Browser: Chrome
Browser version: 86.0.4240.111
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
C3 release: r218 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>
![Captureerror](https://user-images.githubusercontent.com/47309093/98316764-de94a500-1f8f-11eb-88f1-1e6354f9ecc1.PNG)

**Comment by AshleyScirra** [comment]
It's impossible to help unless you share the project you are trying to import. Please provide that and then we can investigate.

**Comment by AshleyScirra** [comment]
No response for a week and nothing we can do about this report as it stands so closing.
