### ISSUE TITLE
[r34] Crash when "Bulge" is the only effect applied to a layer

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#433]
## Problem description

If "Bulge" is the only effect applied to a layer, Construct 3 crashes. This happens whether you apply Bulge to a layer with no prior effects applied, or if you delete all the effects applied to the layer except Bulge.

## Attach a .c3p

[BulgeEffectCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/1049374/BulgeEffectCrash.zip)

## Steps to reproduce

1. Create a new project and select the default layer.
2. Apply the "Bulge" effect to it.

In the attached project, just delete the layer effect that isn't a Bulge.

## Observed result

Construct crashes.

## Expected result

A sweet, sweet bulge effect.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r34/main.js, line 61, col 242537
Message: Uncaught ReferenceError: ǃOez is not defined
Stack: ReferenceError: ǃOez is not defined at u.ǃzN (https://editor.construct.net/r34/main.js:61:242537) at r.ǃzN (https://editor.construct.net/r34/main.js:61:228026) at window.ǃGb.ǃBt (https://editor.construct.net/r34/components/editors/layoutView/layoutView.js:1:6901) at ǃBe (https://editor.construct.net/r34/components/editors/layoutView/layoutView.js:1:1995)
Construct 3 version: r34
URL: https://editor.construct.net/index.html
Date: Fri Jun 02 2017 20:54:26 GMT-0700 (Pacific Daylight Time)
Uptime: 48.1 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r34

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r35.
