### ISSUE TITLE
Copying event sheets from other projects create fake functions.

### ISSUE THREAD

**Issue by Visual917** [Scirra/Construct-3-bugs#4334]
## Problem description

When you try to copy some events from another project that also contain some Functions, and you have some objects missing on the target project, Functions duplicate even though they don't exist. And once you make sure you add the necessary objects, it copies successfully but the Function name will be Function2 or 3 instead (depending on how many times you tried to copy-paste the events.) You cannot change the name of the functions back to Function but when you restart Construct, it is back to normal.

## Attach a .c3p

You don't need a C3P that much i think.

## Steps to reproduce

Stable r218.

Get a source project ready that contains AJAX (or some other plugin object) and some Functions in the event sheet. Go to the blank target project and try to copy the event sheet from the source project. It will indicate that AJAX is missing from the project. Do this at least once. (Let it give you an error) 

Then add AJAX to the target project and try to paste the events one last time to the event sheet. You will now be able to see that the Function name is Function2 (or more, if you tried more before adding AJAX) 

You may think, well okay I will just rename it to "Function" but no. It says that such function name already exists. You need to restart Construct now and see that you can rename it to Function now. 

Can you fix it? ;)

## Observed result

The Functions gets pasted as a hidden duplicate.

## Expected result

The Function to be pasted as is, or not at all when objects are missing.

## More details

**Affected browsers/platforms:** 
Construct Editor, NW.JS

**First affected release:** 
Don't know
## System details
rtx 2060 mobile 64 gb ram 10750h cpu

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines: attach a sample project and only test the latest release (currently r224) to avoid reporting issues we've already fixed. It's impossible to help otherwise. We have tried to make this as clear as possible from the guidelines.

**Comment by aecanales** [comment]
I just ran into this issue when copying a template into my main project. Haven't been able to reproduce it with a minimal project yet, but will share it here when I do.

**Comment by AshleyScirra** [comment]
Issue is a week old and is not actionable, so closing. Please always follow the bug report guidelines.
