### ISSUE TITLE
When Sprite playing Tween (Size) Then Set mirror It seems to something strange.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4335]
## Problem description

When Sprite playing Tween (Size) and Set mirror It seems to something strange.
But sine does not happen like this.
  
If Tween is not playing before the set mirror, it is normal.

## Attach a .c3p

[Test.c3p](https://cdn.discordapp.com/attachments/253490735268102144/776380561865834496/MirrorTwenBUGTest.c3p)

## Steps to reproduce

**Test 1 - 1**
1. play tween (size) 
```
Self.ImageWidth  * 1.25
Self.ImageHeight * 1.25
```
2. When Tween playing, set mirror.
3. 🤷‍♂️ strange
<br>

**Test 1 - 2**
1. set mirror before Tween playing.
2. play tween (size) 
```
Self.ImageWidth  * 1.25
Self.ImageHeight * 1.25
```
3. 🤷‍♂️ strange

<br>

**Test 2 - 1**
1. play tween (size) 
```
(sign(Self.Width) * Self.ImageWidth) * 1.25
Self.ImageHeight * 1.25
```
2. When Tween playing, set mirror.
3. 🤷‍♂️ strange.

<br>

**Test 2 - 1**
1. set mirror before Tween playing.
2. play tween (size)
```
(sign(Self.Width) * Self.ImageWidth) * 1.25
Self.ImageHeight * 1.25
```
3. ok. it ‘s normal.

<br>

**Conclusion**:
when playing Tween, set mirror will cause problems

## Expected result

can be like the the Sine,
When Sine playing, toggle mirror it will not any strange happen.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta, for both size and scale properties.
