### ISSUE TITLE
Sidebars are translucent to object resize mouse events

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4336]
## Problem description

When you are moving the mouse cursor over the left settings panel and  trying to click an option, If the mouse cursor is also over one of the resizing hotposts of an object on the layout (off screen, behind the settings panel), you won't be able to interact with the setting.

## Attach a .c3p

not c3p related

## Steps to reproduce

1. Put any object that can be resized on the layout
2. Move the sprite so one of the resizing hotspot is overlapping one of the settings panel fields or buttons.
3. Try to click the setting.

## Observed result

Mouse shows resizing tool and you can't click the setting.

## Expected result

All layout mouse events behind the side panels should be blocked.

## More details

**Affected browsers/platforms:** Chrome/NWjs

**First affected release:** Not sure, but it happens on both the latest Beta and Stable releases.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
