### ISSUE TITLE
C3 crashes when opening the Z Order Bar on Android Note 10

### ISSUE THREAD

**Issue by FovisJoris** [Scirra/Construct-3-bugs#4337]
## Problem description
On my Samsung Note 9, running Android 10, when i attempt to open the Z Order Bar on a sprite, C3 crashes. I'm using C3 beta version r224, although i initially tested on stable version r218. I am using Chrome 86.0.4240.185 for the browser.

I have tested on Windows with no issue. I have not tested on other browser apps on Android.

Crash dump attached; [c3_crash_dump.txt](https://github.com/Scirra/Construct-3-bugs/files/5531149/c3_crash_dump.txt)

## Attach a .c3p
Project attached: [test.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5531169/test.c3p.zip)

## Steps to reproduce
1. Open C3 in Android 10
2. Create a new project
3. Insert new object add a sprite
4. Right click (or press and hold) on sprite to bring up menu
5. Select Z Order --> Open Z Order bar
6. C3 crashes and requires a reload

## Observed result
C3 crashes and display dump report
Crash dump has been attached

## Expected result
The Z Order Bar should open

## More details
Only tested using Chrome on Android
I haven't tried this feature on Android before, so i'm not sure if it ever worked.

## System details
<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r218/main.js, line 294, col 228
Message: Uncaught Error: component id 'zOrderBar' already registered
Stack: Error: component id 'zOrderBar' already registered at window.Gcb.fU (https://editor.construct.net/r218/main.js:1270:165) at new window.Zi (https://editor.construct.net/r218/main.js:1990:387) at new window.L3 (https://editor.construct.net/r218/components/bars/zOrderBar/zOrderBar.js:1:184) at Function.d.l (https://editor.construct.net/r218/main.js:294:207) at Function.ye (https://editor.construct.net/r218/components/bars/zOrderBar/zOrderBar.js:18:147) at https://editor.construct.net/r218/components/editors/layoutView/layoutView.js:26:95 at https://editor.construct.net/r218/main.js:1226:402
Construct 3 version: r218
URL: https://editor.construct.net/
Date: Thu Nov 12 2020 04:46:19 GMT-0500 (Eastern Standard Time)
Uptime: 652.8 s

Platform information
Browser: Chrome
Browser version: 86.0.4240.185
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Android
Operating system version: 10
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 3.5
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 10; SM-N960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.185 Mobile Safari/537.36
C3 release: r218 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Qualcomm
Renderer: Adreno (TM) 630
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta. Removed the context menu option. In mobile all panes are available by sliding from either the left and right.
