### ISSUE TITLE
Any mouse click enables Drag and Drop behavior 

### ISSUE THREAD

**Issue by ReflextionsDev** [Scirra/Construct-3-bugs#4340]
## Problem description

When attaching the drag and drop behavior to an object, it can be manipulated with any mouse click. This includes right click, middle click, mouse 4/5 etc. In Construct 2, only left mouse click would manipulate an object. This is especially troublesome if the user wants to do anything else with any other mouse button. 

In my case I use middle mouse to pan, and right mouse to deselect. I can no longer pan without selecting an object, and I can't deselect an object without having to move my cursor off of it.

## Attach a .c3p

https://github.com/ReflextionsDev/c3-bugs/blob/main/DragDrop.c3p

## Steps to reproduce

1. Create a sprite
2. Attach and enable the drag and drop behavior
3. Attempt to drag the sprite with right mouse button

## Observed result

The object moves.

## Expected result

The object should not move unless left click is used.

**Comment by AshleyScirra** [comment]
OK, changed to left mouse button only in next beta.
