### ISSUE TITLE
bug preview with google chrome 

### ISSUE THREAD

**Issue by Moraan666** [Scirra/Construct-3-bugs#4341]
the preview stops on "loading script ..." on google chrome, i tested it on firefox it works, for example. The bug appears on chrome since I added layouts with interfaces in global

![rsjrt](https://user-images.githubusercontent.com/74423247/99098571-74a47d00-25d9-11eb-9c4f-ba1694aff757.png)

**Comment by AshleyScirra** [comment]
Try clearing your browser cache and try again. As ever there is nothing else we can do unless you follow the bug report guidelines.
