### ISSUE TITLE
Tilemap bar - popup - tools

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4342]
## Problem description

After popping out the tilemap bar you can't change drawing tools anymore.

## Attach a .c3p

Not c3p related.

## Steps to reproduce

1. Add a tilemap
2. pop out the tilemap bar
3. try to change drawing tools

## Observed result

Buttons are locked

## Expected result

Buttons should be clickable

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
