### ISSUE TITLE
Unable to pick external editor on Mac. Nwjs

### ISSUE THREAD

**Issue by Mak14** [Scirra/Construct-3-bugs#4343]
## Problem description

External image editor is not selecting.

## Attach a .c3p
It happens in any project.

## Steps to reproduce

1. Open any sprite to edit image.
2. Press "pick external editor"
3. Select desired app as editor

## Observed result

Nothing happens on the path line ( where you see the path to the app)

No app selected.
As a result I can't use external editor for image editing.

## Expected result
Expecting the ability to select external editor and launch it when I press "Open External editor" button

App need to be selected
## More details
Sometimes, after several random clicks it adds weird path to some nwjs folders.
In that case after pressing "Open External Editor" button I see the standard dialog "Using external editor", but no apps are launched. 

**Affected browsers/platforms:** 
This issue is on Mac OS Catalina 10.15.6
 

Construct 3 b224
**First affected release:** 

## System details

Browser: NW.js
Browser version: 0.49.2
Browser engine: Chromium
Browser architecture: (unknown)
Context: nwjs
Operating system: Mac OS X
Operating system version: 10.15_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.49.2 (like Chrome/86.0.4240.111)
C3 release: r224 (beta)
Language setting: en-US

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.

**Comment by Mak14** [comment]
After trying to select the editor ( button choose editor), Construct was crashed and i got this log:



Error report information
Type: unhandled rejection
Reason: Error: require(...).XGd is not a function @ TypeError: require(...).XGd is not a function at Object.d.Ni.qyc (https://editor.construct.net/r227-2/main.js:527:42) at Function.Q_c (https://editor.construct.net/r227-2/main.js:646:39) at d.f.G.kLd.Wpd (https://editor.construct.net/r227-2/projectResources.js:1802:419) at HTMLButtonElement.k.onclick (https://editor.construct.net/r227-2/projectResources.js:1800:388)
Stack: TypeError: require(...).XGd is not a function at Object.d.Ni.qyc (https://editor.construct.net/r227-2/main.js:527:42) at Function.Q_c (https://editor.construct.net/r227-2/main.js:646:39) at d.f.G.kLd.Wpd (https://editor.construct.net/r227-2/projectResources.js:1802:419) at HTMLButtonElement.k.onclick (https://editor.construct.net/r227-2/projectResources.js:1800:388)
Construct 3 version: r227.2
URL: https://editor.construct.net/r227-2/
Date: Fri Dec 04 2020 20:55:52 GMT+0300 (Moscow Standard Time)
Uptime: 702.4 s

Platform information
Browser: NW.js
Browser version: 0.50.1
Browser engine: Chromium
Browser architecture: (unknown)
Context: nwjs
Operating system: Mac OS X
Operating system version: 10.15_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.50.1 (like Chrome/87.0.4280.66)
C3 release: r227.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 5300 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

**Comment by AshleyScirra** [comment]
@Mak14 - if you run in to any subsequent problems please file a new issue following the guidelines.
