### ISSUE TITLE
"On created" events are triggered when loading a save slot from a different layout

### ISSUE THREAD

**Issue by ReflextionsDev** [Scirra/Construct-3-bugs#4344]
## Problem description

When the player saves and loads the game within the same layout, "On created" events are not triggered. However, if the player loads a save slot from a different layout, those events are triggered. This is unexpected because those objects had already been created when the player saved the game, "On start of layout" is not triggered when loading a save slot, and it is expected "On created" would behave similarly. 

## Attach a .c3p

https://github.com/ReflextionsDev/c3-bugs/blob/main/OnCreatedDupe.c3p

Press save, then back, then load, repeat. Notice the player can spawn infinite balls.

## Steps to reproduce

1. Create an object with "On created" events
2. Save the game
3. Load the save slot from a different layout

## Observed result

"On created" actions are triggered again

## Expected result

"On created" actions should not repeat for the same objects if they have already run in that save slot

**Comment by ReflextionsDev** [comment]
![image](https://user-images.githubusercontent.com/3964845/99136403-95c59780-25f2-11eb-9295-94ab646858d7.png)

**Comment by AshleyScirra** [comment]
Thanks for the report, it looks like you're right that it shouldn't be doing this, but for some reason we had dedicated code specially to handle triggering 'On created' in this case. I've just removed that code and it works as expected, so it should be fixed in the next release.
