### ISSUE TITLE
Failed to start preview

### ISSUE THREAD

**Issue by PawarHouseStudios** [Scirra/Construct-3-bugs#4345]
I am unable to preview my game in construct 3. Tried everything I can but still not worth it. Cleaned the cached/cookies, reinstalled chrome, scanned for viruses, restarted the complete system, but still, it's not working. I cannot preview in any browser so let it be chrome, mozilla, or edge. Earlier I was able to watch the preview without any issue. I even tried to disable anti-virus but in vain. What should I do to get this issue resolved? Also, I am able to preview it on my laptop and tablet. This issue is only occurring on my system for the past 2 days now. What could possibly be wrong? I recently updated my system as it is on auto-update mode.

Also, when trying to STORAGE CLEANUP under local storage, I receive a pop-up with the error info mentioned below:
Error report information
Type: unhandled rejection
Reason: Event 'error': [object Event]
Construct 3 version: r218
URL: https://editor.construct.net/
Date: Sat Nov 14 2020 15:48:51 GMT+0530 (India Standard Time)
Uptime: 10.2 s

Platform information
Browser: Chrome
Browser version: 86.0.4240.198
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
C3 release: r218 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment]
I'm afraid that in terms of bug reports, your report is not actionable unless you follow the bug report requirements. It also looks like you additionally [posted the same problem to the forum here](https://www.construct.net/en/forum/construct-3/general-discussion-7/failed-start-preview-try-152120#forumPost1027716) which is a better place to start if you are unable to file an issue following all the guidelines, so closing this issue.
