### ISSUE TITLE
fonts doesnt work after export for release

### ISSUE THREAD

**Issue by AmrYami** [Scirra/Construct-3-bugs#4346]
## Problem description

 after i use any fonts in my project it works before export after export it didnt work in release like ("kfgqpc uthmanic Script HAFS") i used as font family and attach 2 images to see what i means before and after export
fonts files i used all links in drive [https://drive.google.com/drive/folders/1C8twHLMJoUSUD97zuwYsdYqwMpnMuZAP?usp=sharing](url)

## Attach a .c3p
[https://drive.google.com/file/d/1HWF3vsuOXcU9_H59Its_C4z652gCshwe/view?usp=sharing](url)

## Steps to reproduce

1.add font to project
2. export project for release
3.the font doesnt work after export

## Observed result

[https://drive.google.com/file/d/1aM1AMXyCTfYSkNWc09IJvXLCbNL8-lEX/view?usp=sharing](url)
## Expected result
[https://drive.google.com/file/d/1CuNBFIyLUxaQZ_PShlqww0JeYqrWwz90/view?usp=sharing](url)

## More details

[https://drive.google.com/file/d/1oWNgKo-LHILjLqlPSVM6BO8XCHVaPMb8/view?usp=sharing
](url)

## System details

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
None of these links are public. Please provide public links for issue reports.

**Comment by AmrYami** [comment]
i solve it thanks
