### ISSUE TITLE
Pressing ESC while renaming an Animation closes the Animation Editor

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4347]
## Problem description

When pressing ESC to cancel the renaming of an Animation, the entire Animation Editor closes. When editing a name, ESC is meant to cancel only the renaming.  

## Attach a .c3p

(Any included Demo project)

## Steps to reproduce

1. Select a sprite.
2. Open the animation editor.
3. Right-click on any animation and select "Rename"
4. Press ESC.

## Observed result

The Animation Editor closes.

## Expected result

The renaming of the sprite is cancelled, and control returns to the previous tool.

## More details

**Affected browsers/platforms:** Chrome 86

**First affected release:** Construct r218

**Comment by AshleyScirra** [comment]
I can reproduce in r218 but it appears to be fixed in r224. Please see the bug report guidelines: they require you only report issues that occur in the latest beta release, to avoid reporting issues that are already fixed.

**Comment by brushfe** [comment]
Right, sorry! Didn't catch that.
