### ISSUE TITLE
iOS14 & UserMedia (Camera) not working again

### ISSUE THREAD

**Issue by andygilbert29** [Scirra/Construct-3-bugs#4348]
## Problem description

This has come up before as I reported this issue back in 2018 when I believe iOS went into version 12+

The usermedia or camera does not work.

## Attach a .c3p
[camera_issue_ios.zip](https://github.com/Scirra/Construct-3-bugs/files/5548899/camera_issue_ios.zip)

## Steps to reproduce

1. Build attached project
2. Run from Xcode
3. Camera doesn't work

## Observed result

Nothing happens, can see this in debug window.

WARN: Error requesting camera: TypeError: undefined is not an object (evaluating 'navigator["mediaDevices"]["getUserMedia"]')

## Expected result

The camera to work.

## More details

Latest Xcode
iOS14.2
Iphone XR

**Affected browsers/platforms:** 

R225

**First affected release:** 

## System details

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
I'm afraid this is a [bug in iOS](https://bugs.webkit.org/show_bug.cgi?id=188360). Apple need to fix it.

**Comment by andygilbert29** [comment]
HI, this is not good, is there any other way to open the camera and get a photo into the app?

Andy

**Comment by AshleyScirra** [comment]
I'm afraid not. It's a problem Apple need to fix.
