### ISSUE TITLE
Import Drag and Drop Sprite Crash

### ISSUE THREAD

**Issue by SupraBagels** [Scirra/Construct-3-bugs#435]
## Problem description

60% of the times when dragging and drop a sprite from file explorer, Construct crash with an error listed below.

## Attach a .c3p

Any project.

## Steps to reproduce

1. Open File Explorer
2. Drag and drop an image into the project
3.  60% of the time it crashes.

## Observed result
<details><summary>My error code</summary>
`Error report information
Type: unhandled exception
File: https://editor.construct.net/r34/main.js, line 61, col 123049
Message: Uncaught Error: invalid size
Stack: Error: invalid size at E.ǃOyi (https://editor.construct.net/r34/main.js:61:123055) at window.ǃOxf.ǃOyn (https://editor.construct.net/r34/main.js:61:110440) at window.ǃOxf.ǃOyy (https://editor.construct.net/r34/main.js:61:110687) at window.ǃOxf.ǃOy$ (https://editor.construct.net/r34/main.js:61:110213) at window.ǃOyj.ǃOyd (https://editor.construct.net/r34/main.js:61:113096) at E.ǃOyd (https://editor.construct.net/r34/main.js:61:122098) at u.ǃOyd (https://editor.construct.net/r34/main.js:61:191294) at d.ǃuC.ǃhu (https://editor.construct.net/r34/main.js:61:379665) at d.ǃuC.ǃhu (https://editor.construct.net/r34/plugins/sprite/plugin.js:1:8610) at d.ǃuC.ǃzN (https://editor.construct.net/r34/plugins/sprite/plugin.js:1:8410) at o.ǃzN (https://editor.construct.net/r34/main.js:61:208219)
Construct 3 version: r34
URL: https://editor.construct.net/
Date: Sat Jun 03 2017 15:15:41 GMT-0400 (Eastern Daylight Time)
Uptime: 18.1 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r34

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context`
</details>

## Expected result

My sprite into the game.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r34

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 22 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Can you provide the image you are trying to import so we can reproduce exactly what you're doing?

**Comment by SupraBagels** [comment]
The problem is with any images (.png).

**Comment by SupraBagels** [comment]
[https://youtu.be/nquzW--CQ3I](url)

**Comment by AshleyScirra** [comment]
I imported over 30 images like your video showed and it worked fine, no crash. We've also not had any reports from anyone else about this. So it might be something to do with the specific images you're using (maybe to do with their exact sizes). Can you provide the images you are trying to import so we can reproduce exactly what you're doing?

**Comment by SupraBagels** [comment]
@AshleyScirra this is my images: [https://drive.google.com/open?id=0BzGqd7KsR_dzc1drUklnZ04xZ0U](url)

**Comment by AshleyScirra** [comment]
No updates for ~2 weeks so closing.
