### ISSUE TITLE
containsPoint doesn't take object area 

### ISSUE THREAD

**Issue by z006** [Scirra/Construct-3-bugs#4350]
## Problem description

pushed variable are boolean.
if the browser have free space beyound workspace-i just cant find where is area of containsPoint of object.if no free space(image#2)-i can found an active space,but it's too tight,and it's at the bottom of object when "pushed"=0,and jump to the top of object when "pushed"=1
if i try to write down sprites[i].instVars.pushed=false(or true); it get a NaN context.

## Attach a .c3p

https://drive.google.com/file/d/14LiFwCQ_268JqpdKoSpxxrFyJUH5sEPZ/view?usp=sharing

## Steps to reproduce

1.run project in debug mode
2.open card_24 properties
3.watch on instance variable "pushed",and try to click on card,like marked on image#2,watching on variable
4.close debug
5.change at code rows sprites[i].instVars.pushed=0; to sprites[i].instVars.pushed=false; ,sprites[i].instVars.pushed=1; to sprites[i].instVars.pushed=true; and sprites[i].instVars.pushed==1 to sprites[i].instVars.pushed==true
6.repeat steps 1-3.for now you get the NaN in "pushed" after click instead true or false,but complete sprite object became clicked,not just slim line on top|bottom

## Expected result

full sprite object clicked,not just slim line,and variable state changes without mistake

## More details
![Untitled-1](https://user-images.githubusercontent.com/73407299/99328023-e30c6800-2883-11eb-8575-0889d4421c27.jpg)
![Untitled-2](https://user-images.githubusercontent.com/73407299/99328035-e7d11c00-2883-11eb-838f-4bfdcdbe0ebc.jpg)

**Comment by AshleyScirra** [comment]
It's not a bug, it's a mistake in your code. The clientX/clientY properties of input events are in a different co-ordinate system to the game. You need to use the layer `cssPxToLayer` method to convert between the co-ordinate systems.

**Comment by z006** [comment]
but what about "sprites[i].instVars.pushed=false(or true); it get a NaN context"

**Comment by AshleyScirra** [comment]
If you believe it's a bug in Construct you need to file a minimal issue following all the guidelines, otherwise I would assume it's a mistake in your code.

**Comment by z006** [comment]
it's easy.i'll try publick it here,if it not ok-tell me,i will open new task with it

## Problem description

pushed variable are boolean.
if i try to write down runtime.objects.Card_24.getFirstInstance().instVars.pushed=false it get a NaN context.

## Attach a .c3p

https://drive.google.com/file/d/1zI30Tty--qJo2VN1VlfOH3EExoCHFx5a/view?usp=sharing

## Steps to reproduce


1.run project in debug mode
2.open card_24 properties
3.watch on instance variable "pushed",and click on button,watching on variable


## Expected result

variable state changes without mistake

**Comment by AshleyScirra** [comment]
Please file a new issue following all the guidelines. The bug report guidelines advise to do this if your issue is closed.

**Comment by z006** [comment]
done
