### ISSUE TITLE
More instance objects Hierarchy problems

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4351]
## Problem description

When multiple instances of the same object in layout. 
Add child objects to some of these instances through the context menu
other instances of the object, will problems 

## Attach a .c3p

https://www.construct.net/en/tutorials/create-animations-scene-graph-2619

## Steps to reproduce

1. disabled Event addChild 

2. Use Layout Context Menu addChild
![image](https://user-images.githubusercontent.com/45864744/99361872-b8ef9000-28ed-11eb-8adf-17036844935d.png)

3. preview
![Imgur](https://i.imgur.com/YmRF619.png)

4. Other instances problems
![image](https://user-images.githubusercontent.com/45864744/99361648-61512480-28ed-11eb-91d0-b360c1472258.png)

Only the parent object normal

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
As far as I can tell, this is by design. It only applies the hierarchy to the objects you set up the hierarchy for in the editor, which is what it's supposed to do.

**Comment by XHXIAIEIN** [comment]
> As far as I can tell, this is by design. It only applies the hierarchy to the objects you set up the hierarchy for in the editor, which is what it's supposed to do.

i think, the instance objects on the right should not be apply.
