### ISSUE TITLE
Tilemap pencil never stops drawing in a popup browser tab.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4352]
## Problem description

If the layout is on a popup tab (popup window, whatever is the name) and then you start drawing with the pencil, it will never stop drawing. Also if you're using eraser, it will never stop erasing and so forth.

## Attach a .c3p

any file should present it.

## Steps to reproduce

1. Have a Tilemap on the layout editor on a popup tab.
2. Start editing with the pencil or eraser.
3. Observe that it never stops when you stop holding the mouse button.

## Observed result

Tools never stop working.
 
## Expected result

Tools stop working when you stop holding the mouse button.

## More details

**Affected browsers/platforms:**  Tested in Edge.

**First affected release:**  Tested in 225.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
