### ISSUE TITLE
Issue #4303 is back

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#4353]
## Problem description

There's not much to say, just take a look at #4303 and you will have all the necessary information. But, in short, it's not possible to close a few windows by pressing Esc, which was already fixed in a previous beta. Maybe it's some sort of regression?

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
It is a regression, it happens if the main panel in the Animations editor has focus, then the ESC key won't work. In any other case it will work. This one will be fixed in the next beta. Unfortunately it was re introduced after fixing another, unreported issue.
