### ISSUE TITLE
C2 project can't be imported in C3

### ISSUE THREAD

**Issue by arcadehistory** [Scirra/Construct-3-bugs#4354]
## Problem description
One of my C2 project cant' be opened in C3. It said to choose a valid .capx file, but the file is valid since it open fine in C2.

## Attach a .c3p
Link to the capx file in question : [https://www.arcade-history.com/temp/coinopboy4-6.capx](https://www.arcade-history.com/temp/coinopboy4-6.capx) (right click, "save as" on this link)

## Steps to reproduce
1. Try to open the attached .capx file in Construct 3
2. Get the error message.

## Observed result
An error message occurs saying the capx file is not valid.

## Expected result
Import the C2 project in C3.

## More details
C2 project saved using the latest version of C2 (Release 279)

**Comment by AshleyScirra** [comment]
I believe I already responded to your support email, so this should be solved.
