### ISSUE TITLE
boolean instance variable set "NaN" instead "false"

### ISSUE THREAD

**Issue by z006** [Scirra/Construct-3-bugs#4355]
## Problem description

pushed variable are boolean.
if i try to write down runtime.objects.Card_24.getFirstInstance().instVars.pushed=false it get a NaN context.

## Attach a .c3p

https://drive.google.com/file/d/1zI30Tty--qJo2VN1VlfOH3EExoCHFx5a/view?usp=sharing

## Steps to reproduce

1.run project in debug mode
2.open card_24 properties
3.watch on instance variable "pushed",and click on button,watching on variable

## Expected result

variable state changes without mistake

**Comment by AshleyScirra** [comment]
Boolean instance variables were accidentally exposed as a number (0 or 1) instead of a boolean type. It's fixed for the next beta so you can use true/false values instead.
