### ISSUE TITLE
Screenshot share not working on IOS

### ISSUE THREAD

**Issue by karimlahbach** [Scirra/Construct-3-bugs#4357]
## Problem description
Share button not working on ios

## Attach a .c3p
You can use the screenshots example

## Steps to reproduce

1. export the project to Xcode
2. open the project on the simulator
3. watch the result

## Observed result
the share button not working

## Expected result
the button should work

## More details

**Affected browsers/platforms:*chrome* 

**First affected release:*r225* 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
