### ISSUE TITLE
Mobile Iap not working on IOS

### ISSUE THREAD

**Issue by karimlahbach** [Scirra/Construct-3-bugs#4359]
## Problem description
the mobile IAP not working 

## Attach a .c3p
[IAP TEST.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5575051/IAP.TEST.c3p.zip)

## Steps to reproduce

1.Add Mobile IAP and add product
2.Export to xcode 
3.Try to Purshase the product

## Observed result
Nothing Happen

## Expected result
to Purshase the product

## More details

**Affected browsers/platforms:*chrome* 

**First affected release:*r225* 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Are you sure you have correctly configured the IAP for your app? I've tested this before and it works fine, as far as I'm aware it's working for all other users, and the most common cause of problems is a mis-configuration of the app. These types of issues are particularly time-consuming to investigate so please double check that you have set this up correctly.

**Comment by karimlahbach** [comment]
i will check again to make sure everything is correct

**Comment by karimlahbach** [comment]
i check again and still have the same problem ( truly have no idea if i did something wrong )
can you test this again Ashley 
Thanks

**Comment by AshleyScirra** [comment]
I think there is just a simple mistake in your events. Event 2 - *Is registration complete* - is always true, so it will overwrite the contents of the text object with "Product complete". This means you'll never see the text object get changed to "Product ready", "Done" or "Fail". You should instead use the trigger *On store registration success*. You should also use *On store registration failed* to check for any error registering the store.

Can you confirm if making these updates solves the problem?

**Comment by karimlahbach** [comment]
I just did as you said but the text not changing at all 
this the Xcode log
<img width="1270" alt="Screen Shot 2020-11-24 at 12 48 31" src="https://user-images.githubusercontent.com/22240696/100090590-aaf0c080-2e53-11eb-88fb-3d23313f2b18.png">

**Comment by AshleyScirra** [comment]
Closing as this is an old issue and we lack sufficient information to be able to investigate (the first project file appeared to have a mistake and the follow-up comment did not share a project file, so we cannot really be sure we are testing with a valid project file that does not have any mistakes). I suspect this is either a IAP configuration error (a common problem but not a bug) or a mistake in events. If you still think there is an issue please double-check your events are correct, the configuration is correct, you've followed all the advice in the IAP manual entry, and the issue still reproduces in the latest release, and then file a new issue following all the guidelines.
