### ISSUE TITLE
Glokar demo crashes in Nvidia shield tablet

### ISSUE THREAD

**Issue by triptych** [Scirra/Construct-3-bugs#436]
## Problem description

Glokar demo crashes on preview in Nvidia shield tablet

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
Just use the glokar demo files from the website

## Steps to reproduce

1.go to editor.construct.net using an Nvidia shield tablet 
2.click on glokar demo open project
3.click on preview
4. A new window opens with construct loading logo, then switches to the "aw snap"  window.
5.close window and observe that the original editor window is now also in the aw snap state

## Observed result

Preview window crashes as well as editor window

## Expected result

See a running demo of the Glokar code

## Affected browsers

* Chrome: yes
* Firefox: na
* Edge: na
* Safari: na

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Shield tablet k1.
Android 7.0

</details>

**Comment by AshleyScirra** [comment]
"Aw snap" means the browser crashed, which is a browser bug, not a C3 problem. I'd recommend filing a Chrome bug at crbug.com for that.

**Comment by triptych** [comment]
Platform information
Browser: Chrome
Browser version: 58.0.3029.83
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Android
Operating system version: 7.0
Operating system architecture: 32-bit
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Linux; Android 7.0; SHIELD Tablet K1 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Safari/537.36
C3 release: r34

Local storage
Storage quota (approx): 304 mb
Storage usage (approx): 169 kb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA Tegra
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 2047
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by triptych** [comment]
It may be a browser bug but it still prevents a user of your tool from using it on mobile devices. Perhaps there is a way to prevent or work around an issue despite it being caused by the browser.

**Comment by triptych** [comment]
I'm able to cause this happening 100% of the time, so that at least suggests that you might be able to find the root cause.

**Comment by triptych** [comment]
Browser crashes like this on mobile suggest memory issues. I'm able to preview a new, empty project.

**Comment by AshleyScirra** [comment]
Chrome crashed. There's nothing we can do about it. I'd file the bug on your behalf, but I don't have the device you're using, so it would just make me an unnecessary middleman.

**Comment by triptych** [comment]
I'm just posting the behaviors I'm seeing. The larger project is probably taking more memory because the PC has more working memory to spare. Ultimately I will bet that some memory leak in the browser or some memory optimization you do for something else will fix this. But this bug makes it impossible to do any significant work on a tablet.

**Comment by triptych** [comment]
Filed an issue with Chrome. https://bugs.chromium.org/p/chromium/issues/detail?id=729414#

**Comment by AshleyScirra** [comment]
Thanks, will close this report and follow up at that bug.

**Comment by triptych** [comment]
I'm unable to reproduce the issue in Chrome Canary on Android, so perhaps they've patched the issue in an upcoming build.
