### ISSUE TITLE
Cordova Plugin White-list request for the Cloud Build

### ISSUE THREAD

**Issue by emi415064** [Scirra/Construct-3-bugs#4363]
cordova-admob-plus@0.40.0
cordova-plugin-firebasex@11.0.3 
cordova-plugin-camera-preview@0.12.1
cordova-plugin-codeplay-facebookads-free@0.1.5
com.pollfish.cordova@1.1.0

https://www.construct.net/en/make-games/addons/480/admob-plus
https://www.construct.net/en/make-games/addons/466/ultimate-camera

thanks.

That is it.

I can not speak English.

**Comment by AshleyScirra** [comment]
Merged in to #4381
