### ISSUE TITLE
Crash when opening debugger - Crash Report

### ISSUE THREAD

**Issue by calminthenight** [Scirra/Construct-3-bugs#4364]
## Problem description

Construct crashed when attempting to open debugger. Could not access crash report but console log is attached. No file as recent work was lost. Understand that this may be closed due to no .c3p attached but just providing the info in case it is useful.

I had duplicated a tilemap and added some new tiles. When I tried to open the debugger it crashed and then got stuck on "Preparing Project Files". The session had been active for a long time and the debugger had been successfully used previously. 

## Attach a .c3p

No file attached as recent work was lost in crash.

## Steps to reproduce

N/A

## Observed result

N/A

## Expected result

N/A

## More details

Chrome Version 87.0.4280.66 (Official Build) (64-bit)
Construct 3 R255

Some messages have been moved to the Issues panel.
View issues
register-root-sw.js:17 Registered root service worker on https://editor.construct.net/
main.js:252 Error while parsing the 'sandbox' attribute: 'allow-storage-access-by-user-activation' is an invalid sandbox flag.
main.js:2022 Stop!
main.js:2022 This is a browser feature intended for developers. If someone told you to copy and paste something here to enable a feature or "hack" something, it is a scam and may allow them to steal your account information or your work.
main.js:2022 Note: this is the developer tools console for the Construct editor. If you're looking for developer tools for preview, be sure to open developer tools for the preview window instead.
main.js:2032 Registered service worker on https://editor.construct.net/r225/
153
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' blob:". Either the 'unsafe-inline' keyword, a hash ('sha256-2EA12+9d+s6rrc0rkdIjfmjbh6p2o0ZSXs4wbZuk/tA='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
graph.microsoft.com/v1.0/me/drive/root:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
editor.construct.net/:1 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' blob:". Either the 'unsafe-inline' keyword, a hash ('sha256-NvMGATtE8aAzsDTglKZDn1P+hRAwruqDkuN2YPcJQzM='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
graph.microsoft.com/v1.0/me/drive/root:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
projectResources.js:2463 Error starting preview:  TypeError: Cannot read property 'width' of null
    at l.bb.E9c (allEditorPlugins.js:252)
    at l.bb.tHc (allEditorPlugins.js:251)
    at n.Tb (projectResources.js:105)
    at Object.oea (projectResources.js:1026)
    at n (main.js:437)
    at k (main.js:437)
﻿
​
Content Security Policy blocks inline execution of scripts and stylesheets
The Content Security Policy (CSP) prevents cross-site scripting attacks by blocking inline execution of scripts and style sheets.

To solve this, move all inline scripts (e.g. onclick=[JS code]) and styles into external files.

⚠️ Allowing inline execution comes at the risk of script injection via injection of HTML script elements. If you absolutely must, you can allow inline script and styles by:

adding unsafe-inline as a source to the CSP header
adding the hash or nonce of the inline script to your CSP header.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.66
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 49 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid as explained in the bug report guidelines, unless you can provide steps to reproduce it's generally impossible to do anything about your report.
