### ISSUE TITLE
teste ads 

### ISSUE THREAD

**Issue by rodriabr** [Scirra/Construct-3-bugs#4365]
## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by rodriabr** [comment]
I ask for new evaluation, please

**Comment by AshleyScirra** [comment]
Please don't file empty issue reports and later edit them. We close any issue reports missing details.

The project shows you a warning on export that some details are missing which also says the app may not work if you don't fill them in. You should read the warning and do what it tells you to.
