### ISSUE TITLE
test ads

### ISSUE THREAD

**Issue by ironmanlegends** [Scirra/Construct-3-bugs#4367]
## Problem description
if using the ad plugin does not open the application

## Attach a .c3p
[TEST_ADS.zip](https://github.com/Scirra/Construct-3-bugs/files/5584920/TEST_ADS.zip)

## Steps to reproduce

1.export apk
2.install apk
3.try to open apk

## Observed result
![test ads](https://user-images.githubusercontent.com/74920229/99999165-8090fb80-2d9e-11eb-9914-695d1452c37b.png)

## Expected result
open and show ad

## More details
if using plugin, ad does not open the app

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The Android application ID is incorrect. It should be the ID provided by AdMob.

Please make sure your project is correctly configured before filing bugs. Check the [Mobile Advert manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/mobile-advert).
