### ISSUE TITLE
Adding Array to Family Causes Crash

### ISSUE THREAD

**Issue by daleinen7** [Scirra/Construct-3-bugs#437]
## Problem description

At some point after adding an initial batch of arrays to a family when I try to add more Construct crashes.

## Attach a .c3p

[arrayFamilyCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/1049982/arrayFamilyCrash.zip)

## Steps to reproduce

1. Open a new project
2. Create an array
3. Add that array to a new family
4. Create a second array
5. Add the second array to the family

## Observed result

Construct crashes

## Expected result

The second array to be a part of the family

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r34/main.js, line 61, col 158224
Message: Uncaught Error: behaviors not supported
Stack: Error: behaviors not supported at s.ǃKr (https://editor.construct.net/r34/main.js:61:158230) at ǃKr.next () at ǃO.ǃU.ǃEM.ǃECx.ǃECv (https://editor.construct.net/r34/main.js:149:45069) at HTMLButtonElement.ǃECa.onclick (https://editor.construct.net/r34/main.js:149:42627)
Construct 3 version: r34
URL: https://editor.construct.net/index.html
Date: Sat Jun 03 2017 17:25:41 GMT-0500 (Central Daylight Time)
Uptime: 151.4 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r34

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 550 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r35.
