### ISSUE TITLE
Crashes when you change font in Text Plugin

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#4371]
## Problem description

Crashes when you change font in Text Plugin

## Attach a .c3p

[test.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5596100/test.c3p.zip)

## Steps to reproduce

1. Create a new text
2. Import a new font
3. Change font

## Observed result

C3 crashes with message: RESULT_CODE_KILLED_BAD_MESSAGE
![image](https://user-images.githubusercontent.com/23579630/100215757-b5718f80-2f11-11eb-8ba1-5b76958a0630.png)

## Expected result

No crash

## More details

**Affected browsers/platforms:** Chrome, Windows

**First affected release:** worked in r225 but broke in r226

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by XHXIAIEIN** [comment]
+1

**Comment by AshleyScirra** [comment]
This is a known issue with Chrome 87 when using the [experimental local font picker](https://www.construct.net/en/forum/construct-3/general-discussion-7/experimental-support-local-156753). Turn off experimental features to work around it.

Please note that if you leave experimental features enabled, you are allowing yourself to be opted in to all future experimental features, which may be unstable and crash.
