### ISSUE TITLE
JSON docs "GetType" is only "Type".

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4372]
## Problem description

At the [JSON docs](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/json) the expression "GetType" is only "Type" in the engine.

## Steps to reproduce

1. go to the hyperlink

**Comment by AshleyScirra** [comment]
Thanks, updated the manual entry.

Note for future reference: please file manual errata issues to the C3 bugs, not website bugs.
