### ISSUE TITLE
TextInput does not auto convert integers into string like Text object.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4375]
## Problem description

I spent some time bumping my head against this problem since I was getting integers from a JSON and they were not displaying in a TextInput object, I found out only later that when you try to write an integer into a "Set text" action it throws a warning that the data must be a string.

Maybe an issue, maybe not, but it made me lose some time not really knowing what was going on (since I was bringing data from a JSON, there was no warning) and is counter intuitive since Texts can perform the same task.

## Attach a .c3p

Any file should present it.

## Steps to reproduce

1. Write an integer into a Text, all good.
2. Write an integer into a TextInput through "Set text" or "Append text" actions, throws warning.
3. Write an integer into a TextInput through a JSON.Get(), no warning and no text.

## Observed result

above.

## Expected result

TextInputs could accept integers and convert them into string just like Texts.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please attach a project as per the bug report guidelines. We make it clear that this is required for issue reports, since it saves a lot of time, and makes it much more likely the problem can be resolved.

**Comment by dupuqub** [comment]
[InputIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/5603385/InputIssue.zip)

I did not ignore guidelines, I was very thorough about how to perform the task and find the issue, but here we go. Should I open a new issue?

**Comment by AshleyScirra** [comment]
A .c3p file is required. Please file a new issue. Both points are covered in the guidelines.
