### ISSUE TITLE
r226 breaks 3rd party - preview not starting

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4377]
## Problem description

Black screen when previewing projects with 3rd party plugins.
This issue happens with other plugins I have installed such as GameAnalytics, so it's probably not plugin specific.

## Attach a .c3p

[3rdPartyPlugin.zip](https://github.com/Scirra/Construct-3-bugs/files/5605100/3rdPartyPlugin.zip)

## Steps to reproduce

1. Run and preview the project

## Observed result

Black screen, preview not starting.

## Expected result

Preview should work.

## More details

**Affected browsers/platforms:** Chrome/NWjs

**First affected release:**  Worked in r225 but broke in r226

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is a compatibility problem with the new JavaScript modules mode that I hadn't previously foreseen. The addon developer will need to make a small, quick update to fix it. I've [documented the necessary changes addon developers will need to make on the forum](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/third-party-addon-changes-156802).

In the mean time you can work around this by switching the project "Scripts type" property back to "Classic" - but that option will be removed in a few months, so you'll need to contact the addon developer and get them to update their addon. It should only be one or two lines of code changed to fix it.

**Comment by avishaymizrav** [comment]
> This is a compatibility problem with the new JavaScript modules mode that I hadn't previously foreseen. The addon developer will need to make a small, quick update to fix it. I've [documented the possible changes addon developers will need to make on the forum](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/third-party-addon-changes-156802).
> 
> In the mean time you can work around this by switching the project "Scripts type" property back to "Classic" - but that option will be removed in a few months, so you'll need to contact the addon developer and get them to update their addon. It should only be one or two lines of code changed to fix it.
> 
> Most addons should not be affected: it should only be a problem if they use "sloppy mode" (i.e. pre-2011 style) JavaScript, or if they also still have not updated to support the [new script minifier](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/third-party-addon-changes-153959), a change we announced several months ago in July.

I tried to do the workaround for now, but I don't have that option in the project properties, I tried r227 too, both on chrome and NWjs.

**Comment by AshleyScirra** [comment]
Oops, the 'Scripts type' option was accidentally hidden. I've added it back for the next release.
