### ISSUE TITLE
JSON.Get or GetAsBeaut... or GetAsComp... does not show array.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4378]
## Problem description

When trying to get an array through "Get", "GetAsBeautifiedString" or "GetAsCompactString", it won't show although it exists.

## Attach a .c3p

[arrayissue.zip](https://github.com/Scirra/Construct-3-bugs/files/5605111/arrayissue.zip)

## Steps to reproduce

1. open the file
2. see the results of each request.
3. observe the array does not show, although its length and values are accessible.

## Observed result

values not showing up.

## Expected result

values showing up.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 226

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The text object has BBcode enabled, so it's trying to interpret the array as a BBcode tag. Turn off BBcode and it works correctly.
