### ISSUE TITLE
Mobile Version of C3 is missing loops in system actions

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#4383]
## Problem description

The system actions have a stop loop action but the other loop actions are missing. I can't create a loop. 

## Steps to reproduce

1. Add new system action
2. No loops listed (just stop loop) 

## Observed result

I can't find loop actions (for, for each etc.) 
## More details

![Screenshot_20201129-184632_Chrome](https://user-images.githubusercontent.com/2725603/100549554-db7d9380-3273-11eb-9817-3f43e80e4c94.jpg)

**Affected browsers/platforms:** 
Chrome on Android 

**First affected release:** 
r255
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.66
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Android
Operating system version: 10
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 3
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Linux; Android 10; SM-G975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Mobile Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 66 gb
Storage usage (approx): 191 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: ARM
Renderer: Mali-G76
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_float_blend
EXT_texture_filter_anisotropic
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
> I can't find loop actions (for, for each etc.)

Those are conditions, not actions.
