### ISSUE TITLE
object click area flattened

### ISSUE THREAD

**Issue by z006** [Scirra/Construct-3-bugs#4384]
## Problem description

when i use on object click just "sprites[i].y=sprites[i].y-10;" it's area,where i can click,is the same as object.but if i add  "sprites[i].instVars.pushed=true;" the area flatt to the small strip on botton or top of object(depends of the object took a step up or down)

## Attach a .c3p

https://dropmefiles.com/ngSTo

## Steps to reproduce

1.run the preview
2.try to click on card.you can see that "can click area" are small line(see screenshot below,to easy find it)
3.comment out lines "sprites[i].instVars.pushed=true;" and "sprites[i].instVars.pushed=false;"
4.run the preview again
5.surprise!now "can click area" are same size as card

## Observed result

small click area when i use runtime instvars

## Expected result

area same size as object

## More details

![Untitled-2](https://user-images.githubusercontent.com/73407299/100549878-711e2080-327e-11eb-8f99-bb26be908e93.jpg)

besides i tried using "runtime.getInstanceByUid(this_obj_uid).instVars.pushed=true;".This gave the same result.

**Comment by AshleyScirra** [comment]
The runtime was accidentally firing the "pointerup" event twice. It should be fixed in the next beta.
