### ISSUE TITLE
runtime created instances are not enabled

### ISSUE THREAD

**Issue by z006** [Scirra/Construct-3-bugs#4385]
## Problem description

if i not place instance of object(sprite) on layer in IDE,but create it runtime-i can't do something with it,e.g.:set frame,change instant vars etc.
to find the resource of problem i try to count created objects,and it..zero!

## Attach a .c3p

https://dropmefiles.com/N2Ows

## Steps to reproduce

1.run preview
2.open console
3.you can see the zero objects,but objects are placed on table

## Observed result

created objects are not available

## Expected result

access to objects and their properties

**Comment by AshleyScirra** [comment]
The provided project uses a third-party addon ("BetterOutline"). Please see the bug report guidelines: we cannot support projects using third-party addons, in case they are causing the problem.

Please also do not use upload services that expire the file after a while. We will close your report if the file expires by the time we investigate it, which may take a few weeks.
