### ISSUE TITLE
[Guest User] Unable to preview properly after trying remote preview in the Project bar context menu

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4387]
## Problem description

Unable to preview properly after trying remote preview in the Project bar context menu. 

Guest cannot use [Remote preview], so will pop up a tips when trying to click [Remote preview] in the "Project" bar context menu . But continue to click [preview] again, it always becomes [Remote preview]

## Steps to reproduce

1. use Guest Free edition
2. open any .c3p project
3. click [Remote preview] in the "Project" bar context menu. 
4. close the "Free edition limit" tips
5. click [preview] in the "Project" bar context menu. 
6. "Free edition limit"

In this case, click the **▶** preview button at the top also does not work.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
