### ISSUE TITLE
runtime created instances are not enabled

### ISSUE THREAD

**Issue by z006** [Scirra/Construct-3-bugs#4389]
## Problem description

if i not place instance of object(sprite) on layer in IDE,but create it runtime-i can't do something with it,e.g.:set frame,change instant vars etc.
to find the resource of problem i try to count created objects,and it..zero!

## Attach a .c3p

[dbg.zip](https://github.com/Scirra/Construct-3-bugs/files/5616099/dbg.zip)

## Steps to reproduce

1.run preview
2.open console
3.you can see the zero objects,but objects are placed on table

## Observed result

created objects are not available

## Expected result

access to objects and their properties

## More details
this is an analogue of the previously created task, but without the BetterOutline module, which did not affect the result

**Comment by AshleyScirra** [comment]
This is an existing quirk in the event system: newly created instances aren't fully created until the next top-level event. It's the same with the 'Create object' action and the `createInstance` method.
