### ISSUE TITLE
Unable to get persistent storage 

### ISSUE THREAD

**Issue by triptych** [Scirra/Construct-3-bugs#439]
## Problem description

Unable to load or save from storage due to permission issue.

## Attach a .c3p

This is not applicable as issue happens before any file is opened.

## Steps to reproduce

1. go to editor.construct.net
2.click menu, then about
3.scroll to click to request persistent storage

## Observed result

An error message pops up saying "Unable to get permission to persist storage. Try bookmarking this page ..."

## Expected result
Persistent storage should work

## Affected browsers

* Chrome: yes/no
* Firefox: did not test
* Edge: did not test
* Safari: did not test

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r34

Local storage
Storage quota (approx): 6.4 gb
Storage usage (approx): 21 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 730 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by triptych** [comment]
This is happening on both my Windows 10 PC and my Windows 10 Laptop - two completely different machines.

**Comment by shortercode** [comment]
Have you bookmarked the page? Chrome uses a kind of "user trust" heuristic to decide if this is allowed, so if you regularly visit a page / allow notifications / bookmark a page then it is automatically allowed.

Also this does not stop you from saving, it just adds extra protection to the storage.

**Comment by AshleyScirra** [comment]
It's up to Chrome if it grants permission or not, so I don't think there's anything we can do about whether or not you get the permission. However @shortercode are you blocked from the local browser save option if you don't get permission? Maybe we should adjust that to allow it to be used even if you don't have the permission, but show an extra warning on the dialog itself.

**Comment by AshleyScirra** [comment]
Oops, didn't mean to close.

**Comment by shortercode** [comment]
It wouldn't block you, but it will ask you for permission each time you open the local save dialog if it hasn't been granted.

Even if you decline the permission request or it fails it will always open the local save dialog. In the case of failure it will show you a warning dialog first though.

**Comment by AshleyScirra** [comment]
OK, sounds like that's fine, it will basically hassle you until it gets permission. We can't force Chrome to grant permissions, so don't think there's anything else we can do here.
