### ISSUE TITLE
 issue with simple minify - could not find com.google.javascript.jscomp.CommandLineRunner

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#4391]
## Problem description

When minifying an existing project the minifying script dialog window stays open indefinitely, looking at browser console there is an error coming from cheerpOS.js where it cannot load class com.google.javascript.jscomp.CommandLineRunner

screenshot

https://drive.google.com/file/d/1QMtm2cv8qH46fGDc_Ocoe_LEWlVCljfy/view?usp=sharing 

## Attach a .c3p

https://drive.google.com/file/d/13jtN1ubqcm4bCWk5_x9zUUDw41Pb0a_p/view?usp=sharing

## Steps to reproduce

1. new project
2. add script file (default main.js)
3. export html project (simple minify enabled) 

## Observed result

minify never completes, and browser console throws error

## Expected result

the project would export correctly

## More details

**Affected browsers/platforms:** Edge/Chrome

**First affected release:** r227

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 87.0.664.47
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.47
C3 release: r227 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 307 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by armandoalonso** [comment]
the latest hotfix has fixed this issue thank you.

**Comment by AshleyScirra** [comment]
Yep, spotted this after r227 and today's r227.2 should fix it.
