### ISSUE TITLE
Copying event sheet doesn't copy tab color.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4392]
## Problem description

When you change a tab color or tab font color, it doesn't get applied when copying the event sheet.

![Capture](https://user-images.githubusercontent.com/34659544/100861098-1f3cec80-3470-11eb-9209-12227a48d32d.PNG)

## Attach a .c3p

any file should present it.

## Steps to reproduce

1. Create an event sheet.
2. Change its tab and/or tab font color.
3. See that the copy doesn't get the tab styles applied.

## Observed result

above.

## Expected result

getting the original colors.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 227

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
