### ISSUE TITLE
Due to the last r227.2 update of my Android game, players complained that the screen is stoped in start page.

### ISSUE THREAD

**Issue by abdoyami** [Scirra/Construct-3-bugs#4393]
## Problem description
Due to the last r227.2 update of my Android game, players complained that the screen is stoped in start page.
![Screenshot_٢٠٢٠-١٢-٠٢-٢٠-٠٨-١١-٣٨٥_com pogames test](https://user-images.githubusercontent.com/49926149/100914811-37e2ec00-34dc-11eb-8810-3dec68dfbcb5.jpg)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help unless you follow the bug report guidelines.

To help diagnose the issue you can try attaching USB debugging to an affected device, which lets you check the browser console. Alternatively find a way to reproduce the problem on any device, and file an issue for that.
