### ISSUE TITLE
Adding description to a new instance variable doesn't show right away.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4397]
## Problem description

When writing the description of a recently created instance variable, you must refresh the instance variables editor to see it.

## Attach a .c3p

Every file should present it.

## Steps to reproduce

1. Open any instance variable editor.
2. Add a new variable and keep the variable editor open.
3. Add a description to the variable.
4. Observe upon closing the variable editor, the description is not shown yet.
5. If you refresh the editor somehow, by opening or closing the editor, or opening and closing some variable editor, then it shows.
6. It does NOT happen for a variable that already exists, only when adding a description to a new variable.

## Observed result

A delayed description update.

## Expected result

Immediate description update.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 227.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
