### ISSUE TITLE
Rectangle's shape in debug mode changes when the layout's angle is increasing/decreasing

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#4399]
## Problem description

Perhaps this is not really a "problem".
Rectangle's shape in debug mode changes when the layout's angle is increasing/decreasing.
In other words: when the layout is spinning/turning, the rectangle of sprites change size, in a predictable way.
You can only see this happening in debug mode, when selecting an instance of a sprite.

No functionality seems to be missing or broken.
From what I see in the included sample project, everything works. It just looks weird. Or at least - I do not understand what I am seeing.

In the example project I added small sprites, to see if overlap works as intended and it does.

## Attach a .c3p

.c3p renamed as zip attached as comment below.

## Steps to reproduce

- Run the project in debug mode
- In the Inspector lane, click on either "Pink" (sprite) or "green" (sprite).
- Click on an instance number (for example "0").
It now shows a red dotted outline, this is the rectangle that is changing shape.

## Observed result

The red dotted outline (rectangle) changes shape, when the layout is spinning. (when the project is running and not paused)

## Expected result

A red dotted outline that matches the sprite's size and angle.
(unless I do not fully understand)

## More details

**Affected browsers/platforms:** 

Tested in Chrome.

**First affected release:** I have not payed attention to this before.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 86.0.4240.198
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
C3 release: r227.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 38 gb
Storage usage (approx): 2.9 gb (7.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by rogerty** [comment]
[testangle.zip](https://github.com/Scirra/Construct-3-bugs/files/5641429/testangle.zip)

**Comment by AshleyScirra** [comment]
> No functionality seems to be missing or broken.

Please do not file issues if nothing is broken. If you have a question, please post to the forum instead.

**Comment by rogerty** [comment]
What if I change the wording to "the way objects are highlighted in debug mode is broken"?

**Comment by AshleyScirra** [comment]
Oh right, I see what you mean now. Fixed for next beta. It's best not to state that nothing is broken if something's not working, it undermines your report!
