### ISSUE TITLE
Editor state is not persisted between pageloads on Android and Windows (possibly others)

### ISSUE THREAD

**Issue by triptych** [Scirra/Construct-3-bugs#440]
## Problem description

Reloading the page or leaving the browser and coming back clobbers the current state of the tool.

## Attach a .c3p

Not necessary to see the behavior

## Steps to reproduce

1.go to editor.construct.net
2.create a new project and save it 'locally'
3.reload the tab or leave the browser and go to another app and come back, or even just go to another tab and then come back.

## Observed result

App reloads and starting dialog pops up. All sheets and events tabs from the saved project are closed.

## Expected result

Preserve the current active state between reloads

## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.83
Browser engine: Blink
Browser architecture: 32-bit
Context: browser
Operating system: Android
Operating system version: 7.0
Operating system architecture: 32-bit
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Linux; Android 7.0; SHIELD Tablet K1 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Safari/537.36
C3 release: r34

Local storage
Storage quota (approx): 390 mb
Storage usage (approx): 351 kb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA Tegra
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 2047
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by triptych** [comment]
This loss of state also occurs on Windows Chrome as well. Open a project, hit reload on the page and the tool goes back to an initial state with no tabs and shows the initial popup window.

**Comment by AshleyScirra** [comment]
@DiegoScirra handles the UI state stuff, but not sure it's possible to save the state when the tab is being closed/reloaded, there's not always enough time in the page unload handler to save data.

**Comment by shortercode** [comment]
@triptych We currently don't persist project state in this way, the project layout ( open tabs etc. ) will persist but we don't attempt to reopen projects on load. So you have to open the project after the editor has loaded.

Unfortunately Android often closes things in the background to save on memory, decrease battery consumption and increase performance. So when you navigate back to the tab it will reload the page. Under some circumstances and depending on the device you will find the tab still open, but it's more likely it was closed.

**Comment by AshleyScirra** [comment]
Apart from #174 for Android, closing as won't fix since this just sounds like how browsers work. If you press 'Reload' you're giving the browser an explicit instruction to basically reboot the web page.
