### ISSUE TITLE
Double click issue using wacom tablet since r227 on MacOs

### ISSUE THREAD

**Issue by Mak14** [Scirra/Construct-3-bugs#4401]
## Problem description
When clicking on the triangle buttons at the properties or the other bars ( e.g. Editor, or Advanced option), 
the menu is rolling up and down quickly, so i can't unroll the menu if it is closed
Also, there is an issue during this bug- when the sprite is unable to click and drag with the the first click ( without releasing button) on the scene editor.
This is happens on Mac using wacom pen. With the mouse there is no problems.

## Attach a .c3p
The issue is in the editor.

## Steps to reproduce

1. Open R227 build 
2. Try to click triangle button from the properties menu to show/hide the options ( Advanced, or Editor)
3. 

 Parallel issue

1. Open any layout scene
2. Click and drag any object without releasing click
 

## Observed result
1- Properties menu is not showing, it is just rolling back and forth

2- The objects on the layout can't be dragged.
    ( it is only drags after Click to select object -> release Click -> Click again to drag selected object)

## Expected result
Menu should be opened as it worked in 225

Objects should be selected and dragged instantly with the first click

## More details

This is happens in any browser and on the Desktop build.
r227-2 Has this issue
r225 works fine

Mouse input  doesn't have these issues in r227-2 

These issues are only with the Wacom pen.

**Affected browsers/platforms:** 

**First affected release:** 
r227
## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.49.2
Browser engine: Chromium
Browser architecture: (unknown)
Context: nwjs
Operating system: Mac OS X
Operating system version: 10.15_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.49.2 (like Chrome/86.0.4240.111)
C3 release: r227.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 104 gb
Storage usage (approx): 509 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 5300 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Both issues will be resolved in the next beta.
