### ISSUE TITLE
mesh editor: if mesh size is too big maybe cause the mouse wheel not work

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4404]
## Problem description

If the mesh size is too big(> 20 x 20) use [SceneGraphTest Examples 'Head' Sprite](https://editor.construct.net/r228/#open=skeleton-hierarchy): 

The reason may be that mesh points are very dense, resulting in incorrect focus

When I Edit mesh, Click Sprite mesh point, and press Ctrl + mouse wheel. Zoom In. Probably not work. 
It may also cause the right mouse button to Probably not work.
Sometimes you can zoom out, sometimes you can’t zoom in.

Then Click on the blank space and continue to try 
and Click Sprite( In Mesh editor), press Ctrl + mouse wheel. Zoom In. Probably not working.

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
