### ISSUE TITLE
Clicking random places in Image Points can sometimes cause crash

### ISSUE THREAD

**Issue by GradiusLover2000** [Scirra/Construct-3-bugs#4405]
Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.d.o (https://editor.construct.net/r225/main.js:216:79) at f.Na (https://editor.construct.net/r225/projectResources.js:159:484) at https://editor.construct.net/r225/projectResources.js:1358:138
Stack: TypeError: expected string at Function.d.o (https://editor.construct.net/r225/main.js:216:79) at f.Na (https://editor.construct.net/r225/projectResources.js:159:484) at https://editor.construct.net/r225/projectResources.js:1358:138
Construct 3 version: r225
URL: https://editor.construct.net/
Date: Wed Dec 09 2020 00:39:01 GMT+0000 (Greenwich Mean Time)
Uptime: 4656 s

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB {{This is incorrect, I actually have 32GB}}
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment]
Please provide specific steps to reproduce the problem if you can, otherwise usually it's impossible to help.

Assigning to @DiegoScirra to check the crash report, but if he cannot fix it based on that alone, the issue will be closed unless you can provide all the necessary information.

**Comment by DiegoScirra** [comment]
There doesn't seem to be anything that is obviously wrong and the crash report is not very useful. Will close this one later on if there is no more information.

**Comment by GradiusLover2000** [comment]
I have no way to reproduce the steps.  it was entirely random and uncalled for.  the title is what I did last before it occured.  possibly I left the text box empty before clicking away but I cannot get it to reproduce.
