### ISSUE TITLE
When creating new eventsheet and layout they have different order in the list

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4408]
## Problem description
Seems like bugged ordering. 
![Order_buggg](https://user-images.githubusercontent.com/28864889/101634820-e41f5800-3a31-11eb-9b1a-ff30bc5f3c7a.jpg)

## Steps to reproduce

1.Open new project.  
2.Create new layout.
3.Create new eventsheet

## Observed result
New layout is put last in the list, while eventsheet is put first. This seems bugged or mistake left in place and could be corrected

## Expected result
Main two things should order themself similarly

## More details

Layouts can be reordered, so user can make list order match, but i see no reason for default order to be different, other then inconsistent order left behaind by mistake. ie bug!

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r226 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.3 gb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is currently by design:

- the order of layouts can be rearranged so they follow the logical progression of your game, e.g. LavaLevel3 followed by IceLevel1
- the order of event sheets is automatically sorted alphabetically since they don't have a logical progression, especially since in large projects many will be common events included in other sheets

Therefore you can control the ordering of layouts, but not event sheets, and they may appear in different places.

**Comment by SnipG** [comment]
Good it's not a bug.

Still i am disagreeing, it's very chaotic and looks messy/buggy. As it follows very strict style. Instead Layout and eventsheet to appear on top/bottom,  user then can drag layout to correct place and rename eventsheet which then gets sorted.
* ie user would generate LavaLevel, then IceLevel and then start doing sub levels, when game needs more stuff.
And i think there is logical progression even among common events. 
But this is just me and how i see it.

**Comment by AshleyScirra** [comment]
I think it makes sense if you consider that layers have a sequence, but event sheets do not have a sequence.
