### ISSUE TITLE
Issue with focus on two different things at same time 

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4409]
## Problem description
in Project bar select any object press F2 to rename and copy its name and then paste it in array editor. Repeat this process You'll notice that after pasting in array editor when we click back to any object in project bar then F2 not changing to rename mode and If you press arrow keys up or down then objects in project bar and cells in array editor is highlighting accordingly.

## Steps to reproduce

1. Create Blank project.
2. Insert Sprite
3. Clone sprite several times
4. Create new Array editor width 2 Height 10
5. click Sprite in project bar and press F2
6. Copy Sprite name and paste it in Array Editor 0,0
7. click Sprite2 and press F2 **(You'll notice here F2 is not working)**
8. press UP or DOWN arrow **(you'll notice in both side "Project bar" and in "Array Editor" UP & DOWN key is working)**

## Observed result

Focus on 2 different place at the same time

## Expected result

Focus should on single item

## More details

**Affected browsers/platforms:** 
Tested in Chrome Browser

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r228 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 980 mb
Storage usage (approx): 37 mb (3.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Minimal repro since none provided: [issue4409.zip](https://github.com/Scirra/Construct-3-bugs/files/5688982/issue4409.zip) (please provide a project whenever possible, it saves time and improves the chance the issue can be fixed)

I can reproduce in r228 but it looks like it's working correctly in our development version. I would guess this is something to do with the Pointer Events update that @DiegoScirra already fixed; marking to verify when the next release goes out.

**Comment by AshleyScirra** [comment]
Looks like it's working fine for me in r229. Can you confirm?

**Comment by luckyrawatlucky** [comment]
Yes Its working in r229

**Comment by AshleyScirra** [comment]
Thanks for confirming.
