### ISSUE TITLE
JSON value gets stuck at null if you get the value before it exists.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4410]
## Problem description

If you try to check a value before its key exists, it will get stuck at null

## Attach a .c3p

[jsongetset.zip](https://github.com/Scirra/Construct-3-bugs/files/5679681/jsongetset.zip)

## Steps to reproduce

1. Run the attached file.
2. You can see the value is addressed normally.
3. Enable the line that is disabled.
3. You can see now that when you try to get the value before it exists, it cannot be changed from null anymore.

## Observed result

value stuck at null.

## Expected result

value change.

## More details

**Affected browsers/platforms:** Chrome

228

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by dupuqub** [comment]
Later I tried also checking the condition "Has key" for some JSON address and it also locked its value at null.

When using "Has key" the value was stuck at null even when the value existed prior to the condition evaluation.

I was going to open a new issue, but they seem related and therefore they might get fixed by the same work.

**Comment by AshleyScirra** [comment]
No line is disabled in the provided project. Please provide a project that matches the steps, otherwise the report cannot be investigated.

**Comment by dupuqub** [comment]
Sorry about that, I edited the issue, the [file](https://github.com/Scirra/Construct-3-bugs/files/5679681/jsongetset.zip) is now correct and it should look like below.

![Capture](https://user-images.githubusercontent.com/34659544/101915313-354f5900-3ba4-11eb-9d9b-c4a8d83cdf93.PNG)

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
