### ISSUE TITLE
Editor Crashes On Tiled Background Object Clone

### ISSUE THREAD

**Issue by Evilobjective** [Scirra/Construct-3-bugs#4411]
When cloning a Tiled Background object that is part of a family, the editor crashes.

Cloning a tiled background object that is part of a family crashes the editor. On the attached test capx, the crash happens when trying to clone the tiled background object when it is selected under it's 'Family' group. On my main project (where I discovered the crash) it will also crash when cloning the tiled background object selected under the object folder in the project panel. I could not replicate the crash using the second method in the test project, but the same error reason is given in the report no matter which method triggers on the crash.

## Attach a .c3p

https://www.dropbox.com/s/qzl2sgulhsmq6cz/CrashTestFile.c3p?dl=0

## Steps to reproduce

1. Go to the 'Family' section of the project window
2. Right click the 'TiledBackground' object under 'Family1' and select clone.
3. Admire the crash report. 

## Observed result

The editor crashes.

## Expected result

The tiled background object to be cloned.

## More details

**Affected browsers/platforms:** 

Chrome Windows
OSX Construct 3 Editor

**First affected release:** 

R225

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: animation frame has no content @ Error: animation frame has no content at n.qI (https://editor.construct.net/r225/projectResources.js:192:233) at n.j2 (https://editor.construct.net/r225/projectResources.js:197:240) at n.rDa (https://editor.construct.net/r225/projectResources.js:198:81) at n.yia (https://editor.construct.net/r225/projectResources.js:120:140) at n.sc (https://editor.construct.net/r225/projectResources.js:120:360) at d.f.rg.HMa (https://editor.construct.net/r225/components/bars/projectBar/projectBar.js:65:333) at d.f.rg.Nfa (https://editor.construct.net/r225/main.js:788:456) at h.Nfa (https://editor.construct.net/r225/main.js:947:403) at h.e$ (https://editor.construct.net/r225/main.js:947:382) at window.IH.ba.yJa (https://editor.construct.net/r225/components/bars/projectBar/projectBar.js:65:324)
Stack: Error: animation frame has no content at n.qI (https://editor.construct.net/r225/projectResources.js:192:233) at n.j2 (https://editor.construct.net/r225/projectResources.js:197:240) at n.rDa (https://editor.construct.net/r225/projectResources.js:198:81) at n.yia (https://editor.construct.net/r225/projectResources.js:120:140) at n.sc (https://editor.construct.net/r225/projectResources.js:120:360) at d.f.rg.HMa (https://editor.construct.net/r225/components/bars/projectBar/projectBar.js:65:333) at d.f.rg.Nfa (https://editor.construct.net/r225/main.js:788:456) at h.Nfa (https://editor.construct.net/r225/main.js:947:403) at h.e$ (https://editor.construct.net/r225/main.js:947:382) at window.IH.ba.yJa (https://editor.construct.net/r225/components/bars/projectBar/projectBar.js:65:324)
Construct 3 version: r225
URL: https://editor.construct.net/
Date: Thu Dec 10 2020 16:04:32 GMT-0700 (Mountain Standard Time)
Uptime: 34.1 s

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Thanks, good catch. Fixed for next beta.
