### ISSUE TITLE
Clicking different conditions/actions in quick succession opens editor dialog.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4412]
## Problem description

If you click on an condition or action and then click on another condition or action, the editor acts like you clicked twice in the same action or condition and opens the editor dialog for the last clicked condition or action.

## Attach a .c3p

Any file should present it.

## Steps to reproduce

1. have 2 different conditions or actions.
2. click on 1 of them.
3. quickly click on another.
4. observe its editor opens.

## Observed result

editor opening.

## Expected result

to not open an editor since I did not double click any condition or action.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 228

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce in Ghost Shooter, it never opens the edit dialog if you change selection, no matter how close the clicks are. Please follow the full bug report guidelines to help make sure the issue can be investigated, otherwise it will be closed.

**Comment by dupuqub** [comment]
I cannot reproduce it anymore even though I could safely reproduce it sooner. If I find out how it happened, I'll open a new issue.
