### ISSUE TITLE
Sprite frames on layout get resized when they should'nt

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4414]
## Problem description
Case when you happen to use sprite and use multiple instances of it on layout, each displaying different frame. When you swap some frames around in animation editor, all frames on layout get resized. While individual frame sizes have not changed! Sprite frame could have 3 different sizes, depending on some case and user has no way to know which one will be displayed.
This should not happen!!! User might see this later and have to resize everything manually. 

## Attach a .c3p
[AutoResize_Buggg.zip](https://github.com/Scirra/Construct-3-bugs/files/5683272/AutoResize_Buggg.zip)

## Steps to reproduce

1.Open example. See 5 sprite instances on layout. Click on second one from left.
2.Mark or remember it's size "(7 x 10.2)"
3.Double click on first instance and open animation editor
4.Click and dublicate first frame, drag dublicated frame as last frame. Close editor
5.Click again second instance from left. See its size is now (7 x 12).
6.Click Crtl+z, then back Crtl+y. See size is now  (7 x 14)

## Observed result
Sprite instance size is changed when it should not. Original 10.2, then 12 and 14. Very chaotic

## Expected result
Keep its original size. As if user dublicates frame and does not drag it as last frame, buggy resize does not happen. This is chaotic behavior and should not exist

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r226 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.3 gb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
The project is using an effect which I don't have and can't find anywhere else, **pixelSmooth (sharppixel)**. Can you post a project without the effect?

**Comment by SnipG** [comment]
oh Sorry, i uploaded wrong version. I should not rename them so similarly.
[AutoResize_Buggg.zip](https://github.com/Scirra/Construct-3-bugs/files/5683271/AutoResize_Buggg.zip)

**Comment by DiegoScirra** [comment]
Thanks, will take a better look on Monday, but I can already see there is a problem.

**Comment by SnipG** [comment]
This might be irrelevant. But as this is some sort similar case of dublicating frames.
Anyway, but dublicating, dragging around and ctrl+z and ctrl+y. Causes 2 crash in r266:

1. Error: frame not found @ Error: frame not found at h.Cqb
2. Error: frame not in this animation @ Error: frame not in this animation at h.QIa

If i sink in time i could/might get 100% reproduce example. But currently just leave this here.

**Comment by DiegoScirra** [comment]
The original issue will be fixed in the next beta.

**Comment by DiegoScirra** [comment]
I can't easily reproduce the other issue, so will be closing this one.

**Comment by SnipG** [comment]
Nice, gonna check thous other cases then.

**Comment by SnipG** [comment]
I tried this case in r231, it still happens. I don't have time for full repo but: resized last frame big, dragged it as first, then closed editor, then dragged big frame back to last. Middle frames loose custom size, defined by user.
