### ISSUE TITLE
Sprite frame change refreshes shader effect of first instance differently then rest of instances

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4416]
## Problem description
Case you got 4 instances of sprite with effect. Using frames as: 1, 2, 2, 1. And user dublicates last frame, then first instance changes it shader effect look, which will change back to correct if you click on layout.

What seems strange is that instance 4 with frame 1 does not have this effect. Only first instance does this refresh!
So it might need a check, is it intended outcome or not!

## Attach a .c3p
[1st_instance_Refresh_Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5684567/1st_instance_Refresh_Bug.zip)

## Steps to reproduce

1.Open example, double click on most right instance. 
2.In Animation editor dublicate last frame. Close editor
3.Look at first instance. Click on first instance.
4.Press Ctrl+z and Ctrl+y. Repeat

## Observed result
First instance refreshes and updates shader effects or some of its properties differently. Even when spritesheet does not change its size. While other instances with different or same frame does not change effect.

## Expected result
If not intended behavior, then no refresh wrongly and wait for user click to refresh back.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r228 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 451 mb
Storage usage (approx): 83 mb (18.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It draws correctly as soon as the layout view redraws (e.g. if you click or scroll).

Assigning to @DiegoScirra, I think all that needs to be done is ensure the layout view refreshes after duplicating an animation frame, and after undo/redo of changing the animation frame.
