### ISSUE TITLE
AJAX doesn't work with long-running Tween

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#4417]
## Problem description

This code doesn't work - array are not loaded, unless I remove the the first event or change Tween duration to 1 second or less.

![image](https://user-images.githubusercontent.com/36763350/102032889-194ef000-3e0e-11eb-99e1-a97573e95d45.png)

## Attach a .c3p

https://www.dropbox.com/s/i6e7fk2cdsax860/LoadArraysBug.c3p?dl=0

## Steps to reproduce

Run in Debug Mode and check the arrays.

## Observed result

One or both arrays are not loaded.

## Expected result

Arrays should contain data.

## More details

**Affected browsers/platforms:** All

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.49.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.49.2 (like Chrome/86.0.4240.111)
C3 release: r225 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 66 gb
Storage usage (approx): 306 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
Minimal repro: [issue4417.zip](https://github.com/Scirra/Construct-3-bugs/files/5688906/issue4417.zip)

Looks like "Wait for previous actions to complete" is also waiting for the tween to complete.

**Comment by AshleyScirra** [comment]
OK, fixed for next beta.
