### ISSUE TITLE
Nested animation subfolders can't become top-level folders again

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4418]
## Problem description

In the Animation Editor, once a folder is nested under another folder, it can't be dragged out to the top level again. 

## Attach a .c3p

https://drive.google.com/file/d/1vHFv6LoaJqtUfJJvaxq1Fi4Le1hD4Iju/view?usp=sharing

## Steps to reproduce

1. Load the attached project (or any project with animations in folders)
2. Open 'Sprite' object in the Animation editor
3. Expand all animation folders.
4. Try to drag "New Folder 2" to the same hierarchy level as "New Folder 1".

## Observed result

"New Folder 2" can't be set to any other level but a subfolder of "New Folder 1". 

## Expected result

"New Folder 2" should be able to be arranged at any hierarchy level (i.e. above "New Folder 1").

## More details

**Affected browsers/platforms:** Chrome 87, Safari 14

**First affected release:** r225

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed on the first release of the next stable cycle.
