### ISSUE TITLE
Signalling server is down, maybe?

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#4419]
![image](https://user-images.githubusercontent.com/32940085/102281197-80e36900-3efc-11eb-866c-4963895a447d.png)

**Comment by AshleyScirra** [comment]
It's working fine for me. I can only assume it's a problem on your end.

**Comment by eleanorawesome** [comment]
does it block connections from an IP temporarily after too many requests ?

**Comment by AshleyScirra** [comment]
Yes. All online services have mechanisms to prevent abuse/DDoS/etc, and we do too.
