### ISSUE TITLE
Stylus problems.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#442]
## Problem description

Using C3 exclusively with Touch/Stylus i noticed some quirks with using stylus. 

1. Most of the time a stylus doubleclick does not behave like mouse double click, or touch double-tap. 90% of the time it does not register the double-tap at all.

2. Using touch, tapping an input field opens the Windows 10 touch keyboard as expected. This does not happen when using stylus to tap an input field.

I do believe this is Chrome not completely supporting stylus input, but wondering if there's any workaround for this? Maybe some js code for web-apps to support stylus input? If no maybe you can file a bug with chrome for this issue? It's a bit frustrating when working with stylus/touch in C3.

## Attach a .c3p

N/A

## Steps to reproduce

1. Open any project.
2. Double tap with a stylus (wacom, surface pro, etc) on any condition or action, or other place where double clicking usually works to edit.
3. Tap with a stylus on any expression input field, and touch keyboard does not open, as it does with touch.

## Observed result

Most of the time (about 90%)it does not work, as it does not recognize the double click.
Tapping with stylus does not open Windows 10 touch keyboard, like touch does.

## Expected result

Expected to work like mouse and touch.

## Affected browsers

* Chrome: yes
* Vivaldi: yes (same behaviour as chorme)
* Opera: yes (opera does not recognize stylus at all)
* Edge: no

## System details

On Surface Pro 4, using stylus.
On PC using Wacom drawing pad.
On Mac using Wacom drawing pad.

**Comment by AshleyScirra** [comment]
We don't have a stylus device right now so this is going to be difficult to do anything about until then.

Are the stylus problems unique to Construct 3? As in, if you visit another web page, do you have similar stylus issues? That would suggest a Chrome bug, otherwise if it's unique to C3 I guess we might have to order something in...

**Comment by tunepunk** [comment]
I am not really sure. In google docs using Chrome for example. Double Tapping works as expected, but not in OneNote from microsoft (using chrome), so I'm not sure if it's because docs extension, or that the google docs, web-app is built with this kind of support. 

Google docs using Edge also works well, but that might be that Edge supports stylus input by default. 

I would suggest Scirra investing in some kind of "Surface Pro" or similar device, as besides from the small Touch/Stylus Quirks, C3 is very pleasant to use on these type of devices even without keyboard & Mouse, and could possibly good selling point attract more tablet developers.

This kind of device is very pleasant as you can test your touch capable games directly on these type of devices as well, without having to remote preview or export.

**Comment by tunepunk** [comment]
On a side note, i think this would be Solved as soon as Edge would be a supported browser to use for C3, as it has this functionality by default.

Currently only (CSS Grid layout, CSS containment, and Dialog Element) is the only thing stopping me from using C3 in Edge instead.

**Comment by tunepunk** [comment]
Maybe related to Touch issue that was fixed, but it C3 using pointer events to destinguish between different input method? Stylus should be supported in Chrome.

https://developers.google.com/web/updates/2016/10/pointer-events

**Comment by AshleyScirra** [comment]
It would still be useful if you could clarify whether this is a Chrome issue or only C3 has issues with the stylus. Your previous comments do not seem to be completely clear on the subject. If it's Chrome, we can look in to filing a bug with Google; if it's C3, we can check if there's code we can change.

FWIW C3 still uses touch events - we tried to port to touch events half way through development, but the APIs were too different for it to be easy, and there didn't seem to be any obvious benefit to it. Ideally we can get stylus working with touch events, but if it's something that only pointer events supports, we could look in to revisiting that.

**Comment by tunepunk** [comment]
I wasn't able to find any definite answer, but from my tests. In some web-apps, double click/tap is supported, and chrome does fire the touch keyboard in some cases, so it seems like there is some support in chrome, but It leans more towards that web-apps has to make use of some code (maybe pointer events) to distinguish between them, where as this seem to work by default in edge for example. 

I'm sorry I can't give any better clarification than that. It's hard to find a good web-apps to test on. The only one i found so far that seemed to work flawlessly was google docs in chrome. But maybe this will help.

In chrome. Regular webpages with text, usually you can double-click to select a whole word. Tripple click to select a whole paragraph. This works fairly well with mouse, and touch, by default in chrome. 
This does usually not work when using a stylus, ... It's like it's not recognizing the double/tripple clicks from a stylus unless (like google docs) has some special code to handle it?

**Comment by justifun** [comment]
check your chrome://flags and try setting your "Enable Touch Events" to enabled instead of automatic then reload the browser

**Comment by tunepunk** [comment]
After some further investigation this seems to be a chrome issue. I've reported a bug with with the chrome developers. There were some similar issues in that were being worked on, so hopefully this will be resolved soon.

**Comment by AshleyScirra** [comment]
@tunepunk - can you link to the Chrome bug here so I can follow it too?

**Comment by tunepunk** [comment]
Here is the chrome issue i posted. Regarding double clicking with a stylus.
https://bugs.chromium.org/p/chromium/issues/detail?id=739173

Here is another posted by someone else about virtual keyboard not firing on clicking input boxes.
https://bugs.chromium.org/p/chromium/issues/detail?id=497381

Another one regarding pointer events, thats probably related or cause.
https://bugs.chromium.org/p/chromium/issues/detail?id=714784

**Comment by AshleyScirra** [comment]
Thanks, I'll keep an eye on them. Bug 714784 would definitely cause problems in C3, we rely on pointer IDs working properly in a number of places. So I suspect this is more Chrome-related.

**Comment by tunepunk** [comment]
I think you can close this issue now since chrome fixed it in latest release. Other browsers are still dodgy though but It's not a C3 problem.
