### ISSUE TITLE
Can't toggle layer "lock" through lock icon in the layers bar.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4420]
## Problem description

Can't toggle layer "lock" through lock icon in the layers bar.

## Attach a .c3p

any file.

## Steps to reproduce

1. try to toggle a layer's "lock" using the lock icon on the side of the layer's name,

## Observed result

can't toggle.

## Expected result

toggle.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 229

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.

(@DiegoScirra - just a heads up, this was a small update for Pointer Events.)

**Comment by AshleyScirra** [comment]
Had a duplicate report already so leaving open marked fixed until next beta.
