### ISSUE TITLE
Can't adjust the sizes of events conditions and actions.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4423]
## Problem description

If you try to adjust the size of events and actions, you won't be able to.

## Attach a .c3p

any file.

## Steps to reproduce

1. Add a couple of events and/or actions.
2. Try to resize the width of the blocks.
3. You won't be able to.

## Observed result

not adjusting sizes.

## Expected result

adjusting sizes.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 229

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.

(Heads up @DiegoScirra - another breakage caused by Pointer Events)
