### ISSUE TITLE
Free edition have event remaining but can't modify event

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4429]
## Problem description

Free edition **have 1 event remaining** but can't modify event
![01](https://user-images.githubusercontent.com/45864744/102846835-052d7300-444c-11eb-98d8-7dfeb5133921.jpg)

## Attach a .c3p

start page project
1.  [card-memory-match](https://editor.construct.net/#open=template-card-memory-match)(49 event) 
2.  [Eat 'em all](https://editor.construct.net/#open=template-eat-em-all) (48 event) 

## Steps to reproduce

1. login a Free edition account.
This account used to be a subscriber, but there was no renewal.
![02](https://user-images.githubusercontent.com/45864744/102847051-900e6d80-444c-11eb-8cb8-d0a9cd3ce9cb.jpg)

  
<br>  
  
2. Open a start page project: [card-memory-match](https://editor.construct.net/#open=template-card-memory-match)(49 event) 
  
3. when i drag the conditions or event. was turned down
![04](https://user-images.githubusercontent.com/45864744/102847685-e92ad100-444d-11eb-9e6b-24c7cfd22990.jpg)
![01](https://user-images.githubusercontent.com/45864744/102846835-052d7300-444c-11eb-98d8-7dfeb5133921.jpg)
  
<br>  
  
  
<br>  
  
4. BUT I Open the [Eat 'em all](https://editor.construct.net/#open=template-eat-em-all) (48 event) 

![05](https://user-images.githubusercontent.com/45864744/102848127-fe542f80-444e-11eb-9252-8300cbcec422.jpg)

It don't send such a question
![06](https://user-images.githubusercontent.com/45864744/102848088-e5e41500-444e-11eb-9f26-69ceed15162e.jpg)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It exceeds the free edition layers limit, not the event count.
