### ISSUE TITLE
Investigate build service APK size overhead

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#443]
If you export an empty project to Cordova and build both with the Scirra build service and PhoneGap Build, the APKs have quite different sizes: PGB is ~320kb, and Scirra build service ~2mb. The main difference seems to be the inclusion of a set of default splash images in the res folder, and some of the files are reasonably large (PNGs with gradients).

As previous Crosswalk support showed users are quite sensitive to APK size overhead, and it is also seen as a sort of proxy for how efficient the engine is if it generates lightweight APKs. Obviously removing splash screens doesn't make the engine faster, but it improves the perception of the efficiency of the service.

Ideally we can remove the splash screens by default - are they even shown? Besides there's not currently a way for users to customise them via our build service so it seems better to omit them until they can be customised. If for some reason it's hard to remove them, something as simple as a solid-fill background with the C3 logo would reduce even high-res PNGs to a few kb.

**Comment by jaydonteh** [comment]
I'm curious, are there even any splash screen showing? I don't see them on a debug build. But if there is one, would like it to be just black screen.

**Comment by shortercode** [comment]
@jaydonteh Good question... I don't seem to see any on the projects I've built as APK's, but it might behave a bit differently on iOS so can't really say for sure.

**Comment by shortercode** [comment]
Okay so I've swapped out the default splashscreen set with a single user generated splashscreen. Seems to have made a pretty good reduction. Looking at about 800KB for an empty project now, of which about 550KB is actually native executable code.  We might be able to knock a bit more off if we enabled proguard minification but that brings in it's own set of problems.

**Comment by AshleyScirra** [comment]
An unsigned release APK is just 640kb now. I think that'll do!
