### ISSUE TITLE
Mistakes in Race Track template

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#4432]
## Problem description

The template stops working if you set the number of laps greater than the number of checkpoints on the layout.

See the screenshot below. Checkpoint functions should use "numberOfCheckpoints" variable or Checkpoint.count, not "numLaps" variable.

![image](https://user-images.githubusercontent.com/36763350/103058970-d0f6b580-45f7-11eb-8412-c82955a4dab8.png)

Also, in this event I would add a condition Checkpoint.ID>=Car.CurCP, otherwise you can drive on the track in the opposite direction and the lap will still be counted as completed.

![image](https://user-images.githubusercontent.com/36763350/103076464-e4b71180-4621-11eb-9789-2c22a5bab02c.png)

**Comment by AshleyScirra** [comment]
Updated template for next release.
