### ISSUE TITLE
Beta 229 Z Hierarchy

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4437]
## Problem description
In editor set Scene Graph Z order hierarchy is not correct

## Attach a .c3p
[https://www.dropbox.com/s/4eaqm13871wfk21/zhierarchy.c3p?dl=1](url)

## Steps to reproduce

1.Note the z order of the existing objects set up with the Scene Graph Hierarchy 
2.Run the project
3.Note the z order of the runtime created Scene Graph Hierarchy 

## Observed result

The z order for the runtime created objects is different than the order set in the editor, and in the z order bar
## Expected result

The preset order should be used
## More details

**Affected browsers/platforms:** 

Chrome W10
**First affected release:** 
Beta 229
## System details
https://imgur.com/flHZ7jJ

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta

**Comment by pigmalien** [comment]
Cool.
Thanks a bunch!
