### ISSUE TITLE
CREATING A SCROLLABLE LIST by bartalluyn published on 7 Oct, 2020 at 16:05

### ISSUE THREAD

**Issue by weepingwilly** [Scirra/Construct-3-bugs#4438]
## Error report information
Type: unhandled exception
File: safari-extension://DAF23EF6-8FFA-49FC-85EA-703250789F7F/9be1e4f5/Grammarly.js, line 2, col 667436
Message: [object Object]
Stack: undefined
Construct 3 version: r225
URL: https://editor.construct.net/
Date: Sun Dec 27 2020 22:44:52 GMT-0500 (EST)
Uptime: 18.2 s

Platform information
Browser: Safari
Browser version: 14.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
C3 release: r225 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_blend_minmax, EXT_sRGB, EXT_frag_depth, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_standard_derivatives, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context, WEBGL_compressed_texture_s3tc, WEBGL_depth_texture, WEBGL_draw_buffers, ANGLE_instanced_arrays, WEBGL_debug_shaders, WEBGL_debug_renderer_info, EXT_color_buffer_half_float, WEBGL_color_buffer_float

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help unless you follow the bug report guidelines.

This also looks like a problem with the Grammarly browser extension, so try disabling that.
