### ISSUE TITLE
Character passing through angled jump-thru objects

### ISSUE THREAD

**Issue by Lobo93** [Scirra/Construct-3-bugs#4439]
## Problem description

1: When a character goes up from a jump-thru slope to another, if the the second slope was crated AFTER the first one, the character passes through it.

2: When a character goes from a straight jump-thru platform to an angled one, if its speed is slow enough, it goes through the angled platform.

## Attach a .c3p

[Jump thru bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5751213/Jump.thru.bug.zip)

## Steps to reproduce bug 1

1. Walk to the right and pass over the slopes

## Observed result

The character passes through the 4th slope

## Expected result

The character should go up every slope

## Steps to reproduce bug 2

1. Use the slider to reduce the character speed (in my tests the bug ocurred from 1 to 3 speed, but it may vary)
2. Walk to the right until you reach a slope

## Observed result

If the speed is slow enough, the character passes through the slope

## Expected result

The character should walk up the slope

## More details
As I mentioned, the first bug seems to occur based on the order the objects were placed in the layout (their UID,  maybe). I added a text object with the order every slope was placed to help you guys understanding the problem.

**Affected browsers/platforms:** Chrome v87.0.4280.88 64 bits 

**First affected release:** r229 beta

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r229 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 267 gb
Storage usage (approx): 1.3 gb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Slopes using jump-thrus are not supported. This is noted in the [jump-thru manual entry](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/jump-thru):

> Note the Jump-thru behavior **does not support slopes.** Any slopes in your game should use the Solid behavior instead.

Given the complexity of the platform behavior and the rules allowing objects to fall through jump-thrus, it's just too complicated.
