### ISSUE TITLE
Construct 3 - Empty Error Alert When Cloud Upload Fails

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#444]
## Problem description
I've noticed a issue that only occurs when an active cloud uploading process fails.
Just a heads up, it will be incredibly difficult to reproduce this bug on a high-speed Internet connection.
(I would recommend using a project with a bigger file size in that case.)

![empty box](https://cloud.githubusercontent.com/assets/15656049/26787810/90e674ee-4a0b-11e7-8055-0a1fa3894fd8.JPG)

## Attach a .c3p

[Download](https://cdn.discordapp.com/attachments/225550155531812865/321292967740571649/Alert_Error.c3p) here.

## Steps to reproduce

1. Open the project
2. Save it to a cloud service (in my case Google Drive)
3. Manually disable your Internet connection
4. Notice error messages in the browser console*
5. Connect to the Internet again (it should display an empty alert box now)

## Observed result

Construct 3 displays an empty alert box when an active cloud upload fails.

## Expected result

Construct 3 should display an error message (including a brief description of what went wrong) and perhaps even offer a "retry" button.

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*Screenshot of the web console
![error](https://cloud.githubusercontent.com/assets/15656049/26788119/88358e92-4a0c-11e7-9b66-364b18de4cc5.PNG)

**Comment by shortercode** [comment]
Looks like there's just no error message to display so it appears as blank, I'll put something in so it's a bit more friendly. Adding a retry button might be a little harder, but I'll have a think on it.

**Comment by shortercode** [comment]
I think I found the cause of this. But I've just refactored a load of the code including ALL the error handlers/creators for this block of code. Hopefully there should be something in the error dialog now!
