### ISSUE TITLE
Editor crashes when using ESC to close a dialogue menu in a layout editor window open on a new tab

### ISSUE THREAD

**Issue by ReflextionsDev** [Scirra/Construct-3-bugs#4440]
## Problem Description

If the user opens a layout window, then drags it to a different window, then opens any menu, then closes it with ESC, the editor will freeze indefinitely or crash.

## Attach a .c3p

This will repro with an empty project.

## Steps to reproduce

1. Create a new project in C3
2. Drag the layout view to a seperate tab
3. Drag the layout view to a new window
4. Double click anywhere to bring up the object menu (alternatively, edit a text field to bring up a text menu)
5. Exit the menu with the ESC key
6. Observe the editor freezes
7. Exit the layout window
8. Press ESC again
9. Observe the editor crashes

## More details
- r229 
- Chrome

## System details

`Error report information
Type: unhandled exception
File: https://editor.construct.net/r225/main.js, line 623, col 114
Message: Uncaught TypeError: Cannot read property 'removeEventListener' of null
Stack: TypeError: Cannot read property 'removeEventListener' of null at d.f.G.IHd.EN (https://editor.construct.net/r225/main.js:623:114) at d.f.G.IHd.th (https://editor.construct.net/r225/main.js:625:401) at d.f.G.IHd.Dd (https://editor.construct.net/r225/main.js:625:174) at d.f.G.IHd.Wd (https://editor.construct.net/r225/main.js:637:458) at t.Wd (https://editor.construct.net/r225/main.js:585:46) at HTMLDocument. (https://editor.construct.net/r225/main.js:581:333)
Construct 3 version: r225
URL: https://editor.construct.net/
Date: Tue Dec 29 2020 19:14:37 GMT-0600 (Central Standard Time)
Uptime: 1907.2 s

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2`

**Comment by AshleyScirra** [comment]
I've fixed the crash for the next beta, but making it work as expected (so Esc still closes the dialog in a popup window) looks like it will require further work - that part is an aspect of issue #4339 though so will follow up remaining work there.
