### ISSUE TITLE
When attempting to use a bar associated with a layout open on a second screen, the values from the layout open on the primary screen are loaded instead

### ISSUE THREAD

**Issue by ReflextionsDev** [Scirra/Construct-3-bugs#4441]
## Problem description

If the player opens a layout on a second screen, but also has one open on the first screen, any data bar will revert to data from the first screen layout, until the player repeats the action.

As an example, if I am editing the second layout, then attempt to lock the second layer, the second layer of the first layout will lock and the bar will change to show layers from the first layout.

This occurs with property bars, z order, layer, etc. It seems the problem occurs because objects in the first layout screen are not deselected when the user switches to the second screen.

## Attach a .c3p

https://github.com/ReflextionsDev/c3-bugs/blob/main/DualLayout.c3p

This can be repro'd in a new project, but this has 2 objects and layouts with identical layers to test with.

## Steps to reproduce

1. In a new C3 project, create a second layout
2. Move the second layout to a second screen, while keeping the first layout on the first screen
3. Select the second layout to bring up the associated layers
4. Attempt to lock a layer on the second layout
5. Observe a layer on the first layout is locked

Alternative:
1. In a new C3 project, create a second layout
2. Move the second layout to a second screen, while keeping the first layout on the first screen
3. Create an object in the second layout
4. Click anywhere on the first layout
5. Click on the object in the second layout
6. Attempt to edit the object name
7. Observe the properties bar is replaced with data from the first layout (usually a layer)

## Observed result

The data in the bar should remain the consistent when clicked

## Expected result

The data in the bar changes when clicked

## More details
- Chrome
- r225

**Comment by ReflextionsDev** [comment]
Adding a video because the description is kind of confusing:

https://user-images.githubusercontent.com/3964845/103325534-2f69cc80-4a1a-11eb-91d2-8ef711bef5f6.mp4

**Comment by AshleyScirra** [comment]
Thanks for the report. I think I tracked it down, it seems to be a slightly complicated issue with transferring focus between windows, but it should be fixed for the next release.
