### ISSUE TITLE
Animation Editor - Origin and Hotspots change after cropping an image

### ISSUE THREAD

**Issue by ReflextionsDev** [Scirra/Construct-3-bugs#4442]
## Problem description

After cropping an image in the animation editor, the origin and hotspots will move. 

## Attach a .c3p

https://github.com/ReflextionsDev/c3-bugs/blob/main/CropBug.c3p

## Steps to reproduce

1. Open an image in the animation editor
2. Select an area within the area
3. Crop the image
4. Observe the origin has moved, along with any hotspots

## Observed result

Origin and hotspots are relocated.

## Expected result

Origin and hotspots should not move when the user crops and image.

## More details
- Chrome
- r225

**Comment by ReflextionsDev** [comment]
![HotspotBug](https://user-images.githubusercontent.com/3964845/103326186-23cbd500-4a1d-11eb-9f4c-103ef9bbcc90.gif)

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
