### ISSUE TITLE
Cursor cannot be hidden or removed

### ISSUE THREAD

**Issue by BluePinStudio** [Scirra/Construct-3-bugs#4445]
## Problem description

 If I attempt to manipulate the window or alt-tab the windows cursor stays visible despite Hide Cursor actions 

## Attach a .c3p
[CursorNotHidden.zip](https://github.com/Scirra/Construct-3-bugs/files/5761080/CursorNotHidden.zip)

Here is the entire event sheet
![entirecode](https://user-images.githubusercontent.com/76889959/103469942-8aacff00-4d39-11eb-9992-ccb5e34febdc.JPG)

## Steps to reproduce

1. Export project as nw.js v0.47.0 win64 build with argument --in-process-GPU (all of the things necessary for a working Steam build)
2. Launch the nw.exe and drag your mouse over the edge of the window, you'll find that the windows cursor appears at the edge and never disappears

## Observed result

Windows Cursor does not get hidden
![CursorNotHidden](https://user-images.githubusercontent.com/76889959/103469903-f2167f00-4d38-11eb-9587-342491218258.gif)

## Expected result

Windows Cursor gets hidden

## More details

**Affected browsers/platforms:**  nw.js export 

**First affected release:** 

## System details

Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It works fine for me with NW.js 0.50 and C3 r229. As per the bug report guidelines, please only report issues using the latest versions to avoid reporting problems that have already been fixed.

**Comment by BluePinStudio** [comment]
@AshleyScirra The reason I use nw.47 is because Scirra says thats the only version that works for steam. I cannot use a newer version
