### ISSUE TITLE
Audio - Tremolo Mix - Not Working

### ISSUE THREAD

**Issue by vamos123** [Scirra/Construct-3-bugs#4446]
## Problem description
The mix option for the tremolo audio effect is not working and changing the values anywhere between 0 and 100 does nothing. In the attached c3p project you can change the values on the fly. Changing the frequency does work, just not the mix. Also in the project is the ring effect disabled. If you disable the tremolo and add the ring effect you will see the mix working, which uses the same parameters.

## Attach a [.c3p]
[tremoloMixError.zip](https://github.com/Scirra/Construct-3-bugs/files/5762242/tremoloMixError.zip)

## Steps to reproduce
1. Add tremolo effect to any audio file.
2. Change the mix value to zero. 
3. Run layout.

## Observed result
Changing the mix to any value between 0-100 does not have an effect. 

## Expected result
At zero the tremolo effect should not be heard, only the original audio file.

## More details
Tested in both Construct 2 and 3 with same results.

**Affected browsers/platforms:** 

**First affected release:** 
First noticed in: r225
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
