### ISSUE TITLE
Newline not working on Text Input

### ISSUE THREAD

**Issue by coco9515** [Scirra/Construct-3-bugs#4447]
## Problem description

newline don't work, at least on the Text Input plugin.

## Attach a .c3p

[Newline Test.zip](https://github.com/Scirra/Construct-3-bugs/files/5764765/Newline.Test.zip)

## Steps to reproduce

After fiddling with the bug on a project, I decided to try on a fresh project to be sure, it's me or the project fault - so that's what I did : 
1. Start a new project with a Text Input
2. Place at least 2 events to print stuff to the Text Input (so we can use the newline function) - I did a "on start of layout" and "trigger once after 1 sec".
3. Launch the preview.
4. Realise that newline don't work even when added in different ways (append text / edit text / using functions / etc...)

## Observed result

No newline; all text are print after each others

## Expected result

Have a newline and readable sentences

## More details
I use Google Chrome, latest stable version.
I tried the preview with the r225 and latest beta r229.
Using the debug preview did not help me find anything.
Export in NW.js Windows 64 did not help.

## System details

No crashes.

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 117 gb
Storage usage (approx): 1 gb (0.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 3090 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The "Text" input type is a single-line field.

Use the "textarea" type if you need a user input field that supports multiple lines. Note if you're trying to display a non-interactive log, the Text object may be more appropriate, and that also supports multiple lines.
