### ISSUE TITLE
Can't drag&drop instance variables

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#4451]
## Problem description
Can't drag&drop instance variables

![test](https://user-images.githubusercontent.com/54614906/103623829-b43c7500-4f49-11eb-875a-4ba23ad36e0a.gif)

## Attach a .c3p

[test.zip](https://github.com/Scirra/Construct-3-bugs/files/5768951/test.zip)

## Steps to reproduce

1. Open instance variables dialog (Sprite object)
2. Click one time to any variable
3. Now try to move it up or down

**Affected browsers/platforms:** Chrome

**First affected release:** r228/r229

**Comment by AshleyScirra** [comment]
It often works fine for me, but it seems sometimes it randomly doesn't work the first once or twice. Probably related to #4413 which was a similar sounding issue that I thought was fixed, but it seems there is still some sporadic issue left.

**Comment by SnipG** [comment]
I took a look at the gif and it seems if you already selected variable,  you can't drag it. But can drag variables which you haven't selected before.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
