### ISSUE TITLE
Advanced Minify doesn't work with Greenworks

### ISSUE THREAD

**Issue by BluePinStudio** [Scirra/Construct-3-bugs#4454]
## Advanced Minify doesn't work with Greenworks Plugin

When you use Advanced minify, you get the Failed To Compile Error

## Attach a .c3p

[GreenworksTest.zip](https://github.com/Scirra/Construct-3-bugs/files/5770724/GreenworksTest.zip)

## Steps to reproduce

1. Export with Advanced Minify

## Observed result

Failed to Export

## Expected result

Export Success

## More details

**Affected browsers/platforms:**   All

**First affected release:**  All

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report, I just published a 0.47.0-r2 update which fixes advanced minification: https://www.construct.net/en/make-games/addons/84/greenworks/0-47-0-r2-666
