### ISSUE TITLE
Hierarchy crash when undo

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#4456]
## Problem description

Hierarchy crash when press undo

## Attach a .c3p

https://drive.google.com/file/d/1JdOR-pR6sGYfGlS-gatjepQVEKu3oVpZ/view?usp=sharing

## Steps to reproduce

1. Select "1" and "3" and add to hierarchy ("1" as child "3" as parent) 
2. Select "2" and "3" and add to hierarchy ("2" as child "3" as parent) 
3. Select "1" and "2" and add to hierarchy
4. Select "2" and "1" and add to hierarchy
5. press ctrl+z repeately
6. CRASH

https://user-images.githubusercontent.com/47735877/103750956-d4326e00-5007-11eb-9631-dd00d975593b.mp4

## Observed result

crash

## Expected result

Not crash

**First affected release:** r230

## System details

<details><summary>Error report information</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'RRa' of null @ TypeError: Cannot read property 'RRa' of null at https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:72:40 at Object.$ja (https://editor.construct.net/r230/main.js:906:76) at Object.Ws (https://editor.construct.net/r230/main.js:873:410) at Object.KA (https://editor.construct.net/r230/main.js:874:493) at Object.e3c (https://editor.construct.net/r230/main.js:910:96) at Object.LR (https://editor.construct.net/r230/main.js:910:27) at n.kva (https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:17:391) at n.Ni (https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:16:247) at Array. (https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:4:120) at Object.Ead (https://editor.construct.net/r230/main.js:429:387)
Stack: TypeError: Cannot read property 'RRa' of null at https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:72:40 at Object.$ja (https://editor.construct.net/r230/main.js:906:76) at Object.Ws (https://editor.construct.net/r230/main.js:873:410) at Object.KA (https://editor.construct.net/r230/main.js:874:493) at Object.e3c (https://editor.construct.net/r230/main.js:910:96) at Object.LR (https://editor.construct.net/r230/main.js:910:27) at n.kva (https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:17:391) at n.Ni (https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:16:247) at Array. (https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:4:120) at Object.Ead (https://editor.construct.net/r230/main.js:429:387)
Construct 3 version: r230
URL: https://editor.construct.net/r230/
Date: Wed Jan 06 2021 09:54:22 GMT+0100 (közép-európai téli idő)
Uptime: 692.1 s

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r230 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
