### ISSUE TITLE
Crash when using patch selection tool on a tilemap in a layout

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#4458]
## Problem description

Selecting the upper-leftmost tile of a tilemap in the layout when using the patch selection tool crashes Construct.

## Attach a .c3p

The Tile-based Game template or any other project with a tilemap in the layout can be used to reproduce this crash.

## Steps to reproduce

1. Open the Tile-based Game example project.
2. Select the tilemap in the layout.
3. Click the patch selection tool in the Tilemap pane or hit the 6 key.
4. Click the tile in the upper-left corner of the tilemap in the layout.

## Observed result

Construct crashes.

## More details

**Affected browsers/platforms:** Tested in Chrome.

**First affected release:** 

Working in r229, broken in r230

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r230/main.js, line 215, col 392
Message: Uncaught TypeError: expected finite number
Stack: TypeError: expected finite number at Function.d.m (https://editor.construct.net/r230/main.js:215:398) at window.jl.pm (https://editor.construct.net/r230/components/editors/layoutView/layoutView.js:53:125) at window.pj.Qe.Csb (https://editor.construct.net/r230/components/bars/tilemapBar/tilemapBar.js:110:310) at window.pj.Qe.Fd (https://editor.construct.net/r230/components/bars/tilemapBar/tilemapBar.js:109:490) at window.pj.Qe.$md (https://editor.construct.net/r230/components/bars/tilemapBar/tilemapBar.js:85:186) at HTMLDocument.Tf (https://editor.construct.net/r230/components/bars/tilemapBar/tilemapBar.js:80:309)
Construct 3 version: r230
URL: https://editor.construct.net/r230/
Date: Fri Jan 08 2021 22:07:19 GMT-0800 (Pacific Standard Time)
Uptime: 16.6 s

Platform information
Browser: Chrome
Browser version: 87.0.4280.141
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
C3 release: r230 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
