### ISSUE TITLE
Cannot cloud save "is already saving"

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#446]
## Problem description
After working for a while this morning I went to save and received the response that the project is saving.  I was able to download a copy and it seems like the cloud save is occurring at some point since I can reload and not lose all my progress.  Doesn't seem to be a major issue but its confusing and doesn't give me confidence to continue working and cloud saving like I prefer to do.

[Bitmen.zip](https://github.com/Scirra/Construct-3-bugs/files/1052401/Bitmen.zip)

## Affected browsers

* Chrome: yes

## System details

No crash report.
Attempting to save to Dropbox.

**Comment by 8bitThirsty** [comment]
Cannot seem to reproduce this issue after opening the ticket and closing the application and reopening it.  I will pay attention and add more details to this issue if I come across it again.

**Comment by shortercode** [comment]
Do you have "periodically back up projects" enabled? It would lock the project from saving to cloud or local browser save until it's completed at the moment. This wouldn't apply to "download a copy".

**Comment by 8bitThirsty** [comment]
Nope, I do not have that feature enabled which is why it was concerning to me.   It also had a message saying "Bitmen.c3p processing" in the bottom left corner of the screen. 

Retracing my steps:
1. I attempted to save and got the message 
2. waited for a few minutes and tried again getting the same results
3. downloaded a copy and opened this ticket with that downloaded copy
4. went back and tried again to cloud save getting the same results for the third time
5. closed Chrome browser and reloaded files from the Cloud
6. Attempted to recreate the issue unsuccessfully

**Comment by shortercode** [comment]
How were you saving? Via the file dialog / ctrl + s / save button on the toolbar? Was this an initial save or an update of an existing save? Generally how long does it take to save this project over your network? Did it say "processing" for all the time that it was broken>

**Comment by 8bitThirsty** [comment]
I never use ctrl+s and I typically use the save icon next to menu but occasionally use save as-> cloud save but I cannot say which I tried first when noticing this issue.  I believe I clicked the save icon and got the save in progress response and then attempted the save as and got the same results. 

Generally saving to the cloud takes around 5 seconds for me and once the processing error showed up it didn't go away till I closed the application and reopened it.

**Comment by shortercode** [comment]
Well "processing" isn't an error, it just means the app is still creating the save archive. If that message never went away it probably means it failed to save for some reason and locked up there. 

I'm not sure we're going to get a replication for this. Thankfully I know which path it's using so I'm going to refactor the code in that area and see if I can find any weak points that could cause this. If I can't find any obvious places then we'll just have to close this issue and hope next time it pops up there's a clear replication.

Have you experienced this bug since?

**Comment by 8bitThirsty** [comment]
I have not experienced the bug again but I haven't had too much opportunity to use the application since opening this ticket.  I will keep an eye on it and if I come across it again I will try to get more info that may be useful and update it here or open a new ticket if this is closed by then.

**Comment by shortercode** [comment]
Thanks @8bitThirsty your welcome to reopen this bug if it is closed, it's good to have to continuity on issues. If you do experience it any information that appears in the console could also be useful.

**Comment by shortercode** [comment]
Refactor is complete, and some of the error checking around that function has been improved. Not sure if it'll help but I think there's a chance it's been fixed!
