### ISSUE TITLE
ContactXAt and ContactYAt doesn't work consistently

### ISSUE THREAD

**Issue by russellrain** [Scirra/Construct-3-bugs#4461]
## Problem description

ContactXAt and ContactYAt works sometimes, but sometimes not.
See https://www.youtube.com/watch?v=IshllDBAaEo

## Attach a .c3p

https://www.construct.net/out?u=https%3a%2f%2fdrive.google.com%2ffile%2fd%2f18ePjnjVUQMMMlRM_LayDshcRk2I1oO9z%2fview%3fusp%3dsharing

## Steps to reproduce

The attached capx will explain this better, but:

1.  Create two physics objects, one circle collision and one immovable rectangle
2.  Set up event to create an object at the ContactXAt and ContactYAt to demonstrate the position (or just log the x and y coordinates)
3.  Play the capx and watch the objects collide

## Observed result

Observe that sometimes the ContactXAt, ContactYAt return as 0,0 instead of actual collision point

## Expected result

Consistently return correct collision point

## More details

**Affected browsers/platforms:** At least chrome on windows and android

**First affected release:** unknown

## System details

Platform information
Browser: Chrome
Browser version: 87.0.4280.141
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
C3 release: r230 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 3.3 gb (1.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by russellrain** [comment]
Someone had a good response for this on the forums, probably not really a big

"Physics has its own collision detection system, which works differently.

Besides, the ball object has rectangular collision polygon, and in physics properties you set Collision mask to Circle. So "On collision event" may happen before Physics behavior registers it.

Try using this condition instead: ball.Physics.ContactCount>0"

**Comment by SnipG** [comment]
No, it does not work like that, i am not sure what someone said somewhere.

Problem is C3 collision system detects collisions outside collision area, so when you call "on collision" it happened before the physic object touched the other object. 
Fix is to decrease the collision polygon, so object itself also touches other object.

![fixit](https://user-images.githubusercontent.com/28864889/104189488-67620e00-5423-11eb-9122-f5d8bdb6ae1d.jpg)

[Uploading Fix_It_forYou.zip…]()
