### ISSUE TITLE
Crash when user dublicates and resize frames and then sprite handles undo and redo

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4462]
## Problem description
Crash when you undo or redo specific frame handling

It's still chaotic, did reproduce steps like ~10, 3 crash: 2 frame missing, 1 frame not in this animation.
Could be case the sprite has already used similarly before or something.

I noticed some other case, which could be cause, when you make sprite, dublicate frame, exit and continue the reproduce steps(open sprite again, dublicating etc). Then sometimes with undo and redo, default sprite state cannot be selected. i.e 
with undo and redo, you can only get blank state(when you created the sprite) and state you already changed/dublicated the frames, but not the state when you exit sprite when you just dublicated first frame 5 times.
Or maybe it's something else. idk

## Steps to reproduce

1.Open new, create sprite, color sprite, dublicate it 5 times, close animation editor
2.Click on sprite and open it, select last frame, resize it, dublicate it.
3.Select dublicated frame, drag it to first place, resize it. Close editor
4.Click Ctrl+z 1 times, then Ctrl+y 1 times.

## Observed result
Editor will crash, mostly when you try to Ctrl+z. So it might not able to load the previous state.

## Expected result
No crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: frame not found @ Error: frame not found at g.bsb (https://editor.construct.net/r230/projectResources.js:177:355) at n.Gr (https://editor.construct.net/r230/projectResources.js:187:259) at Object.hud (https://editor.construct.net/r230/plugins/allEditorPlugins.js:184:403) at Object.hwb (https://editor.construct.net/r230/plugins/allEditorPlugins.js:184:101) at Object.NAa (https://editor.construct.net/r230/plugins/allEditorPlugins.js:180:266) at Array. (https://editor.construct.net/r230/plugins/allEditorPlugins.js:181:340) at Object.Ead (https://editor.construct.net/r230/main.js:429:387) at Object.dispatchEvent (https://editor.construct.net/r230/main.js:425:135) at Object.oG (https://editor.construct.net/r230/main.js:2131:241) at n.X$ (https://editor.construct.net/r230/projectResources.js:195:414)
Stack: Error: frame not found at g.bsb (https://editor.construct.net/r230/projectResources.js:177:355) at n.Gr (https://editor.construct.net/r230/projectResources.js:187:259) at Object.hud (https://editor.construct.net/r230/plugins/allEditorPlugins.js:184:403) at Object.hwb (https://editor.construct.net/r230/plugins/allEditorPlugins.js:184:101) at Object.NAa (https://editor.construct.net/r230/plugins/allEditorPlugins.js:180:266) at Array. (https://editor.construct.net/r230/plugins/allEditorPlugins.js:181:340) at Object.Ead (https://editor.construct.net/r230/main.js:429:387) at Object.dispatchEvent (https://editor.construct.net/r230/main.js:425:135) at Object.oG (https://editor.construct.net/r230/main.js:2131:241) at n.X$ (https://editor.construct.net/r230/projectResources.js:195:414)
Construct 3 version: r230
URL: https://editor.construct.net/r230/
Date: Mon Jan 11 2021 21:59:37 GMT+0200 (Eastern European Standard Time)
Uptime: 382.6 s

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r230 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: frame not in this animation @ Error: frame not in this animation at g.UJa (https://editor.construct.net/r230/projectResources.js:177:437) at n.tTb (https://editor.construct.net/r230/projectResources.js:187:302) at n.Uh (https://editor.construct.net/r230/projectResources.js:183:352) at n.Mi (https://editor.construct.net/r230/projectResources.js:6:6) at n.Xa (https://editor.construct.net/r230/projectResources.js:5:418) at Object.Pf (https://editor.construct.net/r230/projectResources.js:1124:18) at Object.Pf (https://editor.construct.net/r230/projectResources.js:1117:429) at Object.Pf (https://editor.construct.net/r230/projectResources.js:1199:228) at Object.ci (https://editor.construct.net/r230/projectResources.js:1121:153) at ya.ci (https://editor.construct.net/r230/projectResources.js:1009:190)
Stack: Error: frame not in this animation at g.UJa (https://editor.construct.net/r230/projectResources.js:177:437) at n.tTb (https://editor.construct.net/r230/projectResources.js:187:302) at n.Uh (https://editor.construct.net/r230/projectResources.js:183:352) at n.Mi (https://editor.construct.net/r230/projectResources.js:6:6) at n.Xa (https://editor.construct.net/r230/projectResources.js:5:418) at Object.Pf (https://editor.construct.net/r230/projectResources.js:1124:18) at Object.Pf (https://editor.construct.net/r230/projectResources.js:1117:429) at Object.Pf (https://editor.construct.net/r230/projectResources.js:1199:228) at Object.ci (https://editor.construct.net/r230/projectResources.js:1121:153) at ya.ci (https://editor.construct.net/r230/projectResources.js:1009:190)
Construct 3 version: r230
URL: https://editor.construct.net/r230/
Date: Mon Jan 11 2021 22:13:12 GMT+0200 (Eastern European Standard Time)
Uptime: 298.9 s

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r230 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by SnipG** [comment]
Error report information
Type: unhandled rejection
Reason: Error: no original size available @ Error: no original size available at n.Wra (https://editor.construct.net/r230/projectResources.js:234:475) at n.ded (https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:80:235) at https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:56:75 at Object.$ja (https://editor.construct.net/r230/main.js:906:76) at Object.Ws (https://editor.construct.net/r230/main.js:831:405) at Object.KA (https://editor.construct.net/r230/main.js:849:188) at Object.e3c (https://editor.construct.net/r230/main.js:910:96) at Object.LR (https://editor.construct.net/r230/main.js:910:27) at n.kva (https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:17:391) at n.Ni (https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:16:247)
Stack: Error: no original size available at n.Wra (https://editor.construct.net/r230/projectResources.js:234:475) at n.ded (https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:80:235) at https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:56:75 at Object.$ja (https://editor.construct.net/r230/main.js:906:76) at Object.Ws (https://editor.construct.net/r230/main.js:831:405) at Object.KA (https://editor.construct.net/r230/main.js:849:188) at Object.e3c (https://editor.construct.net/r230/main.js:910:96) at Object.LR (https://editor.construct.net/r230/main.js:910:27) at n.kva (https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:17:391) at n.Ni (https://editor.construct.net/r230/components/bars/propertiesBar/propertiesBar.js:16:247)
Construct 3 version: r230
URL: https://editor.construct.net/r230/
Date: Mon Jan 11 2021 23:06:50 GMT+0200 (Eastern European Standard Time)
Uptime: 2986.2 s

Platform information
Browser: Chrome
Browser version: 87.0.4280.88
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
C3 release: r230 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by SnipG** [comment]
Case is pretty chaotic, maybe needs a look at undo code directly. Or sometimes everything what user does, is not saved(dublicate/resize).

As i think bug is same but error code is changed, depending in which case undo/missing info occured.

I set idea it fails to undo. Followed direct order and it crashed, but not next 3 times. 
Case i tried when it crashed again:
![case](https://user-images.githubusercontent.com/28864889/104242352-b92c8780-5467-11eb-9406-4173548b1d51.jpg)

I tried to confuse undo redo, so it won't know where to undo, but still crash happened just once out of 6-7 tries.

**Comment by DiegoScirra** [comment]
Found a consistent crash following similar steps, it's difficult to tell if all the issues are related. We are getting ready for a new stable release, so the fix for this one will be out in the first beta after that.

**Comment by SnipG** [comment]
Neat. It would hard for me to confirm it when it's out. So i bet C3 has already logged thous error previously, a lot. After release if they still show up, then it's feasible to look into it again and try to find conistent crash repo. While i still think they are all same case, but could possible need different fix, as which info is lost.

**Comment by SnipG** [comment]
Another different one. Will log it in this bug report. Can move later.

Error report information
Type: unhandled rejection
Reason: Error: frame is not active @ Error: frame is not active at g.isb (https://editor.construct.net/r231/projectResources.js:177:262) at n.Gr (https://editor.construct.net/r231/projectResources.js:187:259) at Object.Sd (https://editor.construct.net/r231/plugins/allEditorPlugins.js:193:141) at Object.C3a (https://editor.construct.net/r231/plugins/allEditorPlugins.js:193:273) at Object.Sq (https://editor.construct.net/r231/plugins/allEditorPlugins.js:193:296) at n.Sq (https://editor.construct.net/r231/projectResources.js:227:452) at n.osa (https://editor.construct.net/r231/projectResources.js:234:319) at Object.jqb (https://editor.construct.net/r231/plugins/allEditorPlugins.js:184:36) at Array. (https://editor.construct.net/r231/plugins/allEditorPlugins.js:182:494) at Object.Lad (https://editor.construct.net/r231/main.js:429:387)
Stack: Error: frame is not active at g.isb (https://editor.construct.net/r231/projectResources.js:177:262) at n.Gr (https://editor.construct.net/r231/projectResources.js:187:259) at Object.Sd (https://editor.construct.net/r231/plugins/allEditorPlugins.js:193:141) at Object.C3a (https://editor.construct.net/r231/plugins/allEditorPlugins.js:193:273) at Object.Sq (https://editor.construct.net/r231/plugins/allEditorPlugins.js:193:296) at n.Sq (https://editor.construct.net/r231/projectResources.js:227:452) at n.osa (https://editor.construct.net/r231/projectResources.js:234:319) at Object.jqb (https://editor.construct.net/r231/plugins/allEditorPlugins.js:184:36) at Array. (https://editor.construct.net/r231/plugins/allEditorPlugins.js:182:494) at Object.Lad (https://editor.construct.net/r231/main.js:429:387)
Construct 3 version: r231
URL: https://editor.construct.net/r231/
Date: Wed Jan 13 2021 21:15:51 GMT+0200 (Eastern European Standard Time)
Uptime: 18960.8 s

Platform information
Browser: Chrome
Browser version: 87.0.4280.141
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
C3 release: r231 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
