### ISSUE TITLE
new release may cause the editor UI&bar Initialize postion incorrectly

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4467]
## Problem description

I have reported on this issue a long time ago. But at that time the console don't log any error, so the issues are directly closed. 

This time with the R231 update, I repeat this problem when I first opened new release. 

![01](https://user-images.githubusercontent.com/45864744/104409099-7ae6b380-55a0-11eb-8e98-6ac17469023c.jpg)
![02](https://user-images.githubusercontent.com/45864744/104409106-7d490d80-55a0-11eb-9bdb-75ea55a59499.jpg)
![03](https://user-images.githubusercontent.com/45864744/104409128-8803a280-55a0-11eb-9d42-61481ceea520.jpg)

At the time of the r230 update, no such case was sent. but r231 updated,  I can replicated it on my two computer. Then I'm trying to clear storage in Application, still invalid.  And when I open r230 again, it also looks like this.

![04](https://user-images.githubusercontent.com/45864744/104414063-8b039080-55aa-11eb-8135-d86a1ad16e86.jpg)

## Console log

The console is reporting some errors, so I'll paste them in here, maybe it'll help. this warning doesn't happen every time, it happens once. Refresh the page, there is no. Of course, the UI is still misplaced.  if I don't go to Settings to reset bar,&dialogs it will always be in this state.

```
main.js:252 Error while parsing the 'sandbox' attribute: 'allow-storage-access-by-user-activation' is an invalid sandbox flag.
```

```
(anonymous) @ main.js:460
n @ main.js:437
k @ main.js:437
main.js:460 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' blob: https://downloads.scirra.com 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-wqqyxwjupszqwEHKo6pBrBCZQ4qsuEztkXMlGnrYmMg='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
```

## Steps to reproduce
1. open [r231](https://editor.construct.net/r231/)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.141
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
C3 release: r231 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 285 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can't reproduce this, it works fine for me. There also does not appear to be anything meaningful in the log messages provided. I'm afraid without steps to reproduce the problem it's impossible to help. You can reset the UI in settings if you want to restore it back to default.
