### ISSUE TITLE
Animation editor grid does not work for collision grid points

### ISSUE THREAD

**Issue by ReflextionsDev** [Scirra/Construct-3-bugs#4469]
## Problem description

When using the animation editor, the user can configure and enable a grid. However, this grid does not work for collision points. Not sure if this is by design.

Any projects works, just create a sprite.

## Steps to reproduce

1. Create a sprite
2. Open the animation editor
3. Enable the grid
4. Change any collision mesh point

## Observed result

The point does not snap to the grid, even though it is enabled

## Expected result

The point should snap to the grid

## More details
![image](https://user-images.githubusercontent.com/3964845/104419940-2c58fb00-5547-11eb-9505-8af218ac8bf1.png)

**Affected browsers/platforms:** <

Chrome

**First affected release:** 

Earliest tested is r225.

**Comment by DiegoScirra** [comment]
This is already implemented. When you bring up the **"Configure Grid"** dialog, you are able to configure the **"Snap"** option, by default it is set to not snap, but it can be set to snap to the edges of the grid cells, or the centre of the cells.

**Comment by ReflextionsDev** [comment]
@DiegoScirra I've tried that and it not affect the issue. I think you may have misread the bug. I am talking about the **collision point editor** not following the grid snap, not the image points.

**Comment by ReflextionsDev** [comment]
![image](https://user-images.githubusercontent.com/3964845/107107631-4a411500-6800-11eb-847a-463572ca67be.png)
