### ISSUE TITLE
Could the expression drop down picker have a drag-to-resize corner which would be remembered?

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#447]
## Problem description

My problem is that my variables have long names. My project is big and I need to organize my vars in a way that I would know what they mean.
The expression drop down picker does not help me right now at all. The C2 one was better if I recall properly.

Could the corner be resizable? Also could the resize be remembered somehow in the project's settings so I wouldn't need to resize each time I open the expression dialogue or I start up my project?

This would be fancy :) 

## Attach a .c3p

![image](https://cloud.githubusercontent.com/assets/7268697/26802187/419ccbc6-4a48-11e7-80b2-c55f426b37c3.png)

## Affected browsers

* Chrome: yes
## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can you attach a .c3p so we can test with the project your screenshot is from?

**Comment by JeFawk** [comment]
Sure. I've attached a test project with variables I currently use.

![image](https://cloud.githubusercontent.com/assets/7268697/26804354/550ae08c-4a50-11e7-93da-c39fa49d4db5.png)

[LongVars.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1053257/LongVars.c3p.zip)

**Comment by AshleyScirra** [comment]
Rather than make it manually sizable, for the next build I just made it size-to-content. So it is always as wide as the widest item in the list. This means there's no need to scroll or resize the box, and you can always see all the names in the list in full. Hopefully that will work better!

**Comment by alastajj** [comment]
Are you also going to address the other bug in this thread or should I make a new thread about it? 

Sheets/Dialog/window/Preview sizes and positions are not remembered after you close C3 editor.

Each time I open C3 I have to resize and reposition the windows. It doesn't remember the resizing of event columns either, so everything is squished again when you open it up. The "dialog" preview window is always very small, and you have to resize that every time.

Construct 2 would remember all this each session.

Example: 

![pic1](https://user-images.githubusercontent.com/5744908/27211575-905f7f6c-529d-11e7-9971-07606acaeae3.PNG)
