### ISSUE TITLE
Tilemap rectangle tool bug

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4475]
## Problem description

When using the rectangle tool, selecting a different tile from the map will redraw the last tile in the object with the new selected tile. 

## Attach a .c3p

[tilemapBug.zip](https://github.com/Scirra/Construct-3-bugs/files/5815907/tilemapBug.zip)

## Steps to reproduce

1. Select rectangle tool
2. Select any tile from the map
3. Draw to the object
4. Select another tile from the map

## Observed result

The last tile drawn on the tilemap object changes to the new selected tile.

## Expected result

The tilemap object should not be affect when selecting a new tile.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
