### ISSUE TITLE
Folder names in timeslines are not saved

### ISSUE THREAD

**Issue by ffrk74** [Scirra/Construct-3-bugs#4477]
## Problem description

When renaming the name of a folder in the Timeline Zone it is not saved and when reopening the file its name is not kept.

## Steps to reproduce

1. Create a folder in Timeline folder
2. Save
3. ReOpen  

## Observed result

The name of the rename folder in timeline is not kept. 

## Expected result
The name of the rename  folder in timeline should be  kept. 

## More details 
Screencast of the problem on Chrome in the attached file

https://user-images.githubusercontent.com/65666256/104717887-53235700-572a-11eb-87b1-ae3c2e77ce2a.mp4

## System details

Windows

**Comment by AshleyScirra** [comment]
Should be fixed in next beta
