### ISSUE TITLE
Beta 231 Z Hierarchy

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#4478]
## Problem description

Similar to #4437 (Beta 229 Z Hierarchy):

In editor set Scene Graph Z order hierarchy is not correct

## Attach a .c3p

<s>[zhierarchy.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5820274/zhierarchy.c3p.zip)</s>
[z-hierarchy-error.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5822875/z-hierarchy-error.c3p.zip)

## Steps to reproduce

1.Note the z order of the existing objects set up with the Scene Graph Hierarchy
2.Run the project
3.Note the z order of the runtime created Scene Graph Hierarchy

## Observed result

The z order for the runtime created objects is different than the order set in the editor, and in the z order bar

## Expected result

The preset order should be used

## More details

**Affected browsers/platforms:** Chrome/Windows 10
**First affected release:** r229?

![image](https://user-images.githubusercontent.com/23579630/104723840-1fe3c680-5730-11eb-9c99-b8af01596a6b.png)

![image](https://user-images.githubusercontent.com/23579630/104778144-319f8b00-577d-11eb-8aaa-9226be7e3384.png)

**Comment by DiegoScirra** [comment]
Have you tried this in the latest beta, r231?

**Comment by el3um4s** [comment]
> Have you tried this in the latest beta, r231?

Yes, I created the c3p with r231

**Comment by DiegoScirra** [comment]
Is the project you posted the correct one? The screenshots are different to the project, and the project itself looks to produce the expected results.

**Comment by el3um4s** [comment]
You are right. I accidentally overwrote the file. 

[z-hierarchy-error.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5822880/z-hierarchy-error.c3p.zip)

![image](https://user-images.githubusercontent.com/23579630/104778089-16cd1680-577d-11eb-9a8f-c8b97b9bbbc7.png)

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta. Thanks for the comprehensive example 👍

**Comment by AshleyScirra** [comment]
Should be fixed in next beta
