### ISSUE TITLE
JSON Bug

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#4479]
## Problem description
I used same action but it is return different.
This works perfectly
![image](https://user-images.githubusercontent.com/54614906/104728753-73faa500-5748-11eb-977c-787e37e9f1c4.png)

[BugJson.zip](https://github.com/Scirra/Construct-3-bugs/files/5820505/BugJson.zip)

## Steps to reproduce

1. Click save button

## Observed result

> {
    "Level": [
        "{\n\"type\": \"117\",\n\"jsonData\": 155}",
        "{\n\"type\": \"220\",\n\"jsonData\": 139}"
    ]
}

## Expected result
>{
    "Level": [
        {
            "type": "117",
            "jsonData": 155
        },
        {
            "type": "220",
            "jsonData": 139
        }
    ]
}

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's working correctly. You're setting string values in the array. It happens to be a string of JSON data, but this doesn't matter, it keeps it as a string.

**Comment by CrackHub** [comment]
I think it is still bug because if you copy;

First Action
> {"is-c3-clipboard-data":true,"type":"actions","items":[{"id":"set-json","objectClass":"JSON","parameters":{"path":"\"Level.\" & loopindex",**"json"**:"\"{\n\"\"type\"\": \"\"\" & TEST.x& \"\"\",\n\"\"jsonData\"\": \" & TEST.y & \n\"}\""}}]}

Second Action

> {"is-c3-clipboard-data":true,"type":"actions","items":[{"id":"set-value","objectClass":"JSON","parameters":{"path":"\"Level.\" & loopindex",**"value"**:"\"{\r\n\"\"type\"\": \"\"\" & TEST.x& \"\"\",\r\n\"\"jsonData\"\": \" & TEST.y & \r\n\"}\""}}]}

Also you can see difference 
Bold vs normal
![image](https://user-images.githubusercontent.com/54614906/104743630-f8572300-575c-11eb-860a-1ba784c22d23.png)

**Comment by AshleyScirra** [comment]
One action uses "Set value", setting a string, and the other uses "Set JSON", which will parse the JSON string you gave it. It's all working correctly.

**Comment by CrackHub** [comment]
I was confused when i see this. Thanks for clearing. Two actions looks same, maybe one action can be different in event sheet view.

**Comment by AshleyScirra** [comment]
OK, I updated the 'Set JSON' action to use the word "JSON" for the next release.
