### ISSUE TITLE
Crash while renaming a layer if the layout changes 

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#448]
## Problem description

If you rename a layer and leave the textbox opened and then change to another layout, C3 crashes.

## Attach a .c3p

[LayoutCrash.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1053246/LayoutCrash.c3p.zip)

![layoutcrashgif](https://cloud.githubusercontent.com/assets/7268697/26804158/b2b31e62-4a4f-11e7-8b67-d099955b6976.gif)

## Steps to reproduce

1. Rename a layer and don't close the textbox
2. Change layout

## Observed result

Crashes

## Expected result

The rename textbox to close and accept the name and to change the layout

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected HTML element @ TypeError: expected HTML element at Function.ǃu.ǃpn (https://editor.construct.net/r35/main.js:2:178199) at c.ǃf_ (https://editor.construct.net/r35/main.js:61:235308) at b.ǃfY.then (https://editor.construct.net/r35/components/bars/layersBar/layersBar.js:1:3938) at 
Stack: TypeError: expected HTML element at Function.ǃu.ǃpn (https://editor.construct.net/r35/main.js:2:178199) at c.ǃf_ (https://editor.construct.net/r35/main.js:61:235308) at b.ǃfY.then (https://editor.construct.net/r35/components/bars/layersBar/layersBar.js:1:3938) at 
Construct 3 version: r35
URL: https://editor.construct.net/index.html
Date: Tue Jun 06 2017 00:29:30 GMT+0300 (GTB Daylight Time)
Uptime: 35.3 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r35

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r36.
