### ISSUE TITLE
Mapped Functions: Mapping functions returning a value with functions with no return doesn't work.

### ISSUE THREAD

**Issue by LapinChat** [Scirra/Construct-3-bugs#4480]
## Problem description

When mapping functions: if in the same group (same map name) there is a mix of functions returning a value with functions returning nothing, then calling mapped function within this group doesn't work.

## Attach a .c3p

[function_map.c3p](https://drive.google.com/file/d/1qtefPxPai4uiLC9cF_hWmuGcIvuEA9Gx/view?usp=sharing)

## Steps to reproduce

1. Select any item in the middle dropdown list. -> Result: nothing happen
2. Select any item in the left dropdown list. -> Results: mapped functions are called and text changed
3. Select any item in the right dropdown list. -> Results: mapped functions are called and text changed

## Observed result

Left and Right dropdown list call and execute successfully mapped functions. -> Results of functions appear as text below each dropdown.
Middle dropdown list doesn't call and execute successfully mapped functions. -> Results of functions doesn't appear as text below this dropdown list.

## Expected result

The middle dropdown list should call and execute mapped functions even if those mapped functions are a mix of functions returning or not returning value.

## More details

**Affected browsers/platforms:** 

Tested on Chrome, Firefox, macOs

**First affected release:** 
Tested on r225. I don't know if this problem was there before.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.141
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.15_7
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 140 gb
Storage usage (approx): 98 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) UHD Graphics 617
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is by design. Note the two messages logged in the console:

> [Construct 3] Function map 'mix_funcs' string 'Mix Get Func B' function return type not compatible with other functions in the map; entry ignored
> [Construct 3] Function map 'mix_funcs' default: function return type not compatible with other functions in the map; entry ignored

Currently Construct does not let you call functions that return a value from actions, nor call functions that don't return a value in expressions. You're basically trying to use function maps to circumvent that, and it's still not supported. Besides, if a function doesn't return a value, and you call it in an expression, what is it supposed to return? It's not a valid usage.
