### ISSUE TITLE
"Recreate initial objects" from another layout only spawns objects with hierarchy relationships in r231

### ISSUE THREAD

**Issue by ReflextionsDev** [Scirra/Construct-3-bugs#4481]
When using "Recreate intial objects" with "create hierarchy" enabled to spawn objects onto a **different layout**, only objects which have a hierarchy will be created. This only occurs in r231.

The Z order is also messed up per #4478 so this may be an extension of that bug.

## Attach a .c3p

https://github.com/ReflextionsDev/c3-bugs/blob/main/Hierarchy%20Test.c3p

## Steps to reproduce

1. Create a new project in r231 
2. Create two sprites, and assign one as a parent to the other
3. Make a copy of the parent sprite, without making another child
4. In a different layout, use the "Recreate initial objects" event, selecting the parent type. Enable hierarchy.
5. Launch the second layout and run the event (press space)
6. Observe not all objects will spawn

You may have to use the debugger to check object instances because they are hidden now as a result of the z order issue.

## Observed result

Only the object with a child is spawned.

## Expected result

All of the object types should be created, regardless of whether or not they have a child.

**Affected browsers/platforms:** 

Tested on Chrome and Firefox

**First affected release:** 

r231

**Comment by ReflextionsDev** [comment]
The attached .c3p was saved in r226 so you can test it in previous versions as well.

**Comment by AshleyScirra** [comment]
Should be fixed in next beta
