### ISSUE TITLE
Cannot import C2 Cordova project in C3 Export Manager

### ISSUE THREAD

**Issue by BiimGames** [Scirra/Construct-3-bugs#4482]
## Problem description

I am trying to import the Cordova project from C2 into C3 Export Manager as per official instructions., but I get the following message:
"Unable to import file. Only cordova projects exported from C2 or C3 can be imported."

The issue is the same as reported in the past here:
[https://github.com/Scirra/Construct-3-bugs/issues/3468](url)

## Attach a .c3p

https://www.dropbox.com/sh/9c535gdn2ieq9h8/AABuAL7N6BsADsFczaMzPsuqa?dl=0

## Steps to reproduce

YouTube video to see all the steps:
(https://youtu.be/On0TmmWOSgY)

1. Export C2 Vertical Shooter Template as Cordova
2. Zipped the folder
3. Uploaded in C3

## Observed result

Receiving error message:
"Unable to import file. Only cordova projects exported from C2 or C3 can be imported."

## Expected result

Exported game for mobile use (Android APK).

## More details

Tested using C3 on Firefox and Chrome.

**Affected browsers/platforms:** 
Firefox version: 84.0.2 (64-bit)
Chrome version: 87.0.4280.141 (Official Build) (64-bit)

**First affected release:** 
C2 version: 279 (64 bit)     [not working, not tested on earlier versions]
C3 version: 225 stable     [not working, not tested on earlier versions]

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 84.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
C3 release: r225 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 440 mb (21.5%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The problem is you've zipped the files wrong - the export files are in a subfolder in a zip, whereas they need to be at the root level of the zip file, as noted [in this tutorial](https://www.construct.net/en/tutorials/using-c3-build-c2-mobile-22):

> Make sure the files *config.json* and *config.xml* are at the root level of the zip, and not inside a subfolder in the zip.

If I extract the provided zip, zip the extracted files again so those files are at the root level, and then try and import it to Construct 3's export manager, it works.
