### ISSUE TITLE
Setting Y value to BBoxTop on Jumpthru object triggers fall

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4483]
## Problem description

(Sorry to report another jumpthru bug...)

When setting the Y value of a 'Platform object' to the BBoxTop value of a 'Jumpthru object', the Platform object falls through the Jumpthru object. (A minor offset solves this, but you'd expect the same Y value to register as landed on a Jumpthru object.)

## Attach a .c3p

https://drive.google.com/file/d/1vOwX0xRC_b6C4Ikz7vLITI-QDIBOe8pX/view?usp=sharing

## Steps to reproduce

1. Run the project
2. Press Up to jump

To see the offset solve:
1. Enable the "Success" action
2. Disable the "Fail" action
3. Run the project
4. Press Up to jump 

## Observed result

The Platform object falls through the Jumpthru object.

## Expected result

The Platform object lands on the Jumpthru object.

## More details

**Affected browsers/platforms:** Chrome 87

**First affected release:** r231

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Exactly adjacent objects count as intersecting in Construct, so it's the same as positioning the player inside a jump-thru, and the platform behavior is allowed to fall through a jump-thru that it intersects, so it's working as expected.

In general you should not try to interfere with the platform behavior positioning like this. There are extremely finely tuned collision algorithms in the Platform behavior, and you will probably only break it and introduce problems if you try to do things like this.

**Comment by brushfe** [comment]
Cool, thanks. It didn't seem interfering, as the platform object was above the jumpthru, and not visually overlapping. But it's good to know sharing an edge counts. This was my attempt to fix platform objects landing but staying 1px above the floor they landed on, which happens occasionally. I'll try to isolate and report that bug.

**Comment by AshleyScirra** [comment]
FYI, there is code in the Platform behavior specifically to move the player on to the platform with sub-pixel precision, so it should already be landing with something like 1/16th of a pixel precision.

**Comment by brushfe** [comment]
Interesting! I'm sure gotta be a problem on my end, you've got the platform behaviour to a fine science by now and certainly landing on an object would have been sorted a while ago. It's a pixel art game so wonder if it's a rendering or origin point issue on my end. I'll dig into it. Thanks again for your help and clarification with this!
