### ISSUE TITLE
NWjs condition "On save dialog cancel" never triggers

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#4485]
## Problem description

The "On save dialog cancel" condition from the nwjs plugin doesn't seem to trigger at all. 
Not sure why since "on save dialog OK" works fine.

## Attach a .c3p

[Save File Repro.zip](https://github.com/Scirra/Construct-3-bugs/files/5828528/Save.File.Repro.zip)

## Steps to reproduce

1. Run c3p inside Construct 3 NWjs or export it to NWjs from any browser
2. Click on the button
3. Click on "cancel"

## Observed result

It should fire an alert when the saving dialog has been cancelled.

## Expected result

It doesn't fire the cancel alert.

**Affected browsers/platforms:** NWjs

**First affected release:** No clue, sorry.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.50.3
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.50.3 (like Chrome/87.0.4280.141)
C3 release: r231 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 325 gb
Storage usage (approx): 1.5 gb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 SUPER Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks like a bug in NW.js. I filed it with them here: https://github.com/nwjs/nw.js/issues/7658
