### ISSUE TITLE
Error when clicking on preview

### ISSUE THREAD

**Issue by lukreaner** [Scirra/Construct-3-bugs#4490]
## Problem description
Construct 3 crashes after clicking on preview

## Attach a .c3p

Happens even on a new and unmodified project.

## Steps to reproduce

1. Open Project
2. Click on preview

## Observed result

Error message. Preview not working.

## Expected result

Start game preview.

## More details

I am new to Construct 3 and started with the beginner guide. In the guide I clicked on "click here to open the finished game." and clicked on preview. Than the error appeared. I also tried it  with a new project without doing anything in it but with the same problem. I tried different browsers and with and without a vpn. I have the same problem on my Laptop (with Firefox and Edge, haven't tested chrome on it). Edge did not had any extensions installed on both devices. Firefox has some, chrome only honey and lastpass.
**Affected browsers/platforms:** 
- Firefox
- Chrome
- Edge

**First affected release:** 
- r225

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Event 'error': [object Event]
Construct 3 version: r225
URL: https://editor.construct.net/
Date: Tue Jan 19 2021 15:23:21 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 540.6 s

Platform information
Browser: Chrome
Browser version: 87.0.4280.141
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
![chromeError2](https://user-images.githubusercontent.com/14851832/105049792-52adf780-5a6d-11eb-9277-48e7cfb94834.png)
![chromeError1](https://user-images.githubusercontent.com/14851832/105049796-53468e00-5a6d-11eb-9778-fa97ebd94eb5.png)

</details>

**Comment by AshleyScirra** [comment]
This looks almost exactly the same as #4489, which was filed only hours ago, including the same "gc.kis.v2.scr..." text being inserted in to URLs. See the comments in that issue for more details, it's may be a browser extension breaking Construct, but it's difficult to help without more information, and it appears to be working fine for me.

**Comment by AshleyScirra** [comment]
I just noticed, there appears to be references to "kasp", so this may be Kaspersky Internet Security breaking Construct. This seems to have happened before and nobody seems to be able to figure out why, including Kaspersky. See [this forum thread](https://www.construct.net/en/forum/construct-3/general-discussion-7/issues-loading-construct-150535) for more details.

**Comment by lukreaner** [comment]
Thank you for your help! It works for me now. To make it workd i had to disable "Inject script into web traffic to interact with web pages" in Kaspersky and clear the browser cache.
