### ISSUE TITLE
Tilemap Issue 

### ISSUE THREAD

**Issue by redGamer777** [Scirra/Construct-3-bugs#4492]
## Problem description
I tried to create a tilemap, but when placing a block, It didn't show up. after a few attempts I went to the debug screen and found that the tilemap was deleting itself, and respawning itself. I didn't write any events about the tilemap,  and then, my tiled background disappeared!

## Attach a .c3p
blob:https://editor.construct.net/9a090d77-6462-4668-bd05-0c47f2d302a2

## Steps to reproduce

1. open the debug screen
2. go to tilemap
3.

## Observed result

 the tilemap was destroying and recreating itself

## Expected result

 I expected to see the tilemap staying there

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please attach a valid .c3p project file. The link you provided does not work. The issue cannot be investigated until you provide a project file as per the bug report guidelines.

**Comment by DiegoScirra** [comment]
Closing this for lack of information.
