### ISSUE TITLE
Asian characters can‘t convert to latin operators in Expressions

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4493]
## Problem description

[r190](https://www.construct.net/en/make-games/releases/beta/r190) Allow use Asian characters in Expressions. But it now appears to be unreadable.

Set Text: 
```
“Hello Construt 3”
```

error:
```
String missing finishing "
```

| En | Cn |
|---|---|
| ![en](https://user-images.githubusercontent.com/45864744/105182855-828df580-5b68-11eb-95c1-c1b382db23ef.png) |  ![cn](https://user-images.githubusercontent.com/45864744/105182583-29be5d00-5b68-11eb-9533-9903225ac778.png) |

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It works, but the start and end quote characters must be the same, e.g. `“Hello“` or `”Hello”` or `"Hello"`. If the character is different, it is counted as part of the content of the string.

**Comment by XHXIAIEIN** [comment]
> It works, but the start and end quote characters must be the same, e.g. `“Hello“` or `”Hello”` or `"Hello"`. If the character is different, it is counted as part of the content of the string.

In Asian languages, the start quote and  end quote are different characters.

**Comment by AshleyScirra** [comment]
Our expression parser requires that strings start and end with the same character, which is currently by design.
