### ISSUE TITLE
Greenworks Advanced Minify Not Working

### ISSUE THREAD

**Issue by BluePinStudio** [Scirra/Construct-3-bugs#4496]
## Problem description

I am making a second report. I have tried everything to get Advanced minify to work but it does not. **The only plugin i have installed is Greenworks**. A blank project works fine but my capx does not. Simple and No minify works fine. This is for exporting to NW.JS v0.50.0.

## Attach a .c3p

I would prefer not to attach my Steam game's capx file here for public download.

## Steps to reproduce

I have no idea how to re-create, all i know is that blank projects Advance-Minify fine, but mine does not. 

## Observed result

![MinifyError](https://user-images.githubusercontent.com/76889959/105351464-9e21ec00-5bba-11eb-90c4-f5aa58c8b583.JPG)

## Expected result

Exporting Success

## More details

**Affected browsers/platforms:** NW.JS v0.50.0

**First affected release:** 225 Stable

## System details

<details><summary>View details</summary>

Browser: Chrome
Browser version: 87.0.4280.141
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 1.7 gb (1.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by BluePinStudio** [comment]
Issue that is persisting despite my previous issue being fixed https://github.com/Scirra/Construct-3-bugs/issues/4454

**Comment by AshleyScirra** [comment]
An advanced minify works fine for me with r232 and the latest published Greenworks addon 0.47.0-r2 added to a new empty project. Make sure you've updated to the new version that was published as a result of fixing #4454. Otherwise you won't have the fix.
