### ISSUE TITLE
Pressing ESCAPE crashes the editor

### ISSUE THREAD

**Issue by elGabe** [Scirra/Construct-3-bugs#4498]
## Problem description

Crash when pressing the 'escape' key anywhere in the editor, on any project

## Attach a .c3p

Project Link: https://www.dropbox.com/s/amsbyyurbwdbzym/astronaut%20game.c3p?dl=0

Error still happens even if no project is loaded

## Steps to reproduce

1. Press escape anywhere in the editor, even if no project is open. Error occurs when there is no window to close.

## Observed result

A total crash, plus the dialogue to restart Construct

## Expected result

When a floating window is open, the window closes (which is expected); but if no floating windows are open, it shouldn't do anything.

## More details

Observed on Chrome version 88.0.4324.104

Construct Release: r225 stable, and r232 beta

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/, line 7, col 79
Message: Uncaught TypeError: Cannot read property 'contentWindow' of null
Stack: TypeError: Cannot read property 'contentWindow' of null at Object.closeModal [as closeTabMediaModal] (:7:79) at :2:21 at :3:5
Construct 3 version: r225
URL: https://editor.construct.net/
Date: Fri Jan 22 2021 17:24:00 GMT-0500 (Eastern Standard Time)
Uptime: 69.8 s

Platform information
Browser: Chrome
Browser version: 88.0.4324.104
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment]
Can't reproduce here, and I've never heard anyone else mention this issue even though it sounds obvious. My best guess is you have a browser extension that's interfering with Construct. Try disabling them until you find which one causes it.
