### ISSUE TITLE
Iframe - youtube controls

### ISSUE THREAD

**Issue by renanmoura12** [Scirra/Construct-3-bugs#4499]
To avoid adding a listener manually in the index.html and using JS.

It would be great to have these controls (can be a youtube behavior for iframe plugin) or just a flag for isYoutube:

1. Conditions to detect if the video in the iframe is currently playing/stopped.
2. Triggers when it is finished loading/playing.
3. Actions to play/pause video/volume control/mute.

**Comment by AshleyScirra** [comment]
Please post any suggestions to https://construct3.ideas.aha.io/
