### ISSUE TITLE
Open Recent Menu Severe Lack Of Information

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#45]
## Problem description

A project should not put priorities on the name of the project. Rather, the name of the project file. A mention of the project name should be an addition. Take the example of a default project name "New project" but if I saved this to local or cloud, I get the option to name the project file (.c3p) which aren't labeled in an "open recent" process, same goes to the project's version. So, if I create another project "New project" but saved as different project file name in cloud or local, the open recent will still list only the name of the project and not it's saved project file name. How do I distinguish them easily without a thought?

What if I do versioning with project file names rather than the built-in versioning in project properties? These questions should be addressed because they made the current "open recent" feature redundant.

**Comment by AshleyScirra** [comment]
Assigning to Iain since there needs to be extra metadata kept in the recent projects storage, which probably also means getting more metadata from cloud services.

**Comment by shortercode** [comment]
I think it should only require us to store the file name somewhere, we already have the rest of the information. 

With that we should be able to provide: filename, projectname, service ( google drive etc ) and last accessed time. Whether we actually want to show that much information in a small menu is questionable, but it would be down to tweaking the menu then anyway.

**Comment by AshleyScirra** [comment]
The recent projects list on the start page has lots of room, so that's somewhere we'd want to list all those details.

**Comment by pixelmetal** [comment]
Being able to see the version set under project properties in the dropdown menu for recent projects could be useful if you don't want to display the filename.

**Comment by shortercode** [comment]
I've added the version and filename to the recent project data. Also the filename is used instead of the project name as the label for recent projects now.

**Comment by shortercode** [comment]
Okay so spent a while considering this while doing other things, trying to cram some more text in would require reworking the menu system ( which is used in a lot of places ) just for this one small submenu. So I've made one more adjustment and going to leave it as is now. 

The icon next to each file now corresponds to where it's saved ( google drive, dropbox, etc. )

**Comment by jaydonteh** [comment]
https://github.com/Scirra/Construct-3-bugs/issues/297

**Comment by shortercode** [comment]
@jaydonteh ah didn't realise there was another bug referencing this, thanks for pointing that out
