### ISSUE TITLE
[r35] Crash when pasting local variables plus a subevent that uses them into a new event

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#450]
## Problem description

When I was copy/pasting some subevents containing local variables into a new top-level event, Construct 3 crashed. I narrowed it down to what's in the attached project. Just select the variables in the first event, copy and paste them into the second event to get the crash.

## Attach a .c3p

[CopyPasteCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/1054126/CopyPasteCrash.zip)

## Steps to reproduce

1. Create a top-level event and add two local variables to it.
2. Create a subevent with a condition that references both those variables.
3. Create a second top-level event.
4. Select the variables and subevent from the first event, and hit Ctrl+C to copy them.
5. Select the second top-level event and hit Ctrl+V to paste.

## Observed result

Construct 3 crashes.

## Expected result

The local variables and subevent should be pasted into the second top-level event.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Unknown expression 'Variable2': This is not a system expression or variable name in this scope.
Construct 3 version: r35
URL: https://editor.construct.net/index.html
Date: Tue Jun 06 2017 00:41:29 GMT-0700 (Pacific Daylight Time)
Uptime: 568 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r35

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in r36.
