### ISSUE TITLE
The Modulo operator is the remainder operator and there is no modulo operator

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#4505]
## Problem description
according to the manual, the % operator is a modulo operator, but it behaves like a remainder operator https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder
and there is no modulo operator in the expression editor

**Comment by AshleyScirra** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/Modulo_operation):

> In computing, the modulo operation returns the remainder or signed remainder of a division

So it's just another name for the same thing.

**Comment by eleanorawesome** [comment]
![image](https://user-images.githubusercontent.com/32940085/105846726-97281e80-5faa-11eb-9575-f2c9899c4e56.png)

They yield completely different results. 
n modulo 100 = r
will always yield a value between 0 and 100, effectively creating a wrap around where
if n = 101 then r = 1
but 
if n = -1 then r = 99

n Remainder 100 = r
does not create a wrap around, while 
if n = 101 then r = 1
but
if n = -1 then r = -1
