### ISSUE TITLE
using the key shortcut for back (Alt + Shift + 🡐 ) only works once when selecting an event

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#4509]
## Problem description
using the key shortcut for back (Alt + Shift + 🡐 ) only works once when selecting an event, If I open an event and use it, it goes back once, but then i have to manually press the back button with my mouse to go back more into the edit event dialogue

**Comment by eleanorawesome** [comment]
edit: Sometimes it doesn'T even work at all. Cause unknown

**Comment by AshleyScirra** [comment]
Suspect this is not a bug anyway as those are keyboard shortcuts to manage selection when the caret is in an input field, and it defaults to in the search field. Alt+Shift+B/N work in an input.

**Comment by eleanorawesome** [comment]
Alt+Shift+B works thank you

**Comment by eleanorawesome** [comment]
using Alt+Shift+B outside of the event editor dialogue creates a blank new event
