### ISSUE TITLE
New file -> Array is crashing C3

### ISSUE THREAD

**Issue by klabundee** [Scirra/Construct-3-bugs#451]
## Problem description

I created an array using New File -> Array (json), well, if it is 1x1 it runs and works ok, if you change the size like to 10x10 the coord 1x1 is not working and also crashs C3, you can't preview or even save a local file

## Attach a .c3p

I tried but after changing the array size I could not even download a local file.

## Steps to reproduce

1. New project
2. Right click on Files -> New file -> Array
3. Change the size to 10x10, try to preview it.

## Observed result

It crashes.

## Expected result

Change array values as should be.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'textContent' of undefined @ TypeError: Cannot read property 'textContent' of undefined at ǃpb (https://editor.construct.net/r35/components/editors/dataEditor/dataEditor.js:1:4768) at y.ǃpb (https://editor.construct.net/r35/components/editors/dataEditor/dataEditor.js:1:10927) at y.ǃpy (https://editor.construct.net/r35/components/editors/dataEditor/dataEditor.js:1:4739) at y.ǃpr (https://editor.construct.net/r35/components/editors/dataEditor/dataEditor.js:1:4206) at y.ǃpu (https://editor.construct.net/r35/components/editors/dataEditor/dataEditor.js:1:4023) at window.ǃxf.b.ǃpF [as ǃuzK] (https://editor.construct.net/r35/components/editors/dataEditor/dataEditor.js:1:1589) at window.ǃxf.ǃPl (https://editor.construct.net/r35/main.js:61:368219) at g.ǃuTE (https://editor.construct.net/r35/main.js:61:98109) at window.ǃVcJ.ǃVci (https://editor.construct.net/r35/main.js:162:29240) at n.then (https://editor.construct.net/r35/main.js:162:29925)
Stack: TypeError: Cannot read property 'textContent' of undefined at ǃpb (https://editor.construct.net/r35/components/editors/dataEditor/dataEditor.js:1:4768) at y.ǃpb (https://editor.construct.net/r35/components/editors/dataEditor/dataEditor.js:1:10927) at y.ǃpy (https://editor.construct.net/r35/components/editors/dataEditor/dataEditor.js:1:4739) at y.ǃpr (https://editor.construct.net/r35/components/editors/dataEditor/dataEditor.js:1:4206) at y.ǃpu (https://editor.construct.net/r35/components/editors/dataEditor/dataEditor.js:1:4023) at window.ǃxf.b.ǃpF [as ǃuzK] (https://editor.construct.net/r35/components/editors/dataEditor/dataEditor.js:1:1589) at window.ǃxf.ǃPl (https://editor.construct.net/r35/main.js:61:368219) at g.ǃuTE (https://editor.construct.net/r35/main.js:61:98109) at window.ǃVcJ.ǃVci (https://editor.construct.net/r35/main.js:162:29240) at n.then (https://editor.construct.net/r35/main.js:162:29925)
Construct 3 version: r35
URL: https://editor.construct.net/
Date: Tue Jun 06 2017 20:31:56 GMT+1000 (Hora Padrão: Austrália Oriental)
Uptime: 238.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r35

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
I'm afraid I don't seem to be able to reproduce the problem. Can you talk me through any other steps your doing?

Can you try my test file and see if it causes problems on your system? It should log out the array in the browser console when you preview it.

[data editor test.zip](https://github.com/Scirra/Construct-3-bugs/files/1054779/data.editor.test.zip)

**Comment by klabundee** [comment]
I tried your file, It worked but, it's just a 1x5 array. I've just changed it to 10x10 and got the error.
https://image.prntscr.com/image/23fe5f64e9ff46e9a4816ae5893a3278.png

**Comment by shortercode** [comment]
Well I had tried creating a new project and increases the file size exactly to 10 x 10 and to 40 x 40 without any issue. Then I tried adjusting the size of my test project without any issue.

I looks like cell (0, 1) is missing in your screen shot, which would explain the error. As for how that cell was lost, I'm drawing a blank.

When you increase the size do you use the width and height spinners at the top, or the context menu to insert rows?

**Comment by shortercode** [comment]
Also I see you have a few extensions, we've seen issues in the past where plugins break standard web page behaviour. Would you mind trying to repeat this in incognito mode? (plugins aren't enabled in incognito)

**Comment by klabundee** [comment]
Nice news, it was an extension.
After disabled Grammarly extension, it started to work as should.
Sorry for bother.

**Comment by shortercode** [comment]
That's okay, I saw the little G icon over the table and alarm bells started going off in my head!

Given that it's a problem with the extension I can't really do much to help, but it would be appreciated if you could bring it up with Grammarly. You can point them back at this bug, if they care, I'm not sure what their support is going to be like.

For reference: the editor is being broken by Grammerly inserting extra elements into the editor, which is breaking the lookup of table cells via `HTMLTableRowElement.prototype.cells`. In addition these extra elements are also affecting the layout of the table cells, as despite having no size being in a table is causing them to render as the same size as table cells.
