### ISSUE TITLE
Can't paste Hex color code to object/layer color property

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4513]
## Problem description

Can't paste Hex color code to object/layer color property

## Attach a .c3p

[colorCode.zip](https://github.com/Scirra/Construct-3-bugs/files/5887239/colorCode.zip)

## Steps to reproduce

1. Copy Hex color code from any source, outside construct, or even construct sprite editor
2. Try to paste it into the Hex color property of either a sprite or a layer.

## Observed result

Nothing get pasted. Pasting outside of construct does show the code when copied from the sprite editor.

## Expected result

pasting should work.

## More details

**Affected browsers/platforms:** Chrome/NWjs

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This seems to be a browser bug with the input of type color, I tried pasting into the HEX input outside of C3 and it doesn't work either.

You can try it here https://codepen.io/diegomarquez/pen/eYBpRQL.

Click the color input, switch to HEX and try to paste something, it doesn't work.

You can paste the HEX value directly on the Properties bar without bringing the color picker, just click on the numbers representing the color and paste the HEX value, after pressing enter it will be converted to the corresponding RGB string.

**Comment by AshleyScirra** [comment]
For reference it's [this Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1066509).
