### ISSUE TITLE
Video set playback time not working properly 

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#4516]
## Problem description

The video action set playback time seems to be broken since r226

## Attach a .c3p

https://mega.nz/file/w4sSmD6S#fBhYcH2zl6oPyEUclGioYyHvav4wZz7Jd4LjZDQPpKw
(file too big for github)

## Steps to reproduce

1. Open in r225 (latest stable iirc)
2. Open in r226 (any release of the beta branch)

## Observed result

On stable, the video seeks at the right time and keeps the played/paused status. On beta, it seeks  to 0 and plays the video

## Expected result

It should still act like it does on stable

## More details

**Affected browsers/platforms:** Chrome, haven't tested more

**First affected release:** r226

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Hmm, it looks like a Chrome bug that probably started happening due to our change to network requests in preview mode in r226. It's straightforward to work around though, so it should be fixed in the release out today.
