### ISSUE TITLE
Bug with 2 joystick

### ISSUE THREAD

**Issue by LolloGamer9000** [Scirra/Construct-3-bugs#4517]
By creating 2 joysticks on Construct 3, one for aiming the player and the other for movement, if I hold one down (fixed at a certain point, for example to the right) the other starts to lag.

**Comment by LolloGamer9000** [comment]
Here you find a video: https://youtu.be/_paCxk6IF-8
Here you find the code: ![2joystick](https://user-images.githubusercontent.com/78321981/106397457-dec90300-640d-11eb-8739-3c2f9f6dd237.png)

**Comment by LolloGamer9000** [comment]
I want to clarify that the code I found in an internet tutorial

**Comment by LolloGamer9000** [comment]
Here you find the .c3p file: https://howtoconstructdemos.com/two-virtual-thumbstick-capx/
(It is not my property, it is from a tutorual I found on the internet. Although I have tried with other methods but I have encountered the same problem)

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help you.
