### ISSUE TITLE
404 with AJAX requests for local files

### ISSUE THREAD

**Issue by RorySoh** [Scirra/Construct-3-bugs#4518]
## Problem description

Similar to the problem that happened here
https://github.com/Scirra/Construct-3-bugs/issues/4422

However, it's way rarer and more obscure now. I have no idea how to replicate it because of how rare it is. But I have a the console debug information and the modus operandi of the bug. It no longer happens reliably each time C3 preview suspends and resumes like before, but happens occasionally.

## Attach a .c3p

Unable to demonstrate with a C3 project as it happens not with the usage of a feature in a certain way.
Still unable to reliable reproduce, seemingly happens at random.

## Steps to reproduce

1. Enter preview mode.
2. Do other things in other windows for a long time maybe
3. Try to do a local AJAX request

## Observed result

https://streamable.com/q03ahz

This is a video showing the debug information of the error in the console when it happens, the version of construct (r233) and that the AJAX requested files are where they are supposed to be, as well as that a simple restart allows the same files to be requested again.

## Expected result

The dialogue should work.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid as described in the bug report guidelines it's impossible for us to help you unless you can provide a project file and reliable steps to reproduce. We cannot debug a video. Please file a new issue if you can provide the required project and steps.

Please note I also previously requested that you try clearing your browser data and I don't believe you've yet confirmed that you've actually tried this.
