### ISSUE TITLE
add my plugin to Whitelist plugins

### ISSUE THREAD

**Issue by rezamms** [Scirra/Construct-3-bugs#4519]
Hi, could you add this to the build service:

tapsell-v3-cordova-plugin

Thank you!

I need this plugin to add an ad service inside construct 3

**Comment by rezamms** [comment]
Why is this plugin not added to the list of allowed server plugins? I want to test and develop it quickly

**Comment by AshleyScirra** [comment]
Please be patient. Plugin requests go through a thorough security review and this can take a few weeks.

**Comment by rezamms** [comment]
Is there a way to check it out faster? We are at an event and for meeting a milestone, we need it as soon

**Comment by AshleyScirra** [comment]
I'm afraid not. We advise that you submit such requests several weeks in advance to mitigate it. In the mean time you can do your own offline builds with the Cordova CLI that has no restrictions on which plugins you can use.

**Comment by rezamms** [comment]
I have been waiting for several days
But it has not been confirmed yet
How can I be notified if it is approved?

**Comment by AshleyScirra** [comment]
Please be patient. Plugin requests go through a thorough security review and this can take a few weeks. We were also very busy in the past week or two with a stable release and dealing with the Google Drive outage. I am trying to get some reviews done today.

**Comment by rezamms** [comment]
Thankful
Very good if you can confirm today 👍

**Comment by AshleyScirra** [comment]
This plugin is now allowed on the build server. A version wasn't specified, so the latest v3.1.18 was added.
