### ISSUE TITLE
non carica i miei progetti archiviati in google drive

### ISSUE THREAD

**Issue by ruti951** [Scirra/Construct-3-bugs#4526]
## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by ruti951** [comment]
[anomalia.docx](https://github.com/Scirra/Construct-3-bugs/files/5921060/anomalia.docx)

**Comment by AshleyScirra** [comment]
Please see [this forum thread](https://www.construct.net/en/forum/construct-3/general-discussion-7/google-drive-cloud-save-outage-158182) for updates on a known issue with Google Drive. Apologies for the inconvenience.
