### ISSUE TITLE
Turn on edit in timeline with mesh cause crash r234

### ISSUE THREAD

**Issue by seyacat** [Scirra/Construct-3-bugs#4527]
## Problem description
Turn on edit in timeline with mesh cause crash r234

## Steps to reproduce

1. create a mesh
2. create timeline
3. turn on timeline edit

## Observed result

CRASH

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r234/components/editors/layoutView/layoutView.js, line 158, col 26
Message: Uncaught TypeError: this.sba is not a function
Stack: TypeError: this.sba is not a function at p.zec (https://editor.construct.net/r234/components/editors/layoutView/layoutView.js:158:26) at p.xO (https://editor.construct.net/r234/components/editors/layoutView/layoutView.js:157:228) at Array.sB (https://editor.construct.net/r234/components/editors/layoutView/layoutView.js:153:224) at d.Event.fNc.Qad (https://editor.construct.net/r234/main.js:429:387) at window.ll.dispatchEvent (https://editor.construct.net/r234/main.js:425:135) at window.ll.Ftd (https://editor.construct.net/r234/components/editors/layoutView/layoutView.js:14:204) at Upc (https://editor.construct.net/r234/components/editors/layoutView/layoutView.js:4:237)
Construct 3 version: r234
URL: https://editor.construct.net/
Date: Wed Feb 03 2021 15:11:09 GMT-0500 (hora de Ecuador)
Uptime: 105.6 s

Platform information
Browser: Chrome
Browser version: 88.0.4324.104
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
C3 release: r234 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
