### ISSUE TITLE
Error loading exporters r234

### ISSUE THREAD

**Issue by Andrea055** [Scirra/Construct-3-bugs#4529]
## Problem description

When i try to export a project, I get the error "Error loading exporters". Also the preview not working. I try to change 5 browser, clean up the cache, cookies but nothing work

## Attach a .c3p

[emailtest.zip](https://github.com/Scirra/Construct-3-bugs/files/5921931/emailtest.zip)

## Steps to reproduce

1. Open my project
2. Try to export it or start preview
3. See the error

## Observed result

The export give error "Error loading exporters"

## Expected result

Construct start the exporting process

## More details

I use WIndows 20H2, build 19042.746, I try with Microsoft Edge, Firefox and Chrome

I notice it rarely in r226 but i clean the browser and work, with version r234 not working at all

![bug](https://user-images.githubusercontent.com/26500347/106818136-2bb01200-6678-11eb-8a7c-1e138a5f306a.PNG)

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 85.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
C3 release: r234 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 223 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX Vega Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It works fine for me.

It might be a problem with your Internet connection. After the error, also try pressing F12 in case a more detailed error message is logged to the browser console. I'm afraid without further information or a way to reproduce the problem we can't help further.

**Comment by Andrea055** [comment]
With the latest release r234.2 work, sorry for the useless issue.
