### ISSUE TITLE
Crash when typing 'len' in an expression

### ISSUE THREAD

**Issue by UeliSo** [Scirra/Construct-3-bugs#453]
## Problem description

Crash when typing 'len' in an expression before the final parenthesis.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open the action in the attached project
2. Delete the '1', but do not delete the final parenthesis
3. Start writing 'len' at the place of the 3rd parameter

## Observed result

C3 Crash when the intellisense is opening

## Expected result

no crash

## Affected browsers

IDE (standalone)

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r35/main.js, line 149, col 95436
Message: Uncaught TypeError: Cannot read property 'length' of undefined
Stack: TypeError: Cannot read property 'length' of undefined at o (https://editor.construct.net/r35/plugins/system/plugin.js:1:1986) at window.ǃuvO.ǃuvt (https://editor.construct.net/r35/main.js:61:344444) at window.ǃuvO.ǃuNd (https://editor.construct.net/r35/main.js:61:345188) at window.ǃuvO.ǃuvT (https://editor.construct.net/r35/main.js:61:344110) at window.ǃuvO.ǃuNr (https://editor.construct.net/r35/main.js:61:345088) at window.ǃuNF.ǃujE (https://editor.construct.net/r35/main.js:61:365456) at window.ǃuvO.accept (https://editor.construct.net/r35/main.js:61:333535) at window.ǃWk.ǃucj (https://editor.construct.net/r35/main.js:61:332319) at window.ǃVYY.ǃVkL (https://editor.construct.net/r35/main.js:149:92723) at window.ǃVYY.ǃVYE (https://editor.construct.net/r35/main.js:149:95382)
Construct 3 version: r35
URL: https://editor.construct.net/index.html
Date: Tue Jun 06 2017 14:57:50 GMT-0300 (Hora oficial do Brasil)
Uptime: 291.8 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r35

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by UeliSo** [comment]
[TEST.zip](https://github.com/Scirra/Construct-3-bugs/files/1055989/TEST.zip)

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in r36.
