### ISSUE TITLE
Bug with two joystick

### ISSUE THREAD

**Issue by LolloGamer9000** [Scirra/Construct-3-bugs#4533]
## Problem description

 By creating two joysticks, one to move the player and the other to make him look in a direction, if you hold one down and move the other, the latter has a lag. If you don't understand how to reproduce the bug you can find the link to a video example: https://youtu.be/_paCxk6IF-8

## Attach a .c3p

 
[2joystick.zip](https://github.com/Scirra/Construct-3-bugs/files/5927977/2joystick.zip)

## Steps to reproduce

1. Press a random point on the right side of the screen
2. Press simultaneously in another point on the left side of the screen
3. Move the second touch randomly while staying on the left side of the screen

## Observed result

 The left joystick has a lag

## Expected result

 The left joystick should move smoothly without lags

## More details

**Affected browsers/platforms:**  All platforms (mobile only because it has double touch)

 

**First affected release:**  from r233

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.104
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
C3 release: r234.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 352 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I tried this with remote preview on a Pixel 3 and it was perfectly responsive. It always responded quickly no matter whether one or two touches were active.

My best guess is it's a device-specific issue and maybe the particular type of Android version or touchscreen hardware is slower to respond to multiple simultaneous touches. Without a way to reproduce the issue ourselves there's little we can do, and I'm afraid if it is the touchscreen or the OS, it's out of our hands anyway. For what it's worth, Construct itself has very little involvement with touch input. It just forwards the touch events the browser provides directly to your events. So it's difficult to see how any issues involving lag in touch input could actually be caused by Construct.
