### ISSUE TITLE
App exported for IOS Cordova doesn't work with Script type: Module

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#4535]
## Problem description

The game is stuck on the white loading screen with Construct icon.

## Attach a .c3p

Demo project:
https://www.dropbox.com/s/bswtnc133va91mc/IOS234_test.c3p?dl=0

Exported XCode project:
https://www.dropbox.com/s/irl9vyefhbpiedm/IOS234_xcode.zip?dl=0

## Steps to reproduce

1. Build for iOS and run.

## Observed result

Stuck on loading screen.

## Expected result

Should work.

## More details

I tried exporting from Chrome and Firefox, same result.
Tried Cordova project and XCode - same result.
Tested in Simulator and on a real iPhone - same result.

The app works if Script type is set to Classic. There are no addons or scripts in the project. 

**First affected release:** r234

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.146
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
C3 release: r234.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 77 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks for the minimal repro. The problem appears to be specifically the combination of using the legacy file: Cordova iOS scheme with module scripts mode. For now the best workaround is to switch scripts type back to classic. Newer apps using the modern app: scheme should also be unaffected.

It seems similar to a related problem we had with Android during the last beta cycle, and I've got a fix using the same workarounds as we have for Android on iOS with the legacy file: scheme. I suspect there are still many iOS projects out there still using the file: scheme, so we'll probably have a stable patch out early next week to address this.

**Comment by AshleyScirra** [comment]
This should be fixed in r234.3.
