### ISSUE TITLE
Vibration in apk or aab

### ISSUE THREAD

**Issue by TheAvIGOLD** [Scirra/Construct-3-bugs#4536]
## Problem description
I'm trying export my game with vibration permission, but it's not work. I'm using browser object and vibration action, set "require vibrate permission" when exporting, but nothing hapend. Vibration work in browser preview, but not when exporting to apk. 

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r225-r234.2

**Comment by AshleyScirra** [comment]
Please provide a project as per the bug report guidelines. This is to ensure we can reproduce your problem and is the first thing we check when investigating reports.

**Comment by TheAvIGOLD** [comment]
> Please provide a project as per the bug report guidelines. This is to ensure we can reproduce your problem and is the first thing we check when investigating reports.

This is a global error, it is on any project. If your rules require you to create a project, I can make a button that performs a vibration from the system Browser plugin.
