### ISSUE TITLE
Vibration permission

### ISSUE THREAD

**Issue by TheAvIGOLD** [Scirra/Construct-3-bugs#4538]
## Problem description

I'm trying export my game with vibration permission, but it's not work. I'm using browser object and vibration action, set "require vibrate permission" when exporting, but nothing hapend. Vibration work in browser preview, but not when exporting to apk.

## Attach a .c3p

[Vibration.zip](https://github.com/Scirra/Construct-3-bugs/files/5934774/Vibration.zip)

## Steps to reproduce

1. Added Button and browser
2. Set event- On touch button - browser vibrate with patter "200,100,200"
3. Export project for Android(Cordova)
4. Set Export options
![image](https://user-images.githubusercontent.com/19785639/107078208-0994cc00-67ff-11eb-95ce-07a30b6651a5.png)
5. Set Cordova options
![image](https://user-images.githubusercontent.com/19785639/107078267-229d7d00-67ff-11eb-9674-8c0313c2257a.png)
6. Set keystore and exported

## Observed result

Vibration does not work
(Aplication doen't have vibration permisson)
## Expected result

Vibration when the button is pressed

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r225-r234.2

**Comment by EMI-INDO** [comment]
**try this!**

https://www.construct.net/en/make-games/addons/476/vibrate

**Comment by TheAvIGOLD** [comment]
i tried, with addons i have export error.

**Comment by TheAvIGOLD** [comment]
Problem is not in browser\vibration plugin, problem is in permisson. Application doen't have it.

**Comment by AshleyScirra** [comment]
It works fine for me on a Pixel 3 with Android 10.

It's difficult to do anything unless we can reproduce the problem ourselves. Do you have any more details about the problem that may be able to help identify why it's not working for you?

**Comment by AshleyScirra** [comment]
There's been no response for a week and as far as I can tell this is actually working, so closing.
