### ISSUE TITLE
editor.construct.net 

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4539]
## Problem description
Currently https://editor.construct.net/  is cause of lot of problems, if user has used it before and new release comes out, it starts to bug like crazy, when new release redirects user back to main https://editor.construct.net/

Most likely result from cache, but it's not like user has to delete cache all the time.
Is even bigger problem when user uses c3 as an app from desktop.

## Observed result
New releases overwritting part of old cache or something and using https://editor.construct.net/  causes major issues.
Sometimes it does not update to latest stable and goes back to old stable release: https://editor.construct.net/ 

## Expected result
User, if he used c3 more then few month, should be able to specifie latest release even when it's stable. Something like https://editor.construct.net/r234 and it should not push/redirect user back to https://editor.construct.net/ to face bugs and crashes.

So user has option to use https://editor.construct.net/r234 or https://editor.construct.net. Users should not be pushed into https://editor.construct.net

## More details
Example:
Coming to latest beta --->
gets dialog to update latest stable ---> 
updating from beta to latest stable. --->
just landed https://editor.construct.net/  and it promps me again that latest stable is available, info shows https://editor.construct.net/  is previous stable. ----> 
update again. ------> 
now editor is ...messed up ---> 
it uses editor resources from previous stable and trows errors or crashes.

This might not be the case 100%, but each time new stable release comes out it a mess, gets fixed when I can switch to new beta with clean editor cache. So this is not first time and repeats and repeats with each new stable release!

**Comment by AshleyScirra** [comment]
It all seems to be working fine for me. editor.construct.net works, and editor.construct.net/r234 does not redirect you anywhere else, it loads that specific version.

I'm afraid it's difficult to investigate a report like this. It's not clear what you're actually talking about, especially with just a passing reference to things like "messed up" and "bugs and crashes" - we need to know specifically what this means. Further without reliable steps to reproduce there is little we can do, since as described in the bug report guidelines, we need these to be able to help.

**Comment by SnipG** [comment]
Issue was not specific, but case that bugs. To make developers aware of it, that something is not right when updating into same link/aadress that has been used before. Especially when updating into editor.construct.net.  Indeed, editor.construct.net/r234 works, but it does not use it, when you update from beta to stable. 

It's has no solid case, but over time, using new stable in editor.construct.net have caused strange errors. But this is just from my point of view, if i had more overall view like from developer side, who can see all errors reports from users, when new stable release is released. And if more strange errors do pop up in stable from users, then it might be worth to investigate. 

I bet issue is overall: old editor.construct.net plugins conflict with new editor.construct.net plugins, which user changed/updated in beta. Or somekind of list that holds them is not updated or something. It's dull and somewhat time consuming to test, but i though maybe Chrome has known cache problems, some internal list that don't update.

Anyway, i make new issue report if i got time to test thous things out, when they affect me more. I hope it's not just me and more errors/crashed do occure in stable(especially errors that don't show up in beta) with all users.
