### ISSUE TITLE
Crash when cut/paste and drag/dropping included event sheet

### ISSUE THREAD

**Issue by UeliSo** [Scirra/Construct-3-bugs#454]
## Problem description
I managed to reproduce the crash reported in
https://github.com/Scirra/Construct-3-bugs/issues/449

Crash when cut/paste and drag/dropping included event sheet

## Attach a .c3p

[TEST.zip](https://github.com/Scirra/Construct-3-bugs/files/1056048/TEST.zip)

## Steps to reproduce

Steps:
Open attached project
Open 'Event Sheet 1'
Cut the 'Include Event sheet 2'
Paste (it appears at the end of the 'Event Sheet 1')

## Observed result

Crash

## Expected result

no crash

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Crash Report:
Error report information
Type: unhandled exception
File: https://editor.construct.net/r35/main.js, line 61, col 301488
Message: Uncaught TypeError: Cannot read property 'ǃdP' of null
Stack: TypeError: Cannot read property 'ǃdP' of null at window.ǃuiK.ǃuRo (https://editor.construct.net/r35/main.js:61:301488) at window.ǃuiK.ǃujE (https://editor.construct.net/r35/main.js:61:300142) at t.accept (https://editor.construct.net/r35/main.js:61:253185) at window.ǃFSd.ǃujz (https://editor.construct.net/r35/main.js:61:259661) at window.ǃFSd.accept (https://editor.construct.net/r35/main.js:61:253201) at g.ǃuiH (https://editor.construct.net/r35/main.js:61:83093) at g.ǃFSF (https://editor.construct.net/r35/main.js:61:83021) at window.ǃFVM.ǃjl (https://editor.construct.net/r35/components/editors/eventSheetView/eventSheetView.js:1:24174) at window.ǃFVM.ǃFBt (https://editor.construct.net/r35/components/editors/eventSheetView/eventSheetView.js:1:22542) at window.ǃFVM.ǃkh (https://editor.construct.net/r35/components/editors/eventSheetView/eventSheetView.js:1:19714)
Construct 3 version: r35
URL: https://editor.construct.net/index.html
Date: Tue Jun 06 2017 15:23:45 GMT-0300 (Hora oficial do Brasil)
Uptime: 212.6 s
Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r35
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by UeliSo** [comment]
Sorry, somehow step 5 got lost:
5. Drag and drop the 'Include Event sheet 2'

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in r36.
