### ISSUE TITLE
Mesh editor mesh points grid snaps are imperfect

### ISSUE THREAD

**Issue by ReflextionsDev** [Scirra/Construct-3-bugs#4540]
## Problem description

When editing an object mesh in the editor, points on the mesh snap to the layout grid if enabled, however these points seem to be offset at random values, and do not follow the grid perfectly.

## Attach a .c3p

https://github.com/ReflextionsDev/c3-bugs/blob/main/Mesh.c3p

## Steps to reproduce

1. Create a sprite
2. Enable a 2x2 mesh 
3. Enable layout snap, and show the grid
4. Edit the sprite's mesh and observe the points do not snap correctly

## Observed result

The points snap at an offset

## Expected result

The points should snap perfect to the grid

## More details

This seems to be related to the zoom level of the layout. The further zoomed out you are, the worse the offset. If you zoom in all the way, you can get a close to perfect snap. 

**Affected browsers/platforms:** 

Chrome

**First affected release:** 
r234.2

**Comment by ReflextionsDev** [comment]
![image](https://user-images.githubusercontent.com/3964845/107107858-ca1baf00-6801-11eb-8831-da6e81a34290.png)
![image](https://user-images.githubusercontent.com/3964845/107107874-ee778b80-6801-11eb-9942-7ae9ff3bdc26.png)

**Comment by AshleyScirra** [comment]
Thanks, some of the calculations were indeed not quite correct. It should be fixed in the next beta.
