### ISSUE TITLE
Applying Hierarchy and Container to same set of objects Triggering "->On Created" twice

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#4541]
## Problem description

I have applied both hierarchy and containers on a set of objects.
The problem arises on the **"-> On Sprite object created"** Condition. It gets triggered twice. (In the attached c3p, The IID of that object gets logged twice.)

## Attach a .c3p

[hierarchy-container-error.zip](https://github.com/Scirra/Construct-3-bugs/files/5936501/hierarchy-container-error.zip)

## Steps to reproduce

1. Run preview
2. **Left Click** several times in the preview game.
3. Open Developer Tools > **Console**.

## Observed result

The IID of each object created will be logged **twice**.

## Expected result

IID of the created object should be logged only **once**. ("On created" condition should trigger only one time, instead it is getting triggered twice.)

## More details

**Affected browsers/platforms:** Only tested on Microsoft Edge. Not tested on other bowsers.

**First affected release:** Worked in r233 but broke in r234 and r234.2

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 88.0.705.56
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.56
C3 release: r234.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 180 gb
Storage usage (approx): 168 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
