### ISSUE TITLE
PREVIEW BLACK SCREEN

### ISSUE THREAD

**Issue by crugh** [Scirra/Construct-3-bugs#4542]
## Problem description
The preview on one Layout 1 stopped loading..... It has never had this issue before.

When I click Preview it shows a black screen
I have tried linking to a different event sheet with no code
I tried in debug mode
I tried a lower resolution
None of these resolved the issue

## Attach a .c3p
[Level4Game.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5938194/Level4Game.c3p.zip)

## Steps to reproduce
Click Preview on Layout 1

1. Click Preview on Layout 1
2.
3.

## Observed result
A black Preview screen

## Expected result
To play in the Preview mode.  The game played in preview with no problem for the last month without no changes or modifying the game.

## More details

Chrome and Safari were the only two browsers that I tested.
**Affected browsers/platforms:** 

It worked prior to  R234.2
**First affected release:** 

## System details
Platform information
Browser: Chrome
Browser version: 88.0.4324.150
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2.200000047683716
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
C3 release: r234.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 68 gb
Storage usage (approx): 127 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics 640
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The project contains the following third-party addons:

- Behavior MoveTo (Rex_MoveTo) by Rex.Rainbow
- Effect Ripple (Mikal_Ripple) by Mikal

These may be causing the problem, which is why we require that reports do not include third-party addons, as described in the bug report guidelines. If a third-party addon is causing the problem, you will need to contact the addon developer for support.

**Comment by crugh** [comment]
Sorry.  I tested the game by deleting the sprites from the original and all references to:
   
   - Behavior MoveTo (Rex_MoveTo) by Rex.Rainbow
   - Effect Ripple (Mikal_Ripple) by Mikal

I guess the third-party addons effect the preview  regardless and create the black screen.
I sent the original file.....
Thanks for checking.
    On Tuesday, February 9, 2021, 06:56:22 AM EST, Ashley (Scirra) <notifications@github.com> wrote:  
 
 


The project contains the following third-party addons:
   
   - Behavior MoveTo (Rex_MoveTo) by Rex.Rainbow
   - Effect Ripple (Mikal_Ripple) by Mikal

These may be causing the problem, which is why we require that reports do not include third-party addons, as described in the bug report guidelines. If a third-party addon is causing the problem, you will need to contact the addon developer for support.
