### ISSUE TITLE
Continued Trouble with Exiting and Re-entering a chat room 

### ISSUE THREAD

**Issue by part12studios** [Scirra/Construct-3-bugs#4543]
[quit multiplayer trouble.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5938205/quit.multiplayer.trouble.c3p.zip)

## Problem description

I cannot successfully exit a room and then re-enter it without refreshing the browser.  This is a follow up bug to a previous one which was dismissed for lack of an isolated example.  this version uses the scirra provided template with minimal changes showing how i'm trying to leave and return into the room with the same results as my other attempt embedded in a larger project.  

## Attach a .c3p

took the Construct multiplayer template as my test.  I simply added an Exit button in the chat room to trigger two different conditions of "disconnect" and "leave room" neither result in successfully leaving and then re-entering.

## Steps to reproduce

1.  launch the preview.. 
2.  sign in with a consistent name "Scirra" or whatever
3.  enter a room name "testroom" for example
4. notice you can type / say things / see everything work fine
5. click the "exit" button up top
6. you are returned to the login screen
7. enter name / room again.. 
8. enter room again..

## Observed result

you should be back "in" the room, but instead it's not reconnecting.  it's in a stuck state attempting to go in but because you're not a host or a peer no ability to type..  

## Expected result

you should be effectively be starting a new room by the same name.  you were the host.  when you leave the room should be destroyed and freed up to allow the same person to go back into the same room and recreate it.  

## More details

i made a 2nd example that i think will be attached called "leave room trouble"..  this one i made reliant on the logic going back to the main screen when disconnect or leave room are detected, but it all results in the same inability to go back into the room..  

This is all done in chrome.  haven't tried any other browsers... well i have but not consistently and certainly no better results.. so just say it's all chrome at this point.  

BONUS (optional) inquiry..  I also had no luck with kicking users..  so i'm not sure if this is also one of those things that works but only with some special combination to work properly..   i had a rule that you click the user name in the list which then populated that name in a variable..  and then with this variable was filled you could click a button which would kick this name from the list.. but nothing happens.  

Thanks!
Caleb

</details>
[leave room trouble.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5938224/leave.room.trouble.c3p.zip)

**Comment by AshleyScirra** [comment]
As far as I can see this is just a mistake in your events again. If you simply disconnect from the signalling server you have not indicated that you wish to leave the room. Further, waiting for 1 second is not sufficient to verify you have finished disconnecting, since it may take longer. You must use the appropriate triggers to identify when an operation has completed.

Bug reports are not the right place to deal with general support requests about how to build your project, so closing. The forum would be a better place for this type of message
