### ISSUE TITLE
r234.2 Shadowcaster  and Save Slot state

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4544]
## Problem description
Game save slots do not save the xy state of the Shadow Caster object
The load slot puts the xy at the center of the layout

## Attach a .c3p
https://www.dropbox.com/s/0tq4h3qijoiy0w4/shadownosavexy.c3p?dl=1

## Steps to reproduce

1. Run the project
2. Note the shadows
3. Press Save
4. Wait for save to finish
5. Press Load when saved
6. Note new shadow projection

## Observed result

The loaded ShadowLight will not be at the previous xy coordinates but instead cast from the center of the layout. 

## Expected result

Game Slot saves should save all object states
## More details

**Affected browsers/platforms:** 
Chrome
W10

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
