### ISSUE TITLE
NWjs export: Script Type: Module breaks Browser.IsFullscreen

### ISSUE THREAD

**Issue by jobel0092** [Scirra/Construct-3-bugs#4548]
When "Script Type" is set to "Module" the Browser plugin has issues with "Is Fullscreen"

https://drive.google.com/file/d/1RFtSDP9vLtxeS9Zb22hbfhC1LlwReouQ/view?usp=sharing

## Steps to reproduce

1. use stable Construct r234.2
2. set Script Type to Module
3. export to NWjs current version 0.51 Chromium 88

## Observed result

When you hit space bar nothing will happen

## Expected result

When hitting space bar it should toggle between fullscreen and not fullscreen

## More details
if you set Script Type to "classic" everything works as expected

**Affected browsers/platforms:** 

worked in previous stable (not sure of the version) but broke in latest stable (r234.2)

## System details

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
This is kind of weird, I have no idea what it has to do with modules mode, but it looks like we weren't detecting fullscreen changes early enough in startup to cover 'On start of layout'. It should be fixed in the next beta.
