### ISSUE TITLE
Opening same project twice results in duplicate projects in GUI

### ISSUE THREAD

**Issue by triptych** [Scirra/Construct-3-bugs#455]
## Problem description

*Enter a concise description of your problem here*
If you open the same project a second time, you now have two or more versions of the project open in the GUI which is very confusing.
## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
Not necessary for a specific project - works with any project as example.

## Steps to reproduce

1. launch editor
2. choose Menu > Project > Open  
3. (for instance open a project from the cloud - say foo.c3p)
4. observe the tabs that are added. and the Object Tree updated on the Project view.
5. now choose Menu > Project > Open  again
6. choose the same file (from the cloud, or whereever). and open it

## Observed result

The project is opened again as if it were a different project - with no warnings or differentiation.
This is very confusing since you might have been working on a project for a while with changes, but now you have duplicate windows open and no way to know which window goes with which project, so you might accidently start working on the dupe project code and lose the changes from the first instance. You should at least be warned that you are opening a second instance of the same files and be able to either abort, close the current one while opening this one, or go ahead an open it, but have some way to differentiate between the tabs and objects - like have a "-1" "-2" etc on their titles etc.

## Expected result

User should be warned that they are opening a already opened project and choose to either close the already open project, open the current one anyway, or cancel the open task.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

![glokar_-_construct_3_and_java_ee_-_rpptoolpages_src_main_java_com_ebay_app_raptor_rpp_domain_rpsbaseserviceimpl_java_-_ride_for_raptor_2_-__users_awooldridge_documents_workspace_kiosk_experimental_001](https://user-images.githubusercontent.com/8691/26853929-d4760d24-4ac8-11e7-8302-f3f830f6a34a.png)

**Comment by AshleyScirra** [comment]
This is actually really hard to do anything about. We previously did have code to actually entirely prevent you opening the same project twice, but we had to remove it. It worked by giving every project a unique ID. But then people do things like save a project, copy-paste it to a new file, open the copy, and edit it to be completely different. Then C3 completely blocks them opening the two projects at once, even though they are completely different, because the same project unique ID was carried across when they copy-pasted their project. So I'm not sure we can fix this without blocking valid cases of opening two projects simultaneously.

**Comment by shortercode** [comment]
I believe we can block using the file uid for projects opened from the cloud / local browser. However, this won't work for projects that are drag n dropped into the editor or opened from the local file system. 

Still... this will work for the majority of cases. So it's probably worth doing!

**Comment by triptych** [comment]
I agree there are hard edge cases, but if there could be at least warnings for the majority case, that would be an improvement.

**Comment by shortercode** [comment]
Okay I've resolved this that it will prevent you from opening a project with the same service file id. It won't prevent you from opening copies of the project from the same service or the same project from a different service. While this could still be considered confusing it's the behavior you'd get from a normal filesystem, so it's the sweet spot I think.
