### ISSUE TITLE
Animation editor draws with artifacts while snap is on

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4550]
## Problem description
Case you got snap-on and do drawing in animation editor.
Look image below:
![snapoo](https://user-images.githubusercontent.com/28864889/107338036-c28b2d00-6ac3-11eb-9952-626b45b16149.jpg)

Image where top is drag and bottom how it should draw with snap on!
When snap is on and user drags tool from one snap to another snap, it draws like there is no snap.

## Attach a .c3p
[snapo.zip](https://github.com/Scirra/Construct-3-bugs/files/5950012/snapo.zip)

## Steps to reproduce

1.Open example, open sprite in project
2.Erase colors, set grid 10x10, snap middle, select pen, set color and have color with low opacity
3.Drag pen from 1 snap to another.

## Observed result
When snap is on, pen still draws for each time it movies

## Expected result
When snap is on, pen/tool drag should just draw once for each cell. 

I think it should work like that, or maybe not?

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.146
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
C3 release: r234.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.2 gb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SnipG** [comment]
Tested a bit more.
Just want to add, that in some cases this multidraw is needed. So i don't know what would be appropriate fix for this. And from this issue report might fall into feature suggestion instead.

**Comment by DiegoScirra** [comment]
When using the snap options all the editor is doing is limiting the possible positions the pointer can take, after that is done, all the tools work in the same way as if there was no snapping. 

In the case of the brush and pencil tools, a stroke is drawn between each new point.

I think it would be good to see how other similar drawing applications handle this case before doing anything.

**Comment by SnipG** [comment]
I did check, but the problems seems a bit bigger. So it even more into feature suggestion.

Case is:  other drawing apps seems to be defaulted to 'Normal mode', ie it draws with single color. While c3 has some sort of multiple mode. Each time you go over it adds to old color.

While they handle current snapping like c3, but they don't produce color multiple, because their mode is different.
So in the end and compared to other apps, c3 handle snappling like them. So current issue is not a but, but is produce it because how drawing mode draws colors.

**Comment by DiegoScirra** [comment]
Ah I see, this has to do with how the drawing tools work, this includes the pencil, brush and eraser. As you move the tip of the brush, a "stamp" is drawn, that is why you get that effect of overdrawing with the colour getting progressively more saturated when you move the pointer.  Producing a stroke which has a uniform colour all along it's path requires a different way of drawing.

I'll be closing this issue now then.
