### ISSUE TITLE
 Crash when moving digital text while editing width and height.

### ISSUE THREAD

**Issue by ConstructBugsReport** [Scirra/Construct-3-bugs#4551]
Dear developers.
-------------------------
The problem that I am now describing to you has occurred more than 7 times during the operation of the application.
**
When working with an image, that is, with the size of the object, when opening the settings as in the screenshot, the text of the numbers is automatically selected, and moving it in the project crashes.

As I noticed, this happens after a large amount of application time has passed.**

Error report information
Type: unhandled exception
File: https://editor.construct.net/r234-2/main.js, line 832, col 104
Message: Uncaught TypeError: Cannot read property 'ownerDocument' of null
Stack: TypeError: Cannot read property 'ownerDocument' of null at HTMLDocument.Ss.L6 (https://editor.construct.net/r234-2/main.js:832:104)
Construct 3 version: r234.2
URL: https://editor.construct.net/
Date: Tue Feb 09 2021 18:05:53 GMT+0300 (Москва, стандартное время)
Uptime: 176407.6 s

Platform information
Browser: Chrome
Browser version: 88.0.4324.146
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
C3 release: r234.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

![Screenshot_5](https://user-images.githubusercontent.com/75397893/107383731-567be980-6b02-11eb-8b7b-5b0a101f989a.png)

**Comment by ConstructBugsReport** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/75397893/107385065-9abbb980-6b03-11eb-903d-d53c457c3e4a.png)

**Comment by DiegoScirra** [comment]
I am now able to reproduce the issue consistently. It should be sorted for the next beta.

Thanks for taking the trouble of filing this issue, I have been looking for this bug for a while now.

**Comment by ConstructBugsReport** [comment]
It is very good that I could either help you.

I wrote a lot about this on the forum, published at the bottom of each update release.

**Comment by DiegoScirra** [comment]
The fix for this issue is now out.
