### ISSUE TITLE
 This is not a bug but a request to the developers (Mesh editor)

### ISSUE THREAD

**Issue by ConstructBugsReport** [Scirra/Construct-3-bugs#4554]
Hello dear friends.

I ask you to add to "Mesh" the ability to turn off distortion of textures, that is, when, when editing objects using "Mesh" + "TiledBackground", the texture inside the object is stretched or narrowed depending on the polygonal points.

I ask developers to add the ability to enable or disable stretching of textures.

![Screenshot_5](https://user-images.githubusercontent.com/75397893/107458949-2bc37c80-6b66-11eb-87ed-130eed4964e3.png)

**Comment by ConstructBugsReport** [comment]
I would also like to ask if it is not difficult for you to implement this, expand the functionality of the "mesh" editor itself, I mean add additional tools for editing and editing in order to facilitate and optimize time when working with the mesh.

For example, add tools to cut, clean, add, and so on.

I think it will be just gorgeous))

**Comment by ConstructBugsReport** [comment]
Or create a new modified "TelidBackground +" Which would dynamically create any shape throughout the "Layout".
I will try to show it in the screenshot.

![Screenshot_4](https://user-images.githubusercontent.com/75397893/107460296-eb193280-6b68-11eb-8299-6f4f71ec726f.png)

**Comment by AshleyScirra** [comment]
Please post suggestions here: https://construct3.ideas.aha.io/

The issue tracker is for bugs only.
