### ISSUE TITLE
using await in javascript, clears out localvars

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#4555]
## Problem description

when using `await runtime.assets.fetchJson('test.json');` in script in events, the localVar object is cleared after this line is executed

## Attach a .c3p

https://drive.google.com/file/d/1gcu_H2C1IaJXjfAnfjeYKziayaOGPy-6/view?usp=sharing

## Steps to reproduce

1. have a function (with parameter) and create a script block
2. in the script block call the fetchJson function of the assets interface to fecth a localProject file
3. after that fetch happens, the localvars passed into the script are reset to default values

## Observed result

the localVars object variables get reset to default values of the data type. number = 0, strings  = ""

I added a debugger statement to the c3p file so you can step through while the project is running, and see the values change

## Expected result

the localVars object should be persisted for the full scope of the executing event block

## More details

**Affected browsers/platforms:** Edge  

**First affected release:**  r234.3 stable is when i noticed it, but i am not sure if this is when it was introduced

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 88.0.705.63
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.63
C3 release: r234.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 147 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by armandoalonso** [comment]
if i make that call to fetch synchronous, it behaves as expected, but this is not a viable work around, (maybe pre-fetching all the project files would be a viable work around for my specific use-case) but maybe awaiting any other types of promises might also clear out the localVars param.

**Comment by AshleyScirra** [comment]
It's not actually a bug, since using `await` allows the rest of the function to run to completion, and once the function has returned, its local variables no longer exist.

It's easy to work around though: just add `const value = localVars.value`; at the start, which captures the value in a JavaScript variable that you can reference throughout the rest of the code block.
