### ISSUE TITLE
Positional audio produces error in console w/ C3 Test project

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#4557]
## Problem description

Positional audio produces error report in console w/ C3 Test project.

## Attach a .c3p

Use the "Audio Positioning" C3 intermediate demo project.

## Steps to reproduce

Run project on Safari (Mac or iOS), check developer console.

## Observed result

In console get this error:
TypeError: undefined is not an object (evaluating 'pn["positionX"]["value"]')

## Expected result

No error in console (this is important to us, because we are using sentry.io bug tracking and errors in console are reported as errors to track. We can filter, but would prefer this be fixed, so we don't filter out other problems.)

## More details
It looks like Safari does not support the requested features (positionX, etc.)
https://developer.mozilla.org/en-US/docs/Web/API/PannerNode

**Affected browsers/platforms:** Safari (OSX/iOS)

**First affected release:** 

## System details

<details><summary>View details</summary>

OSX / iOS, Safari

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed for next beta. It looks like a missing feature in Safari 14 but it's straightforward to work around. FWIW Safari 14.1 (should be released in the next couple of months, can currently test with Safari Tech Preview) has an updated Web Audio API that better matches the spec, and doesn't have the problem, but the workaround I've added ensures it works in older versions of Safari.
