### ISSUE TITLE
C3 Crashes if I delete image source files

### ISSUE THREAD

**Issue by Ninjadoodle** [Scirra/Construct-3-bugs#456]
## Problem description

C3 Crashes if I delete image source files. If I import an animation, and then delete the images from disk - C3 will crash.

## Attach a .c3p

Can't do this, as you won't be able to load the project.

## Steps to reproduce

1. Import animation sequence
2. Delete the source images from disk
3. C3 will crash

## Observed result

C3 will crash

## Expected result

C3 will should not crash (like C2 doesn't in similar circumstances)

## Affected browsers

N/A

## System details

N/A

**Comment by AshleyScirra** [comment]
Probably same thing as importing files, need to read the files immediately.

**Comment by DiegoScirra** [comment]
This only happens when dragging and dropping, right?

**Comment by Ninjadoodle** [comment]
I just tried again, and in this case nothing happened. In the previous
case, C3 crashed as soon as I deleted the source image files.

**Comment by Ninjadoodle** [comment]
Ok, I just tested again and it seems to only happen when there are multiple
images (animation), and not a single image.

I've just move the animation frames to a new folder and C3 crashed
immediately.

**Comment by AshleyScirra** [comment]
@DiegoScirra in other places it happens with any way of importing files. The Blob Chrome gives you really just remembers the file path on disk, so unless you read it immediately (see CloneBlob/CloneFile) it will fail to read later if the file is moved/removed. This would actually explain why people get corrupt projects with empty image files, should fix ASAP.

**Comment by DiegoScirra** [comment]
Alright, this should be working fine from r36 on wards. Went through all the places the Animations Editor can import files and clone them as soon as the references are available.

**Comment by Ninjadoodle** [comment]
Awesome, thank you!
