### ISSUE TITLE
Android z-indexes changing

### ISSUE THREAD

**Issue by COGames66** [Scirra/Construct-3-bugs#4560]
## Problem description

When exporting to Android/Cordova with a signed release APK, when running on Android simulators in Android Studio, the z-indexes of objects
changes only when there is a certain number of objects on a layor.

.cp3 - https://1drv.ms/u/s!AobC4q3rBlr62Ik1zIpMgzaZCakFYg?e=2SDHNV

Image on chrome browser:
![image](https://user-images.githubusercontent.com/63972417/107789179-44c35d80-6d1f-11eb-829b-c5e0d4722325.png)
Image on Android:
![image](https://user-images.githubusercontent.com/63972417/107789273-63295900-6d1f-11eb-933c-b04bedc37264.png)

## Steps to reproduce

1. Create project on C3
2. Export with Android/Cordova using signed release APK
3. Run on emulator on Android Studio (note that multiple types of emulators were used with the same result) 

## Observed result

On Android the z-indexes of objects changes (but only if there are more than a specific number of objects on the layer).
Note that the barn image will go behind the ground image. Also, some of the sprites that are boxes will also go behind
the ground image. This does not happen on release r218, but will happen on all after that release.

## Expected result

The z-index should not change.

## More details
It seems that the z-index on Android is fine until a certain number of sprites are on a layer. Once that happens, the z-index 
of some sprites change. Android Studio emulators were used. The problem occurred on all types tested.
This does not occur in iOS or on browsers (chrome and edge).

When sprites are taken away, then it seems like the z-indexes are where they should be. The problem occurs only after a certain number of sprites are on a layer.

Release: r234.4 stable (same result), Changing scripts to classic does not change outcome.
Release: r235 beta (same result)
Release: r233 beta (same result)
Release: r225 stable (same result)
Release: r222 beta (same result)
Release: r220.2 beta (same result)
Release: r220 (unable to load - get error)
Release: r219 beta - (same result)
Release: r218 stable - WORKS as it should.

**It looks like it stopped working correctly on r219.**

## System details

</details>

**Comment by AshleyScirra** [comment]
Usually if things work correctly on other platforms but are broken on one, it indicates a problem with the platform, not Construct. If Construct's code was wrong, it would look wrong in Chrome too, but it looks right, suggesting Construct's code is actually correct. I suspect Android emulators may have poor quality graphics drivers which are causing the problem. Can you reproduce it on a real device? If not I would think this is a problem with the emulator, which means it would be something you'd need to report to the emulator developers. FWIW, I can't see anything in the r219 update that could be related to this; graphics driver problems can manifest unpredictably, so it may be an emulator bug that always existed but was only activated by some other innocuous change made in r219.

**Comment by COGames66** [comment]
You're right. I was able to load it up to a chromebook and android phone and the problem does not exist.

**Comment by AshleyScirra** [comment]
OK, sounds a lot like a graphics problem with the emulator, so closing.
