### ISSUE TITLE
Controls disabled after exporting to APK

### ISSUE THREAD

**Issue by ronbirus** [Scirra/Construct-3-bugs#4561]
## Problem description

For some reason, when I export my project as an APK. The controls don't work at all. When I delete the Audio plugin and files, it works as intended.

## Attach a .c3p

https://drive.google.com/file/d/17FdtH9HIOdJs18IJ57dr16iYhChU-lCl/view?usp=sharing

## Steps to reproduce

1. Export as Debug APK

## Observed result

When installed, game loads as intended. The music plays, but the touch controls aren't working at all

## Expected result

Touch controls should be working

## More details
- Only happens on Android
- PC works fine
- Problem goes away when audio and files are deleted
- The specific audio files I used don't cause any problems for any other projects

**Affected browsers/platforms:** 
Android

**First affected release:** 
Not quite sure.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.152
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Android
Operating system version: 10
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2.625
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 10; SM-A705W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Mobile Safari/537.36
C3 release: r234.4 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 66 gb
Storage usage (approx): 205 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Qualcomm
Renderer: Adreno (TM) 612
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It seems to work identically in Chrome with Remote Preview and as an Android APK for me. It shows a title screen with an orbiting sprite, and I can drag that around. I don't know what I'm supposed to do next though.

I would assume this is just a mistake in your events. As explained in the bug report guidelines, please provide a minimal project to prove that the problem really is with Construct and not your project.
