### ISSUE TITLE
Lose of transformation options after undoing a mesh

### ISSUE THREAD

**Issue by TMsimonW** [Scirra/Construct-3-bugs#4562]
After using the undo tool on an object that currently has a mesh you will lose all options to rotate or change the size of the object

1. create a blank project and add a square on to the layout 
2. create a mesh 2,2 on the object
3. click the undo option at the top left of C3 

## Observed result

you are no longer able to change the objects size or rotation through the editor

## Expected result

To still be able to have the options to change the size and rotation through the editor

## More details

Noticed in Chrome on Chrome os not tried in any other browsers

First noticed in R235

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
