### ISSUE TITLE
Re-whitelist plugins

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4565]
Hi @AshleyScirra, thank you.

Ref: https://github.com/Scirra/Construct-3-bugs/issues/4495

However, there is an unexpected requirement in the C3 Build Service that I didn't know.
It seems you require `<preference name="GradlePluginGoogleServicesEnabled" value="true" />` instead of our own declarations, otherwise the build will fail.

![image](https://user-images.githubusercontent.com/31282960/107800400-b3450180-6d99-11eb-9abe-0794bcda522e.png)

I removed that dependency and replaced it by declaring the one in the **Addon SDK** (`SetGooglePlayServicesEnabled(enabled))`.

Please change `chadori-mobile-firebase-analytics@0.0.3` into `chadori-mobile-firebase-analytics@0.0.4`. 
And `cordova-plugin-firebase-config@5.0.0` into `chadori-mobile-firebase-remote-config@0.0.1`.

I've only removed one line of dependency in this update, for both plugins.

I hope we can get a quick patch for this. Thank you.

**Comment by AshleyScirra** [comment]
Updated build service allowlist.
