### ISSUE TITLE
Empty text string + vertical alignment bottom/center + bbcode = crash

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4568]
## Problem description

A text object with an empty text string that has vertical alignment set to bottom/center and bbcode enabled will crash both run-time and edit-time.

I first encountered this in runtime, I was setting a text object to "" right before saving this made the game crash, took a while to figure out it was related to the text action...

## Attach a .c3p

[textBug.zip](https://github.com/Scirra/Construct-3-bugs/files/5978527/textBug.zip)

## Steps to reproduce

1. Try enabling bbcode on the empty text object instance
2. Or try deleting the text from the second instance.

## Observed result

C3 crashes.

## Expected result

No crash.

## More details

**Affected browsers/platforms:** Chrome/NWjs

**First affected release:** r235
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
