### ISSUE TITLE
Pin doesn't always work correctly

### ISSUE THREAD

**Issue by Ninjadoodle** [Scirra/Construct-3-bugs#457]
## Problem description

In the attached case, the pin on one of the instances is offset by a large distance.

[PinBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1056603/PinBug.c3p.zip)

## Steps to reproduce

1. Open the project
2. Look at the bottom Ufo
3. Pin is offset by a large distance

## Observed result

Pin is offset by a large distance

## Expected result

The pinned image should be in the same place as the other two Ufos

## Affected browsers

Can only test in Chrome

## System details

N/A

**Comment by AshleyScirra** [comment]
It's not a bug. You change the sine cycle position before pinning which causes the object to be offset.

The others aren't affected because a cycle position of both 0 and 0.5 are in the original position when using a sine oscillation.

**Comment by Ninjadoodle** [comment]
Sorry, I did't realize that's how it worked. Thank you for the explanation :)
