### ISSUE TITLE
Save & Load doesn't save Text & SpritFont Scaled size when these are child object

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4570]
## Problem description

SpriteFont & Text added as child to a Sprite and On events I scaled up that Sprite which scaled spriteFont and Text obj too. When I save it by "Save & Load" action and load it then SpriteFont & Text were not saved to their scaled size.

## Attach a .c3p
[text save issue.zip](https://github.com/Scirra/Construct-3-bugs/files/5982408/text.save.issue.zip)

## Steps to reproduce

1. open attached file
2. play preview 
3. wait for finish tween scale
4. Once tween scale finish then press save button
5. then press load button.

## Observed result

SpriteFont & Text were not saved in scaled size

## Expected result
save them in their scaled size

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report, this turned out to be pretty complicated but it should be fixed for the next beta.
