### ISSUE TITLE
Loader style Progress bar & logo` 

### ISSUE THREAD

**Issue by AccordEuro06** [Scirra/Construct-3-bugs#4572]
**PROBLEM DESCRIPTION**
Exported game does not show `Progress bar & logo`, when running project from editor everything works great, but once project is exported - no logo is shown.

**Steps to reproduce**
1. create a new project
2. startup -> Loader style -> `Progress bar & logo`
3. add icon to `icons`
4. export project

**OBSERVED RESULTS**
when opened from construct engine -> `Progress bar & logo` is shown
when project is exported `Progress bar & logo` - logo is not shown

**Expected result**
Logo should be shown 

[picture](https://construct-static.com/images/v865/uploads/articleuploadobject/0/images/54691/loading.png)

**Comment by AshleyScirra** [comment]
No project was provided so I exported Space Blaster. It seemed to load just fine - there was no 404 error for loading-logo.png as showed in your screenshot. Please see the bug report guidelines: we need your project to be able to see what you're seeing.

I noticed the priority of loading the loading-logo.png file, if one was specified, was not loading it early enough to guarantee it would be displayed. I will try increasing this priority for the next beta. However it is not possible to verify it works for you based on this report, so closing.
