### ISSUE TITLE
New mesh bugs

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4573]
## Problem description
Look image below.
![nice](https://user-images.githubusercontent.com/28864889/108092429-673dd980-7085-11eb-9f9b-423f81221989.jpg)

Might not be a bug, but could need info which case to avoid.

## Steps to reproduce

1.Open mesh distort example, create 10x10 mesh with piggy sprite
2.Distort meshpoint under piggy arm over piggy arm, click shift while it's over it, now move point outside mesh and then leave the point somewhere top of the hand, 2 image below shows the spot.
3.Drag point back to original place

![ssasaddds](https://user-images.githubusercontent.com/28864889/108093819-ccde9580-7086-11eb-8551-068f920d5610.jpg)

Also small video. Maybe helps

https://user-images.githubusercontent.com/28864889/108095108-301cf780-7088-11eb-812e-05b06a10e03d.mov

## Observed result
Something copies image into wrong triangle.

## Expected result
No bug or it's the edge case?

Could also be feature? If made available more clearly? 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.150
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
C3 release: r236 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.3 gb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks weird, but I don't think it's a bug. When you hold shift it moves both the mesh point and the texture co-ordinates - that is how it gets the non-distorting effect. However unlike the point position, the texture co-ordinates are not allowed to go outside the image area. Therefore you can get some odd clamping effects where it's sampling from unpredictable areas of the image across the mesh triangles if you hold shift to change the texture co-ordinates then move a mesh point outside the image.

**Comment by SnipG** [comment]
That means?:
 if image is already distorted outside image area and user uses shift, then it's not supported and could cause clamping effect?
Or
If user distorts image inside image area and then use shift in 'some cases' the clamping effect should not show up?
Or
New mesh 'shift' feature is just ment to use around edges, previously non distorted images?

Currently i can reproduce this bug even without going outside image area. 
Look Sample vid below:

https://user-images.githubusercontent.com/28864889/108201230-38c50a80-7128-11eb-8a7e-8c1245ca4826.mov

**Comment by SnipG** [comment]
When using shift to move point back, no clamping will occur.
I though you ment image as whole, but i get it now how it works.

It's just edge case and not a bug.
