### ISSUE TITLE
Black screen in Preview

### ISSUE THREAD

**Issue by sergiupetrea-86** [Scirra/Construct-3-bugs#4574]
## Problem description

Black screen on Preview.

## Attach a .c3p

[FirstProject.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5994122/FirstProject.c3p.zip)

## Steps to reproduce

1. I started a new project and I added some Tiled Background and a Player.
2. After adding this elements the Preview was working as aspected.
3. I saved the project and closed the app also I want to mention that this is happening also in browser (Chrome).
4. When I come back today and open the project that I started yesterday the Preview is not working anymore (black screen).

## Observed result

The screen remain black in preview, if I start a new project is working but with the old one no.

## More details

**Affected browsers/platforms:** Chrome and Desktop App.

**First affected release:** Release r234.4

## System details

I use MacBook Pro and Chrome browser

In browser under Inspect I noticed an error when I press Preview button:

![Screen Shot 2021-02-17 at 11 58 17 AM](https://user-images.githubusercontent.com/52706393/108187726-72d9e080-7117-11eb-8ef8-5e9c43d79556.png)

Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' blob: https://downloads.scirra.com 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-2EA12+9d+s6rrc0rkdIjfmjbh6p2o0ZSXs4wbZuk/tA='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by AshleyScirra** [comment]
It's not a bug. You've just (presumably accidentally) turned off "initially visible" for the layout's only layer, so no content is rendered. Tick "initially visible" and it renders correctly.
