### ISSUE TITLE
TypeError: Cannot read property '_GetLastCachedZIndex' of null

### ISSUE THREAD

**Issue by nerdError** [Scirra/Construct-3-bugs#4575]
## Problem description

Started to work on a little mobile game. Makde menu one with several global layers, and "Menu 2" that also has those global layers. And then i made buttons to move back and forth between them. And when i move from "Menu 1" to "Menu 2", everything is fine. But, when im trying to move back from "Menu 2" to "Menu 1", i get an error in Construct 3 source code (check dev console)

![image](https://user-images.githubusercontent.com/55310192/108183208-eaf5d580-711a-11eb-8e06-e2ed344dc2a3.png)

## Attach a .c3p

[c3 project with GetLastCachedZIndex bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5994616/c3.project.with.GetLastCachedZIndex.bug.zip)

## Steps to reproduce

1. Start a preview in "Menu 1" layout
2. Click on "Move to" button
3. Then, after you moved to the layout "Menu 2", press "Come back" button, then error must appear in console, and the game stops to work properly

## Observed result

 I get error in C3 source code and game stops to work properly

## Expected result

It must just go back and forth between two layouts!

## More details

Im almost sure the problem is in global layers. Because im using Construct 3 for more than a year already, and i've never seen this error, and also i didn't use global layers ever before.

Moving between layouts is simple "Go to layout" action

![image](https://user-images.githubusercontent.com/55310192/108185309-36a97e80-711d-11eb-813a-972644291dab.png)

**Affected browsers/platforms:** 

It happens on stable version 234.4. Didn't check it on any other versions. Didn't encounter this error ever before.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.150
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
C3 release: r234.4 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 77 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 1030 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by nerdError** [comment]
UPDATE

I fiddled with project more, and the problem is in "Use render cells" layer option. Im not sure, is it related to global layers or not, but at least if I disable this option for all layers in the project, i never get this error again.

**Comment by AshleyScirra** [comment]
Minimal repro: [issue4575.zip](https://github.com/Scirra/Construct-3-bugs/files/5997897/issue4575.zip)

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.

FYI there's really no point using render cells in this kind of project, it's nowhere near big enough. It's designed for use on huge scrolling layouts with thousands of non-moving objects scattered all across. The [manual entry](https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/layers) advises:

> Optimise the rendering of this layer for extremely large layouts with a large number of static objects spread out across this layer. This is not normally necessary except for certain types of large game. If this is used incorrectly, it can actually make rendering less efficient, so make sure you can measure a performance improvement before using it.
