### ISSUE TITLE
Project won't export with minify selected when audio plugin is used.  Only release r236 Beta

### ISSUE THREAD

**Issue by MathNook1** [Scirra/Construct-3-bugs#4576]
## Problem description

When exporting a project using Minify simple, the export fails with the following message:

Minifying this export failed.  Check the browser console (press F12) for error details.  This is usually caused by the JavaScript code in your project, or a third-party addon.

## Attach a .c3p

zip file containing c3p file attached.
[minify fails beta r236.zip](https://github.com/Scirra/Construct-3-bugs/files/5996451/minify.fails.beta.r236.zip)

## Steps to reproduce

1. Create new project.
2.  Add Audio object to layout
3.  Export for web (HTML5) and choose Minify simple.

## Observed result

Export fails complaining about the JavaScript .  Message shown:

Minifying this export failed.  Check the browser console (press F12) for error details.  This is usually caused by the JavaScript code in your project, or a third-party addon.

## Expected result

Expected export to run successfully

## More details

Tested with Chrome only.

Only see this with r236 Beta.

## System details

Windows 10

[minify fails beta r236.zip](https://github.com/Scirra/Construct-3-bugs/files/5996488/minify.fails.beta.r236.zip)

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.

**Comment by MathNook1** [comment]
Great, thanks!
