### ISSUE TITLE
Can't use hierarchy select mode when object has a parent.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#4579]
## Problem description

I'm trying to use hierarchy like a bone system and use the timeline with it to make character animations. The problem is, I have an arm with two parts, the upper arm is the parent of the lower arm and the body is the parent of the upper arm. I need to use wrapped selection and select the whole arm but since it has a parent, it won't let me use hierarchy selection options.

You can see the issue below:
https://user-images.githubusercontent.com/2965842/108259787-9716db00-7172-11eb-9320-7ae29fd701cd.mp4

I think we could use timeline + scene graph to make modular animations like in Spriter if this issue is fixed.

## Steps to reproduce

1. Create 3 objects. Make the second object parent of the first one.
2. Make the third object parent of the second one.
3. Try to use hierarchy selection and select the second object with its child.

## Observed result

You can't select the second object with its child because the second object has a parent.

## Expected result
We should able to use selection options for all parent objects, not just the highest ones.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
