### ISSUE TITLE
Google drive occasionally showing blank file list

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#458]
## Problem description

Google drive often shows the file list to be empty immediately after authenticating. I've debugged this and it's a bug in the Google Drive API. A bug report is filed [here](https://issuetracker.google.com/issues/62402730).

## Workaround

Refresh the dialog to see all files, or use a different cloud service.

## Attach a .c3p

N/A

## Steps to reproduce

1. Select Menu > Project > Open > Cloud Open
2. Select Google Drive from dropdown
3. See blank filelist
4. Refresh dialog
5. See actual filelist

## Observed result

No files...

## Expected result

Files!

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
C3 release: r35

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 197 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by TheRealDannyyy** [comment]
Thanks for reporting this bug to Google, starred and hoping for a quick response from their end.

**Comment by shortercode** [comment]
@TheRealDannyyy have you experienced this recently? I don't seem to get it anymore. The response from google was pretty rubbish, they ignored it for over a month then closed it as a duplicate of a bug which I'm not sure is actually related (with no feedback on either). The other bug is still open...

**Comment by TheRealDannyyy** [comment]
Nope doesn't seem to happen to me anymore but I noticed that it takes quite some time now in order to load stuff. I'd still take 5sec. more loading time over not loading at all though. Thanks a lot for the fix.

**Comment by shortercode** [comment]
I guess we can consider this closed then!

Shame it's so slow for yours to load... I had been considering some kind of caching for the folder feature. So that it doesn't have to load after each folder change. I guess if I made it use the cache more often than I was planning it could make it faster. It would only have to get the file list from G Drive the first time you loaded the file dialog that session and each time the "refresh" button was pressed. It could cause some de-sync issues if G Drive is being updated by something other than the editor, but nothing major. Mostly user confusion, and we can always make it configurable.
