### ISSUE TITLE
 The value of Online and Offline does not change if the Internet is turned on or off when the application is running.

### ISSUE THREAD

**Issue by ConstructBugsReport** [Scirra/Construct-3-bugs#4581]
**Problem: If the application is launched with the Internet enabled, but the Internet is disabled during operation, the system does not commit these changes.**

_For example: You want to show ads if the Internet is enabled, but the player turns off the Internet after starting the game.
But the system records only the initial value. In the past, turning on or off immediately fixed and worked._

**Plugin: Browser**

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise, as they state, your report will not be investigated.

Please note this feature is also provided by the browser so updating how online/offline is detected is beyond our control.
