### ISSUE TITLE
Intermittent crash when switching to another layout at Multiplayer.

### ISSUE THREAD

**Issue by Filigrani** [Scirra/Construct-3-bugs#4587]
## Problem description

Sometimes, if change layout of host, and send event to change layout for peers, after layout loaded on peer side may happend crash, JS log here:
https://cdn.discordapp.com/attachments/412510504766930944/812278164742995968/unknown.png
(screenshot made on construct 3 r234.4 stable, chrome).
## Attach a .c3p
Can pm my c3p file, or share it at my google drive for your email only, just give me your email.

## Steps to reproduce

If using my c3p, start game from Menu layout, press Play, Together, then +  button to host, select any level.
On peer side,  Menu layout, press Play, Together, then press on server room from the list.
After both connected, press R on both sides. Game will be started and transfer you to other layout, but on peer side exist chance that this crash will happend.

## Observed result

Peer player can't move, cause runtime of c3 dies, but synced props still syncs from the host, but any peer side events are dead.
Constantly repeating error at console, that I has sent above.

## Expected result

After layout change all must works normal, because in 50% cases it works.

## More details
When my game was on Construct 2, it had same crash problem.

**Affected browsers/platforms:** 

Chrome and NwJs on both seen problem not matter who host is.

**First affected release:** 

## System details

<details><summary>View details</summary>

Construct 3 r234.4 stable. But problem has been present in any past version of c3 and last c2 version.

</details>

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines: we need a minimal demonstration project rather than your full project. The guidelines has advice on how to prepare that from a full project.
