### ISSUE TITLE
Collision points don't snap to 1px grid 

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4588]
## Problem description

When editing a sprite, the 'snap to grid' function returns decimal-point coordinates when adjusting the collision polygon anchor points.

## Attach a .c3p

(Any c3 project will do)

## Steps to reproduce

1. Open a sprite in the Animation editor
2. Set the grid to 1x1, enable Snap
3. Adjust the collision polygon handles

## Observed result

The collision handles can have float X/Y values (i.e. 1.20) 

## Expected result

The collision handles should snap to the grid X/Y values (i.e. 1)

## More details

**Affected browsers/platforms:** Chrome 88

**First affected release:** r236 Beta

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
