### ISSUE TITLE
Ajax Request not working

### ISSUE THREAD

**Issue by sizcoz** [Scirra/Construct-3-bugs#459]
## Problem description
Ajax request working in C2, but after importing into C3 it does not work anymore.

## Attach a .c3p

[Bug_report.zip](https://github.com/Scirra/Construct-3-bugs/files/1057860/Bug_report.zip)

## Steps to reproduce

1. open the file in c2 it works
2. open the file in c3 it does not work

## Observed result

Ajax.lastdata not showing after request

## Expected result

It to work.

## Affected browsers

Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Works fine for me. Try clearing your browser cache and re-trying. Please also provide all the information we ask for, since it helps diagnose issues. Also please see the bug report guidelines regarding providing minimal projects.
