### ISSUE TITLE
Tween: Set end value is not as accurate as a lerp on moving targets

### ISSUE THREAD

**Issue by vascco47** [Scirra/Construct-3-bugs#4590]
## Problem description

Using Tween: set end value, while target object is moving, results in a small offset, which increases with increasing object speed, while lerp function positions the object precisely. The tween and lerp codes have the same algorithms.

## Attach a .c3p

[TweenJumpSetEndValueC3.zip](https://github.com/Scirra/Construct-3-bugs/files/6017303/TweenJumpSetEndValueC3.zip)

## Steps to reproduce

1. Open c3p file and run
2. On left screen side are a jumper and target with Tween code, while on right is a jumper and target with Lerp code
3. Tap anywhere on the screen for objects movement (jump)

## Observed result

Jumper with tween code lands on target with a small offset which increases with target speed, while lerp jumper has no offset.

## Expected result

Tween jumper should land exactly on the target at any target speed, with Tween: Set end value during jump.

## More details

Tested on Chrome on Windows and Safari on iPhone 11

**Affected browsers/platforms:** 
Chrome, Safari

r236 beta

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Browser: Chrome
Browser version: 88.0.4324.182
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
C3 release: r236 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 235 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment]
I still need to investigate this one a little bit further, I suspect it has to do with the order in which behaviour's update.

In this example I think what is going on is that the value tweens finish and set the last known value for the target position correctly, but  immediately afterwards, in the same tick, the sine behaviour changes the position of the target so it ends up with that slight offset.

If you manually set the end position of the Jumper instance to the position of the target on the tween's finished trigger (in the same action block **Add Child** is used), then the Jumper ends up in the correct spot.

**Comment by vascco47** [comment]
Hmm, yes, with a set object position to the target position in the last tick, as you said, can solve the situation, at least until the bug is fixed. Thanks for the tip.

**Comment by DiegoScirra** [comment]
I have been looking at this more closely and unfortunately what is happening is exactly what I explained before. This means it isn't possible to fix the issue. It is an edge case that is tightly related to how C3's runtime works. Attempting to fix this will only result in new, different problems.

I know it is not very elegant. but for this particular case (and other similar ones) you will need to rely on explicitly forcing the ending position when the tween finishes.
