### ISSUE TITLE
Android Signed Release Build Fails

### ISSUE THREAD

**Issue by the-socialnetwork** [Scirra/Construct-3-bugs#4591]
When building "Signed Release" for Android, the build fails with the error message below. Doesn't matter if compressions is off, or at simple. It fails over multiple fails, multiple browsers and a few people have the same error trying to build, even with different keystores. Exporting "Debug APK" works fine. Tried multiple versions of android like Nuggat 7.0.0 for example, still same error. Tried earlier r233 version of construct, still same error.

It fails with any project file, even construct, in multiple browsers, multiple people tried it and have same error.

## Steps to reproduce

1. Create a new project.
2. Export android game with Signed Release Apk.

## Observed result

The build fails with a Log which can be found under **System Details**.

## Expected result

The build should succeed, I exported my game yesterday multiple times just fine, nothing but the project description was changed since then, but now it fails.

## More details

**Affected browsers/platforms:** 

Chrome latest, Opera latest.

Tested on r233, r234.4. Worked on r234.4, but now it also fails on r234.4.

## System details

<details><summary>View details</summary>

Windows OS.

LOG:
`Error: Discovered platform "android@9.0.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@9.0.0

Error: Failed to fetch platform cordova-android@9.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform ~~/URL.
Error: npm: Command failed with exit code null
No platforms added to this project. Please use `cordova platform add <platform>`.`

**A few times I also got this error:**
`Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=~~/androidSDK (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
Using Android SDK: ~~/androidSDK
:wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
Starting a Gradle Daemon, 74 busy and 1 incompatible and 13 stopped Daemons could not be reused, use --status for details
> Task :app:preBuild UP-TO-DATE
> Task :app:preReleaseBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preReleaseBuild UP-TO-DATE
> Task :CordovaLib:compileReleaseAidl NO-SOURCE
> Task :app:compileReleaseAidl NO-SOURCE
> Task :CordovaLib:packageReleaseRenderscript NO-SOURCE
> Task :app:compileReleaseRenderscript NO-SOURCE
> Task :app:generateReleaseBuildConfig
> Task :app:javaPreCompileRelease
> Task :app:generateReleaseResValues
> Task :app:generateReleaseResources
> Task :CordovaLib:compileReleaseRenderscript
> Task :CordovaLib:generateReleaseResValues
> Task :CordovaLib:generateReleaseResources
> Task :CordovaLib:packageReleaseResources
> Task :app:createReleaseCompatibleScreenManifests
> Task :app:extractDeepLinksRelease
> Task :CordovaLib:extractDeepLinksRelease
> Task :app:mergeReleaseResources
> Task :CordovaLib:processReleaseManifest
> Task :app:processReleaseManifest
> Task :CordovaLib:compileReleaseLibraryResources
> Task :CordovaLib:generateReleaseBuildConfig
> Task :CordovaLib:javaPreCompileRelease
> Task :app:prepareLintJar
> Task :CordovaLib:prepareLintJarForPublish
> Task :CordovaLib:parseReleaseLocalResources
> Task :app:checkReleaseDuplicateClasses
> Task :CordovaLib:generateReleaseRFile
> Task :app:processReleaseResources
> Task :CordovaLib:compileReleaseJavaWithJavac
> Task :CordovaLib:bundleLibRuntimeToJarRelease
> Task :CordovaLib:bundleLibCompileToJarRelease

> Task :app:compileReleaseJavaWithJavac

> Task :app:compileReleaseSources

> Task :app:lintVitalRelease

> Task :app:dexBuilderRelease
> Task :app:desugarReleaseFileDependencies
> Task :app:mergeReleaseShaders
> Task :app:compileReleaseShaders NO-SOURCE
> Task :app:generateReleaseAssets UP-TO-DATE
> Task :CordovaLib:mergeReleaseShaders
> Task :CordovaLib:compileReleaseShaders NO-SOURCE
> Task :CordovaLib:generateReleaseAssets UP-TO-DATE
> Task :CordovaLib:packageReleaseAssets
> Task :app:mergeReleaseAssets
> Task :app:processReleaseJavaRes NO-SOURCE
> Task :CordovaLib:processReleaseJavaRes NO-SOURCE
> Task :CordovaLib:bundleLibResRelease NO-SOURCE
> Task :app:mergeReleaseJavaResource
> Task :app:collectReleaseDependencies
> Task :app:sdkReleaseDependencyData
> Task :app:mergeReleaseJniLibFolders
> Task :CordovaLib:mergeReleaseJniLibFolders
> Task :CordovaLib:mergeReleaseNativeLibs
> Task :CordovaLib:stripReleaseDebugSymbols NO-SOURCE
> Task :CordovaLib:copyReleaseJniLibsProjectOnly
> Task :app:mergeExtDexRelease
> Task :app:mergeReleaseNativeLibs
> Task :app:stripReleaseDebugSymbols NO-SOURCE
> Task :app:mergeDexRelease

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: ~~/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
~~/screen.png: Error: The drawable "screen" in drawable-land-xxxhdpi has no declaration in the base drawable folder or in a drawable-densitydpi folder; this can lead to crashes when the drawable is queried in a configuration that does not match this qualifier [MissingDefaultResource]
~~/screen.png: Error: The drawable "screen" in drawable-port-xxxhdpi has no declaration in the base drawable folder or in a drawable-densitydpi folder; this can lead to crashes when the drawable is queried in a configuration that does not match this qualifier [MissingDefaultResource]

Explanation for issues of type "MissingDefaultResource":
If a resource is only defined in folders with qualifiers like -land or -en,
and there is no default declaration in the base folder (layout or values
etc), then the app will crash if that resource is accessed on a device
where the device is in a configuration missing the given qualifier.

As a special case, drawables do not have to be specified in the base
folder; if there is a match in a density folder (such as drawable-mdpi)
that image will be used and scaled. Note however that if you only specify
a drawable in a folder like drawable-en-hdpi, the app will crash in
non-English locales.

There may be scenarios where you have a resource, such as a -fr drawable,
which is only referenced from some other resource with the same qualifiers
(such as a -fr style), which itself has safe fallbacks. However, this still
makes it possible for somebody to accidentally reference the drawable and
crash, so it is safer to create a default dummy fallback in the base
folder. Alternatively, you can suppress the issue by adding
tools:ignore="MissingDefaultResource" on the element.

(This scenario frequently happens with string translations, where you might
delete code and the corresponding resources, but forget to delete a
translation. There is a dedicated issue id for that scenario, with the id
ExtraTranslation.)

2 errors, 0 warnings
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=28a10ee6-57de-4b84-86f8-860e8e5fa884, currentDir=~~/c7e05b07-2e0d-458a-aa77-50a8c21b5b03}
Attempting to read last messages from the daemon log...
Daemon pid: 29075
log file: ~~/daemon-29075.out.log
----- Last 20 lines from daemon log file - daemon-29075.out.log -----
As a special case, drawables do not have to be specified in the base
folder; if there is a match in a density folder (such as drawable-mdpi)
that image will be used and scaled. Note however that if you only specify
a drawable in a folder like drawable-en-hdpi, the app will crash in
non-English locales.

There may be scenarios where you have a resource, such as a -fr drawable,
which is only referenced from some other resource with the same qualifiers
(such as a -fr style), which itself has safe fallbacks. However, this still
makes it possible for somebody to accidentally reference the drawable and
crash, so it is safer to create a default dummy fallback in the base
folder. Alternatively, you can suppress the issue by adding
tools:ignore="MissingDefaultResource" on the element.

(This scenario frequently happens with string translations, where you might
delete code and the corresponding resources, but forget to delete a
translation. There is a dedicated issue id for that scenario, with the id
ExtraTranslation.)

2 errors, 0 warnings
----- End of the daemon log -----

FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org
Command failed with exit code 1: ~~/gradlew cdvBuildRelease -b ~~/build.gradle`
</details>

**Comment by renanmoura12** [comment]
I'm having the same problem, in all types of build

**Comment by ReviveR200** [comment]
Error: Discovered platform "android@9.0.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@9.0.0

Error: Failed to fetch platform cordova-android@9.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform ~~/URL.
Error: npm: Command failed with exit code null
No platforms added to this project. Please use `cordova platform add <platform>`.

**Comment by ibiz3091** [comment]
I get the same error in debug apk and signed apk:
Error: Discovered platform "android@9.0.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@9.0.0

Error: Failed to fetch platform cordova-android@9.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform ~~/URL.
Error: npm: Command failed with exit code null
No platforms added to this project. Please use `cordova platform add <platform>`.

**Comment by Vortex00** [comment]
Same issue. tried Debug APK and Android Studio Project.

**Comment by xama300chl** [comment]
in addition to the error of not being able to generate a biuld and export the game, the command when touching any object and others from the shet event are buggy

**Comment by renanmoura12** [comment]
hey guys, now it seems to be back to normal, check it out!

**Comment by the-socialnetwork** [comment]
Yes, seems to be in working condition again
