### ISSUE TITLE
Editor crashed while saving and corrupted project file

### ISSUE THREAD

**Issue by ThisIsNoZaku** [Scirra/Construct-3-bugs#4597]
## Problem description

While trying to save the project, the editor crashed. Additionally, trying to save the project after the error rendered it unusable.

[project.zip](https://github.com/Scirra/Construct-3-bugs/files/6024850/project.zip) (contains corrupted c3p file)

## Steps to reproduce

Added a JSON object to the project then attempted to save.

## Observed result

The editor crashed.

## Expected result

I expected the editor to save successfully.

## System details

Error report information
Type: assertion failure
Message: cannot find 'JSON' object class index
Stack: Error at Function.d.QVa (https://editor.construct.net/r234-4/main.js:287:41) at window.assert (https://editor.construct.net/r234-4/main.js:201:149) at t.uN (https://editor.construct.net/r234-4/projectResources.js:2442:425) at p.$b (https://editor.construct.net/r234-4/projectResources.js:216:497) at https://editor.construct.net/r234-4/projectResources.js:597:3 at Array.map () at r.$b (https://editor.construct.net/r234-4/projectResources.js:596:495) at Object.Lfa (https://editor.construct.net/r234-4/projectResources.js:1035:485) at p (https://editor.construct.net/r234-4/main.js:437:435) at k (https://editor.construct.net/r234-4/main.js:437:224)
Construct 3 version: r234.4
URL: https://editor.construct.net/
Date: Mon Feb 22 2021 14:51:47 GMT-0500 (Eastern Standard Time)
Uptime: 5951.5 s

Platform information
Browser: Chrome
Browser version: 88.0.4324.150
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
C3 release: r234.4 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment]
I can see the project is corrupted, but it's impossible to fix unless you can identify the steps that caused the project to be corrupted in the first place. Can you provide there?

**Comment by ThisIsNoZaku** [comment]
I remember adding a JSON object to the project and was editing it. I tried to save as I hadn't saved in a while which triggered the crash. In the crash dialog I clicked save to try and keep my progress, which ruined the project file.

**Comment by AshleyScirra** [comment]
Well, I opened Ghost Shooter, added the JSON object, and saved the project, and it opened just fine. As explained in the bug report guidelines, I'm afraid there's nothing we can do without steps to reproduce the problem. Please do let us know if you can identify these, since project corruption issues are a high priority to fix, but without more details it's impossible to tell what happened.
