### ISSUE TITLE
Android Adaptive Icons are being overwritten by iOS App Icons

### ISSUE THREAD

**Issue by natebluewizard** [Scirra/Construct-3-bugs#4598]
## Problem description

When building android apps, the defined Adaptive Foreground and Adaptive Background images added to the "Files" Folder are not being respected and are instead being overwritten by iOS defined AppIcon icons.

## Attach a .c3p

https://www.bluewizard.com/nate/TestIcons.c3p

## Steps to reproduce

1. Download the attached project & build for Android devices
2. Look at the app icon of the installed test app.

## Observed result

You will see the icon has a red X, which means its not using the adaptive icons set.

## Expected result

When using the Adaptive Foreground and Background on Android, they should take priority, as icons required for iOS must be set to AppIcon, which will override the android icons to use an iOS icon instead.

## More details

I also found that NOT ALL AppIcons in the Files folder will override. If I set the "Test.png" in the bug report project to be 40x40 pixels, the Adaptive FG/BG will begin to be used again. I did MANY builds testing various sizes and it seems random at this point but for sure if I have 150x150, 180x180, 167x167 and potentially a couple others, it will result in ignoring the Adaptive FG/BG. If i remove those sizes, but have other sizes like 40x40, 60x60, 1024x1024, 256x256, the Adaptive FG/BG works fine.

I also found that the filename seems to make no difference. Naming a 'bad' size (150x150) to anything will still result in that icon being used. Same if I simple kept the name test.png but changed the size to 40x40, suddenly the FG/BG will work again.

**Affected browsers/platforms:** 

Android 

**First affected release:** 

I have never had Adaptive Icons work for the duration of working on this project, so say since about October last year. I recently started trying to figure out why, and this is the result of that research.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.67
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 1.1 gb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro Vega 20 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I did a debug APK build of the project, installed the APK on a Pixel 3, and it correctly showed the adaptive icon in the app list on the device. So it seems to be working fine for me. Some locations (such as the APK file in the downloads folder, and the App Info screen) used the other icon with the red X. I believe Construct/Cordova is correctly configuring the icons, but it's up to the system/launcher which icon it chooses to display from the available set. I think the specific rules about which icons are chosen depends on the device and the launcher app, and I guess the preferred icon could vary depending on the specific sizes and types available. So I don't think there's any issue with Construct here, it's just up to the system which icon it picks from the available set provided by the app.

**Comment by natebluewizard** [comment]
Damn well that's frustrating. Would be nice to at least be able to differentiate IOS icons from Android icons. Unfortunately iOS requires 'no transparency / full bleed' since the do the masking on the OS level, but android, if it uses the App Icon, will display it exactly as the image is, so basically an ugly sharp cornered square. If i could at least have icons defined for iOS and icons defined for android, or ensure that iOS tagged icons are ignored for android, that would be a massive help. For now im just literally manually deleting icons before i build depending on what platform im building. 

Thanks for checking it.

**Comment by natebluewizard** [comment]
@AshleyScirra 

Damn well that's frustrating. Thanks for checking it. 

Would be nice to be able to differentiate IOS icons from Android icons. Unfortunately iOS requires 'no transparency / full bleed' since they do the masking on the OS level, but android, if it uses the App Icon, will display it exactly as the image is, so basically an ugly sharp cornered square. 

If we could have icons defined for iOS and icons defined for android, or ensure that iOS tagged icons are ignored for android, that would be a massive help. For now im just literally manually deleting icons before i build depending on what platform im building. 

Thanks again for checking it.

**Comment by AshleyScirra** [comment]
You should be able to change the app icon's purpose to "(none set)" and export, and it won't use it for that export. Then you can put it back.

**Comment by natebluewizard** [comment]
@AshleyScirra 

Ah, ok, in that case its easier to just delete (and not save) before building since i can only change the file type one file at a time but i can delete everything at once.
