### ISSUE TITLE
Or Block Visual Indicator Inconsistency

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#46]
## Problem description

There is inconsistency in the design of the "Or" block for different types of event conditions.

## Steps to reproduce

A 1. Create a trigger event condition and another non-trigger event.
A 2. Make the events an "Or" block.

B 1. Create 2 non-trigger conditions event.
B 2. Make the events an "Or" block.

## Observed result

A: Results in both conditions indicating an "Or" label.
B: Only the second condition indicating an "Or" label.

## Expected result
**My suggestions**
Initial solution: The first trigger condition should not have the "Or" label.

Better solution: The "Or" label appearing under the trigger condition's green arrow icon or on the left of an event block where the green arrow icon is. Removing the need to add the "Or" label beside every single condition. Additionally, you could replace text "Or" with a "+" symbol if elegance/ space is important.

Alternative solution: Do it like C2's way of separating conditions with "Or" labels.

**Comment by IJCT95** [comment]
same, i think it looks really odd and it should return to the way C2 handled it.

**Comment by Kyatric** [comment]
I must admit I was preferring C2's way as well, it made more sense. 
Although, the current way makes it clear and nice to see if an event is set to be a "Or" block even if it contains a single condition.
Possibly a "best of 2 worlds" would be the extra label like in Construct 2 between every conditions, and have it displaying even if there is a single condition in the event.

**Comment by AshleyScirra** [comment]
I've fixed r18 to consistently only label conditions from the 2nd condition and below. Changing the style completely is more of a feature request, and the main reason it's like that in C3 is because it's a bit more compact and easy to do in CSS. (The C2 style is pretty hard to pull off in CSS alone and DOM changes can be complicated and have performance impact.) So closing this as fixed for now.
