### ISSUE TITLE
BB code formatting wrong on construct.net

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#460]
See: https://www.construct.net/gb/make-games/releases/beta/r36

The italics and bold formatting loses the spaces around the text.

**Comment by TomGullen** [comment]
Fixed for next upload.

**Comment by AshleyScirra** [comment]
Has this upload happened yet? There's still bad BBcode formatting on release notes, e.g.: https://www.construct.net/gb/make-games/releases/beta/r47

Re-opening issue until Tom takes another look.
