### ISSUE TITLE
Whitelist Plugins for Firebase Authentication

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#4600]
Hi, can you add these plugins:

```
cordova-plugin-buildinfo@4.0.0
cordova-plugin-universal-links@0.3.0
cordova-plugin-browsertab@0.2.0
cordova-plugin-customurlscheme@5.0.2
```

These plugins are required for **Firebase oAuth services** with Cordova.
These above plugins will allow features such as multiple Auth Provider management, multiple Firebase Project management and some other features and user properties which are not available in the already included `cordova-plugin-firebase-authentication` plugin.

![image](https://user-images.githubusercontent.com/42723600/108843719-17b95980-7601-11eb-993b-89b8f4a7f399.png)

**Comment by SparshaDhar** [comment]
Okay I just remembered that it also requires some changes in the **config.xml** before building. Is it possible to make changes in the config.xml using Construct 3 plugins?
![image](https://user-images.githubusercontent.com/42723600/108846299-6d433580-7604-11eb-942f-877ce4222915.png)

**Comment by EMI-INDO** [comment]
**Specify the @xx plugin version**


![Screenshot_10](https://user-images.githubusercontent.com/78555833/108851145-b2706300-7616-11eb-8e44-c155479a66f5.png)

**Comment by AshleyScirra** [comment]
We don't currently support arbitrary changes to config.xml. You can only make changes by editing the plugin's XML file as per the design of Cordova.

Since this seems to be a prerequisite for these plugins to work, I don't think it makes sense to do the security review on these plugins at this time. If you want this to be supported perhaps start with a feature request for the necessary config.xml changes.

**Comment by SparshaDhar** [comment]
> If you want this to be supported perhaps start with a feature request for the necessary config.xml changes.
@AshleyScirra , Thanks. However in the config.xml, the host `name `and `url` differs for different Firebase users. I guess 
 attribute changes depending upon each user to config.xml is not possible?

**Comment by AshleyScirra** [comment]
It's possible, but we'd need to implement a specific mechanism to route plugin properties to certain config.xml tags. It's complicated and I don't want to have to end up coding all sorts of similar mechanisms for different plugins that need different settings. It would be easier to find a way to get it working without having to do that if you can.
