### ISSUE TITLE
Timeline guides not visible on global layers

### ISSUE THREAD

**Issue by easyDoesItOK** [Scirra/Construct-3-bugs#4604]
## Problem description

If a objects is placed on a global layer and added to a timeline. The guides are only visible on the original layout, not on all other layouts. So it is not easy to edit a timeline on anything but the original layout.

## Attach a .c3p
[bugTimelineGuide.zip](https://github.com/Scirra/Construct-3-bugs/files/6031768/bugTimelineGuide.zip)

## Steps to reproduce

1. create layer and make global
2. add timeline to project
3. create new timeline
4. create new object, add object to timeline
5. on original layout of layer, with the timeline edit (pen) on when you move the object a guide elastic line is drawn between the previous position of the object and the new object.
6. Now change to another layout, and move the object in this timeline.

## Observed result

The elastic guide line is no longer visible on other layouts. This makes it hard to edit the timeline if you want to do it on another layout with a global layer.

## Expected result

Timeline guides (boxes and elastic lines) should appear on all layouts with the global layer.

## More details

Brave

r234.4

## System details

No crash

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
