### ISSUE TITLE
Android export has visual jittering but is smooth on mobile browser on same device.

### ISSUE THREAD

**Issue by zakkaplay** [Scirra/Construct-3-bugs#4606]
Did a debug apk export & also html5 web export.
It's a very simple project, and both showed 60 fps on my device, but it has bad visual jittering in the android apk, but is smooth in the mobile browser. 
Please have a look at the issue, as Android is my target platform for why I bought the construct 3 licence.

**Test Devices** : 
1. Huawei Honor Note 10
2. Samsung Galaxy Note 5

**Html5 Web** : https://zakkaplay.com/test/ptest/
**APK** : https://drive.google.com/file/d/1jkIivRwAUxDJLp3WtkPsBvZWGNlPwMgW/view?usp=sharing
**Project File** : https://drive.google.com/file/d/1sUz8NR6M33ZsP0JjW90bYMPu5LoRHAqK/view?usp=sharing

Thank you.

**Comment by AshleyScirra** [comment]
This appears to be a re-post of this forum thread, where I already replied: https://www.construct.net/en/forum/construct-3/general-discussion-7/android-vs-web-performance-158738

As I said there, I could not reproduce the problem on a Pixel 3, and device-specific issues are best dealt with by reporting to Google at crbug.com.
