### ISSUE TITLE
Cordova Build Server- a plugin showing error

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#4609]
I tried using this `cordova-plugin-firebase-authentication` using Android Cordova Export Build Server.

But this plugin is giving this error:

<details open>
<summary><b>Build Server Cordova Error</b></summary>

```
Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=~~/androidSDK (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
Using Android SDK: ~~/androidSDK
:wrapper

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
Adding classpath: com.google.gms:google-services:4.3.3


FAILURE: Build failed with an exception.

* Where:
Build file '~~/build.gradle' line: 420

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.google.gms.google-services']
> Cannot add extension with name 'googleServices', as there is an extension already registered with that name.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 5s
Command failed with exit code 1: ~~/gradlew cdvBuildDebug -b ~~/build.gradle
```

</details>

<br><br><br>

So I tried installing using Powershell on my own computer. It installs finely without errors.
However I found that on running the single command `cordova plugin add cordova-plugin-firebase-authentication@4.0.1`,
a total of three plugins get installed. Result:
```
Installing "cordova-plugin-firebase-authentication" for android
Installing "cordova-support-android-plugin" for android
Installing "cordova-support-google-services" for android
```
![image](https://user-images.githubusercontent.com/42723600/109121409-350b3680-776d-11eb-806b-55a0503db2a3.png)

I am not sure but this might be conflicting with C3's Cordova Build Server?

**Comment by AshleyScirra** [comment]
We added the Cordova plugin at the request of a third-party developer. I'm afraid we cannot provide support for it.
