### ISSUE TITLE
C3 crashes when I try to export in the free version.

### ISSUE THREAD

**Issue by yojona** [Scirra/Construct-3-bugs#461]
## Problem description

editor crashes when I try to export in the free version.

## Attach a .c3p

*It happens in any project in chrome for mac*

## Steps to reproduce

1. New project
2. Export to android/ios

## Observed result

"Oops! Something went wrong"
## Expected result

only "This feature is not available in the free version" dialog

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot set property 'tag' of null @ TypeError: Cannot set property 'tag' of null at g.ǃwt.then.then.then (https://editor.construct.net/r36/main.js:71:11082) at 
Stack: TypeError: Cannot set property 'tag' of null at g.ǃwt.then.then.then (https://editor.construct.net/r36/main.js:71:11082) at 
Construct 3 version: r36
URL: https://editor.construct.net/
Date: Wed Jun 07 2017 08:06:39 GMT-0700 (MST)
Uptime: 53.1 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r37.
