### ISSUE TITLE
Crash After Trying to Drag Highlighted Text in JSON File

### ISSUE THREAD

**Issue by Rhindon** [Scirra/Construct-3-bugs#4611]
## Problem description
C3 crashes when clicking elsewhere after highlighting + dragging text in a JSON file.

## Attach a .c3p
[Mr Spy Micro-Missions JSON Crash.zip](https://github.com/Scirra/Construct-3-bugs/files/6042734/Mr.Spy.Micro-Missions.JSON.Crash.zip)
The C3 project file is included with this bug report is presented "as is" (but it is still very small with a single event sheet, objects, and two simple layouts). **The issue as far as I have been able to determine is isolated exclusively to the "GuardNamesList.json file under the Files folder. The rest of the project can be ignored.**

I have left the rest of the project intact only because I have absolutely no idea (however remote) if there is anything else in the project that could lend to this problem. If I remove something (or everything else) and you cannot reproduce the problem, I would not know what to keep and what to remove. I did not encounter this problem until I started working on the JSON file, however.

## Steps to reproduce

1. Create a new JSON array file. Either an array or dictionary file.  (All others - from "plain text" to "stylesheet" - do not seem to be related to this problem.)
2. In a text cell, type any characters and highlight the characters (any or all).
3. While the text is highlighted, attempt to drag the text at all and release it. (It's not necessary that the highlighted + dragged text reach any destination.)
4. After releasing the mouse button, click anywhere (you might need to click a second time - I have not been able to isolate what causes the crash after one click while other times after two clicks).
5. After clicking, C3 will crash.

## Observed result

C3 completely crashes, prompting the usual options to save the file, copy the report, etc.

## Expected result

The expected result was for the highlighted text to simply become de-selected and possibly the cell, itself, where the text resides to be deselected, as well. And/or for the different cell where the click occurs to become newly selected, ready for new text.

## More details

This seems to happen exclusively after dragging the highlighted text from within a given cell in the array/dictionary JSON files. I attempted to recreate the problem by highlighting + dragging text in (for example: global variable edit windows or event line edit windows) and the problem did not occur. In still other text fields (for example: in the properties window) I could highlight text but could not drag it at all.

**Affected browsers/platforms:** 
- Chrome Version 88.0.4324.182 (Official Build) (64-bit)
- Chrome Version 88.0.4324.190 (Official Build) (64-bit) (a new version was presented as available when I went to check what the then-current version was. I tested again with the newer version and the problem persists)

**First affected release:** 
- r237 beta

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r237/components/editors/dataEditor/dataEditor.js, line 65, col 98
Message: Uncaught TypeError: Cannot read property 'xh' of null
Stack: TypeError: Cannot read property 'xh' of null at Object.Qia (https://editor.construct.net/r237/components/editors/dataEditor/dataEditor.js:65:98) at Object.RTc (https://editor.construct.net/r237/components/editors/dataEditor/dataEditor.js:63:151) at Array. (https://editor.construct.net/r237/components/editors/dataEditor/dataEditor.js:63:10) at d.Event.bOc.Rbd (https://editor.construct.net/r237/main.js:429:387) at d.KAc.dispatchEvent (https://editor.construct.net/r237/main.js:425:135) at Object.Nl (https://editor.construct.net/r237/components/editors/dataEditor/dataEditor.js:55:378) at Object.vmb (https://editor.construct.net/r237/components/editors/dataEditor/dataEditor.js:87:174) at HTMLDivElement. (https://editor.construct.net/r237/components/editors/dataEditor/dataEditor.js:83:231)
Construct 3 version: r237
URL: https://editor.construct.net/r237/
Date: Thu Feb 25 2021 03:39:23 GMT-0800 (Pacific Standard Time)
Uptime: 28604 s

Platform information
Browser: Chrome
Browser version: 88.0.4324.182
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
C3 release: r237 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
I can reproduce - assigning to @DiegoScirra, I think this might be related to recent pointer event changes.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.

The default browser behaviour of dragging an element is now disabled when editing a cell in the data editor. It wasn't used for anything.
