### ISSUE TITLE
Cordova Build Server- Whitelist a plugin

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#4613]
Hi, please include this plugin:

**c3-firebase-auth-forked@2.0.0**

<br>

I created this _fork_ for support on Construct 3 from the original [_cordova-plugin-firebase-authentication_](https://www.npmjs.com/package/cordova-plugin-firebase-authentication) plugin which was failing earlier: **Issue #4609**

Thankyou

**Comment by AshleyScirra** [comment]
Updated allowlist on build service.

**Comment by SparshaDhar** [comment]
Thank you so much ❤
