### ISSUE TITLE
Image Point Coordinate Field Entries Changing Incorrectly With NUM PAD

### ISSUE THREAD

**Issue by Willow65806** [Scirra/Construct-3-bugs#4615]
## Problem description

When entering '2' or '8' using the NUM PAD on my keyboard into the coordinate field boxes while changing the image point it erases any number placed before it. For example when entering 32 with the NUM PAD it will leave only 2 entered. Similarly, yet oddly different, when entering 38 it will leave only 4 entered. If placing 2 or 8 before numbers it behaves normally.

After playing around with this a little more, I have found that if you have a number already entered and press 8 on the NUM PAD it will increase the number by one and pressing 2 on the NUM PAD will reduce the number by one. The UP ARROW and DOWN ARROW do the same thing, so this seems to be a built in feature that has somehow been applied to NUM PAD key presses?

## Attach a .c3p

What I have to report isn't demonstrable through a saved project, as it has to do with fields in the actual software itself.

## Steps to reproduce

1. Create a sprite object.
2. Open the sprite object and select to edit the image points.
3. Click in the X field box try to enter the number 32 with the NUM PAD.
4. Observe what occurs.
5. Repeat steps 3 and 4 for the Y field box.
6. Click in the X field box try to enter the number 38 with the NUM PAD.
7. Observe what occurs.
8. Repeat steps 6 and 7 for the Y field box.
9. Enter any other number in and press 2 or 8 to observe how the numbers react.
10. Press the UP and DOWN ARROW keys to observe similar functionality.
11. Click in the X field box try to enter the number 32 with the regular keyboard numbers.
12. Observe that these were entered successfully.
13. Repeat steps 11 and 12 for the Y field box.
14. Click in the X field box try to enter the number 38 with the regular keyboard numbers.
15. Observe that these were entered successfully.
16. Repeat steps 14 and 15 for the Y field box.

## Observed result

I saw that using NUM PAD to enter the numbers 2 or 8 was erasing the first digit placed before them and if multiple numbers were placed before them that 2 was decreasing and 8 increasing the numbers that had been entered.

## Expected result

I expected it to take all the numbers entered via the NUM PAD.

## More details

**Affected browsers/platforms:** Chrome. - Internet explorer is not supported with the version on my computer, so this has only been tested in the Chrome browser.

**First affected release:** R234.4 stable is the only version I used and witnessed this in.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.190
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
C3 release: r234.4 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 38 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Willow65806** [comment]
![image](https://user-images.githubusercontent.com/79710367/109322897-79074580-7818-11eb-8679-e8f63936c6e5.png)
I would like to add to this, that I can see there are built in features surrounding this. These work when you are not actively entering data into the fields manually. These do work as expected, so it is only when entering data via the NUM PAD into the coordinate fields that there are issues with entering the numbers 2 and 8.

**Comment by DiegoScirra** [comment]
The num pad keys have two different uses depending on whether **num lock** is enabled or not.

If it is enabled the keys work like the regular number keys, if it is not enabled they then take their alternate use, where 8, 2, 4 and 6 are UP, DOWN, LEFT and RIGHT respectively. This is the normal behaviour for all input elements.

**Comment by Willow65806** [comment]
The above was done with NUM LOCK enabled.

When NUM LOCK is enabled 2 and 8 are causing my above mentioned behavior, whereas 4 and 6 are not exhibiting that behavior.

**Comment by DiegoScirra** [comment]
It looks this is happening in the latest stable, but in the latest beta it is fixed. Can you try it out in the latest beta?

**Comment by Willow65806** [comment]
I can confirm that this is fixed in the latest beta! 😄 Thank you, sorry about that.
