### ISSUE TITLE
Rewhitelist plugins

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4616]
Hi, could you re-whitelist the following plugins, it seems there are additional requirements with the C3 Build Service:
https://github.com/Scirra/Construct-3-bugs/issues/4565

```
chadori-mobile-firebase-analytics@0.0.7
chadori-mobile-firebase-remote-config@0.0.3
```

Sorry for the frequent requests, there have been a few requirements that I was not aware before.
However, I am more confident these will work now.

I really hope we can expedite these two, since it has been months since I've tried to get these supported.
Thank you!

**Comment by AshleyScirra** [comment]
Updated allowlist on build server.
