### ISSUE TITLE
9patch objects appear distorted in Safari and iOS

### ISSUE THREAD

**Issue by lukasinspace** [Scirra/Construct-3-bugs#4617]
## Problem description

When using Construct 3 in Safari on MacOS, 9patch objects appear distorted when placed into a C3 layout.
When changing the 9patch object margins, the correct dimensions of the artwork are not maintained. 

Distortion is also present if the project is exported from C3 running in Safari to iOS.

## Steps to reproduce

1. Open the attched c3p in Chrome on Windows, or Chrome on MacOS. See in the editor that the 9patch object placed into the layout is pixel perfect with no distortion.
2. Open the same c3p in Safari on MacOS. See in the editor that the 9patch object placed into the editor is NOT pixel perfect. 
3. Change the left and right margin settings for the object and notice that the distortion of the 9patch artwork changes. Some elements become thicker, others become thinner. 

## Observed result
9patch artwork in MacOS safari is distorted in the editor. 
If the project is exported for iOS and tested on a device, the distored appearance of the 9patch object is also apparent on iOS when tested on an Apple device. 

## Expected result
Would expect the artwork to stay pixel perfect, matching the original artwork imported into the 9patch object (as is the case with 9patch objects in Chrome on Windows and MacOS)

## More details

**Affected browsers/platforms:** 
Safari on MacOS
iOS when project exported from C3 running is Safari on MacOS.

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
No project was attached, so I tried the built-in 9-patch example. It looked fine on Safari on macOS. Please make sure you follow the bug report guidelines since we need that information to be able to help.

**Comment by lukasinspace** [comment]
Sorry I made a c3p and I could have sworn I attached it. I think I forgot to rename to a .zip so it didnt attach maybe? Anyway here it is. 
[9patch_test.zip](https://github.com/Scirra/Construct-3-bugs/files/6067922/9patch_test.zip)

**Comment by lukasinspace** [comment]
Should I submit this as a fresh bug report? Or can this be reopened?

**Comment by lukasinspace** [comment]
I submitted a fresh bug report in case my comments here were missed: 
[Link to report](https://github.com/Scirra/Construct-3-bugs/issues/4626)
