### ISSUE TITLE
Editor crashes when cmd + click in the timeline on Mac

### ISSUE THREAD

**Issue by Vikingjonsson** [Scirra/Construct-3-bugs#4618]
## Problem description
When cmd + click in the timeline on mac both in the chrome app and in chrome web browsers the editor crashes.

## Steps to reproduce
1. add a timeline
2. cmd + click in the timeline
3. editor crashes

## Observed result
Editor crash.

## Expected result
Scrolling in the timeline.

## System details
Error report information
Type: unhandled exception
File: https://editor.construct.net/r234-4/components/bars/timelineBar/timelineBar.js, line 295, col 336
Message: Uncaught TypeError: m.vh.pMd is not a function
Stack: TypeError: m.vh.pMd is not a function at window.Ib.p4b.xka (https://editor.construct.net/r234-4/components/bars/timelineBar/timelineBar.js:295:336) at HTMLDivElement. (https://editor.construct.net/r234-4/components/bars/timelineBar/timelineBar.js:292:9) at HTMLDocument. (https://editor.construct.net/r234-4/main.js:419:493)
Construct 3 version: r234.4
URL: https://editor.construct.net/
Date: Sun Feb 28 2021 18:31:18 GMT+0100 (Central European Standard Time)
Uptime: 606.2 s

Platform information
Browser: Chrome
Browser version: 88.0.4324.192
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.14_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36
C3 release: r234.4 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) UHD Graphics 630
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

**Comment by DiegoScirra** [comment]
This was fixed in **r235**. If you are using the latest stable **r234.4** the bug is still present.
