### ISSUE TITLE
Xbox One Controller Support

### ISSUE THREAD

**Issue by wiverson** [Scirra/Construct-3-bugs#462]
## Problem description

Xbox One controller support appears to not be working.

## Attach a .c3p

Use the default "Gamepad control" project in Beginner Examples.

Also reproduced using a blank project with just a few text objects and the Gamepad object.

Verified that the controller was working properly with http://html5gamepad.com/

Used both an Xbox One controller in wired and wireless (Bluetooth) mode, no dice.

## Steps to reproduce

1. Open Beginner Example, "Gamepad Controller"
2. Use a controller
3. It doesn't work.  :)

## Observed result

Nothing.

Testing a bit, "supported" returns true but none of the other controller functions work.

## Expected result

The controller to be recognized.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: n/a (tried but not supported)

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 59.0.3071.86
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
C3 release: r36

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 23 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 540
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
It's a Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=711252

Workaround - change preview mode to browser tab or dialog.
