### ISSUE TITLE
Canvas layout line width

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4620]
## Problem description
Case that needs check.

When user defines line colors for layout canvas, then thous lines look bad with some zoom level.

If there are multiple objects then with some zoom level, then some objects have correct lines and some have blurry lines. When user moves object, the canvas lines don't change.

Case happened when i tried to change default lines, while problem is very small if lines are already faded, but i used solid ones (100% opacity).

Click on image, maximize and go fullscreen
![uuuuuu](https://user-images.githubusercontent.com/28864889/109432982-8be76900-7a16-11eb-92e3-437f63d256ea.jpg)

## Attach a .c3p
[Canvas_line.zip](https://github.com/Scirra/Construct-3-bugs/files/6057953/Canvas_line.zip)

## Steps to reproduce

1.Create sprite, select sprite, look selection outline and change zoom

## Observed result
Some canvas lines are blurry with some zoom level. 

## Expected result
No blurry lines. 

Example:
Line with 4px, with rounding error. Show not blurry 3px line.

## More details

Could be this: https://stackoverflow.com/questions/7607272/incorrect-display-linewidth-1-at-html5-canvas 
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors#a_linewidth_example

But engine should have good performance even with thousands of sprites, then some performance hevy line correction could be bad thing.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 86.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0
C3 release: r237 (beta)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 377 kb (0%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can't see anything wrong in the provided project.

Besides, drawing pixel-perfect lines in all zoom and DPI levels is extremely difficult. For example if you want to draw a 1px line on a display with a devicePixelRatio of 1.5 or 2.5, you don't have any good options: either it's too narrow, too wide, or it linearly samples which can make it look a bit smudged. So I think this is a normal result in some circumstances anyway.

**Comment by SnipG** [comment]
Are thous all canvas objects or some are browser UI with CSS ? If part of it is CSS, then it provides some options that fit devicePixelRatio better

**Comment by AshleyScirra** [comment]
The layout view is entirely rendered with a canvas. CSS doesn't magically fix the problem either though, since as I said, if you have a devicePixelRatio of 1.5, and you want to draw a 1px thick line, you can't. You can choose one device pixel (too thin), two device pixels (too thick), or linearly sample it (which will look slightly blurred). Using a different technology does not avoid the fact you have a limited physical number of display pixels to work with.

**Comment by SnipG** [comment]
Well i had that problem, while doing C3 theme. 1px disappeared and 2px looked sometimes 1px then again 2px or half was 1px other half 2px.
I switched to CSS properties thin / medium instead 1px / 2px / 3px. And it fixed it, in cases i tested it.

**Comment by AshleyScirra** [comment]
Those CSS properties "thin", "medium" etc. will just compute to a specific pixel size.
