### ISSUE TITLE
Changing Layouts shows objects from the Next layout

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-3-bugs#4622]
When I click change layout it will show any form control objects from the next layout into the current one.
Form control objects like:
Buttons, list, Txtbox, etc....

[Layout Bug1.zip](https://github.com/Scirra/Construct-3-bugs/files/6062990/Layout.Bug1.zip)

## Steps to reproduce

1.Preview the project from Home Layout
2.Click on the Play button
3.wait 

## Observed result

As it takes a bit to load the next layout all the form control objects like:
Buttons, list, etc.... will show up in the current layout

## Expected result

It will not show up any object from the next layout into the current layout

## More details

**Affected browsers/platforms:** 

Chrome

affected release:** r237

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.190
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
C3 release: r237 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 360 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The long loop in 'On start of layout' blocks drawing the first frame of the new layout for a while.

Form controls are HTML elements that float above the canvas, so don't need to wait for the first frame to be drawn to appear. So they appear first.

**Comment by Tarek200** [comment]
I'm confused, are you saying this is not a bug? as this defeat the (layout per layout) that you guys saying construct does as it clearly shows while is still in the current layout, I understand that it will show only when the layout has changed but not while is still on the current layout, this doesn't make sense, could you not just make them invisible and inactive until the next layout loads fully? then reactivate them etc.. 

The long loop is because I need something that takes time to load the next layout to simulate my game waiting time when loading layouts so I don't have to post it here with hundreds of events and objects and whatnot so I can make it easier for you to debug, the loading time to wait is similar just with different things.

Every time I report a bug you don't want to fix anything and we are paying for the subscription this is not cool you know. You either send me to a third party or tell me that is normal.

**Comment by AshleyScirra** [comment]
It's not a bug. It's also not related to layout-by-layout memory management, since it's to do with drawing rather than memory.

You should be able to easily work around it by waiting until the second tick to do your long-duration work. Then the first frame of the layout will have been painted.

**Comment by Tarek200** [comment]
But this didn't happen with C2 
[Layout Bug1.zip](https://github.com/Scirra/Construct-3-bugs/files/6068160/Layout.Bug1.zip)

The thing is that I depend on loops that create all the objects at the start of a layout I don't normally wait so I was trying to maybe show a losing screen and do as you said but you closed me the other bug which you say is impossible to show the loading progress so whatever I try to do is not possible as you blocked me both options. 

[Link](https://github.com/Scirra/Construct-3-bugs/issues/4623)

**Comment by AshleyScirra** [comment]
All you need to do is add a short wait before you do intensive work. Then you can control what is displayed.
