### ISSUE TITLE
Pathfinding behavior - "path cost" doesn't work with negative numbers.

### ISSUE THREAD

**Issue by ykanske** [Scirra/Construct-3-bugs#4624]
## Problem description

Dear fellow developers!

Please add the ability to reduce the path cost for objects to the pathfinding behavior.

Your great example "Pathfinding: path cost" shows how pathfinding can avoid unwanted areas, but I can't create the opposite logic when pathfinding builds a path trying to pass through the specified sprites.

**Important point!** Working in Construct 2, I set the price "-20" for objects and it worked fine, objects with the pathfinding behavior moved along my paths. However, after importing to Construct 3, this feature stopped working, and no matter what price I set, pathfinding, on the contrary, tries to run a path through the specified objects. I tried both positive and negative values, but I didn't see much difference.

<img src="https://construct-static.com/images/v878/uploads/articleuploadobject/0/images/53890/untitled-2.png">

Thanks for your attention.

## Attach a .c3p

Open example "Pathfinding: path cost"

## Steps to reproduce

1. Open example "Pathfinding: path cost"
2. Edit event:
+ System: On start of layout
-> Sprite: Add Pathfinding object RoughTerrain with path cost 20
Enter any negative value for path cost. (-20 for example)
3. Run project 

## Observed result

Sprite pathfinding always avoid RoughTerrain. No matter what path cost is added.

## Expected result

I expect the same result as it worked in Construct 2. For those cases when I have the entire map of difficult terrain, but I can place roads or areas that are convenient for movement.

## More details

Open same example in Construct 2, try to change cost to "-20".
You can make sure that in most cases, the pathfinding search will take priority over the object, especially in horizontal and vertical cases. This doesn't work perfectly, sometimes the path creates extra turns and loops, but nevertheless, Construct 2 allowed inverting the logic of the path cost.

**Affected browsers/platforms:** 
Any.

**First affected release:** 
I don't know...

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report, fixed for the next beta.
