### ISSUE TITLE
Particles - overlapping clogs system after instance destroyed

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4627]
## Problem description

If you destroy a particle object, even if there are still instances left (or not), any overlapping events will get stuck in a loop of failed collision check:
"collisionEngine.js:4 Uncaught (in promise) TypeError: Cannot read property 'IsCollisionEnabled' of null"

## Attach a .c3p

[particlesbug.zip](https://github.com/Scirra/Construct-3-bugs/files/6067997/particlesbug.zip)

## Steps to reproduce

1. Run the project

## Observed result

Tons of error messages clogging the system and causing a major system slowdown.

## Expected result

No errors

## More details

**Affected browsers/platforms:** Chrome/Nwjs

**First affected release:** r237

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report, fixed for next beta.
