### ISSUE TITLE
HDR - Unsupported

### ISSUE THREAD

**Issue by ItemME** [Scirra/Construct-3-bugs#4628]
## Problem description

HDR Mode from recent monitor hardware

## Attach a .c3p

It's a general issue with HDR not being properly supported, you can test this with any project/template, as long as you do have a HDR monitor

## Steps to reproduce

- Enable HDR on your Monitor/Windows (if supported)
- Start a Construct game project

## Observed result

One example of the difference between HDR ON/OFF in the current state

(HDR ON)
https://i.imgur.com/N8WfBef.png
(HDR OFF)
https://i.imgur.com/jaZjRPE.png

## Expected result

Colors shouldn't be as broken as it is right now, in the current state, colors, flashes and so on, are making games unplayable, and some texts impossible to read

**Affected browsers/platforms:** Tested only on Windows, but I'm pretty sure it doesn't matter what OS you're on

**Comment by AshleyScirra** [comment]
Construct does not currently support high color depths. If you wish to request this as a feature, please use our suggestions platform: https://construct3.ideas.aha.io/
