### ISSUE TITLE
Resize bug with Shift

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#4629]
## Problem description

Trying to resize sprite with Shift key, it is flipping. (Size: -200,200)

## Attach a .c3p

[bug.zip](https://github.com/Scirra/Construct-3-bugs/files/6068713/bug.zip)

## Steps to reproduce

![bug](https://user-images.githubusercontent.com/54614906/109651788-04157200-7b70-11eb-9550-49d76adba09f.gif)

1. Use **Shift + Left click** on that point. (Look gif)

## Observed result

flip

## Expected result

no flip

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r237

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
