### ISSUE TITLE
Initial value reset in Sprite instance variables 

### ISSUE THREAD

**Issue by SimpleAndEasyGames** [Scirra/Construct-3-bugs#463]
## Problem description

After delete all instances of sprite in layout, the instance variables initial value become 0. 

## Attach a .c3p

https://drive.google.com/file/d/0B7rTDv762xr0cFR3YjJuMlpsYWc/view?usp=sharing

## Steps to reproduce

1.create a sprite
2.create new instance variables to the sprite
3.set initial value for this instance = 10
4.delete the sprite from the layout
5.from project window -> object types. select the sprite and drop it in the layout.
6. the instance variables become 0 not 10

See this:
https://youtu.be/zhVJyxIrQEY

## Observed result

the instance variables initial value equal to 0

## Expected result

the instance variables initial value equal to 10. (like construct 2)

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Fixed for r37.
