### ISSUE TITLE
MobileAdvert plugin - Condition 'On User Personalization Updated' does not trigger as exected?

### ISSUE THREAD

**Issue by lukasinspace** [Scirra/Construct-3-bugs#4630]
## Problem description

When using MobileAdvert plugin, a User Consent dialogue is displayed to App users if they are inside the EU (or unknown location). The user chooses from two options on the dialogue: 'Yes, continue to see relevant ads' OR 'No,see ads that are less relevant'. When the user selects one of these two choices, ConsentStatus expression is changed from 'UNKNOWN' to either 'PERSONALIZED' or 'NON'. 
When this change is made, from 'UNKNOWN' to 'PERSONALIZED' or 'NON' the conditon 'On User Personalization Updated' _SHOULD_ trigger (I believe?). 
But the condition fails to trigger.

Attach a .c3p

FILE UPLOAD. ASHLEY PLEASE NOTE: I have emailed a zip file to support@construct.net containing an APK and a c3p project file. The email subject line matches this bug report number. Ive emailed it because the c3p contains my Admob publisher ID and Im not sure I want to post that publicly? Please refer to the files attached to that email. Thanks.

-------------
UPDATE 05-03-21
As requested, files attached to this bug report. 
-Built apk
-c3p project file, with details removed from MobileAdvert plugin.
[_mobileads_bug_report.zip](https://github.com/Scirra/Construct-3-bugs/files/6087217/_mobileads_bug_report.zip)

## Steps to reproduce

1. Install and run the APK on an Android device.
2. When it loads for first time note that ConsentStatus is 'UNKNOWN' (shown in text object).
3. Press the Green button > This displays current ConsentStatus > Should confirm UNKNOWN
4. Press the Yellow button > This will display the User Consent Dialogue
5. Choose either option on consent dialogue window. The User Consent Dialogue window will close. At this point ConsentStatus expression has been updated from UNKNOWN to either PERSONALIZED or NON depending on your choice. 
6. At this stage when the dialogue window closed, I think the condition 'On User Personalization Updated' _SHOULD_ have triggered, because user personalization was changed from UNKNOWN to either PERSONALIZED or NON. In my testing this condition does NOT trigger.
7. Press the green button to confirm that ConsentStatus HAS indeed changed from UNKNOWN to either PERSONALIZED or NON.
8. This process can be repeated, press the yellow button again to repeat.

## Observed result

When a choice is made on User Consent Dialogue window, User Personalization is changed, this is reflected by expression ConstentStatus, BUT the condition 'On user personalization Updated' does NOT trigger.

## Expected result

Expect that when a choice is made on User Consent Dialogue window, the window closes and condition 'On User Personalization Updated' should trigger > In the test APK this would be reflected by a line in the text box saying '**user personalization updated**'

## More details
**Look another small issue exists. Please note that the MobileAdvert documentation states that the expresson ConsentStatus should return one of 4 strings: UNKNOWN, PERSONALIZED, NON_PERSONALIZED or AD_FREE.
Please note that it doesn't return NON_PERSONALIZED, rather it simple returns 'NON'.
You can test this. When the User Consent Dialogue opens, choose the second option: 'No, see ads that are less relevant'. 
Then press the green button. See that ConsentStatus expression returns 'NON'.
But this is NOT the main bug I am reporting its just something else I noticed in testing that you may be interested to know.  

**Affected browsers/platforms:** 

Project build in Chrome on Windows. 
APK tested on Pixel4a

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Kyatric** [comment]
https://www.construct.net/en/forum/construct-3/general-discussion-7/mobile-ads-user-consent-158868#forumPost1036908

**Comment by lukasinspace** [comment]
Any news on this @AshleyScirra ?

**Comment by AshleyScirra** [comment]
Assigning to @DiegoScirra who is currently working on this, but it may become a moot point if the addon is rewritten.

**Comment by DiegoScirra** [comment]
From the next beta onwards the mobile adverts plugin will support Admob SDK 20.0.0 and upwards.

Many things have changed. One of them is ad personalization. You can no longer explicitly choose this setting, it is implicitly chosen according to user consent. The Construct action to change this value still exists, but can only be used to stop showing ads by setting it to **No Adverts**. eventually it will be deprecated.

I recommend to stop relying on it.
