### ISSUE TITLE
add my plugins to Whitelist plugins

### ISSUE THREAD

**Issue by rezamms** [Scirra/Construct-3-bugs#4632]
Hi, could you add this to the build service:

cordova-plugin-zarinpal

-----and-----

@metrixorg/cordova-plugin

Thank you!

The first plugin is to create a payment service
The second plugin is a system that checks the download rate of the game and its ads

**Comment by AshleyScirra** [comment]
Added `cordova-plugin-zarinpal@1.0.0` and `@metrixorg/cordova-plugin@1.0.4` to build service.
