### ISSUE TITLE
Animation Folders can't be re-ordered in the list of folders

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4633]
## Problem description

Animations themselves can be dragged and re-ordered in the list of animations, but the Animation _folders_ cannot. They can only be dropped into other folders, or moved to the root folder.

## Attach a .c3p

https://drive.google.com/file/d/1Zi7mX-8hp001nd0sUEnKQrnNsTdwMRXf/view?usp=sharing

## Steps to reproduce

1. Open the attached file.
2. Edit "Sprite" in the Animation editor.
3. Try to re-order the "Red Folder" so it's between "Green Folder" and "Blue Folder" 

## Observed result

The folder can only be moved to the bottom of the root Animation folder, or into an existing folder.

## Expected result

The folder should be able to move between existing folders.

## More details

**Affected browsers/platforms:** Chrome 88

**First affected release:** r238

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by lukasinspace** [comment]
I actually submitted this issue to the C3 suggestions website.
https://construct3.ideas.aha.io/ideas/C3-I-1702

**Comment by brushfe** [comment]
Ah ok — I couldn't tell if this was a bug or a new feature. Since it's basic feature of most GUIs and it's possible with the animations themselves, it felt like it was supposed to be possible here, but just non-functional.

**Comment by lukasinspace** [comment]
Well I had the feeling it more like a feature that hasnt been built yet.  

But the more people raising the issue will show the Scirra team that its a feature user's wld like to see!

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
