### ISSUE TITLE
[r238] - Different behavior between export to HTML5 and WebView2

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#4634]
## Problem description

This JS code works fine in previewing and exporting as HTML5 but does not work in WebView2.:

```js
// every tick
  const x = runtime.objects.X.getFirstInstance();
  const y = runtime.objects.Y.getFirstInstance();
  x.text = `${globalThis.screenX}`;
  y.text = `${globalThis.screenY}`;
```

## Attach a .c3p

[ScreenX-ScreenY.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6084581/ScreenX-ScreenY.c3p.zip)

## Steps to reproduce

**In preview**
1. Preview the project
2. Move the window

**In HTML5**
[Scirra Arcade Export.zip](https://github.com/Scirra/Construct-3-bugs/files/6084594/Scirra.Arcade.Export.zip)

1. Go to [https://www.construct.net/en/free-online-games/test-report-bug-24609/play](https://www.construct.net/en/free-online-games/test-report-bug-24609/play)
2. Move the window

**In WebView**
[WebViewExport.zip](https://github.com/Scirra/Construct-3-bugs/files/6084597/WebViewExport.zip)

1. Export the project like WebView and run it
2. Move the window

## Observed result

In preview and in Scirra Arcade the text change: shows the coordinates of the window relative to the screen.

In WebView the correct coordinates are shown only when loading the layout or resizing the window

![BugWebview2](https://user-images.githubusercontent.com/23579630/109984550-2c35da00-7d04-11eb-86c1-8fbec7d5dca7.gif)

## Expected result

I get the same result

## More details

**Affected browsers/platforms:** WebView2 in Windows 10 Pro 20H2 - Build 19042.804 - 64bit
**First affected release:** r238

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This looks like a bug in WebView2. I filed it here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1037
Will follow up there, so closing this issue.

**Comment by AshleyScirra** [comment]
Turns out we were missing some code in the wrapper app. Should be fixed in the next beta.

**Comment by el3um4s** [comment]
Thanks

**Comment by el3um4s** [comment]
I don't know whether to open a new report.

I have a similar problem with `globalThis.moveTo(x, y);`

This code work in C3 

```js
function lerp(start, end, amt) {
  return (1 - amt) * start + amt * end;
}

const sprite = runtime.objects.Sprite.getFirstInstance();
const winX = globalThis.screenX;
const winY = globalThis.screenY;
const x = lerp(winX, sprite.x, 0.25);
const y = lerp(winY, sprite.y, 0.25);

globalThis.moveTo(x, y);
```

![animation](https://user-images.githubusercontent.com/23579630/112636746-cab5e680-8e3d-11eb-83ef-a9d316f6f6e2.gif)

But nothing happens if exported with webview 2
