### ISSUE TITLE
Small sprite animation previews are padded and cropped

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4635]
## Problem description

Certain sprite animations playing inside the Preview Animation window are cropped. There is also a 1px space along the top and left sides of the sprite.

## Attach a .c3p

https://drive.google.com/file/d/1pF-uhSL40U-ryxoL4fwgh5yt4-GA1Ayx/view?usp=sharing

## Steps to reproduce

1. Open the "Sprite" object in the Animation Editor. 
2. Preview the animation. 
3. Preview the 8x8 animation. 
4. Preview the 16x16 animation. 
5. Preview the 24x24 animation. 

## Observed result

Animations are cropped in the Preview window and are padded along the top and left side.

## Expected result

The Preview should show the frames as designed: no padding and no crop.

## More details

**Affected browsers/platforms:** Chrome 88

**First affected release:** r238

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
