### ISSUE TITLE
Failed to open project. Check it is a valid Construct 3 single-file.

### ISSUE THREAD

**Issue by vhsmnk** [Scirra/Construct-3-bugs#4637]
**Problem description**
There's no c3p file opening and there's also a problem when I on saving the project. 

Attach a .c3p
https://drive.google.com/file/d/1asAfh4KDWIToX2e7wBFIUwwSyGyZ7UG4/view?usp=sharing

**Steps to reproduce**
Open the attached file or create a new one.
Make an alteration on the file.
Try to click "save" and it shows a message saying you not allowed to that file in wherever directory you may have setted. Than click "ok" and the file is generated.
Try to open the generated file and the message will be showned. "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

**Expected result**
The platform should be able to save and open the files with no issue.

**More details**
Affected browsers/platforms: Opera GX LVL2 (core: 73.0.3856.408)

First affected release: r238

![image](https://user-images.githubusercontent.com/69655224/110121027-9d28d080-7d9c-11eb-8a59-34f51e27c068.png)

![image](https://user-images.githubusercontent.com/69655224/110121116-bf225300-7d9c-11eb-94e6-b61d83eda8aa.png)

**Comment by AshleyScirra** [comment]
You've attached a file that is 0 bytes big - it has no data at all in it.

I tried saving to Google Drive and then opening, and it worked fine.

Please provide full steps to reproduce the problem in the first place, otherwise I'm afraid there's nothing we can do.

**Comment by AshleyScirra** [comment]
This report is not actionable as it stands, so closing.
