### ISSUE TITLE
Number keys select Tilemap tools instead of entering an array cell

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4638]
## Problem description

While a tilemap is selected, numbers cannot be entered into an array cell (in the array editor). Instead the numbers are registered as tilemap shortcuts, and the corresponding tilemap tool is selected.

## Attach a .c3p

https://drive.google.com/file/d/1tueCinrH8Mzz3QqW3GPuTuQQDNCKPYld/view?usp=sharing

## Steps to reproduce

1. Open the attached file.
2. Select the tilemap on Layout1.
3. Open the NewArray.json file in the array editor.
4. Click on any cell in the array.
5. On your keyboard, press 1, 2, 3, 4, 5, 6, or 7 in any combination.

## Observed result

The numbers are not entered into the cell. Instead, the corresponding tilemap tool is selected (because num 1-7 are shortcuts for the tools while a tilemap is selected).

## Expected result

The numbers are entered into the cell, ignoring the selected tilemap.

## More details

**Affected browsers/platforms:** Chrome 88

**First affected release:** r238

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
