### ISSUE TITLE
Anchored objects flicker on change of layout

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#4639]
## Problem description

Under certain circumstances, objects with anchor behavior (even if they are put on a layer with parallax 0,0) on change or restart of the layout, are flickering.

## Attach a .c3p

[anchor.zip](https://github.com/Scirra/Construct-3-bugs/files/6094464/anchor.zip)

## Steps to reproduce

1. Run / Preview project in a window
2. Click buttons to restart or change layout to see the problem.
3. Exit preview
4. Go to Display tab, change Fullscreen Mode and repeat steps.

## Observed result

On scale inner, objects flicker on top or bottom side
On scale outer, flicker occurs on the left or right side of the object
On letterbox scale, letterbox integer scale or disabled fullscreen mode, anchor behavior behaves correctly.

## Expected result

No flicker

## More details

Just of curiosity, I opened an old C2 project and there, anchor behavior was working without problem.

**Affected browsers/platforms:** Chrome, Firefox

**First affected release:** Don't know. Now I'm using latest beta (r238)

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 88.0.4324.190
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
C3 release: r238 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 269 gb
Storage usage (approx): 654 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report, should be fixed in the next beta.
