### ISSUE TITLE
Tile Map tab doesn't have scroll bars on mac book pro

### ISSUE THREAD

**Issue by rhg1968** [Scirra/Construct-3-bugs#464]
## Problem description

*Enter a concise description of your problem here*
I am evaluating using a tile map in a game I am creating.
As a test I imported a sheet of tile images with the whole image being 1728 × 1280 and each tile 32x32 into the TileMap object. I know I might not need an image that has this many tiles, but I wanted to get a sense of how to use tile maps.
I am able to pick a tile and draw it on the screen without any issues. My problem comes in that I can only see a portion of the tile image to select tiles from in the tile map tab. I can't scroll the window to see more of the image. I can resize it a little and see more of the image to select additional tiles.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.Load a tile image that's bigger then the tile map tab on a mac book pro
2.There is not way to access all parts of the image, no scroll bars.
3.

## Observed result
No way to access all parts of a tile map image on mac book pro
*What do you see happen?*

## Expected result
Ability scroll and click on different parts of the image
*What did you expect to happen instead?*

## Affected browsers
Chrome
* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r37.

The scrollbars still are not shown because that is how OSX rolls, but you can now scroll the image in all directions using the familiar 2-finger swipe on your track pad.
