### ISSUE TITLE
copying timelines across projects causing editor to crash

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-3-bugs#4640]
## Problem description

Attempting to copy a timeline from one project to another causes editor to crash almost every time. Of my test project, I managed to successfully copy the timeline across only once in five attempts. Interestingly, on the one time it managed to copy over, the project that it was copied from became corrupted and could no longer be opened.

Included a gif to show crash in action: ![timelines1](https://user-images.githubusercontent.com/46861823/110195421-2b7e7e80-7e91-11eb-8d5a-cc54dcc2ead2.gif)

## Attach a .c3p

[timelines test.zip](https://github.com/Scirra/Construct-3-bugs/files/6094723/timelines.test.zip)

## Steps to reproduce

See gif

1. open both projects in editor
2. right click and copy timeline from project A
3. right click and paste while on the timeline folder in project B

## Observed result

editor crash

## Expected result

timeline to successfully copy over. I captured a gif of it successfully working, not sure yet what the difference is:

![timelinesSuccess](https://user-images.githubusercontent.com/46861823/110195722-74373700-7e93-11eb-95a0-c9c82c5711fc.gif)

## More details

As per my forum post here: https://www.construct.net/en/forum/construct-3/how-do-i-8/copy-timelines-across-projects-158835
I've been running some tests on how to copy timelines from one project to another. Currently it seems very difficult, and I have only managed to do it once (which suggests to me that it should be possible). 

Tried this in the Chrome browser app as well as the standalone editor.

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: no master keyframe was found for property keyframe
Stack: Error at Function.d.QVa (https://editor.construct.net/r234-4/main.js:287:41) at window.assert (https://editor.construct.net/r234-4/main.js:201:149) at n.uua (https://editor.construct.net/r234-4/projectResources.js:496:112) at n.pgc (https://editor.construct.net/r234-4/projectResources.js:496:487) at https://editor.construct.net/r234-4/projectResources.js:502:12 at Function.Jvd (https://editor.construct.net/r234-4/projectResources.js:389:486) at Function.T1a (https://editor.construct.net/r234-4/projectResources.js:390:35) at Function.JDa (https://editor.construct.net/r234-4/projectResources.js:390:196) at n.Ka (https://editor.construct.net/r234-4/projectResources.js:501:486) at Function.wsd (https://editor.construct.net/r234-4/projectResources.js:503:443)
Construct 3 version: r234.4
URL: https://editor.construct.net/
Date: Sat Mar 06 2021 15:27:21 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 393.7 s

Platform information
Browser: Chrome
Browser version: 88.0.4324.190
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
C3 release: r234.4 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
It seems pasting works, provided that the target project is active, if you try to paste while the target is not active (greyed out in Project Bar) then a  crash will take place.

Maybe that is why you have been able to do it a few times.
