### ISSUE TITLE
Simple "check variable" event doesn't trigger

### ISSUE THREAD

**Issue by KekGames** [Scirra/Construct-3-bugs#4641]
## Problem description

In certain conditions the  "check variable" event doesn't trigger as it should.
In this demo you create characters by pressing "1" key (in which case the character spawns a pickaxe when "Pathfinding arrived" is triggered) or press "2" key (in which case the character spawns a pickaxe upon creation). If you press "1" rapidly - it doesn't work as intended and the **Pickaxe: MyCharacterUID=Character.UID** is not triggered for some instances (it is supposed to set angle towards an imagepoint of the Character).

## Attach a .c3p

[VariableSelectBug.zip](https://github.com/Scirra/Construct-3-bugs/files/6095238/VariableSelectBug.zip)

## Steps to reproduce

1. Start Layout1 preview
2. Press the "1" key once, wait untill the character arrives and press "1" again to spawn another character
3. Try pressing the "1" key rapidly and repeatedly
4. Try pressing the "2" key rapidly and repeatedly

## Observed result

 If you create characters rapidly using "1" key - their pickaxes are not "attached" correctly through instance variables to the character. Even though, if you check it through debug mode - you will see that all variables are set correctly, but the event **Pickaxe: MyCharacterUID=Character.UID** still doesn't trigger, or triggers incorrectly. It can be triggered if you add the "For each" condition, but it's an unnecessary CPU usage in this case, since, as shown in other examples, it should work without the "For each".

## More details

**Affected browsers/platforms:** Chrome PC and Chrome Android

**First affected release:** current stable release, but also checked in r238 beta and in r220 with same results. Same with the c2runtime

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.190
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
C3 release: r234.4 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 67 gb
Storage usage (approx): 239 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
This is just a mistake in your events. In event 11, you compare MyCharacterUID = Character.UID. The expression `Character.UID` will only evaluate to a single number. Therefore the event can only associate a single pickaxe with a single character.

Add 'For each Character' above it and it should do what you want.

**Comment by KekGames** [comment]
I still don't get why it works in other cases - if you either wait between spawning characters, or spawn and the pickaxe in the same event. But I'll also try containers, thanks for the advice.
