### ISSUE TITLE
Crash while in timeline editing mode and set initial frame

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#4642]
## Problem description

Crash when int timeline editing mode set initial frame.

## Attach a .c3p

https://drive.google.com/file/d/1RcGOpXLtKWIi-e7mflf2v6RuQjAKL4tG/view?usp=sharing

## Steps to reproduce

Crash when int timeline editing mode set initial frame

1. Select Sprite and open the timeline1
2. Enter editing mode in timeline
3. Set initial frame in Spirte's properties

## Observed result

Crash

## Expected result

Not crash.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r238/plugins/allEditorPlugins.js, line 192, col 292
Message: Uncaught TypeError: Cannot read property 'Ey' of undefined
Stack: TypeError: Cannot read property 'Ey' of undefined at h.Instance.Z_b (https://editor.construct.net/r238/plugins/allEditorPlugins.js:192:292) at p.iE (https://editor.construct.net/r238/projectResources.js:214:408) at p.ca.Oxd (https://editor.construct.net/r238/components/bars/propertiesBar/propertiesBar.js:85:408) at https://editor.construct.net/r238/components/bars/propertiesBar/propertiesBar.js:83:414 at p.ca.Zwa (https://editor.construct.net/r238/components/bars/propertiesBar/propertiesBar.js:83:481) at p.ca.rla (https://editor.construct.net/r238/components/bars/propertiesBar/propertiesBar.js:83:369) at https://editor.construct.net/r238/components/bars/propertiesBar/propertiesBar.js:75:322 at d.g.J.lua.Bwa (https://editor.construct.net/r238/main.js:906:338) at d.g.J.Ykb.iW (https://editor.construct.net/r238/main.js:832:58) at d.g.J.Ykb.tE (https://editor.construct.net/r238/main.js:846:235)
Construct 3 version: r238
URL: https://editor.construct.net/r238/
Date: Sat Mar 06 2021 19:31:23 GMT+0100 (közép-európai téli idő)
Uptime: 415.2 s

Platform information
Browser: Chrome
Browser version: 89.0.4389.82
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
C3 release: r238 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
