### ISSUE TITLE
Canvas + Mesh not updating every tick?

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4645]
## Problem description

First of all, I'm not sure if this is a bug, a limitation, or something that I'm doing wrong.
I'm trying to create drop shadows using the canvas plugin and mesh distortion on the canvas.
If I'm drawing every tick, when the light source is on the right of the player, the shadows is not drawn in the right place.
If I'm drawing every other tick and wait 0 before changing the mesh, it draws it correctly, but flickers like hell.

P.s I saw you closed this idea, but it would still be nice to be able to draw a quad straight from a sprite, instead of changing the mesh of the canvas, will that be possible in the future?
https://construct3.ideas.aha.io/ideas/C3-I-625

## Attach a .c3p

[shadows.zip](https://github.com/Scirra/Construct-3-bugs/files/6096915/shadows.zip)

## Steps to reproduce

1. Run layout
2. Drag the player or light source around.
3. See result of every tick vs every other tick.

## Observed result

Shadows are not drawn correctly when drawing every tick.

## Expected result

Shadows drawn the same as they do when drawing every other tick.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It looks like your events are wrong. If you make the canvas clear with a red color and set its color to white (so it does not greyscale everything), you're actually setting two mesh points to the same position, resulting in a distorted triangle. This is not how to implement a skew, which is what it looks like you're trying to do: a skew involves moving the upper or lower points sideways by the same amount.
