### ISSUE TITLE
Update Cordova Plugin

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#4646]
Hi, sorry for so many requests.
Can you please include this updated plugin:

**`cordova-support-google-services@1.4.1`**

Thankyou

**Comment by SparshaDhar** [comment]
The currently included version of `cordova-support-google-services` plugin is `@1.3.2` which is over one year old.

Whenever I try to use the `c3-firebase-auth-forked@2.0.0` plugin along with the `cordova-support-google-services@1.3.2`, it gives this result. I tried running this on my PC and the error is still the same. So updating the plugin would fix the issue:
```
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.google.gms.google-services']
   > Cannot add extension with name 'googleServices', as there is an extension already registered with that name.
```

**Comment by AshleyScirra** [comment]
I don't think you should use that plugin any more. Instead, call [SetGooglePlayServicesEnabled()](https://www.construct.net/en/make-games/manuals/addon-sdk/reference/iplugininfo) in the SDK. Let me know if that solves the problem.

**Comment by AshleyScirra** [comment]
I'm afraid I can't help you with build issues using third-party code. The build server basically just runs the Cordova CLI, beyond that you have to determine the configuration yourself. Try doing your own local CLI builds first to get it right.
