### ISSUE TITLE
Changing Font in desktop offline version crashes Construct 3 

### ISSUE THREAD

**Issue by jonathanmwebb** [Scirra/Construct-3-bugs#4647]
When working on the desktop version (not in Firefox) if I add a text box then try to change the Font, Construct 3 will crash and close every time regardless the text size, the characters or numbers inside the text box. Construct 3 text box does work online, but I do not wish to make my projects online https://1drv.ms/v/s!AtwK0EzOYkbyjzDD8ahOQlVYBjt_?e=lq46gh
https://1drv.ms/u/s!AtwK0EzOYkbyjy-Mbj1mIikYqvEO?e=7UO3d7

**Comment by AshleyScirra** [comment]
It works for me. Please follow the bug report guidelines otherwise it's impossible to help.
