### ISSUE TITLE
Share > Request app rating no longer showing popup

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#4648]
## Problem description

When I use the request app rating action no popup appears. Tried it in my released app and in this tiny example.
## Attach a .c3p
[TestRatingPopup.zip](https://github.com/Scirra/Construct-3-bugs/files/6106392/TestRatingPopup.zip)

## Steps to reproduce

1. add share plugin
2. request app rating

## Observed result
No popup to rate appears

## Expected result
popup to rate should appear

## More details

I have an app run counter in my app and on start of layout + appruncount=6 it should show the popup but nothing happens.

In the example above I just used it on Start of Layout to see if anything happens. I exported for Android (debug APK) and no rating window appears. I used the app ID of my app on google play.

**Affected browsers/platforms:** 
Chrome Android

**First affected release:** 
r234
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.190
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.399999976158142
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
C3 release: r234.4 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 1 gb (1.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 615 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I don't believe we've changed the code for this since September, so it seems unlikely there has been any change in Construct that has caused this. The app must also be correctly configured, published to the Play Store, and not have exceeded the rate limits for showing the app rating, since Android will ignore the prompt if you've tried to show it too many times. Are you sure that all the above is not a consideration here?

**Comment by TheBl4ckSh33p** [comment]
Does it work if you just build a debug APK from the example I provided? The project has my published app ID in it so it should show a popup for you?

I think its properly configured and its available on Google Play for some time now.

**Comment by fredriksthlm** [comment]
Even if this is not related to this particular issue, there has been some updates and bug fix for the In App Review in the latest versions of the Core Library.
You use 1.8.0, the latest is 1.10.0. There was a bug fix in 1.8.1 and some change in 1.10.0

So maybe a good idea to keep track with the latest version.

https://developer.android.com/reference/com/google/android/play/core/release-notes

**Comment by DiegoScirra** [comment]
I tried this out with the application I initially made to test the feature, and it still works. Now waiting to get a different one approved to be sure and try a few different things.

Have you tried triggering the review through an explicit user gesture? Like clicking a button?

As I understand it, the API was designed to avoid being abused, so I wouldn't be surprised if it rejects calls that it deems programmatic.

**Comment by fredriksthlm** [comment]
It is the other way around actually. It is only possible to show the app rate window like once a month (or so) to a user, calling it more often will not show you any rate window at all. So you should never trigger it with a button or so, since that button will basically only work once a month, and only if the user has **not** filled in any review.

the api should be called automatically when the user finish some level or get a certain point or something. (which requires some game time). then the rate might show occationally like once a month, until the user has rated, after that it will never show again

(The above approach is according to google recomendation)

**Comment by DiegoScirra** [comment]
I need to try it out, but I would imagine that trying to trigger the review dialog on start of the first layout, would be ignored as a spammy attempt to get a review from the user. Triggering after a while, and after the application has received some sort of input sounds more sensible.

But as I said, I am still waiting to get an application approved to actually test all of this. I mistakenly deleted the signing certificates of the last one I made, so I can't update it and this API has to at least be on a closed testing track to work. It doesn't work on internal testing.

**Comment by DiegoScirra** [comment]
I tried this out, and it works as intended. A few things worth mentioning.

1. The API only works on apps installed through Google Play Store.
2. It doesn't seem to be possible to upload a debug APK to Google Play Store. If you try to do that, Google Play Console just tells you, you can't.
3. If you install the debug APK by other means, the API won't do anything.
4. If you run on an emulator, the API won't do anything.
5. The rate flow will only work with Release APKs or App Bundles installed through Google Play Store.
6. Making a call to rate the app on start of layout does work.

The **Play Core Library** has been updated from version **1.8.0** to **1.10.0**
