### ISSUE TITLE
Enabling Sprite's Anchor Behavior Stretches Sprite

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#4656]
## Problem description

When turning a sprite's anchor behavior on after it was off, the sprite will appear to move or stretch toward one side of the viewport.

## Attach a .c3p

]
[AnchorSlippingTest.zip](https://github.com/Scirra/Construct-3-bugs/files/6116968/AnchorSlippingTest.zip)

## Steps to reproduce

1. Open AnchorSlippingTest.c3p included in AnchorSlippingTest.zip.
2. Run the project in a preview window or remote preview window.
3. Note the sprite with its anchor behavior being toggled every second stretching or moving across the screen each time.

## Observed result

Anchored sprite moves or stretches when its anchor is enabled after being disabled.

## Expected result

Enabling anchor behavior on a sprite for whom it was previously disabled then allows it to continue maintaining a position or size relative to viewport dimensions, but **does not** immediately move or stretch the sprite when the viewport size was not changed.

## More details

**Affected browsers/platforms:**  Firefox, Chrome, Microsoft Edge.

**First affected release:**  Unknown (but currently happening on r234.4 stable)

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 86.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0
C3 release: r234.4 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 370 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by ChromeWisp** [comment]
Update: I've been trying to figure this out more and it seems that the amount and direction of stretch is dependent on the viewport or window. Having the preview window sized to taller proportions than the layout's size causes objects to stretch **vertically** when anchor is enabled on the, while a preview window sized wider proportionally than the layout's size seems to make the anchoring objects stretch **horizontally**.

**Comment by AshleyScirra** [comment]
I believe this is the same thing as issue #4728. It's actually by design. The issue is described more in the comments there, but in short enabling the anchor behavior acts as if it's placed within the dotted viewport area shown in the Layout View. If the fullscreen mode and anchor properties have caused the object to be moved away relative to the dotted viewport area, re-enabling the behavior will cause it to move differently. As I suggested in the other issue, consider positioning with the system viewport expressions if you want more control than the Anchor behavior provides.
