### ISSUE TITLE
TiledBg with mesh crash in certain case

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4658]
## Problem description
Tiledbg with mesh edit. Editor will crash

## Attach a .c3p
[TiledBg_Mesh_buggg.zip](https://github.com/Scirra/Construct-3-bugs/files/6118538/TiledBg_Mesh_buggg.zip)

## Steps to reproduce

1.Open example, enable collision poly on layout, click on sprite, create mesh 2x2
2.Select bottom-left corner, drag it over top-right corner slowly. 
3. If crash does not happen, drag it over multiple times.

## Observed result
Crash

## Expected result
No crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: must have at least three points in a collision poly
Stack: Error at Function.GWa (https://editor.construct.net/r239/main.js:287:41) at https://editor.construct.net/r239/main.js:201:149 at f.bC (https://editor.construct.net/r239/projectResources.js:152:372) at Object.KEa (https://editor.construct.net/r239/main.js:1463:259) at p.KEa (https://editor.construct.net/r239/projectResources.js:238:421) at q.Ugb (https://editor.construct.net/r239/projectResources.js:627:393) at r.Ugb (https://editor.construct.net/r239/projectResources.js:597:474) at Object.Mud (https://editor.construct.net/r239/components/editors/layoutView/layoutView.js:13:474) at Uqc (https://editor.construct.net/r239/components/editors/layoutView/layoutView.js:4:237)
Construct 3 version: r239
URL: https://editor.construct.net/r239/
Date: Wed Mar 10 2021 22:04:12 GMT+0200 (Eastern European Standard Time)
Uptime: 2678.1 s

Platform information
Browser: Chrome
Browser version: 88.0.4324.190
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
C3 release: r239 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report, should be fixed in the next beta.
