### ISSUE TITLE
Fullscreen off and canvas location is moved

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4659]
## Problem description
Case that needs check if bug or feature suggestion

When user uses project with fullscreen scaling off and then user changes canvas location with CSS. Project objects bug out. Their positon location stay at top-left corner, while images move.

## Attach a .c3p
[scale_bugg3.zip](https://github.com/Scirra/Construct-3-bugs/files/6118567/scale_bugg3.zip)

## Steps to reproduce

1.Open example,  drag red sprite around
2.Click fullscreen, try dragging sprite around
3.

## Observed result
When canvas location is changed by CSS, then object locations stay top-left corner. 

## Expected result
Object locations are depending on canvas location.

It seems strange to keep canvas top-left corner when fullscreen is off. But it could be for default location
It would be reasonable to suggest that user like to change it! When fullscreen is off and fullscreen is enabled, user likes to change canvas to be middle, he cannot!

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is not supported. When you use fullscreen "off", the runtime expects the canvas to appear in the top-left. Changing the position with your own CSS will break this assumption that the runtime makes.

**Comment by SnipG** [comment]
C2runtime seems to allow it! There must be reason why c2runtime had it?

**Comment by AshleyScirra** [comment]
It was never supported. Sometimes things only work by accident.
