### ISSUE TITLE
Unable to pick external editor on MacOs

### ISSUE THREAD

**Issue by Mak14** [Scirra/Construct-3-bugs#4660]
## Problem description
I'm trying to select the external editor, but no luck.

## Steps to reproduce
 1. Open any sprite in any project
 2. Click "Edit with external software button"
 3. Chose External Software pop up opens
 4. Press any of the 5 Choose buttons
 5. Select desired app
 

## Observed result
 System window is closed but no apps selected and no paths appeared.
Also, checkbox on the right could not be pressed and selected.

## Expected result
Expecting to select an app as editor

## More details
This happens on Big Sur os, but also was presented on Catalina os.
After you guys did some fixes there is no errors now, but i'm still unable to select an app.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
You haven't included the system details. Are you using the latest version of NW.js? It may be just that you are using an out of date version. Please follow the bug report guidelines with every report.

**Comment by AshleyScirra** [comment]
No information provided after 2 weeks, so closing.
