### ISSUE TITLE
black screen on preview R239

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#4661]
## Problem description

I found a very weird bug in R 239. When I start Construct 3, log in and open my project, preview, the screen is just black. If I do the same thing without login, preview, everything works fine. Then I can log in and it works also in the paid version. 
But if you first login, preview, then you cant just log out, preview, login. Doesnt work. You have to close Construct first and start with Log out :)

## Attach a .c3p
[a_startBlack.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6123358/a_startBlack.c3p.zip)

## Steps to reproduce

1. Start Construct 3 in Browser, Log in, Preview. Observe the Result
2. Start Construct 3 in Browser, Log Out, Preview. Observe the Result
3. Start Construct 3 in Browser, Log Out, Preview. Log in, Preview. Observe the Result

## Observed result
Step 1 - Black screen
Step 2 - Pink square on screen
Step 3 - Both Previews with pink square on screen

## Expected result

always pink square on screen

## More details

I tested on Mac with Chrome an Firefox. In both browsers the same behaviour

**Affected browsers/platforms:** 

**First affected release:** 
worked in r234.4, doesnt work in r239
## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 86.0
Browser engine: Gecko
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko/20100101 Firefox/86.0
C3 release: r239 (beta)
Language setting: en-US
Local storage

Storage quota (approx): 1.9 gb
Storage usage (approx): 29 mb (1.5%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2048
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It works fine for me both logged in and logged out. This is not surprising to me, because whether or not you are logged in does not change what is previewed at all. So I suspect the login state is actually unrelated and you've falsely correlated some other cause with that (which is pretty common).

When preview is blank, can you press F12 and report any errors that appear in the browser console?

**Comment by bubbblebub** [comment]
yes indeed there is an error:

Uncaught (in promise) TypeError: this._runtime.GetLoadingLogoAsset() is null
    InitLoadingScreen https://editor.construct.net/r239/preview/c3/canvasManager.js:37
    _InitialiseCanvas https://editor.construct.net/r239/preview/c3/runtime.js:31

**Comment by AshleyScirra** [comment]
OK, I think that's the same as issue #4651 and already fixed for the next beta.
