### ISSUE TITLE
Whitelist plugin

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#4662]
Hi, please **include** this plugin:

`sparsha-firebase-authentication@1.0.0`

This fixes all the build errors that were occurring earlier.

<br>

Also, **remove** this plugin from the [Cordova Build Server List](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/build-server-cordova-plugin-149266):
`c3-firebase-auth-forked@2.0.0`

Thankyou ❤

**Comment by AshleyScirra** [comment]
Added `sparsha-firebase-authentication@1.0.0` to the build service. `c3-firebase-auth-forked@2.0.0` has been removed.

**Comment by SparshaDhar** [comment]
Thank you so much ❤ Finally its working!
