### ISSUE TITLE
Wait for Signal Initialization

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4663]
## Problem description
Wait for Signal does not receive the Signal the first time it is triggered.

## Attach a .c3p
https://www.dropbox.com/s/poc4o458r8vldmm/waitforsignal.c3p?dl=1

## Steps to reproduce

1. Run the project
2. Click the button object
3. Note the return value
4. Click the button again
5. 5 Repeat... 

## Observed result
The text of the button is not set the first time.

## Expected result
The value from the corresponding signal should be used, as it does in additional clicks.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details
10 chrome last beta

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is not a bug: "wait for signal" only resumes for signals *after* the action is used. If you signal before the action is used, it does nothing, because nothing is waiting.

**Comment by pigmalien** [comment]
Ok. Changing the order so that the wait comes before the signal works.
