### ISSUE TITLE
Ipad mouse click in editor

### ISSUE THREAD

**Issue by kyokucort** [Scirra/Construct-3-bugs#4665]
## Problem description

If I touch the screen with finger in sprite editor then the mouse left click won't work until I restart the editor

## Attach a .c3p

No c3p, it applies with any project, example project too, Kiwi by example.

## Steps to reproduce

1. Open a project on ipad
2. Left click work with no problem
3. Open sprite editor
3. Touch the screen (pan view by example, or anything with finger)
4. Left mouse click doesn't work

## Observed result

Left mouse click doesn't work

## Expected result

Left click working

## More details

It's a problem since zoom with scroll doesn't work on ipad (at least i didn't could make it work), so sometimes I zoom with 2 fingers and then mouse becomes useless.

Browser : Safari on ipad

**First affected release:** I'm not sure the problem was there before 2021, sorry doesn't know the release

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This looks to be the same as #4891. There is a problem when mixing input methods.
