### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'Release' of null

### ISSUE THREAD

**Issue by AquaTide** [Scirra/Construct-3-bugs#4667]
## Problem description

No error on the preview/debug. Error only happen once the project is exported as HTML5.

Build Option:
Platform to export: Web (HTML5)
Deduplicate Image: yes
Recompress Image: yes
Minify mode: none

## Attach a .c3p
.c3p :
[BazkinDaz.zip](https://github.com/Scirra/Construct-3-bugs/files/6136602/BazkinDaz.zip)

HTML Build :
[BazkinDaz Export.zip](https://github.com/Scirra/Construct-3-bugs/files/6136632/BazkinDaz.Export.zip)

## Steps to reproduce

The error only happen in Export build, there's no error when preview/debug:
1. Click start game
2. Follow the tutorial
3. Once it back to store view, this error happen

## Observed result

The following error appears:

Uncaught (in promise) TypeError: Cannot read property 'GetObjectClass' of null
    at js_cols.RedBlackSet.SortByTickSequence [as compare] (c3runtime.js:2157)
    at js_cols.RedBlackSet.get_ (c3runtime.js:555)
    at js_cols.RedBlackSet.contains (c3runtime.js:556)
    at RedBlackSet.Remove (c3runtime.js:565)
    at C3Runtime._RemoveBehInstToTick (c3runtime.js:2360)
    at TimerInstance._StopTicking (c3runtime.js:1965)
    at TimerInstance.Release (c3runtime.js:1963)
    at TimerInstance.Release (c3runtime.js:4009)
    at BehaviorInstance.Release (c3runtime.js:2156)
    at Instance.Release (c3runtime.js:2045)

Uncaught (in promise) TypeError: Cannot read property 'GetDt' of null
    at FadeInstance.Tick (c3runtime.js:4106)
    at C3Runtime._BehaviorTick (c3runtime.js:2361)
    at C3Runtime.Step_AfterPreTick (c3runtime.js:2366)
    at C3Runtime.Tick (c3runtime.js:2364)
    at normal (c3runtime.js:2304)
    at c3runtime.js:355

Uncaught (in promise) TypeError: Cannot read property 'Release' of null
    at Instance.Release (c3runtime.js:2045)
    at C3Runtime.Step_RunEventsEtc (c3runtime.js:2369)
    at C3Runtime.Tick (c3runtime.js:2364)
    at normal (c3runtime.js:2304)
    at c3runtime.js:355

## Expected result

There should be no error except rom LoL API plugin.

## More details

**Affected browsers/platforms:** 
Chrome: yes
Firefox: unknown
Edge: yes
Safari: unknown

**First affected release:**
Start the project using r225, but it's unknow as I haven't try to export the build
and exporting finished project using r234.4

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 89.0.4389.82
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
C3 release: r234.4 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 268 gb
Storage usage (approx): 114 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines - if you provide your full project it can be pretty much impossible to solve the problem. Can you produce a minimal project as per the guidelines?

Can you also test the project in the latest beta release as the guidelines indicate? It's possible we already fixed this problem in a beta release.

**Comment by AshleyScirra** [comment]
No information provided after 2 weeks, so closing.
