### ISSUE TITLE
Mesh - Timeline Edit Crash

### ISSUE THREAD

**Issue by jarnMod** [Scirra/Construct-3-bugs#4669]
## Problem description

Using mesh feature during timeline edit mode results in crash

## Attach a .c3p

[c3p on dropbox](https://www.dropbox.com/s/d2nxzi97db8jmwh/bugTimelineMesh.c3p?dl=0)

## Steps to reproduce

1. Open the attached c3p
2. Click timeline, enable edit mode
3. Click the sprite, add mesh, click ok with any mesh parameter (or if added before hand, edit mesh)
4. Crash expected

If you want to reproduce the file from scratch, simply insert a sprite and a timeline then follow the steps above

## Observed result

C3 crash
![image](https://user-images.githubusercontent.com/50398948/111128716-cb31c000-85a7-11eb-9245-dbc36939a18e.png)

## Expected result

This is something I think the team should consider
1. Makes timeline and mesh deformation compatible, allow sprite to warp in timeline Amoeba style
2. Disable mesh during timeline edit

I think the 1st option is right, but might have a lot of work with it. The 2nd is ok. At least it doesn't crash.

## More details
Thank you for your hard work and for introducing this new mesh feature. It should enable a few things we can do.

**Affected browsers/platforms:**
Running C3 on Chrome

**First affected release:** 
C3 r234.4 stable

## System details
<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r234-4/components/editors/layoutView/layoutView.js, line 158, col 26
Message: Uncaught TypeError: this.sba is not a function
Stack: TypeError: this.sba is not a function at p.Aec (https://editor.construct.net/r234-4/components/editors/layoutView/layoutView.js:158:26) at p.xO (https://editor.construct.net/r234-4/components/editors/layoutView/layoutView.js:157:228) at Array.sB (https://editor.construct.net/r234-4/components/editors/layoutView/layoutView.js:153:224) at d.Event.hNc.Sad (https://editor.construct.net/r234-4/main.js:429:387) at window.ml.dispatchEvent (https://editor.construct.net/r234-4/main.js:425:135) at window.ml.Htd (https://editor.construct.net/r234-4/components/editors/layoutView/layoutView.js:14:204) at Vpc (https://editor.construct.net/r234-4/components/editors/layoutView/layoutView.js:4:237)
Construct 3 version: r234.4
URL: https://editor.construct.net/
Date: Mon Mar 15 2021 16:01:55 GMT+0700 (Indochina Time)
Uptime: 65.4 s

Platform information
Browser: Chrome
Browser version: 89.0.4389.82
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
C3 release: r234.4 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Please test the latest beta release as per the bug report guidelines, to make sure you aren't reporting an issue that we've already fixed.

**Comment by jarnMod** [comment]
Confirm that the bug has been fixed for the recent beta release
Thank you.
I will be more careful and check the beta release before reporting next time.
