### ISSUE TITLE
r239 plug in bug

### ISSUE THREAD

**Issue by dabontv** [Scirra/Construct-3-bugs#4670]
Some files are not updating to current plug in version. If I create a new blank file plugin is correct and shows updates, older files sometimes do not show the update. This is happening with multiple files and plug ins.

Using r239, other developers I work with 
![plugin-bug](https://user-images.githubusercontent.com/3484111/111156191-d5ce6400-856b-11eb-8b1f-c1f1c3403cf7.jpg)
have reported this issue to me as well.

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines - we need that information to be able to help.
