### ISSUE TITLE
Module Script Type does not work with OBS

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#4672]
## Problem description

If I export an HTML from Construct with Script type set to Classic, then upload it to a server and open it as a browser source within OBS, it opens fine. However, if I do the same with the script type set to Module, it refuses to load.

## Attach a .c3p

[ModuleBug.zip](https://github.com/Scirra/Construct-3-bugs/files/6151277/ModuleBug.zip)

## Steps to reproduce

1. Download OBS or Streamlabs OBS
2. Add a browser source linked to classic.challacc.com
3. Note that it will load a green rotating square
4. Add a browser source linked to module.challacc.com
5. Note that it will not load

They are exactly the same, but one exports with classic, and the other module.

## Observed result

Only the classic will load. However, opening up a debug within OBS on the module version shows the following:

> Uncaught (in promise) TypeError: Failed to construct 'Worker': Module scripts are not supported on DedicatedWorker yet. You can try the feature with '--enable-experimental-web-platform-features' flag (see https://crbug.com/680046)
>     at RuntimeInterface.CreateWorker (main.js:29)
>     at RuntimeInterface._InitWorker (main.js:32)
>     at RuntimeInterface._Init (main.js:26)

## Expected result

I would hope that both would appear, but it seems as though they do not yet support module scripts.

## More details

 I doubt it's an issue with Construct, but if classic scripts are taken away, I will not be able to continue to support this project, or I will be unable to upgrade my Construct 3 version beyond its current version.
 
 I have no idea what to suggest. I understand the need to move forward with a more future proof solution, but at the moment I am restricted by OBS Project and Streamlabs OBS.
 
I update the online HTML on a daily basis, so having to set it from module to classic every single time is becoming a chore. Not sure why it doesn't simply save it, or have it as a choice during export.

**Comment by AshleyScirra** [comment]
This is a problem with OBS. It looks like their browser source renders using Chrome 75, which is now quite out of date. If they update it to the latest version of Chrome, it should work fine. You should contact the OBS team about that.

Can't you do a normal window/screen recording instead anyway? Or use Construct's own Game Recorder object?
