### ISSUE TITLE
[Scripting] instVars is empty on 'On Created'

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4673]
## Problem description

[Scripting] instVars is empty on `On Created`.

## Attach a .c3p

[Scripting Null on creation.zip](https://github.com/Scirra/Construct-3-bugs/files/6159480/Scripting.Null.on.creation.zip)

## Steps to reproduce

1. Preview the project
2. Press F12 on the preview application to view the log.

## Observed result

Empty instance variable list.

## Expected result

To reflect the predefined instance variables.

**Comment by AshleyScirra** [comment]
It works here. If you log `console.warn(runtime.objects.Sprite.getFirstPickedInstance().instVars.Var1);`, it logs "Value", as expected.
