### ISSUE TITLE
Plug in Bug on older files

### ISSUE THREAD

**Issue by dabontv** [Scirra/Construct-3-bugs#4674]
Some files are not updating to current plug in version. If I create a new blank file plugin is correct and shows updates, older files sometimes do not show the update. This is happening with multiple files and plug ins.

## Attach a .c3p
[Among Us Shooter.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6159537/Among.Us.Shooter.c3p.zip)

## Steps to reproduce

1. Click Add Action
2. Select LaggedAPI
3. Notice that there are a lack of options (if you open a new file and open the plug in there are more options)

## Observed result

A Lack of options in older .c3 files

## Expected result

More options reflecting the updated plug in 

## More details

![plugin-bug](https://user-images.githubusercontent.com/3484111/111156191-d5ce6400-856b-11eb-8b1f-c1f1c3403cf7.jpg)

## System details

Using Mac but have developers using windows with same issue

**Comment by AshleyScirra** [comment]
As per the bug report guidelines, in general we cannot help with problems in third-party addons. You should contact the addon developer.

The bundled addon only defines six actions, so it appears to be working correctly. You are using a bundled addon embedded in the project file though, so it's possible other projects have a different version of the addon bundled, or you have installed an updated addon which the bundled addon overrides. You can update the bundled addon in the "View used addons" dialog.
