### ISSUE TITLE
Platform behavior Interface, missing getter 'isMoving'

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4675]
## Problem description

Hi, it seems the Platform behavior Interface API is missing a getter for `isMoving`, which is important if we would be to convert events to JavaScript.

![image](https://user-images.githubusercontent.com/31282960/111540138-b755ac00-87a9-11eb-84cc-158ef05ac1d7.png)

I think we can replicate it using `vectorX` and `vectorY`, however just in case this is a missed method, I came to report.

**Comment by AshleyScirra** [comment]
Added for next release cycle.
