### ISSUE TITLE
Android APK build error when combining MobileAdvert with Firebase analytics

### ISSUE THREAD

**Issue by alan1523** [Scirra/Construct-3-bugs#4676]
When combining the the MobileAdvert object with Firebase Analytics plugin building an android debug APK hits error. 

## Attach a .c3p

[example.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6167560/example.c3p.zip)

Link to firebase plugin : https://www.construct.net/en/make-games/addons/506/firebase-analytics-in-app

## Steps to reproduce

1. Open example c3p 
2. Configure MobileAdvert object
3. Configure FirebaseAnalytics object
4. Export Android Debug APK 

## Observed result

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.

## Expected result

Debug APK would build and be available for download. 

## More details

This error started happening around March 15 2021 

## System details

<details><summary>View details</summary>

Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=~~/androidSDK (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
Using Android SDK: ~~/androidSDK
:wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
Adding classpath: com.google.gms:google-services:4.2.0
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:javaPreCompileDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:injectCrashlyticsMappingFileIdDebug
> Task :app:writeDebugApplicationId

> Task :app:processDebugGoogleServices
Parsing json file: ~~/google-services.json

> Task :CordovaLib:compileDebugRenderscript
> Task :CordovaLib:generateDebugResValues
> Task :CordovaLib:generateDebugResources
> Task :CordovaLib:packageDebugResources
> Task :app:mergeDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :CordovaLib:extractDeepLinksDebug
> Task :CordovaLib:processDebugManifest

> Task :app:processDebugManifest
~~/AndroidManifest.xml:24:9-31:50 Warning:
activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:24 to replace other declarations but no other declaration present

> Task :CordovaLib:compileDebugLibraryResources
> Task :CordovaLib:generateDebugBuildConfig
> Task :CordovaLib:javaPreCompileDebug
> Task :CordovaLib:parseDebugLocalResources
> Task :CordovaLib:generateDebugRFile
> Task :app:processDebugResources
> Task :CordovaLib:compileDebugJavaWithJavac
> Task :CordovaLib:bundleLibCompileToJarDebug

> Task :app:compileDebugJavaWithJavac

> Task :app:compileDebugSources
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:mergeDebugShaders
> Task :CordovaLib:compileDebugShaders NO-SOURCE
> Task :CordovaLib:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:packageDebugAssets
> Task :app:mergeDebugAssets
> Task :app:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:bundleLibResDebug NO-SOURCE
> Task :app:mergeDebugJavaResource
> Task :app:checkDebugDuplicateClasses FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https:/~~/command_line_interface.html#sec:command_line_warnings
30 actionable tasks: 30 executed

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
java.lang.RuntimeException: Duplicate class com.google.android.gms.internal.measurement.zzlj found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)
Duplicate class com.google.android.gms.internal.measurement.zzll found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)
Duplicate class com.google.android.gms.internal.measurement.zzlm found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)
Duplicate class com.google.android.gms.internal.measurement.zzln found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)
Duplicate class com.google.android.gms.internal.measurement.zzlp found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)
Duplicate class com.google.android.gms.internal.measurement.zzm found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)
Duplicate class com.google.android.gms.internal.measurement.zzn found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)
Duplicate class com.google.android.gms.internal.measurement.zzo found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)
Duplicate class com.google.android.gms.internal.measurement.zzp found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)
Duplicate class com.google.android.gms.measurement.internal.zzgs found in modules jetified-play-services-measurement-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement:17.5.0) and jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0)
Duplicate class com.google.android.gms.measurement.internal.zzgu found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)
Duplicate class com.google.android.gms.measurement.internal.zzgv found in modules jetified-play-services-measurement-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement:17.5.0) and jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0)
Duplicate class com.google.android.gms.measurement.internal.zzgw found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)
Duplicate class com.google.android.gms.measurement.internal.zzgx found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)
Duplicate class com.google.android.gms.measurement.internal.zzia found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)
Duplicate class com.google.android.gms.measurement.internal.zzig found in modules jetified-play-services-measurement-base-18.0.0-runtime.jar (com.google.android.gms:play-services-measurement-base:18.0.0) and jetified-play-services-measurement-impl-17.5.0-runtime.jar (com.google.android.gms:play-services-measurement-impl:17.5.0)

Go to the documentation to learn how to <a href="~~/classpath-sync-errors">Fix dependency resolution errors<~~/a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 6s
Command failed with exit code 1: ~~/gradlew cdvBuildDebug -b ~~/build.gradle

</details>

**Comment by AshleyScirra** [comment]
I'm afraid as per the bug report guidelines we cannot help with issues involving third-party addons. You'll need to contact the addon developer for help with that.

**Comment by EMI-INDO** [comment]
> When combining the the MobileAdvert object with Firebase Analytics plugin building an android debug APK hits error.
> 
> ## Attach a .c3p
> [example.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6167560/example.c3p.zip)
> 
> Link to firebase plugin : https://www.construct.net/en/make-games/addons/506/firebase-analytics-in-app
> 
> ## Steps to reproduce
> 1. Open example c3p
> 2. Configure MobileAdvert object
> 3. Configure FirebaseAnalytics object
> 4. Export Android Debug APK
> 
> ## Observed result
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:checkDebugDuplicateClasses'.
> 
> ## Expected result
> Debug APK would build and be available for download.
> 
> ## More details
> This error started happening around March 15 2021
> 
> ## System details
> View details

### FIX:  https://prnt.sc/10piaqm
