### ISSUE TITLE
Whitelist plugins

### ISSUE THREAD

**Issue by EMI-INDO** [Scirra/Construct-3-bugs#4678]
`cordova-plugin-consent@1.0.1`
`admob-plus-cordova@1.0.1`

_need info_  https://github.com/Scirra/Construct-3-bugs/issues/4657

**thank you**

**Comment by EMI-INDO** [comment]
### Sorry `consent@1.0.1` doesn't work.

Now fixed @ 2.1.0 

### Update
`cordova-plugin-consent@2.1.0`
`admob-plus-cordova@1.2.2`

### thank you

<img src="https://user-images.githubusercontent.com/78555833/112763581-41fe9c80-902f-11eb-9280-446514dfcea1.jpg" width="300" />

**Comment by AshleyScirra** [comment]
Added `cordova-plugin-consent@2.1.0` and `admob-plus-cordova@1.2.2` to the build service.
