### ISSUE TITLE
behavior without instance

### ISSUE THREAD

**Issue by Dip14u** [Scirra/Construct-3-bugs#4679]
## Problem description

When I add a "Bullet" type of behavior, and some time passes, this behavior runs out of instances. My theory is that this happens when I save my project in the browser.

## Attach a .c3p

[Nova pasta.zip](https://github.com/Scirra/Construct-3-bugs/files/6178543/Nova.pasta.zip)

## Steps to reproduce

1. Add "Bullet" behavior to a Sprite
2. Wait for a while or save the project, something happens to make the behavioral properties disappear.
3. Check the behavior properties.

## Observed result

All the behaviors of the object are without instances, that is, they stop working.

## Expected result

When the behavior properties disappear, the object stops functioning.

## More details

This problem only happens during the programming of the project in "Contruct 3 of browser"
I didn’t check other browsers, just Chrome

Broke in the latest version: r234.4

Worked on version r234 but broke on r234.4

## System details

Platform information
Browser: Chrome
Browser version: 89.0.4389.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
C3 release: r234.4 (stable)
Language setting: pt-BR

Local storage
Storage quota (approx): 17 gb
Storage usage (approx): 38 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
I assume you are referring to the object "Sprite" in the given project and selecting it in the Project Bar.

This is not a bug. The behavior properties belong to instances. There are no instances in the project. So there are no properties to show.

**Comment by Dip14u** [comment]
> Presumo que você esteja se referindo ao objeto "Sprite" no projeto em questão e selecionando-o na Barra de Projetos.
> 
> Este não é um bug. As propriedades de comportamento pertencem às instâncias. Não há instâncias no projeto. Portanto, não há valores de propriedade para mostrar.

So, how do I fix this?

**Comment by AshleyScirra** [comment]
Add an instance to the project.
