### ISSUE TITLE
Crash when moving object from global layer

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#468]
## Problem description

I created an object on a locked global layer. I realized my mistake and tried to move it using the sprite properties bar to a different layer. That's when it crashed.

## Attach a .c3p

**I've sent @AshleyScirra an email with a dropbox link for the project if he would be so kind to take a look. I couldn't reproduce it using a new project. It probably has something to do with how my layouts are and ... stuff ?**

## Steps to reproduce

1. Open the project 
2. Select Background_Weedlet from the Project panel (it is already selected in the gif)
3. Move it to the "Middleground" layer.

![globallayerbug_01](https://user-images.githubusercontent.com/7268697/26946997-c8ed986e-4c99-11e7-9a5e-988b491f42b5.gif)

## Observed result

Notice the crash.

## Expected result

No crash pls thx.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r36/main.js, line 61, col 240197
Message: Uncaught Error: cannot move to overriden layer
Stack: Error: cannot move to overriden layer at u.ǃius (https://editor.construct.net/r36/main.js:61:240203) at r.ǃrZ (https://editor.construct.net/r36/main.js:61:204844) at l.ǃ$a (https://editor.construct.net/r36/components/bars/propertiesBar/propertiesBar.js:1:22039) at ǃi.ǃp.ǃK.ǃg_.ǃiYr (https://editor.construct.net/r36/main.js:2:437556) at ǃi.ǃp.ǃK.ǃiWn.ǃiYQ (https://editor.construct.net/r36/main.js:2:417564) at ǃi.ǃp.ǃK.ǃiWn.ǃay (https://editor.construct.net/r36/main.js:2:417968) at HTMLSelectElement.ǃiYG (https://editor.construct.net/r36/main.js:2:416930)
Construct 3 version: r36
URL: https://editor.construct.net/index.html
Date: Thu Jun 08 2017 22:12:52 GMT+0300 (GTB Daylight Time)
Uptime: 17697.1 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Looks like something to do with the global layers system, assigning to Diego.

**Comment by DiegoScirra** [comment]
Fixed in r38.
