### ISSUE TITLE
Missing 'select mode' in properties bar When Container Object Select mode to All

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4680]
## Problem description

This may not be a error, but it may have been forgotten to include functionality in the design.

If more than one object is added to the container and change the selection mode to 'ALL'. When you select it again, there is no option for container in the properties bar.

Since I think this is a design flaw, I'm not making suggestions, I'm reporting bugs.

![container_properties_bar_01](https://user-images.githubusercontent.com/45864744/112112810-f4c69900-8bf0-11eb-8972-b8775b522f75.jpg)
)

![container_properties_bar_02](https://user-images.githubusercontent.com/45864744/112112822-f7c18980-8bf0-11eb-9f76-cc9caadf48c2.jpg)

## Attach a .c3p

[container_properties_bar.zip](https://github.com/Scirra/Construct-3-bugs/files/6187831/container_properties_bar.zip)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. The container properties are only shown when a single object type is selected, and if you select multiple object types, they cannot be shown. You can use Alt+Click to select a single instance in a container ignoring the select mode to access the full list of properties again.

**Comment by XHXIAIEIN** [comment]
When I Click Container first, Then use Alt+Click to select a single instance, It doesn't happen.  but If I click on the scene first, It's working fine. 

## Steps to reproduce
1. select mode:  All 
2. Click any instance, 

![container_select_all](https://user-images.githubusercontent.com/45864744/112128833-c4d3c180-8c01-11eb-9997-f43b4d4d144a.jpg)

**Comment by AshleyScirra** [comment]
Yes, that is by design.
