### ISSUE TITLE
Preview Options Crashes

### ISSUE THREAD

**Issue by Dienamik** [Scirra/Construct-3-bugs#4683]
## Problem description
 Crashes every time I click on any of the preview options on any files: my projects, the demos, and examples.

## Attach a .c3p

[example.zip](https://github.com/Scirra/Construct-3-bugs/files/6194567/example.zip)

## Steps to reproduce

1. Open any project file.
2. Click on the preview

## Observed result

Crashes appear

## Expected result

See the preview of the project.

## More details

**Affected browsers/platforms:** 

**First affected release:** 
I tested on Chrome, Edge and Firefox. From stable r234.4 to the recent stable version (r241) crashes. From stable r234.3 to any previous stable version, and any of the beta version works fine; doesn't crash when I preview. The anti-virus on or off the result is the same.

## System details

Error report information
Type: unhandled rejection
Reason: Event 'error': [object Event]
Construct 3 version: r241
URL: https://editor.construct.net/
Date: Tue Mar 23 2021 22:35:26 GMT-0700 (Pacific Daylight Time)
Uptime: 2421.5 s

Platform information
Browser: Chrome
Browser version: 89.0.4389.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It works fine for me.

Do you have any browser extensions installed? Does disabling them fix the issue?

Can you press F12 and check the browser console for any further error messages?

**Comment by Dienamik** [comment]
I have them installed. I just disabled and removed them but still crash. I
checked on the console and I'm getting these errors (see attached file).

But there's good news. There was an update windows, and after I did that,
it started working properly again. My issue with the preview options is
solved by updating my windows.

Realizing it now, I remember I was able to preview with r234.4 before. The
issue started after the previous windows update about a month ago.


-Joseph

**Comment by AshleyScirra** [comment]
I'm afraid without further details - particularly the browser console messages (I don't see any attachment) - there is nothing we can do, so closing.

It's unlikely Windows Update affected this, since our code runs in the browser, not directly on Windows. I suspect this is a false correlation, which is fairly common.
