### ISSUE TITLE
error when exporting

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#4684]
Exporting to NW.js (v0.47.0) gives the message "failed to export project. Check the browser console for more error details".

Browser console says:

main.js:2120 Error exporting:  Error: error fetching https://downloads.scirra.com/c3-nwjs/v0.47.0/linux32.zip (0 )
    at XMLHttpRequest.y.onerror (main.js:255)
Ehb @ main.js:2120
downloads.scirra.com/c3-nwjs/v0.47.0/linux32.zip:1 Failed to load resource: net::ERR_FAILED
main.js:2120 Error exporting:  Error: error fetching https://downloads.scirra.com/c3-nwjs/v0.47.0/linux32.zip (0 )
    at XMLHttpRequest.y.onerror (main.js:255)
Ehb @ main.js:2120
downloads.scirra.com/c3-nwjs/v0.47.0/linux32.zip:1 Failed to load resource: net::ERR_FAILED

## Attach a .c3p

When I open a new project and export the new (empty) project, I get the same error message.

- export project
- select deduplicate and recompress
- select minify mode "none"
- select win32,win64,lin32,lin64
Then when the dialog says "adding files", the error message shows.

## Observed result

Error message.

## Expected result

An exported project.

## More details

**Affected browsers/platforms:** 
I am using Chrome.

**First affected release:** 
Right now using 241. It worked before, 1, 2 or 3 beta versions ago.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 89.0.4389.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 38 gb
Storage usage (approx): 2 gb (5.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It works fine for me.

The console error message is saying it failed to load the linux32 version here: https://downloads.scirra.com/c3-nwjs/v0.47.0/linux32.zip
This link works fine though if I click on it. I would guess there was a problem with your Internet connection and you could not download the NW.js version at the time you tried.
