### ISSUE TITLE
Variable name doesn't update in Function parameter 

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4685]
## Problem description

Changing a global/local variable's name doesn't update the variable name in any Function calls referencing it. 

## Attach a .c3p

https://drive.google.com/file/d/1n-qnAQpmA47xeN94Tw5ld8nhZocRm0z6/view?usp=sharing

## Steps to reproduce

1. Open the attached project.
2. Change the name of either the Global Variable or the Local Variable in the group.
3. Notice that the name of that variable doesn't change in the Function calls that pass on that variable.
4. Undo your name change.
5. Notice that the variable name in the Function call now changes to the changed name, despite that change being undone. 

## Observed result

The names of the variables in Function calls aren't reflective of their true names, and seem to be one step behind.

## Expected result

The names of the variables in Function calls match the names of the variables themselves.

## More details

**Affected browsers/platforms:** Chrome 89.0.4389

**First affected release:** r241

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report. It looks like it's purely cosmetic and everything otherwise keeps working as expected, so it's not too severe, but I'll make sure the name gets updated properly.

**Comment by brushfe** [comment]
Glad it's helpful! (and that it's cosmetic)

**Comment by AshleyScirra** [comment]
Thanks for the report, should be fixed in the next beta.
