### ISSUE TITLE
C3 No longer opens my project saved in the folder 

### ISSUE THREAD

**Issue by lucasgc1** [Scirra/Construct-3-bugs#4686]
## Problem description
C3 No longer opens my project saved in the folder

I am not able to open my project saved in the folder after I updated the C3 it gives this error below and does not open the folder with my project anymore what to do?

Error report information

Type: unhandled rejection

Reason: Error: A requested file or directory could not be found at the time an operation was processed.

Construct 3 version: r241

URL: editor.construct.net

Date: Wed Mar 24 2021 19:16:04 GMT-0300 (Horário Padrão de Brasília)

Uptime: 18.3 s

Platform information

Browser: NW.js

Browser version: 0.51.0

Browser engine: Chromium

Browser architecture: 64-bit

Context: nwjs

Operating system: Windows

Operating system version: 8.1

Operating system architecture: 64-bit

Device type: desktop

Device pixel ratio: 1

Logical CPU cores: 2

Approx. device memory: 2 GB

User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.51.0 (like Chrome/88.0.4324.96)

C3 release: r241 (stable)

Language setting: pt-BR

WebGL information

Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)

Numeric version: 2

Supports NPOT textures: yes

Supports GPU profiling: no

Supports highp precision: yes

Vendor: Google Inc.

Renderer: Google SwiftShader

Major performance caveat: yes

Maximum texture size: 8192

Point size range: 0.125 to 2048

Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help unless you follow the bug report guidelines. We need that information to be able to help.

You can also try pressing F12 to see if any additional error details appear in the browser console.
