### ISSUE TITLE
Documentation correction for Timer behavior

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-3-bugs#4688]
There are conditions and actions in the Timer behavior that are not documented in the Construct 3 manual (https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/timer).

**Conditions:**
Is timer paused
Is timer running

**Actions:**
Pause/resume timer

![Conditions](https://user-images.githubusercontent.com/59319082/112605900-75b7a780-8e20-11eb-982a-221db9172f05.png)
![Actions](https://user-images.githubusercontent.com/59319082/112605917-794b2e80-8e20-11eb-8507-7804472605ad.png)
![Documentation](https://user-images.githubusercontent.com/59319082/112605931-7c461f00-8e20-11eb-8a6f-992c48865f28.png)

**Comment by AshleyScirra** [comment]
Thanks for spotting this. I've updated the documentation to include all the features.
