### ISSUE TITLE
Fallback icon is created wrongly, when using Adaptive Icons

### ISSUE THREAD

**Issue by fredriksthlm** [Scirra/Construct-3-bugs#4689]
## Problem description

When using adaptive icons there should also be a "fallback" icon, which will be used for Android versions that cannot use the adaptive ones. This other (legacy) icon should be the one you classify as "App icon" in Construct. But instead it is the Foreground icon that will be used as fallback. Making tha icon look quite odd on old devices.

## Steps to reproduce

1. Create a new project
2. Import the adapative foreground and background icons into the icon folder. Classify them as Adaptive foreground and Adaptive background.
3. Import also a "fallback icon" and classify it as App Icon, in Icons folder.

## Observed result

For all Android v26 and above the icon looks fine on the devices. It will use the Adaptive one.
For Android below 26 the icon will be the foreground image, instead of the App icon. Which is incorrect.

## Expected result

For Android below 26 it should be the App Icon you see as icon on your device.

## More details

I export as Android Studio project, but I guess the result is the same if you build with C3 build service.

In Android Studio the "issue" is very easy to observe!

![image](https://user-images.githubusercontent.com/76128871/112727217-af240c00-8f21-11eb-8c78-0a311b9df52b.png)

The red arrow _should_ have been the App Icon, instead it is the Foreground icon from Construct.

This is the actual file. (It is the file classifed as Adaptive foreground, but should be the App icon):
PROJECT\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png

**Affected browsers/platforms:** 

Android below v26.

**First affected release:** 

I'm not sure when this started, maybe it has been since Adaptive Icons was introduced?

Today I just saw it with latest C3, latest Android Studio.
Exported as 6.0 (v23)

**Comment by EMI-INDO** [comment]
### Cordova CLI


![2021-03-28_020910](https://user-images.githubusercontent.com/78555833/112731849-f4b8f700-8f6a-11eb-89a9-f3ab79f8bf8b.png)

**Comment by AshleyScirra** [comment]
I think this is beyond our control: we tell Cordova the configuration, including the adaptive icon and app icons (which I had thought were already used as the fallback), and Cordova does everything else. I think it would be best to report this to cordova-android directly here: https://github.com/apache/cordova-android

**Comment by fredriksthlm** [comment]
> 

@AshleyScirra . I now found the solution (which is in fact sort of documented by Apache).

In the config.xml created from Construct you export the following:

`<platform name="android">
<icon foreground="www/icons/foreground.png" background="www/icons/background.png" density="xxxhdpi" />
</platform>
`

If adaptive icons is defined in the Android platform tag, the fallback will be the foreround icon, if no source is specified. Regardless if a source icon is defined outside the android platform tag, which it is in construct3 config.xml.

The solution to get the correct fallback icon is to also add the legacy icon to the android platform icon tag. Like this:

`<platform name="android">
<icon density="xxxhdpi" background="www/icons/background.png" foreground="www/icons/foreground.png" src="www/icons/legacy.png" />
</platform>
`



It is actually explained here, even if it is a bit cryptic.
https://cordova.apache.org/docs/en/latest/config_ref/images.html

(Is it possible for me to re-open this ticket?)

**Comment by AshleyScirra** [comment]
I'll take a look.

**Comment by AshleyScirra** [comment]
The Cordova documentation appears to contradict itself - it starts by saying:

> The `src` attribute is not used for adaptive icons.

But then further down does say that the `src` attribute is used, both for image icons and vector icons!

> The fallback icon can be overridden by setting the src attribute.

Based on the latter I have updated the next beta to set the `src` attribute of adaptive icons to a same-sized icon with the "App icon" purpose if one exists in the project. It's tricky to test but it should be configured correctly, so hopefully Cordova/Android will do the right thing with it.
