### ISSUE TITLE
Crash when setting tilemap width to 200

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#469]
## Problem description

Crash when setting tilemap width to 200

## Attach a .c3p

I used the Tilemap sample project from C3 by using the search.

## Steps to reproduce

1. Select the tile map
2. Change the width to 200

## Observed result

Crashes

![tilemapcrash](https://user-images.githubusercontent.com/7268697/26948184-22ad2ec4-4c9e-11e7-9783-c4b15682907e.gif)

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r36/main.js, line 2, col 175274
Message: Uncaught TypeError: expected finite number
Stack: TypeError: expected finite number at Function.ǃi.ǃio (https://editor.construct.net/r36/main.js:2:175280) at k.ǃYK.ǃzhc (https://editor.construct.net/r36/plugins/tilemap/plugin.js:1:4009) at k.ǃYK.ǃzhh (https://editor.construct.net/r36/plugins/tilemap/plugin.js:1:3797) at k.ǃYK.ǃzhB (https://editor.construct.net/r36/plugins/tilemap/plugin.js:1:3188) at j.ǃYJ.ǃYn (https://editor.construct.net/r36/plugins/tilemap/plugin.js:1:6599) at r.ǃOU (https://editor.construct.net/r36/main.js:61:199373) at o.ǃlC (https://editor.construct.net/r36/components/bars/propertiesBar/propertiesBar.js:1:28319) at ǃi.ǃp.ǃK.ǃg_.ǃiYr (https://editor.construct.net/r36/main.js:2:437556) at ǃi.ǃp.ǃK.ǃiYD.ǃiYQ (https://editor.construct.net/r36/main.js:2:404215) at ǃi.ǃp.ǃK.ǃiYD.ǃay (https://editor.construct.net/r36/main.js:2:410707)
Construct 3 version: r36
URL: https://editor.construct.net/
Date: Thu Jun 08 2017 22:58:10 GMT+0300 (GTB Daylight Time)
Uptime: 50.4 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
I can not reproduce this one in my development build, but it does happen in the latest version in construct.net.

Lately I have been working in the Tilemap plugin and Tilemap Bar, so I might already have fixed this one by accident :P 

Make sure to check r37 when it is released.

**Comment by JeFawk** [comment]
It was fixed it seems in r37
