### ISSUE TITLE
Please help! "Error Type: unhandled rejection",  "Reason: Event 'error': [object Event]",  "Construct 3 version: r241". I can not Run the Game? 

### ISSUE THREAD

**Issue by NaradProduction** [Scirra/Construct-3-bugs#4690]
Error report information

Type: unhandled rejection
Reason: Event 'error': [object Event]
Construct 3 version: r241
URL: https://editor.construct.net/
Date: Sun Mar 28 2021 18:04:56 GMT+0900 (Japan Standard Time)
Uptime: 126 s
Platform information

Browser: Firefox
Browser version: 85.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
C3 release: r241 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help without more information. Please see the bug report guidelines - we need that information to be able to help.
