### ISSUE TITLE
Some of exporters don'T work with fullscreen mode "OFF"

### ISSUE THREAD

**Issue by eleanorjmorel** [Scirra/Construct-3-bugs#4691]
## Problem description
Some exporters don'T work with export set to off, notably, scirra arcade, Android, IOS

![image](https://user-images.githubusercontent.com/32940085/112748559-55a3f780-8f8a-11eb-9db6-da75611222aa.png)

## Attach a .c3p
https://drive.google.com/file/d/1sEvCzDkvE9rJ7IYhE6DYRG5mPBgjQ29n/view?usp=sharing

## Steps to reproduce
export using scirra arcade, ios or android
## Observed result

![image](https://user-images.githubusercontent.com/32940085/112748592-a9aedc00-8f8a-11eb-9735-a1a2d6e653a3.png)

## Expected result
sucessful export

## More details

what'S the point of making a custom fullscreen mode by manipulating canvas size and layout scale if the platforms that need it most (mobile) don't support it

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
As the message indicates, this is currently intentional.
