### ISSUE TITLE
Properties description text appearing cancels clicked selections and moves bar up

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#4696]
## Problem description

Clicking on fields at the bottom of the visible portion of the Properties Bar causes the selection to be "canceled" as the properties description text box appears to overlap where the selected field was in time to "block" the user's click, scrolling the bar a short distance away such that the user has to click on the desired field (such as the "Show meshes" checkbox) a second time.

## Attach a .c3p

[Sad Project.zip](https://github.com/Scirra/Construct-3-bugs/files/6239565/Sad.Project.zip)

## Steps to reproduce

1. Open any project or create a new one.
2. In the Properties Bar, scroll to a point where a listed field (such as a checkbox, or the "More information - Help" button at the bottom for many selections in Construct) is at the bottom of the visible part of the Properties Bar.
3. Click on that field in the Properties bar, noting that the selection will not be accepted (checkboxes not toggled, buttons not considered pressed, etc.) if the description text that appears for it would overlap the point where you clicked, and the Properties Bar will scroll up to make room for that description text so you'll need to move the cursor up to the field and click it a second time.

## Observed result

Selections in the Properties Bar are canceled when clicked near the bottom of the bar.

## Expected result

The selection is accepted and works. For example when clicking a checkbox field, it toggles the checkbox, even if the description text for that field then pops up afterward.

## More details

**Affected browsers/platforms:** 
Chrome, Firefox.

**First affected release:** 
r241 at latest.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 89.0.4389.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 70 gb
Storage usage (approx): 148 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Unfortunately this is a pretty much unavoidable consequence of resizable UI sections. I've been aware of it for some time but I don't think there is any good solution to it. If the UI resizes and blocks the mouse cursor, the mouse input no longer reaches the content underneath (by design). Even if a short delay is added before showing the description, since the mouse down selects the property and shows the description, and the mouse up will sometimes perform another interaction e.g. changing the selection of a checkbox, then the mouse up is still blocked by the change caused by the mouse down. So I don't think there is really anything that can be done about this. It's a pretty minor issue anyway - usually you just need to click again and it works.

**Comment by ChromeWisp** [comment]
Ashley, I understand that this is closed now, but as this is an issue that continues to happen (to at least myself and one other friend that I know personally) _many times over a day_ and becomes extremely frustrating usability-wise - even moreso for anyone who has docked another window like the Z Order bar in the lower left corner as I have, leading to more commonly having to scroll through the properties bar to select or toggle a field near the bottom of the visible area of the properties bar, and therefore having user input ignored for the sake of an information box popping in instead. I may not understand why the properties have to resize before the user's desired input is processed instead of after it by design as you've explained, but I think there are solutions that may potentially not be much trouble to implement and which could be worth considering?

1. After years of using C3 a user might not _need_ the information box to pop up and resize the properties bar. After learning what the "fullscreen quality" dropdown or "initially visible" checkbox fields do for example, they may not want to see the info box pop up to explain it to them again every time going forward in the first place and would be more than willing to visit the well-documented features in the manual as is standard procedure for learning and remembering the rest of Construct 3's functionality anyway? Instead, what if users simply had a checkbox in C3's settings for these property info boxes that is on by default for the sake of new users but can be toggled off for users down the road when they're familiar with what they're doing?

2. In some places within C3's environment, information about something in the interface is found by hovering the mouse over the relevant field or button (such as hovering over an event sheet tab to see which project it's part of or over a function to see the description text you've written for it at a glance). Could the same effect be applied to the properties of the properties bar such that instead of a box appearing when you try to interact with a field, you just hover over it to see information pop out above the bar where it can't cancel the user's input? It would be in line with other parts of the UI that use this method of explaining a feature, too. This could, like the last proposed idea, also just be a setting users can choose for themselves. I think this one might be a great solution since it provides the informational hint that the properties info box does but without ever canceling their input.

3. Have the properties info box _always_ be visible at the bottom of the properties bar, and instead of automatically resizing when a property is clicked (since some properties' explanations take more or fewer lines of text to explain), it stays a fixed size but the divider line at its top can be dragged (like any other bar's borders, or the dividers between the columns in the 'Find Results' bar) up to resize it manually to make room for longer explanation texts which might otherwise be cut off near the end _or_ dragged down far enough that none of the text is visible for maximum room in the properties bar for the properties themselves. Again there could also be a setting to toggle whether the info box resizes on its own as it currently does, or whether it can instead be resized manually, allowing it to be moved out of the way for users and even brought back up in a case-by-case basis if they do need a reminder of how some property works but don't want to visit the manual. In manual mode, the box will never pop up to resize the user's desired click target out of the way of their click.

4. As an option that takes the place of the properties info box, there's instead a thin box with text that reads as the name of the last-clicked property followed by a "Help" button (like the kind seen when adding a new object type or select a condition or action for events) which redirects to the manual page relevant to that property, scrolled directly to the part of the page that explains it in full detail. This kind of box would ideally never need to resize/reposition the properties bar when properties are clicked as the size of its contents stay the same.

I know it might not seem like a serious issue but to any users like me in terms of workflow or interface layout especially, it does come up frequently, even more when using C3 40 hours a week for work... I really, truly appreciate your patience even just in reading this all and I know that a lot is asked of Scirra and there's only limited time and resources, and by no means do I think my issue is the highest-priority item, but rather I just hope you might eventually consider some alternative solutions or work-arounds like I've taken some time to write up here if you ever find a moment to address it.
