### ISSUE TITLE
Animation editor rectangle selections under UI makes them unusable

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#4697]
## Problem description

In the Animations Editor, after using rectangle select or the select all shortcut (Ctrl+A) to make a selection, if the selection is ever positioned underneath/behind other Animations Editor UI (such as the crop or resize buttons, animations properties fields, or color palette) that UI cannot be interacted with as clicking there will instead be considered as though dragging the rectangle selection.

## Attach a .c3p

[Sad Project.zip](https://github.com/Scirra/Construct-3-bugs/files/6239680/Sad.Project.zip)

## Steps to reproduce

1. Open a project containing a sprite or create a new project and a sprite in that project.
2. Double-click the sprite to open the Animations Editor.
3. Use the rectangle select tool to select an area.
4. Click and drag the selection to move it behind other Animations Editor UI elements such as the crop button.
5. Attempt to click on or use that UI, noting that instead you can only click and drag the rectangle selection while it's there.

## Observed result

Animations Editor UI could not be used while it overlaps a rectangle selection.

## Expected result

Animations Editor UI can be used while it overlaps a rectangle selection.

## More details

**Affected browsers/platforms:** 

Chrome, Firefox.

**First affected release:** 

r241 at latest.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 89.0.4389.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 70 gb
Storage usage (approx): 149 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
