### ISSUE TITLE
'Restart layout' action does not reset layer properties

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#4698]
## Problem description

The system action 'restart layout' does not set layer properties (such as background color for example) back to their initial states as it does to objects.

## Attach a .c3p

[NoLayerRestart.zip](https://github.com/Scirra/Construct-3-bugs/files/6239791/NoLayerRestart.zip)

## Steps to reproduce

1. Open the NoLayerRestartProject and preview it.
2. In 3 seconds, the background layer will change color to green.
3. Press the 'Restart Layout' button, observing that the background layer's background color does not revert to gray.

## Observed result

Layers within a layout don't get reset upon 'Restart Layout' action.

## Expected result

Layers within a layout do get reset upon 'Restart Layout' action, like the objects within the layout do.

## More details

I'm not 100% sure if this is intentional or not, as the manual page on system actions doesn't go into extreme detail on what all 'Restart layout' is meant to do but as it is specified that 'Reset global variables' is used to reset global variables, it seems like if resetting layers is meant to be separate from 'Restart layout', it would be its own action? If this is not a bug but intentional, could I suggest a 'Restart layers' property to use in conjunction with 'Restart layout' just as 'Reset global variables' is designed for?

**Affected browsers/platforms:** 
Chrome, Firefox.

**First affected release:** 
r241 at latest.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 89.0.4389.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 70 gb
Storage usage (approx): 150 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think this was originally an intentional design: layer properties are effectively global. Unfortunately by this point, changing it would be a major breaking change affecting hundreds, maybe thousands of existing projects, so it's not something we can consider changing as-is. If you'd like to file a suggestion you can do so here: https://construct3.ideas.aha.io/
