### ISSUE TITLE
READ-ONLY MODE

### ISSUE THREAD

**Issue by EMI-INDO** [Scirra/Construct-3-bugs#4699]
### Sorry this is not a bug.

**Since last year my seller account is like this**

I must have done something wrong before.

account `EMI_INDO`
Active ban ID` 2482`

thank you

![2021-04-01_232258](https://user-images.githubusercontent.com/78555833/113331666-6cf83180-934a-11eb-99f4-59dcfbb86964.png)

**Comment by AshleyScirra** [comment]
Please contact support@scirra.com for issues with your account.
