### ISSUE TITLE
Double-click Create Object Crashed

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#47]
## Problem description

Creates 2 Objects when you double-click on "insert" button on the new object creation window.

## Steps to reproduce

1. Double-click on Layout view's empty space.
2. Select object like "Touch" that can only be 1 in a project.
3. Double-click on the "Insert" button.

## Observed result

Crashed or created two objects of the same thing.

## Expected result

Should not be able to create 2 objects.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: single-global plugin already in project
Stack: Error: single-global plugin already in project at window.ǃpsQ.ǃtc (https://editor.construct.net/r16/main.js:61:416802) at app.ǃCq.then.le (https://editor.construct.net/r16/main.js:63:421404)
Construct 3 version: r16
URL: https://editor.construct.net/index.html
Date: Sat Apr 08 2017 16:47:53 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 630.6 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
The fix for this will be in r17.

The bug was affecting all objects types.
