### ISSUE TITLE
Collisions stop between stationary and moving objects

### ISSUE THREAD

**Issue by ephrisian** [Scirra/Construct-3-bugs#470]
## Problem description

Collision between stationary solid and solid in motion cause the collisions to fail.

## Attach a .c3p

https://www.dropbox.com/s/18daaxngvw817gc/sticker.c3p?dl=0

## Steps to reproduce

1. Create sprite_floor with Solid and Physics (Immovable) behavior
2. Create sprite_player with Platformer behavior
3. Create sprite_playerC smaller than sprite_player with Physics (Immovable) and Pin behavior
4. Create sprite_stick with Physics behavior
5. Add Event, On Start of Layout -> Pin sprite_playerC to sprite_player
6. Run into sprite_stick several times

## Observed result

Collisions will cease after several interactions between the objects

## Expected result

Collisions should be continuous

## Affected browsers

* Chrome: yes
* Firefox: N/A
* Edge: N/A
* Safari: N/A

## System details

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r36
Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 24 mb (0.1%)
Persistant storage: No
Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.
•	CSS element() is not supported.
•	Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:
•	EXT_color_buffer_float
•	EXT_disjoint_timer_query_webgl2
•	EXT_texture_filter_anisotropic
•	OES_texture_float_linear
•	WEBGL_compressed_texture_s3tc
•	WEBGL_debug_renderer_info
•	WEBGL_debug_shaders
•	WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:
•	Ogg Opus (audio/ogg; codecs=opus)
•	WebM Opus (audio/webm; codecs=opus)
•	Ogg Vorbis (audio/ogg; codecs=vorbis)
•	WebM Vorbis (audio/webm; codecs=vorbis)
•	MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
•	MP3 (audio/mpeg)
•	FLAC (audio/flac)
•	PCM WAV (audio/wav; codecs=1)
Supported encode formats:
•	WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:
•	WebM VP9 (video/webm; codecs=vp9)
•	WebM VP8 (video/webm; codecs=vp8)
•	Ogg Theora (video/ogg; codecs=theora)
•	H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:
•	WebM VP9 (video/webm; codecs=vp9)
•	WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
Closing, please see the notes about mixing Physics and other behaviors in the physics tutorial: https://www.scirra.com/tutorials/64/physics-in-construct-2-the-basics
