### ISSUE TITLE
Guide tours (Ru)

### ISSUE THREAD

**Issue by ReviveR200** [Scirra/Construct-3-bugs#4701]
## Problem description

It is impossible to correctly enter the expression for the coordinates of Mouse when passing the Guide tour in Russian.

## Attach a .c3p

Guide tour in Construct 3

## Steps to reproduce

1. Guide tour

## Observed result

Everything is good in English
![En](https://user-images.githubusercontent.com/62239715/113397320-453eb300-93b6-11eb-8b28-d2ed11983c96.PNG)

But it does not work in Russian, because there is no object with that name (since the object is named in Russian)
![Ru1](https://user-images.githubusercontent.com/62239715/113397459-86cf5e00-93b6-11eb-83c2-3a98e5f30ca9.PNG)
![Ru2](https://user-images.githubusercontent.com/62239715/113397468-8a62e500-93b6-11eb-9639-f47f44202a6d.PNG)

If you enter the name of the object in Russian, then after clicking "Next" the names are automatically changed to English
![Ru3](https://user-images.githubusercontent.com/62239715/113397561-aa92a400-93b6-11eb-926c-441c8fdbcbd3.PNG)
![Ru4](https://user-images.githubusercontent.com/62239715/113397575-acf4fe00-93b6-11eb-9731-6bc4a9d169a5.PNG)

**Comment by AshleyScirra** [comment]
This looks like a mistake in the translation. The expression is taken from the key `text.tours.beginnersguide.steps.add-action-1.x-value`, which still says `Mouse.X` in the Russian translation. A Russian language contributor will need to fix it. See also the Russian translation forum here: https://www.construct.net/en/forum/construct-3/k-ru-ru-15
