### ISSUE TITLE
Canvas size set is bugged

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4704]
## Problem description
Searched similar bugs and manual, but there was no info.

Case user likes to set canvas size, then setting canvas size bigger then default works, but when decreasing canvas size, canvas start shifting instead cropping.

## Attach a .c3p
[Main_Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/6255382/Main_Bug.zip)

## Steps to reproduce

1.Start example, drag preview window bigger. Close preview
2.Navigate to eventsheet, disable last event and enable event above it
3.Preview, drag window bigger

## Observed result
When canvas size is decreased, it start shifting and is not cropped.  Object should stay at their position and not move with it.

## Expected result
Size of canvas should be allowed be changed, with fullscreen scaling modes ON or OFF.

PS: i checked my old project it's possible to change canvas correctly, but it need more events. Still, correct way for canvas should be crop and not scroll/shift.

## More details

If user likes to keep canvas at "EVEN" size, lets say 650x650 and not 651x649. Then it's seems impossible. It could be 'somewhat' possible with fullscreen OFF, but it lacks features to make usable in most cases.

If canvas size is increased and having scaling mode 'ON' : canvas size triggers multiple times, to account chrome wrong window calculcation. User still ends up with ODD and EVEN canvas size.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 89.0.4389.90
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
C3 release: r242 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.2 gb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This just looks like a mistake in your events. You either always make the canvas size bigger, or always make it smaller, ignoring the actual size of the window. I think you meant to use the window inner size.

**Comment by SnipG** [comment]
Idk if you saw the original problem or not, can't read it out from comment. I add image to show issue clearly.

It's not issue for me and i can fix it, but overall should it happen like this or not?
![nice4](https://user-images.githubusercontent.com/28864889/113726737-27968400-96fd-11eb-84b8-2965f7d10bd6.jpg)

**Comment by AshleyScirra** [comment]
The events in the project don't make any sense. When the browser window resizes, you just keep making the canvas growing bigger and bigger, regardless of whether the window is getting bigger or smaller. So it just looks like your events are wrong.

**Comment by SnipG** [comment]
They are there to show, if you increase canvas. X:0 Y:0 and image is correct, now matter how big it gets. While decreasing, it wrecks canvas and viewport align

**Comment by SnipG** [comment]
If red sprite location is for example 500,500 and you decrease canvas size. It should not move sprite, instead cut it out as if canvas, is small enough, location 500,500 is outside it
![aaaaaaa](https://user-images.githubusercontent.com/28864889/113730915-fae46b80-9700-11eb-82ab-cf64594a6b57.jpg)

**Comment by AshleyScirra** [comment]
If the events don't make sense, and the results don't make sense, the assumption is you're just doing something weird and getting a weird result. You should focus issue reports on legitimate use cases to make it clear what you're trying to do and why it's not working like you want.

**Comment by SnipG** [comment]
Before i abadon this case for future users to handle:

If i got canvas 1000x1000 and i decrease it size on start of layout to 300x300, should i see object on 500x500? And should top-left corner to be 0,0 or 153,143? Which are right?





Correct answers are: You can see 500x500 object and top-left corner is 140,232 and not 0,0
