### ISSUE TITLE
setting texture1 to current render texture

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4705]
## Problem description
Because I didn't find any issue with any feedback, if it's bug or not. So I will post this here.

Case user puts some shaders together that bugs C3 out. 
Why i put this here? Because if this happens, user cannot get his project back. Each time user opens, it crashes. Safe mode also fails to open project, maybe because custom shader was used and it's disabled now. Which will block opening.
So what is C3 solution for such case?
One could be, edit shader and upload back. But should error happen or not?
Crash report in 'System details'

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>
Error report information
Type: assertion failure
Message: Warning: setting texture1 to current render texture
Stack: Error at Function.bXa (https://editor.construct.net/r242/main.js:285:41) at https://editor.construct.net/r242/main.js:200:259 at Object.vva (https://editor.construct.net/r242/main.js:1440:265) at Function.Nnb (https://editor.construct.net/r242/components/editors/layoutView/layoutView.js:89:448) at q.Cf (https://editor.construct.net/r242/projectResources.js:627:243) at r.Cf (https://editor.construct.net/r242/projectResources.js:596:417) at Object.Gvd (https://editor.construct.net/r242/components/editors/layoutView/layoutView.js:13:455) at https://editor.construct.net/r242/components/editors/layoutView/layoutView.js:4:236
Construct 3 version: r242
URL: https://editor.construct.net/r242/
Date: Mon Apr 05 2021 06:00:33 GMT+0300 (Eastern European Summer Time)
Uptime: 11.2 s

Platform information
Browser: Chrome
Browser version: 89.0.4389.90
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
C3 release: r242 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help unless you follow the bug report guidelines. We need that information in order to investigate.

**Comment by SnipG** [comment]
[causes_crash.zip](https://github.com/Scirra/Construct-3-bugs/files/6265377/causes_crash.zip)

Reproduce steps:
1. Add shader
2. Open new project
3. select layer, add shader 'darken'
4. add this custom shader
5. See crash
