### ISSUE TITLE
[r242] - Different behavior between export to HTML5 and WebView2 - window.moveTo(x,y)

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#4708]
## Problem description

This JS code works fine in previewing and exporting as HTML5 but does not work in WebView2:

**globalThis.moveTo(x, y)** - reference: [https://developer.mozilla.org/en-US/docs/Web/API/Window/moveTo](https://developer.mozilla.org/en-US/docs/Web/API/Window/moveTo) (i tested with _Use Worker: NO_

 ```js
globalThis.moveTo(0, 0);
```

## Attach a .c3p

[test-globalThis.move(x,y).c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6259519/test-globalThis.move.x.y.c3p.zip)

exported for win64: [test-globalThis.move(x,y).zip](https://github.com/Scirra/Construct-3-bugs/files/6259539/test-globalThis.move.x.y.zip)

## Steps to reproduce

Open the project in preview mode (I tested with _popup window_). Then try with export in WebView2

## Observed result

Preview/HTML5: The window move to position (0,0)
WebView2: The window doesn't move

## Expected result

WebView2: The window move to position (0,0)

## More details

**Affected browsers/platforms:** Window WebView2

**First affected release:** r238? r242

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm not sure if this is a bug or a missing feature in WebView2, but I filed an issue for this here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1153

To be honest, this is a pretty obscure API. It looks like it no longer works in tabbed browsers, so it probably has little usage in practice. So I should warn you that based on this Microsoft may decide it's not worth supporting in WebView2.
