### ISSUE TITLE
[r242] - Different behavior between export to HTML5 and WebView2 - Notification("Hello")

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#4709]
## Problem description

This JS code works fine in previewing and exporting as HTML5 but does not work in WebView2:

Notification() - reference: [https://developer.mozilla.org/en-US/docs/Web/API/Notification](https://developer.mozilla.org/en-US/docs/Web/API/Notification)
```js
if (!("Notification" in globalThis)) {
 alert("This browser does not support desktop notification");
}
else if (Notification.permission === "granted") {
 const notification = new Notification("Hello!");
}
else if (Notification.permission !== "denied") {
  Notification.requestPermission().then(function (permission) {
    if (permission === "granted") {
      const notification = new Notification("Hello!");
   }
 });
}
```

## Attach a .c3p

[testNotification.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6259635/testNotification.c3p.zip)

WebView2: 
[testNotification.zip](https://github.com/Scirra/Construct-3-bugs/files/6259637/testNotification.zip)

## Steps to reproduce

Click button

In preview and html5 export you see a desktop notification. In WebView2 no.

## Expected result

In WebView2 export you see a desktop notification.

## More details

**Affected browsers/platforms:** WebView2

**First affected release:** r238? r242

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This does not appear to be supported in WebView2 yet. A feature request has already been filed for it here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/308

If support is added it may just start working, but if we have to change anything I'll review it when it's supported.
