### ISSUE TITLE
[r36] Changing a variable to/from a boolean can result in broken logic

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#471]
## Problem description

If a variable is changed to a boolean, actions and conditions that reference the variable aren't deleted and no warning is given. I discovered this after changing a function to accept a boolean instead of a number as a parameter, and changed the local variable in the function to hold the parameter to a boolean as well - comparison conditions didn't work properly after that, but it was hard to notice because at a glance the comparison logic seemed OK. It's easy to forget that "compare variable" only works on non-boolean types.

## Attach a .c3p

[BooleanBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1062281/BooleanBug.zip)

## Steps to reproduce

Note: This also applies to variables that begin as booleans but are later changed to number type.

1. Create a number variable.
2. Create a condition and/or action that uses the variable, i.e., System: Compare variable or System: Add to.
3. Change the variable to the boolean type.

## Observed result

The variable will change, but logic using the variable will not work as expected.

## Expected result

A warning should be given if any incompatible actions or conditions are being used with the variable, and if the user opts to keep the new boolean, those conditions and actions should perhaps be deleted. Likewise in the case of boolean-only conditions/actions using a variable that is changed from a boolean to a number.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r36

Local storage
Storage quota (approx): 8.2 gb
Storage usage (approx): 23 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by Scoremonger** [comment]
Related to this, there is no way to assign a boolean variable's value or a boolean value passed into a function to another boolean. That would be pretty handy in some cases (although for now I've just reverted to using constants of TRUE = 1 and FALSE = 0 and number variables instead of booleans to simulate it). Should this be written as a bug or added to the C3 requests platform?

**Comment by AshleyScirra** [comment]
Thanks, good catch. This also affected instance variables, it turns out. C2 disables the type field once you have added events using the variable since changing the type would make the events invalid; I've added that back for r37.
