### ISSUE TITLE
Crash in timeline editor

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#4712]
## Problem description

Crash in timeline editor when try override a previous set keyframe.

## Attach a .c3p

https://drive.google.com/file/d/1OYKgC7NL9EJAdRVO1o6U9GXHsR6SycbK/view?usp=sharing

## Steps to reproduce

1. Add a sprite
2. Add to the timeline
3. Click set keyframe and set again with override the older one
4. Crash 

## Observed result

Crash

## Expected result

Not crash

## More details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r243/projectResources.js, line 458, col 335
Message: Uncaught TypeError: Cannot read property 'valid' of undefined
Stack: TypeError: Cannot read property 'valid' of undefined at t.LKa (https://editor.construct.net/r243/projectResources.js:458:335) at t.I9c (https://editor.construct.net/r243/projectResources.js:459:304) at t.Lsb (https://editor.construct.net/r243/projectResources.js:456:87) at u.fRb (https://editor.construct.net/r243/projectResources.js:387:150) at https://editor.construct.net/r243/components/bars/timelineBar/timelineBar.js:131:233 at k.d9c (https://editor.construct.net/r243/components/bars/timelineBar/timelineBar.js:131:359) at k.N8b (https://editor.construct.net/r243/components/bars/timelineBar/timelineBar.js:131:216) at k.Cic (https://editor.construct.net/r243/components/bars/timelineBar/timelineBar.js:130:368) at Object.Aj (https://editor.construct.net/r243/components/bars/timelineBar/timelineBar.js:404:398) at k.Otd (https://editor.construct.net/r243/components/bars/timelineBar/timelineBar.js:27:157)
Construct 3 version: r243
URL: https://editor.construct.net/r243/
Date: Tue Apr 06 2021 17:26:46 GMT+0200 (közép-európai nyári idő)
Uptime: 68.9 s

Platform information
Browser: Chrome
Browser version: 89.0.4389.114
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
C3 release: r243 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon(TM) RX Vega 10 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Fixed on the next beta.
