### ISSUE TITLE
Opening R242 Projects in R243 resize/move objects

### ISSUE THREAD

**Issue by supereo** [Scirra/Construct-3-bugs#4713]
## Problem description
Opening projects that were saved in R242 in R243 result in sprites being in the wrong postion and size, also when trying to resize the object will snap into double the size that it is.

## Attach a .c3p
https://drive.google.com/file/d/18FWFUklUfAA8jpxa8XxEjVc1lc_HGksO/view?usp=sharing

## Steps to reproduce

1. Open the R242 project in R243
2. See that the sprites have been resized

## Observed result
In R242
![Image1](https://user-images.githubusercontent.com/15168469/113768793-258dee80-9718-11eb-99cb-af38aaf8e63c.png)
In R243
![Image2](https://user-images.githubusercontent.com/15168469/113768849-350d3780-9718-11eb-9bac-a5973aeda24e.png)

## Expected result
Project opens the same as R242 and objects are in the same place and have the same size

## More details

**Affected browsers/platforms:** Chome and most likely others

**First affected release:** r243

**Comment by fredriksthlm** [comment]
I also experienced the same, only a few sprites though... But when selecting one of these "misplaced/misformed" sprites I see that in the properties it is actually correct! And when previewing I also see the correct things.
So it is only in the preview in the editor that they show up incorrectly. (not accoring to its properties)

**Comment by supereo** [comment]
> I also experienced the same, only a few sprites though... But when selecting one of these "misplaced/misformed" sprites I see that in the properties it is actually correct! And when previewing I also see the correct things.
> So it is only in the preview in the editor that they show up incorrectly. (not accoring to its properties)

yes, i think you're right, this is only visual in the editor. I just ran the project and everythings the same when running. Although the editor still need to be fixed

**Comment by cl3m0ns** [comment]
It seems impossible to create levels because you can't add anything, they all appear the wrong size.  Trying to resize something in the layout view mega enlarges it.  For example I tried to resize my tilemap (bc it appears incorrectly in the editor now).  It was 1200 width and as soon as I click the corner to resize the width was changed to 120000000000.

**Comment by AshleyScirra** [comment]
See also: #4714

**Comment by brushfe** [comment]
I had the same issue with Tiled Backgrounds. The object dimensions are correct, but they're drawn at massive sizes and snap to strange grids.

If it helps — [https://drive.google.com/file/d/1DrWF3YWZIfxEgM7V7unTnSbWaa_Outqt/view?usp=sharing
](url)

**Comment by AshleyScirra** [comment]
This should be fixed in r243.2, which was just released. Apologies for the inconvenience.
