### ISSUE TITLE
r243 Layout view when resizing Object Increases the size dramatically 

### ISSUE THREAD

**Issue by cl3m0ns** [Scirra/Construct-3-bugs#4714]
## Problem description
Open a layout and try to resize and element.  It seems to be losing  the decimal point as you drag (a width of 1200.43434343 for example becomes 120043434343.  

## Attach a .c3p
[Vaultacular 2 - Stranger Influences.zip](https://github.com/Scirra/Construct-3-bugs/files/6267585/Vaultacular.2.-.Stranger.Influences.zip)

## Steps to reproduce
1. open any layout (Level_1 through Level_5)
2. click on any object on the objects layer. 
3. try to resize any object to correct it.

## Observed result

 As you drag the decimal is dropped and the object just grows and grows in scale.

## Expected result

It should look and behave the way it always has.

## More details
this was originally a r242 project.  I cannot open this file in r243 in any browser and have it works as expected. 

worked in r242 broke on r243

**Comment by robinhoed123** [comment]
Indeed It  broke my game whatever you do do not save a r242 project In r243 because it will break everything and you can’t reopen it on r242 because it is saved in r343

**Comment by AshleyScirra** [comment]
This looks the same as #4714, so closing as duplicate.
