### ISSUE TITLE
Dark theme style property bar link button spacing

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4718]
## Problem description

Dark Theme has been around for several years and these problems are still not fixed  :(

![unknown](https://user-images.githubusercontent.com/45864744/113984788-0dd07a80-987e-11eb-9149-678eb9809265.png)

The buttons in the property bar are spaced together. may be not seem obvious in English , but in other languages they will look pretty scary.

Since this issue is about the button problem, I will not mention the bad color of the free user events remaining :)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by robertoParlevecchio** [comment]
I noticed this too and worked out that the simple solution is to remove `height: 100%` from the `.ui-propvalue > a` style.
