### ISSUE TITLE
start page project list viewport size too small when the width less than 1240px

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4719]
## Problem description

When the width is below 1240px, the project list viewport becomes very small.
Such a little viewport I can't see any helpful information.... Instead, the low-use navigation bar at the bottom took up half of my screen

![01](https://user-images.githubusercontent.com/45864744/113985643-f8a81b80-987e-11eb-9017-860b4bf01b55.jpg)
![02](https://user-images.githubusercontent.com/45864744/113985646-f9d94880-987e-11eb-9007-d0bc92664405.jpg)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. It's a responsive layout that is designed to adapt to different screen sizes.

**Comment by XHXIAIEIN** [comment]
yes, But his adaptive rules is a problem.
1240px is not a small screen for a PC monitor. however, it  responsive layout to a smaller screen.

For productivity, users use more time with the project list. Instead of the bottom link list.  You can review the current design, current window only shows 2 project, is that reasonable?

![Snipaste_2021-04-08_19-51-31](https://user-images.githubusercontent.com/45864744/114021938-d5439780-98a3-11eb-8be6-f32d4d85b48a.jpg)

**Comment by SnipG** [comment]
Happened to see this.
Anyway, the possible fix is:
You can paste it into main.css in sources

#startPageWrap .linkContent {
    width: 100%;
    height: 100%;
    overflow-x: hidden;
    overflow-y: auto;
    max-height: 25em;
}
