### ISSUE TITLE
[r36] Gamepad RawAxisCount Uncaught ReferenceError: index is not defined

### ISSUE THREAD

**Issue by wiverson** [Scirra/Construct-3-bugs#472]
## Problem description

Trying to use an Xbox One controller on Mac OS X via BlueTooth.  Axis 2 is the left trigger on that device, which appears to be confusing the Gamepad app.  Bizarrely, all of the other reported Axis values appear to be working fine.  While trying to debug, I found that simply calling Gamepad.RawAxisCount(0) would throw the following ReferenceError

runtime.js:770 Uncaught ReferenceError: index is not defined
    at pluginProto.Instance.Exps.RawAxisCount (runtime.js:770)
    at ExpNode.eval_object_exp (expressions.js:347)
    at Parameter.get_exp (eveng.js:2059)
    at Action.run_object (eveng.js:1817)
    at EventBlock.run_actions_and_subevents (eveng.js:931)
    at EventBlock.run (eveng.js:888)
    at EventSheet.run (eveng.js:224)
    at Runtime.logic (preview.js:2647)
    at Runtime.tick (preview.js:2339)
    at tickFunc (preview.js:628)

Copied and pasted from the Developer Console.

## Attach a .c3p

Here is a simple example, tho you probably don't need it.  :)

[controller-test.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1062713/controller-test.c3p.zip)

## Steps to reproduce

1. Connect a controller, verify it's working with http://html5gamepad.com/
2. Create a blank project, add the Gamepad, add a text widget and try to set the value to  Gamepad.RawAxisCount(0)

## Observed result

I get the error above.

## Expected result

I would get 10 (the number of Axis values as reported by http://html5gamepad.com/

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.86
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
C3 release: r36

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 89 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M290X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by wiverson** [comment]
Not to horribly confuse things, but it looks like Construct is expecting Xbox Wireless Controller (Vendor: 045e Product: 02e0) to report as Axis 2 and 3 for the right stick, but it's actually reporting on 3 and 4 via RawAxis.  LMK if you want me to open another issue for controller mappings, or leave this as a holding spot for Gamepad bugs, or if supporting the Xbox One controller is not in scope...

Either way, this reported bug is just for the Gamepad.RawAxisCount(0) error.

**Comment by wiverson** [comment]
FYI, connected an old Xbox 360 wireless controller to my macOS Sierra 10.12.5 machine with the https://github.com/360Controller/360Controller driver and it looks like it works fine.  Much smaller set of registered axis/buttons.

Still getting the same error above when calling RawAxisCount with the 360 controller.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r37. Turns out the bug is originally from C2 and nobody noticed it until now. It'll be fixed in the next C2 build too.
