### ISSUE TITLE
Audio remote url doesn't work in iOS

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4721]
## Problem description

I try play remote audio and publishing to the web. Android and PC can work. But iOS doesn't work.

At first, I suspected that it was a file encoding problem. I tried to transcode it to M4A, OGG, WAV files, and changed the corresponding MIME Type, but it was still invalid.   `webm`  `"audio/webm; codecs=opus"`

Excluded the possibility of cross-domain, I tried to upload to a different server for testing, but it was also not work.
  
Finally, I implanted a console and saw the error: 
```
Failed to fetch Opus decoder WASM; assuming project has no Opus audio.
Error {column: 324, line: 357, 
message: "fetch 'http://cc.0tw.cn/c2c3/merry3/scripts/opus.wasm.wasm' response returned 404 Not Found"
sourceURL: "http://cc.0tw.cn/c2c3/merry3/scripts/c3runtime.js"
stack: "ThrowIfNotOk@http://cc.0tw.cn/c2c3/merry3/scripts/c3runtime.js:357:324 http://cc.0tw.cn/c2c3/merry3/scripts/c3runtime.js:357:506 promiseReactionJob@[native code]"
```
![ios console](https://user-images.githubusercontent.com/45864744/114140730-40907680-9943-11eb-977b-1436d815a790.jpg)

Note that this problem only appears on iOS, not Android or PC.

## Attach a .c3p

**case 1**: 
[remote audio merry  no file.zip](https://github.com/Scirra/Construct-3-bugs/files/6283780/remote.audio.merry.no.file.zip)

I also did two tests,   
If I import the audio file in the project, the remote url can works.

**case 2**: 
[remote audio merry include file.zip](https://github.com/Scirra/Construct-3-bugs/files/6283790/remote.audio.merry.include.file.zip)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** Safari
**First affected release:** 

## System details

<details><summary>View details</summary>

System: iPhone, iOS 14.4.2
Protocol: HTTP
UA: Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Safari does not support decoding WebM Opus audio. To work around this, Construct exports its own WebM Opus decoder with your project. However in order to keep exports lightweight, if your project does not use any WebM Opus audio at all, it will omit the WebM Opus decoder, which means it can't decode WebM Opus at a remote URL. As you've discovered, including a WebM Opus file in the project works around this, as it means Construct notices you intend to use WebM Opus audio and includes the decoder for Safari.

**Comment by XHXIAIEIN** [comment]
I think there may be many people who have the same problem as me. Maybe can add a output setting to make C3 include WebM Opus Decoder if user reference the Audio Object.

**Comment by XHXIAIEIN** [comment]
March 5, 2024 Update:
Safari 17.4 now is support for VP8/VP9 and WebM on iOS and iPadOS.
https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes
