### ISSUE TITLE
Crash on tile map on safari

### ISSUE THREAD

**Issue by Adavo** [Scirra/Construct-3-bugs#4723]
## Problem description

Contruct 3 crash as soon as I attempt to use a Tilemap on my game

## Attach a .c3p

https://filebin.net/f2jgn6j8mkp9tmr8/test.c3p?t=hd49oacd

## Steps to reproduce

1. Open the project
2. Click on the Draw Tile icon (the little pencil) on the bottom right corner inside the tile map area
3. Construct 3 crash

## Observed result

The popup displaying the crash information.

## Expected result

The ability to "paint" the tiles I suppose ...

## More details

Tested on Mac OS last version 11.2.3 and with the latest version of Safari (14.0.3).
Works on Chrome. Don't know the other browser.
Construct version R241 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r241/components/editors/layoutView/layoutView.js, line 19, col 372
Message: Error: unsupported event object
Stack: nMc@https://editor.construct.net/r241/components/editors/layoutView/layoutView.js:19:344 Cod@https://editor.construct.net/r241/components/bars/tilemapBar/tilemapBar.js:85:115
Construct 3 version: r241
URL: https://editor.construct.net/
Date: Sat Apr 10 2021 08:55:59 GMT+0200 (CEST)
Uptime: 13.5 s

Platform information
Browser: Safari
Browser version: 14.0.3
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
C3 release: r241 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_blend_minmax, EXT_sRGB, EXT_frag_depth, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_standard_derivatives, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_depth_texture, WEBGL_draw_buffers, ANGLE_instanced_arrays, WEBGL_debug_shaders, WEBGL_debug_renderer_info, EXT_color_buffer_half_float, WEBGL_color_buffer_float
</details>

**Comment by DiegoScirra** [comment]
What device are you using exactly? Is it an iPad or a desktop?

**Comment by Adavo** [comment]
Hello DiegoScirra,
It's on my Mac Book Pro 16 (2019).

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
