### ISSUE TITLE
when I try to use the tilemap it bugs me, and tells me to reload the page

### ISSUE THREAD

**Issue by Lindi03** [Scirra/Construct-3-bugs#4725]
## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Lindi03** [comment]
help me someone

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines, otherwise I'm afraid it's impossible for us to help you. If you just need general help, please post to the forum instead.
