### ISSUE TITLE
Pixelrounding is wrong with scaling enabled

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4726]
## Problem description
Case when user uses pixel rounding. Then C3 will produce glitzy rounding when user has fullscreen scale mode ON.

Look simple image below: It shows 1 step length
Top two sprite has fullscreen scale OFF - step is  1 pixel
Bottom has integer scale with fullscreen mode  - step is 2 pixel

Moving sprite in bottom image shows sprite rounds 2 pixels at time(You have to get close to monitor to see it, not easy to detect but it's there! ) Anyway, this 2 pixel rounding will produce glitzy and jagged movement with low speeds. I bet it definetly should not be like this. Sprite never needs to be moved 2 pixels, it only needs 1 pixel to move all pixels to new location

![pixelRounding](https://user-images.githubusercontent.com/28864889/114305259-ff819900-9adf-11eb-93d2-77bb5d7c05a3.jpg)

## Attach a .c3p
[Bug_The_FallenOne.zip](https://github.com/Scirra/Construct-3-bugs/files/6291824/Bug_The_FallenOne.zip)

## Steps to reproduce

1. Open example, preview, click F11
2. Drag bottom sprite around, see it's movement step dependency to line (line is 2 pixel width with fullscreen).
3.

## Observed result
Bottom sprite moves 2 pixels at time, it should move just 1 pixel at time.

## Expected result
Pixel rounding should round pixel 1 pixel at time, 2 will produce lag, jagged and jumpy movement at lower speeds

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 89.0.4389.114
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
C3 release: r243.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 528 mb
Storage usage (approx): 36 mb (6.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
This doesn't look like a bug to me. You have an object with a 25x25 image, scaled up to 40x40, so using a 1.6x scale. That means it will not align with pixel rounding, since 1px in layout co-ordinates now corresponds to 1.6px in the image. So it doesn't make sense to try to make pixel measurements against that object.

FWIW, pixel rounding happens in layout co-ordinates, not object co-ordinates. In other words it's similar to using a 1px 'snap to grid' in the layout view, but with rendering at runtime.

**Comment by SnipG** [comment]
It might be correct by math. But if you use pixel rounding, then with original scale all seems good. But when 2 pixel step occure it makes it jump, instead move smooth.
Even in fullscreen, everything needs to moved only 1 pixel to move all pixels to new location.



Would it be possible with feature suggestion?

**Comment by SnipG** [comment]
Last thing I want to add!

> You have an object with a 25x25 image, scaled up to 40x40, so using a 1.6x scale.
> since 1px in layout co-ordinates now corresponds to 1.6px in the image

Even if i make that object original size, 25x25. It still jumps 2px at time. I did even futher tests to see that image scale itself is irrelevant, so i don't know why it matters.


From 640 x 360 to 1920 x 1080 equals '3 time bigger' , so that is  only thing that should somehow affect it. Not sure why it makes it 2px jump and not 3.

!!! Now i did recheck, it indeed jumps 3 pixels, which is even worse. 

First line is 3 px and second line is 2 pixel. First one jumps 3px! 
![Screenshot77](https://user-images.githubusercontent.com/28864889/114640982-da587a80-9cd9-11eb-89a2-58d6ef68425c.jpg)


>FWIW, pixel rounding happens in layout co-ordinates, not object co-ordinates. In other words it's similar to using a 1px 'snap to grid' in the layout view, but with rendering at runtime.

When integer scale mode, scale 1x  2x or 3x. Then should'nt that layout co-ordinate take it into account and scale the grid down?
