### ISSUE TITLE
Origin Issue while cloning SpriteFont

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#473]
## Problem description
*When I insert SpriteFont and set its Origin to Center and make some clone then Origin automatically do resets to corner left*
## Attach a .c3p
*No file need*
## Steps to reproduce

1. Insert Spritefont
2. Change its Origin Point
3. Clone it by dragging

## Observed result
*Origin reset automatically*

## Expected result
*Origin should remain same *

## Affected browsers
* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for r37.
