### ISSUE TITLE
244 beta 3d crash

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4733]
## Problem description

Duplicating frame crashes C3
## Attach a .c3p

https://www.dropbox.com/s/jwdahcig2tx31i5/244-3ddupeframe.c3p?dl=1
## Steps to reproduce

1.Open project
2. Open image editor of 3d object
3. Try to duplicate a frame

## Observed result
C3 crash

## Expected result
No crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
How are you trying to duplicate a frame?

**Comment by pigmalien** [comment]
> How are you trying to duplicate a frame?

Right click on a frame hit Duplicate.

**Comment by DiegoScirra** [comment]
Oh right of course, this is another side effect of #4731. You shouldn't even be seeing that menu option when editing a 3D shape, but the check is backwards and the options are shown for 3D shapes and not for the rest of the object types that should have them.

**Comment by DiegoScirra** [comment]
Leaving this one open because it is pretty flaring and more people will see it.

**Comment by pigmalien** [comment]
Ok thank you!

**Comment by AshleyScirra** [comment]
This should now be fixed in r244.2.

**Comment by pigmalien** [comment]
Thanks.
