### ISSUE TITLE
3D shape not handle texutes transparent color

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#4734]
## Problem description

The 3D shape not handle texutes transparent color.
It might be by design or not supported.

## Attach a .c3p

https://mega.nz/file/AAkyxbyD#r6QzGOyTywSpROUutxuZzokvrQdmTLfPR0_1e3lPoYw

## Steps to reproduce

1. Insert 3D shape
2. Set a transparent pixels in texture
3. 

## Observed result

It has a bizarr view

## Expected result

Might be white or other color or will be truly transparent.

## More details

Without transparent texture:
![Képkivágás](https://user-images.githubusercontent.com/47735877/114711868-be7fc380-9d2f-11eb-87b9-fbc27dcfc126.PNG)

With transparent texture:
![Képkivágás2](https://user-images.githubusercontent.com/47735877/114711898-c8092b80-9d2f-11eb-9fd1-a1f7c859ec0d.PNG)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 89.0.4389.128
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36
C3 release: r244.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 435 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon(TM) RX Vega 10 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a limitation of 3D rendering. I don't think it's feasible to fix.

Correct 3D rendering requires a depth buffer. However depth buffers do not work with transparency: everything rendered is assumed to be opaque and will block anything being drawn behind it. It will render correctly if the draw order is back-to-front. Construct's draw order is (and always has been) back to front based on Z elevation and Z order - but the different faces of 3D shapes can extend above other shapes. Therefore it's possible to assemble shapes with out-of-order rendering, where the depth buffer will occlude other content behind it. You can see if you change the Z order of the instances, you can get correct rendering at certain viewing angles, but then it will obscure it a different way round. This is a known limitation of 3D rendering. This will be covered in the documentation for 3D shape when it's documented at the next stable release.
