### ISSUE TITLE
Hierarchy not loaded after standard save load

### ISSUE THREAD

**Issue by winkr7** [Scirra/Construct-3-bugs#4735]
## Problem description

When I save a file and then load it back all my hierarchy connections are gone

## Attach a .c3p

https://drive.google.com/file/d/12ZjJT0wbmqIqmmLBrscP4DI15Rnnrx2c/view?usp=sharing

## Steps to reproduce
click the button in the middle of the screen
type s (for save)
type l (for load)
click the blue wizard
click somewhere--he will move but his stuff will be left behind because it is no longer attached

1.Click the middle of the screen to clear help

2.type S (for save)

3.type L (for load)

4.Click the blue wizard

5Click a blank spot close by

6The blue wizard moves but his wand and book don't move --they are no longer children after the load

## Observed result

If you don't type s for save and L for load everything is fine.  If you do the child conections between staff and wizard and book and wizard are lost

## Expected result

The wizard should move with his staff and book as one

## More details

the staff and book are on a different layer from the wizard

Only tested chrome

**Affected browsers/platforms:** 

I only noticed the problem when I tested out save and load

**First affected release:** 

## System details

Only found out on the latest non-beta version

<details><summary>View details</summary>

PASTE HERE

It does not crash

</details>

**Comment by winkr7** [comment]
I did not see any problem with a new example with just two boxes.

**Comment by winkr7** [comment]
If I duplicate the passageOne layout the hierarchy is not preserved either.  It may have something to do with going from one layer to the next?

**Comment by DiegoScirra** [comment]
These were two different issues. Both will be fixed in the next beta.

**Comment by winkr7** [comment]
Thankyou very much.
