### ISSUE TITLE
3D Objects have no Effects and Blending Modes and no Shadows

### ISSUE THREAD

**Issue by KENYONBcom** [Scirra/Construct-3-bugs#4736]
the new 3D plugin objects has no Effects and Blending Modes. They do not cast shadows like other objects.

I think you know about this since it is brand new.

**Comment by AshleyScirra** [comment]
This is currently by design. Effects are difficult to support with 3D shape as the effect compositor is designed to work in 2D.

**Comment by KENYONBcom** [comment]
Understood.

But would it be possible to have it cast shadows like 2D objects? use the Bottom face for what casts and then use the shadow controls to control everything else like 2D objects?

Also, instead of making every effect available, how about just blending mode and it applies to every face (top and sides) the same like they are all 2D objects facing up (if that makes sense)?

The 3D objects as they are now will not work in games that use masking, like a player holding a torch in a dark dungeon. when you approach the 3D object, it doesn't show any details like other sprites. it stays completely black.

**Comment by AshleyScirra** [comment]
Shadow casting is a different issue. It should already be using the back face as the collision polygon for shadows (the same polygon is used for collisions and shadow casting). If that does not work please file an issue following all the guidelines specific to that.
