### ISSUE TITLE
For Each's <click to choose> can add infinite lists of objects

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#4739]
## Problem description

The <click to choose> button as seen in the For Each system condition (and possibly elsewhere as well?) can be pressed multiple times to add unlimited copies of every object to the Pick an Object window's list. After doing so, choosing one of the listed objects can sometimes crash Construct 3.

## Attach a .c3p

[Blank Project.zip](https://github.com/Scirra/Construct-3-bugs/files/6326372/Blank.Project.zip)

## Steps to reproduce

1. Start a new project or open an existing one.
2. In an event sheet, add a new event --> System --> For Each.
3. In the _Parameters for System: For Each_ window, click the _<click to choose>_ button repeatedly.

## Observed result

A theoretically infinite number of each object can be added to the object picking window this way, and when choosing one of those objects listed there after adding multiple copies, C3 sometimes crashes.

## Expected result

Perhaps the _click to choose_ button would be grayed out while the _Pick an object_ window is visible so that users can't infinitely populate the _Pick an object window_?

## More details

**Affected browsers/platforms:**
Firefox, Chrome.

**First affected release:** 
r241 at latest.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 87.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
C3 release: r241 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 370 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I cannot reproduce any issue in Chrome. I also cannot reproduce opening multiple dialogs in Firefox (although it's not clear if your bug report really means this). The only issue I can reproduce is in Firefox where you can open a sub-dialog, close the Parameters Dialog, and then you have the sub-dialog left behind (e.g. "Pick object"), and interacting with that can crash. This is because Firefox doesn't support the `<dialog>` element, so we have to use a polyfill, but it doesn't work exactly the same and in this case doesn't block interacting with another dialog underneath. I've fixed this specific case for the next beta, but it wouldn't surprise me if there were others...
