### ISSUE TITLE
layout.getLayer(layerNameOrIndex) should return null

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4740]
## Problem description

![image](https://user-images.githubusercontent.com/31282960/115073332-c2c40080-9f2a-11eb-87c9-3030b2d61ff2.png)

`layout.getLayer(layerNameOrIndex)` should return `null` instead of an error.
This would be useful and possibly necessary, to check if a layer exists or not.

## Attach a .c3p

[getLayer.zip](https://github.com/Scirra/Construct-3-bugs/files/6327437/getLayer.zip)

## Steps to reproduce

1. Preview project

## Observed result

![image](https://user-images.githubusercontent.com/31282960/115073676-4251cf80-9f2b-11eb-9cb2-5a79d29edc63.png)

## Expected result

A `null` value for checking.

**Comment by AshleyScirra** [comment]
Seems reasonable, updated for next beta.
