### ISSUE TITLE
Dictionary 1000-Row Soft Limit

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#4741]
Posted this in the forums https://www.construct.net/en/forum/construct-3/general-discussion-7/dictionary-row-limit-159917, Diego responded and suggested I also add an issue tracker:

There is a 1000 row soft-limit to dictionaries. Right clicking the dictionaries allows for the addition of a single row past this 1000 mark (which is why I state this as a soft limit). However if I need 200+ rows this becomes unreasonable; leading to the need for multiple 1000 row dictionaries (I'm not there yet, but approaching this point).

Is it possible to increase this limit to a higher value?

Sincerely,

1Step

**Comment by AshleyScirra** [comment]
I looked at the code and I don't think there's any good reason for the limit to be that low. I've increased it to 1 million rows for the next release.

**Comment by OneRepCloser** [comment]
Awesome, thanks Ashley.
