### ISSUE TITLE
Tilemap - PositionToTile 

### ISSUE THREAD

**Issue by FromChris-com** [Scirra/Construct-3-bugs#4743]
## Problem description

When a bullet sprite is moving from right to left the collision is detected, but the positionToTile is not registered for erasure. It does however work, when the bullet sprite is moving from left to right. 

## Attach a .c3p

https://www.dropbox.com/s/kvwcctoukmmx8cq/bulletTilemap.c3p?dl=0

## Steps to reproduce

1. Create Tilemap, and place tiles
2. Create a sprite, with bullet 
3. When Tilemap is hit from the left side with bullet (angle of motion 0) Erase tile > PositionToTile (bullet.position) works as expected
4. When Tilemap is hit from the right side with bullet (angle of motion -180) Erase tile > PositionToTile (bullet.position) does not work. 

## Observed result

When the bullet sprite is moving from right to left the collision is detected, but the positionToTile is not registered for erasure. It does however work, when the bullet sprite is moving from left to right. 

## Expected result

The erasure of tiles upon collision no matter the direction origin of the bullet sprite. 

## More details
Testing with a tween behavior, instead of the bullet, does produce similar results. However it does register the right to left a couple of times. 

**Affected browsers/platforms:** Windows / Chrome

**First affected release:** Never tested in an earlier version, but tested in R241 & R244.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This looks like a mistake in your events. PositionToTileX/Y() could return the position of an empty tile, even when a bullet collides with the tile, because the edge of the bullet collides with a tile while its origin remains in a different tile. Since you clear an area extending to the right of that, for bullets approaching from the right, you just clear a region of empty tiles.
