### ISSUE TITLE
MoveTo Behaviour: Never arrives when there's a slope

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#4744]
Hi there. 

If this is a bug could be argued but i wanted to submit it anyways.

Problem Description:

When having both a platform and a MoveTo Behaviour on an object so it slides across solids (i.e. for cutscenes in a jump'n'run) it usually works without problems.

But i ran into an issue that took me a while to figure out: when there is even a slight slope (done by using the mesh editor to adjust a sprite with a solid behaviour) the MoveTo behaviour never arrives completely. When you look at the debugger you'll see that it is micro-pixels away from the goal of in this case X-200 pixels but it never quite makes it.

How to reproduce:

1. Open the attached file
2. Run the project
3. Remove the sprite with the slope
4. The Sprite arrives at the destination and the text changes to signal that.

This is pretty inconvenient for all sorts of cases and maybe you can implement something that the move to just jumps to the desired location when within 2-3 pixels of reach and slowing down too much.

See the attached .c3p file.

Thanks!
[moveto_slopes.zip](https://github.com/Scirra/Construct-3-bugs/files/6332091/moveto_slopes.zip)

**Comment by AshleyScirra** [comment]
I don't think this is a bug. You are using "Move to" to move the player inside a solid. The Platform behavior prevents the object moving inside a solid. Therefore the movement can never arrive.

**Comment by joelmayer87** [comment]
Okay, could we then at least please get an action that signals the moveto behaviour that it has arrived by hand? because then i can just add a line of event telling it when within 2 pixels, set to moveto.posx and tell it it's arrived, which then triggers other events.

**Comment by AshleyScirra** [comment]
If you tell MoveTo to move in to a solid, and it has another behavior that prevents it moving in to a solid, you have given MoveTo an impossible command that it can never fulfil. It's difficult to see what it could even attempt to do in that situation.

**Comment by joelmayer87** [comment]
But in this case i just tell it to go to a specific X Position which it definitely could reach without problem and keep the y to whatever the sprite currently has.... Oh well, i'll look for a different solution, thanks for taking a look though. I think i might try to revamp my entire movement system using paths and the moveto feature since it's not really a platformer per se anyways and the characters just stay "on rails" so to speak without any jumping. Thank you.

**Comment by AshleyScirra** [comment]
"Move to X, Self.Y" does not mean "just move on the X axis". It means to move to the specific point given - which in the case of your project, is embedded in a solid.
