### ISSUE TITLE
AddRemoteScriptDependency adds script to body instead of head

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#4745]
## Problem description

AddRemoteScriptDependency is the function for adding external script links to the final HTML file, and currently, the method adds the script to the body tag which doesn't make sense as usually, adding external dependencies would instead be added on the head tag to make sure the library has been loaded before the page is ready.

## Attach a .c3p

n/a

## Steps to reproduce

n/a

## Observed result

The script gets added at the top of the body tag

## Expected result

The script should get added at the end of the head tag

## More details

I suppose, it would make more sense to just have this be a secondary option as I can see some cases where having the script in the body is better.

**Affected browsers/platforms:** n/a

**First affected release:** n/a

**Comment by AshleyScirra** [comment]
This is currently by design. It should not matter whether the script is added to the head or body tag. If you can identify an actual case where this matters, this could be reconsidered, but if it's just speculation we won't address it.
