### ISSUE TITLE
Playable Ads for UnityAds in iOS not loading + audio issues

### ISSUE THREAD

**Issue by EnriqueAlbirCodi** [Scirra/Construct-3-bugs#4748]
Greetings, we've been expieriencing issues with our playable ads developed in Construct3 in UnityAds.

For a while, the playables are mute in iOS, no sound or music plays at all. Meanwhile, the audio plays just fine in Android.

We've tried to change the format from .webm to .mp3 to no avail.

This time, I've prepared a version of the Audio Effects Template with some extra that can be detected as a proper playable ad in UntyAds.

In Android everything works fine, but in iOS it gets stuck on the loader screen.

In the .zip below, you can check the .c3p project file and both screenshots.

[iOSAudio_Bug_Report.zip](https://github.com/Scirra/Construct-3-bugs/files/6341995/iOSAudio_Bug_Report.zip)

Thanks for your time.

Sincerely, Enrique Albir.

**Comment by AshleyScirra** [comment]
Audio plays fine for me on iOS in Safari. This suggests the problem is with the ad service, not Construct or iOS. You should try reporting it to them first.
