### ISSUE TITLE
Speech RECOGNITION example project makes Chrome crash

### ISSUE THREAD

**Issue by typingmasteradmin** [Scirra/Construct-3-bugs#4749]
## Problem description

C3 example project crashes Chrome+Edge Browser to a critical browser error NOT IMPLEMENTED

## Attach a .c3p

https://github.com/Scirra/Construct-3-bugs/files/6342801/sound.zip
OR use the C3 template project named SPEECH RECOGNITION ( select it from the Beginner Examples included to C3 )

## Steps to reproduce

1. export c3 speech recognition example project to html5 file
2. unzip the html5 package  to any web server  ( https )
3. load the example project on one TAB of Chrome and see it works OK.
4. leave the Tab open with example project  
5. re-load same url on another tab or multiple times to crash (also try to load in INCOGNITO page if normal page does not crash)

## Observed result

Browser randomly crashes while loading the page, both Chrome and Edge.  The app starts approx every 2nd time.
CHROME Says Error code: STATUS_NOT_IMPLEMENTED

## Expected result

Each web page should LOAD ok and display the example project.
 Alternatively C3 should display some kind of error, instead of crashing, if its not possible to open app on multiple pages.

## More details

Usually when page has crashed once, it no more starts at all.

Here is another example app (based on same template) where Chrome also crashes randomly: usually 1st time the APP works OK.
https://www.typingmaster.com/speech/

**Affected browsers/platforms:** 

CHROME n 90.0.4430.72   gives crash error code: STATUS_NOT_IMPLEMENTED
EDGE Version 90.0.818.42 (Official build) (64-bit) SAYS RANDOMLY: Error code: STATUS_ACCESS_VIOLATION

**First affected release:** 

## System details

<details><summary>View details</summary>

https://user-images.githubusercontent.com/12512271/115383020-01351600-a1de-11eb-90c4-8b68fbbea646.PNG

</details>

**Comment by typingmasteradmin** [comment]
Also attached the example project of C3 here: [sound.zip](https://github.com/Scirra/Construct-3-bugs/files/6342801/sound.zip)

**Comment by typingmasteradmin** [comment]
![crash](https://user-images.githubusercontent.com/12512271/115383020-01351600-a1de-11eb-90c4-8b68fbbea646.PNG)

**Comment by AshleyScirra** [comment]
I'm afraid browser crashes are the responsibility of the browser maker - we cannot fix them, you need to report them to the browser vendor. For example to report an issue in Chrome, please file an issue at crbug.com.

**Comment by typingmasteradmin** [comment]
please vote bug fix up here:

https://bugs.chromium.org/p/chromium/issues/detail?id=1200763
