### ISSUE TITLE
My Construct 3 Projects arn't working 

### ISSUE THREAD

**Issue by BraydenKludt** [Scirra/Construct-3-bugs#4750]
All of my Constuct 3 files wount open. It says check if it is a valid file. I am using cloud storage.

**Comment by BraydenKludt** [comment]
Please help. I am a beginner but I have put in a lot of work learning and designing my games

**Comment by BraydenKludt** [comment]
I have fixed it.

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines - we cannot help unless you provide the requested information.
