### ISSUE TITLE
Can't load png file into animation editor in R245 - Says its not supported

### ISSUE THREAD

**Issue by justifun** [Scirra/Construct-3-bugs#4752]
## Problem description

In the latest R245 release when attempting to import a png file into the animation editor you get a warning saying that its not supported and that you should impoart a image/png type.  This works correctly in R244.

## Steps to reproduce

[pngerror.zip](https://github.com/Scirra/Construct-3-bugs/files/6345935/pngerror.zip)
1. Create a sprite object
2. In the animation editor window use the load file button and select a png image

## Observed result

Error popup: The image test.png is in a format not supported by Construct (image/png) Try converting your image to a supported format such as PNG or jpeg.

## Expected result

Import a png file correctly without errors just like previous versions of construct

## More details

**Affected browsers/platforms:** 

Chrome 90.0.4430.72 (Official Build) (64-bit)

**First affected release:** 

Worked in 244, broken in 245

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 90.0.4430.72
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
C3 release: r245 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 1.1 tb
Storage usage (approx): 356 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3090 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6611)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by OneRepCloser** [comment]
![image](https://user-images.githubusercontent.com/37854520/115447341-413fcd00-a1cd-11eb-9ebe-3fa4e5512186.png)

Confirmed

**Comment by jpbreau** [comment]
Same error message in Edge (89.0.774.77)

**Comment by function87** [comment]
same on Chrome 89.0.4389.128

**Comment by KENYONBcom** [comment]
me too
<img width="559" alt="PNG-error" src="https://user-images.githubusercontent.com/21185437/115479206-f1392880-a215-11eb-9289-9989cfceb7c0.png">

**Comment by alastajj** [comment]
I can't import image my images 

![image](https://user-images.githubusercontent.com/5744908/115524077-13dc4780-a2d1-11eb-9643-d55a7437a9d2.png)

**Comment by AshleyScirra** [comment]
We had to change the experimental animated image importer to update to the latest API, but this accidentally broke support for importing non-animated PNG images in Chrome stable. I've just released r245.2 which should fix the issue.

**Comment by justifun** [comment]
Thank you for the quick fix!
