### ISSUE TITLE
Video Plugin Not Rendering Video

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-3-bugs#4754]
## Problem description

When using the video plugin, if you change the source of the video several times, or quickly, the video stops rendering. Sometimes the audio keeps playing although the video is no longer visible. I migrated a project from c2 to c3 and found this problem, on c2 it didn't happen. I have a game that uses the video to display a video of the character powers, on the c2 version you can quickly switch between videos and it keeps rendering correctly. I switched between WebM and H.264 sources and even indicated both, and the result is the same.

## Attach a .c3p
The project contains the same short videos I'm using to display in my game.
[testVideo.zip](https://github.com/Scirra/Construct-3-bugs/files/6346309/testVideo.zip)

## Steps to reproduce

1. Run the project
2. Click on the buttons to select a video to play
3. Switch multiple times or rapidly, to change the video
4. The video will stop rendering with no console logs 

## Observed result

Video is not rendered

## Expected result

Video must render.

## More details

No console logs are recorded for this error on Chrome, on Edge I noticed this message when switching videos:
![image](https://user-images.githubusercontent.com/10860045/115457032-8540cb00-a1e9-11eb-8b4b-838cbf8a4774.png)

**Affected browsers/platforms:** 
Chrome 90 
Edge 89.0.774.77
Firefox works fine, with a slight delay.

**First affected release:** 
Construct r241

## System details

<details><summary>Platform information
Browser: Chrome
Browser version: 90.0.4430.72
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 572 gb
Storage usage (approx): 1 gb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)</summary>

</details>

**Comment by AshleyScirra** [comment]
This looks like a bug with video playback in Chrome. I filed the issue with Google here: https://bugs.chromium.org/p/chromium/issues/detail?id=1201211

Closing this issue as it will be followed up there.
