### ISSUE TITLE
In the 'Move along path' example project, sprite is not visible from layout editor when playing timeline

### ISSUE THREAD

**Issue by KMU-dev-stack** [Scirra/Construct-3-bugs#4756]
## Problem description

 I opened the 'Move along path' timeline example project, which can be found on the Start page of Construct 3, and played the timeline in the timeline editor, the sprite disappears from the layout.

## Attach a .c3p

 I'm attaching the example link.
https://editor.construct.net/#open=move-along-path

## Steps to reproduce

1. Open an example project on the Start page or through the link attached above.
2. Open the Path file in the Timelines folder.
3. In the Timeline Editor, click the Play button.

## Observed result

 I can't see the sprite. If you select the sprite instance and play the timeline, you will see that only the location is displayed.

## Expected result

 I need to see the sprite moving along the path. As with other timeline example projects.

## More details
 However, deleting and re-creating sprite tracks in the timeline editor does not cause this problem.
Changing the settings for that track did not solve the problem.

**Affected browsers/platforms:**  Chrome/macOS

**First affected release:**  r241 (stable)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 86.0.4240.198
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 11.0_0
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Whale/2.9.115.16 Safari/537.36
C3 release: r241 (stable)
Language setting: ko-KR

Local storage
Storage quota (approx): 68 gb
Storage usage (approx): 44 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) UHD Graphics 630
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

Thank you.

**Comment by AshleyScirra** [comment]
I can reproduce in r241, but it appears to already be fixed in the latest beta r245.2.

As per the bug report guidelines, please only report issues that reproduce in the latest beta, in order to avoid reporting issues that have already been fixed.
