### ISSUE TITLE
Copying area in the sprite editor also copies transparent pixels.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4758]
## Problem description

Try copying some part of an image that has transparent pixels on top of another part that would be beneath said pixels, observe that the image below the transparent pixels are erased.

## Attach a .c3p

any file should present it.

## Steps to reproduce

1. copy any part of an image with transparent pixels.
2. paste it on top of any other part of the image.
3. observe the pixels underneath the transparent ones will be erased.
4. if you cannot observe it while using the editor, close it after editing and then the sprite should present the defect.

## More details

**Affected browsers/platforms:**  Chrome

**First affected release:**  245-2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Should be fixed in the next beta.
