### ISSUE TITLE
adaptive icon problem

### ISSUE THREAD

**Issue by ManuelSanMatin** [Scirra/Construct-3-bugs#4760]
Construct3 r241.
build android in construct service.

hello, i'm not getting my icons to look adaptive. There is no tutorial on how to solve in android studio or anything updated from cordova CLI.
What I can do?

![icons_all](https://user-images.githubusercontent.com/70768024/116007277-5cec0e80-a5e5-11eb-93a6-c5873ada5ec0.png)
![icon_construct3](https://user-images.githubusercontent.com/70768024/116007285-6a08fd80-a5e5-11eb-9aee-aac449e3fe47.png)
![WhatsApp Image 2021-04-25 at 16 32 09](https://user-images.githubusercontent.com/70768024/116007290-6ecdb180-a5e5-11eb-93cf-e9440921fb08.jpeg)

**Comment by AshleyScirra** [comment]
Adaptive icons depend on support from the launcher app. For example they look correct in the Pixel 3 app list. They may not appear in all other parts of the Android system. So it's possible what you have shown is actually everything working as designed. We need you to provide the requested information to be able to help, so closing. Please see the bug report guidelines.
