### ISSUE TITLE
Timeline makes C3 crash if there is a 3d Object [C3 R245.2]

### ISSUE THREAD

**Issue by miredge** [Scirra/Construct-3-bugs#4762]
There's not so much to say. As long as there is a 3d Shape object in the project, the project will crash just by clicking the button that lets you choose an object for the timeline. Timeline can be used as long as there is no 3D object in the layout scene.

![image](https://user-images.githubusercontent.com/14828040/116050803-30350700-a678-11eb-964b-ee606a9ac994.png)
![image](https://user-images.githubusercontent.com/14828040/116050833-375c1500-a678-11eb-8875-6abb9704db30.png)

[TimelineBug.zip](https://github.com/Scirra/Construct-3-bugs/files/6375354/TimelineBug.zip)

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
