### ISSUE TITLE
3D Objects give blackscreen in certain resolution and scaling [C3 R245.2]

### ISSUE THREAD

**Issue by miredge** [Scirra/Construct-3-bugs#4763]
If the project fullscreen mode is anything but letterbox integer scale then the project will just render a black screen in certain windows mode resolution and when in Fullscreen.

![image](https://user-images.githubusercontent.com/14828040/116054285-cd456f00-a67b-11eb-80e3-141a518f4171.png)
![image](https://user-images.githubusercontent.com/14828040/116054632-26150780-a67c-11eb-951a-3c4938fdde87.png)

[ResolutionBlackscreen3Dobject_Issue.zip](https://github.com/Scirra/Construct-3-bugs/files/6375527/ResolutionBlackscreen3Dobject_Issue.zip)

**Comment by AshleyScirra** [comment]
It looks like the issue is with using fullscreen quality 'Low', not the fullscreen mode.

**Comment by miredge** [comment]
> It looks like the issue is with using fullscreen quality 'Low', not the fullscreen mode.

yes it does fix the issue, thanks :).

**Comment by AshleyScirra** [comment]
Fixed using low quality fullscreen mode with 3D shapes for the next beta.
