### ISSUE TITLE
Stealth Game example

### ISSUE THREAD

**Issue by oosyrag** [Scirra/Construct-3-bugs#4764]
## Problem description

The stealth game example pathing is broken on start. The guard objects never reach their first waypoint, and thus never trigger additional pathing. Assuming this project was working properly when it was created, there may have been a breaking change at some point?

## Attach a .c3p

https://editor.construct.net/#open=stealth-example

## Steps to reproduce

1. Preview the stealth example project.

## Observed result

Guard objects stop before reaching first waypoint.

## Expected result

Guards should patrol along designated paths.

## More details

After aggroing the guards, they will return to the "patrol" state, and work as expected. It is only on start of layout that they get stuck. The debugger shows that the tile movement behavior for each guard has the guard target x or y short 1 cell of its intended waypoint, regardless of orientation, which I was unable to account for.

Disabling the compare x/y conditions in event 9 somewhat resolves the issue but introduces new ones.

**First affected release:** Unknown

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 89.0.4389.128
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 70 gb
Storage usage (approx): 188 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Radeon RX 570 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by oosyrag** [comment]
Update by AllenR: https://www.construct.net/en/forum/construct-3/general-discussion-7/stealth-game-example-broken-160134#forumPost1041305

Worked up until R213 and broke in R214 - "Tile movement: move back to previous tile if movement blocked by outside factors (e.g. Bound to Layout)"

**Comment by ariepert** [comment]
Further testing I did showed that on the first tick of the game (tick 0), each guard got the correct target waypoint to the next waypoint (since they start on a waypoint). Tick 1 they still have the correct GridTargetX and Y, on Tick 2 the GridTargetX is changed (even though no actions were executed).  They all arrive at the "new" target coordinates and stop - just not on the next intended waypoint, so they do not get further instructions.

**Comment by ariepert** [comment]
ok, more testing and I found a temporary work around - just don't give any tilemovement orders until after a few ticks of the game running. Something is still happening under the hood for the first couple of ticks when the layout starts. (I didn't test restarting a layout or going to another layout)

adding another condition to event 14 makes it work fine:

system compare two values -> TickCount > 2

**Comment by AshleyScirra** [comment]
Thanks for spotting this. It's a regression caused by the fix for #4166. I've fixed it for the next release so it works both with that old issue and the existing stealth game template.
