### ISSUE TITLE
 App Tracking Transparency ios14.5

### ISSUE THREAD

**Issue by robinhoed123** [Scirra/Construct-3-bugs#4765]
## Problem description
So in the new update from apple iOS 14.5 we have to implement App Tracking Transparency.
Is this a feature that construct 3 will support in future (update) when exporting to  XCode?
if not what's the best way to implement App Tracking Transparency after i export construct project?

## Steps to reproduce

1.open construct 
2.make a new project 
3.export to xcode

## Observed result

App Tracking Transparency is Not implemented.
## Expected result

App Tracking Transparency is implemented if i export a construct project to XCode.
## More details

**Affected browsers/platforms:** 
ios

**First affected release:** 
r2454-2
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is already supported for the AdMob plugin. I'm not aware that it's needed anywhere else.
