### ISSUE TITLE
Voronoi and Cellular noises (maybe others too) break on movement.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4766]
## Problem description

In  a slightly modified file of the "Advanced Random" example, one where arrow keys move the noise around, it's visible that cellular and voronoi noises at some point break in straight lines. Other noises may break too, but less visibly.

## Attach a .c3p

[Mod_Noise.zip](https://github.com/Scirra/Construct-3-bugs/files/6384722/Mod_Noise.zip)

## Steps to reproduce

1. Use arrow keys to move the noise around.
2. Cellular and Voronoi are the most obvious breaks.
3. It doesn't matter where you move to, just keep going and eventually it shows up like below.

## Observed result

Working most of the time, even when moving...
![voro](https://user-images.githubusercontent.com/34659544/116247020-d9473480-a740-11eb-9656-688f67af641b.PNG)

but breaking at points in this straight weird lines.
![voro2](https://user-images.githubusercontent.com/34659544/116247143-eebc5e80-a740-11eb-946d-f7c2b5b5cf32.PNG)

## Expected result

consistency in the noise patterns.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 245-2

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 90.0.4430.93
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
C3 release: r245.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 253 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6172)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by oosyrag** [comment]
Nothing to do with movement, negative inputs fed into cellular and voronoi noise will result in these breaks - horizontal breaks for -y values, and vertical lines for -x values. Other noise functions are not affected.

**Comment by dupuqub** [comment]
That's a nice catch, but it's a bug, right?

**Comment by oosyrag** [comment]
Yes, didn't mean to imply it wasn't. Just narrowing the scope.

**Comment by AshleyScirra** [comment]
It looks like there were rounding errors when using negative numbers in the Voronoi and Cellular functions. It should be fixed in the next beta.
