### ISSUE TITLE
Issue with Mobile Advert and Xcode project

### ISSUE THREAD

**Issue by sam467** [Scirra/Construct-3-bugs#4767]
Hi,
I have been trying to build a Xcode Project from last few days i am trying to add Mobile Advert but as soon as i try to add that and build it fails the project i am attaching the error code i am getting please help me out with this.

Error: Discovered platform "ios@6.2.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-ios@6.2.0
Adding ios project...
Creating Cordova project for the iOS platform:
Path: ~~/ios
Package: com.lenasciencelabrun.lenascience
Name: Lena's Science Lab Run
iOS project created with cordova-ios@6.2.0
Plugin 'cordova-plugin-inappbrowser' found in config.xml... Migrating it to package.json
Plugin 'construct-mobile-advert' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-splashscreen' found in config.xml... Migrating it to package.json
Plugin 'construct-plugin-file' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-statusbar' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-inappbrowser". Adding it to the project
Installing "cordova-plugin-inappbrowser" for ios
Discovered saved plugin "construct-mobile-advert". Adding it to the project
Installing "construct-mobile-advert" for ios
Installing "cordova-plugin-add-swift-support" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Discovered saved plugin "cordova-plugin-splashscreen". Adding it to the project
Installing "cordova-plugin-splashscreen" for ios
Discovered saved plugin "construct-plugin-file". Adding it to the project
Installing "construct-plugin-file" for ios
Discovered saved plugin "cordova-plugin-statusbar". Adding it to the project
Installing "cordova-plugin-statusbar" for ios
Running manual pod update
Pod update failed
Update all pods
Updating local specs repositories

CocoaPods 1.10.1 is available.
To update use: `sudo gem install cocoapods`

For more information, see https:/~~/blog.cocoapods.org and the CHANGELOG for this version at https:/~~/1.10.1

Analyzing dependencies
[!] The target `Lena's Science Lab Run` is declared multiple times for the project `Lena's Science Lab Run.xcodeproj`.

CordovaError: Promise rejected with non-error: undefined
at ~~/cordova:29:15
at processTicksAndRejections (~~/task_queues.js:94:5)

**Comment by AshleyScirra** [comment]
It looks like the build server got stuck, so I rebooted it, and now I can build a project with Mobile Ad in it.

I can't check any further because this report does not follow the guidelines, so closing.
