### ISSUE TITLE
Altering view pannels causes the editor to break on subsequent start-up

### ISSUE THREAD

**Issue by HDeDeDe** [Scirra/Construct-3-bugs#4769]
## Problem description

Changing the appearance of the editor by placing any views below the main view will cause Construct 3 to display a grey screen the next time it is started. This happens with any project, even one that was created from scratch.

## Attach a .c3p
[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/6389544/New.project.zip)
Any project is enough to reproduce the issue.

## Steps to reproduce

1. Open any project or create a new project
![Screenshot 2021-04-27 232556](https://user-images.githubusercontent.com/21134925/116357252-24009500-a7b1-11eb-82a6-dee04d00d70b.png)

2. Snap any view page to below the main view
![Screenshot 2021-04-27 232633](https://user-images.githubusercontent.com/21134925/116357291-2fec5700-a7b1-11eb-8747-91488b412746.png)
![Screenshot 2021-04-27 232727](https://user-images.githubusercontent.com/21134925/116357303-337fde00-a7b1-11eb-91a5-1b4d20f4589f.png)
3. Restart Construct 3 (Either by refreshing the page or closing the application)

## Observed result
![Screenshot 2021-04-27 232749](https://user-images.githubusercontent.com/21134925/116356737-85743400-a7b0-11eb-9c20-5ee4b5b7f01e.png)
Construct 3 will only display a blank screen on startup until the browser cache is cleared.

## Expected result
![Screenshot 2021-04-27 233211](https://user-images.githubusercontent.com/21134925/116357179-0df2d480-a7b1-11eb-82cc-f04d44290bb7.png)
The editor should have started normally.

## More details

**Affected browsers/platforms:** 
All. Can confirm it affects NW.js, Firefox, and Chromium. Occurs regardless of OS.

**First affected release:** 
Occurs as of r241 and earlier.
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 92.0.4492.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4492.0 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 35 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6589)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
