### ISSUE TITLE
Mesh editor and undo cause crash

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#4770]
## Problem description

Mesh editor and undo cause crash

## Attach a .c3p

https://mega.nz/file/ZYVkWbab#jE2oE2n8TDCe6_U4T5A5JBLUBd5vIi1J_2jSopeSNhM

## Steps to reproduce

1. Add a "Sprite" and create "Mesh" (4x4)
2. Edit Mesh many times
3. Press undo many times
4. Crash

## Observed result

Crash
https://user-images.githubusercontent.com/47735877/116365345-75d30a80-a805-11eb-9c2e-3e47fb4ac4e9.mp4

## Expected result

Not Crash

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'fr' of null @ TypeError: Cannot read property 'fr' of null at d.g.J.Xmb.ij (https://editor.construct.net/r246/components/bars/propertiesBar/propertiesBar.js:90:451) at d.g.J.Xmb.ot (https://editor.construct.net/r246/main.js:835:12) at d.g.J.Xmb.kB (https://editor.construct.net/r246/main.js:852:188) at d.g.J.sva.i8c (https://editor.construct.net/r246/main.js:913:94) at d.g.J.sva.FS (https://editor.construct.net/r246/main.js:913:26) at p.nxa (https://editor.construct.net/r246/components/bars/propertiesBar/propertiesBar.js:18:101) at p.Oi (https://editor.construct.net/r246/components/bars/propertiesBar/propertiesBar.js:16:415) at Array.fSa (https://editor.construct.net/r246/components/bars/propertiesBar/propertiesBar.js:4:193) at d.Event.BRc.Kfd (https://editor.construct.net/r246/main.js:430:387) at window.iib.dispatchEvent (https://editor.construct.net/r246/main.js:426:135)
Stack: TypeError: Cannot read property 'fr' of null at d.g.J.Xmb.ij (https://editor.construct.net/r246/components/bars/propertiesBar/propertiesBar.js:90:451) at d.g.J.Xmb.ot (https://editor.construct.net/r246/main.js:835:12) at d.g.J.Xmb.kB (https://editor.construct.net/r246/main.js:852:188) at d.g.J.sva.i8c (https://editor.construct.net/r246/main.js:913:94) at d.g.J.sva.FS (https://editor.construct.net/r246/main.js:913:26) at p.nxa (https://editor.construct.net/r246/components/bars/propertiesBar/propertiesBar.js:18:101) at p.Oi (https://editor.construct.net/r246/components/bars/propertiesBar/propertiesBar.js:16:415) at Array.fSa (https://editor.construct.net/r246/components/bars/propertiesBar/propertiesBar.js:4:193) at d.Event.BRc.Kfd (https://editor.construct.net/r246/main.js:430:387) at window.iib.dispatchEvent (https://editor.construct.net/r246/main.js:426:135)
Construct 3 version: r246
URL: https://editor.construct.net/r246/
Date: Wed Apr 28 2021 09:01:32 GMT+0200 (közép-európai nyári idő)
Uptime: 158.1 s

Platform information
Browser: Chrome
Browser version: 90.0.4430.93
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
C3 release: r246 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6611)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
