### ISSUE TITLE
Tabbing from Width to Height in Resize Image Canvas window does nothing the first time

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#4774]
## Problem description

In the animation editor's Resize Image Canvas window, when you have selected the "Width (Pixels)" field and then press the tab key to jump to the "Height (Pixels)" field, nothing happens the first time and your input is ignored. If you press tab a second time, it will then work. This problem then appears to temporarily go away...until the next time you open the Resize Image Canvas window, where the issue will attempt to thwart you once again.

## Attach a .c3p

[SpriteResizeTabbing.zip](https://github.com/Scirra/Construct-3-bugs/files/6394562/SpriteResizeTabbing.zip)

## Steps to reproduce

1. Open the attached project or create a new one and create a sprite within it.
2. Open a sprite in the animations editor.
3. Click Resize or press Alt+R to open the Resize Image Canvas window.
4. Click on the "Width (Pixels)" field and, optionally, type a number to change the sprite's width.
5. Press the tab key once as if to jump to the Height field, but notice that instead, you stay on the Width field and can even still type numbers in the Width field.
6. Press the tab key a second time, noting that this time you will jump to the Height field.

## Observed result

You have to press tab twice to move from the Width field to the Height field, when nowhere else is a double-press of tab required to jump from one field to the next...

## Expected result

One press of the tab key jumps from the width field to the height field.

## More details
This may seem incredibly minor but like the issue of the properties info box popping up and canceling a property field selection, this can come up a dozen times or more in a day, particularly when modifying the size of several art assets for new projects, and this small hiccup in the process can cause confusion and frustration after occurring enough times in a row.

**Affected browsers/platforms:** Firefox, Chrome.

**First affected release:** No later than r241.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 88.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
C3 release: r241 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 423 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
