### ISSUE TITLE
When copying and pasting an object type in the project bar, its family isn't kept like when cloning types

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#4775]
## Problem description

When you select an object in the project bar and copy and paste it, the copied type keeps all instance variables and effects from the original, but not any families from the original. Interestingly, right-clicking and _cloning_ an object type does ensure the newly created object type is added to the family though, which is why it seems unintentional that copy/pasting would not do the same.

## Attach a .c3p
[SpriteCopyNoFamilies.zip](https://github.com/Scirra/Construct-3-bugs/files/6394682/SpriteCopyNoFamilies.zip)

## Steps to reproduce

1. Open the attached project.
2. Note the sprite is part of a family.
3. Select the sprite in the project bar and press ctrl+c, ctrl+v to quickly copy and paste the object type to make a variant of the sprite.
4. Note that when doing so, the copy keeps its instance variables and effects but is not kept in the family.
5. Now, select the original sprite and right-click and clone it.
6. Note that this time, the copy has been added to the family as well.

## Observed result

Copying and pasting an object type such as with the faster ctrl+c, ctrl+v shortcuts leaves the copy out of the family, unlike the method of right-clicking and cloning the object.

## Expected result

Copying and pasting an object type in the project bar copies its membership into the families the original was part of as well.

## More details

**Affected browsers/platforms:** Firefox, Chrome.

**First affected release:** No later than r241.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 88.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
C3 release: r241 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 423 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next beta.
