### ISSUE TITLE
In animations editor, selecting whole image and pressing Del deletes animation instead of image

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#4778]
## Problem description

In the animations editor, when pressing ctrl+A to select the entire image and then pressing the Delete key to erase the entire selected image, instead the entire animation is deleted - or if there is only one animation remaining, a message pops up explaining that the last animation cannot be deleted.

## Attach a .c3p

[DeleteSelectedImage.zip](https://github.com/Scirra/Construct-3-bugs/files/6394907/DeleteSelectedImage.zip)

## Steps to reproduce

1. Open the attached project.
2. Open the sprite in the animations editor.
3. Press ctrl+A to select the entire image, noting the "marching ants" effect surrounding the selection box to indicate you've now selected the image and not the animation that the image is a part of.
4. Press the delete key, but note that instead of deleting the selected image on the canvas, Construct instead interprets this as an attempt to delete the entire animation.

## Observed result

When pressing the delete key after opening the animations editor and selecting the image with ctrl+A, C3 tries to delete an animation instead of the image you've selected on the canvas.

## Expected result

Pressing ctrl+A and then the delete key only deletes the image you've selected, not the entire animation it's a part of.

## More details
This one actually seems browser-specific? Chrome does not appear to have this issue, but Safari doesn't even let you press ctrl+A to select the canvas image at all until you manually choose the Selection too in the animations editor.

**Affected browsers/platforms:** Firefox, Chrome, Edge.

**First affected release:** No later than r241.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 88.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
C3 release: r241 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 423 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This is fixed in the next beta.

The DELETE key is used to delete many things in the animations editor, in order to decide what to delete, the editor checks which panel has focus. If the frames panel has focus, the selection in that panel will be deleted, same for the animations panel and the same for the main panel (drawing area).

The fix makes sure the main panel has focus after using the CTRL + A shortcut, so pressing DELETE afterwards will delete the selection. If a different panel gains focus before pressing DELETE (by clicking on it for example), then the next time DELETE is pressed that panel will be affected.
