### ISSUE TITLE
'Key is down' gets stuck in down position

### ISSUE THREAD

**Issue by Unconected** [Scirra/Construct-3-bugs#4780]
## Problem description

'Key is down' gets stuck in down position

## Attach a .c3p

https://www.dropbox.com/s/144i1rebrtzsmla/Key_Stuck_in_down.c3p?dl=0

## Steps to reproduce

1. Hold down arrow key up/down
2. Click in TextInput object
3. Release key up/down

## Observed result

Sprite object keeps moving when you click in TextInput object and release held down key.

## Expected result

Sprite object should stop moving when you click in TextInput object or when key is released after clicking in TextInput object. I am not sure which one.

## More details

I see the same results in C3 Preview/Debugger as I do in Windows wrapper (WebView2) (64-bit)
I exported into Signed release APK 5.1. I couldn't use keyboard because I didn't have a TextInput object in focus so keyboard display didn't come up. My Android doesn't have arrow keys anyways. I assume there may be a few Androids that do, so I assume this could be tested on some devices or emulator.

If this isn't a bug I would like to know how to fix it.
I am planning on releasing as APK but will eventually place it on web somewhere. I assume it would have the same issues on most browsers since Chrome has most of the market share and most browsers are chrome based.

## System details

Platform information
Browser: Chrome
Browser version: 90.0.4430.93
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 305 mb
Storage usage (approx): 41 mb (13.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 950 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
This is currently by design. When you focus a form control like a text field, all keyboard input is routed to that control. This means if you focus the form control while a key is down, the "key up" event is sent to the form control instead of the game, which means the game still thinks the key is down. I'm not sure what can be done about this, since if we instead allow the key events in the form control to reach the game anyway, then you get unintended effects like WASD controls activating while typing in a text field, which is the reason the key handling works this way. Maybe we can add some special handling for key up events or something.

**Comment by AshleyScirra** [comment]
I added a similar mechanism for the next release as is used for when the entire window is unfocused - that also releases all key down states to avoid a similar problem when you hold a key while switching to another window. Now it applies the same process when you focus a form control like a text input. So this should be working in the next beta.

**Comment by Unconected** [comment]
Thank you.
