### ISSUE TITLE
rtl support in C3 is kinda broken

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#4782]
## Problem description

I know that rtl support is an endless pit of problems, I'm still gonna report these issues anyway and hope they get fixed one day

## Attach a .c3p

[rtl broken.zip](https://github.com/Scirra/Construct-3-bugs/files/6405807/rtl.broken.zip)

## Steps to reproduce

1. Hit play

## Observed result

There are three issues to outline here, which are IMO the three biggest issues with the current RTL in C3:
- The typewriter text still draws from left to right, so this means that despite my text being aligned to the right, it still starts typing from the left
- The tags "break" the rtl, and each tag appends the rest of the text to the left of what's already there instead of to the right
- The tags "break" the flow of letters. Just like with the kerning issue, the current bbcode tag system breaks the links between letters, which is far more unnacceptable than kerning, because it renders the text completely unreadable.

## Expected result

To be fair, with how big of an issue RTL is, I don't expect much. But please look into this, and maybe you might find a way to fix part if not all of these, and chances are it will also fix other issues with the BBCode tag system.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
RTL text is complicated and involves changing a lot of things. Full support for RTL would probably also extend to a range of other features too, like form controls, and maybe even co-ordinate systems and support for flipping layouts and menus. I think this all qualifies as a feature request than a bug, so closing - please file as a suggestion if this is important to you.

Even just within the scope of the text object, the rules around [bidirectional text](https://en.wikipedia.org/wiki/Bidirectional_text) are super complicated (see how many types of character and text are covered in that article). We had to write our own text layout engine to draw text to canvas, composed merely of the measureText/fillText APIs. Browsers have sophisticated text layout engines that entire teams of developers have spent fine tuning. I don't think it's feasible to expect the same from canvas-drawn text - it's something you would have to turn to HTML instead to get properly supported.
