### ISSUE TITLE
Whitelist plugins (Essential)

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4784]
Hi, in continuation to [previous topic](https://github.com/Scirra/Construct-3-bugs/issues/4747), please update the essential addons below.

## Essential (Bug fix)
All other versions whitelisted in the build service have broke, due to dynamic dependency versions I've previously set.
This new version (0.7.0) should now have static dependency versions, it should be stable for months now.
```
chadori-mobile-ironsource
chadori-mobile-ironsource-debug
chadori-mobile-ironsource-adcolony
chadori-mobile-ironsource-admob
chadori-mobile-ironsource-amazon
chadori-mobile-ironsource-applovin
chadori-mobile-ironsource-chartboost
chadori-mobile-ironsource-facebook
chadori-mobile-ironsource-fyber
chadori-mobile-ironsource-hyprmx
chadori-mobile-ironsource-inmobi
chadori-mobile-ironsource-maio
chadori-mobile-ironsource-pangle
chadori-mobile-ironsource-pangle-cn
chadori-mobile-ironsource-tapjoy
chadori-mobile-ironsource-unityads
chadori-mobile-ironsource-vungle
```
All versions in `0.7.0`.

Thank you very much!
And sorry for the trouble with the whitelisting.

**Comment by AshleyScirra** [comment]
All 15 ad networks broke at once? Don't they use different dependencies?

**Comment by Chadori** [comment]
@AshleyScirra Yeah, unfortunately. 
It broke due to my previously mentioned attempt to auto-update, also all adapter versions are required to be aligned.
Now, I'm using static dependencies, the usual way, which makes it stable now unlike before.

**Comment by AshleyScirra** [comment]
Updated build service to allow these.

**Comment by Chadori** [comment]
Thank you!
