### ISSUE TITLE
Whitelist plugins (Routine only)

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4785]
Hi, in continuation to [previous topic](https://github.com/Scirra/Construct-3-bugs/issues/4747), please update addons below. However, they are not urgent, unlike the [essential ones](https://github.com/Scirra/Construct-3-bugs/issues/4784).

## New addons (Routine)
```
chadori-mobile-ironsource-smaato@0.7.0
chadori-mobile-ironsource-snap@0.7.0
```

## Routine only (AppFlyer's Android X support)
```
cordova-plugin-appsflyer-sdk@6.3.0
```

Thank you very much!
And sorry for the trouble with the whitelisting.

**Comment by Chadori** [comment]
Edited, AppsFlyer SDK updated.

**Comment by AshleyScirra** [comment]
Build service updated to allow these plugins.

**Comment by Chadori** [comment]
Thanks!
