### ISSUE TITLE
Tilemap collisions edit crash 246

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4786]
## Problem description
Beta 246 crashes the editor when selecting a tile to edit its collision polygon

## Attach a .c3p
https://www.dropbox.com/s/udmqq4drwr888kj/tilemapscollision246.c3p?dl=0

## Steps to reproduce

1.Open the project, or the Tilemap editor example
2.Click on the Tilemap section of the editor
3.Double click a tile to edit the collisions

## Observed result

Crash
## Expected result
No crash

## More details

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6627)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
</details>

**Comment by DiegoScirra** [comment]
This is related to #4772. The fix for that issue caught this one as well. Will be available in the next beta.

**Comment by pigmalien** [comment]
Cool. Thanks!
