### ISSUE TITLE
Adding Tilemap objects presents "name taken" dialog no matter what name is entered

### ISSUE THREAD

**Issue by nrusconi** [Scirra/Construct-3-bugs#4787]
When adding a tilemap object the "name taken" dialog is shown no matter what name is entered. 

**Steps to reproduce**

1. Create a new project
2. Add Object
3. Select Tilemap
4. Click add

**Observed result**
Name taken dialog is presented no matter what name is entered. No object is created
**Expected result**
A new object should be created and the image editor opens. 

**More details**
Affected browsers/platforms: 90.0.4430.93 (Official Build) (arm64) 
First affected release: r246
All new projects effected, unable to attach a project as it would be empty.

<img width="431" alt="Screen Shot 2021-05-01 at 5 41 38 pm" src="https://user-images.githubusercontent.com/5958309/116775147-a5537280-aaa4-11eb-9fd5-26aa075e3745.png">
<img width="619" alt="Screen Shot 2021-05-01 at 5 41 56 pm" src="https://user-images.githubusercontent.com/5958309/116775149-a71d3600-aaa4-11eb-8d3d-30efb353b6ed.png">
<img width="632" alt="Screen Shot 2021-05-01 at 5 42 03 pm" src="https://user-images.githubusercontent.com/5958309/116775150-a84e6300-aaa4-11eb-85be-8db269d5effb.png">
<img width="663" alt="Screen Shot 2021-05-01 at 5 42 11 pm" src="https://user-images.githubusercontent.com/5958309/116775151-a97f9000-aaa4-11eb-8a39-d3a16f95b66a.png">

**Comment by DiegoScirra** [comment]
This is related to #4772. The fix for that issue caught this one as well. Will be available in the next beta.
