### ISSUE TITLE
Mouse sprite won't disappear on page refresh.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4789]
The mouse sprite won't disappear on the start of the layout after refreshing the page if during the last preview the mouse cursor was set to be a sprite.

EDIT: In a second (and very possibly related) issue, but unfortunately way less reliable, the mouse cursor won't disappear in the start of the layout even when previewing the problem in a fresh window.

## Attach a .c3p

[mouse.zip](https://github.com/Scirra/Construct-3-bugs/files/6410921/mouse.zip)

## Steps to reproduce

1. Set the mouse cursor style to "None" in the start of the layout.
2. Set it to a Sprite somewhere in the code.
3. Refresh the page (do NOT close the page, if you close the page, there'll be no issue).
4. If the mouse was in its Sprite state before the refresh, it'll ignore the "set style to none" in the start of the layout and still show up.

## Observed result

Cursor not disappearing in the start of the layout.

## Expected result

Cursor disappearing in the start of the layout regardless of whether I refresh or close the page.

## More details

**Affected browsers/platforms:** Latest Chrome.
**First affected release:**  I only cared to isolate the problem in 246, but it's been possibly more than a year since I faced this issue for the first time.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 90.0.4430.93
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
C3 release: r246 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 313 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6627)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I can't reproduce this. If I run the project, press space to change the cursor, then press F5 to reload the page, it reverts the mouse back to the "none" style. So it all appears to be working correctly. Can you find a way to reliably reproduce the issue?

**Comment by dupuqub** [comment]
That's weird because for me it is super reliable, possibly a problem on my end then?

**Comment by AshleyScirra** [comment]
I guess. I checked again and the only thing that looks like it might be wrong is the old cursor is left behind after a reload, but disappears as soon as you move the mouse again, but that seems like a very minor issue. You could try filing the issue at crbug.com, but they might want a more minimal repro...

**Comment by dupuqub** [comment]
that's exactly what happens to me. And the "disappears after moving the mouse" is precisely what I want to avoid if a player just uses the gamepad, but I guess refreshing the page isn't something I have to worry about when deploying, so it's fine probably.
