### ISSUE TITLE
No tutorial on how to successfully publish an iOS Xcode project (I'm having issues with it)

### ISSUE THREAD

**Issue by part12studios** [Scirra/Construct-3-bugs#479]
## Problem description
how do I build / test / publish an xcode project with a C3 xcode project successfully this way.  

## Attach a .c3p
N/A

## Steps to reproduce
1. I have an exported xcode project
2. I have xcode and a developer license
3. I open the project in xcode
4. I build the project and it says "success"
5. no simulator launches the app

## Observed result
I have some xcode experience (but some of your paying customers do not) and I have a developer license and I have published games with C2 before using XDK and CocoonIO at different times with application loader. 

I was able to get the project to build successfully from the get go without much hassle.  I had some warning/errors that a "correct errors" button seemed to clean up so all this is great.  Where I hit trouble was that no simulator would launch the game nor would the game push to my iOS hardware device even though xcode does see that the device is attached.  

I downloaded two different images making the assumption that maybe xcode doesn't include any until you need them.. I was told by Nepeo to not use the default "cordovalib>iphone 7 but what i've done so far has not fixed this..  maybe i need to make a new scheme?  what is a scheme?  

https://www.scirra.com/forum/viewtopic.php?f=191&t=192567&sid=6f200572994abb4aaffb7db20a5689e9&p=1126922#p1126922

## Expected result
I would love to see my project build and launch a simulator / install on my device for testing to see if performance is sluggish on it like the cordova builds are in android

## Affected browsers
Not a browser issue

## System details
Using R36..  Seirra OS..  iMac..  latest standard version of xcode (from app store)

</details>

**Comment by Scott943** [comment]
When you export the build in Xcode, is it to a 'General iOS Device' because that may be the problem?
Ensure you export it to a simulator or a device and check back with me :+1:

**Comment by part12studios** [comment]
Ok I’m happy to report this time I did another unminified export using r36 (not 100% sure what i exported with last time, but i thought it was r36 as well)  the simulator did fire off this time without any configuring needed on my end.  

It loaded up but it hung when loading (similar to the issue on android, stopping at 50% or so at the c3 loading splash) 

To then troubleshoot some I went back and did a minified build it did not even get that far.  just a black screen after the simulator ran.  no c3 screen appears.  

i went back again and saw that the c3 splash works if i reverted to the unminified version.

not that i get 2 warnings when i open a project and when i run it becomes 52 warnings.. nothing that prevents it from crashing but that seems like a lot of warnings to ignore that one of them might be contrbuting to its failure to fully launch.. and seeing minifying definitely has an impact on the app running.  

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios <http://part12studios.com/>

**Comment by Scott943** [comment]
Yes, this is exactly what I had (I have opened two other issues on iOS exports) I to had a lot of warnings (80 in total) and yes, there is a black screen if you click the minifier screen. I believe you can get Xcode to clean up these warnings, but @pwrtoppll has not got back to me with that yet.

**Comment by part12studios** [comment]
Good to know it's not just me.  That said, i wonder what we're doing different that Scirra is doing when they test their xcode exports?  Anyone else had a successful xcode export? 

my game is not complex or using anything more than basic physics and some bullet behaviors.. 

http://part12studios.com/temp/Games/soaring/

so I find it hard to believe that somewhere in this game is some poor design decisions that would be the cause of it failing to launch.

**Comment by Scott943** [comment]
For me, all playable features always work even on Test Flight despite all the warnings. However, the game center and in-app purchasing features do not function at all - but I doubt that is due to the warnings in Xcode. 

I believe Scirra is going to rewrite all the plugins, saying,

'At the moment we're planning to create new Mobile advertising and Mobile purchases plugins. I'm due to do some iOS development testing soon, so will try to figure out whats up with gamecenter when I start working on that. I'm hoping some of the depreciation warnings will go away when we move to cordova 7, but at the moment cordova 7 isn't stable enough to use. I'll review what warnings we're getting and will look into what we can do about them.'

**Comment by part12studios** [comment]
I’m glad it’s working for you.  I just don’t understand why it wouldn’t work for me.  Does the simulator allow you to test ads?  one thing that always made c2 development was the inability to test any 3rd party services (admob for example) without having to push an actual app on a device.  previewing from a browser is great for the game part but not for testing the final mobile product.  

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios <http://part12studios.com/>

**Comment by Scott943** [comment]
Yes I agree, that is a flaw in browser preview, but cannot easily be sorted out without compromising the ease of previewing. Admob, like Game Center and In-app purchases are not currently functioning in C3 exports either, but I believe they will normally work inside the Xcode simulator when fixed!

**Comment by part12studios** [comment]
that would be so nice.  android needs a similar solution..  really a universal solution would be ideal in preview (android more likely would have a way to do it in your pc/mac) like bluestacks or something like that which would run a simulator from C3.

**Comment by AshleyScirra** [comment]
We're aware of the lack of manual and tutorials, and we're going to address it over the coming weeks. It's already on our todo list and since this isn't really a bug, closing this report.
