### ISSUE TITLE
Cache cause Chromium "Aw, Snap" error.

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#4790]
## Problem description

Editor's cache cause Chromium "Aw, Snap" error.

## Attach a .c3p

Just an editor need.

## Steps to reproduce

1. Clear cache
2. Open the editor (will not cause problem) and wait the cache.
3. Reload. (throw some error) 
![Képernyőkép – 2021-05-02 15-39-24](https://user-images.githubusercontent.com/47735877/116815706-1192ac80-ab5f-11eb-80aa-3b3b2377f53b.png)

4. Reload (throw more error and "Aw, Snap" crash or freeze the tab) 
![Képernyőkép – 2021-05-02 15-37-40](https://user-images.githubusercontent.com/47735877/116815735-28390380-ab5f-11eb-8e51-d049aa747f6c.png)

5. Might need more reload...

## Observed result

Crash the browser or freeze the tab

## Expected result

Not crash the browser. (console error logs not problems)

## More details

It might be a Chromium bug.
I use Ubuntu 20.04 LTS. Chromium form ubuntu store with latest update.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 90.0.4430.93
Browser engine: Chromium
Context: browser
Operating system: Linux
Operating system version: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
C3 release: r246 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 130 gb
Storage usage (approx): 1.2 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel Open Source Technology Center)
Renderer: ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2), OpenGL 4.2 (Core Profile) Mesa 20.0.8)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It works fine for me on Windows. I am also sure we'd be hearing a lot more about it if merely reloading Construct crashed the browser, so it sounds like an issue specific to your Linux system. Besides "Aw snap" crashes are in Chrome, which you'd need to report to Google to have fixed - you can try reporting it to them at crbug.com.

**Comment by henrikszucs** [comment]
I reported the bug in: https://bugs.chromium.org/p/chromium/issues/detail?id=1205816
