### ISSUE TITLE
(CMD + A) not selecting more than 95 frame

### ISSUE THREAD

**Issue by karimlahbach** [Scirra/Construct-3-bugs#4791]
## Problem description
if you open animation editor and try to imports frames and you use (cmd + a) to select everything 
the selection will stop in frame 95 and the rest will not get selected

## Steps to reproduce

1. open animation editor
2. imports frames
3. use CMD + A to select more than 200 frame

## Observed result
You will notice that the selection stop in 95 frame or maybe less

## Expected result
everything should be selected

## More details

**Affected browsers/platforms:** 
Chrome Version 90.0.4430.93 (Official Build) (x86_64)

**First affected release:** 
Stable and Last Beta 246
## System details

<details><summary>View details</summary>

i'm using MACBOOK PRO 2014 core i7 16 gb ram

</details>

**Comment by DiegoScirra** [comment]
Can you explain what you are doing? Because there is no CMD + A shortcut to select all frames.

**Comment by DiegoScirra** [comment]
Wait... are you trying to use CMD + A on the Finder window to select files that will then be imported into C3?

Or are you trying to use CMD + A to select all frames in the frames panel, after importing is complete?

**Comment by karimlahbach** [comment]
Hi @DiegoScirra 
to answer your question (Yes i'm trying to use CMD + A on the Finder window to select files that will then be imported into C3)

**Comment by DiegoScirra** [comment]
I see...

C3 triggers the dialog to pick files, but other than that is a completely separate process which is handled by the browser, in turn the browser is relying on the OS to show the file picker. That is why in OSX it looks like a Finder window, in Windows like a File Explorer window and in Linux like what ever file manager you are using.

Unfortunately this means it is out of our control, so I am almost certain I won't be able to fix this issue, but I'll take a look to at least verify it.

**Comment by karimlahbach** [comment]
Thank you so much to be honest is not a big deal i can use the mouse for the selection is just when you have over 200 frames it can take time

**Comment by DiegoScirra** [comment]
I just tried doing this in my extremely old MacBook Air from 2010, and it works. I was able to select all of 600 test files using CMD + A and then import them. As I said , my mac is very old and it is running OSX 10.13.16, so maybe it is a problem with newer versions of OSX.

Which version of OSX are you using? And does this happen consistently? Does the shortcut work properly if you attempt the same kind of selection using Finder normally, outside of C3.

**Comment by karimlahbach** [comment]
https://user-images.githubusercontent.com/22240696/117349694-378bba00-ae9b-11eb-8378-901a55ba2a8c.mp4

this a video to show you the bug ( as you can see the selection stop in frame 94) 
1- i'm using Mac os Big Sur 11.2.3
2- it happen every time you have more than 100 frame 
3- i try to use the shortcut outside c3 in to work fine without problems

finally i have no idea if this a (Mac Os bug) or (chrome browser bug) but i think it going to be a browser problem since it work fine outside c3

**Comment by karimlahbach** [comment]
New Update : i try this on Safari and everything work fine
i think it a google chrome bug

**Comment by DiegoScirra** [comment]
Going to close this one, as there is nothing we can do.
