### ISSUE TITLE
Undo crashes when instance value type is changed

### ISSUE THREAD

**Issue by erenertugrul** [Scirra/Construct-3-bugs#4792]
## Problem description

Undo crashes when value type is changed

## Attach a .c3p
[bb.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6412285/bb.c3p.zip)

## Steps to reproduce

1. add  instance variable  to text object as string type (or spritefont,textinput)
2. set initial value
3. Change string type to number
4. click undo button

## Observed result

crashed

## More details

https://user-images.githubusercontent.com/27224622/116828573-3c552300-aba8-11eb-9500-1d815db1f528.mov

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next beta.
