### ISSUE TITLE
Timeline crashes when adding sprite to timeline while timeline window is in popup

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#4795]
## Problem description

Timeline crashes when adding sprite to timeline while timeline window is in popup

## Attach a .c3p

[Bug TL.zip](https://github.com/Scirra/Construct-3-bugs/files/6415579/Bug.TL.zip)

## Steps to reproduce

1. Open the timeline window
2. Click on the timeline window title bar and click **Open to popup window**
3. Right click on the yellow sprite instance
4. Choose **Timeline,** then **Add to timeline**

## Observed result

Editor Crash

## Expected result

Instance added to timeline

## More details

**Affected browsers/platforms:** Firefox and Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information

Type: unhandled exception
File: https://editor.construct.net/r241/main.js, line 440, col 17
Message: TypeError: f is null
Stack: ca@https://editor.construct.net/r241/main.js:440:17 e.YA@https://editor.construct.net/r241/components/bars/timelineBar/timelineBar.js:337:501 f.Pxd@https://editor.construct.net/r241/components/bars/timelineBar/timelineBar.js:334:134 f.u4@https://editor.construct.net/r241/components/bars/timelineBar/timelineBar.js:333:329 @https://editor.construct.net/r241/components/bars/timelineBar/timelineBar.js:180:87 d.l@https://editor.construct.net/r241/main.js:291:219 e.xj@https://editor.construct.net/r241/components/bars/timelineBar/timelineBar.js:67:84 p@https://editor.construct.net/r241/components/bars/timelineBar/timelineBar.js:33:319 q@https://editor.construct.net/r241/components/bars/timelineBar/timelineBar.js:33:497 f.W8b@https://editor.construct.net/r241/components/bars/timelineBar/timelineBar.js:34:195 f.btd@https://editor.construct.net/r241/components/bars/timelineBar/timelineBar.js:34:303 f.np@https://editor.construct.net/r241/components/bars/timelineBar/timelineBar.js:31:131 h.gv@https://editor.construct.net/r241/components/bars/timelineBar/timelineBar.js:111:460 h.lrd@https://editor.construct.net/r241/components/bars/timelineBar/timelineBar.js:99:472 h.R0c/<@https://editor.construct.net/r241/components/bars/timelineBar/timelineBar.js:88:405 acd@https://editor.construct.net/r241/main.js:428:387 dispatchEvent@https://editor.construct.net/r241/main.js:424:135 oz@https://editor.construct.net/r241/main.js:2133:421 uPb@https://editor.construct.net/r241/projectResources.js:366:231 vPb@https://editor.construct.net/r241/projectResources.js:366:322 VUa@https://editor.construct.net/r241/components/editors/layoutView/layoutView.js:61:419 Ayd/<@https://editor.construct.net/r241/components/editors/layoutView/layoutView.js:25:117 Kd/<@https://editor.construct.net/r241/main.js:1247:431
Construct 3 version: r241
URL: https://editor.construct.net/
Date: Mon May 03 2021 16:46:55 GMT+0200 (Eastern European Standard Time)
Uptime: 59.1 s
Platform information

Browser: Firefox
Browser version: 88.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
C3 release: r241 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 610 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
