### ISSUE TITLE
Group-Dependent Event Disabling

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#4797]
Please let me know if this is as expected, if so I will need to be more careful with toggle disabling groups.

Version: r245.2

[Group_Disable_Test.zip](https://github.com/Scirra/Construct-3-bugs/files/6417038/Group_Disable_Test.zip)

1. Open project

2. Go to event sheet

3. Toggle Disable the group named Test Group

4. Drag Test Group Outside of Overhead

5. Toggle Enable Test Group

Result: The group itself will be enabled while the events underneath will still be disabled. This works both ways, if you apply a toggle disable to the group and then move it either outside of a top level group or into a top level group it will not apply its toggle disable/enable state to the associated events.

Ideal result: When re-enabling groups that have been moved outside of their top level group, applying the enable to the group and the events beneath, especially to collapsed groups, is preferred. I ran into issues where the collapsed group is toggle enabled but collapsed, however when I opened several of these groups I came to find the events were still disabled.

**Comment by AshleyScirra** [comment]
It's currently working by design. At step 3 you have the group and all its contents selected. At step 5 you have only the group itself selected and not its contents. Toggling disabled only affects the selection.

**Comment by OneRepCloser** [comment]
If I may ask, what's the rationale behind a whole selection turning into only the group being selected once moved outside of a top level group?
