### ISSUE TITLE
need Whitelist plugin info

### ISSUE THREAD

**Issue by EMI-INDO** [Scirra/Construct-3-bugs#4799]
Is this still under review or has it been reviewed

New `@1.7.1`

https://github.com/Scirra/Construct-3-bugs/issues/4757#issuecomment-828483373

this is still `@1.2.2`

https://www.construct.net/en/forum/construct-3/plugin-sdk-10/build-server-cordova-plugin-149266

**Comment by AshleyScirra** [comment]
`admob-plus-cordova@1.7.1` and `cordova-plugin-consent@2.1.4` are already allowed on the build service, as originally requested in #4757. I just double-checked that this is correct.

**Comment by fredriksthlm** [comment]
@AshleyScirra , I think you misunderstood this.
The guy asked since on the forum post it still says 1.2.2, and not 1.7.1, even though you have whitelisted the new one. The same thing for the other plugin, consent.
But maybe you don't update the forum post any longer?

**Comment by AshleyScirra** [comment]
Oh, the forum post is out of date, that's all. The build service is indeed updated. I'll update the forum post soon.
