### ISSUE TITLE
Random crash on Bullet Stepping example

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-3-bugs#48]
## Problem description

I opened the Bullet Stepping example.
I selected Event Sheet 1.
After a few seconds, without me having made any inputs, the editor crashed. 

## Attach a .c3p

No changes were made to the example

## Steps to reproduce

1. Open Bullet Stepping example
2. Select Event Sheet 1
3. Wait 10 seconds

May not be reproducible.

## Observed result

Editor Crashed

## Expected result

No crash :)

## Affected browsers

* Chrome: yes

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r16/main.js, line 63, col 172716
Message: Uncaught RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
Stack: RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation at ee.ǃLkj.ǃLVm (https://editor.construct.net/r16/main.js:63:172716) at ee.ǃLkj.ǃLyR (https://editor.construct.net/r16/main.js:63:211540) at ee.ǃLkj.ǃLyd (https://editor.construct.net/r16/main.js:63:213183) at HTMLDocument.ǃLyq.oe (https://editor.construct.net/r16/main.js:63:208988) at HTMLDocument. (https://editor.construct.net/r16/main.js:2:278451)
Construct 3 version: r16
URL: https://editor.construct.net/index.html
Date: Sat Apr 08 2017 13:51:38 GMT+0100 (GMT Summer Time)
Uptime: 3541.5 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
Can't reproduce, and error message looks like a straightforward "out of memory".
