### ISSUE TITLE
After modifying instance variable in Array/Dictionary, "Save" button won't light up.

### ISSUE THREAD

**Issue by ColorfulCakeChen** [Scirra/Construct-3-bugs#480]
## Problem description

After modifying the instance variable in Array (or Dictionary) plugin, the "Save" button won't light up. That is, the modification seems not be viewed as something has changed, so we can not save project file. (Although the undo list is correct: we can undo the modification without problem.)

The same modification, however, has no problem if the instance variable is not inside Array or Dictionary plugin (e.g. Sprite plugin).

## Attach a .c3p
[Test_ArrayDictionary_InstVar_Modify_NoDirty.zip](https://github.com/Scirra/Construct-3-bugs/files/1065673/Test_ArrayDictionary_InstVar_Modify_NoDirty.zip)

## Steps to reproduce

1. Open the project file.
2. Modify any instance variable of Array (or Dictionary).

## Observed result

The "Save" button (at the right of the "Menu" button) will not light up. (i.e. can't save project file)

## Expected result

The "Save" button should light up, so it is possible to save the project file.

## Affected browsers

* Chrome: yes
* Firefox:
* Edge:
* Safari:

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.86
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5625
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
C3 release: r36

Local storage
Storage quota (approx): 9.3 gb
Storage usage (approx): 264 mb (2.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for r37
