### ISSUE TITLE
Tween Scale Not Scaling from 0 to 1.

### ISSUE THREAD

**Issue by Chroma72** [Scirra/Construct-3-bugs#4800]
## Problem description
I have an object that I create on start of layout (initially visible is true). Then I set scale to 0. Then I set the Tween property "" Scale to 1, 1 in 3 seconds. But it's not working.

Scale is supposed to go off the image's original dimensions, so I do believe this is a bug with Tween.
If I set an image's size or scale to 0, the ImageWidth still reads as the original value (in my case it's 64) which is the correct behavior. If you set the Scale directly, it scales to the correct size, ie. setting scale to 0.5 make the image half size. But if you set the scale to 0 and then Tween the Scale from 0 to 1, the Scale stays at 0.

Looks like the Tween Scaling is multiplying against the Width and Height (current image size), instead of ImageWidth and ImageHeight (original image size).

## Attach a .c3p
I have attached a zip file with TweenScaleBug.c3p inside.

Just run the attached TweenScaleBug.c3p

1. Just run the attached TweenScaleBug.c3p
2.
3.

## Observed result

The sprite (yellow square) did not scale up to 1.

## Expected result

The yellow sprite (a simple square should have scaled from 0 to 1 over 2 seconds).

## More details
This happened on Chrome. Unable to test other browsers.

[TweenScaleBug.zip](https://github.com/Scirra/Construct-3-bugs/files/6424699/TweenScaleBug.zip)
[TweenScaleBug.zip](https://github.com/Scirra/Construct-3-bugs/files/6424700/TweenScaleBug.zip)

**Affected browsers/platforms:** 
Chrome

Don't know. Never tried to use Tween Scale before a couple of weeks ago.

**First affected release:** 
Don't know. Never tried to use Tween Scale before a couple of weeks ago.

## System details
No crash dialog.

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 90.0.4430.93
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 185 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.12029.1000)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks like tweening the scale is a factor, i.e. tweening to a scale of 1 means don't change the size, tweening to a scale of 2 means double the size, etc.

I'm not sure if this is intentional or not - @DiegoScirra should be able to comment.

**Comment by DiegoScirra** [comment]
The tweens are currently using incorrect values for the initial sizes, so the scale calculations are wrong in most cases.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
