### ISSUE TITLE
Drag the image to the Sprite Frames, the frames are out of order

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4801]
## Problem description

I have some files, and they're name is: 
- minor_cups_01_A.jpg
- minor_cups_02_A.jpg
- minor_cups_03_A.jpg
- minor_cups_04_A.jpg
- ...

Attach  :  [Sprite.zip](https://github.com/Scirra/Construct-3-bugs/files/6424769/Sprite.zip)  
  
  
They differ only in number, they are arranged in the order of number.  

![Snipaste_2021-05-05_10-14-43](https://user-images.githubusercontent.com/45864744/117090366-bc3ae300-ad8a-11eb-8523-474c91cd29e0.png)
    
<br><br><br><br>  
    
But When I Drag the image to the Sprite Frames,  the frames are out of order  
![Snipaste_2021-05-05_10-26-39](https://user-images.githubusercontent.com/45864744/117090996-7d0d9180-ad8c-11eb-8dd0-6da866c9bd6e.png)

  
<br><br>  
<br><br>  

If pick the first four
![Snipaste_2021-05-05_10-27-17](https://user-images.githubusercontent.com/45864744/117091003-839c0900-ad8c-11eb-85c3-ed0f315b1665.png)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
What is happening here is that the primary file being dragged acts as the main one, and then the other files are loaded in relation to it.

In your example if you select all the files, and drag them by **minor_cups_01_A.jpg**, they will be imported in the order you want.

This is the behaviour of the browser/operating system, so I am not sure if C3 should attempt to override it. @AshleyScirra?

**Comment by AshleyScirra** [comment]
@DiegoScirra - I think it makes sense to sort all the dropped files alphabetically and import them in that order.

**Comment by DiegoScirra** [comment]
Added in the next beta.
