### ISSUE TITLE
Relative property in the timeline is not respecting the size of the objects

### ISSUE THREAD

**Issue by jogosgratispro** [Scirra/Construct-3-bugs#4805]
I'm using 3 different instances pulling from the same timeline animation. 
The problem is that the timeline doesn't respect the relativeness of the properties as it should. For example, if you have 2 objects of different sizes, the timeline will follow what was applied for the first object (main) and ignore the size of the second object making the animation weird (in this sense, the width and height are either increased or decreased).

Relative property in the timeline is not respecting the size of the objects

## Attach a .c3p

https://www.dropbox.com/s/wpibdawkrwu4x6z/timelineexample.c3p?dl=0

## Steps to reproduce

1. Open the c3p file
2. Play the game
3. Click on each object (button)

## Observed result

The main button (middle-sized on) animation works as expected since the timeline was created for it. The animation for the smallest and biggest buttons doesn't respect their relative size.

## Expected result

Since all 3 objects are using the same timeline (Animation), they should be similar independently from the size.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 90.0.4430.93
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.7100000381469727
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 1.1 tb
Storage usage (approx): 557 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6611)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
WEBGL_webcodecs_video_frame
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment]
What is happening here is that the width and height values stored by the timeline only work for the instance that was used to make the animation, because they are relative to that original size.

If you use the same timeline with an instance with different starting dimentions, the animations will look wrong because the starting sizes are different.

If you wish to make an animation involving size changes that will be used with different instances it is better to use **X Scale** and **Y Scale**, because those values will be applied according to the initial size of each instance.

**Comment by jogosgratispro** [comment]
Hi Diego,

I thought about that but the problem persists. The timeline doesn't respect the relativeness depending on the objects' size.

Here is a new example. I setup a time for the bigger heart and applied to the plus sign button using the relative for X and Y scale. see here » https://www.dropbox.com/s/d9spa8ypktqssb7/timelineexample-v2.c3p?dl=0

**Comment by jogosgratispro** [comment]
Thank you. I appreciate your efforts in helping fixing the issues.
