### ISSUE TITLE
Sine magnitude is broken in r247

### ISSUE THREAD

**Issue by johnsmith27** [Scirra/Construct-3-bugs#4806]
## Problem description

Can't seem to change the sine magnitude with events. For example, if I set magnitude to 50 on start of the layout, the magnitude is set to 0.872664626. Some of my old projects where I was changing magnitude doesn't work anymore.

## Attach a .c3p

https://drive.google.com/file/d/1MV0ytlTW1X0FfUTBMcnbB3EC0_V89UEx/view?usp=sharing

## Steps to reproduce

Follow instructions on the attached example

## Observed result

Any modified magnitude is not what is set in the events.

## Expected result

If I set magnitude to 50, then it should be set to 50, not 0.872664626

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** worked in r241 but broke in r247 (maybe since r245)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, this was an accidental regression introduced in r244. Should be fixed for the next beta.
