### ISSUE TITLE
Whitelist plugins update (routine)

### ISSUE THREAD

**Issue by EMI-INDO** [Scirra/Construct-3-bugs#4808]
hi please whitelist plugins update

new features firebase Functions

@11.0.3  update to  @12.1.0

`cordova-plugin-firebasex@12.1.0`

### New Plugin
`admob-plus-cordova-native@0.1.0`

### thank you

<img src="https://user-images.githubusercontent.com/78555833/117498695-54f87b00-afa4-11eb-94c0-8c4e5bdfbfbc.png" width="500" />

**Comment by AshleyScirra** [comment]
Is this an essential update, or routine maintenance?

**Comment by EMI-INDO** [comment]
> Is this an essential update, or routine maintenance?

This is routine.

Thank you friend.

**Comment by AshleyScirra** [comment]
Build service updated to allow these plugins.
