### ISSUE TITLE
Text Font Size is limit to144pt in Editor.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4809]
## Problem description

Current, Editor can‘t Set the Text Font Size over to 144 pt.   
https://www.construct.net/en/forum/construct-3/how-do-i-8/max-font-size-128448?kws=size%2b144

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I increased the limit to 1000 for the next release.
