### ISSUE TITLE
The Google play plugin doesn't work after the game is released on the play store

### ISSUE THREAD

**Issue by EMI-INDO** [Scirra/Construct-3-bugs#4813]
The Google play plugin doesn't work after the game is released on the play store 

When I use the `google play plugin` together with the `mobile advert plugin`,
(it works) if not download it from play store,
But if it gets released on the play store and I download it from there it won't work.
### When the mobile advert plugin is removed everything works fine.

 Now it works but the mobile advert plugin must be removed,
And now I use AdMob Plus Pro plugin, it works fine.
https://play.google.com/store/apps/details?id=com.fizealshehry.duckyjump

tested with: apk release, aab release.
tested with: c3build service, build cordova cli, build android studio.

sorry if my report does not follow the guidelines, hopefully it can be understood.

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise we cannot investigate your report.
