### ISSUE TITLE
Capx project crashes when trying to open in C3

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#4816]
## Problem description

Trying to open all my old projects to port them to the C3 runtime. This one has some AJAX action which crashes C3. It's a very small project, I doubt it has anything else in it, yet I cannot check too well due to the crash.

## Attach a .c3p

[post.capx.zip](https://github.com/Scirra/Construct-3-bugs/files/6454361/post.capx.zip)

![image](https://user-images.githubusercontent.com/7268697/117710045-50b5a300-b1da-11eb-89bb-ebb68d386206.png)

## Steps to reproduce

1. open the project in c3

## More details

**Affected browsers/platforms:** 

**First affected release:** r241
## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Invalid parameter: 'URLEncode' parameter 0 does not take 'number'
Construct 3 version: r241
URL: https://editor.construct.net/
Date: Mon May 10 2021 21:52:07 GMT+0300 (Eastern European Summer Time)
Uptime: 3 s

Platform information
Browser: Chrome
Browser version: 90.0.4430.93
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6192)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
</details>

**Comment by AshleyScirra** [comment]
This is actually a bug in Construct 2. The project uses a URLEncode() expression with a number. The expression actually takes a string. Construct 2 does not correctly enforce the type check, and incorrectly allows you to make an invalid expression. Construct 3 correctly enforces the type check, but this makes it unable to open the project.

The problem here is really with C2 and I don't think we'll go back and fix it at this point. You can work around it by adjusting the use of the URLEncode expression to avoid passing it a number, save the project again, and then it should import to C3.
