### ISSUE TITLE
Trying to close the image editor too fast when importing a big file crashes C3

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#482]
## Problem description

After importing a big image as a sprite, closing the panel pretty quickly crashes the engine.

![pressingxtoofast](https://user-images.githubusercontent.com/7268697/27004704-937c5750-4e16-11e7-993e-0f937deda6ba.gif)

## Attach a .c3p

[ImportingBigFileBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1065945/ImportingBigFileBug.c3p.zip)

## Steps to reproduce

1. open the project attached
2. import this attached file as a sprite 
[garden v2.zip](https://github.com/Scirra/Construct-3-bugs/files/1065946/garden.v2.zip)

3. right after loading it in the image editor try to close the panel quickly

## Observed result

It crashes due to some rendering thing ? (error log below)

## Expected result

I'd expect it to not crash no matter how big the file is or how long the rendering takes.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: dialog not open @ Error: dialog not open at ǃi.ǃp.ǃK.ǃYTL.ǃzgf (https://editor.construct.net/r36/main.js:2:315118) at ǃi.ǃp.ǃK.ǃYTL.ǃzgA (https://editor.construct.net/r36/main.js:2:316285) at ǃi.ǃp.ǃK.ǃYTL.ǃYwW (https://editor.construct.net/r36/main.js:71:64480) at ǃhc.ǃYEW.ǃYwz.then.then.then (https://editor.construct.net/r36/main.js:71:64391) at 
Stack: Error: dialog not open at ǃi.ǃp.ǃK.ǃYTL.ǃzgf (https://editor.construct.net/r36/main.js:2:315118) at ǃi.ǃp.ǃK.ǃYTL.ǃzgA (https://editor.construct.net/r36/main.js:2:316285) at ǃi.ǃp.ǃK.ǃYTL.ǃYwW (https://editor.construct.net/r36/main.js:71:64480) at ǃhc.ǃYEW.ǃYwz.then.then.then (https://editor.construct.net/r36/main.js:71:64391) at 
Construct 3 version: r36
URL: https://editor.construct.net/
Date: Sat Jun 10 2017 19:50:42 GMT+0300 (GTB Daylight Time)
Uptime: 298.3 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by JeFawk** [comment]
This also happens with animations and I've noticed it with other panels as well but random and I couldn't reproduce it. My suggestion is to make a possible fix for all the X buttons in the engine.
Once I remembered it happened when I was in the expression panel, I think the drop down lagged a bit, I pressed Done. Nothing happened, Done again, crash.

**Comment by DiegoScirra** [comment]
Ah cool, it looks like you found a bug which I have been hunting for a while. Should be easy to fix now.

**Comment by DiegoScirra** [comment]
Fixed in r40.
