### ISSUE TITLE
Mesh Z height animation

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4820]
## Problem description

Animating a point on a mesh by setting its z height does not get refreshed as expected.
## Attach a .c3p

https://www.dropbox.com/s/xzjda6st1yy21ed/zrefresh.c3p?dl=1
## Steps to reproduce

1.Run the project
2.Click each Sprite
3.View results

## Observed result

The sprite that is moving via the Sine behavior shows the point being animated.
The sprite that is not moving does not show the point unless you move it.
## Expected result

The animation should show the point being raised by its z.
## More details

**Affected browsers/platforms:** 

Chrome, Windows 10
**First affected release:** 
248
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in next beta.

**Comment by pigmalien** [comment]
Thanks!
