### ISSUE TITLE
There's a huge mouse position delay.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4821]
## Problem description

Observe the file. There's a Laser sprite originating from the Hero sprite. This Laser has its angle and width determined by the angle and distance from the Hero to the Mouse. Moving the Hero around will show a huge difference from where the Mouse cursor is and to where the laser "thinks" it is.

I placed a random terrain just to aid the visualization, but it is irrelevant to the bug.

## Attach a .c3p

[Mouse_Delay.zip](https://github.com/Scirra/Construct-3-bugs/files/6466155/Mouse_Delay.zip)

## Steps to reproduce

1. Run the file.
2. Move the Hero around.
3. Observe the end of the Laser.

## Observed result

A huge discrepancy in mouse position between the mouse cursor and the runtime.

## Expected result

consistency in mouse position.

## More details

**Affected browsers/platforms:**  Chrome
**First affected release:**  240- (I can't really remember when it started, but I remember it happening for a long time now).

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 90.0.4430.212
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
C3 release: r248 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 410 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6627)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It seems to have a decently low latency for me.

This is out of our control anyway - there will always be a couple of frames latency for input to reach rendering. That's largely controlled by the browser.

**Comment by dupuqub** [comment]
Well... I never have any problems whatsoever with my browser and this is not a small gap. What can I do to fix it?

https://giphy.com/gifs/mouse-construct-latency-SFY3JIT8Q0KPNfIE6m

**Comment by AshleyScirra** [comment]
Oh, I thought you were just moving the mouse around. It might be that you position the laser before the player moves, rather than after, so it always looks one tick behind. These kinds of sequencing things are tricky, but you can usually work around them one way or another, such as by putting the laser on a zero parallax layer and positioning it in screen co-ordinates instead.

**Comment by dupuqub** [comment]
@AshleyScirra I don't mean to bother, but how can one translate the position of an object from a 100% parallax layer to a 0% parallax layer? I can't see how it would work.

**Comment by dupuqub** [comment]
@AshleyScirra I don't mean to bother, but I'm really stumped with this problem.

I was able to make it work with the center of the screen, like you said, in the example below:
![Laser](https://user-images.githubusercontent.com/34659544/118036352-d8b6bc80-b342-11eb-9397-699e207cc03b.PNG)

But I can't grasp how to translate the position if I'm not using the perfect center, like below:
![Boat](https://user-images.githubusercontent.com/34659544/118036735-511d7d80-b343-11eb-8fd0-200a7e21f4cf.PNG)

I already asked in the forums, but it doesn't seem like there's going to be any answer there. I deeply appreciate any insight, thanks in advance.
