### ISSUE TITLE
Edges in sprites gets introduced at random screen sizes

### ISSUE THREAD

**Issue by Vikingjonsson** [Scirra/Construct-3-bugs#4825]
At some random resolutions, edges are introduced in sprites using sampling bilinear or trilinear.
Example is a single image with transparent padding around it. 

With edge: ![image](https://user-images.githubusercontent.com/8763236/118234124-35c18800-b493-11eb-936c-1ba7aa649068.png)

Without edge: ![image](https://user-images.githubusercontent.com/8763236/118234140-3c4fff80-b493-11eb-9b64-3b6ae128a3ee.png)

Image in animation editor: ![image](https://user-images.githubusercontent.com/8763236/118254207-23534880-b4ab-11eb-8548-8fb6be9334b1.png)

**Comment by Vikingjonsson** [comment]
I tested this a bit more. The edges seem to appear on sprites that have been copy/pasted into the animation editor. Not sure if this is entirely true.

Also, the sprites that get the edges are made with Figma. Figma has a handy command to copy the graphic in the editor.

So I’ve copied the sprite in Figma and then pasting it to Construct 3.

I would still call it a bug. I like the way this pipeline works, so it would be very nice to have it working.

**Comment by AshleyScirra** [comment]
I would guess this is just the known issue of spritesheets and mipmaps as described in the blog (The surprising difficulty of resizing images on spritesheets)[https://www.construct.net/en/blogs/ashleys-blog-2/surprising-difficulty-1528]. Without more information it's impossible to investigate further, so closing. Please see the bug report guidelines.
