### ISSUE TITLE
Mesh does not have full deform possiblity

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4828]
## Problem description
I read some feature suggestion, which official reply was:

_Mesh distortion is now available for sprites as of r219. Therefore you can now draw a distorted textured quad by using mesh distortion to deform a sprite, and then paste that in to the canvas._

But mesh does not offer full deform capability! 
Is this expected or not, from official point of view. I did not find anything about this case.

![rrrrr](https://user-images.githubusercontent.com/28864889/118372419-27ba5700-b5ba-11eb-9b1b-d2ff807aae62.png)

## Attach a .c3p
[mmmm.zip](https://github.com/Scirra/Construct-3-bugs/files/6487836/mmmm.zip)

## Steps to reproduce

1.Open example
2.See mesh triangles limit deform movements
3.

## Observed result
Sprite with mesh has limited movement capability. Therefore does not offer full deform. From official statment, should it?

## Expected result
" draw a distorted textured quad "  

## More details
Currently user would have to apply whole new logic to mesh, which have possible size of ~20x20 or bigger. Then user would equally move whole mesh as cloth. 
It's still possible to draw textured quad, but one has to draw polygon on drawing canvas and then paste texture onto it.

What is currently possible:
![rrrrrrrr](https://user-images.githubusercontent.com/28864889/118444712-28580800-b6f6-11eb-8d67-d9370c10da17.jpg)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Each triangle of the mesh has to draw in some order, and so sometimes certain triangles will appear in front or behind of others depending on the draw order.

A textured quad has only 4 points, so that seems to be unrelated to this issue.
