### ISSUE TITLE
Array editor text misaligned 

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#4830]
I'm editing my Json Array and it confused me because it said the width was "30" when actually it was only 4 columns. 

Notice the header here:

![image](https://user-images.githubusercontent.com/5744908/118445461-d1702400-b731-11eb-82a2-9cba9aaf05ab.png)

Then I carefully checked and noticed that actually it's just that the labels seem to wrongly positioned.

This is where I got confused:

![image](https://user-images.githubusercontent.com/5744908/118445909-578c6a80-b732-11eb-8468-bce8c969ffb7.png)

As you can see, the "width" label is actually far closer to the 'height' input field

It reads like "Width = 30"

But it's actually "4      = Width"

So it's quite ambiguous at the moment!

Thanks!

**Comment by DiegoScirra** [comment]
Fixed in the next beta. The labels have been moved closer to the corresponding input element.
