### ISSUE TITLE
iOS export uses Cordova default icons when custom icons are added

### ISSUE THREAD

**Issue by Vikingjonsson** [Scirra/Construct-3-bugs#4831]
## Problem description
iOS export uses Cordova default icons even when icons are added to the icons folder.

## Steps to reproduce

1. Add icons to project
2. Set the purpose of icons
3. Export as Xcode project
4. Build/run on iOS device

## Observed result
Only working icon is loading/splash screen icon

## Expected result
Icon of the app in iOS to be one of the icons added to construct 3's icons folder.

**Comment by Vikingjonsson** [comment]
I should add that it is possible to work around this. Would be a nice quality of life improvement if Construct handled it with the icon properties.

**Comment by AshleyScirra** [comment]
I've verified this works in the past. No project has been provided so I can't test your specific icon combinations and settings, so closing. Please see the bug report guidelines.
