### ISSUE TITLE
When navigating outside C3 layout while shift is pressed, objects are forcibly kept in directional snapping mode upon return

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#4832]
## Problem description

If shift is pressed down while moving outside the browser running Construct 3, such as by clicking on another window or by press alt+tab to switch to another program, when returning to C3 and attempting to move objects in a scene, they will be forced to move only in 8 specific directions as if shift is still being held down even when it is not. This behavior stops when pressing shift once more, as if triggering and then once again stopping the directional snapping feature.

## Attach a .c3p

[Sprite Project.zip](https://github.com/Scirra/Construct-3-bugs/files/6494679/Sprite.Project.zip)

## Steps to reproduce

1. Open or create a new project containing a sprite or other object in a layout.
2. Hold shift while navigating outside your browser, either by clicking or using a shortcut like alt+tab on Windows.
3. Switch back to C3 and attempt to move an object in the layout, noting that it is forcibly moved along certain axes.
4. Press and release shift and notice the object's dragged movement returns to normal.

## Observed result

Objects being dragged around a layout are forced to move vertically, horizontally, or diagonally as if shift is being held down.

## Expected result

This would only happen when shift is actually being held down.

## More details

**Affected browsers/platforms:** 
Firefox, Chrome.

**First affected release:** 
No later than r241 stable.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 88.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
C3 release: r241 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 104 mb (5.1%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by ChromeWisp** [comment]
Update: This actually triggers not just when _leaving Construct_ while holding shift but also while clicking to a different tab within Construct (such as switching to an event sheet from a layout, after which when returning to the layout, draggable objects there will be forcibly snapped to certain directions).

**Comment by AshleyScirra** [comment]
Fixed for next beta.
