### ISSUE TITLE
Menu UI stays on screen after changing tabs 

### ISSUE THREAD

**Issue by TMsimonW** [Scirra/Construct-3-bugs#4833]
Editor menus will stay on the screen after very quickly changing tabs. The UIs that stay open have some weird opacity to them and still have accept the hover inputs but can not be clicked on and don't clear by clicking elsewhere 

Happens across entire editor no .c3p needed

1.Open either the right click menu in the editor or the top left hand menu
2. Quickly change tabs 
3. Menu will stay open but become useless

## Observed result

Menu stays open

## Expected result

menu should close and not stick on screen

## More details

Chrome os

First noticed in r248

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by TMsimonW** [comment]
I'm not sure if its on any other OS but I have attached a video showing you how to reproduce the issue. My mistake was you need to switch tabs twice, hopefully this helps

https://drive.google.com/file/d/1lc2FioZabB6Kl3CAyO0PWQFGIEhBGmTd/view?usp=sharing

**Comment by DiegoScirra** [comment]
Was able to reproduce it now, on Chrome OS only, and it is not 100% reproductible. It happens sometimes.

**Comment by DiegoScirra** [comment]
Will be fixed starting the next beta cycle.
