### ISSUE TITLE
Sometimes deleting a character before two line returns in the expression editor wipes the whole thing clean of text

### ISSUE THREAD

**Issue by eleanorjmorel** [Scirra/Construct-3-bugs#4840]
## Problem description
Sometimes deleting a character before two line returns in the expression editor wipes the whole thing clean of text
I'm not sure how to explain it, and this is not the first time is happens, but watch this:

https://streamable.com/980qh7

Trying to navigate the text with the arrow keys doesn'T work between empty line returns, the expression editor seem to think there are no characters there.

## Attach a .c3p
[delete whole expression.zip](https://github.com/Scirra/Construct-3-bugs/files/6513668/delete.whole.expression.zip)

## Steps to reproduce

 1. paste this in the expression editor for the only event in the minimum event sheet without the quotation marks
 "
 lerp(pY,

lerp((((entityFamily.oldX+entityFamily.oldY)*0.5-entityFamily.oldZ)*0.5)- characterOrigin,(((entityFamily.PX+entityFamily.PY)*0.5-entityFamily.PZ)*0.5)- characterOrigin, tickBank / TICKRATE)

 , 1-cameraLerp^dt)
 "
move the cursor around with the arrow keys, it gets stuck, try deleting the comma at the end of the first line

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I can't seem to reproduce this. The video isn't particularly helpful either as it's not clear when any key presses or mouse clicks are being made. Can you provide a project file with the full expression and a clear sequence of key presses/mouse clicks that reproduce the issue that I can follow?

**Comment by eleanorjmorel** [comment]
affects chrome and edge but not firefox

[fdahszhz.zip](https://github.com/Scirra/Construct-3-bugs/files/6534789/fdahszhz.zip)

**Comment by eleanorjmorel** [comment]
It was a bug in chrome, changing chrome version fixed the issue
