### ISSUE TITLE
Mobile Advert APK Crash

### ISSUE THREAD

**Issue by Emmaheroe** [Scirra/Construct-3-bugs#4841]
## Problem description

The mobile advert plugin crash APK applications on android on start, if it is not configured correctly.

## Attach a .c3p

https://drive.google.com/file/d/1DRDVmAJ3At9LsHxMj4qCNe1kFhreCaUl/view?usp=sharing

## Steps to reproduce

1. Export to Signed APK
2. Install on Android phone
3. Try to open the aplication

## Observed result

The application crash before opening. Android don't generate warning or crash report. Some times it says "The app stoped working" without trying to open.

## Expected result

The application starting

## More details

The issue seems to be in the mobile advert plugin if it is not configured correctly. This issue only affects android applications.
This crash also happens randomly on well-configured mobile advert applications, but rarely, my appreciation is that in these weird cases it may be related to mobile advert plugin starting too soon and failing to load and for instance making the same crash.

**Affected browsers/platforms:** 
Tested:
Remote Preview to the phone: Works fine
Hosted HTML on android chrome: Works fine
APK export: Crash
GooglePlay compilation with ABB: Crash

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The AdMob plugin is only expected to work if it is configured correctly. If it is not configured correctly and it crashes the app, make sure the configuration is correct. If other crashes happen with a correct configuration, please file an issue for those separately, or follow-up with AdMob as the issue may be on their side.

**Comment by Emmaheroe** [comment]
> The AdMob plugin is only expected to work if it is configured correctly. If it is not configured correctly and it crashes the app, make sure the configuration is correct. If other crashes happen with a correct configuration, please file an issue for those separately, or follow-up with AdMob as the issue may be on their side.
 
This issue doesn't happen if it is exported in any other method, it Is specific of android export, it doesn't crash even on android emulation, even if it is not configured correctly it shouldn't crash before opening the game.
