### ISSUE TITLE
Proportional resize is not working in r248 

### ISSUE THREAD

**Issue by Mak14** [Scirra/Construct-3-bugs#4844]
## Problem description
When i'm trying to scale object proportionaly with holding shift, it doesn't work and the sprite scales non proportional.
It has started in r248 build after the update from r245(r247 also works fine)

It's happens on both NWJS and Chrome versions.

## Steps to reproduce

1. Select sprite
2. Hold shift
3. Start resizing the sprite

## Observed result
Object is resizing non-proportional.

## Expected result
Proportional resize of the object

## More details

I'm working on Mac, so, i don't know how it works on Windows OS.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
