### ISSUE TITLE
The apk has not been installed

### ISSUE THREAD

**Issue by Leomcs1982** [Scirra/Construct-3-bugs#4845]
I'm trying to export a release version to Android, but the APK doesn't work. When trying to install on the mobile device, the installation displays the message "The app has not been installed".

I tried:
- Test on 2 smartphones
- Export on 3 different devices
- Export using 4 different browsers: Chrome, Firefox, Edge and Opera
- Export 4 different projects
- Export signed and unsigned release version

None of these attempts worked.

When I tried to export a debug version, the application was installed correctly and worked as expected, but it is not possible to publish a debug version on Google Play.

Construct 3 version: Beta R248

Screenshot:
! [Screenshot_20210522-190835] (https://user-images.githubusercontent.com/73327104/119242157-16c99280-bb32-11eb-8a91-522aebf75da9.png)

Sample APK:
https://app.box.com/s/tzsy6g1831f6sbt5zc9amrlc556ib9x8

Test project:
https://app.box.com/s/o604js8wx8xhkt6qrvrwcrijfd6ixohz

**Comment by AshleyScirra** [comment]
I believe this is how it's meant to work. Debug APKs are for testing, and can be loaded on your phone but not published. Release APKs are for publishing, and cannot be loaded on your phone.

**Comment by Leomcs1982** [comment]
Eu publiqueiI always managed to install the release versions on my smartphone, anyway, I published it on the Play Store and the downloaded file presented the same error

@AshleyScirra

**Comment by Leomcs1982** [comment]
@AshleyScirra 

I always managed to install the release versions on my smartphone, anyway, I published it on the Play Store and the downloaded file presented the same error
