### ISSUE TITLE
Array Editor scroll bug

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4846]
## Problem description
in the array editor when you increase size of the any cell and then use arrows to navigate to next cell selected cell doesn't shows in screen. 

## Attach a .c3p

[array editor.zip](https://github.com/Scirra/Construct-3-bugs/files/6530317/array.editor.zip)

## Steps to reproduce

1. open attached file 
2. open "New Array" file in array editor.
3. select first cell and use arrows keys to go to next cell until last cell. 

## Observed result
cell 33 is selected but out of screen.

## Expected result
selected cell should inside screen

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
