### ISSUE TITLE
Text right edge getting clipped when aligned to right

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4847]
## Problem description

Repost of issue #4829 added system info as requested.

Text right edge getting clipped when aligned to right

## Attach a .c3p

https://github.com/Scirra/Construct-3-bugs/files/6488954/textClip.zip

## Steps to reproduce

1. Open file
2. Observe text object both in edit-time and run-time
3. Try setting different font size, I get clips in all different size, but some are rendered OK.

## Observed result

The last character gets clipped

## Expected result

No clipping.

## More details

**Affected browsers/platforms:** Chrome/NWjs

**First affected release:** r248>

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 90.0.4430.212
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
C3 release: r248 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 370 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.6812)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by avishaymizrav** [comment]
@AshleyScirra I noticed when I zoom out the layout in the editor, at around 52% it renders right, but in run-time it is obviously still clipped.
Also when using c2 runtime it renders right too.

**Comment by AshleyScirra** [comment]
I'm using a very similar setup (Chrome 90 on Windows 10) and it looks fine for me, including in the editor at any zoom level.

I'm afraid there's nothing we can do if we can't reproduce the issue - it looks like it's working fine. My best guess is something like a graphics driver bug. Try updating your drivers.
