### ISSUE TITLE
Saving to cloud, empty dialogue window, no repro

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#485]
## Problem description

I've seen this bug around, so it's a duplicate. I could not find the original, also I can't reproduce it.
I saved to cloud and got this dialogue window. I guess the save failed.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
![image](https://user-images.githubusercontent.com/7268697/27007392-903df2e4-4e5a-11e7-8474-c95c5d3bcb1e.png)

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by JeFawk** [comment]
Yeah the save had 0 bytes.

**Comment by JeFawk** [comment]
For some reason the file eventually got saved after ~5 mins since dropbox sent me a notification.

**Comment by shortercode** [comment]
The current build will display a blank message when it receives a network error, as it doesn't understand how to convert them to text. It is already fixed, and will be in the next release.

As for the weird behaviour I'm not really sure what to say. Getting a blank file is quite possible if there was a network failure during a save. Attempting to save again will fix the blank file. However, the file saving by itself after 5 minutes seems kinda impossible ( at least in the client code ). Makes me wonder if there was some issue on the dropbox server where it told the client it failed but it was actually queued or something. 

Was this a really big project? Also was the save on dropbox complete ( does it load? )?

**Comment by JeFawk** [comment]
The c3p file was about 95MB. The save was okey as I could load it afterward.

**Comment by shortercode** [comment]
Given the size of the thing 5 minutes could very well be the processing/upload time. Unfortunately without an error ( which the blank dialog doesn't help ) or a stack trace trying to find the exact oddity will be hard. As it saved correctly I think we'll have to treat it as a one off and leave it.

If it does show up again maybe the fixed error message will give us a bit more info on what happened. I'm wondering if it could have been part of the archiving process, but for whatever reason it continued. All just guesses to be honest, and we're about to release a substantial refactor of the code in that area.
