### ISSUE TITLE
Dictionary won't load AJAX values when the first has a breakpoint

### ISSUE THREAD

**Issue by ArthurJVNB** [Scirra/Construct-3-bugs#4850]
## Problem description

I'm trying to load two dictionaries that are stored in the project. If I put a breakpoint on the first dictionary's AJAX load event, the correspondent dictionary won't load any value. The second dictionary will load just fine.

## Attach a .c3p

https://drive.google.com/file/d/1mWjv_7tIHNmWJIgJHHY2oCC-8aaZumff/view?usp=sharing

## Steps to reproduce

1. Create two dictionaries in Files folder
2. Populate these dictionaries for this test
2. Create two dictionaries in Project folder
3. Create a AJAX object in Project folder
4. Make an event that calls AJAX to load both dictionaries (put tags to catch them in the next step)
5. Make other two events that catches the AJAX load trigger
6. Respectively, create an action that loads the correspondent dictionary with the AJAX values (AJAX.LastData)
6. Put a breakpoint on the first AJAX "on loaded" trigger
7. Play on Debug mode

## Observed result

The first dictionary won't load any value after pressing "continue".

## Expected result

The first dictionary should load all data from the json file after pressing "continue".

## More details

This bug only happens if I put a breakpoint on the first whole AJAX event. If I put it on its condition or actions, it will work just fine. And if I put a breakpoint just on the second AJAX load event, both dictionaries will be loaded correctly.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 90.0.4430.212
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
C3 release: r241 (stable)
Language setting: pt-BR

Local storage
Storage quota (approx): 551 gb
Storage usage (approx): 40 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 960M Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5206)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The problem is that breaking in the debugger when the first request completes does not stop the second request from proceeding. So while it's stopped on a breakpoint, the second request still goes ahead and completes. The current design of the AJAX object provides only a single LastData value which is set when any request completes. So the completion of the second AJAX request overwrites LastData - and then clears it once it's finished running.

Unfortunately this is just a difficult consequence of the current design of the AJAX object. I think you will just have to rely on other debugging methods for AJAX requests, e.g. logging.
