### ISSUE TITLE
project can't open

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4854]
## Problem description

(Repost for others user)

I have a project, that has been working normally. Then I pasted part of the events I made yesterday, But the project can no longer be opened.  The original project, I forgot to back it up !!!!!
 
Now, my project can no longer be opened !!!!!
[fail_project.zip](https://github.com/Scirra/Construct-3-bugs/files/6548153/fail_project.zip)
 
I pasted from this project,  [Added version part.zip](https://github.com/Scirra/Construct-3-bugs/files/6548267/Added.version.part.zip)  
Before this project was added to the `eGameCommon` eventsheet , everything worked fine. However, after only adding the eventsheet and some objectTypes(`Text: fruitQuestionOption`) , it suddenly couldn't be opened! !

probably because I used the name of the original project in this project and added a behavior and container to it. The original project did not have it, causing a name conflict.

Can you help me restore it manually?  please! this item is very important!

## Attach a .c3p

[fail_project.zip](https://github.com/Scirra/Construct-3-bugs/files/6548153/fail_project.zip)

## Steps to reproduce

1. pasted 'eGameCommon' eventsheet from [Added version part.zip]  to [fail_project.zip]

## More details

**Affected browsers/platforms:** 

**First affected release:**  r241

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by XHXIAIEIN** [comment]
Sorry, this is a plugin

[css-0.0.0.3-stable.c3addon.zip](https://github.com/Scirra/Construct-3-bugs/files/6554707/css-0.0.0.3-stable.c3addon.zip)

[html-element-0.0.3.1-stable.c3addon.zip](https://github.com/Scirra/Construct-3-bugs/files/6554706/html-element-0.0.3.1-stable.c3addon.zip)

**Comment by AshleyScirra** [comment]
This doesn't appear to cover the Lite Tween behavior.

**Comment by XHXIAIEIN** [comment]
### 

> This doesn't appear to cover the Lite Tween behavior.

Sorry, 

[css-0.0.0.3-stable.c3addon.zip](https://github.com/Scirra/Construct-3-bugs/files/6554707/css-0.0.0.3-stable.c3addon.zip)

[html-element-0.0.3.1-stable.c3addon.zip](https://github.com/Scirra/Construct-3-bugs/files/6554706/html-element-0.0.3.1-stable.c3addon.zip)

[lunarraylitetween-c3runtime-1.0.1-stable.c3addon.zip](https://github.com/Scirra/Construct-3-bugs/files/6555459/lunarraylitetween-c3runtime-1.0.1-stable.c3addon.zip)

**Comment by AshleyScirra** [comment]
I was able to recover the project: 
[project-recovered.zip](https://github.com/Scirra/Construct-3-bugs/files/6561088/project-recovered.zip)

It had the following problems:

- layout "ObjectRepository" data file missing - removed its references in the project
- functions "initQuestionData", "loadQuestionData" and "initScreenObject" were called but did not exist - other functions named "initQuestionData11", "loadQuestionData11" and "initScreenObject11" existed, so they were renamed

There are no steps to reproduce the problem, so nothing has been done to prevent this happening again. Please do file an issue if you can identify steps to reproduce the problem in the first place - project corruption bugs are a high priority and we will always try to fix them ASAP, but we need to know how they happen to fix them.

Also remember it is absolutely critical to keep regular backups. You are lucky the project was recoverable. In some cases it is permanently lost. You need to keep regular backups for all digital work, regardless of the software.

**Comment by XHXIAIEIN** [comment]
Thank you very much!! Handsome !!
