### ISSUE TITLE
Platform Behaviour

### ISSUE THREAD

**Issue by KICK4H4** [Scirra/Construct-3-bugs#4855]
## Problem description

"set platform default controls" to false causes project to glitch out and debug console shows "Uncaught (in promise) TypeError: this._OnWindowBlur is not a function" error.

## Steps to reproduce

1. Create new project
2. Creat new sprite on layout
3. Apply platform behaviour
4. Add event "set platform default controls" to false
5. Run project

## More details

**Affected browsers/platforms:** 
Version 91.0.4472.77 (Official Build) beta (64-bit)

**First affected release:** 
R249 Beta

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Repro project as none was provided: [issue4855.zip](https://github.com/Scirra/Construct-3-bugs/files/6560999/issue4855.zip)
(Please provide a project as per the bug report guidelines where possible)

**Comment by AshleyScirra** [comment]
Fixed for next release.
