### ISSUE TITLE
Whitelist plugins update (essential)

### ISSUE THREAD

**Issue by EMI-INDO** [Scirra/Construct-3-bugs#4856]
hi please whitelist plugins update
new features ( App Open Ad )

`admob-plus-cordova@1.13.0`
`cordova-plugin-consent@2.1.10`

Coming Soon ( Native Ad )
https://github.com/admob-plus/admob-plus/discussions/314

**Comment by AshleyScirra** [comment]
This looks like a routine maintenance update. Please state the reason why you are asking for an essential update. If no reason is provided, we will treat it as a routine maintenance update, because that's what it looks like.

**Comment by EMI-INDO** [comment]
If using the offset banner the app keeps stopping.

As I explain here
https://github.com/admob-plus/admob-plus/issues/319

**Comment by EMI-INDO** [comment]
@AshleyScirra 

### Sorry

I canceled this, will reopen it after the Native Ad is released
