### ISSUE TITLE
Object selection by double index list is bugged

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4857]
## Problem description
When object list is picked by Object(a,b), it's not usable. I doubt someone is using it like this.
Object(a) picks from all objects and cannot be changed because 'someone' might be using it.
Now Object(a,b) does not work at all. From this, i doubt 'someone' is using it. Because it only and ever can refer 1 object.

So in conclusion object(a,b) method needs check, confirm if bug and possible change.

## Attach a .c3p
[Issue_ab.zip](https://github.com/Scirra/Construct-3-bugs/files/6564556/Issue_ab.zip)

## Steps to reproduce

1.Open project
2.Preview
3.

## Observed result
Object(a,b) is able able to refer only 1 object

## Expected result
Object(a,b) to refer differently then Object(a). Possible from picked list.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I don't believe `Object(a, b)` syntax has ever been supported. I don't recall ever writing code to support it and it's [not documented](https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/events/expressions). I would guess the parser only accepts that syntax by accident.

**Comment by SnipG** [comment]
It clearly is able to refer picked list with it, but is bugged. So it has to be there. But it only refer first instance only.
