### ISSUE TITLE
3D object edges are not sampled

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4858]
## Problem description
![oooooo](https://user-images.githubusercontent.com/28864889/120068905-bd121c80-c08b-11eb-8b3e-def535d663c0.jpg)

To sample edges, user has to crop all sprites. Which brings in empty line.

Is bug, limitation or feature?

## Attach a .c3p
[Issue_3D_sample.zip](https://github.com/Scirra/Construct-3-bugs/files/6564596/Issue_3D_sample.zip)

## Steps to reproduce

1.Preview
2.Remove crop from animation, look edged
3.Add crop from animation, look edges

## Observed result
Edges are not sampled

## Expected result
Possible to sample edges

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is by design. You are basically asking for antialiased rendering, but note that can come with a significant performance overhead. Please post suggestions to the suggestions platform.

**Comment by SnipG** [comment]
I though by default 3D plugin is built for sprites and have vertices with 1 pixel offset by default, as sprites are usually used with padding to get edge sampling. 
![rrrrrr](https://user-images.githubusercontent.com/28864889/120078286-720dfe80-c0b7-11eb-9be0-b90d78410fed.jpg)

Anyway, if this is not the case, then it indeed falls into feature suggestion category.

**Comment by AshleyScirra** [comment]
No, 3D shape does not do that. Nor do Sprites. The 1px padding is applied to the texture, not the size of the actual quad that is drawn. Besides, the 1px padding trick does not really work in 3D, as the actual necessary distance depends on the perspective.
