### ISSUE TITLE
 Tilemap UI Scroll

### ISSUE THREAD

**Issue by hinklefoxmail** [Scirra/Construct-3-bugs#486]
## Problem description

Tilemap UI scroll extremely non-intuitive. No scroll bars appear and clicking and dragging in where the scroll bar should appear is required. Mouse-wheel and trackpad swipes do not cause the window to scroll. This is especially confusing when using a trackpad.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
[Google Drive Link here](https://drive.google.com/file/d/0B3QaE26f2r25QUVORUdVd3ZweXc/view?usp=sharing)

## Steps to reproduce

1. Create new tilemap using a large tilemap spritesheet
2. Save and use the tilemap bar to place tiles
3. Attempt to scroll tilemap bar using standard UI methods for scrolling windows

## Observed result

Difficulty scrolling to see new more tiles than can appear (tried arrow keys, mouse wheel, moving mouse to edges, clicking and dragging in the main window, and two-finger swiping with my trackpad)

## Expected result

Scroll Tilemap Bar follows expected scrolling behavior for OS or at least has more obvious clues as how to scroll such as the up and down buttons on old scroll bars.

## Affected browsers

* Chrome: yes

## System details
OS System Version:	OS X 10.11.6
Chrome Version:  58.0.3029.110 (64-bit)

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This has been fixed already, and will be available in the next release, r37.

Scroll bars still won't show up in OSX, because that is how the OS works, that shouldn't be a problem as the familiar 2-finger swiping can be used to scroll the image.
