### ISSUE TITLE
LocalStorage and native save/load migration from C2 runtime to C3 runtime 

### ISSUE THREAD

**Issue by RobinBloood** [Scirra/Construct-3-bugs#4860]
## Problem description

Hello Scirra team!
I'm on my way to migrate my old projects from C2 runtime to C3 runtime. They use LocalStorage and native save/load. When I'm trying to switch runtime all previous data that I have in LocalStorage and native save/load disappears. 
## Attach a .c3p

[test localstogage.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6573281/test.localstogage.c3p.zip)

## Steps to reproduce

1. run project with C2 runtime
2. click randomize button
3. click save to localstorage button
4.  click randomize button
5. click save
6. click load from localstorage button, to make sure that loading from local storage is working
7. click load button, to make sure that native loading is working
8. close the window and switch project runtime to C3
9. run project
10. click load from localstorage button, to make sure that loading from local storage isn't working
11. click load button, to make sure that native loading isn't working
12. close the window and switch project runtime to C2
13. run project
14. click load from localstorage button, to make sure that loading from local storage is working
15. click load button, to make sure that native loading is working
## Observed result

C2 and C3 runtime have different data location
## Expected result

I want to migrate my projects but I cant. 
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid this is by design: we changed the way the storage engine works in the C3 runtime, and it now uses a separate storage area. Since we originally implemented the C3 runtime back in 2018 and something like 99% of existing projects are already ported, I think it's far too late to implement any kind of migration, and it seems everyone else managed OK without it anyway.

**Comment by RobinBloood** [comment]
> I'm afraid this is by design: we changed the way the storage engine works in the C3 runtime, and it now uses a separate storage area. Since we originally implemented the C3 runtime back in 2018 and something like 99% of existing projects are already ported, I think it's far too late to implement any kind of migration, and it seems everyone else managed OK without it anyway.

It looks not really friendly... Is there any decisions how to transfer this data? Maybe some 3rd party plugins? After c2 will deprecated could I still use c2 runtime in previous versions?

**Comment by AshleyScirra** [comment]
Once support for the C2 runtime is dropped, you can keep using the last version of C3 that supports it. However we won't be providing any further support for the C2 runtime beyond July, so any further bugs or issues will not be supported.

**Comment by RobinBloood** [comment]
> Once support for the C2 runtime is dropped, you can keep using the last version of C3 that supports it. However we won't be providing any further support for the C2 runtime beyond July, so any further bugs or issues will not be supported.

Got it. What about my first question, could you advise some save method that work in C2 and in C3, so I could transfer user data?
