### ISSUE TITLE
Browser 'Request fullscreen' doesn't work properly on mobile

### ISSUE THREAD

**Issue by jorbart** [Scirra/Construct-3-bugs#4862]
## Problem description

Browser 'Request fullscreen' feature works fine on desktop, but on mobile devices it gives different results on different platforms and browsers.

## Attach a .c3p
[fullscreenTest.zip](https://github.com/Scirra/Construct-3-bugs/files/6576144/fullscreenTest.zip)

## Steps to reproduce

1. Run preview of the project (it happens also when you run exported project) on mobile Chrome browser on Android 9 or Android 10
2. Set the device in horizontal orientation
3. Tap the 'Fullscreen ON' button

## Observed result

There's a black bar at the bottom which height is probably the same as the address bar.

## Expected result

There should be no black bar at the bottom.

## More details

It works fine on Opera browser on Android 9 device.

It seems to work fine on Safari browser on Apple devices with iOS 14.1. I'm testing it by using appetize online emulator and I can't check it on other browsers.

**Affected browsers/platforms:** 
Chrome on Android 9 and Android 10.

**First affected release:** 
r241

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.77
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.9375
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 57 gb
Storage usage (approx): 38 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0, D3D11-20.19.15.4352)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This looks like a Chrome bug. I'll file an issue with Google soon.

**Comment by AshleyScirra** [comment]
I filed this issue with Google here: https://bugs.chromium.org/p/chromium/issues/detail?id=1215158
Closing as we will follow up there.
