### ISSUE TITLE
Request for Adding Action on SpriteFont (if Possible)

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#487]
this is a request mail for adding action on Spritefont about changing Character width & Height from EventSheet (not talking about scale)
![request](https://user-images.githubusercontent.com/17684135/27029974-25cc4026-4f88-11e7-8e58-4e3f604034bb.jpg)

I know Spritefont is for custom fonts style but we can manipulate this feature on many other ways like i have done on my tutorial

[How to make Photo Slider Puzzle Game in 2 events](https://www.youtube.com/watch?v=sTzE7rdkFLk)

If you see this video you will found that i have used SpriteFont for Photo Slices 
and now I want to extend this, I want to give option like 
Click on 6x6 button     Grid will become 6x6
Click on 8x8 button     Grid will become 8x8
Click on 10x10 button  Grid will become 10x10
when Grid will 6x6 then i need to change Character height & width to cover the width & height of photo for example 
on Grid 6x6 
Six slices will cover image width and same with height
and in case of 8x8 
Eight slices will cover image width and same with height

now you can understand what i am talking about 
people can do lots of experiments with this new actions

**Comment by AshleyScirra** [comment]
Please use this platform for feature requests: https://construct3.ideas.aha.io/
This GitHub tracker is only for bug reports, so closing.
