### ISSUE TITLE
Audio "Fade volume" no longer resumes after a pause.

### ISSUE THREAD

**Issue by whistlegraph** [Scirra/Construct-3-bugs#4870]
## Problem description

In my game I have areas where I start a sound and set it to fade. When the game pauses and resumes I pause and resume that sound via its tag. Construct used to keep the fade going on resume but now it just sets the clip to the original volume before the fade was applied.

Was this change intentional? 

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise we don't have enough information to help you.
