### ISSUE TITLE
DrawingCanvas clears itself. 

### ISSUE THREAD

**Issue by RufusRufson** [Scirra/Construct-3-bugs#4871]
## Problem description

DrawingCanvas clears itself randomly without scalling window resolution size and DrawingCanvas Layer. Real DrawingCanvas.PixelScale can be only measured in Debug Layout.

## Attach a .c3p

[DrawingCanvas_issue.zip](https://github.com/Scirra/Construct-3-bugs/files/6594558/DrawingCanvas_issue.zip)
## Steps to reproduce

1. Run project in Debug layout
2. Wait a couple of second for DrawingCanvas to clear itself
3. Observe the global variable "PixelScale" 

## Observed result
 

DrawingCanvas clears itself randomly. OnResoultionChanged event updates PixelScale value from DrawingCanvas PixelScale that varies between: 0.9999999999999998 and 1.0000000000000002 which is strange because windows screen doesn't change resolution(full screen mode is off) and layer scale is always 100%
You can only see real Pixel Scale value in Debug Layout (for example action with expression set spriteFont text to DrawingCanvas.PixelScale always returns int 1 which is wrong in this case)
## Expected result

DrawingCanvas should not clear itself in this conditions. Pixel Scale should be 1 in this situation.

## More details

This problem occurs only when Unbounded scrolling is "on", Scroll To action is used with values from Sine and DrawingCanvas changes its position(in this case is sine behaviour). 
When Unbounded scrolling is "off" all is ok. DrawingCanvas keeps PixelScale at 1 and doesn't clear itself.

**Affected browsers/platforms:** 
Chrome/Firefox/Edge

**First affected release:** 
broke in r241 up to r250
not tested below r241
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.77
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
C3 release: r250 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 1.7 gb
Storage usage (approx): 36 mb (2.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6079)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The Drawing Canvas renders in screen co-ordinates to make sure the rendered canvas appears with good quality. Moving the object around to fractional co-ordinates - which is what the sine behavior does - can cause floating point rounding errors to affect the size of the screen surface, which then causes 'On resolution changed' to trigger. It's currently by design that this happens and the rounding errors are just an awkward source of changing the canvas surface size. I'm not sure there's anything we can do about this.
