### ISSUE TITLE
Included "Camera input" template crashes on Chrome in Windows 10.

### ISSUE THREAD

**Issue by whistlegraph** [Scirra/Construct-3-bugs#4872]
Hello, here is a screenshot of this Camera object crash. I only experienced it on Windows in Chrome.

![Camera Capture](https://user-images.githubusercontent.com/3620017/120757769-d7059200-c4c5-11eb-9b94-1d739e5c92f1.PNG)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It works for me.

Tab crashes are browser bugs anyway and we can't fix them, since they need to be fixed by the browser maker. I'd advise filing this at crbug.com if you want it further investigated.

**Comment by whistlegraph** [comment]
I actually just updated Chrome and it worked right away so it must have been something that was already caught by them!
