### ISSUE TITLE
Sound doesn't play on Iphone Safari

### ISSUE THREAD

**Issue by CROmartin** [Scirra/Construct-3-bugs#4874]
## Problem description

Sound isn't playing on Iphone Safari and Iphone Chrome. It works fine on other devices, although I am not in position to test Safari on Mac

## Attach a .c3p

Pleas download from: https://www.mediafire.com/file/1buz1usxgt89rbx/Leprechaun_in_Poland.c3p/file 

## Steps to reproduce

1. Open game on Iphone Safari 
2. Tap on game 
3. There should be sound playing, but isn't
4. Tap on start 
5. There should be sound when you pick up something, but isn't

## Observed result

No sound 

## Expected result

Sound playing

## More details
 I have also tried putting in fallback mp3 and m4p files for "music' sound hoping that it will work for Safari, but it didn't

 This is happening on Iphone device both on Chrome and Safari, but Chrome works fine on PC and Android

**Affected browsers/platforms:**  Iphone Safari, Iphone Chrome, maybe Mac safari 

 Identifying the first version the issue started happening can help resolve the issue more quickly. 

**First affected release:**  It never worked as much as I know, I am working in newest version and probably I have started 1-2 versions lower 

## System details

 I am not in position to debug sadly as I miss equipment 
 Also I am not in position, this is users feedback, although majority of users have everything up to date and multiple users have same problem

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
The project uses third party addons:

- Plugin Firebase SDK (Sparsha_FirebaseSDK) by Sparsha
- Plugin Firebase RD Basic (Sparsha_FirebaseRealtimeDatabase) by Sparsha
- Behavior Lite Tween (lunarray_LiteTween) by lunarray

Please provide a minimal project not using any third-party addons as per the bug report guidelines.

**Comment by CROmartin** [comment]
Sorry for that. Here it is: https://www.mediafire.com/file/m3q3waivbs7rgyf/SoundTesting.c3p/file. Simple project where should sound named "music" start playing when you press Play music button. I have also put in fallback files m4a and mp3. Problem is same, it doesn't play on Safari.

**Comment by AshleyScirra** [comment]
WebM Opus is the only sound file we guarantee will play everywhere. I would advise to just use WebM Opus files only. If you still have trouble playing sound in a project that only uses WebM Opus files in Safari, please file a new issue following all the guidelines, as per the FAQ.
