### ISSUE TITLE
Whitelist plugins update (essential)

### ISSUE THREAD

**Issue by EMI-INDO** [Scirra/Construct-3-bugs#4875]
**broken banner ad**
**need info** https://github.com/Scirra/Construct-3-bugs/issues/4856
If using the offset banner the app keeps stopping.

`admob-plus-cordova@1.15.0`

**Thank you friend**

**Comment by AshleyScirra** [comment]
`admob-plus-cordova-native` is a request to whitelist an entirely new Cordova plugin, rather than update an existing one. What is the reason this is requested as an essential update?

**Comment by EMI-INDO** [comment]
🙏🙏🙏

Sorry i moved it https://github.com/Scirra/Construct-3-bugs/issues/4808

**Comment by AshleyScirra** [comment]
`admob-plus-cordova@1.15.0` now allowed on build server.
