### ISSUE TITLE
Sound doesn't play on Iphone Safari 

### ISSUE THREAD

**Issue by CROmartin** [Scirra/Construct-3-bugs#4876]
## Problem description

Sound isn't playing on Iphone Safari and Iphone Chrome. It works fine on other devices, although I am not in position to test Safari on Mac

## Attach a .c3p

Pleas download from: https://www.mediafire.com/file/m3q3waivbs7rgyf/SoundTesting.c3p/file

## Steps to reproduce

1. Open game on Iphone Safari
2. Tap on Play music
3. There should be sound playing, but there isn't

## Observed result

No sound

## Expected result

Sound playing

## More details

I have also tried putting in fallback mp3 and m4p files for "music' sound hoping that it will work for Safari, but it didn't

This is happening on Iphone device both on Chrome and Safari, but Chrome works fine on PC and Android

Affected browsers/platforms: Iphone Safari, Iphone Chrome, maybe Mac safari

Identifying the first version the issue started happening can help resolve the issue more quickly.

First affected release: It never worked as much as I know, I am working in newest version and probably I have started 1-2 versions lower

## System details

I am not in position to debug sadly as I miss equipment. This is users feedback, although majority of users have everything up to date and multiple users have same problem

**Comment by AshleyScirra** [comment]
You only need a WebM Opus file. That plays on all platforms, so the other files are redundant. Does this reproduce for you in a project only using WebM Opus?

**Comment by CROmartin** [comment]
Yes result was same, but I have found out what was a problem. If silent mode is turned on then it blocks browser sound, if silent is off then everything works fine. Thank you.
