### ISSUE TITLE
Whitelist plugins (Routine)

### ISSUE THREAD

**Issue by tuzke** [Scirra/Construct-3-bugs#4879]
Hi, please add the addons: 

> cordova-plugin-idfa@2.0.0

**Comment by tuzke** [comment]
@AshleyScirra Did you add it to the build service? I just want to know to continue the project

**Comment by tuzke** [comment]
Hi , Did you add it to the build service?

**Comment by AshleyScirra** [comment]
Build service updated to allow this plugin.
