### ISSUE TITLE
Animations editor swipe bars can overlap

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#488]
## Problem description

On mobile, the side-swipe bars in the animations editor can overlap.

## Steps to reproduce

1. Open animations editor on mobile
2. Swipe bar in from left
3. Without closing left bar, swipe bar in from right

## Observed result

Bars overlap

## Expected result

The left bar should collapse as the right bar is swiped in. See how the equivalent happens with the main editor swipe bars for comparison.

**Comment by DiegoScirra** [comment]
Fixed in r38.

Currently the logic will only work in devices with small screens, like phones.
