### ISSUE TITLE
 landscape mode is not working on Chrome iOS

### ISSUE THREAD

**Issue by sonxoans2** [Scirra/Construct-3-bugs#4880]
### Problem description
Currently we are using the paid version of Construct 3 to build the games, however, our game is having some issues on Android and iOS browsers, we predict this error belongs to Construct 3’s fault.

Error (chrome browser on iOS): we had problems with horizontal rotation, sometimes the game went full screen, sometimes it didn't. (details attached)

Please help us check the above errors, thank you very much for your support

### Attack a .c3p
[BrickOut.zip](https://github.com/Scirra/Construct-3-bugs/files/6633241/BrickOut.zip)

### Steps to reproduce
1. Build game html5
2. Deploy and Run on webserver
3. Open game on Chrome browse -  iOS: portrait orientation
4. Rotate game to landscape, issue will happen
### Expected result
Full screen game

**Comment by manhhoangxuan** [comment]
Hi 
I also facing with this problem too

Please any help from Contruct 3 Team

Thanks

**Comment by AshleyScirra** [comment]
This looks like a bug in iOS we work around in other cases, and applying the same workaround to Chrome for iOS appears to fix it, so it should be fixed in the next beta.
