### ISSUE TITLE
Tilemap rectangle draw bug

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4887]
## Problem description

I believe this is somewhat related to an old bug I reported, issue #4475
This strange bug only happens under certain conditions, the weirdest of them is that the tilemap object width needs to be at least 2078px, the other one is that the layout zoom level can also affect this.
Basically the bug is that the last drawn cell is being replaced when changing the tile selection and pressing the rectangle tool (without actually drawing on the tilemap).
https://www.youtube.com/watch?v=dk3ssh9lCIQ

## Attach a .c3p

[tilemapBug13-6-21.zip](https://github.com/Scirra/Construct-3-bugs/files/6643529/tilemapBug13-6-21.zip)

## Steps to reproduce

1. Zoom in layout to about 60%
2. Select a tile to draw
2. Click on the rectangle tool (in some cases this will draw in a random tile cell)
3. Select a different tile.
4. Click the rectangle tool again (this can also happen when you switch to another tool, than back to the rectangle tool).

## Observed result

Last tile is being replace with new selection (sometimes this can be way off screen and break up level design).

## Expected result

Don't replace the last tile.

## More details

**Affected browsers/platforms:** Chrome/NWjs

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.54.0
Browser engine: Chromium
Context: nwjs
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.54.0 (like Chrome/91.0.4472.77)
C3 release: r251 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 26 gb
Storage usage (approx): 328 mb (1.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6677)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed on the next beta. This is effectively the same bug as #4475. The fix for that was not catching all the possible cases though.
