### ISSUE TITLE
Not in line of sight, doesn't work when there're multiple instances

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#4889]
## Problem description

If you invert the "has line of sight to", it only seems to work when there is a single instance of an object, but when there are multiple instances then it seems to stop working at all.

(I can't actually understand what it's doing, it seems to behave differently depending on the amount of instances.)

## specific example

![image](https://user-images.githubusercontent.com/5744908/121838012-319abb80-cd1a-11eb-9b57-c5985b3cd8a0.png)

In this example, the player should change color when there are no objects in line of sight.

But because there are 3 instances in the layout, the condition gets confused and no longer works.

## Attach a .c3p

[LOS_red.zip](https://github.com/Scirra/Construct-3-bugs/files/6645554/LOS_red.zip)

## Steps to reproduce

1. Preview
2. Swing the mouse around the window 
3. observe the line of sight
4. notice when the player changes color
5. (you could also delete instances so there is just one red sprite, and notice the difference)

## Observed result

Player is not changing color when they should

## Expected result

I found a temporary work around:

![image](https://user-images.githubusercontent.com/5744908/121838364-01075180-cd1b-11eb-8680-7e2b4ec438b5.png)

It makes sense that it should behave like this code. 

## More details

**Affected browsers/platforms:** 

windows desktop build

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by SnipG** [comment]
I have had problems with LOS picking to.

Seems inverted LOS check all instances at once. While LOS checks each one separately.

This would be breaking change, if it has always been working like this.

**Comment by AshleyScirra** [comment]
It's actually working correctly. The inverted LOS condition is true if the player does not have LOS to *any* instance. Therefore the player turns red if there is any sprite outside of its LOS, and only reverts to its normal color if the player has LOS to all instances.

**Comment by SnipG** [comment]
I do first tought just like that. But it's wrong, LOS and !LOS work differently. Code wise it's correct, but behavior wise is different. It should be marked so in documentaion.

**Comment by AshleyScirra** [comment]
It is consistent with the way picking works: normally it picks all instances in LOS, and runs the actions if any instances meet the condition. Inverted, it picks all instances *not* in LOS, and runs the actions if any instances meet the condition. It's the same both ways round, but only the test applied per-instance is inverted, not whether or not the event as a whole runs - that is still, as usual for all events, based on whether any instances met the conditions.

**Comment by SnipG** [comment]
Yes, the text "Player has LineOfSight to sprite" should be different and should not confuse users.
Something like "Pick sprites Player has LineOfSight to" -> inverted it picks ones that he does not have LOS to.
