### ISSUE TITLE
webfonts (WOFF) does not render on samsung internet browser

### ISSUE THREAD

**Issue by rumesh99** [Scirra/Construct-3-bugs#4890]
## Problem description

Web fonts used in the game does not render on samsung internet browser. 

This issue only appear on Samsung Internet browser. Others seem to be fine. I also checked if it's a browser bug and it doesn't seem to be a browser bug either because when I tried the same on a simple html it does work.

Here are the links I've set up to test:
[The construct created page](https://games.taloslogy.net/testfonts/)
[The simple HTML example](https://games.taloslogy.net/testfonts/check.html)

[C3P file](https://games.taloslogy.net/testfonts/fonttest.c3p)

## Steps to reproduce

Insert a webfont file (WOFF) with or without it's TTF version. Check on samsung's internet browser

## Observed result

If you check the 2 links I've provided, you will notice that the construct page does not render the font where as the normal HTML does.

## Expected result
Consistent rendition of the web font across all browsers

## More details

**Affected browsers/platforms:** 

Only observer on Samsung's Internet browser.

Not exactly sure on the version, but I noticed this since May. Even the games I have built and published earlier has the same issue now. 

## System details

Checked on  multiple Samsung devices with Samsung Internet version 14.0.3.5

**Comment by AshleyScirra** [comment]
I can reproduce, but this looks like a bug in Samsung Internet. If Construct's code was incorrect it wouldn't work anywhere; if it works everywhere except in one browser, it's a browser bug. Please report it to them here: https://forum.developer.samsung.com/c/samsung-internet/25
