### ISSUE TITLE
Memory leak after dividing by the width of a destroyed object

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#4892]
## Problem description

I calculate the require loop count using variable length=distance/wire.width. But when the wire is destroyed at the start of layout, the code run and probably divides by 0. Then the memory used by Firefox increases rapidly (from 200K KB to Millions of KB!).

## Attach a .c3p

[Mem Leak.zip](https://github.com/Scirra/Construct-3-bugs/files/6654306/Mem.Leak.zip)

## Steps to reproduce

1. Run the project (in Firefox). It should show a simple Rope behavior.
2. Make a copy of the red circle (tSocket sprite) using Ctrl+Shift, and drag it to around x=900,y=220
3. Ctrl+D to enable the block number 3 in the code (the one under the length variable inside the CreateWire function).
4. Preview the layout.
(I can reproduce this for the 4th time now)

## Observed result

Black screen.
In the task manager, FF memory used increases rapidly to millions of KB.

## Expected result

at least an exception, without memory leak.

## More details

**Affected browsers/platforms:** FireFox 89.0 64-bit

## System details

Win7 64-bit, 8GB RAM

**Comment by AshleyScirra** [comment]
It is your events that leak memory, not Construct. You end up setting 'length' to Infinity, which means it starts an infinite loop that creates objects, and each object will use a bit of memory. This is just a mistake in your events.

**Comment by Alaadel** [comment]
Thank you. I am aware of that.
But to track down the bug, I had to restart the project multiple times (and use the Task Manager to shut FF down every time I run the game and a leak happens) and iterate on my code until I could find it. Some work was also lost the first time this happened.

I understand it is not an issue in Construct, but if it is possible to add some sort of safeguard or throw an exception in these cases, it would make tracking and fixing them easier for the developer.

Thank you.
