### ISSUE TITLE
Android studio Failed to sync project 

### ISSUE THREAD

**Issue by Moshe-Paz** [Scirra/Construct-3-bugs#4893]
## Problem description

 Android Studio failed to build Construct 3 mobile android export game.

## Attach a .c3p

[Debug.zip](https://github.com/Scirra/Construct-3-bugs/files/6657585/Debug.zip)

## Steps to reproduce

1. open the project with Construct 3 version 251.2
2. Export as Android and for android build choose Android studio project 
3. Open with Android studio (I'm using 4.2.1)

## Observed result

 Andriod studio starting to sync project with Gradle files, and giving a result of: 
1: Task failed with an exception.
-----------
* Where:
Script 'D:\Construct3\New project.android.project\CordovaLib\cordova.gradle' line: 112

* What went wrong:
A problem occurred evaluating project ':app'.
> Unable to determine Android SDK directory.

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ': app'.
> compileSdkVersion is not specified. Please add it to build.Gradle

BUILD FAILED in 8s

## Expected result

 Andriod studio Should successfully complete the  sync project with Gradle files task

## More details

**Affected browsers/platforms:**  Firefox , Android

 r251

**First affected release:**  worked in r241 broke in r251

## System details

<details><summary>View details</summary>

PASTE HERE 
Platform information

Browser: Firefox
Browser version: 89.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
C3 release: r251.2 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 Gb
Storage usage (approx): 531 kb (0%)
Persistent storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) Iris(R) Plus Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by tarunsraina** [comment]
Either one of them should help.
1)Go to the Build drop down menu in the menu bar. you can see the Rebuild Project under the Clean Project. Rebuild project cleans the project actually. If you cant find Rebuild Project you can simply use Clean Project.
2)try to Invalidate Caches/Restart (file menu)
Hope these help to solve your problem.

**Comment by tarunsraina** [comment]
Sorry to hear that,i had the same issue and these worked for me.

**Comment by fredriksthlm** [comment]
Cordova is updated from 9.0 to 9.1 in r245.

Try to update your gradle or android version in AS. and verify your settings. 
-Open settings->build..->Gradle and set "specified location"
and save the settings in AS

This is not related to Construct, it is a Cordova thing, and it is not a bug.

**Comment by Moshe-Paz** [comment]
> 
> 
> Cordova is updated from 9.0 to 9.1 in r245.
> 
> Try to update your gradle or android version in AS. and verify your settings.
> -Open settings->build..->Gradle and set "specified location"
> and save the settings in AS
> 
> This is not related to Construct, it is a Cordova thing, and it is not a bug.

I made the steps you say, Using now Gradle version 7.1 + JDK 11, now when I try to "sync project with Gradle files" I get:
A problem occurred evaluating project ':CordovaLib'.
> Failed to apply plugin 'com.github.dcendents.android-maven'.
   > Could not create plugin of type 'AndroidMavenPlugin'.
      > Could not generate a decorated class for type AndroidMavenPlugin.
         > org/gradle/api/publication/maven/internal/MavenPomMetaInfoProvider

**Comment by fredriksthlm** [comment]
I have both Android29&30 installed. and the Gradle is set to "'gradle-wrapper.properties' file"
For me the exports work fine.
But regardless, these build settings (or errors) does not come from Construct.

**Comment by Moshe-Paz** [comment]
I changed back the use Gradle from to "'gradle-wrapper.properties' file" , and it's working now.
So to fix my problem I needed to Use Gradle version 7.1+JDK 11 and leave the use Gradle from "'gradle-wrapper.properties' file".

Fredriksthlm and Tarunsraina Thank you for your help and time wish you well.
