### ISSUE TITLE
3D Shapes Problems

### ISSUE THREAD

**Issue by l-t-m-f** [Scirra/Construct-3-bugs#4895]
I noticed a few bugs with 3D Shapes that should be fixed quickly :

- Impossible to use LineOfSight to a 3D shape, I feel like it should work like a 2D sprite (on an image point on the Back face).

- Can't adjust image point for 3D shape (necessary for some tiled games workflow to use snap and corner image point).

- Opacity on 3D shapes makes some faces glitchy, for example I you reduce the opacity by 1 from 100 to 0 and then do the reverse, some faces won't show the opacity properly during and after the changes.

- If you set the objects to faces on the instance 0 of a 3D shape and create the same shape on another layout, the faces won't use the texture object. The texture object for each face has to be present on the layout where the 3D shape are spawned into... No other object in C3 has this peculiarity. You can't use Set face to object if the object isn't on the layout where you placed the 3D shape... It should be possible if the faces are on one layout at least ?

Also, generally, I feel like layers should be "2D" until you had a 3D shape into it. Idk but I feel like 2D and 3D layers interaction with one another is not clear (at least for me).

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help you.

Please note some of these points appear to be covered by the documentation.
