### ISSUE TITLE
252 2D vanishing point render

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4896]
## Problem description

Some 2d objects on a 2d layer are rendered incorrectly.
They are being affected by the vanishing point.

## Attach a .c3p
https://www.dropbox.com/s/um0mt3dxgof8wcw/vpointext.c3p?dl=1

## Steps to reproduce

1.Run the project

## Observed result

The Pinned Text, and Drawing Canvas objects are rendered according to the vanishing point.
Their actual positions do not change.
## Expected result
The 2d layer should not be changed by the vanishing point.
2d objects should not be changed if they don't have a z to render to.

## More details

Placing the 2d objects on the 3d layer stops the vanishing point render.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by pigmalien** [comment]
It seems to also effect touch coordinates, but I'm having a hard time figuring out where. 
In my project the scrolling mechanic uses touch which works perfect in the last release, but the touch start is off in this beta.
I replicated the scrolling events in a new project, but it was perfectly fine. The project its not working is quite complicated with several layers of varying attributes.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next beta.
