### ISSUE TITLE
Timeline for Object inside Hierarchy working wrong

### ISSUE THREAD

**Issue by kimarutaGM** [Scirra/Construct-3-bugs#4897]
## Problem description
Timeline for Object inside Hierarchy working wrong

## Attach a .c3p
[TestHierachy.zip](https://github.com/Scirra/Construct-3-bugs/files/6660249/TestHierachy.zip)

## Steps to reproduce
1. Make a timeline to make SpriteA bigger in scale X. 
2. add SpriteA as children of SpriteB
3. Start Layout, play timeline of Sprite A. (A should bigger)

## Observed result
SpriteA become smaller

## Expected result

SpriteA should bigger 

## More details
1. Using Chrome 
2. Editor version r251.2
3. It's working well on r241

**Comment by skymen** [comment]
I got other issues with timeline and scene graph combined:
[scene graph timeline.zip](https://github.com/Scirra/Construct-3-bugs/files/6807139/scene.graph.timeline.zip)

This had issues with position, angle and size, but I somehow managed to fix the size issue.
In runtime, it works fine

**Comment by DiegoScirra** [comment]
A bunch of issues relating to this report have been fixed and will be available in the next beta.
