### ISSUE TITLE
Text right edge getting clipped when aligned to right and windows text size is set to 125%

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4898]
## Problem description

Text right edge getting clipped when aligned to right and windows text size is set to 125%
https://www.youtube.com/watch?v=McvgkQ7UtO4
You can see that in 125% it sometimes gets pushed to the left and sometimes to the right, depends on the font size.
Sometimes more than one character gets clipped.

## Attach a .c3p

https://github.com/Scirra/Construct-3-bugs/files/6488954/textClip.zip

## Steps to reproduce

1. Set windows text size to 125%
2. Open project and observe the text object both in edit and run time.

## Observed result

Text right edge getting clipped.

## Expected result

No clipping.

## More details

**Affected browsers/platforms:**  Chrome/NWjs

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.54.0
Browser engine: Chromium
Context: nwjs
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.54.0 (like Chrome/91.0.4472.77)
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 26 gb
Storage usage (approx): 309 mb (1.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6677)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I don't see any issue when using a Windows scale of 125%. I tried a range of different scales and they all looked fine to me.

I think the core issue is probably fractional pixel measurements - if you have a scale of 125%, it's possible it might try to draw text with a width of something like 52.25 pixels. It's not possible to draw 0.25 of a pixel, so sometimes the last row of pixels can be lost. I still don't see this happening, but even if it is, it could be the browser or OS cutting off the text, which would be beyond our control anyway. I'm afraid I don't see any action we can take on this, so closing.

**Comment by avishaymizrav** [comment]
@AshleyScirra
If it was just edit-time, I would let it go. But this also affects run-time and if it happens to me, it's a safe bet it can happen to other users/players.
I don't mind reporting it to wherever needed so it'll get fixed, I just need a little guidance with where to post it and what details to send with it.

I tested it on edge, I get the same result, on firefox on the other, it might get pushed left with extra padding, but it doesn't get pushed right, never clipped.

So I'm guessing its a Chromium issue (NWjs also affected).

**Comment by avishaymizrav** [comment]
@AshleyScirra After some more investigation, I tried creating a new blank window user and to my surprise it displays the texts correctly.
Same machine, same OS, same display settings.
So it brings us back to a windows issue.

Do you have any idea what per user conditions might be causing this?

**Comment by avishaymizrav** [comment]
I felt like there's no point on posting a new issue, please just reply when you read this, so I know it got through.
 
@AshleyScirra OK, after a lot of messing around I finally found what the issue was, it turns out for some reason, "ClearType Text" was not enabled (or somehow got disabled) on my windows, this is a per user windows setting.
When it's off and the scaling is higher than 100% the text align gets clipped.
Maybe you should document it somewhere as it can affect both the editor and the runtime previews/exports, I would go as far as checking if it is enabled and prompting if not.
