### ISSUE TITLE
STB Remote key issue

### ISSUE THREAD

**Issue by coolwd10** [Scirra/Construct-3-bugs#4899]
When I Press Left/Right/UP/DOWN(Recognize as gamepad key) from stb remote Event fire and reach to main.Js Gamepad code for example Key Down 20 and UP 19 key code reach. But The Object is not moving.Can u help to solve the issue 

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.
