### ISSUE TITLE
Whitelist plugin (1 new & 1 essential)

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#4900]
## New Plugin:
Hi, the Facebook Cordova Plugin that are currently available in C3 are either outdated or by developers who built it for their private (closed-source) c3plugins.

This is the latest open source Facebook Plugin available on Github:

`cordova-plugin-facebook-connect@2.3.0`

## Essential Update:
The older version stops working in Devices with iOS >= 14, and several more bugs.
`cordova-plugin-sign-in-with-apple@0.1.2`

Thank you ^^

**Comment by Visual917** [comment]
I second this. Sparsha's plugin is a lifesaver!

**Comment by AshleyScirra** [comment]
Please file essential and routine updates separately so we can track them independently.
