### ISSUE TITLE
Whitelist Plugin (new)

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#4901]
Hi, the Facebook Cordova Plugin that are currently available in C3 are either outdated or by developers who built it for their private (closed-source) c3plugins.

This is the latest open source Facebook Plugin available on Github:

`cordova-plugin-facebook-connect@2.3.0`

Via #4902:
`cordova-plugin-sign-in-with-apple@0.1.2`

Thankyou.

**Comment by AshleyScirra** [comment]
Build service updated to allow these plugins.
