### ISSUE TITLE
Whitelist Plugin (routine)

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#4902]
The older version stops working in many Devices with iOS >= 14, and several more bugs.

`cordova-plugin-sign-in-with-apple@0.1.2`

Thankyou so much.

**Comment by AshleyScirra** [comment]
No prior version of `cordova-plugin-sign-in-with-apple` is on the build service therefore this is a request for an entirely new plugin. These requests are not regarded as essential and so will be addressed on a routine schedule.

**Comment by AshleyScirra** [comment]
Since #4901 was filed at the same time as a routine request, merging in to that issue.
