### ISSUE TITLE
Bullet bounces backwards on corner impact

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4905]
## Problem description

When a bouncing bullet hits the corner of a solid, it reverses direction instead of continuing on. 

## Attach a .c3p

https://drive.google.com/file/d/1-fbNj11uI1SR2uKayQY1ZOGgeTzkfy_R/view?usp=sharing

## Steps to reproduce

1. Run the project
2. Note the direction change on the left corner
3. Note the lack of direction change on the right corner

## Observed result

The bullet reverses direction on the left corner.

## Expected result

The bullet should continue in its direction on impact, like it does on the right corner.

## More details

**Affected browsers/platforms:** Chrome 91

**First affected release:** r252

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I can't see anything wrong in this project. I just see a green square bounce once in the middle then fall off. It doesn't seem to match up to the description. Did you attach the right file?

**Comment by brushfe** [comment]
Strange! Here's a video of what happens on my screen.

https://imgur.com/a/XIEUO3p

**Comment by AshleyScirra** [comment]
I can reproduce if I manually adjust the size of the solid so it lands exactly on its corner.

Unfortunately I don't think there's anything we can do about this. The bounce angle is an estimation, because the engine doesn't know what the perfect surface normal angle is. It's known to make bad estimates in some scenarios, but it's only an estimate, and it's the best we can do.

**Comment by brushfe** [comment]
That's too bad — thanks for the investigation. I know these features are meant to replace actual coding, but if there's a way to calculate this more accurately using events, perhaps that could be shown in one of the sample projects you release with updates.
