### ISSUE TITLE
Keyboard doesn't work properly on undocked/windowed event sheet.

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#4907]
## Problem description

For some reason all keyboard shortcuts work very well when I'm working on a single window, but if I undock an event sheet and turn it into its own window to work with two monitors, suddenly the engine does not respond to some keyboard shortcut like it usually does in a single window.

## Attach a .c3p

[Undocked Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/6686963/Undocked.Bug.zip)

## Steps to reproduce

1. Undock the "Event sheet 1" event sheet.
![image](https://user-images.githubusercontent.com/27010889/122769077-9d30db80-d27a-11eb-9a0b-125a2f1626fd.png)

2. Turn the "Event sheet 1" event sheet into its own window by clicking on "Open to popup window".
![image](https://user-images.githubusercontent.com/27010889/122769162-b20d6f00-d27a-11eb-810e-473f3180159c.png)

3. Select the first "Every tick" event, but only the event itself, not the entire block.
![image](https://user-images.githubusercontent.com/27010889/122769240-c8b3c600-d27a-11eb-9809-5b19d61ce2c1.png)

4. Press the down arrow to select the event below it, this command should work fine, but now try to press "Enter" to open it, this one will not work at all.
![image](https://user-images.githubusercontent.com/27010889/122769558-06185380-d27b-11eb-8cd8-1ff3162f1198.png)

5. Now try it all again, but without the undocked window, the command will work just fine.
![image](https://user-images.githubusercontent.com/27010889/122769957-63140980-d27b-11eb-9932-c45bc547cf54.png)

*I noticed that this is not the only command that doesn't work, pressing "Space" to select a key in a "On key pressed" event doesn't work as well. I'm not sure on how many commands doesn't work in windowed mode, but I suppose there are more.

## Observed result

Some commands only work in non-windowed event sheets.

## Expected result

All commands to work in windowed event sheets.

## More details

**Affected browsers/platforms:** Google Chrome v91

**First affected release:** r251.2 Stable

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I found some issues with routing keyboard events from popup windows. It should be fixed in the next beta, which looks like it solves the issues you mentioned here.

**Comment by BonzerKitten** [comment]
@AshleyScirra Thank you very much for the quick fix! I'll make sure to test the next beta release once it comes out and let you know if I find any other problem.

**Comment by BonzerKitten** [comment]
@AshleyScirra I tested the latest beta release to see if the shortcuts were working properly, but unfortunately there's something weird happening with undocked windows, they keep loading forever and don't match the selected theme of the editor (my editor is dark, but the undocked window is light). The shortcuts don't seems to be working as well, pressing "E" don't create a new event and pressing "Esc" don't close the "Add condition" prompt.

![image](https://user-images.githubusercontent.com/27010889/124128343-12f32f00-da53-11eb-9f82-6b1bdd7f4daa.png)

By the way, I can open a new issue if you prefer to keep things separated.
