### ISSUE TITLE
When a 2d Parallax layer visibility is on, the touch coordinates become offset

### ISSUE THREAD

**Issue by johnsmith27** [Scirra/Construct-3-bugs#4908]
## Problem description

Very similar to this issue I believe: https://github.com/Scirra/Construct-3-bugs/issues/4896

Using a 3d layer & a 2d layer for background with parallax - the touch coordinate become offset when the parallax layer visibilty is on. (changing vanishing point doesn't seem to do anything as the problem is still here on default 50-50):
[layer_touch.zip](https://github.com/Scirra/Construct-3-bugs/files/6687326/layer_touch.zip)

## Steps to reproduce

1. use touch to move the sprite around (or the keyboard arrows, but it's not affected by the problem)
2. toggle layer 1 visibility

## Observed result

The touch coordinates are offset or something when the parallax layer is visible (while the keyboard arrows are still working normally)

## Expected result

The touch coordinates should still be working correctly

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r252

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This looks like the same issue as #4904 and is already working in my development build so should already be fixed in the next beta.
