### ISSUE TITLE
Can`t build an apk-file

### ISSUE THREAD

**Issue by IcticStep** [Scirra/Construct-3-bugs#4909]
## Problem description
I can`t build an apk file of my Construct 3 game. It is really big project, I was working on for a few years, but it seems to be broken now.

## Attach a .c3p
A .c3p file was sent to support@construct.net in order to keep sources confidetial(Julien from Scirra said I can do that in this way). Title of email is: "Problems with export of large project".

## Steps to reproduce

1. Open the project.
2. Try to build an apk(I tried to set up these settings: [one](https://drive.google.com/file/d/1OiK1mnmGagYNZWVPAcSlX67oYFKJ8PsH/view?usp=sharing) and [two](https://drive.google.com/file/d/1J0TzLTQDZJXTlYqrzq5hE7k6oZhBlaz0/view?usp=sharing)).
3. Get stucked with message "Bundling script..." for infinite time.
4. See errors occured in DevTools by F12.

## Observed result

I can see a message about bundling script. I have tried to give much time for Construct 3 and left it in buliding mode for a whole night(about 10 hours). Nothing was finished. It is totally stucked.

## Expected result

I expected to get a debug apk for some tests on my Anroid-phone.

## More details

**Affected browsers/platforms:** 

Chrome App(Chrome v.91.0.4472.114 stable(64 bit), Construct 3 r251.2 stable)

**First affected release:** 

## System details

You can find screen of errors from DevTools of Construct 3(F12 menu -> Console): [here](https://drive.google.com/file/d/197-7NOuo1rbRLUi7Fcd753gRwpx-8ql-/view?usp=sharing).

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.114
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 60 gb
Storage usage (approx): 934 mb (1.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6677)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can reproduce, but it's crashing in our build of Closure Compiler that processes JavaScript code which we didn't make ourselves and we don't have any good way of changing it at all. I'm afraid I really can't think of anything we can do about this.

It looks like it's too big a script file for it to process. All I can think to work around it is you will have to find some way to make the project smaller.

**Comment by IcticStep** [comment]
_All rude words were censored by the author. There was about few thousand of them here. The author is not blaming anyone in person, but describing the worst situation in his life._

So, you mean that my 5 years of studying Construct(starting from 2 and moving to 3), nearly 1500 hours of developping this game in Construct 3, nearly 1000 hours of drawing graphics and animations, nearly of 100 hours help from my friends(game testing, additional animations) are just erased by some outer service?

So you mean that [this](https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-uses-large-project-157822) your words about limitations of Construct 3 was just a joke?

And how can you imagine me finding out the small problem part of project if error is caused by enormous size? That means any small project can be build, but the project of a dream have only one option: to be put into the trashbin next to his author. 

And now, after so long development, you think I can just restart all my work and develop the same things in second time with a little hope, that project will have a small chance for being build after that?

In conlusion, I have spent nearly 3500-4500 hours for studying and reasearching Construct, I had plans to release two big comercial games and after that start some kind of educational courses connected to developping games in Construct(perhaps totally free)... I was going to spent so big part of my life for this(and a really big part have already spent) and now my work is just eliminated by such impossible situation.

You know, being avoided after 5.5 years secret love wasn`t so painful as this. In comparation, it wasn`t even painful at all. If it is the end of this project, it seems that meaning of life was erased completely. 

Sorry, for my bad English. I can`t think about gramatic anymore.

**Comment by henrikszucs** [comment]
You can try other browsers or NW.js. The final solution that you should increase the stack limit in the browser. It possible to solve a problem.

**Comment by AshleyScirra** [comment]
I'm afraid I don't know what to tell you. Some problems are beyond our control. We can't be expected to fix those, no matter how frustrating it is. Perhaps some other workaround exists, but I don't know what it might be, it would have to be up to your own experimentation, but I recommended making the project smaller as it probably will solve the problem. It's possible some future update to the JavaScript minifier would fix this, but it is not guaranteed, and that could take months from now too.

This is also why regular testing is important. If you work for 6 months and only then try to export your project and something goes wrong, you have 6 months work at stake. If you did a test export every week, you'd find the problem sooner and before you spent so much time, and there'd be more time to spend solving the problem.

**Comment by IcticStep** [comment]
> You can try other browsers or NW.js. The final solution that you should increase the stack limit in the browser. It is maybe solve a problem. Here some test: https://stackoverflow.com/questions/7826992/browser-javascript-stack-size-limit

Wow! You are an epic guy! You are fantastic, fascinating and breathtaking person! You have saved my work, my life and perhaps this world from some nuclear explosions! Thanks so much! I just can't find appropriate words to express all my feelings now! 

I can easily make export using Mozilla Firefox instead of Chrome. Once again thanks to you, @henrikszucs!

But despite such great news I could't find actual NW.js version of Construct 3. Or [this](https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-nw-js-desktop-app-131317) is the only version available?

Also, I have one more question to @AshleyScirra : is it normal to have all these errors in browser's console? Should I be worried?
![image](https://user-images.githubusercontent.com/59373161/122962463-1e2cc780-d38e-11eb-9a2b-44ee8af0131d.png)

**Comment by AshleyScirra** [comment]
I don't know what any of those console messages mean, but they don't look related to Construct.

**Comment by IcticStep** [comment]
> I don't know what any of those console messages mean, but they don't look related to Construct.

Ok, thank you. Finally, this terible day is over and I can return to my work using such good game engine.
