### ISSUE TITLE
Layer Opacity changes it's Z distance too

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#4910]
## Problem description

In r253 the layer opacity appears to be affecting the Z distance as well.

## Example, Before and After  

changing the opacity of a layer that contains ceiling traps:

![image](https://user-images.githubusercontent.com/5744908/123044902-a74f0780-d43d-11eb-8b96-ce7f0fb0efb1.png)

![image](https://user-images.githubusercontent.com/5744908/123044665-53442300-d43d-11eb-91bc-a6d2f3d6d207.png)

![image](https://user-images.githubusercontent.com/5744908/123044797-7e2e7700-d43d-11eb-88af-572908c8c9ad.png)

## Attach a .c3p

[layer-opacity.zip](https://github.com/Scirra/Construct-3-bugs/files/6699361/layer-opacity.zip)

## Steps to reproduce

1. change layer opacity
2.
3.

## Observed result

object is smaller

## Expected result

no Z effects

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Dramamini** [comment]
I have similar problems, opened my project with 253 and layouts are meshed up. It happens with opacity, on use own texture enabled, when a layer has an effect or when there is a different blend mode than normal. Also affects all text Z distance. I' m trying to find a way to reproduce the problem and fill an issue but it is very tricky... For example when I start a new project there is no problem at all.

**Comment by AshleyScirra** [comment]
Oops, some rendering code was accidentally broken. It should be fixed for the next beta. Leaving open as I suspect others will run in to this.

**Comment by AshleyScirra** [comment]
This should now be working again in r254.
