### ISSUE TITLE
Data editor text alignment is confusing

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#4911]
It's difficult to discern which label applies to which field, due to the text alignment.

You mistakenly type a value into the field "width" but then realize you changed the "height" by accident!

For example: 

##

![image](https://user-images.githubusercontent.com/5744908/123063246-93f96780-d450-11eb-998b-336de66b1b23.png)

This is technically "50 = Height", but the value is actually closer to the "width" in pixels, so it's difficult to tell what's going on.

##

Perhaps something along these lines might help readability?

![image](https://user-images.githubusercontent.com/5744908/123064073-4c271000-d451-11eb-98fd-ac59b05a2425.png)

Thanks!

**Comment by AshleyScirra** [comment]
It looks OK in the default theme. @DiegoScirra I think you changed this recently? Maybe it needs tweaking for the dark theme.

**Comment by DiegoScirra** [comment]
The dark theme explicitly changes the side on which labels of toolbar inputs in the data editor are shown. It has been like that since the introduction of the light and dark themes. It's an easy change.
