### ISSUE TITLE
Text alignement Broke in r253

### ISSUE THREAD

**Issue by karimlahbach** [Scirra/Construct-3-bugs#4914]
This In r252 (The Text under score is good )

<img width="956" alt="Screen Shot 2021-06-23 at 17 48 31" src="https://user-images.githubusercontent.com/22240696/123136918-5e05b480-d44b-11eb-8264-6c441291e28b.png">

and This after opening the project in r253 (the text change position )

<img width="956" alt="Screen Shot 2021-06-23 at 17 45 45" src="https://user-images.githubusercontent.com/22240696/123137077-842b5480-d44b-11eb-9ebc-619516e691cf.png">

and if you try to correct the postion in the project the text change position in Preview 
i'm sorry i can't reproduce this in a simple mini project but definitely (Text alignement got broke in r253)

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to investigate.

**Comment by karimlahbach** [comment]
Hi Ashley sorry for not following the guideline ( it happen only on my 6 month working Project File ) i couldn't reproduce the bug in mini example 
but i think it related to this
https://github.com/Scirra/Construct-3-bugs/issues/4916
