### ISSUE TITLE
Fail to export with Advanced Minification if there is a Slider Bar

### ISSUE THREAD

**Issue by 68kStudios** [Scirra/Construct-3-bugs#4915]
## Problem description

Can't export with Advanced minification if there is a Slider Bar object in the project
## Attach a .c3p

https://drive.google.com/file/d/1D6wy8DaY0ZAPsLQsByGaF1HF_5AoBCE9/view?usp=sharing

## Steps to reproduce

1. Create a new project
2. Add a Slider Bar object
3. Export (Html5, NW.js, etc.) with Advanced Minification

## Observed result

Error:
/str/c3runtime.js:2588:98: ERROR - [JSC_UNDEFINED_VARIABLE] variable value is undeclared

## Expected result

Export with no issue

## More details

**Affected browsers/platforms:** 

**First affected release:** r251.2

## System details

Platform information
Browser: Chrome
Browser version: 91.0.4472.114
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 9.1 gb (1.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) RX Vega 11 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.1034.6)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
<details><summary>View details</summary>

/str/c3runtime.js:2588:98: ERROR - [JSC_UNDEFINED_VARIABLE] variable value is undeclared
  2588| map.set(this,self.IInstance._GetInitInst().GetSdkInstance())}set value(v){C3X.RequireFiniteNumber(value);map.get(this)._SetValue(v)}get value(){return map.get(this)._GetValue()}set maximum(v){C3X.RequireFiniteNumber(v);map.get(this)._SetMaximum(v)}get maximum(){return map.get(this)._GetMaximum()}set minimum(v){C3X.RequireFiniteNumber(v);map.get(this)._SetMinimum(v)}get minimum(){return map.get(this)._GetMinimum()}set step(v){C3X.RequireFiniteNumber(v);map.get(this)._SetStep(v)}get step(){return map.get(this)._GetStep()}set tooltip(str){C3X.RequireString(str);
                                                                                                          ^^^^^

1 error(s), 0 warning(s)

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next beta.
