### ISSUE TITLE
r253 - bounding box is misplaced in editor

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#4916]
## Attach a .c3p

https://www.dropbox.com/s/98mw1cq5ce2dnqt/bbb.c3p?dl=0

## Steps to reproduce

Click the sprite on test layout.

## Observed result

![image](https://user-images.githubusercontent.com/36763350/123367241-f3748600-d5bc-11eb-9bd7-0715810b7ebf.png)

## More details

Somehow deleting some of the other layouts affects the position of this bounding box - it moves closer to the sprite.

**Affected browsers/platforms:** Chrome/Firefox

**First affected release:** seems to be working in r251

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.114
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
C3 release: r253 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 293 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
WEBGL_webcodecs_video_frame
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by dop2000** [comment]
Something is wrong with the layout editor, it's impossible to work with large layouts - almost all objects are misplaced, scaled incorrectly etc.
Here is the same portion of the layout, the top screenshot made in r253, the bottom one is from r251
![image](https://user-images.githubusercontent.com/36763350/123409223-4b2ce480-d5f1-11eb-8315-e51c9b3d5132.png)

**Comment by mOOnpunk** [comment]
Having the same issues. It makes trying to grab the scale and rotate points almost impossible for me at the moment.

**Comment by corlenbelspar** [comment]
I'm also having this happen in r253, but only if I have more than one row of tabs open.

**Comment by pcfernandesjr** [comment]
I am having the same issue. The bounding box also moves around if I'm scrolling through the layout or zooming in / out.

**Comment by AshleyScirra** [comment]
The editor would incorrectly scale and misalign things if resized, which is a regression in r253. It should be fixed in the next beta.
