### ISSUE TITLE
Keyboard shortcuts not working for newly created files

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#4917]
## Problem description

After creating a new file in the Files folder, some keyboard shortcuts will have no effect on the file, until I right-click on it, then the keyboard shortcuts will work again.

## Attach a .c3p

(Happens with new projects)

## Steps to reproduce

1. Create a new project.
2. Create a new Array file under the Files folder.
3. Left-Click on the file.
4. Click F2 button on the keybaord. Doesn't work.
5. Click Delete button on the beyboard. Doesn't work. 
6. Right-click on the file.
7. Repeat 4 and 5. They should work now.

## Observed result

Keyboard shortcuts not working.

## Expected result

Keyboard shortcuts should work.

## More details

**Affected browsers/platforms:** Firefox 89.0.1

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Where exactly are you clicking in step 3 ("Left-Click on the file")? It sounds like it could be either the name of the file in the Project Bar, or the contents of the file in the Data Editor, or possibly something else.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.

For some reason, in the particular instance of clicking an item right after creating a file, the project bar was not gaining focus, and so the keyboard shortcuts associated with it did not work.
