### ISSUE TITLE
Mobile UI - Bookmarks bar stuck

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#4918]
## Problem description

In mobile UI the bookmarks bar not slide. It work only when slide in the top of the bar.

## Attach a .c3p

In editor

## Steps to reproduce

1. Use on mobile
2. Swipe between bars
3. Bookmarks bar stuck and prevent slides

## Observed result

Bookmarks bar not slide

## Expected result

Bookmark bar can slide as other bars

## More details

https://user-images.githubusercontent.com/47735877/123400965-9bcb2000-d5a6-11eb-9394-f7d6b14fb5d6.mp4

r251.2 all bar work
r253 bookmark bar stuck

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.120
Browser engine: Chromium
Context: webapp
Operating system: Android
Operating system version: 9
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Linux; Android 9; Redmi 6A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.120 Mobile Safari/537.36
C3 release: r253 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 5.8 gb
Storage usage (approx): 4.2 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Imagination Technologies
Renderer: PowerVR Rogue GE8320
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_filter_anisotropic
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_pvrtc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
