### ISSUE TITLE
Copying a sprite with an instance var to another project with the same sprite but 1 less instance var crashes C3

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#492]
## Problem description

I tried to reproduce a bug (for some reason this is where I run into other bugs xD) and I copied my sprite that had 2 instance vars from my main project to a new project where I created beforehand the same sprite, with only 1 instance variable (i forgot about the 2nd one). That's when C3 crashed.

## Attach a .c3p

I shall delight you with not 1, but **2!** c3p files.

[PasteHere.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1069254/PasteHere.c3p.zip)
[CopyFromHere.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1069255/CopyFromHere.c3p.zip)

![copyfrompastehere](https://user-images.githubusercontent.com/7268697/27050647-00fa7b4e-4fbc-11e7-9769-5adeaedf99b5.gif)

## Steps to reproduce

1. open up both projects
2. from the project "CopyFromHere" copy the 1st event
3. paste it in the project "PasteHere" (notice the right click menu doesn't have any paste option too so in the gif i used CTRL+V)

## Observed result

The "PasteHere" project crashes.

## Expected result

No crash

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r37/main.js, line 61, col 322887
Message: Uncaught Error: instance variable 'AttachedUID' missing in object 'Interaction_Proximity'
Stack: Error: instance variable 'AttachedUID' missing in object 'Interaction_Proximity' at window.ǃdO.ǃTp (https://editor.construct.net/r37/main.js:61:322893) at e.ǃmif (https://editor.construct.net/r37/main.js:61:281181) at Function.ǃVa (https://editor.construct.net/r37/main.js:61:286317) at i.ǃTp (https://editor.construct.net/r37/main.js:61:277743) at Function.ǃVD (https://editor.construct.net/r37/main.js:61:257855) at i.ǃmDf (https://editor.construct.net/r37/main.js:61:261797) at i.ǃTp (https://editor.construct.net/r37/main.js:61:277761) at Function.ǃVD (https://editor.construct.net/r37/main.js:61:257855) at i.ǃmDf (https://editor.construct.net/r37/main.js:61:261797) at i.ǃTp (https://editor.construct.net/r37/main.js:61:277761)
Construct 3 version: r37
URL: https://editor.construct.net/
Date: Mon Jun 12 2017 22:02:08 GMT+0300 (GTB Daylight Time)
Uptime: 63.6 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r37

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by JeFawk** [comment]
Happens with objects too. I pasted this and forgot to add the function object, so it crashed. 

![image](https://user-images.githubusercontent.com/7268697/27050767-6050b28e-4fbc-11e7-8c37-c126805bb77a.png)

Error report information
Type: unhandled exception
File: https://editor.construct.net/r37/main.js, line 61, col 285872
Message: Uncaught Error: cannot find object 'Function'
Stack: Error: cannot find object 'Function' at Function.ǃVa (https://editor.construct.net/r37/main.js:61:285878) at i.ǃTp (https://editor.construct.net/r37/main.js:61:277743) at Function.ǃVD (https://editor.construct.net/r37/main.js:61:257855) at i.ǃmDf (https://editor.construct.net/r37/main.js:61:261797) at i.ǃTp (https://editor.construct.net/r37/main.js:61:277761) at Function.ǃVD (https://editor.construct.net/r37/main.js:61:257855) at t.items.map (https://editor.construct.net/r37/components/editors/eventSheetView/eventSheetView.js:1:33049) at Array.map (native) at window.ǃvL.ǃVC (https://editor.construct.net/r37/components/editors/eventSheetView/eventSheetView.js:1:33036) at window.ǃvL.ǃkf (https://editor.construct.net/r37/components/editors/eventSheetView/eventSheetView.js:1:32101)
Construct 3 version: r37
URL: https://editor.construct.net/
Date: Mon Jun 12 2017 22:12:40 GMT+0300 (GTB Daylight Time)
Uptime: 357.2 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r37

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
Thanks, turns out pasting wasn't correctly handling errors. Should be fixed in r38.
