### ISSUE TITLE
Xcode Error

### ISSUE THREAD

**Issue by ManuelSanMatin** [Scirra/Construct-3-bugs#4920]
![captura-de-pantalla-2021-06-23_v800](https://user-images.githubusercontent.com/70768024/123438721-6246e480-d5a7-11eb-8adc-4f8d221be7ab.png)
![captura-de-pantalla-2021-06-23](https://user-images.githubusercontent.com/70768024/123438745-65da6b80-d5a7-11eb-9c8c-3b3cc4f9e535.png)

in Xcode I get the following error. Pods folder is missing. and file Podfile.lock

## Steps to reproduce

1. Export for IOs
2.ios14.0+ and Xcode
3.

## Observed result

when unzipping the zip, files are missing that Xcode is looking for

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible for us to help unless you follow the bug report guidelines. The issue may also be to do with your copy of Xcode, its configuration, or the use of any third-party addons that are beyond our control.

**Comment by ManuelSanMatin** [comment]
create a new project, add IAP export IOs for Xcode. try to open in Xcode. the error only appears with IAP, with MobileAdvert they worked fine.
Construct3 R251.2
