### ISSUE TITLE
Changing/scrolling Z elevation to 100, will crash c3 

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4921]
## Problem description
Setting z elevation to 100 will crash c3

## Steps to reproduce

1.New project
2.Add sprite
3.Select layer and set z elevation 100 or scroll with mouse from 0->102

## Observed result
Crash

## Expected result
NO crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r253/main.js, line 836, col 29
Message: Uncaught TypeError: expected finite number
Stack: TypeError: expected finite number at Function.Q.m (https://editor.construct.net/r253/main.js:836:35) at window.Tj.lV (https://editor.construct.net/r253/components/editors/layoutView/layoutView.js:106:164) at d.tG (https://editor.construct.net/r253/projectResources.js:1103:117) at d.vla (https://editor.construct.net/r253/projectResources.js:695:401) at $6a.J0 (https://editor.construct.net/r253/components/editors/layoutView/layoutView.js:232:172) at $6a.pf (https://editor.construct.net/r253/components/editors/layoutView/layoutView.js:230:436) at Array.Ne (https://editor.construct.net/r253/components/editors/layoutView/layoutView.js:227:110) at window.Tj.dispatchEvent (https://editor.construct.net/r253/main.js:1023:386) at window.Tj.pf (https://editor.construct.net/r253/components/editors/layoutView/layoutView.js:97:468) at HTMLDocument.Ne (https://editor.construct.net/r253/components/editors/layoutView/layoutView.js:83:370)
Construct 3 version: r253
URL: https://editor.construct.net/r253/
Date: Sat Jun 26 2021 12:18:15 GMT+0300 (Eastern European Summer Time)
Uptime: 121.7 s

Platform information
Browser: Chrome
Browser version: 91.0.4472.114
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
C3 release: r253 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next beta.
