### ISSUE TITLE
Resizing Spritefont sprite distorts text

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4922]
## Problem description

Resizing a Spritefont's image causes the Spritefont object to render improperly (vertically squeezed and letters remapped).
 
## Attach a .c3p

https://drive.google.com/file/d/12raT6G4KihFq2WRBFqz_X1jagTpuF0iT/view?usp=sharing

## Steps to reproduce

1. Open the attached file
2. Open the Spritefont object in the animation editor
3. Change the height to 512

## Observed result

The Spritefont object changes from "Text" to "j2 + r." and is vertically compressed.

Image of rendered error here: https://imgur.com/a/uJR8p3j

## Expected result

Nothing; the division of the Spritefont letters in the image shouldn't be affected, nor should the image rendering.

## More details

**Affected browsers/platforms:** Chrome 91

**First affected release:** r252, present in 253

**Comment by AshleyScirra** [comment]
Note for future reference: step 3 should be "use image editor resize tool, disable keep aspect ratio, change height to 512, and align image to top-left". It does not reproduce with other alignments or if you change the height of the object, not the image.

Should be fixed in next beta.
