### ISSUE TITLE
Find All References doesn't show some disabled conditions

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#4925]
## Problem description

I have a disabled function with sub conditions and actions. Using "Find all references" on a sprite doesn't show some conditions as disabled (which made me revise the code because I was sure I disabled this line earlier). While using the normal Find (Ctrl+F) dialog shows correct results.

## Attach a .c3p
[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/6724562/New.project.zip)

## Steps to reproduce

1. In the project bar, right-click on Sprite
2. choose Find all references

## Observed result

All references of the Sprite are shown disabled, except the condition

## Expected result

All the disabled actions/conditions should be shown disabled

## More details

![Untitled](https://user-images.githubusercontent.com/12113416/123602769-68340400-d7f9-11eb-9d39-82c4e3d00701.png)

**Affected browsers/platforms:** Firefox

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next beta.
