### ISSUE TITLE
Game working incorrectly on Sumsung A-12

### ISSUE THREAD

**Issue by IcticStep** [Scirra/Construct-3-bugs#4926]
## Problem description

I have made a debug apk-file of my big project for having some tests on different devices. It workes correctlty on every phone/tablet PC I have access to, except Sumsung A-12 with Android 11. Game just crashes on it. System requiroments shouldn't be the reason but I don't know what I should do to investigate this, because the game is using just ~100 mb video memory and about 10-30% of CPU.

## Attach a .c3p

.c3p file was sent to support@construct.net to keep it from society. Sorry, I don't know how to minificate this to save bug but to remove all useless things for investigation. Email title is "Construct 3 bug report #4926 confidential file".
Game debug-apk file: [link](https://drive.google.com/file/d/1R4ofyQriaC8GfX7My2Jw62ITKzy0bMCB/view?usp=sharing)

## Steps to reproduce

(Sorry, I don't have game localiztion yet, so I will tell all the steps detaily).
1. Install the debug-apk on Sumsung A-12 with Android 11.
2. Tap all the text and animation to go throug intro.
3. When you arrive into the room, open menu and select first option.
4. Go through useless game-tips.
5. Enter the third link on the right("Фриланс-биржа").
6. Go to the middle tab and select first link("Найти работу").
7. Enter the first link ("Тестирование игр") and then launch any from available.
8. Just try to play 1-2 minutes and you will have a crash. It won't happen if device is not Sumsung A-12 with Android 11.

## Observed result

Game is crashing. [Here ](https://www.youtube.com/watch?v=i2_lenRCJm4) is video.

## Expected result

Game should work correctly.

## More details

**Affected browsers/platforms:** 
Sumsung A-12, Android 11, debug apk of project

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.114
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 60 gb
Storage usage (approx): 928 mb (1.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7111)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid such issues are typically graphics driver crashes, which are beyond our control. You could try filing an issue with Google at crbug.com in case they can do anything about it.

There is little else we can do - we don't currently have that specific device for testing; even if we did, we'd need a minimal project as per the bug report guidelines for it to be feasible for us to investigate; and even if we did all that, I think it is very likely we'd see a graphics driver crash which we can't do anything about anyway. Therefore closing as I doubt there is anything useful we can do here - you'll have to pursue this by other means.
