### ISSUE TITLE
"Open to Popup Window" behaving weird only on r253

### ISSUE THREAD

**Issue by Jase0000** [Scirra/Construct-3-bugs#4927]
![r253 Window Popup Bug](https://user-images.githubusercontent.com/64868300/123811658-592d7e80-d8eb-11eb-9725-982d0f0dd8b6.png)
I was waiting a few days, because I was worried I would write a duplicate issue, but I feel like I've checked a number of times and I don't think I can see this bug posted in "Open" or "Closed". Sorry if it is a duplicate!

## Problem description

Use any of the window's "Open to Popup Window" options, e.g. for the "Layer" window, "Find" window, "Find All References" window.
It seems to be broken on the latest beta r253 - The word "Loading..." is at the top, the current theme does not load, and there's an error in Chrome's log mentioning "Uncaught ReferenceError: CCG is not defined"

If I jump back to any older version of Construct 3, everything works fine.

## Attach a .c3p

Not required, this can be observed with blank project. See attached for a screenshot of what I see, along with the F11 Chrome log error.

## Steps to reproduce

1. Open Construct 3 r253
2. Right-click on any window that allows "Open to Popup Window" and choose this.
3. Observe

## Observed result

The word "Loading..." is at the top, the current theme does not load, and there's an error in Chrome's log mentioning "Uncaught ReferenceError: CCG is not defined"

## Expected result

Popup and load theme correctly and behave like normal.

## More details

**Affected browsers/platforms:** Chrome/Firefox/NWJS, Windows

**First affected release:** e.g. worked in all previous version, but broke in r253

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.114
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
C3 release: r253 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 290 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6156)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Jase0000** [comment]
Literally after I posted this, r254 came out, but it's still broken in r254!

**Comment by AshleyScirra** [comment]
Thanks for spotting that, it looks like it works in development but got broken by some changes to the build system. I think it should be fixed for the next beta, but will double-check once it's out to make sure it went through the build system correctly.

**Comment by AshleyScirra** [comment]
This looks like it's working correctly in r255 now. Please file a new issue if you run in to any further issues.
