### ISSUE TITLE
 Is the AdMob Plus PRO plugin still worth selling?

### ISSUE THREAD

**Issue by EMI-INDO** [Scirra/Construct-3-bugs#4928]
### Is the AdMob Plus PRO plugin still worth selling?
[https://www.construct.net/en/game-assets/addons/admob-plus-pro-768](url)

I see the Mobile Advert plugin id has changed to `admob-plus-cordova`

And I saw that there were buyers who made refunds for no reason

**Comment by AshleyScirra** [comment]
It's entirely up to you. But there's always been an AdMob-supporting ad plugin built in to Construct, so you were duplicating a built-in feature of Construct from the start.
