### ISSUE TITLE
Whitelist plugins (Routine)

### ISSUE THREAD

**Issue by tuzke** [Scirra/Construct-3-bugs#4929]
Hi, please add the addons: 

> cordova-plugin-applovin-max@1.0.6

**Comment by tuzke** [comment]
Please check as soon as possible. I need it soon for business. thanks

**Comment by tuzke** [comment]
@AshleyScirra Did you add it to the build service? I just want to know to continue the project

**Comment by AshleyScirra** [comment]
Please allow several weeks for security review of Cordova plugin requests. Please also refer to the [Forum & Community guidelines](https://www.construct.net/en/forum/general/open-topic-33/forum-community-guidelines-141035) rules around nagging staff and being patient.

**Comment by AshleyScirra** [comment]
I'd also add `sparsha-firebase-messaging` appears to delete the references to the original fork's repository and authorship, going so far as to replace the copyright in the MIT license, which I think probably violates the MIT license, as it requires that you preserve the copyright notice. I don't believe it allows for misrepresenting the author of the code. This may be reason enough to decline it, but I'll await your response first.

**Comment by AshleyScirra** [comment]
Added to build service.
