### ISSUE TITLE
 Failed to execute 'postMessage' on 'Worker': ArrayBuffer at index 0 is already neutered.

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#493]
## Problem description

not really sure, i was duplicating animations and playing with the animation editor when this happen

the engine crashed

## Attach a .c3p

i have attached a c3p file, this is the project i was working on when the issue happened, https://drive.google.com/open?id=0B-BWGR6TVR6BejFaVXZ1Z196ck0

the project is a bit big. I was modifying the cowboys roll up animation duplication some frames and moving it to the end of the animation when the exception happen.

## Observed result

the engine crashed i was prompted to save my work and restart! thanks for adding the save part that saved my but!!! plug for feature request!! auto save every so often (for lazy ppl like me who doesn't hit ctrl-s often enough!!!) great work though it really saved me when it crashed

## Expected result

the engine not crash =)

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

Error report information
Type: unhandled rejection
Reason: Error: Failed to execute 'postMessage' on 'Worker': ArrayBuffer at index 0 is already neutered. @ Error: Failed to execute 'postMessage' on 'Worker': ArrayBuffer at index 0 is already neutered. at i.ǃmZB (https://editor.construct.net/r37/main.js:61:49631) at window.ǃmPl.ǃmPa (https://editor.construct.net/r37/main.js:61:115680) at window.ǃmPl.ǃmPv (https://editor.construct.net/r37/main.js:61:114920) at Promise.all.then (https://editor.construct.net/r37/main.js:61:114718) at 
Stack: Error: Failed to execute 'postMessage' on 'Worker': ArrayBuffer at index 0 is already neutered. at i.ǃmZB (https://editor.construct.net/r37/main.js:61:49631) at window.ǃmPl.ǃmPa (https://editor.construct.net/r37/main.js:61:115680) at window.ǃmPl.ǃmPv (https://editor.construct.net/r37/main.js:61:114920) at Promise.all.then (https://editor.construct.net/r37/main.js:61:114718) at 
Construct 3 version: r37
URL: https://editor.construct.net/
Date: Tue Jun 13 2017 00:14:22 GMT-0400 (Eastern Daylight Time)
Uptime: 11823.1 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r37

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Sorry, there's very little we can do without steps to reproduce. In this case the crash report isn't particularly helpful.

**Comment by biology-w** [comment]
When these transferable objects are transferred, they are 'neutered' on the previous context — the one they previously belonged to. For instance a port, when is sent, cannot be used anymore by the original context. Note that the only two objects that can currently be transferred are ArrayBuffer and [MessagePort (en-US)](https://developer.mozilla.org/en-US/docs/Web/API/MessagePort).
from:
https://developer.mozilla.org/ko/docs/Web/API/Channel_Messaging_API
