### ISSUE TITLE
Changing text color with JS api doesn't work correctly with BBCode

### ISSUE THREAD

**Issue by nerdError** [Scirra/Construct-3-bugs#4931]
When you have text with BBCode color tags (e.g. `[color=red]`), and then you try to change it's `colorRgb` property with js api, color is changed incorrectly where BBCode color tag was applied. Meanwhile, if you change color with C3 action "Set font color", everything works fine.
## Attach a .c3p

[bbcode conflicts with text color bug.zip](https://github.com/Scirra/Construct-3-bugs/files/6750753/bbcode.conflicts.with.text.color.bug.zip)

## Steps to reproduce

1. Start the project
2. Press "Change" button

## Observed result

When color of the text is changed with js api, bbcode color tags doesn't work correct anymore (purple mixes with yellow, but it shouldn't be that way, it must stay yellow)
![image](https://user-images.githubusercontent.com/55310192/124189505-7f107a00-dac9-11eb-97aa-b4a6cd86d1e8.png)

## Expected result

Part of text where BBCode color tag is applied must stay untoched, color must not change there
![image](https://user-images.githubusercontent.com/55310192/124189388-4d97ae80-dac9-11eb-97d9-63bc3ad293be.png)

## More details

**Affected browsers/platforms:** 
Chrome version: 91.0.4472.124 

**First affected release:** 
Lateset C3 version: r251.2 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 93.0.4557.4
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4557.4 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 40 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 1030 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6089)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The problem is the JS API is not setting the font color, it's setting the IWorldInstance colorRgb property, i.e. overall object color tint. BBcode that changes the font color overrides the default font color, rather than tinting like the IWorldInstance colorRgb property. In the event system the Text object hides its color property in favor of the font color, but in the script interface the color property is still accessible as it is inherited from IWorldInstance, and there is no equivalent font color property, probably due to an oversight.

I've added a `fontColor` property for the ITextInstance interface for the next release, and if you change that it works identically to the 'Set font color' action.
