### ISSUE TITLE
Error: Exporting to Android 

### ISSUE THREAD

**Issue by Leomcs1982** [Scirra/Construct-3-bugs#4933]
## Problem description

Any project exported to Android results in build error

## Attach a .c3p

https://app.box.com/s/fjkqsk8ntyt6hrk8m259rv1b55r8wur2

## Steps to reproduce

Just export project to APK, signed or not, debug or release, whatever

## Observed result

Build error

## Expected result

APK build sucess

## More details
I tried exporting in Chrome, Firefox and Edge. I also tried exporting to two different computers running Windows 10

**Affected browsers/platforms:** Chrome/Firefox/Edge

**First affected release:** Construct 3: R254 Beta

## System details

<details><summary>View details</summary>

Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=~~/androidSDK (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
Using Android SDK: ~~/androidSDK
:wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class java.nio.file.FileSystems$DefaultFileSystemHolder

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 564ms
Command failed with exit code 1: ~~/gradlew cdvBuildDebug -b ~~/build.gradle

</details>

**Comment by ibiz3091** [comment]
I have this problem when exporting to android:
Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=~~/androidSDK (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
Using Android SDK: ~~/androidSDK
:wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app


FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class java.nio.file.FileSystems$DefaultFileSystemHolder

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 581ms
Command failed with exit code 1: ~~/gradlew cdvBuildRelease -b ~~/build.gradle

**Comment by AshleyScirra** [comment]
There was a temporary outage on the build service but it should be working again now. Apologies for the inconvenience.
