### ISSUE TITLE
(Z-elevation / Mesh deform) Sprite visibility inconsistent when transparencies overlap

### ISSUE THREAD

**Issue by SephBoss** [Scirra/Construct-3-bugs#4937]
## Problem description

My game is using sprite characters in a top-down perspective, which I have "standing up" at an angle using mesh deform to achieve the desired camera view.  Unfortunately, this has caused issues between the alpha of overlapping sprites, where parts of certain sprites seem to disappear behind the alpha sections of other sprites, depending on Z order.

I had previously (in R252) built a workaround to this by overlaying a copy of the player sprite on a 2d-rendered layer beneath my 3D objects, which solved the disappearing issues.  However, starting in R253 with the vanishing point fixes/changes I can no longer overlay 3D and 2D layers while altering the vanishing point due to the 2d layers appearing "squished" which no longer allows them to line up with 3d-rendered sprites.

## Attach a .c3p

[3D_Prop_Angle_Testing.zip](https://github.com/Scirra/Construct-3-bugs/files/6760845/3D_Prop_Angle_Testing.zip)

## Steps to reproduce

1. Add a mesh to a sprite
2. Raise the Z-elevation of the top two corners
3. Overlap two such sprites and see disappearing graphics

## Observed result

3d sprite graphics appear and disappear when transparent sections overlap

## Expected result

Alpha transparency of one sprite does not interfere with the visibility of other sprites

## More details

Tested in Firefox and Chrome on windows

First observed transparency bug in r251, with my workaround breaking from changes in r253

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.124
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
C3 release: r254 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 217 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6589)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is due to the way depth buffers work with transparency and is a known limitation. See the section on transparency in the tutorial [Using 3D in Construct](https://www.construct.net/en/tutorials/using-3d-construct-2746).
