### ISSUE TITLE
Whitelist Plugins (New)

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#4938]
Hi, please whitelist these plugins.

`sparsha-firebase-dynamiclinks@0.1.1`
`sparsha-firebase-messaging@0.1.1`

Thankyou

**Comment by SparshaDhar** [comment]
Hi, I just edited the comment at the top to add another new plugin. Thanks

**Comment by AshleyScirra** [comment]
`sparsha-firebase-messaging` appears to be a virtually identical fork of `cordova-plugin-firebase-messaging`, which was also requested in #4979. Is there any particular reason you've duplicated an existing cordova plugin? I would prefer not to have to review duplicated Cordova plugins, as it unnecessarily increases the review workload.

**Comment by AshleyScirra** [comment]
Also, is `sparsha-firebase-authentication` meaningfully different to `cordova-plugin-firebase-authentication`? I would also prefer to remove the custom fork if there's no reason for it.

**Comment by AshleyScirra** [comment]
I'd also add sparsha-firebase-messaging appears to delete the references to the original fork's repository and authorship, going so far as to replace the copyright in the MIT license, which I think probably violates the MIT license, as it requires that you preserve the copyright notice. I don't believe it allows for misrepresenting the author of the code. This may be reason enough to decline it, but I'll await your response first.

**Comment by SparshaDhar** [comment]
Hi, we had problems which needed to be solved. We discussed the problem here: #4609 . So I had to edit these plugins to make it compatible with Construct 3's Build Service. (Change: I needed to add some hooks to move files from one directory to another)
I can assure you that `cordova-plugin-firebase-authentication` doesn't work at all with Construct 3. And I am also sure that `cordova-plugin-firebase-messaging` wont work as well.

As suggested in an online article I found, I also tried to keep the original Author's MIT License in a separate file called "license_chemerisuk". This might be a wrong way, so I would be glad if you can suggest a better or safe way. Thanks.

**Comment by AshleyScirra** [comment]
I think it would be much better to submit a patch to the original Cordova plugin to fix any compatibility issues. (Although all the build service does is run Cordova CLI commands like a local build, so I'm not sure why there would be any significant compatibility differences.) This way you now have to maintain your own fork in parallel with the original plugin, and we have to do extra review work both for the initial review and all subsequent updates as you will presumably have to track all future updates to the original Cordova plugin and also submit separate review requests for those. It's also easy to imagine multiple other developers repeating this, making it even more time-consuming, unless they somehow figure out who has already forked plugins with the necessary compatibility changes. I really don't want to have to end up constantly reviewing patches to half a dozen almost-identical forks of a single Cordova plugin.

Still, for the time being, I've approved the requested plugins, but note for the reasons above I will be strict about reviewing any Cordova plugins that appear to be forks of other ones.

**Comment by SparshaDhar** [comment]
Thanks. I see.. There are some external user files that are needed by these plugins. So I will try to make a new plugin instead that will do the job common to all these plugins. And so we wont have to make forks of each of these plugins again and again.
