### ISSUE TITLE
Stuck on splash screen then goes blank

### ISSUE THREAD

**Issue by vundurty** [Scirra/Construct-3-bugs#4939]
## Problem description
The android build is not working. It displays the splash screen for around 30secs and displays the black screen. When I check the Chrome://inspect, it get these errors

1. Failed to load resource: net::ERR_FILE_NOT_FOUND
2. Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.

This issue is there even in the C3 demo game. I have attached your Kiwi game.

## Attach a .c3p
[Kiwi Demo.zip](https://github.com/Scirra/Construct-3-bugs/files/6769742/Kiwi.Demo.zip)

## Steps to reproduce

1. Export as Android debug
2. Install the APK
3. You will see the splash and black screen

## Observed result

It displays the splash screen for around 30secs and display black screen.
![2021-07-05 (4)](https://user-images.githubusercontent.com/22640025/124595747-07eb3500-de7f-11eb-8593-7e2f4cfd5866.png)

I have recorded video
[Test issue.zip](https://github.com/Scirra/Construct-3-bugs/files/6769803/Test.issue.zip)

## Expected result

It should take me to the game.

## More details

No issues on the browser only the Android version has the issue.

**Affected browsers/platforms:** 
Android build

r254 beta

**First affected release:** 
Works fine in r251.2 but issue persists in r254 beta

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.124
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
C3 release: r254 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 196 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0, D3D11-10.18.15.4278)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I built a debug APK and it ran just fine on a Pixel 3.

Are you using an old device or emulator with out-of-date software? That's the only thing I can think this might be.

**Comment by vundurty** [comment]
Thanks alot for the quick response.

I'm using OnePlus 5 with Android version 9. I have tested it only my phone, I didn't try it on emulator. Anything I need to do like checking any phone settings or C3 setting or anything else to make it run?

**Comment by AshleyScirra** [comment]
The error message looked suspiciously familiar and I figured out it's related to a previous issue #4396, where some specific Android devices needed extra hacks to get JavaScript Modules to work. These hacks needed updating to support worker mode which was enabled by default for Android apps in r252 and only affected the same specific devices. Luckily I have a Samsung Galaxy S8 which does reproduce the issue, and I was able to test on that to get the right code in place to get it working again for those specific kinds of devices. So it should be working in the next beta - but given the device-specific nature of the issue I'm marking this issue to check again when the next release is out so we can verify it works again on your device too.

**Comment by vundurty** [comment]
Thank you for looking into this and the context. I will check in the next beta release and let you know.

**Comment by AshleyScirra** [comment]
@vundurty - I think this should be working in r256 now. Can you confirm?

**Comment by vundurty** [comment]
It works perfect. Thanks alot for fixing it. :D

**Comment by AshleyScirra** [comment]
Great, thanks for confirming.
