### ISSUE TITLE
Wrong tooltip on details of Preview-button

### ISSUE THREAD

**Issue by UeliSo** [Scirra/Construct-3-bugs#494]
## Problem description
![c3 tootlip error](https://user-images.githubusercontent.com/12688267/27074433-7d9053f4-4ffd-11e7-88c3-1ef29fdfe36d.png)

*Enter a concise description of your problem here*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, looks like I copy pasted that too fast. Fixed for r38.
