### ISSUE TITLE
Advanced Minify Mode HTML5 export bug

### ISSUE THREAD

**Issue by dabontv** [Scirra/Construct-3-bugs#4942]
## Problem description

When exporting a project in advanced minify mode it is giving me an export error "C3Debugger is undeclared"

## Attach a .c3p

You can use a blank .c3p files for this, or any file really

## Steps to reproduce

1. Export to HMTL5
2. Check Deduplicate Images and Recompress Images
3. Use Advanced minify mode

## Observed result

Will alert this error:

```
/str/c3runtime.js:2778:138: ERROR - [JSC_UNDEFINED_VARIABLE] variable C3Debugger is undeclared
  2778| 
```

## Expected result

Should export without error

## More details

**Affected browsers/platforms:** 

Using Firefox on MacOS

**First affected release:** r255

**Comment by AshleyScirra** [comment]
Thanks for the report, should be fixed in the next beta.
