### ISSUE TITLE
Crash: while timeline animation is playing and we close timeline bar

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4943]
## Problem description
when timeline animation is playing and we did not stop it and just close the timeline bar then it crash.

## Attach a .c3p
[timeline.zip](https://github.com/Scirra/Construct-3-bugs/files/6788663/timeline.zip)

## Steps to reproduce

1. open attached file
2. press space to play timeline animation.
3. close the timeline bar 

## Observed result

Crash

## Expected result

Not to crash

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'querySelector' of null @ TypeError: Cannot read property 'querySelector' of null at d.lBa (https://editor.construct.net/r255/components/bars/timelineBar/timelineBar.js:34:58) at d.BLa (https://editor.construct.net/r255/components/bars/timelineBar/timelineBar.js:34:133) at d.Yj (https://editor.construct.net/r255/components/bars/timelineBar/timelineBar.js:39:397) at d.z0 (https://editor.construct.net/r255/components/bars/timelineBar/timelineBar.js:35:209) at d.A (https://editor.construct.net/r255/components/bars/timelineBar/timelineBar.js:32:348) at Array.msa (https://editor.construct.net/r255/main.js:2223:226) at Qf.g.Za.ska.dispatchEvent (https://editor.construct.net/r255/main.js:1037:28) at Qf.g.Za.ska.Ze (https://editor.construct.net/r255/main.js:1217:159) at Qf.g.Za.ska.Ze (https://editor.construct.net/r255/main.js:1222:118) at Qf.g.Za.ska.Ze (https://editor.construct.net/r255/main.js:1239:332)
Stack: TypeError: Cannot read property 'querySelector' of null at d.lBa (https://editor.construct.net/r255/components/bars/timelineBar/timelineBar.js:34:58) at d.BLa (https://editor.construct.net/r255/components/bars/timelineBar/timelineBar.js:34:133) at d.Yj (https://editor.construct.net/r255/components/bars/timelineBar/timelineBar.js:39:397) at d.z0 (https://editor.construct.net/r255/components/bars/timelineBar/timelineBar.js:35:209) at d.A (https://editor.construct.net/r255/components/bars/timelineBar/timelineBar.js:32:348) at Array.msa (https://editor.construct.net/r255/main.js:2223:226) at Qf.g.Za.ska.dispatchEvent (https://editor.construct.net/r255/main.js:1037:28) at Qf.g.Za.ska.Ze (https://editor.construct.net/r255/main.js:1217:159) at Qf.g.Za.ska.Ze (https://editor.construct.net/r255/main.js:1222:118) at Qf.g.Za.ska.Ze (https://editor.construct.net/r255/main.js:1239:332)
Construct 3 version: r255
URL: https://editor.construct.net/r255/
Date: Fri Jul 09 2021 09:41:35 GMT+0530 (India Standard Time)
Uptime: 1209 s

Platform information
Browser: Chrome
Browser version: 91.0.4472.124
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
C3 release: r255 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7111)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
