### ISSUE TITLE
Multiplayer: Peers can't rejoin rooms

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4944]
## Problem description

Once a peer disconnects from a multiplayer room, they cannot rejoin. Disconnecting from the signal server doesn't help either; it takes a browser window refresh to be able to rejoin.

## Attach a .c3p

User @wilsonapa had created this example in 2018, and it's a great demonstration of the problem.

https://drive.google.com/file/d/1MgUkauSRhp-Z8xyKOkldoVUniOHYp2pE/view?usp=sharing

## Steps to reproduce

1. Open the attached project. 
2. Start remote preview
3. Paste the preview link into an incognito/private window.
4. Enter a unique user name and click connect. (You will join as a host.)
5. Paste the preview link into a second incognito/private window.
6. In this second browser window, enter a unique user name and click connect. (You will join as a peer.)
7. Still in this second "peer" browser window, click disconnect.
8. Lastly, still in the peer window, click connect.

## Observed result

The peer window will not be able to join the room on the second attempt. 

## Expected result

The peer window should join the room, as it did on the first attempt.

## More details

Just a theory, but does disconnecting from the server also log the user out of it ? While there are actions to both "join room" and "leave room", to both "connect to server" and "disconnect from server", there is only "log in to server" – no "log out". 

EDIT: Interestingly, when the host kicks the peer first (and then the peer runs "leave room" and "disconnect" actions), they can rejoin the room again.

**Affected browsers/platforms:** Chrome 91; Safari 14.11

**First affected release:** Problem in 255, but it seems to have been a problem since 2018?

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is a common mistake. Event 3 disconnects from both the room and the signalling server simultaneously. Leaving a room is asynchronous and takes a moment to complete, but if you disconnect from the signalling server before it completes, the process of leaving a room never completes and thus you are left in the room. Make sure leaving the room has completed before disconnecting from the signalling server (e.g. using 'On left room' trigger).

**Comment by brushfe** [comment]
Ah, ok! My fault, I didn't understand that. Thanks very much!
