### ISSUE TITLE
Whitelist plugins (Essential) (Breaking)

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4946]
Hi, would you please update the following plugins to `0.8.0`. 

Since [Bintray's sunsetting](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), a lot of SDKs that rely on it to fetch dependencies now fails, that includes the [entire IronSource Android SDK](https://developers.ironsrc.com/ironsource-mobile/android/ironsource-artifacts-github/).
I hope you could help us out in resolving this issue by updating the current ones that are whitelisted.

```
chadori-mobile-ironsource
chadori-mobile-ironsource-debug
chadori-mobile-ironsource-adcolony
chadori-mobile-ironsource-admob
chadori-mobile-ironsource-amazon
chadori-mobile-ironsource-applovin
chadori-mobile-ironsource-chartboost
chadori-mobile-ironsource-facebook
chadori-mobile-ironsource-fyber
chadori-mobile-ironsource-hyprmx
chadori-mobile-ironsource-inmobi
chadori-mobile-ironsource-maio
chadori-mobile-ironsource-pangle
chadori-mobile-ironsource-pangle-cn
chadori-mobile-ironsource-tapjoy
chadori-mobile-ironsource-unityads
chadori-mobile-ironsource-vungle
chadori-mobile-ironsource-smaato
chadori-mobile-ironsource-snap
```

Thank you.

**Comment by AshleyScirra** [comment]
Updated build service to allow versions @0.8.0.
