### ISSUE TITLE
Can't undo creating a group

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4948]
## Problem description

Creating a group in an event sheet can't be undone with cmd/ctrl-Z or the undo button. 

## Attach a .c3p

(A new project is the cleanest example.)

## Steps to reproduce

1. Open a new project.
2. In the event sheet, add an event (any condition will do).
3. Press G to add a group.
4. Confirm the group details in the pop-up dialog.
5. Press cmd/ctrl-Z or press the undo button at the top of the event sheet.

## Observed result

The event is removed, not the group — despite adding the group being the most recent action.

## Expected result

The group should be removed from the event sheet.

## More details

**Affected browsers/platforms:** Chrome 91

**First affected release:** 255

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, well spotted. It should be fixed in the next beta.
