### ISSUE TITLE
Cropping with no padding

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4949]
The tooltip for the Crop feature in the Animation Editor reads "Hold control for no padding", but holding control while pressing Crop does nothing to the image.

(Any project should show this)

## Steps to reproduce

1. Open a new project.
2. Create a sprite object.
3. Open the sprite object in the Animation Editor.
4. Draw a small rectangle in the centre of the canvas (with enough transparent space around it to require cropping)
5. Hold the control key and click crop.

## Observed result

Nothing happens.

## Expected result

The rectangle is cropped to the very edge of the shape, with no padding.

## More details
Holding other keys (shift, option, etc) allow the crop to happen, but with padding.

**Affected browsers/platforms:** Chrome 91

**First affected release:** 255

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Are you trying to crop using the keyboard shortcut **ALT + C**? That is the only case I found in which pressing **CTRL** just cropped the image normally with the 1 pixel padding.

**Comment by brushfe** [comment]
Hello! I was using the Crop button at the top the Animation Editor, I did't realize there was a keyboard shortcut. Holding control and clicking Crop doesn't do anything on my end; the image doesn't change or crop when that key is held down.

(I'm on a Mac, so I have Option instead of Alt, if that changes anything)

**Comment by DiegoScirra** [comment]
I see it now, just tried it out on a MAC here and indeed clicking on the button while pressing **CTRL** does nothing.

It does work if you try it with the keyboard shortcuts alone though. So that would be **OPTION + C + CTRL**.

**Comment by brushfe** [comment]
Ok thanks! I'll use that in the meantime. I appreciate your help!

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.
