### ISSUE TITLE
Missing info about Iain on website team page

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#495]
Visit https://www.construct.net/team - the section for Iain is empty.

**Comment by Yazir** [comment]
Can confirm, happens at my end too.

**Comment by KFII** [comment]
I have the same problem :( maybe because the name's "Shorter" (which mission is to shorten things, so much it became invisible?)

**Comment by shortercode** [comment]
I'm like a ghost...

**Comment by JeFawk** [comment]
Empty as well

https://www.construct.net/ro/make-games/education

**Comment by TomGullen** [comment]
@shortercode if you email me a short bio can add this!
