### ISSUE TITLE
Improper size of icon in Android Export

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#4950]
## Problem description

When APK file is generated, wrong size of icon is displayed

## Attach a .c3p

No need of that. Use any project and export it. Run the APK in your mobile
## Steps to reproduce

Explained above.

## Observed result

This is the opening screen of the app. Notice that icon is VERY small
![WhatsApp Image 2021-07-13 at 3 32 31 AM (3)](https://user-images.githubusercontent.com/46170077/125361802-76525a80-e38b-11eb-986a-51802634b48d.jpeg)

This is the screen where icon and loading bar appears. Here icon size looks fine
![WhatsApp Image 2021-07-13 at 3 32 31 AM (2)](https://user-images.githubusercontent.com/46170077/125361878-95e98300-e38b-11eb-80d5-0d04157b5b3f.jpeg)

## Expected result

Size of icon at starting screen must be reasonable. Literally looks like a dot in middle of screen

## More details
And, since my game is quite huge so it takes few seconds at initial white screen hence it is a issue for me

Construct 3 latest beta. Android 10.

**Comment by layilpaht** [comment]
I don't remember exactly what I did last year (this issue is year long when white screen concept was introduced):- something like I changed the size of icon in icon folder and result were as follows
![WhatsApp Image 2021-07-13 at 3 32 31 AM (1)](https://user-images.githubusercontent.com/46170077/125362710-fa591200-e38c-11eb-8b0b-ef63fe428533.jpeg)
This is the white screen. Now icon looks fine
![WhatsApp Image 2021-07-13 at 3 32 31 AM](https://user-images.githubusercontent.com/46170077/125362773-15c41d00-e38d-11eb-8ed9-b1e42fca4451.jpeg)
But unfortunately loading icon gets TOO huge

(Sorry for huge size of images. Drag the images and open it in other tab)

**Comment by AshleyScirra** [comment]
I would guess you just need to add a splash image as documented in [Icons & splash](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/icons-splash).

No project provided so cannot investigate further and closing.
