### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by Leomcs1982** [Scirra/Construct-3-bugs#4953]
## Problem description
Some people are having trouble exporting projects larger than 10mb to APK or XCode file. When exporting blank projects or smaller than 10mb it works fine.

I've tried it many times, with many different projects, tried in various ways, tried all night, but if the project has more than 10mb it doesn't work.

## Attach a .c3p

This is a simple sample project, with 48mb and cannot be exported, please try!
https://app.box.com/s/031seyu3o4kumzzewj9q55oay9y3kx0t

This project is only 4.9mb and can be exported without any problems, please try!
https://app.box.com/s/vjr9exibkk5n8aean6l7sfswzpo14oh3

## Steps to reproduce

1 - Open the project
2 - Export an APK file

## Observed result

Build failed

## Expected result

Functional apk file

## More details
My project was exported correctly last week, when I needed to make a small modification this week, I couldn't export to apk again.

Construct 3 version: R255 and R256

Browsers: Chrome, Firefox and Edge.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.124
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
C3 release: r256 (beta)
Language setting: pt-BR

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 7 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon HD 5450 Direct3D11 vs_5_0 ps_5_0, D3D11-8.17.10.1433)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Huh, it looks like the uploads ended up going really slow. I don't know why that happens... I just rebooted it and it seems to be better now, can you confirm?

**Comment by Leomcs1982** [comment]
Funcionando perfeitamente, obrigado! :)
