### ISSUE TITLE
await import() error in Advanced Minify

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#4956]
## Problem description

Hi, as Ashley suggested in this [forum topic](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/using-importscripts-worker-161429), I am using `await import(script)` in my plugin.
But during Advanced Minify Export, I get an error. (error is provided below)

This same issue has been recently closed in Google Closure Compiler on May 18 2021. https://github.com/google/closure-compiler/issues/2770#issuecomment-834744931

## Attach a .c3p
To reproduce this error in a c3p, I couldnt share my plugin, so I made a eventsheet scripting instead which produces the same error.
[import_c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6821468/import_error.zip)

## Steps to reproduce

1. Export > HTML5
2. Select Advanced Minify

## Observed result

Error:
```
ERROR - [JSC_FEATURES_NOT_SUPPORTED_BY_PASS] Attempted to run pass "markUntranspilableFeaturesAsRemoved" on input with features it does not support. Running pass anyway.
Unsupported features: [Dynamic module import]

1 error(s), 0 warning(s)
```

## Expected result

Export with no error

## More details

**Affected browsers/platforms:** Microsoft Edge

**First affected release:** r256 and less

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 91.0.864.67
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.67
C3 release: r256 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 180 gb
Storage usage (approx): 71 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7111)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This and a few other recent JS features are not currently supported by Closure Compiler. We occasionally update the build of Closure Compiler in Construct, but the process is quite long and complicated. Next time we do it, it should support the latest tier of JS features.
