### ISSUE TITLE
Canvas paste bugs with parallax

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4958]
## Problem description
R248 changes something for DrawingCanvas, when one canvas pasts into another, while other canvas has different layer parallax. Paste will have offset. 
It will only work if both layers have same parallax.

## Attach a .c3p
[HoHo.zip](https://github.com/Scirra/Construct-3-bugs/files/6823452/HoHo.zip)

## Steps to reproduce

1.Open example in r248 or latest release
2.Preview, wait 1 sec, drag "X" around outside default viewport area
3.Close preview, change layer 0 parallax to 100%,100%. preview and test same thing again.

## Observed result
Release r248 changes something which will wreck pasting when layer parallax is different.

PS: Testing in latest release also might have some other major issue, because bugged behavior in r248 and latest release r256 are different. So there could be most likely more bugs then one.

## Expected result
Pasting canvas to another without issues. Something that works in r247, should work in r248 and in latest release r256.

## More details

Testing example project and setting both layers to same parallax, then in r248 everything seems OK. While latest release R256, canvas will erase or reset drawing constantly. So there are some other issue or issues, not sure what.

**Affected browsers/platforms:** 

**First affected release:** 
R248
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.124
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
C3 release: r248 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.3 gb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's pretty confusing to tell what's going on here, but I think I figured it out and it should be working in the next beta.

**Comment by SnipG** [comment]
Nice, i did checking and testing, to see what could be cause of canvas refresh. If it originates from parallax.
Did found cause and fix and workaround. So it does not come from parallax.

Let's hope parallax issue will be fixed, so canvas turns usable again.
