### ISSUE TITLE
Viewport Change is not supported by canvas

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4959]
## Problem description
Case user changes viewport size, then canvas paste will bug.
Overall, is viewport "canvas" change even supported?

## Attach a .c3p
[ViewportChange_NotSupported.zip](https://github.com/Scirra/Construct-3-bugs/files/6831864/ViewportChange_NotSupported.zip)

## Steps to reproduce

1.Preview in latest release
2.Drag sprite around(top object)
3.Draw other canvas around(bottom object)

## Observed result
If viewport canvas changes, then it's not updated for drawingCanvas object, but it's supported other canvas.
Drawing is morphed, like canvas take account old viewport size before sprite object is pasted.

If viewport is changed on start of layout.
*Canvas looks sprite object old viewport size. Squashed that into new size and ruins pasting.

## Expected result
Work and support

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.124
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
C3 release: r256 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.3 gb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SnipG** [comment]
It seems if sprite is pasted first and canvas later, then everything is correct. But if canvas is pasted first instead and sprite after that, then sprite paste is bugged.
From this, i don't know if it's limitation or a bug

**Comment by AshleyScirra** [comment]
This kind of report is pretty confusing because the project is so abstract it's hard to make sense of what it's meant to be doing vs. what appears on screen. It would be clearer if you can clearly explain the expected result as per the bug report guidelines, perhaps with screenshots, so I can compare what appears on-screen with what is supposed to appear.

Also if I simplify the repro to just change the canvas size and then paste something, it works correctly: 
[issue4959.zip](https://github.com/Scirra/Construct-3-bugs/files/6840373/issue4959.zip)
So perhaps this is not related to the viewport change at all? It's hard to tell from this. Can you make a clearer demonstration and explain in more detail what you think is going wrong?

**Comment by SnipG** [comment]
You simplified it to much and removed the bug.

I think what's going on. When 'Canvas' is pasted into canvas, it has own immediate surface it uses(or origin size). Sprite pasted into canvas has same thing. **ie, object has default variables which descripte the original surface size it comes from.**
Because default surface is changed, and 2 different objects are pasted: canvas and sprite. One of them remembers old viewport size and uses that. So when different quad is squashed into another quad, the paste result will be offset.

Here a video. Changed example a bit and made it simpler. It was so abstract, because when viewport canvas is changed, runtime does not handle it well. User has to apply workarounds.
[Case_4959.zip](https://github.com/Scirra/Construct-3-bugs/files/6840697/Case_4959.zip)

https://user-images.githubusercontent.com/28864889/126158828-889d7e70-e668-464d-8830-031afcf2f211.mov


Just flipping 2 actions change pasting.
![Flipp](https://user-images.githubusercontent.com/28864889/126159130-e60308d1-92ea-4cf8-8f2f-121523072182.jpg)

**Comment by SnipG** [comment]
Indeed, i removed canvas change and outcome is still there, just less visible. So it could not be related to viewport change

**Comment by AshleyScirra** [comment]
Adjusted repro to add color clears and move DrawingCanvas2 out the way to make the visualisation clearer: 
[issue4959-alt.zip](https://github.com/Scirra/Construct-3-bugs/files/6946077/issue4959-alt.zip)

**Comment by AshleyScirra** [comment]
The case of pasting DrawingCanvas followed by Sprite should be fixed for the next beta.
