### ISSUE TITLE
JSON-editor (array, dictionary). Crash after "Free cells"+"Tab"

### ISSUE THREAD

**Issue by ReviveR200** [Scirra/Construct-3-bugs#4960]
## Problem description
JSON-editor (array, dictionary). You enter values into cells + "Ctrl+z" and "Tab" = crash. Or create new JSON-file, open and click "Tab"

## Attach a .c3p
[New project (1).zip](https://github.com/Scirra/Construct-3-bugs/files/6833441/New.project.1.zip)

## Steps to reproduce
1. Create any JSON-file (I have tried array and dictionary) 
![Снимок](https://user-images.githubusercontent.com/62239715/126009908-90e35350-347d-4e81-a3bc-e2b1ba8395ad.PNG)

2. Open editor 
![Снимок](https://user-images.githubusercontent.com/62239715/126009982-1600b69c-d287-4314-b58f-bcd72c5ba3f3.PNG)

3. Enter any character and press Esc ![image](https://user-images.githubusercontent.com/62239715/126010069-b013347e-c3b4-4cfe-a231-097a8d5ec0f1.png)

4. Ctrl+z 
![image](https://user-images.githubusercontent.com/62239715/126010171-f04e46b9-d4d8-40ff-9c8c-4dd04b3b5e58.png)

5. Tab ![image](https://user-images.githubusercontent.com/62239715/126010185-2b56cf39-16fe-4e9d-ac88-f72eda61639c.png)

6. Or click "Tab" after open JSON-file 
![image](https://user-images.githubusercontent.com/62239715/126010390-b87214ad-ead2-4b05-8623-7d06171ecf21.png)

## Observed result
Construct 3 doesn't know which field to switch to when click "Tab"

**Affected browsers/platforms:** Chrome

**First affected release:** r200 and r256

## System details
[error report information.txt](https://github.com/Scirra/Construct-3-bugs/files/6833488/error.report.information.txt)

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
