### ISSUE TITLE
Array labels not transposed or restored on undo

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4961]
## Problem description

Using the "Transpose array rows/columns" action on a project file array does not transpose the renamed rows/columns. Similarly, after undoing the "Transpose array row/column" action, the renamed rows/columns are not restored.

## Attach a .c3p

https://drive.google.com/file/d/1LbGdTG4VLpa1Khsc93hN7D7nEmsDU-Sl/view?usp=sharing

## Steps to reproduce

1. Open the attached project. 
2. Open the project file "New Array.json" 
3. (Note the renamed row/columns)
4. Right-click any row or column and select "Transpose array rows/columns"
5. Press control/command+z to undo. 

## Observed result

After step 4, the renamed rows/columns are not transposed with the data. 
After step 5, the renamed rows/columns are not restored to their pre-transposed state.

## Expected result

Either the renamed rows/columns are transposed with their custom names, or they are restored on undo, or both.  

## More details

**Affected browsers/platforms:** Chrome 91

**First affected release:** r256

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in next beta.
