### ISSUE TITLE
Text won't scale with its parent object when BBcode enabled

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4963]
## Problem description
text is added as child object and bbcode is enabled and If we do scale the parent object then text font size doesn't change

## Attach a .c3p
[text in hierarchy issue.zip](https://github.com/Scirra/Construct-3-bugs/files/6835990/text.in.hierarchy.issue.zip)

## Steps to reproduce

1. open attached file
2. preview file
3. click the button and see text

## Observed result
Text doesn't scaled while its parent object is scaling. 

## Expected result
scale or change font size accordingly 

## More details

**Affected browsers/platforms:** 
 Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report. It does actually normally scale with the parent, but in this case you've added [size] BBcode tags which override the size. However it seems reasonable that these ought to scale with the parent as well. I've fixed that for the next beta.
