### ISSUE TITLE
Fade Audio Playback Rate Scale

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4964]
## Problem description

The Fade feature of the Audio plug does not scale with the set Playback Rate feature.
## Attach a .c3p
https://www.dropbox.com/s/ylew2en5vieasph/fadeaudio.c3p?dl=1

## Steps to reproduce

1. Note the events in the project
2.Run the project
3.Click the button

## Observed result

The audio starts to fade, stops, and then starts when the fade would have ended.
## Expected result

The fade should have scaled to what the tags playback rate was.
## More details

The on tag ended condition is being triggered because the audio tag has ended.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

10w Chrome 
Current stable C3
<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This doesn't look like a bug to me. The confusion is the fade time runs in the game time clock, not the playback clock. I don't think it's clear that the fade time ought to be using the playback clock anyway - it seems to me if you have a slow-motion sound with a playback rate of say 0.25, and you say to fade that out over 10 seconds, then it should take 10 seconds, not 40 seconds. (Besides managing the fade out with the playback clock would be incredibly complicated if the playback rate was changing.)
