### ISSUE TITLE
Scroll to disables first canvas paste

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4965]
## Problem description
Case that needs a check.

During Start of Layout, when user does a 'scroll to'. First paste won't work. 
Ideally it should paste object, and because of this it needs a check why it fails pasting. 
Is paste not working in same frame with 'scroll to'?

## Attach a .c3p
[Download_a_copy.zip](https://github.com/Scirra/Construct-3-bugs/files/6836735/Download_a_copy.zip)

## Steps to reproduce

1.Preview, see sprite has been pasted. Close preview
2.Select eventsheet, enable Scroll to. Preview with debug(see both object are still there, but canvas failed paste)
3.

## Observed result
Canvas failed to paste with 'scroll to'. 

## Expected result
Needs investigation why it fails pasting. Is it just limitation or a bug.

 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.124
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
C3 release: r256 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.3 gb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SnipG** [comment]
Did futher testing, it seems first scroll to offsets/glitz paste. So pasting still occures.
![asas](https://user-images.githubusercontent.com/28864889/126078216-421883d6-ef60-409c-badd-e75d09232612.jpg)

**Comment by AshleyScirra** [comment]
Clearer repro: [issue4965.zip](https://github.com/Scirra/Construct-3-bugs/files/6840400/issue4965.zip)

**Comment by ibiz3091** [comment]
I also had problems in r257 with inserting shadowlight on the canvas when changing the Layout angle, the places where the shadow is drawn began to shake, it feels like the canvas draws the shadow 1 time in 20-30 ticks
[Video.zip](https://github.com/Scirra/Construct-3-bugs/files/6843823/Video.zip)

**Comment by SnipG** [comment]
You need to make your own issue report for that. Becase that's different case.
With  Construct you got only 1 way, report the issue or wait for someone else to do so. Which could take years. If you don't have time to report them, but got time to wait for someone else, then it's easier not to use Canvas at all. Clearly Scirra does not have funds to find and fix the issues themselfs as stated before.

Canvas got massive amount of problems(which only get fixed if someone points them out). If you use canvas in advanced case you most likely will encounter much more then 1 issue, i bet easily 5+ in full game. So it could take forever for someone else to use it in such case as you.

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
