### ISSUE TITLE
Unlimited ticks: time and wallclock time

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4966]
## Problem description
With unlimited ticks, time and wallclocktime are 0.
If user has some logic, which has one of them, then it won't work.

Is it intended or not?

## Steps to reproduce

1.Create new, select unlimited ticks
2.Preview with debug, look time and wallclock time
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks for spotting, it turns out the unlimited framerate modes were accidentally broken in r253. It should be fixed in the next beta.
