### ISSUE TITLE
Objects with HSL Effect doesn't fade in preview

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#4969]
**Attach a .c3p**
[FadeEffect.zip](https://github.com/Scirra/Construct-3-bugs/files/6848670/FadeEffect.zip)

**Steps to reproduce**
Open project. Click Bee. Tick the Preview button in the Fade behaviour.

Try again with the bee's opacity at anything apart from 100%

**Observed result**
In the preview in the behaviour, the bee will highlight, then unhighlight after 1 second.

However, if you set the opacity to something other than 100% it will fade again.

**Additional Details**
In my project, it's a lot worse, as it doesn't even appear in runtime previews or debugs. As soon as I apply the effect, whenever the object is less than 100% in the layout preview, it will fade away, but during runtime, it will only be shown if 100%. Therefore, what I'll see is a quick flash of the object for a single frame.

I'm unable to replicate this in my new example, but the other issue remains.

However, if I export the project, it appears to work as expected.

**Comment by AshleyScirra** [comment]
I fixed an editor-specific issue for the next beta. However note that any issue in preview is probably a separate issue and will need to be filed separately with another report following all the guidelines.
