### ISSUE TITLE
Scrollwheel in popout eventsheet view throws errors

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#497]
## Problem description

When in a popup view of the eventsheet is scrolled it throws errors in the console, seems to be caused by changes to type checking code and different origins. Also note warnings about HTMLimports?

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open a new project
2. Undock the event sheet
3. "Popup" the event sheet
4. Scroll 

## Observed result

Errors appear in console, app does not crash

## Expected result

No errors

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>

Main branch HEAD revision.

</details>

**Comment by AshleyScirra** [comment]
Fixed some type checks that didn't work in popups. Will look in to the imports warning separately.
