### ISSUE TITLE
On typewriter finished not showing as a trigger 

### ISSUE THREAD

**Issue by TMsimonW** [Scirra/Construct-3-bugs#4970]
## Problem description

On Typewriter finished missing its green on trigger arrow in the event sheet and within Text UI

## Steps to reproduce

Create a blank project
add a text object within the project bar on the right
in the event sheet travel to the text plugin and search for "on typewriter finished"

## Observed result

No green trigger arrow next to the event

## Expected result

a green trigger arrow next to this event

## More details
checked on chrome os

**Affected browsers/platforms:**
Chrome (from what i have tried)

First noticed in 257

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
