### ISSUE TITLE
AJAX stopped working on r257 beta

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4971]
## Problem description

AJAX stopped working on r257 beta.

## Event sheet

![Project](https://user-images.githubusercontent.com/31282960/126405887-703872fa-175b-4ff1-bc93-38054614b29a.png)

## Attach a .c3p

[AJAX break.zip](https://github.com/Scirra/Construct-3-bugs/files/6851661/AJAX.break.zip)

## Steps to reproduce

1. Export as .debug apk
2. Open [Chrome Developer Tools through USB Debugging](https://www.construct.net/en/forum/construct-3/general-discussion-7/debug-apk-135635).
3. View the console log.

## Observed result

![AJAX](https://user-images.githubusercontent.com/31282960/126405842-7e04501b-8e7d-4306-850a-3585b4cf72b5.png)

## References
- https://www.construct.net/en/forum/construct-3/general-discussion-7/load-json-files-debug-apk-162108

**Comment by AshleyScirra** [comment]
Thanks for the report, looks like it's related to the new worker mode support on Android. Should be fixed in the next beta.
