### ISSUE TITLE
Text/Scale Problem on iOS

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#4978]
## Problem description

I have a weird problem on iOS (Browser) with the text object from construct 3. See here what i mean:
( on the video: is the text object on the right side in landscape mode )
[Example Video](https://photos.app.goo.gl/hN3CE6KtwbbLoeuq5)

When i scale up or down, the font size and position is wrong. I don't have a workaround for that.. :(

## Attach a .c3p

[bugFontSizeIOS.zip](https://github.com/Scirra/Construct-3-bugs/files/6862335/bugFontSizeIOS.zip)

## Steps to reproduce

1. Open the example file
2. Run it on iOS Browser (iPad or iPhone has the same problem)
3. Scale the screen down or scale up and see what is the problem with the text object.

## Observed result

Scaling and position is wrong

## Expected result

Scaling and position is correct.

## More details

(See the video above)

**Affected browsers/platforms:** 

iOS - iPad - Safari 
iOS - iPhone - Safari

on iOS - Chrome the same problem... on Android it works correctly..

r257

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.164
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
C3 release: r257 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 198 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5751)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid this appears to be a Safari bug. It looks like it was already filed... back in 2010! https://bugs.webkit.org/show_bug.cgi?id=46987

It looks like Safari doesn't draw text with a fractional size, so if you smoothly scale the size it will jump around. I don't think there is anything that can be done until Apple fix it.

**Comment by masscube** [comment]
Hm, sounds really bad. Is there any chance for a workaround?
I think display custom text is essential/urgent for any "webapps/games"..

**Comment by AshleyScirra** [comment]
I don't think there's any workaround, the problem is in how Safari is drawing text. It affects the C3 editor in Safari too. Maybe you could design the project to avoid it, e.g. by using fixed zoom levels.
