### ISSUE TITLE
Whitelist Plugins (Update Routine)

### ISSUE THREAD

**Issue by EMI-INDO** [Scirra/Construct-3-bugs#4979]
Removed the `cordova-support-google-services` dependency that caused c3 build failure

### Update:

`cordova-plugin-firebase-analytics@6.0.1`
`cordova-plugin-firebase-authentication@5.0.0`
`cordova-plugin-firebase-messaging@6.0.0`

**Thank you friend**

**Comment by AshleyScirra** [comment]
Added to build service.
