### ISSUE TITLE
Improvement: add match word to search

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#498]
## Problem description

I love the new search feature, however I have a lot of results when looking for something because a lot of sprites have that word in it.

Any possibility of adding along the **Match case** a **Match word** ?

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
The scrollbar of the search is huge, there are a lot of entries in it :/

![image](https://user-images.githubusercontent.com/7268697/27093364-0a0400e4-506f-11e7-897e-dcc1dd03fb38.png)

* Chrome: ye

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
What are you looking for? Are you sure it's not better to use 'Find all references' here?

**Comment by JeFawk** [comment]
I was looking for Bone. I have a lot of sprites with Bone in the word, as well as a sprite named only Bone.
I didn't remember on which of the 56 event sheets I used the simple Bone named sprite and was hoping the search can help me, but without a match word I got everything that had Bone in it :(

**Comment by AshleyScirra** [comment]
No, I mean what kind of thing are you looking for? What is "Bone"? Is that a Sprite? If so you should definitely use 'Find all references', this is exactly the problem it exists to solve.

**Comment by JeFawk** [comment]
You're right, find all references works great in this case, thanks! (to be honest i forgot about that feature)
