### ISSUE TITLE
If the image is too small, 'Guess the polygon shape' will Inaccurate

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4980]
## Problem description

If the image is too small, Guess the polygon shape will not work.

<img width="640" alt="Snipaste_2021-07-23_15-24-23" src="https://user-images.githubusercontent.com/45864744/126751561-383c4d50-d520-4bd5-9fb8-ac045bb02d4c.png">

## Attach a .c3p

It is just a rectangle that is simply filled, nothing special. It’s just a small size, just use it to PlayerMask / PlayerCollision for collision.  

<img src="https://user-images.githubusercontent.com/45864744/126752529-512a9365-cdfe-45c1-9b1c-68a4aa2bae25.png">

It doesn’t matter how many pixels are filled, because there will be problems.Here I made a sample project. 
[Guess_the_polygon_shape.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6867340/Guess_the_polygon_shape.c3p.zip)

## Steps to reproduce

1. create a sprite object,  resize image canvas size to 32 x 32
2. draw a rectangle. e.g，15 x 7
3. Guess the polygon shape in the context menu

Note that if it is drawn on the edge of the canvas or too small, it will not be able to guess. If it is drawn in the middle of the canvas, its guess is not accurate.

## Observed result
  
If I stick it to the edge of the canvas
<img width="300" src="https://user-images.githubusercontent.com/45864744/126751769-00b2eae4-fc62-4efc-b88a-3e331e5368b6.png">
  
If I move this up a few pixels, make it no longer sticks to the canvas edge.  
<img width="300" src="https://user-images.githubusercontent.com/45864744/126752190-6ebd51b0-1a90-4229-af8a-a099c9e3f36e.png">

## Expected result

<img width="300" alt="Snipaste_2021-07-23_15-45-58" src="https://user-images.githubusercontent.com/45864744/126751996-761581ee-61d0-4916-b808-9ebaf9297616.png">

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The word "Guess" is there because it uses an approximate algorithm that may or may not work, and may or may not produce a good result. It's extremely difficult, and perhaps impossible, to write an algorithm that can always produce a good collision polygon automatically. The current algorithm makes a rough guess, and we don't plan on trying to improve it as it's probably an impossible job.
