### ISSUE TITLE
Audio not showing play button if the name of the file is long

### ISSUE THREAD

**Issue by karimlahbach** [Scirra/Construct-3-bugs#4983]
## Problem description
The Audio Plugin not showing the Play button if the name is long

## Attach a .c3p
No need just rename any audio file and put more than 9 longer word

## Steps to reproduce

1.import any audio file and rename it to  something like this (Impact car windshield hit smash sledge hammer_BLASTWAVEFX_14404) 
2. in the audio plugin chose play 
3. you will notice that the preview play button is disappear

## Observed result
<img width="1200" alt="Screen Shot 2021-07-23 at 21 31 36" src="https://user-images.githubusercontent.com/22240696/126839152-a836004f-b907-4ba8-8519-411cd24dafa2.png">

## Expected result
<img width="1200" alt="Screen Shot 2021-07-23 at 21 32 02" src="https://user-images.githubusercontent.com/22240696/126839227-499e5e88-b316-449a-bac3-6956da1e6e99.png">

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details
i'm using the last version of google chrome in my macbook bro (MACOS BIG SUR)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
