### ISSUE TITLE
Wrong text position on iOS, first happens in r243.2

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#4984]
## Problem description

@AshleyScirra if you have time, take a look at this.. I found that wrong text position on iOS, starts happening in r243.2. Until then, text position on iOS is correct! 

## Attach a .c3p

I made a minimal project using r240 in order to check it in various C3 versions:
[TextAlignmentIOS 240.zip](https://github.com/Scirra/Construct-3-bugs/files/6871477/TextAlignmentIOS.240.zip)

## Steps to reproduce

1. Open attached project in every version from r242 to r245
2. Preview it on iOS device
3. Observe text position

## Observed result

In r242 is correct. In r243 and r244 text position is slightly down and after r245 is wrong. Maybe it is somehow related to the the changes on text's vertical alignment that happened on that period. 

![TextAlignmentIOS](https://user-images.githubusercontent.com/53188782/126852112-cbc72dec-0adf-40a6-ad6d-c7b0a4322f18.jpg)

## Expected result

Text to have correct position as in r242

## More details

- Checked on iPhone 6, iOS version 12.5.3
- Text without BBcode have different position than text with BBcode enabled, but that's another story...

**Affected browsers/platforms:** Safari, iOS

**First affected release:** Worked in r242 but broke in r243, r244, r245

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 91.0.4472.164
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
C3 release: r257 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 269 gb
Storage usage (approx): 669 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1, D3D11-9.18.13.4195)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks like you're identifying the changes made across several releases in order to fix #4711. The report mentions you're using iOS 12, which is a couple of years out of date, and I believe the text metrics we need to calculate the correct alignment are only supported on the latest versions of iOS. Therefore closing as I don't think it's possible to make the right calculation on that version of Safari.
