### ISSUE TITLE
On Firefox, text has wrong position in editor when bbcode is enabled

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#4985]
## Problem description

I'm always using C3 with Chrome where things are working just fine but yesterday I opened my project for first time in Firefox and what did I saw? The story of my life! Text has wrong position in editor when bbcode is enabled and alignment is set to vertical or bottom.

I know this thing with text alignment is a nightmare (for you and for me) that never ends but I thought that I should let you know about this new issue and never bother you again with something similar! :)

**Conclusion:** _If someone wants to use text in their game and have the best compatibility between browsers and platforms, should ONLY select top alignment and bbcode enabled._

## Attach a .c3p

[TextAlignmentFirefox.zip](https://github.com/Scirra/Construct-3-bugs/files/6871760/TextAlignmentFirefox.zip)

## Steps to reproduce

1. Open attached project on Firefox
2. Open attached project on Chrome
3. Compare text placement in editor

## Observed result

On Chrome, text has correct position on every situation, on Firefox has not if bbcode is enabled and alignment is set to vertical or bottom.

![Chrome](https://user-images.githubusercontent.com/53188782/126854814-3f7299d6-0b05-48e3-9b79-b82a2ab17c5a.jpg)
![Firefox](https://user-images.githubusercontent.com/53188782/126854817-fa7053e7-01de-4b52-b601-3af5b04a4928.jpg)

## Expected result

Correct position of text

## More details

**Affected browsers/platforms:** Firefox, Windows

**First affected release:** Don't know..

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 89.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
C3 release: r257 (beta)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 669 kb (0%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Unfortunately Firefox currently lacks support for calculating the necessary text metrics to get the right vertical alignment. When Firefox adds support, it should start working correctly. As this is out of our hands, closing. It looks like this Firefox issue tracks implementing the necessary feature: https://bugzilla.mozilla.org/show_bug.cgi?id=1102584
