### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-3-bugs#4986]
## Problem description

Black screen when trying to transition to the next layout 

## Attach a .c3p

[Capx:](https://www.dropbox.com/s/dsxhr3q61lg3e7z/Black%20Screen%20BUG6.c3p?dl=0)

## Steps to reproduce

Note: You need to upload the exported project to a website to reproduce it as it doesn't happen on a normal C3 preview

1.Export the Project as an HTML5
2.Upload it to any website
3.Test it through the website

## Observed result

It shows the "Logo" layout and then after that a black screen when it tries to move to the next layout which is "Main Menu" Layout 

## Expected result

Shows the "Logo" layout and then after that, it should move to the next  "Main Menu" Layout without getting stuck on a black screen

## More details

Chrome

Tested and confirmed not working on  
r251.2 
r257

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 92.0.4515.107
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 726 mb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6663)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by avishaymizrav** [comment]
You are using a loader layout, you need to check that loadingprogress = 1
Before trying to move to another layout.
It probably didn't get the chance to finish loading before the transition ended.

**Comment by Tarek200** [comment]
I would like to add that this looks like it's related to Graphics not sure why meaning the heavier is the art the more likely it will give the black screen.
You can confirm this by removing all the "Art_Test" objects and export again and redo all the steps that I explained above but this time it will work without the art.
Not sure why it is related to the art as there is no art to load on the Layout they need to move to which is the "Main Menu" Layout so I thought that may be helpful to mention it.

**Comment by Tarek200** [comment]
> You are using a loader layout, you need to check that loadingprogress = 1
> Before trying to move to another layout.
> It probably didn't get the chance to finish loading all assets before the transition ended.

Hey Thanks but is that a requirement to check the is =1 ? 
Because I already have my triggers to move to the next layout, also the logo it always shows so it means that it always loaded the layout 
Here are my triggers:
![Image 3](https://user-images.githubusercontent.com/41597700/126901907-eecb41ee-d64e-49c9-9c82-7e4a794866b3.png)

**Comment by avishaymizrav** [comment]
The logo is shown because it is on the loading layout, it loads up before the loading layout is showed.
The problem is that all the other images are loading in this layout, and only when loadingprogress reaches the value of 1, all the images are properly loaded and you can move on.
Waiting 3 seconds is a bad option, because the bigger the game the longer it takes to download and load, it also depends on the network and cpu, so you can't guess how long to wait, you just need to check that the loading is done.

**Comment by avishaymizrav** [comment]
Here use this
[loadingLayout.zip](https://github.com/Scirra/Construct-3-bugs/files/6874012/loadingLayout.zip)

**Comment by Tarek200** [comment]
> The logo is shown because it is on the loading layout, it loads up before the loading layout is showed.
> The problem is that all the other images are loading in this layout, and only when loadingprogress reaches the value of 1, all the images are properly loaded and you can move on.
> Waiting 3 seconds is a bad option, because the bigger the game the longer it takes to download and load, it also depends on the network and cpu, so you can't guess how long to wait, you just need to check that the loading is done.

Hah you're absolutely right it wasn't enough time to load all the Graphics for the whole project, I must be getting old as I'm not sure how I missed that. Nice to see that is not a bug so I don't have to wait for a fix.

Thanks a lot for your help I really appreciate it, have grate day ))
