### ISSUE TITLE
Undo not working with Asynchronous option in Function

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#4989]
## Problem description

Trying to use Ctrl+Z after setting a function as Asynchronous, doesn't work as expected.

## Attach a .c3p

(New Project)

## Steps to reproduce

1. In the event sheet, create a new function.
2. Press OK in the function dialog.
3. Double click the function to edit it.
4. Check "Asynchronous"
5. OK
6. Ctrl+Z

## Observed result

The whole function is removed

## Expected result

Only the Asynchronous state should be reverted to false.

## More details

**Affected browsers/platforms:** Firefox

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
