### ISSUE TITLE
Creating a condition with System Compare two values exists the website

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#499]
## Problem description

I've been having this issue when the C3 tab just ... redirects to a blank one and I had no idea what the heck was happening. I managed to reproduce it using an empty project, funny, by trying to reproduce a different bug.

## Attach a .c3p

![exitingpage](https://user-images.githubusercontent.com/7268697/27093891-f9097dd0-5070-11e7-879f-a35351b5baeb.gif)

## Steps to reproduce

1. Create an empty project using C3 as a browser tab, not desktop app
2. Add as the first condition the Compare as in the gif

## Observed result

The tab tries to redirect itself to a new blank tab. Most of the times there's no confirmation dialogue with Leave - Stay

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r37

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 153 mb (2.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by JeFawk** [comment]
It seems to trigger from basically anything in System.

**Comment by shortercode** [comment]
Related to the new history stack I think, behaviour seems a little iffy if your using the forward and backwards buttons on desktop as well. Assigning to @AshleyScirra

**Comment by AshleyScirra** [comment]
Doesn't happen for me. The back stack code is pretty awkward due to browser limitations though. I might see if I can adjust it to be more reliable in general.

**Comment by JeFawk** [comment]
I tried it again. It's **not a big deal for me** as I almost never use C3 tabbed, and the issue, at least for me appears then.

If I use it as a desktop app it's perfectly fine. Incognito I couldn't reproduce. I had my cache and stuff reset after the issue with r37 where I couldn't preview anything because of double /r37/r37/ in the address.

![image](https://user-images.githubusercontent.com/7268697/27130177-e2ccdaec-510d-11e7-9b30-3f506cbef8f0.png)

**Comment by AshleyScirra** [comment]
I've made some adjustments to try to improve the reliability for r38. Let's check again when that's out.

**Comment by AshleyScirra** [comment]
r38 is out now, can you check if it's better?

**Comment by JeFawk** [comment]
Seems okey now in r38.2

**Comment by AshleyScirra** [comment]
Thanks for confirming!
