### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lucasgc1** [Scirra/Construct-3-bugs#4990]
Error report information
Type: unhandled rejection
Reason: Error: animation frame has no content @ Error: animation frame has no content at d.UG (https://editor.construct.net/r257/projectResources.js:666:320) at d.ab (https://editor.construct.net/r257/projectResources.js:670:405) at https://editor.construct.net/r257/projectResources.js:277:164 at async sIa (https://editor.construct.net/r257/projectResources.js:276:29)
Stack: Error: animation frame has no content at d.UG (https://editor.construct.net/r257/projectResources.js:666:320) at d.ab (https://editor.construct.net/r257/projectResources.js:670:405) at https://editor.construct.net/r257/projectResources.js:277:164 at async sIa (https://editor.construct.net/r257/projectResources.js:276:29)
Construct 3 version: r257
URL: https://editor.construct.net/r257/
Date: Tue Jul 27 2021 22:57:42 GMT-0300 (Horário Padrão de Brasília)
Uptime: 6115.9 s

Platform information
Browser: NW.js
Browser version: 0.54.1
Browser engine: Chromium
Context: nwjs
Operating system: Windows
Operating system version: 8.1
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.54.1 (like Chrome/91.0.4472.114)
C3 release: r257 (beta)
Language setting: pt-BR

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

**Comment by DiegoScirra** [comment]
Closing for not following guidelines
