### ISSUE TITLE
Dragging sprite stripe into Animation bar throws exception

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#4995]
## Problem description

dragging sprite directly into animation list box throws error:

Error report information
Type: unhandled rejection
Reason: Error: expected array @ TypeError: expected array at Function.P.kc (https://editor.construct.net/r257/main.js:851:181) at tA.EXb.mma (https://editor.construct.net/r257/projectResources.js:2133:4) at oA (https://editor.construct.net/r257/projectResources.js:218:274)
Stack: TypeError: expected array at Function.P.kc (https://editor.construct.net/r257/main.js:851:181) at tA.EXb.mma (https://editor.construct.net/r257/projectResources.js:2133:4) at oA (https://editor.construct.net/r257/projectResources.js:218:274)
Construct 3 version: r257
URL: https://editor.construct.net/r257/
Date: Sun Aug 01 2021 04:51:58 GMT-0400 (Eastern Daylight Time)
Uptime: 325.2 s

Platform information
Browser: Edge
Browser version: 92.0.902.62
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.62
C3 release: r257 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

## Attach a .c3p

c3p file: https://drive.google.com/file/d/1fGFLIoDqHB04cVM7aSn4CCnhXzD2F2eV/view?usp=sharing
image :  https://drive.google.com/file/d/1KeOPN0wnlYUK9zXcc8YJTjf_xUgwZPIF/view?usp=sharing

 **tried with different images and got same behavior**

## Steps to reproduce

1. open animation editor
2. drag sprite into animation list box
3. choose sprite sheet on import

video of error (12 sec) :  https://drive.google.com/file/d/1jMyFbY33uoG1_oJRj6EoaMdRqVftMOXg/view?usp=sharing

## Observed result

Unhandled exception, editor crash

## Expected result

new animation created split by the number of frames

## More details

**Affected browsers/platforms:** I was using edge

**First affected release:** r257 is the first I encountered

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 92.0.902.62
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.62
C3 release: r257 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 45 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta. This was a regression from r257.
