### ISSUE TITLE
blog link broken

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4996]
## Problem description

Since `scirra.com` is no supported, the links to articles about blog in the current manuals point to scirra.com, which cannot be resolved.
 
For example,

**manuals**:   
https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/performance-tips

**blog**:   
https://www.construct.net/en/blogs/ashleys-blog-2/answer-own-performance-925

Optimisation: don't waste your time
- href="http://www.scirra.com/blog/83/optimisation-dont-waste-your-time" 
- href="https://www.construct.net/en/blogs/optimisation-dont-waste-time-768"
  

## Steps to reproduce

1.
2.
3.

**Comment by AshleyScirra** [comment]
I've fixed the links in the referenced manual entry/blog posts. Please file another issue if you find any more broken links.
