### ISSUE TITLE
Hierarchy - Pick Children on object create is delayed

### ISSUE THREAD

**Issue by broknecho** [Scirra/Construct-3-bugs#4997]
## Problem description

Right after creating an object (by Object or by Facility), the ChildCount property is set but Children cannot be immediately picked.

## Attach a .c3p

[HierarchyGetChildrenError.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6919875/HierarchyGetChildrenError.c3p.zip)

(drop .zip from the name)

## Steps to reproduce

1. Open attached Project
2. Click buttons 1 - 4 to see behavior
3. Buttons 1 and 3 have no Alert Popup.  Buttons 2 and 4 have alert popups after putting in a modest 0.01 Delay.
4. Check console log's for a reading of `ChildCount` right after each create action.

## Observed result

`ChildCount` property shows 3 for each scenario but the picking of children in sub blocks does not act the same.

## Expected result

Either have the children be pickable immediately or have some sort of warning/information if this is by design.

## More details

**Affected browsers/platforms:** 

Tested with Brave (chromium based)

**First affected release:** 

Using 251.2 Stable

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 92.0.4515.115
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 2 gb
Storage usage (approx): 39 mb (1.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6647)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is actually another case of a long-standing limitation in the event system: newly created instances cannot be picked by conditions until the next top-level event. However it does look like it's worth custom-coding an exception for the 'Pick children' condition, as it seems it would otherwise be difficult to initialise newly created child instances with events. I've implemented this for the next beta.

**Comment by broknecho** [comment]
Ahhhh totally.  I should have remembered that top level event quirk.  I just started using the Hierarchy feature and that `ChildCount` property threw me off a bit.

Thanks for the explanation and it's nice to have some exception throw with unknown conditions there.

Thanks again as always @AshleyScirra !
