### ISSUE TITLE
Sprite + JSON container - System -> 'Create Object' w/ 'create hierarchy' throws exception

### ISSUE THREAD

**Issue by jrkd** [Scirra/Construct-3-bugs#4998]
## Problem description
Cant create a new sprite object with hierarchy.

When Create Object has 'create hierarchy' set to true, regardless of whether the object has a hierarchy or not, as long as its in a container with a data storage object we get this exception. The same thing happens for JSON, Array and Dictionary Object Types.

## Attach a .c3p

[sprite+json-container-bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6920928/sprite%2Bjson-container-bug.c3p.zip)

## Steps to reproduce

1. Run the attached sprite+json-container-bug.c3p.zip project
2. Open the Chrome dev tools 
3. Click the mouse when the construct view is focused, this will trigger the event to create a new jsonsprite
4. See the exception in the dev tools console tab. 

## Observed result

An exception in the chrome dev tools, and no object was created on the construct view. 

## Expected result
Expected the object to be created, no exception and have access to the contained JSON object type when picking the sprite object type in events. 

## More details

**Affected browsers/platforms:** 
Tested in preview mode in Chrome (v91.0.4472.164) & remote preview in Firefox (v90.0.2) on Windows 11 (22000.100)

**First affected release:** 
Not working in version I have - **r251.2 stable release**

## System details

<details><summary>Chrome JS exception (Chromium v91.0.4472.164)</summary>

runtime.js:48 Uncaught (in promise) TypeError: Cannot read property 'GetX' of null
    at C3Runtime.CreateInstanceFromData (runtime.js:48)
    at C3Runtime.CreateInstance (runtime.js:44)
    at SystemPlugin.CreateObject (actions.js:2)
    at Action._RunSystem (action.js:14)
    at EventBlock._RunActions_Fast (eventBlock.js:25)
    at EventBlock._RunAndBlock (eventBlock.js:23)
    at EventBlock.Run (eventBlock.js:20)
    at EventSheet._ExecuteTrigger (eventSheet.js:18)
    at EventSheet._TriggerForClass (eventSheet.js:12)
    at EventSheet._Trigger (eventSheet.js:11)

</details>
<details><summary>Firefox via remote preview JS exception (v90.0.2)</summary>Uncaught (in promise) TypeError: swi is null
    CreateInstanceFromData https://preview.construct.net/c3/runtime.js:48
    CreateInstance https://preview.construct.net/c3/runtime.js:44
    CreateObject https://preview.construct.net/r251-2/plugins/system/c3runtime/actions.js:2
    _RunSystem https://preview.construct.net/c3/events/action.js:14
    _RunActions_Fast https://preview.construct.net/c3/events/eventBlock.js:25
    _RunAndBlock https://preview.construct.net/c3/events/eventBlock.js:23
    Run https://preview.construct.net/c3/events/eventBlock.js:20
    _ExecuteTrigger https://preview.construct.net/c3/events/eventSheet.js:18
    _TriggerForClass https://preview.construct.net/c3/events/eventSheet.js:12
    _Trigger https://preview.construct.net/c3/events/eventSheet.js:11
    _Trigger https://preview.construct.net/c3/events/eventSheetManager.js:13
    Trigger https://preview.construct.net/c3/runtime.js:81
    Trigger https://preview.construct.net/c3/sdk/sdkInstanceBase.js:2
    _OnMouseDown https://preview.construct.net/r251-2/plugins/input/mouse/c3runtime/instance.js:4
    _CheckButtonChange https://preview.construct.net/r251-2/plugins/input/mouse/c3runtime/instance.js:4
    _CheckButtonChanges https://preview.construct.net/r251-2/plugins/input/mouse/c3runtime/instance.js:3
    _OnPointerDown https://preview.construct.net/r251-2/plugins/input/mouse/c3runtime/instance.js:3
    _disposables https://preview.construct.net/r251-2/plugins/input/mouse/c3runtime/instance.js:2
    _FireAndWaitAsyncSequential https://preview.construct.net/lib/events/handler.js:9
    dispatchEventAndWaitAsyncSequential https://preview.construct.net/lib/events/dispatcher.js:5
    _OnEventFromDOM https://preview.construct.net/c3/runtime.js:15
    _OnMessageFromDOM https://preview.construct.net/c3/runtime.js:13
    _PostToRuntimeMaybeSync https://preview.construct.net/c3/workers/domHandler.js:2
    _OnPointerEvent https://preview.construct.net/c3/workers/runtimeDomEvents.js:30
    Attach https://preview.construct.net/c3/workers/runtimeDomEvents.js:18
    Attach https://preview.construct.net/c3/workers/runtimeDomEvents.js:18
    _OnRuntimeReady https://preview.construct.net/c3/workers/domSide.js:30
    _OnMessageFromRuntime https://preview.construct.net/c3/workers/domSide.js:26
    onmessage https://preview.construct.net/c3/workers/domSide.js:11
    _Init https://preview.construct.net/c3/workers/domSide.js:11
    RuntimeInterface https://preview.construct.net/c3/workers/domSide.js:8
    <anonymous> https://preview.construct.net/c3/start-preview.js:1

</details>

**Comment by jrkd** [comment]
Seems like the only way I can get around this is by removing any layout based scene graph hierarchy, creating the parent without hierarchy and creating each child individually and linking them to the parent via Pin behaviour when creating them in the event sheet. 

Also worth noting that this exception only occurs from 'Create Object' action, if you've already got a scene graph based hierarchy on the Layout, with the parent linked to a JSON object, that loads up fine, only the new ones are problematic.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.

**Comment by jrkd** [comment]
Oh dang, looks like it just missed the cutoff for r258 beta, ah well. 
 
Thanks a bunch for looking into and resolving this so quickly @DiegoScirra
