### ISSUE TITLE
[r16] New Project Creation Dialog With Number Format .1 or Emptied Crashed

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#5]
## Problem description

While good news for supporting the numbers typed in the format .1, the new project creation dialog can't handle it and crashed.

## Steps to reproduce

1. Press "NEW PROJECT" to open the new project creation dialog.
2. In viewport size, type ".1" or  just leave it empty space.
3. Press enter or click away to unfocus text field.

## Observed result

Crashed.

## Expected result

Should be able to revert if left empty to default number or handle the newly supported ".1" format.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r16/main.js, line 2, col 199279
Message: Uncaught TypeError: expected finite number
Stack: TypeError: expected finite number at Function.ǃp.ǃUt (https://editor.construct.net/r16/main.js:2:199285) at Function.ǃp.ǃYV (https://editor.construct.net/r16/main.js:2:230536) at ǃp.ǃd.ǃLo.ǃLSs.ǃLGo (https://editor.construct.net/r16/main.js:140:16669) at HTMLInputElement.ǃLGW.onchange (https://editor.construct.net/r16/main.js:140:13448) at ǃp.ǃd.ǃWi.ǃWQh.ǃWtj (https://editor.construct.net/r16/main.js:2:343799) at ǃp.ǃd.ǃWi.ǃWQh.ǃWj (https://editor.construct.net/r16/main.js:2:342934) at ǃp.ǃd.ǃWi.ǃWQh.ǃWj (https://editor.construct.net/r16/main.js:2:359534) at ǃp.ǃd.ǃLo.ǃLSs.ǃhr (https://editor.construct.net/r16/main.js:140:15092) at ǃp.ǃd.ǃLo.ǃLSs.ǃHU (https://editor.construct.net/r16/main.js:2:353462) at re.ǃHU (https://editor.construct.net/r16/main.js:2:327269)
Construct 3 version: r16
URL: https://editor.construct.net/index.html
Date: Fri Apr 07 2017 01:06:51 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 18.9 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for r17.
