### ISSUE TITLE
Fade behaviour ignores "destroy after fade out" bug

### ISSUE THREAD

**Issue by Everade** [Scirra/Construct-3-bugs#50]
## Problem description

The 'Rain Demo' in the Tech Demos menu runs into performance issues because the rain objects are not being deleted.

## Attach a .c3p

-

## Steps to reproduce

1. Pick the Rain Demo inside the Tech Demos
2. Run preview
3. Check the bottom right corner to see the amount of objects being created
4. For me it starts laging at around 4000 objects +

## Observed result

Frame Drops

## Expected result

A proper tech demo which shows what Construct 3 is capable of, not what it can't handle.

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

-

</details>

**Comment by jaydonteh** [comment]
## Cause found & confirmed:
Fade behaviour ignores "destroy after fade out". This cause the "splash" object instances to be kept after it fades out. This applies to any project that uses the "destroy after fade out".

@Everade Perhaps changing the title to **Fade behaviour ignores "destroy after fade out" bug**

**Comment by Everade** [comment]
Thanks for checking it out.
I've changed the title accordingly.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r17.
