### ISSUE TITLE
Crash with nested timelines

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#5000]
## Problem description

I was giving timelines a new try on r258 following the batch of fixes, to see if issues I had reported earlier got fixed since. I was about to declare this version the first version where timeline has not crashed on my, and just as I said that, I clicked the timeline bar one last time, and it crashed on me.

I have no idea what happened, and why it crashed

## Attach a .c3p

Not sure if helpful, but this is the file I got from clicking "save open projects"
[timeline bug.zip](https://github.com/Scirra/Construct-3-bugs/files/6925702/timeline.bug.zip)

## Steps to reproduce

1. I have no idea

## Observed result

Crash

## Expected result

No crash

## More details

For context, I was trying out animating hierarchies (and it works fine), and then I got the idea to try nested timelines. I created a new timeline, dragged the first one in it, tried to drag it again (it did not work) and then clicked on the first timeline a few times.
None of my clicks should have done anything, but it crashed. I don't have more data.

**Affected browsers/platforms:** Only tested chrome

**First affected release:** 258

## System details

here is the error I got
<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r258/components/bars/propertiesBar/propertiesBar.js, line 89, col 153
Message: Uncaught TypeError: g.Xb is not a function
Stack: TypeError: g.Xb is not a function at Array. (https://editor.construct.net/r258/components/bars/propertiesBar/propertiesBar.js:89:153) at window.u2a.dispatchEvent (https://editor.construct.net/r258/main.js:1037:28) at o0 (https://editor.construct.net/r258/components/bars/timelineBar/timelineBar.js:3:3) at Function.SK (https://editor.construct.net/r258/components/bars/timelineBar/timelineBar.js:338:160) at window.Jb.JDb.lea (https://editor.construct.net/r258/components/bars/timelineBar/timelineBar.js:333:387) at HTMLDivElement. (https://editor.construct.net/r258/components/bars/timelineBar/timelineBar.js:331:232)
Construct 3 version: r258
URL: https://editor.construct.net/r258/
Date: Tue Aug 03 2021 18:27:06 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 500 s

Platform information
Browser: Chrome
Browser version: 92.0.4515.107
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
C3 release: r258 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.6911)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
> For context, I was trying out animating hierarchies (and it works fine), and then I got the idea to try nested timelines. I created a new timeline, dragged the first one in it, tried to drag it again (it did not work) and then clicked on the first timeline a few times.
None of my clicks should have done anything, but it crashed. I don't have more data.

What do you mean by **tried to drag it again**? What were you trying to do?

**Comment by skymen** [comment]
I tried to do this
![image](https://user-images.githubusercontent.com/11213825/128061239-e2d7ad5f-1640-4d5d-9428-ed2b764f223b.png)

**Comment by skymen** [comment]
Ok I managed to reproduce it. You just need to click this twice
![image](https://user-images.githubusercontent.com/11213825/128061411-d2c85209-9cbb-4710-871e-9ed08538b23c.png)

Once to select it (and have it show blue) and once to crash C3

**Comment by DiegoScirra** [comment]
The issue will be fixed in the next beta.

As for the checkboxes, there is no particular reason for them not to be styled. I'm pretty sure I added the class that doesn't exist in CSS because I thought it was going to be useful at some point, but never implemented it.
