### ISSUE TITLE
3d layers position inconsistency with layer angles

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#5001]
## Problem description

3d layers positions using vanishing point with altered layer angles are inconsistent with 2d layers.
## Attach a .c3p

https://www.dropbox.com/s/25uasgnk6gp1f4f/vanishingpoint2d3d.c3p?dl=1
## Steps to reproduce

1.Open the project
2.Note the events are set to change the 2d and 3d layers angles at runtime
3.Not the vanishing point is set to change during runtime
4.Run the project
5.Note the objects positions are not kept in sync (even though they are in a hierarchy)

## Observed result
The cube, and sprite on the 3d layer are rendered to different positions than the object on the 2d layer.

## Expected result
All the objects should keep the same position.

## More details

**Affected browsers/platforms:** 

**First affected release:** 
258 beta
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next beta.
