### ISSUE TITLE
Event Sheet: Removing Breakpoint from JS line while debugging is paused causes crash

### ISSUE THREAD

**Issue by jrkd** [Scirra/Construct-3-bugs#5002]
## Problem description
Attempting to remove a breakpoint from a JS line in the event sheet while debugging causes a construct crash. 

## Attach a .c3p
[debug-js-exception.r252.2.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6928072/debug-js-exception.r252.2.c3p.zip)

## Steps to reproduce

1. Press F3 to toggle a breakpoint on the javascript line (it wont show a pause icon, but does actually pause there when debugging)
2. Press 'Debug Layout' icon at the top of the page. 
3. (the game will pause on your JS statement. 
4. Select the statement and press F3 again while the debugger is paused - this causes a app crash

## Observed result

Displays the app crash dialog 'Oops! Something went wrong.' ... 'Construct 3 ran into a problem and is unable to continue...' Ive included the error report info below. 

## Expected result

To remove the pause from the statement, and when pressing the 'continue' play icon in the debugger to continue the flow of the app. 

## More details

**Affected browsers/platforms:** 
Chromium v91.0.4472

**First affected release:** 
r251.2 (stable)
## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r251-2/projectResources.js, line 674, col 23
Message: Uncaught Error: invalid event object type
Stack: Error: invalid event object type at h.f4a (https://editor.construct.net/r251-2/projectResources.js:674:29) at f.mJ (https://editor.construct.net/r251-2/projectResources.js:749:438) at ca.Lob (https://editor.construct.net/r251-2/components/editors/eventSheetView/eventSheetView.js:171:417) at Array. (https://editor.construct.net/r251-2/components/editors/eventSheetView/eventSheetView.js:144:48) at d.Event.CRc.Kfd (https://editor.construct.net/r251-2/main.js:432:217) at d.g.Ia.fia.dispatchEvent (https://editor.construct.net/r251-2/main.js:428:126) at d.g.Ia.fia.Qd (https://editor.construct.net/r251-2/main.js:590:261) at u.Qd (https://editor.construct.net/r251-2/main.js:597:46) at HTMLDocument. (https://editor.construct.net/r251-2/main.js:593:335)
Construct 3 version: r251.2
URL: https://editor.construct.net/
Date: Wed Aug 04 2021 14:04:20 GMT+1200 (New Zealand Standard Time)
Uptime: 32.1 s

Platform information
Browser: Chrome
Browser version: 91.0.4472.164
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.0700000524520874
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next beta.
