### ISSUE TITLE
moving a parent object to another layer doesn't move its child object to the same layer

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#5005]
## Problem description
In runtime if a parent object is moved to another layer then its child object doesn't move to the same layer

## Attach a .c3p
[hierarchy issue.zip](https://github.com/Scirra/Construct-3-bugs/files/6939361/hirarchy.issue.zip)

## Steps to reproduce

1. open attached file
2. play it
3. click on image

## Observed result

only parent object moved to another layer

## Expected result

child object also need to move to the same layer 

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Hierarchies currently don't track Z order and there is no hierarchy option implemented to transform the Z order with the parent.

**Comment by luckyrawatlucky** [comment]
So do you plan to track z order in future?

**Comment by AshleyScirra** [comment]
It's complicated as there are difficult edge cases. For example consider if you have two hierarchies, both with three instances in consecutive Z order, i.e.: ParentA, ChildA1, ChildA2, ParentB, ChildB1, ChildB2. Then you say 'Move ParentB behind ParentA in Z order'. Normally this would produce the Z order ParentA, ParentB, ChildB1, ChildB2, ChildA1, ChildA2. But now you've broken the Z order of ParentA, as its children are further below it. There are even more complicated cases if there are gaps in between the instances. It's difficult to see how this can be resolved, or ought to be resolved, or how or whether it will do what people expect it to. So it would be best to use the suggestions tracker and discuss in detail how these edge cases would be handled before we go and implement it.
