### ISSUE TITLE
Construct 3 (IMPORTANT) - Full Edition Construct 3 License Glitch

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#501]
## Problem description

Several people have noticed today, that they **own a Construct 3 "full edition" license without actually subscribing to one of the available licenses**. We're assuming that this is some sort of glitch that should be fixed ASAP.

## Screenshots:

![c3](https://user-images.githubusercontent.com/15656049/27100890-e89fee3e-507f-11e7-9787-a97377989bb2.PNG)

## Observed result

*What do you see happen?*

Construct free edition users got a full edition license without subscribing to one.

*What did you expect to happen instead?*

If this isn't part of an unannounced event, I would expect that only people who have actually subscribed to a license, would also get the benefits of it.

**Comment by shortercode** [comment]
Fixed, thanks for pointing that out. Something got checked in that shouldn't have. We'll probably have a fix build go out today.

**Comment by Packjackisback** [comment]
Why'd you snitch.
