### ISSUE TITLE
Various other issues with the UI Bars

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#5011]
## Problem description

In the past few months I've tested a bunch of things with UI dialogs, and mostly tried new window dispositions to try and find efficient systems.

I've also encountered many bugs, sometime breaking C3 entirely until you reset the cache (or know what you're doing by removing the right indexed DB keys) that might happen in common scenarios.

The most important one being this one which I freported as a separate entry
https://github.com/Scirra/Construct-3-bugs/issues/5010

This bug report will focus on some other issues I've found that I can only reproduce some of the time, and that seem to happen vaguely randomly. Reason I don't make one entry per bug is that I can't give explanations for all of them or fill a detailed bug report, and they might all be linked to the same underlying issue

## Attach a .c3p

n/a

## Steps to reproduce

https://youtu.be/rKxmQua-CDc

https://youtu.be/0425uwPxeMI

## Observed result

In this video I play around with some of these things, and the major bug happens at the end where C3 crashes
(By the way, restarting C3 does not reset the UI and there is no way to "fix" this without changing the indexedDB values or deleting them)

## Expected result

n/a

## More details

There are a few more issues you might notice in the video (and a few more that I couldn't reproduce in this video that you'll have to take my word for)

As mentionned in https://github.com/Scirra/Construct-3-bugs/issues/5010 logging out and restarting C3 while you have "paid" windows in your layout creates phantom dialogs that can't be interacted with. On top of that, having either the tilemap bar, or a bar with multiple tabs made of paid bars, you get this phantom tab bar that takes the space it used to, but with 0 tab. So when you drag something in it, it tries to push the dialog into a list of children which does not exist.
<details><summary>View error details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r259/main.js, line 317, col 288
Message: Uncaught TypeError: Cannot read property 'PJa' of null
Stack: TypeError: Cannot read property 'PJa' of null at Object.CCG.wf (https://editor.construct.net/r259/main.js:317:288) at sga (https://editor.construct.net/r259/main.js:329:355) at isa.s7 (https://editor.construct.net/r259/main.js:1262:14) at HTMLDocument.gsa (https://editor.construct.net/r259/main.js:1253:208)
Construct 3 version: r259
URL: https://editor.construct.net/r259/
Date: Wed Aug 11 2021 16:15:47 GMT+0200 (Central European Summer Time)
Uptime: 7.5 s

Platform information
Browser: Chrome
Browser version: 92.0.4515.131
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
C3 release: r259 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.6911)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

There is also the issue of having new bars that spawn on top of the start page (when they should not appear) (at 2:00 in the video) and you can drag and dock that new window around and it creates weird things, especially if you then create a project, which changes the layout, and moves stuff around expecting to have only the start page open.

The size of the tabs in the find results, and bookmarks page is not saved

Sometimes when dragging bars to the side of the screen (past the properties bar) the other dialogs get resized, and it creates scenarios where some dialog go under their minimum width

In the video at the end, the phantom dialog is linked to the Timeline Bar, which appears ticked and if I try to untick it (Menu > View > Bars > Timeline), the editor crashes
<details><summary>View error details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'Ay' of null @ TypeError: Cannot read property 'Ay' of null at Qf.g.Za.zka.ov (https://editor.construct.net/r259/main.js:1228:191) at Qf.g.Za.zka.ov (https://editor.construct.net/r259/main.js:1245:439) at Qf.g.Za.zka.Ss (https://editor.construct.net/r259/main.js:1236:120) at d.Ss (https://editor.construct.net/r259/main.js:2228:316) at cfb (https://editor.construct.net/r259/components/misc/mainMenu/mainMenu.js:16:109) at https://editor.construct.net/r259/components/misc/mainMenu/mainMenu.js:15:473 at https://editor.construct.net/r259/main.js:1666:78
Stack: TypeError: Cannot read property 'Ay' of null at Qf.g.Za.zka.ov (https://editor.construct.net/r259/main.js:1228:191) at Qf.g.Za.zka.ov (https://editor.construct.net/r259/main.js:1245:439) at Qf.g.Za.zka.Ss (https://editor.construct.net/r259/main.js:1236:120) at d.Ss (https://editor.construct.net/r259/main.js:2228:316) at cfb (https://editor.construct.net/r259/components/misc/mainMenu/mainMenu.js:16:109) at https://editor.construct.net/r259/components/misc/mainMenu/mainMenu.js:15:473 at https://editor.construct.net/r259/main.js:1666:78
Construct 3 version: r259
URL: https://editor.construct.net/r259/
Date: Wed Aug 11 2021 16:15:19 GMT+0200 (Central European Summer Time)
Uptime: 73.3 s

Platform information
Browser: Chrome
Browser version: 92.0.4515.131
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
C3 release: r259 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.6911)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

Dragging the timeline bar to the left of the screen, past the properties bar and resizing it makes it so it can not resize past it's minimum with, and can go under it. This is only the case with the timeline bar, but does not happen all the time.

With other bars however, it happens pretty often that the minimum and maximum sizes change between two docks, so one time I'll be able to drag as far as I want, and sometimes, I'll be limited to maybe 300px.

If I drag a paid bar somewhere, log out, restart, log back in, drag another bar in the same spot then drag it out, the editor crashes (see second video at the end)

<details><summary>View error details</summary>

Error report information
Type: assertion failure
Message: Cannot find docking pane to remove
Stack: Error at Function.ya.gLa (https://editor.construct.net/r259/main.js:922:268) at window.assert (https://editor.construct.net/r259/main.js:834:38) at isa.Ocb (https://editor.construct.net/r259/main.js:1255:166) at CCG.If.g.Za.Wy.Ze (https://editor.construct.net/r259/main.js:1223:79) at Qf.g.Za.zka.ov (https://editor.construct.net/r259/main.js:1230:409) at Qf.g.Za.zka.ov (https://editor.construct.net/r259/main.js:1245:439) at lga (https://editor.construct.net/r259/main.js:320:235) at qga (https://editor.construct.net/r259/main.js:322:132) at isa.p1 (https://editor.construct.net/r259/main.js:1258:362) at HTMLDocument.fsa (https://editor.construct.net/r259/main.js:1253:42)
Construct 3 version: r259
URL: https://editor.construct.net/r259/
Date: Wed Aug 11 2021 16:22:57 GMT+0200 (Central European Summer Time)
Uptime: 8.5 s

Platform information
Browser: Chrome
Browser version: 92.0.4515.131
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
C3 release: r259 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.6911)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

Sometimes (I couldn't reproduce it sadly) when I move stuff around and reload the editor, the project bar and the tabBar that holds the layer bar and the tilemap bar switch places

This issue also happens when I run this code in the console and play around with the illegal dialog bar
<details><summary>View code</summary>
But this piece of code is cursed, so please try it out if you want to, try and see if you manage to reproduce the issue, then forget about it, deal? :)
Note that I was able to reproduce the issue above without the use of this code, so I know the issue still stands, I just have no clue how to reproduce it reliably.
```Javascript
let openRequest = window.indexedDB.open("PersistantMap");

openRequest.onerror = function (event) {
  console.error(event);
};

openRequest.onsuccess = function (event) {
  console.log("test");
  let res = openRequest.result;
  let store = res
    .transaction(res.objectStoreNames, "readwrite")
    .objectStore("keyvaluepairs");
  let key = store.get("UI_STATE");
  key.onerror = function (event) {
    console.error(event);
  };

  key.onsuccess = function (event) {
    let json = key.result;
    console.log(json);
    json
      .find((x) => x[0] === "PANE_main")[1]
      .push({
        id: "testId",
        size: "296px",
        name: "test",
        devicePixelRatio: 1,
        popup: false,
        type: "CaptionPane",
        activeTab: null,
        caption: "test",
        side: "right",
        docked: false,
        position: {
          x: 1106,
          y: 240,
          width: 296,
          height: 350,
        },
      });
    store.put(json, "UI_STATE");
    location.reload();
  };
};

```

</details>

That's it for now, I might add more stuff if I find new behaviors, and I might make separate reports for specific issues, if I find reliable ways to reproduce them, and can prove they can happen to people in real scenarios.

**Affected browsers/platforms:** Chrome, haven't tested anything else

**First affected release:** since forever maybe? I don't know really.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by skymen** [comment]
Forgot this one in the main post:

If you undock a window that had a small width when undocked but a big with when docked, sometimes the window resizes to its small width and is dragged with a big offset (see second video at the beginning)

**Comment by DiegoScirra** [comment]
@skymen 

Out of all of this stuff which are still happening in the latest beta?

**Comment by skymen** [comment]
> Sometimes (I couldn't reproduce it sadly) when I move stuff around and reload the editor, the project bar and the tabBar that holds the layer bar and the tilemap bar switch places

This one, it happens a lot more often in r262. Haven't played around much with 263 yet, so can't confirm for that version, but 
I spent a lot of time on 262 last week, and it happened quite a few times

**Comment by DiegoScirra** [comment]
The next beta will have a fix for that issue.

**Comment by AshleyScirra** [comment]
r264 is now out, please confirm if now working.

**Comment by skymen** [comment]
I'll give it a try next week, I currently don't have access to my computer
