### ISSUE TITLE
Corrupt .c3p due to conflciting local variables

### ISSUE THREAD

**Issue by AndersAthleticDesign** [Scirra/Construct-3-bugs#5014]
## Problem description

Two local variables with identical names can co-exist in the same scope. This can result in a corrupt .c3p that cannot be opened.

## Attach a .c3p

[local variable conflict.zip](https://github.com/Scirra/Construct-3-bugs/files/6979331/local.variable.conflict.zip)

## Steps to reproduce

1. Move "Function1" to the inside of "Group1" and place it _before_ the declaration of "dx" of the group.  Two variables named "dx" now co-exist.

2. Save the project as single file

3. Try to open the project.

## Observed result

Project cannot be opened. Error message is displayed: "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

Chrome console says: "main.js:2108 [Project] Exception opening:  Error: cannot find event variable 'dx'"

## Expected result

Project should open.

## More details

If the function is instead placed _after_ the declaration of "dx" of the group, there is still no renaming taking place. However, if you save the project in this state, it can subsequently be opened and "dx" of the function has then been renamed to "dx2".

**Comment by AshleyScirra** [comment]
Thanks for filing a minimal repro, this is really helpful. I'll try to make sure this gets fixed soon.

**Comment by AshleyScirra** [comment]
This was tricky to figure out but I think I got it working reliably in the next beta, so hopefully it will no longer be possible to get a corrupt project this way. Thanks for the report, this was an important issue.
