### ISSUE TITLE
Pathfinding: Sprite never makes it to goal position, proximity depends on size & speed

### ISSUE THREAD

**Issue by jrkd** [Scirra/Construct-3-bugs#5015]
## Problem description

When requesting a path to a goal position, a sprite does not make it to that position, but instead stops moving earlier than the position. How far away it gets from the goal position depends on its width/height and the speed settings of the Path finding behaviour.

## Attach a .c3p
[pathfinding-arrived-issue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/6979818/pathfinding-arrived-issue.c3p.zip)

## Steps to reproduce

1. Note the different speed settings for the pathfinding between the top and bottom four grey sprites. 
2. Run the project 
3. Note the distance from the respective goals the sprites are after they finishing moving.

## Observed result
the goal position is always the center of the purple squares, but the sprites using path finding stop the Pathfinding -> Move on path action prematurely, and sit at various positions to the left of the goal centre-points.  

The amount of pixels out the sprite is from the goal seems to change based on the sprite's size, as well as the path finding speed settings. 

## Expected result
I'd expect all the sprites to be sitting right on top of the middle of the goals, with mid-points matching, regardless of size or speed. 

## More details

NB Ive added a on-click trigger to scale up the 1px sprites to see how close they got with the naked eye. 

Chrome v92.0.4515.131

**Affected browsers/platforms:** 

**First affected release:** 
Release r251.2 stable
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 92.0.4515.131
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.0700000524520874
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 23 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks like the size has nothing to do with it - based on the origin point they move the same regardless of the size. The Pathfinding behavior code also ignores the size and only works based on the origin point, so this makes sense.

In the codebase the deceleration calculation is designed to stop when it gets within 10px of the target. This is because floating point calculations in computers are not perfectly precise, so the objects are unlikely to ever decelerate to the exact target position. The 10px margin is designed to reliably ensure moving objects come to a stop close to their target regardless of their speed, acceleration, deceleration, and whether or not they are turning. I guess it could be reduced, but then there might start to be corner cases where objects miss their target, go past it, and then get stuck going in circles - so I'm reluctant to change it.

Since the 10px margin is currently by design and seems to have been working satisfactorily for years now, I have to ask, is this something you really need or were you just reporting something you thought was odd? If you really need it what's your specific use case and why do you need a more accurate move position? I suspect it's worked like this since the Pathfinding behavior was introduced in Construct 2 back in 2013, so it seems like the way it works has been fine for most people for a long time.

**Comment by jrkd** [comment]
>If you really need it what's your specific use case and why do you need a more accurate move position?

Ive got a sprite that has instances placed across the level behind obstacles/walls on the layout that acts as cover positions for enemies - a cover node is selected based on whether path finding can get there, its proximity and line of sight to the player. 

When I'm debugging its immediately obvious that they aren't getting to the actual centre of the sprite (which is just a green circle with some text that i usually have set to invisible), especially cause they aren't that big - 10px is like 20% of their radius. The effect is the enemies can sit in a position that looks out of place for where they should be hiding.

I did try making the cover sprites larger, but then I had problems around being unable to place them too close to walls (eg if they collide with a wall cause of their size, they're marked as invalid) 

--- 

I'm not that familiar with trajectory math but could there be an checkbox on the pathfinding action settings to override the set deceleration in these last frames (eg slow them down faster) rather than override the requested destination position? Then you can be precise about positioning when you want, and precise about movement models when you want.

Also, surely 10px is not enough when your deceleration and/or rotation speed is very slow (eg a v fast moving space ship applying reverse thrusters) and the quicker your deceleration, the more obvious this problem is, cause you always hit the 10px radius right on the edge of it.

If the acceleration/deceleration model of movement is being used, there are surely overshot goals all the time and that's just a feature of how fast you were going and where you wanted to be and how agile you are? 
Perhaps there could be an 'overshot goal' trigger, and a setting for proximity to goal position to count as having arrived?

Apologies for the infodump, just thinking aloud. I understand if this is a low-priority, high-workload issue, thanks for looking into it.

**Comment by Ldwebster111** [comment]
I had something similar to this where the player needed to pat their dog and if I used moveTo to get to the pathfinding point it could be quite jarring when the animation arrived as the player would not be perfectly lined up.

I got around it by checking for the pathfinding path and then moving directly to the destination via imagepoints on the dog, essentially using pathfinding as a check to see if a path is there, but not actually following the path. It's not ideal, but it worked. Would be nice for a more accurate pathfinding.

**Comment by AshleyScirra** [comment]
To be honest, I don't know what the correct maths is to handle this more accurately. Its speed must be controlled according to the deceleration on a frame-by-frame bases incorporating delta-time in a manner that precisely lands it on the destination spot. It's not a simple tween as the object could be turning as it approaches its destination. If anyone can figure out the maths for that I'd appreciate it. As it is it uses a naive approach that just sets the speed according to a proportion of the remaining distance, but that leaves it close to but not exactly on the destination point.

**Comment by jrkd** [comment]
Theres a few good solutions to the v similar problem of having a homing missile reduce its speed to hit a target instead of orbiting it on gamedev exchange. 
- https://gamedev.stackexchange.com/questions/16810/projected-trajectory-of-a-vehicle/16814#16814
- https://gamedev.stackexchange.com/questions/17313/how-does-one-prevent-homing-missiles-from-orbiting-their-targets?rq=1

They both use quadratics and handle a moving target though, and this situation is dealing with a static position. 

**[This one sounds more like what we want](https://gamedev.stackexchange.com/a/73085)**, specifically the second option where they mention `correctSpeed = rotationSpeedInRadians * (distance / 2) / cos(angle);` Currently at work, but ill see if it works on a construct example later on. 


[This also seems like the same problem](https://gamedev.stackexchange.com/a/114675) - if you consider the yellow dot in their animation as the rotational velocity vector applied to the current position, and the teal dot as the goal position. 
Again, using quadratics and sometimes there isnt a solution, because they assume the velocity cant change.

**Comment by AshleyScirra** [comment]
None of those links appear to deal with the problem of controlling a decelerating speed to land exactly on a point.

Even if the pure mathematical equation is identified, there is the engineering side: it is done in discrete steps with a variable time step, and floating point error tends to accumulate with this kind of thing. So even the correct pure mathematical formula will probably have to be modified to some extent to handle these problems.
