### ISSUE TITLE
Construct not installing for offline work

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#5018]
## Problem description

Construct 3 r253 and upper versions not installing for offline work.

Also this doesn't appears.
![image](https://user-images.githubusercontent.com/54614906/129474385-d788aed8-90e4-4f67-a71e-ad5c0c8cf1f9.png)

## Steps to reproduce

1. https://editor.construct.net/r259/
2. Wait for install.
3. It is not installing.

## Observed result

 It is not installing.

## Expected result

Install for offline work.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r253

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in the next release. (Marking to check as sometimes moving to production can affect things.)

**Comment by AshleyScirra** [comment]
Looks like it's working correctly in r260.
