### ISSUE TITLE
iMac unintended editor zoom behaviour (all projects)

### ISSUE THREAD

**Issue by mikehive** [Scirra/Construct-3-bugs#5019]
## Problem description

When using Layout View or Event View on an iMac, CMD + mouse scroll gesture causes the zoom level to change suddenly. Since CMD is a common hotkey component, many common actions (undo, save, copy/paste, etc) are awkward to perform on iMac since the user is regularly changing the zoom level by accident.

I presume this to be a side effect of the zoom hotkey CMD+Mouse Wheel. iMac does not have a mouse wheel and uses gestures. This results in the unintended behaviour. 

I have also heard from another forum user that this happens to them "all the time" when using a trackpad (but I have not personally corroborated this).

## Attach a .c3p

Any project.

## Steps to reproduce

1. Open any project on an iMac and view Layout or Event editor screen.
2. Hold CMD key.
3. Try to scroll in any direction. 

## Observed result

The zoom level changes drastically.

## Expected result

It makes sense that this would happen, but the behaviour is often unwanted and is highly distracting to the user when trying to think about event logic as a small touch on the mouse while holding CMD causes the zoom level to change. It is extremely easy to do this by accident when trying to do something else.

It would be very helpful to provide an option for users on certain devices to disable this hotkey behaviour if it affects them. 

As an aside, an on-screen zoom control would be EXTREMELY useful for changing the view without wrestling with twitchy iMac mouse controls.

As it stands, the only reliable way to restore the event screen to its initial zoom state (as the iMac scroll gesture is very sensitive, meaning that the user spends a good amount of time zooming in and out trying to get it right) is for the user to go away and look up the hotkey to return the zoom to 100%. It would be very helpful if the interface provided a more obvious way to do this. 

(Or perhaps there could be a little on-screen tooltip somewhere unobtrusive when the view is not 100%, reminding users of the reset zoom hotkey?)

## More details

**Affected browsers/platforms:** Confirmed issue on Chrome, Firefox, and offline app on Mac.

**First affected release:** Unknown (presumably for as long as the zoom hotkey has been in effect)

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 92.0.4515.131
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 95 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 555X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can't seem to reproduce this in Chrome on a MacBook Pro: in the Layout View, if I hold control and move with two fingers up and down on the trackpad, it zooms at a reasonable speed. What do you mean by zooming suddenly? Does this match what you're doing?

Cmd+zoom also zooms the event sheet view font size (by design - it's the same shortcut). But it's not clear to me how this interferes with anything else. For example you said this sometimes is activated by accident when using shortcuts like "Copy". But the shortcut for that is Cmd+C, without needing to touch the trackpad at all. So how is this accidentally activated? I'm not sure how you are mixing these two up.

**Comment by brushfe** [comment]
I have this problem as well: it's the font size problem (cmd+two finger scroll over an event sheet). It happens accidentally all the time - it's easy to unintentionally brush the trackpad while command is pressed - meaning I have to constantly reset the font size. It's a workflow interference. An option to disable cmd+two finger scroll would be great!

**Comment by mikehive** [comment]
Unfortunately, this may the kind of problem that you can really only see and understand by doing a lot of work inside Construct. I'm not surprised that you didn't really see what I mean by just opening C3 on a Mac, twiddling the mouse and going "yeah it seems fine". 

If you're copying something with CMD+C, presumably you intend to go somewhere else to paste it. When working at speed, it's natural to want to scroll to the right event to copy, CMD+C it, scroll to where it needs to get pasted, and CMD+V it. If you're doing this a lot on an iMac and scrolling up and down it's just a matter of time before you accidentally do the wrong thing and zoom out to 25% when you were trying to do something else. 

Yes, it's a user mistake based on completely intended interface behaviour and you could call it PEBCAK or a meat component error. But it's a mistake that's far too easy to make - it happens to me multiple times a session pretty much every session, and (as you can see) it's not just me who runs into this issue.

If you don't mind, we would really appreciate the ability to disable this hotkey as and when it proves to be a nuisance.

**Comment by AshleyScirra** [comment]
I'm still not clear how this is a problem in the Layout View, though. It will only zoom a little bit, not a big sudden as the report appears to say. Or is it that you intend to keep exactly the right zoom in the Layout View?

**Comment by DiegoScirra** [comment]
Starting on the next beta the shortcut to increase and decrease font size with **Ctrl/Cmd + Mouse/Scroll Wheel** on an event sheet will be removed. This is not an action that is done too often and you can change the font size using **Ctrl/Cmd + plus/minus** as well as a context menu option. 

The shortcut will be kept for layouts as zooming in and out a layout view is a much more common action.
