### ISSUE TITLE
Consistency: C3 Z order panel does not show which item is selected whilst C2 does

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#502]
## Problem description

The Z Order panel would be way more useful if it would show which object is selected in the panel, like C2 does.

![zorderc3](https://user-images.githubusercontent.com/7268697/27101017-d213de92-5088-11e7-981c-f79214ca8ef2.gif)

![zorderc2](https://user-images.githubusercontent.com/7268697/27101024-d6030668-5088-11e7-90d8-b6ddf355409a.gif)

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

r37

</details>

**Comment by DiegoScirra** [comment]
Fixed in r38.
