### ISSUE TITLE
Bug when previewing

### ISSUE THREAD

**Issue by rafaeltrigo** [Scirra/Construct-3-bugs#5021]
Error report information
Type: assertion failure
Message: cannot select detached view
Stack: Error at Function.d.JYa (https://editor.construct.net/r251-2/main.js:288:209) at window.assert (https://editor.construct.net/r251-2/main.js:200:259) at ca.pp (https://editor.construct.net/r251-2/components/editors/eventSheetView/eventSheetView.js:162:322) at ca.y7c (https://editor.construct.net/r251-2/components/editors/eventSheetView/eventSheetView.js:163:415) at ca.ysd (https://editor.construct.net/r251-2/components/editors/eventSheetView/eventSheetView.js:189:6) at ca.Md (https://editor.construct.net/r251-2/components/editors/eventSheetView/eventSheetView.js:181:6) at HTMLDocument.ce (https://editor.construct.net/r251-2/components/editors/eventSheetView/eventSheetView.js:143:203)
Construct 3 version: r251.2
URL: https://editor.construct.net/
Date: Wed Aug 18 2021 14:29:22 GMT+0100 (Western European Summer Time)
Uptime: 5743.9 s

Platform information
Browser: Edge
Browser version: 92.0.902.73
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.73
C3 release: r251.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0, D3D11-21.20.16.4550)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to do anything without more information. Please see the bug report guidelines.
