### ISSUE TITLE
Recently created object can't be picked

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#5022]
## Problem description

Recently created object can't be picked/found by a for each loop in the same frame, even if the code is properly ordered.

## Attach a .c3p

[Picking Bug (zipped).zip](https://github.com/Scirra/Construct-3-bugs/files/7017155/Picking.Bug.zipped.zip)

## Steps to reproduce

1. Run the project in preview mode.
2. Note that the first red sprite will have its opacity reduced, but the recently created ones wont.

## Observed result

Not every red sprite had their opacity reduced.

## Expected result

All red sprites to have their opacity reduced.

## More details

**Affected browsers/platforms:** Chrome/Windows 10.

**First affected release:** r251 (current stable).

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is another case of a long-standing limitation in the event system: newly created instances cannot be picked by other events until the end of the top-level event.

**Comment by BonzerKitten** [comment]
@AshleyScirra That's completely understandable, limitations are part of any real world software. Do you believe changes to the event system will ever be made in order to accommodate the possibility of picking objects in the same tick/frame? I'm asking just out of curiosity.

**Comment by WilsonPercival** [comment]
> @AshleyScirra That's completely understandable, limitations are part of any real world software. Do you believe changes to the event system will ever be made in order to accommodate the possibility of picking objects in the same tick/frame? I'm asking just out of curiosity.

The frame does not change, you are still selecting in the same frame.
