### ISSUE TITLE
instance and system value cant be in OR event

### ISSUE THREAD

**Issue by easyDoesItOK** [Scirra/Construct-3-bugs#5023]
## Problem description

if a instance value and a system compare value event are in a OR statement, the system statement is ignored.

## Attach a .c3p

[bug instance or system.zip](https://github.com/Scirra/Construct-3-bugs/files/7019846/bug.instance.or.system.zip)

## Steps to reproduce

1. Simple CAPX as attached.
2. on click of sprite, compare a instance value being greater than 0 OR compare 2 values (in this examples I just wrote 1=1)
3. if either of these is true sprite should move.

## Observed result

When the sprites instance value gets to 0, it will no process that the system compare is still correct. 

## Expected result

In the attached CAPX the sprite should keep moving forever even after sprite instance value is 0

## More details

**Affected browsers/platforms:** 

Chrome

**First affected release:** 

251.2 stable

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 92.0.4515.131
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 2 gb
Storage usage (approx): 304 mb (14.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA Quadro P2000 Direct3D11 vs_5_0 ps_5_0, D3D11-26.21.14.3086)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is not a bug, it's a common misunderstanding with OR blocks. If `special > 0` is false, but the OR block runs because `1 = 1`, then the actions run with zero Sprite instances picked. Therefore actions on Sprite have no effect. If it actually did move the sprite, it would be running actions on instances that failed to meet the conditions, which contradicts how conditions work.

**Comment by easyDoesItOK** [comment]
Thanks Ashley, noted. However if I add a 'pick all sprites' event after the 'tap gesture' and before the or statement, each subsetted to each other. By this logic it should then work

![Screenshot_20210824-193941](https://user-images.githubusercontent.com/68974089/130594574-710ff5ca-e1e9-47e6-86cf-4804c41d811f.jpg)

**Comment by AshleyScirra** [comment]
Adding 'Pick all Sprite' will have no effect, because in that event, all sprites already start picked.
