### ISSUE TITLE
Construct 3 "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

### ISSUE THREAD

**Issue by elisaboes** [Scirra/Construct-3-bugs#5024]
## Problem description

I cannot open my project. My computer crashed while I was working on it, and now when I try to open it it says "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

## Attach a .c3p
[PMCopy.zip](https://github.com/Scirra/Construct-3-bugs/files/7024270/PMCopy.zip)

## Steps to reproduce

1. Change from zip to .c3p
2. Try to open file in Construct 3

## Observed result

A dialogue box pops up that says "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

## Expected result

I expected my project to open and be able to work on it.

## More details

**Affected browsers/platforms:** Windows/Chrome

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 92.0.4515.159
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 572 gb
Storage usage (approx): 39 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5749)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
.c3p files are really just .zip files of a folder project, and unfortunately the file you've provided appears to be a corrupt zip. It looks like a lot of data has gone missing from the file. You'll need to restore a backup.

Using WinRAR I was able to partially recover some files, but this is not an openable project as several important files are still missing. In case it's useful to you, here is the recovered zip: 
[rebuilt.PMCopy.zip](https://github.com/Scirra/Construct-3-bugs/files/7031448/rebuilt.PMCopy.zip)
