### ISSUE TITLE
Browser plugin full screen working nor orientation changing

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#5025]
I tried start of the screen-> Browser: Request full screen - Stretch (letterbox scale), navigation UI: Auto
----------------------------> Browser: Lock orientation to landscape
This is not working on both desktop and in mobile. I am doing remote preview in android mobile and only layout is landscape but screen is still in portrait.

I'm not sure if this is really a bug or I'm doing something wrong.

## Problem description

![screen](https://user-images.githubusercontent.com/17684135/130422224-b6e0de75-6b4f-400a-88a3-58fbc4bcb2b0.jpeg)

## Attach a .c3p
[fullscreen issue.zip](https://github.com/Scirra/Construct-3-bugs/files/7030676/fullscreen.issue.zip)

## Steps to reproduce

1. open file
2. do remote preview in android mobile.

## Observed result
**ON MOBILE**
1) Mobile Orientation not changing.
2) Full screen not working.

**ON DESKTOP**
1) Full screen not working.

## Expected result
Mobile Orientation should change to Landscape Mode and full screen should work.

## More details

**Affected browsers/platforms:** 
Chrome, Android

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is not a bug - you can only request fullscreen in a user input event. See the [Browser manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/browser):

> Note the browser may ignore this request unless the action is in a user-initiated event, such as a mouse click, key press, touch event or button press.
