### ISSUE TITLE
Fail to load / save from cloud r260

### ISSUE THREAD

**Issue by moordhuis** [Scirra/Construct-3-bugs#5028]
## Problem description

Latest version r260 will not allow me to load previous files from cloud. I use one drive cloud. I use the construct desktop launcher. Selecting recent projects and choosing a save file from the cloud immediately crashes construct. I also made a new project and tried to save to cloud but once again it immediately crashed. I have a backup file stored on my system that loads just fine which points to it most likely being a problem with cloud saving. It only happens with the latest version r260. Can load / save fine in previous versions still.

## Attach a .c3p

Unable to send a example file as i can not save it. The problem is not happening with a local save. But the problem does happen on a brand new project with no events so should be easy to recreate without a file attached.

## Steps to reproduce

1. Create new project. If useful i made a 1080p landscape.
2. Go to file > save > cloud save
3. Construct crashes.

## Observed result

I see Cloud saving attempt to open briefly then close along with construct.

## Expected result

I expected to see my project load as usual or my project save as normal.

## More details
Problem only seems to be happening with the desktop launcher. Using chrome browser will load fine from cloud.

First started happening in r260. Worked fine in all previous versions.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.51.2
Browser engine: Chromium
Context: nwjs
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.51.2 (like Chrome/88.0.4324.182)
C3 release: r260 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 564 gb
Storage usage (approx): 134 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
If it works in the browser, then it sounds like an NW.js bug, so there may not be much we can do about it. Can you switch to Chrome?

Also your system information says you're using an old version of NW.js (0.51.2). Try upgrading to the latest version (0.55.0) and see if it still reproduces there.

**Comment by moordhuis** [comment]
Updated to 0.55.0 and all seems to be working fine again. Have managed to load my cloud save and new projects can save just fine. No crashes.

**Comment by AshleyScirra** [comment]
OK, must be an NW.js bug that got fixed then.
