### ISSUE TITLE
Crash when Centering the Origin Point , Only when the window is oppen

### ISSUE THREAD

**Issue by rafaeltrigo** [Scirra/Construct-3-bugs#5029]
Crash when Centering the Origin Point

Only when open the window first before change the origin point this bug happens as you can see in the picture

https://www.dropbox.com/s/kh48i3k5n1mdpq5/crash.c3p?dl=0
https://www.dropbox.com/s/9cxbrxuopfszprs/BUG.png?dl=0

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r260/main.js, line 854, col 125
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Function.P.Ea (https://editor.construct.net/r260/main.js:854:131) at GEa (https://editor.construct.net/r260/projectResources.js:150:162) at https://editor.construct.net/r260/projectResources.js:148:436 at https://editor.construct.net/r260/main.js:1666:78
Construct 3 version: r260
URL: https://editor.construct.net/
Date: Wed Aug 25 2021 11:26:53 GMT+0100 (Western European Summer Time)
Uptime: 42290.8 s

Platform information
Browser: Edge
Browser version: 92.0.902.78
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.78
C3 release: r260 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0, D3D11-21.20.16.4550)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
It's not clear to me how to reproduce this and I tried it and it seems to work fine. Please follow the bug report guidelines to ensure we can help.

**Comment by DiegoScirra** [comment]
Found a bug, around that part, not really sure if it is the same one though.
