### ISSUE TITLE
The first parameter in an action or condition dialog isn't automatically given focus 

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#503]
## Problem description

When adding or modifying an action or condition, the first parameter in the dialog that appears isn't given focus.

## Attach a .c3p

[DialogDefaultSelectionBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1073478/DialogDefaultSelectionBug.zip)

## Steps to reproduce

1. Add or modify any condition or action in an event. For example, Sprite: Add to.
2. Observe the dialog containing parameters for the condition or action.

## Observed result

The first parameter of the condition or action isn't given focus by default. The "Done" button effectively has focus because hitting enter confirms the dialog, but visually it looks more like the "Back" button has focus because it has a blue highlight. Hitting tab highlights the "Done" button while leaving the Back button highlighted as well, and hitting tab again adds a dotted selection box to the "Done" button.

## Expected result

The first parameter in the dialog should automatically get focus when the dialog opens. For example, in the case of Sprite: Add to, the "Instance variable" drop down should have focus by default. This is how it works in C2 and I believe also in previous versions of C3.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r37

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 162 mb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It works if the expressions dictionary is closed. Assigning to Diego, looks like Expressions dictionary is stealing focus from the parameters dialog, which it shouldn't do.

**Comment by DiegoScirra** [comment]
Fixed in r38.
