### ISSUE TITLE
Assertion failure: no addon registered

### ISSUE THREAD

**Issue by benjaboyy** [Scirra/Construct-3-bugs#5031]
## Problem description

I get a error "assertion failure" and "no addon registered" when I startup the game I'm working on.
Older save files I opened before are now also unable to open.

## Attach a .c3p

https://drive.google.com/file/d/1WTlXajYiB1OG4-_YRP6ywJJDwYHQRJAa/view?usp=sharing 

## Steps to reproduce

1. Load form anywhere (Drive/desktop)
2. Crashes

## Observed result

Editor freezes with the message pasted in the details

## Expected result

Game to load in editor

## More details

I tested with older versions of the save file and got the same error, these worked before.

**Affected browsers/platforms:** I used windows: Edge, Chrome and Firefox

**First affected release:** 
worked fine on same release the day before, on 260

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: no addon registered
Stack: Error at Function.ya.gLa (https://editor.construct.net/r260/main.js:922:268) at window.assert (https://editor.construct.net/r260/main.js:834:38) at d.h_ (https://editor.construct.net/r260/projectResources.js:973:477) at d.Ja (https://editor.construct.net/r260/projectResources.js:981:123) at Function.Hjc (https://editor.construct.net/r260/projectResources.js:982:361) at d.Ja (https://editor.construct.net/r260/projectResources.js:964:143) at Function.eHb (https://editor.construct.net/r260/projectResources.js:967:67) at Function.Jjc (https://editor.construct.net/r260/projectResources.js:967:175) at d.Ja (https://editor.construct.net/r260/projectResources.js:921:462) at Function.fHb (https://editor.construct.net/r260/projectResources.js:925:443)
Construct 3 version: r260
URL: https://editor.construct.net/
Date: Thu Aug 26 2021 14:36:14 GMT+0200 (Central European Summer Time)
Uptime: 23 s

Platform information
Browser: Chrome
Browser version: 92.0.4515.159
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
C3 release: r260 (stable)
Language setting: nl-NL

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6589)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
@benjaboyy

Do you have any browser extensions installed?

**Comment by AshleyScirra** [comment]
No response for about 2 weeks and can't reproduce so closing.
