### ISSUE TITLE
Canvas record video in Safari flickering

### ISSUE THREAD

**Issue by sweesiong** [Scirra/Construct-3-bugs#5032]
## Problem description

When I used the Screen recording example to record canvas in Safari, the saved video when played is flickering.

## Attach a .c3p
[Screen recording example.zip](https://github.com/Scirra/Construct-3-bugs/files/7064305/Screen.recording.example.zip)

Not allowed to attach c3p, so attached a zip
## Steps to reproduce

1. Run the example under mac Safari
2. Click Record canvas for few seconds
3. Click Stop recording and play downloaded mp4 video

## Observed result
The video is flickering. 

## Expected result
The video should not flicker. 

## More details

When running under mac Chrome, the recorded video is smooth.

**Affected browsers/platforms:** 
macOS Safari, iOS Safari, iOS Chrome

**First affected release:** 
r260
## System details
MacBook Pro

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by sweesiong** [comment]
Hi,
just to let you know that it is also flickering on iOS, pls do a thorough
check.
We are using your product and paying an annual subscription fee, how can
you just say we need to file issues directly to them?

**Comment by AshleyScirra** [comment]
As I mentioned, I'm afraid the problem appears to be with Safari, not Construct. Apple will need to fix it.
