### ISSUE TITLE
Load From URL (Desktop Version) Not working

### ISSUE THREAD

**Issue by Gamedevolop** [Scirra/Construct-3-bugs#5036]
I'm using C3 desktop version and the Load image from URL pointing to my PC stops working.
I have many C2 projects that use this feature and all are broken.
Can you fix it, please?

[Downloads.zip](https://github.com/Scirra/Construct-3-bugs/files/7080624/Downloads.zip)

## Steps to reproduce
1-Run C3 desktop version 
2-In the Load image from URL enter the path where the PNG is located on your PC
Example:
"C:\Users\UserName\Folder\ImageName.png"

3-Hit Run 

## Observed result

The image doesn't load

## Expected result

The image will Load
## More details

Nw.js

r260

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 92.0.4515.159
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
C3 release: r260 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 498 mb (0.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6663)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by Gamedevolop** [comment]
If you run C2 on nwjs that feature still works

I included a C2 capx for you to test it

**Comment by AshleyScirra** [comment]
I'm afraid this is an undocumented feature that was never meant to be supported. It only worked by accident in C2, and in C3 we made some changes, and it no longer works. As undocumented features are not officially supported, we do not promise that any breakages in undocumented features will be fixed. Further this doesn't seem like a good idea anyway - if you use a fixed path like that, it will only work on your PC and not on anyone else's, unless they also set up exactly the same folder structure.

The officially supported way is to use the NW.js object to read files. You'll have to change your project to use that.

**Comment by Gamedevolop** [comment]
Hoh, I didn't know it was an undocumented feature, it was very useful though as I was using it for just internal work to load quick PNGs from PC to speed up the work, it was never meant to be for release.

Though if there is an alternative I don't mind to use it but I tested what you recommended but it doesn't work for me either,

I use NW,js to read the Png file and then I tried both (load from URL or Load from JSON) None of them worked

**Comment by AshleyScirra** [comment]
You're trying to read a binary file as text. Try using the "Read binary file" action.

**Comment by Gamedevolop** [comment]
Hoh that was the issue. 

It worked perfectly now with Binary Data

Thank you so much ))
