### ISSUE TITLE
Crash when dragging an image from Firefox download menu

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5039]
## Problem description

Dragging an image to the animation editor crashes C3 if the image is being dragged from the download menu (the one with "down arrow" icon) of Firefox.

## Attach a .c3p

(New Project)

## Steps to reproduce

1. Open a new project in Firefox.
2. Add a sprite.
3. Double click the sprite to open the animation editor.
4. Fill the image with a solid color.
5. Click save in the animation editor to download the image. (in chrome, this shows a save dialog instead)
6. Click the download button in Firefox bar
7. From the download menu, drag the downloaded image to the animation editor.

## Observed result

Crash

## Expected result

The image should show correctly.
When I drag the same image to another program (e.g. Paint), it opens correctly.

## More details

**Affected browsers/platforms:** Firefox 91.0.2 (64-bit)

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information

Type: unhandled rejection
Reason: Error: g is null @ gba@https://editor.construct.net/r260/main.js:170:449 hba@https://editor.construct.net/r260/main.js:169:383 CCG.ib.E2a@https://editor.construct.net/r260/main.js:973:307 yGa@https://editor.construct.net/r260/projectResources.js:211:204 aM@https://editor.construct.net/r260/projectResources.js:2079:51 om/<@https://editor.construct.net/r260/projectResources.js:2078:289
Stack: gba@https://editor.construct.net/r260/main.js:170:449 hba@https://editor.construct.net/r260/main.js:169:383 CCG.ib.E2a@https://editor.construct.net/r260/main.js:973:307 yGa@https://editor.construct.net/r260/projectResources.js:211:204 aM@https://editor.construct.net/r260/projectResources.js:2079:51 om/<@https://editor.construct.net/r260/projectResources.js:2078:289
Construct 3 version: r260
URL: https://editor.construct.net/
Date: Thu Sep 02 2021 18:41:40 GMT+0200 (GMT+02:00)
Uptime: 29 s
Platform information

Browser: Firefox
Browser version: 91.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
C3 release: r260 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 480 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
