### ISSUE TITLE
Construct Crahed 

### ISSUE THREAD

**Issue by ZManTK** [Scirra/Construct-3-bugs#504]
## Problem description
The construct crashed & restart

## Steps to reproduce

when drag & drop image from desktop to the construct area it works
but when dragging the same image again it crash.

*The construct crashed & restart

## Expected result

*Copy the image in new instance name 

## Affected browsers

* Chrome: yes/no

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r37/main.js, line 61, col 123338
Message: Uncaught Error: invalid size
Stack: Error: invalid size at c.ǃmPc (https://editor.construct.net/r37/main.js:61:123344) at window.ǃmNn.ǃmPW (https://editor.construct.net/r37/main.js:61:110765) at window.ǃmNn.ǃmPm (https://editor.construct.net/r37/main.js:61:111013) at window.ǃmNn.ǃmSo (https://editor.construct.net/r37/main.js:61:110538) at window.ǃmPl.ǃmPS (https://editor.construct.net/r37/main.js:61:113415) at c.ǃmPS (https://editor.construct.net/r37/main.js:61:122390) at f.ǃmPS (https://editor.construct.net/r37/main.js:61:191697) at d.ǃmt.ǃtZ (https://editor.construct.net/r37/main.js:61:381292) at d.ǃmt.ǃtZ (https://editor.construct.net/r37/plugins/sprite/plugin.js:1:8523) at d.ǃmt.ǃtf (https://editor.construct.net/r37/plugins/sprite/plugin.js:1:8323)
Construct 3 version: r37
URL: https://editor.construct.net/
Date: Wed Jun 14 2017 07:49:21 GMT+0300 (Jerusalem Daylight Time)
Uptime: 23.4 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
C3 release: r37

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 745 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
Following your steps, it works fine for me.

Sorry, there's nothing we can do unless you can provide reliable steps to reproduce the problem. It may help to include the exact image you are importing.
