### ISSUE TITLE
Iframe not working on Google Chrome (Cannot read property 'startsWith' of undefined)

### ISSUE THREAD

**Issue by davixe** [Scirra/Construct-3-bugs#5040]
## Problem description

The following error "Exception in 'iframe' handler 'navigate-url': TypeError: Cannot read property 'startsWith' of undefined" appears only on Google Chrome every time an iframe tries to load an url.

## Attach a .c3p

(New empty project)

## Steps to reproduce

1. Open a New project in Chrome
2. Create an iframe object
3. Play or execute the game

## Observed result

The default website (https://www.construct.net) is not loading. If you press ctrl+Mayis+i to open the console, you will see the error.

## Expected result

The website should load without errors.

## More details

This only happens on Chrome. Firefox and Edge are working as expected.

This was working on Chrome last month (approx).

**First affected release:** This happens in different construct versions (tested on r260 and r241)

## System details

<details><summary>View details</summary>

domSide.js:29 Exception in 'iframe' handler 'navigate-url': TypeError: Cannot read property 'startsWith' of undefined
    at IframeDOMHandler._SetSrc (domSide.js:3)
    at IframeDOMHandler._OnNavigateURL (domSide.js:3)
    at domSide.js:1
    at domElementHandler.js:2
    at RuntimeInterface._OnEventFromRuntime (domSide.js:29)
    at RuntimeInterface._OnMessageFromRuntime (domSide.js:28)
    at MessagePort._messageChannelPort.onmessage (domSide.js:12)
_OnEventFromRuntime @ domSide.js:29

Platform information
Browser: Chrome
Browser version: 92.0.4515.159
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
C3 release: r260 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 203 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required but could improve performance or user experience if supported.

WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It works fine for me. No error occurs.

Are you using any browser extensions? Does disabling browser extensions avoid the problem? I suspect one might be interfering with Construct's code.

**Comment by AshleyScirra** [comment]
I still can't reproduce this but it looks easy to work around - the error appears to be because `iframe.src` is undefined, possibly due to some browser extension interfering with loading iframes, so I just added a check that `iframe.src` is set for the next beta.
