### ISSUE TITLE
Double clicking a text object to change its text on Microsoft Edge causes a crash

### ISSUE THREAD

**Issue by edwood-grant** [Scirra/Construct-3-bugs#5041]
## Problem description

Double clicking any Text object in any layout to edit its text causes a crash on Microsoft Edge.

## Attach a .c3p

You can open any project that has a text object. Any project from the demos should suffice. I tested it with the **"Animated Sprite font Effects"**  and the **"Animated Text Effects"** examples.

## Steps to reproduce

1. Using the Edge browser, open any project that has a text object.
2. Double click any text object in the layout to edit its text (clicking the three vertical dots to change its text also generates a crash).
3. Sometimes it needs to be opened/closed two or three times for it to crash.
4. I have not seen this happen on Chrome or Firefox.

## Observed result

Crash, forcing to reload construct.

## Expected result

Not a crash. Display the text box editor normally.

## More details

**Affected browsers/platforms:** Microsoft Edge - Windows

**Affected releases:** Tested on r260 and r261

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/, line 0, col 0
Message: ResizeObserver loop limit exceeded
Stack: null
Construct 3 version: r260
URL: https://editor.construct.net/
Date: Fri Sep 03 2021 17:10:38 GMT-0500 (hora estándar de Colombia)
Uptime: 153.1 s

Platform information
Browser: Edge
Browser version: 92.0.902.84
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 2
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84
C3 release: r260 (stable)
Language setting: es-ES

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon RX 5700 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.15003.5017)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by edwood-grant** [comment]
Ah, I have seen the problem.
It seems that using Text analysing tools like **LanguageTool** or **Grammarly** are what causes the crash. It did not happen on other browser because on those browsers did not have these extensions installed.

Sorry for the bother, I guess disabling extension is the best course of action here of course.

**Comment by AshleyScirra** [comment]
It works fine for me here, but I don't have those browser extensions installed. It sounds like the browser extension is causing this, which means it's out of our control, and I don't think there is anything we can reasonably do to work around this. So you'll need to report it to the browser extension developer.
