### ISSUE TITLE
Close tab I got an error

### ISSUE THREAD

**Issue by rafaeltrigo** [Scirra/Construct-3-bugs#5043]
When I close a tab gave me this error , I didnt do anything I just close a Layout Tab .

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r260/projectResources.js, line 1580, col 84
Message: Uncaught Error: Undopoint not present in buffer
Stack: Error: Undopoint not present in buffer at window.qc.Ze (https://editor.construct.net/r260/projectResources.js:1580:90) at d.SI (https://editor.construct.net/r260/projectResources.js:1467:281) at window.Rbc.Tc (https://editor.construct.net/r260/components/editors/textEditor/textEditor.js:11:109) at Array. (https://editor.construct.net/r260/components/editors/textEditor/textEditor.js:10:33) at Qf.g.Za.zka.dispatchEvent (https://editor.construct.net/r260/main.js:1037:28) at Qf.g.Za.zka.Ze (https://editor.construct.net/r260/main.js:1217:159) at Qf.g.Za.zka.Ze (https://editor.construct.net/r260/main.js:1223:95) at Qf.g.Za.zka.Ze (https://editor.construct.net/r260/main.js:1241:332) at Qf.g.Za.zka.Ss (https://editor.construct.net/r260/main.js:1236:130) at Array. (https://editor.construct.net/r260/main.js:1248:25)
Construct 3 version: r260
URL: https://editor.construct.net/
Date: Sun Sep 05 2021 23:37:46 GMT+0100 (Western European Summer Time)
Uptime: 3154.3 s

Platform information
Browser: Edge
Browser version: 93.0.961.38
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.38
C3 release: r260 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0, D3D11-21.20.16.4550)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help unless you follow the bug report guidelines.
