### ISSUE TITLE
Different behavior stable r260 and stable r251.2

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#5046]
## Problem description

A feature of my project stopped working in the new stable r260, here is a minimal reproduction of the situation.

## Attach a .c3p

[a_Bug_r260_v10.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/7122042/a_Bug_r260_v10.c3p.zip)

## Steps to reproduce

1.open the project in r251.2
2.preview project and observe white square fade in/out
3.do the same in r260

## Observed result

in r251.2 the white square appears and disappears
in r260 it doesnt appear

## Expected result

White square should appear also in r260

## More details

In the latest beta r262 the project fails to be previewed and cant be tested

**Affected browsers/platforms:** I tested with Chrome and Firefox. The problem exists also with a final NW.js export.

**First affected release:** I didnt test the betas inbetween the two stables
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 93.0.4577.63
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 410 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The white square appears in r258 but not r259. I suspect it's to do with this fix in r259:

> Tilemap: fix testing collisions with instances on different layers

The project tests for collisions between a tilemap and an instance on a different layer with a different parallax. I suspect your project previously relied on the old broken behavior, which didn't handle this properly. Now it's handled properly you may have to change the project to get it working with the correct collision detection.

The project failing to preview in the latest betas is a different issue but still needs fixing - assigning to @DiegoScirra as it looks related to the tilemap brushes change.

**Comment by bubbblebub** [comment]
Thanks for the answer. 
I added another File here, I apologize I could reduce the project even more. I made two Versions inside the eventsheet. One is a copy of the other but instead of the Tilemap I used a sprite. Please test both versions just by deactivating one and activating the other. 

-in the new version r260 it treats the same situation different, colision with a sprite works different than collision with tilemap.
-in the previous version r251.2 both situations give the same result, this makes much more sense to me. 

[a_Bug_r260_v11.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/7123626/a_Bug_r260_v11.c3p.zip)

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
