### ISSUE TITLE
Objects get distorted when using 3DCamera with layers that have "Force own texture" setting on

### ISSUE THREAD

**Issue by niechta** [Scirra/Construct-3-bugs#5047]
## Problem description

When using the new 3DCamera plugin, if a layer has "Force own texture" setting on, objects on upper layers get distorted. 

[Project.c3p](https://github.com/niechta/files/blob/main/3DCamera%20Bug%20(Force%20own%20texture).c3p)

## Steps to reproduce

1. Create a layer and turn on "Force own texture" setting.
2. Create a layer above it and put a sprite object on it.
3. Create a 3DCamera and add "Look at position" action so that camera follows your sprite object.
4. Try to move your sprite object in any way (8Direction behavior in example).

## Observed result

Moving objects get distorted.

## Expected result

No distortion at all.

## More details

Can be fixed by creating an emply layer without "Force own texture" setting above the layer with this setting.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 91.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
C3 release: r262 (beta)
Language setting: en-US
Local storage

Storage quota (approx): 854 mb
Storage usage (approx): 376 kb (0%)
Persistant storage: Yes
Browser support notes

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by ulitko** [comment]
что эт за хуйня?))

**Comment by AshleyScirra** [comment]
Yep, this is [Z fighting](https://en.wikipedia.org/wiki/Z-fighting). The renderer does quite a lot of extra work to avoid Z fighting when using a 3D camera, since coplanar sprites are so common in 2D games. However it can't manage this across an own-texture layer, as it renders elsewhere, and it just gets too complicated to deal with. This will be a documented limitation - you should avoid using force own texture layers with 3D camera, or otherwise make sure there isn't coplanar content, e.g. by separating the layers with Z elevation.
