### ISSUE TITLE
3D Opacity is weird when stacked

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#5048]
## Problem description

I was experimenting to see if I could make 3D distance based lighting/fog. 

But I found that opacity behaves quite strangely when stacked on top of each other, it's as if it has some additive effect applied or something like that.

I created 1000 sprites with 1 opacity, and pushed them away from the player, hoping it would gradually fade towards that color in the distance.

![image](https://user-images.githubusercontent.com/5744908/132448549-bc99e038-390f-4725-9f65-ef5446948450.png)

Notice that even after 1000 sprites stacked on top of each other with 1 opacity, it doesn't seem to get close to the original color which is this:

![image](https://user-images.githubusercontent.com/5744908/132448379-1b6d0e47-6e94-4ba3-b318-1c4d0b1828be.png)

Instead of gradually fading towards a deep blue in the distance, instead it moves towards a bright cyan color and you can see the darker colors (black) more easily through it for some reason? 

## 2D example

Sprites seem to do something similar, so it's not just 3D.

![image](https://user-images.githubusercontent.com/5744908/132450523-f4b8e9e8-399f-42f9-a330-e29096a5b479.png)

Notice how the stacked opacity sprites have weird colors, but the black shows through fine.

It doesn't seem to go towards the original color, no matter how many I stack on top of each other.

## Photoshop example

Interestingly it seems photoshop behaves similarly, with hundreds of layers at 1 opacity:

![image](https://user-images.githubusercontent.com/5744908/132451810-19e8686b-73ed-4f3a-9b10-a54c3b122f6e.png)

However, I then tried changing from 8 bits to 32 bits color and it seems to work how you'd expect it to:

![image](https://user-images.githubusercontent.com/5744908/132451875-ee4bb7bc-b6cd-4354-9157-f99bd525cb39.png)

![image](https://user-images.githubusercontent.com/5744908/132451986-06dcf6ba-eca6-4663-b8d2-669587475562.png)

So perhaps it's a "bits" problem?

## Attach a .c3p

[opacityweird.zip](https://github.com/Scirra/Construct-3-bugs/files/7126122/opacityweird.zip)

**Comment by AshleyScirra** [comment]
I don't think this is a bug, it's just the limitations of 8-bit color channels. Here's a minimal repro in 2D: [issue5048.zip](https://github.com/Scirra/Construct-3-bugs/files/7128539/issue5048.zip)

The color is RGBA (41, 77, 142, 3) if you express 1% opacity as an 8-bit alpha component rounded-to-nearest. This will also be premultiplied for better quality blending, so in fact all channels are multiplied by 1% too, and then assuming rounding to nearest, you get RGBA (0, 1, 1, 3). Notice how the red channel has dropped to 0 and the green and blue channels are now the same, as it's run out of precision to express any color difference. So now it's essentially blending towards RGB (0, 255, 255), which has a different hue. There will probably be further similar rounding errors as it draws to the surface and alpha blends on top of the background. And the exact result probably depends on how the rounding works internally (it looks like for me, the minimal repro somehow preserves some red channel, I guess the rounding is handled differently. It might even be GPU-specific.) The fact PhotoShop demonstrates a similar issue shows how it's a limitation of the bit depth, although I suspect PhotoShop is using some other approaches (maybe not premultiplied alpha?) which produces a different but still not perfect result, unless you up to 32-bit color.

Construct could in theory use higher bit depth colors, but this will have a big performance impact, and I'm not sure there is much browser support for that yet. Besides, 1000 overlaid sprites is overdraw hell, so you're probably already tanking performance on weak GPUs with that...
