### ISSUE TITLE
r262 new camera had bug for tilemap and tilemapback

### ISSUE THREAD

**Issue by wertt22** [Scirra/Construct-3-bugs#5049]
**Problem description**
r262 new camera had bug for tilemap and tilemapback
tilemap not show outside viewport,and tilemapback alpha not work when set z for it
**Attach a .c3p**
**[3darpg.zip](https://github.com/Scirra/Construct-3-bugs/files/7127479/3darpg.zip)**

**Comment by AshleyScirra** [comment]
I can't tell what the problem is from this. Please follow the bug report guidelines, we need all that information to be able to help.
