### ISSUE TITLE
Expressions dictionary keeps appearing directly overlapping parameters dialog

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#505]
## Problem description

I keep finding the expressions dictionary appearing directly on top of the parameters dialog. This is the very worst place to put it. It's very confusing for beginners and blocks you from doing anything until you move it.

I'm not 100% sure what causes it to revert but if I move it off the dialog, cancel and re-open the dialog, it's back overlapping.

Providing there is room on the screen, the expressions dictionary should never initially appear overlapping the parameters dialog. Even if that is the remembered position, it should move it off the dialog.

**Comment by DiegoScirra** [comment]
Fixed.

The expressions dictionary now takes available empty space whenever it is shown and it overlaps the parameters dialog.
