### ISSUE TITLE
Drawing Canvas Beta 262

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#5050]
## Problem description

Drawing Canvas is not rendering correctly
## Attach a .c3p
https://www.dropbox.com/s/dc36ey6yie6x2ji/betadc.c3p?dl=1

## Steps to reproduce

1.Open the project
2.View the event sheet... draw ellipse radius of 25
3. Run the project

## Observed result
The ellipse is not being rendered as a circle

The preview shows an oblong ellipse
## Expected result

The ellipse should be a circle with an equal radius
## More details

The same events in the last stable work as expected

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I think some of the new 3D camera code accidentally broke Drawing Canvas. It should be fixed for the next beta.
