### ISSUE TITLE
IOS build fail with admob.

### ISSUE THREAD

**Issue by kesoriny** [Scirra/Construct-3-bugs#5053]
## Problem description

When I build my project to IOS (xcode) without admob it builds fine without any issue but when I add admob it says failed to export project. This only occurs when I add admob. I only need to add admob for pod-file.

## Attach a .c3p

[https://drive.google.com/file/d/16OUWZuczWsKJMU2NiGkEkE3z57gStPEJ/view?usp=sharing]

## Steps to reproduce

1. Add admob
2. export project to Xcode project min. version 14.0+
3. Wait to build

## Observed result

 After stage "adding file" it fails to export and shows alerts "failed to export"

## Expected result

 Export successfully resulting a zip file.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The project uses several third-party addons which could be causing the problem:

- Plugin Mobile Facebook (CV_MobileFacebook) by Chadori
- Plugin PlayFab API (CV_PlayFabClient_APIModule) by Chadori
- Plugin Sync Manager (CV_PlayFabClient_SyncManager) by Chadori
- Plugin Authentication (CV_PlayFabClient_Authentication) by Chadori
- Plugin Mobile Info (CV_MobileInfo) by Chadori

Please see the bug report guidelines - we need a minimal project which does not use any third-party addons to be able to help. Please also check the latest beta if you haven't already (the system details were omitted so it's not clear which release you tested.)
