### ISSUE TITLE
Whitelist Plugins (routine maintenance)

### ISSUE THREAD

**Issue by EMI-INDO** [Scirra/Construct-3-bugs#5054]
Reason: Audience Network SDK UPDATE

`cordova-plugin-codeplay-facebookads-free@0.1.6`

### admob-plus-cordova Cancel due to duplicate
https://github.com/Scirra/Construct-3-bugs/issues/5079

Thank you friend

**Comment by AshleyScirra** [comment]
Updated build server to allow.
