### ISSUE TITLE
Order of tabs isn't preserved on project open 

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#5056]
## Problem description

When a project is opened, the order of the layout/event sheet tabs are not how they were previously ordered. Instead, they're constantly reset to some older order that can't be updated.

Perhaps related—the state of the events and folders (expanded or collapsed) are also not preserved.

## Attach a .c3p

EDIT: I've attached a project.

[https://drive.google.com/file/d/1UIiKfeDsvAJmGcfs9qtQ6vThJSoagewk/view?usp=sharing](url)

And here's a video of the problem in action.

[https://streamable.com/vyr2lo](url)

## Steps to reproduce

1. Open the attached project.
2. Reorder the tabs at the top of the editor. 
3. Save and close the project.
4. Reopen the project.

## Observed result

The tabs are not in the order you left them.

## Expected result

The most recent tab order is preserved. 

## More details

**Affected browsers/platforms:** Chrome (most recent version, and throughout all versions since 2019)

**First affected release:** Probably around 240, but 262 for certain.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can you find a way to reproduce it in a new project? We may be unable to help if it cannot be reproduced in a minimal project.

**Comment by brushfe** [comment]
I've managed to create a minimal project, the link is here (and in the bug report above).  

[https://drive.google.com/file/d/1UIiKfeDsvAJmGcfs9qtQ6vThJSoagewk/view?usp=sharing](url)

**Comment by mikehive** [comment]
For what it's worth (if anything), I have experienced the same issue. I always prefer to have my layout editor tabs first in the bar, and the event tabs second. But when I reload C3 my tabs have been reorganised and the first tab is an event tab again. Currently using r260 on Mac.

**Comment by DiegoScirra** [comment]
Fixed in the next beta. Sorting tabs without tearing them off first was not triggering an update of the new state.
