### ISSUE TITLE
File loader - Release file not working?

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#5057]
## Problem description

If you try to load the same file twice the "on changed" never triggers
Releasing FileAtUrl(0) should allow reselecting the same file.

If I set the html object value to null in JS, then I can select the same file twice, isn't that what releasing the file should do?

Note: I might be doing the release file wrong, as I found no documentation, examples or forum posts about it.

## Attach a .c3p

[fileLoaderBug.zip](https://github.com/Scirra/Construct-3-bugs/files/7157313/fileLoaderBug.zip)

## Steps to reproduce

1. Load a file - see "on changed" event triggers and logged.
2. Try to load the same file again - or try to release and then load the file.
3. Finally use the NULL button to clear the file loader and try loading the file.

## Observed result

Releasing the file doesn't clear the input value.

## Expected result

Releasing the file should clear the input value.

## More details

**Affected browsers/platforms:** Chrome/NWjs

**First affected release:** r260

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.55.0
Browser engine: Chromium
Context: nwjs
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.55.0 (like Chrome/92.0.4515.107)
C3 release: r260 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 27 gb
Storage usage (approx): 442 mb (1.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7196)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
"Release file" does not affect the file chooser element itself. It's for managing memory, and means the memory of the chosen file is allowed to be released.

"On changed" fires whenever the browser triggers the event, Construct has no part in it. If you choose the same file twice it has not changed the file selection, so it seems reasonable that "On changed" does not fire a second time.
