### ISSUE TITLE
Anim-editor folder delete crashes c3

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#5058]
## Problem description
Case you delete folder in anim-editor, results in crash.

## Steps to reproduce

1.Open new, create sprite, open anim-editor
2.Select animation folder by clicking on folder green icon
3.Press Delete on keyboard

## Observed result
Crash

## Expected result
No crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r262/main.js, line 850, col 455
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Function.P.i (https://editor.construct.net/r262/main.js:850:461) at DGa (https://editor.construct.net/r262/projectResources.js:223:246) at KA.FYb.m7 (https://editor.construct.net/r262/projectResources.js:2144:485) at QYa.R7b.Id (https://editor.construct.net/r262/projectResources.js:2128:503) at HTMLDocument.nD (https://editor.construct.net/r262/projectResources.js:2116:88)
Construct 3 version: r262
URL: https://editor.construct.net/r262/
Date: Tue Sep 14 2021 13:15:28 GMT+0300 (Eastern European Summer Time)
Uptime: 99.6 s

Platform information
Browser: Chrome
Browser version: 93.0.4577.63
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
C3 release: r262 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta, this was introduced in the last stable release.
