### ISSUE TITLE
newbug for tilemap on r263，r262 is ok

### ISSUE THREAD

**Issue by wertt22** [Scirra/Construct-3-bugs#5061]
**## Problem description**

i use official plat collision example add 2tilemap not show even i set to different layer and different zelevation and set layout scale to 0.00000001

**## Attach a .c3p**

[tilemapbug.zip](https://github.com/Scirra/Construct-3-bugs/files/7166393/tilemapbug.zip)

**Comment by AshleyScirra** [comment]
I don't think setting the layout scale to such an extreme value is a reasonable thing to do, so I don't think it's worth fixing issues that happen with that. The report also does not follow the bug report guidelines so it's difficult to investigate anyway.
