### ISSUE TITLE
C3 crash on Undo - "First Person Platformer "

### ISSUE THREAD

**Issue by rafaeltrigo** [Scirra/Construct-3-bugs#5062]
When Undo usong the new example "First Person Platformer "

1) I opened the project 
2) change the positions of 3d ground
3) change the images of the 3D shapes
4) Undo every thing pressing ctrl+z 
5) gave me this error below

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: animation frame has no content @ Error: animation frame has no content at d.UE (https://editor.construct.net/r263/projectResources.js:673:320) at d.v_ (https://editor.construct.net/r263/projectResources.js:678:348) at https://editor.construct.net/r263/projectResources.js:597:316
Stack: Error: animation frame has no content at d.UE (https://editor.construct.net/r263/projectResources.js:673:320) at d.v_ (https://editor.construct.net/r263/projectResources.js:678:348) at https://editor.construct.net/r263/projectResources.js:597:316
Construct 3 version: r263
URL: https://editor.construct.net/r263/
Date: Wed Sep 15 2021 14:31:21 GMT+0100 (Western European Summer Time)
Uptime: 1802.9 s

Platform information
Browser: Edge
Browser version: 93.0.961.38
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.38
C3 release: r263 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0, D3D11-21.20.16.4550)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
I tried this and it worked fine for me. Please follow the bug report guidelines otherwise it's impossible for us to help.
