### ISSUE TITLE
Crackling Audio noise appears on iOS 14.7.1 (at least) devices while using positional playback

### ISSUE THREAD

**Issue by MihaMS** [Scirra/Construct-3-bugs#5063]
**Problem description**
Crackling Audio noise appears on iOS 14.7.1 (at least) devices while using positional playback.

[SoundIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/7171030/SoundIssue.zip)
Example project file that represents this problem.

**Steps to reproduce**
1. Open provided example and run Remote Preview. Open (Run) it on iOS 14.7.1 (latest at this moment) device. Confirmed on iPhone8 and iPadPro 2ndGen, but should be the same on other devices with iOS 14.
2. Tap on screen to activate audio, wait a few minutes, listen.
(It's better to turn off your device screen auto-shutdown to prevent it from going to sleep)

**Observed result**
After a few minutes Audio starts to crackle, then it becomes more and more noticeable and after another few minutes, all sounds become a noise.

**Expected result**
Sounds should play without any noise and crackles.

**More details**
To check it, you need iOS device and a bit of patience. On my PC all works fine, on Android - I can't check it right now, but on my iPhone8 and iPadPro-2ndGen (both on iOS 14.7.1, testing by C3 Remote Preview) audio starts crackling (or pops) after about 2-3 minutes and then becomes harder and harder until all audio is messed up in noise.
Interesting moment - I also have a very old iPadAir with iOS 12.5.4, and on it - all works fine, almost no sound issues, just a few "pops" maybe in 5 minutes.
By the way, on the same devices (with iOS 14.7.1) I have my old game C2 build (compiled somewhere in 2017) that still works fine without this issue. 
Tried to change different settings (like to switch from HRTF to Equal Power), but currently, nothing helped.

**System details**
**Construct 3 details:**
Platform information
Browser: Chrome
Browser version: 93.0.4577.63
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
C3 release: r260 (stable)
Language setting: en-US

**Tested device details:**
iPhone8, iOS 14.7.1
iPadPro 2nd generation, iOS 14.7.1
In Remote Preview and compiled xcode game build in TestFlight

**Comment by AshleyScirra** [comment]
I can reproduce after waiting about 5 minutes on an iPad Pro with iOS 15. However the audio engine is managed by the browser, not Construct, so I think Apple need to fix this. I reported it to Apple here: https://bugs.webkit.org/show_bug.cgi?id=230950
