### ISSUE TITLE
GameDistribution and GameMonetize SKD Error

### ISSUE THREAD

**Issue by Stefannag** [Scirra/Construct-3-bugs#5065]
## Problem description

If I add the GameDistribution or GameMonetize SDK in the Construct 3 project, the project will show just a black screen and an error in the console.

## Attach a .c3p

https://www.dropbox.com/s/fcj4va9rn12fglj/GDGM-SDK-Error.zip?dl=0

## Steps to reproduce

1. Add the GameMonetize and GameDistribution official SDK's in Construct 3
2. Open the project
3. Run the project

## Observed result

When the SDK is in the project, the project will fail and will show just a black screen with the following error in the console:

```
Uncaught (in promise) ReferenceError: window is not defined
    at new SingleGlobalInstance (89af66c8-e762-40d7-b98f-b26d98572c97:20)
    at Function.New (jsutil.js:13)
    at Instance._CreateSdkInstance (instance.js:7)
    at ObjectClass._CreateSingleGlobalInstance (objectClass.js:13)
    at new ObjectClass (objectClass.js:8)
    at Function.New (jsutil.js:13)
    at Function.Create (objectClass.js:8)
    at C3Runtime._LoadDataJson (runtime.js:28)
    at C3Runtime.Init (runtime.js:20)
    at async InitRuntime (56a149a7-432e-4b24-9acd-3b04a3727c4c:6)
```
Besides that error, there will be a warning: 
```
bootPreview.js:51 Unexpected message type 'undefined'
OnBootMessage @ bootPreview.js:51
```

## Expected result

I expected the project to run as well with those plugins.

## More details

The SDKs are downloaded from their official sites. After contacting them, they said there is no problem with these SDKs.

I attached in the .zip folder those SDKs as well, but, if you want, you can download them directly from:

- GameMonetize: https://gamemonetize.com/sdk
- GameDistribution: https://gamedistribution.com/sdk/construct3

**First affected release:** 

I run the r260 stable version, having an active personal license of Construct 3.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 93.0.4577.82
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
C3 release: r260 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 1.7 gb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I'm afraid we cannot provide support for third-party addons. If you have a problem with a third-party addon, you must take it up with the addon developer.
