### ISSUE TITLE
(3D Camera) Mesh sprites being culled when their collision box moves off-screen

### ISSUE THREAD

**Issue by SephBoss** [Scirra/Construct-3-bugs#5069]
## Problem description

When using the 3D camera, any mesh sprite with vertexes raised on the Z axis winds up being culled once their collision box exits the view port, such as when the player gets close enough that they're too tall to see it, or simply looks too far up.

## Attach a .c3p

[CullingEx01.zip](https://github.com/Scirra/Construct-3-bugs/files/7189924/CullingEx01.zip)

## Steps to reproduce

Move too close to a mesh sprite or use the mouse to look up and down and they will disappear and reappear every time their collision goes off screen

## Observed result

Meshes disappear prematurely while they should still be on-screen

## Expected result

Meshes should remain visible until the entire mesh is off-screen

## More details

**Affected browsers/platforms:** 

Chrome, Construct R263

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by SephBoss** [comment]
*Edit because I accidentally left an unnecessary plugin in the first .c3p I added

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next beta.
