### ISSUE TITLE
Trying to preview any project tries to export as nwsj and crashes C3

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#507]
## Problem description

Cannot reproduce incognito mode.

## Attach a .c3p

[PressF4.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1074746/PressF4.c3p.zip)

## Steps to reproduce

1. open the project
2. press F4

## Observed result

Notice the crash (it does on my system)

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r37/exporters/preview/exporter.js, line 1, col 40
Message: Uncaught ReferenceError: ǃE is not defined
Stack: ReferenceError: ǃE is not defined at https://editor.construct.net/r37/exporters/preview/exporter.js:1:40
Construct 3 version: r37
URL: https://editor.construct.net/index.html
Date: Wed Jun 14 2017 16:40:26 GMT+0300 (GTB Daylight Time)
Uptime: 7.9 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r37

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by JeFawk** [comment]
I deleted my cache and it's working fine now.

**Comment by AshleyScirra** [comment]
Works for me. Probably just a glitch in the matrix.
