### ISSUE TITLE
Unhandled Rejection when creating groups quickly

### ISSUE THREAD

**Issue by oosyrag** [Scirra/Construct-3-bugs#5070]
## Problem description

Construct crashes when creating groups quickly via keyboard shortcuts. Reproducible in stable R260 and R251.2.

## Attach a .c3p

New blank project

## Steps to reproduce

1. Create multiple groups quickly by keyboard via 'g' and 'enter ' on the event sheet in a new project.

## Observed result

Construct crashes

## Expected result

No crash

## More details

**Affected browsers/platforms:** Tested on Chrome, Windows.

**First affected release:** Uknown, but present in 2 latest stables.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'x3b') @ TypeError: Cannot read properties of null (reading 'x3b') at eP.g.I.hvc.M (https://editor.construct.net/r260/projectResources.js:2432:66) at d.aw (https://editor.construct.net/r260/components/editors/eventSheetView/eventSheetView.js:210:247)
Stack: TypeError: Cannot read properties of null (reading 'x3b') at eP.g.I.hvc.M (https://editor.construct.net/r260/projectResources.js:2432:66) at d.aw (https://editor.construct.net/r260/components/editors/eventSheetView/eventSheetView.js:210:247)
Construct 3 version: r260
URL: https://editor.construct.net/
Date: Fri Sep 17 2021 10:37:27 GMT-0700 (Pacific Daylight Time)
Uptime: 10.5 s

Platform information
Browser: Chrome
Browser version: 93.0.4577.82
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
C3 release: r260 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 570 Series Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.22021.1002)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
