### ISSUE TITLE
crashes when deleted 3d shape plugin

### ISSUE THREAD

**Issue by erenertugrul** [Scirra/Construct-3-bugs#5071]
## Problem description

crashes when deleted 3d shape plugin
r263

## Steps to reproduce

1. open 3d shape project
2. delete 3d shape plugin
3. crashed

https://user-images.githubusercontent.com/27224622/133909772-ca3e5b6a-02b4-4f52-b144-c3aaca1bc965.mov

**Comment by AshleyScirra** [comment]
Fixed for next release.
