### ISSUE TITLE
Type: unhandled rejection Reason: Event 'error': [object Event]

### ISSUE THREAD

**Issue by tommakesgames** [Scirra/Construct-3-bugs#5073]
Happens on preview. 

Have tested in Chrome, Chrome when installed, and Firefox.

Have cleared cache in all these with no change.

It's a super simple project (early!) with hardly anything to go wrong. Why is something this simple causing problems all of a sudden when it was running a second ago?

[crashReport.zip](https://github.com/Scirra/Construct-3-bugs/files/7192470/crashReport.zip)

Info from crash here:

Error report information
Type: unhandled rejection

Reason: Event 'error': [object Event]
Construct 3 version: r263
URL: https://editor.construct.net/r263/
Date: Sun Sep 19 2021 17:09:18 GMT+0100 (British Summer Time)
Uptime: 18.1 s

Platform information
Browser: Chrome
Browser version: 93.0.4577.82
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
C3 release: r263 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) Iris(R) Plus Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by DiegoScirra** [comment]
What is the problem here?

I tried opening the project in the latest beta and it works fine. Previewing also seems to work properly.

**Comment by tommakesgames** [comment]
Hi there, thanks for quick reply,

It’s a problem with preview. Get the crash screen with the info indicated. Have up to date browsers. Removed all plugins from browser to check for errors. No change. Cleared cache. No change. What else could I do from my end?

Cheers

Tom

**Comment by AshleyScirra** [comment]
Preview is working fine for me in r263. Unfortunately there are no useful clues in the crash report. So we have nothing at all to go on.

Do you have any browser extensions installed? Perhaps one is interfering with Construct. Try disabling them and see if that helps.

**Comment by AshleyScirra** [comment]
It's been a week and we have nothing to go on so closing.
