### ISSUE TITLE
3DShape not randomly selecting Family member

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#5076]
## Problem description
AFAIK family members should be picked randomly? Like spawning a family gives a random member, right?
But the 3D shape does always show the first member/sprite.

And I tried a for each 3d shape loop to set a random image but it always shows the same image.

## Attach a .c3p

[3DShapeFamilies.zip](https://github.com/Scirra/Construct-3-bugs/files/7217807/3DShapeFamilies.zip)

## Steps to reproduce

1. add sprites to family
2. use family as 3d face
3. (try sprite without family but its always the same image)

## Observed result
always using the first/same family member

## Expected result
random family members for each object using the family

## More details

I used this for the 3. step

+ System: For each 3DShape
-> 3DShape: Set Left face to use image of FoliageLeft
-> FoliageLeft: Set animation frame to random(5)

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
r260
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 93.0.4577.82
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.2000000476837158
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
C3 release: r260 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 230 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.12028.2)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
No, it won't pick a random family member in that case. That is true for spawning a family, as you're creating one instance, and which object type should it be? There's no good answer so it picks a random one as that might sometimes be useful. That is specific to creating/spawning instances and doesn't apply in any other scenario. For example with 3D shape, the face uses a corresponding instance (based on the IID), not a random instance. (Besides, if it was a random instance, it would flicker unpredictably as it kept choosing different instances!)

**Comment by fodi** [comment]
I have encountered the same issue today and I have an idea that could possibly solve this:
https://construct3-21h2.ideas.aha.io/ideas/C321H2-I-460
