### ISSUE TITLE
Whitelist Plugins (routine maintenance)

### ISSUE THREAD

**Issue by eltonnobrega** [Scirra/Construct-3-bugs#5079]
Hi, how are you?
Is it possible to add new versions of these plugins?

com-artemisoftnian-plugins-unityads3@3.7.2
admob-plus-cordova@1.25.0

And add these?
Reason: Add mediation with admob.

cordova_admob_mediation_applovin@1.0.1
cordova_admob_mediation_ironsource@1.0.0
cordova_admob_mediation_unityads@1.0.0

Another option instead of adding them, is the scirra team to create them, as they are very simple. They basically have no code, just add mediation libraries.

**Comment by AshleyScirra** [comment]
Please file requests for new and updated plugins in separate issues. We handle them on different schedules and so need to be able to track and close them separately.

**Comment by eltonnobrega** [comment]
Do I have to make two new requests now or does your message refer to future requests made by me?

About the requests, should I make one for Update and another for New or is it better to make one request for each package?

**Comment by AshleyScirra** [comment]
This issue is closed and will no longer be monitored. Please file two issues.

**Comment by eltonnobrega** [comment]
I believe they are all routine.
I even wanted to add one more to the list of additions:
cordova-plugin-applovin-max@1.0.6

The reason for all these additions and updates is that we would have more options to use ads in our app. (Admob, Admob with mediation, unityads3, appLovin). Today, I use ironSource because admob has limited my account to show ads for two months for no reason.

**Comment by AshleyScirra** [comment]
OK, sorry for the confusion, I realised the forum thread did not describe the new process around the routine/urgent schedule so I've updated it with some explanation of that. I'll reopen this and address on the routine schedule.

**Comment by AshleyScirra** [comment]
Updated build server to allow.
