### ISSUE TITLE
C3 Crashing this morning with r37 when testing..  Red Screen of Death

### ISSUE THREAD

**Issue by part12studios** [Scirra/Construct-3-bugs#508]
## Problem description

I tried to run C3 today with various projects new and old and none of them will run..

## Attach a .c3p

[Soaring.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1074885/Soaring.c3p.zip)

it happens to all of the projects.. it's not the files themselves but attached anyway

## Steps to reproduce

1.  open any project..
2. run it to test
3. you see thie message listed under system details..  

![screen shot 2017-06-14 at 10 27 53 am](https://user-images.githubusercontent.com/2348824/27137519-30038774-50ec-11e7-946c-559e27b1bf5b.png)

Red Screen of Death? 

## Observed result

it crashes without fail.. have restarted browser..  

## Expected result

run the test browser popup as they did yesterday.. 

## Affected browsers

* Chrome: yes
* Firefox: ???
* Edge: ???
* Safari: ???

## System details

**Error report information**
Type: unhandled exception
File: https://editor.construct.net/r37/exporters/preview/exporter.js, line 1, col 40
Message: Uncaught ReferenceError: ǃE is not defined
Stack: ReferenceError: ǃE is not defined at https://editor.construct.net/r37/exporters/preview/exporter.js:1:40
Construct 3 version: r37
URL: https://editor.construct.net/
Date: Wed Jun 14 2017 10:22:59 GMT-0400 (EDT)
Uptime: 10 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r37

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon HD 6770M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by shortercode** [comment]
Not entirely sure what's wrong here, I managed to replicate it once. I refreshed the page to try and get some more useful information from the crash and it vanished

**Comment by part12studios** [comment]
it's still happening for me.

**Comment by shortercode** [comment]
Do you have any messages in your console?

**Comment by part12studios** [comment]
i don't have a console screen open.  how do i do that?

**Comment by part12studios** [comment]
register-root-sw.js:4 Registered root service worker on https://editor.construct.net/
/r37/main.js:162 Registered service worker on https://editor.construct.net/r37/
/r37/main.js:61 [WebGL] Shader program '<fill>' compilation log: WARNING: Output of vertex shader 'vTex' not read by fragment shader
exporter.js:1 Uncaught ReferenceError: ǃE is not defined
    at exporter.js:1
exporter.js:1 Uncaught ReferenceError: ǃE is not defined
    at exporter.js:1
exporter.js:1 Uncaught ReferenceError: ǃE is not defined
    at exporter.js:1
exporter.js:1 Uncaught ReferenceError: ǃE is not defined
    at exporter.js:1
exporter.js:1 Uncaught ReferenceError: ǃE is not defined
    at exporter.js:1
exporter.js:1 Uncaught ReferenceError: ǃE is not defined
    at exporter.js:1
/r37/main.js:71 Uncaught (in promise) Error: preview not loaded
    at u.ǃmhS (/r37/main.js:71)
    at ǃtBV.ǃm.ǃA_.ǃQk.then (/r37/main.js:71)
    at <anonymous>

**Comment by shortercode** [comment]
Can you try something for me from the debugger? Go to the network tab and ensure "Disable cache" is ticked, then refresh the page and try previewing something again.

**Comment by part12studios** [comment]
it's working now.  i'm not sure if it was the disable cache or not but it did work this time.  i'm going to refresh the browser and close it completely and reopen to see if it stays fixed

**Comment by part12studios** [comment]
yes that seems to have cleared up the issue. i closed the browser and reopened it.

**Comment by shortercode** [comment]
We had to republish r37 this morning, I expect something in your cache got confused. I realised that because I'd opened the debugger to try and a get a trace of the crash earlier I had probably done an accidental cache skip and fixed it. Should be fine now, sorry it took so long to figure it out.

**Comment by part12studios** [comment]
hey no problem thanks for helping isolate it :)
