### ISSUE TITLE
Whitelist Plugin Update (Urgent)

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#5080]
Hi, please whitelist this plugin. The previous one is not working as intended.

`sparsha-firebase-dynamiclinks@1.0.0`

Thank you

**Comment by AshleyScirra** [comment]
By "essential" do you mean "urgent" or "routine maintenance"?

**Comment by SparshaDhar** [comment]
> By "essential" do you mean "urgent" or "routine maintenance"?

Sorry I meant urgent

**Comment by AshleyScirra** [comment]
Updated build server to allow.
