### ISSUE TITLE
R264 Tilemap Minify Script problem

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#5081]
## Problem description

In R264 Tilemaps can cause minify script not to work
## Attach a .c3p

[a_Bug_r264_minify.zip](https://github.com/Scirra/Construct-3-bugs/files/7236045/a_Bug_r264_minify.zip)

## Steps to reproduce

1.open example project in r264
2.export - nw.js- dedublicate images check -recompress images check, minify script advanced
3.nw.js version 0.52 chromium 89 (required for steam greenworks export)

## Observed result

error message :
/str/c3runtime.js:3275:79: ERROR - [JSC_REASSIGNED_CONSTANT] Constant reassigned: probability
  3275| for(const [index,probability]of tileDataItem){if(typeof probability!=="number")probability=1;this._probabilityTable.AddItem(probability,index)}return this._probabilityTable.Sample()}_SetTile(x,y,index){if(x===EMPTY_INDEX)return;this.GetSdkIntance().SetTileAt(x,y,index)}_EraseTile(x,y){this.GetSdkIntance().SetTileAt(x,y,EMPTY_INDEX)}_IsTileIndexInBrush(tileIndex,brushData){for(const tileDataItem of brushData.tileData)for(const [index]of tileDataItem)if(index===tileIndex)return true;return false}_SetAutoTilePatch(tx,
                                                                                       ^^^^^^^^^^^

1 error(s), 0 warning(s)
## Expected result

no error message
## More details

**Affected browsers/platforms:** 

**First affected release:** 
works fine in the latest stable r260
## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Browser: Chrome
Browser version: 94.0.4606.54
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36
C3 release: r264 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 2.6 gb (0.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
