### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by virder** [Scirra/Construct-3-bugs#5085]
Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=~~/androidSDK (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
Using Android SDK: ~~/androidSDK
:wrapper

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class java.nio.file.FileSystems$DefaultFileSystemHolder

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 1s
Command failed with exit code 1: ~~/gradlew cdvBuildRelease -b ~~/build.gradle

**Comment by ecations** [comment]
I have the same error since today. Two days ago my build was still succesful.

**Comment by AshleyScirra** [comment]
It looks like there was a brief outage of the build service. Apologies for the inconvenience. It should be back up and running again now.
