### ISSUE TITLE
Next Typewriter doesn't start when the previous one is finished

### ISSUE THREAD

**Issue by eugene-tkachenko** [Scirra/Construct-3-bugs#5087]
## Problem description

Second Typewriter doesn't start when the previous one is actually finished(On typewriter text finished trigger)

## Attach a .c3p

https://fex.net/ru/s/vplxzn1

## Steps to reproduce

1. Add a new text object
2. Add event: text -> typewriter text -> set some text
3. Add trigger On typewriter text finished -> add even text -> typewriter text -> set some text

## Observed result

First text/event is typewrite'd but the second one is not

## Expected result

Expected to see that the second text start typewriting

## More details

But if you add wait event to the 1st place of "On typewriter text finished" - second typewriter starts working. So I think we need to add some minimal delay for "On typewriter text finished" trigger

**Affected browsers/platforms:** 

Chrome

## System details

Windows 10

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
