### ISSUE TITLE
Undo works for particles "Preview" checkbox

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5090]
## Problem description

If you change anything in particles properties, then click Preview checkbox, then press Ctrl-Z to undo your changes, this happens:

![image](https://user-images.githubusercontent.com/36763350/135392235-adcd434d-ed51-49ed-927f-79b8792d4281.png)

## Observed result

Preview checkbox is reverted, not the property that you've changed.
This probably happens with other objects and behaviors (for example Fade) which have Preview checkbox.

## Expected result

Preview checkbox should not be included to the list of actions for Undo.
It's a small issue, but it may cause some problems if you don't pay attention to what the "Undo" message says.
For example, you might change particle rate, preview, don't like the result, press Ctrl-Z and save the project. But in fact the particle rate was not reverted.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 94.0.4606.61
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
C3 release: r260 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 397 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
WEBGL_webcodecs_video_frame
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by eugene-tkachenko** [comment]
I think this is how it intended to work :)

**Comment by dop2000** [comment]
> I think this is how it intended to work :)
Preview is not a property. It makes no sense to undo/redo it.

**Comment by eugene-tkachenko** [comment]
You literally in Properties panel how it's not a property?

**Comment by AshleyScirra** [comment]
I guess it makes sense to not add an undo point for live preview checkboxes, as they don't actually affect how the project works in any way, it's just an in-editor preview option. Changed for next beta.
