### ISSUE TITLE
GL_OUT_OF_MEMORY & GL_INVALID_OPERATION on Chromebook

### ISSUE THREAD

**Issue by FromChris-com** [Scirra/Construct-3-bugs#5091]
## Problem description

Any C3 runtime game, whether via Preview inside the editor or uploaded to a website will crash the chromebook's chrome browser/webgl making the screen go black and producing the attached console errors. Even an entirely empty game, freshly created and upon hitting preview it will crash. See screenshots attached. 

I understand this would probably fall under the crbug.com but, this is only happening with Construct 3 made games. This does not happen with C2 made games, or any other html5 game I'v been able to test on the web. (tested - html5games.com, itch, crazygames). Also the webgl seems to be running fine via testing website, for example the chromebook could handle 60fps with 1000 fish at https://webglsamples.org/aquarium/aquarium.html 

## Attach a .c3p

Any C3 game, project, or preview - including completely new & empty. 

## Steps to reproduce

1. Run any C3 game
2. Crashes to black screen/window  & Errors in console

## Observed result
Black screen - multiple errors in console: 
GL_OUT_OF_MEMORY: glFramebufferTexture2D
GL_INVALID_OPERATION : glFramebufferTexture2D 
GL_INVALID_OPERATION : glCopySubTextureCHROMIUM
CONTEXT_LOST_WEBGL_ loseContext: context lost

## Expected result

Expected the game to run.

## More details

**Affected browsers/platforms:** Chrome on Chromebook: version 93.0.4577.95 (Official Build)(32-bit) , also tried the Beta and Dev, after a Powerwash - but the problem persisted. 

**First affected release:** tested on R260, R265.2, & R182 

## System details

<details><summary>View details</summary>

<html>
<body>
<div style="font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; box-sizing: border-box; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium;"><h3 style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;">Graphics Feature Status</h3><ul style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;"><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">Canvas: </span><span style="box-sizing: border-box; color: rgb(0, 128, 0);">Hardware accelerated</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">Compositing: </span><span style="box-sizing: border-box; color: rgb(0, 128, 0);">Hardware accelerated</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">Multiple Raster Threads: </span><span style="box-sizing: border-box; color: rgb(0, 128, 0);">Force enabled</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">Out-of-process Rasterization: </span><span style="box-sizing: border-box; color: rgb(0, 128, 0);">Hardware accelerated</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">OpenGL: </span><span style="box-sizing: border-box; color: rgb(0, 128, 0);">Enabled</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">Rasterization: </span><span style="box-sizing: border-box; color: rgb(0, 128, 0);">Hardware accelerated</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">Skia Renderer: </span><span style="box-sizing: border-box; color: rgb(128, 128, 0);">Disabled</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">Video Decode: </span><span style="box-sizing: border-box; color: rgb(0, 128, 0);">Hardware accelerated</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">Vulkan: </span><span style="box-sizing: border-box; color: rgb(255, 0, 0);">Disabled</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">WebGL: </span><span style="box-sizing: border-box; color: rgb(0, 128, 0);">Hardware accelerated</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">WebGL2: </span><span style="box-sizing: border-box; color: rgb(0, 128, 0);">Hardware accelerated</span></li></ul></div><div style="font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; box-sizing: border-box; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium;"><h3 style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;">Driver Bug Workarounds</h3><ul style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;"><li style="margin-left: 15px; box-sizing: border-box;">clear_uniforms_before_first_<wbr>program_use</li><li style="margin-left: 15px; box-sizing: border-box;">disable_discard_framebuffer</li><li style="margin-left: 15px; box-sizing: border-box;">disable_program_caching_for_<wbr>transform_feedback</li><li style="margin-left: 15px; box-sizing: border-box;">enable_webgl_timer_query_<wbr>extensions</li><li style="margin-left: 15px; box-sizing: border-box;">exit_on_context_lost</li><li style="margin-left: 15px; box-sizing: border-box;">use_virtualized_gl_contexts</li><li style="margin-left: 15px; box-sizing: border-box;">disabled_extension_GL_KHR_<wbr>blend_equation_advanced</li><li style="margin-left: 15px; box-sizing: border-box;">disabled_extension_GL_KHR_<wbr>blend_equation_advanced_<wbr>coherent</li></ul></div><div style="font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; box-sizing: border-box; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium;"><h3 style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;">Problems Detected</h3><ul style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;"><li style="margin-left: 15px; box-sizing: border-box;"><a style="color: rgb(34, 34, 34); box-sizing: border-box;">Framebuffer discarding causes jumpy scrolling on Mali drivers</a><span style="box-sizing: border-box;">: </span><a href="http://crbug.com/301988" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://crbug.com/301988&amp;source=gmail&amp;ust=1633083993848000&amp;usg=AFQjCNEf4ABt-fr_wKY2qjHf4e_n5QIa7A" style="color: rgb(17, 85, 204); box-sizing: border-box;">301988</a><br style="box-sizing: border-box;"><i style="box-sizing: border-box;"><span style="box-sizing: border-box;">Applied Workarounds: </span><span style="box-sizing: border-box; color: rgb(128, 128, 0);">disable_discard_<wbr>framebuffer</span></i></li><li style="margin-left: 15px; box-sizing: border-box;"><a style="color: rgb(34, 34, 34); box-sizing: border-box;">Clear uniforms before first program use on all platforms</a><span style="box-sizing: border-box;">: </span><a href="http://crbug.com/124764" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://crbug.com/124764&amp;source=gmail&amp;ust=1633083993848000&amp;usg=AFQjCNGPXkqrgQncLl8xMwvw3dCVEXzXbw" style="color: rgb(17, 85, 204); box-sizing: border-box;">124764</a><span style="box-sizing: border-box;">, </span><a href="http://crbug.com/349137" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://crbug.com/349137&amp;source=gmail&amp;ust=1633083993848000&amp;usg=AFQjCNGJ0d5Uaw03puU5RruOZtz3YPMkfw" style="color: rgb(17, 85, 204); box-sizing: border-box;">349137</a><br style="box-sizing: border-box;"><i style="box-sizing: border-box;"><span style="box-sizing: border-box;">Applied Workarounds: </span><span style="box-sizing: border-box; color: rgb(128, 128, 0);">clear_uniforms_<wbr>before_first_program_use</span></i></li><li style="margin-left: 15px; box-sizing: border-box;"><a style="color: rgb(34, 34, 34); box-sizing: border-box;">Disable KHR_blend_equation_advanced until cc shaders are updated</a><span style="box-sizing: border-box;">: </span><a href="http://crbug.com/661715" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://crbug.com/661715&amp;source=gmail&amp;ust=1633083993848000&amp;usg=AFQjCNG1KDn0ba6LRgQyoifrQLRyLdNa1g" style="color: rgb(17, 85, 204); box-sizing: border-box;">661715</a><br style="box-sizing: border-box;"><i style="box-sizing: border-box;"><span style="box-sizing: border-box;">Applied Workarounds: </span><span style="box-sizing: border-box; color: rgb(128, 128, 0);">disable(GL_KHR_<wbr>blend_equation_advanced)</span><span style="box-sizing: border-box;">, </span><span style="box-sizing: border-box; color: rgb(128, 128, 0);">disa<wbr>ble(GL_KHR_blend_equation_<wbr>advanced_coherent)</span></i></li><li style="margin-left: 15px; box-sizing: border-box;"><a style="color: rgb(34, 34, 34); box-sizing: border-box;">The Mali-Gxx driver does not guarantee flush ordering</a><span style="box-sizing: border-box;">: </span><a href="http://crbug.com/678508" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://crbug.com/678508&amp;source=gmail&amp;ust=1633083993848000&amp;usg=AFQjCNFcanDbpdeyr3Y9t_o-bOPzevjHEw" style="color: rgb(17, 85, 204); box-sizing: border-box;">678508</a><br style="box-sizing: border-box;"><i style="box-sizing: border-box;"><span style="box-sizing: border-box;">Applied Workarounds: </span><span style="box-sizing: border-box; color: rgb(128, 128, 0);">use_virtualized_<wbr>gl_contexts</span></i></li><li style="margin-left: 15px; box-sizing: border-box;"><a style="color: rgb(34, 34, 34); box-sizing: border-box;">Program binaries don't contain transform feedback varyings on Mali GPUs</a><span style="box-sizing: border-box;">: </span><a href="http://crbug.com/778871" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://crbug.com/778871&amp;source=gmail&amp;ust=1633083993848000&amp;usg=AFQjCNEjDXGlX50X6vUMMlQwCB_NnD5fNw" style="color: rgb(17, 85, 204); box-sizing: border-box;">778871</a><br style="box-sizing: border-box;"><i style="box-sizing: border-box;"><span style="box-sizing: border-box;">Applied Workarounds: </span><span style="box-sizing: border-box; color: rgb(128, 128, 0);">disable_program_<wbr>caching_for_transform_feedback</span></i></li><li style="margin-left: 15px; box-sizing: border-box;"><a style="color: rgb(34, 34, 34); box-sizing: border-box;">Expose WebGL's disjoint_timer_query extensions on platforms with site isolation</a><span style="box-sizing: border-box;">: </span><a href="http://crbug.com/808744" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://crbug.com/808744&amp;source=gmail&amp;ust=1633083993848000&amp;usg=AFQjCNFpgwLBQzJGVDbsAQZek1W3CrQfMA" style="color: rgb(17, 85, 204); box-sizing: border-box;">808744</a><span style="box-sizing: border-box;">, </span><a href="http://crbug.com/870491" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://crbug.com/870491&amp;source=gmail&amp;ust=1633083993848000&amp;usg=AFQjCNHOcvXXNG9bxJb4I6d4AgAS4zW7PA" style="color: rgb(17, 85, 204); box-sizing: border-box;">870491</a><br style="box-sizing: border-box;"><i style="box-sizing: border-box;"><span style="box-sizing: border-box;">Applied Workarounds: </span><span style="box-sizing: border-box; color: rgb(128, 128, 0);">enable_webgl_<wbr>timer_query_extensions</span></i></li><li style="margin-left: 15px; box-sizing: border-box;"><a style="color: rgb(34, 34, 34); box-sizing: border-box;">Context loss recovery often fails on Chrome OS</a><span style="box-sizing: border-box;">: </span><a href="http://crbug.com/992286" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://crbug.com/992286&amp;source=gmail&amp;ust=1633083993848000&amp;usg=AFQjCNERAYKhFrIE_QlF4QMBvOYXvNpA8A" style="color: rgb(17, 85, 204); box-sizing: border-box;">992286</a><span style="box-sizing: border-box;">, </span><a href="http://crbug.com/1177986" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://crbug.com/1177986&amp;source=gmail&amp;ust=1633083993848000&amp;usg=AFQjCNF2rUNWcO_EcnU6QPs1MaDYz8lMug" style="color: rgb(17, 85, 204); box-sizing: border-box;">1177986</a><br style="box-sizing: border-box;"><i style="box-sizing: border-box;"><span style="box-sizing: border-box;">Applied Workarounds: </span><span style="box-sizing: border-box; color: rgb(128, 128, 0);">exit_on_context_<wbr>lost</span></i></li></ul></div><div style="font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; box-sizing: border-box; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium;"><h3 style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;">Version Information</h3><div id="m_1336410524027715270gmail-client-info" style="box-sizing: border-box;"><div style="box-sizing: border-box;">

Data exported | 2021-09-30T07:31:18.958Z
-- | --
Chrome version | Chrome/93.0.4577.95
Operating system | Linux 14092.66.0
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/8d6327a30ce92ec1b02a5974db563d4265887437/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/8d6327a30ce92ec1b02a5974db563d4265887437/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | aed9405c250d
2D graphics backend | Skia/93 f0a1e4da79c7ffbb06f547b9e0070cf05ddf7122
Command Line | /opt/google/chrome/chrome --use-gl=egl --enable-native-gpu-memory-buffers --platform-disallows-chromeos-direct-video-decoder --enable-webgl-image-chromium --enable-features=Pepper3DImageChromium,UmaStorageDimensions,ArcAdbSideloading,Crostini,SmartDim --num-raster-threads=2 --gpu-sandbox-failures-fatal=yes --gpu-sandbox-start-early --video-capture-use-gpu-memory-buffer --enable-logging --log-level=1 --use-cras --enable-wayland-server --user-data-dir=/home/chronos --device-help-content-id=fennel14 --login-profile=user --has-chromeos-keyboard --enable-touchview --form-factor=CHROMEBOOK --guest-wallpaper-large=/usr/share/chromeos-assets/wallpaper/guest_large.jpg --guest-wallpaper-small=/usr/share/chromeos-assets/wallpaper/guest_small.jpg --child-wallpaper-large=/usr/share/chromeos-assets/wallpaper/child_large.jpg --child-wallpaper-small=/usr/share/chromeos-assets/wallpaper/child_small.jpg --default-wallpaper-large=/usr/share/chromeos-assets/wallpaper/default_large.jpg --default-wallpaper-small=/usr/share/chromeos-assets/wallpaper/default_small.jpg --has-internal-stylus --ozone-nnpalm-properties={} --arc-availability=officially-supported --enterprise-enrollment-initial-modulus=15 --enterprise-enrollment-modulus-limit=19 --enable-crashpad --login-manager --first-exec-after-boot --vmodule=*arc/*=1,*night_light*=1,*/ash/wm/tablet_mode/*=1,wizard_controller=1,*/webui/chromeos/login/*=1,*/browser/ash/login/screens/*=1,enrollment_screen_handler=1,*/browser/ash/login/enrollment/*=1,*/ui/ozone/*=1,*/ui/display/manager/chromeos/*=1 --enable-features=Pepper3DImageChromium,UmaStorageDimensions,ArcAdbSideloading,Crostini,SmartDim --flag-switches-begin --flag-switches-end --ui-compositor-memory-limit-when-visible-mb=512 --silent-launch

</div></div></div><div id="m_1336410524027715270gmail-log-messages" style="font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; box-sizing: border-box; margin-bottom: 1em; color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium;"><h3 style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;">Log Messages</h3><ul style="box-sizing: border-box; margin-bottom: 0px; margin-top: 0px;"><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">2021-09-30T07:17:59.889177Z ERROR chrome[10885:10885]: [gles2_cmd_decoder.cc(8651)] </span>:<wbr> <span style="box-sizing: border-box;">[.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: &lt;- error from previous GL command</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">2021-09-30T07:17:59.903871Z ERROR chrome[10885:10885]: [gles2_cmd_decoder.cc(8651)] </span>:<wbr> <span style="box-sizing: border-box;">[.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: &lt;- error from previous GL command</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">2021-09-30T07:17:59.918948Z ERROR chrome[10885:10885]: [gles2_cmd_decoder.cc(8651)] </span>:<wbr> <span style="box-sizing: border-box;">[.WebGL-0x5673cc00]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: &lt;- error from previous GL command</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">2021-09-30T07:17:59.922569Z ERROR chrome[10885:10885]: [gles2_cmd_decoder.cc(8651)] </span>:<wbr> <span style="box-sizing: border-box;">[.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: &lt;- error from previous GL command</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">2021-09-30T07:17:59.936411Z ERROR chrome[10885:10885]: [gles2_cmd_decoder.cc(8651)] </span>:<wbr> <span style="box-sizing: border-box;">[.WebGL-0x5673cc00]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: &lt;- error from previous GL command</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">2021-09-30T07:17:59.953170Z ERROR chrome[10885:10885]: [gles2_cmd_decoder.cc(8651)] </span>:<wbr> <span style="box-sizing: border-box;">[.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: &lt;- error from previous GL command</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">2021-09-30T07:17:59.957498Z ERROR chrome[10885:10885]: [gles2_cmd_decoder.cc(8651)] </span>:<wbr> <span style="box-sizing: border-box;">[.WebGL-0x5673cc00]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: &lt;- error from previous GL command</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">2021-09-30T07:17:59.957860Z ERROR chrome[10885:10885]: [gles2_cmd_decoder.cc(8651)] </span>:<wbr> <span style="box-sizing: border-box;">[.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: &lt;- error from previous GL command</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">2021-09-30T07:17:59.969027Z ERROR chrome[10885:10885]: [gles2_cmd_decoder.cc(8651)] </span>:<wbr> <span style="box-sizing: border-box;">[.WebGL-0x5673cc00]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: &lt;- error from previous GL command</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">2021-09-30T07:17:59.969808Z ERROR chrome[10885:10885]: [gles2_cmd_decoder.cc(8651)] </span>:<wbr> <span style="box-sizing: border-box;">[.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: &lt;- error from previous GL command</span></li><li style="margin-left: 15px; box-sizing: border-box;"><span style="box-sizing: border-box;">2021-09-30T07:17:59.985252Z ERROR chrome[10885:10885]: [gles2_cmd_decoder.cc(8651)] </span>:<wbr> <span style="box-sizing: border-box;">[.WebGL-0x5673cc00]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: &lt;- error from previous GL command</span></li></ul></div>
</body>
</html>

</details
![CrashReport_1](https://user-images.githubusercontent.com/38993687/135443148-22e5520d-f5d5-451d-9bb6-2e8f5305d182.png)
![CrashReport_2](https://user-images.githubusercontent.com/38993687/135443152-378ca7e9-ac17-40df-a1b6-40845d7b6c92.png)
![webgl_check_1](https://user-images.githubusercontent.com/38993687/135443155-d14fc414-a3fb-479c-b8dd-8b9fdc663bcf.png)
![webgl_check_2](https://user-images.githubusercontent.com/38993687/135443158-ba2b8d3e-5e9a-42e5-918d-668e36a8f245.png)
![emptyGame_console](https://user-images.githubusercontent.com/38993687/135443160-32f96835-8855-46df-9ff6-4b96c9c892f2.png)
![RandomGame_scirraArcade](https://user-images.githubusercontent.com/38993687/135443161-40865b18-6b66-4a8e-9fed-3969f9059d19.png)
>

**Comment by FromChris-com** [comment]
![CrashReport_2](https://user-images.githubusercontent.com/38993687/135443705-7c34177e-adb3-438e-8086-46c2c7be120c.png)
![webgl_check_1](https://user-images.githubusercontent.com/38993687/135443707-c4cba0ce-b8bf-4c09-80cf-530a011bb4b3.png)
![webgl_check_2](https://user-images.githubusercontent.com/38993687/135443709-321019ca-25c6-401d-9281-3d65f2209e0b.png)
![emptyGame_console](https://user-images.githubusercontent.com/38993687/135443710-28dc4194-a608-4610-a0d0-1faf97d0e41f.png)
![RandomGame_scirraArcade](https://user-images.githubusercontent.com/38993687/135443713-ad7e112b-d22c-4c2a-b6eb-a5fdfa297a5c.png)
![CrashReport_1](https://user-images.githubusercontent.com/38993687/135443715-7835f9b8-07e5-490d-8dd7-5f45992c3881.png)

**Comment by AshleyScirra** [comment]
This looks very likely to be a graphics driver problem on the device. It is reporting an error with OpenGL commands carried out by the driver.

I'm afraid this appears to be out of our hands so your best bet is to file it with Google at crbug.com.
