### ISSUE TITLE
Project Folder mostly doesn't open, but sometimes it does.

### ISSUE THREAD

**Issue by aiaicaptain** [Scirra/Construct-3-bugs#5093]
This is the same issue  as : 

https://github.com/Scirra/Construct-3-bugs/issues/4118

...but some more info. I found out that having lots of instances of a particular family is the issue. I will send the project by mail to ashley@scirra.com . My mail is hopeamity@gmail.com.

To reproduce, load the project as a folder based project. Observe that most times it won't load, it will just hang up, infinetly showing the load bar without doing anything. Sometimes, however, it will load. 

New info from last issue:

If you delete the WorldObjects family it will be OK, if you delete most of the layouts that have WorldObjects without deleting the family itself, it would run. Please note that most of the times it won't open, however sometimes it will open like 3 times in a row max. It gives no errors just stops using CPU but the load bar remains bouncing from side to side. 

Because last issue you said it opens 10 out 10 times for you, and I have tested it on many PCs with always the same result - including a Mac, please tell me what more I can do to be helpful...a video? splitscreen? This is somewhat an existencial threat to a project I've been dragging for the last five years.

Thank you

**Comment by aiaicaptain** [comment]
PS. Ok, I also tried deleting all variables the WorldObjects family has.... it has a lot... and it would load then. I know there a lot, but that still doesn't exaplain why it always loads from a single file project.

**Comment by aiaicaptain** [comment]
[layoutissue_2.zip](https://github.com/Scirra/Construct-3-bugs/files/7271536/layoutissue_2.zip)


Ok, here's an new project created specifically for this issue... lots of instances of a single object with lots variables, in many layouts. I can reproduce the issue here as well. I'd figure I'm pushing the engine if it didn't work fine in a single file project. The issue only manifests in folder project.

**Comment by dop2000** [comment]
> layoutissue_2.zip
I tried this project on my laptop (i5, 8GB ram, ssd)
c3p file takes about 2 minutes to load.
The same project as folder - I waited about 15 minutes and it was still loading.

**Comment by AshleyScirra** [comment]
I'm pretty sure this is a bug in Chrome - it looks like sometimes the file operations just hang. I filed an issue with Google here: https://bugs.chromium.org/p/chromium/issues/detail?id=1255611
I can't find a reliable way to work around this. I reduced the throttling we do and made sure more file system operations are throttled, but it still occasionally seems to get stuck opening the project. So it looks like we will have to wait for Google to fix the underlying issue. So closing this issue as we will follow up at the Chrome issue.

I think for the time being you'll have to use a single-file project as a workaround. You can zip a folder project and rename the zip to .c3p, and vice versa (rename .c3p to .zip and extract), as a single file project is actually just a zip of a folder project.
