### ISSUE TITLE
Issue with adding (Tween) behaviour to families/sprites, if some exist already.

### ISSUE THREAD

**Issue by fredriksthlm** [Scirra/Construct-3-bugs#5095]
## Problem description

Some issues with Tween behavior for sprites and families.

1. If I add sprites with Tween to a family, I cannot set Tween behavior to the Family afterwards (it don't exist).

2. If the family only contains sprites without Tween, I can add Tween to the family. But Then I cannot set any Tween to the idividual sprites within family. Since the behavior doesn't exist.

3. If I try to add a sprite with tween to a family that already have Tween I get a pop up saying it dosnt work, since they have a behavior with the same name. If I though first rename the tween name on the individual sprite first, I can add it afterwards.

Why is this a problem? Lets say you have a big family with a lot of members, and you try to set Tween to the family but you then see that Tween doesn't even exist. Then you must manually search and verify which sprite that actually already have the behavior. You must then exclude this sprite from the family, set Tween to the family, then rename the Tween behavior on the individual sprite, and then re add it.
This is the only way to have Tween on the sprite and the family.

One easy solution would be to set the default name to "Tween_Family" or similar when you add behaviors to families, then you would avoid the conflicting names.
But even if you manually rename the behavior to Tween_family on the family, you still cannot add any Tween to any sprites within the family at the moment! The only way is to exclude it, and then add the behavior to the family, and rename the behavior an exclusive name, then re add the sprite... Image if you have a lot of sprites with the behavior already...! 

I understand this might not be a "_bug_" per definition, but it doesnt work really smooth as it is, and is not easy for "beginner users" to even understand how they can manage it. and how to find the behavior when it doesnt exist!

## Steps to reproduce

1. Create a sprite, add Tween behaviour to it.
2. Create a fmaily and add some sprites (include the one with Tween)
3. Try to set Tween behaviour to the Family, it doesn't exist.

## Observed result
You cannot set Tween to a family if any sprite already have it.

## Expected result

I would have expected it to work to add the behaviour, and it automatically got a name like TweenX (where X is a number so it wont conflict with any sprite behaviour)

## More details

**Affected browsers/platforms:** 

**First affected release:** I guess this has been the way it works from the start.

**Comment by AshleyScirra** [comment]
This is currently by design. The Tween behavior can only be added once (as there is no point having multiple Tween behaviors on an object). Make sure you add the Tween behavior to the family, and then all object types in the family can use the family Tween behavior.
