### ISSUE TITLE
Audio Scheduling does not work correctly in Chrome when using web worker

### ISSUE THREAD

**Issue by calminthenight** [Scirra/Construct-3-bugs#5098]
## Problem description

When using the audio scheduling in Chrome with web workers, opening a preview window will regularly fail with error code: STATUS_NOT_IMPLEMENTED.

If it does successfully load, the scheduled audio does not work as intended and is played at random intervals.

The problem does not exist in Firefox, if the C3 debug preview option is used, or if use worker is set to no.

When the preview does not load, Chrome debugger does not connect so no additional info is available. When the preview does load, there are no errors in the Chrome debugger, even as the audio does not play correctly.

## Attach a .c3p

https://editor.construct.net/#open=audio-scheduling

## Steps to reproduce

1. open Audio scheduling example project in Chrome
2. Set Use Worker to Yes
3. Preview the project
4. if the preview opens, play the scheduled audio

## Observed result

Regularly the preview window fails to load and returns error code: STATUS_NOT_IMPLEMENTED.
If it does load the scheduled audio is inconsistent.

## Expected result

The preview window should load every time and the scheduled audio should play in a consistent fashion.

## More details

**Affected browsers/platforms:** 

Chrome on Windows 10

Issue exists in R260 and beyond. Likely exists across prior versions.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 94.0.4606.71
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36
C3 release: r265.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 73 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9365)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
> When using the audio scheduling in Chrome with web workers, opening a preview window will regularly fail with error code: STATUS_NOT_IMPLEMENTED.

I believe this is a sporadic issue with Chrome that affects any project, and isn't specific to this issue. It looks like [crbug.com/1207317](https://bugs.chromium.org/p/chromium/issues/detail?id=1207317).

With worker mode on, the audio scheduling still seems pretty good to me most of the time. I think that worker mode might need an increased buffer time though as it has additional latency as it has to post audio commands from the worker to the main thread. Try increasing the *ScheduleAhead* variable to 0.5. Since this comes down to latency and buffering being slightly different in a worker, I don't think there's any action to take in Construct; the events logic will have to use a bit more buffering. I've updated the Audio Scheduling example for the next release to use a *ScheduleAhead* value 0.5 which should make it more reliable especially given worker mode defaults to on now.

**Comment by calminthenight** [comment]
Increasing the ScheduleAhead time does get the scheduling working correctly, and reduce the number of crashes on load, but limits the use case for scheduled playback in scenarios where instant or near instant start is required. Thanks for identifying the issue. Hopefully the chrome team will get around to it.
