### ISSUE TITLE
DUPLICATE #12 : Layout view "c" shortcut crash when no objects (selected or exist)

### ISSUE THREAD

**Issue by arturosanz** [Scirra/Construct-3-bugs#51]
## Problem description

I was testing the new feature of r16 to center objects in layout, and when I pressed "c" with no objects selected, Construct 3 crashed. It also happens when the layout is empty (no objects).

## Attach a .c3p

The minimal construct 3 project is a new empty project.

## Steps to reproduce

1. Launch Construct 3
2. Menu > Project > New
3. Name the new project and click on "Create"
4. Click on "Layout 1" tab
5. Press "c"

## Observed result

A crash report dialog

## Expected result

I expected nothing to happen

## Affected browsers

* Chrome: yes
* Firefox: browser not supported yet
* Edge: don't know
* Safari: browser not supported yet

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r16/components/editors/layoutView/layoutView.js, line 1, col 48638
Message: Uncaught Error: no selection
Stack: Error: no selection at E.ǃdt (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:48644) at window.ǃUN.ǃej (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:25296) at window.ǃUN.ǃHU (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:16300) at Array.ǃqD.ǃp.ǃqx.ǃp.ǃqH.ǃqR.j (https://editor.construct.net/r16/components/editors/layoutView/layoutView.js:1:3698) at ǃp.Event.ǃWXR.ǃWXG (https://editor.construct.net/r16/main.js:2:283188) at ǃp.ǃd.ǃ$n.ǃW_j.dispatchEvent (https://editor.construct.net/r16/main.js:2:281769) at ǃp.ǃd.ǃ$n.ǃW_j.ǃHU (https://editor.construct.net/r16/main.js:2:324114) at re.ǃHU (https://editor.construct.net/r16/main.js:2:327269) at HTMLDocument.document.addEventListener.Le (https://editor.construct.net/r16/main.js:2:325577)
Construct 3 version: r16
URL: https://editor.construct.net/
Date: Sat Apr 08 2017 22:58:20 GMT+0200 (CEST)
Uptime: 415.7 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: Intel Inc.
Renderer: Intel HD Graphics 3000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 255.875
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_disjoint_timer_query, EXT_frag_depth, EXT_shader_texture_lod, EXT_sRGB, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by jaydonteh** [comment]
Duplicate: https://github.com/Scirra/Construct-3-bugs/issues/12
