### ISSUE TITLE
Add support for drawing plugins in SDK

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#510]
Implement support for plugins which can draw in the Layout View in the plugin SDK.

**Comment by XpMonster** [comment]
Would really like to have it sooner so developers could release their plugins.

**Comment by mOOnpunk** [comment]
Any news on this?

**Comment by AshleyScirra** [comment]
This is now in development. However it's a large API surface and will require a lot of documentation work as well for it to be useful to SDK developers. Then we'll probably need a few iterations to get the API coverage that developers need. So it's in progress but may take some time to get finished.

**Comment by AshleyScirra** [comment]
Closing, see this thread for updates: https://www.scirra.com/forum/drawing-plugins-now-supported-in-r68_t197970

We might be missing a few APIs, so post to the forum about them if you need them, but basic drawing APIs are now available.
