### ISSUE TITLE
Hierarchies are hidden if they're on a Global layer

### ISSUE THREAD

**Issue by Visual917** [Scirra/Construct-3-bugs#5101]
## Problem description

If a layer is global, and you hierarchy some sprites to a sprite on the global layer on a separate layout, the hierarchies are only shown on the original layout of the global layer. 

Layout 1: (The green is on the global layer)
![image](https://user-images.githubusercontent.com/30579752/136556975-4c4a8003-0765-4e44-8bc3-ff6e755fb962.png)

The global layer's layout:
![image](https://user-images.githubusercontent.com/30579752/136556936-922a6e6a-5453-41b8-abb6-c81efd48a1c0.png)

## Attach a .c3p
[Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/7311228/Bug.zip)

## Steps to reproduce

1. Launch the project
2. Click on all of the objects to confirm that they're hierarchied together
3. Check Layout 2

## Observed result

Hierarchy arrows are seen on Layout 2.

## Expected result

Hierarchy arrows should be seen on Layout 1.

## More details

**Affected browsers/platforms:** 
All browsers, this is an editor issue mostly.

**First affected release:** 
It exists on the latest stable and beta as well. Both Browser and NW.JS edition.
## System details

<details><summary>View details</summary>

i7-10750h, RTX 2060, nVME M.2 SSD, 2560x1440, Construct 3 Browser and NW.JS edition.

</details>

**Comment by DiegoScirra** [comment]
How did you manage to produce the second image? I mean the steps to arrive in that state.

I tried removing all links between the instances and setting them up again but no arrows are shown between the  instance in the global layer and the other two. I am thinking there are a few additional things that need to happen in between, but I can't figure out what those should be.

**Comment by DiegoScirra** [comment]
Ok I see, you need to set up the links in a specific order, that's why I wasn't able to see it right away.

**Comment by Visual917** [comment]
Are you able to fix it by the next stable update?

**Comment by DiegoScirra** [comment]
Not for the next beta. but I can tell you the fix for this is not allowing hierarchies between instances in a global layer and instances which are not in a global layer.

The fact you can even do this to begin with, is an oversight.
