### ISSUE TITLE
Firefox - Automatically `focus` search field when creating new Behavior or Effect

### ISSUE THREAD

**Issue by samuelfine** [Scirra/Construct-3-bugs#5104]
## Problem description

When creating a new Event, the Add Description modal automatically focuses the keyboard input on the Search box in the upper right, allowing a user to quickly find a specific object or condition. However, the Add Behavior and Add Event modals do _not_ do this. 

## Attach a .c3p

User Interface issue, applies to all projects

## Steps to reproduce

1. Select an Object or Layout
2. In the Properties pane under Effects, click the `Effects` link to `Add / edit`, then click `Add new effect`

## Observed result

The `Add effect` modal opens, but the Search field in the upper right is does not have keyboard focus. To filter the results, a user needs to click on the search field.

## Expected result

Similar to the improved user experience of the `Add event` modal, I would expect to be able to instantly start typing the name of an Effect or Behavior and have the results filter to only show matches, allowing me to find what I'm looking for more quickly.

## More details

Firefox 92.0.1 for macOS 11.6. Using Chrome 94.0.4606.71, it appears that the Search fields are automatically focused as expected.

**Comment by AshleyScirra** [comment]
Fixed for next beta.
