### ISSUE TITLE
Typo: Preview button text says "undo stack"

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#511]
## Problem description

In Construct 3 editor, when hovering over the arrow next to the "Preview" button the text from the "Undo stack" is shown. 

## Attach an image

http://i.imgur.com/nsgfo9p.png

## Expected result

This is obviously a typo and should say something like "view preview stack" instead.

**Comment by AshleyScirra** [comment]
Duplicate of #494, already fixed for r38!

**Comment by alastajj** [comment]
Thanks! And apologies, I couldn't see that issue in my search (due to their limited details).
