### ISSUE TITLE
Spaces in strings are not accurately shown in Actions on Event Sheet

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#5111]
## Problem description

If an Action has a string (i.e. "Set Text" or "Append Text" for the Text object) with multiple spaces in it, only one space is shown in the event sheet. 

This is a very small bug, but it is a bit of a pain, as the action is misrepresenting its contents.

## Attach a .c3p

https://drive.google.com/file/d/1Rj6TkUeqIIM_-4didJAjoJWFYyPHO3Ug/view?usp=sharing

## Steps to reproduce

1. Open the attached project.
2. Note the single space shown (" ") in the Text object action.
3. Double-click the action, and note true number of spaces in the string ("          ").

## Observed result

The action shows only one space in the string.

## Expected result

The action shows the true amount of spaces in the string. 

![Screen Shot 2021-10-12 at 3 20 12 PM](https://user-images.githubusercontent.com/63005234/137017168-a2184fad-7cc6-4630-8869-cff53283a77d.png)

![Screen Shot 2021-10-12 at 3 20 18 PM](https://user-images.githubusercontent.com/63005234/137017178-843e89a8-2bf5-45e8-95ec-13582a3a1ea9.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** r267

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I think this just needs a change to the CSS white-space property. I've updated it for the next release cycle.
