### ISSUE TITLE
png gradient transparency is not rendered in preview, but displays correctly in remote preview in IOS 

### ISSUE THREAD

**Issue by scottybme** [Scirra/Construct-3-bugs#5112]
png gradient transparency is not rendered in preview, but displays correctly in remote preview in IOS it works as expected on Windows, Android or Macintosh.

png with gradient transparency is not displaying properly in the preview window when run in IOS. This happens in safari or chrome on ipad touch, m1 ipad pro , iPhone 11 , iphone12 all with latest software updates .
 I've gone back to previous versions of construct 3  from 255 with same results.
opening the file from remote preview on same machine works as it should.

## Steps to reproduce

1. open project in preview
2. you will see no shine or glare on ball
3. save file and open in another machine and create remote preview QR code  and scan with original device.
now you can see side by side preview of the ball with and without glare/shine.

## Observed result
no gradient transparency

## Expected result
should display the same on all platforms

## More details

Problem is on Chrome, Safari IOS only, works as it should on other platforms.

**Affected browsers/platforms:** 

**First affected release:** 

## System details
Im running this on ipad touch, ipad pro m1, also tried iPhone 11 , 12 ,13 all with latest software
[Gradient transparency png test.zip](https://github.com/Scirra/Construct-3-bugs/files/7335222/Gradient.transparency.png.test.zip)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Here's a minimal repro:
[gradienttest-minimal.zip](https://github.com/Scirra/Construct-3-bugs/files/7461126/gradienttest-minimal.zip)

It looks like the image with an alpha channel does not render correctly in Safari in local preview (including on macOS, which is an easier way to repro). I suspect this is a Safari bug. It will probably be quite tough to get to the bottom of this.

**Comment by scottybme** [comment]
Hi Ashley
I’m having the same results in Chrome or Safari.

**Comment by AshleyScirra** [comment]
On iOS, Chrome is just a skin around Safari, because Apple ban other browser engines.

**Comment by scottybme** [comment]
Thanks it’s working as it should now .
Thanks , you guys are great!

**Comment by AshleyScirra** [comment]
Thanks for confirming!
