### ISSUE TITLE
3D render mode not working with transparent 2D sprites with effects

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#5121]
## Problem description

Sprites with effects do not render if they have effects and their opacity is not 100% when placed on a 3D layer.

## Attach a .c3p

[3DEffects.zip](https://github.com/Scirra/Construct-3-bugs/files/7358001/3DEffects.zip)

## Steps to reproduce

1. Open the project and take note of the 2 objects on screen. One is 2D and the other is 3D.

2. Press preview

## Observed result

The 2D sprite will not render.

## Expected result

The 2D sprite should render

## More details

r260 stable

If the 2D sprite doesn't have any effects, it will render correctly. Also, if it's set to 100%, it will render fine. The moment it's set to anything other than 99%, it will not render.

Changing the layer's rendering mode from 3D to 2D will fix the issue... and seemingly still produce 3D effects.

**Comment by AshleyScirra** [comment]
r270 ships the new effect compositor which ought to fix this. @4demon - can you verify it is working correctly there?

**Comment by AshleyScirra** [comment]
Pretty sure this is now working as of r270 so closing.
