### ISSUE TITLE
CPU Performance Issues Multiplayer plugin

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#5127]
When adding the Multiplayer plugin to the project, the CPU is very heavily loaded, even in the absence of actions with this plugin. Performance drawdowns are especially felt when exporting to Android, CPU usage increases and fps drawdown appears

## Steps to reproduce

1.Create a new project
2.Run debug and go to CPU profiler, measure Engine/Other readings
3.Add the Multiplayer plugin to the project
3.Run debug and go to CPU profiler, measure Engine/Other readings
## Observed result
https://drive.google.com/file/d/1MQB-RBKdZVSmxlLb8TePP0X_utuZWZ2H/view?usp=sharing
https://drive.google.com/file/d/18X1vT0QxSFOYW5x7Yqnbyh552Q5zQQ5r/view?usp=sharing

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by l-t-m-f** [comment]
I also have performance issues on my game. It used to run 60 fps and now the same project runs 14 fps. I am not using multiplayer.
