### ISSUE TITLE
C3 crashes when I try to preview a game [R37]

### ISSUE THREAD

**Issue by Digital-Prophet** [Scirra/Construct-3-bugs#513]
## Problem description

I open up C3, then i try run either blank or with one single sprite and it crashes. with an error.
I upgraded to Chrome 59.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
[test (2).c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1077119/test.2.c3p.zip)

## Steps to reproduce

1. Open C3
2. Add 1 Sprite 
3. Run Project

## Observed result

Crashes with error box

## Expected result

For it to run 

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r37/exporters/preview/exporter.js, line 1, col 40
Message: Uncaught ReferenceError: ǃE is not defined
Stack: ReferenceError: ǃE is not defined at https://editor.construct.net/r37/exporters/preview/exporter.js:1:40
Construct 3 version: r37
URL: https://editor.construct.net/
Date: Thu Jun 15 2017 11:00:30 GMT+0200 (SAST)
Uptime: 10.9 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.86
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
C3 release: r37

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 650M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2047
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Digital-Prophet** [comment]
It works in Opera 
Browser identification

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) **Chrome/58.0.3029.110** Safari/537.36 OPR/45.0.2552.898

**Comment by shortercode** [comment]
Hi there, we had to re release r37 and it's caused a minor caching issue. Please look at [this](https://github.com/Scirra/Construct-3-bugs/issues/512).

**Comment by shortercode** [comment]
Keeping this open until r38 is released.
