### ISSUE TITLE
Tilemap with Tile Movement collision bugs

### ISSUE THREAD

**Issue by 2dchaos** [Scirra/Construct-3-bugs#5133]
## Problem description

When using Tile Movement's "Set Grid Position To" actions in a Tilemap, these collision bugs happen.

- In this case, the player is repelled by the wall after moving in one wall but not in the other:

![bug_c32](https://user-images.githubusercontent.com/966426/138096339-71834e5a-6324-417c-b251-a9f5dc41a695.gif)

- In this case, the Player get stuck on the wall after moving.

![bug_c33](https://user-images.githubusercontent.com/966426/138096374-c3bee74d-0faf-4d4d-b531-5b59b425a371.gif)
## Attach a .c3p
[Bug_Repro_Tilemap (1).zip](https://github.com/Scirra/Construct-3-bugs/files/7381354/Bug_Repro_Tilemap.1.zip)

## Steps to reproduce

1. Create a Tilemap object with 16x16 tiles, give it the Solid Behavior.
2. Create a Sprite with 32x48 with the Tile Movement Behavior, 16x16 grid.
3. Create an Event that checks if it's possible to move the Sprite and proceeds to move him to the spot if possible.

## Observed result

Depending on the origin and end point, the sprite can either:
- Be repelled
- Land on the correct spot
- Get stuck

## Expected result

- Sprite should move to the correct spot in the grid.
- 
## More details

The OriginX of the sprite seems to go negative when the bug occurs.

**Affected browsers/platforms:** 
Teste on Chrome.

**First affected release:** 
265.2 beta
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 93.0.4577.82
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
C3 release: r265.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 99 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 630M Direct3D11 vs_5_0 ps_5_0, D3D11-23.21.13.9135)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This looks like a mistake in your events. The "Can move to" condition only checks if the destination cell is free, not if the entire path there is clear. It's designed for checking if adjacent cells are free. When standing in the marked location and pressing space, your event logic will identify that a space 4 cells away is clear, even though there is a wall on the way, and attempt to move through it. When it hits the wall, it will stop and move back to a previously clear cell.

To fix this you should make sure your events check all 4 cells are clear before trying to move it 4 cells along.
