### ISSUE TITLE
Construct 3 currently treats whitespaces in properties connected to Cordova plugin variables as empty

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#5146]
Hi there, please review my bug report below. I have tried my best to explain the case, please let me know if there are any missing details. Thank you.

## Problem description

Construct 3 currently treats whitespaces in properties connected to Cordova plugin variables as empty.

The Construct 3 mobile exporter currently does not allow Cordova plugin variable properties with whitespaces. 

Whitespace values are intentionally used for loading default variable values in Cordova. However, if the `Optional Property` below is inputted with a whitespace, the Construct 3 editor launches a requirement dialog in the 2nd image, after export.

**[1]** Addon property connected to a Cordova plugin variable.
![image](https://user-images.githubusercontent.com/31282960/138566317-78e60fc6-7d6d-454e-aded-c4dbf82deaaa.png)

**[2]** Error after export, even when there is a whitespace in the optional property.
![image](https://user-images.githubusercontent.com/31282960/138566391-1fb76f88-4e79-4f72-90a6-f5843cfaafab.png)

## Request 

Please allow whitespaces to be inputted in properties connected to Cordova plugin variables, to allow export to Android or iOS, where whitespaces are intendedly used to load default values, which is a typical practice done with Cordova. 

## Reasoning

There are cases when Cordova plugins need optional values, and since the Cordova CLI require all variables to be filled, plugin developers write whitespaces as `default` values to differentiate actual user values and ignored values, e.g. internally when `--variable` is not declared.

Just for the record, it is done through `default`, for e.g.:
```
<preference name="MY_OPTIONAL_PROPERTY" default=" " />
```
Which I then implement from the addon side as:

![image](https://user-images.githubusercontent.com/31282960/138567730-304164da-3ab1-4c5a-9591-8c868140519e.png)

However, in Construct 3 all Cordova plugin variable properties are treated as mandatory values. To prevent this, may I request to allow inputting of whitespaces to load default values?

## Further reasoning

It is very important to have optional Cordova plugin variables since service providers develop their SDKs with optional parameters, and our only current option right now is either to rule a parameter out or make it mandatory, which I know you understand how it cannot be always applicable. 

## Attach a .c3p

[Addon + Project.zip](https://github.com/Scirra/Construct-3-bugs/files/7403426/Addon.%2B.Project.zip)

## Steps to reproduce

1. Install the `Construct.c3addon`.
2. Open the `Construct 3.c3p`project.
3. Click the `Construct 3` object (plugin), and look at its properties on the properties bar.
4. Focus your attention to the `Optional Property` and observe that there is a single whitespace used as the value.
5. Export to Android.
6. Please observe the result.

## Observed result

Whitespaces for Cordova plugin variable properties are considered empty parameters. **[2]**
![image](https://user-images.githubusercontent.com/31282960/138566391-1fb76f88-4e79-4f72-90a6-f5843cfaafab.png)

## Expected result

Whitespaces allowed for Cordova plugin variable properties.
Then, successful export to Android.

**Comment by AshleyScirra** [comment]
Updated next beta to allow all-whitespace Cordova plugin variables.
