### ISSUE TITLE
Crash and Restart popup  when selecting Audio Plugin in events

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#515]
## Problem description

*I just selecting Audio in eventsheet for example I do start of the layout and then in action adding action selecting audio then i am getting this error each time
I have updated software already. I have try to restart browser and tries so many times but same thing is happening and This was coming after the updating Construct to the latest version. Because I have used Audio last day with not bug*
Bug report pasted below

## Attach a .c3p

*No file needed*

## Steps to reproduce

1. Open New File
2. Insert Audio Plugin
3. do something in event sheet to select audio plugin 

## Observed result

*Restart Popup*

## Expected result

*it should work*

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r38/main.js, line 2, col 203281
Message: Uncaught Error: missing dialog element with class name: nextButton
Stack: Error: missing dialog element with class name: nextButton at ǃT.ǃTp.ǃTI.ǃUlx.ǃXE (https://editor.construct.net/r38/main.js:2:311413) at ǃT.ǃTp.ǃTI.ǃUlx (https://editor.construct.net/r38/main.js:149:83516) at Function.ǃT.ǃP (https://editor.construct.net/r38/main.js:2:203260) at Function.ǃVhf (https://editor.construct.net/r38/main.js:2:302933) at Function.ǃZG (https://editor.construct.net/r38/main.js:2:310473) at ǃT.ǃTp.ǃTI.ǃUle.ǃXp (https://editor.construct.net/r38/main.js:149:80781) at ǃT.ǃTp.ǃTI.ǃUle.ǃCF (https://editor.construct.net/r38/main.js:149:80536) at Array.ǃTOy.addEventListener (https://editor.construct.net/r38/main.js:149:78353) at ǃT.Event.ǃVkY.ǃVk_ (https://editor.construct.net/r38/main.js:2:254590) at ǃT.ǃTp.ǃTI.ǃTps.dispatchEvent (https://editor.construct.net/r38/main.js:2:253244)
Construct 3 version: r38
URL: https://editor.construct.net/
Date: Thu Jun 15 2017 18:45:32 GMT+0530 (India Standard Time)
Uptime: 13 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
C3 release: r38

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce 210 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Is this fixed in r38.2?

**Comment by luckyrawatlucky** [comment]
No
I got this problem just before 2 hours and may be that was 38.2
I have reverted my version back to 37 and its working

On 15 Jun 2017 10:30 p.m., "Ashley (Scirra)" <notifications@github.com>
wrote:

Is this fixed in r38.2?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Scirra/Construct-3-bugs/issues/515#issuecomment-308803867>,
or mute the thread

**Comment by AshleyScirra** [comment]
Crash report matches the issue in r38 which was fixed in r38.2, so closing.
