### ISSUE TITLE
CPU Performance Issues Multiplayer plugin

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#5152]
When adding the Multiplayer plugin to the project, the CPU is very heavily loaded, even in the absence of actions with this plugin. Performance drawdowns are especially felt when exporting to Android, CPU usage increases and fps drawdown appears.

If this cannot be fixed, then add the ability to disable the multiplayer plugin when necessary through events.

## Attach a .c3p

.c3p : https://drive.google.com/file/d/1wOfFp426yqcUmD4c8m1GDr-cyEnYvf7Z/view?usp=sharing
apk without Multiplayer : https://drive.google.com/file/d/17axMJqp2BKxvfCNVVVjL6uwiy55htQD8/view?usp=sharing
apk from Multiplayer : https://drive.google.com/file/d/1dozZOYZTXa4jIg4NfqyYRnvdvMnyg-2r/view?usp=sharing
## Steps to reproduce

I created 2 android apks, one without the multiplayer plugin, the second with the multiplayer plugin.

1. Install two apks on your phone.
2. Measure the CPU load.

My phone number:
Samsung Galaxy S10 Lite SM-G770F/DS 6GB/128GB

Qualcomm Snapdragon 855
Processor clock speed 2,840 MHz
Number of cores 8 (1+3+4 )
Kryo 485 2840 MHz + Kryo 485 2420 MHz + Kryo 485 1800 MHz

Graphics Accelerator
Adreno 640

CPU usage increases by an average of 15-20% when using the multiplayer plugin.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Once again, you are merely measuring throttling effects on the CPU. The provided project does not do nearly enough to fully load the CPU. So it will remain in a low power state and produce misleading CPU results.

With the provided project using remote preview on a Pixel 3, without multiplayer it measures ~12% CPU, and with multiplayer it measures ~21% CPU. This looks like a big difference, but it is not. A few rotating sprites is a tiny amount of work for the CPU. Adding the Multiplayer object adds another tiny amount of work for the CPU. In an artificially slow low-power mode, you can measure this tiny difference.

A better test is the 'Quad issue performance' benchmark. That really does fully load the CPU. Running that without multiplayer reaches 98305 sprites @ 30 FPS on my Pixel 3. If I drop in the Multiplayer plugin and re-run the test, it measures 98305 sprites @ 30 FPS - exactly the same.

This is proof that the Multiplayer object actually adds a negligible amount of CPU work and you are only measuring throttling effects.

**Comment by ibiz3091** [comment]
@AshleyScirra I realized that you cannot be persuaded, let it be according to you, I have already written that the deterioration in the performance of my game is visible without any performance counters, it is noticeable by the eye. I ask you to add the ability to disable the multiplayer plugin from the event sheet.

**Comment by AshleyScirra** [comment]
My benchmark showed no difference at all. Maybe it depends on the device, but even your results only show a small difference (~7%), and the test itself isn't always very accurate and can vary by ~5% from run to run. So it may just be variance in the run, and even so, it should not cause more than 7% impact. I've also looked at the source code. Multiplayer does virtually nothing when running on its own. So I am pretty sure there is something else that is really affecting performance and the real cause has been mis-attributed, which is easy to do and very common.

**Comment by ibiz3091** [comment]
@AshleyScirra As a developer, you understand that nothing should work for optimization when it is not required. Why does the plugin perform actions when nothing happens?

**Comment by AshleyScirra** [comment]
Because it makes it simpler, and simpler code is more reliable. All software development is trade-offs.
