### ISSUE TITLE
Exported projects do not start on r269

### ISSUE THREAD

**Issue by BeauTheBeau** [Scirra/Construct-3-bugs#5159]
## Problem description

Exported projects do not start 

## Attach a .c3p

[project.zip](https://github.com/Scirra/Construct-3-bugs/files/7421408/project.zip)

## Steps to reproduce

1. Export
2. Run the exported project

## Observed result

Does not start, blank screen only accompanied by an error

![image](https://user-images.githubusercontent.com/90942493/138958240-daccc769-1cbf-4c19-ba22-4519d1e4a8d2.png)

## Expected result

Project would start as normal and load 

## More details

**Affected browsers/platforms:** 

Latest versions of MS Edge, Chrome and Firefox on Windows

**First affected release:** 

Worked on r268, no longer working on r269

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 95.0.1020.30
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36 Edg/95.0.1020.30
C3 release: r269 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 282 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 1030 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7196)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by ahmed3DMindd** [comment]
> @ahmed3DMindd
> 
> > Unfortunately, this will expose me to a great loss, especially since the project I am working on has a specific deadline. I do not think this solution may be suitable (just wait for next **week's** beta release ), especially for those who use this application in real business not just for fun.
> 
> Well, to be fair, it's probably not the best idea to use beta versions of software if it's your business. Beta gives you early access in exchange for risk.

unforgettable lesson

**Comment by Wackytoaster** [comment]
Heh, I see this is already worked on :) Don't think it matters but just in case, this also happens with NW.js exports but I suppose it's the same fix.

@ahmed3DMindd in 99% of cases you can fall back to a version of construct that works.
https://www.construct.net/en/tutorials/open-project-saved-newer-2203

**Comment by AshleyScirra** [comment]
Should now be fixed in r270.
