### ISSUE TITLE
Crash when adding event

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#516]
## Problem description

Attempted to add an event with newly created sprite.  I created a new sprite, gave it an instance variable then attempted to create an event using it and the program crashed.

## Attach a .c3p

[Bitmen.zip](https://github.com/Scirra/Construct-3-bugs/files/1077736/Bitmen.zip)

## Steps to reproduce

1. Open the project
2. Add event on the Title Screen event page
3. Select the sprite "Selector"

## Observed result

App crashes

## Expected result

Event menu displayed

## Affected browsers

* Chrome: yes

## System details
Error report information
Type: unhandled exception
File: https://editor.construct.net/r38/main.js, line 2, col 203281
Message: Uncaught Error: missing dialog element with class name: nextButton
Stack: Error: missing dialog element with class name: nextButton at ǃT.ǃTp.ǃTI.ǃUlx.ǃXE (https://editor.construct.net/r38/main.js:2:311413) at ǃT.ǃTp.ǃTI.ǃUlx (https://editor.construct.net/r38/main.js:149:83516) at Function.ǃT.ǃP (https://editor.construct.net/r38/main.js:2:203260) at Function.ǃVhf (https://editor.construct.net/r38/main.js:2:302933) at Function.ǃZG (https://editor.construct.net/r38/main.js:2:310473) at ǃT.ǃTp.ǃTI.ǃUle.ǃXp (https://editor.construct.net/r38/main.js:149:80781) at ǃT.ǃTp.ǃTI.ǃUle.ǃCF (https://editor.construct.net/r38/main.js:149:80536) at Array.ǃTOy.addEventListener (https://editor.construct.net/r38/main.js:149:78353) at ǃT.Event.ǃVkY.ǃVk_ (https://editor.construct.net/r38/main.js:2:254590) at ǃT.ǃTp.ǃTI.ǃTps.dispatchEvent (https://editor.construct.net/r38/main.js:2:253244)
Construct 3 version: r38
URL: https://editor.construct.net/
Date: Thu Jun 15 2017 09:19:09 GMT-0400 (Eastern Daylight Time)
Uptime: 349.1 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.24
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.24 Safari/537.36
C3 release: r38

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by UncleHo74** [comment]
Same here. Adding an event, crash with "... Message: Uncaught Error: missing dialog element with class name: nextButton ". Tried my offline C3 version and the online version, both with the same error since r38.

**Comment by 8bitThirsty** [comment]
I also tried clearing my cache and using chrome incognito mode in case it was a duplicate of the cache issue I ran into yesterday but that didn't help.

**Comment by luckyrawatlucky** [comment]
same "The next button" i am getting

**Comment by NetOneGames** [comment]
Yep same. ( on Android)

Create sprite, goto events,  create event,  boom... Crash.... Repeatable every time.....

Error report information
Type: unhandled rejection
Reason: Error: missing dialog element with class name: nextButton @ Error: missing dialog element with class name: nextButton at ǃT.ǃTp.ǃTI.ǃUlx.ǃXE (https://editor.construct.net/r38/main.js:2:311413) at ǃT.ǃTp.ǃTI.ǃUlx (https://editor.construct.net/r38/main.js:149:83516) at Function.ǃT.ǃP (https://editor.construct.net/r38/main.js:2:203260) at Function.ǃVhf (https://editor.construct.net/r38/main.js:2:302933) at Function.ǃZG (https://editor.construct.net/r38/main.js:2:310473) at d (https://editor.construct.net/r38/main.js:149:81628) at n (https://editor.construct.net/r38/main.js:149:81409) at t (https://editor.construct.net/r38/main.js:149:81293) at n.then (https://editor.construct.net/r38/main.js:149:81350) at 
Stack: Error: missing dialog element with class name: nextButton at ǃT.ǃTp.ǃTI.ǃUlx.ǃXE (https://editor.construct.net/r38/main.js:2:311413) at ǃT.ǃTp.ǃTI.ǃUlx (https://editor.construct.net/r38/main.js:149:83516) at Function.ǃT.ǃP (https://editor.construct.net/r38/main.js:2:203260) at Function.ǃVhf (https://editor.construct.net/r38/main.js:2:302933) at Function.ǃZG (https://editor.construct.net/r38/main.js:2:310473) at d (https://editor.construct.net/r38/main.js:149:81628) at n (https://editor.construct.net/r38/main.js:149:81409) at t (https://editor.construct.net/r38/main.js:149:81293) at n.then (https://editor.construct.net/r38/main.js:149:81350) at 
Construct 3 version: r38
URL: https://editor.construct.net/index.html
Date: Thu Jun 15 2017 14:40:50 GMT+0100 (BST)
Uptime: 31 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.20
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Android
Operating system version: 5.1.1
Operating system architecture: 32-bit
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: 4
User agent: Mozilla/5.0 (Linux; Android 5.1.1; D5503 Build/14.6.A.1.236) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.20 Mobile Safari/537.36
C3 release: r38

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: Qualcomm
Renderer: Adreno (TM) 330
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_disjoint_timer_query, EXT_sRGB, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_atc, WEBKIT_WEBGL_compressed_texture_atc, WEBGL_compressed_texture_etc1, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

**Comment by UncleHo74** [comment]
Makes me wonder what to do later when we're out of the beta period.. is there a way to go back to a "previous" C3 version? Or will there be multiple branches, stable, beta and so on?

**Comment by 8bitThirsty** [comment]
Seems to be fixed with r38.2

**Comment by AshleyScirra** [comment]
Should be fixed in r38.2 now.
