### ISSUE TITLE
Layout editor's backround graphic glich

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#5164]
## Problem description

Layout editor's backround has a graphic glich. It is black (might has a wrong offset). It might be a video driver bug (Xiaomi mi 9t) because I tried in other android systems (android x86, xiaomi redmi 6a) and it is works correctly.

## Attach a .c3p

In editor

## Steps to reproduce

1. Open project
2. Move the zoom in layout editor
3. Black backround

## Observed result

Black background

## Expected result

Normal background color

## More details

https://user-images.githubusercontent.com/47735877/139088982-7a772ed4-589c-4565-9116-de8625c270bc.mp4

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 94.0.4606.85
Browser engine: Chromium
Context: browser
Operating system: Android
Operating system version: 11
Device type: mobile
Device pixel ratio: 2.75
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 11; Mi 9T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 Mobile Safari/537.36
C3 release: r269 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 121 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Qualcomm
Renderer: Adreno (TM) 618
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think I've seen this before, but it doesn't seem to reproduce in r269 on my Pixel 3. I suspect it's a graphics driver bug, as the background color is simply a full-surface clear, and it works on other devices.

We've made several changes to the way the renderer works in r270, does it work any better there?

**Comment by henrikszucs** [comment]
r270 has the same glitch. Yes I think it is a device specific chrome driver bug. In Mozilla Firefox the editor works well. I think you can close this issue.

**Comment by AshleyScirra** [comment]
Yeah, I'm afraid it sounds a lot like a driver bug, which also means it's probably infeasible to do anything about it. You could try reporting it to Google, but it will be tough as they'd most likely ask for a minimal repro. Closing as there doesn't seem to be any action we can take ourselves over this.
