### ISSUE TITLE
Project folders with search results collapse when changing tabs

### ISSUE THREAD

**Issue by ReflextionsDev** [Scirra/Construct-3-bugs#5168]
## Problem description

When changing tabs in Construct, folders set to collapse will do so when changing tabs, even with a search query. 

## Attach a .c3p

Empty project

## Steps to reproduce

1. Create new project
2. Search for '3' in the project folder
3. Navigate to Event Sheet 1
4. Observe the 'Icons' folder is now collapsed, rendering icon-32.png hidden

## Observed result

The folder containing search results is collapsed

## Expected result

Search results should remain visible, even while switching tabs

## More details

I'm not sure if this is expected behavior but it's really cumbersome when you search for an object, then go to a different layout / event sheet to modify something and have to redo your search.

**Comment by AshleyScirra** [comment]
Should be fixed in next beta.
