### ISSUE TITLE
Custom JSON Doesn't Load on Reload

### ISSUE THREAD

**Issue by hinklefoxmail** [Scirra/Construct-3-bugs#517]
## Problem description

When you edit a custom JSON file using the text editor the first time you load the project it will load and everything will work fine. Upon reloading the project AJAX will not retrieve the file and AJAX.LastData will remain blank. 

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
[Goolge drive Link](https://drive.google.com/file/d/0B3drqUikE3kuVFMwY2ktTUtERDQ/view?usp=sharing)
## Steps to reproduce

1. Use a custom JSON script with the text editor
2. Open the project
3. Close the project and open it again or click reload in debug mode

## Observed result

File data is not retrieved. AJAX.LastData remains empty

## Expected result

File Loads

## Affected browsers

* Chrome: yes

## System details
Mac OS X

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here in r38.2: it loads fine every time, either by preview, close and preview again, or by debug and repeatedly clicking "restart".

Please always include your full system details as requested, since it includes your Construct 3 version and allows me to verify you are using the latest version.
