### ISSUE TITLE
Ios and android build failed

### ISSUE THREAD

**Issue by listpull** [Scirra/Construct-3-bugs#5171]
ios and android build either fail or timeout.

Error: Platform 'android' found in config.xml... Migrating it to package.json
Discovered platform "android". Adding it to the project
Using cordova-fetch for cordova-android@10.1.0

Failed to fetch platform cordova-android@10.1.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform ~~/URL.
CordovaError: Error: npm: Command failed with exit code null

n/a

try to export an android or ios build

1.
2.
3.

## More details

Chrome/Firefox/Safari, Windows/macOS/Android

**First affected release:** 

 worked in r268 yesterday 24 hours prior

<details><summary>View details</summary>

Error: Platform 'android' found in config.xml... Migrating it to package.json
Discovered platform "android". Adding it to the project
Using cordova-fetch for cordova-android@10.1.0

Failed to fetch platform cordova-android@10.1.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform ~~/URL.
CordovaError: Error: npm: Command failed with exit code null
</details>

**Comment by samratshamim** [comment]
> Not sure what happened but I just rebooted the build server and it looks like it's working again.

The same problem is happening again. I have been trying to build 3 projects for 4 hours now. Every time it's taking really long than expected and finally returning timeout. 

You might have to restart the server again as you did before.

**Comment by portugalcsm** [comment]
Please reboot the build server...
<img width="1168" alt="Screenshot 2023-05-13 at 01 15 46" src="https://github.com/Scirra/Construct-bugs/assets/42272385/82f043cd-7fb7-4a5e-9742-a990027e5393">
