### ISSUE TITLE
Picking doesn't work if the object was created during the same frame

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5178]
## Problem description

I need to spawn 10x object A, then spawn 1x object B on a random A instance. Using Pick Random Instance didn't work until I separated the two spawn functions with a Wait(0) action.

## Attach a .c3p

[Test Pick.zip](https://github.com/Scirra/Construct-3-bugs/files/7451717/Test.Pick.zip)

## Steps to reproduce

1. Run the attached project.
2. Notice there are no Blue sprites.
3. In Line 3, enable the Wait action.
4. Run the project.

## Observed result

Blue sprites appear only after waiting.

## Expected result

Blue sprites should appear without waiting; since the Red sprites have been already created.

**Comment by Wackytoaster** [comment]
That's normal as created objects are not available until the next tick. However, there is a specific action to solve this issue. I guess it's a quirk of the engine.
![tick](https://user-images.githubusercontent.com/31101309/139667324-6811766f-78e6-43f5-a07a-6523eb1aa5ec.PNG)

**Comment by AshleyScirra** [comment]
This is a long-standing known limitation of the event system which is in place for complicated technical reasons: newly created instances can be picked by their own event, but are not fully created until the end of the next top-level event (in this case after 'On start of layout'). Given this rule, you can also work around it by calling 'Spawn2' in a second 'On start of layout' trigger.

**Comment by Alaadel** [comment]
Thank you!
It would be nice if there is a hint to this behavior in the documentation. It will help minimize confusion of future users.
