### ISSUE TITLE
Tilemap window crops the tilemap's height to its width

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#5179]
When a Tilemap object is selected, the tiles are drawn in the Tilemap window. However, once the mouse is moved over the Tilemap window, some of the tiles disappear.

It appears that the tilemap width value is used as its height.

## Attach a .c3p

https://drive.google.com/file/d/1cBAf-Cg13F1xog4yKKzRsf2uSMMJLUbE/view?usp=sharing

## Steps to reproduce

1. Open the attached project.
2. Select the tilemap object.
3. Move the mouse over the tilemap window.
4. Note that some tiles in the tilemap window disappear.

To see how the Tilemap's width plays a role:
1. Double-click the tilemap object to open it in the Animation Editor.
2. Change the width to 128 (leave the height as is)
3. Close the tilemap editor
4. Move the mouse over the tilemap window.
5. Note that even more tiles disappear. 

## Observed result

Tiles that exist in the tilemap file, at a height larger than its width value, disappear from the Tilemap window.

Video of the error: https://gfycat.com/apttinyfalcon

## Expected result

All tiles are visible when moving the mouse over to select them.

## More details

**Affected browsers/platforms:** Chrome 95

**First affected release:** r269

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Does this still reproduce in r270? It includes a fix which sounds similar:

> Tilemap bar: tileset image not displayed properly (regression r269)

**Comment by brushfe** [comment]
Looks like it's fixed! Thanks very much!

**Comment by AshleyScirra** [comment]
Thanks for confirming!
