### ISSUE TITLE
Dialog Sizes and positions are not remembered after closing and opening a C3 project

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#518]
## Problem description

The size of the dialog windows are not the same after you save your project, then close C3 editor then open it and the project again. All of the dialog windows are "brand new" in the default size and positions, it has forgotten how you sized and positioned everything!

(My main project also doesn't remember the resizing of event sheets, but I'm yet to be able to figure out how to duplicate that issue unfortunately.)

This problem was mentioned previously but unaddressed here by @JeFawk: https://github.com/Scirra/Construct-3-bugs/issues/447

This was not an issue in Construct 2.

## Attach a .c3p

[memory.zip](https://github.com/Scirra/Construct-3-bugs/files/1079757/memory.zip)

## Steps to reproduce

1. Open the .c3p
2. Preview the game with dialog setting (the one that works the best)
3. Resize the Preview dialog and close it
4. Go to the event sheet and open an action
5. Resize the expression dictionary dialog
6. Edit a value and save the project 
7. Close the program
8. Open the program and project again
9. Preview the game again
10. Check the expression dictionary size again

## Observed result

The dialog windows are the default sizes and positions.

## Expected result

They should be how I left them before when I saved the project then closed the program.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r38.2

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 159 mb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Is this affecting all the dialogs or the expressions dictionary only?

**Comment by alastajj** [comment]
The most frustrating one that is affected is the Preview Dialog. But from what I've seen all event sheet dialogs are affected too. I didn't notice it affect things like the Animation Editor.

**Comment by shortercode** [comment]
Looks like it was broken around 10 days ago, each dialog is resetting it's position the first time it's opened per page load. Fixing it at the moment so it should appear in r39.

Worth noting that some dialogs don't actually persist by design, like the **progress** dialog. This is generally because they are used in lots of different places so it doesn't make sense to remember it.

**Comment by shortercode** [comment]
Fixed and awaiting release.
