### ISSUE TITLE
Request: Allow uninstalling bad addons

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5180]
## Problem description

I installed a broken addon and got this message:

![image](https://user-images.githubusercontent.com/36763350/139779379-5bf60392-0afe-428a-852b-ab0bae98a6e9.png)

I wanted to uninstall the addon, but Construct locked up and the Menu button was disabled. 
I ended up clearing browser storage and lost a lot of time re-installing dozens of other addons.

Can you please make the Addon Manager accessible when this happens, so that we could uninstall bad addons?
Or is there another way to remove just one particular addon from browser storage?

**Comment by henrikszucs** [comment]
I think you can start in safe mode: https://editor.construct.net/r261/?safe-mode
https://www.construct.net/en/make-games/manuals/addon-sdk/guide/safe-mode

**Comment by dop2000** [comment]
@henrikszucs  Thanks, didn't know about it!
