### ISSUE TITLE
Objects with multiple effects disappear on zoom in/out 

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#5182]
Objects aren't drawn in the layout editor after zoom inputs if they have effects applied to them.

## Attach a .c3p

https://drive.google.com/file/d/1j9JwntK0TIwUICJlIiBvJLeCd5bGmprm/view?usp=sharing

## Steps to reproduce

1. Open the layout in the attached project.
2. Zoom out with cmd-
3. Note all but the first tilemap disappears.
4. Zoom in with cmd+
5. Note the tilemaps return to view.

To see the impact of the effects:
1. Open the attached project.
2. Delete the three effects from the Tilemap family.
3. Zoom in and out as above.
4. Note the tilemaps render properly.
5. Also note the performance of the editor increases greatly.

## Observed result

• All but the first tilemap objects are not rendered. 
• The amount you have to zoom in to render properly gets higher the more you zoom in/out of the layout. 
• The editor also slows down considerably when these objects have their effects applied. 

## Expected result

• The tilemaps to render properly and at any zoom.
• No slowdown in the editor.

Note: This project may look like a useless 'stress-test' but it is a sample of a game I've been developing, with this amount of tilemaps per layout, each with three effects (to change their shadow, midtone, and highlight). Up until 270, C3 has had no issue rendering or displaying these objects and more. 

## More details

**Affected browsers/platforms:** Chrome 95.0.4638.69 on MacOS 11.6

**First affected release:** Started in 270

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by dupuqub** [comment]
I also experienced objects failing to show up on the editor when they have effects applied to them.
In my case, zoom is a non-issue, they just never show up on the editor at all.
it also begun in r270.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next release.
