### ISSUE TITLE
Crash when disabling certain effects in stack (r270 new effects compositor)

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#5183]
## Problem description

If the "Replace Solid Color" effect is placed _after_ a different effect, then disabling that effect crashes the game and results in this error:
![image](https://user-images.githubusercontent.com/36490901/139951118-e23341fa-6dd3-4b57-b1f6-770810719aaf.png)
This might extend to other color shaders as well.

I am also getting this related error in my game since updating to r270 but I am having a very difficult time reproducing it in a new .c3p:
![image](https://user-images.githubusercontent.com/36490901/139951700-e8b606e0-8d6a-4dc6-bc6b-16969cc151a9.png)

## Attach a .c3p
[ShaderError.zip](https://github.com/Scirra/Construct-3-bugs/files/7464004/ShaderError.zip)

## Steps to reproduce

1. Just preview the project and observe the error in the console.

## Observed result

Crash & error

## Expected result

No crash or error

## More details

**Affected browsers/platforms:** Chrome & nw.js

**First affected release:** r270

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by brushfe** [comment]
I'm seeing the second crash in my project as well. There's definitely some strange stuff going on with the order of effects and ReplaceSolidColor.

You can see that second error in this file here. Just press a key and it appears:
https://drive.google.com/file/d/1FolSbaXxX2RM7JPOaHufM3AF3SnA52gh/view?usp=sharing

**Comment by AshleyScirra** [comment]
Thanks for the report - it turns out the new effect compositor does not handle effect parameters correctly after a disabled effect. It should be fixed in the next beta.
