### ISSUE TITLE
Disabling ReplaceSolidColor effects only disables the lowest enabled effect on the list

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#5187]
## Problem description

When a sprite has multiple ReplaceSolidColor effects, each effect can't be disabled until the lowest effect on the list are disabled. Trying to disable an effect _before_ the effects below it are disabled will only disable the lowest enabled effect.

## Attach a .c3p

https://drive.google.com/file/d/1fzT18QWzW67OBxt_bsdRWWBy4n9Kbfbb/view?usp=sharing

## Steps to reproduce

1. Open the attached project.
2. Note the ReplaceSolidColor effect 'Green' is the bottom effect on the sprite's list of effects. 
3. Preview the project.
4. Press 1 to disable the Grey highlight. Only the Green highlight is disabled.
5. Press 1 to enable it again.
6. Press 2 to disable the Blue highlight. Only the Green highlight is disabled.
7. Press 2 to enable it again.
8. Press 3 to disable the Green highlight. Now it is now correctly disabled (since Green is the lowest enabled effect on the list)

9. Now that the Green highlight is disabled, press 1 to disable Grey again. Note now only the Blue highlight is disabled (since Blue is now the lowest enabled effect on the list).
10. Press 1 to enable it again.
11. Press 2 to disable the Blue highlight again. Now it is now correctly disabled.

12. Now that the Green and Blue highlight are disabled, press 1 to disable the Grey highlight. Now it is correctly disabled (since Grey is now the lowest enabled effect on the list).
13. Press 3 to enable to the Green highlight. Note that only the Grey highlight is disabled. 

14. Pressing 4 enables/disables all effects at once, which works correctly, if that's helpful.

## Observed result

Only the lowest enabled ReplaceSolidColor effect on the list can be enabled/disabled.

## Expected result

Any ReplaceSolidColor effect should be enabled/disabled on command.

## More details

**Affected browsers/platforms:** Chrome 95, MacOS 11.6

**First affected release:** 270, works correctly in prior versions

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I think this is the same issue as #5183: the new effect compositor basically mixes up effect parameters after the first disabled effect. This causes a crash in the other issue, but this project doesn't crash and instead shows the parameters getting mixed up. The fix for #5183 looks like it also fixes this, so it should also be working in the next release.

**Comment by brushfe** [comment]
Great news, thank you very much!
