### ISSUE TITLE
xcode export does not work - app freezes in c3 splash screen 

### ISSUE THREAD

**Issue by driesdriessen** [Scirra/Construct-3-bugs#519]
## Problem description
app exported to IOS (Cordova) and built via xcode does not work. The app freezes during the c3 load screen with progress bar at 70%

## Attach a .c3p
The Cordova export:
[Battle at Ras El Hanout.cordova.zip](https://github.com/Scirra/Construct-3-bugs/files/1080040/Battle.at.Ras.El.Hanout.cordova.zip)

The C3 file:
[Battle at Ras El Hanout.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1080042/Battle.at.Ras.El.Hanout.c3p.zip)

Screen shot of blocked app
[schermafbeelding 2017-06-16 om 09 30 20](https://user-images.githubusercontent.com/9109682/27216795-7b9fd44e-5277-11e7-8cd7-8901758b3075.png)
(this is a screenshot from the simulator, the same happens when I create an .IPA and install on my device.

## Steps to reproduce

1. Export to iOS (Cordova)
2. Open the workspace in xcode
3. start the simulator

## Observed result

The app starts, the C3 splash creen shows, the progress bar grows to about 70% and then it stops.

## Expected result
Progress bar completes and the main app starts

## Affected browsers
n.a.

## System details
IOS 10.11.6
xcode 8.2.1
C3 r38.2

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

latform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r38.2

Local storage
Storage quota (approx): 6.8 gb
Storage usage (approx): 196 mb (2.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 5000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by shortercode** [comment]
Took a little bit of searching to find this, particularly as the safari debugger kept spontaneously closing on me. WKWebView is blocking our audio decoder from loading up in a worker.

**Comment by driesdriessen** [comment]
Hi Ian,
That was quick! Thanks for investigating this. I have tried a very simple project without audio and indeed that works fine.
Hopefully you can solve the audio/wkwebview conflict.
Thanks,
Dries.


Op 16 jun. 2017, om 19:03 heeft Iain Shorter <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Took a little bit of searching to find this, particularly as the safari debugger kept spontaneously closing on me. WKWebView is blocking our audio decoder from loading up in a worker.

**Comment by shortercode** [comment]
Good news! Should now be sorted, the patch will be in r40 so keep an eye out.

Incidentally if you have a large amount of audio there are still some memory issues in the audio loader on iOS. It's still on the to-do list

**Comment by driesdriessen** [comment]
Hi Ian,

Great. Thanks for fixing this so quick, and for the update.

Dries

Op 19 jun. 2017 om 17:06 heeft Iain Shorter <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Closed #519<https://github.com/Scirra/Construct-3-bugs/issues/519>.
