### ISSUE TITLE
Tilemap's Autotile Brush gives error during runtime

### ISSUE THREAD

**Issue by RadioMars** [Scirra/Construct-3-bugs#5190]
## Problem description
Using any brush which isn't the first one results in an error. Each brush works individually if they occupy the first position in the brush list. This applies to runtime only. In editor everything works well

## Attach a .c3p
https://www.dropbox.com/s/xz2bw6nrawnncd3/Tilemap_brush_bug.c3p?dl=0

## Steps to reproduce
1. Disable the "blue" brush(which is the first one) in one of the bookmarked cases
2. Enable "green" or "purple" brush instead
3. Run the project and try to paint with enabled brush

## Observed result
A black screen if "green" or "purple" brush are enabled in "on start" event
Drawing with a brush will be impossible if "green" or "purple" brush is enabled in "on touch" event

## Expected result
Autotiling with every brush works in both cases and it is possible to use all brushes in runtime

## More details
Same error appears in chrome console in both cases

**Affected browsers/platforms:** 

Tested in Chrome and Edge on construct versions 268 and 270

## System details

Chrome version 95.0.4638.69 (Official Build) (64-bit)

<details><summary>View details</summary>

Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz   4.00 GHz
64-bit operating system, x64-based processor
RAM 32,0 GB (31,8 GB usable)
GPU GeForce gtx1060

**Comment by DiegoScirra** [comment]
Will be fixed in r272.
