### ISSUE TITLE
3d object when clicked with the mouse only works at the bottom of the object

### ISSUE THREAD

**Issue by gamazgenii** [Scirra/Construct-3-bugs#5191]
When I play in first person mode I want to press the small button on the wall to call the elevator but the knoak is not pressed. but it is pressed only at the very bottom of the button

![003](https://user-images.githubusercontent.com/90530052/140217479-6c2114d9-7a1b-4267-8ed0-8cfb9d2b0431.png)

![002](https://user-images.githubusercontent.com/90530052/140217577-61ddb284-4337-4254-9919-cf88757ed396.png)

![001](https://user-images.githubusercontent.com/90530052/140217687-097e688a-576e-47e2-8769-19d741695b9f.png)

**Comment by AshleyScirra** [comment]
This is currently by design. The editor essentially still works in 2D.

**Comment by gamazgenii** [comment]
> This is currently by design. The editor essentially still works in 2D.

but if this is not a bug, what do I sometimes do what works?

**Comment by AshleyScirra** [comment]
3D collision detection is not currently supported. Construct remains fundamentally a 2D engine, just with 3D graphics on top.

**Comment by gamazgenii** [comment]
thanks
