### ISSUE TITLE
Can't open beta 270 

### ISSUE THREAD

**Issue by 1mrpaul1** [Scirra/Construct-3-bugs#5195]
## Problem description

when downloading 270 getting red screen and error 
this is in the error details
" effects.fog.name" already exist in language string map
![Снимок экрана 2021-11-05 143954](https://user-images.githubusercontent.com/64515864/140491537-558269fb-f378-4e37-9ebc-7b367de6944d.png)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

windows 11.  chrome 95.0.4638

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Do you have a third-party addon named "fog" installed?

**Comment by 1mrpaul1** [comment]
> Do you have a third-party effect named "fog" installed?

yeah, deleting this "fog" effect extension resolved the issue. Thank you

**Comment by AshleyScirra** [comment]
We have an in-development fog effect that's not yet exposed, but it looks like the name clashes with an existing effect. I've renamed the in-development one for the next release to try to avoid the name collision.
