### ISSUE TITLE
Android games with admob showing just black screen on start 

### ISSUE THREAD

**Issue by 1mrpaul1** [Scirra/Construct-3-bugs#5196]
My game was released today on google play
But my friends wasn't able to install it because the store showed an error 
not available for this device
those who were able to install got just a black screen
I tried to export the game without Admob, and it worked as expected
made clean project with just admob, and again, just black screen

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines, otherwise it's impossible for us to help.
