### ISSUE TITLE
android export does not work

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#5197]
## Problem description

from last 24 hours I have been trying to export android apk files but it is literally hit & trial. Sometimes it works,sometimes not. Most of the time it displays "Build:Preparing Project" & then "connection lost" & then this cycle keeps on repeating. Sometimes it ends with a error message "Build timeout"
Latest stable version. Chrome browser

**Comment by DanPkg** [comment]
Hello Scirra Support, 

Trying to build any of my C3 Projects via Android Bundle export (or APK) at the moment causes an error.  

It seems identical issue to the one occurred on 29th Sept, 29th Oct, where a restart of the Build Server fixed the outage.

It says Lost Connection to Server in the status bar Build Service, then it goes back to Preparing Project, a continual loop on this.

Eventually the error says Timeout.

Thanks, Dan

C3 Stable R268 (simple minify)
Chrome Version 95.0.4638.69 (Official Build) (64-bit)
Windows 10 Version 21H1 OS BUILD 19043.1288

![unnamed](https://user-images.githubusercontent.com/71873522/140633371-3870c3ae-6ba7-4bec-bcc3-a55b19188361.png)

**Comment by CalmBlast** [comment]
Oh, same issue here.
My link: https://github.com/Scirra/Construct-3-bugs/issues/5203

**Comment by AshleyScirra** [comment]
Apologies for the inconvenience. The build server should now be working again.

For future reference, if the build server is unreachable for any reason, you can also use manual offline builds as described in [this tutorial on the Cordova CLI](https://www.construct.net/en/tutorials/building-mobile-apps-locally-21).
