### ISSUE TITLE
Software update neeeded on iOS 13 (WebAssembly)

### ISSUE THREAD

**Issue by eponesh** [Scirra/Construct-3-bugs#5198]
## Problem description

On iOS 13 (Safari) see "Software update neeeded" screen

![imgonline-com-ua-Resize-0YWqBgsXncp4R9](https://user-images.githubusercontent.com/31591812/140612706-f5770ea5-5dba-44f3-b0ae-e6416c4e4cc4.jpg)

When run "Remote Preview"

![2021-11-06_2031252](https://user-images.githubusercontent.com/31591812/140612751-639ea7e5-6b68-4c79-b46b-4f06089e33db.png)

## Attach a .c3p

[example.zip](https://github.com/Scirra/Construct-3-bugs/files/7490592/example.zip)

## Steps to reproduce

1. Export as "Web (HTML5 )" / Or run remote preview
2. Open game on iOS 13

## Observed result

"Software update neeeded" screen

## Expected result

Safari iOS 13 Supported

## More details

**Affected browsers/platforms:**

iOS Safari: 13.0 - 13.6

**First affected release:** r268

On **SYSTEM REQUIREMENTS** page Safari 13 still supports:
https://www.construct.net/en/make-games/manuals/construct-3/getting-started/system-requirements

On **Can I Use** page - Safari 11+ supports wasm:
https://caniuse.com/wasm

**Comment by AshleyScirra** [comment]
This makes no sense. iOS 13 does support WebAssembly. So that error should never appear.

I cannot imagine why it would appear, unless you've done something like gone in to developer settings and disabled WebAssembly. Have you done that? Does a stock device with no alterations still exhibit the issue?

**Comment by eponesh** [comment]
I used lambdatest, found out they use emulators. On a real ios 13 device, everything is fine.

**Comment by AshleyScirra** [comment]
I would guess they are using Xcode 11 or older. Using Xcode 12+ should work with the simulator too.
