### ISSUE TITLE
Website menu: Double Pricing

### ISSUE THREAD

**Issue by glerikud** [Scirra/Construct-3-bugs#520]
## Problem description

The construct.net website's menu has a double "Pricing" option in it while the user is in mobile view.

## Attach a .c3p

This is a website issue, no c3p file needed.

## Steps to reproduce

1. Open the construct.net website on mobile, or on PC forcing it to display the mobile layout.
2. Open up the menu.

## Observed result

There are 2 "Pricing" options in the menu. Here's a screenshot: https://www.dropbox.com/s/bgvve1ubjohi9v1/c3_menu.png?dl=0

## Expected result

There should be only 1 "Pricing" option.

## Affected browsers

* Opera: yes (the only browser I tested in both on PC and Android)

**Comment by TomGullen** [comment]
As pricing is a top level item it should exist as a big menu item in the drop down.
