### ISSUE TITLE
Search_Duplication

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#5200]
## Problem description

Problem: Search results are duplicated in the find interface.

Effect: For larger search results this creates unnecessary work to process, potentially hampering performance of the engine.

## Attach a .c3p

[Search_Duplication.zip](https://github.com/Scirra/Construct-3-bugs/files/7491436/Search_Duplication.zip)

## Steps to reproduce

1. Open find interface.
2. Search a portion of the listed action in the event sheet.
3. Observe search result count.

## Observed result

Two search results per portion of the substring found in the event sheet.

## Expected result

A single search result per portion of the substring found in the event sheet.

**Affected browsers/platforms:** Chrome

**First affected release:** r270

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
