### ISSUE TITLE
"Show translucent inactive layers" with Layer Effects error

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#5201]
## Problem description

When "Show translucent inactive layers" is enabled for a layout, layers with Layer Effects are never made translucent.

## Attach a .c3p

https://drive.google.com/file/d/1dfJGM0xGb1RT635umDG1pEe2TvpSOkoC/view?usp=sharing

## Steps to reproduce

1. Open the attached project.
2. Note that the Layout has "Show translucent inactive layers" enabled.
3. Note that Layer 0 has a ReplaceSolidColor effect.
3. Select Layer 2.
4. Note that Layer 0 is _not_ translucent, but Layer 1 is.
5. Select Layer 0.
6. Remove the ReplaceSolidColor from its Layer Effects menu.
7. Select Layer 2 again.
8. Note that Layer 0 is now translucent. 

## Observed result

The layer with a Layer Effect is not drawn translucent.

## Expected result

All inactive layers should be translucent when the layout's "Show translucent inactive layers" option is enabled.

## More details

**Affected browsers/platforms:** Chrome 95

**First affected release:** r270

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in next beta.
