### ISSUE TITLE
Tilemap layer dissappear

### ISSUE THREAD

**Issue by radel999** [Scirra/Construct-3-bugs#5202]
## Problem description

the tiles are not visible when a different tile layer is applied 
## Attach a .c3p

https://downloads.construct.net/uploads/120/31098/ff8db6a8-266d-4311-9d1d-c849f94f339f/super%20contra%20engine%20%28for%20construct%203%29.c3p

## Steps to reproduce

1.  Create two tilemap object

## Observed result

One of tilemap layer is not visible

## Expected result

Two tilemap object is visible on the same layer
## More details

**Affected browsers/platforms:** Chrome

**First affected release:** Worked on previous version but brokes on 270r

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The provided project uses a third-party addon `Pause (Rex_Pause) by Rex.Rainbow`. Please provide a project without using any third-party addons as per the bug report guidelines.
