### ISSUE TITLE
r271_Loading_Error

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#5205]
Launching r271 leads to a failure to load page (attached as image)

## Steps to reproduce

1. Go to https://editor.construct.net/r271/
2. Error

## Observed result

![image](https://user-images.githubusercontent.com/37854520/140930326-53804922-fb34-48b4-b258-71a5e9c02bc9.png)

![image](https://user-images.githubusercontent.com/37854520/140930669-5189a485-67aa-4414-a4a3-bd5ecb444deb.png)

## Expected result

Load up of the construct start page.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r271

**Comment by AshleyScirra** [comment]
It works for me. Try clearing your browser cache and retrying.

**Comment by OneRepCloser** [comment]
1st Attempt: Clear browser cache: 

Didn't work

2nd Attempt: Clear Cookies and sign out of sites:

Worked

Might be useful to add this to the error page suggestions alongside the clearing of cache.

![image](https://user-images.githubusercontent.com/37854520/140950423-19018572-6904-43d0-939a-d86b41184c37.png)
