### ISSUE TITLE
Error opening project in r271

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#5206]
## Problem description

A project that opens in 270 displays an error when it opens it 271.

## Attach a .c3p

(unable to attach this project)

## Steps to reproduce

1. I've opened a project that opens properly in 270.
2. The project files all download and open correctly: all the layers, objects, etc., load into the bars. The layout editor opens the layout.
3. However, as soon as everything has loaded, Construct crashes with the error message below.

## Observed result

The full error report is pasted below in "System Details", but the headline reads:

Type: unhandled exception
File: https://editor.construct.net/r271/main.js, line 482, col 182
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'pua')
Stack: TypeError: Cannot read properties of undefined (reading 'pua') at Object.CCG.xka 

## Expected result

The project opens as it does in 270.

## More details

**Affected browsers/platforms:** Chrome 95 MacOS 11.6

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r271/main.js, line 482, col 182
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'pua')
Stack: TypeError: Cannot read properties of undefined (reading 'pua') at Object.CCG.xka (https://editor.construct.net/r271/main.js:482:182) at Object.CCG.Ik (https://editor.construct.net/r271/main.js:497:261) at d.yf (https://editor.construct.net/r271/projectResources.js:1172:477) at d.yf (https://editor.construct.net/r271/projectResources.js:1171:298) at d.yf (https://editor.construct.net/r271/projectResources.js:1132:460) at vTb (https://editor.construct.net/r271/components/editors/layoutView/layoutView.js:77:284)
Construct 3 version: r271
URL: https://editor.construct.net/r271/
Date: Tue Nov 09 2021 08:15:24 GMT-0500 (Eastern Standard Time)
Uptime: 12.9 s

Platform information
Browser: Chrome
Browser version: 95.0.4638.69
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
C3 release: r271 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to investigate this without the project, as per the bug report guidelines.

You can email it to ashley@scirra.com if you want to keep it private and I'll take a look, but if it is broken due to third-party addons I may not be able to help.

**Comment by AshleyScirra** [comment]
Actually the error looks the same as #5209 (crash using global layers), so I would assume it's just that and will be fixed when that issue is fixed.
