### ISSUE TITLE
r271 Crash using global layers

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-3-bugs#5209]
## Problem description

If you in editor mode go to a layout with overriden layer, construct will crash

## Attach a .c3p

Use blank project.

## Steps to reproduce

1. Create global layer on layout 1
2. Create layer with the same name on layout 2
3. Switch to layout 2

## Observed result

Crash

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r271

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r271/main.js, line 482, col 182
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'pua')
Stack: TypeError: Cannot read properties of undefined (reading 'pua') at Object.CCG.xka (https://editor.construct.net/r271/main.js:482:182) at Object.CCG.Ik (https://editor.construct.net/r271/main.js:497:261) at d.yf (https://editor.construct.net/r271/projectResources.js:1171:482) at d.yf (https://editor.construct.net/r271/projectResources.js:1171:298) at d.yf (https://editor.construct.net/r271/projectResources.js:1132:460) at vTb (https://editor.construct.net/r271/components/editors/layoutView/layoutView.js:77:284)
Construct 3 version: r271
URL: https://editor.construct.net/r271/
Date: Tue Nov 09 2021 19:03:38 GMT+0500 (Екатеринбург, стандартное время)
Uptime: 21.5 s

Platform information
Browser: Chrome
Browser version: 95.0.4638.69
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
C3 release: r271 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9649)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
There was a small oversight in the global layers rendering code that needed updating for sub-layers. I've fixed it now, and I think we'll get a hotfix out tomorrow to unblock further testing of sub-layers. Leaving this open for the time being.

**Comment by AshleyScirra** [comment]
This should now be fixed in the r271.2 hotfix release.
