### ISSUE TITLE
Crash at launch after installing faulty c3addon

### ISSUE THREAD

**Issue by alvaromartmart** [Scirra/Construct-3-bugs#521]
## Problem description

I did a quick test modifying the SDK template and installed the plugin. I obviously did something wrong in the plugin, and the editor crashes upon launch showing the crash report included below, which references the error in my plugin.

As it crashes inmediately, I can't even open the plugin manager to update or remove the plugin. 

## Attach a .c3p

I can't attach a .c3p as I didn't save one with the faulty plugin and can't run the editor to create one. I'm attaching the .c3addon file instead (in zip format as apparently .c3addon attachments are not allowed at the moment, BTW)

[faultybehaviour.zip](https://github.com/Scirra/Construct-3-bugs/files/1081074/faultybehaviour.zip)

## Steps to reproduce

1. Rename attached plugin to .c3addon
2. Install addon
3. Restart editor

## Observed result

Editor crashes on launch

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: ACE definition "id" is not a string @ Error: ACE definition "id" is not a string at window.ǃCzq.window.ǃCzl (https://editor.construct.net/r38-2/main.js:61:290590) at window.ǃCzv (https://editor.construct.net/r38-2/main.js:61:292719) at window.ǃCzq (https://editor.construct.net/r38-2/main.js:61:296353) at Function.ǃC.ǃA (https://editor.construct.net/r38-2/main.js:2:202980) at window.ǃCEM.ǃCEo (https://editor.construct.net/r38-2/main.js:61:298205) at window.ǃCoo.ǃCon (https://editor.construct.net/r38-2/main.js:61:412394) at v.ǃwbC (https://editor.construct.net/r38-2/main.js:71:27576) at Object.n.push.ǃC.ǃLv [as ǃwLB] (https://editor.construct.net/r38-2/main.js:71:27950) at n (https://editor.construct.net/r38-2/main.js:2:257257) at t (https://editor.construct.net/r38-2/main.js:2:257043)
Stack: Error: ACE definition "id" is not a string at window.ǃCzq.window.ǃCzl (https://editor.construct.net/r38-2/main.js:61:290590) at window.ǃCzv (https://editor.construct.net/r38-2/main.js:61:292719) at window.ǃCzq (https://editor.construct.net/r38-2/main.js:61:296353) at Function.ǃC.ǃA (https://editor.construct.net/r38-2/main.js:2:202980) at window.ǃCEM.ǃCEo (https://editor.construct.net/r38-2/main.js:61:298205) at window.ǃCoo.ǃCon (https://editor.construct.net/r38-2/main.js:61:412394) at v.ǃwbC (https://editor.construct.net/r38-2/main.js:71:27576) at Object.n.push.ǃC.ǃLv [as ǃwLB] (https://editor.construct.net/r38-2/main.js:71:27950) at n (https://editor.construct.net/r38-2/main.js:2:257257) at t (https://editor.construct.net/r38-2/main.js:2:257043)
Construct 3 version: r38.2
URL: https://editor.construct.net/
Date: Fri Jun 16 2017 16:40:47 GMT+0200 (Romance Daylight Time)
Uptime: 5.6 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r38.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by alvaromartmart** [comment]
BTW, how do I "uninstall" the cached version of C3 so I can use it again? Do I have to do a full Chrome cache cleaning?
It may be useful to include a button in the crash report dialog to clear the cached C3 files in case it gets "corrupted"

**Comment by AshleyScirra** [comment]
First of all you should use [developer mode](https://www.scirra.com/doc/c3sdk/testing-developer-addons.html) for addons, so if you crash the editor you can just fix it and carry on.

If you install a .c3addon which crashes the editor, the only way to get rid of it is to clear browser storage. You can do this just for C3 by opening dev tools, going to the "Application" tab, selecting "clear storage" on the left, make sure everything is ticked and then click "clear site data". This is a bit of a pain, so I've filed #522 to add a special safe mode to more easily avoid this.
