### ISSUE TITLE
Cannot paste image selections in animations editor from outside browser tab on Firefox

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#5210]
## Problem description

While in Chrome, image selections copied to the clipboard from outside the Construct 3 tab/window (such as a selection made in an image editor like Paint.net, or the Windows Snipping Tool, or even copied from another tab with another instance of Construct 3 running) can be pasted into Construct 3's animation editor, in _Firefox_, no copied image from outside a given Construct 3 tab can be pasted into that Construct 3's image editor.

## Attach a .c3p

[Blank.zip](https://github.com/Scirra/Construct-3-bugs/files/7506179/Blank.zip)

## Steps to reproduce

1. In a C3 tab, open any project such as the empty one provided above.
2. Create or open an existing sprite in the animations editor.
3. In a _new_ C3 tab or in an external image editor, select and copy part of an image to the clipboard.
4. In our initial C3 tab's animations editor, attempt to paste the copied image, noting that none appears.

## Observed result

As in Chrome, Firefox Construct 3 allows for copied images from outside the tab to be pasted into the animations editor.

## Expected result

Nothing is successfully pasted from clipboard that was not copied within the same Firefox Construct 3 tab animations editor.

## More details

Occurs in Firefox. Tested in Microsoft Edge and could not reproduce the issue there.

**Affected browsers/platforms:** Firefox

**First affected release:** No later than r268, but has been an issue for far longer.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 94.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
C3 release: r268 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 446 mb
Storage usage (approx): 468 kb (0.1%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0, D3D11-23.20.16.4973)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
The feature was disabled by Mozilla in Firefox version 87. Nothing to do on Construct's side.
