### ISSUE TITLE
In animations editor, cannot scroll or zoom with mousewheel with cursor over a selected area

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#5213]
## Problem description

In the animations editor, after having selected an area with the rectangle select tool, while the mouse cursor is over it, attempting to scroll vertically or horizontally (by holding shift) or scroll to zoom (by holding ctrl) will fail to work.

## Attach a .c3p

[Blank.zip](https://github.com/Scirra/Construct-3-bugs/files/7506525/Blank.zip)

## Steps to reproduce

1. Open a new C3 project or an existing one like the one provided above.
2. Create a new sprite or open an existing one in the animations editor.
3. Use the rectangle select tool to select an area of any size or paste an image selection, causing an area to be selected in the canvas.
4. If mouse is not already over the selected area, move it there.
5. Scroll the mousewheel, attempting to scroll to move or zoom in the animations editor, noting that it won't happen now.

## Observed result

Scrolling functions stop working while highlighting a selected area in animations editor.

## Expected result

Scrolling functions work just the same while highlighting a selected area in animations editor.

## More details

This issue becomes a problem most frequently in my experience just after pasting an image into the animations editor, whereupon the entire pasted image will appear as a rectangle-selected area, meaning you may not be able to scroll or zoom while highlighting any part of the entire canvas, depending on the size of the pasted image! It can also come up often when, after making a selection, you would try to scroll to move or zoom your view in to get a better look at your selected area.

**Affected browsers/platforms:** Chrome, Firefox, Edge

**First affected release:** First occurred no later than r268.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 94.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
C3 release: r268 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 446 mb
Storage usage (approx): 468 kb (0.1%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0, D3D11-23.20.16.4973)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
