### ISSUE TITLE
On Firefox, 'For Each' condition's object picking window can be infinitely populated

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#5214]
## Problem description

The 'click to choose' button as seen in the For Each system condition can be pressed multiple times to add unlimited copies of every object to the Pick an Object window's list.

## Attach a .c3p

[ForEachMultipleClick.zip](https://github.com/Scirra/Construct-3-bugs/files/7507811/ForEachMultipleClick.zip)

## Steps to reproduce

1. Open the attached project or any existing or new project, ensuring the project contains at least one sprite object.
2. In an event sheet, add a new event --> System --> For Each.
3. In the 'Parameters for System: For Each' window, click the 'click to add object' button repeatedly, thus opening and then repeatedly populating the 'Pick an object' window with a copy of every applicable object for each time the 'click to add object' button is pressed.

## Observed result

The 'Pick an object' window is repeatedly filled with copies of every applicable object, once for each time the 'click to add object' button is pressed.

## Expected result

The 'click to add an object' button (and perhaps any other buttons in the 'Parameters for System: For Each' window?) should not be interactive while 'Pick an object' window is open, or at least the 'click to add object' button will not populate the object picking window more than once if it's already open.

## More details

This is similar to an older bug report here: https://github.com/Scirra/Construct-3-bugs/issues/4739

After that report was closed without Scirra being able to find the problem, I totally forgot to follow up and be more helpful in pointing it out! Sorry about that! Wasn't sure if protocol allows for reopening a closed bug report so I made this one here, which is slightly different anyway because testing the issue now, it seems the issue only happens in Firefox, whereas before I claimed it happened in Chrome too. But I'm also including a video to show how to reproduce this issue in a new project, hopefully more clearly than I communicated last time:

https://user-images.githubusercontent.com/4585257/141002928-2822eb3b-ebd3-42e8-bd51-b82fa4631351.mp4

**Affected browsers/platforms:** Firefox

**First affected release:** First occurred no later than r241.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 94.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
C3 release: r268 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 446 mb
Storage usage (approx): 468 kb (0.1%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0, D3D11-23.20.16.4973)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
