### ISSUE TITLE
3d view gives black screen when 3d camera position set and lowest layer not transparent

### ISSUE THREAD

**Issue by driesdriessen** [Scirra/Construct-3-bugs#5215]
## Problem description

3d camera object gives a black screen

## Attach a .c3p

[debug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/7508132/debug.c3p.zip)

## Steps to reproduce

When the 3d camera view is not set to a specific position, the screen renders normally.
When the 3d camera view is set to a position, the screen shows black and the game freezes
When the lowest layer (Main in the attached example) is set to transparent, the 3d view works fine.
When the object on layer 1 is moved to layer 0, all works fine.

## Observed result

3d view shows a black screen when the 3d camera position is set to a horizontal view.

## Expected result

3d view should show a normal 3d view

## More details
This problem occurs in build 271. It did not occur in a recent earlier build, probably 1-2 builds back (sorry I can't be more specific about that.) 

## System details

Platform information
Browser: Chrome
Browser version: 92.0.4515.159
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
C3 release: r271 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 268 gb
Storage usage (approx): 649 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 5000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in an upcoming hotfix release.

**Comment by driesdriessen** [comment]
Super. Thanks for the quick response!
