### ISSUE TITLE
r271 Overlay Effect looks very different

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#5217]
## Problem description

The Overlay effect gives very different results since updating to the new effects compositor. In the following example it is applied to a fog mask over the whole screen. Not only is the fog now practically invisible, but it no longer gives the boost in contrast and saturation that it once did. Please let me know if a .c3p is needed for this case.

Before:
![Screenshot 2021-11-09 165445](https://user-images.githubusercontent.com/36490901/141029910-0ab636e1-10fe-48c5-8744-96e7b9455769.png)

After:
![Screenshot 2021-11-09 165254](https://user-images.githubusercontent.com/36490901/141029947-f2f60025-c09d-4002-b205-87fc91dbe729.png)
## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid we always need all the required details, as it's impossible to do anything without them.
