### ISSUE TITLE
Documentation didn't explain ImagePointCount expression didn't include Origin

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5219]
## Problem description

I have spent some time figuring out the bug in my code, only to find that I assumed ImagePointCount includes the origin, and built my calculations on that.
Since Origin is included in the Image Points window (in the Animation Editor), I assumed it is an "Image Point".

**Comment by AshleyScirra** [comment]
I've added a note to the manual section covering these expressions to note that they exclude the origin: https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/sprite
