### ISSUE TITLE
r271 Overlay effect looks different

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#5223]
## Problem description

The Overlay effect gives very different results since updating to r271 with the new effects compositor - It no longer gives the boost in contrast and saturation that it once did, instead it just darkens things a bit.

## Attach a .c3p

[Overlay Discrepancy.zip](https://github.com/Scirra/Construct-3-bugs/files/7522357/Overlay.Discrepancy.zip)

## Steps to reproduce

1. Preview .c3p in any C3 build prior to r271. Note the boosted contrast and saturation on the left side of the screen. Take a screenshot if need be.
2. Preview .c3p in r271.
3. Observe the differences.

## Observed result

The overlay effect no longer gives a boost in contrast and saturation.

## Expected result

For the overlay effect to give the same boost in contrast and saturation as it did in prior releases.

## More details

**Affected browsers/platforms:** Chrome / nw.js

**First affected release:** r271

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 95.0.4638.69
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
C3 release: r268 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 96 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-22.20.16.4749)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This had me scratching my head for a while as the editor renders it differently to the runtime in r268, matching what the editor & runtime now do in r271. However it turns out the runtime in r268 is indeed the correct rendering and the new effect compositor had the same bug as the editor in r268. This is fixed for the next beta, which also ensures the editor previews the same as the runtime (which means another presumably old long-standing bug fixed). Thanks - good catch.
