### ISSUE TITLE
Using right(textinput.text,count) not displaying properly.

### ISSUE THREAD

**Issue by jsuttonBRC** [Scirra/Construct-3-bugs#5224]
## Problem description

right(textinput.text,count) not displaying properly.  It displays fine to 10 characters, then drops a character each input until it reaches the count.

## Attach a .c3p

https://drive.google.com/file/d/1Dpycj5snj823IJgyixJhF7g_KqzyXfAf/view?usp=sharing

## Steps to reproduce

1.  New project, add keyboard, textinput, and text objects.
2.  TextInput On Text changed, set text to right(textinput.text,20)
3.  Type "This should work correctly"

## Observed result

Up to the 10th characters the text displays the right 10 characters of the textinput object.  (textinput.text)

Character 11 thru 19 the text object starts displaying 1 less character than what is actually in textinput.text

At the 19th character, the textinput.text displays properly in the text object

## Expected result

I would expect right(textinput.text,count) to always display the counted spaces in the text object.

## More details

N/A

**Affected browsers/platforms:** 

**First affected release:** 
Construct 3, r268  (I recreated this using Chrome Version 95.0.4638.69 on Windows 10, in android remote preview on a S9+.  It happens in debug and normal preview.)  

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 95.0.4638.69
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
C3 release: r268 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 548 gb
Storage usage (approx): 25 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-23.20.16.4973)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by jsuttonBRC** [comment]
[Text_Bug_Report.zip](https://github.com/Scirra/Construct-3-bugs/files/7522990/Text_Bug_Report.zip)
In case the link isn't what's needed, here is a zipped version.

**Comment by AshleyScirra** [comment]
Fixed for next beta.
