### ISSUE TITLE
Some submenu commands in event sheets do not apply when selecting multiple conditions.

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5225]
## Problem description

When selecting multiple actions and applying one of the following commands, it only applies to the condition that was clicked.
- Make OR block
- Toggle breakpoint
- Toggle bookmark

## Steps to reproduce

1. Add an event to an event sheet.
2. Add multiple sub-conditions to the event.
3. Select multiple sub-conditions using Ctrl+Click.
4. Right click on one of them.
5. Select on of the aforementioned commands.

## Observed result

The command only applies to the clicked condition.

## Expected result

The command should apply to all selected conditions. ("Toggle disabled" command for example works correctly for all selected conditions)

## More details

**Affected browsers/platforms:** Firefox 94.0.1 64-bit Windows 7

**Comment by AshleyScirra** [comment]
Should be fixed for next beta.
