### ISSUE TITLE
error when saving the first time the project folder

### ISSUE THREAD

**Issue by gamazgenii** [Scirra/Construct-3-bugs#5229]
1) open the project folder
2) press keyboard shortcuts to save
3) an error pops up

![Снимок](https://user-images.githubusercontent.com/90530052/141604670-619f73aa-4238-44cf-ae68-75c02dc53601.PNG)

if you save the project again, then errors will never appear again

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it is impossible for us to help.
