### ISSUE TITLE
Crash when selecting Object

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#5232]
## Problem description

I just selected an enemy (includes a hierarchy) and this happened. I did have the tilemap bar open at that time (the error mentions the tilemap bar). I cannot replicate it though...
Update: Possibly related issue https://github.com/Scirra/Construct-3-bugs/issues/5239

## Attach a .c3p

-

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r271-2/projectResources.js, line 716, col 97
Message: Uncaught TypeError: Cannot read properties of null (reading 'ZG')
Stack: TypeError: Cannot read properties of null (reading 'ZG') at d.Bd (https://editor.construct.net/r271-2/projectResources.js:716:97) at d.uc (https://editor.construct.net/r271-2/projectResources.js:716:280) at d.rk (https://editor.construct.net/r271-2/projectResources.js:716:364) at Feb.oic.rk (https://editor.construct.net/r271-2/components/bars/tilemapBar/tilemapBar.js:145:232) at adb (https://editor.construct.net/r271-2/components/bars/tilemapBar/tilemapBar.js:5:92) at DX (https://editor.construct.net/r271-2/components/bars/tilemapBar/tilemapBar.js:13:412) at d.CCG.aa.V9a (https://editor.construct.net/r271-2/components/bars/tilemapBar/tilemapBar.js:91:326) at window.W4a.dispatchEvent (https://editor.construct.net/r271-2/main.js:1044:32) at GQ (https://editor.construct.net/r271-2/components/editors/layoutView/layoutView.js:1:265) at F8a.Ho (https://editor.construct.net/r271-2/components/editors/layoutView/layoutView.js:190:408)
Construct 3 version: r271.2
URL: https://editor.construct.net/r271-2/
Date: Sat Nov 13 2021 12:28:08 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 12794.6 s

Platform information
Browser: Chrome
Browser version: 95.0.4638.69
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
C3 release: r271.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6079)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
This is not related to #5239. It's a very old issue that I have seen in our crash reports previously, but have never been able to figure it out.

**Comment by DiegoScirra** [comment]
I haven't been able to reproduce this, so it is impossible to tell if this will be fixed on the next beta, but a little change will go out that might prevent the crash.
