### ISSUE TITLE
Preview Window Blacks Out (Chrome OS)

### ISSUE THREAD

**Issue by fingerskier** [Scirra/Construct-3-bugs#5233]
## Problem description

When dragging the mouse cursor the screen goes black, then comes back, then the preview window is solid black.

## Steps to reproduce

1.  Load the project
2. Click the triangle run button in the menubar
3. 

## Observed result

When dragging the mouse cursor the screen goes black, then comes back, then the preview window is solid black.

## Expected result

The project is supposed to rotate the tiled-background and lengthen it to touch the mouse-click-location

## More details

Newest Chome OS version; I have installed Construct via the Chrome browser as an "app".

**Affected browsers/platforms:** 

Version 94.0.4606.114 (Official Build) (32-bit)

The issue exists in r268 and r271.2

## System details

Construct does not crash.  Restarting the preview works but the issue always occurs on the next preview.

**Comment by AshleyScirra** [comment]
Please attach a project file as per the bug report guidelines otherwise it's impossible for us to help.

**Comment by fingerskier** [comment]
Sry, here it is...
[MouseTouch_possiblebug.zip](https://github.com/Scirra/Construct-3-bugs/files/7559216/MouseTouch_possiblebug.zip)

**Comment by AshleyScirra** [comment]
It seems to work fine here.
