### ISSUE TITLE
Layout Edit Broken

### ISSUE THREAD

**Issue by fingerskier** [Scirra/Construct-3-bugs#5234]
## Problem description

The layout editor breaks after a short while.

## Attach a .c3p

...and screenshot

## Steps to reproduce

1. After editing for awhile the layout view breaks

## Observed result

![LayoutTest](https://user-images.githubusercontent.com/271169/141663865-5a88886b-18e0-40e6-b986-6580f3cbc8e3.png)

[LayoutTest.zip](https://github.com/Scirra/Construct-3-bugs/files/7533010/LayoutTest.zip)

## Expected result

I expected the editor to continue working...

## More details

Same result on r268 and r271.2

**Affected browsers/platforms:** 

Chrome OS Version 94.0.4606.114 (Official Build) (32-bit)

## System details

No crash.

**Comment by DiegoScirra** [comment]
There isn't much to do about this because there are no clear steps to reproduce the issue.

**Comment by fingerskier** [comment]
It's as simple as stated: on any project the layout editor breaks, showing the unhappy face icon.  After a restart it works again.

**Comment by AshleyScirra** [comment]
The "sad face" icon in the corner suggests a graphics driver crash. So I think this is a system-specific issue to do with your graphics driver rather than an issue with Construct itself.
