### ISSUE TITLE
Timeline: color manipulation crash

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-3-bugs#5235]
## Problem description

Trying to undo or delete color property in timeline editor causes crash.

I pressed CTRL+Z before it crashed:
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/15311427/141679257-44821f15-38be-45db-93cf-4b40ba6e4942.gif)

## Attach a .c3p

https://drive.google.com/file/d/1nIEkR2GOtQ-WmHL2C6JgORPAm4rPivZ_/view?usp=sharing

## Steps to reproduce

This could be tricky.

Just adding a color property and removing it seems has no effect in early versions (r230 - r257). But adding it, changing the value and removing it makes a crash constantly.

1. Add color property to timeline
2. Change sprite color (whether it's default sprite color or timeline property, doesn't matter)
3. Undo or remove

But for later versions (r258 - r271.2) you don't even have to change the value to make it crash.

1. Add color property
2. Undo or remove

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** It is r230! And then it changed in r258

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.R.i (https://editor.construct.net/r271-2/main.js:858:461) at window.Ubb.Df (https://editor.construct.net/r271-2/projectResources.js:756:220) at WH.z7 (https://editor.construct.net/r271-2/projectResources.js:1033:114) at d.Kh (https://editor.construct.net/r271-2/projectResources.js:1003:214) at d.Rh (https://editor.construct.net/r271-2/projectResources.js:492:506) at d.Wa (https://editor.construct.net/r271-2/projectResources.js:492:394) at d.Wa (https://editor.construct.net/r271-2/projectResources.js:1002:493) at wL.Wa.sf (https://editor.construct.net/r271-2/projectResources.js:1647:69) at window.vc.Ih (https://editor.construct.net/r271-2/projectResources.js:1644:19) at d.Ih (https://editor.construct.net/r271-2/projectResources.js:1529:198)
Stack: TypeError: unexpected type at Function.R.i (https://editor.construct.net/r271-2/main.js:858:461) at window.Ubb.Df (https://editor.construct.net/r271-2/projectResources.js:756:220) at WH.z7 (https://editor.construct.net/r271-2/projectResources.js:1033:114) at d.Kh (https://editor.construct.net/r271-2/projectResources.js:1003:214) at d.Rh (https://editor.construct.net/r271-2/projectResources.js:492:506) at d.Wa (https://editor.construct.net/r271-2/projectResources.js:492:394) at d.Wa (https://editor.construct.net/r271-2/projectResources.js:1002:493) at wL.Wa.sf (https://editor.construct.net/r271-2/projectResources.js:1647:69) at window.vc.Ih (https://editor.construct.net/r271-2/projectResources.js:1644:19) at d.Ih (https://editor.construct.net/r271-2/projectResources.js:1529:198)
Construct 3 version: r271.2
URL: https://editor.construct.net/r271-2/
Date: Sun Nov 14 2021 16:16:32 GMT+0500 (Екатеринбург, стандартное время)
Uptime: 84.4 s

Platform information
Browser: Chrome
Browser version: 95.0.4638.69
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
C3 release: r271.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9649)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
