### ISSUE TITLE
Timeline: Keyframes minor visual bug

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-3-bugs#5236]
## Problem description

Keyframes remain on the layout after deleting a sprite, while in editing mode. They remain until the timeline windows is closed

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/15311427/141680224-38d6b1f3-2912-4576-9eca-9a891a8f9f6f.gif)

## Steps to reproduce

1. Create a timeline
2. Press Editing mode button
3. Remove sprite

**Comment by elfwy-uwu** [comment]
p.s I forgot to switch back construct version after publishing previous bug, but this case is still actual for r271.2 and it looks the same as on gif

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
