### ISSUE TITLE
Dark Theme: Set value for instance var drop down overlaps text

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#524]
## Attach a .c3p

![image](https://user-images.githubusercontent.com/7268697/27237611-7bd4f286-52d2-11e7-88c8-3a96aba8bf81.png)

## Expected result

No overlapping

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Animmaniac** [comment]
It should be fixed for the next theme release.
