### ISSUE TITLE
Lens got renamed to Lens2 in C3

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#5240]
## Problem description

I had a C2 project I wanted to port to C3, and it used only vanilla addons, but C3 still rejected it as missing addons
![image](https://user-images.githubusercontent.com/11213825/141780636-dcceea22-96c1-4449-91ac-e7023134c57a.png)

## Attach a .c3p

[lens test.zip](https://github.com/Scirra/Construct-3-bugs/files/7538589/lens.test.zip)

## Steps to reproduce

1. drag and drop file on C3

## Observed result

project gets rejected

## Expected result

project should automatically use Lens2 (or Lens should be added as a vanilla addon with the same ID)

## More details
Simple solution:
Hard code a whitelist of addons to their new C3 counterpart

More interesting solution:
Provide an Editor SDK extension for managing support for old C2 addons and automatically port them to new ones. Lens being ported to Lens2 would be a 1:1 map, but it would also be interesting to have an interface (like the on file dropped interface) that runs for every installed addon, even if they haven't been added to the project yet, that can detect when a missing addon has been found, and prompts the user if they want to try an alternative.

The addon would then be given every reference data (ACEs and property data) of the old addon, and be tasked to return with new appropriate data. This would make supporting old C2 addons that can't work in C3 anymore a LOT easier.

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
At some point years ago the Lens effect was deprecated and replaced with Lens2. So the message is correct. Following its advice about using r251.2 should work as a workaround.

The old effect has actually been completely deleted from the codebase now as there is no way to use it in the latest version of C3. Given it has presumably very little usage, and custom import logic like this is complicated and difficult to test, I don't think it's worth changing it.
