### ISSUE TITLE
Bugs & suggestions

### ISSUE THREAD

**Issue by idjer83** [Scirra/Construct-3-bugs#5241]
Hey everybody, I've found some bugs and make suggestions in C3 and want to share with devs.
Bugs:
- Sounds in preview mostly broken (preload sound sometimes cause preview does't start - black screen, and trying to listen sound in editor mostly cause crashes of C3)
- Image editor recently caught a bug: image point does't apply if switch to another frame, switch frames, etc. Only close/reopen it helps (most time)
- In suggestions I mention about moving functions. Well, if using method I describe - sometimes I get in function list 2 function with same names, but new one is on 'event sheet name', another in event sheen with no name (nowhere), but i still can use it O_o

Suggestions:
- Return multiline input in variable editor (it was very useful to separate pieces of formulas or text to lines after or before 'newline')
- Add to objects comment field (to see it in properties, such as width, height, etc)
- Allow functions to be moved to another layout (without make duplicate there, find all events its used, replace and then delete original)
- [HARD!] Make in layout editor feature to replace one object to another (like in event sheet editor). Yes, I understand its damn hard, but if you have this idea interest and can realize it - its will be useful in many situations :3

Its all for now on. More if I see something weird, strange or broken :)

**Comment by AshleyScirra** [comment]
For bug reports, please follow the guidelines, otherwise it is impossible for us to investigate them.

For suggestions please see this thread: https://www.construct.net/en/forum/construct-3/general-discussion-7/announcing-new-construct-161682
