### ISSUE TITLE
Editor UI - Copy and Paste Shortcuts don't work in Color Picker

### ISSUE THREAD

**Issue by broknecho** [Scirra/Construct-3-bugs#5243]
## Problem description

Using the keyboard shortcuts for copy and paste do not work in the text inputs of the color picker.

## Attach a .c3p

No c3p needed.  Just open a brand new project

## Steps to reproduce

1. Open New Project
2. Click the Project level `Background color` picker
3. In any of the color modes, try Copy'ing and Paste'ing from/to any of the inputs

## Observed result

The input field is cleared out and nothing is added to the clipboard.  If clipboard had content, it does not paste into the field (i.e. HEX input).

## Expected result

Clipboard should contain the text copied if `Copy` command is used.
If pasting, the contents of the clipboard should be entered. i.e. copying a HEX code from a different layers color picker.

## More details

**Affected browsers/platforms:** 

Tested with Edge, Brave, Chrome, In Private Edge, Incognito Chrome.
Tested on a windows machine and Chromebook to eliminate the platform.

**First affected release:** 
`r268` stable

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 95.0.1020.53
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53
C3 release: r268 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 914 mb
Storage usage (approx): 22 mb (2.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6647)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This is an issue with Chromium's form controls. It is easily reproductible with any input of type "color" outside of Construct. There is already an issue on their public bug tracker about it.

https://bugs.chromium.org/p/chromium/issues/detail?id=1066509

Nothing we can do about but wait for it to be fixed. The best you can do is star it, it's not much but the more stars an issue has the better chances it has of being looked at.

**Comment by broknecho** [comment]
Thanks @DiegoScirra !  Starred the chromium bug.

**Comment by broknecho** [comment]
@DiegoScirra Looks like this just got fixed!  https://issues.chromium.org/issues/40124558

Nice and short 4 year turn around.
