### ISSUE TITLE
Project ruined - won't open (Timeline missing)

### ISSUE THREAD

**Issue by TeamDisgrace** [Scirra/Construct-3-bugs#5244]
## Problem description
I'm trying to open a local project file in Construct 3 version 271.2 and it immediately crashes, giving me a crash message. This happened after i was editing a timeline

## Attach a .c3p
[Bugged_Project.zip](https://github.com/Scirra/Construct-3-bugs/files/7555020/Bugged_Project.zip)

## Steps to reproduce

How it happened:
1. I was working with timelines in timeline editor. I've added two small timelines inside a bigger one.
2. Project crashed, i pressed "restart" (Didn't save it!)
3. Now everytime i load the project it just crashes

## Observed result

Here's a screenshot of what i see
![Безымянный](https://user-images.githubusercontent.com/94541962/142211438-8f789cf0-6c61-426b-8fa2-f4fff1cacbe8.png)

## Expected result
The project should open as usual

## More details
The full error message is under SYSTEM DETAILS spoiler

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: missing timeline
Stack: Error at Function.xa.iNa (https://editor.construct.net/r271-2/main.js:927:268) at window.assert (https://editor.construct.net/r271-2/main.js:846:38) at iCa (https://editor.construct.net/r271-2/projectResources.js:81:100) at d.Gbc (https://editor.construct.net/r271-2/projectResources.js:877:21) at d.T5a (https://editor.construct.net/r271-2/projectResources.js:1503:300) at d.eLb (https://editor.construct.net/r271-2/projectResources.js:1574:344) at async Object.CCG.dn (https://editor.construct.net/r271-2/main.js:703:1) at async Toa (https://editor.construct.net/r271-2/main.js:747:307) at async CP (https://editor.construct.net/r271-2/main.js:2302:338)
Construct 3 version: r271.2
URL: https://editor.construct.net/r271-2/
Date: Wed Nov 17 2021 16:35:19 GMT+0300 (GMT+03:00)
Uptime: 979.8 s

Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r271.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Vega 3 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.22023.1004)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
@TeamDisgrace

Can you share the project?

**Comment by DiegoScirra** [comment]
[WindyDay.zip](https://github.com/Scirra/Construct-3-bugs/files/7555339/WindyDay.zip)

That project should open properly, some of the work you did before the crash might have been lost.

I haven't fixed the problem that caused the crash though. Do you remember more or less what you did after adding the two small timelines inside the bigger one? If you don't, don't worry too much about it, but any extra information is useful to figure out what is going wrong.

**Comment by TeamDisgrace** [comment]
> [WindyDay.zip](https://github.com/Scirra/Construct-3-bugs/files/7555339/WindyDay.zip)
> 
> That project should open properly, some of the work you did before the crash might have been lost.
> 
> I haven't fixed the problem that caused the crash though. Do you remember more or less what you did after adding the two small timelines inside the bigger one? If you don't, don't worry too much about it, but any extra information is useful to figure out what is going wrong.

Hi! Thank you for the file. I do actually remember. Previously that day i was messing with blending modes and i guess that's it. I also had crashes a few days ago, when i was trying to rename any layout. These crashes were happening to me after messing with arrays and dictionaries.

**Comment by TeamDisgrace** [comment]
> [WindyDay.zip](https://github.com/Scirra/Construct-3-bugs/files/7555339/WindyDay.zip)
> 
> That project should open properly, some of the work you did before the crash might have been lost.
> 
> I haven't fixed the problem that caused the crash though. Do you remember more or less what you did after adding the two small timelines inside the bigger one? If you don't, don't worry too much about it, but any extra information is useful to figure out what is going wrong.

K, i've recreated this bug entirely. 
1. Open my project
2. Create a timeline for arrow object (or any idk)
3. Duplicate this timeline and swap instances in the second timeline to other instances of the same object
4. Combine this two timelines inside a bigger timeline
5. Play it a few times then close timelines tab
And then game crashes

**Comment by TeamDisgrace** [comment]
> [WindyDay.zip](https://github.com/Scirra/Construct-3-bugs/files/7555339/WindyDay.zip)
> 
> That project should open properly, some of the work you did before the crash might have been lost.
> 
> I haven't fixed the problem that caused the crash though. Do you remember more or less what you did after adding the two small timelines inside the bigger one? If you don't, don't worry too much about it, but any extra information is useful to figure out what is going wrong.

Okay. I've found out how to replicate it 100
1) Go ahead and download the project
[WD_1.1 (1).zip](https://github.com/Scirra/Construct-3-bugs/files/7556843/WD_1.1.1.zip)
%
2) Open the project, search for timelines Arrow_L and Arrow_R
3) Create another empty timeline and call it e.g. Arrow_Both
4) Put timelines Arrow_L and Arrow_R inside Arrow_Both timeline and adjust them a bit.
5) Close the tab of Arrow_Both
6) Done. The engine's crashed.

**Comment by DiegoScirra** [comment]
I was able to fix the last issue and it will be available in the next beta, but I think it was a different problem.

Following those steps, making the editor crash and then saving does not produce a corrupted save file like the one in your first post. I will continue to investigate this issue.

**Comment by DiegoScirra** [comment]
Found the cause for the original issue, the fix for it will be available in the next beta.
