### ISSUE TITLE
Beta 272 sdk issue

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#5245]
## Problem description

Beta 272 crashes with installed third party addons.
## Attach a .c3p
Project made in 271-2:
https://www.dropbox.com/s/e0byr6u4bdo2uig/test.c3p?dl=1
Third party addon used:
https://www.construct.net/en/make-games/addons/562/fast-radial-progress-bar

## Steps to reproduce

1.Install the third party behavior.
2.
3.

## Observed result
The editor will crash

## Expected result
No crash

## More details

If you already have the behavior installed from 271-2 the editor will also crash, which is what is happening to everyone else.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is a bug in the latest version of Closure Compiler that incorrectly transforms our code. I filed it here: https://github.com/google/closure-compiler/issues/3891

I think we can do a hotfix tomorrow and just use the previous version of Closure Compiler that worked.

**Comment by AshleyScirra** [comment]
Should be fixed in r272.2.

**Comment by pigmalien** [comment]
Thanks!
