### ISSUE TITLE
Sub layers: visibility switch minor bug

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-3-bugs#5246]
## Problem description

It takes 2 clicks to turn on invisible layer which is a sub-layer of another invisible layer

## Attach a .c3p

Use blank project

## Steps to reproduce

1. Create a layer and sub-layer
2. Turn them insvisible
3. Try to switch on the sub-layer

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r272

**Comment by AshleyScirra** [comment]
This is currently by design. Parent layers are responsible for drawing its sub-layers, and so a layer and all its parent layers must be set visible for it to appear.

**Comment by elfwy-uwu** [comment]
@AshleyScirra 

I'm not sure you understood it correctly. What i mean is after clicking a checkbox of invisible layer it remains unchecked, until you click it one more time. Thus, when you activate a parent layer, sub-layer appears to be visible, even while checkbox is uncheked. Attaching gif to show it

![layers](https://user-images.githubusercontent.com/15311427/142440400-7be24220-6dc5-460f-ba5b-daa07051cbbf.gif)

**Comment by AshleyScirra** [comment]
OK, I'll take a look. It's good to fill out all the fields of bug reports as per the guidelines - they are there to help avoid confusion like this.

**Comment by AshleyScirra** [comment]
Minimal repro for reference:
[issue5246.zip](https://github.com/Scirra/Construct-3-bugs/files/7571805/issue5246.zip)

**Comment by AshleyScirra** [comment]
Fixed for next beta.
