### ISSUE TITLE
Pathfinding finds path to unreachable point

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-3-bugs#5253]
## Problem description

When using pathfinding, I believe it is returning an incorrect value when trying to find a path that is located on an obstacle. Instead of returning 'failed to find path', the plugin sets a path closest to the destination point which is not ideal in certain situations and is problematic when writing AI systems that need to determine if they can get to random points in a layout

## Attach a .c3p
[pathfinding issue.zip](https://github.com/Scirra/Construct-3-bugs/files/7573800/pathfinding.issue.zip)

## Steps to reproduce

1. Click to send sprite to mouse position 
2. Note that it cannot find a path into the first square but can in the second, single solid
3. Note that the positional target changes depending on where in the 2nd box is clicked, giving inconsistent results.

## Observed result

Sprite will attempt to move as close to the path target as possible

## Expected result

The system should return 'failed to find path'. This seems like the logical result when trying to find a path that is unreachable.

**Comment by AshleyScirra** [comment]
This is currently by design. If you try to find a path to an obstacle, it will try to find a path to the nearest clear cell instead. If you try to find a path to a clear cell that is unreachable, such as being completely cut off, then it will trigger "failed to find path".
