### ISSUE TITLE
8-Direction moves diagonally when using 4-Directions and 90-intervals rotation

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5254]
## Problem description

I used 8-Direction behavior and intended to make an object that moves in 4-directions only, and rotates sharply at 90 degrees intervals. I was able to set these parameters in the behavior properties. But in some cases while clicking 2 arrow buttons at the same time, it moves diagonally for a split second before moving straight again.

## Attach a .c3p

[Bug Diagnoal.zip](https://github.com/Scirra/Construct-3-bugs/files/7574041/Bug.Diagnoal.zip)

## Steps to reproduce

1. Run the project.
2. Move right for a few seconds.
3. Move down for a few seconds.
4. Move in 2 directions at the same time for a few seconds.
5. You can repeat step 4 multiple times, but each one for a split second.

## Observed result

The object turns in a curve. If you disable the DrawingCanvas, you will notice the diagonal move more clearly. For a split second (while rotating), the object appears to be moving diagonally.

## Expected result

Sharp 90-degrees turns.

## More details
I was able to produce the desired 90 degrees sharp turns by disabling the default controller and making my own movement controller. The trick was to set the movement vector of an axis to 0 before moving on the other axis.
E.g. moving right :: set vectorY = 0 then simulate moving right.

It seems the object rotates (internally) smoothly, but the sprite is rotated in 90 degrees intervals. When you look at the curve it leaves (the curve is drawn based on X,Y of the object) it rotates in smooth curves, while the sprite doesn't.
This mismatch between the internal rotation and the sprite rotation is what I think causes the object to look like it is moving diagonally.

**Affected browsers/platforms:** Firefox 94.0.1

**Comment by AshleyScirra** [comment]
This is currently by design. 4 direction movement means the object can only accelerate in 4 directions. However if it is decelerating on a different axis, this means you can get brief periods of moving diagonally, hence why the example draws curves. Try setting the deceleration to a high value like 99999 and it will work more like you want to, as it means as soon as you start accelerating in a different direction, the previous movement decelerates away almost instantly.
