### ISSUE TITLE
First person view does not hold aspect ratio

### ISSUE THREAD

**Issue by rogerty** [Scirra/Construct-3-bugs#5256]
When you change the viewport in the C3 included demo "First-person shooter", the aspect ratio of what is on screen is not ideal anymore.
The demo starts in viewport size 854 x 480. (16:9)

When I change the viewport size to one of these two:
500x281 (16:9)
300x168 (16:9)
Then everything seems stretched when I run the game.

Because I kept the ratio the same (16:9), I was expecting to see the same aspect ratio as in the starting size (854x480), but in a smaller viewport.
However, I get to see a stretched view of the world. 

## Steps to reproduce

1. Open the First-Person Shooter demo, included in C3.
2. Run the game and look at how the aspect ratio looks like.
3. Decrease the viewport to 500x281 (keeping the 16:9 ratio)
4. Notice how the aspect ratio is out of place, compared to the  original viewport dimensions. All objects are more "fat" (increased widthness) now.

## Observed result

When changing the viewport, keeping it in 16:9 ratio.
The aspect ratio is out of place, compared to the  original viewport dimensions. All objects are more "fat" (increased widthness) now.

## Expected result

Because the ratio was still 16:9, I expected to see a smaller window, but with proper aspect ratio of all objects.

## More details

**Affected browsers/platforms:** 

**First affected release:** I only noticed it this week, never tried this before.

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r272.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 1.2 gb (0.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon R7 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.1034.6)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is currently by design as I explained in this forum post: https://www.construct.net/en/forum/construct-3/how-do-i-8/viewport-work-3d-165304#forumPost1056944
