### ISSUE TITLE
Timeline crashes Construct

### ISSUE THREAD

**Issue by psychoanima** [Scirra/Construct-3-bugs#5259]
## Problem description

Timeline is crashing construct

## Attach a .c3p

It's not for public.

## Steps to reproduce

I create 2nd timeline, did few tests. When I wanted to close timeline bar crash message with error report information.

1. created 1st timeline
2. created 2nd
2. manage keyframes
3. didt few tests
4. closed timeline bar
5. crash

## Observed result

Error report information

## Expected result

To continue working on my game

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'Xs') @ TypeError: Cannot read properties of undefined (reading 'Xs') at d.BBa (https://editor.construct.net/r268/projectResources.js:815:88) at oBa (https://editor.construct.net/r268/projectResources.js:73:146) at d.oa (https://editor.construct.net/r268/projectResources.js:827:447) at d.VA (https://editor.construct.net/r268/projectResources.js:828:145) at Function.h5.OJb (https://editor.construct.net/r268/components/bars/timelineBar/timelineBar.js:392:74) at Function.h5.Sna (https://editor.construct.net/r268/components/bars/timelineBar/timelineBar.js:390:154) at window.Jb.$l.A (https://editor.construct.net/r268/components/bars/timelineBar/timelineBar.js:220:188) at d.B2.Gr (https://editor.construct.net/r268/components/bars/timelineBar/timelineBar.js:108:130) at d.B2.ICb (https://editor.construct.net/r268/components/bars/timelineBar/timelineBar.js:111:286) at d.A (https://editor.construct.net/r268/components/bars/timelineBar/timelineBar.js:32:462)
Stack: TypeError: Cannot read properties of undefined (reading 'Xs') at d.BBa (https://editor.construct.net/r268/projectResources.js:815:88) at oBa (https://editor.construct.net/r268/projectResources.js:73:146) at d.oa (https://editor.construct.net/r268/projectResources.js:827:447) at d.VA (https://editor.construct.net/r268/projectResources.js:828:145) at Function.h5.OJb (https://editor.construct.net/r268/components/bars/timelineBar/timelineBar.js:392:74) at Function.h5.Sna (https://editor.construct.net/r268/components/bars/timelineBar/timelineBar.js:390:154) at window.Jb.$l.A (https://editor.construct.net/r268/components/bars/timelineBar/timelineBar.js:220:188) at d.B2.Gr (https://editor.construct.net/r268/components/bars/timelineBar/timelineBar.js:108:130) at d.B2.ICb (https://editor.construct.net/r268/components/bars/timelineBar/timelineBar.js:111:286) at d.A (https://editor.construct.net/r268/components/bars/timelineBar/timelineBar.js:32:462)
Construct 3 version: r268
URL: https://editor.construct.net/
Date: Sun Nov 21 2021 00:23:12 GMT+0100 (Central European Standard Time)
Uptime: 12.6 s

Platform information
Browser: Edge
Browser version: 95.0.1020.53
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53
C3 release: r268 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-25.20.100.6577)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by elfwy-uwu** [comment]
@psychoanima 

You'd better provide minimal .c3p for the issue, otherwise devs won't be able to reproduce it.

**Comment by elfwy-uwu** [comment]
Actually for me timiline is also throwing crashes like this a lot. But I can't figure out any single subsequence.

**Comment by DiegoScirra** [comment]
```
3. manage keyframes
4. did a few tests
```

That is too vague, there doesn't appear to be anything wrong by just creating timelines and doing some changes, this could be a very specific case.

Have any of you been trying to use nested timelines? The crash suggests it has something to do with that. A few issues relating to closing the Timeline bar while showing nested timelines were fixed in r273 so this might be the same as that.

**Comment by psychoanima** [comment]
@DiegoScirra Here is the project, I removed many things from it but error is there. Try opening and closing "Timeline 1"

[https://1drv.ms/u/s!AtMv1SrHrjT3gaMvMkfw6vmqE3r7ww?e=TuwtoT](url)

**Comment by DiegoScirra** [comment]
That issue was fixed in the latest beta.

**Comment by DiegoScirra** [comment]
I'm going to close this now, as going any further will just be looking into different issues.

If you find any more problems just file a new report.
