### ISSUE TITLE
Dark theme: comments already in Italic so the [i] is useless

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#526]
## Problem description

Greetings

I know it's a matter of style but I really don't think the comments should be in italic since we have the [i] [/i] if we want that. I understand the use of the // at the beginning to show that it's a comment so that's pretty cool, but the italic .... I don't think it's too good to use it by default.

I kinda get the point of using italic aswell, but I don't think a theme should overwrite text formatting.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
![image](https://user-images.githubusercontent.com/7268697/27248317-84815036-530a-11e7-8a35-456bc60a74c1.png)

**Comment by AshleyScirra** [comment]
If the comment is already italic, I guess [i] should actually revert to non-italic.

**Comment by Animmaniac** [comment]
The italic for comments helps to quickly scan the event sheet and easily spot what's an event from what is a comment, it greatly improves readability. Lot's of editors for traditional programming languages also use it for the same reason. I think it's a good idea to maintain them.

Ashley's idea seems the best solution for me. I'll try to implement it for the next iteration.

**Comment by JeFawk** [comment]
The middle solution that Ashley suggested sounds good, thanks for implementing it.

Regarding the editors and the visibility, I'll have to politely disagree. 
The comments stick out a lot from the code block. When you scroll through the event sheets the Italics really doesn't stick out at all.
![image](https://user-images.githubusercontent.com/7268697/27280948-87000bba-54f2-11e7-8080-d198edaafa72.png)

And the most used IDE's such as Visual Studio, Net Beans, Eclipse and Xcode by default do not have their comments in Italics. There are options to set them so though.

**Comment by JeFawk** [comment]
If you could implement the same thing in Groups that would be great btw.

![image](https://user-images.githubusercontent.com/7268697/27309403-4596a200-555c-11e7-9e48-6ae223831aae.png)

**Comment by Animmaniac** [comment]
What I meant was that comments being italic, in contrast with events in normal text style, makes easier to tell them apart at a glance then if they had all the same style. The italic markers are totally invisible right now and that was an oversight on my part. But it should be fixed for the next iteration, both for groups' descriptions and comments.

**Comment by JeFawk** [comment]
Any possibility of adding a [code] block to make the text inside it appear as Consolas font and maybe inside a box?
