### ISSUE TITLE
Scene graph: deleting all instances curses the only remaining object

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-3-bugs#5260]
## Problem description

In editor objects keep hierarchy menu even after all instances of hierarchy were deleted. I guess this is made for "undo/redo" to be possible. But there're cases when this behaviour of hierarchy can cause crashing. In fact, i found 2 different subsequnces which brought me to different crash dialogues, but there's a single origin leading to this - **undo to the moment when there's is only one object left in hierarchy**

## Attach a .c3p

https://drive.google.com/file/d/1oMUfwM80gfWj-aDSrNzmxXX3E0tcis97/view?usp=sharing

## Steps to reproduce

**Case 1: Cursed child**
1. Delete parent instance
2. Left click on single instance that left, "Hierarchy" menu remained even while hierarchy itself doesn't exist anymore
3. Right click -> Hierarchy (also remained for some reason) -> Remove from parent
4. Undo

**Case 2: Cursed parent**
1. Delete child instance
2. Click instance, same thing with "Hierarchy" menu as in 1st case. _But there's no hierarchy actions on right click._
3. Copy this sprite. _All copies of this sprite will have ghost hierarchy, which probably actually exists in the engine but it's empty._
4. Create new hierarchy with them. Cursed object has to be parent (in case you create new object instead copying at step 3).
5. Undo

## Observed result

Crash dialogue.

## Expected result

Well, this subsequences don't make a lot of sense, but crashes are something we are trying to avoid, right?

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r254 _(scene graph added)_

## System details

<details><summary>View details (Case 1)</summary>

Error report information
Type: unhandled rejection
Reason: Error: cannot set deleted instance's UID @ Error: cannot set deleted instance's UID at d.WLb (https://editor.construct.net/r272-2/projectResources.js:698:97) at d.ILb (https://editor.construct.net/r272-2/projectResources.js:707:343) at d.Ga (https://editor.construct.net/r272-2/projectResources.js:752:499) at YVa.Vm.sf (https://editor.construct.net/r272-2/projectResources.js:1657:41) at XL.Vza.sf (https://editor.construct.net/r272-2/projectResources.js:1643:405) at window.vc.Ih (https://editor.construct.net/r272-2/projectResources.js:1647:19) at d.Ih (https://editor.construct.net/r272-2/projectResources.js:1531:198) at window.a5a.Ih (https://editor.construct.net/r272-2/main.js:2285:214) at Array. (https://editor.construct.net/r272-2/main.js:2258:414) at window.a5a.dispatchEvent (https://editor.construct.net/r272-2/main.js:1044:398)
Stack: Error: cannot set deleted instance's UID at d.WLb (https://editor.construct.net/r272-2/projectResources.js:698:97) at d.ILb (https://editor.construct.net/r272-2/projectResources.js:707:343) at d.Ga (https://editor.construct.net/r272-2/projectResources.js:752:499) at YVa.Vm.sf (https://editor.construct.net/r272-2/projectResources.js:1657:41) at XL.Vza.sf (https://editor.construct.net/r272-2/projectResources.js:1643:405) at window.vc.Ih (https://editor.construct.net/r272-2/projectResources.js:1647:19) at d.Ih (https://editor.construct.net/r272-2/projectResources.js:1531:198) at window.a5a.Ih (https://editor.construct.net/r272-2/main.js:2285:214) at Array. (https://editor.construct.net/r272-2/main.js:2258:414) at window.a5a.dispatchEvent (https://editor.construct.net/r272-2/main.js:1044:398)
Construct 3 version: r272.2
URL: https://editor.construct.net/r272-2/
Date: Tue Nov 23 2021 10:16:55 GMT+0500 (Екатеринбург, стандартное время)
Uptime: 68.6 s

Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r272.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

<details><summary>View details (Case 2)</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading '0') @ TypeError: Cannot read properties of null (reading '0') at uv.zFb.dUa (https://editor.construct.net/r272-2/projectResources.js:772:242) at FBa (https://editor.construct.net/r272-2/projectResources.js:69:61) at uv.zFb.ZW (https://editor.construct.net/r272-2/projectResources.js:771:459) at d.Ga (https://editor.construct.net/r272-2/projectResources.js:754:37) at YVa.Vm.sf (https://editor.construct.net/r272-2/projectResources.js:1657:41) at XL.Vza.sf (https://editor.construct.net/r272-2/projectResources.js:1643:405) at window.vc.Ih (https://editor.construct.net/r272-2/projectResources.js:1647:19) at d.Ih (https://editor.construct.net/r272-2/projectResources.js:1531:198) at window.a5a.Ih (https://editor.construct.net/r272-2/main.js:2285:214) at Array. (https://editor.construct.net/r272-2/main.js:2258:414)
Stack: TypeError: Cannot read properties of null (reading '0') at uv.zFb.dUa (https://editor.construct.net/r272-2/projectResources.js:772:242) at FBa (https://editor.construct.net/r272-2/projectResources.js:69:61) at uv.zFb.ZW (https://editor.construct.net/r272-2/projectResources.js:771:459) at d.Ga (https://editor.construct.net/r272-2/projectResources.js:754:37) at YVa.Vm.sf (https://editor.construct.net/r272-2/projectResources.js:1657:41) at XL.Vza.sf (https://editor.construct.net/r272-2/projectResources.js:1643:405) at window.vc.Ih (https://editor.construct.net/r272-2/projectResources.js:1647:19) at d.Ih (https://editor.construct.net/r272-2/projectResources.js:1531:198) at window.a5a.Ih (https://editor.construct.net/r272-2/main.js:2285:214) at Array. (https://editor.construct.net/r272-2/main.js:2258:414)
Construct 3 version: r272.2
URL: https://editor.construct.net/r272-2/
Date: Tue Nov 23 2021 10:18:55 GMT+0500 (Екатеринбург, стандартное время)
Uptime: 23.6 s

Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r272.2 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
These issues will be fixed in the next beta.
