### ISSUE TITLE
Save Slots no longer work correctly

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#5262]
## Problem description

In 273 game save slots no longer save the state of everything. Behaviors, and hierarchies seem to be broken. 
## Attach a .c3p

https://www.dropbox.com/s/gyb5rmm132v7c7b/saveslot273.c3p?dl=1
## Steps to reproduce

1. Run the project. Its the Skelton hierarchy demo
2. Save the game by clicking "Save Me", be sure to note the state of the bones at the time.
3. Refresh the browser. The events will read from Local Storage and load the game save.
4. Note the state of loaded bones.

## Observed result

The behaviors are no longer working.
The bones seem to no longer be connected.
## Expected result
The load should show the state as it was saved.

## More details

Click clear storage, and refresh to retest.

**Affected browsers/platforms:** 

**First affected release:** 
273, (perhaps 272, 272.2, I didn't check those}
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta. Was a regression relating to the changes to improve the performance of tweens and timelines.

**Comment by pigmalien** [comment]
Alright, thanks!
