### ISSUE TITLE
r273 invert crash.

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-3-bugs#5263]
## Problem description

Inverting events is broken in r273, causing crash.

I am so lucky with all these crashes today 

## Attach a .c3p

https://drive.google.com/file/d/1owVWrNmzlRDyYqhtfQhO3yHI-iDAikko/view?usp=sharing

## Steps to reproduce

1. Right click on event -> Invert

## Observed result

Crash dialogue

## Expected result

No crash dialogue

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r273

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r273/components/editors/eventSheetView/eventSheetView.js, line 98, col 53
Message: Uncaught TypeError: H9a.oAc is not a constructor
Stack: TypeError: H9a.oAc is not a constructor at d.FHb (https://editor.construct.net/r273/components/editors/eventSheetView/eventSheetView.js:98:53) at https://editor.construct.net/r273/components/editors/eventSheetView/eventSheetView.js:93:458 at https://editor.construct.net/r273/main.js:1678:100
Construct 3 version: r273
URL: https://editor.construct.net/r273/
Date: Tue Nov 23 2021 23:34:52 GMT+0500 (Екатеринбург, стандартное время)
Uptime: 2296.9 s

Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r273 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by beebits** [comment]
I have the same problem.

**Comment by Aurelregard** [comment]
Glad I'm not alone with this issue.
Trying to invert any condition makes Construct r273 crash here as well.

**Comment by beebits** [comment]
Yeah, I need them to fix it, cause I can't continue my program with C3.

**Comment by beebits** [comment]
In Firefox also have the same error.

Error report information

Type: unhandled exception
File: https://editor.construct.net/r273/components/editors/eventSheetView/eventSheetView.js, line 98, col 53
Message: TypeError: H9a.oAc is not a constructor
Stack: FHb@https://editor.construct.net/r273/components/editors/eventSheetView/eventSheetView.js:98:53 $w/<@https://editor.construct.net/r273/components/editors/eventSheetView/eventSheetView.js:93:458 Ed/<@https://editor.construct.net/r273/main.js:1678:100
Construct 3 version: r273
URL: https://editor.construct.net/r273/
Date: Wed Nov 24 2021 12:56:33 GMT+0100 (hora estándar de Europa central)
Uptime: 72 s
Platform information

Browser: Firefox
Browser version: 81.0
Browser engine: Gecko
Context: browser
Operating system: Mac OS X
Operating system version: 10
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:81.0) Gecko/20100101 Firefox/81.0
C3 release: r273 (beta)
Language setting: es-ES
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by Aurelregard** [comment]
beebits >not sure if useful, but just in case, here's a quick reminder if you're stuck and don't know how to continue your work.

1 - download your current project as a c3p file.
2 - open your c3p file using a zip file manager like winrar.
3 - find the project.c3proj file et open it using notepad.
4 - rename 27300 as 27200 and save.
5 - open your updated c3p project using https://editor.construct.net/r272-2/

tadaa, back in business : )

**Comment by beebits** [comment]
Thanks!!!!!!!!!

**Comment by armandoalonso** [comment]
it also happens you use the shortcut for OR as well

**Comment by beebits** [comment]
I hope this could be fixed as soon as possible.

**Comment by AshleyScirra** [comment]
Thanks for the report, fixed for next beta. Leaving this issue open as it will probably be a fairly common issue.

BTW:

> it also happens when you use the shortcut for OR as well

I can't reproduce this, it seems to work fine. If you want this investigated you'll need to file a separate issue also following all the guidelines.

**Comment by beebits** [comment]
Thanks @AshleyScirra

**Comment by boogiecreations** [comment]
I tested it in Edge as well (not sure who uses that browser) and it crashes there as well.

Once I made the change in notepad, I zipped the file and renamed it .c3p but that isn't working when I try to open with C3.  Help on the step between 4 and 5 that @Aurelregard posted above.  Thanks.

**Comment by Aurelregard** [comment]
Boogiecreations > Hi! Here's the safest way to do it without getting an error from Construct after the modifications :

Don't extract or rename your files. Open your c3p file directly using Winrar (don't rename as .zip) and then open and modify your project.c3proj using notepad from Winrar as well.
Once modified, Winrar will ask if you want to update the archive, say yes, and you'll be good to go.

**Comment by boogiecreations** [comment]
> Boogiecreations > Hi! Here's the safest way to do it without getting an error from Construct after the modifications :
> 
> Don't extract or rename your files. Open your c3p file directly using Winrar (don't rename as .zip) and then open and modify your project.c3proj using notepad from Winrar as well. Once modified, Winrar will ask if you want to update the archive, say yes, and you should be good to go.

Brilliant!!!  Just did it and I'm up/running.  Thank you!  (Happy Thanksgiving)

**Comment by AshleyScirra** [comment]
Should be working in r274.
