### ISSUE TITLE
Whitelist plugins (routine maintenance)

### ISSUE THREAD

**Issue by invictus9860** [Scirra/Construct-3-bugs#5264]
Hi,

Would you please whitelist the following plugins:

com.google.payments
https://github.com/MobileChromeApps/cordova-plugin-google-payments

cordova-plugin-apple-pay-google-pay-with-environment
https://npm.io/package/cordova-plugin-apple-pay-google-pay-with-environment

Reason:  Cordova integration with Google Pay API.

I have followed the required guidelines to my knowledge, please let me know if there are issues with my request.
Thank you.

**Comment by AshleyScirra** [comment]
`com.google.payments` appears to be 6 or 7 years old and retired, as the repository is archived. This suggests it has been retired and is no longer maintained. The plugin may in fact no longer work at all if it's not been maintained that long.

Why do you need it? Have you tested it to ensure it works correctly still before requesting it for the build service? If you haven't tested it yet, please make sure you test both plugins before requesting them for the build service - I don't want to have to security review things just for testing.

**Comment by AshleyScirra** [comment]
No answer after a week so closing request.
