### ISSUE TITLE
Open the camera in Android

### ISSUE THREAD

**Issue by AboJood2** [Scirra/Construct-3-bugs#5268]
My app connects with the device camera and displays it on screen. Everything works in the browser, and even on my mobile via remote preview.

But, as soon as it is an APK (or debug APK), the camera request is not complete. I check the app permission requests, and there's no request for the camera to be used.

Note: I have checked the box to "require camera permission" on APK export.

Anyone know a solution?

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines, as we need that information to be able to help.

**Comment by AboJood2** [comment]
I do not know how to deal with your message .. I am a big fan of your
program .. Please solve my problem by opening the camera on Android!!

في الخميس، ٢٥ نوفمبر ٢٠٢١ ٣:٥٧ م Ashley (Scirra) ***@***.***>
كتب:
