### ISSUE TITLE
No way to pick object just created by name

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#527]
## Problem description

There's this cool System action to create an object by its name but there's no way to pick it up (not that I've found anyway). So if I create it, I can't assign it an instance var and basically, I can't do anything with it.

A **Pick last created by name** condition would be great! Otherwise, it's useless.

## Attach a .c3p

![image](https://user-images.githubusercontent.com/7268697/27248603-962e7e2c-530e-11e7-9a37-90c2bdf0706b.png)

![image](https://user-images.githubusercontent.com/7268697/27248606-a6eeed6e-530e-11e7-9ebf-dc322d353135.png)

**Comment by AshleyScirra** [comment]
Implementation may be tricky due to sub-event SOL optimisation algorithm.

**Comment by AshleyScirra** [comment]
Actually, a better reason not to do this is the same reason I posted in this comment from issue #533: https://github.com/Scirra/Construct-3-bugs/issues/533#issuecomment-309397311

This feature essentially breaks "find all references" in a way much worse than in issue #533: it will create entire sub-trees of events that are ambiguous and cannot be proven to refer to any particular kind of object. This is probably a good enough reason not to implement this at all.

Perhaps a better feature would be simply a "pick last created" action. This doesn't involve any string names and still solves your case.

**Comment by JeFawk** [comment]
Pick last created sounds great, I'll use that tracker for ideas instead of github, I wasn't aware of it.
