### ISSUE TITLE
Drawing Canvas with 3d camera

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#5270]
## Problem description

Drawing Canvas does not render correctly when used in 3d layers with 3d camera
## Attach a .c3p

https://www.dropbox.com/s/t9691iahha6oz02/dc3d.c3p?dl=1
## Steps to reproduce

1.Run the project
2.Drag the black object around
3.Drag the white object around

## Observed result

The Drawing Canvas is being cut off in parts of the render.
## Expected result
The Drawing Canvas should render the same as the Sprite.

## More details

**Affected browsers/platforms:** 

**First affected release:** 
273? Haven't checked others
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I think the current design of Drawing Canvas means it cannot support 3D layers. The resolution scaling approach (i.e. deciding how large the surface should be in device pixels) relies on 2D calculations to match its appearance on-screen, and this is then in turn used to calculate a scale factor for drawing commands. Once there is a 3D perspective none of these calculations are correct any more, nor is there an obvious solution, unless a different scaling system is implemented. This could be tracked as a feature request, but for now closing as wontfix, and I've added a note to the manual entry to mention Drawing Canvas is only supported on 2D layers.

**Comment by pigmalien** [comment]
That kind of complicates Drawing Canvas having a mesh with z's.
Should that feature be removed? 
Could Sprite, Tiled BG vertex color filters be a solution?
Thanks.
