### ISSUE TITLE
Suggestions for expressions do not appear when referencing object IID in expression

### ISSUE THREAD

**Issue by calminthenight** [Scirra/Construct-3-bugs#5271]
## Problem description

The editor does not suggest relevant expressions following a full stop if the object's IID has been referenced in brackets.

For Example:

You type "object." and are presented with a list that only contains valid expressions related to that object.

You type "object(0)." and and aren't presented with any valid expressions.

Just a UX issue.

## Attach a .c3p

https://1drv.ms/u/s!AkmrWgxeuxlKhItry-3ZRGqUhCu-bA?e=dY5ThE

## Steps to reproduce

1. Open project and add an Evaluate Expression condition
2. Enter: "Sprite." (You will see a list of suggested expressions relevant to the "Sprite" object).
3. Clear that and enter "Sprite(0)." (no list of suggested expressions relevant to the "Sprite" object are presented).

## Observed result

Suggested expressions relevant to the object do not appear when you reference an objects index number in brackets.

## Expected result

Suggested expressions should appear, consistent with the behaviour of the editor when not referencing the object's Index number.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r268 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 119 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9365)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is currently intentional - Construct doesn't make an attempt to parse such cases, because it's difficult to parse it. You could have `Sprite(<some arbitrarily long and complex expression).` - autocompleting that means having to parse and backtrack over the arbitrarily long and complex expression to find the "Sprite" part and hence know what to autocomplete. Given that the instance indexing feature is AFAIK rarely used, it's difficult to justify the complicated work to support this. So I think it would be best to track this as a feature request here: https://construct3-21h2.ideas.aha.io/

**Comment by calminthenight** [comment]
I figured that was probably the case. AFAIK though there is nothing else that can be used after the object name, within brackets, and before the first full stop other than the Index reference. So the complexity of the expression within the brackets isn't important. You should just be able to parse all text within the brackets prior to the first full stop.
