### ISSUE TITLE
Build Service

### ISSUE THREAD

**Issue by Ocsid** [Scirra/Construct-3-bugs#5272]
## Problem description
Fail to build signed android .aab

## Steps to reproduce

1.
2.
3.

## Observed result

error log msg:
"Error: Platform 'android' found in config.xml... Migrating it to package.json
Discovered platform "android". Adding it to the project
Using cordova-fetch for cordova-android@10.1.0

Failed to fetch platform cordova-android@10.1.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform ~~/URL.
CordovaError: Error: npm: Command failed with exit code null"

## Expected result

download link for complete build

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's impossible to investigate this without the details we ask for.

BTW there was a brief outage on the build service and it should now be back up and running, so maybe just try again, and it might work this time.

**Comment by Ocsid** [comment]
Of course it was the build service outage, apart from timeout messages and no connection errors, I got the message mentioned above.
Thought it might help you in your investigation to what causes the recent build service outages...
Take it or leave it.
