### ISSUE TITLE
Apk fails to develop when special characters are used in the name

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#5275]
Maybe not a bug, but this MUST be reported to user that they can't use special characters in name for APKs

For example:- project name "Food & Drink Pixel Art Color" will generate an error during APK export, however "Food Drink Pixel Art Color" will not generate an error & user will get an APK from online scirra servers.

User must be notified of such errors,otherwise they will believe that there is an issue from scirra side

**Comment by layilpaht** [comment]
Also there are some special unique cases too:-
1.) if ID contains reserved words then again apk process will fail 
for example "com.cascade.pixel.color.abstract" will result in an error whereas "com.cascade.pixel.color.abstracto" will not & user will get an APK from online scirra servers. Why? Because "abstract is a reserved word in java (something like that)". I think that such types of errors should also be reported to the user otherwise they will think that servers are not working

**Comment by AshleyScirra** [comment]
Minimal repro as none provided:
[Ghost&Shooter.zip](https://github.com/Scirra/Construct-3-bugs/files/7618069/Ghost.Shooter.zip)

We might not be able to fix every case. If Cordova or Android/iOS have naming rules that disallow certain names, we can't make them allowed, only perhaps warn about them in the editor.

**Comment by layilpaht** [comment]
You took me wrong

I am not saying that allow disallowed characters (that is impossible). I am just saying to notify the user about it. Like Message "wrong characters used" should get displayed

Also I have noticed that if : is used in the project name, it disappears. Maybe use same approach with other characters

**Comment by AshleyScirra** [comment]
This looks like a bug in cordova-android that was already filed here: https://github.com/apache/cordova-android/issues/1380

Closing as will follow-up there.
