### ISSUE TITLE
OSX only NW.js export bug

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#5279]
## Problem description

I realized that my project works fine when exported with nw.js on windows, but it stopped working correctly on OSX as nw.js export. In the browser preview in construct 3 it works fine.
## Attach a .c3p

[a_Bug_OSX_JS_07.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/7637543/a_Bug_OSX_JS_07.c3p.zip)

## Steps to reproduce

1.open project on a mac, preview project (you need audio)
2.click on the green square once, then click wildly in quick succession and listen to the result
3. now export it to nw.js, all three options enabled (minify advanced, or no minification- same result). 
4. latest Chromium 95, Mac 64,  package assets, Window Frame, Rezisable, Ignore Blacklist enabled
5. start exported project, repeat step 2

## Observed result

-previewed Project plays sound always in rhythm
-osX nw.js exported project plays sound quickly as soon as you start to click in quick succession

## Expected result

should always play sound in rhythm

## More details

-works on windows, worked some time ago fine on OSX,  but I have not tested it for a while.

**Affected browsers/platforms:** 

**First affected release:** 
Problem exist with the latest Beta r274 and also with the latest stable r268
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 96.0.4664.55
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36
C3 release: r274 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 5.9 gb (2.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 630
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I can reproduce an apparent timing difference. However with around 100 events the project is too complex to rule out this somehow being a mistake in the events. Please see the bug report guidelines.

Further it looks like the schedule-ahead time is very small (0.02 seconds). The 'Audio scheduling' example uses a schedule-ahead time of 0.5 seconds. It may just be that you're not scheduling far enough ahead of time.

**Comment by bubbblebub** [comment]
thanks for the answer, I just filed a new report with a much less complex file and a different way to reproduce it
