### ISSUE TITLE
Image Editor Thumbnail can't be small or medium size in height

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#528]
## Problem description

*when we want to make small size of thumbnail in image editor But only width wise its changing but not changing in height wise*

## Attach a .c3p

*no need*

## Steps to reproduce

1.no steps required
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please always follow the guidelines otherwise it's impossible to understand what you mean.

**Comment by luckyrawatlucky** [comment]
![difference](https://user-images.githubusercontent.com/17684135/27280577-0373fc02-5506-11e7-9f7e-d76caafe4a81.jpg)
This is what i am talking

**Comment by DiegoScirra** [comment]
Fixed in r40
