### ISSUE TITLE
Games are bloking on Facebook when upload it as zipped HTML5 game as playable

### ISSUE THREAD

**Issue by 1mrpaul1** [Scirra/Construct-3-bugs#5280]
## Problem description

Facebook blocks the construct games when uploading them in a format of html5 in a zip archive as a playable ad with resource folders.

Any, even empty project

## Steps to reproduce

1. create an empty project
2. export as html5
3. archive as zip
4. upload at https://developers.facebook.com/tools/playable-preview/

Result - black empty screen.  The game is blocking with the error
![Без названия](https://user-images.githubusercontent.com/64515864/144454594-59683faf-8b85-4daf-9b5b-3ae6d067389d.png)

## Expected result

game got to start to play

## More details
AddDOMHandlerClass
main.js:1822 if (window["C3_IsSupported"])
main.js:350 window.RuntimeInterface
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:437 _Init
main.js:1766 self.JobSchedulerDOM = class JobSchedulerDOM
main.js:408 GetBaseURL
main.js:416 GetExportType
main.js:424 GetScriptFolder
main.js:1778 Init
main.js:471 _GetWorkerURL
main.js:478 CreateWorker
main.js:1790 _CreateJobWorker
main.js:471 _GetWorkerURL
main.js:478 CreateWorker
main.js:573 _InitDOM
main.js:1175 HANDLER_CLASS
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:737 AddRuntimeComponentMessageHandler
main.js:404 GetCanvas
main.js:432 IsiOSWebView
main.js:752 _FindRuntimeDOMHandler
main.js:845 _MaybeGetCordovaScriptURL
main.js:265 AddScript https://apps-1674532876158279.apps.fbsbx.com/instant-bundle/2417149408390084/4308531905936698/scripts/c3runtime.js
main.js:275 new Promise(
main.js:506 _GetCommonRuntimeOptions
main.js:498 _GetWindowInnerWidth
main.js:502 _GetWindowInnerHeight
main.js:768 IsDocumentFullscreen
main.js:1808 GetPortData
main.js:428 IsiOSCordova
main.js:432 IsiOSWebView
main.js:627 _OnBeforeCreateRuntime
main.js:631 _RemoveLoadingMessage
index.html?__cci=FQAREREA.ARaBfI9liJyviizXDFTObKWd8cvJEvRc34CEdXedSrENIsiO:604 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'then')
    at Function.FetchOk (index.html?__cci=FQAREREA.ARaBfI9liJyviizXDFTObKWd8cvJEvRc34CEdXedSrENIsiO:604)
    at Function.FetchText (index.html?__cci=FQAREREA.ARaBfI9liJyviizXDFTObKWd8cvJEvRc34CEdXedSrENIsiO:604)
    at AssetManager.FetchText (index.html?__cci=FQAREREA.ARaBfI9liJyviizXDFTObKWd8cvJEvRc34CEdXedSrENIsiO:1469)
    at AssetManager.FetchJson (index.html?__cci=FQAREREA.ARaBfI9liJyviizXDFTObKWd8cvJEvRc34CEdXedSrENIsiO:1469)
    at C3Runtime.Init (index.html?__cci=FQAREREA.ARaBfI9liJyviizXDFTObKWd8cvJEvRc34CEdXedSrENIsiO:3120)
    at self.C3_InitRuntime (index.html?__cci=FQAREREA.ARaBfI9liJyviizXDFTObKWd8cvJEvRc34CEdXedSrENIsiO:3215)
    at RuntimeInterface._InitDOM (main.js:618)
    at async RuntimeInterface._Init (main.js:468)

**Comment by AshleyScirra** [comment]
If I follow these steps all that happens is the tool incorrectly states it needs to be less than 2mb, when it already is.

I am pretty sure the tool is broken in various ways. We can't fix it - I think you'll need to report any such issues to Facebook.

**Comment by 1mrpaul1** [comment]
They will say that this is the problem of construct, vicious circle
As I understood there is a problem with the assets folder. this is why a single file without an asset folder doesn't have errors, there is no asset folder

**Comment by AshleyScirra** [comment]
Construct's HTML5 exports work in a browser. If Facebook's tool is meant to be compatible with what loads in a browser, then their tool is broken. If their tool is not meant to be compatible with what loads in a browser, then they need to document what the differences are, so we can make sure our engine complies with the restrictions. However I am not aware that they have documented any such restrictions. Facebook need to either fix their tool or tell us what we need to change. If they do neither, it is impossible for us to know what to do.

**Comment by 1mrpaul1** [comment]
in all error messages, there is one message, that some resource is blocked and wrote why blocked 
it is hard for me to say what is wrong because you have much much more advanced programming knowledge and construct is your child, you know every byte in it, but, construct is a closed engine and only you can fix this issue
At least using reversed engineering 
I think it is more the question of priorities 
As I said before, companies do not want to hire construct coders, as long as the app isn't a standard in the gamedev
Only one exclusion is playable ads, where construct could be a super tool and construct users doing playable will be valuable in every game company 
Playable just are still open niche where unity and unreal can't work, and it is a good time to fill this niche

**Comment by AshleyScirra** [comment]
I do know every part of Construct, which is why I know this is not Construct's fault: Facebook need to fix it, or at least tell us what restrictions they are enforcing, because if there are unknown restrictions, it's not feasible to work around them. (Reverse engineering is not a feasible approach, I've tried that before and failed, Facebook need to tell us what we need to do.)

**Comment by 1mrpaul1** [comment]
may be they didn't react because something is really wrong with builds?
I found few topics using errors messages from Facebook preview tool (console)
Honestly, for me, it is not very clear, but as I understood, construct games using unsafe method to load scripts 
look on it please, may be it is not the main error, but I have many errors of this type
https://stackoverflow.com/questions/31211359/refused-to-load-the-script-because-it-violates-the-following-content-security-po/31219814#31219814
https://csper.io/blog/no-more-unsafe-inline
Also, as long as, single file didn't have this error, please try to separate code with graphics and sounds when exporting for facebook playable. If  HTML file will not load any scripts but just images, games will pass this error, and will allow keeping expensive resources in the compressed formats (not base64) and will allow uploading the game as zip with 5mb limit

Please try, if it will be successful I will advertise the construct every day, in the telegram in the channels with all pro game devs
this theme is popular there

**Comment by AshleyScirra** [comment]
Construct doesn't use the 'unsafe-eval' method of loading scripts, so I don't know why that would have come up.

I'm afraid it's Facebook who need to act on this. There's little more I can add.
