### ISSUE TITLE
Strange Rare Crash(es); may be difficult to recreate though.

### ISSUE THREAD

**Issue by RetroeyDoofery** [Scirra/Construct-3-bugs#5281]
## Problem description

This one is an interesting weird case. Whenever I did some of the more basic things within Construct 3's beta build, I ended up being greeted with 'unhandled rejection' type crashes that seem to either no longer happen again (whenever attempts to reproduce the crashes are made) or they may possibly occur after some uptime.
I genuinely wish I knew what's more to add to this, but I don't. It's a weird thing I thought I'd give a heads up about.

## Attach a .c3p

[Rare Crash Reproduction Attempt.zip](https://github.com/Scirra/Construct-3-bugs/files/7645180/Rare.Crash.Reproduction.Attempt.zip)

## Steps to reproduce

1. Screwing around in the engine was just about enough for me...
2. The crashes.
2.1. Crash no.1 - Font related
2.1.1. After some time of me fiddling around, I add a Text object and drag it into the layout.
2.1.2. I attempt to change it's font from the default pre-loaded ones into one of the project font files.
2.1.3. I am greeted with Crash Log no.1 (you can check it in the "System Details" tab), and that doesn't happen again after I reload the engine and try to recreate the crash in a separate minimal project I would have attached to this issue. However...
2.2. Crash no.2 - Folder related
2.2.1. After some time trying to recreate the previous crash, I ended up crashing the engine again after creating an Object Type folder (with some symbols); [see Crash Log no.2]. However, this one crash could not be recreated after the page reload either.

## Observed result

Crashes. After restarting the engine web-page after these few crashes, Construct 3 didn't crash again whenever I tried reproducing both crash myself. Either they can occur after some uptime or some things are just that kind of strange.

## Expected result

...**_TO BE HONEST? DEFINITELY NONE OF THAT!_**

## More details

**Affected browsers/platforms:** Chrome/Brave, Windows
**First affected release:** r274 (Beta)

## System details

<details><summary>View details (Crash no.1)</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot set properties of null (setting 'value') @ TypeError: Cannot set properties of null (setting 'value') at rq.g.I.YDb.G2 (https://editor.construct.net/r274/main.js:1336:130) at https://editor.construct.net/r274/main.js:1337:169
Stack: TypeError: Cannot set properties of null (setting 'value') at rq.g.I.YDb.G2 (https://editor.construct.net/r274/main.js:1336:130) at https://editor.construct.net/r274/main.js:1337:169
Construct 3 version: r274
URL: https://editor.construct.net/r274/
Date: Thu Dec 02 2021 22:47:58 GMT+0300 (Moscow Standard Time)
Uptime: 480.9 s

Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r274 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-10.18.10.4358)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>
<details><summary>View details (Crash no.2)</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'No') @ TypeError: Cannot read properties of null (reading 'No') at eI.lc (https://editor.construct.net/r274/projectResources.js:1032:152) at Array.Lnb (https://editor.construct.net/r274/projectResources.js:1046:222) at window.s5a.dispatchEvent (https://editor.construct.net/r274/main.js:1048:32) at Object.CCG.Nn (https://editor.construct.net/r274/main.js:754:230) at d.La (https://editor.construct.net/r274/projectResources.js:499:453) at SU (https://editor.construct.net/r274/components/bars/projectBar/projectBar.js:7:106)
Stack: TypeError: Cannot read properties of null (reading 'No') at eI.lc (https://editor.construct.net/r274/projectResources.js:1032:152) at Array.Lnb (https://editor.construct.net/r274/projectResources.js:1046:222) at window.s5a.dispatchEvent (https://editor.construct.net/r274/main.js:1048:32) at Object.CCG.Nn (https://editor.construct.net/r274/main.js:754:230) at d.La (https://editor.construct.net/r274/projectResources.js:499:453) at SU (https://editor.construct.net/r274/components/bars/projectBar/projectBar.js:7:106)
Construct 3 version: r274
URL: https://editor.construct.net/r274/
Date: Thu Dec 02 2021 23:08:08 GMT+0300 (Moscow Standard Time)
Uptime: 1141.4 s

Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r274 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-10.18.10.4358)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
I'm afraid as per the bug report guidelines it's impossible to help without reliable steps to reproduce the problem. We may need to follow the steps several times and observe the issue happening repeatedly in order to investigate that, and if we can't do that, we can't investigate the problem. Please do file a new issue if you can identify how to reliably reproduce either issue.
