### ISSUE TITLE
Strings affect trigonometry expressions

### ISSUE THREAD

**Issue by Zackarotto** [Scirra/Construct-3-bugs#5282]
## Problem description

Setting text to cos(270) or sin(180) will return -1.8369701987210297e-16 instead of 0, if a string is included. Such as:
"Cosine of 270 degrees: " & cos(270)

## Attach a .c3p

[cos.zip](https://github.com/Scirra/Construct-3-bugs/files/7648244/cos.zip)
## Steps to reproduce

1. Open project

## Observed result

-1.8369701987210297e-16

## Expected result

0

## More details

**Affected browsers/platforms:** 
Chrome, Firefox

**First affected release:** 
r274 (only tried this version)
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r274 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 1.4 gb (1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
-1.8369701987210297e-16 is the correct answer (and note the `e-16` part indicates it is an extremely small number). Fractional calculations on computers are not perfectly exact and are usually subject to small rounding errors, so this is a normal result.

'Set text' applies a small amount of rounding if passed a number, in order to try to display a better result, which is why that method returns 0 - it rounded -1.8369701987210297e-16 to several decimal places. Appending to a string does not do that though.
