### ISSUE TITLE
OSX only NW.js export bug (follow up #5279)

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#5285]
## Problem description

This is a follow up to #5279, with a new way to reproduce an inconsistency when exported

I realized that my project works fine when exported with nw.js on windows, but it stopped working correctly on OSX as nw.js export. In the browser preview in construct 3 it works fine.

## Attach a .c3p

[a_Bug_OSX_JS_09.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/7653557/a_Bug_OSX_JS_09.c3p.zip)

## Steps to reproduce

1.open project on a mac, preview project (you need audio)
2.listen to the audio
3. now export it to nw.js, all three options enabled (minify advanced, or no minification- same result).
4. latest Chromium 95, Mac 64, package assets, Window Frame, Rezisable, Ignore Blacklist enabled
5. start exported project, repeat step 2

## Observed result

-previewed Project plays sound always in rhythm
-osX nw.js exported project is skipping a beat right at the beginning, then like every 17 - 30 beats it makes a beat inbetween the rhythm

should always play sound in rhythm
## More details

Please read the comments in the project, the cause of the first skipped beat is indicated as well as the reason for the middle beat that appears from time to time. All connected to wait actions

if I replace the audio scheduling  with a wait action that changes the beat every interval seconds, the problem is not there.

**Affected browsers/platforms:** 

**First affected release:** 
Problem exist with the latest Beta r274 and also with the latest stable r268
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 96.0.4664.55
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36
C3 release: r268 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 3.4 gb (1.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel(R) HD Graphics 630
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
For a minimal repro we generally need a project with <5 events. Otherwise it is very difficult to prove it's not just somehow a mistake in the events, or to debug what is actually going wrong. Can you reduce the project even further?

**Comment by bubbblebub** [comment]
Yes I was able to reduce it much more. The Audioscheduling is necessary to reproduce it, so this alone is more than 5events, but for the rest its reduced to the max. Reproduce it the same way as before, but I deactivated the second inconsistency for even more simplicity. 

So now  it just skips a beat right at beginning when you start the exported nw.js (please read the comments in the EventSheet)

[a_Bug_OSX_JS_10.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/7662419/a_Bug_OSX_JS_10.c3p.zip)

**Comment by bubbblebub** [comment]
I just experimented around and found some additional informations that indicates that it is not a platform specific problem:

-I exported the latest bug report (a_Bug_OSX_JS_10.c3p), BOTH 2 Bug Examples in the project Eventsheet activated, to Android - debug APK, using the latest Beta r274 - The first time I opened it, it worked like intended. Then I closed it, reopened it, and then it first skipped a beat, then had a constant double beat with a regular break every x beats. So the acoustic result is wrong, but different than with nw.js export on mac.

-then I exported it again same as above to iOS, X-code, tested it on an iPhone 8 with iOS 15.1. The beat is wrong, same as on android (but without working correctly the first time I opened it)

-Then I exported my personal project to iOS. It s broken, the acoustic result is wrong. The latest working export for iOS I have dates the 03.11.2021. So it is somewhat newly broken - bevor I tested it a lot on iOS over a very long period of time.

-on Android my personal project is also broken, but like the bug Report file it worked fine the first time I opened it.

-for all the exports I activated deduplicate images, recompress images, Minify -none

I hope that helps to solve the problem!

**Comment by bubbblebub** [comment]
Thanks for your answer!
I understand the Bugreport file doesn’t make a lot of sense, that’s  just because its only reasen is to identify the Bug. This worked for me for certainly the last 2 years, then it stopped. It still works perfect in the browser on every system, only with certain exports it stoped working and prevents me to publish my project. Basecally I just hope that it will work again the same way when exportet than it works as a construct 3 preview.

I am aware that calling the sound later (with the variable "beat“) can cause inconsistencies, but that was never a big problem as it concerned alway just a short moment, then came back to normal.  It just started to behave completly different from the moment when the bug appeared. If you could give it another try to fix it this would be really great.

**Comment by bubbblebub** [comment]
I was able to create a new bugreport project without the unlogic events, basecally by just adding one line of code to your Audio Scheduling example. Please check the new file I add here. I indicated the event additions to the original audioscheduling example in the file.

How to recreate:
-preview project in construct 3. Press the button. listen to the pause between the first and the second sound (its a short pause)
-now export the file as NW.js for for Mac64 (I used the latest chromium 98 NW.js) . Open the file and listen again, this time there is a long pause between the first an the second sound.

what I expect: both time same pause duration
[AudioSchedulingBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8036504/AudioSchedulingBug.c3p.zip)

**Comment by bubbblebub** [comment]
Hi Ashley, I found a hint that may help to solve the problem! If I play a sound (with no volume) before the real soundfile, the problem is gone. I think its now bulletproof that it is actually a bug. I can add an event to your Audioscheduling example to make the bug appear, then I can add another very weird event and its gone. 
This new file is the same as above, but with the deactivated play sound event in it. If you activate this event, the bug is gone (when exportet the pause has the correct length).  For the rest just recreate it like in the message above.

[AudioSchedulingBug2.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8056415/AudioSchedulingBug2.c3p.zip)

Please tell me if you prefer that I make a new bugreport. Because the case is closed, a short reaction would be kind so I know that you read this closed bugreport messages.
