### ISSUE TITLE
Global layers with sub-layers behave weird and do not show in Preview

### ISSUE THREAD

**Issue by rilem** [Scirra/Construct-3-bugs#5287]
## Problem description

Global layers with sub-layers do not show sub-layers on other layouts.

## Attach a .c3p

[global layer with sublayers.zip](https://github.com/Scirra/Construct-3-bugs/files/7654542/global.layer.with.sublayers.zip)

## Steps to reproduce

1. view the layer on Layout 1
2. view the layer on Layout 2

## Observed result

Notice the layer renders oddly in the editor (parallax) and doesn't show up in preview.

## Expected result

The global layer appears normally.

## More details
R274

**Comment by AshleyScirra** [comment]
Fixed for next beta.
