### ISSUE TITLE
Canvas Rendering Error

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#5288]
## Problem description

The canvas has some problems accurately pasting objects. I included an example image (Example.png) of what is happening that will explain better than I can in words. The sprite on the left is the canvas paste, but you can tell by the example project.

## Attach a .c3p

[Canvasbug.zip](https://github.com/Scirra/Construct-3-bugs/files/7654825/Canvasbug.zip)

## Steps to reproduce

1. It just needs a preview started.

## Observed result

![Example](https://user-images.githubusercontent.com/27903903/144948136-966114b1-c84e-441f-a1e5-794a7b655785.png)
This is when the display is x2 in size and i just increased the size of it to try to make the issue easier to see.
Look at the left side and how it has about half a pixel of the far left pixels copied next to it that shouldn't be there. The pasted sprite is also about half a pixel down from where it should be. Then the right side of the pasted sprite is cut off by half a pixel. This makes it impossible to accurately read RGB values from the pasted sprite because when it's x1 in size, some pixels get distorted throwing off the canvas image.

If I change the canvas object's position by adding 0.1, then it renders correctly, but I assume this isn't intentional because it used to not do this.

![Example2](https://user-images.githubusercontent.com/27903903/144949512-5c0e1aa8-50a1-4ee9-bba7-e278585ace4e.png)
Here is when the canvas object is left in the same place as the sprite. Zoom in on the top left and you should be able to see the distortion.

![add](https://user-images.githubusercontent.com/27903903/144950222-28cf9408-ac47-49b3-822e-e7f2649c3d13.png)
Giving the canvas additive blending apparently make it a lot easier to see how they don't match up.

It seems that adding 0.1 to canvas' size before pasting also corrects it.

## Expected result

Canvas used to paste objects verbatim. This apparently has been an issue since I first reported canvas scaling incorrectly for the display size.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r274

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r274 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 139 gb
Storage usage (approx): 6.9 gb (4.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 1030 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9709)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm looking at the project and I can't see anything that's wrong. Can you fill out the observed result vs. expected result fields, with screenshots if it helps, to make it clear what you think the problem is?

**Comment by corlenbelspar** [comment]
I updated the observed results part of the report.

**Comment by AshleyScirra** [comment]
It looks pixel-perfect correct for me - this is a screenshot of the resulting Drawing Canvas that I see:
![issue5288](https://user-images.githubusercontent.com/768723/151561309-c8f3cb59-7cf9-4c75-82d8-38f340988d3a.png)
It looks perfectly aligned - I can't see any of the misalignment you showed.

The events look odd as well - there doesn't seem to be any reason to be using snapshots. As of the latest beta it's also advisable to use 'Wait for previous actions to complete' after pasting an object to ensure the paste has finished before doing anything else. None of this seems to affect the issue for me though. I'm afraid without a reliable way to reproduce the issue there's little we can do.

**Comment by corlenbelspar** [comment]
![image](https://user-images.githubusercontent.com/27903903/151916236-0b3002ce-5bdf-4727-aeea-280f67368910.png)
Use something like MS Paint and measure the size of the pixels here vs the other columns. They're wider than the rest. It's not something you can easily see just looking at it.

**Comment by corlenbelspar** [comment]
![image](https://user-images.githubusercontent.com/27903903/151916535-d8566c8d-2443-4f19-b0d3-6574f6401966.png)
Here is the far left of the image in width vs anywhere else across the image.

**Comment by corlenbelspar** [comment]
![16px](https://user-images.githubusercontent.com/27903903/151917433-a6a680b6-ef2b-459b-bcb5-0304fe037a25.png)
![20px](https://user-images.githubusercontent.com/27903903/151917435-1e0af407-e9dc-410f-8967-00999120dc36.png)

**Comment by AshleyScirra** [comment]
OK, I see now. It is difficult to spot.

**Comment by corlenbelspar** [comment]
It's all good. It's definitely something I couldn't figure out until I started doing a bunch of testing and screenshots. Thanks.

**Comment by AshleyScirra** [comment]
The paste object code is extremely complicated but I think I've got this working for the next beta now.
