### ISSUE TITLE
Restarting layout in runtime, while timeline is playing freezes the game

### ISSUE THREAD

**Issue by TeamDisgrace** [Scirra/Construct-3-bugs#5289]
## Problem description

If you perform action "restart layout" during runtime, while timeline is playing, the game freezes completely. After the freeze you can't restart again or do anything else. It's just stuck.

Edit: r274 by the way
## Attach a .c3p

[BuggyTImeline.zip](https://github.com/Scirra/Construct-3-bugs/files/7655670/BuggyTImeline.zip)

## Steps to reproduce

1. Create a project
2. Create a timeline animation
3. Create a condition to restart the game. E.g: On key pressed "R" --> Restart Layout
4. Start the game
5. Press R

## Observed result

Freeze

## Expected result

Restarted layout

## More details

![bug](https://user-images.githubusercontent.com/94541962/144742962-4678033b-01d9-4a29-b20a-99ace46c129f.png)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by TeamDisgrace** [comment]
Also it doesn't help if i put "stop all timelines" before "restart layout"

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta. Was a regression introduced in r273 relating to the changes to improve performance of timelines.
