### ISSUE TITLE
Getting This message "Aw, Snap Google Chrome run Out of Memory while trying to display this Webpage" each time while preview

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#529]
## Problem description
*I am getting this each time when i do preview of just 3 mb file*

## Attach a .c3p

*[File](https://www.dropbox.com/s/30c01zp20qkl7qv/Bounce.c3p?dl=0)*

## Steps to reproduce

1. preview linked file
2.
3.

## Observed result

*![aw snap](https://user-images.githubusercontent.com/17684135/27252227-73cdd112-5376-11e7-83f2-a401b2220dab.jpg)*

## Expected result

*Preview*

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Does it reproduce in Chrome Canary? We've had other reports of memory-related issues which are already fixed.

**Comment by AshleyScirra** [comment]
Closing as had 'need info' tag for over 2 weeks with no response.
