### ISSUE TITLE
Assertion Failure - Fatal Error

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#5290]
## Problem description

Over 3 years of use this is a random yet lasting bug where right clicking an element will sometimes yield this error, usually only if I've been working in a project for a while (hours). Thus I consider this not easily reproducible.

## Steps to reproduce

1. Work on a project for a lengthy amount of time (Check uptime in error report)
2. Right clicking an element will on rare occasions elicit this error

## Observed result

![image](https://user-images.githubusercontent.com/37854520/144935798-28323c3d-2eb1-4d45-bfc5-020748d79380.png)

## Expected result

Show the drop down options of the element that was right clicked.

## More details

**Affected browsers/platforms:** Chrome

## Message: language context stack reached 100 items - is this right? Suspicious context is ".event-block.context-menu"
Stack: Error at Function.xa.DNa (https://editor.construct.net/r274/main.js:931:289) at window.assert (https://editor.construct.net/r274/main.js:849:38) at Function.K (https://editor.construct.net/r274/main.js:1026:89) at i9a (https://editor.construct.net/r274/components/editors/eventSheetView/eventSheetView.js:2:228) at window.V5a.$w (https://editor.construct.net/r274/components/editors/eventSheetView/eventSheetView.js:83:290) at window.V5a.Ee (https://editor.construct.net/r274/components/editors/eventSheetView/eventSheetView.js:19:384) at HTMLDivElement.Vh (https://editor.construct.net/r274/components/editors/eventSheetView/eventSheetView.js:10:271)
Construct 3 version: r274
URL: https://editor.construct.net/r274/
Date: Mon Dec 06 2021 15:48:12 GMT-0700 (Mountain Standard Time)
## Uptime: 162632.3 s

Platform information
Browser: Chrome
Browser version: 96.0.4664.45
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
C3 release: r274 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment]
I'm afraid without reliable steps to reproduce there is nothing we can do.

I've tried to improve the error message for the next beta so that if this happens again, it should shed a little more light on it and maybe we can look further in to it then - do file another issue if you see it happen again in r275+. However until then there's no way to know what else we can do, so closing this issue.
