### ISSUE TITLE
Child objects don't follow parent when you preview in editor

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#5294]
## Problem description

Child objects don't follow parent when you preview in editor

## Attach a .c3p
[PreviewEditor.zip](https://github.com/Scirra/Construct-3-bugs/files/7674630/PreviewEditor.zip)

## Steps to reproduce

1. Click on Head and preview sine
or
1. Right click on layout -> View -> Start all live previews

## Observed result

Child objects don't follow parent 

## Expected result

Child objects follow parent 

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I think this is pretty complicated: currently live previewing works much like dragging/editing the object manually, which you'll note in the editor does not affect the entire hierarchy.

I believe @DiegoScirra has done some work to get hierarchies to preview correctly with timelines - assigning to him on the assumption the problem will need to be solved a similar way.

**Comment by DiegoScirra** [comment]
Added starting on the next beta cycle.
