### ISSUE TITLE
Black Space at bottom of screen when closing iPad Keyboard

### ISSUE THREAD

**Issue by JadenDavisAkupara** [Scirra/Construct-3-bugs#5295]
---

## Problem description

When using the text input object in Construct 3, the screen will scroll up on iPad. If you close the keyboard with the button (instead of tapping somewhere on the screen) it will leave a large black space under the layout until the screen is tapped again. This occurs in both r251.2 (the version our project is in) as well as r268.

## Attach a .c3p

[KeyboardIssueDemo.zip](https://github.com/Scirra/Construct-3-bugs/files/7679257/KeyboardIssueDemo.zip)

## Steps to reproduce

1. Export and open the project on an iPad (This doesn't occur on the iPad Air)
2. Tap on the text input, causing the screen to scroll up
2b. When emulating an iPad through Xcode, I had to open the keyboard manually, click off the text box, then click the text box again for the screen to scroll upwards
3. Close the keyboard using the button in the bottom right corner

## Observed result

There is a black space under the layout from when it scrolled up.

![Screenshot_6](https://user-images.githubusercontent.com/87153179/145293057-77b6ce5a-a846-4413-858c-bafd1f5a7a87.png)
![Screenshot_8](https://user-images.githubusercontent.com/87153179/145293059-30950c44-7645-498d-9e15-cd6fecf31fef.png)
![Screenshot_9](https://user-images.githubusercontent.com/87153179/145293053-1be5681c-d691-40ba-9ecc-476ae35ee70d.png)

## Expected result

The layout would scroll back down upon closing the keyboard, eliminating said black space.

## More details
 We've tested this across a few iOS platforms but it only seems to affect iPad.

**Affected browsers/platforms:** iPad

**First affected release:**  Occurs in r251.2 though I haven't checked earlier versions

## System details

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
Is the iPad running iOS 15? Did it work on iOS 14?

**Comment by JadenDavisAkupara** [comment]
The actual iPads we used were running iOS 15.1 and the XCode emulator was running iOS 15. The only other version I can test in XCode is 13.7 but the demo doesn't open there.

**Comment by AshleyScirra** [comment]
This is a bug in iOS that leaves the view scrolled when the keyboard is hidden. We have a workaround that resets the scroll position when the focus changes, but the "hide" button on the keyboard does not change focus, so it does not reset the scroll position. (It will reset when you touch outside the control, as that resets focus.) This should be fixed in the next beta as the workaround has been adjusted to watch for changes in the viewport height rather than focus, so it should always detect the keyboard being hidden.
