### ISSUE TITLE
JSON object ignores "Stop loop" action

### ISSUE THREAD

**Issue by yehorlevchenko** [Scirra/Construct-3-bugs#5296]
## Problem description
Existing "stop loop" action stops any loop ran by System (e.g. for, for each). 
However, there is no way to stop a "for" loop over JSON object. 
Example:
```
+ JSON: For each entry in ""
-> System: Set query_checksum to 0
-> Browser: Log in console: JSON.CurrentKey
-> System: Stop loop
----+ System: For "query_loopindex" from 0 to query_len - 1
----+ subquery_json: Pick instance with UID int(query_json.Get("query." & str(loopindex)))
--------+ subquery_json: For each entry in "."
---------> System: Add JSON.Get("." & subquery_json.CurrentKey) = subquery_json.CurrentValue ? 1 : 0 to query_checksum

--------+ System: query_checksum = query_len
---------> System: Stop loop # This action won't stop "query_loopindex" loop
---------> Functions: Set return value 1
```
Note: having "stop loop" right in the event with loop condition doesn't stop it after first iteration.

## Steps to reproduce
1. Create a loop over JSON object
2. Try to stop it anyhow using "stop loop"
3. Fail

## Observed result
Loop goes on until the end of collection

## Expected result
Loop stops

**Affected browsers/platforms:** any

**Comment by AshleyScirra** [comment]
Similar to #1451, this is currently by design: the system 'Stop loop' action only stops system loops.
