### ISSUE TITLE
Error report information

### ISSUE THREAD

**Issue by sarawut985** [Scirra/Construct-3-bugs#5298]
Error report information
Type: unhandled exception
File: blob:https://editor.construct.net/dfcb307b-a493-463b-bb00-849553ea341b, line 1918, col 3
Message: Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://downloads.scirra.com/cheerpj-runtime/20201027b/runtime/rt.jar.js' failed to load.
Stack: null
Construct 3 version: r268
URL: https://editor.construct.net/
Date: Fri Dec 10 2021 11:23:06 GMT+0700 (Indochina Time)
Uptime: 72 s

Platform information
Browser: Edge
Browser version: 96.0.1054.43
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43
C3 release: r268 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.101.1069)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to do anything about reports like this. Please see the bug report guidelines.
