### ISSUE TITLE
Event_Chain_And_Or_Debug

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#5299]
## Problem (Might be by design, but inconvenient in practice) :

It is not possible to individually set sub events to AND/OR states in an event chain

The setup and issue are explained in the attached project's event sheet.

[Event_Chain_And_Or_Debug.zip](https://github.com/Scirra/Construct-3-bugs/files/7695288/Event_Chain_And_Or_Debug.zip)

Browser: Chrome
Version: r275

**Comment by AshleyScirra** [comment]
Looks like a regression in r273. Fixed for next release.
