### ISSUE TITLE
Crash when using Animations Editor: Sprite

### ISSUE THREAD

**Issue by IsmailAdvice** [Scirra/Construct-3-bugs#53]
## Problem description

https://youtu.be/FpPtxADOH0o

## Attach a .c3p

No need to save any file.

## Steps to reproduce

1. Insert new object: Sprite.
2. Select the location to add the sprite, and open the Editor.
3. Draw a line.
4. inset new object: sprite in new location
5. without using mouse clicking, move the mouse and you will see the line drawing.
6. don't do think just close the editor.
7. the crash will show.

## Observed result

the window turn to red
dialog box  show with Error report information.

*What did you expect to happen instead?*
the line not show.
and there is no crash.

## Affected browsers

* Chrome: yes

## System details

Error report information
Type: unhandled rejection
Reason: TypeError: this.ǃWBg is not a function
Stack: TypeError: this.ǃWBg is not a function at ǃp.ǃd.ǃWW.ǃWB_ (https://editor.construct.net/r16/main.js:2:420885) at ǃp.ǃd.ǃWBc.ǃWfR (https://editor.construct.net/r16/main.js:2:423823) at ǃp.ǃWhh.then.then (https://editor.construct.net/r16/main.js:2:423726)
Construct 3 version: r16
URL: https://editor.construct.net/
Date: Sun Apr 09 2017 16:52:17 GMT+0300 (EEST)
Uptime: 1815.5 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GTX 675MX OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2047
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

<details><summary>View details</summary>

see this youtube about this bug
https://youtu.be/FpPtxADOH0o

</details>

**Comment by jaydonteh** [comment]
Duplicate: https://github.com/Scirra/Construct-3-bugs/issues/17

**Comment by IsmailAdvice** [comment]
that's right.
