### ISSUE TITLE
Dark theme: Collapse button for event blocks has an odd line on top

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#530]
## Problem description

When not expanded the button has this odd line on the top. When expanded the line disappears (or goes under the code block graphics so it can't be seen.

## Attach a .c3p

Any empty project works.
![image](https://user-images.githubusercontent.com/7268697/27256060-dd999d78-53b3-11e7-8756-38b3d458aa15.png)

![image](https://user-images.githubusercontent.com/7268697/27256071-1471c28a-53b4-11e7-9fb0-0d4fe5a1a8ab.png)

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r38.2

Local storage
Storage quota (approx): 9.1 gb
Storage usage (approx): 258 mb (2.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This may be related to the device pixel ratio. Please, always include the system details we ask for, it includes the device pixel ratio and would save us from having to ask.

**Comment by JeFawk** [comment]
My bad, I've added the platform info. The bug seems to appear only on my laptop btw.

**Comment by AshleyScirra** [comment]
Yep, non-integral DPR. Probably more to do with the icon system than the theme.

**Comment by AshleyScirra** [comment]
I just increased the padding for icons and it fixed it. Should be fixed in r41.
