### ISSUE TITLE
Firefox not showing sprite alpha correctly in the editor

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5304]
## Problem description

I added a "glow" sprite (attached). Alpha shows correctly in Chrome, but in Firefox it shows white. 
This affects the editor only, and not the preview.

## Attach a .c3p

[alpha.zip](https://github.com/Scirra/Construct-3-bugs/files/7710236/alpha.zip)

## Steps to reproduce

1. Open the project
2. The "glow" object appears white in the Editor
3. In the Animations Editor, the object appears correctly

## Observed result
The "glow" object appears white in the Editor

## Expected result

The alpha in the Editor should match the sprite alpha in the original png

## More details

**Affected browsers/platforms:** Firefox 95.0

**First affected release:** 

## System details
Win 7 64-bit

**Comment by AshleyScirra** [comment]
Should be fixed in next beta.
