### ISSUE TITLE
Stable R276 introduces unnecessary Android permission with built-in Share plugin

### ISSUE THREAD

**Issue by DanPkg** [Scirra/Construct-3-bugs#5305]
## Problem description

Stable R276 introduces unnecessary Android permission with built-in Share plugin

## Attach a .c3p

Blank project with Share object type

## Steps to reproduce

1. Create Blank Project using R276
2. Insert "Share" object type
3. Export un/signed Android app bundle or APK
4. Open APK/aab in Android Studio. Investigate AndroidManifest.XML
5. Permission added android.permission.WRITE_EXTERNAL_STORAGE

## Observed result

Permission added android.permission.WRITE_EXTERNAL_STORAGE in AndroidManifest.xml

## Expected result

No android.permission.WRITE_EXTERNAL_STORAGE permission required

## More details

Previous Stable Version R268 did not include write to external storage permission after inserting the Share object in a blank project.

My other game projects without the Share object also produce this permission now too, but I thought we could start investigation with this Share default plugin first (I do not use 3rd party plugins)

## System details

Chrome 96.0.4664.110 (Official Build) (64-bit)

Exported using Dedup and Recompress Images ticked. With Minify Simple.
Min Version default 5.1+. Properties section all default

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
We switched from a customised version of `cordova-plugin-file` back to the stock version, as our customised version was causing its own compatibility problems. The stock version adds these permissions. It's difficult to fix as it's a core part of Cordova that is adding the permissions.

Does it matter though? The permissions won't be used and won't prompt the user for them. So perhaps you can just ignore this?

**Comment by DanPkg** [comment]
I guess not if it doesn't prompt users for them. More of a deterrent/privacy concern for users as they will see access to external storage perm listed on Google Play store listing.

This can be closed then, thanks for your reply.
