### ISSUE TITLE
banner ads don't work in few situation

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#5309]
## Problem description

As stated,banner ads don't work in some situation.

## Attach a .c3p

https://drive.google.com/file/d/1B1E4xSY59ULmtgFPy3oWEkHzg4G47gvK/view?usp=sharing

## Steps to reproduce
1.) I need to show banner ads at the top of screen,hence I selected "banner ads at the top"
2.) In display section, I set viewport fit to "cover"

In my example, you have to just add your admob details.That's it. It is super minimal (1 line code). Please use my code to test it
## Observed result

Banner ads don't work

## Expected result

Banner ads work

## More details
Last stable version (not using current stable version because tween is not working)

**Comment by layilpaht** [comment]
Any updates on this?

**Comment by DiegoScirra** [comment]
I tested this with the simulator in Android Studio and it works, with test ads.

I'll try it with a release APK in a published application with real ads, at that point and if that also works I will have to close this issue.

**Comment by layilpaht** [comment]
> I tested this with the simulator in Android Studio and it works, with test ads.
> 
> I'll try it with a release APK in a published application with real ads, at that point and if that also works I will have to close this issue.

Thanks for the reply
Did you used my given c3p file? Because that is extremely important

**Comment by DiegoScirra** [comment]
Yeah, but there doesn't seem to be anything special about it.

**Comment by layilpaht** [comment]
1.) Banner ads is at the top
2.) "Viewport Fit" in project settings is set to Cover

**Comment by DiegoScirra** [comment]
As it turns out there was a problem with the adverts as a whole. This should be fixed in the next beta.

**Comment by fredriksthlm** [comment]
@DiegoScirra  "_As it turns out there was a problem with the adverts as a whole_".......

Can you elaborate on this fix please, either here or on the forum (if it is something serious or important).
