### ISSUE TITLE
C3 Engine crash when adding instance variable with same name as object

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#531]
## Problem description

I had an object (Sprite) called Weapon and and i tried to add an instance variable to a different sprite object (Player) the name of the Instance variable was also weapon and the engine crashed 

## Attach a .c3p

https://drive.google.com/open?id=0B-BWGR6TVR6BQnhZREpyLUs3ZFk

## Steps to reproduce

1. Create object with name Weapon
2. Add instance variable to another object with the same name "Weapon"
3.

## Observed result

the engine crashed asked me to save the project and showed a stack trace

## Expected result

if you cannot name instance variable same name as object i would expect to get an error message but not throw and exception that cannot be recovered from

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: name already in object class namespace @ Error: name already in object class namespace at v.ǃCTG (https://editor.construct.net/r38-2/main.js:61:147792) at e.ǃFk.then (https://editor.construct.net/r38-2/main.js:149:24213) at 
Stack: Error: name already in object class namespace at v.ǃCTG (https://editor.construct.net/r38-2/main.js:61:147792) at e.ǃFk.then (https://editor.construct.net/r38-2/main.js:149:24213) at 
Construct 3 version: r38.2
URL: https://editor.construct.net/
Date: Sat Jun 17 2017 23:06:42 GMT-0400 (Eastern Daylight Time)
Uptime: 23618.5 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r38.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I can't reproduce the problem from this report. The Player already has an instance variable called "weapon", so it looks like it worked already, and that means I can't follow your steps since I can't add the same instance variable name again (which correctly shows an error that the name is in use, not crashing). So I tried adding an instance variable named "weapon" to a different object (Collision) and it worked.

We can't fix bugs without a way to reproduce the original problem. Can you provide a way to reliably reproduce the crash?
