### ISSUE TITLE
Anything is not working

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#5310]
Weird issue. Maybe a server issue

1.)Forum is not loading
2.)I am not able to create new projects. As I click "new projects",it waits for a long time.Then it displays "failed to create new project"
3.)I am not able to download & try examples. It says "stalled" & then after few moments it says "failed to download project"
4.)I am currently at last stable version. I am also not able to load the latest stable version

And much,much more. It is even more dangerous than APK export issue

**Comment by AshleyScirra** [comment]
It's working fine for me now. I think the servers just had a brief outage earlier.
