### ISSUE TITLE
animation error and page crash

### ISSUE THREAD

**Issue by programmer861** [Scirra/Construct-3-bugs#5311]
## Problem description

Frame animation does not work correctly in google chrome browser on IOS 15.1. Sometimes it either reboots or does not open at all writes "Can't open this page"
## Attach a .c3p

[1.zip](https://github.com/Scirra/Construct-3-bugs/files/7730623/1.zip)
https://drive.google.com/file/d/1pJFexZXn3ol6GYMSlTs3uXg8IYVLvupl/view?usp=sharing

## Steps to reproduce

1. Launch on iphone 13 (you can use the emulator)
2. error is not always the case. Run it a few more times.
3.

## Observed result
Objects are blinking, sometimes there is a reboot at startup, sometimes it does not start at all
showed an error on the video https://www.youtube.com/watch?v=SBH1XZ_wHw4&ab_channel=%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B9%D0%90%D1%80%D1%85%D0%B8%D0%BF%D0%BE%D0%B2
from this link i have compiled and tested https://storage.yandexcloud.net/spk.map/error%20/6/index.html

## Expected result
Objects should not flicker. Automatic reboot should not occur. The page shouldn't crash.

## More details

**Affected browsers/platforms: iOS, v15.1,Browser Chrome** 

**First affected release:**  r275

## System details

<details><summary>View details</summary>

PASTE HERE
iOS, v15.1,Browser Chrome
</details>

**Comment by programmer861** [comment]
on ios 15.2 completely stopped working in browsers

**Comment by DiegoScirra** [comment]
I am not really sure how Yandex Cloud works or how it manages to show you how an application would work on a real device, but this seems like it's a problem with that platform rather than C3.

I tested the example project in a real iPhone running iOS 14.7.1 and a real iPad running iOS 15.2 and in both cases everything seems to work properly.

Unless there is something else about this issue I am missing, I will be closing it as there is nothing we can do about it.

**Comment by programmer861** [comment]
@DiegoScirra ios 15.1,15.2 doesn't work in all browsers. Attached a new c3p file.

https://storage.yandexcloud.net/spk.map/test/3/index.html

**Comment by programmer861** [comment]
https://drive.google.com/file/d/17Gbv_VEsleLMpX8EVSCCItp9CKAyQ3OP/view?usp=sharing

**Comment by programmer861** [comment]
support@construct.net wrote a letter here with additional information please see more

**Comment by AshleyScirra** [comment]
I received the support email but I don't believe there is any action we can take. If the issue only occurs with an emulator, then the problem will need to be reported to and resolved by the emulator developer.

**Comment by programmer861** [comment]
I have a problem on my real ipone 11, a friend also has a problem on ipone 12, we have versions of ios 15.1, 15.2

**Comment by programmer861** [comment]
The error on the phone is exactly the same as on the emulator. Everything works correctly on tablets and older versions of ios.

**Comment by programmer861** [comment]
after reloading the page, it no longer loads. on the emulator exactly the same errors as encountered. video shot from my real ipone 11.
ipone 11, ios 15.2, google chrome, construct 3
https://www.youtube.com/watch?v=OlKpdoMngw0

**Comment by programmer861** [comment]
@DiegoScirra @AshleyScirra  There is information? in version 278.2 the error is the same.   https://storage.yandexcloud.net/spk.map/Pepsi/4/index.html

**Comment by AshleyScirra** [comment]
Closing as this is an old issue and it appears specific to certain emulators. There does not appear to be anything we can do about it and as far as I'm aware it's working fine for everyone using real devices.
