### ISSUE TITLE
Tween set time now allows unintended actions

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#5313]
## Problem description

Skipping a Tween animation with "Set time → Infinity" no longer works and will make the object reach impossible values like "NaN". I believe the value was clamped based on the animation time in previous releases, but now it seems to be allowing extrapolated values.

## Attach a .c3p

[Tween Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/7737454/Tween.Bug.zip)

## Steps to reproduce

1. Simply run the project and watch the object disappear.

## Observed result

The object will disappear from the layout.

## Expected result

The object to skip to the end of its tween animation, like it did in a few older releases.

## More details

**Affected browsers/platforms:** Chrome/Windows 11

**First affected release:**  r276-2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in r278.

**Comment by AshleyScirra** [comment]
Updating milestone and closing issue.
