### ISSUE TITLE
Crashpad Handler is not executable when exporting to linux

### ISSUE THREAD

**Issue by Zafuzi** [Scirra/Construct-3-bugs#5314]
## Problem description
I followed the guided tour then exported the tour to linux32 and linux64 using nw.js The resulting binary crashed with failed permissions for executing chrome_crashpad_handler. Setting the handler binary to executable SOLVED my issue.

## Attach a .c3p
.c3p would not upload to git so I wrapped it in a zip file. 
[tour1.zip](https://github.com/Scirra/Construct-3-bugs/files/7737651/tour1.zip)

## Steps to reproduce

1. Export the project using NW.js to Linux32 and Linux64 ( compression and minifying does not affect result )
2. ![image](https://user-images.githubusercontent.com/7799288/146604482-0a084d2a-48ef-4a9f-b8e7-aa9d9155a701.png)
3. Unzip the project and attempt to run `tour`
4. ![image](https://user-images.githubusercontent.com/7799288/146604693-a754799d-0b30-4df1-b5f6-96b9ec8ea671.png)

## Observed result
![image](https://user-images.githubusercontent.com/7799288/146604790-5abef211-3d14-4851-8e18-c47657c6ca02.png)

## Expected result
![image](https://user-images.githubusercontent.com/7799288/146604870-42e005f5-07d7-4115-9107-fa840468e1de.png)

## More details
Observed in both 64 and 32 bit versions

**Affected browsers/platforms:**
Exported in Firefox 95 64 bit
Linux 32 and 64 bit

**First affected release:**
This is my first time using the platform version is r276.2 stable

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 95.0
Browser engine: Gecko
Context: browser
Operating system: Linux
Operating system version: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
C3 release: r276.2 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 913 mb (44.6%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 980/PCIe/SSE2
Major performance caveat: no
Maximum texture size: 32768
Point size range: 1 to 2047
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_etc
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks for the heads up, it looks like `crashpad_handler` got renamed to `chrome_crashpad_handler` so doesn't get the right permission any more. Fixed in the next beta.
