### ISSUE TITLE
On Landed is called when hitting your head on platform moving down

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#5315]
## Problem description

With the platformer behavior, hitting your head on a falling platform triggers the "on landed" and "on fall" triggers very quickly in succession

## Attach a .c3p

[platformer landed bug.zip](https://github.com/Scirra/Construct-3-bugs/files/7737851/platformer.landed.bug.zip)

## Steps to reproduce

1. wait for platform to go down
2. jump into it

## Observed result

the player alternates quickly between landed and falling animation and gets stuck on the ceiling

## Expected result

This shouldn't happen

## More details

**Affected browsers/platforms:** 

**First affected release:** I know this has been happening in at least the past two stable releases

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in next beta.
