### ISSUE TITLE
Custom tab colours don't save

### ISSUE THREAD

**Issue by Interinactive** [Scirra/Construct-3-bugs#5316]
Hi there

I like to keep my event sheet tabs white and my layouts black. Upon reopening a project, the event sheets save the custom colour I set, but layouts revert to their default multicolored state.

I assume this is a bug?

Thanks.

**Comment by AshleyScirra** [comment]
I just tried it and it works fine for me. It's impossible to investigate further unless you follow the bug report guidelines.
