### ISSUE TITLE
unlimited tick issue with paste

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#5317]
## Problem description
Case where unlimited tick cause side effect. Might be bug, which don't show up in common mode

## Attach a .c3p

[zippp.zip](https://github.com/Scirra/Construct-3-bugs/files/7739977/zippp.zip)

## Steps to reproduce

1.Open example, preview. Select and drag right side of window, left and right.
2.Enable unlimited tick. Select and drag right side of window, left and right.
3.

## Observed result
Unlimited tick mode, makes pasting sprite bugged

## Expected result
Investigation needed, if this is a quirk of unlimited tick mode or a bug that might even show up in v-sync mode

## More details

![ooooo](https://user-images.githubusercontent.com/28864889/146655761-f6a75c02-dacd-4a8f-81e5-a4db5278c50e.jpg)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 96.0.4664.110
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.1 gb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
> Select and drag right side of window, left and right.

I don't know what this means in terms of reproducing the issue. Nothing happens when I try to drag anything in the preview.

I can see a difference in pasting the object, but that's just because higher framerates move objects with smaller time steps, so this does not look like a bug.

**Comment by SnipG** [comment]
Preview window edge.
![yoo](https://user-images.githubusercontent.com/28864889/147933454-079e1626-22e0-4e7b-b138-2b981a116714.jpg)

**Comment by SnipG** [comment]
> just because higher framerates move objects with smaller time steps, so this does not look like a bug.
 From this I understand that it pasted faster, because of smaller time steps? So it did not reproduce the behavior for you? which is shown images posted before.

If glitzing behavior is confirmed to be "not a bug".  Then i would know, that i can't use Unlimited tick mode in certain cases with drawing canvas!
So i need confirmation.
