### ISSUE TITLE
Effect not consistently working with non-rotated and rotated image in project sprite sheet

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#5319]
## Problem description

Effect not consistently working with non-rotated and rotated image in project sprite sheet (according to Ashley it should automatically be pre-drawn to prevent this behavior.)

## Attach a .c3p

[effectRotatedSpriteSheet.zip](https://github.com/Scirra/Construct-3-bugs/files/7740318/effectRotatedSpriteSheet.zip)

## Steps to reproduce

1. Rename project .c3p
2. Load project

## Observed result

3. Trim effect on the sprites should only work in horizontal direction
4. Notice that the left sprite is correctly trimmed in the horizontal direction.
5. Notice that the right sprite is not correctly trimmed in the horizontal direction, instead it's trimmed in the vertical direction.
6. Look at the project spritesheet, the right image is rotated.
7. Run project, play with slide, trim for second sprite is in vertical direction.

## Expected result

Both sprites should trim effect in the horizontal direction. A possible regression?

## More details

More details here:
https://www.construct.net/en/forum/construct-3/plugin-sdk-10/rotated-images-sprite-sheets-166123#forumPost1059017

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by MikalDev** [comment]
A performance comment: if it is the case that a sprite must be predrawn if it's rotated in the sprite sheet, I would like the project option to not rotate sprites in the spritesheet, which may take more texture memory, but would enable the faster draw straight to framebuffer render path for all sprites/images with just a single effect or just color/opacity, etc.

**Comment by AshleyScirra** [comment]
The WebGL renderer was meant to add a pre-draw step in this case, but a missing check meant it didn't. It's been added for the next beta so it should be fixed there.

FWIW the WebGPU renderer passes shaders a flag indicating if the source texture is rotated, so shaders will be able to take it in to account in the shader itself without needing a pre-draw step (and so eliminating the performance overhead of that).

**Comment by MikalDev** [comment]
Thanks Ashley. Also, thanks for the information about WebGPU shaders, I hope we can get other optional info passed to WebGPU shaders, like varying world position per fragment, M / V / P matrices, multiple texture sources (e.g. other frames of animation or normal / bump / depth maps, etc.)
