### ISSUE TITLE
Not Mirroring Correctly With the Pin Behavior

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#532]
## Problem description

not mirroring properly with the pin behavior, unless my assumption is incorrect, that mirroring a sprite should effect the pin behavior.  

players image point : https://drive.google.com/open?id=0B-BWGR6TVR6BWmlubEdqa2VVTVU

weapons image point : https://drive.google.com/open?id=0B-BWGR6TVR6BUzNqdGQzdFJaazg

events to pin : https://drive.google.com/open?id=0B-BWGR6TVR6BX2dGYnVvZXJXSWc

gif of behavior : https://drive.google.com/open?id=0B-BWGR6TVR6BcU1DQ1RXTm9jTDg

## Attach a .c3p

https://drive.google.com/open?id=0B-BWGR6TVR6BeDBacDdHbEpiR2s

## Steps to reproduce

1. pin weapon to player image point
2. mirror player & mirror weapon
3. the pinned object is not mirroring with the image point

## Observed result

when you pin an object it is not effected by mirroring the sprite

## Expected result

i expected the weapon pinned to player sprite to mirror with the player, there is an easy work around when the player is mirrored reconnect the pinned weapon or just set the position to  the image point every tick. if it is not the expected behavior should there be a parameter on the pinned behavior to mirror with the object it is pinned to. 

the way i think about it is i'm pinning this weapon to an image point on the player, at the start. if the player is mirrored so is the image point that i pinned the weapon to, so i would expect the the it to stay pinned to that image point.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r38.2

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 844 mb (1.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's not a bug - the Pin behavior pins to the object origin, not any image point. (The 'Pin' action doesn't have anywhere to specify which image point, so it can't know which to use, either.) It's working correctly as pinned to the origin.

It's really easy to work around though: don't use the pin behavior, and just move your "set position to..." action from "on start of layout" to "every tick". That works because that action does specify the image point to use.
