### ISSUE TITLE
Search field not focused in the Pick an Object dialog in Firefox

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5320]
## Problem description

When adding an object to a For Each for example, "Pick an object" dialog opens, but the search field is not focused. It is a little inconvenience for keyboard users :)

## Steps to reproduce

(It is preferred to make the steps using keyboard shortcuts)
1. New project
2. Add a For Each in the event sheet (e -> enter -> search for "each" -> Enter)
3. Click Enter (to open "Pick an Object" dialog)

## Observed result

Search field is not focused

## Expected result

Search field should be focused

## More details

**Affected browsers/platforms:** Firefox

**First affected release:**

**Comment by AshleyScirra** [comment]
Fixed for next beta.
