### ISSUE TITLE
Loader style sometimes changed back to C3 Splash

### ISSUE THREAD

**Issue by arcadesindo** [Scirra/Construct-3-bugs#5322]
## Problem description
I dont know what the cause was, but have been experienced multiple times with unknown condition since r268 and also still occuring in 276.2
Seems like it's similar with old issue #4930 and #3744 
This not just happen on my end, my other colleague also has the same issue.

## Attach a .c3p

n/a

## Steps to reproduce

1.
2.
3.

## Observed result
Loader style back to Construct 3 Splash

## Expected result
Still the same style we've choose before.

**Comment by AshleyScirra** [comment]
If you use the free edition, the project setting will revert, as the other options require a valid subscription. Without steps to reproduce I can only assume this is what is happening, as the other issues were already resolved, so closing.
