### ISSUE TITLE
Ajax requesting local file with uppercase URL fails when exported to html5 (tested on itch.io)

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5325]
If requesting project file by URL using the AJAX plugin it failes if the URL uses uppercase characters. (when exported to html5 running on itch.io in chrome, error doesn't happen in preview)
example: 
AJAX request URL globalStringThatUsesUppercase&".json"
works in preview but not exported to html5 (on itch.io) 
![jsonError](https://user-images.githubusercontent.com/89512047/146770439-54e65615-9ce0-4e42-94d4-42bc6f366382.PNG)

When using lowercase(globalStringThatUsesUppercase&".json") it works, but according to this: (https://github.com/Scirra/Construct-3-bugs/issues/1989) if I understand correctly, Ashley said lowercasing is not needed anymore.

Not sure If it's really a bug, but was fairly frustating for me to figure out.

I'd prefer if the AJAX plugin would automatically lowercases the URL to avoid this happening to other users.

**Comment by AshleyScirra** [comment]
On case sensitive servers you must make sure you request the exact case-sensitive name of the project file, or the server will return 404 Not Found. This does not affect preview, as it is case insensitive.

Construct attempts to make this easier by lowercasing all exported filenames, so you can at least be consistent about using lowercase. I'm not sure that was really a good thing to do, but it's been doing it for years now, and changing it would then break all projects that make use of the lowercasing. So I would just make sure you also request only lowercase names.
