### ISSUE TITLE
I tried to import an image from google to the animation editor

### ISSUE THREAD

**Issue by jaxongamer2** [Scirra/Construct-3-bugs#5326]
Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'length') @ TypeError: Cannot read properties of undefined (reading 'length') at YYa.G8b.rM (https://editor.construct.net/r268/projectResources.js:2109:80)
Stack: TypeError: Cannot read properties of undefined (reading 'length') at YYa.G8b.rM (https://editor.construct.net/r268/projectResources.js:2109:80)
Construct 3 version: r268
URL: https://editor.construct.net/
Date: Tue Dec 21 2021 13:53:53 GMT-0500 (Eastern Standard Time)
Uptime: 1902.5 s

Platform information
Browser: Chrome
Browser version: 96.0.4664.111
Browser engine: Chromium
Context: browser
Operating system: Chrome OS
Operating system version: (unknown)
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 14268.67.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.111 Safari/537.36
C3 release: r268 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 400 (BSW)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_texture_float_linear, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

The image:
![image](https://user-images.githubusercontent.com/96495969/146984479-1e608446-ffcb-4eb0-b92f-bde672c7e7b2.png)

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it is impossible for us to help.
