### ISSUE TITLE
Ajax Fetching JSON Twice

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-3-bugs#5327]
Hi, have been 4 month+ trying to solve a bug that Ajax fails to load a JSON file 28MB size as you can see here:
[Forum Link](https://www.construct.net/en/forum/construct-3/general-discussion-7/ajax-failing-load-json-162657)

so I recently opened a bug in "bugs.chromium.org" and they told me that there is a possible bug that is fetching the JSON file twice and that could maybe help to solve the problem of the Ajax failure, the exact word he used is I quote:
"1) Any chance you don't need to be fetching it twice? That's possibly a bug anyway."

Here is the Link for the Bug report:
[BUG Link](https://bugs.chromium.org/p/chromium/issues/detail?id=1280788&start=0)

Note:
Not sure yet who does the fetching (C3 or Cloudflare)

## Attach a .c3p

The (Zip file or Url Link Test) is in the "bugs.chromium.org" 

## Steps to reproduce

It's on "bugs.chromium.org"  or you can check my "Network Capture Log" that I provided in there and loot at the events 17193 and 17234 which are both requests to the failing URL, and close together in time, meaning is getting fetching twice.

## Observed result

JSON is getting fetching twice

## Expected result

JSON to get fetching just once

## More details
Please check the BUG report at  "bugs.chromium.org" all the details are in there

Chrome (PC & Mobile)

r268

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 96.0.4664.110
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
C3 release: r268 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 122 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6663)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
There are not two requests. There is a single request going via a service worker. Chrome's network panel lists two entries for one request in that case. I commented on the Chrome issue pointing that out.

**Comment by Tarek200** [comment]
Interesting

Thanks for commenting on the Chrome bug thread, I really appreciate it.

They still say that it makes to calls and that maybe is the service worker that makes duplicate calls, super weird, I guess I will have to wait until they figure it out.
