### ISSUE TITLE
Keyboard opening in browser when Android is in landscape cause "Error: texture exceeds maximum texture size"

### ISSUE THREAD

**Issue by mitsuhashish** [Scirra/Construct-3-bugs#5329]
## Problem description
When on android, due to how the keyboard influence the size of viewport compared to iOS where the size remain the same, if phone is in landscape and fullscreen mode is set to "scale outer" and fullscreen quality is set to "low" the game seems to crash/stop working due to a WebGL texture size error.

## Attach a .c3p
[CrashExampleMobileKeyboard.zip](https://github.com/Scirra/Construct-3-bugs/files/7770217/CrashExampleMobileKeyboard.zip)

## Steps to reproduce

1. set fullscreen mode to "scale outer"
2. set fullscreen quality to "low"
3. put phone in landscape
4. tap the textbox to trigger the keyboard

## Observed result

Game stops working

## Expected result

Game continues to work

## More details
>Logged error : (need to connect thru USB to see in logs)

Uncaught (in promise) Error: texture exceeds maximum texture size (texture.js:15)
    at WebGLRendererTexture._CreateDynamic (texture.js:15)
    at WebGLRenderer.CreateDynamicTexture (webglRenderer.js:52)
    at WebGLRenderTarget._Create (renderTarget.js:4)
    at WebGLRenderer.CreateRenderTarget (webglRenderer.js:54)
    at CanvasManager.GetAdditionalRenderTarget (canvasManager.js:39)
    at C3Runtime.GetAdditionalRenderTarget (runtime.js:44)
    at Layout.Draw (layout.js:39)
    at C3Runtime._Render (runtime.js:86)
    at C3Runtime.Render (runtime.js:85)
    at C3Runtime.Tick (runtime.js:72)

**Affected browsers/platforms:** 

Chrome on Android 4.4.4
unknown

## System details
Android 4.4.4

**Comment by fredriksthlm** [comment]
Android 4.4.4   ???

**Comment by AshleyScirra** [comment]
Construct does not support Android 4.4. It only supports Android 5.1+ now. Therefore I'm afraid we can only investigate reports on supported devices running Android 5.1+.

**Comment by mitsuhashish** [comment]
Thanks for your support, unfortunately I forgot to mention recently I've come to realize this issue isn't related to OS type/version nor browser type/version, it's an internal issue I assume, as it still happens on other browsers too if the dimensions are "weird" and the fullscreen quality is set to low. (see attached screenshot replicating same sizes of and android with keyboard open but on lastest chrome version on an updated windows 10 installation)
![image](https://user-images.githubusercontent.com/59168393/147932968-06cdb55a-af42-421c-b2fd-f2bbf08ca06d.png)

**Comment by AshleyScirra** [comment]
Please file a new issue following all the guidelines with regards to a supported system if you want this further investigated.
