### ISSUE TITLE
Paste the image and toggle the grid directly, The image will come back.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5330]
## Problem description

After pasting an image, if you do not click again to confirm, you will immediately switch the grid, which will cause paste failure.Restore to what it looked like before paste.

### Step 1: Create a new Sprite
<img src="https://user-images.githubusercontent.com/45864744/147450072-602fbdee-b1b7-44a6-840e-3c3d9dc6d0c9.png" width="480">

### Step 2: Paste The Sprite
copy any image, just `Ctrl + C`  
<img src="https://user-images.githubusercontent.com/45864744/147449967-1a571229-a994-416d-a4f6-c8096815550d.png" >

click the canvas and `Ctrl + V` 
<img src="https://user-images.githubusercontent.com/45864744/147450519-7cd92333-8a18-4245-b1f2-485a022415a6.png" width="480">

Note that the image still shows dotted lines, don‘t click the mouse to confirm.  
<img src="https://user-images.githubusercontent.com/45864744/147450473-e29b94ec-799b-410f-b3a5-364010d71388.png" width="480">

### Step 3: Toggle grid 
<img src="https://user-images.githubusercontent.com/45864744/147451316-4e616a33-e762-4faf-91f6-cbf45871567d.png" width="480">

Now, you can see that the image disappears and it goes back to what it was before pasted it.
![Snipaste_2021-12-27_16-20-38](https://user-images.githubusercontent.com/45864744/147451423-ae86e164-e18f-4b4f-8a4a-b6876e554737.png)

## More details

**Affected browsers/platforms:** Chrome 96.0 / Windows 11

**First affected release:** r276.2

## System details

<details><summary>View details</summary>

```
Platform information
Browser: Chrome
Browser version: 96.0.4664.110
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 1.5 gb (2.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9674)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
```

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta. Something similar was also happening when toggling onion skinning, that was fixed as well.
