### ISSUE TITLE
Crop leaves empty margins

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5333]
## Problem description

The Crop tool in the Animations Editor leaves small empty margins around the image. I am making a pixel art game and these margins are messing up all the sprites and tilemaps. So after a crop, I need to re-adjust each image manually to remove the margins.
If you want to keep the current behavior, please consider adding a "pixel-perfect" option that would crop precisely without leaving any empty margins.

## Attach a .c3p

[Crop.zip](https://github.com/Scirra/Construct-3-bugs/files/7783445/Crop.zip)

## Steps to reproduce

1. Double click the Sprite to open the Animations Editor
2. Click Crop
3. Zoom in near the edges

## Observed result

A tiny margin remains visible, even though the image has sharp edges (i.e. no shadows or glow)

## Expected result

A perfect crop (Clear-cut!), like most other image-editing software.

## More details

**Affected browsers/platforms:** Chrome and Firefox

**First affected release:**

**Comment by AshleyScirra** [comment]
The 1px padding is by design. It improves the rendering consistency and quality, ensuring internal transparency blends the same way as edge transparency.

A close crop also already exists. As the tool's tooltip says, hold control and click the crop button to remove the padding.

**Comment by Alaadel** [comment]
Thanks! I didn't know that.
The tooltip shows 3 actions: Crop edges, Crop animation, Close crop, but the crop submenu shows only the first 2. It would be nice (and save users like me some time :D ) if it can show the third one as well.

Thank you.
