### ISSUE TITLE
Resizing a sprite on one axis is faulty

### ISSUE THREAD

**Issue by anty21ro** [Scirra/Construct-3-bugs#5334]
layout snap to grid is ON.
When I try to increase the size of a sprite with the mouse, by clicking and dragging one margin of it, both scale axis are triggered.
This happens if the sprite is smaller than the layout grid size (example: layout grid size = 32px, sprite size = 20px)

![ss_drag_snap_faulty](https://user-images.githubusercontent.com/9966693/147602076-23f0be77-bbd6-4107-b2e9-70fc56c6b46d.jpg)
W

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines - we need that information to help.
