### ISSUE TITLE
Touch conditions detects sprite collision even if it's disabled

### ISSUE THREAD

**Issue by anty21ro** [Scirra/Construct-3-bugs#5335]
## Problem description

Touch conditions detects sprite collision even if it's disabled.

## Attach a .c3p
You can find it in System Details.

## Steps to reproduce

Click on the black square.

## Observed result

It detects the collision of the black square by spawning a sprite.

## Expected result

It should do nothing.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

[touch_issues.zip](https://github.com/Scirra/Construct-3-bugs/files/7786193/touch_issues.zip)

**Comment by AshleyScirra** [comment]
I'm not sure this is actually a bug: collisions generally refer to an intersection between two objects. Touch input to one object only involves one object. So it's not exactly the same thing.

Given that changing how existing features works brings a backwards compatibility risk of breaking existing projects that rely on it working the way it already does, and the fact it's not really clear this is actually a bug, I don't think this warrants a change.
