### ISSUE TITLE
Construct 3 Suspending Doesn't Work Properly Inside an Android App.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#5336]
## Problem description

I made a game for an Android app. The app is like a website where you can play many different games/videos on it. When the app is in the background the sound of a C3 game doesn't stop and keeps playing in the background even you open another app on it or turn off the phone's screen.

The other games made with different engines work fine and I tried a C2 project, it also works fine. When I checked the console log inside the app, it seems that C3 doesn't suspend the game when the app is going to the background. It suspends and resumes it at the same time as you re-open the app.

Audio plugin's "Play in background" is unchecked and I tried Worker mode off. I'm not sure if it's a bug but since C2 games work without an issue and suspend the game as soon as they went to the background, I thought it might be a bug.

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.
