### ISSUE TITLE
Failed to open project. check it is a valid construct 3 single-file (.c3p) project

### ISSUE THREAD

**Issue by Stefannag** [Scirra/Construct-3-bugs#5338]
## Problem description

After I saved the project and closed Construct 3 I made a pause. After that pause, I tried to open again the C3 file saved in the cloud, but it didn't work, having the "Failed to open project. check it is a valid construct 3 single-file (.c3p) project" error.

I tried to download the .c3p file, but I get an error (I pasted it at System details).

After that, I tried to open another version of the same project I saved in 10 December, and it appears to have the same error, I couldn't open it.

What should I do?

## Attach a .c3p

Unfortunately, I can't open the project to download it without various images, scripts, and so on. Currently, the game has +350mbs.

## Steps to reproduce

1. Open C3 in the browser.
2. Open the project from the cloud.

## Observed result

An error appeared: "Failed to open project. check it is a valid construct 3 single-file (.c3p) project"

## Expected result

To open the project properly.

## More details

I use Chrome.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

//THIS IS THE ERROR FROM WHERE I TRY TO DOWNLOAD THE .C3P

Error report information
Type: unhandled rejection
Reason: {"response":null,"code":0,"status":""}
Construct 3 version: r276.2
URL: https://editor.construct.net/
Date: Thu Dec 30 2021 12:55:45 GMT+0200 (Eastern European Standard Time)
Uptime: 8.5 s

Platform information
Browser: Chrome
Browser version: 96.0.4664.110
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 950M Direct3D11 vs_5_0 ps_5_0, D3D11-23.21.13.8857)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by Stefannag** [comment]
It seems that if I download the .c3p file directly from Google Drive, and after that, I open it via Construct 3 Desktop App, it is working. So, it seems to be a problem with the browser version. I have the latest stable version.

**Comment by AshleyScirra** [comment]
It looks like a problem with Google Drive rather than an issue with the project file. I just tried opening a project from Google Drive and it worked fine. So it probably involves some more specific set of circumstances than those you described.

I'm afraid there's very little we can do without steps to reproduce the problem in the first place. If you can identify how to reproduce the problem, please file another issue with those steps. The project file shouldn't matter, so you can probably just use a new empty project for that.
