### ISSUE TITLE
color picker breakes zoom via mouse wheel

### ISSUE THREAD

**Issue by Sanchopi** [Scirra/Construct-3-bugs#5339]
## Problem description

If you tint a sprite with the color picker tool, the zoom with "control" + "mouse wheel" is defective.

[Color Picker Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/7793004/Color.Picker.Bug.zip)

## Steps to reproduce

All steps are listed in the attached project file.

## Observed result

Zoom with "control" + "mouse wheel" is defective.

## Expected result

Zoom with "control" + "mouse wheel" should work well.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It seems to work fine here. Ctrl+mouse wheel keeps working as zoom even after using the color picker.

Note if you focus away from the Layout View, its keyboard shortcuts will stop working, by design. You may need to click back in to the Layout View to focus it again.

**Comment by Sanchopi** [comment]
Hi Ashley,

I forgot to say, this happens with the app downloaded via chrome and run from desktop. The OS is Windows 7 ...
But anyways, seems to be a very little bug, no one else notice at all.

Wish you guys a happy and successful new year!
