### ISSUE TITLE
AJAX - Request project file doesn't work in HTML5 and Android

### ISSUE THREAD

**Issue by UeliSo** [Scirra/Construct-3-bugs#534]
## Problem description

AJAX - Request project file doesn't work in HTML5 and Android.

## Attach a .c3p

[AJAX Read Permission Test.zip](https://github.com/Scirra/Construct-3-bugs/files/1083470/AJAX.Read.Permission.Test.zip)

## Steps to reproduce

1. Run the project local or remote - it works.
2. Export the project to Windowsphone 10 - it works
3. Export the project to HTML5
4. Upload it to itch.io and run it
(5. Exporting to Android gives Access error as well)

## Observed result

Showing error message.
See https://5pm.itch.io/ajax-test?secret=fGTHyyNshBQIqf3r5dei06qk

## Expected result

Showing 'File content'

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r38.2

Local storage
Storage quota (approx): 6.5 gb
Storage usage (approx): 348 mb (5.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The itch.io server is returning 403 Forbidden for the request. It's not a bug, the server is saying you don't have permission to do that. You should probably talk to itch.io to sort out why their server is doing that.

**Comment by UeliSo** [comment]
Creating an apk within C3 and installing it on an Android 6 phone doesn't work neither. It doesn't show the content of the file or any error message. If it's not a bug but a configuration problem, then maybe the default export options of C3 should make this word out of the box? It's very confusing.

**Comment by shortercode** [comment]
@UeliSo it sounds like the Android bug is a different issue, but with the same symptom.

**Comment by UeliSo** [comment]
I found out what the underlying problem is: C3 doesn't handle the local text file creation correctly. When you create a new file or rename an existing one to "MyFile.txt" C3 actually creates "myfile.txt", while maintaining the intern reference "MyFile.txt". In Windows this doesn't matter, but when you then try to make the AJAX-Call on a case sensitive OS (Android, itch.io) it won't work.

**Comment by UeliSo** [comment]
I opened a new issue #654.

**Comment by UeliSo** [comment]
The underlying problem is that when crating a new file, C3 lowercases automatically the file name, but doesn't lowercase the reference to that file. This causes problems on case sensitive operating systems.
