### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#5342]
When exporting android or ios during cloud build, I get an error and the build stops, this was not the case before.

**Comment by ERAgames777** [comment]
I tried to make an empty project without plugins and it exported successfully, but after I added the "MobileAdvert" plugin from Scirra and the export does not occur, it gives an error, I will attach a screenshot:
![Screenshot](https://user-images.githubusercontent.com/33450672/147873985-ded93a4f-7735-4d52-b650-c6c57c6f25a7.png)

**Comment by EJAMIARTSTUDIO** [comment]
![unknown](https://user-images.githubusercontent.com/96992927/147884364-eb877112-346e-45a7-a026-fc275e7a6177.png)
SAME SHIT
https://www.construct.net/en/forum/construct-3/general-discussion-7/cannot-connect-build-server-131519
It's been four years and these guys still can't handle the problem properly.

**Comment by AshleyScirra** [comment]
The build service has been rebooted and should be working again now. Apologies for the inconvenience.

**Comment by ERAgames777** [comment]
@AshleyScirra thank you Ashley!
