### ISSUE TITLE
Sine preview not working if the object has a parent and the Movement is Size

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5343]
## Problem description

Sine preview (only in the editor) not working if the object has a parent and the Movement is Size

## Attach a .c3p
[Sine.zip](https://github.com/Scirra/Construct-3-bugs/files/7797923/Sine.zip)

## Steps to reproduce

1. Click the blue sprite.
2. Check the Preview box in its Sine behavior properties.

## Observed result

The size squares disappear from around the sprite, but the preview doesn't play.

## Expected result

Normal preview.

## More details
Removing the sprite from its hierarchy will make the preview run.

**Affected browsers/platforms:** Firefox 95.0.2

**First affected release:**

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
