### ISSUE TITLE
Sine Size works with initial size, not current size

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5344]
## Problem description

I have an object with size 72x72 in the editor, and has Sine behavior. At runtime, I set it to 250x250 and enable the sine. The object returns to the previous size, instead of staying the same size!

## Attach a .c3p

[sine size.zip](https://github.com/Scirra/Construct-3-bugs/files/7798662/sine.size.zip)

## Steps to reproduce

1. Preview the game
2. Drag the green sprite to the brown sprite

## Observed result

The object is resized, but when the sine starts, it goes back to the initial size.

## Expected result

The sine should work relative to the _current_ size, not the initial size.

## More details

**Affected browsers/platforms:** Firefox 95.0.2

**First affected release:**

**Comment by AshleyScirra** [comment]
This is by design. Use the "Update initial state" action after changing the size if you want to set that as the new state to oscillate from.
