### ISSUE TITLE
Resizing a sprite on one axis is faulty 

### ISSUE THREAD

**Issue by anty21ro** [Scirra/Construct-3-bugs#5347]
## Problem description

When trying to resize the height of the sprite with the mouse , in the example I've added, the width size is modifying, too by snapping to grid. 
Layout "Snap to grid" is enabled in Properties.

## Attach a .c3p

The file can be found at the bottom of the page.

## Steps to reproduce

1. Try to resize the height of the sprite with the mouse cursor.

## Observed result

Height and Width size of the sprite is triggered.

## Expected result

Only the height should snap to grid.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

Platform information
Browser: Chrome
Browser version: 96.0.4664.110
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 127 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9649)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>
[resize_issues.zip](https://github.com/Scirra/Construct-3-bugs/files/7803003/resize_issues.zip)

**Comment by AshleyScirra** [comment]
I think this used to work but I suspect recent changes by @DiegoScirra changed it, so assigning to him. (Resizing on one axis should only change the size on that axis, but it looks like it always sets both the width and height when resizing, which causes the wrong snapping behavior.)

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
