### ISSUE TITLE
Repeatable crash moving object to global overridden layer 

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-3-bugs#535]
## Problem description

When attempting to move an object to a global overridden layer the project will crash.

## Attach a .c3p

https://www.dropbox.com/s/ukul6fqciv2koj2/globalLayerTest.c3p?dl=0

## Steps to reproduce

1. Create a new project
2. Add a layer to Layout 1
3. Make Layer 1 (the top layer) global
4. Duplicate Layout 1
5. Select Layout 2
6. Select Layer 0 (non-global)
7. Add a text object to Layer 0 (bottom layer)
8. In the text object's instance properties select the layer option
9. Select Layer 1 (top layer, overridden)

## Observed result
The project will crash

## Expected result

The project allows the object to be added or prevents the object being added to the overridden global layer

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r38-2/main.js, line 61, col 205235
Message: Uncaught Error: cannot move to overriden layer
Stack: Error: cannot move to overriden layer at o.ǃhG (https://editor.construct.net/r38-2/main.js:61:205241) at o.ǃvS (https://editor.construct.net/r38-2/components/bars/propertiesBar/propertiesBar.js:1:21835) at ǃC.ǃk.ǃQ.ǃU.ǃwmC (https://editor.construct.net/r38-2/main.js:2:439370) at ǃC.ǃk.ǃQ.ǃwmZ.ǃwmw (https://editor.construct.net/r38-2/main.js:2:419429) at ǃC.ǃk.ǃQ.ǃwmZ.ǃmV (https://editor.construct.net/r38-2/main.js:2:419833) at HTMLSelectElement.ǃwog (https://editor.construct.net/r38-2/main.js:2:418798)
Construct 3 version: r38.2
URL: https://editor.construct.net/index.html
Date: Mon Jun 19 2017 11:53:45 GMT+0100 (GMT Summer Time)
Uptime: 164.3 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r38.2

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed  in r40.

Now it is possible to move instances to and from overridden layers. Bear in mind that when you do this, the actual changes are made to the source global layer.
