### ISSUE TITLE
The advertising plugin does not work in version r276 and higher!! 1000 requests, 0 impressions!!

### ISSUE THREAD

**Issue by arnallia** [Scirra/Construct-3-bugs#5351]
The advertising plugin does not work in version r276 and higher!! 1000 requests, 0 impressions!!! The project now does not open in older versions! Result:lost income

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines as otherwise it is impossible for us to help you.

Issues with ads are also commonly just misconfiguration, so please double-check you have everything configured correctly as per the [manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/mobile-advert).

**Comment by layilpaht** [comment]
> Please follow the bug report guidelines as otherwise it is impossible for us to help you.
> 
> Issues with ads are also commonly caused by misconfiguration, so please double-check you have everything configured correctly as per the [manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/mobile-advert).

There were 1000 requests which prove that the plugin was working. This can not only lead to loss in revenue but admob account can also get banned

**Comment by layilpaht** [comment]
> The advertising plugin does not work in version r276 and higher!! 1000 requests, 0 impressions!!! The project now does not open in older versions! Result:lost income

Can you please describe the issue with more details (version number, which type of ads:- banner,interstitial or video & more details)

**Comment by arnallia** [comment]
Hi! It's not just me who has this problem! I have been working with construct for a long time, everything is configured correctly, ads in the ios version are not shown in android.
https://www.construct.net/en/forum/construct-3/general-discussion-7/introducing-web-adverts-r269-164580 
>Среда, 5 января 2022, 14:00 +03:00 от Ashley (Scirra) ***@***.***>:
> 
> 
>Please follow the bug report guidelines as otherwise it is impossible for us to help you.
>Issues with ads are also commonly just misconfiguration, so please double-check you have everything configured correctly as per the  manual entry .
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <Scirra/Construct-3-bugs/issues/5351/1005585885 @ github . com> 
 
 
--
1111 1111111111
Отправлено из Почты  Mail.ru

**Comment by arnallia** [comment]
Hi! It's not just me who has this problem! I have been working with construct for a long time, everything is configured correctly, ads in the ios version are not shown in android.
https://www.construct.net/en/forum/construct-3/general-discussion-7/introducing-web-adverts-r269-164580
>Четверг, 6 января 2022, 10:46 +03:00 от layilpaht ***@***.***>:
> 
> 
>Please follow the bug report guidelines as otherwise it is impossible for us to help you.
>Issues with ads are also commonly caused by misconfiguration, so please double-check you have everything configured correctly as per the  manual entry .
There were 1000 requests which prove that the plugin was working. This can not only lead to loss in revenue but admob account can also get banned
—
Reply to this email directly,  view it on GitHub , or  unsubscribe .
Triage notifications on the go with GitHub Mobile for  iOS or  Android .
You are receiving this because you authored the thread. Message ID:  <Scirra/Construct-3-bugs/issues/5351/1006350397 @ github . com>  
 
--
1111 1111111111
Отправлено из Почты  Mail.ru
