### ISSUE TITLE
If fullscreen quality is set to "low" and fullscreen mode is set to "scale outer" the game crashes when the window's height is small

### ISSUE THREAD

**Issue by mitsuhashish** [Scirra/Construct-3-bugs#5352]
#5329 

UPDATED ISSUE

## Problem description
When on android, due to how the keyboard influence the size of the viewport compared to iOS where the size remains the same if the phone is in landscape and fullscreen mode is set to "scale outer" and fullscreen quality is set to "low" the game seems to crash/stop working resulting in a WebGL texture size error.
I recently discovered the issue extends to what seems to be all other browsers and OS too, simply reducing the window height to a small size while maintaining its width will trigger the bug too, which results in the same scenario and behavior as the bug I've previously misdiagnosed on android.

## Attach a .c3p
[CrashExampleMobileKeyboard.zip](https://github.com/Scirra/Construct-3-bugs/files/7770217/CrashExampleMobileKeyboard.zip)

## Steps to reproduce

ANDROID:
1. set the fullscreen mode to "scale outer"
2. set fullscreen quality to "low"
3. run the game
4. put the phone in landscape
5. tap the textbox to trigger the keyboard

WINDOWS:
1. set the fullscreen mode to "scale outer"
2. set fullscreen quality to "low"
3. run the game
4. reduce the window height until it's very thin

## Observed result

The game stops working if the fullscreen mode is set to "scale outer" and the fullscreen quality is set to "low"

## Expected result

The game continues to work if the fullscreen mode is set to "scale outer" and the fullscreen quality is set to "low" in the same way it works when fullscreen quality is set to "high"

## More details
>Logged error : (need to connect thru USB to see in logs)

Uncaught (in promise) Error: texture exceeds maximum texture size (texture.js:15)
    at WebGLRendererTexture._CreateDynamic (texture.js:15)
    at WebGLRenderer.CreateDynamicTexture (webglRenderer.js:52)
    at WebGLRenderTarget._Create (renderTarget.js:4)
    at WebGLRenderer.CreateRenderTarget (webglRenderer.js:54)
    at CanvasManager.GetAdditionalRenderTarget (canvasManager.js:39)
    at C3Runtime.GetAdditionalRenderTarget (runtime.js:44)
    at Layout.Draw (layout.js:39)
    at C3Runtime._Render (runtime.js:86)
    at C3Runtime.Render (runtime.js:85)
    at C3Runtime.Tick (runtime.js:72)

**Affected browsers/platforms:** 

- Chrome 81 on Android 4.4.4
- Chrome 97.0.4692.71 on Windows 10
- Firefox 95.0.2 on Windows 10
- Probably more, only had the chance to test those

## System details
Android 4.4.4
Windows 10 lastest

**Comment by AshleyScirra** [comment]
As of r272, the virtual keyboard on Android should work like it does on iOS, i.e. overlay the game rather than cause it to resize. I suspect you are only seeing the resizing happening because you are running an unsupported version of Android (4.4, only 5.1+ is supported by Construct).

However the issue does reproduce on Windows 10, so fixed for the next beta.
