### ISSUE TITLE
ReplaceSolidColor effects applied to families drops FPS after r269

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#5353]
## Problem description

Construct r269 and prior had no issues applying multiple ReplaceSolidColor effects to families of sprites and tilemaps. But the same project running in r270 to r277 has significant FPS drops (averaging 50% or more).

## Attach a .c3p

https://drive.google.com/file/d/1Tj7wVi8zONTk48STCS3J8WM-J3dbF5dX/view?usp=sharing

## Steps to reproduce

**1. Open the attached project in r269.**
2. Ensure that Construct runs previews in a Browser Tab, and the project's Fullscreen Quality is set to High.
3. Preview the project.
4. Make the browser tab as large as you can on your screen (press F for fullscreen if you prefer)
5. Note the FPS stabilizes at 60 and the effects are disabled. 
6. Use the arrow keys the camera left and right across the layout; note no change to the FPS.
7. Press Space to toggle on the ReplaceSolidColor effects.
8. Note the FPS should remain at 60; moving the camera should also show no change.

**9. Open the attached project in r277.**
10. Ensure that Construct runs previews in a Browser Tab, and the project's Fullscreen Quality is set to High.
11. Preview the project.
12. Make the browser tab as large as you can on your screen.
13. Note the FPS stabilizes at 60 and the effects are disabled.
14. Move the camera left and right across the layout again; note no change to the FPS.
15. Press Space to toggle on the effects.
16. Note the FPS drops considerably (in my tests, to approx 25-35 FPS)
17. Moving the camera with the arrow keys demonstrates the severity of the issue.
18. Press Space to toggle off the effects.
19. Note the FPS returns to 60.

## Observed result

A project that performed perfectly in r269 and earlier now has serious performance issues. 

## Expected result

The performance in r270 and beyond should match that of r269 and earlier. Families of sprites and tilemaps should still be able to render multiple effects without performance issues.

## More details
It's important to note that Fullscreen Quality needs to be set to High. Setting it to low in r270—r277 does retain 60 FPS, but causes considerable judder when the layouts scroll, making the project equally problematic. 

In the case of my two projects, the new Layer Effects approach isn't a workaround, as objects on the same layer will share pixel colours. Sprites and tilemaps need to have effects enabled/disabled at a per-instance level, versus a layer level, and so Families are the most efficient way I can see to achieve this.

**Affected browsers/platforms:** Chrome 97.0.46  //  Safari 15

**First affected release:** r270

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
r278 includes some optimisation work on the new effect compositor. Does this help your case?

**Comment by brushfe** [comment]
It seems like you've solved it! Thanks very much!

**Comment by AshleyScirra** [comment]
Thanks for confirming!
