### ISSUE TITLE
Looping relative timeline opacity slowly offsets over time

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#5355]
## Problem description

I have a tutorial animation made with timeline that slowly offsets over time in relative mode

## Attach a .c3p

don't have time to repro for now, because copy pasting timelines between projects fails (see https://github.com/Scirra/Construct-3-bugs/issues/5354)

## Steps to reproduce

1. Create a looping relative timeline that loops opacitty going from -100% to 0% back and forth
2. Play
3. Wait for a few minutes

## Observed result

The opacity slowly drifts off from its initial point.
You can see it happen here: https://zenblockspoki.surge.sh/

The tutorial slowly drifts and after a few minutes, the opacity is incorrectly looped

## Expected result

The timeline should loop correctly

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by therealPaulPlay** [comment]
I have the same issue, for me it only offsets when there is a change happening right at the end or beginning of the timeline. (So if the value is changing till the end)

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.
