### ISSUE TITLE
Newlines in dictionary editor

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#5358]
## Problem description

When you enter a new line (shift+enter) in the value of a dictionary key in the built-in editor, once you confirm the edit with "enter" the new line gets deleted.

If I paste the invisible character between theses lines, it does save it (same character you add when adding a key in run-time and building the string with new lines)

text1
text2

## Attach a .c3p
 
[dicEditNewline.zip](https://github.com/Scirra/Construct-3-bugs/files/7840155/dicEditNewline.zip)

## Steps to reproduce

1. Open the dictionary file in the built-in editor
2. See key 1 includes a new line
3. Try to do the same with key 2, using shift+enter

## Observed result

Once you confirm the edit, the new line gets deleted.

## Expected result

New lines converted into the special character.
P.S I tried just putting \n as it's saved in the actual file, but that just put it in as a text string.

## More details

**Affected browsers/platforms:** Chrome/NWjs, Windows

**First affected release:** I'm not sure if it ever worked, maybe it's an enhancement rather than a bug.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
