### ISSUE TITLE
Canwas bug r 277

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#5359]
canvas incorrectly inserts shadow light when default Normalized mode is set. After installing regular mode, the display is correct. I have attached c3p. To repeat, run the project in the Normalized and regular mode and see the result.

[## Attach a .c3p](https://drive.google.com/file/d/150oN1tC5ZANewGq-u-yK-SPs5AwD2lXO/view?usp=sharing)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
In the latest beta the project looks identical to me with both regular and normalized Z axis scale.

Please always follow the full bug report guidelines to ensure we can properly investigate your report.
