### ISSUE TITLE
iOS builds succeed but fail to open in simulator or hardware

### ISSUE THREAD

**Issue by part12studios** [Scirra/Construct-3-bugs#536]
## Problem description

I've done a number of successful builds in xcode but it seems like none of them will run in the simulators or hardware.  

## Attach a .c3p

[Soaring.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1084831/Soaring.c3p.zip)

## Steps to reproduce

1. export the app for iOS
2. open the project in xcode
3. build the app (succeeds)
4. attempts to run simulator but see just a black screen

## Observed result

I just see a black screen.  no C3 loading screen. 

## Expected result

See the game run.  

## Affected browsers

None, not a browser issue

## System details

i7 iMac (mid 2011)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Just tried this and it does show the loading screen, which is admittedly broken but I'm working on that. What options are you using with the build?

**Comment by part12studios** [comment]
I’m not doing any special settings. i open the project and build.  i get a bunch of warnings but the build succeeds.  I wouldn’t know what options to check in xcode.  

as for in c3.. basics.. i don’t check anything..  except hide status bar.  

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios <http://part12studios.com/>

**Comment by shortercode** [comment]
Okay, well I'm using the default settings with your project. Have tried with and without hide statusbar checked and it showing me the loading screen each time. If I send you an xcode project would you mind trying to run it on your machine? This will tell me if your xcode is acting up, or we're missing something.

**Comment by shortercode** [comment]
[soaring.cordova (1).zip](https://github.com/Scirra/Construct-3-bugs/files/1085054/soaring.cordova.1.zip)

I've just run that project, it won't ever complete loading but it will show the loading screen. So for this we're considering it known good ( I'm fixing the other issue at the moment )

**Comment by part12studios** [comment]
ok cool that might still be an improvement.  i’ll test it. 

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios <http://part12studios.com/>

**Comment by shortercode** [comment]
Okay just as a head up I've fixed the other issue with the loader where it would get stuck, there should be a fix for that coming in r40. I still haven't been able to repeat your issue, and i've been using your project for test builds most of today so I don't think it's that.

If the xcode project I sent you works then it's an issue with a config option in C3, if it doesn't then it's a config issue on xcode for your device...

**Comment by part12studios** [comment]
Ok I opened the project today and it built fine.  when it runs the simulator it shows the apple logo..  and yes now i see the loading screen..  and it went past the cordova screen to the C3 loading screen.. which it appears to hang..  so that’s good to see.   

my settings are:

deduplicate images unchecked

recompress images unchecked

minify script unchecked


9/0+

hide status bar checked

require vib unchecked

requrie cam unchecked



i then click “build app”

download 



and i do now see with this build that i get to the C3 screen.. i didn’t do anything different so maybe R37 somehow?  /shrug..  ok so yes i’m where you are it seems..  ultimately the game will not load.  you can  close this issue of not loading at all.  

Thanks for verifying!  



Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios <http://part12studios.com/>

**Comment by shortercode** [comment]
**shrugs** I'd put it down as a grouchy computer, sounds like you were doing everything right and the problem isn't there any more. I don't think there's been any significant changes in runtime that would have fixed it in recent builds, I know ashley did fix some security issues in WKWebView for the pathfinder plugin but I don't see how that would be affecting you. Glad to hear the problem is solved and let me know if you have any other issues when r40 hits and you can actually load a game with audio... 

Incidentally adding an mp4 version of each of your audio files will both increase loading speed and bypass the broken loader at the moment for iOS development.

**Comment by part12studios** [comment]
Yea i really don’t know but yea something choked and isn’t now..  i’m pretty “don’t touch anything!” in my approach to stuff.. 

Ok thanks for that tip.  I just want to see if iOS runs faster / better than the android version.

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios <http://part12studios.com/>
