### ISSUE TITLE
Formatting Text With roundtodp 

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#5360]
## Problem description
Formatting text using roundtodp() does not format correctly when the text object is set to center alignment.

## Attach a .c3p

https://www.dropbox.com/s/e6shnhux12lkysq/roundtodptext.c3p?dl=1
## Steps to reproduce

1.Run the project

## Observed result
The text objects(text, and spritefont) jitter on the instances with center alignment.

## Expected result

There should be no jitter.
## More details

**Affected browsers/platforms:** 

**First affected release:** 
277 untested in others.
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's working correctly. Numbers like 0.3 are not as wide as 0.33, and center alignment will position it in the middle.

**Comment by pigmalien** [comment]
Ok, I guess I was taking round to n decimal places too literally.
