### ISSUE TITLE
Text Object is Vibrating / Jittery

### ISSUE THREAD

**Issue by BluePinStudio** [Scirra/Construct-3-bugs#5361]
## Problem description

When the camera is moving smoothly, text objects appear to vibrate or jitter. This is most noticeable when moving diagonally. Keep in mind, this issue does not occur when using a sprite object. I have attempted to change the pixel rounding setting, the scaling, downscaling, fullscreen quality all to no avail.

## Attach a .c3p

[Jittery_Text.zip](https://github.com/Scirra/Construct-3-bugs/files/7842258/Jittery_Text.zip)

## Steps to reproduce

1. Open the project and move around using WASD or Arrow keys
2. You will notice that the text object (on the left) will vibrate while the sprite object (on the right) will not.
3. Optionally you can use the auto pilot feature for the camera to move automatically while you stare at the text object.

## Observed result

Text object vibrates

## Expected result

Text object doesn't vibrate, like the sprite object adjacent to it.

## More details

**Affected browsers/platforms:** Happens in chrome preview & in nw.js exports.

**First affected release:**  Not sure, I've only recently noticed this when moving from Sprites to Text Objects in my project.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 97.0.4692.71
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 1.2 gb (1.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.100.7325)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks perfectly smooth for me here, but I tested with a high-dpi display so sub-pixel jitter may be harder to see.

The Text object has some logic in it to basically do some degree of pixel rounding in order to preserve the text quality. If it allowed perfectly smooth movement like with sprites, then at some camera positions the text will appear blurry. Applying a small degree of pixel rounding ensures the text is pixel-aligned when it is drawn, ensuring the text appears sharp and more readable. I suppose this could cause a small amount of jitter on low-dpi displays, but the alternative is blurry text in some circumstances (which will surely result in a follow-up bug report about blurry text). So I think this is basically by design for the Text object.
