### ISSUE TITLE
Saves Crashing With Timeline

### ISSUE THREAD

**Issue by hammanneric6** [Scirra/Construct-3-bugs#5362]
## Problem description

I am having an issue with save games being loaded in conjunction with the use of timelines.  In short the game fails to load a save according to chrome the issue is to do with timelines.  I don't tend to download the betas anymore so this may have begun sooner but from what I can tell the problem made itself known in R276.  I updated to R277 and the problem still persists.  Below is an attached screenshot of the error code that is displayed when running the game in NW.js.  That said I have reported similar issues to this in the past although I cannot say if it was the same exact bug.

Another thing to note, I was looking at the bug reports from other users and there is issue #5356 .  This seems to be something similar so the issues may be linked, I just wanted to mention that.  The error code reported in that bug report doesn't match the one I posted below however.

## Attach a .c3p

I have tried making a minimal project, but for the life of me I can't seem to reproduce the issue.  If you absolutely need a project file I would be more than happy to send the actual game file privately and point out the code that is running.  Apologies, I know a test file is very important.  If you do need this just give me an email to send to and I'll send it over right away.

## Steps to reproduce

Load the save from the load screen

## Observed result

The game will load the save however certain events are set to run on the "On Load Complete" event and they never trigger because the load technically fails.

## Expected result

The game should load successfully.

## More details
**Affected browsers/platforms:** NW.js (version 0.52) (apologies if this is the cause there isn't a greenworks plugin that works with any newer version)
Chrome V96.0.4664.110

**First affected release:** As stated above R276 was the first release I saw this happen in, I don't download betas but things were working normally in R268

![C3 Timeline Error](https://user-images.githubusercontent.com/11020190/148868849-f32a3786-e2d6-490b-ad8a-00ee41c28d82.PNG)

**Comment by DiegoScirra** [comment]
If you can post your project with some steps on how to recreate the crash in it, it would be very helpful.

**Comment by DiegoScirra** [comment]
This should be fixed in the next beta. It's hard to tell without reproduction steps though, so you will need to try it out.

**Comment by hammanneric6** [comment]
Looks like a project won't be needed.  I downloaded r278 and ran everything again on that export and its all working normally again.  Thanks for addressing this as quickly as you did, very appreciated, and sorry again that I couldn't just post a simple project for an example.
