### ISSUE TITLE
Strange Fill Tool behaviour

### ISSUE THREAD

**Issue by Calart** [Scirra/Construct-3-bugs#5364]
## Problem description

Flood Fill tool with tolerance below 6 causes transparent 1x1 pixel holes appearing in the filled area.

The Flood Fill tool seems to fill into random areas rather than the whole area.

The type of sprite seems to have no effect on this issue. I also noticed the problem is worse the smaller scale the sprite you use the tool on.

I believe the addressed issue could be a minor fix with a little added browser support

## Attach a .c3p
[Minimal Construct Demo File](https://drive.google.com/file/d/1FsnLajFYHp9OpfOfrW0qxy7zA7lOUSfY/view?usp=sharing)

## Steps to reproduce

1. Open up Construct 3 editor with Brave (browser)
2. Open provided file or Create new project
3. Create or open a new tiled background sprite. 
4. Locate the fill tool and pick a random color with alpha set to the max value.
5. Set fill tools tolerance to 0, or make sure tolerance is lower than 6
6. Use fill tool on blank/transparent area

## Observed result

Transparent 1x1 pixel holes appearing in the filled areas.

## Expected result

Complete coverage of color, since there is a clean sprite with no pixel artifacts/graphics in the way.

## More details

I've only had this issue on the Brave browser. I love this browser and I want to keep using it for things like Construct.

I could not reproduce it in Firefox or Chrome, and Opera GX.

I was confused when their was a spread of 1x1 pixel holes appearing when using Flood fill tool.

I tried several tolerances, on a new tiled background to see when it started creating these holes in my filled area. It seemed to get fixed when hitting the tolerance 6. I couldn't find any reason why, and thought it might be related to the sampling options, but this does not seem to be the case, at least for me. I've never encountered this issue before.

**Affected browsers/platforms:** 

Known affected browsers: Brave

Known browsers that aren't affected: Chrome/Firefox/Opera GX

**First affected release:** 

I last heavily used the engine around r260. However I believe that r268 it broke, although I could be wrong. 
I haven't haven't this issue before, while using Construct 3 in Brave, of what I know.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 97.0.4692.71
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 10
Approx. device memory: 0.5 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 2 gb
Storage usage (approx): 49 mb (2.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5730)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This is very strange.

I'll look into it... but this might be a feature of Brave. Since it is geared for security, maybe it garbles ImageData on purpose to prevent mischievous application from obtaining information that could be used for finger printing.

**Comment by DiegoScirra** [comment]
This is in fact a feature of Brave, known as **"Farbling"**

You can read more about it [here](https://brave.com/privacy-updates/4-fingerprinting-defenses-2.0/#farbling)

The article shows all the APIs which Brave modifies to prevent finger printing, the one that is affecting the Animations Editor is **CanvasRendering2dContext.getImageData**. There are other things which might also be affecting C3 in very subtle ways.

This isn't really something that can be fixed, it's one of the features that Brave uses that offers online security.

I think the easiest thing to do is toggle Brave's **Shields** to **DOWN** when visiting **editor.constrcut.net**. The toggle is in the right most side of the address bar, should be easy to find.
