### ISSUE TITLE
Androix build export failed

### ISSUE THREAD

**Issue by SteroideBello** [Scirra/Construct-3-bugs#5365]
## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>
![Screenshot_1106](https://user-images.githubusercontent.com/36568899/149121588-fa388fbc-33d7-42f1-ad28-3e71d018e1e8.png)

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it is impossible for us to help.

**Comment by fredriksthlm** [comment]
It states **_Invalid character in entity name_**
Try to verify your name, description and so on, and make sure to only use a-z 1-9 to be safe.
