### ISSUE TITLE
Weird drag and drop and destroy error

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#5366]
## Problem description

Here's the set up:
Have a family with drag and drop behavior
With mouse addon, on click on object, destroy it
With family's drag and drop, on drag start, move to top of layer

This creates a ghost instance with no world info that C3's layer tries to sort, and it crashes the game

## Attach a .c3p

[DestroyDragError.zip](https://github.com/Scirra/Construct-3-bugs/files/7855228/DestroyDragError.zip)

## Steps to reproduce

1. Click on sprite

## Observed result

```
layer.js:33 Uncaught (in promise) TypeError: Cannot read properties of null (reading '_SetZIndex')
    at Layer._UpdateZIndices (layer.js:33:326)
    at Layer.Draw (layer.js:49:47)
    at Layout._DrawLayerList (layout.js:41:286)
    at Layout.Draw (layout.js:39:300)
    at C3Runtime._Render (runtime.js:86:207)
    at C3Runtime.Render (runtime.js:85:144)
    at C3Runtime.Tick (runtime.js:72:399)
    at normal (runtime.js:7:38)
```

## Expected result

If you do the same thing but use the same object both times, this doesn't happen. So I guess whatever extra check you do for regular object types, also do it for family object types :+1: 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
