### ISSUE TITLE
Image editor adjusts the opacity of the top row of pixels

### ISSUE THREAD

**Issue by craigsssmith** [Scirra/Construct-3-bugs#5368]
## Problem description

When the height of an image is 24, 25, or 26 pixels, the opacity of the top row of pixel in the image editor is set to be one less than the opacity of the currently selected colour.

## Attach a .c3p

I have not attached a project because it could not demonstrate the problem.

## Steps to reproduce

1. Start a new project.
2. Create a new Sprite object type (thought it can be any object type that uses the image editor).
3. In the image editor, resize the image to 24 x 24 pixels.
4. Select RGBA 0,0,0,255 as the current colour.
5. Fill the image with black.
6. Switch to the colour picker tool and observe that the alpha value of each of the top row of pixels is only 254.

## Observed result

The top row of pixels has an alpha value of 254, instead of 255.

## Expected result

The top row of pixels should be the same as the currently selected colour.

## More details

- If the height of the image is less than 24, the problem does not occur.
- Likewise, if the height of the image is greater than 26, the problem does not occur.
- The width of the image does not seem to affect things.
- The problem occurs when using the fill tool, but also when using the other drawing tools, such as the line tool and the pencil.
- The dimensions of the canvas does not seem to affect things.

**Affected browsers/platforms:** 

I've tested on Chrome, Firefox, and Safari, and it only seems to affect Chrome. I'm using Chrome 96.0.4664.55.

**First affected release:** 

I've tested every version of C3 as far back as r260 and it affects all versions.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Can't reproduce this one, does it still happen in the latest version of Chrome? That is **98.0.4758.81**

**Comment by AshleyScirra** [comment]
No response for ~2 weeks and issue cannot be reproduced so closing.
