### ISSUE TITLE
Cant open game after reset browser

### ISSUE THREAD

**Issue by benjaboyy** [Scirra/Construct-3-bugs#5369]
## Description
I had a problem that construct coud not open my project on some PC's, no matter the browser (Crome, IE, firefox).
But at my PC at home it was working fine.
After a browser reset on my personal PC im not able to edit the program on my home PC as well.
I load game and screen gets RED with an error.

I dont use extra addons

## Attach a .c3p

[Download](https://www.deschuurr.nl/wp-content/uploads/2022/01/AirForceUltraMobile.zip)

## Reproduce

1.Open project on a "fresh" browser instalation

## Observed result

Red screen with error

## Expected result

Being able to edit game

## More details

**Affected browsers/platforms:** Chrome, IE, Firefox

**First affected release:** R276 and probably earlier 

## System details

Error report information

<details><summary>
View report details
</summary>

Type: assertion failure
Message: no addon registered
Stack: xa.ENa@https://editor.construct.net/r276-2/main.js:931:289 window.assert@https://editor.construct.net/r276-2/main.js:849:38 t0@https://editor.construct.net/r276-2/projectResources.js:1022:263 Ga@https://editor.construct.net/r276-2/projectResources.js:1029:328 npc@https://editor.construct.net/r276-2/projectResources.js:1031:32 Ga@https://editor.construct.net/r276-2/projectResources.js:1011:336 ELb@https://editor.construct.net/r276-2/projectResources.js:1015:251 Tfb@https://editor.construct.net/r276-2/projectResources.js:1015:359 Ga@https://editor.construct.net/r276-2/projectResources.js:950:198 FLb@https://editor.construct.net/r276-2/projectResources.js:955:204 ppc@https://editor.construct.net/r276-2/projectResources.js:955:350 Ga@https://editor.construct.net/r276-2/projectResources.js:882:194 mpc@https://editor.construct.net/r276-2/projectResources.js:884:416
Construct 3 version: r276.2
URL: https://editor.construct.net/
Date: Thu Jan 13 2022 11:09:36 GMT+0100 (Midden-Europese standaardtijd)
Uptime: 67.4 s
Platform information

Browser: Firefox
Browser version: 96.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0
C3 release: r276.2 (stable)
Language setting: nl-NL
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0, D3D11-24.20.100.6286)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
It opens fine for me, both in my existing setup and an incognito window which simulates a fresh setup.

I'm afraid as per the bug report guidelines there's nothing we can do unless you can provide reliable steps to follow to reproduce the issue. Can you provide these?

**Comment by benjaboyy** [comment]
Thanks, @AshleyScirra, for looking into my problem.

Incognito is not the same as a clean installation.
Every pc that never had Construct.net on it is unable to run the game file.
I can't see any other way to reproduce this bug.

Since I don't want to waste a half year of work, is there any other way to get more information out of my problem?

**Comment by benjaboyy** [comment]
I got something!
When I deleted the timelines out of the project, I'm able to open it again on all PC's.
I provided a screenshot!
![afbeelding](https://user-images.githubusercontent.com/16157766/149394582-54493360-abee-43a5-bf74-383772904691.png)

**Comment by AshleyScirra** [comment]
An incognito tab should be the same as a clean installation: it acts as if you are loading Construct for the very first time.

Try removing any browser extensions in case they are interfering in some way.

I'm afraid there's no action we can take until there are a list of steps we can follow that reliably reproduce the problem, as per the bug report guidelines. We can't debug screenshots. Therefore closing this issue - please file again if you can identify the necessary details.
