### ISSUE TITLE
Splashscreen automatically added - causes tedious work to remove everytime

### ISSUE THREAD

**Issue by fredriksthlm** [Scirra/Construct-3-bugs#5372]
## Problem description

When exporting for iOS och Android the build always contain the Cordova Splashscreen plugin.

Regarding iOS
 Cordovas recomendations for iOS is to not include the Cordova Splashscreen at all. As far as I've understood all ios related code is now even gone from the plugin totally:
https://github.com/apache/cordova-plugin-splashscreen/pull/263

Regarding Android
Back in time there was a problem with "black screen" or delay when loading big projects on slow devices. This still might be an issue, but loading small projects on modern devices goes instantly, so the need of the splashscreen is for most people not needed.
The splashscreen also contain a very well known bug causing issues for the back-button. Also the fullscreen code runs _after_ the splashscreen so using splashscreen without amending the code in android studio is super ugly.

Normal small (fast loading) games should not really use or benefit from splashscreen at all.

Also when cordova bump to target 31 by default the app will start use the built in android12 splash functionality, so this needs to be done anyway. Otherwise people will see two splashes

## Steps to reproduce

Instead of exporting to xcode or directlt create an android build, many people now need to export as cordova and manually remove the splashscreen plugin from the config file before creating the project with CLI. It would be great to be able to chose in the export if you want to include it or not.

1. Export as cordova
2. Open config file

## Observed result

cordova-splashscreen is included in config files for both android and ios exports.

## Expected result

To be able to chose in the export if I want to include it in my project or not. (Just like Fullscreen plugin)

This should be a tickbox for this in the export window:

![image](https://user-images.githubusercontent.com/76128871/149517381-fbddd363-5747-453a-8f67-e43962266b1a.png)

It's fine that this tick-box is Defeult=Yes, then everyone that is used to have it won't be affected.

## More details

To add this setting in the export would help a lot and also minimize the risk intead of people amending the files manually every single export. 

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I don't think we can just drop support for splash screens on Android. I'm sure there's still people out there relying on them, especially with slower and older devices that display them for a few seconds. We also need the plugin (at least on Android) to customise the splash screen: by default it will show a built-in spinner over the splash screen and automatically hide the splash after a timeout, whereas for Construct the spinner is hidden and the splash is hidden when the Construct-displayed loader is ready to be shown (which can in turn be customised in Construct, e.g. with a loader layout). So I don't think this is a bug: it's a feature that a number of users likely still rely on so it cannot just be "fixed" by removing it.

Adding an extra option for this is a feature request, so please submit here instead: https://construct3-21h2.ideas.aha.io/
