### ISSUE TITLE
Flipping / Mirroring / Rotating Tile in layout editor offsets it from mouse

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#5374]
## Problem description

(In the layout editor while placing tiles on a tilemap object) If you flip, mirror, or rotate the tile it offsets it from the mouse. The tile position is only reset when the mouse moves. Note the direction the tile is offset seems to depend on the size of the tilemap object. In the attached .c3p it move to the left instead of up/left.
![TheGif](https://user-images.githubusercontent.com/36490901/149643039-6cb057c5-e83d-4437-9797-960b772e1f7c.gif)

## Attach a .c3p

[tilemap flip bug.zip](https://github.com/Scirra/Construct-3-bugs/files/7876167/tilemap.flip.bug.zip)

## Steps to reproduce

1. Click the tilemap object in the layout view.
2. Select a tile from the tilemap bar.
3. Move the mouse over the tilemap as if you were about to place the tile.
4. Use X, Y, or Z to mirror, flip, or rotate the tile.

## Observed result

The tile shifts itself away from the mouse with each mirror / flip / rotation, and only returns to the mouse when the mouse moves.

## Expected result

The tile to stay in place.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** I think this started happening a few weeks ago but I haven't used tilemaps much lately and ignored it. Currently happening in r276.2 beta

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 97.0.4692.71
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
C3 release: r278.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 190 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1123)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta, was a regression introduced in r261.
