### ISSUE TITLE
Canvas Paste bug with effects

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#5375]
## Attach a .c3p

[canvasbug.zip](https://github.com/Scirra/Construct-3-bugs/files/7877645/canvasbug.zip)

## Steps to reproduce

1. preview

## Observed result

![1](https://user-images.githubusercontent.com/54614906/149672995-2fde5f7c-58a9-4801-848e-1079067f93e5.png)

## Expected result

![2](https://user-images.githubusercontent.com/54614906/149672989-6c7eb210-510c-4d7f-92c9-29d781cef06a.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It looks correct for me in r278.2. Without all the required details it cannot be investigated further, so closing.

**Comment by CrackHub** [comment]
Sorry but you can see difference i was used different versions. Why this happening in latest beta? I just open project without changing anything.
![compare](https://user-images.githubusercontent.com/54614906/149768375-826ce9f5-f3c1-458c-9f13-f25993cd005a.png)

**Comment by AshleyScirra** [comment]
It looks fine to me, as shown below, in r278.2. Please always follow the full bug report guidelines. They're there to make sure we can help you, and if you skip on lots of the key details then we end up unable to help you. Issues are often much more complicated than they might seem to you.

![issue5375](https://user-images.githubusercontent.com/768723/149769099-dcb4668a-693f-4924-84be-9bdd24ee52a0.png)
