### ISSUE TITLE
Canvas Paste [enhancement]

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#5376]
## Problem description

There is anyway to detect, pasting object process when done? I don't see anything. I used wait 0 (one tick) it doesn't work. It is need more tick for pasting. It should be async so we can use "wait previous actions" and we can continue actions. It is really need for mobile devices, they have limited CPU.

## Attach a .c3p

[paste.zip](https://github.com/Scirra/Construct-3-bugs/files/7877661/paste.zip)

## Steps to reproduce

1. Preview project, pasting will fail.
2. Enable two wait 0 actions and preview it will success.

## Observed result

![image](https://user-images.githubusercontent.com/54614906/149673289-9e358ff0-a82c-4b73-8d93-97551ee94ea4.png)

## Expected result

![image](https://user-images.githubusercontent.com/54614906/149673334-307e94bd-7e03-4135-883d-7fc8cdfb1e17.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I can see how this is a problem and making the 'paste' action async so it can be used with "Wait for previous actions to complete" looks like a good solution and is easy to do, so added for next beta.
