### ISSUE TITLE
Resuming Color Tween on a 9patch Crashes Game

### ISSUE THREAD

**Issue by RorySoh** [Scirra/Construct-3-bugs#5378]
## Problem description

This actually took me a year to track down what was causing this crash. But I finally found it.
If you have a 9patch and it's tweening color, and you pause and resume the tween, it crashes the entire game.
It happens in both exports and debug.

## Attach a .c3p

[CrashingPauseResumeTweenColor.zip](https://github.com/Scirra/Construct-3-bugs/files/7880739/CrashingPauseResumeTweenColor.zip)

## Steps to reproduce

![image](https://user-images.githubusercontent.com/5456478/149745729-9faca3e4-43cf-4644-bee8-7e15c10e002c.png)

1. Tween (one property) "color" on a 9patch with the Tween behavior
2. Pause all tweens on the object
3. Resume all tweens on the object

## Observed result

The tween pauses fine.
When you try to resume it, it crashes and gives an error.

![image](https://user-images.githubusercontent.com/5456478/149745248-1ef7cf97-72d5-4bbb-bf66-3d89007ceb7b.png)

![GIF 1-17-2022 5-47-41 PM](https://user-images.githubusercontent.com/5456478/149746595-b41b22e3-0f9a-485d-b5d0-6138be55ae6e.gif)

## Expected result

The tween should pause and resume.

## More details
**Affected browsers/platforms:** Chrome, Windows (to my knowledge)

**First affected release:** This has been present for around a year at least.

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.57.1
Browser engine: Chromium
Context: nwjs
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.57.1 (like Chrome/94.0.4606.81)
C3 release: r275 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 236 gb
Storage usage (approx): 11 gb (4.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.

**Comment by RorySoh** [comment]
Thank you Diego!
