### ISSUE TITLE
Pointerlock second is button down only works if mouse is moved.

### ISSUE THREAD

**Issue by j0schi** [Scirra/Construct-3-bugs#5381]
## Problem description

When pointerlock is active and there are 2 events eg. left button is down and right button is down it only registers  the first mouse button that is down, till the mouse is moved, then the second button down triggers.

## Attach a .c3p

https://drive.bytecrunch.org/index.php/s/2NBFqmNxbRt2KPx

## Steps to reproduce

1. After starting the layout click once for pointer lock
2. Hold one mouse button down
3. Hold second mouse button down WITHOUT moving the mouse.
4. As you can see the second hold down does not trigger
5. Move the mouse slightly
6. Second is down is now triggered

## Observed result

The second button is down does not trigger

## Expected result

The second button is down should trigger without moving the mouse

## More details
Observed with https://editor.construct.net/r278-2/ in latest Chrome on Windows 10
Observed in Webview Export 
Observed in NW.JS Export
In Firefox it works as expected! 

No Information available.

## System details

No Information available.

<details><summary>View details</summary>

No Information available.

</details>

**Comment by AshleyScirra** [comment]
This looks like a bug in Chrome. I'll make a report directly to Google soon.

**Comment by j0schi** [comment]
Thank you :) I know its a very special case but for my current project its actually somewhat relevant ;)

**Comment by AshleyScirra** [comment]
Filed an issue with Google here: https://bugs.chromium.org/p/chromium/issues/detail?id=1289683

Closing this issue as it will be followed up there.
