### ISSUE TITLE
dropdown list in the javascript code editor can't be clicked

### ISSUE THREAD

**Issue by eleanorjmorel** [Scirra/Construct-3-bugs#5383]
## Problem description
when using JavaScript in construct, if you use the autocomplete dropdown list and try to click, it closes the code editor without adding the autocomplete you clicked on or anything

## Steps to reproduce
https://youtu.be/XVEYCuCwpUs

**Comment by AshleyScirra** [comment]
It works for me. Follow the bug report guidelines with every report otherwise it's impossible for us to help.
