### ISSUE TITLE
Paste Canvas into canvas with effects

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#5385]
## Problem description

I have two project for this bug.
BUG-1: Used "Grayscale" effect on canvas
BUG-2: Used "Grayscale" effect on layer

## Attach a .c3p
[bug1.zip](https://github.com/Scirra/Construct-3-bugs/files/7914891/bug1.zip)

[bug2.zip](https://github.com/Scirra/Construct-3-bugs/files/7914892/bug2.zip)

## Steps to reproduce

1. Preview projects

## Observed result - (BUG-1)

![image](https://user-images.githubusercontent.com/54614906/150556584-bb499ad9-93d1-454a-bfff-f9122040751d.png)

## Expected result - (BUG-1)

![image](https://user-images.githubusercontent.com/54614906/150556654-f3f34eef-2ff4-49ec-a0e3-7db30fcc0cfc.png)

## Observed result - (BUG-2)

![image](https://user-images.githubusercontent.com/54614906/150556819-793717fa-642a-4cb9-9234-f91af65ce5f3.png)

## Expected result - (BUG-2)

![image](https://user-images.githubusercontent.com/54614906/150556654-f3f34eef-2ff4-49ec-a0e3-7db30fcc0cfc.png)

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r279

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 97.0.4692.99
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
C3 release: r279 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 135 gb
Storage usage (approx): 25 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1109)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The first case is indeed a bug - it looked like pasting another Drawing Canvas with effects has never worked. It was difficult but I managed to fix this for the next beta.

The second case is not a bug though. Layer effects are applied after everything else has been drawn to the layer as part of compositing layers to the display. Therefore layer effects do not affect 'Paste object'.
