### ISSUE TITLE
Construct 3 crashes every 5 minutes, renaming a function or when making a new project

### ISSUE THREAD

**Issue by DrMeepso** [Scirra/Construct-3-bugs#5386]
## Problem description

construct 3 keeps crashing with well trying to do any of the following:
renaming a function
making a new project
when it feels like it (randomly)

## Attach a .c3p

I dont believe this needs a project file as its persistence between projects

## Crash 1
1. Make a new project

## Crash 2
1. Create then rename a function

## Crash 3
1. Some times it just crashs when it feels like it

## Observed result

Crashes 

## Expected result

It doesn't crash???

## More details

**Affected browsers/platforms:** 

Chrome in a PWA

r276.2

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/, line 0, col 0
Message: ResizeObserver loop limit exceeded
Stack: null
Construct 3 version: r276.2
URL: https://editor.construct.net/
Date: Sat Jan 22 2022 10:17:04 GMT+1300 (New Zealand Daylight Time)
Uptime: 181.2 s

Platform information
Browser: Chrome
Browser version: 97.0.4692.99
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 570 Series Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13037.1003)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DrMeepso** [comment]
Is there any update because its pretty much impossible to use c3

**Comment by DiegoScirra** [comment]
I haven't been able to reproduce this one. Are there any more details you can add? Simply renaming a function doesn't seem to produce any errors.

**Comment by DiegoScirra** [comment]
A possible fix for this will be available in the next beta, but it's hard to tell if it will do anything. So you will need to try it out and tell us if it worked for you.

**Comment by AshleyScirra** [comment]
r282 is now out, please check again there.

**Comment by DrMeepso** [comment]
Yep patch seems to have worked!

**Comment by AshleyScirra** [comment]
Thanks for confirming!
