### ISSUE TITLE
Construct crashing when trying to run the preview and export

### ISSUE THREAD

**Issue by TinyCrocodileStudios** [Scirra/Construct-3-bugs#5387]
## Problem description

I am working on a project that I worked the last time a while ago. Back then, previewing my changes worked fine. Now, it crashes on:

- preview layout
- debug layout
- preview project
- export project

I am confident that this is not a problem of my project, since I also opened an old, finished project that with 100% certainty worked before (since I finished and exported it last year). And it also crashes when I try to preview the Kiwi project from your start page.

Error message see below

## Attach a .c3p

I don't think my project is to blame, but here it is anyway: https://www.dropbox.com/s/xm3dbj4gkb8ooix/waldritter-2.c3p?dl=1 

## Steps to reproduce

1. open project in chrome
2. click preview
3. observe crash

## Observed result

Construct tells me "oops, something went wrong" and prompts me to save my game and / or restart the project. (Still broken after restart though)

Error report information
Type: unhandled rejection
Reason: Event 'error': [object Event]
Construct 3 version: r276.2
URL: https://editor.construct.net/
Date: Sat Jan 22 2022 11:44:16 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 147.7 s

Platform information
Browser: Chrome
Browser version: 97.0.4692.99
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9365)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

## Expected result

Seeing the preview of the game

## More details
I think all the details should be in the error message

## System details

I think all the details should be in the error message

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It works fine for me. It's also a basic feature of the software and AFAIK nobody else is reporting a problem. So it sounds like a problem with your copy of Chrome.

I'm afraid without more information about the problem it's not possible to investigate. The crash report does not include any useful information and the steps to reproduce the problem do not work for me. It's possible that if you press F12 and check the browser console, there may be a more detailed error message there. I would also advise disabling any browser extensions you have installed in case one of them is interfering with Construct.

Unfortunately as this issue is not currently actionable, closing.
