### ISSUE TITLE
Lock selection not saved

### ISSUE THREAD

**Issue by arcadesindo** [Scirra/Construct-3-bugs#5389]
## Problem description
The objects lock selection feature on layout was didn't get save onto the system, it keeps unlocked everytime we open the project.

## Attach a .c3p

Not needed

## Steps to reproduce

1. Pick the objects
2. Lock selection
3. Save
4. Close
5. Open back the project
6. Click on the locked objects before.

## Observed result

the objects didnt get locked.

## Expected result

the objects should be locked as before

## More details

**Affected browsers/platforms:** 

**First affected release:** 
v276.2 Stable

**Comment by AshleyScirra** [comment]
@DiegoScirra - I think this should be included in UI state.

**Comment by DiegoScirra** [comment]
Added in the next beta.
