### ISSUE TITLE
Layers not being set as global on duplicated layouts

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-3-bugs#539]
## Problem description

If you duplicate a layout containing a global layer, the "Global"  Layer property for that layer on the new layout will be set to "No". 

If you then click the setting to "Yes" then back to "No" the setting will then be set to "Overridden" and any objects on the original layout will be duplicated on the new layout. 

Deleting these objects will delete them from the original global layer. 

## Attach a .c3p

No c3p needed - start from a new project.

## Steps to reproduce

1. Create a new project
2. Set Layer 0 on Layout 1 to Global = yes
3. Right click on Layout 1 in the Project window and select "Duplicate"
4. Add a new sprite object to Layout 1, Layer 0
5. Select Layout 2
6. Select Layer 0 in the Layers window for Layout 2
7. Observe that the Global setting in the Layer Properties is set to "No"
8. Set the Global setting to "Yes" and then set it back to "No" - the setting should now be "overridden"
9. A new instance of the sprite will be added to the overridden layer.
10. Delete the sprite object on Layout 2, Layer 0
11. Return to Layout 1 - the sprite has also been deleted from Layout 1, Layer 0.

## Observed result

Duplicated layouts containing global layers are not being marked as overridden.
Non-global objects on global layers are being duplicated *after* the duplicated layer is forced to overridden.
Deleting the a duplicated object on duplicated overridden layer deletes the original object on the original global layer.  

## Expected result

Global layers on duplicated layouts should be marked as overridden upon creation.
Non-global objects added to a global layer after that layout has been duplicated shouldn't be added as new instances to duplicated layouts.
Deleting objects on a duplicated layout's overridden global layer shouldn't delete the original object.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r40.

This is how it works now. When a global layer is duplicated, none of it's instances are passed over to the duplicate. Instead the duplicate is marked as "Overridden" and just displays the original's content.

Bear in mind though, that deleting instances from an overridden layer will delete them from the global source layer. This is the expected behavior, after all the overridden layer is just acting as a middle man for the global layer.

**Comment by jakemay74** [comment]
Perhaps it would be worth either automatically locking an overridden layer or adding a confirmation pop-up when deleting an object from an overridden layer so that the user is aware it will be removed from all layouts containing the global layer?

**Comment by AshleyScirra** [comment]
I don't think there's a special case here. If you don't normally see a warning when deleting an instance from an overridden layer, then you shouldn't see a warning doing that after duplicating a layout, either. It's just another route to the same situation.
