### ISSUE TITLE
Transparency bug affecting for example Layout Projections example

### ISSUE THREAD

**Issue by esowe** [Scirra/Construct-3-bugs#5391]
## Problem description
There is a bug affecting how 3D objects are drawn behind transparent objects.

That there might be issues with transparency and 3D is already described in the manual (https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/3d-shape), but the observed behaviour only affects copied 3D objects.  

## Attach a .c3p
[Layout projections.zip](https://github.com/Scirra/Construct-3-bugs/files/7920301/Layout.projections.zip)

## Steps to reproduce
1. Open the "Layout Projections" example project.
2. Select the "Main" layer.
3. Copy the tall box (UID 3).
4. Paste it somewhere close to the original box.
5. Walk the PlayerBillboard in front of the copy (UID 19). 

## Observed result
Where the transparent parts of the PlayerBillboard overlap the copied box, the GridBackground is visible through it. This doesn't happen when walking in front of the original box. Both the perspective and the orthogonal views are affected.

![TransparencyBug](https://user-images.githubusercontent.com/10393576/150675632-fec57aa9-7a41-41cd-bc4f-2b5fee4069c1.PNG)

## Expected result
There should be no difference between how the copy and the original boxes are drawn. Preferrably of course, the GridBackground should not be visible through any box, but at least the behaviour should be consistent.

## More details

**Affected browsers/platforms:**
Only tested on Chrome 97.0.4692.71 on Windows.

**First affected release:**
Unknown, only tested on R279,

## System details
Platform information
Browser: Chrome
Browser version: 97.0.4692.71
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
C3 release: r279 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 224 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9171)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
This is just another variant of the transparency issues already documented. Notice the 3D shape where the issue happens has a higher Z index than the player. Therefore it is drawn *after* the player, by which time the transparent parts of the player image have already filled in the depth buffer.

The same advice as before applies: transparent objects must be drawn after everything else, in back-to-front order. The best way to do this is add an extra layer above and put the player on that, which solves the problem. The only reason the example project does not do that is it already uses 2 layers and is designed to stay within the free edition limits.
