### ISSUE TITLE
Issue with 3D transparency + Fogexponential effect

### ISSUE THREAD

**Issue by bobatealee** [Scirra/Construct-3-bugs#5393]
## Problem description

On a layer that has the Fogexponential effect, viewing a transparent 3D object through another transparency 3D object will reset the fog value of the back 3D object to the front 3D object's fog value.

## Attach a .c3p

[transparentfog.zip](https://github.com/Scirra/Construct-3-bugs/files/7921688/transparentfog.zip)

## Steps to reproduce

1. Walk with WASD and use the mouse to look around
2. Look at a fence while behind another fence

## Observed result

The back fence will inherit the fog value of the front fence.

## Expected result

The back fence should retain its fog value while the front fence has its own.

## More details

**Affected browsers/platforms:** Chrome, Firefox, most likely a platform-wide issue

**First affected release:** r276.2

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 96.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0
C3 release: r276.2 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 17 mb (0.9%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9709)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is another variant of the case of transparency - and fog, which has the same problem for the same reason - being tricky in 3D. See also issue #5391 where I just explained a very similar problem. All transparent objects must be drawn on their own layer above everything else and in back-to-front order to render correctly. However this gets trickier when using fog, as the effect is applied afterwards, and transparent portions of images will have filled in the depth buffer and cause the same amount of fog as if they were opaque. Therefore, you cannot use the fog effect on an entire layer if that layer has transparent content: there is only one depth buffer, and the effect will be applied once afterwards.

The solution is to remove the fog effect from the transparency layer, and then add the fog effect to the fence objects instead. This means each fence draws its own fog independently in camera distance draw order, rather than once after all content is drawn, allowing each fence to have its own fog level which can be overlaid by other fences with different fog levels.

**Comment by alastajj** [comment]
@AshleyScirra could be worth doing a manual entry on this topic, if it's not already! thanks for explaining here at least

**Comment by alastajj** [comment]
I fixed the Foggy example by putting all the transparent billboards in a family with the fog effect, and removed the fog effect from the billboard layer.

![image](https://user-images.githubusercontent.com/5744908/151109518-9c391221-6f80-4a92-8d9d-6ecc20b33fa3.png)

**Comment by AshleyScirra** [comment]
@alastajj - good idea, I updated the [Using 3D in Construct](https://www.construct.net/en/tutorials/using-3d-construct-2746) tutorial with a section on "Transparency and fog".

**Comment by comitodedito** [comment]
watch out @bobatealee is paededo from tf2c who wants kids naked
![re](https://user-images.githubusercontent.com/107486488/173593746-0299d5dc-c44d-47be-9abc-5ad15eb938bc.png)
