### ISSUE TITLE
Preload Sounds causes freeze at loading on Firefox

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5395]
## Problem description

For some reason, preloading audio started to fail. Before, it was failing inconsistently after uploading to itch.io, but now it doesn't even run a preview (stuck at "Made by C3" screen).
Update: Trying to preview the audio causes an "unhandled rejection" and crashes the editor.

## Attach a .c3p

[New project(1).zip](https://github.com/Scirra/Construct-3-bugs/files/7926996/New.project.1.zip)
(any audio attached with the project cannot be used in any other way than testing this project.)

## Steps to reproduce

1. Run on Firefox.
2. Run after disabling Preload Audio.
3. Run after deleting all sound files (but not the music).

4. Double click the sound file "correct.webm".
5. Click play
6. Click close

## Observed result

Result of 1: stuck at Loading.
Result of 2,3: game opens.
Result of 5: doesn't play.
Result of 6: crash.

## Expected result

game runs correctly in all cases.

## More details

**Affected browsers/platforms:** Firefox 96.0.2 Win7 64-bit

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information

Type: unhandled rejection
Reason: Error: The fetching process for the media resource was aborted by the user agent at the user's request.
Construct 3 version: r276.2
URL: https://editor.construct.net/
Date: Mon Jan 24 2022 18:54:32 GMT+0200 (GMT+02:00)
Uptime: 79.3 s
Platform information

Browser: Firefox
Browser version: 96.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0
C3 release: r276.2 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (GeForce GTX 480 Direct3D11 vs_5_0 ps_5_0, D3D11-23.21.13.9135)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
All steps work fine for me in Firefox 96 with r279. Can you find reliable steps to reproduce in the latest release? Do you have any browser extensions installed that are causing the problem? (Try removing any browser extensions and see if the problem goes away)

**Comment by AshleyScirra** [comment]
I'm afraid without more details there is nothing we can do, so closing.
