### ISSUE TITLE
r280 beta start screen looks small on 4k

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#5398]
## Problem description

On 4k resolution the new start screen looks a bit small and it honestly makes me zoom in on that part of Construct to 125-150%

This is at 100%:

![image](https://user-images.githubusercontent.com/7268697/151073906-c16fedfd-4727-4716-aa12-649d0a54c9be.png)

**Affected browsers/platforms:** Chrome

**First affected release:** r280 beta

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 97.0.4692.99
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.375
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
C3 release: r280 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 1006 gb
Storage usage (approx): 165 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm on a 4K display and the display scale is 200%, so it looks like this - i.e. a perfectly reasonable scale:

![startpage-4k](https://user-images.githubusercontent.com/768723/151189588-08be3b11-cf8f-4a5f-bf77-d0d343c264fe.png)

Your display scale appears to be 137.5%, which seems to be very low for such a high resolution display. Is it a physically very large display? Or do you just like the text to be really small?

Paulo's design imposes a maximum size for the Start Page presumably to avoid it resizing to absurdly large sizes if you give it more and more space. In theory the size you showed should be reasonable assuming the display scale is reasonable for the resolution.

**Comment by JeFawk** [comment]
We have 32 inch displays with the current system dpi increase:
![image](https://user-images.githubusercontent.com/7268697/151190282-0eb273ff-6bf9-4cad-895f-1e01ff39c571.png)

![image](https://user-images.githubusercontent.com/7268697/151191356-757e7745-bc71-4b4f-9f9a-653035b437bd.png)

Just seems like there is a lot of empty space around and the font is quite small (for me in particular) but it's not a big deal since we dont spend much time there.
