### ISSUE TITLE
Animations Editor doesn't remember last tool

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#540]
## Problem description

The last tool isn't remembered when opening the animations editor.

## Steps to reproduce

1. Create sprite
2. Select a color and paint bucket tool
3. Click to fill image with solid color
4. Close, create another new sprite
5. Click to fill image with solid color again

## Observed result

No tool is selected so nothing happens

## Expected result

The last tool (paint bucket) should still be selected. This makes it quicker to mock up several dummy sprites for testing.

**Comment by DiegoScirra** [comment]
Fixed in r40
