### ISSUE TITLE
Whitelist  - Update GameAnalytics plugin

### ISSUE THREAD

**Issue by the1schwartz** [Scirra/Construct-3-bugs#5400]
Hi, would you please update a Cordova plugin for me:
`cordova-plugin-gameanalytics@4.2.5`

Thanks a lot.

**Comment by AshleyScirra** [comment]
Added to build service.

**Comment by the1schwartz** [comment]
I get this error when trying to export to a apk but when I export for cordova project and build for android it works fine no problem getting cordova-plugin-gameanalytics@4.2.5. Am I doing something wrong?

```
Discovered plugin "cordova-plugin-gameanalytics". Adding it to the project
Failed to restore plugin "cordova-plugin-gameanalytics". You might need to try adding it again. Error: CordovaError: Failed to fetch plugin cordova-plugin-gameanalytics@4.2.5 via registry.

CordovaError: Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cordova-plugin-gameanalytics@4.2.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

CordovaError: Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cordova-plugin-gameanalytics@4.2.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

```

**Comment by AshleyScirra** [comment]
I double-checked and it's been allowed on the build service. I'm afraid I can't help with any build issues in third-party Cordova plugins - you should ask the plugin developer for any help.

**Comment by the1schwartz** [comment]
Ok thanks, I am the plugin developer. The plugin is fetched correctly if I export as a cordova project and build with cordova command line. I am not sure if it could some environment settings on build server that could cause any issues getting the new version of the plugin. If not then I am not how I can test if it works on using your build server :/

**Comment by AshleyScirra** [comment]
The build server just runs Cordova CLI commands on it. It should work the same as running locally. I'm afraid I don't know what else to tell you.

**Comment by the1schwartz** [comment]
OK no worries

**Comment by AshleyScirra** [comment]
@the1schwartz - I was doing some other routine maintenance and came across the same error you mentioned for another plugin. It turns out the npm cache was corrupt on the build server. It took ages to figure that out! I've now cleared the cache so if you try again, you may find your plugin is working now.
