### ISSUE TITLE
No preview on iOS

### ISSUE THREAD

**Issue by scottybme** [Scirra/Construct-3-bugs#5403]
## Problem description: Beta versions after 275 will not preview in iOS on iPad or iPhone.
It occurs on iOS versions 14 or 15 .
I have duplicated it on multiple devices , and all work as they should when using  the stable release 276

I have not added a .c3p as any sample project from launch page will duplicate problem regardless of size or type.
## Steps to reproduce: Load any project (any sample will duplicate issue ) on iOS device with beta after 275 and the load screen hangs(never loads)

1.open any project on iOS device with beta after 275
2.run local preview ,start screen displays but project  never loads or runs
3.problem occurs even if you are using construct on windows or macintosh OS and use remote preview on iPad or iPhone

## More details

I have duplicated this running construct 3 on   Windows and Macintosh ,using  remote preview and opening in iPhone or iPad running iOS 14  and 15.
It happens in all browsers 
**Affected browsers/platforms:** 

Latest Stable release 276 works as it should and beta 275.
Every beta after 275 fails to load preview.
**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

Scotts ipad pro
15.2.1
iPad Pro (12.9-inch) (5th generation)
 I have also duplicated on iPad Air running 14.2
</details>

**Comment by programmer861** [comment]
+++ even the animation does not work for me on ios and the preliminary prompt. It's been a mistake for three months now.

**Comment by AshleyScirra** [comment]
This looks like some bizarre bug in Safari. It is throwing a JavaScript error complaining a variable is undefined, but the variable definitely is defined, and it works in all other browsers.

I've made some changes for the next beta to try to work around it, so I'll check again when it's out.

**Comment by AshleyScirra** [comment]
r282 is now out and it looks like it's working for me there.

**Comment by scottybme** [comment]
I see that you closed #5403 however you will find remote preview is still not working when construct 3 is running on windows ,macintosh or iOS and the preview is attempted to be opened on iOS by using the QR code.

**Comment by scottybme** [comment]
Also found on screen keyboard is not working for any text input, including signing on to account in beta

**Comment by AshleyScirra** [comment]
The originally described issue appears to be fixed. If something else is wrong, please file a new issue.

**Comment by AshleyScirra** [comment]
Wait, I got confused. I can see the same problem happening in Remote Preview. Ugh, it's a real nightmare Safari bug. That should be fixed for the next beta too.

**Comment by scottybme** [comment]
The other thing I referred to is that text Input is not working in iOS.
On screen keyboard dose not display in editor.
You can’t even log into your account.
I will issue another bug report if you would like, but it’s very obvious problem.
Thanks for your hard work🙂

**Comment by AshleyScirra** [comment]
@scottybme - keyboard input seems to be working fine for me in the editor on iOS. As ever if you have any other problems please file a new issue following all the guidelines, as we need all that information to be able to help.
