### ISSUE TITLE
Image points doesn't work correctly

### ISSUE THREAD

**Issue by Stand43** [Scirra/Construct-3-bugs#5407]
## Problem description

Image points move from their intended positions when object collide with layout edge using "Bound in Layout" behavior.

## Attach a .c3p
[ImagePointsBug.zip](https://github.com/Scirra/Construct-3-bugs/files/7970818/ImagePointsBug.zip)

## Steps to reproduce

1. Create a sprite object with 8-direction movement and Bound in Layout behaviors
2. Set speed properties to higher values
3. Create second sprite object
4. Add action for second object in event sheet to set it to position of first object's "Origin" point
5. Launch the game

## Observed result

When you collide with an edge of a layout, second object for some reason moves further than it suppose to. It seems like first object's points behave incorrectly

## Expected result

Second object stays in place relatively to the first object

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 96.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.3636363636363635
Logical CPU cores: 16
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0
C3 release: r276.2 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 1.2 gb
Storage usage (approx): 20 mb (1.6%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1123)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

## :(
i dont like it and i am sad

**Comment by AshleyScirra** [comment]
It's not a bug, just the order things run in:

1) 8 direction will move the object forwards a bit
2) The events will position an object on top of it
3) Then the bound behavior will move the object back (but not the one that was positioned on top of it)
4) Then the screen is drawn. The object positioned on top is left in a different position.

Either use events to bound the position so that can be sequenced properly with other events, or use the scene graph feature ("add child" action) for positioning, which means the object positioned on top will always automatically update whenever the thing it is attached to moves.

**Comment by Stand43** [comment]
That is very strange... In my example I am setting second object's coordinates to be ALWAYS the same as "Origin" point of first object, but it does not stay in those coordinates visually, when first object collides with an edge of layout. That means that for some reason image of an object stops, but it's point are not. When I create new object in that point there is the same problem that point is shifted from its place. What is the point of these image points, when they does not stay in the same place all the time???

**Comment by AshleyScirra** [comment]
They do stay in the place all the time. The sequence I described above is what happens during a frame, causing objects to end up in different places. As I said using the scene graph feature will also avoid this, as it means objects always move with their parent, rather than ending up with synchronisation issues like this depending on when your 'Set position' action runs.

**Comment by Stand43** [comment]
ok, understood, thanks, but it is very unintuitive and not user friendly at all:(
