### ISSUE TITLE
My project doesn't open in r280

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#5409]
Error report information
Type: unhandled rejection
Reason: Error: e.Ga is not a function @ TypeError: e.Ga is not a function at Function.JKb (https://editor.construct.net/r280/projectResources.js:1234:349) at window.eza.Udb (https://editor.construct.net/r280/projectResources.js:1243:43) at window.eza.Ga (https://editor.construct.net/r280/projectResources.js:1244:308) at d.Ga (https://editor.construct.net/r280/projectResources.js:1221:115) at Object.BE (https://editor.construct.net/r280/projectResources.js:1222:403) at Pca (https://editor.construct.net/r280/main.js:219:293) at Nca (https://editor.construct.net/r280/main.js:219:68)
Stack: TypeError: e.Ga is not a function at Function.JKb (https://editor.construct.net/r280/projectResources.js:1234:349) at window.eza.Udb (https://editor.construct.net/r280/projectResources.js:1243:43) at window.eza.Ga (https://editor.construct.net/r280/projectResources.js:1244:308) at d.Ga (https://editor.construct.net/r280/projectResources.js:1221:115) at Object.BE (https://editor.construct.net/r280/projectResources.js:1222:403) at Pca (https://editor.construct.net/r280/main.js:219:293) at Nca (https://editor.construct.net/r280/main.js:219:68)
Construct 3 version: r280
URL: https://editor.construct.net/r280/
Date: Mon Jan 31 2022 22:32:42 GMT+0300 (Москва, стандартное время)
Uptime: 209.7 s

Platform information
Browser: Chrome
Browser version: 97.0.4692.99
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
C3 release: r280 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 710M Direct3D11 vs_5_0 ps_5_0, D3D11-23.21.13.8871)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it is impossible for us to help.
