### ISSUE TITLE
Undo/Redo doesn't work anymore in parameters

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#541]
## Problem description

Undo/Redo doesn't work anymore in parameters.
It seems that it worked before but not since CTRL key adjustments.

## Steps to reproduce

1. In a event sheet, edit an action with parameters
2. Edit text parameters and use CTRL+Z and CTRL+Y

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Duplicate of #93

**Comment by sebastien-c3** [comment]
Thanks Ashley, sorry for the duplicate.
