### ISSUE TITLE
UI state sometimes corrupt on first load

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#542]
## Problem description

The UI state on first load appears to have a race condition, and can sometimes crash or load the wrong UI layout.

## Steps to reproduce

1. Open a new incognito window and load C3
2. Repeat several times

## Observed result

One of three cases happens each time:

1. The editor loads normally
2. The editor loads with all the bars docked to the left, which is the wrong initial layout
3. It crashes while loading

<details><summary>Crash report for case 3</summary>
Stack: TypeError: Cannot read property 'ǃ$$x' of null at ǃ$.ǃY.ǃU.ǃ$EJ.ǃCg (https://editor.construct.net/r39/main.js:2:360737) at x.ǃEH (https://editor.construct.net/r39/main.js:2:384638) at window.ǃsU.ǃEc (https://editor.construct.net/r39/components/bars/layersBar/layersBar.js:1:1725) at window.ǃsU.ǃEG (https://editor.construct.net/r39/components/bars/layersBar/layersBar.js:1:1847) at ǃ$.ǃ$I.addEventListener (https://editor.construct.net/r39/components/bars/layersBar/layersBar.js:1:6877) at Object.d.push.ǃ$.ǃhS [as ǃESK] (https://editor.construct.net/r39/main.js:2:254796) at n (https://editor.construct.net/r39/main.js:2:257155) at t (https://editor.construct.net/r39/main.js:2:256941)
Construct 3 version: r39
</details>

## Expected result

The editor should load normally every time.

This is potentially a serious issue if new users may see a crash on first run, or the wrong initial layout.

**Comment by shortercode** [comment]
It shouldn't crash on first load, as it uses the original layout mode and bypasses the state restoration. Incognito mode will actually allow you to save state until the tab is closed, also allows you to request persistent storage... not sure why though!

Not sure what's up but I'll try taking a look.

**Comment by AshleyScirra** [comment]
I'm closing and reopening an incognito tab every time so it seems it is crashing from empty state.

Just thought this may be due to racing with Diego's code to hide the UI bars when the start page is shown - you might want to collaborate with him to figure out what's going on there.

**Comment by shortercode** [comment]
Yeah I've been trying that, seems pretty tough to pin down... I'm not sure if it's related to diegos code, I think it's coming in earlier than that. The crash seems to only happen on first run, when the restoration code doesn't kick in and it defaults to the original layout system.

**Comment by AshleyScirra** [comment]
This even seems to happen sometimes after clicking "Reset layout". Guess it's the same case though, just not handling missing UI data.

**Comment by shortercode** [comment]
Have you been able to replicate this in development yet? I can only seem to trigger it using the live r39, but the minification is making it hard to track down the trouble code.

Closest I've got is noting that part of the docking code tries to set the height of the layers bar but it doesn't have a layout for some reason. Which causes it to fail getting it's maximum height

**Comment by shortercode** [comment]
Think we can close this one now, with the changes to initial layout it shouldn't be a problem anymore... Hopefully!
