### ISSUE TITLE
Undo script bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5420]
## Problem description

Incorrect work of undo and redo.

## Attach a .c3p

[undo_script_bug_r276s.zip](https://github.com/WilsonPercival/WilsonPercival/files/7713639/undo_script_bug_r276s.zip)

## Steps to reproduce

1. Create a new project.
2. Add a new script - main.js will be added automatically.
3. Add a line "const hello".
4. Click Undo twice.
5. Click Redo.

## Observed result

We can't click Redo the second time. Everything in main.js has vanished without a trace.

![ghh](https://user-images.githubusercontent.com/91274932/146050735-e87dab6c-9172-474f-8f6e-0baf15c261d6.gif)

## Expected result

After first Redo we are able to click Redo again - to get everything to the previous state.

## More details

This bug doesn't happen if before first Undo you close main.js.

![ghh2](https://user-images.githubusercontent.com/91274932/146051332-32dd5d9d-f642-4fab-a86a-c3906a335140.gif)

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r276s

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 95.0.4638.54
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
C3 release: r276 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 254 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll-10.18.10.4653)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
In the current design of the editor, the text editors such as used for script editors have their own undo/redo stack. Closing the text editor then discards the text editing undo stack, and replaces all edits with a single "change script" undo point. I did some digging around the source code and it seems this design also in part derives from issue #1601, filed back in 2018, which deals with some complicated-looking edge cases involving undo in the text editors. This isn't ideal in this case, as the first undo is basically deleted by the second undo that removes the entire script file. However changing this would probably be complicated and risk re-introducing some old and difficult bugs in the undo stack, and the issue seems pretty minor, so closing as wontfix.
