### ISSUE TITLE
Buttons disappear in full screen mode

### ISSUE THREAD

**Issue by sebastien-c3** [Scirra/Construct-3-bugs#543]
## Problem description

Buttons disappear when requesting full screen mode (reappear when cancel it).

## Attach a .c3p

[bug-fullscreen-button.zip](https://github.com/Scirra/Construct-3-bugs/files/1090652/bug-fullscreen-button.zip)

## Steps to reproduce

1. Preview the c3p file project
2. Click the FULLSCREEN button

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r45.
