### ISSUE TITLE
image editor doing image blur while increasing or decreasing size only 1px

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#545]
## Problem description

*i am inserting a photo into layout image quality is good
but if i do any change in size even only 1 pixel change, its doing blur image
i have attached screenshot with different results when i increase size by 1 pixel and when i decrease size by 1 pixel and a expecting result is also included *

## Attach a .c3p

*![image issue](https://user-images.githubusercontent.com/17684135/27420917-a69825b6-5745-11e7-9765-919161b7eab9.jpg)*

## Steps to reproduce

1. insert any image
2. increase size or decrease size only 1 pixel
3. 

## Observed result

*blurry image*

## Expected result

*clean*

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
I did some work on this and the changes will be available in r41.

I think it is better now, but the the problem with this kind of issues is that they are quite subjective. Try the resizing in the next release and let me know if it is any better.

**Comment by AshleyScirra** [comment]
r41 is out now, please check again!

**Comment by luckyrawatlucky** [comment]
I have checked and Now it is perfect

**Comment by AshleyScirra** [comment]
Great, thanks for confirming!
