### ISSUE TITLE
Find All Used Addons Crash

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#5468]
## Problem description

Trying to use find all references in the box for viewing used addons in your project always crashes C3.

## Attach a .c3p

[Findplugininstancescrash.zip](https://github.com/Scirra/Construct-3-bugs/files/7999839/Findplugininstancescrash.zip)

## Steps to reproduce

1. View the project's used addons
2. Right click on an entry and pick "Find all references..."

## Observed result

C3 crashes.

## Expected result

It used to work fine like any other place you use that command.

## More details

**Affected browsers/platforms:** Chrome, but Firefox and NWjs work

**First affected release:** r281

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: d.nv.G is not a function @ TypeError: d.nv.G is not a function at Vhb (https://editor.construct.net/r281/components/bars/findReferencesBar/findReferencesBar.js:1:230)
Stack: TypeError: d.nv.G is not a function at Vhb (https://editor.construct.net/r281/components/bars/findReferencesBar/findReferencesBar.js:1:230)
Construct 3 version: r281
URL: https://editor.construct.net/r281/
Date: Thu Feb 03 2022 21:30:01 GMT-0600 (Central Standard Time)
Uptime: 28.6 s

Platform information
Browser: Chrome
Browser version: 97.0.4692.99
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
C3 release: r281 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 1030 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1165)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
This is a duplicate of #5405, and as I said there, it works fine for me.

There must be something different about your setup - perhaps a system or browser setting or something changed in Construct's setting - that causes this. Does it reproduce in a private browsing window for you? Can you find any settings or configuration that the issue correlates with? It's difficult to do anything about this at all until we identify what is really causing it.

**Comment by corlenbelspar** [comment]
It does work as intended when I open Construct 3 in an incognito tab. Is there something I can do with this that will pinpoint it further?

**Comment by elle-trudgett** [comment]
> It does work as intended when I open Construct 3 in an incognito window. Is there something I can do with this that will pinpoint it further?

That would indicate there is an extension that is causing the issue- try reintroducing some extensions (you can enable them in incognito mode from the Extensions settings menu) until you find the bug again, and you can then narrow down which extension is causing the issue.

**Comment by corlenbelspar** [comment]
The first thing I tried was the 3D shape object, and bingo, it crashed.

**Comment by corlenbelspar** [comment]
[Findplugininstancescrashadditionalinfo.zip](https://github.com/Scirra/Construct-3-bugs/files/8007352/Findplugininstancescrashadditionalinfo.zip)

Here's the project updated to reflect my findings if it's of any help.

**Comment by corlenbelspar** [comment]
I finally tried just resetting Chrome to default setting and that seems to have fixed it. So I'm not sure what I botched up that badly. Here's to hoping it fixes other minor issues I was having.

**Comment by AshleyScirra** [comment]
FWIW I tried your last project attachment in r281 and did "find all references" on the 3D shape, and it worked fine.

**Comment by corlenbelspar** [comment]
Yeah I'm not sure what was going on, but thanks for double checking.
