### ISSUE TITLE
Rewarded Video Ad gets auto-cancelled every 2nd time the user chooses to see an ad

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-3-bugs#5469]
## Problem description

When the user clicks a button to see an ad which is loaded in, the ad appears as expected. When the user then watches the whole ad OR cancels it, everything is as expected. BUT the second time the user clicks on the "show ad" button, no new ad appears but the "on rewarded cancelled" signal triggers again. This happens after every time the user sees an ad.
After this, the ad works again, but after that the bahaviour is as explained again (it repeats itself)

This happens every time the user cancels a rewarded video ad. That is quite annoying, because for the user it appears that the ad isn't working properly (as it isn't) because after cancelling pressing the button to watch an ad once does nothing! 

## Attach a .c3p

[RewardedCancelNotWorking2ndTime.zip](https://github.com/Scirra/Construct-3-bugs/files/8006802/RewardedCancelNotWorking2ndTime.zip)

## Steps to reproduce

1. Load a rewarded video ad
2. Show it
3. Cancel it or watch till the end and close it, then load a new one
4. Show it again
-> cancelled gets triggered again, doesnt show ad
5. Show it again (a 2nd time) -> works

## Observed result

When pressing the button to watch an ad after cancelling one, no ad appears and cancel signal gets triggered again

https://user-images.githubusercontent.com/80539587/152640425-01bf69f9-ab8b-4fa5-96c5-8d3d83dc51d1.mp4

## Expected result

New ad should appear!

## More details
Currently using r.276.2
## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 92.0.4515.131
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 105 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.13023.4001)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by DiegoScirra** [comment]
When trying ads in preview, the [new web ads](https://www.construct.net/en/forum/construct-3/general-discussion-7/introducing-web-adverts-r269-164580) are used because in preview the game behaves like an HTML5 export.

Because it's preview you are only seeing test ads, which in turn also simulate frequency capping. This means the system alternates between showing a place holder for an ad that works and doing what would happen if the request for an ad was rejected.

When using real ads, requests will only be frequency capped if the ad server decides you are making too many requests.

**Comment by therealPaulPlay** [comment]
Thanks for the detailed explanation and your efforts!

**Comment by therealPaulPlay** [comment]
Quick question: Why does it then trigger „cancelled“ instead of „failed to load“?

**Comment by therealPaulPlay** [comment]
Thanks for your reply, so basically I do not have to worry about this for a mobile game, it is just working differently in preview/html export because it uses a different ad system from google, if I understand correctly.
Keep up the good work, there is so much new stuff introduced in each construct update, it‘s amazing to see the engine develop this quickly!
