### ISSUE TITLE
xcode export does not work - app freezes in c3 splash screen (re-opened issue 519)

### ISSUE THREAD

**Issue by driesdriessen** [Scirra/Construct-3-bugs#547]
## Problem description
app exported to IOS (Cordova) and built via xcode does not work. The app freezes during the c3 load screen with progress bar at 70%

This problem was planned to be solved in R40 (issue 519) but the problem is still there. 

(I'm not sure if I can re-open a closed issue, so instead I have created this new one.)

## Attach a .c3p
CP3 file (zipped):
[Uploading test xcode build.c3p.zip…]()

Screenshot:
![schermafbeelding 2017-06-22 om 23 01 41](https://user-images.githubusercontent.com/9109682/27455795-d3bbc6d4-579e-11e7-89e0-3c05fe5d7ef3.png)

Exported xcode workspace:
[test xcode build.cordova.zip](https://github.com/Scirra/Construct-3-bugs/files/1096175/test.xcode.build.cordova.zip)

## Steps to reproduce

1. Export to iOS (Cordova)
2. Open the workspace in xcode
3. start the simulator

## Observed result
The app starts, the C3 splash creen shows, the progress bar grows to about 70% and then it stops.

*What do you see happen?*

## Expected result

Progress bar completes and the main app starts

## Affected browsers

n.a.

## System details

IOS 10.11.6
xcode 8.2.1

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r40

Local storage
Storage quota (approx): 6.8 gb
Storage usage (approx): 218 mb (3.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 5000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
@driesdriessen I don't think the upload of you project file completed, the link doesn't point anywhere.

**Comment by driesdriessen** [comment]
Hi Ian,
Here is the ZIP file with the C3 project. Not sure what went wrong earlier. Hopefully it works this time.
[test xcode build.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1097812/test.xcode.build.c3p.zip)
Dries.

**Comment by shortercode** [comment]
Thanks for the reupload, I've managed to debug the issue in the mean time though.

Silly mistake on my part when I was tidying up the patch, a `value > 0` that should have been `value > 1`. Thanks for catching it. Would you like me to upload the fixed runtime file for you so you can just drop it into your project? Saves you having to wait until r41 is released.

**Comment by shortercode** [comment]
I've committed the patch for r41 but it won't likely be released until Monday/Tuesday.

This is the file that needs changing in the runtime. I had to change the extension to `.txt` for github to allow me to upload it, it should be `.js`. You should be able to find the file in your exported projects `www` directory, you can just replace the existing file with the new one. The change is on line 28 if your curious.

[opusDecoder.txt](https://github.com/Scirra/Construct-3-bugs/files/1097932/opusDecoder.txt)

**Comment by driesdriessen** [comment]
Thanks for the quick response, and for the workaround!

**Comment by shortercode** [comment]
Did the workaround fix the issue for you? Sorry that this patch required a second release. The audio decoder is proving to be a real pain point for me... I'm actually due to try overhaul it sometime soon to try and improve performance, not really looking forward to it.

**Comment by driesdriessen** [comment]
Hi,
The app launches fine now. Thanks. Audio plays. 

It appears that the Vibrate command from the Browser object does not work. I'll raise a separate issue for that. (I need it because I am developing an app for visually impaired people that depends on tactile feedback)

Thanks for your support,

Dries.
