### ISSUE TITLE
Using Audio "Fade volume" and "Set master volume" at the same time results in unexpected behavior

### ISSUE THREAD

**Issue by elle-trudgett** [Scirra/Construct-3-bugs#5470]
## Problem description

In certain situations, when using the "Fade" action to slide the volume of an audio, at the same time as changing the master volume in other events, the audio can play at unexpected volumes.

## Attach a .c3p

1. [fade_issue.zip](https://github.com/Scirra/Construct-3-bugs/files/8006932/fade_issue.zip)

## Steps to reproduce

1. Run the project
2. Wait 3 seconds
3. See that the master volume and the sample volume should both be 0 dB but there is no audio

## Observed result

No audible music is playing.

## Expected result

Music should fade in towards full volume by 3 seconds, because both the sample and the master volume should be 0 dB.

## More details

Unsure on the specific values that cause this issue to happen, but changing the master volume during a fade can either have the audio stop fading or get overridden to the master volume value ([this](https://github.com/Scirra/Construct-3-bugs/files/8006953/fade_issue_2.zip) project shows the latter case.)

**Affected browsers/platforms:** 

Tested in Chrome 97.0.4692.99 (64-bit) and Firefox 96.0.3 (64-bit)

**First affected release:** 

Broken as of r276.2 stable, still broken in r281 beta

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 97.0.4692.99
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 90 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6079)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The current implementation of master volume works by changing the volume of all audio sources, and changing the volume of an audio source will cancel any fades it is running. I can see how this is inconvenient and implementing the master volume as a final gain node at the end of the audio graph fixes this and makes a lot more sense anyway. However we're close to a scheduled stable release and I'm concerned about the backwards compatibility of this change, especially since it moves applying the master volume from before effect processing to after, which might be noticeable in some circumstances. Therefore this change will be made for the next release cycle to maximise the testing period. This means it will be available in the first beta release after the next stable release.
