### ISSUE TITLE
NWjs Version 60 Missing As Option

### ISSUE THREAD

**Issue by hammanneric6** [Scirra/Construct-3-bugs#5475]
## Problem description

As the title says, unless its just my computer, which I guess could be the problem, version 60 of NWjs isn't an option in the NWjs listings.  This is only a problem because the current Greenworks plugin works off of version 60.

## Attach a .c3p

I could make a capx but I don't think its relevant here.  If needed though I'd be happy to.

## Steps to reproduce

1.  Open C3
2.  Export as NWjs
3.  Version 60 won't be listed as an option or available to download

## Observed result

There is no option for version 60 of NWjs.

## Expected result

There should be a download for version 60 of NWjs

## More details

I admittedly don't watch this sort of stuff but I'm on version R281 and the option is missing.  Unclear when it started though as I only do real exports every few months.

**Comment by AshleyScirra** [comment]
Oops, the last update accidentally overwrote v0.60.0. I've added it back now, thanks for the heads up.
