### ISSUE TITLE
Pasting 3DShape onto Layer with Z elevation crashes C3.

### ISSUE THREAD

**Issue by Q-ba** [Scirra/Construct-3-bugs#5479]
## Problem description

Pasting a 3DShape onto a Layer with a non-zero Z elevation crashes Construct 3. 

## Attach a .c3p

[LayerZElevationPasteBug.zip](https://github.com/Scirra/Construct-3-bugs/files/8050647/LayerZElevationPasteBug.zip)

## Steps to reproduce

1. Copy the 3DShape.
2. Set Layer 0 Z elevation to 100.
3. Paste the 3DShape.

## Observed result

Construct 3 crashes with the save project/restart window.

## Expected result

The 3DShape gets pasted onto the Layer.

## More details

Seems to only affect 3DShapes.

**Affected browsers/platforms:** Chrome/Windows 10

**First affected release:** r282 beta

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected finite number @ TypeError: expected finite number at Function.R.o (https://editor.construct.net/r282/main.js:859:407) at sR (https://editor.construct.net/r282/components/editors/layoutView/layoutView.js:32:159) at window.gl.N6a (https://editor.construct.net/r282/components/editors/layoutView/layoutView.js:115:351)
Stack: TypeError: expected finite number at Function.R.o (https://editor.construct.net/r282/main.js:859:407) at sR (https://editor.construct.net/r282/components/editors/layoutView/layoutView.js:32:159) at window.gl.N6a (https://editor.construct.net/r282/components/editors/layoutView/layoutView.js:115:351)
Construct 3 version: r282
URL: https://editor.construct.net/r282/
Date: Sat Feb 12 2022 01:49:58 GMT+0800 (Singapore Standard Time)
Uptime: 903.5 s

Platform information
Browser: Chrome
Browser version: 98.0.4758.82
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
C3 release: r282 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9729)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report. The problem is when you Z elevate the layer to 100, it is exactly at the position of the camera at 100% zoom (in fact, slightly behind the visible near-plane). This means there is no solution to the calculation done to work out where you clicked, as the entire layer is invisible and the clicked position does not correspond to any visible position on the layer. Since there is no mathematical solution it's impossible to drop the pasted instance in the right position; the next beta works around this by just reverting to the mouse position, which isn't technically correct, but at least avoids it crashing.
