### ISSUE TITLE
Drawing Canvas self-erasing when updated after rescaling Layout or Window

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-3-bugs#5481]
## Problem description

After the Layout or the Window scale changes, 
If an already-drawn Drawing Canvas is updated  (using any of the Draw Action), 
The Drawing Canvas self-erases.

## Attach a .c3p

[[Bug] DrawingCanvas_SelfErasing_OnUpdateAfterRescale.zip](https://github.com/Scirra/Construct-3-bugs/files/8073062/Bug.DrawingCanvas_SelfErasing_OnUpdateAfterRescale.zip)

## Steps to reproduce

1. Draw something on a Drawing Canvas
2. Rescale the Layout (using a set layout scale event) or rescale the window (manually)
3. Draw something else on the Drawing Canvas => what was drawn in step 1. disappeared

## Observed result

On the .c3p sample, a red ellipse is drawn on the Drawing Canvas at the Bullet position every tick, and the layout is rescaled to 1.0+random(-0.01,0.01) every 0.2 seconds. 
Everytime the layout is rescaled, the "red trail" drawn on the Canvas disappears.

![Bug  DrawingCanvas_SelfErasing_BadObservedResult](https://user-images.githubusercontent.com/99751718/154115958-c564de16-594c-48ea-b45f-fad426c43dc4.gif)

## Expected result

(Same .c3p disabling the layout rescale)

![Bug  DrawingCanvas_SelfErasing_ExpectedResult](https://user-images.githubusercontent.com/99751718/154115977-3625cbc6-7751-4f26-97b3-5d41b2a4d745.gif)

## More details

(**note** : it's not self-erasing right after rescale, only if the drawing canvas is updated **after** the rescale)

If this issue is made by design by Construct Team, because of performance issues related to CPU/GPU when rescaling a Drawing Canvas, for example, : it would still be nice to implement a work-around that fixes this automatically behind-the-scene so Construct users doesn't need to take care about this. For example by saving the drawing canvas right before the Window/Layout scale changes and redrawing it right before a Draw action is called after that.

Some counter-intuitive work-arounds were found but doesn't cover most use cases. For example, the current issue makes it impossible or at least difficult and costly to have a game in which the layout scale changes every tick (thanks to dynamic zooming camera system based on main character position in Level) and being able to "paint" the Canvas by drawing moving particle systems. (to draw and keep blood splatters of all previously killed ennemies on the environment for example)

**This issue seems pretty important to fix because even games who doesn't need to rescale layout are affected as if the player just rescales the game window by hand, it happens**. Making the whole Drawing Canvas feature unusable in a lot of cases, which is a shame because otherwise this plugin is amazing and opens a lot of possibilities !

**Affected browsers/platforms:** Chrome + Firefox + Edge at least, but probably all platforms/browsers (everybody I asked on the Discord has the same issue)

**First affected release:** The issue is there since at least a year (maybe it was always there). I'm checking if it's still there everytime an update fixes something related to Drawing Canvas.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 98.0.4758.82
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
C3 release: r283 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 433 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9729)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. See the section on handling resizing and resolution in the [Drawing Canvas manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/drawing-canvas).

**Comment by OverboyDev** [comment]
> This is currently by design. See the section on handling resizing and resolution in the [Drawing Canvas manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/drawing-canvas).

I know it is by design, see the "More Details", I'm just wondering why it is impossible to solve this behind the scene. It makes the whole plugin unusable in a lot of use cases. Sometimes it is impossible to redraw the canvas every frame, for example if what was drawn were particle systems.

**Comment by AshleyScirra** [comment]
It's a difficult problem. If you paste to a low-resolution surface and then scale it up, it will look blurry. Creating a new surface with a higher resolution ensures you can still get good quality rendering to the surface, but it clears it. If the old content is drawn over the top, it still appears blurry, and if that happens while the scale smoothly changes over time, it has a weird effect where the old content progressively blurs further and further across the image, since low-resolution's blurriness essentially does an expanding blur effect over time. I'm not sure how to better handle it. I think for the use case described here, it may be better just to spawn lots of sprites. The engine can easily handle tens of thousands of them - hundreds of thousands on some systems.

**Comment by pigmalien** [comment]
How about adding a way to load the binary from local storage directly in to Drawing Canvas so we don't have to load it in to a Sprite to paste in to DC?

**Comment by OverboyDev** [comment]
> It's a difficult problem. If you paste to a low-resolution surface and then scale it up, it will look blurry. Creating a new surface with a higher resolution ensures you can still get good quality rendering to the surface, but it clears it. If the old content is drawn over the top, it still appears blurry....

Thank you for those additional explanations.

But still, something i don't understand is why it would be impossible to redraw what was erased right after the Canvas is rescaled (and cleaned), using some maths and the draw features behind the scene.
Is it because it would involve a complicated algorithm to upscale what was previously drawn ?

If this really is a problem, don't you think something such as having a drawing canvas with higher resolution by default, would help to prevent this need to erase the canvas to keep good quality ? 
(like by default it would be corresponding to the resolution for full screen in 1080p, but user could opt for 4K if needed, or putting a value that allows them to keep good quality whatever the zoom in/out of their game will be), 
Like the canvas by default is higher rez and just rendered scaled down instead of changing its actual resolution depending on window size/layout scale ?

It could be 2 additional properties of the Drawing Canvas object :
- **a boolean that allows to choose between dynamic resolution (how the plugin works right now) and fixed resolution (as described in my paragraph just above)**
- if the boolean Fixed Resolution is true, an other properties that allow to choose the desired resolution, that would be then scaled up or down depending on layout and window scale or even the scale of the Drawing Canvas object itself. That way no need to change the resolution of the drawing canvas, just scale it up or down.

**Comment by OverboyDev** [comment]
> I'm not sure there's one simple and good solution that will always work. But if you want a fixed resolution mode, the best approach is to file it as a suggestion here: https://construct3-21h2.ideas.aha.io/

Ok thank you for explaining this ! I just added a suggestion about the Fixed Resolution for Drawing Canvas here :
https://construct3-21h2.ideas.aha.io/ideas/C321H2-I-226
