### ISSUE TITLE
Drawing Canvas - Clear Rectangle Function reverses Y Coordinate

### ISSUE THREAD

**Issue by JauqGames** [Scirra/Construct-3-bugs#5482]
## Problem description

When using the "Clear Rectangle" function for a Drawing Canvas object the Y coordinates are reversed. This is **inconsistent** with other Drawing Canvas functions.

## Attach a .c3p

[ClearRectangleIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/8082437/ClearRectangleIssue.zip)

## Steps to reproduce

1. Create a Drawing Canvas object and size it to fit the Viewport.
2. Fill a shape somewhere within the Drawing Canvas.
   - In my example: I filled an ellipse at screen center with radius 200.
3. Use the Clear Rectangle function to remove a portion on the top half of the object.
   - In my example: I attempted to clear a 20x20 rectangle at coordinates 860,440.

## Observed result

A small square was removed at the correct X coordinates, but the reversed Y coordinates.
![ClearRectangleIssue](https://user-images.githubusercontent.com/39632133/154331227-5828ea80-e985-40b3-94c1-99a1ce3eaa59.jpg)

## Expected result

The small square should've been removed above the center line.

## More details

I have not used this function prior to r276.2 stable where I discovered it was broken, but I also tested this on r283 beta (the most recent version as of reporting this) and the problem persists.

**Affected browsers/platforms:** I'm using Chrome 98.0.4758.82 (64-bit)

**First affected release:** Unknown

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 98.0.4758.82
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 1.2 gb (0.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7208)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks for catching this - it looks like it was broken by some refactoring done a few months ago. OpenGL's co-ordinate systems strike again. It should be fixed in the next beta.
