### ISSUE TITLE
3DShapes not rendering through transparent faces of other 3DShapes at higher Z elevation

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#5483]
## Problem description

When using a 3DCamera and viewing a 3DShape through another 3DShape (with transparent or partially-transparent faces), the nearer 3DShape will not appear to render where it is seen through the closer 3DShape while the closer 3DShape's z elevation is higher than its own.

## Attach a .c3p

[3DObjectsDisappear.zip](https://github.com/Scirra/Construct-3-bugs/files/8082786/3DObjectsDisappear.zip)

## Steps to reproduce

1. Open the provided 3DObjectsDisappear.c3p.
2. Run the project, observing that as the dice 3DShapes move up and down over time, they cannot be seen through the "windows" in the slightly Z-elevation-raised 3DTrainCar object until their Z elevation falls lower than that of the 3DTrainCar.
3. Move around with WASD or arrow keys or set the 3DTrainCar's Z elevation with number keys for additional observation.

## Observed result

When a 3DShape is viewed through transparency in a 3DShape closer to the 3DCamera, it doesn't show up through this overlapping area on-screen.

## Expected result

3DShapes can be seen through transparency in other 3DShapes, to achieve effects such as viewing objects out a building window.

## More details

https://user-images.githubusercontent.com/4585257/154340319-69e539c1-9646-4180-b586-ccd132f5d0cc.mp4

**Affected browsers/platforms:** Firefox, Chrome.

**First affected release:** First seen no later than r283.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 97.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0
C3 release: r283 (beta)
Language setting: en-US
Local storage

Storage quota (approx): 58 gb
Storage usage (approx): 433 mb (0.7%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
See the section on transparency in [Using 3D in Construct](https://www.construct.net/en/tutorials/using-3d-construct-2746). This project is a perfect demonstration of why you need the "Camera distance" draw order on the layer rather than "Z order", since transparent content needs to be drawn from furthest-distance to nearest-distance. That then causes Z fighting on the shadows, but you should be able to fix that by using a separate layer for the ground, and a separate layer for the transparent content with "camera distance" draw order (again as per the advice in that tutorial).

**Comment by ChromeWisp** [comment]
Whoops - sorry about that! You're completely right, of course.
