### ISSUE TITLE
3DShape faces on screen disappear depending on viewing angle

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#5484]
## Problem description

When using a 3DCamera to view a 3DShape, some of the 3DShape's faces can disappear based on the angle between the face and the camera, even when the face remains in view.

## Attach a .c3p

[3DFacesDisappear.zip](https://github.com/Scirra/Construct-3-bugs/files/8082983/3DFacesDisappear.zip)

## Steps to reproduce

1. Open the attached 3DFacesDisappear.c3p.
2. Run the project, noting that one of the 3DTrainCar object's faces is already not visible from the start.
3. Move with WASD/arrow keys or strafe with Q and E keys to observe the effect changing which 3DShape faces are visible depending on viewing angle.

## Observed result

3DShape's faces disappear depending on the camera's angle to them.

## Expected result

3DShape's faces would _not_ disappear depending on the camera's angle to them.

## More details

https://user-images.githubusercontent.com/4585257/154342891-0bf01327-4451-479d-be39-d97121a3c9d2.mp4

**Affected browsers/platforms:**  Firefox, Chrome.

**First affected release:**  First seen no later than r283.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 97.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0
C3 release: r283 (beta)
Language setting: en-US
Local storage

Storage quota (approx): 58 gb
Storage usage (approx): 433 mb (0.7%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, good catch. For proper transparent rendering 3D shape has to sort the order its faces are drawn in by camera distance, but in some circumstances this did not produce a good ordering. I've improved the ordering algorithm so it should be fixed in the next beta.
