### ISSUE TITLE
Vertical text alignment issues with enabled BBCode

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5486]
## Problem description

Here is a new report for #4711 issues. The current version has worked well, but there are still some details.

## Attach a .c3p
[text_bbcode_issues.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8087168/text_bbcode_issues.c3p.zip)

### Top Vertical alignment 

```
{"is-c3-clipboard-data":true,"type":"world-instances","items":[{"type":"EnableBBCode","properties":{"text":"Text","enable-bbcode":true,"font":"Arial","size":48,"line-height":0,"bold":false,"italic":false,"color":[0,0,0,1],"horizontal-alignment":"left","vertical-alignment":"top","wrapping":"word","initially-visible":true,"origin":"top-left"},"instanceVariables":{},"behaviors":{},"world":{"x":346,"y":54,"width":128,"height":64,"originX":0,"originY":0,"color":[1,1,1,1],"angle":0,"zElevation":0}},{"type":"NoBBCode","properties":{"text":"Text","enable-bbcode":false,"font":"Arial","size":48,"line-height":0,"bold":false,"italic":false,"color":[0,0,0,1],"horizontal-alignment":"left","vertical-alignment":"top","wrapping":"word","initially-visible":true,"origin":"top-left"},"instanceVariables":{},"behaviors":{},"world":{"x":98,"y":54,"width":128,"height":64,"originX":0,"originY":0,"color":[1,1,1,1],"angle":0,"zElevation":0}}],"object-types":[{"name":"NoBBCode","plugin-id":"Text","isGlobal":false,"instanceVariables":[],"behaviorTypes":[],"effectTypes":[]},{"name":"EnableBBCode","plugin-id":"Text","isGlobal":false,"instanceVariables":[],"behaviorTypes":[],"effectTypes":[]}]}
```
Arial  
![Snipaste_2022-02-17_15-43-40](https://user-images.githubusercontent.com/45864744/154428769-46faab8a-e720-42b9-9b48-25e6f6f5d683.png)

Silver 
![top](https://user-images.githubusercontent.com/45864744/154426386-2fcaf811-706a-489a-bed7-59ee5f2d0052.png)

### Bottom Vertical alignment

This problem is displayed differently in different fonts. Some fonts work well, e.g. Arial. But some fonts are different results.

Arial  (work well)  
![Snipaste_2022-02-17_15-32-31](https://user-images.githubusercontent.com/45864744/154427080-10dcd14f-252a-466e-ace7-1cd353ea4d74.png)

Silver  
If the Text Object height is small (96px). (but still larger than Text Font Size: 48px)  
![bottom](https://user-images.githubusercontent.com/45864744/154427275-56322ce3-f818-45c4-9530-492c378f3ffe.png)

If the Text Object height is enough.  when enable bbcode the y-axis off by 1 pixels
![Snipaste_2022-02-17_15-35-43](https://user-images.githubusercontent.com/45864744/154427761-99a074e3-de7f-4dd0-84fb-40a03d5b8433.png)

## More details

Silver  
https://poppyworks.itch.io/silver

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 98.0.4758.82
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
C3 release: r283 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 196 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.5671)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The situation with text alignment is complicated, but so far, this is all by design.

Text alignment "top" differs between BBcode enabled and disabled mainly for compatibility with C2 projects. "top" originally placed the text too high up so some characters in some languages would get cut off; C3 with the new BBcode feature fixes that, but doesn't change BBcode disabled for backwards compatibility.

Text alignment "bottom" depends on the fontBoundingBoxDescent measurement for the font. Some web fonts seem to set weird values for that, which means you get weird results. But there's nothing we can do about it. If the font says it needs that much space under it, it gets that much space under it; there's no way to know how much it "really" needs, because that value is meant to be the thing that tells you. You can see it working well with Arial, because it sets the right ascent/descent sizes. But the web font you provided sets unusually large values, so gets spaced out more.

**Comment by XHXIAIEIN** [comment]
Is it possible to provide an offset property with editor, user can adjust the fontBoundingBoxDescent offset value themselves? Similar to Photoshop's "paragraph" property.or like css style of "padding" property.

Of course, I will explain it in detail later in the ideas website.

**Comment by AshleyScirra** [comment]
Font metrics are themselves complicated, when you get in to font sizing units, scaling, changing font face and font size with BBcode, etc. I'd suggest just using top alignment and then positioning the text manually, or based on the measured text size.
