### ISSUE TITLE
In Firefox, properties bar dropdown menus inconsistently ignore/reject mouse input

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#5488]
## Problem description

While using Construct 3 in Firefox, dropdown menus in the properties bar will sometimes ignore or reject user's attempts to mouse over a dropped-down option (instead closing the dropdown as if the mouse was moved elsewhere outside the dropdown or any of its
visible options when opened) or when clicking an option to select it (instead closing the dropdown as if the moused-over option was selected, but in fact the dropdown choice has remained unchanged from its previous selected option). The behavior does not seem entirely consistent as mousing over and selecting options sometimes works and sometimes has these issues instead, at times requiring the user to re-open the dropdown and attempt to click their selection from it several times in a row before the selection will apply.

## Attach a .c3p

[DropdownMisbehavior.zip](https://github.com/Scirra/Construct-3-bugs/files/8098147/DropdownMisbehavior.zip)

## Steps to reproduce

1. Open the included .c3p or create a new C3 project in Firefox.
2. Click a dropdown menu in the properties bar to open it.
3. Attempt to move the mouse down to hover over one of the revealed options, noting that sometimes this mouse movement causes the closure of the dropdown as if the mouse had moved out of the dropdown area entirely.
4. After a successful attempt to mouse over a dropped-down option without the dropdown closing, attempt to select the option by clicking it, noting that sometimes even though the dropdown closes at this point, the clicked option has not been set as the dropdown's selection.

## Observed result

A dropdown will often close when mousing over its options or will not set a clicked option as its selection.

## Expected result

A dropdown _would not_ close when mousing over its options and _will_ set a clicked option as its selection.

## More details

https://user-images.githubusercontent.com/4585257/154575955-0d41634c-f01d-4e09-b7bc-8f9f5d856d02.mp4

Note that in this video, when the dropdown appears to close suddenly while the mouse cursor is still over it, I have _not_ clicked a mouse button to make it do so - it just happens while mousing over the options. On the same note, when the dropdown remains open long enough to hover over one of its options and then closes a moment later without setting the hovered option as this dropdown's selection, I _have_ clicked on the hovered option, even though the choice did not seem to apply.

I've tested in other browsers, but this issue doesn't seem to occur in Chrome or Edge, only in Firefox so far.

**Affected browsers/platforms:** Firefox

**First affected release:** First seen no later than r283

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 97.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0
C3 release: r283 (beta)
Language setting: en-US
Local storage

Storage quota (approx): 58 gb
Storage usage (approx): 391 mb (0.7%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by ChromeWisp** [comment]
Apologies for that - I've edited the post to contain an actual zipped project file this time.

I have also checked in default theme now (I'm on Windows and normally using dark theme) and the dropdowns seem completely fine now! If I switch to dark _or light_ theme, the dropdown issues return, but when I switch to default theme, the problem is gone! So I guess it's an issue with the non-default themes?

**Comment by AshleyScirra** [comment]
I see, it is specific to Firefox with the dark theme. It's really weird, sometimes the dropdown seems to randomly disappear too. I can't think of what could be causing that. Maybe it's a Firefox bug, in which case it will be difficult to do anything about it. Assigning to @Animmaniac in case he's aware of any style changes that might be relevant.

**Comment by AshleyScirra** [comment]
This is an old issue and I suspect it is a problem with Firefox rather than Construct. I don't think it's actionable as there is no clear way to fix or work around the problem on our side. If this still happens in the latest Firefox it would be best to report the issue to Mozilla as a web compatibility problem with Firefox.
