### ISSUE TITLE
Pathfinding behavior not going straight as it should

### ISSUE THREAD

**Issue by User845791** [Scirra/Construct-3-bugs#5489]
## Problem description

The path chosen by the pathfinder behavior is changed by obstacles that are not in its way, and should not alter it . 

## Attach a .c3p

[drive.google.com/file/d/1KvFJtfAnE_aSnZry5_Ckx-G2rjOQQYNK/view](https://www.construct.net/out?u=https%3a%2f%2fdrive.google.com%2ffile%2fd%2f1KvFJtfAnE_aSnZry5_Ckx-G2rjOQQYNK%2fview%3fusp%3dsharing)

## Steps to reproduce

1. Open the c3p and preview it.
2. Drag the blue square closer to the path generated by the pathfinder but not in its way.

## Observed result

The path change when it should not (when the blue square enter slightly in the yellow background).

## Expected result

When there is no obstacles in its way, the path generated by the pathfinder behavior should not change.

## More details
No matter the cell size, the path doesn't go straight.

**Affected browsers/platforms:** 

Tested on chrome and firefox

First discovered on r276.2

**Comment by AshleyScirra** [comment]
This is currently by design. The Pathfinding behavior will plot a direct route to the destination if the entire area is clear. If the area is not clear, it plots a route using the grid system and pathfinding algorithm to ensure it goes around any obstacles.
