### ISSUE TITLE
Editor crashes editing sprite after deleting a tilemap

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#549]
## Problem description

The tilemap bar seems to be in a broken state after tilemap deletion, using the animations editor can then cause the tilemap bar to crash. In addition the tilemap bar still shows the tilemap AFTER it's been deleted, which allows you to edit said tilemap (which also causes a crash).

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. New project
2. Insert tilemap (then close animations editor)
3. Delete tilemap from project
4. Insert sprite
5. Draw line in anims editor
6. Close anims editor

## Observed result

Crash

## Expected result

Animations editor to close

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: animation frame has no content @ Error: animation frame has no content at c.ǃbDt (https://editor.construct.net/r40/main.js:61:189545) at c.ǃUB (https://editor.construct.net/r40/main.js:61:191979) at e.ǃCM (https://editor.construct.net/r40/components/bars/tilemapBar/tilemapBar.js:1:3401) at e.window.ǃGF.ǃEX (https://editor.construct.net/r40/components/bars/tilemapBar/tilemapBar.js:1:17268) at e.window.ǃGF.ǃlr (https://editor.construct.net/r40/components/bars/tilemapBar/tilemapBar.js:1:17755) at ǃb.Event.ǃTDf.ǃTDA (https://editor.construct.net/r40/main.js:2:254817) at window.ǃXgY.dispatchEvent (https://editor.construct.net/r40/main.js:2:253295) at window.ǃXgY.ǃbhi (https://editor.construct.net/r40/main.js:162:42737) at c.ǃ$R (https://editor.construct.net/r40/main.js:61:191438) at c.i (https://editor.construct.net/r40/main.js:71:68827)
Stack: Error: animation frame has no content at c.ǃbDt (https://editor.construct.net/r40/main.js:61:189545) at c.ǃUB (https://editor.construct.net/r40/main.js:61:191979) at e.ǃCM (https://editor.construct.net/r40/components/bars/tilemapBar/tilemapBar.js:1:3401) at e.window.ǃGF.ǃEX (https://editor.construct.net/r40/components/bars/tilemapBar/tilemapBar.js:1:17268) at e.window.ǃGF.ǃlr (https://editor.construct.net/r40/components/bars/tilemapBar/tilemapBar.js:1:17755) at ǃb.Event.ǃTDf.ǃTDA (https://editor.construct.net/r40/main.js:2:254817) at window.ǃXgY.dispatchEvent (https://editor.construct.net/r40/main.js:2:253295) at window.ǃXgY.ǃbhi (https://editor.construct.net/r40/main.js:162:42737) at c.ǃ$R (https://editor.construct.net/r40/main.js:61:191438) at c.i (https://editor.construct.net/r40/main.js:71:68827)
Construct 3 version: r40
URL: https://editor.construct.net/
Date: Fri Jun 23 2017 12:55:10 GMT+0100 (GMT Summer Time)
Uptime: 576.5 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.109
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36
C3 release: r40

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r41.

The case of the object type being deleted wasn't handled, at all.
