### ISSUE TITLE
Even while holding Ctrl, previous selections are lost when click-and-dragging over more objects

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#5492]
## Problem description

After clicking and dragging a selection rectangle over multiple objects in a layout to select them, then while holding Ctrl and beginning to drag to make a second selection rectangle around additional objects, all previously-selected objects are unselected. Thus, clicking and dragging multiple times  - even with Ctrl held - to select additional groups of objects is impossible...even though Ctrl+_clicking_ additional objects _after clicking and dragging to select a first group of objects_ is possible.

## Attach a .c3p

[SeveralObjects.zip](https://github.com/Scirra/Construct-3-bugs/files/8099405/SeveralObjects.zip)

## Steps to reproduce

1. Open the enclosed project or create a new one, adding at least 3 sprites to its layout.
2. Click and drag a rectangle selection over multiple (but not all) sprites on the layout to select them.
3. While holding Ctrl (as also used when Ctrl+clicking objects for more selections) click and drag another rectangle selection over any remaining, unselected sprites on the layout, noting that the previously-selected sprites are now unselected. Also note that it _is_ possible to Ctrl+click an unselected sprite after previously selecting sprites with a rectangle selection without deselecting those previous sprites.

## Observed result

When attempting to hold Ctrl while clicking and dragging rectangle selections over unselected objects with previous objects already selected, the previously-selected objects will be deselected.

## Expected result

Just as when holding Ctrl while clicking to select new objects while leaving previously-selected objects selected, holding Ctrl while clicking and dragging a rectangle selection over new objects would leave previously-selected objects selected. Much like in other game engine, text editor, and image editor programs as well.

## More details

https://user-images.githubusercontent.com/4585257/154742178-87d58da0-7aad-40d9-a193-d339706f97d6.mp4

Note, in this video I am continuously holding Ctrl when clicking and dragging the rectangle selections over objects.

**Affected browsers/platforms:** Firefox, Chrome, Edge

**First affected release:** r283

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 97.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0
C3 release: r283 (beta)
Language setting: en-US
Local storage

Storage quota (approx): 58 gb
Storage usage (approx): 398 mb (0.7%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think this is the standard way for drag selection boxes to work. I tried Google Slides with a few text boxes placed around and it seems to work the same way. As far as I can tell, it's also worked this way in Construct right back to C2 which was first released in 2011 - so it seems it's worked this way for about a decade, and I don't think anyone else has ever mentioned it. So I think that's the way it's meant to be.
