### ISSUE TITLE
Dark theme - spinners missing in the number fields

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5493]
## Problem description

In Chrome little spinners/arrows are missing in the number fields - for example in the animation editor, array editor, properties panel etc.

![image](https://user-images.githubusercontent.com/36763350/154898464-5a728c6c-e55c-4041-923b-6d9783f2b9da.png)

![image](https://user-images.githubusercontent.com/36763350/154898541-9720248c-8cff-45db-ab61-9877b1bcdf74.png)

In Firefox the spinners are visible:

![image](https://user-images.githubusercontent.com/36763350/154898629-58086311-24e8-457b-90b1-af99ad3fed19.png)

## More details

**Affected browsers/platforms:** Chrome

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 98.0.4758.102
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.3958333730697632
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
C3 release: r283 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 52 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.11020.10001)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Browsers are pretty fussy about when to show spinners. IIRC they're not actually part of the specification so whether or not they appear is basically at the browser's discretion, and some styles may cause them to be hidden as they alter the appearance of the element too much. So it may not be fixable.

I couldn't immediately find any styles that affected whether the spinners appear so assigning to @Animmaniac in case he is aware of any relevant styles.

**Comment by AshleyScirra** [comment]
I eventually tracked down an obscure CSS feature that affected this. They should appear again in the next beta.

**Comment by dop2000** [comment]
This is great, thank you! This was one of the main problems stopping me from switching to the dark theme, I use spinners a lot.
