### ISSUE TITLE
Image is not defined

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5497]
## Problem description

The project does not start and the error "Image is not defined" appears in the console.

## Attach a .c3p

"Cave Bridge" on the start page.

## Steps to reproduce

1. Open and run project.

## Observed result

The game won't start.

![bug](https://user-images.githubusercontent.com/91274932/155207793-8966df66-f2be-4819-b556-ec73f8e3a611.png)

## Expected result

The game starts.

![bug2](https://user-images.githubusercontent.com/91274932/155207812-f7e3bc95-0c94-43dd-a3e2-9eab1293d136.png)

## More details

I found out that the bug does not occur if the "Fog" object is removed or the Worker mode is turned off.

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r284b.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 95.0.4638.54
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
C3 release: r284 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 578 mb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll-10.18.10.4653)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This worked fine for me, but then I realised your system only supports WebGL 1, and I think this only happens if the device does not support WebGL 2.

**Comment by AshleyScirra** [comment]
This turned out to be a very complicated texture upload problem affecting only WebGL 1 in a worker. While the vast majority of devices nowadays support WebGL 2 (which is not affected), I suspect this is a regression caused by some recent changes, and I think there's still something like ~5% of devices using WebGL 1, so this ought to be fixed for the next stable release, which we currently have scheduled for next week. Since the fix is not trivial I think we will get a patch release out today just to try to confirm this is fixed and hasn't broken anything else before we proceed with a stable release next week.

**Comment by WilsonPercival** [comment]
> This turned out to be a very complicated texture upload problem affecting only WebGL 1 in a worker. While the vast majority of devices nowadays support WebGL 2 (which is not affected), I suspect this is a regression caused by some recent changes, and I think there's still something like ~5% of devices using WebGL 1, so this ought to be fixed for the next stable release, which we currently have scheduled for next week. Since the fix is not trivial I think we will get a patch release out today just to try to confirm this is fixed and hasn't broken anything else before we proceed with a stable release next week.

I don't think it's just because of WebGL2. On another computer that supports WebGL2, the same error occurs. If the console is not open, the game starts. If the console is open - the game does not start and this error pops up.

https://user-images.githubusercontent.com/91274932/155366310-1877c85d-8e01-4d1d-93d9-75b69948f292.mp4

Platform information
Browser: Chrome
Browser version: 97.0.4692.99
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
C3 release: r284 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 137 gb
Storage usage (approx): 556 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Apple
Renderer: Apple M1
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
Please test r284.2 which includes this fix.

**Comment by WilsonPercival** [comment]
> Please test r284.2 which includes this fix.

Working.
