### ISSUE TITLE
Missing translate

### ISSUE THREAD

**Issue by DavidCB14** [Scirra/Construct-3-bugs#5498]
## Problem description

In the main frontend of C3 there is an Explore column field whose heading is not translated. Even in poeditor exists the entry and it has a translation:
English = EXPLORE
Spanish = EXPLORA

No C3 examples involved
See the capture here
![image](https://user-images.githubusercontent.com/11505355/155224460-28da74b7-0298-4c27-ad32-eddc9cfff909.png)

**Comment by AshleyScirra** [comment]
Thanks for spotting that. Fixed for next release.
