### ISSUE TITLE
Collision Polygon Point X,Y text is stuck at the last edited value (Firefox)

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5501]
## Problem description

After editing the Y value of some collision polygon point, the Y text remains at this value even after selecting other points. Affects Firefox but not Chrome.

## Attach a .c3p

(New Project)

## Steps to reproduce

1. Create a new project.
2. Add a Sprite.
3. Open its animation editor.
4. Move any polygon point: X and Y values update.
5. Edit its Y value using Y textbox, then press Enter.
6. Move any **other** polygon point: Y doesn't update anymore.
7. Choose another point.
8. Edit X value using X textbox, then press Enter.
9. Move any **other** polygon point: X doesn't update anymore.

## Observed result

The text shows the last value only. The effect persists even after we close and re-open the animation editor.
Update:
- The issue affects X textbox too.
- It persists a project restart.
- It resets after Editor restart.

## Expected result

Show the value of the currently selected point.

## More details

**Affected browsers/platforms:** Firefox 97.0.1

**Comment by Alaadel** [comment]
Update:
- The issue affects X textbox too.
- It persists a project restart.
- It resets after Editor restart.

New test steps:
1. Open animation editor.
2. Move any polygon point: X and Y values update.
4. Edit its Y value using Y textbox, then press Enter.
6. Move any **other** polygon point: Y doesn't update anymore.
7. Choose another point.
8. Edit X value using X textbox, then press Enter.
9. Move any **other** polygon point: X doesn't update anymore.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
