### ISSUE TITLE
Framerate mode V-synced introduce errors on iOS

### ISSUE THREAD

**Issue by janfredslund** [Scirra/Construct-3-bugs#5502]
When we play our game in the browser (on computer as well as mobile Safari) everything works fine! When we export our game to Cordova iOS we see a lot of problems with the 'Framerate mode' when set to 'V-synced'. We see skipped conditions and therefore also a lot of random errors. It's also mentioned in this old post: https://www.construct.net/en/forum/construct-3/how-do-i-8/disable-vsync-fixed-time-125951

If we change the setting to 'Unlimited (ticks only) everything works fine. But that doesn't seem to be a viable sollution??

**Comment by XIMIKATIK** [comment]
outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;outline: none;

**Comment by AshleyScirra** [comment]
"V-synced" has been the default mode for years and we are not aware of anyone else having such issues on iOS. It seems likely this is a mistake in your project with handling delta-time.

As per the bug report guidelines, it's impossible for us to investigate without more information anyway, so closing.
