### ISSUE TITLE
Timline relative result mode

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#5504]
## Problem description

I don't know if I missed a feature, or if this is a missing feature or a bug: If I combine with parenting two timelines, and they should move relative to each other, the relative mode does not take into account the angle when moving in x/y.  This way it is impossible to use timelines to do a controlled animation with a rigged puppet, the way it is done in an animation software (like toonboom harmony for example).

## Attach a .c3p

[Timeline_Relative.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8148335/Timeline_Relative.c3p.zip)

## Steps to reproduce

1.analyse the two timelines. The red square moves inside the blue square from left to right. Timeline red result mode is "relative"
2.preview the project
3.

## Observed result

The red square separates from the blue square
## Expected result

the red square should stay inside the blue square and take into account the angle from the blue square while moving from left to right
## More details

**Affected browsers/platforms:** 

Google Chrom on Mac, latest Beta r284.2

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Browser: Chrome
Browser version: 98.0.4758.109
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36
C3 release: r284.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 3.8 gb (1.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 560 OpenGL Engine, OpenGL 4.1 ATI-4.6.21)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment]
Starting with r295 there will be a new option to tell a timeline whether it should transform with a corresponding hierarchy or not. It will be off by default for backwards compatibility, but toggling it on will solve this issue.

**Comment by bubbblebub** [comment]
It works great! This is a very important feature for making animations, thanks a lot!
