### ISSUE TITLE
Audio Scheduling export problem

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#5505]
## Problem description
I would like to re address an old closed bugreport (#5285), as it is still a problem for my project and I found two clean ways to reproduce it based on your audio scheduling example. Problem: The timing of the Sound is correct in construct3 preview, but when I export it to nw.js on Mac the timing is different. When I play two sounds in a row the timing changes again (back to the way it should be)

## Attach a .c3p
[AudioSchedulingBug3_v1.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8148383/AudioSchedulingBug3_v1.c3p.zip)
[AudioSchedulingBug3_v2.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8148384/AudioSchedulingBug3_v2.c3p.zip)

## Steps to reproduce

1.preview the project (you can choose file v1 or v2, v1 reproduces the problem with a wait action, v2 by calling to sound with a function), press the button and listen to the time it takes from pressing the button to the beginning of the sound
2.now export it to nw.js Mac64, chromium 98 
3.repeat step 1 with your exported project
4.activate the deactivated sound event in the eventsheet and repeat step 1 to 3

## Observed result

-in construct 3 preview the sound starts directly when you press the button 
-in the exported file it takes a while before the sound starts
-with the soundevent activated it starts directly when you press the button
## Expected result

the sound should always start at the same time

## More details
I added two project files, both reproduce the same problem. In version one its done with a wait action, in the second by calling the sound with a function.

unfortunately I am lacking a lot of equipment at the moment and cant test other exports, but in my earlier bugreport to the same problem, nw.js on windows worked fine, exports to iOS where the same as nw.js on mac. Android exports worked fine the first time played, when closed and reopened the problem was also there.

**Affected browsers/platforms:** 

**First affected release:** 
the problem appeared first around christmas 2021
## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 98.0.4758.109
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36
C3 release: r284.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 4.7 gb (1.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 560 OpenGL Engine, OpenGL 4.1 ATI-4.6.21)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
PASTE HERE

</details>

**Comment by bubbblebub** [comment]
I have some small additional informations concerning this problem. Windows nw.js export is also somehow affected, my project is on steam and the last time I made an update could export it with NW.js 0.52.0 (required for the previous greenworks plugin), but not with NW.js 0.60.0 (newest greenworks plugin).

I now found a workaround, by placing an empty short soundfile in front of every soundfile thats called with audio scheduling, this seems to work perfect (preview project behaves the same as the exported project).  

So for me the problem is solved even it doesn't feel properly done. If you think it is not a C3 problem feel free to close this report. But then just be aware, that it causes problems if users want to call a scheduled audio with a function, maybe a note in the manual would be great.

**Comment by AshleyScirra** [comment]
I had another look at this but with latest macOS and NW.js versions it seems the NW.js export audio playback works the same as it does in Chrome, i.e. playing back reasonably quickly and with good scheduling consistency. Besides anything to do with audio latency is likely to do with the browser/OS as it is not directly controlled by Construct. I suspect maybe there was some quirk in NW.js or Chrome that was subsequently improved.

Further, there is no technical reason why adding a function call or a wait would affect audio playback in any way: in terms of the actual audio playback commands it will work identically. I strongly suspect there was an intermittent issue and you falsely correlated these to unrelated things based on chance.
