### ISSUE TITLE
Fog Bug on mobile

### ISSUE THREAD

**Issue by MrPotato-1** [Scirra/Construct-3-bugs#5510]
## Problem description

Fog effect is not shown well on Android mobile, it does not fade, appears in gradient colors.

## Attach a .c3p

https://drive.google.com/file/d/17QQudZVFuZHQnDH3HONlVBTxVSadkPN0/view

## Steps to reproduce

1.
2.
3.

## Observed result

![FOG-BUG](https://user-images.githubusercontent.com/81446041/156609542-a96ad549-85fd-4979-a1b0-ff32dac97bca.png)
![FOG-BUG 2](https://user-images.githubusercontent.com/81446041/156610128-d9da64b0-e3e3-4665-8e04-8d8aecf7d7e2.jpg)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It looks like an old device with limited precision in the depth buffer. I suspect it only supports WebGL 1, but no system details were provided so it's difficult to verify.

I don't think it's feasible to fix this, and the vast majority of modern devices support either WebGL 2 or WebGL 1 with good precision in the depth buffer, so most systems should work OK and the older devices will fall out of use eventually anyway.

**Comment by AshleyScirra** [comment]
I think it depends on the device and its supported resolution for the depth buffer. I thought pretty much all modern devices could handle this OK.

I think in the latest releases you should be able to work around it - set the near and far distances in project properties to have the smallest distance between them possible, and then the depth buffer is used over a smaller distance with better resolution.

**Comment by drestuff** [comment]
Thanks for the suggestion. I tried latest release and set the far distance to around 1k (instead of default 10k) and the fog gradient did not seem to look any smoother.

**Comment by drestuff** [comment]
Are you sure this isn't a fixable bug @AshleyScirra? Adjusting far distance, even down to a minimum doesn't make the fog any smoother, there's still some very blocky color banding happening when using this shader on phones.

**Comment by WilsonPercival** [comment]
@drestuff I set the `Near distance` parameter to `6` and this seemed to fix the problem.
