### ISSUE TITLE
Player moviment 8 direction - Vector Y don't wotk in script mode

### ISSUE THREAD

**Issue by Simonatoo** [Scirra/Construct-3-bugs#5511]
## Problem description

When i try to apply force VectorY(8 direction behavior) on my playerInstance it apply in VectorX.
In a eventsheet project work corretly but in scriptmode no. 

## Attach a .c3p

[bugVectorYScriptmode.zip](https://github.com/Scirra/Construct-3-bugs/files/8185841/bugVectorYScriptmode.zip)

## Steps to reproduce

Its a simple code with only 3 lines of code inside function Tick(runtime)

## Observed result

8 direction behavior don't identify VectorY in scriptmode.

## Expected result

The normal VectorY. 

## More details

Dont work corretly:
```
function Tick(runtime)
{
	const player = runtime.objects.obj_playercol.getFirstInstance();
	const move = player.behaviors.Move;
	
	move.vectorY = 50;
}
```
Work corretly:
![image](https://user-images.githubusercontent.com/54852302/156764725-f0267ed5-8c38-423d-b2e6-d854e6f66007.png)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

No details.

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.

**Comment by Simonatoo** [comment]
Thanks!!! I hope I've helped.
