### ISSUE TITLE
Text background bbcode 

### ISSUE THREAD

**Issue by maciejfijalkowski** [Scirra/Construct-3-bugs#5515]
When you create text object, and set text like: 
[size=50px][background=#ff0000]change background color[/background][/size]
or
[background=#ff0000][size=50px]change background color[/size][/background] 
the background of text not covering bottom of letter "g"

[Attach a .c3p](https://hobibit.itch.io/test-font)

## Steps to reproduce

1. Create text object
2. Set text to [size=50px][background=#ff0000]change background color[/background][/size]

## Observed result

Bottom of letter "g" is not covered by background

## Expected result
Whole letter have background

**Comment by AshleyScirra** [comment]
No project has been provided - the link only appears to have an exported project. Please follow the bug report guidelines.
