### ISSUE TITLE
Construct 3 crash when import sprite sheet through JSON file

### ISSUE THREAD

**Issue by Mit1988** [Scirra/Construct-3-bugs#5516]
## Problem description

I import sprite sheet through JSON file, with option: 

"replace-existing-animation": true,
"replace-existing-folder": true

Construct 3 crash when I delete the last previous animation and import it this way.

## Attach a .c3p

https://drive.google.com/drive/folders/1GTO-qtTmbSM55jTG80Lkj_UYbTjcUjGR?usp=sharing

## Steps to reproduce

1.Import the sprite sheet needed with JSON file :
"replace-existing-animation": true,
"replace-existing-folder": true

2.Delete the last previous animation (because cannot delete the last animation in the sprite object, so I will delete it after import other animation)

3.Import again the sprite sheet needed to check it can replace the right animation and subfolder, with JSON file
"replace-existing-animation": true,
"replace-existing-folder": true

4. Crashes

## Observed result

Crash report dialog of Construct 3

## Expected result

The animation and subfolder in the sprite object need to replace.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'name') @ TypeError: Cannot read properties of undefined (reading 'name') at IHa (https://editor.construct.net/r285-3/projectResources.js:250:295) at async MA (https://editor.construct.net/r285-3/projectResources.js:240:476)
Stack: TypeError: Cannot read properties of undefined (reading 'name') at IHa (https://editor.construct.net/r285-3/projectResources.js:250:295) at async MA (https://editor.construct.net/r285-3/projectResources.js:240:476)
Construct 3 version: r285.3
URL: https://editor.construct.net/
Date: Fri Mar 11 2022 10:28:49 GMT+0700 (Indochina Time)
Uptime: 58.9 s

Platform information
Browser: Chrome
Browser version: 99.0.4844.51
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
C3 release: r285.3 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11-24.20.100.6287)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
