### ISSUE TITLE
'OR' block picking logic is incorrect when including non-picking statement

### ISSUE THREAD

**Issue by elle-trudgett** [Scirra/Construct-3-bugs#5517]
## Problem description

When picking objects within an 'OR' block that has a non-picking statement, the object can become 'unpicked' even if the non-picking statement evaluates to true.

## Attach a .c3p

[PickingLogicIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/8236788/PickingLogicIssue.zip)

## Steps to reproduce

1. Start the project
2. Mouse over the orbs. They should all illuminate on hover.

## Observed result

Only the red orbs illuminate.

## Expected result

All orbs should illuminate.

## More details

The issue is with event 4. The "Sprite is Red" condition will unpick the blue sprite even though it's in an OR condition.

**Affected browsers/platforms:** 

Tested on Google Chrome Version 99.0.4844.51 (Official Build) (64-bit)

**First affected release:** 

Tested in r285.3 stable, the latest release available at the time of writing

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 99.0.4844.51
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
C3 release: r285.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 88 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6079)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by elle-trudgett** [comment]
Here is a smaller example

[PickingLogicIssuev2.zip](https://github.com/Scirra/Construct-3-bugs/files/8236795/PickingLogicIssuev2.zip)

All orbs should be red, but only the ones with their instance variable flagged are.

**Comment by AshleyScirra** [comment]
This is not a bug - it's a common mistake when using OR blocks. It's the same as #5023 which is the last time this was reported.

OR blocks still pick instances. So if you add `1 = 1` then the next condition still runs and filters out sprites not matching the condition. Then the event runs but with zero instances picked, if none matched the condition. So nothing happens when you mouse over the sprite. However the event block is actually running: if you do something else like log to the console or change some text, that will happen.

**Comment by elle-trudgett** [comment]
Hmm, I understand now, but if it's true that a non-picking condition in an OR block with a picking condition has no effect, maybe that should be disallowed to avoid confusion.
