### ISSUE TITLE
Video does not play automatically when exporting the project in Windows format.

### ISSUE THREAD

**Issue by diter23** [Scirra/Construct-3-bugs#5519]
I imported an mp4 video to my project, when I use the preview function it looks ok, but after exporting my project and running the exe the video doesn't play automatically. The only way to reproduce is if I press any key or the mouse.

https://drive.google.com/file/d/1iBFQ_6hYkT6VYdnISaBfo54SnOVpKtXj/view?usp=sharing

-Open CP3
-Preview Proyect
-Export to Windows
-Verify exported proyect

The video does not play automatically until you press a key or the mouse.

The video should play automatically.

Let the video play automatically.

**Affected browsers/platforms:** 

**First affected release:** 

This happens to me in version r285.3 and exporting my project to Windows.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
There are two ways to export to Windows: NW.js and the Windows WebView2 exporter. Which are you using?

**Comment by diter23** [comment]
Hi, thanks for your response.
I did not know that the NW.js option also works for Windows. The one I am
using is WebView2. Greetings.

**Comment by AshleyScirra** [comment]
OK, so autoplay does work in NW.js, but wasn't working in WebView2. I found a setting we can change to ensure autoplay is allowed in WebView2 which looks like it fixes this, so it should be working in the next beta.
