### ISSUE TITLE
Jump animation bug.

### ISSUE THREAD

**Issue by diter23** [Scirra/Construct-3-bugs#5520]
As of the new version of Construct (r283.3) the jump animation of one of my sprites started to fail. I reiterate that this did not happen before and I did not modify anything in the code. I attach a video so you can see the bug.

https://drive.google.com/file/d/1i3TRffcA1VZG3yGDKcXsNlvfssJOvn1M/view?usp=sharing

In "Lvl1 Event" Event Sheet, in line 460 findthe group  "Jump Boss Lvl1". Here you can see the code related to the jump.

1. Play layout Lvl1CastleGreen
2. Shoot arrows at the enemy by pressing space

The observed result is that sometimes the jump animation is executed well and other times it is not, showing the bug as seen in the video.

The enemy stays on the ground with the jump animation bugged

The jump animation should work as it does on the occasions where it works correctly and this can be seen in the video.

This can be seen by previewing the project in both Chrome and Mozilla or by exporting the project in Windows.

Attached the video where you can also see the bug:

https://drive.google.com/file/d/1Scx-JT2wvW_SHMkE3t-WLZjiMuIFxca9/view?usp=sharing

**Comment by AshleyScirra** [comment]
I'm afraid it's infeasible for us to investigate problems with such large and complex projects. Please see the bug report guidelines.

**Comment by diter23** [comment]
Ok, I'm going to create a new simpler project and if the same bug appears,
I'll let you know.
