### ISSUE TITLE
Failed to build APK when video plugin is in project

### ISSUE THREAD

**Issue by Leomcs1982** [Scirra/Construct-3-bugs#5522]
## Problem description

I have some old project that I've been updating constantly, in previous versions of Construct 3 I can build normally, but in version R286 it doesn't work. Doing a lot of research and trying, I found that if I removed the VIDEO plugin, I would be able to export to APK. I created a project with just this plugin, without any other elements and it didn't work. I tested it in Chrome and Edge and the problem persists.

## Attach a .c3p

C3P: https://app.box.com/s/jwzy9efmpwnx3oe60o9afuqhslt7dni2

## Steps to reproduce

Export the project to APK

## Observed result

ERROR: "Failed to export project. Check browser console (press F12) for more details."

## Expected result

Build an APK file

## More details
Chrome and Edge. R286.

## System details

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
