### ISSUE TITLE
Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.

### ISSUE THREAD

**Issue by Ocsid** [Scirra/Construct-3-bugs#5525]
## Problem description
Can not open c3p file saved in latest beta.

## Attach a .c3p
[test.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8261726/test.c3p.zip)

## Steps to reproduce

Update to latest beta.
Create sprite on layout1, add variable
Add new layout
drag sprite to layout 2
make sprite on layout2 the template original
make sprite on layout1 the replica
save project as c3p
close project
try to open project.

## Observed result

error message "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

## Expected result

expected the project to open.

## More details

**Affected browsers/platforms:** 
chrome based install as app.

r286 beta

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.

**Comment by Ocsid** [comment]
can I change any value in a text edtitor as a work around?

**Comment by DiegoScirra** [comment]
@Ocsid 

If you rename the cp3 file as a .zip and then unpack it you could edit the project files manually.

If you want to do this you need to look for the **layouts** folder and edit each of the **layout.json** files in it manually. Look for the **"template"** keys in each of the json files and delete them.

When you are done pack everything again into a zip file. The project should load again with out any of the template data is causing problems.

Make sure to do this on a backup copy of your project! Just in case anything goes wrong. You can also just post your project here and I can fix it for you.

**Comment by Wackytoaster** [comment]
Jup that fixes it :)
