### ISSUE TITLE
Timeline Total time should automatically follow of the last keyframe by default

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5527]
## Problem description

In the current design, when the Timeline is created, Total Time will be set to 5s by default. However, if my timelines doesn't take that long, when I preview it, I have to wait extra for the blank time. This is very unreasonable.

So, I think it should default follow of my last keyframe unless I manually adjusting the Total time (drag the green line).

## Steps to reproduce

1.
2.
3.

## Observed result

![Snipaste_2022-03-17_10-27-34](https://user-images.githubusercontent.com/45864744/158755369-439b4c12-7c98-4b9e-ac36-db77a3a865d4.png)

## Expected result

![Snipaste_2022-03-17_15-08-33](https://user-images.githubusercontent.com/45864744/158755436-40422b15-def5-4983-a9a6-9278da5d3030.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I think the current behavior is reasonable: if you've set a 5 second duration, then previewing will take 5 seconds. It also allows you to see the finish position for a few seconds. @DiegoScirra what do you think?

**Comment by XHXIAIEIN** [comment]
If I set 5 seconds duration, then previewing will take 5 seconds. which is reasonable. But there is a precondition, I manually set 5 seconds. And before I manually set it should follow my content length to decide the total time.
