### ISSUE TITLE
Hard to see highlight context menu in dark theme at guided tour

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5528]
## Problem description

Hard to see highlight context menu in dark theme at guided tour 

![Snipaste_2022-03-17_21-20-38](https://user-images.githubusercontent.com/45864744/158818237-5d68c46d-1fab-44c3-ae07-5927afb0b6bf.png)

## Attach a .c3p

[guided-tour-beginnersGuide](https://editor.construct.net/#open=guided-tour-beginnersGuide)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta
