### ISSUE TITLE
Autocomplete problem when replacing a part of a global var

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#553]
## Problem description

In a global variable whenever I replace a letter/number whose position is not at the end of the variable in any dialogue with autocomplete, even though I create the correct variable, the autocomplete comes up and selects exactly what I've written there.

If I press Enter, it just adds it at the cursor and creates a global var which does not exist.

## Attach a .c3p

[AutocompleteProblem.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1099033/AutocompleteProblem.c3p.zip)

![autocompleteproblem](https://user-images.githubusercontent.com/7268697/27500162-e0f8a638-586f-11e7-827c-1d74d82524f4.gif)

This gif is related to the c3p upload
![autocompleteproblem2](https://user-images.githubusercontent.com/7268697/27500163-e35c85ac-586f-11e7-86c0-9cbd2c3117a6.gif)

## Steps to reproduce

1. Open the project attached
2. Edit the Ability_02_Cooldown by removing the 2
3. Write 1 instead of the 2 

## Observed result

The autocomplete pops up even though the global var is correct. When pressed Enter it just adds it at the cursor

## Expected result

I'd expect the autocomplete to not appear at all

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r40

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 92 mb (1.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I've seen other coding IDEs do this :P but it is annoying, so I've fixed it for the next build. Choosing an autocomplete will clear any part of a name to the right of the caret. I'm a little concerned this itself might be annoying in some edge cases, but we'll see how it pans out in r41.
