### ISSUE TITLE
r286 When Add a video and preview, it turns black screen

### ISSUE THREAD

**Issue by EAsome** [Scirra/Construct-3-bugs#5530]
## Problem description

When You add a video and then when you preview the preview turns black for some reason

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by hoyhoyhoyyy** [comment]
I also have this problem on r286. Adding a video plugin and previewing gets stuck in loading or is black.

**Comment by AshleyScirra** [comment]
Same issue as #5522, will be fixed in next beta.
