### ISSUE TITLE
Crashing when right clicking properties of objects on another layout. r286

### ISSUE THREAD

**Issue by hoyhoyhoyyy** [Scirra/Construct-3-bugs#5532]
## Problem description

When you right click on a objects properties and if the object isnt on the layout it will crash.

## Attach a .c3p

https://editor.construct.net/r286/

## Steps to reproduce

1.Open Cave Bridge Template with version r286.
2.While on the Main Level layout and select Bubble from Object types.
3.Then when properties appear on the left, right click somewhere like on the greyed out tween behavior.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
