### ISSUE TITLE
Family Behavior Crash

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#5535]
## Problem description

There is a crash when you add a behavior to a family

## Attach a .c3p

[FamilyCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/8309288/FamilyCrash.zip)

## Steps to reproduce

1. Open attached project
2. Add a behavior to Family1

## Observed result

C3 crashes

## Expected result

Not to crash

## More details

**Affected browsers/platforms:** Chrome/Firefox, Windows

**First affected release:** r286

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r286/main.js, line 944, col 65
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'sU')
Stack: TypeError: Cannot read properties of undefined (reading 'sU') at Function.Dea (https://editor.construct.net/r286/projectResources.js:832:282) at Function.Dea (https://editor.construct.net/r286/projectResources.js:824:471) at d.P3 (https://editor.construct.net/r286/projectResources.js:731:516) at d.xfb (https://editor.construct.net/r286/projectResources.js:732:365) at d.Na (https://editor.construct.net/r286/projectResources.js:564:264) at https://editor.construct.net/r286/components/bars/properti
[FamilyCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/8309283/FamilyCrash.zip)
esBar/propertiesBar.js:136:304 at OW (https://editor.construct.net/r286/components/bars/propertiesBar/propertiesBar.js:46:162) at d.CCG.aa.YK (https://editor.construct.net/r286/components/bars/propertiesBar/propertiesBar.js:136:269) at https://editor.construct.net/r286/components/bars/propertiesBar/propertiesBar.js:24:372 at gh (https://editor.construct.net/r286/main.js:370:150)
Construct 3 version: r286
URL: https://editor.construct.net/r286/
Date: Sat Mar 19 2022 15:06:14 GMT+0200 (Eastern European Standard Time)
Uptime: 244.8 s

Platform information
Browser: Chrome
Browser version: 99.0.4844.74
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
C3 release: r286 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1, D3D11-9.18.13.4195)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by SamuelCurrier** [comment]
I can confirm that I had this issue as well. The behavior does actually get added to the family, but then it crashes. When I load up the local saved file afterwards, the behavior is there. This is in the most recent Beta version for me.

I came here to report it, good on you for beating me to it!

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
