### ISSUE TITLE
Buttons for dialogues inconsistent in placement

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#554]
## Problem description

I'm unsure if this is regarding the Dark Theme only or not.
There are buttons in dialogue windows which are inconsistent in location. This is a very minor thing but so is the fix I would guess.

The reference dialogue I got was the Compare two values. It is the most common layout I see in C3.

![image](https://user-images.githubusercontent.com/7268697/27501347-6aac23d2-5875-11e7-880c-69ad2d36e33e.png)

However there are some dialogue windows in which the buttons are inverted.
This is the one I mostly bump into, and if you agree to invert the buttons I can update this thread with others which I find.
![image](https://user-images.githubusercontent.com/7268697/27501356-7a015456-5875-11e7-830a-0db92de7c7e7.png)

I've countlessly clicked the wrong button on that one.

Now I'm not an UIX expert by far, but I've done some research and it seems (apart from the obvious consistency is key) that the affirmative button is suggested to be placed on the right side next to the right border.

https://material.io/guidelines/components/buttons.html#buttons-persistent-footer-buttons - seems they show Chrome and Android placement mostly
http://uxmovement.com/buttons/why-ok-buttons-in-dialog-boxes-work-best-on-the-right/

## Observed result

OK is on left, Cancel is on right while most dialogue windows have it inverted.

## Expected result

I expect to see the OK button on the right side.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r40

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 91 mb (1.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can see the inconsistency, but there is a sort-of logic to it. As with most of Windows we go with the [OK] [Cancel] ordering for most dialogs. The dialogs to add/edit conditions/actions however are more of a wizard with next/back sequencing. With these dialogs it makes more sense to have [Back] [Next] (and Next says Done on the last step) since that corresponds to the "direction" you're going in (as per reading order).

I think changing this would just cause more confusion, though.
