### ISSUE TITLE
Right Click Menu 286

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#5540]
## Problem description
Right click menus are not showing up in the regular browser texts(cut paste, etc).

## Attach a .c3p

https://www.dropbox.com/s/h97t4ijkk0ktnuh/rightclickmenu.c3p?dl=1
## Steps to reproduce

1.Open the project
2.Right click on any text input
3.

## Observed result
Nothing happens

## Expected result
The regular context menu should pop up.

## More details

**Affected browsers/platforms:** 

Works correctly in the current stable
**First affected release:** 
286
## System details
W10 Chrome

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta. Was introduced with the new templates features.
