### ISSUE TITLE
Can't open construct 3

### ISSUE THREAD

**Issue by truongson-devgame** [Scirra/Construct-3-bugs#5541]
## Problem description
I can't open construct3 on url: https://editor.construct.net/

Error report information
Type: unhandled exception
File: https://editor.construct.net/, line 1, col 1
Message: Uncaught SyntaxError: Unexpected end of JSON input
Stack: SyntaxError: Unexpected end of JSON input at JSON.parse () at XMLHttpRequest.xhr.onreadystatechange (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=X2Convert%2520Button.user.js&id=c07effcb-d2b2-4057-8152-cbebb7958f32:354:591)
Construct 3 version: r285.3
URL: https://editor.construct.net/
Date: Tue Mar 22 2022 00:36:34 GMT+0700 (Indochina Time)
Uptime: 5.6 s

Platform information
Browser: Chrome
Browser version: 99.0.4844.74
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
C3 release: r285.3 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1 Metal - 76.3)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
<img width="1440" alt="Screen Shot 2022-03-22 at 00 39 31" src="https://user-images.githubusercontent.com/7587813/159332230-a47e56e2-8d1f-4393-aa2f-180b2bf06223.png">

**Comment by DiegoScirra** [comment]
This looks like a browser extension might be causing problems.

Try turning them all off and see if the problem still happens. If the problem is solved by turning all the extensions off, you can then try turning them on one at a time to see which one is the problem.

**Comment by AshleyScirra** [comment]
It looks like it's caused by the Tampermonkey browser extension. You'll probably need to report the issue to them.

**Comment by AshleyScirra** [comment]
The problem is caused by Tampermonkey, but I've updated the next beta to ignore errors caused by Chrome browser extensions, so that should avoid this type of issue happening again. In the mean time you'll need to contact the Tampermonkey developers to identify why it is throwing an exception, apparently due to invalid JSON data, in the context of the page.

**Comment by truongson-devgame** [comment]
Thank all. 
I have done Tampermonkey removal. And, problem solved
