### ISSUE TITLE
File selector not working in Android export if you set accepted file type

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#5542]
## Problem description

When you add a file type to "accepted" like ".json" nothing happens when you tap on the file locator button in an android export.

## Attach a .c3p
[FileSelectorBug.zip](https://github.com/Scirra/Construct-3-bugs/files/8326963/FileSelectorBug.zip)

## Steps to reproduce

1. add file selector
2. set "accepted" value
3. export for android (apk)

## Observed result

the plugin with file type defined does not seem to do anything when you touch it.
## Expected result

It should show a file open dialog with only accepted file types.
## More details

**Affected browsers/platforms:** 
Crome / Android

**First affected release:** 
r285.3
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 99.0.4844.82
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.2000000476837158
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
C3 release: r285.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 331 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.12028.2)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
As far as I can tell, the situation is this: Android WebView doesn't support <input type="file"> at all. Cordova implements a small polyfill to make it work. However that polyfill only appears to understand MIME types.

File extensions are not a universally cross-platform concept - that's the reason MIME types were invented. So using an accept value of `application/json` - the MIME type for JSON files - is actually more cross-platform than using `.json`. And in this case it works, so you can work around the issue that way.

There's the question of file extensions for types that don't have a registered MIME type, e.g. Construct's `.c3p` project file format. But that's not currently supported by Cordova - they would have to add support for that, so it would need to be followed up with them.

**Comment by TheBl4ckSh33p** [comment]
Thanks! I will try the MIME type.

**Comment by TheBl4ckSh33p** [comment]
I added application/json and I can click on it now. But it's still showing all file types on Android, not just .json. I removed it for now.
