### ISSUE TITLE
Family Behavior Crash Again

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#5544]
## Problem description

This problem is possibly related to #5535 that may have not been fixed completely:
When you add a sprite into a family that has a behavior, C3 crashes

## Attach a .c3p

[FamilyCrash2.zip](https://github.com/Scirra/Construct-3-bugs/files/8327334/FamilyCrash2.zip)

## Steps to reproduce

1. Open attached project
2. Add Sprite2 to Family1

## Observed result

C3 crashes

## Expected result

Not to crash

## More details

**Affected browsers/platforms:** Chrome/Firefox, Windows

**First affected release:** r286

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'tU') @ TypeError: Cannot read properties of undefined (reading 'tU') at Function.Fea (https://editor.construct.net/r287/projectResources.js:833:282) at Function.Fea (https://editor.construct.net/r287/projectResources.js:825:471) at d.AZ (https://editor.construct.net/r287/projectResources.js:732:516) at d.Efb (https://editor.construct.net/r287/projectResources.js:733:365) at d.Oa (https://editor.construct.net/r287/projectResources.js:565:264) at https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:136:304 at PW (https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:46:162) at d.CCG.aa.$K (https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:136:269) at https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:24:372 at ih (https://editor.construct.net/r287/main.js:370:229)
Stack: TypeError: Cannot read properties of undefined (reading 'tU') at Function.Fea (https://editor.construct.net/r287/projectResources.js:833:282) at Function.Fea (https://editor.construct.net/r287/projectResources.js:825:471) at d.AZ (https://editor.construct.net/r287/projectResources.js:732:516) at d.Efb (https://editor.construct.net/r287/projectResources.js:733:365) at d.Oa (https://editor.construct.net/r287/projectResources.js:565:264) at https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:136:304 at PW (https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:46:162) at d.CCG.aa.$K (https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:136:269) at https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:24:372 at ih (https://editor.construct.net/r287/main.js:370:229)
Construct 3 version: r287
URL: https://editor.construct.net/r287/
Date: Tue Mar 22 2022 21:19:44 GMT+0200 (Eastern European Standard Time)
Uptime: 121.2 s

Platform information
Browser: Chrome
Browser version: 99.0.4844.74
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
C3 release: r287 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1, D3D11-9.18.13.4195)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
