### ISSUE TITLE
undo after frame duplication not resetting sprite size

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-3-bugs#5547]
## Problem description

When working with sprites, duplicating a frame somewhere other than the end of the animation pushes all existing sprites along a frame, affecting their sizes. However, after undoing this frame duplication, the sprites do not return to their previous size prior to the frame duplication. I have attached a gif to show this in action.

![frame duplication](https://user-images.githubusercontent.com/46861823/159618902-91c80d59-b519-4257-a07e-9a2925572cfd.gif)

This can be a major source of pain when using sprites as static objects in a game world (for example, I have a single sprite for all trees in my game) as inserting a frame completely mucks up the sizes of every instance in the game and is not fixable using the undo command, meaning that the only choices at this stage are to close the project and load a previous version, or go through each instance and manually reset their size to the actual sprite size (would be great if there was a shortcut for this btw).

## Attach a .c3p

[frame duplication bug.zip](https://github.com/Scirra/Construct-3-bugs/files/8329524/frame.duplication.bug.zip)

## Steps to reproduce

1. duplicate a frame in the animation (not the last one)
2. Note how the other sprites have changed their size
3. use the undo command
4. note that, even though the sprites have returned to their previous frame, their sizes have not.

## Observed result

Sprites become deformed

## Expected result

Sprites should return to their size prior to the duplication of the frame. This is the case if the user adds a new frame to the end of the animation and then moves it to the front of the sequence. Ideally, it might even be better if instances retain their relative frame when one is inserted before it, rather than overriding their frame order.

## More details
I've had this happen a couple of times in a very large project and it can be a massive headache. At the very least, undo should fix the sizing issue.

While I know this may not have been the original intention when it comes to sprite animations (different size frames within a single animation), I've yet to find a more convenient way to store large collections of individual sprites.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Does this happen on the latest stable release or the latest beta?

**Comment by Ldwebster111** [comment]
> Does this happen on the latest stable release or the latest beta?

I'm using stable

**Comment by DiegoScirra** [comment]
Undoing will produce the expected results in the next beta.
