### ISSUE TITLE
HTMLElement: Set attribute, Why not separate 'Set' and 'Remove' mode

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5548]
## Problem description

HTMLElement has an action, Set attribute. There are two modes set Attribute or Remove attribute. So, why not separate them as 2 actions. 

![Snipaste_2022-03-23_13-16-57](https://user-images.githubusercontent.com/45864744/159628890-02b920a7-500d-4b33-814f-84cb0acccef3.png)

This is certainly not a reason to "make the page look simple", I don't think it is necessary.

## Steps to reproduce

1.
2.
3.

## Observed result

![Snipaste_2022-03-23_13-26-40](https://user-images.githubusercontent.com/45864744/159629983-d6c96ed0-0d94-4870-a45e-86dc952f4e94.png)

## Expected result

![Snipaste_2022-03-23_13-25-38](https://user-images.githubusercontent.com/45864744/159629884-d5b90f2b-dafe-451f-8b80-3c098a32226b.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is by design, just to reduce the number of very similar actions. There could be for example be separate actions for 'Set class', 'Toggle class', 'Remove class', and 'Set HTML', 'Set BBcode', 'Set plain text', and 'Clear content', 'Remove content' etc. Rather than have loads of almost identical actions with small variants between them, they've been condensed to fewer entries.

**Comment by XHXIAIEIN** [comment]
This just makes the page more cluttered.
- I removed something and changed it to another value, select from XX, how many times to match.
- I removed something thing.

**Comment by XHXIAIEIN** [comment]
So, By this design, why not merge the variables action. add value, set value, subtract value.

**Comment by AshleyScirra** [comment]
Software design is based on judgement, and this was what I thought was best. There are other side-effects too, like substantially increasing the number of strings translators have to translate. Fewer actions means fewer strings and less translation work, less and simpler code, less clogged user interface, etc.

**Comment by XHXIAIEIN** [comment]
merge different logics together, it will cause confusion in other languages. I reported this issues because I thought it was strange in zh-CN. As the case I mentioned above:
- I removed something and changed it to another value, select from XX, how many times to match.
- I removed something thing.

At present, it is the first case. If they are separated out, the second one will be more concise
