### ISSUE TITLE
cannot export/build apk

### ISSUE THREAD

**Issue by christianadiwijaya** [Scirra/Construct-3-bugs#5549]
Error: Platform 'android' found in config.xml... Migrating it to package.json
Discovered platform "android". Adding it to the project
Using cordova-fetch for cordova-android@10.1.0
Adding android project...
Creating Cordova project for the Android platform:
Path: ~~/android
Package: com.izos.megaforce
Name: Mega Force
Activity: MainActivity
Android target: android-30
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@10.1.0
Plugin 'cordova-plugin-applovin-max' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-splashscreen' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-file' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-fullscreen' found in config.xml... Migrating it to package.json
Discovered plugin "cordova-plugin-applovin-max". Adding it to the project
Failed to restore plugin "cordova-plugin-applovin-max". You might need to try adding it again. Error: CordovaError: Failed to fetch plugin cordova-plugin-applovin-max@1.0.8 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin ~~/URL.
CordovaError: Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cordova-plugin-applovin-max@1.0.8.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR! ~~/2022-03-23T06_38_29_852Z-debug-0.log
Discovered plugin "cordova-plugin-file". Adding it to the project
Failed to restore plugin "cordova-plugin-file". You might need to try adding it again. Error: CordovaError: Failed to fetch plugin cordova-plugin-file@6.0.2 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin ~~/URL.
CordovaError: Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cordova-plugin-applovin-max@1.0.8.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR! ~~/2022-03-23T06_38_30_459Z-debug-0.log

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.

The error looks related to a third-party addon `cordova-plugin-applovin-max`, so you may need to take it up with the addon developer.
