### ISSUE TITLE
[Tilemap] Tilemaps do not show properly

### ISSUE THREAD

**Issue by ephrisian** [Scirra/Construct-3-bugs#555]
## Problem description

When a Tilemap is being edited in C3, the tiles do not show properly. However when you run the game, the tiles show up properly.

This makes it very difficult to place tiles in C3.

## Attach a .c3p

https://www.dropbox.com/s/q0cu5j2tx4epd13/tilemap.c3p?dl=0

## Steps to reproduce

1. Create Tilemap
2. Select Tilemap and use the Open feature in the Tilemap view
3. Open the attached NewMap.tmx and select the attached sprite sheet
4. Press OK

## Observed result

The tilemap will show up wrong in the editor, but when you run it you will see it show properly.

## Expected result

Have the editor view match the end results

## Affected browsers

* Chrome: YES
* Firefox: NA
* Edge: NA
* Safari: NA

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
C3 release: r40

Local storage
Storage quota (approx): 7.7 gb
Storage usage (approx): 94 mb (1.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL indicates a major performance caveat. It is probably using software rendering.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
I am looking into this right no, can you upload the .tmx file and the corresponding tiles image? I think you forgot to upload those :P

**Comment by DiegoScirra** [comment]
Forget about my last comment, just noticed the files are inside the .c3p.

**Comment by DiegoScirra** [comment]
Fixed in r41.

**Comment by ephrisian** [comment]
They should be under the files in the capx
