### ISSUE TITLE
Time-based effects ignore object time scale

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#5550]
## Problem description

It appears that time-based effects such as warp and pulse ignore the time scale of the object they're applied to, utilizing only the game/system time scale instead. In other words, these effects "freeze" if the game/system time scale is 0, regardless of the time scale of the object they're applied to.

## Attach a .c3p

[timeScaleEffectIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/8330965/timeScaleEffectIssue.zip)

## Steps to reproduce

1. Preview the project
2.
3.

## Observed result

The "Warp Object" effect on the sprite object is frozen despite its timescale being 1.

## Expected result

The "Warp Object" effect to wiggle the sprite object because its timescale is 1.

## More details
I'm not sure this is actually a bug instead of the indended effect, but either way this prevents us from using any time-based effects in, say, pause menus / subscreens, or could lead to unintended results when the game time scale is otherwise altered.

**Affected browsers/platforms:** Chrome

**First affected release:** Probably always like this but tested in 285.3

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 99.0.4844.82
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
C3 release: r285.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 117 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1179)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is an interesting catch. The solution is fairly complicated though: it means tracking the time for individual instances, which if done naively would potentially add a large performance overhead. So I've added a per-instance clock for tracking the time used for effects only where instances both use effects and have an altered timescale. That's implemented for the next beta and should do the trick.
