### ISSUE TITLE
Nag screen pops up every 2 hours, despite being a paying customer

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#5552]
r286 introduced a nag screen that people are forced to click on every single day, every 2 hours.
This is a really intrusive move to make, not a good direction for the program. 

It may be coming from a good place to encourage to do what you believe is best for people, but it's not right to force and nag people constantly like this.

Please remove it, or make it optional, or let people change the interval, or let them never see it again. (Not that it matters, but I already take breaks every 20 minutes, yet it still interrupts my work to nag me.)

**Comment by AshleyScirra** [comment]
Looks like a cross-post of this suggestion: https://construct3-21h2.ideas.aha.io/ideas/C321H2-I-252

Is it really that much trouble to click OK once every 2 hours?

**Comment by szabeszg** [comment]
> Is it really that much trouble to click OK once every 2 hours?

I think deciding when to take a break should be our own decision. I get the intention, still, treat us as adults, please. If you decide to keep it, at least make it possible for us to opt out.

BTW, I also have my own way of reminding myself to take a break, I have no need for an app to intervene.

**Comment by brushfe** [comment]
> Is it really that much trouble to click OK once every 2 hours?

The other way to ask this, "is it worth irritating your users every two hours?". The spirit of the prompt is great, but it's a constant annoyance if it's not a useful reminder. What benefit does Scirra get in exchange for the user's degraded experience?

It should be an option for those who appreciate the reminder.

**Comment by dop2000** [comment]
(https://heeris.id.au/2013/this-is-why-you-shouldnt-interrupt-a-programmer/)[This is why you shouldn't interrupt a programmer]

**Comment by Interinactive** [comment]
Having it as an option in settings would be better.

I often do take breaks and leave my computer on in the meantime, it's annoying. Particularly when I'm deep into something.

**Comment by AshleyScirra** [comment]
This was cross-posted as a suggestion, and as it's by design / not a defect, we'll track it as a suggestion here: https://construct3-21h2.ideas.aha.io/ideas/C321H2-I-252
