### ISSUE TITLE
expression autocomplete not working when pasting parameters

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5554]
## Problem description

Expression autocomplete sometimes doesn't work, When I cut and paste a parameter. It doesn't reappear unless I delete the pasting   parameter and type it manually  or re typing ` ( ` and `,`.

![2](https://user-images.githubusercontent.com/45864744/159750950-8e9441f1-0ff6-4eff-8be9-dc717a4bd0df.png)

![3](https://user-images.githubusercontent.com/45864744/159750875-d19e6b4c-3316-4336-8c3b-ed76f0c1afc2.png)

## Attach a .c3p
In any project, any expression dialog.  Here is a quick paste. You can edit the expression dialog of 'Go to layout'  to continue.
`+ System: On start of layout  -> System: Go to layout ""`

```
{"is-c3-clipboard-data":true,"type":"events","items":[{"eventType":"block","conditions":[{"id":"on-start-of-layout","objectClass":"System"}],"actions":[{"id":"go-to-layout-by-name","objectClass":"System","parameters":{"layout":"\"\""}}]}]}
```

## Steps to reproduce
Let's use the `tokenat("A|B|C", "|", 0)` expression as an example.  
1.  Type `tokenat(`.  appeared autocomplete when typing `(`
2.  Type `"A|B|C",` continue.  appeared autocomplete when typing `,`
3.  Now, Select this parameter and Ctrl + X to clip. --> `tokenat(`
4.  Ctrl + V.  --> `tokenat("A|B|C",`
5.  Then, even if you continue to enter the parameters, and then enter the `,`, it will no longer prompt for expression autocomplete.
6.  Finally, delete all parameters and re type the "(" , the expression autocomplete reappears. --> `tokenat(`

## Observed result

![3](https://user-images.githubusercontent.com/45864744/159750875-d19e6b4c-3316-4336-8c3b-ed76f0c1afc2.png)

## Expected result

![2](https://user-images.githubusercontent.com/45864744/159750950-8e9441f1-0ff6-4eff-8be9-dc717a4bd0df.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

It does not have to be pasted to reproduce. If you enter the wrong symbol, such as using the symbol of CJK, and delete parameters and retype it, it will also reproduce.  Unless go back to the expression position and retype '(' 

<details><summary>View details</summary>

```
Platform information
Browser: Chrome
Browser version: 99.0.4844.74
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36
C3 release: r287 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 96 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Super with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9649)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
```

</details>

**Comment by AshleyScirra** [comment]
There are lots of cases the parameter tips don't appear, or track it wrong. Parsing expressions for these cases is really complicated: incomplete expressions are invalid and so the expression parser can't parse them and so we can't use that to identify what you've typed. So currently it only supports tracking parameter tips as you type commas after a `(`. For example even if you just click away and click back and keep typing, sometimes the parameter tip does not come back. Or if you type `tokenat("a,b"` it incorrectly thinks you've moved on to the next parameter because you typed a comma, but really it was in a string.

I think these cases are too difficult and time-consuming to implement that I don't think it's worth the trouble. It just makes a best-effort to track as you type but more complicated cases are a real headache. If you think this is important you can file a feature suggestion for it.

**Comment by XHXIAIEIN** [comment]
I think it's possible to provide a shortcut key to display the parameters required by the expression. Or, just type `,` to show instead of just `(`
