### ISSUE TITLE
new line missed while copying and pasting within the array editor

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-3-bugs#5556]
## Problem description

when a cell containing a text with a newline (carriage return, aka SHIFT+RETURN) is copied and pasted, the text after the new line is missed.
Text with the newline is also not shown till the cell is edited.

## Attach a .c3p
[bug newline array.zip](https://github.com/Scirra/Construct-3-bugs/files/8336580/bug.newline.array.zip)

## Steps to reproduce

1. create a new array file
2. type some text in the cell and type SHIFT+RETURN to create a second line, type the text of the second line
3. exit from the editing of the cell
4. click the cell with the text to select the cell (do not double click)
5. press CTRL+C to copy the cell
6. select an empty cell
7. press CTRL+V to paste the cell

## Observed result

the pasted cell does not contain the lines after the newline
![moNHSIcaj3](https://user-images.githubusercontent.com/58107632/159794491-b34d37ce-2a4f-49e3-acdc-c1623eb812ed.png)
![zStimZmdJq](https://user-images.githubusercontent.com/58107632/159794500-112fa56e-4510-4f1c-a7ea-79a21c4eb8b3.png)
![bJdT7cxL5j](https://user-images.githubusercontent.com/58107632/159794511-79cf78b0-b442-4e62-8485-df8611ddc915.png)
![sOCNcRLYap](https://user-images.githubusercontent.com/58107632/159794518-ec4f8f37-34f2-4eaf-b517-faac05bf5793.png)

## Expected result

copy and pasting of the cells should contains everything
rendering of the cells should take care of the new line characters as well.

## More details
Windows 10
C3 R287

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
These issues will be fixed in the next beta.

**Comment by rraffo** [comment]
great! tx
