### ISSUE TITLE
Video playback: WebGL: INVALID_VALUE: texImage2D: The source data has been detached.

### ISSUE THREAD

**Issue by Interinactive** [Scirra/Construct-3-bugs#5557]
## Problem description

Video playback often blinks / disappears and this error shows in the console:

**WebGL: INVALID_VALUE: texImage2D: The source data has been detached.**

I have been testing video in C3 for maybe 1-2 hours a day, every day for the past 6 months, and immediately noticed this happening multiple times since opting in to r287 (which contains a separate fix I need in order to progress with work)

## Attach a .c3p

https://www.dropbox.com/s/msged5wmogzmtuw/video_test.c3p

## Steps to reproduce

1. Either wait a while, as it appears to occur at random
2. Resize the window or go from window to fullscreen while video is playing, it happens almost 100% of the time
3. Open the browser inspector while video is playing as that tends to trigger it as well

## Observed result

https://youtu.be/eQ3VWhV2YJ8

The video disappears, blinks and reveals the content of the layers behind it. The associated error in the console is:

**WebGL: INVALID_VALUE: texImage2D: The source data has been detached.**

## Expected result

Uninterrupted video playback without error

## More details

**Affected browsers/platforms:** 

**First affected release:** Worked without issue up until R285.3, started occurring in Beta r287

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 99.0.1150.46
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46
C3 release: r287 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 572 gb
Storage usage (approx): 111 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1215)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
We changed the video playback code to try to improve #5524, but it looks like part of the updated code was incorrect. I've made some more improvements so it should be working better in the next beta.
