### ISSUE TITLE
Compare variable dialogue panel - resizing makes buttons overlap

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#556]
## Problem description

I've found this happening on my laptop and I'm not sure if this is strictly related to the dark theme or not.
When I resize the Compare parameter dialogue the buttons overlap and the location is kinda weird.

## Attach a .c3p

![image](https://user-images.githubusercontent.com/7268697/27509447-d27e01ac-5905-11e7-9361-51d4ebcbafff.png)

## Steps to reproduce

1. make new blank project
2. add a global var
3. compare it and resize the panel

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r40

Local storage
Storage quota (approx): 9.3 gb
Storage usage (approx): 305 mb (3.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
It happens with the default theme too, but just with adjacent placement instead of overlapping. It's really hard to get UI items to fit on tiny layouts like that, not sure much can be done other than tweaking the spacing.

**Comment by AshleyScirra** [comment]
So, coming back to this after a while, and without redesigning the whole dialog layout the obvious thing to do is space out the rows if buttons wrap so it looks a bit nicer. Normally this is really awkward but there's a lovely new CSS property `row-gap` that takes care of it beautifully:

![row-gap](https://user-images.githubusercontent.com/768723/67972287-450d1780-fc06-11e9-980e-440a9ea7c6d3.png)

However the caveat is... it's only supported in Firefox right now. It's a [very highly starred issue on the Chrome tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=762679) though - in the top 25 most starred open issues - which suggests it's likely Google will implement it at some point. Given it's a simple and effective change to the CSS and side-steps a lot of awkwardness, I think this is the best we can do for now - and sooner or later Chrome will pick up support for row-gap which means it will start working the same as Firefox as soon as they ship that.
