### ISSUE TITLE
"Sine+Physics" disables changing the Image point and uses the standard location.

### ISSUE THREAD

**Issue by ConstructBugsReport** [Scirra/Construct-3-bugs#5560]
![Screenshot_2](https://user-images.githubusercontent.com/75397893/160056588-462ef3ce-0d2f-4571-8f5b-b813598d6855.png)
The change of image point 0 is not fixed if it is moved anywhere other than the center.

When you use two behaviors "Sine+Physics" to change the point point does not solve the problem.
I want to make a Physics-based pendulum+Sine whose Imagepoint is at the position "Y=0" 

But the system does not understand this requirement if physics is present.

**Comment by AshleyScirra** [comment]
Please follow the bug report guides otherwise it's impossible for us to help.
