### ISSUE TITLE
Z order of 2d sprites always above 3d object if 2d sprite z elevation is greater than 0.

### ISSUE THREAD

**Issue by tyler61084** [Scirra/Construct-3-bugs#5562]
## Problem description

So as the title states placing a 2d sprite at a z elevation greater than 0 forces the sprite to the top of the z-order. I need it below my 3d objects to remove the white clipping due to the order that construct creates everything in. I'm not fully sure if this is a glitch or not but I did find it very strange that any 2d object with a z elevation greater than 0 forces it to the top of the z-order.

## Steps to reproduce

1. add sprite
2.add 3d object
3. set sprite z elevation to anything greater than 0
4. right-click open z-order panel

## Observed result

sprite is forced above 3d object

## Expected result

still, allow player to change z-order

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is by design. Z elevation takes precedence over Z order.
