### ISSUE TITLE
Platform behavior/Jumpthrough, another weird interaction (I'm sorry)

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#5563]
## Problem description

I found, once again, another very weird interaction thing with the platform behavior and jumpthrough. I know you said in the past how complicated it is and there's many edgecases, but I think this can't even be considered one. Seems like the platform behavior gets confused if the player is standing on a jumpthrough overlapping another jumpthrough. Sorry for the headache :V

The setup is just this
![image](https://user-images.githubusercontent.com/31101309/160162484-f62da40c-16c3-4211-a017-295d617ce03b.png)

Simply walking right causes this
![image](https://user-images.githubusercontent.com/31101309/160162558-3010dc34-2bfe-4d40-8556-679e705ad2b5.png)

## Attach a .c3p

[onfloor.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8352307/onfloor.c3p.zip)

## Steps to reproduce

1. Walk right

## Observed result

Player sinks into the floor (jumpthrough) and starts walking in the air

## Expected result

The player to walk up normally.

## More details
Does not happen if the bottom object is a solid rather than a jumpthrough.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 99.0.4844.82
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
C3 release: r287 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 4 gb (3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9709)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
As [noted in the manual](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/jump-thru), jumpthrus do not support slopes.

**Comment by Wackytoaster** [comment]
Oh ok, I can work with that I think.
