### ISSUE TITLE
Tiled BackGround Load From URL BUG

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-3-bugs#5568]
When I load the Tiled BG from URL it doesn't retain the Image as the next instance that I spawn from the same Sprite object it will load the old Image instead.

It should retain the New Image that was last loaded from URL the same as the Sprites do.

[1-TiledBG Load From URL BUG.zip](https://github.com/Scirra/Construct-3-bugs/files/8357074/1-TiledBG.Load.From.URL.BUG.zip)

1. Run the Project 
2. Wait 3 seconds
3. Watch the new Tiled BackGround Spawned

## Observed result

The new Tiled Background spawned it didn't use the new image that we loaded from URL 

## Expected result

When we load an image from URL it should retain the image for the whole game session unless I change it again as the Sprites objects do, this has to be consistent the same as all objects that load from URL and retain the Image for the whole session, so Tiled Background should be no different. It will be really unlogical if this is done by design and is not a bug as is a waste of performance if every time I spawn a Tiled BG I have to load From URL.

## More details

Chrome

r268
r287

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 99.0.4844.84
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
C3 release: r287 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 336 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6663)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Note that Tiled Background works slightly differently to sprites: Tiled Backgrounds can switch to a per-instance image, whereas when Sprites load an image they overwrite one of the animation frames shared by all instances.

**Comment by Tarek200** [comment]
> This is currently by design. Note that Tiled Background works slightly differently to sprites: Tiled Backgrounds can switch to a per-instance image, whereas when Sprites load an image they overwrite one of the animation frames shared by all instances.

Hah this is really hard braking, you don't how much of a problem this causes us, I'm not even exaggerating. I understand you did that design for X reason but why wouldn't you add the option that we could choose reusing the image as the sprites object do? which will be in line with how Construct its been working for many years. If you think about it doesn't make much sense not to have that option as most luckily when devs will need to use more than one Instance of the same TileBG object for any reason they will most luckily want to reuse the same image as its in my case. You are forcing us to load the New Images for each instance which will be treated as individuals and that will add more RAM so if the image is big we are screwed like in our case, this is really unnecessary as you could have avoided it and not limiting us by the current design.

Could you please add an option in the TiledBG properties panel to select if we want to use any instance of this TiledBG as an ("Independent" or "Reuse the Images as the sprites do")? 
This will really help us a lot as right now we don't have much help with Memory management and we have a lot of issues in older Android phones which it crashes. We have been working really hard with all the limitations that we encounter in Construct but we still didn't give up so we will really appreciate it if you give us a hand here easing our burden. Not sure how much will cost you to add this mini-setting but it sounds like it could be easy to add and the gain will be huge.

Please consider adding this small setting

it could be added here:
![Imagcce 2](https://user-images.githubusercontent.com/41597700/160449104-072f8afe-27dc-458a-9169-139653a47ba7.png)

1-switch to a per-instance image
2-Dont switch to a per-instance image
