### ISSUE TITLE
Collision Polygon refresh

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#557]
## Problem description

When you work on a collision polygon of an animation in the Animations editor, and then you select another animation with another resolution, the collision polygon stay the same.
You must zoom or dezoom to see the real Collision Polygon

## Steps to reproduce

1. Create an animation 64*64
2. Create another animation 128*128
3. Clic on edit collision polygon and go to the other animation

## Observed result

You can see the collision polygon of the other animation

## Expected result

The collision of the current animation

## Affected browsers

* Chrome: yes

**Comment by Picoti** [comment]
It's the same problem with the image point.

**Comment by sizcoz** [comment]
Yep, same here, almost unworkable, also slow response time compared to c2

**Comment by DiegoScirra** [comment]
Fixed in r41.
