### ISSUE TITLE
Crashes while editing a instance variable. r287

### ISSUE THREAD

**Issue by hoyhoyhoyyy** [Scirra/Construct-3-bugs#5573]
## Problem description

When editing an instance variable from number to a string construct crashes r287

## Attach a .c3p

[Crash.zip](https://github.com/Scirra/Construct-3-bugs/files/8359767/Crash.zip)

## Steps to reproduce

1.r287 Create a sprite and give it an instance variable with number type and click ok.
2.Double click and edit the same variable and change it to string click ok.
3.Crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by dop2000** [comment]
Doesn't crash for me.

**Comment by hoyhoyhoyyy** [comment]
> Doesn't crash for me.

Uploaded cp3. Try changing the sprites instance variable from a Number to a String and press ok. It might be only me then if it doesnt crash.

**Comment by dop2000** [comment]
@hoyhoyhoyyy  You are right! It does crash.

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r287/main.js, line 864, col 78
Message: Uncaught TypeError: expected number
Stack: TypeError: expected number at Function.R.Lg (https://editor.construct.net/r287/main.js:864:84) at CCG.$g.g.J.zbb.H4 (https://editor.construct.net/r287/main.js:1330:226) at CCG.$g.g.J.zbb.I4 (https://editor.construct.net/r287/main.js:1327:185) at CCG.$g.g.J.zbb.JA (https://editor.construct.net/r287/main.js:1338:17) at Object.CCG.oh (https://editor.construct.net/r287/main.js:373:420) at d.Nsa (https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:105:147) at bd.ws.$R (https://editor.construct.net/r287/components/bars/propertiesBar/propertiesBar.js:93:455) at bd.ws.LXa (https://editor.construct.net/r287/main.js:1072:240) at bd.ws.mjb (https://editor.construct.net/r287/main.js:1072:370) at QZb (https://editor.construct.net/r287/main.js:1072:143)
Construct 3 version: r287
URL: https://editor.construct.net/r287/
Date: Mon Mar 28 2022 16:17:15 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 19.8 s

Platform information
Browser: Chrome
Browser version: 99.0.4844.82
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.3958333730697632
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
C3 release: r287 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
