### ISSUE TITLE
Can't build Android Debug APK (Error message from build service)

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#5576]
## Problem description
When I try to build for Android I get an error message.
It worked yesterday with the same version of C3. Not sure if I should report here or in forums.

## Steps to reproduce

1. build for android (I tried debug apk)

## Observed result
error message and build fails

## Expected result
no error

## More details

Error: Platform 'android' found in config.xml... Migrating it to package.json
Discovered platform "android". Adding it to the project
Using cordova-fetch for cordova-android@10.1.0
Adding android project...
Creating Cordova project for the Android platform:
Path: ~~/android
Package: de.bl4cksh33p.borderlands
Name: Wonderlands & Borderlands App
Activity: MainActivity
Android target: android-30
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@10.1.0
Plugin 'admob-plus-cordova' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-consent' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-device' found in config.xml... Migrating it to package.json
Plugin 'construct-mobile-export' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-purchase' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-inappbrowser' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-x-socialsharing' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-file' found in config.xml... Migrating it to package.json
Plugin 'construct-mobile-rate' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-splashscreen' found in config.xml... Migrating it to package.json
Discovered plugin "admob-plus-cordova". Adding it to the project
Installing "admob-plus-cordova" for android
Subproject Path: CordovaLib
Subproject Path: app
Discovered plugin "cordova-plugin-consent". Adding it to the project
Installing "cordova-plugin-consent" for android
Subproject Path: CordovaLib
Subproject Path: app
Discovered plugin "cordova-plugin-device". Adding it to the project
Installing "cordova-plugin-device" for android
Discovered plugin "construct-mobile-export". Adding it to the project
Installing "construct-mobile-export" for android
Discovered plugin "cordova-plugin-purchase". Adding it to the project
Installing "cordova-plugin-purchase" for android
Subproject Path: CordovaLib
Subproject Path: app
Discovered plugin "cordova-plugin-inappbrowser". Adding it to the project
Installing "cordova-plugin-inappbrowser" for android
Discovered plugin "cordova-plugin-x-socialsharing". Adding it to the project
Installing "cordova-plugin-x-socialsharing" for android
Installing "es6-promise-plugin" for android
Subproject Path: CordovaLib
Subproject Path: app
Discovered plugin "cordova-plugin-file". Adding it to the project
Installing "cordova-plugin-file" for android

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

"<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.

Discovered plugin "construct-mobile-rate". Adding it to the project
Installing "construct-mobile-rate" for android
Subproject Path: CordovaLib
Subproject Path: app
Discovered plugin "cordova-plugin-splashscreen". Adding it to the project
Installing "cordova-plugin-splashscreen" for android

Invalid character in entity name
Line: 3
Column: 42
Char:

**Affected browsers/platforms:** 
N/A

**First affected release:** 
r285.3 (stable)
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 99.0.4844.84
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.2000000476837158
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
C3 release: r285.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 158 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0, D3D11-26.20.12028.2)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by TheBl4ckSh33p** [comment]
Seems it was the "&" in the app name (Wonderlands & Borderlands App). The C3 Editor did not says its a "bad" or forbidden symbol. When I changed it to "and" it worked.

**Comment by fredriksthlm** [comment]
It clearly states in your log:  **Invalid character in entity name**

**Comment by AshleyScirra** [comment]
This is a bug in Cordova: https://github.com/apache/cordova-android/issues/1380
It should be fixed in the next Cordova release.
