### ISSUE TITLE
Vibrate function in Browser object does not work in Xcode

### ISSUE THREAD

**Issue by driesdriessen** [Scirra/Construct-3-bugs#558]
## Problem description

The Vibrate function seems not to work in a project exported to iOS. The project builds without errors, the app starts up fine, but the Vibrate function does not work.  

## Attach a .c3p

C3 project
[test xcode build.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1100611/test.xcode.build.c3p.zip)

iOS/Cordova Export 
[test xcode build.cordova.zip](https://github.com/Scirra/Construct-3-bugs/files/1100629/test.xcode.build.cordova.zip)

## Steps to reproduce

1. Include the Browser object in a project 
2. Create an event that triggers the Vibrate function with a valid string 
3. Export to iOS/Cordova
4. Create an ad hoc build and install the app (.ipa) on an actual device using itunes 

## Observed result

The app starts up as expected, but the vibrate function does not work  

## Expected result

The app starts and the vibrate function makes the device vibrate

## Affected browsers

n.a.

## System details

iOS 10.11.6
xcode 8.2.1
Chrome 58.0.3029.110 (64-bit)
Construct3 r40

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r40

Local storage
Storage quota (approx): 6.8 gb
Storage usage (approx): 218 mb (3.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 5000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Note Safari does not support vibration: http://caniuse.com/#feat=vibration

...but I suppose we can use a Cordova polyfill in this case.

**Comment by shortercode** [comment]
Ah I wasn't aware safari didn't support the vibration API, thanks @AshleyScirra! I've just had a quick look and there's a plugin by the cordova team which does provide vibration... but it's pretty limited on iOS. It doesn't allow the use of patterns, cancelling or even a duration.

This seems to be an inherent limitation on the platform until iOS 9. There's a new API in iOS 10 that allows access to the "haptic engine" (iPhone 7 only), but it still doesn't seem to give much control ( introduces 3 "styles" of "impact").

@driesdriessen in your use case would a single short vibration work? As a warning it seems that firing these in rapid succession seems to be criteria for app store rejection.

**Comment by driesdriessen** [comment]
Hi Ian,
I am creating an app for visually impaired people. I want to use short vibrations to give tactile feedback if the user is touching an object (similar to how the home button works on the iPhone 7).
So a single short vibration could work.
Thanks for your support.
Dries.

**Comment by shortercode** [comment]
Sounds like a good project! I think the newer haptic feedback API would probably work better for your use case but the minimal support it offers is a problem. 

I think a good plan of action would be:

1. Add cordova plugin to enable simple vibration on iOS
2. Consider separate C3 plugin for the haptic feedback API

A new C3 plugin, even a simple one, is a bit of a timesink to consider right now but it might prove to be a good addition for the future.

**Comment by driesdriessen** [comment]
Hi Ian,

Sounds like a plan.

Thanks,

Dries

Op 27 jun. 2017 om 13:26 heeft Iain Shorter <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Sounds like a good project! I think the newer haptic feedback API would probably work better for your use case but the minimal support it offers is a problem.

I think a good plan of action would be:

  1.  Add cordova plugin to enable simple vibration on iOS
  2.  Consider separate C3 plugin for the haptic feedback API

A new C3 plugin, even a simple one, is a bit of a timesink to consider right now but it might prove to be a good addition for the future.

**Comment by shortercode** [comment]
Okay sorry this has been a little while, I was away most of last week. Just tried a simple project with the existing runtime and vibration does work on iOS. At least in it's limited form. 

Test project: [Angry Face.zip](https://github.com/Scirra/Construct-3-bugs/files/1124801/Angry.Face.zip)

Sprite is a little random... We end up drawing a lot of test sprites.

But anyway if you export that for iOS with the vibrate permission enabled, then compile with xcode onto a device you should have a face that vibrates when poked. The time set in the expression doesn't really matter, as iOS will ignore it anyway.

**Comment by driesdriessen** [comment]
Hi Iain,

Strange - on my iphone 7 it does not work. I've exported to IOS/Cordova from R44, compiled (the usual warnings but build succeeds). Installed the ad hoc build on my phone via iTunes. But unfortunately the vibrate does not work.

As an experiment I've added Flash behaviour to see if the app responds. It responds to a tap so it recognizes the touch. but no vibrate :-(

Hopefully you can investigate further...

Thanks,

Dries.

**Comment by shortercode** [comment]
That's odd... Perhaps it's related to the newer version of iOS, or that your on a device that supports haptic feedback. I'm testing on a 4s running 9.3.5, so there's room for some differences I guess.

I had heard from some people that having having the device silenced would prevent the vibrate plugin from working. In my testing it only seemed to do this if the "Vibrate on Silent" option in sounds was disabled. Does that help?

**Comment by driesdriessen** [comment]
Hi Iain,
It was indeed the "Vibrate on Silent" option. The vibrate now works. I'm gong to experiment how the fixed vibrate time works for my app. 

The separate C3 plugin for the haptic feedback API will still be valuable. Is this something the Construct team will be developing?
Thanks,
Dries.

**Comment by driesdriessen** [comment]
Hi Iain, 

The vibrate option works, but it has a delay and does not feel very precise.

Does the C3 team plan to develop the separate C3 plugin for the haptic feedback API that you mentioned, or is there one I can purchase? I am not sure I have the skills to develop this myself.

Thanks,

Dries.

**Comment by shortercode** [comment]
Hi @driesdriessen sorry about the radio silence, I was away on leave last week.

I guess I'm glad that you managed to get vibration working, shame it doesn't work "well enough" though.

We haven't really discussed the new plugin internally yet, beyond some passing comments. Best guess is that we'll probably do it, but it'll be a long way down the priority list. So it could be several months before a plugin appears. I'm not aware of any third party options, but I don't think there's one that will work with the build service ( as I have to whitelist native components for security reasons, and nobody has asked me why it isn't working ).

It's a shame, as I don't think the time requirement is very high. I had a look around and found a suitable library to base the plugin on, so it just needs some wrapper code. Depending on how much accidental overtime I end up doing this week I might use some personal time to work on the plugin.

If possible do you think you could review these links to tell me if you think it's suitable / useful ?

[cordova plugin ](https://github.com/EddyVerbruggen/cordova-plugin-taptic-engine)

[haptic guidelines](https://developer.apple.com/ios/human-interface-guidelines/interaction/feedback/#haptics)

You might be able to find an iOS demo app to try these effects out I guess?

**Comment by shortercode** [comment]
Yeah I think we'll stick clear of the undocumented part, doesn't sound that useful anyway. They will be using the native Apple API, but unless they are cordova apps they won't be using this wrapper library.

Nothing to test right now, I'll ping you on here with any progress.

**Comment by driesdriessen** [comment]
Dear Iain,
You probably did not find time to look at this any further. Can you please give me some guidance on how to try writing a wrapper so I can try to do this?
Thanks,
Dries.

**Comment by shortercode** [comment]
Hi @driesdriessen I'm afraid I didn't no. I've done one ( very simple ) unofficial plugin in the last year and I haven't had time to keep up with issues on that, so I'd rather not take on a second at this point.

If your going to look into this yourself a good starting place is [the addon sdk manual](https://www.construct.net/gb/make-games/manuals/addon-sdk).

To add a cordova plugin you should look into [the specifying dependencies section](https://www.construct.net/gb/make-games/manuals/addon-sdk/reference/specifying-dependencies) specifically the section titled **cordova plugin dependencies**.

I've done a security review of "cordova-plugin-taptic-engine" version "2.0.0" and added it to the build service whitelist for you.

In terms of actual code you would want to create some actions that call the library, doing something like

```
if (window["TapticEngine"]) {
    window["TapticEngine"]["impact"]({
        "style": "heavy" // light | medium | heavy
    });
}
```

Given that this issue had no official action I'm going to close this now, but if you have any issues with the build service feel free to create a new issue.

**Comment by therealPaulPlay** [comment]
I made a [plugin](https://www.construct.net/en/make-games/addons/923/taptic-engine-vibrations-c3) that adds this cordova plugin as well as multiple actions for using it inside of construct 3.
