### ISSUE TITLE
Wrap Selection is broken when snapping to grid is enabled

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5585]
## Problem description

If I have several composite objects and I want to align them evenly on the grid, there is no way to do this. Even if I wrap the selection, when I try to move it, each individual object is snapped to the grid:

![image](https://user-images.githubusercontent.com/36763350/160968638-d62ca57e-b258-42e7-8001-52e42bc4c525.png)

## Attach a .c3p

https://www.dropbox.com/s/x5zxp0lwb1zs813/wrapGrid.c3p?dl=0

## Steps to reproduce

1. Enable "Snap to grid"
2. Select one human, wrap the selection
3. Try to move it.

## Expected result

I expect "wrap selection" to keep the objects together.

## More details

The same happens if you try to move an hierarchy with Select Mode set to "All" or "Wrap".

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 99.0.4844.84
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.3958333730697632
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
C3 release: r288 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 405 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.8681)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's not clear to me how this should work. If you have a wrapped selection with lots of objects that do not align to a grid, and then move it with snap to grid enabled, how should it work out where to position them? Does it pick one instance to snap and then move everything with that? But then which instance should it pick? There is no particular reason to choose one instance over another. So rather than try to solve that, the current approach just snaps everything.

**Comment by simonpaulkeating** [comment]
As far as objects with a hierarchy are concerned; I think it should pick the parent and do all the aligning/snapping from the parents origin.

With a wrap all selection and multiple none hierarchical objects selected I would expect the corners of the wrap all selection bounding box to be the thing that snaps to the grid. Failing that it could be the center point of the bounding box. I think the current method is not expected behavior nor commonly required.

**Comment by simonpaulkeating** [comment]
You can also see my forum post [here](https://www.construct.net/en/forum/construct-3/how-do-i-8/align-multiple-characters-168672#forumPost1066336) regarding aligning with hierarchical objects which includes an image of the issue.

**Comment by AshleyScirra** [comment]
You can wrap selection for multiple hierarchies though. Then which should it snap? It's the same problem.

I think children of hierarchies could be treated differently, but that's not the problem described in this bug report. If you think that should be handled differently I would advise to file a separate report for that, as it's a slightly different case to the one presented here.

**Comment by dop2000** [comment]
>  Does it pick one instance to snap and then move everything with that? But then which instance should it pick?
@AshleyScirra  It can pick the instance which is clicked and being dragged, and snap its origin point to the grid. Or it can snap the center of the wrapped selection. Either way will be much more useful than the current behavior. We can then disable snapping to the grid, select all groups of objects (all three man in my example screenshot) and adjust their position on the layout if needed.

**Comment by Wackytoaster** [comment]
I agree that the current behavior is not exaclty useful. I found that holding Alt and dragging temporarely disables the snapping which helps a little, but if you want to align something to the grid, tough luck.

**Comment by AshleyScirra** [comment]
The thread you linked to actually describes a different case of this involving hierarchies. The case described here does not involve hierarchies. It's also worked like this for years - possibly all the way back to Construct 2 - and I am very wary of changing such long-standing functionality. It seems reasonable that lots of people could actually rely on the current behavior. For example it provides a quick way to snap lots of unaligned objects. And changing it like you suggest has its own problems: there could be lots of overlapping instances, and so if you try to "anchor" the movement to "the clicked one", then the user actually has no easy way to control which one they want that to be if it is covered by another object.

If we fixed the issue specifically for hierarchy children, that seems reasonable and would solve the problem described in the thread. But it would not change how this case works when there is no hierarchy. Perhaps that is a reasonable compromise though? Your example looks like a natural cause to use hierarchies anwyay: each body part could be a child of the main body segment.

**Comment by dop2000** [comment]
> For example it provides a quick way to snap lots of unaligned objects.
You can quickly snap lots of objects by simply selecting them, don't need to wrap. But if you wrap the selection, then I believe it should move as one object, not break into pieces.

Fixing this behavior for hierarchies will certainly help, but I not always use hierarchies when I need to group objects. Sometimes they are in the same container, sometimes not connected at all. One such example is UI elements, for example a button consisting of 9patch frame + icon + text. I often need to evenly align several buttons and this simple task may take a lot of time..

**Comment by AshleyScirra** [comment]
I've fixed the problem described in the forum thread relating to hierarchies for the next beta. However the issue in this report is more complicated, and lacks a good way to define which the "anchor" instance is. This is obvious with hierarchies, as the hierarchy root is the instance to move everything with. However when using a multiple selection everything will be positioned independently. For this purpose, a wrapped selection is not different to a normal multiple selection, and so will work the same.

I don't think there's a good usability solution to trying to identify the "anchor" instance in a wrapped selection; the choice seems pretty arbitrary as there is not any hierarchy inside a wrapped selection, it's just another way to group a multiple selection. Given it will now work for hierarchies which can also be used for wrapped selections, maybe that is good enough anyway. I'd advise to track any further proposed changes for wrapped selections as suggestions, but I'm not convinced there's a good way to solve the anchor problem in that case, and hierarchies already solve that problem.
