### ISSUE TITLE
Timer on global layer executed multiple times?

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#5589]
## Problem description
I have a sprite with a timer, set as global object. On Start of layout if no times runs a timer should be started + code executed. But its executed multiple times while the timer is running when my timer object (sprite) is on a global layer. Not sure if a bug or if I should not put a global object on a global layer.

PS: In debug mode all timer names are in lowercase, not how I wrote them.

## Attach a .c3p
[GlobalTimerOnGlobalLayerStartingMultipleTimes.zip](https://github.com/Scirra/Construct-3-bugs/files/8390063/GlobalTimerOnGlobalLayerStartingMultipleTimes.zip)

## Steps to reproduce

1. add a timer to a object like sprite, set object to be global
2. put global object on a global layer (gui layer for example)

## Observed result
The actions are executed even if the timer is already running. often multiple times in my app (only once in the demo project). Does it create a new copy for each layout? But the timer continues to count up in debug view and is not restarted or ended.
But the code should prevent actions executed while a timer is running.

## More details

Code I used:
+ System: On start of layout
+ GlobalTimers: [X] Is Timer "MyTimer" running
-> GlobalTimers: Start Timer "MyTimer" for 30 (Once)
-> Browser: Alert "Starting 30s Timer"

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
r285.3
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 100.0.4896.60
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.2000000476837158
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36
C3 release: r285.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 167 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is not a bug, but is a confusing result based on the different uses of the term "global".

"Global layers" basically mean "automatically copy and paste the content of this layer on to other layouts". When you change layouts, it will destroy all objects on all layers, then create a new set of objects for the new layers on the new layout, which may include an exact copy of objects from a global layer.

In addition to that, you enabled "Global" on the sprite object. This setting basically means "don't destroy this object when changing layout". Then that has been placed on a global layer. So you've ended up with an object that is created on every layout using the global layer, and is never destroyed.

What you want to do is move that sprite object on to a non-global layer, so it is only ever created once and lasts between layouts.

**Comment by TheBl4ckSh33p** [comment]
Thanks. Adding the global sprite to the first layout on a normal layer fixed it. 👍
