### ISSUE TITLE
Crash when changing Z order in Z Order bar

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#559]
## Problem description

Construct crashes when the Z order of an object is changed in the Z Order bar.

## Attach a .c3p

[ZOrderBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1100646/ZOrderBug.zip)

## Steps to reproduce

1. Add two or more objects to a layout.
2. Right-click on one of them and choose Open Z Order Bar.
3. Drag and drop any object to change its Z order

## Observed result

Crash.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r40/main.js, line 61, col 240795
Message: Uncaught ReferenceError: ǃeo is not defined
Stack: ReferenceError: ǃeo is not defined at l.ǃnJ (https://editor.construct.net/r40/main.js:61:240795) at window.ǃLE.ǃnC (https://editor.construct.net/r40/components/bars/zOrderBar/zOrderBar.js:1:9709) at window.ǃLE.ǃTd (https://editor.construct.net/r40/components/bars/zOrderBar/zOrderBar.js:1:8954) at Array.ǃed (https://editor.construct.net/r40/components/bars/zOrderBar/zOrderBar.js:1:1464) at ǃb.Event.ǃTDf.ǃTDs (https://editor.construct.net/r40/main.js:2:254634) at ǃb.ǃf.ǃt.ǃG.dispatchEvent (https://editor.construct.net/r40/main.js:2:253285) at ǃb.ǃf.ǃt.ǃG.ǃbbQ (https://editor.construct.net/r40/main.js:2:457477) at ǃb.ǃf.ǃt.ǃTN.ǃHv (https://editor.construct.net/r40/main.js:2:463999) at HTMLDocument.ǃbh.ǃNX (https://editor.construct.net/r40/main.js:2:460029) at HTMLDocument. (https://editor.construct.net/r40/main.js:2:250161)
Construct 3 version: r40
URL: https://editor.construct.net/index.html
Date: Sun Jun 25 2017 14:06:43 GMT-0700 (Pacific Daylight Time)
Uptime: 21.6 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r40

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r41.
