### ISSUE TITLE
Animation editor cannot copy frames

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5591]
## Problem description

It may be by current design, but I prefer to consider it a design flaw.

If I select multiple animation frame in the 'Frames' area and paste it in the 'Frames' area of other Animations, I can only operate on canvas. instead of pasting multiple frames.

![Snipaste_2022-04-01_19-29-07](https://user-images.githubusercontent.com/45864744/161254918-4c99c301-d6cc-4357-9e75-8daade532562.png)

## Attach a .c3p

[Animation-frames-copy.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8397277/Animation-frames-copy.c3p.zip)

## Steps to reproduce

1.Select multiple frames and copy and paste them to 'Frames' 

## Observed result

Only the current frame is pasted to the canvas.

## Expected result

Generate additional animation frames in 'Frames' .  
  
If I need to "replace" the frame image on the 'canvas', I should  focus to the 'canvas' to paste.  And when my focus is on 'Frames' and copy other frames, it should be to paste on frames.  

![2022-04-01_194947](https://user-images.githubusercontent.com/45864744/161257946-068b545a-e8a5-44e2-a460-f3b4927b95b3.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

```
Platform information
Browser: Chrome
Browser version: 100.0.4896.60
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36
C3 release: r288 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 187 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Super with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
```

</details>

**Comment by DiegoScirra** [comment]
Added for the next beta.

The frames can only be copied/pasted as long as the frames panel has focus (by clicking on it specifically).

The pasted frames will always be added at the end of the current animation.

Copying/pasting to and from the main area now requires for the frames panel to not have focus.
