### ISSUE TITLE
HTML Element Layer Issue

### ISSUE THREAD

**Issue by andygilbert29** [Scirra/Construct-3-bugs#5593]
## Problem description

HTML Element ignores layers, it is always visible regardless of the layer it is on.

## Attach a .c3p

[html_element_layer_issue.zip](https://github.com/Scirra/Construct-3-bugs/files/8399333/html_element_layer_issue.zip)

## Steps to reproduce

1. Add HTML Element (and some HTML content to it) on layer 0
2. Add another layer above it (not transparent)
3. Run and see result. 

## Observed result

The HTML element is shown despite being UNDER the top layer (that is not transparent) 

## Expected result

The HTML Element not to be shown.

## More details

Only tested in preview (Chrome)

R288 Beta

**Comment by AshleyScirra** [comment]
HTML elements are not rendered in to the canvas. It's therefore pretty much technically impossible to make any canvas content, like Sprites, display on top of them.

The same thing happens with other HTML element based plugins like Button and Text Input. This has always been the case and it's unlikely it will ever be solved.

**Comment by andygilbert29** [comment]
> HTML elements are not rendered in to the canvas. They are separate elements that essentially float on top of the `<canvas>` element that the main game is rendered in to. It's infeasible to make any canvas content, like Sprites, display on top of them.
> 
> The same thing happens with other HTML element based plugins like Button and Text Input. This has always been the case and it's unlikely it will ever be solved.
> 
> This is noted in the manual for things like [Button](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/button), and a similar note will be documented for HTML element:
> 
> > Form controls are actual HTML elements floating above the game canvas. Therefore, nothing can be displayed on top of a form control, apart from other form controls. Form controls position themselves according to the layer parallax, scale and so on. However they are not truly "in the game" (since they float above), so it is recommended to avoid using scrolling, parallax and layer scaling with form controls, otherwise the end result can feel unnatural.

Of course, sorry. Completely forgot!
