### ISSUE TITLE
Vanishing Point missing system expression

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5597]
## Problem description

When I was going to debug the  layout vanishing point in the game, I found that the expression was missing to get him.
  
 
The current solution is that I add 2 variables and manually control. 

## Steps to reproduce

1.
2.
3.

## Expected result

LayoutVanishingPointX
LayoutVanishingPointY

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Added for next beta.
