### ISSUE TITLE
[R17]"Else" condition color may not update "on the fly"

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#56]
## Problem description

"Else" condition does not properly color to red or black/default to let the user know if it is appropriate to use when adding new events/conditions around it.

## Attach a .c3p
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
Not seen in a saved c3p where the color is actually updated on load.
Can be reproduced in a blank project.
Nevertheless consider the provided project
https://www.dropbox.com/s/b3w0gziwka0z3pj/2017-04-11-Red%20else.c3p?dl=0

## Steps to reproduce

If you have two "Else" events following one another, the second condition is colored Red to mention it is not valid.
Delete the first event.

Expected : The former red "Else" being now alone to be displayed black/default.
Observed : The red "Else" is still red.

In the project you can do it by selecting blank sub-event 2 and pressing the X key a couple of time.
On the first press, you already notice that the existing "Else" sub-event (former 3 now 4) should be red, but is still displayed as black.

Moreover, when following a triggered event added after the "Else" existed, the color do no change/update.

Example add an "Else" to an existing blank sub-event. Right on top of the Else, add a "On start of layout" (triggered).

Expected : The "Else" being now following a triggered condition to be colored red.
Observed : The "Else" is still black/default.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 2.5 gb
Storage usage (approx): 281 mb (10.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 560 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r28. There may be a few extra corner cases where it doesn't update correctly, please file another issue if you find any times it's not updating.
