### ISSUE TITLE
inGame Audio still playing while showing Rewarded Ads in iOS

### ISSUE THREAD

**Issue by arcadesindo** [Scirra/Construct-3-bugs#5600]
## Problem description
When showing a rewarded ads, ingame audio still playing on background instead of paused like we had on Android. The Audio object properties "Play in background" are already set to false.

## Observed result

https://user-images.githubusercontent.com/28801633/161912145-4440488a-3b21-4ace-816b-fc76f5e78140.mp4

## More details

**Affected browsers/platforms:** iOS 15.3.1

**First affected release:** 258.3 Stable release

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.
