### ISSUE TITLE
[Addon SDK] Cordova plugin variables with "~>" returns "~%rt;" on export, which cannot be built

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#5601]
## Problem description

Cordova plugin variables with `~>` returns `~%rt;` on export, which cannot be built.

## Addon Script (Not working)

These are the configurations when it is not working, please focus your attention to the `~>`.

**The plugin property code:**
![image](https://user-images.githubusercontent.com/31282960/161946543-28c37889-b9ad-4db1-8ac6-fcb4a7d57f5f.png)

**The plugin property inserted in a Cordova plugin variable:**
![image](https://user-images.githubusercontent.com/31282960/161946787-4c0ff9b9-605d-45a4-b9d4-3a1f29262cfb.png)

**Plugin Property**
![image](https://user-images.githubusercontent.com/31282960/161945993-887f24fa-8b70-4010-891c-8c6d507d92df.png)

**Export:**
![image](https://user-images.githubusercontent.com/31282960/161945784-b3d153ab-391f-49f5-9edc-daf70bf54b13.png)

**Build:**
![image](https://user-images.githubusercontent.com/31282960/161948527-2d853deb-50cc-4962-9694-c705b17d21ad.png)

## Addon Script (Working)

These are the configurations when it is working, please focus your attention to the omitted `~>`.

**The plugin property code:**
![image](https://user-images.githubusercontent.com/31282960/161947453-2375fa1e-9a13-42c3-a811-933d55fb208f.png)

**The plugin property inserted in a Cordova plugin variable:**
![image](https://user-images.githubusercontent.com/31282960/161947554-7e27fbea-f3e1-49e7-ad9c-d87bb327335a.png)

**Plugin Property**
![image](https://user-images.githubusercontent.com/31282960/161947731-9032a42e-d0bf-410a-8cf7-8d5b2da25fe2.png)

**Export:**
![image](https://user-images.githubusercontent.com/31282960/161948065-4b47242e-9e07-4ca2-a739-dfdabd314338.png)

**Build:**
![image](https://user-images.githubusercontent.com/31282960/161948316-96b90bf3-b756-431a-9dc4-bdee61095d47.png)

## Attach a .c3p

[Addon + Project.zip](https://github.com/Scirra/Construct-3-bugs/files/8425824/Addon.%2B.Project.zip)

## Steps to reproduce

1. Install the `Broken Plugin.c3addon`, then open the `Project.c3p`.
2. Observe the plugin property of the `Construct3` object, where the `~>` is included.
3. Build `debug.apk`, then observe the error.
4. Install the `Working Plugin.c3addon`, then open the `Project.c3p`.
5. Observe the plugin property of the `Construct3` object, where the `~>` is omitted.
6. Build `debug.apk`, then observe the build success.

## Observed result

If the `~>` is in a combo parameter, or any compatible plugin property type, the build fails because the `~>` is automatically converted to  `~%rt;`, which cannot be identified by the Cordova CLI.

Remove the `~>` and the Cordova CLI builds successfully.

## Expected result

For the Construct 3 export to retain `~>` when included in a Cordova plugin variable.

## More details

Thank you!

**Comment by AshleyScirra** [comment]
Oops, this looks like a typo: `>` should be escaped as `&gt;` not `&rt;`. I've fixed this for the next beta. I've also patched the build service, which IIRC generates the config.xml file itself, so this may now be working already with the build service (otherwise it will be fixed at the next beta).

**Comment by Chadori** [comment]
Thank you, this is really helpful!
