### ISSUE TITLE
Image Point Moves After Reaching First/Last Frame in Animations Editor

### ISSUE THREAD

**Issue by brainwavecreations** [Scirra/Construct-3-bugs#5604]
Problem description:
When I set the image point for an entire animation(s). If I am cycling through the Animation frames quickly using CTRL + Arrow keys. If going too quickly, it will start to move the image point on the first or last frame, if I am holding down CTRL + an Arrow key, or just pressing the arrow key too quickly and reach the first or last frame, and continue pressing the arrow key.  It would be awesome to make it so, if on first or final frame, and CTRL is held plus the left or right arrow key being pressed quickly or held down all together, it will not start moving the image point in the direction being pressed in pixels.

The same thing goes for using the CTRL + Arrow Up or Down to cycle through the various Animations on a Sprite Object as well.  If reaching the final animation in the list, it starts moving the image point down. And, reaching the first animation at the top of the list, it starts moving the image point upwards, if the key is still held or being pressed.

Attach a .c3p:
Any .c3p file would do.  Create a new project, a simple Sprite Object, duplicate frames.  Then see the image point moved, after doing the above.  I could create a brief YouTube video as well, if that would be at all helpful.

Steps to reproduce:
Create a new project, a simple Sprite Object, duplicate frames.  Then see the image point moved, after doing the steps in the above description.

Observed result:
Image Point/Object Origin moves by pixel(s) if first/last frame, or first/last Animation in Animations list is reached, while still holding CTRL and pressing the arrow key in that same direction.

Expected result:
Image Point/Object Origin should not move, when the above is performed.

More details: N/A

Affected browsers/platforms:
Chromium based browsers is all I use

First affected release:
Not sure, it's been ongoing

System details:
Windows 10, latest updates, latest Chrome web browser.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
