### ISSUE TITLE
Bounding Box in Animations Editor Flashes to old Point Positions, then Changes Back

### ISSUE THREAD

**Issue by brainwavecreations** [Scirra/Construct-3-bugs#5605]
Problem description:
If I change the bounding box points, then apply to entire animation(s). Then cycle through the animation frames quickly, either via clicking with mouse pointer, or CTRL + arrow keys. The bounding box/shape points will quickly flash to the previous locations, but then jump back to where I've set them. As long as they keep going back to where I've set them last, it doesn't really matter. Just a slight visual bug. But, it does stop if I close the Animations Editor and re-open it, then go back to that particular Animation.

Attach a .c3p:
It would be really difficult to attach a .c3p for this issue.  It doesn't happen, unless the Sprite Object is brand new, and just opened up, and Animations Imported, with Bounding Box re-adjusted, then changing through Animation Frames quickly.  Either clicking through quickly, or using the CTRL + Arrow Keys shortcut.  I could create a brief YouTube video as well, if that would be at all helpful.

Steps to reproduce:
Create a new project, a simple Sprite Object, with the Animations being imported.  I was only imported .gif images, so not sure if it happens importing a bunch of static images as well.   Then adjust each bounding box for each Animation Frame.  You could simply do option to set the default bounding box to the entire frame for entire animation.   Then change through Animation Frames quickly.  Either clicking through quickly, or using the CTRL + Arrow Keys shortcut.

Observed result:
The bounding box/collision box points for animation frames will flash their previous layout, then quickly change back over to where they have been last set to.

Expected result:
The bounding box/collision box should remain the same, no flash.

More details: N/A

Affected browsers/platforms: 
Chromium based browsers is all I use

First affected release: 
Not sure, it's been ongoing

System details: 
Windows 10, latest updates, latest Chrome web browser.

**Comment by dop2000** [comment]
@DiegoScirra  This might be the same issue - I noticed that now in the latest beta when you click on an animation name, the properties bar blinks and shows frame properties. You need to click the animation name again for it to show animation properties.

**Comment by DiegoScirra** [comment]
@dop2000 That was issue #5603. That's fixed already.

I think this issue happens because there are loads of asynchronous tasks going on in the Animations Editor and things are not quite lining up.

@brainwavecreations I am having a hard time seeing what is actually happening, if I am not very focused on the screen I don't even notice it. Only if I pay real close attention I can see it. Is it the same for you?

**Comment by brainwavecreations** [comment]
Hey hey @DiegoScirra 

I've made a brief video, and uploaded to youtube to show what I am seeing.  https://www.youtube.com/watch?v=Py0DdPjfPD4

It's pretty much a non issue, as long as the bounding box points revert to where they were set last.  It's actually barely noticeable this morning, compared to the other day.  This is used to happen in previous versions, right before the bounding box would change back to using it's previous points when the animation was imported.

As long as that is solved, as it seems to be.  This isn't a big deal.  I think it's just a matter of how the Animations Editor operates.  I didn't include it in the video.  But, if I close down the Animations Editor.  Then open back up.  The slight visual change, doesn't even appear anymore.

Thanks for looking into this!  I really appreciate your time :)

**Comment by DiegoScirra** [comment]
I see, then this should be sorted for the next beta.
