### ISSUE TITLE
The dialog for Pick instances for Timeline is missing search bar

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5606]
## Problem description

The dialog for 'Pick instances for Timeline' is missing search bar.

![Snipaste_2022-04-07_14-22-24](https://user-images.githubusercontent.com/45864744/162133590-9649b577-23d3-46f5-ac73-12562febdba5.png)

## Attach a .c3p

https://editor.construct.net/#open=segmented-boss-fight

## Steps to reproduce

1.
2.
3.

## Observed result

![Snipaste_2022-04-07_14-19-02](https://user-images.githubusercontent.com/45864744/162133603-bfd6927b-d5b5-4ac0-9079-914bbaf27998.png)

## Expected result

![Snipaste_2022-04-07_15-19-34](https://user-images.githubusercontent.com/45864744/162142489-c9708455-8f9b-4367-9412-b32ab7cb8835.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be added in the next beta.
