### ISSUE TITLE
2D layer object placed outside the layout, and use 3D Camera the object will disappear.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5608]
## Problem description

If a 2D layer object is placed outside the layout, scrolling with the 3D camera will cause the object to disappear.

![Snipaste_2022-04-07_16-25-41](https://user-images.githubusercontent.com/45864744/162155078-84b9fa25-9afe-4eb3-b36a-1323f854d416.png)

## Attach a .c3p

[layer-rendering-issue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8440958/layer-rendering-issue.c3p.zip)

## Steps to reproduce

You can toggle the first line of events to observe different rendering results from the initial camera.

![Snipaste_2022-04-07_16-28-39](https://user-images.githubusercontent.com/45864744/162155718-79e3b7c4-5ad7-492a-9030-25dbd16f4e5a.png)

1. If  use the 'ScrollTo' first, can see the 2D layers sprite. but use the '3Dcamera' first, will can‘t see.  

![Snipaste_2022-04-07_16-40-11](https://user-images.githubusercontent.com/45864744/162158113-6d159dcd-4438-4303-98a0-cf1929d25033.png)

2. click the 2D button to switch, you can see it again.  But causes Parallax to be misdirected.

![Snipaste_2022-04-07_16-39-00](https://user-images.githubusercontent.com/45864744/162157852-c5444338-0b8d-434b-a603-2fbed8c55d5e.png)

## Observed result

![Snipaste_2022-04-07_16-25-01](https://user-images.githubusercontent.com/45864744/162155164-70367ba3-98c8-4804-a3ae-33aade296093.png)

## Expected result

![Snipaste_2022-04-07_16-24-10](https://user-images.githubusercontent.com/45864744/162155189-92ef88d0-23db-48c9-9ab9-caaf42ae17db.png)

## More details

**Affected browsers/platforms:** Chrome, Windows 11

**First affected release:** 

## System details

<details><summary>View details</summary>

```
Platform information
Browser: Chrome
Browser version: 100.0.4896.75
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
C3 release: r289 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 267 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
```

</details>

**Comment by AshleyScirra** [comment]
This just looks like a mistake in your events. The 3D Camera object only affects 3D layers. If you don't enable the ScrollTo behavior then nothing will ever scroll the 2D layer. It looks like you actually want to leave the ScrollTo behavior always enabled for the 2D layer, and then use the 3D Camera object to control the view on the 3D layer.

**Comment by XHXIAIEIN** [comment]
I re-uploaded an attach file
[2D&3Dlayer-issue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8443228/2D.3Dlayer-issue.c3p.zip)

**Comment by AshleyScirra** [comment]
Once again, the 3D Camera only affects 3D layers. There is nothing in that project that attempts to scroll the 2D layer. If you enable the disabled "Scroll to" behavior, it works, because that behavior scrolls the 2D layer.
