### ISSUE TITLE
Cloud built .apk failing to import into Monaca

### ISSUE THREAD

**Issue by ommidan** [Scirra/Construct-3-bugs#561]
## Problem description

Exported project and built .apk using the Construct 3 cloud based build utility (as debug app), however when trying to import into Monaca  via the 'upload project package' option it fails due to 'missing' index.html file:
"index.html file is not found in the project root or in the www directory"

## Attach a .c3p

https://drive.google.com/open?id=0B6Xd0j_vuzCOWWpPd1ZPRl9wX3M

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Export project as Cordova and choose the Build App option (debug version)
2. In Monaca choose 'Import Project'Option then 'Upload Project Package'
3.

## Observed result
Monaca reports that the index.html file is missing - I presume it's telling the truth!

## Expected result
index.html would be present

## Affected browsers

* Chrome: yes

## System details

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r40

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 97 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 650M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2047
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by shortercode** [comment]
Just given it a go and that menu isn't for importing an APK, it's for importing an archive of a monaca project. We don't support monaca projects, but I tried importing a cordova project and they seem to be able to convert it to their own format. The format is pretty similar but with a few folders moved around so it makes sense that they'd support it.

When you try to build for android or iOS stop at the dialog with the build apps button and click the link above it to download the cordova project instead and import that zip file.

**Comment by ommidan** [comment]
Iain - many thanks for the very prompt and helpful response.

I'll try your suggestions- Much appreciated.
