### ISSUE TITLE
Increasing Variable freezes time/ticks

### ISSUE THREAD

**Issue by amazingsulley** [Scirra/Construct-3-bugs#5612]
## Problem description

When Variable is increased once every z seconds (until limit of y) it freezes time, wall clock time, and ticks in preview.  

## Attach a .c3p

[Bug test.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8444709/Bug.test.c3p.zip)

## Steps to reproduce

1. Make any variable that starts at x value
2. If variable = y value, add 1 every z seconds to variable while variable is less than x value
3. Trigger variable to equal y value and watch the chaos

## Observed result

freezes time, wall clock time, and ticks in preview

## Expected result

Variable would get slowly increased until it was back at original y value

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The events are wrong. "Every X seconds" will never run inside a while loop. So you've just set up an infinite loop. That will stop the game from advancing to the next frame, so the game time never advances, so "Every X seconds" never runs.
