### ISSUE TITLE
Functions - Creating an object with a Function then moving it with another Function does not work

### ISSUE THREAD

**Issue by JauqGames** [Scirra/Construct-3-bugs#5613]
## Problem description

When attempting to create an object (a sprite in my example) with a function and then immediately changing its position with another function, its position is not altered.

## Attach a .c3p

[CreateAndMoveFunctionIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/8454933/CreateAndMoveFunctionIssue.zip)

## Steps to reproduce

1. Create a sprite object in the project but delete it from the layout (so this object does not interfere with the function-created one).
   - In my example: I created a 32x32 Sprite entirely colored white.
2. Create a function named "create" and program the function to create a new sprite on layer 0 at coordinates (0, 0).
3. Create another function named "move" and program the function to move all instances of the sprite object to any other coordinates.
   - In my example: I moved it to coordinates (512, 512)
4. Create a "On Start of Layout" Event and call both the "create" and "move" functions in it, in that order.

## Observed result

The sprite object remains in its created position of (0, 0) and not at the move position.
![CreateAndMoveFunctionIssueResult](https://user-images.githubusercontent.com/39632133/162524489-d20bda74-f80c-4c78-89d9-216026d38496.png)

## Expected result

The sprite object should've been moved to the move position.
![CreateAndMoveFunctionIssueExpected](https://user-images.githubusercontent.com/39632133/162524537-eae7f2c5-d0c0-4753-98f0-a3d1e456f309.png)

## More details
I've noticed this in versions prior, but I do not recall the first affected release. Before, I simply programmed workarounds, but my newest project now requires functions like these to run one after the other in the same event.

More details on my workarounds or the project that requires this can be provided at request.

**Affected browsers/platforms:** I'm using Chrome 100.0.4896.75 (64-bit)

**First affected release:** Unknown

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 100.0.4896.75
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
C3 release: r285.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 1.2 gb (0.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a long-standing limitation of the event system: newly created instances are not fully created until the end of the next top-level event. Until then they can be picked in the same event, but not other events.

The workaround should be simple though: make sure you create and initialise the object in the same event.
