### ISSUE TITLE
Hierarchy with Select mode = Wrap has translation issues

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-3-bugs#5614]
## Problem description

An angled sprite rotates while scaling in a hierarchy of 2 combined sprites.

![chrome_2022-04-09_01-53-09](https://user-images.githubusercontent.com/18266300/162547624-4fc73cff-07a6-4c60-a804-68da2f682233.gif)

## Attach a .c3p

[Hierarchy_bug_01.zip](https://github.com/Scirra/Construct-3-bugs/files/8455833/Hierarchy_bug_01.zip)

## Steps to reproduce

The setup found in the project file:
- Combine 2 sprites in a hierarchy 
- Rotate one of them on an angle
- Set select mode to wrap

Reproducing the bug:
- select the 2 combined sprites
- change the height of the sprite
- the sprite that is on an angle will start to rotate while scaling

## Observed result

sprite that is on an angle will rotate while scaling if it is in a hierarchy with another sprite while in the wrap selection mode

## Expected result

sprite that is on an angle should only scale in the described constellation, not rotate.

## More details

Bug occurs inside the Construct 3 editor

**Comment by AshleyScirra** [comment]
This is solely to do with wrapped selections - it reproduces without hierarchies. It's also not actually a bug. If you resize a wrapped selection with rotated objects in it, the correct thing to do is skew the object (try it in an image editor, resizing an image with a rotated box on it). Construct does not support skewing objects. So it cannot do the correct thing. Instead it rotates the object in a way to produce something approximate to a skew.
