### ISSUE TITLE
Renaming an Object Types subfolder doesn't sort the list alphabetically

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#5615]
## Problem description

When renaming an Object Types subfolder, it remain in its place on the list, regardless of the alphabetical order. 

Only by adding a new subfolder does the list reorder alphabetically.

## Attach a .c3p

(New project will work)

## Steps to reproduce

1. Open a new project
2. Right click on "Object Types" and create a new Object Types subfolder. Keep the name "New folder"
3. Create a second Object Types subfolder. Keep the name "New folder 2"
4. Rename "New folder 2" to "Apple". Note the order won't change to put the "Apple" folder first.
5. Create a third Object Types subfolder. Note that "Apple" is now top.

## Observed result

The order of subfolders remains the same.

## Expected result

The new subfolder should have been at the top of the list after renaming it, in the usual forced alphabetical order. 

## More details

**Affected browsers/platforms:** Chrome 99

**First affected release:** r289

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by XHXIAIEIN** [comment]
+1
![4](https://user-images.githubusercontent.com/45864744/162657528-e46e76ae-081e-49d0-bb38-0ad565df33c2.gif)
