### ISSUE TITLE
More useful font preview in Font picker dialog

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5616]
## Problem description

This is an enhancement suggestion,     
When the Font picker dialog opens the font preview, provide some sample text choices. Easy to test for different sentence.

This feature is commonly used in some font websites.

- https://fonts.adobe.com/fonts
- https://fonts.google.com/
  
  
Take 'adobe fonts' for example:  
![Snipaste_2022-04-10_09-38-56](https://user-images.githubusercontent.com/45864744/162598969-73be1324-3123-450a-9ce9-cd0219833c90.png)
  
You can also find more examples in other languages here: 
- https://clagnut.com/blog/2380/
- https://clagnut.com/blog/2380/#Sample_font_displays_in_other_languages_using_pangrams
- https://fr.wikipedia.org/wiki/Pangramme
  

I sorted them out:  
```
ABCDEFGHIJKLMNOPQRSTUVWXYZ

0123456789 ¿ ? ¡ ! & @ ‘ ’ “ ” « » % * ^ # $ £ € ¢ / ( ) [ ] { } . , ® ©

The quick brown fox jumps over the lazy dog

Roger, hungry: ate 236 peaches & cantaloupes in 1904!

Realigned equestrian fez bewilders picky monarch

Voix ambiguë d’un cœur qui au zéphyr préfère les jattes de kiwi

Victor jagt zwölf Boxkämpfer quer über den großen Sylter Deich

Quiere la boca exhausta vid, kiwi, piña y fugaz jamón

Ma la volpe, col suo balzo, ha raggiunto il quieto Fido

Zebras caolhas de Java querem passar fax para moças gigantes de New York
```

Also, for testing, I've created a quick preview in the editor
```html
<ui-dialog-contents alignleft>
<div><span class="fontPickerLocalHeaderText">Choose sample text...</span><br>
<select class="localFontSelect">
    <option>ABCDEFGHIJKLMNOPQRSTUVWXYZ</option>
    <option>0123456789 ¿ ? ¡ ! &amp; @ ‘ ’ “ ” « » % * ^ # $ £ € ¢ / ( ) [ ] { } . , ® ©</option>
    <option>The quick brown fox jumps over the lazy dog</option>
    <option>Roger, hungry: ate 236 peaches &amp; cantaloupes in 1904!</option>
    <option>Realigned equestrian fez bewilders picky monarch</option>
</select></div>
<br><br>
<div>
<span>Text Size</span><br>
<select>
    <option>5</option>
    <option>8</option>
    <option>11</option>
    <option>14</option>
    <option>20</option>
    <option>28</option>
    <option>36</option>
    <option>48</option>
    <option>64</option>
    <option>72</option>
</select></div>
<br><br>
<div><span class="sampleTextHeader">Sample text:</span><br><br>
<span class="sampleText">0123456789 ¿ ? ¡ ! &amp; @ ‘ ’ “ ” « » % * ^ # $ £ € ¢ / ( ) [ ] { } . , ® ©</span></div>
<br><br>
</ui-dialog-contents>
```

## Observed result

![Snipaste_2022-04-10_09-35-44](https://user-images.githubusercontent.com/45864744/162597485-69cfe3c5-5199-4c9f-b001-b73b44bdfec4.png)

## Expected result

![Snipaste_2022-04-10_10-38-30](https://user-images.githubusercontent.com/45864744/162598819-0216283e-1ecf-4060-ae1e-8eb69c5bf46d.png)

![Snipaste_2022-04-10_10-34-44](https://user-images.githubusercontent.com/45864744/162598828-725a5ac1-2ea4-458d-942f-39bffb3325ef.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
while we are at it, add an example with different bbcode formatting
