### ISSUE TITLE
Sprite.count inconsistency with object created in a function 

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#5619]
## Problem description

The ".Count" property of a sprite is inconsistent when the object is created inside a function. 

The first time the sprite is created, the Sprite.Count doesn't recognize it. But in all subsequent function calls, the object created is recognized by Sprite.Count. 

Ideally this is consistent: either Sprite.Count includes the sprite object created in the function (including the first one) or ignores them all. 

## Attach a .c3p

https://drive.google.com/file/d/1cTAWXWf0qjIQHCSPfFhib48LNPDsaIoV/view?usp=sharing

## Steps to reproduce

1. Run the attached project.
2. Left-click on the layout. A sprite is created, but note that the count doesn't register it, and is inaccurate (Sprite.Count = 0).
3. Left-click again. Another sprite is created, however this time the count does register it (Sprite.Count = 2).
4. Left-click a few more times. Sprite.Count increases accurately.

## Observed result

Sprite.Count doesn't recognize the first object created, but it does recognize all subsequent objects created by the same code.

## Expected result

A) Sprite.Count consistently doesn't register any object created in the function. 
or
B) Sprite.Count consistently registers all objects created in the function.

## More details

**Affected browsers/platforms:** Chrome 99

**First affected release:** r289

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is partly a mistake in your events, and partly a quirk in the engine.

First of all if no instances of Sprite exist, all its expressions return 0. Your expression to position the created Sprite is based on

`50 + (Sprite.Height * (Sprite.Count + 1))`

When there are no Sprite instances, `Sprite.Height` will return 0, and so calculate `50 + (0 * 1)`. This is why a gap appears in the column of created sprites. If you hard-code the sprite height, it closes the gap.

Secondly the count is displayed in a text object in a sibling sub-event. There is a long-standing limitation in the event engine that newly created instances are not fully created until the next top-level event. Therefore the first time an instance is created, it still does not count as fully created by the time the `Count` expression is used; as per the previous rule, this counts as no instances existing, and so it will return 0 (with 1 instance pending creation). So long as any instance exists, the `Count` expression can take in to account instances pending creation, but there must be at least one instance for the expression `Sprite.Count` to return anything other than zero.
