### ISSUE TITLE
Nesting Include Event sheet not working

### ISSUE THREAD

**Issue by broknecho** [Scirra/Construct-3-bugs#562]
## Problem description

Cannot nest an include event sheet call under events or groups.

## Attach a .c3p

[GroupIncludeTest.zip](https://github.com/Scirra/Construct-3-bugs/files/1104066/GroupIncludeTest.zip)
*Renamed to zip from c3p for github

## Steps to reproduce

1. Open attached project
2. Go to Event Sheet 1
3. Try to nest the Event Sheet 2 call within the group or event

## Observed result

The Event Sheet 2 Include pops back up to the top of the file

## Expected result

The Include Sheet line should stay nested under the event your placed it within.

## Affected browsers

* Tried in Chrome Desktop app

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.109
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36
C3 release: r40

Local storage
Storage quota (approx): 7.2 gb
Storage usage (approx): 272 mb (3.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Nesting event sheets is not supported, so closing as won't fix.

**Comment by broknecho** [comment]
@AshleyScirra Try importing this Construct 2 Capx:

[C2NestedIncludeExample.zip](https://github.com/Scirra/Construct-3-bugs/files/1105749/C2NestedIncludeExample.zip)

And now here is the `.c3p` version of that file that C3 saved out:
[C3NestedIncludeTest.zip](https://github.com/Scirra/Construct-3-bugs/files/1105753/C3NestedIncludeTest.zip)
![image](https://user-images.githubusercontent.com/3253547/27594754-ea178798-5b17-11e7-823a-bbfdd5e7874e.png)


This is a very nice feature in C2 for code organization and would be a big loss in C3.  It does look like it's partially supported if you try the samples above.

**Comment by AshleyScirra** [comment]
It's a mistake that Construct 2 allows it. Includes are meant to work statically at the top-level only. They were never designed to work anywhere else. If you put them in a group and disable the group, for example, it will probably still run the included events. Rather than allow you to do something unsupported, C3 disallows it, which C2 should have done in the first place too.

**Comment by broknecho** [comment]
I just tested what you're saying and it does seem to work when I toggle the group state:
![image](https://user-images.githubusercontent.com/3253547/27600034-da8ccdd2-5b27-11e7-8d08-5216ddb71fea.png)

![image](https://user-images.githubusercontent.com/3253547/27600036-dda35644-5b27-11e7-9f8b-212ef2f8c86e.png)

So pressing `D` toggles the Enabled/Disabled state of that event sheet 3 which contains a keyboard event press.  If you toggle it's state, the Keyboard event only fires when that event sheet include group is enabled.

C2
[C2NestedIncludeExample2.zip](https://github.com/Scirra/Construct-3-bugs/files/1106176/C2NestedIncludeExample2.zip)

C3
[C3NestedIncludeTest2.zip](https://github.com/Scirra/Construct-3-bugs/files/1106177/C3NestedIncludeTest2.zip)


Either way it is working as I expect but I also understand what you're getting at.  This simple sample I setup is only showing events working as expected and there may be some other scenarios that may break here.

Just to give you a real life example, my largest C2 project has over 400 events in one event sheet as it's the main game loop for a multiplayer game.  I'm now starting to refactor it to have individual event sheets for related logic and it helped having groups to organize those included event sheets. (Instead of having all includes at the top of this one event sheet)

Should I maybe add this idea back to the Contruct 3 future ideas?  Doesn't have to be the same idea exactly but something along the lines of being able to include code from another event sheet?

**Comment by broknecho** [comment]
Thinking about this more, I can just wrap all included event sheets in their own group at the top level of the event sheet and just name it the same as the event sheet. This way I can then toggle those Groups from a different event sheet using the fact that group names are global.

**Comment by AshleyScirra** [comment]
It's a totally 100% unintentional part of the engine. If it works, it's basically luck. So I'd rather turn off things we're not actually supporting rather than leave people to find unexpected results.

Using groups in the sheets themselves is a much better idea, I think.

**Comment by broknecho** [comment]
Sounds good!  Thanks a lot for taking the time to look into this and explain.
