### ISSUE TITLE
Timelines - ignoring object time scale

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-3-bugs#5620]
## Problem description

Timelines only follow system time, rather than object time. I'm not sure if this is fixable or not due to how the timeline plugin works, but thought I'd post it just in case. Essentially, using the timeline plugin to animate a sprite will give undesired results if the system time scale is running at something other than 1, even when the object that is in the timeline has its timescale set to 1.

## Attach a .c3p

[timelines and timescale.zip](https://github.com/Scirra/Construct-3-bugs/files/8460391/timelines.and.timescale.zip)

## Steps to reproduce

1. press space to run the timeline with the desired result
2. reload and press 'T', setting system time to 0 and Sprite time to 1
3. repress space, note that the animation no longer runs as desired

## Observed result

The animation does not play

## Expected result

From a user point, it would be nice to be able to play timelines regardless of system time (i.e. the game is paused while a menu is up)

## More details

Stable Chrome

**Comment by DiegoScirra** [comment]
Sorry for the late response.

This isn't really possible with the current implementation.

The first problem would be that a timeline can have multiple instances, but it only has one play head and it can only follow one timescale to make sure all the instances arrive at the desired destination at the same time. If each track of the timeline followed it's own time scale, then some instances would never reach their destination.

The ideal solution would be to extend/halve the segments of time of each individual track by the time scale of the corresponding instance. That should allow to have multiple instances using different time scales in the same timeline, giving the illusion they are moving at different rates. The main problem is that the system is not prepared to dynamically change a timeline at runtime. This would take a lot of work to implement and at the moment it doesn't seem to be worth it.

If what you really would like is for a timeline to be able to play while the system timescale is set to 0. Then that could be added, as a setting to a timeline, with relative ease.

**Comment by Ldwebster111** [comment]
I think I put in a workaround back when this way an issue (from memory, I think I just gave up on timelines and used tweens instead).

But yes, an option to ignore system timescale would have made this a non-issue. As mentioned, timelines can't be used currently while a game is paused so that would fix the issue.

Cheers

**Comment by DiegoScirra** [comment]
Starting with the next beta cycle, timelines will show a checkbox property in the Properties bar to be able to decide if it should be tied to the system timescale or not.
