### ISSUE TITLE
Black screen on iOS app with MobileAdvert test mode Disabled.

### ISSUE THREAD

**Issue by lukasinspace** [Scirra/Construct-3-bugs#5621]
## Problem description
When trying to publish an app on iOS I get a black screen when MobileAdvert test mode is 'disabled'.

When MobileAdvert test mode is set 'disabled', app shows a black screen on start up immediately after the C3 splash screen.

If MobileAdvert test mode is set 'enabled', app loads up and runs as expected. 

## Attach a .c3p
[_mobileAdvert test.zip](https://github.com/Scirra/Construct-3-bugs/files/8472590/_mobileAdvert.test.zip)

## Steps to reproduce
In Admob dashboard create an app, and create a rewarded ad unit. 

Open the attached c3p file. In MobileAdvert properties enter iOS App ID and Publisher ID from Admob dash.
(can open in latest stable release or latest beta, result is the same).

In the event sheet enter real ad unit ID (from admob dash) 

Export for iOS > Choose Xcode project

On Mac open Xcode project > Follow construct 3 tutorial to set up automatic signing 
> Run the project on a simulator OR
> attach iPhone device to Mac > run the project on the device OR
> archive the project > choose AdHoc > export ipa > install AdHoc ipa on iPhone device OR
> archive the project > choose App Store Connect > upload to app store > Install on device through Test Flight

## Observed result

Under all testing methods I see the app load as far as the C3 splash screen and a black screen appears immediately after. The game never loads beyond that. 

## Expected result

Expected result would be app loads as expected, Admob configures successfully, debugging text in the app confirms that MobileAdvert configures and rewarded ad loads and is ready to be shown.

## More details
I thought that, when MobileAdvert test mode is set disabled, a built iOS app shouldn't hang and give a black screen, at the point that it tries to configure, even if configuration fails. In the event that MobileAdvert configuration fails, the app should continue to load in that situation, its just that ads wouldnt show? 
But what seems to be happening in my case, is the MobileAdvert tries to initialize /configure, it cant for some reason I dont understand and the app hangs? (It may be that MobileAdvert is unable to configure because my app isnt linked in the admob dash.. it can't be linked until its actually published.. and it cant be published until I can solve this black screen). Im not sure thats right. Im just grasping at straws.. 

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
IIRC if Mobile Advert is misconfigured it can sometimes cause AdMob to crash, and there's nothing we can do about it. So double-check everything is configured correctly.

**Comment by lukasinspace** [comment]
Hello Ashley. Theres only two things to enter right? publisher ID and app ID? I have checked both of these.

**Comment by DiegoScirra** [comment]
What version of C3 are you using? Stable or Beta?

**Comment by lukasinspace** [comment]
Hi Diego. I get the same result if I used the latest stable (r285-3) or latest beta (r289).

**Comment by lukasinspace** [comment]
Ive tried a lot of different things. I was getting this with my actual project, so I made a minimalist c3p with just MobileAdvert, I exported xcode from r285-3 and r289... result is always the same for me.

If test mode is enabled. App loads as expected.
If test mode is disabled. Black screen immediately after C3 splash screen.

**Comment by DiegoScirra** [comment]
What are your minification settings, None, Simple or Advanced?

**Comment by lukasinspace** [comment]
Always Advanced.

**Comment by DiegoScirra** [comment]
Yeah, I just tried disabling test ads and and tried it on a real device and it just stays on a black screen. I'll check if it has anything to do with minification, it probably doesn't but just to be sure.

**Comment by DiegoScirra** [comment]
It looks like **Advanced** minification is causing a problem, I tried it with **None** and it is working. Not sure what **Simple** minification will do.

**Comment by lukasinspace** [comment]
Can confirm Diego. Minification set to None worked. App was able to boot up all the way. No black screen. It worked in simulator and running on iPhone device. Didn't try exporting an iap yet. YESSS!!!👍

I'm using latest C3 stable, haven't tried beta. And I'm testing with the minimal c3p, not my game project. Which C3 version are you using Diego?

I've literally wasted days trying to figure this out. Changing Minification should have been one of the first things I tried!!! 

I'll try my game project now.

**Comment by DiegoScirra** [comment]
I usually work on the latest beta, but in this case it shouldn't make a difference.

I am wondering if people that encounter this problem just figure out that turning minification off fixes it and don't bother reporting it or if it started happening recently.

**Comment by lukasinspace** [comment]
Just tested my game project and thats working with Minification set to **None** as well. Man I'm so happy 😆

I can't tell you how recently it's been doing it Diego. I just discovered it about maybe 3-4 days ago. I assumed it was something I was doing wrong with Xcode or my admob setup. I published the same game to android already and MobileAdvert works on Android with Minification set to **Advanced**.. so I didn't think to change it. In hindsight it's an obvious thing to test tho. I'm glad you thought of it!!!

Tmoro I'll do some more testing. To try Simple Minification. And test it with exported ipa files through Test Flight etc. That will be the important test, that I can actually get a working ipa to publish!

Will report back tmoro. Cheers Diego 👍

**Comment by DiegoScirra** [comment]
This is definitely an old issue that whoever encounters it, is side stepping it by disabling minification, will be fixed in the next beta.

**Comment by lukasinspace** [comment]
@DiegoScirra Just to follow up. I found the app works as expected with **Simple** minification as well as **None**. So it's just **Advanced** that causes a problem..

Exporting from C3r285-3

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.
