### ISSUE TITLE
Project Won't Open in Chrome

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#5626]
My project will no longer open through the cloud (Google Drive) in the Chrome browser.

## Problem description

My project will no longer open through the cloud (Google Drive) in the Chrome browser, which states to "check it is a valid Construct 3 single-file (.c3p) project." However, the project still cloud opens in other browsers like Firefox and Edge. The project also _will_ open in Chrome if opened as a local file rather than one stored in Google Drive.

## Attach a .c3p

[Common.zip](https://github.com/Scirra/Construct-3-bugs/files/8483585/Common.zip)

## Steps to reproduce

1. Save the .c3p file to Google Drive.
2. In Chrome, attempt to open the .c3p using cloud open.
3. Observe that the project will not open in this way, whereas it seems to have no issue opening as a local file.

## Observed result

The project did not open, and instead a popup appeared suggesting to "check it is a valid Construct 3 single-file (.c3p) project."

## Expected result

The project would open through the cloud as normal, as it works in other browsers.

## More details

This project was last saved in a recent beta version of Construct rather than a stable version, so that could potentially be relevant somehow. I also see the following error messages in Chrome's console window when trying to open the project:

![image](https://user-images.githubusercontent.com/4585257/163243100-96f0595c-4be4-4731-8bab-dcb6db8beb8f.png)

**Affected browsers/platforms:** 
Chrome.

**First affected release:**  No later than r290 beta.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 100.0.4896.75
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
C3 release: r290 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 70 gb
Storage usage (approx): 47 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It saves and loads from Google Drive just fine for me here, using Chrome in r290.

Try disabling any browser extensions you have in Chrome. They could be interfering some way.

**Comment by ChromeWisp** [comment]
So here's a screenshot of my Chrome extensions. There weren't many to begin with but they're all off now and I'm still having the issue, though on further testing it doesn't seem entirely consistent? On my first attempt to open the project through Google Drive today, it worked, but after that I closed the project, started recording my screen, and tried again several times (through both the Recent Projects listing and through the Open dropdown menu). As seen in this recording, I got a failure to open, then one successful open, and then a string of failures (some of which take longer to fail out than others?) every try after that... I'm wondering if the issue has something to do with Google Drive, and if it's not always accessible for some reason, leading some attempts to open the project to work while others fail? I'm stumped.

![image](https://user-images.githubusercontent.com/4585257/163420073-e39929bd-3fac-4770-956f-8331f56db787.png)

https://user-images.githubusercontent.com/4585257/163420741-60384f1d-e2c0-4c9c-9569-5ba379baf087.mp4

**Comment by AshleyScirra** [comment]
I'm afraid there's nothing much we can do without a reliable way to reproduce the problem. I would guess this is either some kind of browser/extension modification on your end that is interfering, or a problem with your Internet connection.

**Comment by ChromeWisp** [comment]
@AshleyScirra So, since unfortunately I'm still stuck with this issue, I have to keep trying to solve or understand it. As mentioned already and shown in the provided screenshot, all browser extensions are turned _off_, and I've found I can still open older projects without the issue ever occurring at all, so it seems the issue is specific to newer projects rather than network related. Did the errors logged in the browser in my first screenshot give you any hints at all? I am trying to understand them myself but it seems at a glance as though no reason is given for why the project won't open, which I can't make sense of.

**Comment by AshleyScirra** [comment]
I'm afraid I have no idea what this could be, as there's nothing much useful in the screenshots. It works fine for me, and as far as I'm aware, all other users.

Perhaps there is some problem on Google Drive's side. You could try working around it by downloading your file to your local device and just opening it as a file instead.
