### ISSUE TITLE
bug report for lizard dash.

### ISSUE THREAD

**Issue by doald3** [Scirra/Construct-3-bugs#5629]
## Problem description

The game is not working even when i build an apk for it and i can't open the game through the cloud when i try it gives me an error. 

The game is not working even when i build an apk for it and i can't open the game through the cloud when i try it gives me an error. 

## Attach a .c3p
[
](https://drive.google.com/file/d/1_i2m8Yen1oh5Bqlf5cZrT7ybdlvI2EeC/view?usp=sharing)

## Steps to reproduce

1. the project does not work on my phone
2. the project does not open in my google chrome anymore.
3.i can't build my project anymore

## Observed result

![Screen Shot 2022-04-14 at 08 29 01](https://user-images.githubusercontent.com/103654060/163445150-83472570-2275-4f87-ba4a-e18ad4213228.png)
![Screen Shot 2022-04-14 at 08 33 37](https://user-images.githubusercontent.com/103654060/163445715-9993eda2-9fef-4f5c-8e69-b36219a3aa64.png)

## Expected result

i expect it to build so that i can focus on releasing the game.

## More details

yes it does on all those browsers.

**Affected browsers/platforms:** 

all of the above browsers and platforms.

**First affected release:** 

worked in r284 but broke in r285.3

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: blob:https://editor.construct.net/51799309-d5fd-442d-850c-d299de10aa97, line 502, col 4
Message: Uncaught InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Stack: null
Construct 3 version: r285.3
URL: https://editor.construct.net/
Date: Thu Apr 14 2022 12:11:32 GMT-0500 (Central Daylight Time)
Uptime: 10161.8 s

Platform information
Browser: Chrome
Browser version: 100.0.4896.88
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
C3 release: r285.3 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 5000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help unless you follow the bug report guidelines.
