### ISSUE TITLE
Focus problem with X and Y value in Animations editor

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#563]
## Problem description

Hello. I use Construct 3 for a long time now (I win the 2d place on the NG GameJam with my brother :-) Thanks again for the 1 year license :-) )
I  want to tell a recurent problem of ergonomy. A little bit annoying...
When I put a value in the animations editor ( X and Y for the Image point or a point of a collision box) I have always problem. I find it's not ergonomic.
If you clic on an X value for exemple, first a blue rectange select the value, and after the cursor appears right. I think you must choose one think : The blue rectangle OR the cursor.
I have always problem when i want to select the value (blue rectangle).
I think the "hold clic and go left or right to change value" is not adapted here. It would be better if you hold clic on the Up en Down arrow (Right) and go Up and Down.
Another bug with the actual system is if you hold clic on the value to select it and go left above the Y value, then it change the focus on the Y value...
Thank you in advance for your understanding. (And sorry for my bad english, i'm French ^^)

## Steps to reproduce

1. Select the X value by hold clic
2. keep holding clic and go left above Y value

## Observed result

Focus change on Y value

## Expected result

Keep Focus on X Value

## Steps 2 to reproduce

1. Select the X value by hold clic
2. keep holding clic and go left or right

## Observed result

X value change

## Expected result

I just want to select the value !  ;-)

This problem of focus appears not just in the Animation Editor.
Exemple : If you add an Event with value that must be specified in an Event Sheet : 
Hold Clic on a value, Keep holding Clic and Go outside the Window : The Blue Rectangle of selection go away and the cursor come at the right.

## Expected result

Keep the blue rectangle of selection

**Comment by DiegoScirra** [comment]
Fixed the issues with the Animations Editor. Checkout the changes in the next release, r45.
