### ISSUE TITLE
Layer interactivity setting is not shown in Debug View

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5632]
Sorry for posting this as a bug report, this is a minor thing and I'm worried it will get unnoticed on the suggestions platform.
This is clearly an oversight that the new "Interactive" setting is not available in Debug Mode, could you please add it?

![image](https://user-images.githubusercontent.com/36763350/163590328-7fc29048-149d-47c5-883b-9b90ba699d05.png)

**Comment by AshleyScirra** [comment]
Yeah, that looks like an oversight. Added for next beta.
