### ISSUE TITLE
Losing event sheet focus

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-3-bugs#5633]
## Problem description

I have the issue that I'm losing focus on the event sheet after editing some parameters and closing out the window with the enter key. It took me a while to be able to reproduce the bug and it turns out that the bug only occurs with an open expression window.

## Attach a .c3p

[lost_focus.zip](https://github.com/Scirra/Construct-3-bugs/files/8499529/lost_focus.zip)

## Steps to reproduce

https://user-images.githubusercontent.com/18266300/163668051-d365fe1e-d440-429b-b336-76219f173f79.mp4

- edit a parameter in an action 
- click the find expressions button 
( another bug is that F4 no longer opens the expression window even though it says so in the manual ) 
- click back into the parameters window 
- hit enter to confirm and exit the parameter window
- use the arrow key to navigate the event sheet
- if it still works, open up the parameters window again, use enter key to get out again and it should now no longer be possible to navigate the event sheet with the arrow keys 
( The bug only occurs if the parameters window is opened up together with the expression window, that's why it might needs to be closed and opened again once )

## Observed result

The event sheet loses focus after editing a parameter when the expression window is open 

## Expected result

To not lose focus

**Comment by AshleyScirra** [comment]
Both issues should be fixed for next beta (F4 shortcut and making sure focus returns to the event sheet).
