### ISSUE TITLE
Copying a cropped animation frame doesn't preserve the crop

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#5634]
## Problem description

After cropping a frame in a sprite's animation, copying that frame to another animation ignores the crop, and pastes the frame's original image.

## Attach a .c3p

https://drive.google.com/file/d/1UVj9JhhRg3q5PeUX2a_1lR0tUGT5Nwnz/view?usp=sharing

## Steps to reproduce

1. Open the attached project.
2. Open the sprite in the animation editor.
3. Select any frame in Animation 1.
4. Make a selection of part of the image (i.e. the character's head) and click Crop.
5. Right-click the frame and click Copy.
6. Add a new Animation (Animation 2 should appear)
7. Select the new Animation 2.
8. Paste the frame into the Animation 2. 

## Observed result

The original, uncropped image is pasted into the new frame.

## Expected result

The current version of the frame, containing the cropped image, should be pasted.

## More details

**Affected browsers/platforms:** Chrome 100.0.4896.127, Mac 11.6

**First affected release:** r290

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
