### ISSUE TITLE
Editor crashes when copying an object with missing template name.

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5637]
## Attach a .c3p

https://www.dropbox.com/s/hyjp07g0kjngc1z/MissingTemplateName.c3p?dl=0

## Steps to reproduce

1. Try to copy and then paste the blue sprite

## Observed result

Editor crash.

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: missing template name
Stack: Error at Function.xa.eRa (https://editor.construct.net/r290/main.js:941:289) at window.assert (https://editor.construct.net/r290/main.js:859:38) at Lv (https://editor.construct.net/r290/projectResources.js:78:16) at https://editor.construct.net/r290/projectResources.js:836:246 at Array.some () at bH.dm.Fa (https://editor.construct.net/r290/projectResources.js:836:238) at d.tQb (https://editor.construct.net/r290/projectResources.js:737:285) at d.Fa (https://editor.construct.net/r290/projectResources.js:789:361) at window.ul.A9a (https://editor.construct.net/r290/components/editors/layoutView/layoutView.js:118:123)
Construct 3 version: r290
URL: https://editor.construct.net/r290/
Date: Sun Apr 17 2022 18:49:40 GMT+1000 (Australian Eastern Standard Time)
Uptime: 109.4 s

Platform information
Browser: Chrome
Browser version: 100.0.4896.88
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.3958333730697632
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
C3 release: r290 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
