### ISSUE TITLE
Add 'toggle' option to system layers action

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5638]
## Problem description

‘toggle’ option should be support system  layers action. 
- Set layer visible
- Set layer effect enabled
- Set layer interactive (Note that it is currently a radio button)

also
- Set Pixel rounding
- Set fullscreen scaling

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please file these as suggestions.
