### ISSUE TITLE
Custom plugin from construct 2 to 3 error

### ISSUE THREAD

**Issue by kishlayaS** [Scirra/Construct-3-bugs#564]
## Problem description

My custom plugin when tried to modify from construct 2 to 3 is throwing "ACE language string 'description' missing

## Attach a .c3p

[ArcadixPlugin.zip](https://github.com/Scirra/Construct-3-bugs/files/1107533/ArcadixPlugin.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

![image](https://user-images.githubusercontent.com/23715042/27620325-785579c4-5be6-11e7-8db3-33787b66efce.png)

This plugin give us two event, Initial event (triggers when task is initially loaded) and solution event (When 'show solution' button is pressed ) in the task.

![image](https://user-images.githubusercontent.com/23715042/27620278-287426b2-5be6-11e7-8439-45a6966f1d29.png)

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: ACE language string 'description' missing for '0' @ Error: ACE language string 'description' missing for '0' at window.ǃBOQ.ǃBow (https://editor.construct.net/r41/main.js:61:291344) at window.ǃBOQ.ǃBow (https://editor.construct.net/r41/main.js:61:293080) at new window.ǃBOQ (https://editor.construct.net/r41/main.js:61:296830) at Function.ǃB.ǃd (https://editor.construct.net/r41/main.js:2:203820) at window.ǃBjw.ǃBjx (https://editor.construct.net/r41/main.js:61:298351) at window.ǃBkv.ǃBAQ (https://editor.construct.net/r41/main.js:61:402164) at C.ǃtv (https://editor.construct.net/r41/main.js:71:27806) at Object.n.push.ǃB.ǃ_K [as ǃfwz] (https://editor.construct.net/r41/main.js:71:28179) at n (https://editor.construct.net/r41/main.js:2:258053) at t (https://editor.construct.net/r41/main.js:2:257839)
Stack: Error: ACE language string 'description' missing for '0' at window.ǃBOQ.ǃBow (https://editor.construct.net/r41/main.js:61:291344) at window.ǃBOQ.ǃBow (https://editor.construct.net/r41/main.js:61:293080) at new window.ǃBOQ (https://editor.construct.net/r41/main.js:61:296830) at Function.ǃB.ǃd (https://editor.construct.net/r41/main.js:2:203820) at window.ǃBjw.ǃBjx (https://editor.construct.net/r41/main.js:61:298351) at window.ǃBkv.ǃBAQ (https://editor.construct.net/r41/main.js:61:402164) at C.ǃtv (https://editor.construct.net/r41/main.js:71:27806) at Object.n.push.ǃB.ǃ_K [as ǃfwz] (https://editor.construct.net/r41/main.js:71:28179) at n (https://editor.construct.net/r41/main.js:2:258053) at t (https://editor.construct.net/r41/main.js:2:257839)
Construct 3 version: r41
URL: https://editor.construct.net/
Date: Wed Jun 28 2017 09:22:50 GMT+0530 (India Standard Time)
Uptime: 7.1 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r41

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 730 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
You are probably missing a string in the language file. Please refer to the SDK documentation: https://www.scirra.com/doc/c3sdk/the-language-file.html
