### ISSUE TITLE
Can't copy "Duration" value in Animation Editor

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#5640]
## Problem description

In the Frame Properties of Sprite's Animation, the Duration value can't be copied. Instead, the frame's image is copied. 

## Attach a .c3p

(Any project with animations; Kiwi Story example below)
 
## Steps to reproduce

1. Open the Kiwi Story project
2. Open NPC_Kiwi sprite (Level Objects -> Player -> NPC_Kiwi)
3. Click on the Idle animation. 
4. Click on Frame 0 to open the Frame Properties.
5. Click on the value in the Duration field ("1").
6. Change the value to 5.
7. Highlight the value ("5"), then press Cmd/Ctrl-C to Copy it.
8. Click on the Jump animation.
9. Click on Frame 0. 
10. Click on the Duration field.
11. Press Cmd/Ctrl-V to Paste the Duration value of 5.

## Observed result

The image from Idle's Frame 0 is pasted over the image.
 
## Expected result

The copied Duration value of 5 should have been pasted over the value of 1. 

## More details
I believe what's happening is that the image area is still active while any of the Frame or Animation Properties are being edited. For example, if you select the Animation Speed value, and press Cmd/Ctrl-A to select all, the entire image is selected as well.

**Affected browsers/platforms:** Chrome 100, MacOS 11.6

**First affected release:** 290

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
