### ISSUE TITLE
nEW UPDATE UNHANDLE REJECTION

### ISSUE THREAD

**Issue by beebits** [Scirra/Construct-3-bugs#5642]
wHEN ENTER INTO THE SCENE WITH THE LAST VERSION 291 BETA
i USING CHROME

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'length') @ TypeError: Cannot read properties of undefined (reading 'length') at CCG.uh.g.J.$Ea.ed (https://editor.construct.net/r291/main.js:1424:182) at window.Pcb.leb.ed (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:17:454) at window.Pcb.nc (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:446) at window.Pcb.eGa (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:122) at Array. (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:8:101) at window.cIb.dispatchEvent (https://editor.construct.net/r291/main.js:1058:42) at jS (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:39:423) at window.cIb.lC (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:126:484)
Stack: TypeError: Cannot read properties of undefined (reading 'length') at CCG.uh.g.J.$Ea.ed (https://editor.construct.net/r291/main.js:1424:182) at window.Pcb.leb.ed (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:17:454) at window.Pcb.nc (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:446) at window.Pcb.eGa (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:122) at Array. (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:8:101) at window.cIb.dispatchEvent (https://editor.construct.net/r291/main.js:1058:42) at jS (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:39:423) at window.cIb.lC (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:126:484)
Construct 3 version: r291
URL: https://editor.construct.net/r291/
Date: Wed Apr 20 2022 15:26:10 GMT+0200 (hora de verano de Europa central)
Uptime: 70.8 s

Platform information
Browser: Chrome
Browser version: 100.0.4896.127
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
C3 release: r291 (beta)
Language setting: es-ES

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible to help. It seems to be working fine for me in r291.

**Comment by beebits** [comment]
Ok, but i change to 290 and works fine, but in 291 i have this problem...

**Comment by beebits** [comment]
I save again, into the 291 and now works fine
