### ISSUE TITLE
(multiple) instance Object adjusting Z elevation

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5644]
## Problem description

This is another question by #5643.  
When I select multiple instance objects, I want to move their Z elevation at the same time. But I can't do it. I can only edit it one by one.This is very inefficient.

## Attach a .c3p

[multiple_instance_Zelevation.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8523307/multiple_instance_Zelevation.c3p.zip)

## Steps to reproduce

1. select them and try adjust them Z elevation as a whole

## Expected result

it can support spinners. It doesn't matter if the Real value is not displayed, Or can display the value of the current trim.
![Snipaste_2022-04-21_00-19-51](https://user-images.githubusercontent.com/45864744/164277064-4d40e1c3-b6ee-442f-b6fa-486b90d509e6.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is also not currently supported. Please file a feature request.
