### ISSUE TITLE
Image Point Moves After Reaching First/Last Frame or Animation in Animations Editor

### ISSUE THREAD

**Issue by brainwavecreations** [Scirra/Construct-3-bugs#5645]
Problem description:
When I set the image point for an entire animation(s). If I am cycling through the Animation frames quickly using CTRL + Arrow keys. If going too quickly, it will move the image point on the first or last frame, while holding down CTRL and pressing/tapping the directional arrow.  Pressing the arrow key too quickly and reach the first or last frame, and continue pressing the arrow key.

The same thing goes for using the CTRL + Arrow Up or Down to cycle through the various Animations on a Sprite Object as well. If reaching the final animation in the list, it starts moving the image point down. And, reaching the first animation at the top of the list, it starts moving the image point upwards, if the key is still held or being pressed after reaching that Animation.

Attach a .c3p:
Any .c3p file would do. Create a new project, a simple Sprite Object, duplicate frames. Then see the image point moved, after doing the above. I could create a brief YouTube video as well, if that would be at all helpful.

Steps to reproduce:
Create a new project, a simple Sprite Object, duplicate frames. Then see the image/origin point moved, after doing the steps in the above description.

Observed result:
Image Point/Object Origin moves by pixel(s) if first/last frame, or first/last Animation in Animations list is reached, while still holding CTRL and pressing/tapping the arrow key in that same direction.  Quick YouTube Video explaining the issue here: https://www.youtube.com/watch?v=-fneiqGHgyI

Expected result:
Image Point/Object Origin should not move, when the above is performed.  Basically, check to see if First/Last Frame in the Animation is open.  Or, if the first/Last Animation in the Animations list has been reached.  If either of these conditions are met, do not move the Origin or Image Point while holding down the CTRL key.

More details: This listed as a bug fix in Construct 3 r290, but it still persists.  It basically means being extra careful while checking the image point/origin point for an Object, while cycling through it's animation frames and animations using the CTRL shortcuts.  I've just been trying to be super careful when cycling through Frames and Animations, and stopping when reaching the first or last of either.  But, I still wind up moving the Point from time to time.

Affected browsers/platforms:
Chromium based browsers is all I use

First affected release:
Not sure, it's been ongoing

System details:
Windows 10, latest updates, latest Chrome web browser.

**Comment by DiegoScirra** [comment]
I though the problem was the specific case of keeping **Ctrl + arrow key** down which would cause quick cycling through frames/animations and upon reaching the end/beginning some unwanted image point changes could happen by accident.

Since the issue seems to be more general than that, starting on the next beta, image points won't move at all while **Ctrl/Cmd** is pressed. That should take care of everything.

**Comment by brainwavecreations** [comment]
Awesome!  Thank you so much, @DiegoScirra :)
