### ISSUE TITLE
Qol improvement to tab selection of object under objects.

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5646]
**This is not a bug, but I post it here as it's too small for the suggestion board.**

Currently tab clicking works great for selecting objects that are behind objects in the editor, this is a really useful feature.
 
But in many cases I want to reposition the object, which I usually do by dragging or add it to a hierarchy etc. by right clicking.
Sadly if you right click or drag it still selects the object on top and not the tab selected object.

I would suggest if the object has been selected by tab clicking it will now be the target for drags and right-click instead of the object on top.

**Comment by AshleyScirra** [comment]
This is a suggestion, and could well be complicated and not at all simple, as the logic for all the interactions in the Layout View is highly complex. It could also introduce its own usability issues, as after a tab-click you could end up stuck on that instance with no way to intentionally select the instance on top. Please post a suggestion and make sure such edge cases are considered in your proposal.
