### ISSUE TITLE
r291 crashes when opening certain layouts

### ISSUE THREAD

**Issue by Kapusta-dev** [Scirra/Construct-3-bugs#5649]
## Problem description

This has been reported in the update notes but I don't see a formal bug report so opening one here.
Certain layouts will crash when opening them in the new r291 beta.

Error: Cannot read properties of undefined (reading 'length')

<details><summary>Full Error Report</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'length') @ TypeError: Cannot read properties of undefined (reading 'length') at CCG.uh.g.J.$Ea.ed (https://editor.construct.net/r291/main.js:1424:182) at window.Pcb.leb.ed (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:17:454) at window.Pcb.nc (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:446) at window.Pcb.eGa (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:122) at Array. (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:8:101) at window.cIb.dispatchEvent (https://editor.construct.net/r291/main.js:1058:42) at jS (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:39:423) at window.cIb.lC (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:126:484)
Stack: TypeError: Cannot read properties of undefined (reading 'length') at CCG.uh.g.J.$Ea.ed (https://editor.construct.net/r291/main.js:1424:182) at window.Pcb.leb.ed (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:17:454) at window.Pcb.nc (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:446) at window.Pcb.eGa (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:9:122) at Array. (https://editor.construct.net/r291/components/bars/layersBar/layersBar.js:8:101) at window.cIb.dispatchEvent (https://editor.construct.net/r291/main.js:1058:42) at jS (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:39:423) at window.cIb.lC (https://editor.construct.net/r291/components/editors/layoutView/layoutView.js:126:484)
Construct 3 version: r291
URL: https://editor.construct.net/r291/
Date: Thu Apr 21 2022 01:48:25 GMT-0400 (Eastern Daylight Time)
Uptime: 150.8 s

Platform information
Browser: Chrome
Browser version: 100.0.4896.127
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
C3 release: r291 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

## Attach a .c3p

I cannot reproduce this with a simple project newly created in r291/r290.
Opened a few sample projects to test as well and those worked without any issues, so I'm not sure what the exact contributing factor is here.

Will be willing to share a private project via e-mail or any other means of direct contact without publicly posting it.

## Steps to reproduce

Unable to reproduce. 
Crash report attached in Problem Description section.

## Observed result

Editor will crash with error described in Problem Description section when opening certain layouts.

## Expected result

The layout should open.

## More details

**Affected browsers/platforms:** All browsers affected.

**First affected release:** r291

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 100.0.4896.127
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
C3 release: r291 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 80 gb
Storage usage (approx): 60 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.

This happens if you create a new layout while the Layers Bar is closed and then save your project, at this point the project is saved with some data that C3 can't load properly. When you open it again and open the Layers bar, C3 crashes when trying to show the layers for the layout that was previously created while the Layers bar was closed.

If the Layers Bar is open at all times then the problem never happens.
