### ISSUE TITLE
Publisher ID property is missing from the Mobile Advert documentation

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5651]
## Problem description

Publisher ID property is missing from the [MobileAdvert documentation](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/mobile-advert).

It would also help to have some links to the related Google docs, and the expected results when using this ID, and also the common issues (if any).

Thank you!

**Comment by DiegoScirra** [comment]
The documentation for the Mobile adverts plugin has been updated to include information about showing adverts in web exports.
