### ISSUE TITLE
Objects on specific layer are missing resize handles

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#5652]
## Problem description

Objects on a layer are missing resize handlers. I can still move the objects and resize them via the properties, but they don't show the little white resize handlers. I think it might have something to do with being on a global layer, but I cannot reproduce it in a fresh project. Any object moved to this layer will also lose it's handles.

![nohandles](https://user-images.githubusercontent.com/31101309/164552709-f754a5fa-5106-458f-b168-e1289ed76f2c.PNG)

## Attach a .c3p

[foobar.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8535072/foobar.c3p.zip)

## Steps to reproduce

1. Click an object on the layout

## Observed result

Object is missing it's resize handles

## Expected result

Resize handles to be there

## More details
There's also a crash happening when attempting to open the other layout that contains the global layer. The handles have been missing since before the crash was happening! For reference https://github.com/Scirra/Construct-3-bugs/issues/5653

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 100.0.4896.127
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
C3 release: r291 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 28 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
@DiegoScirra - looks like the UI state is in an inconsistent state - it thinks the layer is invisible but it is actually being shown, and the resize handles are hidden for invisible layers.

**Comment by DiegoScirra** [comment]
What is happening is that those instances are coming from a global layer. The global layer is locked and invisible in it's original layout. Overridden layers can be set to be **Visible in the editor**, independently of the global layer, but the instances themselves still report to be in a locked invisible layer, that is why you can't see the resize handles.

This is similar to issue #4126. In that issue the **Parallax in Editor** property was made to be inherited from the global layer if one was available (instead of being independent to each layer) because otherwise it was confusing. @AshleyScirra  Should we do the same here?

**Comment by AshleyScirra** [comment]
I think it would be annoying if the *Visible in editor* option was taken from the global layer - I think it is useful to be able to toggle it individually per layout depending on what kind of editing you are doing. So I think we need to allow a per-layout toggle, and make sure the editor checks the right thing when working out if the layer is visible or not.
