### ISSUE TITLE
Global layers/Layout layers - objects vanishing when moving between layers

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#5654]
## Problem description

Objects vanish under specific conditions when moving them to a different layer. I think this has something to do with global layers. Also the properties show layers that are technically not even in the same layout, I thought I might add this here. It kinda makes sense but it's also kinda confusing.

![layers](https://user-images.githubusercontent.com/31101309/164554018-4bc36d10-8871-45d5-9ebd-dad02bf79b46.PNG)

## Attach a .c3p

[foobar.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8542414/foobar.c3p.zip)

## Steps to reproduce

1. Click one of the objects
2. In the properties bar set the layer to "main" (or any other works too)
3. Now click the object again

## Observed result

The object evaporates entirely (as if deleted, check with find all references)

## Expected result

The object to move to the layer I selected. Though that might be weird considering there's layers that aren't on the layout.

## More details
Unrelated to the crash https://github.com/Scirra/Construct-3-bugs/issues/5653 I had this happen before.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 100.0.4896.127
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
C3 release: r291 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 29 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Please attach a project file as per the bug report guidelines otherwise it's impossible for us to help.

**Comment by AshleyScirra** [comment]
This is quite a confusing sample project, but I think this is actually by design. What is happening is layout "start" is using a global layer for "HUD". In this case it is showing the "HUD" layer from layout "thiscrashes", which is where the global layer is defined. So the objects on that layer are really from a different layout. When you change which layer the object is on, since you are editing an object from the "thiscrashes" layout, it moves it to the "main" layer on the "thiscrashes" layout. This is why the layer dropdown lists all the layers from the "thiscrashes" layout, and if you go to that layout after changing the layer, you can see the object has been moved to the "main" layer there.
