### ISSUE TITLE
Playable ads export seems broken on (target.my.com)

### ISSUE THREAD

**Issue by arturbier** [Scirra/Construct-3-bugs#5656]
## Problem description

In the test mode of Playable ADS on the platform target.my.com black screen and console errors.

## Attach a .c3p

The C3P file renamed to zip
[DC playable.zip](https://github.com/Scirra/Construct-3-bugs/files/8539309/DC.playable.zip)

## Steps to reproduce

1. Make a playable ad export. Use the meta tag `<meta name="ad.size" content="width=100%,height=100%">` for responsive design in HTML file.
2. Open the my target playable preview - [dashboard my target](https://target.my.com/dashboard)
3. Look at black screen.

## Observed result

The ad fails to load with a black screen and fails with this error:
![2022-04-21_22-33-32](https://user-images.githubusercontent.com/78679486/164674860-06624d89-d8f3-488c-88bb-f1ea7a20b203.png)

## Expected result

The ad should load without errors and a black screen

## More details
Does not work with worker mode and without worker mode

**Comment by AshleyScirra** [comment]
This is caused by the server hosting the game: it specifies a Content Security Policy (CSP) that blocks the Construct game from loading. The server configuration needs to be changed. You'll need to take it up with the host.
