### ISSUE TITLE
file copy as Text

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5657]
## Problem description

This is a suggestion, but I post it here as it's too small for the suggestion board.    

Is it possible to allow copying of file to plain text. For example, I want to copy the plain text of the Array file to have the dictionary store multiple arrays. Currently, I can only download the file, copy on local and then go back to the C3 to paste.  

![Snipaste_2022-04-23_10-54-39](https://user-images.githubusercontent.com/45864744/164872148-b22b4278-3c38-474b-972e-2d9eae5885df.png)

It would be easier if it could be like the 'copy as text' option of eventsheet  
![Snipaste_2022-04-23_11-12-26](https://user-images.githubusercontent.com/45864744/164872991-47551dd2-3d07-484b-9e16-16a7ab518834.png)

## Attach a .c3p

[array-plain-text-suggestion.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8546044/array-plain-text-suggestion.c3p.zip)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please post this as an enhancement.

Please note the issue tracker is intended for defects. Most of the time suggestions should be posted to the suggestion platform. There is sometimes a grey area where it is not clear whether something is a defect or a suggestion; we sometimes deal with this on the issue tracker at our discretion.
