### ISSUE TITLE
Construct 3 - Suggestion For C3 In-App Notifications

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#566]
## Problem description

I would like to propose a change to the current system of _In-App Notifications_.
Currently it seems like each notification is running on it's own, set timer or "rule".

While there are no real problems caused by the current approach, I still think that it would be better to improve the current method and make it more customizable for users.

## My suggestion

I'd like to suggest simple, technical changes to notifications and keep the design as is. To get to the point, I think it would be better to have a global setting for all notifications, probably inside the settings menu.

Basically an option to set the time of initial visibility before it automatically fades out.
`Set Notification Timer: #TEXTBOX# [0-120]`
(time in seconds; default is "0" = notification will remain on-screen and requires to be closed by the user.)

For the notification itself, I would recommend adding an option to close it and an option to quickly access Construct 3's settings menu or even a dedicated sub-menu to set the notification timer.

Here is a quick image from the web push-notification API and how it could look like:

![pushnotification](https://user-images.githubusercontent.com/15656049/27660104-33e9b5dc-5c56-11e7-9367-f3ac6061cf8e.PNG)

Additionally I'd like to suggest a "Notification Log", in case for people that have missed notifications. 
It would be something like Github's bell icon on the top-right.

## Possible advantages:
**For Users:**
+ Users that frequently step away from their PC get to see all notifications (if set to "0")
+ Users that absolutely hate getting notifications could put the timer to "1" in order to make them less annoying overall (e.g. notifications from successful cloud uploads)

**For Scirra (everyone working on Construct 3)**
+ No requirement to manually set or change notification visibility properties anymore
+ No need to apply changes to individual notifications if users request it

## Last words:
I know that this change request might not seem to be _relevant_ right now, since there aren't a lot of push-type notifications in use currently. (Updates; Offline Usage; Cloud Success etc.)

However, I think that this could be considered as a feature to make Construct 3 notifications future proof.
_~Thanks and looking forward towards a response._

**Comment by AshleyScirra** [comment]
I'm not sure this is actually important. The notifications appear in the lower-left and are already pretty ignorable if you don't care about them. They don't cover up anything important or otherwise get in the way. Also IMO they're not really important enough to warrant more features, since they appear for things like undo and redo, simply as visual confirmation that your action did something.

This is very much a feature suggestion so I think it would be best to add it to the feature tracker at https://construct3.ideas.aha.io/ so we can weigh up if other people think it's important.
