### ISSUE TITLE
sine behavior eat draw call when a tilemap on screen

### ISSUE THREAD

**Issue by wertt22** [Scirra/Construct-3-bugs#5660]
## Problem description
sine behavior eat draw call when a tilemap on screen

## Attach a .c3p
[drawcallbug.zip](https://github.com/Scirra/Construct-3-bugs/files/8552957/drawcallbug.zip)

## Steps to reproduce

1.add a sprite with sine behavior
2.add a tilemap and set tile
3.run debug

## Observed result

drawcall use 50%
## Expected result

if delete sine! drawcall use 0%
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is not a bug. If nothing changes, Construct skips drawing a frame, and so there will be no draw calls. The sine behavior moving will cause changes and therefore cause everything to be redrawn. The draw calls are the time it takes to draw the extremely large tilemap, not the sine behavior.
