### ISSUE TITLE
Browser.QueryParam not working in Debug preview

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5661]
## Problem description

Browser.QueryParam not working in Debug preview. It works fine in normal preview, but is empty in debug preview.

## Attach a .c3p
[Test Params.zip](https://github.com/Scirra/Construct-3-bugs/files/8555644/Test.Params.zip)

## Steps to reproduce

1. Run normal preview in a new tab.
2. Change the preview link like this: "https://preview.construct.net/local.html?user_id=123"
3. Click enter to load the new preview
4. The text should show "123"
5. Repeat the steps but using debug preview.

## Observed result
The text is empty

## Expected result
The text should show "123"

## More details

**Affected browsers/platforms:** Tested on Firefox 99.0.1

**Comment by AshleyScirra** [comment]
In debug mode the preview actually runs in an iframe, so it does not see the query string parameters (or hash) of the debugger frame. However it's relatively straightforward to copy the debugger query string to the preview iframe URL, which has been done for the next beta.
