### ISSUE TITLE
"Has LineOfSight" condition unintentionally triggers "Object.LineOfSight.HitUID"

### ISSUE THREAD

**Issue by fvcalderan** [Scirra/Construct-3-bugs#5663]
## Problem description

"Has LineOfSight" condition unintentionally triggers "Object.LineOfSight.HitUID". Shouldn't "Object.LineOfSight.HitUID" only be triggered by a manual ray cast (Cast Ray action from an Object)?

## Attach a .c3p

[LOSBug.zip](https://github.com/Scirra/Construct-3-bugs/files/8572711/LOSBug.zip)

## Steps to reproduce

1. Run the game
2. Notice that all enemies are destroyed on Main layout start
3. Comment the 3rd event from MainEvents and run the project again
4. No enemies are destroyed this time

## Observed result

"Has LineOfSight" condition cast rays

## Expected result

"Has LineOfSight" condition doesn't cast rays

## More details

**Affected browsers/platforms:** MS Edge on Windows 11, Google Chrome on Windows 11 and Brave on Windows 11.

**First affected release:** r285.3 stable

**Comment by AshleyScirra** [comment]
Checking line of sight is a variant of raycasting: it casts a ray but returns the result as a boolean.

So arguably it's a feature, but even apart from that I don't think this ought to be changed for two reasons:

1) Some projects may be making use of this, so changing it could be a breaking change.

2) It only makes sense to check the HitUID expression immediately after a raycast. Checking it in regular events without a raycast is pretty much meaningless. Suppose you have 5 different places you raycast. In a separate event, HitUID is just the leftover result of whatever you last did, which isn't really useful. So really you should only check it immediately after a raycast - and if you want to hold on to that result, store it in something like an instance variable.
