### ISSUE TITLE
[Remote Preview] Signalling server is down

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#5666]
It seems the signalling server is down. I've tried in a clean project and through a VPN in different regions, just to be sure.

![image](https://user-images.githubusercontent.com/31282960/165908307-f89c39f2-0fa3-4eb4-b97f-ce522683e324.png)

**Comment by AshleyScirra** [comment]
It should be back up and running now. Apologies for the inconvenience.
