### ISSUE TITLE
Construct 3 - No Option To Cancel Active Downloading Process

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#567]
## Problem description

There is currently no way in order to cancel an active project downloading process.
This makes it really frustrating for users with slow connections, since we're required to wait through the whole downloading process, which can take quite some time.

## Attach a .c3p

*Not Required*

## Steps to reproduce

1. Open a fairly large project on a slow Internet connection
2. Notice that you cannot cancel the downloading process

## Observed result

Construct 3 doesn't offer a button in order to cancel an active downloading process.

## Expected result

Construct 3 should have a "cancel" button inside the downloading dialog.

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

**Comment by shortercode** [comment]
This should be doable, I've started to lay some ground work for it but given the amount of async code in the area it's a little fiddly.

**Comment by shortercode** [comment]
@TheRealDannyyy Okay I've just added this in for r45, things are a little complicated around this so it would be appreciated if you could try it out and let me know how you get on. At the moment only downloads can be cancelled, not uploads. This is for 2 reasons:

1. Cancelling during an upload could leave the remote file in a strange state ( most likely having a size of 0 )
2. As it uses a status message not a dialog there's no place to put a cancel button...

Also once the file has been downloaded the progress bar appears for loading the project, this can't be cancelled at the moment.

**Comment by TheRealDannyyy** [comment]
Works well on my end, thanks for adding this. No probs about the upload cancelling feature.

**Comment by shortercode** [comment]
No problem, glad to hear it hasn't broken anything yet!
