### ISSUE TITLE
Platform's "Fall through" action isn't working in a consistent way.

### ISSUE THREAD

**Issue by fvcalderan** [Scirra/Construct-3-bugs#5671]
## Problem description

The "Fall through" action from the Platform behavior isn't working consistently, even in an ideal environment.

## Attach a .c3p

[FallBug.zip](https://github.com/Scirra/Construct-3-bugs/files/8603763/FallBug.zip)

## Steps to reproduce

1. Execute the project.
2. Try to fall through the platform consistently by pressing "Space" on the keyboard (won't work).
3. Stop the project.
4. Enable the "Set Y to Self.Y + 1" action in the event sheet.
5. Execute the project.
6. Try to fall through the platform again (works fine).

## Observed result

The object with the platform behavior won't do anything.

## Expected result

The object with the platform behavior falls through the platform.

## More details

**Affected browsers/platforms:** Chrome on Windows 11, Edge on Windows 11

**First affected release:** r285.3

</details>

**Comment by brushfe** [comment]
I had a similar issue in the past, but it was solved by changing "Framerate Mode" to from Unlimited back to V-Synced

**Comment by AshleyScirra** [comment]
@brushfe - interesting point, this only happens because the project uses unlimited framerate mode, which is only intended to be used for performance benchmarking. If you set it back to v-synced it works fine.

However this suggests framerate-dependent behavior in the 'Fall through' action, which should be fixed anyway.

**Comment by brushfe** [comment]
Oh wow, I'm glad that worked out!

**Comment by AshleyScirra** [comment]
Fixed for next beta.
