### ISSUE TITLE
Crash when drag-and-dropping image onto the editor (Invalid size?)

### ISSUE THREAD

**Issue by simoneddeland** [Scirra/Construct-3-bugs#568]
## Problem description

The editor crashes sometimes when drag-and-dropping an image onto the layout part of the editor. I can't reliably reproduce this crash but it has happened to me randomly at least on 10 different occasions during the last 2 weeks, even on the latest build and always when drag-and-dropping an image onto the editor. As far as I can remember, the error has always been "invalid size".

This seems to be the same error as https://github.com/Scirra/Construct-3-bugs/issues/504, I know that issue was closed due to no repro but since it has affected me quite a few times as well I thought that you might want to look in to it. The crashes I got today all mentioned the same error (invalid size) on the same line, see the crash report below.

## Attach a .c3p

I have no reliable way to reproduce, see below.

## Steps to reproduce

There is no reliable way for me to reproduce this error since it seems to happen randomly, even though I've been trying. I could reproduce the error once by using the two images attached in this zip file: [grass images.zip](https://github.com/Scirra/Construct-3-bugs/files/1111918/grass.images.zip)

1. Create a new project.
2. Drag-and-drop the image grassMid onto the layout.
3. Drag-and-drop the image grassLeft onto the layout.

Two consecutive times this cause Construct 3 to crash, I pressed the "Restart" button that appeared together with the crash report inbetween the two incidents. I have not been able to reproduce the crash this way after restarting the Chrome window though, even after trying a lot of times.

## Observed result

C3 is crashing.

## Expected result

C3 should not crash.

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r41/main.js, line 61, col 123411
Message: Uncaught Error: invalid size
Stack: Error: invalid size at C.ǃBqo (https://editor.construct.net/r41/main.js:61:123417) at window.ǃBpw.ǃBqg (https://editor.construct.net/r41/main.js:61:110817) at window.ǃBpw.ǃBq_ (https://editor.construct.net/r41/main.js:61:111065) at window.ǃBpw.ǃBqG (https://editor.construct.net/r41/main.js:61:110590) at window.ǃBqj.ǃBWJ (https://editor.construct.net/r41/main.js:61:113464) at C.ǃBWJ (https://editor.construct.net/r41/main.js:61:122461) at p.ǃBWJ (https://editor.construct.net/r41/main.js:61:191983) at d.ǃI.ǃfz (https://editor.construct.net/r41/main.js:61:382296) at d.ǃI.ǃfz (https://editor.construct.net/r41/plugins/sprite/plugin.js:1:8817) at d.ǃI.ǃe (https://editor.construct.net/r41/plugins/sprite/plugin.js:1:8621)
Construct 3 version: r41
URL: https://editor.construct.net/index.html
Date: Thu Jun 29 2017 13:47:42 GMT+0200 (Centraleuropa, sommartid)
Uptime: 57882 s
Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r41
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r45.
