### ISSUE TITLE
Accelerometer does not work in Construct Arcade

### ISSUE THREAD

**Issue by CalebBennetts** [Scirra/Construct-3-bugs#5680]
## Problem description

Gyroscope not detected with Construct Arcade exports.

## Attach a .c3p

[Link to Project File on Google Drive](https://drive.google.com/file/d/1q-Tk4cERwxywXRgQygl7lqix6UJkdlBp/view?usp=sharing)

## Steps to reproduce

1. Test the project on a mobile device with remote preview. The numbers change in response to gyroscope and accelerometer input.
2. Export the project for Construct Arcade.
3. Upload the exported project to Construct Arcade.
4. Open the project on a mobile device and attempt to use the gyroscope.

## Observed result

The project does not detect gyroscope or accelerometer input, and the numbers in the sprite font display stay at zero. Otherwise, the project seems to be running fine.

## Expected result

I expect the numbers to change when I move or rotate the phone. This works correctly in both remote preview and with the HTML5 export uploaded to itch.io.

## More details

**Affected browsers/platforms:**

The situation is only applicable to mobile devices.
Only tested in Chrome on Android.
Remote preview works correctly.
HTML5 Game export works correctly, tested through itch.io.
Construct Arcade export, tested through the Construct Arcade, does not work.
Have only tested from Construct 3 Version 293.2.

## System details

<details><summary>View details</summary>

Platform information

Browser: Chrome
Browser version: 101.0.4951.41
Browser engine: Chromium
Context: webapp
Operating system: Android
Operating system version: 10
Device type: mobile
Device pixel ratio: 2.625
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 10; SM-N960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Mobile Safari/537.36
C3 release: r293.3 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 67 gb
Storage usage (approx): 92 mb (0.1%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Nothing is missing. Everything is OK!

WebGL information

Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Qualcomm
Renderer: Adreno (TM) 630
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions:

    EXT_color_buffer_float
    EXT_color_buffer_half_float
    EXT_float_blend
    EXT_texture_filter_anisotropic
    EXT_texture_norm16
    OES_texture_float_linear
    WEBGL_compressed_texture_astc
    WEBGL_compressed_texture_etc
    WEBGL_compressed_texture_etc1
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context
    WEBGL_multi_draw

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by CalebBennetts** [comment]
Update: After more-extensive testing with about 5-10 devices, the web export on itch.io only worked correctly on roughly 1/3 of devices, including some Androids and _possibly_ 1 iPhone. All others tested performed the same way as described in the observed result in the main bug report. So, unfortunately, it's no longer clear if the issue is export method, specific version of device used, or some combination of the two.

**Comment by AshleyScirra** [comment]
It looks like your project attempts to use motion/orientation without first requesting permission. It's not guaranteed to work unless the user approves permission to use it. Refer to the Touch manual entry for more details: https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/touch
