### ISSUE TITLE
[Chrome] Oops! There was an error loading Construct

### ISSUE THREAD

**Issue by l-t-m-f** [Scirra/Construct-3-bugs#5682]
## Problem description
When I try to open the editor, I get the "Oops! There was an error loading Construct". 
I tried all the possible solutions and nothing does it.

## Attach a .c3p
Editor access problem.

## Observed result

![image](https://user-images.githubusercontent.com/33851651/167278000-64873356-e165-4163-bdd1-2dc1fb499b9d.png)

## Expected result

I get to the editor.

## More details

This error was happening and I fixed it with Clear the cache. However, my editor was in French.
When I put it back in English the error appeared again and now Clearing the cache doesn't fix it anymore.
I'm stuck and can't get in the editor at all now.

**Affected browsers/platforms:** Only in Construct 3 Google chrome. In Firefox I can access the editor.

**First affected release:** It was working fine 2 days ago.

## System details

<details><summary>View details</summary>

</details>

**Comment by l-t-m-f** [comment]
I closed this issue because I fixed it.
It was conflict with an extension after all. Should I report which extension to you or vice-versa, should I report the conflict to them ?
Sorry for spamming x)

**Comment by AshleyScirra** [comment]
If a browser extension breaks Construct, please let us know which one, but report the problem to the browser extension developer.
