### ISSUE TITLE
Janking On Debug APK even when running at 60fps

### ISSUE THREAD

**Issue by simonpaulkeating** [Scirra/Construct-3-bugs#5685]
## Problem description

On Android Device (tested on Samsung Galaxy A7 Lite and Huwai Mate Pro 10) I see janking every few seconds even though the framerate is a solid 60fps+. 

## Attach a .c3p

[https://www.dropbox.com/s/7wq0z2lhtggj7e7/JankTest1.c3p?dl=0](https://www.construct.net/out?u=https%3a%2f%2fwww.dropbox.com%2fs%2f7wq0z2lhtggj7e7%2fJankTest1.c3p%3fdl%3d0](url)

## Steps to reproduce

Create a debug apk and install on device. Increase the slider and you should see Janking every few seconds despite the frame rate reading above 60fps

## Observed result

The moving sprites 'jank' every few seconds even though the fps is a rock solid 60fps

## Expected result

It should be completely smooth throughout th experience when at 60fps with no stutters.

## More details
I tried many way to reduce things in my own project. The discussion and videos can be seen here: [https://www.construct.net/en/forum/construct-3/general-discussion-7/stutterring-reads-60fps-169596](url)

There is minimal janking on my PC running Chrome staright from the editor although it DOES happen but its much more rare..

I am using version 293.3

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 101.0.4951.54
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
C3 release: r293.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 283 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can see some minor jank happening on an Asus Zenfone 8. A few frames are occasionally dropped. However it is mostly smooth.

Frame scheduling is handled by the browser engine so this is beyond our control. I have filed an issue with Google here for them to investigate: https://bugs.chromium.org/p/chromium/issues/detail?id=1324177
Closing this issue as we will follow up there.

**Comment by simonpaulkeating** [comment]
Thanks Andrew. Much appreciated!

**Comment by JeFawk** [comment]
I am also experiencing this on M1 Macbook Air. Will check the bug report submitted to Chromium

**Comment by JeFawk** [comment]
I managed to reproduce it with a very basic project.
For me, on M1 Macbook Air, the following project jitters when viewing it in Google Chrome. It does not jitter in Safari.

[Jitter test.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9542839/Jitter.test.c3p.zip)
