### ISSUE TITLE
HTML5 export turns all imported file names that are case sensitive into lowercase

### ISSUE THREAD

**Issue by organised** [Scirra/Construct-3-bugs#569]
## Attach a .c3p
[Lower_caser.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1112320/Lower_caser.c3p.zip)

In the Screenshot below you can see a file I've unzipped from the Export on the left in a finder window and the filenames in the file-browser on the right in Construct3.  seededScale has turned into seededscale

![screen shot 2017-06-29 at 14 37 57](https://user-images.githubusercontent.com/3727889/27692674-3b805312-5cdf-11e7-844a-85f46e942d79.png)

## Steps to reproduce

1. add a JSON file to your project or rename the JSON file in the example to have a mixture of uppercase and lowercase.
2. Hit export HTML5 
3.Then open the zip file you receive.

## Observed result
The JSON filename you just added has entirely turned lowercase

## Expected result

I expected the filename to preserve its form and remain case sensitive, This actually breaks any functions that depend on those JSON files. 

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

Unzipping on a mac but that shouldn't make any difference as the other default files in the export preserve their case sensitivity so it's not the unarchiving issue.

**Comment by AshleyScirra** [comment]
This is by design, and C2 does this as well. Construct generally treats everything as case-insensitive, but some web servers are case-sensitive. In the past there have been bugs where Construct case-insensitively allowed a file to be fetched, but exporting it to a case-sensitive server caused it to fail. So to avoid this, C2 and C3 lowercase all project filenames, and only ever requests lowercase versions of the name.

**Comment by organised** [comment]
That's fine and I totally understand. I suggest maybe as a usability affordance and good practice,  the filebrowser (seen in my screenshot) also turns everything lowercase to reflect the fact that construct is case insensitive. Otherwise this will break projects and you might run into other error reports where people are clueless as to why it's happening.
