### ISSUE TITLE
R294 - Significant Performance drop using SpriteFont

### ISSUE THREAD

**Issue by Jase0000** [Scirra/Construct-3-bugs#5690]
## Problem description

Since r294, the more text in a SpriteFont, the higher the CPU usage gets.

Run the same project on r293-2 and you get much better performance.

## Attach a .c3p

https://drive.google.com/file/d/1-J5EzTZUT94_H95qN62n1Z4Yln2229Kx/view?usp=sharing

## Steps to reproduce

1. In r293-2, open c3p file.
2. Observe the events - Just a few "Append Text" actions, nothing major.
3. Preview in popup window.
4. Observe CPU, should be very low like 4%
5. In r294, open c3p file and preview.
6. You will see CPU usage is much higher, for me at 85%

## Observed result

Very high CPU Usage when enough text in a SpriteFont on r294 (I get 85% CPU Usage)

## Expected result

Low CPU Usage (I get 4% CPU Usage)

## More details

**Affected browsers/platforms:** Chrome, Windows

Worked in r293-2, broke in r294

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 101.0.4951.54
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
C3 release: r293.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 975 mb
Storage usage (approx): 45 mb (4.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The fix for #5622 made SpriteFont/word wrap work by grapheme, and it turns out grapheme splitting is surprisingly slow. This project has something of a worst case scenario with a very wide SpriteFont with long content and "Character" word wrap - changing any of those should still be pretty fast. The word wrap engine was doing grapheme splitting repeatedly during word wrap which caused the problem, but it doesn't need to. The next beta updates it to do it once up-front which looks like it restores performance to the original level.
