### ISSUE TITLE
guided tours: Event dialog action scroll should not be at the bottom.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5692]
## Problem description

He should be scroll to middle, not at the bottom.
  
![Snipaste_2022-05-11_13-58-16](https://user-images.githubusercontent.com/45864744/167780713-15148257-a343-4fcc-a6ed-cba19331912f.png)

## Attach a .c3p

https://editor.construct.net/#open=guided-tour-makeAPlatformGame

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I don't see why this would be a bug or why it should be changed.
