### ISSUE TITLE
Browser.IsOnline returns wrong result on Android

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5693]
## Problem description
Using Browser Is Online condition returns true on Android even though the wifi and phone data are turned off.

## Attach a .c3p
[Test Online.zip](https://github.com/Scirra/Construct-3-bugs/files/8669043/Test.Online.zip)

## Steps to reproduce

1. Build a debug apk.
2. Run it on Android.
3. Turn off wifi and phone data.

## Observed result

The text shows "Online"

## Expected result

The text shows "Offline"

**Comment by AshleyScirra** [comment]
The state is provided by the browser, not Construct. So I'm afraid this is beyond our control.

I would not recommend using it anyway. Online state is generally not just a boolean - you can have situations like patchy signal where things sometimes work and sometimes don't. Rather than trying to check "is online", just go ahead and make network requests, and if they fail treat that as being offline.

**Comment by Alaadel** [comment]
Thank you.
We would appreciate a note about that in the description of IsOnline. I spent hours designing based on this approach, and hours testing it, until I realized the issue is not on my side.

**Comment by AshleyScirra** [comment]
There is already a warning about using it in the manual entry: https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/browser

> The "is online" detection of the Browser plugin is more or less a guess. It is actually difficult to categorically determine if an Internet connection is available. For example the user may have intermittent signal, and online features sometimes work and sometimes fail unpredictably. In this case the "Is online" detection is probably wrong, as it can't actually tell whether a connection will work. Rather than using this condition to check if online features will work, usually it's better to just go ahead and use online features anyway as if the user is online, and handle any errors that occur as a result.
