### ISSUE TITLE
3D to 2D position imprecise conversion

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#5698]
## Problem description

Converting a 3D position to a 2D position only works if the projection mode is set "Orthographic", if it's set to "Perspective" the conversion will be imprecise.

This is how orthographic looks:
![Orthographic](https://user-images.githubusercontent.com/27010889/168381417-7c488b57-ff8e-44f3-bbb1-6fc0af6f893c.png)

And this is how perspective looks while running the exact same code:
![Perspective](https://user-images.githubusercontent.com/27010889/168381430-307776c6-93e6-4254-91e1-4f80040afa28.png)

## Attach a .c3p

[3Dto2DBug.zip](https://github.com/Scirra/Construct-3-bugs/files/8691021/3Dto2DBug.zip)

## Steps to reproduce

1. Execute the project with the projection mode set to Orthographic .
2. Notice how all "+" symbols are properly positioned on top of the cubes.
3. Execute the project with the projection mode set to Perspective.
4. Notice how all "+" symbols are scattered around the viewport.

## Observed result

All "+" symbols are scattered around the viewport, when using the Perspective projection mode.

## Expected result

All "+" symbols to be properly positioned on top of the cubes, independently of the projection mode.

## More details

**Affected browsers/platforms:** Chrome / Windows 11

**First affected release:** r293.3

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is a mistake in your calculation. When doing layer to canvas conversion, you provide the correct Z co-ordinate, and get a flat 2D position on the canvas. However when doing canvas to layer conversion afterwards, you provide the same Z co-ordinate, which is incorrect. That Z co-ordinate should be zero, as you're already working in flat 2D canvas co-ordinates by then. When you use zero in that parameter, it then works correctly.

So the X and Y expressions you want are:

`3DCamera.CanvasToLayerX("HUD", 3DCamera.LayerToCanvasX("World", Cube.X, Cube.Y, Cube.ZElevation + Cube.ZHeight), 3DCamera.LayerToCanvasY("World", Cube.X, Cube.Y, Cube.ZElevation + Cube.ZHeight), 0)`

`3DCamera.CanvasToLayerY("HUD", 3DCamera.LayerToCanvasX("World", Cube.X, Cube.Y, Cube.ZElevation + Cube.ZHeight), 3DCamera.LayerToCanvasY("World", Cube.X, Cube.Y, Cube.ZElevation + Cube.ZHeight), 0)`

**Comment by BonzerKitten** [comment]
@AshleyScirra My apologies for the mistake on my calculation, it was indeed a fault on my side. Thank you for the complete explanation on how each conversion works and how to properly apply them, it was very insightful and everything seems to working now. I honestly can't wait to get to Construct in a few weeks!
