### ISSUE TITLE
"Cordova Android scheme" doesn't create a savepoint

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-3-bugs#5699]
When you only change this property "Cordova Android scheme" under the advanced project properties, no savepoint will be created which means that you cannot save your project if no other modifications were made. This is not a super important issue but I wanted to point it out.

**Comment by AshleyScirra** [comment]
The description for those properties notes that changing them will clear storage, as storage is saved per origin and changing the scheme changes the origin. You should probably never change those properties, they are there for backwards compatibility.

**Comment by therealPaulPlay** [comment]
Sorry, my report is a bit misleading. I‘m not sure wether you understood it correctly, but I mean the savepoint of the engine, so basically you cant save the project to google drive etc. without making further changes as it does not register a change in the code of the project. In comparison, if you change any other setting (let‘s say you switch to a different Anti-Aliasing mode) you can click on the save icon in the engine immediately as it is not greyed out.
