### ISSUE TITLE
Hierarchy missing Transform Opacity 

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5706]
## Problem description

The Transform Opacity option is currently missing from the Hierarchy, which is very strange. I don't think it's "current by design" but probably forgot to add it. So this is an issue and not a suggestion?

https://construct3-21h2.ideas.aha.io/ideas/C321H2-I-125

## Observed result

![Snipaste_2022-05-16_03-20-08](https://user-images.githubusercontent.com/45864744/168490216-83b5ed71-3ae6-4a94-8192-0f74300acd3c.png)

## Expected result

Transform opacity

![Snipaste_2022-05-16_03-19-30](https://user-images.githubusercontent.com/45864744/168490342-b410f4db-d06a-4cf2-b484-f4cc6ac68b4e.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is already filed as a suggestion so closing the issue.
