### ISSUE TITLE
r294: Picked scope is wrong for children in hierarchy

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5708]
## Problem description

Seems like the default picked scope (with no conditions) for instances in hierarchy may be wrong. For example, the total number of instances is 4, but only 2 are picked by default.

Note, that it was working correctly in r293 and got broken in r294, possibly because of this change:  "Also pick children when using 'Create object' / 'Spawn an object' with 'Create hierarchy'"

## Demo project

https://www.dropbox.com/s/6dbechoscqczd56/HierarchyBug.c3p?dl=0

## Steps to reproduce

1. Press "4" to create four text instances.
2. Press "3" to generate console output

## Observed result

This event is at the top level, so the picked scope for statsText should be all 4 instances:
![image](https://user-images.githubusercontent.com/36763350/168764772-b813413a-0b70-48dd-adde-83b33eb3d6a7.png)

However, pickedCount returns only two instances, and the For Each loops only two times:

![image](https://user-images.githubusercontent.com/36763350/168764718-496243e2-124b-4882-91d4-bdf3c3e12eb0.png)

It gets weirder. Adding a "dangling" wait 0 at the end of the event which creates blue sprites+texts fixes the issue.

![image](https://user-images.githubusercontent.com/36763350/168765331-162eb442-3f70-478f-ad4a-584c4dfc378d.png)

## More details

As I said, this works correctly in r293.3

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r294 (beta)
Browser: Chrome 101.0.4951.67
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 127 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
Thanks, good find - this particular combination of events could incorrectly leave instances picked after the 'Create object' action. It should be fixed in the next beta.
