### ISSUE TITLE
r287: Tween bug, freeze during the layout transfer

### ISSUE THREAD

**Issue by UbruPro123** [Scirra/Construct-3-bugs#5709]
## Problem description

I am facing some bug with probably tween behaviour, at previous stable r285.3 everything was working good but at the new one r293.3 it is not working anymore (no change in project) game is freezing during the layout transition probably due to some end-state of tween.

## Attach a .c3p

IMPORTANT: I uploaded .zip (project file .c3p and step-by-step image guide) at my google disk and sent you link via email directly to - **hello@construct.net** and **ash@construct.net**

I have to do it like that, simply I cannot share my whole project publicly so please respect it.

## Steps to reproduce

It is hard to describe it without image so I attached step-by-step image guide with notes. I know maybe you think it is complicated or too much work to solve it but please take a look at it, simulate it in my game project is matter of 30 sec. You know it is always hard to deal with something very specific for one situation in huge project, but there is a problem and it is forcing me to stay at previous stable so I need to fix it. Maybe it could be also a problem for others.

## Observed result

Game freeze during the layout transition (going from game to menu).

## Expected result

Working transition into menu layout and everything load ok.

## More details
During the freeze there is error message in browser console:

timelineState.js:38 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'map')
    at Tween._SaveTracksToJson (timelineState.js:38:535)
    at Tween._SaveToJson (timelineState.js:36:66)
    at Tween._SaveToJson (tweenState.js:17:361)
    at runtime.js:12:226
    at Array.map (<anonymous>)
    at TweenInstance._SaveActiveTweensToJson (runtime.js:12:209)
    at TweenInstance.SaveToJson (runtime.js:8:31)
    at BehaviorInstance.SaveToJson (behaviorInstance.js:4:172)
    at Instance.SaveToJson (instance.js:28:407)
    at objectClass.js:30:45

**First affected release:** 

I am not sure with beta versions (using only stable versions) so at version r285.3 it is working, at next stable r293.3 it is NOT working, freeze and error message in console.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 101.0.4951.67
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
C3 release: r293.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 2.1 gb (1.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I have received the project but as per the bug report guidelines, we normally need a minimal project otherwise it can be impossible to diagnose the problem. Are you able to find a way to do that?

It's also helpful to establish the exact release number it broke in, as it narrows down the range of possible changes.

**Comment by UbruPro123** [comment]
I can give a try to cut off irrelevant things but I think that step-by-step process is needed to simulate it and cannot be reduced because I do not know exactly what is causing it.

OK I will try all betas one by one between these two stables and try to find out one specific version. I will add it here ASAP.

**Comment by UbruPro123** [comment]
First beta version where this problem appeared is r287.
In previous r286 it is ok.

**Comment by DiegoScirra** [comment]
Not really sure why this started happening as there haven't being any meaningful changes to tweens around those versions. in any case, this will be fixed starting on the next beta.

**Comment by UbruPro123** [comment]
It looks ok in new beta r296 so I hope there will be no more problem. Thank you for solving it.
