### ISSUE TITLE
Regular preview does not work in r42.2 when using addons

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#571]
## Problem description
Opened existing project after the update, attempted to preview. the preview window stays black and there are java script errors in the preview. created a new test project and the preview work as soon as i added a addon (behavior) to a sprite the preview did not work.

see attached gif
https://drive.google.com/open?id=0B-BWGR6TVR6BZm4yaVQ1SG9tTXM

## Attach a .c3p

attached c3p bundled with addon: 
https://drive.google.com/open?id=0B-BWGR6TVR6BeC1TZG9TNkR5TWM

if addon is not bundled in project, i got it from here https://github.com/rexrainbow/C3Plugins/tree/master/behaviors/rex_fsm

I suspect the preview is running into cors issue when loading the add on files,
* this project was working before the update 

## Steps to reproduce

1. add the fsm behavior (should be added in project)
2. hit preview
3.

## Observed result

nothing, no preview window and there were javascript errors in the console

## Expected result

have the game preview start normally.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r42.2

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 933 mb (1.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by rexrainbow** [comment]
Error message in console is -
**crossOriginPreviewWindow.js:83** Not allowed to load local resource: blob:https://editor.construct.net/a83e1064-f9b9-4eb3-845f-a9faf7b49ec7

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next build. There should be a r42.3 release today.
