### ISSUE TITLE
same folder name

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5711]
## Problem description

He didn't make any mistakes and didn't have any ill effects.  I know that the C3 folder will not have any effect on the path of file access, just something for myself management to appreciate.

![14](https://user-images.githubusercontent.com/45864744/169097998-7f97792b-03db-4af3-85f9-324b685999f0.png)

![Snipaste_2022-05-19_00-48-03](https://user-images.githubusercontent.com/45864744/169098030-3062bb10-39c0-46f0-9dff-b504658edfb9.png)

![Snipaste_2022-05-19_00-50-36](https://user-images.githubusercontent.com/45864744/169098413-830f2786-a592-41d0-8c26-25549eb8c1ad.png)

## Steps to reproduce

1. add new folder

## Expected result

"folder name already exists" ?

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
C3 already creates new folders with unique names, to get a structure like this you would need to purposely rename all the folders manually to be the same.

**Comment by AshleyScirra** [comment]
I don't think it's a bug, the folders don't really create file system folders so are just for organisation purposes, and there's no issue with having folders with the same name.

Changing this could also be tricky as we'd have to rename duplicate folder names in existing projects, and some people might like the way it works already.
