### ISSUE TITLE
Text Hierarchy Size Error

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#5712]
## Problem description

Setting the parent size to zero in a hierarchy with text causes an error.
The screen will sometimes go black.
## Attach a .c3p

https://www.dropbox.com/s/r0bukueoz2bhp1y/textheirsize.c3p?dl=1
## Steps to reproduce

1.Note the Sprite is set to zero size in the editor
2.Note the Sprite is set to be destroyed on start
3.Run the project
4.Click the button
5.Open the console, check for errors

## Observed result

Nothing happens, but the screen will go black. An error is thrown for the text object
## Expected result

There should be no crash, or error.
## More details

It is expected to be able to create things at a smaller size to be able to animate them to the full size
Note its doesn't happen if say the Sprite is 5x5.

**Affected browsers/platforms:** 
Chrome W 10

**First affected release:** 

## System details
Error is in the current stable, and beta

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This will be sorted for the next beta.
