### ISSUE TITLE
Crash when live previewing and removing behaviors in specific order

### ISSUE THREAD

**Issue by EydiavHamri** [Scirra/Construct-3-bugs#5716]
## Problem description

Program crashes when removing sine, rotate, fade or other live preview-able behaviors from objects but only while editor is in live preview, and if object behavior dialog was opened after live preview was started.

## Attach a .c3p
[PreviewCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/8729266/PreviewCrash.zip)

## Steps to reproduce

1. In attached project file, start live preview, either through right click menu or ctrl+r shortcut.
2. While live preview is running, open object behaviors dialog for "Sprite" object.
3. Remove Sine behavior.

## Observed result

The program crashes if steps are done in this order.
Note that if you have the object behavior dialog open before starting live preview (swap step 1 and 2), Construct doesn't crash.

## Expected result

I expect sine behavior to be removed and live preview to stop, like it does if object behavior window was open before live preview was started.

## More details

**Affected browsers/platforms:**
Google Chrome Version 101.0.4951.67 (Official Build) (64-bit)
Microsoft Edge Version 101.0.1210.47 (Official build) (64-bit)
Mozilla Firefox 100.0.1 (64-bit)

**First affected release:**
worked in r285.3, broke in r286, same release as when templates were introduced. 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r295/projectResources.js, line 843, col 295
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'FU')
Stack: TypeError: Cannot read properties of undefined (reading 'FU') at Function.$ea (https://editor.construct.net/r295/projectResources.js:843:295) at Function.$ea (https://editor.construct.net/r295/projectResources.js:836:28) at d.MZ (https://editor.construct.net/r295/projectResources.js:740:516) at d.sgb (https://editor.construct.net/r295/projectResources.js:741:365) at d.Na (https://editor.construct.net/r295/projectResources.js:573:264) at https://editor.construct.net/r295/components/bars/propertiesBar/propertiesBar.js:136:304 at CW (https://editor.construct.net/r295/components/bars/propertiesBar/propertiesBar.js:46:63) at d.CCG.aa.tL (https://editor.construct.net/r295/components/bars/propertiesBar/propertiesBar.js:136:269) at https://editor.construct.net/r295/components/bars/propertiesBar/propertiesBar.js:24:291 at gh (https://editor.construct.net/r295/main.js:372:150)
Construct version: r295
URL: https://editor.construct.net/r295/
Date: Thu May 19 2022 14:59:49 GMT+0200 (Central European Summer Time)
Uptime: 10 s

Platform information
Product: Construct 3 r295 (beta)
Browser: Chrome 101.0.4951.67
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.
