### ISSUE TITLE
advanced minification Error

### ISSUE THREAD

**Issue by XIMIKATIK** [Scirra/Construct-3-bugs#5717]
I get an error when trying to export to android with advanced minification enabled

/str/main.js:2094:21: ERROR - [JSC_UNDEFINED_VARIABLE] variable event is undeclared
  2094| 			this._LogCallback(event, argsList, isSuccess);
        			                  ^^^^^

1 error(s), 0 warning(s)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The code highlighted does not appear to be in Construct's code. It may be caused by a third-party addon.

I'm afraid it's impossible to help further unless you follow the bug report guidelines.
