### ISSUE TITLE
Timeline Hierarchy Transform Crash

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#5718]
## Problem description
There is a Crash with the new option for using the Hierarchy Transform on Timelines. If you edit the position of the sprites with the Hierarchy Transform activated, Construct 3 crashes. I can work around that by manipulate it without the option, then activate it afterwards.

## Attach a .c3p
[hierarchy_Bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8730543/hierarchy_Bug.c3p.zip)

## Steps to reproduce

1.Activate Edit mode in the timeline Bar for the Blue sprite
2.Move the blue sprite position to make a new key
3.

## Observed result

crash
## Expected result

no crash
## More details

without the hierarchy transform activated everything works as intended. You can even activate it afterwards, and its perfect.

this is the Crash Report:
Error report information
Type: unhandled exception
File: https://editor.construct.net/r295/components/editors/layoutView/layoutView.js, line 210, col 436
Message: Uncaught TypeError: Cannot read properties of null (reading 'pQa')
Stack: TypeError: Cannot read properties of null (reading 'pQa') at CS.XK (https://editor.construct.net/r295/components/editors/layoutView/layoutView.js:210:436) at DS (https://editor.construct.net/r295/components/editors/layoutView/layoutView.js:58:26) at v8a (https://editor.construct.net/r295/components/editors/layoutView/layoutView.js:57:164) at H9a.If (https://editor.construct.net/r295/components/editors/layoutView/layoutView.js:217:475) at Array.H9a.bf (https://editor.construct.net/r295/components/editors/layoutView/layoutView.js:212:240) at window.wl.dispatchEvent (https://editor.construct.net/r295/main.js:1095:399) at window.wl.If (https://editor.construct.net/r295/components/editors/layoutView/layoutView.js:96:61) at HTMLDocument.bf (https://editor.construct.net/r295/components/editors/layoutView/layoutView.js:81:304)
Construct version: r295
URL: https://editor.construct.net/r295/
Date: Thu May 19 2022 17:11:21 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 142.2 s

Platform information
Product: Construct 3 r295 (beta)
Browser: Chrome 101.0.4951.64
Browser engine: Chromium
Context: browser
Operating system: macOS 11.6.5
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 560 OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

**Affected browsers/platforms:** 
I tested in Chrome and Firefox on Mac

r295
**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Product: Construct 3 r295 (beta)
Browser: Chrome 101.0.4951.64
Browser engine: Chromium
Context: browser
Operating system: macOS 11.6.5
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 4.3 gb (1.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 560 OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
