### ISSUE TITLE
Dark Theme : Copy visual problem

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#572]
## Problem description

Dark Theme : Visual Problem : 
If you copy/Paste an Event, all the pasted conditions and actions in the New Event are white.

## Steps to reproduce

1. Copy an Event
2. Paste the event

## Observed result

All the conditions and actions in the new event are white

## Expected result

conditions and actions in Grey

## Affected browsers

* Chrome: yes

**Comment by Animmaniac** [comment]
@AshleyScirra you recently changed the way selection works to support my theming requests, so I think this is probably related to that. From what it seems when an event is pasted it still keeps a 'selected' attribute on 'conditionNameCell', 'conditionDescCell', 'actionNameCell' and 'actionDescCell' even after being deselected. 

My guess is that some code related to paste needs to be updated to comply with the recent changes.

**Comment by Animmaniac** [comment]
Anyway, I'm still updating the dark theme to support the new way selection works, so if it's working on the default theme it will probably work properly in the next theme release.

**Comment by Animmaniac** [comment]
Seem to be fixed.
