### ISSUE TITLE
Layout Editor: Unable to move or right-click an object selected with Tab

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5720]
## Problem description

This is more like a design flaw. 
If you use Tab to select an object which is behind another object, you can't move it with mouse or right-click it to access its context menu. Instead, as soon as you click it, the front object is selected again.

This is a small thing, but it may be quite frustrating when you are editing big layouts of complex objects.
For example, if I need to access the context menu I have to move the object somewhere else, where I will be able to select it without Tab. Then return it to its original position.

## Steps to reproduce

1. Hold Tab key and select an object which is behind another object
2. Try to move it with mouse or right-click it

## Observed result

Here Text2 is behind Text1, and I can't right-click Text2.

![gif](https://media.giphy.com/media/RxaHzxANg56AiTaSr2/giphy.gif)

## Expected result

I think the selected object should not change when you left-click it to move or right-click it.

## More details

**Affected browsers/platforms:** all

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 101.0.4951.67
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.3958333730697632
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
C3 release: r293.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 232 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by dop2000** [comment]
> This is currently by design. 
With this current implementation selecting objects with Tab has very little usefulness. All you can do is resize or delete the object.
If I need to select a different object, I would click somewhere else to clear the selection, not click the already selected object again.

I don't see a point of posting this on the suggestion platform because with the limited number of votes this minor idea will likely not receive any.

**Comment by AshleyScirra** [comment]
It lets you access all the properties of the selected instance, which is useful. That also includes the position and size properties for manual changes, and nudging by arrow keys.

Even if the design is not perfect, it does not make it a bug. It's not appropriate to request design changes through bug reports, this is intended for defects only.
