### ISSUE TITLE
Ability to move windows by close button

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-3-bugs#5724]
## Problem description

C3's windows (bars/dialogs) can be moved not just by the caption, but also by the close button (which is wrong in my opinion).

## Steps to reproduce

1. Open any dialog (New project dialog, Z Order bar etc.)
2. Hold LMB on the close button, and without releasing it, start moving the mouse (window will be moving)

## Observed result

https://ibb.co/CQDF5m6

## Expected result

https://ibb.co/997jW8H

## More details

**Releases:** r293.3 & r295

**Comment by AshleyScirra** [comment]
Thanks, well spotted. Fixed for next beta.
