### ISSUE TITLE
missing ’scale‘ expressions for Sprite

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5726]
## Problem description

'Set scale'  used in many places, But missing the 'scale' expression about it. 
- Sprite: Set scale
- Tween: Set scale 

## Expected result

Sprite.ImageScaleX
Sprite.ImageScaleY

like:
[tiled-background](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/tiled-background#internalH1Link3)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Sprite.Width / Sprite.ImageWidth

**Comment by AshleyScirra** [comment]
This is a feature request and not a bug, so please post it as a suggestion.

Please do not try to post suggestions to the bug tracker. You have done this a lot lately. We will close such reports without considering them - they should be posted to the suggestions platform.
