### ISSUE TITLE
Open crash projet

### ISSUE THREAD

**Issue by FusionJeunesse** [Scirra/Construct-3-bugs#5728]
---
name: Open crash projet
about: Use this option to report a bug. You must use this option for your report to
  be investigated.
title: ''
labels: ''
assignees: ''

---

## Problem description

Hello,

Today I try to open my project and I had this crash report. Do you know I can resolve this crash ?

Thanks for all your response. 

## Attach a .c3p

I don't have C3P files because à use the folder project for Github.
https://github.com/FusionJeunesse/RallyeDesJeux.git

## Steps to reproduce

1. Open de projet
2. Crash report

## Observed result

![image](https://user-images.githubusercontent.com/69011789/169934980-1502929d-ef7d-4342-9b5b-04dbc0fb136d.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Unexpected token < in JSON at position 0 @ SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse () at Object.vF (https://editor.construct.net/r293-3/main.js:912:194) at Pca (https://editor.construct.net/r293-3/main.js:219:293) at Nca (https://editor.construct.net/r293-3/main.js:219:68)
Stack: SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse () at Object.vF (https://editor.construct.net/r293-3/main.js:912:194) at Pca (https://editor.construct.net/r293-3/main.js:219:293) at Nca (https://editor.construct.net/r293-3/main.js:219:68)
Construct 3 version: r293.3
URL: https://editor.construct.net/
Date: Mon May 23 2022 22:13:51 GMT-0400 (Eastern Daylight Time)
Uptime: 5.4 s

Platform information
Browser: Chrome
Browser version: 101.0.4951.67
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
C3 release: r293.3 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help with just this information. Please see the bug report guidelines - we do need all that information to be able to help you.
