### ISSUE TITLE
Problem with Tint effect

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#573]
## Problem description

Hello
Perhaps I don't understand a new way of working in Construct 3, but I think can't change the Tint of an object with the "Set Effect Parameter" action.
In construct 2 you can use parameter 0 for the Red, parameter 1 for the Green and parameter 2 for the Blue.
But in construct 3 all the 3 colors are in the same parameter 0, i think.
Or perhaps there's another way to change the color ?

## Steps to reproduce

1. Add Tint effect to an object
2. Add a "Set effect parameter" action on this object
3. Set effect 0 to a value
4. Add a "Set effect parameter" action on this object
5. Set effect 1 to a value
5 Add a "Set effect parameter" action on this object
7. Set effect 2 to a value

## Observed result

Only the effect 0 parameter is working

## Expected result

A new color with the 3 parameters

## Affected browsers

* Chrome: yes/

**Comment by AshleyScirra** [comment]
Please follow all the guidelines so we can properly investigate your report. In C3 the Tint effect only has one parameter, which you set to an expression like `rgb(0, 0, 0)`. This sounds like the issue, so closing.
