### ISSUE TITLE
R296 Crashes when creating HTML elements. Show Error("effects not supported")

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5730]
## Problem description

When I create HTML elements C3 in R296 it crashes. At first I thought I had some third-party plug-in was broken (r295 is no problem), But I also tried to incognito windows and edge, they did not install any plugins, the same problem.

Then I tried clearing the browser cache in Edge and re-open r296, the same problem. and r295 can work.

![Snipaste_2022-05-25_00-21-07](https://user-images.githubusercontent.com/45864744/170085320-3893db5f-553e-4839-94cc-a4f196e0731e.png)

As you can see, Edge doesn't have any third-party plugins
![Snipaste_2022-05-25_00-36-35](https://user-images.githubusercontent.com/45864744/170087507-8ab9de35-41bc-4b7d-b12c-84210b351bdb.png)

## Attach a .c3p

create a new project

## Steps to reproduce

1. new a project in r296
2. create 'HTML elements'

## Observed result

![Snipaste_2022-05-25_00-24-31](https://user-images.githubusercontent.com/45864744/170085389-833142f1-1b1e-4a93-8777-832b780b2f2a.png)

![Snipaste_2022-05-25_00-33-52](https://user-images.githubusercontent.com/45864744/170087014-51f157c2-d2dc-40f9-b273-6df1b4a336a6.png)

## More details

**Affected browsers/platforms:** Chrome and Edge 101.0.1210.53, Windows 11 21H2

**First affected release:**  worked in 295 but broke in 296

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r296/projectResources.js, line 639, col 206
Message: Uncaught Error: effects not supported
Stack: Error: effects not supported at d.ZB (https://editor.construct.net/r296/projectResources.js:639:212) at ZB.next () at d.b7a (https://editor.construct.net/r296/projectResources.js:776:514) at b7a.next () at d.aDa (https://editor.construct.net/r296/projectResources.js:776:453) at d.Df (https://editor.construct.net/r296/projectResources.js:1269:377) at d.Df (https://editor.construct.net/r296/projectResources.js:1229:3) at QYb (https://editor.construct.net/r296/components/editors/layoutView/layoutView.js:78:153)
Construct version: r296
URL: https://editor.construct.net/r296/
Date: Wed May 25 2022 00:15:48 GMT+0800 (中国标准时间)
Uptime: 32 s

Platform information
Product: Construct 3 r296 (beta)
Browser: Edge 101.0.1210.53
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Super with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by pigmalien** [comment]
Confirmed. 
Tried with Button Object, and crashed.

**Comment by AshleyScirra** [comment]
Should be fixed in next update. (It affected all objects that do not support effects.)
