### ISSUE TITLE
r295 project open crashed in r296 

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#5731]
## Problem description

Project that saved in r295 cause crash in r296

## Attach a .c3p

https://mega.nz/file/pR9k1JIT#crmmuNZ1-of5NBtxYUXCGQXkrX1ue2udWhZfFWAZI6U

## Steps to reproduce

1. Create project in r295
2. Add something (I think HTML cause crash)
3. Save
4. Open in r296

## Observed result

Crash

## Expected result

Not crash

## More details
I think it is an effect properties bug.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r296/projectResources.js, line 639, col 206
Message: Uncaught Error: effects not supported
Stack: Error: effects not supported at d.ZB (https://editor.construct.net/r296/projectResources.js:639:212) at ZB.next () at d.b7a (https://editor.construct.net/r296/projectResources.js:776:514) at b7a.next () at d.aDa (https://editor.construct.net/r296/projectResources.js:776:453) at d.Df (https://editor.construct.net/r296/projectResources.js:1269:377) at d.Df (https://editor.construct.net/r296/projectResources.js:1229:3) at QYb (https://editor.construct.net/r296/components/editors/layoutView/layoutView.js:78:153)
Construct version: r296
URL: https://editor.construct.net/r296/
Date: Tue May 24 2022 18:23:06 GMT+0200 (közép-európai nyári idő)
Uptime: 3.5 s

Platform information
Product: Construct 3 r296 (beta)
Browser: Chrome 101.0.4951.67
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA Corporation)
Renderer: ANGLE (NVIDIA Corporation, NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2, OpenGL 4.5.0)
Major performance caveat: no
Maximum texture size: 32768
Point size range: 1 to 2047
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Looks like same issue as #5730 so marking duplicate.
