### ISSUE TITLE
Selecting an object in the project window crashes Construct 3

### ISSUE THREAD

**Issue by elle-trudgett** [Scirra/Construct-3-bugs#5732]
## Attach a .c3p

[c3crash.zip](https://github.com/Scirra/Construct-3-bugs/files/8765280/c3crash.zip)

## Steps to reproduce

1. Open the project file in r296
2. Click (left or right mouse button, it doesn't matter) on the object in the project window Object types -> Game -> LunaVisualOnlyNoCollision

## Observed result

<img width="293" alt="error" src="https://user-images.githubusercontent.com/6572020/170104778-2c23c098-0be0-4983-b25f-51a7a796cbfe.png">

## Expected result

Normal editor behavior, e.g. opening the context menu or selecting the object.

## More details

This project was last edited in an older version of construct, but I'm not sure which

Tested on Google Chrome Version 101.0.4951.67 (Official Build) (64-bit) in Windows 10. The crash also occurs in Firefox 100.0.2 (64-bit)

**Affected browsers/platforms:** 

**First affected release:** 

Unsure when it broke.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r296/main.js, line 985, col 65
Message: Uncaught Error: no item array available
Stack: Error: no item array available at gh (https://editor.construct.net/r296/main.js:372:111) at tq.g.J.yCb.Ft (https://editor.construct.net/r296/main.js:1402:355) at new tq.g.J.yCb (https://editor.construct.net/r296/main.js:1400:385) at Function.xa.j (https://editor.construct.net/r296/main.js:985:44) at xq.g.J.cZ.vf (https://editor.construct.net/r296/main.js:1416:100) at ccb (https://editor.construct.net/r296/components/bars/propertiesBar/propertiesBar.js:27:88) at d.CCG.aa.BR (https://editor.construct.net/r296/components/bars/propertiesBar/propertiesBar.js:137:152) at jab (https://editor.construct.net/r296/components/bars/projectBar/projectBar.js:2:130) at window.mR.MGa (https://editor.construct.net/r296/components/bars/projectBar/projectBar.js:96:128) at Array. (https://editor.construct.net/r296/components/bars/projectBar/projectBar.js:92:97)
Construct version: r296
URL: https://editor.construct.net/r296/
Date: Tue May 24 2022 11:21:39 GMT-0700 (Pacific Daylight Time)
Uptime: 5.1 s

Platform information
Product: Construct 3 r296 (beta)
Browser: Chrome 101.0.4951.67
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by brushfe** [comment]
I'm having the same issue with an r295 project brought into r296 when double-clicking an object to open the animation editor

**Comment by AshleyScirra** [comment]
Should be fixed in the next update.

**Comment by elle-trudgett** [comment]
> I'm having the same issue with an r295 project brought into r296 when double-clicking a sprite object to open the animation editor (Chrome 100, Mac 11.6)

Opening the project in the latest stable release, saving it, then opening it in the beta release seems to fix this.

**Comment by elle-trudgett** [comment]
Seems to be fixed in 296.2. 👍
