### ISSUE TITLE
r296 changing z-elevation causes crash

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5733]
Error report information
Type: unhandled exception
File: https://editor.construct.net/r296/main.js, line 905, col 29
Message: Uncaught TypeError: expected string
Stack: TypeError: expected string at Function.R.m (https://editor.construct.net/r296/main.js:905:35) at d.V8 (https://editor.construct.net/r296/projectResources.js:1222:152) at CCG.Yg.g.J.ycb.Yl (https://editor.construct.net/r296/components/bars/propertiesBar/propertiesBar.js:17:443) at CCG.Yg.g.J.ycb.Qn (https://editor.construct.net/r296/main.js:1368:158) at CCG.Yg.g.J.ycb.DE (https://editor.construct.net/r296/main.js:1376:39) at HTMLInputElement.Ps (https://editor.construct.net/r296/main.js:1362:295) at CCG.Yg.g.J.ycb.Nd (https://editor.construct.net/r296/main.js:1378:299) at HTMLInputElement.bD (https://editor.construct.net/r296/main.js:1365:64)
Construct version: r296
URL: https://editor.construct.net/r296/
Date: Tue May 24 2022 21:35:11 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 12.3 s

Platform information
Product: Construct 3 r296 (beta)
Browser: Chrome 101.0.4951.67
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Language setting: de-DE

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by DiegoScirra** [comment]
This happens when inputing a number with the keyboard and then hitting enter.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
