### ISSUE TITLE
A error ocurred with a construct 3 plugin

### ISSUE THREAD

**Issue by FranHUB2021** [Scirra/Construct-3-bugs#5735]
Good afternoon, nights I had an error when installing a plugin in construct 3 , when starting construct gives error when starting, the error code is: Error report information
Type: assertion failure
Message: no display text to parse
Stack: Error at Function.xa.lRa (https://editor.construct.net/r293-3/main.js:942:289) at window.assert (https://editor.construct.net/r293-3/main.js:860:38) at window.qQa.yPb (https://editor.construct.net/r293-3/projectResources.js:1397:530) at Object.vF (https://editor.construct.net/r293-3/main.js:542:86) at Pca (https://editor.construct.net/r293-3/main.js:219:293) at Nca (https://editor.construct.net/r293-3/main.js:219:68)
Construct 3 version: r293.3
URL: https://editor.construct.net/
Date: Tue May 24 2022 23:28:35 GMT-0300 (hora estándar de Argentina)
Uptime: 4.2 s

Platform information
Browser: Edge
Browser version: 101.0.1210.53
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53
C3 release: r293.3 (stable)
Language setting: es-ES

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Vega 3 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.

Note if the issue is with a third-party addon, you will need to contact the addon developer for support.

**Comment by AshleyScirra** [comment]
Clear your browser storage.
