### ISSUE TITLE
The project does not run on an android phone from version 295 to version 296.2 inclusive

### ISSUE THREAD

**Issue by KabutoJRM** [Scirra/Construct-3-bugs#5737]
## Steps to reproduce

1. The project runs perfectly in the EDGE browser.
2. I build an APK for version OREO 8.0.
3. I install the APK on my phone without problems

## More details

[Umi Liberator DX W-addons.zip](https://github.com/Scirra/Construct-3-bugs/files/8773350/Umi.Liberator.DX.W-addons.zip)

**Comment by AshleyScirra** [comment]
What export options are you using? Are you doing a minified export for example? I need complete details otherwise it's very difficult to help. (Often if I just try, it just works, because the reporter forgot to mention an important detail.)

**Comment by KabutoJRM** [comment]
Hi Ashley, sorry if I wasn't more specific, I'm new to reporting here on Github and English is not my native language.

Correct, the project was exported to Android without deduplicate images, without recompress images and the minify mode is set to "none", I never really use these options. The generated APK is installed correctly on the phone but when I open it it stays on the splash screen.

Yesterday I was trying to see what was wrong, so I followed these steps:

* I removed the firebase plug-in and the third party effect that the project had.
* Compile on android with the same negative result.
* Then I opened a new project, copied the assets and code and it worked perfectly.
* Of all my projects, the only ones that have been working on beta version 294 are failing and I went to 295 recording both and then to 296.2, I don't know if they were corrupted in version 295. The other old projects that I hadn't recorded if not I simply built yesterday in version 296.2 they worked perfectly (all these projects use the same add-ons that I mentioned above).

I hope I have been more specific here and I don't want to waste your time, by the way, congratulations on the new Animate product, it looks great.

**Comment by AshleyScirra** [comment]
Thanks for the additional details, it's very helpful.

In r295 we updated Closure Compiler which is used for minifying code, but also used for bundling projects using the legacy file: scheme for Cordova apps due to various restrictions of that mode. A bug in the latest version of Closure Compiler broke this special bundling mode. I've worked around it for the next beta, so it should be working there.

**Comment by KabutoJRM** [comment]
Many thanks to you Ashley for the great support you do on Construct, I was a Beta Tester of the iOS and android exporter of Fusion a few years ago and I switched to C3 a couple of years ago and I am very happy for the continuous revisions of the engine, in what I can help I will. Greetings
