### ISSUE TITLE
Positional audio crackling

### ISSUE THREAD

**Issue by Interinactive** [Scirra/Construct-3-bugs#5738]
## Problem description

Whenever I use positioned audio, there is a noticeable crackling/popping sound every now and then. I have tried many different music tracks and formats (mp3, wav, ogg etc, they all get converted to webm anyway).

## Attach a .c3p

[positional_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/8776293/positional_bug.zip)

## Steps to reproduce

1. Put headphones on. Open test file, click preview.
2. The initial audio is an audio file being played normally.
3. Click the button to change the audio to 'positional'. Listen for at least 30 seconds. There will be crackling / popping at certain intervals. It's the exact same audio file so I conclude that it's the positioned audio causing this.

## Observed result

The audio crackles/pops when using positioned sound.

## Expected result

Positioned audio that doesn't crackle/pop, much like when the same track is playing without being positioned.

## More details
I sent the file to two other people who tested the file and confirmed it occurs on their machines as well. You can use any audio track you like, the crackling remains.

**Affected browsers/platforms:** 

Windows 11 / Chrome Version 102.0.5005.63 (Official Build) (64-bit)

**First affected release:** I have long since noticed this issue, I only decided to investigate it today.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 102.0.5005.63
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
C3 release: r293.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 572 gb
Storage usage (approx): 1.7 gb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Interinactive** [comment]
Here is a video to help demonstrate the issue:

https://youtu.be/7H5-TQJDmBY

**Comment by Interinactive** [comment]
I have spent most of the night trying various things. I imported WAV, MP3 and OGG files into an old version of C3 (one that doesn't convert them), and then saved/pasted them over into the new project. None of that made a difference. Then I tried again at different sample rates, different channel types, various bit depths (and anything else I could change). It doesn't seem to matter.

FYI the crackling also occurs on your official 'Audio positioning' demo file, it's just hard to notice with constant sounds continually playing in the background.

On bugs.chromium I can also see various reports for this issue going back to 2019, specifically for Construct 3. Three years and multiple reports later, there still isn't a fix and all of those reports have been closed or ignored.

If the positional feature is still bugged after all this time, how come there isn't an alternative? Or a fix? Clearly both parties are aware of the issue. This is almost exactly like the last issue I contributed to in regards to audio bugs (#5503). As one of the customers in the middle, what are we supposed to resort to when neither party seems to be able to do anything about it after 1000+ days?

Would it not be worth reworking the way positioned audio works at this stage?

**Comment by AshleyScirra** [comment]
The audio playback is handled by the browser, not Construct. I believe this is [a known bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1242647) so Google will need to fix it. Firefox and Safari should not be affected.

**Comment by Interinactive** [comment]
@AshleyScirra I feel like you missed the last comment there. The reports go back for years and the crackling is present in NW.JS exports (for Steam), so I'm unsure of how Firefox/Safari are relevant.

**Comment by Interinactive** [comment]
Google:

> The plain JS version helps, but it's still almost 30000 lines of code.

https://bugs.chromium.org/p/chromium/issues/detail?id=1041182

How are they expected to help when they aren't familiar with your code, with so much to work through?

Another one:

> Something we should still investigate, but the repro case is huge with lots of setposition calls.

https://bugs.chromium.org/p/chromium/issues/detail?id=1002093

@AshleyScirra It really sounds like you guys need to communicate with one another. This issue is going nowhere.

**Comment by AshleyScirra** [comment]
Those issues are closed. The issue I linked to is the current open issue and has a minimal code sample demonstrating the problem.

I'm afraid Google need to fix this, as the problem is in the Chrome browser, not Construct.
