### ISSUE TITLE
Error when trying to import a C2 project

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#5744]
I'm trying to move the one last game I still have on C2 to C3.
A few years back I did mange to import the capx, but now when I try I get an error message.
I tried it on 251-2 and the latest stable on NWjs and chrome.

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>
Error report information

Type: unhandled rejection
Reason: Error: missing C2 action id '2' @ Error: missing C2 action id '2' at window.ihb.qta (https://editor.construct.net/r251-2/projectResources.js:803:479) at window.$Rb.qta (https://editor.construct.net/r251-2/main.js:1542:16) at Function.bP (https://editor.construct.net/r251-2/projectResources.js:764:373) at g.lM (https://editor.construct.net/r251-2/projectResources.js:733:402) at Function.bP (https://editor.construct.net/r251-2/projectResources.js:689:192) at g.vzb (https://editor.construct.net/r251-2/projectResources.js:697:305) at g.lM (https://editor.construct.net/r251-2/projectResources.js:733:443) at Function.bP (https://editor.construct.net/r251-2/projectResources.js:689:192) at window.UGa.vzb (https://editor.construct.net/r251-2/projectResources.js:697:305) at window.UGa.lM (https://editor.construct.net/r251-2/projectResources.js:699:6)
Stack: Error: missing C2 action id '2' at window.ihb.qta (https://editor.construct.net/r251-2/projectResources.js:803:479) at window.$Rb.qta (https://editor.construct.net/r251-2/main.js:1542:16) at Function.bP (https://editor.construct.net/r251-2/projectResources.js:764:373) at g.lM (https://editor.construct.net/r251-2/projectResources.js:733:402) at Function.bP (https://editor.construct.net/r251-2/projectResources.js:689:192) at g.vzb (https://editor.construct.net/r251-2/projectResources.js:697:305) at g.lM (https://editor.construct.net/r251-2/projectResources.js:733:443) at Function.bP (https://editor.construct.net/r251-2/projectResources.js:689:192) at window.UGa.vzb (https://editor.construct.net/r251-2/projectResources.js:697:305) at window.UGa.lM (https://editor.construct.net/r251-2/projectResources.js:699:6)
Construct 3 version: r251.2
URL: https://editor.construct.net/r251-2/
Date: Sat May 28 2022 22:13:22 GMT+0300 (Israel Daylight Time)
Uptime: 184.1 s
Platform information

Browser: Chrome
Browser version: 101.0.4951.67
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
C3 release: r251.2 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 750 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help unless you follow the bug report guidelines.
