### ISSUE TITLE
Timeline crashes when dragging a single keyframe when in edit mode

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5747]
After the Construct  Animate announcement I tried to give a bit of feedback on the forums and spend a few hours trying to reproduce some of the timeline crashes I have had in the past.

The timeline crashes with the same error with both of these actions:
1. dragging a single keyframe (not the master one) in edit mode
![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/89512047/171050763-fef2e801-01a4-4748-9535-c8a2ce3a6056.gif)

2. dragging a single keyframe when not in edit mode and then switching to edit mode (so this has to do something with edit mode)
![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/89512047/171050709-ef5ee6f3-9663-4613-b329-0ddf948f966a.gif)

the error message:
![timeLineCrashGoingIntoEditMode](https://user-images.githubusercontent.com/89512047/171050563-835a0d23-4f9d-4dd4-b390-dbe2807ba68e.png)
c3p file to reproduce, just requires you to drag a the single key frame and enter edit mode.
[C3preproEditMode.zip](https://github.com/Scirra/Construct-3-bugs/files/8800508/C3preproEditMode.zip)

**Comment by F3der1co** [comment]
edited as I found a simpler repro

**Comment by DiegoScirra** [comment]
This will be fixed for the next beta.
