### ISSUE TITLE
Crash when launching a remote preview

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#575]
## Problem description

When I try to remote preview on a phone or with a desktop web browser, Construct crashes.

## Attach a .c3p

Any project will apparently do - I reproduced this with the 9-patch example project as well as my game project.

## Steps to reproduce

1. Open a project (i.e., built-in 9-patch object example)
2. Launch a remote preview
3. Paste the preview URL into a browser or use the QR barcode with a phone and launch that way

## Observed result

Construct 3 crashes as soon as the client tries to connect. In the browser window attempting to preview (this is in Chrome, in my case) an error message appears under "Construct 3 remote preview": "Error: TypeError: RTCPeerConnection is not a constructor"

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r42-3/exporters/preview/exporter.js, line 1, col 13642
Message: Uncaught TypeError: r is not a constructor
Stack: TypeError: r is not a constructor at window.ǃeoj.ǃeNO (https://editor.construct.net/r42-3/exporters/preview/exporter.js:1:13642) at window.ǃeSA.ǃeSj (https://editor.construct.net/r42-3/exporters/preview/exporter.js:1:20024) at window.ǃeNC.ǃeSw.ǃeNP (https://editor.construct.net/r42-3/exporters/preview/exporter.js:1:19027) at window.ǃeNC.ǃeoE (https://editor.construct.net/r42-3/exporters/preview/exporter.js:1:11439) at window.ǃeNC.ǃ_LP (https://editor.construct.net/r42-3/exporters/preview/exporter.js:1:9414) at WebSocket.ǃeNx.onmessage (https://editor.construct.net/r42-3/exporters/preview/exporter.js:1:8777)
Construct 3 version: r42.3
URL: https://editor.construct.net/index.html
Date: Sat Jul 01 2017 01:27:37 GMT-0700 (Pacific Daylight Time)
Uptime: 239.6 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r42.3

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here, remote preview works fine, and we've had no other reports of this so far. The error message is also strange and looks like WebRTC support has been disabled in your browser. Have you altered the browser flags at all? Or installed addons that turn off browser features? Or anything else like that?

**Comment by Scoremonger** [comment]
You're right, thanks, the browser I was using to run Construct had a Web RTC blocker addon. I removed it and remote preview works fine now. It would be nice if there was a more human-readable error message that called out the possibilities you mentioned in your comment, though admittedly this probably isn't a  common scenario.
