### ISSUE TITLE
The new 8-direction setting "allow sliding" doesn't stop the velocity when colliding with solids 

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5750]
**The new 8-direction "allow sliding" doesn't stop the velocity when colliding with solids.** I get that this is part of the solution as the 8dirObject is supposed to keep sliding at that velocity. 
But when colliding with solids dead on or in other ways where the 8dirObject doesn't move visibly on screen, the velocity is not stopped.
This means that the 8dirObject tends to stick to solids, because **when moving against a solid and then moving away from it the 8-dirObject has to overcome the velocity in the opposite direction first before moving.**

_See this video by TackerTacker that illustrate the problem:_
https://user-images.githubusercontent.com/89512047/171255639-61afc277-fab0-4778-91b8-8c23f4ba433d.mp4

**Comment by AshleyScirra** [comment]
No project was provided. I can't debug videos. Please see the bug report guidelines.
