### ISSUE TITLE
Manually-modified expression text is auto-completed to a different string even if it was already valid

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#576]
## Problem description

Auto complete can replace manually modified expression text with something else that begins with the same characters even if the manually-changed text was already valid. 

For example, if I have instance variables XDelta and YDelta, and I have an expression that contains "Sprite.XDelta" and I manually replace the "X" with a "Y", intending to change it to "Sprite.YDelta", autocomplete changes it to "Sprite.Y" instead. 

(I know this arguably isn't a bug, but it tripped me up enough times today it felt worth writing up.)

## Attach a .c3p

[AutoCompleteBuggish.zip](https://github.com/Scirra/Construct-3-bugs/files/1116942/AutoCompleteBuggish.zip)

## Steps to reproduce

1. Add instance variables to a sprite: "XDelta" and "YDelta".
2. Create an expression that uses Sprite.XDelta (attached project has one).
3. Select the "X" in Sprite.XDelta and replace it with a "Y" so that the expression now contains "Sprite.YDelta".
4. Hit tab to complete the edit.

## Observed result

"Sprite.YDelta" changed to "Sprite.Y" by the autocomplete.

## Expected result

Construct recognizes that the string is already valid and makes no change when tab is hit to autocomplete.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r42.3

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 308 mb (2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next build.
