### ISSUE TITLE
Using Animation Editor scrollbar clears frame selection

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5761]
## Problem description

Using Animation Editor scrollbar clears frame selection. When trying to multi-select many frames across multiple rows in the Frames section, using the scrollbar to go to the next row clears the selection. It is very hard to multi-select frames across multiple rows.

## Attach a .c3p

(New Project)

## Steps to reproduce

1. Create a sprite
2. Open its Animation Editor
3. Right-click in the Frames section and choose: Thumbnail Size -> Large
4. Keep adding frames until you have 2 rows of frames
5. Select a frame in the first row
6. Hold Shift
7. Use the scrollbar to go to the next row to select the final frame

## Observed result

Clicking the scrollbar clears the selection.

## Expected result

The scrollbar should not affect the selection.

## More details

**Affected browsers/platforms:** Chrome (C3 Chrome app)

**Comment by DiegoScirra** [comment]
I see the problem. In the mean time, while this is fixed, if you keep **Shift** pressed down while using the scrollbar, the selection will be kept. Same goes for **Ctrl**.

If you have a mouse wheel, you can scroll using it and the selection will be kept as well. Mind that using the mouse wheel while keeping **Shift** or **Ctrl** pressed will prevent any scrolling.

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
