### ISSUE TITLE
Cannot add a new object type if no layout is open

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5762]
## Problem description

Cannot add a new object type if no layout is open

## Attach a .c3p

(New Project)

## Steps to reproduce

1. Close the layout
2. Open the event sheet
3. Right click on the "Object types" folder.

## Observed result

"Add object type" button is hidden. (unless you open the layout)

## Expected result

"Add object type" button should be visible.

**Comment by AshleyScirra** [comment]
This is currently by design as many plugins need an associated layout. The active layout is used as the associated layout, and if none is available, then the option is not available.

**Comment by Alaadel** [comment]
> This is currently by design as many plugins need an associated layout. The active layout is used as the associated layout, and if none is available, then the option is not available.

Thank you.
It is a bit confusing, as the user will not know why the option disappeared. If a new user closed the layout by mistake, how can he reach the conclusion that he can't add objects because a layout **should** be opened?

Maybe C3 can automatically use the first layout in the project, or a random layout.
Or maybe disable the option and/or add a simple message: "Please open a layout to add plugins".

A little clarity would help.
Thank you.
