### ISSUE TITLE
Copy / Pasting text from Google Drive documents in the data editor crashes Construct

### ISSUE THREAD

**Issue by daleinen7** [Scirra/Construct-3-bugs#577]
## Problem description

Copy and pasting text (specifically from Google Drive Text Documents) into an array cell in the data editor crashes Construct.

## Attach a .c3p

https://drive.google.com/open?id=0B3LkhSnYCm1_ZjVyblRaZWdwems

## Steps to reproduce

1. Create an array.json file and add several columns and rows.
2. Copy and paste text from Google Drive Document
3. It won't immediately crash. But moving the cursor around various array cells it will eventually crash.

## Observed result

The text is bold and hitting the RIGHT arrow at the end of the text will not move to the next column.  Shortly after (usually when arrowing back to the cell with the text in it) Construct crashes.

## Expected result

I'd expect it to act the same as text that I typed into the cell. 

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r42-3/main.js, line 2, col 108388
Message: Uncaught DOMException: INDEX_SIZE_ERR
Stack: undefined
Construct 3 version: r42.3
URL: https://editor.construct.net/index.html
Date: Sat Jul 01 2017 10:37:33 GMT-0500 (Central Daylight Time)
Uptime: 110.7 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r42.3

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 550 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Looks like a few HTML elements were being dragged along for the ride with the text, probably would have been repeatable taking text from an arbitrary website.

I've made a fix that forces the clipboard data to plain text when it's inserted, fixes the problem and possibly some others.
