### ISSUE TITLE
r298 Timeline, time markers (1S,2S etc.) are cut off on the the top

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5774]
**Tested on default theme and dark theme, so doesn't seem to be dependant on that. 
Resizing the timeline also doesn't change it.**

Repro c3p not needed imo, but I can supply it if necessary.

![timelineTimeMarkersCutOff](https://user-images.githubusercontent.com/89512047/172413104-89d3e7c1-bf26-4adf-bd45-eceb3d71b391.png)

**Comment by F3der1co** [comment]
oh, true, I didn't realize my zoom level was set to 90%!
Though I'd still expect it to work with other zoom levels, afaik the rest of the editor seems to have no problem.

**Comment by DiegoScirra** [comment]
Oh yeah, was just making the comment to remember about it when I come back to this. Nothing in the time ruler is taking into account zoom (or at least not correctly), that includes the little markers and the numbers. It's not a problem when you zoom in, but the more you zoom out it becomes more apparent they are not changing size properly.

**Comment by DiegoScirra** [comment]
As it turns out it was only the numbers that were not taking into account device pixel ratio. Will be fixed for the next beta.
