### ISSUE TITLE
Crash when pasting a script file from a different project

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5776]
## Problem description

Construct crashes everytime I try to copy-paste a script from one project to the other.

## Attach a .c3p

(New Project)

## Steps to reproduce

1. Create a new project
2. Right-click the Scripts folder and create a new script
3. Rename the script to "script.js"
4. Copy the script
5. Create a new project
6. Right-click the Scripts folder and click Paste

## Observed result

Crash

## Expected result

Successful paste

## More details

**Affected browsers/platforms:** Chrome (App)

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: file not yet added to folder @ Error: file not yet added to folder at d.Hc (https://editor.construct.net/r293-3/projectResources.js:866:326) at d.Jf (https://editor.construct.net/r293-3/projectResources.js:866:508) at Array. (https://editor.construct.net/r293-3/components/bars/projectBar/projectBar.js:89:211) at window.j9a.dispatchEvent (https://editor.construct.net/r293-3/main.js:1059:42) at window.j9a.RZ (https://editor.construct.net/r293-3/main.js:2318:285) at d.fha (https://editor.construct.net/r293-3/projectResources.js:867:380) at d.ah (https://editor.construct.net/r293-3/projectResources.js:877:216) at x (https://editor.construct.net/r293-3/components/bars/projectBar/projectBar.js:67:249) at async Promise.all (index 0) at async rbb (https://editor.construct.net/r293-3/components/bars/projectBar/projectBar.js:68:48)
Stack: Error: file not yet added to folder at d.Hc (https://editor.construct.net/r293-3/projectResources.js:866:326) at d.Jf (https://editor.construct.net/r293-3/projectResources.js:866:508) at Array. (https://editor.construct.net/r293-3/components/bars/projectBar/projectBar.js:89:211) at window.j9a.dispatchEvent (https://editor.construct.net/r293-3/main.js:1059:42) at window.j9a.RZ (https://editor.construct.net/r293-3/main.js:2318:285) at d.fha (https://editor.construct.net/r293-3/projectResources.js:867:380) at d.ah (https://editor.construct.net/r293-3/projectResources.js:877:216) at x (https://editor.construct.net/r293-3/components/bars/projectBar/projectBar.js:67:249) at async Promise.all (index 0) at async rbb (https://editor.construct.net/r293-3/components/bars/projectBar/projectBar.js:68:48)
Construct 3 version: r293.3
URL: https://editor.construct.net/
Date: Wed Jun 08 2022 14:46:10 GMT+0200 (GMT+02:00)
Uptime: 172.4 s

Platform information
Browser: Chrome
Browser version: 102.0.0.0
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
C3 release: r293.3 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 610 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
