### ISSUE TITLE
Built-in text editor doesn't save changes after Save and Run

### ISSUE THREAD

**Issue by valerypopoff** [Scirra/Construct-3-bugs#578]
## Problem description

When in a built-in text editor (plain text, javascript, JSON...) if you make changes to a file and then close the file tab, it saves the changes. But if you make changes and do Save or Run before closing the tab, it doesn't save the changes. 

## Attach a .c3p

[Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1117429/Bug.zip)

## Steps to reproduce

1. Create a new file under Files category in the Project Bar
2. Open a file in a built-in editor
3. Make changes to a file
4. Do Save or Run
5. Close the file tab
6. Open the file again
7. See no changes were saved

## Observed result

Last changes to a file are not saved

## Expected result

Last changes to a file are saved

## Affected browsers

* Chrome: yes
* Firefox: dunno
* Edge: dunno
* Safari: dunno

## System details

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r42.3

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 0 bytes (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
The isChanged check was incorrectly blocking the save, would have been quite awkward to find, thanks for reporting that!
