### ISSUE TITLE
Instant game on ios: Dosent start

### ISSUE THREAD

**Issue by Itslossless** [Scirra/Construct-3-bugs#5782]
## Problem description

 My Instant games on Facebook stopped working on IOS devices, The game loads to 100%, but doesn't start, we didn't have this issue before with our games.  

## Attach a .c3

[InstantGameIOS.zip](https://github.com/Scirra/Construct-3-bugs/files/8873165/InstantGameIOS.zip)

## Steps to reproduce

1. Export as an Instant game 
2. [Y]Deduplicate images, [Y]Recompress images, minify mode: simply
3. upload to Facebook as an instant game app
4. play the game with IOS 15.X device 

## Observed result

 The game starts to load, it gets to 100%, and that it, the game doesn't start

## Expected result

 The Game start and I see the open screen of the game

## More details
 
1. The game worked on Desktop browsers and on a Facebook app on android devices. 
2. Link for the live game on Facebook: https://www.facebook.com/gaming/play/3198205077118074/
3. We have two more games on the Facebook instant game platform that have been on the platform for about half a year with no issues on IOS devices, and they have the same issue right now (load to 100%, Doesn't start). 

**Affected browsers/platforms:** Safari,IOS 

**First affected release:**  r293.3

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 102.0.5005.63
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
C3 release: r293.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 1.3 gb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) Iris(R) Plus Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Itslossless** [comment]
Hi Ashley,
Thanks for the quick response,
"The link to the live game on Facebook seems to load and run just fine for me. Is the issue meant to reproduce there?"- Did you try to run the game with an iPhone device(IOS) and it's worked? 
"Could you test with r298" - I tried and still the game won't go throw 100%, On IOS devices (iPhone), On Desktop+android the game work Only IOS won't work (iPhone).

**Comment by Itslossless** [comment]
Hi, is there any news about our problem?

**Comment by AshleyScirra** [comment]
I tried playing the game on Safari and after pressing "Play", it just shows a red banner that says "Unexpected error". It does not appear to attempt to load the game. That looks like a problem with the Instant Games service. It also looks different to the problem you reported. I'm not sure what to do about this.

I'd advise to try attaching the iOS device to a Mac with its cable, and get Safari development tools open for the iOS device so you can look at the console for the iOS device and see if any error messages appear when it fails to load.

**Comment by tuzke** [comment]
@Itslossless @AshleyScirra I had the same error, but it seems that the problem is that Facebook instant game IOS does not support the sound file of the Construct 3, so it cannot load the sound files. But if you uncheck "Preload sounds" the game will load and the game works without sound in the game, All construct 3 games currently on Facebook IG work without sound , or failed to load. @AshleyScirra Please consider if the issue is resolved. Thank you! I have attached a screenshot from the console:
[https://i.imgur.com/sZUR0bH.jpg](url)
[https://i.imgur.com/4IWV5Yg.png](url)

**Comment by tuzke** [comment]
I understand this, but currently only construct 3 suffers from this problem. If you can fix it that would be great, we contacted facebook but they just replied: "Since you're using Construct 3 INSTANT GAMES plugin, we don't support third-party libraries, please reach out to Construct directly for this issue." 
Thank you!

**Comment by Itslossless** [comment]
Hi, @tuzke Thank you for sharing the issue you had and your conclusions on that
@AshleyScirra,@tuzke was correct as soon as I disabled the "Preload sounds" + disabled the music/sound functions inside our games for ios devices, the games are running on ios devices.
As @tuzke said when we sent Facebook team about this issue, their response was "Since you're using Construct 3 INSTANT GAMES plugin, we don't support third-party libraries, please reach out to Construct directly for this issue." 
So we don't know what do to with this issue, right now we uploading all our games with no sounds for ios devices.

Thank you @tuzke And @AshleyScirra  for the response.

**Comment by tuzke** [comment]
@AshleyScirra Great! It has been fixed in the latest version r303! Thanks for the hard work!

**Comment by Itslossless** [comment]
Hi @AshleyScirra, If I build from r303 (beta) the games work with sounds on IOS devices,  Amazing. 
Thank you guys for the support
