### ISSUE TITLE
Failed to Open Project, check to see that it's a valid project

### ISSUE THREAD

**Issue by theBobcatte** [Scirra/Construct-3-bugs#5783]
## Problem description

I am unable to open my project anymore. I was working on and took a break, when I came back I could not open the project anymore. I tried downloading my cloud version but it wouldn't open in firefox or chrome, nor the newest beta.

I also tried opening my backup, but it is experiencing the same issue so it seems like something got saved twice that made construct really sad.

I am including my project (sorry it's a monster one) for debugging as I don't have any idea what happened. I was working on my Player Interactions and making some functions that called each other step by step to create selection logic, so I assume the problem is somewhere in there.

## Steps to reproduce

1. Download project
2. Attempt to open in r293.3 or current beta branch in either chrome or firefox

## Observed result

message saying " Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project. "

## Expected result

Project to open

## More details

**Affected browsers/platforms:** Firefox/Chrome, r293.3 and Beta branch

**First affected release:** only been working on this in 293.3
## System details

<details><summary>View details</summary>
[NCMAAdventure_Drop01v3.zip](https://github.com/Scirra/Construct-3-bugs/files/8895261/NCMAAdventure_Drop01v3.zip)

PASTE HERE
Platform information

Browser: Firefox
Browser version: 101.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.0909090909090908
Logical CPU cores: 16
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0
C3 release: r293.3 (stable)
Language setting: en-US
Local storage

Storage quota (approx): 228 gb
Storage usage (approx): 316 mb (0.1%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

* Error seen in browser logs 
* 20:06:34.927 [Project] Exception opening:  Error: invalid function name 'fcnBuildingCostAssessment'
    LR https://editor.construct.net/r293-3/projectResources.js:1375
    rg https://editor.construct.net/r293-3/projectResources.js:1375
    ol https://editor.construct.net/r293-3/projectResources.js:1420
    accept https://editor.construct.net/r293-3/projectResources.js:1288
    accept https://editor.construct.net/r293-3/projectResources.js:1356
    qT https://editor.construct.net/r293-3/projectResources.js:1331
    accept https://editor.construct.net/r293-3/projectResources.js:1288
    qT https://editor.construct.net/r293-3/projectResources.js:1302
    qT https://editor.construct.net/r293-3/projectResources.js:1331
    accept https://editor.construct.net/r293-3/projectResources.js:1288
    qT https://editor.construct.net/r293-3/projectResources.js:1302
    qT https://editor.construct.net/r293-3/projectResources.js:1331
    accept https://editor.construct.net/r293-3/projectResources.js:1288
    qT https://editor.construct.net/r293-3/projectResources.js:1302
    accept https://editor.construct.net/r293-3/projectResources.js:1288
    qT https://editor.construct.net/r293-3/projectResources.js:1302
    accept https://editor.construct.net/r293-3/projectResources.js:1288
    qT https://editor.construct.net/r293-3/projectResources.js:1302
    accept https://editor.construct.net/r293-3/projectResources.js:1288
    qT https://editor.construct.net/r293-3/projectResources.js:1302
    accept https://editor.construct.net/r293-3/projectResources.js:1288
    eL https://editor.construct.net/r293-3/projectResources.js:1615
    Xqc https://editor.construct.net/r293-3/projectResources.js:1615
    g$a https://editor.construct.net/r293-3/projectResources.js:1594
    SPb https://editor.construct.net/r293-3/projectResources.js:1667

**Comment by theBobcatte** [comment]
now that I see the function name in this, it seems like maybe I had renamed a reference to that function but not the function itself? Would test but obviously I can't open the project

**Comment by AshleyScirra** [comment]
The project includes a third-party addon "3D Object", and I can't open it because of that.

It's also not possible for us to fix the problem that caused this in the first place, if it really was Construct's fault, without steps to reproduce the problem.

It's essential to make regular backups for any kind of digital work to protect it in the event of a disaster. I would advise restoring a backup if you can.

**Comment by theBobcatte** [comment]
Is there no way to open the project without that addon, or to package the add-on in so it can open? I am pretty sure it's a broken link between a function being called that has the wrong name or got renamed. Like I posted above, I cannot open backups because this was saved there too, so I can't open at all to recover or even try to figure out repro steps. Additionally, if I were to find repro steps on a new project that fit with my hypothesis, I also have no idea if that's the actual problem so I doubt it would be helpful?

**Comment by AshleyScirra** [comment]
I need the exact version of the "3D object" plugin your project uses to even attempt opening it. I'm afraid even with that though I cannot guarantee the project will be recoverable.

**Comment by theBobcatte** [comment]
omg @arcadesindo how were you able to do that? I would love to speak with you directly, PMing you my personal email. This is a monumentous life saver!

**Comment by theBobcatte** [comment]
just sent a request with 9's for phone number through your arcadesindo.com site, if you don't see it please email me at matthew.e.wagner@gmail.com as I am currently totally blocked on this issue

**Comment by joshculpart** [comment]
Hey @theBobcatte,

I had a similar issue just now. It happened exactly as you said.

What I did to fix my issue was to take my .c3p and turn it into a zip file (change the file extension .zip). Unzip that file to a folder. If your file is already a project folder, thats great.

Go to the event sheet (project folder/eventSheets/*nameofyoureventsheet.JSON*) with the referenced function that isn't correctly referenced/named, and find the references to it. I just did a search for the name of my function. Delete those sections.

If you need help, send me an email at joshculpart@gmail.com and I'll try to walk you through those steps.

Currently trying to figure out how to reproduce the error, since it's definitely a bug in c3.
