### ISSUE TITLE
Whitelist Plugins (Routine)

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#5784]
Hi, please whitelist these plugins:

### New Plugin
`sparsha-firebase-config@1.0.2`

### Other Routine Maintenance
`cordova-plugin-firebase-authentication@5.1.0`
`cordova-plugin-firebase-messaging@6.1.2`

The new plugin will reduce the work for the Construct team in whitelisting plugins based on the original Firebase cordova plugins (by chemerisuk). This new plugin will make chemerisuk's plugins compatible with Construct's Cordova build server, and thus reduce the forks of chemerisuk's plugins. ([Issue was adressed by Ashley](https://github.com/Scirra/Construct-3-bugs/issues/4938#issuecomment-893371121))

**Comment by AshleyScirra** [comment]
I've added `cordova-plugin-firebase-authentication@5.1.0` and `cordova-plugin-firebase-messaging@6.1.2`, but `sparsha-firebase-config` looks like a variant of `firebase-config`, and in general I do not want to have to review forks of existing Cordova plugins. Why can't you use `firebase-config`? The build server just runs the usual Cordova CLI commands so it's not clear why any specific Cordova plugin would not be compatible with the build server, and I'd rather make changes to the build server to increase its compatibility if necessary.

**Comment by jE-KI** [comment]
how to add `<resource-file>`   In IPluginInfo

dependencies are automatically included in the exported config.xml.
`<resource-file src="google-services.json" target="app/google-services.json" />`
`<resource-file src="GoogleService-Info.plist" />`

I've been looking for info here but can't find it (**this is very important**)
https://www.construct.net/en/make-games/manuals/addon-sdk/reference/iplugininfo
https://www.construct.net/en/make-games/manuals/addon-sdk/reference/specifying-dependencies

**Comment by SparshaDhar** [comment]
Hi, @AshleyScirra this is not a fork of `firebase-config`.
For cordova-firebase plugins to work, we need user provided files such as `google-services.json` and `GoogleService-Info.plist`.
Users need to provide files like this:
![image](https://user-images.githubusercontent.com/42723600/176275378-0b2c6c4b-6790-4802-9771-ee2cb99de495.png)

And in this way, the file will be located in the folder named `www\` after exporting to cordova.

But according to the Docs of the cordova-firebase plugins, it requires those two files to be located in some other directory like `platforms\android\app` (for android) and `platforms/ios/<appName >/Resources/` (for ios).

What `sparsha-firebase-config` does is move these files from `www/` to these required locations.

**Comment by SparshaDhar** [comment]
> how to add `<resource-file>` In IPluginInfo
> 
> dependencies are automatically included in the exported config.xml. `<resource-file src="google-services.json" target="app/google-services.json" />` `<resource-file src="GoogleService-Info.plist" />`
> 
> I've been looking for info here but can't find it (**this is very important**) https://www.construct.net/en/make-games/manuals/addon-sdk/reference/iplugininfo https://www.construct.net/en/make-games/manuals/addon-sdk/reference/specifying-dependencies

Yes, allowing us to include our own `<resource-file>` tag in config.xml will totally solve this issue!
