### ISSUE TITLE
Mouse.X and Mouse.Y don't update while hovering HTML elements.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#5787]
## Problem description

When you hover HTML elements, like drop down menus or text inputs, Mouse.X and Mouse.Y don't update.

EDIT: Mouse.AbsoluteX and Y also don't update.

## Attach a .c3p

[mouse_hover_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/8905537/mouse_hover_bug.zip)

## Steps to reproduce

1. Create some HTML element.
2. Hover the mouse on it.
3. Observe numbers don't change while hovering.

**Affected browsers/platforms:**  Tested on Chrome.
**First affected release:**  Tested on r298.

## System details

There was no crash.

**Comment by AshleyScirra** [comment]
This is currently by design. HTML elements consume input events like mouse movements and keyboard input to avoid form controls input interfering with the game (e.g. using arrow keys in a text input should not also move an 8 Direction behavior).
