### ISSUE TITLE
Deleting a global layer leaves all other layers with the same name "overridden"

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#579]
## Problem description

I deleted a layout with a global layer after making some duplicates of that layout. Then, when I later duplicated one of the copies, all the objects placed in the global layer vanished from all the layouts. This is the same thing that happens if just the original global layer is deleted, but not the layout - in both cases all the remaining layers that share the name of the original, now-deleted global layer are marked "overridden", which I guess means they're empty since the global layer is gone.

I checked C2 and it looks like there, if the user tries to delete a global layer, a warning appears saying all instances of that layer will be deleted too, and giving the user a chance to cancel. However it doesn't do this if a layout containing the original global layer is deleted.

## Attach a .c3p

[GlobalLayerBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1117661/GlobalLayerBug.zip)

## Steps to reproduce

1. Create a layer in a layout (I'll call this layout Layout 1).
2. Make the layer global.
3. Put something in the global layer, like a sprite.
4. Duplicate the layout (Create Layout 2). The sprite appears in the duplicated layout properly, and the global layer is marked "overridden" in the new layout.
5. Delete the original layout (Layout 1). The sprite still appears in the duplicated layout, as expected (however the global layer is still marked as "overridden", with no way to change it).
6. Duplicate the layout (Create Layout 3).
7. Open the new layout.

## Observed result

The sprite (and any other objects) is now gone from the global layer in the new layout. Reopening Layout 2 will show its contents are gone now too.

## Expected result

C3 warns the user that deleting a global layer or layout containing it will result in the layer(s) being deleted from all layouts, the same way C2 handles it. 

I would ideally want the option for remaining instances of the global layer to be preserved even if the original layout has been deleted - the user could be prompted to either pick a new instance to become the new global "master" layer, or to allow all layers with that name to be deleted, or cancel. But a simple warning/option to cancel would be good enough.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r42.3

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 307 mb (2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
@Scoremonger 

I already fixed the bug, the fix will be available in r44.

This is how it works, when you delete a global layer or a layout containing a global layer, all layers that were overridden revert their state to normal. This means that they cease to show content of the deleted global layer and start showing again their own content (if they had any previously to being overridden).

They are not deleted and their **Global** property in the properties bar shows **No**

We didn't include the message that C2 gives before deleting a layer because we think it is not needed. If deleting the layer was a mistake, you can simply UNDO the change. 

Adding the option to set a new master global layers sounds like a good idea, it would be an improvement though so I will leave for further down the line.

**Comment by Scoremonger** [comment]
Thank you! Sounds like a good solution.
