### ISSUE TITLE
Browser Request/Cancel Fullscreen actions don't work after pressing F11

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5795]
## Problem description

If you press F11 to manually enter fullscreen in browser, actions to cancel/request fullscreen stop working.
Also `Browser Is Fullscreen` condition wrongly returns false.

## Attach a .c3p

https://www.dropbox.com/s/7g0uvqr4nf44wex/Fullscreen.c3p?dl=0

## Steps to reproduce

1. Preview the project and press F11
2. Try pressing "Toggle fullscreen" button

## Observed result

The button has no effect. Also the first time you press it, the text reads "Fullscreen OFF"

## Expected result

Cancel fullscreen action should work.

I suppose the browser is overriding requests to cancel fullscreen after F11 was pressed. 
If there is no way to fix this, could you at least make the `Is Fullscreen` to condition to work correctly in this case?

## More details

**Affected browsers/platforms:** Chrome/Firefox

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r298 (beta)
Browser: Chrome 102.0.5005.115
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 271 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks like a problem with the browser - F11 fullscreen state appears to work independently of requesting fullscreen from JavaScript.

I filed an issue with Google here and will follow up there: https://bugs.chromium.org/p/chromium/issues/detail?id=1337785

**Comment by F3der1co** [comment]
That is sad, as with this exception the condition is not really usable imo.
I guess comparing the window size with the screen size would be a way, but there might be other exception with that as well.
