### ISSUE TITLE
r298 Particles turned black

### ISSUE THREAD

**Issue by EAsome** [Scirra/Construct-3-bugs#5799]
## Problem description

In the editor it looks normal and original color but when I play it, it turned black and it's not on the first layer for no reason,
I tried cloning it but still

## Steps to reproduce

1.
2.
3.

## Observed result

![image](https://user-images.githubusercontent.com/101848849/174461216-c21f4479-d92f-4f46-9b5f-c2928af0bfe2.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** r298

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. I'm afraid it's impossible to help unless you provide the necessary information. This process is also intended to make sure the problem is not just a mistake in your project, which is quite common.
