### ISSUE TITLE
R17 Crash:  Save As -> To Local Browser

### ISSUE THREAD

**Issue by bigcatrik** [Scirra/Construct-3-bugs#58]
Save As -> 
Save to Local Browser ->
Type in "Filename" text box ->
Crash

Error report information
Type: unhandled exception
File: https://editor.construct.net/r17/main.js, line 2, col 210681
Message: Uncaught TypeError: Cannot read property 'toLowerCase' of null
Stack: TypeError: Cannot read property 'toLowerCase' of null at Function.ǃE.ǃbTE (https://editor.construct.net/r17/main.js:2:210681) at ǃE.ǃv.ǃEgd.ǃJU (https://editor.construct.net/r17/main.js:50:40651) at window.addEventListener.te (https://editor.construct.net/r17/main.js:50:40118)
Construct 3 version: r17
URL: https://editor.construct.net/index.html
Date: Tue Apr 11 2017 09:49:40 GMT-0700 (PDT)
Uptime: 23.9 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.146
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Chrome OS
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
User agent: Mozilla/5.0 (X11; CrOS x86_64 9202.64.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.146 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Bay Trail 
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by shortercode** [comment]
Looks like there was a partially unrelated change that assumed all inputs would have an explicit type set, so I've added a default value. Should work again in r18!
