### ISSUE TITLE
[r42.3] Oh snap! After clicking on any UI dialogue's close [x] button

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#580]
## Problem description

I keep getting Oh Snap! By just clicking on the UI's close button [x]

## Steps to reproduce

1. Open any pop-up dialogue UI. (such as profile, behaviour, settings)
2. Close with the X button. at the top corner.

## Observed result

Oh snap! page appeared. There is no crash report to be logged from C3 at all. I can also reproduce this on incognito mode with the same steps.

## Expected result

Does not go Oh snap!

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r42.3

Local storage
Storage quota (approx): 7.2 gb
Storage usage (approx): 25 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Not sure there's much we can do here, it's a Chrome bug which needs to be reported to Google if Chrome crashes. Does clearing your cache help?

**Comment by jaydonteh** [comment]
It does, but it reoccurs again after a few use. I'm not sure how to go about this. Maybe I'll try reinstall chrome if it helps.

**Comment by AshleyScirra** [comment]
Even if you can reproduce it I'd recommend filing on crbug.com instead - it's not usually possible for web content to crash Chrome like that, so there's not much we can do about it.

**Comment by jaydonteh** [comment]
I found the cause. It was because I disable the UI animation (yet another UI animation bug). It might be the quirks from the polyfill changes.

**Comment by AshleyScirra** [comment]
Huh, I can reproduce after changing that setting. Still seems to happen in Canary too. It still is a Chrome issue so nothing we can directly fix, but I'll leave this open till I get round to filing a bug with Google.

**Comment by AshleyScirra** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=739199, will follow up there.
