### ISSUE TITLE
Poor editor performance

### ISSUE THREAD

**Issue by EydiavHamri** [Scirra/Construct-3-bugs#5801]
## Problem description

Sluggish editor performance for layouts with many instances.
I hadn't encountered editor performance issues until r286 beta. I noticed it immediately then, but didn't have time to report. Apologies.

## Attach a .c3p
This project file is meant to emulate a massive game, hence the high object count.
[EditorPerformance.zip](https://github.com/Scirra/Construct-3-bugs/files/8941723/EditorPerformance.zip)

## Steps to reproduce

Try the following:

- Select many objects, or all of them with Ctrl+A

- Move many instances around and resize them

- Pan around the layout

## Observed result

When doing the above actions Construct is struggling to keep up. It is especially severe in Firefox.
Here's a video demonstration of the issue

https://user-images.githubusercontent.com/44640946/174631915-c4c3e0f3-2de5-4404-8210-29ed46b62767.mp4

## Expected result

I expect smooth or acceptable performance (depending on how reasonable the project is)
There are virtually no editor performance issues in earlier builds, as demonstrated in this video

https://user-images.githubusercontent.com/44640946/174632337-baf7c71e-218a-4be1-a0a6-991e331d2ef1.mp4

## More details

**Affected browsers/platforms:** 
I tested with:

- Chrome 102.0.5005.115 (64-bit)

- Edge 102.0.1245.44 (64-bit)

- Firefox 101.0.1 (64-bit)

**First affected release:** 
Worked in [r285.3 stable](https://editor.construct.net/r285-3/), issue started in [r286](https://editor.construct.net/r286/)
(Same build as when the templates feature was introduced. I could imagine the issue lies somewhere there)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r298 (beta)
Browser: Chrome 102.0.5005.115
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 95 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
@DiegoScirra - looks like the new template code is thrashing CanPropertyBeUsedByTemplate during rendering. This should be fixed before the next stable to avoid regressing performance. Hopefully something straightforward can be done.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
