### ISSUE TITLE
Timeline - Adding Z El property causes editor to crash

### ISSUE THREAD

**Issue by Rhindon** [Scirra/Construct-3-bugs#5802]
## Problem description

Adding Z-Elevation Property to Timeline Object Instance Causes Crash

## Attach a .c3p

[https://drive.google.com/file/d/1suJkTVtemhcQeNhVPuu7_a1MyYESug5Q/view?usp=sharing](https://drive.google.com/file/d/1suJkTVtemhcQeNhVPuu7_a1MyYESug5Q/view?usp=sharing)
OR
[That's Stacked Up - Z-El Crash.zip](https://github.com/Scirra/Construct-3-bugs/files/8943336/That.s.Stacked.Up.-.Z-El.Crash.zip)

## Steps to reproduce

1. Add (presumably) any object to the Timeline.
2. With or without any other existing properties for that object instance in the Timeline, add the Z Elevation property.
3. The editor will then completely crash.

## Observed result

Adding the Z Elevation property to any existing object instance will cause a full editor crash.

## Expected result

To be able to add the Z Elevation property and edit its performance.

## More details
Per my included project file...
The _Grid2_ object was already on the Timeline and only its size was to be affected.
I added the _Grid_ object which would see its size then Z Elevation properties affected. It wasn't until I added the Z Elevation property that I discovered the problem but I wasn't aware of the exact cause.
I narrowed this down by adding Z Elevation to both the _Grid_ and _Grid2_ object instances with and without existing properties.
No other changes or edits were made except for adjusting the timescale slider (red line) but that seemed to make no difference as the crash still happened even when I didn't touch the slider.

**Affected browsers/platforms:** Chrome only (most up-to-date version).

**First affected release:** r298 (I have not used the Timeline feature prior to this release.)

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: this.OQ is not a function @ TypeError: this.OQ is not a function at qI.fG (https://editor.construct.net/r298/projectResources.js:1127:122) at qI.KA (https://editor.construct.net/r298/projectResources.js:1124:303) at NRa.Xf (https://editor.construct.net/r298/projectResources.js:1180:304) at d.ylb (https://editor.construct.net/r298/projectResources.js:1106:384) at new d (https://editor.construct.net/r298/projectResources.js:1104:172) at xa.j (https://editor.construct.net/r298/main.js:985:44) at d.dBa (https://editor.construct.net/r298/projectResources.js:1091:476) at d.RM (https://editor.construct.net/r298/projectResources.js:1091:271) at d.FBb (https://editor.construct.net/r298/projectResources.js:1091:6) at new d (https://editor.construct.net/r298/projectResources.js:1080:357)
Stack: TypeError: this.OQ is not a function at qI.fG (https://editor.construct.net/r298/projectResources.js:1127:122) at qI.KA (https://editor.construct.net/r298/projectResources.js:1124:303) at NRa.Xf (https://editor.construct.net/r298/projectResources.js:1180:304) at d.ylb (https://editor.construct.net/r298/projectResources.js:1106:384) at new d (https://editor.construct.net/r298/projectResources.js:1104:172) at xa.j (https://editor.construct.net/r298/main.js:985:44) at d.dBa (https://editor.construct.net/r298/projectResources.js:1091:476) at d.RM (https://editor.construct.net/r298/projectResources.js:1091:271) at d.FBb (https://editor.construct.net/r298/projectResources.js:1091:6) at new d (https://editor.construct.net/r298/projectResources.js:1080:357)
Construct version: r298
URL: https://editor.construct.net/r298/
Date: Mon Jun 20 2022 14:48:09 GMT-0500 (Central Daylight Time)
Uptime: 9.9 s

Platform information
Product: Construct 3 r298 (beta)
Browser: Chrome 102.0.5005.115
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_video_texture, WEBGL_webcodecs_video_frame, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.

**Comment by Rhindon** [comment]
> This will be fixed in the next beta.

Oh! Good to know! Thanks, Diego.
