### ISSUE TITLE
Changing initial value affects all instances even if none are selected

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#5804]
## Problem description

Changing the _initial value_ of an object variable affects all existing instances even if none are selected. This makes it impossible to set a different initial value for newly placed instances without it changing all of the existing instances throughout the project. I would consider this a bug or at least a misnomer of sorts because I don't want to change any existing values, just the one that newly placed instances start with.

In my particular case, I have changed the math which uses a variable from a family type that already has many instances placed throughout the project. I now need the initial value of the variable in this family type to start at 100 instead of 0, but there seems to be absolutely no way of doing this without setting all existing instances' values to 100. This forces me to go back and update every single instance to what they were beforehand.

## Attach a .c3p

[InitialValue.zip](https://github.com/Scirra/Construct-3-bugs/files/8950237/InitialValue.zip)

## Steps to reproduce

1. Close all layout tabs
2. In the Project Bar, select the Sprite object and go to Edit Instance variables (note that no instances are selected)
3. Change the initial value of Variable1 to anything
4. Open Layout 1
5. Click any sprite instance and look at the value for Variable1

## Observed result

Variable1 has been changed to the new initial value for all existing instances.

## Expected result

Variable1 to not be changed to the new initial value for the existing instances. Instead, only newly placed instances should use the new initial value. This is what makes it _Initial Value,_ which should not function the same as changing the value after clicking "Select All Instances".

## More details

**Affected browsers/platforms:** all

**First affected release:** all

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 102.0.0.0
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
C3 release: r293.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 141 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Editing an instance variable has no relation to the selected instances in the Layout View. The "Initial value" field will show the initial value if it's the same for all instances in the project; if it's not the same for all instances, it says "(varies)". If you then type in a new value, it applies to all instances in the project.

I'm not quite clear on what your workflow is but I think there is a misunderstanding here - the field is reflecting the current state of the values in the project, and is not used when determining the default for newly placed instances in the editor, or newly created instances at runtime.
