### ISSUE TITLE
dark theme, timeline cascade track button nearly invisible

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5806]
In the dark theme, the timeline cascade track button is nearly invisible.
You can see the one to the left of the audio track because it's currently highlighted, but the one to the left of "Sprite - 2" is almost invisible. 
A different color, for example the dark grey that is also used (in the theme) for the cascade button on folders in the project bar would be better. 
![cascadeTimeline](https://user-images.githubusercontent.com/89512047/174882033-4def2a93-096a-416e-89d4-3d490de11cc4.png)

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
