### ISSUE TITLE
'Is enabled' condition is not documented for most behaviors

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-3-bugs#5808]
Documentation says nothing about 'Is enabled' condition for following behaviors:

[8Direction](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/8-direction)
[Anchor](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/anchor)
[Bullet](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/bullet)
[Car](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/car)
[Custom Movement](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/custom-movement)
[Pathfinding](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/pathfinding)
[Platform](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/platform)
[Rotate](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/rotate)
[Scroll To](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/scroll-to)
[Turret](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/turret)

## Observed result

'Is enabled' condition is not documented.

## Expected result

'Is enabled' condition should be documented.

**Comment by AshleyScirra** [comment]
Updated manual entries to include 'Is enabled' for all cases.
