### ISSUE TITLE
8Direction's behavior 'Maxspeed' expression typo

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-3-bugs#5809]
## Problem description

8Direction's behavior **MaxSpeed** expression is not written as it should.

## Steps to reproduce

1. Create new project
2. Add new object type (ex. Sprite) and add 8Direction behavior to it
3. Go to event sheet and open Expressions dictionary for created object type
4. Scroll to 8Direction behavior expressions section

## Observed result

**MaxSpeed** expression is written as _Maxspeed_: https://ibb.co/DKKF9Nw

## Expected result

**MaxSpeed** expression should be written as **MaxSpeed**, how it was in C2: https://ibb.co/N9pn4bT

## More details

**Affected releases:** r293.3 & r299 (current stable & beta)

**Comment by AshleyScirra** [comment]
Fixed for next beta.
