### ISSUE TITLE
Sine's behavior ACEs list name in documentation not updated

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-3-bugs#5811]
## Problem description

Sine's behavior ACEs ('Is enabled' condition and 'Set enabled' action) list name in [documentation](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/sine) not updated.

## Observed result

The [documentation](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/sine) still refers to the **Is enabled** condition and **Set enabled** action by their previous names:
_Is active
Set active_

## Expected result

The [documentation](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/sine) should refer to the **Is enabled** condition and **Set enabled** action by their actual names:
_Is enabled
Set enabled_

**Comment by AshleyScirra** [comment]
Thanks, updated the manual entry.
