### ISSUE TITLE
No Speech Synthesis on Safari iOS 15.5 (iPad)

### ISSUE THREAD

**Issue by Didaktik-digital** [Scirra/Construct-3-bugs#5813]
## Problem description

When exporting the example "Speech synthesis demo" from the latest version of Construct 3 (r299 Beta) to HTML5 and uploading it to a standart hosting, the result does not output any speech.

## Attach a .c3p

Please use the example "Speech synthesis demo" from the latest version of Construct 3 (r299 Beta)

## Steps to reproduce

1. Export the project as HTML5
2. Upload to webhosting
3. Acces the project url with Safari on iOS 15.5 (iPad)
4. Press the Speak button
5. Select another voice and press the Speak button

## Observed result

Nothing happens - no TTS audio is being played

## Expected result

I tested the WebSpeech API with Safari on iOS 1.5 (iPad) with this link: https://codepen.io/matt-west/pen/DpmMgE
Here the TTS audio is being played as expected and other voices can be selected and then played

## More details
Tested on iPad running iOS 15.5 with Safari

**Affected browsers/platforms:** 
Safari iOS 15.5 iPad

**First affected release:** 

## System details
iPad (7th Generation)
iOS 15.5

<details><summary>View details</summary>

No crash report

</details>

**Comment by AshleyScirra** [comment]
Have you disabled Siri on the device? IIRC if you disable Siri it also disables the system-wide speech recognition/synthesis service, which prevents those features working.

**Comment by Didaktik-digital** [comment]
Hey Ashley,
I just tested the SpeechRecognition example on the same device, with the same browser. And the SpeechRecognition example is running as expected. Also the codepen example from above is producing the expected output, likewise on the same device.

Best wishes
/Thomas

**Comment by AshleyScirra** [comment]
I'm confused, are you saying it works fine now? Can the issue be closed?

> Upload to webhosting

Is your host secure (https:)? Many modern browser features only work on secure hosts.

**Comment by Didaktik-digital** [comment]
Hey Ashley,
I used the Speech Synthesis Plugin of Construct and this is not working on Safari iOS 15.5.
You can test this out with the standart Construct Speech Synthesis example. (And yes, I use https domain).

I then tested the Web Speech Synthesis API on the same iPad, with the same browser (Safari iOS 15.5 - using the ocde pen above) and here it works as expected. 

So, it works o iPad without using Construct (using plain Html,css and js).  
But when using the Construct Speech Synthesis Plugin it does not work.

(Sidenote: I also found an error in the Construct Speech Recognition Plugin, likewise on Safari and iOS 15.5 - but will post that seperatly as an issue tomorrow)

**Comment by AshleyScirra** [comment]
I found that Safari on iOS seems to have some restrictions on usage that Safari on macOS doesn't, which is a bit odd, but it was straightforward to work around so it should be fixed in the next beta.

**Comment by Didaktik-digital** [comment]
Brilliant!
And thank you so much - we really enjoy using this engine, and are super impressed by the work you guy's do.
