### ISSUE TITLE
Creating brand new instances distanced from each other by their own width.

### ISSUE THREAD

**Issue by TeamDisgrace** [Scirra/Construct-3-bugs#5815]
## Problem description
Hello. I'm trying to create 3 sprites on the start of the layout, which should be separated from each other by the distance of their own with. However, the sprites overlay each other when created. I tried making an _**object repository**_ layout but it didn't help. I also tried new _**template**_ feature but it also didn't help. I asume that sprite just couldn't get the information about its width since there are no instances of this object on the layout yet. Fixing this might be a great addition to the new template feature. But for now, please, let me know if there's a solution.

## Attach a .c3p
[TestProj.zip](https://github.com/Scirra/Construct-3-bugs/files/8979957/TestProj.zip)

## Steps to reproduce
![Noname](https://user-images.githubusercontent.com/94541962/175645746-7e7e1ce9-054b-4de5-8a39-623c14ac8ac0.png)

## Observed result
Multiple instances of the red sprite overlay each other
![Bad](https://user-images.githubusercontent.com/94541962/175645307-cdef9145-1bf7-4f0a-bd8f-fedc93968a6c.png)

## Expected result
All 3 red sprites are at a distance of their own width from each other.
![Good](https://user-images.githubusercontent.com/94541962/175645441-cfac64d8-09da-4df1-b43f-e54c9af924f8.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System deta

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's not a bug, it's a mistake in your project. If no Sprite objects exist, all its expressions return 0, so Sprite.width will return 0.

Just drop a sprite on to the layout somewhere outside the visible area and destroy it on startup, and that will be enough to have an actual width returned for the Sprite object.
