### ISSUE TITLE
How render cells work

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5818]
## Problem description

The link to the article has been lost.

## Attach a .c3p

https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/layers

## Steps to reproduce

1. Follow the link.
2. Find the `Layer properties` section.
3. Find the item `Use render cells`.
4. Follow the hyperlink indicated in the paragraph.

## Observed result

![ccc](https://user-images.githubusercontent.com/91274932/175827127-8c5821e2-c5b5-400a-a0df-d892c3f29b82.png)

https://www.construct.net/en

## Expected result

I can read the article `How render cells work`.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

![inscryption](https://user-images.githubusercontent.com/91274932/175827374-34cc405b-90fe-4e6e-90e0-482114318fea.gif)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed the link.
