### ISSUE TITLE
Most example projects use the old icon design

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-3-bugs#5819]
## Problem description

In the current C3's stable + beta release (r293.3 & r299), half of the example projects still use the old C2 logo icons (in _Icons_ folder). I think they need to be updated to the new C3 logo.

## Steps to reproduce

1. Open any project from the list below
2. Go to Project Bar and scroll down to the _Icons_ folder
3. Expand folder (if not expanded)

## Observed result

https://ibb.co/vksKY04

## Expected result

https://ibb.co/MpXPwtH

## Projects list

[8 Direction behavior](https://editor.construct.net/#open=8-direction-behavior)
[9-patch object](https://editor.construct.net/#open=9-patch-plugin)
[Audio analyzer](https://editor.construct.net/#open=audio-analyser)
[Audio effects](https://editor.construct.net/#open=audio-effects)
[Audio scheduling](https://editor.construct.net/#open=audio-scheduling)
[Basic hierarchy](https://editor.construct.net/#open=basic-hierarchy)
[Blend modes](https://editor.construct.net/#open=blend-modes)
[Bouncing balls](https://editor.construct.net/#open=bouncing-balls)
[Bouncing bullets](https://editor.construct.net/#open=bouncing-bullets)
[Bounding box performance](https://editor.construct.net/#open=bouncing-bullets)
[Camera effects](https://editor.construct.net/#open=camera-effects)
[Camera input](https://editor.construct.net/#open=camera-input)
[Custom movement ('Asteroids' style)](https://editor.construct.net/#open=custom-movement-asteroids)
[Demonoire](https://editor.construct.net/#open=demonoire)
[Detecting input method](https://editor.construct.net/#open=detecting-input-method)
[Driving](https://editor.construct.net/#open=template-driving)
[Effects: Glass](https://editor.construct.net/#open=effects-glass) (this example also contains transparent C2's logo on the layout)
[Effects: Haze](https://editor.construct.net/#open=effects-haze)
[Effects: Luminance transition](https://editor.construct.net/#open=effects-luminance-transition)
[Effects: Old TV](https://editor.construct.net/#open=effects-oldtv)
[Effects: Pixellate transition](https://editor.construct.net/#open=effects-pixellate-transition)
[Effects: Ripple transition](https://editor.construct.net/#open=effects-ripple-transition)
[Effects: Screen Blend](https://editor.construct.net/#open=effects-screen-blend)
[Effects: Swirl transition](https://editor.construct.net/#open=effects-swirl-transition)
[Effects: Water transition](https://editor.construct.net/#open=effects-water-transition)
[Endless runner](https://editor.construct.net/#open=template-endless-runner)
[Falling blocks](https://editor.construct.net/#open=falling-blocks)
[Families](https://editor.construct.net/#open=families)
[Fill rate performance](https://editor.construct.net/#open=fillrateperf)
[Flapping bird](https://editor.construct.net/#open=template-flapping-bird)
[Flying along](https://editor.construct.net/#open=template-flying-along)
[Gamepad control](https://editor.construct.net/#open=gamepad-control)
[Ghost Shooter Code](https://editor.construct.net/#open=ghost-shooter-code)
[Ghost Shooter Tutorial](https://editor.construct.net/#open=ghost-shooter-tut)
[Glokar](https://editor.construct.net/#open=glokar)
[Infinite Jumping](https://editor.construct.net/#open=template-infinite-jumping)
[Instance Variables](https://editor.construct.net/#open=instance-variables)
[JSON](https://editor.construct.net/#open=json)
[Kiwi Story](https://editor.construct.net/#open=kiwi-story)
[Line Of Sight](https://editor.construct.net/#open=line-of-sight)
[Mesh platforms](https://editor.construct.net/#open=mesh-platforms)
[Microphone input](https://editor.construct.net/#open=microphone-input)
[Move along path](https://editor.construct.net/#open=move-along-path)
[Move to position](https://editor.construct.net/#open=move-to)
[Multiplayer: Chat room](https://editor.construct.net/#open=multiplayer-chat)
[Multiplayer: Pong](https://editor.construct.net/#open=multiplayer-pong)
[Multiplayer: Real-time game](https://editor.construct.net/#open=multiplayer-game)
[Particle explosions](https://editor.construct.net/#open=particle-explosions)
[Particle fountain](https://editor.construct.net/#open=particle-fountain)
[Particles](https://editor.construct.net/#open=particles)
[Pathfinding](https://editor.construct.net/#open=pathfinding)
[Pathfinding: path cost](https://editor.construct.net/#open=pathfinding-path-cost)
[Persistent layouts](https://editor.construct.net/#open=persistent-layouts)
[Physics catapult](https://editor.construct.net/#open=template-physics-catapult)
[Physics puzzle](https://editor.construct.net/#open=template-physics-puzzle)
[Physics scripting](https://editor.construct.net/#open=physics-scripting)
[Physics: Basics](https://editor.construct.net/#open=physics-basics)
[Physics: Distance joint](https://editor.construct.net/#open=physics-distance-joint)
[Physics: Force point](https://editor.construct.net/#open=physics-force-point)
[Physics: Ragdoll](https://editor.construct.net/#open=physics-ragdoll)
[Physics: Revolute joint](https://editor.construct.net/#open=physics-revolute-joint)
[Physics: Rolling platformer](https://editor.construct.net/#open=physics-rolling-platformer)
[Physics: Vehicle](https://editor.construct.net/#open=physics-vehicle)
[Pick nearest](https://editor.construct.net/#open=pick-nearest)
[Pin chain style](https://editor.construct.net/#open=pin-chain-style)
[Pin rope style](https://editor.construct.net/#open=pin-rope-style)
[Platformer](https://editor.construct.net/#open=template-platformer)
[Pop Lab](https://editor.construct.net/#open=poplab)
[Quad issue performance](https://editor.construct.net/#open=quadissueperf)
[Raycast reflections](https://editor.construct.net/#open=raycast-reflections)
[Real time strategy (RTS)](https://editor.construct.net/#open=template-real-time-strategy)
[Rotating platformer](https://editor.construct.net/#open=rotating-platformer)
[Savegames](https://editor.construct.net/#open=savegames)
[Screen recording](https://editor.construct.net/#open=screen-recording)
[Shadows: Colors](https://editor.construct.net/#open=shadows-colors)
[Shadows: Light height](https://editor.construct.net/#open=shadows-light-height)
[Shadows: Soft penumbras](https://editor.construct.net/#open=shadows-soft-penumbras)
[Shadows: Blending multiple lights](https://editor.construct.net/#open=shadows-blending-multiple)
[Simple keyboard movement](https://editor.construct.net/#open=simple-keyboard-movement)
[Simple lighting](https://editor.construct.net/#open=simple-lighting)
[Sine behavior types](https://editor.construct.net/#open=sine-behavior-types)
[Space Blaster](https://editor.construct.net/#open=space-blaster)
[Speech recognition](https://editor.construct.net/#open=speech-recognition)
[Speech synthesis](https://editor.construct.net/#open=speech-synthesis)
[System 'Wait' action](https://editor.construct.net/#open=system-wait)
[Taking screenshots](https://editor.construct.net/#open=taking-screenshots)
[The 'Rain demo'](https://editor.construct.net/#open=ghost-shooter-rain-demo)
[Tile-based game](https://editor.construct.net/#open=template-tile-based-game)
[Tile-based pathfinding](https://editor.construct.net/#open=tile-based-pathfinding)
[Tilemaps](https://editor.construct.net/#open=tilemaps)
[Top-down shooter](https://editor.construct.net/#open=template-top-down-shooter)
[Touch: panning](https://editor.construct.net/#open=touch-panning)
[Touch: rotating](https://editor.construct.net/#open=touch-rotating)
[Touch: zooming](https://editor.construct.net/#open=touch-zooming)
[Turret behavior](https://editor.construct.net/#open=turret-behavior)
[Turret defense](https://editor.construct.net/#open=template-turret-defense)
[Turret predictive aim](https://editor.construct.net/#open=turret-predictive-aim)
[Unique IDs](https://editor.construct.net/#open=unique-ids)
[Vertical space shooter](https://editor.construct.net/#open=template-vertical-space-shooter)
[Vibrate](https://editor.construct.net/#open=vibrate)
[XML](https://editor.construct.net/#open=xml)

**Comment by AshleyScirra** [comment]
This would be a lot of boring manual work to fix and I don't think it's important enough to justify using our very limited time on that, so I think we will just leave it.
