### ISSUE TITLE
Highlighting isn't removed from Conditions and Actions after copy/paste or initial event creation

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#582]
## Problem description

After copy/pasting or dragging to reorder an event, and then clicking off of the event, the highlighting of conditions and actions inside the event isn't removed. Similarly, if you create a new event, the initial condition remains highlighted even when another event is selected.

## Attach a .c3p

[CopyPasteHighlightBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1121709/CopyPasteHighlightBug.zip)

## Steps to reproduce

1. Create an event with one condition and one action
2. Click "Add event" to create a second event. Note that the condition in the first event remains highlighted, while the action in the first event is properly de-highlighted
3. Click the second event with a condition and action, and drag it up to reorder the two events
4. Click the empty space below the events to deselect them both

## Observed result

The yellow highlighting remains on the condition of the original event, and on both the condition and the action of the second event.

## Expected result

All highlighting is removed when an event is deselected.

Note that it's possible to remove the highlighting by clicking each highlighted element and then clicking somewhere else to deselect it. After that the highlighting of these element works properly.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r42.3

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 307 mb (2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r44.
