### ISSUE TITLE
Buggy loading of Layouts if "Go to Layout" Action executes after Wait Action

### ISSUE THREAD

**Issue by MihaMS** [Scirra/Construct-3-bugs#5820]
## Problem description

Layout loads buggy if requested after Wait Action.
The action on next On start of layout is not executed as expected (This only happened if Layout started after Wait)

## Attach a .c3p

https://drive.google.com/file/d/1kWta41KZ_RvSUPNsq_a-0jA89VOZzlpj/view?usp=sharing

## Steps to reproduce

1. Open attached project
2. Run it via F4

## Observed result

Sprite rectangle at Left - Incorrect position

## Expected result

Sprite rectangle at Right - Correct position

## More details

If we remove Wait Action before GoTo Layout Action - Sprite will be in Correct position after Layout 2 will be started
If we run Layout 2 at the beginning (by F5 or setting it as first layout to load) - Sprite will be in Correct position

I made workarounds like using Timer behavior in objects to trigger GoTo Layouts with delay, or use Wait 0 at the start of requested layouts... But in really big projects that creates a lot of unnecessary crutches. And it's better to work as intended.

Yes, in example Move Sprite action can be moved to the first "On start of layout", but in a real (big) project I'm using "Included event sheet" so this two On start of layout - imitates this.

**Affected browsers/platforms:** 
Chromium (not tested on other platforms)

**First affected release:** 
Construct 3 - r293.3 stable (not tested in previous releases)

## System details
Windows 10

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This turned out to be a tricky case of the 'Wait' action not completely resetting state after it ran, which caused the second 'Start of layout' event in the new layout to run with zero Sprite instances picked. It should be fixed for the next build.
