### ISSUE TITLE
3d object fx bug

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#5821]
## Problem description
Using an effect on an individual object can make the texture get cut at certain views.

## Attach a .c3p
https://www.dropbox.com/s/enyeye31fi0xgs5/3dobjectfxbug.c3p?dl=1

## Steps to reproduce

1. Run the project
2. If the texture background is not already cut off, then move the object around with the keyboard.

## Observed result
The Tiled Background's texture is cut off at certain camera views. It seems like the texture is constrained to the 2d box.

## Expected result
The texture, and fx  should work like layer fx do.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, the effect compositor was missing a check for this specific case (2D object with 3D camera). Fixed for next beta.
