### ISSUE TITLE
How render cells work again

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5822]
## Problem description

Links to the article are missing.

## Attach a .c3p

https://www.construct.net/en/blogs/ashleys-blog-2/render-cells-work-921

## Steps to reproduce

1. Follow the link.
2. `collision cell optimization` and `back-to-front renderer` are gone.

## Observed result

![a1](https://user-images.githubusercontent.com/91274932/175987537-1643a75f-2582-4d13-a509-5ae65d427ecf.png)

![a2](https://user-images.githubusercontent.com/91274932/175987552-e9bd2270-f9b1-4452-b623-d18f4bcaf91d.png)

## Expected result

I can read articles.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in 2022

## System details

<details><summary>View details</summary>

![inscryption](https://user-images.githubusercontent.com/91274932/175827374-34cc405b-90fe-4e6e-90e0-482114318fea.gif)

</details>

**Comment by AshleyScirra** [comment]
Updated the links (and a few more I found following the links).
