### ISSUE TITLE
Render performance

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5823]
## Problem description

I have 300 sprite instances, which are located on a separate layer, where there is nothing else besides them. At startup everything is fine, 60 fps. But when I move the pink sprite, which is on another layer, my fps drops a lot.

## Attach a .c3p

[render_performance_r299b.zip](https://github.com/WilsonPercival/WilsonPercival/files/8994004/render_performance_r299b.zip)

## Steps to reproduce

1. Open and run the project.
2. Press the `S` key.

## Observed result

![a1](https://user-images.githubusercontent.com/91274932/175989885-e0a40dac-6c65-4a8c-82fd-f9b0bc8c0e57.gif)

## Expected result

![a2](https://user-images.githubusercontent.com/91274932/175989900-67061192-c264-492e-aec0-e3f33325001e.gif)

## More details

You can increase the number of instances to better see the effect.

It looks good in classic.

![classic](https://user-images.githubusercontent.com/91274932/176008956-386da5f8-6731-40e2-912b-baac8b59b0bd.gif)

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r299b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r299 (beta)
Browser: Chrome 102.0.5005.115
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 229 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This isn't a bug. If nothing changes C3 skips rendering, as rendering the same scene again just wastes system resources (and power on battery devices). So if nothing is changing then your performance measurements aren't useful. As soon as things start changing because a sprite is moving, it starts re-rendering everything, and so you see the true performance of the game.

This is why Construct's own performance tests have a small spinning sprite in the corner, to force constant re-rendering.

**Comment by AshleyScirra** [comment]
It could be done, but it would mean forcing that layer to use its own texture, which uses memory. So that makes a difficult trade-off between saving rendering time or saving memory. I'm not sure it would actually work out better overall if we did that.
