### ISSUE TITLE
Mouse cursor set from image does not scale with game window size.

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#5829]
## Problem description

When setting mouse cursor from a sprite the image renders in the same size (original image resolution) regardless of the window size.

## Attach a .c3p

[mouseCur.zip](https://github.com/Scirra/Construct-3-bugs/files/9003767/mouseCur.zip)

## Steps to reproduce

1. Preview the project.
2. Change the window size (actual browser window to affect inner window).

## Observed result

The mouse cursor stays in the same resolution regardless of the inner game window size.

## Expected result

The mouse cursor should scale relatively to the game's window size.

## More details

**Affected browsers/platforms:** Chrome/NWjs

**First affected release:** r300

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I think your expected result is incorrect. The operating system does not scale mouse cursors depending on the window size. Notice the normal cursor stays the same size no matter how large the window is. That remains true even if you set a custom cursor image.

**Comment by avishaymizrav** [comment]
@AshleyScirra 
That's true, but we're not in a normal operating system window, we are in a game window and for a game I think everything should scale relatively.

The only way to have a custom image for the mouse and have it on top of html or any other dom element is by using this feature.

Is it possible at least to have manual control of the render size? or is it an OS limit?

**Comment by AshleyScirra** [comment]
The feature replaces the OS cursor so no scaling will be done, and browsers also put a limit on the maximum cursor size so there is a limit to how far it can scale anyway. I would argue that for usability the cursor should not scale either; the user will expect the cursor to stay the same size like it does in the OS with all other apps too.

**Comment by avishaymizrav** [comment]
@AshleyScirra
If you run any game with a mouse cursor in window mode, you'll see that once the mouse is over the window and the window is active, the cursor size will snap and lock and scale with the view.

But OK, I get that it's a limitation, I'm trying to find another solution for displaying the mouse cursor image over html elements.

I tried adding another html object and injecting the images into that, it does work but it's a bit sluggish on the positioning, is this something that is going to get improved over time or is this the best it's going to get?

I also notice that the div get smaller when it reaches the edges of the viewport, instead of clamping to viewport or exiting the viewport, either would be better frankly.

[mouseDiv.zip](https://github.com/Scirra/Construct-3-bugs/files/9014815/mouseDiv.zip)

**Comment by AshleyScirra** [comment]
The OS cursor has special handling by the system to minimise its latency. You can only choose the OS cursor, which is low latency, or render your own cursor with higher latency. I would advise to use the OS cursor.

**Comment by avishaymizrav** [comment]
@AshleyScirra 
I didn't mean compared to the OS cursor.
Before this I just used a sprite with set position to the mouse, while this is a little slower than the OS, it is good enough and much more smoother than setting the html object to the mouse position.
There's much more latency with the html object than any canvas object.

**Comment by AshleyScirra** [comment]
HTML content updates differently to canvas content. I'm afraid there's not much that can be done about that, especially in worker mode, as the canvas and the HTML content run in different contexts that run independently of one another.
