### ISSUE TITLE
CSS discrepancy between Preview and Remote Preview

### ISSUE THREAD

**Issue by robertoParlevecchio** [Scirra/Construct-3-bugs#5832]
## Some CSS styles applied to a Button appear in the Preview but not the Remote Preview

Styles (added to a css file) such as color, background, font-family, font-size, etc are working across both Preview and Remote Preview, but others such as border-radius and box-shadow display correctly in Preview, but not in Remote Preview.

I've attached a simple .c3p file, and screenshots of the Preview and Remote Preview to see the difference, as well as a screenshot of the Safari Dev Tools (inspecting the Button element on my iPhone).

## Steps to reproduce

1. Open project
2. Click Preview to see it on your desktop
3. The button should appear with black text on white background with completely rounded corners and a drop shadow (see screenshot) 
4. Click Remote Preview to see it on your phone
5. The button has slightly rounded corners and no drop shadow (see screenshot) 

## Observed result

The button has slightly rounded corners and no drop shadow (see screenshot) 

## Expected result

The button should appear with completely rounded corners and a drop shadow (see screenshot) 

## More details

**Affected browsers/platforms:** iOS Safari 

**First affected release:** This is the first time I've tried this (version r293.3) 

## System details

Platform information
Browser: Chrome
Browser version: 103.0.0.0
Browser engine: Chromium
Context: webapp
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
C3 release: r293.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 27 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
<details><summary>View details</summary>

PASTE HERE

</details>
[bug report - css styles.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9007041/bug.report.-.css.styles.c3p.zip)
![remote-preview](https://user-images.githubusercontent.com/2385698/176345551-c4b754dc-c43c-4865-be66-d4f5785be141.png)
![preview](https://user-images.githubusercontent.com/2385698/176345554-4d39601c-969b-4545-88ff-ee35ae853d54.png)
![Safari dev tools](https://user-images.githubusercontent.com/2385698/176345867-15106aa3-213c-424d-ba59-643eaec15ad9.png)

**Comment by AshleyScirra** [comment]
Have you tried local preview in Safari too? It might just be that Safari handles the CSS differently. In particular it looks like you have a button but haven't modified the CSS `appearance` property, so it's not clear whether you're trying to adjust the browser-default style or use your own custom style entirely. You might need to add `appearance: none;`.

**Comment by robertoParlevecchio** [comment]
Thanks for the quick reply @AshleyScirra - Yes, I'm trying to style the button entirely with my own css and `appearance: none;` was exactly the fix it needed!

Thanks again,
Roberto

**Comment by AshleyScirra** [comment]
OK, sounds like you just needed to adjust your CSS to work cross-browser.
