### ISSUE TITLE
C3 does not respond to mouse clicks in iPad OS v15-16 (iPad Pro 12.9 M1)

### ISSUE THREAD

**Issue by arturbier** [Scirra/Construct-3-bugs#5834]
## Problem description

When I work for more than 1 hour in C3, then C3 stops responding to mouse clicks!

## Steps to reproduce

1. Open C3
2. Work for a while
3. You will see a bug with a broken mouse

## Observed result

https://user-images.githubusercontent.com/78679486/176453164-75a7fb91-bac7-4e3f-ab3a-f265f3231b1f.MOV

## Expected result

I want the mouse to work fully as well as on a PC! After all, this mouse is used by me on a Macbook where everything works fine!

## More details

This happens in any browser

This happens in any version of C3

**First affected release:** 

## System details

<details><summary>View details</summary>

IpadOS 15 , Ipad 12.9 M1

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's essentially impossible to investigate a bug that says "work for 1 hour" in the reproduction steps.

We might need to try the steps to reproduce 10-20 times in the course of investigating and fixing an issue and we also need a clear way to determine if the issue has reproduced or not.

It's essential to find a reliable set of steps we can follow to reproduce the issue, as per the bug report guidelines. Can you find a particular action or sequence of actions that causes the problem?

**Comment by AshleyScirra** [comment]
I'm afraid without clear steps to reproduce the problem it's impossible to investigate, so closing. If you can identify a clear sequence of steps to follow that causes the problem, please file a new issue.

**Comment by arturbier** [comment]
> I'm afraid without clear steps to reproduce the problem it's impossible to investigate, so closing. If you can identify a clear sequence of steps to follow that causes the problem, please file a new issue.

Have you not worked on an iPad? This happens all the time, no specific steps are required for this. Just work on the iPad for a few minutes and you will see the problems I described! Closing the report was an ugly gesture on your part!
