### ISSUE TITLE
3D Shape with Tiled Background Error On Right Face only

### ISSUE THREAD

**Issue by arcadesindo** [Scirra/Construct-3-bugs#5838]
## Problem description
When we try to use the tiled background as the face of the 3D Shape, it was all fine, until it just happened on the Right face. Not quite sure if it was the problem of Tiled Background or 3D Shape, but I think its from the Tiled BG?

## Attach a .c3p
[3dPlat_bugRightFace3Dshape.zip](https://github.com/Scirra/Construct-3-bugs/files/9016988/3dPlat_bugRightFace3Dshape.zip)

## Steps to reproduce

1. Attach Top, Left, Right, Bottom, Front, Back face
2. Try to resize the 3D Shape

## Observed result
![image](https://user-images.githubusercontent.com/28801633/176609016-9eb466ed-d592-48c9-9c4d-0e6e94ceae64.png)
![image](https://user-images.githubusercontent.com/28801633/176609083-af0b7234-b022-4c62-b2a8-77c135529b13.png)

## Expected result
The tiled of the Right Face should be symmetric as the Left Face have

## More details

**First affected release:** We've been trying this in r293.3 and also r300, but still has the same issue.

**Comment by AshleyScirra** [comment]
The attached project uses a third-party plugin (3D object). Please provide a project not using any third party addons as per the bug report guidelines.

**Comment by arcadesindo** [comment]
@AshleyScirra 
[3dPlat_bugRightFace3Dshape.zip](https://github.com/Scirra/Construct-3-bugs/files/9019592/3dPlat_bugRightFace3Dshape.zip)

**Comment by arcadesindo** [comment]
thanks ashley, but why the right face didn't going the same like the left one when resizing?
![3d shape](https://user-images.githubusercontent.com/28801633/176694997-081e2c42-c17c-4475-a80f-c4358eefff81.gif)

**Comment by AshleyScirra** [comment]
As I said, it's because texture mapping works in an anticlockwise order around the faces.
