### ISSUE TITLE
Timeline Play/Pause Icon

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5840]
## Problem description

At present, the icon used is not particularly suitable, it is a little small.
![Snipaste_2022-06-30_16-02-17](https://user-images.githubusercontent.com/45864744/176625438-e4b52e0a-48e8-4424-88c5-0f67ae67edcc.png)

i recommend using this icon instead
- Start all live previews
- Stop all live previews
![Snipaste_2022-06-30_16-04-13](https://user-images.githubusercontent.com/45864744/176625656-bc13b4ae-5049-42e2-863a-3e272128cf79.png)

Oh, right. Can  live previews button also be merged into 1 dynamic button?

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Changed for the next beta.
