### ISSUE TITLE
objects position incosistent when scaling window

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5842]
## Problem description

objects position incosistent when scaling the window and refreshing

## Attach a .c3p

[scalingIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/9019010/scalingIssue.zip)

## Steps to reproduce

1. go into play mode
2. change window size 
3. press F5

(alternatively going into or out of fullscreen mode with f11 causes issues as well)

## Observed result
![ezgif com-gif-maker (16)](https://user-images.githubusercontent.com/89512047/176659927-b9d2525a-c3aa-496f-aa14-2f241b96a0ab.gif)

The coin is at a different position before and after the refresh

## Expected result

Object is at the same position

_This probably is another one of the "not a bug", but still wanted to report it as this is causing some headache for me._

**Comment by AshleyScirra** [comment]
It's not a bug: you have "Scale outer" fullscreen mode, which extends the view depending on the aspect ratio of the window, combined with a small layout that has bounded scrolling. In that case the scroll bounding will interfere with scale outer mode. Tick "Unbounded scrolling" on the layout and it works like you want.
