### ISSUE TITLE
dragging condition into empty event wrong visualization 

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5843]
## Problem description
dragging a condition into an emtpy event or function shows the wrong visualization but still places it correctly.

## Attach a .c3p
[dragCondition .zip](https://github.com/Scirra/Construct-3-bugs/files/9019352/dragCondition.zip)

## Steps to reproduce
1.drag the condition over the function or an event without conditions
![ezgif com-gif-maker (17)](https://user-images.githubusercontent.com/89512047/176666507-0b974036-80ff-466a-ab29-186e9f000780.gif)

## Observed result

Visualization is wrong, but dropping positions correctly. 

## Expected result

Visualization matches where it's dropped

**Comment by AshleyScirra** [comment]
Fixed for next release cycle.
