### ISSUE TITLE
Crash - deleting a behaviour while previewed

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-3-bugs#5846]
## Problem description

Deleting a behaviour while it is being previewed crashes the editor, regardless of behaviour (tested on orbit, rotate, sine and fade). See gif:

![preview crash](https://user-images.githubusercontent.com/46861823/176796145-c23a5801-4b5b-4727-a8e5-90cf48b49078.gif)

Also note, deleting any behaviour while previewing will crash the editor, even if the behaviour is not associated with the preview.

## Attach a .c3p
[preview crashing.zip](https://github.com/Scirra/Construct-3-bugs/files/9024058/preview.crashing.zip)

## Steps to reproduce

1. preview any of the four Sprite behaviours
2. while in preview mode, delete the corresponding behaviour

## Observed result

Editor crashes

## Expected result

No crash

## System details

Chrome, stable

Win 10, Ryzen 3600, 6700xt

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r293-3/projectResources.js, line 841, col 295
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'tU')
Stack: TypeError: Cannot read properties of undefined (reading 'tU') at d.Lea (https://editor.construct.net/r293-3/projectResources.js:841:295) at WG.fm.Lea (https://editor.construct.net/r293-3/projectResources.js:833:471) at d.FZ (https://editor.construct.net/r293-3/projectResources.js:740:516) at d.agb (https://editor.construct.net/r293-3/projectResources.js:741:365) at d.Na (https://editor.construct.net/r293-3/projectResources.js:573:264) at https://editor.construct.net/r293-3/components/bars/propertiesBar/propertiesBar.js:135:304 at QW (https://editor.construct.net/r293-3/components/bars/propertiesBar/propertiesBar.js:46:13) at CCG.aa.hL (https://editor.construct.net/r293-3/components/bars/propertiesBar/propertiesBar.js:135:269) at https://editor.construct.net/r293-3/components/bars/propertiesBar/propertiesBar.js:23:323 at ih (https://editor.construct.net/r293-3/main.js:373:150)
Construct 3 version: r293.3
URL: https://editor.construct.net/
Date: Fri Jul 01 2022 09:39:31 GMT+1000 (Australian Eastern Standard Time)
Uptime: 124.4 s

Platform information
Browser: Edge
Browser version: 103.0.1264.37
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37
C3 release: r293.3 (stable)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon RX 6700 XT Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
This was fixed in beta r296. From that version the crash doesn't happen anymore.
