### ISSUE TITLE
game not load on ios 

### ISSUE THREAD

**Issue by vijayCoolboots** [Scirra/Construct-3-bugs#5847]
[Error] Refused to load blob:https://apps-364328528899530.apps.fbsbx.com/d65f076c-74c1-45e7-b728-5fcf5c99a586 because it does not appear in the script-src directive of the Content Security Policy.
[Error] NetworkError:  A network error occurred. (jobworker.js, line 8)
[Error] no handler for message type 'OpusDecode'
	OnDispatchWorkerMessage (jobworker.js:9:135)
[Error] Refused to load blob:https://apps-364328528899530.apps.fbsbx.com/d65f076c-74c1-45e7-b728-5fcf5c99a586 because it does not appear in the script-src directive of the Content Security Policy. (x2)
[Error] no handler for message type 'OpusDecode'
	OnDispatchWorkerMessage (jobworker.js:9:135)

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.
