### ISSUE TITLE
C3 does not respond to mouse clicks in iPad OS v15-16 (iPad Pro 12.9 M1)

### ISSUE THREAD

**Issue by arturbier** [Scirra/Construct-3-bugs#5849]
## Problem description

C3 stops responding to mouse clicks! I have added the steps that lead to the problem.

## Steps to reproduce

1. Open C3
2. Follow the steps from the video!
(the second video is a continuation of the first video!)

https://user-images.githubusercontent.com/78679486/176891086-7333c43a-9554-4cec-8f0c-18fa4946edfb.mp4

## Observed result

https://user-images.githubusercontent.com/78679486/176890867-e8e61be3-9c32-4dca-8c0d-357500057970.mp4

## Expected result

I want the mouse to work fully as well as on a PC! After all, this mouse is used by me on a Macbook where everything works fine!

## More details

This happens in any browser

This happens in any version of C3

**First affected release:** 

## System details

<details><summary>View details</summary>

IpadOS 15 , Ipad 12.9 M1

</details>

**Comment by AshleyScirra** [comment]
It seems to work fine for me with a bluetooth mouse on an iPad.

I tried copying what you did in the video; it worked fine for me, but it's difficult to follow as the video is doing some fairly random inputs in quick succession.

I suspect there is some specific action or sequence of actions that causes the problem, but without knowing what those specific actions are, unfortunately it is impossible to investigate the problem. This is why our bug report guidelines require a step-by-step list of instructions to follow to reproduce the problem: we need that to help you. I'm afraid there's still nothing we can do, but if you can find such a sequence of actions that reliably reproduces the problem, please do file a new issue.
