### ISSUE TITLE
Autocomplete not working (MacOS)

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#585]
## Problem description

Autocomplete is giving me lots of problem today. Adding random text when pressing, + - . or other symbol signs, after writing an object name. I'm not sure if this is only On MacOS. There also seem to be some problem with certain expressions and instance variables not showing up in dropdown.

Works as intended in R42.3

## Attach a .c3p

N/A

## Steps to reproduce

1. Create a new project
2. Add a sprite
3. Try edit expression fields.

## Observed result

Autocomplete not working as intended, adding random stuff on some symbol keypresses.

## Expected result

Broken since last time i tried. Should be working as usual.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
It's very difficult to do anything about bug reports this vague. I gave it a quick go on Windows and everything looked like it was working normally. Note it's intended that extra content is added to the expression field when trying some keypresses. For example if you type `Sprite.An`, and autocomplete has `Angle` highlighted, then you type `+`, it will autocomplete to `Sprite.Angle+`. Therefore sometimes adding extra characters as you type is intended.

To be able to investigate this further I'd need a comprehensive description of your precise keypresses, what characters you expected to be entered, and what characters you saw entered instead. (i.e. properly fill out the observed/expected result fields)

**Comment by jaydonteh** [comment]
I can confirm this. Was getting weird auto-completion when it is unnecessary.

Issue 1:
## Steps to reproduce
1. Go into any expression textbox within the add condition/event dialogue.
2. Type lerp and enter to auto-complete.
3. Then open bracket and type a number.

Result: After typing a number, the auto-complete dialogue is still present. Thus, rendering the enter key broken.

Issue 2:
## Steps to reproduce
1.  Create a Sprite and name it anything.
2. Go into any expression textbox within the add condition/event dialogue.
3. Type the object name (Example: player), make sure to auto-complete the name by enter key.
4. Then type a full-stop "." (Example: player.)
5. Lastly, type something like "x" (Example: player.X) and press enter.

Result: The enter key on step 5 has a broken auto-completion.

Two issues with reproduction but same problem appearing after a recent update.

**Comment by JeFawk** [comment]
I can confirm this too. I need to revert to 42.3 or something because autocomplete is not working at all and it's just hindering me instead.

For example I can't choose the Angle at all, or the bullet behaviour. I go through the list even and these things don't exist there.

![image](https://user-images.githubusercontent.com/7268697/27911509-f05b3824-6261-11e7-99fc-d47ac54a7cb1.png)

**Comment by tunepunk** [comment]
@AshleyScirra This seems to be a Mac issue. I didin't notice the same problem on windows. It says in the Title (MacOS) so I don't know why you tested on a windows machine.

**Comment by AshleyScirra** [comment]
OS-specific issues are pretty rare. I'm also pretty sure that this is to do with a bug in our code minifier at the moment.

**Comment by AshleyScirra** [comment]
OK, rolled back our minifier to the same version we used in r42.3 and that seems to have fixed it. r44 is out now, hopefully that works better!

**Comment by JeFawk** [comment]
It's working now, thanks.
