### ISSUE TITLE
Whitelist UnityAds3 4.2.1 cordova Plugin (Google Play Store SDK Compliance Policy Update)

### ISSUE THREAD

**Issue by artemisoftnian** [Scirra/Construct-3-bugs#5850]
Hi Ashley,

I just update my UnityAds3 plugin to 4.2.1 : com-artemisoftnian-plugins-unityads3@4.2.1
Please put me in the flow if can be whitelisted?

Thanks in advance as always!

**Comment by AshleyScirra** [comment]
Added com-artemisoftnian-plugins-unityads3@4.2.1 to build service.
