### ISSUE TITLE
Cmd+X (Cut) doesn't store cell value in Dictionary Editor

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#5851]
## Problem description

When using "Cut" (Cmd+X) on a cell in the Dictionary Editor, the value is removed, but not stored in the clipboard and cannot be pasted. Using "Copy" (Cmd+C) works, just not "Cut".

## Attach a .c3p

(Any new project with a dictionary will show the error)

## Steps to reproduce

1. Add a dictionary project file. 
2. Edit the dictionary file.
3. Set size to 4.
4. Type a string into Key 0.
5. Select Key 0 and press Cmd/Ctrl+X.
6. Select any other Key and press Cmd/Ctrl+V.

## Observed result

The string is not copied.

## Expected result

The string is copied.

## More details

Video for reference: https://drive.google.com/file/d/1H540LQV5JbPcjuFwzNe9KTLjPun5wX2H/view?usp=sharing

The first action tries to copy "Test0" and then paste it below; this works well. The second action tries to cut "Test1" and then paste it below; this is unsuccessful, as Test0 is pasted instead. 

**Affected browsers/platforms:** Mac 11.6.6 Chrome 103.0.5060.53 (Official Build) (x86_64)

**First affected release:** r300

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Can't reproduce this. It works as expected on Windows 10 and also works on OSX 12.4. Maybe it's an issue with older versions of OSX? Hard to tell.

**Comment by brushfe** [comment]
@DiegoScirra Strange! I'll upgrade my OS and see if it still occurs. Thank you!

**Comment by brushfe** [comment]
@DiegoScirra 

After the update to Monterey 12.4 (21F79), I'm still having the same problem in Chrome and Firefox. No browser plugins or extensions enabled. 

Using 'cmd+x' to cut a selected cell, then using "cmd+v" to paste that content doesn't paste the cut content into the cell. The cut command does seem to store the content, however—if I use "cmd+v" to paste into another application, the cut content appears properly. It seems like construct is pulling the wrong content from the clipboard. 

It gets weirder in Safari—when I highlight a cell in an array and press "cmd+c", "cmd+x", or "cmd+v", it doesn't register the "cmd" key. It just replaces the cell's contents with the letter "c", "x", or "v".

**Comment by DiegoScirra** [comment]
I am able to reproduce the Safari issue, no idea why it is happening though.

About the original issue, what hardware are you using? Is it a regular desktop/laptop or are you using an iPad with a keyboard attached? Maybe an unusual hardware setup is causing problems.

**Comment by brushfe** [comment]
Even stranger! I'm using a typical Macbook Pro, nothing modified or external keyboards or anything. Just laptop and external monitor. I just tried it again on th latest Firebox with no plug-ins and an empty cache. Copy/paste works, but cut/paste afterwards uses the copy data.

(If it's just me that's experiencing it, I don't want to take away from more pressing bugs—I can just use copy/paste!)

**Comment by XHXIAIEIN** [comment]
Is this checked?
![Snipaste_2022-08-09_12-36-26](https://user-images.githubusercontent.com/45864744/183565247-22321054-983a-42b6-b483-f7276798f75c.png)

**Comment by brushfe** [comment]
@XHXIAIEIN Good question, but yes it's checked. The Copy command works perfectly, it's just Cut that doesn't seem to store the text it captures onto the clipboard.

**Comment by AshleyScirra** [comment]
@brushfe - does it work correctly with the option unchecked?

That's a legacy option for when browsers had much less clipboard support - I'm actually inclined to remove the setting as it has caused confusion in clipboard-related issues like this several times in the past now.

**Comment by brushfe** [comment]
@AshleyScirra Great call — unchecking that option fixed the Cut problem! The problem only occurs when the in-app option is checked. Maybe another reason to remove it then! Thanks for your help!

**Comment by AshleyScirra** [comment]
I don't think we will take action if it only affects the "fake" (in-app) clipboard; I'd rather remove that. We'll probably remove it at some point in future.
