### ISSUE TITLE
Facebook Instant Game Bug Sound and Music

### ISSUE THREAD

**Issue by tuzke** [Scirra/Construct-3-bugs#5855]
## Problem description

The problem is that Facebook instant game IOS does not support the sound file of the Construct 3, so it cannot load the sound files. But if you uncheck "Preload sounds" the game will load and the game works without sound in the game, All construct 3 games currently on Facebook IG work without sound , or failed to load. @AshleyScirra Please consider if the issue is resolved. Thank you! I have attached a screenshot from the console:
[IMG1](https://i.imgur.com/sZUR0bH.jpg)
[IMG2](https://i.imgur.com/4IWV5Yg.png)

## Attach a .c3p

Any FB Instant Game project
Link some game:

[-Game1: Play on facebook](https://www.facebook.com/gaming/play/332294548926327)
[-Game2: Play on facebook](https://www.facebook.com/gaming/play/1131960057627833)
[-Game3: Play on facebook](https://www.facebook.com/gaming/play/661036458576043)

**Comment by AshleyScirra** [comment]
This looks the same as #5782 so marking duplicate.

**Comment by AshleyScirra** [comment]
(FWIW I have no idea why the preload sounds option would affect it - that only changes when sounds are loaded, not how they are loaded. I suspect the same problem will happen when you first try to play audio.)

**Comment by tuzke** [comment]
> (FWIW I have no idea why the preload sounds option would affect it - that only changes when sounds are loaded, not how they are loaded. I suspect the same problem will happen when you first try to play audio.)

If preloading the sound, it will wait for the sound to finish loading before starting the game, because it is having an error loading the sound, it will always stop at 100% without entering the game, if unchecked it will enter the game and no sound
