### ISSUE TITLE
Large project won't save

### ISSUE THREAD

**Issue by Tobye** [Scirra/Construct-3-bugs#5856]
## Problem description

When I try to save the project it will stall for a long time, then in approximately 9 out of 10 times it will crash the browser with a message saying 'out of memory'.  The task manager shows there is still memory space, but the CPU caps out while trying to save.

I have tried on 4 different browsers across 3 different computers, all with the same results.

It is a very big project, I have been working on it for years in my spare time.  Small projects still work fine.  It used to save fine (obviously), but now even older backup versions are refusing to save, even when I delete large chunks of the project.

## Attach a .c3p

https://drive.google.com/file/d/1mUiFc_MMQG-Ke2mLJ8aAW9Ld_qo6ODau/view?usp=sharing

## Steps to reproduce

1. Load the project
2. Try to save the project (in any way)

## Observed result

The editor will freeze up for a long time and eventually crash.

## Expected result

The game would save.

## More details

The problem has occurred in all browsers tested: Chrome, Edge, Yandex, Firefox, Android
On 3 laptops using Windows 10 and 11
And an Android phone.

**Affected browsers/platforms:**
The problem has occurred in all browsers tested: Chrome, Edge, Yandex, Firefox, Android
On 3 laptops using Windows 10 and 11
And an Android phone.

**First affected release:** 
It first occurred in Construct 3 version 300, but now also occurs in the stable release 293.3

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 103.0.0.0
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
C3 release: r293.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 42 gb
Storage usage (approx): 49 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by Tobye** [comment]
Thanks for your advice, your solution partially works - I can load and save the project after converting it to a folder project, it will only save by clicking the disk save icon, if I try to save by menu > save as > save as a project folder, it still crashes, either by the same memory issue as before or a new message from the C3 editor saying "Unable to save project.  Try checking you have permission to save in the chosen location.  Alternatively, try a saving a different way."

This means to make backup versions I will need to manually make copies of the project folder, but the main thing is that I can keep working so thank you for the solution :)

**Comment by AshleyScirra** [comment]
It sounds like there's a workaround and I'm not sure there's much more we can do about this anyway, so closing.
