### ISSUE TITLE
C2Runtime is mentioned in the Addon SDK manual

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-3-bugs#5857]
## Problem description

I found two references to legacy C2Runtime in the Addon SDK manual (which C3 is no longer supports).

## References

1. [GetRuntime() method](https://www.construct.net/en/make-games/manuals/addon-sdk/reference/model-interfaces/iproject#:~:text=the%20project%20name.-,GetRuntime(),-Return%20the%20runtime) [should be removed]

2. [Porting C2 addons](https://www.construct.net/en/make-games/manuals/addon-sdk/guide/porting-c2-addons#:~:text=You%20can%20directly%20copy%20the%20runtime.js%20from%20your%20Construct%202%20addon%20to%20c2runtime/runtime.js.%20Usually%20the%20runtime%20script%20does%20not%20require%20any%20modifications.) [I think this guide needs to be updated]

**Comment by AshleyScirra** [comment]
Thanks, updated both.
