### ISSUE TITLE
'3D' plugin category is not mentioned in the Addon SDK manual

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-3-bugs#5858]
## Problem description

Addon documentation says nothing about '3D' plugin category in [Configuring plugins](https://www.construct.net/en/make-games/manuals/addon-sdk/guide/configuring-plugins#:~:text=in%20addon.json.-,PLUGIN_CATEGORY,-The%20category%20for) manual entry.

## Observed result

**3D** plugin category is not mentioned.

## Expected result

**3D** plugin category should be mentioned.

## Additional question

Is it also possible to make your own addon categories in the future with names you choose, like it was available in C2? This would be really helpful to filter out certain developer addon kinds. For instance, a certain group/series of addons.

**Comment by AshleyScirra** [comment]
Added `"3d"` category to the docs.

> Is it also possible to make your own addon categories in the future with names you choose

Arbitrary names are not translatable, so we have to have a fixed list.

**Comment by GameSoul7Eugene** [comment]
> Arbitrary names are not translatable, so we have to have a fixed list.

What prevents you from using your own translated category name in the language file for the addon? I imagine it like this:

```
plugin/behavior.js
this._info.SetCategory(self.lang(".category"));
```

```
lang\en-US.json
"addon_id": {
	"name": "AddonName",
	"category": "AddonCategoryCustomName",
	"description": "AddonDescription",
	"help-url": "https://www.construct.net"
}
```
Anyway, I appreciate your work.

**Comment by AshleyScirra** [comment]
That won't appear for translators on POEditor. Only official terms get translated there.
