### ISSUE TITLE
[r43] Image Editor's text boxes in the  color palette don't work properly

### ISSUE THREAD

**Issue by josea122** [Scirra/Construct-3-bugs#586]
## Problem description

Trying to write an exact number in the color selector (either rgb or HSL) but the editor keeps changing it to a random number. One number up and down buttons doesn't work either.

## Steps to reproduce

1. Open any image in the image editor (for example, an sprite)
2. In the color palette, try changing one of the values (such as Red, Green or Blue)
3. Try also using the One number up and down

## Observed result

Values changes randomly until reaching rgb 0,0,0 (black)

## Expected result

The engine lets me write the exact value I want

## Affected browsers

* Chrome: yes

**Comment by josea122** [comment]
# Other Problems that I just found

- Using the select tool to copy a part of the image, then pasting it and moving it is buggy. The selection sometimes gets stuck when moving it with the mouse

-Clicking after making a line in the border of the image by using the line tool while pressing Shift will make the line disappear.

**Comment by DiegoScirra** [comment]
Fixed the color spinner in the Animations Editor. That will be available in the next release,  r44.

@josea122

I am closing this and opening a new issue for the second thing that you mentioned.

In the future don't be hesitate to create new issues for each different problem, even if it seems like a minor thing.
