### ISSUE TITLE
Gamepad "On any button" not triggering with multiple button presses

### ISSUE THREAD

**Issue by Jase0000** [Scirra/Construct-3-bugs#5860]
## Problem description
With the Gamepad plugin, if you use "On any button pressed" and press 2 Gamepad buttons at the exact same time, only 1 trigger will occur.

## Attach a .c3p
https://drive.google.com/file/d/11G2pBub4z2V_cUjlAKLl7-ypN2hCgETF/view?usp=sharing

## Steps to reproduce
1. Run attached project
2. Press two Gamepad buttons at the exact same time.
3. You should see two new lines appear in the "Input Log" with the Gamepad Button Indexes. If you timed it perfectly, you will see the bug where only one new line appears. You must press the two buttons at the EXACT same time.
4. If bug did not occur, press SPACEBAR to clear log and repeat step 1.

## Observed result

If two gamepad buttons are pressed at the exact same time, the log will not show two lines.

## Expected result

Each trigger gets fired for each button pressed, even if exactly the same time.

## More details
I checked Keyboard "On any key" trigger, but the bug is NOT present here, which is good!

Chrome 

R301

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r301 (beta)
Browser: Chrome 103.0.5060.66
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 1.3 gb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This may be a bit of an odd quirk, but is this actually important to an actual game? I'm not sure this would actually affect any real-world games, and I'd rather not invest time in fixing obscure quirks if they don't matter.

**Comment by brushfe** [comment]
FWIW, I'm building a 4-player action game that uses gamepads, and I'm wondering if this problem has been the source of some issues I've had in playtesting. All to say, I imagine multiplayer games like this using gamepads would be a good real-world example

**Comment by AshleyScirra** [comment]
But why would hitting two buttons at exactly the same time only triggering "On any button" once have any impact on the game?

In one sense it kind of seems reasonable that within the space of one frame, the answer to the question "was any button pressed?" is "yes", and so maybe triggering once kind of makes sense anyway?

**Comment by Jase0000** [comment]
Thanks for looking into this, Ashley.

I am making a rhythm game that I plan to support any controller (was testing a wii guitar hero funnily enough, works great ignoring this bug!). My game is long in development but I have only done keyboard code. I knew all along that I could essentially duplicate my keyboard code to gamepad. I have a system that logs all button presses, in order, into an array, so I use "on any key pressed" for this. So when I duplicated the code for gamepad, it works flawlessly as I expected, except for this 1 bug due to "on any button pressed", which does ruin the game as you frequently need multiple button presses at the same time (this is how I discovered the bug and reported it). E.g. When strumming guitar and pressing a fret, the strum and 2 frets, you might be pressing 3 buttons at a time. I don't plan to support just guitars, but any controller, which makes using button indexes important, rather than hard coding each possible button (which I guess might work as a last resort).

I do understand the niche aspect of this, and I understand the logic behind gamepads working via polling. Do you think there's any realistic workaround, even a new action so it doesn't break existing projects? I'd love to keep this same system I designed which works great on keyboards.

**Comment by AshleyScirra** [comment]
OK, I think I've come up with a way to solve this - internally it can actually work similarly to a looping condition, ensuring it repeats for multiple buttons if more than one is down that tick. I'm still a little wary of the backwards compatibility implication so the fix is in for the next release cycle (first beta release after the next stable release).

**Comment by Jase0000** [comment]
Greatly appreciated!! Thanks for all the hard work you and your team always put in!

**Comment by brushfe** [comment]
@AshleyScirra A huge thanks from me as well!
