### ISSUE TITLE
behavior Tween (self.Angle+360\720)

### ISSUE THREAD

**Issue by starkiJi** [Scirra/Construct-3-bugs#5862]
**Problem description**

I think **Tween behavior** has a bug. If I add 360 degrees to the angle of the sprite, then the sprite doesn't rotate around the axis. In another **LiteTween**  behavior it works and it's good. In the example, click on sprites.

**Attach a .c3p**

[https://drive.google.com/file/d/1mmEpvtG22-6cwXPxNgQxXgTWryzdQ_ov/view?usp=sharing](url)

**r293.3**

**Comment by AshleyScirra** [comment]
I can't open the project as it uses a third party addon LiteTween (please see the bug report guidelines). However I am assuming this is not a bug, as angles are cyclical, and so an angle + 360 degrees is the same angle.

**Comment by starkiJi** [comment]
@AshleyScirra Here's the behavior you want if you decide to take a look. Also, I can't add 720 degrees, the feeling that the behavior sees a maximum of 360 degrees and because of this the sprite cannot be rotated around its own axis, and in the **LiteTween** behavior you can - https://drive.google.com/file/d/17JPqIoEhWLtlObO0ssk1XQ8A1Z-09F5D/view?usp=sharing

**Comment by AshleyScirra** [comment]
Angles are cyclical so it is mathematically correct that angle + 360 is the same angle. If you want to force a rotation, you can treat angles linearly using a value tween.
