### ISSUE TITLE
Layout layer fx duplicate bug

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#5864]
If you use an effect in more than one layout layer it will give you warning when you try to remove the fx about having associated events, even if there are no events in that layout.
## Problem description

https://www.dropbox.com/s/dti0ly8gl2yrsu6/layoutfxdupebug.c3p?dl=0
## Steps to reproduce

1.Navigate to the second layout
2.Try to remove the layer fx
3.

## Observed result
A warning appears about having associated events even if there are no events for that layout.

## Expected result
The warning shouldn't pick up on irrelevant duplicate effects.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Event sheets can be re-used across multiple layouts, therefore making event sheet references to layers ambiguous. You can see this if you click "Find all references" on the message: it returns one reference as an ambiguous result with a question mark, as it can't resolve for certain whether that layer will be referenced by that event sheet. Analysing the tree of event sheet includes could eliminate some cases, but not all, so it still won't completely solve the problem; meanwhile that would involve writing pretty complex analysis code, and the side-effect is merely a warning message, so I don't think any further action is justified.
