### ISSUE TITLE
Load images bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5869]
## Problem description

I have two sprites. I want to load first the image from the first one and then from the second one. But without a delay, the images on the second sprite are not loaded.

## Attach a .c3p

[load_images_bug_r301b.zip](https://github.com/WilsonPercival/WilsonPercival/files/9078300/load_images_bug_r301b.zip)

## Steps to reproduce

1. Open and run the project.
2. Open the console.

## Observed result

![bug](https://user-images.githubusercontent.com/91274932/178128902-6eca8282-070a-479a-b68f-5d3eeddc7747.gif)

## Expected result

![expected](https://user-images.githubusercontent.com/91274932/178128905-03a92a63-d143-4121-be14-cb1531c31201.gif)

## More details

If you enable the disabled action `Wait for previous actions`, then everything will work.

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r301b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r301 (beta)
Browser: Chrome 103.0.5060.114
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 346 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
These events aren't useful - you may as well load both sets of images at the same time (two "load" actions in sequence), which will allow them to load in parallel and work faster than loading them sequentially as your events do. However the fix is straightforward, so it's fixed for the next release cycle.

**Comment by WilsonPercival** [comment]
> Member

Yes, I know. But I need to load them sequentially. To speed up the loading of the game, I load the necessary resources first. While the player is thinking - I load the next part of the sprites.

**Comment by AshleyScirra** [comment]
The bug only happens if you load more content in "On image loading complete", and in that case, it is always better to load both sets of images simultaneously.

**Comment by WilsonPercival** [comment]
> The bug only happens if you load more content in "On image loading complete", and in that case, it is always better to load both sets of images simultaneously.

But this will increase the loading time of the game, because before the download is complete, I can not play the game.

**Comment by AshleyScirra** [comment]
I think you are confused about what the actions do. They manage which images are loaded in to memory. They do not manage which images are downloaded.

**Comment by WilsonPercival** [comment]
> I think you are confused about what the actions do. They manage which images are loaded in to memory. They do not manage which images are downloaded.

I know. I mean, I want to reduce game loading time. I made a demo and drew a diagram.

https://www.dropbox.com/s/fo319vwh3np20xa/test_load_images.c3p?dl=1

![load images speed wilson vs ashley new](https://user-images.githubusercontent.com/91274932/178667162-b2926fdd-fb64-47c2-9f83-542512f8074a.png)

**Comment by AshleyScirra** [comment]
I assumed you would change layout after loading pack1 images, so that layout's content is now ready for immediate use. Then once on the next layout, you'd start loading pack2 images for the first level that is chosen. (In fact you might want to load different sets of images depending on the level chosen.) I'm not sure why you would need to explicitly load pack1 images for the menu; if the user is just going to be looking at a blank screen, then Construct will automatically load that layout's images when the layout starts, without you having to make an action to load them.

**Comment by WilsonPercival** [comment]
> I assumed you would change layout after loading pack1 images, so that layout's content is now ready for immediate use. Then once on the next layout, you'd start loading pack2 images for the first level that is chosen. (In fact you might want to load different sets of images depending on the level chosen.) I'm not sure why you would need to explicitly load pack1 images for the menu; if the user is just going to be looking at a blank screen, then Construct will automatically load that layout's images when the layout starts, without you having to make an action to load them.

I don't use multiple layouts because I find it inconvenient. I do everything on the same layout.
