### ISSUE TITLE
Timeline bar scrolls to top when the current time marker gets dragged to 0

### ISSUE THREAD

**Issue by birbdoy** [Scirra/Construct-3-bugs#5870]
## Problem description
Whenever the current time marker in the timeline bar gets dragged from somewhere >0 to 0, the timeline bar scrolling jumps to the top.

## Attach a .c3p
[timelineBug.zip](https://github.com/Scirra/Construct-3-bugs/files/9079123/timelineBug.zip)

## Steps to reproduce
1. Drag the current time marker anywhere >0
2. Scroll to the bottom of the timeline bar
3. Drag the current time marker back to 0

## Observed result
The timeline bar scrolling jumps to the top.

## Expected result
There should be no change to the current scroll position.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next stable.
