### ISSUE TITLE
Crash in Android using 9-patch

### ISSUE THREAD

**Issue by easyDoesItOK** [Scirra/Construct-3-bugs#5872]
## Problem description

Took me many weeks to find the cause of this bug as it happens infrequently but narrowed it down to this. I have created a stripped down file of a larger one. Crashes on layout start, when using a 9-patch on Android exported using Cordova Android v10.

## Attach a .c3p

[220711 testSpeechBubbleBug.android.debug.zip](https://github.com/Scirra/Construct-3-bugs/files/9080830/220711.testSpeechBubbleBug.android.debug.zip)
[buSpeechBubble.zip](https://github.com/Scirra/Construct-3-bugs/files/9083527/buSpeechBubble.zip)

## Steps to reproduce

1. press the buttons to skip between 2 layouts back and forth.
2. eventually at some point (seems to be random) it will crash when the layout with the 9-path 'peopleTalkBubble' is shown.
3. In some cases just crashes after a few clicks, on others need to press 30 odd times....

## Observed result

Crashes the app on Android. Crash not apparent in preview mode on PC.

## Expected result

no crash

## More details

**Affected browsers/platforms:** 

Android v10

r293.3. has been crashing infrequently for some time but not sure what release it started.... took me a long time to find out what was crashing my game.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please provide a Construct project (.c3p) as per the bug report guidelines - you've only attached an APK.

When you say it crashes, is an error message displayed or logged to the console, or does the app just quit? I'm afraid if it's just the app quitting, normally that's a sign that Android itself has crashed rather than Construct. (Mistakes in Construct's code will freeze the app and log a message to the console.) Usually such app crashes are graphics driver errors, which unfortunately there is little we can do about.

**Comment by easyDoesItOK** [comment]
Sorry Ashley, cp3 attached now.

There's not much code in the project file, seems to be something with the format/display of the 9-patch on Android.

**Comment by easyDoesItOK** [comment]
Just tried the usb debugger again now. Can't see an error, it just loses connection as app closes when crashed.

**Comment by AshleyScirra** [comment]
I built a debug APK and tried loading the 9-patch layout around 100 times, including going as quickly as I possibly could, on an Asus Zenfone 8. It worked fine.

I'm afraid I suspect this is a device-specific graphics driver crash, which is what these types of issues tend to come down to. That is beyond our control - ultimately it's the graphics chip maker's responsibility, but contacting them is likely to be hopeless. Your best bet is to report the issue to Google and see if they can work around it. You could also try ensuring any available app/system software updates are installed, on the off chance an update fixes the problem.
