### ISSUE TITLE
Quick manual fixes

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-3-bugs#5876]
## Problem description

Minor manual errors that need to be fixed. They are quick fixes in my opinion, therefore I submitted them into one issue.

## Errors

1. Solid behavior
[Are you sure about that?](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/solid#:~:text=The%20Solid%20behavior%20has%20no%20properties%2C%20conditions%2C%20actions%20or%20expressions%20apart%20from%20the%20its%20enabled%20option.) Solid behavior now has some properties, conditions and actions.
[Initial state](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/solid#:~:text=Solid%20properties-,Initial%20state,-Set%20whether%20the) property should be renamed to _Enabled_

2. Car behavior scripting interface ([Link](https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/behavior-interfaces/car))
_turnWhileStopped_ method is not documented

3. Orbit behavior
[Reset total rotation](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/orbit#:~:text=layout%20co%2Dordinates.-,Reset%20total%20rotation,-Sets%20the%20counters) action looks different than others (style issue).

4. Platform behavior ([Link](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/platform))
**Set ceiling collision** action is not documented

5. Tile Movement behavior ([Link](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/tile-movement))
**Set default controls** action is not documented

6. Tile Movement behavior scripting interface ([Link](https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/behavior-interfaces/tile-movement))
On this manual entry page, it is spelled out as **behaviour** everywhere. In other manual entry pages, nevertheless, that talk about behavior scripting interfaces, it is referred to as **behavior**.

7. Object instances ([Link](https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/objects/instances))
This manual entry doesn't say anything about _Templates_. However, this is one of the common instance properties, though.

8. Project properties
[Runtime](https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/projects#:~:text=Advanced-,Runtime,-Switch%20between%20the) property should be removed
_Cordova Android scheme_ property is not documented

**Comment by AshleyScirra** [comment]
Thanks for spotting these. I've updated the manual for all these cases.
