### ISSUE TITLE
'Enabled' property missing for some behaviors (debugger)

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-3-bugs#5877]
## Problem description

**Enabled** property is missing for the following behaviors in the debugger. It need to be fixed:
[Anchor](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/anchor)
[ScrollTo](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/scroll-to)
[Tween](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/tween)

## Observed result

![observed](https://user-images.githubusercontent.com/59319082/178729674-22080723-b2b6-4145-ad22-37a5c2c6120e.png)

## Expected result

![expected](https://user-images.githubusercontent.com/59319082/178729766-7468ec8e-514e-4392-a4af-bcde2fb4ffef.png)

## More details

**First affected release:** r302

## Additional missing debugger properties

**Tags** for [Solid](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/solid)
**Axes** for [DragDrop](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/drag-drop)

**Comment by AshleyScirra** [comment]
Added missing debugger properties for the next beta.
