### ISSUE TITLE
Popout window doesn't style properly

### ISSUE THREAD

**Issue by TomGullen** [Scirra/Construct-3-bugs#588]
## Problem description

Dragging a pop out window always opens the popup window with the default theme - not the current theme loaded in C3.

## Steps to reproduce

1. Open Construct 3 with dark theme selected
2. Open Kiwi's Adventure
3. Drag a window (EG properties window) outside of the browser

## Observed result

Pop out window that opens has default theme applied

## Expected result

Pop out window should have dark theme applied

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Should be fixed for r52
