### ISSUE TITLE
Editor crash when pasting layout

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5880]
Here is a repro project for my earlier issue #5878 
But this time the editor crashes immediately when pasting the layout.
This happens when pasting objects which are members of a family in the source project, and that family doesn't exist in the target project.

## Attach a .c3p

https://www.dropbox.com/s/8e5cj2cm0jv9h79/A.c3p?dl=0

## Steps to reproduce

1. Create a new empty project and add a new sprite with the default name "Sprite" to it.
2. Open my project, copy the entire layout A and try to paste it into your new project

## Observed result

Editor crashes.

## More details

**Affected browsers/platforms:** Chrome

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r302/main.js, line 986, col 65
Message: Uncaught Error: missing instance variable value
Stack: Error: missing instance variable value at d.GN (https://editor.construct.net/r302/projectResources.js:562:419) at Ubb (https://editor.construct.net/r302/components/bars/propertiesBar/propertiesBar.js:46:141) at https://editor.construct.net/r302/components/bars/propertiesBar/propertiesBar.js:20:498 at gh (https://editor.construct.net/r302/main.js:372:150) at CCG.Yg.g.J.ydb.Jt (https://editor.construct.net/r302/main.js:1367:346) at new CCG.Yg.g.J.ydb (https://editor.construct.net/r302/main.js:1367:295) at xa.j (https://editor.construct.net/r302/main.js:986:44) at xq.g.J.sZ.Wd (https://editor.construct.net/r302/main.js:1416:74) at Xbb (https://editor.construct.net/r302/components/bars/propertiesBar/propertiesBar.js:20:480) at CCG.ba.OR (https://editor.construct.net/r302/components/bars/propertiesBar/propertiesBar.js:137:123)
Construct version: r302
URL: https://editor.construct.net/
Date: Thu Jul 14 2022 21:06:50 GMT+1000 (Australian Eastern Standard Time)
Uptime: 228.3 s

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.114
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in next beta.
