### ISSUE TITLE
old stable release r293.3 not available anymore

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#5881]
## Problem description
the old stable release r293.3 is not available anymore

## Steps to reproduce

1.try to open https://editor.construct.net/r293-3/
2.
3.

## Observed result

link doesnt work
## Expected result

should open the old stable 
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's working fine for me. Check your Internet connection is working.

**Comment by bubbblebub** [comment]
great, its there again :)
