### ISSUE TITLE
Can't add new keyframes in the timeline editor (same issue in every project)

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-3-bugs#5883]
## Problem description

I cannot add keyframes. It doesn't work by clicking in the animations editor and the keyboard shortcut does not work either. I am facing this issue since the new Construct release that just dropped, before that, it worked flawlessly.

## Attach a .c3p

As it's the same problem for me in every project, I don't think this is necessary 

## Steps to reproduce

1. Open the timeline editor
2. Try to add a keyframe by clicking on the "+" button or by doing the keyboard shortcut

Here is a video: 

https://user-images.githubusercontent.com/80539587/179251751-1390806d-8cd6-4a21-8782-d581968f457a.mp4

## Observed result

I don't see a new keyframe and it doesn't exist. Even when I reopen the project, no keyframe is visible. 

## Expected result

A keyframe should be created.

## More details
It doesn't work for me on my device using chromium and it's the same on my macbook using chrome. I'm using a 1440p display on both devices so mabye that causes the issue? Not sure. 

Windows, Mac OS (Construct 3 takes ages to load on my phone so I'm not testing that)

It stopped working in the stable release r302.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: webapp
Operating system: undefined (unknown)
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 106 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11-31.0.12001.2008)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Keyframes are not added because timeline editing mode is not turned on. Before it was allowed as an oversight. It didn't seem like a very useful behaviour because the added keyframes forcefully need to be edited with useful values later on and to do that you most likely need to turn editing mode on.

May I ask what was your workflow? Maybe it's a behaviour that needs to be re-introduced.

**Comment by therealPaulPlay** [comment]
Thanks for the response, that makes sense. Now what I do is, I switch the timelines to have absolute values, then I enter the values I want in the keyframe inspector and then when I'm finished I switch it back to relative/default so I can use it with differently sized objects. That was pretty quick for me. So I was just curious to see if it work with the edit mode enabled and it does, but when I try to delete the keyframe this happenes (I mean the black point, not exactly the keyframe.) 
![grafik](https://user-images.githubusercontent.com/80539587/179350854-47a63a81-b349-4d00-be67-566c7466ba6c.png)

-> It crashes every time I delete this black dot in edit mode, which makes it very tedious to remove keyframes when I've got many properties..... 

Here is the crash data:

 Error report information
Type: unhandled exception
File: https://editor.construct.net/r302/components/bars/timelineBar/timelineBar.js, line 224, col 326
Message: Uncaught TypeError: Cannot read property 'Tw' of null
Stack: TypeError: Cannot read property 'Tw' of null at d.Y2.lrc (https://editor.construct.net/r302/components/bars/timelineBar/timelineBar.js:224:326) at d. (https://editor.construct.net/r302/components/bars/timelineBar/timelineBar.js:219:51) at h (https://editor.construct.net/r302/components/bars/timelineBar/timelineBar.js:222:320) at d.Y2.Iqc (https://editor.construct.net/r302/components/bars/timelineBar/timelineBar.js:222:409) at d.Y2.Td (https://editor.construct.net/r302/components/bars/timelineBar/timelineBar.js:223:336) at HTMLDocument. (https://editor.construct.net/r302/components/bars/timelineBar/timelineBar.js:218:55)
Construct version: r302
URL: https://editor.construct.net/
Date: Sat Jul 16 2022 12:21:24 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 55.9 s

Platform information
Product: Construct 3 r302 (stable)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: webapp
Operating system: undefined (unknown)
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11-31.0.12001.2008)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by therealPaulPlay** [comment]
Quick edit here: I cannot remove any keyframes at all anymore, not just the black dots. 
![grafik](https://user-images.githubusercontent.com/80539587/179351131-ec0feefc-9cb4-4d24-9cb2-67e280f10bd9.png)

**Comment by therealPaulPlay** [comment]
I've installed it as an app in chromium for windows if that's still relevant... Thanks for looking into the issue!

**Comment by DiegoScirra** [comment]
The crash will be fixed in the next beta.
