### ISSUE TITLE
Scale outer fullscreen bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5886]
## Problem description

What I'm talking about is very similar to these reports:

https://github.com/Scirra/Construct-3-bugs/issues/5884

https://github.com/Scirra/Construct-3-bugs/issues/5790

When I switch from windowed to fullscreen, part of the image is cut off. If I reload the page while in full screen mode, the page will display normally after the refresh.

## Attach a .c3p

[scale_outer_fullscreen_bug.zip](https://github.com/WilsonPercival/WilsonPercival/files/9125070/scale_outer_fullscreen_bug.zip)

## Steps to reproduce

1. Open and run the project.
2. Switch to full screen mode.

## Observed result

Window:

![a1](https://user-images.githubusercontent.com/91274932/179337549-6224a82c-2c1c-465d-b311-ca58c7fdc669.png)

Fullscreen:

![a2](https://user-images.githubusercontent.com/91274932/179337500-577bd824-d70e-441f-8ae1-6fa09f10a9c5.png)

## Expected result

Window:

![a1](https://user-images.githubusercontent.com/91274932/179337549-6224a82c-2c1c-465d-b311-ca58c7fdc669.png)

Fullscreen:

![a3](https://user-images.githubusercontent.com/91274932/179337503-aaf70110-6835-40c2-b3ac-45270c744d8a.png)

## More details

720x1280, Scale outer.

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r302s

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.114
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 272 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think this is the same mistake as in #5884. You have a 2x2 layout and bounded scrolling enabled. This puts impossible constraints on the engine: to handle the fullscreen mode it must scroll, but scrolling is effectively disabled. Use 'Unbounded scrolling' for such cases.

**Comment by Bbms98** [comment]
Bonjour, j'ai exactement le même problème qui se produit sur Safari. J'ai déjà fait plusieurs tests avec un défilement fixé et non fixé et cela se produit malgré tout... Ce bug ne se produit que sur Safari.
