### ISSUE TITLE
Construct doesn't open when opening an associated file (.c3p)

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#5888]
## Problem description

When I try to doubleclick a .c3p associated with Construct, it first shows this popup.
![ok](https://user-images.githubusercontent.com/31101309/179350542-6c1f13f6-c663-42df-93d0-0ff6b11a5614.PNG)
Clicking OK closes and instantly reopens the same popup, nothing else happens. Having Construct open already also doesn't work.

## Attach a .c3p

🌵 

## Steps to reproduce

1. Doubleclick .c3p file

## Observed result

Nothing happens

## Expected result

Construct opens the file

## More details

**Affected browsers/platforms:** 
Windows/Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.114
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 1.2 gb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This doesn't happen for me - after installing I see the prompt below, which is the expected one. Perhaps you had something else associated with .c3p files (e.g. the old NW.js app)? Does uninstalling and reinstalling C3 as an app help? I'm not sure there's much we could do about this anyway, it's handled between Chrome and Windows.

![image](https://user-images.githubusercontent.com/768723/179506777-9f6edc42-8b04-4915-b7d5-7fad5f2bb825.png)

**Comment by Wackytoaster** [comment]
Yeah, reinstalling did the trick. It asked me the same thing but now showed another Construct 3 (denoted as new) that I could select. I never used the NWjs app. I'm unsure how I ended up in this state though. Anyway, the classic reinstall works so I guess there isn't anything to fix. Only thing is now the file doesn't show the C3 icon anymore and looks a little bit sad.
![sad](https://user-images.githubusercontent.com/31101309/179517717-67a79d47-0bec-4144-8a0e-c2e33429ed6e.PNG)
