### ISSUE TITLE
Ctrl+S overwrites autosaves (?)

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#5889]
## Problem description

I have Ctrl+S embedded deeply in my brain, so I'm constantly saving. I noticed that if you happen to press Ctrl+S at just the right time, this popup will show. I assume this happens when at the same time Construct is also saving an autosave. I'm saving in Google Drive, not sure if it happens otherwise.

![savebug](https://user-images.githubusercontent.com/31101309/179350707-61ed73b2-d83f-4537-ae30-eb5d3aa83b25.PNG)

## Attach a .c3p

🐤 

## Steps to reproduce

1. Press Ctrl+S (at the same time an autosave is made)

## Observed result

This popup, that sounds kinda threatening and confusing as to what actually happens if I click ok.

## Expected result

Not sure what the expected behavior would be, but I guess not having regular saves and autosaves interfere would be a good start.

## More details

**Affected browsers/platforms:** 
Windows/Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.114
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 1.2 gb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I was able to reproduce this by artificially making an autosave slow. During the autosave, manually saving shows that message. Projects can only be saved to one location at a time, so I've changed it for the next beta to show a different message that just tells you to wait for the autosave to finish before saving, which avoids the confusing "this project is an autosave" message.
