### ISSUE TITLE
MobileAdvert Interstitial Ads Fail To Load

### ISSUE THREAD

**Issue by am-brick** [Scirra/Construct-3-bugs#5891]
## Problem description

I am using the MobileAdvert plugin in my C3 project. On Android device, sometimes interstitial ads are not shown because of an error or the action "Create Interstitial Ad" does not fire. The error that is shown in the console is: Rejection from 'advert' handler 'ShowInterstitialAdvert': interstitial ad failed to show

## Attach a .c3p

[AndroidInterstitialAdBug.zip](https://github.com/Scirra/Construct-3-bugs/files/9126542/AndroidInterstitialAdBug.zip)
I've attached a .c3p file with the same code as my app that reproduces the same problems.

## Steps to reproduce

1. Run the project file
2. Tap on the button labeled "Show Ad" that triggers the "Create Interstitial Ad" action

## Observed result

Either nothing happens (no errors are thrown and the console is empty) or an error is returned in the console: Rejection from 'advert' handler 'ShowInterstitialAdvert': interstitial ad failed to show

Sometimes an ad is successfully shown but it is rare and it never showed an ad in the final signed release apk.

## Expected result

I expected an interstitial ad to show everytime.

## More details

I am using Microsoft Edge Version 103.0.1264.62 (Official build) (64-bit).

I am using Construct3 release r302 stable version.

The issue was not present in Construct3 version r285 stable.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Edge 103.0.1264.62
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62
Language setting: en-US

Local storage
Storage quota (approx): 1.1 tb
Storage usage (approx): 303 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Is "On interstitial failed to load" triggering?

If so that may be the normal and expected behavior. If there is a problem like an interruption in Internet connectivity, or a problem with AdMob's ad service, then it is expected that loading the ad will fail, that trigger will fire, and then your project will have to do something to handle that. In that case it's not a bug; it's a kind of failure your project needs to handle. If the problem is with AdMob's service failing to serve ads then you'll need to contact them for support.

Also it's worth double-checking you have configured everything correctly, as the configuration is quite complex and misconfiguration is often the cause of problems. As far as we know it's working for everyone else, which suggests a misconfiguration in your particular setup.

**Comment by fredriksthlm** [comment]
Just a hint: If you preview a project the ads you see (and error messages) is coming from Adsense (web ads) and not related to Admob, at all. Admob can only be tested when exported as apk.

**Comment by am-brick** [comment]
There were some family policy settings that I have changed on AdMob console. I also have the Tag For Child Directed Treatment action added. Will see in a few hours if ads work.

**Comment by am-brick** [comment]
> Just a hint: If you preview a project the ads you see (and error messages) is coming from Adsense (web ads) and not related to Admob, at all. Admob can only be tested when exported as apk.

This is not the issue. I tested on mobile device using compiled debug APK.

**Comment by DiegoScirra** [comment]
Is this your first project using ads?

If it is, there might be missing details in your account that need to be completed. Admob is not helpful at all when it comes to telling you if there is a problem with your account.

Here is a checklist of things to complete in your account.

[Have you tried ](https://support.google.com/admob/thread/146201559/how-can-i-fix-failed-to-load-3-error-test-ads-also-does-not-appear?hl=en)

**Comment by am-brick** [comment]
The ads work using unsigned apk on my android phone. Specifically, kids ads are actually showing. But when I build a signed apk for release and upload that one to google play store, the ads never show. There is a difference because of the apk that causes the ads to stop showing. I have checked all of the things necessary for kids ads and I'm not sure what to do at this point.

**Comment by am-brick** [comment]
Just tested ads are working with family policy stuff

**Comment by DiegoScirra** [comment]
I think the plugin already supports everything, that's being able to set **"max ad content rating"**, **"tag for child directed treatment"** and **"tag for under age of consent"** flags.

https://support.google.com/admob/answer/6223431?hl=en-GB#:~:text=Apps%20for%20children&text=Once%20your%20app%20is%20in,of%20the%20broader%20ad%20pool.

**Comment by am-brick** [comment]
I added the other two flags and it is working now. Thanks.
