### ISSUE TITLE
Cannot Open Project

### ISSUE THREAD

**Issue by fingerskier** [Scirra/Construct-3-bugs#5893]
## Problem description

Cannot open my project in, or access it from, Construct in _any_ recent version.  Getting the following message and error:

`In some circumstances, previous versions of Construct allow invalid expressions..etc.`

Then:

```
Settings, event 50, condition 1: Invalid parameter: 'tokencount' parameter 0 does not take 'number'

Settings, event 50, action 1: Invalid parameter: 'tokenat' parameter 0 does not take 'number'
```

**I was actively working on this project yesterday in v302 and today it is inaccessible.**

When running an older version (v293 & v285) I get this error:

This project cannot be opened since it was saved in a newer version of Construct 3...

## Steps to reproduce

When trying to open my project I get the aforementioned error and message.  
Older versions refuse to open the project.

## Observed result

Project won't open and, after downgrading, isn't accessible at all from Construct.

## Expected result

I expect the project to open and be accessible from within Construct.

## More details

Windows, Construct v302

**Affected browsers/platforms:** Tried Chrome and Brave on Windows

...tried installing and using v293 and v285

**First affected release:** v302

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.114
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 1.1 tb
Storage usage (approx): 109 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help unless you follow the bug report guidelines. No project has been attached so there's nothing I can do.

**Comment by AshleyScirra** [comment]
If you can't share a project, I'm afraid it's impossible to help. It leaves me only with telepathy, and that is notoriously unreliable for problem solving. I would advise restoring a backup.
