### ISSUE TITLE
HTML5 Crash

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#5894]
## Problem description

When I export my game as HTML5, it will not load, instead displaying an error message:

`c3runtime.js:1636 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'IsInContainer')
    at Layout._CreateAndLinkContainerInstances (c3runtime.js:1636:210)
    at Layout._StartRunning (c3runtime.js:1630:446)
    at C3Runtime.Start (c3runtime.js:3235:417)
    at async C3Runtime.Init (c3runtime.js:3220:161)
    at async InitRuntime (workermain.js:8:1)`
    
This has only been an issue since the latest stable release, and appears to only be connected to objects I have worked on since. I have removed every single eventsheet, and the problem still occurs.

I can export it as a windows program, or an NW.js without issue. It only crashes when exporting as HTML5.

## Attach a .c3p

[AnD4DGlitch.zip](https://github.com/Scirra/Construct-3-bugs/files/9134058/AnD4DGlitch.zip)

## Steps to reproduce

1. Export to html5.
2. Upload to web server.
3. Try to play game.
4. Press F12 to note the error, as mentioned above.
5. Delete one of the objects in Construct 3.
6. Repeat the other steps.
7. Note that it now works.

## Observed result

The game crashes to a black screen, displaying an error message in the console.

## Expected result

The game should load.

## More details

I've been exporting this game on an almost daily basis for the past 2 months without issue. I have only exported once since the new update, and immediately had the crashed.

All of the events have been removed, and the problem remained.

When I moved "BuilderFontPixel" from the DUMP layout to the BUILDER layout, the crash doesn't occur. The same happens if I remove any of the objects from the game.

Crashes in Chrome, Firefox and Edge.

Worked in r293.3 But doesn't work in r302.

## System details

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.114
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 268 gb
Storage usage (approx): 664 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
I did a web export and hosted it on a local web server, and it worked fine.

Are you sure it's not a problem with your server? Perhaps it cached some old files from a previous upload and your new upload mixed new and old files, causing project corruption.

**Comment by 4demon** [comment]
"Are you sure it's not a problem with your server?"

I'm certain, I've tried it with multiple servers, as well as tried to access it with multiple computers on different networks.

I just tried it again and got another black screen.

What happens if you try to access:

https://challacc.net/builder3/

**Comment by AshleyScirra** [comment]
I see the error there, but then why would the export work on my own web server? It points to a problem with your web server. For example perhaps it has cached some old files on the server side, and it is serving a mixed version that is broken. Does it work if you upload it to a different URL?

**Comment by 4demon** [comment]
No idea... maybe the save file I produced is glitched. However, when I try loading the save file and exporting the game from there, I still get the error. Even if I put it on a different server and a new folder.

Same error here:

https://challacc.com/ashley/

https://challacc.com/ashley2/

Are you definitely testing it on the latest stable version?

**Comment by 4demon** [comment]
I updated to the beta you just posted, and the html5 version now works, albiet after a second refresh.

I note the export system changed slightly, but don't know if that made a difference or not.

I exported on the stable version again, and it failed again... so the current direction/changes appear to be working for me :)

**Comment by AshleyScirra** [comment]
My own exports using both r302 and r303 work fine.

I'm afraid there's nothing that I can do unless I can reproduce the problem. My best guess is your server is misconfigured or somehow corrupting the files. Please file a new issue if you can find a better way to reproduce.

**Comment by 4demon** [comment]
@AshleyScirra Just as an update to this, I managed to resolve it.

Turns out I had the loader layout set as the game. I replaced this with a simple progress bar, and it now loads every time.

I have a feeling it was trying to set up containers before the game had properly loaded. Only thing I can think of.

**Comment by kingpirux** [comment]
Same issue here. The problem is with the loading screen, if there are several objects it has like issues caching the required images and events and this happens, this is all what i could see.

**Comment by san40511** [comment]
I also have the same issue. Does anybody know how to fix it?
