### ISSUE TITLE
[R17] Mobile - Crash on "Log Out"

### ISSUE THREAD

**Issue by el3um4s** [Scirra/Construct-3-bugs#59]
## Problem description

C3 crash when touch "Log out" and I'm offline.

## Attach a .c3p

.

## Steps to reproduce

1. Touch the avatar on the top right
2. Touch "Log Out"

## Observed result

I see a crash report dialog
## Expected result

Log Out

## Affected browsers

* Chrome: yes
* Firefox: I don't know
* Edge: I don't know
* Safari: I don't know

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r17/main.js, line 153, col 3024
Message: Uncaught TypeError: re is not a function
Stack: TypeError: re is not a function at ǃE.ǃv.ǃP.ǃaMz.ǃWI (https://editor.construct.net/r17/main.js:153:3024) at window.ǃsw.ǃWI (https://editor.construct.net/r17/components/misc/userAccount/userAccount.js:1:2338) at t.ǃEz (https://editor.construct.net/r17/components/misc/userAccount/userAccount.js:1:1532)
Construct 3 version: r17
URL: https://editor.construct.net/index.html
Date: Tue Apr 11 2017 19:05:01 GMT+0200 (CEST)
Uptime: 20.5 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.132
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Android
Operating system version: 6.0.1
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 3
Logical CPU cores: 6
User agent: Mozilla/5.0 (Linux; Android 6.0.1; Redmi Note 3 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.132 Mobile Safari/537.36

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: Qualcomm
Renderer: Adreno (TM) 510
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_disjoint_timer_query, EXT_sRGB, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_atc, WEBKIT_WEBGL_compressed_texture_atc, WEBGL_compressed_texture_etc1, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r18.
