### ISSUE TITLE
Implement dragging objects to unlocked layers

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#590]
Ref: https://www.scirra.com/forum/viewtopic.php?f=191&t=193656

Currently, you can't drag an instance from a layout to the layers bar, like you could in C2. This should be implemented for C3.

Secondly in C2, if you lock a layer, you can still drag instances on to it, and paste instances on it. There doesn't seem to be a good reason for this to be supported, since you can't interact with anything you add to a locked layer. If it's done by accident it can be annoying (see thread).

These actions should probably be blocked instead. This could also apply to hidden layers.

**Comment by alastajj** [comment]
Also you can't drag sprites from the layout editor on to a different layer in C3, like you could in C2? If you move your mouse over the Layers toolbar it doesn't do anything, it just moves the sprites to a new position rather than changing layer.

**Comment by AshleyScirra** [comment]
@alastajj - I'll look in to that as well.

**Comment by AshleyScirra** [comment]
#1016 was filed pointing out again that layout -> layer dragging doesn't work. Updated title and description and bumping priority.

**Comment by AshleyScirra** [comment]
Finally got round to doing this. Should be supported in r78.
