### ISSUE TITLE
WorldInfo sceneGraph maps not cleaned 

### ISSUE THREAD

**Issue by ratalaika** [Scirra/Construct-3-bugs#5900]
## Problem description
Stuff not been cleaned from sceneGraphExportDataMap and sceneGraphZIndexMap on WorldInfo class.
Due to JS doesn't use pointers as WeakMap ids it is fine code wise but just fills the memory with garbage slowly.

## Steps to reproduce
1. Open the game with scene graph logic
2. Restart the layout

## Expected result
Probably on WorldInfo Release() method, both maps should be check and deleted from self instance if needed to keep memory print low.

## More details
This is probably not a major issue but I noticed it while converting the last r302 code.

**Comment by AshleyScirra** [comment]
@DiegoScirra - please take a look - sounds like it might be good to delete stuff from WeakMaps on release anyway, just to keep the overhead low.

@ratalaika - I don't think this will materially affect anything, JS GC is excellent these days and a bit more garbage probably won't matter.

**Comment by ratalaika** [comment]
@AshleyScirra Yeah Im pretty sure it wont matter much haha.
We noticed cause on C++ pointer addresses get reused and we were facing issues with scene graph and re-used pointers that's how we discovered it. Our CTO thought it would be good to report anyway just in case :).

**Comment by DiegoScirra** [comment]
The next beta will explicitly clear those maps when instances are released.
