### ISSUE TITLE
Spawn another object issue/bug. Sprite and SVG object in container

### ISSUE THREAD

**Issue by porshegt9** [Scirra/Construct-3-bugs#5901]
I have 2 objects in the container:
- Sprite (with Physics behavior)
- SVG (with Pin behavior). In the events sheet, it is pinned to the invisible Sprite (On start of layout), additionally added as a child to that Sprite.

When I create condition: 
System Repeat XX times and in the actions choose Sprite2, which is not in the container (action Spawn another object choose a Sprite which is in the container) 

On start of layout, it creates only instances for Sprite from the container but does not create instances for SVG object that is also there.

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.
