### ISSUE TITLE
SceneGraphInfo _OnAfterLoad if disabled via ;

### ISSUE THREAD

**Issue by ratalaika** [Scirra/Construct-3-bugs#5902]
## Problem description
On SceneGraphInfo class on the _OnAfterLoad method the "if (!ignoreMissingInstances);" call seems to de disabled via the ; on all places.

## Steps to reproduce
Code issue, unsure about proper behaviour

## Expected result
Probably the variable should be used to check and do something?

## More details
I found it very odd while adjusting this method, so I thoguht it may be important to brought it up.

**Comment by AshleyScirra** [comment]
I don't see any such code in our existing codebase. @DiegoScirra - is this something you already fixed?

**Comment by AshleyScirra** [comment]
Ah yes, the export process strips out assets, but puts `;` in their place otherwise `if (x) assert(y);` would incorrectly put the next statement in to the if statement. You can ignore those cases if it's after export.
