### ISSUE TITLE
Dark theme: search results in JSON almost invisible

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5908]
Search results in JSON are barely distinguishable:

![image](https://user-images.githubusercontent.com/36763350/179917075-e872af24-b2cc-4472-ad36-06088ce7f17f.png)

![image](https://user-images.githubusercontent.com/36763350/179917689-6c9bb2c5-20f5-47da-b391-dc0da4e1e1f2.png)

Please change the highlight color.

Also the search box itself is bright white with light grey text, which is not a good choice for a dark theme..

**Comment by DiegoScirra** [comment]
Both of these issues will be solved in the next beta.
