### ISSUE TITLE
Dark theme: Animation title is black while renaming thus not visible

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#591]
## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
![image](https://user-images.githubusercontent.com/7268697/27941565-dd3e15ea-62d9-11e7-9b26-4ea0d33966e9.png)

## Steps to reproduce

1. make a new project with dark theme enabled
2. create a sprite
3. rename its animation

## Observed result

Black text while renaming

## Expected result

White or something readable on the dark theme

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r44

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 233 mb (3.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by JeFawk** [comment]
Found another related issue

![image](https://user-images.githubusercontent.com/7268697/27942420-550025fa-62df-11e7-9888-0d79d8c68629.png)

**Comment by JeFawk** [comment]
While I'at it, is this intended?

![image](https://user-images.githubusercontent.com/7268697/27942577-b5f74536-62e0-11e7-81b5-a91f667b47e9.png)

**Comment by Animmaniac** [comment]
The renaming color should be fixed for the next iteration.

Regarding the arrow it's something I already reported to Ashley, but according to him it's the result of a Chrome bug. However I noticed there's a `fill="#010101"` in the second `<path>` node of the svg that is not present on the other icons. Removing it seems to fix it.
