### ISSUE TITLE
Spawning objects gives them a wrong UID

### ISSUE THREAD

**Issue by staarmaan** [Scirra/Construct-3-bugs#5910]
## Problem description
the objects that are spawned have a wrong UID that increases for every object spawned

## Attach a .c3p
[uid_spawn_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/9152730/uid_spawn_bug.zip)

## Steps to reproduce

1.spawn any object
2.use the debugger to check for the object UID

## Observed result
The objects have an incorrect UID and increases for the next object spawned. For example: you may have an object with a UID of 6 even if there is only one object present on the layout, and for the next object it will be an UID of 7. Even after restarting the layout, spawned objects still get a wrong UID
![image](https://user-images.githubusercontent.com/109689489/180051585-6aef08bc-6fe9-4bd3-ada1-d5cc448e9608.png)

## Expected result
The object UID should be based on the object count and it shouldn't be higher than that

## More details

**Affected browsers/platforms:** 
I tested this on a Windows 11 on Microsoft edge

**First affected release:** 
r302
## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Product: Construct 3 r302 (stable)
Browser: Edge 103.0.1264.62
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 2.9 gb (2.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by dop2000** [comment]
> the objects that are spawned have a wrong UID that increases for every object spawned

This is how UID works. It's unique for every new instance and across all objects on the current layout.

**Comment by AshleyScirra** [comment]
You should not expect UIDs to assume any particular value. The only guarantee made about UIDs is that they are a whole number and they are unique for each instance. The engine could also do something like generate large random numbers for each instance, but it happens to use an incrementing scheme; either way it should not meaningfully affect your project.
