### ISSUE TITLE
Layer properties:  Uses own texture

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5912]
## Problem description

It's not a bug, it doesn't cause any problems, I know this is by design. it's just curious.

why display an extra property to show the status of 'Uses own texture'.

![Snipaste_2022-07-22_14-58-36](https://user-images.githubusercontent.com/45864744/180382138-e83a8172-10ea-49b1-8829-5175f0445a72.png)

## Expected result

Would it be cleaner if removed it? And move it to the top

![Snipaste_2022-07-22_15-02-38](https://user-images.githubusercontent.com/45864744/180382672-458f9e17-634f-4e8d-9d80-62a514eb0dfc.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please don't file an issue to ask a question. It's better to ask questions on the forum.

There is a separate field because other properties can enable "own texture", like changing opacity or adding effects.
