### ISSUE TITLE
'Z axis scale' Project Properties Move to '3DCamera' Properties

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5913]
## Problem description

It's not a bug, it doesn't cause any problems, I know this is by design. it's just curious.

I think the 'Z Axis Scale 'property should be moved to the object property of '3D Camera' Plugin, Because this property only affects 3D features.

![Snipaste_2022-07-22_15-07-46](https://user-images.githubusercontent.com/45864744/180383932-024b6ce2-f06c-496f-9da3-b12472d5efa7.png)

## Expected result

![Snipaste_2022-07-22_15-12-35](https://user-images.githubusercontent.com/45864744/180384280-a6e196e1-25d3-4685-90ba-0be9c1bf2837.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It needs to be a project property because it affects things in the project even if there is not a 3D camera, such as 3D shapes.
