### ISSUE TITLE
Inputbox for Description in Function or Variable, Use <textarea> instead of <input>

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5914]
## Problem description

I think, the input box for Description should use `<textarea>` instead of `<input>`

Add / Edit global variable
![Snipaste_2022-07-22_15-23-31](https://user-images.githubusercontent.com/45864744/180386176-91eda50e-8e63-425a-a4c4-16a96455573d.png)

Add / Edit  function
![Snipaste_2022-07-22_15-17-48](https://user-images.githubusercontent.com/45864744/180386106-a6c665f0-9a18-4d02-a85f-af58a6cca0a3.png)

## Expected result

![Snipaste_2022-07-22_15-18-49](https://user-images.githubusercontent.com/45864744/180386037-5129131c-a979-4b88-b006-8bab5a899981.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please post this as a suggestion.
