### ISSUE TITLE
dragging conditions again

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5917]
## Problem description
![ezgif com-gif-maker (18)](https://user-images.githubusercontent.com/89512047/180503304-1d42ac6e-fc97-428a-ad8e-6548f06565f3.gif)

this is an follow up of issue #5843 
While the issue was marked as fixed and I see what change was made, it was not done in the way I expected. Maybe this is just a misunderstanding on my part of how the visualization of dragging conditions is supposed to be understood.
While I get that this might not be  a bug but moreso a problem with interpreting the visualization, but I will try to communicate clearly why I think it's suboptimal.

## Observed result
When dragging a CONDITION onto an event or function that HAS NO condition the dragging is visualized with a LONG line. 
When dragging a CONDITION onto an event or function that HAS conditions the dragging is visualized with a SHORT line. 
When dragging an EVENT around it is visualized with a LONG line.

## Expected result
When dragging a CONDITION onto an event or function that HAS NO condition the dragging is visualized with a SHORT line as well.

## More details
Visualizing it with a long line makes it seem like the user is dragging the condition above or below the event not into it (as it is seemingly the same visualization as dragging an event below or above another event).
The short line that overlaps the event should be used when dragging conditions at all times imho, as the conditions are represented shorter than the event when highlighted as well.
Currently the visualization of dragging a condition or the whole event looks the same to me.

**Comment by AshleyScirra** [comment]
Fixed for next beta.
