### ISSUE TITLE
 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'GetZElevation') - no idea how / why / when

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#5918]
## Problem description

I've been getting these random errors recently since r 302 in a huge project and honestly I got no idea how / why / when nor where to start from and where to end.

Doesn't help at all that I cannot disable events since it breaks my game so badly it won't run (it's multiplayer)

So I do expect this to be closed since I cannot provide a c3p yet, mainly because I would need to send the server over too until I can put it live somewhere and open the connection to public.

Maybe someone gets a clue what I can do next to try to pinpoint this completely random and wacky C3 error.

![image](https://user-images.githubusercontent.com/7268697/180518347-0e97c9d1-276c-4a0e-bf34-3cde5b081fdb.png)

 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'GetZElevation')
    at SortByInstZElevation (layer.js:2:187)
    at Array.sort (<anonymous>)
    at Layer._UpdateZIndices (layer.js:33:306)
    at Layer.Draw (layer.js:49:165)
    at Layout._DrawLayerList (layout.js:41:286)
    at Layout.Draw (layout.js:39:353)
    at C3Runtime._Render (runtime.js:91:312)
    at C3Runtime.Render (runtime.js:90:277)
    at C3Runtime.Tick (runtime.js:76:399)
    at C3Runtime.SetSuspended (runtime.js:72:446)
SortByInstZElevation @ layer.js:2
_UpdateZIndices @ layer.js:33
Draw @ layer.js:49
_DrawLayerList @ layout.js:41
Draw @ layout.js:39
_Render @ runtime.js:91
Render @ runtime.js:90
Tick @ runtime.js:76
SetSuspended @ runtime.js:72
_OnVisibilityChange @ runtime.js:69
(anonymous) @ runtime.js:11
_OnEventFromDOM @ runtime.js:17
_OnMessageFromDOM @ runtime.js:15
C3Runtime._messagePort.onmessage @ runtime.js:11

## More details

**Affected browsers/platforms:** Edge

**First affected release:** noticed from r302, but irrelevant since I tested only parts of the game before r302.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Edge 103.0.1264.62
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.375
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62
Language setting: en-US

Local storage
Storage quota (approx): 1006 gb
Storage usage (approx): 165 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to do anything about reports like this, and the error message does not even provide any useful information about what might have happened. I'm afraid I must direct you to the bug report guidelines, as we need all that information to be able to help.

**Comment by JeFawk** [comment]
I've sent a few days ago an email with the link to the project @AshleyScirra if you got some time to look over the crash. 
It's still happening, and so often now to the point where I'm not sure I can continue developing it since I can't get to the parts of the game I need to test.

**Comment by gutsalovpavel** [comment]
Had the same issue today, didn't know what I do wrong, just added new array, and randomly got to same error. when rolled back everything become fine
