### ISSUE TITLE
Scroll To Bug (With Screenshots)

### ISSUE THREAD

**Issue by GL00F** [Scirra/Construct-3-bugs#5920]
## Problem description

 Whenever I add the "Scroll To" behavior the sprite appears in the middle of the screen and cant move

## Attach a .c3p

 GitHub says they dont support a .c3p whenever I try and import it

## Steps to reproduce

1. Add scroll to behavior to a sprite
2. Add some sort of movement behavior
3. Preview the project

## Observed result

 The sprite gets stuck

## Expected result

 The sprites moves around and has the camera follow it

## More details
 I opened my account on a different computer and the same thing happend

**Affected browsers/platforms:**  Windows, Bing, Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>
![Behaviors](https://user-images.githubusercontent.com/109859672/180609325-3d417c7c-bd58-4390-9529-ec804b4d57ef.png)
![Placement](https://user-images.githubusercontent.com/109859672/180609330-84b5556c-264a-487c-9788-09fbaa983637.png)
![Bugged Placement](https://user-images.githubusercontent.com/109859672/180609336-6e0dbdf7-f969-4147-8b4b-1db07f82d6bc.png)

**Comment by F3der1co** [comment]
https://github.com/Scirra/Construct-3-bugs#how-to-include-a-project

btw, keep in mind: if the background is just one even color it will be impossible to see if the camera is moving or not.
Try adding some objects or a texture.

**Comment by staarmaan** [comment]
you can import a .c3p file by compressing it into a ZIP file

**Comment by AshleyScirra** [comment]
No project was provided so it's impossible for us to investigate, so closing. Please see the bug report guidelines which covers this and how to attach projects.
