### ISSUE TITLE
Tween: Edit Action, The properties incorrectly

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5922]
## Problem description

When I have a Tween (two Properties) event that 'Destroy on Complete ' is 'Yes'

![01](https://user-images.githubusercontent.com/45864744/180657764-cbf8f1c1-a2dd-4d81-9d15-99aaf0b4d1eb.png)

if I edit it and replace it with Tween (one Properties), The dialog will incorrectly change 'Loop' to Yes. You can find that, the background eventsheet display is correct.  'Loop' is No.  'Destroy on Complete ' is 'Yes'
![02](https://user-images.githubusercontent.com/45864744/180657791-eaef37ae-e17d-4929-8d55-75c35bf0ec12.png)

## Attach a .c3p

[Tween-event-parameter-issue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9176217/Tween-event-parameter-issue.c3p.zip)

## Steps to reproduce

1. Add action, Tween(two properties).  
2. 'Destroy on complete'  Yes, 
3. Done.
4. (optional) ~Select this action and copy and paste it below~ 
5. Edit the action,  Back,  Tween(one properties)
6. 

## More details

**Affected browsers/platforms:** Chrome, Windows 11

**First affected release:** 

## System details

<details><summary>View details</summary>

```
Platform information
Product: Construct 3 r303 (beta)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 368 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Super with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
```

</details>

**Comment by AshleyScirra** [comment]
This is by design: when editing conditions and actions, Construct will try to preserve the parameters you've entered even if you switch to a different condition or action. It only tries to match by if the type of the parameter matches, otherwise it would rarely ever be able to preserve the parameters. I believe in the vast majority of cases this is useful; in a few cases it might not be perfectly appropriate but I think it's still worth having.
