### ISSUE TITLE
[r303] Multiple Family members cannot be properly picked and assign as different Face object of 3DShapes

### ISSUE THREAD

**Issue by l-t-m-f** [Scirra/Construct-3-bugs#5923]
## Problem description

It is impossible to assign two instances belonging to the same Family to be different Face objects of the same 3DShape.

## Attach a .c3p

[FamilyFaceBug.zip](https://github.com/Scirra/Construct-3-bugs/files/9176931/FamilyFaceBug.zip)

## Steps to reproduce

OUTSIDE THE EVENT SHEET

1. Create a Family containing 2 objects (tested with Sprite and TiledBackground)
2. Give them different art

IN THE EVENT SHEET

1. Create two set of event condition to pick the Family using the UID of one of the objects (in two branch of individual events).
2. As an action, assign the Family you just picked by UID to be the Face object of a 3DShape, **select only certain faces**
3. **With the other event branch, assign the remaining faces**

## Observed result

Only one of the object will be assigned to ALL faces.

## Expected result

Each Family instance member should be assigned to the appropriate faces.

## More details

I use this technique in other places in C3, and it works. Something in the case of 3DShape Face object assignment is glitched.
Family and their instance members usually share UID and can be picked by their instance UID.

**Affected browsers/platforms:** 

Chrome

**First affected release:** Noticed in r303

## System details

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 48 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
The 'Set face object' action uses an object type only. It ignores the picked instances. I think this is what is causing confusion. Images belong to object types, not instances, so the action is choosing which object type to source images from. It will ignore what the conditions pick and just tell the 3D shape to use a family for the image on one face. However families contain multiple object types with different images, and so this instruction is ambiguous; so it just picks any object type in the family and goes with that.

It seems easy enough to work around though - just use the action with specific object types instead of a family.

**Comment by l-t-m-f** [comment]
I was trying to build a generic function which would take any TiledBackground and assign it to any 3DShape's specified face, for the sake of efficiency (procedural game). 

Any chance you revise the way this is handled in the event sheet ? Seems like after a Pick by UID the editor should be wise enough to figure it out.

**Comment by fodi** [comment]
I have encountered the same issue today and I have an idea that could possibly solve this:
https://construct3-21h2.ideas.aha.io/ideas/C321H2-I-460
