### ISSUE TITLE
Crash when editing a couple of scripts

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#5925]
## Problem description

C3 crashed when I was editing a few script files. As often I don't know an exact cause, but I'll keep an eye out if it keeps happening. Specifically it happened after I edited 2 different js scripts, then switched back to the layout view (while a save was in progress).

## Steps to reproduce

1. ?

## Observed result

Crash

## Expected result

No Crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r303/projectResources.js, line 752, col 375
Message: Uncaught TypeError: Cannot read properties of null (reading 'rG')
Stack: TypeError: Cannot read properties of null (reading 'rG') at d.Qd (https://editor.construct.net/r303/projectResources.js:752:375) at d.oc (https://editor.construct.net/r303/projectResources.js:753:55) at d.mk (https://editor.construct.net/r303/projectResources.js:753:138) at Lgb.Zqc.mk (https://editor.construct.net/r303/components/bars/tilemapBar/tilemapBar.js:144:255) at Ueb (https://editor.construct.net/r303/components/bars/tilemapBar/tilemapBar.js:5:92) at TX (https://editor.construct.net/r303/components/bars/tilemapBar/tilemapBar.js:13:414) at CCG.ca.Rjc (https://editor.construct.net/r303/components/bars/tilemapBar/tilemapBar.js:93:315) at window.bLb.dispatchEvent (https://editor.construct.net/r303/main.js:1096:42) at fS (https://editor.construct.net/r303/components/editors/layoutView/layoutView.js:44:309) at window.fl.QV (https://editor.construct.net/r303/components/editors/layoutView/layoutView.js:110:400)
Construct version: r303
URL: https://editor.construct.net/r303/
Date: Mon Jul 25 2022 12:45:11 GMT+0200 (Central European Summer Time)
Uptime: 9528 s

Platform information
Product: Construct 3 r303 (beta)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Usually such reports are impossible to act on but assigning to @DiegoScirra in case his telepathic debugging is working.

**Comment by DiegoScirra** [comment]
This doesn't look like it has anything to do with scripts. The crash has something to do with the tilemap bar, but it is hard to tell exactly what.

**Comment by AshleyScirra** [comment]
Closing as there does not appear to be any way to further investigate this.
