### ISSUE TITLE
Array editor clear cell bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5928]
## Problem description

When I paste two cells from the clipboard into the array editor, the third one is cleared.

## Attach a .c3p

[array_editor_clear_cell_bug_r304b.zip](https://github.com/WilsonPercival/WilsonPercival/files/9183203/array_editor_clear_cell_bug_r304b.zip)

[Лист Microsoft Office Excel.xlsx](https://github.com/WilsonPercival/WilsonPercival/files/9183201/Microsoft.Office.Excel.xlsx)

## Steps to reproduce

1. Create a new project.
2. Add Array.json.
3. Resize it to 1x3x1.
4. Copy two cells from Excel.
5. Paste them into the array editor.

## Observed result

![bug](https://user-images.githubusercontent.com/91274932/180831275-654e0cfe-98df-45de-afeb-c1354a74d668.gif)

## Expected result

![expected](https://user-images.githubusercontent.com/91274932/180831254-a36be5a8-f556-484c-8257-dccdaa248324.png)

## More details

**Affected browsers/platforms:** Firefox

**First affected release:** broke in r304b

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r304 (beta)
Browser: Firefox 102.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
Language setting: en-US
Local storage

Storage quota (approx): 9.8 gb
Storage usage (approx): 25 mb (0.2%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
I'm inclined to believe this is a problem with what is being placed in the system clipboard by that particular spreadsheet program, I tried following those steps by copying and pasting from Google Sheets and there doesn't seem to be any problem.

Did you try to copy content from Microsoft Excel? If so, what version is it?

**Comment by WilsonPercival** [comment]
2007.

**Comment by Gryphonn** [comment]
> Did you try to copy content from Microsoft Excel? If so, what version is it?

The same bug. The latest version of Office 365.

**Comment by WilsonPercival** [comment]
> I'm inclined to believe this is a problem with what is being placed in the system clipboard by that particular spreadsheet program, I tried following those steps by copying and pasting from Google Sheets and there doesn't seem to be any problem.
> 
> Did you try to copy content from Microsoft Excel? If so, what version is it?

I just noticed that Excel itself adds a new line on purpose. Because of this, C3 updates 3 cells instead of 2.

**Comment by DiegoScirra** [comment]
It looks like this is just how Excel works.

I found a few StackOverflow questions from people asking how to avoid the behaviour and the questions go pretty far back. Not much to do about it, because there is no way to distinguish if the newline in the clipboard is unintentional or not.

Closing as there is nothing to do about it.
