### ISSUE TITLE
batching optimization, bug/request

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5930]
## Problem description
The moment one instances of the same object type has a different opacity (or anything else that requires it to be drawn separately), all instances of that object are drawn separately and not batched anymore. 

**I would have expected Construct to batch all instances that for example have the same opacity, set color etc. together.**

Currently having two separate object types, one with a bunch of instances with opacity at 50%, the other object with a bunch of instances being at opacity 80 has way better gpu performance then having the same object count, but only one object type and having half the instances set to opacity 50, the others to 80.

## Attach a .c3p
[batching.zip](https://github.com/Scirra/Construct-3-bugs/files/9200758/batching.zip)

## Steps to reproduce
1. run the project in debugger
2. check gpu usage in the first layout (one object type with 8192 instances, half the instances set to 50% opacity, the other half to 80%)
3. check gpu usage in the second layout (two object types with 4096 instances each, one object type is set to opacity 50% the other to 80%)

## Observed result
the first layout (with just one object type) has extemely hight gpu usage.
The second layout (with two objects types) has almost no gpu usage.

## Expected result
Both layouts have the same performace, as the instances with the same opacity should be batched even when there are instances of the same object type with another opacity.

There is also a higher cpu usage in the layout with just one object type, no idea why that would be the case.

**Comment by AshleyScirra** [comment]
This is not really a bug, just an observation of the batching system in the renderer. All programming involves tradeoffs, and with the capabilities of WebGL, there is a choice between either batching opacity but slowing down all normal rendering, or not batching opacity and speeding up all normal rendering. I went with the latter.

For what it's worth, with the increased capabilities of WebGPU, Construct will be able to batch changes in color and opacity. Hopefully WebGPU will arrive in browsers some time in the next year or so.

**Comment by F3der1co** [comment]
Ok, that makes sense. Thank you for commenting on this!
