### ISSUE TITLE
Animations Import Crashes Construct 3

### ISSUE THREAD

**Issue by brainwavecreations** [Scirra/Construct-3-bugs#5937]
Bug Video: https://youtu.be/iZlVSkUarB4

Problem description: 

I noticed this bug while trying to import images I had exported from another version of this project.  I'm recreating the project for a tutorial series.  Anyways.  I had deleted some images from my player sprite object, and then imported the .zip that had been exported previously.  All projects were in r304.  I got a crash the first time with a crash report regarding memory loss, but closed it without grabbing the report.  Then my .c3p file was corrupted and could not be opened.  I've tested this again, and recreated it a couple times on video by removing animations and then importing the file.  Sometimes, it takes just one time, other times a couple times of deleting and importing images.  But, now it gives a browser memory issue, now that I'm recording the video.  The crash report initially stated something about a memory issue as well.

Attach a .c3p:  Attached
[Bugged 1 - Player Initialization & Player Animations.zip](https://github.com/Scirra/Construct-3-bugs/files/9215194/Bugged.1.-.Player.Initialization.Player.Animations.zip)

Steps to reproduce

1. Delete some Animations from Animations List on a sprite object
2. Import previously exported Animation File with data of any size.  I even tested smaller .zips, and smaller animations, but didn't get it on video unfortunately.  I am spent, and trying to submit these bug reports quickly before I personally crash.
3. Sometimes it will crash with a bug report(first time for me), or a browser memory error
4. This one is hit or miss.  Sometimes it will crash.  No telling how many times you can delete animations, and re-import animations, or other animations not previously imported

Observed result:

Construct 3 crashes while trying to import images from previous export .zip with data, after deleting some images from the Animations List.  Does not seem to matter how many Animations are left.  I tried with all different sizes, images, animations, etc.

## Expected result

No crash while importing image export .zip file with data

More details: None.  It's explained pretty well above.

**Affected browsers/platforms:** 
Windows 10, all chromium browsers I have (Chrome, Brave)

Noticed it with r304

**First affected release:** 
Noticed it with r304

System details:
Windows 10, all chromium browsers I have (Chrome, Brave)

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 195 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
The video is not available in all three bug reports.

**Comment by brainwavecreations** [comment]
I just made them public.  It's strange because anyone with the link should be able to view "Private" videos through the direct link.  Apologies for that : /

**Comment by avishaymizrav** [comment]
> I just made them public. It's strange because anyone with the link should be able to view "Private" videos through the direct link. Apologies for that : /

Private are private :)
You're looking for unlisted, then it won't show up on your profile or search, but be available with a link.

**Comment by brainwavecreations** [comment]
Ohh....  Right.  My bad : /.  I am so sleep deprived, and was super sick last night.  I was just trying to get the videos recorded, and these bug reports submitted.  My bad....  I've got to get my sleep back under control.  They should all be viewable now, in any case.

Thanks for the reminder.  It says which one is viewable with a link when uploading the videos.  But, I was just in a rush to be done with the day at 9-10pm last night, and relax for an hour or two before bed.

**Comment by DiegoScirra** [comment]
Ok, I am able to reproduce this If I just hammer it with a massive file a few times. Will have to make sure there are no leaks, but asides from that, I imagine if you use a large enough file, eventually it would crash in one go.

**Comment by brainwavecreations** [comment]
That makes sense.  I figured it had to do with the memory not clearing properly while removing animations already setup in there, then importing more.  But, I don't know the internal workings.  Thanks so much for all of your work, @DiegoScirra !

**Comment by DiegoScirra** [comment]
This will be greatly improved on the next beta cycle. There were a few things left behind during the import process and those eventually crashed the app.

Because of the way the importer is implemented, I am pretty sure that if a zip file containing around 300 animations is imported it will cause the browser to crash too, fixing that will be much more difficult though, so unless it proves to be a pain point to some user (which I doubt), I will leave that to fix it sometime in the future.
