### ISSUE TITLE
Physics 120 fps bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5938]
## Problem description

When I run the game on a mobile device with 120 fps, the car's spring effect disappears. At 60 fps everything works fine.

## Attach a .c3p

[physics_120_fps_bug_r302s.zip](https://github.com/WilsonPercival/WilsonPercival/files/9217760/physics_120_fps_bug_r302s.zip)

## Steps to reproduce

1. Open the project on a device that plays the game at 120 frames per second.
2. Launch the game.
3. Hold down on the gas.

## Observed result

60 fps:
https://user-images.githubusercontent.com/91274932/181711267-5d3aa05c-3eaa-4467-ab30-c3d77a7e8c70.mp4

120 fps:
https://user-images.githubusercontent.com/91274932/181711311-4807d3d9-70b8-4340-a38d-1dc30438fc88.mp4

## Expected result

At 120 fps everything should work the same as at 60 fps.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r302s

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: browser
Operating system: Android 11.0.0
Device type: mobile
Device pixel ratio: 3
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Linux; arm_64; Android 11; RMX2086) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.148 YaBrowser/22.7.3.82.00 SA/3 Mobile Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 26 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Qualcomm
Renderer: Adreno (TM) 640
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Wackytoaster** [comment]
Quick guess: You need to use deltatime when you apply forces to objects.
https://www.construct.net/en/tutorials/delta-time-framerate-71

**Comment by AshleyScirra** [comment]
Please provide a minimal project if you can as per the bug report guidelines - it is extremely difficult to investigate problems in projects with any degree of complexity.

**Comment by WilsonPercival** [comment]
> Please provide a minimal project if you can as per the bug report guidelines - it is extremely difficult to investigate problems in projects with any degree of complexity.

[car.zip](https://github.com/Scirra/Construct-3-bugs/files/9281579/car.zip)

**Comment by AshleyScirra** [comment]
I have a mobile device that supports a 120 Hz refresh rate. Both the original project and the minimal project work fine on it for me.

Besides, I doubt there is anything we can do about this anyway: the physics engine is Box2D, and if Box2D does not calculate movement for a timestep then that was up to Box2D, which is outside of our control. I suspect that for smaller time steps perhaps you need to increase the precision of the physics behavior to compensate and ensure the simulation keeps working as expected. Try using 'Set stepping iterations' to increase the velocity/position iterations so it does more CPU work to improve the precision of the simulation.
