### ISSUE TITLE
Error Name is not allowed

### ISSUE THREAD

**Issue by ravensdojo** [Scirra/Construct-3-bugs#5940]
## Problem description

I am unable to open project folder. Red screen kicks stating file project folder cannot be opened.

## Attach a .c3p

Unable to open file folder to save c3p. Project folder zipped instead.

http://www.ravensdojo.com/terrorcube2021.zip

## Steps to reproduce

1. Download zipped file.
2. Attempt to open project folder. 
3. Project will fail to open every time. 

## Observed result

File folder fails to open. Screen turns red. Error pops stating 'Check to see if file is valid construct 3 file'. Error report states Unhandled rejection. Error: Name is not allowed

## Expected result

File Project folder opened fine before today.

## More details

I was working on the project and saving the file just fine before the issue happened. Then I went to save and an error kicked stating unable to save. It stated I might not have proper permissions. After that error happened Construct 3 crashed. After that I was unable to open the project again.

**Affected browsers/platforms:** 

I attempted to open my file project folder in Chrome, Firefox, and Opera. None allowed the project to open. All kicked the exact same error. 

**First affected release:**

The project was developed under r302 stable with no issues before today. 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Name is not allowed. @ TypeError: Name is not allowed.
Stack: TypeError: Name is not allowed.
Construct version: r302
URL: https://editor.construct.net/
Date: Sat Jul 30 2022 00:45:47 GMT-0400 (Eastern Daylight Time)
Uptime: 216.1 s

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by GameSoul7Eugene** [comment]
@ravensdojo, I fixed your project's integrity. It should now successfully open: [Download fixed project](https://drive.google.com/file/d/1rm-NC4xU9j6-Bt_xcNM-cFRoTLiMoIv2/view?usp=sharing)

The issue can be closed.

**Comment by ravensdojo** [comment]
Thank you King! You are an absolute hero! Saved a week of my life! Time to backup projects DAILY!! Phew!
