### ISSUE TITLE
More array scrolling bugs

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5942]
## Attach a .c3p

First issue:

1. Scroll to the second column
2. Try to use the scroll bar to return to the first column

## Observed result

Scroll bar doesn't work. You can only return to the first column using keyboard.

![image](https://media.giphy.com/media/A6dD9lUsHJZ2we0AtG/giphy.gif)

Second issue:

1. Double-click any cell in the second column
2. Double-click any other cell in the same column

## Observed result

The table scrolls to the third column, while the focus remains in the clicked (but now invisible) cell. If you type something, the data in the cell will be overwritten.

![image](https://user-images.githubusercontent.com/36763350/182013070-3eaeaa0d-c558-4f75-96de-aac23b4ad8f1.png)

## More details

**Affected browsers/platforms:** Chrome/Firefox

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 169 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment]
The second issue will be fixed in the next beta.

The first one is too much trouble for what it is worth, so it won't get fixed.

What is happening is that  the editor will snap to the position of a cell on the left side and place the scroll bar accordingly, so unless the scroll bar moves enough to snap to a cell, it is set back to a position in which it does snap. This seems to only be noticeable when the scroll is almost at the beginning.

The solution for that would be to implement smooth scrolling, rather then by cell, so there would be no need to force the position of the scroll bars. That is a lot of work and would just open the door for lots of new and interesting bugs.

**Comment by dop2000** [comment]
> The first one is too much trouble for what it is worth, so it won't get fixed.
No worries! 
Thanks for fixing the other one 👍
