### ISSUE TITLE
Missing debugger properties

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-3-bugs#5944]
## Problem description

The second set of missing debugger properties for some addons:

**Enabled** for [Slider bar](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/slider-bar)
**Jump sustain** for [Platform](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/platform)
**Z height** for [3D shape](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/3d-shape)
**Light height & Tag** for [Shadow Light](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/shadow-light)
**Analog deadzone** for [Gamepad](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/gamepad)

## Observed result

Debugger properties above are missing.

## Expected result

Debugger properties above should not be missing.

## More details

**First affected release:** r304

**Comment by Wackytoaster** [comment]
I wanna add, anything relating to effects/effect parameters is also nowhere to be found in the debugger.

**Comment by dop2000** [comment]
And hierarchy.. I so want to see parent/children in debug view!

**Comment by AshleyScirra** [comment]
I've added the properties mentioned in the original report for the next beta, as those appear to be oversights. For other debugger requests please post suggestions as they are more significant additions (and in particular it's not clear how the hierarchy would be best represented in the debugger).
