### ISSUE TITLE
Saving & sharing projects 404 :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5945]
## Problem description

The link leads to nowhere.

## Attach a .c3p

https://www.construct.net/en/make-games/manuals/construct-3/overview/saving-sharing-projects

## Steps to reproduce

1. Follow the link.

## Observed result

![bug](https://user-images.githubusercontent.com/91274932/182045319-a2c86a20-8865-443a-a586-e1328a61e2c7.png)

## Expected result

Working link.

## More details

https://www.construct.net/en/make-games/manuals/construct-3/interface/main-menu

![xxx](https://user-images.githubusercontent.com/91274932/182045384-fe9d8fe2-bd12-40ca-b43c-ce7053f4f36b.png)

**Affected browsers/platforms:** Chrome

**First affected release:** broke in 2022

## System details

<details><summary>View details</summary>

![inscryption](https://user-images.githubusercontent.com/91274932/175827374-34cc405b-90fe-4e6e-90e0-482114318fea.gif)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed the link.
