### ISSUE TITLE
Saving a project different items :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5946]
## Problem description

The description items differ from the buttons in the menu.

## Attach a .c3p

https://www.construct.net/en/make-games/manuals/construct-3/interface/main-menu

## Steps to reproduce

1. Compare the menu items and the items described in the documentation.

## Observed result

![xxx](https://user-images.githubusercontent.com/91274932/182045620-1897d93c-3fe3-4d9e-b944-fb9e1b82f168.png)

![bug](https://user-images.githubusercontent.com/91274932/182045639-a03612f3-2215-4d6b-8ff1-f23f32c85670.png)

## Expected result

Items in the article:

Cloud save

Save as single file...

Save as project folder...

Download a copy

## More details

I'm interested in the difference between `Save as single file...` and `Download a copy`.

**Affected browsers/platforms:** Chrome

**First affected release:** broke in 2022

## System details

<details><summary>View details</summary>

![inscryption](https://user-images.githubusercontent.com/91274932/175827374-34cc405b-90fe-4e6e-90e0-482114318fea.gif)

</details>

**Comment by AshleyScirra** [comment]
Updated the documentation to cover the possible options.
