### ISSUE TITLE
Form objects vanish on full screen

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#595]
## Problem description

Form objects vanish in game on full screen request
(repeatable)

## Steps to reproduce

1. create button, create some other form object eg text input box , list etc
2. make event on click button browser request fullscreen 
3. run
4. press button for fullscreen

## Observed result

all form objects disappear 

## Expected result

not to

## Affected browsers

* Chrome:

## System details

C3 R44
Windows 10 
Chrome 59
Surface Pro 4 i5 8gb

**Comment by AshleyScirra** [comment]
Please provide a project as per the guidelines
