### ISSUE TITLE
Instance Variables missing from Dictionary and Array AsJSON output

### ISSUE THREAD

**Issue by broknecho** [Scirra/Construct-3-bugs#5951]
## Problem description

When using the `AsJSON` expression, the `Dictionary` and `Array` objects do not include their own Instance Variables in the JSON ouput. 

## Attach a .c3p

[MissingIvsInJson.zip](https://github.com/Scirra/Construct-3-bugs/files/9237626/MissingIvsInJson.zip)

## Steps to reproduce

1. Rename attached project to `c3p`
2. Open project
3. Click the 3 buttons to see the `AsJSON` expression of a Sprite, Dictionary and Array object.
4. Observe that each object have a `name` instance variable on each object

## Observed result

Sprite has a `ivs` output in it's JSON but Dictionary and Array do not.

## Expected result

Given that other objects that have instance variables can export the contents of those variables, Dictionary and Array should also export `ivs` if they are set.

## More details

Testing in Edge 103.0.1264.49

**Affected browsers/platforms:** 

**First affected release:** 
Likely has been this way for a long time.  Not sure if this affects the C2 backwards compatibility but given it's a new `ivs` property, it may be ignored.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Edge 103.0.1264.49
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.49
Language setting: en-US

Local storage
Storage quota (approx): 140 gb
Storage usage (approx): 663 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.2.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by dop2000** [comment]
If anything, there should be a separate expression. One for exporting the array/dictionary data only, and another for exporting the entire object with all its properties, instance variables etc. Similar to Tilemap.TilesJSON and Tilemap.AsJSON

**Comment by AshleyScirra** [comment]
It's currently by design that Dictionary and Array only return their data structure contents with the `AsJSON` expressions. The purpose of these expressions is to export the data somewhere else. For example you can add it as a JSON file to the project and use it with the array or dictionary editors in Construct. These editors don't show or use instance variables in any way, nor presumably would any other external tool that makes use of this data as they wouldn't have the concept of instance variables either. So even if this data was exported it probably wouldn't be used by anything that reads the data.

I guess we could add a separate expression to include instance variables, but then I still don't see why, as nothing would read the instance variable values.

**Comment by broknecho** [comment]
@AshleyScirra  The use case here is for a game I'm making where I store the user preferences on a remote server.  I have been using an Invisible Sprite for this it feels like overkill.   Using Global variables is an anti pattern and I avoid it to not pollute the intellisense in the editor:

![image](https://user-images.githubusercontent.com/3253547/183110395-233fac85-c3b2-4c2b-be48-8b8cb347508c.png)

'Globals' there is a dictionary that I hand variables off for intellisense and storage.

`Globals` or something like `PlayerPrefs` can easily be serialized into JSON and then stored on a remote server.  Then loaded from there is just as trivial.

I figured that a Dictionary/Array object is lighter weight than a Sprite object for holding variable information that is saved to disk/remote server.

This ticket was more about how the engine allows `ivs` variables to be set but does not behave consistently with its AsJSON expression.  I agree it's not a bug but it is a consistency issue.  @dop2000 brought up a good example with the TileMap object (which is newer than the Dictionary/Array design).
