### ISSUE TITLE
On Mouse Wheel event continues to fire for 2-3 seconds when using touchpad on laptop

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#5953]
# Problem description

Swiping with two fingers on any touchpad usually emulates mouse wheel. However I noticed that in Construct this causes "On wheel" event to fire for a very long time - 2-3 seconds after the gesture has finished.. 
After some investigation I found that the touchpad sends deltaX and deltaY values in the 'wheel' event for a much longer time than mouse. These values are gradually reducing from ~175 to 0 over several seconds, allowing for a nice inertia effect. 

But in Construct we don't have access to these delta values. So, for example, if I'm using mouse wheel events to scroll a map in the game, it will continue scrolling at full speed for 3 seconds!

## Attach a .c3p

https://www.dropbox.com/s/bm4b97ff2wrfux6/TouchpadScrollIssue.c3p?dl=0

## Steps to reproduce

1. Try using mouse wheel and two-finger scroll gesture on touchpad 
2. Check browser console

## Observed result

A short mouse wheel rotation triggers "On wheel" event about 2-5 times.
A short swipe may trigger it 100-300 times!
This makes this event pretty much unusable with touchpad.

## Expected result

Could you add a check that deltaX/Y needs to be over a certain value to trigger "On Wheel" event?
If this is not possible, then maybe you could add a new expressions to Mouse object - wheelDeltaX/wheelDeltaY ?

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 168 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This does make the wheel trigger basically useless for trackpads. I think the best thing to do is just to expose the wheel delta values so you can either vary the magnitude accordingly or apply thresholding yourself; added those for the next beta.
