### ISSUE TITLE
Holding alt + clicking on an already-selected object doesn't select it exclusively

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#5955]
## Problem description

When multiple instances are selected, holding alt and clicking on an object doesn't select it. The selection effectively stays the same.

## Attach a .c3p
[youguysshoulddogfoodmore.zip](https://github.com/Scirra/Construct-3-bugs/files/9248789/youguysshoulddogfoodmore.zip)

## Steps to reproduce

Create a project or open any existing project with two or more objects in a layout.
Drag-select multiple objects.
Hold alt and and left click on one of the already-selected objects.

## Observed result

Nothing with the selection changes.

## Expected result

The object left-clicked on should have become the only selection.

## More details

**Affected browsers/platforms:** 

**First affected release:** 
Checked back to r302

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Scoremonger** [comment]
For context, I noticed this problem when I was using `Select mode: All` with a hierarchy and was trying to figure out how to select and move around individual elements inside it without changing the select mode. From reading the C3 docs I got the impression that this was the intent of the alt-click selection feature.

It's also not easy to change back to `Select mode: Normal` in a hierarchy because you must find the parent object in the Object Types folder to select it, which is clunky, and if you're working with multiple hierarchies you're forced to change the select mode to normal for all of them. If holding alt and clicking on an individual element selects only that element and deselects everything else, that would fix all these workflow issues.

**Comment by AshleyScirra** [comment]
The provided project and steps doesn't look like a bug to me. Holding alt and clicking something is not supposed to unselect it - that's what holding control does, and it works correctly in that project if you hold control instead.

**Comment by Scoremonger** [comment]
@AshleyScirra To clarify, I'm not suggesting that holding alt and clicking should deselect the thing you're clicking on. (As you said, that makes no sense as it is already handled by ctrl+click.)

I'm saying that holding alt and clicking on an object that is already selected doesn't really do anything. The handles appear around the object, but the object isn't selected exclusively, so effectively nothing changes. Here's a better project for illustrating the problem:
[AltSelectionWorkflowIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/9272572/AltSelectionWorkflowIssue.zip)

This is especially noticeable when working with a hierarchy or container set to `Select mode: All`, and the hierarchy/container is already selected. Holding alt and clicking on one of the instances doesn't do anything useful - it's functionally the same as clicking on each instance in the hierarchy without holding alt. The handles move from instance to instance, but that doesn't let the instances be individually manipulated, so it feels like a broken feature.

The docs say:

> If you still need to select an individual object in an automatically wrapped selection, hold Alt and click one of the objects.
(Containers)

> The root instance also has a Select mode property that, similar to containers, allows automatically selecting the entire hierarchy, also optionally with selection wrapping. If this is enabled, you can always hold Alt and click an instance to select it individually regardless of the select mode.
(Hierarchies)

It wasn't clear from those descriptions that holding alt + clicking an instance will _only_ work if the container/hierarchy is not already selected, so my expectation was that holding alt and clicking within a selection would exclusively select the instance I clicked on (somehow), i.e. that everything _but_ the alt-clicked instance would be deselected. That's what I was suggesting RE: deselection.

If you opt not to address this limitation, I hope you'll update the docs to clarify when alt-click will work and when it won't. Thanks for your time.

**Comment by Scoremonger** [comment]
@AshleyScirra Bumping this because I think there was a misunderstanding about what the bug/workflow issue is and I don't want this to fall through the cracks because of that. Hopefully my more detailed description + project makes it clear.

**Comment by AshleyScirra** [comment]
It's by design. I think you have misunderstood how it's supposed to work. I guess we can update the manual to clarify it but I'm not sure what wording to use. Holding Alt works exactly the same as not holding alt, in that it only selects unselected items and is not able to unselect already-selected items; holding alt disables the automatic additional selection of other items. I don't think the manual description suggests that you can unselect anything by holding alt.

**Comment by Scoremonger** [comment]
Ah, I see. Thank you for reviewing what I wrote and clarifying how the feature works. I believe making alt-click exclusively select an item regardless of the current selection would be more intuitive and generally useful, but I now understand the distinction and see why you say it's not a bug. I can add this to the ideas platform as a workflow improvement suggestion and we'll call it a day. 

To respond to your other comments, the manual doesn't explicitly say that alt-click deselects anything, true. I just assumed it would because it seems like an unnecessary step when working with auto-selected hierarchies to have to deselect the entire hierarchy and then alt-click the elements I want to move. And as I mentioned, if I have an auto-selected hierarchy selected, deselect one of the instances with ctrl-click, and then alt-click that instance, it does indeed deselect the remaining instances. So there are situations where alt-clicking _does_ deselect things (per your description, that's the actual bug here.) Hopefully I'm making the case that this is all a bit confusing.

As for how to update the manual, I think something along the lines of what you wrote in your response would be pretty clear, at least in terms of removing the confusion I had about why it wasn't doing anything with an already-selected hierarchy.
