### ISSUE TITLE
"Lock all but this" improvement

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#5956]
## Problem description

I use sublayers a lot to keep order in with layers. Also I like the right click on Layer options Show/Hide and Lock/unlock. Like "lock all but this" is very useful. I use other software that use similar options but with a, in my opinion slightly improved mechanism. When the layer structure is collapsed the options like "lock all but this" is applied to all sublayers, which can be very handy in some situations. So this is more an improvement idea and not a bug.
## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please post suggestions for improvements to the suggestions platform.
