### ISSUE TITLE
Gamepad object not working

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#596]
## Problem description

Gamepad not working

## Attach a .c3p

+ Gamepad: Gamepad 0 Button A is down
+ OR Keyboard: Space is down
-> Sprite: Set Invisible

+ System: Else
-> Sprite: Set Visible

## Steps to reproduce

1. add joypad object (also keyboard for test)
2.  make sprite 
3. use code above to test joypad support

## Observed result

Nothing happens when joy  key a pressed

## Expected result

Sprite disappears when joypad key a pressed

## Affected browsers

Chrome:

## System details

C44
Chrome 59
Windws 10
Surface Pro I5 8gb

**Comment by AshleyScirra** [comment]
Please provide a project as per the guidelines.
