### ISSUE TITLE
Array editor: copy and paste in excel bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5960]
## Problem description

When I copy 4 cells from the array editor in Excel, the paste doesn't work correctly.

## Attach a .c3p

[array_editor_copy_and_paste_in_excel_bug_1_r304b.zip](https://github.com/WilsonPercival/WilsonPercival/files/9254674/array_editor_copy_and_paste_in_excel_bug_1_r304b.zip)

[bug1.xlsx](https://github.com/WilsonPercival/WilsonPercival/files/9254675/bug1.xlsx)

[bug1.txt](https://github.com/WilsonPercival/WilsonPercival/files/9254676/bug1.txt)

## Steps to reproduce

1. Create a new project.
2. Create an `Array` in the `Files` folder.
3. Resize the array to 2x2x1.
4. Fill the array appropriately:
```
3   Say "Hello"
6   2
```
5. Copy all cells.
6. Paste the contents of the clipboard into Excel.

## Observed result

![bug1](https://user-images.githubusercontent.com/91274932/182700201-e530c3dd-8e9d-4035-bb6b-b075684a88fb.gif)

## Expected result

The insertion occurs correctly: each cell into its own cell.

## More details

I also noticed wrong pasting if I add 1 to a new row in the top right cell:

![bug](https://user-images.githubusercontent.com/91274932/182700289-23910962-265c-4485-8875-43b7a75937a7.gif)

[array_editor_copy_and_paste_in_excel_bug_2_r304b.zip](https://github.com/WilsonPercival/WilsonPercival/files/9254679/array_editor_copy_and_paste_in_excel_bug_2_r304b.zip)

[bug2.xlsx](https://github.com/WilsonPercival/WilsonPercival/files/9254680/bug2.xlsx)

[bug2.txt](https://github.com/WilsonPercival/WilsonPercival/files/9254681/bug2.txt)

**Affected browsers/platforms:** Mozilla

**First affected release:** broke in r304b

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r304 (beta)
Browser: Firefox 103.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Language setting: en-US
Local storage

Storage quota (approx): 9.8 gb
Storage usage (approx): 25 mb (0.3%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
I have tried this in several different alternatives to the desktop version of Excel (Google Sheets, Excel's web version and OpenOffice's Calc) and they all seem to handle this properly. Going to have to close this as I don't see how our code could change without breaking anything else.

**Comment by Gryphonn** [comment]
> I have tried this in several different alternatives to the desktop version of Excel (Google Sheets, Excel's web version and OpenOffice's Calc) and they all seem to handle this properly. Going to have to close this as I don't see how our code could change without breaking anything else.

Correct me if I'm wrong. 
You copied four cells (one of them is multiline AND contains quotes) into Excel and everything is fine. Correct?

Could you please share a screenshot after copying? 

Do you by any chance have Mac?
