### ISSUE TITLE
This site can’t be reached https://editor.construct.net/r302/

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-3-bugs#5961]
I cannot access the R302 directly as it shows an error message:

> This site can’t be reached
> The webpage at https://editor.construct.net/r302/ might be temporarily down or it may have moved permanently to a new web address.
> ERR_FAILED

It's been broken since r302 came out, I like to use direct links to lock the projects to a specific C3 Release until I upgrade again so it's very important for me. 
If I use the normal link "**https://editor.construct.net/**" 
Then in the Next stable release, it will Update me Automatically which I don't want as I would like to have control over when I will update to a newer version.

## Attach a .c3p

![Image 40](https://user-images.githubusercontent.com/41597700/182779735-9d8d11e1-f171-4c46-9770-15a599555fc4.png)

## Steps to reproduce

1. Visit the R302 using the Direct Link: **https://editor.construct.net/r302/**
2.
3.

## Observed result

Chome Error message

## Expected result

To rich C3 editor r302 version

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

I can't past anything as I haven't rich the editor

</details>

**Comment by AshleyScirra** [comment]
I think I figured out what's going on: at the moment `editor.construct.net/r302` is redirecting to `editor.construct.net`, and the browser is rejecting the offline cache when it's redirected. (It's possible the way browsers handle this has changed recently, I thought this previously worked OK.) I came up with a workaround which should fix it, but it won't take effect until the next stable release, so you'll have to wait until then - in the mean time just continue to visit editor.construct.net directly for the latest r302 stable release.

**Comment by Tarek200** [comment]
Thanks a lot
