### ISSUE TITLE
Positioned sounds not played after game loaded

### ISSUE THREAD

**Issue by MihaMS** [Scirra/Construct-3-bugs#5962]
## Problem description

After Saving and then loading game Positioned Sounds are do not continue to play (as regular sounds do).

## Attach a .c3p

https://drive.google.com/file/d/1B3P0ADvhKtPtjGWP2y823XyOIXGHrvVn/view?usp=sharing

## Steps to reproduce

1. Open and run attached project file. You will hear a sound
2. Click Save button
3. Click Load button

## Observed result

Sound doesn't play after loading.

## Expected result

Sound does play after loading, as non-positioned audio does.

## More details

**Affected browsers/platforms:** 

Tested on Chrome. Not tested on other platforms.

**First affected release:** 

C3 r302 stable. Not tested on previous releases

## System details

Windows 10.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
