### ISSUE TITLE
Array editor: remove spaces bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5968]
## Problem description

When I paste text from notepad into the array editor and open the cell, there is only one space left.

## Attach a .c3p

[array_editor_remove_spaces_bug_r304b.zip](https://github.com/WilsonPercival/WilsonPercival/files/9277486/array_editor_remove_spaces_bug_r304b.zip)

## Steps to reproduce

1. Create a new project.
2. Create an `Array` in the `Files` folder.
3. Write in a notepad

```
1        9
```
4. Paste the content into the cell.
5. Open the cell.

## Observed result

![bug](https://user-images.githubusercontent.com/91274932/183309808-73a092e5-5aae-49e6-ac08-b6317465daf8.gif)

## Expected result

![expected](https://user-images.githubusercontent.com/91274932/183309965-b8367244-d70d-4e4b-9475-dcf931e0aff2.png)

## More details

**Affected browsers/platforms:** Mozilla

**First affected release:** broke in r304b

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r304 (beta)
Browser: Firefox 103.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Language setting: en-US
Local storage

Storage quota (approx): 9.8 gb
Storage usage (approx): 26 mb (0.3%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It preserves the spaces for me just fine, both when pasting, viewing and editing. Check if you have any browser extensions that might be interfering with CSS styles or editing.

**Comment by WilsonPercival** [comment]
> It preserves the spaces for me just fine, both when pasting, viewing and editing. Check if you have any browser extensions that might be interfering with CSS styles or editing.

None. Have you tried pasting content without going into the cell?

**Comment by AshleyScirra** [comment]
Oh, I see, it does not reproduce if you edit the cell first, only if you paste directly on to it. Fixed for next beta.
