### ISSUE TITLE
Tilemap bar render problem

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#597]
## Problem description

Blurry pixel art in the tilemap bar.
Here's a screenshot: **http://imgur.com/BulGa4s**

## Attach a .c3p

[Tilemap bar bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1133484/Tilemap.bar.bug.zip)

## Steps to reproduce

1. Create a new project
2. Insert a pixel art tilemap in the project
3. Select the tilemap bar
4. Zoom in

## Observed result

Blurry pixel art in the tilemap bar.

## Expected result

Hard edge pixel art in the tilemap bar.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r45.
