### ISSUE TITLE
Specific action performed during saving leads to application freezing

### ISSUE THREAD

**Issue by UbruPro123** [Scirra/Construct-3-bugs#5970]
## Problem description

If I use the system save action during a specific action, it leads to freezing of the whole application, see description below.

## Attach a .c3p

Sent via email because of the larger size and the fact that I don't want to share it publicly, thank you for understanding.

## Steps to reproduce

I am creating this bug report (related to previous one #5848) again with exact steps to reproduce this state easily. Before I was not sure when this is happening but now you can simulate it yourself in matters of seconds. Also now there is only condition and directly save action, no waiting etc so it should work in this form.
I changed the logic of the game to make it possible from the opening screen to jump straight into the game where a situation is prepared for simulating an error.

1. Open project and start preview F4
2. After loading simply Click at the main screen ("click to start")
3. Now you are in the game... just in case wait few seconds... You can move with arrows Left/Right and go to build slots (white dots) and complete it by arrow Up. This action leads to freeze when it is done during the save process. 

I set auto-saving almost every second so at the max 2-3 tries you will simulate it at 100%. I often make it at the first try. This is the easiest way I can come up with to simulate this error.

To make it more clear I also add my YT video of simulation where you can see it is really easy process to follow up.
https://youtu.be/pJ_Y9xEvgjI

## Observed result

During the saving, game is freeze and nothing helps it has to be closed via ALT+F4.

## Expected result

Complete save action and save everything correctly without freeze. No matter what is going/changing in the game.

## More details

I tested more exports and it is not related to it. I mean it happened to me in preview directly in C3, in exported APK, NW.js, etc.

I am not sure about C3 version because it must be older thing. I can say for sure that this problem was even in 285.3 stable and still happening in every newer version even in the latest beta.

## System details

Every time an error occurs this bug message is written to the console.
![bug](https://user-images.githubusercontent.com/44697344/183432926-3e42b7e6-7a4c-428a-8f97-aa5f91fa88a9.png)

<details><summary>View details</summary>

Platform information
Product: Construct 3 r304 (beta)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 3.8 gb (2.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I had a look but I'm afraid such complex projects are basically impossible to debug.

By the time the crash happens, the internal state is already corrupted. To fix the problem we need to identify when the internal state first becomes corrupt. But with a huge project with 3000+ events this is infeasible. This is why we ask for minimal projects: it's generally impossible to help unless we have that.

I'm afraid as it's not possible to help in this case, I'm closing this report. As per the bug report guidelines the best way forward is to try to reproduce this in a minimal project.

**Comment by UbruPro123** [comment]
So finally after a long search I found the place where the problem is.
In the action I simulated, the values in the array is changing and also saving as JSON and there was also action Wait 1 sec. I disabled Wait and there is no more problem. So it was the interplay of saving and waiting at the same time in a specific situation because it doesn't cause a problem elsewhere.
