### ISSUE TITLE
Animation Playing is not restored if was stopped before loading game

### ISSUE THREAD

**Issue by MihaMS** [Scirra/Construct-3-bugs#5971]
## Problem description

Sprite Animation Playing is not restored if was stopped before loading game

## Attach a .c3p

https://drive.google.com/file/d/17SyzWAzd3G2ZEAo2FRBpNt9ruGF7NZsG/view?usp=sharing

## Steps to reproduce

1. Open and run attached c3p example file
2. Lightning animation is Playing, Press Save game button
3. Press Load Game button (Animation will be stopped and then game will be loaded)

## Observed result

Animation will stop.

## Expected result

Animation must play, as it was at Saving game moment.

## More details
---

**Affected browsers/platforms:** 

Tested only in Chrome

**First affected release:** 

r302 stable, not tested in previous releases

## System details

Windows 10

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
