### ISSUE TITLE
Cannot select multiple animation for pasting (to other objects)

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5972]
## Problem description

This may be a suggestion, but I think it should be within the expectations of what users are used to. 

Currently, copy and paste is supported for frames, but not for animation. I should be able to select/multi-select, copy and paste it into other objects animation.

![Snipaste_2022-08-09_08-05-26](https://user-images.githubusercontent.com/45864744/183535059-63867b0d-1303-4af6-9e70-d170bb696199.png)

## Expected result

1.  multi-select animation
2.  paste it into other objects animation.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Coincidentally the latest beta includes a related improvement and it is now possible to modify the properties of multiple animations at the same time as well as doing familiar multi select operation on the animations tree.

Copying animations between object types is still not possible, but a substantial amount of work towards that has already been made.

**Comment by DiegoScirra** [comment]
The next beta will include context menu options and keyboard shortcuts to cut copy and paste animations in the current and to other object types.
