### ISSUE TITLE
Template: Replica Fails to Enable behavior

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5973]
## Problem description

If the Template object is Disabled 'Orbit' / 'Rotate' / ’Fade‘/ 'MoveTo'.... behavior. Then the replaced object cannot set the behavior enabled Unless replaced object enabled behavior before the behavior is disabled.

No response to button click
![Snipaste_2022-08-09_08-28-13](https://user-images.githubusercontent.com/45864744/183537073-5cb2e0bb-5633-4a2d-9f1f-048e45a9f2ee.png)

## Attach a .c3p

[template-behavior-issue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9285812/template-behavior-issue.c3p.zip)

## Steps to reproduce

1. Create a Sprite, Add 'Orbit' behavior
2. **Disable 'Orbit' behavior**
3. Set Template mode as Template 
4. Copy a new Instance object, Set Template mode as 'Replica'
5. Try to Enable  'Orbit' behavior

## Observed result

![4](https://user-images.githubusercontent.com/45864744/183542666-6e2da5e3-a9c1-4d28-b99d-110055c0a6f4.gif)

## Expected result

![Snipaste_2022-08-09_09-02-25](https://user-images.githubusercontent.com/45864744/183540196-8627ce5b-faa2-4417-ad79-3dd3ed2a7e57.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r304 (beta)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 362 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Super with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.

Revision 17564.
