### ISSUE TITLE
r305 Crashes on Sprite Animation rename

### ISSUE THREAD

**Issue by StylianosK** [Scirra/Construct-3-bugs#5974]
## Problem description

I tried to change the name of an animation and C3 crashed

## Attached .c3p

https://drive.google.com/file/d/1u4Z3MN_qEGjzpt2XMwn5euDQims3GJav/view?usp=sharing

## Steps to reproduce

1. Open a sprite
2. Change the name of an animation

## Observed result

The software crashes and shows an Error log

## Expected result

I expected to rename the Animation successfully

Using
Chrome
Version 104.0.5112.79

Worked in r304 but broke in r305

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'iB') @ TypeError: Cannot read properties of undefined (reading 'iB') at wM.k9b.Alb (https://editor.construct.net/r305/projectResources.js:1913:347) at Array.tba (https://editor.construct.net/r305/projectResources.js:1909:147) at window.xab.dispatchEvent (https://editor.construct.net/r305/main.js:1090:42) at window.xab.Sr (https://editor.construct.net/r305/main.js:2349:85) at d.Ra (https://editor.construct.net/r305/projectResources.js:693:184) at d.gl (https://editor.construct.net/r305/projectResources.js:694:6) at https://editor.construct.net/r305/projectResources.js:244:318
Stack: TypeError: Cannot read properties of undefined (reading 'iB') at wM.k9b.Alb (https://editor.construct.net/r305/projectResources.js:1913:347) at Array.tba (https://editor.construct.net/r305/projectResources.js:1909:147) at window.xab.dispatchEvent (https://editor.construct.net/r305/main.js:1090:42) at window.xab.Sr (https://editor.construct.net/r305/main.js:2349:85) at d.Ra (https://editor.construct.net/r305/projectResources.js:693:184) at d.gl (https://editor.construct.net/r305/projectResources.js:694:6) at https://editor.construct.net/r305/projectResources.js:244:318
Construct version: r305
URL: https://editor.construct.net/r305/
Date: Tue Aug 09 2022 22:29:15 GMT+0300 (Eastern European Summer Time)
Uptime: 58 s

Platform information
Product: Construct 3 r305 (beta)
Browser: Chrome 104.0.5112.79
Browser engine: Chromium
Context: webapp
Operating system: macOS 12.5.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by alastajj** [comment]
I have the same bug in my project. I duplicated an animation, then after I renamed it, there was a crash.

**Comment by DiegoScirra** [comment]
This was a regression introduced in r305. Will be fixed for the next beta.

Revision 17568.

**Comment by AshleyScirra** [comment]
Leaving open with 'fixed' tag in an attempt to reduce duplicates.

**Comment by alastajj** [comment]
> Leaving open with 'fixed' tag in an attempt to reduce duplicates.

is it difficult to release hotfixes?

 Working with sprites is a common thing in construct, so sitting on this fix for a common crash, seems strange from a user perspective.
