### ISSUE TITLE
Sprite load image from binary object url changes all sprites of same object type

### ISSUE THREAD

**Issue by driesdriessen** [Scirra/Construct-3-bugs#5975]
## Problem description

When loading a sprite image from a binary object's url In a project with multiple instances of a specific sprite, all sprites get the new image, not just the selected one

## Attach a .c3p

[loadfrombinarybug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9295856/loadfrombinarybug.c3p.zip)

## Steps to reproduce

1. Create multiple instances of a sprite and assign a different value to an instance variable to tell them apart.
2. Load image data in a binary object.3. 
3. Select one of the sprite instances (via the instance variable) and load an image from URL using the URL of the binary object

## Observed result

All sprites are updated with the new image

## Expected result

Only the selected sprite gets the new image

## More details

**Affected browsers/platforms:** Chrome 103.0.5060.134 on OSX 12.5

**First affected release:** C3 R304 beta

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by driesdriessen** [comment]
I'm not sure this report was saved properly. I added the details as instructed in the template but somehow they don't show in the summary above. When I edit the problem details I see my full description.

**Comment by AshleyScirra** [comment]
You wrote all your content inside comments (between `<!--` and `-->`) which are hidden. I removed the comment marks so it displays correctly.

This is not a bug. It's by design that sprites all share the same set of images, and when you load an image, you replace one of the images shared by all instances.

**Comment by driesdriessen** [comment]
Thanks for the quick and patient reply. I should have known this is how sprites work. And apologies for being clumsy with the content.
I will use animation frames for showing different images.
Dries.
