### ISSUE TITLE
'\n' Can't work in events but available in editor properties.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5982]
## Problem description

This problem has been bothering me for a long time, because the expressions of `& newline &` are really cumbersome for long texts.

I can use `\n` in the editor properties
![01](https://user-images.githubusercontent.com/45864744/184062368-90215c1c-50a7-4e81-b891-98cdd6d77434.png)

But in the event, it doesn't work
![03](https://user-images.githubusercontent.com/45864744/184062407-1e662b34-65e7-4dd4-b14f-0aea1bee1cdf.png)

![02](https://user-images.githubusercontent.com/45864744/184062429-4272935c-3897-4c9d-bda0-649c04497288.png)

## Attach a .c3p

[newline-issue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9306008/newline-issue.c3p.zip)

## Steps to reproduce

1.
2.
3.

## Expected result

I think '\n' should work in strings anywhere. include strings variables

![Snipaste_2022-08-11_12-10-32](https://user-images.githubusercontent.com/45864744/184063517-37b037d0-c146-47ef-be2a-b49027d80cec.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is not a bug: it's just that properties and string expressions use different escape sequences. It is a little unfortunate, but it's probably too difficult to change now without breaking thousands of existing projects, as at the moment any backslash in a string expression works normally, but implementing this would make that work differently.

**Comment by XHXIAIEIN** [comment]
Honestly, '\n' is common in most computer languages, and there are probably thousands of existing projects that parse it themselves just for newlines. implementing it is a very good thing.

**Comment by XHXIAIEIN** [comment]
Someone submitted a suggestion here:
https://construct3-21h2.ideas.aha.io/ideas/C321H2-I-325
