### ISSUE TITLE
Add 'Open new version' button When open a newer version of Project from old version

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5983]
## Problem description

Currently, the link of this dialog is easy to ignore, and it is not easy to know that this link can jump to the new version. For some new users, this is an editor error warning that the file is corrupted, rather than an update prompt.

![Snipaste_2022-08-11_15-42-55](https://user-images.githubusercontent.com/45864744/184087882-a8e9fefe-8b31-46ff-89ff-eed203c46bfe.png)

## Observed result

I have met a lot of new users and I had to explain to them that it's just that your editor version doesn't match the project version, Don't worry, this isn't your problem. you can try to open it with the beta version.

## Expected result

So. I think a button should be added to help users jump directly to the new version.

![Snipaste_2022-08-11_15-46-11](https://user-images.githubusercontent.com/45864744/184088860-5f006173-c107-48e4-91f9-3bf06d4ed3aa.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is a suggestion so please post as a feature request. FWIW I'm sceptical many ordinary users would see that prompt. In practice I think it only happens if you save a project with a beta release and share it with someone on a stable release.

**Comment by XHXIAIEIN** [comment]
a stand-alone button is much more visible than text in different colors hidden in a bunch of text. 

> In practice I think it only happens if you save a project with a beta release and share it with someone on a stable release.

Yes. You kown Because I'm a big fan of beta versions, sometimes I make a projects in beta for others. But they prefer to use the stable version.
