### ISSUE TITLE
Whitelist UnityAds3 4.3.0 cordova Plugin (Interestials and Reward Videos Not Showing Fix)

### ISSUE THREAD

**Issue by artemisoftnian** [Scirra/Construct-3-bugs#5986]
Hi Ashley,

I just update my cordova UnityAds3 plugin to 4.3.0 : com-artemisoftnian-plugins-unityads3@4.3.0
Please put me in the flow if can be whitelisted.

Thanks in advance as always!

**Comment by AshleyScirra** [comment]
Added to build service.
