### ISSUE TITLE
Tab-clicking through an auto-selected hierarchy instance leaves instances selected

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#5987]
## Problem description

When you have a hierarchy set to `Select mode: All` or `Select mode: Wrap` overlapping another object, and you hold tab and click on the hierarchy (which selects all instances in the hierarchy), and then tab-click again to select the object under the hierarchy, un-clicked instances in the hierarchy remain selected in addition to the object buried below the hierarchy. You must manually deselect each hierarchy instance in order to exclusively select the buried object. 

_(As a side note on the workflow here, there is no way to manipulate the transform on a buried object once you've selected it other than using the arrow keys to nudge it. It would be preferable if the selection of a buried object remained intact until the user deselects it by clicking in empty space or clicking another object in a place it's not overlapping, so the mouse can be used to translate, rotate and scale the selected object or hierarchy. I'll add this as a suggestion, but I wanted to mention it here too.)_

## Attach a .c3p
[HierarchySelectionWoes.zip](https://github.com/Scirra/Construct-3-bugs/files/9330064/HierarchySelectionWoes.zip)

## Steps to reproduce

1. Create a hierarchy with a couple sprites, and set the hierarchy's selection mode to "All" or "Wrap."
2. Create another, stand-alone sprite and send it to the bottom of the layer.
3. Position the hierarchy so one of its sprites overlaps the stand-alone sprite.
4. Hold tab and left click twice where the stand-alone sprite and one hierarchy instance overlap to cycle selection between them.

## Observed result

The entire hierarchy is selected on the first click (which is expected), but on the second click, the stand-alone sprite and the un-clicked hierarchy instance(s) remain selected.

## Expected result

The entire hierarchy should be deselected on the second click, not just the overlapping instance, and only the stand-alone sprite should be selected.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r305 (beta)
Browser: Chrome 104.0.5112.81
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 1.1 tb
Storage usage (approx): 54 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by F3der1co** [comment]
#5646 
yea, I made a similar report to your workflow suggestion a while back.

**Comment by Scoremonger** [comment]
@F3der1co Yeah, exactly - same issue. I'm sure lots of people run into it. I can understand if it's too complicated/risky for Scirra to change, but there's definitely a workflow problem there and RE: the response you got, I don't think there's a risk of users getting their selection stuck if it's implemented as suggested [here](https://construct3-21h2.ideas.aha.io/ideas/C321H2-I-423). Let's hope it gets addressed eventually!

**Comment by AshleyScirra** [comment]
This is currently by design. This is just two separate features (auto-select of hierarchy, and tab changing to selecting something underneath) that don't work together in the way that you want. It works the same not using hierarchies if you just have normal objects, you select a few, and then you hold tab and click part of the existing selection to select something underneath. You can however hold Alt while first selecting something in the hierarchy to select just the thing you click on, temporarily disabling the hierarchy select mode.

Changing this is a feature request, and it would be a difficult one for usability. If Construct is meant to automatically know to unselect the hierarchy, then it's difficult to actually identify that against similar cases where the user intentionally selected other content, and therefore in that case unselecting it all will go against the user's intention. Further, remembering the previous actions and acting differently afterwards makes selections stateful (i.e. the way selections and keyboard shortcuts work changes depending on what you've done previously), which opens its own usability can of worms - it would mean if you forgot what you just did, or you did something by accident, you can't predict what your next interaction will actually do. It's a tough one that will need to be carefully considered in any feature request.

**Comment by Scoremonger** [comment]
I see, makes sense. Thank you for describing some of the issues you see in making a change to this. My expectation was that unless I explicitly make a selection of a subset of objects in an auto-selected hierarchy it would be treated as a single object. This seems the most intuitive behavior to me, but I appreciate the complexity of the problem. If I write up a suggestion for a change to that aspect of selection I'll be sure to take those issues into account.
