### ISSUE TITLE
Construct crashes when unchecking "Use collision" in the tile properties in a tilemap

### ISSUE THREAD

**Issue by baptiste-chiocca** [Scirra/Construct-3-bugs#5988]
## Problem description

Construct crashes when unchecking "Use collision" on a tile in a tilemap

## Attach a .c3p

https://drive.google.com/file/d/1B6jOcGzy_p5Vb6oq6L6e-dULjirR_xyP/view?usp=sharing

## Steps to reproduce

1. Double click on a tile in the tilemap window
2. Uncheck "Use Collision" in the tilemap properties

## Observed result

Construct crashes.

## Expected result

Construct should not crash.

## More details

Browser : Chrome & Firefox

**First affected release:** 

Works in r304, broke in r305

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r305/main.js, line 1392, col 166
Message: Uncaught TypeError: Cannot read properties of null (reading 'Paa')
Stack: TypeError: Cannot read properties of null (reading 'Paa') at lq.g.J.nab.ME (https://editor.construct.net/r305/main.js:1392:166) at HTMLInputElement.Ur (https://editor.construct.net/r305/main.js:1389:426)
Construct version: r305
URL: https://editor.construct.net/r305/
Date: Sat Aug 13 2022 12:48:49 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 9.9 s

Platform information
Product: Construct 3 r305 (beta)
Browser: Edge 104.0.1293.47
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.47
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
