### ISSUE TITLE
Tilemap eraser problem

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#599]
## Problem description

Everytime i want to erase a tile from a tilemap i need to select the eraser tool in the tilemap bar and select a random tile from the tilemap for it to work, if i only select the eraser tool without selecting a tile it won't work.
It's not necessarily a bug, but it doesn't used to work like that in C2.

## Attach a .c3p

[Tilemap bar eraser bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1134292/Tilemap.bar.eraser.bug.zip)

## Steps to reproduce

1. Select the eraser tool in the tilemap bar.
2. Try to erase a tile from the tilemap.
3. Select the eraser tool in the tilemap bar and a random tile.
4. Try to erase a tile from the tilemap again.

## Observed result

It's only possible to erase a tile if a random tile is selected.

## Expected result

Be able to erase a tile without selectin a random tile.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r45
