### ISSUE TITLE
Bug with timer and objects pick

### ISSUE THREAD

**Issue by TecenGOD** [Scirra/Construct-3-bugs#5991]
## Problem description

In my example, there are 3 copies of Sprite that have a VAR variable with values 0-1-2. At the beginning of the scene, I start a regular timer for 0.5 seconds. When the timer is triggered, I pick Sprite2 objects that have the same VAR variable.
All sprite2 should spawn "particles", but it does not create correctly.

## Attach a .c3p

.c3p - https://www.dropbox.com/s/t7c9m0sgns4myou/timerBugC3.c3p?dl=0

## Steps to reproduce

1. Run .c3p
2. See the wrong particle spawn

## Observed result

![timerBugC3_bug](https://user-images.githubusercontent.com/7480088/184605138-7f32a063-2419-410d-b1ee-dfda23f7ec27.png)

## Expected result

![timerBugC3_nobug](https://user-images.githubusercontent.com/7480088/184605189-37af5bd7-79a7-4ea0-a9e0-337f4d3afddb.png)

## More details

Platform information
Product: Construct 3 r302 (stable)
Browser: Edge 104.0.1293.47
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.47
Language setting: en-US

**Comment by AshleyScirra** [comment]
This is not a bug: as documented in the [Timer behavior manual entry](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/timer), 'On timer' can run with multiple instances picked, but your events act as if only one is picked. Adding *For each* as the manual description recommends fixes your events.
