### ISSUE TITLE
Platformer Behavior stutters while moving

### ISSUE THREAD

**Issue by scribbleisback** [Scirra/Construct-3-bugs#5992]
Any time I try to control a character with the platform behavior, it doesn't move. It stutters.  This happens with literally any c3p with the platformer behavior, including the examples. Just open any example with the platform behavior, i.e. kiwi story.

**Comment by AshleyScirra** [comment]
It works fine for me, and as far as I'm aware, everyone else. Please follow the bug report guidelines otherwise it's impossible for us to help.
