### ISSUE TITLE
Admob crash Android12 (easy fix)

### ISSUE THREAD

**Issue by fredriksthlm** [Scirra/Construct-3-bugs#5996]
## Problem description

Since Cordova updated to target 32, all apps with Admob will crash for users with Android 12.

## Steps to reproduce

1. Just export a project with Mobile Advert
2. Do not change any versions
3. Run it on a Android phone with Android12, and it will crash

## Observed result

It wil crash when lanched on a phone with Android12, 
**_Fatal Exception: java.lang.IllegalArgumentException_**

## Expected result

No crash.

## More details

There is a very simple thing you need to do, just bumb the version of the Admob cordova version you are using and this will fix itself wihtout any development needed.

The crash and when it was fixed is desbrived here:
https://developers.google.com/admob/android/rel-notes

This will fix itself if you bumb the Admob cordova version:
https://github.com/admob-plus/admob-plus/blob/master/packages/cordova/CHANGELOG.md

So bumb to 1.28.

More info on affected users:
https://www.construct.net/en/forum/construct-3/general-discussion-7/android-studio-gradle-wrapper-171411?kws=
https://www.construct.net/en/forum/construct-3/general-discussion-7/stability-errors-play-console-171846

Users that do not build with C3 build service they can easily amend version themselves..

**Affected browsers/platforms:** 

Only Android 12.

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Updated admob-plus to version 1.28.0
