### ISSUE TITLE
Changing the blending mode of a sprite while the timeline bar is visible crash

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5997]
## Problem description

if you change the blending mode of a sprite while the timeline bar is visible, Construct crashes

## Attach a .c3p
[crashTest.zip](https://github.com/Scirra/Construct-3-bugs/files/9351226/crashTest.zip)

## Steps to reproduce
1. make sure the timeline bar is visible
2. change the blending mode of the sprite

## Observed result
crash

## Expected result
no crash

## More details
Error report information
Type: unhandled exception
File: https://editor.construct.net/r305/main.js, line 901, col 388
Message: Uncaught TypeError: expected array
Stack: TypeError: expected array at P.Ob (https://editor.construct.net/r305/main.js:901:394) at y1 (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:31:463) at x5.kTb (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:505:214) at x5.Jwc (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:505:118) at Array. (https://editor.construct.net/r305/components/bars/timelineBar/timelineBar.js:501:288) at window.xab.dispatchEvent (https://editor.construct.net/r305/main.js:1090:42) at Nbb (https://editor.construct.net/r305/components/bars/propertiesBar/propertiesBar.js:2:310) at d.Paa (https://editor.construct.net/r305/components/bars/propertiesBar/propertiesBar.js:109:136) at Array. (https://editor.construct.net/r305/components/bars/propertiesBar/propertiesBar.js:96:118) at CCG.Zg.g.J.Nsa.dispatchEvent (https://editor.construct.net/r305/main.js:1090:42)
Construct version: r305
URL: https://editor.construct.net/r305/
Date: Tue Aug 16 2022 15:03:57 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 128.6 s

Platform information
Product: Construct 3 r305 (beta)
Browser: Chrome 104.0.5112.81
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
**Affected browsers/platforms:**

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta. The crash happens while auto-keyframing is turned on.
