### ISSUE TITLE
Inconsistent local variable behaviour when using keyboard vs gamepad

### ISSUE THREAD

**Issue by calminthenight** [Scirra/Construct-3-bugs#5998]
## Problem description

When using: (Keyboard on key pressed - Set local variable to X) and then attempting to check variable in same tick, event does not run.

When using: (Gamepad on button pressed - Set local variable to X) and then attempting to check variable in same tick, event runs as expected .

## Attach a .c3p

(https://1drv.ms/u/s!AkmrWgxeuxlKhJwEtVi9toLcNpPv3w?e=pxa8Ka)

## Steps to reproduce

Open Project.
Press Up Arrow on keyboard
Press D-Pad Up on gamepad
Observe different result

## Observed result

Local variable is not set/does not remain set for whole tick when using Up arrow to set.

## Expected result

Local variable should remain set for whole tick.

## More details

Controller is wired X360

**Affected browsers/platforms:** 

Issue appears in Chrome

**First affected release:** 

First identified in R302

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 104.0.5112.81
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 954 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is not a bug - you've just made a dependency on when exactly triggers run.

Triggers can run at any time during or outside of the normal top-to-bottom evaluation of events. Keyboard triggers happen outside of the event sheet evaluation and so don't change the text in your project. Gamepad triggers do happen during event sheet evaluation so do change the text in the project. In general triggers aren't guaranteed to run at any particular time and so you should avoid making events that depend on a particular ordering.

**Comment by calminthenight** [comment]
Interesting. I've made a bunch of control systems before using local variables and haven't come across this.

Could you explain why Keyboard triggers are outside of the Event sheet evaluation, while Gamepad triggers aren't?

From what you have said, the keyboard trigger must always take place post event sheet evaluation, prior to the next tick, so the local variable is set and then immediately reset at the beginning of the next tick prior to the event sheet evaluation. Otherwise it would at least work some of the time. Is that correct?

**Comment by AshleyScirra** [comment]
It derives from the fact the Gamepad API internally is a polling based API, whereas everything else uses an event model.

**Comment by calminthenight** [comment]
Ok, that makes sense. Thanks for explaining.
