### ISSUE TITLE
Closing on Android does not always prompt to save changes

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#6]
## Problem description

Original report: https://www.scirra.com/forum/press-back-button-lose-project-on-mobile_t189589

> Using Chrome Beta, so version 58.whatever, as long as you're in fullscreen, pressing back will bring up a prompt to let you know of unsaved changes. However, if you created a shortcut to your mobile desktop and open it from there, it doesn't give you an option to go full screen, so pressing back minimizes the window and restarts the engine upon bringing it back up.

I'd guess the swipe-to-close in task view would also not prompt.

I'm not sure if there's anything we can do about this, the browser may not give us a chance to save, or maybe even the Android OS doesn't give a chance to save. Probably should compare to other apps.

**Comment by shortercode** [comment]
I've seen some suggestion online that abusing the history API with the "popstate" event can suppress the back button, and in fact it may allow us to even implement some behaviour with the dialogs? I haven't tried this out yet though, so I guess the mileage may vary.

**Comment by AshleyScirra** [comment]
I think that just allows back to be pressed without leaving the page. The real problem is swipe-to-close in the Android task view, I don't think the Android OS allows a prompt at that point at all.

**Comment by shortercode** [comment]
Android doesn't offer any guarantee that any background activity will be kept open, even if it appears on the Android recent applications list and I don't expect activity life-cycle events to be appearing any time soon.

Also pressing **back** triggers different life-cycle states than pressing **home** / **recent**. **Back** seems to close web apps and tabs (if they have no history) but the **home** / **recent** just background the activity.

**Comment by AshleyScirra** [comment]
Will implement as per bug #174, closing this report.
