### ISSUE TITLE
crash when adding images from explorer

### ISSUE THREAD

**Issue by vtrixdev** [Scirra/Construct-3-bugs#600]
## Problem description

Crash when adding images from explorer (win10) (images are different size)
no direct steps for repro, but very recurrent
just dragging in images one for one

## Attach a .c3p

crash - [www.vtrixdev.com/scirra/bugs/imagebug.c3p](url)

## Steps to reproduce

1. just dragging in images (png) one for one in a new project
2.
3.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r44/main.js, line 61, col 123324
Message: Uncaught Error: invalid size
Stack: Error: invalid size at l.ǃPYq (https://editor.construct.net/r44/main.js:61:123330) at window.ǃPBs.ǃPYz (https://editor.construct.net/r44/main.js:61:110709) at window.ǃPBs.ǃPYt (https://editor.construct.net/r44/main.js:61:110957) at window.ǃPBs.ǃPYO (https://editor.construct.net/r44/main.js:61:110482) at window.ǃPYp.ǃPYm (https://editor.construct.net/r44/main.js:61:113368) at l.ǃPYm (https://editor.construct.net/r44/main.js:61:122374) at p.ǃPYm (https://editor.construct.net/r44/main.js:61:191894) at d.ǃzP.ǃpY (https://editor.construct.net/r44/main.js:61:382718) at d.ǃzP.ǃpY (https://editor.construct.net/r44/plugins/sprite/plugin.js:1:8611) at d.ǃzP.ǃp_ (https://editor.construct.net/r44/plugins/sprite/plugin.js:1:8411)
Construct 3 version: r44
URL: https://editor.construct.net/
Date: Mon Jul 10 2017 16:16:48 GMT+0200 (Romance Daylight Time)
Uptime: 283.7 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r44

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r45.
