### ISSUE TITLE
Whitelist plugins (New)

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#6000]
Hi,

Would you please whitelist the following plugins:

These plugins do not need to be maintained, I can control version updates from the plugin-side. Hopefully that helps with considering it to get whitelisted.

```JS
- chadori-google-admob-adcolony@0.0.1
- chadori-google-admob-applovin@0.0.1
- chadori-google-admob-chartboost@0.0.1
- chadori-google-admob-inmobi@0.0.1
- chadori-google-admob-ironsource@0.0.1
- chadori-google-admob-maio@0.0.1
- chadori-google-admob-meta@0.0.1
- chadori-google-admob-mytarget@0.0.1
- chadori-google-admob-pangle@0.0.1
- chadori-google-admob-tapjoy@0.0.1
- chadori-google-admob-unityads@0.0.1
- chadori-google-admob-vungle@0.0.1
```

I have followed the required guidelines to my knowledge, please let me know if there are issues with my request.
Thank you.

**Comment by AshleyScirra** [comment]
This is a lot. Do you really need them all? Do you actually have customers asking for each and every one of these networks? It would be much less work all round if you added them one by one as they were actually needed.

**Comment by Chadori** [comment]
Hi @AshleyScirra, yeah each network actually wins a bid sometimes, which increases overall revenue.

These do not need to get maintained though since I can do version bumps from the Addon SDK, would only need these to get approved once.

**Comment by Chadori** [comment]
Hi @AshleyScirra, I have removed the ones that do not perform well. Thank you.

**Comment by AshleyScirra** [comment]
Added to build service.
