### ISSUE TITLE
Window Height/Width expression is inaccurate

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#6011]
## Problem description

The NWJS window size expressions appear to be inaccurate.

And strangely, on my 4k monitor the sizes are way different. But on my 1080p monitor it's more accurate. 

It appears to me that the larger the window, the less accurate the result.

This bug makes it difficult to know exactly how big the game is running at. 

## 4k monitor

Here is the resolution of my monitor:
![scale](https://user-images.githubusercontent.com/5744908/185728781-e4199a81-4c76-48d4-95d8-2f1b442cee43.PNG)

And here is the claimed window size: 
![image](https://user-images.githubusercontent.com/5744908/185728777-8853b59a-e757-4894-8bdc-4a6bc19c7ae8.png)
yet when I measure the pixels in paint it says it's closer to 1050 x 620

And the inaccuracy is most obvious when I'm fullscreen, I would expect that because the window is filling the screen that it would show the monitor resolution, but it's closer to 3k instead of 4k

![asdf2](https://user-images.githubusercontent.com/5744908/185728849-72287683-71f9-4dea-a55f-395448849784.PNG)

This should say 3840 x 2160

## Attach a .c3p

[windowsize.zip](https://github.com/Scirra/Construct-3-bugs/files/9386228/windowsize.zip)

## Steps to reproduce

1. Export and run with NWJS
2. change window to various sizes
3. measure the accuracy of the displayed values with the actual pixel size

## Observed result

Window height/width are not accurate

## Expected result

Match the pixel size of the game, so I can know the size of the person's game

## More details

Regular NWJS 64 bit export with current build

latest c3 beta

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r306 (beta)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.3420000076293945
Logical CPU cores: 3
Approx. device memory: 1 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 2 gb
Storage usage (approx): 1.5 gb (74.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by alastajj** [comment]
I just looked at the system details, and perhaps it's related to the "device pixel ratio"

I'm not sure why my screen isn't saying "1".

But either way, shouldn't the window be giving an accurate pixel result regardless of the device's pixel ratio?

**Comment by AshleyScirra** [comment]
Construct just reports the values NW.js gives it. So if they're wrong for any reason, there's nothing we can do about it, and the issue would have to be reported to NW.js.

But what I suspect is happening here is that the value is given in CSS pixels, not device pixels, and the window has a device pixel ratio above 1. That could be due to the system default scaling option, a customised zoom level, or changed for some other reason that NW.js itself decided.
