### ISSUE TITLE
Unable to save project while network request is occupied (Working is stuck at 0%)

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6012]
## Problem description

Construct cannot save project(always at 0%) when the network is blocked.Network blocking means that the computer's network is normal, but only Chrome cannot access the network of certain reasons.

I can't reproduce the problem, but I know what's causing it.  

I using *Internet Download Manager* on my computer, and I'm [downloading something](https://www.screentogif.com/) (Click *Installer* button) on the web. But I have an unfinished IDM task dialog and my network is affected by VPN. Unable to create a new download task in IDM. So The new download request cannot be responded to because a download task in a session is blocking the system.

In this state, I can't save the C3 project.Ideally, Construct would work even when offline. After that I also tried to use `ipconfig /flushdns`, close VPN, turn off WIFI network. still can't solve

It stays stuck at 0%  
![Snipaste_2022-08-20_16-45-53](https://user-images.githubusercontent.com/45864744/185760197-b3f9fc71-a7d7-4298-8d6a-9ed517670b9e.png)

Console error:  
![Snipaste_2022-08-20_16-46-01](https://user-images.githubusercontent.com/45864744/185760213-427c6842-36b0-4650-8065-082bef8ef2d9.png)

Waiting for a long time, about ten minutes. C3 prompted unable to save, restored the editor page and I can retry to save it. Then I tried renaming .c3p to a new file, and also tried saving it as a local folder, but it still wouldn't save.

Finally I closed all the applications on my computer And I save the project using `Download a copy` in C3. it Can be worked. It was saved successfully. Then I restart my computer and all the work back to normal.

## Observed result

It stays stuck at 0%  
![Snipaste_2022-08-20_16-45-53](https://user-images.githubusercontent.com/45864744/185760197-b3f9fc71-a7d7-4298-8d6a-9ed517670b9e.png)

## Expected result

allow the user to interrupt the save task if the save process at 0% for a long time(timeout: 30 seconds). and use an alternate solution for emergency local saves.

## More details

**Affected browsers/platforms:** Chrome & PWA, Windows 11 

**First affected release:** r306

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r306 (beta)
Browser: Chrome 104.0.5112.101
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 411 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Super with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
In normal operation Construct should save itself for use offline, and then be able to work offline - which means features like save can happen without contacting the server at all. So assuming Construct managed to save itself to work offline, this should never happen - it will not need to contact the server to complete a save. Therefore I would assume Construct has not managed to save itself to work offline, and so it still needs to request some resources from the server; if the connection is busy or unavailable, then that process will not be able to complete.

I would suggest making sure you wait for the "ready to use offline" notification to avoid connection-related issues. If you are sure you've seen that notification and then you still have some issue using Construct offline after that, please file a new issue.
