### ISSUE TITLE
Hierarchy lagging under certain conditions

### ISSUE THREAD

**Issue by EydiavHamri** [Scirra/Construct-3-bugs#6014]
## Problem description

Moving an object and its child object in hierarchy, while snapped to grid lags terribly if child object is on bottom in Z-order
(video attached)

## Attach a .c3p

[SnapPlusZOrderPlusHierarchyBug.zip](https://github.com/Scirra/Construct-3-bugs/files/9387938/SnapPlusZOrderPlusHierarchyBug.zip)

## Steps to reproduce

1. In editor, send blue sprite "Sprite2" to bottom of layer
2. Select both sprites
3. Move them around with the mouse (bug doesn't reproduce if moved with arrow keys). Bug should already show itself. It gets more severe if moved quickly, or if you let go of the mouse button while moving it

## Observed result

Blue sprite lags behind, in some cases when you drop it, it will be placed way off where you expect it to.

https://user-images.githubusercontent.com/44640946/185764554-2ee3691d-4893-44b0-bdc3-bab297a58799.mp4

## Expected result

I expect it to follow mouse movement without lag, like it does if it's on the front of the layer

## More details

**Affected browsers/platforms:** 
Microsoft Edge 104.0.1293.54 (64-bit)
Google Chrome 104.0.5112.102 (64-bit)
Mozilla Firefox 103.0.2 (64-bit)

**First affected release:** 
Worked in [r288](https://editor.construct.net/r288/) but broke in [r289](https://editor.construct.net/r289/)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r306 (beta)
Browser: Chrome 104.0.5112.102
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 210 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
It looks like this is related to what was fixed for issue #5585. The revision number is 16933.

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
