### ISSUE TITLE
Google Billing 3 - not supported

### ISSUE THREAD

**Issue by fredriksthlm** [Scirra/Construct-3-bugs#6016]
## Problem description

According to Google they do not accept any new apps with GoogleBilling below v4, since 2 August 2022. Updates to old apps are still allowed until November 2022.

When we build an app from Construct3 using Mobile IAP, we still get Google Billing3.

## Steps to reproduce

1. Create new project
2. Add Mobile IAP
3. Export

## Observed result

The export uses
`<plugin name="cordova-plugin-purchase" spec="10.6.1" />`

## Expected result

The export to use at least 
`<plugin name="cordova-plugin-purchase" spec="11.0.0" />`

## More details

Here is the link to Google, where it states Billing3 is deprecated, and minimum v4 should be used:
https://developer.android.com/google/play/billing/release-notes

Here is the release notes for the cordova plugin:
https://github.com/j3k0/cordova-plugin-purchase/blob/master/RELEASE_NOTES.md

Bumbing the plugin to v11 (GoogleBilling4) should be possible without any development, since it is no breaking changes. But you should still test all events.

Also note that they have already updated the plugin to v12, for support of the brand new GoogleBilling 5. But this is not in npm yet.
But I believe you should start to update and test, also for a bigger update for this.

**Affected browsers/platforms:** 
This only affetcs Android, when uploading builds to Google Play.

**First affected release:** 
All C3 releases affected.
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Updated to `cordova-plugin-purchase@11.0.0` for the next beta - their release notes say it should be backwards compatible, hopefully they're right!
