### ISSUE TITLE
Touch scrolling moves events and actions. 

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#602]
## Problem description

When using a touch capable device to scroll in event sheet, action and events are picked and moved. This happened several times for me and broke some projects until I found out the reason.

## Attach a .c3p

N/A

## Steps to reproduce

1. Open any project on a touch capable device.
2. Go to a long event sheet.
3. Scroll with touch through the event sheet.
4. If your finger is on an action or condition when you start to scroll, a black line appears under and the action is picked and moved to where you stop scrolling.

## Observed result

Actions and conditions are picked and moved when scrolling through event sheet.

## Expected result

Preferably nothing should be picked up when scrolling with touch. Maybe a delay or hold action would prevent this? This can break projects if you're not careful where you touch when scrolling.

## Affected browsers

* Chrome: yes

**Comment by tunepunk** [comment]
Any fix for this coming soon? I keep breaking my projects and have to reload after scrolling event sheet using touch. 

Black line appears, and sometimes moves events and actions around when scrolling.

**Comment by tunepunk** [comment]
By the way, is the movement of elements in the event sheet triggered by something specific? Any special pointer event for that? 

The was a setting in about:flags to turn off stylus scrolling on pointer down, so this is my last an final issue regarding pen/touch input (at least in chrome) Everything else seems to be working flawlessly now.

Touch/Pen as main input is a pure pleasure in C3(Chrome) except for this little quirk now.

**Comment by tunepunk** [comment]
[**Touch initiated drag and drop Windows, Chrome OS**
Touch drag and drop can be initiated through long press on a draggable element. #enable-touch-drag-drop]

This flag in chrome didn't seem to help the behaviour of moving events while scrolling. So I'm guessing this is a C3 issue.

**Comment by AshleyScirra** [comment]
I've made a fix for this in the next build. Let's check it again then and see if it works for you.

**Comment by tunepunk** [comment]
Awesome news, thank you! cant wait to try it out.

**Comment by AshleyScirra** [comment]
r65 is out now, can you verify it works better?

**Comment by tunepunk** [comment]
Can verify this works perfectly now thanks. Touch is no longer grabbing events and moving them around while scrolling. Good job. Issue can be closed.

**Comment by AshleyScirra** [comment]
Thanks for confirming.
