### ISSUE TITLE
Timeline Tags

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#6020]
## Problem description
If a timeline has two tags and one is already used by other timelines, in the situation of the Bugreportfile it makes a difference which tag I use to make the timeline resume playing. 
Its very possible that I misunderstand the way the tags work. 

## Attach a .c3p
[TimelineTag.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9394209/TimelineTag.c3p.zip)

## Steps to reproduce

1.please preview the project. Two identical timelines are played in exchange, this is the way its intended to look like
2.now deactivate the actions "resume Z" and "resume Z2", and activate the two "resume aktiv" actions
3.preview the project again and compare. The pink sprite is only there to see the difference

## Observed result

step 1 looks different than step 3
## Expected result

I think it should look the same.  
## More details

I stopped the additional timelines after they ran once, but I noticed that "set time" stops them automatically, so I deleted the "stop" actions.

**Affected browsers/platforms:** 

**First affected release:** 
I tested in chrome on mac, r306
## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r306 (beta)
Browser: Chrome 104.0.5112.101
Browser engine: Chromium
Context: browser
Operating system: macOS 11.6.8
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 243 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 560 OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
The reason for the difference is directly related to the way tags work.

In this example you have two timelines tagged **"aktiv Z"** and **"aktiv Z2"**, when you use the tag **"aktiv"** with any of the actions that support tags, you are telling C3 to perform that action on all timelines with that tag.

So **Resume "aktiv"** is resuming both timelines when ever it is used.

This part of the documentation talks about this system of tagging, it's for Tweens, but tagging Timelines works exactly the same

https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/tween

**Comment by bubbblebub** [comment]
thanks a lot for the explanation!

Von meinem iPhone gesendet
