### ISSUE TITLE
Cursor is over object, terrible performance

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6025]
## Problem description

Cursor is over object has terrible performance

## Attach a .c3p
[CursorTest.zip](https://github.com/Scirra/Construct-3-bugs/files/9401513/CursorTest.zip)

## Steps to reproduce
1. preview in the debugger 
2. check cpu usage of the different event groups

## Observed result
Cursor is over has a performance cost magnitudes over the other event groups

## Expected result

About the same performance as on collision (collision cells) or only checking on screen objects (as you cannot move the cursor over off screen objects ever afaik)

This optimization should also be made to the touch events I assume. (I did not test them)

_this seems to be an easy optimization that should be done by the cursor and touch events by default. This would bring huge performance benefits for games with a large amount of off screen clickable/hoverable elements, for example rts game etc._

**Comment by AshleyScirra** [comment]
This should be much faster in the next beta - all three approaches measure about the same performance for me after the optimisation. It basically now just uses an internal viewport check as a faster way to discard offscreen instances, as well as a couple of other tricks. This has been applied to both 'Cursor is over object' and 'Is touching object'.

**Comment by F3der1co** [comment]
awesome!

**Comment by F3der1co** [comment]
btw, am I misunderstanding or is there a reason these optimizations are not done to the trigger events?

mouse: 
on object clicked
touch: 
on tap object, on hold over object, on double-tap object, on touched object

**Comment by F3der1co** [comment]
> 

So I just tested the new version and for me collision cells is still much faster in all cases? 
Is there a reason this is not used?

**Comment by AshleyScirra** [comment]
Using the provided project, the *cpuTest* group measures about 1.5% CPU in the debugger, and *cpuTestOnCollision* measures about 3%. So it looks to me like it's actually the other way round. Also either way, a couple of percent CPU usage to test thousands of instances is pretty good, and so at some point you get to the threshold of performance being good enough and further efforts would just be adding extra complexity for negligible gain.

**Comment by F3der1co** [comment]
interesting as these are my measurements (with some slight fluctuation):
![interesting2](https://user-images.githubusercontent.com/89512047/190193821-8975d916-9307-4a71-aa23-b71d1526a60b.png)

One way I can get the group cpuUsage lower is by moving the mouse off screen (then it becomes 0%, which is a cool optimization)
