### ISSUE TITLE
Export to Webview (windows) - Layout offset until window resized

### ISSUE THREAD

**Issue by andygilbert29** [Scirra/Construct-3-bugs#6027]
## Problem description

When I exported my project to windows webview (not NW.js) the layout was offset until the window was resized, then the layout would jump to the correct position. I then tried a new project with a button in the center of the layout and this exported OK. 

So I slowly removed things from my project with a hope to find what was causing it but nothing correct it. I kept going until NOTHING was left, not object, files or events. I then added a button to the center and yet it still does it. 

The attached example is the said project with a button in the center. I have attached the c3p and the exported webview. 

## Attach a .c3p

[Webview_issue.zip](https://github.com/Scirra/Construct-3-bugs/files/9415066/Webview_issue.zip)

## Steps to reproduce

1. Export to Webview (not NW.js)

## Observed result

Layout is offset to the bottom left until your click to resize the window, then it jumps to position.

## Expected result

Layout should be centred

## More details

**Affected browsers/platforms:** 

Windows

**First affected release:** 

R302 Stable

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 104.0.5112.102
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 455 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It looks fine to me in the latest beta. Have you tested it in r307? (The guidelines request that you always test with the latest beta to avoid reporting issues we may have already fixed)

**Comment by andygilbert29** [comment]
> It looks fine to me in the latest beta. Have you tested it in r307? (The guidelines request that you always test with the latest beta to avoid reporting issues we may have already fixed)

Apologies regarding version. 

Just tested with latest Beta on the same PC and the issue remains. I will try it on a different computer later today.

**Comment by AshleyScirra** [comment]
Just tried again, still looks absolutely fine to me. Can't see anything wrong. I'm afraid there's nothing we can do unless we can reproduce the problem.

I'd suggest installing any available software updates for your system, in case this is something like a WebView bug that Microsoft already fixed.

**Comment by pandabear7413** [comment]
I'm getting the same issue with my project.  I can also reproduce this issue with the export @andygilbert29 attached on all 4 of my laptops:
- 1 Dell (1 month old) running Windows 10
- 2 HP's running Windows 10
- 1 HP running Windows 7

Here are before and after screenshots of the window.  'After' is the result of adjusting the size of the window a tiny bit by grabbing/moving the window handles.  The change happens immediately.

Can you please reopen the issue?  

before:
![beforeResize](https://user-images.githubusercontent.com/85074714/188769252-72003f5b-bf29-4a14-9418-3db9c1166f7d.jpg)

after:
![afterResize](https://user-images.githubusercontent.com/85074714/188769251-5aecfd2c-d29c-4859-b170-54aae4ebc0bb.jpg)

**Comment by AshleyScirra** [comment]
I tried again and it still works fine for me. I'm afraid as per the bug report guidelines there's little we can do unless we can reproduce the problem.

I'd suggest installing any available software updates for your system, in case this is something like a WebView bug that Microsoft already fixed.

**Comment by pandabear7413** [comment]
@AshleyScirra So just to clarify, are you saying that when you run the attached exported project, the button is in the center of the window at startup like in the 'after' screenshot (and not skewed to one side like in the 'before' screenshot)?  

I understand you cant do anything if you can't reproduce the issue, but I'm surprised it's not happening on at least one of your machines given how it's happening on all of mine.  FYI I have the latest Windows updates on at least one of the machines, the others may be a little older, but I get the same behavior on all of them.  I also uninstalled/reinstalled WebView2 on the new machine but am still having the issue.

**Comment by andygilbert29** [comment]
Just downloaded this from here and tried this on another computer to my DEV pc and have a experiencing the same issue.

Window opens but shows NOTHING, as soon as I start to resize the window the button appears, its probably the same issue (but the button is so offset it is out of view)

This is another computer to the original.

There is clearly something going on...

**Comment by AshleyScirra** [comment]
I've tried on two desktop machines, one Windows 10 and one Windows 11, and they both work fine.

Given Construct runs pretty much the same code on all platforms, if something is wrong with one platform specifically (Windows WebView2 in this case), that suggests a problem with the platform, not Construct. So I suspect this is something wrong with WebView2 itself and not Construct. That's why I suggested installing all available system updates, maybe updating would help fix it.

**Comment by andygilbert29** [comment]
> Coincidentally I was doing some unrelated testing and spotted an offset window issue with WebView2 which looks like this issue. I looked in to a bit and it does look like a bug with WebView2 itself.
> 
> However the issue only occurred in DOM mode, i.e. with 'Use worker' set to 'No'. I found a way to work around the problem, but it only helps with DOM mode. The provided project does use a worker ('Use worker' is set to 'Auto' and it defaults to using a worker with that project). So it should not have been affected by the issue I saw - so it still doesn't make sense to me why you'd see this issue with the provided project.
> 
> The next beta has the workaround for DOM mode, so we can see if that somehow helps anyway - bug reports can often confuse specific settings/project files/etc so it may be that your own tests are in fact using DOM mode.

I can confirm that in my project was in DOM mode (which is required for this project).

Andy

**Comment by pandabear7413** [comment]
FYI I saw that Beta 310 has a possible fix for this, so I did a quick export to webview2 (64 bit only, minimal settings for time), and the window contents now fit properly.  I then did a 'full export' (deduplicate, advanced mini, 32 + 64 bit, webp) with Beta 311 and contents fit properly.  Very pumped this is addressed, thanks @AshleyScirra for fixing this!!
