### ISSUE TITLE
Animate MP4 portrait export

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#6028]
## Problem description

Mp4 export does not work properly in portrait view.
## Attach a .c3p
https://www.dropbox.com/s/w9ffzzupls2bof6/animatemp4portrait.c3p?dl=1

## Steps to reproduce

1.Export to Mp4 (30 seconds)
2.Preview export
3.

## Observed result
The video stops unexpectedly.

## Expected result

No stops
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This reproduces for me in Chrome 104 but not in Canary 107. The symptoms sound like this Chrome issue I previously filed which is still being worked on: https://bugs.chromium.org/p/chromium/issues/detail?id=1334234

Does it work for you in Canary 107?

**Comment by pigmalien** [comment]
Yes, it showed the full 30 seconds I exported it to.

**Comment by AshleyScirra** [comment]
OK, sounds like a Chrome bug that's fixed in Canary then.
