### ISSUE TITLE
Lost access to my local storage in Chrome

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6029]
## Problem description

I opened my C3 Chrome App and I cannot Open From Local Browser. I cannot Save To Local Browser either. Those 2 options are completely hidden. They do not appear in settings (only Cloud and Local File).

The only thing I remember doing is change the "Send 'Do Not Track'" option in chrome settings to On.

How to enable Local Storage again, please ?

**Affected browsers/platforms:** Version 104.0.5112.102 (Official Build) (64-bit)

**First affected release:**

**Comment by AshleyScirra** [comment]
It's intentional that in browsers that support local file saves, the local browser save option is hidden. This has been the case since local file & folder saves were introduced in late 2020.

**Comment by Alaadel** [comment]
> It's intentional that in browsers that support local file saves, the local browser save option is hidden. This has been the case since local file & folder saves were introduced in late 2020.

I don't understand. I have been using C3 as a Chrome App for a year now, and I have dozens of project saved in the local storage!

Now all of a sudden, they are gone, and the local save/open options (that were visible and functional 1 day earlier) are now hidden.

**Comment by Alaadel** [comment]
I rechecked C3 settings in Chrome, and I gave C3 all the necessary permissions, but I can't find anything related to Local Storage. Maybe Chrome removed this feature?

Also, does your comment mean that if I disable Local File Save it will re-enable the local storage option?
I just need access to my -now lost- local storage files so I can make a backup at least.

Any help please?

**Comment by AshleyScirra** [comment]
The local browser option will have been hidden since late 2020 unless there is already content saved to the local browser, in which case it keeps showing the option. The only reason I can think of that it would have disappeared is that you or your browser wiped its storage. This is part of the reason we now hide the option where possible - it's not a reliable place to save your work.
