### ISSUE TITLE
Webfont causes fonts to crash

### ISSUE THREAD

**Issue by Scott943** [Scirra/Construct-3-bugs#603]
## Problem description

*Enter a concise description of your problem here*
When I open the font menu, the program crashes with an red error message appearing. This could be because I have an imported web font in the mix.
## Attach a .c3p
- Any cp3 with a webfont
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.Import webfont
2.Click arrow by fonts
3.

## Observed result

*What do you see happen?*
error
## Expected result

*What did you expect to happen instead?*
no error
## Affected browsers

* Chrome: yes
* Firefox: 
* Edge:
* Safari: 

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*
**ERROR HERE**
<details><summary>View details</summary>

PASTE HERE
Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r44

Local storage
Storage quota (approx): 5.2 gb
Storage usage (approx): 277 mb (5.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

---------------------------------------------------------------------------------------------------

Error report information
Type: unhandled exception
File: https://editor.construct.net/r44/main.js, line 61, col 375561
Message: Uncaught Error: cannot load as font
Stack: Error: cannot load as font at n.ǃGf (https://editor.construct.net/r44/main.js:61:375567) at h.ǃKR (https://editor.construct.net/r44/main.js:61:90536) at ǃP.ǃo.ǃL.ǃSIE.e.ǃKb [as ǃSIY] (https://editor.construct.net/r44/components/bars/propertiesBar/propertiesBar.js:1:28777) at ǃP.ǃo.ǃL.ǃSIE.ǃSIk (https://editor.construct.net/r44/main.js:2:419261) at HTMLButtonElement.ǃSIu (https://editor.construct.net/r44/main.js:2:416561)
Construct 3 version: r44
URL: https://editor.construct.net/
Date: Mon Jul 10 2017 22:58:36 GMT+0100 (GMT Daylight Time)
Uptime: 203.4 s

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r44

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by AshleyScirra** [comment]
I can't reproduce from your steps, there is no project attached, and you did not include the crash message, so there's nothing I can do about this. Please follow the bug report guidelines as closely as possible to ensure we can actually fix the problem you report.

**Comment by Scott943** [comment]
@ashleyscirra Yes sorry about the unnattached .cp3 (I posted this late at night!) However, I believe I did include the crash report, under view details?

**Comment by AshleyScirra** [comment]
It looks like it's crashing because you've imported an invalid or corrupt font file. We can't reproduce this without the actual font file you are using. This is why we always ask for you to provide your project.

**Comment by Scott943** [comment]
@ashleyscirra Yes I see, that makes sense. However, my iOS export seems to function fine despite this, so I guess I will not bother to change it.
I will remember to put .cp3's on any future reports too. I just thought this was a generic problem that could be reproed with any blank .cp3 with a webfont, as it happened like that for me.

I can attach the project if you want, but I am still on holiday, so it would have to be when I'm back in a few days?

**Comment by AshleyScirra** [comment]
Yes, please do send us the file, we want to fix all possible crashes.

**Comment by Scott943** [comment]
@ashleyscirra Sure, will try do as soon as possible.

**Comment by Scott943** [comment]
OK @AshleyScirra , here is a very minimised project file in a zip. :)

[Sidecar Split (37).zip](https://github.com/Scirra/Construct-3-bugs/files/1173006/Sidecar.Split.37.zip)

For me, whenever I click on a text object, and then on the arrow beside 'Font' in properties, Construct throws out the aforementioned error.

**Comment by AshleyScirra** [comment]
OK thanks, I could reproduce and should be fixed for r47. Please remember it always helps to reduce your project to a minimal example.
