### ISSUE TITLE
Splash and Adaptive icon don't work in new beta

### ISSUE THREAD

**Issue by KekGames** [Scirra/Construct-3-bugs#6030]
## Problem description

On start-up you see cordova logo instead of the splash and the adaptive icon  when exporting to Android (I tested with signed AAB)

## Attach a .c3p

https://drive.google.com/file/d/1QQDoOU6pDEERL_WTGkRnzSQ9IAg7aYJy/view?usp=sharing

## Steps to reproduce

1. Export to android
2. Run the game

## Observed result

Cordova logo instead of the icon and splash when opening the game.

## Expected result

Adaptive icon and splash set in "Icons" folder

## More details

**Affected browsers/platforms:** Android

**First affected release:** Worked in stable but broke in r307

**Comment by AshleyScirra** [comment]
It doesn't work if you use uppercase characters in the splash image filename. This is fixed for the next release and you should be able to work around it already by using a lowercase filename for the splash image.

**Comment by KekGames** [comment]
![0-02-05-6f0627e8f849563f33ddb947e4a3ebac3c799fab2b137bf44bee009478833c80_d50f1215f392f9b2](https://user-images.githubusercontent.com/42392288/186640234-1b8c3841-9ae7-49d2-bc5b-c90606b995e2.jpg)
![96](https://user-images.githubusercontent.com/42392288/186640379-0b285a17-9ed0-4c54-ac1f-d135ab2ff687.png)
Ok, but there's a new issue: splash is now displayed with round corners instead of it's original shape.

**Comment by AshleyScirra** [comment]
No, that's what Android now does with splash images. Their design guidelines have more details.
