### ISSUE TITLE
Audio.Duration returns 0 if used immediately after Play

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6032]
## Problem description

Using Audio.Duration after Audio.Play returns 0. I must wait a few seconds in-between them.
In one project I had to wait >1 seconds, and in the attached project waiting 0.01 is enough.

## Attach a .c3p

[Audio Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/9418891/Audio.Bug.zip)

## Steps to reproduce

1. Run
2. Input any number of seconds to wait
3. Click the button

## Observed result

if you use 0, the Duration will show 0.
If you use 0.01 or more, Duration will work correctly.

## Expected result

Duration should work regardless of the waiting. Maybe add an event "On Started Playing"; so we know we can use Duration now.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Works for me. Looks the same as #5989 so closing as duplicate.
