### ISSUE TITLE
[Addon SDK] Project saved with a combo box item selected but no longer exists in plugin update, prevents preview to launch

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#6033]
## Problem description

Project saved with a plugin property combo box item selected but no longer exists in a new plugin update, prevents preview to launch, thus causing preview failure.

![image](https://user-images.githubusercontent.com/31282960/186637964-5d275cf4-e44e-4e82-a025-adaf7a314fe1.png)

Here is the error message from the console, just after receiving the alert dialog for `Failed to start preview`:

![image](https://user-images.githubusercontent.com/31282960/186638126-d999460c-7f3c-4354-9e76-7699595dcab0.png)

## Attach a .c3p

[Files.zip](https://github.com/Scirra/Construct-3-bugs/files/9423714/Files.zip)

## Steps to reproduce

This is to reproduce the error immediately, without having to go through the process of switching to a plugin update.

1. Install the addon `2_combo_items.c3addon`.
2. Open the project `2_combo_items_saved.c3p`.
3. Press `F4` to preview.
4. Observe the `Failed to start preview` alert dialog.

## Steps to reproduce the issue from a blank project

1. Install the addon `3_combo_items.c3addon`. 
This [blank] plugin only contains a plugin property with the following combo items: `["item1", "item2", "item3"]`.
2. Create a new project.
3. Add the object `New Plugin`, which is the object type name of `3_combo_items.c3addon`.
4. See that the initial combo plugin property value is `item1`.
5. Save project
6. Install the addon `2_combo_items.c3addon`, this is the same plugin as `3_combo_items.c3addon` but without `"item1"` in the plugin property combo list.
7. Open the recently saved project.
8. Press `F4` to preview.
9. Observe the `Failed to start preview` alert dialog.
10. Check the browser console for the error.

## Observed result

This might just be a regression. It seems the Construct 3 editor currently fails to fully adapt to missing combo box items in the plugin properties when an item is removed. Saved projects with more combo box items successfully load but fail to preview.

## Expected result

The Construct 3 editor seems to be already quite good at adapting to changes for missing or changed plugin properties. However, currently it seems there is a regression where the project loads but fails to preview when a saved project is detected to have a selected combo box item that no longer exists in a new plugin update/version.

**Comment by Chadori** [comment]
Thank you!

**Comment by AshleyScirra** [comment]
This kind of thing is difficult for backwards compatibility. It's not clear which other combo item should be selected if loading a project with a non-existent combo item, and changing it could also be a breaking change anyway.

Perhaps you could just remove the property and add it with a different ID?

**Comment by Chadori** [comment]
> Perhaps you could just remove the property and add it with a different ID?

Yeah, that works fine as well, thank you!

**Comment by Chadori** [comment]
Would closing this be fine?

**Comment by Chadori** [comment]
> Perhaps you could just remove the property and add it with a different ID? Then you also get to choose the new default.

Yeah, this certainly works much better since we can change the default. Thanks again.

**Comment by AshleyScirra** [comment]
Closing as developers should remove and replace instead (for properties - for ACEs use deprecation instead of removal to avoid breaking projects).
