### ISSUE TITLE
Text not displaying in preview, but is in debug. same code.

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#6034]
The text does not display properly when running preview, but the same code displays correctly in debug. Same code.

[## Attach a .c3p](url)
[new_menu_system_copy.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9425379/new_menu_system_copy.c3p.zip)

## Steps to reproduce

1.Just run file
2.
3.

## Observed result

![Screen Shot 2022-08-25 at 14 41 09](https://user-images.githubusercontent.com/30123541/186685896-2f6d5bfb-85d1-42f1-b043-e779c2692b64.png)

## Expected result

![Screen Shot 2022-08-25 at 14 41 21](https://user-images.githubusercontent.com/30123541/186685917-2ba1d0a1-b47b-4ce9-b1e6-8b408c4ec5dd.png)

## More details

**Affected browsers/platforms:** 

Chrome, mac

**First affected release:** 

Latest beta r307

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r307 (beta)
Browser: Chrome 104.0.5112.101
Browser engine: Chromium
Context: webapp
Operating system: macOS 10.13.6
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 260 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., ATI Radeon HD 5670 OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It doesn't reproduce for me in debug mode, but if I smoothly resize the window changing the scale, the last line sometimes flickers. So I think this is to do with the displayed scale, rather than the debugger specifically (the debugger just sometimes shows with a different scale).

The problem is you set the text object size to exactly the text height. You need to add a small margin to that, e.g. +10, to make sure there is room to render the last line. Otherwise as the scale changes, the browser text rendering adjusts the text size with some rounding or precision error, so sometimes it may be too large, and sometimes too small. Adding some padding vertically avoids that by just giving it enough room for some text size variation as the scale changes.

**Comment by mOOnpunk** [comment]
You are right, thanks, the padding worked.
