### ISSUE TITLE
PWA  Window Title bar does not start with the project name

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6036]
## Problem description

If Construct is used in PWA, the name of the window title bar does not start with the project name.

This is in Chrome tab:

```
New project - Construct 3
```
![01](https://user-images.githubusercontent.com/45864744/186812281-34c7d44b-7b04-4840-90cd-2b0605af258f.png)

This is in PWA:
```
Construct3 - New project - Construct 3
```
![02](https://user-images.githubusercontent.com/45864744/186812368-3d9da00f-1e3d-453f-8fe5-2954df1d4bf8.png)

## Observed result

When you have multiple projects open at the same time, you can't tell from the Windows taskbar which project is which.  

![03](https://user-images.githubusercontent.com/45864744/186812409-4fd1dc80-6de4-4c2b-a57b-4082b4dbae39.png)

![Snipaste_2022-08-26_11-41-00](https://user-images.githubusercontent.com/45864744/186812692-d6512f67-b9d9-442c-b43c-0819973b9c09.png)

## Expected result

Start with the project name
```
New project - Construct 3
```
![Snipaste_2022-08-26_11-48-39](https://user-images.githubusercontent.com/45864744/186813479-c8bef7ae-6993-4872-a7a9-e21e79713f1e.png)

## More details

**Affected browsers/platforms:** Chrome 104.0.5112.102 / window 11

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r307 (beta)
Browser: Chrome 104.0.5112.102
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 384 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by XHXIAIEIN** [comment]
Added:

When PWA is previewing, the window does not display the project name

![Snipaste_2022-08-26_12-17-32](https://user-images.githubusercontent.com/45864744/186821085-911fb076-9a85-4d5d-ada6-b642adff84f9.png)

This is in Chrome tab:
![Snipaste_2022-08-26_12-15-01](https://user-images.githubusercontent.com/45864744/186821019-9e7ac30f-a87a-4780-a08c-c1db0be91cba.png)

**Comment by AshleyScirra** [comment]
It's Chrome that changes the title bar, not Construct, and it's out of our control.

There appears to be a Chrome issue already filed about this: https://bugs.chromium.org/p/chromium/issues/detail?id=1351682

I added a comment there stating our case. Closing as we will follow up there.
