### ISSUE TITLE
Mobile Fullscreen Save Area

### ISSUE THREAD

**Issue by C3GameDev** [Scirra/Construct-3-bugs#6038]
## Problem description

When using Fullscreen-Scaling on Android, the "save-area" (like front-camera on top of each screen) is also covered with the game / app. Normally this area shouldn't be used from fullscreen.

## Attach a .c3p
Test Project: just open it and build for Android Debug apk with r302 (working), and r303 or above (not working):
[https://kkgames.de/test302.c3p]

## Steps to reproduce

1. Build and export a fullscreen app with the following settings to Android:
Viewport fit: Auto
Fullscreen mode: Scale outer
Fullscreen quality: High
Orientations: Portrait
2. Start the app: now the "fullscreen scaling" also covers the camera area of the phone

## Observed result

"fullscreen scaling" also covers the camera area of the phone

## Expected result

"fullscreen scaling" with free camera area

## More details

Android Mobile

The error first appeared in beta r303, in the latest stable (302) everything works fine.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
All we did in r303 is update to support the latest version of Android, including its new splash screen requirements. I suspect the change has come from Cordova or the Android SDK and not Construct. So I'm afraid there may not be anything we can do about it.

**Comment by C3GameDev** [comment]
Thanks for the info, I found the issue on the Cordova Github:
[https://github.com/apache/cordova-android/issues/1465](https://github.com/apache/cordova-android/issues/1465)

So it's an issue from Cordova like you said.

**Comment by AshleyScirra** [comment]
OK, closing this issue and we will follow up at the Cordova issue.
