### ISSUE TITLE
Cropping does not properly preserve image points

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#604]
## Problem description

When you click crop in the image editor, and you've placed an image point (like the origin), it will not have those points properly aligned with the new image size.

This is not an issue in C2.

This bug is quite frustrating as it makes importing batch animations very tedious. As there's no point in applying the origin to an entire animation if it's just going to change again when you crop it.

## Attach a .c3p

[cropbug.zip](https://github.com/Scirra/Construct-3-bugs/files/1138002/cropbug.zip)

## Steps to reproduce

1. Go to the sprite
2. Look at the origin/image point.
3. Click Crop
4. Look at how the position is incorrect

## Observed result

The image point is in the wrong place

## Expected result

The image point should stay where I told it to go in the image

**Comment by DiegoScirra** [comment]
Fixed in r45.
