### ISSUE TITLE
c3_ javascript calls broken, MY GAMES ARE DEAD IN THE WATER PLZ PATCH

### ISSUE THREAD

**Issue by pir8radio** [Scirra/Construct-3-bugs#6043]
I updated a bunch of images in my games, and recompiled using the latest C3,   only to find after publishing games that ALL of my games calling functions in C3 are BORKED!    Further digging, it looks like a bunch of c3_XXXXXXX   calls are missing or rather not defined.   

## Attach a .c3p
attaching c3p in a zip below, see https://github.com/Scirra/Construct-3-bugs/issues/6043#issuecomment-1229256510

## Steps to reproduce
1.  open any c3 project and using the console view defined c3_ calls, c3_callFunction, as well as others are missing or not defined.

As you can see below in the latest c3  you are missing a bunch of javascript functions found in other versions, particularly c3_callFunction() 
![image](https://user-images.githubusercontent.com/16748696/187044558-7901849c-f86c-4ca4-a485-7cdf3d0b71d1.png)

As you can see here in version r285 all c3_ functions are intact:
![image](https://user-images.githubusercontent.com/16748696/187044599-18240158-3e6e-40a8-88b4-467a9dfbab0c.png)

here is a console reporting the call is not defined.   "c3_callFunction("spinFunction");"
![image](https://user-images.githubusercontent.com/16748696/187044651-83112be1-aec7-4ec0-bb2e-d130521f06a3.png)

WORKED IN R285 HAVE NOT CHECKED ALL VERSIONS BETWEEN 285 AND LATEST.
TRIED LATEST BETAS ISSUE STILL PRESENT THERE AS WELL.

**Comment by WilsonPercival** [comment]
Everything works well for me.

![xxx](https://user-images.githubusercontent.com/91274932/187045285-42c5bb58-73be-435c-abd0-ae9cd51cf1ae.png)

**Comment by pir8radio** [comment]
> Everything works well for me.
> 
> ![xxx](https://user-images.githubusercontent.com/91274932/187045285-42c5bb58-73be-435c-abd0-ae9cd51cf1ae.png)

you are calling from within the event list..    create an html object that calls that function and embed it, call from there.

**Comment by pir8radio** [comment]
[c3_broken.zip](https://github.com/Scirra/Construct-3-bugs/files/9438585/c3_broken.zip)

Here is an example project to try.. it should log the call but doesnt.

**Comment by WilsonPercival** [comment]
> 
Everything works well for me.

![bbb](https://user-images.githubusercontent.com/91274932/187046448-2d138265-24da-416f-a447-6b66d88610ed.png)

[c3CALLtest_fixed.zip](https://github.com/Scirra/Construct-3-bugs/files/9438609/c3CALLtest_fixed.zip)

**Comment by pir8radio** [comment]
> > [c3_broken.zip](https://github.com/Scirra/Construct-3-bugs/files/9438585/c3_broken.zip)
> > Here is an example project to try.. it should log the call but doesnt. @WilsonPercival
> 
> Everything works well for me.
> 
> ![bbb](https://user-images.githubusercontent.com/91274932/187046448-2d138265-24da-416f-a447-6b66d88610ed.png)
> 
> [c3CALLtest_fixed.zip](https://github.com/Scirra/Construct-3-bugs/files/9438609/c3CALLtest_fixed.zip)

i cant seem to view what you sent.. can you let me know how you got it to work, and why what i had worked on the previous version and not the new version?

**Comment by WilsonPercival** [comment]
> > > [c3_broken.zip](https://github.com/Scirra/Construct-3-bugs/files/9438585/c3_broken.zip)
> > > Here is an example project to try.. it should log the call but doesnt. @WilsonPercival
> > 
> > 
> > Everything works well for me.
> > ![bbb](https://user-images.githubusercontent.com/91274932/187046448-2d138265-24da-416f-a447-6b66d88610ed.png)
> > [c3CALLtest_fixed.zip](https://github.com/Scirra/Construct-3-bugs/files/9438609/c3CALLtest_fixed.zip)
> 
> i cant seem to view what you sent.. can you let me know how you got it to work, and why what i had worked on the previous version and not the new version?

Compare your code and mine.

![aaa](https://user-images.githubusercontent.com/91274932/187046641-732d5a70-5d4d-442a-aa28-84d7fda258b9.png)

**Comment by pir8radio** [comment]
> 

well.......  that's embarrassing   I didn't change to quotes, how was this working before....

**Comment by pir8radio** [comment]
> > > > [c3_broken.zip](https://github.com/Scirra/Construct-3-bugs/files/9438585/c3_broken.zip)
> > > > Here is an example project to try.. it should log the call but doesnt. @WilsonPercival
> > > 
> > > 
> > > Everything works well for me.
> > > ![bbb](https://user-images.githubusercontent.com/91274932/187046448-2d138265-24da-416f-a447-6b66d88610ed.png)
> > > [c3CALLtest_fixed.zip](https://github.com/Scirra/Construct-3-bugs/files/9438609/c3CALLtest_fixed.zip)
> > 
> > 
> > i cant seem to view what you sent.. can you let me know how you got it to work, and why what i had worked on the previous version and not the new version?
> 
> Compare your code and mine.
> 
> ![aaa](https://user-images.githubusercontent.com/91274932/187046641-732d5a70-5d4d-442a-aa28-84d7fda258b9.png)

I updated my game and still not working, on local test..     so in devtools your example above, if you type c3_   what is defined, what shows up for you in the latest version?

**Comment by WilsonPercival** [comment]
> > > > > [c3_broken.zip](https://github.com/Scirra/Construct-3-bugs/files/9438585/c3_broken.zip)
> > > > > Here is an example project to try.. it should log the call but doesnt. @WilsonPercival
> > > > 
> > > > 
> > > > Everything works well for me.
> > > > ![bbb](https://user-images.githubusercontent.com/91274932/187046448-2d138265-24da-416f-a447-6b66d88610ed.png)
> > > > [c3CALLtest_fixed.zip](https://github.com/Scirra/Construct-3-bugs/files/9438609/c3CALLtest_fixed.zip)
> > > 
> > > 
> > > i cant seem to view what you sent.. can you let me know how you got it to work, and why what i had worked on the previous version and not the new version?
> > 
> > 
> > Compare your code and mine.
> > ![aaa](https://user-images.githubusercontent.com/91274932/187046641-732d5a70-5d4d-442a-aa28-84d7fda258b9.png)
> 
> I updated my game and still not working, on local test.. so in devtools your example above, if you type c3_ what is defined, what shows up for you in the latest version? I dont understand why its not an option any longer for me.. ![image](https://user-images.githubusercontent.com/16748696/187046818-d15ca5e5-b643-4d02-90d6-3a100b7f60d0.png)

Can you send a full screenshot of your screen, not just a part?

![ggg](https://user-images.githubusercontent.com/91274932/187046899-3ce39185-661d-477b-93fc-0c2674b346d2.png)

**Comment by pir8radio** [comment]
> 

I feel like someone is messing with me over there at construct..      i just took another screenshot and the missing c3_ options are now there.   but you can see in my old screenshots they were not....  another user verified too so I'm not crazy lol

![image](https://user-images.githubusercontent.com/16748696/187047064-06968b78-12ee-4782-a0fb-f416e84d6450.png)

this still is not working on the local debug, but let me try to export and push it to my server see if it now works..    at least the options are there now..     I'll report back..

**Comment by pir8radio** [comment]
Yea still not working in production any longer.   @WilsonPercival can i DM you my project to see if you can see what i am seeing?  I created at "test" button that should call a function from html.    i can add a c3 button and call it just fine, but not the html test button....

**Comment by pir8radio** [comment]
i also just tried adding c3_callFunction()  in my event sheet and it doesnt work, so its not html related.    The call function object calls the function just fine... but not in javascript.    I'm not sure what to do...

**Comment by WilsonPercival** [comment]
> Yea still not working in production any longer. @WilsonPercival can i DM you my project to see if you can see what i am seeing? I created at "test" button that should call a function from html. i can add a c3 button and call it just fine, but not the html test button.... I still think something changed from last version to this one... thought its not obvious to me what that change is.

go

**Comment by pir8radio** [comment]
@WilsonPercival  here is one of my exported html games if you want to test,   its also live on github pages to test it through the web server..   I added the simple javascript call button below the production "SPIN" button...     https://github.com/pir8radio/Wheel-Of-Signa             here is the online version  https://wos.notallmine.net/        and i can send the full project in DM or email..        would love to discover what broke this..

**Comment by WilsonPercival** [comment]
> @WilsonPercival here is one of my exported html games if you want to test, its also live on github pages to test it through the web server.. I added the simple javascript call button below the production "SPIN" button... https://github.com/pir8radio/Wheel-Of-Signa here is the online version https://wos.notallmine.net/ and i can send the full project in DM or email.. would love to discover what broke this..

Everything works well for me.

![jjj](https://user-images.githubusercontent.com/91274932/187048989-dd3b5249-9491-44cb-ba90-574079a8867e.png)

**Comment by pir8radio** [comment]
> > @WilsonPercival here is one of my exported html games if you want to test, its also live on github pages to test it through the web server.. I added the simple javascript call button below the production "SPIN" button... https://github.com/pir8radio/Wheel-Of-Signa here is the online version https://wos.notallmine.net/ and i can send the full project in DM or email.. would love to discover what broke this..
> 
> Everything works well for me.
> 
> ![jjj](https://user-images.githubusercontent.com/91274932/187048989-dd3b5249-9491-44cb-ba90-574079a8867e.png)

so inside the game,   you pushed the "test" button and the wheel started spinning?

**Comment by WilsonPercival** [comment]
> > > @WilsonPercival here is one of my exported html games if you want to test, its also live on github pages to test it through the web server.. I added the simple javascript call button below the production "SPIN" button... https://github.com/pir8radio/Wheel-Of-Signa here is the online version https://wos.notallmine.net/ and i can send the full project in DM or email.. would love to discover what broke this..
> > 
> > 
> > Everything works well for me.
> > ![jjj](https://user-images.githubusercontent.com/91274932/187048989-dd3b5249-9491-44cb-ba90-574079a8867e.png)
> 
> so inside the game, you pushed the "test" button and the wheel started spinning?

![jjjk](https://user-images.githubusercontent.com/91274932/187049055-7dd2be41-99ac-4dc9-b8f8-d24df363e0cd.png)

**Comment by pir8radio** [comment]
[Wheel Of Signa - TEST.zip](https://github.com/Scirra/Construct-3-bugs/files/9438731/Wheel.Of.Signa.-.TEST.zip)

i was waiting for a private way to send to you.. but here is the test project,   I added THREE test buttons,  one from the HTML that uses c3_callFunction,   one that uses c3_callFunction from the event list,  and one that uses the Function call object.   The only one that works is the function call object.   but i need the javascript call to work..      thank you for your help!!!

**Comment by WilsonPercival** [comment]
> [Wheel Of Signa - TEST.zip](https://github.com/Scirra/Construct-3-bugs/files/9438731/Wheel.Of.Signa.-.TEST.zip)
> 
> i was waiting for a private way to send to you.. but here is the test project, I added THREE test buttons, one from the HTML that uses c3_callFunction, one that uses c3_callFunction from the event list, and one that uses the Function call object. The only one that works is the function call object. but i need the javascript call to work.. thank you for your help!!!

My contact information is in my profile.

**Comment by pir8radio** [comment]
> > [Wheel Of Signa - TEST.zip](https://github.com/Scirra/Construct-3-bugs/files/9438731/Wheel.Of.Signa.-.TEST.zip)
> > i was waiting for a private way to send to you.. but here is the test project, I added THREE test buttons, one from the HTML that uses c3_callFunction, one that uses c3_callFunction from the event list, and one that uses the Function call object. The only one that works is the function call object. but i need the javascript call to work.. thank you for your help!!!
> 
> My contact information is in my profile.

i didn't see that sorry..   if this works for you, then I'm at a complete loss..   ignore the messy code. lol  I'm still learning.

**Comment by pir8radio** [comment]
i suspect this has something to do with the migration of the project to the newer c3 release.  since the call function DOES work in a fresh test, but does not work in my existing game..

**Comment by WilsonPercival** [comment]
> i suspect this has something to do with the migration of the project to the newer c3 release. since the call function DOES work in a fresh test, but does not work in my existing game..

`Function`. As long as it is present in the project, you cannot call `c3_callFunction()`. I created a new bug report:

https://github.com/Scirra/Construct-3-bugs/issues/6045

**Comment by pir8radio** [comment]
> 

im not crazy then!  good..    any way for me to get this working in my current project i sent you?

**Comment by WilsonPercival** [comment]
> > 
> 
> im not crazy then! good.. any way for me to get this working in my current project i sent you?

Either remove the `Function` object or use `runtim.callFunction()`. But I advise you to wait until Monday and see what Ashley has to say about it.

**Comment by pir8radio** [comment]
> 

i couldnt get runtime.callFunction to work either..  i tried..   so remove what "function"  is it something i can remove and add a c3 version?

thanks again for the help...   I'm still learning here.   i would have never put together that was the issue.

**Comment by WilsonPercival** [comment]
> > 
> 
> i couldnt get runtime.callFunction to work either.. i tried.. so remove what "function" is it something i can remove and add a c3 version?

If it was a question, I didn't understand it.

**Comment by pir8radio** [comment]
> 

your new bug report says  c3_callFunction() wont work if there is a C2 function in the project.     Is there anything i can do to remove the "C2 Function" and replace it with a C3 equivalent?   or did i misunderstand the issue?

**Comment by WilsonPercival** [comment]
> > 
> 
> your new bug report says c3_callFunction() wont work if there is a C2 function in the project. Is there anything i can do to remove the "C2 Function" and replace it with a C3 equivalent? or did i misunderstand the issue?

Yes, you can change all functions to built-in functions.

**Comment by pir8radio** [comment]
> 

sorry,  I do not understand,  I thought they were already,  do you have an example of one of my functions before and after?    I promise ill stop bugging you..   :-)

**Comment by WilsonPercival** [comment]
> > 
> 
> sorry, I do not understand, I thought they were already, do you have an example of one of my functions before and after? I promise ill stop bugging you.. :-)

![pppp](https://user-images.githubusercontent.com/91274932/187050658-1b818c81-8fa2-4caf-9229-6a4157cec449.png)

**Comment by pir8radio** [comment]
> > > 
> > 
> > 
> > sorry, I do not understand, I thought they were already, do you have an example of one of my functions before and after? I promise ill stop bugging you.. :-)
> 
> ![pppp](https://user-images.githubusercontent.com/91274932/187050658-1b818c81-8fa2-4caf-9229-6a4157cec449.png)

ahh   ok, i understand..  i didnt realize the actual function object was from c2..   ill see if i can find equivalent replacements.  
Thanks again and **THANK YOU FOR NOT GIVING UP ON MY BUG TROUBLESHOOTING**

**Comment by pir8radio** [comment]
@WilsonPercival   you are a genius,  that worked and wasn't super hard to do,   now i know!    thanks!!!!!!   thats what i get for using legacy stuff...

**Comment by AshleyScirra** [comment]
This bug report is too long and complicated to adequately review. We need issues to be submitted providing all the information requested by the bug report guidelines for it to be possible for us to help.

I would add that:

- outside of `c3_callFunction`, all the other variables shown in your screenshot are undocumented and you should not use them. If you use them and something breaks, we will not support you.
- if you have the legacy function object in your project it is by design that `c3_callFunction` calls functions in that, rather than built-in functions, for backwards compatibility.
- if you are typing in the browser console, then the console context, and the project worker mode, are significant. For example if you have worker mode enabled and you type in the console when in the main thread context, nothing from the runtime will show up. You can change worker mode or change the context of the console at the top of dev tools.
