### ISSUE TITLE
Hierarchy - Timelines "width" and "height" ignored under certain conditions

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#6044]
## Problem description

I have two sprites attached together with the hierarchy option.  The parent timeline moves only in X, so in the action "add child", I activate only the X value, because nothing else moves. When I move the second sprite with a timeline, it works nice for x, y and angle, but not for width and height. If I want to make width and height work, I have to activate those values in the "add child" action.
For Angle and X Y this is not necessary

## Attach a .c3p
[Timeline_BugX.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9438614/Timeline_BugX.c3p.zip)

## Steps to reproduce

1.preview the timeline 1 (red sprite) in the timeline bar to see what it should do
2.now preview the project and observe the red sprite
3.now activate the "width" value in the "add child" action
4.step 2 again

## Observed result
in step 2. the red sprite does not transform its width

## Expected result
red sprite should transform its width

## More details

I tested on mac in chrome, r306 and 307
**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r307 (beta)
Browser: Chrome 104.0.5112.101
Browser engine: Chromium
Context: browser
Operating system: macOS 11.6.8
Device type: desktop
Device pixel ratio: 2.200000047683716
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 269 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel Inc.)
Renderer: ANGLE (Intel Inc., Intel(R) HD Graphics 630, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.

Revision 17702.
