### ISSUE TITLE
iid picking bug?

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#6046]
Changing an instance of an objects colour by picking the instance based on a matching variable number does not work in my project, but does in a new project. Same code.

I've stripped my project down to just the elements effected. 

## Attach a .c3p
[iid_not_working.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9439437/iid_not_working.c3p.zip)
[iid_working.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9439438/iid_working.c3p.zip)

press the A key to add one to the instance variable "test". The sprite with the matching iid should turn black in colour. Same code both projects.

1. run projects
2.press A key
3.

in one file matching iid instance turns black in colour

does not seem to be picking instance.

## More details

chrome, mac os 

R307 beta 

Platform information
Product: Construct 3 r307 (beta)
Browser: Chrome 104.0.5112.101
Browser engine: Chromium
Context: webapp
Operating system: macOS 10.13.6
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 276 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., ATI Radeon HD 5670 OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
both example work for me, it's just that the one you mark as not working takes some time to show up as the first hundred or so objects are overlapped by high iid objects!

**Comment by AshleyScirra** [comment]
It looks like the "not working" project just has so many instances all overlapping, then you need the variable to reach about 100 before it makes a visible difference. I believe it is in fact all working correctly.
