### ISSUE TITLE
Timeline Scale X Y not very practical to handle 

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#6049]
## Problem description
edit: please check out #6052 , you will possibly encounter this issue while taking a look at this one :)

As the standart for sizemanipulation in Timeline seems to be width and heigth, it is a bit annoying to handle scale X and Y,  it quickly adds an additional heigth or width value. I think if scale X or Y exists in the timeline, it should use those values instead of adding new ones for width and height.

I quick point of view of mine, why I think to choose width and height as the standard in the timeline is the wrong choice: It is very common to work with placeholder graphics, to constantly improve the graphics. So I usualy use a standart size sprite that I can easily replace, and in the end when exporting I crop them. So it is very common that the graphic changes its size while working, which means all animations done with "width" and "height" will look different. To use Scale X and Y would partly solve this problem, it would even be perfect if the scaleX and Y would not be related to the sprite properties scaleX Y, but only be a percentage of the possibliy manipulated spritesize in the editor. 

A sidenote, I was irritated for a moment that for scale X and Y,  0% is basicaly 1 or 100%, and double size means 100%, halve size -50% but I can work with that. I think it would be clearer if 2 or 200% is double, 0.5 or 50% is half.

## Attach a .c3p
[Timeline_Scale_XY.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9447508/Timeline_Scale_XY.c3p.zip)

## Steps to reproduce

1.open timeline 1, go to edit mode
2.go to timemarker 0.5 (where no keyframe is)
3.manipulate in the editor the size of the green sprite
4.press + for a new keyframe

## Observed result

it adds values for width and height, they dont seem to be  connected to the scale x and y. When a delete width and height and keep the newly added keyframes for scale x and y, it doesn't preserve the manipulation.
## Expected result

it should add keys for the existing values, so in this case for scale x and y. It works when I click in the timeline on those values, but thats not very intuitiv way of working.
## More details

**Affected browsers/platforms:** 
I tested on mac in chrome, r307

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r307 (beta)
Browser: Chrome 104.0.5112.101
Browser engine: Chromium
Context: browser
Operating system: macOS 11.6.8
Device type: desktop
Device pixel ratio: 2.200000047683716
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 269 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel Inc.)
Renderer: ANGLE (Intel Inc., Intel(R) HD Graphics 630, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment]
The next beta will have two new features to improve working with scales.

The first one, a context menu option available when right clicking on a width or height property track to convert to equivalent scale X and scale Y property tracks. There will also be an option to convert from scale to size.

The second feature is a setting you can turn on at either the timeline, track folder or track level which will let you choose which should be the properties affected when making changes through the layout view in timeline editing mode.

**Comment by bubbblebub** [comment]
Great, thats sounds like the perfect solution! Thanks a lot for addressing all my timeline issue reports.
