### ISSUE TITLE
Editor crashes after Undo

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#6051]
## Problem description

After adding/removing a new frame in the animation editor, pressing Ctrl-Z crashes the program.

## Steps to reproduce

1. Create a new sprite, close the animation editor.
2. Double-click the sprite to open the animation editor again.
3. Duplicate the animation frame, then delete the duplicate.
4. Close the animation editor.
5. Press Ctrl-Z 

## Observed result

![image](https://user-images.githubusercontent.com/36763350/187351763-375856e1-5542-47b2-ae16-1e4a9691c212.png)

**Affected browsers/platforms:**  Chrome/Firefox

**First affected release:**  worked in the latest stable release.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: animation frame has no content @ Error: animation frame has no content at d.eH (https://editor.construct.net/r307/projectResources.js:725:341) at d.ia (https://editor.construct.net/r307/projectResources.js:734:6) at IWa.gn.rf (https://editor.construct.net/r307/projectResources.js:1784:21) at rM.JLb.rf (https://editor.construct.net/r307/projectResources.js:1770:405) at self.hp.rf (https://editor.construct.net/r307/projectResources.js:1770:405) at pM.Bjc.rf (https://editor.construct.net/r307/projectResources.js:1770:405) at pM.Bjc.rf (https://editor.construct.net/r307/projectResources.js:1861:207) at window.qc.Sh (https://editor.construct.net/r307/projectResources.js:1774:19) at d.Sh (https://editor.construct.net/r307/projectResources.js:1655:95) at window.Hab.Sh (https://editor.construct.net/r307/main.js:2345:269)
Stack: Error: animation frame has no content at d.eH (https://editor.construct.net/r307/projectResources.js:725:341) at d.ia (https://editor.construct.net/r307/projectResources.js:734:6) at IWa.gn.rf (https://editor.construct.net/r307/projectResources.js:1784:21) at rM.JLb.rf (https://editor.construct.net/r307/projectResources.js:1770:405) at self.hp.rf (https://editor.construct.net/r307/projectResources.js:1770:405) at pM.Bjc.rf (https://editor.construct.net/r307/projectResources.js:1770:405) at pM.Bjc.rf (https://editor.construct.net/r307/projectResources.js:1861:207) at window.qc.Sh (https://editor.construct.net/r307/projectResources.js:1774:19) at d.Sh (https://editor.construct.net/r307/projectResources.js:1655:95) at window.Hab.Sh (https://editor.construct.net/r307/main.js:2345:269)
Construct version: r307
URL: https://editor.construct.net/r307/
Date: Tue Aug 30 2022 14:52:33 GMT+1000 (Australian Eastern Standard Time)
Uptime: 14.6 s

Platform information
Product: Construct 3 r307 (beta)
Browser: Chrome 104.0.5112.102
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.
