### ISSUE TITLE
Timeline Scale X Y not possible to manipulate visualy with the editor, works only with manual input

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#6052]
## Problem description

This is an addition to #6049
I can not manipulate Scale X and Y in the timeline visualy, if I do that it makes keyframes, but it changes only the size of the sprite for the whole animation. The only way to use Scale X Y at the moment is to exit the Timeline Edit mode, manipulate your sprite, copy the Scale value, undo the manipulatien, enter edit mode, enter copied value in the spriteproperties, and then adding a keyframe

## Attach a .c3p
[Timeline_Scale_XY.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9450199/Timeline_Scale_XY.c3p.zip)

## Steps to reproduce

1.open timeline 1 go to edit mode
2.go to time marker 0.5s manipulate the size of the sprite
3.click on the Scale X Y layers ,so it will not create a width and height value (see  #6049), click + for a new keyframe
4.play the timeline to see the result

## Observed result

the new key has changed the spritesize of the whole animation, instead of just the size of this keyframeposition

## Expected result

correct keyframe only for this position in time

## More details

it is possible to get the right result, bei entering the wanted value here manualy, then adding a keyframe
![Bildschirmfoto 2022-08-30 um 08 32 08](https://user-images.githubusercontent.com/35291800/187366280-24f705c8-4388-4bbf-ae1f-5db6ec52dbb5.png)

**Affected browsers/platforms:** 

**First affected release:** 
i tested in mac / chrome / r307
## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r307 (beta)
Browser: Chrome 104.0.5112.101
Browser engine: Chromium
Context: browser
Operating system: macOS 11.6.8
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 267 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 560 OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
The new feature added for #6049 to choose what kind of keyframes will be created when making dimension changes in the layout view should sort this out.

Please try it out and see how it works out for you.
