### ISSUE TITLE
Video Playback Significantly Slows Framerate (Sometimes Below 10 FPS) in Firefox

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#6054]
## Problem description

On Firefox, playing a video in projects slows down framerate from a steady 60 FPS to around 30 FPS when using an .ogv video, or down to 10 FPS or lower when using .mp4 or .webm video. When given all three sources as options to play video, Firefox does not seem to detect the better-performing options and will remain at a low FPS while playing video.

## Attach a .c3p

[Video Types Test.zip](https://github.com/Scirra/Construct-3-bugs/files/9456339/Video.Types.Test.zip)

## Steps to reproduce

1. Open the provided project in different browsers or operating systems, but most notably in Firefox on Windows.
2. Click the buttons on the left to switch the file source used for the video between .mp4, .ogv, and .webm.
3. Observe the effects of different video filetypes on framerate as shown in the top right corner's FPS counter and visible smoothness of the rotating sprite's motion.

## Observed result

On Firefox, playing an .ogv video file type reduces FPS from about 60 by roughly 30, whereas playing .mp4 or .webm videos will reduce FPS by at least 50, often leading to single-digit framerates. These issues don't seem to occur on Chrome, in which none of these video file types reduce framerate below 60.

## Expected result

As was once previously the case, video playback should not significantly affect performance.

## More details
The issue seems worst in Firefox on Windows, where as described, FPS can drop to single digits.
In Firefox on Macs, FPS seems to drop down only to 40 FPS during video playback of any file type, but never any lower.
In Chrome on Windows, FPS seems unaffected by video playback of any file type.
In Chrome on Macs, FPS seems unaffected by video playback of any file type.

As this issue seems dependent on user's specific hardware, here are some videos for reference in a .zip file:
- **Video Types Test.mp4** is recorded from Firefox on my Windows PC, showing frame drops most drastic with .mp4 and .webm.
- **Before.mp4** is recorded from Firefox on my Windows PC, showing a project built in February 9th, 2022, which uses a video tutorial (in provided filetype sources of .mp4, .webm, and .ogv) to show how to play, which does not appear to have negatively affected its performance and still does not do so today. It's not clear to me what version of Construct 3 I'd used to produce this build of this game at the time, though I would guess it would have been the most recent stable version available at that time in February.
- **After.mp4** is recorded from Firefox on my Windows PC, showing the same project from Before.mp4, but now rebuilt in the recently released r308 stable version of Construct 3. Here, as shown, the otherwise untouched months-old project now suffers from drastically lower framerates as its tutorial video runs either on-screen or invisibly in the background during gameplay.

[Videos.zip](https://github.com/Scirra/Construct-3-bugs/files/9456508/Videos.zip)

**Affected browsers/platforms:** Firefox, Windows, Macs

**First affected release:** Unclear, but I believe the issue has existed for at least a few weeks before the release of r308.

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r308 (stable)
Browser: Firefox 104.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0
Language setting: en-US
Local storage

Storage quota (approx): 58 gb
Storage usage (approx): 536 mb (0.9%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can reproduce, but I'm afraid if Firefox is slow, it's beyond our control - you'd need to report the issue to Mozilla who develop Firefox.

We've already worked hard to optimise the video playback to be as efficient as possible for a variety of mobile and desktop platforms, and I doubt there is much more we can do on our end. It looks like Firefox just handles this much slower than other browsers.
