### ISSUE TITLE
Collision polygon breaks after game load. (using hierarchies) r308

### ISSUE THREAD

**Issue by MihaMS** [Scirra/Construct-3-bugs#6060]
## Problem description

Collision polygon breaks after game load (r308)
watch attached video

https://user-images.githubusercontent.com/23280578/187635409-efd78aae-bfc0-4f42-9179-132ae9fa196d.mp4

## Attach a .c3p

[WeirdBug1.zip](https://github.com/Scirra/Construct-3-bugs/files/9460002/WeirdBug1.zip)

## Steps to reproduce

1. Dowload, unpack and open attached c3p
2. Run this example. Press Save button
3. Green rectangle has Platform behaviour with default controls. So use Right Arrow on Keyboard to **move it on right side of the brown "bridge"** - this is important condition
4. Load Game by pressing "Load" button. Move Green rectangle again to the right side of the "bridge".

## Observed result

After game was loaded Platform object falls through solid object

## Expected result

Not falling through solid object

## More details
The same result (bug) will be also without using families in example and/or without mirroring object
![Screenshot 2022-08-31 110007](https://user-images.githubusercontent.com/23280578/187640671-5490f51f-98cb-4448-a8fc-93f746f7b604.png)

**Affected browsers/platforms:** 

Chrome (not tested in others)
Windows 10

**First affected release:** 

r302, r308 (tested only on this releases)

**Comment by DiegoScirra** [comment]
This has something to do with families. I modified the example project to add another object without using families and it looks like it works correctly.

[weirdbug1.zip](https://github.com/Scirra/Construct-3-bugs/files/9462261/weirdbug1.zip)

@AshleyScirra any ideas?

**Comment by MihaMS** [comment]
> This has something to do with families. I modified the example project to add another object without using families and it looks like it works correctly.
> 
> [weirdbug1.zip](https://github.com/Scirra/Construct-3-bugs/files/9462261/weirdbug1.zip)
> 
> @AshleyScirra any ideas?

1) No, you just hide one solid underneath another that it can't be accessed, if we set it's coordinates a bit to the side and higher - we will get the same bug.

https://user-images.githubusercontent.com/23280578/187712927-f8767ab1-25c9-4541-a3c4-d3ef00e26775.mp4

2) Sorry, but for whom I writing bug report? I mentioned that "The same result (bug) will be also without using families in example and/or without mirroring object"
Here is absolutely the same issue without any Families used:
[WeirdBug1_withoutFamilies.zip](https://github.com/Scirra/Construct-3-bugs/files/9462639/WeirdBug1_withoutFamilies.zip)

**Comment by AshleyScirra** [comment]
This was a tricky one, but it turned out to be a complicated issue with caching angles when using hierarchies. It should be fixed for the next beta.
