### ISSUE TITLE
JSON TEXT EDITOR REGRESSION IN R308

### ISSUE THREAD

**Issue by TmesisStudio** [Scirra/Construct-3-bugs#6061]
## Problem description

I just loaded the new r308 and found a regression in JSON Editor.

Before (the last version of C3 I used was r302) when I double click on a cell it open me the entire text inside the cell (splitting it vertical), so I can easily edit the text wherever I want. Now if I double click it doesn't open the entire text and I have to manually search for a word inside the cell by scrolling right/left with the arrows, which is a huge time-wasting job in a game like ours with more than 40'000 words.
Would it be possible to update the editor to make it go back to how it was before?
Thank you guys!
Federico from Tmesis Studio

## Attach a .c3p

[Json Editor Regression.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9460555/Json.Editor.Regression.c3p.zip)

## Steps to reproduce

Just open the unique array present inside the project called "Nuovo Array.json" and you'll find a long text in cell (1,0) that cannot
be read entirely like once but you have to manually use the arrows to see what's inside the cell.
Really time consuming for a text based game. 

## Observed result

Just open the unique array present inside the project called "Nuovo Array.json" and you'll find a long text in cell (1,0) that cannot
be read entirely like once but you have to manually use the arrows to see what's inside the cell.
Really time consuming for a text based game. 

## Expected result

It would expect that the entire cell text comes up in a separate vertical box ready to be modified (as it was until r302 C3 release) in every his word, without need to scroll it.

## More details

There's no need.

**Affected browsers/platforms:** 

Google Chrome tested.

**First affected release:** 

Until r302 release works then in r308 doesn't anymore.

**Comment by DiegoScirra** [comment]
@AshleyScirra This has to do with the change made in revision 17552 to fix issue #5968. The **white-space: pre** style prevents the edit box from changing it's height.

**Comment by AshleyScirra** [comment]
Yep, it's a regression caused by the fix to #5968. Fixed for the next beta.
