### ISSUE TITLE
C3 causes graphic card failure when resizing an image to huge dimensions

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6063]
## Problem description

I work on a pc with an old graphics card (GT 660). I accidentally resized an image to 15000x15000, and the pc froze for a minute before showing that the graphic card restarted (similar to a Blue Screen).

Please add a warning message before a user attempts such resize. For example:
"The new size 15000x150000 is too big and might cause a slow performance. Are you sure you want to resize?"

## Attach a .c3p

(New Project)

## Steps to reproduce

1. Add a sprite
2. Double click and give it a big image
3. Resize the image to the biggest size you think your device will handle.

## Observed result

No response for a while, then graphic card failure/blue screen

## Expected result

Warning message (suggestion).

## More details

**Affected browsers/platforms:** Chrome App

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
There already is a warning in some cases, as shown below. It sounds like using an extremely large image caused the graphics driver to crash. I'm not sure there's anything much we can do about that.

![image](https://user-images.githubusercontent.com/768723/187879884-6ab128cd-00f1-4630-9ba2-96150800db52.png)
