### ISSUE TITLE
Undo with fx crash

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#6065]
## Problem description
Changing the order of layer shaders and then hitting undo causes a crash

## Attach a .c3p
https://www.dropbox.com/s/1ydrxxhykqauf8b/tiltshiftdc.c3p?dl=1

## Steps to reproduce

1.Load the project.
2.Open up the effects dialog for layer 1
3. Pick the Blur Horizontal and drag it above Multiply
4. Close the dialog.
5. Hit undo.

## Observed result
Crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r308/main.js, line 485, col 123
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'wF')
Stack: TypeError: Cannot read properties of undefined (reading 'wF') at CCG.uka (https://editor.construct.net/r308/main.js:485:123) at vr.Lc.iG.WR.Y9b.CFa (https://editor.construct.net/r308/main.js:1866:406) at vAa (https://editor.construct.net/r308/projectResources.js:42:83) at d.Jf (https://editor.construct.net/r308/projectResources.js:1293:201) at d.Jf (https://editor.construct.net/r308/projectResources.js:1252:3) at C0b (https://editor.construct.net/r308/components/editors/layoutView/layoutView.js:84:153)
Construct version: r308
URL: https://editor.construct.net/
Date: Fri Sep 02 2022 10:05:44 GMT-0400 (Eastern Daylight Time)
Uptime: 46.1 s

Platform information
Product: Construct 3 r308 (stable)
Browser: Chrome 104.0.5112.102
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 2
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in next beta.
