### ISSUE TITLE
Offline json update bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6066]
## Problem description

I upload the first version of the game to the server with the `offline.json and sw.js` files. Then I upload the second version of the game to the server, but without the `offline.json and sw.js` files. Further, no matter how much I update the page, the game will not be updated. You need to clear the cache.

## Attach a .c3p

[c3p_project_1.zip](https://github.com/WilsonPercival/WilsonPercival/files/9481723/c3p_project_1.zip)

I just added a tomato sprite: [c3p_project_2.zip](https://github.com/WilsonPercival/WilsonPercival/files/9481724/c3p_project_2.zip)

Export project 1: [project_1.zip](https://github.com/WilsonPercival/WilsonPercival/files/9481725/project_1.zip)

Export project 2 (without `offline.json and sw.js`.): [project_2.zip](https://github.com/WilsonPercival/WilsonPercival/files/9481804/project_2.zip)

## Steps to reproduce

1. Open the first project and export to Web (HTML5) or use the first archive with the exported project.
2. Upload it to the server, for example, https://app.netlify.com/drop.
3. Open the game. It must be stored in the cache.
4. Open the second project and export to Web (HTML5) or use the second archive with the exported project.
5. Upload it to the server.
6. Open the game.

## Observed result

After I uploaded the first export to the server:

![a1](https://user-images.githubusercontent.com/91274932/188256194-09c81089-cf7a-445d-8da0-19366a6b207d.png)

After I uploaded the second export to the server (which is without `offline.json and sw.js`). It can be seen that in the console `warn 404 offline.json`:

![a2](https://user-images.githubusercontent.com/91274932/188256198-01ae20f9-4763-4227-8e71-81918bf7136e.png)

## Expected result

![expected](https://user-images.githubusercontent.com/91274932/188256201-136f5dd3-4769-4a70-86ef-d0c210d0565b.png)

## More details

https://www.construct.net/en/tutorials/offline-games-construct-8

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r308s

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r308 (stable)
Browser: Chrome 105.0.5195.54
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 718 mb (1.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by arcadesindo** [comment]
Agreed, this happens a lot of time, that's why now I just deleted the offline.json file

**Comment by AshleyScirra** [comment]
This is not a bug, because:

> Then I upload the second version of the game to the server, but without the offline.json and sw.js files.

Those are the files Construct uses to detect if an update has happened. If you don't upload them it will never detect that an update happened. This is covered in the documentation you linked to ("Remember to re-upload offline.json").

**Comment by WilsonPercival** [comment]
> This is not a bug, because:
> 
> > Then I upload the second version of the game to the server, but without the offline.json and sw.js files.
> 
> Those are the files Construct uses to detect if an update has happened. If you don't upload them it will never detect that an update happened. This is covered in the documentation you linked to ("Remember to re-upload offline.json").

@AshleyScirra But what if I first loaded `offline.json and sw.js` and then changed my mind and stopped loading `offline.json and sw.js` so that the game would no longer work offline?

![asd](https://user-images.githubusercontent.com/91274932/188427823-651a8856-1e96-45de-bfa0-f66f8e48db88.png)

**Comment by AshleyScirra** [comment]
That only works the first time you upload. After the first load, the content loads in full without even communicating with the server; the only way it updates is via offline.json.
