### ISSUE TITLE
Adding a Cordova plugin

### ISSUE THREAD

**Issue by SurenaMHZ** [Scirra/Construct-3-bugs#6068]
Hello
I request to add a plugin   tapsell-plus-cordova-plugin
The link of this plugin on GitHub: https://github.com/vinoosir/tapsell-plus-cordova-plugin
This plugin is the new version of tapsell-v3-cordova-plugin and tapsell-cordova-plugin, which were added before, but these plugins are no longer supported and can be deleted.
Thankful

**Comment by AshleyScirra** [comment]
Added `tapsell-plus-cordova-plugin@2.1.6` to build service.
