### ISSUE TITLE
iOS sprite effect problems

### ISSUE THREAD

**Issue by Scott943** [Scirra/Construct-3-bugs#607]
## Problem description

*Enter a concise description of your problem here*
Black pixels come up instead of transparent when brightness effect is applied in an iOS export.
![image1 3](https://user-images.githubusercontent.com/8079722/28072664-99e2afde-664b-11e7-8888-43b9a317d881.PNG)

## Attach a .c3p
any .c3p
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.Add effect to a non-square sprite (Brightness effect used)
2.Export to iOS and Xcode project
3.Run on an iOS device (seems to work fine in simulator, but not on an iPhone/iPad)

## Observed result

*What do you see happen?*
Black edges in sprites
## Expected result

*What did you expect to happen instead?*
Object has transparent parts
## Affected browsers

* Chrome: yes
* Firefox: 
* Edge:
* Safari: 

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE
r
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r44

Local storage
Storage quota (approx): 5.2 gb
Storage usage (approx): 276 mb (5.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
This looks like a C2 bug we fixed a while ago, and I checked and it turns out I forgot to merge the fix back in to C3. I've merged the fix for the next C3 build now, so if you check r45 when it's out it should be working correctly again.

**Comment by Scott943** [comment]
@ashleyscirra Thanks - will do!

**Comment by AshleyScirra** [comment]
r45 is out now, please check again!

**Comment by Scott943** [comment]
@AshleyScirra Can confirm the issue has been fixed in r45! Thank you very much :)
