### ISSUE TITLE
Crash on moving keyframe to 0s - if its past the time marker

### ISSUE THREAD

**Issue by uwosi** [Scirra/Construct-3-bugs#6071]
## Problem description

Dragging a keyframe to the 0s position of the timeline bar causes a crash if the keyframe is moved past the time marker 

## Steps to reproduce

1. Create a sprite
2. Open a timeline and add the sprite
3. Enter the edit mode
4. Move the sprite and add a keyframe
5. Drag the keyframe to the 0s position but _past the time (red) marker_

Example:
![timey_liney](https://user-images.githubusercontent.com/73887800/188282427-113a1696-384f-40e2-b37f-ec7d76bf0208.gif)

## Observed result

💣💥😲 crash

## Expected result

😊👍 no crash

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.Q.i (https://editor.construct.net/r308/main.js:900:461) at gJ.gp (https://editor.construct.net/r308/projectResources.js:1191:396) at d.gp (https://editor.construct.net/r308/projectResources.js:1113:312) at d.gp (https://editor.construct.net/r308/projectResources.js:1044:266) at d.AG (https://editor.construct.net/r308/projectResources.js:966:114) at d.AG (https://editor.construct.net/r308/projectResources.js:966:203) at d.pha (https://editor.construct.net/r308/components/bars/timelineBar/timelineBar.js:41:416) at d.u2.eS (https://editor.construct.net/r308/components/bars/timelineBar/timelineBar.js:187:107) at d.u2.jwc (https://editor.construct.net/r308/components/bars/timelineBar/timelineBar.js:173:304) at Array. (https://editor.construct.net/r308/components/bars/timelineBar/timelineBar.js:158:9)
Stack: TypeError: unexpected type at Function.Q.i (https://editor.construct.net/r308/main.js:900:461) at gJ.gp (https://editor.construct.net/r308/projectResources.js:1191:396) at d.gp (https://editor.construct.net/r308/projectResources.js:1113:312) at d.gp (https://editor.construct.net/r308/projectResources.js:1044:266) at d.AG (https://editor.construct.net/r308/projectResources.js:966:114) at d.AG (https://editor.construct.net/r308/projectResources.js:966:203) at d.pha (https://editor.construct.net/r308/components/bars/timelineBar/timelineBar.js:41:416) at d.u2.eS (https://editor.construct.net/r308/components/bars/timelineBar/timelineBar.js:187:107) at d.u2.jwc (https://editor.construct.net/r308/components/bars/timelineBar/timelineBar.js:173:304) at Array. (https://editor.construct.net/r308/components/bars/timelineBar/timelineBar.js:158:9)
Construct version: r308
URL: https://editor.construct.net/
</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.

Revision 17691.
