### ISSUE TITLE
The "video" object slows down on the phone

### ISSUE THREAD

**Issue by barabash777** [Scirra/Construct-3-bugs#6073]
If the device is weak or average, then I see how the video twitches and fps decreases. (mobile) (i used google translate)

I'm trying to resize a "Video" object and hope the smaller the size the higher the fps, but it doesn't seem to make a difference if the object size is **300 - 300 or 3000 - 3000** = the drop problem is always the same. Can I make it so that if I decrease the "Video" object, I could increase the fps? I think this should reduce the draw area

I tried to come up with at least 1 way to organize the game settings so that the player can do something, select some parameter in the options that will increase performance, which falls in the real implementation of the video plugin. **Maybe you have some advice or you can add some new influence parameter to the "video object"**, something similar in meaning to big games, where the player can change the game resolution from 1920-1080 to 1280-1024 or another in the game settings and it increases the speed of the game. I really need to use video, good quality, but I don't know what to do for players who will have visible lags.

Perhaps you can **add a parameter** in video object - fixed fps, for example, I can set the maximum fps to 24 frames and maybe this will give a smooth image.

 **.c3p** - https://cloud.mail.ru/public/Zktg/qm8tzpHSp

**r308**

**Comment by AshleyScirra** [comment]
We've already done a lot of work to optimise video playback as much as we can in our engine.

If it's still slow it's probably coming from the browser engine, so it's something you'd need to report to Apple or Google depending on the platform, as only they can improve the performance of the browser engine itself.

**Comment by barabash777** [comment]
Okay, I understand, thanks. 1 question. 
When resizing the "video" object (width and height) to 300-300 or 3000-3000 I don't see any change in performance, is this not a bug? I thought the smaller the size of the object, the easier it is for the engine to render the screen and the higher the fps

@AshleyScirra

**Comment by AshleyScirra** [comment]
If the browser is slow then only the browser maker can explain precisely why. But I would guess the slowness is in the video decoding, not the rendering.
