### ISSUE TITLE
chrome animation editor issue

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#6075]
## Problem description
in google chrome (I am on mac), when I flip between some frames that are zoomed in, the image jumps around until it finds a stable position. I tested also in Firefox and Safari, there it works fine. 
This can be quite annoying when you want to flip your drawings to verify an animation.

## Attach a .c3p
[animationEditor_Bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9484306/animationEditor_Bug.c3p.zip)

## Steps to reproduce

1.open the project in chrome (on mac?) doubleclick on the sprite to open the animation editor
2.zoom in like in the screenshot
![Bildschirmfoto 2022-09-04 um 10 34 01](https://user-images.githubusercontent.com/35291800/188305106-45fc0016-1131-4365-b354-91c56a3dc4c4.png)

3.now klick on the next drawings 1,2,3,4 on the bottom, and take a look at the framing

## Observed result
the frame jumps around 3 or 4 times until it finds a stable position

## Expected result
no movement of the frameing

## More details

**Affected browsers/platforms:** 
I am on mac, bug exists in chrome, but not in firefox and Safari

**First affected release:** 
I went back to 276.2 and there also it doesn't work. But in my memory it appeared recently (1 or 2 month ago) so it is probably related to a chrome update
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 105.0.0.0
Browser engine: Chromium
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_7
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 156 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 560 OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by bubbblebub** [comment]
it works perfect now, thanks a lot!

**Comment by AshleyScirra** [comment]
Thanks for confirming!
