### ISSUE TITLE
crash opening animation editor

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#6078]
I worked in the anim editor on a sprite, changed layout, then came back again to open the sprite again and it crashed.

______________________

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'Le') @ TypeError: Cannot read properties of null (reading 'Le') at window.jl.Ku (https://editor.construct.net/r308/components/editors/layoutView/layoutView.js:95:77) at https://editor.construct.net/r308/components/editors/layoutView/layoutView.js:120:14
Stack: TypeError: Cannot read properties of null (reading 'Le') at window.jl.Ku (https://editor.construct.net/r308/components/editors/layoutView/layoutView.js:95:77) at https://editor.construct.net/r308/components/editors/layoutView/layoutView.js:120:14
Construct version: r308
URL: https://editor.construct.net/
Date: Mon Sep 05 2022 22:26:57 GMT+1000 (Australian Eastern Standard Time)
Uptime: 1303.9 s

Platform information
Product: Construct 3 r308 (stable)
Browser: Chrome 104.0.5112.102
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by DiegoScirra** [comment]
Can't reproduce this. Is it a consistent crash?

**Comment by alastajj** [comment]
Doesn't seem like it. Just thought I'd post incase
