### ISSUE TITLE
Undo crash with tilemap image editor

### ISSUE THREAD

**Issue by ericcraft123456** [Scirra/Construct-3-bugs#6079]
## Problem description

When you edit the image of a tilemap close the image editor, and press Undo, Construct 3 crashes.

## Attach a .c3p
https://www.dropbox.com/s/e179r80b550b33l/tilemapcontrolzbug.c3p?dl=0

## Steps to reproduce

1. Open the tilemap's image editor and make an edit (e.g. draw a line)
2. Close the image editor and press Undo or Control+Z

## Observed result

Construct 3 crashes with the error:
Type: unhandled rejection
Reason: Error: cannot change duration of non-animated image @ Error: cannot change duration of non-animated image at d.gaa 

## Expected result

The image undoes the edit properly

## More details

**Affected browsers/platforms:**
Browsers: Chrome, Firefox, Microsoft Edge
Platforms: Windows, Chromebook
(I didn't test any other browsers or platforms)

**First affected release:** r308

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: cannot change duration of non-animated image @ Error: cannot change duration of non-animated image at d.gaa (https://editor.construct.net/r308/projectResources.js:719:156) at OXa.s9b.lf (https://editor.construct.net/r308/projectResources.js:1820:164) at rM.JLb.lf (https://editor.construct.net/r308/projectResources.js:1770:405) at self.hp.lf (https://editor.construct.net/r308/projectResources.js:1770:405) at pM.Cjc.lf (https://editor.construct.net/r308/projectResources.js:1770:405) at pM.Cjc.lf (https://editor.construct.net/r308/projectResources.js:1862:207) at window.qc.Th (https://editor.construct.net/r308/projectResources.js:1774:19) at d.Th (https://editor.construct.net/r308/projectResources.js:1655:95) at window.Hab.Th (https://editor.construct.net/r308/main.js:2345:269) at Array. (https://editor.construct.net/r308/main.js:2318:478)
Stack: Error: cannot change duration of non-animated image at d.gaa (https://editor.construct.net/r308/projectResources.js:719:156) at OXa.s9b.lf (https://editor.construct.net/r308/projectResources.js:1820:164) at rM.JLb.lf (https://editor.construct.net/r308/projectResources.js:1770:405) at self.hp.lf (https://editor.construct.net/r308/projectResources.js:1770:405) at pM.Cjc.lf (https://editor.construct.net/r308/projectResources.js:1770:405) at pM.Cjc.lf (https://editor.construct.net/r308/projectResources.js:1862:207) at window.qc.Th (https://editor.construct.net/r308/projectResources.js:1774:19) at d.Th (https://editor.construct.net/r308/projectResources.js:1655:95) at window.Hab.Th (https://editor.construct.net/r308/main.js:2345:269) at Array. (https://editor.construct.net/r308/main.js:2318:478)
Construct version: r308
URL: https://editor.construct.net/
Date: Mon Sep 05 2022 10:16:36 GMT-0700 (Pacific Daylight Time)
Uptime: 158.2 s

Platform information
Product: Construct 3 r308 (stable)
Browser: Chrome 105.0.5195.102
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Vega 8 Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.

**Comment by ericcraft123456** [comment]
Do you know roughly when the next beta will be released?
