### ISSUE TITLE
Image Memory reading changes when the window is resized

### ISSUE THREAD

**Issue by Ninjadoodle** [Scirra/Construct-3-bugs#608]
## Problem description

Image Memory reading changes when the window is resized

## Attach a .c3p
[imageMemory.zip](https://github.com/Scirra/Construct-3-bugs/files/1140595/imageMemory.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open the project
2. Run in debug
3. Resize the browser window up and down and see the image memory reading change

## Observed result

Resize the browser window up and down and see the image memory reading change

## Expected result

The image memory reading should stay the same

## Affected browsers

Can only test in Chrome

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

No crash

</details>

**Comment by AshleyScirra** [comment]
This is not a bug, because the image memory includes the memory used for the double-buffered main surface.
