### ISSUE TITLE
Animation editor crashes if you paste something big and select enlarge canvas.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#6082]
## Problem description

I copy something outside of C3 and paste it into the image editor. If it's a large image and you select enlarge canvas option, it crashes the editor.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'style') @ TypeError: Cannot read properties of null (reading 'style') at https://editor.construct.net/r308/projectResources.js:2265:309 at e (https://editor.construct.net/r308/projectResources.js:2262:288) at https://editor.construct.net/r308/projectResources.js:2262:344
Stack: TypeError: Cannot read properties of null (reading 'style') at https://editor.construct.net/r308/projectResources.js:2265:309 at e (https://editor.construct.net/r308/projectResources.js:2262:288) at https://editor.construct.net/r308/projectResources.js:2262:344
Construct version: r308
URL: https://editor.construct.net/
Date: Tue Sep 06 2022 18:29:25 GMT+0300 (Eastern European Summer Time)
Uptime: 54.8 s

Platform information
Product: Construct 3 r308 (stable)
Browser: Chrome 105.0.5195.52
Browser engine: Chromium
Context: webapp
Operating system: macOS 12.5.1
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 10
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
</details>

**Comment by DiegoScirra** [comment]
How large does the image needs to be?

**Comment by bilgekaan** [comment]
300x300 for example, anything that you can use "enlarge canvas" I believe. 

Open a new project and create a sprite then paste an image with the enlarge canvas option.

example image:
![image](https://user-images.githubusercontent.com/2965842/188714546-2c021216-a9bd-4df8-9641-f7c6463c4e95.png)

**Comment by raassh-23** [comment]
This happened to me too. It seems like it crashes if you paste a large image in edit collision polygon mode.

**Comment by bilgekaan** [comment]
> This happened to me too. It seems like it crashes if you paste a large image in edit collision polygon mode.

Yes, it seems like it happens only if you are in collision or image point.

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta, was a regression introduced in r307.

Revision 17720.
