### ISSUE TITLE
Hierarchy does not load right.

### ISSUE THREAD

**Issue by bugalerto** [Scirra/Construct-3-bugs#6083]
## Problem description

Hierarchy children not keeping position after loading.

## Attach a .c3p

[hierarchysaveload.zip](https://github.com/Scirra/Construct-3-bugs/files/9501183/hierarchysaveload.zip)

## Steps to reproduce

1.Move diagonally and press S to save.
2.Press L to load.

## Observed result

Child does not keep position.

## Expected result

For child to keep position.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r309

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.

Revision 17743.
