### ISSUE TITLE
9-patch undo redo crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6084]
## Problem description

Construct crashes when I press `Undo` and `Redo` back and forth. To catch this crash you have to be like a predator patiently stalking its prey :feet:

## Attach a .c3p

[save_open_project_r309b.zip](https://github.com/WilsonPercival/WilsonPercival/files/9506545/save_open_project_r309b.zip)

## Steps to reproduce

1. Create a new project.
2. Add `9-patch`.
3. Draw a squiggle (alternative color).
4. Close the image editor.
5. Open the image editor.
6. Repeat steps 3, 4 and 5 3 times.
7. Cancel everything by pressing the Undo button.
8. Redo everything by pressing the Redo button.
9. Repeat steps 7 and 8 4 times.
10. Start randomly clicking either Undo or Redo.
11. Miss when clicking and accidentally hit the `Save project` button.
12. Close the save project window.
13. Repeat steps 7 and 8.
14. Repeat step 7.

## Observed result

![bug](https://user-images.githubusercontent.com/91274932/188889387-ce5ee480-343c-4588-ba1b-f99437b55389.gif)

Error report information
Type: unhandled rejection
Reason: Error: animation frame has no content @ Error: animation frame has no content at d.hH (https://editor.construct.net/r309/projectResources.js:727:341) at d.t3 (https://editor.construct.net/r309/projectResources.js:733:139) at https://editor.construct.net/r309/projectResources.js:652:211
Stack: Error: animation frame has no content at d.hH (https://editor.construct.net/r309/projectResources.js:727:341) at d.t3 (https://editor.construct.net/r309/projectResources.js:733:139) at https://editor.construct.net/r309/projectResources.js:652:211
Construct version: r309
URL: https://editor.construct.net/r309/
Date: Wed Sep 07 2022 15:56:52 GMT+0300 (Восточная Европа, летнее время)
Uptime: 49.3 s

Platform information
Product: Construct 3 r309 (beta)
Browser: Chrome 105.0.5195.54
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_float_blend, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, EXT_sRGB, KHR_parallel_shader_compile, OES_element_index_uint, OES_fbo_render_mipmap, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBGL_lose_context, WEBGL_multi_draw

## Expected result

No crash.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r309b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r309 (beta)
Browser: Chrome 105.0.5195.54
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 366 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This may not be possible to fix as we can't reliably follow steps like "randomly click on buttons". Usually we have to follow the same steps predictably 10+ times to fix the issue. If you can find a more reliable sequence of steps please update the issue.

**Comment by WilsonPercival** [comment]
> This may not be possible to fix as we can't reliably follow steps like "randomly click on buttons". Usually we have to follow the same steps predictably 10+ times to fix the issue. If you can find a more reliable sequence of steps please update the issue.

@AshleyScirra 
1. Create a new project.
2. Create a `9-patch`.
3. Draw a squiggle in it (alternative color).
4. Close the image editor.
5. Open the image editor and draw another squiggle in it.
6. Close the image editor.
7. Rewind to the very beginning by pressing the `Undo` button.
8. Pull the mouse sharply down.

![bug](https://user-images.githubusercontent.com/91274932/189097018-9cff48cd-09eb-4b54-ac86-c91444e083db.gif)

This bug does not work on the first try. Need practice. I can't provide easier steps to reproduce.

**Comment by LukeWolfGames** [comment]
Try this instead to reproduce the crash
1. Create a 9 patch object
2. Upload an image to the 9patch object
3. Exit the 9patch image editor window
4. Press CTRL+Z.

I was able to reproduce this in my own project after editing an existing 9patch by uploading a different image over the top, exiting the 9patch editor window and then press CTRL+Z.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
