### ISSUE TITLE
when text objects is child & it's parent is tween scaling then text scale is shaking 

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#6086]
## Problem description

I have a text object set as child of other object type when I do smooth scale to that object by tween then text scaling is very shaky. 

## Attach a .c3p
[tween scale text.zip](https://github.com/Scirra/Construct-3-bugs/files/9507405/tween.scale.text.zip)
![text scale issue](https://user-images.githubusercontent.com/17684135/188914504-8ef8fc29-8524-4d47-973f-042179ae50aa.gif)

## Steps to reproduce

1. set text object as child of sprite.
2. in runtime scale Sprite using tween.

## Observed result

text is flickering (not smooth). 

## Expected result
text should scale smoothly like sprite does

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
That's just how text is rendered in some browsers. IIRC some browsers are better than others at scaling text, but you didn't include which browser you tested so it's hard to compare what you were looking at.

**Comment by luckyrawatlucky** [comment]
uts chrome browser
