### ISSUE TITLE
Video User Media Recording does not work in Firefox depending on the sequence you request the user media sources

### ISSUE THREAD

**Issue by vicbarbosa** [Scirra/Construct-3-bugs#6088]
## Problem description

Problem with Video Recorder in Firefox: If in User Media you request camera first then microphone second, Video Recorder user media record will not work (Throws the error: "MediaRecorder.start: An audio track cannot be recorded: video/webm;codecs=vp8 indicates an unsupported codec")

If you request microphone first then camera second, the user media recording will work
>

## Attach a .c3p

[video-recorder-bug-firefox.zip](https://github.com/Scirra/Construct-3-bugs/files/9531238/video-recorder-bug-firefox.zip)

## Steps to reproduce

In firefox

1. request camera first
2. request microphone second
3. start recording
4. stop recording

## Observed result

Firefox throws an error and the recording fails but the Recording Error trigger never fires

## Expected result

Recording should work regardless of the media request sequence

## More details
Works normally if you request the microphone before camera

**Affected browsers/platforms:** Firefox

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r308 (stable)
Browser: Chrome 105.0.5195.102
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 70 gb
Storage usage (approx): 26 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is actually a mistake in your events. 'Start user media recording' will record only the last thing you requested - either the camera input or the microphone input, depending on the last thing you started. If you request microphone second then it is going to try to record just that, with an audio track only; however your 'Start user media recording' specifies a video format of 'Auto', which means it will use a default video format. However there is no video track in the recording so Firefox returns an error.

Instead you should set the video format to 'None' if you want to record only audio, or if you want to record camera and microphone at the same time, tick 'Include microphone' when requesting the camera.

**Comment by vicbarbosa** [comment]
Well... it does not work requesting both camera and microphone in the Request Camera + Include Microphone
Throws the same error in firefox (In the browser console) when you attempt to start the recording.

Here is the .c3p with only the button to request camera with microphone and buttons to start and stop recording...

[video-recorder-bug-firefox.zip](https://github.com/Scirra/Construct-3-bugs/files/9535705/video-recorder-bug-firefox.zip)

**Comment by AshleyScirra** [comment]
I'll take another look... might be a Firefox bug though.

**Comment by vicbarbosa** [comment]
I opened a new issue with the new c3p and updated problem description as I thought this one would be closed so there is a duplicate.  I apologize for that

Seems like it has to add opus to the MIME Type in order to work
video/webm;codecs=vp8,**opus**

https://github.com/w3c/mediacapture-record/issues/194
https://github.com/rico345100/react-multimedia-capture/issues/19

**Comment by AshleyScirra** [comment]
No worries, I'll close this and follow up in #6090.
