### ISSUE TITLE
Video Recorder does not work to record video with audio from User Media on Firefox

### ISSUE THREAD

**Issue by vicbarbosa** [Scirra/Construct-3-bugs#6090]
## Problem description

In Firefox:
Request UserMedia camera **with include microphone true**
![image](https://user-images.githubusercontent.com/27690689/189362946-07c0b2f1-4b49-4475-a31c-8ce70aff8ed4.png)

Attempt to Start User Media recording with VideoRecorder with Auto for video and Auto for Audio
![image](https://user-images.githubusercontent.com/27690689/189363971-487ee522-e4dc-4dd0-ac28-72c85a342111.png)

Throws this error in firefox console and does not record
![image](https://user-images.githubusercontent.com/27690689/189364032-603e4a51-0e41-45d0-8d70-26526b2ff370.png)

Uncaught (in promise) DOMException: MediaRecorder.start: An audio track cannot be recorded: video/webm;codecs=vp8 indicates an unsupported codec domSide.js:14
    _OnStartUserMediaRecording https://preview.construct.net/r308/plugins/media/videorecorder/dom/domSide.js:12
    GameRecorderDOMHandler https://preview.construct.net/r308/plugins/media/videorecorder/dom/domSide.js:3
    _OnEventFromRuntime https://preview.construct.net/workers/domSide.js:30
    _OnMessageFromRuntime https://preview.construct.net/workers/domSide.js:29
    onmessage https://preview.construct.net/workers/domSide.js:12

## Attach a .c3p

[video-recorder-bug-firefox.zip](https://github.com/Scirra/Construct-3-bugs/files/9535858/video-recorder-bug-firefox.zip)

## Steps to reproduce

In Firefox latest version
1. Request user media
2. Click Start Recording
3. Check browser console for an error

## Observed result

In firefox you can't record video with audio
## Expected result
Should be able to record video with audio

## More details

**Affected browsers/platforms:** Firefox 

**First affected release:** unknown

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r308 (stable)
Browser: Chrome 105.0.5195.102
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 49 gb
Storage usage (approx): 979 mb (2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
