### ISSUE TITLE
Specific function name causes crash in Edge

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#6093]
## Problem description

C3 installed as an app using Edge, r308 stable: creating a function with a specific name ( Achievement_DoTheHelicopter_AttemptIncreaseProgress ) causes C3 to crash: 
30 sec

https://user-images.githubusercontent.com/7268697/189486046-a394a1c9-f395-411e-93bc-0f9c1780e27b.mov

This does not happen in Chrome, so it could be an Edge bug.

## Attach a .c3p

Use a blank project.

## Steps to reproduce

1. Open a blank project
2. Go to events and try to create the function with the name "Achievement_DoTheHelicopter_AttemptIncreaseProgress"
3. Pressed enter / ok, and wait a bit - even click on some space

## Observed result

The app crashes

## More details

**Affected browsers/platforms:** C3 installed as an app in Edge browser 

**First affected release:** r308

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r308 (stable)
Browser: Edge 105.0.1343.33
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.375
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33
Language setting: en-US

Local storage
Storage quota (approx): 1006 gb
Storage usage (approx): 303 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by JeFawk** [comment]
Actually it might be related to the size of the Function, I wrote stuff like qweqwe_qweqweqwe_qweqweqweqweqweqwe and it crashed.

**Comment by AshleyScirra** [comment]
It works for me with both the names you mentioned.

The error shows Edge crashing with STATUS_ACCESS_VIOLATION. That means it's Edge itself crashing, not Construct. You'll need to report this to Microsoft for them to fix it.
