### ISSUE TITLE
Can't rearrange Layout folders

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#6096]
## Problem description

In 309, layout folders and subfolders can't be rearranged, moved, and reordered as they can be in 308.

## Attach a .c3p

(Any project)

## Steps to reproduce

1. Start a new project
2. Create layout folders A, B, and 0 
3. Try to rearrange their order
4. Note: the alphabetization is also not correct. 0 should come above A and B.

## Observed result

Dragging a folder only lets you put it into another folder, versus reorder it at its current level in the hierarchy.

## Expected result

The same rearrangement capability as 308.

## More details
EDIT: This is also true for Layers in the layer list.

**Affected browsers/platforms:**  Chrome 105.0.5195.52, Mac 12.5

**First affected release:**  309 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by brushfe** [comment]
308 
<img width="243" alt="308" src="https://user-images.githubusercontent.com/63005234/189544278-23188ca6-0122-4a4f-8e10-d36dcb8c1791.png">

309
<img width="243" alt="309" src="https://user-images.githubusercontent.com/63005234/189544289-62766e1f-f8a1-4f2a-8391-b9edd9b28c21.png">

**Comment by brushfe** [comment]
EDIT: This is also true for Layers, not just Layouts

**Comment by brushfe** [comment]
EDIT: This is also true for Layers

**Comment by AshleyScirra** [comment]
Thanks, both cases fixed for next beta.
