### ISSUE TITLE
Timeline SetTime multiple Tags doesn't work

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-3-bugs#6098]
## Problem description
Multiple Tags for Set Time (Timeline) does not work

## Attach a .c3p
[TimelinePositionBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9547941/TimelinePositionBug.c3p.zip)

## Steps to reproduce

1.preview the project
2.press space
3.close the project
4.in event 3 deactivate the multiple tag set time action and activate the two separate set time actions
5.repeat step 1 to 2

## Observed result
pressing space has no influence when multiple tags in on action are called

## Expected result
the two sprites should stopp their movement

## More details

**Affected browsers/platforms:** 
tested in r309 on mac, chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r309 (beta)
Browser: Chrome 105.0.5195.102
Browser engine: Chromium
Context: browser
Operating system: macOS 11.6.8
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 183 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 560 OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by bubbblebub** [comment]
it seems to be more than just the set time action. Timeline resume "tag1 tag2" also doesnt work with multiple tags, I have to make two different actions.

**Comment by DiegoScirra** [comment]
Just from looking at the example it looks like you are trying to do something that the tagging system does not do.

The action **Set "Q  W" time** is trying to set the time for any timeline which has both **Q and W** tags. Since the example doesn't have any timeline with both tags, nothing will happen.

**Comment by bubbblebub** [comment]
I see, thanks for the expanation. "Match any tags or all tags" like it is done in the on keyframe action would be handy, but of course I can just use multiple actions. thanks
