### ISSUE TITLE
Object.TemplateName doesn't work if Object Instance is Template Source

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-3-bugs#6099]
## Problem description

The expression Object.TemplateName returns nothing if the instance is a Template Source. 
(It only works if it's a Replica)

## Attach a .c3p

[TemplateSource Object.TemplateName issue.zip](https://github.com/Scirra/Construct-3-bugs/files/9556501/TemplateSource.Object.TemplateName.issue.zip)

## Steps to reproduce

1. Just launch the preview
2. The child text of the Template Source (on top of it) is empty, while the child text of the Replica correctly displays the Template name "MyTemplateName01"

## Observed result

![chrome_KaauKa8RDA](https://user-images.githubusercontent.com/99751718/189888329-47528615-7acc-4338-bcf8-b168c2275c27.png)

## Expected result

![chrome_XXt0PGjSnM](https://user-images.githubusercontent.com/99751718/189888601-83205d69-4e07-423d-a20a-beca426e10a2.png)

## More details

This makes all my system based on Hierarchies and Template very harder to set up.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
