### ISSUE TITLE
Animations are ordered backwards

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#6102]
## Problem description

When dragging a list of animations in the Animation Editor, placing them in the root folder reverses their order.

## Attach a .c3p

(New project)

## Steps to reproduce

1. Create a new project.
2. Create a new sprite, and open it In the Animation editor.
3. Duplicate "Animation 1" three times.
4. Create a sub-folder.
5. Select and drag all animations (1-4) into the sub-folder
6. Select and drag all animations (1-4) back into the root folder. 

Note: this can be done without the sub-folder. Select and drag the animations into the root folder while they're still in the root folder (see images below)

## Observed result

The animation list is reversed and has to be reordered by hand.

![Screen Shot 2022-09-14 at 6 14 09 AM](https://user-images.githubusercontent.com/63005234/190128220-03e24429-f9e1-4233-8409-17177200a53a.png)

## Expected result

The animation list stays in the same order.

![Screen Shot 2022-09-14 at 6 13 57 AM](https://user-images.githubusercontent.com/63005234/190128366-8e3389aa-38a0-4180-83d4-2c2938dd32f6.png)

## More details

**Affected browsers/platforms:** Chrome 105.0.5195.102, Mac 12.5.1 

**First affected release:** 309

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
