### ISSUE TITLE
Invert ease icon looks like a refresh icon

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6104]
## Problem description

Invert ease icon looks like a refresh/sync icon

## Observed result

![reaaa](https://user-images.githubusercontent.com/89512047/190166363-f5d3409f-f9c4-449a-8431-95db9efd893b.png)

## Expected result

![horizontal-swap-glyph-icon-vector-28873667](https://user-images.githubusercontent.com/89512047/190166544-c8d49941-835f-43c3-9f8a-73832f54e12f.jpg)

## More details
The icon I posted above is just a suggestion, there might be different/better solutions.
But when I first saw the button I asked myself "what would I refresh in the ease editor, doesn't make sense to me" then only after hovering and reading the tooltip it became clear to me what it does.

**Comment by DiegoScirra** [comment]
This will be changed for the next beta, at least just to make the icon different to the reload icon used elsewhere.
