### ISSUE TITLE
Bullet angle of motion resets if bullet speed is exactly 0

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#6105]
## Problem description

A bullets angle of motion resets to default (going right) if the bullet hits exactly speed 0.

## Attach a .c3p

[bulletAngle.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9569796/bulletAngle.c3p.zip)

## Steps to reproduce

1. Preview

## Observed result

The bullet will briefly stop (setting speed 0) then change the angle of motion when it continues

## Expected result

The bullet to stop, but then continue in the direction it was moving in.

## More details
I have a feeling I have seen this reported once already but it was dismissed because at speed 0 the bullet simply does not have an angle of motion/direction and falls back to default. I think it should retain the angle though if possible and I don't see a benefit in not doing so.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r310 (beta)
Browser: Chrome 105.0.5195.126
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 149 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is just how the maths work. What's the angle of a zero vector? It doesn't have an angle really.

It's also [noted in the manual](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/bullet) under AngleOfMotion:

> Note when the object is stopped (with a speed of 0), the angle of motion is always 0.

**Comment by brushfe** [comment]
@AshleyScirra I've run into this as well, and I see the point about the vector. But from the user's perspective, it's the bullet that has the angle, not the vector. And in this case, the bullet _had_ an angle, until its speed somehow changed that. 

It's like a car — stopping a car doesn't change the angle it faces. Math-wise it might make sense, but from object-wise it's strange.

**Comment by AshleyScirra** [comment]
Internally 'set speed' means 'set the magnitude of the movement vector'. If the movement vector is (0, 0), then it has no angle to preserve, so it goes to angle 0.

I recognise it's odd, but it is very easy to work around - you can just set the angle of motion again after setting the speed. Changing this is also risky: it's a basic feature that's very heavily used, and we've seen many times before how people literally make gameplay mechanics around every last quirk of Construct. So changing this could well be a breaking change, we might not find out about it until the next stable release, and then we have a lot of complaints about breaking people's projects to deal with. So, given how trivial the workaround is, my judgement is it's probably better to just live with it.

**Comment by Wackytoaster** [comment]
Ok, I'll file this one under engine quirks ^^
