### ISSUE TITLE
Loading saved game offsets hierachy items position and size

### ISSUE THREAD

**Issue by Aldenwar** [Scirra/Construct-3-bugs#6108]
## Problem description

In my deckbuilder, an issue has appeared where loading a save file breaks hierarchy positioning and size of one object in the hierarchy. Managed to make a minimal example now. Loading the same save a second time fixes the errors for some reason.

## Attach a .c3p

[HiearchyLoadBug.zip](https://github.com/Scirra/Construct-3-bugs/files/9579259/HiearchyLoadBug.zip)

## Steps to reproduce

1. Click on some cards on the right to "build a deck"
2. Click save
3. Exit the preview
4. Open preview again, load deck

## Observed result

The card copies counter has reset its position to the origin of the parent object, and the border attached has changed its size

## Expected result

Hierarchy looks exactly as it did when the game was saved

## More details

**Affected browsers/platforms:** Tested on Chrome and Brave 

**First affected release:**  r305 I think 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.

Revision 17834.
