### ISSUE TITLE
Project doesn't start if LFJS plugin is used if Worker is set to yes

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-3-bugs#6109]
## Problem description
Any project doesn't start if the LFJS plugin is used and Worker is set to YES.
The issue appears starting from R310 version.

## More details
debug show the following error:
![5rtq3QldnN](https://user-images.githubusercontent.com/58107632/190625900-805e149e-7af9-4724-a535-9ceebe5be44b.png)

**Comment by AshleyScirra** [comment]
Please follow all the bug report guidelines otherwise it's impossible to help, and note that in general issues with third-party addons need to be reported to the addon developer.

**Comment by rraffo** [comment]
Unfortunately, the developer has not replied to anyone for one year.
