### ISSUE TITLE
SpriteFont.textHeight shows incorrect height

### ISSUE THREAD

**Issue by q3olegka** [Scirra/Construct-3-bugs#6112]
## Problem description

SpriteFont.textHeight shows incorrect height. More precisely, it always shows the height at 100% scale

## Attach a .c3p

[sf_textheight_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/9591546/sf_textheight_bug.zip)

## Steps to reproduce

Change the scale of the text in the editor and see the preview

## Observed result

The scale of the text and its height change, but SpriteFont.textHeight always shows the same number

## Expected result

SpriteFont.TextHeight should display the actual height of the text in pixels

**Comment by AshleyScirra** [comment]
Fixed for next beta.
