### ISSUE TITLE
Construct 3 + greenworks seems slow when testing the game on steam.

### ISSUE THREAD

**Issue by Corradi** [Scirra/Construct-3-bugs#6116]
I have a integration of greenworks on my construct 3 project, did all the configs from nw.js etc

When testing the game on steam, If i press f12 to screenshot, I have a delay on it and when i press the buttons to open the steam overlay - the lag occurs as well.

is there a fix for this? or i'm missing some configuration?

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.
