### ISSUE TITLE
Android IAPs don't work in some countries

### ISSUE THREAD

**Issue by KekGames** [Scirra/Construct-3-bugs#6118]
## Problem description

It looks like MobileIAP currently doesn't work in some countries on Android. For example, in Indonesia, Thailand, Malaysia. Every time someone tries to make a purchase from these countries - the status stays "Payment pending" for a few days, after which it gets canceled

## Attach a .c3p

https://drive.google.com/file/d/1fJGHRV2EQa1azyoE_Gu_MfoPgry0watM/view?usp=sharing

## Steps to reproduce

1. Add IAP ID in project and on Google Play
2. Export to android
3. Test purchase from one of the countries (idk if it's possible)

## Observed result

None of the purchases work in those countries, but work in others. 

## More details
![Untitled-2](https://user-images.githubusercontent.com/42392288/190897298-807a35c6-578b-495a-a72f-ab69b0714567.png)

Here's the same issue report for Unity with relevant information.  https://forum.unity.com/threads/iap-doesnt-work-for-indonesia.1165847/

**Affected browsers/platforms:** Android

**First affected release:** Current stable, but also older versions

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I've looked in to this but on first investigation I don't think this is related to the code in Construct - it looks like it would come down to some code in the Cordova plugin we use that handles payments (cordova-plugin-purchase).

I've filed an issue with them here about it: https://github.com/j3k0/cordova-plugin-purchase/issues/1331
I'll be following up there to try to sort this out with them. I'll close this issue as it will be dealt with there so follow that issue for updates.
