### ISSUE TITLE
Renaming an animation does not immedietely update its references in event sheets

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#612]
## Problem description

If you've renamed animations and you have event sheets that reference the animation's name, it does update, or refresh, to the new name. 

It does not update after I've closed and reoponed the event sheet, or even after saving and opening the project!

## Attach a .c3p

[renaming bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1144371/renaming.bug.zip)

## Steps to reproduce

1. Click on sprite to see the animation name
2. Look at the event sheet to see the animation name

## Observed result

The animation editor and event sheet use different names to refer to the animation

## Expected result

The event sheet should immedietly update all references to the animation name, once it has been renamed.

**Comment by AshleyScirra** [comment]
This is not solvable in general. You can use runtime expressions like `"Animation" & number` and in the general case, the editor cannot know how to update these expressions. The same problem occurs with group names, create object by name, etc.

We could add a feature to cover the obvious cases, but then it would have a nasty gotcha of doing inconsistent updates when the editor can't statically analyse the name (such as when runtime expressions are used). I think the best solution is to use the 'Find all references' feature, which knows how to list ambiguous results so provides a useful tool to manually review all references and ensure they are correct. 'Find all references' doesn't cover animations yet, but I'll add that to my todo list.
