### ISSUE TITLE
Javascript/Editor linebreak/indent with long lines

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#6120]
## Problem description

Long lines in javascript wrap to the next line, but lose the indentation. Makes it a harder to read and other editors do retain that indentation.

![linebreak](https://user-images.githubusercontent.com/31101309/191002803-df71b20d-8851-48f2-994f-b952942e6ce3.PNG)

## Steps to reproduce

1. Write a long line in editor

## Observed result

Indentation lost after linebreak.

## Expected result

Indentation retained after linebreak

## More details

Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r310 (beta)
Browser: Chrome 105.0.5195.127
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 4.3 gb (3.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I don't think our text editor, CodeMirror, directly supports this. It's a special line-wrap-indent feature that only some text editors support. It would be best to track this as a feature request, but there doesn't appear to be a quick route to support it.

TBH I think it would be best to just use a folder project and an external editor like VS Code rather than have us reinvent the wheel in Construct. We'll never catch up with every last feature of something like VS Code, so there will always be a stream of bugs/requests along the lines of "VS Code does this but Construct's editor doesn't" - but you can just use an external editor of your choice with a folder project, so I'd say just do that.

**Comment by Wackytoaster** [comment]
Hmm bummer. But I'll stick to the C3 editor regardless for the autocomplete. (And for external coding I stick to notepad++, the ol' reliable)

I did a quick search around and found this
https://discuss.codemirror.net/t/making-codemirror-6-respect-indent-for-wrapped-lines/2881
https://gist.github.com/dralletje/058fe51415fe7dbac4709a65c615b52e

though I do not know if it works or not. It's not an urgent issue, so maybe next time you run low on work and get bored (lol) you could take another look.
