### ISSUE TITLE
When app is exported to debug.apk , "set playback time" is behaving like "restart video"

### ISSUE THREAD

**Issue by Kernonen** [Scirra/Construct-3-bugs#6122]
## Problem description

My project has a video object. There is also on screen a button with the following function
+ Toucher: On tap gesture on Button
-> Video: Set playback time to 10 seconds

in preview and online hosting, everything is fine : when button is clicked, video jumps to 10 seconds time. 
But when project is exported to debug.apk, button restarts the video. 

[## Attach a .c3p
[https://www.dropbox.com/s/ucqek2ob2ckht83/Video%20player%20Bug.c3p?dl=0](url)
[Video player Bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9598720/Video.player.Bug.c3p.zip)

## Steps to reproduce

1. add video object
2. add button object and link it to video with "set playback time"
3.  export project to debug.apk
4. upload project to Samsung S5e Tablet. Install project
5. run project 

## Observed result

6. press play 
7. press orange button to jump video playhead to 10 seconds    
8.  video restarts 

## Expected result

step 8 above, video playhead is supposed to jump to 10 seconds instead of restarting
## More details
Issue only in Android when playing export debug.apk
Works fine on every browser Mac and Android

**Affected browsers/platforms:** 

android
**First affected release:** 

## System details

Tablet Samsung S5E
![Screenshot_20220919-141928_Settings](https://user-images.githubusercontent.com/32126635/191015975-6f54954d-407a-4592-8379-1f42fb305d8f.jpg)

**Comment by AshleyScirra** [comment]
I can reproduce, but it appears to be a problem with Cordova itself. I filed an issue here: https://github.com/apache/cordova-android/issues/1494

Closing as it will be followed up there.

**Comment by Kernonen** [comment]
Thank you. 
So we have to wait for Cordova to fix the problem on their side ?

**Comment by AshleyScirra** [comment]
Yes, I'm afraid in this case it's outside our direct control.
