### ISSUE TITLE
Unable to save folder project after autosave fails

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#6129]
## Problem description

I sometimes need to work on a folder project which is over 7GB in size.
I have automatic backup set up in Construct settings, but whenever it prompts me to autosave this huge project, I usually hit Cancel.
I pressed Ok by accident today, Construct started autosaving and after about a minute displayed an error saying that there's no access to the folder. 
After that the manual save stopped working:

![image](https://user-images.githubusercontent.com/36763350/192085010-7b0907ad-f21c-4600-8921-b49d3f1e8b82.png)

## Expected result

If autosave fails, I should still be able to save the project manually.

Also, is it possible to disable automatic backups if the project exceeds certain size, say 1GB or 4GB?
I don't think saving 7GB backup as a single file would ever be useful.

## More details

**Affected browsers/platforms:** Chrome

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r308.2 (stable)
Browser: Chrome 105.0.5195.127
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 531 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
> but whenever it prompts me to autosave this huge project, I usually hit Cancel.

Construct doesn't ask to do autosaves, it just goes ahead and does them automatically on a timer. You actually showed a screenshot of the message you get when you open an autosaved project. So the description doesn't seem to match what you're actually doing.

I don't think the fact your project is 7 GB would affect this, it should be reproducible in a new project. As ever we need steps to reproduce to investigate, so please provide them if you can, otherwise it's unlikely we can do anything.

**Comment by dop2000** [comment]
> Construct doesn't ask to do autosaves

It does for me. First it shows this message:
![image](https://user-images.githubusercontent.com/36763350/192320918-ce01bc9e-acd6-4146-98f3-08096da74676.png)

Then this:
![image](https://user-images.githubusercontent.com/36763350/192321033-10d43a79-c0cc-43ce-84c1-b7bdcabcab45.png)

Here is where I hit "Cancel" when I'm working on that large project. After that it opens Settings window, which I close.

Yesterday I clicked "Edit files" by accident, and after a minute or so it showed me a message that saving failed, I don't remember exactly what was in it.
 
I'm not asking to fix the autosave of very large projects, I think C3 shouldn't autosave them at all - it will take too much time, disk space and system resources.

The problem is that I wasn't able to save the project after the autosave failed.

**Comment by AshleyScirra** [comment]
Right, that's the folder write permission prompt for the first autosave only when autosaving to a local folder. It doesn't appear with every autosave.

I tried following these steps:

1. Set up autosaves to a local backup folder
2. Open a project and make some changes
3. Wait for an autosave to the folder
4. Click 'Cancel' on the permission prompt
5. Go back to editing project and save it again

It all seems to work normally.

I had a check over some of the code involved in autosave and made a few tweaks to try to make sure it cleans up in case of an error, but I can't verify it works without being able to reproduce the problem. Anyway that change will be in the next beta, but if that doesn't help, I'd need reliable steps to reproduce it, so closing this issue.
