### ISSUE TITLE
After deleting a frame of animation it does not reselect the frame

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#613]
## Problem description

When you delete a frame of animation from the list of frames the selection changes away from the frame had selected before, and goes back to select the first frame of animation.

This was not an issue in Construct 2. 

The reason this is annoying is because when you delete frames from an animation you often want to do it from the same position.

## Attach a .c3p

[frame delete bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1144394/frame.delete.bug.zip)

## Steps to reproduce

1. Open the Sprite animation
2. Delete frame 2

## Observed result

Notice how it goes to frame 0 after deleting frame 2. 

## Expected result

It should go to frame 2 again, which was previously frame 3 before the deletion.

**Comment by DiegoScirra** [comment]
Ah, thanks for pointing this one out. I implemented this behavior but it never seemed quite right, I couldn't put my finger on it though.

**Comment by DiegoScirra** [comment]
Fixed in r45. 

Thanks for reporting.
