### ISSUE TITLE
ios 15.7 iphone6s text scale issue

### ISSUE THREAD

**Issue by q3olegka** [Scirra/Construct-3-bugs#6136]
When scaling the layer on which the text is located, there is a problem with scaling the text itself - it "shakes"

## Attach a .c3p
[ios_15.7_iphone6s_text-scale_issue.zip](https://github.com/Scirra/Construct-3-bugs/files/9639599/ios_15.7_iphone6s_text-scale_issue.zip)

## Steps to reproduce

Run the preview in the project on your iOS phone

## Observed result

The text that is on the scalable layer is shaking and does not have the smoothness of resizing

## Expected result

The text that is on the scalable layer should smoothly change its size. This can be seen on an android phone or on a PC, in any browser

## More details

IOS 15.7 version or lower

https://user-images.githubusercontent.com/50992459/192119196-8d00a6a7-d8a8-4cd8-bbb1-d2cf17005b14.mp4

r311 beta

**Comment by q3olegka** [comment]
please fix it as soon as possible

**Comment by AshleyScirra** [comment]
I believe this is a Safari bug caused by the fact it rounds text sizes to the nearest 1px, which breaks smooth scaling: https://bugs.webkit.org/show_bug.cgi?id=46987

It looks like there might be a fix for it soon.

**Comment by q3olegka** [comment]
@AshleyScirra 
Hello. This problem has appeared on android now. I do not know what happened and it does not seem to be related to the new C3 update. I also can't catch the exact moment when the problem appears. But, here's what I have for an android device: (I checked versions r300,311,312 and everywhere the problem behaves the same strange)

- the problem is missing in the preview of C3!
- the problem appears after the export
- the problem may not appear if the link to the game is opened in the browser chrome, but if the link to the game is opened via telegram, then it appears. After that, even if the same link is opened again separately in the browser, the problem reappears, although there was no problem before opening the link in the telegram.

It looks weird, but that's what I see for android. For iPhone, the problem always appears, even in the preview. 

Are you sure this is an external problem?

https://q3olegka.com/demo/c3-text

video: https://disk.yandex.ru/i/yCVPa-ahbEiYLQ 
or https://drive.google.com/file/d/1_Av1bZ1RakyPNbyoj6O-3-sZAzJVMk80/view?usp=sharing

**Comment by q3olegka** [comment]
@AshleyScirra Please let me know that you have viewed my message
