### ISSUE TITLE
Mac: CMD Button Shows ??? in Keyboard Condition

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#614]
## Problem description

When you add a "On Key pressed" Condition in the Event Sheet Editor, the preview of the popup of the Key Selection shows "???" when the (Mac-only) Key CMD is pressed

## Steps to reproduce

1. Open a new Project
2. Add the Keyboard behaviour
3. Add a Condition "On Key pressed" and try adding the CMD Button

##Screenshot

<img width="559" alt="bildschirmfoto 2017-07-13 um 12 49 45" src="https://user-images.githubusercontent.com/30116964/28163058-d300fb52-67c9-11e7-9f91-4744de3b35e9.png">

## Observed result

Shows as "???"

## Expected result

Should show up as CMD or Command. Mac uses Command instead of CTRL on Windows most of the time.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

Don't think it's necessary for this bug but if you need it, let me know...

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for r45.
