### ISSUE TITLE
Rename object type crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6144]
## Problem description

After renaming the object - Construct crashes.

## Attach a .c3p

https://www.dropbox.com/s/lxbznii1foy0laj/a50.c3p?dl=1

Save open project after crash: https://www.dropbox.com/s/36728hgfmvl6pgh/save_open_project.c3p?dl=1

## Steps to reproduce

1. Open a project.
2. Start making object clones. Tilt approximately 40-50 copies. I needed to make 38 copies.
3. Rename one of the objects.

## Observed result

![bug](https://user-images.githubusercontent.com/91274932/192295917-1468e773-df9e-43e7-a00b-3608fc098f4e.gif)

## Expected result

Construct does not crash, why all of a sudden.

## More details

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'xq') @ TypeError: Cannot read properties of null (reading 'xq') at d.Ye (https://editor.construct.net/r308-2/main.js:1471:495) at d.S2 (https://editor.construct.net/r308-2/main.js:1477:6) at jV (https://editor.construct.net/r308-2/components/bars/projectBar/projectBar.js:7:49) at https://editor.construct.net/r308-2/components/bars/projectBar/projectBar.js:21:114 at https://editor.construct.net/r308-2/main.js:1723:100
Stack: TypeError: Cannot read properties of null (reading 'xq') at d.Ye (https://editor.construct.net/r308-2/main.js:1471:495) at d.S2 (https://editor.construct.net/r308-2/main.js:1477:6) at jV (https://editor.construct.net/r308-2/components/bars/projectBar/projectBar.js:7:49) at https://editor.construct.net/r308-2/components/bars/projectBar/projectBar.js:21:114 at https://editor.construct.net/r308-2/main.js:1723:100
Construct version: r308.2
URL: https://editor.construct.net/
Date: Mon Sep 26 2022 16:50:44 GMT+0300 (Восточная Европа, летнее время)
Uptime: 109.8 s

Platform information
Product: Construct 3 r308.2 (stable)
Browser: Chrome 105.0.5195.54
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_float_blend, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, EXT_sRGB, KHR_parallel_shader_compile, OES_element_index_uint, OES_fbo_render_mipmap, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBGL_lose_context, WEBGL_multi_draw

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r308-2s

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r308.2 (stable)
Browser: Chrome 105.0.5195.54
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 673 mb (1.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The provided project already has lots of cloned sprites. If I rename one it works fine.

I cloned the original sprite 10 more times, and tried renaming one of the new clones. That also worked fine. I'm not sure what doing more than 10 clones would achieve.

Can you find a more reliable way to reproduce this issue?

**Comment by WilsonPercival** [comment]
I was able to reproduce the issue from scratch. Here are the steps:

1. Create a new project.
2. Create a new sprite.
3. Fill with pink.
4. Duplicate the frames. There should be 100 of them.
5. Close the animation editor.
6. Save the project.
7. Start cloning objects and try to rename the sprite.

[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/9648342/New.project.zip)

save open project after crash: [save_open_project_r311b.zip](https://github.com/Scirra/Construct-3-bugs/files/9648345/save_open_project_r311b.zip)

![bug](https://user-images.githubusercontent.com/91274932/192341275-32e87acd-a159-4359-b021-394ce95883cd.gif)

**Comment by WilsonPercival** [comment]
Another demo, showing the steps from the very creation of the project.

![bug](https://user-images.githubusercontent.com/91274932/192341748-12fca36c-7095-4e63-9d0f-a540c66f153a.gif)

**Comment by WilsonPercival** [comment]
I tried with a sprite, in which 100 frames are 1000x1000.

![bug](https://user-images.githubusercontent.com/91274932/192497105-9980dc0c-40e8-4b46-991d-05f23c626f46.gif)

**Comment by WilsonPercival** [comment]
I can't retry the crash if there is only one frame in the sprite. As I understand it, it is necessary that the cloning of the sprite takes some time and it was necessary to quickly rename it. To do this, you can create many large frames in the sprite.

![bug](https://user-images.githubusercontent.com/91274932/192498149-c78b1464-8123-4d0f-ae77-f198e2819469.gif)

**Comment by AshleyScirra** [comment]
I tried this a bunch of different ways and I still can't reproduce it. I even tried adding artificial waits of 2 seconds in the cloning process to deliberately slow it down, and it still didn't reproduce. I suspect it's somehow related to the speed of the system and if it responds too quickly then it's impossible to get to the rename step in time.

I made a speculative fix based on the crash report alone, but I can't verify it. I've marked this issue to check again after the next release.

**Comment by WilsonPercival** [comment]
> I tried this a bunch of different ways and I still can't reproduce it. I even tried adding artificial waits of 2 seconds in the cloning process to deliberately slow it down, and it still didn't reproduce. I suspect it's somehow related to the speed of the system and if it responds too quickly then it's impossible to get to the rename step in time.
> 
> I made a speculative fix based on the crash report alone, but I can't verify it. I've marked this issue to check again after the next release.

r312b:

![bug](https://user-images.githubusercontent.com/91274932/192741053-ef13bc04-48f5-46fc-8300-c3c8cb2e9e20.gif)

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'gq') @ TypeError: Cannot read properties of null (reading 'gq') at d.Xe (https://editor.construct.net/r312/main.js:1482:28) at d.u3 (https://editor.construct.net/r312/main.js:1487:120) at eV (https://editor.construct.net/r312/components/bars/projectBar/projectBar.js:7:49) at https://editor.construct.net/r312/components/bars/projectBar/projectBar.js:21:114 at https://editor.construct.net/r312/main.js:1733:100
Stack: TypeError: Cannot read properties of null (reading 'gq') at d.Xe (https://editor.construct.net/r312/main.js:1482:28) at d.u3 (https://editor.construct.net/r312/main.js:1487:120) at eV (https://editor.construct.net/r312/components/bars/projectBar/projectBar.js:7:49) at https://editor.construct.net/r312/components/bars/projectBar/projectBar.js:21:114 at https://editor.construct.net/r312/main.js:1733:100
Construct version: r312
URL: https://editor.construct.net/r312/
Date: Wed Sep 28 2022 12:17:38 GMT+0300 (Восточная Европа, летнее время)
Uptime: 118 s

Platform information
Product: Construct 3 r312 (beta)
Browser: Chrome 105.0.5195.54
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_color_buffer_half_float, EXT_float_blend, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, EXT_sRGB, KHR_parallel_shader_compile, OES_element_index_uint, OES_fbo_render_mipmap, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBGL_lose_context, WEBGL_multi_draw

**Comment by AshleyScirra** [comment]
To be clear, I mean the next release after r312. That release already came out yesterday.

**Comment by WilsonPercival** [comment]
> To be clear, I mean the next release after r312. That release already came out yesterday.

Okay, looking forward to the next one.

**Comment by AshleyScirra** [comment]
r313 is now out, can you check again there?

**Comment by WilsonPercival** [comment]
> r313 is now out, can you check again there?

Everything works great! I can't repeat)

![a](https://user-images.githubusercontent.com/91274932/193796475-e89f12d9-34f9-47a5-81e4-8c45f9d5d9b7.gif)

**Comment by AshleyScirra** [comment]
Great, thanks for confirming.
