### ISSUE TITLE
Error when exporting XCODE iOS project with Mobile Advert plugin

### ISSUE THREAD

**Issue by JayWKoko** [Scirra/Construct-3-bugs#6146]
## Problem description

Tried exporting an ios xcode project recently that uses the Mobile Advert plugin and it fails with the following error:

Running manual pod update
Pod update failed
~~/sh: 1: pod: not found

CordovaError: Promise rejected with non-error: undefined
at ~~/cordova:30:15
at processTicksAndRejections (node:~~/task_queues:96:5)

I also get similar errors when trying to export the Construct Mobile Collection Ironsource plugin. The collection support team told me it's a build service issue? Can anyone help?

## Attach a .c3p

[MobileAdvertIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/9657353/MobileAdvertIssue.zip)

## Steps to reproduce

1. Open blank project
2. Add the mobile advert plugin
3. Export for iOS, using xcode

## Observed result

Received a build failed error.

## Expected result

Expected the project to build as normal.

**Comment by AshleyScirra** [comment]
It's working for me, I suspect it's the same as was mentioned in this forum thread so it should be working now: https://www.construct.net/en/forum/construct-3/general-discussion-7/error-exporting-ios-xcode-172749
