### ISSUE TITLE
R312 - Failed to open project.  Check it is a valid Construct 3 project folder / single-file (.c3p) project (Chrome 101 - 105)

### ISSUE THREAD

**Issue by drewhamlett** [Scirra/Construct-3-bugs#6147]
## Problem description

None of my projects or projects in the "Example Browser" will load on 312 in Chrome.  311 and below works fine.  I've tried clearing out site data for Construct.  Logging out / etc.

Safari seems to work fine.

## Steps to reproduce

1. Use 312 - https://editor.construct.net/r312/ in Chrome.
2. Go to Example Browser
3. Try to open any project
4. Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.

## Observed result

`main.js:723 [Project] Exception opening:  TypeError: unexpected type`

```main.js:723 [Project] Exception opening:  TypeError: unexpected type
    at R.i (main.js:900:461)
    at d.UL (projectResources.js:1674:345)
    at d.PIb (projectResources.js:1678:9)
    at d.kfb (projectResources.js:1678:57)
    at d.uba (projectResources.js:1380:75)
    at d.Ha (projectResources.js:1383:226)
    at window.YQ.TRb (projectResources.js:1351:344)
    at window.HDa.Gkb (projectResources.js:1360:43)
    at window.HDa.Ha (projectResources.js:1361:308)
    at d.Ha (projectResources.js:1337:478)

```

## Expected result

Project to open

## More details

Chrome 101 - 105
Safari seems to be fine.

**Affected browsers/platforms:** 

**First affected release:** 

r312

## System details

<details><summary>View details</summary>
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,3
  Chip:	Apple M1 Pro
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	32 GB

</details>

**Comment by AshleyScirra** [comment]
I don't think there's any further action we can take on this without more details, so closing. If you find something like a browser extension that causes this problem, let me know which it is and I can try to figure out what's going on.
