### ISSUE TITLE
Construct not loading :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6148]
## Problem description

I reinstalled Windows 7, it had an older version of Google Chrome preinstalled. When I logged into it, it automatically updated to the latest version. Next, I tried to open Construct and couldn't. I tried opening Construct in incognito mode and it works great there. I tried clearing the cache, but that didn't help. And what cache if I reinstalled Windows? In mozilla everything works fine.

## Attach a .c3p

https://editor.construct.net/r308-2
https://editor.construct.net/r241
https://editor.construct.net/r312

## Steps to reproduce

1. Follow any of the links.

## Observed result

Infinitely shows this window:

![a1](https://user-images.githubusercontent.com/91274932/192884684-59c23b89-307f-4ae5-b8f5-4e12b34b4aff.png)

But if you click on the screen, it will show an error message and an error will pop up in the console:

![error](https://user-images.githubusercontent.com/91274932/192884592-9934743b-f8b2-4b93-b964-19f7ddc6163a.png)

## Expected result

The contract is loaded as before.

## More details

The new Windows is exactly the same as it was before.

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r241s, r308-2s, r312b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r308.2 (stable)
Browser: Chrome 106.0.5249.62
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 250 mb
Storage usage (approx): 1.1 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
All three links work fine for me. I've also not seen any reports from anyone else (if it wasn't loading for anyone at all, it would be a major incident). Are you sure it's not a problem with your Internet connection or something else?

**Comment by WilsonPercival** [comment]
> All three links work fine for me. I've also not seen any reports from anyone else (if it wasn't loading for anyone at all, it would be a major incident). Are you sure it's not a problem with your Internet connection or something else?

Internet in chrome works.

**Comment by WilsonPercival** [comment]
@AshleyScirra Could it be related to outdated certificates? I also do not open half of the sites in any browser except Mozilla. I was told that mozilla has its own database of certificates.

**Comment by AshleyScirra** [comment]
I don't think it's to do with certificates, otherwise the main page would fail to load and show an SSL warning.

Maybe the website had an outage when you were trying to load it. Perhaps try clearing the cache and reloading one more time?

**Comment by WilsonPercival** [comment]
> I don't think it's to do with certificates, otherwise the main page would fail to load and show an SSL warning.
> 
> Maybe the website had an outage when you were trying to load it. Perhaps try clearing the cache and reloading one more time?

@AshleyScirra I reinstalled Windows again. Next, the first thing I did was install the video driver (because the last time I tried to open Construct first, as soon as chrome was updated to the latest version). After that, I went to chrome, which had an old version, went to the editor and saw this:

![a1](https://user-images.githubusercontent.com/91274932/193099027-1835920a-beaf-4c68-aba8-9cd70f116cda.png)

Next, I waited for the chrome update:

![a2](https://user-images.githubusercontent.com/91274932/193099177-cfd21821-9d30-42dc-b798-f6e4a3c59168.png)

After that, chrome rebooted. I tried to go into the editor, but its page didn't even load. I waited five minutes. After that I decided to uninstall chrome via uninstall programs and reinstall it via offline installer. After that, the editor finally opened. You can close the issue.

**Comment by AshleyScirra** [comment]
OK, not sure what happened here, but I don't think we'll be able to figure it out.

**Comment by WilsonPercival** [comment]
> OK, not sure what happened here, but I don't think we'll be able to figure it out.

@AshleyScirra I reinstalled windows again. Now, after the automatic update of chrome, I have earned a construct. I didn't have to uninstall it and install the offline version.
