### ISSUE TITLE
R312 - Unable to export HTML5 project with minify enabled

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-3-bugs#6149]
## Problem description
Unable to export HTML5 project if minify mode is enabled.
![woq8aeXYuX](https://user-images.githubusercontent.com/58107632/193107985-cccee03d-ec11-4af3-a97e-cf1a5e5565da.png)

## Attach a .c3p
any c3 project, even an empty one.

## Steps to reproduce

1. export  to html5 a
2. enable minify mode (simple or advanced)
3. export 

## Observed result
The file is not generated and the export process doesn't complete

## More details

**Affected browsers/platforms:** 

**First affected release:** 
C3 R312 (the previous versions are not affected) using:
- Chrome Version 105.0.5195.127 (Official Build) (64-bit)
- Firefox 105.0.1 (64-bit)

Windows 10 Enterprise

## System details
See the debug log screenshot below:

<details><summary>View details</summary>
See the debug log screenshot below:
PASTE HERE
![cOdXGtf3ep](https://user-images.githubusercontent.com/58107632/193107812-b3ec6549-4f8a-481a-a85f-f9b7ddb18669.png)

</details>

**Comment by WilsonPercival** [comment]
Everything works well for me. Are you sure you waited long enough?

![a](https://user-images.githubusercontent.com/91274932/193140094-5166708e-412b-4bbb-be46-b1c605d977e1.png)

**Comment by AshleyScirra** [comment]
It works fine for me too, but it does take a while. I think you just need to be patient!

**Comment by rraffo** [comment]
The problem was indeed solved by refreshing the cache of the browser. Sorry to engage you with the issue but this is the first time I need to refresh the cache to solve a specific C3 function. I was misled by the fact that both Chrome and Firefox were affected by this problem with the R312 version only. And actually I'm not able to solve this issue on Firefox.
Do you confirm you don't have issue with Firefox as well?
And by the way, why minifying is taking so longer even with an empty project? I'm pretty sure it was faster weeks ago.

**Comment by WilsonPercival** [comment]
> The problem was indeed solved by refreshing the cache of the browser. Sorry to engage you with the issue but this is the first time I need to refresh the cache to solve a specific C3 function. I was misled by the fact that both Chrome and Firefox were affected by this problem with the R312 version only. And actually I'm not able to solve this issue on Firefox. Do you confirm you don't have issue with Firefox as well? And by the way, why minifying is taking so longer even with an empty project? I'm pretty sure it was faster weeks ago.

@rraffo Mozilla:

![s](https://user-images.githubusercontent.com/91274932/193700520-a609cccc-1770-4414-b164-cc13d1bb6f24.png)

**Comment by rraffo** [comment]
@WilsonPercival , @AshleyScirra is **50 minutes** a reasonable time for minifying an empty project?

**Comment by AshleyScirra** [comment]
It should finish much faster than that. What kind of CPU does your system have?

**Comment by rraffo** [comment]
@AshleyScirra I have a Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz   2.59 GHz 
The last screenshot is not from my PC.
By the way, I noticed that the minifying process has been taking longer than expected for a while. I'm not sure exactly when it started to be so slow, but it was a lot faster in the past.
If you look at the @WilsonPercival screenshots it appears it takes a different time to be completed.
In my case, an empty project takes 21 minutes.
![tPD19ZALwE](https://user-images.githubusercontent.com/58107632/193804319-33cd5839-78e7-45cf-8119-1089363d75ed.png)

**Comment by WilsonPercival** [comment]
> It should finish much faster than that. What kind of CPU does your system have?

@AshleyScirra 

![aaa](https://user-images.githubusercontent.com/91274932/193808925-1232853f-a0ef-4204-87a7-5ce4aa4467b3.png)
