### ISSUE TITLE
Drag scroll events to new line

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#615]
## Problem description

In C2 you could select a bunch of events  then drag them to the top or bottom edge of the event editor which would cause the event sheet to scroll allowing them to be repositioned beyond the screen.

I miss this ability with C3 and i'm forced to instead cut and paste which can cause problems if the selected events contain a local variable.

## Attach a .c3p

not required

## Steps to reproduce

1.
2.
3.

## Observed result

Can not drag selected events beyond the screen.

## Expected result

Be able to scroll the event sheet while dragging selected events lines.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Added for r52.
