### ISSUE TITLE
Ctrl + W shortcut key in browsers

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#6151]
## Problem description

In NWjs when pressing ctrl+w it closes the current tab (layout/event sheet), when using C3 in the browsers, even installed as an app, ctrl + w closes the whole app, and if the project was saved, it doesn't even ask if I want to close, it just shuts down.
I've been using this short key for years now, I can't tell you to how many times I accidentally closed C3 today.

## Attach a .c3p

Not c3p related.

## Steps to reproduce

1. Read description.

## Observed result

Read description.

## Expected result

Optimally it should work with the same keys, if that's not possible, then a different key and ctrl+w (quitting) should request confirmation before closing.

## More details

**Affected browsers/platforms:** All

**First affected release:** All

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by dop2000** [comment]
I agree that there should be a keyboard shortcut to close tabs in the editor.
I to had a hard time moving from the Desktop Build to web version and accidentally closed the editor at least a hundred times. There is a Chrome extension "Closure" you can install - it will prompt you if you accidentally press Ctrl-W or Ctrl-F4.

**Comment by AshleyScirra** [comment]
Unfortunately it appears the Ctrl + W shortcut cannot be overridden in browsers. This is probably to stop abusive pages preventing the user from closing the page.

I've added a Shift + W shortcut for the next beta though to close the current editor tab. Also note the editor should prompt before closing if you have unsaved changes and try to close the tab with Ctrl + W.

**Comment by avishaymizrav** [comment]
> Unfortunately it appears the Ctrl + W shortcut cannot be overridden in browsers. This is probably to stop abusive pages preventing the user from closing the page.
> 
> I've added a Shift + W shortcut for the next beta though to close the current editor tab. Also note the editor should prompt before closing if you have unsaved changes and try to close the tab with Ctrl + W.

Yes I know, but the problem is that I also do it a lot when the project is saved.
Most programs offer an option to show extra confirmation box when quitting, so these kind of things won't happen.
Is that possible for C3?
