### ISSUE TITLE
Fullscreen preview in browsers - browser overlays in the way

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#6152]
## Problem description

Full screen preview in browsers shows browser extra overlay when hovering the top of the screen with the mouse - to exit.
I need to be able to capture full screen game footage without it showing up.

## Attach a .c3p

Not c3p related

## Steps to reproduce

1. Run any project.
2. Press F11 for fullscreen.
3. Move the mouse cursor to the top of the screen.

## Observed result

Chrome shows X button overlay.
Firefox shows address bar.

## Expected result

Either don't show it at all, or add an option to disable it for previews.

## More details

**Affected browsers/platforms:** All

**First affected release:** All

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
That's part of the browser user interface and I'm afraid it's not possible for it to be customised. Further, I believe it's an important security mechanism to avoid confusing users with fullscreen content.

If you want to record a fullscreen video without browser controls, try using a desktop export.
