### ISSUE TITLE
Premission to edit file is not saved in browser.

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#6153]
## Problem description

Running C3 in Chrome, installed as an app.
Every time I open a local c3p file (same file) it asks again for permission: "Let site edit file.c3p".

## Attach a .c3p

Not c3p related

## Steps to reproduce

1.
2.
3.

## Expected result

Permissions to edit should be saved.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The permission is requested by the browser for security reasons and we cannot control that or bypass it in any way.
