### ISSUE TITLE
Alt + F4 to close dialog preview window

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#6154]
## Problem description

Pressing alt + F4 when preview in a dialog box shuts down C3 instead of closing the preview dialog box.

## Attach a .c3p

Not c3p related

## Steps to reproduce

1.
2.
3.

## Expected result

Alt+F4 should only close the dialog preview window, same as it does with the pop up preview window.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Alt+F4 is a system shortcut to close the current window. It cannot be intercepted by web pages.

When using a dialog preview, the current window is the browser window, and so that will be closed.
