### ISSUE TITLE
" Load Sprite from Url" will apply to all same sprite without select

### ISSUE THREAD

**Issue by WalkinginDarkness** [Scirra/Construct-3-bugs#6158]
## Problem description

use the function of " Load Sprite from Url" of an individual Sprite will update all the Sprite 

## Attach a .c3p

[hockney.zip](https://github.com/Scirra/Construct-3-bugs/files/9690741/hockney.zip)

## Steps to reproduce

1. allow camera and get the camera source
2.  snap to create a sprite
3. snap to create another sprite, and then all the sprite will be updated

## Observed result
![image](https://user-images.githubusercontent.com/29536554/193418539-68565fc1-7088-4025-8982-1d2557ecaa72.png)

## Expected result

Only the selected (pick the last created Sprite) sprite will be updated

## More details

![image](https://user-images.githubusercontent.com/29536554/193418748-c794f42d-e39e-4410-b18d-93e16893d94f.png)

**Affected browsers/platforms:** 

Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
You are loading in the same frame every time. Accordingly, the image will change for all sprites that play the same frame. You just need to add more frames and specify them when taking the snapshot:

[hockney_solution.zip](https://github.com/Scirra/Construct-3-bugs/files/9691080/hockney_solution.zip)

**Comment by WalkinginDarkness** [comment]
Thank you very much!!! @WilsonPercival
