### ISSUE TITLE
Crash when double-clicking on an animation in the image editor

### ISSUE THREAD

**Issue by floriandecupper** [Scirra/Construct-3-bugs#616]
## Problem description

When my 'player' object is opened in the image editor and I want to access a specific animation by double-clicking it, the app crashes. 

c3p attached as a .zip
[OnlineTestReport.zip](https://github.com/Scirra/Construct-3-bugs/files/1148059/OnlineTestReport.zip)

## Steps to reproduce

1. Double-click on the 'player' object, in the only layout created or directly in the object list
2. Once in image editor, double click on either 'jump' or 'run' animation

## Observed result

The app crashes. The crash happened nearly all the time on 'jump', all the time on 'run'

## Expected result

No crash. 

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection Reason: Error: Cannot read property 'ǃsw' of null @ TypeError: Cannot read property 'ǃsw' of null at r.ǃPdl.ǃxtb.then (https://editor.construct.net/r44/main.js:71:287211) at  Stack: TypeError: Cannot read property 'ǃsw' of null at r.ǃPdl.ǃxtb.then (https://editor.construct.net/r44/main.js:71:287211) at  Construct 3 version: r44 URL: https://editor.construct.net/ Date: Fri Jul 14 2017 11:49:37 GMT+0200 (CEST) Uptime: 34.1 s
Platform information
Browser: Chrome Browser version: 59.0.3071.115 Browser engine: Blink Browser architecture: (unknown) Context: browser Operating system: Mac OS X Operating system version: 10.12_5 Operating system architecture: (unknown) Device type: desktop Device pixel ratio: 2 Logical CPU cores: 4 User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36 C3 release: r44
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium) Numeric version: 2 Supports NPOT textures: yes Vendor: Intel Inc. Renderer: Intel(R) Iris(TM) Graphics 6100 Major performance caveat: no Maximum texture size: 16384 Point size range: 1 to 255.875 Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r45
