### ISSUE TITLE
[r44] Crash when use Resize Button on a sprite and set to 3x500 

### ISSUE THREAD

**Issue by gpibernats** [Scirra/Construct-3-bugs#617]
## Problem description

Crash when use Resize Button on a sprite and set to 3x500.

## Attach a .c3p

It happens creating a new project.

Video with example [here](https://www.dropbox.com/s/fzf1p7jcm7sz7ct/ResizeButtonBug_r44_14jul2017.mov?dl=0).
Blank project created by me [here](https://www.dropbox.com/s/zlg4v245vmei45a/ResizeBugTest.c3p?dl=0).

## Steps to reproduce

1. Create new project
2. Insert sprite
3. Click on layout to edit sprite
4. Resize Image button
5. Insert Width: 3 and Height: 500

## Observed result

Crash dialog.

## Expected result

Image resized or a dialog saying not possible/showing restrictions.

## Affected browsers

* Chrome: yes
* Firefox: -
* Edge: -
* Safari: -

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: invalid size @ Error: invalid size at ǃP.ǃo.ǃSJL.ǃScx (https://editor.construct.net/r44/main.js:2:396385) at ǃP.ǃo.ǃcv.ǃVn (https://editor.construct.net/r44/main.js:2:392620) at r.ǃPdl.ǃxtb.then (https://editor.construct.net/r44/main.js:71:287130) at 
Stack: Error: invalid size at ǃP.ǃo.ǃSJL.ǃScx (https://editor.construct.net/r44/main.js:2:396385) at ǃP.ǃo.ǃcv.ǃVn (https://editor.construct.net/r44/main.js:2:392620) at r.ǃPdl.ǃxtb.then (https://editor.construct.net/r44/main.js:71:287130) at 
Construct 3 version: r44
URL: https://editor.construct.net/
Date: Fri Jul 14 2017 13:12:26 GMT+0200 (CEST)
Uptime: 224.7 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r44

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r45.
