### ISSUE TITLE
Has los to object bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6172]
## Problem description

I throw a beam at an obstacle. I set the position of the point to the coordinates of the collision of the ray with the obstacle. The `has los to object` condition does not work if the obstacle is rotated.

## Attach a .c3p

[has_los_to_object_bug_r313b.zip](https://github.com/WilsonPercival/WilsonPercival/files/9735711/has_los_to_object_bug_r313b.zip)

## Steps to reproduce

1. Open and run the project.
2. Move the green sprite up and down.

## Observed result

![observed](https://user-images.githubusercontent.com/91274932/194605298-41798b34-9851-4639-8a48-783cb8dd0980.gif)

## Expected result

![expected](https://user-images.githubusercontent.com/91274932/194605314-bd3a32c6-13b1-4d59-9a08-735396de380c.gif)

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r313b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r313 (beta)
Browser: Chrome 106.0.5249.103
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 401 mb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
These events are weird: it raycasts to find the exact point of intersection, then checks line of sight to the exact point of intersection. Why would you want to do that?

This means the result of a line-of-sight check probably just comes down to which direction floating point calculations get rounded in, causing random or unpredictable results. That is just a general precision issue and not something I think it is worth trying to fix.

**Comment by WilsonPercival** [comment]
> These events are weird: it raycasts to find the exact point of intersection, then checks line of sight to the exact point of intersection - i.e. asking "do I have line of sight to a position exactly on the border of something that blocks line of sight?". Why would you want to do that?
> 
> This means the result of a line-of-sight check probably just comes down to which direction floating point calculations get rounded in, causing random or unpredictable results. That is just a general precision issue and not something I think it is worth trying to fix.

@AshleyScirra I make a rope like in the game `Worms`. First I throw one beam. Next, I will check if I can see the point of the last ray. If I don't see it, then I need to create a new point.

![a](https://user-images.githubusercontent.com/91274932/194875344-ab0bef14-849e-4e5e-9bd6-f955de87cdcf.gif)

**Comment by AshleyScirra** [comment]
Using the exact point of intersection of an obstacle will cause rounding errors. Move the hit point inwards a small distance (1px?) and you should have a safe point to use.

**Comment by WilsonPercival** [comment]
> Using the exact point of intersection of an obstacle will cause rounding errors. Move the hit point away from the obstacle a small distance (1px?) and you should have a safe point to use.

@AshleyScirra Yes, this is the first option that came to me and which I use. Another option is to ray cast instead of checking `has los to object` and checking if the coordinates are the same after rounding them up.
