### ISSUE TITLE
Find dialog width too small to show all options

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#6173]
## Problem description

Pressing cmd/ctrl+F opens the new Find dialog, but not wide enough to see options like "match case".

## Attach a .c3p

(Any project)

## Steps to reproduce

1. Open a project
2. Press cmd/ctrl+F
3. Try to enable Match Case

## Observed result

The dialog window only shows two of the options.

![Screen Shot 2022-10-07 at 2 05 23 PM](https://user-images.githubusercontent.com/63005234/194622019-880eb239-d154-411d-93ba-f88ae50c9399.png)

## Expected result

The full range of Find options were revealed when the dialog appeared.

![Screen Shot 2022-10-07 at 2 05 30 PM](https://user-images.githubusercontent.com/63005234/194622036-0b1751dc-7e25-4ec5-9eb6-32c140b21b57.png)

## More details

**Affected browsers/platforms:** Chrome 105.0.5195.125, Mac 12.6

**First affected release:** r313

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
This seems to be a problem of the theme, in the normal dark theme they get put in a row below.
You might want to contact mitsu (assuming this is DARCSS).

**Comment by brushfe** [comment]
Ah ok! I didn't realize this could be affected by a theme. It is indeed PROCSS. Thanks!
