### ISSUE TITLE
Collision data on cloned tilemaps can't be changed

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#6178]
If you clone a tilemap and change the collision on tiles in the cloned tilemap, whether by altering the collision polygon or toggling the Use Collision setting, behaviors like Platform and 8Direction don't use the altered collision. It appears that cloned tilemap collision can't be altered - whatever the original tilemap had for collision is what you're stuck with in the clone. 

There are also UI issues with the collision being displayed in the Tilemap view: the collision that's displayed with blue lines on the tilemap can get out of sync with what you see when editing the tile. Similarly, the collision shown in the viewport when "Show collision polygons"can be inaccurate - changing collision on the original can change what's displayed on clones and vice versa.

## Attach a .c3p
[TilemapCollisionBug.zip](https://github.com/Scirra/Construct-3-bugs/files/9743385/TilemapCollisionBug.zip)

## Steps to reproduce

1. Create a new project, add a **sprite** with the **platform** behavior and a default **tilemap** with the **solid** behavior.
2. Create a simple environment with the tilemap.
3. **Clone** the tilemap and add the clone to the layout.
4. **Edit collision** on one of the tiles in the cloned map - i.e., make a ramp from one of the tiles that the platform character should be able to slide up. (_Note that the Tilemap view doesn't show the blue polygons for the modified collision while the cloned tilemap is selected, but it does show the modified collision when the original tilemap is selected. In the layout, with Show collision polygons turned on, both tilemap instances show the modified collision._)
5. Delete the original tilemap instance from the layout.
6. Add the edited tile(s) to the tilemap.
7. Run the game and move the platform sprite around on the modified tiles on the cloned tilemap.

## Observed result

The collision from the original tilemap is used, not the modified collision of the cloned tilemap.

## Expected result

The modified collision should be used - the cloned tilemap shouldn't be tied to the original, or vice versa.

## More details

**Affected browsers/platforms:** 
Tested in Microsoft Store version/Edge in Windows.

**First affected release:** 
Tested in r308.2 and r313.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r313 (beta)
Browser: Edge 106.0.1370.37
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.37
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 76 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.

Revision 17886.
