### ISSUE TITLE
Crash with "animation frame has no content" when quick-assigning an image point

### ISSUE THREAD

**Issue by valerypopoff** [Scirra/Construct-3-bugs#618]
## Problem description

Construct crashes when creating new animation and trying to quick-assign an image point. It only  happens if I delete an empty frame after adding frames to a new animation

## Attach a .c3p

[Fighting.zip](https://github.com/Scirra/Construct-3-bugs/files/1148521/Fighting.zip)

## Steps to reproduce

1. Open Animations editor
2. Add new animation
3. Right click on Animation frames bar
4. Import frames -> From files
5. Select two files
6. Left click on Frame 0 (the one that is empty)
7. Press Delete key 
8. In Image points bar right click on "Origin 0" line
9. Quick assign -> Bottom

## Observed result

Construct crashes.

## Expected result

Image point 0 of the 0 frame is assigned to Bottom

## Affected browsers

* Chrome: yes
* Firefox: dunno
* Edge: dunno
* Safari: dunno

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r44/main.js, line 2, col 203848
Message: Uncaught Error: animation frame has no content
Stack: Error: animation frame has no content at p.ǃPCF (https://editor.construct.net/r44/main.js:61:189763) at p.ǃt_ (https://editor.construct.net/r44/main.js:61:193576) at ǃOx.ǃPRR.ǃOx.ǃSPh (https://editor.construct.net/r44/main.js:71:38269) at ǃOx.ǃPRR (https://editor.construct.net/r44/main.js:71:46289) at Function.ǃP.ǃY (https://editor.construct.net/r44/main.js:2:203827) at Function.ǃqE (https://editor.construct.net/r44/main.js:71:326636) at Function.ǃxfJ (https://editor.construct.net/r44/main.js:71:326506) at Function.n.ǃPN$.ǃxsy (https://editor.construct.net/r44/main.js:71:331808) at a.ǃxsE.ǃxsQ (https://editor.construct.net/r44/main.js:71:129446) at P.ǃPt (https://editor.construct.net/r44/main.js:71:131112)
Construct 3 version: r44
URL: https://editor.construct.net/
Date: Fri Jul 14 2017 16:07:02 GMT+0300 (Russia TZ 2 Standard Time)
Uptime: 41.2 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r44

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r45
