### ISSUE TITLE
nw.js not using the discreet gpu on laptops

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6181]
## Problem description
There have been issues encountered by developers releasing their game on steam with nw.js (for example Bio Gun and Astral Ascent) where laptops did not use the integrated gpu, leading to severe performance problems.

Relixes, a dev on Astral Ascent linked this https://github.com/toptensoftware/nvpatch and said that it fixes the problem.
Could something like this be added to the nw.js export option, maybe as a checkbox or as default?

**Comment by AshleyScirra** [comment]
Construct already asks for the high-performance GPU where there are multiple GPUs. I'm afraid this is a long-standing problem that dual-GPU laptops often ship with system-level software that overrides the GPU choice of applications. Often the system software forces the use of a power-saving GPU and only uses the high-performance GPU for known games, which unfortunately often fails to recognize indie games. They do however provide manual options to control which GPU is in use.

I'm not willing to integrate seemingly unmaintained code that describes itself as experimental in to commercial production software. If you can find any official AMD/nVidia documentation indicating a way to override the GPU selection, I'd look in to that. But the very purpose of the system-level software is to override what apps ask for, so I don't know why they would provide a way for the app to override the system-level software once more.

I think your two options are:

1) try to get your indie game recognised by the GPU manufacturers
2) tell your users that they may need to change settings on dual-GPU laptops

**Comment by jobel0092** [comment]
is there a way AMD/nVidia can recognize that it is a Construct game, or any game for that matter?   Would it just be a matter of contacting them and making a request?
