### ISSUE TITLE
Moving Behaviors in order, Crash

### ISSUE THREAD

**Issue by beebits** [Scirra/Construct-3-bugs#6184]
## Problem description

My problem was when i try to move the behaviors from a sprite.

## Steps to reproduce

Having activate around from the scene, and state in the scene the object behavior, and moving 

1.
2.
3.

## Observed result

Red screen and crash

## More details

**Affected browsers/platforms:**  Everyone

**First affected release: r314 beta

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r314/projectResources.js, line 558, col 493
Message: Uncaught TypeError: e.T is not a function
Stack: TypeError: e.T is not a function at window.SFb.YE (https://editor.construct.net/r314/projectResources.js:558:493) at lE.g.J.cLc.Nja (https://editor.construct.net/r314/projectResources.js:2691:41) at Array. (https://editor.construct.net/r314/projectResources.js:2686:394) at CCG.oi.g.J.Table.dispatchEvent (https://editor.construct.net/r314/main.js:1101:42) at ui (https://editor.construct.net/r314/main.js:405:250) at CCG.vi.g.J.Table.bH.Ed (https://editor.construct.net/r314/main.js:1687:476) at fya.Ea.W3a.Zd (https://editor.construct.net/r314/main.js:1682:84)
Construct version: r314
URL: https://editor.construct.net/r314/
Date: Wed Oct 12 2022 22:49:06 GMT+0200 (hora de verano de Europa central)
Uptime: 11231.1 s

Platform information
Product: Construct 3 r314 (beta)
Browser: Chrome 106.0.5249.103
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: es-ES

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon RX 5700 XT Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
Same issue as #6183
