### ISSUE TITLE
Intermittent crash when saving Platform to JSON

### ISSUE THREAD

**Issue by johnBrink** [Scirra/Construct-3-bugs#6187]
## Problem description

Sometimes, under conditions that I haven't been able to figure out, the game will crash when an object with the Platform behavior gets saved to JSON (either the System -> Save action or the Object.AsJSON expression). I haven't been able to figure out what causes this, but whatever the circumstances are, it happens every time.

Since I couldn't figure out a minimal test case, I instead did some debugging in the console.

This is the stack trace:

```
runtime.js:9 Uncaught (in promise) TypeError: this._wasOverJumpthru.GetUID is not a function
    at PlatformInstance.SaveToJson (runtime.js:9:507)
    at BehaviorInstance.SaveToJson (behaviorInstance.js:4:172)
    at Instance.SaveToJson (instance.js:29:407)
    at SpriteInstance.AsJSON (commonACEs.js:67:414)
    at ObjectExpressionNode.ExpObject (expNode.js:7:307)
    at ExpressionParameter._expressionFunc (expFuncs.js:129:20)
    at ExpressionParameter.GetExpression (parameter.js:6:340)
    at Action._RunObject_SomeParamsVary (action.js:22:421)
    at EventBlock._RunActions_Fast (eventBlock.js:26:97)
    at EventBlock.Retrigger (eventBlock.js:33:141)
 ```

During PlatformInstance.SaveToJson, when the error occurs, the value of `this._wasOverJumpthru` is equal to `true`. It's clear that this function expects the value to be an IInstance or null.

I searched for references to this variable, and I found what looks like the offending line: `this._wasOverJumpthru=!!this._runtime.GetCollisionEngine().TestOverlapJumpthru(this._inst)`. The function `TestOverlapJumpthru()` returns an IInstance as expected, but the `!!` converts it to a boolean.

The offending line looks like it's in the PlatformInstance constructor. This is the stacktrace from which that got called:

```
    at new PlatformInstance (runtime.js:3:91)
    at C3.New (jsutil.js:15:47)
    at BehaviorInstance._CreateSdkInstance (behaviorInstance.js:3:236)
    at Instance._CreateSdkInstance (instance.js:7:108)
    at C3Runtime.CreateInstanceFromData (runtime.js:58:349)
    at Layer.CreateInitialInstances (layer.js:10:40)
    at Layout._CreateInitialInstances (layout.js:29:407)
    at Layout._StartRunning (layout.js:25:359)
    at C3Runtime.Start (runtime.js:40:417)
```

## Attach a .c3p

I was unable to reproduce this in a test project.

## Steps to reproduce

I was unable to reproduce this in a test project.

## Observed result

The error in the stacktrace above

## Expected result

The Platform behaviors serialize without errors.

## More details

I am running Construct 3 as a Chrome "standalone" web app. I am previewing the game in a popup window.

**Affected browsers/platforms:**

I am running this in Chrome 106.0.5249.103.

**First affected release:**

This has been happening for a long time. I don't know what the current release was the first time this happened.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r308.2 (stable)
Browser: Chrome 106.0.5249.103
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 280 gb
Storage usage (approx): 2.1 gb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I had a look at the code and it does look like it sometimes mixes booleans with instances; I've fixed that for the next beta. However without repro steps this cannot be verified. I'll just have to let you test it again in the next beta and see if it helped.

**Comment by johnBrink** [comment]
Thank you very much! I'll keep an eye out for the next beta and test this ASAP.

**Comment by AshleyScirra** [comment]
@johnBrink - r315 is now out, can you check if the problem is resolved there?

**Comment by AshleyScirra** [comment]
Great, thanks for confirming.
