### ISSUE TITLE
Sprite + JSON container - System -> 'Create Object' w/ 'create hierarchy' throws exception 

### ISSUE THREAD

**Issue by SushiDestroy** [Scirra/Construct-3-bugs#6191]
## Problem description

The problem of this Issue [Sprite + JSON container - System -> 'Create Object' w/ 'create hierarchy' throws exception #4998](https://github.com/Scirra/Construct-3-bugs/issues/4998) is back on r308.2.

It can be reproduce with the .c3p of the original issue.

**Comment by DiegoScirra** [comment]
Looks like it was a different problem triggered by the same steps. Will be fixed in the next beta.

Revision 17912.
