### ISSUE TITLE
construct does not work when I enter mmi from an error

### ISSUE THREAD

**Issue by K4RANTHEBEST** [Scirra/Construct-3-bugs#6193]
## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>Error report information
Type: assertion failure
Message: no display text to parse
Stack: Error at ta.pTa (https://editor.construct.net/r308-2/main.js:969:289) at window.assert (https://editor.construct.net/r308-2/main.js:886:353) at window.tSa.ISb (https://editor.construct.net/r308-2/projectResources.js:1430:530) at Object.IA (https://editor.construct.net/r308-2/main.js:535:86) at zca (https://editor.construct.net/r308-2/main.js:213:293) at xca (https://editor.construct.net/r308-2/main.js:213:68)
Construct version: r308.2
URL: https://editor.construct.net/?startTour
Date: Mon Oct 17 2022 17:53:18 GMT+0200 (Ora legale dell’Europa centrale)
Uptime: 1.7 s

Platform information
Product: Construct 3 r308.2 (stable)
Browser: Chrome 106.0.5249.119
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: it-IT

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.
