### ISSUE TITLE
Cannot open project: audio file name issue

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-3-bugs#6198]
## Problem description

In recent beta releases of Construct, projects with an **Audio:Play** action that tries to play an audio file whose name ends in a dot cannot be opened for some reason.

## Attach a .c3p

https://drive.google.com/file/d/1VEbe4JpM8toaoWag142KqCIOVjlA0Zp2/view?usp=sharing

## Steps to reproduce

1. Download the project from the link above
2. Try to open it in the latest stable (r308.2) and beta release (r315)

## Observed result

The project doesn't open in beta (but does in a stable).

## Expected result

The project should open successfully in both (beta and stable).

## More details

**First affected release:** r309

**Comment by AshleyScirra** [comment]
That's a weird filename... but if it used to work it should still work, so fixed for the next release.
