### ISSUE TITLE
Sprite Modification does not trigger Save Condition

### ISSUE THREAD

**Issue by TGeneDavis** [Scirra/Construct-3-bugs#62]
## Problem description

If you have a saved project, then change the ordering of the frames in a sprite, the project does not detect that it needs to be saved again.

## Attach a .c3p

[Ski Penguin Ski.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/917053/Ski.Penguin.Ski.c3p.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Save a project with one sprite that has two frames
2. Open the sprite and drag frame one to the frame zero position
3. Close the sprite editor

## Observed result

The project does not recognize that it has changed and needs to be resaved. The save icon is still grayed out.

## Expected result

The project should have activated the save icon

## Affected browsers

* Chrome: yes
Only tested on Chrome

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Chrome 57 on newest OS X

</details>

**Comment by DiegoScirra** [comment]
Fixed. Will be available in r18.
