### ISSUE TITLE
Crash when editing my file

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#620]
## Problem description

I was just editing my inventory prototype. It's kind of a tricky bug because i don't think i did any repeated action to call it but Construct crashed on me several times within half an hour, usually while editing an Event.

## Attach a .c3p

[20170714_Inventory.zip](https://github.com/Scirra/Construct-3-bugs/files/1149194/20170714_Inventory.zip)

## Steps to reproduce

1. I opened my File
2. Was working on an additional feature to use Inventory Items on Objects
3. Was just editing in the Event Sheet Editor

## Observed result

Construct closed unexpectedly and gave me a Crash Report.

## Expected result

Not crashing

## Affected browsers

* Chrome: yes

## System detail

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃP.ǃSw (https://editor.construct.net/r44/main.js:2:177185) at d.ǃzP.ǃka (https://editor.construct.net/r44/plugins/sprite/plugin.js:1:6668) at d.ǃzP.ǃkX (https://editor.construct.net/r44/plugins/sprite/plugin.js:1:5757) at Array.ǃV.ǃP.ǃY.ǃP.ǃF.ǃj (https://editor.construct.net/r44/plugins/sprite/plugin.js:1:5288) at ǃP.Event.ǃSgx.ǃSg_ (https://editor.construct.net/r44/main.js:2:255404) at window.ǃxcm.dispatchEvent (https://editor.construct.net/r44/main.js:2:253882) at window.ǃxcm.ǃxAR (https://editor.construct.net/r44/main.js:162:42964) at n.ǃfG.then (https://editor.construct.net/r44/main.js:162:39995) at 
Stack: TypeError: unexpected type at Function.ǃP.ǃSw (https://editor.construct.net/r44/main.js:2:177185) at d.ǃzP.ǃka (https://editor.construct.net/r44/plugins/sprite/plugin.js:1:6668) at d.ǃzP.ǃkX (https://editor.construct.net/r44/plugins/sprite/plugin.js:1:5757) at Array.ǃV.ǃP.ǃY.ǃP.ǃF.ǃj (https://editor.construct.net/r44/plugins/sprite/plugin.js:1:5288) at ǃP.Event.ǃSgx.ǃSg_ (https://editor.construct.net/r44/main.js:2:255404) at window.ǃxcm.dispatchEvent (https://editor.construct.net/r44/main.js:2:253882) at window.ǃxcm.ǃxAR (https://editor.construct.net/r44/main.js:162:42964) at n.ǃfG.then (https://editor.construct.net/r44/main.js:162:39995) at 
Construct 3 version: r44
URL: https://editor.construct.net/
Date: Fri Jul 14 2017 19:12:55 GMT+0200 (CEST)
Uptime: 2574.6 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r44

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I think Diego has fixed this already, it should be working in r45.
