### ISSUE TITLE
'Remember this access code' doesn't work.

### ISSUE THREAD

**Issue by iamthepineapple** [Scirra/Construct-3-bugs#6200]
When putting an access code in, the option 'remember this access code' doesn't actually work. If you check it, leave, then come back on, you have to re-enter the access code. This is kind of annoying, so it being fixed would be nice.

**Comment by AshleyScirra** [comment]
I just tried it and it remembers it fine for me. Please always follow the bug report guidelines otherwise it's impossible for us to help.

**Comment by iamthepineapple** [comment]
Ok.
