### ISSUE TITLE
Parameters dialog autocomplete: The height is too long if options are less

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6201]
## Problem description

When I create a new object, I type in the Template name box. You'll notice that the autocomplete list only has one option, but it's such a long window
![Snipaste_2022-10-20_00-25-45](https://user-images.githubusercontent.com/45864744/196753266-16bc60e4-947b-4428-9dd8-87f0743b6170.png)

## Attach a .c3p

[issue-autocomplete-height.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9822603/issue-autocomplete-height.c3p.zip)

## Steps to reproduce

1. Try type in Template name - `"`

## Observed result
 
![Snipaste_2022-10-20_00-50-24](https://user-images.githubusercontent.com/45864744/196754714-6a457108-195b-4f7d-bc9d-c48157396b71.png)

## Expected result

min-width: 100 px
min-height: 60 px

![Snipaste_2022-10-20_00-51-24](https://user-images.githubusercontent.com/45864744/196754757-ac999712-4f1f-4021-b3ce-ce37eb4e8411.png)

## More details

**Affected browsers/platforms:** Chrome 106, Windows 11 22H2

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r315 (beta)
Browser: Chrome 106.0.5249.119
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 424 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Super with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I've adjusted the styles to allow the autocomplete box to shrink to fit content if it's not got much content.

As we are near a stable release and this is a cosmetic change only, it will come out in the next release cycle (first beta release after next stable release).
