### ISSUE TITLE
Touch does not persist after waiting for an async event

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6202]
## Problem description

It may be my usage is wrong. After the previous Tween finishes playing, it rotates to the Touch, but moves to the (0, 0) position. I use the Touch object's directly. Therefore, the Touch object is already undefined at this time.

![Snipaste_2022-10-20_12-31-38](https://user-images.githubusercontent.com/45864744/196856949-14fb9ec2-618f-4235-83a2-64c7cb84963b.png)

but if I store it using a variable it works fine.
![Snipaste_2022-10-20_12-31-51](https://user-images.githubusercontent.com/45864744/196856959-5bc7e15f-725b-4460-8d4d-7bb828ccc26a.png)

## Attach a .c3p

[touch-tween-await.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9826280/touch-tween-await.c3p.zip)

## Steps to reproduce

1. Click anywhere on the screen

## Observed result

1. Rotate to touch
2. Move to (0,0)

## Expected result

1. Rotate to touch
2. Move to touch

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r315 (beta)
Browser: Chrome 106.0.5249.119
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 89 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is not a bug: if you always display the values of Touch.X and Touch.Y, you'll see they are both 0 when there is not an active touch. If you wait for a period of time and then read those values again when there is not a touch, they will return 0. Your alternative events that remember the touch position are the correct way to handle this.
