### ISSUE TITLE
add to family context menu icon incorrectly displayed

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6203]
## Problem description
The add to family context menu icon is incorrectly displayed.

## Attach a .c3p
[conFamilyIconIncorrect.zip](https://github.com/Scirra/Construct-3-bugs/files/9828562/conFamilyIconIncorrect.zip)

## Steps to reproduce

![tileIconIncorrect](https://user-images.githubusercontent.com/89512047/196915206-c244676b-e50c-44a6-8959-a7de82622a3f.png)
1. Right-click Sprite2 in the project bar
2. Hover add to family

## Observed result

icon seems to be misplaced on the spritesheet /offset part of the spritesheet is pulled.

## Expected result

the family icon is displayed correctly

**Comment by AshleyScirra** [comment]
I don't see this happening in the default theme. It looks like the dark theme styles are breaking this.

**Comment by AshleyScirra** [comment]
I've adjusted the light/dark themes to fix this. As we are near a stable release and this is only a cosmetic issue, it will be in the next release cycle (first beta release after the next stable release).
