### ISSUE TITLE
Can't select drop-down menu options when they're over an image selection

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#6205]
In the Animation Editor, when part of the image is selected, you can't select drop-down menu options (such as Crop -> Apply to all animations).

(Any project should work)

## Steps to reproduce

1. Open a sprite in the Animation Editor.
2. Select part of the image with the Rectangle Select tool.
3. Pan the image so that the selected part is "underneath" the top toolbar (see image below if that's unclear). 
4. Click the "Crop" tool.
5. Try to select the "apply to all animations" option.

## Observed result

The option flickers green for a moment, then remains unselected.

![croperror1](https://user-images.githubusercontent.com/63005234/197308945-c84aaae2-0c60-42f3-9bf4-c669a5049200.png)

## Expected result

The option would take mouse priority over the image selection.

![croperror2](https://user-images.githubusercontent.com/63005234/197308949-f779738d-1ef1-46c6-b4cb-709ebeca83e2.png)

## More details

**Affected browsers/platforms:** Latest Chrome stable and OS 12.6 

**First affected release:** r315

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This one will be fixed in the next beta release.

Revision 17950.
