### ISSUE TITLE
The Tween behavior has extra propgroups

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6206]
## Problem description

This question is not important. It may be caused by the previous design, but it is forgotten.

If 'Tween' has no extra properties, it should have no more groups, like 'Timer'

![Snipaste_2022-10-22_18-20-59](https://user-images.githubusercontent.com/45864744/197334074-bb7e92eb-3e4c-43d0-ad5c-fed98bdb9298.png)

## Attach a .c3p

[tween-properties-group.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9844073/tween-properties-group.c3p.zip)

## Observed result

![Snipaste_2022-10-22_18-21-07](https://user-images.githubusercontent.com/45864744/197334077-7ed84302-7ce0-42aa-9d69-d51f38798f3d.png)

## Expected result

![Snipaste_2022-10-22_18-26-20](https://user-images.githubusercontent.com/45864744/197334273-83c5de8f-c634-450f-a8c0-57507af54d8d.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
The Tween behaviour has one property, **Enabled**.
