### ISSUE TITLE
Renaming families doesn't sort family list alphabetically

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#6207]
When renaming a family, the order of the family list doesn't update to be alphabetically sorted. Only by creating a new family does the list sort again.

(New project)

## Steps to reproduce

1. Start a new project.
2. Create a sprite.
3. Create a family with that sprite. Leave the name as Family1.
4. Create a second family with that sprite. Leave the name as Family2.
5. Rename "Family2" to "Alphabetical".
6. Note the list doesn't sort itself.
7. Create a third family with the sprite. Leave the name as Family3.
8. Note the list now sorts.

## Observed result

The family list doesn't sort alphabetically.

## Expected result

The family list is always sorted alphabetically - in this case, after renaming a family.

## More details

**Affected browsers/platforms:**  Latest Chrome stable on Mac OS 12.6

**First affected release:** r315

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release cycle.
