### ISSUE TITLE
Mac/Safari: Crash when attempting to Copy and Paste in Animations Editor

### ISSUE THREAD

**Issue by tengine-gd** [Scirra/Construct-3-bugs#6208]
## Problem description

Instant crash simply from pressing the copy (Cmd + C) or paste (Cmd + V) shortcuts while Animations Editor window is open. Undo/Redo do not cause this problem. 
Setting "Use in-app clipboard" does not solve this problem.

[Example Project](https://www.dropbox.com/s/4u2r2ixp3rrmzkp/imageEditorBug.c3p)

## Steps to reproduce

1. Click on black Sprite to open Animations Editor
2. Press either Cmd + C or Cmd + V

## Observed result

Instant appearance of "Oops! Something went wrong." dialog

## Expected result

Perform copy or paste function

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Type error @ query@[native code] @https://editor.construct.net/r308-2/projectResources.js:371:129 asyncFunctionResume@[native code] @https://editor.construct.net/r308-2/projectResources.js:369:56 asyncFunctionResume@[native code] @https://editor.construct.net/r308-2/projectResources.js:2111:10 asyncFunctionResume@[native code] DFa@https://editor.construct.net/r308-2/projectResources.js:174:78 ro@https://editor.construct.net/r308-2/projectResources.js:2100:451 @https://editor.construct.net/r308-2/projectResources.js:2058:291 Wd@https://editor.construct.net/r308-2/projectResources.js:2322:377
Stack: query@[native code] @https://editor.construct.net/r308-2/projectResources.js:371:129 asyncFunctionResume@[native code] @https://editor.construct.net/r308-2/projectResources.js:369:56 asyncFunctionResume@[native code] @https://editor.construct.net/r308-2/projectResources.js:2111:10 asyncFunctionResume@[native code] DFa@https://editor.construct.net/r308-2/projectResources.js:174:78 ro@https://editor.construct.net/r308-2/projectResources.js:2100:451 @https://editor.construct.net/r308-2/projectResources.js:2058:291 Wd@https://editor.construct.net/r308-2/projectResources.js:2322:377
Construct version: r308.2
URL: https://editor.construct.net/
Date: Sat Oct 22 2022 17:12:38 GMT+0100 (British Summer Time)
Uptime: 18.7 s

Platform information
Product: Construct 3 r308.2 (stable)
Browser: Safari 16.0
Browser engine: WebKit
Context: browser
Operating system: macOS 10.15.7
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
Language setting: en-US

WebGL information
Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 511
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by DiegoScirra** [comment]
This will be fixed starting on the next release cycle.

Revision 17955.
