### ISSUE TITLE
Platform Behaviour: "Is next to wall" condition does not trigger when underneath solid tile

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-3-bugs#621]
## Problem description

The Is next to wall condition only triggers if the sprite testing the condition doesn't have a solid tile above it.
## Attach a .c3p

https://www.dropbox.com/s/90krbak275kg0sc/101_00.c3p?dl=0

## Steps to reproduce

1. Open c3p file
2. Preview layout
3. Walk the avatar underneath tiles on far right and left of window
4.Push into wall

## Observed result
The normal idle (forward-facing) animation is displayed.

## Expected result
The left-facing animation should be displayed when pushing into a left wall (and v.v.) regardless of the presence of a tile above it. 
You can confirm the correct behaviour by repeating the action on the central block of tiles or right clicking on the ceiling tiles on the left and right to remove them. Left click to replace.

Not that the collision on the avatar shouldn't be overlapping with ceiling tile as it is 1px smaller than the tile height.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It would help if you could make a minimal repro, the project has ~40 events which are mostly unnecessary to demonstrate the issue, it should be possible to show it in 1-2 events.

Anyway, looking at the code it appears to be a deliberate feature to not count as against a wall if the player is directly against an above obstacle. Unfortunately this code was originally written in 2011 and I can't remember the rationale for it :-\ so I'm concerned if I change this back, we'll break some other case that was meant to cover. Also with 6 years of games designed with the condition working as it is, there's a backwards-compatibility concern of breaking existing games that work with the fact the condition is false in these circumstances.

**Comment by jakemay74** [comment]
Yes, sorry, I normally try to keep the repros minimal - I left in the tile placement code so that you could experiment with adding and removing tiles to test if necessary, as mentioned in the expected results.

You actually explained why you left it as is in a C2 bug post a while back (I found this out after reporting the bug):

https://www.scirra.com/forum/r123-2-is-by-wall-miss-detection_t81392

Seeing as this is C3 and you're still in beta I thought it might be worth revisiting the issue and improving the behaviour.  


As it stands next to wall is a bit useless as you have no guarantee that it will work in all circumstances where the object is, in fact, next to one. I'm also wondering how many games would actually be deliberately using the fact that this doesn't work as expected and how many of those would be ported to C3.

If this ends up being a no fix  then how about adding a note to the manual or a tip to the behaviour so that users are aware of this restriction - might prevent some repeat bug reports?

**Comment by AshleyScirra** [comment]
Okay, I think it is more intuitive to have the condition true in this case, but I'm nervous about changing such old code. I've changed it for both Construct 2 and Construct 3. We'll see if it sticks. If it causes a significant backwards-compatibility problem we'll probably revert it and just say to use an "overlapping at offset" workaround as mentioned in that thread.

**Comment by jakemay74** [comment]
Cool, cheers Ashley :)
