### ISSUE TITLE
Shift+W with a highlighted array cell closes array

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#6210]
Typically when you single-click an array cell and start typing, the cell is opened, and what you type is put into the cell. But when you press Shift+W, the entire array sheet closes.

I think this has to do with the keyboard shortcuts recently introduced?

## Attach a .c3p

(Any project should work)

## Steps to reproduce

1. Create an array project file.
2. Single-click on the first cell (to highlight, not to edit)
3. Press shift+L
4. Note that "L" is entered into the cell.
5. Try the above steps again, but press shift+W at step 3.

## Observed result

The array sheet closes.

## Expected result

The letter "W" would be entered into the cell.

## More details

**Affected browsers/platforms:** Latest Chrome stable on MacOS 12.6

**First affected release:** 315

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by avishaymizrav** [comment]
@DiegoScirra 
Maybe changes it to Shift+Alt+W ?
So it can also be used to close scripts and other editor windows that are not event sheets or layouts.

**Comment by DiegoScirra** [comment]
This is one of those shortcuts that need to be ignored when a text input has focus, because there is a 99.9% chance you want to type a W, rather than close the tab.

**Comment by avishaymizrav** [comment]
With just shift yeah, but you wouldn't hold alt if you wanted to type. And I think this should work on all type of windows the editor supports.

**Comment by DiegoScirra** [comment]
Since the **Shift + W** shortcut was added in this beta cycle and it introduced some unexpected behaviour it will be removed for the upcoming stable release.

Starting with the next beta cycle it will be replaced by the **Alt + W** which shouldn't conflict with any other shortcut and will also work to close data editor tabs and text editor tabs.
