### ISSUE TITLE
PlatformInfo "Is NW.js export" does not trigger when remote previewing on NWjs

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#6211]
## Problem description

Platform info "Is NW.js export" does not trigger when remote previewing on NWjs

## Attach a .c3p

[nwjsplatform.zip](https://github.com/Scirra/Construct-3-bugs/files/9846653/nwjsplatform.zip)

## Steps to reproduce

1. Run project in remote preview.
2. Access remote preview link in NWjs with the remote preview package.json

## Observed result

Construct doesn't recognize it is running in NWjs.

## Expected result

Should return true.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release cycle.
