### ISSUE TITLE
The editor's root folder can be copied.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6215]
## Problem description

just look at the picture.

Select the folder
![Snipaste_2022-10-25_22-14-33](https://user-images.githubusercontent.com/45864744/197798369-1b5dcdf0-df7f-4acf-9050-b1cfe63314c2.png)

Then go crazy and hit the paste button.
![Snipaste_2022-10-25_22-14-46](https://user-images.githubusercontent.com/45864744/197798395-74811e07-c440-4729-b470-a0e7cb49a7fc.png)

Well, it's not just the 'layouts'folder can be copied.
![Snipaste_2022-10-25_22-20-19](https://user-images.githubusercontent.com/45864744/197799266-52a234e5-90ff-47b8-926e-e82adb73dab8.png)

  
Would you like to challenge copy-pasting the 'Object types' folder in a large project?
https://editor.construct.net/#open=demonoire

![Snipaste_2022-10-25_22-24-26](https://user-images.githubusercontent.com/45864744/197800319-29ee67e3-b147-4242-b9f8-6b0b18ba00e4.png)

## Attach a .c3p

Just open a project, e.g.
https://editor.construct.net/#open=scripting-shooting

## Steps to reproduce
1. Select the 'Layouts' folder
2. Ctrl + C / Ctrl + V 
3. Ctrl + V VVVVVVVVVV

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I don't see why this is a bug. This lets you do things like copy and paste a project's entire set of objects to another project.

Please note the observed vs. expected result fields are aimed at avoiding issues like this. Why would you expect this to not work? If there's no explanation of that then you aren't actually explaining any reason why this is a problem.
