### ISSUE TITLE
No other 3d objects are visible behind transparent 3d objects

### ISSUE THREAD

**Issue by Baguhan-p** [Scirra/Construct-3-bugs#6218]
No other 3d objects are visible behind transparent 3d objects.
I wanted to create a 3d fortress scene, but I ran into an unpleasant bug. I wanted to make a transparent window. I set the transparency of the 3d object to 50%. I noticed this bug: all 3d objects that are above the transparent 3d object at the Y coordinate are not visible behind it.
P.S. when I wrote the error report, I noticed that this problem is observed in c3 itself.
![b1](https://user-images.githubusercontent.com/45269472/198086251-4a15c1b6-3913-4915-8418-1c3dee7e65f6.png)
![b2](https://user-images.githubusercontent.com/45269472/198086258-6f558c87-aaa4-4e49-8198-110c114aa06b.png)

https://drive.google.com/file/d/1z056lJ4vZeDFYKOCsDa6hJdvWx50I_It/view?usp=sharing

The attached file already has the code to move around the scene. You just need to launch the project and walk around the transparent object.

1.Launch a project
2.Walk around a transparent object

Behind a transparent 3d object, objects standing above it are not visible

I wanted to make a regular transparent window

**Affected browsers/platforms:** 

Windows and Android, Chrome 

**First affected release:** 

r308.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
See the section on transparency in the tutorial [Using 3D in Construct](https://www.construct.net/en/tutorials/using-3d-construct-2746). Transparency in 3D is much more complicated than it is in 2D, and that documents what you may need to do.

In this case setting the layer draw order to "Camera distance" seems to do the trick.

**Comment by Baguhan-p** [comment]
> См. Раздел о прозрачности в руководстве по [использованию 3D в Construct](https://www.construct.net/en/tutorials/using-3d-construct-2746). Прозрачность в 3D намного сложнее, чем в 2D, и в этом руководстве рассказывается о том, что вам может понадобиться сделать.
> 
> В этом случае установка порядка прорисовки слоя на "Расстояние до камеры", по-видимому, делает свое дело.

Oh, thank you so much!
