### ISSUE TITLE
Template replace whole workflow improvements

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6219]
## Problem description
this is a follow up to #6212 as suggested by Diego.

Currently the workflow for "replace whole" or "modify existing" a templates hierarchy is a bit tedious as the user has to go multiple context-menu levels deep to apply them. This becomes especially painful when doing tweaks to a templates hierarchy and testing them, as it requiring the user to do these steps very often.

Imo a good solution would be a list or toggle inside the templates or replicas properties where the user can select if the hierarchy should be automatically updated or not. This would have the great benefit of not requiring an additional step any time the user does changes to the templates hierarchy.

**Comment by AshleyScirra** [comment]
In general non-bug features/suggestions/improvements should not be posted to the issue tracker - please post them to the suggestions platform instead: https://construct3-21h2.ideas.aha.io/

Perhaps file a suggestion there and then post a link to it here so Diego can see where it went.

**Comment by F3der1co** [comment]
https://construct3-21h2.ideas.aha.io/ideas/C321H2-I-478
moved to the suggestion board
