### ISSUE TITLE
Sort Z order changes object layers

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#6220]
## Problem description

When the Sort Z Order action is applied to a family of sprites on separate layers, those sprites unexpectedly change to different layers.

## Attach a .c3p

https://drive.google.com/file/d/1Rct1G45C_Qa8TB_sLPT3xr6uLZfon3lF/view?usp=sharing

## Steps to reproduce

1. Open the attached project. 
2. Note that each object is on its named layer (Layer0ObjectA is on Layer 0, etc.)
3. Run the project.

## Observed result

After the Sort Z order, the objects change layers.

![Screen Shot 2022-10-26 at 2 45 05 PM](https://user-images.githubusercontent.com/63005234/198111072-eb74e698-8dc6-4ede-8660-d22f7fc4ae88.png)

## Expected result

The objects would remain on their layers, and be sorted only against objects within those layers.

![Screen Shot 2022-10-26 at 2 45 47 PM](https://user-images.githubusercontent.com/63005234/198111099-a6c63adb-93b8-4a56-939e-9ea9467a8ace.png)

## More details

Note:

I may be misunderstanding how Sort by Z works, but if so, it seems very strange that the objects would change layers. I think that would mean I'd need a separate Sort by Z for each layer, and that objects couldn't move layers if they wanted to be Z Ordered.

From the manual: 

_This means if the instances are spread across a range of layers, they will be sorted in the same Z order locations, maintaining the same order relative to other instances on those layers._ 

It's a bit hard to understand this language, but it doesn't say anything about objects changing layers. It sounds like the objects stay on their layers, but are sorted relative to other instances on those layers.

**Affected browsers/platforms:** Latest Chrome stable on MacOS 12.6

**First affected release:** 316

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is by design. The algorithm essentially removes all instances from their layers and Z indices, sorts them, and puts them back in the holes left in the new order.

Your proposed expected result means that 'Sort Z order' failed, as it did not leave the objects in a Z order according to their order variable (based on the Y co-ordinate). So that approach is in fact broken and does not achieve the Z order you instructed it to.

**Comment by brushfe** [comment]
Thanks for clarifying this! I misunderstood the manual entry. I'll find another way to sort objects on multiple layers!
