### ISSUE TITLE
Copy Picked doesn't work with Families

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6221]
## Problem description

When applying a family action in a function that uses Copy Picked, it is applied to the whole family, instead of only the picked object.
My project has a family that has multiple members, each member has its own code, and they need to call a function that applies an action to the picked member.
So object A, B, and C each calls Function(). To avoid making an implementation for each object, Function() applies the action to Family. Instead of having the picked (caller) member affected, Function() affects all members.

## Attach a .c3p
[CopyPicked.zip](https://github.com/Scirra/Construct-3-bugs/files/9879535/CopyPicked.zip)

## Steps to reproduce

1. Click an object
2. Change the disabled code lines to compare behaviors

## Observed result
All family members are destroyed.

## Expected result
Only the clicked member is destroyed (i.e. the function should apply the action to the picked family member)

**Comment by AshleyScirra** [comment]
It's not a bug - it works the same as if you have "On tap gesture on Sprite: destroy Family1". The condition picks from Sprite, not Family1, and so Family1 remains with all instances picked. If you call a function with "copy picked", it preserves that state in the function too.

**Comment by Alaadel** [comment]
I understand, but Sprite is a Family1 too!
Is there any way I can use families in this case, without making a function for each object type? (this is is main purpose of families, correct?)

**Comment by AshleyScirra** [comment]
I'd suggest posting to the forum for general help with events and provide more details about what you're trying to do. As it is, I'd just say use "On tap gesture on Family1: destroy Family1" and then it works consistently, as the action and condition objects are the same.
