### ISSUE TITLE
error fetching worker on itch.io

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6223]
## Problem description
![workr](https://user-images.githubusercontent.com/89512047/198700586-0b7a5f4b-8278-4c15-9bc9-a8c9d4411e0e.png)

I have a bug in a large project that I can't seem to be able to fix, the project works in preview or when exported as nw.js but has some bugs if I run it on itch.io.
For me it's hard to debug if this error message is actually the problem but I think it's likely, **this error also happens with an empty project!**

## Steps to reproduce

1. upload an empty project on itch.io
2. run the project on itch (html played in browser) 
3. check the console

## Observed result
error 

## Expected result
no error

**Comment by AshleyScirra** [comment]
It looks like the itch.io server is responding to a request with "403 Forbidden". That would be an issue with the itch.io server, not Construct.

**Comment by F3der1co** [comment]
> It looks like the itch.io server is responding to a request with "403 Forbidden". That would be an issue with the itch.io server, not Construct.

I have reported this to itch.io, see here:
https://github.com/itchio/itch.io/issues/1383

As I have no idea how service workers operate I can only spew bs here. So could you please check the answers leafo gave on the report I linked? @AshleyScirra
