### ISSUE TITLE
Hierarchy breaks between layouts when using Persist object

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6225]
## Problem description

Hierarchy breaks in a spawned object after leaving the layout

## Attach a .c3p
[HierarchyPersist.zip](https://github.com/Scirra/Construct-3-bugs/files/9893122/HierarchyPersist.zip)

## Steps to reproduce

1. Move the object around using arrow keys
2. Click the button to go to Layout2
3. Move the (spawned) object around
4. Click the button to go back to Layout1
5. Move the object around
6. Click the button to go to Layout 2
7. Move the object

## Observed result
Hierarchy is broken. The child does not follow the parent

## Expected result
The child follows the parent

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.

Revision 18033.
