### ISSUE TITLE
[Bullet] Issue with Sliding Along Solids for Homing Bullets (set angle of motion every tick + Bounce off solids set to true) + Maybe a solution to solve several old issues with Bounce off Solids

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-3-bugs#6229]
## Problem description

When a Bullet has its bouce off solids boolean set to true and we set its angle of motion regularily (Homing Bullet in a game for example), several weird things happen when it collids with Solids/slide along solids. 

It moves way to fast when sliding along solids, sometimes get stucked, teleport to a far place.

This is an issue for all situations where Bullets angle of motion changes pretty often (homing projectile for example). This problem has always been there. 

_See **More Details** for a potential solution to solve this issue and several other old issues with Bullet boucing off solids_

## Attach a .c3p

[BugReport_HomingBulletSlideAlongSolids.zip](https://github.com/Scirra/Construct-3-bugs/files/9894141/BugReport_HomingBulletSlideAlongSolids.zip)

## Steps to reproduce

The Bullet_Homing (red) targets the cursor, it sets its angle of motion towards the Mouse cursor. It is supposed to move at the same speed as the Blue bullets.
1. Try to make the Red Homing Bullet slide along the black solids of the Layout by moving the curosr. (Border of the room + inner walls) as shown in gifs below

## Observed result VS Expected result

![BugReport_BulletSlideSolid_01_BorderRoom](https://user-images.githubusercontent.com/99751718/198842634-dbe9f410-045e-4f3a-877b-958da2883d0b.gif)

**1. Observed :** When sliding along the Borders of the Room (solids with angle equal to 0/90/180/270), the effective speed of the Red Bullet is much higher than the speed of the Blue bullets (while they all should have the exact same speed)
**1. Expected :** When sliding along Walls, the homing bullet should always stay close to its Bullet speed

![BugReport_BulletSlideSolid_02_SolidsInsideRoom](https://user-images.githubusercontent.com/99751718/198842646-2db23625-cbf5-4228-9984-ef2fa147c6bf.gif)

**2. Observed :** When sliding along the Solids inside the Room, the movement of the Red bullet is really janky. It sometimes teleports, gets stuck and/or moves way too fast.
**2. Expected :** It should slide smoothly along any solids, any kind of corners, in any angles.

## More details

Maybe it could be great to do something similar to the recent "Allow Sliding" boolean addition you did for the 8 Direction Behavior to fix this issue of Homing Bullet and all the other issues that were reported over the years regarding the Bouce of (non-homing) Bullets, all the ones related to the lack of accuraccy with the actual regular Bouce off solid feature. 
To kill 2 birds with 1 stone.

Like **add a "Perfect Bounce" boolean for Bullet** (could use a better and more explicit name of course), 
(instead of a new boolean, the Bouce Off Solid parameter could now be a 3-choice boolean "No"/"Vanilla Bounce"/"Perfect Bounce")It would set to false by default, or to "Vanilla Bounce" to not break backward compatibility.

The "Perfect Bouce" would allow :

1. Homing Bullet to slide along solids correctly (this issue)
2. The actual bouce of regular (non-homing) Bullets to be 100% accurate and predictible whatever is its collision polygon, like under the hood, it could achieve the same thing as a Line Of Sight + ReflectionAngle based on Angle of Motion.

It means that if I have 2 situations with the same bullet with a weird polygon shape (let's say a 5-branch star shape for example), with the same angle of motion bounce off the same solid, but in both situation the point of collision of the Bullet is different, the Bouce angle would still be exactly the same :

Under the hood, it could just pick the Angle of Motion of the Bullet right before the collision, calculate the Reflection Angle based on this angle of motion, as if the raycast was from the point of collision towards the previous Angle of Motion.

=> The existing behavior of bounce off solid would still be useful in case we want to have bouces based on the polygon shape of the Bullet.

=> But the new "Perfect Bounce" boolean option would allow to have a 100% or a least more accurate and previsible Bounce no matter what is the polygon shape of the Bullet (**the polygon would only be useful** to check if the collision happens, and so if the reflection angle should be calculated and applied, but it wouldn't have an impact on the actual reflection angle) - useful for regular Non-Homing Bullets + would allow Homing Bullet to slide along Solids without any issue.

**Comment by AshleyScirra** [comment]
The bullet behavior's 'Bounce off solids' feature is not designed to be used like this. It's intended for one-off collisions that make the bullet bounce away at a reflection angle, such as in the [Bouncing bullets example](https://editor.construct.net/#open=bouncing-bullets).

This usage is very different to that and is more like a "slide along solids" request for the Bullet behavior. Given that this amounts to a significantly different algorithm for a significantly different use case I think this ought to be filed as a feature suggestion instead - but to be honest I'm sceptical the bullet behavior is appropriate for this at all. Perhaps you should be using some other combination of behaviors, or a custom implementation using events.
