### ISSUE TITLE
particle spawner breaks if the parent is manipulated

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6231]
## Problem description
The particle spawner breaks if the parent object is manipulated (setting width, mirroring, flipping etc.)

## Attach a .c3p
[particleHierarchy.zip](https://github.com/Scirra/Construct-3-bugs/files/9895919/particleHierarchy.zip)

## Steps to reproduce

1. run the project
2. press the button

## Observed result

particles stop spawing

## Expected result

particles keep spawning

## More details
**The same happens when setting width or flipping the parent! (maybe even with more actions?)**

Maybe certain hierarchy checkboxes, in this case set height/width, should be ignored or greyed out if the object doesn't support them or if it breaks the object.
_(wink wink adding hierarchy support to tilemaps while you are at it would be appreciated ;) https://construct3-21h2.ideas.aha.io/ideas/C321H2-I-297)_

**Comment by AshleyScirra** [comment]
Fixed for next beta.
