### ISSUE TITLE
"3Dshape is overlapping sprite" - does not work properly

### ISSUE THREAD

**Issue by FromChris-com** [Scirra/Construct-3-bugs#6232]
## Problem description

3DShape does not detect "is overlapping" a sprite properly. It does detect "on collision". 

## Attach a .c3p
[3d_isOverlapping.zip](https://github.com/Scirra/Construct-3-bugs/files/9896316/3d_isOverlapping.zip)

## Steps to reproduce

1. Check a variable/action for a specific sprite when 3Dshape is overlapping sprite

## Observed result

Condition does not work, and all sprites are selected.

## Expected result

The overlapped sprite's variable to show in the text.

## More details
I noticed when swapping around the conditions it does work properly:
When Sprite is overlapping 3D Shape works, while 3D Shape is overlapping Sprite does not. 

**Affected browsers/platforms:** 

**First affected release:** Noticed in most recent beta, but when back to 274 and still doesn't work properly. 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release cycle (the fix will be in the first beta release after the next stable release).
