### ISSUE TITLE
Physics - High world gravity issue

### ISSUE THREAD

**Issue by Dav88eve** [Scirra/Construct-3-bugs#6239]
## Problem description

Physics jitter on higher world gravity (80).

https://filetransfer.io/data-package/p7tA10nN#link

## Steps to reproduce

1. Preview the project

## Observed result

Physics object vibrates, and collisions trigger repeatedly.

## Expected result

Expect to only get one collision trigger on impact, and sleeping physics object.

## More details
Seems to be happening only when framerate is 60fps or less.

**Affected browsers/platforms:** Tested in Chrome on Windows

**First affected release:** Don't work in any I have tested, either the newest beta or stable release.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r317 (stable)
Browser: Chrome 107.0.5304.87
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 89 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Please provide a project file as per the bug report guidelines. We can't debug a video!

**Comment by Dav88eve** [comment]
Sorry, wrong link. Here's the cap.

https://filetransfer.io/data-package/p7tA10nN#link

**Comment by Dav88eve** [comment]
> Please provide a project file as per the bug report guidelines. We can't debug a video!

So I

**Comment by Dav88eve** [comment]
Hi! Any progress?

**Comment by AshleyScirra** [comment]
I looked in to this previously but was not able to make any progress. Now the link to the file no longer appears to work, or wants me to log in. Our policy (as per the bug report guidelines) is not to use such services - please attach the file here on GitHub or use one of our recommended services.
