### ISSUE TITLE
[r44] Copying project with "save as" -> Unable to distinguish between copy and original 

### ISSUE THREAD

**Issue by gpibernats** [Scirra/Construct-3-bugs#624]
## Problem description

When you save a copy of a project using "Save as" you get different projects unable to distinguish through editor.

Video with example [here](https://www.dropbox.com/s/xye8szq3hcka90b/ConfusingProjectName_16jul.mov?dl=0).

(That is not a big deal, but as I am in love with Construct3 i report it:)

## Attach a .c3p

[A.c3p](https://www.dropbox.com/s/5do4le6w7vm5shq/A.c3p?dl=0)
[A_copy.c3p
](https://www.dropbox.com/s/noz38cikuj6qqo9/A_copy.c3p?dl=0)

Different projects unable to distinguish through editor.

## Steps to reproduce

1. Create and save project (projectA)
2. "Save as" with a new name the project (pojectA_copy)
3. Open both projects (projectA and projectA_copy)
4. Try to distinguish which is which

## Observed result

Both projects look the same, same name in Poject bar and Properties bar.

## Expected result

New name showed in some place.

## Affected browsers

* Chrome: yes
* Firefox: -
* Edge: -
* Safari: -

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

No crash dialog.

</details>

**Comment by shortercode** [comment]
Thanks for the suggestion. Based upon other applications the general fix here is to append the location the end of the label. So I'm working to add this. At the same time I consider this related to #297, which has been untouched for quite awhile so going to try and resolve that at the same time using jaydonteh's suggestion.

**Comment by shortercode** [comment]
@gpibernats Okay there's going to be a first pass version of this change in r45, let me know how you get on with it!
