### ISSUE TITLE
Quick manual fixes (pt.2)

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-3-bugs#6240]
## Problem description

Minor manual errors that need to be fixed (part 2).

## Errors

1. Solid behavior
[Initial state](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/solid#:~:text=changed%20by%20the-,Initial%20state,-property%20or%20the) should be renamed to _Enabled_

2. Project properties ([Link](https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/projects))
_Export file structure_ property is not documented

3. Particles scripting interface
[lifeOpacityRandom](https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/plugin-interfaces/particles#:~:text=pixels%20per%20second.-,lifeOpacityRandom,-Set%20or%20get) method looks different than others (style issue).

4. Audio plugin ([Link](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/audio))
_On fade ended_ condition is not documented
_PlaybackRate_ expression is not documented
[PlaybackTime](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/audio#:~:text=are%20in%20place.-,PlaybackTime,-(Tag)%0AGet) expression looks different than others (style issue).

**Comment by AshleyScirra** [comment]
Thanks, updated the manual for all these cases.
