### ISSUE TITLE
Tile With Brush - Family vs. Instance

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#6244]
[Family_Tile_With_Brush_Debug_0.zip](https://github.com/Scirra/Construct-3-bugs/files/9933706/Family_Tile_With_Brush_Debug_0.zip)

Issue: Using a family to set tile with brush results in an error

Step 1: Set tile with brush using family

Step 2: error

**Comment by OneRepCloser** [comment]
More of lacking a feature than a bug, the engine sees Family1 as having 0 brushes I presume.

**Comment by AshleyScirra** [comment]
I can't tell what is supposed to be wrong in the provided project, and no error seems to appear at any point.

Please always follow the bug report guidelines. We really do need all the requested information in order to be able to investigate your report. That is why we ask for it.

**Comment by OneRepCloser** [comment]
I see, for some reason when I selected new issue it just provided a blank comment section this time around.

So didn't have anything to go on in terms of guidelines. I'll try again.
