### ISSUE TITLE
wall hanging bug

### ISSUE THREAD

**Issue by kennethkao111** [Scirra/Construct-3-bugs#6245]
## wall bug

character hanging on the wall
## c3p file: https://drive.google.com/drive/folders/1ElzyYKpn_B2QmK1eveI2k9pwBUIWbJK5?usp=share_link
c3p file: https://drive.google.com/drive/folders/1ElzyYKpn_B2QmK1eveI2k9pwBUIWbJK5?usp=share_link

## Steps to reproduce

1.create wall (add solid)
2.create character , then stretch the character via mouse (then add platform)
3.play and jump toward the wall

## Observed result

the stretched character will cling on the wall
## Expected result

the stretched character would slide down 
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by kennethkao111** [comment]
nope nope,,,, i found out that the angle changes...... that is the only reason. but i promise i didn't change the angle of the object, so i guess that still a bug.

**Comment by AshleyScirra** [comment]
This is a mistake in your project. The blue object has an angle of 359.8° and the pink one is 0°. The slight tilt to the left causes extra collisions with the wall as it falls. Set the angle of both to 0° and they both work identically.
