### ISSUE TITLE
Tile With Brush - Family vs. Instance 

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#6246]
Using a family to set tile with brush results in an error

[Family_Tile_With_Brush_Debug_0.zip](https://github.com/Scirra/Construct-3-bugs/files/9941136/Family_Tile_With_Brush_Debug_0.zip)

## Steps to reproduce

1. Add Action
2. Family1
3. Set tile with Brush

## Observed result

Error report information
Type: unhandled rejection

## Expected result

Add action

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at R.i (https://editor.construct.net/r317/main.js:903:461) at d.qha (https://editor.construct.net/r317/projectResources.js:1725:266) at pNa (https://editor.construct.net/r317/projectResources.js:482:494) at new window.Dqc (https://editor.construct.net/r317/projectResources.js:2867:197) at ta.j (https://editor.construct.net/r317/main.js:980:44) at new d (https://editor.construct.net/r317/projectResources.js:2872:269) at ta.j (https://editor.construct.net/r317/main.js:980:44) at sF.g.J.vlc.P (https://editor.construct.net/r317/projectResources.js:2878:48) at iOa (https://editor.construct.net/r317/projectResources.js:510:57) at eOa (https://editor.construct.net/r317/projectResources.js:508:117)
Stack: TypeError: unexpected type at R.i (https://editor.construct.net/r317/main.js:903:461) at d.qha (https://editor.construct.net/r317/projectResources.js:1725:266) at pNa (https://editor.construct.net/r317/projectResources.js:482:494) at new window.Dqc (https://editor.construct.net/r317/projectResources.js:2867:197) at ta.j (https://editor.construct.net/r317/main.js:980:44) at new d (https://editor.construct.net/r317/projectResources.js:2872:269) at ta.j (https://editor.construct.net/r317/main.js:980:44) at sF.g.J.vlc.P (https://editor.construct.net/r317/projectResources.js:2878:48) at iOa (https://editor.construct.net/r317/projectResources.js:510:57) at eOa (https://editor.construct.net/r317/projectResources.js:508:117)
Construct version: r317
URL: https://editor.construct.net/
Date: Fri Nov 04 2022 11:28:48 GMT-0700 (Mountain Standard Time)
Uptime: 24.5 s

Platform information
Product: Construct 3 r317 (stable)
Browser: Chrome 106.0.5249.119
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by OneRepCloser** [comment]
More of lacking a feature than a bug, the engine sees Family1 as having 0 brushes I presume.

**Comment by DiegoScirra** [comment]
The problem is that the family itself doesn't know about the brushes, it's the object types that have that information and families were just overlooked completely when the feature was originally developed.

I think the best thing is for the dropdown to show only brush names that are shared by all the object types in the family, so no matter what you choose something useful will be picked.

Of course this will mean that you would need to be careful to name brushes across all object types in a consistent way. That should be ok as it is a common pattern across all of C3.

Asides from that, adding another pair of actions to use brushes with string names shouldn't be too much trouble.

Not sure if everything will be available for the next beta, but definitely for the one after that.

**Comment by DiegoScirra** [comment]
The next beta will support using auto tiling brushes with families.

**Comment by DiegoScirra** [comment]
The next beta will also include new actions to use brushes name as well as a condition to check for the existence of brush in an object type or family.
