### ISSUE TITLE
"Rats! WebGL hit a snag" while playing games in Iphone, Ipad

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#625]
## Problem description

*I export game in HTML5 and upload it on server. Game is Playing well in Chrome, Android & Desktop but when I play on IPhone, IPad & Safari First loading screen complete and then it showing this error "Rats! WebGL hit a snag". Please do help.
Details of error
iPhone/iPad 
Safari
Loading page appears, then error message "A problem occurred with this webpage so it was reloaded." then it blinks and reloads a half dozen times. Then there is a blank page with an error message "A problem repeatedly occurred on "URL"."
##ScreenShot 
![1](https://user-images.githubusercontent.com/17684135/28248145-32c1ba5a-6a5d-11e7-9285-43f1f2ce8767.PNG)
![2](https://user-images.githubusercontent.com/17684135/28248146-32c2de8a-6a5d-11e7-9368-03a11ddbeb45.PNG)
![3](https://user-images.githubusercontent.com/17684135/28248147-32c8faea-6a5d-11e7-96bb-d991ae3cad32.PNG)

## Attach a .c3p
*[C3p File](https://www.dropbox.com/s/25zhqtdioafvczq/SplishSplash_Error.c3p?dl=0)
[Zipped File](https://www.dropbox.com/s/gyy32nht04ymo31/Export%20in%20Construct%203.zip?dl=0)
[Uploaded on Server](http://12punch.com/clients/KB/TEST/test1_c3/index.html)*
## Steps to reproduce

1. Open Attached File
2. Export to HTML5
3. Test it on iPhone, iPad& Safari

## Observed result

*Rats! WebGL hit a snag*

## Expected result

*Play the game*

## Affected browsers

* Chrome: no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
That error means the browser crashed, and is not a problem with Construct. I checked your project and C3 estimates the first layout uses 1 GB of memory. So I assume the device is simply running out of memory due to using a large number of extremely large images. Try to design games with smaller images - see this blog for more information: https://www.scirra.com/blog/112/remember-not-to-waste-your-memory

**Comment by luckyrawatlucky** [comment]
Hi Ashley 
Okey I understand this is not a bug but I reduced image sizes 66% and i deleted many images for testing but it still doesn't work, and When I deleted all images then it doesn't give any error
I made below two kind of zip Files
[Removed Some Images](https://www.dropbox.com/s/rbn10nbqwppj7mz/SplishSplash_1280x720_remove_some_images.zip?dl=0)
[Removed all images](https://www.dropbox.com/s/2uaksnfopln61ks/SplishSplash_1280x720_without_Images.zip?dl=0)
If their is anything that i have to do then please suggest me

**Comment by AshleyScirra** [comment]
If you're testing at the same URL, note the offline cache will give you the previous copy you uploaded first, so I suspect you're actually running the same test twice. If you export to a new URL with images removed does that work better? I am sure this is a memory usage problem.

**Comment by luckyrawatlucky** [comment]
I am changing URL each time

**Comment by AshleyScirra** [comment]
Then please share the original .c3p projects, exported projects aren't much use in bug reports.

**Comment by luckyrawatlucky** [comment]
[Original C3p File](https://www.dropbox.com/s/25zhqtdioafvczq/SplishSplash_Error.c3p?dl=0)

**Comment by luckyrawatlucky** [comment]
did you check file?

**Comment by luckyrawatlucky** [comment]
Please give me some reply
How much I have to wait ? @AshleyScirra

**Comment by AshleyScirra** [comment]
Please be patient. As you can see from this tracker we deal with hundreds of reports.

**Comment by AshleyScirra** [comment]
I can't investigate this unless you provide the .c3p files for each case. It looks like you want me to compare the "removed some images" version with the "removed all images" version, but you've only provided the .c3p file for the verson with all the images, which certainly uses too much memory for many devices. Please provide the .c3p file for all versions if you want me to look in to this further.

I'm still pretty sure it's still running out of memory even after you removed some images, because the original project had such an extremely high amount of memory usage. I think this report will simply be a matter of verifying that.

**Comment by luckyrawatlucky** [comment]
I have tried files in very different different ways 
Even I give flat colors to all images still it didn't playing
Below game has not much images and not so large but it also working on Iphone
Please take a look into this
[Peek-a-bounce](https://www.dropbox.com/s/7qx39q6m0rgfqn3/Peek%20a%20bounce%202%20.c3p?dl=0)

**Comment by luckyrawatlucky** [comment]
I have Tried So many ways But none of those worked on iphone
Now you are only my hope
[Deleted All Images](https://www.dropbox.com/s/p1rr7ubxl2ukiig/Deleted%20All%20Images.c3p?dl=0)
[All Image Size Reduced](https://www.dropbox.com/s/fdv9503rpo1v06w/Image%20Size%20Reduced.c3p?dl=0)
[Deleted Some Images](https://www.dropbox.com/s/jm87oc835btbd5d/Deleted%20Some%20Images.c3p?dl=0)

**Comment by luckyrawatlucky** [comment]
@AshleyScirra Did you checked these files?

**Comment by luckyrawatlucky** [comment]
@AshleyScirra 
Its going to be a very long waiting 
I can wait for a long time but Client can't wait for it, They asking me regularly.
This is my first project I received as Job & I afraid that I will lost this If I didn't solve this issue.

**Comment by luckyrawatlucky** [comment]
Hi @AshleyScirra 
I have found the solution and I thought I should share this solution So you can help others
Memory Or Large images are not problem
Problem was Mouse Plugin
I removed Mouse plugin and insert touch control and now file is working very well

**Comment by AshleyScirra** [comment]
@luckyrawatlucky - that should not cause a crash. If it's the Mouse plugin, can you file a new bug with the minimum necessary to cause the problem? i.e. if that really is the problem, you should be able to just add the Mouse plugin to an empty project, reproduce the problem, and file a bug with that. Otherwise if it does not reproduce, that is not really the problem.

**Comment by luckyrawatlucky** [comment]
okey I will test that and if problem I will file a bug here

**Comment by luckyrawatlucky** [comment]
@AshleyScirra I tried this with Blank project and found that mouse is not problem
You are saying i have large sized images but i also tried with images reduced size and it never works

[Deleted All Images](https://www.dropbox.com/s/p1rr7ubxl2ukiig/Deleted%20All%20Images.c3p?dl=0)
[All Image Size Reduced](https://www.dropbox.com/s/fdv9503rpo1v06w/Image%20Size%20Reduced.c3p?dl=0)
[Deleted Some Images](https://www.dropbox.com/s/jm87oc835btbd5d/Deleted%20Some%20Images.c3p?dl=0)

Please check these

**Comment by luckyrawatlucky** [comment]
@AshleyScirra I tried this with Blank project and found that mouse is not problem
You are saying i have used large sized images but i also tried with images reduced size and it never works

Deleted All Images
All Image Size Reduced
Deleted Some Images

Please check these
