### ISSUE TITLE
Timeline On Finished bugs with multiple timelines playing

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#6250]
## Problem description

There are several issues with On Finished trigger when multiple timelines are playing, which I think are related.

## Attach a .c3p

[TimelinesBugs.zip](https://github.com/Scirra/Construct-3-bugs/files/9948279/TimelinesBugs.zip)

## Steps to reproduce

Bug 1
1. Disable event 4 in the event sheet. 
2. Launch preview and press the button.
3. Notice how the first finished timeline has no tag or name.
4. Also, not sure if it's a bug or not, but "On t1 finished" event is triggered before "On any finished", although it comes after it in the event sheet.

![image](https://user-images.githubusercontent.com/36763350/200229418-59f696bb-142a-465a-acab-de4e50478ce8.png)

Bug 2
1. Enable event 4 and run the project
2. Now when "t1" is finished, an error is thrown in the console log, and "On any finished" event is not triggered for it.
If you preview in Debug Mode, the project no longer works after that error.

![image](https://user-images.githubusercontent.com/36763350/200230102-fd3467f3-9e33-4901-b661-6fcb4a4556dd.png)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r317 (stable)
Browser: Chrome 107.0.5304.88
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 559 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.

About the order of triggers, all the variations of the **"on finished"** triggers are different, that means that their order in the event sheet has no influence on when they will be executed relative to each other. The position on the event sheet only matters when there are multiple triggers which are exactly the same.

https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/events/how-events-work#internalH1Link4

For example if there were two **"on any finished"** triggers, then the order in which they appear would matter.

Of course, if you were to do some diligent testing, you would find out there is an order in which the **"on finished"** triggers are executed, but that is an implementation detail and shouldn't be relied upon.

Revision 18036.
