### ISSUE TITLE
Faild to open game files

### ISSUE THREAD

**Issue by Itslossless** [Scirra/Construct-3-bugs#6251]
## Problem description

 every game that I saved on version r308 cant be opened on the last version of construct r317

## Steps to reproduce

1. try to open the game on Construct 3 r317
2. if you open the file on version r308 it will work
3.

## Observed result

 "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

## More details
 At dev tools I see the next massage : [Project] Exception opening:  TypeError: unexpected type
    at R.i (main.js:903:461)
    at d.VL (projectResources.js:1677:345)
    at d.$Ib (projectResources.js:1681:9)
    at d.mfb (projectResources.js:1681:57)
    at d.xba (projectResources.js:1383:75)
    at d.Ha (projectResources.js:1386:226)
    at window.$Q.cSb (projectResources.js:1354:344)
    at window.IDa.Ikb (projectResources.js:1363:43)
    at window.IDa.Ha (projectResources.js:1364:308)
    at d.Ha (projectResources.js:1340:478)

 Chrome, Construct doesn't work on firefox

**Affected browsers/platforms:** 

 all the version after r308

**First affected release:**  worked on r308 broken any version after

## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Product: Construct 3 r317 (stable)
Browser: Chrome 107.0.5304.88
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 181 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) Iris(R) Plus Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Shreyas-Mith** [comment]
Im facing the same problem. Can someone suggest a solution.

Platform information

Product: Construct 3 r317 (stable)
Browser: Chrome 107.0.5304.87
Browser engine: Chromium
Context: browser
Operating system: Linux 5.15.0
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

![image](https://user-images.githubusercontent.com/82201047/200287396-0573f0b4-3ab7-460a-9179-45fc88e35c8a.png)
These are some of the errors in developer tools!. Please help

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help unless you provide your project file. Please attach it to the issue report as per the bug report guidelines or email it to support@construct.net if you'd prefer not to share it.

**Comment by Itslossless** [comment]
I attach the project file

**Comment by Itslossless** [comment]
I attached the project file please reopen the case

**Comment by Shreyas-Mith** [comment]
[test_project.zip](https://github.com/Scirra/Construct-3-bugs/files/9951876/test_project.zip)
Please find attached the folder. Please reopen the issue

**Comment by AshleyScirra** [comment]
@Shreyas-Mith - that project opens OK for me here.

Both of you - I'd advise opening a new issue with your project file attached and following all the bug report guidelines, otherwise it quickly becomes so confusing it's difficult to help.

**Comment by Shreyas-Mith** [comment]
@AshleyScirra ok will do. But as i stated before, it open happens on linux systems.
