### ISSUE TITLE
Layout margins disappear below 100x100

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#6252]
## Problem description

When the margins of a layout are 99x99 or lower, they aren't visible.

## Attach a .c3p

(Any project should work)

## Steps to reproduce

1. Start a new project.
2. Select Layout 1.
3. Change the margins to 100x100.
4. Note you should see them on-screen (zoom out if required)
5. Change the margins to 99x99.

## Observed result

The margins disappear.

## Expected result

The margins remain on screen.

## More details

**Affected browsers/platforms:** Latest Chrome stable on MacOS 12.6

**First affected release:** Noticed in 317.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It looks like there's been code to only show them above a distance of 100 (the same size as the lines) since the very beginning of Construct.

Is it any particular problem? If it's just some quirk you noticed, I don't think it justifies changing. Perhaps there was some reason for it I forgot about.

**Comment by brushfe** [comment]
Strange! Maybe I notice it more in the dark themes then.

I use small margins (50x50) as a work around to a problem with the keyboard zoom. When zooming in/out on a layout with the keyboard shortcuts, it zooms toward the mouse cursor.

In most programs (that I use anyway), keyboard zooms don't move the center-point of the layout view, they just increase/decrease the layout size. Construct's zoom in/out always acts like a mouse scrollwheel zoom, following the cursor (I'm working on a laptop with a trackpad, so i'm always fighting this).

However, if the margins are really small, it limits how far away from the layout construct will zoom toward the cursor. So until keyboard zoom can change, smaller margins are the workaround, and visibility below 100 would be helpful!

**Comment by AshleyScirra** [comment]
Hmm, I thought that zooming via keyboard toward the mouse would be useful for laptops with trackpads. It means you can move the cursor to choose where to zoom in to. Still, we're at the beginning of a beta cycle so it's the least risky time to make changes. It turns out those margin markers have a 10px padding on them so they can't be displayed at margin sizes less than 10 (otherwise they move inside the layout area). So I changed the next release to use a minimum size of 10 rather than 100. Hopefully that does the trick.

**Comment by brushfe** [comment]
Thanks for increasing the visibility!

And I appreciate your intent re: the cursor, but it means you _always_ have to move cursor before you zoom. Or, which is more often, you use the keyboard shortcut, it zooms somewhere you didn't expect, and you have to swipe a lot to get back to where you want it. 

With the added trouble of this keyboard zoom style being unique to construct (in my software workflow), it's a battle (and if you forget to click on the layout, the whole app zooms and you have to restart).

If there's room for future consideration, this would definitely be a help. I'd make a suggestion, but I'm not sure it's worthy of switching votes to. Thanks again!
