### ISSUE TITLE
Out bounce tween not match the final result.

### ISSUE THREAD

**Issue by amyhapple** [Scirra/Construct-3-bugs#6254]
## Problem description

On ended tween with ease Out Bounce/In Out Bounce, the final value is not matching **exactly** as predicted. This happens in C3 version r317, but not in previous r308.

## Attach a .c3p

https://github.com/Scirra/Construct-3-bugs/files/9964068/outbounce_bug.zip

## Steps to reproduce

1. Make an object tween its angle + 90 with ease Out Bounce.
2. Look in the debug mode its angle after the tween stopped.

## Observed result
Final angle: 90.00000001 (the results varies)

## Expected result
Final angle: 90

## More details

**Affected browsers/platforms:** 

**First affected release:** 
worked in r308 but broke in r317 (maybe r317.2)
## System details

<details><summary>View details</summary>

PASTE HERE

</details>
[outbounce_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/9964068/outbounce_bug.zip)

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta. While it is a regression, the error is negligible and shouldn't matter for any practical purpose. 

Revision 18043.

**Comment by DiegoScirra** [comment]
Will be fixed for the next beta.
