### ISSUE TITLE
Text vertical alignment working different in each browser.

### ISSUE THREAD

**Issue by amyhapple** [Scirra/Construct-3-bugs#6255]
## Problem description
Text **vertical alignment** working different in each browser.

## Attach a .c3p
[textalignbug.zip](https://github.com/Scirra/Construct-3-bugs/files/9964518/textalignbug.zip)

## Steps to reproduce

1. Set text objects with different settings.
2. Open the project in different browsers (can be reproduced in preview mode).

## Observed result

With BBCode activated, **center** and **bottom** alignments not matches in Chrome, Firefox and iOS Safari.
Removing the BBCode option, both stay same, but not in iOS Safari (even the Top alignment is different in this browser)

LEFT: **CHROME** | RIGHT: **FIREFOX** (I don't have an iPhone to send screenshots, but have tested in a previous project.)
![firefox_LBkmKi70d7](https://user-images.githubusercontent.com/26300961/200660282-27469e14-207a-459a-a574-2e8b359f9dbc.png)
With larger fonts the difference are **HUGE**.

## Expected result

All main browsers working the same.

## More details

The only settings that I could reproduce in the three browsers equally, is enabling the BBCode and setting the vertical aligment to Top.

Another case 1:
https://www.construct.net/en/forum/construct-3/general-discussion-7/text-offset-mobile-browser-161303

Another case 2:
https://www.construct.net/en/forum/construct-3/general-discussion-7/text-center-vertical-alignment-158779

**Affected browsers/platforms:** 
Tested in: Windows and Android Chrome / Windows Firefox / iPhone Safari

**First affected release:** 
This bug is too old. There were some changes in past versions, but the bug was never actually fixed. I'm using r317 right now (last stable one)
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid this is currently due to incompatibilities between browsers, the same as #6137. Browser makers will need to first agree on the correct behavior and then implement it everywhere consistency (see [this comment](https://github.com/Scirra/Construct-3-bugs/issues/6137#issuecomment-1258191925)).

**Comment by amyhapple** [comment]
@AshleyScirra I think the solution is to do it manually then. Is there any way to detect the browser used for this? The closest I've come is using Browser.UserAgent, but I would still need an API to translate the info.
And it's possible to make an action Enable/Disable BBCode to text objects?
