### ISSUE TITLE
double-clicking project file search in the find windows crashes c3

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6256]
## Problem description
double-clicking a project file search in the find windows crashes c3

## Attach a .c3p
[searchBroken.zip](https://github.com/Scirra/Construct-3-bugs/files/9965896/searchBroken.zip)

## Steps to reproduce

1. press ctr-f
2. make sure "look in:" is set to project files
3. type apple into the search field
4. double click the result

## Observed result

crash

## Expected result

opens the dictionary at the correct cell

## More details
only the array and dictionary causes the crash, the other file types seem to work.

I just wanted to say that this new search feature is awesome, it solves an issue perfectly that I just made a suggestion for a week ago. [suggestion](https://construct3-21h2.ideas.aha.io/ideas/C321H2-I-480)
Thank you!
## System details
Error report information
Type: unhandled rejection
Reason: Error: e.NL is not a function @ TypeError: e.NL is not a function at window.Zcb.aka (https://editor.construct.net/r318/components/bars/findResultsBar/findResultsBar.js:16:99)
Stack: TypeError: e.NL is not a function at window.Zcb.aka (https://editor.construct.net/r318/components/bars/findResultsBar/findResultsBar.js:16:99)
Construct version: r318
URL: https://editor.construct.net/r318/
Date: Wed Nov 09 2022 00:09:20 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 51.4 s

Platform information
Product: Construct 3 r318 (beta)
Browser: Chrome 107.0.5304.88
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment]
I've fixed the next beta so it opens the data editor for search results that use the data editors, rather than crashing. However the search result still shows a line of the JSON source, and the data editor does not highlight the result yet. That's on my todo list for further improvements, but closing this issue as the crash is fixed.
