### ISSUE TITLE
template hierarchy replace whole crash

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6259]
## Problem description
using the context menu option "template hierarchy replace whole" crashes c3

## Attach a .c3p

[creatingHierarchyFromTemplateCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/9969924/creatingHierarchyFromTemplateCrash.zip)

## Steps to reproduce

1.right-click the left hierarchy
2.select the context menu option template>apply template to all replicas>hierarchy>replace whole

## Observed result

crash

## Expected result

hierarchy is created

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r318/main.js, line 900, col 141
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at O.i (https://editor.construct.net/r318/main.js:900:147) at e8a (https://editor.construct.net/r318/components/editors/layoutView/layoutView.js:43:147) at L7a (https://editor.construct.net/r318/components/editors/layoutView/layoutView.js:28:358) at https://editor.construct.net/r318/components/editors/layoutView/layoutView.js:13:396 at https://editor.construct.net/r318/main.js:1738:100
Construct version: r318
URL: https://editor.construct.net/r318/
Date: Wed Nov 09 2022 11:25:55 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 104.8 s

Platform information
Product: Construct 3 r318 (beta)
Browser: Chrome 107.0.5304.88
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
