### ISSUE TITLE
Pixelate Effect Broken

### ISSUE THREAD

**Issue by morrisfeldman** [Scirra/Construct-3-bugs#626]
## Problem description

So in my pixel artsy game, I have linear sampling to keep the lighting looking smooth, so I use the pixelate effect on almost everything. I soon noticed after buying c3 that the pixelate effect was just broken. 

Also as an unrelated note, I was upset to see that there was no NWJS preview mode/support unlike in construct 2, considering that the game I'm making is meant to be desktop-only and I can't hop back into c2 at this point.

## Attach a .c3p

The file is in the zip file.
[bugexample.zip](https://github.com/Scirra/Construct-3-bugs/files/1157293/bugexample.zip)

## Steps to reproduce

1.Create sprite
2.Add pixelate effect
3.Preview or export game

## Observed result

It's like it set the pixel size back to the default 16-pixel size, it's a big mess.

## Expected result

See sharp pixels at the normal 1-pixel size.

## Affected browsers

 Chrome: Yes
 Firefox: Yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r45

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 333 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: Google Inc.
Renderer: ANGLE (ATI Mobility Radeon HD 4200 Series Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by morrisfeldman** [comment]
I have a pretty big project that has the same effect even more broken than on the basic new projects that easily reproduce the bug. I didn't post it because it's way too big, but if you're willing to do the digging for the source of the increased breaking of the effect, just check out my W.I.P sandbox game.
[Huber.zip](https://github.com/Scirra/Construct-3-bugs/files/1161274/Huber.zip)

**Comment by AshleyScirra** [comment]
C3 has a re-worked effect rendering engine, and this has uncovered some awkward inconsistencies between C2, C3, and C3's editor and runtime. The effects system needs a review anyway (#402), so I'll probably look at this at the same time as that is done.

Note if you just want sharp pixellated rendering, just set the sampling project property to "point". There's no need to add pixellate shaders to everything.

**Comment by AshleyScirra** [comment]
As of r47 (to be released soon) the runtime now matches the editor, so it looks like it's working.
