### ISSUE TITLE
Animations Editor rectangle select broken

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6260]
## Problem description
changes with the rectangle select tool in sprite editor seem to be overwritten/not applied
## Attach a .c3p
easy to do with a new project

## Steps to reproduce
![ezgif com-gif-maker (36)](https://user-images.githubusercontent.com/89512047/200960184-8d3a1353-ea59-483e-bf21-3c3ecaf31e0d.gif)

1. create a sprite
2. open the animation editor
3. fill the sprite with a color
4. use the rectangle seletion tool
5. press delete
## Observed result
the animation editor shows the rectangle selected area as being erased, but the frame itself still doesn't have the deletion. (you can see it in the bottom animation bar or when closing the animation editor the change is not applied)

## Expected result

deleting with the rectangle select tool deletes a part of the image and that is saved to the frame

## More details
it's a bit confusing to describe, I hope the gif makes it clear

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta. Was a regression introduced in r318.

Revision 18037.
