### ISSUE TITLE
When multi selected objects in the Editor Layout, missing the same properties.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6263]
## Problem description

I plan to select multiple objects and change their 'Initially visible' properties. Yes, each of them has this attribute, but after multiple choices, can not see it.

Probably because one of them is a 9-patch object and the others are Tiled Background objects. But I think since they both have this, they should be able to work.

## Attach a .c3p

[issue-MultiSelect-properties-visible.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9977285/issue-MultiSelect-properties-visible.c3p.zip)

## Steps to reproduce

Select them all and look at the property bar.

## Observed result

![Snipaste_2022-11-10_12-21-18](https://user-images.githubusercontent.com/45864744/201000042-8a2301e9-b2fe-4bda-90a6-ff0eb2861c96.png)

## Expected result

If they both have the 'Initially visible' property Or something like that, they can also be modified together.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r318 (beta)
Browser: Chrome 107.0.5304.88
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 155 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Multi-selecting instances reduces the property list to only those properties in common between them all. For example Tiled Background has a "wrap horizontal" property and 9-patch does not, so if you select both a Tiled Background and a 9-patch it cannot show the "wrap horizontal" property as 9-patch does not have it and so changing it cannot apply anything to 9-patch.

Currently Construct considers plugin-specific properties as unique to the plugin, so the fact that two plugins both have a property that displays the same does not mean Construct considers them the same property, and so they will still be filtered according to this rule.

Perhaps that could change but it may prove to be complicated and it wouldn't surprise me if it had its own series of difficult edge cases, so I think changing this is best tracked as a feature request.

**Comment by XHXIAIEIN** [comment]
My vote has been used up :(

I think 'Initially visible'' can be promoted to the scope of public properties because it is useful for all objects.

**Comment by XHXIAIEIN** [comment]
Digression:
Just like all behaviors or plugins, they should have the public properties of "Enabled" OR "Set Enabled" Action by default.

https://construct3-21h2.ideas.aha.io/ideas/C321H2-I-403
