### ISSUE TITLE
Layers bar: Visible icons are not scaled correctly

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6265]
## Problem description

Look at the picture

![1](https://user-images.githubusercontent.com/45864744/201096515-c157e1d8-d643-4677-92b5-55f5a929b355.gif)

## Attach a .c3p

[issue-layers-visibleicon.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9980823/issue-layers-visibleicon.c3p.zip)

## Steps to reproduce
1.Just drag the Layers bar to make the window smaller.
2.
3.

## Expected result

The icon is not affected when scaling

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
