### ISSUE TITLE
C3 - Warp Effect panel Text

### ISSUE THREAD

**Issue by MrGrayCSC** [Scirra/Construct-3-bugs#627]
Problem Description
Construct 3 - Hardly a major issue but are the text headings in the Warp Effect panel correct? I think the 4th one down should be "Y amplitude" - not frequency

![new project - construct 3](https://user-images.githubusercontent.com/29109667/28341908-d3b20d8a-6c69-11e7-9e15-744517dcddc1.png)

Attach a Capx
Not Needed

Affected Browsers
Chrome: (YES)

Operating System and Service Pack
Windows 10 pro (1703)

Construct 3 beta online r45

**Comment by AshleyScirra** [comment]
Oops, you're right, there's a mistake in the language file. I've fixed it for r46. It's a tiny change though so it won't be in the changelog.
