### ISSUE TITLE
Mesh point z-elevation - randomly doesn't work 

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#6271]
## Problem description

I'm trying to use mesh distortion to flip book pages. Noticed that z-elevation is sometimes ignored for mesh points.

**EDIT:** Seems like "Rendering mode: Auto" setting doesn't recognize when z-elevation is used in events. 
Making a mesh manually in the layout editor makes it temporarily switch to "3D", but if you reload the project, it defaults to "2D" again.

## Attach a .c3p

[MeshZBug.zip](https://github.com/Scirra/Construct-3-bugs/files/9996500/MeshZBug.zip)

## Steps to reproduce

1. Run the project.
Notice how despite the fact that z-elevation of point (0,0) is increased with every tick, it stays behind the rest of the sprite.

![image](https://user-images.githubusercontent.com/36763350/201505241-85a5ba34-a8f4-43b4-8fe3-6c91292a464a.png)

2. In the layout editor make a copy (second instance) of the sprite, create a 2x2 mesh for it, move one of its points, change its z-elevation.
![image](https://user-images.githubusercontent.com/36763350/201505402-d935443c-e404-416a-a8a2-3864dc1be98a.png)

3. Delete that second instance in the editor and restart the preview. This time point z-elevation works correctly.

![image](https://user-images.githubusercontent.com/36763350/201505578-d2d2d93f-832b-48c2-b45c-86275d763b73.png)

4. Even if you save the project now, next time you reload the editor it won't work again. 

## More details

**Affected browsers/platforms:** Chrome/Firefox

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Chrome 107.0.5304.107
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 210 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Rendering mode "auto" by design only looks at things in the editor. If you only use 3D features dynamically, such as in this example, then you should change the rendering mode to "3D". This is [mentioned in the manual](https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/projects#internalH1Link5:~:text=Memory%20usage.-,Rendering%20mode,-Whether%20to%20render).

If I clone the object and add a mesh with a mesh point that has a raised Z elevation, then the project correctly changes in to 3D mode. This also appears to work fine for me after saving and reopening the project, so I don't see any issue there.
