### ISSUE TITLE
Problems with UI in the image editor

### ISSUE THREAD

**Issue by 1mrpaul1** [Scirra/Construct-3-bugs#6276]
after each app restart the probs are different, sometimes there is just no eraser, sometimes all buttons are cutted and no image points are displayed on the image.
started after the last update 319.2 (may be 319 earlier, didn't install it) 

Windows 11, intel i5 11 series, nvidia GPU rtx 3050, chrome 107 (last)

![Screenshot 2022-11-17 160410](https://user-images.githubusercontent.com/64515864/202430351-8a8d1d60-2bbe-49db-81fc-46345967c706.png)
](url)

**Comment by AshleyScirra** [comment]
Please note it may not be possible to help as we usually need all the requested information in the bug template to be able to help.

Assigning to @DiegoScirra in case he can figure anything out.
