### ISSUE TITLE
Checkbox click area is off 

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-3-bugs#6277]
## Problem description

Every Checkbox in the properties window can be clicked on in the empty space next to it, which leads to accidentally clicking on them without even noticing it.

![checkbox gif ](https://media.discordapp.net/attachments/983080966505529354/1037588318327681065/chrome_2022-11-03_05-44-59.gif)

## Attach a .c3p

This is an editor issue and is reproduceable in every project.

## Steps to reproduce

1. Open C3 and create a new project
2. click on empty space next to any checkbox in the properties window

## Observed result

The clickable area for any checkbox is like this 
![Discord_2022-11-17_21-30-31](https://user-images.githubusercontent.com/18266300/202553881-559ce8ef-c249-4fed-976c-1af5b474a48b.png)

## Expected result

The clickable area to be like this 
![Discord_2022-11-17_21-29-59](https://user-images.githubusercontent.com/18266300/202554062-cea85ece-5a99-41c7-98be-e537667f81d6.png)

## More details

**Affected browsers/platforms:** 

I installed C3 as a PWA via chrome

**First affected release:** 
I'm on release r317.2 but noticed this in previous releases, idk when it started or if it was always an issue.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Please leave everything as it is! This speeds up the development process, as I find it easier to hit at high speed.

**Comment by TackerTacker** [comment]
Then they should look visually longer. 
But it is a bug as it is right now.

**Comment by TackerTacker** [comment]
That makes sense, but there should be a visual indicator where the clickable area starts and ends.

**Comment by AshleyScirra** [comment]
Perhaps, but I don't think there's any standard UI metaphor for denoting a larger click area, and it might look a bit ugly given the click area is not the full box in order to keep away from the scrollbar.
