### ISSUE TITLE
"Go to layout (by name)" action apparently being ignored sometimes

### ISSUE THREAD

**Issue by CR1MS4NE** [Scirra/Construct-3-bugs#6278]
## Problem description

So I have a rather complicated room layout system that works by using an array to determine which layout to go to when exiting a room. It was working perfectly not long ago, so once I was satisfied with it, I saved it, tested it, and it worked the way I wanted it to.

Then I moved on to work on a dialogue system for stationary objects that the player could inspect. During this time, I made no changes to the room navigation code whatsoever.

When I was done with that, I went and tested the game again, but now for some reason I couldn't leave the starting room. Every time I tried, it would teleport me back in. I could see the next layout flash on screen for a tick, so the layout loaded and the player sprite was in it, but it immediately went back to the last layout.

It didn't actually restart the previous layout; I could tell because it kept putting me at a very specific Y level which was not the starting point (and which was not being stated anywhere else in the code). It was as if the game was simply skipping back half a second.

I used some keybinds to force the game to put me in a specific layout, and I was able to get that to work, but then I discovered that also happened with a few other rooms. Each time it would put me at a specific, consistent location, but it was never a location that I had programmed the game to put me at. It always happened in some rooms, and never happened in others. I had not changed any part of this programming since I had finished it earlier, when it worked properly.

I spent at least an hour adjusting numbers and trying to find out what was causing this, and I did at least get the bug to act differently, but I couldn't make it stop. I even tried setting a breakpoint at the exact moment the layout would change and using the debugger to play it frame by frame from there, but then the bug didn't happen for some reason.

Unexplainably, the bug does not happen when you walk through the exit at an angle.

I can't make sense of what's going on. I've reset everything to exactly the way it was before the bug started happening and it's still happening. It is of course possible that I've simply missed something important, but if that's the case then I'm very confused as to why it was working perfectly fine, but messed up arbitrarily even though I hadn't changed anything.

## Attach a .c3p

[game bug.zip](https://github.com/Scirra/Construct-3-bugs/files/10035324/game.bug.zip)

## Steps to reproduce

1. Open the test client.
2. Use the arrow keys to move the player (don't question why it's an amongus) right and downward through the exit of the room.
3. Observe that you are teleported back into the room, but not where you started.

## Observed result

You see 1 frame of the next layout but are immediately teleport back into the last layout, about 2-3 tiles above the exit.

## Expected result

You would switch to the next layout and stay there, and you would be put 1 tile below the exit at the top of the room.

## More details

**Affected browsers/platforms:** Chrome, Microsoft Edge/Windows
**Version: r317.2**

## System details

<details><summary>View details</summary>

Product: Construct 3 r317.2 (stable)
Browser: Chrome 107.0.5304.107
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

</details>

**Comment by CR1MS4NE** [comment]
Update: sometimes it doesn't teleport you back to your previous room but instead teleports you to a completely random layout.

**Comment by WilsonPercival** [comment]
Just turn off this event.

![aaa](https://user-images.githubusercontent.com/91274932/202577712-d0807acd-2182-4b6d-ad5d-cfe337b4adf4.png)

**Comment by CR1MS4NE** [comment]
> Just turn off this event.
> 
> ![aaa](https://user-images.githubusercontent.com/91274932/202577712-d0807acd-2182-4b6d-ad5d-cfe337b4adf4.png)

That's the event that makes it possible to walk upwards into a room. It solves the problem but creates another one.

**Comment by WilsonPercival** [comment]
> > Just turn off this event.
> > ![aaa](https://user-images.githubusercontent.com/91274932/202577712-d0807acd-2182-4b6d-ad5d-cfe337b4adf4.png)
> 
> That's the event that makes it possible to walk upwards into a room. It solves the problem but creates another one.

What? Let's solve them all, I have a lot of time.

**Comment by CR1MS4NE** [comment]
I can't tell whether you're being sarcastic or not so I'll just address them separately:

If you are being sarcastic: solving an issue by introducing another issue is not actually solving it.

If you are not: allow me to explain what that event is meant to do. There is a specific exit room which needs to behave differently from the other rooms when the player leaves it. That's what the else is for--it detects part of the name of the room to determine whether it's an "exit" or not, and if it is, then leaving it leads to a new area. If it does not find the word exit, it does whatever it normally does.

**Comment by WilsonPercival** [comment]
> I can't tell whether you're being sarcastic or not so I'll just address them separately:
> 
> If you are being sarcastic: solving an issue by introducing another issue is not actually solving it.
> 
> If you are not: allow me to explain what that event is meant to do. There is a specific exit room which needs to behave differently from the other rooms when the player leaves it. That's what the else is for--it detects part of the name of the room to determine whether it's an "exit" or not, and if it is, then leaving it leads to a new area. If it does not find the word exit, it does whatever it normally does.

It seems to me, or did you just admit that the error is in the logic of your events, and not a Construct problem? In this case, the developers will not be able to help you unless they want to dive into your project.

You wrote: `"Go to layout (by name)" action apparently being ignored sometimes` - everything seems to work well for me.

I'm not being sarcastic, I really have a lot of time. If you want to discuss your problem - write your discorde.

**Comment by CR1MS4NE** [comment]
My discord is SirPogsalot#0001

**Comment by avishaymizrav** [comment]
@CR1MS4NE 
It seems that when you move you player then switch layout, the grid movement snaps the players to a cell outside the layout, then your trigger once happens again and shoots you back to the last layout.

If you save the direction you were coming from and set the position on the start of the layout instead, it will work.

I'm guessing it's some sort of racing conditions with tile movement and global objects.

[gamebugsfix.zip](https://github.com/Scirra/Construct-3-bugs/files/10036684/gamebugsfix.zip)

**Comment by CR1MS4NE** [comment]
Construct is saying it's not a valid Construct 3 project.

For what it's worth though, I think you're right. Putting the movement at the beginning did seem to help, but there are still some issues. They seem to involve the room coordinates receiving the wrong numbers.

**Comment by avishaymizrav** [comment]
@CR1MS4NE 

Runs fine for me. I'm on the beta and I they did some changes to the zip format C3 uses, so if you're trying on the stable that's probably the reason.

As for the second issue, that's most likely an issue with your events, make sure you're reading the array properly.

**Comment by CR1MS4NE** [comment]
Opened it in the beta and yes, it appears to work perfectly. If you've got time, would you mind messaging me on Discord (SirPogsalot#0001) and explaining what exactly you did? I noticed you added a **dir** variable to the player and I'm curious how you made use of that.

**Comment by avishaymizrav** [comment]
@CR1MS4NE It's pretty straight forward, when you change rooms I set the dir value based on the direction you exit from, 0 going down, 1 going up, 2 going left, 3 going right.

Then on start of layout I check the dir value and set the position based on that.

**Comment by CR1MS4NE** [comment]
Huh. Fascinating.

Thanks so much, I'd been stuck on this hours.

**Comment by avishaymizrav** [comment]
Sure, no problem.

Keep this open though, I still believe there's a bug here, I don't see why the tile movement should snaps you out of the grid. It might be a regression from some other bug fix.

**Comment by CR1MS4NE** [comment]
Tile movement is disabled. The player is using 8 direction movement.

My main confusion was why the issue seemed to happen on its own and why it only happened in certain rooms.

**Comment by avishaymizrav** [comment]
I see. Well, something is still pushing you outside the layout when you're switching layouts, not sure what's causing it though.

**Comment by avishaymizrav** [comment]
It is something with the 8 direction movement, if you disable it when you're outside the layout and enable it again on start of layout, it will work without saving the direction.

I thought it might be due to the new Allow Sliding property, but it happens when it's off too.

**Comment by CR1MS4NE** [comment]
Interesting, I will give that a try.

**Comment by avishaymizrav** [comment]
Oh, silly me...

It is an issue with your events!

When you set the position after changing the layout in the same event, it actually changes position before the layout changes, then it puts you inside a solid wall, which pushes you outward and outside of the layout.

So yeah, either disable the behavior, disable the collision, disable the solid on walls, or save the direction and set position on start of layout. Any of these should work.
