### ISSUE TITLE
Image Point does not stay selected when changing frames

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#628]
## Problem description

If you have selected an image point but change to the next frame it will go back to origin, even though the next frame has all the same image points. So tedious!

NOT A PROBLEM IN C2

## Steps to reproduce

1. Select "Image Point X" in frame 0, , then go to frame 2 to set the position it 
2. Place the point somewhere
3. Go to the next frame and the image point is no longer selected, you click somewhere but relize you've just changed the origin point...

## Expected result

Keep the image point selected when changing frames. 

In C2 you could easily change frames and change points, now you have to take the extra time to select the points every time you change frame.

**Comment by DiegoScirra** [comment]
Fixed in r47
