### ISSUE TITLE
Scroll wheel stops working after color picker

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-3-bugs#6280]
## Problem description

After using the color picker my scroll wheel has no effect. No zoom, no page scroll, until I focus a different program.

https://user-images.githubusercontent.com/18266300/202568921-e7ae9d5f-34f8-4521-b80a-dc9636223aed.mp4

## Attach a .c3p

[color_picker_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/10036045/color_picker_bug.zip)

## Steps to reproduce

1. Open attached .c3p 
2. select tilemap or sprite 
3. use the color picker to select a color
4. try to scroll the page or zoom with ctrl+scroll wheel. It doesn't work.
5. click or alt+tab to a different program and back to Construct. It does work.

## Observed result

Zooming or page scrolling with the mouse wheel does no longer work after using the color picker.

## Expected result

That stuff should work after using the color picker.

## More details

**Affected browsers/platforms:** 

I installed C3 as a PWA via chrome

**First affected release:** 

I'm on release r317.2 but noticed this in previous releases, idk when it started or if it was always an issue.
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by TackerTacker** [comment]
I listed all the steps necessary for me to reliably reproduce the bug every time. 
I will ask around if I'm the only one with this problem.

**Comment by AshleyScirra** [comment]
I tried using the color picker pipette too - it still works fine here.

Have you tried clicking back inside the layout view? If focus isn't inside the layout view then it won't use mouse wheel events.

**Comment by TackerTacker** [comment]
Yes, I did, nothing but switching to a different program and back helps. I can still press down middle mouse button to pan around and use ctrl + +/- to zoom too, but not use the scroll wheel.

**Comment by TackerTacker** [comment]
It seems to be an issue specific to me. Others don't seem to have this problem.
I'm still on Windows 8.1, so that might be why only I get this. Tested in chrome, and as PWA. On Firefox I get a different color picker and no pipette so I don't get it on FireFox/ can't test it because the option isn't available.

**Comment by AshleyScirra** [comment]
I'm not sure what's going on, but it sounds like a one-off system-specific issue, so closing. If a reliable way can be found to reproduce the problem then a new issue can be filed and we will take another look.
