### ISSUE TITLE
Guess polygon shape is off by 1px

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-3-bugs#6284]
## Problem description

Using guess polygon shape results in the polygon always being 1 pixel offset at the right and the bottom.

![grafik](https://user-images.githubusercontent.com/18266300/202771344-1436b945-9937-440a-9357-b997510eb929.png)

## Attach a .c3p

[guess_polygon_shape_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/10043734/guess_polygon_shape_bug.zip)

## Steps to reproduce

1. Open sprite in animation editor
2. shift + P
3. right click > guess the polygon shape 

## Observed result

The resulting polygon is 1 pixel offset on the right and bottom

## Expected result

To not be offset

## More details

**Affected browsers/platforms:** 

I installed C3 as a PWA via chrome on Windows 8.1

**First affected release:** 

I'm on release r317.2 but noticed this in previous releases, idk when it started or if it was always an issue.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.

Revision 18077.
