### ISSUE TITLE
hierarchy arrow incorrect on paralax layer with show paralax in editor

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6289]
## Problem description
The hierarchy arrow is misplaced on paralax layers with show paralax in editor enabled. (it's still at the non paralax position)

## Attach a .c3p
[hierarchyParalax.zip](https://github.com/Scirra/Construct-3-bugs/files/10078566/hierarchyParalax.zip)

## Steps to reproduce
![ezgif com-gif-maker (39)](https://user-images.githubusercontent.com/89512047/203632598-55570398-f11e-4241-89c7-5f666d76ed87.gif)

1. make sure the layer is set to show paralax in editor
2. observe the hierarchy arrow

## Observed result
hierarchy arrow is at the non paralaxed position

## Expected result
the hierarchy arrow should point from/to the paralaxed position if the layer is set to show paralax in edtior

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
