### ISSUE TITLE
Image Editor: Dragging selection does not work if mouse moves outside of selection

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#629]
## Problem description

Using the "rectangle select" tool only works if the mouse stays inside the selection area, dragging the mouse too quickly outside the area will cause the selection to not work. 

## Steps to reproduce

1. Make a small area selection in a sprite
2. Drag the area
3. Move the mouse outside the area

![7677](https://user-images.githubusercontent.com/5744908/28356290-e0c824c8-6caa-11e7-921f-9d024d71f608.PNG)

## Observed result

The selected area does not move

## Expected result

It should keep up with the mouse

**Comment by DiegoScirra** [comment]
Fixed in r47
