### ISSUE TITLE
Audio in folders cannot be played by using Play (by name) event

### ISSUE THREAD

**Issue by Darkwizard9944** [Scirra/Construct-3-bugs#6290]
## Problem description

In the beta release r310 and all versions above it, there is a bug that has been made where audio that is inside a folder structure cannot be played using the event Play (by name). It will still work when outside of the folder. 

## Attach a .c3p
[AudioExamples.zip](https://github.com/Scirra/Construct-3-bugs/files/10096281/AudioExamples.zip)
Contains 3 versions

## Steps to reproduce

1. Create a project in r310 or higher with the keyboard and audio plugins
2. Create a folder inside the sound folder
3. Import an audio file into the newly created folder
4. Create an event **On key pressed** > Play (by name) 'audio file name'

## Observed result

The audio is not played.

## Expected result

The audio should have played.

## More details

TO NOTE if the r309 version is imported into a higher version where the bug appears it is not affected and works as intended.
The issue has been tested on all newer releases
This issue has been tested on Edge and Chrome on Windows

r309 works > r310 onwards is bugged.

## System details

<details><summary>View details</summary>
Platform information
Product: Construct 3 r310 (beta)
Browser: Chrome 107.0.5304.107
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

</details>

**Comment by avishaymizrav** [comment]
That's working as it should, to access files in folder with the new folder structure you need to put in the folder name too, like this:
"f/bought"

If you don't need folder support you can revert the project file structure back to Flat in the project settings.

**Comment by Darkwizard9944** [comment]
You are absolutely right I wasn't aware of this change sorry.
