### ISSUE TITLE
"Auto reload all on preview" doesn't work for project files

### ISSUE THREAD

**Issue by nerdError** [Scirra/Construct-3-bugs#6291]
## Problem description

When project is saved as a folder, and you toggle "Auto reload all on preview" for the "Files" folder, it just doesn't work. It says "0 updated" all the time, even though the files were changed. At the same time, this feature works fine for scripts. And when you manually click "reload from files", it will load updated file just fine, so only automated part of the feature doesn't work.

## Attach a .c3p

[File reload bug.zip](https://github.com/Scirra/Construct-3-bugs/files/10096914/File.reload.bug.zip)

## Steps to reproduce

1. Open project as a folder project
2. Change "file.txt" in any outside editor, save.
3. Be sure "Auto reload all on preview" is toggled for files
4. Start the preview

## Observed result

Nothing happens, like file wasn't changed, so text stays the same.

## Expected result

C3 should say "1 updated" and load the changed file, so text in the preview will match file contents.

## More details

**Affected browsers/platforms:** One of the latest chrome versions (107.0.5304.108)

**First affected release:** latest C3 release (r317.2 stable)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Chrome 107.0.5304.108
Browser engine: Chromium
Context: webapp
Operating system: Windows NT 8.0.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 268 gb
Storage usage (approx): 111 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The "Auto reload all on preview" feature was only implemented for scripts - it's only shown for other folders by accident. This is fixed for the next beta, but the fix is to hide the option for other folders and show it only for scripts, as that's the only one it affects. (The same thing happens when pressing the F9 keyboard shortcut: it reloads only script files, and not all project files.)

**Comment by nerdError** [comment]
> The "Auto reload all on preview" feature was only implemented for scripts - it's only shown for other folders by accident. This is fixed for the next beta, but the fix is to hide the option for other folders and show it only for scripts, as that's the only one it affects. (The same thing happens when pressing the F9 keyboard shortcut: it reloads only script files, and not all project files.)

Oh, okay, i see! But, by the way, there won't be auto reload feature for files, or it's just planned for later? It would be really helpful when editing css files for example. I myself had to work with them a lot recently and reloading files manually was a pretty tedious work. If files would reload alongside with scripts just by starting preview, it will improve workflow a lot.
