### ISSUE TITLE
Timeline - Crash Construct when right click on an object in it

### ISSUE THREAD

**Issue by Bcraft128** [Scirra/Construct-3-bugs#6293]
## Problem description

When you have objects in your timaline and you want to edit the properties of an object (by right clicking on it), Construct simply crash.

## Attach a .c3p

File in beta version:
https://drive.google.com/file/d/1C1OnWHVwPZ7l4eS8pop1UVIEmbGKTwnw/view?usp=share_link

## Steps to reproduce

1. Add an available object (sprite) to the timeline 
2. Right click on it, in edit mode or not

## Observed result

Crash

## Expected result

Open the popup menu for choosing to add a new property to the object for example

## More details

Tested even after relauching the browser and the computer, and on a blank project
It also append on a free account on an other computer (tested by my friend)

**Affected browsers/platforms:** 

Windows / Firefox

**First affected release:** 

I think it wasn't in the last stable version (r308), but is also appearing in the latest beta verison (r319.2).

## System details

Error details from the beta version :

<details><summary>View details</summary>

Error report information

Type: unhandled exception
File: https://editor.construct.net/r319-2/main.js, line 873, col 407
Message: TypeError: expected finite number
Stack: O.m@https://editor.construct.net/r319-2/main.js:873:407 ea.gra@https://editor.construct.net/r319-2/main.js:914:162 T2.Llb@https://editor.construct.net/r319-2/components/bars/timelineBar/timelineBar.js:240:48 T2.n0a@https://editor.construct.net/r319-2/components/bars/timelineBar/timelineBar.js:238:291 T2.Hpc/<@https://editor.construct.net/r319-2/components/bars/timelineBar/timelineBar.js:236:227
Construct version: r319.2
URL: https://editor.construct.net/r319-2/
Date: Sun Nov 27 2022 20:58:53 GMT+0100 (heure normale d’Europe centrale)
Uptime: 62.4 s
Platform information

Product: Construct 3 r319.2 (beta)
Browser: Firefox 107.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Looks like this is Firefox specific, couldn't reproduce it in Chrome and I guess there won't be a problem in other Chromium based browsers.
