### ISSUE TITLE
Setters instead of methods

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6295]
## Problem description

Why setters instead of methods? After all, I am constantly mistaken, for example, writing

```javascript
runtime.layout.scrolX = 13;
```

instead of

```javascript
runtime.layout.scrollX = 13;
```

If there was a method instead of a setter, I would see an error in the console:

`runtime.layout.setScrolX(13);` - there is no such method, great! I don't spend a lot of time looking for a bug.

You've already done well by adding the `scrollTo(x, y)` method, but what about the rest? `instance.width` instead of `instance.setWidth()`, `text.fontFace` instead of `text.setFontFace()`. Please tell me how can I get rid of the waste of time when on writing the wrong setter name I'm just looking for where I went wrong?

I have already reported a similar case

https://github.com/Scirra/Construct-3-bugs/issues/5702

This saves a lot of time, thanks a lot for this.

I noticed that a wonderful thing was introduced into JS - private fields. Now, if I suddenly make a mistake in the name of the field, they will inform me about it immediately, before the game starts, and this is wonderful.

## Attach a .c3p

There is not.

## Observed result

```javascript
runtime.layout.scrolX = 13;
```

![observed](https://user-images.githubusercontent.com/91274932/204441366-49079540-8109-4b9f-8c32-524eb4ea6c6a.png)

I don't get any error or working code.

## Expected result

```javascript
runtime.layout.setScrolX(13);
```

![expected](https://user-images.githubusercontent.com/91274932/204441503-3c2847f3-8486-4990-843d-7b1f4973bef9.png)

I see the mistake right away and understand where I made it and go to fix it right away, without spending a lot of time figuring out the reasons.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r319-2b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r319.2 (beta)
Browser: Chrome 107.0.5304.121
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 267 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This isn't a bug, it's more of a question of API design or a feature request. For what it's worth, Construct's API design is aimed at following the same style as the browser APIs which generally use the same approach. For example if you have `const url = new URL("https://www.construct.net");`, then the origin is accessed as a property `url.origin`, rather than a method `url.getOrigin()`. Similarly HTML elements consist of lots of properties such as `id`, `className`, `src`, `clientLeft`, etc. So it's pretty much just the way it's done in browsers. I appreciate the point about how error handling of methods is more explicit but the other options are duplicating existing features, which I don't think is good API design, or diverging from the way browsers work, which means the style is inconsistent and it becomes harder to remember what style to use since it depends on the API. So I think this is just something you have to live with when writing code in JavaScript with browser-style APIs.

**Comment by WilsonPercival** [comment]
> This isn't a bug, it's more of a question of API design or a feature request. For what it's worth, Construct's API design is aimed at following the same style as the browser APIs which generally use the same approach. For example if you have `const url = new URL("https://www.construct.net");`, then the origin is accessed as a property `url.origin`, rather than a method `url.getOrigin()`. Similarly HTML elements consist of lots of properties such as `id`, `className`, `src`, `clientLeft`, etc. So it's pretty much just the way it's done in browsers.
> 
> I appreciate the point about how error handling of methods is more explicit but the other options are duplicating existing features, which I don't think is good API design, or diverging from the way browsers work, which means the style is inconsistent and it becomes harder to remember what style to use since it depends on the API. I guess we could also seal the objects to make adding a new property an error, but that blocks a common coding style of adding extra properties to existing objects, which is useful in some cases. So I think this is just something you have to live with when writing code in JavaScript with browser-style APIs. I'd also point out that the autocomplete system in Construct knows all of Construct's own property names, so if you type something like `scrol`, it should be listing `scrollX` and `scrollY` in the suggestion. So if you rely on that it will make sure you enter the right property name.

No, I'm using a 3rd party notepad++ editor and don't use autocomplete.

**Comment by WilsonPercival** [comment]
@AshleyScirra You talk about following one style, but at the same time you use two options:

`sprite.setAnimation("Animation 1");`
`sprite.animationFrame = 0;`

Obviously you couldn't use the `animationName` setter, because you need to pass another `from` parameter to be able to write `sprite.setAnimation("Animation 1", "current-frame");`.

I just made another mistake by trying to assign an animation via the `animationName` setter instead of the `setAnimation()` method. So why can't you just do everything through methods?
