### ISSUE TITLE
[Project View] Can't drag and drop Objects into Layout if it's from under the "Families" Folders

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-3-bugs#6297]
## Problem description

We can drag and drop an Object from the Project View to a Layout if it's from under the "Object Types" Folder,
but it doesn't work if we do that from the "Families Folder", which is inconsistent and a bit painful or big projects with lots of Objects/Families/Folders.

Also sometimes it's just easier to find that Object from its Family rather than the place we put it manually under the "Object Types" folder.

## Attach a .c3p

[[BugReport] DragAndDropObject_FromProjectFamiliesFolder.zip](https://github.com/Scirra/Construct-3-bugs/files/10133000/BugReport.DragAndDropObject_FromProjectFamiliesFolder.zip)

## Steps to reproduce

1. Drag and Drop the Sprite Object from the Families Folder of the Project View into the Layout to create a new instance of Sprite.
2. You can't.

## Observed results VS Expected results

![BugReport_DragAndDropObject_FromProjectFamiliesFolder](https://user-images.githubusercontent.com/99751718/205072277-298f4618-9d2f-46b4-8dc3-d65c67d7c32e.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
