### ISSUE TITLE
[Project View] Can't Move Items in Project View while searching

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-3-bugs#6298]
## Problem description

As soon as the search field of Project View isn't empty (the user is searching in the Project View), the Project View feels really rigid because we can't move items anymore by drag-and-dropping them.

On big projects with lot of folders/subfolders/items, it makes Folder management very tedious as we can't use the search bar at all to find an item, to move it to the root "Object Type" Folders easily for example. We need to scroll a lot to find the item we want to move, open multiple nested folder, then start drag and dropping it, scrolling again to find the desired destination. Sometimes the destination isn't opened etc... It makes the worklow tedious for no reason.

## Attach a .c3p

[[BugReport] Move Files in Project View while searching.zip](https://github.com/Scirra/Construct-3-bugs/files/10133302/BugReport.Move.Files.in.Project.View.while.searching.zip)

## Steps to reproduce

1. Enter something in the Project View search field
2. Try to drag and drop an item or a folder inside the Project View
3. You can't.

## Observed results VS Expected results

![BugReport  Move Files in Project View while searching](https://user-images.githubusercontent.com/99751718/205080945-b1a9e732-9405-479c-b146-fca03f470b89.png)

## More details

It would really make Project Management on bigger projects easier.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.

**Comment by OverboyDev** [comment]
thank you so much for those 2 Project View fixes/enhancements Ashley !! 🙏
