### ISSUE TITLE
Uncaught type error while using pathfind and loading a new layout

### ISSUE THREAD

**Issue by ggabo** [Scirra/Construct-3-bugs#63]
## Problem description

If You try to load a new layout (or reload the current one) and there's one object with the pathfinding behavior, it will cause a crash

## Attach a .c3p

[path_bug_minimal.zip](https://github.com/Scirra/Construct-3-bugs/files/917746/path_bug_minimal.zip)

## Steps to reproduce

1.Use the player object (8-direction control) to crash into the green square, that will trigger the error

## Observed result

This message pops up:
![pathfinding_bug](https://cloud.githubusercontent.com/assets/10185699/24977350/28b7ca7c-1fa3-11e7-9684-5aebb2cc68f3.JPG)

And the game becomes unresponsive.

## Expected result

The layout should be reloaded after colliding with the dark green square. It does if the pathfinding behavior is removed.

## Affected browsers

Chrome (tested only in chrome)

## System details

<details><summary>View details</summary>

Chrome 57.0.2987.133 over Windows 8.1

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r18.
