### ISSUE TITLE
Start Page does not close once you've opened a project

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#630]
## Problem description

The start page can be useful as it shows the recently opeoned projects, but once I've opened the proejct the tab still stays open when I don't want it to because I've already oponed the project. 

This bug occurs every single day.

This is a bug because it's annoying and hinders productivity. I tried doing this as a feature request but it was ignored, maybe it will get more attention here. At a minimum it should be a setting to have it close.

Thank you.

## Steps to reproduce

1. Open C3
2. Select a project

## Observed result

The "start page" is still open.

## Expected result

It should be closed.

**Comment by AshleyScirra** [comment]
It's because C3 doesn't have any start page settings yet, specifically the "close Start Page when I click on something" setting. #300 already tracks adding this, so closing as a duplicate.
