### ISSUE TITLE
my project doesn't run when exported

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6300]
## Problem description
My project doesn't run when exported, tested with NW.js and html5. But runs in preview.

## Attach a .c3p
sadly the project is large-ish and not a minimal repro and I cannot reproduce it with a new project. I can send in the project via email if that would help.

## Observed result
running the exported project with worker
![wrkr](https://user-images.githubusercontent.com/89512047/205284186-03dbd027-bd7f-4863-a0ec-813710d410a9.png)
running it with worker set to no
![withoutWrkr](https://user-images.githubusercontent.com/89512047/205284199-9d3678ae-6281-4248-a367-25dbb466e617.png)

## More details
I get that this is not really a good bug report, so I understand if this just gets closed.
But I'm hopeful that the error message maybe hint to something that can be acted on?
Sadly the project is fairly large and having to export makes checking if the error still persists after removing elementes take a few minutes. So I struggle to narrow down what the cause could be.

**Comment by WilsonPercival** [comment]
Remove all graphics from the project.

**Comment by F3der1co** [comment]
I can e-mail the project if that would help, as I don't want to put it somewhere public.

**Comment by F3der1co** [comment]
I spend some time and figured it is connected to a 3rd party addon.
Though weirdly that 3rd party addon doesn't cause the error in a new project

**Comment by F3der1co** [comment]
closing as it is related to 3rd party
