### ISSUE TITLE
Timeline: this.GetTriggerKeyframe is not a function

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#6303]
## Problem description

Any method used in timelines that calls this.GetTriggerKeyframe seems to fail due to: 

Uncaught (in promise) TypeError: this.GetTriggerKeyframe is not a function

## Attach a .c3p
[Get_Trigger_KeyFrame_Debug_0.zip](https://github.com/Scirra/Construct-3-bugs/files/10149799/Get_Trigger_KeyFrame_Debug_0.zip)

## Steps to reproduce

1. Preview Layout 1

2. Open Debug Console

3. Press Space Bar

4. Close Preview

5. Toggle disable on any keyframe reached (any get trigger keyframe function call seems to be an issue, but this serves the point)

6. Repeat Steps 1-3

## Observed result

Project freezes

## Expected result

Timeline plays

## More details

runtime.js:9 Uncaught (in promise) TypeError: this.GetTriggerKeyframe is not a function
    at TimelineInstance.OnAnyKeyframeReached (runtime.js:9:213)
    at EventBlock._RunAndBlock (eventBlock.js:24:127)
    at EventBlock.Run (eventBlock.js:21:212)
    at EventSheet._ExecuteTrigger (eventSheet.js:19:154)
    at EventSheet._TriggerForClass (eventSheet.js:13:302)
    at EventSheet._Trigger (eventSheet.js:12:205)
    at EventSheetManager._Trigger (eventSheetManager.js:13:90)
    at C3Runtime.Trigger (runtime.js:94:125)
    at TimelineManager.Trigger (timelineManager.js:11:76)
    **at Track.OnKeyframeReached (trackState.js:26:80)
OnAnyKeyframeReached @ runtime.js:9**

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r320 (beta)
Browser: Chrome 107.0.5304.123
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 572 gb
Storage usage (approx): 107 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta, was a regression introduced in r319 as a result of fixing #6250.

Revision 18122.
