### ISSUE TITLE
Critical softlock when saving an object that uses hierarchy+templates

### ISSUE THREAD

**Issue by clovelt** [Scirra/Construct-3-bugs#6304]
## Problem description

Using the save action fails in the presence of hierarchies+templates due to:
Uncaught (in promise) TypeError: Cannot set properties of null (setting '1').

## Attach a .c3p

[bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10150096/bug.c3p.zip)

## Steps to reproduce

1. Preview Layout 1.
2. Check console to see the error.

## Observed result

Project softlocks+fails to save as soon as the action is triggered.

## Expected result

It should save normally and not softlock.

## More details
The interesting thing is, this particular object actually believed there was already an existing template of itself, and seems to be permanently bugged. As in, when isolating the issue, I managed to see there was only one instance of itself in the project, but it said it was a replica of a template named "main". After changing it around, there wasn't an option to choose the replica anymore, but you could still not set it as a template named "main", as it would prompt you with "this template name already exists". 

I tried saving different versions of the .c3p for the report, but the different states of the bug didn't seem to stick between copies (I might be wrong on this last part, as it was very hard for me to keep track of, or maybe the bug is in the cache of my c3 browser?).

I have other characters in the game with the same system/code without issue. I created all of these by cloning one instance of body and head (as in, I didn't create a new sprite and assign it to the families, etc), and this clone happened to become bugged.

**Affected browsers/platforms: Chrome/Firefox/Safari, macOS/Android** 

**First affected release: r320 beta** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r320 (beta)
Browser: Chrome 107.0.5304.110
Browser engine: Chromium
Context: webapp
Operating system: macOS 12.0.1
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 1.2 gb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
I can save the project.

**Comment by clovelt** [comment]
> I can save the project.

I wrote "save action", as in saving game data into a slot, not saving the project in the editor. You should see an error when previewing, as I mentioned in the steps.

**Comment by DiegoScirra** [comment]
The runtime crash will be fixed for the next beta.

Not too clear on the part about the issue changing between template modes, can't seem to replicate any problems easily. If there is problem it must be very specific.

Revision 18123.

**Comment by clovelt** [comment]
> 

I will try my best to replicate it again! It was all in vanilla, no addons or weird stuff.
Thanks a ton <3
