### ISSUE TITLE
Animation folder bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6308]
## Problem description

If there is not a single instance of the sprite on the layout and I try to drop the folder with images on the animation panel, then the default animation of the sprite will change. This will not happen if there is an instance of the sprite on the layout.

I also noticed that if you drag the sprite to the layout after that, it will be pink, but if you create it through events, there will be a "lol" animation.

## Attach a .c3p

[animation_folder_bug_r320b.zip](https://github.com/WilsonPercival/WilsonPercival/files/10167416/animation_folder_bug_r320b.zip)

## Steps to reproduce

1. Open a project.
2. Create a sprite. Fill it with pink.
3. Close the sprite.
4. Remove the sprite from the layout.
5. Open the animation editor.
6. Drag the folder with the image to the animations panel.

## Observed result

https://user-images.githubusercontent.com/91274932/205942178-435fada9-4689-47ca-8cc5-cc996a58efe5.mp4

## Expected result

https://user-images.githubusercontent.com/91274932/205942222-562ba04f-a89e-4de7-a437-6dac373f3927.mp4

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r320

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r320 (beta)
Browser: Chrome 108.0.5359.94
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 748 mb (1.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
The problem here is that the Animations Editor displays the animations in an object type backwards from what they are represented internally. That means the Animations editor is showing first the root level animations and then sub folders, while the internal representation is, first sub folders and then root level animations.

When you couple this with the special case of picking an icon for an object type that doesn't have any active instances in any layout and has animations in subfolders, you get the confusing result of picking the first frame of an animation that doesn't seem to be the first on the list. 

I am not keen on changing how C3 handles everything internally just for this minor issue, so the next beta will change how the Animations Editor displays the animation list so it makes more sense which frames are being picked to generate icons.
