### ISSUE TITLE
poeditor: tween properties display text is incorrect

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6309]
## Problem description

There have an extra `,` 
```
text.behaviors.tween.actions.tween-two-properties.display-text
text.behaviors.tween.actions.tween-value.display-text
```
![Snipaste_2022-12-07_00-15-16](https://user-images.githubusercontent.com/45864744/205964668-12be4607-f364-4e47-b276-ac4998cac0d6.png)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This will be sorted for the next beta.
