### ISSUE TITLE
Dark theme: Renaming animation is hard to read

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#631]
## Problem description

Renaming animation is hard to read when using the dark theme.

## Attach a .c3p

![sdfsdfsdfsdfsdfsdfsdf](https://user-images.githubusercontent.com/5744908/28352888-4afa3f52-6c9c-11e7-8a23-a05a55fefbb6.PNG)

## Steps to reproduce

1. Image editor
2. Rename an animation
3.

## Observed result

Can't see what I'm typing

**Comment by Animmaniac** [comment]
Duplicate of https://github.com/Scirra/Construct-3-bugs/issues/591

It's already fixed for the next dark theme release.

**Comment by alastajj** [comment]
Oh sorry, I thought it said fixed for next release, didn't realize the theme was separate, so I assumed it was not done correctly.
