### ISSUE TITLE
Adding behaviours & object types in offline mode breaks preview

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#6310]
## Problem description

When construct moves from online to offline mode, adding a new behaviour or object type stops the project from previewing. 

The problem also exists when construct.net is down (for example, while online, I couldn't access construct.net on Dec 6 at 12:11pm EST, which also prevented my project from previewing after adding a new behaviour.)

## Attach a .c3p

(Any new project)

## Steps to reproduce

1. Open Construct in a browser while connected to the internet.
2. Create a new project.
4. Add a sprite object.
5. Preview the project.
6. Give construct a few minutes to be ready for offline use.
7. Disconnect from the internet.
8. Add either the Timer behaviour to the sprite, or add a new Spritefont object.
9. Preview the project.

## Observed result

The project hangs at "Please wait, loading..." and I receive browser errors.

By adding a Timer behaviour: 

<img width="559" alt="Screen Shot 2022-12-04 at 4 57 03 PM" src="https://user-images.githubusercontent.com/63005234/205979199-91fd3fcc-9f4c-44c2-96ba-db91e2dbc422.png">

By adding a Sprite font when construct.net was down:

<img width="1440" alt="Screen Shot 2022-12-06 at 12 11 39 PM" src="https://user-images.githubusercontent.com/63005234/205979480-100eed76-a08c-4a99-aebc-25e1822e9830.png">

## Expected result

Preview starts as is.

## More details

**Affected browsers/platforms:** Chrome 107.0.5304.121, MacOS 12.6

**First affected release:** r320

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I tried this and it works fine for me.

90% of bug reports about offline mode seem to end up being that it didn't actually end up being able to save Construct for use offline. For example either Construct was closed before it finished, or a storage error (e.g. running out of quota space) stopped it working. Try clearing your browser cache and starting over.

If it still happens try checking in Chrome Canary as well - I think there was a Chrome bug a few weeks back that could sometimes stop offline mode working too.

**Comment by brushfe** [comment]
Ok thanks, I'll clear the cache and give Canary a shot and report back if it still happens.

**Comment by brushfe** [comment]
This seems to work well in a Canary 110.0.5473.0—hopefully that means your hunch was right! Thanks for the help!

**Comment by AshleyScirra** [comment]
If it works in Canary then I think it's that Chrome bug, so closing this issue.
