### ISSUE TITLE
Picking by highest/lowest value doesn't work as expected with families

### ISSUE THREAD

**Issue by CodyRockwell** [Scirra/Construct-3-bugs#6313]
## Problem description

The pick-by-highest/lowest-value condition produces strange results when picking objects within a family using a family variable.
This seems to be affected by a number of arbitrary factors such as UID,  other families, and instance variables for individual objects.

## Attach a .c3p

https://www.dropbox.com/s/8ews6x1ky3hs8bf/Family%20Picking%20Test.c3p?dl=0

## Steps to reproduce

1. Run the preview. The picked object in Family2 will flicker.
2. Family2's variable is continually modified. The picked object should be the one with the lowest value.

## Observed result

Regardless of which object has the lowest value, only a specific one is picked, shown by flickering.

## Expected result

As each objects' variable changes, the picked one should always be the one with the lowest value.

## More details
Deleting certain variables or replacing certain object instances can alter the results:

- Deleting Fam1_Variable causes Family2 to be picked as expected

- Deleting PinkSphere Variable causes no sprites to be picked

- Deleting BlueSphere and then adding a new BlueSphere to the layout causes Family2 to be picked as expected

- Adding either type of sphere doesn't change which sprite gets picked (it will always be thePinkSphere with UID 475)

- Having only one type of sphere causes Family2 to be picked as expected

- Deleting Family1 causes picking to work normally

**Affected browsers/platforms:** 

Chrome

**First affected release:**

 r317

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Chrome 108.0.5359.94
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 26 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report, it's a good catch - it turned out there's a tricky edge case in the event system when handling this specific situation. It should be fixed in the next beta.
