### ISSUE TITLE
audio play at object, sound keeps playing after the object is destroyed

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6316]
## Problem description

audio play at object, sound keeps playing after the object is destroyed
## Attach a .c3p

[audioNotStopped.zip](https://github.com/Scirra/Construct-3-bugs/files/10188964/audioNotStopped.zip)

## Steps to reproduce

1. start preview

## Observed result

audio keeps playing after the object is destroyed.

## Expected result

audio stops

## More details
I always though this was the intended way...
But according to this [forum post](https://www.construct.net/en/forum/construct-3/general-discussion-7/play-object-object-173918) it should stop.
tested on windows 11, chrome

**Comment by AshleyScirra** [comment]
On further review, having checked over the code, there is nothing that attempts to stop playing a positioned sound when the object is destroyed, so my earlier comment was incorrect. Apologies for the confusion. It will update the positioned sound to follow the object while it exists, but when the object is destroyed it just stops updating the positioned sound, leaving it with its last parameters.

This is all very old code so it's hard to remember what the original intent was, but I suppose this way means you have the flexibility to control it either way. You can either explicitly stop the audio by its tag when the object is destroyed so the sound stops with the object being destroyed, or you can leave it to continue playing.

I would be very reluctant to change the existing behavior of a feature that is years old, as it will likely be a breaking change for many existing projects that made use of this. Perhaps a stop-on-destroy option could be added, but that would be a feature request, and it should already be possible anyway by stopping the sound by its tag.

**Comment by AshleyScirra** [comment]
I see, yeah that makes sense. Multiple tags for Audio would be good and I'd have done it already if we had unlimited resources, but as ever, we're constantly asked to do far, far more things than we have time for, so we have to make difficult choices about what to work on.
