### ISSUE TITLE
Construct 3 crashing, Ease editor crashing when editing custom curves

### ISSUE THREAD

**Issue by Fromageinteractif** [Scirra/Construct-3-bugs#6317]
## Problem description

Once I have edited the curves I am looking for in the "Ease editor", I cannot click "Ease editor" for the keys with my custom curves again without Construct 3 crashing.

## Attach a .c3p

https://drive.google.com/file/d/1m0PnKDp_Os49hYNwG6Id1Qind6zeWyrV/view?usp=sharing

## Steps to reproduce

1. Create a new timeline.
2. Add an object to the timeline.
3. Make two simple keys for that object in the timeline.
4. Click the first key in the timeline.
5. Set "Ease" property to "Quadratic In"
6. Click Ease editor.
7. Edit the curve and create a new Ease setting called "Quadratic In 1".
9. Close the Ease editor.
10. Remain on the same key, click the ease editor again to edit your custom ease setting.

## Observed result

I see the curve editor opening and Construct 3 immediately crashing, consistently with the dialog box "Oops! Something went wrong" and the error report message

## Expected result

No crash.

## More details

This seems to happen 100% consistently. I can walk around the issue by resetting ease properties to default but I have never been able to edit previously edited ease settings with the ease editor.

**Affected browsers/platforms:** Chrome/Firefox, Windows

**First affected release:** I wouldn't know, never worked for me and started with Construct 3 from r317.2

## System details

OS Name	Microsoft Windows 10 Home
Version	10.0.19044 Build 19044
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-9JPESE3
System Manufacturer	ASUS
System Model	All Series
System Type	x64-based PC
System SKU	All
Processor	Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 4001 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 1104, 16/07/2014
SMBIOS Version	2.8
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	MAXIMUS VII RANGER
BaseBoard Version	Rev 1.xx
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Name	NVIDIA GeForce RTX 2070 SUPER
PNP Device ID	PCI\VEN_10DE&DEV_1E84&SUBSYS_87081043&REV_A1\4&3834D97&0&0008
Adapter Type	NVIDIA GeForce RTX 2070 SUPER, NVIDIA compatible
Adapter Description	NVIDIA GeForce RTX 2070 SUPER
Adapter RAM	(1,048,576) bytes
Driver Version	31.0.15.1694
INF File	oem24.inf (Section001 section)
Colour Planes	Not Available
Colour Table Entries	4294967296
Resolution	2560 x 1440 x 239 hertz
Bits/Pixel	32
Memory Address	0xF6000000-0xF6FFFFFF
Memory Address	0xE0000000-0xEFFFFFFF
Memory Address	0xF0000000-0xF1FFFFFF
I/O Port	0x0000E000-0x0000E07F
IRQ Channel	IRQ 16
I/O Port	0x000003B0-0x000003BB
I/O Port	0x000003C0-0x000003DF
Memory Address	0xA0000-0xBFFFF
Driver	C:\WINDOWS\SYSTEM32\DRIVERSTORE\FILEREPOSITORY\NV_DISPI.INF_AMD64_47917A79B8C7FD22\NVLDDMKM.SYS (31.0.15.1694, 41.72 MB (43,743,736 bytes), 10/09/2022 16:59)

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r317-2/main.js, line 1057, col 323
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
Stack: TypeError: Cannot read properties of undefined (reading 'toString') at bp.gZa (https://editor.construct.net/r317-2/main.js:1057:323) at Jec (https://editor.construct.net/r317-2/main.js:1077:477) at dLa (https://editor.construct.net/r317-2/projectResources.js:406:295) at OD.g.J.lH.P (https://editor.construct.net/r317-2/projectResources.js:2618:291) at HTMLAnchorElement. (https://editor.construct.net/r317-2/components/bars/propertiesBar/propertiesBar.js:60:200)
Construct version: r317.2
URL: https://editor.construct.net/
Date: Thu Dec 08 2022 21:33:23 GMT+0000 (Greenwich Mean Time)
Uptime: 196.2 s

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Chrome 108.0.5359.96
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
