### ISSUE TITLE
Crash: subfolder name already used

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#6319]
## Problem description

Moving a subfolder to the parent tier when there's already a folder with that name causes a crash.

(The reason this happened is that I was trying to duplicate a folder of layouts, so I did copy + paste, then it made it a subfolder)

### Solution ideas

- just automatically rename the folder instead of crashing the program when moving the folder. 
- or rename folder when copy + pasting folders (e.g. "folder" to "folder 2")

## Attach a .c3p

[New project (1).zip](https://github.com/Scirra/Construct-3-bugs/files/10192146/New.project.1.zip)

## Steps to reproduce

1. move sub folder to same tier as parent folder

![image](https://user-images.githubusercontent.com/5744908/206633488-f732757c-1751-41c8-bcfd-8ad9f0177c8c.png)

then 

![image](https://user-images.githubusercontent.com/5744908/206633595-9f54508a-89f8-4d79-bf7d-f9c77bed287c.png)

what will happen next?

![image](https://user-images.githubusercontent.com/5744908/206633727-b895c714-6eae-4e5b-aac5-4756898033d9.png)

OH NO!!!

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: subfolder name already used
Stack: Error at qa.jVa (https://editor.construct.net/r321/main.js:1098:289) at window.assert (https://editor.construct.net/r321/main.js:1014:353) at d.PO (https://editor.construct.net/r321/projectResources.js:559:368) at Acb (https://editor.construct.net/r321/components/bars/projectBar/projectBar.js:13:152) at Odb.pka (https://editor.construct.net/r321/components/bars/projectBar/projectBar.js:118:85) at Array. (https://editor.construct.net/r321/components/bars/projectBar/projectBar.js:91:462) at CCG.hh.g.J.vIa.dispatchEvent (https://editor.construct.net/r321/main.js:1227:399) at kh (https://editor.construct.net/r321/main.js:377:371) at d.zd (https://editor.construct.net/r321/main.js:1610:14) at Tb.ce (https://editor.construct.net/r321/main.js:1601:89)
Construct version: r321
URL: https://editor.construct.net/r321/
Date: Fri Dec 09 2022 16:39:16 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 548.2 s

Platform information
Product: Construct 3 r321 (beta)
Browser: Chrome 108.0.5359.99
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
