### ISSUE TITLE
8direction behavior decelerates when using "Set vector" actions

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#6323]
## Problem description

I'm not sure if this is truly a bug, but it feels very wrong to me.
Seems like if you set a vector on every tick, it gets reduced by deceleration. 
Say, I set vector X to 100, but the object really moves at 20px/s speed because of high deceleration value. However 8Direction.VectorX expression still returns 100.

## Attach a .c3p

[8dirVectorDeceleration.zip](https://github.com/Scirra/Construct-3-bugs/files/10201543/8dirVectorDeceleration.zip)

## Observed result

All objects move at different speeds. However, VectorX and Speed expressions for all three objects return 100, and the same is in Debug View.

![image](https://user-images.githubusercontent.com/36763350/206888385-50d421b0-3098-498a-bbd1-b8881d038673.png)

## Expected result

All objects should move at 100px/s speed.
Expressions should return the true speed.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Chrome 108.0.5359.99
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 588 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
https://github.com/Scirra/Construct-3-bugs/issues/6131

**Comment by AshleyScirra** [comment]
This is by design. Every tick the movement will apply deceleration, but only if the player is not holding down a control, and then move at the resulting speed.

If the player is holding down a control, either real or simulated, then the behavior knows to skip applying deceleration. However if you set the vector directly, then you skip that process and then since the behavior doesn't see the player attempting any movement, it will apply deceleration before movement.

You can see the correct speeds if you change the order of events: set the text objects to the current vectorX first, and then set the vectorX afterwards.

**Comment by dop2000** [comment]
I always thought that Set Vector or Set Velocity are "low level" actions for precise control, they should override everything else, all other speed calculations. It doesn't seem right that after setting a vector the object will move at a different and unpredictable speed.

**Comment by AshleyScirra** [comment]
Setting vectors gives you custom control over the movement, but it doesn't disable the rest of the behavior. For example you can't use 'Set vector' to move the Platform movement through the floor - the rest of the behavior's rules still apply.

**Comment by dop2000** [comment]
Ah, fair enough. I don't know how I never noticed before that setting a vector doesn't guarantee that the object will move at that speed.
