### ISSUE TITLE
HTMLElement Infinity bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6324]
## Problem description

When I set the X position of `HTMLElement` to `Infinity`, it doesn't disappear. The normal sprite disappears.

If I set it to 10000 instead of `Infinity` everything works as expected.

## Attach a .c3p

[html_element_infinity_bug_r321.zip](https://github.com/WilsonPercival/WilsonPercival/files/10201650/html_element_infinity_bug_r321.zip)

## Steps to reproduce

1. Open and run the project.

## Observed result

![observed](https://user-images.githubusercontent.com/91274932/206891161-8c920396-958b-4085-8e58-96cadd168c60.png)

## Expected result

![expected](https://user-images.githubusercontent.com/91274932/206891163-698733d0-8590-4671-9ac6-7ff5bbe86b33.png)

## More details

**Affected browsers/platforms:** Mozilla

**First affected release:** broke in r321b

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r321 (beta)
Browser: Firefox 107.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0
Language setting: en-US
Local storage

Storage quota (approx): 9.8 gb
Storage usage (approx): 18 mb (0.2%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
HTML elements must convert layer co-ordinates to CSS co-ordinates. When using a position of infinity, this conversion fails, and so there is nowhere valid to position the element. (Further, I don't think there is an obvious way in CSS to position something at infinity - you can use things like `0px` but not `Infinity px`.)

The engine will sometimes ignore positions of infinity or NaN anyway on the assumption this was a calculation error. If you want to hide something, make it invisible.

**Comment by WilsonPercival** [comment]
> HTML elements must convert layer co-ordinates to CSS co-ordinates. When using a position of infinity, this conversion fails, and so there is nowhere valid to position the element. (Further, I don't think there is an obvious way in CSS to position something at infinity - you can use things like `0px` but not `Infinity px`.)
> 
> The engine will sometimes ignore positions of infinity or NaN anyway on the assumption this was a calculation error. If you want to hide something, make it invisible.

If you hide an object, you can still click on it. It is easier for me to move it along one of the coordinate axes to such a position that it disappears from the layout and cannot be clicked on.

**Comment by AshleyScirra** [comment]
> If you hide an object, you can still click on it.

If you set a HTML object to be invisible, Construct sets the style `display: none`, which essentially removes it from the document and makes it unclickable. It should not be clickable in such a state.

**Comment by WilsonPercival** [comment]
> > If you hide an object, you can still click on it.
> 
> If you set a HTML object to be invisible, Construct sets the style `display: none`, which essentially removes it from the document and makes it unclickable. It should not be clickable in such a state and so there should be no need to use positioning instead.

This is great! Didn't know, thanks!
