### ISSUE TITLE
Debugger causes huge FPS drops on bigger Projects because it inspects System by defaults.

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-3-bugs#6325]
## Problem description

On bigger projects, the Debugger causes big FPS drops making the games unplayable and preventing us to actually debug them efficently. Because of this, I always end up not using the Debugger at all, and doing all my debug by manually adding Browser.Log Events.

I never reported it before because i always thought the issue was because of how the whole Debugger worked under the hood and it would involves too much rework for C3 devteam.

However i realized the issue was deadly simple : **the huge FPS drop only happens on the Inspect Tab and only when the System is inspected**. I don't know how it works under the hood but something wrong is definitely happening there.

The issue is that the debugger always default to the exact situation where the performance issue happens : inspecting the System, this is why I always thought the debugger as a whole was unusable.

**A really easy fix would be to stop making the Debugger inspecting the System by default : indeed it could just default to the Inspect Tab but with nothing (no System and no objects) selected/inspected.**
(unless there is just a simple thing to fix to solve that specific System Inspect performance issue)

## Attach a .c3p

I spent 1 hour trying to replicate it in a blank "dumb" project but didn't managed to make anything resulting in obvious FPS drop when inspecting Sustem. I'm sorry i couldn't afford spending more time on this. However all my bigger prototypes are affected by this. (Tried on 4 different projects made at different times, using different plugins, different C3 level skill : it always happen)

In each situation, as soon as I inspect a specific object (instead of the default "System" inspector) or if i swith the tab to Watch/CPU profiler/GPU Profiler, I get 60 FPS again (or almost) as when i just Preview my game without Debugger.

## Steps to reproduce & Observed Result

1. Open your most complex and complete project (with actual graphics/**eventsheet** game logic/big number of layouts/layer/objects/behaviors)
2. Launch a Debug Preview
3. Notice how bad the FPS drop by default (as System is inspected by default)
4. Inspect any other object instead or select any other Debugger Tab instead => FPS is way better

## Expected result

Similar FPS between Regular Preview and at least the default state of the Debug Preview (or inspecting "System")

=> Maybe not selecting the "System" by default in the Debugger Inspector would solve this : the Debugger doesn't inspect anything by default and just wait the user to select an object in the list.

## More details : tiny changes to improve Debugger usability

On Top of this Debugger default state performance issue, I think just a few tiny improvements would greatly improve the usability and efficiency of the Debugger :

- Right now only the "Hide Unused" boolean is remembered while closing/launching again the Debugger but not the search field. **It would helps a ton if the "Search" field in the object list would also be remembered**.

- **Add a second search bar for Variables to the Inspect Bar** : a search bar to look for specific values/variables in the right side of the inspect tab. Right now we need to scroll a lot to find the relevant variable we're looking for in system or on an object. Just add a search field that would only displays : 
1. The categories (and all their variables) matching the Search String
2. The specific variables of each categories matching the Search String
_Example :_ I have a Global Variable called "Perforation" (among a huge number of other Global Variables). If I inspect the System and search for "Perfo" in the new "Search variable" field : the whole category "Performance" and its variables would appear but only the Global Variable "Perforation" would appear (the Global Variable "Level" wouldn't appear for example)

![Debug Inspector improvements](https://user-images.githubusercontent.com/99751718/207018485-08fe52e1-cdb7-4149-be3b-c8768bd0d7f1.png)

- **Add a search bar in CPU Profiler Tab of the Debugger** (especially useful as there are a huge amount of entries in there - for all event sheets and groups) and we need to scroll a lot to find the relevant ones when sorting alphabetically and it's even harder when sorting by Self-Time or Total-Time and the order can change every tick. 
- Add a search bar in Watch Tab of the Debugger 
- Add a search bar in GPU Profiler Tab of the Debugger

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid as ever without a report following the guidelines, including a sample project, it is pretty much impossible to do anything about it.

Assuming your project runs in worker mode, any performance overhead of the debugger should not affect the performance of the project itself. So use worker mode if you can; otherwise if it's already in worker mode, I have no idea why there would be any significant performance overhead and would need a sample project to investigate.

FWIW across the software industry debuggers usually have a high performance overhead as they add a great deal of extra diagnostic work. So it is not unusual if the debugger causes reduced performance. It also sounds easy to work around - just switch to another tab if one view is too slow.

**Comment by OverboyDev** [comment]
Yeah i understand, as I said I didn't manage to reproduce it and can't aford to spend more time on it for now.
As i said it happens on any bigger project so i suppose it's worth it to just open the biggest project on your drive and check if what I described happens.

I'm using worker mode.

Yeah i always assumed Debugger overhead was normal but i just realized it's a pity that the worst overhead (from 60 to like 20 irregular FPS) only happens in the default state. Like why don't just make it so default state has a lower overhead ? (unselect "System" by default)

Anyway yeah i understand your points.
