### ISSUE TITLE
Cannot save or load project folders (.c3proj)

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#6326]
## Problem description

(I use the installed desktop app of C3 with chromium/brave)

I wanted to try using the "Project Folder", but I can't see an option for it.

I saw in the manual if you extract .c3p you can then open it as a folder type, rather than having to save a new/download a seperate file each time you save.

So I excracted it and tried to open the .c3proj file , but it doesn't work for some reason?

"Open Local File" seems to be the only real option that's visible to me (I sync with Mega so I can't use the "cloud" option). 

![image](https://user-images.githubusercontent.com/5744908/207039454-c8c0a799-e357-42a3-96e4-1586d0275bde.png)

then it gives this error:

![image](https://user-images.githubusercontent.com/5744908/207039566-da16fb73-9496-4d7e-b50c-28879e89faac.png)

I don't see any way to save or load "Open Local Project Folder" options? Is there a bug somewhere? 

(you can see in the screenshots above)

## System details

<details><summary>View details</summary>
Platform information
Product: Construct 3 r321 (beta)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5250000953674316
Logical CPU cores: 3
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 2 gb
Storage usage (approx): 1 gb (51.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Using a project folder requires the File System Access API. I believe Brave [disables the File System Access API by default](https://github.com/brave/brave-browser/issues/18979), presumably intended as an (in my opinion excessive) privacy or security measure. It looks like you can manually turn it back on though.
