### ISSUE TITLE
Angle and Scale Ping-Ponging Tweens Break After First Completion

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-3-bugs#6327]
## Problem description

For sprites with the tween behavior, when the performing a one- or two-property tween action with property set to "angle", "scale", "x scale", or "y scale", and with "ping-pong" set to "yes", after the sprite finishes tweening back and forth, it snaps to a different state than its initial state (specifically, it seems to snap back to the state it was told to tween to and back from). This breaks some previously functioning tweening objects and is especially jarring for looping tweens.

## Attach a .c3p

[Tween Test.zip](https://github.com/Scirra/Construct-3-bugs/files/10211323/Tween.Test.zip)

## Steps to reproduce

1. Open and run the included project or start a new project, add a sprite with tween behavior, and give it an action to tween in one of the ways mentioned above.
2. Observe that after the sprite(s) finish tweening back and forth, they then snap to a different-than-initial state rather than simply returning to their initial state.
3. That's weird, right? It seems weird.

## Observed result

Certain tween types (angle and scale) do not stay in their initial state after a ping-pong tween.

## Expected result

All tweens set to ping-pong return and stay in their initial state after the tweening finishes, as before.

## More details

Only seems to happen with angle, x scale, y scale, and scale tweens, as far as I could determine.

**Affected browsers/platforms:**  Firefox and Chrome.

**First affected release:** First appeared no later than r321 beta.

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r321 (beta)
Browser: Firefox 107.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0
Language setting: en-US
Local storage

Storage quota (approx): 58 gb
Storage usage (approx): 911 mb (1.5%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This will be fixed in r322. It was a regression introduced in r321 when attempting to to fix #6254.
