### ISSUE TITLE
Water Background effect (and other distortion), glitching after long time

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-3-bugs#6328]
After a very long time running the game (or just high timescale) the Water Background effect starts to progressively glitch.

How to reproduce:

- Create a project with a simple coloured sprite

- Apply the effect Water or Water Background to the layer or sprite (its the same)

- Use a key to set timescale 1, and another one for timescale 50.000

- Run the game, set to 50.000 timescale for a few seconds, and go back to 1.

You'll see that the effect becomes more and more glitched.

*The issue happens also with lower timescales, even 1x after very LOOONG time.

*The issue happens also if you keep the effect disabled during said ingame time and enable it at the end, or if you spawn a new instance with the effect and delete the old one.

*It also happens for Water effect (and possibly other distortion effects).

*It also happens on C2.

*I'm on C3 321 beta, Win11 home

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines. They are there to make sure we can help you.
