### ISSUE TITLE
Sprite Origins shift by about -1,-1 after every crop

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#633]
## Problem description

After every crop I make in a sprite the origin (image points) shifts position very slightly, by about -1 pixel.

## Attach a .c3p

[crop origin bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1158442/crop.origin.bug.zip)

## Steps to reproduce

1. Open the sprite
2. Position the origin points so that they're overlapping the center of the red cross
3. Crop the image
4. Look at the origin position
5. Select and Delete the purple circle from the image
6. Crop the image
7. Look at the origin position

## Observed result

Notice how the origin position changes ever so slightly, that it gradualls drifts away from the center of the red cross.

## Expected result

The origin points should stay where you originally place them on the image, regardless of how many times you crop the image.

**Comment by DiegoScirra** [comment]
Fixed in r47
