### ISSUE TITLE
Popup windows (bars) do not remember their state after restart

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6330]
## Problem description
I prefer to work with bars separated in a new window, but I have to repeat the process each time I open Construct. Please make them remember their state.
Thank you.

## Attach a .c3p

(New Project)

## Steps to reproduce

1. Right-click any bar (layers, properties, ...etc)
2. Click "Open to popup window"
3. Restart Construct

## Observed result

The bar is Undocked.

## Expected result

The bar is in a popup window (preferably at the same position it was last time).

**Comment by OverboyDev** [comment]
Not sure if it's related to this, but I think Chrome can now handle a lot of features regarding Multi-Screen Window Placement. [Multi-Screen Window Placement](https://chromestatus.com/feature/5252960583942144)

(maybe not yet fully supported in all browsers though)

**Comment by AshleyScirra** [comment]
It's difficult to automatically open popup windows, as popup blockers usually prevent that. The current design does not attempt to work around popup blockers when loading Construct.

Using the multi-screen window placement API does not appear to by itself solve the popup blocker problem, and doesn't appear to be supported by non-Chromium browsers for the time being either. Supporting multiple screens is also a related but different topic to merely remembering which popups were open.

I think this qualifies more as a feature request, so closing this issue - please use the suggestions platform instead.
