### ISSUE TITLE
Event Search window doesn't remember all aspects of sizing

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#6333]
I like to keep the search window always open in the corner, since I use it a lot, and C3 manages to remember the positioning of the window, and the sizing of the Project/layer bar:

![image](https://user-images.githubusercontent.com/5744908/207519255-e84128f0-65ea-41e2-b92d-950289625ddc.png)

But it doesn't remember the column sizing of the search window:

![image](https://user-images.githubusercontent.com/5744908/207519815-ff2cd97a-65fc-4425-9df2-3bfce41b7cb1.png)

What it's meant to look like:

![image](https://user-images.githubusercontent.com/5744908/207520268-772f255c-5369-4916-b6bd-0875e31222e8.png)

Save and open again:

![image](https://user-images.githubusercontent.com/5744908/207520980-372c6488-98e5-4eb1-bfeb-8b0a9305984a.png)

Column sizing was not remembered...

Since I don't use some of the columns, I prefer to keep them collapsed, but it doesn't remember the UI. So I have to keep resizing it every day. 

This seems broken as most other UI sizing things are remembered. 

(Using chromium/brave desktop installed)

**Comment by DiegoScirra** [comment]
This will be added to the **Find Results Bar** and the **Find All References Bar** starting on the next beta.
