### ISSUE TITLE
Dragging objects from Project bar not working if the bar is in Popup window

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6334]
## Problem description
I am trying to drag-drop an object from project bar to the layout, but it is not working because the bar is in a popup window.

## Attach a .c3p

(New Project)

## Steps to reproduce

1. Open the Project bar in a popup window
2. Double click the layout
3. Add a sprite
4. Drag the sprite from the Project bar popup

## Observed result

No effect

## Expected result

Sprite dragged normally to the layout.

## More details

**Affected browsers/platforms:** Chrome 108.0.5359.99 (Official Build) (64-bit)

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Alaadel** [comment]
Is there any updates on this issue, please?

**Comment by AshleyScirra** [comment]
I looked further in to this and I'm afraid I don't believe it is feasible to fix with current browser features. It would require hit-testing a different browser window, and there are no browser APIs that are directly capable of this, nor any obvious and robust way to work around it.
