### ISSUE TITLE
Debugger doesn't remember the string input of the Search Field in the Inspect Tab

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-3-bugs#6336]
## Problem description

Debugger doesn't remember the input of the Search Bar in the Inspect Tab.
However it works for the Hide unused boolean

## Attach a .c3p

Happens on any project

## Steps to reproduce

1. Debug Preview your project
2. Write something in the search
3. Launch de Debug Preview of your project
4. Only the "Hide unused boolean" is remembered, the Search Field is empty again

## Observed result

Only the "Hide unused boolean" is remembered, the Search Field is empty again

## Expected result

Both the "Hide unused boolean" and the **"Search" Field should be remembered**

## More details : little changes to improve Debugger usability

A few other quick improvements would greatly improve the usability and efficiency of the Debugger :

- **Add a second search bar for Variables to the Inspect Bar :** a search bar to look for specific values/variables in the right side of the inspect tab. Right now we need to scroll a lot to find the relevant variable we're looking for in system or on an object. Just add a search field that would only displays :

1. The categories (and all their variables) matching the Search String
2. The specific variables of each categories matching the Search String
_Example :_ I have a Global Variable called "Perforation" (among a huge number of other Global Variables). If I inspect the System and search for "Perfo" in the new "Search variable" field : the whole category "Performance" and its variables would appear but only the Global Variable "Perforation" would appear (the Global Variable "Level" wouldn't appear for example)

![Debug Inspector improvements](https://user-images.githubusercontent.com/99751718/207832363-0ef0534c-def1-48e2-be8a-da4f3b82bf68.png)

- **Add a search bar in CPU Profiler Tab of the Debugger** (especially useful as there are a huge amount of entries in there - for all event sheets and groups) and we need to scroll a lot to find the relevant ones when sorting alphabetically and it's even harder when sorting by Self-Time or Total-Time and the order can change every tick.

Less important but easy-to-do and nice-to-have once the first 2 are done :
- Add a search bar in Watch Tab of the Debugger
- Add a search bar in GPU Profiler Tab of the Debugger

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
If it just remembers what you last typed in the search field, then that will be applied even in other projects. It doesn't remember it because it doesn't seem appropriate to restore a search term for something that was possibly for a different project. I guess maybe it could clear the debugger search field if you switch to another project so it at least remembers it during the same session?

**Comment by OverboyDev** [comment]
Oh yeah didn't think about that ! Yeah it would probably be even better if it doesn't involve too much work. 

Otherwise, I guess it's less annoying to just have to edit the search field each time we switch to an other project rather than having to rewrite the search field each time we reload the Debugger while editing a project.

**Comment by AshleyScirra** [comment]
Added support for remembering the object list search term while using the same project for the next beta.
