### ISSUE TITLE
3DCamera usage breaks fullscreen mode inner/outer scale for 3D layer (moves offscreen)

### ISSUE THREAD

**Issue by SwiftIllusion** [Scirra/Construct-3-bugs#6343]
## Problem description

After adding the the 3DCamera, if you use it in a layout, the 3D objects don't move alongside 2D objects (e.g. interface elements) when using fullscreen mode inner/outer scaling.

## Attach a .c3p

[3DCameraFullscreenModeBug.zip](https://github.com/Scirra/Construct-3-bugs/files/10252269/3DCameraFullscreenModeBug.zip)

## Steps to reproduce

1. The project is scale outer, however play scene and scale the window and you will see the 3D dice move off screen while the 2 black squares at the edge scale downwards. 
2. Disable the action activating the 3D camera in the layout, the play the scene and you will see scale outer working correctly.

## Observed result

3D objects move off screen, ignoring fullscreen mode

## Expected result

3D objects continue to act as the chosen fullscreen mode even with 3D camera

## More details

**Affected browsers/platforms:** Observed in Chrome/Firefox, Windows

**First affected release:** Seen in current and beta (new project)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r322 (beta)
Browser: Chrome 108.0.5359.125
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 555 gb
Storage usage (approx): 377 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4090 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a bit confusing but I think I figured it out: it's actually a mistake in your events.

The problem is your events set a fixed 3D camera Z position of 869.1 on startup. This only applies to the 3D layer. However due to the way the camera math works out, the default camera Z position can change in scale inner/outer fullscreen modes. Since Construct controls the 2D layers it handles it automatically, but on the 3D layer it abides by the 3D camera position you gave it, which will have the wrong camera Z position for the same zoom level.

If you change the event to run every tick, and use `3DCamera.DefaultCameraZ` as the camera Z position, then it works correctly.
