### ISSUE TITLE
Construct 3 Crashing after paste from sprite animation

### ISSUE THREAD

**Issue by radel999** [Scirra/Construct-3-bugs#6346]
## Problem description

This happens when I want to copy the image to another object, suddenly the program crashes. E.g. When I have a tilemap and want to copy a piece of tiles to Tilemap-1 it suddenly gives an error.

## Steps to reproduce

1. Create Tilemap. 
2. Create a second tilemap in (Files) Folder
3. Copy fragment of tiles from tilemap to second tilemap.

## Observed result

A Program crashes when i paste in new tilemap file

## Expected result

A fragment of tile pastes normal as always.

## More details

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'Uf') @ TypeError: Cannot read properties of null (reading 'Uf') at Array. (https://editor.construct.net/r322/projectResources.js:392:256) at tx.g.J.Qb.dispatchEvent (https://editor.construct.net/r322/main.js:1228:42) at Array. (https://editor.construct.net/r322/projectResources.js:2116:294) at Pz.SYa.dispatchEvent (https://editor.construct.net/r322/main.js:1228:42) at Yy (https://editor.construct.net/r322/projectResources.js:178:392) at YFa (https://editor.construct.net/r322/projectResources.js:177:431) at https://editor.construct.net/r322/projectResources.js:178:279
Stack: TypeError: Cannot read properties of null (reading 'Uf') at Array. (https://editor.construct.net/r322/projectResources.js:392:256) at tx.g.J.Qb.dispatchEvent (https://editor.construct.net/r322/main.js:1228:42) at Array. (https://editor.construct.net/r322/projectResources.js:2116:294) at Pz.SYa.dispatchEvent (https://editor.construct.net/r322/main.js:1228:42) at Yy (https://editor.construct.net/r322/projectResources.js:178:392) at YFa (https://editor.construct.net/r322/projectResources.js:177:431) at https://editor.construct.net/r322/projectResources.js:178:279
Construct version: r322
URL: https://editor.construct.net/r322/
Date: Mon Dec 19 2022 10:45:06 GMT+0100 (czas środkowoeuropejski standardowy)
Uptime: 714.6 s

Platform information
Product: Construct 3 r322 (beta)
Browser: Chrome 108.0.5359.125
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
