### ISSUE TITLE
AddCordovaResourceFile (Editor API-plugin.js) Error

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#6347]
## Problem description
AddCordovaResourceFile  is not working during Android & iOS Export. 
In config.xml, the `AddCordovaResourceFile` attribute must be inside the `platform` element: `<platform name="android"></platform>` for Android and `<platform name="ios"></platform>` for iOS.

For example, like this:
```
<platform name="android">
        <resource-file src=... target=... />
</platform>

<platform name="ios">
        <resource-file src=... target=... />
</platform>
```
Instead, in the Cordova Project that I exported using Construct 3, the config.xml contains the `AddCordovaResourceFile` attribute outside the `platform` element.

## Attachments
1. C3P and C3ADDON: [Download "AddCordovaResourceFileTest.zip"](https://github.com/Scirra/Construct-3-bugs/files/10313840/AddCordovaResourceFileTest.zip)

## Steps to reproduce

1. Install _ct_1_0_0_0.c3addon_
2. Open _AddCordovaResourceFileTest.c3p_
3. Export to Android -> Android Build- Cordova Project
4. Follow the video: [Download Video](https://user-images.githubusercontent.com/42723600/209804292-9c51e36e-9a59-4cc9-85e1-4ee502f8b22c.mp4)
(This video also shows how the problem was solved by editing the config.xml)

## Observed result
Error:
```
BUILD FAILED
```
```
File google-services.json is missing. The Google Services Plugin cannot function without it.
```

## Expected result
```
BUILD SUCCESSFUL
```
```
Built the following apk(s):
        C:\Users\....app-debug.apk
```

## More details

**Tested affected release:** r317.2

___

## Problem Detailed Description
<details><summary>Read details</summary>

Hi, `AddCordovaResourceFile` is not working when I tested.

# Using Construct 3's Cordova Build server
## My plugin.js (Edittime)
```
this._info.AddCordovaResourceFile({
    src: "www/google-services.json",
    target: "app/google-services.json",
    platform: "android"
});
```
## google-services.json File in Construct Project
![image](https://user-images.githubusercontent.com/42723600/208440821-e0a67f26-2d9a-4df1-b991-6aaa8b5d1bb6.png)

## Error while exporting using Construct 3's Cordova Build server
<details><summary>Click to view Full Error</summary>
<p>

```
Error: Checking Java JDK and Android SDK versions
ANDROID_HOME=~~/androidSDK (recommended setting)
ANDROID_SDK_ROOT=~~/androidSDK (DEPRECATED)
Using Android SDK: ~~/androidSDK
The project name 'New project' contains at least one of the following characters: [ , /, \, :, <, >, ", ?, *, |]. This has been deprecated and is scheduled to be removed in Gradle 5.0. Set the 'rootProject.name' or adjust the 'include' statement (see https:/~~/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).
at cdv_gradle_name_2ds261m0ik6m78yj3b9welkmg.run(~~/cdv-gradle-name.gradle:2)
(Run with --stacktrace to get the full stack trace of this deprecation warning.)
:wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
Adding classpath: com.google.gms:google-services:4.3.8

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:javaPreCompileDebug
> Task :app:generateDebugResValues
> Task :CordovaLib:writeDebugAarMetadata
> Task :app:generateDebugResources
> Task :app:processDebugGoogleServices FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https:/~~/command_line_interface.html#sec:command_line_warnings
6 actionable tasks: 6 executed


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
Searched Location:
~~/google-services.json
~~/google-services.json
~~/google-services.json
~~/google-services.json


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 1s
Command failed with exit code 1: ~~/gradlew cdvBuildDebug -b ~~/build.gradle
```
</p>
</details>

### Error Highlights:
```
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
Searched Location:
~~/google-services.json
~~/google-services.json
~~/google-services.json
~~/google-services.json
```
Seems like `AddCordovaResourceFile` did not work at all.

___
# When Building the Exported Cordova Project manually on my computer works?
I tried building a Cordova project on my computer and added the following to config.xml:
```
<platform name="android">
        <resource-file src="www/google-services.json" target="app/google-services.json" />
</platform>
```
This method worked when I built the Cordova project on my computer.

</details>

**Comment by AshleyScirra** [comment]
This report does not follow the bug report guidelines (no repro is provided) so it's difficult to help. It could be a mistake or misconfiguration in your addon. I would suggest exporting a Cordova project from Construct (not using the build service) and verify the exported file structure and content of config.xml matches what you expect. If you manually configure it and it works, then that suggests to be a misconfiguration when it's not working.

**Comment by SparshaDhar** [comment]
Hi @AshleyScirra , I just edited my previous comment to follow the required bug report guidelines.
Yes I exported as a Cordova Project from Construct 3, then I tried to build that using Cordova CLI. But it fails, unless I manually change the content of config.xml. It works after manually configuring the config.xml

I attached a c3p, and a c3addon and all the steps required to reproduce the error. Hope it helps. 

Thanks a lot

**Comment by AshleyScirra** [comment]
Huh, you're right. The official Cordova documentation says nothing on the subject, but it does indeed appear that resource-file tags only work inside a platform tag. I'd guess this is either a Cordova bug or some undocumented limitation. Moving the tags works around it, and that's been done for the next beta. (The build service is already updated to do that.)
