### ISSUE TITLE
Steam overlay doesn't render correctly using letterbox scaling

### ISSUE THREAD

**Issue by DannyyyOnGit** [Scirra/Construct-3-bugs#6348]
The recent addition of a constantly refreshing canvas, doesn't apply to the black bars that appear in letterbox scaling mode.

## Attach a .c3p
[SteamDrawingTest.zip](https://github.com/Scirra/Construct-3-bugs/files/10260313/SteamDrawingTest.zip)

## Steps to reproduce

1. Export project for Steam
2. Add nw.exe as a "non-steam game"
3. Run the game through steam
4. Change the window size until black bars appear
5. Enable and disable the Steam overlay

## Observed result
![image](https://user-images.githubusercontent.com/86955470/208456815-ffd92f8c-6619-45ad-b63b-5c358e0459c5.png)

## Expected result
No artifacts.

## More details
The example is a Construct 2 project but it should work with any blank C3 project using the new exporting method.

**Affected browsers/platforms:** Chromium

**First affected release:** Never worked

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r323 (beta)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 2 gb
Storage usage (approx): 51 mb (2.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DannyyyOnGit** [comment]
https://www.construct.net/en/comments/58231

**Comment by AshleyScirra** [comment]
Thanks for the repro, I do see the issue and forcing the browser to redraw the document solves the problem (and appears sufficient without having to also force the canvas to redraw). It should be fixed in the next beta.

**Comment by DannyyyOnGit** [comment]
> Thanks for the repro, I do see the issue and forcing the browser to redraw the document solves the problem (and appears sufficient without having to also force the canvas to redraw). It should be fixed in the next beta.

Thanks for the hotfix! I unfortunately don't have the means to confirm the fix but it sounds like enough in-house testing has been done.
