### ISSUE TITLE
Lost Project

### ISSUE THREAD

**Issue by anasclay** [Scirra/Construct-3-bugs#6350]
I have a serious issue. 
Suddenly i  my project has disappeared from "Recent Projects" It it's supposed to be saved. I have no local backup so I'm wondering how to restore my project.
This is urgent :(

**Comment by AshleyScirra** [comment]
I'm afraid it's difficult to help without more details about exactly what you did and exactly what happened and why.

It's important to keep regular backups of all digital work to protect yourself in the event of disaster, including software or hardware failures, cyberattack (including ransomware), theft, fire, flood and so on. Construct has built-in backup features to help do this automatically for you, but you must first turn them on in Settings.
