### ISSUE TITLE
Can't run construct3 project having a sprite with animations exported as html5 on iPad 12.1.4

### ISSUE THREAD

**Issue by outbounder** [Scirra/Construct-3-bugs#6351]
## Problem description

Whatever project I export as web(html5) and try to load it in iPad it doesn't work. 

To isolate the problem I've tried with a new project having just a Text object -> it works.
However if I try with new project having Sprite object with animation in it -> it fails with blank screen.

## Attach a .c3p

[Test-iPad-12.zip](https://github.com/Scirra/Construct-3-bugs/files/10286695/Test-iPad-12.zip)

## Steps to reproduce

1. create a new construct3 project
2. add a sprite object on the layout and add animation frames
3. export the project to web html5
4. load the html5 on iPad 12.1.4 at Safari 

## Observed result

After the default preloader completes I see blank screen.  

## Expected result

To see the sprite and its animation played.

## More details

**Affected browsers/platforms:** 

* iPad 12.1.4
  * Safari
  * Chrome

**First affected release:**

* r317.2 stable

## System details

<details><summary>View details</summary>
Platform information
Product: Construct 3 r317.2 (stable)
Browser: Chrome 108.0.5359.124
Browser engine: Chromium
Context: webapp
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 10
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 556 gb
Storage usage (approx): 1.4 gb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

## Screenshots from Safari Inspector attached to iPad 12.1.4

![image](https://user-images.githubusercontent.com/125437/209129584-aa310fcb-7a5a-487e-b9cf-17cf4ef23eb1.png)
![image](https://user-images.githubusercontent.com/125437/209129665-9df15b1c-8b52-40ac-85ae-bd0e4de8a65b.png)
![image](https://user-images.githubusercontent.com/125437/209129712-71ed740c-9d16-49d5-8be4-9b471d5b3057.png)
![image](https://user-images.githubusercontent.com/125437/209129760-2d1c4c41-1a6e-4a19-837c-bda070cf163b.png)

**Comment by AshleyScirra** [comment]
Can you update the device to iOS 12.5.6?

Safari has had many serious bugs over the years. Safari 12 was too long ago to remember any specifics but 12.1.4 is not even the latest version of iOS 12 and so might have had some severe bugs that were later fixed.

I'm not sure it will be easy to investigate any further as I don't think we have any test devices left still running iOS 12, and there aren't any useful details in the error message.

**Comment by AshleyScirra** [comment]
There's been no response and the device is out of date even by iOS 12 standards, so closing.
