### ISSUE TITLE
Physics behavior not working in Playable Ad export

### ISSUE THREAD

**Issue by TechnicTom22** [Scirra/Construct-3-bugs#6354]
If the user makes any game with the "Physics" behavior and then exports it to "Playable Ad," the game will not run.

Attach a .c3p:

.C3P:
[f.zip](https://github.com/Scirra/Construct-3-bugs/files/10299111/f.zip)

Steps to reproduce:

1. Open up a C3 project.
2. Make a sprite.
3. Attach the "physics" behavior to the sprite.
4. Export the project to "Playable Ad"
5. Run it in your browser.

Observed Result:

The game loads to a black screen. In the console, it shows:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///C:/Users/username/Downloads/box2d.wasm.js. (Reason: CORS request not http).
Module source URI is not allowed in this document: “file:///C:/Users/username/Downloads/box2d.wasm.js”. index.html:1:1
Uncaught (in promise) 
error { target: script, isTrusted: true, srcElement: script, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 84, … }

Expected Result:

The game should normally run in the browser. At least it does with other projects without the "physics" behavior.

More details:
I noticed this feature when I was trying to export an actual game. I think it's tied to how the physics behavior pulls data.

Affected browsers:
I've tried doing this in both FireFox and Microsoft Edge. Same thing happens in both.

First affected release: I am not quite sure, but it does affect r317.2

System details:
Platform information

Product: Construct 3 r317.2 (stable)
Browser: Firefox 108.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
Language setting: en-US
Local storage

Storage quota (approx): 10 gb
Storage usage (approx): 1.8 gb (17.9%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
