### ISSUE TITLE
Conditions in Or-Blocks being ignored

### ISSUE THREAD

**Issue by CodyRockwell** [Scirra/Construct-3-bugs#6357]
## Problem description

Actions are not triggered when using certain conditions in an Or-Block, even when these conditions are met.

## Attach a .c3p

https://www.dropbox.com/s/ci53b7ye22y53d6/Or-Block%20Bug.c3p?dl=0

## Steps to reproduce

1. Drag and drop the Pink Square around
2. Dragging it from the Blue Circle into the Orange Circle causes it to stop flickering as expected
3. Dragging it out of the Blue Circle so that it overlaps no circle results in no changes

## Observed result

The Pink Square continues to flicker even when it is not overlapping the Blue Circle.

## Expected result

The Pink Square should stop flickering if it's either overlapping the Orange Circle OR if it's not overlapping the Blue Circle

## More details
The global boolean, isInBlueCircle, is switched to true while the Pink Square is overlapping the Blue Circle and false when it's not.
The conditions in the Or-Block test if this boolean is false Or if the Pink Square is overlapping the Orange Circle.
By switching the boolean check in the Or-Block with an overlap check of the Blue Circle, everything works normally.

**Affected browsers/platforms:** Chrome

**First affected release:** r317.2 and also tested beta 323

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Chrome 108.0.5359.125
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 85 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by dop2000** [comment]
Apparently it's not a bug, this is how OR-blocks work in Construct. I logged similar issues several times :)

The first condition (Not InsideBlueCircle) is true, so the whole OR-block is true. But "PinkSquare is overlapping OrangeCircle" condition is false, therefore PinkSquare instance is not picked. The event runs, but no PinkSquare instances are picked in it. So "PinkSquare set Flicker to False" action is skipped.

You can fix the code by changing it like this:

![image](https://user-images.githubusercontent.com/36763350/209651250-133ebef6-df1b-4ef1-90a4-e4ddef4f8a5b.png)

**Comment by WilsonPercival** [comment]
The fact is that in this event there is not a single instance selected by events, so the actions do not work.

![a1](https://user-images.githubusercontent.com/91274932/209652604-07294309-1ff1-450b-b77c-de3240fbe25a.png)

You can get around it like this:

![a2](https://user-images.githubusercontent.com/91274932/209652626-88d811b4-1d01-41dd-a064-385d2f2bf48d.png)

**Comment by CodyRockwell** [comment]
Thanks for the comments, guys :) 
I see that I was taking for granted that instances would be picked automatically as they are with other events. Glad it's not a bug.
