### ISSUE TITLE
Pressing Esc while trying to dock a panel crashes C3

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#6358]
## Problem description

https://user-images.githubusercontent.com/7268697/209698286-deb95de5-5f3f-452b-9733-549128e60606.mov

## Steps to reproduce

1. have a panel undocked, i tried with find all references
2. move it so the docking icons appear
3. put the panel over the middle docking icon
4. without releasing the mouse button, press Esc on the keyboard

## More details

**Affected browsers/platforms:** Edge Version 108.0.1462.54 (Official build) (arm64)

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r317-2/main.js, line 1286, col 143
Message: Uncaught TypeError: Cannot read properties of null (reading 'style')
Stack: TypeError: Cannot read properties of null (reading 'style') at Sf.g.bb.zqa.i0 (https://editor.construct.net/r317-2/main.js:1286:143) at Sf.g.bb.zqa.fg (https://editor.construct.net/r317-2/main.js:1286:326) at pga (https://editor.construct.net/r317-2/main.js:329:154) at osa.k6 (https://editor.construct.net/r317-2/main.js:1319:371) at HTMLDocument.lsa (https://editor.construct.net/r317-2/main.js:1314:42)
Construct version: r317.2
URL: https://editor.construct.net/
Date: Tue Dec 27 2022 19:03:22 GMT+0200 (Eastern European Standard Time)
Uptime: 7 s

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Edge 108.0.1462.54
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
