### ISSUE TITLE
Vibration length or pattern does not work on IOS

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-3-bugs#6359]
Whatever you enter in the expression is not being taken into account on ios and it just vibrates with a fixed (and way too long) length if the browser "vibrate" expression is used and it does not do anything when a vibration pattern is specified. This is really frustrating as vibrations are quite important in mobile games nowadays.

**Comment by therealPaulPlay** [comment]
I made [this plugin](https://www.construct.net/en/make-games/addons/923/taptic-engine-vibrations-c3) which solves this issue.

**Comment by AshleyScirra** [comment]
Safari does not support vibration. It looks like support in iOS apps comes from Cordova's `cordova-plugin-vibration`. The [documentation](https://cordova.apache.org/docs/en/11.x/reference/cordova-plugin-vibration/) states that it uses only a fixed length vibration for iOS, so this appears to be a Cordova limitation. (If you're willing to write code, submitting a fix for cordova-plugin-vibrate would probably be appreciated and also fix Construct.)

Construct's vibration support relies solely on the standard `navigator.vibrate()` method, which only supports a simple on-off control. If you want advanced haptics control you'll need a plugin anyway, and it looks like you already went that route, so closing this issue.

**Comment by therealPaulPlay** [comment]
Thanks for your reply. I have tried to modify the official cordova plugin to make it work, but unfortunately it did not work out. As far as I‘m concerned, there is no straightforward API that could be used here to make vibrations work in the same way as on pretty much every other platform. Unfortunately, I have very little experience in objective-c or swift, but one might be able to make this work by building their own haptic engine as shown here: https://developer.apple.com/documentation/corehaptics/chhapticengine?language=objc
…and then creating their own haptic pattern with a custom vibration length as explained here: https://developer.apple.com/documentation/corehaptics/chhapticpattern?language=objc

I might look into this in the future if I have more time but for now, the vibrations provided by my addon / the cordova plugin should be enough for most ios games/apps… I‘ve also read about a way to change the fixed vibration length in cordova, however, it seems like this isn’t working anymore as it is always 100ms for me.
