### ISSUE TITLE
Please whitelist "cordova-plugin-screen-edges" 

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-3-bugs#6368]
This plugin: https://github.com/distinctdan/cordova-plugin-screen-edges is supposed to make the homebutton on ios semi-transparent and add the "double gesture" that is required to exit the app. This is called "defer system gestures" and is used in most mobile games to make them more immersive and prevent accidental swipes from the bottom that would close the game. I did not validate the security of this plugin and lack the knowledge to do so.

**Comment by AshleyScirra** [comment]
I'm afraid that plugin does not appear to be published on npm, which is required for the build service. You can either do manual builds with the CLI, or fork it and publish it to npm yourself, and request adding that.

**Comment by therealPaulPlay** [comment]
Okay right I think I‘ll fork it once I have time :)
