### ISSUE TITLE
issue with sound when sounds placed in folder

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#6370]
## Problem description
when sounds are place in a folder then Play (by Name) does play audio and if we placed audio openly then it works.

## Attach a .c3p
[sound issue.zip](https://github.com/Scirra/Construct-3-bugs/files/10334375/sound.issue.zip)

## Steps to reproduce

1. open attached file
2. play it

## Observed result
Audio play by name not working

## Expected result
should play audio

## More details

**Affected browsers/platforms:**  Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
Due to the new folder project structure you need to use foldername/soundname instead.
Alternatively you can set it to flat mode in the project settings.

**Comment by luckyrawatlucky** [comment]
@F3der1co do you means I should type name as "folderName/sound.webp" ?
