### ISSUE TITLE
the playbayname action does not work if the sound is nested in a folder

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#6374]
## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help without more information. Without knowing more I'd assume this is a duplicate of #6370.
