### ISSUE TITLE
HandleWebGLContextLoss() has been removed from world instance SDK?

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#6378]
## Problem description

Regarding webglcontext, it looks like HandleWebGLContextLoss() has been removed from sdkworldinstancebase

Is there a new way to enable the custom options for handling webgl context loss / restore (the spine addon may need this)?

## Attach a .c3p

[Archive.zip](https://github.com/Scirra/Construct-3-bugs/files/10355556/Archive.zip)

## Steps to reproduce

1. Install include Spine addon
2. Open c3p in latest beta (r324)
3. Preview project

## Observed result

Project crashes and does not start. Debug console has an error:
Uncaught (in promise) TypeError: this.HandleWebGLContextLoss is not a function

## Expected result
Project runs and spine animation appears

## More details

Regarding webglcontext, it looks like HandleWebGLContextLoss() has been removed from sdkworldinstancebase
Is there a new way to enable the custom options for handling webgl context loss / restore (the spine addon may need this)?

**Affected browsers/platforms:** 

**First affected release:** r324

## System details

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
Thanks for catching this. Should be fixed in the next beta.
