### ISSUE TITLE
Tooltips obscured by "rendering sprites" and other System messages

### ISSUE THREAD

**Issue by PSyCHoHaMSTeRza** [Scirra/Construct-3-bugs#638]
## Problem description

Trying to read tooltips in the bottom left corner of the screen (eg, for behaviour parameters), but when saving or rendering spritesheets, tooltips are hidden behind the message

## Attach a .c3p

None needed

## Steps to reproduce

1. Save file / wait for spritesheets to render / export file
2. Click on something in the properties window (like a behaviour parameter) and try to read the tooltip at the bottom left corner of the screen.

## Observed result

System message (eg Rendering spritesheets) obscuring tooltips in bottom left corner of the screen.

## Expected result

Unobscured tooltips

## Affected browsers

* Chrome: yes
* Opera: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

No crash

</details>

**Comment by AshleyScirra** [comment]
Do those messages really stay there for long? Normally something like rendering spritesheets completes relatively quickly. Also the Properties Bar can be moved somewhere else, and wherever we move those status messages, they could end up overlapping something else too. So I'm not sure there's anything to be done about this.

**Comment by AshleyScirra** [comment]
I don't think there's any combination that is guaranteed to never overlap something else useful, so closing as won't fix.
