### ISSUE TITLE
Audio - Placing Audio Files In a Sub-Folder Of Sounds/Music -> No Audio Playing

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#6380]
## Problem description
Playing a sound or music **(By Name)** that has been placed in a sub folder of "Sounds/Music" results in no audio playing.

## Attach a .c3p
[Sound_Folder_Debug_0.zip](https://github.com/Scirra/Construct-3-bugs/files/10362741/Sound_Folder_Debug_0.zip)

## Steps to reproduce

Steps on Event sheet 1

## Observed result

Sound outside of sub-folder -> Sound plays

Sound inside sub-folder -> No Sound

## Expected result

Sound plays while in sub-folder of sound

## More details
Platform information
Product: Construct 3 r324 (beta)
Browser: Chrome 108.0.5359.125
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 572 gb
Storage usage (approx): 211 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by F3der1co** [comment]
due to the change in the project folder structure you need to use foldername/audioname.
Otherwise you can set it to flat mode in the project settings and it should work the old way.

**Comment by OneRepCloser** [comment]
> due to the change in the project folder structure you need to use foldername/audioname. Otherwise you can set it to flat mode in the project settings and it should work the old way.

Thanks [F3der1co](https://github.com/F3der1co), do you find any benefits to maintaining Folders as the export file structure?

I see that it's the recommended setting, but if having that on prevents folder organization while being able to call a file directly I might roll it back to flat.

**Comment by F3der1co** [comment]
as it's just the export I don't really see the point, especially as 3rd party stuff tends to break when using the folder structure.

**Comment by OneRepCloser** [comment]
Thanks [F3der1co](https://github.com/F3der1co).
