### ISSUE TITLE
Lazy conditions bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6382]
## Problem description

I have an `OR` block with two conditions. The first is true and the second is also true. But when the first is true, then the second shouldn't be checked, because it doesn't make sense:

![broken](https://user-images.githubusercontent.com/91274932/211173393-ac03eb86-d2a9-4b51-8200-c900ad6764ec.png)

This works well when I have an `AND` block with two conditions. The first is false, the second is true. But when the first is false, the second is not checked. It works well:

![fine](https://user-images.githubusercontent.com/91274932/211173418-0c45e9c6-7b9f-4f76-8f8d-e0aafbf765e6.png)

It also works well in scripts:

![ideally](https://user-images.githubusercontent.com/91274932/211173421-69212f9c-3dbe-4a55-89d5-5c3485e137d8.png)

## Attach a .c3p

[lazy_conditions_bug_r324b.zip](https://github.com/WilsonPercival/WilsonPercival/files/10367341/lazy_conditions_bug_r324b.zip)

## Steps to reproduce

1. Open and run the project.
2. Open the console.

## Observed result

![observed](https://user-images.githubusercontent.com/91274932/211173362-be96c03c-590c-4d6f-b893-7c3e27b7e8d7.png)

## Expected result

![expected](https://user-images.githubusercontent.com/91274932/211173365-7f9bb7d1-1b42-451c-bfd3-5985e738c7dc.png)

## More details

**Affected browsers/platforms:** Mozilla

**First affected release:** broke in r324b

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r324 (beta)
Browser: Firefox 108.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
Language setting: en-US
Local storage

Storage quota (approx): 9.8 gb
Storage usage (approx): 67 mb (0.7%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by dop2000** [comment]
Here is Ashley's comment from 2019:
> This cannot be implemented for OR conditions, because the subsequent conditions still need to run in order to set up the picked objects for the actions. Additionally, there are no performance measurements indicating this has any meaningful impact to real-world games.

I still think that conditions which don't pick instances should not be evaluated.

**Comment by dop2000** [comment]
Also, there is no need to process other conditions within one expression if the first one is true:

![image](https://user-images.githubusercontent.com/36763350/211182647-e3f0641d-8be6-4038-8bcf-5dbb807dca85.png)

**Comment by brushfe** [comment]
> Yes, this is by design. Short-circuit evaluation does not apply to Construct's OR blocks, as later conditions could still affect picking, and so later conditions must be run anyway even when it is known that the actions will be run. However short-circuit evaluation does apply to AND blocks, since as soon as it knows the actions will not be run, then nothing will refer to the picked instances, so it can exit early.

@AshleyScirra Sorry if I'm misunderstanding - this is really interesting. How would picking be possible in an OR statement? I thought each condition was treated as a separate notion? 

<img width="503" alt="Screen Shot 2023-01-09 at 1 32 45 PM" src="https://user-images.githubusercontent.com/63005234/211381917-a3f30395-8f1c-4899-a370-354570ec6047.png">

In this example, I always assumed every sprite would be checked for "on the floor" and "frame 0". But is there way to affect this picking within the OR condition?

**Comment by AshleyScirra** [comment]
By design, the condition you showed will run actions with all Sprite instances that are on the floor, or have an animation frame of 0. The issue filed here was based on the expectation that the event would stop running conditions after finding instances that are on the floor, because by that point it already knows the actions will run. However this would run actions excluding instances that have an animation frame of 0. Therefore Construct continues to run all the conditions in the OR block to make sure the actions run with all relevant instances picked.
