### ISSUE TITLE
Huge regression in speed of 'Adding files..." between r293.3 and 302

### ISSUE THREAD

**Issue by whscienceteacher** [Scirra/Construct-3-bugs#6383]
## Problem description

Change between stable 293.3 and 302 introduced a huge slow down in the 'Adding files...' step of exporting. A test of a new empty 720p landscape project game me:

3 seconds on r293.3
59 seconds on r302

~20x slow down for adding files. 

Minifying gave ~2-3x slowdown as well. 

The problem does not show without minifying. Previously, minifying added time but did not affect the Adding files... step. 

## Attach a .c3p

A default new project will show the problem. 

## Steps to reproduce

1. Open any project
2. Export to html5
3. Set Minifying to advanced

## Observed result

Very long time adding files, something that used to be almost instant. 

## Expected result

Very short  time adding files.

## More details

**Affected browsers/platforms:** 

Tested on Edge and Firefox. Both show similar patterns. 

**First affected release:** 
302
## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Edge 108.0.1462.54
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54
Language setting: en-US

Local storage
Storage quota (approx): 572 gb
Storage usage (approx): 388 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I think this is just because of the updated minifier in r295. This is provided by a third party and so unfortunately we have limited control over it. However it's not expected to be too much of a problem as minifying should only need to be done on one-off occasions when exporting a final version of the project. Indeed this change was made around 8 months ago and so far everyone's lived with it.

If you really need a faster way to minify, you can export without minifying and use a third-party minifier on the resulting JavaScript code.
