### ISSUE TITLE
Project tree folder: name problems and undo crash

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#6384]
## Problem description

_These may be related, so I've combined them into one report_

1. Dragging a nested folder in Object Types folder can cause a strange renaming problem: it keeps adding numbers to the folder's name, even though there's only one folder with that name.

2. Undoing this move will crash C3.

## Steps to reproduce

1. Create a new project
2. Create a subfolder under "Object types". Leave the folder name as-is ("New folder")
3. Create a subfolder under "New folder". Call this folder "Error".
4. Drag the "Error" folder out of the "New folder" and under "Object types".
5. Note the folder is now called "Error2". **
6. Press cmd/ctrl+z to undo the folder move.

_** You can keep dragging this "Error2" folder back into / out of the "New folder". The number suffix will increase each time._

## Observed result

Construct crashes (see crash report below)

## Expected result

1. The "Error2" folder is moved back under "New folder" without error.
2. The folder is never called "Error2" or gets any kind of number suffix. There's only one "Error" folder in the project, so it should never need to be delineated.

## More details

**Affected browsers/platforms:** Latest Chrome stable, MacOS 12.6

**First affected release:** r324

## System details: 

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: overwriting project bar item map entry
Stack: Error at qa.sVa (https://editor.construct.net/r324/main.js:1103:289) at window.assert (https://editor.construct.net/r324/main.js:1019:353) at window.sS.MJ (https://editor.construct.net/r324/components/bars/projectBar/projectBar.js:93:215) at Tcb (https://editor.construct.net/r324/components/bars/projectBar/projectBar.js:16:122) at VU (https://editor.construct.net/r324/components/bars/projectBar/projectBar.js:16:258) at window.sS.hpb (https://editor.construct.net/r324/components/bars/projectBar/projectBar.js:99:134) at Array. (https://editor.construct.net/r324/components/bars/projectBar/projectBar.js:84:81) at window.ldb.dispatchEvent (https://editor.construct.net/r324/main.js:1233:42) at CCG.Vn (https://editor.construct.net/r324/main.js:908:417) at d.ab (https://editor.construct.net/r324/projectResources.js:560:134)
Construct version: r324
URL: https://editor.construct.net/r324/
Date: Mon Jan 09 2023 23:39:56 GMT-0500 (Eastern Standard Time)
Uptime: 14.2 s

Platform information
Product: Construct 3 r324 (beta)
Browser: Chrome 108.0.5359.124
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel Inc.)
Renderer: ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics 655, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
</details>

**Comment by AshleyScirra** [comment]
@DiegoScirra - looks like a regression in r322 caused by #6319
