### ISSUE TITLE
facebook instant games saving game data problem

### ISSUE THREAD

**Issue by phill1965** [Scirra/Construct-3-bugs#6385]
using facebook instant games. in test c3p , click on green square to add 1 to "Level". this is then saved using instantgames.set player data. when test opened again, instead of value for "level" being loaded using instantgames.load player data, it stays at value 0, and developer console reports an error, (attached).

[test (3).zip](https://github.com/Scirra/Construct-3-bugs/files/10382910/test.3.zip)

## Steps to reproduce

1.  click on green square to add 1 to "level" 
2.  close test
3.  open test and "level " will still be at value 0.  not loaded as an increased value.

## Observed result

"Level" remains at o

## Expected result

test started with "level" at a higher value.

developer console error included here....

[www.facebook.com-1673344675774.log](https://github.com/Scirra/Construct-3-bugs/files/10382935/www.facebook.com-1673344675774.log)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE
[www.facebook.com-1673344675774.log](https://github.com/Scirra/Construct-3-bugs/files/10382938/www.facebook.com-1673344675774.log)

</details>

**Comment by AshleyScirra** [comment]
I doubt this is a bug in Construct. It is logging an error parsing JSON data, which came from Instant Games. The error is `Error parsing JSON:  SyntaxError: Unexpected end of JSON input`. Either the data returned by Instant Games is invalid, or perhaps it has gone over the allowed size limit and so it got truncated. Try displaying the received data so you can see if it is wrong. We don't control the Instant Games service, so if you have a problem with the data returned by it, you'll need to take it up with Facebook.
