### ISSUE TITLE
Cannot select multiple objects in project panel in Firefox, but can in Chrome

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#6386]
## Problem description

In Firefox I cannot select multiple objects in the project panel using Control / CMD. I can with the Shift key.
In Chrome I can select individual objects with Control / CMD.

https://user-images.githubusercontent.com/7268697/211620180-bfb8942e-0018-494f-bc5b-397bead3a8e5.mov

There are actually some inconsistencies between Chrome and Firefox where Firefox is put at a disadvantage. Unfortunately chromium lags on my laptop for months (mac book air M1) whereas Firefox works great. Would be amazing to see a bit more love for Firefox.

## Steps to reproduce

1. Open Crossing frog template on Firefox (108.0.2 64-bit)
2. Hold Ctrl / CMD and try to select multiple individual objects in the project panel
3. Notice it does not work

Repeat with Chrome. Notice it works.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r317.2 (stable)
Browser: Firefox 108.0
Browser engine: Gecko
Context: browser
Operating system: macOS 10.15
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0
Language setting: en-US
Local storage

Storage quota (approx): 10 gb
Storage usage (approx): 432 mb (4.2%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple
Renderer: Apple M1
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 64
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Just tried it out, turns out in OSX Firefox uses a different keycode compared to Safari and Chrome when pressing the **Cmd** key.

**Comment by DiegoScirra** [comment]
Will be fixed on the next release.
