### ISSUE TITLE
Search box in project panel not having X in Firefox (mac) as on Chrome - very low priority

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#6387]
## Problem description

In the Project panel on latest Firefox version on Mac, the X to remove the search is missing whilst on Chrome it exists.

Firefox:
<img width="667" alt="image" src="https://user-images.githubusercontent.com/7268697/211625063-b34fcb96-9787-4831-95cc-44cf8d796e98.png">

Chrome:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/7268697/211625131-5e431dc7-073f-4a72-8db5-feefdfe48a72.png">

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Chrome shows an X in `<input type="search">` elements, but Firefox does not: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

Therefore this is a difference between browsers, not a Construct issue.

You can also press escape to clear the search, which is probably more convenient anyway.
