### ISSUE TITLE
Please whitelist "cordova-plugin-screen-edges" (I published it on npm)

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-3-bugs#6394]
The plugin allows for hiding the homebutton on ios, which is called "defer system gestures" in the documentation. This makes the homebutton semi-transparent and require two swipes to go home. 

npm package: https://www.npmjs.com/package/cordova-plugin-screen-edges
github fork: https://github.com/therealPaulPlay/cordova-plugin-screen-edges 
official repository: https://github.com/distinctdan/cordova-plugin-screen-edges

**Comment by AshleyScirra** [comment]
Added `cordova-plugin-screen-edges@1.0.1` to build service.

**Comment by therealPaulPlay** [comment]
Thanks that’s great, I‘ll check whether my plugin works with the build service later this week and upload it

**Comment by therealPaulPlay** [comment]
Update: It works!
