### ISSUE TITLE
missing expressions in expressions dictionary

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#6398]
Gamepad expression dictionary doesn't show "Gamepad.LastButton(#)" in the list as shown below

![image](https://user-images.githubusercontent.com/5744908/212651964-f723c13a-5965-491c-aa49-fd4fa4eaa905.png)

**Comment by AshleyScirra** [comment]
This is due to an intentional change in [r320](https://www.construct.net/en/make-games/releases/beta/r320):

> Gamepad: replace LastButton expression with ButtonIndex, as due to an oversight LastButton never used its parameter
