### ISSUE TITLE
update Gamepad documentation

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6399]
## Problem description

Recently the Gamepad object was updated and on any button pressed -1 was added.
What is really useful about it is: gampad.gamepadIndex also returns the correct gamepad. This change is amazing and makes handling dynamic gamepad switching so much easier. So no problem here at all.

But the documentation was not updated, it still states that gamepadIndex only returns the index on connected and disconnected.

I would appreciate if the documentation of _on any button pressed_, _any button released_ and _gamepadIndex_ would be updated.

I only realized this, even though the documentation doesn't state it, because I wanted to suggest this exact thing and did some testing beforehand. :D

**Comment by AshleyScirra** [comment]
These features currently only exist in a beta release. Our long-standing policy is that the documentation is updated around the time we make a stable release, and we will update the documentation with these features accordingly.

**Comment by F3der1co** [comment]
oh yea, my bad.
