### ISSUE TITLE
Preview with Popup window: url bar is shown

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#640]
## Problem description

When you preview with the Popup window setting the URL bar is shown, this is not needed and also causes the game to shrink in size.

## Attach a .c3p

![image](https://user-images.githubusercontent.com/5744908/28513656-40df7634-709a-11e7-950c-1429d20b9d4e.png)

## Steps to reproduce

1. Run a game in popup setting, black bars setting too if you want to see how it causes it shrink

## Observed result

The game is shrunk, notice the black bar on the side, and the URL bar is visible.

## Expected result

The URL bar should be hidden so that it's not wasting space.

**Comment by shortercode** [comment]
Looking into it this is a chrome security "feature" that popup's must always have an address bar so I'm afraid this isn't going to change. Refer to [hide-bar-address-in-popup-chrome](https://stackoverflow.com/questions/15230137/hide-bar-address-in-popup-chrome)

**Comment by alastajj** [comment]
That's annoying, should be able to at least do it in the desktop app!

**Comment by shortercode** [comment]
I expect we will be able to do it in the desktop app yes. But I haven't really looked into it.
