### ISSUE TITLE
wrong expression in gamepad manual entry

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#6401]
related to #6398 and r320

>Gamepad: replace LastButton expression with ButtonIndex, as due to an oversight LastButton never used its parameter

The gamepad manual entry refers to lastbutton despite it being replaced:

https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/gamepad

**Comment by F3der1co** [comment]
#6399
did a very similar report today :D check Ashleys comment, it will be upadated when the stable drops.

**Comment by alastajj** [comment]
thanks mate! 

Hopefully the expression dictionary will update at this time too. 

It's very confusing right now! Especially as now that the update lets you do any gamepad index button check, it doesn't say that gamepadindex will let you get the index of the button pressed.

**Comment by AshleyScirra** [comment]
As per #6398, the documentation will be updated at the next stable release.
