### ISSUE TITLE
Out-Tweens within hierarchys don't reach the correct endpoint

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#6403]
## Problem description

Out-Tweens with **size** don't reach the correct endpoints within hierarchies unless the hierarchy transforms are disabled.

## Attach a .c3p

[tweenhierarchy.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10446635/tweenhierarchy.c3p.zip)

## Steps to reproduce

1. Preview layout

## Observed result

The middle sprite does not reach the size it's supposed to.

## Expected result

All sprites to reach the specified size

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r326 (beta)
Browser: Chrome 109.0.5414.75
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 4.4 gb (3.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Not really sure what is happening, but I can tell there is a problem with setting the size to 0. If you set the initial size to 1, it works as expected (or a small value closer to 0 but not quite).

It's an implementation detail, but as far as hierarchies working with sizes or scales is concerned, 0 is basically not allowed. Internally the runtime always makes sure to avoid 0 because it messes with all the maths going on, instead a really small number is used, which for practical purposes is the same as 0 with the crucial difference that it doesn't screw up the math.

**Comment by Wackytoaster** [comment]
Hmm I see. Setting it to 1 is fine by me, but I suspect that people will eventually run into this problem again at some point unless it's fixed.

**Comment by DiegoScirra** [comment]
Oh yes, I will look into it further to see just why setting the size to 0 does this.

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.
