### ISSUE TITLE
can't see family properties if no member is in current layout

### ISSUE THREAD

**Issue by StefanSava** [Scirra/Construct-3-bugs#641]
## Problem description

Family properties are not being displayed in the properties bar. (family behaviors & family variables) 

## Attach a .c3p

*This can be easily replicated*

## Steps to reproduce

1.Create a family from two sprites
2.Create a second layout and have that visible
3.Select the family 

## Observed result

family variables and family behaviors are not visible

## Expected result

see all family properties regardless if any members are on the selected layout

## Affected browsers

* Chrome: yes

**Comment by StefanSava** [comment]
Maybe I need to clarify a bit - if i have, for example, one member of a family in the selected layout. And I select the family from the project box, I see a incomplete list of properties on the left with missing instance variables and behaviors.

**Comment by shortercode** [comment]
Hi @StefanSava thanks for the report, I can confirm that I'm seeing the same behaviour and it doesn't match C2. We're working on it!

**Comment by StefanSava** [comment]
Thanks!

**Comment by shortercode** [comment]
Sorted! Check back when r47 goes live :)
