### ISSUE TITLE
Runtime Crashing when loading under GameMonetize.com portal

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-3-bugs#6412]
## Problem description
When you export any construct project and upload it to GameMonetize.com, the runtime crashes with _undefined_ exceptions in the console. I tested my complex projects and completely blank projects (no events, code or anything) and it throws errors everytime. This is not an error within the platform GameMonetize, but instead an exception at runtime. The game doesn't even load the runtime.
The runtime crashes in the method where the splash screen is loading when trying to initialize the runtime.

## Attach a .c3p
No need, simply export a blank project to HTML5, it can be either minified or not, as well as either running in worker or not and it will crash.
[TestBlank.zip](https://github.com/Scirra/Construct-3-bugs/files/10467849/TestBlank.zip)

## Steps to reproduce
1. Create a blank project on construct r317.2 Stable
2. Export the project as an HTML5 game
3. Create an account at GameMonetize.com (it's completely free) at https://gamemonetize.com/account/register.php 
4. Login to GameMonetize.com at https://gamemonetize.com/account/login.php
5. Under the "Developer" section click on "Add Game"
![image](https://user-images.githubusercontent.com/10860045/213629803-0a5ddeec-1f4a-4f96-b6ed-fdc8f5fa8e48.png)
6.  Upload the exported project
![image](https://user-images.githubusercontent.com/10860045/213630558-52523211-5ddb-4021-a663-8808d28d5c2d.png)

7. Click on "Verify game"
![image](https://user-images.githubusercontent.com/10860045/213630697-83ede9b6-832c-4212-9679-05e5ef2c0ef8.png)

8. Open the developer console and see the error messages. These messages appear regardless if you are using the GameMonetize plugin or not.
![image](https://user-images.githubusercontent.com/10860045/213632799-4b17ac32-b39c-4397-9f9c-75b685f72ebf.png)

## Observed result

Construct runtime fails to load, hence all the game is unable to run.

## Expected result

Runtime should not crash

## More details
You'll notice two exceptions: 
The first one states that the XPathResult property is undefined (probably you minified the **_window_** object)
![image](https://user-images.githubusercontent.com/10860045/213631237-18f665c8-f8c8-4249-bdec-b0e8450ddd3e.png)

The second error regards an undefined function when initializing the runtime:
![image](https://user-images.githubusercontent.com/10860045/213631294-02d516fd-9095-4b54-ba43-423b48683fe7.png)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

## More details

**Affected browsers/platforms:** 
Chrome Versión 109.0.5414.75 (Build oficial) (64 bits)
Firefox 109.0 (64-bit)

**First affected release:** 
Construct r317.2 Stable

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Chrome 109.0.5414.75
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 572 gb
Storage usage (approx): 1.2 gb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I signed up an account, exported the Ghost Shooter demo, added a game, uploaded it and clicked "verify". It loaded and ran the game just fine. So it seems to be working fine for me.

Besides, if it works everywhere else but doesn't work only on GameMonetize.com, that suggests the problem is with their service and so should be reported to them.
