### ISSUE TITLE
Active layer is reset to the topmost layer in layout editor

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#6415]
This issue was bugging me for years.. Active layer is constantly reset to the topmost layer, which is often a HUD layer, invisible and locked to prevent edits. And objects are dropped on the layout, they are added to that locked layer..

I even posted on the suggestion platform assuming that the editor doesn't remember active layer. Turned out it's a bug and I finally found the way to reproduce it.

## Attach a .c3p

[ActiveLayerBug.zip](https://github.com/Scirra/Construct-3-bugs/files/10473954/ActiveLayerBug.zip)

## Steps to reproduce

1. Open the project, check both layouts - layer "BG" is active on both.
2.  Restart the editor.
3. Open the project again, **without clicking on Layout1 tab,** move the red sprite on Layout2, save the project. It's important not to touch Layout1 tab.

4. Restart the editor, open the project.
5. Notice how "FG" now became the active layer on Layout1

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r326 (beta)
Browser: Chrome 109.0.5414.75
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 272 gb
Storage usage (approx): 636 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
@DiegoScirra - I think the active layer is stored in UI state, so looks like something about the UI state not being preserved across saves?

**Comment by DiegoScirra** [comment]
The setting was saved, but now restored properly. Will be fixed in the next beta.
