### ISSUE TITLE
Right-click not working in Timeline window if it was a Popup

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6416]
## Problem description
If the Timeline window is in a popup, right-clicking the Object or Property will not work (but clicking the Timeline itself still works). I am using Chrome app.

## Attach a .c3p
[Timeline Popup.zip](https://github.com/Scirra/Construct-3-bugs/files/10473966/Timeline.Popup.zip)

## Steps to reproduce

1. Open the timeline window.
2. Open it in a popup.
3. Try to right-click the Timeline name, Object name, Property name in the window.

## Observed result
Right-clicking the Timeline name works, but right-clicking Object name, Property name doesn't work.

## Expected result
Everything should work as normal windows.

**Comment by DiegoScirra** [comment]
This seems to be a rather old regression that got into the stable channel with r302. Since it is a rather simple fix it might go out in a patch to the latest stable.
