### ISSUE TITLE
Timeline animaiton breaks after adding the parent to another parent

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6417]
## Problem description

I had an object A attached to a parent B. I made a timeline animation for A and tested it. B is not moved in the animation.
Then I added B as a child for C. Now the animation is messed up! It moves generally in the same movement, but with random movements (sometimes skipping rotations..etc) in between, which pile up and mess up the rest of the animation.
The attached project will hopefully make things clear.

Update 1: The timeline is not recognizing the hierarchy anymore. Before adding the new parent, the timeline would move the children when I move their parent. Now, only the parent moves alone.
I've tried to remove the track, re-create the hierarchy (of the small objects, not the new parent), delete the timeline and re-create it, restart C3, and still the timeline is not recognizing the hierarchy.

Update 2: Only when I remove the newly added parent, the timeline recognizes the hierarchy again and moves children as intended.
So I presume the issue is that timeline saves the initial hierarchy state when the timeline is first created, and (in this case) never changes it, even if the user changed the hierarchy. The case is adding the initial parent to a new parent.

Update 3: Even after deleting all instances and recreating them, the issue remains.
I had to remove the small objects from their parent (the blue sprite) so the timeline moves them again.
Maybe the issue is with the number of hierarchy levels? Timeline works with 3 levels, but once you add a new level (parent of the grandfather!) it breaks?

## Attach a .c3p
[timeline hierarchy.zip](https://github.com/Scirra/Construct-3-bugs/files/10474087/timeline.hierarchy.zip)

## Steps to reproduce

1. Play the timeline animation (to see the intended move).
2. Add the blue sprite as a child to of the red sprite. (so Sprite becomes the parent of Sprite2)
3. Play the animation.

## Observed result
Original animation is now messed up.

## Expected result
Original animation should not be affected with parenting, specially when the objects (blue and red sprites) are stationary.

**Comment by DiegoScirra** [comment]
I noticed that adding the blue sprite to the timeline, even with out performing any animations on it produces the expected results. 

That is just a work around though, will have to look into this further to figure out what is the problem.

**Comment by Alaadel** [comment]
> I noticed that adding the blue sprite to the timeline, even with out performing any animations on it produces the expected results.
> 
> That is just a work around though, will have to look into this further to figure out what is the problem.

Thanks, I will try to use it in the time being.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
