### ISSUE TITLE
Crash when dragging an image from Firefox to Animation Frames window

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6419]
## Problem description
I am using Firefox on Win7x64. Tried to drag [this image](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.wrlX1oVAa3z4H4ZtzKqyKgHaC1%26pid%3DApi&f=1&ipt=63ed4f79576f323dd2dfbd9199d8216c3d82e10eac081b0c6c6c8aa51e7bb2e5&ipo=images) (and others, jpg and bmp) from FF to C3 (Chrome App). I dragged it to the Frames window in the Animator window, then Chrome says (in case of bmp) that the file is not supported and I should chose another, so I click to choose a different file, then crash.
I tried the same in GIMP and got this error:
```
Opening 'C:\Users\[my user]\AppData\Local\Temp\xnvv7v2g.bmp' failed:

Could not open 'C:\Users\[my user]\AppData\Local\Temp\xnvv7v2g.bmp' for reading: No such file or directory
```

## Attach a .c3p
(New project)

## Steps to reproduce

1. Open the image in FF
2. Add a Sprite and open its animation editor
3. Drag the image from FF to the Frames window

## Observed result
Crash

## Expected result
Normal File Import Mode window (i.e. from files or sprite strip).

## More details

**Affected browsers/platforms:** Firefox 109 64-bit

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at R.Ga (https://editor.construct.net/r317-2/main.js:904:131) at iB.iec.q4 (https://editor.construct.net/r317-2/projectResources.js:2397:35) at p0a.lec.SO (https://editor.construct.net/r317-2/projectResources.js:2325:357)
Stack: TypeError: unexpected type at R.Ga (https://editor.construct.net/r317-2/main.js:904:131) at iB.iec.q4 (https://editor.construct.net/r317-2/projectResources.js:2397:35) at p0a.lec.SO (https://editor.construct.net/r317-2/projectResources.js:2325:357)
Construct version: r317.2
URL: https://editor.construct.net/
Date: Sun Jan 22 2023 18:07:30 GMT+0200 (GMT+02:00)
Uptime: 9.5 s

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Chrome 109.0.5414.75
Browser engine: Chromium
Context: webapp
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 610 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
