### ISSUE TITLE
Crash with r327 stable in Animation Editor

### ISSUE THREAD

**Issue by squalinho** [Scirra/Construct-3-bugs#6423]
## Problem description

Construct crash with animation editor preview.

## Steps to reproduce

1. Create sprite, 
2. Edit with animations Editor, 
3. launch Preview Animation and without close Preview duplacate current frame, 
4. Construct Crash.

## Observed result

Crash

## System details

Windows 10 
<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: frame not found @ Error: frame not found at d.onb (https://editor.construct.net/r327/projectResources.js:734:357) at d.xo (https://editor.construct.net/r327/projectResources.js:746:342) at $Ia (https://editor.construct.net/r327/projectResources.js:300:58) at dJa (https://editor.construct.net/r327/projectResources.js:296:298) at A_a.nPb.zH (https://editor.construct.net/r327/projectResources.js:1960:164) at e (https://editor.construct.net/r327/projectResources.js:413:67) at Array. (https://editor.construct.net/r327/projectResources.js:413:123) at window.ldb.dispatchEvent (https://editor.construct.net/r327/main.js:1232:42) at window.ldb.sM (https://editor.construct.net/r327/main.js:2507:391) at d.UZa (https://editor.construct.net/r327/projectResources.js:744:447)
Stack: Error: frame not found at d.onb (https://editor.construct.net/r327/projectResources.js:734:357) at d.xo (https://editor.construct.net/r327/projectResources.js:746:342) at $Ia (https://editor.construct.net/r327/projectResources.js:300:58) at dJa (https://editor.construct.net/r327/projectResources.js:296:298) at A_a.nPb.zH (https://editor.construct.net/r327/projectResources.js:1960:164) at e (https://editor.construct.net/r327/projectResources.js:413:67) at Array. (https://editor.construct.net/r327/projectResources.js:413:123) at window.ldb.dispatchEvent (https://editor.construct.net/r327/main.js:1232:42) at window.ldb.sM (https://editor.construct.net/r327/main.js:2507:391) at d.UZa (https://editor.construct.net/r327/projectResources.js:744:447)
Construct version: r327
URL: https://editor.construct.net/
Date: Tue Jan 24 2023 21:11:03 GMT+0100 (heure normale d’Europe centrale)
Uptime: 13.7 s

Platform information
Product: Construct 3 r327 (stable)
Browser: Chrome 109.0.5414.75
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 670MX Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
