### ISSUE TITLE
Property sizePt text in hierarchy bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6424]
## Problem description

The `sizePt` property of the text changes when I add it to the hierarchy.

![description1](https://user-images.githubusercontent.com/91274932/214483914-2ebbc50d-4031-4699-ad64-e2ef3fa98e51.png)

What the project does:
1. Creates `sprite1`.
2. Creates `sprite2`.
3. Adds `sprite2` hierarchy to `sprite1`.
4. Changes the width of `sprite2` to 100.
5. Creates `text1` and attaches `text1` in a hierarchy to `sprite2`. You can see how the text looks smaller than it should be.
6. Creates `text2`. It can be seen that everything is working well.

This bug does not reproduce if:

1. Remove `Sprite1`:

![a1](https://user-images.githubusercontent.com/91274932/214484375-29459ce0-47ff-4249-8aa6-3874b1f85acf.png)

2. First change the width of `sprite2` and then add `sprite2` hierarchy to `sprite1`:

![a2](https://user-images.githubusercontent.com/91274932/214484572-189fe467-2546-4cfa-b4d6-10c767eef3c2.png)

3. Don't add `text1` through the hierarchy to `sprite2`. I demonstrated this by creating the same text side by side and not adding it to the hierarchy:

![a3](https://user-images.githubusercontent.com/91274932/214484761-5cc155e0-0385-4abc-8d3c-5e640ad83d59.png)

## Attach a .c3p

[property_size_pt_text_in_hierarchy_rose-cheeked_bug_r327s.zip](https://github.com/WilsonPercival/WilsonPercival/files/10496318/property_size_pt_text_in_hierarchy_rose-cheeked_bug_r327s.zip)

## Steps to reproduce

1. Open and run the project.

## Observed result

![observed](https://user-images.githubusercontent.com/91274932/214483896-b0c159c2-75b0-4aaf-bf0d-397e9786bf24.png)

## Expected result

![expected](https://user-images.githubusercontent.com/91274932/214483906-45d6ed30-020f-4ded-8751-058e52c136a6.png)

## More details

![original - копия](https://user-images.githubusercontent.com/91274932/214488774-416dff08-5be7-4282-b01f-7e01f8baa0af.png)

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r327s

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r327 (stable)
Browser: Chrome 109.0.5414.75
Browser engine: Chromium
Context: webapp
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 237 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I believe this is by design. When in a hierarchy, text objects scale their font size to match the scaling of the parent. text1 is a child of a sprite that was resized to 40% of its width and so will be scaled; text2 is not a child in a hierarchy and so won't be scaled. Only one font size can be chosen so if an object is resized differently on width and height then Construct uses the minimum scale, so if the width is 40% and the height is 100%, then the text size will be scaled to 40%.
