### ISSUE TITLE
Facebook Instant Game problem uploading

### ISSUE THREAD

**Issue by am-brick** [Scirra/Construct-3-bugs#6428]
## Problem description

When trying to upload a game to Facebook Instant Games page, an error is thrown:  Games must use the Instant Games SDK properly and should not call private methods directly.

## Attach a .c3p

[BrokenFBGame.zip](https://github.com/Scirra/Construct-3-bugs/files/10502128/BrokenFBGame.zip)

## Steps to reproduce

1. Add Instant Games plugin to project
2. Export project using Facebook Instant Games option
3. Upload exported zip file to Web Hosting page of Facebook Instant Games website

## Observed result

I receive an error message from Facebook: Games must use the Instant Games SDK properly and should not call private methods directly.

## Expected result

I expected the file to upload successfully.

## More details

I have tried exporting and uploading various project zip files that were created using Construct 3's Facebook Instant Games option but none of them work.

**Affected browsers/platforms:**

Tried Google Chrome and Mozilla FireFox on Windows 11 Pro.

**First affected release:** r327

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r327 (stable)
Browser: Edge 109.0.1518.61
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.61
Language setting: en-US

Local storage
Storage quota (approx): 1.1 tb
Storage usage (approx): 1.5 gb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by phill1965** [comment]
hi there, same problem here. did you find a solution?

**Comment by AshleyScirra** [comment]
I think the error message is misleading: Facebook doesn't understand the Zip64 format, which Construct now uses for zip files. You can work around it by extracting the files, adding them back to a zip, and then uploading again.

Construct is however creating a valid Zip64 file, so the problem is with Facebook's service. You'll need to report it to them to get it fixed.
