### ISSUE TITLE
"Export for Steam", blank Steam overlay

### ISSUE THREAD

**Issue by 68kStudios** [Scirra/Construct-3-bugs#6432]
The overlay on Steam is blank

## Attach a .c3p
https://drive.google.com/file/d/1uwge5SaQQTyboLeUSvBfAJqPHrAySyui/view?usp=sharing
there is nothing in this project, the issue is in the export so I think that you can try with any c3p file

## Steps to reproduce

1. Export to Nwjs with "Export for Steam" option flagged
2. Submit to Steam
3. Start the game using the Steam client

## Observed result

You see a white box in the bottom-right corner and a blank screen if you press SHIFT+TAB to open the Steam overlay

Screenshot: https://www.68kstudios.com/images/whitebox.jpg
## Expected result

You should see the login message and the Steam Overlay
## More details

Greenworks plugin 0.71.0 installed, Steam sdk 150, chromium 0.71.0, sdkencryptedappticket64.dll and steam_api64.dll in the package.nw and steam_appid.txt in the main folder of the game.

Also tried to add --disable-direct-composition to the package.json file.

**Affected browsers/platforms:** 
Steam client, windows

**First affected release:** 
tried with the latest stable release, r327
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's not possible for us to fix the Steam overlay as that's part of Valve's software. You'll need to report the issue to them.

You can try adjusting the command line parameters to see if there's something that works around the problem, but if not, then only Valve can fix an issue with the Steam overlay.

**Comment by 68kStudios** [comment]
@AshleyScirra I don't think that is an issue with Steam because if I don't flag the option "Export for Steam" and I manually modify the package.json file adding --in-process-gpu --disable-direct-composition, it works correctly (see here https://www.68kstudios.com/images/whitebox2.jpg)

**Comment by 68kStudios** [comment]
`"c3-steam-mode": true` and `--disable-windows10-custom-titlebar` are the only differences between the non-working and the working project. (the working one is missing `--disable-windows10-custom-titlebar` and `"c3-steam-mode"` is set to false).

**Comment by AshleyScirra** [comment]
We need those settings for the Steam overlay to work in other cases, though. Overall those settings are there to work around other existing problems with the Steam overlay. Basically it has bugs we try to work around, but there is only so much we can do - it's fundamentally up to Valve to ensure the Steam overlay works correctly.
