### ISSUE TITLE
No WebGL1 support in r327

### ISSUE THREAD

**Issue by lightwood** [Scirra/Construct-3-bugs#6433]
## Problem description

Projects exported from Construct r327 do not appear to support WebGL 1 when WebGL2 is not present.

## Attach a .c3p
[SampleProject.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10519918/SampleProject.c3p.zip)

## Steps to reproduce

Open this link on an affected system:
https://www.uketok.com/SampleProject/ 

The problem appears to be specific to browsers that do not support WebGL2. This is checked using edge://gpu or chrome://gpu - users who have the following system information are affected:

![Graphics Features - kelly](https://user-images.githubusercontent.com/151248/215115862-fcfabcd1-5371-4d78-bdf6-b4b60cc4b266.jpg)

Anecdotally, the project runs as expected only when WebGL2 support is present. Both Edge and Chrome exhibit the problem on this system. 

## Observed result

The project does not run and displays a black screen. System console reports "failed to acquire a renderer"
 
![WebGL issue](https://user-images.githubusercontent.com/151248/215115968-543bd890-e2da-49af-83da-61c524834038.jpg)

The project should execute and display a text label:
<img width="1506" alt="Screenshot 2023-01-27 at 14 54 00" src="https://user-images.githubusercontent.com/151248/215116264-14849349-3909-4578-af77-e08412610b6f.png">

**Affected browsers/platforms:** 

Reproduced using Chrome and Edge on Windows on a system without WebGL2. 3 end-users confirmed issue so far.
Cannot be reproduced using Safari on Mac or iOS; or on Windows browsers where WebGL2 is present.

**First affected release:** 

Same project works when built using r317-2 but does not work in r327

## System details

<details><summary>View details</summary>

Note: This is the platform information for my development machine, which does NOT exhibit the problem.

Platform information
Product: Construct 3 r327 (stable)
Browser: Chrome 109.0.5414.87
Browser engine: Chromium
Context: webapp
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 556 gb
Storage usage (approx): 101 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M2, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by WilsonPercival** [comment]
I am having the same problem. My browser version is 109.0.5414.120. Have you tried updating your browser version?

**Comment by lightwood** [comment]
> 

I can't reproduce this myself. The end-user who is helping to diagnose this has installed the latest updates to both browsers and rebooted several times.

**Comment by AshleyScirra** [comment]
In r327 you can force the editor to use WebGL 1 for both the editor and preview. If I do that, I can preview that project using WebGL 1 and it appears correctly. I also tried exporting the project and manually adjusting the exported code to only request WebGL 1, and that also worked fine. So it looks to me like Construct's WebGL 1 support is still there and working.

I suspect the problem is not to do with Construct and that it comes down to faulty graphics driver, which is very commonly what this kind of issue is caused by. I'd suggest getting them to install any available software updates, try updating their graphics driver, or try a different browser.

**Comment by lightwood** [comment]
The issue title may be erroneous, but this is not completed. I'm happy to gather more information as necessary. Can we re-open, or is a new ticket more appropriate?

The only variable is r317 vs r327. Affected users can run a project generated by one version of Construct but not the other.

Perhaps I assumed wrongly that WebGL 1 was the reason, but I think I demonstrated that compatibility has changed with this update. Presumably this is not intentional?

Is there anything I can get an affected user to run to help to diagnose further? Can we find out which renderers are supported on that system, and which one(s) Construct is attempting to use before failing?

**Comment by lightwood** [comment]
I exported a test project with every Construct version from r317 to r327. With r320 and below it works as expected. With r321 and higher, it's the black screen and "failed to acquire a renderer" error.

**Comment by AshleyScirra** [comment]
This problem usually is caused by broken graphics drivers, not Construct, in which case it is out of our control. Graphics drivers are a system-level component (not even part of the browser) and historically most issues relating to graphical glitches or WebGL errors are caused by broken graphics drivers, which is also a common and widely recognized problem in the industry.

Broken graphics drivers can fail under what are essentially a random combination of factors. An entirely valid and correct change to Construct's rendering code can, therefore, still cause broken graphics drivers to stop working when they previously worked. In this case it is still the graphics drivers that are broken and not Construct.

**Comment by nerdError** [comment]
> This problem usually is caused by broken graphics drivers, not Construct, in which case it is out of our control. Graphics drivers are a system-level component (not even part of the browser) and historically most issues relating to graphical glitches or WebGL errors are caused by broken graphics drivers, which is also a common and widely recognized problem in the industry.
> 
> Broken graphics drivers can fail under what are essentially a random combination of factors. An entirely valid and correct change to Construct's rendering code can, therefore, still cause broken graphics drivers to stop working when they previously worked. In this case it is still the graphics drivers that are broken and not Construct.

In my case, i have pretty old laptop, and i have the same game exported on versions r317 and r327. And like, same gpu, same drivers (i dont think i can really update anything sine this laptop is ~13 years old), same chrome, same windows version, only C3 version is variable in this situation. And so I just run both versions in different tabs and the one exporeted from r317 works perfectly, while the same game exported from r327 always fail. 
Same situation in the Edge.

Can this be not casued by Construct still?

![Screenshot_70](https://user-images.githubusercontent.com/55310192/219379034-548dcab9-8ae7-446f-9356-9f4c90b52fef.png)
![Screenshot_74](https://user-images.githubusercontent.com/55310192/219379074-1e844db4-b55e-410c-b4d2-27061ac86604.png)

**Comment by lightwood** [comment]
> And so i literally run both versions in the same browser in different tabs, and the one exported from r317 works prefectly, while the other one exported from r327 fails every time, both in chrome and edge. Both versions work on Firefox though

I now have this exact behaviour reported by 4 end users so far (regular user base of about 50, and I run our app alongside live audio, so I'm in close contact with users). Worked in Chrome and Edge when built with r317, but fails this way with r327 (but still works in Firefox). We've actually pinpointed r321 as the version that broke things for them.

All affected users report "WebGL2: Unavailable" in chrome://gpu (which is why I assumed that was the problem when I opened this bug, although that may be erroneous). Are you the same?

**Comment by nerdError** [comment]
> > And so i literally run both versions in the same browser in different tabs, and the one exported from r317 works prefectly, while the other one exported from r327 fails every time, both in chrome and edge. Both versions work on Firefox though
> 
> I now have this exact behaviour reported by 4 end users so far (regular user base of about 50, and I run our app alongside live audio, so I'm in close contact with users). Worked in Chrome and Edge when built with r317, but fails this way with r327 (but still works in Firefox). We've actually pinpointed r321 as the version that broke things for them.
> 
> All affected users report "WebGL2: Unavailable" in chrome://gpu (which is why I assumed that was the problem when I opened this bug, although that may be erroneous). Are you the same?

Yes, my laptop doesnt support WebGL2 either. And again, everything worked fine before with WebGL1 until r327 (or probably until r321 as you mentioned, didn't check that version specifically)

**Comment by AshleyScirra** [comment]
I'm afraid this does sound a lot like graphics driver bugs. Unfortunately it's often infeasible to work around this. The problem is with a system-level component on the device, not Construct.

We have stats on the WebGL support for Construct editor, which uses exactly the same renderer as the runtime. Based on that we see 99.7% of devices support WebGL in some form (and 95.5% support WebGL 2). This is similar to the numbers we saw for r317 as well. So based on this I'd say that some innocuous (and as far as I'm aware, entirely correct) changes to Construct's rendering code have started causing a different combination of buggy GPU drivers to stop working. I'm afraid there's little we can do about that, just as there was little we could do about the 0.3% of devices not supported in r317. All I can suggest is installing any available system software updates, or try updating the graphics driver.

I'd add that graphics driver bugs have long been an industry-wide problem, and things like this have kept coming up through my career right from Construct Classic in 2007, through Construct 2 in 2011+, and now in Construct 3 as well. Broken graphics drivers are even responsible for major launch difficulties for commercial game titles. It's the way it's been for a long time and unfortunately there's not much anyone can do about it outside of the GPU vendors themselves.

**Comment by lightwood** [comment]
I'm still trying to set up an environment so I can reproduce this and provide more information. I've not found any way to disable WebGL2 without also disabling WebGL1, so I can't force (what I think is) the same situation. Indeed, when Chrome has no hardware acceleration at all, it appears to fall back to software rendering successfully. Do you by any chance know if I can disable WebGL2 in a browser without disabling WebGL1?

I agree that there will always be a small number of users who can't be supported, but (if lack of WebGL2 support is indeed the problem) 4.5% is fifteen times as significant as 0.3% and I would argue that 1 in 22 is no longer a "very small number of devices" that are incompatible for anyone wishing to deploy an application.

My headache is that these users were happily using my software until that update and now they feel like I've taken it away from them - they can't understand why; nor should they need to. Nobody likes being told they've chosen the wrong computer, and it's a particularly hard pill to swallow when everything worked just fine, they changed nothing, I updated the app... now it just doesn't work.

This is a different situation to dropping support for known older systems (e.g. no longer works on iOS 12 or lower), but that's not the case here. It's more a random finger of fate kind of situation.

For those happy to engage with the developer, we have Firefox as a workaround at least - but others will just get frustrated and give up.

If you're happy with 95.5% being the new number of devices supported, then I guess I will go no further. It would be preferable, of course, if the user saw a "Sorry, your browser is incompatible message - try Firefox" instead of a nondescript black screen, and then needing tech support from the developer for a now-common issue. Is that possible in the code that attempts to launch the engine?

But if you'd like me to continue digging, I will see if I can attempt to remote-control one of the affected machines and find something more concrete about where it falls over.

**Comment by AshleyScirra** [comment]
Our numbers show 99.7% of devices are supported, not just 95.5%.

I would advise to try installing any available system software updates or updating the graphics driver on any affected devices. That may be sufficient to solve the problem.

I doubt you can reproduce the problem on a system where WebGL works. That means the graphics driver is working.

The runtime does already check WebGL is supported and shows a "sorry, your browser is incompatible" if it is unable to use WebGL. However it is possible for devices with broken graphics drivers to pass that check, and then fail the next time WebGL is accessed. For this reason it is difficult to even properly detect this situation.

**Comment by nerdError** [comment]
> Our numbers show 99.7% of devices are supported, not just 95.5% (which was the number for WebGL 2 only excluding devices where WebGL 1 is working).
> 
> I would advise to try installing any available system software updates or updating the graphics driver on any affected devices. That may be sufficient to solve the problem.
> 
> I doubt you can reproduce the problem on a system where WebGL works. That means the graphics driver is working. Earlier in this issue I already verified WebGL 1 rendering code is working correctly on my system - because my graphics driver is working, and the problem is caused by broken graphics drivers, not problems in Construct's WebGL code.
> 
> The runtime does already check WebGL is supported and shows a "sorry, your browser is incompatible" if it is unable to use WebGL. However it is possible for devices with broken graphics drivers to pass that check, and then fail the next time WebGL is accessed. For this reason it is difficult to even properly detect this situation.

By the way, I tried to open C3 on the same laptop and now I get this message. So, after r321 I'm unable to work on C3 without webgl2. And I actually used this laptop to work, so a little sad but not that bad I guess.

![image](https://user-images.githubusercontent.com/55310192/219990762-47294910-2a0d-48b6-bb71-47200b931e3e.png)

Also, maybe my information will be helpful to people here, as my laptop doesn't support webgl2 and I don't need to reproduce this

P.S. I'm not sure why C3 thinks I have windows NT 8, I definitely have windows 10, not the last version though

<details><summary>C3 platform info</summary>
Platform information
Product: Construct 3 r327.2 (stable)
Browser: Chrome 110.0.5481.104
Browser engine: Chromium
Context: webapp
Operating system: Windows NT 8.0.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 276 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Failed to create WebGL renderer. Layout views cannot be opened.
WebGL information
Failed to create WebGL renderer. Try installing any available software updates.

Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

[chrome gpu info.txt](https://github.com/Scirra/Construct-3-bugs/files/10778727/chrome.gpu.info.txt)

**Comment by AshleyScirra** [comment]
To emphasise, Construct does still support WebGL 1 and I've verified it is still working. The problem is broken graphics drivers, not WebGL 1. The devices which tend to have broken graphics drivers are usually older, and so correlate with only supporting WebGL 1, but correlation is not causation.

**Comment by lightwood** [comment]
Can you explain how you have verified that WebGL1 is working by adjusting the exported code please?

Here's what I've tried, which suggests it is not. What's wrong with this logic?

In c3runtime.js, in a project built using r327, I changed each occurrence of this condition so that the check for WebGL2 support will fail:

`if(2<=this.GetWebGLVersionNumber())`
to
`if(99<=this.GetWebGLVersionNumber()`

This causes the "failed to acquire a renderer" error, as reported above, on my otherwise-working web browser.
(Example: https://www.uketok.com/Test/Test327/)

However, in the same project built using r317, I changed the corresponding condition:

`webglVersion>=2`
to
`webglVersion>=99`

And the project still runs correctly - presumably now falling back to WebGL1?
(Example: https://www.uketok.com/Test/Test317/)

**Comment by AshleyScirra** [comment]
If you just make some random change to the exported code without understanding what you're doing, all you are likely to do is break it. I suspect the code modification you made is invalid and that is why it got broken.

**Comment by lightwood** [comment]
So, you're not going to tell me what's wrong with this logic - just pooh pooh it?

I understand that speculation and passing the blame is much easier than actual problem-solving, but come on... are we really just left with a combination of "works for me" and "la-la-la not listening" for this one?
