### ISSUE TITLE
3d audio not working

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6436]
## Problem description

3d audio does not seem to work, or maybe I am misunderstanding how to use it.

## Attach a .c3p
[3dAudioTest.zip](https://github.com/Scirra/Construct-3-bugs/files/10527846/3dAudioTest.zip)

## Steps to reproduce

1. start preview
2. rotate the camera

## Observed result

audio position doesn't change, swush keeps playing on the left speaker even when rotating the camera 180 degrees.

## Expected result

Audio position does change relative to the camera.

## More details

Maybe it's an error in my implementation. If so, I would love some clarification on how to use it in the documentation.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The problem is the *Rotate camera* action does not change the forward vector (which you can see in the debugger). This is currently by design as the rotation is a secondary transform after setting the base camera orientation. However it's easy to work around: instead of using `3DCamera.ForwardX/Y/Z` for the listener forward orientation, use `3DCamera.LookX/Y/Z - 3DCamera.CameraX/Y/Z`. This does seem a bit of a gotcha so I added a note to the Audio manual entry about this.

**Comment by NickR-Git** [comment]
Thanks for adding the note in the docs, but the way you've worded it here is much clearer than the note you've left there - the explanation provides important context.

**Comment by F3der1co** [comment]
> The problem is the _Rotate camera_ action does not change the forward vector (which you can see in the debugger). This is currently by design as the rotation is a secondary transform after setting the base camera orientation. However it's easy to work around: instead of using `3DCamera.ForwardX/Y/Z` for the listener forward orientation, use `3DCamera.LookX/Y/Z - 3DCamera.CameraX/Y/Z`. This does seem a bit of a gotcha so I added a note to the Audio manual entry about this.

I now have another problem with billboard math that Rojo made, it works perfectly, but once I use the rotate camera action it completely breaks. 
I would greatly prefer if the rotate camera would update the 3dCamera vectors/values. As currently it's a huge pain as you have to use different formulas if you are using the rotate camera action.

**Comment by F3der1co** [comment]
@AshleyScirra 
![image](https://user-images.githubusercontent.com/89512047/226147249-b7bb6df0-216a-4b3c-b748-5d3bc4a154ae.png)
could we maybe get access to the camera matrix, as R0J0hound asks here?
