### ISSUE TITLE
custom action icon too small and incorrect color in dark theme

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6440]
## Problem description

The custom action icon is too small and has the wrong color in the dark theme.

![iconCustomAction](https://user-images.githubusercontent.com/89512047/215786392-901da362-253e-45b1-a0d3-3848b7b73825.png)

**Comment by F3der1co** [comment]
I see it is also black with family custom action, but there the small placement in the bottom right-corner makes more sense.

**Comment by AshleyScirra** [comment]
I think we need a new icon design to make sure it works well on any color background/theme, especially as solid black doesn't work over a dark object icon. I'll talk to our designer and see if we can come up with something.

**Comment by AshleyScirra** [comment]
The icon design has been updated for the next beta, including a theme-controllable icon color, which is set to a lighter color for the dark theme.
