### ISSUE TITLE
Copy to buffer animation editor crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6441]
## Problem description

When I copy an image in the image editor it crashes.

## Attach a .c3p

Save open project: [New project.zip](https://github.com/WilsonPercival/WilsonPercival/files/10547384/New.project.zip)

## Steps to reproduce

1. Create a new project.
2. Add a sprite.
3. Select the entire image.
4. Press `CTRL+C`.

## Observed result

https://user-images.githubusercontent.com/91274932/215790315-9946a6e0-74e7-41b8-8c6c-afd160ee01f2.mp4

## Expected result

Construct does not crash.

## More details

Error report information

Type: unhandled rejection
Reason: Error: DOMString not supported for 'image/png' as image data.
Construct version: r328
URL: https://editor.construct.net/r328/
Date: Tue Jan 31 2023 16:32:11 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 27.2 s
Platform information

Product: Construct 3 r328 (beta)
Browser: Firefox 109.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Affected browsers/platforms:** Mozilla

**First affected release:** broke in r328b

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r328 (beta)
Browser: Firefox 109.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
Language setting: en-US
Local storage

Storage quota (approx): 9.8 gb
Storage usage (approx): 75 mb (0.7%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This is crashing in Firefox because the setting **dom.events.asyncClipboard.clipboardItem** is set to **true**. Firefox disables it by default because the feature is experimental. We don't support features that haven't been fully shipped by the browser vendor.

In the default case of the setting being disabled, C3 falls back to saving to a fake clipboard, which only works within itself (can't paste into external applications)

**Comment by WilsonPercival** [comment]
> This is crashing in Firefox because the setting **dom.events.asyncClipboard.clipboardItem** is set to **true**. Firefox disables it by default because the feature is experimental. We don't support features that haven't been fully shipped by the browser vendor.
> 
> In the default case of the setting being disabled, C3 falls back to saving to a fake clipboard, which only works within itself (can't paste into external applications)

@DiegoScirra But I think it's worth `false` here.

![aa](https://user-images.githubusercontent.com/91274932/215850176-6d5ed5e1-118d-480b-9c72-7c6c78cccad4.png)

**Comment by WilsonPercival** [comment]
> This is crashing in Firefox because the setting **dom.events.asyncClipboard.clipboardItem** is set to **true**. Firefox disables it by default because the feature is experimental. We don't support features that haven't been fully shipped by the browser vendor.
> 
> In the default case of the setting being disabled, C3 falls back to saving to a fake clipboard, which only works within itself (can't paste into external applications)

@DiegoScirra But I think it's worth `false` here.

![aa](https://user-images.githubusercontent.com/91274932/215850686-e14172c7-3ee8-497e-976f-3b95877eb3df.png)
