### ISSUE TITLE
dialog window jumping

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6442]
## Problem description
it seems like the dialog opens in the previous and then moves to the current position after half a second.

![ezgif com-gif-maker (40)](https://user-images.githubusercontent.com/89512047/215792814-34cde083-e3fd-4230-ba2a-83d3330d9ec4.gif)

## Attach a .c3p

not project specific

## Steps to reproduce

1. create a new project
2. select create a new action
3. move the dialog box
4. press next

## Observed result
dialog opens at incorrect position and jumps to correct position
## Expected result
dialog opens at the correct position.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
