### ISSUE TITLE
Persist hierarchy go to layout bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6445]
## Problem description

After switching layouts, if the parent has the `Persist` behavior, the hierarchy detaches the parent and child.

## Attach a .c3p

[persist_hierarchy_go_to_layout_bug_r328b.zip](https://github.com/WilsonPercival/WilsonPercival/files/10549671/persist_hierarchy_go_to_layout_bug_r328b.zip)

## Steps to reproduce

1. Open and run the project.

## Observed result

The hierarchy is detached and the parent spins without the child.

## Expected result

The parent rotates with the child.

## More details

**Affected browsers/platforms:** Mozilla

**First affected release:** broke in r328b

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r328 (beta)
Browser: Firefox 109.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
Language setting: en-US
Local storage

Storage quota (approx): 9.8 gb
Storage usage (approx): 75 mb (0.7%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This one is tricky because fixing it could very well break existing projects relying on the existing behaviour.

The loading process handles the cases of **NONE** of the instances in a hierarchy being persisted and **ALL** the instances in a hierarchy being persisted. In both cases the structures are recreated properly.

In the example only the parent has the persist behaviour... should I make all children of a persisted instance to be implicitly persisted as well? That will fix this problem, but it changes the current behaviour dramatically.

@AshleyScirra what do you think?

**Comment by AshleyScirra** [comment]
It does seem odd to have the persist behavior on some, but not all, objects in a hierarchy. It's hard to know what Construct ought to do in this case as returning the layout means reconciling the initial objects with a hierarchy with the persisted state including only the parent object and no child. I think it's reasonable that Construct responds to this by restoring only the parent with the persist behavior, and ignores the child as there is no persist data for it. Therefore I don't think any change is warranted here.
