### ISSUE TITLE
[r46] Editor crash on Effect rename

### ISSUE THREAD

**Issue by wiverson** [Scirra/Construct-3-bugs#645]
## Problem description

Renaming an Effect on a Layer causes a crash.

## Attach a .c3p

Repro steps are so simple I don't think you need a .c3p, let me know if you want me to submit something.

## Steps to reproduce

1. Create new empty project
2. Add Effect Tint to the Layer 0
3. Rename the Tint to TintX
4. Get the error message below with a standard Construct 3 crash dialog.

## Observed result

Unhandled rejection!  (Very bad for my fragile ego).

## Expected result

The Tint effect to be renamed

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: this.ǃt$I.ǃtRt is not a function @ TypeError: this.ǃt$I.ǃtRt is not a function at window.ǃOD.ǃbS (https://editor.construct.net/r46/main.js:61:136595) at n.ǃbu.then (https://editor.construct.net/r46/main.js:149:39709) at 
Stack: TypeError: this.ǃt$I.ǃtRt is not a function at window.ǃOD.ǃbS (https://editor.construct.net/r46/main.js:61:136595) at n.ǃbu.then (https://editor.construct.net/r46/main.js:149:39709) at 
Construct 3 version: r46
URL: https://editor.construct.net/
Date: Tue Jul 25 2017 15:10:35 GMT-0700 (PDT)
Uptime: 222.8 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r46

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M290X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by shortercode** [comment]
Should be fixed in r47, the issue exists for any non-objects. So also breaks in layouts etc.
