### ISSUE TITLE
Cannot move events keyboard bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6451]
## Problem description

I already reported a similar bug https://github.com/Scirra/Construct-3-bugs/issues/5433

## Attach a .c3p

[cannot_move_events_keyboard_bug_r328b.zip](https://github.com/WilsonPercival/WilsonPercival/files/10556998/cannot_move_events_keyboard_bug_r328b.zip)

## Steps to reproduce

1. Create a new project.
2. Add a sprite.
3. Add a keyboard.
4. Add a private variable to the sprite.
5. Create a new event - on button click.
6. Create a new condition - if the instance variable is equal to the empty string.
7. Put the button click event as a sub-event under the instance variable.
8. Create a new function.
9. Duplicate the first two events.
10. Remove the keypress sub-event.
11. Move the instance variable event below the function.

## Observed result

https://user-images.githubusercontent.com/91274932/216043982-75a9653c-d82a-4e46-864d-d0b294c85924.mp4

## Expected result

I can move events.

## More details

**Affected browsers/platforms:** Mozilla

**First affected release:** broke in r328b

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r328 (beta)
Browser: Firefox 109.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
Language setting: en-US
Local storage

Storage quota (approx): 9.8 gb
Storage usage (approx): 75 mb (0.7%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by GeekManOfficial** [comment]
https://user-images.githubusercontent.com/95054989/216056447-b02be335-aa91-4cb2-82c0-4200c568824b.mp4

i can repeat it

**Comment by AshleyScirra** [comment]
BTW please don't explain how you made the project in bug reports - it just makes it longer and more complicated to deal with. Your steps to reproduce (and a video if you provide one) can start with opening the project, e.g.:

1. Open project
2. Copy and paste event 1
3. Delete the triggered subevent
4. Drag as sub-event of the function

This is more concise and clearer. Explaining or recording everything you did to create the project is pointless, because I start by opening the project, not by creating a new project.

**Comment by WilsonPercival** [comment]
> BTW please don't explain how you made the project in bug reports - it just makes it longer and more complicated to deal with. Your steps to reproduce (and a video if you provide one) can start with opening the project, e.g.:
> 
> 1. Open project
> 2. Copy and paste event 1
> 3. Delete the triggered subevent
> 4. Drag as sub-event of the function
> 
> This is more concise and clearer. Explaining or recording everything you did to create the project is pointless, because I start by opening the project, not by creating a new project.
> 
> Anyway I can reproduce this so will investigate.

@AshleyScirra OK, thanks)

**Comment by AshleyScirra** [comment]
I believe this is a variant of the same issue that causes #5433, so marking duplicate.
