### ISSUE TITLE
Wait this is canvas fantasy bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6453]
## Problem description

The canvas won't paste if I wait a second after running the layout. Everything works fine if I remove the first wait action.

## Attach a .c3p

[wait_this_is_canvas_fantasy_bug_r328b.zip](https://github.com/WilsonPercival/WilsonPercival/files/10560691/wait_this_is_canvas_fantasy_bug_r328b.zip)

## Steps to reproduce

1. Open and run the project.

## Observed result

![observed](https://user-images.githubusercontent.com/91274932/216138232-b54bfdeb-26de-4bd3-8a34-5dd74bd5fd1b.png)

## Expected result

![expected](https://user-images.githubusercontent.com/91274932/216138257-a3e2214b-c602-459a-bc66-c0b274409df8.png)

## More details

**Affected browsers/platforms:** Mozilla

**First affected release:** broke in r328b

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r328 (beta)
Browser: Firefox 109.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
Language setting: en-US
Local storage

Storage quota (approx): 9.8 gb
Storage usage (approx): 75 mb (0.7%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is not a bug. What is happening is Layout 1 is creating and pasting Sprite at the same time, but Sprite does not exist on Layout 1, only Layout 2. Construct's memory management means that Sprite's images are not loaded on Layout 1. Therefore when Sprite is created, it loads its images dynamically, but that is asynchronous, so takes a moment to complete. The paste is done before the images are loaded and so it cannot draw the image yet.

There are two possible workarounds:
1) Put a Sprite instance on Layout 1. Then Construct loads its images when starting the layout.
2) Use the system 'Load object images' action to load the Sprite images, and 'Wait for previous actions to complete', before creating the sprite and pasting it.

**Comment by WilsonPercival** [comment]
> This is not a bug. What is happening is Layout 1 is creating and pasting Sprite at the same time, but Sprite does not exist on Layout 1, only Layout 2. Construct's memory management means that Sprite's images are not loaded on Layout 1. Therefore when Sprite is created, it loads its images dynamically, but that is asynchronous, so takes a moment to complete. The paste is done before the images are loaded and so it cannot draw the image yet.
> 
> There are two possible workarounds:
> 
> 1. Put a Sprite instance on Layout 1. Then Construct loads its images when starting the layout.
> 2. Use the system 'Load object images' action to load the Sprite images, and 'Wait for previous actions to complete', before creating the sprite and pasting it.

@AshleyScirra Oh right! Thanks a lot!
