### ISSUE TITLE
Wrong V4 icons when V26 Adaptive icons are used to build the APK

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-3-bugs#6454]
## Problem description

If I use "Adaptive foreground" and "Adaptive background" icons together with the default C3 icons, the android 7.0 device shows the adaptive foreground icon instead of the default "App icon"
As far as I understood, when both standard "App icon" and "Adaptive icons" coexist in the same building, legacy devices (in this case Android 7 device) will pick up the standard "App icon" and API26 or higher will use the adaptive versions.

In the provided example the android 7 device uses the adaptive foreground.
This is the Android 7 icon:
![android 7 icon](https://user-images.githubusercontent.com/58107632/216151739-4114835a-94a5-43ed-bc89-bf15e0499b32.png)

This is the Android 8 icon (This is correct because it assembles the background and foreground icons):
![android 8 icon](https://user-images.githubusercontent.com/58107632/216151850-cac955a8-8d15-4ea2-a4e0-0a0186f66fae.png)

On android 7 I should expect (this is the redesigned default icon):
![2mjuZpHqz7](https://user-images.githubusercontent.com/58107632/216152966-e1882679-7fd1-48cc-8ac7-520a302d7ee1.png)

Actually, if you take a look into the "res" folder of the APK and have a look at the v4 folders there isn't the default expected icon but the Adaptive one.

## Attach a .c3p
[icon bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10561236/icon.bug.c3p.zip)
[android icon bug.android.debug.apk.zip](https://github.com/Scirra/Construct-3-bugs/files/10561237/android.icon.bug.android.debug.apk.zip)
please remove ".zip" extension.

This is the cordova export:
[android icon bug cordova.zip](https://github.com/Scirra/Construct-3-bugs/files/10566174/android.icon.bug.cordova.zip)

## Steps to reproduce

1. install di APK into an Android 7.0 or older device
2. remove all fore and back icons and rebuild the APK
3. reinstall the APK into the same previous device.

## More details

Using the R238 version but I think the problem exist in the previous version as well.
Tested with Chrome only.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by fredriksthlm** [comment]
This should be fixed, since I reported it. https://github.com/Scirra/Construct-3-bugs/issues/4689

But you should verify your icon sizes

You can verify how the xml file look like if you export as a cordova proj.

**Comment by rraffo** [comment]
I have also uploaded the cordova export.
This is the XML file content:
![vtDVIws6dL](https://user-images.githubusercontent.com/58107632/216258509-2eca14b3-4cca-4ec3-b2ff-215f11e0adc5.png)

**Comment by rraffo** [comment]
@fredriksthlm you are very kind to help me with this.
As far as I understood the fallback must have the same resolution as the adaptive icon and for each adapting icon size there must be its corresponding fallback size. Is my reasoning correct?

**Comment by fredriksthlm** [comment]
In Constructs they must be the same size, otherwise they will not be part of the exported xml. If your icon has the same design for all dpis you will also only need _one_ size.

**Comment by rraffo** [comment]
Do you mean that if I specify the xxxhdpi (108dp, 432px) size only, C3 will automatically use this size to create the smaller version too?

**Comment by fredriksthlm** [comment]
> C3 will automatically use this size to create the smaller version too

No. But the actual devices will scale the icon down. So if they look identical you do not need more.
Otherwise, if you want more sizes, then you must provide the same resolution for them in Construct.
If you ever see any issue, you should verify your xml.

There is no bug here.

**Comment by rraffo** [comment]
Thanks!
I do appreciate your help.
