### ISSUE TITLE
Parameters for MoveTo: Set enabled should be a combo option 

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6455]
## Problem description

To keep C3 design consistent, `Parameters for MoveTo: Set enabled` should be a combo option.

> BTW ideas: all 'Set enabled' action should be support 'Toggle' state

## Attach a .c3p

https://editor.construct.net/#open=move-along-path

## Observed result

- Set Enable
- Set stop on solids

![Snipaste_2023-02-02_14-09-03](https://user-images.githubusercontent.com/45864744/216245634-176df63d-a42f-4bec-a45d-cc2f06638bcb.png)

## Expected result

![Snipaste_2023-02-02_14-09-28](https://user-images.githubusercontent.com/45864744/216246184-b0062acf-a155-410f-89c8-d22cfbd440e3.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Actually, the checkbox is the new modern design that all boolean parameters are supposed to use. However many parameters pre-date the implementation of the checkbox parameter and so still use a combo. For backwards compatibility reasons it's tricky to replace them, so they're left as-is for now.
