### ISSUE TITLE
List not showing tabs (\t) correctly

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6457]
## Problem description

My project tries to use the list to present a table. The List shows the Tab (\t) in an inconsistent way that differ between editor, properties, events, and debugger.
In the editor: The tab is shown as small space.
In the properties: It is shown as "\t". I have to type it in the properties box "\t", otherwise if I use the Items editor, it doesn't accept tabs (or Shift+tab), but if you have "\t" in the properties box, it will be shown correctly in the item editor.
In the events: If I set the item text to "A\tB" it is considered "A\\tB"; i.e. the tab is ignored.
In the debugger: When checking the list's contents, tabs are ignored, unless you double click the item in the debugger, then it shows the real tabs.
In the preview: Tabs are just spaces, even if the debugger (after double clicking the item) shows them as real tabs.

## Attach a .c3p
[ListTabs.zip](https://github.com/Scirra/Construct-3-bugs/files/10567358/ListTabs.zip)

## Steps to reproduce

Check how the tab is presented in the following: 
1. Properties window
2. Items editor
3. Events
4. Preview
5. Debugger

## Observed result
Tabs are inconsistent, and not showing correctly in the list.
![Untitled](https://user-images.githubusercontent.com/12113416/216286586-d9c8f84c-ed6f-45e7-a4ac-f8fb74c65fe4.png)

## Expected result

The tabs should show correctly in preview, at least.

**Comment by AshleyScirra** [comment]
This is all actually working as designed - tabs are a bit of a weird whitespace character. In general browsers collapse all whitespace. So in HTML if you have `<p>Hello           world</p>`, that renders as "Hello world", no matter how many spaces (or even tabs) are in between the words. That is why in several places it appears as if the tab is a space.

In the Properties Bar you can use escape sequences like `\n` and `\t`. However these escape sequences are not used in expressions. So an expression string of `A\tB` means literally what you typed. There isn't currently an easy way to enter a tab in to an expression string, but you can copy and paste a tab character in, but it doesn't help as HTML still collapses the space.

Construct's debugger actually works the same as Chrome's dev tools where editing the item shows the text with whitespace preserved, but after editing shows it with whitespace collapsing.

I don't think there warrants any change to Construct here, and I'd say it's appropriate to use tabs to try to display a table anyway. If you want to display information in a table format, [using a real HTML table](https://editor.construct.net/#open=html-table) is most likely a better option.
