### ISSUE TITLE
Can I downgrade to a earlier release, to get it to work ?

### ISSUE THREAD

**Issue by christian1966** [Scirra/Construct-3-bugs#6458]
Can I downgrade to a earlier release, to get it to work ?

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by XHXIAIEIN** [comment]
This is submit bug report. you can post questions in forum
https://www.construct.net/en/forum/construct-3/how-do-i-8
