### ISSUE TITLE
Layer with <100% Opacity appears as if it has modified SCROLL AND ZOOM

### ISSUE THREAD

**Issue by StefanSava** [Scirra/Construct-3-bugs#646]
## Problem description

If i reduce the opacity of a layer it starts showing as if it has modified Parallax and Zoom (they are all at 100%)

## Steps to reproduce

1.add some objects to a layer
2.change opacity of layer from 100%

## Observed result

Objects become zoomed in and miss-positioned (only in editor view). 'Parallax in editor' checkbox has no effect.

## Expected result

Objects would just change opacity.

## Affected browsers

* Chrome: yes/no

**Comment by shortercode** [comment]
I can't get this to replicate, but this is definitely Ash's area so going to assign to him to have a look in. I expect it's something to do with opacity adjustments requiring a layer to use it's own texture.

**Comment by AshleyScirra** [comment]
Since you didn't provide a full report, I just opened Ghost Shooter, changed a layer opacity, and everything appeared correctly. Closing.
