### ISSUE TITLE
Clone Object Type causes 'Template' property to remain

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6460]
## Attach a .c3p

[clone-template-property.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10607818/clone-template-property.c3p.zip)

## Steps to reproduce
1. `Clone` in the Object types
2. Drag Sprite 2 onto the Layout create an instance
3. Look at the Template property of sprite 2

![Snipaste_2023-02-04_13-43-59](https://user-images.githubusercontent.com/45864744/216751369-30e1e894-82ce-40fb-a67f-c2d77f1eba00.png)

## Observed result

Sprite 2
![Snipaste_2023-02-04_13-45-13](https://user-images.githubusercontent.com/45864744/216751388-9d995b30-aa9b-4469-bd88-ca5dd5ea728b.png)

## Expected result

![Snipaste_2023-02-04_13-45-38](https://user-images.githubusercontent.com/45864744/216751375-d3a13019-b288-42a1-b340-b86c53acb734.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r328 (beta)
Browser: Chrome 110.0.5481.77
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 158 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Wackytoaster** [comment]
As of r329 this appears to crash the project IF the sprite in question has had a hierarchy attached at some point.

1. Create spriteA
2. Set to template (give a name, might not be needed)
3. Create spriteB and put it as a child of spriteA
4. Delete spriteB
5. Clone SpriteA
6. Drag cloned object into layout

[crashy.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10678175/crashy.c3p.zip)


<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r329/components/bars/propertiesBar/propertiesBar.js, line 94, col 212
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'Tb')
Stack: TypeError: Cannot read properties of undefined (reading 'Tb') at $V (https://editor.construct.net/r329/components/bars/propertiesBar/propertiesBar.js:94:212) at ofb (https://editor.construct.net/r329/components/bars/propertiesBar/propertiesBar.js:39:231) at CCG.aa.XS (https://editor.construct.net/r329/components/bars/propertiesBar/propertiesBar.js:142:179) at d.EWb (https://editor.construct.net/r329/components/bars/propertiesBar/propertiesBar.js:114:40) at d.WBc (https://editor.construct.net/r329/components/bars/propertiesBar/propertiesBar.js:114:6) at Array. (https://editor.construct.net/r329/components/bars/propertiesBar/propertiesBar.js:102:142) at window.ceb.dispatchEvent (https://editor.construct.net/r329/main.js:1234:42) at CR (https://editor.construct.net/r329/components/editors/layoutView/layoutView.js:1:394) at ibb.vo (https://editor.construct.net/r329/components/editors/layoutView/layoutView.js:210:205) at window.Gl.nQb (https://editor.construct.net/r329/components/editors/layoutView/layoutView.js:121:23)
Construct version: r329
URL: https://editor.construct.net/r329/
Date: Tue Feb 07 2023 19:10:40 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 48.7 s

Platform information
Product: Construct 3 r329 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
