### ISSUE TITLE
Advanced Minification Broken in r328?

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#6463]
## Problem description

Exporting with advanced minification on r328 seems to result in a failure to pass minifying script.
Attempting to perform advanced minification on previous builds also seems much slower than I recall.

## Attach a .c3p

Any blank project with advanced minification (I've tried nwjs, html, windows web view, construct arcade, all the same issue)

## Steps to reproduce

Export -> Advanced Minification

## Observed result

Stuck at Minfifying script (stopped waiting ~60 minutes in on a blank project, and 5+ hours on my main project)

## Expected result

Reach the zip file access as is usual when exporting.

## More details

**Affected browsers/platforms:** Chrome/Firefox

**First affected release:** r328

*(then tried on r327 and r320, for 327 and 320 it eventually works but seems slower than usual)

## System details

Platform information
Product: Construct 3 r328 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 572 gb
Storage usage (approx): 6.6 gb (1.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It does take a while but it's working fine for me in r328.

Maybe try clearing your browser and try again? Perhaps it failed to download the minifier last time. We have not made any significant changes to the minifier for some months now.

**Comment by OneRepCloser** [comment]
Much appreciated Ashley,

Based on your advice, this worked for me:

1. Uninstalled the C3 app.
2. Closed all tabs on Chrome.
3. Cleared all browsing history, cached files, and cookies.
4. Re-installed the app
5. Opened project.
6. Export now works
