### ISSUE TITLE
Object templates don't properly set object origins

### ISSUE THREAD

**Issue by pandabear7413** [Scirra/Construct-3-bugs#6465]
It seems like templates don't properly set object origins...

I'm trying to use template to set the origin for Text objects. I created 2 templates of my Text object: leftOriginTemplate and rightOriginTemplate. I then added a new Text object to my layout and its origin was automatically set to left, probably because leftOriginTemplate was the first Text object created on that layout.

I then renamed this new Text object "replica" and made it a replica of rightOriginTemplate. It inherited all the elements of rightOriginTemplate, and shows Origin as 'right' in the Properties bar, but the actual origin is still left. I can manually change the origin in the Properties bar to 'right' (have to change it to something else first, and then back to 'right'), and it will then correctly set the origin to 'right', but if I then make replica a replica of leftOriginTemplate, it doesn't change to origin to 'left' as it should.

![cl](https://user-images.githubusercontent.com/85074714/216983551-b810e8bd-231a-441b-bad8-fdb3135adcce.jpg)
![cr](https://user-images.githubusercontent.com/85074714/216983573-065ebe46-371a-4048-a296-acfffd69a08f.jpg)
![c1](https://user-images.githubusercontent.com/85074714/216983590-93a824ac-a322-4503-949c-f54d8a322e51.jpg)
[originTemplateV1.zip](https://github.com/Scirra/Construct-3-bugs/files/10663498/originTemplateV1.zip)

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
