### ISSUE TITLE
crash building android "Cannot read property 'unshift'" 

### ISSUE THREAD

**Issue by Jau-Al** [Scirra/Construct-3-bugs#647]
## Problem description
Try to export : crash
It's talking about an 'unshift' property it can't read.
I checked : no special characters in media names, no 

## Attach a .c3p

I'm truely sorry but this project contains medias from some people who are really "pernickety" about copy rights lol.

## Steps to reproduce

1.export to android
2.wait for upload
3.click build

## Observed result
crash

## Expected result

build.

I will continue digg by myself cause it's weird. I just added some images, some variables and nothing realy important... I saw a bug ! I removed a global boolean variable and it didn't remove the related rules. I had to remove them. I'll check again (3rd time) but I don't think there is a remnant.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'unshift' of null @ TypeError: Cannot read property 'unshift' of null at ǃxvK.ǃxvF.then (https://editor.construct.net/r46/exporters/cordova/exporter.js:1:5889) at 
Stack: TypeError: Cannot read property 'unshift' of null at ǃxvK.ǃxvF.then (https://editor.construct.net/r46/exporters/cordova/exporter.js:1:5889) at 
Construct 3 version: r46
URL: https://editor.construct.net/index.html
Date: Thu Jul 27 2017 18:54:38 GMT+0200 (CEST)
Uptime: 3719.8 s

Platform information
Browser: Chromium
Browser version: 59.0.3071.109
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/59.0.3071.109 Chrome/59.0.3071.109 Safari/537.36
C3 release: r46

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 1070/PCIe/SSE2
Major performance caveat: no
Maximum texture size: 32768
Point size range: 1 to 189.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Does this always happen when you build this project?

Could you try to export and build the "Space Blaster" example for me?

**Comment by Jau-Al** [comment]
Hello, 
My project can be is exported to nw.js. No problem. But it can't be exported to cordova (android export).
I Tried Pop Lab : no problem with Cordova
Then Space Blaster. It exports fine and the game runs on my phone.

I recently added many photos / sounds in the project. Exported to Android, the archive size is 32.9Mb.
All my media files have names like something-new-1 something-else-2 etc

**Comment by shortercode** [comment]
Okay thanks for testing that for me. I haven't been able to find a way to repeat this, I know where the issue is happening but I'm unable to find out how it happens.

Given that you've confirmed your computer can export this project correctly, and that it has also succeeded to build an APK of a different project I can only conclude something specific about your project is breaking the exporter.

Would you be willing to share the project privately with me so that I can test it?

**Comment by Jau-Al** [comment]
I can't do that today, but I will try to make a copy and remove parts to find what is crashing this week.
I'm sorry, but this is a demo project  which is not exactly a video game. It's showing some "unreleased" artistic content. (copyrights always give you a headache lol).
Thanks anyway. I'll keep you informed.

**Comment by shortercode** [comment]
It's okay, I understand. It'll be easiest to find this if you can come up with another project that also breaks but that you can send my way. 

Happy hunting!

**Comment by Jau-Al** [comment]
I found something. It looks like the images become incredibly heavy (more than 3mb) when converted to png while being exported. I made a copy of the project and tried to replace some of them and it exported.
I saw there was an option to change the export format. There is a crash if I ask for a format change for every image files 
![capture d ecran de 2017-08-03 02-49-34](https://user-images.githubusercontent.com/15030964/28901138-6a258dc2-77f6-11e7-9c64-68c828c31659.png)
then
[crash-select-export-png.txt](https://github.com/Scirra/Construct-3-bugs/files/1195653/crash-select-export-png.txt)

**Comment by Jau-Al** [comment]
I changes the export format to JPEG Q80 for all the largest images. (one frame at a time so C3 doesn't crash). Now it exports to android again :-).

**Comment by shortercode** [comment]
The conversion crash is probably unrelated, but will pass it on to @DiegoScirra to look at.

I have idea what could be causing this. Could you try to export your project as a cordova project, then tell me the size of the zip file and the unzipped project size?

**Comment by shortercode** [comment]
I've created a new bug for the conversion issues here #663 could you subscribe to it in case Diego has any questions please?

**Comment by Jau-Al** [comment]
The overall size was around 40mb instead of 10 with big image files as jpeg

**Comment by shortercode** [comment]
I think I've put a fix in for this crash, which should be available in r48, can you check back when it's released please.

**Comment by AshleyScirra** [comment]
r48 is out now, please check again!

**Comment by Jau-Al** [comment]
Image conversion still crash. Android export stopped crashing after I compressed my intro video a few more and forced jpeg for the large pictures. 
I'll let you know if my project export crashes again.

**Comment by Jau-Al** [comment]
I changed back. All in png. Now It tells me time exceeded. No error report.

**Comment by Jau-Al** [comment]
:-( Ok your time limit is too short. My upload speed is 1Mb/s (which is average in France outside big cities). 
I tried using my phone's 4G connection and this time, it worked just fine.

**Comment by shortercode** [comment]
Well we're making progress, it doesn't crash anymore! I knew the server was cancelling the upload for some reason, and that was causing the client to crash. So I guess the reason is the timeout.

It was giving a maximum upload time of 5 minutes before, I've increased it to 20 minutes now which should be more than enough. It should take about 14 minutes to upload the max upload size of 100MB at 1Mb/s . It's pointless allowing larger files at the moment due to size restrictions on APK files.

I think we can consider this fixed, we'll continue to track the image conversion bug on #663.
