### ISSUE TITLE
Checking for overlap in an OR block breaks logic (somehow)

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#6471]
## Problem description

I have a case where I want to check if a sprite is overlapping another sprite OR if the distance between them is small enough. However, the check for distance does not trigger and only the check for overlap does. If the check for overlap is replaced with something else, the check for distance works as expected.

![image](https://user-images.githubusercontent.com/31101309/217320967-fbbef4ba-98f2-4525-a598-37d4fbc58800.png)

## Attach a .c3p

[ORdistance.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10677853/ORdistance.c3p.zip)

## Steps to reproduce

1. Move mouse near the grey sprite, but not touching them together

## Observed result

The check for distance does not trigger the action. ONLY overlap does trigger the action.

## Expected result

The check for distance to also trigger the action.

## More details
I've included a second group that you can enable where the overlap check is replaced with 1=0, in this case the check for distance triggers normally. So it has something to do with checking for overlap. Also at first I thought it had something to do with picking, that's why I tried to pick nearest first but that wasn't it.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r329 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 4.2 gb (3.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is not a bug, just another case of OR block picking confusion (same as e.g. #5023).

OR blocks are special in that they can run with no instances picked. If "Sprite2 is overlapping Sprite" is not true, then no Sprite2 instances meet the condition. However the event can be made to run anyway by the following system condition. In this case it is correct to run the event with no Sprite2 instances because none met the overlap condition. If it did work, it would mean running actions on instances that did not meet the conditions, which violates the picking rules of event blocks.
