### ISSUE TITLE
Mouse MovementX and MovementY are Significantly Faster in Debug Previews

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#6476]
## Problem description

Mouse movement registers as significantly faster during debug preview vs normal preview. This makes if you use mouse look in your game with 3D way too sensitive to be able to use debug.

## Attach a .c3p

[Mousespeedbug.zip](https://github.com/Scirra/Construct-3-bugs/files/10682076/Mousespeedbug.zip)

## Steps to reproduce

1. Run a normal preview and move the mouse around and take note of the speeds the text object shows.
2. Run a debug preview and move the mouse and it will give significantly higher speeds via the text object.

## Observed result

Debug previews register mouse as significantly faster.

## Expected result

I'm guessing it should be the same for either type of preview.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** I'm using r327.2, but it's been present in dozens of updates before this.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r327.2 (stable)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 139 gb
Storage usage (approx): 137 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon RX 6500 XT Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is not actually a bug. It is that 'On movement' is triggering at different rates. In normal preview mode it triggers very fast (possibly multiple times a frame) with small movement values. However for various reasons (a browser bug workaround IIRC) in debug mode it triggers less often (probably just once a frame) with larger values. In both cases, the movement values add up to the same amount of movement over the same period of time. It's just a question of how often you get updates. For example if in 'On movement' you set the sprite X to `Self.X + Mouse.MovementX` and Y to `Self.Y + Mouse.MovementY`, then the sprite moves at the same speed in both preview and debug. So for the purposes of mouse movement it works out the same.

**Comment by corlenbelspar** [comment]
Huh. Weird. I don't know what to do then to make it visually the same speed, but I guess players won't be able to use debug preview when it's in NW.js so it only affects me as a minor issue that disrupts me debugging, so I guess it doesn't matter then.
