### ISSUE TITLE
A function called from another function with "copy picked=yes" inherits its picked scope

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#6477]
## Problem description

Function A has  "copy picked=Yes" property. 
Function B has  "copy picked=No". 
If I call function B from A, it still inherits the picked scope.

I assume this may be by design, but in this case it needs to be re-evaluated. 
Functions very often call other functions, which call many other functions, which call lots of other functions... This tree of function calls may be huge. If some function along the way has "copy picked=yes" property, this will cause bugs which will be nearly impossible to troubleshoot.

## Attach a .c3p

[CopyPickedBug.zip](https://github.com/Scirra/Construct-3-bugs/files/10683744/CopyPickedBug.zip)

## Steps to reproduce

1. Control the character with arrow keys
2. Summon the boss either by killing (colliding with) three enemies, or collide with the text.

## Observed result

The same function SummonBoss is used in both cases.
But it doesn't work if you collide with enemies, because the wrong picked scope is passed to the function.

## Expected result

SummonBoss function should not inherit the picked scope from another function.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r327.2 (stable)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 272 gb
Storage usage (approx): 1.3 gb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
This is indeed a bug and not the intended design. Thanks for spotting it, should be fixed in the next beta.
