### ISSUE TITLE
Construct3 does not load cloud or disk files.

### ISSUE THREAD

**Issue by Austoio** [Scirra/Construct-3-bugs#648]
## Problem description

*I can not upload any files from my disk or the cloud. I've cleared enough space on my disk. Please help me. This project is already delayed, I am losing much with this situation. Started appearing the message that it lacks space on my disk but I have 20 gb of space.*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Please fill in the rest of the report form, you have given us almost nothing to go on.
