### ISSUE TITLE
Touch inputs being detected as mouse movement

### ISSUE THREAD

**Issue by Lobo93** [Scirra/Construct-3-bugs#6485]
## Problem description

Touch movements (such as touching the screen and then moving your finger) are detected by the game as mouse movement.

## Attach a .c3p

[Touch input.zip](https://github.com/Scirra/Construct-3-bugs/files/10710383/Touch.input.zip)
(Had to upload as .zip because GitHub wouldn't let me upload a .c3p)

## Steps to reproduce

1. Run the project in a mobile device (or a browser window simulating a mobile devide)
2. Touch the screen
3. Move your finger accross the screen

## Observed result

The event "on mouse movement" will trigger and the text will change

## Expected result

The event shouldn't trigger because there wasn't any mouse movement.

I don't know if this behavior is intended, but if it's the case, then consider this a suggestion:
Since the Touch plugin has an option to consider mouse inputs as touch or not, the Mouse plugin should have one as well

## More details

**Affected browsers/platforms:** 

Tested on mobile on a MotoG 5G phone running Android 11 on Chrome 109.0.5414.117
Tested on desktop on Chrome 109.0.5414.120 (64bits) and on Firefox 108.0.2 (64-bits), both simulating touch inputs through the dev console

**First affected release:**

Tested on C3 r329 beta and C3 327.2 stable. Not sure if it happens on older versions

## System details

<details><summary>View details</summary>
Platform information
Product: Construct 3 r329 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 267 gb
Storage usage (approx): 725 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
The project in question has not enabled "Use mouse input" on the Touch object. However it does make use of the Mouse 'On movement' trigger, which [the documentation](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/mouse) does state also uses touch input:

> **On movement**
> Triggered every time the mouse moves, or any touch input moves.

The reason is the 'On movement' trigger was implemented with Pointer Lock and intended for mouse look with 3D camera, and since there isn't an equivalent for the Touch object this provides an easy way to use touch for looking in 3D as well.
