### ISSUE TITLE
crash with ctrl-c , ctrl-v an object in editor

### ISSUE THREAD

**Issue by vtrixdev** [Scirra/Construct-3-bugs#649]
Error report information
Type: unhandled exception
File: https://editor.construct.net/r46/main.js, line 2, col 177199
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Function.ǃt.ǃM (https://editor.construct.net/r46/main.js:2:177205) at c.ǃKO (https://editor.construct.net/r46/components/editors/layoutView/layoutView.js:1:52151) at o.ǃZS (https://editor.construct.net/r46/components/editors/layoutView/layoutView.js:1:59383) at Array.ǃZZ (https://editor.construct.net/r46/components/editors/layoutView/layoutView.js:1:58060) at ǃt.Event.ǃxau.ǃxae (https://editor.construct.net/r46/main.js:2:255304) at window.ǃuG.dispatchEvent (https://editor.construct.net/r46/main.js:2:253957) at window.ǃuG.ǃZS (https://editor.construct.net/r46/components/editors/layoutView/layoutView.js:1:15495) at HTMLDocument.ǃZZ (https://editor.construct.net/r46/components/editors/layoutView/layoutView.js:1:2310) at HTMLDocument. (https://editor.construct.net/r46/main.js:2:250837)
Construct 3 version: r46
URL: https://editor.construct.net/
Date: Fri Jul 28 2017 03:50:24 GMT+0200 (Romance Daylight Time)
Uptime: 162.7 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r46

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by shortercode** [comment]
Please complete as much of the bug report form as you can, without a good replication most bugs are very hard to track down.

**Comment by shortercode** [comment]
Replication:
1. Insert sprite
2. Ctrl + C sprite
3. Ctrl + V
4. Ctrl + drag original sprite

**Comment by shortercode** [comment]
Fixed in r47
