### ISSUE TITLE
Object class not yet added to folder crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6496]
## Problem description

Construct crashes.

To be honest, it is quite difficult to repeat it. I get it once out of twenty.

## Attach a .c3p

save open project: [save_open_project.zip](https://github.com/WilsonPercival/WilsonPercival/files/10714672/save_open_project.zip)

## Steps to reproduce

1. Create a new project.
2. Create a sprite.
3. Add him to the family.
4. Cut out the family.
5. Insert a family.
6. Click on the folder with families.
7. Insert a family.
8. Insert again.
9. Click on a family.
10. Insert a family.
11. Press the `Undo` button until you reach the top of the stack.
12. Press the `Redo` button until you reach the end of the stack.

## Observed result

https://user-images.githubusercontent.com/91274932/218280305-b4680682-7724-4220-93e9-1d1c06e586cd.mp4

I also happened to accidentally repeat it another time in a different way:

https://user-images.githubusercontent.com/91274932/218285409-894dc889-dc21-4e72-8f75-927d69960659.mp4

## Expected result

Construct does not crash.

## More details

Error report information
Type: unhandled rejection
Reason: Error: object class not yet added to folder @ Error: object class not yet added to folder at d.Nc (https://editor.construct.net/r329/projectResources.js:648:71) at window.FS.c2a (https://editor.construct.net/r329/components/bars/projectBar/projectBar.js:100:97) at Array. (https://editor.construct.net/r329/components/bars/projectBar/projectBar.js:86:394) at window.ceb.dispatchEvent (https://editor.construct.net/r329/main.js:1234:42) at Lu (https://editor.construct.net/r329/projectResources.js:45:319) at d.Ih (https://editor.construct.net/r329/projectResources.js:647:390) at d.Ih (https://editor.construct.net/r329/projectResources.js:666:345) at d.wi (https://editor.construct.net/r329/projectResources.js:559:122) at d.wi (https://editor.construct.net/r329/projectResources.js:643:145) at d.wi (https://editor.construct.net/r329/projectResources.js:647:323)
Stack: Error: object class not yet added to folder at d.Nc (https://editor.construct.net/r329/projectResources.js:648:71) at window.FS.c2a (https://editor.construct.net/r329/components/bars/projectBar/projectBar.js:100:97) at Array. (https://editor.construct.net/r329/components/bars/projectBar/projectBar.js:86:394) at window.ceb.dispatchEvent (https://editor.construct.net/r329/main.js:1234:42) at Lu (https://editor.construct.net/r329/projectResources.js:45:319) at d.Ih (https://editor.construct.net/r329/projectResources.js:647:390) at d.Ih (https://editor.construct.net/r329/projectResources.js:666:345) at d.wi (https://editor.construct.net/r329/projectResources.js:559:122) at d.wi (https://editor.construct.net/r329/projectResources.js:643:145) at d.wi (https://editor.construct.net/r329/projectResources.js:647:323)
Construct version: r329
URL: https://editor.construct.net/r329/
Date: Sat Feb 11 2023 22:17:26 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 71.1 s

Platform information
Product: Construct 3 r329 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r329b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r329 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 167 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Merging similar undo issues in to tracking issue #6531.

**Comment by WilsonPercival** [comment]
@AshleyScirra This bug is very hard to reproduce. I'm not even sure if I could play it again in `r329b`. Therefore, I cannot say that I cannot repeat it. But also I can not say that it is fixed.

**Comment by AshleyScirra** [comment]
If it can't reproduced then this issue is not actionable, so marking as completed.

**Comment by WilsonPercival** [comment]
@AshleyScirra I think I figured out how to repeat this mistake. In the window for adding an object, I double-click on the `Insert` button. I can no longer repeat this error in `r331b`.


Uploading observed.mp4…
