### ISSUE TITLE
Can't choose location of save in Google Drive

### ISSUE THREAD

**Issue by LapinChat** [Scirra/Construct-3-bugs#65]
## Problem description

Projects are saved in the root of my Google Drive. I can't save elsewhere. It is needed to choose the location.

## Attach a .c3p

It is not project dependant. It's a software issue.

## Steps to reproduce

1. Make the best game you can. (Or the worse...)
2. Save your creation on Google Drive.
3. Admire the inability you have to choose a saving location.

## Observed result

Can't choose a saving location.

## Expected result

I expect to be able to save where I want/need in my Google Drive account. This is important.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.146
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Chrome OS
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (X11; CrOS x86_64 9202.64.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.146 Safari/537.36

Local storage
Storage quota (approx): 879 mb
Storage usage (approx): 42 mb (4.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 400 (Braswell) 
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
We're intending to implement folder support in the future ( no timeframe at the moment) , which will allow you to choose a specific folder to save into, explore specific folders when opening projects and create new folders.

Unfortunately it's quite a large addition. It involves adding mechanisms to understand folders in our code for google drive, dropbox, onedrive and local browser storage. In addition to updating our file dialog to understand folders.

Dropbox and OneDrive both use "application mode" which gives you a special folder tied to C3. So they offer a more encapsulated alternative if you prefer that? We chose not to use this mode on Google Drive as it's implementation hides the application folder away from the user, preventing any access outside of the application.

Alternatively you can use the google drive website to move the project to your folder of choice. C3 will still be able to find it ( we ask for any files with the .c3p extension ) and when you save it will save to the new location.

**Comment by LapinChat** [comment]
Thanks you. This is useful informations. I didn't know I could move the project file where I wanted in Google Drive.

(Suggestion:) Maybe all this can be added temporally in construct application under a '?' in the 'Cloud Save' dialog. It's good to know.

**Comment by shortercode** [comment]
We may include some additional information for users in the future, but it isn't always easy to find a sensible location to put that information. It's likely that the implementation of the folder structure will come before the notice.

Implementing folders is fairly high up my to do list, but at the moment I'm working on parts external to the editor. So it's down to how quickly I finish those and if I have any other major bugs to fix in the mean time!

**Comment by shortercode** [comment]
Implementation is complete, will be included in r64.
