### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by sjqtentacles** [Scirra/Construct-3-bugs#6500]
## Problem description

Hello I tried to start a new project using 720p portrait mode, made my first sprite and when I pressed the X at the top right part to exit out of the animation editor, construct crashes. This happened in Chrome and Safari on my Macbook.
## Attach a .c3p

It should be a nearly empty project if not an entirely empty one as I was only able to save it during the crash.

[russian tanks.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10715657/russian.tanks.c3p.zip)

## Steps to reproduce

1. start new project 720p portrait mode, either pixel optimized or not, I tried both and crashed both ways
2. create a new sprite
3. close the animation editor
crash!

## Observed result

it crashed with a popup dialog asking to save, saying it might not be possible, and it showed the crash report and this error message stuck out to me:
ResizeObserver loop limit exceeded

## Expected result

Not crash

## More details

**Affected browsers/platforms:** 

Chrome  109.0.5414.119 , Safari 15.4

**First affected release:**

This is my first day with the product 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/, line 0, col 0
Message: ResizeObserver loop limit exceeded
Stack: null
Construct version: r327.2
URL: https://editor.construct.net/
Date: Sun Feb 12 2023 00:41:46 GMT-0800 (Pacific Standard Time)
Uptime: 80.8 s

Platform information
Product: Construct 3 r327.2 (stable)
Browser: Chrome 109.0.5414.119
Browser engine: Chromium
Context: browser
Operating system: macOS 12.3.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by DiegoScirra** [comment]
I am guessing you must have some browser extension installed.

Construct does not use **ResizeObserver** anywhere on it's code, but an extension might.

If you have extensions, try disabling them one at a time while you try to reproduce the problem. You should be able to find out which one is the one causing problems.

**Comment by sjqtentacles** [comment]
Thanks @DiegoScirra ! That fixed the issue :D

**Comment by AshleyScirra** [comment]
@sjqtentacles - out of interest which browser extension caused the problem?

**Comment by sjqtentacles** [comment]
> @sjqtentacles - out of interest which browser extension caused the problem?

@AshleyScirra 

I wasn't able to determine the exact one, but I only have 6 addons - lastpass, ublock origin, javascript on/off switcher, 1pass, google docs offline, djvu viewer, video screenshot tool, and some bullshit I can't remove called AODocs - Smartbar for Google Workspace

The strange part was that the js switcher and ublock didn't seem to be the problem since I already tried to disable them and reload the program.

**Comment by WilsonPercival** [comment]
> @sjqtentacles - out of interest which browser extension caused the problem?

@AshleyScirra https://github.com/Scirra/Construct-3-bugs/issues/6430 This is about LastPass.

**Comment by AshleyScirra** [comment]
I tried installing the LastPass browser extension for Chrome and followed the repro steps, but it did not crash for me.

**Comment by seyacat** [comment]
Lastpass made the mess in my case

**Comment by pguardiario** [comment]
Stupid lastpass extension. I'm moving to nordpass.
