### ISSUE TITLE
3D effect rendering Issue

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6509]
## Problem description

alpha not discarded when using an effect on a sprite.

## Attach a .c3p
[3dEffectRenderingIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/10717631/3dEffectRenderingIssue.zip)

## Steps to reproduce

1. preview project

## Observed result

alpha not discarded, fog exponential is cut out.

## Expected result

alpha discarded

## More details
This is just an example of one effect, but it happens with a wide range of effects.
I would prefer if the alpha would be discarded after the effects, not before.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid I don't believe this is feasible to fix. Construct allows skipping transparent pixels in default rendering mode, as a way to make dealing with transparency easier in 3D. However this only applies to default rendering mode. Effects firstly go through the entire effect compositor depending on the effect sequence, and effects fundamentally work by changing to a different shader for rendering, and the shader they use does not include the skipping transparent pixels logic. It might be possible to force all shader effects developed in Construct to support two variants, but that does not necessarily solve the problem for multi-step effects in the effect compositor, and I don't think is a reasonable thing to require (especially if the same thing happened a few more times we'd end up forcing shader authors to write 4, 8, 16... shader variants). So I'm afraid I think this just amounts to a limitation of Construct's 3D rendering. Remember it's primarily designed as a 2D engine and these kinds of situations involve really difficult 3D rendering circumstances that usually demand a sophisticated true 3D engine to handle.

**Comment by F3der1co** [comment]
I see.
The sad thing about this is: specifically because Construct is a 2D-engine at its core, the main use case that I see is mixing a lot of Sprites with some 3D elements. But Sprites mean transparency and transparency currently means spending a good chunk of dev time on fixing rendering issues. I would argue that doing a game with only 3D assets would be easier in this regard.

Because I am doing research for my next commercial project (2D fighting-game with some 3D environmental assets) Mikal already made a variant of one of his effects for me to solve this issue, and that worked perfectly.
But like you said yourself,  requiring a new version of every effect that updates glFragDepth is suboptimal. This is why I hoped this could be solved at the engine level instead.
I naively though the renderer could do another pass after the effect stack in case the object is in a 3d layer and and has effects to discard the alpha.

Ideally actual semi-transparency woul work but that is a pipe dream I guess  :D

**Comment by AshleyScirra** [comment]
Proper support for transparency in 3D is extremely complicated. AFAIK 3D engines usually do things like a front-to-back pass of opaque content and then a back-to-front pass of semitransparent content. That is already a significantly different rendering architecture. Then it doesn't solve cases like mutually intersecting semitransparent content, because there is no draw order that will appear correct. Construct's effect compositor is also designed for 2D and is fundamentally based on copying rectangles of pixels in screen space. All this stuff is far, far more complicated than it probably looks. This is one of the reasons I'm very reluctant to push Construct much further in to 3D - you just keep on opening new cans of worms like this.
