### ISSUE TITLE
1 second of silence added to converted imported music files.

### ISSUE THREAD

**Issue by daleinen7** [Scirra/Construct-3-bugs#652]
## Problem description

Imported music tracks have 1 second of silence added to them.

## Attach a .c3p

N/A

## Steps to reproduce

1.import audio
2.play audio on loop

## Observed result

A pause in audio before looping.

## Expected result

The loop to be seamess and undetectable.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
I can't reproduce this, as far as I can tell there isn't even a pause when the track loops. Please check your source audio file for a pause at the start/end. If you still think there is an issue then please send us a project or audio file that reproduces this.

**Comment by daleinen7** [comment]
I checked it again and you are completely right. It was my audio editor
adding a second of silence. Sorry about that.

**Comment by shortercode** [comment]
No worries, I'm glad you found the problem.
