### ISSUE TITLE
Whitelist Plugins (Routine Maintenace)

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#6521]
Hi, please whitelist these plugins:

**UPDATES:**
`cordova-plugin-firebase-config@7.0.3`
`cordova-plugin-firebase-crash@7.0.4`
`cordova-plugin-firebase-inappmessaging@7.0.2`

**NEW:**
`cordova-plugin-firebase-performance@1.0.0`
`cordova-plugin-firebase-dynamiclinks@7.0.2`

Thanks

**Comment by AshleyScirra** [comment]
Added all to build service.
