### ISSUE TITLE
AddCordovaResourceFile (Editor API-plugin.js) Error

### ISSUE THREAD

**Issue by SparshaDhar** [Scirra/Construct-3-bugs#6522]
## Problem description
Hi, I need to include a resource file (_GoogleService-Info.plist_) during iOS export using `AddCordovaResourceFile`
The problem arises only if I don't include a `"target"` property. 

According to the Docs, for iOS the _config.xml_ should look like this:
```
<platform name="ios">
    ...
    <resource-file src="GoogleService-Info.plist" />
</platform>
```

And this is my plugin code:
```
this._info.AddCordovaResourceFile(
{
  src: "www/GoogleService-Info.plist",
  platform: "ios"
});
```
After installing and running the plugin, this is the error I get:

<img src="https://user-images.githubusercontent.com/42723600/218657854-d7d44ff4-4de3-402f-a8e4-b874dc7e8a6d.png" width="500"/>

## Attach a .c3addon
[ct_1_0_0_0.zip](https://github.com/Scirra/Construct-3-bugs/files/10729476/ct_1_0_0_0.zip)

## Steps to reproduce

1. Install _ct_1_0_0_0.c3addon_
2. Start Construct 3 editor

## Observed result
<img src="https://user-images.githubusercontent.com/42723600/218657854-d7d44ff4-4de3-402f-a8e4-b874dc7e8a6d.png" width="500"/>

**Comment by AshleyScirra** [comment]
You're right, `target` is meant to be optional but it's actually required. I've fixed that for the next beta, but you should also be able to work around it by just passing an empty string (e.g. `target: ""`) which is what the default value is treated as anyway, so it will work the same.
