### ISSUE TITLE
[SDK] Plugin SDK "dependency"

### ISSUE THREAD

**Issue by Psychokiller1888** [Scirra/Construct-3-bugs#653]
## Problem description

This is a request originally posted on the forums: https://www.scirra.com/forum/viewtopic.php?f=196&t=194463

We need the dependency as it was working for Construct2, in order to include scripts, in my case AirConsole API, to our plugins.

The temp workaround for now is to manually edit the index.html after exporting the project and add the <script> import there.

**Comment by AshleyScirra** [comment]
Added for r48.
