### ISSUE TITLE
Old projects, hierarchy visiblity and opacity automatically enabled

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6530]
When opening projects that use hierarchies in the new beta, visiblity and opacity are automatically enabled.
For backwards compatability I think they should be disabled.

## Attach a .c3p
[hierarchyBool.zip](https://github.com/Scirra/Construct-3-bugs/files/10735081/hierarchyBool.zip)

## Steps to reproduce

1. open the project
2. look at the childs hierarchy properties

## Observed result

opacity and visibility hierarachy checkboxes are set to enabled

## Expected result

they are set to disabled

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
fixed

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta. Was thinking about this during the weekend, but forgot about it.

**Comment by DiegoScirra** [comment]
Yes, that wasn't mentioned here but I changed that aswell.
