### ISSUE TITLE
Audio plugin: Music does not fade out with r330 😊

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#6537]
## Problem description

Audio action "fade" works in r329 but not in r330

## Attach a .c3p

[fadeBroken.zip](https://github.com/Scirra/Construct-3-bugs/files/10738701/fadeBroken.zip)

## Steps to reproduce

Repeat these steps in r329 and then in r330 to hear difference

1. Listen to beautiful song
2. Click button to fade song

## Observed result

r329 = song fades out
r330 = song doesn't change

## Expected result

r329 = song fades out
r330 = song fades out

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DinoSystem** [comment]
Not just music, Fade volume is broken for all sounds

**Comment by alastajj** [comment]
thank you Robert for the additional info!

**Comment by dop2000** [comment]
"Set playback rate" doesn't work either. Both actions throw errors in the console:

![image](https://user-images.githubusercontent.com/36763350/218956761-902914b9-6d88-4e84-a3b1-dfb78b0c7342.png)

**Comment by AshleyScirra** [comment]
Thanks, fixed both 'Fade volume' and 'Set playback rate' actions for the next beta.
