### ISSUE TITLE
Tags seem to be broken and show "undefined" in the debugger

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#6542]
## Problem description

Tags seem to be broken. Playing sounds works, but doing any other action on them does not. When looking at the debugger, it shows that the tag is then attached to "undefined" instead of what I gave it. Note that this happens both when multitags are enabled or not

## Attach a .c3p
[bug_audiotag.zip](https://github.com/Scirra/Construct-3-bugs/files/10745221/bug_audiotag.zip)

## Steps to reproduce

1. Press N to start a sound
2. Press B to try and fade it

## Observed result

The sound does not fade

## Expected result

The sound fades

## More details

**Affected browsers/platforms:** 

**First affected release:** r330

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed the tags not showing correctly in the debugger for the next beta.

The 'Fade volume' action not working was reported in #6537 and should also be fixed for the next beta.
