### ISSUE TITLE
Cras when try open 3d shape object r330

### ISSUE THREAD

**Issue by JonaszO** [Scirra/Construct-3-bugs#6543]
Ashley, take look at vid: https://youtu.be/A8tNga5Dwlc

This happen for each 3D shape obj.

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'Fk') @ TypeError: Cannot read properties of undefined (reading 'Fk') at PEa (https://editor.construct.net/r330/projectResources.js:140:253) at SFa (https://editor.construct.net/r330/projectResources.js:175:182) at Sy.pW.ga (https://editor.construct.net/r330/projectResources.js:2109:131) at yx.g.K.Sb.R (https://editor.construct.net/r330/projectResources.js:1972:232) at https://editor.construct.net/r330/projectResources.js:134:334
Stack: TypeError: Cannot read properties of undefined (reading 'Fk') at PEa (https://editor.construct.net/r330/projectResources.js:140:253) at SFa (https://editor.construct.net/r330/projectResources.js:175:182) at Sy.pW.ga (https://editor.construct.net/r330/projectResources.js:2109:131) at yx.g.K.Sb.R (https://editor.construct.net/r330/projectResources.js:1972:232) at https://editor.construct.net/r330/projectResources.js:134:334
Construct version: r330
URL: https://editor.construct.net/r330/
Date: Wed Feb 15 2023 19:46:57 GMT+0100 (czas środkowoeuropejski standardowy)
Uptime: 51.2 s

Platform information
Product: Construct 3 r330 (beta)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 0.75
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by DiegoScirra** [comment]
Already fixed, was a regression introduced in r330.

**Comment by JonaszO** [comment]
when next relase with fix? 
            
          
     
      
       
        Dnia 15 lutego 2023 20:01 DiegoScirra ***@***.***&gt; napisał(a):
       
    
       
         
 Closed  github.com #6543  as completed.

**Comment by DiegoScirra** [comment]
We usually make releases every Tuesday. Unless something strange happens, this fix should be available next week.
