### ISSUE TITLE
Platform behavior, applying vectorY to objects suspened in air is somehow framerate dependent?

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#6544]
## Problem description

This is tricky to explain, but I have an object with platform behavior suspended in air. On key pressed, I set a -vectorY to it. However, the object reaches quite different heights depending on framerate.

## Attach a .c3p

[whatthe.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10748848/whatthe.c3p.zip)

## Steps to reproduce

1. Preview, press Space (use a 60hz monitor)
2. Note that the rightmost cube doesn't jump as high as the other ones
3. Preview with unlimited frames
4. Now all cubes jump the same height

## Observed result

One cube doesn't reach the height it's supposed to reach.

## Expected result

All cubes to reach the same height regardless of framerate.

## More details
First I wanna mention that the difference between the left cubes and the right cube is that the left ones are on floor. I assume that because of that, for 1 frame, gravity is not applied to them whereas gravity is applied instantly to the right one. This explains the difference between the one in the air and the ones on the floor.

**However, I still believe that this might be a bug, as even with gravity applied instantly, there should not be a such a vast difference between framerates, assuming that deltatime is used inside the behavior. The cubes on the floor also reach the same height regardless of framerate, so why not the one in the air? There is also no noticable difference when doing the same with vectorX, which tells me that gravity is the culprit. My only guess is that vectorY is not just applied instantly, but instead first has gravity applied to it. Perhaps this is applied without deltatime or is applied twice in the same tick?**

In case this is shot down as "not a bug", please provide me a solution & explanation because I have no idea... (and I do believe this to be incorrect behavior)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 110.0.5481.96
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 4.3 gb (3.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Wackytoaster** [comment]
![Screenshot_20230216_114049_Discord](https://user-images.githubusercontent.com/31101309/219343261-cf30b795-d2c2-4e05-b582-cd98b25901c3.jpg)
![image-10](https://user-images.githubusercontent.com/31101309/219343272-a44d153c-853a-4e1c-b8d0-42af76fa8be5.png)

I do think this user has the same problem. This was posted a few days before I ran into the same issue.

**Comment by AshleyScirra** [comment]
I don't believe this is actually a bug. The problem is the sprite on the right only "lands" because of the event that says "if Sprite3 Y > 311, set Sprite3 Y to 311". This is not the same as being on the floor: it means it is actually constantly in free-fall, but held in a fixed place by an event.

Normally the effect of gravity is applied every tick to objects not on the floor. So when the objects on the floor jump, there is no gravity adjustment, and it sets the vectorY according to the jump strength. However when an object in free-fall (but held in place by event logic) adjusts its vectorY, it still applies the effect of gravity the same tick you set vectorY. This means that an object in free-fall but held in place by event logic gets one extra tick of gravity applied to it. This is indeed framerate dependent, but I would argue the flaw is in the event logic that tries to hold an object in free-fall in a fixed place by fixing its position, and then expects it to act the same as objects on the floor that then jump. I don't think that's a reasonable assumption and so I don't think any change to Construct is warranted.

**Comment by Wackytoaster** [comment]
I don't think I expressed myself clear enough. I do **not** expect those to behave the same (even though they almost do), I expect the one in the air to behave consistent across framerates, **which it is not**. Because I do not see how I could prevent that reasonably in eventlogic. I also tried disabling/enabling the behavior as needed to no avail.

So just to be more clear:
The cubes on the floor always reach **exactly the same height +-1px regardless of framerate**.
The cubes in the air reach **different heights in the range of ~15px depending on framerate**.

I have measured this
[measure.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10755947/measure.c3p.zip)

![image](https://user-images.githubusercontent.com/31101309/219363359-4fbc7780-014e-4f88-8043-5fb354034348.png)

On average the cube on the floor reaches a height of 66px at 60fps, and a height of 65.5px at unlimited fps. So the difference at different framerates is <1px
On average the cube in the air reaches a height of 81px at 60fps, and a height of 66px at unlimited fps. So the difference at different framerates is ~15px

I don't care if the cube in the air reaches less height on average because of an extra tick of gravity, the point is it should reach a consistent height overall. And that extra tick of gravity is applied regardless of framerate and uses deltatime I assume, so this shouldn't matter at all.

As I said, I do not see how I could ever reasonably work around this other than silly stuff like "spawn a floor under the thing when applying a vectorY to it so it gets framerate independent" or "add X*dt additional vectorY to compensate for this somehow"

Even your own implementation of the players doublejump mechanic suffers this issue! Tested like so & manually.
![image](https://user-images.githubusercontent.com/31101309/219367296-d5d8cca9-4d20-4d9b-a173-26f66fe046bd.png)

Reaches a height of -55 at 60fps but a height of -70 at unlimited fps. So a difference in heights of, again, ~15px. This one has a little mit more variation at the same framerates but at worst it's about 2px and that's well within the margin of error.

In this case it doesn't even require any events, just the behavior and a stage. I'm very convinced that there's an error somewhere, and I know you hate touching the platform behavior, but please can you look into this again? @AshleyScirra

**Comment by Wackytoaster** [comment]
[noeventrepro.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10756208/noeventrepro.c3p.zip)
A repro with just the behavior and a cliff to jump up. You cannot make that jump at 60fps, but at unlimited fps you make it with room to spare. I'm very well aware that one shouldn't make a game too pixelperfect, but this goes further than pixelperfect. And it happens every time you apply vectorY to an object leading to compounding error.
