### ISSUE TITLE
Unhandled rejection insert object after fixed crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6547]
## Problem description

Construct crashes. I already reported this bug: https://github.com/Scirra/Construct-3-bugs/issues/6523

## Attach a .c3p

save open project: [save_open_project.zip](https://github.com/WilsonPercival/WilsonPercival/files/10755275/save_open_project.zip)

## Steps to reproduce

The same as in the previous report.

## Observed result

https://user-images.githubusercontent.com/91274932/219350460-a96b380a-2c29-4250-8e06-98a2c0a3d8a9.mp4

## Expected result

Construct does not crash.

## More details

Error report information
Type: unhandled rejection
Reason: Error: object class not yet added to folder @ Error: object class not yet added to folder at d.Oc (https://editor.construct.net/r330/projectResources.js:651:71) at window.JS.w2a (https://editor.construct.net/r330/components/bars/projectBar/projectBar.js:100:97) at Array. (https://editor.construct.net/r330/components/bars/projectBar/projectBar.js:86:410) at window.ueb.dispatchEvent (https://editor.construct.net/r330/main.js:1235:42) at Lu (https://editor.construct.net/r330/projectResources.js:45:319) at d.Jh (https://editor.construct.net/r330/projectResources.js:650:390) at d.Jh (https://editor.construct.net/r330/projectResources.js:669:345) at d.wi (https://editor.construct.net/r330/projectResources.js:562:122) at d.wi (https://editor.construct.net/r330/projectResources.js:646:145) at d.wi (https://editor.construct.net/r330/projectResources.js:650:323)
Stack: Error: object class not yet added to folder at d.Oc (https://editor.construct.net/r330/projectResources.js:651:71) at window.JS.w2a (https://editor.construct.net/r330/components/bars/projectBar/projectBar.js:100:97) at Array. (https://editor.construct.net/r330/components/bars/projectBar/projectBar.js:86:410) at window.ueb.dispatchEvent (https://editor.construct.net/r330/main.js:1235:42) at Lu (https://editor.construct.net/r330/projectResources.js:45:319) at d.Jh (https://editor.construct.net/r330/projectResources.js:650:390) at d.Jh (https://editor.construct.net/r330/projectResources.js:669:345) at d.wi (https://editor.construct.net/r330/projectResources.js:562:122) at d.wi (https://editor.construct.net/r330/projectResources.js:646:145) at d.wi (https://editor.construct.net/r330/projectResources.js:650:323)
Construct version: r330
URL: https://editor.construct.net/r330/
Date: Thu Feb 16 2023 02:16:58 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 30.7 s

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r330b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 193 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I suspect this is not actually to do with clicking the 'Insert' button, and is actually to do with pressing undo and redo quickly on a system that can't keep up. In that case I believe this is part of issue #6531, so merging in to that.

**Comment by WilsonPercival** [comment]
> I suspect this is not actually to do with clicking the 'Insert' button, and is actually to do with pressing undo and redo quickly on a system that can't keep up. In that case I believe this is part of issue #6531, so merging in to that.

@AshleyScirra You say `The 'Insert' button is coded to ignore all clicks after the first one, so it should not matter if you click it multiple times, as it will ignore all later clicks.` I don't agree with that.

You say `I suspect this is not actually to do with clicking the 'Insert' button, and is actually to do with pressing undo and redo quickly on a system that can't keep up.` I don't agree with that either.

Note that after closing the animation editor, I had many undo points in my rollbacks. Also, when a new sprite is created, it is given the name `Sprite12` instead of `Sprite2`. Also I can't rename `Sprite` to `Sprite2`.

https://user-images.githubusercontent.com/91274932/219365978-f7f1263e-24f4-4747-923d-19556347a669.mp4

**Comment by GeekManOfficial** [comment]
https://user-images.githubusercontent.com/95054989/219365567-1b07b017-5e9c-4a42-ae54-103d7ae053eb.mp4

i can reproduce this

**Comment by WilsonPercival** [comment]
> I suspect this is not actually to do with clicking the 'Insert' button, and is actually to do with pressing undo and redo quickly on a system that can't keep up. In that case I believe this is part of issue #6531, so merging in to that.

@AshleyScirra It seems to work well. After clicking a few times, I can't replicate the same bug. Great job!
