### ISSUE TITLE
Event sheet includes can not be draged into groups

### ISSUE THREAD

**Issue by muuzepuckel** [Scirra/Construct-3-bugs#655]
## Problem description

Event Sheet includes can only be moved on the main level of an Event sheet but not inside groups.

## Attach a .c3p

[includes_in_groups.zip](https://github.com/Scirra/Construct-3-bugs/files/1191989/includes_in_groups.zip)

## Expected result

Included sheet moving an indent down. (like in C2)

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
This is by design.
