### ISSUE TITLE
Display Text Wrong:  Tween Set start value

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6552]
## Problem description

`text.behaviors.tween.actions.set-value-property-tweens-start-value.display-text`

![tween](https://user-images.githubusercontent.com/45864744/219571689-f3372af0-548f-420a-a5dd-42f7ce192f5b.png)

Set start value
```
{my} set [b]{0}, Value[/b] start value to [b]{1}[/b]
```

Set end value
```
Set {my} [b]{0} {1}[/b] end value to [b]{2}[/b]
```

## Attach a .c3p

[tween-startValue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10764085/tween-startValue.c3p.zip)

## Expected result

Set start value
```
Set {my} [b]{0} {1}[/b] start value to [b]{2}[/b]
```

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
