### ISSUE TITLE
Text in tabs is permanently dark grey.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#6559]
## Problem description

Text in tabs is permanently dark grey.

## Attach a .c3p

Any file should present it.
![scirra1](https://user-images.githubusercontent.com/34659544/219844156-ec6cdda1-935b-480c-990e-afae43da703d.PNG)

## Steps to reproduce

1. Try to change the color of a tab's text to white.
2. Observe the color of the text doesn't change.
3. You can also observe from the image that comments do text color, so the problem is probably isolated.

## Observed result

not changing the text color in tabs

## Expected result

being able to change color in the tab's text.

## More details

**Affected browsers/platforms:** Tested in latest chrome.
**First affected release:** Tested in r330

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Looks like it only affected the dark/light themes. Should be fixed for next beta.
