### ISSUE TITLE
Update prompt gets wrong version number

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#656]
When a new version of Construct 3 is detected, it prompts the user to update, and tells them what the new version is. However it tells them the wrong new version. It gets the new version from the `version` field in editor.construct.net/offline-root.json. This is expected to have the Construct 3 version code in it, but instead it has the release ID (currently 58).

If the C3 version is `rA.B`, the version code is `A * 100 + B`. E.g. r41.2 is 41 * 100 + 2 = `4102`. This number (4102) should be in the `version` field of offline-root.json. This will make C3 say "version r41.2 is now available". Currently it says "version r0.58 is available", which is not a valid version.

**Comment by TomGullen** [comment]
Done for next release
