### ISSUE TITLE
Unhandled rejection spritesheet size crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6576]
## Problem description

Construct crashes.

## Attach a .c3p

save open project: [save_open_project.zip](https://github.com/WilsonPercival/WilsonPercival/files/10775447/save_open_project.zip)

## Steps to reproduce

1. Create a new project.
2. Create a new sprite.
3. Select the first frame.
4. Press Ctrl + C.
5. Press Ctrl + V 20 times.
6. Close the animation editor by pressing `Escape`.
7. In the left ear, set the `Max spritesheet size` parameter to `512`, then to `2048`.
8. Press Ctrl + Z and Ctrl + Y quickly until it crashes.

## Observed result

https://user-images.githubusercontent.com/91274932/219905714-73d40339-8688-437a-ba7b-45defb9401bf.mp4

## Expected result

Construct does not crash.

## More details

Error report information
Type: unhandled rejection
Reason: Error: iterating sprite sheet collection while rebuilding @ Error: iterating sprite sheet collection while rebuilding at window.mwa.rEa (https://editor.construct.net/r330/projectResources.js:578:244) at rEa.next () at d.kla (https://editor.construct.net/r330/projectResources.js:1745:578) at d.GSb (https://editor.construct.net/r330/projectResources.js:1727:484) at d.vh (https://editor.construct.net/r330/projectResources.js:1775:246) at OM.Pq.ef (https://editor.construct.net/r330/projectResources.js:1865:481) at window.sc.gj (https://editor.construct.net/r330/projectResources.js:1860:143) at d.gj (https://editor.construct.net/r330/projectResources.js:1736:78) at window.ueb.gj (https://editor.construct.net/r330/main.js:2510:264) at Array. (https://editor.construct.net/r330/main.js:2483:31)
Stack: Error: iterating sprite sheet collection while rebuilding at window.mwa.rEa (https://editor.construct.net/r330/projectResources.js:578:244) at rEa.next () at d.kla (https://editor.construct.net/r330/projectResources.js:1745:578) at d.GSb (https://editor.construct.net/r330/projectResources.js:1727:484) at d.vh (https://editor.construct.net/r330/projectResources.js:1775:246) at OM.Pq.ef (https://editor.construct.net/r330/projectResources.js:1865:481) at window.sc.gj (https://editor.construct.net/r330/projectResources.js:1860:143) at d.gj (https://editor.construct.net/r330/projectResources.js:1736:78) at window.ueb.gj (https://editor.construct.net/r330/main.js:2510:264) at Array. (https://editor.construct.net/r330/main.js:2483:31)
Construct version: r330
URL: https://editor.construct.net/r330/
Date: Sun Feb 19 2023 02:29:48 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 49.9 s

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r330b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 193 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Steps involve rapid undo/redo so merging in to #6531.

**Comment by WilsonPercival** [comment]
@AshleyScirra I can still reproduce it in `r331b`.

https://user-images.githubusercontent.com/91274932/220714353-9dc616e2-fd1e-46e0-ad32-bcc12a64c242.mp4

Error report information
Type: unhandled rejection
Reason: Error: iterating sprite sheet collection while rebuilding @ Error: iterating sprite sheet collection while rebuilding at window.rwa.BEa (https://editor.construct.net/r331/projectResources.js:580:244) at BEa.next () at d.sla (https://editor.construct.net/r331/projectResources.js:1749:578) at d.$Sb (https://editor.construct.net/r331/projectResources.js:1731:484) at d.vh (https://editor.construct.net/r331/projectResources.js:1779:306) at YM.Rq.ff (https://editor.construct.net/r331/projectResources.js:1871:481) at window.sc.Dh (https://editor.construct.net/r331/projectResources.js:1865:319) at d.Dh (https://editor.construct.net/r331/projectResources.js:1740:9) at https://editor.construct.net/r331/main.js:2511:354 at window.Geb.Dh (https://editor.construct.net/r331/main.js:2511:397)
Stack: Error: iterating sprite sheet collection while rebuilding at window.rwa.BEa (https://editor.construct.net/r331/projectResources.js:580:244) at BEa.next () at d.sla (https://editor.construct.net/r331/projectResources.js:1749:578) at d.$Sb (https://editor.construct.net/r331/projectResources.js:1731:484) at d.vh (https://editor.construct.net/r331/projectResources.js:1779:306) at YM.Rq.ff (https://editor.construct.net/r331/projectResources.js:1871:481) at window.sc.Dh (https://editor.construct.net/r331/projectResources.js:1865:319) at d.Dh (https://editor.construct.net/r331/projectResources.js:1740:9) at https://editor.construct.net/r331/main.js:2511:354 at window.Geb.Dh (https://editor.construct.net/r331/main.js:2511:397)
Construct version: r331
URL: https://editor.construct.net/r331/
Date: Wed Feb 22 2023 19:48:18 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 61.8 s

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
