### ISSUE TITLE
Unhandled rejection when editing any 3D object crash

### ISSUE THREAD

**Issue by ToadLobe** [Scirra/Construct-3-bugs#6578]
## Problem description

Whenever the graphical editor for any 3D object opens, Construct 3 crashes immediately.

https://user-images.githubusercontent.com/65856568/219948669-2b50eb03-b6db-401b-b9d1-ed6f2fb51f13.mp4

## Attach a .c3p

Easy to reproduce without project file.
[Demo.zip](https://github.com/Scirra/Construct-3-bugs/files/10776893/Demo.zip)

## Steps to reproduce

1. Create a 3D object.
2. When the graphics editor opens, Construct 3 crashes

## Observed result

Crashed.

## Expected result

Not to crash.

## More details

Although I forgot to remove 3rd party addons, the bug persists when they are uninstalled.

**Affected browsers/platforms:** Chrome, Edge (haven't tested others)

**First affected release:** Broke in r330

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'Fk') @ TypeError: Cannot read properties of undefined (reading 'Fk') at PEa (https://editor.construct.net/r330/projectResources.js:140:253) at SFa (https://editor.construct.net/r330/projectResources.js:175:182) at Sy.pW.ga (https://editor.construct.net/r330/projectResources.js:2109:131) at yx.g.K.Sb.R (https://editor.construct.net/r330/projectResources.js:1972:232) at https://editor.construct.net/r330/projectResources.js:134:334
Stack: TypeError: Cannot read properties of undefined (reading 'Fk') at PEa (https://editor.construct.net/r330/projectResources.js:140:253) at SFa (https://editor.construct.net/r330/projectResources.js:175:182) at Sy.pW.ga (https://editor.construct.net/r330/projectResources.js:2109:131) at yx.g.K.Sb.R (https://editor.construct.net/r330/projectResources.js:1972:232) at https://editor.construct.net/r330/projectResources.js:134:334
Construct version: r330
URL: https://editor.construct.net/r330/
Date: Sun Feb 19 2023 12:28:24 GMT+0000 (Greenwich Mean Time)
Uptime: 9.3 s

Platform information
Product: Construct 3 r330 (beta)
Browser: Chrome 109.0.5414.121
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2
</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-3-bugs/issues/6543

**Comment by ToadLobe** [comment]
> Duplicate #6543

Oh thanks, my bad
