### ISSUE TITLE
When press 'Ctrl + F' in Example browser, Should search in Example browser

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6592]
## Problem description

Currently, press `Ctrl + F` will displays the search bar even if no project open. So, in the Examples browser, if you want to search something, it will be blocked.

![Snipaste_2023-02-21_23-24-33](https://user-images.githubusercontent.com/45864744/220386546-0615f5af-254f-4a10-bbe5-46c710b7a819.png)

## Steps to reproduce
1. [open Construct](https://editor.construct.net/beta)
2. Press `Ctrl + F`

## Expected result

Search in here
![Uploading Snipaste_2023-02-21_23-59-00.png…]()

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in next beta.
