### ISSUE TITLE
Unhandled rejection insert object class not yet added to folder crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6594]
## Problem description

Construct crashes.

## Attach a .c3p

save open project: [save_open_project.zip](https://github.com/WilsonPercival/WilsonPercival/files/10798172/save_open_project.zip)

## Steps to reproduce

The steps below only apply to the last video showing the crash. Also, I'm not sure if each step is required to reproduce the problem.

1. While on the main page, reload Construct. This is necessary so that I have time windows, thanks to which I can break some of the Construct mechanisms. Because at this moment all the resources have not yet loaded. The next steps must be done at a pace.
2. Create a new project.
3. Open the `Create new object type` window.
4. Wait until the icons are loaded and you will see the selected `3D Camera` object and press the `Insert` button.
5. Open the `Create new object type` window.
6. Wait until the icons are loaded and you will see the selected `3D Shape` object and press the `Insert` button. Without waiting for the addition, click the `Cancel` button.
7. Wait for the `Loading icons...` in the lower left corner to load.
8. Wait for the `Loading addon events...` to load in the bottom left corner.
9. Slowly press the `Undo` buttons until the very beginning.
10. Slowly press the `Redo` buttons until a crash occurs.

## Observed result

I started checking this bug after the fix: https://github.com/Scirra/Construct-3-bugs/issues/6547

Initially, I found that after certain actions I could not use the rollback system at all: I clicked, but nothing rolled forward or back. The `Ctrl + Z` and `Ctrl + Y` keys do nothing either.

https://user-images.githubusercontent.com/91274932/220473305-2f22a6f8-ccb9-4949-9d8a-ca92c2f98796.mp4

I also found that now I can't insert any new object.

https://user-images.githubusercontent.com/91274932/220473373-b7499771-3ed1-4632-8029-7aeef525bdeb.mp4

On the last try, when I was going to record an existing problem, I caught a crash.

https://user-images.githubusercontent.com/91274932/220473560-fa50a8c4-1d02-4833-91e6-2a47b4f78bc7.mp4

## Expected result

Construct does not crash.

## More details

Error report information
Type: unhandled rejection
Reason: Error: object class not yet added to folder @ Error: object class not yet added to folder at d.Oc (https://editor.construct.net/r331/projectResources.js:654:71) at window.NS.F2a (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:100:97) at Array. (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:86:410) at window.Geb.dispatchEvent (https://editor.construct.net/r331/main.js:1236:42) at Pu (https://editor.construct.net/r331/projectResources.js:46:319) at d.Kh (https://editor.construct.net/r331/projectResources.js:653:390) at d.Kh (https://editor.construct.net/r331/projectResources.js:672:345) at d.xi (https://editor.construct.net/r331/projectResources.js:564:122) at d.xi (https://editor.construct.net/r331/projectResources.js:649:145) at d.xi (https://editor.construct.net/r331/projectResources.js:653:323)
Stack: Error: object class not yet added to folder at d.Oc (https://editor.construct.net/r331/projectResources.js:654:71) at window.NS.F2a (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:100:97) at Array. (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:86:410) at window.Geb.dispatchEvent (https://editor.construct.net/r331/main.js:1236:42) at Pu (https://editor.construct.net/r331/projectResources.js:46:319) at d.Kh (https://editor.construct.net/r331/projectResources.js:653:390) at d.Kh (https://editor.construct.net/r331/projectResources.js:672:345) at d.xi (https://editor.construct.net/r331/projectResources.js:564:122) at d.xi (https://editor.construct.net/r331/projectResources.js:649:145) at d.xi (https://editor.construct.net/r331/projectResources.js:653:323)
Construct version: r331
URL: https://editor.construct.net/r331/
Date: Wed Feb 22 2023 00:00:57 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 41.3 s

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

https://user-images.githubusercontent.com/91274932/220480055-f59eeb95-fb5e-4ae6-990b-b333be73b6a9.mp4

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r331b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 198 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is another tricky one to reproduce but I think the problem is pressing 'Insert' then 'Cancel' before it closes. I've added some extra checks for that in the next beta so we'll see if that helps.

**Comment by AshleyScirra** [comment]
r332 is now out, please check again there.

**Comment by WilsonPercival** [comment]
> r332 is now out, please check again there.

@AshleyScirra It seems to work great! I can't press `Insert` and quickly `Cancel` - the object is created anyway! Great job!

**Comment by AshleyScirra** [comment]
Thanks for confirming.
