### ISSUE TITLE
Image editor: Pasting a selection makes it go offscreen when zoomed in

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#660]
## Problem description

When you paste a selection, while zoomed in, or scrolled to the side, it is not acccessible for you to move until you scroll or zoom out to go searching for it.

This is not a problem in C2.

## Attach an Image

![image](https://user-images.githubusercontent.com/5744908/28907849-ae33d380-7863-11e7-8d6c-c4c163209cc5.png)

I pasted a drawing, but it's not on my screen

## Steps to reproduce

1. Draw a picture
2. Select and copy it
3. Zoom in and scroll to the side
4. Paste it

## Observed result

I can't see where the paste has gone.

If you look for it, it has gone to the 0,0 coordinates of the image.

## Expected result

**Minimum C2 expectation:** 

- The pasted selection should be at the top left of the current screen coordinates.

**Photoshop expectation:** 

- If a selection box is present, it pastes it into the center of that box. (Although unlike C3, PS does not deselect your box after Copying.)
- If no selection box is present, it pastes to the center of the screen

**Comment by DiegoScirra** [comment]
This is implemented in r48.

When you paste paste something it will always appear in the center of the screen, no matter the zoom or the scrolling.
