### ISSUE TITLE
Platformer Object 'On Landed' triggers one tick too late

### ISSUE THREAD

**Issue by Kapusta-dev** [Scirra/Construct-3-bugs#6600]
## Problem description

Platformer object 'On Landed' trigger seems to take an extra tick to process after the object lands, causing unintended effects in certain situations when running code in that trigger event.

## Attach a .c3p

[PlatformerJumpBug.zip](https://github.com/Scirra/Construct-3-bugs/files/10800329/PlatformerJumpBug.zip)

## Steps to reproduce

If running on a 60Hz display - adjust the VectorX value in event 6 from 93.3 to 108.55
If running on a 144Hz display - leave VectorX value in event 6 at 93.2

1. Press Q to align the player, wait for them to land on the ground
2. Press W to make the player jump, note they land on the very edge of the platform, stop, and then slide down along it
3. It may not consistently reproduce - keep repeating steps 1 and 2 until it does - usually doesn't take more than 4 tries

## Observed result

The player lands on the very edge of the platform, stops, and then slides along it

## Expected result

Event 4 states that once the player lands, VectorX should be set to 0, therefore stopping the player on the edge of the platform and not letting them slide down along it.

Strangely enough under debug different results are observed almost every time, where the player will either successfully land on the platform, the bug will occur and player will fall down along it, or the player will overshoot the platform (which never happens when testing outside of debug)

When managing to replicated the issue under debug and advancing frame by frame, player's VectorY does hit 0 indicating they landed, yet the VectorX is decelerating.

![image](https://user-images.githubusercontent.com/67970011/220532695-bc9feefe-9474-4735-aa1d-e6fa8ef116fc.png)

Advancing one additional frame is when VectorX is then set to 0 as well per Event 4

![image](https://user-images.githubusercontent.com/67970011/220532784-0b3d9017-070c-4664-82b3-292542e7f22b.png)

But by then the player has already moved off of the platform, and therefore starts to fall down along it

![image](https://user-images.githubusercontent.com/67970011/220532852-4435e4f0-d071-4256-bafb-fc45a513e26a.png)

The expected result is the player's VectorX is set to 0 on the same frame that player's VectorY is set to 0, as that would be the point where the player has landed, and the 'on landed' should trigger - otherwise I'm not sure how else to make precise platforming controls. Increasing deceleration value was not a workable solution.

## More details

Occurs on both Chrome and Edge browsers.
Bug occurs in R331 but have had projects with this happening as far back as R270

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 110.0.5481.104
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 80 gb
Storage usage (approx): 304 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Also are you sure this isn't just another variant of #6599? It uses the same repro and the cause of that issue may be enough to explain this one too.

**Comment by Kapusta-dev** [comment]
Hi Ashley,

Can confirm the attached project in the original post would reproduce when switching between v-synced and unlimited framerate - I just can't predict the jump strength in the case of unlimited framerates because platform movement doesn't seem to be entirely framerate independent and the player ends up jumping further, per issue #6599

Reading over #6550 I believe it might be the same issue here though, where 1 extra tick of velocity is being applied. I am Ok to close this issue out and see if the fix for #6550 resolves this as well. Apologies for the duplication, I did not find the other issue when initially searching and submitted this one.

Thanks!
