### ISSUE TITLE
Drawing canvas not drawing lines

### ISSUE THREAD

**Issue by CR1MS4NE** [Scirra/Construct-3-bugs#6609]
I seem to be having a very strange issue with a drawing canvas. I added one and had it drawing a line between different locations of a moving object, and it worked perfectly fine. I then added another canvas and had it drawing a line between locations of a different moving object, but this time it didn't work--it just did not draw the line. I wasn't sure if it had something to do with interference from another object or the first canvas, so I simply disabled literally everything except the condition to make the second canvas draw the line, and it still didn't work. The canvas just stayed empty. I had it set to draw a line between random positions every tick and there were no other conditions or actions, so I was expecting to see a point moving around randomly and drawing lines, but instead nothing happened. It was like the canvas didn't exist. I even tried deleting the first canvas and the second one still wouldn't draw anything. However, notably, it could paste objects perfectly fine.

[compound rotation tracking.zip](https://github.com/Scirra/Construct-3-bugs/files/10809567/compound.rotation.tracking.zip)

## Steps to reproduce

1. Create a drawing canvas
2. Create another drawing canvas
3. Have the second drawing canvas attempt to draw a line

## Observed result

The second drawing canvas does not draw any lines.

## Expected result

The canvas would draw a line between the provided points.

## More details

This issue occurs on Opera GX and Chrome on Construct release r327.2.

**Affected browsers/platforms:** 

**First affected release:**

I have never tried this before.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This looks like a mistake in your project. The "wave" canvas is weirdly sized and positioned, extending about 4000 pixels off to the left of the layout. Therefore the only enabled action is drawing content way offscreen. If you resize and reposition the "wave" canvas to fit the screen then it looks like it's working OK.

**Comment by CR1MS4NE** [comment]
I see. The reason I had it so far out was so that I could move it to the right over time and have it draw a wave pattern of the y position of the other draw point, but now I think I know how to fix it. Thanks!
