### ISSUE TITLE
Image editor: If you get a selection from paste, press delete, it will put it on the canvas anyway

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#661]
## Problem description

If you paste a selection then change your mind and press Delete, that selection will be pasted onto the image, then the selection box will be empted, but once you deselect the box you will see that the image has been left behind.

## Attach a .c3p

[paste bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1196150/paste.bug.zip)

## Steps to reproduce

1. Copy a picture 
2. Press Cntrl+V to paste
3. Presss Delete
4. Click away from the selection box to deselect it.

## Observed result

The image was pasted

## Expected result

The selection should not have pasted anything, because I pressed delete.

## Reproduction steps in image form

1. ![image](https://user-images.githubusercontent.com/5744908/28908465-2aaa3492-7867-11e7-9c96-1ad0eaa44087.png) 
2. ![image](https://user-images.githubusercontent.com/5744908/28908510-671ed8ec-7867-11e7-8df1-8c0c9292fc66.png)
3. ![image](https://user-images.githubusercontent.com/5744908/28908519-79b2f95c-7867-11e7-9237-0b08daf86740.png)
4. ![image](https://user-images.githubusercontent.com/5744908/28908530-89af6ea8-7867-11e7-87ba-3b43c755c430.png)

**Comment by DiegoScirra** [comment]
Fixed in r48.
