### ISSUE TITLE
Error when starting the project 

### ISSUE THREAD

**Issue by SPOYIN** [Scirra/Construct-3-bugs#6610]
## Problem description

Error when starting the project 

## Attach a .c3p

https://drive.google.com/file/d/1ScoBcQdqSZiNPZwZvH_5cQ2scYxpLeQS/view?usp=sharing

## Steps to reproduce

1. The error appears as soon as you open the project

## Observed result

Error report information
Type: unhandled rejection
Reason: Error: Failed to fetch @ TypeError: Failed to fetch
Stack: TypeError: Failed to fetch
Construct version: r327.2
URL: https://editor.construct.net/
Date: Thu Feb 23 2023 19:56:13 GMT+0500 (Екатеринбург, стандартное время)
Uptime: 204.6 s

Platform information
Product: Construct 3 r327.2 (stable)
Browser: Chrome 100.0.4896.75
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) c3/1.4.0 Chrome/100.0.4896.75 Electron/18.0.4 Safari/537.36
Language setting: ru-RU

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_video_texture, WEBGL_webcodecs_video_frame, OVR_multiview2

## Expected result

The project should be up and running 

## More details

This error appears when launching through any browser and in the client 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Failed to fetch @ TypeError: Failed to fetch
Stack: TypeError: Failed to fetch
Construct version: r327.2
URL: https://editor.construct.net/
Date: Thu Feb 23 2023 19:56:13 GMT+0500 (Екатеринбург, стандартное время)
Uptime: 204.6 s

Platform information
Product: Construct 3 r327.2 (stable)
Browser: Chrome 100.0.4896.75
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) c3/1.4.0 Chrome/100.0.4896.75 Electron/18.0.4 Safari/537.36
Language setting: ru-RU

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_video_texture, WEBGL_webcodecs_video_frame, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
I can't open the project because it uses third-party addons:

- Effect [Glow Worms] (Mikal_GlowWorms) by Mikal
- Effect [Outline Glow] (Mikal_OutlineGlow) by Mikal

Please see the bug report guidelines. Usually we can only help with projects that do not use third-party addons in order to rule out that the third-party addons are causing the problem.

**Comment by SPOYIN** [comment]
Can I send you these addons?

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. It is preferable to produce a minimal project, or at least one that does not use third-party addons.

**Comment by SPOYIN** [comment]
Oh, it was almost a finished game that at one point, after I added a new location stopped starting, sad that there's nothing you can do about it

**Comment by AshleyScirra** [comment]
I am willing to help, but we need the information requested by the bug report guidelines in order for it to be possible to help. Since this information is missing the report is not actionable, so closing this report. If you still want us to investigate please file a new issue and be sure to follow all the guidelines, as we cannot help without that information.
