### ISSUE TITLE
Editor Crashes when using fill tool on a Sprite

### ISSUE THREAD

**Issue by amzer0** [Scirra/Construct-3-bugs#6617]
Hello,
Using the free version of Construct3, I've created a very simply project that only has three assets in it: an enemy sprite, a player sprite, and a health bar sprite. The health bar sprite is currently an empty object.

Whenever I open up the health bar sprite and select the Fill Tool to give it a color, the editor crashes on me. This has happened 5 or 6 times.

Here is the crash report:

Error report information
Type: unhandled exception
File: https://editor.construct.net/?startTour, line 0, col 0
Message: ResizeObserver loop limit exceeded
Stack: null
Construct version: r327.2
URL: https://editor.construct.net/?startTour
Date: Thu Feb 23 2023 17:36:49 GMT-0500 (Eastern Standard Time)
Uptime: 946.9 s

Platform information
Product: Construct 3 r327.2 (stable)
Browser: Chrome 110.0.5481.105
Browser engine: Chromium
Context: browser
Operating system: Windows 11
[crashSave.zip](https://github.com/Scirra/Construct-3-bugs/files/10819144/crashSave.zip)

Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) Iris(R) Plus Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

**Comment by DiegoScirra** [comment]
This is a browser extension causing a problem. Some people have reported that the Last Pass extension was giving them trouble, but there might be others. Try disabling your extensions one at a time, use C3 for a bit and see if it improves, doing that you will be able to find which one is causing problems.

Alternatively, you can just disable them all when using C3.
