### ISSUE TITLE
cannot tab-select object that is behind a wrap-select hierarchy

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6618]
## Problem description

When trying to select an object behind another object and the overlapping object is automatically wrap selected via hierarchies, undesired selections happen.

## Attach a .c3p
[tabSelectWrap.zip](https://github.com/Scirra/Construct-3-bugs/files/10819215/tabSelectWrap.zip)

## Steps to reproduce

1.try selecting the blue sprite by tab+click

## Observed result

the blue sprite and part of the wrap-selection is selected.

## Expected result

only the wrap selection or the blue sprite is selected.

## More details
by experimenting more I realized that with shift+tab clicking I can actually select only the blue sprite, but that seemes counter intuitive.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
