### ISSUE TITLE
wrap-select+tab-click =crash

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6619]
## Problem description
tab-clicking and wrap selection causes crash

## Attach a .c3p
[wrapSelectCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/10819257/wrapSelectCrash.zip)

## Steps to reproduce

https://user-images.githubusercontent.com/89512047/221051184-bed74640-d3bc-4c51-a6fe-4be7c191f9ef.mp4

1. press tab and click one sprite
2. keep tab pressed and now click a part of the wrap boundig box, but at a place without a sprite
(video might make it clearer)
## Observed result
crash

## Expected result
no crash

## More details
There are some other quirks with tab-selecting and wrap-selected object. I feel like the way they interact is weird in general, so it might make sense to take a look at it as a whole. (I totally understand that this get's really complex here with the different selections counteracting)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r331/components/editors/layoutView/layoutView.js, line 210, col 433
Message: Uncaught TypeError: d is not iterable
Stack: TypeError: d is not iterable at xbb.Do (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:210:433) at xbb.Jc (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:203:382) at Array.tc (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:201:305) at window.Ll.dispatchEvent (https://editor.construct.net/r331/main.js:1235:399) at window.Ll.Jc (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:108:131) at HTMLDivElement. (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:96:188)
Construct version: r331
URL: https://editor.construct.net/r331/
Date: Fri Feb 24 2023 00:03:58 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 16.1 s

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 110.0.5481.177
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
