### ISSUE TITLE
Dark Theme: Search events dialog is partially missing

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#662]
## Problem description

Search events dialog is partially missing, with the default dark theme.

## Attach a .c3p

![image](https://user-images.githubusercontent.com/5744908/28912605-41d8e062-7878-11e7-8246-48c34f1f380f.png)

## Steps to reproduce

1. Right click event sheet
2. Find

## Observed result

Dialog box is invisible, the background part of I think.

**Comment by JeFawk** [comment]
![32512358-6e9a6f12-c3ff-11e7-9e23-f0306fb1c062](https://user-images.githubusercontent.com/7268697/32527119-5c8fac0c-c435-11e7-9c4f-a0a4c468877c.png)

It was kinda fixed. This is a problem on the light theme now.

**Comment by Animmaniac** [comment]
Fixed for next theme release.
