### ISSUE TITLE
Inconsistent Wait Timer

### ISSUE THREAD

**Issue by paala** [Scirra/Construct-3-bugs#6625]
## Problem description

When using wait , the game sometimes waits for a little longer and the results on the screen are not the same all the time:

I am using a player with platform behaviour with gravity changed to 200.

The events are:
if Keyboard presses F: platform vector y=-650; wait 0.2 sec; platform.vector.y=0;

## Attach a .c3p

 https://drive.google.com/file/d/1pSInat6aqWungtl7i78bmIp92IP4vmL7/view?usp=share_link

## Steps to reproduce

1. press F to trigger jump, 
2. observe on screen the player highest Y 
3. wait for the player to land
4. repeat step 1-3 multiple times(20-30 times)

## Observed result

Observe that sometimes the player reaches 314 sometimes 324. 
This is not a text bug since when it reaches 314 it touches the red box

## Expected result

I expect the player to reach the same height every time, consistently.

More Details:

If you press D the game waits for 13 game loops. This case is consistent, the player stops at 314 every time.
 If waiting for seconds is inconsistent we need a function wait for X game loops 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
`If you press D the game waits for 13 game loops. This case is consistent, the player stops at 314 every time.`  No, I don't always have 314. Sometimes 313.

**Comment by paala** [comment]
@WilsonPercival well is 313.90 and 314.1. the range is much smaller compared to 314 vs 324

**Comment by paala** [comment]
@WilsonPercival is not very elegant since it uses code and not events but thanks

**Comment by WilsonPercival** [comment]
> @WilsonPercival is not very elegant since it uses code and not events but thanks

It uses events. And the fact that in the body of the function you should not worry.

**Comment by AshleyScirra** [comment]
I can't reproduce this. For me, it reads almost exactly 324 every time, and I tried many times.

Besides, I think the problem is this: 'Wait' is only accurate to the nearest frame. Waiting 200ms means it will wait for enough frames to pass that the frame times add up to at least 200ms, but at say 30 FPS then that will only be accurate to the nearest 33ms. So there is no guarantee that 'Wait' will work as precisely as this project expects it to.
