### ISSUE TITLE
XML.StringValue("/") does not return a proper xml node as text - XML syntax characters are being escaped

### ISSUE THREAD

**Issue by YoricWatterott** [Scirra/Construct-3-bugs#6626]
## Problem description

Construct3's XML object can return node-attributes and node-values without issue
But when returning a node itself, it produces white space instead of XML syntax around the values

So it seems that it is escaping the characters, which should be preventable somehow I'm sure

## Attach a .c3p

[XPathBug.zip](https://github.com/Scirra/Construct-3-bugs/files/10823624/XPathBug.zip)

## Steps to reproduce

1. use any XML in XML object
2. XML.StringValue("/")
3. see that node's syntax is gone and white space in its place
4. see XPath tester for comparison: [https://www.freeformatter.com/xpath-tester.html](url)

## Observed result

white space instead of XML syntax around node values
and in more complex XML, just whitespace and no values

## Expected result

I expect the stringified XML to look like this:
`"<root>
    <node>value</node>
</root>"`

then i can use `nodeXML.load(fullXML.StringValue("/node"))`
then nodeXML would be: `<node>value</node>`

## More details

**Affected browsers/platforms:** Chrome/Firefox/Construct3 previewer, Windows

**First affected release:** I am using r327.2 (stable) - I don't know about how other releases are affected.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r327.2 (stable)
Browser: Chrome 110.0.5481.104
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 102 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I don't think this is a bug. Ultimately the expression `XML.StringValue()` returns a string, and so evaluates the XPath with a result type of `XPathResult.STRING_TYPE`. I think it is correct that this returns a string-content interpretation of the entire XML document, which is basically the text content of all nodes appended together.

What you are finding in other tools is requesting an XPath of `/` with a result type of `XPathResult.ANY_TYPE` allows returning a node iterator result, which is an object representation that can include the entire document. Construct doesn't support any types other than strings or numbers in expressions, so this type of result is not supported in Construct. Other tools might show the XML source in this case, but it's not really a string, it's just their representation of an object result.
