### ISSUE TITLE
Unhandled exception layout view after fixed crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6627]
## Problem description

Construct crashes. I have already reported this: https://github.com/Scirra/Construct-3-bugs/issues/6558

## Steps to reproduce

1. Create a new project.
2. On `Layout 1`: Create a new layer `Layer 1` and make it global.
3. Create a layout `Layout 2`.
4. On `Layout 2`: Create a new layer named `Layer 1`.
5. On `Layout 2`: Create a sprite on `Layer 1`.
6. On `Layout 2`: Rename `Layer 1` to `Layer` and make it global.
7. Switch to `Layout 1`.

## Observed result

https://user-images.githubusercontent.com/91274932/221218467-ff58fdfa-4c40-4b59-8a21-20efbd39ef2b.mp4

## Expected result

Construct does not crash.

## More details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r331/components/editors/layoutView/layoutView.js, line 56, col 61
Message: Uncaught TypeError: Cannot read properties of null (reading 'Kr')
Stack: TypeError: Cannot read properties of null (reading 'Kr') at https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:56:61 at Array.filter () at J$a (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:56:35) at window.Prc.YP (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:190:114) at Array. (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:189:6) at window.Ll.dispatchEvent (https://editor.construct.net/r331/main.js:1236:42) at G5b (https://editor.construct.net/r331/components/editors/layoutView/layoutView.js:91:458)
Construct version: r331
URL: https://editor.construct.net/r331/
Date: Fri Feb 24 2023 17:20:08 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 40.6 s

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r331b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 198 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Please provide all necessary information in the bug report as per the guidelines.

**Comment by WilsonPercival** [comment]
> Please provide all necessary information in the bug report as per the guidelines. Do not refer to other issues as it complicates dealing with the issue.

@AshleyScirra Updated steps.

**Comment by AshleyScirra** [comment]
@DiegoScirra - this one looks weird to me, not sure what's going on, think you need to look in to it. At step 6 renaming "Layer 1" to "Layer" moves it from an override layer to a normal layer, but the sprite instance incorrectly remains selected. The select tool has code to unselect instances in case overrides change when layer names change. This code runs, but when it does, it looks like the instance is on the normal layer on Layout 2, rather than the global layer on Layout 1 that it was created on. I tried making a minimal repro saving a project after step 5 but then it does not reproduce. So it seems to be some weird state that it ends up in after following the full steps.

**Comment by DiegoScirra** [comment]
I think the problem is that when the instance is added directly to the overridden layer (**Step 5**), it is added to the collection of instances in the source global layer, but it's keeping a reference to the overridden layer in it's own properties. That is why when the layer changes name and stops being overridden, the instance reports it belongs to the normal layer rather than the global one. It's an inconsistent state because depending who you ask, the instance will belong to different layers.

In the common use case none of that ever happens. When a layer becomes overridden it just shows the instances from the global layer and all those instances have their own layer set to be the global one.
