### ISSUE TITLE
Unhandled rejection animation editor xba crash :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#6628]
## Problem description

Construct crashes. I have already reported this: https://github.com/Scirra/Construct-3-bugs/issues/6527

I couldn't repeat, but my friend did.

The bug seems to be something like this: https://github.com/Scirra/Construct-3-bugs/issues/6488

## Steps to reproduce

1. Create a new project.
2. Add a sprite.
3. Duplicate 30 frames.
4. Select the zero frame.

The following steps need to be done at a pace:

5. Hold down `Shift` and press the `Mirror` button.
6. Duplicate the animation.
7. Press Ctrl + X until you see the `Can not delete the last animation` sign.
8. Close the animation editor.

## Observed result

https://user-images.githubusercontent.com/91274932/221230449-f3e643eb-2aa5-48be-9f41-32334eb738cb.mp4

## Expected result

Construct does not crash.

## More details

Error report information
Type: unhandled rejection
Reason: Error: animation frame has no content @ Error: animation frame has no content at d.kI (https://editor.construct.net/r331/projectResources.js:760:341) at d.Xba (https://editor.construct.net/r331/projectResources.js:764:438) at d.l (https://editor.construct.net/r331/projectResources.js:137:101) at async Rc.NF.ixa (https://editor.construct.net/r331/main.js:1252:286)
Stack: Error: animation frame has no content at d.kI (https://editor.construct.net/r331/projectResources.js:760:341) at d.Xba (https://editor.construct.net/r331/projectResources.js:764:438) at d.l (https://editor.construct.net/r331/projectResources.js:137:101) at async Rc.NF.ixa (https://editor.construct.net/r331/main.js:1252:286)
Construct version: r331
URL: https://editor.construct.net/r331/
Date: Fri Feb 24 2023 19:50:51 GMT+0400 (Самарское стандартное время)
Uptime: 130 s

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 110.0.5481.178
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA Corporation)
Renderer: ANGLE (NVIDIA Corporation, NVIDIA GeForce GTX 1650/PCIe/SSE2, OpenGL 4.5.0)
Major performance caveat: no
Maximum texture size: 32768
Point size range: 1 to 2047
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r331b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 110.0.5481.178
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 802 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA Corporation)
Renderer: ANGLE (NVIDIA Corporation, NVIDIA GeForce GTX 1650/PCIe/SSE2, OpenGL 4.5.0)
Major performance caveat: no
Maximum texture size: 32768
Point size range: 1 to 2047
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Please provide all the necessary information in the bug report as per the guidelines.

**Comment by WilsonPercival** [comment]
> Please provide all the necessary information in the bug report as per the guidelines.

@AshleyScirra Updated steps.

**Comment by DiegoScirra** [comment]
Does this still happen in the latest beta?

**Comment by WilsonPercival** [comment]
> Does this still happen in the latest beta?

@DiegoScirra It seems my friend can no longer repeat this in `r332b`.
