### ISSUE TITLE
Crop Transparent Edges on Firefox deteriorates image quality

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#6633]
## Problem description

On latest Firefox and previous version (109), this feature deteriorates the image quality a lot. It seems it saves the png maybe with less colors? The gradient is the most noticeable deteriorated.
This does not happen on latest Chrome.

The video does not show this too well due to the recording quality to keep under 10mb for posting here.

## Attach a .c3p
[New project.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10831608/New.project.c3p.zip)

https://user-images.githubusercontent.com/7268697/221366558-2d43277d-c239-4b62-a267-c2a8d7ee7064.mov

![frame2](https://user-images.githubusercontent.com/7268697/221366569-2b5d323f-e2ba-4980-b9b9-acc665801f65.png)

## Steps to reproduce

1. open a new project in C3 Firefox
2. drag frame file (attached above)
3. notice the quality is good
4. use the Crop transparent edges
5. notice the quality dropped

## More details

**Affected browsers/platforms:** Firefox

**First affected release:** not aware of any relevant info for this, I just noticed it now (r327.2 (stable))

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r327.2 (stable)
Browser: Firefox 109.0
Browser engine: Gecko
Context: browser
Operating system: macOS 10.15
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0
Language setting: en-US
Local storage

Storage quota (approx): 10 gb
Storage usage (approx): 10 mb (0.1%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple
Renderer: Apple M1
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 64
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Can't reproduce this.

The oldest OSX version I can try it in is 12.6, and it seems to work as expected there, no noticeable degradation. Also tried it on Windows 11 in both Chrome and Firefox and it looks like they produce the same results. There hasn't been any work done on the crop tool recently that could affect this, at least not on C3's side. I am guessing that that maybe the newer versions of Firefox produce subtle artifacts when running on old versions of OSX, 10.5 is pretty old by now.

Will have to close as there doesn't seem to be anything we can do about this.
