### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#666]
## Problem description

added / deleted some sprites.   On Close project (no saved file) crash with chrash report below

## Attach a .c3p

No saved file. posting for your info.

## Steps to reproduce

1. Adding / deleting sprites in editor then close project

## Observed result

Crash with report

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: released sprite instance was never initialized @ Error: released sprite instance was never initialized at d.ǃnd.ǃSY (https://editor.construct.net/r47/plugins/sprite/plugin.js:1:5385) at o.ǃSY (https://editor.construct.net/r47/main.js:61:198071) at o.ǃSY (https://editor.construct.net/r47/main.js:61:203968) at s.ǃSY (https://editor.construct.net/r47/main.js:61:152880) at v.ǃSY (https://editor.construct.net/r47/main.js:61:73585) at n.then (https://editor.construct.net/r47/main.js:162:35027)
Stack: Error: released sprite instance was never initialized at d.ǃnd.ǃSY (https://editor.construct.net/r47/plugins/sprite/plugin.js:1:5385) at o.ǃSY (https://editor.construct.net/r47/main.js:61:198071) at o.ǃSY (https://editor.construct.net/r47/main.js:61:203968) at s.ǃSY (https://editor.construct.net/r47/main.js:61:152880) at v.ǃSY (https://editor.construct.net/r47/main.js:61:73585) at n.then (https://editor.construct.net/r47/main.js:162:35027)
Construct 3 version: r47
URL: https://editor.construct.net/
Date: Fri Aug 04 2017 15:22:17 GMT+0100 (GMT Daylight Time)
Uptime: 1578 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
C3 release: r47

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro K3100M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Can you provide the full steps to reproduce the issue? We can't fix the issue solely from the crash report in this case.

**Comment by NetOneGames** [comment]
Sorry dont really know what happened.
I was messing with additive rendering on a top layer which its self didnt seem to be working properly.
the additive was not adding to the sprites on layer underneath.
was also having other issues with the editor.
i.e. parts of sprites were permanently transferring to other sprites when resizing
and sprite bounding boxes were detached from actual sprites and behaving almost like in paralax

I am trying to recreate

**Comment by NetOneGames** [comment]
cant recreate, editor and preview behaving OK now doing the same things
it was just for info. you can close
if it crops again i let you know.
