### ISSUE TITLE
Timeline panel gets layout spacebar input, and layout gets spacebar input when over timeline panel

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#6663]
## Problem description

I use spacebar a lot to move around the layout. I noticed the timeline bar receives the same input for start / stop.
It would be more normal in my opinion for the timeline to receive these inputs if the mouse is over the panel.

A second issue is that when the mouse is above the panel, the spacebar can move the layout around as shown in this video:

https://user-images.githubusercontent.com/7268697/221547547-4d83d28c-5fda-4073-aa50-a22bac0c5499.mov

Would be very convenient if this was changed/fix :) thank you

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** Chrome latest

**First affected release:** no idea, just started using timelines now

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r327.2 (stable)
Browser: Chrome 110.0.5481.177
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 51 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Keyboard input goes to the focused pane. The mouse position is ignored. For example pressing the up/down arrow keys in the Project Bar causes the selected item to move up and down, but with the Layout View focused it nudges the selection position; this does not change depending on where the mouse is.

**Comment by AshleyScirra** [comment]
Please file a new issue and make sure you always fill out the full report as the bug report guidelines state. Skipping on details means such subtleties are overlooked, and this happens all the time, which is why we ask that you fill out a full report every single time, no matter how obvious you think the problem is.
