### ISSUE TITLE
Crash when duplicating a timeline that is included in another timeline

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6665]
## Problem description

Crash when duplicating a timeline that is included in another timeline. In the attached project, Timeline1 is part of Timeline3.
Manual Copy/Paste will give the same result, with an "Cannot Paste" error message.

## Attach a .c3p
[duplicate tl.zip](https://github.com/Scirra/Construct-3-bugs/files/10842914/duplicate.tl.zip)

## Steps to reproduce

1. Duplicate "Timeline 1"

## Observed result

Crash

## Expected result

Duplicating Timeline 1

## More details

**Affected browsers/platforms:** Chrome App

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'Ha') @ TypeError: Cannot read properties of undefined (reading 'Ha') at vCa (https://editor.construct.net/r327-2/projectResources.js:87:172) at d.Ha (https://editor.construct.net/r327-2/projectResources.js:1009:415)
Stack: TypeError: Cannot read properties of undefined (reading 'Ha') at vCa (https://editor.construct.net/r327-2/projectResources.js:87:172) at d.Ha (https://editor.construct.net/r327-2/projectResources.js:1009:415)
Construct version: r327.2
URL: https://editor.construct.net/
Date: Mon Feb 27 2023 20:35:49 GMT+0200 (GMT+02:00)
Uptime: 20.5 s

Platform information
Product: Construct 3 r327.2 (stable)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: webapp
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 610 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.

What was happening is that the process of duplication was trying to set the new timeline as nested in the same place the original was, that wasn't working, and even if it did it would be strange. On the next beta, the duplicate will have no knowledge of any timelines the original was nested in.
