### ISSUE TITLE
Crash After Selecting Family Object When Layout Is Selected

### ISSUE THREAD

**Issue by Rhindon** [Scirra/Construct-3-bugs#6667]
## Problem description

When a layout tab is active for editing, clicking a Family object (not the drop-down arrow next to the object's listing) in the Project window may cause a crash. I am uncertain what exactly causes this as not all Family objects cause a crash in all layouts.

Two things seem to be part of the condition to cause the crash:
1. The Family object must have two or more objects that collectively make up that Family object.
2. Most or all (???) objects of that Family must have at least one instance in the layout.

## Attach a .c3p

[The Ring v 3-1 zip.zip](https://github.com/Scirra/Construct-3-bugs/files/10845284/The.Ring.v.3-1.zip.zip)

## Steps to reproduce
The following are the ways I was able to cause the crash... But as mentioned above, I'm unsure of the exact conditions as not all times that I clicked on a Family object listing in the Project window caused a crash in both layouts of my project.

It should be noted that clicking on any Family object while the event sheet is active does not appear to cause a crash. ....... Actually, scratch that. I re-tested it with the "Event sheet 1" sheet active and it caused a crash. I'll detail everything as best I can below.

I also just discovered that left- or right-clicking on the Family object in the Project window will cause the crash.

SCENARIO 1
1. Select the "L Ring" layout tab.
2. In the Project window, click on any of the following Family objects: "ElecBarr_Bases" , "ElecBarr_Poles" , "ElecBarr_Poles_Imgs" , "ElecBarr_Wall_Track_Bases" , or "Family1".
3. The crash occurs.

SCENARIO 2
1. With "Event sheet 1" already active when loading the project file...
2. Click on any of the following Family objects: "ElecBarr_Bases" or "ElecBarr_Poles_Imgs".
3. The crash occurs.

SCENARIO 3
1. Select the "L Dump" layout tab.
2. Click on any of the following Family objects: "ElecBarr_Bases" or "ElecBarr_Poles_Imgs"
3. The crash occurs.

## Observed result

When certain Family objects are clicked on in the Project window, the editor crashes with the red-highlight of doom.
(That's a joke...because, ya know...blue-screen of death? You guys are programmers. I figured you'd get it. I know...terrible joke. I'll quit now. LOL)

## Expected result

The normal expectation of selecting the Family object to highlight it and edit its properties or editing its contents (via right-click).

## More details
As I mentioned, I am unclear of the precise nature of what it is about the Family objects that cause the crash. It seems that instances of all objects in the Family must be in the layout but this doesn't always seem to be the case. For example, in the "L Ring" layout, I added one and then two instances of the lone "Player_BulletBasic" object from the "Weapons" Family object. Then I clicked on the Family object listing in the Project window. This did not cause a crash. I did not test if adding another object to the "Weapons" Family and then adding that object instance into the layout would also cause a crash.

**Affected browsers/platforms:**
CHROME Version 110.0.5481.177 (Official Build) (64-bit)
(Apparently, there is a new release available...I was not aware of this until now.)

**First affected release:**
r331 beta

Thank you to all of you at Construct who work so hard to kill these bugs! I do not envy you your job, but I am very grateful for you!
- A Yank from across the Pond

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r331/components/bars/propertiesBar/propertiesBar.js, line 33, col 146
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'ta')
Stack: TypeError: Cannot read properties of undefined (reading 'ta') at Gfb (https://editor.construct.net/r331/components/bars/propertiesBar/propertiesBar.js:33:146) at CCG.aa.eT (https://editor.construct.net/r331/components/bars/propertiesBar/propertiesBar.js:145:167) at Adb (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:2:130) at window.NS.dLa (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:95:129) at Array. (https://editor.construct.net/r331/components/bars/projectBar/projectBar.js:91:97) at CCG.lh.g.K.HJa.dispatchEvent (https://editor.construct.net/r331/main.js:1235:399) at CCG.lh.g.K.HJa.PM (https://editor.construct.net/r331/main.js:1604:317) at CCG.lh.g.K.HJa.YF (https://editor.construct.net/r331/main.js:1599:24) at d.tk (https://editor.construct.net/r331/main.js:1627:321) at d.Ed (https://editor.construct.net/r331/main.js:1620:317)
Construct version: r331
URL: https://editor.construct.net/r331/
Date: Mon Feb 27 2023 17:38:09 GMT-0600 (Central Standard Time)
Uptime: 20.1 s

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 110.0.5481.177
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_provoking_vertex, WEBGL_video_texture, WEBGL_webcodecs_video_frame

</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-3-bugs/issues/6639

**Comment by Rhindon** [comment]
@WilsonPercival - Ah, thanks. I guess I didn't search well enough...though I did search to see if there was any such bugs already. Thanks!
