### ISSUE TITLE
Setting webfonts not working

### ISSUE THREAD

**Issue by chris200x9** [Scirra/Construct-3-bugs#667]
## Problem description

Webfont not working in C3 but works in C2

## Attach a .c3p

https://drive.google.com/open?id=0B0oFUfPeBLT0NDhoSVR0UVFYVGc

And for refrence to see it working the c2 capx is below

https://drive.google.com/open?id=0B0oFUfPeBLT0RURPRFBjZThQU2c

## Steps to reproduce

try to set local webfont

## Observed result

Text stays same font

## Expected result

Text set to webfont*

## Affected browsers

* Chrome: yes

Just tried in editor preview but seems more like an editor bug than a browser bug since chrome was used both in the c2 test and c3 test.

## System details

win 10 x64

**Comment by AshleyScirra** [comment]
The "Set webfont" action is deprecated in Construct 3, because you can set the web font directly. Change the Text object's font property to the webfont and delete the 'Set webfont' action and it seems to work OK. Is that a reasonable workaround for you?

**Comment by chris200x9** [comment]
That works out very well for my purposes, thank you! This way seems to work better too because there is no longer a noticeable jump as the text changes font.
