### ISSUE TITLE
Template Scripting Interface Missing

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-3-bugs#6673]
## Problem description

There is no JS Scripting Interface for **TemplateName()** and **TemplateKind() (returns Source/Replica/None)**.

It would also be great to have a **getAllTemplateNames()** and a ***TemplateNames()**  API : an array and an iterator for all the Templates for this ObjectType

**Btw it would also be useful to also add a C3 expression or condition regarding TemplateKind**.
Expressions : MySprite.TemplateKind = Source/Replica/None
Or Condition : [MySprite] is Source/Replica/Not a Template (dropdown list)

**Comment by AshleyScirra** [comment]
I will add script interfaces for information that is currently available in the event system (such as TemplateName), but if they are not already in the event system they should be posted as suggestions.

**Comment by OverboyDev** [comment]
Ok thanks, does it includes getAllTemplateNames() and *TemplateNames() ?

Regarding TemplateKind, this is one of those numerous things that are already in the engine but they're not exposed to us (neither in eventsheets or in JS). 

It would be great if such things that are actually there in the engine would be exposed to Eventsheets most of the time (missing conditon/action/expressions), because sometimes there isn't any way to do things that looks very simple and we know it's just a matter of exposing something.

The opposite is also true, there are so many things that are exposed in the scripting interfaces but lacking in the eventsheets. I would love if there was the same priority to add missing ACE from existing JS features as adding missing JS interfaces from existing ACE.

**Comment by WilsonPercival** [comment]
> Ok thanks, does it includes getAllTemplateNames() and *TemplateNames() ?
> 
> Regarding TemplateKind, this is one of those numerous things that are already in the engine but they're not exposed to us (neither in eventsheets or in JS).
> 
> It would be great if such things that are actually there in the engine would be exposed to Eventsheets most of the time (missing conditions/actions/expressions), because sometimes there isn't any way to do things that looks very simple and we know it's just a matter of exposing something.
> 
> The opposite is also true, there are several things that are exposed in the scripting interfaces but lacking in the eventsheets. I would love if there was the same priority to add missing ACE from existing JS interfaces as adding missing JS interfaces from existing ACE.

@OverboyDev I think it's better to prioritize scripts. Because more experienced developers write scripts. And more often than the less experienced, they lack some subtle things.

**Comment by OverboyDev** [comment]
I don't think it's better to prioritize scripts. The biggest part of C3 userbase are Eventsheet users, this is the main USP of C3, all the most successful C3 games are made with eventsheet so far. A lot of experienced and talented devs in the community are eventsheet users.

Moreover my point wasn't to say X should be prioritized over Y. I just think it would be cool if at least all things exposed to JS were also exposed as ACE for eventsheets.

**Comment by F3der1co** [comment]
I think idealy both scripting and events should have as much overlap as possible, this will be perfect for projects that use both events and js (which I think is the sweetspot of the engine rn) as well for users that want to transition between events and js.
Having a stuff available in one but not the other is sub-optimal imo.

**Comment by AshleyScirra** [comment]
I've added `IInstance.templateName` for the next release cycle (first beta release after the next stable release, in order to minimise changes in the run-up to a stable release). That is arguably an oversight as there is an expression for it but not a script API.

For other additions please post a suggestion, and be sure to include an explanation of what it is used for, as it is difficult to prioritise suggestions that do not include a rationale.
