### ISSUE TITLE
Crash on adding spritexy for set position of created sprite - Crash report for info

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#668]
## Problem description

Crash on adding spritexy for set position of created sprite - Crash report for info

## Attach a .c3p

Sorry no file crash pre save - for info only.

## Steps to reproduce

**1.  adding spritexy for set position of new created sprite (had just double clicked target sprite in "expressions dictionary"**

## Observed result

crash

## Affected browsers

* Chrome: yes

## System details

Error report information
Type: assertion failure
Message: _parent must be null
Stack: Error at Function.ǃp.ǃSEC (https://editor.construct.net/r47/main.js:2:202189) at t (https://editor.construct.net/r47/main.js:2:171852) at window.assert (https://editor.construct.net/r47/main.js:2:172255) at ǃp.ǃk.ǃi.ǃlT$.ǃShO (https://editor.construct.net/r47/main.js:2:315953) at ǃp.ǃk.ǃi.ǃlT$.ǃoR (https://editor.construct.net/r47/main.js:2:315867) at ǃp.ǃk.ǃi.ǃlT$.ǃoR (https://editor.construct.net/r47/main.js:149:136879) at ǃp.ǃk.ǃi.ǃlMa.ǃlTD (https://editor.construct.net/r47/main.js:149:132899) at ǃp.ǃk.ǃi.ǃlMa.ǃlTl (https://editor.construct.net/r47/main.js:149:132850) at HTMLAnchorElement.ǃlTp.onclick (https://editor.construct.net/r47/main.js:149:123577)
Construct 3 version: r47
URL: https://editor.construct.net/
Date: Fri Aug 04 2017 16:05:35 GMT+0100 (GMT Daylight Time)
Uptime: 2218.5 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
C3 release: r47

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro K3100M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by AshleyScirra** [comment]
What is "spritexy"? That's not a valid expression or term used anywhere in Construct. Please be as clear and detailed as possible when providing the steps to reproduce so we can easily understand how to follow.

Assigning to Diego based on stack trace.

**Comment by NetOneGames** [comment]
System action > Create Object > X (specify x coordinate)   (goto expressions dictionary to select another sprite x as spawn point x > double click sprite) > crash

**Comment by DiegoScirra** [comment]
Fixed in r50.
