### ISSUE TITLE
Example Browser:  unkown button Tooltip

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6681]
## Problem description

![Snipaste_2023-03-02_16-32-51](https://user-images.githubusercontent.com/45864744/222374701-a3691b2d-105f-485e-b99a-fd8277ae05de.png)

![Snipaste_2023-03-02_16-33-08](https://user-images.githubusercontent.com/45864744/222374763-0bf72f67-7f25-4d13-869b-3424b6ea37be.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
