### ISSUE TITLE
Worker onmessage needlessly throws an error

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#6687]
## Problem description

When worker is enabled, the engine registers an onmessage event listener in `workermain.js`

My issue is that it only uses it to initialise the runtime once, and filters for messages with the type "init-runtime" and if it receives anything that isn't that it throws an error in the console:

```throw new Error(`unknown message '${type}'`);```

This is very annoying because, I use postMessage/onMessage to communicate from worker to domSide and it needlessly throws hundreds of errors per second

## Attach a .c3p
[WorkerOnMessageThrow.zip](https://github.com/Scirra/Construct-3-bugs/files/10878230/WorkerOnMessageThrow.zip)

## Steps to reproduce

1. Preview project
2. Open the console

## Observed result

Throws an error every tick

## Expected result

Should not throw an error at all because the error doesn't serve any purpose

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
