### ISSUE TITLE
Script validation problem stops preview even when the script is disabled

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6690]
## Problem description

Script validation problem stops preview even when the script is disabled.
## Attach a .c3p
[scriptBugs.zip](https://github.com/Scirra/Construct-3-bugs/files/10886638/scriptBugs.zip)

## Steps to reproduce

1. try starting preview

## Observed result
Script validation problem doesn't allow previewing

## Expected result
Script is not validated at all because it's disabled

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta
