### ISSUE TITLE
Export failure with certain icon and "Recompression" enabled

### ISSUE THREAD

**Issue by Laserwolve** [Scirra/Construct-3-bugs#6691]
## Problem description

Exporting with the attached icon-512.png and "Recompression" enabled causes a failure to export.

## Attach a .c3p

[bugExample.zip](https://github.com/Scirra/Construct-3-bugs/files/10886653/bugExample.zip)
(file extension changed from .c3p to .zip)

## Steps to reproduce

Export project with "Recompression" enabled.

## Observed result

project fails to export.
![image](https://user-images.githubusercontent.com/87336074/222841671-1fc8a047-929d-4470-87f0-1355db5e70e5.png)
Line 906 reads:
```
CCG.Un = function(d) {
    d.I5a = !1;
    CCG.Tn(d, "livepreviewstop")
}
;
CCG.$oa = async function(d, e) {
    CCG.M.S(e, self.pb);
    if (!(!e || 0 < d.oE || 0 < d.Tv || CCG.Oe()))
        try {
            await CCG.M.yi.vsc(e)
        } catch (f) {
            console.error("Error exporting: ", f),
            f && "minify-failed-load" === f.type ? CCG.M.g.M.N("OK").P((0,
            CCG.en)("ui.errors.failed-to-load-minifier")) : f && "minify-error" === f.type ? CCG.M.g.M.N("MinifyError").P(f.log) : CCG.M.g.M.N("OK").P((0,
            CCG.en)("ui.errors.failed-to-export"))
        }
}
;
```

## Expected result

Project to export correctly.

## More details

PNG is 512x512 and was created in Photoshop. Resizing to 511x511 or 513x513 fixes the issue. Proceeding to then resize back to 512x512 does not reinstate the issue. Renaming the image does not fix the issue.

**Affected browsers/platforms:** Edge

**First affected release:** r327.2

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r327.2 (stable)
Browser: Edge 110.0.1587.57
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 4.7 gb (1.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The problem is our copy of OptiPNG seems to encounter an error when trying to recompress that particular PNG file. I don't really know why that is (it might be an OptiPNG bug), but Construct can at least handle the error better. I've updated the next beta so if a particular file fails recompression, it just uses the original file and continues with export, so it doesn't fail the export entirely.
