### ISSUE TITLE
script validation problem, line zero-based

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6693]
## Problem description
In the script validation problem the line info is 0 based, but the script editor line starts with 1.

## Attach a .c3p
[scriptBugsZero.zip](https://github.com/Scirra/Construct-3-bugs/files/10886701/scriptBugsZero.zip)

## Steps to reproduce

![line0](https://user-images.githubusercontent.com/89512047/222844315-f94cddc1-3dbd-41e2-ad11-c68d0094ed8c.png)
![line1](https://user-images.githubusercontent.com/89512047/222844325-abf5e0a6-4ea5-4399-b48e-def9e922b8ec.png)

1.double click the script in the event and observe the line number
2. try starting a preview
3. observe the line number in the script validation problem dialog

## Observed result

In the script the line is 1, but in the validation line is 0

## Expected result

either both are 1 or 0

## More details
This was really confusing to me as I was looking for a mistake in the wrong line in one of my scripts.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
