### ISSUE TITLE
copy a sprite between from  two open projects, C3 crashes in preview mode

### ISSUE THREAD

**Issue by amarcelo** [Scirra/Construct-3-bugs#670]
## Problem description

When I copy a sprite between from  two open projects, C3 crashes

## Steps to reproduce

1. Open two projects in a C3 instance
2. Copy a sprite object from the first project
3. Paste in the second project
4. Run

## Observed result

*What do you see happen?*

When I preview the game C3 crashes

## Expected result

*What did you expect to happen instead?*

Copy a sprite between two projects and run my game without any problem.

## Affected browsers

* Chrome: yes/no

## System details

Error report information
Type: assertion failure
Message: cannot find object class index
Stack: Error at Function.ǃp.ǃSEC (https://editor.construct.net/r47/main.js:2:202189) at t (https://editor.construct.net/r47/main.js:2:171852) at window.assert (https://editor.construct.net/r47/main.js:2:172255) at window.ǃSiy.ǃpVy (https://editor.construct.net/r47/main.js:61:427543) at o.ǃpVc (https://editor.construct.net/r47/main.js:61:201294) at o.ǃpVc (https://editor.construct.net/r47/main.js:61:210675) at t.map (https://editor.construct.net/r47/main.js:61:245815) at Array.map (native) at u.ǃpVc (https://editor.construct.net/r47/main.js:61:245804) at t.map (https://editor.construct.net/r47/main.js:61:231246)
Construct 3 version: r47
URL: https://editor.construct.net/
Date: Fri Aug 04 2017 12:50:50 GMT-0300 (Hora oficial do Brasil)
Uptime: 147.8 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r47

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce using the Player sprite from Ghost Shooter. Please always attach a .c3p, as per the bug report requirements, to make sure we can reproduce the issue. This happens all the time, that's why the bug report requirements are there.
