### ISSUE TITLE
Signal triggers 2 times when triggering from another signal

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-3-bugs#6707]
## Problem description

When a signal triggers from another different signal, it triggers two times instead of one.

## Attach a .c3p

[Signal BUG.zip](https://github.com/Scirra/Construct-3-bugs/files/10890552/Signal.BUG.zip)

## Steps to reproduce

1. Press space to create a sprite.

## Observed result

It creates 2 sprites.

## Expected result

It should create 1 sprite (check the event sheet).

## More details

The issue appears also if the first signal triggers from a timer or other events, not just key pressed.

**Affected browsers/platforms:** 

Chrome - didn't test others

**First affected release:** 

332 Beta - didn't test others

## System details

<details><summary>View details</summary>

Device name	LAPTOP-DAOHK829
Processor	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
Installed RAM	8.00 GB (7.83 GB usable)
Device ID	3FC91B51-E8DD-4CFB-B006-E1141BF1C7B0
Product ID	00325-82098-04728-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Home
Version	22H2
Installed on	‎20/‎11/‎2022
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in next beta.
