### ISSUE TITLE
dark theme, value up-down arrows not styled

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6711]
## Problem description

In the dark theme it seems like the value up-down arrows aren't styled

## Attach a .c3p
[darkThemeStyle.zip](https://github.com/Scirra/Construct-3-bugs/files/10892169/darkThemeStyle.zip)

## Steps to reproduce

1. open the array editor
2. click in to the width field

## Observed result
![notStyled](https://user-images.githubusercontent.com/89512047/222970576-83bd736a-c7df-46b3-b178-6457fcfeb038.png)

up down arrows show up, but aren't styled

## Expected result

the up down arrows are styled with the dark grey color palette.

## More details
These handy arrow show up not only here, but in a lot of other value fields as well, so this is just an example. (but I assume they all are based on the same CSS so fixing this might fix all).
The also don't seem to be styled in the light theme (they are the same as in the dark theme, but here the color seems to fit more naturaly with the bright colors.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
There is no native CSS styling that can be applied on the arrow buttons of number input elements.

It is possible to hide them and then implement your own buttons... that doesn't sound like something anybody in their right mind would want to do though. Those little controls probably perform all sorts of subtle behaviours which would be extremely difficult to replicate.

So in short, in the future if that styling becomes available to CSS then it will be very easy, but right now it's almost impossible.
