### ISSUE TITLE
.count not working after instance destroyed

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-3-bugs#6717]
## Problem description

"Count" doesn't report the global instance count (as supposed to) if object is picked in the same event and destroyed before a wait.

## Attach a .c3p

[COUNT BUG.zip](https://github.com/Scirra/Construct-3-bugs/files/10900705/COUNT.BUG.zip)

## Steps to reproduce

1. Run the example.

## Observed result

The text reports 0 sprites, when there are still 4 remaining.

## Expected result

The text should report the remaining 4 sprites (check the events).

**Affected browsers/platforms:** 

Chrome (didn't test others).

**Affected releases:**

332 Beta (didn't test others).

## System details

<details><summary>View details</summary>

Device name	LAPTOP-DAOHK829
Processor	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
Installed RAM	8.00 GB (7.83 GB usable)
Device ID	3FC91B51-E8DD-4CFB-B006-E1141BF1C7B0
Product ID	00325-82098-04728-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Home
Version	22H2
Installed on	‎20/‎11/‎2022
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0

</details>

**Comment by DinoSystem** [comment]
PS: love C3 keep up the great work, i hope i can contribute make it slightly better!

**Comment by AshleyScirra** [comment]
I don't think this is actually a bug, it's more a bit of a weird edge case with 'Wait'.

When using 'Destroy', it's not actually immediately destroyed, so you can still do something like create an explosion at the same position. It is only actually destroyed at the end of the next top-level event.

Adding 'Wait' causes the following actions to run after they were actually destroyed. 'Wait' also resumes the action with the same instances picked as it had originally. This means it tries to pick all the sprites with opacity 50 again, but they were destroyed, so it resumes with no instances picked. This is always a bit of a confusing situation in the event system, as it means all expressions will return 0 or an empty string, as there is no instance to ask what its value is. Consider asking what the opacity of a destroyed sprite is. Shouldn't it be 50? It actually has no value, as no instances are picked, so it returns 0. The count expression works the same (even though technically it doesn't need an instance to ask for the value, the way the event engine works still requires it).

**Comment by DinoSystem** [comment]
> I don't think this is actually a bug, it's more a bit of a weird edge case with 'Wait'.
> 
> When using 'Destroy', it's not actually immediately destroyed, so you can still do something like create an explosion at the same position. It is only actually destroyed at the end of the next top-level event.
> 
> Adding 'Wait' causes the following actions to run after they were actually destroyed. 'Wait' also resumes the action with the same instances picked as it had originally. This means it tries to pick all the sprites with opacity 50 again, but they were destroyed, so it resumes with no instances picked. This is always a bit of a confusing situation in the event system, as it means all expressions will return 0 or an empty string, as there is no instance to ask what its value is. Consider asking what the opacity of a destroyed sprite is. Shouldn't it be 50? It actually has no value, as no instances are picked, so it returns 0. The count expression works the same (even though technically it doesn't need an instance to ask for the value, the way the event engine works still requires it).

Thanks, that makes sense, i'll take this into consideratio in my project's events.
