### ISSUE TITLE
Shadow Caster Plugin and Behavior wrong color

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#674]
## Problem description

When inserting an object and assigning a shadowcaster behaviour and then adding a shadow light and adjusting the shadow color, the Shadow has a different color in the Editor than in the executed preview.

## Attach a .c3p

[shadowcaster.zip](https://github.com/Scirra/Construct-3-bugs/files/1205001/shadowcaster.zip)

## Screenshots

https://s3.postimg.org/cxqydzklv/Bildschirmfoto_2017-08-03_um_09.34.50.png
https://s3.postimg.org/r2wrfstn7/Bildschirmfoto_2017-08-03_um_09.35.05.png

## Steps to reproduce

1. Create new Construct Project
2. Insert Sprite
3.Attach Shadowcaster Behaviour
4. Insert ShadowLight
5. Adjust Shadowcolor at will.
6. Preview in the Editor with checkbox
7. Preview by hitting the play button

## Observed result

I had different issues occur, sometimes the shadow was shown correctly in the editor but pitch black in the executed game and vice versa. Also, lots of time the shadow itself colors in the Sprite that has the behaviour attached to it.

## Expected result

Shadow shown correctly as adjusted in Editor and without colorizing the Sprite.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r47

Local storage
Storage quota (approx): 131 gb
Storage usage (approx): 86 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by rvion** [comment]
I also have the bug.
@joelmayer87 As a workaround, you can manually set the shadow color from the event sheet in a layout start event.

**Comment by AshleyScirra** [comment]
Thanks, fixed for the next build.
