### ISSUE TITLE
Update Lens effect to be stable at viewport edges

### ISSUE THREAD

**Issue by XpMonster** [Scirra/Construct-3-bugs#676]
## Description
 
Can you please update Lens effect to "to be more stable at viewport edges and work better when combined with other effects."
Just must have for my superior effect to work! None other effect can do what lens can.

*I post this from "Construct 3 suggestions & ideas" as Ashley advised.
## Observed & Expected results

Download example of my issue [from Google Drive](https://drive.google.com/file/d/0Bz-IOXMAnpNvajhaZGZpMnRVTG8/view)

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

**Comment by XpMonster** [comment]
Ashley, I just made what I wanted with Warp Object Mask and it looks fine. So you can close this report if you want. I'm sure you must have plenty of other things to do.
Actually looking forward for all SDK released as very much need Spriter plugin in C3. The only way of making decent animations like with Bone Animation in CC.

**Comment by AshleyScirra** [comment]
I've made a new Lens2 effect which is viewport-stable, but it depends on the improved effects engine in the C3 runtime. I'm afraid it's difficult to backport to the C2 runtime. So it will be available in future.

**Comment by XpMonster** [comment]
Thank you. 
Still might come in handy.
