### ISSUE TITLE
[SDK] Safe-mode doesn't catch duplicate addon IDs

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#678]
## Problem description

In testing plugin creation, somehow two plugins with the same ID must have been uploaded. Not sure if this is because I was trying to load via Developer Mode, and then switched to standard mode. No issue was reported until refreshing C3 to reload with new plugin.

## Attach a .c3p

N/A

## Steps to reproduce

Unclear, other than load two plugins with the same ID.
## Observed result

Uncaught (in promise) Error: duplicate addon id 'noisejs
Can't run C3 since it throws this error. This is even with safe-mode enabled.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
Addons are stored by ID, so there is probably only one addon actually stored. This makes it difficult to tell if there are really two addons with the same ID by that point. There is probably a missing check for a duplicate ID when installing an addon. We need steps to reproduce to find that though.
