### ISSUE TITLE
Cannot Shortcut Undo/Redo After Toggle Loop & Ping Pong

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#68]
## Problem description

Also a similar mentioned bug https://github.com/Scirra/Construct-3-bugs/issues/15. But this one affects not the layout view editor but the animation editor.

## Steps to reproduce

1. Toggle "Loop" & "Ping Pong" in the animation editor.
2. Undo/ Redo.

## Observed result

Cannot undo/redo while these tick boxes is in focus.

## Expected result

Able to undo/redo.

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed. will be available in r19.
