### ISSUE TITLE
IDE CRASH after adding PLUGIN in DEVELOPPER MODE without "file-list" key in addon.json

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#680]
--------------

📝  EDIT: this problem happened because I didn't add the "file-list" key in `addon.json` ([step 3](https://www.construct.net/fr/make-games/manuals/addon-sdk/guide/using-developer-mode)) in the. Still, the crash preventing the IDE to load may lock some users out of the application.

📝  EDIT 2: just found about https://www.construct.net/fr/make-games/manuals/addon-sdk/guide/safe-mode. The documentation is clear but I think a message on the loading screen would help discovering it.

-----------

## Problem description

The ide doesn't load anymore (stuck at the loading phase) after I added an addon in developper mode.

![image](https://user-images.githubusercontent.com/2150990/29067165-e2882574-7c31-11e7-9295-2c68cb812cb0.png)

## steps to reproduce

 - downloaded [c3-plugin-sdk-v1.zip](https://www.construct.net/out?u=https%3a%2f%2fwww.scirra.com%2fdoc%2fc3sdk%2fplugin-sdk%2fc3-plugin-sdk-v1.zip)
 - extracted it as `~/dev/c3-plugins/c3-plugin-sdk-v1/*`
 - installed a webserver with cors and https support `npm i -g browser-sync`
 - ran the server `cd ~/dev/c3-plugins/ && browser-sync start --server --cors --https`
 - enabled developper mode  following [instructions here](https://www.construct.net/fr/make-games/manuals/addon-sdk/guide/enabling-developer-mode)
 - added the plugin by url: `https://localhost:3000/c3-plugin-sdk-v1/addon.json` following [documentation here](https://www.construct.net/fr/make-games/manuals/addon-sdk/guide/using-developer-mode)
 - reloaded (CMD+R) the tab as per instruction

also:

 - stopping the static server doesn't fix it

tested on chrome

**Comment by rvion** [comment]
when I stop the server, the error becomes:
![image](https://user-images.githubusercontent.com/2150990/29067759-2410477c-7c34-11e7-90bf-bb4ff58b4f5e.png)

in this case, this IDE should probably invalidate the plugin rather than fail.

**Comment by AshleyScirra** [comment]
I've updated r49 to display a better error message in this case ("developer addon is missing 'file-list' in addon.json - check the SDK documentation").
