### ISSUE TITLE
MOBILE IDE: BACK BUTTON sometimes quit ide with no warning instead of closing pane

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#681]
## Problem description

Back button sometimes quit the app without warning instead of closing project pane

## Steps to reproduce

1. open any project (any demo in the start page)
2. open project pane
2. long tap on project > close project -> the project pane is empty
3. press "back" button a first time to close the project pane : nothing happens
4. press "back" a second time (because sometimes

🕸  android / chrome

----------------

📝  there are several other scenarii leading to strange back-button behaviour:
sometimes, I have to press _back_ 3 times for a pane to close, etc. Those behaviours are consistent

**Comment by rvion** [comment]
Sometimes, it happens when pressing back in a menu choice, and I loose all my progress 😢 

Would it makes sense the the IDE to ask before leaving no matters what ?

**Comment by rvion** [comment]
I keep loosing changes because of this.
it happens in a lot of situations. At some points, the back button start to mis-behave, and a few moment later, I end up leaving the application.

right now, I just pressed back while adding an event, nothing happened, so I pressed back a second time, and the app closed without further notice :|

**Comment by AshleyScirra** [comment]
This should be working better in r58 when it's out. Let's review again when it's out. This has proven very tricky to get right...

**Comment by AshleyScirra** [comment]
r58 is out now, please check again!

**Comment by AshleyScirra** [comment]
Over 2 weeks with needinfo tag and no response, so closing.
