### ISSUE TITLE
MOBILE IDE: pasting instances place them at the wrong position

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#682]
## Problem description

1. I open a project, drag the layout view a bit, zoom a bit
1. I copy an instance  (long tap on an instance > copy) 
2. I paste it somewhere else (long tap on the layout > paste)
3. the instance appear very far from where I pasted it: often near the top left corner of the layout: I need to unzoom, look for an instance at the wrong position, click on it, and move it at the right position.

- are viewport local coordinates of the tap used to put the pasted instance ?

🔴  on medium projects with lots of instance, it makes editing layouts near impossible

🕸  Android / Chrome

**Comment by AshleyScirra** [comment]
Should be fixed in r52.
