### ISSUE TITLE
No way of removing Container

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#683]
## Problem description

When creating a container and adding a few Objects to it and then changing the selection mode to "All" or "Wrap", there is no apparent way of separating these objects again in the properties bar.

## Steps to reproduce

1. Create two sprites
2. Add sprite to a Container of the other sprite
3. Change selection mode to "All" or "Wrap"

## Observed result

The list of objects in the container disappears in the properties panel, when selecting an object.

## Expected result

Some way of separating the objects again or being able to select them separately.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Hold Alt and click an object to select just that one. Alternatively you can hold Ctrl or Shift and unselect the other objects in the container until one is left.

**Comment by joelmayer87** [comment]
Thanks! I didn't find this anywhere in the documentation. I think you should add it in the section about containers...
