### ISSUE TITLE
Mobile Advert consent form doesn't save the user's choice

### ISSUE THREAD

**Issue by bitropAlex** [Scirra/Construct-3-bugs#6839]
## Problem description

Mobile Advert consent form doesn't save the user's choice

## Attach a .c3p

[MobAdEx.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11082200/MobAdEx.c3p.zip)

## Steps to reproduce

1. Export for IOS or Android
2. Install on phone
3. Open app
4. Click consent button
5. Restart the application
6. Consent form again and status obtain

## Observed result

Consent form opened again

## Expected result

Consent form shouldn't open bc of accepted by user before

## More details

I added Mobile Advert Plugin
Specified Test mode
Created IOS and Adroid Apps in Google Admob Advert
Specified application ids
Specified "Show on start up" according to construct documentation
Created GDPR message and IDFA message

<img width="371" alt="Screenshot 2023-03-27 at 22 04 50" src="https://user-images.githubusercontent.com/129107647/228046142-4132b304-c006-4393-9a27-3346f20dc100.png">

As a result i see this consent form every time I reload the application despite the fact that every time I agree by clicking consent button

https://user-images.githubusercontent.com/129107647/228043416-01e07702-a3a6-49a6-8baa-010aaa16d37f.mp4
 

**Affected browsers/platforms:** IOS/Android

**First affected release:** r327.3 (stable)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r327.3 (stable)
Browser: Chrome 111.0.5563.110
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.2
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 10
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 1.4 gb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
When **Test mode** is enabled the consent status is reset every time the application starts, just to be able to properly see what a first install would look like, without the need of uninstalling and installing. When test mode is disabled, the dialog should work as expected. I don't think this behaviour is documented as it is quite subtle.

**Comment by bitropAlex** [comment]
Thanks a lot for the answer
But, If you don't mind, shouldn't that be in your documentation after all ?

1. This is not a standard behavior, because the AdMob documentation says that there is a separate method for resetting and by itself it is not reset
2. In case of such behavior without production mode I can't check the actual behavior and that the popup will no longer be shown after consent. And it would be better to have also a separate method than non-obvious reset every time automatically
3. Even based on your own documentation about Spoof location gives the impression of standard behavior as described in the AdMob documentation


Unfortunately at the moment it is not possible to use this feature in a real device with iOS version 14 or greater. This is because to enable the feature, it is necessary to have access to the IDFA beforehand, which is not possible without first showing the App Tracking Transparency dialog. **Since the dialog can only be shown one time**, enabling the feature makes it impossible to later test how the application would behave upon first installing it. The feature can still be used in a simulator though. 


This is just my opinion since I spent 2 days looking for the problem before posting a bug here and didn’t find anything, I also asked a question on the forum, but I didn’t get an answer, I suspect just because this is not a described non-standard behavior.

Thank a lot once again

**Comment by bitropAlex** [comment]
Thanks a lot
