### ISSUE TITLE
IDE: various CRASH & bugs on EVENT SHEET when using shortcuts

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#684]
## Problem description

on __event sheet__, with various combinaisons of `up`, `down`, `left`, `right` `c`, `b`, `a`, `shift` it's possible to reach illegal states. Once you are in such a state, you can

 1.  add __invisible__ events, sub events and actions that do not belong to anything
 2. CRASH the ide
 3. experience weird and persistent behaviours
   3.1. select 1st action of an event, press ↓ ↓ ↓ , see the selection do 1 2 __4 3__ instead of 1 2 __3 4__)
   3.2. etc.

it's easy for an user to reach an invalid state without noticing.

## Steps to reproduce

__1: to add invisible actions and events:__

minimal example:

see gif here: http://www.giphy.com/gifs/l1J3uIh5hc8JbZCpO

- add initial event (click ⏎ ⏎ ⏎)
- add blank subevent (b)
- add action (a  ⏎ ⏎ ⏎)
- go up (↑)  => 🔶  NOW in ILLEGAL STATE
- add event : a ⏎ ⏎ ⏎ => 🔴  event is invisible

__2: to crash:__

-- todo

__3: to have some weird behaviour:__

1. select some event
2. b b b b "shift" ↑ ↑ a ⏎ ⏎ ⏎ => 🔶  NOW in ILLEGAL STATE
3. many things to try from now:
 3.2. 🔴   "click on the last blank subevent" a ⏎ ⏎ ⏎ => then experiment pressing several times "up" and "down" keys
 3.2. 🔴   if you press "left", then it's now impossible to deselect the parent event with "up" or "down"
 3.3. etc.

see gif here http://www.giphy.com/gifs/3oEhmNd6dsRcEFhb1e

you'll notice that once the  overflown

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

some crash:

<details><summary>View details</summary>

Error report information

Type: assertion failure
Message: cannot select detached view
Stack: Error at Function.ǃE.ǃOVP (https://editor.construct.net/r48/main.js:2:202201) at t (https://editor.construct.net/r48/main.js:2:171837) at window.assert (https://editor.construct.net/r48/main.js:2:172240) at window.ǃKA.ǃRc (https://editor.construct.net/r48/components/editors/eventSheetView/eventSheetView.js:1:10609) at window.ǃKA.ǃAj (https://editor.construct.net/r48/components/editors/eventSheetView/eventSheetView.js:1:9077) at window.ǃKA.ǃdu (https://editor.construct.net/r48/components/editors/eventSheetView/eventSheetView.js:1:16355) at Array.ǃL.ǃE.ǃB.ǃE.ǃq.ǃs (https://editor.construct.net/r48/components/editors/eventSheetView/eventSheetView.js:1:2812) at ǃE.Event.ǃOwF.ǃOwN (https://editor.construct.net/r48/main.js:2:256115) at ǃE.ǃo.ǃEk.ǃEOb.dispatchEvent (https://editor.construct.net/r48/main.js:2:254766) at ǃE.ǃo.ǃEk.ǃEOb.ǃXQ (https://editor.construct.net/r48/main.js:2:297597)
Construct 3 version: r48
URL: https://editor.construct.net/
Date: Tue Aug 08 2017 16:47:59 GMT+0200 (CEST)
Uptime: 12839.4 s

Platform information

Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r48

WebGL information

Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

--------------

some other crash:

<details><summary>View details</summary>
Error report information
Type: assertion failure
Message: cannot select detached view
Stack: Error at Function.ǃE.ǃOVP (https://editor.construct.net/r48/main.js:2:202201) at t (https://editor.construct.net/r48/main.js:2:171837) at window.assert (https://editor.construct.net/r48/main.js:2:172240) at window.ǃKA.ǃRc (https://editor.construct.net/r48/components/editors/eventSheetView/eventSheetView.js:1:10609) at window.ǃKA.ǃAj (https://editor.construct.net/r48/components/editors/eventSheetView/eventSheetView.js:1:9077) at window.ǃKA.ǃdu (https://editor.construct.net/r48/components/editors/eventSheetView/eventSheetView.js:1:16355) at Array.ǃL.ǃE.ǃB.ǃE.ǃq.ǃs (https://editor.construct.net/r48/components/editors/eventSheetView/eventSheetView.js:1:2812) at ǃE.Event.ǃOwF.ǃOwN (https://editor.construct.net/r48/main.js:2:256115) at ǃE.ǃo.ǃEk.ǃEOb.dispatchEvent (https://editor.construct.net/r48/main.js:2:254766) at ǃE.ǃo.ǃEk.ǃEOb.ǃXQ (https://editor.construct.net/r48/main.js:2:297597)
Construct 3 version: r48
URL: https://editor.construct.net/
Date: Tue Aug 08 2017 17:00:18 GMT+0200 (CEST)
Uptime: 683.1 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r48

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
</details>

**Comment by rvion** [comment]
edit 1: added git and repro step to see weird behaviours

**Comment by rvion** [comment]
I think a tool to automate random clicks in the layout, and random key press (arrows, a, b, c, e, shift) could be handy because the above repro steps are not the only buggy ones I'm experiencing

**Comment by AshleyScirra** [comment]
I think the repro steps are missing something: you have to first delete an event, and then the arrow keys can be used to navigate to the deleted thing which is when the invalid state happens. If you just follow the steps, there's nothing deleted so it doesn't happen.

I made sure arrow keys can't select anything deleted for the next build, so that should fix all cases of this.
