### ISSUE TITLE
IDE: various UX annoyances & usability tweaks to consider

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#685]
I discovered construct a few days ago and am really impressed with the quality of your product ! Thanks for the great work 💐  !

I'm creating this thread because I've been using construct 3 quite a lot those last 3 days, both on mobile and PC, and while the UX is really great, there are some annoyances with the IDE I would love you to consider tweaking (those are not really feature request, but rather usability improvement request to make it more pleasant to use; on mobile, it is sometimes really painfull to do simple things).

I'll write them down in separated comments below (RANDOM order):

 1. [Optional "Welcome" popup](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321013800)
 2. [Mobile IDE: add 2 fingers gesture to resize and rotate objects in the layout pane](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321022604)
 3. [MOBILE IDE: avoid scrolling in menus](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321030782)
 4. [Mobile IDE - Resources creation : from "Long tap + look + click" to "click"](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321034862)
 5. [Mobile IDE: remove the "close menu” option](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321039414 )
 6. [Mobile IDE: move across layout with one finger when no object is selected](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321043219)
 7. [MOBILE IDE: side panes are too hard to open 😢 😢](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321068986) <- __please help me on this one__
 8. [Mobile IDE: filter input (and help text) are absent in some popups (not all)](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321126212)
 9. [improve readability of property pane](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321127132)
 10. [image editor: wrap toolbars on mobile like it does on desktop](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321177375)
 11. [Event sheet: focus (yellow) variable after they are created (like for events)](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321184651)
 12. [Event sheet: bind 'E' key to add event on empty sheet (like for variables)](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321184885)
13. [remote preview : allow to dock the popup](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321490640)
14. [remote preview: add "auto reload on host updated checkbox"](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321492046)
15. [remote preview: add "open in popup" button](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321494221)

**Comment by rvion** [comment]
![image](https://user-images.githubusercontent.com/2150990/29083594-8f95f854-7c69-11e7-97e9-b7f060c911ad.png)

Can we get rid of this message (opt-in option in the popup ? in the settings ?) ?
I reload the IDE a lot, and it is a bit annoying.

**Comment by rvion** [comment]
on mobile ide, in the layout:

 - it is hard to resize and rotate object (need to go through the  property pane), no visual feedback, etc.
 - when an object is selected  __two fingers gesture__ is not binded (using two fingers or one finger just move the object)

💚  easy fix: 

 - bind the __two finger gestures__ to __rotate__ and __resize__ objects

| mobile ide | ide |
|--------|--------|
| HARD to resize and rotate | EASY to resize and rotate |
| ![image](https://user-images.githubusercontent.com/2150990/29084762-637bd3f2-7c6d-11e7-9112-3babf7f6dd51.png)  |  ![image](https://user-images.githubusercontent.com/2150990/29084747-5803c192-7c6d-11e7-83fc-fd14bc2eae01.png) |

**Comment by rvion** [comment]
Can you reduce the "large_menu" font size ? 

- it is __slower__ to use (more mouse mouvements, or worse: 🔴 need to scroll in mobile menus with only 10 options 😢  🔴 )
 - it is bad for __muscle memory__
 - it is bad from a __consistency perspective__ 


|||
|--------|----------|
|![image](https://user-images.githubusercontent.com/2150990/29086098-b4d7ec82-7c71-11e7-8c3f-ecddeb758432.png) | <div> I don't care much about themes and colors, but here, it just makes the UX painful |

**Comment by rvion** [comment]
can you add those buttons please ?

![image](https://user-images.githubusercontent.com/2150990/29086743-e1a43cd2-7c73-11e7-9722-e6ab5a1ae709.png)

"right click" -> "add" is okay on the desktop IDE, but on the mobile IDE, it is quite painfull: 
I have to do a "long tap", then look for the right menu entry (not the first one), then click.

**Comment by rvion** [comment]
Can you remove the "close menu" option on the mobile IDE popups ?

 - 🍏 : there is no "close menu" on the desktop because we can just click away. it is the same on mobile, I can click anywhere around the popup to make it close.
 - it's even more redundant on mobile because I can also press the back button
 - people are not use to click in a menu item to cancel the menu selection, so it's not really effective.
 - cancelling an action should anyway not be the first thing we see when we open a menu

| desktop | mobile  | better mobile |
| ---------- | -----------| ----------- |
| ![image](https://user-images.githubusercontent.com/2150990/29087091-ff15c4e2-7c74-11e7-9f30-65a8fa3bf2a5.png) |  ![image](https://user-images.githubusercontent.com/2150990/29087107-12677d2e-7c75-11e7-9b34-2730c40a586e.png) | ![image](https://user-images.githubusercontent.com/2150990/29087440-42ce7566-7c76-11e7-94f7-d7c643ddf0f7.png) |

-------------

if you want to keep it, can you place it at the bottom or replace it by a small cross at the top right corner ?

**Comment by rvion** [comment]
## Mobile layout navigation in the IDE 

As of now, the only way I found to navigate the layout pane is to use two fingers (same as for zooming in and out). It's not practical nor very usual.

On mobile, it turns out that when no object is selected in the layout ide, "touch down" followed by "touch drag" is not binded to anything

indeed, to move objects, they need to be selected, and to select an object, I need to

| desktop | mobile |
|---------| --------|
|mouse down | touch up| 

on an object.

💚  an easy win would be allow layout navigation with one finger when no object is selected. It would be natural, efficient, and from what I can see, logical.

**Comment by rvion** [comment]
# MOBILE IDE: side panes are too hard to open 😢  😢 

this one is a major annoyance for me - it feels dump, but it almost makes the IDE impossible to use.

## side borders I need to catch and drag are too thin

I have a big cover case with a bezel around the front to protect the screen (the protection makes it a bit hard to slide from the sides, but it's usually not much a problem.

 - 🔴  with construct 3, it is a problem, it's just hard. the border I need to drag to open side panes is a bit too thin for me and half the time, I miss it. maybe my fingers are too fat, but in the end, I just feel stupid.

## I have to drag the borders way too much

my phone is 5,5".

 - 🔴  the drag distance to both open and close side panes is too big. Usual gesture are not enough and the pannel snap back.

💚  can the borders to grab to open side panes be wider ?
💚  can the drag distance to open and close side panes be reduced ? 

------------

- 🔴  in addition to this, the fact I need to swipe several times to switch between sub-panes makes it even more annoying for me. 

## side sub-panes cycling feels wrong: slow to use and hard to discover

- 🔴 side panes themselves are hard to discover
- 🔴🔴  cycling sub-side panes are even harder to discover ( I spent a few hours on mobile wondering how to pick a color in the sprite editor)

# what I really wish for the mobile IDE

💚💚💚  can you put tabs (even with just small icons and no text if it takes too much space on screen) to both reveal side panes, and switch between panes ?

I don't mind at all if it's opt-in in editor params, but as of now, it's just too painful to use.

----------

(I know I put way too many red and green emojis in this one, but I really wanted this UI tweak request to stand out)

**Comment by rvion** [comment]
## Mobile IDE: filter input (and help text) are absent in some popups (not all)

I find the filter field quite usefull

desktop:

![image](https://user-images.githubusercontent.com/2150990/29101369-0ca7e224-7cb2-11e7-885c-6251e31e21f4.png)

mobile: 

![image](https://user-images.githubusercontent.com/2150990/29101389-2cd050b8-7cb2-11e7-950a-252fbea60358.png)

**Comment by rvion** [comment]
## property pane is quite hard to read:

![image](https://user-images.githubusercontent.com/2150990/29101542-3faa6f24-7cb3-11e7-9d04-fcce463299cc.png)

 - small borders around blocs, with clearer color scheme / title background would help quite a lot I think

**Comment by rvion** [comment]
## image editor: wrap toolbars on mobile like it does on desktop

when editing images on mobile, I spend more time scrolling the toolbar to select actions (undo, grid, flip, etc), or tools options (size, hardness, etc.) than actually editing images. It is really tedious. 
(same for vertical scrolling to change tools)

on desktop, tool bars wrap correctly

| mobile 🔴  | desktop 🍏  | 
|-------|--------|
| <img src="https://user-images.githubusercontent.com/2150990/29109540-a06dce7a-7ce3-11e7-9d35-c386b54ce8fe.png" width="300px"> | <img src="https://user-images.githubusercontent.com/2150990/29110056-a96660b2-7ce5-11e7-9aac-305afdd8fbca.png" width="300px"> |

**Comment by rvion** [comment]
## Event sheet: select variable after they are created (like for events)

so we don't have to use the mouse and click somewhere to continue editing the event sheet with the keyboard

**Comment by rvion** [comment]
## Event sheet: bind 'E' key to add event on empty sheet (like for variables)

so we don't have to use the mouse and click the add button to start editing the event sheet with the keyboard

(this or something similar to avoid using the mouse)

**Comment by rvion** [comment]
## allow to dock the remote preview window.

![image](https://user-images.githubusercontent.com/2150990/29162252-26ec9730-7db9-11e7-9413-4eaaf62ecf23.png)

**Comment by rvion** [comment]
## remote preview: add "auto reload on host updated checkbox"

![image](https://user-images.githubusercontent.com/2150990/29162471-d8c6a464-7db9-11e7-8e58-cb9cb28620f2.png)

**Comment by rvion** [comment]
remote preview: add "open in popup" button

![image](https://user-images.githubusercontent.com/2150990/29162934-20904f92-7dbb-11e7-9b1b-a27f1af10258.png)

**Comment by AshleyScirra** [comment]
Some of these are good ideas, but we have a separate system for [feature suggestions](https://construct3.ideas.aha.io/). Most of these belong there instead; please only file bugs here if it's a defect. Please also make separate submissions for each suggestion/issue, since otherwise we can't update the status for each individual one.

Just some random thoughts on some of your points:
[This](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321068986) and [this](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321184651) can probably be filed as bugs
[Image editor toolbars](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321177375) used to wrap like you ask for, but there are so many options it used up loads of space on screen and reduced the drawing area to a tiny peep-hole. So this is actually intentional, it's important to save the screen space.
[This](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321490640) should not be necessary because [this](https://github.com/Scirra/Construct-3-bugs/issues/685#issuecomment-321494221) is already supported - just right click in the caption. Although I guess there could be a more visible option for that.

**Comment by rvion** [comment]
I don't feel like pasting there elsewhere, I spend too much time reporting issues for now x) feel free to do whatever you want with them.
