### ISSUE TITLE
android IDE: all downloads report failure (but files download correctly)

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#686]
## Problem description

every downlaod started from chrome (web page or app mode) report a failure at the end 
files are downloaded correctly, but error messages and notifications tell me they are not.

on android / chrome: 

(sorry for the 🇫🇷 )

| error at the bottom of the app: | error in the notification pannel |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/2150990/29084031-0cd5d6f8-7c6b-11e7-9e3d-dbc16e104621.png)    | ![image](https://user-images.githubusercontent.com/2150990/29084046-1b60b1a2-7c6b-11e7-9217-c61f6a48ff35.png)    |

## Attach a .c3p

any project, any file (export, image, etc)

## Steps to reproduce

1. download anything

## Affected browsers

OS: one plus 3T, android 7.1.1, no fancy app, or custom stuff.
regular chrome version, up to date on the play store.

**Comment by shortercode** [comment]
I experience this myself, it's a chrome bug I believe. Works correctly on chrome canary, so hopefully the fix will find it's way to stable at some point.

**Comment by AshleyScirra** [comment]
I can reproduce, but it doesn't happen on Chrome Dev, so it does look like a Chrome bug that's already fixed. FWIW the first time I did a download in Chrome Dev it prompted for storage permission, so I guess the current version of Chrome doesn't have the storage permission so isn't allowed to write the file.
