### ISSUE TITLE
MINOR BUG: "tab" does not unfocus selected items in the layout editor:

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#687]
## Problem description

"tab" does not unfocus selected items in the layout, so moving selection in pane lists keep moving previously selected object in the layout 

![tab-focus-problem](https://user-images.githubusercontent.com/2150990/29085429-92c87b68-7c6f-11e7-8a91-e72aaa685fb3.gif)

📝  if you fix this, can you make it so that when I focus back the layout, the previously edited object gains back focus (if still present) ?

## Affected browsers

* Chrome

**Comment by AshleyScirra** [comment]
Should be fixed in r52.
