### ISSUE TITLE
IDE - CRASH on sequential sprite creation when layout pane is focused

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#688]
## Problem description

I created a sprite, it crashed.

~@AshleyScirra the bug report is succint, but I have no idea what happens, so I'm just opening an issue to paste the stack trace. Is that appropriate ?~

EDIT: after quite a bit of experimentation, I finally found what happens.
EDIT2: You can see the bug in action here: https://github.com/Scirra/Construct-3-bugs/issues/688#issuecomment-321210924, see 
reproduction steps here: https://github.com/Scirra/Construct-3-bugs/issues/688#issuecomment-321051745

## Affected browsers

* Chrome stable

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: crosshair tool already placing @ Error: crosshair tool already placing at r.ǃOEv (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:76999) at O.ǃm_.then (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:17221) at 
Stack: Error: crosshair tool already placing at r.ǃOEv (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:76999) at O.ǃm_.then (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:17221) at 
Construct 3 version: r48
URL: https://editor.construct.net/
Date: Tue Aug 08 2017 20:40:29 GMT+0200 (CEST)
Uptime: 7909.3 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r48

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

------------

> Error: crosshair tool already placing

For the record, It's not the first time I see this error.

**Comment by rvion** [comment]
Ah ! I also had it on mobile after quickly clicking 3 times on the sprite object type in the add object popup.

race condition ?

<details><summary>View details</summary>

Error report information

Type: unhandled rejection
Reason: Error: crosshair tool already placing @ Error: crosshair tool already placing at r.ǃOEv (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:76999) at O.ǃm_.then (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:17221) at 
Stack: Error: crosshair tool already placing at r.ǃOEv (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:76999) at O.ǃm_.then (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:17221) at 
Construct 3 version: r48
URL: https://editor.construct.net/
Date: Tue Aug 08 2017 18:56:20 GMT+0200 (CEST)
Uptime: 210 s

Platform information

Browser: Chrome
Browser version: 59.0.3071.125
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Android
Operating system version: 7.1.1
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2.625
Logical CPU cores: 4
User agent: Mozilla/5.0 (Linux; Android 7.1.1; ONEPLUS A3003 Build/NMF26F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36
C3 release: r48

WebGL information

Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Qualcomm
Renderer: Adreno (TM) 530
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_atc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by rvion** [comment]
wow, this one is tricky, but I can reproduce and I think I know what is going on 
I'll try to note down how I reproduce it.

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: crosshair tool already placing @ Error: crosshair tool already placing at r.ǃOEv (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:76999) at O.ǃm_.then (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:17221) at 
Stack: Error: crosshair tool already placing at r.ǃOEv (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:76999) at O.ǃm_.then (https://editor.construct.net/r48/components/editors/layoutView/layoutView.js:1:17221) at 
Construct 3 version: r48
URL: https://editor.construct.net/
Date: Tue Aug 08 2017 20:49:49 GMT+0200 (CEST)
Uptime: 239.7 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r48

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by rvion** [comment]
okay, so here is it:

full repro : https://giphy.com/gifs/xT39CTRqC7Roetlcsw

1. you need to focus the layout editor
2. add a sprite as in the above git
3. the layout is expecting you to click on it to add the first instance. => DONT click it.
4. ⚠️  note that the layout editor believes that the mouse is pressed: the layout pane follows the mouse. I think some even has been either fired programatically, or catched unintentionally.
5: add a new sprite right away without doing any left click (right click on the Object types menu)
6: ...
7. crash

**Comment by rvion** [comment]
ah, the animated gif above is not the right one, I'll try to fix the link :(

**Comment by rvion** [comment]
![full-bug](https://user-images.githubusercontent.com/2150990/29116044-e6681c26-7cf9-11e7-8739-3e5067c723c1.gif)

**Comment by AshleyScirra** [comment]
Should be fixed in r52.
