### ISSUE TITLE
Left-click drag + Middle-click crash

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#69]
## Problem description

Highlight on layout view, while left-click is still down, do a middle-click.

## Steps to reproduce

1. Click and drag using left-click on layout view.
2. While left-click is down, click the middle-button.

## Observed result

Crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r17/main.js, line 2, col 285202
Message: Uncaught Error: pointer already captured
Stack: Error: pointer already captured at Function.ǃRq (https://editor.construct.net/r17/main.js:2:285208) at r.ǃoI (https://editor.construct.net/r17/components/editors/layoutView/layoutView.js:1:37571) at Array.ǃRM.u (https://editor.construct.net/r17/components/editors/layoutView/layoutView.js:1:37057) at ǃE.Event.ǃbvx.ǃbvk (https://editor.construct.net/r17/main.js:2:283167) at window.ǃEa.dispatchEvent (https://editor.construct.net/r17/main.js:2:281748) at window.ǃEa.ǃoI (https://editor.construct.net/r17/components/editors/layoutView/layoutView.js:1:13473) at HTMLDivElement.ǃm.ǃE.ǃY.ǃE.ǃB.ǃp.$ (https://editor.construct.net/r17/components/editors/layoutView/layoutView.js:1:3903) at HTMLDocument. (https://editor.construct.net/r17/main.js:2:278431)
Construct 3 version: r17
URL: https://editor.construct.net/index.html
Date: Thu Apr 13 2017 20:06:40 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 5.1 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r18.

**Comment by jaydonteh** [comment]
Unfortunately, if it was done in quick succession it will still crash. This time, a different crash log report.

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r18-2/main.js, line 2, col 285067
Message: Uncaught Error: pointer already captured
Stack: Error: pointer already captured at Function.ǃDU (https://editor.construct.net/r18-2/main.js:2:285073) at u.ǃQA (https://editor.construct.net/r18-2/components/editors/layoutView/layoutView.js:1:40845) at u.ǃA_ (https://editor.construct.net/r18-2/components/editors/layoutView/layoutView.js:1:51688) at Array.ǃAM.A (https://editor.construct.net/r18-2/components/editors/layoutView/layoutView.js:1:50813) at ǃs.Event.ǃEWN.ǃEWU (https://editor.construct.net/r18-2/main.js:2:283033) at window.ǃaM.dispatchEvent (https://editor.construct.net/r18-2/main.js:2:281614) at window.ǃaM.ǃA_ (https://editor.construct.net/r18-2/components/editors/layoutView/layoutView.js:1:14231) at HTMLDocument.ǃAM.P (https://editor.construct.net/r18-2/components/editors/layoutView/layoutView.js:1:2396) at HTMLDocument. (https://editor.construct.net/r18-2/main.js:2:278297)
Construct 3 version: r18.2
URL: https://editor.construct.net/index.html
Date: Thu Apr 13 2017 23:26:20 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 16.7 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by jaydonteh** [comment]
[r18.2] For the sake of easier reproduction, middle-click and left-click at the same then drag.

**Comment by AshleyScirra** [comment]
@jaydonteh can you file a new report? Looks like different cases of a similar problem.
