### ISSUE TITLE
Cannot Export Project

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#690]
## Problem description

Unable to export project to html or nwjs.  Chrome crashes whenever I try just saying something went wrong.  Attempted in-cognito mode too.

## Attach a .c3p

[Bitmen.zip](https://github.com/Scirra/Construct-3-bugs/files/1209859/Bitmen.zip)

## Affected browsers

* Chrome: yes

**Comment by shortercode** [comment]
When you say chrome crashes do you mean the tab crashes or the C3 error dialog appears?

**Comment by 8bitThirsty** [comment]
Chrome goes to their blank opps...something went wrong screen.  Like this one https://www.xtremerain.com/wp-content/uploads/2015/10/screenshot-aw-snap-error-chrome.jpg

**Comment by shortercode** [comment]
Ah okay thanks, just thought I'd check. I expect this is either a chrome bug or your running out of memory. How much memory does your system have? Do you have any of the chrome unstable releases (canary, beta, etc. ) on your machine to test against?

**Comment by 8bitThirsty** [comment]
My system has I believe 8gigs of ram and I wasn't running anything else.  I was on chrome beta at one point because it was necessary to launch C3 early on but I can't remember.  I will get definite answers when I can but it will be probably 12 hours from now.

**Comment by AshleyScirra** [comment]
Possible duplicates: #173, #359 
It depends on the Chrome version - please always include the information we ask for, this includes the browser version and helps us diagnose the issue.
I'd guess this is an already-fixed memory leak that will work with Chrome 61+.

**Comment by 8bitThirsty** [comment]
It's Version 60.0.3112.90 (Official Build) (64-bit)  Do I need to run chrome beta to export my project now?  How did this become a chrome issue when it worked so many times before?

**Comment by AshleyScirra** [comment]
Memory issues can be non-deterministic. Can you try Canary or Beta and check if it works there? They'll make their way to the stable channel in due course.

**Comment by 8bitThirsty** [comment]
Tested again with Version 61.0.3163.39 (Official Build) beta (64-bit) and it worked.  Closing the issue and I will stick to chrome beta for now.  I was a little worried my project file had some issues since I have been working on it since the beta jam across so many different versions.
