### ISSUE TITLE
MOBILE IDE: selecting the last menu item of several popups is buggy

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#691]
## Problem description

selecting the last menu item of several popups is often buggy

## Attach a .c3p

blank new project

## Steps to reproduce

1. create a blank new project
2. go to even sheet 1
3. add event > system > scroll to the bottom
4. double tap the Every X second => 

60% of cases:
  🔴  screen flickers and condition is not create
20% of cases:
  🔶  popup closes, condition is created
20% of cases
  🔸  popup closes, condition is created with default values for each variable

highly reproductible

-----------

same for adding actions

![image](https://user-images.githubusercontent.com/2150990/29100690-73dad55a-7cad-11e7-8afd-25cd8f90b016.png)

Android Chrome

**Comment by AshleyScirra** [comment]
Hmm, looks like it's bringing up the next dialog but the touch is directly over the "Back" button which accidentally gets triggered as well.

**Comment by AshleyScirra** [comment]
Should be fixed in r52.
