### ISSUE TITLE
image editor bug: drawable area is sometimes cropped on first sprite edition

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#693]
## Problem description

drawable area is sometimes cropped on first sprite edition:

![image editor bug](https://user-images.githubusercontent.com/2150990/29110278-71210c06-7ce6-11e7-9f3d-357eb3d37f9c.gif)

## Attach a .c3p

blank .c3p

## Steps to reproduce

1. create an image (double click on layout, write "spr", press enter)
2. quickly click somewehere in the editor (the brush tool need to be preselected)
3. sometimes, it does what you see on the above gif

to fix it, just switch tools, or re-open the sprite editor

* stable Chrome desktop

**Comment by rvion** [comment]
@DiegoScirra  this one is hard to reproduce, but I saw it 4 or 5 times, on 2 different devices, so it's reproductible-ish

**Comment by rvion** [comment]
additional infos: 
 
 - the locked part was always on the right
 - the locked part was not always the same size

**Comment by DiegoScirra** [comment]
Fixed in r50. Thanks for the feedback!
