### ISSUE TITLE
MOBILE IDE  BUG : img editor + tool + left pane (Animation, color) + back button = not good

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#694]
## Problem description

It is possible to persistently lock the image editor when pressing back under some reproductible conditions.
(it happens all the time when I'm editing images on mobile ide)

## Attach a .c3p

any blank project

## Steps to reproduce

1. create a new project
2. create a sprite
3. open the mobile image editor
4. pick the point eitor tool (crosshair)
5. open left panel (slide from left)
6. open the color palette
7. press "back button" = > 🔶  the whole image editor closes
8. open the sprite editor again
9: 🔴  editor is broken: you can't click on tools, you can't click on the image

🔴 🔴  even if you close the project, the image editor is now broken.

🔨  to fix it, you need to re-open the image editor, then re-open the left panel (slide from left), then close it __without__ the back button, by dragging the panel back to the left border

**Comment by rvion** [comment]
related to https://github.com/Scirra/Construct-3-bugs/issues/681

**Comment by DiegoScirra** [comment]
Fixed in r50.
