### ISSUE TITLE
Video won't play on Android with Pad

### ISSUE THREAD

**Issue by Jau-Al** [Scirra/Construct-3-bugs#695]
Hello,

## Problem description
If you make a button pressed event that triggers a video "Play" action, nothing happens. You HAVE to touch the screen. Which is... useless / absurd lol

## Steps to reproduce

1.Put a video
2.Make an event on On gamepad 0 any button pressed
3.Add a Play action

## Observed result

black screen
You have to touch the screen to play. Pretty unfitting for a gamepad / TV use lol.

## Expected result

Play ? lol

## Affected browsers

Android

**Comment by AshleyScirra** [comment]
It's an issue with Chrome for Android: it requires a "user gesture" (i.e. input event) to start media playback, but Gamepads never count. So you can't start media playback via gamepad. I filed a Chrome bug for this over two years ago, unfortunately no progress yet: https://bugs.chromium.org/p/chromium/issues/detail?id=454849
Follow up on the Chrome bug since there's nothing we can do about this.

**Comment by Jau-Al** [comment]
They say you can force it for webview. : https://bugs.chromium.org/p/chromium/issues/detail?id=728330&can=2&q=728330&

https://developer.android.com/reference/android/webkit/WebSettings.html#setMediaPlaybackRequiresUserGesture(boolean)

**Comment by Jau-Al** [comment]
Enable autoplay of videos in cordova for android :
https://gist.github.com/blairvanderhoof/9380545

**Comment by Jau-Al** [comment]
Cordova plugin : 
https://github.com/simplec-dev/AndroidMediaGestureSetting

**Comment by Jau-Al** [comment]
I don't understand exactly the reasons but this is crazy... Could you please add some information in C3 so people know we must trigger a layout change and add the video on the new layout with auto-play ?

Thanks for your great work !

**Comment by AshleyScirra** [comment]
It's [already documented](https://www.scirra.com/manual/181/video).

**Comment by Jau-Al** [comment]
Not exactly. It doesn't tell people to use a new layout with the video in autoplay mode to start it using a gamepad.
Thanks anyways ;-)
