### ISSUE TITLE
Crash when opening Tilemap window

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#70]
## Problem description

Crash when opening Tilemap window after the restricted free edition dialogue of "Find all references..." is closed.

## Steps to reproduce

1. Create a sprite.
2. Right-click it and click "Find all references...".
3. Close the restricted free edition dialogue.
4. Go to Menu -> View -> Bars -> Tilemap Bar (Assuming you have close it prior to this step. If not, you just repeat this step twice to close and re-open).

## Observed result

Crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: TypeError: Cannot read property 'selection' of undefined
Stack: TypeError: Cannot read property 'selection' of undefined at l.window.ǃ$V.ǃbnT (https://editor.construct.net/r17/components/bars/tilemapBar/tilemapBar.js:1:16920) at Function.ǃac (https://editor.construct.net/r17/components/bars/tilemapBar/tilemapBar.js:1:4123) at g (https://editor.construct.net/r17/components/misc/mainMenu/mainMenu.js:1:6597) at Promise () at ǃlG.ǃl$.ǃ$E (https://editor.construct.net/r17/components/misc/mainMenu/mainMenu.js:1:6394) at d.ǃEz (https://editor.construct.net/r17/components/misc/mainMenu/mainMenu.js:1:6995)
Construct 3 version: r17
URL: https://editor.construct.net/index.html
Date: Thu Apr 13 2017 20:16:12 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 69 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r19.
