### ISSUE TITLE
"For each" issue with instance variables

### ISSUE THREAD

**Issue by yojona** [Scirra/Construct-3-bugs#703]
## Problem description
I am trying drop an event below a "For each" event and I get this:
"You can't drop events here because: Unknown expression "startx..."

But if I create the event manually (Right click, Create sub-event, same evaluation), there is no problem.

## Attach a .c3p
[Flappy Bird.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1215784/Flappy.Bird.c3p.zip)

## Steps to reproduce

1. Drag event.
2. Drop below "for each" event.

## Observed result

![Event sheet screenshot](https://i.snag.gy/WOG25X.jpg)

**Comment by AshleyScirra** [comment]
Can't reproduce here. Please remember to file clear bug reports, I'm missing a lot of information, e.g.:

- which version of C3 did you test?
- which event are you dragging exactly?
- are you dropping the event adjacent to the 'for each' event or as a sub-event?

I tried several combinations and it always worked.
