### ISSUE TITLE
Tilemap Bar doesn't show tile collision poly outlines

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#708]
In C2, hovering a tile with a collision poly in the tilemap bar showed its collision poly outline on the tile. This is missing in C3.

There should probably be more items in the context menu as well, such as "Edit tile collision poly" and the zoom options.

**Comment by AshleyScirra** [comment]
Some extra minor feedback:

- the mirror/flip status in the footer is redundant if you use button states on the toolbar
- the browser prompts for permission if you try to download more than one file at a time, so the export TMX option should probably just download a zip of the files necessary instead of downloading two files

**Comment by DiegoScirra** [comment]
Added most of this to r50.

Except for

- mirror/flip status in the footer is redundant if you use button states on the toolbar

I'll create a different issue for that one.
