### ISSUE TITLE
Viewport limits don't show on stage

### ISSUE THREAD

**Issue by Loughfinn** [Scirra/Construct-3-bugs#71]
## Problem description
In C2, when layout is bigger than viewport size, viewport limits appear as a dotted rectangle. 
In C3, on Mac, Chrome r57, it doesn't work. Limits don't show.

## Attach a .c3p
Never works, whatever the .c3p

## Steps to reproduce
Start a new project, open a existing project, it never works.

## Observed result
No viewport limits on screen

## Expected result
Like in C2, I expect to se the viewport limits shown on screen as a dotted rectangle. 
## Affected browsers

* Chrome: yes
* Firefox: na
* Edge: na
* Safari: na

## System details
MacBook pro, El Capitan 10.11.6, Chrome r. 57

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 0.800000011920929
Logical CPU cores: 4
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 82 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

[https://www.dropbox.com/s/ucnd0rzu3qi47nn/Capture%20d%E2%80%99%C3%A9cran%202017-04-13%20%C3%A0%2013.41.58.png?dl=0](url)

**Comment by jaydonteh** [comment]
Maybe adding extra info to the report might help:

*Go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

**Comment by AshleyScirra** [comment]
Yes, please provide all information here, and include the screenshot you previously provided so we can track everything in one place here.

**Comment by AshleyScirra** [comment]
From your system details it looks like you've zoomed out to smaller than 100% zoom. Does restoring 100% zoom fix it?

**Comment by Loughfinn** [comment]
I've set stage zoom at 100% and nothing happens

**Comment by Loughfinn** [comment]
You're right ! That's it. If you can make it work with different screen zoom, that would be amazing (and allow me to compensate the bad confort of working on a laptop screen)

**Comment by AshleyScirra** [comment]
Verified that at 80% zoom the lines disappear. Will look in to this.

**Comment by AshleyScirra** [comment]
Alright, should be fixed in the next build. Thanks for the report!

**Comment by Loughfinn** [comment]
You're welcome. You're doing a great job ! C3 looks amazing so far
