### ISSUE TITLE
Z Order bar doesn't open in subset mode

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#710]
If you right-click an object and choose "Open Z Order bar", it opens in full mode, rather than subset mode. You have to deselect and reselect the object to get it to go in to subset mode, which it should have started with.

**Comment by AshleyScirra** [comment]
It also doesn't display the selected instances in bold, which C2 does.

**Comment by AshleyScirra** [comment]
Double-clicking an object in the Z Order bar should be a shortcut for flashing the instance like it is in C2.

**Comment by DiegoScirra** [comment]
Added all this stuff to r50
