### ISSUE TITLE
Bookmarking global variable lists it as by event -1

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#711]
Open Space Blaster and bookmark the Score variable at the top of Game Events. The Bookmarks Bar lists it as by event -1. It should say by event 1. (It's an edge case where there is no event before it, so the event by it must be the next one.)

IIRC there are already some methods to get the adjacent event while handling these edge cases.

**Comment by DiegoScirra** [comment]
A case of an < instead of an <=

Fixed in r50.
