### ISSUE TITLE
No internet no construct

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#713]
## Problem description

Even though I've heard C3 is supposed to work for 7 days without internet, this was not the case.
The image below represents C3 without a net connection.

## Attach a .c3p

![image](https://user-images.githubusercontent.com/7268697/29249552-1b30e918-803a-11e7-92ee-9cced5d8ba14.png)

## Steps to reproduce

1. cut your internet
2. load C3 previously downloaded and "ready to work offline"

## Observed result

C3 wont load

## Expected result

C3 to load

## Affected browsers

* Chrome: yes
## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.90
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
C3 release: r48

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 319 mb (4.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here:

1. Open a new incognito window
2. Load C3; wait for "offline ready"
3. Disable network adapter so no internet connection available
4. Reload incognito window

C3 still starts up fine.

I'd guess somehow it failed to cache the first time around, but without a way to reproduce there's nothing much we can do about it.

**Comment by JeFawk** [comment]
I tried the same, but instead of reloading it I closed it. It didn't work, it was saying no internet connection. I was hoping it would load the app from the cache.

In case it does not work like that, I don't see much use of this offline feature if it can't be started if the computer is offline without a C3 tab opened to begin with.

**Comment by AshleyScirra** [comment]
If you close an incognito window it deletes all saved data - that's the point of incognito windows. So if you open a new incognito window while offline, it definitely will not work, as per the design of incognito mode. You have to reload with the same window open for it to be able to use the previous tab's saved data.
