### ISSUE TITLE
Updated to r48, can't open project saved in previous build.

### ISSUE THREAD

**Issue by StefanSava** [Scirra/Construct-3-bugs#714]
## Problem description

Can't open project that was saved with previous build of construct, before r48.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.

## Expected result

Open as usual.

## Affected browsers

Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: name is reserved @ Error: name is reserved at A.O (https://editor.construct.net/r48/main.js:61:143829) at A (https://editor.construct.net/r48/main.js:61:151500) at Function.ǃE.ǃB (https://editor.construct.net/r48/main.js:2:204449) at window.ǃAeO.ǃeS (https://editor.construct.net/r48/main.js:61:406473) at n.ǃOlH.then (https://editor.construct.net/r48/main.js:61:162954) at 
Stack: Error: name is reserved at A.O (https://editor.construct.net/r48/main.js:61:143829) at A (https://editor.construct.net/r48/main.js:61:151500) at Function.ǃE.ǃB (https://editor.construct.net/r48/main.js:2:204449) at window.ǃAeO.ǃeS (https://editor.construct.net/r48/main.js:61:406473) at n.ǃOlH.then (https://editor.construct.net/r48/main.js:61:162954) at 
Construct 3 version: r48
URL: https://editor.construct.net/index.html
Date: Mon Aug 14 2017 09:10:49 GMT+0300 (E. Europe Daylight Time)
Uptime: 12.6 s

Platform information
Browser: Chrome
Browser version: 59.0.3071.115
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
C3 release: r48

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by StefanSava** [comment]
I can't attach a cp3 because it is a big project and i'd rather keep it private.

**Comment by AshleyScirra** [comment]
Sorry, nothing we can do to help unless you can follow the bug report guidelines. Revert to a backup. If you don't have one, congratulations on learning to keep backups, and you can send your project to ashley@scirra.com if you want me to try to recover it (but I can't guarantee anything).
