### ISSUE TITLE
Editing tile image adds it to project spritesheets

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#717]
## Problem description

Editing a tile image adds it to the spritesheet, as if a sprite was added to the project.

## Attach a .c3p

Open the built-in 'Tilemap' example

## Steps to reproduce

1. View project spritesheets and verify just the tilemap image is there
2. In the tilemap bar, edit the cactus tile by double-clicking it
3. Make some trivial change and close the image editor
4. View the spritesheets again

## Observed result

A second cactus was added as its own sprite to the spritesheet.

## Expected result

No modification to the spritesheet - the tilemap image should update, without adding any new images.

Closing and re-opening the project removes the added tiles, but they shouldn't be added in the first place, something funny is going on there.

**Comment by DiegoScirra** [comment]
This must be the temporary animation frame I create to edit a single tile. I must have missed something when it is released.

**Comment by DiegoScirra** [comment]
Fixed in r50.

The temporary Animation was never released.
