### ISSUE TITLE
Localisation: Setting time zone: Wrong hint/Wrong region name

### ISSUE THREAD

**Issue by albertvgrigoryan** [Scirra/Construct-3-bugs#718]
## Problem description

*On "construct.net" I want to select my region, which is "Armenia". In the region selection, Armenia is enlisted in Asia, which is wrong and should be transferred to Europe. When I select "Armenia", it shows up as "Hajastan", whereas it must be the same name "Armenia". And last, when "Armenia" is selected and I want to set my Time-zone in Personal details, I must receive a correct hint message, which is currently wrong.*

## Steps to reproduce

1. Go to construct.net, change region (bottom of the page)
2. Set country/region to "Armenia" (Asia)
3. Go to Account/Personal details
4. See Localisation section, Time-zone setting.
5. Set timezone to Yerevan

## Observed result

*"Armenia" is enlisted in Asia, when setting region. "Hajastan" is shown up in region setting, when "Armenia" selected (bottom of the page). When in Personal details/Localisation/Time zone setting, a wrong hint is shown "We think your timezone should be Azerbaijan Standard Time". The hint message does not disappear, after I select Yerevan for my Time-zone*

## Expected result

*"Armenia" shall be enlisted in Europe, when setting region. "Armenia" shall be shown up in region setting, when "Armenia"  selected (bottom of the page). When in Personal details/Localisation/Time zone setting a proper hint shall be shown "We think your timezone should be Armenian Standard Time". the hint mesage shall disappear, after I select Yerevan for my Time-zone*

## Affected browsers

* Chrome: yes

**Comment by TomGullen** [comment]
Fixed for next upload.
