### ISSUE TITLE
No option of logging out of cloud storage services

### ISSUE THREAD

**Issue by simoneddeland** [Scirra/Construct-3-bugs#719]
## Problem description

When browsing your available cloud projects there is no option to log out of the current cloud service. This is a problem when using a shared/public computer since the project files might be accessed by someone who shouldn't have access to them. There are ways to delete browser data/revoke access if you log in to a cloud service, but a simple "Log out" button/link would be very convenient.

![logout needed](https://user-images.githubusercontent.com/12908966/29334382-81b017bc-8207-11e7-9cb4-7e52f0e320b6.png)
This windows should have a "Log out" link/button.

## Attach a .c3p

Not a .c3p-specific problem.

## Steps to reproduce

1. Sign in to a cloud service while saving a project.
2. Log out your current Construct 3 user.
3. Browse your cloud projects.

## Observed result

No log out option.

## Expected result

A button/link to log out of the current cloud service.

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details
x

**Comment by shortercode** [comment]
Yup sounds pretty reasonable, I'll look into implementing it when I get a chance. It's worth pointing out that any other browser synced information ( browser saves, recent exports, UI state ) will still be available. So if your worried about project security incognito mode is your friend. We'll likely make tweaks to those over time, but I think being able to log out of cloud services is a good start.

**Comment by shortercode** [comment]
@simoneddeland Okay I've just checked in this feature, should appear in r51. I've tried my best to level out the differences between the services but it's still pretty variable. But at least it allows you to sign out of the service on C3 now.

Both Dropbox and Google Drive won't sign you out of their websites, so if you want to prevent someone just reauthenticating you need to sign out of that as well ( as they won't ask for a password if your signed in on the website ). The behaviour will probably vary depending on your account settings
