### ISSUE TITLE
Severe Sprite on layout view bug with potential crash

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#72]
## Problem description

Seems semi-transparent for all new create sprite objects.

## Steps to reproduce

1. Open any existing projects, or a new project.
2. Create a new Sprite object.
3. Doodle or paint it colour.

## Observed result

It just shows a semi-transparent Sprite object and sometimes got a crash for creating a new object.

## Expected result

Display normally and no crash trying to create Sprite objects.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r18/main.js, line 2, col 227646
Message: Uncaught Error: animation frame has no content
Stack: Error: animation frame has no content at ae.ǃH_S (https://editor.construct.net/r18/main.js:61:196884) at ae.ǃDB (https://editor.construct.net/r18/main.js:61:200642) at ǃWt.ǃAHI.ǃWt.ǃTS (https://editor.construct.net/r18/main.js:63:31897) at ǃWt.ǃAHI (https://editor.construct.net/r18/main.js:63:40365) at Function.ǃH.ǃM (https://editor.construct.net/r18/main.js:2:227632) at Function.ǃea (https://editor.construct.net/r18/main.js:63:325436) at Function.ǃAow (https://editor.construct.net/r18/main.js:63:325294) at Function.ee.ǃHXT.ǃAmf (https://editor.construct.net/r18/main.js:63:331039) at ee.ǃAFc.ǃADB (https://editor.construct.net/r18/main.js:63:244479) at Array.ǃAD_.ie (https://editor.construct.net/r18/main.js:63:237000)
Construct 3 version: r18
URL: https://editor.construct.net/index.html
Date: Thu Apr 13 2017 21:13:41 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 428.2 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
The bug about the changes made in the animations editor not being reflected in the layout view is fixed.

I couldn't find any crashes though.

**Comment by AshleyScirra** [comment]
r18.2 is out, please check it again.

**Comment by jaydonteh** [comment]
Its now working as usual.
