### ISSUE TITLE
[UWP] No test ads displayed 

### ISSUE THREAD

**Issue by deerta76** [Scirra/Construct-3-bugs#720]
## Problem description
This problem has been on going since Construct 2 r228 and above and including Construct 3. When trying to test ads for UWP no ads appear

*Enter a concise description of your problem here*
no test ads appear for UWP app.

## Attach a .c3p see attached

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Use a stock template provided with Construct 3 "Flying along template"
2. add to start of layout Pubcenter show banner ads (pick any size and location)
3.export to Visual studio 2015 community with the latest update
4. add reference for Microsoft Advertising SDK for JavaScript
5. Run local machine 
6. notice no test ads a appear (this has been happening since r228 in C2

## Observed result

*What do you see happen?*
no adds appear
however looking at the index.html file its missing the ad unit code 
DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<title>Flying along template</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no"/>

	<link rel="icon" type="image/png" href="icons/icon-256.png" />

<link href="WinJS/css/ui-dark.css" rel="stylesheet"/>
<script src="WinJS/js/base.js"></script>
<script src="WinJS/js/ui.js"></script>

<link rel="stylesheet" href="style.css"/>

</head>
<body>
<div id="fb-root"></div>

<script src="c2runtime.js"></script>
<script src="start.js"></script>

</body>
</html>

## Expected result
Show test ads
*What did you expect to happen instead?*
no ads appear

## Affected browsers
n/a
* Chrome: /no
* Firefox: /no
* Edge: /no
* Safari: 
[Flying along template.zip](https://github.com/Scirra/Construct-3-bugs/files/1228247/Flying.along.template.zip)
/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

Platform information
Browser: Chrome
Browser version: 60.0.3112.101
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
C3 release: r49

Local storage
Storage quota (approx): 29 gb
Storage usage (approx): 61 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce 8400GS Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 16000 Hz
Output channels: 1
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
I've made some changes in the next build of C3 that ought to help - C3 wasn't actually exporting all the necessary script and HTML :P Once you export you also have to add a reference to the Microsoft Advertising SDK (the latest version is 10.0 from August), and also manage NuGet packages and add WinJS. If it works in C3 I'll backport the changes to C2.

**Comment by deerta76** [comment]
Hi Ashley,

I tried on the latest build of C3 and I still do not see any test ads appearing. I have attached a copy of the C3 capx that I am using

[c3ads.zip](https://github.com/Scirra/Construct-3-bugs/files/1431097/c3ads.zip)

**Comment by AshleyScirra** [comment]
This is an old issue and I don't think we'll be able to make progress on it - I'd suggest contacting Microsoft for further support on this since pubCenter is their service.

**Comment by deerta76** [comment]
This isn't a Microsoft Issue. I even manually added the adcontrol Microsoft uses and still no banner ads. I can now get video ads with exporting with Construct but thats it. This was working fine up until R227. after that version no banner ads
Joe 

    On Monday, November 19, 2018, 10:58:30 AM CST, Ashley (Scirra) <notifications@github.com> wrote:  
 
 
This is an old issue and I don't think we'll be able to make progress on it - I'd suggest contacting Microsoft for further support on this since pubCenter is their service.

**Comment by AshleyScirra** [comment]
It's probably this change from r228:

> Windows 10 apps: now no longer depends on WinJS library, which makes apps a bit smaller and more efficient

You might need to just add back the WinJS dependency.
