### ISSUE TITLE
Tilemap picking by overlap

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#723]
## Problem description
I had a rather specific idea where I needed to test if a tilemap is beeing overlapped by a sprite on a sprites image point. I tried to do this using "Pick by overlapping point" However, this caused the event to fire all the time for overlapping the tilemap object, even if the tiles were empty. In comparison, using collision or even normal "is sprite overlapping tilemap" it works fine. I still needed the specific overlap on image point (and overlap at offset is not an option in my case) The same thing also happens in C2.

This seems less of an actual bug, but to me it´s not a logical behavior to suddenly stop ignoring empty tiles (and also tile colission polygons)

While I´m at it, I think the tilemap plugin could use some more love regarding setting colission on/off for specific tiles, making it easier to pick certain tiles (on colission with tile XYZ), etc... I know there are other priorities now, just needed to put it out there. <3

## Attach a .c3p
[tilemap picking.zip](https://github.com/Scirra/Construct-3-bugs/files/1231472/tilemap.picking.zip)
Move sprite with arrow keys. It changes to green when it detects the overlap. You can switch bottom left between normal overlap and picking tilemap at image point.

Edit: Just a quick note, it´s an actual .zip, not a renamed c3p

## Steps to reproduce

1. Pick tilemap by overlapping point
2. Event fires even on empty tiles
3. :(

## Observed result
The event is called because of an overlap of the tilemap object, not of the individual tiles. So even empty tiles count as part of the tilemap object and detect the overlap.

## Expected result
Should use the individual tiles collision polygon (and empty tiles as no collision)

## Affected browsers
Not browser dependent.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.90
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2.5
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
C3 release: r49

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 45 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

Cheers, keep up the great work scirra-team!

**Comment by AshleyScirra** [comment]
Thanks, fixed for r52.
