### ISSUE TITLE
debug resize

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#725]
## Problem description

Some time variable names are long, the variable vaue can't be seen because it its overlapped by another panel, resizing does not help.

[img]https://www.dropbox.com/s/kpydcmqj3cmlpuw/debug.gif?raw=1 [/img]

https://www.dropbox.com/s/kpydcmqj3cmlpuw/debug.gif?dl=0

and

you can see in screen shot below values clearly cut off and hidden.

https://www.dropbox.com/s/5ode82x9bo5mchm/Screen%20Shot%202017-08-19%20at%2011.37.21.png?raw=1

## Attach a .c3p

n/a, any long variable name will do.

## Steps to reproduce

1. add longish variable name
2.preview in debug

## Observed result

variable value column is cut off by next row.

## Expected result

You should be able to see the variable values. Being able to adjust/ slide/ resize value box over variable name would solve issue.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Made the labels wrap in r52 which should fix this.
