### ISSUE TITLE
clearly identify variable types in pulldown menu

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#727]
## Problem description

when selecting an objects variable can it be identified which are values and which strings (perhaps have it in brackets at the end of the variable name in a differnt colour), and also which are family variables, as these can be accessed in the object as well.

## Attach a .c3p

n/a

## Steps to reproduce

1.
2.
3.

## Observed result

https://www.dropbox.com/s/rey6fsjd7snjv61/Screen%20Shot%202017-08-13%20at%2014.29.40.png?raw=1

## Expected result

it would be good for ease of use to identify values, strings, and family variables.

## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Added group categorisation by family, and variable types, for r54.
