### ISSUE TITLE
Minified script breaks the game

### ISSUE THREAD

**Issue by arcadehistory** [Scirra/Construct-3-bugs#729]
Minified script breaks the loading of the game.

## Description
When exported as a minified script, this project don't load (HTML5). It works fine without minified script.

## C3P file (+required addon)
https://www.arcade-history.com/temp/asteroidsX.zip

## Steps to reproduce
1. Open the project,
2. Export as a HTML5 game with minified script
3.  Load the game in the browser: 

## Observed result
Black Screen.

## Expected result
Normal loading.

## Affected browsers
* Chrome: yes.
* Firefox: yes.
* IE: yes.

## System details
Intel I3, 8Go Ram, SSD, Windows 10

**Comment by arcadehistory** [comment]
Please note the minified project works fine when exported in C2.

**Comment by Scott943** [comment]
Yeah this still happens for me - think this is the same problem as #560.

**Comment by AshleyScirra** [comment]
The project uses a third-party addon ("Extra expressions"). Closing, please see the bug report guidelines. It could be this addon breaking export.
