### ISSUE TITLE
Prior select tools activated on object creation

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#73]
## Problem description

Again another bug on the Animation editor. Used tools or previously selected tool will now engage/activated on new creation of an object that uses the animation editor.

## Steps to reproduce

1. Create a sprite.
2. Select any draw tool and colour.
3. close animation editor and create another sprite or object that uses the animation editor.

## Observed result

Tool engaged pr activated straightaway as tho I clicked on the canvas with the selected tools.

## Expected result

Don't activate tools on initial creation.

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed.
