### ISSUE TITLE
can't see variable descriptions

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#730]
## Problem description

Can you add variable description in the variable properties box for clarity.

## Attach a .c3p

n/a

## Steps to reproduce

1.
2.
3.

## Observed result

cant see variable descriptions

https://www.dropbox.com/s/so6ogm5a7rgc5bd/Screen%20Shot%202017-08-20%20at%2014.14.51.png?raw=1

## Expected result

should be able to see variable descriptions.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Added for r52.
