### ISSUE TITLE
Platform behaviour recognizing the "roof" with "is by wall left/right".

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#731]
## Problem description

Everytime i jump with the platform behaviour, the "is by wall" function is triggered by the "roof", even if there's no walls.

## Attach a .c3p

[Is by wall problem.zip](https://github.com/Scirra/Construct-3-bugs/files/1239228/Is.by.wall.problem.zip)

## Steps to reproduce

1. Jump towards the roof
2. Wait for the character to reach the roof
3. Notice that anything can be triggered by the "is by wall" function.

## Observed result

Anything can be triggered by the "is by wall" function, even if there's no walls.

## Expected result

The "is by wall" function to be triggered only if there are walls.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by flipog** [comment]
I'm using "TheObject.Platform.VectorY = 0" along with the NOT version of "Is on floor" to identify ceilings, hope it helps someone until it's solved.

ps: This rule may also recognize a brief moment between the jump and the fall, so trust it only for collisions.

**Comment by AshleyScirra** [comment]
OK, I've tweaked the detection again and it should be working in all cases for r54 (hopefully).

For reference the fix to #621 accidentally caused this.
