### ISSUE TITLE
Setting animation speed to a negative value doesn't make it reverse in playback, instead it stops

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#733]
## Problem description

When you set the speed of an animation to a negative value in the events it treats it as 0, when setting the value below 0 in the image editor it will set it to 0.

## Steps to reproduce

1. Set the animation speed of an animation to -20

## Observed result

The animation stops, as if its at 0 speed.

## Expected result

It should reverse in playback, similar to the ping pong setting. 

For instance, a -20 speed animation should play the same as a +20 speed animation with the only difference being that it's doing the frames in the reverse order.

**Comment by AshleyScirra** [comment]
Closing, please see the bug report guidelines (attach a project)
