### ISSUE TITLE
Html export error when using expression System.ProjectVersion

### ISSUE THREAD

**Issue by NitidOnline** [Scirra/Construct-3-bugs#736]
## Problem description

IDE brokes when i try to export if expression System.ProjectVersion is in use.
I used it in a Set Text. I don't know if it happens using it in others places.

## Attach a .c3p

[VersionError.zip](https://github.com/Scirra/Construct-3-bugs/files/1243801/VersionError.zip)

## Steps to reproduce

1. Export as HTML
2. See it crashing ^^

## Observed result

IDE screen becomes red and a Error report show up. I have to restart C3.
The export ends and a zip file is generated.

## Expected result

No crash at all.

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

Error report information
Type: assertion failure
Message: cannot find object class index
Stack: Error at Function.ǃr.ǃgWY (https://editor.construct.net/r49/main.js:2:202883) at r (https://editor.construct.net/r49/main.js:2:172159) at window.assert (https://editor.construct.net/r49/main.js:2:172567) at window.ǃg$X.ǃrQu (https://editor.construct.net/r49/main.js:61:425648) at n.ǃqrW (https://editor.construct.net/r49/main.js:61:352424) at n.ǃrQV (https://editor.construct.net/r49/main.js:61:351988) at window.ǃsf.ǃrQV (https://editor.construct.net/r49/main.js:61:333962) at window.ǃghr.ǃrj$ (https://editor.construct.net/r49/main.js:61:326236) at window.ǃghr.ǃrQV (https://editor.construct.net/r49/main.js:61:316658) at a.map (https://editor.construct.net/r49/main.js:61:285076)
Construct 3 version: r49
URL: https://editor.construct.net/index.html
Date: Wed Aug 23 2017 02:47:41 GMT+0200 (Hora de verano romance)
Uptime: 705.1 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.90
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
User agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
C3 release: r49

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The problem is `System.ProjectVersion` is actually invalid syntax which is accidentally allowed and ends up causing a crash on export. System expressions are used on their own, i.e. simply `ProjectVersion`. In r51 this syntax is disallowed so you cannot cause the problem again, but note you'll need to fix any existing projects using the invalid syntax before using them in r51.

**Comment by NitidOnline** [comment]
Thank you Ashley. Could you check C2 as well? I have a flash remind about a
problem  with this in C2 too.

Keep the good work! This C3 looks great.

Greetings from Galicia.

-RG

2017-08-25 13:49 GMT+02:00 Ashley (Scirra) <notifications@github.com>:

**Comment by NitidOnline** [comment]
You are right. Thank you for check it.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-08-26 15:33 GMT+02:00 Ashley (Scirra) <notifications@github.com>:
