### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#737]
## Problem description

I've all of a sudden gotten this error message when attempting to load C3. I have no new plugins installed and have had no previous issues. Regardless i dissabled them but it did not work.

https://www.dropbox.com/s/lg0c3kcam024r8o/Screen%20Shot%202017-08-23%20at%2016.59.27.png?raw=1

I've tried loading from the desktop icon and from browser tab as well.

## Attach a .c3p

n/a

## Steps to reproduce

try to load C3.

## Observed result

https://www.dropbox.com/s/lg0c3kcam024r8o/Screen%20Shot%202017-08-23%20at%2016.59.27.png?dl=0

## Expected result

C3 to load up.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Can't loadup to paste, but on Chrome for Mac. Version 60.0.3112.101 (Official Build) (64-bit)
</details>

**Comment by jmiller4180** [comment]
I have this issue as well. Tried Chrome , and then tried Canary. Both give the same error after updating to 49

**Comment by mOOnpunk** [comment]
I've tried reverting back to previous versions but still nothing is working.

**Comment by mOOnpunk** [comment]
Since nothing has changed on my system i'm guessing something has happened at the scrirra end?

So i can't use C3 at all until it's fixed.

**Comment by AshleyScirra** [comment]
Can you cut and paste the error message here? We have a tool that can help diagnose errors based on that, but we can't do that from an image.

**Comment by mOOnpunk** [comment]
It won't let me copy and paste because i can't select the text. The cursor has the mac spinning circle. Going into select all and copy and paste doesnt work either. 

How can it suddenly just stop working?

As i said nothing has changed.

**Comment by TheRealDannyyy** [comment]
I guess you guys are fixing the bugs right now. If not, Construct 3 and Construct.net are currently completely down and cannot be accessed anymore. (The offline version doesn't seem to work either.)

**Comment by AshleyScirra** [comment]
Turns out there was a server-side issue in CloudFlare. We made a few tweaks and it looks like it's working my end. Can anyone else confirm? If you still have trouble please try clearing the browser cache.

**Comment by mOOnpunk** [comment]
back up and working now.

**Comment by TheRealDannyyy** [comment]
It still doesn't seem to work despite clearing all the data on my end. It works in incognite mode though.
Am I doing something wrong here @AshleyScirra ?
![del](https://user-images.githubusercontent.com/15656049/29634068-d66b8218-8848-11e7-9052-817f4f22419d.PNG)

**Comment by mOOnpunk** [comment]
worrying that offline mode was also affected.

**Comment by Ind1eed** [comment]
Still doesn't work for me. I cleared my cache like 500 times.

**Comment by AshleyScirra** [comment]
@Ind1eed - this was fixed about a week ago, if you still have an issue please file a new issue following all the guidelines, since by now it's probably unrelated.
