### ISSUE TITLE
Remote Preview on iOS Doesn't Work at All

### ISSUE THREAD

**Issue by AppDude27** [Scirra/Construct-3-bugs#738]
## Problem description

I am creating a fan made project, Nancy Drew Message in a Haunted Mansion Mobile. I have no affiliation with HeR Interactive. This is a fan made project that I am creating for fun and educational purposes.

Whenever I try to use the QR code or link to my game through an iOS device (iPad Air 2, iPhone 5, iPhone 6-7), I get the same error message saying the browser isn't supported. I'm using the Google Chrome iOS app and FireFox iOS app to run the game and am still getting this error message. 

I am not getting this problem at all for Android devices. I have tried Remote Preview with Android tablets and phones and have had no problems at all.

## Attach a .c3p

Below is a link to my project. The project link will expire in 30 days. If it needs to be extended, please notify me and I will extend the the link time.
https://1drv.ms/u/s!AhPyA2qrea__xEpRmlOTkP9-8Dxh

## Steps to reproduce

1. Run a Remote Preview
2. Use an iOS device to scan the QR code or copy and paste the link into your iOS Chrome browser
3. Get an error message

## Observed result

I get an error message saying that my browser isn't supported. Even though it is Chrome or Firefox for iOS.

## Expected result

I expect my game to run normally like it does on the Android version of Chrome.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: n/a
* Safari: n/a

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

n/a

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
iOS 10 does not support WebRTC, which is required for Remote Preview to work. iOS 11 adds it though, and should be out in a couple of months.

Apple ban other browsers on iOS. Chrome and Firefox are just skins for Safari. So trying them is usually no different.

**Comment by AppDude27** [comment]
Hi Ashely,

Thanks for the fast feedback! Good to know! 

Best regards,

Joe Amadeo
