### ISSUE TITLE
Origin indicator not functioning bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#74]
## Problem description

Isn't aligned to the origin set through the animation editor.

## Steps to reproduce

1. Create a sprite object.
2. change the Origin position.
3. close the animation editor.

## Observed result

The sprite isn't adjusted nor the indicator changes position.

## Expected result

The sprite adjusts and the indicator changes position.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Seems to be working OK here, except for issue #72. You can work around the image not showing by trying to change the initial frame in sprite properties, and the image appears. So long as you do that the origin appears to update correctly as well, so I think this might just be a dupe of that bug.

**Comment by jaydonteh** [comment]
Checked, image point is not the problem.
