### ISSUE TITLE
Crash adding new non-layout object (e.g. Array, Dictionary)

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#741]
## Problem description

*Enter a concise description of your problem here*
Error window pops when adding a new object (dictionary, ...)
after test, same thing happens when adding a dictionary or array to a new project

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

[Petrisquare_2017_08_24_17.zip](https://github.com/Scirra/Construct-3-bugs/files/1249564/Petrisquare_2017_08_24_17.zip)

## Steps to reproduce

1. add Dictionary

## Observed result

*What do you see happen?*
Error Window comes up

## Expected result

*What did you expect to happen instead?*
i add a Dictionary

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

{"is-c3-clipboard-data":true,"type":"actions","items":[{"id":"set-eventvar-value","objectClass":"System","parameters":{"variable":"state","value":"0"}}]}

</details>

error window comes up when im adding something new

**Comment by AshleyScirra** [comment]
Looks like it's crashing in UI state, assigning to Diego. This is a pretty bad bug, might need another release tomorrow.

**Comment by AshleyScirra** [comment]
Looked like a simple fix, patched it and leaving open for Diego to review

**Comment by DinoS124** [comment]
Same thing happens to me when I try to add Array.

**Comment by DiegoScirra** [comment]
Yeah, this is currently affecting all object types which don't have an instance in the layout, such as Array or Dictionary.

Fixed in the next release.
