### ISSUE TITLE
Serious 50r Exclusive Tilemap Bug 

### ISSUE THREAD

**Issue by XpMonster** [Scirra/Construct-3-bugs#742]
## Problem description

Whatever was done on r50 about tilemap made it broken.

I suppose this should be a priority №1 to fix considering how many games rely on tilemaps. 

[Download example](https://drive.google.com/open?id=0Bz-IOXMAnpNvdnF5dlFzMi1rNlk)

## Reproduce

If you create two different tilemaps. 

## Observed result

Tilemap places incorrect tiles in editor. When you open the game these blocks would change again and not on the correct ones. 

Sometimes instead of your tilemap - bright squares. That's what I have in my project as of today in all versions. 

## Expected result

Have my old dear tilemap back.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

**Comment by AshleyScirra** [comment]
Can you post an image of what it's meant to look like and what you're actually seeing? If I open the project, it's not obvious what's wrong, or even if it is wrong.

**Comment by DiegoScirra** [comment]
I think there is a problem with the shader. It is not taking the texture rectangle into account properly. It is as if it is always taking information starting from the top left of the sprite sheet.

So it works properly if the tilemap texture is the first image in it's sprite sheet, but in any other case it will draw incorrect things.

**Comment by XpMonster** [comment]
Ashley, I don't think screenshot will help here much, but OK. 

[What I want ](http://i.imgur.com/BfKZSxt.png) & [What I get](http://i.imgur.com/u9qJ1hF.png)

Just try working with two different tilemaps and you will see that one works incorrectly sometimes only in editor, sometimes both in editor and project. I'm observing different results from time to time. 
From what Diego said seems like I certainly won't find any work around for myself until it's fixed.

Can focus on drawing sprites now. I'll draw C3 logo for my project to make spiritual sacrifice of time to help you fix tilemaps faster xD

**Comment by ArsCreativa** [comment]
Getting same problem here.
I'm using two tilesets on the same layout, but in the editor, it uses only the first tileset images to render both. In the preview, it looks fine.
Here are two screenshots, one of the editor and other of the preview.
![scr0](https://user-images.githubusercontent.com/14160478/29702063-a419f39e-896f-11e7-89f7-22b50412cc05.jpg)
![scr1](https://user-images.githubusercontent.com/14160478/29702064-a41b3bc8-896f-11e7-8b64-a80c32d92f90.jpg)

**Comment by AshleyScirra** [comment]
Fixed for r51. Made a mistake in the new tilemap rendering math. We should have a release out shortly.

**Comment by XpMonster** [comment]
Thank you Ashley for a quick fix.
