### ISSUE TITLE
deleting extentions will crash r50 instantly

### ISSUE THREAD

**Issue by drexegar** [Scirra/Construct-3-bugs#745]
## Problem description

*When deleting an extension in any file, r50 will crash*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Start new project
2. Add random Extensions (Audio, Video, Facebook, Touch etc.)
3. Delete random Extention
4. CRASH

## Observed result

*What do you see happen?*
r50 crashed when I deleted extenstion

## Expected result

*What did you expect to happen instead?*
For the program to continue running after I deleted my extenstion
## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

r50 will not let me copy details, just test it yourself to get them

</details>

**Comment by JeFawk** [comment]
Happens to me too. I added an array and tried to delete it. Crash

![image](https://user-images.githubusercontent.com/7268697/29694154-b8950c00-8942-11e7-8317-d3a74dbd783a.png)


I've also tried to rename an instance var of a family object and it crashed.

**Comment by AshleyScirra** [comment]
Should be fixed in r51.

**Comment by JeFawk** [comment]
Could we please not have updates near the end of your working day? It would be better I think if you do it the next day in the morning because then we have time to find problems like these and you, time to fix them.

**Comment by drexegar** [comment]
i will keép that in mind, i live in New york city and i have no idea where you guys are located, so i can see that uploading around this time which is around 8am now will be a good idea

**Comment by JeFawk** [comment]
@drexegar I was talking to @AshleyScirra  💯

**Comment by AshleyScirra** [comment]
It shouldn't be important. You can roll back to any previous version if there's an issue.

**Comment by JeFawk** [comment]
I tried r49 and couldnt open the c3p. Actually I can't open it now either but i'll just use a backup.

![unknown](https://user-images.githubusercontent.com/7268697/29717592-662713e8-89b8-11e7-8ee7-3ed8b4615dcd.png)

**Comment by AshleyScirra** [comment]
r51 is out now, have you tried that?

**Comment by JeFawk** [comment]
Yes. Same error. The backup which is 10 minutes behind in terms of progress is working.

**Comment by AshleyScirra** [comment]
If you share the broken .c3p I might be able to fix whatever prevented it opening - might be useful in case it ever happens again.
