### ISSUE TITLE
After Cropping an entire animation if you don't select each individual frame before closing Image Editor then all the Origin and Image points will change position

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#749]
## Problem description

In the Image Editor, if you crop the entire animation, all of the Origin points will change position, but only if you do not go through and individually select each frame of animation before closing the image editor. 

So any of the frames that you invidiually check after the crop, will have their Origin and Image Points set to the correct position, but only if you select the frame to see it. 

(Image Points do not behave at all like Origin Points after a crop and are covered in a seperate report. #750)

## Attach a .c3p

[croppy.zip](https://github.com/Scirra/Construct-3-bugs/files/1251317/croppy.zip)

## Steps to reproduce with this .c3p

1. Open the Sprite and place the Origin in the center of the red cross 
2. Right Click the Origin and "Apply to whole animation"
3. Close the editor
4. Preview Game: observe that the red cross stays still in the animation

5. Open the Sprite
6. Hold Shift then click on Crop, so that it applies to the entire animation
7. Immediately close the image editor, without looking at other frames
8. Preview Game

## Observed result

Notice that with step 8, we see how the animation has drastically changed after cropping the entire animation, it is bouncing all over the place, unlike in our Step 4 observation!

## Expected result

The red cross should be stable, like it was before the crop.

**Comment by DiegoScirra** [comment]
Fixed in r52. Thanks for the detailed report. I think some people had seen this before but there were no clear reproduction steps.
