### ISSUE TITLE
Crash after undo creating a Sprite object

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#75]
## Problem description

In conjunction with the sprite object bug where it shows semi-transparency look, apparently any undo after creating the sprite object will end in a crash. I'm assuming this bug is caused by the prior filed bug (https://github.com/Scirra/Construct-3-bugs/issues/72).

## Steps to reproduce

1. Create a Sprite object.
2. Do any actions.
3. Undo.

## Observed result

Crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: TypeError: unexpected type
Stack: TypeError: unexpected type at Function.ǃH.ǃX (https://editor.construct.net/r18/main.js:2:201226) at a.ǃU.ǃCZR (https://editor.construct.net/r18/plugins/sprite/plugin.js:1:6058) at a.ǃU.ǃCZA (https://editor.construct.net/r18/plugins/sprite/plugin.js:1:5399) at Array.ǃHk.ǃH.ǃM.ǃH.ǃHV.ǃHl (https://editor.construct.net/r18/plugins/sprite/plugin.js:1:5052) at ǃH.Event.ǃChB.ǃChc (https://editor.construct.net/r18/main.js:2:283286) at window.ǃAQM.dispatchEvent (https://editor.construct.net/r18/main.js:2:281678) at window.ǃAQM.ǃArF (https://editor.construct.net/r18/main.js:153:35425) at Pe.ǃZo.then.Me (https://editor.construct.net/r18/main.js:153:32698)
Construct 3 version: r18
URL: https://editor.construct.net/index.html
Date: Thu Apr 13 2017 21:31:29 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 1032.8 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Can't reproduce after fixing #72.

**Comment by AshleyScirra** [comment]
r18.2 is out, please check it again.

**Comment by jaydonteh** [comment]
Checked, fixed!

**Comment by AshleyScirra** [comment]
Thanks!
