### ISSUE TITLE
Image Points change position after a crop, differently to the way Origin points do

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#750]
## Problem description

The way that the Image Points are positioned after a crop is incorrect, they do not stay exactly on the pixel that they were assigned to. Whereas the Origin Point behaves correctly in this case.

## Attach a .c3p

[croppy.zip](https://github.com/Scirra/Construct-3-bugs/files/1251348/croppy.zip)

## Steps to reproduce

1. Open the Sprite
2. Place the Origin Point on the red cross 
3. Place the Image Point on the blue circle
4. Crop

## Observed result

See how the Origin Point is still on the red cross

See how the Image Point is no longer on the blue circle.

## Expected result

The Image Point should stay on the blue circle, where it was placed before the crop.

**Comment by DiegoScirra** [comment]
Fixed in r52.
