### ISSUE TITLE
Videos do not work at all when exported to app. Works only in browser r50, r51.

### ISSUE THREAD

**Issue by drexegar** [Scirra/Construct-3-bugs#752]
## Problem description

Video does not play regardless of any trigger I add when exported to an app, it does however work fine in the browser. TESTED ON ANDROID AND IPHONE XCODE

https://drive.google.com/file/d/0ByybatBADJBNQVZobHVHTHA2TlU/view?usp=sharing

## Steps to reproduce

1. Export an app with a video
2. Test out on browser and it works
3. Test out on app and it doesnt work
4. Regardless what code video functions do not work.

## Observed result

Video not playing at all, ignoring any events, even touch triggers don't work (there is no touch trigger in given file, just playing video when layout starts in the "MOVIE" layout)

## Expected result

Video to play when triggered.

## Effect Browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The project has hundreds of events and dozens of objects. It could simply be a mistake in your project. Please provide a minimal project as per the bug report requirements.

**Comment by drexegar** [comment]
Im pretty sure there are no problems, but here is a minimal c3p file:
https://drive.google.com/file/d/0ByybatBADJBNOUppb180em9RRDg/view?usp=sharing

Its works on browser, but will not work as an apk, touch or start on layout is ignored, as well as the autoplay.

Will update the post too.

**Comment by drexegar** [comment]
On touch Start or On touch end does not work, do I have to make a new post? Here is the minimal apk. 
https://drive.google.com/file/d/0ByybatBADJBNeEE0QzByYU4xZVU/view?usp=sharing
