### ISSUE TITLE
 Video does not work on app at all, including on touch start, and on touch end conditions with a play action

### ISSUE THREAD

**Issue by drexegar** [Scirra/Construct-3-bugs#753]
## Problem description

Video doesn't work at all, all actions however do work as intended in the browser
I tried on touch start (disabled in file) and on touch end (enabled in file)

 https://drive.google.com/file/d/0ByybatBADJBNZzdLcDlJZXoweXM/view?usp=sharing

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Add video
2. Add action to play video
3. Works in browser
4. Export app file
5. Video will not play regardless of condition

## Observed result

My video didn't work as intended when exporting to an app.

## Expected result

To watch my video play.

* Chrome: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by drexegar** [comment]
Oh wow nice! Cool beans ill try it now!

**Comment by AshleyScirra** [comment]
The video plugin ought to automatically lowercase the name to match export, but maybe I missed that.

**Comment by drexegar** [comment]
Well I can confirmed this, after switching the case of of the video it did work, and even the auto play worked too on android.

**Comment by AshleyScirra** [comment]
OK, turns out this was originally fixed in C2, then was somehow accidentally reverted again some time afterwards. It should be fixed in r52, and I've applied the fix back to C2 as well.

**Comment by drexegar** [comment]
Excellent!
