### ISSUE TITLE
[r51] Crash on close during close?

### ISSUE THREAD

**Issue by wiverson** [Scirra/Construct-3-bugs#755]
## Problem description

Crash report dialog.  Happened when I tried to close a project while it was already closing.

## Attach a .c3p

Happened when I selected close from the menu while the project was already closing.  Project was kind of large, not including but happy to send along if you need it.

## Steps to reproduce

1. Select Close Project from menu.
2. Select Close Project again before it finishes closing.

## Observed result

Crash dialog!

## Expected result

A bit more feedback about project close (a bit like the way saving works?)

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: project not open @ Error: project not open at t.then (https://editor.construct.net/r51/main.js:163:35459) at 
Stack: Error: project not open at t.then (https://editor.construct.net/r51/main.js:163:35459) at 
Construct 3 version: r51
URL: https://editor.construct.net/
Date: Sat Aug 26 2017 11:56:53 GMT-0700 (PDT)
Uptime: 539.2 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.101
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
C3 release: r51

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M290X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Closing a project happens immediately. If it takes a long time the UI should not be responding while it's closing. So the fact you could open the menu again suggests it actually crashed or failed the first time you clicked "Close project", and the second time was the only time you saw an error message.

There's no project attached and the steps to reproduce don't work with Ghost Shooter (my fallback in such a case), so there's basically nothing we can do about this. If it happens again please check the browser console in case there's an error there, and if you can reproduce it please file again.
