### ISSUE TITLE
Crash in Sprite Editor

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#757]
## Problem description

Construct keeps crashing in the sprite editor.  Occurred 5+ times in the past two days.

## Attach a .c3p

[Bitmen.zip](https://github.com/Scirra/Construct-3-bugs/files/1254376/Bitmen.zip)

## Affected browsers

* Chrome: yes
Version 60.0.3112.101 (Official Build) (64-bit)

## System details
Error report information
Type: unhandled exception
File: https://editor.construct.net/r51/main.js, line 2, col 177960
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Function.ǃo.ǃ_ (https://editor.construct.net/r51/main.js:2:177966) at Function.ǃRqb (https://editor.construct.net/r51/main.js:71:351495) at Function.ǃC_ (https://editor.construct.net/r51/main.js:71:345593) at Function.ǃRLQ (https://editor.construct.net/r51/main.js:71:335065) at Function.ǃC_ (https://editor.construct.net/r51/main.js:71:331950) at e.ǃRJC.ǃREf (https://editor.construct.net/r51/main.js:71:263302) at e.ǃRJC.ǃREP (https://editor.construct.net/r51/main.js:71:176726) at e.ǃRJC.ǃRJO (https://editor.construct.net/r51/main.js:71:176310) at o.ǃRrx.o.ǃRJq (https://editor.construct.net/r51/main.js:71:158730) at e.ǃRcs.ǃQc (https://editor.construct.net/r51/main.js:71:277479)
Construct 3 version: r51
URL: https://editor.construct.net/
Date: Sun Aug 27 2017 08:20:23 GMT-0400 (Eastern Daylight Time)
Uptime: 60634.3 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.101
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
C3 release: r51

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by DiegoScirra** [comment]
Have you been able to figure out some more details about this? From the error report I can tell the crash is happening when you undo changes in the image editor.

That alone is too vague though.

**Comment by 8bitThirsty** [comment]
Nope, that is the extent of the details I have on the issue.  Really frustrating doing 20 mins of image editing work only to have the app crash unable to save my edits.  After losing hours to this issue I switched to the less convienent method working on images outside construct.

**Comment by DiegoScirra** [comment]
Possibly fixed in r52. It is hard to tell as I haven't been able to reproduce it.

Please check the next release.

**Comment by AshleyScirra** [comment]
r52 is out, please verify it works as expected.

**Comment by 8bitThirsty** [comment]
I finally had time and need to spend some time working in the sprite editor and I am no longer seeing this issue.  Appears to be fixed so I will close.
