### ISSUE TITLE
Tilemap issues

### ISSUE THREAD

**Issue by CodeZeek** [Scirra/Construct-3-bugs#758]
## Problem description

When using some tilemaps the selected tile is not the one being painted.

## Attach a .c3p

[PlatformShooter.zip](https://github.com/Scirra/Construct-3-bugs/files/1254454/PlatformShooter.zip)

## Steps to reproduce

1. Add a tilemap like this: https://opengameart.org/content/platformer-art-deluxe
2. Set the Tile width and size (seems to be 70 px).
3. Choose one of the last tiles and try to paint that.

## Observed result
The wrong tile being painted: (Note the one selected versus the one painted)
![tilemap_issue](https://user-images.githubusercontent.com/13259169/29750705-eae39006-8b44-11e7-84cd-25b24987b1dd.png)

## Expected result

That the correct tile was painted ...

## Affected browsers

* Chrome: yes (added to desktop)

## System details

No crash

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r52.
