### ISSUE TITLE
Construct 3 Manual errata: Installing third-party addons

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-3-bugs#759]
## Problem description

Incorrect spelling of "Bundling"

## Steps to reproduce

https://www.construct.net/gb/make-games/manuals/construct-3/tips-and-guides/installing-third-party-addons

Sub-title "Bunding addons to projects" should read "Bundling addons to projects"

**Comment by AshleyScirra** [comment]
Thanks, fixed.
