### ISSUE TITLE
Rearranging frames crash

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#76]
## Problem description

Potential culprit: https://github.com/Scirra/Construct-3-bugs/issues/72 causing this bug.

## Steps to reproduce

1. Create a Sprite object.
2. Duplicate it's frame.
3. Rearrange the frames.

## Observed result

Crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Not able to reproduce this one. I already fixed #72 though, so it might already been fixed.

**Comment by AshleyScirra** [comment]
r18.2 is out, please check it again.

**Comment by jaydonteh** [comment]
checked, it's not crashing anymore!
