### ISSUE TITLE
Imagepoint edit button crash

### ISSUE THREAD

**Issue by NitidOnline** [Scirra/Construct-3-bugs#760]
## Problem description

After editign an Image Point, IDE crash if you push edit button without selecting an Image Point first.

## Attach a .c3p

[ImagePointEditButtonError.zip](https://github.com/Scirra/Construct-3-bugs/files/1257459/ImagePointEditButtonError.zip)

## Steps to reproduce

1. Create a Sprite
2. Go to Edit Image Points
3. Add a Image Point
4. Select image point to activate edit button
5. Press edit button
6. Edit Image point name
7. Press Enter to end edition
8. Press edit button
9. Watch it crash

## Observed result

*What do you see happen?*
It crashes becouse it allows me push edit button if I have not selected an IP first.

## Expected result

Edit button should be deselected when i push Enter or last IP edited would be already selected.

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r51/main.js, line 50, col 18589
Message: Uncaught TypeError: Cannot read property 'addEventListener' of null
Stack: TypeError: Cannot read property 'addEventListener' of null at !o.!Q.!_z.!CW.!oXx.!Yp (https://editor.construct.net/r51/main.js:50:18589) at s.!RlC.!Rlv (https://editor.construct.net/r51/main.js:71:134919) at Array.!Gh.addEventListener (https://editor.construct.net/r51/main.js:71:131357) at !o.Event.!Qzh.!QuR (https://editor.construct.net/r51/main.js:2:259636) at !o.!Q.!Cp.dispatchEvent (https://editor.construct.net/r51/main.js:2:257908) at !o.!Q.!_z.!oiv.!pw.!oPu (https://editor.construct.net/r51/main.js:2:517437) at !o.!Q.!_z.!oiv.!pw.!oPv (https://editor.construct.net/r51/main.js:2:516252) at HTMLElement.click.R.!zm (https://editor.construct.net/r51/main.js:2:514373) at HTMLDocument. (https://editor.construct.net/r51/main.js:2:254778)
Construct 3 version: r51
URL: https://editor.construct.net/index.html
Date: Mon Aug 28 2017 18:03:03 GMT+0200 (Hora de verano romance)
Uptime: 889.1 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.101
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
User agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
C3 release: r51

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2048
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r52
