### ISSUE TITLE
Large Project Bottlenecks: Slow to Open and Close Event Sheets

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#7610]
## Problem description

Large Project Series: A project with 18k objects (stress test)

Slow to Open and Close Event Sheets (Even Blank Ones)

## Attach a .c3p

[Large_Project_Debug_0.zip](https://github.com/Scirra/Construct-bugs/files/13545911/Large_Project_Debug_0.zip)

## Steps to reproduce

1. Open Ev_Empty_1
2. Close Ev_Empty_1
3. Note the time it takes in each case.

**Comment by AshleyScirra** [comment]
Merging in to #7611
