### ISSUE TITLE
WebGPU outsider with Drawing canvas performance

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#7629]
## Problem description

I have a puzzle that consists of `5600` pieces. I wanted to try drawing each puzzle link on the `Drawing canvas`. But when I tried running this on `WebGPU` I saw a significant drop in performance.

On my bucket with `5600` elements of `Drawing canvas` these are the indicators:

`WebGL`: `30` FPS;

`WebGPU`: `6` FPS.

## Attach a .c3p

[web_gpu_outsider_with_drawing_canvas_performance_r370b.zip](https://github.com/WilsonPercival/WilsonPercival/files/13619991/web_gpu_outsider_with_drawing_canvas_performance_r370b.zip)

## Steps to reproduce

1. Open and run the project.

## Observed result

`WebGPU`:

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/38f1fc09-da3c-4167-a2ea-c9a0d972df6f

`WebGL`:

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/541f2f9d-72d5-4b42-80f8-7a36d3b652a0

## Expected result

I would like `WebGPU` to be no worse than `WebGL`.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r370b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r370 (beta)
Browser: Chrome 119.0.6045.200
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 182 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
A known performance issue with WebGPU vs. WebGL is that starting a render pass is much more expensive in WebGPU (I filed an issue about this a while ago at https://bugs.chromium.org/p/dawn/issues/detail?id=1215). In this case using loads of Drawing Canvases results in starting a drawing pass per instance, mainly because it has a special pixel snapping mode for Drawing Canvas to ensure pixel-perfect rendering. You can work around this by setting the Drawing Canvas angle to `Number.EPSILON` (a small but non-zero value) which disables the pixel snapping path and renders it more like a normal sprite, which makes WebGPU as fast as WebGL. Beyond that I don't think there's much we can do to make it faster, and I think thousands of drawing canvases is an unusual use case anyway so probably doesn't warrant complicated extra work to optimize it.

**Comment by WilsonPercival** [comment]
@AshleyScirra Wow, cool, thanks!
