### ISSUE TITLE
Xbox Plugin missing in new manual

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#763]
## Problem description

Xbox Plugin missing in new manual

**Comment by AshleyScirra** [comment]
It's not finished yet. Issue #217 is for pending improvements, once that's fixed we'll add the manual entry.

**Comment by AshleyScirra** [comment]
Manual entry now available at https://www.construct.net/make-games/manuals/construct-3/plugin-reference/xbox-live
