### ISSUE TITLE
Construct 3 [Firefox] - Eventsheet View Poor Performance

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#765]
## Problem description

Events with huge amounts of actions take at least 10 seconds to unfold and also cause severe freezes during the process. Framerate while scrolling is even worse than Chrome. Editing an event causes an Firefox to be unresponsive for a while.

## Attach a .c3p

[Download](https://cdn.discordapp.com/attachments/225550155531812865/321301531569684480/Event_Delay.c3p) here.

## Steps to reproduce

1. Open the project
2. Go to the eventsheet
3. Unfold the collapsed event
4. Notice that it takes up to 10 seconds to load (it's also quite "choppy" while scrolling)

## Observed result

Construct 3 seems to take longer when loading huge event structures.

## Expected result

It should load much faster like Construct 2 did.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: -
* Safari: -

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Nothing.

</details>

**Comment by TheRealDannyyy** [comment]
Reference Issue: #445

**Comment by AshleyScirra** [comment]
Expanding does take ages in Firefox 55 but seems pretty quick in Nightly (57). Could you try it there and see if it's better? Mozilla have done a lot of performance work in v57 so it may be it's OK once that reaches stable.

**Comment by TheRealDannyyy** [comment]
It is indeed faster in Nightly but it still takes 4-6sec. which is longer in comparison to Construct 2.
The framerate is also suffering tremendously when scrolling the eventsheet with the unfolded event.

**Comment by AshleyScirra** [comment]
It's fine for me in Nightly, but I have a high-end machine. Is Nightly at least comparable to Chrome? If so I think we can close this issue as it's not Firefox specific. I guess we should reopen #445 as it's not really resolved either.

**Comment by TheRealDannyyy** [comment]
Nightly performs just like Chrome in regards to unfolding the event. Chrome however performs better in terms of performance after the event has be unfolded.

**Comment by TheRealDannyyy** [comment]
Closing and moving over to #445.
