### ISSUE TITLE
Construct 3 [Firefox] - Mouse Icon Doesn't Change To Resize Icon

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#767]
## Problem description

When hovering over window borders or in the eventsheet view, my mouse cursor icon doesn't change to the "resize" icon. This works fine in Chrome.

## Attach a .c3p

Not required.

## Steps to reproduce

1. Open an in-app window
2. Hover over the border of the window
3. Notice that the icon doesn't change to the "resize" one

## Observed result

I expect it to change accordingly.

## Expected result

I want the icon to change like in Chrome.

## Affected browsers

* Chrome: no
* Firefox: yes
* Edge: -
* Safari: -

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Nothing.

</details>

**Comment by AshleyScirra** [comment]
Works OK for me here. Can you paste in your system details?

**Comment by TheRealDannyyy** [comment]
[Here is a WebM](https://cdn.discordapp.com/attachments/311108993739390976/352817485495402496/Cursor_Icon.webm) demonstrating the issue, presumably only on my end.

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 55.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
C3 release: r52
Local storage

Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Layout View rendering is slow in Firefox due to bug 1163426
    UI animations are disabled in Firefox due to bug 1354501
    CSS containment is not supported. Editor performance may be significantly degraded.
    The <dialog> element is not supported. A polyfill is in use.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    Persistent storage is not available. Local storage could be deleted by the browser.
    Storage quota estimate is unavailable.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 670 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_texture_filter_anisotropic
    EXT_disjoint_timer_query
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_debug_renderer_info
    WEBGL_lose_context
    MOZ_WEBGL_lose_context
    MOZ_WEBGL_compressed_texture_s3tc

Audio information

System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)



</details>

**Comment by AshleyScirra** [comment]
Hmm, nope, still can't reproduce - working OK for me in Firefox 55 and Nightly 57...

**Comment by TheRealDannyyy** [comment]
Hmm, that's weird. I guess if it's just an issue on my end, then it's probably not C3's fault.
Closing for now, re-opening if someone else experiences this as well.
