### ISSUE TITLE
Cloud Login Popup Window Blocked By Default

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#768]
## Problem description

The cloud login window popup is being blocked by default.

## Attach a .c3p

Not Required.

## Steps to reproduce

1. Go to "Cloud"
2. Login to a cloud service (in my case Google Drive)
3. Notice that Firefox blocks it by default (user has to grant permission for it to work)

## Observed result

Popups are blocked by default on Firefox.

## Expected result

If possible, allow Firefox popups to work without additional permissions.

## Affected browsers

* Chrome: no
* Firefox: yes
* Edge: -
* Safari: -

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Nothing.

</details>

**Comment by AshleyScirra** [comment]
This does also happen in Chrome, you can try it in incognito mode to see what it's like with reset preferences. You've probably just already approved popups for C3 in Chrome, since you have to for preview to work. Opening a popup can work before approval if it's in a user input event though, so maybe the cloud login should be adapted to do that. Assigning to Iain to consider.

**Comment by TheRealDannyyy** [comment]
You're right about Chrome, weird can't remember allowing that at all. Maybe adding it to desktop somehow changed the preference for that as well.

Anyway, the user input idea sounds good to me.

**Comment by shortercode** [comment]
Mmm well it's doable, I think I reviewed this in the past and decided it was a better idea to improve the message that appears when the popup is blocked. 

Would require:
- moving authentication to the main context
- modifying the communication channel so the cloud context can request authentication from the main context
- triggering a "unable to open popup: retry" dialog when it fails to open ( normal usage can't originate in a user action, so we need to do this fallback trick )

**Comment by TheRealDannyyy** [comment]
Yep, I could see the message in the cloud-login window.

I hope this change doesn't cause a lot of trouble. In my opinion it's a good thing to work around any kind of Browser related "blocking" like in this case. We've had a similar workaround for copying things to the clipboard and from my experience a lot of people (including myself) appreciate built-in workarounds like this.

**Comment by shortercode** [comment]
What worries me is that this could become the opposite of the copy workaround...

**Current flow:** User see's warning, and changes setting for construct to allow popup. User never sees the failure again.

**Suggested flow:** User get's a retry button and just hits retry, so popups are still blocked by default. Every time they need to authenticate they need to click retry before seeing the auth window.

I guess it's not as bad as what we had with copy, you'll see it at most once an hour ( the session length for G Drive ) but I wonder how many people will just click through the retry button every time. 

I guess if anyone complains we can just tell them to allow popups.

**Comment by AshleyScirra** [comment]
I think the main issue is there's no way to conveniently retry - you have to change the service dropdown back to the first entry, then change it back. If you change it to a different service, it tries to popup again for the wrong service. It's all a bit confusing, maybe just adding a "retry" button is the best we can do here.

**Comment by shortercode** [comment]
There's no need to switch service, just press "refresh" button on the top left of the dialog, it works the same as a "retry" button would with the current implementation. I guess I could change the message to mention the refresh button, but it might prompt people to refresh the actual page...

I don't think the browsers make it clear enough how to enable popups which is a pain. It would be nice to be able to open the popup using the initial user action, but we do a network request to check if the stored token is valid before launching the authentication which messes with that.

**Comment by AshleyScirra** [comment]
I totally missed that, and I wouldn't be surprised if lots of other people did too! I think there should just be a "retry" button in the main window, below the text saying that you need to retry.

**Comment by shortercode** [comment]
Should be fixed in the upcoming release.
