### ISSUE TITLE
Construct 3 [Firefox] - Cloud Project Window Not Scrollable

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#769]
## Problem description

The cloud project-list extends far beyond the screen, instead of being a scrollable list.

## Attach a .c3p

Not Required.

## Steps to reproduce

1. Login to a cloud service (Google Drive in my case)
2. Let the loading process finish
3. Notice that the list extends way beyond the screen.

## Observed result

The project list extends beyond the screen, thus makes it impossible to see all of my projects.

## Expected result

It should be a scollable list like in Chrome.

## Affected browsers

* Chrome: no
* Firefox: yes
* Edge: -
* Safari: -

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Nothing.

</details>

**Comment by AshleyScirra** [comment]
This does also happen in Chrome, you can try it in incognito mode to see what it's like with reset preferences. You've probably just already approved popups for C3 in Chrome, since you have to for preview to work. Opening a popup can work in a user input event though, so maybe the cloud login should be adapted to do that. Assigning to Iain to consider.

**Comment by AshleyScirra** [comment]
Turns out the file list dialog didn't use the required <ui-dialog-contents> element, adding it back in fixed the layout.

**Comment by shortercode** [comment]
Huh, totally possible when it was written originally it didn't use much of the library components. Obviously it's since been updated, but I guess I missed this.

**Comment by TheRealDannyyy** [comment]
Thanks for the quick fix. The good thing is that this was the only "real issue" I could find in the FF beta.
I'd say as soon as they add support or fix all the known issues, C3 is pretty much ready for use on FF.
