### ISSUE TITLE
Middle-click drag then left-click crash

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#77]
## Problem description

While left-click drag then Middle-click bug is fixed: https://github.com/Scirra/Construct-3-bugs/issues/69 , if you reverse your order of the action you get a crash.

**Note:** This has to be done in quick succession to reproduce.

## Steps to reproduce

1. Middle-click then drag.
2. While middle-click is down, do a left-click.

## Observed result

Crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r18/main.js, line 2, col 285118
Message: Uncaught Error: pointer already captured
Stack: Error: pointer already captured at Function.ǃXN (https://editor.construct.net/r18/main.js:2:285124) at g.ǃXb (https://editor.construct.net/r18/components/editors/layoutView/layoutView.js:1:40691) at g.ǃnK (https://editor.construct.net/r18/components/editors/layoutView/layoutView.js:1:51513) at Array.ǃnw.c (https://editor.construct.net/r18/components/editors/layoutView/layoutView.js:1:50660) at ǃH.Event.ǃChB.ǃChz (https://editor.construct.net/r18/main.js:2:283085) at window.ǃei.dispatchEvent (https://editor.construct.net/r18/main.js:2:281666) at window.ǃei.ǃnK (https://editor.construct.net/r18/components/editors/layoutView/layoutView.js:1:14222) at HTMLDocument.ǃnw.I (https://editor.construct.net/r18/components/editors/layoutView/layoutView.js:1:2400) at HTMLDocument. (https://editor.construct.net/r18/main.js:2:278349)
Construct 3 version: r18
URL: https://editor.construct.net/index.html
Date: Thu Apr 13 2017 22:09:03 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 345.8 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r18.2.
