### ISSUE TITLE
R52 - Translation issue

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#770]
## Problem description

The field "Value" of a specific dialog seems to not be translating.
Auto completion also looks to use the English string file only

## Attach a .c3p
https://kyatric.com/c3/bugs/2017-08-31-Bug_Translation_Field_Value.c3p

## Steps to reproduce

1. Have C3 in French 
2. The action is set the value of a global variable.
3. When read in the event sheet view, Sprite.IDU is correct (IDU is translation for UID.
4. Double-click the action notice in the "Valeur" (Value) field how it is written "Sprite.UID" (with the colored syntax).

extra

5. If you try to delete .UID and have the auto completion for the expressions available for the object Sprite, you can notice they only provide the English version of the expression, not the translated one.

## Observed result

An expression from the English strings file in a text field.
On auto-completion, all proposals coming from the English strings file.

## Expected result

The expression to be translated. Instead of Sprite.UID have Sprite.IDU in the "Valeur" text field.
On auto-completion, having the proposals taken from the French string file (where asJSON is enJSON; where ImagePointCount is NombrePointImage; etc...)

## Affected browsers

* Chrome: yes

## System details
<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r52

Local storage
Storage quota (approx): 12 gb
Storage usage (approx): 853 mb (6.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Unfortunately expressions cannot be typed with translated names. We have to use English to avoid name collisions. For example imagine if in English you use Sprite.foo, but in French you use Sprite.bar. An English user can add an instance variable named "bar" without causing a name collision. But for a French user that causes a name collision. Worse, if the English user with an instance variable named "bar" switches their language to French, or sends their project to a French user, there is a name collision and the project can't be opened.

This is solved by forcing expressions to be *typed* using the English names, but display it translated everywhere else we possibly can. This is why it appears translated in the Event Sheet View but appears with an English expression name in the parameters dialog.

There are more places we could display translated names though as you point out, so in the next build:
- hovering the mouse shows the translation in a tooltip (so hovering "UID" shows a tooltip "IDU")
- autocomplete lists translated names and suggests based on translated names, but also shows the English in italic beside it (e.g. IDU [i]UID[/i]) to make it clear what will be entered if you pick that item
- call tips display the translated expression name

I think that's about all we can do without causing name collisions. Hopefully that does make it better to use though.
