### ISSUE TITLE
Tilemap Selection and Erasing Continuously

### ISSUE THREAD

**Issue by flipog** [Scirra/Construct-3-bugs#771]
## Problem description

When I try to erase continuously, instead I move the tilemap I'm editing around. It also happens when I'm trying to select an area of said tilemap

## Attach a .c3p

Any file with tilemaps should display this issue

## Steps to reproduce

1. Try to erase tiles in a tilemap by holding the left mouse button, or...
2. Try to select an area of tiles in any tilemap.
3. Both the options above should display the issue

## Observed result

My tilemaps moving around

## Expected result

I expected to be able to select areas and erase by hold-dragging the mouse

## Affected browsers

* Chrome: yes
* Firefox: did not test
* Edge: n/a
* Safari: n/a

## System details

There were no crashes.

**Comment by DiegoScirra** [comment]
Fixed in r53.
