### ISSUE TITLE
Preview freezes when rgb() is called

### ISSUE THREAD

**Issue by virgulaleal** [Scirra/Construct-3-bugs#773]
## Problem description

Attempting to change the background color of a layer causes the preview to freeze completely.

## c3p example
[crashexample.zip](https://github.com/Scirra/Construct-3-bugs/files/1272558/crashexample.zip)

## Steps to reproduce

1.Set up an event that changes the background color using rgb()
2.Attempt to preview the project

## Observed result

Preview freezes, fps drops to zero, developer console returns the following error message repeatedly:

Uncaught ReferenceError: rgb is not defined
    at cr.system_object.SysActs.SetLayerBackground (system.js:1905)
    at Action.run_system (eveng.js:1765)
    at EventBlock.run_actions_and_subevents (eveng.js:947)
    at EventBlock.run (eveng.js:904)
    at Runtime.executeSingleTrigger (preview.js:4967)
    at Runtime.triggerOnSheetForTypeName (preview.js:4886)
    at Runtime.triggerOnSheet (preview.js:4813)
    at Runtime.trigger (preview.js:4795)
    at Layout.startRunning (layout.js:417)
    at Runtime.start_first_layout (preview.js:2171)

## Affected browsers

* Chrome: yes
* Firefox: unsupported
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r53

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 27 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 255
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for r54.
