### ISSUE TITLE
Exported HTML5 builds with minify selected do not load

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-3-bugs#778]
## Problem description

Exporting a project to HTML5 with minify script selected results in a build that will not download in Chrome or Firefox when uploaded to a web host.

## Attach a .c3p

https://www.dropbox.com/s/mjyor6y1gkmud5f/exportTest00.c3p?dl=0

## Steps to reproduce

1. Open the attached C3 project file
2. Select Export>Web(HTML5)
3. Download the export and unzip
4. Upload to a web host (I used BitBalloon)
5. Test link in Chrome/Firefox

## Observed result
The build doesn't download - the C3 loading screen isn't shown.

N.B works fine on Edge.

## Expected result

Project should load

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: no

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r54.
