### ISSUE TITLE
Creating a sprite bug

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#78]
## Problem description

*If you create a sprite with less then 250x250px, like 128x128px filled with a any solid color, and them create another sprite with 250x250px, the 250x250px sprites will have the 128x128px square inside it*

## Attach a .c3p

*There's no need to add a .c3p, the bugs happens even with a blank proejct*

## Steps to reproduce

1. Create a 128x128px sprite and use the bucket tool to fill it with any solid color
2. Create a another sprite with 250x250px
3. The second sprite will have the 128x128px sprite inside it

## Observed result

*The second sprite received the first sprite inside it*

## Expected result

*The second sprite to be absolutely blank*

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Can't reproduce right away. Might be related to #72 which has already been fixed.

**Comment by BonzerKitten7** [comment]
Absolutely, i'm getting these semi-transparent sprites too.

**Comment by AshleyScirra** [comment]
r18.2 is out, please check it again.

**Comment by BonzerKitten7** [comment]
Updated, and everything is solved! Thanks both of you.

**Comment by AshleyScirra** [comment]
Great, thanks for verifying!
