### ISSUE TITLE
Facebook post text/description not populating in 'share link'

### ISSUE THREAD

**Issue by hansonbrody** [Scirra/Construct-3-bugs#780]
![share1](https://user-images.githubusercontent.com/15069506/30043048-acc9dab8-91cb-11e7-8eba-472bd9581ef3.PNG)
![share2](https://user-images.githubusercontent.com/15069506/30043049-accb0f28-91cb-11e7-847f-dab1e4524f94.PNG)

## Problem description

I have a 'share link' action using the facebook object. The function works, but none of the information (link text, caption, description) is included.

## Attach a .c3p

Attached screenshots

## Steps to reproduce

1. prompt user to share link
2.
3.

## Observed result

Link post is opened and ready to share in facebook, but none of the descriptive information is populated

## Expected result

Link includes the text, caption, and description I wrote in the construct 3 facebook prompt to share link dialog.

## Affected browsers

* Chrome: yes
* Firefox:
* Edge: 
* Safari: 

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by hansonbrody** [comment]
I have a new launch coming up in two weeks; any chance this might be addressed by then?

**Comment by AshleyScirra** [comment]
I've removed the redundant parameters in r78 and closing for now. If we find a replacement we'll track that as a new feature.
