### ISSUE TITLE
Unable to read Text File

### ISSUE THREAD

**Issue by Parth-Kadakia** [Scirra/Construct-3-bugs#781]
I have created a quiz game. My questions are in text files. While testing on editor.construct.net and previewing, it works fine. When I export the game to Android for testing or upload it to itch.io for testing on browser the game is unable to read the text file. I see there is Questions.txt file in the folder but somehow its not reading it.

[NumberGame.zip](https://github.com/Scirra/Construct-3-bugs/files/1276281/NumberGame.zip)

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Export the project (Android or HTML5)
2. Run it on host / Android device

## Observed result

The application fails to read the text file and shows my default text of text box.

## Expected result

Questions should be displayed

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

Android 6.0 and itch.io gaming host

**Comment by shortercode** [comment]
By the looks of this it's related to case sensitivity, had a very similar issue with a video file on Android a little while ago. Some servers / systems are case sensitive, but others are not; for instance Construct.net isn't, but Android is. This would explain why you don't have an issue on preview, but you do on Android.

We change all files to have lowercase names when exported, to try and prevent issues like this. But I guess we missed the place where the file is loaded. As a workaround if you change the filename to lowercase in both places it should load.

**Comment by AshleyScirra** [comment]
Yep, probably missed another lowercasing in the project file parameter.

**Comment by AshleyScirra** [comment]
Added in some extra lowercasing, should be fixed in r54.
