### ISSUE TITLE
Crash with copy&paste at tilemap

### ISSUE THREAD

**Issue by NitidOnline** [Scirra/Construct-3-bugs#785]
## Problem description

IDE crash when using ctrl-c / ctrl-v if any tool from Tilemap Bar is in use.

## Attach a .c3p

Use Tilemap example from Start Page

## Steps to reproduce

1. Select tilemap
2. Select any tool from Tilemap Bar
3. Press ctrl-c
4. Press copy
5. Press ctrl-v
6. IDE crash

## Observed result

IDE crash doing an innecesary operation ^^

## Expected result

Copy and paste don't be allowed when using Tilemap Bar Tools. A prompt alerting that whould be nice. 
(I guess, becouse I'm noob with tilemaps)

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

PError report information
Type: unhandled exception
File: https://editor.construct.net/r54/components/editors/layoutView/layoutView.js, line 1, col 75565
Message: Uncaught Error: crosshair tool not enabled
Stack: Error: crosshair tool not enabled at r.ǃqt (https://editor.construct.net/r54/components/editors/layoutView/layoutView.js:1:75571) at window.ǃBt.ǃqL (https://editor.construct.net/r54/components/editors/layoutView/layoutView.js:1:30555) at window.ǃBt.ǃGC (https://editor.construct.net/r54/components/editors/layoutView/layoutView.js:1:30071) at Array.ǃa.ǃO.ǃG.ǃO.ǃr.ǃk (https://editor.construct.net/r54/components/editors/layoutView/layoutView.js:1:3754) at ǃO.Event.ǃzks.ǃzkD (https://editor.construct.net/r54/main.js:2:259811) at ǃO.ǃN.ǃj.ǃOOt.dispatchEvent (https://editor.construct.net/r54/main.js:2:258256) at ǃO.ǃN.ǃj.ǃOOt.ǃGC (https://editor.construct.net/r54/main.js:2:301945) at a.ǃGC (https://editor.construct.net/r54/main.js:2:304825) at HTMLDocument.window.C3_IsPopupWindow.t.document.addEventListener (https://editor.construct.net/r54/main.js:2:303157)
Construct 3 version: r54
URL: https://editor.construct.net/index.html
Date: Thu Sep 07 2017 11:35:59 GMT+0200 (Hora de verano romance)
Uptime: 41049.7 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r54

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2048
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by NitidOnline** [comment]
Updated with correct Error Report Information.

**Comment by DiegoScirra** [comment]
Working on this, blocking the keyboard shortcuts when the Tilemap Bar is in use is easy enough, but what were you trying to do by using the copy/paste keyboard shortcuts while editing a tilemap instance?

Was it just a mistake? Or were you expecting something else to happen?

**Comment by NitidOnline** [comment]
I was trying to copy and paste a group of tiles, but it was a mistake.... I had not read the manual yet, so I was missusing the tool. Now I use keys 6 and 1 and it works great.

Thanks for asking!

**Comment by DiegoScirra** [comment]
Fixed in r55. Now, those keyboard shortcuts don't do anything while editing a tilemap.
