### ISSUE TITLE
Tilemap object: empty tiles not registering as being contained within the tilemap object

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-3-bugs#789]
## Problem description

Empty tile positions within the tilemap object will not respond to (for example) "On touch tilemap". This issue has arisen fairly recently - previously empty tiles would respond. 

## Attach a .c3p

https://www.dropbox.com/s/lieyosnhmuu0epr/tilemapbug.c3p?dl=0

## Steps to reproduce

1. Open tilemapbug.c3p
2. Preview the project
3. Tap or click in on the space in between the two groups of tiles.
4. Tap or click one of the groups of tiles

## Observed result

When you click on the space between the two groups of tiles the text below it doesn't update to reference the position.

When you click on a tile group the text does update.

## Expected result

Clicking on an empty tile within the tilemap object should still register as clicking the object.

## Affected browsers
* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is a deliberate change to fix issue #723. It's the correct behavior now - empty tiles should never have registered collisions. I think it was inconsistent before as well, since empty tiles would not register sprite collisions, but would for point collisions; now everything works consistently and correctly.

**Comment by jakemay74** [comment]
This becomes problematic - any empty tiles will not register as being contained within the tilemap object, meaning that you can't manipulate them at runtime. Consider that this also affects conditions like "mouse over"

**Comment by jakemay74** [comment]
If this isn't going to change how do I go about identifying that I'm making an input within a tilemap object on an empty tile so that I can manipulate that tile?

**Comment by AshleyScirra** [comment]
Just check the touch is inside its rectangle.
