### ISSUE TITLE
Animation editor: Undo enabled even there's nothing to undo

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#79]
## Problem description

Title says it all.

## Observed result

The undo button is enabled for user to click.

## Expected result

Should be disabled just like the redo button when there is no history of actions. Apparently once you did an action, you could disable the undo button after an undo as usual.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Which version is affected? Please always include the relevant information to make it unambiguous.

**Comment by jaydonteh** [comment]
Was filed for **r18** when **r18.2** released, now it is fixed in **r18.2**!

**Comment by DiegoScirra** [comment]
Cool!
