### ISSUE TITLE
Physics Behaviour - Limited revolute Joint Bug with Animated Parent

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#790]
## Problem description
When you use the Physics Behaviour, and use the Limited Revolute Joint (dont know if it happens with other Joints too) to put an object (lets call it child) on a parent, the child will follow everything the parent does, and also be used in collisions.

Expected Result:
When you move around with the parent and rotate around, the child follows normally. **If the Parent does not have an animation.**

Observed Result:
When the parent has an animation running the child will seemingly randomly move away/toward the parent and or  rotate weirdly in relation to the parent.

- yes Collision Polygon is the same across frames
- yes it also happens when you set collision mask of the parent to circle
- yes when you set animation speed to 0 it moves normal again
- yes it also happens if the child does not collide with the parent (when collision disabled with physics 
 behaviour)
- yes after the child has moved massively it still collides with other objects

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

i made a simple project with 2 green circles with a red line in them, where the above green circle does not play an animation and the below does play an animation. after some time the child to the parent playing the animation will be somewhere else, as next to the red line.

[TEST_Physics.zip](https://github.com/Scirra/Construct-3-bugs/files/1285798/TEST_Physics.zip)

(i dont know if you can open it, i added to a .rar and just changed ending to .zip so i can upload here)

## Steps to reproduce

1. make 2 sprites with physics behaviour
2. have the parent run an animation
3. make limited revolute joint to animated sprite
4. ???
5. random movement

## Affected browsers

* Chrome: yes

## System details

There is no crash, so there is no bug report or anything

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I can't open the zip file, apparently it is corrupt. Anyway, you should not animate Physics objects: when the animation frame changes we are forced to destroy the physics object and teleport a new physics object in its place with the new size and collision shape. (This always happens, regardless of if anything has actually changed.) Obviously this is an unrealistic thing to do in the real world and so the resulting simulation is unrealistic as well.

Workaround: use an invisible object which does not animate with the physics behavior, and place the animating sprite on top of that.
