### ISSUE TITLE
Can't use particles

### ISSUE THREAD

**Issue by amarianno** [Scirra/Construct-3-bugs#791]
I've try to add a particle and got this error:

Error report information
Type: unhandled rejection
Reason: Error: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0. @ Error: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0. at o (https://editor.construct.net/r54/main.js:2:193256) at i (https://editor.construct.net/r54/main.js:2:192954) at d (https://editor.construct.net/r54/main.js:2:193176) at Function.ǃO.ǃznW (https://editor.construct.net/r54/main.js:2:198853) at Function.ǃWGj (https://editor.construct.net/r54/main.js:71:395405) at Function.ǃzip (https://editor.construct.net/r54/main.js:71:393596) at t.ǃWsB.ǃWud (https://editor.construct.net/r54/main.js:71:196849) at t.ǃWsB.ǃWwL (https://editor.construct.net/r54/main.js:71:196589) at ǃWEj.then (https://editor.construct.net/r54/main.js:71:176930) at 
Stack: Error: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0. at o (https://editor.construct.net/r54/main.js:2:193256) at i (https://editor.construct.net/r54/main.js:2:192954) at d (https://editor.construct.net/r54/main.js:2:193176) at Function.ǃO.ǃznW (https://editor.construct.net/r54/main.js:2:198853) at Function.ǃWGj (https://editor.construct.net/r54/main.js:71:395405) at Function.ǃzip (https://editor.construct.net/r54/main.js:71:393596) at t.ǃWsB.ǃWud (https://editor.construct.net/r54/main.js:71:196849) at t.ǃWsB.ǃWwL (https://editor.construct.net/r54/main.js:71:196589) at ǃWEj.then (https://editor.construct.net/r54/main.js:71:176930) at 
Construct 3 version: r54
URL: https://editor.construct.net/
Date: Sat Sep 09 2017 15:05:21 GMT-0300 (BRT)
Uptime: 635.1 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r54

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Sandybridge Mobile 
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 255
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_frag_depth, EXT_shader_texture_lod, EXT_sRGB, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

**Comment by AshleyScirra** [comment]
Please provide all the required information, such as the steps to reproduce, otherwise there's nothing we can do.

**Comment by amarianno** [comment]
Step 1: create a particle
Step 2: Resize particle w:1 and h:1
Step 3: confirm the operation
Step 4: Pop up with text  

Error report information
Type: unhandled rejection
Reason: Error: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0. @ Error: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0. at o (https://editor.construct.net/r54/main.js:2:193256) at i (https://editor.construct.net/r54/main.js:2:192954) at d (https://editor.construct.net/r54/main.js:2:193176) at Function.ǃO.ǃznW (https://editor.construct.net/r54/main.js:2:198853) at Function.ǃWGj (https://editor.construct.net/r54/main.js:71:395405) at Function.ǃzip (https://editor.construct.net/r54/main.js:71:393596) at t.ǃWsB.ǃWud (https://editor.construct.net/r54/main.js:71:196849) at t.ǃWsB.ǃWwL (https://editor.construct.net/r54/main.js:71:196589) at ǃWEj.then (https://editor.construct.net/r54/main.js:71:176930) at
Stack: Error: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0. at o (https://editor.construct.net/r54/main.js:2:193256) at i (https://editor.construct.net/r54/main.js:2:192954) at d (https://editor.construct.net/r54/main.js:2:193176) at Function.ǃO.ǃznW (https://editor.construct.net/r54/main.js:2:198853) at Function.ǃWGj (https://editor.construct.net/r54/main.js:71:395405) at Function.ǃzip (https://editor.construct.net/r54/main.js:71:393596) at t.ǃWsB.ǃWud (https://editor.construct.net/r54/main.js:71:196849) at t.ǃWsB.ǃWwL (https://editor.construct.net/r54/main.js:71:196589) at ǃWEj.then (https://editor.construct.net/r54/main.js:71:176930) at
Construct 3 version: r54
URL: https://editor.construct.net/
Date: Sat Sep 09 2017 15:05:21 GMT-0300 (BRT)
Uptime: 635.1 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r54

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) Sandybridge Mobile
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 255
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_frag_depth, EXT_shader_texture_lod, EXT_sRGB, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

**Comment by AshleyScirra** [comment]
Thanks, I can reproduce with those steps.

**Comment by DiegoScirra** [comment]
Fixed in r56.
