### ISSUE TITLE
Find all references returns all events that use a variable as the name of an object to be created

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#792]
## Problem description

When searching my project using "Find all references" I was getting lots of results that weren't relevant. It seems that every event that uses "Create object by name" along with a variable to specify the name is showing up in the results list.

## Attach a .c3p

[ReferencesBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1291554/ReferencesBug.zip)

## Steps to reproduce

1. Create an object, like a Sprite (i.e., named "Sprite")
2. Add a string variable (i.e., named "Variable1") to the sprite and fill it with gibberish characters
3. Create an event that uses "Create object by name" and use "Sprite.Variable1" as the name of the object to be created
4. Create another Sprite (i.e., named "Sprite2")
5. Right-click on Sprite2 in the Object types list and choose "Find all references"  

## Observed result

The list of references includes the call to Create object by name, even though this line doesn't reference Sprite2.

## Expected result

Expect that only explicit references to Sprite2 are returned from the search. (I can see the utility of returning every possible reference, but once you start storing lots of objects to be created in instance variables within a large project, the search gets difficult to parse.)

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r54

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 338 mb (2.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is by design. The editor doesn't know what the value of variables will be at runtime, so it returns ambiguous results (with an icon of a question mark). This is a reason to avoid using "create object by name" too heavily. It is discussed in the manual some more: https://www.construct.net/make-games/manuals/construct-3/interface/bars/find-results-bar
