### ISSUE TITLE
Future keyword "let" error on old devices

### ISSUE THREAD

**Issue by cihanyakar** [Scirra/Construct-3-bugs#793]
## Problem description

c2runtime.js line 679 contains `let` keyword. On old devices this line fires an exception.

## Attach a .c3p

Any empty .c3p file

## Steps to reproduce

1. Open new project
2. Publish
3. Open in an old os such as ios 7, android 4

## Observed result

Black screen after loading.

## Expected result

The game after loading.

## Affected browsers

* Android default browser (4): yes
* Chrome : no
* Firefox: no
* Edge: no
* Safari (ios 7): yes

**Comment by AshleyScirra** [comment]
Well spotted, sometimes these slip in since we use that style regularly in C3 itself. Should be fixed in the next build.
