### ISSUE TITLE
LOS ray cast from the edge of an obstacle has varied intersection results

### ISSUE THREAD

**Issue by CodyRockwell** [Scirra/Construct-3-bugs#7995]
## Problem description

When casting a ray that starts exactly at the edge of an obstacle, depending on the angle and position of the ray, the ray may not trigger the 'Ray Intersected' condition. If the ray does intersect the obstacle, the 'HitX' and 'HitY' values may return 'NaN'.

## Attach a .c3p

https://drive.google.com/file/d/1by8JDRxsZqc5FD1mkH_5Hgx1vZfMjYzN/view?usp=sharing

## Steps to reproduce

1. Open the .c3p and observe
2. The numbered RayCaster sprites all cast rays down (90 degrees). Their opacity flickers to indicate when 'Ray Intersected' is triggered
3. Any RayCaster whose ray intersects the obstacle creates a green line from the rays starting point to its ending point

## Observed result

- RayCaster sprites 0 and 8 don't register a hit at all.
- Sprites 2, 4 and 7 are the only ones that have 'HitX' and 'HitY' values that are not 'NaN'.

## Expected result

- If 'Ray Intersected' is triggered, then 'HitX' and 'HitY' should have a numerical value.
- Rays that align with the angle of an obstacles edge (rays from 0, 1, 4, 5, and 8) should either all trigger 'Ray Intersected' or not trigger it, rather than only certain ones triggering it.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 388.2

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r388.2 (stable)
Browser: Chrome 124.0.6367.119
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 2.1 gb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 (0x00002487) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by WilsonPercival** [comment]
I may be wrong, but if we try to calculate the intersection point of two vertical lines using Cramer's method, we will get NaN due to the division by 0. Perhaps the same thing happens in the raycast process.

[issue7995.zip](https://github.com/Scirra/Construct-bugs/files/15245059/issue7995.zip)

**Comment by AshleyScirra** [comment]
Computers do fractional (floating point) calculations with limited precision. This introduces rounding errors with any type of calculation (in any software, on any hardware). This means this kind of intermittent or unreliable result at extreme edge cases is normal in software. You generally just have to design your game around it as there is no feasible workaround. See [0.30000000000000004.com](https://0.30000000000000004.com/).
