### ISSUE TITLE
Undo/Redo Drop List Everything

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#8]
## Problem description

As of title.

## Steps to reproduce

1. make actions.

## Observed result

List entire Drop List of Undo/ Redo. Caused to have a long list that cannot be navigated with mouse wheel.

## Expected result

Menu should be scroll-able and it shouldn't try to list everything. @AshleyScirra suggest 10 item limit to the dropdown.

## Affected browsers

* Chrome: yes

**Comment by DiegoScirra** [comment]
Fixed this in the undo stacks of both the main editor and the animations editor. The stacks now have a limit of 10 items and show no scrollbars.
