### ISSUE TITLE
Left-click + Middle-button then drag crash

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#80]
## Problem description

As of title.

## Observed result

Crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r18-2/main.js, line 2, col 285067
Message: Uncaught Error: pointer already captured
Stack: Error: pointer already captured at Function.ǃDU (https://editor.construct.net/r18-2/main.js:2:285073) at u.ǃQA (https://editor.construct.net/r18-2/components/editors/layoutView/layoutView.js:1:40845) at u.ǃA_ (https://editor.construct.net/r18-2/components/editors/layoutView/layoutView.js:1:51688) at Array.ǃAM.A (https://editor.construct.net/r18-2/components/editors/layoutView/layoutView.js:1:50813) at ǃs.Event.ǃEWN.ǃEWU (https://editor.construct.net/r18-2/main.js:2:283033) at window.ǃaM.dispatchEvent (https://editor.construct.net/r18-2/main.js:2:281614) at window.ǃaM.ǃA_ (https://editor.construct.net/r18-2/components/editors/layoutView/layoutView.js:1:14231) at HTMLDocument.ǃAM.P (https://editor.construct.net/r18-2/components/editors/layoutView/layoutView.js:1:2396) at HTMLDocument. (https://editor.construct.net/r18-2/main.js:2:278297)
Construct 3 version: r18.2
URL: https://editor.construct.net/index.html
Date: Fri Apr 14 2017 01:16:28 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 11.3 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r19.
