### ISSUE TITLE
After trying to set values for variables Chrome directs to new tab

### ISSUE THREAD

**Issue by griffenk** [Scirra/Construct-3-bugs#800]
**Problem**
After trying to set values for variables Chrome directs to new tab

**Description** 
Not possible to edit variables value. After pressing SET VALUE Chrome directing to new tab. Your project automatically closing and of course not saved

By the way. I tried to set height of the sprite and receive the same result

## Attach a .c3p
[a.zip](https://github.com/Scirra/Construct-3-bugs/files/1302798/a.zip)

**Steps to reproduce**
1. Create new empty project
In EvenSheet
2. Create Global variable 
3. Try to Set value for this variable
 

## Observed result
Construct project closed unsaved. Instead of project tab, new  empty Chrome tab appears 
*What do you see happen?*

## Expected result
Set value for the variable 

*What did you expect to happen instead?*
I expected to set variable value

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: untested

## System details

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir4,2
  Processor Name:	Intel Core i5
  Processor Speed:	1.7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	4 GB
  Boot ROM Version:	MBA41.0077.B33

I use r55 Construct 3
Chrome Version 60.0.3112.113 (Official Build) (64-bit)
OS macOS Sierra version 10.12.6 (16G29)

**Comment by AshleyScirra** [comment]
You can't add a 'set value' action to the project, because there is no event to add it to. You can only add a 'Compare value' condition, and that seems to work fine on Windows.

What browser version, OS version and C3 version are you using? Please paste all the info in the Platform Dialog as the bug report guidelines suggest; it includes all this information already so we don't have to ask for it.

**Comment by griffenk** [comment]
Ashley, Sorry my bad!

Try to compare variable, redirecting to the new tab as well

I use r55 Construct 3
Chrome Version 60.0.3112.113 (Official Build) (64-bit)
OS macOS Sierra version 10.12.6 (16G29)

Regards,

Sergey

**Comment by AshleyScirra** [comment]
If you go to Help -> About Google Chrome, it should update to Chrome 61 which is out now. If you update, does that fix it? I'm testing on Chrome 61 here.

Also have you disabled UI animations? IIRC there was a Chrome bug that caused a crash in some cases when you had that turned off.

**Comment by griffenk** [comment]
Ashley, 
I updated Chrome
Unfortunately I experience the same problem with Chrome 61
I google on how to disable Ui Animation on chrome and have not found solution. 

Anyway I have not changed anything expect updating Construct 3 to 55 version and them issue appears

Thanks,

Sergey

**Comment by AshleyScirra** [comment]
I meant the "Enable UI animations" option in Construct 3's settings.

If you roll back to r54, does it still happen?

**Comment by drexegar** [comment]
I can also confirm this happens for me as well, and any back action while messing with variables will also cause the browser to go back a page.

This does not happen in r54, only in r55.

**Comment by AshleyScirra** [comment]
@drexegar - you mentioned "any back action", which is not in the original report posted here. Are you doing something different? Can you clarify exactly what you mean? I am getting pretty confused because everything everyone is talking about sounds vague and contradictory.

**Comment by drexegar** [comment]
My apologies here is some detail

1. Create a new project
2. Go to event editor
3. Add Event
4. Double Click on System
5. Click on any system condition
6. Press the back arrow on that condition and it will force the browser to go back exiting the program.

1. Create a new project
2. Go to event editor
3. Add Event
4. Double Click on System
5. Press the back arrow
6. Double Click on System again and it will force the browser to go back exiting the program.

This only happens on r55 on google chrome. I haven't test firefox yet.

**Comment by AshleyScirra** [comment]
Which back arrow are you pressing? The one in the dialog, or the one in the browser?

**Comment by drexegar** [comment]
The little small arrow in the event editor dialog the one use to go back if you don't want the condition you chose.

**Comment by griffenk** [comment]
Ashley,

Please see video (Screen recording) in .mov format for issue #800

[#800_issue.zip](https://github.com/Scirra/Construct-3-bugs/files/1308152/800_issue.zip)

Hope, it helps somehow

Regards,

Sergey

**Comment by AshleyScirra** [comment]
r56 is out, can you check if this still happens?

**Comment by griffenk** [comment]
Ashley, 

r56 works perfectly for me! 

Thanks for such a quick response!!!

You're the best,

Regards, 

Sergey

**Comment by AshleyScirra** [comment]
Great, thanks for confirming.
