### ISSUE TITLE
Cordova Plugin for native app builder

### ISSUE THREAD

**Issue by newman321** [Scirra/Construct-3-bugs#801]
want to add a third party cordova plugin to get whitelisted or added to c3 native app builder.

https://github.com/don/BluetoothSerial or similar plugins.

**Comment by shortercode** [comment]
I need to review the plugin but I expect this should be fine to add to the whitelist.

**Comment by shortercode** [comment]
The servers been updated with several new plugins whitelisted, including Bluetooth serial. Let me know if you have any issues ( presuming your writing the c3addon for it )

Enjoy!
