### ISSUE TITLE
Can't use dictionary editor in Firefox

### ISSUE THREAD

**Issue by MeStrak** [Scirra/Construct-3-bugs#803]
## Problem description

I have the paid plan. When I try to open the dictionary editor, the page is blank - all I can see is the box to set the size of the dictionary.

## Attach a .c3p

https://www.dropbox.com/s/n65n8j21nhvdt1y/Test%281%29.c3p?dl=0

## Steps to reproduce

1. Open dictionary .json file for editing in Firefox
2. No data is displayed

## Observed result

No dictionary data (no grid) is displayed, just a blank background.

## Expected result

I expected to see the grid like I do in Chrome.

## Affected browsers

* Chrome: no
* Firefox: yes
* Edge: can't open C3 in Edge
* Safari: not tested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 55.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
C3 release: r55
Local storage

Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Layout View rendering is slow in Firefox due to bug 1163426
    UI animations are disabled in Firefox due to bug 1354501
    CSS containment is not supported. Editor performance may be significantly degraded.
    The <dialog> element is not supported. A polyfill is in use.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    Persistent storage is not available. Local storage could be deleted by the browser.
    Storage quota estimate is unavailable.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Mobility Radeon HD 5000 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_texture_filter_anisotropic
    EXT_disjoint_timer_query
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_debug_renderer_info
    WEBGL_lose_context
    MOZ_WEBGL_lose_context
    MOZ_WEBGL_compressed_texture_s3tc

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Hi @MeStrak thanks for the bug report.

I've had a look and the element is rendering at 0px height, I believe this is to do with some styles that are applied when CSS containment isn't supported.

@AshleyScirra I'm not really sure how these rules are supposed to work so would you mind having a look? noContainmentStyles.css is applying height: auto, which appears to make a pane with no layout content (absolute children) 0px high.

**Comment by AshleyScirra** [comment]
Just need a few well-placed height: 100% rules when CSS containment isn't supported. Should be fixed in the next release.
