### ISSUE TITLE
Duplicating flowcharts causes crash

### ISSUE THREAD

**Issue by saucerinvasion** [Scirra/Construct-3-bugs#8037]
## Problem description

Attempting to duplicate a flowchart using RIGHT CLICK -> DUPLICATE causes C3 to crash

## Attach a .c3p

[flowchartDialog.zip](https://github.com/Scirra/Construct-bugs/files/15470526/flowchartDialog.zip)

## Steps to reproduce

1. create a flowchart
2. Right click on the flowchart
3. Select duplicate

## Observed result

C3 Crashes - red screen - save your work etc

## Expected result

The flowchart would duplicate

## More details
I'm afraid that's it. I was doing a pretty minimal test

**Affected browsers/platforms:** 
Tested in Chrome (125.0.6422.77) &  firefox (126.0)

**First affected release:**  
r388.2

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected finite number @ TypeError: expected finite number at P.B (https://editor.construct.net/r388-2/main.js:1051:407) at d.lq (https://editor.construct.net/r388-2/projectResources.js:611:327) at d.Aa (https://editor.construct.net/r388-2/projectResources.js:1799:110) at d.Dg (https://editor.construct.net/r388-2/projectResources.js:1793:395) at https://editor.construct.net/r388-2/components/bars/projectBar/projectBar.js:88:229 at https://editor.construct.net/r388-2/main.js:1933:388
Stack: TypeError: expected finite number at P.B (https://editor.construct.net/r388-2/main.js:1051:407) at d.lq (https://editor.construct.net/r388-2/projectResources.js:611:327) at d.Aa (https://editor.construct.net/r388-2/projectResources.js:1799:110) at d.Dg (https://editor.construct.net/r388-2/projectResources.js:1793:395) at https://editor.construct.net/r388-2/components/bars/projectBar/projectBar.js:88:229 at https://editor.construct.net/r388-2/main.js:1933:388
Construct version: r388.2
URL: https://editor.construct.net/
Date: Tue May 28 2024 11:03:36 GMT-0230 (Newfoundland Daylight Time)
Uptime: 235.7 s

Platform information
Product: Construct 3 r388.2 (stable)
Browser: Chrome 125.0.6422.77
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 (0x00001F07) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/8025
