### ISSUE TITLE
Json Editor crashes line 1

### ISSUE THREAD

**Issue by crugh** [Scirra/Construct-3-bugs#805]
## Problem description
Json Editor crashes line 1 when edited an uploaded json file
*Enter a concise description of your problem here*
Error report information
Type: unhandled exception
File: https://editor.construct.net/r55/components/editors/dataEditor/dataEditor.js, line 1, col 25181
Message: Uncaught TypeError: a.split is not a function
Stack: TypeError: a.split is not a function at Object.ǃ_$ (https://editor.construct.net/r55/components/editors/dataEditor/dataEditor.js:1:25181) at Object.ǃJG (https://editor.construct.net/r55/components/editors/dataEditor/dataEditor.js:1:26065) at Object.ǃJQ (https://editor.construct.net/r55/components/editors/dataEditor/dataEditor.js:1:23788) at HTMLDivElement.ǃEX.addEventListener (https://editor.construct.net/r55/components/editors/dataEditor/dataEditor.js:1:23315) at HTMLDocument. (https://editor.construct.net/r55/main.js:2:255416)
Construct 3 version: r55
URL: https://editor.construct.net/
Date: Fri Sep 15 2017 11:41:15 GMT-0400 (EDT)
Uptime: 52.4 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.79
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36
C3 release: r55

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
@shortercode - see if the stack trace makes sense, but if not, just close it, there's no steps to reproduce.

**Comment by shortercode** [comment]
Found it, there was a piece of code that assumed the cell contained a string.

**Comment by crugh** [comment]
Thanks... do I need to fix my json file?  Or is this bug and will updated the next update.  I never had any problems with this until the last update earlier this week.  I have used a template program that I modify the sprites and a json file for the last couple of months with out any crashes.
  

    On Friday, September 15, 2017 12:48 PM, Iain Shorter <notifications@github.com> wrote:
 

 Found it, there was a piece of code that assumed the cell contained a string.—

**Comment by shortercode** [comment]
The bug was introduced in the new update, no issues with your json file.
I'm afraid their isn't much of a workaround. But you can use r54 instead
which shouldn't have the problem. We'll publish a release with a fix soon.

**Comment by crugh** [comment]
Thanks.  I have been downloading the file, editing it with an array editor then uploading again.  That is ggod news that it will be fixed. 

    On Friday, September 15, 2017 5:55 PM, Iain Shorter <notifications@github.com> wrote:
 

 The bug was introduced in the new update, no issues with your json file.
I'm afraid their isn't much of a workaround. But you can use r54 instead
which shouldn't have the problem. We'll publish a release with a fix soon.

**Comment by mauriciolaser** [comment]
¡Thanks for noticing! And thanks for taking care of this, despite the difficulty of attaching a project file. :) hope you can fix it soon.

**Comment by shortercode** [comment]
Okay should be fixed in r56 when it comes out.

For reference this issue was if you opened an existing array or dictionary file which contained a number value, then attempted to edit that value.
