### ISSUE TITLE
Copy/Paste crash in animation/image editor

### ISSUE THREAD

**Issue by Rhindon** [Scirra/Construct-3-bugs#806]
## Problem description

Copied image from one frame to another frame in the same animation. The image being copied was larger than the frame the image was (attempted) to be copied to. The editor then crashed.

## Attach a .c3p

Issue is within the editor, itself. It is a User Interface problem.

## Steps to reproduce

1. Copy an image in the image/animation editor for a sprite object.
2. Paste image into a frame with a smaller height/width than the copied image.
3. When prompted to expand frame size, press Enter and do not select one of the two buttons.

## Observed result

The above dialogue error.

## Expected result

The size of the frame to adjust and the image to be pasted.

## Affected browsers

* Chrome: Yes
* Firefox: Untested
* Edge: Untested
* Safari: Untested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r55/main.js, line 2, col 176235
Message: Uncaught TypeError: expected string
Stack: TypeError: expected string at Function.ǃd.ǃm (https://editor.construct.net/r55/main.js:2:176241) at ǃd.ǃV.ǃzG.ǃzVg.ǃmQ (https://editor.construct.net/r55/main.js:71:325808) at ǃd.ǃV.ǃzG.ǃzVg.ǃWi (https://editor.construct.net/r55/main.js:2:331154) at r.ǃWi (https://editor.construct.net/r55/main.js:2:304887) at HTMLDocument.window.C3_IsPopupWindow.t.document.addEventListener (https://editor.construct.net/r55/main.js:2:303183)
Construct 3 version: r55
URL: https://editor.construct.net/
Date: Thu Sep 14 2017 20:22:11 GMT-0500 (Central Daylight Time)
Uptime: 19509.6 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.79
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36
C3 release: r55

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: Google SwiftShader
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 0.125 to 2048
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r57.

Now when you press "Enter" the highlighted option will be selected.

**Comment by Rhindon** [comment]
Awesome! Thank you, Diego.
