### ISSUE TITLE
Copy/Paste shortcuts doesn't work on pop-up event sheet

### ISSUE THREAD

**Issue by Bro7hers** [Scirra/Construct-3-bugs#807]
## Problem description
When an event sheet is open in a Pop-up window, it is not possible to copy and paste with the common shortcuts Ctrl+C and Ctrl+V.

## Attach a .c3p
That is true even for an empty project.

## Steps to reproduce

1. Undock event sheet.
2. Open it in a pop-up window
3. Add some event
4. Try to copy paste it with shortcuts.

## Observed result
Nothing happens.

## Expected result
The event should be copied as it is with right-click -> copy ; right-click -> paste.

## Affected browsers

* Chrome: yes
* Firefox: yes

**Comment by AshleyScirra** [comment]
Hmm, it's not just copy-paste, it's most keyboard shortcuts, like arrow key navigation, 'D' to toggle disabled, etc. Still, the context menus work.

**Comment by AshleyScirra** [comment]
OK, should be working in r80.
