### ISSUE TITLE
Firefox: crash on open demo project

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#809]
## Steps to reproduce

1. try to open kiwi story
2. notice the crash after the download has finished

* Firefox: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information

Type: unhandled exception
File: https://editor.construct.net/r55/main.js, line 61, col 26591
Message: Error: failed to initialise WebGL context
Stack: ǃd.ǃcW.ǃcQ<@https://editor.construct.net/r55/main.js:61:26591 ǃd.ǃG@https://editor.construct.net/r55/main.js:2:204880 ǃCy@https://editor.construct.net/r55/components/editors/layoutView/layoutView.js:1:39493 ǃqA@https://editor.construct.net/r55/components/editors/layoutView/layoutView.js:1:6527 window.ǃqC Construct 3 version: r55
URL: https://editor.construct.net/
Date: Sat Sep 16 2017 22:06:38 GMT+0300 (GTB Standard Time)
Uptime: 124.5 s
Unable to collect further diagnostic information because a promise rejection occurred while trying to collect it.

</details>

**Comment by AshleyScirra** [comment]
I can't reproduce here, but the error looks like WebGL is actually blacklisted and unavailable. We hard-coded support for Firefox for C3 but I think this lets it through even when WebGL is unavailable. I've adjusted the support check to make sure this will show an error in Firefox too.

**Comment by JeFawk** [comment]
I tried with r56 and got this crash now when the download finished

Error report information

Type: unhandled exception
File: https://editor.construct.net/r56/main.js, line 2, col 0
Message: NS_ERROR_NOT_IMPLEMENTED:
Stack: r/this.ǃYHK@https://editor.construct.net/r56/main.js:2:83711 n@https://editor.construct.net/r56/main.js:2:88048 a@https://editor.construct.net/r56/main.js:2:88261 getEntries@https://editor.construct.net/r56/main.js:2:88866 ǃDj/ Construct 3 version: r56
URL: https://editor.construct.net/
Date: Mon Sep 18 2017 16:45:41 GMT+0300 (GTB Standard Time)
Uptime: 75.3 s
Platform information

Browser: Firefox
Browser version: 55.0
Browser engine: Gecko
Browser architecture: 32-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0
C3 release: r56
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_texture_filter_anisotropic, EXT_disjoint_timer_query, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_lose_context, MOZ_WEBGL_lose_context, MOZ_WEBGL_compressed_texture_s3tc

**Comment by AshleyScirra** [comment]
It works fine for me in Firefox 55. It's weird if it previously couldn't create a WebGL context, I don't know why it would be working now? Did you disable the GPU blacklist or something?

**Comment by JeFawk** [comment]
I had the WebGL disabled in the about:config for a long time, sorry I forgot. However my last message was with it turned on. I might try reinstalling Firefox to see if it fixes it.
