### ISSUE TITLE
Chrome: Bug on opening Construct 3

### ISSUE THREAD

**Issue by tunchunairarko** [Scirra/Construct-3-bugs#810]
Hi I found a bug in Construct 3

[Linguiso.zip](https://github.com/Scirra/Construct-3-bugs/files/1308876/Linguiso.zip)
Error report information
Type: unhandled rejection
Reason: Error: display text for 'treeondisconnectedcancel36' has incorrect placeholder '{0}' @ Error: display text for 'treeondisconnectedcancel36' has incorrect placeholder '{0}' at window.ǃzHn.ǃzdr (https://editor.construct.net/r55/main.js:61:301298) at new window.ǃzHn (https://editor.construct.net/r55/main.js:61:305238) at Function.ǃd.ǃG (https://editor.construct.net/r55/main.js:2:204874) at window.ǃzdM.ǃzzK (https://editor.construct.net/r55/main.js:61:306768) at window.ǃzKd.ǃzUJ (https://editor.construct.net/r55/main.js:61:429104) at u.ǃXE (https://editor.construct.net/r55/main.js:71:29308) at Object.t.push.ǃd.ǃHrx [as ǃHnt] (https://editor.construct.net/r55/main.js:71:29678) at t (https://editor.construct.net/r55/main.js:2:263009) at d (https://editor.construct.net/r55/main.js:2:262795)
Stack: Error: display text for 'treeondisconnectedcancel36' has incorrect placeholder '{0}' at window.ǃzHn.ǃzdr (https://editor.construct.net/r55/main.js:61:301298) at new window.ǃzHn (https://editor.construct.net/r55/main.js:61:305238) at Function.ǃd.ǃG (https://editor.construct.net/r55/main.js:2:204874) at window.ǃzdM.ǃzzK (https://editor.construct.net/r55/main.js:61:306768) at window.ǃzKd.ǃzUJ (https://editor.construct.net/r55/main.js:61:429104) at u.ǃXE (https://editor.construct.net/r55/main.js:71:29308) at Object.t.push.ǃd.ǃHrx [as ǃHnt] (https://editor.construct.net/r55/main.js:71:29678) at t (https://editor.construct.net/r55/main.js:2:263009) at d (https://editor.construct.net/r55/main.js:2:262795)
Construct 3 version: r55
URL: https://editor.construct.net/index.html
Date: Sun Sep 17 2017 12:04:45 GMT+0600 (Bangladesh Standard Time)
Uptime: 25.1 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r55

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 7520G Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by Ind1eed** [comment]
Same here. Versions R55 and R54.

**Comment by AshleyScirra** [comment]
The project uses third-party addons. Please see the bug report guidelines, we do not accept bug reports relating to third-party addons. The error message appears related to loading the third-party addons, so the addon developer needs to fix it.

- Plugin Authentication (Rex_Firebase_Authentication) by Rex.Rainbow
- Plugin Firebase API v3 (Rex_FirebaseAPIV3) by Rex.Rainbow

**Comment by Ind1eed** [comment]
Well i meant  that part with "Error loading, unhandled promise rejection".
during startup. I cleared my cache like 1,000000000000 times and still
doesn't work.
18.09.2017 1:20 PM "Ashley (Scirra)" <notifications@github.com> napisał(a):
