### ISSUE TITLE
Construct 3 sometimes freezing when starting multiplayer

### ISSUE THREAD

**Issue by newman321** [Scirra/Construct-3-bugs#811]
Sometimes When i start Remote previewing my project c3 freezes and i can do nothing.

i dont think this happen in so small projects so i can not make a minimal construct file but in my not so big project i get this problem i can privately send c3p file to a moderator.

**Comment by newman321** [comment]
im ready to send .c3p file and steps to reproduce it are described what does ignored guidelines  means ? :|

**Comment by AshleyScirra** [comment]
Sorry, these kinds of report are not useful. We generally don't want your whole project, see the bug report guidelines for what to do.
