### ISSUE TITLE
An instance is being picked when it's not supposed to (Families)

### ISSUE THREAD

**Issue by valerypopoff** [Scirra/Construct-3-bugs#815]
## Problem description

An instance is being picked when it's not supposed to when messing with Families. See event 5. 

p.s.: It seems like when I use OR event block, the instances are being picked from scratch as if there was no picking in event 4. But when I use AND event block, the instances are being picked from the pool of instances that is already filtered by picking in event 4. Here's an extra demonstration on that: 
[Bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1314689/Bug.c3p.zip)

## Attach a .c3p

[digger.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1311083/digger.c3p.zip)

## Steps to reproduce

1. Run the project
2. Press any key 

## Observed result

Both Enemy (red square) and Digger (blue square) moved.

## Expected result

Only Digger (blue square) should move. Enemy should stand still.

## Affected browsers

* Chrome: yes
* Yandex browser: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 59.0.3071.125
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 YaBrowser/17.7.1.720 Yowser/2.5 Safari/537.36
C3 release: r56
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 26 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon HD 6770M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think I finally figured this one out. OR blocks are very complicated :P First of all the demo project uses "pick by comparison" and then manually matches the UID. It works correctly if you just use the "pick by UID" condition. Since a different condition is used the OR block in a sub-event appears able to pick from instances that failed the parent event (in "pick by comparison") which produces the wrong result. This should be fixed in the next release but I'm a little nervous about how the backwards compatibility of this will play out - let's see how it goes.
