### ISSUE TITLE
STARTUP.

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#816]
## Problem description
Error on startup. On versions > R54 

## Attach a .c3p
n/a

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*
Error loading! try disabling browser addons, they can sometimes break construct 3. Unhandled promise rejection [object event]
## Expected result
Start.
## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Sorry, there's nothing we can do with such little information.
