### ISSUE TITLE
Tilemap's editor crash

### ISSUE THREAD

**Issue by flipog** [Scirra/Construct-3-bugs#817]
## Problem description

Whenever I click any tool in the tilemap's editor, construct crashes

## Attach a .c3p

Every file should suffer from this.

## Steps to reproduce

1. Open any file
2. Try to edit a tilemap
3. It should have crashed instantly

## Observed result

It crashes

## Expected result

Not crashing

## Affected browsers

* Chrome: yes
* Firefox: did not test
* Edge: n/a
* Safari: n/a

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r56/components/bars/tilemapBar/tilemapBar.js, line 1, col 3664
Message: Uncaught TypeError: r.ǃZp.ǃZA is not a function
Stack: TypeError: r.ǃZp.ǃZA is not a function at e.ǃQg (https://editor.construct.net/r56/components/bars/tilemapBar/tilemapBar.js:1:3664) at e.window.ǃrZ.ǃGE (https://editor.construct.net/r56/components/bars/tilemapBar/tilemapBar.js:1:7798) at e.window.ǃrZ.ǃZS (https://editor.construct.net/r56/components/bars/tilemapBar/tilemapBar.js:1:7268) at ǃj.Event.ǃYJL.ǃYJd (https://editor.construct.net/r56/main.js:2:260369) at ǃj.ǃo.ǃbv.dispatchEvent (https://editor.construct.net/r56/main.js:2:258641) at ǃj.ǃo.ǃI.ǃjnG.ǃYiH.ǃjIL (https://editor.construct.net/r56/main.js:2:519262) at ǃj.ǃo.ǃI.ǃjnG.ǃYiH.ǃjIo (https://editor.construct.net/r56/main.js:2:518605) at ǃj.ǃo.ǃI.ǃjnG.ǃYiH.ǃjIv (https://editor.construct.net/r56/main.js:2:519009) at ǃjI$ (https://editor.construct.net/r56/main.js:2:516249)
Construct 3 version: r56
URL: https://editor.construct.net/
Date: Mon Sep 18 2017 16:28:27 GMT-0300 (E. South America Standard Time)
Uptime: 22.8 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r56
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by flipog** [comment]
Right now I'm extremely disappointed. This is the 3rd major issue with tilemaps in less than a month and by major I mean, some kind of problem that completely unables me to develop my projects.

**Comment by AshleyScirra** [comment]
We'll have an update out on Tuesday that fixes it. Remember if you run in to any issues, you can roll back to the previous version and carry on.

**Comment by MarcoWorms** [comment]
@AshleyScirra don't you guys have tests for this? I mean, if something has already broken 3 times before I think it's wise to add coverage for it on your test suite so it won't break again :P

**Comment by ArsCreativa** [comment]
Hi, just updated to r56, but now I have this tilemap crash problem.

Error report information
Type: unhandled exception
File: https://editor.construct.net/r56/components/bars/tilemapBar/tilemapBar.js, line 1, col 3664
Message: Uncaught TypeError: r.ǃZp.ǃZA is not a function
Stack: TypeError: r.ǃZp.ǃZA is not a function at e.ǃQg (https://editor.construct.net/r56/components/bars/tilemapBar/tilemapBar.js:1:3664) at e.window.ǃrZ.ǃGn (https://editor.construct.net/r56/components/bars/tilemapBar/tilemapBar.js:1:7568) at e.window.ǃrZ.ǃZS (https://editor.construct.net/r56/components/bars/tilemapBar/tilemapBar.js:1:7220) at ǃj.Event.ǃYJL.ǃYJd (https://editor.construct.net/r56/main.js:2:260369) at ǃj.ǃo.ǃbv.dispatchEvent (https://editor.construct.net/r56/main.js:2:258641) at ǃj.ǃo.ǃI.ǃjnG.ǃYiH.ǃjIL (https://editor.construct.net/r56/main.js:2:519262) at ǃj.ǃo.ǃI.ǃjnG.ǃYiH.ǃjIo (https://editor.construct.net/r56/main.js:2:518605) at ǃj.ǃo.ǃI.ǃjnG.ǃYiH.ǃjIv (https://editor.construct.net/r56/main.js:2:519009) at ǃjI$ (https://editor.construct.net/r56/main.js:2:516249)
Construct 3 version: r56
URL: https://editor.construct.net/index.html
Date: Tue Sep 19 2017 08:09:14 GMT+0200 (Hora de verano romance)
Uptime: 21.9 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r56
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context
