### ISSUE TITLE
Selection box travels

### ISSUE THREAD

**Issue by insanesnake** [Scirra/Construct-3-bugs#820]
Don't know if this is a known issue, But I got a very small sprite. if I select it the selection box is out of place. if I zoom in on the sprite the selection box will slide towards it and jump over it, if I zoom out the selection box goes up and away from the sprite image. 

don't believe it's an issue that has to be solved with haste, but it does throw me off

keep up the good work! loving C3 so far!

**Comment by insanesnake** [comment]
http://prntscr.com/gn2jsn <- fine
http://prntscr.com/gn2k0j <- selection box goes off
http://prntscr.com/gn2kfg <- selection box is way off

**Comment by AshleyScirra** [comment]
Sorry, there's nothing we can do to help unless you follow the bug report requirements.
