### ISSUE TITLE
Parameter value dropdown list doesn't show objects' attributes

### ISSUE THREAD

**Issue by NitidOnline** [Scirra/Construct-3-bugs#822]
## Problem description
 
When you want to use an object attribute in a parameter value textfield, the dropdown list only shows the first level objects despite you use a dot to access their attributes.

## Attach a .c3p

Any example project.

## Steps to reproduce

1. Create a object with a variable
2. Create an action Set Value with that object
3. In tha value textbox type Object.
4. After writing the dot dropdown should show the attributes under Object but it doesn't.

## Observed result

The dropdown list only show the main level objects list.

## Expected result

The dropdown list should show the attributes of an object.

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by cihanyakar** [comment]
Functions also not listed.
![image](https://user-images.githubusercontent.com/5078937/30641976-9ada4714-9e11-11e7-8bf2-6aa04ece0fb1.png)

**Comment by mauriciolaser** [comment]
Bumping this issue. System expressions are not being listed either.

**Comment by cihanyakar** [comment]
May be related to #826

**Comment by AshleyScirra** [comment]
We updated our minifier used on build and it had a bug which mangled some of the autocomplete code and caused this. I've worked around it for the next build, it should be working in r58.
