### ISSUE TITLE
Dark theme: Remote preview QR code not working

### ISSUE THREAD

**Issue by shinkan-fb** [Scirra/Construct-3-bugs#823]
## Problem description

It looks like it's not possible to scan QR code while using dark theme. 
Tested few android phones with few different QR scanning apps and none of them work.
On C3 "default" color theme it takes just a second to scan the code successfully. 

## Steps to reproduce

1. Open C3
2. Choose "Dark Theme" from settings
3. Restart C3
4. Open random project and choose "Remote preview"
5. Try scanning the QR code

## Observed result

Nothing happens, all tested QR apps behave like there was no code on the screen.

## Expected result

Scanning app should scan QR code with no problems.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r57
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 194 mb (1.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 780 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Well... the main problem seems to be the entire Remote Preview dialog has a transparent background in the dark theme. You didn't mention that - are you seeing that too?

I think if the background is transparent and the layout is showing behind, it's too high-contrast and confuses the QR code scanner. I've added an extra white border around the QR code for the next release, which seems to help but not completely solve it. I think fixing the transparent background should fix this!

**Comment by shinkan-fb** [comment]
Oh, yes You are right, I didn't noticed the transparency cause I never moved the dialog around and at that time I also had an empty layer with black color on it... so all of it looks quite normal.

**Comment by Animmaniac** [comment]
Fixed for next theme release.
