### ISSUE TITLE
Dark Theme: Remote Preview

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#824]
## Problem description
Simply, the remote preview freezes on 66%. 

## Attach a .c3p

n/a

## Steps to reproduce

1. Open construct 3
2. Select remote preview.
3.

## Observed result
Freezes at 66%.

In the browser console i see these errors:

Failed to load resource: the server responded with a status of 404 ()
/#ckjhae8c:1 Uncaught (in promise) DOMException: Unable to decode audio data
/pl/edm%20sub1%20extended.mp3 Failed to load resource: the server responded with a status of 404 ()
/#ckjhae8c:1 Uncaught (in promise) DOMException: Unable to decode audio data
/pl/diabelli%20sonatina%20168.mp3 Failed to load resource: the server responded with a status of 404 ()
/#ckjhae8c:1 Uncaught (in promise) DOMException: Unable to decode audio data
/pl/anw2752_03_hallucinogenic-dreams.mp3 Failed to load resource: the server responded with a status of 404 ()
/#ckjhae8c:1 Uncaught (in promise) DOMException: Unable to decode audio data
/pl/campfire.mp3 Failed to load resource: the server responded with a status of 404 ()
/#ckjhae8c:1 Uncaught (in promise) DOMException: Unable to decode audio data
/pl/arcade%20funk.mp3 Failed to load resource: the server responded with a status of 404 ()
/#ckjhae8c:1 Uncaught (in promise) DOMException: Unable to decode audio data
*What do you see happen?*

## Expected result

Open remote preview.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Are you sure this is to do with the theme? Does it still happen if you change the theme back to default?

Also the errors reference MP3 files in your project, but you didn't provide it, so we can't reproduce what you are doing. Please always follow the bug report guidelines.

**Comment by Ind1eed** [comment]
Well, it doesn't work on light theme, too. 
Also, i installed the game on my device (Samsung Galaxy Note 4) and it says: Application Error, the connection to the server was unsuccesful (file:///android_asset/www/index/html)

**Comment by AshleyScirra** [comment]
OK, so that proves it isn't to do with the dark theme. I'm afraid there's nothing we can do unless you follow all the bug report guidelines, though. We need all that information to be able to help you.

**Comment by Ind1eed** [comment]
Do you want a link to remote preview or a .c3p file? Can you discover it
remotely?

2017-09-20 20:35 GMT+02:00 Ashley (Scirra) <notifications@github.com>:

**Comment by AshleyScirra** [comment]
Please read the bug report guidelines. The .c3p file is required.

**Comment by Ind1eed** [comment]
Ok.. so here you are. Try to export that into working .apk

2017-09-20 21:44 GMT+02:00 Ashley (Scirra) <notifications@github.com>:

**Comment by Ind1eed** [comment]
I provided the .c3p to the support.
