### ISSUE TITLE
Autocomplete is broken in expressions in various ways (doesn't jump to the right term, appends whatever string was previously auto-completed even when it's not appropriate, etc.)

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#826]
## Problem description

When typing an expression, the autocomplete is broken in several ways. If you begin the expression with a number (i.e. 1000) and follow it with an operator followed by a letter (i.e., the first letter of the variable you want to use), the autocomplete list won't appear at all. On the other hand if you start with a variable name followed by an operator and a number, the autocomplete list will appear when you start typing the number. I.e., typing "GlobalVariable1/100" will make the autocomplete list appear after "1", and if you hit enter or try to add another operator once you've finished typing, autocomplete will append "GlobalVariable1" (the last used autocomplete string) to the 100. Furthermore, if you continue by adding another operator and attempt to add another variable to the expression, autocomplete appears but fails to function. So, "GlobalVariable1/100/ti" will cause the autocomplete list to appear, and should cause autocomplete to jump to the "time" system property, but it doesn't. Again, if you hit enter, even after fully typing out "time", "GlobalVariable1" will be appended to your expression and you wind up with "GlobalVariable1/100/timeGlobalVariable1". Also, if you start to type an instance variable into a new expression field (i.e., "Sprite.") the autocomplete appears but doesn't function. So, if you continue typing "Sprite.Variable1", the autocomplete selection stays on "Sprite", and hitting enter at any point will append "Sprite" to the expression.

## Attach a .c3p

This is so simple to reproduce in a new project I'm skipping the .c3p.

## Steps to reproduce

1. Create a global variable, i.e. Variable1.
2. Create an event condition, i.e. System:Compare two values.
3. In one of the expression fields, type "Variable1/100" and hit enter

## Observed result

The expression becomes "Variable1/100Variable1". (There are loads of other similar problems, please see the problem description).

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.79
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36
C3 release: r57
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 45 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by wiverson** [comment]
Seeing same issue in r57.

**Comment by jakemay74** [comment]
Yeah, still in r57. Also occurs when typing punctuation after an expression e.g.:

choose(1choose,2choose)

**Comment by AshleyScirra** [comment]
I think this is the same as #822.
