### ISSUE TITLE
Crash when changing layout width or height to 1 or less

### ISSUE THREAD

**Issue by SebaGenetic** [Scirra/Construct-3-bugs#829]
## Problem description

If you change the layout height or width to 1 or less construct 3 crashes and needs to restart

## Attach a .c3p

[layout crash.zip](https://github.com/Scirra/Construct-3-bugs/files/1322224/layout.crash.zip)
any project will do.

## Steps to reproduce

1. open any project or create a new one
2. click on a layout
3. change it's width or height to 1 or less
4. profit

## Observed result

Crash

## Expected result

Width or height should be set to the minimum possible or get an error about the number not being valid.

## Affected browsers

Chrome: yes
Firefox: yes
Opera: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r58/main.js, line 61, col 237072
Message: Uncaught Error: invalid layout height
Stack: Error: invalid layout height at a.ǃSS (https://editor.construct.net/r58/main.js:61:237078) at ǃC.ǃG.ǃe.ǃCgB.a.ǃIM [as ǃCgW] (https://editor.construct.net/r58/components/bars/propertiesBar/propertiesBar.js:1:13229) at ǃC.ǃG.ǃe.ǃCgB.ǃCXH (https://editor.construct.net/r58/main.js:2:418542) at ǃC.ǃG.ǃe.ǃCgB.ǃZII (https://editor.construct.net/r58/main.js:2:425637) at HTMLInputElement.ǃCXD (https://editor.construct.net/r58/main.js:2:416800) at ǃC.ǃG.ǃe.ǃCgB.ǃEF (https://editor.construct.net/r58/main.js:2:426982) at HTMLInputElement.ǃCXE (https://editor.construct.net/r58/main.js:2:417975)
Construct 3 version: r58
URL: https://editor.construct.net/
Date: Thu Sep 21 2017 14:27:33 GMT-0300 (Hora estándar de Montevideo)
Uptime: 33.9 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r58
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by SebaGenetic** [comment]
[layout crash.zip](https://github.com/Scirra/Construct-3-bugs/files/1322224/layout.crash.zip)

**Comment by XpMonster** [comment]
Why would you actually need to change Layout size to 1 in the first place? ;D

**Comment by SebaGenetic** [comment]
@XpMonster While I don't want to change the size to 1, I don't think that's a reason for a crash.  
I discovered this because when I went to type 1366 y pressed 1 and then Enter (on the numerical keyboard).   
For example if I set the size to 13513513513513531 it automatically goes to 10000 which is the maximum, it should work the same when you put a low number and go to the minimum.

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r59.
