### ISSUE TITLE
[r18.2] Debug preview window mode cannot restart

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#83]
## Problem description

When entering the debug preview, you can split the screen of the debugger to have it's own window. Once you do that, you couldn't restart the debug preview by pressing the restart button.

## Steps to reproduce

1. Preview in debug mode.
2. Pop-up the debugger to it's own window. (the icon at the top very end. Beside the restart button)
3. Press "Restart".

## Observed result

Cannot restart.

## Expected result
Can restart.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r19.
