### ISSUE TITLE
"Periodically back up projects" breaks "Save the project back to it's last location" feature

### ISSUE THREAD

**Issue by valerypopoff** [Scirra/Construct-3-bugs#830]
## Problem description

"Periodically back up projects" breaks "Save the project back to it's last location" feature. 

With "Periodically back up projects" setting on, after back up file is saved into local storage, the shortcut "Save the project back to it's last location" starts to work incorrectly. It keeps saving a project to a local storage with the name Projectname_autosave_.c3p (!!!) even after you do "Save As → Cloud drive". It persists until you reopen the project.

## Attach a .c3p

Any project is ok to reproduce

## Steps to reproduce

1. Turn "Periodically back up projects" setting on
2. Open a project, make changes
3. Wait till Construct automatically saves a backup
4. Do "Save As → Cloud drive"
5. Do "Save the project back to it's last location"

## Observed result

It saves a project into a local storage with the name Projectname_autosave_.c3p

## Expected result

It saves a project into a cloud

## Affected browsers

Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r57
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 115 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Thanks for finding this, I found 2 bugs here. Firstly when a project autosaved for the first time it was changing the project origin to the autosaved file (autosave should **not** effect the origin). Secondly when saving to an existing file with a different origin than the current origin would not update the origin, this is why once it had autosaved the quick save button was stuck on the autosave location.

Both these fixes should be in r59 when it's published.
