### ISSUE TITLE
Function params acting funny

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#831]
## Problem description

Since r56 or so this issue has appeared. Sometimes when I try to modify parameters when calling a function the caret goes crazy. It either skips the field I press on or just goes to a random one.

I cannot reproduce it (i know you might say "we can't do much in that case"), but maybe you kinda have a clue what could be causing this.

Restarting the project temporarily fixes it.

## Attach a .c3p

![animation](https://user-images.githubusercontent.com/7268697/30749049-d71f6538-9fba-11e7-8fce-95e8c6d24c53.gif)

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r58
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 534 mb (7.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by mOOnpunk** [comment]
I'm getting the crazy caret as well, only for me it happens when trying to enter values in a "for" loop. The caret acts as though the delete button is stuck down and is constantly erazing anything i type.

Infact the who things getting worse. Autocomplete still doesnt work right and is a pain, and now sometimes the caret gets stuck on a highlighted bracket in an expression and wont move.

**Comment by AshleyScirra** [comment]
In r57 we added bracket highlighting which I think caused an issue around this. I just fixed #832 which looks similar so I think this ought to be fixed in the next build. You did not provide a .c3p for me to verify if that fix has also fixed your case, so closing.

**Comment by JeFawk** [comment]
Since I cannot reproduce it without a big amount of chance, I'm not sure if putting an almost empty .c3p would help.

**Comment by AshleyScirra** [comment]
Have you noticed this happening in r59 at all?

**Comment by JeFawk** [comment]
I didn't notice it, however, I didn't have much time to work with r59 yet. If it happens again I'll come back here with a new comment.
