### ISSUE TITLE
System -> Create Object - X value text box 

### ISSUE THREAD

**Issue by 8bitThirsty** [Scirra/Construct-3-bugs#832]
## Problem description

The X value text box in system -> create object automatically moves to the next text box when you press any button.  If you delete the value you can't get back to the box.  

## Attach a .c3p

[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/1326115/New.project.zip)

## Steps to reproduce
![create object x position](https://user-images.githubusercontent.com/11980014/30767631-41e40552-9fcc-11e7-83b6-1716509c5634.gif)

## Affected browsers

* Chrome: yes
Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next build.
