### ISSUE TITLE
Cannot Open from Cloud (Dropbox) on Android

### ISSUE THREAD

**Issue by KENYONBcom** [Scirra/Construct-3-bugs#833]
Cannot open a saved project from Dropbox on Android.

C3 version r58
Android v 8.0.0
Pixel XL

## Steps to reproduce

1. open C3 on Android
2. click Open
3. click "open from cloud"
4. API request opens as pop-up
5. click "Personal" button
6. blank/empty window opens

## Observed result

Nothing happens. Nothing ever loads in the window. Pulling down to refresh does nothing.
Press back just relaunches Construct 3

## Expected result

I expect to select a project from Dropbox. I already authorized from the desktop version and saved a project.

## Affected browsers

* Chrome: yes

## System details

no crash report. no error message.

**Comment by shortercode** [comment]
I tried this a few times, and it seems to work fine. Saying that, I did have some issues where the main C3 window would navigate back occasionally but only on my phone. Debugging that issue with Ashley at the moment. Did this issue always happen for you?

**Comment by KENYONBcom** [comment]
I only recently purchased C3 and only tried saving and opening from Cloud options yesterday on the latest version. In my brief history with C3, yes, always happened.

I do have a Personal and Business Dropbox account. Not sure if that is causing a hiccup.

**Comment by shortercode** [comment]
I don't think it's related to having both personal and business, the account I was testing with has both as well. Does the blank pagehave the url `editor.contruct.net/cloudauth.html[...]`? or is it just a blank page

**Comment by KENYONBcom** [comment]
I click Open, select Cloud.

It opens this url in pop-up:
https://www.dropbox.com/oauth2/authorize?response_type=token&client_id=75tt20aoyg2ccbg&redirect_uri=https%3A%2F%2Feditor.construct.net%2Fcloudauth.html

I click on Personal, then it looks like it tries to return to the C3 app, but the entire screen is white.

**Comment by shortercode** [comment]
It should redirect to `https://editor.contruct.net/cloudauth.html[...]` after you have completed the login, that page is blank but is closed immediately by C3 so you shouldn't see it. C3 will still be open in a different tab during the login.

**Comment by KENYONBcom** [comment]
It is still open in Chrome, but after granting access, it appears it is trying to open the "app" I was prompted to save on my device when launching C3 in Chrome. The C3 app is blank. And closing that and returning to C3 tab in chrome says "cloud auth cancelled".

**Comment by KENYONBcom** [comment]
![screenshot_20170925-125054](https://user-images.githubusercontent.com/21185437/30820717-c4c8074a-a1f0-11e7-9f67-293496150c64.png)

**Comment by shortercode** [comment]
Ah okay I see the issue now, I wasn't aware you were using C3 in "app" mode. I will see if there's anything I can do to fix this. In the mean time if you run C3 in chrome instead you will be able to log into dropbox, and this will also login the "app" version.

**Comment by KENYONBcom** [comment]
I have tried it in the "app" and in Chrome. The result is same for both. As noted above, when I try from Chrome, after authorizing Dropbox, it tries to load the "app" instead of returning to Chrome. Manually closing the app and returning to editor in Chrome says "cloud auth cancelled".

**Comment by shortercode** [comment]
@KENYONBcom a revision was published a week or so ago which has fixed android login for me, is it working for you now?

**Comment by KENYONBcom** [comment]
Cloud sync works for me using Chrome browser. I deleted the "app" which fixed the mix-up during authorization. Since I don't use the app shortcut anymore, not sure if the issue still persists.

**Comment by shortercode** [comment]
Okay well thanks for letting me know! The app version works for me now so going to close this as fixed.
