### ISSUE TITLE
r58 - Editor crashes on iOS 11 when logged into account

### ISSUE THREAD

**Issue by dolomite** [Scirra/Construct-3-bugs#834]
## Problem description
On the iPad Pro (using 2016 9.7 model), iOS 11, accessing the Construct 3 editor by using Chrome or Safari, the editor loads when in Guest account. However, when logged into your personal account the editor crashes and throws and error message.

## Steps to reproduce

1. Open up the C3 editor on the iPad using either Chrome or Safari.
2. Login with personal account.
3. Crashes with error message.

## Observed result

Editor crashes with error message. Can't do anything else.

## Affected browsers

* Chrome: yes
* Safari: yes

## System details
Error report information
Type: unhandled rejection
Reason: Error: web crypto only available on secure origins @ ǃZcU@https://editor.construct.net/r58/main.js:2:229717 https://editor.construct.net/r58/main.js:165:1732712 promiseReactionJob@[native code]
Stack: ǃZcU@https://editor.construct.net/r58/main.js:2:229717 https://editor.construct.net/r58/main.js:165:1732712 promiseReactionJob@[native code]
Construct 3 version: r58
URL: https://editor.construct.net/
Date: Sun Sep 24 2017 23:39:18 GMT-0400 (EDT)
Uptime: 43.1 s

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.0
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores : (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1
C3 release: r58
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 50.8)
Numeric version: 1
Supports  NPOT  textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A9X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions: EXT_blend_minmax, EXT_sRGB, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_standard_derivatives, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context, WEBKIT_WEBGL_compressed_texture_pvrtc, WEBGL_depth_texture, ANGLE_instanced_arrays, WEBGL_debug_renderer_info

**Comment by newman321** [comment]
Same Problem with Ipad Air 2

**Comment by AshleyScirra** [comment]
Should be fixed in the next release.
