### ISSUE TITLE
Websocket not working

### ISSUE THREAD

**Issue by pedronasser** [Scirra/Construct-3-bugs#839]
[WebSocketTest.zip](https://github.com/Scirra/Construct-3-bugs/files/1331829/WebSocketTest.zip)
## Problem description

Websocket is not connecting to the websocket server.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Open attached c3p
2. Run with debug
3. Check if it connected (maybe change the address to another websocket server)

## Observed result

WebSocket's Last Error: Unable to create a WebSocket with the given address and protocol.

## Expected result

WebSocket should connect just like it connects on Construct 2

## Affected browsers

* Chrome: Yes
* Firefox: Yes
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r58
Language setting: en-US

Local storage
Storage quota (approx): 19 gb
Storage usage (approx): 41 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon (TM) R9 380 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The problem is Chrome blocks the connection, because you're using an insecure websocket (ws: not wss:) from a secure page (https://preview.construct.net). You can click the "load unsafe scripts" button in Chrome to allow Chrome to make the insecure connection, but a better idea is to use a secure websocket. Many features require HTTPS to work, so you should host your project on HTTPS anyway, which will have the same problem. Additionally secure websockets are more likely to successfully connect. There's not much we can do about this in C3 itself, we definitely do not want to host the preview on an insecure site.

**Comment by shortercode** [comment]
@pedronasser If your testing a local websocket server [allow insecure localhost](chrome://flags/#allow-insecure-localhost) is very useful. You might still need an SSL certificate but it can be self-signed, and doesn't need to have the correct domain name.

**Comment by AshleyScirra** [comment]
I just added a section on "Secure WebSockets and preview mode" to the [WebSocket manual entry](https://www.construct.net/make-games/manuals/construct-3/plugin-reference/websocket) to help clarify this.

IIRC there is some work being done to allow 'localhost' to be considered secure by itself, so you might not need SSL for localhost connections.
