### ISSUE TITLE
[r18.2] Won't reset preview window's properties

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#84]
## Problem description

In C2 when you close the preview, it would not remember the window's position was nor the size that was changed. It will reset itself, unless you leave the window open for all your previews. Here in C3, it would remember the resize you done to the preview window, including the position.

The position might not be the issue as it would be nice to have C3 remember it was viewed on another monitor. But as for the size, it would be ridiculous for me to manually resize to original window size if my project uses scale outer.

## Steps to reproduce

1. Preview project.
2. Move preview window and resize it.
3. Close preview window and re-preview.

## Observed result

The preview window remembered the previous resize and position.

## Expected result

Construct shouldn't remember the window resizing, but rather reset it each time the preview window is closed. It could become a daunting task to test screen sizes with original window size of the project if the project is using scale outer. It certainly breaks my workflow in this regard.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
The only C2 didn't remember the window size was because it couldn't (at least not easily) - it would have meant controlling an external application.

C3 remembers the preview window size by design. Another user specifically asked for this. I'm not sure why it would be a problem? Why would you have to keep resizing the window if it remembers the last size?

**Comment by jaydonteh** [comment]
## My reason for the change
Maybe it's just me. When I try to test my portrait game on a tablet form factor, I would scale the width of my window. And usually if I would want to look at the window again in the original width I would just close and re-open the preview browser.

## Reason for the current feature as redundant
I actually don't understand why the user who asked for this. Rather than closing the preview window that the user has manipulated, he can just keep it up and no size resets for each preview.

## My issue with the current feature
Now in C3, I had to close & restart C3 to get the windows reset to it's original size. Not to mention all my projects that was opened in C3 share the position & size of the preview! Imagine the extra work needed if the projects are in portrait and landscape mode. Why would I have to resize the preview window each time I switch from project to project preview. Resizing the window manually is inaccurate too.

**Comment by jaydonteh** [comment]
Before I re-open another bug issue, perhaps I should mention here and hear out your decision. Here is what I found:

When you preview in debugging mode, it does not remember it's window size. Which would be a bug if the  current feature you mentioned here is by design. But if not remembering the window size would the decision to go with in regards to my reasoning above, then this preview in debugging mode bug wouldn't be a bug at all.

**Comment by AshleyScirra** [comment]
If you want to test specific device screen sizes and orientations, it sounds like you should really be using Chrome's device mode. Press Ctrl+Shift+J to open dev tools and click the device icon in the top left, and you can easily switch between different emulated devices, without having to mess around with the main window size.

**Comment by jaydonteh** [comment]
That's a really neat developer feature. So I checked the device icon and unfortunately realised it wasn't available for C3 preview. The shortcut is CTRL+ SHIFT+ M for the device. It works on normal webpages open in chrome but not for C3's previews. That option is not there.

**Comment by AshleyScirra** [comment]
I think it needs the normal browser UI to be showing for the device option to appear. You can right-click in the caption and choose "show as tab", then the device mode option should be available.

**Comment by jaydonteh** [comment]
Desktop version of C3 through "Add to desktop" option will not have the "show as tab" option. Only open browser window, which just opens a new tab on the browser.

Only C3 through the browser could access this device mode feature.

**Comment by pixelmetal** [comment]
This certainly seems like a bug or oversight. As the browser features you're referring to aren't available on desktop, only when C3 is operating in a tab in Chrome specifically, features like this need to be provided to devs and accessible through the C3 interface.

**Comment by AshleyScirra** [comment]
Construct 2 didn't have any equivalent features for this, so it's not a regression.

**Comment by pixelmetal** [comment]
C2 was also a desktop application, and allowed preview in NW.js, where we could set the window size manually on the start of the layout. Not being a regression is also not the same thing as a feature that would be useful for developers, and which is available in popular game development tools (Unity, Unreal, GM:S).

**Comment by AshleyScirra** [comment]
OK, I've added a new 'browser tab' preview mode for r20. This always uses the full Chrome tab for preview, even when running from desktop. This means you can reliably use the existing dev tools device mode.

**Comment by pixelmetal** [comment]
This could be a good temporary solution, but still feels like a workaround by depending upon 3rd-party tools. Including some way to have preset aspect ratios/resolutions that can be added to by users directly within C3 (again, as other game engines have) without having to rely on Chrome-specific features could become more pressing as C3 IDE support is added for additional browsers and platforms which don't include such features. This could simply be options that are accessible from the Project Properties sidebar under the preview area.

**Comment by jaydonteh** [comment]
Thanks Ashley, this turns out to be me lacking​ of understanding of a better workflow by taking advantage of the browser's tools. Nice to see C3 and the browser complements developments.

The browser's tools aren't going anywhere, so it's fine. There are more things to better focus on than this i guess.
