### ISSUE TITLE
cant login to my account 

### ISSUE THREAD

**Issue by newman321** [Scirra/Construct-3-bugs#840]
when i opened editor i saw it shows im offline while i was online.

in details page, it said i can be offline for 5 more days then i need to get online so i just logged out and tried to log in again but i only can log-in in construct.net not in https://editor.construct.net/ when i try to log-in in editor it shows this error message 
![screenshot 2017-09-26 15 09 17](https://user-images.githubusercontent.com/426713/30858478-b7a85a56-a2cc-11e7-9d3b-76c2ce28a257.png)

PS: changing password does not helps with this problem

**Comment by newman321** [comment]
using chrome Version 61.0.3163.100 (Official Build) (64-bit) on Mac

**Comment by AshleyScirra** [comment]
We were just updating the server for the account system, maybe you hit it during the update. If you try again does it work now?

**Comment by newman321** [comment]
nope, still cant login changed my pass again

**Comment by newman321** [comment]
weird thing is now i can login with my ipad and firefox in macz(never logged in with it before) but not in chrome for mac
removed cookies but afraid to remove cache files as not sure if it may remove my project files too

**Comment by shortercode** [comment]
I believe @AshleyScirra has pushed a second update to the account system to fix a bug. I'm not sure how the cache behaves around the account system but you might be able to solve your problem by temporarily [disabling the http cache](https://stackoverflow.com/questions/5690269/disabling-chrome-cache-for-website-development).

**Comment by shortercode** [comment]
Also if your worried about losing your projects from browser save you should still be able to open the browser saves dialog and download your projects ( right click on the project and select download )

**Comment by newman321** [comment]
i dont see my project even when i try to open from local browser does it means i lost changes that were not backed up online yet ?

**Comment by newman321** [comment]
> Also if your worried about losing your projects from browser save you should still be able to open the browser saves dialog and download your projects ( right click on the project and select download )
 👍 1  

I just did what you recommended and it worked but lost my last changes.
i think this experiment shows importance of regular auto backups to cloud.
now im just waiting for forum to get live again and download addons i used again

**Comment by AshleyScirra** [comment]
Logins should be working now so closing issue.
