### ISSUE TITLE
Balloon tips have transparent background in Safari

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#841]
In Safari, balloon tips show with no background or outline. The only things that appear are the balloon tip text and icon. As with #813 a simple way to make a balloon tip:

1. Create a new project
2. Insert Text object
3. Try to rename it to "System" in the Properties Bar.

Easiest to reproduce on macOS but also reproduces on iOS.

I noticed the loading logo SVG is a bit glitchy after the build script, it might be some SVG is getting mangled by build. Alternatively maybe there's some styling that isn't applying in Safari.

**Comment by DiegoScirra** [comment]
I moved the creation of the SVG for the balloon tips into a template string, so the mangling shouldn't be affecting it anymore.

Still not entirely sure this will fix the problem, because I wasn't able to reproduce it in the development environment, even after minifying.

**Comment by AshleyScirra** [comment]
Nope, still reproduces in r60... there must be something in the SVG Safari doesn't like, or something else is being mangled by the build system that Safari doesn't like.

**Comment by DiegoScirra** [comment]
Should be fixed in r61.

Turns out there is a bug in Safari with inline SVG filters, which we were using to show a drop shadow around the balloon tips. 

Turns out you can use the CSS filter property in a DOM element wrapping the SVG and you can achieve the same effect without the bug.

**Comment by AshleyScirra** [comment]
Looks like it works now! 🎉
