### ISSUE TITLE
Android Export.

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#842]
## Problem description

The .apk doesn't work.

## Attach a .c3p

Provided the .c3p to the support.

## Steps to reproduce

1. Open construct.
2. Select Export > Android.
3. The exported app shouldn't work.

## Observed result

After launching app on my device (Samsung Galaxy Note 4) after few seconds, i see this error: Application Error, connection to the server was unsuccessful. (file:///android_asset/www/index.html).

## Expected result

Launch the application.

## Affected browsers

* Chrome: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Did you build a debug APK? Unsigned release APKs won't work until you publish them.

**Comment by Ind1eed** [comment]
Yes, i build debug APK.

**Comment by AshleyScirra** [comment]
Please try to follow the bug report guidelines. It is slower and more difficult to deal with issues when you email entire projects to us. If you can share a minimal project it will be much easier and quicker to solve any issues you report.

**Comment by Ind1eed** [comment]
I can't upload this here cause this file isn't smaller than 10MB.....

**Comment by shortercode** [comment]
@Ind1eed can you try building a minimal project, say a sprite, and try running that on your Note 4? Without a method for us to replicate the problem it's very hard to solve most issues.

**Comment by AshleyScirra** [comment]
The original report mentioned providing the .c3p to support. I can't find any emailed project so there's nothing we can do, closing.

**Comment by Ind1eed** [comment]
I created a new project, same error.

2017-09-26 19:17 GMT+02:00 Ashley (Scirra) <notifications@github.com>:

**Comment by Ind1eed** [comment]
You can try it by yourself, just export any project into .apk
