### ISSUE TITLE
[r59] - Changing UI Mode on iOS 11 causes crash 

### ISSUE THREAD

**Issue by dolomite** [Scirra/Construct-3-bugs#843]
## Problem description

When using the iPad Pro 9.7 (iOS 11), changing the UI Mode of C3 causes a crash. However, once the page reloads the UI change does take effect and is usable. This occurs on BOTH Safari and Chrome browsers.

## Steps to reproduce

1. Go to Menu/Settings/UI Mode - select any other option
2. Close dialogue, then new popup messages says "Restart Construct 3 for changes to take effect". Click OK
3. C3 crashes with error message

## Observed result

Error Message occurs. However, after clicking on Restart button at the bottom of error message, C3 will reload with the proper UI Mode that was selected.

## Expected result

Expected to restart without crash.

## Affected browsers

* Chrome: yes
* Safari: yes

## System details

Error report information
Type: unhandled rejection
Reason: Error: dialog not open @ ǃqZE@https://editor.construct.net/r59/main.js:2:327499 ǃXo@https://editor.construct.net/r59/main.js:2:328671 https://editor.construct.net/r59/main.js:152:1534225 promiseReactionJob@[native code]
Stack: ǃqZE@https://editor.construct.net/r59/main.js:2:327499 ǃXo@https://editor.construct.net/r59/main.js:2:328671 https://editor.construct.net/r59/main.js:152:1534225 promiseReactionJob@[native code]
Construct 3 version: r59
URL: https://editor.construct.net/
Date: Tue Sep 26 2017 11:02:46 GMT-0400 (EDT)
Uptime: 122.1 s

Platform information
Browser: Chrome for iOS
Browser version: 61.0.3163.73
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.0
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores : (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/61.0.3163.73 Mobile/15A372 Safari/602.1
C3 release: r59
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Metal - 50.8)
Numeric version: 1
Supports  NPOT  textures: partial
Supports GPU profiling: no
Vendor: Apple Inc.
Renderer: Apple A9X GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions: EXT_blend_minmax, EXT_sRGB, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_standard_derivatives, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, OES_vertex_array_object, OES_element_index_uint, WEBGL_lose_context, WEBKIT_WEBGL_compressed_texture_pvrtc, WEBGL_depth_texture, ANGLE_instanced_arrays, WEBGL_debug_renderer_info

**Comment by AshleyScirra** [comment]
This should be fixed in r60.
