### ISSUE TITLE
Adding a sprite from one family to another causes all family variables to vanish from the second, (added-to) family

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#846]
## Problem description

I added a sprite from one family to another family, and the second family (the one I added the sprite to) appeared to lose all its variables (of which there were many - at least 20 or so). Variables from the first family still appeared on the sprite, but that's it.

## Attach a .c3p

This is the closest thing I have to a minimal case, as I'm unable to repro this so far starting from scratch. Hopefully it sheds some light on what's going on. The problem is with the "Particle" family, which has a ton of variables that are no longer displaying.

[ParticleTest.zip](https://github.com/Scirra/Construct-3-bugs/files/1334786/ParticleTest.zip)

## Steps to reproduce

Note: This doesn't seem to actually reproduce the bug when done from scratch, but it's the closest I can recall to what I did to cause it in the attached project.

1. Create a sprite (oParticle)
2. Create two families (Particle and ScaleTween) and put the oParticle in both.
3. Add a ton of variables to Particle.
4. Add a fewer number of variables to ScaleTween.
5. Create another sprite (oScaleTween)
6. Add oScaleTween to the ScaleTween family, and remove the oParticle.
7. Close the "edit family" window, do some more work.
8. Add oParticle back to the ScaleTween family.
9. Look at the variables for the Particle family or the oParticle sprite.

## Observed result

All the Particle family variables have vanished, but are still accessible from the event editor/autocomplete, and the events that use these variables still function properly.

## Expected result

The variables in the Particle family should still be displayed.

## Affected browsers

* Chrome: yes
* Firefox: None of my projects will open in Firefox at the moment. I just get a popup window labeled Construct 3 and an OK button. 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 80 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Scoremonger** [comment]
Well, it looks like those variables were actually deleted. I tried reopening the project and they and their associated events are gone. So I'm guessing this project isn't useful for much in the way of diagnosis.

**Comment by Scoremonger** [comment]
Hopefully it's not too presumptuous, but I'm going ahead and closing this.

**Comment by AshleyScirra** [comment]
Haven't had the chance to even follow the repro steps yet, going to reopen until I can check.

**Comment by AshleyScirra** [comment]
This sounds a lot like #1197 which was fixed in r79. Without a reliable repro it's tough to verify, but I think it is likely the same issue. Please file a new issue with full details if you still run in to trouble with r79+.
