### ISSUE TITLE
Difficult to select slider bar button on touch devices

### ISSUE THREAD

**Issue by andychan1998** [Scirra/Construct-3-bugs#847]
## Problem description

When I try to adjust the slider bar button on a mobile device (only tried this on iPhone and iPad), very often the slider bar itself is selected, not the slider bar button.  I can select the slider bar button after a few tries, but it's often frustrating for the user.  For a slider bar, the user most likely wants to use the slider bar button, so it would be great if it can selected more easily.

## Attach a .c3p

https://drive.google.com/open?id=0B8XY81b11D4sRkdRN3FoNi1oU1k

## Steps to reproduce

1. Export the attached .c3p into a HTML5 game.  Load it onto a server.
2. Point to it from a mobile device (only tried on iPhone and iPad).
3. Try moving the slider bar button.

## Observed result

Very often, the slider bar itself is selected.

## Expected result

Ideally, the slider bar button can be more easily selected since users most likely want to adjust that.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: (not tried)
* Safari: yes (on mobile devices)

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r59
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 598 mb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I tried putting a slider element in an empty HTML document and it worked the same in Safari. So I think this is just how Safari handles slider elements. You have to drag directly on the circle marking the slider position to change it. Otherwise touching the slider just makes it flash.
