### ISSUE TITLE
Text on top of video doesn't show up on iOS devices

### ISSUE THREAD

**Issue by andychan1998** [Scirra/Construct-3-bugs#848]
## Problem description

I have a video, and some text on top of it (showing progress).  It's fine on most platforms, but the text doesn't show up on iPhone and iPad using Safari.

## Attach a .c3p

https://drive.google.com/open?id=0B8XY81b11D4sTllGcE9qQm9MeVE.

## Steps to reproduce

1. Load the attached .c3p file.  Export it into a HTML5 game and load it on a server.
2. On iPhone or iPad, use Safari to access the HTML5 game.

## Observed result

The text doesn't show on top of the video.

## Expected result

The text should show on top of the video.  You can verify this by using Chrome or Firefox on a PC to point to the HTML5 game.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: haven't tried
* Safari: yes (only tried on iPhone/iPad)

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r59
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 646 mb (1.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This has so far been by design, because Safari could not render video in to the canvas (where other things can be painted on top), so we "float" the video over the canvas instead (which means nothing can appear over it).

IIRC this was for an old version of Safari and things may be better in newer versions, so we might be able to remove the workaround now.

**Comment by AshleyScirra** [comment]
OK, after some testing it looks like we can render video to the canvas in iOS 10+. I think for C3 this is enough support to drop our old workaround. This should be working from the next build.
