### ISSUE TITLE
icon image editor crash

### ISSUE THREAD

**Issue by TGeneDavis** [Scirra/Construct-3-bugs#849]
## Problem description

Open icon-128 in the image editor in a new project and try to load a png to replace it, and it crashes C3

## Attach a .c3p

![icon-128](https://user-images.githubusercontent.com/27360407/30892988-e96d34ae-a2f8-11e7-9f8f-5cd79c7851c0.png)

[Blah.zip](https://github.com/Scirra/Construct-3-bugs/files/1335603/Blah.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.Create new project
2.Open the 128-icon in the image editor
3.Try opening the attached PNG to replace it
4.CRASH

Note: I used this feature and icon successfully a couple of versions back.

## Observed result

*What do you see happen?*
CRASH

## Expected result

*What did you expect to happen instead?*
NO crash

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃq.ǃX (https://editor.construct.net/r59/main.js:2:179732) at e.ǃKxF.ǃKVm (https://editor.construct.net/r59/main.js:71:266006) at Promise.resolve.then.then (https://editor.construct.net/r59/main.js:71:200664) at 
Stack: TypeError: unexpected type at Function.ǃq.ǃX (https://editor.construct.net/r59/main.js:2:179732) at e.ǃKxF.ǃKVm (https://editor.construct.net/r59/main.js:71:266006) at Promise.resolve.then.then (https://editor.construct.net/r59/main.js:71:200664) at 
Construct 3 version: r59
URL: https://editor.construct.net/
Date: Tue Sep 26 2017 20:17:58 GMT-0600 (MDT)
Uptime: 20.7 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r60.
