### ISSUE TITLE
Pressing "b" shortcut to create a blank sub-event often creates two sub-events

### ISSUE THREAD

**Issue by pixelmetal** [Scirra/Construct-3-bugs#85]
## Problem description

Pressing "b" shortcut to create a blank sub-event often creates two sub-events

## Attach a .c3p

N/A

## Steps to reproduce

1. Create a new project
2. Create a top-level event
3. Select the event
4. Press "b" keyboard shortcut
5. Observe two blank sub-events are created

## Observed result

A blank sub-event, that has its own blank sub-event, is created. This does not happen when right-clicking and choosing "blank sub-event" from the context menu. This occurred on multiple Windows 10 PCs  (Dell M4700 & M6500, MS SP4, custom desktop).

## Expected result

A single sub-event to be created when using keyboard shortcut.

**Comment by AshleyScirra** [comment]
Can't reproduce here, I tried a new project and also opened Ghost Shooter and added a blank sub-event, it only added one every time.

If you hold it down it keeps repeating it - maybe you're doing that by accident?

**Comment by pixelmetal** [comment]
It was definitely not a user issue. It occured across 3 different Will does machines. Maybe the repeat interval for keystrokes needs to be longer in C3? It always creates two nested blank events, no matter how long/short the keypress is.

This issue is limited only to C3 on Windows, and after more testing does NOT occur on the two most recent releases of OSX, which I tested on a late 2016 MBP and a late 2009 Mac Mini.
