### ISSUE TITLE
Google Drive loading sooo slow

### ISSUE THREAD

**Issue by MrCreightonD** [Scirra/Construct-3-bugs#851]
## Problem description

When I try to save or open to the cloud it takes a really long time to load Google Drive and display all the Construct 3 files in my Google Drive.

## Steps to reproduce

1. Menu > Project > Cloud Open or Save

## Observed result

The loading wheel just spins round and round for 1 to 2 minutes

## Expected result

Google Drive loads instantly and I choose a folder to save/open my .c3p file.

## Affected browsers

* Chrome: yes
* Firefox: maybe
* Edge: maybe
* Safari: maybe

## System details

Dell Intel i7

**Comment by shortercode** [comment]
I expect this is down purely to the network request to google taking a long time, can you answer these questions for me? It will help me know if there is anything we can do to improve the download speed for you.

1. what is you download speed (mbps)
2. what is your latency (ms)
3. how many c3p files do you have on google drive
4. how many folders do you have on google drive ( roughly )
5. how much space have you used on google drive ( roughly )
6. how quickly does the google drive website load for you
7. are you behind a proxy of any kind

**Comment by MrCreightonD** [comment]
1. what is you download speed (mbps):  5Mbps
   2. what is your latency (ms): 11ms
   3. how many c3p files do you have on google drive: 8
   4. how many folders do you have on google drive ( roughly ): 32
   5. how much space have you used on google drive ( roughly ): Unlimited
   6. how quickly does the google drive website load for you: Normal. No
   observable slowness
   7. are you behind a proxy of any kind: No


On Sep 27, 2017 8:34 AM, "Iain Shorter" <notifications@github.com> wrote:

I expect this is down purely to the network request to google taking a long
time, can you answer these questions for me? It will help me know if there
is anything we can do to improve the download speed for you.

   1. what is you download speed (mbps)
   2. what is your latency (ms)
   3. how many c3p files do you have on google drive
   4. how many folders do you have on google drive ( roughly )
   5. how much space have you used on google drive ( roughly )
   6. how quickly does the google drive website load for you
   7. are you behind a proxy of any kind

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Scirra/Construct-3-bugs/issues/851#issuecomment-332561661>,
or mute the thread

**Comment by shortercode** [comment]
I think you might have misread question 5, I hope your not using "unlimited" quantities of storage ;) Either way I expect you have quite a few files on there given your paying for the unlimited storage tier.

We use a filtered query to request files and I'm wondering if it has some kind of per file overhead when it generates the results. If you wouldn't mind could you visit the [drive API V3 reference list files](https://developers.google.com/drive/v3/reference/files/list) and try running some test queries and tell me how long they take.

Expand the part that says "Show standard parameters" and for the "fields" value put `files(parents,fileExtension,mimeType,id,name,modifiedTime,size),nextPageToken`.

Then in the "q" value try these queries:

- `trashed = false and ((name contains '.capx' or name contains '.c3p') or mimeType = 'application/vnd.google-apps.folder')`
- `trashed = false and ((name contains '.c3p') or mimeType = 'application/vnd.google-apps.folder')`
- `(name contains '.capx' or name contains '.c3p') or mimeType = 'application/vnd.google-apps.folder'`
- `trashed = false and (name contains '.capx' or name contains '.c3p')`

If any/all of them take more than a moment to complete would you please time them roughly using a stopwatch of some sort. Also worth noting is google drive seems to have a kind of "warm up" time, so the first request is often slower than subsequent ones, as such I'd recommend running each query once before timing it.

I appreciate this is a bit of a hassle. I would try this myself except when I make a query it is generally less than a second and I'm also reasonably sure it's not related to your network speed, so it somewhat limits my ability to test the issue other than best guesses.

**Comment by shortercode** [comment]
@MrCreightonD without any additional information I can't help improve your situation. Given that this isn't reproducible it will likely be closed soon.

**Comment by shortercode** [comment]
Okay without any further information I can't make any improvements here. r61 included a metadata caching system which should help speed things up a bit ( only need to request the file list once per session ).
