### ISSUE TITLE
.APK error

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#854]
## Problem description
After export (debug APK) doesn't work.

## Steps to reproduce

1. Open construct.
2. Select export to Android.
3. Export debug APK.

## Observed result

It appears on every APK i made and only online, when offline everything works fine:
Error Application! The connection to the server was unsuccessful (file:///android_assets/www/index.html)

## Expected result

Open the APK without error.

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Samsung Galaxy Note 4

</details>

**Comment by shortercode** [comment]
project? if repeats with an example one please specify which

**Comment by Ind1eed** [comment]
You can make it by your own, simply export any project into debug APK. The app shouldn't work on your device.

**Comment by shortercode** [comment]
I haven't ever seen this error on any test device in the office, just made a test app and it worked perfectly.

I found this [article](https://forum.ionicframework.com/t/application-error-the-connection-to-the-server-was-unsuccessful/67584) which suggests it's to do with the page load timing out on older phones. The suggested work around seems to be to increase the timeout duration.

Do you know how to build an APK using the cordova command line tool?

**Comment by Ind1eed** [comment]
Did you tested offline or online?

No, i don't know.

**Comment by shortercode** [comment]
Online? App seems to work fine in airplane mode as well.

I'll send you my test app for you to try, and a second version of it with the timeout hack in for you to compare.

**Comment by shortercode** [comment]
[normal_touch_demo.zip](https://github.com/Scirra/Construct-3-bugs/files/1341304/normal_touch_demo.zip)

That zip contains the normal one

**Comment by shortercode** [comment]
[android-delayed.zip](https://github.com/Scirra/Construct-3-bugs/files/1341328/android-delayed.zip)
That zip contains the one with the longer timeout.

**Comment by Ind1eed** [comment]
The first app works perfectly, even if i turn wi-fi off, but regarding to
the second one i get: Application was not installed.

2017-09-28 16:56 GMT+02:00 Iain Shorter <notifications@github.com>:

**Comment by shortercode** [comment]
mmm sorry I might have built the second one wrong! But if the first one works then it's kinda pointless fixing the second one. Maybe it's related to the size of the project. How long does the app I sent you take to start? which project was it that you were building that broke? Going to try building a modified version of that for you.

**Comment by Ind1eed** [comment]
Well it loads very quickly. I can send you the "broken" file, so you will
take a look at if you want.

2017-09-28 17:11 GMT+02:00 Iain Shorter <notifications@github.com>:

**Comment by shortercode** [comment]
Reason why I ask about loading time is that apparently the default time out is 20 seconds, so I was a little surprised that it was timing out. But yeah sure send the project over and I'll take a look.

**Comment by Ind1eed** [comment]
Okay, so here is the .apk and the .c3p, apologies for a files size.​
 Marble Mania (2).c3p
<https://drive.google.com/file/d/0B5qSpRFRvr7BajJERjdCOTJ4UjQ/view?usp=drive_web>
​.​
 Marble Mania.android.debug (1).apk
<https://drive.google.com/file/d/0B5qSpRFRvr7BX3NEQ19HUXhaRm8/view?usp=drive_web>
​

2017-09-28 17:23 GMT+02:00 Iain Shorter <notifications@github.com>:

**Comment by shortercode** [comment]
Not sure if this is reassuring or not but runs fine on my phone, I'll try a couple of other devices.

**Comment by Ind1eed** [comment]
Well, it looks like the app is working fine now, just restarted my modem.
But now i have another trouble. When i select Export > i got "No items".

2017-09-28 17:58 GMT+02:00 Iain Shorter <notifications@github.com>:

**Comment by shortercode** [comment]
Sounds like the exporters list hasn't loaded, given the odd issues you've had around networking this doesn't surprise me. Try reloading construct, chrome, network adaptors etc.

**Comment by Ind1eed** [comment]
Works fine, thank you so much. :)

2017-09-28 18:41 GMT+02:00 Iain Shorter <notifications@github.com>:

**Comment by Ind1eed** [comment]
I don't get it.. again doesn't work. Same error.

28.09.2017 6:45 PM "Piotr Piotr" <npiotr96@gmail.com> napisał(a):

**Comment by Ind1eed** [comment]
But your app works perfectly..

28.09.2017 7:13 PM "Piotr Piotr" <npiotr96@gmail.com> napisał(a):

**Comment by Ind1eed** [comment]
By the way, i sent this project this project to a publisher and for them it
doesn't work, too.

2017-09-28 19:16 GMT+02:00 Piotr Piotr <npiotr96@gmail.com>:

**Comment by Ind1eed** [comment]
Can you please re-open this post? Cause it seems to don't be fixed yet. Im
not even sure the fault is by your or mine side.

2017-09-28 22:01 GMT+02:00 Piotr Piotr <npiotr96@gmail.com>:

**Comment by AshleyScirra** [comment]
You must follow all the bug report guidelines, otherwise there is nothing we can do to help.

**Comment by Ind1eed** [comment]
So what exactly should i do nów?

29.09.2017 12:48 PM "Ashley (Scirra)" <notifications@github.com> napisał(a):

**Comment by Ind1eed** [comment]
May the local storage cause this error?

2017-09-29 16:31 GMT+02:00 Piotr Piotr <npiotr96@gmail.com>:

**Comment by Ind1eed** [comment]
Can you please rebuild this app using the cordova command line tool?​
 Marble Mania (8).c3p
<https://drive.google.com/file/d/0B5qSpRFRvr7BZlJHMmRlNVc0T0k/view?usp=drive_web>
​

2017-09-28 16:40 GMT+02:00 Iain Shorter <notifications@github.com>:
