### ISSUE TITLE
Use WebAssembly physics engine

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#855]
Construct 3 uses an asm.js compiled version of box2d in the Physics behavior. We should update this to WebAssembly with an asm.js fallback. WebAssembly should be faster and have more flexible memory usage - the asm.js version currently has a fixed memory size which wastes memory for small projects, and breaks large projects which run in to the limit.

**Comment by BonzerKitten7** [comment]
It's recommended to avoid the Physics Behaviour in some serious project for now or can we use it without any problem?

**Comment by AshleyScirra** [comment]
Had a look in to this and there are some difficulties with the WebAssembly version:

- it needs to be recompiled to support either >16mb memory or, preferably, dynamic memory growth
- asm.js compiles synchronously but wasm compiles asynchronously. Given the way the C2 code is currently written, this means we would have to compile the wasm before even loading c2runtime.js.
- C3's dependency management probably needs special wasm support added to it to conveniently manage WebAssembly components in addons.

Given these difficulties it probably makes sense to punt this to the C3 runtime. Some performance benchmarks showed the latest asm.js performing pretty close to the wasm performance, so it's not really a big difference at the moment.

**Comment by AshleyScirra** [comment]
Closing as this is is a feature update rather than a bug, so will track it as a feature request.
