### ISSUE TITLE
Kiwi story not loading in safari

### ISSUE THREAD

**Issue by shortercode** [Scirra/Construct-3-bugs#856]
## Problem description

Kiwi story doesn't run in safari, load fails on decoding one audio file which is "kiwi-credits.m4a" or something similar. File doesn't seem to be able to play the last few seconds. Have left test case on shared desktop.

## Attach a .c3p

Kiwi story project is included with C3

## Steps to reproduce

1. Load kiwi story
2. Preview kiwi story

## Observed result

Load gets stuck right at the end, never shows an error.

## Expected result

Game to load.

## Affected browsers

* Chrome: no
* Firefox: unknown
* Edge: unknown
* Safari: yes

## System details

Macbook Pro 17" 2015

<details><summary>View details</summary>

No error message

</details>

**Comment by shortercode** [comment]
Assigning to @AshleyScirra to look at the audio file.

**Comment by AshleyScirra** [comment]
Just re-encoded it in Audacity and it seems to work now. Must've been some weird corruption in the file.
