### ISSUE TITLE
Using Trackpad Zoom In on Mac zooms the whole Browser

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#857]
## Problem description

When using a Mac and Chrome, when i use the two Finger System for zooming in or out, the whole browser gets scaled instead of just the C3 Workspace.

## Steps to reproduce

1. Open an empty C3 Project on a Macbook or similiar without using a Mouse
2. Use the standard Two Finger Gesture on the Trackpad to Zoom in (Layout View)

## Observed result

The whole Browser Window gets zoomed, Property and Layer Bar disappear.

## Expected result

Only the Layout view zooming in, like when using a Mousewheel.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
IIRC this is built-in functionality in Safari itself and web pages cannot override it. So we might not be able to do anything about this.

**Comment by joelmayer87** [comment]
Hi @AshleyScirra 

This actually happens in Chrome, i don't use Safari...

**Comment by AshleyScirra** [comment]
Oh, I think it might have been a built-in macOS feature then...

**Comment by AshleyScirra** [comment]
Ah, there were just some extra zoom events we needed to intercept. Should be working in the next build.
