### ISSUE TITLE
Right click in Layers Panel on iOS doesn’t work

### ISSUE THREAD

**Issue by TinyMartian** [Scirra/Construct-3-bugs#859]
## Problem description

Tap and hold for right click options in the layers panel doesn’t work. No pop up. The panel flashes grey indicating it’s registering the gesture. No other way to add layers. Same issue for right clicking on sprites. 

## Attach a .c3p

N/A

## Steps to reproduce

1. Tap and hold in layers panel
2. Nothing happens
3.

## Observed result

The layer panel flashes grey and nothing else.

## Expected result

A pop up with layer options.  Wanted to add a new layer.

## Affected browsers

* Chrome: n/a
* Firefox: n/a
* Edge: n/a
* Safari: yes

## System details

No bug report
iOS 11.0.1
iPad Pro (1st gen.)
C3

**Comment by AshleyScirra** [comment]
Looks like it's not just the layers panel, it's everywhere, because iOS doesn't fire contextmenu events. Polyfilled it for the next release.
