### ISSUE TITLE
construct 3 manual - can't scroll menu

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#860]
## Problem description

When i view the c3 manual in safari i can't scroll the menu category links on the left and lots are cut off.

https://www.dropbox.com/s/reh2zmkj774ia2u/Screen%20Shot%202017-09-30%20at%2019.58.23.png?raw=1

## Attach a .c3p

web page issue

## Steps to reproduce

1.
2.
3.

## Observed result

if i say look at the plugins section lots of plugin links are off the page.

## Expected result

see all categories options.

## Affected browsers

* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
@mOOnpunk this should work in Safari now, they added the required CSS in Safari 11 I believe

**Comment by mOOnpunk** [comment]
yes working in latest Safari.
