### ISSUE TITLE
Trying to load a 512px icon crashes the editor

### ISSUE THREAD

**Issue by sachos345** [Scirra/Construct-3-bugs#862]
## Problem description

Construct crashes when trying to import a 512px image as my new icon in the icons folder.

## Attach a .c3p

It should happen in every project. (I tested with a new empty project and it crashed)

## Steps to reproduce

1.Open a new project
2.Try to change the 512px icon by importing a 512px img (my icon is a 32bit png)
3.It crashes

## Observed result

Construct crashes when trying to import a 512px image as my new icon.

## Expected result

Succefully change the my game icons.

## Affected browsers

* Chrome: yes
Others not tested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Function.ǃq.ǃX (https://editor.construct.net/r59/main.js:2:179732) at e.ǃKxF.ǃKVm (https://editor.construct.net/r59/main.js:71:266006) at Promise.resolve.then.then (https://editor.construct.net/r59/main.js:71:200664) at 
Stack: TypeError: unexpected type at Function.ǃq.ǃX (https://editor.construct.net/r59/main.js:2:179732) at e.ǃKxF.ǃKVm (https://editor.construct.net/r59/main.js:71:266006) at Promise.resolve.then.then (https://editor.construct.net/r59/main.js:71:200664) at 
Construct 3 version: r59
URL: https://editor.construct.net/index.html
Date: Sat Sep 30 2017 21:40:07 GMT-0300 (Hora estándar de Argentina)
Uptime: 85.3 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 960 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by armandoalonso** [comment]
this is also happening to me but it has happened with 32px, 64px images

**Comment by DiegoScirra** [comment]
Fixed in r60
