### ISSUE TITLE
Error application.

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#865]
## Problem description

After launching my app on my device (Samsung Galaxy Note 4) i got exactly this error: [https://www.scirra.com/forum/the-connection-to-the-server-was-unsuccessful_t68474](url) 

## Steps to reproduce

1. Launch Construct 3
2. Select Export > Android and build .apk.
3. Then, test app on your device, enable Wi-Fi connection, cause (for me) the error appears only when i turn Wi-Fi on.

## Observed result

Error application! The connection to the server was unsuccessful. (file:///android_asset/www/index.html)

## Expected result

Launch the app without errors.

## Affected browsers

* Chrome: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Device: Samsung Galaxy Note 4

</details>

**Comment by Ind1eed** [comment]
No .c3p attached cause the error appears on any project. (created by me).

**Comment by AshleyScirra** [comment]
This is just a re-post of #854 and all you've done is link to a forum thread that is 5 years old. I'm afraid we can't help you unless we can reproduce the issue, and to do that you should follow the full bug report requirements.

**Comment by Ind1eed** [comment]
I told you how you can reproduce that. Create ANY project and export that
to .apk..

2017-10-02 12:51 GMT+02:00 Ashley (Scirra) <notifications@github.com>:

**Comment by AshleyScirra** [comment]
We can't reproduce any problem. It works for us, and apparently, for everybody else too.

**Comment by Ind1eed** [comment]
Fine... So, what do i have to do then? Any suggestions?

2017-10-02 19:47 GMT+02:00 Ashley (Scirra) <notifications@github.com>:
