### ISSUE TITLE
Pick by evaluate won't accept equality expression

### ISSUE THREAD

**Issue by faulknermano** [Scirra/Construct-3-bugs#87]
## Problem description
When using Pick by evaluate to pick an instance, the C3 editor itself won't allow equality operators by putting up a 'Type mismatch' error saying 'This parameter does not take a "string"'.

## Attach a .c3p

https://www.dropbox.com/s/ug3dnxc1lxf27es/expression_equality.c3p?dl=0

Please also see this image, which is the error message and the expression I tried to type.

https://www.dropbox.com/s/qs0dc1uwiq2pb4q/2017-04-16%2008_01_59-New%20project%20-%20Construct%203.png?dl=0

## Steps to reproduce

1. The c3p doesn't actually show anything but the project that I was testing. The error lies in the editor not accepting a string, which is demonstrated in the attached .png file.
2. Type in a simple equality  expression using the Pick by evaluate (not using the System Expression functions)

## Observed result

*What do you see happen?*
Error message 'type mismatch' as seen in the .png.

## Expected result

In C2, the expression is grokked fine. In C3, it is disallowed.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r19.
