### ISSUE TITLE
Animation Editor Glitch

### ISSUE THREAD

**Issue by tyler3327** [Scirra/Construct-3-bugs#870]
## Problem description

Every time I import a animation into construct 3 on any sprite I have to close out of the animation editor for that sprite before I can set there origin points. If you set the origin point right after you import an animation then close out of the animation editor in construct 3 then reopen that sprites animation origins will reset to where they where before

## Steps to reproduce

1.Create a sprite and import any animation then set there origin points
2.Do not close out of animation editor until you've changed the origin points of the animation you've imported.
3.Then close animation editor and reopen animation editor. The origin points on the imported animation will be reset.

## Expected result

*What did you expect to happen instead?*
Self explanatory animation origin points don't save after first importing them.

## Affected browsers

  I have only tried this on chrome

Note: I can not attach a cp3 file because you wont be able to see glitch because it only happens when you import an animation for the first time and not close out of it.

**Comment by joelmayer87** [comment]
Happens to me as well.

**Comment by DiegoScirra** [comment]
Do you have any more details on this? I can't easily reproduce it.

There are quite a few different ways of importing an animation as well as setting the origin and image points, so chances are I am not doing exactly what you are doing.

Please try to be as specific as possible with the reproduction steps, sometimes some of the steps you are taking might seem like they are not important but they can be of real use to fix a bug.

**Comment by tyler3327** [comment]
Yes sorry about. This is exactly what I did. Note I have done this with different amount of frames when I imported it....okay so I create a random sprite at the bottom of the frames i right clicked then clicked import frames I imported 6 frames for this animation deleted the first frame because when you import an animation the first frame stays blank then I renamed the animation to what ever I find suitable then rotate entire animation to right once so all frames face the correct orientation for top down game. Then I set there origin points after that I close out of the sprite animation editor and I’m back on my main layout screen then I double click on that sprite again to open its animation editor when it reopens the origin points i set are not where I set them. Thank you and I hope this helps I can provide images if you can’t reproduce.

**Comment by tyler3327** [comment]
> Yes sorry about. This is exactly what I did. Note I have done this with
different amount of frames when I imported it....okay so I create a random
sprite and I double click the sprite I just created at the bottom of the
frames i right clicked then clicked import frames I imported 6 frames for
this animation deleted the first frame because when you import an animation
the first frame stays blank then I renamed the animation to what ever I
find suitable then rotate entire animation to right once so all frames face
the correct orientation for top down game. Then I set there origin points
after that I close out of the sprite animation editor and I’m back on my
main layout screen then I double click on that sprite again to open its
animation editor when it reopens the origin points i set are not where I
set them. Thank you and I hope this helps I can provide images if you can’t
reproduce.

**Comment by tyler3327** [comment]
Yes sorry about. This is exactly what I did. Note I have done this with different amount of frames when I imported it....okay so I create a random sprite and I double click the sprite I just created at the bottom of the frames i right clicked then clicked import frames I imported 6 frames for this animation deleted the first frame because when you import an animation the first frame stays blank then I renamed the animation to what ever I find suitable then rotate entire animation to right once so all frames face the correct orientation for top down game. Then I set there origin points after that I close out of the sprite animation editor and I’m back on my main layout screen then I double click on that sprite again to open its animation editor when it reopens the origin points i set are not where I set them. Thank you and I hope this helps I can provide images if you can’t reproduce.

**Comment by tyler3327** [comment]
Also the image sizes for the frames I imported are not all the same size because I also cropped them after I import them sorry.

**Comment by DiegoScirra** [comment]
@tyler3327 

Thanks for the additional information. I was just able to reproduce the bug thanks to it, should be able to fix it soon.

**Comment by tyler3327** [comment]
Alright thank you so much Diego! This will help me immensely.

**Comment by DiegoScirra** [comment]
Fixed in r62.

Thanks for the help!
