### ISSUE TITLE
Errors in console.

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#871]
## Problem description
 While im testing on the pc i get tons of errors in my browser's console.
 THE ERRORS APPEARS EVEN IF I DISABLE KASPERSKY.

## Attach a .c3p

No .c3p attached cause it appears in any project.

## Steps to reproduce

1. Open construct 3
2. Test your app 
3. Open console 
4. You should see likes 7 errors

## Observed result

![drawing 15](https://user-images.githubusercontent.com/31414273/31132050-10ea806e-a85c-11e7-9ee6-fbb6a8f2ef67.png)

## Expected result

No errors.

## Affected browsers

* Chrome: yes
## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce. No errors here. One of the errors references kaspersky-labs.com, which suggests it is a browser addon causing the errors, despite what you say about disabling it. Besides, if the project continues to work OK, it doesn't matter if there are errors in the console.
![preview-console](https://user-images.githubusercontent.com/768723/31138873-ce7d6438-a867-11e7-8ccc-312792fdf5b9.png)

**Comment by Ind1eed** [comment]
The project works ok while testing on PC, but after exporting to android APK the app shows error.

**Comment by Ind1eed** [comment]
Even if i totally close Kaspersky, it still shows Kaspersky errors. I don't get it...

**Comment by Ind1eed** [comment]
By the way i don't have any addons in the browser.

**Comment by shortercode** [comment]
@Ind1eed anti-virus software is pretty notorious for breaking programs and in some cases actually making programs more vulnerable to attack, I would recommend running C3 in incognito mode to tell if it is an extension. If it still occurs it's likely that kaspersky has modified your version of chrome to "make it safer", which is likely to cause issues even if kaspersky is disabled.

Either way there's very little we can do about 3rd party software breaking your version of chrome, if it worries you then I recommend taking it up with kaspersky. Your welcome to reference this issue.

**Comment by Ind1eed** [comment]
Thank you so much for your tip! No more errors! :))))))

2017-10-04 18:07 GMT+02:00 Iain Shorter <notifications@github.com>:

**Comment by Ind1eed** [comment]
Well, no more errors in the empty projects, but in my biggere project the
error still appears :(

2017-10-04 18:15 GMT+02:00 Piotr Piotr <npiotr96@gmail.com>:

**Comment by Ind1eed** [comment]
Okay, nevermind there is only one error, but i don't know what it
means: Failed to load resource: net::ERR_FAILED

2017-10-04 18:21 GMT+02:00 Piotr Piotr <npiotr96@gmail.com>:

**Comment by Ind1eed** [comment]
So, reinstalling chrome would fi  that?


04.10.2017 6:23 PM "Piotr Piotr" <npiotr96@gmail.com> napisał(a):

**Comment by Ind1eed** [comment]
Fix'

04.10.2017 6:45 PM "Piotr Piotr" <npiotr96@gmail.com> napisał(a):

**Comment by Ind1eed** [comment]
Reinstalled my chrome and still same errors, and even more.. i have no idea
what to do to fix that.

2017-10-04 18:45 GMT+02:00 Piotr Piotr <npiotr96@gmail.com>:
