### ISSUE TITLE
add online dependency error

### ISSUE THREAD

**Issue by paala** [Scirra/Construct-3-bugs#875]
## Problem description

My c2 plugin was modified to include a dependency  from online file:
//imasdk.googleapis.com/js/sdkloader/ima3.js

If I add this as:
this._info.AddFileDependency({
				filename: "//imasdk.googleapis.com/js/sdkloader/ima3.js",
				type: "external-script"
				});
It throws the error on the editor.construct.net when I try to preview/export the project.
If I don't add the line the export works ok but I need to add :

<script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>

to the index.html of exported project.

There is a way to add this line to preview/exported project without needing the actual file?

## Attach a .c3p
[ima4_addon.zip](https://github.com/Scirra/Construct-3-bugs/files/1355838/ima4_addon.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

Error report information
Type: unhandled rejection
Reason: Error: missing addon file '//imasdk.googleapis.com/js/sdkloader/ima3.js' @ Error: missing addon file '//imasdk.googleapis.com/js/sdkloader/ima3.js' at window.ǃKfx.ǃKfy (https://editor.construct.net/r59/main.js:61:443286) at window.ǃYi.ǃBiU (https://editor.construct.net/r59/main.js:61:463142) at window.ǃYi.ǃKD_ (https://editor.construct.net/r59/main.js:71:1571) at Promise.resolve.then.then.then.then.then.then.then (https://editor.construct.net/r59/main.js:71:12651) at 
Stack: Error: missing addon file '//imasdk.googleapis.com/js/sdkloader/ima3.js' at window.ǃKfx.ǃKfy (https://editor.construct.net/r59/main.js:61:443286) at window.ǃYi.ǃBiU (https://editor.construct.net/r59/main.js:61:463142) at window.ǃYi.ǃKD_ (https://editor.construct.net/r59/main.js:71:1571) at Promise.resolve.then.then.then.then.then.then.then (https://editor.construct.net/r59/main.js:71:12651) at 
Construct 3 version: r59

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by paala** [comment]
https://www.construct.net/ro/make-games/manuals/addon-sdk/reference/specifying-dependencies
from here:


filename

    Name of the dependency file in the addon. This must be bundled with the addon; it cannot refer to a URL

If I download the file and place it locally it doesn't work. I must use the online file.

**Comment by AshleyScirra** [comment]
This is not supported as per #675. Either bundle the file with your addon, or load it at runtime.
