### ISSUE TITLE
.Capx Project which was working smoothly on Windows and C2 slows down on Mac

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#877]
I prototyped a Game Scene last year in C2 on a Windows Machine in C2. Everything worked very smoothly and since it's very low resolution (256*144), i used High Quality on the Fullscreen Mode to be able to use Fonts and Particles that show sharply. However, now working in C3 and on MacOS with a 2016 MacBook Pro and 16 GB or Ram as well as Chrome, it totally stutters and is extremely slow.

## Attach a .c3p##

[Archiv.zip](https://github.com/Scirra/Construct-3-bugs/files/1356605/Archiv.zip)

## Steps to reproduce

1. Open up Project on a MacBook similiar to my Specifications.
2. See it stutter
3. Compare it with .capx File on a Windows with C2

## Observed result

Game runs very slowly.

## Expected result

I expect to run it as well as on Windows and in C2...

## Affected browsers

* Chrome: yes

## System details

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 85 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by joelmayer87** [comment]
Funny, just tried it with Firefox now and there it works smoothly as well! Might be a Chrome on MacOS Problem :S Doesn't give me much hope when it comes to exporting this with nw.js.... which i already tried as well and it stutters too...

**Comment by joelmayer87** [comment]
Just tried the project and my new one on C3 with a Windows Surface and it works totally fine here with scaling set to "high"! Really weird... All my drivers etc. are on the newest version on the Mac, what could the reason be? :S


Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 19 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) Iris(TM) Graphics 540 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by joelmayer87** [comment]
AHA! I think i got the problem. In MacOS's Monitor Settings when you set the scaling to "More Space" or anything other than Standard or Standard for Monitor (sorry, only got the german descriptions, but i'm sure it's called similiarly in english), the game runs smoother... Huh, is there a way that when running the Game this will be set automatically? Lots of people with Mac's are using the "More Space" Option so they have more Display Space available to them...

![image](https://user-images.githubusercontent.com/30116964/31189634-1c58e660-a939-11e7-80d7-24900e3b654d.png)

**Comment by AshleyScirra** [comment]
Are you sure it's not just a hardware difference? It's the same engine and the same code running, and the MacBook has an Intel GPU which is typically pretty underpowered for gaming, and is exacerbated by the high-DPI displays on MacBooks.

Is the difference consistent if you also test Firefox? Is Safari any better?

**Comment by joelmayer87** [comment]
Ashley, i wasn't putting the blame on C3, on the contrary, i just wrote that it's probably a matter of the high-DPI displays on the MacBook.

I tested Firefox and no difference. The only difference happens when i change the window resolutions lower in the monitor settings.

Yes, MacBooks are not optimized for Gaming but i think they should suffice for a 256*144 game ;) Plus the game works smoothly on my Android Phone via Remote Preview as well. So the problem is with Mac but i mean, if Construct wants to sustainably work on Mac, there must be some kind of workaround... ?

**Comment by joelmayer87** [comment]
@AshleyScirra PS: Tried the latest Safari Browser as well now, same result unfortunately...Tried running different Games from PnC Adventures with Realtime Effects like myself even to some Realtime 3D Stuff and although the 3D Things surely didn't run as smoothly as on my Gaming PC, they still worked a lot better than my crummy game :D

**Comment by joelmayer87** [comment]
@AshleyScirra I've opened up a Thread in the C3 forums, since this doesn't seem to be a direct Bug of C3 you're welcome to close this issue... sorry about the confusion and thank you!

**Comment by AshleyScirra** [comment]
Closing as per forum reply here: https://www.scirra.com/forum/c3-on-mac-your-experiences_p1143574?#p1143574
