### ISSUE TITLE
Array Editor Moves Cells outside Sheet

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#879]
## Problem description

When creating a new Array with the Editor and starting to input values, the added values are moved off the sheet. Seems to be a display error (see attached picture).

![image](https://user-images.githubusercontent.com/30116964/31193661-10b96b70-a945-11e7-98a0-bf1712a10d15.png)

## Steps to reproduce

1. Open a new C3 project
2. Create a new Array with the Array Editor (Files -> New -> Array)
3. Start to input values in cells

## Observed result

Display of the sells moves to the corner of the spreadsheet in a much smaller fashion.

## Expected result

Just normal input in the Spreadsheet.

## Affected browsers

* Chrome: yes

## System details
Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 309 mb (2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 6100
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Okay thanks for the report, looks like this is because of the device pixel ratio. As a workaround if you scroll the table it will trigger a redraw and get rid of the artifacts.

**Comment by joelmayer87** [comment]
@shortercode Thank you! My, there seem to be quite some Mac Retina Display Problems. But that might change with the Desktop Version :) Thanks again.

**Comment by shortercode** [comment]
Should be fixed in r60, it wasn't taking into account the scale factor when redrawing a single cell. What sort of issues are you seeing with the retina display? Was it just this bug?

**Comment by joelmayer87** [comment]
Well i still got the problem that sometimes, it just cuts off part of my layout view with grey... kinda hard to explain but looks like a display bug too, and the only way to get it working again is very often close out of Chrome and restart C3. Really difficult to replicate though but since i've been working in C3 on my MacBook Pro now for a week i encountered issues like this quite frequently ;) Note: my display setting is set to "More Space" which might also be a problem sometime i feel, but pretty much all Mac Users are using this display setting...

**Comment by shortercode** [comment]
Hmm and that's specifically on the layout view? Might be related to changes @AshleyScirra made with the layout view rendering in r59, but given that he was making those changes specifically for safari and firefox I would have though he would have seen them while testing. Or it could legitimately be a graphics driver bug, which would make it super hard for us to track down.

Any thoughts @AshleyScirra ?

**Comment by shortercode** [comment]
Either way this bug is fixed so going to close this issue.
