### ISSUE TITLE
Video doesn't play in Safari using Remote Preview

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#881]
Ref: [thread](https://www.scirra.com/forum/construct3_t196484)

Repro: https://www.dropbox.com/s/4215c1d0jmqp8sc/video_test.zip?dl=0

On iOS, the video does not appear to play.

**Comment by AshleyScirra** [comment]
Looks like it does work after export - it only fails to play in Remote Preview.

**Comment by pixcubeanim** [comment]
Hello AshleyScirra, 
could you explain how you bring it to work? 
I builded it with xCode and adobe PhoneGap in Construct3 and it doesnt worked on every IOS device. 
In Construct2 i builded it via adobe PhoneGap - it worked on IOS devices with versions less than 11.
In both cases, the settings where the same and it where "final" builds, so no remote previews or something like that. 

Could you provide how you did it?  

Best regards - (congrats2u on scirra)

**Comment by AshleyScirra** [comment]
I uploaded your files here: https://www.scirra.com/labs/bugs/iosvideo/
It plays fine on an iPad Air running iOS 11.

**Comment by AshleyScirra** [comment]
Making this issue specifically about Remote Preview. The problem appears to be related to Safari not wanting to play a blob URL that we sent via the DataChannel.

**Comment by pixcubeanim** [comment]
Hey Ashley, first: thanks for your effort. 

Okay it plays the file in the browser, but in our case the problem is, that it doesnt play this video inside the app. (if youre building for IOS via cordova) - sry if this wasnt clear communicated. In the dropbox link above, there is an ipa included. 

Is there a solution possible? 

Please dont forget: Our app is on the store and this problem appears after ios11 was dropped.

**Comment by AshleyScirra** [comment]
Can you try again in r60? We just released it and it includes a change to how video playback is scheduled.

If there's still a problem please file another issue following all the guidelines.

**Comment by pixcubeanim** [comment]
AshleyScirra. Thanks for your Update. Sadly it didnt changed something on the issue. Videoplayback still dont run on IOS, builded with cordova/phonegap.

**Comment by AshleyScirra** [comment]
OK, please file a new issue.

**Comment by AshleyScirra** [comment]
Video playback should be fixed in Safari using Remote Preview for r61.
