### ISSUE TITLE
Construct 3 crashed...

### ISSUE THREAD

**Issue by Bootfit** [Scirra/Construct-3-bugs#882]
## Problem description

Construct 3 crashed and pop up reported a problem.
## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

Pop up message:

Error report information
Type: unhandled exception
File: https://editor.construct.net/r59/main.js, line 152, col 115797
Message: Uncaught TypeError: Cannot read property 'ǃQK' of null
Stack: TypeError: Cannot read property 'ǃQK' of null at window.ǃZRF.ǃZRr (https://editor.construct.net/r59/main.js:152:115797) at ǃZRA (https://editor.construct.net/r59/main.js:152:112379)
Construct 3 version: r59
URL: https://editor.construct.net/
Date: Thu Oct 05 2017 13:29:40 GMT+0100 (BST)
Uptime: 160133.3 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no - Yes iOS
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r59/main.js, line 152, col 115797
Message: Uncaught TypeError: Cannot read property 'ǃQK' of null
Stack: TypeError: Cannot read property 'ǃQK' of null at window.ǃZRF.ǃZRr (https://editor.construct.net/r59/main.js:152:115797) at ǃZRA (https://editor.construct.net/r59/main.js:152:112379)
Construct 3 version: r59
URL: https://editor.construct.net/
Date: Thu Oct 05 2017 13:29:40 GMT+0100 (BST)
Uptime: 160133.3 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Sorry, there's not much we can do unless you follow the bug report guidelines. We just issued an r60 update now which might help though.
