### ISSUE TITLE
Creating Tilemap takes a very long time

### ISSUE THREAD

**Issue by esowe** [Scirra/Construct-3-bugs#885]
## Problem description

I have been trying to implement the Large Tilemaps tutorial (https://www.scirra.com/tutorials/9443/template-load-and-save-large-tilemaps-in-localstorage) in C3 and have run into a strange problem, where creating Tilemap instances takes a very long time.

I modified the tutorial in order to use it as the basis for a map editor. Therefore, if a Tilemap cannot be found in Local Storage I create a new, empty Tilemap, to which the user will add tiles.

However, creating each empty Tilemap takes a very long time, and if I allow C3 to create all nine tilemaps, as described in the tutorial, both the preview and C3 crash with an out of memory error. The maximum number of tilemaps that can be created without this happening is six. 

## Attach a .c3p

I have attached a .c3p file with a minimal setup, where I retain the basic structure of the tutorial but have removed all LocalStorage accessing:

[CreateTilemapProblem.zip](https://github.com/Scirra/Construct-3-bugs/files/1359870/CreateTilemapProblem.zip)

## Steps to reproduce

1. Load the project and go to the Tilemap Event Sheet.
2. Preview the layout MapLayout and wait for the screen to update, which on my computer sometimes takes more than 20 seconds.
3. In the function "Tilemap.CreateAdjacentTiles", disable or enable the number of calls to "Tilemap.CreateTiles" wanted, in order to get different times and the Out of memory error.

## Observed result

It takes a very long time for the project to start, and by printing to a TextBox, I have located the problem to a call to System: CreateObject. It normally takes about two seconds to create each Tilemap instance, but the time to create each tilemap seems to be increasing, at least for the last Tilemaps. Here is one example with normal times, but a few times a delay of over 8000 ms has been recorded for a single Create call:
![debugtext](https://user-images.githubusercontent.com/10393576/31235126-eb225762-a9f0-11e7-8190-bfb0f8ca55db.PNG)

The times above are calculated from the unixtimes printed immediately before and after the call to "-> System: Create object MapLayoutTilemap on layer "Tilemaps" at (0, 0)" within the "Tilemap.CreateTargetTile" function of the Tilemap Event Sheet. Therefore, I suppose that the problem is within this call.

## Expected result

A much faster creation of Tilemap instances, like in the original C2 tutorial, and no Out of memory crashes

## Affected browsers

* Chrome: yes
* Firefox: unknown
* Edge: unknown
* Safari: unknown

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r60
Language setting: en-US

Local storage
Storage quota (approx): 6.4 gb
Storage usage (approx): 1.8 gb (27.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
You're creating outrageously colossal tilemaps at 150000x150000. These have around 22 million tiles. I cannot imagine why you need such a huge tilemap. I'm not surprised it's slow and uses lots of memory.

Why do you need such large tilemaps? If you don't have a good reason you can't use far, far smaller tilemaps, then I don't see why this should be improved.

**Comment by esowe** [comment]
Sorry, no I don't need that large Tilemaps, only a Layout that is that large. The point of the original tutorial is that the project creates nine tilemaps next to each other, each as large as a single viewport (not Layout), and then loads and creates new Tilemap instances from LocalStorage and destroys old ones whenever the map is scrolled, thereby supporting enormous Layouts.

I used to set the size of each newly created Tilemap to the OriginalViewportWidth and -Height immediately after creating it, but unfortunately I seem to have edited that out when cleaning up the project. However, the error was that I hadn't noticed that the initial Tilemap instance that I used as a template had become as large as the layout. By setting its size to a much smaller value and resizing it immediately after creation the problem was solved. Please remove this report since it was not a bug at all. My apologies!

**Comment by AshleyScirra** [comment]
The MapLayoutTilemap object is 150000 x 150000 in your project. It is the tilemap that is that size. There is no performance overhead to having a large layout, it's entirely the Tilemap object. This looks like an accident, so closing as won't fix.
