### ISSUE TITLE
Whitelist Cordova plugins for Ultimate Ads plugin

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#886]
User Toby R requested via support to whitelist the following Cordova plugins for the Ultimate Ads plugin with the C3 build service. Review them and permit if they look OK.

```
cocoon-plugin-ads-android-admob
cocoon-plugin-ads-ios-admob
cocoon-plugin-inapps-android-googleplay
cocoon-plugin-inapps-ios-appstore
cocoon-plugin-inapps-android-amazon
```

**Comment by TobyReeno** [comment]
First two are for Ultimate Ads, next three for Ultimate IAP plugin if that matters for your tests.

Thanks!

**Comment by TobyReeno** [comment]
Any update in regards to these plugins? Please note that a lot of people are using them in C2. All users happy, ratings 5/5 stars in Scirra store. It all works well and I've tested also with C3.

Let me know if I can help any further.

**Comment by shortercode** [comment]
@TobyReeno we haven't been able to review the plugins yet, just because time constraints. I'll bring it further up the to do list. Once I've checked them over I'll update the server whitelist and notify you here.

**Comment by odapplications** [comment]
What's the status of actually using the construct 3 ADMOB plugins? This has been an option for sometime now within the builder, however there are countless users. (all to be exact) that can not use admob. 

Having to use cacoon will only reduce the quality of a construct 3 app with their bs splash screen..

It's been months now.

**Comment by TobyReeno** [comment]
You misunderstand the request here @odapplications 

It's not about the native C3 AdMob plugin. It's for my Ultimate Ads and Ultimate IAP (3rd party) plugins to be able to use the C3 wrapper. And even though these Cordova plugins start with "cocoon", they are not Cocoon dependent, just made by Ludei.

**Comment by shortercode** [comment]
Okay should all work now.

**Comment by shortercode** [comment]
This bug is closed, and by the sounds of it does not cover your issue. If
you have a problem with the build service can you please open a new issue
and I will help you there.

**Comment by TobyReeno** [comment]
Sorry to reply here even though you closed it, but I think I know what's going on.

Ludei recently released updated plugins marked as v2.x.x. These have different API so are not backward compatible. To bypass the issue you should specify the version as below in config.xml

```
<plugin name="cocoon-plugin-ads-ios-admob" spec="^1.0.0"/>
<plugin name="cocoon-plugin-ads-android-admob" spec="^1.0.0"/>
```

**Comment by QuasarX** [comment]
@TobyReeno 
Good point. I already tried that codes (I see in Discord) but it is not works too.
