### ISSUE TITLE
Cannot create const var starting with number, creating var doing so crashes it.

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#887]
## Problem description

Cannot create a global constant var starting with a number such as 8DIRECTIONS, it gets reset to DIRECTIONS. Trying to create a global var (not a const one) with the 8DIRECTIONS name causes C3 to crash.

## Attach a .c3p
[New project.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1360188/New.project.c3p.zip)

## Steps to reproduce

1. open a new project
2. create a global var, tick the const, name it 8DIRECTIONS
2,1 notice how the name is reset to DIRECTIONS
3. create a global var without the const ticked, name it 8DIRECTIONS
3.1 notice the crash

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Error report information
Type: unhandled rejection
Reason: Error: event variable name 'dir' already in use @ Error: event variable name 'dir' already in use at t.ǃqG (https://editor.construct.net/r60/main.js:74:279596) at i.ǃOH.then (https://editor.construct.net/r60/components/editors/eventSheetView/eventSheetView.js:1:30817) at 
Stack: Error: event variable name 'dir' already in use at t.ǃqG (https://editor.construct.net/r60/main.js:74:279596) at i.ǃOH.then (https://editor.construct.net/r60/components/editors/eventSheetView/eventSheetView.js:1:30817) at 
Construct 3 version: r60
URL: https://editor.construct.net/
Date: Thu Oct 05 2017 19:47:29 GMT+0300 (GTB Daylight Time)
Uptime: 33.6 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r60
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by JeFawk** [comment]
![image](https://user-images.githubusercontent.com/7268697/31241984-3f8de04c-aa0e-11e7-96c7-1c528179a375.png)

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r61. C3 did not allow variable names starting with a number, but C2 allowed it - I've updated it to allow it in C3 as well.
