### ISSUE TITLE
iOS List Object always shows as Dropdown List

### ISSUE THREAD

**Issue by PudgyPlatypus** [Scirra/Construct-3-bugs#889]
## Problem description

When using C3 on my iOS devices in Firefox, if I have a List Object on a layout, even if it is set to a List Box, always shows as a Dropdown List.

## Attach a .c3p

https://www.dropbox.com/s/7s6kyz3dc6l60cs/ExampleList.c3p?dl=0

## Steps to reproduce

1. Add List Object
2. Set type to List Box
3. Run

## Observed result

It shows like one big button (dropdown list)

## Expected result

A scrollable list of items that I can select (works fine on desktop)

## Affected browsers

iOS
* Safari: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 11.0
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1
C3 release: r60
Language setting: en-US

**Comment by AshleyScirra** [comment]
iOS has no equivalent to the list control, it only supports a dropdown. This is a missing feature on iOS so there's nothing we can do about it.
