### ISSUE TITLE
Inconsistent 8Direction Behavior

### ISSUE THREAD

**Issue by TGeneDavis** [Scirra/Construct-3-bugs#89]
## Problem description

Default 8Direction controls behavior is not the same as simulated controls behavior. It appears the values for Deceleration/Acceleration behave differently for default and simulated controls.

## Attach a .c3p

https://app.box.com/s/8qrxwg5q8fa1etlxoorozhawkw7y5yfk

## Steps to reproduce

1. Run C3P with left & right 8Direction behavior with 200 speed, 10000 acceleration, and 0 deceleration, and default controls enabled, and simulated controls disabled
2.Next run with default controls disabled, and simulated controls enabled

## Observed result

For default controls, the sprite reverses direction instantly. For simulated controls, the sprite stops moving and needs a second prompt to reverse direction

## Expected result

Left and right controls should behave the same for simulated and default controls.

## Affected browsers

* Chrome: yes
Have not tried other browsers.

## System details

OS X, newest OS, newest Chrome

<details><summary>OS X, newest OS, newest Chrome</summary>

Have seen this behavior on newest Android, too.

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 9 gb
Storage usage (approx): 129 mb (1.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Not a bug. You use 'On key pressed' instead of 'Is key down' so the movement only applies for 1 tick.
