### ISSUE TITLE
Safari not playing sound

### ISSUE THREAD

**Issue by andychan1998** [Scirra/Construct-3-bugs#891]
## Problem description

A layout has a single button.  When that button is clicked, it's suppose to play a sound.  However, there's no sound.  This is only a problem on Safari for my iPhone though.  It seems to work fine on my PC Chrome browser.  Also, this problem only seems to start happening today.  I am not sure it's because of the new update to my phone, or new Construct 3 release.

## Attach a .c3p

Please download from https://drive.google.com/open?id=0B8XY81b11D4sODduVC1vWGktTlE.

## Steps to reproduce

1. Run the attached .c3p on a server, and point Safari browser from iPhone to it.
2. Click on the "Play" button.

## Observed result

No sound is heard.

## Expected result

Two audio files should be played.  One is a "sound" and the other is a "music" file.

## Affected browsers

* Chrome: no
* Firefox: not sure
* Edge: not sure
* Safari: yes (only on latest iOS version for my iPhone 6)

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r60
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 876 mb (1.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
How are you testing this? Are you using Remote Preview?

**Comment by andychan1998** [comment]
No, I exported and loaded onto my server when testing.


Thanks.


- Andy



________________________________

**Comment by AshleyScirra** [comment]
It works for me now, but we made some changes to how audio playback works for the next build, so it might be that helped fix it. Let's review this again when r61 is out.

**Comment by AshleyScirra** [comment]
r61 is out, please check again!

**Comment by andychan1998** [comment]
Thanks.  The problem seems to be resolved.


- Andy



________________________________
