### ISSUE TITLE
Animation preview close button when editing points

### ISSUE THREAD

**Issue by SebaSOFT** [Scirra/Construct-3-bugs#894]
## Problem description

Usually when clicking close button in preview animation window, the underlying image editor receives the click also, causing pivots to move.

## Attach a .c3p

Not needed as a .c3p will not show editor's behaviour

## Steps to reproduce

1. Import/create an animation
2. Make sure you are using a brush/eraser tool or the image point editing tool
2. Preview it, using the animation preview window
3. click close button making sure preview window and mouse are over the image editor

## Observed result

The click is received by the editor, changing the position of the pivot, or brushing/erasing part of the bitmap

## Expected result

Just to close the window

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

Local storage
Storage quota (approx): 24 gb
Storage usage (approx): 59 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

Looks like the current (r59) version of the image editor, when you are editing pivots. The preview screen close button detects mousedown and the mouseup if coincidently located in the image editing canvas, the pivot is missplaced. This may apply to other popups that are present (ie closing the image editor and the mouse up causes an event in the layout editor.

</details>

**Comment by AshleyScirra** [comment]
Assigning to Diego but it might be more of a UI library issue - perhaps clicks on the X should have propagation stopped so they don't reach anything else.

**Comment by DiegoScirra** [comment]
Haven't been able to reproduce this one in Chrome 61.

Tried it out in Windows 10, OSX 10.13 and Ubuntu 17.04.

Maybe it has something to do with the specific version of Linux @SebaSOFT is using?

**Comment by SebaSOFT** [comment]
lubuntu Zesty
Attached a file, was able to reproduce also in Chrome 61

I tough is was having to do with "release outside" the button, but it doesn't.

It is more likely to happen if the click is performed hastily enough

Also confirmed that the popup is closing on mouse down, not sure if this should be ok

Attaching a video capture
[2017-10-11_14-22-41.mp4.zip](https://github.com/Scirra/Construct-3-bugs/files/1376593/2017-10-11_14-22-41.mp4.zip)
