### ISSUE TITLE
Upper/Lowercase Renaming gives Error Message in Animation Editor

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#900]
## Problem description

When having a new Sprite and trying to rename an animation from, let's say "Animation1" to "animation1" it gives the Message "Name is already used".

## Steps to reproduce

1. Open new Project
2. Create Sprite
3. Open Sprite in Animation Editor
4. Change the Animation1 Name to "animation1"

## Observed result

Error Message and no renaming happening.

## Expected result

That it let's me rename the Animation, since it's quite inconvenient to first delete the name and then re-click to change it again.

## Affected browsers

* Chrome: yes

</details>

**Comment by mOOnpunk** [comment]
I was just about to report this bug :)

**Comment by DiegoScirra** [comment]
Fixed in r62.
