### ISSUE TITLE
Array Editor: Renaming File in Properties Window doesn't Update Tab Name

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#901]
## Problem description

When creating a new Array with the Array Editor under "Files" and then, with the Tab for the new Array open, changing the Name in the File Inspector, it doesn't update the Name in the Tab until you close and reopen the Array.

## Steps to reproduce

1. Create new File
2. Create new Array under Files -> New -> Array
3. Have the new Array open in the Editor
4. Change the name of the Array in the Project Window

## Observed result

Name change is not updated in Tab of Array in the Layout Screen.

## Expected result

The name to update.

## Affected browsers

* Chrome: yes

**Comment by shortercode** [comment]
Found it, the variable name for the file changed during the refactor and the name update event still used the old variable name. Will be fixed in r61
