### ISSUE TITLE
need to remove error addon

### ISSUE THREAD

**Issue by kagnarok** [Scirra/Construct-3-bugs#904]
## Problem description

Error report information
Type: unhandled rejection
Reason: Error: invalid addon id @ Error: invalid addon id at o.ǃgdY (https://editor.construct.net/r60/main.js:84:29194) at n.ǃzn (https://editor.construct.net/r60/main.js:74:444272) at ǃY.ǃzv.addEventListener (https://editor.construct.net/r60/main.js:84:18501) at Object.t.push.ǃY.ǃgH [as ǃjVm] (https://editor.construct.net/r60/main.js:2:265011) at n (https://editor.construct.net/r60/main.js:2:267438) at t (https://editor.construct.net/r60/main.js:2:267224)
Stack: Error: invalid addon id at o.ǃgdY (https://editor.construct.net/r60/main.js:84:29194) at n.ǃzn (https://editor.construct.net/r60/main.js:74:444272) at ǃY.ǃzv.addEventListener (https://editor.construct.net/r60/main.js:84:18501) at Object.t.push.ǃY.ǃgH [as ǃjVm] (https://editor.construct.net/r60/main.js:2:265011) at n (https://editor.construct.net/r60/main.js:2:267438) at t (https://editor.construct.net/r60/main.js:2:267224)
Construct 3 version: r60
URL: https://editor.construct.net/
Date: Mon Oct 09 2017 15:10:15 GMT+0700 (+07)
Uptime: 2 s

Platform information
Browser: Chrome
Browser version: 60.0.3112.113
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
C3 release: r60
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Graphics 550
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Use [safe mode](https://www.construct.net/make-games/manuals/addon-sdk/guide/safe-mode) to remove broken addons.

**Comment by kagnarok** [comment]
Thank sir!!
