### ISSUE TITLE
Cloning from Project windows does not copy object settings.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#905]
## Problem description

When cloning an object from the project window, new object will have their values reset after being placed in the layout. This seem to affect all objects that can be placed in layout.

Cloning the object in layout the layout view will clone the object settings as expected, and does not reset the values.

## Attach a .c3p

N/A

## Steps to reproduce

1. Create a Particle object and place it in the layout, and make some random settings to it.
2. Right click & Clone the object from the Project window (here the settings look correct)
3. Place the new object in the layout. (this is where the settings get reset)
4. Settings has been reset to that of a brand new particle object.

## Observed result

When an object is cloned from the Project window, the new object will reset values when placed in the Layout.

This is also true for any object instance variables. Not only the object settings. All instance variables will get reset to zero after placing a cloned object in layout.

## Expected result

Should have kept the settings, just as when cloning from the Layout.

## Affected browsers

* Chrome: yes/no

**Comment by joelmayer87** [comment]
I had the same problem with SpriteFonts not saving Character sets or associated behaviors etc.

**Comment by AshleyScirra** [comment]
Should be fixed in r66.
