### ISSUE TITLE
Effect errors not being caught by 'safe-mode'

### ISSUE THREAD

**Issue by blackhornet2010** [Scirra/Construct-3-bugs#906]
## Problem description

Errors in the Effect ADDON files are not being caught by the safe-mode override.

## Attach a .c3p

Duplicate Bulge addon attached.

## Steps to reproduce

1. Create an Effect with a name that already exists
OR
1. Remove the comma from the language JSON file in the parameters data (ie: between name & desc)

## Observed result

Uncaught (in promise) Error: key name 'effects.bulge.name' already exists in language string map
OR
<another error for the language error - not captured - sorry>

## Expected result

Errors should be ignored as per safe-mode mechanism.

## Affected browsers

N/A

## System details

[bulge_test.zip](https://github.com/Scirra/Construct-3-bugs/files/1369455/bulge_test.zip)

**Comment by AshleyScirra** [comment]
Fixed for r62 - it won't try to load the language file at all in safe mode. A bigger problem though is it lets you install an addon with the same ID as an existing installed addon (it uses the id `bulge` which is a built-in addon ID). So I fixed that too, you won't be able to install an addon with a duplicate ID.
