### ISSUE TITLE
Crash when closing several projects

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#907]
## Problem description

I was right-clicking on project names in the project list to close them, and Construct crashed.

## Attach a .c3p

No cp3 - this happened with multiple projects open.

## Steps to reproduce

(Only seen once so far, will update if I narrow the steps.)

1. Open several projects from local files.
2. Make changes to them.
3. Right-click one of them in the projects list and choose to close it from the context menu.
4. Construct asks if you want to save. Choose to save.
5. Attempt to close the next project the same way.

## Observed result

Construct crashes.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r60/main.js, line 74, col 214846
Message: Uncaught TypeError: Cannot read property 'ǃKA' of null
Stack: TypeError: Cannot read property 'ǃKA' of null at g.ǃlr (https://editor.construct.net/r60/main.js:74:214846) at g.ǃri (https://editor.construct.net/r60/main.js:74:215038) at window.ǃnc.ǃjne (https://editor.construct.net/r60/components/editors/layoutView/layoutView.js:1:33079) at g.ǃZB (https://editor.construct.net/r60/main.js:74:219321) at d.ǃZB (https://editor.construct.net/r60/main.js:74:252442) at d.ǃZB (https://editor.construct.net/r60/main.js:74:238361) at l.ǃZg (https://editor.construct.net/r60/components/editors/layoutView/layoutView.js:1:55507) at Array.ǃJQ (https://editor.construct.net/r60/components/editors/layoutView/layoutView.js:1:54000) at ǃY.Event.ǃjCV.ǃjVj (https://editor.construct.net/r60/main.js:2:264400) at window.ǃnc.dispatchEvent (https://editor.construct.net/r60/main.js:2:262860)
Construct 3 version: r60
URL: https://editor.construct.net/index.html
Date: Mon Oct 09 2017 23:14:42 GMT-0700 (Pacific Daylight Time)
Uptime: 3540.2 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r60
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Crash report looks like it might be something to do with global layers. Still without the exact projects you're using and more specific steps than "Make changes to them", we can't follow what you're doing, so marking as no repro. Assigning to Diego in case he can figure out what's going on but otherwise may have to close.

**Comment by DiegoScirra** [comment]
This was related to #920.

Closing a project with with an instance in a layout view from another project crashed C3.
