### ISSUE TITLE
Updating Addons - Doesn't Update on saving Project

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#909]
## Problem description

When Updating a Third Party Addon (in this case, again, Toby R's Animated Text Addon), there is a prompt showing up saying, the Addon would be updated the next Time the Project is saved. However, it doesn't seem to really update until you close the project and refresh C3

I unfortunately don't know if i can provide a .c3p with the necessary files, since the Animated Text Addon is a commercial one but if you need it for testing, best get in touch with him.

![image](https://user-images.githubusercontent.com/30116964/31375887-4e58ac18-ada3-11e7-86d2-10247fbbfe99.png)

## Steps to reproduce

1.Create new Project
2.Add an Addon in an earlier Version
3.Save Project Bundled with Addon
4. Close Project
5. In the Addon Manager, Update Editor Version of the Addon
6. Reopen Project
7. In The Projectname->Tools->View used Addon Menu, choose the Addon and update to Editor Version
8. Popup shows up
9. Save Project
10. Changes added to Addon don't take effect and the Used Addons Menu still shows the old version
11. Close Project
12. Reopen Project
13. Now the new Version of the Addon should show up although sometimes it worked only for me when refreshing Construct 3 

## Observed result

Addon was not updated as shown and did not take immediate Effect while still in the Project.

## Expected result

Since the MessageBox sais the Addon would be updated the next Time i saved the Project i would've expected it to do just that and not having to close and reopen the project and restart C3. This might either be just a naming issue but of course, if it would behave as the Messagebox sais it would be most convenient.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
This is by design. The saved project includes the updated addon, but it won't use it until you reload the project, because C3 doesn't support live-swapping a currently in-use addon.

**Comment by joelmayer87** [comment]
@AshleyScirra Yes that might be but i think the PopUp Box when updating an Addon is misleading since it states that changes will take effect after "saving" the project not reloading it. I think maybe just a simple addition to the Dialogue Box like "Please Restart Construct 3 for the changes to take effect" would help to make it less confusing...

**Comment by AshleyScirra** [comment]
OK, I added a note about closing and reopening the project. It just missed r61 though so should be in r62.

**Comment by joelmayer87** [comment]
@AshleyScirra Perfect Thanks! Well nevermind, i think i got one or two other fixes in there as well :D
