### ISSUE TITLE
mobile version image editor view

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#91]
## Problem description
in mobile version if i have 5.5 inch screen 
i open image editor i can see only 2 tools on left side. 
it should scroll 
*in mobile version if i have 5.5 inch screen 
i open image editor i can see only 2 tools on left side. 
it should scroll up to down
Mostly i use it on desktop but sometime when i wish to do some little work then i choose to do on mobile but i can't because when i want to inset a sprite i cant fill it with colors*

## does not require file

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. just open c3 in 5.5 inch mobile landscape mode

## Observed result

*i cant see all tools*

## Expected result

*i want it to scroll up-down according to finger move*

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by jaydonteh** [comment]
Would be nice if you can attach a screenshot here.

**Comment by AlexSanchezCdz** [comment]
![captura2](https://cloud.githubusercontent.com/assets/13063557/25277165/dbfdc5fe-269d-11e7-92ad-9ee52639c7d2.PNG)
![captura](https://cloud.githubusercontent.com/assets/13063557/25277166/dbfebdb0-269d-11e7-8ff5-3db50db7d448.PNG)

There is no way to scroll to see all tools :(

**Comment by DiegoScirra** [comment]
All scroll bars of the Image Editor are now scrollable in mobile devices. The top bar doesn't wrap anymore, so that leaves some more space for the editing area.

The status bar has also been removed in mobile devices as it isn't so useful and it takes up valuable space.

**Comment by luckyrawatlucky** [comment]
1 more thing to be done here
when we double tap on layout to insert new object
and popup "create new object type" comes with keyboard popup by default and covers whole screen
So Please hide keyboard by default and if we have to search anything we can do it manually when we need

![screenshot_2017-04-28-10-34-06-562_com android chrome](https://cloud.githubusercontent.com/assets/17684135/25515050/776cc2e0-2bff-11e7-89e0-9d07a9e37b22.png)
![screenshot_2017-04-28-10-33-27-105_com android chrome](https://cloud.githubusercontent.com/assets/17684135/25515051/7775d42a-2bff-11e7-91be-012ef902cbdb.png)
