### ISSUE TITLE
Missing Manual entry for Move To Behavior

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#912]
## Problem description

see title :)

## Observed result

no details about behavor actions etc.

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by joelmayer87** [comment]
@TheBl4ckSh33p I think that's a 3rd party behaviour by rexrainbow not a default one by Scirra... So that's why there's no manual entry for it ;)

**Comment by TheBl4ckSh33p** [comment]
oops, totally forgot that I installed a few plugins a few months ago. (could not work for a while)
Sorry.

**Comment by AshleyScirra** [comment]
Yep, it's not an official behavior.
