### ISSUE TITLE
Mouse cursors don't change in Safari

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#913]
Mouse cursors still don't change in Safari (e.g. crosshair place tool). It works in dev but after the build, it doesn't work again. So mouse cursors still don't change in Safari on editor.construct.net.

**Comment by shortercode** [comment]
It would appear that the change I put into the cursors.css file has been reverted in the build, although I'm not sure if this is a side effect of the build or an actual reversion of the file. I tried running a simple test with clean-css but it didn't repeat what I expected to be happening, I'm trying to test the build now ( having some issues with package dependencies... )

**Comment by AshleyScirra** [comment]
It would make sense that a CSS minifier might combine selectors... maybe we need a way to prevent that.

**Comment by shortercode** [comment]
I managed to replicate this on the build, but not in a minimal file. I was calling clean-css using the module version, not the CLI one and the commands are not easy to map from one to the other. So it might have been running differently.

There's a comment style command to not minify a given chunk, so I'm trying that right now.

**Comment by shortercode** [comment]
@AshleyScirra has taken this over, was fixed in r63
