### ISSUE TITLE
IDE Crash when changing order in Image Point list

### ISSUE THREAD

**Issue by NitidOnline** [Scirra/Construct-3-bugs#916]
## Problem description

IDE crash when changing the order of an image point in an animation with two or more frames.
It is possible to change the order of imagepoints un one of the frames, but crash with the next frame change.
This happen too if you change the IP position and use the menu option "Apply to whole animation"

## Attach a .c3p

[ImagePointCrash.zip](https://github.com/Scirra/Construct-3-bugs/files/1372944/ImagePointCrash.zip)

## Steps to reproduce

1. Go to Image Point Edito of a sprite (all with the same igmagepoints)
2. Select a frame
3. Use the arrow button to move up or down an IP
4. Select next frame
5. Use the arrow button or the menu option "Apply to whole animation"
6. IDE Crash

## Observed result

IDE crash

## Expected result

Imagepoint position in list changes.

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r61/main.js, line 63, col 198310
Message: Uncaught Error: cannot find image point in this frame
Stack: Error: cannot find image point in this frame at u.ǃUek (https://editor.construct.net/r61/main.js:63:198316) at e.ǃJTb.ǃJTn (https://editor.construct.net/r61/main.js:73:141746) at Array.ǃDW.addEventListener (https://editor.construct.net/r61/main.js:73:137532) at ǃU.Event.ǃuxx.ǃueu (https://editor.construct.net/r61/main.js:2:264995) at ǃU.ǃq.ǃGf.dispatchEvent (https://editor.construct.net/r61/main.js:2:263282) at ǃU.ǃq.ǃX.ǃUAR.ǃuUD.ǃUXx (https://editor.construct.net/r61/main.js:2:528546) at ǃU.ǃq.ǃX.ǃUAR.ǃuUD.ǃUXd (https://editor.construct.net/r61/main.js:2:527178) at HTMLElement.click.a.ǃj$ (https://editor.construct.net/r61/main.js:2:524958) at HTMLDocument. (https://editor.construct.net/r61/main.js:2:260049)
Construct 3 version: r61
URL: https://editor.construct.net/index.html
Date: Tue Oct 10 2017 20:14:31 GMT+0200 (Hora de verano romance)
Uptime: 76.7 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r61
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2048
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r62. Thanks for reporting.
