### ISSUE TITLE
r61 Win10 UWP export not passing test (UTF-8 error)

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#918]
## Problem description

After building the app for the store the tests returned errors and it failed.
I tried to save the files in UTF8 in visual studio as described in the report but it did not fix it. 

## Steps to reproduce

1. export uwp app 
2. open in visual studio
3. added xbox live package
4. assigned app to store entry
5. built app package

## Observed result

tests after building shows errors
Bereitstellungs- und Starttests

NICHT BESTANDEN
Generierung von Bytecode
Fehler: Beim Test der Bytecodegenerierung wurden folgende Fehler erkannt:
In der Datei \\?\C:\Program Files\WindowsApps\58213Bl4ckSh33p-Soft.Theverylongwalk_1.1.4.0_x64__asda3k4nqej0g\start.js liegen Probleme mit der JavaScript-Syntax oder sonstige Probleme vor.
In der Datei \\?\C:\Program Files\WindowsApps\58213Bl4ckSh33p-Soft.Theverylongwalk_1.1.4.0_x64__asda3k4nqej0g\opus.wasm.js liegen Probleme mit der JavaScript-Syntax oder sonstige Probleme vor.
In der Datei \\?\C:\Program Files\WindowsApps\58213Bl4ckSh33p-Soft.Theverylongwalk_1.1.4.0_x64__asda3k4nqej0g\opus.js liegen Probleme mit der JavaScript-Syntax oder sonstige Probleme vor.
In der Datei \\?\C:\Program Files\WindowsApps\58213Bl4ckSh33p-Soft.Theverylongwalk_1.1.4.0_x64__asda3k4nqej0g\opus.asm.js liegen Probleme mit der JavaScript-Syntax oder sonstige Probleme vor.
In der Datei \\?\C:\Program Files\WindowsApps\58213Bl4ckSh33p-Soft.Theverylongwalk_1.1.4.0_x64__asda3k4nqej0g\c2runtime.js liegen Probleme mit der JavaScript-Syntax oder sonstige Probleme vor.

and UTF-8 errors:
NICHT BESTANDEN
UTF-8-Dateicodierung
Fehler: Beim Test der UTF-8-Codierung wurden die folgenden Fehler erkannt:
Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.theverylongwalk_1.1.4.0_x64__asda3k4nqej0g\c2runtime.js ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).
Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.theverylongwalk_1.1.4.0_x64__asda3k4nqej0g\opus.asm.js ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).
Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.theverylongwalk_1.1.4.0_x64__asda3k4nqej0g\opus.js ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).
Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.theverylongwalk_1.1.4.0_x64__asda3k4nqej0g\opus.wasm.js ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).
Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.theverylongwalk_1.1.4.0_x64__asda3k4nqej0g\start.js ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).
Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.theverylongwalk_1.1.4.0_x64__asda3k4nqej0g\index.html ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).
Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.theverylongwalk_1.1.4.0_x64__asda3k4nqej0g\style.css ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r61
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 895 mb (1.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by TheBl4ckSh33p** [comment]
I created a example (for this error and music issue in r61) and just tried to build an store app package again and had the same problem.

example:
[r61-UWP-MusicBugtest.zip](https://github.com/Scirra/Construct-3-bugs/files/1378688/r61-UWP-MusicBugtest.zip)

built with x86 and x64 package in one file (with Xbox Live UWP files from nuget installed and associated with a test app in my dev account)

Errors in app certification kit:

> Bereitstellungs- und Starttests
> 
> NICHT BESTANDEN
> Generierung von Bytecode
> Fehler: Beim Test der Bytecodegenerierung wurden folgende Fehler erkannt:
> In der Datei \\?\C:\Program Files\WindowsApps\58213Bl4ckSh33p-Soft.Bugtesting_1.1.2.0_x64__asda3k4nqej0g\start.js liegen Probleme mit der JavaScript-Syntax oder sonstige Probleme vor.
> In der Datei \\?\C:\Program Files\WindowsApps\58213Bl4ckSh33p-Soft.Bugtesting_1.1.2.0_x64__asda3k4nqej0g\opus.wasm.js liegen Probleme mit der JavaScript-Syntax oder sonstige Probleme vor.
> In der Datei \\?\C:\Program Files\WindowsApps\58213Bl4ckSh33p-Soft.Bugtesting_1.1.2.0_x64__asda3k4nqej0g\opus.js liegen Probleme mit der JavaScript-Syntax oder sonstige Probleme vor.
> In der Datei \\?\C:\Program Files\WindowsApps\58213Bl4ckSh33p-Soft.Bugtesting_1.1.2.0_x64__asda3k4nqej0g\opus.asm.js liegen Probleme mit der JavaScript-Syntax oder sonstige Probleme vor.
> In der Datei \\?\C:\Program Files\WindowsApps\58213Bl4ckSh33p-Soft.Bugtesting_1.1.2.0_x64__asda3k4nqej0g\c2runtime.js liegen Probleme mit der JavaScript-Syntax oder sonstige Probleme vor.
> Auswirkungen, falls nicht behoben: Als Leistungsoptimierung zum Verkürzen der Ausführungszeit für JavaScript generieren JavaScript-Dateien mit der Erweiterung ".js" bei der Bereitstellung der App Bytecode. Diese Optimierung verkürzt die Start- und Ausführungszeiten für JavaScript wesentlich. 
> Behebungsmethode: Möglicherweise müssen Sie einen oder mehrere dieser Schritte berücksichtigen, um das Problem zu beheben:
> - Stellen Sie die App nicht durch Drücken von F5 in Visual Studio bereit. Erstellen Sie stattdessen ein APPX-Paket.
> - Stellen Sie sicher, dass die Ereignisprotokollierung aktiviert ist
> - Alle JavaScript-Dateien sind syntaktisch gültig; andernfalls schließen Sie die betreffenden Dateien aus dem Paket aus
> - Beachten Sie, dass Sie alle vorherigen Versionen der App deinstallieren müssen, bevor Sie mit der der Bereitstellung beginnen
> Andernfalls schließen Sie die betreffenden Dateien aus dem Paket aus.
> 

And:

> Dateicodierungstest
> 
> NICHT BESTANDEN
> UTF-8-Dateicodierung
> Fehler: Beim Test der UTF-8-Codierung wurden die folgenden Fehler erkannt:
> Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.bugtesting_1.1.2.0_x64__asda3k4nqej0g\c2runtime.js ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).
> Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.bugtesting_1.1.2.0_x64__asda3k4nqej0g\opus.asm.js ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).
> Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.bugtesting_1.1.2.0_x64__asda3k4nqej0g\opus.js ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).
> Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.bugtesting_1.1.2.0_x64__asda3k4nqej0g\opus.wasm.js ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).
> Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.bugtesting_1.1.2.0_x64__asda3k4nqej0g\start.js ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).
> Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.bugtesting_1.1.2.0_x64__asda3k4nqej0g\index.html ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).
> Die Datei C:\Program Files\windowsapps\58213bl4cksh33p-soft.bugtesting_1.1.2.0_x64__asda3k4nqej0g\style.css ist nicht ordnungsgemäß UTF-8-codiert. Speichern Sie die Datei erneut als UTF-8 (einschließlich Bytereihenfolge-Marke).
> Auswirkungen, falls nicht behoben: HTML-, CSS- und JavaScript-Dateien müssen im Format UTF-8 mit entsprechender Bytereihenfolge-Marke (Byte-Order Mark, BOM) codiert werden, um die Bytecode-Zwischenspeicherung nutzen zu können und andere Fehler zur Laufzeit zu vermeiden. 
> Behebungsmethode: Öffnen Sie die betreffende Datei, und wählen Sie in Visual Studio im Menü "Datei" den Eintrag "Speichern unter" aus. Wählen Sie neben der Schaltfläche "Speichern" im Dropdown-Steuerelement die Option "Mit Codierung speichern" aus. Wählen Sie im Dialogfeld "Erweiterte Speicheroptionen" die Option "Unicode (UTF-8 mit Signatur)" aus, und klicken Sie auf die Schaltfläche "OK".

**Comment by AshleyScirra** [comment]
IIRC UWP is fussy about the UTF-8 Byte Order Mark (BOM). If you find a way to save the file with BOM does that fix it?

**Comment by TheBl4ckSh33p** [comment]
I tried saving it as UTF8 in visual studio but got the same error.
Here are the options available: 
![utf8_options](https://user-images.githubusercontent.com/2725603/31492136-06a02ee8-af4a-11e7-8c4f-204cbc0e2bc4.jpg)

**Comment by AshleyScirra** [comment]
No, we haven't touched the UWP exporter for several releases now, so this is odd.

**Comment by TheBl4ckSh33p** [comment]
The only other new thing is I updated Visual Studio to version 15.4. 🤔🙁

**Comment by AshleyScirra** [comment]
Turns out we do just need to explicitly prefix a few files with the UTF-8 BOM, and then WACK accepts it. Should be fixed in r64.
