### ISSUE TITLE
Opening a sprite in the image editor does not default the selection to the "initial frame"

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#919]
## Problem description

Opening a sprite in the image editor does not default the selection to the "initial frame", instead it goes to frame 0.

## Attach a .c3p

[openimagebug.zip](https://github.com/Scirra/Construct-3-bugs/files/1374306/openimagebug.zip)

## Steps to reproduce

1. Double Click on the sprite which has the initial frame setting of 3.

## Observed result

Notice that the image editor shows frame 0.

## Expected result

It should show the frame that you have selected as the initial frame. 

(This bug may also apply to "Initial Animation", but I will check that at another time.)

**Comment by DiegoScirra** [comment]
Added to r67.
