### ISSUE TITLE
[r18.2] Imported files cannot undo

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#92]
## Problem description

After importing a file, this action cannot undo.

## Steps to reproduce

1. Import any file to C3 with the import window from the project bar.
2. Undo.

## Observed result

Cannot undo.

## Expected result

Can undo after importing files.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
The import code calls in to Iain's code so assigning to Iain.

**Comment by shortercode** [comment]
It was just missing the undo code. I've implemented undo for ImportFiles and ImportAudio now. Just going through other related places to check if they have undopoints set or not.

This has missed the boat for r20 but should be in r21 I expect.

**Comment by shortercode** [comment]
Okay should all be sorted now, also added in undo points for the context menu "New [ JSON / HTML / ... ]"
