### ISSUE TITLE
Dragging an object from one project to another will break the project

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#920]
## Problem description
EDIT: OK it's really simple - just open two projects at once and click and drag a sprite in the Projects view from one project into the other, and save the other. The one you dropped the sprite into will no longer open if you try to load it.

After saving a project (by downloading) and attempting to open it again the next day, the project wouldn't open, and neither would the most recent autosave (stored in browser memory).

## Attach a .c3p

[SpriteProgressBar._autosave_.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1374418/SpriteProgressBar._autosave_.c3p.zip)

## Steps to reproduce
EDIT: Please disregard these steps - the actual steps are in the updated problem description above.

Only seen once with the attached file, but a couple other projects I've saved recently (say, withing the last ten versions of C3 or so) have had the same problem. So it seems repeatable, but very rare.

1. Create or open a project. (in this case in r60)
2. Work on it long enough for it to autosave, and then save by downloading.
3. Attempt to open either the standalone file or the browser-saved file (in this case in r61)

## Observed result

In the case of the stand-alone file, Construct displays a message that says "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

In the case of the browser-saved file, Construct says "i.!UID is not a function."

## Expected result

File should open.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r61
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 435 mb (3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I'm looking through the autosave at the moment and it has a mismatch between the objects in the project and the instances in the first layout. The project contains a blank sprite object but the layout contains a sprite called "PBFill" with a tint, which I'm guessing are the same object but recorded at different times.

I can kinda see how this could happen if you were creating a sprite when it was saving, but I'm not sure if anyone could be fast enough to create a sprite, rename it and add a tint in the time it takes C3 to archive a small project! Could you send the manual save over as well? I'm curious if it has the same problem. Also how much more work do you expect there to be on the manual save?

**Comment by Scoremonger** [comment]
Ah, you just reminded me of something that's probably pretty significant - the PBFill sprite was referenced in events I had pasted from an older project as I was trying to port some logic into a new project. I'm not at the PC I was using when this happened so I don't have the manual save on hand, but I'm pretty sure it's almost identical to the autosave (the timestamps on them are only a minute or two apart iirc). I'll try to upload it tonight (California time) if you still want it, but in the meantime I can try recreating the bug from scratch and upload that with some repro steps instead, since it's probably to do with copy/pasting Events and/or objects from other projects.

**Comment by Scoremonger** [comment]
OK it's really simple - just open two projects at once and click and drag a sprite in the Projects view from one project into the other, and save the other. The one you dropped the sprite into will no longer open if you try to load it.

**Comment by shortercode** [comment]
Ah nice thanks @Scoremonger that would explain how it got into such a weird state, going to drag @AshleyScirra in here as I'm pretty sure this is his area. I've confirmed that the project from that replication matches the original problem. There's an instance of a sprite in the layout but the sprite itself isn't in the project ( crazy stuff ).

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in r64 which now prevents cross-project drag-and-drop.
