### ISSUE TITLE
When I try to resize my sprite and set origin/collision, my images go away and i have to do it all again

### ISSUE THREAD

**Issue by Contadojuan** [Scirra/Construct-3-bugs#922]
[RetroNinja.zip](https://github.com/Scirra/Construct-3-bugs/files/1377386/RetroNinja.zip)
## Problem description

Hello, i was trying to edit some sprites on my imported C2 project, so i opened my sprite, "cut" it to resize and paste again, when i set the origin and adjust the collision, my images go away and the animation frame became empty

## Steps to reproduce

1. Open sprite editor
2. Create a new animation
3. Import one image, use rectangle select to resize it excluding the "extra pixel empty border", CTRL + C and resize canvas to 1,1
4. CTRL V and set origin and collision, what happens next to me is the canvas clean and i have to do it all again, just to get the bug again

## Observed result

My canvas turns empty

## Expected result

I just want to properly edit my animations like i did on c2

## Affected browsers

* Chrome: yes

**Comment by Contadojuan** [comment]
update : tested in firefox, same

**Comment by DiegoScirra** [comment]
Fixed in r65.
