### ISSUE TITLE
r61 UWP exports dont stream music properly

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#923]
## Problem description

since r61 my exports running in Visual Studio preview (after adding the UWP from nuget for xbox live plugin) are not playing background music at all or it takes 10-30 seconds to load before music is played. 

I created a example file playing a music file with 2 layouts. sometimes music is not played for quite some time and then starts when switching profile. before r61 and in c3 editor preview it worked fine and instantly. 

## Attach a .c3p

[r61-UWP-MusicBugtest.zip](https://github.com/Scirra/Construct-3-bugs/files/1378652/r61-UWP-MusicBugtest.zip)

## Steps to reproduce

1. add music on different layouts
2. export for UWP (with xbox live plugin)
3. install uwp files from nuget
4. preview as x64  in visual studio

## Observed result

music delayed sometimes for 10-30 secs or more

## Expected result

music should play after switching profiles (start of layout)

## Affected browsers

UWP

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r61
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 916 mb (1.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Are you only seeing this when you install the Xbox Live nuget package? Do you not see this happen if you don't do that? Is that why it's included in your steps to reproduce?

**Comment by AshleyScirra** [comment]
I gave it a spin and it seems fine, it always plays the track within a second or two. There's a few things to consider here:

- you're using WebM Opus audio files which Edge/Win10 does not natively support, so we [decode them ourselves](https://www.scirra.com/blog/211/opus-audio-in-construct-3). This doesn't support streaming so it will have to completely decode the audio before starting playback. You can encode your audio to AAC yourself and they'll be natively supported on this platform, with streaming support.
- I tested with the Fall creator's update which has Edge 16, which also supports WebAssembly, which allows it to use our faster wasm audio decoder. You might still be getting the asm.js version.
- If you run in debug mode, it may disable optimisations, as well as disabling asm.js support, causing very slow decoding if you're not using the wasm decoder. Try switching to release build and launch without debugging to test with maximum performance.

Anyway, I don't think it's a problem (most likely just debug build + asm.js slowness), and even if it is you can work around it by using AAC audio instead, so closing.
