### ISSUE TITLE
R62 "Failed to open Project"

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#924]
## Problem description

Well, i could open any project i worked on yesterday but today it gives me a "failed to open" project. It's a commercial project still very early in the works so i don't feel quite comfortable sharing it on here but i'll email it to support@scirra.com

**UPDATE**

After completely removing my History and Cache with Chrome it works again. Might be a Caching issue or something...

## Steps to reproduce

1. Try to open Project with R62
2.
3.

## Observed result

Even with restarting Construct, Chrome and the Computer:

![image](https://user-images.githubusercontent.com/30116964/31504020-8a3dddfa-af71-11e7-8b57-5348db6acb33.png)

Alternatively, when trying to open it directly from the Cloud again and not via "Open Recent Projects", i get this message:

![image](https://user-images.githubusercontent.com/30116964/31504241-2a31df6e-af72-11e7-910e-fe02013fe002.png)

When trying to open it locally from my computer, i get this one:

![image](https://user-images.githubusercontent.com/30116964/31504332-691aea4a-af72-11e7-9486-3297aee5788b.png)

## Expected result

The project to open

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r62
Language setting: en-US

Local storage
Storage quota (approx): 131 gb
Storage usage (approx): 789 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M395X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The "not a function" error seems related to `SetLastSaveName`, so assigning to Iain.

**Comment by shortercode** [comment]
Can you forward the project to me @AshleyScirra ?

**Comment by tunchunairarko** [comment]
I also can't open any project file
![untitled2](https://user-images.githubusercontent.com/7689333/31529975-bc66b940-affe-11e7-91f9-14a1fea5f91e.png)

**Comment by joelmayer87** [comment]
@tunchunairako : Delete Chrome History and Cache and restart Browser, it should work then.

**Comment by tunchunairarko** [comment]
@joelmayer87 : My first attempt was that. It didn't work. I uninstalled chrome and reinstalled again and tested, still the same error with r62. I deleted every browsing things, didn't work. Therefore I rolled back to r61, its working fine for now.

**Comment by joelmayer87** [comment]
Huh that's really weird! Worked for anyone until now :O Well, good that it still works with 61 ;)

**Comment by shortercode** [comment]
mmmmm sounds like some sort of compatibility issue between versions... looking into it now

**Comment by shortercode** [comment]
Okay think we've found the issue! The cryptic error code turned out to be pretty much useless, just a small bug covering over the fact that the project failed to open. The real issue seems to be if you have an addon installed, and the same addon also bundled with the project it refuses to load the project.

Many thanks to @MeStrak for his "hunch" about the addon prompt, probably saved me from a good hour sifting through commit logs trying to find this. Fix should be in the next release.

Also just wanted to say thanks to the regulars on here, your help is greatly appreciated!

**Comment by AshleyScirra** [comment]
r62.2 is out now and should be working correctly.

**Comment by joelmayer87** [comment]
@shortercode @AshleyScirra Thanks for the quick fixes and i think we're glad if we can contribute in a small part to C3's success (and non-beta release :P) ;)

**Comment by MeStrak** [comment]
Hi all,I've just updated to r62.2 and I get the error i.!TUd is not a function at the same point as before, just before loading the LiteTween addon :(
Strak    On Friday, 13 October 2017, 13:52:54 CEST, Ashley (Scirra) <notifications@github.com> wrote:  
 
 
r62.2 is out now and should be working correctly.

**Comment by AshleyScirra** [comment]
We had an issue with the server-side caching and released r63 already. Can you try that?

**Comment by MeStrak** [comment]
Just updated to r63, all working now. Thanks!
    On Friday, 13 October 2017, 15:41:32 CEST, joelmayer87 <notifications@github.com> wrote:  
 
 
@shortercode @AshleyScirra Thanks for the quick fixes and i think we're glad if we can contribute in a small part to C3's success (and non-beta release :P) ;)
