### ISSUE TITLE
Mobile: palette and frames bar missing in animation editor

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-3-bugs#925]
## Problem description

When using C3 on an Android phone and opening the sprite animation editor:

- I am unable to access the colour palette for use with paintbrush, fill etc
- the frames bar is inaccessible

I am using a Nexus 5X

## Steps to reproduce

1. Open a new project on a mobile phone
2. Add a sprite object
3. Tap on the sprite to open the animation editor
4. Click on the fill tool

## Observed result

The frames bar is not shown
The palette is not shown 

## Expected result

Both features should be accessible (maybe they are there somewhere but it's not obvious how to access them)

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
You just need to swipe in from the sides. Have you tried that and you're reporting that it doesn't work, or were you just unaware?

**Comment by jakemay74** [comment]
Ah I see - you need to swipe *twice* to see those bars. I got as far as the Animation Properties and Animations bars, didn't realise that an extra swipe was needed. My apologies.
