### ISSUE TITLE
Music doesn't play on iOS after wait

### ISSUE THREAD

**Issue by andychan1998** [Scirra/Construct-3-bugs#927]
## Problem description

Layout has one button, which plays a music file after being tapped.  If I put a wait before playing the music file, then the file wouldn't play until I click on it again.  This problem only happens on my iPhone using Safari browser.

## Attach a .c3p

https://drive.google.com/open?id=0B8XY81b11D4sODduVC1vWGktTlE

## Steps to reproduce

1. Export the c3p as a HTML5 game.  Load it onto a server.
2. Point iPhone Safari browser to the game.
3. Click on the "Play" button.

## Observed result

Music (some narration in this case) doesn't get played until I tap the screen again.

## Expected result

Music should play after the first tap.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari: yes (only on iPhone)

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r62
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 641 mb (1.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a limitation in Safari. It blocks auto-playing music tracks unless it starts playback in a user input trigger.

We can't work around the limitation in Safari, but you can work around it by moving the audio file to the Sounds folder, or by publishing it as a native app where we are able to disable the restriction.

**Comment by andychan1998** [comment]
The music was started by tapping an object though.  The only difference is there's a "wait" before playing the music.


Does this only affect music, but not sounds?  According to the mobile limitations section, it seems to affect sounds as well.


Thanks.


- Andy



________________________________

**Comment by AshleyScirra** [comment]
If you wait, then by the time you try to play music, you're not in a user input trigger any more.

It only affects music, because unfortunately Safari's restrictions are inconsistent! I filed a bug about that with Apple here: https://bugs.webkit.org/show_bug.cgi?id=178120

**Comment by andychan1998** [comment]
I see.  Thanks.


- Andy



________________________________

**Comment by awb11** [comment]
Ashley does that mean if we export it to iOS using Phone Gap than music works properly?

**Comment by AshleyScirra** [comment]
Yes, if you build a mobile app the restrictions should be lifted.
