### ISSUE TITLE
Mouse's sprite opacity

### ISSUE THREAD

**Issue by flipog** [Scirra/Construct-3-bugs#928]
## Problem description

I'm not sure if this is a bug, but when a cursor is set to be a sprite, I cannot change its opacity, I must therefore make its position equal to the mouse's and style the mouse to "None" for such an effect.

## Attach a .c3p

Any file should feature this issue.

## Steps to reproduce

1. Set the mouse to a sprite.
2. Try to change the opacity of said sprite.

## Observed result

The opacity won't change.

## Expected result

I thought it would change.

## Affected browsers

* Chrome: yes
* Firefox: didn't test
* Edge: n/a
* Safari: n/a

## System details

It doesn't crash.

**Comment by AshleyScirra** [comment]
Closing as the cursor is set by the operating system and will ignore the opacity set from C3, which only affects rendering in to the canvas.

**Comment by flipog** [comment]
Oh, you're right! Sorry about that.
