### ISSUE TITLE
R63 : Crash when renaming imported file 

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#929]
## Problem description

When having two files imported of the (in my case a .csv and a .json) same name, C3 seems to group them together. If you try to rename one of the files the software crashes.

## Attach a .c3p

These were the two files with which the error was happening (JSON and CSV).

[dialogues.zip](https://github.com/Scirra/Construct-3-bugs/files/1383915/dialogues.zip)

## Steps to reproduce

1. Import first file "dialogues.json"
2.Import second file "dialogues.csv"
3. Open the fold-out menu with both files in them.
4. Try to rename one of the files.

## Observed result

Crash

## Expected result

No crash would be nice :) 

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r63/components/bars/projectBar/projectBar.js, line 1, col 8495
Message: Uncaught Error: not a named object
Stack: Error: not a named object at window.ǃsu.ǃQs (https://editor.construct.net/r63/components/bars/projectBar/projectBar.js:1:8501) at window.ǃsu.ǃxp (https://editor.construct.net/r63/components/bars/projectBar/projectBar.js:1:7828) at Array.ǃGi.ǃG.ǃCm.ǃG.ǃGW.ǃG$ (https://editor.construct.net/r63/components/bars/projectBar/projectBar.js:1:3147) at ǃG.Event.ǃRfg.ǃRfS (https://editor.construct.net/r63/main.js:2:264578) at ǃG.ǃR.ǃNQ.ǃxj.dispatchEvent (https://editor.construct.net/r63/main.js:2:263038) at ǃG.ǃR.ǃNQ.ǃxj.ǃGlH (https://editor.construct.net/r63/main.js:2:471865) at ǃG.ǃR.ǃNQ.ǃUG.ǃGlb (https://editor.construct.net/r63/main.js:2:484913) at ǃGlt (https://editor.construct.net/r63/main.js:2:473141)
Construct 3 version: r63
URL: https://editor.construct.net/
Date: Fri Oct 13 2017 22:22:37 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 788.8 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r63
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 580 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r64.
