### ISSUE TITLE
[r18.2] Event sheet parameters cannot undo/redo

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#93]
## Problem description

in C2 you can undo/redo the parameter text box but in C3 you can't.

## Expected result

Able to undo/redo in the event sheet parameters.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Which parameter text box are you talking about exactly? Please try to be comprehensive in every report.

**Comment by jaydonteh** [comment]
All event triggers and action parameters that can edit texts are involved. Hence, parameter box.

**Comment by AshleyScirra** [comment]
This looks tricky. I think applying the syntax highlighting clears the browser's undo stack. We'll probably have to invent our own undo stack for expression inputs to fix this.

**Comment by AshleyScirra** [comment]
@shortercode do you want to take this as something for your backburner since you've done a bit of work on the expressions code recently and it seems to have come up a couple of times lately?

**Comment by AshleyScirra** [comment]
Turning this over to @shortercode for the time being

**Comment by shortercode** [comment]
I've implemented a separate undo stack and integrated it with the expression control. It seems to behave the same as the browser undo stack in most areas. The only notable difference being the browser undo will switch focus to a previous input box if you undo past the end of the current input box's stack. Whereas this treats each input as  completely separate. It is likely possible to also match this if we consider it important.

I don't think it should have any issues with IME composition, although I have no method for testing this at the time being. One thing I do wonder is though is if we have the correct keybindings for undo/redo in all locales.

Going to assign this back to @AshleyScirra to review the changes and decide if the change is ready for release.

**Comment by AshleyScirra** [comment]
I'm happy with this so closing.
