### ISSUE TITLE
Auto backup is doing it every minute instead of every 60 minutes

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#930]
## Problem description

Auto backup setting seems to save every 60 seconds when I said 60 minutes, it won't let me do a value higher than 60 either.

## Attach a .c3p

Unrelated to c3p, open any file and have settings like this:

![image](https://user-images.githubusercontent.com/5744908/31571295-6f05a12e-b0db-11e7-9a35-72fd0e467213.png)

## Steps to reproduce

1. Enable backup
2. Put interval at 60 (minutes)
3. Fiddle around with the project for a few minutes watching it autosave

## Observed result

Every 1 minute it autosaves to google drive 

## Expected result

Saving every hour, or 60 minutes.

**Comment by shortercode** [comment]
@alastajj what revision was this on?

**Comment by alastajj** [comment]
@shortercode happens to me on r63

**Comment by shortercode** [comment]
Okay thanks, thought it might have been related to an older bug that I fixed. I found something in the timer code that was stopping it from updating it's settings ( so it was starting with the default value of 1 minute and ignore the initial settings value / subsequent settings changes ).

Should be fixed in r64.

**Comment by alastajj** [comment]
@shortercode oh great thank you! I was still trying to figure out how to replicate it easily.

**Comment by shortercode** [comment]
It's a real pain to test, because of having to wait for it! Also it won't trigger unless your active project has been saved at least once, and have unsaved changes.
