### ISSUE TITLE
Origin points change position incorrectly after cropping entire animation, but only with the frames you didn't look at

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#932]
## Problem description

In the image editor, the origin points change position incorrectly after cropping an entire animation, but only if you don't go through and individually select each frame, to look at them, before closing editor.

This also affects image points, make sure they behave the same as origin points!

I thought we'd fixed this bug before, don't know why it's happening again! #749

## Attach a .c3p

[OriginBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1384447/OriginBug.zip)

## Steps to reproduce

1. Shift + Crop entire animation
2. Close editor immediately
3. Preview the game

## Observed result

Notice how the animation is wiggling, only frame 0 has the correct origin point

## Expected result

Since all the animation frames are identical, and before the crop had the same origin point coordinate, the animation should not move at all but it's shifting weirdly!

**Comment by DiegoScirra** [comment]
A similar bug was reported, and while fixing that one, I re-introduced this one. Now both should be working properly as of r66.
