### ISSUE TITLE
Missing non-world object instances after deleting loader layout from project

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#936]
## Problem description

I went through the entire project file to figure out what was the issue. Initially, what caught my attention was all my events does not work with my arrays and it seemed off to me. Checked the arrays from the debugger preview and got a cold sweat that all instances of my arrays and dictionary objects are missing. The debugger indicates "helloArray (0)" which displays no instances. I didn't know what I did initially that causes this. None of my actions asks to delete those instances.

Thanks to MekaSkull from the Discord we manage to sort the problem out. I remembered I deleted my loader layout and changed to a different layout. Apparently, when you delete the loader layout, C3 forgot to re-initiate those non-world objects in another layout and causing the game to not have the arrays nor the dictionaries. The objects are there but no initiations. Thankfully, I regularly backup my progress once every few iterations, I get to compare the .c3p files and found that the arrays and dicts initiations are missing in the layouts json files. What I did was copy pasted the initiations from the deleted loader layout and paste it in one of the other layout json file that was missing the initiations.

This is a project breaking bug and should be addressed quickly.

## Steps to reproduce

1. Create a new project.
2. Add an array object.
3. Add a new layout.
4. Delete the initial layout called "layout 1".
5. Debug preview to see the missing array instance.

## Observed result

The added array object does not have an instance and thus do not work even if it was declared to have that object in the project.

## Expected result

C3 add the initiations of the non-world objects to another layout.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r63
Language setting: en-US

Local storage
Storage quota (approx): 7.2 gb
Storage usage (approx): 1.9 gb (27.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 765M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, this is a good catch. It should be fixed in r64 which will be out shortly.
