### ISSUE TITLE
[r18.2] Middle-click move gizmo enabled in preview bug

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#94]
## Problem description

Supposedly middle clicks should not trigger the move gizmo cursor during preview.

## Steps to reproduce

1. Create a new project.
2. Preview.
3. Middle-click.

## Observed result

Cursor activated moving mode, changing it's appearance to the move gizmo cursor. This caused trigger events for all clicks to not register when the cursor is in the move gizmo.

## Expected result

Do nothing.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Should be fixed in r20.
