### ISSUE TITLE
Crash when creating and immediately deleting an image point

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#940]
## Problem description

Creating then deleting an image point causes Construct to crash.

## Attach a .c3p

Bug can be reproduced in any project with a sprite.

## Steps to reproduce

1. Open a sprite in the sprite editor.
2. Click to add a new image point.
3. Click the trash can button to delete the image point.

## Observed result

Construct crashes.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r63/main.js, line 2, col 179758
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Function.ǃG.ǃq (https://editor.construct.net/r63/main.js:2:179764) at Function.ǃG.ǃTJ (https://editor.construct.net/r63/main.js:2:179833) at e.ǃOVD.ǃOVb (https://editor.construct.net/r63/main.js:73:141728) at Array.ǃoq.addEventListener (https://editor.construct.net/r63/main.js:73:137656) at ǃG.Event.ǃRfg.ǃRfl (https://editor.construct.net/r63/main.js:2:264761) at ǃG.ǃR.ǃyn.dispatchEvent (https://editor.construct.net/r63/main.js:2:263048) at ǃG.ǃR.ǃNQ.ǃGZu.ǃRRN.ǃGKg (https://editor.construct.net/r63/main.js:2:528182) at ǃG.ǃR.ǃNQ.ǃGZu.ǃRRN.ǃGUd (https://editor.construct.net/r63/main.js:2:526815) at HTMLElement.click.a.ǃJE (https://editor.construct.net/r63/main.js:2:524593) at HTMLDocument. (https://editor.construct.net/r63/main.js:2:259817)
Construct 3 version: r63
URL: https://editor.construct.net/index.html
Date: Mon Oct 16 2017 22:25:11 GMT-0700 (Pacific Daylight Time)
Uptime: 26.3 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r63
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by Scoremonger** [comment]
This only happens when you create and then immediately delete the image point. If you create the new point, select the origin point, then re-select and delete the new point, there's no crash.

**Comment by tunepunk** [comment]
I noticed something weird with this as well. I didn't get a crash, but creating an image point then trying to delete it directly after, nothing happened. I could click the trashcan button several times but nothing would happen. Maybe after a while it would delete.

**Comment by DiegoScirra** [comment]
Fixed as of r66.
