### ISSUE TITLE
Platform small jump after leaping from angled edges

### ISSUE THREAD

**Issue by flipog** [Scirra/Construct-3-bugs#941]
## Problem description

This is very tricky so it's probably my fault, but when the Hero sprite leaps from an angled ledge it jumps a little. This behavior can also be observed when changing layouts (going down mainly, going up seems ok)

## Attach a .c3p

https://github.com/flipog/games/blob/master/Travel.c3p

## Steps to reproduce

1. Start the game in layout "Lx0500y0500"
2. Walk down angled ledges
3. The Hero sprite will jump a little
4. It can also be observed when crossing layouts (going down)

## Observed result

A little jump after leaping from angled edges or crossing layouts (going down)

## Expected result

I don't think it should make such a jump.

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: untested

## System details

Not a crash situation

**Comment by flipog** [comment]
I was wrong, this is not a bug and should be closed. The character will go fully sideways after stepping out of an inclined ledge making it only look like it gained a little momentum.

**Comment by AshleyScirra** [comment]
I can't see anything wrong moving up and down the slope, and as you seem to agree there's no bug, closing.
