### ISSUE TITLE
[edge] Missing UI elements

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#944]
## Problem description

Missing UI elements in Edge. Icons. (All themes).

## Attach a .c3p

Attaching screenshot instead.
https://www.dropbox.com/s/kxs4h3dpxuqc7xa/edge_bug1.JPG?dl=0

## Steps to reproduce

1. Open C3 in edge.
2. Observe icons missing.

## Observed result

Icons were missing.

## Expected result

Should not be missing.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: yes

**Comment by AshleyScirra** [comment]
Looks fine here in Edge 16.16299.

**Comment by tunepunk** [comment]
Try with higher zoom level. 100% looks ok here. But i use high dpi screen so zoom is usually at 200%

**Comment by AshleyScirra** [comment]
I tried on a laptop with a devicePixelRatio of 2.5 (250% zoom), and also tried zooming in to 300%. It looks fine. Can you post your system information from the Platform Information dialog?

**Comment by tunepunk** [comment]
Very weird. I will provide the info as soon I'm back on that device. It was not only the UI icons. All icons, sprite miniatures in project window didn't show up either.

**Comment by tunepunk** [comment]
Rolled back Creators update on my main machine, and installed it on my old Surface. No issues there. Must have been something with my device. You can close the issue until I decide to install creators update again. If the issue is still there I will file a new bug.

**Comment by AshleyScirra** [comment]
OK. I've not seen any other mentions of this particular issue, so it does sound like a weird system-specific thing.
