### ISSUE TITLE
[edge] Can't connect to dropbox.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#945]
## Problem description

After logging in to dropbox nothing happens. Login popup doesn't close and nothing happens. It seems to be the case for one drive as well, where I can't even log in.

## Attach a .c3p

N/A

## Steps to reproduce

1. Start C3 in edge and try to open a project from dropbox.
2. After login, nothing happens.

## Observed result

Get stuck on authetication.

## Expected result

Expected to be logged in and able to see files.

## Affected browsers

* Edge: yes
* UC Browser UWP: yes

**Comment by shortercode** [comment]
Okay finally got the new version of edge on my system. Issue was caused by an edge bug related to popup windows, I've found a workaround so this should work in the next release.
