### ISSUE TITLE
Event sheet column sizes collapse to smallest possible size, if the tab was not opened before saving

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#946]
## Problem description

If you open a project that has multiple event sheets tabs open, make some changes in 1 of the sheets, but don't open and look at the 2nd event sheet tab in a session, the 2nd event sheet will have all of it's event columns resized to a very small size.

This bug is unrelated to any theme choice.

## Attach a .c3p

[eventsheet.zip](https://github.com/Scirra/Construct-3-bugs/files/1393600/eventsheet.zip)

## Steps to reproduce

1. Open the project that has 2 event sheet tabs
2. Click on Event sheet 1
3. Do **NOT** click on Sheet 2
3. Press B to make a blank event in Sheet 1
4. Save 
5. Close project
6. Open project
7. Click on Event sheet 2

## Observed result

Notice how the event columns have all collapsed to the smallest possible size?

![image](https://user-images.githubusercontent.com/5744908/31703363-fa66cbb8-b427-11e7-878f-ff9aa411e2ef.png)

## Expected result

The columns should not change size just because I did not open the sheet this session! I don't want them to change from this size I chose!

![image](https://user-images.githubusercontent.com/5744908/31703411-2ccf20e6-b428-11e7-9af9-b325940e4b44.png)

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r65.
