### ISSUE TITLE
Pen input broken in ALL browsers.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#949]
## Problem description

The way browsers handles pointer events these days is getting very annoying especially when working with a pen as main input. Old behaviour was that if you used a pen, it would simulate mouse input. Now that they added (broken) support for pen, in pointer events it's not really working well or at all in most browsers. I found this article on pointer events and wondering if C3 could override the pen pointer events using this code to simulate mouse instead of touch behaviour.

I really want to use C3 with my pen as main input but it's currently broken in all browsers.

This article (Step 3) highlights how to add fallback code for pointer events. 
https://www.davrous.com/2015/08/10/unifying-touch-and-mouse-how-pointer-events-will-make-cross-browsers-touch-support-easy/

If it's not too much hassle could you convert pen input to mouse until most browsers get a fix for it? 

I know this is not a C3 bug, but rather poor implementation of pointer events especially working with a pen in modern browsers.

Touch is fine at the moment, working as expected, but pen input is broken, and has been for a long time, and don't know when or if it will be fixed in the various browsers. Pen input broke in Edge for fall creators update but was working fine prior.

## Attach a .c3p

N/A

## Steps to reproduce

1. Using a pen in C3 in any browser
2. Notice strange behaviour related to how pointer events are handled.

## Observed result

Pen input is broken in most browsers and not behaving as expected or att all. Functions that usually doesn't work with pen. 

While using a pen:
* Double click to select text. (Should be same as a mouse double click)
* Double click to open dialogs (Should be same a mouse double ckick)
* Click and drag to mark text (Does not work)

If the pen has a button for right clicking this is the only thing that works as expected as it simulates a mouse right click.

## Expected result

Should work similar to how mouse works when selecting and editing text.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Opera: yes
* Vivaldi: yes

**Comment by AshleyScirra** [comment]
If this is not specific to C3, please file bugs with the browsers themselves.

**Comment by tunepunk** [comment]
Just got the latest stable Chrome build, and It's already working a lot better in Chrome. Not optimal, but a LOT better. I can work with this for now. Let's hope Edge fixes what they broke in the creators update.

**Comment by AshleyScirra** [comment]
This landed in Chrome 62 which was just released and looks like it might've helped: https://bugs.chromium.org/p/chromium/issues/detail?id=746581

**Comment by tunepunk** [comment]
Yep, finally. One step closer to having to be an awesome tool, on hybrid tablets. I had to roll back my windows becase Fall creators update was giving me a lot of headaches with edge. I mainy use edge for everything else only because how well it handled stylus. Seems crome is catching up. But hoping MS will get the s**t together, and stop breaking things that works perfectly fine.
