### ISSUE TITLE
[r18.2] Re-preview after change URL crash

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#95]
## Problem description

Preview after changing the URL of the preview by using the browser object's "Go to URL" action will cause a crash.

## Steps to reproduce

1. Try changing the URL using the browser object in preview.
2. Click the preview button again.

## Observed result

Crashed.

## Expected result

No crash.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: SecurityError: Blocked a frame with origin "https://editor.construct.net" from accessing a cross-origin frame.
Stack: Error: Blocked a frame with origin "https://editor.construct.net" from accessing a cross-origin frame. at window.ǃEdN.ǃEdw (https://editor.construct.net/r18-2/exporters/preview/exporter.js:1:1575) at window.ǃEgr.ǃEgY (https://editor.construct.net/r18-2/exporters/preview/exporter.js:1:20747) at ǃs.ǃPw.ǃEge.ǃEbp (https://editor.construct.net/r18-2/exporters/preview/exporter.js:1:24240) at ǃdEC.ǃs.ǃPR.ǃIp.then.then.then.then (https://editor.construct.net/r18-2/main.js:63:9856)
Construct 3 version: r18.2
URL: https://editor.construct.net/index.html
Date: Tue Apr 18 2017 01:23:27 GMT+0800 (Malay Peninsula Standard Time)
Uptime: 2818.1 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.1458333730697632
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I could only reproduce this in dialog preview mode. In popup window mode it also appears to unintentionally close the preview window. I've worked around this in r20 by making 'go to URL' always open a new window in preview mode.
