### ISSUE TITLE
Tilemaps opacity

### ISSUE THREAD

**Issue by flipog** [Scirra/Construct-3-bugs#950]
## Problem description

* Tilemaps' opacity cannot be changed while tilemap editing.
* Tilemaps will be forced back to 100% opacity at the tilemap's editor.
* Tilemaps don't display their correct opacity at the editor, but will display correctly in-game.

## Attach a .c3p

Any tilemapped file should display this issue.

## Steps to reproduce

1. Open a file containing tilemaps.
1. Try to edit its opacity.
1. Tilemaps editor opened: the opacity should back to 100%.
1. Tilemaps editor closed: the opacity resists until you try to edit the tilemap again.
1. Tilemaps should not display their correct opacity in the editor if opacity changed outside tilemaps editor.

## Observed result

The tilemaps opacity not being manageable.

## Expected result

The new opacity should persist

## Affected browsers

* Chrome: yes
* Firefox: untested
* Edge: untested
* Safari: untested

## System details

Doesn't crash.

**Comment by DiegoScirra** [comment]
Fixed in r66
