### ISSUE TITLE
Crash when renaming Image Points

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#951]
## Problem description

When trying to Rename an Image Point in the Animation Editor by clicking on the Pencil Icon, Construct 3 crashes unexpectedly.

## Steps to reproduce

1. Open new Project
2. Create new Sprite
3. Open Sprite in Animation Editor
4. Open Origin/Image Point Tab
5. Create new Image Point
6. Select Image Point and Click on the Rename Button

## Observed result

Crash.

## Expected result

C3 to send me Flowers and Chocolate and maybe also going on a Date with me.. and not crashing ;)

## Affected browsers

* Chrome: yes

## System details

Error report information
Type: unhandled exception File: https://editor.construct.net/r64/main.js, line 2, col 179732 Message: Uncaught TypeError: unexpected type Stack: TypeError: unexpected type at Function.ǃO.ǃOk (https://editor.construct.net/r64/main.js:2:179738) at Function.ǃO.ǃBM (https://editor.construct.net/r64/main.js:2:179807) at e.ǃeSm.ǃeSD (https://editor.construct.net/r64/main.js:73:141626) at Array.ǃgD.addEventListener (https://editor.construct.net/r64/main.js:73:137701) at ǃO.Event.ǃBNk.ǃBNq (https://editor.construct.net/r64/main.js:2:264867) at ǃO.ǃs.ǃXw.dispatchEvent (https://editor.construct.net/r64/main.js:2:263153) at ǃO.ǃs.ǃt.ǃOVG.ǃxX.ǃOlk (https://editor.construct.net/r64/main.js:2:528589) at ǃO.ǃs.ǃt.ǃOVG.ǃxX.ǃOlB (https://editor.construct.net/r64/main.js:2:527217) at HTMLElement.click.d.ǃBqt (https://editor.construct.net/r64/main.js:2:524986) at HTMLDocument.(https://editor.construct.net/r64/main.js:2:259918) Construct 3 version: r64 URL: https://editor.construct.net/ Date: Thu Oct 19 2017 09:43:56 GMT+0200 (CEST) Uptime: 14.9 s
Platform information
Browser: Chrome Browser version: 61.0.3163.100 Browser engine: Blink Browser architecture: (unknown) Context: browser Operating system: Mac OS X Operating system version: 10.12_3 Operating system architecture: (unknown) Device type: desktop Device pixel ratio: 2 Logical CPU cores: 8 Approx. device memory: (unavailable) User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 C3 release: r64 Language setting: en-US
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium) Numeric version: 2 Supports NPOT textures: yes Supports GPU profiling: yes Vendor: ATI Technologies Inc. Renderer: AMD Radeon R9 M395X OpenGL Engine Major performance caveat: no Maximum texture size: 16384 Point size range: 1 to 2048 Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
This is Diego's code but he's currently on vacation. I've hacked in a workaround for the next build to stop it crashing, but it doesn't properly fix the problem (the buttons will do nothing, instead of crashing). I'll leave this bug open and assigned to Diego for him to review when he gets back.

**Comment by DiegoScirra** [comment]
This is working correctly as of r66.
