### ISSUE TITLE
Conditions based on local variables dont run after changing the variables value

### ISSUE THREAD

**Issue by newman321** [Scirra/Construct-3-bugs#953]
## Problem description

if a condition is based on local variables, changing the value of the local variable does not activates that condition.

## Attach a .c3p

[TestProject.zip](https://github.com/Scirra/Construct-3-bugs/files/1400945/TestProject.zip)

## Steps to reproduce

1.Create a group.

2.make a local variable inside of the group with initial value of 0 or something other than conditions first value check.

3.make a condition with comparing value of the variable lets say comparing if its 1 or not and do something like reducing opacity of an object.

4.change value of the variable while running the project to 1.

5.reducing opacity event wont work.

6. tried this with boolean and number local variables.

## Expected result

the event based on variable value check to run

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.62
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
C3 release: r64
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 19 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 330M OpenGL Engine
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2047
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_disjoint_timer_query
EXT_frag_depth
EXT_shader_texture_lod
EXT_sRGB
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Local variables reset every tick. You probably meant to make it a static local variable.

**Comment by newman321** [comment]
Then it should run at least once, when toggle becomes one and until next tick
![screenshot 2017-10-20 14 54 50](https://user-images.githubusercontent.com/426713/31818847-b5380950-b5a6-11e7-9224-083a819577e4.png)

**Comment by AshleyScirra** [comment]
It won't, because triggers fire outside of the normal top-to-bottom evaluation of events.
