### ISSUE TITLE
Preview in Visual Studio shows runtime error about property 'hasCurrentMatMV'

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#955]
## Problem description

I exported my game for UWP, added Nuget packages for Xbox Live plugin, assigned it to store entry and hit preview for x64. After a short time the game window appears with the placeholder loading image and Visual Studio shows this error message:

> "WWAHost.exe" (Skript): "Skriptcode (MSAppHost/3.0)" geladen. 
> Es wurde eine Ausnahme ausgelöst: in Zeile 35127, Spalte 5 in ms-appx://58213bl4cksh33p-soft.seafrenzy/c2runtime.js
> 0x803f6107 - JavaScript runtime error: Unknown runtime error
> Ausnahmefehler in Zeile 3004, Spalte 4 in ms-appx://58213bl4cksh33p-soft.seafrenzy/c2runtime.js
> 0x800a138f - JavaScript runtime error: **Unable to set property 'hasCurrentMatMV' of undefined or null reference**
> 
> Das Programm "[8784] WWAHost.exe" wurde mit Code 3 (0x3) beendet.

Last thing I added was Roaming values for Windows Store to test it in Visual Studio (don't know if it works if not published in store or if they work on Xbox). And Xbox Live Sign in and Leaderboards.

## Attach a .c3p

I tried to reproduce it and preview a new, blank project with Xbox Live and Windows Store plugin but it did not show the error. **I dont know what "hasCurrentMatMV" stands for and what it does relate to so its hard to narrow down the issue to post a example which is not my complete game.**

Should I post the entire game? Its 1 event sheet with 244 lines.

## Steps to reproduce

1. Export for UWP (includes Plugins for: Xbox Live, Windows Store, Touch, Mouse, Browser, ScirraArcade, Audio, Button, Sprites, Text, Gamepad, Function, Keyboard, LocalStorage, TextBox)
2. Add Nuget packages for Xbox Live
3. Assign app to store entry
4. Select Debug Preview x64

## Observed result

Error message shown and preview stopped

## Affected browsers

Win10 UWP (Edge)

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r64
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 1.5 gb (2.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think this means a script failed to load, so the real problem occurred before that error message. I can see there is an error before that one in the log, but it looks like it's just "Unknown runtime error". There is almost nothing I can do without an example though.

**Comment by TheBl4ckSh33p** [comment]
Hi. I exported the whole game (1 sheet, about 240 lines) because I have no idea what could cause it yet. But if you have any  hints I can remove big parts of the code to make a smaller example and I will contine to make some exports with part of the code to see if I can reproduce it.

[SeaFrenzy_BugExample.zip](https://github.com/Scirra/Construct-3-bugs/files/1403897/SeaFrenzy_BugExample.zip)

**Comment by AshleyScirra** [comment]
It turns out it's a bug in Edge failing to compile the Overlay WebGL shader effect. I filed a report here: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14342519/

I've worked around it for the next build, and also improved the robustness of the error checking so it reports the error right away - the error message you saw was a later consequence of the shader having failed to compile, so ended up being misleading.
