### ISSUE TITLE
Problem running demo

### ISSUE THREAD

**Issue by David18148** [Scirra/Construct-3-bugs#957]
## Problem description
Being new to C3 I tried the demo Kiwi Story. The project loaded OK but when I tried to run it errored as follows
*Enter a concise description of your problem here*
## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.Load Kiwi Story
2.Click preview
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/
* Firefox: no
* Edge: yes
* Safari: Don't use

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Hello
I have just  loaded KiwiStory but when I tried to execute it I received the following error:-
 
Error report information
Type: unhandled exception
File: https://editor.construct.net/r64/exporters/preview/exporter.js, line 1, col 903
Message: Not implemented 
Stack: Error: Not implemented at Global code (https://editor.construct.net/r64/exporters/preview/exporter.js:1:903)
Construct 3 version: r64
URL: https://editor.construct.net/
Date: Fri Oct 20 2017 13:45:17 GMT+0100 (GMT Summer Time)
Uptime: 87.8 s 
Platform information
Browser: Edge
Browser version: 16.16299
Browser engine: Edge
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8500000238418579
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
C3 release: r64
Language setting: en-US 
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Microsoft
Renderer: Intel(R) HD Graphics 4600
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 14
Extensions: WEBGL_compressed_texture_s3tc, OES_texture_float, OES_texture_float_linear, EXT_texture_filter_anisotropic, OES_standard_derivatives, ANGLE_instanced_arrays, OES_element_index_uint, WEBGL_debug_renderer_info, WEBGL_depth_texture, EXT_frag_depth, OES_texture_half_float, OES_texture_half_float_linear
</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here, works fine for me in Edge 16 and Chrome 62.

The error message is weird: it points at a line where it creates an Audio object, and the error is "Not implemented". This has been supported in all major browsers for years. Are you using any browser addons? Does disabling them fix it?

**Comment by David18148** [comment]
Hello Ashley

This is weird. Over the weekend I tried all of my browsers and got varying results.

 

Edge 16 The same error as before. (No addons enabled). I then went to caniuse.com It said it supports WebGL but it accesses it through experimental-webgl

 

Chrome 62 fails on loading construct3 with Error loading! Try disabling browser addons Unhandled promise rejection: [object Event] No addons enabled.

 

Firefox 56 Works fine

 

Opera 48 Works fine

 

Safari 5 Construct 3 does not support Needs ES2015, CSS Gridlayout, CSS Flex Box, CSS variables, Promises, WebGL and WebAssembly

 

So I would assume that Edge and Chrome need settings amending on my machine. My browser of choice is Chrome. Are there any settings needed other than the bog standard needed in order to run C3? I did notice that Chrome seems to only use WebGL 2 as there is no WebGL 1.0 in chrome://flags. Hope this helps.

 

Regards

 

Dave

**Comment by AshleyScirra** [comment]
So, it's specific to Edge only then?

Do you have the "N" edition of Windows that comes without any media features? Perhaps if you have that then Edge disables audio features...

**Comment by David18148** [comment]
I do run win 10 pro n but have updated to 1709 and there is no media feature pack available yet and the latest media pack will not install. Edge also refuses to recognise Flash.

**Comment by AshleyScirra** [comment]
Okay, I thought you might have the N edition. I guess in this case no media related features will work in Edge. There's not much we can do about that - it'll break any web page using media, and in C3's case we can't even work out what type of audio files to use in preview mode, hence the crash. This is a weird edge case, I think your workaround just has to be to install the media feature pack.

**Comment by David18148** [comment]
Ashley

Microsoft released today a media pack for Win 10 N 1709. I’ve installed it and Edge works ok for the demos. However Chrome refuses to even load C3

 

Dave

**Comment by AshleyScirra** [comment]
I'm afraid I can't help without more information.

**Comment by David18148** [comment]
When I try to load using Chrome after the Load Construct 3 button I get an error message (see attachment) The second attachment is the extensions screen from chrome. The third is windows about screen

**Comment by AshleyScirra** [comment]
I can't see the attachments on github. Please file a new issue on github and attach the images there.

**Comment by David18148** [comment]
Sorry I have been using Outlook not GitHub.
![2017-10-25_09-30-35](https://user-images.githubusercontent.com/32977439/31993609-9ec7f644-b975-11e7-992d-1d556dcf06c0.png)
![2017-10-25_09-41-04](https://user-images.githubusercontent.com/32977439/31993610-9ee7f750-b975-11e7-9fbf-9ceb9447e7dd.png)
![2017-10-25_09-35-31](https://user-images.githubusercontent.com/32977439/31993611-9f0605d8-b975-11e7-8654-c0f65309224e.png)

**Comment by AshleyScirra** [comment]
We need all the information requested in a new bug report to be able to do anything. Please file a new issue following all the guidelines or we won't be able to investigate.
