### ISSUE TITLE
No Paste option in right click dialogue.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#96]
## Problem description

There's no option to paste in the right click dialogue in Event Sheet & Layout view

## Attach a .c3p

N/A

## Steps to reproduce

1. Start New project and create a new sprite.
2. Create a random Condition+Action in the Event sheet.
3. Right click to to open dialogue to copy event or action.
4. Right click to paste event or action. (Does not exist)

## Observed result

*There is no option to paste from right click menu.*

## Expected result

*Expected paste option in right click menu.*

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
JavaScript does not provide an option for web content to cause a paste - you can only use the browser shortcut or the browser menu option. There's no workaround (in the browser) this until a corresponding feature is added to the browser. It will be supported in the desktop builds though.

**Comment by tunepunk** [comment]
There is no workaround? I'm working with C2 and C3 completely without keyboard, on a tablet. (Except for the on screen keyboard on my Surface Pro 4) That pretty much rules out using C3 on the go without bringing a bluetooth keyboard and mouse. This work well in Edge, using OneNote etc. Will this functionality work in standalone version?

**Comment by tunepunk** [comment]
Also. If you go to google docs, and create a new document. Copy and paste from right click works perfectly there. why not in other web-apps?

**Comment by AshleyScirra** [comment]
Huh, I have no idea how Google Docs does it - I've looked around for a while and never found any pure JS solution. I suppose they're using an extension? There's a Google Docs extension that appears to ship with Chrome, I guess they're "cheating" with that...

It's also possible we could implement a fake clipboard by just storing data locally... maybe we should do that instead.

**Comment by tunepunk** [comment]
They do it with a chrome extension. Another web-app also uses this approach. Here's some more info about it.
https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/ 

They have a link to their extension in the Popup dialogue when you try to copy. 
I just tried it and it worked perfectly. Link at the bottom of the page linked you can try this web-app and download the extension to try.
