### ISSUE TITLE
Crash when hitting ESC while renaming cloud project

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#960]
## Problem description

I rightclicked a file in the cloud > open project window and hit ESC to cancel. got a crash. (Google Cloud)

## Attach a .c3p

not related to project

## Steps to reproduce

1. click cloud open
2. rightclick file
3. select rename
4. hit ESC to cancel

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected string @ TypeError: expected string at Function.ǃO.ǃOT (https://editor.construct.net/r64/main.js:2:177850) at t (https://editor.construct.net/r64/main.js:154:168372) at i.ǃZj.then.then (https://editor.construct.net/r64/main.js:154:176922) at 
Stack: TypeError: expected string at Function.ǃO.ǃOT (https://editor.construct.net/r64/main.js:2:177850) at t (https://editor.construct.net/r64/main.js:154:168372) at i.ǃZj.then.then (https://editor.construct.net/r64/main.js:154:176922) at 
Construct 3 version: r64
URL: https://editor.construct.net/index.html
Date: Sun Oct 22 2017 07:59:05 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 32.6 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r64
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Thanks, I've found and fixed it. Will be patched in r65
