### ISSUE TITLE
Minor: Debug preview shows 60% FPS

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#961]
## Problem description

Inspector window at bottom shows "60% FPS" next to the % GPU and CPU usage. I think the % should not be after the frame number. :)

## Attach a .c3p

not project related

## Steps to reproduce

1. hit debug preview

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Well spotted, fixed in next build!
