### ISSUE TITLE
Sprite Editor screen is unusable in Chrome latest version

### ISSUE THREAD

**Issue by locohost** [Scirra/Construct-3-bugs#963]
## Problem description

*I'm using Chrome Version 61.0.3163.100 (Official Build) (64-bit). The Sprite Editor screen is completely garbled and just barely usable as is*

## Attach a .c3p

*C3 project file is attached*

## Steps to reproduce

1. Use Chrome Version 61.0.3163.100 (Official Build) (64-bit)
2. Right click on purple sprite square
3. Select "Edit" in the context menu
4. Look at the garbled UI

## Observed result

*A completely messed up Sprite Editor UI screen. It's very barely functional*

## Expected result

*A correctly formatted and usable Sprite Editor UI screen.*

## Affected browsers

* Chrome: yes
* Firefox: don't have
* Edge: don't have
* Safari: don't have

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

No crash screen, however UI freezes completely when I try to "go back" because there is no menu or button visible that I can use to close/go back.

Platform info...

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: mobile
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r64
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 38 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4600 Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

[pic-quiz-puzzle-game.zip](https://github.com/Scirra/Construct-3-bugs/files/1407155/pic-quiz-puzzle-game.zip)
![construct 3 sprite editor ui is messed up](https://user-images.githubusercontent.com/132458/31890312-a8012f38-b7d0-11e7-99d8-d6009e6bf29f.PNG)

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce here, it looks correct in Chrome 62. The screenshot also looks like a browser compositor bug, or a GPU driver bug. I'd suggest checking for any system updates, a graphics driver update, and updating Chrome to 62 (which is now on stable channel - go to Help -> About to update). Another workaround could be to simply switch to Firefox for the time being.

**Comment by locohost** [comment]
Updated AMD Radeon graphics drivers. Updated Chrome to 62.something, latest Chrome. Sprite Editor UI is still not rendering correctly. I did download and install latest Firefox and C3, smoke test, looks much different and correct. It seems as I type, C3 doesn't work in Chrome 61 or 62. Which is fine for now. At least it works in FF.
