### ISSUE TITLE
Missing images for  UWP Xbox One Export

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#964]
## Problem description

I published my first creators program game and noticed some images are missing and just grey blocks. 
Missing images I noticed so far are:
- **image in store listing on Xbox (Creators collection) is smaller than usual. most games have a tall image**
- gamehub is missing small Icon in upper left corner (in gamehub subpages)
- game added to new home screen has no image
- Pins on mobile xbox app dont show icon for the game

## Attach a .c3p

not project related

## Steps to reproduce

1. export game for UWP / Xbox One

## Observed result

missing placeholder images

## Expected result

would be great to have all images in project export

## Affected browsers

none

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
We only provide the minimum images for a successful build. It's expected that you will open package.appxmanifest in Visual Studio and update the images there, which also lists all the possible images you can add and change (of which there are quite a few). I don't see much point in adding empty placeholder images if they don't affect the build, you should review all these images before publishing anyway, so naturally you'd add in any more important ones.
