### ISSUE TITLE
Tilemap Problem in C3

### ISSUE THREAD

**Issue by Contadojuan** [Scirra/Construct-3-bugs#965]
[RetroNinjaV3.5.zip](https://github.com/Scirra/Construct-3-bugs/files/1408824/RetroNinjaV3.5.zip)
## Problem description

I cant use any tilemap, even the default one
## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.Create a Tilemap
2.Try to use it
3.The tilemap window is blank

## Observed result
Blank window, cant use tilemap

## Expected result
Use tilemap lol

## Affected browsers

* Chrome: yes

<details><summary>View details</summary>

Reddit post with screenshot: https://www.reddit.com/r/construct/comments/78aw45/problem_with_c3_tilemap_description_inside/

</details>

**Comment by shortercode** [comment]
Seems to work fine for me, on your screenshot you haven't selected a tilemap instance in your layout. Unless a tilemap instance is selected you can't edit it.

Try this for me:
1. Open new project
2. Double click on the new layout
3. Select tilemap from the menu
4. Place tilemap anywhere on the layout
5. The tilemap image editor will open with the default tilemap, close it
6. When you've returned to the layout editor the tilemap instance should be selected
7. Tilemap bar should show the default tilemap image and the tab name will be Tilemap: Tilemap UID 1

If any of this goes wrong let me know with which step.

**Comment by Contadojuan** [comment]
Well, i dont know what happened but after reebot the pc and try again few hours later it worked yay
Thx 👍

**Comment by shortercode** [comment]
No worries, computers can be fickle things... 😄
