### ISSUE TITLE
The selection box in the layout editor does not fit to the object

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#966]
## Problem description

The selection box that wraps around the sprite is not perfectly mapped to the object you select.

Seen below is a sprite, and on the right is the sprite after it has been selected.
![image](https://user-images.githubusercontent.com/5744908/31929169-a1816ed6-b8e6-11e7-83b7-126febae4f5c.png)
A zoomed in version of this is posted at the bottom of this post.

## Attach a .c3p

[selectionbox.zip](https://github.com/Scirra/Construct-3-bugs/files/1409853/selectionbox.zip)

## Steps to reproduce

1. Click on the sprite

## Observed result

The selection is offset and 1 pixel larger in each dimension compared to the sprite.

## Expected result

The selection is odd, it should either place the selection box around the object on every side, or completely within in the object at the edges of it.

It should be consistent.

![image](https://user-images.githubusercontent.com/5744908/31929269-1c7c8fee-b8e7-11e7-933c-2eed7afdb197.png)

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: ?
* Safari: ?

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 62.0.3202.62
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
C3 release: r64
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 488 mb (3.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I've made an adjustment for r80 which looks like it sorts this out, but it's surprisingly difficult to get right - it depends on the device pixel ratio, browser zoom level, and even whether the layout view pane has an even or odd width/height. Let's check this when r80 is out and see if it's working better.

**Comment by AshleyScirra** [comment]
r80 is out now, can you check if it's working better?

**Comment by alastajj** [comment]
Seems like it is from my tests, thanks!

**Comment by AshleyScirra** [comment]
Thanks for confirming!
