### ISSUE TITLE
Crash when undoing several event editor changes

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#968]
## Problem description

I spammed undo to undo 5 or 6 event changes I'd made, and Construct crashed. Haven't been able to reproduce this.

Something weird and probably unrelated happened after the crash, too - after choosing to save the current project, letting C3 automatically restart, reloading the project and then trying to add a condition to an event, the Add condition dialog had the error report text in it (see screenshot). I closed and restarted C3 and this went away. I'm using the built-in C3 clipboard instead of the OS one, if that matters.

![crash knock-on bug](https://user-images.githubusercontent.com/28039905/31967496-ea8f797a-b8c2-11e7-9f0c-e4b4db7c6da8.png)

## Attach a .c3p

[UndoBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1412564/UndoBug.zip)

## Steps to reproduce

I can't repro, but the steps were something like this. I've attached a project but it's probably useless - hopefully the crash message sheds some light on this.

1. Create a sprite family with a Pin behavior ("PinnableFamily" in the attached project).
2. Create a second sprite family and give it an On created event ("ManagerFamily"), and give this family a string variable with the name of a PinnableFamily member.
3. Under On created, add a sub-event to create the pinnable object using the name of the string in the manager. Create a sub-event of that sub-event with an action to Pin the sprite to the manager.
4. Copy/paste this sub-event a few times so there are three at the same level of indention under the On created event.

(The steps above are a simpler version of the section of the project I loaded before seeing the bug.)

5. Add a boolean (i.e. "PinChildObjects") to the ManagerFamily.
6. Add a blank sub-event under first of the sub-events that pin the pinnable sprite to the manager.
7. Add a condition in this new sub-event checking for whether the bool is set.
8. Drag the Pin action down into the new sub-event.
9. Copy the new sub-event with the bool condition and pin action, and paste it under the remaining two higher-level sub-events.
10. Delete the Pin action from the other two higher-level sub events.
11. Spam ctrl-z.

## Observed result

Construct crashes.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r64/main.js, line 154, col 39998
Message: Uncaught TypeError: Cannot read property 'ǃODS' of null
Stack: TypeError: Cannot read property 'ǃODS' of null at ǃO.ǃs.ǃt.ǃuOG.ǃOu (https://editor.construct.net/r64/main.js:154:39998) at ǃOg.ǃtE.d.ǃtS [as ǃeVY] (https://editor.construct.net/r64/main.js:154:42874) at ǃOg.ǃtE.ǃBa (https://editor.construct.net/r64/main.js:73:37120) at ǃOg.ǃtE.ǃeVi (https://editor.construct.net/r64/main.js:73:47719) at window.ǃOyt.ǃXJ (https://editor.construct.net/r64/main.js:73:36072) at t.ǃXJ (https://editor.construct.net/r64/main.js:63:91576) at window.ǃutH.ǃXJ (https://editor.construct.net/r64/main.js:167:44085) at Array.ǃzy.ǃO.ǃz.ǃO.ǃzi.ǃzp (https://editor.construct.net/r64/main.js:167:15756) at ǃO.Event.ǃBNk.ǃBNV (https://editor.construct.net/r64/main.js:2:264684) at window.ǃutH.dispatchEvent (https://editor.construct.net/r64/main.js:2:263143)
Construct 3 version: r64
URL: https://editor.construct.net/index.html
Date: Tue Oct 24 2017 13:37:30 GMT-0700 (Pacific Daylight Time)
Uptime: 757.3 s

Platform information
Browser: Chrome
Browser version: 62.0.3202.62
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
C3 release: r64
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Based on the crash report I was able to reproduce the same error message via:

1. Reorder some instance variables in an object
2. Delete the object
3. Press undo twice

The crash comes from undoing the reordering after the instance variables dialog was closed. This should be fixed in r66.
