### ISSUE TITLE
No clone option in Project window.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#97]
## Problem description

Right clicking on an option in Project window doesn't have Clone option. This is a very useful option in C2.

## Attach a .c3p

N/A

## Steps to reproduce

1. Start a new project.
2. Create a new sprite.
3. Right click sprite in Project window. 
4. Clone option is not there, as it is in C2.

## Observed result

There's no clone option in right click menu in project window.

## Expected result

Expected clone option to be available, like in C2.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Added in r20.
