### ISSUE TITLE
IDE crash when drag&drop from Winrar to Animation Editor

### ISSUE THREAD

**Issue by NitidOnline** [Scirra/Construct-3-bugs#970]
## Problem description

IDE crash when dropping files into "Animation Frames" directly from a .zip or .rar file dragged form  Winrar 5.4.

I tried the same with a .zip file created with Windows Explorer and it works (ignorig the drop operation)

## Attach a .c3p

Any C3 example.

## Steps to reproduce

1. Create a .zip with png images
2. Open it with Winrar
3. Open the sprite editor
4. Drag and drop the images into Animation Frames
5. IDE crash

## Observed result

IDE crash.

## Expected result

Extract and add the images to the animation or nothing at all.

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.
Construct 3 version: r64
URL: https://editor.construct.net/index.html
Date: Wed Oct 25 2017 19:53:51 GMT+0200 (Hora de verano romance)
Uptime: 751.2 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 32-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r64
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2048
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_frag_depth, EXT_shader_texture_lod, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by DiegoScirra** [comment]
Fixed in r67.

The editor now shows a dialog giving a short explanation about the problem and won't crash.

It is not possible to drag and drop from Winrar into Chrome and manipulate the content of those files, it is not just a C3 issue. Other 3rd party applications might produce a similar result. The easiest work around is extracting the file to your desktop and then dropping it into C3.

Other browsers like Firefox and Edge don't event accept drops from Winrar.
