### ISSUE TITLE
Car hops thru thin barriers w/wo Bullet step

### ISSUE THREAD

**Issue by bobcgausa** [Scirra/Construct-3-bugs#973]
## Problem description

Car behavior w/wo Bullet behavior drives thru thin barriers

## Attach a .c3p

attached
PS: dragging a c3p doesn't work so changed suffix from c3p to zip
[Car.zip](https://github.com/Scirra/Construct-3-bugs/files/1419644/Car.zip)

## Steps to reproduce

1. try driving and turning right or left in pipe
2.
3.

## Observed result

car sometimes hops outside the pipe

## Expected result

Stay inside the lines.
I was trying to draw driving lanes without lining the course with blobs as in your

 example

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The bullet behavior has no effect on the car behavior. It sounds like you were expecting the bullet behavior properties to affect the car behavior, but they don't. The car is wider than the pipe so there is no room for it to rotate, so it kicks off a "escape from solid" routine which moves it to a space. You need to use a smaller car or bigger pipe.
