### ISSUE TITLE
Can't reorder actions of an event by dragging them in iOS

### ISSUE THREAD

**Issue by TinyMartian** [Scirra/Construct-3-bugs#974]
## Problem description

Unable to reorder actions of an event by dragging the actions up or down or by using the right click options.

## Attach a .c3p

n/a

## Steps to reproduce

1. Tap on an action and try to drag up or down the list.
2. Nothing happens unless you hold it too long and right click menu opens.

OR

1. Tap and hold for right click options.
2. No options to move action up or down.

## Observed result

Nothing happens

## Expected result

Would love to be able to easily reorder actions without having to cut and paste them.

## Affected browsers

* Chrome: n/a
* Firefox: n/a
* Edge: n/a
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

iPad Pro (1st Gen)
iOS 11.0.3

</details>

**Comment by AshleyScirra** [comment]
This is currently by design because touch input is used for scrolling on mobile rather than drag-and-drop. We probably need to design a new mechanism for drag-and-drop since it's awkward to treat touch input the same way as mouse input.
