### ISSUE TITLE
Pause by changing timescale not working

### ISSUE THREAD

**Issue by KENYONBcom** [Scirra/Construct-3-bugs#975]
Pausing a game by pressing a sprite and changing timescale works once to pause and unpause, but will not work again.

## Attach a .c3p
I used the template endless runner to demonstrate the issue.
I am using a call function method that works in Construct 2.
[runner pause bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1424695/runner.pause.bug.zip)

## Steps to reproduce

1. run game
2. press pause button (it should pause)
3. press pause button (it should resume playing)
4. press pause again and nothing happens, game keeps playing.

## Observed result

Pause button only works once to pause and unpause. Clicking/touching only makes the character jump.

## Expected result

I expect the game to pause/unpause as many times as I press the button.

## Affected browsers

* Chrome: on desktop and mobile

## System details

n/a

**Comment by Scoremonger** [comment]
This looks like a bug in your event logic. In the "Pause_Controller" function you're testing if System _time_ is = 1.0, but you want to be testing the _timescale_ instead. Replace this condition with **System: compare two values**, and put "timescale" as the first value and 1 as the second, and your pause function should work fine.

![2017-10-28 22_59_03-clipboard](https://user-images.githubusercontent.com/28039905/32141098-a46a8316-bc34-11e7-92b5-91876ba3ffc8.jpg)

**Comment by KENYONBcom** [comment]
@Scoremonger you are correct. sorry, I was working too fast and had a brain fart. thanks for pointing that out. case closed.
