### ISSUE TITLE
8Direction disabled if second object uses it and created objects lose properties

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-3-bugs#977]
[CreateWithoutProperties_8waynotworkingonmultipleobj.zip](https://github.com/Scirra/Construct-3-bugs/files/1425133/CreateWithoutProperties_8waynotworkingonmultipleobj.zip)
## Problem description

I tried to reproduce a bug I had when I worked on my game. I created new sprites with 2 sine behaviors and bullet first, but bullet seems to disable sine so I switched to 8Direction for movement. Everytime I create a new sprite it had not the properties of the one already on the layout like it was in the past. Same sine settings etc. for all new created objects. It worked fine when I tried to make a test project to report the bug. **But in my game all new created sprites had the default values not my entered values for Sine and I had to add new actions to set the values after the create object command.**

While testing this I found another issue. When you enable Default Controls for 8Direction they suddenly stop working if you create a second sprite with 8Direction. Is this intended so only one object can use 8Direction default controls or a bug? I attached the project.

## Attach a .c3p

[CreateWithoutProperties_8waynotworkingonmultipleobj.zip](https://github.com/Scirra/Construct-3-bugs/files/1425134/CreateWithoutProperties_8waynotworkingonmultipleobj.zip)

## Steps to reproduce

1. create sprite
2. add 8direction
3. create new sprite with actions

## Observed result

controls stop to work (arrow keys)

## Expected result

both should be moving at the same time

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r64
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 1.2 gb (1.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
So following these steps to reproduce (not sure why yours are different):

1. Open provided project
2. Use arrow keys to see object moving
3. Click "Create new Sprite"
4. Use arrow keys to move sprites again

It works, but only if I click inside the canvas. After clicking the button, it has focus and by default all keyboard input goes to the button. When you click inside the canvas focus transfers back and keyboard input can move both sprites again. So I think this is just confusion over focus. Can you confirm that this explains what you are seeing?

**Comment by AshleyScirra** [comment]
@TheBl4ckSh33p ping - did you try this?

**Comment by TheBl4ckSh33p** [comment]
I tried preview and when I click on the canvas again it works. Browser Plugin > Focus may fix it if it happens in a game?

but I am still trying to reproduce the other issue where all new created objects have no settings and I need to set all params again via commands. Dont know why it works in the example but not in my game. :/

**Comment by AshleyScirra** [comment]
OK, so this is probably just an issue with focus. The repro steps mention the focus issue so closing. If you have a separate problem please file another issue.
