### ISSUE TITLE
Construct 3 - Crash When Trying To Copy Event Across Projects

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#98]
## Problem description

Construct 3 crashes when trying to copypaste an event into another project, which references instance variables that are not available inside the other project. I think the problem is basically C3 not checking for instance variables when copying events between projects, should be fairly easy to fix.

## Attach a .c3p

[Download](https://cdn.discordapp.com/attachments/225550155531812865/303877514118299648/C3_Crash_-_2_Projects_1_Event.zip) Files

## Steps to reproduce

1. Open both projects (blank & quere messages)
2. Copy the 2nd event from the "quere" eventsheet over to the "blank" eventsheet
3. Notice crash when pasting the event

## Observed result

Construct 3 crashes while copying an event from one project into another.

## Expected result

Construct 3 shouldn't crash while doing that and prevent me from doing so if something is missing.

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: TypeError: Cannot read property 'ǃbX' of null
Stack: TypeError: Cannot read property 'ǃbX' of null at Function.ǃJt (https://editor.construct.net/r18-2/components/editors/eventSheetView/eventSheetView.js:1:79563) at t.ǃQE (https://editor.construct.net/r18-2/components/editors/eventSheetView/eventSheetView.js:1:79458) at new t (https://editor.construct.net/r18-2/components/editors/eventSheetView/eventSheetView.js:1:79422) at Function.ǃs.ǃc (https://editor.construct.net/r18-2/main.js:2:227596) at window.ǃhz.ǃFy (https://editor.construct.net/r18-2/main.js:61:332822) at t.ǃJp (https://editor.construct.net/r18-2/components/editors/eventSheetView/eventSheetView.js:1:68823) at t.ǃJI (https://editor.construct.net/r18-2/components/editors/eventSheetView/eventSheetView.js:1:68735) at t.ǃJZ (https://editor.construct.net/r18-2/components/editors/eventSheetView/eventSheetView.js:1:68628) at new t (https://editor.construct.net/r18-2/components/editors/eventSheetView/eventSheetView.js:1:70404) at Function.ǃs.ǃc (https://editor.construct.net/r18-2/main.js:2:227596)
Construct 3 version: r18.2
URL: https://editor.construct.net/index.html
Date: Tue Apr 18 2017 14:55:10 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 264 s

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 32-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 670 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in r20. As you point out the instance variable is missing, so it will show an error message indicating which instance variable is missing.
