### ISSUE TITLE
R65 preview not working.

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#981]
## Problem description

Just updated to R65 and preview is just black. I've tried many files all is the same. I tried Debug preview but that wont load.

Reverting back to R64 fixes the issue.

## Attach a .c3p

Not file related.

## Observed result

Can't preview project.

## Expected result

Be able to previre project.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by tunepunk** [comment]
Can confirm. Happens on my Surface and my Mac as well. Only black screen when previewing.

**Comment by tunepunk** [comment]
https://www.dropbox.com/s/gstofu34qbbqngv/remote_preview.png?dl=1

I get this popup when trying remote preview.

**Comment by newman321** [comment]
same problem here

**Comment by AshleyScirra** [comment]
Just released r65.2 to address this. Can you confirm it is resolved?

**Comment by tunepunk** [comment]
Can confirm, preview working for me now in r65.2

**Comment by mOOnpunk** [comment]
Working again.

**Comment by AshleyScirra** [comment]
Thanks for confirming.
