### ISSUE TITLE
In Mac OS alt+left and alt+right work weirdly

### ISSUE THREAD

**Issue by valerypopoff** [Scirra/Construct-3-bugs#982]
## Problem description

In Mac OS when in any filed of Action or Condition parameters popup, pressing alt+left and alt+right makes construct go back and forth windows-wise, but it's supposed to make text cursor jump forwards/backwards words.

## Attach a .c3p

[Example.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1432503/Example.c3p.zip)

## Steps to reproduce

1. Edit the only action in a Layout sheet
2. Place text cursor in the end of the line "I hate when it does this"
3. Press alt+left

## Observed result

Construct opens an action list window for the "System" plugin as if I clicked "Back".

## Expected result

Text cursor jumps left to the beginning of the word "this"

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r65.2
Language setting: en-US

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 231 mb (3.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon HD 6750M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_get_buffer_sub_data_async
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Alt+Left/right is a deliberate shortcut to navigate back/forward. I guess we need to change the shortcut.

**Comment by AshleyScirra** [comment]
Changed the back/forward shortcuts to Alt+Shift+Left/Right for the next build, which leaves Alt+Left/Right to use the default function.
