### ISSUE TITLE
tilemaps showing differently 

### ISSUE THREAD

**Issue by insanesnake** [Scirra/Construct-3-bugs#987]
## Problem description

tilemaps not showing the correct tiles. whilst showing them in the constructor they show up completly different whilst testing. using different tile maps, as shown in the minimal project, none of them are showing the correct tiles for me except the one without spacing.

## Attach a .c3p

[the city.zip](https://github.com/Scirra/Construct-3-bugs/files/1439828/the.city.zip)

## Steps to reproduce
I'm honestly not entirely sure. I started making a map for a new project and it looked crooked immediately. the tilemaps without spacing seem to be fine though.

## Observed result
tilemaps showing different tiles when testing then in the constructor. 

## Expected result

tilemaps showing the correct tiles in comparison with the constructor

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in r66
