### ISSUE TITLE
Construct is not working offline at all

### ISSUE THREAD

**Issue by flipog** [Scirra/Construct-3-bugs#989]
## Problem description

The title pretty much sums it.

## Attach a .c3p

n/a

## Steps to reproduce

1. Try to use Construct 3 offline

## Observed result

Not working offline

## Expected result

Working offline

## Affected browsers

n/a

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Failed to fetch @ TypeError: Failed to fetch
Stack: TypeError: Failed to fetch
Construct 3 version: r65.2
URL: https://editor.construct.net/
Date: Fri Nov 03 2017 14:00:32 GMT-0200 (-02)
Uptime: 6.2 s

Platform information
Browser: Chrome
Browser version: 62.0.3202.75
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 0.800000011920929
Logical CPU cores: 2
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
C3 release: r65.2
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce 320M OpenGL Engine
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2047
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_disjoint_timer_query, EXT_frag_depth, EXT_shader_texture_lod, EXT_sRGB, EXT_texture_filter_anisotropic, WEBKIT_EXT_texture_filter_anisotropic, OES_element_index_uint, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_compressed_texture_s3tc, WEBKIT_WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBKIT_WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBKIT_WEBGL_lose_context

</details>

**Comment by newman321** [comment]
i tried it offline with r65.2 and it just works for me fine.

do you see a browser page saying page can not be loaded ?

**Comment by AshleyScirra** [comment]
Can't reproduce here either, it works fine offline. Note you need to wait for the "this version of Construct is ready to work offline" notification, otherwise it hasn't finished caching and won't work offline. If your repro steps do not include waiting for that notification to appear, then I will simply assume you didn't wait for that notification.
