### ISSUE TITLE
Construct 3 - Poor Loading Times Of Images On The Starting Page

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#99]
## Problem description

Whenever I start Construct 3 I'm able to notice that some of the images on the starting page didn't load in yet and usually take up to 15 seconds to load in.

This isn't an engine breaking issue and more of a convenience issue so not a high priority.

## Attach a .c3p (image in this case)

![poor loading](https://cloud.githubusercontent.com/assets/15656049/25132603/62d32a0c-244a-11e7-90ff-9393524488b6.PNG)

## Steps to reproduce

1. Start Construct 3 in Chrome "desktop" mode
2. Notice that some images are still not loaded in after 10-15sec.

## Observed result

It can takes up to 15sec. for images to load in on a 6000kbits Internet connection.

## Expected result

I want Construct 3 to look good immediately after it has finished loading.

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Nothing.

</details>

**Comment by AshleyScirra** [comment]
Made a few tweaks for r20. Let's review again when it's out.

**Comment by AshleyScirra** [comment]
r20 is out, can you try it again?

**Comment by TheRealDannyyy** [comment]
Just a slight improvement, maybe 1-2 seconds faster than before.

I don't know how the loading is handled but I'd recommend a system were Construct 3 keeps the old images, loads them in and updates them on the go.

It might also be worth mentioning that this affects the user experience more than I thought it would because it displays "Still loading editor" and prevents further actions such as loading or creating new projects.

With all that said, it still requires some improvements in my opinion.

**Comment by AshleyScirra** [comment]
Hmm... I'm seeing some weird results in the Chrome network tab. Some resources are taking way too long to load. I filed https://bugs.chromium.org/p/chromium/issues/detail?id=713738, hopefully a Chrome engineer can figure out what's going on.

**Comment by pixelmetal** [comment]
Another option would be to allow users to disable the start screen altogether, similar to Adobe products that provide a "display on startup" checkbox to hide/show data advanced users don't need to be reminded of time and again.

**Comment by TheRealDannyyy** [comment]
Not sure if you did some changes to this Ashley but I'm able to notice an improvement in r24.
Loading now takes only 5-8 seconds. I still won't consider this bug to be fixed though.

**Comment by AshleyScirra** [comment]
We didn't make any changes aimed at this in r24. Chrome 58 was released recently though so it may be that Chrome updated and made it a bit better. I bumped the Chromium bug to see if anyone's working on this at Google.

**Comment by AshleyScirra** [comment]
Pretty sure this does stem from Chrome judging by work going on in https://bugs.chromium.org/p/chromium/issues/detail?id=713738, so closing as this issue will now be followed up there.

**Comment by TheRealDannyyy** [comment]
Alright, well I hope they get this one fixed and include it in the next stable release. Thanks for reporting it to them again.

**Comment by TheRealDannyyy** [comment]
Don't know if it matters but this issue also occurs in the most recent C3 release when hiding the starting page. This basically confirms that it's an SW issue on startup in general and not caused by the starting page specifically.

**Comment by TheRealDannyyy** [comment]
@AshleyScirra I'm on Version 64.0.3282.119 of Chrome now and I can still reproduce this issue.
For some reason it worked fine for me in Canary v64 but not in the stable branch.

My best guess is that the fix didn't get into the stable branch yet, either way just a quick heads up.

**Comment by AshleyScirra** [comment]
The bug I referenced is still open (https://bugs.chromium.org/p/chromium/issues/detail?id=713738) so I would assume this will still be an issue until that is closed. It seems better than it was before in the latest Chrome versions though.

**Comment by TheRealDannyyy** [comment]
Can confirm that it's faster now but I also got a faster Internet connection so I'm not sure.
Anyway going to keep track of this until it's getting fixed I guess.
