### ISSUE TITLE
Cloud Save creates an empty file if filename field is clicked before saving

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-3-bugs#990]
## Problem description

When cloud saving (OneDrive, in my case - haven't checked the other services), if I click inside the "filename" field in the "save as" dialog, then click "save", a message appears saying "expected filename", and an empty file with the name entered is created, and the project isn't saved properly.

Edit: After entering this I found that the same thing happens if you create a new project, add some stuff to it, and then select "Save As" from the Menu or click the disk icon to save. However, after the first save attempt fails with "expected filename", hitting the save icon again will allow you to save the file by overwriting the old one. You can even click in the filename field before you do it, once Construct is in that state.

## Attach a .c3p

A new project is all that's needed to reproduce this.

## Steps to reproduce

1. Create a new project.
2. From the Menu, choose Project -> Save As -> Cloud Save.
3. In the Save As dialog, click inside the "filename" field.
4. Click the Save button.

## Observed result

A message prompt appears saying "expected filename", and an empty file with the name entered is created.

## Expected result

File should save normally.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r65.2
Language setting: en-US

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 72 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
I haven't been able to reproduce this, although I did find a slightly different issue which I've just fixed.
 
When I attempted to save on OneDrive it would fail outright if it was in the root folder, displaying an error like "required string". 

When you doing this what are you seeing inside the filename box before and after you click on it?

**Comment by Scoremonger** [comment]
I am using One Drive too, and yeah it looks like clicking inside the filename field no longer matters - just trying to save a new project in One Drive produces that error. So I imagine your question about what I see in the filename box is moot, but just in case: I see the project name that I assigned when creating the project both before and after I click inside the box. After I click there's a cursor blinking wherever I clicked, but otherwise nothing's different.

When I discovered the bug originally (which may have been a C3 version or so behind the one I actually wrote this up on), I'm pretty sure this could be done with an old project too: I could open an existing project, choose save as, save to cloud, click inside the filename field, then hit save, and the "expected filename" message appeared and an empty file would be created. 

One other note about the save dialog behavior from when I first encountered this - if I clicked inside the filename field after choosing "Save As" and hit backspace once, it would erase the entire filename. But I could click on the filename and add some characters to it - just hitting backspace would erase everything in the field. 

Anyway, that's fixed now too, so maybe you found the only remaining bug here.

**Comment by shortercode** [comment]
Wow, I have to say I've been searching through code and triple reading through some of the issues you've had and I honestly have no idea how some of this is happening. But I'm glad most of it seems to have resolved itself for you, let me know if any of these oddities comes back and I'll try to figure out what's going on!

With my fix for the issue preventing the creation of files on onedrive everything seems to be working fine here, so hopefully it will be fully functional for you once the next release goes out.

**Comment by Scoremonger** [comment]
You're not the only one questioning my sanity, believe me. ;) I do stand by these reports (especially the stuff I mentioned in the comment above - that was happening to me on multiple PCs), but for the record I think the bug I wrote about all my variables getting nuked (#[846](https://github.com/Scirra/Construct-3-bugs/issues/846)) was me staying up too late and doing something stupid, not a bug in Construct. I wanted to close that one but Ashley wouldn't allow it, ha ha.

**Comment by shortercode** [comment]
So that fix should now be out with r67, how does it work for you? 

I always try to keep an extra open mind, it's very easy to pass the buck onto someone else when you come across a problem. I think it comes down to people assuming code they've written is correct, but mistakes crop up in the weirdest of places!

**Comment by Scoremonger** [comment]
Yes, everything seems fine for me now, thanks. I've tried all the things that were causing trouble before and the projects are saving properly every time. :)

**Comment by shortercode** [comment]
Great news! Thanks for checking
