### ISSUE TITLE
Build failed with Mobile IAP

### ISSUE THREAD

**Issue by UeliSo** [Scirra/Construct-3-bugs#991]
## Problem description

The C3 server doesn't  build the project when you add the Mobile IAP.

## Attach a .c3p

[Test IAP.zip](https://github.com/Scirra/Construct-3-bugs/files/1443871/Test.IAP.zip)

## Steps to reproduce

1. Create a new blank project
2. Add Mobile IAP
3. Export (Android Cordova)
4. No export options marked
5. Debug APK

## Observed result

Error "Build failed. failed to build project"

## Expected result

Message with link to download package

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Server was resolving with an older version of the native plugin, that was broken. I've updated the server and this seems to be working now. Thanks for the report :)
