### ISSUE TITLE
(r66) Effects list not updated after adding effects.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#992]
## Problem description

There is no way to remove effects after they have been added. They don't show up in the list. This worked in 65.2 

## Attach a .c3p

N/A

## Steps to reproduce

1. Create a sprite and add an effect.
2. Check list again
3. Added effect is not in list.

## Observed result

effect list did not update after add.

## Expected result

Effect should be listed and able to be removed.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
Oops. One of our fixes for an undo crash in r66 accidentally caused this. Thanks for the report, it's corrected in r67. I guess we should get that out soon since this is an important feature.

**Comment by AshleyScirra** [comment]
Fixed in r66.2 which is out now.
