### ISSUE TITLE
Minor xpression editor graphical bug. (wordwrap)

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#995]
## Problem description

Unless you add some spaces to your expression the expression input box will look weird in some cases and has no wrapping. Very long expressions without spaces doesn't wrap well and can become hard to work with.

## Attach a .c3p

N/A

## Steps to reproduce

1. Go to the event sheet and edit an expression.
2. Create a long expression without spaces (ex by: copy sprite.x+sprite.x+ several times.
3. expression input box behaves strangely.

## Observed result

Since the expression has no spaces there's no where to wrap, and the expression will extend outside the expression editor popup. like this.
https://www.dropbox.com/s/3ard7z783uauka2/nowrap.png?dl=0

## Expected result

This is what it looks with spaces.
https://www.dropbox.com/s/kkvmc6rh7aipnxj/wrap.png?dl=0

Some kind of automatic wrapping for very long expressions would be good. Manually adding spaces here and there just for visibility can become a bit cumbersome at times.

Suggested wrapping points would be + - , etc.

## Affected browsers

* Chrome: yes

**Comment by tunepunk** [comment]
May I also suggest to give the expression editor a little bit more room? Looks a bit more tidy like this.

![expression_input](https://user-images.githubusercontent.com/27011641/32503759-5641d93a-c3de-11e7-8b00-673ca88d454d.gif)

**Comment by AshleyScirra** [comment]
That layout uses a lot less vertical height than your suggestion, which is better when you have a lot of parameters, especially with short values (e.g. just a number), or a small screen. Also let's keep to one item per issue, this report will deal only with word wrap.

**Comment by AshleyScirra** [comment]
Fixed wrapping for r67 - it will ensure long expressions with no spaces wrap instead of extending horizontally.
