### ISSUE TITLE
Spritefont dissapear

### ISSUE THREAD

**Issue by Ind1eed** [Scirra/Construct-3-bugs#998]
## Problem description

Spritefonts dissapear in preview mode  after managing it via events (that's important).

## Attach a .c3p

Appear (at least for me) in every .c3p You can do it by yourself.

## Steps to reproduce

1. Create new project.
2. Add new spritefont object.
3. Add new variable, and then make the font to display that variable.
4. The font should dissapear in preview mode.

## Observed result

Spritefont dissapear in preview mode.

## Expected result

Visible sprtefont.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce - tried it and it worked fine. Please always follow the guidelines and attach a .c3p to ensure we can fix the bug you are reporting.
